### ISSUE TITLE
[BUG] PFD/FMS/EICAS only turn on with external power. External/Battery power works intermittently.

### ISSUE THREAD

**Issue by JuicyDreamer** [flybywiresim/a32nx#1000]
**Mod Version**

v0.3.1

**Describe the bug**

PFD/FMS/ECIAS/MCDU do not power on with battery power, you must turn on external power. Additionally the battery power and external power only works intermittently meaning when I load into the world sometimes turning on batteries/external power does absolutely nothing.

**To Reproduce**

1. Load in at a gate
2. Turn on batteries (sometimes panel backlights will turn on as well as the radio other times nothing powers on.)
    2a. If batteries powered on the radio and panel lighting continue to step 3, if battery power didn't turn anything on restart by 
    reloading into the game and try again as external power will not function at this point either.
3. Turn on external power (PFD/FMS/ECIAS/MCDU will power on, only if the batteries were functioning in the previous step.
4. Finish start up procedures as normal.

**Expected behavior**

Turn on batteries and systems will boot up and then turn on external power if/when it is available.

**Actual behavior**

Turn on batteries sometimes nothing happens and you must continue to reload into the world until it decides to function. When it decides to function only the backlighting and radio power on and nothing else works until you have external power.

**References**

**Additional context**

Issue persists regardless if other mods are installed or not.

Was this working before/when did the issue start occurring?
I noticed it after patch 1.8.3.0 was released.

Is this a problem in the vanilla unmodded game?
Intermittent battery/external power is an issue in the vanilla game. But when they do work in the vanilla game the batteries power up everything.

Discord username (if different from GitHub):

**Comment by wpine215** [comment]
It is intended behavior for the displays not to turn on solely on battery power - it is also the case for the real aircraft.

As for the external power/batteries both not working whatsoever, please make sure you are flying with all ground/airport/air traffic set to OFF, and if you're flying online, use generic models for other users. This was a problem introduced in the MSFS update 1.8.3 with variable leaking between planes, and these instructions are clearly labeled in the changelog.
