### ISSUE TITLE
[BUG] Speed set to MACH after cruise alt reached

### ISSUE THREAD

**Issue by visualcookie** [flybywiresim/a32nx#1002]
**Mod Version**

Stable: 0.3.1

**Describe the bug**

After reaching the cruise altitude, the speed sets itself to MACH and can't be reset by pressing the SPD MACH button.

**To Reproduce**

1. Start a game with a flightplan imported from STKP or SimBrief
2. Climb to cruise alt
3. See the change to MACH on the PFD

**Expected behavior**

This should not happen at all and if so, you shall be able to change it back to knots.

**Actual behavior**

The above described.

**References**

![image](https://user-images.githubusercontent.com/1857554/94723788-957e7f00-0359-11eb-901f-bf7bdd4e3959.png)

**Additional context**

Was this working before/when did the issue start occurring?
Was working fine before. Occured after the 3rd patch and your release of 0.3.1, where you reversed that workaround.

Is this a problem in the vanilla unmodded game?
Not tested yet.

Discord username (if different from GitHub): unicornhunter

**Comment by hralou** [comment]
Hi,
the switchover to mach is a normal behaviour I believe.

In managed speed, at the crossover altitude, the FMGC automatically changes the managed speed target to the corresponding MACH target. The FCU displays the Mach number corresponding to the speed at the switching altitude.

When the speed is selected, the flight crew has to perform the switching manually by pressing the SPD/MACH pb on the FCU The FCU then displays the aircraft Mach number.

![A320 speed_mach control](https://user-images.githubusercontent.com/72165750/94734459-8ef80380-0369-11eb-8aab-e1ce8a61e1d6.JPG)

**Comment by visualcookie** [comment]
@hralou That's not the correct thing according to the issue. This is just a description of how the "SPD MACH" switch works, there is nothing that says "changes speed unit from knots to mach at cruise alt". Also: nope, that can't be it, since in the EU we measure airspeed in knots.

**Comment by fourdragons** [comment]
So the managed mode works differently in the US vs EU? Weird.

**Comment by FlyingCarpet7** [comment]
In climb and in managed speed mode the FMA will announce SPEED up to the speed/Mach crossover point as described above. After that it changes to MACH.
It is only in selected mode you can use the SPD-MACH pushbutton to change if you want to select a speed in knots or Mach.
The attached picture of the PFD displays a managed speed mode, hence you are not able to use the SPD-MACH pushbutton in this case. 
So, I am not sure about what is the original bug reported here. Was the automatic changeover from speed to Mach happening just as reaching cruise at FL350? Think we need more input here.

**Comment by visualcookie** [comment]
> In climb and in managed speed mode the FMA will announce SPEED up to the speed/Mach crossover point as described above. After that it changes to MACH.
> It is only in selected mode you can use the SPD-MACH pushbutton to change if you want to select a speed in knots or Mach.
> The attached picture of the PFD displays a managed speed mode, hence you are not able to use the SPD-MACH pushbutton in this case.
> So, I am not sure about what is the original bug reported here. Was the automatic changeover from speed to Mach happening just as reaching cruise at FL350? Think we need more input here.

I gave all the info I had.

The following is in the description of the issue at the top:
> After reaching the cruise altitude, the speed sets itself to MACH and can't be reset by pressing the SPD MACH button.

I can also not change it back when in selected mode at cruise alt.

**Comment by Watsi01** [comment]
> @hralou Also: nope, that can't be it, since in the EU we measure airspeed in knots.

Not to question your knowledge. Do you have any reference for that? As far as I know, mach speed is also common in Europe.

**Comment by visualcookie** [comment]
> > @hralou Also: nope, that can't be it, since in the EU we measure airspeed in knots.
> 
> Not to question your knowledge. Do you have any reference for that? As far as I know, mach speed is also common in Europe.

As stated on the following links, `MACH` is used for highspeed planes, which, as far as I know, the A320 isn't. For the Concorde it would make sense to use `MACH` for airspeed.

https://aviation.stackexchange.com/questions/2566/what-is-the-measurement-system-used-in-the-aviation-industry
https://aviation.stackexchange.com/a/12574

**Comment by Watsi01** [comment]
> 
> 
> > > @hralou Also: nope, that can't be it, since in the EU we measure airspeed in knots.
> > 
> > 
> > Not to question your knowledge. Do you have any reference for that? As far as I know, mach speed is also common in Europe.
> 
> As stated on the following links, `MACH` is used for highspeed planes, which, as far as I know, the A320 isn't. For the Concorde it would make sense to use `MACH` for airspeed.
> 
> https://aviation.stackexchange.com/questions/2566/what-is-the-measurement-system-used-in-the-aviation-industry
> https://aviation.stackexchange.com/a/12574

You don't have to fly over mach 1 to be a highspeed plane. The reason for using mach is, because it's more accurate from a specific altitude on.

See here a typical EU flight:

https://youtu.be/j9p5AORcY8o?t=1269

**Comment by Mehlsocke** [comment]
> > > @hralou Also: nope, that can't be it, since in the EU we measure airspeed in knots.
> > 
> > 
> > Not to question your knowledge. Do you have any reference for that? As far as I know, mach speed is also common in Europe.
> 
> As stated on the following links, `MACH` is used for highspeed planes, which, as far as I know, the A320 isn't. For the Concorde it would make sense to use `MACH` for airspeed.
> 
> https://aviation.stackexchange.com/questions/2566/what-is-the-measurement-system-used-in-the-aviation-industry
> https://aviation.stackexchange.com/a/12574

Wrong wrong wrong

MACH has to be used in upper flightlevels die aerodynamic limiting reasons. All planes use Mach worldwide in upper flightlevels.

Best regards from a real Pilot...

**Comment by FlyingCarpet7** [comment]
I tested the SPD/MACH pushbutton now and it is not working in selected speed mode above the Mach transition level. That is something that needs to be fixed eventually.

**Comment by visualcookie** [comment]
> I tested the SPD/MACH pushbutton now and it is not working in selected speed mode above the Mach transition level. That is something that needs to be fixed eventually.

That was the whole intention. :)

> > > > @hralou Also: nope, that can't be it, since in the EU we measure airspeed in knots.
> > > 
> > > 
> > > Not to question your knowledge. Do you have any reference for that? As far as I know, mach speed is also common in Europe.
> > 
> > 
> > As stated on the following links, `MACH` is used for highspeed planes, which, as far as I know, the A320 isn't. For the Concorde it would make sense to use `MACH` for airspeed.
> > [aviation.stackexchange.com/questions/2566/what-is-the-measurement-system-used-in-the-aviation-industry](https://aviation.stackexchange.com/questions/2566/what-is-the-measurement-system-used-in-the-aviation-industry)
> > [aviation.stackexchange.com/a/12574](https://aviation.stackexchange.com/a/12574)
> 
> Wrong wrong wrong
> 
> MACH has to be used in upper flightlevels die aerodynamic limiting reasons. All planes use Mach worldwide in upper flightlevels.
> 
> Best regards from a real Pilot...

Your 3 wrongs there are kinda toxic. I'm not a pilot and this issue was flagged for pilot input, since I discovered it since patch 3 and A32NX 0.3.1 patch.

Instead of screaming 3x wrong, you could've just clarified the entire thing, how it works correctly and when it turns to MACH and if you are able to turn it back to KNOTS when pressing the SPD/MACH button, instead you just scream and not clarify anything about the aircraft, like @lousybyte flagged.

**Comment by fourdragons** [comment]
Making definitive statements that are incorrect will get people upset. (I have more to say, but I don’t want to get banned.)

**Comment by visualcookie** [comment]
@fourdragons Definitive statements I took from the internet, where I get my sources from. So if you get upset over something people found on the internet and think is wrong, then you could give a clearer description on how it works correctly, instead of blaming someone who doesn't know better and uses sources found on the internet.

And since I can't bother with any of this anymore, I ain't reporting no more bugs on this mod. Sad, that the community overall turns into a toxic place, when something like this happens.
