### ISSUE TITLE
Make build.py have same output when ran in CI or locally on Windows

### ISSUE THREAD

**Issue by AdenFlorian** [flybywiresim/a32nx#1004]
build.py outputs different file sizes and different file order when ran in CI versus run locally on windows. Ideally they would have the same output given the same input.

**Comment by AdenFlorian** [comment]
@2hwk in case you're interested in taking a shot at this.

**Comment by 2hwk** [comment]
I'll take a look but I need to fix the ISI, last update broke quite a bit of my code

**Comment by 2hwk** [comment]
Also while I am at it maybe it would be good to restore python 2 compatibility to help QA out.
