### ISSUE TITLE
Excessive pitch on approach/Lack of elevator control and engine response[BUG]

### ISSUE THREAD

**Issue by joniatus** [flybywiresim/a32nx#1005]
**Mod Version**

latest master 

**Describe the bug**

When on approach the plane is at about a 10° pitch up if holding altitude.  With AP off and AT on, if you try to pitch up, even with full stick deflection, there is no response.  It seems like the engines are not spooling up properly to provide additional thrust needed.  It took 22 seconds for the engines to go from 45-55%.  Eventually when the engines spool up enough the plane will begin to pitch up assuming you haven't hit the ground yet.  Didn't matter if selected or managed speed was used

**To Reproduce**

1.  Put plane in landing configuration
2.  Disconnect AP, leave AT on
3.  Try to pitch up

**Expected behavior**

Engine response need to be much faster to allow plane to gain altitude

**Actual behavior**

If you are descending and pull the stick fully aft, then plane will continue to descend for another 20-25 seconds waiting on engines to catch up

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Only stated happening after patch

Is this a problem in the vanilla unmodded game?
No, I tested on vanilla and engines responded approriately

Discord username (if different from GitHub):
Jon D

**Comment by mehupalli** [comment]
I have the same problem. I was able to repeat the problem. Also rolls hard when landing.

**Comment by sebby1983** [comment]
Same for me too, almost uncontrollable when flying a manual approach

**Comment by MICHER79** [comment]
Hello, I have the same problem, plane uncontrollable on manual approach

**Comment by Pheome** [comment]
Same issue,it exists before 1.9.3,I noticed that if I raise approach speed from 140 to around 150 knots than I have pitch control again.

**Comment by joniatus** [comment]
Never had this issue before latest patch but yes if you use a selected speed above 150 it will pitch up however engine response is still slow and you will be limited again once speed falls to 140 again waiting on engines

**Comment by blastertwist** [comment]
Same issue, even before the last patch the nose pitching up so high in approach when the VAPP around 140 to 150 knots.

**Comment by joniatus** [comment]
Please also see issue #1014 as I believe they are related

**Comment by OVI-7** [comment]
I have the same bug. Pitch too much at 10 degrees, when AP off the plane doesn’t react on the side stick pitch movement and stalls. I did landing at Vls+5 speed upon the speed bug (138 kts) . Checked in the vanilla Bus - no problem there.

**Comment by joniatus** [comment]
Video of issue [https://youtu.be/dq7egGPB_jg](url)  Again this only happens in mod

**Comment by joniatus** [comment]
Closed as issue we resolved with pr 1029
