### ISSUE TITLE
[BUG] AP fails to climb after take off in managed mode, also fails to descend. Open descent behaves weird.

### ISSUE THREAD

**Issue by AndLindemann** [flybywiresim/a32nx#1008]
**Mod Version**

master

**Describe the bug**

AP has trouble with climbing and descending. Managed ALT mode sometimes doesn't work. In Open descent and THR IDLE, plane is climbing instead of descending.

**To Reproduce**

1. I started in Brussels, on the runway, plane ready for flight, flightplan set to land in Schiphol, NL. Normal take off, pretty much just deactivated parking brake and set throttle to TOGA.
2. Shortly after take off, throttle back to CL gate, switched on managed ALT mode with an altitude set to 6.000 feet - at that time, plane was around 2.000 feet AGL.
3. -> managed ALT mode did not turn on. PMD shortly flashed the ALT indicator but then went blank again and ATHR stays in SPEED mode.
4. After the first few minutes, possibly when passing the first waypoint, managed ALT mode begins to work as expected.
5. Later in the flight when instructed to descent by ATC, coming from FL10 I set ALT to 6.000 feet again and engaged managed ALT mode, but again it would not turn on and only shortly flash on the PMD.
6. I then switched to open descent to start descending, and as expected ATHR goes into THR IDLE. Looking back at the instruments a minute later, the plane has CLIMBED to 14.000 feet while still showing THR IDLE, yet looking at the engine stats, it is actually at full throttle (while the actual throttle is correctly at the CL gate).

**Expected behavior**

1. Before the patch I'm pretty sure I could engage managed ALT mode more or less directly after take off and it would happily take over climbing at THR CLIMB.
2. Also for descending, managed ALT mode worked fine before the patch.

**Actual behavior**

1. Managed ALT mode did not climb after take off, instead it could not be switched on and ATHR stays in SPEED mode.
2. Managed ALT mode did not descend, could not be switched on. 
3. Open descent seemed to show up correctly on PFD, but instead of descending, the plane actually started to climb with full power to the engines while PFD shows THR IDLE, see screenshot.

**References**

![20200930222340_1](https://user-images.githubusercontent.com/4157845/94736729-fd8a9080-036c-11eb-8dbd-3222344d834e.jpg)

**Additional context**

Was this working before/when did the issue start occurring?
MSFS 1.9.3 patch

Is this a problem in the vanilla unmodded game?
Did not check.

Discord username (if different from GitHub):
Phiolin#2315

**Comment by Emile31** [comment]
I think I have the same issued. I push on the ALT button but nothing happened.
I can only use the SELECTED altitude and not the MANAGED one.

**Comment by MisterChocker** [comment]
open decent still has issued, closing since all issues listed are either fixed or covered by another issue
