### ISSUE TITLE
[BUG] accel speed, n/d following issue. 

### ISSUE THREAD

**Issue by ducky3333** [flybywiresim/a32nx#1009]
**Mod Version**

0.3.1
![fix_Microsoft Flight Simulator Screenshot 2020 10 01 - 08 54 58 30](https://user-images.githubusercontent.com/38446386/94751749-3bff6a00-03c4-11eb-8779-2cad7da665fc.jpg)
![fix_Microsoft Flight Simulator Screenshot 2020 10 01 - 08 55 19 15](https://user-images.githubusercontent.com/38446386/94751752-3dc92d80-03c4-11eb-9ddc-8c47138486ca.jpg)

**Describe the bug**

1. after take off , mcp manage speed had set to 138. 

so cannot climb from 2000ft.  autothrottle not increasing from idle because maniging speed was 138 knot. 

i v set take off accel ALT was 3000ft.

2. the aircraft have to follow n/d route like circle , but the system skipped circle route.

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment]
fixed by now
