### ISSUE TITLE
APU EGT temps should start between 0-4 degrees above ambient OAT

### ISSUE THREAD

**Issue by michaeldiguiseppi** [flybywiresim/a32nx#101]
Usually depends on length of time sitting shut down, but we can use a random number betewen 0 and 4 degrees off to be "realistic."

**Comment by AdenFlorian** [comment]
Is this before turning on the APU MASTER switch?

**Comment by michaeldiguiseppi** [comment]
So when the APU starts, and the gauges show, but before they start climbing, the EGT temp should start between 0 and 4 degrees above the ambient temp.  Currently i think it always starts at like, 10 or 15 degrees or something like that. (im not sure of the actual numbers but i know that the numbers seem to be the same every time regardless of OAT)

**Comment by AdenFlorian** [comment]
I'm hoping to get to this today

**Comment by paul92ilm** [comment]
This issue looks to be fixed.
With the master APU ON, I can see that EGT follow the AT
I tried to change Weather Temp and EGT adapt accordingly
LGTM, I think this issue can be closed

**Comment by tareksabet** [comment]
issue fixed
