### ISSUE TITLE
[BUG] Flight Level Entered in INIT page does not calculate in FLT PLN page. 

### ISSUE THREAD

**Issue by emadera80** [flybywiresim/a32nx#1011]
**Mod Version**

Current Version release 9/30/2020

**Describe the bug**

hello in the Flight plan mod the FMS does not calculate the cruise altitude it will remain blank or null.  It appears that when we enter a flight plan in the INIT page it does not calculate the flight level.  Also it does not calculate a top of decent.  

![image](https://user-images.githubusercontent.com/61091940/94754900-a54d9180-0360-11eb-8f8a-a281d5d97440.png)

**To Reproduce**

1.
2.
3.

**Expected behavior**

I like to see the flight level and corresponding altitude and speed restrictions on the FLT PLN page. 

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by lousybyte** [comment]
Related #307, #436.

**Comment by MisterChocker** [comment]
partly fixed by now, current issue is not toc and descent being calculated. but closing since it's already being worked on and has other issues for tracking.
