### ISSUE TITLE
[BUG] ND/PFD/ECAM Self-Tests if Brightness Knob Reduced to Zero

### ISSUE THREAD

**Issue by efortier-95** [flybywiresim/a32nx#1012]
**Mod Version**

v0.3.1 Stable

**Describe the bug**

If the brightness knob controlling the brightness of the PFD, ND, or ECAM is reduced to zero, upon increasing the brightness the screen will enter the Self Test mode

**To Reproduce**

1. Make sure screen is displaying content required (e.g., PFD shows PFD display)
2. Reduce Brightness to Zero
3. Increase Brightness

**Expected behavior**

Screen doesn't undergo Self-Test

**Actual behavior**

Screen undergoes self test

**References**

**Additional context**

Was this working before/when did the issue start occurring?
It's been an issue as far as I remember.

Is this a problem in the vanilla unmodded game?
Self test doesn't exist in vanilla game

Discord username (if different from GitHub):
Eefoe#0570

**Comment by lousybyte** [comment]
Same as #945.

**Comment by NathanInnes** [comment]
Closing as this is a duplicate isssue.
