### ISSUE TITLE
[REQUEST] Strobe Light pulses to illuminate cloud and ground

### ISSUE THREAD

**Issue by efortier-95** [flybywiresim/a32nx#1013]
**Is your feature request related to a problem? Please describe.**

No

**Describe the feature you'd like to see implemented**

The strobe lights should be capable of illuminating the surrounding clouds if one is inside cloud. Strobes are **very** high powered lights. In fact, some operators recommend turning the strobe lights off when in IMC to prevent the pilots from being disoriented. 

Right now, the strobe lights are just tiny dots on the wingtips. They should be far more obnoxious.

**References**

https://www.youtube.com/watch?v=7tnd-prQXgE

**Additional context**

Discord username (if different from GitHub):
Eefoe#0570

**Comment by NathanInnes** [comment]
Include a reference if you can so people can try and get an idea on how intense it should be

**Comment by efortier-95** [comment]
I found one here, though the strobe pattern seems slightly different. It should give a good idea of how powerful the strobes typically are on an A320neo (give or take a bit):
https://www.youtube.com/watch?v=7tnd-prQXgE

Not sure what other kind of info I can provide; I don't have access to any technical data to pin down exact wattage of the light.
