### ISSUE TITLE
[BUG] Takeoff and landing stall speeds are faster

### ISSUE THREAD

**Issue by hotshotp** [flybywiresim/a32nx#1014]
**Mod Version**
Stable 0.3.1

**Describe the bug**
During takeoff, before 0.3.1 I was about to take off at about 130 knots very easily and smoothly. Now, if I take off at 130 knots my main landing gear doesn't leave the ground and when it does it almost always stalls. I have to reach speeds of about 160 to smoothly take off. Furthermore, the regular approach speed that I use is about 140 knots. At 140 knots now, I am not able to even raise the nose, the plane just falls out of the sky. This is a problem that I have seen a few other people on the discord complain about.

**To Reproduce**

1. Either take off or get on an approach
2.Use your regular takeoff/approach speeds
3. Observe the strange behaviour

**Expected behavior**

You are supposed to be able to take off at about 130 knots and approach at about 140 knots without problems.

**Actual behavior**

At 130 knots the main landing gear doesn't even lift off the ground. At 140 knots on approach you can't even control your pitch anymore.

**Additional context**

Was this working before/when did the issue start occurring?
It was working fine with the 0.3.0 release AFTER the MSFS update. While I had no screens, I could see my speed in external view and everything worked as it should. When I downloaded 0.3.1, this problem started happening.

Is this a problem in the vanilla unmodded game?
I haven't checked, but as said above, this didn't happen on 0.3.0 AFTER the update but only after I downloaded 0.3.1

Discord username (if different from GitHub):
Boris#9134

**Comment by XiaNaphryz** [comment]
What was your aircraft weight, and what does the MCDU say for your V1/VR/V2 speeds on the Take Off Perf page? And does clicking on the buttons next to the V speeds generate updated target speeds?

**Comment by donstim** [comment]
Are you using speeds from the FMC or from some other source that are known to be correct for your takeoff weight? 

I just did a takeoff from KDCA in Config 1+F at 134,000 lb takeoff weight and VR of 118 and V2 of 121.  I should say I tried to conduct a takeoff with those parameters. I can at least partially confirm there seems to be some kind of issue with this latest master build. Although I don't know if it was a stall, I crashed on takeoff on the first 2 of 3 attempts, with the airplane refusing to climb away after liftoff. It's possible there could have been a trim issue as I did not check my takeoff trim setting. I am used to needing to really pull through after takeoff, but not to this degree.

**Comment by yunnypuff** [comment]
I have the latest stable release 0.3.1

The 140knot stall behavior is very apparent in any of the landing challenges involving the A320. I can't keep my plane in the sky with my throttle set to CLB (it just displays SPEED instead of THR/CLB), auto throttle is on. Engine only revs at 35% ish instead of giving me more power to maintain my altitude.

Conversely, I've had at least one experience where I managed to lower myself to 20ft, "RETARD" call is out. I set my throttle to 0 (IDLE is displayed), but the engine still revs at 70-80% power while I'm on the ground, preventing me from stopping. I've repeatedly set the throttle to 0 w/o any effect.

These issues do not occur in any of the landing challenges after removing the mod.

**Comment by bisinchi** [comment]
Same issue, I used computed speeds from FMC (updated with flap setting), for a Vr of 135, I rotate normally, no issue, but the plane wouldn't fly until reaching 160kts. Then in flight, I notice that the alpha prot speed is actually higher than the V2 speed.

**Comment by tankedman** [comment]
Can confirm that I'm only experiencing this issue with release version 0.3.1 installed. Even in an empty plane with only fuel onboard, often on approach at around about 145kts the aircraft loses lift and starts to stall, without any stall warning. Even on an ILS approach with autopilot at around 150kts, it struggles to maintain lift and pitches up +10 degrees. Tested this on multiple landings (landing challenges and world map) and was easily reproducible.

Default Asobo a320 does not have these issues.

**Comment by joniatus** [comment]
Yes can confirm as others have stated. Imo this needs to be top priority as the plane is unflyable in this state and seems to be specific to the mod or at least worse than vanilla in this regard

**Comment by hotshotp** [comment]
> What was your aircraft weight, and what does the MCDU say for your V1/VR/V2 speeds on the Take Off Perf page? And does clicking on the buttons next to the V speeds generate updated target speeds?



> Are you using speeds from the FMC or from some other source that are known to be correct for your takeoff weight?
> 
> I just did a takeoff from KDCA in Config 1+F at 134,000 lb takeoff weight and VR of 118 and V2 of 121. I should say I tried to conduct a takeoff with those parameters. I can at least partially confirm there seems to be some kind of issue with this latest master build. Although I don't know if it was a stall, I crashed on takeoff on the first 2 of 3 attempts, with the airplane refusing to climb away after liftoff. It's possible there could have been a trim issue as I did not check my takeoff trim setting. I am used to needing to really pull through after takeoff, but not to this degree.

I tried using an empty plane. And I did not use the MCDU speeds, I was testing my ground roll sounds over and over and that was me just spawning on the runway over and over and taking off. The performance of the aircraft is still really bad for some reason.

**Comment by DoToAdventures** [comment]
I nailed this down to be something related to the flightmodel.cfg, I will invest further.

**Comment by donstim** [comment]
Can see the differences between flight model cfg for the mod vs base. Can I simply revert the relevant changes in the mod cfg, or will that not work because of the json files?

Also, is the bases for the changed values in the flight model cfg file documented somewhere?

**Comment by davidnorfolk96** [comment]
Following

**Comment by AK-777** [comment]
Yes that's true the airplane don't have enough lift in low air speed and this problem is presented because of completely wrong airplane peformance numbers in flight model file i tried to customize it and 'yes' it's become way more stable in flying and i found also triming effect landing flare because at 30 ft above the ground the autotriming will push the airplane soo hard to the ground this true system reaction in real life but in sim is too fast that make the plane touch the ground very hard .

**Comment by lousybyte** [comment]
Any impact on #984, #1034 or unrelated?
