### ISSUE TITLE
[BUG] Managed speed on PERF page not the same as actual speed

### ISSUE THREAD

**Issue by AndersHogqvist** [flybywiresim/a32nx#1018]
**Mod Version**

1.3.1

**Describe the bug**

I've noticed that the speed mentioned under MANAGED on the CRZ PERF page is always higher than the speed in which the aircraft is actually flying

**To Reproduce**

1. Start a flight and fly in managed mode
2. After reaching cruising altitude, compare the the indicated speed with the speed shown on the PERF page

**Expected behavior**

The speed at which you're flying should be the same as the speed shown on the PERF page

**Actual behavior**

The speed in which you're flying is lower than the speed shown on the PERD

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment]
fixed by now
