### ISSUE TITLE
[BUG] Speed occasionally drops to zero

### ISSUE THREAD

**Issue by AndersHogqvist** [flybywiresim/a32nx#1019]
**Mod Version**

1.3.1

**Describe the bug**

At several occasions now the speed has suddenly dropped while in cruising phase.

**To Reproduce**

1. Start a flight in managed mode and proceed to the cruising phase

**Expected behavior**

Speed should stay relatively stable

**Actual behavior**

Sudden drops to 0kt and then it goes back to normal after a little while

**References**

https://app.box.com/s/0t2dqndzubjw9ewkwalm1g0b9dng4422

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by NathanInnes** [comment]
Known issue. Most likely scenario was that the Probe froze over. It's supposed to be auto by default but it's currently set to off. Just turn on probe anti ice, etc..
