### ISSUE TITLE
[BUG] One LDG light switch extends both halfway

### ISSUE THREAD

**Issue by liebbe10** [flybywiresim/a32nx#1022]
**Mod Version**

master

**Describe the bug**

If you use one LDG light switch and set it to on while leaving the other one in off both extend halfway.

**To Reproduce**

1.Power up the Acft
2.Use only one LDG light switch

**Expected behavior**

Only one of them should extend fully.

**Actual behavior**

Both extend halfway.

**References**

![Screenshot 2020-10-01 205239](https://user-images.githubusercontent.com/30324171/94851425-b9f55c80-0428-11eb-9296-754f63e5b20c.png)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
Probably, not checked.

Discord username (if different from GitHub):

**Comment by NathanInnes** [comment]
Do you have one side retracted on the switch?

**Comment by lukecologne** [comment]
Can confirm, one switch extends both halfway, and when both switches are on, both landing lights extend fully. I think the problem is that both animations have the same name. They are seperate animation when viewed in blender, but their name is the same, so both get extended at the same time

**Comment by komp1821** [comment]
Confirmed. Checked it in the unmodded version as well. Same behavior.

**Comment by liebbe10** [comment]
> Do you have one side retracted on the switch?

Yes one side was in retract and the other in off.
![Screenshot 2020-10-01 211438](https://user-images.githubusercontent.com/30324171/94853094-25402e00-042b-11eb-8018-6a7f513efc93.png)
