### ISSUE TITLE
[BUG] ILS does not appear/work with selected RWY

### ISSUE THREAD

**Issue by liebbe10** [flybywiresim/a32nx#1024]
**Mod Version**

master

**Describe the bug**

When selecting an ILS approach it won't show up on the PFD and the Autopilot won't capture the ILS. When entering the frequency and course manually in the VOR section of the RAD/NAV page the autopilot will follow the ILS but there still won't be an indication

**To Reproduce**

1. enter an ILS approach into the FMS
2. fly on rwy heading, activate the LS button and try to activate the APPR button

**Expected behavior**

FMS should tune the ILS and display it on the PFD. Autopilot should follow the ILS

**Actual behavior**

RAD/NAV page shows the right ILS selected but there is no indication and autopilot won't catch the LOC or G/S. After entering the frequency and crs manually the AP works but there is still no indication

**References**

FMS has the right RWY selected (ILS34 in LOWW):
![Screenshot 2020-10-01 203725](https://user-images.githubusercontent.com/30324171/94852432-2ae94400-042a-11eb-8368-bc007a5f0353.png)

Autopilot still in NAV and ALT:
![Screenshot 2020-10-01 203741](https://user-images.githubusercontent.com/30324171/94852438-2d4b9e00-042a-11eb-8b0b-f11c48957404.png)

Manual entry of the freq and CRS:
![Screenshot 2020-10-01 203840](https://user-images.githubusercontent.com/30324171/94852448-2e7ccb00-042a-11eb-9fe7-d3c50774fcfb.png)

Now autopilot captures the LOC but no indication:
![Screenshot 2020-10-01 203854](https://user-images.githubusercontent.com/30324171/94852452-30468e80-042a-11eb-9870-a48deb46c141.png)

**Additional context**

I know there is a similar Bug reported, but it sounded a bit different. (Wrong RWY selected by the FMS)

Was this working before/when did the issue start occurring?
Since V3 of the Airbus
Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by donstim** [comment]
It looks like you put the ILS frequency into the wrong field. You put it in as a VOR frequency. It should go in the ILS field, which would then say ILS 34/108.10.

**Comment by liebbe10** [comment]
> It looks like you put the ILS frequency into the wrong field. You put it in as a VOR frequency. It should go in the ILS field, which would then say ILS 34/108.10.

True, but I couldn't edit the ils freq and it should have been preselected by the fms automatically after selecting the ils approach in my route. Putting it in the VOR slot was just to try, if I could still capture the localizer.

**Comment by visualcookie** [comment]
@liebbe10 A lot should have been automated in the sim, so does INIT B. The thing is, that I believe the devs of this mod can't fix this, as it is an issue with the FMS of the base aircraft, that needs fixing from Asobo, or Asobo could just give the devs permission/access to edit the aircrafts deeper model/metadata.

(Correct me if I'm wrong. That's what I read from a lot of Discord messages from the devs.)

**Comment by donstim** [comment]
I just set up a flight from Vienna to LOWI, and on the ground in Vienna it looks fine to me. I am using Navigraph nav data, though.
![Screenshot (22)](https://user-images.githubusercontent.com/70166617/94872138-acc47780-0400-11eb-9042-e34c0890cdc2.png)

**Comment by liebbe10** [comment]
I tried it again starting in LOWI
1. set up dep/dest on the init page
2. set the ILS 34 arrival in LOWW
Still it enters the ILS34 in the RAD/NAV section but no freq. I can enter the freq manually now in the fms though...

Not using Navigraph but the standard MSFS data and not entering a flight plan in the Main Menu, only Dep LOWI and then entering the Flightplan directly into the FMS in the ACFT.
I only wonder, because with v2 of the A320 it was working for me. I only had the problem since v3

![1](https://user-images.githubusercontent.com/30324171/94897885-d3ca8a00-0490-11eb-86cf-d23a0357df7c.png)
![2](https://user-images.githubusercontent.com/30324171/94897888-d5944d80-0490-11eb-96aa-a5eaa423020f.png)
![3](https://user-images.githubusercontent.com/30324171/94897891-d6c57a80-0490-11eb-9167-c571e1877f6b.png)
![4](https://user-images.githubusercontent.com/30324171/94897892-d75e1100-0490-11eb-8650-a3988be86e47.png)

**Comment by lousybyte** [comment]
There's a known issue with the base game since launch, ILS indication on the PFD can just randomly fail even for the same runway. It will display correctly on the ND if you switch from ARC to LS.

**Comment by lousybyte** [comment]
Might be related #975.

**Comment by liebbe10** [comment]
Just tested it out again. The PFD works for me now. The problem was that I used the wrong format for the ILS freq to override it manually (I tried "/108.1" but it only accepts "108.1") and therefore entered it in the VOR slot, so no ILS indication on the PFD. With the right freq in the ils slot it works. (So my mistake)

Still frustrating is that the FMS knows the ILS rwy but does not preselect the freq for me. A feature that worked for me in previous versions of the mod. Therefore I wondered if something broke this functionality in newer Versions since v3

**Comment by theersink** [comment]
By any chance are you using the marketplace payware version? I have noticed and think it may be a bug with these is if you have a payware version it will not automatically tune the ILS frequency. I get the same with KDEN, default msfs works fine but as soon as I install the upgraded airport it refuses to auto tune the frequency. With Kden ther is also an ils offset that flightbeam is aware of in marketplace versions. 
Just a thought this might be related. I don't have LOWW from the marketplace so I can't confirm.

**Comment by XiaNaphryz** [comment]
I just ran into something similar to land into Cairo (airport code HECA) on runway 05R...on final when I enabled the LS display no diamonds appeared for the localizer or glide slope indicators, and no FMAs appeared regarding ILS CAT or anything. However, when I activated Approach mode the plane continued to descend towards the runway as if the plane did capture the ILS...perhaps just a visual bug?

**Comment by efortier-95** [comment]
Feels like it's been resolved (at least at La Guardia with runway 22).

However, I do note that, while the ILS frequency can be overriden and the LOC/GS indicators appear on the PFD, the Course selection in the MCDU can't be overwritten:
![image](https://user-images.githubusercontent.com/56796781/96059706-a997a580-0e5c-11eb-8362-1cd47417b074.png)

**Comment by SpyCopBR** [comment]
I have the exact same problem here.
![Captura de tela 2020-11-30 03 12 58](https://user-images.githubusercontent.com/75239023/100578250-9fbceb00-32c0-11eb-9907-2585179b1ce6.png)

**Comment by MisterChocker** [comment]
issue seemed to have changed since #2273
