### ISSUE TITLE
[BUG] All displays/buttons in AP Panel illuminated regardless of state, knobs functional but displays not

### ISSUE THREAD

**Issue by Marley365** [flybywiresim/a32nx#1025]
**Mod Version**
Release V0.3.1

**Describe the bug**

Mid flight all of the dispplays in the AP panel becamse populated with 8888, all other buttons on the panel became illuminated. They were still functional but are now permanently active.

**To Reproduce**

1.
2.
3.

Not sure how to reproduce, the past thing I did was turn off the seatbelt signs and turn on the smoking signs, before realsiing the displays had changed. This was about 30 minutes into the flight.

**Expected behavior**

The Displays should stay functional and show their desired values.

**Actual behavior**

All lights/buttons on the panel are illuminated regardless of their state.

**References**

![image](https://user-images.githubusercontent.com/72228183/94857244-1ce6f380-0429-11eb-8d3b-306c8732900a.png)

**Additional context**

Was this working before/when did the issue start occurring?

All displays were working correctly through take off and climb to FL360

Is this a problem in the vanilla unmodded game?
No I've tested and it doesn't seem to happen after the same amount of time flying in the current build.

Discord username (if different from GitHub):Marley#6781

**Comment by komp1821** [comment]
You accidentally activated the light test on the overhead panel.

**Comment by Marley365** [comment]
> You accidentally activated the light test on the overhead panel.

Well now I feel stupid
