### ISSUE TITLE
[BUG] CTD on camera move

### ISSUE THREAD

**Issue by jgord2006** [flybywiresim/a32nx#1028]
**Mod Version**

0.3.1

**Describe the bug**

when I get up to cruise my camera locks 45 degrees to the left and then my game stutters a bit then crashes to desktop this has happened twice now in the past 2 days.

**To Reproduce**

1.my flight plan was Detroit to Atlanta and when I got to the cruise of 36000 it happened
2.my exact flight plan was this KDTW/27R CLVIN1 STAZE DCT FLM DCT KTRYN ONDRE1 KATL/27R
3.

**Expected behavior**

I expected not for the game to crash.

**Actual behavior**

My camera moved 45 degrees to the left and locked its self there and crashed to my desktop. 

**References**

**Additional context**

Was this working before/when did the issue start occurring?
It started occurring yesterday when I was trying to do the same flight.
Is this a problem in the vanilla unmodded game?
I don't think so.

Discord username (if different from GitHub):
Sniff#0723

**Comment by ABoldOne** [comment]
Same for me on almost every flight. It seems kinda random. The camera freezes in the last position. If i try to move it via controller or mouse the game crashes.

**Comment by lousybyte** [comment]
This was a 1.9.3 bug I think, should be solved now on 1.9.5?

**Comment by ABoldOne** [comment]
> This was a 1.9.3 bug I think, should be solved now on 1.9.5?

For me it's fixed with the new update.

**Comment by Benjozork** [comment]
This is an MSFS bug. Please report the issue on the forums if it still persists.
