### ISSUE TITLE
Zero Pitch on final approach (locks up) [BUG]

### ISSUE THREAD

**Issue by davidnorfolk96** [flybywiresim/a32nx#1031]
**Mod Version**

0.3.1 master

**Describe the bug**

Any flight on finals, flaps 4 speed 140/150. I have no pitch control even in manual flying nose dips into stall phase. Feels like the elevators lock up 

**To Reproduce**

1. On finals anywhere with ILS
2. Live weather and live time
3. A320 0.3.1

**Expected behavior**

Pitch for glide & speed 

**Actual behavior**

Nose dives down and no control on pitch both in manual & AP 

**References**

N/A
**Additional context**

N/A
Was this working before/when did the issue start occurring?
After 0,3
Is this a problem in the vanilla unmodded game?
No 

Discord username (if different from GitHub):

**Comment by DoToAdventures** [comment]
See #1014 and #1029

**Comment by davidnorfolk96** [comment]
> See #1014 and #1029

Hi mate cheers! Has this been fixed then? shall i just download the latest build? cheers

**Comment by DoToAdventures** [comment]
No worries. Not quite fixed yet but should be very soon. For further discussion please view either the issue or the correlating pull request :)
