### ISSUE TITLE
[BUG] AP crashes plane at takeoff

### ISSUE THREAD

**Issue by Pross** [flybywiresim/a32nx#1032]
**Mod Version**
master

**Describe the bug**
Auto Pilot just banks to the left, no speed control or waypoint and no climb.

**To Reproduce**

1. select dep and arrival to anywhere
2. hi or low alt airways + ils landing 
3. turn on AP

**Expected behavior**
For it to not kill you every time.

**Actual behavior**
Kills you every time

**References**

https://youtu.be/LFYhUT3NhZI

**Additional context**

Was this working before/when did the issue start occurring?
After the Japan update I think.

**Comment by Pross** [comment]
Looks like setting deadzone to 7% for the controller fixes this.
Using genuine new Xbox controller.

**Comment by lousybyte** [comment]
So it's a controller or an AP issue?

**Comment by johnwillimas** [comment]
Agree - I have been having AP problems with both this mod and the native plane. I've cured the problems on the Asobo native plane by setting dead zone on all axes to 10%. Now going to try the 3.1 fix from here......

**Comment by johnwillimas** [comment]
Tried the 3.1 fix and can confiorm it now works OK with control null zone set at 10%. Also tried with or without AI traffic (which has been suggested as a factor here) and that seems to make no difference.

**Comment by johnwillimas** [comment]
Spoke too soon. Works OK if AP is used in selected speed / heading / alt etc. but not when FMC is following a flight plan and using managed speed and heading..

**Comment by Pross** [comment]
I set the deadzone to 7% on all 4 axis and only had one issue.. half way along a flight going from one waypoint to another.. in a straight line.. and the plane did a 180.. it eventually did a full circle and picked up the line again, I'm going to try 10% tonight.

**Comment by KozziOS** [comment]
This is a +1 for me although it sometimes happens mid-flight for no apparent reason

**Comment by Pross** [comment]
> This is a +1 for me although it sometimes happens mid-flight for no apparent reason

Someone on discord suggested pressing ESC to pause the game for 2 or 3 seconds then rejoining the game the AP will stop banking and rejoin the flightpath... and it does seem to work..

**Comment by Pross** [comment]
So I set the deadzone to 10% last night and managed a 300km flight and only had to do the ESC trick once when it drifted to the left near the end of the flight. I can live with this I just have to remember to pause when leaving the room thats all.

**Comment by OFC1983** [comment]
I think this is a Flight Sim AP Bug. Had the same issue with the 787 after TakeOff, when turning on LNAV to follow Flight Plan Route... A/C didnt stop turning

**Comment by lousybyte** [comment]
Should be fixed now in 1.9.5?

**Comment by lousybyte** [comment]
Seems it's still an issue with the game.

**Comment by Pross** [comment]
> Seems it's still an issue with the game.

Yea it is. Best _fix_ is to set the controller deadzone, I have mine set to 20% across the axis. Then when it does drift off press ESC and wait 5s then rejoin the game and it should turn back to the waypoint.

**Comment by hotshotp** [comment]
fixed in latest updates
