### ISSUE TITLE
ROSE NAV on ND[BUG]

### ISSUE THREAD

**Issue by Ares1378** [flybywiresim/a32nx#1033]
**Mod Version**

Master

**Describe the bug**

There should be no course needle if there is no VOR tuned or no course entered in the RAD NAV it should not be displayed. 

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment]
Closing since is issue is not following the template.
