### ISSUE TITLE
Unusual AoA during approach (and cruise) [BUG]

### ISSUE THREAD

**Issue by dmajestic80** [flybywiresim/a32nx#1034]
**Mod Version**

Latest Master 3.1

**Describe the bug**

So there is 100% an issue with the mod that induces an unusual AoA during approach which has the aircraft sitting at around 5-6 degrees nose up. The issue is not present when using the unmodded aircraft and I have tested this about 10 times on both modded and unmodded using exact same weight, config and weather conditions.

**To Reproduce**

1. Try the below steps in both unmodded and modded version
2. Please see screenshot below for fuel and payload settings that I used (no rhyme or reason for these) you can test using any weights as long as both are the same for unmodded and modded trials
3. I set up on the ILS YPAD Rwy 23 by selecting only arrival airport when setting up the flight for the test.
4. Weather set as per below screenshot. Selected default 'Rain' setting and set winds to 0 for the test with QNH 1013.
5. Using selected speed of 145 kts for the entire approach at full flaps (it defaults to these flaps when you are spawned at 3200ft and established for the ILS) You will need to manually engage selected speed of 145 kts) PERF page is stating VAPP 140 with VLS 130 but on the modded version the AoA would be even worse if using these so have kept 145 kts as the control.
6. Tested with AP on, autothrottle on, throttle in CL detent and APPR button engaged and leave this for the entire approach, do not take manual control for the purposes of this test.

Weight and Payload settings
<img width="982" alt="Capture" src="https://user-images.githubusercontent.com/72002430/94882469-3fb7ed00-04a7-11eb-8c19-0d29490c6afc.PNG">

**Expected behavior**

Using mod test, AoA seemed high ata round 5-6 degrees, previous mod version I never had this problem before the Microsoft update. Expecting maybe 2.5 degrees max with such a light payload as set up in the test. 

**Actual behavior**

As stated above and shown in below screenshots. I have included 3 screenshots each for both modded and unmodded test. 1 screenshot is showing AoA @ 2500ft, another @1000ft and another at the threshold @100ft

**References**

**Additional context**

Was this working before/when did the issue start occurring?
This issue seems to have only started when using the updated mod 3.1 after the new 1.9.3.0 update was released.

Is this a problem in the vanilla unmodded game?
100% a problem with the 3.1 mod as the issue is non-existent in the vanilla version.

Below screenshots are the Modded version
100ft Mod
![100ft](https://user-images.githubusercontent.com/72002430/94881775-6ecd5f00-04a5-11eb-8987-12e2c5395c8e.png)
1000ft Mod
![1000ft](https://user-images.githubusercontent.com/72002430/94881837-94f2ff00-04a5-11eb-9344-53bec0a0159c.png)
2500ft mod
![2500ft](https://user-images.githubusercontent.com/72002430/94881887-b2c06400-04a5-11eb-9d67-0442f4e4ce4a.png)

Below screenshots are the Vanilla version
100ft unmod
![100ft](https://user-images.githubusercontent.com/72002430/94882000-f1eeb500-04a5-11eb-929d-998bd6fd6579.png)
1000ft unmod
![1000ft](https://user-images.githubusercontent.com/72002430/94882074-1ea2cc80-04a6-11eb-9453-bdc56900eb5a.png)
2500ft unmod
![2500ft](https://user-images.githubusercontent.com/72002430/94882223-86591780-04a6-11eb-9519-0dbf4d08fcca.png)

Weather settings
![1250410_20201002113443_1](https://user-images.githubusercontent.com/72002430/94882442-2fa00d80-04a7-11eb-8f03-4f553df6e8cb.png)

Discord username (if different from GitHub):

**Comment by lousybyte** [comment]
Related #984.

**Comment by dmajestic80** [comment]
I've made my own work around for the time being. I can see the flightmodel.cfg within the mod has some different values. I simply added the default details from the Asobo flightmodel.cfg and the issue is fixed. The AoA is now acceptable and as it was with the unmodded version. At least I can now fly as per normal and still enjoy all the features of the mod.
