### ISSUE TITLE
Strobe light frequency

### ISSUE THREAD

**Issue by lalloretpilou** [flybywiresim/a32nx#1035]
**Mod Version**
Last repository version.

**Describe the bug**
In reality, the lights flash at the end of the wings, flash at a frequency of twice quickly whereas it is once.

**To Reproduce**

1. Just flight at night with strobe light ON
2.
3.

**Expected behavior**

**Actual behavior**

**References**
https://www.youtube.com/watch?v=cG48JB996uI (8min40)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by lousybyte** [comment]
Related #905.

**Comment by NathanInnes** [comment]
Closing as this is a duplicate issue, before posting an issue in future, just do a quick search around to see if it is already been put through 👍
