### ISSUE TITLE
[BUG] All screens suddenly turns off.

### ISSUE THREAD

**Issue by EsherDemo** [flybywiresim/a32nx#1036]
**Mod Version**
3.1

**Describe the bug**
During my preflight, all screens and battery suddenly turns off and wont come back on.

**To Reproduce**

1. Turned on bat 1.+2.
2.GrdPower on
3.Preflight = electronics out.

**Expected behavior**

**Actual behavior**

**References**
https://streamable.com/mxcoqv

**Additional context**
Settings : 
AI on
Worker + airport vehicles on
REX
PACX
Navigraph Simlink

Was this working before/when did the issue start occurring?
3.0 master
Is this a problem in the vanilla unmodded game?
I think this has to do with the Japan upgrade for the game.

**Comment by VideoScape** [comment]
i am having the same issue, i thought I missed a button or something.

**Comment by NathanInnes** [comment]
Turn off AI traffic and make sure you run build.py

**Comment by EsherDemo** [comment]
> Turn off AI traffic and make sure you run build.py

Sorry mate, how does the build.py work ? :)

**Comment by NathanInnes** [comment]
Download the latest version of python. Head to **MOD_LOCATION > a32nx > A32NX > build.py**

All you have to do is click on build.py and it should rebuild layout.json & manifest.json

**Comment by NathanInnes** [comment]
Try turning all AI off first.

**Comment by lukecologne** [comment]
>  3.0 master

What do you have installed, 3.0 or master?

**Comment by EsherDemo** [comment]
3.1 Luke*

Do I need to turn off the airport life and land/sea traffic as well? :)

**Comment by EsherDemo** [comment]
Thanks guys
That did it for me ! 
Have a great weekend
