### ISSUE TITLE
Requesting a printable version of the mod's checklists

### ISSUE THREAD

**Issue by h-rezaei** [flybywiresim/a32nx#1039]
Hi there
If possible could a printable version of the checklist that is available with the mod, be published on the flybywire's website?
Thanks.

**Comment by NathanInnes** [comment]
Please respect the template provided to you in future. If you would like a checklist in the mean time there are plenty online. Just look up A320 Checklist.

But good suggestion to make our own.

**Comment by MisterChocker** [comment]
This has been done by now.
[Checklist](https://cdn.discordapp.com/attachments/747571948342476850/782013966104133632/FBW_A320NEO_CHECKLIST_2.pdf)
