### ISSUE TITLE
[BUG] Low FPS since newest version / performance issue

### ISSUE THREAD

**Issue by Pilot747-hub** [flybywiresim/a32nx#1041]
**Mod Version**

V 0.3.1

**Describe the bug**

Very low FPS since new version/patch of MSFS2020 and A320NX V 0.3.1 installed. Running i9-9900k, 32GB RAM, GTX 1080 TI, 1TB SSD - only getting 10 FPS in avarage

**To Reproduce**

1. Install latest MSFS2020 update/patch
2. Install latest A320NX V 0.3.1 
3.

**Expected behavior**

**Actual behavior**

FPS dropping down to 10 FSP

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Yes!

Is this a problem in the vanilla unmodded game?
No! 

Discord username (if different from GitHub): 747pilot

**Comment by Aarondodd88** [comment]
Not sure how this is related to the mod

**Comment by Aarondodd88** [comment]
Please provide more detail nothing can be figured out from your description

**Comment by Aarondodd88** [comment]
Please provide more details. This doesn't provide any information for anybody. Thankyou

**Comment by NathanInnes** [comment]
Also include screenshots of the FPS counter in-game please. If you're limited by CoherentGTDraw I would recommend reading this post. https://forums.flightsimulator.com/t/limited-by-coherentgtdraw-issue/275843

**Comment by NathanInnes** [comment]
I have a worse build than @Pheome and latest master and doing just fine. 

If you're locked to 10 fps it's usually related to a CoherentGT bug.

**Comment by Pilot747-hub** [comment]
Thanky guys! Turning off VFR Map helped in the first instance and I got minor improvements.
Furthermore in the next step I completely deleted A320NX folder in community folder, restartet PC and MSFS, quit MSFS, restarted PC, redownloaded the latest version of A320NX and installed it again. Finally restarted PC and MSFS and then I got an avarage of 40 to 50 FPS again.
