### ISSUE TITLE
Takeoff and Flare Mode[BUG]

### ISSUE THREAD

**Issue by captbillybob** [flybywiresim/a32nx#1043]
**Mod Version*
Latest

**Describe the bug**
It seems on takeoff and landing, the aircraft will ignore pitch inputs. 

**To Reproduce**

1.Just take off or land
2.
3.

**Expected behavior**
If you pull the stick back to pitch to 10 degrees it should stay at 10 degrees if you center the stick. It lowers pitch significantly requiring to pull back significantly. Try to flare it's the same issue. Release stick and pitches down severely.

**Actual behavior**

See above
**References**

**Additional context**
There's someone wrong with either auto trim or with ground and transiting to flight mode.
Was this working before/when did the issue start occurring?
With all mods so far
Is this a problem in the vanilla unmodded game?
I'm not sure.

Discord username (if different from GitHub):

**Comment by lousybyte** [comment]
Have you tried after https://github.com/flybywiresim/a32nx/pull/1029?

**Comment by captbillybob** [comment]
> Have you tried after #1029?

Yes I did. Very difficult to take off and land correctly.

**Comment by veikkos** [comment]
Upvoting. Had a lenghty gaming session with a pilot friend and we were puzzled why plane pitches heavily down at flare.

**Comment by captbillybob** [comment]
> Upvoting. Had a lenghty gaming session with a pilot friend and we were puzzled why plane pitches heavily down at flare.

Do you have takeoff issues as well?

**Comment by veikkos** [comment]
> 
> 
> > Upvoting. Had a lenghty gaming session with a pilot friend and we were puzzled why plane pitches heavily down at flare.
> 
> Do you have takeoff issues as well?

Yes. Nose pitches down heavily right after TO. You have to yank stick back hard to keep the plane from crashing back to ground.

100% repro for me.

**Comment by mateoriddl** [comment]
The exact issue for me also. Could only finish one flight out of five today, all the others crashed due to this bug with the flight model.
