### ISSUE TITLE
Auto Throttle and Climb Thrust are switched

### ISSUE THREAD

**Issue by FlightSimmer7700** [flybywiresim/a32nx#1044]
**Mod Version**
Latest Master

**Describe the bug**
When you put the thrust levers into the climb detent the thrust is set to Auto Thrust while when you pull them back into Auto Thrust it is set to Climb Thrust

**To Reproduce:**
Start a flight,
Take off
Put throttles into climb detent
then into Auto thrust range

**Expected behaviour**

Should be set to Climb Thrust and then Auto Thrust

**Actual behaviour**

It does it the other way around

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Since I got the newest version

**Is this a problem in the vanilla unmodded game?**
No

**Discord username (if different from GitHub):**

**Comment by NathanInnes** [comment]
According to this source there's no AUTO
![image](https://user-images.githubusercontent.com/18389085/94968770-6dc61d00-04f9-11eb-992e-70bd7afa0627.png)

**Comment by FlightSimmer7700** [comment]
By Auto Thrust I mean when you move the throttles to A/THR and the plane then holds the speed you have set or managed speed

**Comment by atulumello** [comment]
The real A32X treats CL (CLB) as autothrottle. Once in CL, if you move out of CL, it will cut the autothrottle.

**Comment by FlightSimmer7700** [comment]
yes but in the mod it goes into Thrust climb when you move the throttles back, I'm not talking about if it is realistic or not I'm saying that it is switched from what it used to be and in the climb detent it just says speed not thrust climb and when I pull the levers back it says thrust climb I'm just comparing it to what it has been until now

**Comment by hotshotp** [comment]
now it says speed when you do this
