### ISSUE TITLE
No sound on the altitude knob

### ISSUE THREAD

**Issue by HL020** [flybywiresim/a32nx#1046]
No sound when the altitude knob is being turned

**Comment by aviationenthusiast** [comment]
Please use issue template and provide more details.

**Comment by NathanInnes** [comment]
Works for me.

**Comment by HL020** [comment]
Well when you turn the autopilot knobs there should be a clicking sound. I can't hear it when I turn the altitude knob, but others like the speed and vertical speed has this clicking sound

**Comment by lousybyte** [comment]
Please try the new stable version and open a new issue following the template if it's still a problem, so we get all the details.
