### ISSUE TITLE
[BUG] The plane goes full down and right or left

### ISSUE THREAD

**Issue by SgtFreddy713** [flybywiresim/a32nx#1050]
**Mod Version**

0.3.1

**Describe the bug**

When i active the auto pilot the plane goes full down and right or left and doesn't follow the route

**To Reproduce**

1. Take off
2. Climb around 5000/4000FT
3. Active AP

**Expected behavior**

The plane should to follow the route

**Actual behavior**

Goes full down and right or left

**References**

**Additional context**

Was this working before/when did the issue start occurring?

The problem start after the Japan update

Is this a problem in the vanilla unmodded game?

I don't know, i don't tested without the mod

Discord username (if different from GitHub):

**Comment by lousybyte** [comment]
Related #1006, #1007, #1032 and I think a few others.

**Comment by SgtFreddy713** [comment]
> Related #1006, #1007, #1032 and I think a few others.

Oh, i don't noticed, sorry

**Comment by Superlister97** [comment]
Yeah im having this issue to... its unflyable for me at the moment and its very frustrating. Hopefully this issue is resolves soon !

**Comment by Kubakuurne** [comment]
Same problem here plane in AP is swerving all around and doesn't follow flight plan

**Comment by speedwaystar** [comment]
this is a widely reported issue, and the commonly suggested fixes are (1) turn off all AI aircraft because of a bug where their AP sometimes takes over the AP of your aircraft making it appear possessed, and/or (2) set your joystick dead zone to >10%

**Comment by Clo08** [comment]
I have the same issue, the plane does'nt follow the flight plan and bank to right. I use the last stable release.  With the default plane I have not the problem.

**Comment by MisterChocker** [comment]
fixed by game updates
