### ISSUE TITLE
No Master Warning when trying to Land with Improper Landing Configuration[BUG]

### ISSUE THREAD

**Issue by ErickSharp** [flybywiresim/a32nx#1054]
**Mod Version**

V0.3.1

**Describe the bug**

No master warning when in improper landing configuration, as well as no memo displaying on ECAM display alerting that the gear is up.

**To Reproduce**

1. Attempt to land with gear up.
2. Done.

**Expected behavior**

Master Warning should sound and memo on ECAM display should indicate a message that tells that gear is up.

**Actual behavior**

Nothing happens - no master warning or ECAM memo

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Worked on V0.2 well
Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by NathanInnes** [comment]
![Uploading image.png…]()
