### ISSUE TITLE
ADD Door Cam

### ISSUE THREAD

**Issue by lalloretpilou** [flybywiresim/a32nx#1055]
[

**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**
Next to the Lock button, the video button display on the ECAM the video of the door.

**References**
![PEDESTAL](https://user-images.githubusercontent.com/42711915/94985497-941aa580-0557-11eb-8e9d-c42a8641e0fd.PNG)
![image png b83fbe1c3e29d7d43ea0b31af928bcd5](https://user-images.githubusercontent.com/42711915/94985498-967cff80-0557-11eb-857c-a1c2d882de2b.png)

**Additional context**

Discord username (if different from GitHub):

**Comment by lousybyte** [comment]
Duplicate #120.

**Comment by KevinTheMinion97** [comment]
It's doesn't work for me :( the video doesn't show up on ECAM

**Comment by NathanInnes** [comment]
@KevinTheMinion97 It's a feature request not a bug.
