### ISSUE TITLE
[REQUEST] PACKS (APU Bleed sound) disabled during Engine Mode to IGN/START

### ISSUE THREAD

**Issue by sebbenandsebben** [flybywiresim/a32nx#1056]
**Is your feature request related to a problem? Please describe.**
Because the APU bleed functionality has been implemented in this mod, we now have the sound of the 'PACKS' when the bleed is switched on. On the real aircraft, during engine start the air is completely diverted from the PACKS to the engine for start, so the PACK valves are closed. When the Engine Mode selected is switched to "IGN/START" the implemented APU bleed sound (which is really the sound the PACKS would be making) should stop.

**Describe the feature you'd like to see implemented**
As per the functionality of the real aircraft, the following logic (or as close to it) could be implemented:
- When the Engine Mode selector is set to IGN, when on ground, the PACKS (APU bleed noise) switch off.
- When the Engine Mode selector is set back to NORM after start, the PACKS (APU bleed noise) are switched back on.

**References**
Have confirmed my reference from the A330 FCOM 1 is correct with the A320 NEO as per "komp" in Discord. Full reference from the FCOM is:
The pack flow control valve is open when the PACK pb is selected ON (not currently simulated) except in the following cases:
<ommitted for brevity>
— Engine start sequence:
1. One valve (or both, if the crossbleed valve is open) closes when :
• The MODE selector is set to IGN, when on ground (valves reopen if
MASTER switch or MAN START pushbutton are not set to ON within
30 seconds) ;
• The MODE selector is set to IGN (or CRANK) and when, on either
engine :
— The MASTER switch is set to ON (or MAN START pushbutton is
set to ON), and
— The start valve is open, and
— N3 < 50 %.
2. On ground, reopening of the valves is delayed 1 minute to avoid an extra
pack closure cycle during subsequent engine start.
<ommited for brevity>

**Additional context**

Discord username (if different from GitHub): PhilKenSebben

**Comment by Ares1378** [comment]
Note in a dumbed down version:
Pack valve will be open unless: 
Start in progress - Start Valve OPEN
Air pressure Low (NO BLEED AIR)
Ditching pb pressed
Fire PB released (ON SIDE ENGINE)
Overheat of the compressor outlet/pack outlet

OR if you manually turn the packs off via the pushbutton

**Comment by hotshotp** [comment]
Hello! For your issue, what I can do is once the packs are fully implemented and the variables are there I can remove the sound that is attached to the APU bleed.
