### ISSUE TITLE
 [BUG] PFD and other displays not working

### ISSUE THREAD

**Issue by TommyCoding** [flybywiresim/a32nx#1061]
**Mod Version**
v0.3.1
(MSFS: v1.9.3.0 Steam version)

**Describe the bug**
Cannot get PFD displays to work, they stay black/offline whatever I do

**To Reproduce**
1. Installed mod following your tutorial (extracted A320 folder to "community")
2. Selected various gate as start position on any airport (airplane is in cold&dark)
3. Followed various cold&dark startup tutorials (like: https://www.youtube.com/watch?v=oSOVC6sHACU)
4. Increased brightness of all PFDs
5. Tried the same with default A320 when mod was disabled, displays work instantly there

**Expected behavior**
Displays should turn on and self test mode should be visible (as far as I could find out)

**Actual behavior**
Displays stay empty/black/offline.

**References**
![image](https://user-images.githubusercontent.com/70858367/94996938-02875400-05a8-11eb-94c1-3b64d1186fb5.png)

**Additional context**
Using Logitech Multi Panel, Flight Switch Panel, Yoke and rudder pedals with Logitech plugin for MSFS (https://support.logi.com/hc/de-at/articles/360024692354--Downloads-Fluginstrumententafel).
Works with default A320 when mod is uninstalled.
Also Checklist does not work in UI, I get an empty window when opening it.
Tried to find solution with Google & co. but no chance I have no idea whats wrong.
MSFS is a fresh install just digging into it.

**Comment by lousybyte** [comment]
Try running `build.py` or download the [latest master](https://github.com/flybywiresim/a32nx/archive/master.zip) version.

**Comment by TommyCoding** [comment]
Hi, tried latest master but no success.
Btw I forgot to mention that I am running Saitek (or now Logitech) Multi Panels and yokes with correspondings msfs plugin from Logitech website in-sim. I`ve already had some sort of problems with that in FSX and 3rd-party aircraft. 
Maybe the switches on the panel could override something needed (avionics, bat, alt., panel lights) to turn the displays on ?

**Comment by lousybyte** [comment]
Have you tried disabling multiplayer, AI traffic, and ground AI ? Honestly don't see how input would affect this, but I might be wrong.

**Comment by TommyCoding** [comment]
Tried it without traffic and AI. Also tried it with Saiteks panels disconnected. Result is exactly the same :-(

Am I missing any step (i mean turning on the battery and rotating brightness knobs to maximum should be enought shouldn`t it ?).

**Comment by lousybyte** [comment]
Tried turning EXT PWR on first then BAT?

**Comment by TommyCoding** [comment]
Yep exactly. Tried EXT PWR first, then BAT1/BAT2. Then turning brightness PFD left on maximum. Remains black.

**Comment by lousybyte** [comment]
I'm out of ideas. Can you please try deleting `A32NX` folder from `Community `completely, then download the latest master, extract only the `A32NX` folder and paste it in the `Community `folder again?
Also maybe try temporarily removing any liveries you might have, some older format ones could interfere with the mod.

**Comment by lousybyte** [comment]
One thing, does EXT PWR have the green AVAIL on it when you load?

**Comment by KellyAlicia** [comment]
I have the same issue.
I turn on the ground power first and then turn on the battery, but all the monitors including MFD, PFD and FMS do not light up.

**Comment by guntoad** [comment]
Installed and tried for the first time yesterday, I have the same issues as noted above. i also noticed the acars  swiches do not light when enabled as shown in previous videos. removed A32NX folder, re downloaded and added again, no difference. I will try the latest master and advise

**Comment by guntoad** [comment]
Latest master seems to have fixed this issues for me. thank you

**Comment by TommyCoding** [comment]
Yep EXT PWR has green AVAIL. I can also hear the sounds when turning on power. I`ve tried latest master too but no luck for me.

**Comment by OFC1983** [comment]
I had the same issue. I fixed it the following way: Deleted the A32NX Folder and all the installed liveries. Also deleted the Rolling Cache File with the CCC ending. After that started Msfs. After successful loading exited the game, placed the A32NX and the liveries back in the Community folder and then it worked for me. Took me a while to figure it out as the loading screen are very time consuming...

**Comment by TommyCoding** [comment]
Tried this procedure with latest master but didnt help. I`ve also tried it with plane starting on runway. All systems are online except for all displays of PFD, MFD, FMS which stay black. What I`ve also noticed that the battery voltage display on overhead is also black everytime (in contrast to default behaviour) so none of the displays work with this addon. 
There is one difference in my installation/config. I`ve changed the data directory of MSFS to target another hard disk. I did not use the default paths within UserData. 
In my case the data dir of MSFS is set to "E:\FS" and there are the "Community" and "Official" folders are there. I`ve changed the path within the installation launcher before downloading the packages.
Could this be a reason (maybe because of some paths not loading correctly) ?

**Comment by akambience** [comment]
I am also experiencing this. I've tried installing the latest maser, clearing the rolling cache, removing the liveries... I've tried rolling back to prior stable builds to no avail.

**Comment by lousybyte** [comment]
There's an [official installer](https://github.com/Externoak/A32NX-installer/releases/latest/download/A32NX_Downloader.zip) now available, maybe try using that and see if it makes a difference.

**Comment by akambience** [comment]
Used the official installer; tried both the developer and the stable versions.  No dice, I'm still in the dark. 

literally.

**Comment by DominikTV** [comment]
Same here. It worked like 2 hours ago and I did not change anything in between (except one restart of my pc). Even ACT stays off.

**Comment by TommyCoding** [comment]
Hmmm....maybe something dedicated to hardware, drivers or system specs ?

I am using Windows 10 powered by an AMD Ryzen 3xxxx CPU and an Nividia 1070 GTX graphics card. I recently updated my graphics card drivers 2 weeks ago (issue not going to be solved).

**Comment by akambience** [comment]
I tried rolling back drivers. No differentrence. Everything was fine until about a week ago. 
This is super strange.

**Comment by lousybyte** [comment]
Please try the new [stable release](https://github.com/flybywiresim/a32nx/releases/tag/v0.4.0), make sure to read the description, and also that your game is on version 1.9.5, and have no other mods installed.

**Comment by TommyCoding** [comment]
Yay the latest update solved my issue thank you very much. :-)

My steps:
1) updated MSFS to 1.9.5 
2) removed the A320 addon package from community directory
3) deleted the rolling cache file
4) finally installed the latest stable release (0.4.0) using the installer

Now all displays work instantly which were completely black before.

**Comment by akambience** [comment]
I also have success after the latest update. Running the official installer and running the stable version. Same steps as TommyCoding. 

I'm back baby!

**Comment by Benjozork** [comment]
Glad your issue is resolved !
