### ISSUE TITLE
[BUG] DCT to in MCDU should automatically engage managed mode in autopilot

### ISSUE THREAD

**Issue by efortier-95** [flybywiresim/a32nx#1063]
**Mod Version**

v0.3.1 release

**Describe the bug**

If one selects a dct-to in the MCDU, the autopilot should automatically engage managed mode and directly proceed to the waypoint in question.

**To Reproduce**

1. Fly a flight
2. Engage heading mode 
3. Choose dct-to a waypoint on-route
4. Active routing

**Expected behavior**

FMA reverts to NAV and the aircraft starts turning towards the dct-to waypoint

**Actual behavior**

HDG mode still enabled

**References**

Not a real A320 pilot; that's just how the Aerosoft A320 behaved so I *presume* that's how it actually works.

**Additional context**

Was this working before/when did the issue start occurring?
Unsure

Is this a problem in the vanilla unmodded game?
Unsure

Discord username (if different from GitHub):
Eefoe#0570

**Comment by Ares1378** [comment]
It is correct that DIR TO or RADIAL IN should automatically switch to managed mode.

**Comment by St54Kevin** [comment]
I do confirm it should be as described above
