### ISSUE TITLE
[BUG] Fire Push Covers can't be closed

### ISSUE THREAD

**Issue by liebbe10** [flybywiresim/a32nx#1065]
**Mod Version**

Master

**Describe the bug**

After opening the fire push covers, they can't be closed again (I don't mean the actual fire push buttons, only their protective covers)

**To Reproduce**

1. open the covers
2. try to close them by pressing again on the open covers

**Expected behavior**

they should be closable, but only if the fire push button hasn't been pushed

**Actual behavior**

they remain open and can't be closed

**References**

no reference, but wouldn't make sense to have them forced open I guess

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by liebbe10** [comment]
@wpine215 as I saw that you are working on the overhead button functionality, is this something you could fix?

**Comment by lukecologne** [comment]
This has been fixed
