### ISSUE TITLE
[REQUEST]Disable controller or ignore controller inputs when autopilot is engaged

### ISSUE THREAD

**Issue by donstim** [flybywiresim/a32nx#1069]
**Is your feature request related to a problem? Please describe.**

Yes. There are many reports of the airplane not following the programmed flight path under autopilot control. The airplane will start a left or right turn off the flight path and possibly enter into an uncontrollable spiral dive if it is not corrected immediately.

**Describe the feature you'd like to see implemented**

Provide the capability to either disconnect or ignore controller inputs when under autopilot control. This could be either something that is selectable by the user or if that is not possible or considered necessary, be always present.

I feel that I have recently confirmed that at least some of the problems of the airplane deviating from the flight path to be a controller issue. I never had the problem myself until a recent attempt to help someone else who did experience the issue. For IFR, I I fly the A320 exclusively (up to this point) due to this mod and the state of the other planes. To help this other individual, I flew the 787. To my surprise, I then experienced the problem several times on a relatively short flight (KSEA-KGEG).

I then realized that I had switched controllers from a Thrustmaster HOTAS X joystick for the A320 to a CH Flight Sim Yoke for the 787. So, I switched back to the joystick and re-flew the 787 flight. And I did not experience the autopilot not following the flight path issue!

Although this was only 2 flights, I think it shows that for at least some of those experiencing this issue, it is due to the controller. I think the sim is interpreting spurious signals as intended autopilot corrections or overrides.

Until Asobo fixes this issue, if the controller input could be disabled or ignored in some way while under autopilot control, it may be a significant improvement for some people.

**References**

This is not a realism feature; it is merely to give some relief to an issue that makes MSFS unplayable for what appears to be a relatively large number of people.

**Additional context**
Not that it should matter, but I think if this could be incorporated and it does address a significant issue for a lot of people, it would really elevate flybywiresim's reputation even higher than it already is.

Discord username (if different from GitHub):donbikes#4084

**Comment by Benjozork** [comment]
We cannot control peripheral inputs - that's a sim feature. Sorry.

**Comment by NathanInnes** [comment]
Safest option is to just unplug your controller or not to touch it. I'm afraid this is something that most likely won't be worked on.

**Comment by donstim** [comment]
My controller works fine. The issue is that some controllers (many?) send spurious signals without being touched that cause this issue in MSFS. Unplugging the controller just while on autopilot is not a reasonable workaround. Setting an appropriate dead zone is.

**Comment by NathanInnes** [comment]
Yeah, that's not something we can really do. The sim has a setting already for a dead zone though.

**Comment by wpine215** [comment]
Seems to be resolved with deadzone settings. Closing.

**Comment by donstim** [comment]
Using dead zones is a workaround. It does not resolve the issue. If it is to be closed, the reason should be the one given in the first comment -- that you have no "control" (pun intended) over peripheral inputs.
