### ISSUE TITLE
[BUG] ND blocked when interacting with VOR / ADF, APT etc. switches

### ISSUE THREAD

**Issue by ACSoft47** [flybywiresim/a32nx#1071]
**Mod Version**

master (but exist since some time already)

**Describe the bug**

When interacting with ADF/VOR, the ND display stay locked in MODE CHANGE state.

**To Reproduce**

1. Cruise fly, let say at FL330.
2. Be sure you selected both ADF/VOR switches to VOR
3. Save the flight
4. Exit to menu and then load the saved flight.

**Expected behavior**

The ND display to run normally.

**Actual behavior**

The ND display stay locked in MODE CHANGE state.

**References**

![ND-locked](https://user-images.githubusercontent.com/70327013/95003997-dd193b00-05e5-11eb-9d4d-bf5d0f7b92dd.jpg)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):
ACSoft#7917

**Comment by NathanInnes** [comment]
Does turning all ADF/VOR aids make it return to normal?

**Comment by NathanInnes** [comment]
Most likely related.

**Comment by ACSoft47** [comment]
Yes, it is the way I use to unlock the situation.

Sorry, I should have mentionned, but the guide didn't asked for a workaround so I forget

**Comment by 2hwk** [comment]
![image](https://user-images.githubusercontent.com/15316958/95162658-b66f2600-07d8-11eb-85d9-0cd86282cd9e.png)

Console output

**Comment by ACSoft47** [comment]
@2hwk Does your pic with code mean you corrected ?
If yes, thanks a lot !

**Comment by Benjozork** [comment]
> 
> 
> @2hwk Does your pic with code mean you corrected ?
> If yes, thanks a lot !

No, that is only so we can debug the issue.

**Comment by ACSoft47** [comment]
Oh, I see !
I am sure you wiil find !

**Comment by 2hwk** [comment]
I think I've solved this, will push a new bugfix PR, will need feedback.  @ACSoft47
