### ISSUE TITLE
[BUG] Avionics ventilation sound comes with delay, after entering the cockpit 

### ISSUE THREAD

**Issue by Watsi01** [flybywiresim/a32nx#1077]
**Mod Version**
master

**Describe the bug**
When entering the cockpit e.g. from external view (with APU or ext power on), the avionics ventilations sound is silent and comes back with a delay of 1-2 sec.

**To Reproduce**

1. Enter cold& dark
2. Start batt and ext power or APU (no bleed - to hear it better)
3. go to external view
4. go back to cockpit view

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Did work before editing the ventilation sounds (0.3.1)

Thanks

**Comment by aboodilatif** [comment]
I'm able to reproduce this, sound has a delay of about 1s when switching into cockpit view

**Comment by hotshotp** [comment]
I have tested and found what that bug was caused by. Will create a pull request to fix this later.

**Comment by lousybyte** [comment]
Still an issue?

**Comment by Watsi01** [comment]
Nope. Just forgot to close it.
