### ISSUE TITLE
Push a 0.3.2 that includes pr#1029

### ISSUE THREAD

**Issue by joniatus** [flybywiresim/a32nx#1084]
**Is your feature request related to a problem? Please describe.**

0.3.1 includes a flight model bug that makes it barely flyable.  Most support questions are related to this issue

**Describe the feature you'd like to see implemented**

Push out a 0.3.2 that includes the fix implemented by pr#1029

**References**

It's a well established bug that makes the plane stall below 150kt

**Additional context**

The latest stable version shouldn't include such a crippling bug

Discord username (if different from GitHub):

**Comment by Pleasure0102** [comment]
before the PR will be pushed it will be tested, the 0.31 was a hotfix to make it playable. Which it is, even with a crippling bug, you can use the pr if it fixes the issue

**Comment by joniatus** [comment]
I do use it. I'm just trying to help the seemingly endless amount of people coming to chat for help with issues directly related to that bug.

**Comment by aboodilatif** [comment]
The PR @joniatus is mentioning has already been merged, I believe its worth pushing a 0.3.2 as the plane on the current "stable" literally falls out of the sky on managed speed and flaps 4. A lot of users only download the stable and its pretty broken for them. just a suggestion to minimize the questions in # help

**Comment by joniatus** [comment]
Closing this because you guys want to pretend that 0.3.1 is useable when it's clearly not.  You can deal with the support in chat
