### ISSUE TITLE
[BUG] LGKR - Anormal trajectory in approach

### ISSUE THREAD

**Issue by JLD95** [flybywiresim/a32nx#1086]
**Mod Version**

Latest dev 2020-10-04

**Describe the bug**

Post Sun Oct 04, 2020 2:15 pm

Hi,

I used this flight plan: LIEE -> LGKR generated with SimBrief. Near finale, waypoints A4, VEMAT and deccel are misaligned

![2020-10-04 (13)](https://user-images.githubusercontent.com/5894146/95018677-8b15fb00-0661-11eb-860f-740187fe5319.jpg)
![2020-10-04 (14)](https://user-images.githubusercontent.com/5894146/95018685-936e3600-0661-11eb-9711-85a4646fc16b.jpg)
![2020-10-04 (10)](https://user-images.githubusercontent.com/5894146/95018694-98cb8080-0661-11eb-8854-f60fa673b09b.jpg)
[LIEELGKR_MFS_04Oct20.zip](https://github.com/flybywiresim/a32nx/files/5323421/LIEELGKR_MFS_04Oct20.zip)

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Curtis-VL** [comment]
Can you check if this is a bug in the vanilla unmodded game too? You didn't answer that on the issue template. :)

**Comment by MisterChocker** [comment]
closing since no response from the op
