### ISSUE TITLE
[BUG] Flight Directors Visible Before Takeoff

### ISSUE THREAD

**Issue by sef3613** [flybywiresim/a32nx#1087]
**Mod Version**

Latest

**Describe the bug**

When the "FD" pushbutton is on, the flight directors are always visible on the PFD even with no active mode on the FMA. This happens before engine start, during taxi, after landing, etc. 

**To Reproduce**

1. Connect aircraft to ground power or start APU.
2. Align ADIRS.
3. Turn on the flight directors and notice that they are visible right away.

**Expected behavior**

Until the thrust levers are in "FLEX" or "TOGA," the flight directors should not appear on the PFD even if the "FD" button is on. There is no active mode on the FMA until takeoff when the thrust is set to "FLEX" or "TOGA" so the flight directors shouldn't appear yet (see screenshots).

**Actual behavior**

The flight directors are instantly visible on the PFD once turning on the "FD" button (see screenshots). 

**References**

Here is a screenshot of the FFA320 in XP11 with the MCDU and FCU setup, engines started, FDs on, but before setting takeoff thrust:
![A320 - 2020-10-04 10 47 02](https://user-images.githubusercontent.com/70450099/95018621-ee3a6a00-062e-11eb-8b0e-3994676ecbad.png)

And this shows how they appear when selecting either "FLEX" or "TOGA:"
![A320 - 2020-10-04 10 47 10](https://user-images.githubusercontent.com/70450099/95018633-014d3a00-062f-11eb-87b7-c8dfb43ff3e2.png)

Here is the FBW a32nx setup before takeoff with the FDs on, notice that they are visible unlike the first screenshot:
![Screenshot (73)](https://user-images.githubusercontent.com/70450099/95018878-4887fa80-0630-11eb-8f58-6c7e554517fa.png)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by sef3613** [comment]
https://youtu.be/vDs2A_rzHVE
Here’s a real Airbus PFD on takeoff, notice the flight directors only appear when takeoff power is set because the FMA has “SRS,RWY”

**Comment by Curtis-VL** [comment]
Will look into this, thanks!

**Comment by Curtis-VL** [comment]
This is currently undergoing testing before I put up a PR for it, will update with the PR when it's open!

**Comment by sef3613** [comment]
Gotcha thanks, also note the vertical (roll) flight director on takeoff is just a line BELOW the horizon showing the runway centerline. It's not the full vertical flight director such as in flight. It transitions after rotation if you notice in the video.

**Comment by sef3613** [comment]
![image](https://user-images.githubusercontent.com/70450099/95028250-99194b00-0664-11eb-98fe-9f39ec5cdf50.png)
This^

**Comment by Curtis-VL** [comment]
@sef3613 Can you create another issue for that? I'm aware it's missing but it justifies its own issue. :)

**Comment by Curtis-VL** [comment]
Fixed in the following PR: #1100
