### ISSUE TITLE
[BUG] Missing pack 1/2 "fault" light with no bleed air

### ISSUE THREAD

**Issue by sef3613** [flybywiresim/a32nx#1088]
**Mod Version**

Latest

**Describe the bug**

When the Pack 1 and Pack 2 pushbuttons are pushed in, they are in the "auto" position. This means that if there is no bleed air to the Packs, the "fault" light should illuminate on the Pack pushbuttons because they're not on.

**To Reproduce**

1. Connect airplane to ground power or start APU without turning on the APU bleed.
2. Ensure the PACK 1 and PACK 2 pushbuttons are pushed (in auto mode, not off).
3.

**Expected behavior**

Due to the pushbuttons for the Packs being set to the "auto" mode (no off light), the "fault" light should illuminate if there is no bleed air to the system because the packs aren't on in this state.

**Actual behavior**

Button has no "fault" light even without bleed air.

**References**

Here is the FFA320 in XP11 with the APU on, APU bleed off, PACK 1 and 2 pushbuttons in auto mode. Notice the fault lights are illuminated due to lack of bleed air:
![A320 - 2020-10-04 11 08 37](https://user-images.githubusercontent.com/70450099/95019180-e9c38080-0631-11eb-9376-999075b3e605.png)

Here is the FBW a32nx in a similar state. The first screenshot shows the lack of bleed pressure on the ECAM and the second screenshot shows the missing PACK "fault" lights:
![Screenshot (75)](https://user-images.githubusercontent.com/70450099/95019208-065fb880-0632-11eb-8db1-1b4a31d4852f.png)
![Screenshot (76)](https://user-images.githubusercontent.com/70450099/95019213-0a8bd600-0632-11eb-8bf9-7b4521a920de.png)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by sef3613** [comment]
![](https://www.researchgate.net/profile/Aymen_Labidi/publication/341110548/figure/fig1/AS:887038006018048@1588497749361/A320-Overhead-Panel-Hydraulic-Panel.png)
Here’s a real A320 overhead that shows the APU bleed is off and because of this, the fault lights are illuminated on the pack push buttons

**Comment by hotshotp** [comment]
The packs actually are not yet implemented. The pack buttons currently are dummy buttons meant for things to be added to them later on. So, hopefully this clears it up. The packs will 100% be worked on in the future.
