### ISSUE TITLE
[BUG] Incorrect PFD attitude indicator when on the ground

### ISSUE THREAD

**Issue by sef3613** [flybywiresim/a32nx#1089]
**Mod Version**

Latest

**Describe the bug**

When on the ground, the nose-down pitch degree lines are visible on the PFD attitude indicator. They should be missing and replaced with the plain brown color.

**To Reproduce**

1. Start APU or connect ground power.
2. Notice PFD markings.
3.

**Expected behavior**

The brown portion (negative pitch) of the attitude indicator on the PFD should be plain, with no white degree markings when on the ground.

**Actual behavior**

Attitude indicator looks the same as it does in the air, with pitch degree markings on both the nose-up and nose-down sides.

**References**

Here is the FFA320 in XP11 on the ground, notice the bottom half of the attitude indicator (artificial horizon) has no markings on the ground:
![A320 - 2020-10-04 10 47 02](https://user-images.githubusercontent.com/70450099/95019295-8ede5900-0632-11eb-90e8-442e48ddc29f.png)

Here is the FBW n32nx on the ground, notice the bottom half of the attitude indicator (artificial horizon) has white markings on it on the ground:
![Screenshot (74)](https://user-images.githubusercontent.com/70450099/95019318-a7e70a00-0632-11eb-82f4-9f5079a9de3d.png)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by NathanInnes** [comment]
Do you have another reference other than the FFA320?

**Comment by sef3613** [comment]
Yup. Check out this real PFD video https://youtu.be/ECV3IBkzZLc

**Comment by sef3613** [comment]
https://youtu.be/TEi-WX08ov8
Also notice when they’re flaring and touching down the bottom pitch markers disappear.

**Comment by sef3613** [comment]
![image](https://user-images.githubusercontent.com/70450099/95107555-0fbb5480-0708-11eb-8566-d9bd816cc038.png)
Here's the FSLabs as well

**Comment by sef3613** [comment]
Or here's a real PFD picture posted by FlyingCarpet7 in the FBW discord:
![Uploading image.png…]()
