### ISSUE TITLE
Panel retexturing

### ISSUE THREAD

**Issue by TobitFR** [flybywiresim/a32nx#109]
There is a lot of texture issues in the cockpit, a A320 pilot made a video about it, it will be great if they might be corrected :D

[The video](https://www.youtube.com/watch?v=r0YqBAqsUpg)

**Comment by TobitFR** [comment]
There is also no speed above the isis

**Comment by arvinjarvin** [comment]
Hello.

Thanks for taking the time to raise this issue.

Currently the team is focusing on the core functionality of the Airbus 320, however we will certainly get to this, and improve the modelling, and texturing of the panels.

We have been in touch with Asobo Studios regarding the 3D model raw files, and will keep all updated accordingly!

All the best
Arvin

**Comment by DarkOfNova** [comment]
> There is also no speed above the isis

![speed](https://user-images.githubusercontent.com/70452276/92073419-8254af80-edab-11ea-9778-2b65dad62bf3.png)
:D

**Comment by TobitFR** [comment]
![image](https://user-images.githubusercontent.com/31391535/92178556-19207b00-ee43-11ea-91d5-806a32b5fea2.png)
I don't have it on mine ^^
