### ISSUE TITLE
Managed speed on approach doesn't target VAPP [BUG]

### ISSUE THREAD

**Issue by sef3613** [flybywiresim/a32nx#1091]
**Mod Version**

Latest

**Describe the bug**

When the approach mode is activated in the perf page of the MCDU, the target speed when pushing for managed speed should be VAPP, or V approach. In the fbw a32nx, the speed bug is incorrectly set to VLS, or V landing speed. 

**To Reproduce**

1. Enter approach conditions in the MCDU approach perf page.
2. Ensure approach phase is activated and push for managed speed.
3. Note the speed bug is at VLS instead of VAPP when configured for landing.

**Expected behavior**

Magenta target speed should be set to VAPP when in managed speed on approach.

**Actual behavior**

Magenta target speed is actually set to VLS.

**References**

Here you can see in the MCDU that VLS is 145 and VAPP is 150, and the magenta speed target is at 145 when it should be at 150 (VAPP).
![Screenshot (79)](https://user-images.githubusercontent.com/70450099/95021659-488ff680-0640-11eb-894a-c2bd02140984.png)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by donstim** [comment]
VLS is actually Lowest Selectable Speed, not Landing Speed. It is the lowest speed that can be selected with autothrust enabled.

There is something else wrong with the picture you attached. VLS should be indicated on the PFD with being coincident with the top of the amber band on the speed tape, not above it as shown.

**Comment by sef3613** [comment]
Gotcha my bad. But shouldn't managed speed in the approach phase still put the speed target at VAPP instead of VLS?

**Comment by donstim** [comment]
Yes.
[Airbus_Speed_Tape_On_Descent_and_Arrival_1.pdf](https://github.com/flybywiresim/a32nx/files/5324661/Airbus_Speed_Tape_On_Descent_and_Arrival_1.pdf)

**Comment by sef3613** [comment]
That’s what I thought, seems like the a32nx mod actually targets VLS instead

**Comment by sef3613** [comment]
Cause in my screenshots the magenta target is set to VLS with managed speed on approach. It should be at 150 because that's what the MCDU says VAPP is

**Comment by sef3613** [comment]
Also I think the other parts of the speed tape may have been correct because of how light I was. I found that the VLS/VAPP the MCDU gave me had me almost pitched down and was a similar speed to when I tested this heavy. I don't think the MCDU correctly computes VAPP based on weight because at this same weight the FFA320 gave me a VAPP of only 130 which is 20 knots less.

**Comment by MisterChocker** [comment]
the ap targets the next slowest speed, first GD, S, F, VApp.
