### ISSUE TITLE
Roll stability is exaggerated[BUG]

### ISSUE THREAD

**Issue by sef3613** [flybywiresim/a32nx#1092]
**Mod Version**

Latest

**Describe the bug**

When inputing roll on the sidestick and then letting go, the ailerons flutter back and forth in a very exaggerated way and even sometimes the roll spoilers come on the opposite wing. Notice the comparison videos at the bottom to see the difference.

**To Reproduce**

1. Open flight control ECAM page and note aileron/spoiler behavior when rolling the airplane and then letting go.
2.
3.

**Expected behavior**

Very very very minor aileron flutter when releasing a roll input.

**Actual behavior**

Extreme aileron flutter back and forth and even roll spoiler adding in the opposite direction of the roll once pressure is released from stick. Almost equal deflection of opposite aileron when pressure is released.

**References**

I was doing very similar control inputs in both videos. Note the aileron movements in the a32nx after releasing aileron pressure in the direction of the roll.

https://www.youtube.com/watch?v=-MQMiVgC1fo&feature=youtu.be

https://www.youtube.com/watch?v=9QgqxQAUN20&feature=youtu.be

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by lukasrz** [comment]
I have the same problem, during approach it is terrible to control the plane.

**Comment by MisterChocker** [comment]
seems to be fixed by now
