### ISSUE TITLE
[BUG]CTD after open VFR map in flight

### ISSUE THREAD

**Issue by johnths2** [flybywiresim/a32nx#1094]
**Mod Version**
Version V0.3.1

**Describe the bug**
During a flight from Palma the Mallorca to Valencia after about 15 min of flight the sim craches to desktop after opening the VFR map. I test the flight again with the standard A320 without the  A32NX mod and there was no CTD when opening the VFR map.
I dit the test again with and without the mod and that gave the same result. CTD with mod and no CTD whitout the mod.

**To Reproduce**
1. Start flight from Palma
2. Follow ATC calls and go to 16.000 feet
3. Open VFR map after about 15 min of flight before you pass Ibiza
4. The sim crashes to Desktop after oening of VFR map.

**Expected behavior**
No CTD after opening of VFR map

**Actual behavior**
CTD after opening of VFR map

**References**

**Additional context**

Was this working before/when did the issue start occurring?
It occurs after update of MSFS to the latest release and when a installed version V0.3.1 of the A32NX mod.

Is this a problem in the vanilla unmodded game?
Yes, there are no other mods

Discord johnths2 (if different from GitHub):

**Comment by wpine215** [comment]
This is a recognized issue in the MSFS patch notes for 1.9.3. It's not related to our mod at all - it just happened to crash when you were using our mod.
