### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by yannTravel** [flybywiresim/a32nx#1095]
**Mod Version**

**Describe the bug**

Hi everyone.

I have a problem with my A32Nx .
In flight (often in approach), the A320 cutt off like a « Cold & dark » ( no engine , no screen... nothing).

I only have the last version of A32NX on my Community Folder ( nothing else , no texture add ...) and I don’t use ATC.
Do you know why ?

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by wpine215** [comment]
Turn off all AI/traffic as instructed in the release notes. Please follow the template and include a title next time.
