### ISSUE TITLE
ATHR unstable on TOGA

### ISSUE THREAD

**Issue by ThePilot916** [flybywiresim/a32nx#110]
ATHR oscillates between full throttle and down some percent when on TOGA and no other modes like MCT,CMB etc

**Comment by miniarmagb** [comment]
Mine seems to rev like some boy racer in a car. Was on man FLX and TOGA and still the same

**Comment by ThePilot916** [comment]
The thrust fixes provided in the engines.cfg seems to have damped them down a bit, reduced max_fuel_flow and high_fuel_flow but I found the optimal perf after doubling the drag on the flightmodel, but this doesn't seem like the right fix, core flight drag dynamics probably needs an update from asobo.

**Comment by Curtis-VL** [comment]
Can agree with this, the thrust fluctuates at TOGA, I assumed it my HOTAS at first. :)

**Comment by arvinjarvin** [comment]
Thanks for raising the issue. 

This will be looked into and is common!

**Comment by AdenFlorian** [comment]
Does this issue exist in the vanilla unmodded game, or was it caused by the mod?

**Comment by AdenFlorian** [comment]
Anyone have a repeatable steps to reproduce? I can't recall ever experiencing this issue...

**Comment by AdenFlorian** [comment]
i was able to reproduce by raising the ambient temps in the weather settings

**Comment by AdenFlorian** [comment]
tested taking from arizona with this weather temp setting, and looks good!
![image](https://user-images.githubusercontent.com/3533988/92439458-80566c00-f170-11ea-88f1-5270e3452ab6.png)
