### ISSUE TITLE
Incorrect PFD Flight Director for Takeoff[BUG]

### ISSUE THREAD

**Issue by sef3613** [flybywiresim/a32nx#1101]
**Mod Version**

Latest

**Describe the bug**

On takeoff, the vertical flight director (roll) should only be the runway centerline symbol below the horizon. It should switch to the full vertical flight director when NAV engages.

**To Reproduce**

1. Set FLEX or TOGA and notice flight directors.
2.
3.

**Expected behavior**

The runway centerline symbol should be only below the horizon on the PFD (see pictures below).

**Actual behavior**

The roll (vertical) flight director appears the same as it does in flight.

**References**

![image](https://user-images.githubusercontent.com/70450099/95029620-6e84bd80-0677-11eb-86f5-722a0007d0ae.png)

![Screenshot (82)](https://user-images.githubusercontent.com/70450099/95029630-7c3a4300-0677-11eb-83fc-058203ee0249.png)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Hello, it seems like you have referenced an EIS1 PFD (can be seen with the CRT curves and margins). Could you find a reference using EIS2 (LCD panels) ?

**Comment by NathanInnes** [comment]
![image](https://user-images.githubusercontent.com/18389085/95039438-a2d49a00-06c8-11eb-90fa-4dd8997b0f20.png)

**Comment by sef3613** [comment]
https://www.youtube.com/watch?v=ECV3IBkzZLc&feature=youtu.be
Here's a LCD PFD. And that is correct, if there is no Localizer the FMA should also NOT say RWY.... so since my test screenshot says "RWY", it should have the ground roll guidance command bar

**Comment by sef3613** [comment]
If there's no localizer, the FMA won't say "RWY" and it will just have nav in blue cause it's armed and no roll mode is active. There will also be no ground roll guidance command bar in this case. There will also be no roll command bar at all without a localizer so either way is incorrect on the a32nx.

**Comment by sef3613** [comment]
https://youtu.be/lLJK6Xmi7oA?t=1069 I'm aware this is the FSLabs but it shows the PFD on takeoff from a runway without a localizer.

**Comment by sef3613** [comment]
![](https://user-images.githubusercontent.com/70450099/95107001-4e044400-0707-11eb-90db-3579fec20554.png)
 
notice that even at a runway without a localizer, the PFD incorrectly has a roll flight director

**Comment by MisterChocker** [comment]
using this issue #1145 instead
