### ISSUE TITLE
[REQUEST] Assigning hot keys

### ISSUE THREAD

**Issue by chif4477** [flybywiresim/a32nx#1103]
**Is your feature request related to a problem? Please describe.**

The problem is that there is no ability to assign keys. I would like to customize the joystick or keyboard in this mode.

**Describe the feature you'd like to see implemented**

It would be great to be able to assign keys to the functions of this mod. In the simulator or in the configuration file of this mod or in SPAD next. You're doing a good job. Thanks.

**References**

**Additional context**

Discord username (if different from GitHub):

**Comment by joeherwig** [comment]
Especially for Homecockpit builders it is essential to be able to access the functions explicit so On | Off instead of just Toggle. Toggling then is easy to implement. 

Also buttons like for the MCDU to be assignable to gamecontroller functions are highly appreciated.

**Comment by sidnov** [comment]
The API has been updated significantly over time allowing access to functions in the A32NX through external application. For reference: https://docs.flybywiresim.com/fbw-a32nx/a32nx-api/
https://docs.flybywiresim.com/pilots-corner/a32nx-briefing/a32nx_api/
