### ISSUE TITLE
[BUG] Weather radar scans a 360 degree arc

### ISSUE THREAD

**Issue by Zchulski** [flybywiresim/a32nx#1104]
**Mod Version**

**Describe the bug**
The weather radar scans a 360 degree arc when in reality the weather radar in the neo scans at best maybe 160 degrees.

**To Reproduce**
1. the bug is visible at all times the wx radar is activated
2.
3.

**Expected behavior**

I expect the radar to scan to the edge of the pfd then reverse direction to the other side of the pfd.

**Actual behavior**
The radar refresh scans 360 degrees around the pfd 

**References**

**Additional context**

Was this working before/when did the issue start occurring? unsure

Is this a problem in the vanilla unmodded game? unsure

Discord username (if different from GitHub): ziffel

**Comment by 2hwk** [comment]
Working on this.
