### ISSUE TITLE
[BUG] Hydraulic PTU "barking" only activated for a specific time

### ISSUE THREAD

**Issue by Zchulski** [flybywiresim/a32nx#1105]
**Mod Version**
MASTER

**Describe the bug**
The hydraulic PTU barking sound is only activated for a set period of time

**To Reproduce**
1. Start the number one engine with the number 2 engine off or vice versa
2.
3.

**Expected behavior**
I would expect to hear the PTU any time the hydraulic pressures do not match between the 1 and 3 hydraulic systems

**Actual behavior**
When you start one engine the ptu makes noise for about 10 seconds and stops regardless of the ptu actually being activated

**References**
https://www.youtube.com/watch?v=SCplhq1xoYE

**Additional context**

Was this working before/when did the issue start occurring? since release

Is this a problem in the vanilla unmodded game? yes

Discord username (if different from GitHub): ziffel

**Comment by komp1821** [comment]
> I would expect to hear the PTU any time the hydraulic pressures do not match between the 1 and 3 hydraulic systems

That is a quite simplified view. It is more complex irl. PTU operation is inhibited in specific situations. There is also an ECAM memo for it. Look at the Upper ECAM right memo area after you started first engine. It says PTU INHIBIT after 1st engine start.

![Screenshot 2020-10-05 110740](https://user-images.githubusercontent.com/71044068/95061263-a6cddf80-06fb-11eb-93e8-87d81b5b8e7a.jpg)

**Comment by hotshotp** [comment]
The hydraulic system is currently in work and is being made so it becomes very complex and fully functional

**Comment by beheh** [comment]
@hotshotp This was done, right?

**Comment by hotshotp** [comment]
This has been done with the hydraulic implementation
