### ISSUE TITLE
captain nd is not sync with copliots[BUG]

### ISSUE THREAD

**Issue by lawfulrocky** [flybywiresim/a32nx#1106]
**Mod Version**
dev lastest  10/5/2020 1:49 am est

**Describe the bug**

captain nd is not sync with copilots and dont  go into self check

**To Reproduce**

1.turn off nd many times 
2.reload aircraft
![Screenshot (9)](https://user-images.githubusercontent.com/25673245/95044443-69dafc00-06ad-11eb-9014-b5e731596462.png)

**Expected behavior**
suppose to be sync

**Actual behavior**
unsync

**Comment by NathanInnes** [comment]
If you are referring to the displays not being in sync to the co-pilots then that is a new feature that was implemented. As for the self test, each display is now independent which means each will do their own self test if you turn it off then back on.

**Comment by tareksabet** [comment]
> If you are referring to the displays not being in sync to the co-pilots then that is a new feature that was implemented. As for the self test, each display is now independent which means each will do their own self test if you turn it off then back on.
> 
> Going off of what you described this sounds to be normal :)

He meant that the screens are not showing the same thing with both of them selected in ARC mode and if you concentrate you’re going to find the captain side is showing a thing and the F/O side is showing another thing @NathanInnes

**Comment by rbywater** [comment]
Possibly related might be that I just came across a situation where the pilot's ND is frozen apart from the compass rose on it moving correctly. All other details are frozen as they were before pushback. F/O side is showing correct info but also none of the Constraints/VOR D/buttons are working and neither is LS or Show Terrain - these do not light up and no change on either ND display.

**Comment by jooglestumpe** [comment]
can confirm this
![nd](https://user-images.githubusercontent.com/71871087/95056841-9286e400-06f5-11eb-8125-5438c290fb26.jpg)

**Comment by jooglestumpe** [comment]
Also, can it be that the displays being individual now affects performance quite a bit?

**Comment by NathanInnes** [comment]
> Also, can it be that the displays being individual now affects performance quite a bit?

Yes, but that's a separate issue.
