### ISSUE TITLE
Cabin crew announcement

### ISSUE THREAD

**Issue by lalloretpilou** [flybywiresim/a32nx#1108]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**
Can you automate the cabin crew announcements? 
For example create:
=>Ttake off annoucement when the pilot switch ON the strobe light. 
=> Safety demo when the pilot switch ON engines. 
=> Turbulence announcement when the pilot switch ON seatbelt sign. 
=> Landing announcement when the pilot flaps down ......

**References**

**Additional context**

Discord username (if different from GitHub):

**Comment by aboodilatif** [comment]
Takeoff announcements have been added, press TO config before takeoff
I'm pretty sure landing announcements have been added as well.

**Comment by liebbe10** [comment]
Not the TO config but the Call ALL button on the Overhead in the lower left corner. When the T/O Memo or the Landing Memo is displayed you can press the Call Button and get a Seats for departure/landing message plus the Cabin switches to READY in the Memo.

**Comment by hotshotp** [comment]
T/O and landing announcements have been added if you press any of the call buttons on the overhead panel. I plan to add boarding/deboarding announcements, announcements AFTER landing, and 10,000ft announcements

**Comment by liebbe10** [comment]
@hotshotp Maybe passenger boarding sounds with open doors would be nice too

**Comment by lalloretpilou** [comment]
I think everyone knows the ZIBO 737? we should have the same sound effects in the cabin for the 320 (boarding, cruise, crew annoucment).

**Comment by hotshotp** [comment]
> @hotshotp Maybe passenger boarding sounds with open doors would be nice too

definitely. I plan to have a simvar that gets toggled when the door is open, exactly that.

**Comment by Andydigital** [comment]
These features need to be optional there are already plenty of products available that can do cabin announcements externally. So please give us an option to disable them, thx.

**Comment by msvenm** [comment]
I'll have to agree with @Andydigital , all kind of announcements should be optional. Thank you!

**Comment by jvieira21** [comment]
Yeah what if people don't wanna pay for extras and just use these cabin announcements. I would have to disagree with you
