### ISSUE TITLE
Wrong brightness knob for ND1&2

### ISSUE THREAD

**Issue by g0per** [flybywiresim/a32nx#1109]
**Mod Version** 0.3.1

**Describe the bug**
ND brightness knob is wrongly assigned.

**To Reproduce**

Change ND1 or ND2 brightness with the knobs on the side.

**Expected behavior**

Inner knob regulates display brightness, outer knob regulates WXR overlay contrast. 

**Actual behavior**

Currently only outer knob is animated, but function is inner's.

**References**

(From Aerosoft's Forums)

https://forum.aerosoft.com/uploads/monthly_09_2014/post-43-0-16330700-1411559214.png

**Additional context**

Was this working before/when did the issue start occurring?
 * Since first mod release

Is this a problem in the vanilla unmodded game?
 * No. Not animated in vanilla

----

Discord username (if different from GitHub): paritg#2452

**Comment by NathanInnes** [comment]
```

Inner knob regulates display brightness, outer knob regulates WXR overlay contrast.

```
Are you sure it's not the other way round?

**Comment by g0per** [comment]
Yes I am 100% sure. You pull the small one for regulating brightness.

**Comment by FlyingCarpet7** [comment]
Bug report is correct, well spotted.

From FCOM:

ND Brightness Control Knob

The outer knob controls the brightness of both the weather radar image and EGPWS terrain display.

The inner knob controls the general brightness of the ND symbols.
Rotating this knob all the way counterclockwise switches off the NDU.
