### ISSUE TITLE
Performance decrease of around 20% in FPS and more stutter in latest master[BUG]

### ISSUE THREAD

**Issue by danbw9** [flybywiresim/a32nx#1110]
**Mod Version**

Master downloaded 05/10/2020

**Describe the bug**
Assuming it is the separate FO and CP screens implementation, the performance has decreased a lot and personally I don't think the feature gain is worth it unless there is a workaround. When shared cockpit comes out then for sure. 

**To Reproduce**
Fly any flight and see the performance loss, even when the PFD and ND screens on the FO side are all the way off.

**Expected behavior**
Maybe make it such that if you turn of the FO screens that it does not transmit data. I would expect this

**Actual behavior**
In normal configuration and all screens turned to on, the FPS loss is too much. As mentioned above, if the FO and CP screens are set to OFF and not just dimmed, the performance should be like before.

**Comment by jooglestumpe** [comment]
I can confirm this, unfortunately. Agreed that it's hardly worth the feature, given the general performance of the sim is unstable as it is.

**Comment by Metalix64** [comment]
I get the same issue

**Comment by Barnes62** [comment]
I am also seeing the same loss of frames. Would prefer the feature be removed.

**Comment by c1be** [comment]
Same here. I don't think they should sacrifice fps over anything.

**Comment by Artax04** [comment]
Same here :(

**Comment by MICHER79** [comment]
Hello, in my case the performance decrease is huge, from 35 to 20 fps

**Comment by c1be** [comment]
Yeah, i also have around 10 fps lower than before and more freuqent stutters, funny that in their testing they saw only 1 or 2 fps lower performance. They should really give as separate version or remove it, there's no point in sacrificing perfomance for something majority of us don't really care about, imo. Same goes for any graphical improvements that might affect perfomance, that should be only as and option, but not forced into final version.

**Comment by Benjozork** [comment]
@c1be this is in no way a "final version". You simply cannot expect any software whose version starts with "0" to be stable and bug free.

If the decrease is that bad, download this version from before the PR was merged: https://github.com/flybywiresim/a32nx/archive/daa2a8208c010468af7e65e93ceddae40628c333.zip

**Comment by c1be** [comment]
> @c1be this is in no way a "final version". You simply cannot expect any software whose version starts with "0" to be stable and bug free.
> 
> If the decrease is that bad, download this version from before the PR was merged: https://github.com/flybywiresim/a32nx/archive/daa2a8208c010468af7e65e93ceddae40628c333.zip. However, we will not support any additional bugs found in that version.

It's obvious what i meant by final version, it's the next stable version, and by that i meant that there should be two stable versions. Devs don't have hundreds of systems laying around to test peformance, that's why there is a master version for people here to test it and give feedback. Also, basic game engine understanding would tell you that there's nothing they can do to improve perfomance degradation in this case, separate FO and CP screen implementation causes even more cpu bottleneck which can only be solved by working on a game engine itself, and that's something Asobo must do by implementing dx12, not the flybywire devs.

**Comment by Venorcis** [comment]
Can confirm this gives around a 10FPS drop for me too, not worth it IMO (if it's really just the screen decoupling).

**Comment by ErikNL80** [comment]
I also get a lot of stuttering and performance decrease. Would be nice to have an option to switch this feature on or off.

**Comment by veikkos** [comment]
I think it would be time to implement mod settings menu and allow some configuration like double separated cap/fo screens.

**Comment by nonocaptain** [comment]
I confirm impact on FPS is huge after testing and by night it is worth

**Comment by c1be** [comment]
> I think it would be time to implement mod settings menu and allow some configuration like double separated cap/fo screens.

That would be great!

**Comment by ErikNL80** [comment]
I don't think it is possible yet to add a menu via the SDK... I would make an option page in the MCDU to make this happen.

**Comment by Benjozork** [comment]
>Devs don't have hundreds of systems laying around to test peformance, that's why there is a master version for people here to test it and give feedback

Which is exactly what's happening here.

**Comment by nabil74** [comment]
screen refresh rate of medium appears to reduce the impact of fps issue

**Comment by myselfaaryan** [comment]
> screen refresh rate of medium appears to reduce the impact of fps issue 

Yea, I guess, but it not the point. I would love to set it to high to enjoy the most out of this mod. Maybe, they'll soon get a fix :D

**Comment by c1be** [comment]
> > Devs don't have hundreds of systems laying around to test peformance, that's why there is a master version for people here to test it and give feedback
> 
> 
> 
> Which is exactly what's happening here. We merged something, we are getting feedback.
> 
> 
> 
> > Also, basic game engine understanding would tell you that there's nothing they can do to improve perfomance degradation in this case
> 
> 
> 
> Not really, we can improve the already very inefficient code in the PFD and ND.
> 
> 
> 
> > and that's something Asobo must do by implementing dx12, not the flybywire devs.
> 
> 
> 
> Out of curiousity, could you elaborate on how DX12 solves the issue of the main thread being synced to `CoherentGTDraw` ?

You can improve a little bit, but it's not worth the time, that's just my opinion. As far as i know coherentGTDraw hit gpu, not cpu, but i might be wrong.

**Comment by c1be** [comment]
> > screen refresh rate of medium appears to reduce the impact of fps issue 
> 
> Yea, I guess, but that's not the point. I would love to set it to high to enjoy the most out of this mod. Maybe, they'll soon get a fix 😄

Agreed.

**Comment by aboodilatif** [comment]
> 
> 
> > screen refresh rate of medium appears to reduce the impact of fps issue
> 
> Yea, I guess, but that's not the point. I would love to set it to high to enjoy the most out of this mod. Maybe, they'll soon get a fix 😄

I wouldn't set it to high as it has no added benefit, I believe (someone correct me if I'm wrong please, this was old info on the discord) that the medium setting draws still has a higher refresh rate than the IRL a320.

**Comment by ErikNL80** [comment]
I have refresh rate already on medium, and still a huge impact on FPS. In the mean time, would it be possible working with 2 branches? One 'normal' and one 'shared cockpit' with seperate screens?

**Comment by c1be** [comment]
> I have refresh rate already on medium, and still a huge impact on FPS. In the mean time, would it be possible working with 2 branches? One 'normal' and one 'shared cockpit' with seperate screens?

That would be the best solution, conpletely separate version for shared cockpit, so people can decide for themselves. Medium setting does improve fps a little bit in my case also, but i'm more worried about stutters, they're much more frequent than before, doesn't matter what refresh rate setting you use.

**Comment by veikkos** [comment]
> I have refresh rate already on medium, and still a huge impact on FPS. In the mean time, would it be possible working with 2 branches? One 'normal' and one 'shared cockpit' with seperate screens?

Branching is not scalable or sustainable solution. Only static (config file) or way better runtime options can be seriously considered.

**Comment by ErikNL80** [comment]
Best option would be an integration with an in-game option in the MCDU for example. But don't know if that is possible...

**Comment by ErikNL80** [comment]
> @c1be this is in no way a "final version". You simply cannot expect any software whose version starts with "0" to be stable and bug free.
> 
> If the decrease is that bad, download this version from before the PR was merged: https://github.com/flybywiresim/a32nx/archive/daa2a8208c010468af7e65e93ceddae40628c333.zip. However, we will not support any additional bugs found in that version.

I tested this version, but it has some issues with terrain not showing and the EFIS is not working (buttons, range). Is there a way to select another DEV branche or just stick to 0.3.1?

**Comment by Artax04** [comment]
> > I have refresh rate already on medium, and still a huge impact on FPS. In the mean time, would it be possible working with 2 branches? One 'normal' and one 'shared cockpit' with seperate screens?
> 
> That would be the best solution, conpletely separate version for shared cockpit, so people can decide for themselves. Medium setting does improve fps a little bit in my case also, but i'm more worried about stutters, they're much more frequent than before, doesn't matter what refresh rate setting you use.

Yeah, stutter increase A LOT, is still playable but last versions got tons of more stutter.
I have old cpu, so i play with low in cockpit refresh, still, i got lot less performance than before.
As far as, thank you all for the job, you made this game playable and enjoyable with this addon guys

**Comment by rbywater** [comment]
> Best option would be an integration with an in-game option in the MCDU for example. But don't know if that is possible...

I believe (haven't seen it - only read it in the docs) that the Salty 747 project has a menu option on the MCDU so sounds possible and would definitely be a good place to stick options if they can be saved between sessions.

**Comment by ErikNL80** [comment]
That is good news... I hope they will revert the changes for now, the plane is not flyable now. Way too much lag and stuttering.

**Comment by c1be** [comment]
> > I have refresh rate already on medium, and still a huge impact on FPS. In the mean time, would it be possible working with 2 branches? One 'normal' and one 'shared cockpit' with seperate screens?
> 
> 
> 
> Branching is not scalable or sustainable solution. Only static (config file) or way better runtime options can be seriously considered.

I don't expect this feature to find it's way into the next stable version, unless they find a way to add some kind of menu option or something like that. Perfomance loss is just too much for a feature very small number of people will ever use, it's just not worth it, and as far as i now, shared cockpit is not even possible right now, but i'm not too sure.

**Comment by myselfaaryan** [comment]
I would really like that. To be honest, the 320neo is the only aircraft I love flying and more than that, I love that this mod exists. The master branch does have bugs, but they are worth it. However, on the side note, public test will not be possible with significant performance issues. I really appreciate the developers here spending their time and resources.

**Comment by Pleasure0102** [comment]
guys, we have understood that you have performance issues, the master is not a version that is released to stable, we appreciate the feedback.. but suggestions that this should be disabled so you can play with more fps is ridiculous. The goal is not to disable the system, but to improve the code so the fps issues will be less. We cannot make an option to disable every single thing some people dont like.. do you want us to change the textures to 256x256 so you can run it on your old dos machine too ?

**Comment by c1be** [comment]
> guys, we have understood that you have performance issues, the master is not a version that is released to stable, we appreciate the feedback.. but suggestions that this should be disabled so you can play with more fps is ridiculous. The goal is not to disable the system, but to improve the code so the fps issues will be less. We cannot make an option to disable every single thing some people dont like.. do you want us to change the textures to 256x256 so you can run it on your old dos machine too ?

You are aware not everyone have rtx2080 and 9900k to sacrifice fps for something that's not really needed. I'm really interested how many people even asked for it. This is about significant perfomance loss, not an issue of not liking something, there's a big difference between those two. I really doubt there's people around saying flight model is shit, but it doesn't matter, we finally have separate CP and FO screens!

**Comment by NathanInnes** [comment]
Please keep chatter to a minimum.

**Comment by Pleasure0102** [comment]
> > guys, we have understood that you have performance issues, the master is not a version that is released to stable, we appreciate the feedback.. but suggestions that this should be disabled so you can play with more fps is ridiculous. The goal is not to disable the system, but to improve the code so the fps issues will be less. We cannot make an option to disable every single thing some people dont like.. do you want us to change the textures to 256x256 so you can run it on your old dos machine too ?
> 
> You are aware not everyone have rtx2080 and 9900k to sacrifice fps for something that's not really needed. I'm really interested how many people even asked for it. This is about significant perfomance loss, not an issue of not liking something, there's a big difference between those two. I really doubt there's people around saying flight model is shit, but it doesn't matter, we finally have separate CP and FO screens!

i agree, the report is justified, but what else can be said other than it is being worked on.

**Comment by wpine215** [comment]
This issue is getting out of hand. Will be locking it for the time being until further updates are available.

**Comment by Benjozork** [comment]
Please advise of the following PR and report if you get any improvements:

https://github.com/flybywiresim/a32nx/pull/1163
