### ISSUE TITLE
[BUG] Plane nose is extremely pointed down

### ISSUE THREAD

**Issue by lukasrz** [flybywiresim/a32nx#1111]
**Mod Version**

0.3.1 from 03 october 2020

**Describe the bug**

Did you noticed, that during normal descend, or little faster ~2000ft/min, plane nose i extremely pointed down? 

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

It looks like this, or even more.
![a32](https://user-images.githubusercontent.com/70447248/95088262-025f9380-0723-11eb-9396-63ca2fcab518.jpg)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Ares1378** [comment]
I can confirm this. I will explain this more in detail. It seems the flaps are generating too much lift? The aircraft on approach is -15 NOSE down pitch MAX down pitch in normal law to obtain -1000fpm descent. This is incorrect. The aircrafts normal pitch attitude on approach is 2 to 2.5 nose up.

**Comment by theersink** [comment]
Others reported similar. Look at the end of #1053 for possible fix. Flightmodel essentially needs to be fixed by Asobo, other than the ground handling after 1.9.3 the mod uses the default.

**Comment by Benjozork** [comment]
Please respect the issue template. Will close until that is done.
