### ISSUE TITLE
[BUG] GPU Packs Audio delay after switching view

### ISSUE THREAD

**Issue by CoffeePanda0** [flybywiresim/a32nx#1113]
**Mod Version**

Latest Master Branch

**Describe the bug**

When you can hear the GPU air conditioning and switch view, the sound stops and there is a 10 second delay or so until the pax sounds start again

**To Reproduce**

1. Spawn cold and dark
2. Turn on GPU and batteries
3. Switch view to external and then back to cockpit
4. Listen and the air conditioning sound does not return for a few seconds

**Expected behavior**

The air conditioning sound in the cockpit is continuous

**Actual behavior**

After switching views, there is a delay until the sound starts again

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Latest master

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub): obama#6262

**Comment by hotshotp** [comment]
Already known. I have already fixed this on my end and this bug will be gone in my next PR :)
