### ISSUE TITLE
[BUG] Dual engine failure during flight

### ISSUE THREAD

**Issue by aviationenthusiast** [flybywiresim/a32nx#1115]
**Mod Version**

latest master, but also on previous versions.
Since the latest 1.9.3.0 release.

**Describe the bug**

See the video below. N2 and engine temperatures suddenly drop and both engines fail.
Tried with and without anti icing. and with and without icing settings in the settings.

**To Reproduce**

I got it first once like 3 days ago on a different flight, restarted the flight and it worked without issues.
But today I restarted this flight like 5 times and it would happen around the 8 minute mark after takeoff.
1. start a flight from EDDF to EHAM. Low altitude airways. Gate A18 Medium direct to direct ILS 27. Fuel at 9% and sky conditions high level clouds.
2. start from cold and dark get jetway baggage catering and taxi to runway 25C.
3. take off turn on autopilot follow altitudes and set throttle CLB.

**Expected behavior**

The engines shouldn't fail.

**Actual behavior**

They fail.

**References**

https://vimeo.com/465047506

**Additional context**

Livery Ryan Air. AI traffic and ground aircraft off
will test next without the livery.
**UPDATE: still the same problem without any liveries.**

Was this working before/when did the issue start occurring?
it was working before.

Is this a problem in the vanilla unmodded game?
not sure. I will do more testing.
**UPDATE:** **i tried same settings with the plain vanilla game and the left engine dies on me shortly after startup.**

Discord username (if different from GitHub):

**Comment by NickyNiclas** [comment]
Here is a working link to the video https://vimeo.com/465047506

**Comment by aviationenthusiast** [comment]
> 
> 
> Here is a working link to the video https://vimeo.com/465047506

updated, thank you.

**Comment by aviationenthusiast** [comment]
Update: I think it may be related to fuel. When I start with 9% engines always fail around 6%. And today when i almost ran out of fuel during a long flight i increased it to like 12% until i almost ran out again and nothing happened. But when i increased it again to like 5% the engines immediately failed.

**Comment by lousybyte** [comment]
Had this happened twice myself, it looked like fuel issue indeed.

**Comment by willisb12** [comment]
Had this happen twice as well, both when on approach after short haul flight (LFPG to EGLL with 12% fuel at takeoff). Engines fail and all displays go black. Displays turn back on with APU. FCU input still works and plane follows correct navigation and approach until the plane can no longer maintain lift.

**Comment by ChrisDeadman** [comment]
I had the same issue twice now - it always happens for me when the inner wing tanks run empty, fuel from outer wings is there but unaccessible. Also crossfeed is not working if only one of the inner tanks run empty (turning the pump off in the empty tank does not fill it when crossfeed and other pumps are enabled)

**Comment by NickyNiclas** [comment]
@ChrisDeadman so the issue has moved from the center tank to the inner wing tanks after the patch. Interesting..

**Comment by ChrisDeadman** [comment]
@NickyNiclas When I tested I had center tank always empty, fuel only in inner and outer wing tanks

**Comment by SeanHanway** [comment]
Just had this happen to myself as well, no way to bleed fuel from the outer tanks to the inner tanks and the engines shut off even with both outer tanks full as soon as the inner tanks go to empty. I always fly with center tank empty so that's out of the equation here.

**Comment by 2hwk** [comment]
As per linked issue, likely fixed in an Asobo update. Will reopen if this reoccurs (fuel system tends to be a bit temperamental and causes issues from time to time, similar issue occured in an old version)

**Comment by timothyj6767** [comment]
I had this happen to me the other day while in flight at cruise altitude

**Comment by wlouckx** [comment]
Fairly similar, dual engine failure happened to me a couple of flights. I can start them again (start apu, open apu bleed, start engines) but sometimes they fail again after a while, sometimes they don't. I think it only happens with Anti Ice on (as required, flying through clouds when it's freezing), but not 100% sure.

**Comment by bucmic** [comment]
With latest MSFS 2020 and FBW A320 developer and experimental version I currently have this issue.
Fuel settings are MSFS default but ECAM is showing almost no fuel loaded.

**Comment by bucmic04** [comment]
With latest MSFS 2020 and FBW A320 developer and experimental version I currently have this issue.
Fuel settings are MSFS default but ECAM is showing almost no fuel loaded.
