### ISSUE TITLE
Autothrust Climb Logic when Hand-flying (part 2)[BUG]

### ISSUE THREAD

**Issue by sef3613** [flybywiresim/a32nx#1119]
**Mod Version**

Latest

**Describe the bug**

I made a bug report about this before but I've done some more testing and have included videos this time. When hand flying in managed climb (and managed speed) and "THR CLB," the autothrust adjusts engine power as you reach the target speed (250 knots usually) to hold airspeed. This is incorrect. The autothrust should hold climb thrust constant and upon reaching target speed, the flight directors should command a pitch up to hold airspeed. 
**To Reproduce**

1. Takeoff, reduce thrust levers to "climb" detent when instructed by the FMA.
2. Hand fly in managed climb (and managed speed) and notice the engine behavior when the airplane accelerates to 250 knots (or whatever the speed bug is set at).
3.

**Expected behavior**

When in "THR CLB," the engines should remain at the climb thrust setting. When the plane accelerates to the managed target climb speed, the flight directors should command a pitch up attitude to hold airspeed. The engines should REMAIN in climb thrust unless switching to "SPEED" mode. See video.

**Actual behavior**

The engines spool back when reaching target airspeed in "THR CLB" mode. This behavior is acting as if the autothrust is in SPEED mode. See video.

**References**

Here is a departure in the a32nx. Watch as I reach 250 knots, the engines in "THR CLB" DECREASE POWER at the timestamp 1:57. They should be holding the climb thrust setting while in "THR CLB." Notice how they only return to climb thrust if I pitch up to slow the airplane well below 250 knots. This makes it impossible to hold a target airspeed when handflying in this scenario. 

https://www.youtube.com/watch?v=l8lAuukhIzc&feature=youtu.be

Here is the FFA320 in XP11 doing the same departure from Denver. Note that the engines remain at the same climb power setting even as I accelerate and slightly overspeed 250 knots at timestamp 2:08. You can see that the autothrust isn't trying to hold airspeed as it is in the video above. Note, this is consistent behavior on the FFA320, Toliss products, FSLabs, and videos I've seen of the real airplane.

 https://www.youtube.com/watch?v=o8WsN0dHgFY&feature=youtu.be

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by bisinchi** [comment]
Even though the behavior much better on version 0.4, there is still an issue. After reducing thrust to CLB detent, thrust is reduced about 5sec later to around 60%, then goes back to expected Max N1 thrust for CLB detent. It takes about 15 sec to go back to expected value.

**Comment by TabsAZ** [comment]
Is this intended to be fixed? Sorta can't believe it hasn't been addressed yet (does no one hand fly departures lol?). Noticed it immediately too. This should behave exactly as @sef3613 says - thrust should be held constant at the climb N1 limit and the FD should command pitch to control airspeed. For some reason in manual flight with the AP off, this isn't the case and it acts as if it's in the SPEED autothrust mode mode where the thrust retards to maintain airspeed instead of commanding pitch to control it. If the AP is on it works correctly and the thrust goes back up to the limit and it commands pitch.

**Comment by tracernz** [comment]
Fixed in custom autopilot (experimental version).

**Comment by TabsAZ** [comment]
Ah ok, I'll give that a shot (was on dev build).
