### ISSUE TITLE
Plane's climbrate is out of the enveloppe [BUG]

### ISSUE THREAD

**Issue by vlbreda** [flybywiresim/a32nx#1122]
**Mod Version**

master

**Describe the bug**

When engaging the a/p after take-off (1500 ft agl, flaps retracted) the plane tends to climb at a very high rate. I think there is a correlation with the managed climb speed, which isn't met after take-off. The plane flies at a lower speed than it should be doing.

**To Reproduce**

1. Take-off, with loaded flightplan and assigned altitude installed
2. Climb to 1500 feet agl, retract flaps, engage a/p and set altitude to managed mode
3. Plane climbs at a much higher rate than in reality. Very high pitch. Would not feel very nice in real life.

**Expected behavior**

A climb to the dedignated altitude at managed climb speed, with plane's pitch not exceeding appr. 10 degrees

**Actual behavior**

Plane climbs at a much higher rate than in reality. Very high pitch. 

**References**

**Additional context**

Was this working before/when did the issue start occurring?
has been a problem since the launch

Is this a problem in the vanilla unmodded game?
Yes

Discord username (if different from GitHub):

**Comment by lawfulrocky** [comment]
it is a Asobo bug with the autopilot . The autopilot isnt being work on untill flight by wire is down. i suggest do V/s climb until it is fix

**Comment by MisterChocker** [comment]
has been fixed
