### ISSUE TITLE
MCDU and right ND freeze when choosing arrival runway and transition.[BUG]

### ISSUE THREAD

**Issue by krieke58** [flybywiresim/a32nx#1123]
**Mod Version**

Both master and stable version 0.3.1

**Describe the bug**

When approaching TOD or later in the flight I want to choose the landing runway, SID and/or transition.
After choosing the runway and transition I click on "insert".
After this the MCDU freezes. There is a black screen with "UNTITLED" as title.
Also the right pilot ND freezes (route), some things still move, but not the route. Distance to next waypoint also frozen.
Left ND is OK.

**Screenshot:**
![MCDU Freeze](https://user-images.githubusercontent.com/72417680/95136203-fb0da980-0765-11eb-832c-06618ee0de86.jpg)

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring? 
It was working before but already tried 7 flights ... same issue.

Is this a problem in the vanilla unmodded game? 
Use to try the master version but switched to the stable version, but no difference.

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment]
Can you please recheck with latest master or stable (0.5.1)?

**Comment by MisterChocker** [comment]
Closing since no response from op.
