### ISSUE TITLE
Open/unlocked doors should be AMBER in lower ECAM page, they are green instead[BUG]

### ISSUE THREAD

**Issue by CaptainStraw** [flybywiresim/a32nx#1124]
**Mod Version**

master

**Describe the bug**

The lower ECAM door page shows locked or unlocked door information. All real-life references show that open door indicators should be AMBER, but they appear GREEN here.

**To Reproduce**

1. Start Cold & Dark in any airport gate
2. Turn on batteries
3. Activate Ground Power
4. Ask ground services to connect jetway, start catering service or baggage service.
5. ECAM door page will show that open/unlocked doors are green.

**Expected behavior**

ECAM door page should show AMBER instead of green for any open/unlocked doors.

**Actual behavior**

ECAM door page shows open/unlocked doors in green, as shown in this picture:
![94969601-a7cafb00-04c8-11eb-8d85-b7e2fa528e83](https://user-images.githubusercontent.com/8702738/95136337-90d81300-072b-11eb-88e4-954c805915d2.png)

**References**

Here's an explanation of how it should actually be: 
<img width="431" alt="94969325-25423b80-04c8-11eb-93cc-7dec52a1b7f0" src="https://user-images.githubusercontent.com/8702738/95134433-7cdee200-0728-11eb-9a1a-5a3d091edac9.png">

And some other references:
https://www.youtube.com/watch?v=Mo7A3CuVb8g&t=105s
http://theflyingengineer.com/projects/airbus-tech/doors/
http://mcdu.equicom.net/blog20150715.php

**Additional context**

The color used to be right in previous builds. Not exactly sure why it changed. Probably related to #911 or #937 ? 
A real A320neo pilot's input would be really helpful.

I've managed to fix the problem locally simply by changing a line in this file:
`\A32NX\html_ui\Pages\VCockpit\Instruments\Airliners\A320_Neo\EICAS\ECAM\A320_Neo_LowerECAM_DOOR.css`

However, I don't have a lot of experience with GitHub to create PRs.

If this is NOT a bug/problem, and the actual A320neo behaves like this color-wise, please consider this issue closed.

Is this a problem in the vanilla unmodded game?
Vanilla doesn't have ECAM door page.

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
![image](https://user-images.githubusercontent.com/4503241/95138985-86247a80-0739-11eb-8cdc-1a2df11e52c3.png)

PR coming soon.

**Comment by Benjozork** [comment]
Confirmed this is accurate, Ares#3394 on discord says they are amber.

https://discordapp.com/channels/738864299392630914/750095266937438258/762413796261101590
