### ISSUE TITLE
[REQUEST] Correct functionality of ATC “CLR” key

### ISSUE THREAD

**Issue by FlyingCarpet7** [flybywiresim/a32nx#1126]
**Is your feature request related to a problem? Please describe.**

Request the correct functionality of ATC (Transponder) “CLR” key.

**Describe the feature you'd like to see implemented**

The correct functionality of the ATC “CLR” key is as follows:
Press The CLR key one time delete the last entered number.
Press a second time deletes all entered numbers.
If not a full set of four numbers are inserted within a certain time (not sure but estimate to 10 seconds) the previous code will be displayed again.

Note: The code “2000” is a normal code to have at startup. It is often selected just prior going from Auto/On to Stand By.

**References**

IRL A320 pilot.
From FCOM:
CLR Key
The flight crew uses this key to clear the code display.
Note: As long as the four figures of the new code are not entirely written, the previous code remains.

**Additional context**

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
This is a bug report, not a feature request.
