### ISSUE TITLE
[BUG] Functionality of the ATC “CLR” key

### ISSUE THREAD

**Issue by FlyingCarpet7** [flybywiresim/a32nx#1127]
**Mod Version**

0.3.1

**Describe the bug**

With the CLR key today just one digit at a time is cleared and replaced with a dash.

**To Reproduce**

**Expected behavior**

The correct functionality of the ATC “CLR” key is as follows:
Press The CLR key one time delete the last entered number.
Press a second time deletes all entered numbers.
There should not be dashes in stead of numbers when cleared.
If not a full set of four numbers are inserted within a certain time (not sure but estimate to 5 seconds) the previous code will be displayed again.

Note: The code “2000” is a normal code to have at startup. It is often selected just prior going from Auto/On to Stand By.

**Actual behavior**

With the CLR key today just one digit at a time is cleared and replaced with a dash.

**References**

I am a IRL A320 pilot.
From FCOM:
CLR Key
The flight crew uses this key to clear the code display.
Note: As long as the four figures of the new code are not entirely written, the previous code remains.

**Additional context**

Was this working before/when did the issue start occurring?
Never worked before

Is this a problem in the vanilla unmodded game?
Yes

Discord username (if different from GitHub):

**Comment by paul92ilm** [comment]
Working on this issue

**Comment by beheh** [comment]
After more feedback from @FlyingCarpet7, this is not fully fixed yet, as also outlined towards the end of #1570:
- The dashes should be removed so that missing digits are blank
- The old squawk should remain in memory and reappear after 5 seconds.

Reference footage:
https://discord.com/channels/738864299392630914/758149448399847424/813012021725495296
