### ISSUE TITLE
[BUG] A320 pitches down aggressively

### ISSUE THREAD

**Issue by mateoriddl** [flybywiresim/a32nx#1129]
**Mod Version**

V0.3.1
**Describe the bug**

When disengaging the autopilot, the aircraft falls out of the sky until an inevitable crash. It immediately pitches down about -1500 fpm. I have tried pitching pulling back on my yoke on multiple occasions, but I have only been able to save the aircraft once out of 5 different approaches.

**To Reproduce**

1. On ILS approach to an ILS capable airport, around 1000 feet.
2. Disable autopilot at 1000 feet for manual landing. 

**Expected behavior**

Full control of the aircraft, able to pitch up and control descent for landing.

**Actual behavior**

Aircraft nosedives heavily and crashes.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
This issue started happening right after I downloaded V0.3.1.
Is this a problem in the vanilla unmodded game?
No.

Discord username (if different from GitHub):

**Comment by eduardogbsouza** [comment]
Same for me.  

But in oficial FS forum, very pilots have the same bug.

**Comment by davydecorps** [comment]
Agreed. Full stick aft no effect. Can only save the plane using trim up.

**Comment by lukasrz** [comment]
Yes, I have the same. Normal descend rate 1000ft/min full flaps, a nose down like tomahawk rocket. It's big bug. To much lift even on flaps 1. It look normal only with retracted flaps.

**Comment by PiotrMKG** [comment]
I did have this issue, but now I haven't yet experienced it. There is walkaround for it, at least it worked for me, disengage auto throttle.

**Comment by Benjozork** [comment]
I have not seen this bug happen again since MSFS update, gonna close. Re-open if it happens again.
