### ISSUE TITLE
[BUG] Unusual flight model behavior when MCDU in Takeoff PERF with Throttle set to climb.

### ISSUE THREAD

**Issue by mak60062** [flybywiresim/a32nx#1133]
**Mod Version**

master (10/5/2020)

**Describe the bug**

Aircraft looses nose-up elevator control and descends at ~1500 FPM at ~200kts with 10 degrees nose-up attitude when MCDU PERF is set to takeoff and throttle set to Climb detent. Appears to be related to MCDU PERF not switching from Takeoff to Climb mode after takeoff. 

**To Reproduce**

1.Start plane on runway or at gate.
2.Do not set a "THR RED/ACC" speed
3.Takeoff either with TOGA or FLX MCT throttle setting in managed speed mode
4. Reduce throttle to CLB at ~1300 ft AGL with a 10 degree nose-up pitch attitude

**Expected behavior**

MCDU PERF should switch from take off to climb when throttle is reduced to CLB and update the A/THR target speed to the Climb Speed

**Actual behavior**

MCDU Remains in Takeoff PERF and A/THR speed targets V2+1, even with flaps up. Additionally, the aircraft will descend at about 1500FPM with a 10 degree pitch nose-up attitude at 200 knots and the joystick will no longer allow pitch to increase beyond ~8 degrees nose-up. Upon putting the throttle back to TOGO the joystick regains normal elevator functionality.  

**References**

https://www.youtube.com/watch?v=pOfy_BF67k8

**Additional context**

I think this could be a result of the MCDU not switching to CLB mode when throttle is brought back to Climb, or when the gear is retracted. 

Was this working before/when did the issue start occurring?
First noticed after 1.9.3
I am running the latest master, and this has occurred for me in all masters since 1.9.3

Is this a problem in the vanilla unmodded game?
No, in vanilla the MCDU switches to Climb PERF after the wheels leave the runway. 

I also noticed that in vanilla THR RED/ACC defaults to 1500, but in a32nx it defaults blank. Unknown if related to the issue, just wanted to mention it. 

Discord username (if different from GitHub): COVID_19_Fox3#6734

**Comment by Benjozork** [comment]
Please add a title and fill out the remaining "Mod Version" and "Describe the bug" sections.

**Comment by mak60062** [comment]
> Please add a title and fill out the remaining "Mod Version" and "Describe the bug" sections.

Fixed. Sorry about that.

**Comment by Benjozork** [comment]
No worries !

**Comment by starvingjavi** [comment]
From discord qa chat: Known issue of the plane not changing to clb mode since it follows the altitude set on the Take off perf. the way to fix it would be that when the throttle is moved to clb position it should then change to climb mode on the mcdu. Instead of only following the altitude set of thrust red/acc

**Comment by MisterChocker** [comment]
most likely to be fixed by various flight model improvements
