### ISSUE TITLE
[BUG] V/S must be reset every time the altitude is changed

### ISSUE THREAD

**Issue by andrewortman** [flybywiresim/a32nx#1134]
**Mod Version**

master - https://github.com/flybywiresim/a32nx/commit/a22b4b623334c3729e3e700c6a2c6a3c280e92c2

**Describe the bug**

When using V/S climb mode, every change to the altitimer resets V/S back into LVL/CH mode immediately, even during a climb

**To Reproduce**

1. At FL50, set alt to 15000, while throttle in CLB mode
2. Enable Selected V/S mode at +2000 FPM
3. Observe climb rate set to 2000FPM
4. Change alt to 16000 at FL60, observe immediate pitch up as climb mode reset to FL/CH

**Expected behavior**

I am not a pilot, so I'm not sure if this is expected behavior or not

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Not sure exactly when, but I noticed the issue first in the master revision  - https://github.com/flybywiresim/a32nx/commit/a22b4b623334c3729e3e700c6a2c6a3c280e92c2

Is this a problem in the vanilla unmodded game?
Yes, this is the only addon

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
> Is this a problem in the vanilla unmodded game?

Please fill out this section.

**Comment by andrewortman** [comment]
My bad, thanks! Updated

**Comment by danbw9** [comment]
Can confirm this is an issue and does not match the real aircraft. It should not change the vertical mode away from V/S if another ALT/FL is selected.

**Comment by ElSrJuez** [comment]
I confirm this is an issue, I was descending yesterday and decided to adjust V/S, I had to re-enable V/S mode and enter a new value every short while, not sure what triggers it , 
It happens in Default Asobo A320 as well.

**Comment by aguther** [comment]
This will be fixed by the custom autopilot system.
