### ISSUE TITLE
[BUG] MCDU does not show all approaches

### ISSUE THREAD

**Issue by Watsi01** [flybywiresim/a32nx#1139]
**Mod Version**
current master

**Describe the bug**
On my way to Paris (LPTG). It's wind from the west and my MCDU only shows 08 and 09 approaches, no 26 or 27 approaches (STAR: DINA8J, which is a STAR for all Rwys)

**To Reproduce**

1. Plan a flight to LPTG
2. Maybe use the same STAR (see above)
3. Check out the approach options MCDU is giving you.

**Expected behavior**
Should show all approaches available

**Actual behavior**
see above

**References**

**Additional context**
Don't know if it's an A32NX or a vanilla issue.

Was this working before/when did the issue start occurring?
First time I'm seeing this.

**Comment by ACSoft47** [comment]
I remarked that since day one. This is a bug in the Asobo nav datas.
Lets hope this will be corrected with future nav datas update.
REM: If you use Navigraph beta, data will be OK for LFPG.

**Comment by lousybyte** [comment]
Already reported in #1020, closing as duplicate.
