### ISSUE TITLE
MCDU - airways not accepted

### ISSUE THREAD

**Issue by EDKL1980** [flybywiresim/a32nx#1140]
**Mod Version**
Master

**Describe the bug**
When you enter a new route in the MCDU and you select a SID and want to add an airway to the next waypoint, the MCDU says "not in database". You you can add only direct waypoints. 

**To Reproduce**

1. start anywhere and start feeding the MCDU with SIDs
2. then click on the last sid Waypoint and click airways
3. try to enter a new airway

**Expected behavior**

MCDU should accept airways

**Actual behavior**

MCDU is not accepting airways

**References**

**Additional context**

nothing else to be added

Was this working before/when did the issue start occurring?
No

Is this a problem in the vanilla unmodded game?
i think so 

Discord username (if different from GitHub):
EDKL1980

**Comment by mc130h** [comment]
Ive had this issue, though, as you put in the airway and press the correct button along the side to enter in the [  ] nothing shows up. Enter the waypoint on the right side as you would in the next step. Sometimes once that is done they'll both display as they should, other times when you view the flight plan it is there.

**Comment by lukecologne** [comment]
Fixed in #1460
