### ISSUE TITLE
[BUG] Installer Security Issue

### ISSUE THREAD

**Issue by johnwillimas** [flybywiresim/a32nx#1143]
Installer
**Mod Version**

Installer initial version announced in Discord @Progress

**Describe the bug**

The installer available at https://github.com/Externoak/A32NX-installer/releases/download/0.1/A32NX_Downloader.zip is flagged by Windows Defender as having a Trojan virus.

**To Reproduce**

1. Download installer zip.
2. Extract installer file.
3. Attempt to run it.

**Expected behavior**

The programme should execute and install the latest version of A32NX (as I understand it).

**Actual behavior**

Windows Defender announces that the file has a virus and deletes it.

**References**

**Additional context**

Was this working before/when did the issue start occurring?

First occasion.

Is this a problem in the vanilla unmodded game?

N/A

Discord username (if different from GitHub):

**Comment by NathanInnes** [comment]
This repository doesn't have control over that. Please post your issue here instead. https://github.com/Externoak/A32NX-installer
