### ISSUE TITLE
[BUG] ADF/VOR switch freezes PFD

### ISSUE THREAD

**Issue by SgtNikeR** [flybywiresim/a32nx#1146]
**Mod Version**
Master

**Describe the bug**
Switching on ADF/VOR display selector for PFD freezes PFD instead of showing VOR or ADF freq and DME at the left bottom of the screen. 

**To Reproduce**
1. Fly anywhere
2. During the flight switch either ADF or VOR selector
3. Observe your PFD as it is freezed

**Expected behavior**
PFD not to freeze and to show actual ADF/VOR freq and DME

**Actual behavior**
PFD freezes

**References**
https://streamable.com/dnr2d2

**Additional context**

Was this working before/when did the issue start occurring?
Yes

Is this a problem in the vanilla unmodded game?
No, related to this mod

Discord username (if different from GitHub): Nikodem Rudziński#7173

**Comment by tareksabet** [comment]
Hello, can you confirm on which master version are you on and are you using any AI traffic ore any fps fix.

**Comment by NathanInnes** [comment]
Duplicate issue of #1071. Closing.
