### ISSUE TITLE
Rudder Trim not working in flight when AP engaged [BUG]

### ISSUE THREAD

**Issue by ed42t** [flybywiresim/a32nx#1147]
**Mod Version**

Master

**Describe the bug**

Rudder trim control does not work in flight. 

I had an engine failure on take off today and wanted to trim the rudder for one engine flight. Engaged the AP to free my hands then went to trim the aircraft however the dial did nothing (indicator stayed on 0). Not sure if that is expected IRL behaviour.

Recreated the problem by shutting down one engine on my next flight and noted that before AP engaged it works (and that any value imputed stays if pre-selected). Interestingly the model appears to cancel the trim when AP engaged and put it back when disconnected however the F/CTL ECAM page shows rudder deflection with AP on but no input with trim. Again not sure what the IRL behaviour is here.

**To Reproduce**

1. Take off, random engine failure (or switch off one engine to recreate)
2. Positive rate, gear up
3. Engage AP
4. Try to trim rudder

**Expected behavior**

Rudder to trim (or at least pre-set itself for when AP is disconnected). 
// If that is correct IRL then I would expect F/CTL ECAM to show deflection when rudder trimmed (with AP off)

**Actual behavior**

Rudder cannot be trimmed and stays at 0 //
No rudder movement seen on F/CTL when rudder is trimmed (rudder on the model moves)

**References**

https://www.youtube.com/watch?v=KyWBCiQYRVM - Engine out procedure guide

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by NathanInnes** [comment]
Working as intended. In the video they set the rudder trim before turning AP1 on.

Section from FCOM also states 
![image](https://user-images.githubusercontent.com/18389085/95274171-0089f300-083d-11eb-913f-a8f8f008b9e5.png)
