### ISSUE TITLE
[BUG] Flaps Retracted approach speed is not followed

### ISSUE THREAD

**Issue by veikkos** [flybywiresim/a32nx#1149]
**Mod Version**

master

**Describe the bug**

Flaps Retracted approach speed is not followed in managed speed mode. Speeds with flaps down are followed as expected. See image.

**To Reproduce**

1. Approach RWY
2. Check managed speed before extracting any flaps/slats.

**Expected behavior**

Clean (O) speed should be followed by the plane.

**Actual behavior**

Approx 15 kt lower speed is followed by the plane.

**References**

![kuva](https://user-images.githubusercontent.com/24453333/95243346-2e5d4080-0819-11eb-976b-986df52c57c9.png)

**Additional context**

Was this working before/when did the issue start occurring?
_Not sure._

Is this a problem in the vanilla unmodded game?
_Not sure._

Discord username (if different from GitHub): _VeGe-#4631_

**Comment by veikkos** [comment]
MCDU shows Green Dot Speed (`mcdu.getPerfGreenDotSpeed()`) but plane flies Clean Approach Speed ( `this.getCleanApproachSpeed()`). I guess latter is just incorrectly calculated?

**Comment by AdenFlorian** [comment]
references section is for things that show how its supposed to work IRL, the screenshot you provided is not a reference, please provide one, thanks!
