### ISSUE TITLE
[BUG] Cabin Altitude Vertical Speed not displaying true value

### ISSUE THREAD

**Issue by Figrol** [flybywiresim/a32nx#1151]
**Mod Version**

Stable version downloaded from FlyByWireSim website on 4th October 2020

**Describe the bug**

When the aircraft is climbing and the CRUISE ECAM page is displayed, Cabin pressure V/S only displays 8 FT/MIN but it should be more as clearly the cabin pressure displayed below this is increasing faster than 8fpm.

**To Reproduce**

1. Climb in the Aircraft. It seems to happen whenever climbing.

**Expected behavior**

Cabin V/S should fluctuate, or be significantly higher than 8FT/MIN

**Actual behavior**

Cabin V/S figure increases only to a maximum of 8 FT/MIN

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by lukecologne** [comment]
Please add a title

**Comment by Emile31** [comment]
I guess it can be linked to #553

**Comment by lukecologne** [comment]
This has been fixed in master.
