### ISSUE TITLE
[BUG] Fuel Pumps Linked to Opposite Engines

### ISSUE THREAD

**Issue by TheoBearman** [flybywiresim/a32nx#1152]
**Mod Version**
Master

**Describe the bug**
As per the title.

**To Reproduce**

1. Start engines.
2. Cut engines by turning off fuel pumps.

**Expected behavior**

L and R fuel pumps should be linked to L and R engines respectively.

**Actual behavior**

L fuel pump linked to R engine and vice versa.

Was this working before/when did the issue start occurring? Unknown.

Is this a problem in the vanilla unmodded game? Unknown.

Discord username (if different from GitHub): theob

**Comment by FlyingCarpet7** [comment]
Where you able to cut the engines by selecting fuel pumps off? That is not correct behaviour. With fuel pumps off there is still gravity feeding available.

**Comment by TheoBearman** [comment]
Yes I was.

**Comment by komp1821** [comment]
> Where you able to cut the engines by selecting fuel pumps off? That is not correct behaviour. With fuel pumps off there is still gravity feeding available.

That's a bug in the vanilla version. Turn them off, lose the engines...

On the issue:

Doesn't happen to me.

![Screenshot 2020-10-07 142745](https://user-images.githubusercontent.com/71044068/95330847-6dd36d80-08a9-11eb-803c-e171fd47b35c.jpg)

**Comment by FlyingCarpet7** [comment]
![pump off](https://user-images.githubusercontent.com/71129337/95333381-fef81380-08ac-11eb-9197-35f6ecb10ee7.png)
Same side for me as well

**Comment by lukecologne** [comment]
Also cannout reproduce this issue, of course there is still the issue that the engines shouldn't turn off when the fuel pumps are off, but for that, a new issue should be created, if there isn't one already.
