### ISSUE TITLE
[BUG] WHEEL page displayed to early and with wrong indication.

### ISSUE THREAD

**Issue by FlyingCarpet7** [flybywiresim/a32nx#1153]
**Mod Version**

0.3.1
**Describe the bug**

Lower ECAM WHEEL page is displayed to early. As it is now the WHEEL page replaces the CRUISE page as soon as the landing gear lever is selected down which is to early.
Because it was early displayed I noticed that the red landing gear position indicator was flashing in transit. This is not correct as far as I know. It should be steady red.

**To Reproduce**

1. Lower the gear and observe the lower ecam.
2.
3.

**Expected behavior**

The logic of the automatic flight phase switching is when the landing gear is EXTENDED (and < 16000 ft)
When the WHEEL page is displayed the gear position triangles are already green, but you can just see how the landing gear door position goes from transit to up.

**Actual behavior**

**References**

**Additional context**

![C9CB9237-4DFA-4F0D-B133-1F86CE7FDD7F](https://user-images.githubusercontent.com/71129337/95265643-de3ea800-0831-11eb-8c49-57a30e9d37e1.jpeg)

Was this working before/when did the issue start occurring?
No
Is this a problem in the vanilla unmodded game?
Feature not implemented in vanilla.

Discord username (if different from GitHub):

**Comment by lukecologne** [comment]
See also this video for the switching issue:
https://youtu.be/g32B8_5TbdQ?t=95

**Comment by lukecologne** [comment]
IIRC the triangles flashing should be fixed in #632 by @Benjozork. The gear door indicator is in the up position pretty much at the same time as the gear indicator is green, so that will need to be changed as well (maybe also in #632?). I will create a fix for the page switching so that the wheel page will come up only once the gear is more than 95% extended, which should be much more realistic.

**Comment by lukecologne** [comment]
The flasing triangles was fixed in #786, and the wheel page auto selection was fixed in #1170, so I'm going to close this.
