### ISSUE TITLE
[BUG] Fps and frametime - unplayable

### ISSUE THREAD

**Issue by Viper-Mav** [flybywiresim/a32nx#1155]
Hello i'm new in the forum
First of all i want to thank you all for the work, this is the only plane that it's good in fs2020, witout this mod, that game would have been unplable, so thanks a lot to you all!!!
Now the bug
After last plane i downloaded, it all became unplayable, lot of stuttering and like 25 or more fps loss!! 
I don't know what's happend but it's unplayable now
I hope i can help with this! Thank you all again! Great job guysss

**Mod Version**

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Username23-23** [comment]
This question has already been asked a few times

The performance drop is due to the ND’s being de-synced. I believe the team is working on fixing the performance drop. In the meantime, you may just have to stick to the stable version

**Comment by wpine215** [comment]
Duplicate issue. Please search before opening one next time.
