### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Pilot747-hub** [flybywiresim/a32nx#1165]
**Mod Version**
A320NX master V0.3.1, MSFS latest patch installed

**Describe the bug**
At T/O after rotating with thrust set to FLX MCT, gear up, flaps 0, selected speed 250, thrust back to CLB: When I engage AP at this point the aircraft continously banks either hard to the left or to the right (depends on departing airport) and doesn't follow flightplan NAV until short before approach, then it's working again. When I switch to drone mode (Showcase) right after T/O, AP is working and aircraft is following NAV. It does not in External and Cockpit view. 

**To Reproduce**

1. T/O with FLX MCT, Gear Up, Flaps 0, selected speed 250 then thrust CLB
2. Engage Autopilot
3. banking left/right not following NAV

**Expected behavior**
Following NAV when engaging AP

**Actual behavior**
banking left or right in Cockpit or External view, NOT in Showcase/Drone mode

**References**

**Additional context**
Used loaded flight plan from Littlenavmap or Simbrief

Was this working before/when did the issue start occurring?
Yes, was already working in V0.3.1

**Comment by NathanInnes** [comment]
Please add a title.

**Comment by wpine215** [comment]
Closing until title added.
