### ISSUE TITLE
Elevator Unresponsive on Approach

### ISSUE THREAD

**Issue by FS2020Paul** [flybywiresim/a32nx#1167]
Using V0.3.1 and FS2020 1.9.3
Every landing attempt results in an elevator that is unresponsive after disengaging AP. The aircraft maintains the setup descent rate and flies into the ground. As soon as aircraft touches runway/ground/water elevator works again. This has happened if using APP for an ILS or simply using AP altitude control until I disengage AP and hand fly.

**Comment by davydecorps** [comment]
Totally had that one. Can only save your life using trim.
Not totally sure it's mod related though.

**Comment by tumev2** [comment]
I can confirm this, went to the fs2020 forums, people say this is linked with the A32NX mod, doesnt happen with the normal a320, or doesnt happen if you haven't pressed APP on the FCU.

**Comment by CoffeePanda0** [comment]
Yeah this sucks, and the bank to the left or right before touchdown is still a massive, massive issue

**Comment by Benjozork** [comment]
Please use the issue template. Closing until that is resolved 🙁
