### ISSUE TITLE
[BUG] Cockpit unresponsive

### ISSUE THREAD

**Issue by Saabertooth1** [flybywiresim/a32nx#1168]
**Mod Version**

master

**Describe the bug**

After installation the whole cockpit is broken, not letting me interact with anything on it.

**To Reproduce**

1. Install the mod
2. Launch game
3. Load any flight with the A320

**Expected behavior**

Modded cockpit

**Actual behavior**

Cockpit with buttons illuminated but can't interact with anything on it.

**References**

https://cdn.discordapp.com/attachments/748731242912022649/763406553814269952/unknown.png
https://cdn.discordapp.com/attachments/748731242912022649/763406412171968542/unknown.png

**Additional context**

Was this working before/when did the issue start occurring?
The problem began after installing the mod

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):
Sabertooth#9217

**Comment by Gan-ceann** [comment]
Is there any chance this is the ATC window bug? Try moving/wiggling the ATC window around and then trying the buttons again, unless you have already tried that

**Comment by Saabertooth1** [comment]
It doesn't seem like it. I've tried with multiple games, and moving/resizing the atc window, but it's the same.
Even if I move my thurster, the in-game model won't change.

**Comment by CoffeePanda0** [comment]
Just did a full flight on latest dev and didnt have this issue. Have you tried deleting your community folder and letting the sim rebuild, then installing the mod?

**Comment by Saabertooth1** [comment]
Just tried it. Same issue. Aircraft systems make "sounds" but still, can't interact with anything. Displays are black and all buttons are on. (Some of them displaying all states like on/avl).

**Comment by Benjozork** [comment]
Disable ALL AI / ground traffic and remove custom liveries. Does it still do that after ?

**Comment by Saabertooth1** [comment]
Just tried that. Still not working. I also noticed this:
![image](https://user-images.githubusercontent.com/23661049/95463980-ba867980-0979-11eb-835f-c04cde394cea.png)

**Comment by lukecologne** [comment]
Your mod install is likely somehow broken, have you tried reinstalling?

**Comment by Saabertooth1** [comment]
Yes I have. I've also made sure to only install the A32NX folder.
I'm not using the latest update for the game though. I don't know if that could be the issue.

**Comment by lousybyte** [comment]
> Yes I have. I've also made sure to only install the A32NX folder.
> I'm not using the latest update for the game though. I don't know if that could be the issue.

That is the issue, the mod will only work with the latest official game update.

**Comment by lousybyte** [comment]
Please try the new stable release and make sure the game is on the 1.9.5 patch. Can open a new issue if you still have problems.
