### ISSUE TITLE
[BUG] New bleed page gone???

### ISSUE THREAD

**Issue by Watsi01** [flybywiresim/a32nx#1172]
**Mod Version**
current master

**Describe the bug**
Maybe the bug is, I'm about to lose my mind.
BUT wasn't the new (working) bleed page already merged into the master today?
I downloaded the latest version (with nice sound additions and changes by hotshotp) and now the bleed page is the old "fake" one again? 

OR: this was only in my imagination and I will admit myself into an according facility.

**To Reproduce**

1. Just start a flight and check the bleed page in ECAM

**Expected behavior**
ECAM bleed page working. I'm sure I checked a few hours ago... (really, I'm sure, believe me,...)

**Actual behavior**
Pilot going mad...

**References**
None

**Additional context**

Was this working before/when did the issue start occurring?
see above - just today

**Comment by Benjozork** [comment]
The new BLEED page was not merged – the PR still says open.

**Comment by Watsi01** [comment]
Thx. So I'm closing this (don't trust me anymore).
