### ISSUE TITLE
[BUG] Batt 1 & 2 randomly inoperative during cold and dark starts

### ISSUE THREAD

**Issue by jjcodestuff** [flybywiresim/a32nx#1174]
**Mod Version**

master (10/7/2020 2PM EST)

**Describe the bug**
Batt 1 & 2 randomly inoperative during cold and dark starts

**To Reproduce**

1. Load any semi-complex flight plan from simbrief, preferably from a busy, detailed airport (I can recreate it more often)
2. Try to start preflight sequence by pressing Bat 1 & 2 

**Expected behavior**
should power up

**Actual behavior**
 nothing happens

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Has been wonky even before todays master was pulled

Is this a problem in the vanilla unmodded game?
Unknown

Discord username (if different from GitHub):

**Comment by cjk422** [comment]
I encountered this bug as well. Bat 1 and 2 do nothing, turning on external power does nothing. I wasn't loading a flight plan from MSFS, I was simply selecting the starting airport and gate. Live traffic and weather was on. I restarted the flight several times and had the same issue. I rebooted my computer and on the next flight it worked.

**Comment by wpine215** [comment]
You are not following the installation instructions. You must have AI/Live traffic/multiplayer planes either set to generic models or turned off completely.

**Comment by cjk422** [comment]
I remember reading about that somewhere (probably Reddit), but that's not mentioned anywhere in the installation instructions on the GitHub page.

**Comment by jjcodestuff** [comment]
> You are not following the installation instructions. You must have AI/Live traffic/multiplayer planes either set to generic models or turned off completely

@wpine215 nowhere in readme does it say to do that. Probably should think about adding that to the repo, so that when you are terse with people who are opening issues to try to improve the project, it's actually well-founded.
