### ISSUE TITLE
[BUG] Crash to Desktop when selecting ILS

### ISSUE THREAD

**Issue by Zyonix007** [flybywiresim/a32nx#1175]
**Mod Version**
Latest DEV as of 10-7-20

**Describe the bug**
When imputing waypoint then selecting an ILS the sim CTD 

**To Reproduce**
Imput max waypoint using airways tab then select the arrival ILS

1.Normal cold dark
2.selecting approach ILS
3.

**Actual behavior**
Sim CTD

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by MANFahrer-GF** [comment]
same problem as here #1137

**Comment by ChruutvoLuzi** [comment]
Can confirm this aswell, when starting cold and dark it usually works the first time but when trying to change the selected ils again, it crashes to desktop

**Comment by heftelin** [comment]
I have the same problem!
When starting cold and dark my sim crashes when selecting the ILS. When starting at the rundway it usually works.
I'm using the latest version 0.4.0 installed with the installer v0.6.

**Comment by Benjozork** [comment]
@heftelin can you try with the development version and report back ?

**Comment by heftelin** [comment]
> 
> 
> @heftelin can you try with the development version and report back ?

I installed the development version with the installer and it seems that there is no problem.
I tried cold and dark and also change the settings during flight -> no crash.

**Comment by lousybyte** [comment]
Cannot replicate, make sure to remove any other mods that might conflict with this and also have the latest version of the game installed.

**Comment by Zyonix007** [comment]
must have gotten fixed
