### ISSUE TITLE
[BUG] CTD when selecting ILS

### ISSUE THREAD

**Issue by Zyonix007** [flybywiresim/a32nx#1176]
**Mod Version**
Latest DEV as of 10-7-20

**Describe the bug**
When imputing waypoint then selecting an ILS the sim CTD 

**To Reproduce**
Imput max waypoint using airways tab then select the arrival ILS

1.Normal cold dark
2.selecting approach ILS
3.

**Actual behavior**
Sim CTD

**References**

**Additional context**

Was this working before/when did the issue start occurring?

It used to work

Is this a problem in the vanilla unmodded game?

no

Discord username (if different from GitHub):

**Comment by wpine215** [comment]
Duplicate issue.

**Comment by Zyonix007** [comment]
sorry for some reason it duplicated when i posted it
