### ISSUE TITLE
[BUG] SRS Speed is too low

### ISSUE THREAD

**Issue by sef3613** [flybywiresim/a32nx#1177]
**Mod Version**

Latest

**Describe the bug**

SRS Climb speed is between a-prot and a-max speed. Almost in the red band on the airspeed tape.

**To Reproduce**

1. Takeoff and note SRS managed magenta speed bug.
2.
3.

**Expected behavior**

Speed should be above VLS and far from stalling (see FSLabs screenshot).

**Actual behavior**

Speed is below VLS, below a-prot and just above a-max.

**References**

![Screenshot (87)](https://user-images.githubusercontent.com/70450099/95401655-c885bd00-08db-11eb-9820-cadfdeeb5779.png)

Here's the FSLabs A320 on initial climb. Note magenta speed bug.
![image](https://user-images.githubusercontent.com/70450099/95401707-ef43f380-08db-11eb-8326-02dc567e9c3e.png)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by tyler58546** [comment]
What was your V2 speed set to?

**Comment by sef3613** [comment]
134, which is too low but thats the number the MCDU gave me.

**Comment by sef3613** [comment]
MCDU V2 speed is off then

**Comment by MisterChocker** [comment]
This has been fixed
