### ISSUE TITLE
[BUG] Pulling for Heading doesn't cause a reversion to open climb

### ISSUE THREAD

**Issue by sef3613** [flybywiresim/a32nx#1180]
**Mod Version**

Latest

**Describe the bug**

When pulling for heading mode, the plane remains in managed climb rather than reverting to open climb.

**To Reproduce**

1.Fly in "NAV" and "CLB" (managed climb) modes.
2.Pull the heading knob to engage heading mode.
3.Note that "CLB" is still active and hasn't switched to open climb

**Expected behavior**

According to a real world Airbus pilot in the FBW discord, "Selecting HDG will give you a mode reversion from CLB to OPEN CLB. If you were in managed DEC you will get V/S."

**Actual behavior**

Plane remains in managed climb.

**References**

![Screenshot (86)](https://user-images.githubusercontent.com/70450099/95402829-ab9eb900-08de-11eb-84ec-0fdb1e0b2339.png)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by AdenFlorian** [comment]
unable to recreate on latest master, had a lot merged to master in last 5 hours, but i dont recall any of them touching the FMAs. are you using 0.3.1 stable? or master branch?

**Comment by MisterChocker** [comment]
Has this been fixed now?

**Comment by 2hwk** [comment]
Seems ok on 1.12.13, closing.
