### ISSUE TITLE
[BUG] Radio screens do not display frequency when radio turned off and then on

### ISSUE THREAD

**Issue by yusufsan38** [flybywiresim/a32nx#1184]
**Mod Version**
Latest master as of 10/07/2020 11:01pm EST

**Describe the bug**
When radios are turned off and back on frequency is not displayed on radio screens

**To Reproduce**
1. Spawn at any airport
2. Turn on the batteries
3. Turn on external power
4. Turn off either one of the comm. radios at the pedestal
5. Turn them back on and the frequency display is not coming on

**Expected behavior**
Displays the stand by and active radio freq.

**Actual behavior**
Comm. radio displays are black

Was this working before/when did the issue start occurring?
Haven't tested with other master branch releases

Is this a problem in the vanilla unmodded game?
I have scenery mods installed as well ass GA aircraft mods

Discord username (if different from GitHub): The Sim Pilot

**Comment by AdenFlorian** [comment]
are you in instrument view when this happens? Try exiting instrument view and see if it becomes visible again. If it does, then we probably can't do much about it.

**Comment by ErikNL80** [comment]
Yes is an issue with the vanilla aircraft... Frequency alsways fixed to 124.850 and not visible when calling other views like CTRL 5 (MCDU view).

**Comment by yusufsan38** [comment]
Ah makes sense I never used the top down view on the Pedestal first time I used when recording a tutorial. Turned off the radios and turned them back on and the displays went black all of a sudden.

**Comment by lukecologne** [comment]
Closing since this is an issue with the game, see #717
