### ISSUE TITLE
[BUG] Standby Instrument Barometer Knob has no STD Push Functionality

### ISSUE THREAD

**Issue by 2hwk** [flybywiresim/a32nx#1186]
**Mod Version**

master

**Describe the bug**

Standby Instrument ISIS is missing the pull/std function to set standard baro pressure, also used on BUGS to select/set bugs (This is currently being worked around) 

**To Reproduce**

1. Observe that there is no where to click baro knob on ISIS which simulates the push functionality
2. There is no step 2
3.

**Expected behavior**

Pushing the button should set pressure to std, and in bugs mode this should set/select bugs (Currently this occurs when reset is pushed (as a workaround) which is incorrect)

**Actual behavior**

Missing functionality

**References**

**Additional context**

Posting this so it is listed as a known issue, **unfortunately this cannot be fixed without a change in the plane's 3D model** as the model is missing a group for push functionality entirely.

Was this working before/when did the issue start occurring?
No, was never working before. 

Is this a problem in the vanilla unmodded game?
Yes

Discord username (if different from GitHub): 2hwk#1022

**Comment by komp1821** [comment]
Mouse at 6o'clock position of the selector:

![baro](https://user-images.githubusercontent.com/71044068/95454036-2d88f380-096c-11eb-83d6-1bee58a8ebe7.jpg)

**Comment by lukecologne** [comment]
@komp1821 They meant the Standby Instrument :)

**Comment by komp1821** [comment]
I should definitely pay more attention while reading.
