### ISSUE TITLE
[BUG] MCDU cruise altitude not filled from flightplan

### ISSUE THREAD

**Issue by ErikNL80** [flybywiresim/a32nx#1187]
**Mod Version**

Master

**Describe the bug**

When creating a flightplan, it is correctly filled in the MCDU, but the cruise altitude is empty although it is known.

**To Reproduce**

1. Create an IFR flightplan
2. Start the aircraft cold and dark
3. Notice the empty cruise altitude at the init page

**Expected behavior**

I would expect the cruise altitude to be prefilled

**Actual behavior**

Cruise altitude is left empty

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Yes, working up until today's master version
Is this a problem in the vanilla unmodded game?
Issue in the Master, vanilla is working as expected.

Discord username (if different from GitHub):

**Comment by Venorcis** [comment]
Indeed, besides CRZ FL on Init A some more things that were filled in automatically before when using a flightplan from the sim are now empty on Init B too (ZFW/BLOCK).

**Comment by lousybyte** [comment]
Probably after #888, and possibly they are intended changes, author could tell you more.

**Comment by lousybyte** [comment]
Seems intended.
