### ISSUE TITLE
Should be possible to activate both AP1 and AP2 at the same time.

### ISSUE THREAD

**Issue by Curtis-VL** [flybywiresim/a32nx#119]
Should be possible to activate both AP1 and AP2 at the same time. Currently enabling one will disable the other.

**Comment by arvinjarvin** [comment]
Thanks for raising the issue. This will be resolved such that you can support CATIII instrument landings, etc.

**Comment by Curtis-VL** [comment]
Interestingly, the code is already in to display both AP's being enabled!

So long as both of these return true, it should already display AP1+2 on the FMA:
Simplane.getAutoPilotActive(1);
Simplane.getAutoPilotActive(2);

**Comment by 2hwk** [comment]
Working on this, results soon hopefully

**Comment by JackZ974** [comment]
There are specific conditions for activating AP1+2: ILS/GLS, Rollout or Go Around mode only. It is for precision approaches only. In all other cases, and NPA for example only one AP is allowed at a time.

**Comment by docjonny** [comment]
so has this been corrected for allowing dual AP cat 3 B approaches?

**Comment by aguther** [comment]
Will be fixed in the upcoming autopilot system

**Comment by docjonny** [comment]
Thanks, saw demos of experimental version by 320simpilot and can’t wait for delivery to the masses. Thanks
