### ISSUE TITLE
[BUG] Bleedthrough of pushback truck orange warning light

### ISSUE THREAD

**Issue by ErikNL80** [flybywiresim/a32nx#1190]
**Mod Version**

Master

**Describe the bug**

When pushed back the pushback truck has a flashing orange light. This light is bleeding through the cockpit.

**To Reproduce**

1. Start a flight at a gate
2. Request pushback
3. Notice the orange light bleeding through

**Expected behavior**

I would expect some effect in the cockpit, but not bleeding.

**Actual behavior**

Light is bleeding through
![bleed](https://user-images.githubusercontent.com/71258178/95445867-d41ac780-095f-11eb-9a3b-ba8bf6b32a0c.png)

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Venorcis** [comment]
Can confirm this always happens indeed, quite jarring.

**Comment by lukecologne** [comment]
I am not sure if we can fix this, IIRC the way previous light bleed issues were fixed was by changing the actual light sources on the aircraft, but we can't really do that with the pushback truck light.

**Comment by MisterChocker** [comment]
This might be fixed by latest game update

**Comment by MisterChocker** [comment]
Closing since no response from op.
