### ISSUE TITLE
[BUG] ND barosetting ref QFE instead of QNH

### ISSUE THREAD

**Issue by bouill** [flybywiresim/a32nx#1191]
**Mod Version**

master

**Describe the bug**

The ND and the baro setting FCU window display QFE and the value when toggeling the baro FCU knob from STD.
QFE is not used for approach (whould give a 0ft altitude at landing wherever used)

**To Reproduce**

1. Fly from a Flight Level, STD baro setting
2. Descend, and "push" the FCU baro knob
3. the associated window and the ND display QFE

**Expected behavior**

The FCU baro window and the ND should display QNH. The FCU knob should always trigger STD - QNH, never QFE

**Actual behavior**

QFE is displayed instead of QNH on ND and FCU window

**References**

![Microsoft Flight Simulator Screenshot 2020 10 08 - 11 41 17 27 (3)](https://user-images.githubusercontent.com/72552323/95449030-7472eb00-0964-11eb-94f9-9c735a86aabf.png)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
Yes

Discord username (if different from GitHub):

**Comment by komp1821** [comment]
Push the button one more time and it reverts to QNH.

**Comment by bouill** [comment]
Alright, thanks for the answer, I didn't see that.

Though, to me, doesn't seem like a normal behavior, and pushing / pulling once the knob should toggle STD/QNH, and maybe one more push triggering QFE, for the very remote users of this function on the 320. 
Is it just me thinking that?

**Comment by St54Kevin** [comment]
You can change from QNH to QFE by pushing the knob. BUT it should always go back to the setting you had before. For my it changes from QNH to STD to QFE. Thats wrong

**Comment by lukecologne** [comment]
The altimeter mode is remembered in latest master. Closing as fixed.
