### ISSUE TITLE
[BUG] Correct functionality of transponder / ATC box

### ISSUE THREAD

**Issue by bouill** [flybywiresim/a32nx#1192]
**Mod Version**

master

**Describe the bug**

The xpdr keypad and window do not work as in the real aircraft in 2 situations:
- double hit of CLR key
- code let uncomplete after some seconds

NOTE: This issue has been described in post #1126, but closed because BUG instead of enhancement

**To Reproduce**

1. Have the aircraft powered (anywhere)
2. on the atc box (transponder), hit the CLR key twice
3.

**Expected behavior**

the whole code blanks (all four digits)

**Actual behavior**

just the last 2 digits blank

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by lukecologne** [comment]
#1126 was re-created as a bug report under #1127 and is already described there, closing as duplicate.
