### ISSUE TITLE
[BUG] starter bleed air status after engine start

### ISSUE THREAD

**Issue by bouill** [flybywiresim/a32nx#1193]
![FCOM 320](https://user-images.githubusercontent.com/72552323/95481551-67b6bd00-098d-11eb-9051-0e3e3310373c.png)

**Mod Version**

Master

**Describe the bug**

The starter bleed valve scheme on the lower ECAM (sd) is incorrect at the end of engine start sequence.

**To Reproduce**

1. Aircraft powered, perform a normal start sequence : IGN switch then master 2 ( or 1 doesn't matter)
2. The start sequence is happening: source bleed eng 2 opens, then ignition and FF after some N2
3. Watch parameters on ECAM: When eng started and N1 stabilized, the ignition stops, but the bleed source doesn't close.

**Expected behavior**

The bleed valve on the started engine should close, and the scheme on SD should show it (green circled with crossed line)
There should also be an [AVAIL] displayed on the N1 gauge on E/WD.

**Actual behavior**

The icon remains on open status (circle with inline bar)

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Never been working. The IGN display was fixed between v0.3.1 and master, not the bleed closing.

Is this a problem in the vanilla unmodded game?
Yes. The lower ECAM (SD) shows bleed opening but not closing just the same.
BUT just nearby, the igniter ON symbol is not used properly in unmodded; but has been corrected to show real igniter activation in the master version (was corrected after v0.3.1)

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Please fill in the missing information:

> Was this working before/when did the issue start occurring?
>
> Is this a problem in the vanilla unmodded game?

**Comment by bouill** [comment]
edited, thanks.

**Comment by bouill** [comment]
And to add something on the ENG start sequence, regarding the upper display: on ground and until the ign button is turned right, the upper ECAM should display amber crosses instead of green values for engine parameters (see picture)
![thumbnail](https://user-images.githubusercontent.com/72552323/95481884-d09e3500-098d-11eb-8b65-402c43103e69.jpg)

This is just details. The job done here on the A320 is truly amazing.

**Comment by MisterChocker** [comment]
> And to add something on the ENG start sequence, regarding the upper display: on ground and until the ign button is turned right, the upper ECAM should display amber crosses instead of green values for engine parameters (see picture)

yes after fadec self test.

**Comment by bouill** [comment]
This issue is now solved, thanks so much! Really appreciated! Works perfectly
