### ISSUE TITLE
[BUG] LANDING ECAM MEMO still present in GOAROUND PHASE

### ISSUE THREAD

**Issue by MisterChocker** [flybywiresim/a32nx#1194]
**Mod Version**
master

**Describe the bug**
After touch and go or go around the landing ecam memo is still present even tho the landing gear has been fully retracted.

**To Reproduce**
1.Take-Off at any airport
2.Fly an touch and go or abort landing and go around
3.

**Expected behavior**

When Thrust Lever is set to TOGA while in approach phase the airbus will then be in the GOAROUND PHASE.
This phase change triggers some events so the ECAM will be cleared and no LANDING ECAM MEMO will be shown.

**Actual behavior**
The LANDING ECAM MEMO is still shown and will not disappear.

**References**
![](https://i.imgur.com/d4nkWza.png)

**Additional context**

Was this working before/when did the issue start occurring?
No.

Is this a problem in the vanilla unmodded game?
I think there is no ECAM MEMO in default 320.

Discord username DerL30N#3751

**Comment by Benjozork** [comment]
cc. @tyler58546

**Comment by sef3613** [comment]
Can you check and see if it gives "TOGA, SRS, GA TRK" or not as well? I've experienced that it's stuck on "FLARE"
