### ISSUE TITLE
[BUG] The ATHR does not disengage when thrust lever is set to IDLE

### ISSUE THREAD

**Issue by MisterChocker** [flybywiresim/a32nx#1195]
**Mod Version**

master

**Describe the bug**

The ATHR does not disengage when thrust lever is set to IDLE

**To Reproduce**

1. Be in the air with ATHR activated
2. Pull Thurst Lever to IDLE
3.

**Expected behavior**

ATHR will disengaged when thrust lever are set to IDLE.

**Actual behavior**

ATHR will remain activated.

**References**

General ATHR DC conditions: http://www.a320dp.com/A320_DP/engines/sys-5.4.1.html

**Additional context**

Was this working before/when did the issue start occurring?
No, this was not working before.. hence this is based on a Boeing and the Boeing ATHR does not disengage cause their thrust levers are moving. (in this sim not real life)

Is this a problem in the vanilla unmodded game?
Yes

DerL30N#3751

**Comment by Benjozork** [comment]
Thanks for your bug report !

Please provide the missing information:

> Was this working before/when did the issue start occurring?
>
> Is this a problem in the vanilla unmodded game?

**Comment by MisterChocker** [comment]
@Benjozork updated

**Comment by snaylor111** [comment]
I done a flight yesterday and it was fine upon touchdown

**Comment by MisterChocker** [comment]
@snaylor111 did not tested this on the ground.. this was in flight

**Comment by sef3613** [comment]
Even on the ground, the FCU A/THR stays engaged when the switch should disengage as well.

**Comment by MisterChocker** [comment]
@sef3613 from my perspective I actually can not tell anything regarding flying with AP and ATHR engaged. I only test this airplane by flying manually to test all basic functions.

**Comment by MisterChocker** [comment]
duplicate of #1047
