### ISSUE TITLE
[BUG] ECAM Engine Indications are wrong

### ISSUE THREAD

**Issue by MisterChocker** [flybywiresim/a32nx#1197]
**Mod Version**

master

**Describe the bug**

The range of the Engines N1 indication is wrong.
The Engine N1 "needle " at idle thrust has to be almost at the beginning of the arc (as seen in picture 1), not somewhere in the 1/4th.
Also the font seems to be a bit to thick, compared to the reference picture and what I am used to see.
However the EGT is lacking an amber vertical line as the Engine N1 has.
Also the red range seems to be longer as the one in the reference but this could be due to an different engine.

**To Reproduce**

1.Start Engines
2.
3.

**Expected behavior**

The idle Engine N1 is at or extremely close to the beginning of the arc.
![image](https://user-images.githubusercontent.com/1857322/95471990-c9255e80-0982-11eb-84c6-d596c42e2598.png)

**Actual behavior**

The idle Engine N1 is way to far off the beginning of the arc.
![image](https://user-images.githubusercontent.com/1857322/95475153-38508200-0986-11eb-8362-2d9f4d3a657c.png)

**References**

On Ground https://www.youtube.com/watch?v=cv41hm4JEB8&feature=youtu.be&t=100
In Air https://www.youtube.com/watch?v=FODhSJucbK0

**Additional context**

Was this working before/when did the issue start occurring?
Not working before
Is this a problem in the vanilla unmodded game?
Yes

DerL30N#3751

**Comment by RichardPilbery** [comment]
I have a fix for this. Will submit after work.

**Comment by MisterChocker** [comment]
Nice thanks ;)
