### ISSUE TITLE
[REQUEST] Flex to Temp Indication in upper ECAM

### ISSUE THREAD

**Issue by MisterChocker** [flybywiresim/a32nx#1198]
**Is your feature request related to a problem? Please describe.**

The "auto" indication stands for TOGA and also will display as TOGA.
Note that "auto" is currently displayed at all flight phases.

**Describe the feature you'd like to see implemented**

Rename "auto" to TOGA
If Flex to Temp is set -> Display the Flex to Temp readout instead of the "auto" (TOGA) as seen in both pictures.
After Take-Off and the rest of the flight the readout will be "CLB" for Climb.

**References**

On Taxi to Take-off https://www.youtube.com/watch?v=cv41hm4JEB8&feature=youtu.be&t=100
Landing https://youtu.be/FODhSJucbK0?t=64

TOGA:
![image](https://forum.aerosoft.com/uploads/monthly_10_2013/post-94663-0-83194400-1381421837_thumb.png)
Flex to Temp:
![image](https://user-images.githubusercontent.com/1857322/95476509-99c52080-0987-11eb-9f4d-1dee4531567a.png)
CLB (Climb)
![image](https://user-images.githubusercontent.com/1857322/95478266-9cc11080-0989-11eb-85fa-249b938db55e.png)

This shows the current situation:
![image](https://user-images.githubusercontent.com/1857322/95476351-739f8080-0987-11eb-8a40-23c9b9e5e689.png)

**Additional context**

Discord username DerL30N#3751

**Comment by Pheome** [comment]
It's working properly.
![Desktop Screenshot 2020 10 08 - 22 24 26 18](https://user-images.githubusercontent.com/1176338/95510165-c8f28680-09b5-11eb-854b-ea6574f2e3fd.png)

**Comment by MisterChocker** [comment]
@Pheome not for me. I also don't see TOGA and CLB hm

**Comment by Pheome** [comment]
> @Pheome okay thanks, does it also say CLB for the rest of the flight?

Yes It's working properly.

**Comment by MisterChocker** [comment]
@Pheome why not for me? I am on master and you can read "auto" in my video I just did for another issue https://youtu.be/B8wyczwU4xM

**Comment by MisterChocker** [comment]
In latest master it still says "AUTO" instead of "CLB".
