### ISSUE TITLE
[BUG] No separate engine thrust lever control

### ISSUE THREAD

**Issue by MisterChocker** [flybywiresim/a32nx#1199]
**Mod Version**

master

**Describe the bug**

The thrust lever can not be controlled separately.
I do have two axis setup properly as seen in the picture.
And my two axis setup works on other 2 mod or engine aircraft in the game.

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

![image](https://user-images.githubusercontent.com/1857322/95479229-d0506a80-098a-11eb-9c59-27a13ceb75b0.png)

**Additional context**

Was this working before/when did the issue start occurring?
I don't know

Is this a problem in the vanilla unmodded game?
No

Discord username DerL30N#3751

**Comment by NathanInnes** [comment]
We cannot setup peripheral options as of yet so this will be a long way from ever being completed.

**Comment by MisterChocker** [comment]
Works now with latest MFS update.
