### ISSUE TITLE
allow users to select waypoints and go direct to them 

### ISSUE THREAD

**Issue by Zyonix007** [flybywiresim/a32nx#12]

**Comment by arvinjarvin** [comment]
In progress.

Thanks for bringing this to our attention.

This will likely be rolled out with the CDU update.

**Comment by AdenFlorian** [comment]
@arvinjarvin any updates?

**Comment by AdenFlorian** [comment]
Does this issue exist in the vanilla unmodded game, or was it caused by the mod?

**Comment by Zyonix007** [comment]
No it's a feature request

**Comment by lousybyte** [comment]
Closing since no description provided and I assume is a duplicate of #1150.
