### ISSUE TITLE
Cockpit door video button should display cockpit door image on ECAM

### ISSUE THREAD

**Issue by Curtis-VL** [flybywiresim/a32nx#120]
Cockpit door video button should display cockpit door image on ECAM

**Comment by arvinjarvin** [comment]
In progress.

**Comment by becas22** [comment]
The system on the MSFS is to show Cockpit door image on a TV near the cockpit door. To see the image on the ECAM, you need this system:

![image](https://user-images.githubusercontent.com/11005754/91363808-58bce680-e7f5-11ea-91e3-33c1272737b4.png)

**Comment by TobitFR** [comment]
Well it is embeded in the aircraft : 
![image](https://user-images.githubusercontent.com/31391535/91469045-295cb700-e893-11ea-8bf9-2197e2e326a5.png)

**Comment by becas22** [comment]
@TobitFR That switch it's just to manually de-energize the cockpit door surveillance system.

**Comment by hotshotp** [comment]
Implemented
