### ISSUE TITLE
[REQUEST] RAD NAV PAGE insert via IDENTIFIER (text insert option)

### ISSUE THREAD

**Issue by MisterChocker** [flybywiresim/a32nx#1200]
**Is your feature request related to a problem? Please describe.**

Atm when trying to insert via identifier this is action is "not allowed"

**Describe the feature you'd like to see implemented**

Entering FORs/NDBs or AFDs via their identifier.

**References**

Shows entry of VOR https://youtu.be/5uN1Rr-hGcQ?t=461 (Its a sim but SAME AS RL)
![image](https://user-images.githubusercontent.com/1857322/95479526-2c1af380-098b-11eb-9028-6f771907a06c.png)
![image](https://user-images.githubusercontent.com/1857322/95479553-34732e80-098b-11eb-9605-d2efa45ebb66.png)

**Additional context**

Discord username DerL30N#3751

**Comment by Benjozork** [comment]
Hello, "references" refers to IRL A320 references in order realistic behavior. Please provide those and remember to use the correct MCDU vendor and version as specified in the PR template.

**Comment by MisterChocker** [comment]
@Benjozork added

**Comment by lukecologne** [comment]
Looks like this might be added in #1960

**Comment by MisterChocker** [comment]
yeah, I am excited ;)
