### ISSUE TITLE
[BUG] Aerodynamic Drag and Engine Thrust

### ISSUE THREAD

**Issue by MisterChocker** [flybywiresim/a32nx#1204]
**Mod Version**

master

**Describe the bug**

Its less a bug more of an "config" problem.
The aerodynamic drag is waaaaaaaay to high atm.
For the engines however, IRL even with CFM56 engines the aircraft starts rolling on idle thrust and little thrust is needed to accelerate to taxi speeds. With 30% N1 the acceleration is already fast (for taxiing).
However in-game I need 60% N1 to start rolling (slowly)

**To Reproduce**

1.
2.
3.

**Expected behavior**

_The A320 needs about 55% N1 for level flight with FLAPS 2 and LANDING GEAR UP to maintain 160 knots 2000ft ASL, QNH1013, 15°C air temperature._
A320 with classic wingtips on a 3° glide path with FLAPS 2 and LANDING GEAR UP and throttle IDLE losses extremely little speed.
Pilots on an A320(NEO) with Sharklets told me that in the exact same configuration they loose no speed at all.

With landing gear down however the aircraft slowly starts decelerating.
The FF320 for x-plane 11 got this pitch perfect for their "classic" A320.

For taxiing the aircraft rolls on idle thrust and for acceleration only 30% N1 is needed.

**Actual behavior**

With throttle IDLE on an 3° glide path with FLAPS 2 and GEAR UP the speed loss is insane.

For taxiing the aircraft slowly starts rolling at 50% N1, however quick acceleration starts somewhere around 55 to 60% N1.
The aircraft also slows down roughly 1 knot every second at 44% N1.

**References**

For taxiing https://youtu.be/cv41hm4JEB8?t=100
NEO (autoland) landing https://www.youtube.com/watch?v=FODhSJucbK0
For landing https://www.youtube.com/watch?v=rhI5XGwlnaI (NOT NEO, CFM56) (NEO engines are even more powerful tho)

## **Additional context (UPDATED)**

What did I improved? and what does the aircraft do now?

* Taxiing on idle thrust
* More realistic vertical speeds
* "slippery" approach
* flyable aircraft from what I saw during testing
* no stalling or rolling on flare / landing

Preview of changes:
Aero and Engine: https://youtu.be/lwsGYmMAj40
Aero only: https://youtu.be/CVGqyF5aOf8

![image](https://user-images.githubusercontent.com/1857322/95785921-f05b9300-0cd6-11eb-8f28-63821fb752e2.png)

flight_model.cfg (changes)

```haproxy-config
lift_coef_flaps = 1.6038 ; Change in lift due to flaps
rag_coef_flaps = 0.0566
drag_coef_gear = 0.155
pitch_moment_delta_elevator = -12.51784 ; The change in pitch moment per change in elevator deflection
pitch_moment_flaps = -1.3645 ; The pitch moment due to flaps
```

This is the part I edited:
engines.cfg

 ```haproxy-config
 n1_and_mach_on_thrust_table = 0.000000:0.000000:0.100000:0.200000:0.300000:0.400000:0.500000:0.600000:0.700000:0.800000:0.900000,0.000000:0.000000:0.000000:0.000000:0.000000:0.000000:0.000000:0.000000:0.000000:0.000000:0.000000,,20.000000:0.084000:0.088000:0.092000:0.096000:0.100000:0.104000:0.108000:0.112000:0.116000:0.120000,25.000000:0.116870:0.121830:0.126790:0.131750:0.136710:0.141670:0.146630:0.151590:0.156550:0.161510,30.000000:0.155620:0.161820:0.168020:0.174220:0.180420:0.186620:0.192820:0.199020:0.205220:0.211420,35.000000:0.209000:0.217000:0.225000:0.233000:0.241000:0.249000:0.257000:0.265000:0.273000:0.281000,40.000000:0.280333:0.289667:0.298667:0.308000:0.317333:0.326667:0.336000:0.345000:0.354333:0.363667,45.000000:0.351667:0.362333:0.372333:0.383000:0.393667:0.404333:0.415000:0.425000:0.435667:0.446333,50.000000:0.423000:0.435000:0.446000:0.458000:0.470000:0.482000:0.494000:0.505000:0.517000:0.529000,55.000000:0.488000:0.502000:0.515000:0.529000:0.542667:0.556333:0.570333:0.583333:0.597333:0.611000,60.000000:0.553000:0.569000:0.584000:0.600000:0.615333:0.630667:0.646667:0.661667:0.677667:0.693000,65.000000:0.618000:0.636000:0.653000:0.671000:0.688000:0.705000:0.723000:0.740000:0.758000:0.775000,70.000000:0.676027:0.696563:0.716427:0.736963:0.756827:0.776690:0.797227:0.817090:0.837627:0.857490,75.000000:0.727873:0.750767:0.773323:0.796217:0.818773:0.841330:0.864223:0.886780:0.909673:0.932230,80.000000:0.772000:0.797000:0.822000:0.847000:0.872000:0.897000:0.922000:0.947000:0.972000:0.997000,85.000000:0.819110:0.847727:0.876343:0.904960:0.933577:0.962193:0.990810:1.019427:1.048043:1.076660,90.000000:0.858500:0.890483:0.922467:0.954450:0.986433:1.018417:1.050400:1.082383:1.114367:1.146350,95.000000:0.889000:0.924000:0.959000:0.994000:1.029000:1.064000:1.099000:1.134000:1.169000:1.204000,100.000000:0.923140:0.961520:0.999900:1.038280:1.076660:1.115040:1.153420:1.191800:1.230180:1.268560,105.000000:0.948390:0.989800:1.031210:1.072620:1.114030:1.155440:1.196850:1.238260:1.279670:1.321080,110.000000:0.964000:1.008000:1.052000:1.096000:1.140000:1.184000:1.228000:1.272000:1.316000:1.360000
 ```

![image](https://user-images.githubusercontent.com/1857322/95888802-d925af80-0d81-11eb-92db-92ac1a32f3d8.png)

Was this working before/when did the issue start occurring?
This Issue exists since the beginning.

Is this a problem in the vanilla unmodded game?
GA no, airliner Yes

Discord username (if different from GitHub):

**Comment by Watsi01** [comment]
I think in air this is an issue. And on ground too. But I want to say that I have a different experience on ground. Current master, no wind, flat surface: my plane starts to roll taxi with above 31% N1. Quick acceleration above 41% N1. Slows down under 29% N1.
I don't know why we have different numbers...

**Comment by MisterChocker** [comment]
@Watsi01 I was at EDDL for this test with an GW of 44.6t

**Comment by Watsi01** [comment]
@MisterChocker  My ground weight was about 58t at EDDF. This is strange.

**Comment by MisterChocker** [comment]
@Watsi01 I also had difficulties with turning but since my tiller does not work in MFS I can not tell if it was just me or also something related to this aircraft. But since I am not sure I did not mentioned it.

**Comment by sef3613** [comment]
I agree with the thrust, I have to use way more thrust to get moving even when the a32nx is very light than any other airbus simulation and I've heard an IRL airbus pilot say that it takes too much thrust. I will say, I think every airplane in msfs2020 takes way too much thrust to move on the ground.

**Comment by MisterChocker** [comment]
@sef3613 for the airliners yes, the GA is fine from what I saw.

**Comment by sef3613** [comment]
Eh, I find myself using way more rpm to get rolling than any GA plane I've seen irl

**Comment by sef3613** [comment]
I also agree about the landing drag that the OP mentioned. As far as I'm aware, the A320 can be very "slippery" to get down and slow down which I don't think the a32nx matches.

**Comment by MisterChocker** [comment]
> Eh, I find myself using way rpm to get rolling than any GA plane I've seen irl, but not as extreme of an issue as the airbus.
Oh I barely use any throttle on taxi, but I have some issues in the air to get up to and hold speed without "killing" the engine.

**Comment by Watsi01** [comment]
I hear that from many pilots (767, 777, A320, etc.) "...oh, MY plane is so slippery, we often use speedbrakes...". Seems to be a common pilot talk. ;-)
Anyway. This is a flight model issue I think. And from what I read in Discord, it will take a while until these things are made.

**Comment by donstim** [comment]
I agree that it takes too high a power setting to initiate taxi and maintain taxi speed, and that the airplane decelerates too quickly in the air as well. However, I believe these are separate issues. In addition, I think the airplane accelerates too quickly in flight and speedbrake drag is much too high. You think the airplane decelerates to quickly without speedbrakes; just try it with speedbrakes!

For the taxi issue, this involves little to no speed, so aerodynamic drag is not an issue. The problem is caused by too low an engine thrust at low power settings or too high ground friction, or both.

In-flight, the issue is that the thrust is too low at the idle power setting, the drag is too high for the configuration you were in, or both, but even more, there seems to be some inertia or mass issue where the airplane is behaving like a much lower mass airplane in terms of how quickly it gains or loses speed with changes in thrust or drag.

**Comment by dickbig2** [comment]
During landing, I have to keep the plane for at least 145-150kts in full flaps. Lower than that, the plane will drop like a brick which is pretty ridiculous. The wing try to dip to either side when close to runway / flare.

**Comment by MisterChocker** [comment]
> 1. Do you use the "modern" flight model in MSFS?
> 2. Do you have other addons/mods installed, that could interfere?
> 3. Do you use addon livieries (I do) or the default livery?
> 4. Is there any "assistance" setting in MSFS which could interfere (I don't think so, my only active assistance is the taxi ribbon)?

@Watsi01
1. Yes I do use it.
2. No I don't.
3. Default airbus livery.
4. "assists" are all off, I don't even have the taxi ribbon because I don't use the trash AI atc.

Did u tried taxiing at EDDL, for me it looks like the taxi ways are not properly "paved". They feel odd and that also explains higher N1s and my issue turning.

@donstim agree! However the airplane feels way to heavy in the air, almost like the sim engine cannot handle larger aero surfaces or something. An 320 is very agile and not unstable at all. Also we have way too high Vls speeds, take off the same.
I do think we need to have a central Issue that describes what we just encountered and maybe over time we can get to a solution.

@dickbig2 yup it is indeed ridiculous.

**Comment by MisterChocker** [comment]
Okay guys just checked the taxiing thing at EDDF and somehow I can steer the aircraft way better on ground and taxiing requires less thrust as u guys said. So there is a difference then between handcrafted airports and non handcrafted? wtf?!?

**Comment by sef3613** [comment]
I’ve noticed the landing issue as well. It’s like the airplane stalls below about 145 which causes a lack of aileron authority and the wing to drop. This is odd cause at the weight I test the a32nx the VAPP SHOULD be 140 if not less. 145-150 has me at about -1 degrees pitch and is too fast but lower than that causes partial loss of control on flare.

**Comment by sef3613** [comment]
And agreed about it feeling too heavy, it’s like you have to hold full back pressure for 4-5 seconds to raise the nose 3-4 degrees. Feels like flying an A380 with A320-sizedflight controls.

**Comment by MisterChocker** [comment]
> And agreed about it feeling too heavy, it’s like you have to hold full back pressure for 4-5 seconds to raise the nose 3-4 degrees. Not to mention how Heavy it feels to rotate. Feels like flying an A380 with A320-sizedflight controls.

Yeah it kinda feels that way.

A few hours ago I attempted a few touch and gos back to back, after two aborted attempts I simply "forced" a full landing, because I got tired and annoyed.
While transitioning from downwind to base (with FLAPS 2, GEAR coming down, then flaps 3 and full) I had to apply full stick back input in order not to exceed 1500ft/m (I targeted about 1000ft/m). I also noticed that the this plane tends to slowly reduce its bank and pitch, so I also had to counter the plane countering my Inputs. (I watched the trim while applying my inputs and saw the trim countering my inputs (almost like the MCAS on the 737MAX).

Same for turning into final.

In another attempt I gave inputs and then waited a bit and watched the aircraft reacting to this and then gave inputs again to react the aircraft's behavior. Video: https://youtu.be/B8wyczwU4xM
When deploying flaps, the pitch will raise and the vs will decrease significantly, but that does also not happen.

The actual A380 is extremely agile because the wings were designed for even larger versions of the 380. I guess the 319 would be a good comparison. A380 pilots even say it feels sporty.

Landing this A320NX feels absolutely wrong.. its like forcing the plane to do something it cant like flying upside down. Where in real life you initiate a precise break and then gently flare until touchdown. In RL even dropping 10 knots below Vapp does not result in any kind of loss of control. When flying in normal law the pilots always have full control of the aircraft.

I simply guess that the surfaces are just poorly simulated or configured by the game itself.

**Comment by sef3613** [comment]
> > And agreed about it feeling too heavy, it’s like you have to hold full back pressure for 4-5 seconds to raise the nose 3-4 degrees. Not to mention how Heavy it feels to rotate. Feels like flying an A380 with A320-sizedflight controls.
> 
> Yeah it kinda feels that way.
> 
> A few hours ago I attempted a few touch and gos back to back, after two aborted attempts I simply "forced" a full landing, because I got tired and annoyed.
> While transitioning from downwind to base (with FLAPS 2, GEAR coming down, then flaps 3 and full) I had to apply full stick back input in order not to exceed 1500ft/m (I targeted about 1000ft/m). I also noticed that the this plane tends to slowly reduce its bank and pitch, so I also had to counter the plane countering my Inputs. (I watched the trim while applying my inputs and saw the trim countering my inputs (almost like the MCAS on the 737MAX).
> 
> Same for turning into final.
> 
> In another attempt I gave inputs and then waited a bit and watched the aircraft reacting to this and then gave inputs again to react the aircraft's behavior. Video: https://youtu.be/B8wyczwU4xM
> When deploying flaps, the pitch will lower and the vs will decrease significantly, but that does also not happen.
> 
> The actual A380 is extremely agile because the wings were designed for even larger versions of the 380. I guess the 319 would be a good comparison. A380 pilots even say it feels sporty.
> 
> Landing this A320NX feels absolutely wrong.. its like forcing the plane to do something it cant like flying upside down. Where in real life you initiate a precise break and then gently flare until touchdown. In RL even dropping 10 knots below Vapp does not result in any kind of loss of control. When flying in normal law the pilots always have full control of the aircraft.
> 
> I simply guess that the surfaces are just poorly simulated or configured by the game itself.

I genuinely think this feels more like landing a C172 than anything else, even then it's kinda off. It feels like if you flare, you always balloon and you have to land almost flat which makes no sense. Honestly none of the airliners in FS2020 land anything remotely like transport category airplanes. I literally can't land any of them controllably.

**Comment by MisterChocker** [comment]
> I genuinely think this feels more like landing a C172 than anything else, even then it's kinda off. It feels like if you flare, you always balloon and you have to land almost flat which makes no sense. Honestly none of the airliners in FS2020 land anything remotely like transport category airplanes. I literally can't land any of them controllably.

Agreed. Same for me.

**Comment by sef3613** [comment]
Its like you have a descent rate of 700 fpm at 3 degrees pitch up, so logic would tell you to arrest the descent rate, you have to increase pitch to 5-6 degrees. But in the a32nx, that causes a balloon in ground effect and you almost have to shove the nose back down to force it on to the ground.

**Comment by MisterChocker** [comment]
> Its like you have a descent rate of 700 fpm at 3 degrees pitch up, so logic would tell you to arrest the descent rate, you have to increase pitch to 5-6 degrees. But in the a32nx, that causes a balloon in ground effect and you almost have to shove the nose back down to force it on to the ground.

Absolutely.

**Comment by dickbig2** [comment]
damn...I hate this

**Comment by donstim** [comment]
The "too heavy" feeling you all are reporting is has a different cause than the lack of mass or inertia that I think exists when accelerating or decelerating in flight. In fact, both can be true. You all are talking about the aerodynamic modeling, which contains coefficients for the aerodynamic moments in the roll, pitch and yaw axes for changes in pitch, roll, yaw inputs as well as things like flap changes, angle of attack, trim, sideslip, etc. Based on your descriptions, It sounds like it is currently tuned to be too stable and slow to react to control inputs. This can be fixed.

**Comment by sef3613** [comment]
> The "too heavy" feeling you all are reporting is has a different cause than the lack of mass or inertia that I think exists when accelerating or decelerating in flight. In fact, both can be true. You all are talking about the aerodynamic modeling, which contains coefficients for the aerodynamic moments in the roll, pitch and yaw axes for changes in pitch, roll, yaw inputs as well as things like flap changes, angle of attack, trim, sideslip, etc. Based on your descriptions, It sounds like it is currently tuned to be too stable and slow to react to control inputs. This can be fixed.

Interesting, that's very possible. The weird thing is that it's over-responsive in the flare. No joke feels just as "twitchy" as the 152 in the sim when trying to land which is the opposite problem as in flight.

**Comment by Watsi01** [comment]
> 
> The "too heavy" feeling you all are reporting can have a different cause than the lack of mass or inertia that I think exists when accelerating or decelerating in flight. In fact, both can be true. You all are talking about the aerodynamic modeling, which contains coefficients for the aerodynamic moments in the roll, pitch and yaw axes for changes in pitch, roll, yaw inputs as well as things like flap changes, angle of attack, trim, sideslip, etc. Based on your descriptions, It sounds like it is currently tuned to be too stable and slow to react to control inputs. This can be fixed.

Yes, absolutely. In general, the A320 feels off in many ways. Since Asobo changed the flightmodel, I think, expecially during descent and approach, that the A320 is way to light (regarding the speeds, flaps lift, etc.). If I land with MCDU commanded/managed Vapp I nearly don't fly with any nose up. So there's much to be done. On Asobo side, but maybe also on this project's side (to make things even better).

**Comment by MisterChocker** [comment]
I think it's not only about the "feeling" but the behavior in general.

**Comment by randidiot** [comment]
FSX had this problem too, could be a problem they ported over.
https://www.avsim.com/forums/topic/392772-inherent-flaw-of-fsx-to-give-too-much-ground-friction/

**Comment by lukasrz** [comment]
When I retract flaps at 190-200kts plane nose wont go up, it slowly starting going down, and I need to increase a lot of trust. I think its not right.

**Comment by dickbig2** [comment]
> When I retract flaps at 190-200kts plane nose wont go up, it slowly starting going down, and I need to increase a lot of trust. I think its not right.

Same here! This is terrible ...

**Comment by MisterChocker** [comment]
hey gusy I have been playing around with the config and I found some values that really improve the flying of this aircraft.
THIS IS NOT meant to be the real aero or something but just a tweak to make the plane "flyable".

![image](https://user-images.githubusercontent.com/1857322/95785921-f05b9300-0cd6-11eb-8f28-63821fb752e2.png)

**Comment by MisterChocker** [comment]
I also looked into the engine file and wrote a short script that modifies/adjusts the engine thrust.
This video shows the result of my changes to aero and engine.
https://youtu.be/lwsGYmMAj40

This is the part I edited:
```
n1_and_mach_on_thrust_table = 0.000000:0.000000:0.100000:0.200000:0.300000:0.400000:0.500000:0.600000:0.700000:0.800000:0.900000,0.000000:0.000000:0.000000:0.000000:0.000000:0.000000:0.000000:0.000000:0.000000:0.000000:0.000000,,20.000000:0.084000:0.088000:0.092000:0.096000:0.100000:0.104000:0.108000:0.112000:0.116000:0.120000,25.000000:0.136000:0.142000:0.148000:0.154000:0.160000:0.166000:0.172000:0.178000:0.184000:0.190000,30.000000:0.172500:0.179500:0.186500:0.193500:0.200500:0.207500:0.214500:0.221500:0.228500:0.235500,35.000000:0.209000:0.217000:0.225000:0.233000:0.241000:0.249000:0.257000:0.265000:0.273000:0.281000,40.000000:0.310000:0.320000:0.330000:0.340000:0.350000:0.360000:0.370000:0.380000:0.390000:0.400000,45.000000:0.366500:0.377500:0.388000:0.399000:0.410000:0.421000:0.432000:0.442500:0.453500:0.464500,50.000000:0.423000:0.435000:0.446000:0.458000:0.470000:0.482000:0.494000:0.505000:0.517000:0.529000,55.000000:0.536000:0.551000:0.565000:0.579000:0.594000:0.608000:0.622000:0.636000:0.651000:0.665000,60.000000:0.577000:0.593500:0.609000:0.625000:0.641000:0.656500:0.672500:0.688000:0.704500:0.720000,65.000000:0.618000:0.636000:0.653000:0.671000:0.688000:0.705000:0.723000:0.740000:0.758000:0.775000,70.000000:0.700000:0.721000:0.742000:0.763000:0.784000:0.805000:0.826000:0.847000:0.868000:0.889000,75.000000:0.736000:0.759000:0.782000:0.805000:0.828000:0.851000:0.874000:0.897000:0.920000:0.943000,80.000000:0.772000:0.797000:0.822000:0.847000:0.872000:0.897000:0.922000:0.947000:0.972000:0.997000,85.000000:0.838000:0.868000:0.898000:0.928000:0.958000:0.988000:1.018000:1.048000:1.078000:1.108000,90.000000:0.863500:0.896000:0.928500:0.961000:0.993500:1.026000:1.058500:1.091000:1.123500:1.156000,95.000000:0.889000:0.924000:0.959000:0.994000:1.029000:1.064000:1.099000:1.134000:1.169000:1.204000,100.000000:0.923000:0.963000:1.003000:1.043000:1.083000:1.123000:1.163000:1.203000:1.243000:1.283000,105.000000:0.943500:0.985500:1.027500:1.069500:1.111500:1.153500:1.195500:1.237500:1.279500:1.321500,110.000000:0.964000:1.008000:1.052000:1.096000:1.140000:1.184000:1.228000:1.272000:1.316000:1.360000
```

**Comment by donstim** [comment]
Hey, I think you might be getting somewhere with these changes. Could you comment a bit on why you made the changes you did? I mean, I get reducing the flaps extended drag coefficient to make it "more slippery," but why increase the lift coefficient, and why increase the pitching moment change due to flaps? In your second video, it looked like the airplane ballooned up when you extended the slats, but maybe that was due to being in managed altitude and there was an altitude constraint that messed it up?

Have you looked at the effect of spoilers at all? I think the drag coefficient for spoilers is much too high, but that may just be me.

On your thrust table changes, were you trying to do more than improve taxying at idle thrust?  Just wondering why you elected to increase thrust at low N1 for all Mach numbers.

Good job.

**Comment by MisterChocker** [comment]
> Hey, I think you might be getting somewhere with these changes. Could you comment a bit on why you made the changes you did? I mean, I get reducing the flaps extended drag coefficient to make it "more slippery," but why increase the lift coefficient, and why increase the pitching moment change due to flaps? In your second video, it looked like the airplane ballooned up when you extended the slats, but maybe that was due to being in managed altitude and there was an altitude constraint that messed it up?

Hey yeah I wanted to show the AP behavior but unfortunately it could not handle the change. Unfortunetly I was a bit tired yesterday I did not noticed ATHR was will active, even tho I pulled the Thrust Lever to IDLE and since there was no such "Limited Thrust" caution I wasn't even paying attention to this even more and literally thought I was completely manual flying at this moment. 
When flying manual I got up to 500fpm vs bevor leveling again.
As said this is not perfect and needs some tweaking.

I did increased the lift because the aircraft was stalling way too soon.
I increased the pitching moment to make it more realistic.

> Have you looked at the effect of spoilers at all? I think the drag coefficient for spoilers is much too high, but that may just be me.

No I did not since was only focusing on the drag and lift of flaps since they are more important. But I can take a look into it anyways.

> On your thrust table changes, were you trying to do more than improve taxying at idle thrust? Just wondering why you elected to increase thrust at low N1 for all Mach numbers.

Yes the engine seemed a bit to underpowered at low N1 and way to overpowered at high N1. So I basically took a part of the original values / table set that looked good to me and applied them to the entire N1 range. (thats why I created a small script/program)

> Good job, I'm looking forward to trying it out myself.
Thanks mate, please to so and let met know!

**Comment by MisterChocker** [comment]
This is an before after comparison from one of the 10 parameters from the engine performance table.

![image](https://user-images.githubusercontent.com/1857322/95888802-d925af80-0d81-11eb-92db-92ac1a32f3d8.png)

**Comment by donstim** [comment]
Okay, so I managed 2 flights to check this out in between power failures here in the Seattle area. Both were short flights, the first under full manual control just to 5000 feet, and the 2nd was meant to check it out under normal autopilot/autothrust control on a flight up to FL330. Unfortunately, the 2nd flight was in such stormy conditions and was short (KSEA-KGEG), so I only got to FL230 before having to descend. Also, I was checking out a STAR that went right through KGEG with a 180 turn back around. That totally befuddled the autopilot, so it went into one of those death dives that I have hardly ever experienced, but have been reported by many. The only full recovery was to take back manual control and go to TOGA thrust, regain control, turn off autothrust and land under full manual control again. So, I did not get to see how this modification might affect an autopilot/autothrust flown final approach.

I like the change to increase the thrust at low power settings at all speeds. I think this helps not only with taxying, but also with reducing the descent rate in open descent, which has received many comments that it is too high. The reduction in thrust at high N1/low speed should help more with the "rocket" takeoff issue. 

My only concern is that I don't think thrust should be reduced at high N1 (climb N1s)/high speed. There have been a number of complaints about climb difficulties getting to higher altitudes. While many of these reports may be unjustified for various reasons (heavy weigh/high speed/etc), I think care needs to be taken in this area. While I was only able to test to a bit above FL230, already in climbing above FL230, I only had a 500 fpm rate of climb at 280 knots after departing KSEA at around 134,000 lb. Now, there was nasty weather with wind shifting all over the place, but I think someone needs to check this out more closely before going further.

One other change I made to my flight model config file was to reduce spoiler drag from 0.15 to 0.10. I'm not sure if this variable is used because it did not give me the improvement I expected, so I am going to try either 0.07 or 0.08. I think the speedbrakes are way too powerful.

**Comment by MisterChocker** [comment]
@donstim I will take a look at the climb rate in higher altitudes.
Yeah I also adjusted the speedbrakes as seen in the PR.
I also continued improvement on my engine thrust table to further improve aerodynamic.
I will also look into the slow vs in higher alt.

**Comment by donstim** [comment]
Great, thanks!

**Comment by Watsi01** [comment]
Hey MisterChocker,

without having tested your changes, I do appreciate them very much!! But I would also be carefull with the reduced high N1. I know that the A320 isn't a good climber like the B737 (e.g.). But I think the present climbrate at high N1 / higher altitudes is at least at the low limit right now. Climibing with  5 - 8 tons of fuel and 45-50% payload, you are already at climbrates between 900-1500 ft/min above FL240 (with a CLB speed of selected 285KIAS). You're the expert, but less than that seems to me a bit underpowered. What do you think?

**Comment by MisterChocker** [comment]
> Hey MisterChocker,
> 
> without having tested your changes, I do appreciate them very much!! But I would also be carefull with the reduced high N1. I know that the A320 isn't a good climber like the B737 (e.g.). But I think the present climbrate at high N1 / higher altitudes is at least at the low limit right now. Climibing with 5 - 8 tons of fuel and 45-50% payload, you are already at climbrates between 900-1500 ft/min above FL240 (with a CLB speed of selected 285KIAS). You're the expert, but less than that seems to me a bit underpowered. What do you think?

I will look into it and try to make some changes as needed. 
I don't know the ZFW for 45-50% payload, but keep in mind that with max TOW your cruise fl will be much lower. Of course there are steps in between, but I don't know them right now, need to look them up.

**Comment by Watsi01** [comment]
@MisterChocker Just to answer that: with 45% payload and 6t of fuel you have around 61t GW (or 55t ZFW). At least in MSFS. I think I never flew with max TOW so far. Should try that.

**Comment by MisterChocker** [comment]
> @MisterChocker Just to answer that: with 45% payload and 6t of fuel you have around 61t GW (or 55t ZFW). At least in MSFS. I think I never flew with max TOW so far. Should try that.

Okay with earlier changes I climbed 900ft/m at 320 IAS with 67.5t TOW above FL240.
But since I have been working on the performance table and graphs now looking even better, I am excited for sim testing.
I am expecting somewhat +500fpm increase on top of current improvements.
I hope sim testing will prove my calculations and expectation.
