### ISSUE TITLE
[REQUEST] Include FlyByWire Livery in the mod

### ISSUE THREAD

**Issue by AdenFlorian** [flybywiresim/a32nx#1206]
We should consider including the FBW livery in the mod itself.

**Comment by Pleasure0102** [comment]
Totally agree it's part of the mod imho

**Comment by snaylor111** [comment]
Yup 😉

**Comment by Pleasure0102** [comment]
Question : make it default livery?

**Comment by MisterChocker** [comment]
> Question : make it default livery? Of course switchable. But the first one before you select one

absolutely

**Comment by calwalker1** [comment]
Would be a great way to spot other FBW players online!

**Comment by omarosva** [comment]
Hola gente, felicitarlos por el gran trabajo que se viene haciendo, mejorando el A320 , lamentablemente esta fusión no funciona el el overhead y demás los lnop aparecen de nuevo, ojala se corrija pronto

**Comment by fourdragons** [comment]
Flying with it right now. Works great! 👍
