### ISSUE TITLE
[BUG] RMP does not work with Logitech radio panel

### ISSUE THREAD

**Issue by tooldrmr2009** [flybywiresim/a32nx#1211]
**Mod Version**
 latest flyby wire mod downloaded using the installer

**Describe the bug**

Radio stack in the Airbus a320 does not work with the logitech flight radio panel.  The a320 without your mod works with the logitech radio panel and the panel works in various other aircraft.

**To Reproduce**

1. Happens all the time
2. No certain time frame
3. Logitech radio panel inop with the a320nx

**Expected behavior**

When switching radio frequencies it'll show in the a320 it's being switched and when clicking the standby button it'll switch from active to standby and it does not do this.

**Actual behavior**
. Changing the logitech frequencies leaves the a320 frequencies alone and doesn't show they've been changed

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by ElSrJuez** [comment]
Please check if this may have a common root cause with https://github.com/flybywiresim/a32nx/issues/1079
If so, consider merging.

**Comment by tooldrmr2009** [comment]
I believe it does share similarities however I am using logitech software to provide the drivers for the MSFS2020 it works in all other aircraft except the a320 thats why I believe its an issue directly with the a320 either flybywire or the a320 in general.

**Comment by Benjozork** [comment]
> either flybywire or the a320 in general.

Can you please confirm this ?

**Comment by tooldrmr2009** [comment]
I will remove the fly by wire mod and see if it works tonight and post up my findings!

**Comment by tooldrmr2009** [comment]
I have removed flybywire and ran the default MSFS2020 A320 and the panel still does not work so its not a Flybywire mod, but maybe it can still be fixed by you guys?  My panel works with other aircraft, 747, 787 ect so i know its not my panel or settings/drivers.

**Comment by carl-lol** [comment]
I've got the same problem

**Comment by Benjozork** [comment]
Please state your add-on version.

**Comment by carl-lol** [comment]
Version 0.5.3, the latest stable version

**Comment by Benjozork** [comment]
Can you try with the development version? Should work better.

**Comment by carl-lol** [comment]
ok, is there a great difference between those version for me as a player?

**Comment by carl-lol** [comment]
thx now it works

**Comment by davidwalschots** [comment]
@tooldrmr2009 Are you still having this problem?

**Comment by MisterChocker** [comment]
Closing since no response from op.
