### ISSUE TITLE
[BUG] windshield divider dark texture

### ISSUE THREAD

**Issue by AdenFlorian** [flybywiresim/a32nx#1212]
**Mod Version**

master

**Describe the bug**

bad texture

vanilla:
![image](https://user-images.githubusercontent.com/3533988/95531246-ad7f7f80-09a5-11eb-8397-5b13f7053d68.png)

master:
![image](https://user-images.githubusercontent.com/3533988/95531257-b40df700-09a5-11eb-8441-eb0054ff8335.png)

**References**

![image](https://user-images.githubusercontent.com/3533988/95531327-db64c400-09a5-11eb-9f50-a66f04e14f7a.png)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by AdenFlorian** [comment]
@Pleasure0102 please take a look when have the time, thanks!

**Comment by Pleasure0102** [comment]
Will be fixed tomorrow. I will be home quite soon so eta 4-5 hours
