### ISSUE TITLE
[BUG] FlyByWire Mod not installing

### ISSUE THREAD

**Issue by dcherrie** [flybywiresim/a32nx#1214]
**Mod Version**
Latest master at the time of this post.

**Describe the bug**
When downloading the latest master zip and installing it in the community folder, inside FS2020 its not recognising and using the default Asobo A320.

**To Reproduce**
1. Download latest master and unzip
2. Delete previous A320NX from the community folder
3. Empty recycle bin
4. Copy new A320NX folder into community folder
5. Open FS2020, spawn with the A320 at a gate and is the default Asobo A320.

**Expected behavior**
Should be FlyByWire mod aircraft.

**Actual behavior**
Is Asobo aircraft.

**References**
n/a

**Additional context**
n/a

**Comment by Pleasure0102** [comment]
Check the announcements you should use vmaster, try it with that

**Comment by Benjozork** [comment]
@Pleasure0102, users are not required to use discord tbh

@dcherrie, downloading via the "Code" button is no longer supported.

Please use the installer or use the direct links provided in the "A32NX Installer" section of the README.

**Comment by dcherrie** [comment]
@Benjozork thanks! Installer application works great. Just to clarify the developer build is the latest unstable master branch build right?
