### ISSUE TITLE
[BUG] Plane not following approach anymore with latest master (09 Oct.)

### ISSUE THREAD

**Issue by ErikNL80** [flybywiresim/a32nx#1218]
**Mod Version**

Master (Download from October 9th)

**Describe the bug**

I did a flight from EGLC to EGNM, and did an ILS for RWY32. The MCDU directs to the ILS32 instead of following the waypoint of the approach. Also noticed the same behaviour on another flight

**To Reproduce**

1. Set-up a short IFR flight with predefined arrival
2. Fly the plane using the autopilot
3. Watch the plane on approach

**Expected behavior**

I would expect the plane to follow the flightplan and waypoint until manual override

**Actual behavior**

As soon as the last 'normal' waypoint is past the plane wants to go direct to the runway.
![Appr](https://user-images.githubusercontent.com/71258178/95564688-71890080-0a1f-11eb-9ee5-36949b23763c.png)

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Found the issue this week, probably after some PR's to enhance the MCDU.
Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):

**Comment by ErikNL80** [comment]
In the above case the next waypoint should be DME09, but the plane wants ILS RW32

**Comment by lousybyte** [comment]
As far as I know this is due to the shape of the route, mostly the very narrow U shaped ones or ones that go over the runway like in your case. Try using a different (wider) or straight approach and see if you still have the issue.

**Comment by ErikNL80** [comment]
Yes, maybe this is not the right example, but had the same issue yesterday with EKCH landing ILS 22L. It was a nice great curve overflying Copenhagen and here the same happened. In previous versions never had issues with it?

**Comment by lousybyte** [comment]
Might be different issue then, will have to test later.

**Comment by lousybyte** [comment]
Can't replicate, landed at EKCH ILS 22L just fine.
[https://postimg.cc/QHmk9Gmm](https://postimg.cc/QHmk9Gmm)

**Comment by pickels98** [comment]
had exactly the same problem with an approach to LGTS/16 localizer under wide angle. A.C. follows the fligthtplan to the last waypoint but skips the approach fixes and goes DCT to the runway. (last master - default nav data)

**Comment by theersink** [comment]
I have encountered this too but at other times it flies fine. The only thing I can think of that I did different was on the ones that the AP did not fly the approach and went direct to the airport, I had loaded the approach after starting the flight rather than loading it into the flightplan from the planning screen. Won't be able to test for a while due to life commitments but may help narrowing it down.

**Comment by ErikNL80** [comment]
Today had a similar experience with latest master, also created a topic at the MSFS forum with some screenshots. Maybe this gives some guidance? https://forums.flightsimulator.com/t/flytampa-copenhagen-ils22l-approach-not-followed-with-tudl1n-approach/305508

**Comment by Paikanx** [comment]
Similar experience with a flight from LFPO to LSGG, at some point, Autopilot goes directly to the airport.
