### ISSUE TITLE
[BUG] ILS FMA changes when disconnecting AP

### ISSUE THREAD

**Issue by sef3613** [flybywiresim/a32nx#1222]
**Mod Version**

Latest master

**Describe the bug**

After intercepting the G/S and LOC with the AP on, I disconnected the AP. The FMA reverted to "CLB" instead of remaining on the glideslope so I had to press the "APPR" button again on the FDU to recapture. The autothrust mode also changed to "THR CLB" when it should remain in "SPEED" mode. The FMA/FD should stay in "G/S LOC" when disconnecting the AP.

**To Reproduce**

1. With AP on, hit APPR button to intercept the localizer and glideslope.
2.Once established on the ILS approach, disconnect the autopilot (using the red button on the sidestick).
3.Note the FMA change (THR CLB, CLB) and pitch flight director no longer is giving glideslope guidance.

**Expected behavior**

When disconnecting the AP on an ILS approach, the FMA/FD should stay in "G/S LOC" so that you can use the flight directors to hand-fly the ILS. The autothrust mode should also remain in "SPEED" mode.

**Actual behavior**

Plane correctly stays in "LOC"  but the pitch mode reverts to "CLB" which renders the pitch FD useless. The autothrust mode also switched to "THR CLB."

**References**

This was just after disconnecting the AP on the ILS 16C into KSEA:
![Screenshot (93)](https://user-images.githubusercontent.com/70450099/95591826-d2abd680-0a15-11eb-94ef-8ebc60ed7c81.png)

Here is V1 Simulations (Real airbus captain) disconnecting the AP on an ILS in the FFA320. Note the plane stays in (G/S LOC) and the autothrust stays in (SPEED):
https://youtu.be/FsROrvv9tJs?t=6847

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by sef3613** [comment]
> The problem is that, when AP is disconnected, APPR turns off and switches to LOC mode. Same here too on latest release version.

Yup exactly^. As well as the autothrust switching modes which shouldn't happen

**Comment by antikythera288** [comment]
yep, can confirm, this is happening for me aswell when disconnecting the AP.

**Comment by sef3613** [comment]
Yup, I really wish I would get a response on this issue as it's a pretty big deal imo.

**Comment by antikythera288** [comment]
> 
> 
> Yup, I really wish I would get a response on this issue as it's a pretty big deal imo.

i am looking into it ... but cant promise something

**Comment by SLUF4** [comment]
I understand that this issue was closed.  It does hold the modes now, but the test I just did  KSUX ILS 31, I disconnected the AP, and my FD is showing that I need to fly up, but the GS is 1 dot below me. It stayed like that until touchdown.  I just disregarded the FD and manually flew the GS.  I'll try to test at a few more airports.

**Comment by antikythera288** [comment]
> I understand that this issue was closed.  It does hold the modes now, but the test I just did  KSUX ILS 31, I disconnected the AP, and my FD is showing that I need to fly up, but the GS is 1 dot below me. It stayed like that until touchdown.  I just disregarded the FD and manually flew the GS.  I'll try to test at a few more airports.

Yes, in the PR there is a section where I am describing the limitations of the implementation. Unfortunately the FD movement is not in our control, it's handled internally in ASOBOs auto pilot ... it's a general issue that the FDs are "dead" when the AP is Off ... I am afraid this will be solved only when there is an "own" Autopilot logic
