### ISSUE TITLE
[BUG] camera bugging out and then the game crashes

### ISSUE THREAD

**Issue by nikotina91** [flybywiresim/a32nx#1225]
**Mod Version**
master

**Describe the bug**
After some time during flight the camera turns around towards the seat, it cant be moved anymore and the game crashes

**To Reproduce**

1. start from cold and dark
2. takeoff
3. wait a while, sometimes it happens sometimes it doesn't

**Expected behavior**

camera behaving normally and not crashing the game

**Actual behavior**

camera getting stuck looking at the seat and game crashing

**References**

**Additional context**

Was this working before/when did the issue start occurring?
it started happening about a week ago.

Is this a problem in the vanilla unmodded game?
not sure.

Discord username (if different from GitHub):

**Comment by ChruutvoLuzi** [comment]
Thats a Vannila Problem. Try turning Multiplayer off

**Comment by nikotina91** [comment]
alright I'll try thanks.

**Comment by Benjozork** [comment]
Closing as this is a game bug.
