### ISSUE TITLE
[BUG] altitude alert

### ISSUE THREAD

**Issue by KeepGamingLP** [flybywiresim/a32nx#1227]
**Mod Version**
0.3.1.

**Describe the bug**

If you are reaching or leaving your preselect or managed altitude there should be an alert sound.

**To Reproduce**

1.set altitude
2.climb
3.reach altitude

**Expected behavior**

**Actual behavior**

**References**

- (redacted by admin)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by NathanInnes** [comment]
Do you have any reference for this behaviour?

**Comment by lukecologne** [comment]
![grafik](https://user-images.githubusercontent.com/39596827/95640895-5d84e380-0a9f-11eb-8dfe-4c49e558872d.png)

**Comment by Benjozork** [comment]
ESLD reference

![image](https://user-images.githubusercontent.com/4503241/95643615-3ec22500-0a7e-11eb-9bdf-9e6e31dba163.png)

**Comment by KeepGamingLP** [comment]
https://youtu.be/sudHp3xdkzY
@4:05 you can hear the sound of c chord.

**Comment by donstim** [comment]
Shouldn't this be an enhancement rather than a bug?

**Comment by hotshotp** [comment]
If someone can code the behaviour of it being toggled I can add a wwise event

**Comment by MisterChocker** [comment]
This has been implemented by now.

**Comment by beheh** [comment]
So while the visual altitude has been implemented, the aural altitude alert as outlined in the initial report has not been implemented. This will be added by #3281 though.
