### ISSUE TITLE
[BUG] Layout.json and manifest.json absence

### ISSUE THREAD

**Issue by kferrano** [flybywiresim/a32nx#1229]
**Mod Version**

DEV

**Describe the bug**

Layout.json and manifest.json absence

**To Reproduce**

1. Download Dev Version
2. -/-
3. -/-

**Comment by MMontalto** [comment]
![image](https://user-images.githubusercontent.com/18440901/95632624-59000100-0a86-11eb-9033-d453b51b1a1e.png)

From @AdenFlorian discord channel @contributors

**Comment by kferrano** [comment]
Ok, but the download .exe for the a320 mod is pointless because you still have to go into the folder.

**Comment by kferrano** [comment]
how run build.py ?

**Comment by lukecologne** [comment]
Also from @AdenFlorian :
Hi! A little has changed recently about how people can/should go about downloading the A32NX mod, so I wanted to write out a little guide here.

All links are at the bottom of this post.

**Users**
If you want to use the mod in general, then use either the latest stable release or the master pre-release, via links in the readme, website, or the installer (make sure you have the latest version of the installer! The old versions don't work for getting the dev version anymore!).

**Developers**
If you are a developer working on the mod (programmer, artist, sound, etc.), you should use some form of git, and you must run build.py yourself before the mod will work. Ask questions in #dev-support.
See also: https://github.com/flybywiresim/a32nx/blob/master/.github/Contributing.md

**A32NX Installer (Latest version is 0.3 released 2020-10-07)**
The installer allows you to install the latest stable release, or the unstable dev pre-release (master branch).
https://github.com/Externoak/A32NX-installer/releases/latest/download/A32NX_Downloader.zip
more info here: https://github.com/Externoak/A32NX-installer/releases/latest

**Latest Stable Release (Currently v0.3.1 released 2020-09-30)**
https://github.com/flybywiresim/a32nx/releases/latest/download/flybywiresim-a32nx.zip
this is the same link on our website: https://flybywiresim.com/a32nx
changelog: https://github.com/flybywiresim/a32nx/releases

**Unstable Master Branch Pre-Release (Updated automatically multiple times a day)**
https://github.com/flybywiresim/a32nx/releases/download/vmaster/A32NX-master.zip
more info here: https://github.com/flybywiresim/a32nx/releases/tag/vmaster
changelog: https://github.com/flybywiresim/a32nx/blob/master/.github/CHANGELOG.md


All of these links can be found in the README on our github repo: https://github.com/flybywiresim/a32nx

**Comment by lukecologne** [comment]
Closing as this is intended.

**Comment by Benjozork** [comment]
> Ok, but the download .exe for the a320 mod is pointless because you still have to go into the folder.

this change was not made to make the process easier or harder, it was made because it is necessary due to how we want to improve the mod by adding custom autopilot that require different packaging processes.

**Comment by kferrano** [comment]
how run build.py ?

**Comment by AdenFlorian** [comment]
@kferrano https://wiki.flybywiresim.com/a32nx/guides/build.py

> download .exe

If you're talking about the installer, you need to get the latest version, which gets the dev build from a different location which already has run the buildpy for you:
https://github.com/Externoak/A32NX-installer/releases/latest/download/A32NX_Downloader.zip
