### ISSUE TITLE
[BUG] ILS Glide Slope Diamond Capture and Display Issue

### ISSUE THREAD

**Issue by betterpilot** [flybywiresim/a32nx#1230]
**Mod Version**

Dev Version from the Installer
built: 2020-10-09T01:15:11+00:00
ref: refs/heads/master
sha: 51d3109f62e23815769d4b47ca50e527b634382f
actor: AdenFlorian
event_name: push

**Describe the bug**
ILS Glide Slope indicator diamonds and capture functionality not working on certain runways. 

Please view reference video showing when LS is selected the G/S diamond shows momentarily then disappears from view. The only way to get it to show again is to deselect LS and then reselect LS at which point the behavior is recreated. 

I have now experienced the issue doing ILS approaches on RWY 16 at CYLW and RWY 28R at KPDX. 

I do not believe this bug is related to the approach being generated by the sim since I have tested it by manually inputting the approach frequencies. 

Further testing with the TBM 930 showed the diamond to appear on the same approach with the same ILS frequency in the attached screenshot. 

**To Reproduce**

1. Execute ILS approaches on RWY 16 at CYLW and RWY 28R at KPDX 
2. Select the LS button 

**Expected behavior**
GS Diamond to appear for vertical guidance on the approach.

**Actual behavior**
GS Diamond appears momentarily then disappears. 

**References**
Video reference of bug occurring: https://www.dropbox.com/s/2ik6dioeltftzsw/ILS%20GS%20Diamond%20Vertical%20Guidance%20Capture%20Issue.mp4?dl=0 

![Screenshot_1](https://user-images.githubusercontent.com/72628364/95636846-0d793300-0a45-11eb-9ed0-dbe9f5e9ee29.png)

Was this working before/when did the issue start occurring?
Have had this issue on last couple of builds on certain runways listed above. 

Is this a problem in the vanilla unmodded game? 
I was able to get the diamond to show on TBM but not sure about unmodded Airbus Neo

Discord username (if different from GitHub): AWE593

**Comment by yunnypuff** [comment]
I have had the GS diamond not show up (and approach mode doesn't seem to know about it) in the NEO at:

KSNA (ILS RWY 20R)
KSAN (ILS RWY 9)

It did work at KLAX.

I was able to land at KSAN ILS RWY 9 using the published ILS frequency and was able to see the glideslope indicator in the XCUB.
