### ISSUE TITLE
[BUG] EWD shows 100% thrust limit before thrust is changed

### ISSUE THREAD

**Issue by JacobKreindler** [flybywiresim/a32nx#1231]
**Mod Version**

master

**Describe the bug**

The readout that shows the percentage of thrust being put out is at 92% until the levers are set to toga and returned to idle again

**To Reproduce**

1. Spawn in anywhere with the A320
2. Go through the engine start procedure
3. Look at the readout at the top right of the top ECAM screen

**Expected behavior**

The ECAM should show the true readout at all times

**Actual behavior**

The readout shows 92% untill the thrust levers are set to TOGA and then returned to Idle

**References**

![Microsoft Flight Simulator 2020-10-09 8_54_40 PM](https://user-images.githubusercontent.com/70914399/95642032-f7cf3200-0a73-11eb-8967-b8965e97717d.png)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):
Discord Username - JacobK #9511

**Comment by Benjozork** [comment]
Will be merged into #909
