### ISSUE TITLE
how run build.py ?

### ISSUE THREAD

**Issue by kferrano** [flybywiresim/a32nx#1234]
how run build.py ?

**Comment by PuL9** [comment]
1. Install Python https://www.python.org/downloads/
2. Run build.py

**Comment by kferrano** [comment]
Thank you, it would have been nice if it had been written somewhere.

**Comment by kferrano** [comment]
After I ran build.py, it still doesn't work because the 2 .json files are still missing

**Comment by Pleasure0102** [comment]
@kferrano do you want to contribute to the project or use it? Because the master is now for devs only. There is a "vmaster" for users where you do not have to run build.py

**Comment by PuL9** [comment]
That is why it is not written somewhere, it is for people who know what it does.
If you want to download latest unstable version there is a link in readme
https://i.imgur.com/2hDDUtb.png
https://github.com/flybywiresim/a32nx/releases/download/vmaster/A32NX-master.zip

**Comment by kferrano** [comment]
how often is the latest unstable updated?

**Comment by PuL9** [comment]
https://github.com/flybywiresim/a32nx/releases/tag/vmaster

**Comment by Pleasure0102** [comment]
There is no clear answer to that. So how this works is that people
Work on things in their own time. Create a "pull request"  for something they want to add to unstable (master/vmaster). After testing by our qa team it will be merged or bugs fixed first and then merged. Or in rare cases the pull request is declined. So there is no schedule when things get merged. So updates happen when new features have been tested 
And approved

**Comment by Pleasure0102** [comment]
Just to be clear this will be closed soon. So for any further questions check discord. This should be for bugs /issues / suggestions
To enhance the mod. Not support

**Comment by NathanInnes** [comment]
If you require support in future please use discord instead :) Github is for tracking feature requests and bugs.
