### ISSUE TITLE
Improve cruise sound

### ISSUE THREAD

**Issue by lalloretpilou** [flybywiresim/a32nx#1235]
**Is your feature request related to a problem? Please describe.**

I don't know if the sound in flight has already been modified, but when cruising it is not very realistic compared to reality

**Describe the feature you'd like to see implemented**

**References**

https://youtu.be/qizueSHEd8w

**Additional context**

Discord username (if different from GitHub):

**Comment by waredrive** [comment]
I don't really understand the reference video you posted. Do you want a Boombox playing "Sail" in the cockpit?

**Comment by Pleasure0102** [comment]
sounds get constantly updated, depending on which version you are using. 
We also get lots of feedback from pilots saying it actually is realistic, it was improved a dozen times already.

so first question: Which version ?

**Comment by lalloretpilou** [comment]
I ve the last dev version. But in the reality when I fly the sound in the cockpit is more acute. And the engine sound are not very realistic. Listen some cockpit sound on YouTube and the cockpit sound on the Fs.

i am sure i will see the difference and you will understand what i mean.  it's never easy to describe a sound in writing !!

**Comment by Pleasure0102** [comment]
the engine sounds have not been touched yet, they are being worked on though, ofc there can always be adjustements. I will tag @hotshotp here who is doing the sounds.

**Comment by hotshotp** [comment]
> I ve the last dev version. But in the reality when I fly the sound in the cockpit is more acute. And the engine sound are not very realistic. Listen some cockpit sound on YouTube and the cockpit sound on the Fs.
> 
> i am sure i will see the difference and you will understand what i mean. it's never easy to describe a sound in writing !!

I am updating engine sounds already, that is coming pretty soon. One thing is the wind, we have added wind and avionics ventilation sounds. When packs are implemented that will also be another thing to add to the ambience. With everything in total, it will sound much more realistic

**Comment by MisterChocker** [comment]
> I don't really understand the reference video you posted. Do you want a Boombox playing "Sail" in the cockpit?

YES PEALSE!! :D

**Comment by Benjozork** [comment]
Closing as nothing concrete is being discussed, and sound improvements are already planned.
