### ISSUE TITLE
[REQUEST] Barometric pressure button. Strobe lights. Standby compass.

### ISSUE THREAD

**Issue by PuL9** [flybywiresim/a32nx#1236]
**Is your feature request related to a problem? Please describe.**

If the barometric pressure is set to standard and you change it back to selected mode, it always goes to QFE instead of QNH.
Strobe lights are visible in the cockpit at night.
Standby compass light switch is working but there is no standby compass modeled in the aircraft.
Cabin temperature is always at 24c

**Describe the feature you'd like to see implemented**

When switching from STD to selected pressure it should remember last selected mode (QFE/QNH) or always set it to QNH 
Standby compass light switch getting disabled (inop.)

**References**

--

**Additional context**

I might be wrong here, but screen (PFD and others) backlight looks a bit too much, I have seen night videos on youtube and the backlight is barely/not visible.

Discord username is the same as on Github.

**Comment by fourdragons** [comment]
That double-click on the barometric pressure always bothers me, too. 😁

**Comment by Benjozork** [comment]
Bug reports should be for one specific bug, this one has three. Please look if other already reported the issue then create separate issues.
