### ISSUE TITLE
Tracking: Using Rust for WASM Modules

### ISSUE THREAD

**Issue by devsnek** [flybywiresim/a32nx#1239]
This weekend we have been working on a rust library for writing MSFS addons (https://github.com/devsnek/msfs-rs) and the library is now in what I would call an "MVP" stage. From this point, I would like to gauge interest in using this for the various wasm projects that are currently in progress, and if there is interest, I'd like to work with the relevant people to improve the library's coverage of the SDK and port code over.

Why would we want to use Rust instead of C/C++? (ordered by importance, in my opinion)

- Memory safety and correctness (reduces the likelihood of our addons crashing)
  - Thread safety, for when MSFS adds threads
- Supports WASM as a first-class target
- Great standard library
- People like Rust

cc @akaritakai @ThePilot916 @wpine215

**Comment by akaritakai** [comment]
I'm not against this. However, in fairness, I am also going to list some cons in the context of this request:
1) Asobo has said that they will make SDK changes in the future to accommodate developers like PMDG. These will likely be features we want/need, and so this library will need active maintenance with all SDK changes.
2) The Visual Studio add-on allows for debugging the WASM file against the C++ code that generated it. If we moved to Rust, would we lose this ability?

**Comment by devsnek** [comment]
> 1. ...

I'm planning to maintain the library as long as it's being used, though it would definitely be good to get some more people helping with it.

> 2. ...

We looked at this a bunch yesterday. Visual Studio most likely is unable to provide the debug experience for rust, but newer editors like VSCode and CLIon have proper rust support and should handle the debugging.

**Comment by AdenFlorian** [comment]
> We looked at this a bunch yesterday. Visual Studio most likely is unable to provide the debug experience for rust, but newer editors like VSCode and CLion have proper rust support and should handle the debugging.

Is this something you can test now?
Does CLion have a free community version like visual studio does?

**Comment by nistei** [comment]
CLion is free for OSS
https://www.jetbrains.com/community/opensource/#support
![image](https://user-images.githubusercontent.com/1652722/96320695-6b90b200-1013-11eb-8d47-c28ffb0d6bbf.png)

**Comment by devsnek** [comment]
You can also access CLion (and the rest of jetbrains software) through github student backpack. That being said, you don't need a big fancy IDE with a debugger to develop addons (I use vim), it's just something we should make sure we support.

**Comment by Benjozork** [comment]
I'd like to add that VSCode with the `rust-analyzer` plugin is considered one of the two main options for rust development and it's free and OSS. The other being `intellij-rust`, referred to here as CLion.

**Comment by AdenFlorian** [comment]
@akaritakai have you used the visual studio addon to debug WASM in MSFS?

**Comment by davidwalschots** [comment]
I think we can agree we have some Rust running in the sim.
