### ISSUE TITLE
[BUG] Autopilot don't work

### ISSUE THREAD

**Issue by Amunlar** [flybywiresim/a32nx#1240]
**Mod Version**

built: 2020-10-09T16:07:45+00:00
ref: refs/heads/master
sha: 40080314220bd8931106aebe97cf48b4140db3c4
actor: lukecologne
event_name: push

**Describe the bug**

Autopilot won't follow the flightplan. It starts bank either to the right or left at an 50 degree angel.

**To Reproduce**

1. File a flightplan
2. Takeoff from runway
3. Activate Autopilot and managed heading.

**Expected behavior**

The autopilot is supposed to follow the selected waypoint in the flightpath.

**Actual behavior**

The autopilot starts bank at 50 degree angel, either to the right or left.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
It worked before the 1.9.3 update.

Is this a problem in the vanilla unmodded game?
Im not sure

Discord username (if different from GitHub): Amunlar#9633

**Comment by lukecologne** [comment]
First of all, please add a title. Second: This may be a duplicate, please take a look at #1171 and #1006.

**Comment by lukecologne** [comment]
Can you confirm that you are experiencing the same issue as mentioned?

**Comment by metahmet** [comment]
I can confirm that autopilot also for me doesn't follow the flight plan. Especially, when heading to descent approach landing phase, then just starting to bank eithere to the left or right.

**Comment by vryzhenkin** [comment]
Almost sure that this is a dup of #1006 (there a video in comments https://github.com/flybywiresim/a32nx/issues/1006#issuecomment-701628932) . Got the same behaviour after 1.9.3. with 0.3.1 and latest master (e.g v0.3 and v1.8.3 worked fine together). Probably mod doesn't causing it. That's the bug for Asobo probably.

**Comment by MuppetOwl** [comment]
I had this exacts same issue after the latest Asobo/Flight Simulator patch since it did delete my sensitivity settings, but also did some changes on how sensitive the controller is. I had to increase the deadzone settings even more than before to solve the problem. Now its all good.

**Comment by SergeantSerk** [comment]
I can confirm I have this issue as well, but without this mod installed, try it on the vanilla A320 and see if you experience the same thing because I did as well.

**Comment by BROADACRES16xFS17MAP** [comment]
> 
> 
> I had this exacts same issue after the latest Asobo/Flight Simulator 1.9.3 patch since it did delete my sensitivity settings, but also did some changes on how sensitive the controller is. I had to increase the deadzone settings even more than before to solve the problem. Now its all good.

Can you please share your settings. Have same problem after hitting auto pilot and banks right and does circles.

**Comment by SergeantSerk** [comment]
> I had this exacts same issue after the latest Asobo/Flight Simulator 1.9.3 patch since it did delete my sensitivity settings, but also did some changes on how sensitive the controller is. I had to increase the deadzone settings even more than before to solve the problem. Now its all good.

Can confirm, increased my deadzone to 25% on all axis (maybe arbitrary?) and autopilot follows nav correctly.

**Comment by BROADACRES16xFS17MAP** [comment]
Okay I fixed mine by removing my other yokes settings in the msfs2020 settings menu. I am running a honeycomb yoke for actual flying but run a Saitek throttle through my saitek yoke (non usb saitek throttle). I removed my saitek yoke settings it had picked up and now no issues at all.

**Comment by MisterChocker** [comment]
Seems to be fixed. User hardware error.
