### ISSUE TITLE
[BUG] Switching to MACH is not revertable

### ISSUE THREAD

**Issue by mfnalex** [flybywiresim/a32nx#1241]
**Mod Version**

latest master

**Describe the bug**

When switching the autopilot to MACH, it is not possible to revert this

**To Reproduce**

1. Click on "SPD MACH"
2. Click again
3. It still displays the speed in MACH
It's not always bugged, I somehow got it to revert to knots by disabling the autopilot or something, I cannot recall exactly

**Expected behavior**

It should revert to knots

**Actual behavior**

It doesn't^^

**Additional context**

I don't use any other mods

Discord username (if different from GitHub):
Discord: mfnalex#1908

BTW thanks for this AWESOME mod! 👍  :)

**Comment by Codeh4ck** [comment]
There's a specific altitude in which the A320 will automatically switch from knots to mach. This is also reflected in the PFD where SPEED will be replaced with MACH. If my memory serves, it's FL280 and above. This is how a real A320neo operates as well

**Are you sure you're not passing that threshold?**
Try lowering your altitude below FL280 and switch from mach to knots if that's the case. It should work fine.

**Comment by ukflyer** [comment]
This is an issue also in the default where you cant switch back to knots. A workaround is to add a key assignment to SET AP MANAGED SPEED IN MACH OFF

![343bc2fb92ec9e6710eba22e2efd11182a11800f](https://user-images.githubusercontent.com/70434502/95673577-bd63b300-0ba1-11eb-9074-22fdfe011fab.png)

**Comment by mfnalex** [comment]
Thanks for the clarification :)

**Comment by nobodyn0se** [comment]
This issue must be kept open until a proper fix is implemented. This would avoid duplicate issues of the same bug when people try to search for an open issue that references the mach. 
For the record, the first machfix for this mod allows you to manually toggle SPD/MACH on ground. 
It does not affect the auto-toggle in air. 

Currently, SPD -> MACH switch happens normally above crossover altitude during climb. But it does not switch back to knots below crossover altitude on descent. **It must be manually toggled** or it remains in MACH for the rest of the flight.
