### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by st3ph29** [flybywiresim/a32nx#1244]
**Mod Version**

dev version 

**Describe the bug**
<When I select the VOR/NDB switch, on the Captain's efis, the VOR does not appear in ND and the screen does not move, even if I move the range selector. In the FO, it works perfectly. 

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by lukecologne** [comment]
Add a title please

**Comment by Benjozork** [comment]
Issue does not follow template
