### ISSUE TITLE
[BUG] F-PLAN no calculation after input

### ISSUE THREAD

**Issue by lalloretpilou** [flybywiresim/a32nx#1245]
**Mod Version**
Last dev version

**Describe the bug**

I have just entered my flight plan with the performances, the cost index and the Cruise level and yet the calculations are not done

**To Reproduce**

**Expected behavior**

**Actual behavior**

**References**

![image](https://user-images.githubusercontent.com/42711915/95676470-b303e200-0bbe-11eb-8e48-d9ec2d2a9ef6.jpeg)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Please follow issue template as there is missing information. Will close until that is corrected.
