### ISSUE TITLE
Resource: Airbus 319/320/321 Flight crew menu

### ISSUE THREAD

**Issue by edmond1992** [flybywiresim/a32nx#1246]
I download it some times before, maybe would help
[https://www.avsimrus.com/f/aviation-documents-15/full-a320-fcom-vol-1-2-3-4-7364/zip](url)

**Comment by Benjozork** [comment]
Hello, thank you for the document. GitHub issues are more ideal for bug reports and feature requests however so I'd advise you join our Discord to provide us with documents.
