### ISSUE TITLE
Aircraft banks without any input before touchdown [BUG]

### ISSUE THREAD

**Issue by vlbreda** [flybywiresim/a32nx#1248]
**Mod Version**

Master

**Describe the bug**

Just before touchdown (5-10 ft RA) the aircraft often suddenly banks. There is no input from flightstick, a/p is disengaged, winds are set to 0

**To Reproduce**

1. Fly approach, winds zero
2. Turn off a/p at 200 ft AGL and try to land manually (AThr still on, appr. speed 145)
3. just before touchdown, aircraft banks with no reason. 

**Expected behavior**

Aircraft stays level 

**Actual behavior**

Aircraft banks. Not all the cases, but too often to call it a minor issue

**References**

**Additional context**

Bug might be reported before by someone else
Was this working before/when did the issue start occurring?
Has allways been an issue with the 320NX

Is this a problem in the vanilla unmodded game?
Don't know for sure.

Discord username (if different from GitHub):

**Comment by lukecologne** [comment]
Duplicate #1173. Please look through existing issue before creating a new one.
