### ISSUE TITLE
[REQUEST] Electronic Flight Bag

### ISSUE THREAD

**Issue by hi1213345446231** [flybywiresim/a32nx#1251]
**Is your feature request related to a problem? Please describe.**

no

**Describe the feature you'd like to see implemented**

A tablet in the tablet holder like avitab for xplane 11

**References**

has holder for ipad

**Additional context**

Discord username (if different from GitHub):

**Comment by aviationenthusiast** [comment]
please add a title.

**Comment by lukecologne** [comment]
This is called an EFB, electronic flight bag. It is already planned, but we currently have no way of bringing it into the sim.

**Comment by Benjozork** [comment]
Issue should not be closed as the request is not complete and is planned to be added.
