### ISSUE TITLE
[BUG] Upper ECAM not displaying "SELF TEST IN PROGRESS"

### ISSUE THREAD

**Issue by Lamao2244** [flybywiresim/a32nx#1254]
**Mod Version**
 Latest Master

built: 2020-10-11T14:46:24+00:00
ref: refs/heads/master
sha: 01a66a60c570a4f1068c0f8430846de1ced32582
actor: Benjozork
event_name: push

**Describe the bug**
 Upper ECAM does not display "SELF TEST IN PROGRESS" during Startup. 

**To Reproduce**

1.Start up plane in Cold and Dark
2.Monitor Upper ECAM

**Expected behavior**
"SELF TEST IN PROGRESS" to be shown in all displays when engaging EXTERNAL POWER/APU initially.

**Actual behavior**
 Upper ECAM does not display "SELF TEST IN PROGRESS" during Startup. 

**References**

![bug](https://user-images.githubusercontent.com/72637344/95685092-6228d380-0c28-11eb-8461-12e5d032ca0d.png)

**Additional context**

Was this working before/when did the issue start occurring? Occurs on latest Master

Is this a problem in the vanilla unmodded game? No

Discord username (if different from GitHub): LaMao

**Comment by Benjozork** [comment]
Ugh, this is like a whack-a-mole game 😆 never got it during testing strangely ...

Will see why this is happening. Thanks for the report 👍

**Comment by Lamao2244** [comment]
Wlc :)
