### ISSUE TITLE
aerodynamic problem - FLAPS [LANDING & TAKEOFF]

### ISSUE THREAD

**Issue by lalloretpilou** [flybywiresim/a32nx#1255]
**Mod Version**
Last dev version

**Describe the bug**

**To Reproduce**
1. **For take off:**  take with 1+F flaps and at 2000ft/ 200knots retract flaps.=> The plane loses a lot of altitude very quickly and the speed increases and exceeds 250knots and therefore you are in overspeed.
2. **For landing:** When you are lined up on the track between 200-220 knots. you pull out flaps 1 by 1. The plane becomes uncontrollable, the vario becomes very high, the plane pulls up a lot, we gain a lot of altitude, and we lose a lot of speed up to 140 knots. (STALL). _The attitude of the airplane is the same whether it is a manual landing, ILS, Rnav._

**Expected behavior**
When in real life, I pull out the flaps after take-off and for landing, the plane does not get out of control, and the change in speed and altitude is very minimal.

**Actual behavior**
1. **For take off:** The plane loses a lot of altitude very quickly and the speed increases and exceeds 250knots and therefore you are in overspeed.
2. **For landing:** The plane becomes uncontrollable, the vario becomes very high, the plane pulls up a lot, we gain a lot of altitude, and we lose a lot of speed up to 140 knots. (STALL).

 _The attitude of the airplane is the same whether it is a manual landing, ILS, Rnav._

**References**
My video:
https://www.youtube.com/watch?v=DiKxbWAyQQI

**Additional context**
I created a video to show you the problem on landing.
During the Take off the effect is opposite.

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment]
Already opened such an Issue https://github.com/flybywiresim/a32nx/issues/1204.
Jeez what are you trying anyways.. ur insane.

**Comment by sef3613** [comment]
Lol and I thought my DA40 was tricky to control the balloon when adding flaps.... This flight model is somethin else

**Comment by sef3613** [comment]
I like how the FMA modes are so borked when handflying too. It doesn't do ALT*/ALT but rather switches from DES to CLB when you pass the altitude when handflying.

**Comment by lalloretpilou** [comment]
After the MSFS update et the last Dev version, I've already the aerodynamic problem when I use the flaps during take off and landing, the altitude increase when flaps down until STALL. and inversely.
but in turns the bug has been fixed.

**Comment by Sheetso** [comment]
Today I had exactly the same problem as OP. Uncontrollable at landing!

**Comment by MrGilgamesh89** [comment]
Hi. I have observed same behavior twice on most recent builds. After setting Flaps to 1 before approach aircraft becomes uncontrollable exactly as mentioned above. Setting Flaps to 2 has same effect, however it appears that after Flaps are set to 3 aircraft stabilizes. 

When it comes to take-off, retracting the Flaps causes sudden loss of V/S, however it is definitely not comparable with complete loss of control observed on approach.

Once aircraft stabilized the pitch was incredibly low.

**Comment by Sheetso** [comment]
Also tried now #1295 but still same problem. It always rockets up into the air after raising flaps to 1. What I've also noticed is, that the angle of the plane itself when raising the flaps, is a bit broken. I have to pull down to -25° to fly straight with VS-0

**Comment by lalloretpilou** [comment]
I think we all have the same problem.  I don't know if it can be corrected by flybywire or by Microsoft but it is really annoying.  this does not preclude using the 320.

**Comment by joniatus** [comment]
That sounds like you are using legacy flight model rather than modern in settings. I've had it switch on me before after asobo update

**Comment by lalloretpilou** [comment]
> That sounds like you are using legacy flight model rather than modern in settings. I've had it switch on me before after asobo update

What is the setting to modify? It interests me because I have concerns on all planes.

**Comment by joniatus** [comment]
![Screenshot_20201015-100348__01](https://user-images.githubusercontent.com/71446004/96140425-ea7bd280-0ecd-11eb-9f94-32c2d909e41f.jpg)

Make sure it's set to modern

**Comment by lalloretpilou** [comment]
> ![Screenshot_20201015-100348__01](https://user-images.githubusercontent.com/71446004/96140425-ea7bd280-0ecd-11eb-9f94-32c2d909e41f.jpg)
> 
> Make sure it's set to modern

ohh! it is regulated on history.
I just had a test flight and it's excellent. More problems.
thank you very much. you saved me !!

**Comment by MrGilgamesh89** [comment]
Hi, same here. It solved the problems, I was finally able to land without any surprises - Thank You!

**Comment by Sheetso** [comment]
So with other words, we are not able to fly with the realistic flight model. Only with the unrealistic arcade one...

**Comment by joniatus** [comment]
Yes, except the exact opposite of what you said
