### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by griffon55** [flybywiresim/a32nx#1256]
**A320**

**blank screen**

**on the runway ready to take off**

1.
2.
3.

**screen sould be on**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Issue does not respect issue template and has no screenshots
