### ISSUE TITLE
[BUG] > tiny bug: first cargo door opening sound (cold&dark start) not playing

### ISSUE THREAD

**Issue by Watsi01** [flybywiresim/a32nx#1262]
**Mod Version**
current master

**Describe the bug**
The first of all cargo door sounds is not playing. Cold&dark start. When the baggage comes. All other cargo door sounds are hearable (closing at dep airport, opening and closing at dest airport)

**To Reproduce**

1. Enter cold&dark at gate
2. get the plane under power (Ext or APU)
3. order the baggage
4. STAY in cockpit and watch the ECAM door page
5. listen

**Expected behavior**
door sound playing

**Actual behavior**
see above

**References**

**Additional context**

Was this working before/when did the issue start occurring?
I think it was a bug since the audibles were implemented.

**Comment by aviationenthusiast** [comment]
I confirm

**Comment by Watsi01** [comment]
By the time, I wonder if there ever was an opening sound of the door? Maybe it's not a bug. @hotshotp ?

**Comment by hotshotp** [comment]
> By the time, I wonder if there ever was an opening sound of the door? Maybe it's not a bug. @hotshotp ?

I am just testing it now, it works, The cargo door is supposed to make an opening sound. I reproduced your steps and the sound played for me like it should have

**Comment by Watsi01** [comment]
Thanks @hotshotp . Strange, the opening sound never plays on my side (beeing in the cockpit of course). Always the closing sound only. I'll do further testing.

**Comment by Watsi01** [comment]
After the newest master. I hear now the opening too. So I close this one. Thanks @hotshotp

**Comment by ACSoft47** [comment]
It seem that the cargo door opening sound only play if no other doors are open. This is almost the behavior I have.
