### ISSUE TITLE
[BUG] The sound of the engines is reversed when using external camera

### ISSUE THREAD

**Issue by CJ1045** [flybywiresim/a32nx#1264]
**Mod Version**

Latest DEV and previous releases too

**Describe the bug**

If you use the external camera and have the camera rear of the plane but pointing towards the plane the engine sounds are quite quiet. If you use the mouse to swing the camera around so that it is in front of the plane pointing towards the plane the engine sounds are loud. I think it should be the other way round

**To Reproduce**

1. Select External Camera
2. Camera rear of the plane but pointing towards the plane the engine sounds are quite quiet
3. Swing the camera around so that it is in front of the plane pointing towards the plane the engine sounds are loud

**Expected behavior**

1. Select External Camera
2. Camera rear of the plane but pointing towards the plane the engine sounds should be loud
3. Swing the camera around so that it is in front of the plane pointing towards the plane the engine sounds should be quiet

**Actual behavior**

As above

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Always been there, just decided to report it

Is this a problem in the vanilla unmodded game?
I think so

Discord username (if different from GitHub):
CJ1045

**Comment by hotshotp** [comment]
This a vanilla issue. Engine sounds are being worked on and will be fixed soon.

**Comment by CJ1045** [comment]
Cool, thanks.

**Comment by hotshotp** [comment]
this is just the way that engines behave IRL. In front is the engine intake which is noisy. At the back the engine wake is very powerful and its simulated that its muffled
