### ISSUE TITLE
[BUG] Format error when autofilling ZFW

### ISSUE THREAD

**Issue by ErikNL80** [flybywiresim/a32nx#1265]
**Mod Version**

Master (2020-10-12T03:20:12+00:00)

**Describe the bug**

In the MCDU you can now automatically prefil the ZFW, but when doing so, I get a format error. The error is caused by the fact that the ZFW format is XXX.X/XX.X and tries to enter a value in format XX.X/XX.X leading to the error. If you put in a leading 0, so 0XX.X/XX.X it is accepted in the MCDU.

**To Reproduce**

1. Create a flightplan (I used LOWW/LGKO)
2. Retrieve the ZFW values
3. Fill in the retrieved values and notice the format error

**Expected behavior**

I would expect the MCDU to accept the value without the need of adding a leading 0.

**Actual behavior**

The MCDU gives a format error.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
I have seen this working in previous builds?
Is this a problem in the vanilla unmodded game?
No, this feature is not available in the vanilla aircraft
![ZFW1](https://user-images.githubusercontent.com/71258178/95732029-8adcb780-0c80-11eb-8446-f8e076eb6b12.png)
![ZFW2](https://user-images.githubusercontent.com/71258178/95732037-8ca67b00-0c80-11eb-97c1-093bf210c254.png)

Discord username (if different from GitHub):

**Comment by Watsi01** [comment]
Yepp, confirmed

**Comment by Primestarswe** [comment]
Its seems that this error is back again. I downloaded the newest version that fixed the flickering light. And was trying to do a flight, But I get again today Format Error
