### ISSUE TITLE
[BUG] PFD/ND/ECAM/FMC Issue with fonts and display

### ISSUE THREAD

**Issue by NERV-EVA-01** [flybywiresim/a32nx#1266]
**Mod Version**
Latest DEV

**Describe the bug**
The display and fonts shows incorrect and strange

**To Reproduce**
1. Started from cold and dark and started from runway and the issue remains the same

**Expected behavior**
Show correct data, fonts and display

**Actual behavior**
All messed up and incorrect

**References**
![ERRO](https://user-images.githubusercontent.com/72739100/95738626-6d5c1d80-0c81-11eb-86fa-1e050f5ed8d3.jpg)

**Additional context**

Installed the latest dev today and this ocurred

**Comment by lukecologne** [comment]
You likely didn't run build.py, please try doing that and see if that fixes your issue.

**Comment by NERV-EVA-01** [comment]
> You likely didn't run build.py, please try doing that and see if that fixes your issue.

I did that and didn't solve the issue

**Comment by lukecologne** [comment]
I just updated to master and didn't run build.py, got the exact same issue as you. Then, I ran it, and the issue was resolved. Maybe you didn't run it properly.

**Comment by NERV-EVA-01** [comment]
> I just updated to master and didn't run build.py, got the exact same issue as you. Then, I ran it, and the issue was resolved. Maybe you didn't run it properly.

I've tried again and didn't solved. However I used the installer and now works fine. Thanks
