### ISSUE TITLE
not all keyboard shortcuts work [BUG]

### ISSUE THREAD

**Issue by maor561** [flybywiresim/a32nx#1269]
**Mod Version**

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by ChruutvoLuzi** [comment]
There is a reason why there is a bug template. To fill it out

**Comment by Pleasure0102** [comment]
@maor561 an issue not following the template will most likely be deleted, please fill out the template, so we get the correct information

**Comment by lukecologne** [comment]
I will close this as the template is not followed. If you do not fill out the template, we will not have enough information to investigate the bug. When you have filled in the missing info, comment here so this issue can be re-opened.
