### ISSUE TITLE
Engine Ignition behavior during start

### ISSUE THREAD

**Issue by chrisarrow90** [flybywiresim/a32nx#127]
On ECAM ENG page, it shows both IGN A B immediately when the ENG MODE SELECTOR is placed in IGN/START. This is not correct behavior in the real aircraft.
FADEC only uses 1 igniter during the first start attempt alternating between A and B, the letter should only appear once ignition is actually applied during the start sequence which occurs at 18% N2 and the letter should disappear at approximately 55% N2.
If a start attempt fails, then the second attempt is made with both igniters.

**Comment by HorseGlass** [comment]
So when starting the right engine it uses the B igniter and the left engine uses the A?

**Comment by PCGamesF1Tech** [comment]
No, each engine has an A and B system (four systems total).

**Comment by HorseGlass** [comment]
Okay I see

**Comment by PCGamesF1Tech** [comment]
I don't know if there are plans for a FADEC sim and keeping track of which ignition was used last but I think it would be easier to just use e.g. ign A for ENG1 and ign B for ENG2 (just to have the display of different systems for a "more real" look)

**Comment by HorseGlass** [comment]
Yeah thats easily possible

**Comment by HorseGlass** [comment]
Started working on it

**Comment by chrisarrow90** [comment]
Yeah or just make it randomly select between A and B for each engine.

**Comment by lousybyte** [comment]
Related #31
