### ISSUE TITLE
[BUG] Graphical glitch

### ISSUE THREAD

**Issue by Pross** [flybywiresim/a32nx#1274]
**Mod Version**
master

**Describe the bug**
Graphical glitch appeared today

https://www.youtube.com/watch?v=yHe86fFOXGA

**To Reproduce**

1. start flight
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?
was fine yesterday
Is this a problem in the vanilla unmodded game?
no

Discord username (if different from GitHub):

**Comment by lukecologne** [comment]
The video is private

**Comment by Pleasure0102** [comment]
Your video is set to private

**Comment by ChruutvoLuzi** [comment]
Private video

**Comment by Pross** [comment]
Try now sorry

**Comment by Benjozork** [comment]
What is the problem here ?

Do the controls not work ? Try resizing a window (like ATC, Weather) and / or switching cameras.

Please report whether that fixes it.

**Comment by ChruutvoLuzi** [comment]
No he probably refers to the flickering LS Decal

**Comment by Pleasure0102** [comment]
Yeah I will check it tomorrow might have happened with one of the decal fixes. It's 11pm so checking it tomorrow morning

**Comment by Pross** [comment]
Yea I'm referring to the flickering around the buttons text and toggles

**Comment by Pleasure0102** [comment]
Would be nice if someone can confirm. So we can make sure it's not a local issue

**Comment by lukecologne** [comment]
I got it as well

**Comment by Pleasure0102** [comment]
Okay should not be a big deal to fix (hopefully) so I am expecting to make a pr sometime tomorrow morning

**Comment by Benjozork** [comment]
> Mod Version
> master

Can you provide the contents of the ``build-info.txt` file so we know when this started ?

**Comment by Pross** [comment]
I dont see that file, I am on commit https://github.com/flybywiresim/a32nx/commit/2f93d9926e7dd56b59aa195e2377905b9716b038 if that helps?

**Comment by Benjozork** [comment]
Okay thank you. By the way, the file is located at the root of the package:

![image](https://user-images.githubusercontent.com/4503241/95793996-dc069e80-0cb4-11eb-9773-8930e57e62d6.png)

**Comment by Pross** [comment]
Oh well maybe its because I just run `git pull; build.py`

**Comment by Benjozork** [comment]
> 
> 
> Oh well maybe its because I just run `git pull; build.py`

Probably, yes.

**Comment by Pleasure0102** [comment]
So it turns out, it actually is in vanilla as well. I have checked if it has to do with the decal texture, and it does not. I am assuming it has to do with the decal mesh being to close to the glareshield panel mesh
https://streamable.com/rp967m

**Comment by Pleasure0102** [comment]
so the conclusion of my testing is that it is unfortunately something we cannot fix "yet" But it is something i will keep i mind once we can.

**Comment by Pleasure0102** [comment]
oh this means btw @Pross you did not actually test if it is a problem in vanilla. Please next time test before saying in vanilla it works.. it would have saved me half an hour of searching..

**Comment by Watsi01** [comment]
I have that too. I assume it's some of the graphic/scenery flickering through the cockpit. Have that when only on ground or slightly above clouds. Also you can enable "taxi ribbons" (assistance) and check out the main and center panel while driving over the ribbons. There's a lot of flickering going on.

**Comment by Pross** [comment]
To be honest I didn't think I needed to because the issue wasn't there the day before and the only thing I did was pull master and build and it included the updated graphics.
I'll know next time not to open a ticket and waste your valuable time.
> oh this means btw @Pross you did not actually test if it is a problem in vanilla. Please next time test before saying in vanilla it works.. it would have saved me half an hour of searching..

**Comment by Pleasure0102** [comment]
@Pross no it is okay to post an issue, but as i said, it is in vanilla, so you must have been mistaken, so if you find an issue, actually test vanilla first before you say it is not in vanilla pls

**Comment by MisterChocker** [comment]
This has been fixed by now.
