### ISSUE TITLE
[BUG] The plane sinks down with AP disconnected and A/THR set with an user input speed

### ISSUE THREAD

**Issue by marquinhosue** [flybywiresim/a32nx#1276]
**Mod Version**

Released 0.3.1 version 

**Describe the bug**

In the final approach, with the AP disconnected, the plane sinks down if any speed is set and the autothrottle is active.

**To Reproduce**

1. Load any landing challenge with the airbus, e.g.: Rio de Janeiro or Madeira.
2. Adjust the final desired speed, i.e.: 140 knots
3. Move the joystick down to start the final descent more than needed.
4.  Try to recover the horizontality by pulling up the stick

**Expected behavior**

The plane should get a positive ascending rate

**Actual behavior**

The plane continues to sink down and no altitude recovery is possible unless you disconnect the Autothrottle and increase power manually

**References**

**Additional context**

I am a rookie with the airbus, but I think there is likely a bug. Maybe I am ignoring some basic adjust with the plane. If so, I will appreciate your comments to avoid this frustating experience.
Was this working before/when did the issue start occurring?
I only installed the last released version, 0.3.1, thus I don't really know when the bug, if any, was introduced
Is this a problem in the vanilla unmodded game?
In the vanilla version of the aircraft the speed is kept at 140 knots (in Rio, no windy) and you can ascend or descend, and the A/THR will add or cut gas as needed

Discord username (if different from GitHub): Marquinhos

**Comment by Benjozork** [comment]
Does #1173 match what you are experiencing ?

**Comment by marquinhosue** [comment]
Hi,
No, nothing to do with right or left or 10 feet. It is just a lack of "auto" power, the plane does not answer to the stick pulling up request.
Rio is an example, but it happens to me everywhere. Moreover, the vanilla version seems to operate normally,  unlike the #1173 report.
Thanks for your time, and congrats for your nice job!

________________________________
De: Benjamin Dupont <notifications@github.com>
Enviado: lunes, 12 de octubre de 2020 23:57
Para: flybywiresim/a32nx <a32nx@noreply.github.com>
Cc: marquinhosue <marquinhosue@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [flybywiresim/a32nx] [BUG] The plane sinks down with AP disconnected and A/THR set with and user input speed (#1276)


Does #1173<https://github.com/flybywiresim/a32nx/issues/1173> match what you are experiencing ?

**Comment by joniatus** [comment]
This is a well-known issue with 0.3.1, you will need to update to dev version to fix

**Comment by marquinhosue** [comment]
Ok, thanks. Closing ticket
