### ISSUE TITLE
[REQUEST] Make the Pause Icon in the in-flight Toolbar use Real Pause instead of Active Pause

### ISSUE THREAD

**Issue by fourdragons** [flybywiresim/a32nx#1278]
**Is your feature request related to a problem? Please describe.**

Yes. Active Pause causes the plane to crash upon resuming, due to it continuing to use thrust during it's so-called "pause".

**Describe the feature you'd like to see implemented**

I'd would be nice if the Pause Icon (far left) in the in-flight Toolbar (at top of screen) used the Real Pause feature (located in controller/keyboard assignments under the "All" listing), instead of the Active Pause "feature". If not possible, perhaps an option to remove or disable the Active Pause icon from the toolbar.

**References**

Not applicable to real world (yet).

**Additional context**

None

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
This is unrelated to the mod, closing. Please raise those concerns with Asobo via Zendesk / the MSFS forums.

**Comment by fourdragons** [comment]
Like all the others? 🤔🤦‍♂️

**Comment by Benjozork** [comment]
> Like all the others? 🤔🤦‍♂️

I don't see why you wants a plane mod to change the game menus. That is not our goal or responsibility. The concern should be raised with Asobo or you should ask people to make a mod.

I hope you understand that this GitHub issue board is used for tracking issues and feature requests related to the mod itself, and therefore we close issues unrelated to the A320.

**Comment by hotshotp** [comment]
> Like all the others? 🤔🤦‍♂️

Bro are you good? We can't fix that stuff, it's a Microsoft issue not flybywire
