### ISSUE TITLE
[REQUEST] Increase volume of GPWS/Alt Callouts 

### ISSUE THREAD

**Issue by Lamao2244** [flybywiresim/a32nx#1282]
**Is your feature request related to a problem? Please describe.**

GPWS and Altitude Callouts seems to be slightly soft.

**Describe the feature you'd like to see implemented**

increase the GPWS and Alt Callouts slightly louder

**References**

https://www.youtube.com/watch?v=-mSSFCamk0I

**Additional context**

Nil

Discord username (if different from GitHub):LaMao

**Comment by Benjozork** [comment]
cc. @hotshotp

**Comment by lionomega** [comment]
Is anything known about this? the volume of the announcements is very low

**Comment by hotshotp** [comment]
> Is anything known about this? the volume of the announcements is very low

Low priority issue right now. Turn down every slider to 50 and then warnings to 100
