### ISSUE TITLE
[BUG] [MSFS 1.9.5] Flickering lights in the cockpit

### ISSUE THREAD

**Issue by Benjozork** [flybywiresim/a32nx#1286]
**Mod Version**

master @ 16f5d53

**Describe the bug**

https://cdn.discordapp.com/attachments/738864300818432023/765597295022309406/2020-10-13_17-29-48.mp4

**To Reproduce**
1. Load in a flight
2. Observer cockpit is flickering

**Was this working before/when did the issue start occurring?** After MSFS 1.9.5.

**Is this a problem in the vanilla unmodded game?** No.

Discord username (if different from GitHub): someperson#4953

**Comment by Carter633** [comment]
second this as a new issue from the latest patch 13/10/2020

**Comment by manud49** [comment]
Great Job it works after updating 
x:\MSFS2020\Community\plane-A32NX\SimObjects\AirPlanes\Asobo_A320_NEO\Systems.cfg
