### ISSUE TITLE
ZFW/ZFWCG double click (Invalid Format}[BUG]

### ISSUE THREAD

**Issue by snaylor111** [flybywiresim/a32nx#1288]
**Mod Version**

**Describe the bug**
Init page 2 ZFW/ZFWCG when click once it enters the automatic in scratchpad then click it once more its saying "Format error"

**To Reproduce**

1. init on MCDU
2. right arrow for init page 2
3. click once on right key 1 (ZFW/ZFWCG) shows up in scratch pad.
4. click right key again then getting the "FORMAT ERROR" error

**Expected behavior**
Noramlly once you click it once it give you the automated calculated ZFW, then tap again it should all the input values to go in

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring? yes, after downloading and installing the DEV mod after the MS2020 update

Is this a problem in the vanilla unmodded game? no

Discord username (if different from GitHub): EWA0111-Sean N

**Comment by lukecologne** [comment]
Duplicate #1265. Closing.
