### ISSUE TITLE
screens not working

### ISSUE THREAD

**Issue by leeandjess2** [flybywiresim/a32nx#1289]
**Mod Version**

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Please respect the issue template. Will reopen when required information is provided.
