### ISSUE TITLE
Power down bug

### ISSUE THREAD

**Issue by kyalmcconville** [flybywiresim/a32nx#129]
Was flying from NZQN to YSSY using the Dev branch and during descent the engines and Aircraft power went completely offline. Was unable to turn both Batteries back on nor activate the APU or Restart engines no matter what i did. Saved the flight thinking it would fix itself on reload and upon reloading the saved flight the sim crashes. Had about ~3000kgs of fuel left

**Comment by Curtis-VL** [comment]
Sorry, this issue will be closed as this could be a one-time bug in the default aircraft!

Please re-open the issue if you gather more info on what could cause this issue as well as steps to reproduce it. 👍
