### ISSUE TITLE
[BUG] ND shows wrong info after turning brightnes to 0, and up back again

### ISSUE THREAD

**Issue by kpa23** [flybywiresim/a32nx#1293]
**Mod Version**

built: 2020-10-13T17:02:32+00:00
ref: refs/heads/master
sha: 57309c9a135616c60781b78a91e1598c39510f53
actor: lukecologne
event_name: push

**Describe the bug**
ND shows wrong info after turning brightnes to 0, and up back again. Detailed in screenshot. Left display froze all(only magnetic navgator workes and rotates). 

**To Reproduce**

1. Fly
2. while on the route, turn brightness on ND to 0
3. Turn brightness up, display notify 40sec to adjust.
4. Display is up after 40 seconds, but shows old info about postion and don't update. I belive the info saved before 0 brightness was used.
5. Right ND  works properly, left ND not

**Expected behavior**

All ND displays should work properly.

**Actual behavior**

After turning brightness to 0, ND doesn't work as expected. Only magnetic 

**References**

![image](https://user-images.githubusercontent.com/1526383/95907386-1ef36f80-0da4-11eb-9864-1dd1170110f9.png)

**Additional context**

Was this working before/when did the issue start occurring?
  - not checked

Is this a problem in the vanilla unmodded game? 
  - not checked

Discord username (if different from GitHub): 
```kpa23 (nitrognom)#0862```

**Comment by 2hwk** [comment]
This should be fixed as the code around display updating has been refactored since this issue was posted.
