### ISSUE TITLE
After MS oct 13th update, aircraft is complete and utterly unstable.....

### ISSUE THREAD

**Issue by vlbreda** [flybywiresim/a32nx#1294]
**Mod Version**

Both 'stable' and developers version tried

**Describe the bug**

- AC doesn't follow flightplan
- Climbs beyond managed altutude
- Overspeeds under 10.000 ft (>250 kn, managed speed mode)
- Direct-to-function isn't working (returns to previous navpoints after reaching DT-point)
- and a lot more I fear......

**To Reproduce**

1. Download oct 13th update
2. Re-install mod (developer or stable)
3. Fly

**Expected behavior**

Hoped ac would still be functional after update

**Actual behavior**

ac is not stable after oct 13th update

**References**

**Additional context**

Was this working before/when did the issue start occurring?
After oct 13th update

Is this a problem in the vanilla unmodded game?
Don't know

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Those issues are all known problem with the autopilot that were happening before the update.

I have experienced 2 of those problems yesterday before the MSFS update for example.

Those cannot be fixed until we have our own autopilot implementation, stay tuned for that 🙃

**Comment by vlbreda** [comment]
Hi, thanks for your swift reply! I have flown the same flights as yesterday (oct. 12th). None of these problems then....

**Comment by Benjozork** [comment]
> Hi, thanks for your swift reply! I have flown the same flights as yesterday (oct. 12th). None of these problems then....
> 
> 

The problems are pretty random.

I didn't get any issues until yesterday, which was before the update.

Hold tight, we are working on a solution.

**Comment by vlbreda** [comment]
Yes, you are absolutely right. Retried the flight, no problems now. I can't emphasis enough how much your hard work is appreciated!! You take the simulator to a next level.
