### ISSUE TITLE
[BUG] ND WX radar display dimmed color after switching OFF & ON the display

### ISSUE THREAD

**Issue by ACSoft47** [flybywiresim/a32nx#1296]
**Mod Version**

built: 2020-10-13T17:02:32+00:00
ref: refs/heads/master
sha: 57309c9a135616c60781b78a91e1598c39510f53
actor: lukecologne
event_name: push

**Describe the bug**

I switched OFF the 2 copilot display (to test framerate impact) and when I switched ON again, WR radar colors were totally dimmed.

**To Reproduce**

1. Normal cruise flight with WX radar ON
2. Switch OFF (fully) both copilot display
3. Switch ON again both copilot display

**Expected behavior**

After the self-test display, when switching ON again, to retrieve the same WX radar colors as before.

**Actual behavior**

The WX radar had completely dimmed color.

**References**

![WXR-color-dimmed](https://user-images.githubusercontent.com/70327013/95911148-60365000-0da1-11eb-905c-53f47c92163a.jpg)

**Additional context**

Was this working before/when did the issue start occurring?
don't know

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):

**Comment by lukecologne** [comment]
Can you confirm that the WX radar brightness knob wasn't accidentally turned all the way down when you disable the display?

**Comment by ACSoft47** [comment]
Of course, I can confirm !
I turned the button to switch ON again, then I set it to middle range as I do usually, then seing these dimmed colors, I turn it full, then tried OFf again, then tried to switch OFF & ON again the WX radar, nothing worked to restore the normal colors.

**Comment by Watsi01** [comment]
What @lukecologne tries to ask: are you aware that there are now 2 brightness rotary controls at the inner brightness knob? One  manages the ND brightness overall, one manages the WX brightness _only_.

**Comment by lukecologne** [comment]
What I'm saying is that you did in fact change this setting, without knowing, because it's very close to the display brightness.

**Comment by ACSoft47** [comment]
Just checked all this now and it is exactly what's happen !

Not being aware that this was now a double button, I suppose the WX brightness knob was turned too. This was done inflight with some turbulences, so, not easy to turn these buttons.

Just checked now on the ground all the logic and it is ok.

**Comment by ACSoft47** [comment]
Obviously, this isn't a bug ! So I close this ynd sorry for the error !
