### ISSUE TITLE
[BUG] Altitude Constraints not refreshing on MFD

### ISSUE THREAD

**Issue by texpage1** [flybywiresim/a32nx#1297]
**Mod Version**

built: 2020-10-12T03:20:12+00:00
ref: refs/heads/master
sha: 471555844dc2181977cbc8cd2dd4479c8bfbf8eb
actor: wpine215
event_name: push

**Describe the bug**

When creating new altitude constraints on flight plan page, new constraint does not automatically appear on MFD. Pressing constraints button off then on seems to reset constraint

**To Reproduce**

1. change waypoint altitude constraint
2. View MFD - showing original constraint
3.

**Expected behavior**

Would expect new altitude constraint to appear on MFD by waypoint

**Actual behavior**

Old waypoint remained on MFD; by pressing the constraints button off then on corrected the issue

**References**

**Additional context**

Was this working before/when did the issue start occurring? New

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub): texpage

**Comment by MisterChocker** [comment]
Reproduced, I was unable to find a fix for this.

**Comment by 2hwk** [comment]
Fixed by #4953 closing ☑️
