### ISSUE TITLE
TCAS

### ISSUE THREAD

**Issue by Jannis-D** [flybywiresim/a32nx#130]
A TCAS functionality would be great for VATSIM!

**Comment by shaithan** [comment]
![TCAS NOT Avil in air](https://user-images.githubusercontent.com/22303602/92488651-21840780-f1ef-11ea-950c-bc932fafd94b.jpg)
![TCAS Avil on ground](https://user-images.githubusercontent.com/22303602/92488673-28127f00-f1ef-11ea-9fd0-01d95cee0d90.jpg)

**Comment by DerHero** [comment]
weird...

**Comment by TheoBearman** [comment]
@shaithan how do the switches need to be set to turn it on?

**Comment by shaithan** [comment]
![tcas setings](https://user-images.githubusercontent.com/22303602/92572233-71f97480-f284-11ea-9539-854b2b38e05a.jpg)
@TheoBearman

**Comment by TheoBearman** [comment]
Thanks!

**Comment by shaithan** [comment]
Any progress on reliable TCAS ?

**Comment by lukecologne** [comment]
Looking into it, for now only NPC aircraft though

**Comment by shaithan** [comment]
> Looking into it, for now only NPC aircraft though

ok, cuz I do have TCAS while I am on the ground but as soon as my wheels leve the tarmac, it goes away, it's so wierd

**Comment by ElSrJuez** [comment]
> Looking into it, for now only NPC aircraft though

@lukecologne why would it display only AI/NPC traffic, my understanding is that vPilot inserts VATSIM traffic as AI/NPC traffic?

**Comment by lukecologne** [comment]
It depends. There are currently two ways of getting traffic. One seems to only include the live traffic. The other one should get all traffic. If VATSIM inserts as normal traffic, then it should show up in the second way, but I can't guarantee that it works.
