### ISSUE TITLE
[BUG] Flight Deck Screens still illuminate the cockpit when the screens are off and aircraft power is on battery

### ISSUE THREAD

**Issue by efortier-95** [flybywiresim/a32nx#1300]
**Mod Version**

Dev version from the auto installer:
built: 2020-10-13T21:31:54+00:00
ref: refs/heads/master
sha: c67e814216940ec4cfe7619d641c1c5178bd3e42
actor: Benjozork
event_name: push

**Describe the bug**

When powering on the aircraft electrically, the flight deck screens (PFD/ND/ECAM) are all off because they don't receive power, fairly straightforward.
*However*, there's a hint of ambient light still coming from the screens, and turning the brightness knobs of the screens causes the respective areas of the cockpit to receive ambient light. So it's as if the cockpit is being illuminated by the screens...but the screens are off so there shouldn't be ANY light coming off of them.

**To Reproduce**

1. Start aircraft cold and dark (preferably at night)
2. Turn batteries on
3. Verify screens are still off
4. Turn brightness knobs for all screens up. Note that the rest of the cockpit illuminates.

**Expected behavior**

Screen is off, so there shouldn't be ambient light coming from the screens.

**Actual behavior**

Ambient light from the screen illuminates the cockpit.

**References**

Shown with battery on, external power avail but not on:
Right-Hand PFD brightness at min:
![image](https://user-images.githubusercontent.com/56796781/95922876-46394500-0d82-11eb-98a6-e0245a040e5f.png)
Right-Hand PFD brightness at max:
![image](https://user-images.githubusercontent.com/56796781/95922952-68cb5e00-0d82-11eb-8c19-41eb14389b1e.png)

**Additional context**

Was this working before/when did the issue start occurring?
Unsure

Is this a problem in the vanilla unmodded game?
Unsure

Discord username (if different from GitHub):
Eefoe#0570

**Comment by efortier-95** [comment]
Actually, an update: It's not dependent on aircraft battery power being available. The issue is present even when the aircraft is cold and dark.

Cold and dark spawn:
![image](https://user-images.githubusercontent.com/56796781/96322310-90bafb80-0fe6-11eb-8af3-48428ddc8fa2.png)

Then when I manually go in and turn all screens off by turning the knobs accordingly:
![image](https://user-images.githubusercontent.com/56796781/96322382-d081e300-0fe6-11eb-8cba-4e0e1c89df43.png)

All this happened without applying any kind of power to the aircraft.

**Comment by bouveng** [comment]
Cant reproduce this issue anymore.
