### ISSUE TITLE
[BUG] Can't engage both autpilots on approach.

### ISSUE THREAD

**Issue by oldmanbishop** [flybywiresim/a32nx#1302]
**Mod Version**

built: 2020-10-13T17:02:32+00:00
ref: refs/heads/master
sha: 57309c9a135616c60781b78a91e1598c39510f53
actor: lukecologne
event_name: push

**Describe the bug**

You should be able to engage both autopilots on descent once established on the LOC/GS (or when armed). This used to work, but doesn't now. 

**To Reproduce**

1. Establish an approach on an ILS (any category)
  -- I was landing on KLAX 25L as my testing attempt, for reference. Have seen this on others as well.
2. Press the AP2 button

**Expected behavior**

AP2 engages while AP1 stays active

**Actual behavior**

AP2 engages and AP1 disengages. Tried this at all stages (armed, established). 

**References**

**Additional context**

Not sure if this is affecting autoland (which forgets to flare and bounces even on Cat-3).

Was this working before/when did the issue start occurring?
This works in 0.3.1
Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):
oldmanbishop#1107

**Comment by aviationenthusiast** [comment]
i confirm

**Comment by lukecologne** [comment]
Duplicate #1223. Please search the previous issue before opening a new one.

**Comment by oldmanbishop** [comment]
Apologies, I saw the previous issues and somehow thought they were closed.
