### ISSUE TITLE
[BUG] Cruise ECAM page doesn't display 

### ISSUE THREAD

**Issue by oldmanbishop** [flybywiresim/a32nx#1303]
**Mod Version**

built: 2020-10-13T17:02:32+00:00
ref: refs/heads/master
sha: 57309c9a135616c60781b78a91e1598c39510f53
actor: lukecologne
event_name: push

**Describe the bug**

At cruise or climb there should be a Cruise ECAM page when no other page explicitly selected.  I've seen it before, but it's not there in current development.

**To Reproduce**

1. Takeoff, climb, and reach defined cruise altitude.
2. Deselect any ECAM pages. 

**Expected behavior**

The autoselected page should be cruise.

**Actual behavior**

ENG page is shown for the duration of the flight.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Works in 0.3.1 

Is this a problem in the vanilla unmodded game?
N/A

Discord username (if different from GitHub):
oldmanbishop#1107

**Comment by lukecologne** [comment]
Did you have the engine mode selector in NORM or IGN/START during the flight? I ask because the engine ecam page will be displayed as long as the engine mode selector is not in NORM.

**Comment by oldmanbishop** [comment]
Retested departing from the runway. If the mode selector is in NORM before/during takeoff, it works as expected and the cruise page appears. If you don't select NORM until after takeoff (or cycle to IGN and then NORM), Cruise never shows up.

**Comment by oldmanbishop** [comment]
Appears I wasn't patient enough.  There's a delay on switching before the auto page appears.  Going to assume I had the switch in IGN for all my flights today.
