### ISSUE TITLE
MCDU Displaying a black page with "UNTITLED" when adding SID to the flight plan

### ISSUE THREAD

**Issue by yusufsan38** [flybywiresim/a32nx#1304]
**Mod Version**
Latest master as of 10/13/2020 07:30 pm

**Describe the bug**
When entering the flight plan from scratch in the MCDU everything goes fine until it's time to select the SID. then MCDU displays a page with "UNTITLED" at the top and gets stuck at that page. Also happens when flight plan loaded via World Map but this time you can navigate to the other pages and the flight plan is displayed on the ND.

**To Reproduce**
1. Enter waypoints EDDF - EKCH (MARUN Y150 UVANO Y150 NATSU Y150 TOLGI DCT ROSOK Q296 NIKDA Q296 MONAK)
2. Select departure RW25L, MARU2K departure, hit "TPY Insert"
3. MCDU goes to a black page with "UNTITLED" displayed at the top. Can't navigate to any other page

**Expected behavior**
MCDU accepts the SID and adds associated waypoints

**Actual behavior**
MCDU goes to a black page with "UNTITLED" displayed at the top.

**References**
See attachment

**Additional context**
NA

Was this working before/when did the issue start occurring?
Yes
Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub): The Sim Pilot
![Capture](https://user-images.githubusercontent.com/45862788/95928766-44767e00-0d90-11eb-9973-eee813f8d2ad.PNG)

**Comment by NathanInnes** [comment]
Please add a title

**Comment by yusufsan38** [comment]
> Please add a title

Sorry, just corrected. thanks for the catch

**Comment by Benjozork** [comment]
You didn't add one yet

**Comment by yusufsan38** [comment]
> You didn't add one yet

Forgot to click the save button, should be good now

**Comment by lousybyte** [comment]
EEDF is not a valid entry.

**Comment by yusufsan38** [comment]
> EEDF is not a valid entry, I assume was EDDF. Can't replicate, worked just fine on latest master.
> 
> ![](https://camo.githubusercontent.com/2c97632482f69020192dbefca6475552bff0712f/68747470733a2f2f692e706f7374696d672e63632f7064445634394c372f53637265656e73686f742d323032302d31302d31342d3233343132322e706e67)

It was meant to be EDDF small typo error there

**Comment by DraivPro** [comment]
When you press the F-PLAN button on the latest version of the wizard at this time.

The flight plan was pre-loaded into the EDDF-LOWW menu

I get an error when loading the plane UNTITLED
![Снимок экрана 2020-10-16 005343](https://user-images.githubusercontent.com/71631760/96189932-1046bd00-0f4a-11eb-9b7c-20379167a621.jpg)

**Comment by DraivPro** [comment]
I tried to score the entire route manually. got "untitled" error after typing approach masuw2 on RWY 34 at LOWW arrival airport

**Comment by lousybyte** [comment]
Loaded that plan just fine on the latest master, with and without navigraph, not sure why you are having issues. 
Is your game on the 1.9.5 version?

**Comment by DraivPro** [comment]
Oh sure. Licensed version. From the mods installed navigraph 2011 rev5 and a32nx. I'll check it again tonight more closely.

**Comment by DraivPro** [comment]
I checked everything more carefully. I only got the error if I used navigraph airac 2011 rev5. I requested airac update and rev6 was downloaded to me. It was not possible to repeat the error with the new version. Its OK now. Thanks.

**Comment by Benjozork** [comment]
Issue is related to outdated Navigraph data, closing.

**Comment by lab44Hub** [comment]
just because airac is outdated, should this break the mod? 

Navigraph is a subscription service which can be cancelled at any time. Is the mod going to be tied always to having a Navigraph subscription?

**Comment by Lessar277** [comment]
@lab44Hub It's most likely to do with the fact that he had a buggy version of the AIRAC cycle (revision 5). Navigraph has its own bugs, the navdata implementation is currently in beta. The mod works fine without Navigraph and it is not required.

**Comment by Alisayedaa** [comment]
is there any solution to the above issue still I am facing the issue with sim brief arrival destination ?? UNTITLED
