### ISSUE TITLE
[BUG] Graphical (lighting) glitch in the center stack area

### ISSUE THREAD

**Issue by spiff72** [flybywiresim/a32nx#1306]
**Mod Version**

0.3.1

**Describe the bug**

I am getting a strange flickering lighting effect in the center stack area (the area where the throttles are).  Video in references section shows it.

It only affects the center area, and to a lesser extent the area around it (like it is a flickering light source).

**To Reproduce**

1.  Just Fly.
2.
3.

**Expected behavior**

I wouldn't expect to see this flickering

**Actual behavior**

The panel flickers.

**References**

https://youtu.be/TGVw3JGhWJw

**Additional context**

Hardware:
Core i7-9700 and RTX 2060

Was this working before/when did the issue start occurring?
The sim just updated (patched today).  I didn't see this issue until AFTER this patch update, but I only flew two night flights with this mod installed previously.  This is a daytime flight where i see the issue now.

Is this a problem in the vanilla unmodded game?
Not sure.  

Discord username (if different from GitHub):  spiff72 (same as github)

**Comment by lukecologne** [comment]
See #1305. Fixed in master. Please look through previous issues before opening one.

**Comment by spiff72** [comment]
Sorry - I tried searching but didn't find it (searched for "flickering").

**Comment by spiff72** [comment]
Wow - I guess i didn't find it because it was posted just before I posted my own.

**Comment by lukecologne** [comment]
For the future: Likely you didn't look at closed issues, you need to explicitly click a button to see them: 
![grafik](https://user-images.githubusercontent.com/39596827/95931911-b10e6e80-0dca-11eb-8be1-e969def25e67.png)

**Comment by spiff72** [comment]
Got it - you are correct - I guess I didn't expect it to have been closed so quickly! :-)
