### ISSUE TITLE
[BUG] CSTR freezes ND when turned on

### ISSUE THREAD

**Issue by yusufsan38** [flybywiresim/a32nx#1309]
**Mod Version**
Latest master as of 11/13/2020 08:00 pm

When turned on CSTR freezes the ND

**To Reproduce**

1. Take off from any airport
2. While cruising turn on CSTR @ EFIS panel
3. ND freezes

**Expected behavior**
ND displays the WP constraints

**Actual behavior**
ND freezes and does not update

**References**
See the attached video in the zip

**Additional context**
Was this working before/when did the issue start occurring?
Yes
Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub): The Sim Pilot
[cstr_bug.zip](https://github.com/flybywiresim/a32nx/files/5375286/cstr_bug.zip)

**Comment by Venorcis** [comment]
Can confirm, selecting CSTR can freeze the whole ND.

**Comment by Benjozork** [comment]
Does this only happen in ARC mode ?

**Comment by lousybyte** [comment]
Cannot replicate and no reply.
