### ISSUE TITLE
When I have the new master file I cannot edit any buttons.[BUG]

### ISSUE THREAD

**Issue by AB324** [flybywiresim/a32nx#1313]
**Mod Version**

**Describe the bug**

**To Reproduce**

1.When I have the new master file I cannot edit any buttons.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by webermaximilian92** [comment]
What do you mean with "edit". 
Edit inside device keybindings?
click buttons inside the A320?

If you can't press buttons, there are a lot of workarounds allready and it is a MSFS issue. 

For me turning off the "Ground Aircraft Density" inside traffic settings fixed it completly.

**Comment by AB324** [comment]
Ich kann die Schalter wie irs und anschnal zeichen nicht bewegen die sind immer an egal ob Cold an dark oder wen ich auf der start Bahn das Spiel lade.

**Comment by webermaximilian92** [comment]
> ging mir genau so - 

Das ist eher ein Anzeichen dafür, dass der aktuelle master Stand des A32NX Mods für einige nicht kompatibel mit der neuen Hotfix Version vom 13.10.2020 des Flightsim ist. 

Da heißt es erst mal ca. 2 Tage abwarten und den nächsten master ziehen

**Comment by webermaximilian92** [comment]
###
for some reason the current master doesn't work for new hotfix patch from 13.10. yet. 
You can install it, it will be shown at content manager, but inside sim a32nx features wont work at all.

bug ticket might be closed

**Comment by lukecologne** [comment]
How did you download master? Did you download vmaster, or did you download via the installer, or pulled directly via git? (Not gonna speak german so that other people can read it too)

**Comment by AB324** [comment]
I downloaded it from her and via the download software from flybywire

**Comment by webermaximilian92** [comment]
Try to load the stable verion

![image](https://user-images.githubusercontent.com/46194969/95996549-15fdaf00-0e33-11eb-9879-0cd9662137ac.png)

this fixed it for me. Can you try this


> Verwende bitte mal die stabilen Version

**Comment by AB324** [comment]
Habe Bodenflugzeugdichte auf null jetzt gehts, danke

**Comment by MisterChocker** [comment]
Still relevant?

**Comment by Benjozork** [comment]
This does not respect the template and is too old to be investigated.
