### ISSUE TITLE
[BUG] Cabin heat knobs turn too slow when scrolling

### ISSUE THREAD

**Issue by PuL9** [flybywiresim/a32nx#1314]
**Mod Version**

master version

**Describe the bug**

Thing to adjust the cabin heat has a lot of steps/levels, it takes long time to set them to center, it wasn't like that before.
I don't know if that is realistic, but because we have to spend time on that, having less steps would be better.

**To Reproduce**

As stated before, to reproduce it you have to adjust cabin heat, it has a lot of steps

**Expected behavior**

I expect it to have around 10-15 steps to get it to maximum heat level.

**Actual behavior**

It feels like it has 100+ steps to get them to max level

**References**

https://i.imgur.com/bzwtNhi.png

**Additional context**

Was this working before/when did the issue start occurring?
Around a week or two ago it got changed

Is this a problem in the vanilla unmodded game?
Vanilla doesnt have these implemented as far as I know.

Discord username is the same as here.

**Comment by SeanHanway** [comment]
Previously it had around six steps and someone opened a ticket requesting it be a bit more precise so that's how we ended up here but I agree at the minute it's a bit of a drag to turn the heat up and down with such a huge number of steps.

**Comment by ChruutvoLuzi** [comment]
It was made like that intentionally since the irl counterpart is working the same, altough it really takes a bit too log atm. Something that would improve the experience is if it would start in the middle but i think they are working on that together with the packs

**Comment by Benjozork** [comment]
I am the one who implemented this functionality. I was thinking of making the turning dramatically faster when using the scroll wheel and making the normal speed a bit faster - wdyt ?

**Comment by SeanHanway** [comment]
> I am the one who implemented this functionality. I was thinking of making the turning dramatically faster when using the scroll wheel and making the normal speed a bit faster - wdyt ?

I like the idea of making the turning dramatically faster with the scroll wheel, that's all we need really.

**Comment by hotshotp** [comment]
> I am the one who implemented this functionality. I was thinking of making the turning dramatically faster when using the scroll wheel and making the normal speed a bit faster - wdyt ?

Yeah this sounds great!

**Comment by Benjozork** [comment]
Can you test this ?

https://github.com/flybywiresim/a32nx/pull/1346

**Comment by SeanHanway** [comment]
> Can you test this ? Use the instructions at the bottom
> 
> #1346

Just tested. Much prefer the faster scrolling and everything looks to be working as expected 👍
