### ISSUE TITLE
[REQUEST] New speeds for managed CLB, CRZ and DES (MDCU)

### ISSUE THREAD

**Issue by Watsi01** [flybywiresim/a32nx#1315]
**Is your feature request related to a problem? Please describe.**
Messed up managed speeds in MCDU. See here:
Issue "[BUG] Managed speeds are a kind of a mess" [https://github.com/flybywiresim/a32nx/issues/1080](https://github.com/flybywiresim/a32nx/issues/1080)

**Describe the feature you'd like to see implemented**
Since I'm actually to stupid to file a proper pull request, I do it this way. I tried to make the three flight phases a bit smoother regarding the according managed speeds and the transition between the phases. Maybe someone of you PR pro's can add the change at some time. So I only changed the managed speeds for the flight phases (CLB, CRZ and DES). Didn't touch any flap speeds, speed restrictions or else. 

Inside A32NX folder:
1. go to "...\html_ui\Pages\VCockpit\Instruments\Airliners\A320_Neo\FMC"
2. open the "A32NX_FMCMainDisplay.js" and change

 _getCrzManagedSpeed() {
        let dCI = this.costIndex / 999;
        dCI = dCI * dCI;
        const flapsHandleIndex = SimVar.GetSimVarValue("FLAPS HANDLE INDEX", "Number");
        if (flapsHandleIndex != 0) {
            return this.getFlapSpeed();
        }
        let speed = **290** * (1 - dCI) + 310 * dCI;
        if (SimVar.GetSimVarValue("PLANE ALTITUDE", "feets") < 10000) {
            speed = Math.min(speed, 250);
        }
        return speed;
    }
    getDesManagedSpeed() {
        const dCI = this.costIndex / 999;
        const flapsHandleIndex = Simplane.getFlapsHandleIndex();
        if (flapsHandleIndex != 0) {
            return this.getFlapSpeed();
        }
        let speed = **288** * (1 - dCI) + 260 * dCI;
        if (SimVar.GetSimVarValue("PLANE ALTITUDE", "feets") < 10000) {
            speed = Math.min(speed, 250);
        }_

This makes the cruise a tiny bit faster (according to the cost index) and the managed descent speed is not ~240kts from top down anymore, but around 285-290kts (speed limit below 10.000 still kept). I didn't touch the CLB speed here, cause - for some reason - it doesn't do anything (even if there are numbers for CLB around this section).

3. for CLB speeds you have to go to:
   "...\html_ui\Pages\VCockpit\Instruments\Airliners\A320_Neo\CDU"

4. open the "A320_Neo_CDU_MainDisplay.js" and change the following

_let dCI = this.costIndex / 999;
        dCI = dCI * dCI;
        let speed = **290** * (1 - dCI) + 330 * dCI;
        if (SimVar.GetSimVarValue("PLANE ALTITUDE", "feets") < 10000) {
            speed = Math.min(speed, 250);
        }_

This reduces the climb speed from ~320 to ~290kts. I'm not sure about this number. I did it that way, because the Asobo AP seems to handle mach speeds incorrectly. Even if the speed bug is switched to mach, the AP seems to still hold KIAS. So the 290kts here are mainly to smooth the transition between CLB and CRZ. Suggestions of other / more realistic values are appreciated for the future (when AP is working correctly).

**References*

**Additional context**
If someone would test these changes and/or make a PR out of it, I would be thankful. 

Discord username: RogePete

**Comment by nobodyn0se** [comment]
This is cool, will try a few flights with these changed values.

**Comment by Watsi01** [comment]
> 
> 
> This is cool, will try a few flights with these changed values.

Thanks.

**Comment by nobodyn0se** [comment]
Tried a 384 NM flight with these settings. Much better now. I reached the DECEL point at FL110 so it slowed down from 290IAS to green dot speed. Will try another one to see if it maintains 250kts till DECEL.

**Comment by Watsi01** [comment]
Sounds good so far. Thanks for your testing work.

**Comment by MisterChocker** [comment]
isnt this merged already?

**Comment by Watsi01** [comment]
Yeah, I close it.
