### ISSUE TITLE
[BUG] ZFW/ZFWCG Data Entry Format

### ISSUE THREAD

**Issue by donstim** [flybywiresim/a32nx#1316]
**Mod Version**
master (latest downloaded version)
built: 2020-10-14T04:45:18+00:00
ref: refs/heads/master
sha: 5ac2b03ea8132e7f549c3210e33437feef91f453
actor: Benjozork
event_name: push

**Describe the bug**
The ZFW entry allows entries that should be out of bounds. According to Appendix B of the Honeywell Pegasus Pilot Guide, the acceptable range of entries is 35.0-80.0 Metric Tonnes (or 77.1-176.0 !000s of pounds). I was able to enter "2" and also "900000."  For out-of bounds entries, there should be a "FORMAT ERROR" message in the scratchpad (see Appendix C of the Honeywell Pilot Guide).

Similarly, there should be some bounds on the ZFWCG entry of 8.0 to 50.0. I was unable to check this because once I put an entry in (and it was within the allowable range), it would not allow me to change that entry. This is also incorrect behavior. According to the Honeywell Pilots Guide (page 4-23), after initial entry, the ZFW and ZFWCG values cannot be cleared, but they can be modified either separately or together.

**To Reproduce**

1. Start Cold and Dark
2. Establish electrical power
3. Go to INIT B page of MCDU. Enter ZFW/ZFWCG using numbers that should be out of range. 
4. Once ZFW and ZFWCG entries have been accepted, try to change just the ZFWCG value.

**Expected behavior**
As stated above, numbers outside the allowable range should not be accepted and a FORMAT ERROR message should be displayed on the scratchpad.

For ZFWCG, modification of the value should be permitted.

**Actual behavior**
An out of range value for ZFW was accepted. I was unable to test out of range values for ZFWCG. Modification of the ZFWCG was not taken and should have been.

**References**

**Additional context**

Was this working before/when did the issue start occurring?Just happened to check it with this version when I was verifying that entries could even be made after Discord messages that 2 people were unable to enter ZFW/ZFWCG at all. 
![Screenshot (32)](https://user-images.githubusercontent.com/70166617/95959013-c8436100-0db6-11eb-9883-cc3a091aabb1.png)
![Screenshot (33)](https://user-images.githubusercontent.com/70166617/95959034-d0030580-0db6-11eb-9f4d-ac2eb3328899.png)
![Screenshot (31)](https://user-images.githubusercontent.com/70166617/95959049-d5f8e680-0db6-11eb-8317-5c64b503b9d2.png)

Is this a problem in the vanilla unmodded game?I don't know, but since the ZFW and ZFWCG entry process has been modified by the mod, I assume this issue is also fixable within the mod.

Discord username (if different from GitHub):donbikes#4084

**Comment by Lucky38i** [comment]
I'll fix this however since it's not urgent(unless otherwise) it'll pushed along with my FUEL computation PR
