### ISSUE TITLE
[BUG] [CDSS] Video button has to be one-click

### ISSUE THREAD

**Issue by St54Kevin** [flybywiresim/a32nx#1318]
**Mod Version**

0.3.1 current **master** as of 14th Okt 20

**Describe the bug**

When clicking the CDSS Video button you have to hold it to have the video be displayed on the lower ECAM.

**To Reproduce**

1. Hold the button
2. Video shows
3. Release the button

**Expected behavior**

The Video button should be a one-click button. Click it once to show the camera, click it again to show camera 2 and then 3. THEN on the last click it disappears.

**Actual behavior**

Its a click and hold button

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Hello,

This behaviour was not implemented because we do not have the necessary knobs in the 3D model to attach the video on / off functionality to.

Will be fixed when we can get model edits back into the sim.
