### ISSUE TITLE
[BUG] Format error on MCDU ZWF/ZWFCG

### ISSUE THREAD

**Issue by ABoldOne** [flybywiresim/a32nx#1320]
**Mod Version**
current master (updated 14th October)

**Describe the bug**
When putting in zwf and zwfcg in the mcdu init page (like 50.2/21.6) i will get a format error.

**To Reproduce**
1. start cold and dark
2. establish power
3. try to enter valid data into MCDU init ZWF/ZWFCG

**Expected behavior**
it should use the data i put in

**Actual behavior**
it actually didn't

**References**

**Additional context**

Was this working before/when did the issue start occurring?
it started with the latest master build

**Comment by OddSobriquet** [comment]
I think it's an issue connected to font change:
"The new custom font uses a different character to represent slashes" #1273
I also couldn't enter a "-" at the crz level/temp on init page which may also be connected to this.

**Comment by DraivPro** [comment]
I also can't enter a value, I always get format error

**Comment by lousybyte** [comment]
Related #1316

**Comment by snaylor111** [comment]
this is now fixed

**Comment by lve0200** [comment]
Wonderful! and how/where to get the corrected release?

**Comment by ABoldOne** [comment]
> 
> 
> Wonderful! and how/where to get the corrected release?

when its merged with the master build

**Comment by Rudss** [comment]
Hi, i also can't enter a value, I always get format error, im trying diferent values but simply i cant.

**Comment by ABoldOne** [comment]
> 
> 
> Hi, i also can't enter a value, I always get format error, im trying diferent values but simply i cant. I have the latest act.

It is fixed and will probably be merged with the master build soon.

**Comment by ABoldOne** [comment]
Fix is in the latest master build.

**Comment by AdmiralArtemiy** [comment]
Still catch on the latest master.
