### ISSUE TITLE
[BUG] [SOUND] EXT PWR relay sound doesnt play on destination

### ISSUE THREAD

**Issue by St54Kevin** [flybywiresim/a32nx#1321]
**Mod Version**

0.3.1 **master** as of 13th Okt 20

**Describe the bug**

EXT PWR relay sound doesnt play on destination

**To Reproduce**

1. Arrive at destination
2. request EXT PWR
3. Click the button

**Expected behavior**

relay sound should play

**Actual behavior**

no relay sound

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by St54Kevin** [comment]
Looks like EXT PWR doesnt take over when engine have some N1 indication left. Boris mentioned it. So its also coupled to an ELEC bug.

**Comment by hotshotp** [comment]
This is a game issue when you have to wait until the engine generators actually stop producing power because they produce power even when shutting down. if the engine is at 1 RPM it will still provide power, so you either have to turn off the engine gens or wait a while before turning it on.
