### ISSUE TITLE
[BUG] Mod doesn't work anymore after clean install in 1.9.5.0 for me

### ISSUE THREAD

**Issue by webermaximilian92** [flybywiresim/a32nx#1323]
**Mod Version**

After commit 5ac2b03

**Describe the bug**

can not setup flight with mod 

**To Reproduce**

1. Clean reinstall MSFS 1.9.5.0
2. Install newest Airbus 0.1.58 from ingame content-manager and install every other package
3. insert A32NX Master from github "code" zip button inside Community MSFS folder
4. check if A32NX is inside ingame content-manager
5. load a flight with A320 anywhere you want. 

**Expected behavior**

features of mod are available

**Actual behavior**

no features are available / mod is not correctly included

**References**

![image](https://user-images.githubusercontent.com/46194969/95991936-aafda980-0e2d-11eb-883a-05157c0a0218.png)
later i tried other MODS / Liveries. those worked

**Additional context**

Game is installed via MS Store WITHOUT xbox app or Steam
Patch 1.9.5.0 was installed after clean install
Content Manager Packages were installed after that
then I moved A32NX inside Community folder

Was this working before/when did the issue start occurring?
It worked for me before clean install

Is this a problem in the vanilla unmodded game?
YES, at least for ME

Discord username (if different from GitHub): Performer - Max#8957

**Comment by webermaximilian92** [comment]
I fixed it by using the downloader.exe https://github.com/Externoak/A32NX-installer/releases/latest/download/A32NX_Downloader.zip and choosing stable verion
![image](https://user-images.githubusercontent.com/46194969/95996379-e3ec4d00-0e32-11eb-8361-d5de8bccec6f.png)

**Comment by Mariolink123** [comment]
Yeah, the code method doesn't work anymore so you have to either use the installer or this link for the latest master: https://github.com/flybywiresim/a32nx/releases/tag/vmaster 
P.S The stable version is kind of buggy at the moment (ironically!) so if you're having problems ingame with it, feel free to use the dev version on the installer instead.

**Comment by webermaximilian92** [comment]
I installed the dev version now with the installer and everthing is fine..

sorry.. but the "https://github.com/flybywiresim/a32nx/releases/tag/vmaster" is the "stable" version too? 

so the only way to get the dev version is the installer now?

**Comment by Mariolink123** [comment]
The VMaster link is updated with the latest changes, so it's also the dev version. You can either use the installer to get the dev version, or that link. Just don't use the code method and you'll be fine!

**Comment by smukherj1** [comment]
I ran into this as well and figured the issue is the source tree no longer includes the manifest and layout JSON files. So obviously, the easiest path here is to use the installer. An alternative is to manually run the [build.py](https://github.com/flybywiresim/a32nx/blob/master/A32NX/build.py) script (requires Python 3 to be installed) to generate the JSON files
