### ISSUE TITLE
[BUG] DCDU Labels are Missing/Off when brightness knob is turned to 0

### ISSUE THREAD

**Issue by 2hwk** [flybywiresim/a32nx#1324]
**Mod Version**

master

**Describe the bug**

DCDU buttons appear to be missing text.

**To Reproduce**

1. Load in to the A320
2. Turn integ lt knob to 0
3. The emissive textures on the buttons now appear to be missing.

![image](https://cdn.discordapp.com/attachments/753381993802235944/765831375458402304/unknown.png)

**Expected behavior**

Labels should not disappear when brightness is turned down

**Actual behavior**

Labels disappear

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub): 2Cas#1022

**Comment by lukecologne** [comment]
Working at this at the moment, fix is on the way
