### ISSUE TITLE
[BUG] CRZ level and negative temp and wind - MCDU

### ISSUE THREAD

**Issue by Watsi01** [flybywiresim/a32nx#1326]
**Mod Version**

Current master

**Describe the bug**
Right now it isn't possible to insert negative temps in the  CRZ FL / TEMP field (MCDU INIT page). Because behind the / (or any other entry) the minus won't work

**To Reproduce**

1. Enter cold&dark
2. get power on (APU or EXT)
3. go to the INIT page in MCDU
4. try to insert e.g. 320/-38 in the CRZ FL/ TMP field

**Expected behavior**
input of negative temps for higher alt

**Actual behavior**
see above

**Additional context**
EDIT: maybe the same problem: try to enter positiv winds in the INIT page 2 for "trip wind" (no minus in front of number). It's not working. Negative winds work here (??).

Was this working before/when did the issue start occurring?
Yesterday it worked. Seems to be a new one.

**Comment by lousybyte** [comment]
Might be related to #1243.

**Comment by Rameyuk** [comment]
I can replicate this bug: I also can't type using the +/- button to enter 380/-55.

My current workaround is to just type in 38000 and enter it into the CRZ FL/TEMP. And it'll auto-populate with the appropriate cruising flight level and the temperature with the negative sign included.
