### ISSUE TITLE
Cocpit lighting flicker [BUG]

### ISSUE THREAD

**Issue by mark1606** [flybywiresim/a32nx#1330]
**Mod Version**
Realese Ver. V0.3.1  

**Describe the bug**
Flickering of cocpit lighting

See Video: 

https://www.youtube.com/watch?v=Bc4-VzmIaXA

Was working before 13th of October Update 

No problem in vanilla

**Comment by hotshotp** [comment]
This has been solved in the latest master version. This is a duplicate if many other issues. I recommend you close this issue as it has been fixed

**Comment by mark1606** [comment]
Roger that! Thank you!
