### ISSUE TITLE
[REQUEST] Skip IRS alignment time

### ISSUE THREAD

**Issue by Tawmu** [flybywiresim/a32nx#1331]
It would be nice if there were a feature or setting somewhere to skip the 7 minute IRS alignment time when starting the plane from cold and dark.

Discord username (if different from GitHub): Tawmu#9445

**Comment by hotshotp** [comment]
Iceman posted a teaser showing that the option will be there. I recommend you close the issue as the team is working on it already

**Comment by Tawmu** [comment]
Aha didn't realise. Thanks!

**Comment by Benjozork** [comment]
@hotshotp Issues should not be closed until it is implemented or fixed.

**Comment by Benjozork** [comment]
Just realized this is a duplicate though #398.
