### ISSUE TITLE
Chrono on ND resets to 00'00" after a while

### ISSUE THREAD

**Issue by UNSCJohn-117** [flybywiresim/a32nx#1333]
Using the Chrono just above the "Side Stick Priority" button will start normally when I click it upon entering the runway and takeoff, but after a while I notice that it has reset and stopped.

Steps to reproduce: 
1. Start Chrono when entering runway
2. Take off
3. Wait
4. Should stop somewhere between climbing and cruise

I have not tested the Chrono below the Auto-brake section.

**Comment by UNSCJohn-117** [comment]
Also appears to start again when exiting cruise

**Comment by UNSCJohn-117** [comment]
Well, I don't know what happened but in my latest flight it worked as intended. I have no idea if my previous flight (which was from PAJN to PAFA, while my latest was KDFW to KLAX) had anything to do with it not behaving or it was fixed in the latest dev branch update (from ~6PM CDT).

**Comment by 2hwk** [comment]
Have been unable to reproduce, will keep an eye out.

**Comment by UNSCJohn-117** [comment]
Yeah, may have been fixed a while back. Closing for now,
