### ISSUE TITLE
[BUG] Landing with Flaps 3 should not trigger "too low, flaps" warning

### ISSUE THREAD

**Issue by imkow** [flybywiresim/a32nx#1335]
**Mod Version**

latest master branch

**Describe the bug**

landing with flaps 3 is allowed, should not trigger "too low, flaps" warning

**To Reproduce**

1. during approach, set flaps to 3, and landing ( tested at CYPR)
2.
3.

**Expected behavior**

no warning

**Actual behavior**

triggers warning if not set flaps to FULL

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by hotshotp** [comment]
We haven't implemented the flaps 3 config yet even though we have the button working, so coming soon

**Comment by CJ1045** [comment]
I have always landed with Flaps 3 using the mod which I have used since first release and this warning has only just started happening with the latest stable release and the dev version for a couple of days prior to that.
