### ISSUE TITLE
[BUG] klax/ksfo not in database 

### ISSUE THREAD

**Issue by pilldoc** [flybywiresim/a32nx#1338]
**Mod Version**
 master

**Describe the bug**

Any entry into init page with ksfo brings up not in database 

**To Reproduce**

1. Enter klax/ksfo into init page
2.
3.

**Expected behavior**

Should not show not in database 

**Actual behavior**

Shows not in database 

**References**

**Additional context**

Was this working before/when did the issue start occurring? Yes

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Mariolink123** [comment]
I just flew from KLAX to KSFO today, when you get the "NOT IN DATABASE" message, just CLR and re-enter it, works for me 100% of the time.

**Comment by pilldoc** [comment]
I’ve tried that no luck

**Comment by lousybyte** [comment]
Can't confirm, worked fine for me.

![](https://i.postimg.cc/Qth7yZhQ/Screenshot-2020-10-14-235508.png)

**Comment by pilldoc** [comment]
I’m having this issue on newest msfs update even without the mod on a320

**Comment by resir014** [comment]
Related: #758

I came across this issue in the past and I fixed it by doing a complete reinstall of MSFS (including deleting the packages folder + deleting the `%AppData%\Microsoft Flight Simulator` folder)

**Comment by archer884** [comment]
I have this same issue regardless of where I try to go. I usually fly GPS routes but then select an ILS approach in flight, but that's impossible because the database has never heard of any airport in the known universe now. I do not have the FPS fix installed, and it has never been installed.

**Comment by archer884** [comment]
@lousybyte as I reported in my comment above, I do NOT experience this bug in Vanilla.

**Comment by lousybyte** [comment]
Someone mentioned above it can happen on base game as well.

**Comment by chitol** [comment]
Tried it on 787.  Same issue.  During 1.9.5 patch, they updated KSFO.  I think it screwed up the KSFO airport data.  It is not a NX specific issue.  It is a MSFS specific issue.

**Comment by pilldoc** [comment]
I can confirm since the 1.9.5 patch ksfo has been wiped out of the nav database and shows up as “not in database” in the vanilla a320

**Comment by Watsi01** [comment]
There was the theory that all deluxe airport wiped out of the database. But EDDF e.g. works.

**Comment by pilldoc** [comment]
Yeah not all airports were wiped out klax still works. I do have deluxe so that may explain why some people can’t reproduce this bug.

**Comment by jswidler** [comment]
I am having this problem, this thread has helped me identify the behavior I was connecting may or may not be related.

I see "NOT IN DATABASE" on the init page for the premium airports, at least SFO but some others as well.  After reading this thread, it appears to me that this only happens with premium airports.  This part happens in vanilla I think, without the mod installed.

I also see "NOT IN DATABASE" on the F-PLN page trying to load up approaches as outlined in https://github.com/flybywiresim/a32nx/issues/1378,  this is very common and seems to happen with all airports.  This only happens with A32X installed.

**Comment by Mariolink123** [comment]
Can confirm with the premium deluxe version that KSFO shows up as not being in the database, had to divert to KOAK instead!

**Comment by Benjozork** [comment]
Closing as this is a game issue.
