### ISSUE TITLE
Instrument Panel Refresh Rate

### ISSUE THREAD

**Issue by arkar16** [flybywiresim/a32nx#134]
Real A320neo should be around 30hz refresh rate, right now MSFS has no cap on it which causes lag issues.

https://www.reddit.com/r/flightsim/comments/igw31c/lowering_2d_instrument_refresh_rate_improves

You can assign this to me since it's not really a critical bug but a QoL thing and I can get it done (unless someone is already working on it!)

**Comment by Meqolo** [comment]
That was changed, but then reverted as it changes the shared code between every aircraft, not just the A320, and may cause future issues

**Comment by arvinjarvin** [comment]
Hi

Thanks for opening this issue.

We are currently working on this! And we ask for your patience. We will keep you updated (: 

All the best
Arvin

**Comment by NathanInnes** [comment]
You can now adjust the refresh rate of the displays with the base game under GENERAL > GRAPHICS. Closing issue.
