### ISSUE TITLE
[BUG] Fuel consumption too high

### ISSUE THREAD

**Issue by Fiorentoni** [flybywiresim/a32nx#1343]
**Mod Version**

**Describe the bug**

I plan all my flights with Simbrief, but with the calculated fuel amount on Simbrief I only end up with about 1 ton left when I'm landing. I saw that on cruise flight (Mach 0,78) it uses at least 50kg/min, which I think is much too high, it should be around 30kg/min IIRC.

**To Reproduce**

1. Plan a flight with Simbrief
2. Use the block fuel indicated by Simbrief
3. Fly normally and check how much fuel is left when you land

**Expected behavior**

At least the ALTN fuel, contingency and emergency reserve fuel should be left over after a normal flight, which is AT LEAST 3 tons (most of the time it is more because the alternative airport isn't close).

**Actual behavior**

A lot less fuel is left when I arrive at the destination. A diversion would have no chance.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
I did not really watch out for it, as I haven't simulated a diversion yet or something like that. It could very well have been like this for a while.
Is this a problem in the vanilla unmodded game?
No idea.

Discord username (if different from GitHub):

**Comment by ElSrJuez** [comment]
Could you post here the exact parameters from your Simbrief Fleet Aircraft Profile?

**Comment by Fiorentoni** [comment]
Sure:
[https://www.simbrief.com/system/dispatch.php?sharefleet=eyJ0cyI6IjE2MDE0ODI0ODE1MzQiLCJiYXNldHlwZSI6IkEzMjAiLCJjb21tZW50cyI6IiIsImljYW8iOiJBMzJOIiwibmFtZSI6IkEzMjBORU8iLCJlbmdpbmVzIjoiQ0ZNIExFQVAtMUEyNiIsInJlZyI6Ik4iLCJmaW4iOiIiLCJzZWxjYWwiOiIiLCJoZXhjb2RlIjoiIiwiY2F0IjoiTSIsInBlciI6IkMiLCJlcXVpcCI6IlNERTNGR0hJUldZIiwidHJhbnNwb25kZXIiOiJMQjEiLCJwYm4iOiJBMUIxQzFEMU8xUzEiLCJleHRyYXJtayI6IiIsIm1heHBheCI6IjE4OSIsIndndHVuaXRzIjoiS0dTIiwib2V3IjoiNDEwMDUiLCJtemZ3IjoiNjQzMDAiLCJtdG93IjoiNzkwMDAiLCJtbHciOiI2NzQwMCIsIm1heGZ1ZWwiOiIyNjczMCIsInBheHdndCI6IjEwNCIsImRlZmF1bHRjaSI6IiIsImZ1ZWxmYWN0b3IiOiJQMDAiLCJjcnVpc2VvZmZzZXQiOiJQMDAwMCJ9](url)

**Comment by lousybyte** [comment]
Duplicate #1166.
