### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JacobKreindler** [flybywiresim/a32nx#1347]
**Mod Version**

master

**Describe the bug**

There are fast strobing lights coming from a random spots all over the cockpit

**To Reproduce**

1. Load into the cockpit at night
2. Look around
3.

**Expected behavior**

**Actual behavior**

There shouldn't be random strobing lights

**References**

[Random Flashing Lights.zip](https://github.com/flybywiresim/a32nx/files/5381488/Random.Flashing.Lights.zip)

**Additional context**

Was this working before/when did the issue start occurring?
With the last release
Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):
JacobK #9511

**Comment by MisterChocker** [comment]
I have the same issue. This is since the last MSFS update.

**Comment by Pleasure0102** [comment]
you are not on the latest dev version, this has been fixed in the latest dev version, please download the installer and download latest version. Or downloaded however you want to download it :)

**Comment by JacobKreindler** [comment]
Is it in the latest master version?

**Comment by Pleasure0102** [comment]
the latest master fixed it like i said

**Comment by lukecologne** [comment]
Also duplicate #1336 and may more. closing now.
