### ISSUE TITLE
[BUG] Displays Go Into Self Test Mode When Dimmed

### ISSUE THREAD

**Issue by JacobKreindler** [flybywiresim/a32nx#1348]
**Mod Version**

master

**Describe the bug**

All of the displays goes into test mode when all the way dimmed and turned back up again

**To Reproduce**

1. Turn the knob for any of the displays all the way down and then back up again
2.
3.

**Expected behavior**

It should just go back to the way that it was instead of going to self test mode

**Actual behavior**

It goes into self test mode

**References**

[Display Bug.zip](https://github.com/flybywiresim/a32nx/files/5381513/Display.Bug.zip)

**Additional context**

Was this working before/when did the issue start occurring?
Since the beginning
Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):
JacobK #9511

**Comment by Pleasure0102** [comment]
please add a tiitle

**Comment by JacobKreindler** [comment]
Where?

**Comment by Pleasure0102** [comment]
:) thanks

**Comment by JacobKreindler** [comment]
Sure, No prob

**Comment by lukecologne** [comment]
This has been discussed already. The current behaviour is kind of correct, but not really. See #945 for more info.

**Comment by lukecologne** [comment]
Closing as duplicate.
