### ISSUE TITLE
Rate of Descent too high in managed mode

### ISSUE THREAD

**Issue by nobodyn0se** [flybywiresim/a32nx#135]
When trying to descend in managed mode, the aircraft pitches down 3-5 degrees below the horizon and initially starts descending at a rate of -4400 to -5200 fpm. The descent rate then decreases to around -3300 to -3500 fpm which is still higher than usual.

**Comment by lousybyte** [comment]
It's not just managed mode, I've had as high as -6000fpm in OP DESC mode, the only way to properly set it is to manually adjust the vspeed.

**Comment by g0per** [comment]
I dont have a FCOM available right now. Which is the standard ROD value?

**Comment by PCGamesF1Tech** [comment]
DES mode should start descending with 1000fpm until intercepting the calculated profile, thereafter idle decent managing the profile with the speed range

**Comment by lousybyte** [comment]
This should be fixed now, or at least greatly improved, other more detailed issues opened about it.
