### ISSUE TITLE
[BUG] Modelling - Steering tiller glowing disconnect button

### ISSUE THREAD

**Issue by efortier-95** [flybywiresim/a32nx#1350]
**Mod Version**

Dev version:
built: 2020-10-14T20:06:03+00:00
ref: refs/heads/master
sha: 3906ea82ef00d54f85387430444c583238144621
actor: Benjozork
event_name: push

**Describe the bug**

The steering tiller disconnect button glows at night. There's no ambient light coming from it, so I don't think this is intentional.

**To Reproduce**

1. Load up at night
2. Apply electrical power (batteries?)
3. Increase main panel and pedestal integral lighting
4. Look at steering tiller

**Expected behavior**

No glowing parts

**Actual behavior**

Steering tiller disconnect button glows.

**References**

No battery power:
![image](https://user-images.githubusercontent.com/56796781/96060816-81f60c80-0e5f-11eb-81c0-aa4dbd8f3a71.png)

Battery 1 and 2 on:
![image](https://user-images.githubusercontent.com/56796781/96060870-aeaa2400-0e5f-11eb-834c-e0fb5d0e2974.png)

Main panel and pedestal integral lighting:
![image](https://user-images.githubusercontent.com/56796781/96060882-bcf84000-0e5f-11eb-9e6d-1b63c2373db1.png)
![image](https://user-images.githubusercontent.com/56796781/96060896-c5e91180-0e5f-11eb-89fe-718e202d6677.png)
I don't think the button should be glowing...

**Additional context**

Was this working before/when did the issue start occurring?
Unsure

Is this a problem in the vanilla unmodded game?
Unsure

Discord username (if different from GitHub):
Eefoe#0570

**Comment by Pleasure0102** [comment]
Dark checked the texture, and said it can't be changed from texture side. But I will take another look at it to confirm

**Comment by Pleasure0102** [comment]
so the Emmisive texture is fine, it looks like the pedestal integral lighting actually increases the brightness of the mesh below the actual decals, @Benjozork can that be changed ? It is bascially the same thing that has been done to the fire lights i think
