### ISSUE TITLE
[REQUEST] 

### ISSUE THREAD

**Issue by JacobKreindler** [flybywiresim/a32nx#1353]
**Is your feature request related to a problem? Please describe.**

I'm annoyed when I am using the F/O  seat and have to use the captains side FMC

**Describe the feature you'd like to see implemented**

I would like to have the 2 FMC's work independently of one another

**References**

Both FMC's do the same thing bug can be used independently

**Additional context**

Discord username (if different from GitHub):
JacobK #9511

**Comment by Benjozork** [comment]
Duplicate of #1058
