### ISSUE TITLE
[BUG] Plus / Minus button on the MCDU does not take inputs

### ISSUE THREAD

**Issue by Hans-4SM** [flybywiresim/a32nx#1354]
**Mod Version**

Stable release 0.4.0

**Describe the bug**

Plus / Minus button on the FMC does not function.

**To Reproduce**

1. Set up your flight on the INIT page of the FMC
2. When entering CRZ ALT/TEMP, attempt to enter the anticipated temperature at CRZ ALT (e.g. -50)
3.

**Expected behavior**

When clicking the button, a minus should appear in the text box. 

**Actual behavior**

A minus does not appear. 

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Yes, up until the dev of the day before yesterday that button was still working as expected. 

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by lousybyte** [comment]
Related #1326.

**Comment by Watsi01** [comment]
> 
> 
> Related #1326.

Yeah, I think it's the same problem.

**Comment by Rameyuk** [comment]
I can replicate this bug: I also can't type using the +/- button to enter 380/-55.

My current workaround is to just type in 38000 and enter it into the CRZ FL/TEMP. And it'll auto-populate with the appropriate cruising flight level and the temperature with the negative sign included.
