### ISSUE TITLE
[BUG] No Speeds are showing in FMC Flightplan - Speeds too slow in FP Mode

### ISSUE THREAD

**Issue by SM-396** [flybywiresim/a32nx#1356]
**Mod Version**
0.4.0

**Describe the bug**
I cant see the Speeds in Flightplan Page on FMC

**Expected behavior**
When i inserted an Simbrief Flightplan the Plane should use the correct Speeds . 

**Actual behavior**
I See no Speeds in the Flightplan and mostly the used Speeds are too less. 

**Additional context**
I cant find another Post with this behaviour. Sorry

**Comment by James3221** [comment]
you can click on v1, vr and v2 to get the calculated speeds in your scratch pad then click again to paste them in.

**Comment by MisterChocker** [comment]
fixed by now
