### ISSUE TITLE
[BUG] DIR , V/S issue 

### ISSUE THREAD

**Issue by ducky3333** [flybywiresim/a32nx#1360]
**Mod Version**
 

0.4.0 

**Describe the bug**

i v searched this issue, but i couldnt find it so i m gonna issue to requesting fix. if this is was issued , i m sorry 

1. DIR N/D drawing still not working. (FMC following is works) 

The only drawing is strange. aircraft had followed perfectly.

2. descend profile.

on Cruzing ALT , if i push altitude nobe, start descending -4500 v/s. i think the normal is to keep -1000 v/s untill matching FMC ALT.

3. V/S not work.  
i m gonna try to use V/S from Cruzing altitue to descend , but not worked. 

**To Reproduce**

1. nothing
2. using v/s mode
3.it is worked after push open descend mode.

**Expected behavior**

**Actual behavior**

**References**

![Honeyview_Microsoft Flight Simulator Screenshot 2020 10 15 - 15 39 00 49](https://user-images.githubusercontent.com/38446386/96102440-7d8a2c00-0f11-11eb-9fa9-87a4eb408e92.png)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Please open separate issues for both issues and respect the issue template entirely.
