### ISSUE TITLE
[REQUEST] Logo light shall be off when gear up

### ISSUE THREAD

**Issue by JLD95** [flybywiresim/a32nx#1362]
**Is your feature request related to a problem? Please describe.**

In flight, we can see logo light on the tail

**Describe the feature you'd like to see implemented**

In flight, when gear is up, logo light shall be extinguished.

**References**

**Additional context**

Discord username (if different from GitHub):

**Comment by JLD95** [comment]
![b704b724848a2efda1f845fc447a86f6](https://user-images.githubusercontent.com/5894146/96111682-d4780d00-0ee1-11eb-8eb3-122270c9e8d6.jpg)

**Comment by JLD95** [comment]
And when gear down, logo lights shall be turned on.

**Comment by JLD95** [comment]
![unknown-1](https://user-images.githubusercontent.com/5894146/96112145-7dbf0300-0ee2-11eb-86ff-740f120295e8.png)
![unknown](https://user-images.githubusercontent.com/5894146/96112148-7e579980-0ee2-11eb-82f5-e8b806090948.png)

**Comment by JLD95** [comment]
![unknown-3](https://user-images.githubusercontent.com/5894146/96112347-c24a9e80-0ee2-11eb-8a13-781a170e75a1.png)

**Comment by MuppetOwl** [comment]
So turn it off when you take up the landing gear and on then when lading? Its a switch for it :P The logo light usage also have different company policy. Most common is to turn it off when above 10 000feet and on when under. Or i'm misunderstanding this request?

**Comment by lukecologne** [comment]
You can't turn off the logo light without also disabling the nav lights.

**Comment by JLD95** [comment]
Ok thank YouLe 16 oct. 2020 13:31, lukecologne <notifications@github.com> a écrit :
You can't turn off the logo light without also disabling the nav lights. That is the problem
