### ISSUE TITLE
[BUG] Version 0.4.0 - Speed too slow on Takeoff , two Takeoffs , two crashes . 

### ISSUE THREAD

**Issue by SM-396** [flybywiresim/a32nx#1366]
**Mod Version**
0.4.0

**Describe the bug**
When i takeoff the Speed ist too slow . Two trys two crashes because of Stall . 

**To Reproduce**
Takeoff , Set to CL Trust .  Switch Autopilot on . 

**Expected behavior**
Like in the Versions before an Speed of around 220-240 konts

**Actual behavior**
120 Knots , then Stall and Crash 

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by nikotina91** [comment]
Are you setting the throttle to CL before the plane tells you? you're supposed to use MCT/FLX or TOGA until thrust reduction altitude then, when on the fma LVR CLB start blinking, you can set it to CL.

**Comment by SM-396** [comment]
Good Morning , 
Yes when it blinks in the PFD then i set the Thrust Lever to "CL" . 
Why i can see the Speeds from the Flightplan in the Flightplan Page in FMC ?

**Comment by James3221** [comment]
make sure to be using the updated v1, vr and v2 calculations in the mcdu, the autopilot is being worked on, so if it's an issue with aggressive aoa then a fix should come with the new ap, also make sure you are using the right thrust settings and correct weight & balance when taking off.

**Comment by MisterChocker** [comment]
Still relevant? #1563 changed takeoff speeds.

**Comment by MisterChocker** [comment]
@Benjozork

**Comment by Benjozork** [comment]
Closing, new report can be made for new speeds if problematic
