### ISSUE TITLE
[BUG] MCDU "+/-" button don't work properly

### ISSUE THREAD

**Issue by ACSoft47** [flybywiresim/a32nx#1367]
**Mod Version**

built: 2020-10-15T01:38:50+00:00
ref: refs/heads/master
sha: a72a977f0b5c74eab9396bab64cb16f6cc4c8120
actor: Benjozork
event_name: push

**Describe the bug**

If you don't stroke "+/-" button in the first place, it does not work

**To Reproduce**

1. Try to stroke "+/-" button in first place, it work
2. Try to use "+/-" button while typing, "380/-55", minus does not work !
3.

**Expected behavior**

typing "380/-50" should have displayed the minus and then the field FL380/-55

**Actual behavior**

Then minus isn't taken on typing field and value field

**References**

**Additional context**

Was this working before/when did the issue start occurring?
don't know

Is this a problem in the vanilla unmodded game?
not applicable, I think

Discord username (if different from GitHub):

**Comment by Rameyuk** [comment]
I can replicate this bug: I also can't type using the +/- button to enter 380/-55.

My current workaround is to just type in 38000 and enter it into the CRZ FL/TEMP. And it'll auto-populate with the appropriate cruising flight level and the temperature with the negative sign included.

**Comment by Benjozork** [comment]
Thank you for your report ! It's duplicated by #1354, let's track it there.
