### ISSUE TITLE
BUG WHITH VERSION 4

### ISSUE THREAD

**Issue by benjack57** [flybywiresim/a32nx#1369]
Hello
I installed version 4 of A320NX today and there are several bugs in my house
- the IRS no longer works
- the anti ice are on when opening
- no lighting on the icam and PFD and ND although the buttons are activated
can you help me please version 3.1 was working pretty well
thank you

**Comment by Benjozork** [comment]
Please respect the issue template.

**Comment by Benjozork** [comment]
> sorry i don't understand what you mean i'm just posting bugs
> thank you

* When you create an issue, there is a template. You deleted it.
* The de-ice issue has already been reported and we are working on it 👍
* When you report bugs, open separate issues instead of one for multiple

We ask for this because it makes it tremendously easier for us to sort out problems.
