### ISSUE TITLE
PFD isn't replying informations.

### ISSUE THREAD

**Issue by erickdib** [flybywiresim/a32nx#1374]
I'm flying with version 4.0.0 and I found a bug at PFD, they don't are replicating the screen with FO
At this screenshot at cpt side have a THR CLB | CLB | NAV and at FO this doesn't appears

![image](https://user-images.githubusercontent.com/7771613/96170612-30e72680-0efa-11eb-8809-70c247e5a855.png)

**Comment by 1Revenger1** [comment]
If you enable the Flight Director for the right display, does the FMA information appear?

**Comment by lukecologne** [comment]
Please respect the issue template.

**Comment by lukecologne** [comment]
Also this is expected as you have disabled your FO side flight director.

**Comment by erickdib** [comment]
> If you enable the Flight Director for the right display, does the FMA information appear?

Sorry guys, was a mistake! A always remember but today I forget that!
