### ISSUE TITLE
[BUG] Plane can't reach normal cruising altitude

### ISSUE THREAD

**Issue by marci1229** [flybywiresim/a32nx#1375]
**Mod Version**
 **Release version 0.4.0** 

 **built: 2020-10-15T01:38:50+00:00**
**ref: refs/heads/master
sha: a72a977f0b5c74eab9396bab64cb16f6cc4c8120
actor: Benjozork
event_name: push** 

**Describe the bug**
**The plane can't climb and can't reach FL380. Weird climbing and cruising.**

**To Reproduce**

1. Start an IFR flight with the plane.
2. Try to climb FL380 with Live Weather.
3. Plane will stops at about FL300 and can't reach higher levels. The cruising angle will be weird like when you in stall statement.

**Expected behavior**
**Normal easily climb with normal cruising and speed.** 

**Actual behavior**
 **Weird climbing and cruising.** 

**References**
**None.** 

**Additional context**
**You can see cruising on the picture.**

Was this working before/when did the issue start occurring? Yes.

Is this a problem in the vanilla unmodded game?
**Modded with liveries and REX Weather Force only.**

Discord username (if different from GitHub): marci1229#1646
![Weird Cruising](https://user-images.githubusercontent.com/72943374/96174600-d2d23780-0f29-11eb-9fc2-11bdbbc7bef8.png)

**Comment by Benjozork** [comment]
Pitch angle reported in #984

**Comment by Benjozork** [comment]
Is #1377 the same problem you are facing for altitude ?

**Comment by ntlgr** [comment]
Make sure your plane is not all frozen. If so, turn on wing & engine a.ice

**Comment by marci1229** [comment]
> Make sure your plane is not all frozen. If so, turn on wing & engine a.ice. Judging from your screenshot, it is.

It's okay but the ice set to visual only.

**Comment by marci1229** [comment]
> Is #1377 the same problem you are facing for altitude ?

No it is a different bug or something. Also with approaches the pitch is too much but now while cruising. I can't even reach FL330. The plane can't handle it.

**Comment by MisterChocker** [comment]
I haven't experienced this in https://github.com/flybywiresim/a32nx/pull/1295 maybe my changes to aero resolve this.

**Comment by MisterChocker** [comment]
Also what was your GW?

**Comment by ntlgr** [comment]
> > Make sure your plane is not all frozen. If so, turn on wing & engine a.ice. Judging from your screenshot, it is.
> 
> It's okay but the ice set to visual only.

I can assure you that the plane can reach FL330+.
The bug might be in the sim, and the "visual only" might not work.
Please enable wing and engine anti ice and try again.

**Comment by CBGonzalez** [comment]
As it is now, the engines seem under powered to me: taking off with 66000kg weight, ISA 10, clear skies climbing at 250/300/0.78 it barely reaches mach switchover (is climbing at approx 800 ft/min), then crawls up. Leaving the autopilot on, it is doing approx 400 ft/min at FL320. Turning the autopilot off you can hand-fly it to FL350 with great delicacy :-)
By the book it should be able to reach FL390 in approx 23 minutes at that staring weight.
The current `engines.cfg` has a `thrust_scalar = 0.88` (original Asobo is 1.0). I tend to use 0.92 to get better numbers.

**Comment by MisterChocker** [comment]
@CBGonzalez https://github.com/flybywiresim/a32nx/pull/1295
