### ISSUE TITLE
[BUG] will not stay at FL360

### ISSUE THREAD

**Issue by Middi25X** [flybywiresim/a32nx#1377]
**Mod Version**
 0.4.0

**Describe the bug**

When at FL 360 airplane start turning left then descent.. when i try to put waypoint again in it still fly to left but after some secound it come back to NAV again. Other bug is when at FL360 it start shaking even when mac is .78 or higher

**To Reproduce**

1. At Cruiuse level
2. As soon it reach FL 300 or aboive
3.

**Expected behavior**

Start turnin left and start shaking,

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?
was working fine with 0.3.1 version
Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Middi25X** [comment]
Almost the same bug only here is turning left

**Comment by MisterChocker** [comment]
For me sounds like some sort of stall

**Comment by Middi25X** [comment]
Yeah it almost stall too above FL300:s was flying from Kastrup to Varenes but have to divert to Arlanda because it was so shaky :/

**Comment by MisterChocker** [comment]
Do you know your GW at the time?

**Comment by Middi25X** [comment]
no sorry :/
