### ISSUE TITLE
[BUG] Backlight illuminates cockpit after shutdown of a/c

### ISSUE THREAD

**Issue by ChruutvoLuzi** [flybywiresim/a32nx#1379]
**Mod Version**

latest dev branch (from installer)

**Describe the bug**

PFD, ND and ECAM Backlight still iluminating after shutdown

**To Reproduce**

1. Load C&D
2. Start everything
3. Shut down everything

**Expected behavior**

It should not iluminate the cockpit

**Actual behavior**

It does :)

**References**

https://media.discordapp.net/attachments/314015589595086848/766395136564396053/Microsoft_Flight_Simulator_2020.10.15_-_22.19.54.01.mp4

**Additional context**

Was this working before/when did the issue start occurring?
Cant tell for sure but around 4 Days ago it was working, havent been flying since then
Is this a problem in the vanilla unmodded game?
No, as there is no backlighting in the vanilla

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Duplicate of #1300

**Comment by ChruutvoLuzi** [comment]
Oh, sorry. I often check the issues on github when at work but seems like i might have missed that one D:
