### ISSUE TITLE
User/Pilot waypoints

### ISSUE THREAD

**Issue by bluecew** [flybywiresim/a32nx#1380]
**Is your feature request related to a problem? Please describe.**

When not selecting an arrival airport in the world map, I like to set up my flight plan manually in the MCDU with SimBrief. Short flights work fine, but for longer flights that require waypoints based on latitude/longitude I am unable to set up them up. In the MCDU, going to DATA>[next page]>PILOTS WAYPOINTS, inputting anything into the identifier does not work. It also does not work if I hit NEW WAYPOINT on that same page. So I cannot manually set up flight plans for longer flights and I must use the world map.

**Describe the feature you'd like to see implemented**

In the MCDU, going to DATA>[next page]>PILOTS WAYPOINTS>NEW WAYPOINT, I would like that entire page to work so I can input a random identifier and latitude/longitude coordinates for custom waypoints that do not have a database name. Currently, nothing on that page or the page before works.

**References**

https://youtu.be/FElp-P2BySw?t=277

**Additional context**

In order to input custom waypoints, I must use the world map to set my flight plan so the MCDU becomes useless for inputting flight plan.

Discord username (if different from GitHub): bluecew#5112

**Comment by ghosh9691** [comment]
Any timeframe for inclusion of this feature?

**Comment by tracernz** [comment]
> 
> 
> Any timeframe for inclusion of this feature?

See https://github.com/flybywiresim/a32nx/pull/6144
