### ISSUE TITLE
[REQUEST] VOR AND NDB NAVAIDS

### ISSUE THREAD

**Issue by cvqueiroz** [flybywiresim/a32nx#1381]
**Is your feature request related to a problem? Please describe.**

**Please, considering the fact of the aircraft does not offer a kind of precision sistem in order to start descent respecting all the constraints at exactly point of TOD until the IAF, i would like to see VOR and NDB navaids available in the next versions. It's gonna become easier the calculation of TOD**

**References**

**Additional context**

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment]
What is the matter of this issue?

**Comment by MisterChocker** [comment]
Closing since no response from OP
