### ISSUE TITLE
Final approach (G/S) attitude not realistic

### ISSUE THREAD

**Issue by mark1606** [flybywiresim/a32nx#1383]
**Mod Version**
Realese v0.4.0

Approach attitude not realistic.

See Video:

https://www.youtube.com/watch?v=vdn-bi7zhwY

**Expected behavior**
Lower pitch atttidude when g/s is established

Was working ok before latest release.

Problem not present in Vanilla.

Thanks.

**Comment by joniatus** [comment]
It looks like your flight model got changed to legacy. In settings make sure flight model is set to modern

**Comment by mark1606** [comment]
Thanks!
