### ISSUE TITLE
[BUG]I'm using the stable version. I'm trying to load a flightplan into the MCDU and it wont let me select the departure airport so I can set my runway or STAR. If I go to INIT A and select IRS INIT it is showing me in the Northern hemisphere instead of the southern. I tried after the IRS was aligned and it still gave me the same problem. I cannot select my departure airport. The first image is prealignment and the second image is post alignment. I can set a flight plan using the ingame world map. My discord name is @brownyb

### ISSUE THREAD

**Issue by Brownyb68** [flybywiresim/a32nx#1384]
**Mod Version**

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):
![Desktop Screenshot 2020 10 16 - 07 51 07 14](https://user-images.githubusercontent.com/72951458/96195538-bcaf9000-0f98-11eb-95a7-2c5e4a7469c9.png)
![Desktop Screenshot 2020 10 16 - 10 01 55 85](https://user-images.githubusercontent.com/72951458/96195554-c9cc7f00-0f98-11eb-8cc9-b76a9b911390.png)
![Desktop Screenshot 2020 10 16 - 10 02 45 67](https://user-images.githubusercontent.com/72951458/96195567-d224ba00-0f98-11eb-98a4-b58d06731593.png)
![Desktop Screenshot 2020 10 16 - 10 03 13 92](https://user-images.githubusercontent.com/72951458/96195602-e5378a00-0f98-11eb-892e-ba199a6b7735.png)

**Comment by Inaxair** [comment]
Please modify the title, then out the message in the message box. Thanks!

**Comment by DLH455** [comment]
Have the same issue unfortunately

**Comment by SCBionicle** [comment]
This is the same issue I'm having here #1378

**Comment by Benjozork** [comment]
Please make issues with the template filled out and not in the title.
