### ISSUE TITLE
[REQUEST]F-PLN Discontinuity 

### ISSUE THREAD

**Issue by Username23-23** [flybywiresim/a32nx#1385]
**Is your feature request related to a problem? Please describe.**
The request relates to an inaccuracy in the f-pln page of the MCDU. When there are no waypoints entered between the dep/arr airports, there should be a flight-plan discontinuity. Instead, the f-pln page has no discontinuities and simply shows the deceleration waypoint.

**Describe the feature you'd like to see implemented**
Discontinuities wherever appropriate. They don’t seem to even exist in the default MCDU 

**References**
See message from IRL pilot Dokug in #mcdu channel on discord 

**Additional context**
N/A

Discord username (if different from GitHub):
NONAmr2433 [Z-5] #8777

**Comment by NathanInnes** [comment]
Please add a title.

**Comment by Oberstumfuher** [comment]
I don’t know what’s going on, but the autoland is totally terrible to execute, maybe it’s something from Asobo, I’m using the current version of the 3nx master, the aircraft simply touches the ground, it seems to go into stool and floats, it stays very complicated to control and make it fall into the "nose" of the aircraft. Maybe if you could take a look, using ILS and autolanding, to see what's going on and, who knows, be able to fix it.

**Comment by SM-396** [comment]
Hello , 
I can confirm this . The Plane jumps like an Rubber Ball .

**Comment by Mariolink123** [comment]
> I don’t know what’s going on, but the autoland is totally terrible to execute, maybe it’s something from Asobo, I’m using the current version of the A32nx master, the aircraft simply touches the ground, it seems to go into stool and floats, it stays very complicated to control and make it fall into the "nose" of the aircraft. Maybe if you could take a look, using ILS and autolanding, to see what's going on and, who knows, be able to fix it.

Think this is slightly off topic, you probably want to make a new issue discussing this. However, the auto landing IIRC is something team can't modify yet, and it's like this in the default aircraft as well.

**Comment by Oberstumfuher** [comment]
> > I don’t know what’s going on, but the autoland is totally terrible to execute, maybe it’s something from Asobo, I’m using the current version of the A32nx master, the aircraft simply touches the ground, it seems to go into stool and floats, it stays very complicated to control and make it fall into the "nose" of the aircraft. Maybe if you could take a look, using ILS and autolanding, to see what's going on and, who knows, be able to fix it.
> 
> Think this is slightly off topic, you probably want to make a new issue discussing this. However, the auto landing IIRC is something team can't modify yet, and it's like this in the default aircraft as well.

off topic ?? this is related to outopilot, isn't it ?? Now I believe that you can fix your flight, follow routes, etc. You can also check this, correct? Many people keep asking for things that I don't think are important, like lighting color and etc. Now, I believe it would be the most important thing to make the aircraft "good for flight" the rest is just cosmetic, right?

**Comment by Mariolink123** [comment]
> > > I don’t know what’s going on, but the autoland is totally terrible to execute, maybe it’s something from Asobo, I’m using the current version of the A32nx master, the aircraft simply touches the ground, it seems to go into stool and floats, it stays very complicated to control and make it fall into the "nose" of the aircraft. Maybe if you could take a look, using ILS and autolanding, to see what's going on and, who knows, be able to fix it.
> > 
> > 
> > Think this is slightly off topic, you probably want to make a new issue discussing this. However, the auto landing IIRC is something team can't modify yet, and it's like this in the default aircraft as well.
> 
> off topic ?? this is related to outopilot, isn't it ?? Now I believe that you can fix your flight, follow routes, etc. You can also check this, correct? Many people keep asking for things that I don't think are important, like lighting color and etc. Now, I believe it would be the most important thing to make the aircraft "good for flight" the rest is just cosmetic, right?

You can create a new "issue" just like this one and name it something like "Autoland not working as intended". This thread is specifically about the F-Plan discontinuity bug. Click this link: https://github.com/flybywiresim/a32nx/issues/new/choose and choose "Bug".

**Comment by Oberstumfuher** [comment]
> > > > I don’t know what’s going on, but the autoland is totally terrible to execute, maybe it’s something from Asobo, I’m using the current version of the A32nx master, the aircraft simply touches the ground, it seems to go into stool and floats, it stays very complicated to control and make it fall into the "nose" of the aircraft. Maybe if you could take a look, using ILS and autolanding, to see what's going on and, who knows, be able to fix it.
> > > 
> > > 
> > > Think this is slightly off topic, you probably want to make a new issue discussing this. However, the auto landing IIRC is something team can't modify yet, and it's like this in the default aircraft as well.
> > 
> > 
> > off topic ?? this is related to outopilot, isn't it ?? Now I believe that you can fix your flight, follow routes, etc. You can also check this, correct? Many people keep asking for things that I don't think are important, like lighting color and etc. Now, I believe it would be the most important thing to make the aircraft "good for flight" the rest is just cosmetic, right?
> 
> You can create a new "issue" just like this one and name it something like "Autoland not working as intended". This thread is specifically about the F-Plan discontinuity bug. Click this link: https://github.com/flybywiresim/a32nx/issues/new/choose and choose "Bug".

Thank you!

**Comment by Tiebo** [comment]
Also when you press CLR on any WYP it should be removed and a F-PLN DISCONTINUITY should be inserted instead
