### ISSUE TITLE
[BUG] Strobe lights are visible inside cockpit

### ISSUE THREAD

**Issue by PuL9** [flybywiresim/a32nx#1386]
**Mod Version**

Master

**Describe the bug**

Strobe lights are visible inside cockpit in night

**To Reproduce**

1. Enable strobe lights in night
2. Get annoyed

**Expected behavior**

They should obviously not be blinking through the aircraft in to the cockpit

**Actual behavior**

As the title says

**References**

Might be hard to see on the video because of compression stuff, but it's visible on my monitor
https://drive.google.com/file/d/1301QC97tNqR2Zpa46U1d466lXwEHTUN5/view?usp=sharing

**Additional context**

Not sure if this can be fixed with current SDK tho

Was this working before/when did the issue start occurring?
Not sure

Is this a problem in the vanilla unmodded game?
Not sure

Discord username same

**Comment by Roi1862** [comment]
Is it possible that even on the real thing some strobe light getting in ? Its very faint on my end.

**Comment by PuL9** [comment]
> Is it possible that even on the real thing some strobe light getting in (most likely not...)? Its very faint on my end.

Don't think so. It is very annoying, imagine pilots getting annoyed on an 4 hour flight.

**Comment by pilldoc** [comment]
Can confirm the new update is causing flashing strobe lights within the cockpit

**Comment by PuL9** [comment]
Strobe lights are still visible inside the cockpit.
https://i.imgur.com/zQYyOVO.png
https://i.imgur.com/5ysKhx9.png

**Comment by Benjozork** [comment]
The reason this was closed is that this is a game engine problem. Sorry for the lack of message.

**Comment by PuL9** [comment]
> The reason this was closed is that this is a game engine problem. Sorry for the lack of message.

Sorry for late response, I have found a workaround to solve this issue
https://github.com/flybywiresim/a32nx/pull/1455#issuecomment-727596035

This workaround didn't break anything (from my testing) strobe lights still work outside and don't bleed in to the cockpit.
I don't want to sound rude but what stops A32NX developers to fix or just remove that file from future dev builds? Because that file comes together with A32NX mod, not with asobo's A320
