### ISSUE TITLE
[REQUEST] Hope to increase the voice prompt effect of the first officer on takeoff airspeed, 

### ISSUE THREAD

**Issue by dc1ps2** [flybywiresim/a32nx#1390]
**Is your feature request related to a problem? Please describe.**

I hope to increase the first officer's call to take-off speed, V1 Vr rotate and other sounds

**Describe the feature you'd like to see implemented**

When the take-off speed reaches the speed specified by MCDU, there will be voice prompts such as V1, Vr, rotate, etc.

**References**

N/A

**Additional context**

N/A

Discord username (if different from GitHub):

**Comment by hotshotp** [comment]
I'll close this in reference to #1558. I am going to be working on this feature the next few days
