### ISSUE TITLE
[BUG] Which is the Right way to insert ZFW/ZFWCG ? 

### ISSUE THREAD

**Issue by SM-396** [flybywiresim/a32nx#1393]
**Mod Version**
0.4.0

**Describe the bug**
I create an Flightplan EDDB to EDDT with Simbrief  for an A320-200 as u can see here . 

I have an ZFW of 60.8 and an Block Fuel of 5246 

<img width="443" alt="2020-10-16 11_09_04-EDDBEDDT_PDF_1602824540 pdf" src="https://user-images.githubusercontent.com/50043259/96239626-3bf49200-0fa0-11eb-9aed-2651f03466ed.png">
<img width="311" alt="2020-10-16 11_09_23-EDDBEDDT_PDF_1602824540 pdf" src="https://user-images.githubusercontent.com/50043259/96239628-3d25bf00-0fa0-11eb-85c0-c81c20f36a17.png">

When i try to insert the ZFW of 60.8 the i become an Format Error . 
When i try to insert an ZFW of 60.8 and an ZFWCG of 25.0 i become an Format Error . 

**To Reproduce**
As describe it before . 

**Expected behavior**
When i insert ZFW and ZFWCG the it should work . 

**Actual behavior**
Format Error

**Additional context**
1. Where i become the correct ZFWCG for my ZFW ? 
2. Is it necessary to setup the Fuel in Game as it was in the Simbrief Flightplan ?

**Comment by ABoldOne** [comment]
This issue is fixed with the latest master build.

**Comment by SM-396** [comment]
> This issue is fixed with the latest master build.

Eh , i dont understand . The latest Build is the 0.4.0 right . This is what i have installed .

**Comment by ABoldOne** [comment]
> > This issue is fixed with the latest master build.
> 
> Eh , i dont understand . The latest Build is the 0.4.0 right . This is what i have installed . 

Do you have the stable or dev build installed? You need the latest dev/master build.

**Comment by SM-396** [comment]
> > > This issue is fixed with the latest master build.
> > 
> > 
> > Eh , i dont understand . The latest Build is the 0.4.0 right . This is what i have installed .
> 
> Do you have the stable or dev build installed? You need the latest dev/master build.

Means i should choose in Installer the Development Version ? 

<img width="333" alt="2020-10-16 11_27_04-FlyByWire Downloader v0 5" src="https://user-images.githubusercontent.com/50043259/96241531-94c52a00-0fa2-11eb-84a4-0a49dc31109d.png">

**Comment by ABoldOne** [comment]
> > > > This issue is fixed with the latest master build.
> > > 
> > > 
> > > Eh , i dont understand . The latest Build is the 0.4.0 right . This is what i have installed .
> > 
> > Do you have the stable or dev build installed? You need the latest dev/master build.
> 
> Means i should choose in Installer the Development Version ? 
> 
> <img width="333" alt="2020-10-16 11_27_04-FlyByWire Downloader v0 5" src="https://user-images.githubusercontent.com/50043259/96241531-94c52a00-0fa2-11eb-84a4-0a49dc31109d.png">
> 

Right :)

**Comment by SM-396** [comment]
> > > > > This issue is fixed with the latest master build.
> > > > 
> > > > 
> > > > Eh , i dont understand . The latest Build is the 0.4.0 right . This is what i have installed .
> > > 
> > > 
> > > Do you have the stable or dev build installed? You need the latest dev/master build.
> > 
> > 
> > Means i should choose in Installer the Development Version ?
> > <img alt="2020-10-16 11_27_04-FlyByWire Downloader v0 5" width="333" src="https://user-images.githubusercontent.com/50043259/96241531-94c52a00-0fa2-11eb-84a4-0a49dc31109d.png">
> 
> Correct :)

In the Past i have Big Problems with the Development Version . Problems with AP ( Speed, FP follow etc. )

**Comment by ABoldOne** [comment]
> > > > > > This issue is fixed with the latest master build.
> > > > > 
> > > > > 
> > > > > Eh , i dont understand . The latest Build is the 0.4.0 right . This is what i have installed .
> > > > 
> > > > 
> > > > Do you have the stable or dev build installed? You need the latest dev/master build.
> > > 
> > > 
> > > Means i should choose in Installer the Development Version ?
> > > <img alt="2020-10-16 11_27_04-FlyByWire Downloader v0 5" width="333" src="https://user-images.githubusercontent.com/50043259/96241531-94c52a00-0fa2-11eb-84a4-0a49dc31109d.png">
> > 
> > Correct :)
> 
> In the Past i have Big Problems with the Development Version . Problems with AP ( Speed, FP follow etc. ) 

Its your decision. The dev version is a wip version of course.

**Comment by ntlgr** [comment]
I am using the 0.4.0 master release and I have the same problem. This is not a DEV build, the problem exists in the release.

**Comment by ABoldOne** [comment]
> 
> 
> I am using the 0.4.0 master release and I have the same problem. This is not a DEV build, the problem exists in the release.

Please understand. The master build is NOT the stable build. You need to download the latest master build to get it working again NOT the stable build.

**Comment by ntlgr** [comment]
> > I am using the 0.4.0 master release and I have the same problem. This is not a DEV build, the problem exists in the release.
> 
> Please understand. The master build is NOT the stable build. You need to download the latest master/dev build to get it working again NOT the stable build.

Got it, sorry new to github, so I have to download latest master build from https://github.com/flybywiresim/a32nx/releases/download/vmaster/A32NX-master.zip ? is that right?

**Comment by ABoldOne** [comment]
> 
> 
> > > I am using the 0.4.0 master release and I have the same problem. This is not a DEV build, the problem exists in the release.
> > 
> > 
> > Please understand. The master build is NOT the stable build. You need to download the latest master/dev build to get it working again NOT the stable build.
> 
> Got it, sorry new to github, so I have to download latest master build from https://github.com/flybywiresim/a32nx/releases/download/vmaster/A32NX-master.zip ? is that right?

No problem, just saying. Yes thats right. the alternative is to download the flybywire installer and select the dev build.

**Comment by robertmacnair** [comment]
This was resolved, but not yet merged with stable. Simple change to get it working:

https://images-ext-2.discordapp.net/external/ArN7Vf85UE-WZMEQDRS06E80s7Is0YT4sju5m9iN5J8/https/i.imgur.com/f2ynhfuh.jpg

**Comment by desponda** [comment]
Would it be possible to release a minor patch for this? Seems like a big issue

**Comment by Benjozork** [comment]
@SM-396 those problems are in the base game autopilot, which we don't edit. they are pretty random and unpredictable and I can almost guarantee it was a coincidence that you were using the dev version.

**Comment by Benjozork** [comment]
> Would it be possible to release a minor patch for this? Seems like a big issue

This is planned.

**Comment by SM-396** [comment]
Another Question from this Post was where i can find the ZFWCG Value . 
Thanks for answering .

**Comment by ABoldOne** [comment]
> Another Question from this Post was where i can find the ZFWCG Value . 
> Thanks for answering . 
> 

You can find it in the fuel/cargo menu at the same spot where you can find the ATC menu in msfs. If you expand the fuel menu to the right u will see the cg.

**Comment by SM-396** [comment]
> > Another Question from this Post was where i can find the ZFWCG Value .
> > Thanks for answering .
> 
> You can find it in the fuel/cargo menu at the same spot where you can find the ATC menu in msfs. If you expand the fuel menu to the right u will see the cg.

Thanks for the fast answer :-) 
Another question . I let Simbrief create my Flightplan because this is very accurate for all Settings. 
The Result is the Simbrief Flightplan like u see at the Top of my Post. 
When i load this Flightplan in Sim , FS2020 dont know about the calculated ZFW and Block Fuel Values from the Simbrief Plan , right ? 
Only the Waypoints from the Flightplan will oad in Sim i think. 
Is it right that i now have to change in Game over the Fule Menu the Values so that they match with my Simbrief Flightplan ? 
Thanks

**Comment by ABoldOne** [comment]
> > > Another Question from this Post was where i can find the ZFWCG Value .
> > > Thanks for answering .
> > 
> > You can find it in the fuel/cargo menu at the same spot where you can find the ATC menu in msfs. If you expand the fuel menu to the right u will see the cg.
> 
> Thanks for the fast answer :-) 
> Another question . I let Simbrief create my Flightplan because this is very accurate for all Settings. 
> The Result is the Simbrief Flightplan like u see at the Top of my Post. 
> When i load this Flightplan in Sim , FS2020 dont know about the calculated ZFW and Block Fuel Values from the Simbrief Plan , right ? 
> Only the Waypoints from the Flightplan will oad in Sim i think. 
> Is it right that i now have to change in Game over the Fule Menu the Values so that they match with my Simbrief Flightplan ? 
> Thanks

That's up to you. But msfs will not know the values from simbrief. So you need to enter them. The thing is. Simbrief only has an a320 not an a20n so the weight value might be different. I personally look how many fuel I will need for the flight and change the msfs values accordingly.

**Comment by SM-396** [comment]
> > > > Another Question from this Post was where i can find the ZFWCG Value .
> > > > Thanks for answering .
> > > 
> > > 
> > > You can find it in the fuel/cargo menu at the same spot where you can find the ATC menu in msfs. If you expand the fuel menu to the right u will see the cg.
> > 
> > 
> > Thanks for the fast answer :-)
> > Another question . I let Simbrief create my Flightplan because this is very accurate for all Settings.
> > The Result is the Simbrief Flightplan like u see at the Top of my Post.
> > When i load this Flightplan in Sim , FS2020 dont know about the calculated ZFW and Block Fuel Values from the Simbrief Plan , right ?
> > Only the Waypoints from the Flightplan will oad in Sim i think.
> > Is it right that i now have to change in Game over the Fule Menu the Values so that they match with my Simbrief Flightplan ?
> > Thanks
> 
> That's up to you. But msfs will not know the values from simbrief. So you need to enter them. The thing is. Simbrief only has an a320 not an a20n so the weight value might be different. I personally look how many fuel I will need for the flight and change the msfs values accordingly.

Ok, thanks . How you can find out the necessary Fuel for the Flight . Is there an Online Calculator ?

**Comment by SM-396** [comment]
> > > > > Another Question from this Post was where i can find the ZFWCG Value .
> > > > > Thanks for answering .
> > > > 
> > > > 
> > > > You can find it in the fuel/cargo menu at the same spot where you can find the ATC menu in msfs. If you expand the fuel menu to the right u will see the cg.
> > > 
> > > 
> > > Thanks for the fast answer :-)
> > > Another question . I let Simbrief create my Flightplan because this is very accurate for all Settings.
> > > The Result is the Simbrief Flightplan like u see at the Top of my Post.
> > > When i load this Flightplan in Sim , FS2020 dont know about the calculated ZFW and Block Fuel Values from the Simbrief Plan , right ?
> > > Only the Waypoints from the Flightplan will oad in Sim i think.
> > > Is it right that i now have to change in Game over the Fule Menu the Values so that they match with my Simbrief Flightplan ?
> > > Thanks
> > 
> > 
> > That's up to you. But msfs will not know the values from simbrief. So you need to enter them. The thing is. Simbrief only has an a320 not an a20n so the weight value might be different. I personally look how many fuel I will need for the flight and change the msfs values accordingly.
> 
> Ok, thanks . How you can find out the necessary Fuel for the Flight . Is there an Online Calculator ?

In Simbrief you have the Possibility to create an own Aircraft . Now i need the right values . Can u help me for this ? 
<img width="555" alt="2020-10-17 08_55_25-SimBrief com - Virtual Flight Planning Solutions" src="https://user-images.githubusercontent.com/50043259/96330601-b253cb80-1056-11eb-8e8c-857ec4cffca3.png">

**Comment by ABoldOne** [comment]
> > > > > > Another Question from this Post was where i can find the ZFWCG Value .
> > > > > > Thanks for answering .
> > > > > 
> > > > > 
> > > > > You can find it in the fuel/cargo menu at the same spot where you can find the ATC menu in msfs. If you expand the fuel menu to the right u will see the cg.
> > > > 
> > > > 
> > > > Thanks for the fast answer :-)
> > > > Another question . I let Simbrief create my Flightplan because this is very accurate for all Settings.
> > > > The Result is the Simbrief Flightplan like u see at the Top of my Post.
> > > > When i load this Flightplan in Sim , FS2020 dont know about the calculated ZFW and Block Fuel Values from the Simbrief Plan , right ?
> > > > Only the Waypoints from the Flightplan will oad in Sim i think.
> > > > Is it right that i now have to change in Game over the Fule Menu the Values so that they match with my Simbrief Flightplan ?
> > > > Thanks
> > > 
> > > 
> > > That's up to you. But msfs will not know the values from simbrief. So you need to enter them. The thing is. Simbrief only has an a320 not an a20n so the weight value might be different. I personally look how many fuel I will need for the flight and change the msfs values accordingly.
> > 
> > Ok, thanks . How you can find out the necessary Fuel for the Flight . Is there an Online Calculator ?
> 
> In Simbrief you have the Possibility to create an own Aircraft . Now i need the right values . Can u help me for this ? 
> <img width="555" alt="2020-10-17 08_55_25-SimBrief com - Virtual Flight Planning Solutions" src="https://user-images.githubusercontent.com/50043259/96330601-b253cb80-1056-11eb-8e8c-857ec4cffca3.png">
> 

I actually don't know how to calculate the values. You can find the empty weight in the sim. But that's all I know. You could Google the values or ask somebody at the flybywire discord. There are many experts maybe they can help you with this.

**Comment by SM-396** [comment]
> > > > > > > Another Question from this Post was where i can find the ZFWCG Value .
> > > > > > > Thanks for answering .
> > > > > > 
> > > > > > 
> > > > > > You can find it in the fuel/cargo menu at the same spot where you can find the ATC menu in msfs. If you expand the fuel menu to the right u will see the cg.
> > > > > 
> > > > > 
> > > > > Thanks for the fast answer :-)
> > > > > Another question . I let Simbrief create my Flightplan because this is very accurate for all Settings.
> > > > > The Result is the Simbrief Flightplan like u see at the Top of my Post.
> > > > > When i load this Flightplan in Sim , FS2020 dont know about the calculated ZFW and Block Fuel Values from the Simbrief Plan , right ?
> > > > > Only the Waypoints from the Flightplan will oad in Sim i think.
> > > > > Is it right that i now have to change in Game over the Fule Menu the Values so that they match with my Simbrief Flightplan ?
> > > > > Thanks
> > > > 
> > > > 
> > > > That's up to you. But msfs will not know the values from simbrief. So you need to enter them. The thing is. Simbrief only has an a320 not an a20n so the weight value might be different. I personally look how many fuel I will need for the flight and change the msfs values accordingly.
> > > 
> > > 
> > > Ok, thanks . How you can find out the necessary Fuel for the Flight . Is there an Online Calculator ?
> > 
> > 
> > In Simbrief you have the Possibility to create an own Aircraft . Now i need the right values . Can u help me for this ?
> > <img alt="2020-10-17 08_55_25-SimBrief com - Virtual Flight Planning Solutions" width="555" src="https://user-images.githubusercontent.com/50043259/96330601-b253cb80-1056-11eb-8e8c-857ec4cffca3.png">
> 
> I actually don't know how to calculate the values. You can find the empty weight in the sim. But that's all I know. You could Google the values or ask somebody at the flybywire discord. There are many experts maybe they can help you with this.

Many Thanks for your support.

**Comment by SM-396** [comment]
> > > > Another Question from this Post was where i can find the ZFWCG Value .
> > > > Thanks for answering .
> > > 
> > > 
> > > You can find it in the fuel/cargo menu at the same spot where you can find the ATC menu in msfs. If you expand the fuel menu to the right u will see the cg.
> > 
> > 
> > Thanks for the fast answer :-)
> > Another question . I let Simbrief create my Flightplan because this is very accurate for all Settings.
> > The Result is the Simbrief Flightplan like u see at the Top of my Post.
> > When i load this Flightplan in Sim , FS2020 dont know about the calculated ZFW and Block Fuel Values from the Simbrief Plan , right ?
> > Only the Waypoints from the Flightplan will oad in Sim i think.
> > Is it right that i now have to change in Game over the Fule Menu the Values so that they match with my Simbrief Flightplan ?
> > Thanks
> 
> That's up to you. But msfs will not know the values from simbrief. So you need to enter them. The thing is. Simbrief only has an a320 not an a20n so the weight value might be different. I personally look how many fuel I will need for the flight and change the msfs values accordingly. If you are really into this you could create a plane profile that fits the msfs a20n to 100 percent.


Where i can find here the CG ? Thanks again 
<img width="846" alt="2020-10-17 09_49_54-Microsoft Flight Simulator - 1 9 5 0" src="https://user-images.githubusercontent.com/50043259/96331537-4ffec900-105e-11eb-9dc0-01ac938d096a.png">

**Comment by ABoldOne** [comment]
> > > > > Another Question from this Post was where i can find the ZFWCG Value .
> > > > > Thanks for answering .
> > > > 
> > > > 
> > > > You can find it in the fuel/cargo menu at the same spot where you can find the ATC menu in msfs. If you expand the fuel menu to the right u will see the cg.
> > > 
> > > 
> > > Thanks for the fast answer :-)
> > > Another question . I let Simbrief create my Flightplan because this is very accurate for all Settings.
> > > The Result is the Simbrief Flightplan like u see at the Top of my Post.
> > > When i load this Flightplan in Sim , FS2020 dont know about the calculated ZFW and Block Fuel Values from the Simbrief Plan , right ?
> > > Only the Waypoints from the Flightplan will oad in Sim i think.
> > > Is it right that i now have to change in Game over the Fule Menu the Values so that they match with my Simbrief Flightplan ?
> > > Thanks
> > 
> > That's up to you. But msfs will not know the values from simbrief. So you need to enter them. The thing is. Simbrief only has an a320 not an a20n so the weight value might be different. I personally look how many fuel I will need for the flight and change the msfs values accordingly. If you are really into this you could create a plane profile that fits the msfs a20n to 100 percent.
> 
> 
> Where i can find here the CG ? Thanks again 
> <img width="846" alt="2020-10-17 09_49_54-Microsoft Flight Simulator - 1 9 5 0" src="https://user-images.githubusercontent.com/50043259/96331537-4ffec900-105e-11eb-9dc0-01ac938d096a.png">
> 

Sure. Expand this window to the right and you will see it at the top right corner.

**Comment by Aarondodd88** [comment]
The Flybywire Discord would be a better place to have conversations like these, as they will be answered much quicker for you :)

**Comment by SM-396** [comment]
> The Flybywire Discord would be a better place to have conversations like these, as they will be answered much quicker for you :)

Thanks , How i can find the Discord ?

**Comment by Benjozork** [comment]
Closing as resolved and going off-topic.
