### ISSUE TITLE
[BUG]Flap sound continuously playing after shutdown

### ISSUE THREAD

**Issue by James3221** [flybywiresim/a32nx#1394]
**Mod Version**

V0.4.0

**Describe the bug**

The flap sound continuously playing after retracting the flaps when aircraft is in a cold and dark state

**To Reproduce**

start up the aircraft to a state at which you can lower the flaps, drop the flaps all the way, then shut down the aircraft to cold and dark and pull the flaps level back to 0

**Expected behavior**

the flaps should not come up and no sound should play

**Actual behavior**

the flaps did stay down, but the flaps extend/retract sound played non stop and there was no way of reverting this, even after powering on the aircraft and changing all the flap settings.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
i believe this has been an issue from the base game
Is this a problem in the vanilla unmodded game?
i believe so

Discord username (if different from GitHub):
JRH3221

**Comment by hotshotp** [comment]
Thats not a sound bug. That is a game thing, in the game the hydraulic motors work even with engines off. So at cold and dark you can move them and they will sound. This happens on the default aircraft. This will be fixed with the new hydraulic system overhaul coming in the next few weeks.

**Comment by Benjozork** [comment]
@hotshotp I think they mean that the sounds keeps playing forever.

**Comment by hotshotp** [comment]
> @hotshotp I think they mean that the sounds keeps playing forever.

Yes that's how the default works too, it plays forever

**Comment by hotshotp** [comment]
issue doesnt persist anymore, and this shouldnt be a problem now that flaps arent heard in cockpit
