### ISSUE TITLE
[BUG] The aircraft nose points downwards but the FL increases in PFD

### ISSUE THREAD

**Issue by SM-396** [flybywiresim/a32nx#1395]
**Mod Version**
0.4.0. Dev Mode

**Describe the bug**
The Plane is sinking , Nose down , but the FL inceases in PFD. 
Totally strange. 

**To Reproduce**
follow Flightplan . 
5000 was set in AP. 210 Knts speed . Flightplan was active. 

**Expected behavior**
When the Nose wents down the Flightlevel should decrease .

**Actual behavior**
It increases 

![121](https://user-images.githubusercontent.com/50043259/96246116-7bbf7780-0fa8-11eb-8613-7ea74919bd34.jpg)
![122](https://user-images.githubusercontent.com/50043259/96246122-7c580e00-0fa8-11eb-8486-8dac220617e2.jpg)
![123](https://user-images.githubusercontent.com/50043259/96246125-7d893b00-0fa8-11eb-85ca-7c73cf5274bd.jpg)

**Comment by ukflyer** [comment]
so many issues with the base flight model, hopefully the modders here can help :)

**Comment by gti222** [comment]
same problem

**Comment by SM-396** [comment]
> same problem

Which Version of the Mod u use ? Dev or stable ? 
Thanks

**Comment by gti222** [comment]
Stable. 

 

Van: SM-396 <notifications@github.com> 
Verzonden: zaterdag 17 oktober 2020 08:47
Aan: flybywiresim/a32nx <a32nx@noreply.github.com>
CC: gti222 <gti222@onsbrabantnet.nl>; Comment <comment@noreply.github.com>
Onderwerp: Re: [flybywiresim/a32nx] [BUG] The aircraft nose points downwards but the FL increases in PFD (#1395)

 

same problem

Which Version of the Mod u use ? Dev or stable ?
Thanks

**Comment by joniatus** [comment]
You're most likely using the legacy flight model. You need to change to modern flight model in settings

**Comment by gti222** [comment]
Your advice works, thank you very much

 

Gr Gerard

 

Van: joniatus <notifications@github.com> 
Verzonden: zaterdag 17 oktober 2020 14:32
Aan: flybywiresim/a32nx <a32nx@noreply.github.com>
CC: gti222 <gti222@onsbrabantnet.nl>; Comment <comment@noreply.github.com>
Onderwerp: Re: [flybywiresim/a32nx] [BUG] The aircraft nose points downwards but the FL increases in PFD (#1395)

 

You're most likely using the legacy flight model. You need to change to modern flight model in settings

**Comment by SM-396** [comment]
On my side too . Thanks so much . Think you can close this Ticket-.

**Comment by MisterChocker** [comment]
Still relevant?
@Benjozork
