### ISSUE TITLE
[BUG] Opening VFR map causes flight plan to delete

### ISSUE THREAD

**Issue by safes007** [flybywiresim/a32nx#1396]
**Mod Version**

built: 2020-10-15T01:38:50+00:00
ref: refs/heads/master
sha: a72a977f0b5c74eab9396bab64cb16f6cc4c8120
actor: Benjozork
event_name: push

**Describe the bug**
On opening the VFR map, the flight plan as entered into the MCDU deletes. 

**To Reproduce**

1. Bug occurred on a flight from YSSY to BNE while using Self Loading Cargo and vPilot.
2. After entering cruise mode and opening the vfr map I noticed some lag in it opening and the flight plan was no longer visible. On checking the MCDU flight plan page the flight plan had disappeared.

**Expected behavior**

No change of flight plan on opening VFR map.

**Actual behavior**

Flight plan deletes on opening VFR map

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Noticed on first flight on download on this build

Is this a problem in the vanilla unmodded game?
I don't believe so.

Discord username (if different from GitHub):

**Comment by NathanInnes** [comment]
Unable to replicate this issue. Does this still occur for you? @safes007

**Comment by safes007** [comment]
The bug has not occurred for me since thankfully. Must have just been a one off weird thing

**Comment by safes007** [comment]
The bug has not occurred for me since thankfully. Must have just been a one off weird thing

**Comment by Benjozork** [comment]
Closing as resolved
