### ISSUE TITLE
"Autoland not working as intended"[BUG]

### ISSUE THREAD

**Issue by Oberstumfuher** [flybywiresim/a32nx#1398]
**Mod Version**

Last Master
built: 2020-10-16T00:15:31+00:00
ref: refs/heads/master
sha: e08f84b3c7db7767aab2c34c8a90ea059bd1f9fe
actor: lukecologne
event_name: push

**Describe the bug**

I don’t know what’s going on, but the autoland is totally terrible to execute, maybe it’s something from Asobo, I’m using the current version of the A32nx master, the aircraft simply touches the ground, it seems to go into stool and floats, it stays very complicated to control and make it fall into the "nose" of the aircraft. Maybe if you could take a look, using ILS and autolanding, to see what's going on and, who knows, be able to fix it.

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by ElSrJuez** [comment]
I was under the impression FS2020 Neo had really implemented autoland, instead just LOC/GS capture. Because of this, I always disconnected the autopilot @ DH and flared manually, etc.
The Mod does add CATII/III and I think even the LAND annunciator, but the only time I left the plane do its thing, it hit the asphalt as gracefully as a brick would... 

So, I was left under the impression that the mod only tries to improve the ILS indications on the FD cosmetically, but the autoland would have to be implemented by Asobo?

**Comment by Oberstumfuher** [comment]
> I was under the impression FS2020 Neo really hadn't implemented autoland and instead just LOC/GS capture. Because of this, I always disconnect the autopilot @ DH and flare manually, etc.
> The Mod does add CATII/III and I think even the LAND annunciator, but the only time I left the plane do its thing, it hit the asphalt as gracefully as a brick would...
> 
> So, I was left under the impression that the mod only tries to improve the ILS indications on the FD cosmetically, but the autoland would have to be implemented by Asobo?

In the first version of the mod, for version 1.7 of MSFS 2020 the autoland worked perfectly, after the update 1.8 nothing else worked.

**Comment by christertepper** [comment]
Having the same issue- autoland doesn't work at all.  Keeps the plane at last entered altitude and overflies the airport.  Tried multiple times to see if it was my error, but occurred each time since the last update.

**Comment by duchuy265** [comment]
![screenshot_1603129882](https://user-images.githubusercontent.com/58601297/96493185-dc7fd600-126e-11eb-9461-bdbe72b29fff.png)
Speed Error

**Comment by Benjozork** [comment]
This is dependent on both APs working, which is being tracked here: #119
