### ISSUE TITLE
[BUG] MCDU can't edit INIT page

### ISSUE THREAD

**Issue by yeyep** [flybywiresim/a32nx#1399]
**Mod Version**
```
built: 2020-10-16T00:15:31+00:00
ref: refs/heads/master
sha: e08f84b3c7db7767aab2c34c8a90ea059bd1f9fe
actor: lukecologne
event_name: push
```

**Describe the bug**
I can't edit anything on my MCDU init page:

- No from/to (error: not in database). I can't edit/add the FROM field in my F-PLAN.
- Can't enter my FL and ofc no temp calculation
- Can't enter any cost index

**To Reproduce**
1. Have latest dev version (see build info)
2. Start a fresh flight from KSFO to KSAN

**Expected behavior**
I can edit my MCDU init page and also my F-PLAN (FROM).

**Actual behavior**
I can't edit my MCDU init page and can't add/edit any FROM information in the F-PLAN.

**References**
![image](https://user-images.githubusercontent.com/5039883/96270292-bc7cb800-0fcb-11eb-918f-0c504eda4f83.png)
![image](https://user-images.githubusercontent.com/5039883/96270206-a111ad00-0fcb-11eb-8cd8-f57c7abb3222.png)

**Additional context**
I never had any problems with MSFS or this mod before.

Was this working before/when did the issue start occurring?
Everything worked before the latest MSFS patch.

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by wuperguy** [comment]
Getting this as well, something on west coast... KFAT-KSFO did not work, weird

**Comment by chitol** [comment]
I have the same issue.

**Comment by chitol** [comment]
Tried it on 787.  Same issue.  During 1.9.5 patch, they updated KSFO.  I think it screwed up the airport data.  It is not a NX specific issue.  It is a MSFS specific issue.

**Comment by yeyep** [comment]
@chitol I can confirm and in addition I found similar topics in the MSFS forum. I will close the issue and we have to wait for a fix by Asobo.
