### ISSUE TITLE
[BUG] Aircraft icon is not visible in navigation display during flight

### ISSUE THREAD

**Issue by Hitz337** [flybywiresim/a32nx#1402]
**Mod Version**

built: 2020-10-15T01:38:50+00:00
ref: refs/heads/master
sha: a72a977f0b5c74eab9396bab64cb16f6cc4c8120
actor: Benjozork
event_name: push

**Describe the bug**

Aircraft icon is not visible in navigation display during flight.

**To Reproduce**

1. Setup IFR
2. Activate ND
3. Fly aircraft

**Expected behavior**

In the default aircraft, there is an icon in ND corresponding to the aircraft position on route. It should be also present in this mod.

**Actual behavior**

The aircraft icon is not present in ND

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by 2hwk** [comment]
Probably linked with already resolved #1071 aka it's the ADF/VOR switches being moved before adirs is aligned, which triggers an event in the ND which looks for a variable that has not been initialized.

See #1285

**Comment by Benjozork** [comment]
@Hitz337 can you confirm if this is fixed in the latest development version ?

**Comment by Hitz337** [comment]
Hi,
I confirm, the issue has been fixed. I have the following version:
built: 2020-10-15T01:38:50+00:00
ref: refs/heads/master
sha: a72a977f0b5c74eab9396bab64cb16f6cc4c8120
actor: Benjozork
event_name: push

**Comment by CoffeePanda0** [comment]
I am on latest master and this still happens after switching modes on the ND but goes away after a few minutes.

**Comment by BreakerHUN** [comment]
unfortunately as of 2020.10.21 latest build th eissue is still here:
![image](https://user-images.githubusercontent.com/71471788/96652566-7b700500-1337-11eb-8fb7-e52594d607d4.png)

I havent touched the vor switches at all so problem seems to be somewhere else.
