### ISSUE TITLE
[BUG] No checklist item for fuel pumps on

### ISSUE THREAD

**Issue by geoffda** [flybywiresim/a32nx#1405]
**Mod Version**

dev:
built: 2020-10-16T00:15:31+00:00
ref: refs/heads/master
sha: e08f84b3c7db7767aab2c34c8a90ea059bd1f9fe
actor: lukecologne
event_name: push

**Describe the bug**

There is no checklist item to turn on the fuel pumps. I end up turning them on at the "no white lights" checklist step.

**To Reproduce**

1. Follow the various checklists all the way to engine start
2.
3.

**Expected behavior**

A checklist item to turn on fuel pumps. I'm not an A320 pilot and there is a checklist item for "no white lights" (which is where I usually turn on the fuel pumps), but I would assume that there should be a checklist item for this...

**Actual behavior**

No checklist item to turn on the fuel pumps. 

**References**

**Additional context**

Was this working before/when did the issue start occurring?
This has always been an issue in A32NX

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Giorgio1234** [comment]
The turn off white lights checklist item is what turns of the fuel pumps since they are disabled (Turned into white lights) when securing the aircraft.

**Comment by lbaron123** [comment]
Yeah this isn't a bug, there is no checklist item to do specifically with fuel pumps.

**Comment by 2hwk** [comment]
As this is not a bug, closed.
