### ISSUE TITLE
[BUG] Missing a single STAR in the A320 MCDU but not from FS2020 or other Aircraft

### ISSUE THREAD

**Issue by mak60062** [flybywiresim/a32nx#1412]
**Mod Version**

built: 2020-10-16T00:15:31+00:00
ref: refs/heads/master
sha: e08f84b3c7db7767aab2c34c8a90ea059bd1f9fe
actor: lukecologne
event_name: push

**Describe the bug**

Some airports are missing a single STAR. 

For example KCMH has 3 STARS that appear in the FS2020 Menu and on other aircraft. The MCDU on the A320 only displays two of the three of them. 

**To Reproduce**

1. Load KCMH as the destination airport in the MCDU
2. Load the "Arrival to KCMH" page under F-PLN
3. Press the right arrow

**Expected behavior**

BREMN5, GAILL3, and GUNNE4 should appear at selectable STARS. 

Pressing the up arrow should reveal the third STAR. 

**Actual behavior**

BREMN5 and GAILL3 appear. GUNNE4 does not appear. Up arrow does nothing. 

**References**

From Game Menu:
![image](https://user-images.githubusercontent.com/6889399/96308295-1e8bec00-0fd1-11eb-89e3-75d9d70e36e9.png)

From A320 (up and down arrow does nothing)
![image](https://user-images.githubusercontent.com/6889399/96307245-5134e500-0fcf-11eb-8c28-11f1e776710c.png)

From TBM
![image](https://user-images.githubusercontent.com/6889399/96307378-82151a00-0fcf-11eb-8a18-37f762bc7c5e.png)

**Additional context**

Possibly related to #1020 which was partially resolved by #1027 

Prior to #1027 no STARs would show up at KCMH, now 2 of the 3 show up. 

I worked with @NathanInnes to determine this appears to be a mod issue. He was able to recreate this issue at another airport. 

Was this working before/when did the issue start occurring?
Has not worked before, as mentioned above prior to #1027 no STARs would show up at KCMH, now 2 of the 3 show up. 

Is this a problem in the vanilla unmodded game?
No STARs appear at all in the vanilla game in the A320. However the STARS do appear on other aircraft and in the menu. 

Discord username (if different from GitHub):
COVID_19_FOX3

**Comment by NathanInnes** [comment]
Issue may be related to NO STAR overwriting the first 3 results and not separating it into another page.

**Comment by efortier-95** [comment]
This is an issue. I wrote #1436 discussing the issue with the arrival page cutting off the end of these arrival/approach/transition lists.
