### ISSUE TITLE
[BUG] Speed Brake Extend/Retract Speed Way Too Fast during Aileron input.

### ISSUE THREAD

**Issue by mak60062** [flybywiresim/a32nx#1413]
**Mod Version**

built: 2020-10-16T00:15:31+00:00
ref: refs/heads/master
sha: e08f84b3c7db7767aab2c34c8a90ea059bd1f9fe
actor: lukecologne
event_name: push

**Describe the bug**

The speed brake extends and retracts almost instantly when any aileron input is added. 

**To Reproduce**

1. Add left or right aileron input
2. Extend or retract the Speed Brakes

**Expected behavior**

Speed brakes should extend or retract at a normal rate (much slower)

**Actual behavior**

Speed brake extends and retracts instantly.

**References**

Normal (No Bank)
https://youtu.be/gblP_HR6leE

While Banking
https://youtu.be/Kod6bjTBvXI

**Additional context**

I was told by one of the A320 pilots in Discord that the wrong speed brakes are extending while airborne as well. I'm not a pilot so unfortunately I cant tell you the true expected behavior. 

Was this working before/when did the issue start occurring?
No. Always. 

Is this a problem in the vanilla unmodded game?
Yes

Discord username (if different from GitHub):
COVID_19_Fox3

**Comment by donstim** [comment]
Used for roll control, they are called spoilers. According to an A320neo FCOM, the 4 outboard (out of 5 total) spoilers on each wing are used along with the ailerons for roll control. The maximum deflection of the ailerons is 25 degrees, while the maximum deflection of the spoilers is 35 degrees.

**Comment by derl30n** [comment]
I am unable to reproduce.
