### ISSUE TITLE
[BUG] Upper ECAM message doesn't reset after TOGA on ground

### ISSUE THREAD

**Issue by pepperoni505** [flybywiresim/a32nx#1416]
**Mod Version**

Release 0.4.0

**Describe the bug**

A bit of a weird bug, if you are sitting at the gate and put the throttle in the TOGA position, the upper ECAM will display warnings, but when you put the throttle back to idle, it won't clear those until takeoff. I assume this is a bug, since you would want to see any ECAM messages before taking off.

**To Reproduce**

1. Spawn in at a gate cold and dark
2. Start up the plane up until after the APU is started
3. Set the throttle to TOGA
4. Set the throttle to idle
5. Pushback/taxi and you will notice the warning doesn't go away

**Expected behavior**

The expected behavior would be the warning would go away eventually

**Actual behavior**

The ECAM warning never went away until after TOGA again on takeoff

**References**

![image](https://user-images.githubusercontent.com/49950581/96325532-915b8e00-0ff6-11eb-8157-fc1b69ba4086.png)

**Additional context**

Was this working before/when did the issue start occurring?
I have no idea, but I've tested this a few times and it happens every time.
Is this a problem in the vanilla unmodded game?
Probably not, as the majority of ECAM messages were introduced in the mod.

Discord username (if different from GitHub): pepperoni505#0001

**Comment by Benjozork** [comment]
I am pretty sure you need to clear the message from the ECAM.

**Comment by pepperoni505** [comment]
I don't see how the correct behavior would be known.

**Comment by Benjozork** [comment]
> I don't see how the correct behavior would be known.

We have the necessary documents. I will share a screenshot when I find something.

The FWC, and specifically message priorities, is not really modeled yet. We have very extensive documentation about it - but we have not figured out an efficient way to model it yet.

**Comment by pepperoni505** [comment]
Ah, ok.

**Comment by pepperoni505** [comment]
Yeah I was not sure why I opened this - I completely forgot about the clear warning button
