### ISSUE TITLE
[BUG] Flashing ECAMs, PFDs, and NDs at night

### ISSUE THREAD

**Issue by Flyguy224** [flybywiresim/a32nx#1418]
**Mod Version**

Master

**Describe the bug**

Flashing ECAMs, PFDs, and NDs at night where the screen stays on, but the ambient light seems to strobe. 

**To Reproduce**

1. Turn on ECAMs, PFDs, and NDs at night
2.
3.

**Expected behavior**

Ambient light thrown off should remain steady

**Actual behavior**

Strobing effect. 

**References**

https://youtu.be/jFppc81hF_g

**Additional context**

Was this working before/when did the issue start occurring?

Tonight

Is this a problem in the vanilla unmodded game?

No. 

Discord username (if different from GitHub):

@Justin 001#8961

**Comment by Benjozork** [comment]
Fixed in latest stable release and master😄 Let me know if updating works for you.

**Comment by estebanbouza** [comment]
@Benjozork I just pulled from master and can see the flashing lights still. Steps to reproduce:
- Pull from master
- Run python build.py
- Copy built assets into Community folder
- Start flight on runway
- See flashing screens in the cockpit.

**Comment by Benjozork** [comment]
Have you deleted the mod folder before copying ?
