### ISSUE TITLE
[BUG] Autopilot does not fly commanded speed for constant Mach climb/descent

### ISSUE THREAD

**Issue by donstim** [flybywiresim/a32nx#1422]
**Mod Version**
master
built: 2020-10-17T02:56:44+00:00
ref: refs/heads/master
sha: 8675df0eedca8320e8f22ed1aa50bb4ba8db2a60
actor: Benjozork
event_name: push

**Describe the bug**
When flying a constant Mach descent in open descent mode, the autopilot maintains a constant speed (whereas the KCAS for a constant Mach increases as altitude decreases) well below the bugged PFD speed.

Conversely, when flying a constant Mach climb, the autopilot commands a speed higher than the bugged speed.

When descending at a constant Mach number using selected speed and selected altitude mode (i.e,, open descent) the autopilot holds a speed well below the selected speed. See screenshot 137, where M0.78 has been set in the FCU, the speed bug is at about 261 KCAS in the PFD, but the autopilot is holding a speed of around 249 KCAS at an altitude of about 35,700 feet. As the airplane descends, and the KCAS for M0.78 increases, the autopilot continues to fly at an airspeed of less than 250 KCAS. See screenshot 138, where the bugged speed is around 273 KCAS for an altitude of around 33,700 feet.

Conversely, when climbing at a constant Mach number, the autopilot holds an airspeed above the selected speed. See screenshots 141 and 142.
![Screenshot (137)](https://user-images.githubusercontent.com/70166617/96329835-59a81280-1005-11eb-8fcd-f8d977e4536c.png)
![Screenshot (138)](https://user-images.githubusercontent.com/70166617/96329839-688ec500-1005-11eb-96de-c99a203fb87a.png)
![Screenshot (141)](https://user-images.githubusercontent.com/70166617/96329844-6cbae280-1005-11eb-8f86-927c30977ec4.png)
![Screenshot (142)](https://user-images.githubusercontent.com/70166617/96329848-72b0c380-1005-11eb-8d43-efb118b77677.png)

**To Reproduce**

1. Set a clear weather ISA day 
2. Takeoff and climb in the A320 to 39,000 feet (at a weight for which that altitude can be easily reached - I used the default weight settings that resulted in a takeoff weight of around 134,000 lb). 
3. Put an altitude of 29,000 feet, a speed of M0.78, and the current heading in the FCU. 
4. Select selected heading, speed, and altitude modes under autopilot/autothrust control. 
5. Note where airspeed bug is placed in the PFD and what speed the autopilot maintains. 
6. Level off at 29,000 feet and note what speed is maintained. 
7. Put an altitude of 39,000 feet and verify a speed of M0.78 is still in the FCU. 
8. Again select selected speed and altitude modes and continue in selected heading mode. (It should not be necessary to re-select the selected speed mode, but when I did this, the speed at the end of step 6 remained at the lower speed used during the descent, well below the FCU speed of M0.78) 
9. Note the speed maintained by the autopilot during the climb compared to the bugged speed on the PFD.

**Expected behavior**
I expected the autopilot to maintain the selected constant Mach number speed selected on the FCU and displayed as the bugged speed in the PFD.

**Actual behavior**
See above

**References**
Included above

**Additional context**

Was this working before/when did the issue start occurring?No, this is a problem in the vanilla unmodded game. I have put in the same bug report in Zendesk, but am including it here in case you all have a way to fix it first.

Is this a problem in the vanilla unmodded game?Yes

Discord username (if different from GitHub):donbikes#4084

**Comment by SM-396** [comment]
I have the same Problem in Takeoff . 
When i set the Speed to "planed" means press Speed Button then while Takoff i have set 170 Kts . I think this is too low . 
I import my Flightplan from Simbrief . 
I must pull the Speed Selector knob and turn it to 200 for example .

**Comment by MICHER79** [comment]
Hello, any news on this issue? The plane does not mantain the commanded speed
