### ISSUE TITLE
[BUG] Goes to CRZ mode very soon even way below 10 000 ft

### ISSUE THREAD

**Issue by JanMar85** [flybywiresim/a32nx#1424]
**Mod Version**

Master

**Describe the bug**

I put selected speeds into MCDU performance page (for ex. 220 for CLB, 310 for CRZ). Than I take off. Auto throttle on, Autopilot on. It skips the CLB mode very quickly - and then it stops climbing, gains speed to 310, continues climbing because it went to CRZ mode even way below 10 000 ft. (I am not a native english speaker, sorry)

**To Reproduce**

1. Put selected speeds for CLB, CRZ modes into MCDU unit
2. Take off, Autopilot on normaly after take off
3. Observe speed going almost immediately up because the autopilot switched from CLB to CRZ. Observe MCDU display, CRZ mode shown

**Expected behavior**

Change from CLB to CRZ mode when actualy cruizing.

**Actual behavior**

Autopilot changes from CLB to CRZ mode too soon when still climbing.

**References**

-

**Additional context**

Was this working before/when did the issue start occurring?

After last update.

Is this a problem in the vanilla unmodded game?

I dont think so.

Discord username (if different from GitHub):

**Comment by Carter633** [comment]
In the MCDU are you inputting the Flight Level for your cruise altitude?

Also have you kept the departure transition altitude at 10000 in the MCDU?

I've not had the issue you describe so wondering if it's one of the two questions above that may solve it for you unless others report the same issue

**Comment by JanMar85** [comment]
Thank you. That was my fault. Before the last update, it was working automaticaly without inputtin FL I think. But I am not sure. Thanks!
