### ISSUE TITLE
[BUG] pushback tractor lights are visible in cockpit

### ISSUE THREAD

**Issue by JLD95** [flybywiresim/a32nx#1425]
**Mod Version**

0.4.0

**Describe the bug**

pushback tractor lights are visible in cockpit

![2020-10-17 (3)](https://user-images.githubusercontent.com/5894146/96334579-25b70680-1072-11eb-81ac-b5099659199d.jpg)
**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by MMontalto** [comment]
#1190

**Comment by JLD95** [comment]
Ok, thank you
