### ISSUE TITLE
[BUG] Aircraft constantly trimming down upon landing

### ISSUE THREAD

**Issue by janszett** [flybywiresim/a32nx#1426]
**Mod Version**

Latest Master (0.4.0)

**Describe the bug**

Somehow I'm not able to control the plane when hand flying an approach. I can pull the stick back all the way but the trim wheel moves down all the time.

**To Reproduce**

1. let the autopilot intercept LOC and GS
2. Disable autopilot at around 500ft.

**Expected behavior**

The plane maintains the correct attitude after disengaging the AP. Working fly by wire.

**Actual behavior**

The plane is trimming all the time and maybe reaches the maximum nose up position, bit still slams into the ground.

**Comment by billsux** [comment]
Had the same issue at the last 2/4 flights (seems it happens only when plane is heavy). I was able to get back control of the plane by setting the thrust to TO/GA. Seems that there is a problem with the approach speed.

**Comment by janszett** [comment]
Thanks. The payload seems to be the problem indeed. I set the payload to around 90% when I had the problems. Just did a quick test flight with 50% payload and everything worked as expected.

**Comment by Poiuz367** [comment]
I think the trimming of the plane is the result of not enough thrust in managed speed mode on approach. I had this problem in 4 of 6 flights with version 0.4 of the mod. It begins at approx 5'000ft. above ground, 200 knt, and flaps 0, when i select the next lower alltitude. Trim is 100% up and it dives with almost 0 rudderauthority. Manual thrust is the only way out.
After this happens the plane has on the g/s with autopilot on approachmode still not enough thrust. There it dives below the g/s and then the rpm and the speed goes up to 170 for a short climb before it dives again.

**Comment by gti222** [comment]
Had the samen problem;

You're most likely using the legacy flight model. You need to change to modern flight model in settings

Got this advice from Joniatus and for me it worked

**Comment by Poiuz367** [comment]
No, i have set it to modern. Actually because it is kind of random, i don't think it's the flightmodel. Maybe more a autopilot inconsistency on the approach phase. This could have all sorts of reasons...

**Comment by billsux** [comment]
Seems to be a vanilla bug: 
https://forums.flightsimulator.com/t/complete-pitch-loss-during-approaches-in-all-ariliners/304032

**Comment by Oberstumfuher** [comment]
The A320 has the same problem, mainly using autolanding, it is impossible to control.

**Comment by Benjozork** [comment]
This will most likely be fixed with our own fly-by-wire implementation.

**Comment by MisterChocker** [comment]
custom fbw has fixed this, this has been also fixed by flight model improvements
