### ISSUE TITLE
What means the Waypoint "USR" or "USER" ? 

### ISSUE THREAD

**Issue by SM-396** [flybywiresim/a32nx#1427]
In every Flightplan i have on different places an Waypoint called "USR" or "USER" . 
But in Flightplan io dont see this Waypoint . 

Can someone explain me this ? 

Thanks

**Comment by hotshotp** [comment]
> In every Flightplan i have on different places an Waypoint called "USR" or "USER" . 
> But in Flightplan io dont see this Waypoint . 
> 
> Can someone explain me this ? 
> 
> Thanks 

Please only post issues with the mod in the issues sections and ask questions in the discord

**Comment by SM-396** [comment]
How can i use the Discord

**Comment by AlexChesters** [comment]
@SM-396 if you look at the [README](https://github.com/flybywiresim/a32nx#flybywire-a32nx) you will see the Discord button at the top.
