### ISSUE TITLE
[BUG] SAT shows -114° at FL330

### ISSUE THREAD

**Issue by SM-396** [flybywiresim/a32nx#1428]
**Mod Version**
Actual downloadad Master

**Describe the bug**
The SAT shows -114° and the TAT shows -95° 

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by SM-396** [comment]
Is it a normal Value for the temperature at this FL ? I Think not ? Thanks

**Comment by SleutelMan** [comment]
As far as my knowledge of flying goes, it is not. That's almost double of what I normally see on FL390 (FYI: I'm not a pilot, just a simmer ;-)). The ratio between the two values seems to be alright though, if that's any consolation ;-)

**Comment by Benjozork** [comment]
Hello, what MSL temperature did you set in your Weather panel ?

**Comment by asessa1976** [comment]
I noted this problem using rex weather. If i use fs default live weather all temps are ok

**Comment by SM-396** [comment]
> I noted this problem using rex weather. If i use fs default live weather all temps are ok

Correct , i can confirm that . I opend an Ticket on REX Support Site .

**Comment by SM-396** [comment]
This is an REX Weatherforce Problem . Open an Ticket on her Site .
