### ISSUE TITLE
[BUG] Stuttering after turning off and on the FO's PFD and ND

### ISSUE THREAD

**Issue by MapleNAV-TCASFAULT** [flybywiresim/a32nx#1429]
**Mod Version**

Stable and Master.

**Describe the bug**

Once you turn off the FO sides PFD and ND and turn them back on, terrible stutters appear.

**To Reproduce**

1. Turn off the FO PFD and ND when taxiing/when the ADIRS is aligned.
2. Turn them back on and wait till self test ends.
3.

**Expected behavior**

No performance drop should occur.

**Actual behavior**

Really bad stutters occur and flying is almost impossible/very uncomfortable.

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub): ChristopherXie#3904

**Comment by 2hwk** [comment]
Should have been fixed by #4117 as the suspected cause of this issue was thrown out with the old PFD code. If this arises again issue can be reopened.
