### ISSUE TITLE
FMS/MCDU Ident/Status Page not updating

### ISSUE THREAD

**Issue by DraivPro** [flybywiresim/a32nx#1431]
**Is your feature request related to a problem? Please describe.**

No

**Describe the feature you'd like to see implemented**

I know you have started some communication with the Navigraph team regarding collaboration. It would be just great if in the near future your mod could show in MCDU the version of AIRAC installed from navdata navigraph. So that the community will finally get rid of the date 4MAY-4JUL.

**References**

https://forum.navigraph.com/viewtopic.php?f=48&t=10068
https://forum.navigraph.com/viewtopic.php?f=14&t=10830&start=10

**Additional context**

Discord username (if different from GitHub): Draiv#9073

**Comment by MisterChocker** [comment]
please update references

**Comment by tracernz** [comment]
This was fixed some time ago.
