### ISSUE TITLE
[BUG] MCDU Arrivals page - Page scroll constrained by length of left list (arrival/approach selection), ignoring right list (transition selection)

### ISSUE THREAD

**Issue by efortier-95** [flybywiresim/a32nx#1436]
**Mod Version**

Dev version:
built: 2020-10-16T00:15:31+00:00
ref: refs/heads/master
sha: e08f84b3c7db7767aab2c34c8a90ea059bd1f9fe
actor: lukecologne
event_name: push

**Describe the bug**

The Arrival Page scroll up/down is limited by the left list (which lists available arrivals and approach procedures), not by the max of that and the right list (available transitions for selected procedure). As a result, **if the number of transitions exceeds the number of available procedures, transitions further down the list can't be selected**

**To Reproduce**

1. Program a flight plan in the MCDU from KSLC to KSNA
2. Program in the DSNEE4 arrival
3. Try to select the MARUE transition for the arrival by scrolling down the list

**Expected behavior**

Ability to scroll down the list of transitions continues. List on left scrolls up and off the page.

**Actual behavior**

Can't continue scrolling because the left list is at its end.

**References**

Can't scroll past TANDY5 arrival:
![image](https://user-images.githubusercontent.com/56796781/96356725-e1068c00-10c0-11eb-935c-344dc33a540d.png)

**Additional context**

Was this working before/when did the issue start occurring?
I think this has always been an issue?

Is this a problem in the vanilla unmodded game?
Probably. It may explain the numerous reports of missing transitions to certain approaches.

Discord username (if different from GitHub):
Eefoe#0570

**Comment by efortier-95** [comment]
Actually, strange enough, TILLT2 arrival into KSNA isn't available either. Not sure if it's also dropping off the end of the list for some reason because of the added "NO STAR" at the start of the list.

**Comment by efortier-95** [comment]
Same issue observed at CYYZ: The last arrival in the list (VIBLI5) isn't available, but all others are. I suspect it's falling off the list as well because of length issues:
![image](https://user-images.githubusercontent.com/56796781/96357261-b9ff8880-10c7-11eb-9311-272dc60ba073.png)
![image](https://user-images.githubusercontent.com/56796781/96357263-c1bf2d00-10c7-11eb-98b2-320344c11f8c.png)

**Comment by LarrySheen** [comment]
I can't even insert the DEP/ARR section in the INIT page...

**Comment by mak60062** [comment]
This also seems to occur on SIDs with a lot of transitions.

KORD ORD5 SID - A320nx (unable to scroll):
![image](https://user-images.githubusercontent.com/6889399/96373427-59f5fa00-113a-11eb-8603-7292f9bac1f8.png)

KORD ORD5 SID - TBM (Able to scroll):
![image](https://user-images.githubusercontent.com/6889399/96373532-0afc9480-113b-11eb-8052-ae5cffe567b5.png)
