### ISSUE TITLE
[BUG] Can't insert ZFW/ZFWCG

### ISSUE THREAD

**Issue by ProrokC2** [flybywiresim/a32nx#1439]
**Mod Version**
Master

**Describe the bug**
Incorrent format error when inserting ZFW/ZFWCG

**To Reproduce**
1. Try to insert ZFW/ZFWCG (50/25)
2. Incorrect format error pops up
3.

**Expected behavior**
ZFW/ZFWCG values go in

**Actual behavior**
Incorrect format pops up

**Additional context**

Was this working before/when did the issue start occurring? Haven't played for a while, used to work in older versions

Is this a problem in the vanilla unmodded game? Modded

Discord username (if different from GitHub): (UwU)#6969

**Comment by Benjozork** [comment]
Issue is resolved in development build.
