### ISSUE TITLE
[BUG] FMC / Flightplan dont follow the Waypoints - Loose the next WP. 

### ISSUE THREAD

**Issue by SM-396** [flybywiresim/a32nx#1440]
**Mod Version**
Last actual 0.4.0

**Describe the bug**
I set with DIRECT TO an next WP in the FP. 
When the Plane reaches this WP , the next WP on FP dont activate . At this Point no WP is activated. 

**To Reproduce**
Select with DT an Waypoint in active FP. 
When the Plane rech this Point no nex WP is active . 

**Expected behavior**
After an DT the next waypoints should fly one after another . 

**Actual behavior**
The FMC loose completely the next active WP. 

![111111111](https://user-images.githubusercontent.com/50043259/96365196-194caf80-113f-11eb-8e27-f0aaa953a2d6.jpg)

![2222222](https://user-images.githubusercontent.com/50043259/96365194-1782ec00-113f-11eb-8aba-54cd2ee781cf.jpg)

**Comment by SM-396** [comment]
Again , dont follow the Active Flightplan ? What happens there and when did this Problem solved ?!?


![2020-10-24 10_08_25-Greenshot](https://user-images.githubusercontent.com/50043259/97073897-22c39500-15e1-11eb-8337-d893c53263c3.jpg)

**Comment by Benjozork** [comment]
@SM-396, remember that this is a community project carried out by people who are not paid at all. We are planning a re-do of the flight plan page but it's very complex and we are waiting until we understand more how MSFS handles flight plans before working on it.

**Comment by SM-396** [comment]
Hi , 
I understand this . And i understand also that this is not your fault . The guys from Flybywire do an fantastic job. 
But with the behaviour that the Plane dont follow an Flightplan , the flying of the A320 will become very difficult .

**Comment by brandaopj** [comment]
i have this problem too.

**Comment by ahmadjie80** [comment]
me too....hope this fix ASAP...thanks for hard working

**Comment by MisterChocker** [comment]
Seems to be fixed by now
