### ISSUE TITLE
various little issues

### ISSUE THREAD

**Issue by lve0200** [flybywiresim/a32nx#1441]
**Mod Version**

vmasster as of 17 Oct.

**Describe the bug**

As I said, I'm not sure, if these are real bugs:
Applying brakes on Taxi way b4 TO, deletes AutoBrake setting
LDG Lights stays on in ECAM, if switched OFF but not retracted
LDG Lights are rarely updated and don't come back, when switched ON again
No Strobes msg in ECAM

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
n/a in Vanilla

Discord username (if different from GitHub):

**Comment by NathanInnes** [comment]
The auto brake problem has already been reported but do you have references to include for the rest of the behaviours?

**Comment by lukecologne** [comment]
> LDG Lights stays on in ECAM, if switched OFF but not retracted

This is correct: 
![grafik](https://user-images.githubusercontent.com/39596827/96371805-f5e82b80-1163-11eb-8787-251da1e67ffc.png)
Where 00-00-190 is the code for the LDG LT message.

**Comment by Benjozork** [comment]
Please avoid opening bug reports for multiple issues and before confirming behaviour is intended.
