### ISSUE TITLE
[BUG] Incorrect APPR page speed calculation + likely fix

### ISSUE THREAD

**Issue by ohnoitsBlarry** [flybywiresim/a32nx#1442]
**Mod Version**
Release version acquired by installer per Oct 16 2020.

**Describe the bug**
Currently, the VLS and Vapp speeds under the APPR page of the FMGS are calculated incorrectly. 
As it stands, the weight component used in the calculation does not take into account fuel burned during flight, using (ZFW + block fuel) instead of (ZFW + FOB). This results in unnecessarily high calculated approach speeds. 

**To Reproduce**
1. Load up the A320 at any runway with high fuel load, with e.g. 15 tons of fuel loaded.
2. Set up INIT 1 and INIT 2 pages. Enter the correct Block Fuel on INIT 2. 
3. Go to APPR page and note VLS/VApp. 
4. Go back to INIT 2. Enter a significantly lower block fuel, e.g. 3 tons.
5. Go to APPR page. Note significantly lower VLS/VApp speeds.

**Expected behavior**
Speed calculation should take into account the current gross weight, that is of course calculated as Zero Fuel Weight + Fuel On Board. 

**Actual behavior**
Currently, speed calculation takes into account the static sum of Zero Fuel Weight + Block Fuel during the entire flight.

**PROBABLE FIX**
1. Go to A32NX\html_ui\Pages\VCockpit\Instruments\Airliners\A320_Neo\FMC.
2. Open A32NX_FMCMainDisplay.js.
3. Find the getWeight() function; in the version stated above, it is at line 1295. 
4. Add this.updateFuelVars(); as the first step of the function.

This causes the getWeight() function that is called many times throughout the FMGC to update the fuel variables to the current fuel on board.

One issue that -may- arise is that this updates the Block Fuel in INIT 2 whenever you enter a number to the current FOB, or use up any fuel during flight. So your Block Fuel displayed in INIT 2 is pretty much a FOB display now. This is obviously fixing a Thing by breaking another Thing in a sense, but that's just what I was able to cobble together on the quick. I rarely ever use the INIT pages after initial start-up, but I sort of require correct speeds throughout all flight phases, so that's a small trade-off. Needless to say, this also affects F/S/O speeds as well as V1, Vr, V2 speeds, so burning a lot of fuel during long taxi times will correctly reduce your takeoff speed.

I'm perfectly aware there's more elegant solutions to this issue, but for now, this has worked for me. 

Discord username (if different from GitHub): Blarry#3664

![a320bug](https://user-images.githubusercontent.com/70750265/96367567-faeeb000-114e-11eb-8e1f-fbd035a51e3f.png)

**Comment by FlyingCarpet7** [comment]
INIT 2, or INIT B as it’s called, are not accessible after engine start anyway, in the real aircraft that is, so that thats not a problem I would say that FOB is displayed there instead if Blockfuel.

**Comment by ElSrJuez** [comment]
>Needless to say, this also affects F/S/O speeds as well as V1, Vr, V2 speeds, so burning a lot of fuel during long taxi times will correctly reduce your takeoff speed.
Not only that - the VREF/VAPP speed on long-haul changes massively as fuel is burned, and gives totally crazy landing speeds (160+ kn).
