### ISSUE TITLE
[REQUEST] ALTITUDE AND SPEED ENTRY IN CDU

### ISSUE THREAD

**Issue by avgeek132638** [flybywiresim/a32nx#1445]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**

**References**

**Additional context**
where we can add the altitude we need to be at and the speed we need to be at in the cdu

Discord username (if different from GitHub):

**Comment by vlbreda** [comment]
Please check youtube. Plenty of tutorials! Don't bother the developers with this.
