### ISSUE TITLE
Trim as all wrong. Plane flies with a trim of 44 % on cruise. Has to be fixed[BUG]

### ISSUE THREAD

**Issue by SAS649** [flybywiresim/a32nx#1447]
**Mod Version**

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by vlbreda** [comment]
?? Trim is measured in degrees, not %. Latest model has a 2.2 degrees pitch trim up during crz, which is just right.

**Comment by Benjozork** [comment]
Duplicate and issue template not respected

**Comment by SAS649** [comment]
The nose is way to high during cruise using managed mode. The plane use more fuel that way

**Comment by Benjozork** [comment]
Please see #984.
