### ISSUE TITLE
[BUG] when I download it won’t go over the original a320 neo file 

### ISSUE THREAD

**Issue by avgeek132638** [flybywiresim/a32nx#1448]
**Mod Version**

**Describe the bug**
I used to use it and. It would work but now it dosent 

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by nikotina91** [comment]
if you download the master version you have to run build.py I believe, might be wrong.

**Comment by avgeek132638** [comment]
Where would that be found

**Comment by nikotina91** [comment]
![image](https://user-images.githubusercontent.com/43645128/96378717-407e9d80-118e-11eb-94d2-01a3a438b319.png)

its just called "build",  you need python installed to run it.

**Comment by Benjozork** [comment]
It's recommended to either use the installer or the direct download link provided in the README file.
