### ISSUE TITLE
[BUG] Lighting knobs should be continuous 

### ISSUE THREAD

**Issue by Benjozork** [flybywiresim/a32nx#1450]
**Mod Version**

master 1b4e008a

**Expected behavior**

- Knobs are smooth and continuous
- Knobs do not make clicking sound unless turned off

**Actual behavior**

- Knobs are stepped
- Knobs make clicking sound

**References**

danbw9#7028 on Discord

Discord username (if different from GitHub): someperson#4953

**Comment by SeanHanway** [comment]
A similar implementation to how the air conditioning knobs were fixed would probably be well suited to all the lighting knobs.

**Comment by Benjozork** [comment]
I tried that but there are some issues with the template. I'll have a PR coming soon.

**Comment by MisterChocker** [comment]
Status on this?
