### ISSUE TITLE
[REQUEST] Bleeding "Beacon" lights on sharklets

### ISSUE THREAD

**Issue by Aero-3D** [flybywiresim/a32nx#1453]
**Is your feature request related to a problem? Please describe.**

This is not a problem

**Describe the feature you'd like to see implemented**

With the A320 IRL, the beacon lights bleed along the entire length of the sharklets as well as the edges of the wings. What does not exist at present on this MOD.

**References**

![Beacon_320](https://user-images.githubusercontent.com/71601864/96431093-55e1df00-1203-11eb-9a84-c07e18ba5394.PNG)
https://www.youtube.com/watch?v=Gh0SySq3eJo

**Additional context**

No particular context

Discord username (if different from GitHub): MnU

**Comment by marci1229** [comment]
UP!

**Comment by Snapmatics** [comment]
> UP!

Yup, I have posted a preview as well.
