### ISSUE TITLE
[BUG]No text to speech after today's update.

### ISSUE THREAD

**Issue by johnwillimas** [flybywiresim/a32nx#1454]
**Mod Version**

Dev version commit a.m. 19/10 version: 615dd16
**Describe the bug**

ATC does not generate spoken advice. Text advice is still present. Problem exists with both Azure and and Windows Offline text to speech. Pilot calls are generating text to speech correctly.

**To Reproduce**

1. Take off flight LGIR to LGAV
2. Respond to ATC as usual.

**Expected behavior**

1. ATC should be audible.

**Actual behavior**

1. Take off flight LGIR to LGAV
2. Pilot requests and responses can be heard.
3. ATC requests and responses inaudible.

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Yes. Problem only since this a.m.

Is this a problem in the vanilla unmodded game?

No. Seems to work ok with unmodded A320

Discord username (if different from GitHub):

**Comment by johnwillimas** [comment]
Just tried it again and now it's working properly. ????

**Comment by FizbanLP** [comment]
I had the same issue. For what ever reason the ATC Option at the Immersion-Menu was turned down. After turning that on, everything with the ATC works like before. This issue appeared after installing the latest stable version. I took me a few hours to figure it out that the solution was so easy :(

**Comment by Benjozork** [comment]
Closing as resolved.
