### ISSUE TITLE
[BUG] Wind noise sounds like radio static noise

### ISSUE THREAD

**Issue by Villason** [flybywiresim/a32nx#1456]
**Mod Version**
0.4

**Describe the bug**
Airflow noise sounds like radio static noise. Source file: a32nx/src/sound/Originals/SFX/wind.wav

**To Reproduce**
1. Take off

**Expected behavior**
Airflow noise in real life does not sound like static radio noise.

**Comment by Benjozork** [comment]
I'm afraid that since sound realism is more of a subjective thing that is hard to categorize, I would rather have this discussed on the Discord #sounds channel. I don't want to mean your opinion is not taken seriously, but if we discuss this here it will distract from the technical bug fixing.

**Comment by hotshotp** [comment]
> **Mod Version**
> 0.4
> 
> **Describe the bug**
> Airflow noise sounds like radio static noise. Source file: a32nx/src/sound/Originals/SFX/wind.wav
> 
> **To Reproduce**
> 
> 1. Take off
> 
> **Expected behavior**
> Airflow noise in real life does not sound like static radio noise.

Hey! We are currently working on new, much more easy to listen wind sounds. It will come with the better engine sounds and it will sound a lot better.
