### ISSUE TITLE
[BUG] INIT 2 - ZFW not updating after changing the load via MSFS load manager panel

### ISSUE THREAD

**Issue by St54Kevin** [flybywiresim/a32nx#1457]
**Mod Version**

Latest dev version as of 19th Okt 20

**Describe the bug**

When entering ZFW/ZFWCG on Init 2 by just clicking it, then changing the load via the load manager, clicking it again does NOT put in the updated, current values.

**To Reproduce**

1. Load the plane
2. Click the ZFW/ZFWCG LSK on Init 2 to fill in current values
3. Change payload on load manager
4. Click LSK again

**Expected behavior**

I expect new ZFW value to get into the scratchpad

**Actual behavior**

old value gets copied from the LSK line

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
> 0.4.1

There is no such version of the mod. Can you try with the latest development version ?

**Comment by St54Kevin** [comment]
> > 0.4.1
> 
> There is no such version of the mod. Can you try with the latest development version ?

Ups sorry. I AM on lates dev version

**Comment by MisterChocker** [comment]
Is this still an issue in latest master?
cc @Lucky38i

**Comment by wpine215** [comment]
MSFS load manager no longer used, closing.
