### ISSUE TITLE
INIT PAGE no FROM/TO insert [BUG]

### ISSUE THREAD

**Issue by cheechsascha** [flybywiresim/a32nx#1459]
I can't insert a from/to, like KLAX/KLAS at the INIT page. No error appears in the scratchpad. its goes empty after pressing LSK1R to insert it. Nothing appears at FROM/TO. The orange boxes don't change.
 I'm using the last stable version, downloaded October 16th.

greetings
Sascha   

**Mod Version**

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by asenyurt** [comment]
hi @cheechsascha 
i have same issue.
also my vertical speed segments are not working on autopilot panel. but its working i saw on pfd screen when i turn it.. could you test vertical speed segments also ??

**Comment by Benjozork** [comment]
Please respect issue tempate. Will reopen when done.

**Comment by Benjozork** [comment]
@asenyurt please avoid commenting on unrelated issues, make a separate one if needed.
