### ISSUE TITLE
AP disconnect change FMA and APPR mode when established on ILS

### ISSUE THREAD

**Issue by SmithFR** [flybywiresim/a32nx#146]
Happened in the last dev build 

When established on an ILS and disconnecting the autopilot with a keybind the FMA change from SPEED to THR LVR, and G/S to OP DES and on the FCU The APPR mode is disengaged and LOC is engaged

Here is a video of it 

https://youtu.be/BBap9r_d0pE

**Comment by SeaRoll** [comment]
does it happen more than 1 time?

**Comment by SmithFR** [comment]
Yes this is 3rd time the 2 others was on a previous build

**Comment by toffee2000** [comment]
I can confirm this. LAND currently annunciates regardless of AP engagement.

**Comment by AdenFlorian** [comment]
i just did a bunch of testing around this. sometimes it happens and sometimes it doesn't, but it also happens in vanilla.

**Comment by AdenFlorian** [comment]
i also looked into the code, and didn't see anything that might be changing the APPR mode, so might be native code.
