### ISSUE TITLE
[REQUEST] decision height/minimum callouts

### ISSUE THREAD

**Issue by luke-stec** [flybywiresim/a32nx#1461]
**Is your feature request related to a problem? Please describe.**
No

**Describe the feature you'd like to see implemented**
Would like to see decision height and minimums call outs implemented

**References**

**Additional context**

Discord username (if different from GitHub):

**Comment by hotshotp** [comment]
those will be added soon, we have began work on that

**Comment by luke-stec** [comment]
> those will be added soon, we have began work on that

That's awesome to hear! You guys are doing an amazing job and everyone in the community appreciates what you guys are doing!

**Comment by xdega** [comment]
@hotshotp Are you also considering callouts for approaching runways when taxiing, or would that be out of scope?

**Comment by hotshotp** [comment]
> @hotshotp Are you also considering callouts for approaching runways when taxiing, or would that be out of scope?

that isnt a thing on the airbus a320 afaik

**Comment by xdega** [comment]
@hotshotp Here it is in action (although admittedly on an a330) https://www.youtube.com/watch?v=91Uyo4wn-F8&feature=youtu.be&t=840 

It's the Honeywell RAAS, and is apparently an option for both Boeing and Airbus.
Here's a nice rundown of the system: https://www.youtube.com/watch?v=SwaFeVVnnGw

**Comment by hotshotp** [comment]
> @hotshotp Here it is in action (although admittedly on an a330) https://www.youtube.com/watch?v=91Uyo4wn-F8&feature=youtu.be&t=840 
> 
> It's the Honeywell RAAS, and is apparently an option for both Boeing and Airbus.
> Here's a nice rundown of the system: https://www.youtube.com/watch?v=SwaFeVVnnGw

Yeah but RAAS is a very rare option, don't think it's worth the effort of adding it right now
