### ISSUE TITLE
Bugs doing my own livery

### ISSUE THREAD

**Issue by leocb24** [flybywiresim/a32nx#1462]
![image](https://user-images.githubusercontent.com/73149365/96531144-328c5380-1246-11eb-8ce5-b400e6fb4c3a.png)
Hi I was doing my own liveries for A320neo, but I got this issue and some other buttons doesn't work well, any way to fix this?

Thanks!

**Comment by Benjozork** [comment]
Please join our discord, this is for bug reports on the mod only :slightly_smiling_face: 

You are probably including some files (panel.xml comes to mind) that you should not include. Keep additional files to the bare minimum required for the livery to work, otherwise it will break our mod.
