### ISSUE TITLE
[BUG] EMER EXIT LIGHT should be amber

### ISSUE THREAD

**Issue by Pilotutut** [flybywiresim/a32nx#1465]
**Mod Version**
0.4.0

**Describe the bug**
On the overhead panel, in the panel SIGNS, the emer exit light "OFF" should be amber, not white.

**Comment by MMontalto** [comment]
There's a template for reporting a bug.
Several sections are missing.
Change the request, otherwise it cannot be considered.

**Comment by Benjozork** [comment]
Already reported in #956
