### ISSUE TITLE
[BUG] Autopilot seems to "drift" off course

### ISSUE THREAD

**Issue by CoffeePanda0** [flybywiresim/a32nx#1468]
**Mod Version**

built: 2020-10-19T01:09:48+00:00
ref: refs/heads/master
sha: 615dd16c54607b64940718d53b0b050770883f87
actor: Benjozork
event_name: push

**Describe the bug**

In around a third of my flights, the autopilot often seems to miss turns and instead carries on straight. Another issue is that the autopilot may randomly start to drift up to 10-15nm to the right or left of the flight plan. Once you hand fly back onto the correct path and re-engage AP, it seems to work again for a few minutes. NOTE: This only appears to happen in cruise.

The strange thing is, the flight directors show the turn but the autopilot does not follow when this is happening.

**To Reproduce**

1. Do a normal flight with LNAV and VNAV
2. The aircraft will often drift up to 15nm to the right or left of the waypoint
3. Watch the aircraft on high altitude sharp turns, it will start turning and then give up and carry on straight.
4. Hand fly to the path then re-engage, and the autopilot will behave until the next turn when it repeats

**Expected behavior**

The autopilot follows the flight directors

**Actual behavior**

It does not

**References**

**Additional context**

I have talked to 3 friends and messaged people, and the majority of them have had this issue occur on at least one flight with the new A32NX

Was this working before/when did the issue start occurring?
Since the latest asobo update
Is this a problem in the vanilla unmodded game?
I don't believe so

Discord username (if different from GitHub):
obama#6262

**Comment by Benjozork** [comment]
This is an Asobo autopilot issue, requires our own AP implementation. Stay tuned.

**Comment by MisterChocker** [comment]
Adobo AP improved since then, custom ap wip
