### ISSUE TITLE
[BUG] ECAM Bleed page not updating accordingly

### ISSUE THREAD

**Issue by Watsi01** [flybywiresim/a32nx#1469]
**Mod Version**
current master

**Describe the bug**
When APU is running and APU bleed activated, the ECAM bleed page stays on XX (Packs) if the ECAM is switched to the bleed page. When switching to another page and come back, temperatures are shown after a while. Also when inflight and switching to bleed page for the first time, the packs are not at sel temperature but spool up to it

**To Reproduce**

1. Enter cold&dark
2. Go for batteries
3. Either use ext. power or not.
4. Turn the air cond temp to a desired value
5. Start up APU
6. When running, activate APU bleed
7. Right after APU bleed is activated, switch to ECAM bleed page
8. sit there and watch for a while
9. Switch to another ECAM page and then back to bleed (maybe for several times)
10. Inflight (engines running): Just switch from any other ECAM page to bleed (for the first time inflight)

**Expected behavior**
bleed page should update as soon as APU bleed is functional

**Actual behavior**
see above

**References**

**Additional context**

I'm not sure how the IRL behaviour should be. 

Was this working before/when did the issue start occurring?
I think this behaviour was since the bleed page was made working (show some stuff).

**Comment by derl30n** [comment]
Cant reproduce
