### ISSUE TITLE
ADIRS PFD Should take time to align.

### ISSUE THREAD

**Issue by Zyonix007** [flybywiresim/a32nx#147]
Normally it takes like 3 minutes for the pfd to align

**Comment by AdenFlorian** [comment]
I think this might be fixed in dev branch?

This is what the PFD looks like after turning on external power and turning up the brightness knobs, before starting ADIRS alignment:
![image](https://user-images.githubusercontent.com/3533988/91792211-a3b27180-ebda-11ea-8bce-aa9e18550e0f.png)

**Comment by AdenFlorian** [comment]
This is immediately after setting ADIRS to align, so now I think I see what you mean:

![image](https://user-images.githubusercontent.com/3533988/91792551-639fbe80-ebdb-11ea-93c3-b0f50d2bc95c.png)

Is it just supposed to look like it does with ADIRS turned off? Or is it slightly different? Pictures would help of course if available.

**Comment by Zyonix007** [comment]
When the adirs are off the plane should look like the top pic for about 3
minutes before the pfd comes online

The pfd aligns faster than the nd but it still takes time.

**Comment by AdenFlorian** [comment]
@Zyonix007 You mean it should look like the first img for 3 minutes after ADIRS are set to NAV? Then transition to the second img? Does the HDG at the bottom center of the PFD stay like that after that 3 minutes?

**Comment by AdenFlorian** [comment]
Have a fix, it can be tweaked if needed to have control over which parts of the PFD become available at what times. I'm just making it so everything on the PFD is available 3 minutes after starting ADIRS alignment, except for the HDG at the bottom, which will become available once ADIRS has finished aligning.

**Comment by Coralec** [comment]
![image](https://user-images.githubusercontent.com/4960953/92212214-a245ab00-ee5f-11ea-9ab6-13e9fd859002.png)

So I'm still seeing the same performance as from your second screenshot AdenFlorian. I'm not sure the left pfd screen should be displaying like that before the ADIRS is fully aligned. I think we are going to need to get some input from an irl a320 pilot regarding how the pfd behaves during alignment. Regardless, I'm not seeing any changes from your fix.

**Comment by AdenFlorian** [comment]
@Coralec i link to the video that i based the timings off of in my pr. i think i had some chats with pilots in discord that i can link tomorrow

**Comment by AdenFlorian** [comment]
@Coralec here's teh start of the discussion: https://discordapp.com/channels/738864299392630914/747572666780745828/750413489570447451

**Comment by AdenFlorian** [comment]
@Coralec Also, I should've commented on this when I finished my PR:

Based on a video I found, the PFD airspeed, altitude, and VS indicators come on at 18 seconds after beginning alignment, and the attitude indicator 28 seconds after alignment start, then heading once alignment is finished, so that's what I think should be tested.

**Comment by ischmal** [comment]
to be perfectly honest, I really feel like this should be converted into an "opt-in" feature only. 

As much as I respect and appreciate realism, I really don't think the average user enjoys doing absolutely nothing for several minutes at a time sheerly because it's more realistic.

**Comment by Zyonix007** [comment]
No It should be forced on no matter what. If you want easy just fly the
default plane.

Just my 2 cents

**Comment by AdenFlorian** [comment]
@Zyonix007 Please don't force what you want on other people. Having an option to enable quick align shouldn't affect you at all.

**Comment by fourdragons** [comment]
Speaking only for myself, alignment is the second thing I do, and I’m never waiting on them. To many things to do in that time.
