### ISSUE TITLE
[REQUEST] Taxi ribbon leaking into cockpit

### ISSUE THREAD

**Issue by CoffeePanda0** [flybywiresim/a32nx#1471]
**Is your feature request related to a problem? Please describe.**

Not really a big bug and i'm not sure if it's easily fixable so that is why I put it as enhancement instead. 

**Describe the feature you'd like to see implemented**

If you turn on "taxi ribbon" in assistance settings, the taxi arrows leak into the cockpit

**References**

**Additional context**

Discord username (if different from GitHub): obama#6262

**Comment by konjakk** [comment]
My experience is that it's reflection of the blue chevrons on the inside of the windows. Especially noticeable at night. One1E#8499

**Comment by NathanInnes** [comment]
Can you include a screenshot for reference? Also sounds like a base game issue but worth looking into.

**Comment by NathanInnes** [comment]
Here is a suggested mod: https://flightsim.to/file/2373/tiny-taxi-ribbons

**Comment by hotshotp** [comment]
fixed in asobo update
