### ISSUE TITLE
[BUG]Autopilot is to sensitive

### ISSUE THREAD

**Issue by Kimbyeoungjang** [flybywiresim/a32nx#1474]
**Mod Version**
 use master branch(https://github.com/flybywiresim/a32nx/commit/30405b7be9e161077d09617528e40f79fc27eb15)

**Describe the bug**
 I try to test new master version(new crz, climb, descend speed). Speed is so good, but autopilot have a problem

When aircraft descend by autopilot altitude input, aircraft start descend. When reach desire altitude around 1000ft, plane must reduce descend rate gently, but autopilot rapidly pitch up. 

Also, autothrottle behavior is weird. When start descend, autothrottle will reduce engine slowly to idle. But autothrottle sometimes stopped on some point like N1 50% around. It must going idle thrust but sometimes stuck some point.

Sorry about my bad english.

**To Reproduce**

1. On the air
2. Start descend
3. Autothrottle sometimes stuck some point(very slowly going to idle thrust), and autopilot pitch up too rapidly.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Kimbyeoungjang** [comment]
https://youtu.be/u7dPekV76DQ

In this video, autopilot gently pitch up and down but asobo’s autopilot is to rapidly change pitch. I think this is asobo problem. I try to find a wag to solve this autopulot behavior.

**Comment by Benjozork** [comment]
Will have to wait for our custom AP in order to fix this

**Comment by Kimbyeoungjang** [comment]
@Benjozork do you know which file is autopilot's behavior? i try to find on flightsimulator official folder to use reference but i can't find that. 

is custom AP project is already start? or will start further time?

**Comment by Benjozork** [comment]
@Kimbyeoungjang editing the default AP works very badly as we have experimented going that route.

As for the custom AP, it requires the fly-by-wire control system to be complete.

**Comment by MisterChocker** [comment]
Update: will be fixed by custom AP
