### ISSUE TITLE
VDev profile indication

### ISSUE THREAD

**Issue by michaeldinozzo** [flybywiresim/a32nx#1475]
**Mod Version**
v0.4.0

**Describe the bug**
Not a bug but would it be possible to include the green dot for the managed descent? I know VNAV is still work in progress but it would be nice to add this indication as it is very useful when descending to be sure we don't end up holding at a FL for ages (or overshooting the runway!).

**To Reproduce**
Once in the air, start the descent at TOD. No green dot or vertical indication.

**Expected behavior**
Nearing TOD a green dot should appear on the altitude tape of the PFD and the aircraft will attempt to follow it. See references below.

**Actual behavior**
No green dot currently modelled.

**References**
https://youtu.be/u7dPekV76DQ

**Additional context**
n.a.

**Was this working before/when did the issue start occurring?**
n.a.

**Is this a problem in the vanilla unmodded game?**
Of course

Discord username (if different from GitHub): n.a.

**Comment by Benjozork** [comment]
Please use the feature request template next time

**Comment by michaeldinozzo** [comment]
Understood.

**Comment by MisterChocker** [comment]
The Green Dot on the altitude on PFD is the visualization of the VDEVa from PROG Page.
So would be nice to combine this when working on this.
