### ISSUE TITLE
MCDU FROM/TO entering not possible at INIT PAGE [BUG]

### ISSUE THREAD

**Issue by cheechsascha** [flybywiresim/a32nx#1479]
**Mod Version**
0.4.0
built: 2020-10-15T01:38:50+00:00

**Describe the bug**
It's not possible to enter FROM/TO like KLAX/KLAS at INIT Page. After writing KLAX/KLAS in the Scratchpad and then pressing LSK1R the scratchpad clears and the orange boxes stay empty.. 

**To Reproduce**

1. Load up the A320 at any runway or parking position
2. Turn Battery and external power on
3. Align IRS to NAV
4. Open MCDU and choose INIT Page
5. Enter KLAX/KLAS into scratchpad
6. Press LSK1R to enter (nothing happens)

**Expected behavior**
the orange boxes under FROM/TO in the upper right corner should be replaced by KLAX/KLAS

**Actual behavior**
After pressing the LSK1R (when KLAX/KLAS was entered in scratchpad), the scratchpad clears and nothing happens

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Since 0.4.0 update a few days ago

Is this a problem in the vanilla unmodded game?
Yes. Only repaints.

**Comment by Benjozork** [comment]
Do you see "NOT IN DATABASE" in the scratchpad ?

**Comment by cheechsascha** [comment]
NO, Nothing

**Comment by DoctRChaseR** [comment]
Hello.  I did a flight this morning on 0.4.0 and everything was fine.  Tried several times tonight and have this issue now.  I am seeing the "NOT IN DATABASE".

**Comment by cheechsascha** [comment]
NOT IN DATABASE doesn't appear. Scratchpad goes empty.

**Comment by DoctRChaseR** [comment]
> NOT IN DATABASE doesn't appear. Scratchpad goes empty.

I found in another post that some west coast US airports aren't found in database after this last update.  Try a different airport.  SFO is one of the ones affected.  I'm doing SEA-AUS right now and it worked perfect.  SEA-SFO was what I was trying last night.  Maybe LAX or LAS is also affected. Good luck.

**Comment by Benjozork** [comment]
Hello,

This was found to be a game issue with premium airports.

An update to the simulator will hopefully fix this soon.

**Comment by cheechsascha** [comment]
I tried some airports. SEA-AUS didnt't work either. Tested airports in europe also have this issue.
[FROM-TO issue.zip](https://github.com/flybywiresim/a32nx/files/5417518/FROM-TO.issue.zip)
