### ISSUE TITLE
MCDU - Waypoint distance in the list of duplicate waypoints.

### ISSUE THREAD

**Issue by BreakerHUN** [flybywiresim/a32nx#1480]
**Is your feature request related to a problem? Please describe.**
It is a request

**Describe the feature you'd like to see implemented**
When there are more waypoints with same names in the database, and you want to insert into the flight plan, the mcdu will give you a list of waypoints with gps coordinates. On a real MCDU on the right side the distance of the waypoint should be presented to that it is obvious to select the closest (proper) one.

**References**
https://www.youtube.com/watch?v=c7UJlJMJdfk&feature=youtu.be&t=591&ab_channel=320SimPilot
This guy is a real A320 pilot and clearly says that on the right side normally there is the distance from your position.

![mcdubefore-1](https://user-images.githubusercontent.com/71471788/96651647-89248b00-1335-11eb-8867-7ba486f0f90e.png)
![mcduafter-1](https://user-images.githubusercontent.com/71471788/96651650-8a55b800-1335-11eb-828e-6e940a2db392.png)

**Additional context**
N/A

Discord username (if different from GitHub):
BreakerHUN#3986

**Comment by Benjozork** [comment]
Hello,

The "References" section is meant to have references to the real plane - could you please provide that ? Thanks !

**Comment by BreakerHUN** [comment]
https://www.youtube.com/watch?v=c7UJlJMJdfk&feature=youtu.be&t=591&ab_channel=320SimPilot

This guy is a real A320 pilot and clearly says that on the right side normally there is the distance from your position.

**Comment by lousybyte** [comment]
Expected behavior for reference:
![](https://i.postimg.cc/fyWQzzzt/Screenshot-2020-10-27-192050.png)

**Comment by pessip** [comment]
Can you assign this to me?
