### ISSUE TITLE
I currently have three notes: vertical landing speed + defective frame + air speed brake light [BUG]

### ISSUE THREAD

**Issue by welyy55** [flybywiresim/a32nx#1481]
**Mod Version**
a32nx V.4.0.0

**Describe the bug**
Auto pilot  vertical landing path speed + Defective frame + Auto Air speed brake (LOW) light.

**To Reproduce**

1.When descending below 5,000 feet in the landing stage, the auto pilot  will drop sharply to the orange pointer (sharp vertical velocity) that is often repeated when approaching the landing stage below 5,000 feet

2.After installing the version V 0.4.0 , and after running the emulator, the frames go down to more than 20 fps in the main menu (before 95 fps - after 54 fps , and upon entering a trip the frame becomes fixed under 10-23 fps and stutters according to the approach of dense clouds or heavy weather, in the previous version V.3.0.1  I did not encounter that Defect.

3.After take off from the runway the auto speed brake MAX light  go off ,  But after climbing to a height 8000 ft , the low speed brake light up, and I turn it off, but it returns to work again after a few minutes and remains on until I close it.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Hello, please create separate issues for those problems (with the appropriate information in the template, that are currently left out) - it is impossible for us to properly track this way.
