### ISSUE TITLE
All button in Cockpit became inactive (zoom of mouse too)

### ISSUE THREAD

**Issue by multinet33** [flybywiresim/a32nx#1483]
During a flight (see here : https://www.twitch.tv/videos/777112351?filter=archives&sort=time) ALL my button in the cockpit became inactive (see at 1:03+)

**Comment by mark1606** [comment]
Not sure about fix but there is a workaround that worked for me. Click on the atc window and move it around the screen, buttons will become clickable again.

**Comment by CoffeePanda0** [comment]
This bug has been in the sim since the launch. Like Mark says, open the ATC window, resize it. That fixes the issue and it is not linked to the A32NX or the A320 and is a sim wide bug

**Comment by Benjozork** [comment]
Issue does not respect template that is provided.

**Comment by multinet33** [comment]
Thank you all for the tip :)
