### ISSUE TITLE
APU Bleed Pressure Indication

### ISSUE THREAD

**Issue by avtechnician** [flybywiresim/a32nx#1484]
**Mod Version**

v0.4.0

**Describe the bug**

On the APU SD page, the APU Bleed Pressure is indicated immediately even when the ADIRS is still "OFF"

**To Reproduce**

1. On Ground
2. Energize Aircraft Electrical Network
3. Monitor the APU SD page
4. Switch on the APU Master SW
5. Start the APU
6. Observe APU Bleed Pressure Indication

**Expected behavior**

APU Bleed Pressure on the APU System Display should show "XX PSI" when the ADIRS is still "OFF" and will only indicate the Bleed Pressure when the ADIRS is activated

The APU bleed will still work normally if the indication are amber "xx"

**Actual behavior**

During APU start-up, I noticed that the APU Bleed Pressure is indicated right-away as soon as it's available, contrary
to the actual behaviour on the real aircraft

**References**

![apu](https://user-images.githubusercontent.com/73177405/96766567-92683300-13db-11eb-9e2e-4f6ff867296c.PNG)

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

avteknisyan

**Comment by Benjozork** [comment]
The reference you gave does mention it gets data from the ADIRS but says nothing about what it should display when ADIRS is off. Could you find a picture / reference for that ?

**Comment by avtechnician** [comment]
Hello, im currently on vacation now so I don't have direct access to the A320

but here's another information,

![apu1](https://user-images.githubusercontent.com/73177405/96918085-0b35c080-14aa-11eb-9bfb-e009b3867e66.PNG)


and here's a link to a video i found on youtube showing APU start-up with the ADIRUS "off"

time stamps

2:52 - APU AVAIL, Bleed Pressure Amber "XX" PSI (Cyan)
3:28 - Shows evidence that ADIRUS are "OFF" thru PFD/ND current state

[](https://youtu.be/Im0OFRxImYw?t=172)
