### ISSUE TITLE
[BUG] AUTO BRAKE MAX setting

### ISSUE THREAD

**Issue by ezanchi** [flybywiresim/a32nx#1485]
**Mod Version**
master

**Describe the bug**
The AUTO BRAKE MAX option should not be available to be armed when in the air.

**To Reproduce**
1. Get airborne
2. Arm the MAX setting of the AUTO BRAKE

**Expected behavior**
The MAX setting should not be able to be armed when airborne.

**Actual behavior**
MAX setting of the AUTO BRAKE system is able to be armed.

**Additional context**
Real life A320 pilot noticed this.

Is this a problem in the vanilla unmodded game?
Yes.

**Comment by NathanInnes** [comment]
Can you include a reference for the described behaviour?

**Comment by ezanchi** [comment]
> Can you include a reference for the described behaviour?

For some reason I can't find any documentation on the specifics of the AUTOBRAKE system, but I am 100% sure the MAX setting can't be armed while airborne.

**Comment by NathanInnes** [comment]
Looking through the FCOM I have, there's nothing to indicate that this is what happens
![image](https://user-images.githubusercontent.com/18389085/97487059-41fd5200-1954-11eb-8b5f-f5f236e6e2e9.png)

**Comment by lukecologne** [comment]
There is actually: 
![grafik](https://user-images.githubusercontent.com/39596827/97487640-67428e00-195d-11eb-854c-38c32043845c.png)

**Comment by NathanInnes** [comment]
Mine says this
![image](https://user-images.githubusercontent.com/18389085/97505980-d4601e80-1971-11eb-91e2-123cc3f2e70c.png)
Which FCOM are you using?

**Comment by ezanchi** [comment]
Is anyone working on this?

> **Mod Version**
> master
> 
> **Describe the bug**
> The AUTO BRAKE MAX option should not be available to be armed when in the air.
> 
> **To Reproduce**
> 
> 1. Get airborne
> 2. Arm the MAX setting of the AUTO BRAKE
> 
> **Expected behavior**
> The MAX setting should not be able to be armed when airborne.
> 
> **Actual behavior**
> MAX setting of the AUTO BRAKE system is able to be armed.
> 
> **Additional context**
> Real life A320 pilot noticed this.
> 
> Is this a problem in the vanilla unmodded game?
> Yes.

**Comment by ezanchi** [comment]
Is anybody able to fix this?

**Comment by MrMinimal** [comment]
Fixed in https://github.com/flybywiresim/a32nx/pull/1762

Verified just now on master 5e57e8dd9fbcf3cbbefd119606df2576da85bd7e
Works as advertised! Close?

**Comment by ezanchi** [comment]
> Fixed in #1762
> 
> Verified just now on master [5e57e8d](https://github.com/flybywiresim/a32nx/commit/5e57e8dd9fbcf3cbbefd119606df2576da85bd7e)
> Works as advertised! Close?

I tested the latest Dev version and it still lets the pilot arm the MAX setting while airborne. So not really.

**Comment by ezanchi** [comment]
> Fixed in #1762
> 
> Verified just now on master [5e57e8d](https://github.com/flybywiresim/a32nx/commit/5e57e8dd9fbcf3cbbefd119606df2576da85bd7e)
> Works as advertised! Close?

Yes it now works as it should. Thank you!
