### ISSUE TITLE
[REQUEST] New default cockpit view / seat position

### ISSUE THREAD

**Issue by St54Kevin** [flybywiresim/a32nx#1486]
**Describe the feature you'd like to see implemented**

Default seating position is way too low and too far back. I would like to see the default cockpit view/seat position to be adjusted according the real seat flight position. Like the screenshot below. I adjusted to match with the seating position balls in the middle. Glareshield model is a bit off, thats why I couldnt put it like I do IRL. But this is a way better and more realistic view onto the instruments

**References**

Before
![image](https://user-images.githubusercontent.com/448627/96786212-3cea5100-13f0-11eb-980f-d13c8ed9b962.png)
After
![image](https://user-images.githubusercontent.com/448627/96786300-5c817980-13f0-11eb-981e-a6d9cab4ce76.png)

**Additional context**

Discord username (if different from GitHub):

**Comment by ZigTag** [comment]
I'll work on this
