### ISSUE TITLE
[BUG]Performance issue over longhaul flight. 

### ISSUE THREAD

**Issue by CityFlightClub** [flybywiresim/a32nx#1492]
**Mod Version**

Master version 10-22

**Describe the bug**

Starting at ground, with FPS 44 outside, and 40 inside.
After takeoff and on route, 30mins, fps drop to 40 outside, and 35 inside.
After 1 hour, fps drop to 35 outside, 30 inside.
After 2 hour, fps drop to 30 outside, 25 inside.
After 2 hour 40 mins before landing, fps drop to 24 outside, 18 inside.

**To Reproduce**

1.Ground at LOWW
2.Fill all route point in MCDU, and finish all process before start
3.Pustback and start, taxi to rwy and take off.
4.At this point have 46 fps outside, and 42 inside.
5.on route, and time pass by, whole flight take almost 2hour40mins.
6.Before landing, on final leg, fps drop to 24 outside, 15~18 inside.
7.Try two times with same route, same result.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by wpine215** [comment]
Can you attempt the same exact flight, under the same weather conditions and time on a fully default A320neo? If there are no lurking variables in this test, it may be evidence a possible memory leak somewhere, and this would help us narrow it down

**Comment by ukflyer** [comment]
Degraded performance over time is a known base game issue where one of the CPU cores gets to 100%. It was discussed in the Q&A developer session..

https://www.youtube.com/watch?v=FZ_ODML7IQc&t=414s

**Comment by c1be** [comment]
Performance goes down over time and also if you load new flight, don't know if it's some conflict with some liveries but with lastest master i get a lot of crashes to desktop without any message, stable version doesn't crash.

**Comment by Benjozork** [comment]
Please fill in the missing information as required by the template:

> Was this working before/when did the issue start occurring?
>
> Is this a problem in the vanilla unmodded game?

**Comment by CityFlightClub** [comment]
Take some tests, at different condition.
It's seemed that ukflyer is right. 
with default A320Neo, with different  weather condition, even I have try TBM930 with different condition. I got the same fps drop over time.
I check the CPU usage, and from core 0 to 7, the core7 always 100%. 
Maybe that's reason cause fps drop.

I didn't notice that with version 1.8.3. just remember with 1.8.3 I can take flight around 2 hours no problem.
And now I upgrade the version 1.9.5.
I try affinitymask, it's not work. Maybe have to wait MS release update.

**Comment by Benjozork** [comment]
Closing as this is a game issue.
