### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Geniickbruch** [flybywiresim/a32nx#1493]
Mod Versin 4.0

**Describe the bug**
My Autopilot doesnt work.

**To Reproduce**

1. I tried to put the Autopilot on and the plane just flies to the right and goes down
2.
3.

**Expected behavior**
I expected the Autopilot to work

**Actual behavior**
The Autopilot was flying to the right and goes down

**References**
i have a video but i cant send it in here 

**Additional context**

Was this working before/when did the issue start occurring? Yes

Is this a problem in the vanilla unmodded game? No 

Discord Username: 🔥𝓖𝓮𝓷𝓲𝓲𝓬𝓴𝓫𝓻𝓾𝓬𝓱🔥#2548

**Comment by CoffeePanda0** [comment]
Does selected heading and altitude work instead of using MCDU waypoints? If you have a waypoint below and to the right the aircraft will fly there. You have to program a flight plan to the MCDU if you wanna use managed heading and altitude

**Comment by Benjozork** [comment]
No response.
