### ISSUE TITLE
[BUG] Absent localization files causing show of MODEL and MANUFACTURER params in UI in different languages except english

### ISSUE THREAD

**Issue by vryzhenkin** [flybywiresim/a32nx#1494]
**Mod Version**

master

**Describe the bug**

Model and manufacturer of A32NX does not shown correctly for any language except english

**To Reproduce**

1. Install mod (Use installer or just drag/drop files)
2. Launch a game
3. Navigate to World Map -> Aircraft -> Liners
4. Look at the Airbus A32NX

**Expected behavior**

Manufacturer and model shown correctly

**Actual behavior**

See the screenshot
![issue](https://user-images.githubusercontent.com/9842424/96861301-f25ee800-1474-11eb-868d-17f859723b19.jpg)

**Workaround/Possible fix**
1. Copy localization files from original ASOBO folder to A32NX folder
2. Edit layout to include files into mod

Was this working before/when did the issue start occurring? Yes, afair in 0.3.1 it worked correctly

Is this a problem in the vanilla unmodded game? No

Discord username (if different from GitHub):
c0updegrace#8661

**Comment by Aesculab** [comment]
> 
>     Copy localization files from original ASOBO folder to A32NX folder
>     Edit layout to include files into mod
>

Confirm that it fixes the issue in the aircraft-selection plane. 

Is there a need to translate former INOP-Buttons for other localization-files / build a localization-table?

**Comment by vryzhenkin** [comment]
> Is there a need to translate former INOP-Buttons for other localization-files / build a localization-table?
Not sure that mod needs it right now. In future - maybe, but it's a good question for project owners.
