### ISSUE TITLE
[BUG] Erroneous distance on PFD

### ISSUE THREAD

**Issue by JLD95** [flybywiresim/a32nx#1495]
**Mod Version**

V0.4.

**Describe the bug**

In following screenshot, distance ti waypoint MAR is erroneous: at 10 Nm circle, displayed 3.2 Nm
![2020-10-22 (7)](https://user-images.githubusercontent.com/5894146/96865335-208afa80-146a-11eb-9f04-ef9cee2fec26.png)

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Oberstumfuher** [comment]
what is the shortest way to a point? The straight, correct? It is marking 3.2 nm due to the fact that the "curve" is the longest path, that is, if you turn to the left it will really be 10 nm, but you need to follow the route, which in this case is the curve, and precisely this curve 3.2 nm

**Comment by JLD95** [comment]
No 5he waypoint is on 10 Nm circle so it is the shortest distance, impossible to have 3 NmLe 22 oct. 2020 14:09, Oberstumfuher <notifications@github.com> a écrit :
what is the shortest way to a point? The straight, correct? It is marking 3.2 nm due to the fact that the "curve" is the longest path, that is, if you turn to the left it will really be 10 nm, but you need to follow the route, which in this case is the curve, and precisely this curve 3.2 nm

**Comment by Benjozork** [comment]
Issue does not respect template

**Comment by Oberstumfuher** [comment]
> A questão não respeita o modelo. Será reaberto quando as informações solicitadas for fornecidas



> Issue does not respect template. Will reopen when requested information is provided




If you take that line from the aircraft to the fixed one and stretch, that line will be 3.2nm.

**Comment by Oberstumfuher** [comment]
> Issue does not respect template. Will reopen when requested information is provided


92/5000
If you take that line from the aircraft to the fixed one and stretch, that line will be 3.2nm.

**Comment by JLD95** [comment]
Not understood, I find10 Nm
![Uploading IMG_20201022_194456.jpg…]()

**Comment by Oberstumfuher** [comment]
> Not understood, I find 10 Nm
> 
> ![IMG_20201022_194456](https://user-images.githubusercontent.com/5894146/96910623-108e0d80-14a0-11eb-8e28-18eff85858fd.jpg)

I will try to explain in a simple way, magine that you are on an avenue with a central flower bed, this "10nm" is a cafeteria that is on the other side of the flower bed on the other side of the street, right? if you want to go there you can’t drive the car over the construction site, you have to follow "the street ahead" to make a contour to get to the other side, right? that way the airways work, you need to follow a path, which is exactly the curve in front of you.

**Comment by Benjozork** [comment]
@Oberstumfuher the curve is visibly longer than 10nm.

**Comment by Oberstumfuher** [comment]
> @Oberstumfuher a curva é visivelmente maior que 10nm.

has the 3.2mn that is marked
