### ISSUE TITLE
[BUG] RMP display blanks out when camera is near

### ISSUE THREAD

**Issue by St54Kevin** [flybywiresim/a32nx#1496]
**Mod Version**

Master as of 22nd of Oct 20.

**Describe the bug**

The display of the RMPs blank out when the camera is located very near it.

**To Reproduce**

1. Use arrow keys to move the camera near the RMP panel. Do not use zoom
2. At a specific distance the RMP display will blank out

**Expected behavior**

Displays stays on.

**Actual behavior**

Display blanks out.

**References**

![image](https://user-images.githubusercontent.com/448627/96865606-7bbced00-146a-11eb-89ca-42a320cf5783.png)
![image](https://user-images.githubusercontent.com/448627/96865649-87101880-146a-11eb-9f8f-023f520a00c3.png)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
idk

Discord username (if different from GitHub):

**Comment by lukecologne** [comment]
Duplicate #717?

**Comment by St54Kevin** [comment]
> Duplicate #717?

Yes i think so

**Comment by lukecologne** [comment]
Alright, I'll close this. This is also likely something Asobo needs to fix.
