### ISSUE TITLE
[BUG] Airplane self-accelerates on the ground

### ISSUE THREAD

**Issue by DraivPro** [flybywiresim/a32nx#1500]
**Mod Version**

Development version

**Describe the bug**

On the latest dev version of the patch, I noticed that the plane accelerates itself, even if the throttle is in the IDLE position

**To Reproduce**

1. Launch the plane
2. Add throttle 5-10 percent for 2-3 seconds. Then move the throttle to the idle position
3. The plane further accelerates itself. even if the brake is applied periodically, it will still accelerate a little, as if the power in the idle position has increased with the new master patch.

**Expected behavior**

I also noticed that in the last master patch, the indication on the screen changed and it ceased to correspond to the power (the circle that should be at the line level) Maybe this is due to this error.

**Actual behavior**

**References**

**Additional context**

![Снимок экрана 2020-10-23 031718](https://user-images.githubusercontent.com/71631760/96943940-31775280-14e2-11eb-9af5-7d00a5bc159a.png)
![2](https://user-images.githubusercontent.com/71631760/96943945-350ad980-14e2-11eb-8800-1ad2a25d1133.png)

Was this working before/when did the issue start occurring?
Yes

Is this a problem in the vanilla unmodded game?  
No

Discord username (if different from GitHub): Draiv#9073

**Comment by Oberstumfuher** [comment]
I just checked this, I did a 2 hour flight, and I noticed this problem mentioned with the stop, the aircraft continues to move only if I apply the parking brakes and release it to stop, but when accelerating again it happens again.

**Comment by 1Revenger1** [comment]
Pretty sure this is intended behavior - it taxies very easily with little thrust in real life.

**Comment by Benjozork** [comment]
This is IRL behaviour with the LEAP-1A engines.

**Comment by Benjozork** [comment]
> I also noticed that in the last master patch, the indication on the screen changed and it ceased to correspond to the power (the circle that should be at the line level) Maybe this is due to this error.

This is also IRL behaviour, as that circle does not follow power but throttle position.

**Comment by Benjozork** [comment]
DraivPro - we will probably tone it down a bit after reports from IRL pilots - but I can confirm the plane does move on idle in real life.
