### ISSUE TITLE
[BUG] Modify STAR without TMP_INSERT modify the aircraft trajectory

### ISSUE THREAD

**Issue by JLD95** [flybywiresim/a32nx#1504]
**Mod Version**

v0.4.0

**Describe the bug**

At cruise level and when aircraft is in straight line, a editing of STAR without TMP_INSERT pressed modifiy the trajectory following by aircraft.

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Issue does not follow template. Will reopen when corrected.

Please cease opening new issues without correcting the information you provide. We cannot realistically figure this out if you don't provide the information we ask for in the template.
