### ISSUE TITLE
[BUG] Aircraft accelerating on ground with 0% Thrust

### ISSUE THREAD

**Issue by CoffeePanda0** [flybywiresim/a32nx#1506]
**Mod Version**

built: 2020-10-22T19:47:10+00:00
ref: refs/heads/master
sha: 6990843773ebc2bd2344ffce395e616b8c52d0be
actor: Benjozork
event_name: push

**Describe the bug**

Once parking brake is released, the aircraft starts accelerating at about 1kt every 3 seconds despite having 0% Throttle and the nose of the aircraft pointed on a slightly uphill runway

**To Reproduce**

1. Taxi
2. Reduce throttle to 0%
3. It carries on accelerating

**Expected behavior**

The aircraft does not accelerate with 0% throttle when going uphill

**Actual behavior**

The aircraft accelerates on taxi despite taxiing uphill+

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Since the new improved aerodynamics update

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub): obama#6262

**Comment by Benjozork** [comment]
Hello, this behaviour is intended. It will be toned down but the real aircraft does accelerate on idle thrust.

**Comment by NovaLogicDev** [comment]
This is an issue that plagues pretty much every aircraft in the game, do you know how was it eventually fixed?
