### ISSUE TITLE
[BUG] Weather radar show clouds instead of precipitations

### ISSUE THREAD

**Issue by TrsCab7** [flybywiresim/a32nx#1508]
**Mod Version**

**Describe the bug**

In Wx and Wx+T mode the weather radar is showing clouds but not precipitations… that makes it useless…

**To Reproduce**

1. Activate your weather radar
2.
3.

**Expected behavior**

Weather radar have to show precipitation, quantity of water in clouds (different from clouds...)

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
We have discussed this and for now we need to come up with our own radar system, which we are not sure how to do as of yet. Stay tuned.

**Comment by TrsCab7** [comment]
Right, thanks for your fantastic job !

**Comment by BigBuddhaJ57** [comment]
Yes, thanks for your work!

Regarding this issue I have some observation. Here is a picture:

![A320-a](https://user-images.githubusercontent.com/78483763/106748971-45c10480-6626-11eb-86c6-7b4f4ee5e311.jpg)

As you can see, the pilot's ND shows a different picture than the Co's side ND. On the Co's side the picture seems to be realistic, only showing denser areas, as well as showing other traffic as TCAS is active. On the pilot's side only the clouds are shown in general and also the traffic is not shown there!
That makes no sense for me, as they should get the same setting from the switches:

![A320-b](https://user-images.githubusercontent.com/78483763/106749339-b10ad680-6626-11eb-9f99-254d0ffde4da.jpg)

Or do I miss anything here like an option what to depict on which side of the cockpit?

Thanks and many greetings

**Comment by 2hwk** [comment]
Fixed in SU4
