### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by madmonkeyfpv** [flybywiresim/a32nx#1511]
**Is your feature request related to a problem? Please describe.**
Quick Start (ctrl+E) when on stand does not setup everything such as ADIRS etc like spawning on a runway.

**Describe the feature you'd like to see implemented**
Using quick start (ctrl+E) sets aircraft up good to go from cold and dark on the stand without forcing a full start real time procedure.

**References**
A320

**Additional context**
I’d like to benefit from all A32NX features but sometimes just want to get going from the stand.

Discord username (if different from GitHub):

**Comment by hotshotp** [comment]
Please respect issue template and put a title

**Comment by hotshotp** [comment]
Ctrl + E is made to start engines, not ADIRS and other functionality

**Comment by madmonkeyfpv** [comment]
yes so is there a way to quick setup everything like when spawning on runway but whilst on stand?

**Comment by hotshotp** [comment]
> yes so is there a way to quick setup everything like when spawning on runway but whilst on stand?

no. but a quick irs align feature will be implemented soon
