### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by neto123456789** [flybywiresim/a32nx#1514]
**Mod Version**
< v. 0.4.0 >

**Describe the bug**
MFD is not displaying route or heading information after alignment of NAV systems. 

**To Reproduce**

1. Started a IFR plan at KLAX to KLAS
2. Turned battery switches on and ext power. 
3. Set NAV alignment on overhead panels
4. After ~7 mins MFS turned on but did not display route or heading info. All settings (ARC, Plan, VOR, etc.) head this issue.
Note: PFD was operational and did display FD, LS, and heading info with no issues.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring? Yes, notice bug on 10/23/2020

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by hotshotp** [comment]
Please put your issue in the title

**Comment by Benjozork** [comment]
Issue does not respect issue template
