### ISSUE TITLE
PFD Transition Altitude Indicator

### ISSUE THREAD

**Issue by Coralec** [flybywiresim/a32nx#152]
The PFD should indicate when the transition altitude that has been set in the MCDU has been reached.

**Comment by PCGamesF1Tech** [comment]
You mean the altimeter setting at the bottom right of the PFD (e.g. 1013 hPa) should start blinking.

**Comment by Coralec** [comment]
Yes

**Comment by arvinjarvin** [comment]
Thanks for raising this issue.

This will be added!
