### ISSUE TITLE
[Fehler]

### ISSUE THREAD

**Issue by Rennradfahrer** [flybywiresim/a32nx#1521]
Im neuesten Update kommt die Call Out Warnung "Don´t Sink" bei jedem Landeanflug mit dem A320. Sinkrate, Geschwindkigeit und Gleitpfad passen. Klappen sind ausgefahren. 

**Mod Version**

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by chkgk** [comment]
Translation of the above report in German:
In the newest update, callout "don't sink" sounds on every approach. Sink rate, speed, and glide path are correct. Flaps are down.

**Comment by vlbreda** [comment]
Did you activate appr-phase in the FMC? Problems occurs for me only when aircraft is spawned on an approach, without flying a complete route.

**Comment by Rennradfahrer** [comment]
The Problem about this Warning is in every landing Situation. Spawned or Full flight. 
🥺

**Comment by MisterChocker** [comment]
@vlbreda this also occurs when below 1000ft radio alt and vertical speed is higher then 1200ft/m.

**Comment by Rennradfahrer** [comment]
VS is 300-400 ft/s

**Comment by Rennradfahrer** [comment]
How can I activate the approch Phase in the fmc by a spowned flight?

**Comment by lukecologne** [comment]
Please add a title, and follow the issue template.

**Comment by vlbreda** [comment]
In a spawned flight, you can't activate the approach phase. That's an Asobo-error.

**Comment by Rennradfahrer** [comment]
Okay, thx a lot

**Comment by bluecew** [comment]
Hello guys, I have this issue too. It does not have to be a spawned flight, I do full flights with the A320 and the "sink rate" callout has happened many times for no reason while doing an ILS approach and following the glidepath correctly.

**Comment by vlbreda** [comment]
@bluecew: did you check that the **appr-phase** was active in the FMC while flying the approach? This happens automatically when passing the DEC-point in your flightplan, but sometimes you have to do it manually (activate appr-phase / confirm activate appr-phase), when the decel-point is 'missed' bij the FMC. It is very import that the plane knows you are in approach-phase, cause it reacts completely different.

**Comment by bluecew** [comment]
Yes, still happens after appr-phase was activated and confirmed in the MCDU (even tried before DECEL). Many times, in fact. I do many long flights and the callout happens sometimes when initially entering the glideslope.

**Comment by Benjozork** [comment]
Issue should be in English.
