### ISSUE TITLE
[BUG] Turning on Logo light disables sound for APU and Eng Fire test

### ISSUE THREAD

**Issue by theersink** [flybywiresim/a32nx#1529]
**Mod Version**
 Dev

built: 2020-10-25T03:41:28+00:00
ref: refs/heads/master
sha: 8794bc11701e452c57480bf1a13eac398d07419d
actor: Benjozork
event_name: push

**Describe the bug**
 If you turn on the Logo light switch and then do the fire tests on the APU or Eng the sound no longer plays. Turn off the light and the sound will play fine

**To Reproduce**

1. Start and flight cold and dark, turn on batts, Ext power
2. Press fire test buttons, sound will play
3. Turn on logo light and try to use the fire tests again and the visual indication works but the sound does not play

**Expected behavior**

Warning tone sound should play when the fire test buttons are pushed

**Actual behavior**

Sound does not play for the eng and apu fire tests when the logo light is turned on

**References**

**Additional context**

Was this working before/when did the issue start occurring? After last PR is when the issue started occurring

Is this a problem in the vanilla unmodded game? N/A

Discord username (if different from GitHub):

**Comment by lukecologne** [comment]
Cannot reproduce on latest master 8794bc11701e452c57480bf1a13eac398d07419d

**Comment by theersink** [comment]
Well, neither can I now. Reproduced 3 times last night. Can be closed. I'll inform if it comes up again
