### ISSUE TITLE
[BUG]Displays Emit Light Despite Not Being On

### ISSUE THREAD

**Issue by ErickSharp** [flybywiresim/a32nx#1530]
**Mod Version**

v0.4.0

**Describe the bug**

The displays emit light that can be seen, although only batteries are turned on and sufficient power from APU or GPU is not provided to support the displays.

**To Reproduce**

1. Select both batteries to 'ON' 
2. Ensure that no APU or ground power is selected
3. Dial-up display lighting

**Expected behavior**

No light is emitted from displays when unable to be powered up.

**Actual behavior**

Light is emitted from displays that you can see on nearby surfaces.
**References**

Here's a video clip I took. I accidentally spawned in on the runway but shut off all the engines and APU. This happens even when you spawn in at a gate.
https://imgur.com/a/jy9KaJV

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by lukecologne** [comment]
Duplicate #1300
