### ISSUE TITLE
[REQUEST] - IRS Quick Align

### ISSUE THREAD

**Issue by madmonkeyfpv** [flybywiresim/a32nx#1531]
**Is your feature request related to a problem? Please describe.**
Enable fast/instant ADIRS Alignment so an immediate departure can be made when spawned anywhere other than a runway

**Describe the feature you'd like to see implemented**
Fast/immediate ADIRS Alignment hotkey

**References**

**Additional context**
Ctrl+E only starts engines but an alternative hotkey or even tieing in to this hotkey to enable fast/immediate ADIRS Alignment for immediate departure when spawning at gate etc. Alternatively option to spawn ready to go and not always cold and dark

Discord username (if different from GitHub):

**Comment by JLD95** [comment]
Hi,
Fast alignment is not available for an adiru that has just been powered on. The fast alignment is used after a landing without power off in order to update adiru velocities and position

**Comment by madmonkeyfpv** [comment]
fully agree in real life it would just be nice to be able to “quick start” on the stand as it is when spawning on a runway. Ctrl+E is only used for engines I know but as it is only used when wanting to make a quick push back, skipping alignment would be very helpful

**Comment by vlbreda** [comment]
Would be a great improvement if you get the choice for a quick alignment. The seven minute wait doesn't add much to the experience, especially since MSFS itself takes a long time to startup. This might be an option: maintain the seven minute countdown, but shorten the 'minutes' to 15 sec.onds each. Realism stays, but a quick depart becomes possible.

**Comment by lukecologne** [comment]
Duplicate #1331. Please look through previous issues before opening a new one
