### ISSUE TITLE
[REQUEST] A320neo have a V1 callout?

### ISSUE THREAD

**Issue by Kimbyeoungjang** [flybywiresim/a32nx#1532]
**Is your feature request related to a problem? Please describe.**

I just wonder that A320neo have a V1 callout when reach V1 speed. 

I find V1 sound on A320neo sound folder.

**Describe the feature you'd like to see implemented**

**References**

**Additional context**

Discord username (if different from GitHub):

**Comment by madmonkeyfpv** [comment]
I’d also like this too

**Comment by doratown** [comment]
Never see a A320 equipped with V1 callout..

But would prefer this as a option, so user can choose to have it turn on or off

**Comment by Kimbyeoungjang** [comment]
I just wonder a320neo have a callout.
Because i find V1 callout sound from sound.xml and a320neo default sound pack

**Comment by Benjozork** [comment]
Hello, GitHub issues are for bug reports. head to discord for questions.

**Comment by hotshotp** [comment]
The a320neo does not have a v1 callout

**Comment by Res72** [comment]
Hi. Sorry, but this is only a comment related to the think that you guys are very expert in this matter. It’s a great curiosity. 
I always use the FBW A32NX on MSFS with FDC Cockpit Live and it’s incredible but if I use the stable version, the copilot calls all the V-Speeds (V1, Rotate, V2), while, if I use the development version, the copilot does not call the only V1 speed, just Rotate e V2. Why?
Kind Regards.
