### ISSUE TITLE
[BUG] F-PLAN says "untitled" when loading in Arrival 

### ISSUE THREAD

**Issue by FSLBRNE** [flybywiresim/a32nx#1533]
**Development Version**

built: 2020-10-25T03:41:28+00:00
ref: refs/heads/master
sha: 8794bc11701e452c57480bf1a13eac398d07419d
actor: Benjozork
event_name: push

**Describe the bug**
I am **not** using Navigraph for planning my flights, so I am just doing it in the world map in game. When I type in the Origin and the Destination Airport, without loading SIDs and STARs everything is fine. The Flight Plan gets loaded correctly in the MCDU. 
But when I'm selecting an Arrival either in the FMS or in the world map, my MCDU says "untitled"

**To Reproduce**
1. Select Origin: EGFF, Destination: EDDB
2. Select IFR (upper airspace) 
3. Change the Departure to "DIRECT" and the Arrival to ILS-25R Z
4. Start the flight.
5. Click on "F-PLAN" in the MCDU. 

**Expected behavior**
MCDU accepts the STAR and adds associated waypoints

**Actual behavior**
MCDU goes to a black page with "UNTITLED" displayed at the top.

**References**
See attachment

**Additional context**
Whatever you are using, the development version or the stable version this Bug appears. 

Was this working before/when did the issue start occurring?
Yes
Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub): flo__#1193
![image](https://user-images.githubusercontent.com/70855713/97106452-08adb380-16c2-11eb-932d-17f8af3d5f5a.png)

**Comment by Seth-Dark** [comment]
Just had the same "untitled" issue while importing Star/arrival during flight from KSEA/KSFO
![a320_issue](https://user-images.githubusercontent.com/72630481/97119834-8e118200-171b-11eb-9f30-63c234622246.jpg)

**Comment by FSLBRNE** [comment]
So, I could fix this issue by downloading the newest airac cycle over navigraph. But for me it also should be possible to load SIDs and STARs without navigraph...

**Comment by Onkelpuh** [comment]
I downloaded the current beta from the mod and still got this error, as soon as you load a route or create it manually you get the empty black page * untitled * in the MCDU

**Comment by Seth-Dark** [comment]
in my situation the "Untitled" issue has to do with Navigraph beta installer and airac cycle. Has nothing to do with A32NX as when i use default navblue flight plans everythng works great. Still investigating as there is a confict between navigraph-A320-F-pln

**Comment by Onkelpuh** [comment]
that's right, I work with navigraph and have loaded the current airac into the sim and will try it right away without it

**Comment by Onkelpuh** [comment]
I just tested it and deleted the navigraph folder from the community folder and it is actually because of this that the flight plan is no longer displayed
We can therefore assume that navigraph has to improve and adapt its tool to the current update

**Comment by Seth-Dark** [comment]
So you have exactly the same issue. For some reason other users dont have it, so i start to believe that has to do with windows/Navigraph installation/ MFS packages. 
When you install navdata airac though Navigraph beta installer is "Installing" button freeze/stuck ?
i need to quit, re-open beta installer and then airac looks installed and placed in Community folder.
maybe this is the issue

**Comment by MICHER79** [comment]
Hello, any update on this? I'm facing the same issue, after selecting the STAR the f-pln plage shows UNTITLED. I'm using Navigraph beta

**Comment by Seth-Dark** [comment]
> Hello, any update on this? I'm facing the same issue, after selecting the STAR the f-pln plage shows UNTITLED. I'm using Navigraph beta

yes after many tests and re-search the only option that worked so far : Uninstall/Re-install MFS
I have all new added airports ( EDDS,LTFM etc) + waypoints + no more "Untitled" on f-pln A320 with Navigraph Airac cycle installed

**Comment by mbobojar** [comment]
I had the same issue today with the latest master branch 2020-11-17T00:49:32+00:00 from commit 7993adf.
I don't use any additional software to plan my flight. 
Today it happened before engine start-up. Not sure when exactly, but my flight plan was already in MCDU, because I planned flight in MSFS world map, as always. 
I tried again after restarting whole MSFS and now it was okay.

**Comment by MisterChocker** [comment]
Can you retry with latest master please?

**Comment by MisterChocker** [comment]
Closing since no response from op.

**Comment by iamjsabz** [comment]
yo..guys still no solution for the mcdu arrival procedure goes to "UNTITLED" .?

**Comment by tracernz** [comment]
> yo..guys still no solution for the mcdu arrival procedure display only "UNTITLED" .?

There is no known issue. If you are experiencing an issue please open a new bug report with precise steps to reproduce it, including whose navdata you are using.

**Comment by Alisayedaa** [comment]
is there any solution to the above issue still I am facing the issue with sim brief arrival destination ???
