### ISSUE TITLE
[BUG] AP disconnect warning sounds 4 times instead of 3

### ISSUE THREAD

**Issue by ntlgr** [flybywiresim/a32nx#1534]
**Mod Version**

**Describe the bug**

The AP disconnect warning is the so-called ‘Cavalry Charge’ and consists of three beeping sounds (AP disconnect warning) followed by three clicks (autoland capability reduced). The AP disconnect warning sounds 4 times instead of 3 (incorrect part). Then 3 clicks follow (correct part)

**To Reproduce**

1. Start a flight
2. Engage AP
3. Disengage AP to trigger the warning.

**Expected behavior**

Three "cavalry charges" followed by three clicks.

**Actual behavior**

Four "cavalry charges" followed by three clicks.

**References**

See this [YouTube video](https://youtu.be/XU3B8Qq1niY?t=2m50s) (at 2:52) from the real aircraft, a cavalry charge immediately followed by a triple click.

**Additional context**

Problem occured since game release, and has not been changed by the mod.

Discord username (if different from GitHub):

**Comment by hotshotp** [comment]
Hello, this behaviour will be fixed later. The behaviour is a lot more complex than you wrote here as there are many more parameters.

**Comment by ntlgr** [comment]
No problem, hope it's okay I reported it.

**Comment by ntlgr** [comment]
Keeping open for tracking until addressed at a later date.

**Comment by ntlgr** [comment]
surprising that a year later this still hasn't been corrected.

**Comment by Benjozork** [comment]
@ntlgr Your contributions towards fixing the issue are more than welcome.

**Comment by hotshotp** [comment]
fixed in latest sound update

**Comment by ntlgr** [comment]
Not sure why this attitude @Benjozork? Is this section not for reporting issues?
If someone does find an issue, you don't wanna hear it, he's better correct it himself?
On the subject, I'm not an audio file expert let me know what I need to learn and I'll fix it.

**Comment by Benjozork** [comment]
On the contrary, we do want issues to be reported.

However phrasing like "surprising that a year later this still hasn't been corrected." just sounds demanding to me. This is a project done by volunteers.

Anywho, this is off topic.
