### ISSUE TITLE
[BUG] it always crashes on climb out or during flight 

### ISSUE THREAD

**Issue by avgeek132638** [flybywiresim/a32nx#1537]
**Mod Version**

**Describe the bug**
when either climbing out of an airport the sound stutters and it crashes or it just crashes during a flight 

**To Reproduce**
just manually set up the fmc then take off and passing 10000 the sound will stutter and then the game will crash.or just flying the aircraft and it crashes 

1.I took off from Houston to Orlando and it just crashed 
2.I was flying from kmsp-kmia and when trying to contact Memphis center it just crashed 
3.

**Expected behavior**

To change frequency’s and just to be able to fly the aircraft 

**Actual behavior**

It just crashed and when I tried again it just crashed 

**References**

**Additional context**
I think it may have to do with the new update 

Was this working before/when did the issue start occurring?last night but it worked before the new update 

Is this a problem in the vanilla unmodded game?yes it is in the unmodded game 

Discord username (if different from GitHub):

**Comment by hotshotp** [comment]
could not reproduce

**Comment by avgeek132638** [comment]
Yes I figure it out my sound was in full and I had a mod I downloaded in between it working and not working and I deleted that and it worked so thanks
