### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by killerbsting16** [flybywiresim/a32nx#1540]
auto pilot is turning off course
**Mod Version**

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Does not respect issue template.

**Comment by hotshotp** [comment]
Please respect issue template 😤
