### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by killerbsting16** [flybywiresim/a32nx#1541]
**Mod Version**

**Describe the bug**
Hey everyone, I have been flying with a32nx for some time now, great aircraft by the way, I have not ran into any issues until now, I set up settings inside the aircraft just like i always do but when i turned on the auto pilot aircraft turns left off course about 5 degrees.

**To Reproduce**
Load flight plan
Turn on FD
Turn on auto throttle
set heading
load ils into fmc
takeoff 
turn on auto pilot.

1.Randomly 
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
You still didn't respect the template, but anyway

Did you set your deadzones to at least 10% ?  Tiny erratic inputs from your stick can throw off AP without disconnecting it.

**Comment by killerbsting16** [comment]
i was almost positive that was going to be it but i just tried adjusting those settings, didnt change anything, so I unplugged my joystick and then tried AP again still turning left off course

**Comment by Benjozork** [comment]
Please come into our discord so we can try basic troubleshooting steps

**Comment by killerbsting16** [comment]
how do I

**Comment by Benjozork** [comment]
https://discord.gg/flybywire

**Comment by killerbsting16** [comment]
how do i find you in discord im in your discord what channel

**Comment by Benjozork** [comment]
#chat
