### ISSUE TITLE
All buttons freeze on approach

### ISSUE THREAD

**Issue by BROADACRES16xFS17MAP** [flybywiresim/a32nx#1542]
**Mod Version**

A32NX-master.zip

**Describe the bug**
On final approach into YSSY 16R and **all** buttons inside aircraft became unusable. Could still utilise the yoke and throttles and flaps etc moved on yoke input however all other buttons froze. The mouse would remain as a pointer and not change.

**To Reproduce**

1. As above
2.
3.

**Expected behavior**

Buttons to work as expected

**Actual behavior**

As above

**References**

**Additional context**

Was this working before/when did the issue start occurring? U/K (second flight using this mod.)

Is this a problem in the vanilla unmodded game? Yes

Discord username (if different from GitHub):

**Comment by MattPaxtonBel** [comment]
Had the same behaviour only once before take-off out of LFKJ, was unable to reproduce. I rebooted my PC and restarted MSFS and all was back.

**Comment by JoeTheOx** [comment]
Had this happen a while back. Opening the VFR map and resizing it seemed to fix the problem.

**Comment by lukecologne** [comment]
Also works with the ATC window (maybe with all windows, not sure), it's a weird bug from asobo.

**Comment by hotshotp** [comment]
This is an asobo bug. Click on the ATC window and go back to the airplane and all buttons will work

**Comment by Pross** [comment]
I find that going to an external view and right clicking a couple of times fixes it for me.
