### ISSUE TITLE
[BUG] Missing airplane symbol on CPT ND

### ISSUE THREAD

**Issue by L-1011** [flybywiresim/a32nx#1543]
**Mod Version**
0.4.0 Stable

**Describe the bug**
The airplane yellow symbol (cross) is missing on Captain Navigation Display (ARC mode)

**To Reproduce**
in all conditions simple plan and start a flight
![1](https://user-images.githubusercontent.com/70903455/97180720-b2f90a00-179a-11eb-80af-48d6a1d8d0a5.JPG)

Discord username (if different from GitHub): L-1011

**Comment by Ash624** [comment]
Yep, I have this too on the captains side only. Starts off ok then disappears mid flight.

**Comment by pickels98** [comment]
I have this too in the last master version. It reappears  by turning to plan mode and back to arc mode.

**Comment by ntlgr** [comment]
I am using a master build post-0.4.0 release and the symbol appears fine.

**Comment by Carter633** [comment]
Current workaround is to flick ND mode to PLAN, then after a second back to ARC or whatever, but I believe it's a known bug

**Comment by MisterChocker** [comment]
Does this still happen on latest master or stable (0.5.1)

**Comment by BritishAvgeek** [comment]
I just checked my stream from yesterday for an ILS into KORD and yes the magenta line was totally obscuring the "airplane symbol" for me. Odd as it's not an issue on VOR (which is what I've been doing a lot of lately). But for me streaming yesterday - just watched it back - the line does still overlay

**Comment by ThatRedMelon** [comment]
This original issue (not the LS obscuring the icon) should be fixed by #2468

**Comment by MisterChocker** [comment]
okay closing then, for the airplane symbol being overlapped, I suggest open a new issue in order to get that fixed.
