### ISSUE TITLE
[BUG] LOG SCREEN APPEARS AFTER ENGINE SHUTDOWN

### ISSUE THREAD

**Issue by H3nr1ks-C0d3** [flybywiresim/a32nx#1545]
**Mod Version**

Newest stable build

**Describe the bug**

Log screen appears directly after Engine shutdown. Usually I would want to take a look at the MFD or clear out the ECAM and set the Aircraft back to mint condition.

**To Reproduce**

1. Land
2. Roll to assigned Gate
3. Turn off Engines (before connecting Jetway)

**Expected behavior**

Session should end when the last source of power has been cutoff. Only if the Aircraft doesnt have any power to go for anymore the session should be ended.

**Actual behavior**

Said this multiple times, but I need to follow this template: Log screen does appear after engine shutdown, while batterys (maybe APU) and External Power are still on.

Was this working before/when did the issue start occurring?
Yes, it was changed in a later build. Always bothered me. I don't know when. Even though Iv'e literally used this mod since the first release, I haven't started reading Documentation and Changenotes since it blew up and got so many great new features. Thanks btw. 👍 🥇 

Is this a problem in the vanilla unmodded game?
Nope

**Comment by Benjozork** [comment]
This is an MSFS bug. Please report it on the Zendesk or official forums.

**Comment by H3nr1ks-C0d3** [comment]
> This is an MSFS bug. Please report it on the Zendesk or official forums.

Sorry man, but before I posted this I wanted to be sure and restarted MSFS without the mod. Problem doesn't appear.

**Comment by H3nr1ks-C0d3** [comment]
> This is an MSFS bug. Please report it on the Zendesk or official forums. We do not and cannot change anything related to the logbook.

So it has to be, or am I missing something?

**Comment by Benjozork** [comment]
We cannot affect that menu. It's functionality inside of MSFS, and what it listens to for appearing is completely unknown. We have no way of fixing this,
