### ISSUE TITLE
[BUG] Airways do not work as expected with a long route

### ISSUE THREAD

**Issue by jamessawle** [flybywiresim/a32nx#1550]
**Mod Version**
master - A32NX-master.zip
built: 2020-10-26T03:15:17+00:00
ref: refs/heads/master
sha: 8ba938f0bfa1c07e1f60ae34c41385507fe4a6e0
actor: Benjozork
event_name: push

Using Navigraph data

**Describe the bug**
The new airway support does not appear to work as expected after 2-3 pages of airways. This is a combination of airways between waypoints missing in the full flightplan and then the airways page clearing upon entry of first airway/waypoint combination on subsequent pages.

**To Reproduce**
1. Start new flight cold and dark
2. Initialise flight between LFBO and OMDB
3. Insert following flight plan

`LFBO/32R AMOL5B AMOLO UT24 FJR UL127 SODRI UM728 DOKAR DCT TAQ DCT PEMAR DCT EKMOT DCT DIVKU DCT ENOXA Y2 PAPIZ DCT PINDO UP14 RIKSO UN127 IMR UN135 VESAR L619 NIKAS R785 KTN A21 TAN G202 PUSTO M203 ILMAP UP975 ULDUR UM688 SIDAD R784 TATLA L223 VUTEB VUTE3C OMDB/ULDOT.R30L`

**Expected behavior**
It should be possible to add a flight of any length and number of airways via the new airway support.

**Actual behavior**
1. After 3 pages of airways, new waypoints do not have airways between them in flight-plan page
2. After another page, after entering first airway and waypoint, the airway and waypoint will disappear off the airway page, but the waypoint and its intermediaries will be added to the flight plan (with airways between them included)
3. This can then be repeated for all subsequent airways (by going to last waypoint in the flight plan once at a time)

Was this working before/when did the issue start occurring?
This started to occur since the new airway support was added yesterday. The functionality is brilliant, especially for shorter flights, but with a couple of corner cases in this longer example.

Is this a problem in the vanilla unmodded game?
No as is related to the new airway support that was added

Discord username (if different from GitHub): sawlo

**Comment by santii90** [comment]
Thanks for the good report it helped me a lot to figure out what was the issue. I have been working on a improvement PR that brings some new features and fixes for this route and another difficult one that should expand the amount of routes suitable for the airways.

Gently remainder that the fix just is correctly displaying the airways and waypoints for the selected waypoint, it not bring pages. So after you complete a page you are going to select another waypoint to continue adding the airways. In your case I recommend selecting the last one.

Thanks again.

**Comment by Carter633** [comment]
I was testing this with a long route EGKK - LGSK the other day prior to merge and worked fine for me though on occasion had to come out back to the flight plan route list and back into airways again but that was the limitations at the time
