### ISSUE TITLE
[BUG] [MCDU] MDA and DH input

### ISSUE THREAD

**Issue by linkeleven** [flybywiresim/a32nx#1551]
version: master

**Describe the bug**

1. Currently booth MDA and DH can be entered at the same time.
2. Values entered in either MDA or DH cant be cleared with CLR or NO

**To Reproduce**

1. Enter MDA and DH on the approach phase page in the MCDU
![mcdu_MDA_DH](https://user-images.githubusercontent.com/57767584/97217820-1ea59c00-17c8-11eb-9592-3b12949f9f06.png)

2. Try to clear the MDA or DH with CLR or entering NO
![mcdu_MDA_CLR_1](https://user-images.githubusercontent.com/57767584/97217867-2bc28b00-17c8-11eb-9678-099bf2f27ea5.png)
![mcdu_MDA_NO_1](https://user-images.githubusercontent.com/57767584/97217883-2feea880-17c8-11eb-9569-91e380c91a46.png)
![mcdu_MDA_CLR_2](https://user-images.githubusercontent.com/57767584/97217905-35e48980-17c8-11eb-88e0-bd6bdcfeca1f.png)

**Expected behavior**

1. Only one value can be entered at the same time
2. If a value for MDA is entered the entry for DH should be cleared and vice versa
3.Entering CLR or NO should clean the entry

**Actual behavior**

**References**

![grafik](https://user-images.githubusercontent.com/39596827/97218959-a63fda80-17c9-11eb-90b0-9c553d5dc333.png)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by paul92ilm** [comment]
Bug also encountered with the unmodded A320
![image](https://user-images.githubusercontent.com/9373163/97238867-abf9e800-17ea-11eb-951f-7b11d26bcb38.png)
Looks like it comes from the shared FMC code for airliners
