### ISSUE TITLE
[BUG] PR #1512 Enhancement -> Hard to read cockpit text at 1080p.

### ISSUE THREAD

**Issue by nreyes90** [flybywiresim/a32nx#1560]
**Mod Version**

Master with merged PR #1512 

**Describe the bug**

At default cockpit view (default spawn in view). Panning around the cockpit a lot of the "upscaled" panels the text is unreadable. 

Relevant In sim settings have render scaling at 100%,Texture Resolution set at "high", Alisasing "TAA", Haven't changed any graphic settings. 

Unsure if there are other relevant settings applicable to cockpit textures. 

**To Reproduce**

1. Load in C&D. 
2. Pan around the cockpit at a 1920x1080 resolution. 
3. Check if you can read panel text without having to zoom in. 

**Expected behavior**

Readable text on panels/controls without zooming in. Essentially in default view for example it's very easy for me to see SPD/MACH or HGD TRK on the FCU. Or on the overhead panel easily read the light swtich texts or APU text without zooming in.

**Actual behavior**

Hard to read / faded out panel/control text. 

**References**

 What I see Currently:
Apologes on the quality of images but essentially it's what I see. 

![FlightSimulator_GB2BEjbWkS](https://user-images.githubusercontent.com/1619968/97261302-82c47080-1859-11eb-965e-7e35b81639e1.jpg)
![FlightSimulator_RSc9yKkxep](https://user-images.githubusercontent.com/1619968/97261310-848e3400-1859-11eb-8d8f-a014c903c0ab.jpg)
![FlightSimulator_kgaptUZDRd](https://user-images.githubusercontent.com/1619968/97261315-8657f780-1859-11eb-8c0e-65f7b8d6b716.jpg)

Older image:

![FlightSimulator_vqy5eTbd9b](https://user-images.githubusercontent.com/1619968/97261422-c5864880-1859-11eb-9de3-2ca29e5ef5a2.jpg)

**Additional context**

I did not have time to try out other settings in the sim but considering I was able to read the text prior to the enhancement PR I figured shouldn't have too. 

Was this working before/when did the issue start occurring?
Yes. No additional liveries / mods / scenery added prior to updating A20NX Dev Branch via installer. 

Is this a problem in the vanilla unmodded game?
Untested.

Discord username (if different from GitHub): Valastiri#8902

**Comment by Benjozork** [comment]
We are working on proper fonts, waiting for when we get close-up screenshots in the actual plane from our engineers.

In the meantime, we decided to compromise readability at lower resolutions when zoomed out for improved legibility and quality when zoomed in.

We can assist in replacing the files with the old version if you want.

**Comment by Watsi01** [comment]
@Benjozork Yes, maybe you could give a tiny howto, if someone likes to replace them please.

**Comment by Pleasure0102** [comment]
[decals_old.zip](https://github.com/flybywiresim/a32nx/files/5443561/decals_old.zip)
download that file, there are 4 files in there, replace the ones you have in Packages\Community\A32NX\SimObjects\AirPlanes\Asobo_A320_NEO\TEXTURE\

Then you have the old ones, we should get the pictures today or tomorrow, then we will rework the text

**Comment by Pleasure0102** [comment]
please keep in mind we won't give any support normally... because the master version is something that changes a lot. If you need further help please pm me for that.

**Comment by nreyes90** [comment]
Ah no worries then. I assumed since nothing changed on my part it was a downsampling issue for us users without 2k capable rigs/monitors. 

And no problem with the support issue I understand the connotations behind the master vs stable, just thought it might be a bug/oversight! 

Closing issue and thanks again. (Great work as usual)
