### ISSUE TITLE
[BUG] Can't assign "strange" altitudes to FMC

### ISSUE THREAD

**Issue by ktechmidas** [flybywiresim/a32nx#1561]
**Mod Version**
Master

**Describe the bug**
China uses it's own "meters" version of RVSM which leads to strange flight levels, examples being FL341/FL351 etc, see the full list from VATPRC here: https://www.vatprc.net/wp-content/uploads/2019/11/China_RVSM-1024x593.jpg

When I attempt to add FL341 in the INIT page on the FMC, it inserts FL340

**To Reproduce**
1. Start at ZSPD
2. Go to the FMC and select INIT
3. Type ZSPD/ZBAA into FROM/TO
4. in CRZ FL type FL341
5. It'll then show FL340 in the FMC instead

**Expected behavior**
FL341 to appear as the CRZ FL

**Actual behavior**
FL340 appears as the CRZ FL

**References**
![image](https://user-images.githubusercontent.com/9920871/97275686-3422d080-1871-11eb-9f36-843e771bd026.png)

Was this working before/when did the issue start occurring?
Never worked

Is this a problem in the vanilla unmodded game?
Seems to be, unfortunately

**Comment by Benjozork** [comment]
You need to provide a reference to the behavior in the real A320 in the "References" section, not a screenshot of the sim.

**Comment by ktechmidas** [comment]
I've been discussing it in #help with other devs on Discord. So I got a reference from there but we're still not certain... Here's the reference, particularly the "Hundred of ft" part in "UNITS"

![datatable](https://user-images.githubusercontent.com/9920871/97304257-73174d00-1896-11eb-95c7-b79c898455ab.PNG)

I also have the fact that the FSL on P3D and the FF on xplane both allow it.... 

![unknown](https://user-images.githubusercontent.com/9920871/97304035-2a5f9400-1896-11eb-9a4a-594ab3350f06.png)
