### ISSUE TITLE
MOD NOT WORKING, EVERYTHING IN PLACE

### ISSUE THREAD

**Issue by Juanlox123** [flybywiresim/a32nx#1566]
As the title states... I've placed the A320X in the correct folder (for steam edition) and it just refuses to work. It was working perfectly fine until the newest release.

**Comment by Benjozork** [comment]
![image](https://user-images.githubusercontent.com/4503241/97314937-91515e80-183e-11eb-8226-bcc93330b4ec.png)

Please join our discord for installation assistance.
