### ISSUE TITLE
[BUG] mcdu performance page QNH only can write number

### ISSUE THREAD

**Issue by Kimbyeoungjang** [flybywiresim/a32nx#1567]
**Mod Version**

**Describe the bug**

When we prepare approach to airport, we set a mcdu performance page, appr phase.
QNH section only can write integer.

**To Reproduce**

1. Open mcde perf page
2. Go to appr phase, write qnh
3. Only can write integer.

**Expected behavior**

Can insert number like 29.92 

**Actual behavior**

When insert 29.92, mcdu just rounds to 30

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
Yes

Discord username (if different from GitHub):

**Comment by komp1821** [comment]
Looks like the QNH is only accepted in hPa. Try 1013 for 29.92 eg. Works for me.

**Comment by lousybyte** [comment]
Expected behavior for reference:
![](https://i.postimg.cc/26FZZw4b/Screenshot-2020-10-27-191218.png)

**Comment by pessip** [comment]
I can do this
