### ISSUE TITLE
[BUG] CG texture on the throttle is misaligned

### ISSUE THREAD

**Issue by Nyxtorm** [flybywiresim/a32nx#1568]
**Mod Version**

built: 2020-10-27T13:04:32+00:00
ref: refs/heads/master
sha: 87324ef670e164a028fd698dbdd95396f9c52943
actor: Benjozork
event_name: push

**Describe the bug**
The texture of the CG on the throttle is misaligned.

**To Reproduce**
1 - Only load a new flight with the A320n with the last revision of a32nx mod and look at the throttle. ;)

**Expected behavior**
```
G  or  C   should be CG
0      2             20
```

**Actual behavior**
The texture is cut.

**References**
![Inkedcapt-throttle-view_LI](https://user-images.githubusercontent.com/20800786/97334300-e3b17000-187c-11eb-9ea8-1cf7b7f6d78e.jpg)
![Inkedfo-throttle-view_LI](https://user-images.githubusercontent.com/20800786/97334314-e6ac6080-187c-11eb-9316-a5345b1d3835.jpg)
![0393544](https://user-images.githubusercontent.com/20800786/97334396-fe83e480-187c-11eb-8853-9890235be625.jpg)

**Additional context**
-

Was this working before/when did the issue start occurring?
Sorry, I don't know

Is this a problem in the vanilla unmodded game?
Same problem with the unmodded A320.

Sorry for my bad English, I'm French.

**Comment by DarkOfNova** [comment]
Yeah known issue, sadly we can't do anything about it at the moment as it has to do with the UV's. On the backlog though

**Comment by DarkOfNova** [comment]
So after some further analysis, it seems as though the collider mesh for the camera is blocking the decals as seen below: 
![Screenshot_73](https://user-images.githubusercontent.com/70452276/97641511-fc678480-1a3a-11eb-8b84-0552b12fb3a3.png)
![Screenshot_74](https://user-images.githubusercontent.com/70452276/97641677-5b2cfe00-1a3b-11eb-85b4-a454460c70c4.png)

I've talked to Luke to see if he can remove it and it might be possible however your camera will be able to clip through the trim wheels which IMO is less important than actually being able to see CG values. Hopefully it works.

**Comment by lukecologne** [comment]
So, I tried hiding the mesh in the model XML, but it doesn't work, the shadow is still there. I still have no idea why this is even happening, and only there on the trimwheel and nowhere else

**Comment by DarkOfNova** [comment]
Weird, it's not logical but it's the only thing that makes sense as you can see above. Will have to have a look again once we have the models I guess.

**Comment by DarkOfNova** [comment]
![Screenshot_76](https://user-images.githubusercontent.com/70452276/98046498-3a412000-1e22-11eb-8825-ed7ac37bb338.png)
@lukecologne did you fix it?

**Comment by lukecologne** [comment]
No, you are seeing it in this screenshot because the integrated lighting is on. It looks to me like the light can pass from inside to the outside, but lights on the outside of the collider can't illuminate the inside. I have no idea why though, and why the same does not happen with the main panel collider for example.

**Comment by MisterChocker** [comment]
@lukecologne Any updates on this?

**Comment by DarkOfNova** [comment]
I recall someone mentioning to me that this was fixed by Asobo with the latest patch, can't remember who though.

Not closing this issue until further confirmation.

**Comment by MisterChocker** [comment]
Closing in favor of #4312
