### ISSUE TITLE
[BUG] Identified Possible T.O Config Discrepancy 

### ISSUE THREAD

**Issue by BritishAvgeek** [flybywiresim/a32nx#1569]
Mod Version - Master

**Describe the bug**
Through some QA testing I was doing of the general Master and of the XML pull PR via QA yesterday I operated into and out of a number of airports testing as many features as possible.

One test included a takeoff out of LGSK - which has a runway length of just over 1500m - quite short but I wanted to test performance, config etc for short field use as it's not been tested much.

Started Cold and Dark - Configured the MCDU to indicate a calculated 61° flex temp and FLAPS 3 for the short runway departure as I understand would be normal IRL and updated the Vrefs accordingly in the MCDU.

During the short taxi I set up for takeoff and selected TO Config test to check TO Config and for it to show "Norm" on the eicas quick checklist.

I got Master Warning and visual warnings on eicas for takeoff config not being correct. 

I reduced to Flaps 2 - pressed TO Config again and it cleared everything, and after this I returned to Flaps 3 for the departure.

**To Reproduce**

1. Spawn at any runway and configure as if to use a very short runway departure requiring Flaps 3. 
2. Ensure Flaps 3 set in MCDU on perf page and everything else is configured accordingly
3. During taxi, press the TO Config Test button 

**Expected behavior**
Set Flaps 3 in TO Perf page due to very short 1500m runway departure requiring F3. Prior to departure, test TO Config and it should show as Norm without issue. 

F3 is available for this purpose for short runway takeoff IRL I understand, so wanted to specifically test the mod behaviour with these conditions as a QA.

**Actual behavior**
It did not accept a Flap 3 config for very short takeoff even with Flap 3 set in the MCDU TO Perf Page.
When running TO Config Test again reselecting Flap 2 that worked but I needed Flaps 3 - so when I reset that again I got Master Warning again.

I cleared the issue (workaround) by selecting Flap 2 with the config warning displayed, retested TO Config to clear the message as it accepted F2 - then reselected F3 afterwards.

**References**
Found this just now which helps explain what I've done in a million words above! That's how I expected it to behave (I also used LGSK for my QA test flight when I discovered this issue)
https://youtu.be/myBmuhsJf90[https://youtu.be/myBmuhsJf90](https://youtu.be/myBmuhsJf90) 

**Additional context**
N/A

Was this working before/when did the issue start occurring?
Just noticed it today from running different QA tests for the aircraft development 

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub): 
British Avgeek YT - Carter633 #1436
(I'm on the QA chat on discord and have also asked Danbw9 to take a look to see how it behaves with his knowledge as IRL pilot) give me a shout on there if you need anything. I also recorded the behaviour on my YouTube channel though the video isn't live yet

**Comment by Carter633** [comment]
Further:
Short chat about it on the QA chat between myself and danbw9 who has said the issue is indeed present and he's been able to see it's not correct too

**Comment by imkow** [comment]
Yep, I noticed the exact same problem about Flaps 3 take off config.

**Comment by SLUF4** [comment]
I get a config warning with flaps 3 takeoff, but it's normal to use this in real life on shorter runways

**Comment by Carter633** [comment]
https://youtu.be/YVFiXKBfeCw

This is my YouTube channel video for short take offs which show the issue I reported here. Hope it helps

**Comment by BritishAvgeek** [comment]
Just re-ran the same takeoff from Skiathos again re-recording the tutorial and the same issue occured today

... To further add to it as well - when you apply takeoff thrust after initially clearing the warning etc, you get master warning on the takeoff roll too as it doesn't accept flaps 3 even with it input into the TO Perf page on the MCDU

**Comment by 2hwk** [comment]
To investigate

**Comment by BritishAvgeek** [comment]
The above only fixes half of this bug report.
