### ISSUE TITLE
[BUG] FCU knobs issues

### ISSUE THREAD

**Issue by stevex77** [flybywiresim/a32nx#1572]
**Mod Version**

Latest DEV
built: 2020-10-27T19:58:13+00:00
ref: refs/heads/master
sha: f7072f8efce5db85d92124aa90aa93190f6fda2d
actor: Benjozork
event_name: push

**Describe the bug**

Issues with some FCU knobs:
- Can't set BARO value (critical issue) - when turning knob using mouse click or mouse wheel it always returns to 948 hPa / 27.99 mmHg value
- When turning Selected Airspeed and Selected Heading knobs using mousewheel, there are incements / decrements of +/-10. When clicking with left mouse button, increments / decrements are +/-1.

**To Reproduce**

1. Spawn at the gate and start from C&D
2. Try to modify BARO, Airspeed and Heading values with FCU knobs using mousewheel / left mouse button
3. Observe above mentioned behavior

**Expected behavior**

- Can set BARO to desired value using knob, both Captain and F/O side
- +/- 1 increments / decrements when using mousewheel on Airspeed / Heading knobs

**Actual behavior**

- Some FCU knobs are misbehaving compared to vanilla / previous mod builds

**References**

Vanilla A32N or older DEV build

**Additional context**

Suspecting these modifications in PR https://github.com/flybywiresim/a32nx/pull/1476

Was this working before/when did the issue start occurring?
YES

Is this a problem in the vanilla unmodded game?
NO

Discord username (if different from GitHub):
n/a

**Comment by lousybyte** [comment]
Can't replicate, works fine on latest master for me. Make sure to [use the installer](https://github.com/Externoak/A32NX-installer/releases/latest/download/A32NX_Downloader.zip) and also try disabling any other mods that might have any conflicts with this one.

**Comment by stevex77** [comment]
Tried again and no issue this time, got rid of some add on liveries and UIMOD Hide Tooltips mod (will try later wit them). Probably some one-time problem or so. Closing this for now.
