### ISSUE TITLE
[BUG] MCDU RDNAV PAGE UNUSABLE

### ISSUE THREAD

**Issue by lionhell** [flybywiresim/a32nx#1573]
**Mod Version**
V0.4.0

**Describe the bug**
In MCDU RDNAV page it is now impossible to enter frenquencies of navaid (ADF, VOR, ...)

**To Reproduce**
Just try to setup MCDU RDNAV

1. I discovered the prob after having installed last version 0.4.0 and tried it

**Expected behavior**
To be able to enter navaid frequencies in MCDU

**Actual behavior**
RDNAV MCDU page inop.

**References**

**Additional context**

It was working in former version.

**Comment by Benjozork** [comment]
Can you try the development version and report back ?

**Comment by Kimbyeoungjang** [comment]
> Can you try the development version and report back ?

Development version working correctly. Yestetday, I use RDNAV page due to VOR. It work well

**Comment by lionhell** [comment]
I can try, I have downloaded adeveloper version (master) but I’m not sure it is the good one !!!
It is worst ! Nothing working normally !
Can you give me a direct link ?

Lionel

De : Benjamin Dupont
Envoyé le :mercredi 28 octobre 2020 00:54
À : flybywiresim/a32nx
Cc : lionhell; Author
Objet :Re: [flybywiresim/a32nx] [BUG] MCDU RDNAV PAGE UNUSABLE (#1573)

Can you try the development version and report back ?

**Comment by Benjozork** [comment]
@lionhell if you use the "code" button from GitHub, it will not work.

You need to use this link:

https://github.com/flybywiresim/a32nx/releases/download/vmaster/A32NX-master.zip

Or use the installer:

https://github.com/Externoak/A32NX-installer/releases/latest/download/A32NX_Downloader.zip

**Comment by lionhell** [comment]
OK, I tested your file and absolutely no change !
RADNAV fully inoperative ! Impossible to enter frequencies…

Lionel

**Comment by Benjozork** [comment]
Thanks. Ok, what happens when you try to enter a frequency ?

Is there an error that appears ?

Could you possibly record a video ?

**Comment by lionhell** [comment]
CORRECTION !!!! I AM SO SORRY…

I just read that one had to remove liveries… I did it (only 1 livery was installed) and now it is working !

On the former version livery was not a problem.

Thx

Lionel

**Comment by lionhell** [comment]
With one livery installed RADNAV page totally unusable… all text white (no blue) and impossible to push any frequency into the page.

Removing the livery fixed the problem.

De : Benjamin Dupont
Envoyé le :mercredi 28 octobre 2020 03:14
À : flybywiresim/a32nx
Cc : lionhell; Mention
Objet :Re: [flybywiresim/a32nx] [BUG] MCDU RDNAV PAGE UNUSABLE (#1573)

Thanks. Ok, what happens when you try to enter a frequency ?
Is there an error that appears ?
Could you possibly record a video ?

**Comment by Benjozork** [comment]
I see.

Some liveries are badly made and they replace files they should not replace - that's why.

Closing as resolved.

**Comment by lionhell** [comment]
Bonjour Benjamin,

This Morning I tried to fly A320 with A32NX mod again and I got the same problem as yesterday on first attempt… RADNAV page unusable.

Environment was :
- FS2020
- A32NX
- FSUIPC7
- Altitude (IVAO)
- ArcA (tracker from Arcadair)

I was so glad to fly at last this A320, following an almost full checklist that took long time and finally reached inoperative RADNAV page ! Imagine my disappointment…



Then I tried to check if one of the surrounding applications was the cause of the Failure :
- Closed and relaunched FS2020 and all applications
- No other app running > RADNAV ok
- Launching Altitude > RADNAV ok
- Launched FSUIPC7 > RADNAV ok
- Launched ArcA tracker > RADNAV ok

Well… I don’t know what happened on the former trial !? Why RADNAV inoperative on the 1st attempt ? No answer… but it’s a problem if A32NX works randomly !



Lionel
