### ISSUE TITLE
[BUG] Flap drag too low

### ISSUE THREAD

**Issue by CBGonzalez** [flybywiresim/a32nx#1574]
**Mod Version**

Master, downloaded 2020/Oct/27

**Describe the bug**

After changes to flight_model.cfg (among other things, drag_coef_flaps = 0.046 from original value 0.1566), flap drag is way too low. This is noticeable during approach, making it impossible to decelerate without using speed brakes.

**To Reproduce**

1. At green dot speed (managed speed), gross weight around 66000kg, before capturing glide slope, select flaps 1
2. Notice that after capturing the glide slope the speed increases, making it impossible to deploy flaps 2 without deploying speed brakes (thrust remains idle)
3.

**Expected behavior**

As per Airbus descriptions it should be possible to continuously loose speed descending via glide slope by deploying flaps 2, landing gear, 3 and full, reaching Vapp at 1000 feet

**Actual behavior**

**References**

![Airbus-Descent-Profile](https://user-images.githubusercontent.com/32073269/97375634-11f17880-189a-11eb-9a91-f8103332bd3e.png)

**Additional context**

If I understand the drag_coef_flaps variable, the reduction (by a factor of 5!) is at the root of this. Changing the value back to the original makes following the above profile possible. Maybe the new value is a typo? A change of 5x seems unlikely...

Was this working before/when did the issue start occurring?
Issue started after flight model was tweeked, don´t know which pull number that was.
Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub): cgbFlight

**Comment by MisterChocker** [comment]
This is a more common approach procedure (in germany). Also note that in both charts flaps 2 are set as soon gs is captured.
![image](https://user-images.githubusercontent.com/1857322/97377816-2a28be00-18c1-11eb-8782-a99705c7268b.png)

**Comment by MisterChocker** [comment]
@CBGonzalez  So flaps don't slow down as they do in my reference video (https://youtu.be/uOhrr1irBLg) ?
_(I was not able reproduce, see video)_

**Comment by CBGonzalez** [comment]
@MisterChocker good point will try again later (that figure is the continuous descent approach, right?)
@MisterChocker what was your weight? Hard to tell from the video.

**Comment by MisterChocker** [comment]
@CBGonzalez
> that figure is the continuous descent approach, right?

yes, its more economical. (noice reduction, lower fuel consumption)

> what was your weight?

57.6t GW (can be seen at [0:43](https://youtu.be/uOhrr1irBLg?t=43))

**Comment by CBGonzalez** [comment]
You´re right, just tried again with 2 different weights and all is well up to around 65000 kg. Don´t know how I managed to do it the first time. Will close this, thanks for the help.

**Comment by MisterChocker** [comment]
Np, we have very good QA so this was very unlikely to be flat wrong. Glad we could help!
