### ISSUE TITLE
[BUG] Peripherals and Keyboard unresponsive issue still persists

### ISSUE THREAD

**Issue by dmajestic80** [flybywiresim/a32nx#1575]
**Mod Version**
 Latest Development version from latest installer

built: 2020-10-27T19:58:13+00:00
ref: refs/heads/master
sha: f7072f8efce5db85d92124aa90aa93190f6fda2d
actor: Benjozork
event_name: push

**Describe the bug**

Following on from previous issue under #1420 
Keyboard, mouse and controls/peripherals all become unresponsive but doesn't happen all the time and I'm finding it difficult to pin point exactly what I'm doing that cause this issue.
I can't pan around using hatswitch 
I can't pan around using mouse whilst middle button is held down
I can press ESC key to access the menu but this is the only keyboard key that works
I can use the mouse to click buttons and switches 
I can use the mouse to access the toolbar and select ATC, Camera's etc. but if I say select External camera, it'll take me outside but once again I cannot pan around or move and the aircraft control surfaces don't work.

**To Reproduce**

1. I had downloaded the latest Dev version via the installer into my Community folder
2. I add in my liveries into the community folder
3. I then go start a flight and it works as normal
4. I finish my flight, close the sim, start the sim again and start another flight with a different livery
5. Get into the cockpit and the issue described above happens
6. I then go delete all liveries, then delete the A32NX folder from the community folder
7. Re-install A32NX and re-install liveries
8. Start a new flight and all works again as normal
9. I then once again, close the sim, start a new flight, select another livery, start a flight, and the issue is back....????

**Expected behavior**

For keyboard, mouse and controls inputs to work as normal

**Actual behavior**

All described above

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
This does not happen with the unmodded version

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Hello,

Please retry for a longer amount of time without any liveries, especially from the megapack. Those are not quality-controlled at all and often cause issues.

I however am afraid you are the only user I have seen report the issue, and I really doubt the mod is causing this.

**Comment by dmajestic80** [comment]
> 
> 
> Hello,
> 
> Please retry for a longer amount of time without any liveries, especially from the megapack. Those are not quality-controlled at all and often cause issues.
> 
> I however am afraid you are the only user I have seen report the issue, and I really doubt the mod is causing this.

Hi, 

Just for reference, I use individual liveries downloaded from this site:

https://fsmegapack.org/downloads/all-in-one/

I don't add every livery, only about 5 or 6 that I use at any one time. The strange thing is that the liveries work fine, and there is no issue using these liveries when not using the mod so the issue must in some way be related to the mod.

I'm not sure how it all works but is there possibly a entry hierarchy in an xml that could potentially cause the issue? If so, what xml would that be so I can share what it looks like?

I had this issue a while ago and had since done a full re-install but it still persists so it must be something I am doing although I'm following all steps correctly, and previous to this issue starting, for weeks I never had any issues (using the same liveries)

It's so strange and there must be a logical resolution for it.

**Comment by Benjozork** [comment]
> I'm not sure how it all works but is there possibly a entry hierarchy in an xml that could potentially cause the issue? If so, what xml would that be so I can share what it looks like?

We cannot really "control" user inputs, trust me we'd love to for stuff like keyboard-controlled MCDU. Flight Simulator simply does not provide the ability.

> I had this issue a while ago and had since done a full re-install but it still persists so it must be something I am doing although I'm following all steps correctly, and previous to this issue starting, for weeks I never had any issues (using the same liveries)
>
> It's so strange and there must be a logical resolution for it.

Yeah, it's really strange. if I find anything, I'll get back to you.

**Comment by dmajestic80** [comment]
> 
> 
> > I'm not sure how it all works but is there possibly a entry hierarchy in an xml that could potentially cause the issue? If so, what xml would that be so I can share what it looks like?
> 
> We cannot really "control" user inputs, trust me we'd love to for stuff like keyboard-controlled MCDU. Flight Simulator simply does not provide the ability.
> 
> > I had this issue a while ago and had since done a full re-install but it still persists so it must be something I am doing although I'm following all steps correctly, and previous to this issue starting, for weeks I never had any issues (using the same liveries)
> > It's so strange and there must be a logical resolution for it.
> 
> Yeah, it's really strange. if I find anything, I'll get back to you.

Appreciate the response. In the meantime I think I found a workaround, albeit it is quite annoying but if I delete all liveries after finishing a flight and then delete the a320 livery folders from within the microsoft flight simulator/simobjects folder that contain the 'state.cfg' files and then just add the livery of the next flight I'm going to do at least allows me to still use the sim. 

It's so weird that I'm the only one that has reported the issue, that makes me even more curious....I wonder if there is another addon completely unrelated that conflicts in some way. I may need to test with absolutely no other addons (but I have a feeling I did this when I first had the issue)

**Comment by janszett** [comment]
I have the same issues with keyboard and mouse becoming unresponsive sometimes. I can't click any buttons or access the menu at all. I don't see the mouse cursor, but I see the quick navigation icons highlighting when I hover over them.

**Comment by hotshotp** [comment]
this has not been reported int the past two months, so i will close the issue
