### ISSUE TITLE
[BUG] Clock, Brake Gauge And ISIS Disapear at certain angles

### ISSUE THREAD

**Issue by Samueleonard** [flybywiresim/a32nx#1576]
**Mod Version**
built: 2020-10-27T19:58:13+00:00
ref: refs/heads/master
sha: f7072f8efce5db85d92124aa90aa93190f6fda2d
actor: Benjozork
event_name: push

**Describe the bug**
When the camera is at certain angles, mainly down low in the cockpit, certain lights/gauges turn black
![FlightSimulator_jGwx3djqlf](https://user-images.githubusercontent.com/34142670/97378517-660c5500-18ba-11eb-894c-f29f24468ed9.png)
Looking upwards further will turn them back on, it is only certain angles where they go off

**To Reproduce**
1. Move camera down low, around pedestal height
2. Look upwards towards glare shield

**Expected behaviour**
Gauges do not disappear

**Actual behaviour**
Gauges disappear

**References**
Image attached with camera position
Only certain gauges disapear, screens remain on, in the image you see the ECAM and ND remain on 

Was this working before/when did the issue start occurring?
Not noticed before today, however, I haven't been in this position to notice it before

Is this a problem in the vanilla unmodded game?
Untested

Discord username (if different from GitHub): 1samueleonard1#0001

**Comment by Benjozork** [comment]
This is an MSFS bug.
