### ISSUE TITLE
ANN LT on TEST position from a cold start

### ISSUE THREAD

**Issue by ColdChicken1** [flybywiresim/a32nx#158]
from a cold start, the ANN LT is on "test" position, shouldn't be and the brt/dim have the same brightness - dev version

[https://imgur.com/a/QQ7HZKd](url)

**Comment by arvinjarvin** [comment]
hello

We are aware of this and are solving the issue

We will keep you updated

Arvin

**Comment by oliverpope03** [comment]
Yes ive also been looking into how to fix this issue 😄 a few switches have the same thing atm

**Comment by AdenFlorian** [comment]
ANN LT is now  spawning in the BRT position on cold and dark, on master branch:
![image](https://user-images.githubusercontent.com/3533988/92549271-7e4ae680-f21e-11ea-896d-44b4548d76c5.png)

**Comment by AdenFlorian** [comment]
created new issue to implement the actual functionality of thw switch: https://github.com/flybywiresim/a32nx/issues/528
