### ISSUE TITLE
blue G/S and LOC annunciators at FL350 in cruise

### ISSUE THREAD

**Issue by speedwaystar** [flybywiresim/a32nx#1581]
**Mod Version**

master

**Describe the bug**

while flying at FL350 in cruise, the PFD displayed G/S and LOC in blue text. ![](https://i.imgur.com/Y1lW5bp.png)

**Expected behavior**

I wouldn't expect G/S and LOC information at FL350 in Cruise ![](https://i.imgur.com/yfWiNzQ.png)

**Comment by Rameyuk** [comment]
Did you press the APPR button on the FCU panel by accident that arms the G/S and LOC modes?

**Comment by speedwaystar** [comment]
i did :( i have failed.
