### ISSUE TITLE
[BUG] APPR phase activates during cruise despite not passing DECEL point

### ISSUE THREAD

**Issue by ThatRedMelon** [flybywiresim/a32nx#1582]
**Mod Version**

Master

built: 2020-10-28T04:59:23+00:00
ref: refs/heads/master
sha: a175647cd77b46b1ef4da4c7ee0482126b73ab48
actor: Benjozork
event_name: push

**Describe the bug**

During cruise, at seemingly random points, the APPR phase of the flight will begin, causing airspeed to drop and pitch to increase.

**To Reproduce**

1. Load a flight
2. Takeoff and climb to cruise
3. Occasionally APPR phase will activate on the PERF page during cruise

**Expected behavior**

The plane remains in cruise phase until descent at which point the plane will change to DES phase.

**Actual behavior**

During cruise the plane switches to APPR phase instead of remaining at cruise.

**References**

![APPRphase](https://user-images.githubusercontent.com/34657891/97451254-7c9ec480-192b-11eb-8a9d-522512c37c34.png)

**Additional context**

Might be hard to reproduce, since it seems to be random.

Was this working before/when did the issue start occurring?
Multiple people reported this happening as of 28/10/20

Is this a problem in the vanilla unmodded game?
Unsure but probably not

Discord username (if different from GitHub):
ThatRedMelon#6756

**Comment by nreyes90** [comment]
Verified. Just occurred during my flight right now 1457Z KDEN-KLAS 


ROCKI5 DEN DCT TEHRU DCT JASSE Q90 DNERO ANJLL4
--

Bug occured somewhere after JASSE mid crz way before even first waypoint of STAR.

![image](https://user-images.githubusercontent.com/1619968/97454147-661b5c00-1971-11eb-8266-350840124145.png)

Image of Navigraph point whereabouts I noticed the issue.

**Comment by lars-reimann** [comment]
Same for me (and yes, I know the baro should have been set to Std 😉):

![approach phase (Large)](https://user-images.githubusercontent.com/2501322/97456606-5122d680-1939-11eb-80c5-2ed673e9308e.png)

**Comment by Watsi01** [comment]
As far as I know, the only condition for the MCDU switching to APPR is <40nm from the destination. Just this seems already strange to me - as well as the reported issue.  But I didn't find another parameter so far. We're getting more and more issues with 3rd party liveries involved. Maybe that's one of them.

**Comment by kielyscott** [comment]
I believe there are only 2 ways for APPR to switch automatically IRL 

- Manual activation of phase
- Passing DECEL point

On expected behaviour you say "The plane remains in approach phase until descent at which point the plane will change to DES phase." Just checking this is what you mean as DES should be before APPR. 

Did you have a normal managed descent or did you descend manually? Did the DES phase activate as expected?

**Comment by ThatRedMelon** [comment]
Apologies, that was a mistype, I mean cruise phase

**Comment by kielyscott** [comment]
Got ya! I was a little confused.

Yeah, strange though. Was there a particular time in flight, or maybe a particular distance from the RW that this happened, or random?

I'll try tonight and see if it happens to me on a175647

**Comment by Watsi01** [comment]
@kielyscott yes. I discribed what I found in the specific code so far. I don't think that's all. I must have missed something.

**Comment by ThatRedMelon** [comment]
I performed a selected descent however the APPR phase activated a long time before I began my descent. Could the DECEL waypoint be ay the incorrect place, causing the APPR phase to activate? I understand the DECEL logic was changed in a175647

**Comment by ThatRedMelon** [comment]
I couldn't see a specific point it activated. However, I wasn't paying full attention to the sim, just heard the engines spooling down.

**Comment by Watsi01** [comment]
EDIT/Correction: ok he's switching to APPR if less than 40nm from DEST and/or lesss than 3nm from DECEL. It could be a DECEL problem. I saw DECEL flickering over my MFD more than one time.

**Comment by kielyscott** [comment]
Spotted this in the code, I suspect DECEL is being calculated incorrectly thought I don't know what the logic _should_ be

[CDU] Cleanup logic for DECEL ETA calculation

` if (mcdu.flightPlanManager.decelWaypoint) {
            const idx = waypointsWithDiscontinuities.findIndex((e) => e.wp.cumulativeDistanceInFP > mcdu.flightPlanManager.decelWaypoint.cumulativeDistanceInFP);
            if (idx > 0 && idx < waypointsWithDiscontinuities.length) {
                mcdu.flightPlanManager.decelWaypoint.cumulativeEstimatedTimeEnRouteFP = mcdu.flightPlanManager.decelWaypoint.cumulativeDistanceInFP / groundSpeed * 3600;
                mcdu.flightPlanManager.decelWaypoint.estimatedTimeOfArrivalFP = utcTime + mcdu.flightPlanManager.decelWaypoint.cumulativeEstimatedTimeEnRouteFP;
                waypointsWithDiscontinuities.splice(idx, 0, {
                    wp: mcdu.flightPlanManager.decelWaypoint,
                    fpIndex: -42
                });`

**Comment by kielyscott** [comment]
```
if (mcdu.flightPlanManager.decelWaypoint) {
            const idx = waypointsWithDiscontinuities.findIndex((e) => e.wp.cumulativeDistanceInFP > mcdu.flightPlanManager.decelWaypoint.cumulativeDistanceInFP);
            if (idx > 0 && idx < waypointsWithDiscontinuities.length) {
                mcdu.flightPlanManager.decelWaypoint.cumulativeEstimatedTimeEnRouteFP = mcdu.flightPlanManager.decelWaypoint.cumulativeDistanceInFP / groundSpeed * 3600;
                mcdu.flightPlanManager.decelWaypoint.estimatedTimeOfArrivalFP = utcTime + mcdu.flightPlanManager.decelWaypoint.cumulativeEstimatedTimeEnRouteFP;
                waypointsWithDiscontinuities.splice(idx, 0, {
                    wp: mcdu.flightPlanManager.decelWaypoint,
                    fpIndex: -42
                });
```

**Comment by nreyes90** [comment]
For reference, the APPR phase activated ~170-152NM away from airport mid CRZ.

**Comment by st3ph29** [comment]
OP says it might be random. I have had the issue  2 times in a row mid flight in cruise phase.

**Comment by lousybyte** [comment]
> Spotted this in the code, I suspect DECEL is being calculated incorrectly thought I don't know what the logic _should_ be
> 
> [CDU] Cleanup logic for DECEL ETA calculation
> 
> ```
> if (mcdu.flightPlanManager.decelWaypoint) {
>             const idx = waypointsWithDiscontinuities.findIndex((e) => e.wp.cumulativeDistanceInFP > mcdu.flightPlanManager.decelWaypoint.cumulativeDistanceInFP);
>             if (idx > 0 && idx < waypointsWithDiscontinuities.length) {
>                 mcdu.flightPlanManager.decelWaypoint.cumulativeEstimatedTimeEnRouteFP = mcdu.flightPlanManager.decelWaypoint.cumulativeDistanceInFP / groundSpeed * 3600;
>                 mcdu.flightPlanManager.decelWaypoint.estimatedTimeOfArrivalFP = utcTime + mcdu.flightPlanManager.decelWaypoint.cumulativeEstimatedTimeEnRouteFP;
>                 waypointsWithDiscontinuities.splice(idx, 0, {
>                     wp: mcdu.flightPlanManager.decelWaypoint,
>                     fpIndex: -42
>                 });
> ```

This code just tries to put the DECEL point in the correct position in the flight plan, its coordinates are calculated in another place  as 32nm from DEST, and can confirm I saw it glitching as well for a few frames at times.

**Comment by santii90** [comment]
I did 3 flights with the a320 today, with the latest master every time, and the first two times I faced this bug, I just finished another flight without any issues. The only difference besides the F-PLAN itself was that for the ones that I had the issue, I added some ALT constrains to cruise level waypoints, for example a mid waypoint with FL 350. Don't know if have something to do with that. Also took a look to the code but looks like the conditions to activate the approach are good, the only part that I'm not sure is on the A32NX_NavSystem.js file, line 330:

```
if (this.currFlightPlanManager.isLoadedApproach() && !this.currFlightPlanManager.isActiveApproach() && (this.currFlightPlanManager.getActiveWaypointIndex() == -1 || (this.currFlightPlanManager.getActiveWaypointIndex() > this.currFlightPlanManager.getLastIndexBeforeApproach()))) {
            if (SimVar.GetSimVarValue("L:FMC_FLIGHT_PLAN_IS_TEMPORARY", "number") != 1) {
                this.currFlightPlanManager.tryAutoActivateApproach();
            }
        }
```

**Comment by James3221** [comment]
it could be to do with the function: tryAutoActivateApproach()
or to be with when it is called: if (SimVar.GetSimVarValue("L:FMC_FLIGHT_PLAN_IS_TEMPORARY", "number") != 1) {
                                                      this.currFlightPlanManager.tryAutoActivateApproach();
                                                 }
you can find it being called in: A32NX_NavSystem.js and i suspect it could be to do with it.

**Comment by billsux** [comment]
I also had this issue with the latest master. It happened litterally in the middle of the flight (EDDM -> LGIR, 
approx. 1h after takeoff). DECEL was not passed at that time
![original_e2376373-051c-4836-bd5f-2ef300a2e740_Screenshot_20201029-105628_Chrome](https://user-images.githubusercontent.com/71268660/97554322-e031fc00-19d6-11eb-90d8-24d690873847.jpg)

Perhaps this helps you out: DECEL was (as expected) a few miles before the airport.
![Microsoft Flight Simulator Screenshot 2020 10 29 - 10 33 13 51](https://user-images.githubusercontent.com/71268660/97554588-474fb080-19d7-11eb-9953-371f8f96d641.png)

**Comment by MisterChocker** [comment]
@billsux yeah decel looks correct for me, even tho it should be on the line xD

**Comment by Watsi01** [comment]
I made several flights the last days and there was no issue at all. Of course that doesn't mean, that the problem doesn't exist. But there has to be a precondition for it to happen.

Long or short haul?
CRZLevel (higher or lower ones)?
Heavy or light weighted?
Used Appr procedures like a STAR or not?
Inserted the landing rwy / appr (MCDU) at the beginnig of the flight or later?

**Comment by ThatRedMelon** [comment]
The last few times I experienced this, it was short hauls at FL350-370 with a light payload with STARS and arrival runway selected before takeoff.

I am currently performing a long haul flight at FL350 with a heavy payload with STARS and arrival runway selected before takeoff and have been in flight for 3hr 27 with no approach phase activated.

**Comment by Watsi01** [comment]
I don't insert a landing rwy from the beginning. Maybe that's a difference...?

**Comment by ThatRedMelon** [comment]
Is the decel point calculated if a arrival runway is not set? Because multiple people say they saw the decel point flashing which could be causing the appr phase to activate. That could be the difference.

**Comment by RiderKickingMarco** [comment]
I can confirm this is an issue in the latest master.

**Comment by lousybyte** [comment]
Found the issue, it is related to #1505 but in a very subtle way, looking into it to see if there's a way to patch it cleanly.

**Comment by CJ1045** [comment]
I have just flown Schipol to Heathrow and did not have a DECEL point at all and ILS would not connect/approach mode would not activate. Worked fine on default A320 on same plan.

**Comment by CJ1045** [comment]
Yep, just tested this again both on FBW Neo and default. When I flew the FBW there was no DECEL in FMC but there was in Default. This was using the same pln loaded from a file and ILS27R. A bug in the new master for FBW, prior to the patch and the prior master all was fine again on this same pln

**Comment by lousybyte** [comment]
Noticed that as well, is due to the last update, but it's not related to this, there's no DECEL even on the ND, looking into it, probably some new code needs to be ported.

**Comment by lousybyte** [comment]
Found the missing code, will push fix soon after I test some more.

**Comment by CJ1045** [comment]
Great, thanks - managed to land the Airbus FBW with a full manual approach. Not saying it was a smooth landing but at least not the black screen with 'Overstressed Aircraft' note!
