### ISSUE TITLE
[REQUEST] Working TCAS

### ISSUE THREAD

**Issue by avgeek132638** [flybywiresim/a32nx#1584]
**Is your feature request related to a problem? Please describe.*
becuase I like to fly vatsim and if I’m flying into a crowded event they like pilots to have an active tcas.

**Describe the feature you'd like to see implemented**
just like the normal airbus tcas where it shows you the other aircraft on your mfd and tell you to climb or decend in a situation.

**References**
like fs labs or just the regular airbus 

**Additional context**

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by lukecologne** [comment]
#1097
