### ISSUE TITLE
[REQUEST] Side stick priority

### ISSUE THREAD

**Issue by TansyEliot** [flybywiresim/a32nx#1587]
**Is your feature request related to a problem? Please describe.** 

No.

**Describe the feature you'd like to see implemented**

Make "side stick priority" button functional

**References**

![image](https://user-images.githubusercontent.com/72763559/97483531-4adf2b00-1936-11eb-8a83-25c997893558.png)

**Additional context**

Discord username (if different from GitHub):

**Comment by lukecologne** [comment]
#908. Actual sidestick priority logic will be pretty useless to implement.

**Comment by Benjozork** [comment]
@lukecologne shared cockpit beta is coming next week FYI
