### ISSUE TITLE
[BUG] V/S Mode is cancelled when crossing route waypoints

### ISSUE THREAD

**Issue by ElSrJuez** [flybywiresim/a32nx#1590]
**Mod Version**: 
4.0

**Describe the bug**
When flying, the Vertical Speed Hold Mode with a manually adjusted vertical speed would cancel when crossing a route waypoint, the aircraft would then bust the configured vertical speed.

**To Reproduce**
1. Start a flight with a proper flight plan, climb to CRUISE
2. Start descent, and activate VS HOLD mode and set a custom descent vertical speed

**Expected behavior**
The VS HOLD mode should stay and the A/C should continue descent at configured VS

**Actual behavior**
On next waypoint, VS HOLD mode will cancel out, aircraft will start descending at a different VS

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Unsure.

Is this a problem in the vanilla unmodded game?
Unsure.

**Comment by MisterChocker** [comment]
When passing waypoint, VS Mode will switch to Open Descent.

**Comment by ChruutvoLuzi** [comment]
Can confirm this aswell

**Comment by James3221** [comment]
possibly linked with #1582

**Comment by MisterChocker** [comment]
> possibly linked with #1582

Nope
