### ISSUE TITLE
[BUG] [ECAM] N1 donut behavior not correct

### ISSUE THREAD

**Issue by St54Kevin** [flybywiresim/a32nx#1596]
**Mod Version**

Current master as of 29th Okt 20

**Describe the bug**

Behavior of the Thrust lever postion indicator (donut) lags behind and is not correct. 
Donut starting position is already fixed by #1549 

This is the point where the donut starts moving. Already lagging behind. **Levers at 20%**
![image](https://user-images.githubusercontent.com/448627/97578303-e1702280-19f0-11eb-9c1d-8f050a1a335c.png)

**Thrust set at 50% with levers only at 38%**
![image](https://user-images.githubusercontent.com/448627/97578382-ff3d8780-19f0-11eb-94fb-fe66207a1b09.png)

**Levers 100%**
![image](https://user-images.githubusercontent.com/448627/97578444-15e3de80-19f1-11eb-83d2-2a761793ac80.png)

**To Reproduce**

1. Load a flight
2. Look at the indication
3.

**Expected behavior**

donut should match up with the N1 indicator when in manual thrust

**Actual behavior**

**References**

**Additional context**

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment]
yep same for me, had opened an few days ago.
I got this since #1477 merge
https://github.com/flybywiresim/a32nx/issues/1527

**Comment by St54Kevin** [comment]
> yep same for me, opened https://github.com/flybywiresim/a32nx/issues/1527 a few days ago.
> I got this since #1477 merge

Ah did not find that. Please merge or close

**Comment by MisterChocker** [comment]
Merge or close? I have opened an issue with the same problem, not an pr or anything ^^

**Comment by St54Kevin** [comment]
> Merge or close? I have opened an issue with the same problem, not an pr or anything ^^

I mean merge this issue with the other one or close it :D

**Comment by MisterChocker** [comment]
don't know how merge issues.

**Comment by St54Kevin** [comment]
> Hi @St54Kevin . That might be my fault as I've set the behaviour of the donut to match the thrust lever position and not the N1 value. Presumably they are not always the same though?

No that is correct it has to match thrust lever position BUT thrust has to match the lever position

**Comment by RichardPilbery** [comment]
Okay, this seems to be the case for me with #1549 applied.

**Comment by St54Kevin** [comment]
> Okay, this seems to be the case for me with #1549 applied. 

Not for me. Only for idle

**Comment by RichardPilbery** [comment]
Okay, I'll wait for #1549 to be merged and I'll take another look.

**Comment by MisterChocker** [comment]
@RichardPilbery looking forward!

**Comment by RichardPilbery** [comment]
So this is what I'm currently seeing:
**50%**

![50percent](https://user-images.githubusercontent.com/5834254/97602165-e76eff00-1a02-11eb-8fbb-91e45d8534a4.png)


**70%**
![70 per cent](https://user-images.githubusercontent.com/5834254/97602190-ef2ea380-1a02-11eb-9e0f-252ab9900f38.png)


**100%**

![100 per cent](https://user-images.githubusercontent.com/5834254/97602232-f9e93880-1a02-11eb-8d93-3d0cb8781444.png)


Is this correct behaviour or should it be displaying something else?

**Comment by MisterChocker** [comment]
No I believe the donut should match up with the N1% indicator when in manual thrust.
Should look like this
![image](https://user-images.githubusercontent.com/1857322/97602746-f60de400-1a0b-11eb-81c5-1094b1e43e3a.png)

**Comment by RichardPilbery** [comment]
Thanks @MisterChocker have you got a reference for this as I'll need it if I submit a pull request to amend this behaviour? On the plus side, it should be an easy fix!

**Comment by MisterChocker** [comment]
https://youtu.be/rhI5XGwlnaI?t=213

**Comment by MisterChocker** [comment]
This is not really a reference, but you can see the exact throttle position N1% in the top right corner.
In real life this is not the case, but we are currently displaying the current throttle sim value.

**Comment by St54Kevin** [comment]
It's simple. When in manual thrust, the needle of N1 (thrust value) goes to the exact position where the donut is.

**Comment by RichardPilbery** [comment]
No worries.

**Comment by ntlgr** [comment]
> It's simple. When in manual thrust, the needle of N1 (thrust value) goes to the exact position where the donut is.

That's when the donuts exceed idle thrust. At idle position, donuts are at 0% but needle is higher.

**Comment by MisterChocker** [comment]
@ntlgr no, not on ground

**Comment by starvingjavi** [comment]
I have this error as well. I notice that the donut position does not match the throttle quadrant position when selecting low power (during taxi). Usually I see the donuts react when applying more power
