### ISSUE TITLE
[BUG]  MCDU is black after last msfs update

### ISSUE THREAD

**Issue by noga-aviator** [flybywiresim/a32nx#1599]
**Mod Version**
latest master

**Describe the bug**
MCDU is black. changing brightness doesn't works
![image](https://user-images.githubusercontent.com/35369933/97614049-c06ff780-1a19-11eb-80bf-5287b291f55b.png)

**To Reproduce**
1. just load the aircraft anywhere you want

**Expected behavior**
The mcdu should turn on with external power or any generator

**Actual behavior**
the mcdu screens stays black

Was this working before/when did the issue start occurring?
after last update

Is this a problem in the vanilla unmodded game?
no

**Comment by LarrySheen** [comment]
Asobo: Update #5 delayed due to autopilot issues.
fbw: Of course.
Asobo: Update #5 release!!! (suddenly, new bugs came out..)
fbw: ...
me: That was expected🤣

**Comment by noga-aviator** [comment]
i don't really understand asobo's behaviour tbh. They say they are very interested in working with fbw but with every update it looks like they don't care and it breaks the whole thing.

**Comment by wpine215** [comment]
> 
> 
> i don't really understand asobo's behaviour tbh. They say they are very interested in working with fbw but with every update it looks like they don't care and it breaks the whole thing.

That's to be expected with mods, especially since we haven't hard-forked our code from some of their share code. So they aren't to blame for any issues that we encounter during an update (unless those issues are also present on the default A320neo, such as the left engine out bug a while back).

**Comment by kielyscott** [comment]
Confirmed fixed in #1607 

![1](https://user-images.githubusercontent.com/45067080/97646813-9124af00-1a48-11eb-8a16-6e66e986860d.PNG)
