### ISSUE TITLE
Download no longer working with new MSFS update?

### ISSUE THREAD

**Issue by kevjell** [flybywiresim/a32nx#1602]
**Mod Version**

**Describe the bug**

**To Reproduce**

1. download is no longer accessible
2. game reverts back to original MSFS 2020 Airbus version 
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by ThatRedMelon** [comment]
This can be fixed by reinstalling the mod either via the installer or the direct link.

**Comment by kevjell** [comment]
did that twice both master and perfected version @ThatRedMelon
