### ISSUE TITLE
[BUG] Issues with 1.10.7.0

### ISSUE THREAD

**Issue by Venorcis** [flybywiresim/a32nx#1603]
**Mod Version**
master

**Describe the bug**
Several features are not working with the latest MSFS update:
- ~~ADIRS are non-functional; setting them to NAV will not start the alignment.~~ duplicate #1600
- ~~MCDU is not working at all (none of the pages show up), only a single / is visible in the top-right corner.~~ duplicate #1599
- ~~It's not possible to start the APU (starter button turns to ON but doesn't actually do anything).~~ (fixed)
- ~~Frequencies on the radios are not visible (displays not working).~~ (fixed)
- (minor) three-way overhead switches don't animate (e.g. strobe and landing lights instantly move position)

Everything else I can test sitting at a gate seems to be working fine.

**To Reproduce**
Use latest MSFS version with latest A32NX version. Cold & Dark start at a gate.

**Comment by LarrySheen** [comment]
Also, Mach units knob won't return to knots once activated (Asobo bug, at the bottom of the KNOWN ISSUE section)

**Comment by LarrySheen** [comment]
bugs resolved after I spawn at the runway with take off status.

**Comment by TheoBearman** [comment]
> MCDU related bugs resolved after I spawn at the runway with take off status.

That isn't exactly a fix :wink:. We will still need all of these looked into.

**Comment by lukecologne** [comment]
> (minor) three-way overhead switches don't animate (e.g. strobe and landing lights instantly move position)

I just tested, it is an issue in the default A320 as well

**Comment by Benjozork** [comment]
@TheoBearman, it's still a workaround and useful to us for identifying the problem.

**Comment by lukecologne** [comment]
> ADIRS are non-functional; setting them to NAV will not start the alignment.
> It's not possible to start the APU (starter button turns to ON but doesn't actually do anything).

These are probably both an issue with A32NXCore, because that is attached to the MCDU. since it isn't functioning, A32NXCore isn't updating as well, causing those issue.

**Comment by Benjozork** [comment]
Hello, I crossed out some of your issues as they were already reported.

**Comment by LarrySheen** [comment]
Maybe this is not the right time to say this... but, my FPS is slightly high after this update.. 🤣

**Comment by Benjozork** [comment]
@LarrySheen probably because a lot of the systems are not updating

**Comment by LarrySheen** [comment]
@Benjozork exactly

**Comment by smukherj1** [comment]
> MCDU related bugs resolved after I spawn at the runway with take off status.
> SEATS BELTS & NO SMOKING and many other buttons shows 'INOP'

It's possible this means the A32NX mod just didn't load for you here. I restarted the sim and spawned at take-off and I got all the issues reported in this bug

**Comment by LarrySheen** [comment]
> > MCDU related bugs resolved after I spawn at the runway with take off status.
> > SEATS BELTS & NO SMOKING and many other buttons shows 'INOP'
> 
> It's possible this means the A32NX mod just didn't load for you here. I restarted the sim and spawned at take-off and I got all the issues reported in this bug

You're right, that wakes me up

**Comment by Tchors** [comment]
WORKAROUND FOR APU BUG: Just assign APU Start in controls to a button on your keyboard or joystick for now. Just worked for me.

**Comment by lukecologne** [comment]
No workaround needed. Newest master fixed the APU issue.

**Comment by kevjell** [comment]
@lukecologne I cant seem to get the master version to work after I move it into my community folder, MSFS just reverts to their version. However for some reason v4.0 still works for me, any tips?

**Comment by dualznz** [comment]
after the latest update none of the additional buttons work

**Comment by Benjozork** [comment]
@dualznz which version of the mod are you using ?

**Comment by dualznz** [comment]
I think I'm running 0.4.0 but I will remove then readd the mod just to make sure

**Comment by FinalLightNL** [comment]
VS knob also has issues, doesn't do 100 increments and can't go back down

**Comment by JanMar85** [comment]
Every time you update MSFS 2020, you have to also reinstal A320NX again. Just copy the files.

**Comment by SM-396** [comment]
Same Here . Clear A320X Mod in Community Folder and do an fresh install. Stable Version shows 0.4.0 and Up to Date
FMC not Working  etc

![2020-10-30 07_52_36-Greenshot](https://user-images.githubusercontent.com/50043259/97675150-129f3000-1a8f-11eb-807a-c484b001d0a9.jpg)

**Comment by SM-396** [comment]
> I think I'm running 0.4.0 but I will remove then readd the mod just to make sure

No , dont work !!!!

**Comment by dualznz** [comment]
nope apu is dead and wont fire, mcas is blank, radio stack is blank so plane is essentially useless on 0.4.0

**Comment by bisinchi** [comment]
I also have all no information on PFD and all my engines indications are crossed.

**Comment by Venorcis** [comment]
Guys, make sure to download the master from here: https://github.com/flybywiresim/a32nx/releases/tag/vmaster

I can confirm all listed issues are fixed with the latest master, besides the knob animation (but that seems to be a vanilla problem anyway).

**Comment by Oberstumfuher** [comment]
> Pessoal, não deixem de baixar o mestre daqui: https://github.com/flybywiresim/a32nx/releases/tag/vmaster
> 
> Posso confirmar que todos os problemas listados são corrigidos com o último mestre, além da animação do botão (mas isso parece ser um problema de baunilha mesmo).

Thank you
