### ISSUE TITLE
[BUG] Enabling VFR map clears MCDU

### ISSUE THREAD

**Issue by DraivPro** [flybywiresim/a32nx#1608]
**Mod Version**

No

**Describe the bug**

**To Reproduce**

1. Load the plane without Flight Plan
2. Enter any airports of departure and arrival in Flight Plan (in MCDU)
3. Add VFR map to the top toolbar (number 1 in the screenshot)
4. Run VFR map (number 2 in the screenshot)
5. The MCDU is now cleared. (number 3 in the screenshot)

![bug vfr](https://user-images.githubusercontent.com/71631760/97645460-16ff2500-1a5e-11eb-8f46-2d76cc4796cb.png)

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
Yes ( 1.10.7.0)

Discord username (if different from GitHub):

**Comment by lukecologne** [comment]
From the screenshot it looks like you are using the default A320

**Comment by DraivPro** [comment]
> From the screenshot it looks like you are using the default A320

Yes, I wrote about this above that the problem is with the game without a mod. I wanted to report a problem. Suddenly it will somehow break the Flybywire version.

**Comment by MisterChocker** [comment]
Please recheck with latest master or stable (0.5.1)

**Comment by MisterChocker** [comment]
Closing since no response from op.
