### ISSUE TITLE
[BUG] Display of first officer can not be dimmed

### ISSUE THREAD

**Issue by ronaldvdmeer** [flybywiresim/a32nx#1609]
**Mod Version**
0.4

**Describe the bug**
One of the screens in front of the first officer can not be dimmed. I believe it’s the second from the right.

**To Reproduce**
1. Fly at nighttime
2. Adjust brightness of screens

**Expected behavior**
Change of brightness 

**Actual behavior**
The brightness stays at full brightness.

**Comment by Benjozork** [comment]
Version 0.4.0 is not supported for the latest MSFS release.

**Comment by ronaldvdmeer** [comment]
Confirmation that this has been solved in latest development version.
