### ISSUE TITLE
[BUG] Autopilot not working on 1.10.7

### ISSUE THREAD

**Issue by kyleawayan** [flybywiresim/a32nx#1611]
**Mod Version**

"master" https://github.com/flybywiresim/a32nx/commit/6b37627174a969d36a42fca76e086ecfb75ecf46

**Describe the bug**

Autopilot doesn't work

**To Reproduce**

1. Start a new flight on runway
2. Takeoff
3. Activate AP1
4. Set a heading and altitude

**Expected behavior**

Autopilot starts ascending

**Actual behavior**

Autopilot ascends for a little bit, then starts nosediving

**References**

![unknown](https://user-images.githubusercontent.com/56655579/97647529-b9dc8280-1a0f-11eb-99a1-37ff64ae7c40.png)

**Additional context**

I'm using the latest pre-release master version https://github.com/flybywiresim/a32nx/commit/6b37627174a969d36a42fca76e086ecfb75ecf46 https://github.com/flybywiresim/a32nx/pull/1607

**Comment by Kimbyeoungjang** [comment]
Are you change the sensitivity in settings? It seems asobo bug that autopilot is not working when sensitivity is default condition

**Comment by Benjozork** [comment]
Cannot reproduce here.

**Comment by Flextemp** [comment]
Same issue after update

**Comment by kyleawayan** [comment]
> 
> 
> Are you change the sensitivity in settings? It seems asobo bug that autopilot is not working when sensitivity is default condition

Looks like it was my sensitive joystick taking over autopilot. Unplugged it and autopilot started working again.

**Comment by Flextemp** [comment]
I really appreciate your help solving the problem, i definitely going check
that out, thanks.
Have good flights!

Il giorno ven 30 ott 2020 alle ore 04:02 Kyle Awayan <
notifications@github.com> ha scritto:
