### ISSUE TITLE
[BUG] First officer's MCDU buttons is not working

### ISSUE THREAD

**Issue by Kimbyeoungjang** [flybywiresim/a32nx#1612]
**Mod Version**

 Master

**Describe the bug**

First officer's knobs working good but MCDU buttons is not working. Can click but not working

**To Reproduce**

1. Spawn on aircraft
2. Move to first officer's seat
3. First officer's MCDU is not working

**Expected behavior**

Can controll mcdu

**Actual behavior**

Buttons can click but not working

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Duplicate of #1058
