### ISSUE TITLE
Not able to use current master version. only able to use v4.0?

### ISSUE THREAD

**Issue by kevjell** [flybywiresim/a32nx#1613]
**Mod Version**

**Describe the bug**

**To Reproduce**

1. I've downloaded and installed both versions properly but when i try to use to most current master version, MSFS reverts to their build with A320NX in community folder
2. Of course I'm trying to see if anyone has been able to fix the issues caused by this useless update
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Please respect the issue template, it saves everyone time.

FYI, the last stable version is not supported when MSFS updates. Use the development version, this issue is fixed.

> Of course I'm trying to see if anyone has been able to fix the issues caused by this useless update

Please go to Discord before opening an issue if you have doubts other people are having it.
