### ISSUE TITLE
[BUG] The trigger distance of the APU fire test button is too short

### ISSUE THREAD

**Issue by javaflans** [flybywiresim/a32nx#1615]
Mod Version
Last version by 30,Oct,2020

Describe the bug
The APU test button accidentally touched the upper cover, and the trigger distance was too short

To Reproduce

    Load the aircraft without flight plan
    Click the central APU test button
    It is the APU red top cover that is triggered, not the test button 

image

before
![圖片](https://user-images.githubusercontent.com/67624258/97671020-69722d00-1ac2-11eb-9548-1fdfbcf6c681.png)

after
![圖片](https://user-images.githubusercontent.com/67624258/97671046-7b53d000-1ac2-11eb-9b5c-98356a0f4a25.png)

Discord username (if different from GitHub):
dc1ps2

**Comment by RiderKickingMarco** [comment]
Can confirm this occasionally happens to me as well in the latest master.

**Comment by noga-aviator** [comment]
i cannot use the fire test, it always triggers the cover

**Comment by lukecologne** [comment]
What is the problem? Just close the cover again...

**Comment by Aleksandaarrr** [comment]
The problem is (as I can see it), that the touch area for the cover is a rectangle dimensions of the whole cover, meaning that the agent button and test button are covered with that touch area. I will try to look into this and solve :)
