### ISSUE TITLE
[REQUEST] Web MCDU

### ISSUE THREAD

**Issue by St54Kevin** [flybywiresim/a32nx#1616]
**Describe the feature you'd like to see implemented**

A version of the MCDU that is hosted on the MSFS computer and can be opened on any Browser (Phone, Tablet) in the network via an IP:Port adress like the XP Tool Web FMC [ is doing.

**References**

https://store.x-plane.org/WebFMC-Pro_p_814.html](url)

**Comment by St54Kevin** [comment]
> This is very similar to #1317

But also completely different ;)

**Comment by SecOpsSteve** [comment]
With the frequent need to interact with the MCDU, WebFMC-like capability is most desirable.

**Comment by DanP77** [comment]
This is a really useful request.
We can use a Smartphone* or a Tablet to manage separately (and with a touch screen) a complete MCDU.
A lot of interaction with A320 Systems, is done by MCDU.

* a good idea is provide the ability to zoom to be easily managed by different screen size...

**Comment by andrejetcat** [comment]
It would be such a nice Feature! I used "virtual avionic - virtual CDU" back in FSX and it works GREAT! only connecto to the same WLAN network, start a little program on the FS-maschine, and you could have your FMS/CDU on your device. :) I hope it is possible in the future!

**Comment by joeherwig** [comment]
Fully agreed.
See also FSLabs mod: https://github.com/joeherwig/fslabs-mcdu

**Comment by wpine215** [comment]
cc: @tyler58546
