### ISSUE TITLE
[BUG] Airplane rolling from left to right with A/P on

### ISSUE THREAD

**Issue by ErikNL80** [flybywiresim/a32nx#1617]
**Mod Version**
Master, latest build

**Describe the bug**
I am currently in a flight from LIRQ to ESGG at FL340. The airplane is heavily rolling from left to right, have never seen this behaviour in previous versions. It looks like the plane is way too sensitive.

**To Reproduce**
1. Plan an IFR flight 1 hour or so
2. Fly up until FL340 or so
3. Notice airplane behaviour and a/p.

**Expected behavior**
I would expect the plane to react to winds or turbulence, but in a smooth way.

**Actual behavior**
Now it looks like the aircraft is floating on waves on the sea...

**References**
n/a

**Additional context**
Issue occurs since the latest patch #5.

**Comment by ErikNL80** [comment]
Disabling the A/P immediately solves the issue...

**Comment by Rameyuk** [comment]
Are you on Legacy flight model, by any chance? I'm on Modern flight model and I'm not experiencing this issue.

**Comment by ErikNL80** [comment]
No, I am using the modern flightmodel.

**Comment by ChruutvoLuzi** [comment]
Try using a deadzone on your stick/yoke.
That fixed it for some users

**Comment by ErikNL80** [comment]
Is already set (mandatory for an Xbox Controller ;)) Never had issues before, start occuring after this patch... Disabling the autopilot and everything is smooth.

**Comment by ErikNL80** [comment]
Seems to be an issue in vanilla as well. See multiple posts on Facebook about this.

**Comment by Benjozork** [comment]
Disabling and enabling the autopilot fixes this issue.

Sadly this is not something we can fix as the autopilot is managed by MSFS.

We are working on our own custom autopilot - stay tuned.

**Comment by ChruutvoLuzi** [comment]
I actually have the same issue now even with AP off

https://cdn.discordapp.com/attachments/314015589595086848/772198186035052605/Microsoft_Flight_Simulator_2020.10.31_-_21.37.35.01.mp4

i dont know if this is turbulence but its really weird

**Comment by FS2020Paul** [comment]
Turning AP off fixes issue for a few minutes, but then it returns. I experienced this KDEN to KJAC and back KJAC to KDEN between FL220 and FL350. Winds were quartering headwind and crosswind at times, 50-70 knot winds. This did not happen on prior versions. Thanks FBW for an awesome A320!

**Comment by wpine215** [comment]
Fixed with latest Asobo patch
