### ISSUE TITLE
[BUG] MCDU no FPLN 

### ISSUE THREAD

**Issue by Onkelpuh** [flybywiresim/a32nx#1619]
I downloaded the current beta of the mod via AutoDownloader and when I load the flight after creating a flight plan in MSFS and sit in the A320, the MCDU FPLN only shows an empty page but no flight plan
![MCDU FPLN](https://user-images.githubusercontent.com/71586280/97707887-3e82db80-1ab8-11eb-9cce-db4d65869b01.png)

**Comment by Venorcis** [comment]
This screenshots doesn't look like the current A32NX MCDU?

**Comment by Sateprikkert** [comment]
I encounter the same issue since patch 5.

**Comment by Onkelpuh** [comment]
> Diese Screenshots sehen nicht aus wie die aktuelle A32NX MCDU?

the cockpit design is not the original but an extra mod that changes the original blue cockpit

**Comment by hairagon** [comment]
Exactly the same here. Also noticed the PFD and other instruments are not on when APU power only is available. External power and / or engine generators OK. Not sure if this is by design.

**Comment by Biniou671** [comment]
Having the same issue also, since patch#5.
Batteries ON, ok
GPU ON, ok
A32NX MCDU screen full black, even with brightness at max.
All others screens, no issue.

**Comment by Benjozork** [comment]
Hello everyone, you seem to be using the 0.4.0 version which is incompatible with the new MSFS patch. Please use the development version.

**Comment by Onkelpuh** [comment]
the display of the route works as long as you manually enter the start/finish xxxx/xxxx but as soon as you enter approach or depature the flight plan is gone and only empty page as in the picture above

**Comment by Onkelpuh** [comment]
> Hello everyone, you seem to be using the 0.4.0 version which is incompatible with the new MSFS patch. Please use the development version.

I had when I had the problems yesterday the current beta extra reloaded but I will test it again afterwards with the latest version

**Comment by hairagon** [comment]
I did try that last evening and flying with it now, thanks.

 

 

Best Regards
Charles Cartmel

BE CAREFUL

STAY SAFE

**Comment by Onkelpuh** [comment]
I downloaded the current beta from the mod and still got this error, as soon as you load a route or create it manually you get the empty black page * untitled * in the MCDU

**Comment by Onkelpuh** [comment]
**Error was identified ´by another simmer here on github**

The problem is the Navigraph tool for the MSFS which brings the current Airac into the Flusi

I just tested it and deleted the navigraph folder from the community folder and it is actually because of this that the flight plan is no longer displayed
We can therefore assume that navigraph has to improve and adapt its tool to the current update

**Comment by Sateprikkert** [comment]
I don’t use navigraph when I reported this bug. Installed development version and it seems to work OK.

**Comment by anwer202** [comment]
![بدون عنوان](https://user-images.githubusercontent.com/73133415/179373631-fcbeaaf8-d709-4f85-a124-dcc42c420aae.png)
I have the same problem
