### ISSUE TITLE
[BUG] Packs fault light are on during flight.

### ISSUE THREAD

**Issue by Tonyehrd** [flybywiresim/a32nx#1620]
**Mod Version**
Latest DEV version from the installer.

**Describe the bug**
Packs 1 & 2 lights are on during flight with engines running.

![prob 2](https://user-images.githubusercontent.com/37801826/97708797-a259d400-1ab9-11eb-9303-f49e6205bbef.png)
![Prob 1](https://user-images.githubusercontent.com/37801826/97708807-a5ed5b00-1ab9-11eb-8830-d79dc1ec3d04.png)

**Additional context**
I tried to start the apu hoping the error lights went away, but without success. No notification on the ECAM.

**Was this working before/when did the issue start occurring?**
Yes, with the version before MSFS updated.

**Is this a problem in the vanilla unmodded game?**
Dont know, didnt test it.

Discord username (if different from GitHub): Tonyehrd

**Comment by Venorcis** [comment]
Doesn't happen to me on latest MSFS with latest master.

**Comment by James3221** [comment]
this is due to all the logic being tied to the screen. with the new additions coming soon, this won't be a problem

**Comment by frankkopp** [comment]
Workaround: When selecting Bleed page the fault light disappears.

**Comment by wpine215** [comment]
Basically a duplicate of #1593 so closing for now
