### ISSUE TITLE
[BUG] NO Logo light on model

### ISSUE THREAD

**Issue by Lamao2244** [flybywiresim/a32nx#1621]
**Mod Version**
 Master
built: 2020-10-30T02:12:21+00:00
ref: refs/heads/master
sha: 772b70172905237d6db8dfe6fcf58701708c15b0
actor: Benjozork
event_name: push

**Describe the bug**
 Logo light on the ext will not light up even though its switched on in the cockpit

**To Reproduce**

1.Lauch Plane
2.Turn on the NAV/LOGO light
3.Monitor EXT tail

**Expected behavior**
Logo light should turn on when LOGO/NAV switch is on

**Actual behavior**
 No logo light can be seen on the exterior

**References**
Nil

**Additional context**
nil

Was this working before/when did the issue start occurring? On latest master

Is this a problem in the vanilla unmodded game? No

Lamao
Discord username (if different from GitHub):

**Comment by lukecologne** [comment]
This is intended, the logo light is only engaged if the landing gear is compressed or slats/flaps are extended.
