### ISSUE TITLE
[BUG] MCDU and Radio Displays Black

### ISSUE THREAD

**Issue by TXLBER** [flybywiresim/a32nx#1624]
**Mod Version**
Current Version of FS2020 & i used the Downloader Application of the MOD

**Describe the bug**
MCDU and Radio Displays appear fully black when doing the Cold and Dark Startup

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**
![MCDU](https://user-images.githubusercontent.com/73706392/97718417-35007000-1ac6-11eb-808e-f1d01404162e.jpg)

**Comment by lukecologne** [comment]
Fixed in latest master.
