### ISSUE TITLE
[BUG] MCDU not working

### ISSUE THREAD

**Issue by CoverdaleJ** [flybywiresim/a32nx#1625]
**Mod Version**
Latest STABLE version from the installer

**Describe the bug**
After update to MSFS 1.10.7.0 MCDU is not working. Shows black screen (can see brightness adjustment on the shade of black) with only a "/" in top right hand corner. Still able to add text to the scratch pad, but that is it.

**To Reproduce**
1. Update to MSFS 1.10.7.0
2. Fresh install of A32NX from installer, stable build
3. Load into any airport cold&dark, turn on EXT power + battery. All screens show typical "warmup 40 sec" but MCDU remains black. 

**Expected behavior**
MCDU should illuminate and function. 

**Actual behavior**
MCDU is black, with white "/" in top right hand corner. Data entry to scratch pad still possible.

**References**
![Test](https://user-images.githubusercontent.com/73707362/97721228-18ae0480-1ac1-11eb-9683-998c24670071.png)

Was this working before/when did the issue start occurring?
Yes, worked before, until updating MSFS.

Is this a problem in the vanilla unmodded game?
Yes, latest Microsoft/Asobo update.

**Comment by mathis650** [comment]
this is a known issue. it's fixed on the master build, so use that for now

**Comment by lukecologne** [comment]
Duplicate, and already fixed.
