### ISSUE TITLE
[BUG] AVAIL/REV indication are missing 

### ISSUE THREAD

**Issue by Cthulhus** [flybywiresim/a32nx#1626]
**Mod Version**

built: 2020-10-30T02:12:21+00:00
ref: refs/heads/master
sha: 772b70172905237d6db8dfe6fcf58701708c15b0
actor: Benjozork
event_name: push

**Describe the bug**

AVAIL message during engine start is gone since last update. I'm using the DEV version (uptodate)
Same for REV (reverse)

**To Reproduce**

1. Star the engine, the new added indication "AVAIL" is now missing on the upper ECAM
2. Use the reverse when engines are on. You'll not see the REV on the upper ECAM
3.

**Expected behavior**

We should see AVAIL or REV.

**Actual behavior**

Nothing appear

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Carter633** [comment]
Didn't follow the template but I can personally say I've noticed this today too on a full flight I ran. Both the above have disappeared since latest patch
