### ISSUE TITLE
[BUG] Still game-breaking issues after MSFS oct 29th update, both stable and master

### ISSUE THREAD

**Issue by vlbreda** [flybywiresim/a32nx#1627]
**Mod Version**

Latest stable (16.10 oct 30th) & latest dev, used last version of installer

**Describe the bug**

**Stable**: MCDU not working, PFD not working, ND not coming online. EICAS gives 'NAV TCAS FAULT'-warning, APU not working
**Dev**: systems are working but descent rate is still far too low to fly a STAR. Fastest descent-rate in APPR-phase is around 1000 ft/minute tops, which makes it impossible to fly allmost any ILS- or RNAV-approach

**To Reproduce**

1. Install latest mod
2. Open flight. Stable version has mentioned systems not working (MCDU, PFD), dev version has descent-rate issue.
3.

**Expected behavior**

Hoped the plane would work fine....

**Actual behavior**

Plane is not useable now for complete flight

**References**

**Additional context**

Was this working before/when did the issue start occurring?
After MSFS oct 29th update

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by lukecologne** [comment]
First of all: 

> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning

Second:
> Stable: MCDU not working, PFD not working, ND not coming online. EICAS gives 'NAV TCAS FAULT'-warning, APU not working

As you said yourself, it's fixed, don't report a fixed issue.

> Dev: systems are working but descent rate is still far too low to fly a STAR. Fastest descent-rate in APPR-phase is around 1000
ft/minute tops, which makes it impossible to fly allmost any ILS- or RNAV-approach 

This is not really related to the update.
