### ISSUE TITLE
[BUG] major systems not working in stable version from v0.6 Downloader

### ISSUE THREAD

**Issue by flytester** [flybywiresim/a32nx#1628]
**Mod Version**

Latest stable as in v0.6 FBW downloader

**Describe the bug**

-removed previous mod
-updated MSFS with thursday's latest update
-downloaded v0.6 downloader from FBW
-installed stable version of mod
-lot of things don't work anymore....... PFD, flight computer, APU.... see screenshot.

**To Reproduce**

1. As mentioned above
2.
3.

**Expected behavior**

I read the bug reports since yesterday, and thought everything was updated in accordance with the MSFS-update. Seems not to be the case yet.

**Actual behavior**

See screenshot below + description above,

**References**

![image](https://user-images.githubusercontent.com/73710754/97729714-41d79080-1ad3-11eb-94f3-15c6b8726969.png)

**Additional context**

Was this working before/when did the issue start occurring?
Mod worked fine before MSFS update

Is this a problem in the vanilla unmodded game?
No, unmodded version seems to work fine. Hope this is fixed soon or someone can tell me if I'm doing anything wrong......

Discord username (if different from GitHub):

**Comment by lukecologne** [comment]
>  -installed stable version of mod

stable version is not compatible with the new MSFS update. If you want to use the mod, you need to use latest master.
