### ISSUE TITLE
[BUG] Dark MCDU since last patch 

### ISSUE THREAD

**Issue by DominikPilot** [flybywiresim/a32nx#1629]
**Mod Version**
built: 2020-10-15T01:38:50+00:00
ref: refs/heads/master
sha: a72a977f0b5c74eab9396bab64cb16f6cc4c8120
actor: Benjozork
event_name: push

**Describe the bug**
Since the last patch from MSFS2020 the MCDU of the A320 ist totally dark. Also the plane doesn't align the IRS. So I don't have the primary flight display...Is it because of the patch? I alreday unistalled and tried again, but no chance to fix the problem. 

**Expected behavior**
If I start the plane, the MCDU should be there. The plane should align the IRS after a few min.

**Comment by lukecologne** [comment]
You are using 0.4, that is not supported with the MSFS update.
