### ISSUE TITLE
Aural Warnings Incorrect

### ISSUE THREAD

**Issue by Al-Roker** [flybywiresim/a32nx#163]
(I'm not super experienced in this field so I might be wrong about some of these things) 

Overspeed warning is currently aurally annunciated whereas it should be just a warning tone like the "L/G not down" alert. I believe there is a "Speed, Speed" warning too, similar to the airspeed low warning found on Boeing aircraft that is not present. The Terrain awareness warnings (I.E. "Terrain ahead" and "Obstacle ahead etc." are not currently present as well as GPWS warnings like (I.E. "Pull Up" and "Don't Sink" etc.). Too Low Gear and Flap alerts are also not present. The stall warning may also not be correct but I am not 100% sure. In the BAA Training video "Basics of Stall Recovery on Airbus A320 FFS" around the 12:00 minute mark a different stall warning is played where the warning bell is constantly played throughout the stall. In other a320 simulator training videos, different stall warnings are also used, however, they seem to be standard a320s, not NEOs.

**Comment by SergeantTimelord** [comment]
The overspeed warning has been addressed by this commit: https://github.com/wpine215/msfs-a320neo/commit/4e2d624d4fe2a57e8c36a354705c3eff7ad16b97

**Comment by Al-Roker** [comment]
@SergeantTimelord 

Just tried it out, worked great. Thank you.

**Comment by lousybyte** [comment]
Related https://github.com/flybywiresim/a32nx/pull/997.

**Comment by hotshotp** [comment]
GPWS callouts have been addressed and implemented. stall warning is correct by default
