### ISSUE TITLE
[BUG] TCA Quadrant Airbus edition ENG 1-2 Turn on levers not work

### ISSUE THREAD

**Issue by DewSebastian** [flybywiresim/a32nx#1630]
**Mod Version**
Latest DEV version from the installer.

**Describe the bug**
TCA Quadrant Airbus edition Turn on ENG 1-2  levers not work，Original  A320 is work

**Expected behavior**
ENG 1 and 2 Start lever Turn on ENG start

**Actual behavior**
ENG 1 and 2 Start lever Turn on but not work

Was this working before/when did the issue start occurring?
This time updata add

Is this a problem in the vanilla unmodded game?
Original  A320 is work

**Comment by MoparCharger1969** [comment]
For clarity and testing purposes, here are the 4 commands mapped to Engine switch 1 (Button 3) on the quadrant...
set engine master 1
set starter 1
set engine 1 fuel valve
toggle engine 1 fuel valve
 
Change 1 to 2 for the same commands on the Engine 2 switch on the quadrant (Button 4)

You can test with these commands mapped to any button on any controller, but you'll need to press and hold the button to simulate the switch staying on.  So, just to be clear, it does not appear to be unique to the TCA quadrant, but should be the same issue with any hardware controller trying to "flip" the engine switches.

**Comment by Saschl** [comment]
The issue lies in changes of the fuel systems in the latest patch (probably regarding the quadrant implementation) that were not ported yet. Once the changes are ported, we should be fine :)

**Comment by MoparCharger1969** [comment]
> The issue lies in changes of the fuel systems in the latest patch (probably regarding the quadrant implementation) that were not ported yet. Once the changes are ported, we should be fine :)

Forgive my lack of development knowledge, but does this mean we are waiting for Microsobo to implement this?  Or is this something the FlyByWire team will need to do?

**Comment by Saschl** [comment]
No need to apologize! I guess FBW must adopt the changes from Asobo but I'm also not really experienced here. I'm currently fiddling around and making some progress. Perhaps I'll open a Pull Request to "fix" the issue later on if that's desired.

**Comment by c1be** [comment]
I can confirm this, both knob selector and master switches don't work, i tried to assign them again through controls, but still the same.

**Comment by SaltySaltcreek** [comment]
Not sure if this is clear from above but in the default plane these switches only work if you assign the Engine switches (button 3 and 4) on the TM Quadrant to **Set Engine 1 Fuel Valve** and **Set Engine 2 Fuel Valve**.  If you hover over the buttons in the plane it says Engine Master 1 and Engine Master 2 but these are not what the plane recognises.  

I re-checked **Set Engine 1 Fuel Valve** and **Set Engine 2 Fuel Valve** in the latest dev mod as of today and they did not work.  I hope this gives you more information.

**Comment by lionomega** [comment]
Work perfect!

**Comment by L1qu1d1c3** [comment]
Hello,

I've just bought the TC Quadrant today, and I have the latest A32NX (stable), and the latest patch that came out on December 11, and the engine switches do not worked. I've mapped the switches in any and all the possible combinations provided above and it still doesn't work.

Thanks

**Comment by MoparCharger1969** [comment]
Try using the latest DEV version and not the stable.  I'm not sure this fix was added to the current stable build yet.  It looks like it is tagged for stable build 0.5.0.
