### ISSUE TITLE
[BUG] All lights in cockpit on, buttons not working, animations(throttle, sidestick, etc) not changing.

### ISSUE THREAD

**Issue by 03vmate** [flybywiresim/a32nx#1631]
**Mod Version**
Both Stable and Master

**Describe the bug**
Nothing is clickable in the cockpit(mouse cursor doesn't change when hovering over clickable things, clicking doesn't do anything)
All lights are on, even though there's no power on the aircraft(button lights, panel lighting, etc, but ECAMs and PFDs are black
Aircraft is functional using keyboard/controller keybinds, but nothing happens in the cockpit(I can set throttle, flaps, etc with keyboard, and fly the plane with controller without any problems, but cockpit is totally unresponsive)
No errors show up in developer console

**To Reproduce**
Use A320neo. Bug present in every scenario I've tried.

Was this working before/when did the issue start occurring?
Never worked.

Is this a problem in the vanilla unmodded game?
Stock A320neo works

Discord username (if different from GitHub): Green@4747

**Comment by 03vmate** [comment]
Looks like FS is quite out of date, 1.7.14.0. Downloading updates, hopefully that fixes it.
Master was downloaded today, nothing else installed.

**Comment by Benjozork** [comment]
> Looks like FS is quite out of date, 1.7.14.0

That is most definitely the issue

**Comment by LogRol** [comment]
I have the same problem, but with a Wizzair livery installed.

**Comment by 03vmate** [comment]
Updating MSFS fixed my issue

**Comment by LogRol** [comment]
For me not :(

**Comment by Benjozork** [comment]
@LogRol when did you install the development version ?

**Comment by LogRol** [comment]
First of all I have installed the stable version and today.

**Comment by Benjozork** [comment]
@LogRol the stable version is not compatible with MSFS 1.10.7. please use the development version or wait for stable 0.4.1.

**Comment by LogRol** [comment]
Ah got it okay so I will try the development one and update with the responses :)

**Comment by LogRol** [comment]
I have put it into the same folder as before when it wasnt working and now it actually doesnt do anything the a320 is the default one weird...

**Comment by Benjozork** [comment]
@LogRol that usually means you drag and dropped the master archive - you need to use the "vmaster" release on GitHub or use the installer if you're not comfortable with that.

**Comment by LogRol** [comment]
oh yea I got the wrong folder sry give me a few min

**Comment by LogRol** [comment]
Same error, all lights are illuminated

**Comment by Benjozork** [comment]
Any liveries installed ? Any other mods ?

Try a COMPLETE clean install (delete and use installer) of the development mod and make sure you're on the latest MSFS.

**Comment by LogRol** [comment]
I have the Wizzair livery installed as I have wrote it before and only the Wizzair livery. I have done a complete reinstall while installing the development mod of the A32NX.

**Comment by Benjozork** [comment]
As I asked, please remove any liveries.

**Comment by Benjozork** [comment]
Try without any liveries.

**Comment by LogRol** [comment]
Okay

**Comment by LogRol** [comment]
Without liveries - same error - unresponsive cockpit, all lights illuminated

**Comment by Benjozork** [comment]
Honestly I don't know anymore, this is the only case where this has not worked.

Head over to the discord and see in the #help channel.

**Comment by Benjozork** [comment]
Do you have the "Your Control" shared cockpit addon ?

**Comment by LogRol** [comment]
As how I wrote before it is just the plain MFS2020 except the Wizzair livery however I have removed it for the testing period.

**Comment by truthz33k3r** [comment]
i have this issue too. downloaded the latest development version. only paid sceneries in the community folder. no liveries at all.

**Comment by Benjozork** [comment]
I have called multiple people with the exact same issue and reinstalling the dev version has always worked.

There's an unknown variable at play here.

**Comment by LogRol** [comment]
Okay, I will try to reinstall it without any addons just only the A32NX mod. Could you confirm that I need to download the developer build and the folder named "A32NX" need to be put into the Community folder?

**Comment by truthz33k3r** [comment]
I'm using the downloader if that makes any difference. I'll try to download the dev version manually and see how that goes.

**Comment by Benjozork** [comment]
> Okay, I will try to reinstall it without any addons just only the A32NX mod. Could you confirm that I need to download the developer build and the folder named "A32NX" need to be put into the Community folder?

Yes, but make sure the A32NX folder you place contains a "layout.json" file in it. Otherwise, you downloaded the wrong thing.

**Comment by truthz33k3r** [comment]
i can confirm downloading the dev version manually fixes this issue. something wrong with the installer dev version that is downloaded. i noticed too that the installer version downloaded close to 600mb. the standalone dev file was a bit over a hundred or so.

**Comment by LogRol** [comment]
Same e

> > Okay, I will try to reinstall it without any addons just only the A32NX mod. Could you confirm that I need to download the developer build and the folder named "A32NX" need to be put into the Community folder?
> 
> Yes, but make sure the A32NX folder you place contains a "layout.json" file in it. Otherwise, you downloaded the wrong thing.

Same errror as before. All lights are illuminated and I have a layout.json in the A32NX folder. Any more clues?

**Comment by truthz33k3r** [comment]
> 
> 
> Same e
> 
> > > Okay, I will try to reinstall it without any addons just only the A32NX mod. Could you confirm that I need to download the developer build and the folder named "A32NX" need to be put into the Community folder?
> > 
> > 
> > Yes, but make sure the A32NX folder you place contains a "layout.json" file in it. Otherwise, you downloaded the wrong thing.
> 
> Same errror as before. All lights are illuminated and I have a layout.json in the A32NX folder. Any more clues?

download this version. i used this and everything is back to normal. https://github.com/flybywiresim/a32nx/releases/download/vmaster/A32NX-master.zip

**Comment by LogRol** [comment]
I have downloaded just that.

**Comment by Oberstumfuher** [comment]
New update MSFS 2020 1.10.8.0

**Comment by CptRPeralta93** [comment]
i have the same problem, both my FS and 320nx are up to date

**Comment by CptRPeralta93** [comment]
![Sem Título 7](https://user-images.githubusercontent.com/72822967/97789275-0a421480-1bb7-11eb-94c1-97a2ea15d747.jpg)

**Comment by CptRPeralta93** [comment]
note that this was taken when the plane was supose to be cold and dark. all the buttons that are iluminated dont work

**Comment by LogRol** [comment]
Yep, same for me

**Comment by Benjozork** [comment]
@CptRPeralta93 @LogRol please try with the latest 0.4.1 release.

**Comment by LogRol** [comment]
Download the latest developer release?

**Comment by Benjozork** [comment]
> Download the latest developer release?

The 0.4.1 stable release.

**Comment by LogRol** [comment]
Okay, I got it, I'm downloading it now. Hope it works :D

**Comment by LogRol** [comment]
Same. In the cold and dark status every light is illuminated and nothing is responsive.

**Comment by CptRPeralta93** [comment]
well, it kind of work, the light problem on every button is almost fix, appart from the anti Ice switchs that still have the light on and dont work, also the regulators for cab temperature doesnt work either. Now i have a new problem, black screens. i´ll send the pictures

**Comment by CptRPeralta93** [comment]
![Sem Título 8](https://user-images.githubusercontent.com/72822967/97790780-73c82000-1bc3-11eb-80a1-0117f86ac0e8.jpg)
![Sem Título 9](https://user-images.githubusercontent.com/72822967/97790783-74f94d00-1bc3-11eb-8602-46a417521b12.jpg)

**Comment by CptRPeralta93** [comment]
note that the GroundPower is connected, thats why the light is on.

**Comment by Benjozork** [comment]
> note that the GroundPower is connected, thats why the light is on


Which version of the mod are you using ? Please paste the build-info.txt provided in the A32NX folder.

**Comment by LogRol** [comment]
For me its "v0.4.1"

**Comment by CptRPeralta93** [comment]
> > note that the GroundPower is connected, thats why the light is on
> 
> Which version of the mod are you using ? Please paste the build-info.txt provided in the A32NX folder.

v0.4.1

**Comment by Benjozork** [comment]
I'm afraid I'm gonna have to suggest a complete reinstall of MSFS because I have no idea what is causing this. I've tested with multiple people and could not manage to reproduce this bug.

Steps I suggest:

1. Reinstall MSFS
2. Do not install ANYTHING else. No liveries, no other mods, no planes, no weather engines, no navdata.
3. Install 0.4.1

**Comment by CptRPeralta93** [comment]
> I'm afraid I'm gonna have to suggest a complete reinstall of MSFS because I have no idea what is causing this. I've tested with multiple people and could not manage to reproduce this bug.
> 
> Steps I suggest:
> 
> 1. Reinstall MSFS
> 2. Do not install ANYTHING else. No liveries, no other mods, no planes, no weather engines, no navdata.
> 3. Install 0.4.1

i was hopping that i wasnt going to need to reinstall.. :`(  .. i had the black screen problem before, and after some updates on the A320nx the problem was solve, the thing that makes me sad is that all the problems appear after every single update of the game.

**Comment by mirahu92** [comment]
I have had the same issue after installing V0.4.1.   No difference with the default livery.  My sim looked the same as the image from CptRPeralta93 above.  

I reverted to V0.4.0 and the problem went away.

No issues with this version.

**Comment by bndzor** [comment]
Currently on all up to commit 517b7849488254f7df493c1414123210d92b62ca
Game updated, no liveries.

Starting at KLAX, gate 159

Here is a short video
https://debriage.com/files/5fa02ebe0e2d75fa02ebe0e376.mp4

**Comment by Benjozork** [comment]
@bndzor your mod seems to not have installed properly. (can be seen by the green-ish backlighting on the OVHD)

make sure you either use the installer or delete the mod folder before replacing it.

This is also not related to this issue. Please head to our discord for assistance.

**Comment by bndzor** [comment]
@Benjozork Thanks for clarifying that. I will give it a go!

**Comment by Inaxair** [comment]
I encountered a similar problem with Your control shared cockpit software. Did you have it installed too?

**Comment by Inaxair** [comment]
Also, can you provide a screenshot of the community folder as well as the path?

**Comment by yigitemres** [comment]
I think I found the problem. If you use this mod via 'git pull' A32NX folder doesn't include any layout and manifest file. You have to 'python build.py'.

**Comment by lukecologne** [comment]
No, do not run the python build script manually anymore. You need to run `npm run build`

**Comment by yigitemres** [comment]
@lukecologne I'm just using mod and don't have any dev info about it. I just create Makefile which git pulls and moves A32nx folder to the Community folder and run py script. Do I still need npm run in this use case?

**Comment by lukecologne** [comment]
Only run npm, not the python script, it will likely be removed in the near future. Just edit your makefile.

**Comment by yigitemres** [comment]
@lukecologne Thanks for the info. Have a nice day! :clinking_glasses:

**Comment by CptRPeralta93** [comment]
i´ve done, everything i know to correct the problmes whits the lights and the black screens and nothing work!! :´( I´m really sad because... someone know how to fix it? many thanks

**Comment by MisterChocker** [comment]
I assume the reason for this to occur was a bad installation?

**Comment by Benjozork** [comment]
Not reproduced.

**Comment by metronorth** [comment]
I use a pirated version of FS2020 ("copyright infringement" is a more accurate term) and just noticed this issue with a fresh re-install I performed yesterday to get FS2020 back down to 1.7.14.0 so that the network based content like Bing/3d buildings actually loads. I'll try whatever anyone has suggested here and suggest anyone else here be honest as to whether they too are using the "HOODLUM" edition ;) - side note, I'll buy the thing if anyone can confirm the network functions work with the latest patches with a legit copy via Steam, etc.

**Comment by Benjozork** [comment]
@metronorth Do not discuss piracy on this GitHub.

**Comment by metronorth** [comment]
My apologies ^^ did you delete my comment or do I need to? Take care.

**Comment by gamingatmax3090** [comment]
> i´ve done, everything i know to correct the problmes whits the lights and the black screens and nothing work!! :´( I´m really sad because... someone know how to fix it? many thanks

Hey, I know it's been 2 years, but did you ever find a solution to this problem? I have installed stable, experimental, and dev versions of the plane and also multiple older versions, all of which have the same problem. Seriously, I have tried E V E R Y T H I N G!

**Comment by CptRPeralta93** [comment]
Hi,

From that moment on, I only use the development version and it's working
super fine.

Happy flights

A domingo, 18/09/2022, 06:48, gamingatmax3090 ***@***.***>
escreveu:

**Comment by gamingatmax3090** [comment]
yes, but I have tried using the development version and reinstalling it many times. It does not work and I have the exact same error.

**Comment by Benjozork** [comment]
@gamingatmax3090 which version of the sim are you running ?
