### ISSUE TITLE
[BUG] Unable to start APU

### ISSUE THREAD

**Issue by Vanzan982** [flybywiresim/a32nx#1633]
**Mod Version**
Stable release 0.4.0 

**Describe the bug**
APU does not start while performing cockpit preparation check list. External power, fuel pumps and batteries are on. APU Master switch and APU Start switch indicate "on".
APU EGT temperature stays at the outside air temperature. Switching APU to off / on again and pressing the Start Switch shows XX as APU EGT temperature.
Seems triggered by the latest release of MSFS on 29th October 2020. Has been working before. 

**To Reproduce**
1. Perform Checklist.

**Expected behavior**
APU should start ;-)

**Actual behavior**
APU doesn't start. 

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Yes

Is this a problem in the vanilla unmodded game?
No.

**Comment by lukecologne** [comment]
Fixed in latest master, this has been reported multiple times, look at the previous issues (also closed) before reporting.
