### ISSUE TITLE
[BUG] No REV announcement on engine gauges

### ISSUE THREAD

**Issue by starvingjavi** [flybywiresim/a32nx#1634]
**Mod Version**
Dev

**Describe the bug**
When landing and applying reverse thrust no REV announcer comes on in the ECAM gauges

**To Reproduce**

1. Land
2. Apply reverse thrust
3. Check engine gauges

**Expected behavior**
Reverse amber and green announcers

**Actual behavior**
No reverse thrust announcers

**References**
Previous dev versions.

**Comment by lukecologne** [comment]
Duplicate #1626
