### ISSUE TITLE
[BUG] Changing V/S When in Selected Alt Mode

### ISSUE THREAD

**Issue by TheoBearman** [flybywiresim/a32nx#1637]
**Mod Version**
Master

**Describe the bug**

On the FCU, when selecting an altitude lower than the current level, engaging the selected altitude mode, and manually selecting a V/S, the V/S cannot be made shallower than the initial input unless a new altitude is selected, whereby the V/S resets.

**To Reproduce**

1. Enter cruise.
2. Change altitude to lower than current.
3.  Engage selected altitude mode.
4. Set V/S.

**Expected behavior**
V/S should be freely selectable.

**Actual behavior**
Once a V/S is set you cannot make it shallower, only steeper.

**References**

[Video of bug in gameplay](https://streamable.com/ehr2n0).

**Additional context**

Was this working before/when did the issue start occurring? Issue was not present before MSFS 1.10.7.0 update.

Is this a problem in the vanilla unmodded game? Unknown.

Discord username (if different from GitHub): theob

**Comment by FinalLightNL** [comment]
Apparantly this is fixed with using the earlier metric system, haven't tested it out myself yet.
might be a asobo issue

**Comment by TheoBearman** [comment]
Sorry, I don't follow.

**Comment by TheoBearman** [comment]
Reported on Zendesk. It does appear to be an issue with the new metric unit of measurement implementation as @FinalLightNL suggested. Not sure if it's something we can fix in the mod?

**Comment by Karlschen** [comment]
You must have switched to the metric system. Put it back on the US system and it should work again.
