### ISSUE TITLE
[BUG] MCDU and GPS alignment are not working after patch 5

### ISSUE THREAD

**Issue by torontoflyer** [flybywiresim/a32nx#1640]
**Mod Version**
0.4.0

**Describe the bug**
MCDU and ADIRS GPS alignment is not working with mod after patch 5 installation

**To Reproduce**
1. begin cold and dark flight using a320neo
2. turn ADIRS IR1 to IR3 to NAV (seems like there is no longer switching action, just the knob immediately turned to NAV position)
3. turn on bat 1 and 2, as well as external power; ECAM will show NAV TCAS FAULT instead of aligning NAV IR

**Expected behavior**
GPS alignment should start as soon as ADIRS switch is turned to NAV mode
MCDU should be working after external power is switched on

**Actual behavior**
No GPS alignment, even after waiting for 10 minutes. MCDU is not working.

**References**
ECAM message (ADIR switches are all in the NAV mode) and INOP MCDU:
![image](https://user-images.githubusercontent.com/73716850/97746126-362e9e80-1ac0-11eb-9e4d-5b1e46b2434a.png)

**Additional context**

Was this working before/when did the issue start occurring?
it was working fine before, just 

Is this a problem in the vanilla unmodded game?
there was no issue in vanilla unmodded game as the ADIRS switch are inop without A32NX

Discord username (if different from GitHub):

**Comment by lukecologne** [comment]
Fixed in master
