### ISSUE TITLE
MCDU and coms not working

### ISSUE THREAD

**Issue by Roboplayer999** [flybywiresim/a32nx#1641]
**Mod Version**
Version 4.0

**Describe the bug**
MCDU only displaying text you type and coms not displaying anything

**To Reproduce**
I just started msfs with the new update and yea

**Expected behavior**
MCDU only displaying text you type and coms not displaying anything

**Actual behavior**
MCDU only displaying text you type and coms not displaying anything

Was this working before/when did the issue start occurring?
after msfs update

**Comment by Benjozork** [comment]
Duplicate and doesn't properly fill template. Please use development version as it's fixed there.

Also, look through existing issues before creating new ones.
