### ISSUE TITLE
[BUG] Aircraft Decels Unrealistically Slowly After Landing

### ISSUE THREAD

**Issue by TheoBearman** [flybywiresim/a32nx#1642]
**Mod Version**
Master.

**Describe the bug**
As per the title. Low auto break, reverse thrust and flaps used in the video below.

**To Reproduce**

1. Attempt a normal landing.

**Expected behavior**

Aircraft realistically decels according to the inputs deployed.

**Actual behavior**
Aircraft decels much more slowly compared to what would realistically be expected with inputs deployed.

**References**
[Video](https://streamable.com/rpxq54) (exemplified through a rejected take-off scenario).

**Additional context**

Was this working before/when did the issue start occurring? Issue was not present before MSFS 1.10.7.0 update.

Is this a problem in the vanilla unmodded game? Unknown.

Discord username (if different from GitHub): theob

**Comment by CBGonzalez** [comment]
Hard to be sure but it seems the reversers did not engage and the breaks were fighting the trhust...

**Comment by TheoBearman** [comment]
I don't believe this was the case in this instance. Flew it the same as I've always done and this has never happened before.

**Comment by korundar** [comment]
In the video the reversers are clearly not engaged. Your throttle levers are in TOGA.

**Comment by lukecologne** [comment]
If you look closely, it says MREV in the top right corner of the E/WD. The reversers are engaged, there is a bug that causes the REV not to show up

**Comment by James3221** [comment]
A few things to check off, make sure spoilers are armed, you have proper flaps, you have MAX auto brake selected and that you use full reverse thrust on a rejected takeoff. If it is still decelerating at abnormal speeds, then it was broken when they updated the engine thrust for things like idle taxi.

**Comment by TheoBearman** [comment]
Can confirm all of these. Video might suggest otherwise but that is simply because of how I have keybinded reverse thrust on my local install.

**Comment by zachsutt** [comment]
I am having the same issue, seems like I can not pull the donut back far enough on N1 no matter what I do. As if the thrust 0% min for controls is set as 10% to start at 0%.

**Comment by st3ph29** [comment]
> Can confirm all of these. Video might suggest otherwise but that is simply because of how I have keybinded reverse thrust on my local install.

your auto brake is not set to max as it need to be set for a RTO

**Comment by zachsutt** [comment]
> > Can confirm all of these. Video might suggest otherwise but that is simply because of how I have keybinded reverse thrust on my local install.
> 
> your auto brake is not set to max as it need to be set for a RTO


Is it also normal for the aircraft to start rolling forward the second the parking brake isn't applied?

**Comment by zachsutt** [comment]
But even when the parking brake is off right before departure taxi the
aircraft lurches forward and accelerates by 1knot every 5 seconds

**Comment by hotshotp** [comment]
> > > Can confirm all of these. Video might suggest otherwise but that is simply because of how I have keybinded reverse thrust on my local install.
> > 
> > 
> > your auto brake is not set to max as it need to be set for a RTO
> 
> Is it also normal for the aircraft to start rolling forward with no brakes? I was a mechanic on these aircraft and we never had that while during engine runs.

yes that is normal, how the leap 1a behaves IRL

**Comment by zachsutt** [comment]
Thanks.

**Comment by airfirefighter** [comment]
reverse thrust is 45% N1 is that normal?I checked with my mouse the throttles and pop up only 20% reverse thrust engagement on thrust levers.Actual behavior isn't 100%?

**Comment by hotshotp** [comment]
> reverse thrust is 45% N1 is that normal?I checked with my mouse the throttles and pop up only 20% reverse thrust engagement on thrust levers.Actual behavior isn't 100%?

Yes reverse never goes 100% n1

**Comment by MisterChocker** [comment]
Could not recreate problem. Does it still persists?

**Comment by donstim** [comment]
Also, is this only an issue when using autobrakes, or does it also occur when using maximum manual braking?

**Comment by MisterChocker** [comment]
Any response? No? :(

**Comment by Benjozork** [comment]
No response from the author, closing.

**Comment by TheoBearman** [comment]
Hi all,

Sorry for the slow reply. This has been working fine since I switched to the latest stable master.

Happy to keep closed.

Many thanks!
