### ISSUE TITLE
[BUG] Distance to destination and waypoints not updated

### ISSUE THREAD

**Issue by ytr81** [flybywiresim/a32nx#1644]
**Mod Version**

built: 2020-10-30T14:43:53+00:00
ref: refs/heads/master
sha: d27b179b4bb9c3548f649197b1fd3f7919a8dbe5
actor: lousybyte
event_name: push

**Describe the bug**

In flight the FMS does not update the distance left to destination and next waypoint.

**To Reproduce**

1. Entered flightplan into FMS (EHEH/21 RONSA2K WOODY N872 MEDIL DCT DISAK DCT ARKIP DCT ARNAV DCT
LMG UN857 OSMOB DCT ARVID UT424 PPN UN857 TERTO TERTO7P GCRR/03) 
2. When in flight the time distance left to waypoints and destination is not updating.

**Expected behavior**

Updating of distances left to destination and next waypoint.

**Actual behavior**

Not updating the distance left to destination and next waypoint.

**References**

[https://youtu.be/5UaiT_2akr4](https://youtu.be/5UaiT_2akr4)

**Additional context**

**Was this working before/when did the issue start occurring?**
Did some flights earlier today and it did work.

Is this a problem in the vanilla unmodded game?
Does not apply

Discord username (if different from GitHub): YouriNL

**Comment by lars-reimann** [comment]
Related to #1622.

**Comment by lousybyte** [comment]
Work is being done on #1652.

**Comment by MisterChocker** [comment]
Isn't this fixed in latest master?

**Comment by lousybyte** [comment]
Should be fixed indeed.
