### ISSUE TITLE
[BUG] No working cdu/apu's

### ISSUE THREAD

**Issue by cellotako** [flybywiresim/a32nx#1646]
**Mod Version**

4.0.0

**Describe the bug**

I cant turn on APU and CDU shows nothing.

**To Reproduce**

update MSFS2020
re-install A32nx
starts from gate
fton CLDDRK, starting procedure

**Expected behavior**

starts APU
shows cdu

**Actual behavior**

nothing happened

**References**

https://youtu.be/jKxdNXX2xek

**Additional context**

Was this working before/when did the issue start occurring?

yes, last varsion of MSFS2020, this mod completely worked. I've tried to re-install and Reboot already.

Is this a problem in the vanilla unmodded game?

Yes.

Discord username (if different from GitHub):
__Cellotako#1652

**Comment by lukecologne** [comment]
Fixed

**Comment by cellotako** [comment]
Already fixed before or just fixed?
Should I use development version?

**Comment by cellotako** [comment]
okay I’m now using development version thank you

> 2020/10/31 6:02、琳 内田 <cello_rin_uchida@yahoo.co.jp>のメール:
> 
> ﻿Already fixed before or just fixed?
> Should I use development version?
