### ISSUE TITLE
Can’t slow down the plane on descent 

### ISSUE THREAD

**Issue by dmoranr** [flybywiresim/a32nx#1647]
**Mod Version**
 V6 development mod

**Describe the bug**

When descending to destination, I can’t reduce speed even using spoilers. My descent rate was at 1700 and my n1 was at 23, and still couldn’t reduce speed. 

**To Reproduce**

1. Descending 
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?
After the sim update I also updated the A320NX folder 
Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):
Dmoranr

**Comment by Fiorentoni** [comment]
I have the same problem, even with full speed brakes and a normal descent at 1800 FPM I cannot slow down to approach speed or even flap extension speed

**Comment by lukecologne** [comment]
Duplicate #1638

**Comment by jer029** [comment]
I'm not sure this should be closed...or perhaps needs to be reopened.  The Master version I just downloaded today is doing this.  Plane won't slow down and speed brakes seem to offer no resistance or drag.
