### ISSUE TITLE
pfd attitude indicator[BUG] INSERT TITLE HERE

### ISSUE THREAD

**Issue by buju2** [flybywiresim/a32nx#1648]
PFD not displaying IF I take A32NX folder away it works.

![image](https://user-images.githubusercontent.com/73714742/97759335-34240a00-1ad7-11eb-8984-8550016f772b.png)
 

**Mod Version**

Using the Development Version

**Describe the bug**

PFD not displaying IF I take A32NX folder away the PFD works. I deleted all my Liveries and the issue is the same.

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning
