### ISSUE TITLE
[BUG] weird light (ldg light ?)

### ISSUE THREAD

**Issue by noga-aviator** [flybywiresim/a32nx#1649]
**Mod Version**
latest master

**Describe the bug**
as you can see there is a weird light that seems to be a landing light. It is facing a weird direction and is placed in the middle of a window 
![image](https://user-images.githubusercontent.com/35369933/97760910-96473400-1b04-11eb-9e0d-55c520c527dc.png)

**To Reproduce**
turn on landing light

Was this working before/when did the issue start occurring?
i think this wasn't an issue before last msfs patch

Is this a problem in the vanilla unmodded game?
no

**Comment by lukecologne** [comment]
This is the wing light, not the landing light.
