### ISSUE TITLE
[BUG] Can't Align IR

### ISSUE THREAD

**Issue by CaptainRiles** [flybywiresim/a32nx#1654]
**Mod Version**
master
built: 2020-10-30T19:53:43+00:00
ref: refs/heads/master
sha: 0c0e40c59e3fbd4ee4da7583033cebb939e9fb49
actor: AdenFlorian
event_name: push

**Describe the bug**

When loaded at a gate cold and dark, I cannot turn the ADIRS knobs to align the IR this means I cannot fly the plane properly with no alignment. A temporary fix can be to start on the runway where it is auto-aligned

**To Reproduce**

1.Spawn at gate cold and dark
2.Try to turn ADIRS knobs to align IR
3.

**Expected behavior**

The knob to turn and alignment to begin

**Actual behavior**

There was no tooltip or anything when mouse was over the knobs, also couldn't turn the knobs. Plane not aligned

**References**

![Microsoft Flight Simulator - 1 10 7 0 31_10_2020 03_53_34](https://user-images.githubusercontent.com/73729828/97770647-09fd3700-1b2d-11eb-8862-1452ca2a30e7.png)

**Additional context**

Was this working before/when did the issue start occurring?
Started occurring after the latest MSFS2020 Asobo patch.
Is this a problem in the vanilla unmodded game?
ADIRS is auto-aligned in vanilla

Discord username (if different from GitHub):
Riles#1349

**Comment by Benjozork** [comment]
Hello, do you have the "Your Control" addon installed ?

**Comment by CaptainRiles** [comment]
Hey, yeh I do. I guess this breaks the mod?

**Comment by CaptainRiles** [comment]
> Hello, do you have the "Your Control" addon installed ?

Hey, yeh I do. I guess this breaks the mod?

**Comment by Benjozork** [comment]
It's not compatible with the newest MSFS update yet.

**Comment by Robdun26** [comment]
What is "your control" addon?  I have the same problem.

**Comment by Benjozork** [comment]
@Robdun26 it's a shared cockpit program.

You are probably using an old development version or the stable version. Update to the latest version.

**Comment by Rikenbacker** [comment]
I have same problem. IR align timer stoppend at 7 minutes.
I didn't have "your control" addon. I have latest dev version.

**Comment by Rameyuk** [comment]
Even though it's no longer animated, I can still turn the knob to align the IRs
If you're coming from a previous stable version. I find it's better to completely delete the A32NX mod folder from the community folder and do a fresh installation of the development version. It's to ensure you're deleting all the legacy or garbage files and config which may (or may not) affect the next installation.

**Comment by Robdun26** [comment]
TCAS ALIGN FAULT AND NO DISPLAYSent from my Samsung Galaxy smartphone.
-------- Original message --------From: Rikenbacker <notifications@github.com> Date: 2020/10/31  10:45  (GMT+02:00) To: flybywiresim/a32nx <a32nx@noreply.github.com> Cc: Robdun26 <robdun26@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [flybywiresim/a32nx] [BUG] Can't Align IR (#1654) 
I have same problem. IR align timer stoppend at 7 minutes.
I didn't have "your control" addon. I have latest dev version.

**Comment by lukecologne** [comment]
How did you install the mod? Via installer or github?

**Comment by Rikenbacker** [comment]
Now I reinstall mod. Deleted folder from community, and install again.
PROBLEM WAS SOLVED!

**Comment by lukecologne** [comment]
@CaptainRiles It looks like an installation problem for you as well.

**Comment by CaptainRiles** [comment]
> @CaptainRiles It looks like an installation problem for you as well.

Yes, it was due to the 'Your Control' software not being compatible with the latest MSFS patch.
