### ISSUE TITLE
Load saved Flightplan as a company route

### ISSUE THREAD

**Issue by HoloByteus** [flybywiresim/a32nx#1656]
**Is your feature request related to a problem? Please describe.**

This is a of a quality of life feature request for those that don't want to have to enter FMS flight plan data manually.  The user would use the Company route FMS feature to load a previously saved flight plan overwriting any existing flight plan.

**Describe the feature you'd like to see implemented**

Upon selecting Company Route in the FMS a list of flight plans previously saved could be loaded into the FMS.  This would save the user from both having to enter a flight plan manually in the FMS and enable this feature which actually exists.  Turn arounds or continuations of flights would be possible without the need to return to the Flight planner and start a new flight.  If a list can't be displayed then just an option to Enter the flight plans name and load it as done with XP11 737 shown in the video I attached below.

**References**

If you really want to shoot for realism you could even examine the chosen airline by requiring the user to enter an ICAO airline code as the Flight Number when starting a flight like AAL1501 and then reference actual routes used between the user entered orig/destination. in a database.  There's a user that's created several airline routes here: https://flightsim.to/discover?s=greatceo.  I can't attest to their accuracy however.

I'd think just allowing users to load a saved flight plan would be easier to implement and offer flexibility.

**Additional context**

Here's an implantation of a similar feature for XP11 737
https://www.youtube.com/watch?v=HbsLWHL5WXo&ab_channel=SimsSmith

Discord username (if different from GitHub):
HoloByteus#8435
**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by ukflyer** [comment]
+1 for this :)

**Comment by Lessar277** [comment]
I proposed something similar in my comment on #1684. I think these two feature requests could be merged.

**Comment by mohamed-abdellatef** [comment]
Same request, thank you for the hard work hope you add compatibility to pfpx soon.

**Comment by jessebrust** [comment]
I'd love to see this implemented. +1
