### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by regisbiass** [flybywiresim/a32nx#1657]
**Mod Version**
built: 2020-10-31T04:21:14+00:00
ref: refs/heads/master
sha: b3d691f5df63bfa45ca779a0f2941dbdc7bae499
actor: Benjozork
event_name: push

**Describe the bug**
Lined up on the runway (say EIDW), Take off...As the plane rolls at around 100 kts, it s veers to the left.

**To Reproduce**

Lined up on the runway (say EIDW), Take off...As the plane rolls at around 100 kts, it s veers to the left.

**Expected behavior**

Rudder is normal, the plane should roll lined up and not veer to the grass

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by robertmacnair** [comment]
What were the winds doing?

**Comment by regisbiass** [comment]
Hi Robert,

The wind is gusty....I have been using real weather. I just tested this now.

EIDW  (runway 28), try it.

Live weather.

Thanks

Best Regards,

Regis Biassala

Tel: 00353864052190

________________________________

**Comment by Carter633** [comment]
Probably had a 40kt crosswind and didn't take that into account as he was on the takeoff roll / rotate

**Comment by James3221** [comment]
can you please add a title to the bug report

**Comment by regisbiass** [comment]
I will test back on calm weather and report back

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by lukecologne** [comment]
Please add a title

**Comment by hotshotp** [comment]
please follow issue template and remove the line or else the issue will be closed

**Comment by regisbiass** [comment]
Hi,

Please close the issue.

Thanks,
Regis

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by lukecologne** [comment]
You can close the issue yourself if you want to
