### ISSUE TITLE
[BUG] Cruise altitude only filled with Cost Index of 30

### ISSUE THREAD

**Issue by ErikNL80** [flybywiresim/a32nx#1658]
**Mod Version**
Master

**Describe the bug**
If you enter a Cost Index other than 30 in the MCDU, Cruise altitude and temp are not automatically filled.

**To Reproduce**

1. Create an IFR flightplan
2. Load the plane cold & dark
3. Align IRS and fill CI of 30
4. Notice the Cruise altitude and temp are automatically filled
5. Repeat steps 1 to 4 with another CI, like 20 or so.

**Expected behavior**

I would expect altitude and temp to be filled regardless of CI value.

**Actual behavior**

Cruise altitude and temp are only filled with a CI of 30.

**Comment by MisterChocker** [comment]
Does the altitude gets automatically filled on change/set CI? I don't think so because the CI has nothing to do with your cruise alt.
Temperature will be set when cruise altitude is set.

**Comment by ErikNL80** [comment]
Hi, yes, you have 2 lines below each other. Top line is CI. Set it to 30 and notice altitude/temp (second line) are filled automatically. If you choose another CI value it is not. I would expect the cruise altitude and temp automatically filled if you use a flightplan, it can be derived automatically since it is known.

**Comment by MisterChocker** [comment]
> Top line is CI. Set it to 30 and notice altitude/temp (second line) are filled automatically

I still don't get why the altitude gets auto filled on entering CI.

**Comment by MisterChocker** [comment]
This issue needs reference

**Comment by MisterChocker** [comment]
Closing since no response from op.
