### ISSUE TITLE
[BUG] Pressing ESC to enter menu and exiting will cause flaps/speed brakes to deploy fully

### ISSUE THREAD

**Issue by SaltySaltcreek** [flybywiresim/a32nx#1659]
**Mod Version**
<Dev version>
<built: 2020-10-31T04:21:14+00:00
ref: refs/heads/master
sha: b3d691f5df63bfa45ca779a0f2941dbdc7bae499
actor: Benjozork
event_name: push
>

**Describe the bug**

Pressing ESC to go to the menu in game and then exit.  Once you exit the menu the flaps and speed brakes will start to fully deploy.

**To Reproduce**

1. While in the A320 press ESC
2. Exit menu
3. Watch speed brakes/flaps deploy

Note:  Speed brake level may not move but if you hover over it it will say 100%.

**Expected behavior**

Nothing when exiting the menu

**Actual behavior**

The moment you leave the in game menu the flaps and speed brakes deploy.

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Yes

Is this a problem in the vanilla unmodded game?

Yes.

Saltcreek (in discord)

**Comment by ErikNL80** [comment]
I am in flight now, and I cannot reproduce the issue now. Pressing ESC, wait a few seconds in the menu and the ESC again to continue the flight, nothing happens...

**Comment by SaltySaltcreek** [comment]
I must apologise.  It appears when I downloaded the dev mod (or the new patch) the key bindings for flaps was remapped on my quadrant to deploy flaps (not sure what button it is but I deleted the mapping).  I thought it was mod related but it is not. Thanks,  Sent from Mail for Windows 10 From: ErikNL80Sent: 31 October 2020 11:05To: flybywiresim/a32nxCc: SaltySaltcreek; AuthorSubject: Re: [flybywiresim/a32nx] [BUG] Pressing ESC to enter menu and exiting will cause flaps/speed brakes to deploy fully (#1659) I am in flight now, and I cannot reproduce the issue now. Pressing ESC, wait a few seconds in the menu and the ESC again to continue the flight, nothing happens...—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by DewSebastian** [comment]
Me too
[Video](https://youtu.be/F2spNy0flo8)

**Comment by ChruutvoLuzi** [comment]
Do you use the TCA Quadrant?

**Comment by DewSebastian** [comment]
> Do you use the TCA Quadrant?

Yes

**Comment by ChruutvoLuzi** [comment]
Unbind the flaps and spoiler axis, i had the same issue.

**Comment by MisterChocker** [comment]
this is not a bug from the aircraft, I have the TCA Quadrant my own, removing flaps axis (which are not even real buttons) will do the job.

@Benjozork is this issue still relevant?

**Comment by dcherrie** [comment]
@MisterChocker they have already bound the two accessories that aren't released that connect via the SATA connections underneath the quadrant. Am guessing MSFS chucks a hissy fit when it realises those SATA connections aren't there and deploys to the wrong end of the axis.
