### ISSUE TITLE
[BUG] MCDU screens blank MSFS2020 1.10.7.0

### ISSUE THREAD

**Issue by MedicoreV8** [flybywiresim/a32nx#1661]
**Mod Version**
V0.4.0

**Describe the bug**
After starting up the airplane (Ext. Pwr, Batteries, APU) the MCDU screens and Radio Frequency screens remain completely blank.
(https://ibb.co/7yt97Hp).
This wasn't the case before I updated MSFS2020 2 days ago.

**To Reproduce**
1. Start the game, Load up a flight plan, select the A320 and click Fly.
2. Start Ext. Pwer, Batteries, APU
3. MCDU Screens and Radio Frequency screens remains blank

**Expected behavior**
I expected the MCDU Screens to turn on once the plane had power as it did before updating MSFS2020

**Actual behavior**
What actually happened was that the MCDU screens remain blank, the PFD, ND and ECAM screens turn on.

**References**
https://ibb.co/7yt97Hp

**Additional context**
There is no other context to add.

Was this working before/when did the issue start occurring?
The issue started occurring after updating MSFS2020 2 days ago.

Is this a problem in the vanilla unmodded game?
No. As soon as I have the a32nx uninstalled and load up the game with the stock A320 and turn on the Ext. Pwr. The MCDU's light up instantly.

Discord username (if different from GitHub): wokkelp#7194

**Comment by Nikla-debug** [comment]
I've got the same bug. I already installed diffrent versions of the A32NX, but nothing changed!

**Comment by trami17** [comment]
I've got the same bug with the new MSFS2020 version

**Comment by Eishockey44** [comment]
Das kann nur an dem Update von MSFS liegen. Die FlyByWire Version ist wahrscheinlich nicht kompatibel mit der jetzigen Version von MSFS. Es wird wahrscheinlich demnächst ein neues Update von FlyByWire kommen.

**Comment by fsouzamoraes** [comment]
same problem here :/ with this mod the a320 is the best aircraft of the bug simulator. good job guys. can't wait for the compatible release. also when i turn on the adirs the countdown do not display anymore...

**Comment by lukecologne** [comment]
Fixed in latest master, look through previous issues before reporting.
