### ISSUE TITLE
mcdu screen blank with no data  and artificial horizon always on standby and apu not starting 

### ISSUE THREAD

**Issue by ScarKnight** [flybywiresim/a32nx#1662]
**Mod Version**

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Nikla-debug** [comment]
I've got the same bug. I already installed diffrent versions of the A32NX, but nothing changed!

**Comment by ErikNL80** [comment]
Either fill in the report properly, or don't report the issue at all...

**Comment by ScarKnight** [comment]
srry new to github
