### ISSUE TITLE
[BUG] Collection of issues after MS patch #5 V 1.10.7.0

### ISSUE THREAD

**Issue by lve0200** [flybywiresim/a32nx#1665]
Havn't found anything rather than scattered report, concerning the issues after patch #5  MS 1.10.7.0.
 Upon comment on #1662, I started this.

**Mod Version**

Latest Master DEV version w/ commits as of Oct. 30

**Describe the bug**

1. MCDU screen blank with no data; No reaction on Brightness
2. PFD artificial horizon always on standby 
3. APU not starting
4. Engines running on RWY line up, but upper ECAM shows Engines OFF; Console Engines switches ON

**To Reproduce**

1. Start flight from Runway
2. Check Cockpit b4 TO
3.

**Expected behavior**

Should work at least as good as b4

**Actual behavior**

n/a

**References**

**Additional context**

Was this working before/when did the issue start occurring? YES

Is this a problem in the vanilla unmodded game? NO

Discord username (if different from GitHub):
Related: #1661, #1662, #1654, #1657 :), 

![6aaMlAXVnZ](https://user-images.githubusercontent.com/47894777/97779857-3347b280-1b81-11eb-8bb6-8bc6642958a9.jpg)

**Comment by lukecologne** [comment]
You need to look through the closed issues as well. Everything you list is already fixed
