### ISSUE TITLE
Thank You to the Flybywiresim team for the excellent job they're doing.  I refuse to fly the base A320 and will patiently await your 1.4.1 update.  You guys deserve many beers.   Thank you again!

### ISSUE THREAD

**Issue by Warthog355** [flybywiresim/a32nx#1667]

**Comment by fsouzamoraes** [comment]
totally agree, many beers to all devs involved in this amazing job.

**Comment by NathanInnes** [comment]
I say this for myself and all others. Thanks for the appreciation on the project!

Im going to close this as it's not what GitHub issues are supposed to be used for :P but thanks again
