### ISSUE TITLE
No mcdu, apu or radio[BUG] INSERT TITLE HERE

### ISSUE THREAD

**Issue by billygoat515** [flybywiresim/a32nx#1671]
**Mod Version**
 4.0
yes

**Describe the bug**

After battery and ground unit is started. No lights on the MCDO or radio. The APU will not start as well. Tried starting from the runway but no change.

**To Reproduce**

1. After installing 4.0
2. I reinstalled the previous version and got the same issue
3. I removed addons (ex. liveries) no change

**Expected behavior**

Fix the bug

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring? It was working great until 4.0

Is this a problem in the vanilla unmodded game? I do not know

Discord username (if different from GitHub):

**Comment by lukecologne** [comment]
This is already fixed, and if you would have actually searched the previous issues, you would have known that.

**Comment by billygoat515** [comment]
Thank you so much. I hope you have a great day.

**Comment by billygoat515** [comment]
lukecologne I noticed you keep telling others it is fixed but you offer no help in finding it.... great job sir I hope you are not part of the customer service team.

**Comment by lukecologne** [comment]
This is not the place for customer service, you can find the announcements on the discord server.

**Comment by lukecologne** [comment]
Also, I stated multiple times that it is fixed on the latest master.

**Comment by Benjozork** [comment]
> customer service team.

You are not a customer. This mod is provided entirely free by people who do not make a single cent from it. A few minutes of searching resolved issues would have indicated the solution to your problem.

**Comment by billygoat515** [comment]
All I am saying is instead on commenting on everyone’s post he could’ve pointed in the right direction. I appreciate all the work they have done. I apologize for offending or seeming unappreciative. 


Sent from Yahoo Mail for iPhone


On Saturday, October 31, 2020, 2:40 PM, Benjamin Dupont <notifications@github.com> wrote:





customer service team.


You are not a customer. This mod is provided entirely free by people who do not make a single cent from it. A few minutes of searching resolved issues would have indicated the solution to your problem.

**Comment by Benjozork** [comment]
I guess it comes down to what this issue board is for. Maybe this isn't very clear to non-developers, but GitHub issues are not support tickets. It's important that you go to our discord first to avoid creating bug reports for things that have already been asked.

I'll try to state this clearly somewhere.

**Comment by billygoat515** [comment]
Again my apologies, I’m sorry for all the problems


Sent from Yahoo Mail for iPhone


On Saturday, October 31, 2020, 3:14 PM, Benjamin Dupont <notifications@github.com> wrote:




I guess it comes down to what this issue board is for. Maybe this isn't very clear to non-developers, but GitHub issues are not support tickets. It's important that you go to our discord first to avoid creating bug reports for things that have already been asked.

I'll try to state this clearly somewhere.
