### ISSUE TITLE
[BUG] IRS not aligning/FMGS stays dark

### ISSUE THREAD

**Issue by Monkeyclock** [flybywiresim/a32nx#1674]
**Mod Version**

Master.
built: 2020-10-15T01:38:50+00:00
ref: refs/heads/master
sha: a72a977f0b5c74eab9396bab64cb16f6cc4c8120
actor: Benjozork
event_name: push

**Describe the bug**

When at the gate cold and dark, once I turn on external power all the screens light up with the power on self test and go to their correct screens for IRS not in alignment, however the FMGS stays dark and when I turn the dials to align the IRS i do not get the message saying IRS in alignment.

**To Reproduce**

1. Start at gate cold and dark
2. Turned on both batterys
3. Turn on external power
4. Wait for POST to complete
5. Turn dials to align IRS

**Expected behavior**

After external power was turned on I expected the FMGS to power on
After turning IRS dials to NAV i expected the IRS in alginment message to appear on ECAM

**Actual behavior**

FMGS stays dark (Tried changing brightness to no avail.
Turning IRS dials does not bring up IRS in alignment message on ECAM

**References**

I have a video but it's too big to attach. Can send over discord if required.

**Additional context**

Was this working before/when did the issue start occurring?
I had to reinstall the game recently so downloaded the latest version of this mod in case of an update to the game (I believe it was updated recently) and after installing the mod I experienced this issue. I removed the mod folder completely from the community folder and reinstalled using the installer but still no luck,
Is this a problem in the vanilla unmodded game?
If by this you mean without this mod installed, nope tested it without this mod and it works fine (except for IRS but that is not built into game). FMGS turns on.

Discord username (if different from GitHub):

Monkeyclock1234#2340

**Comment by Benjozork** [comment]
Hello,

you are using a very outdated development version. please try with the newest development build before reporting an issue.
