### ISSUE TITLE
[BUG] MCDU BLACK AND GREY AND PERMANENT NAV TCAS FAULT ON DISPLAY

### ISSUE THREAD

**Issue by lorenlan** [flybywiresim/a32nx#1675]
**Mod Version**
TRIED EVERY VERSION FROM 4 TO THE LATEST MASTER BUILD

**Describe the bug**
AT COLD AND DARK STATE EVERY ISTRUMENTS ARE OK BUT MCDU AND RADIO HAS BLACK SCREEN.. ALSO HAVE NAV TCAS FAULT ON ECAM.. I CANT DO NOTHING.. BEFORE LATEST MFS UPDATE ALL WORKED GOOD

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by lukecologne** [comment]
This has been fixed in the latest master, please searhc for duplicates before opening a new issue.
