### ISSUE TITLE
Missing MCDU when started midair

### ISSUE THREAD

**Issue by Hansen82** [flybywiresim/a32nx#1677]
When the a320 is started midair (as opposed to C&D on the ground or hot and running on the runway), the MCDU is blank.  This does provide minor issues when f. ex. wanting to rehearse landing. This was not an issue prior to FS patch 1.10.8.0.

**Comment by Benjozork** [comment]
You removed the template. Also, look for issues before opening new ones - your problem has been reported more than 20 times.
