### ISSUE TITLE
[BUG] Wrong appearance of N2

### ISSUE THREAD

**Issue by tareksabet** [flybywiresim/a32nx#1681]
**Mod Version**

latest master

**Describe the bug**

a zero appeared after the XX while engine are off 

**To Reproduce**

1. start the plane on C & D state 
2.
3.

**Expected behavior**

the zero shouldn't be there 

**Actual behavior**

the zero is there 

**References**

![Desktop Screenshot 2020 11 01 - 02 52 10 100](https://user-images.githubusercontent.com/70240330/97792936-90794d80-1bed-11eb-9891-eee1def90f89.png)

**Additional context**

Was this working before/when did the issue start occurring?
the zero wasn't there before 
Is this a problem in the vanilla unmodded game?
yes

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Please provide a reference to the IRL plane.

**Comment by tareksabet** [comment]
> Please provide a reference to the IRL plane.

![image](https://user-images.githubusercontent.com/70240330/97797624-2a112100-1c27-11eb-9ce0-887d055095e8.jpeg)

@Benjozork here you go also they're all in amber

**Comment by MisterChocker** [comment]
This feature actually is in the master already, we added proper FADEC power logic a while ago. Curious what broke it.

**Comment by RichardPilbery** [comment]
@MisterChocker That might be my fault as I had to separate the decimal from the whole number value. Should be fixed by #1650

**Comment by MisterChocker** [comment]
@RichardPilbery Okay can you then please test this / let people test if this works correctly then?

**Comment by RichardPilbery** [comment]
@MisterChocker The fix is included and it is ready to test.

**Comment by MisterChocker** [comment]
@RichardPilbery I will test and post the results in your pr. Please link this issue so it gets automatically solved.
