### ISSUE TITLE
[REQUEST] Simbrief Integration

### ISSUE THREAD

**Issue by JacobKreindler** [flybywiresim/a32nx#1684]
**Is your feature request related to a problem? Please describe.**
 No

**Describe the feature you'd like to see implemented**

Being able to import a generated Simbrief flight plan directly from the MCDU

**References**

https://github.com/Working-Title-MSFS-Mods/fspackages/tree/main/docs/workingtitle-cj4

**Additional context**

See link above for how this was implemented for the CJ4

Discord username (if different from GitHub):
JacobK#9511

**Comment by wpine215** [comment]
Definitely plan to implement this! Waiting for final iteration of airways support and the in-progress ATSU PR to be merged in, and then we'll get on it

**Comment by Lessar277** [comment]
I would go further than the CJ4 implementation. I think it's possible to read files from disk (I saw some mention of that on Discord at some point), so theoretically, when one enters the departure/destination ICAOs, we could look in the default folder where MSFS saves flightplans and see if there is any pln file matching the two ICAOs. If there is, we could display that as a company route on the MCDU page that shows up after entering departure/destination ICAO.

@wpine215 what is there left to do on airways?
