### ISSUE TITLE
[BUG] IRS "ALIGN" light not on during Alignment 

### ISSUE THREAD

**Issue by Lamao2244** [flybywiresim/a32nx#1685]
**Mod Version**

built: 2020-11-01T01:01:54+00:00
ref: refs/heads/master
sha: af858b4cd6c37cf087a04545ff1aa6c2b931f3b7
actor: Benjozork
event_name: push

**Describe the bug**
 When IRS switch is turn to "NAV" mode for alignment, "ALIGN" light will not illuminate. 

**To Reproduce**

1.Spawn in Cold and Dark
2.Turn on GPU
3.Align IRS and monitor the light

**Expected behavior**
 IRS "ALIGN" light should illuminate when it is aligning when switched to NAV mode. 

**Actual behavior**
When IRS switch is turn to "NAV" mode for alignment, "ALIGN" light will not illuminate. 

**References**

![1 (2)](https://user-images.githubusercontent.com/72637344/97793970-64ca8780-1c2e-11eb-9238-3bad02d77879.png)

**Additional context**
Nil

Was this working before/when did the issue start occurring? Latest Master

Is this a problem in the vanilla unmodded game? Not sure

 LaMao
Discord username (if different from GitHub):

**Comment by lukecologne** [comment]
There is no align light in newer ADIRS units: https://user-images.githubusercontent.com/39596827/97513219-f5ce0400-198b-11eb-8cc2-5c8292a81434.png

**Comment by lukecologne** [comment]
See here for an old unit.
![grafik](https://user-images.githubusercontent.com/39596827/97794103-9410d280-1bf5-11eb-8d3d-929dd9cdb032.png)

**Comment by Lamao2244** [comment]
Oohh okok :)
