### ISSUE TITLE
[BUG] Trust problem

### ISSUE THREAD

**Issue by lalloretpilou** [flybywiresim/a32nx#1686]
**Mod Version**
Last Dev version

**Describe the bug**
There is a thrust problem. I put a video so that you can see the problem. I do not use a joystick in it is not a problem of calibration or sensitivity. The thrust gets carried away when I gradually increase the throttle.

**To Reproduce**
1. gradually increase the throttle.

**Expected behavior**
In reality, the engine power should not exceed the EGT blue bar.

**Actual behavior**

**References**
https://youtu.be/jV73uPh4RxQ
<img width="1005" alt="Capture d’écran 2020-11-01 à 09 10 58" src="https://user-images.githubusercontent.com/42711915/97797999-3fd01780-1c22-11eb-95ed-07290fc43253.png">

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by fsouzamoraes** [comment]
i noticed the same behavior on the egt donuts. i've been using this mod for a week everyday and only saw this after the bugsobo release the latest patch.

**Comment by MisterChocker** [comment]
already known https://github.com/flybywiresim/a32nx/issues/1596

**Comment by Benjozork** [comment]
Closing as duplicate.
