### ISSUE TITLE
Airplane rolling out of the runway at Vr speed.

### ISSUE THREAD

**Issue by fsouzamoraes** [flybywiresim/a32nx#1687]
A32NX-master.zip donwloaded at 4am Zulu

Today I will try to cut a clip, but as soon as the airplane reach about 160kt he rolls violently to the grass, always to the right. It is not my pedals neither my hotas. I tested with wind and without wind, also wind coming from the right to see if the plane keep aligned. I just saw the .1 release and will test again. 

I do search on the closed bugs and open ones and did not find nothing in this regard. If there is another report regarding this issue I apologize.

Keep the good work guys! I literally keep my second pc without the asobo patch just to keep flying with this mod.

Align on the runway and go for it! When it reaches 155kt he will go for the grass. Since the speed was high I did manage to takeoff in all tests.

1. Flying on OnAir Company
2. Testing after I noticed the behavior.
3.

**Expected behavior**

Well, expected behavior is an aligned and leaving the ground airplane!

**Actual behavior**

He do leave the ground but with some grass on the rubber and the pilot with some soil on the cockpit. Specially when the plane is destroied and you have to pay a lot for the fixes.

**References**

I will try to link a video here later today. 

**Additional context**

Was this working before/when did the issue start occurring?
After the latest official release.
Is this a problem in the vanilla unmodded game?
It's my fault, but I didn't test vanilla.
 
Discord username (if different from GitHub): I hate discord. Sorry. I am a TeamSpeak guy.

**Comment by MrGilgamesh89** [comment]
I confirm that since the last patch, aircraft is extremely hard to handle during take-off. Staying on the line is basically impossible, around 40-50kts aircraft drifts towards right edge of the runway. Correction requires full range twist in separate direction. Loss of control increases proportionally to the speed. Around V1 it is impossible to keep the aircraft on the runway. 

Also, take-off speeds appear to be too high by ~20KTS.

**Comment by hotshotp** [comment]
could not reproduce, are you sure you have the sensitivity curves right? they were changed in the update recently

**Comment by lousybyte** [comment]
I had this issue for a while a few weeks back then it somehow fixed itself. Maybe it has the same underlying cause as when the plane wants to roll to the left on landing sometimes?

**Comment by smukherj1** [comment]
For repro, you'll want to takeoff with a crosswind >= 10kts. However, I'm noticing this "issue" with the default B747 as well so this might be related to something in update 5 in the sim. I'm not a pilot so I don't know if the new behavior is more realistic. According to the Youtube video [here](https://www.youtube.com/watch?v=Tnbzhdmm0K4), crosswind takeoffs are supposed to be difficult and require several concurrent control inputs :)

**Comment by MisterChocker** [comment]
please recheck with current master

**Comment by MisterChocker** [comment]
Closing since no response from op.
