### ISSUE TITLE
FMA AP colour should be white not green

### ISSUE THREAD

**Issue by toffee2000** [flybywiresim/a32nx#169]
Rightmost column of FMA should be all white text. 1FD2, ATHR etc. AP should also be in white there.

**Comment by Curtis-VL** [comment]
This is now fixed in my fork, I'll submit a pull request later with the changes!

**Comment by Curtis-VL** [comment]
#202 Fixes are implemented in this pull request.

**Comment by Curtis-VL** [comment]
Fixed.
