### ISSUE TITLE
[BUG] NO WAYPOINTS ON SELECTED AIRWAY

### ISSUE THREAD

**Issue by timox275** [flybywiresim/a32nx#1691]
**Mod version*** 
0.4.1. Stable

**Describe the bug**
Waypoints don’t appear on selected airways 

**To Reproduce**
1.just fix this problem asap pls
2.
3.

**Expected behavior**
When I select airway to selected waypoints there must be waypoints in airway

**Actual behavior**
Airway to waypoint is entered without contained waypoints 

**References**
![image](https://user-images.githubusercontent.com/73781413/97802828-2ac1ab80-1c57-11eb-9b0d-3b0bdac8cc77.jpg)
For example , between BUKUT and LOGAN on airway P7 must be around 5 waypoints 

**Additional context**

Was this working before/when did the issue start occurring?
It was working on 0.4.0 dev version after msfs latest update
Is this a problem in the vanilla unmodded game?
I have no mods except fbw a320

Discord username (if different from GitHub):
Timox275

**Comment by lars-reimann** [comment]
> 0.4.0 dev version

Do you mean you had the development version installed previously and are now using the stable version? 0.4.1 is actually much older than the current dev version. It just contains some changes that are necessary to make the stable release 0.4.0 work with the latest version of MSFS. The airways changes made in #1460 and other pull requests are not integrated and are targeted for the next stable release 0.5.0.

Using the latest development version I could enter a flight plan using the airways page just fine and it automatically added intermediate waypoints.

**Comment by Benjozork** [comment]
> 1. just fix this problem asap pls

Please provide proper reproduction steps. I'd like to inform you that we are all unpaid volunteers putting our time into this and you have no reason to tell us fix stuff ASAP instead of providing the information we need.

**Comment by tareksabet** [comment]
To have the feature of the new Airways you need to download the latest master version via the installer. Also it's not in the stable version 0.4.1. Thanks for reporting
