### ISSUE TITLE
[BUG] Throttle detents 

### ISSUE THREAD

**Issue by andreas9700** [flybywiresim/a32nx#1692]
**Mod Version**

**Describe the bug**
The throttle detents (clb/flex/toga) does not match up with the thrustmaster tca quadrant.

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub): Andreas9700

**Comment by Benjozork** [comment]
Does not follow issue template.
