### ISSUE TITLE
[BUG] PFD emits light even if screen is black

### ISSUE THREAD

**Issue by lars-reimann** [flybywiresim/a32nx#1694]
**Mod Version**

built: 2020-11-01T01:01:54+00:00
ref: refs/heads/master
sha: af858b4cd6c37cf087a04545ff1aa6c2b931f3b7
actor: Benjozork
event_name: push

**Describe the bug**

Even when the PFD screen is black it reflects light onto the pillar to its left on the captain's side or its right on the first officer's side.

**To Reproduce**

1. Spawn cold and dark.
2. Set time to night.
3. Turn PFD brightness knob.

**Expected behavior**

Screen should stay black and it should not emit light.

**Actual behavior**

Screen stays black but emits light.

**References**

Video: https://www.youtube.com/watch?v=QCPER0_7xLo

**Additional context**

Was this working before/when did the issue start occurring?
I never paid attention to this before. 

Is this a problem in the vanilla unmodded game?
Not sure.

Discord username (if different from GitHub): Ignavia#1987

**Comment by lars-reimann** [comment]
This is probably an issue with the other screens as well, I can't test it right now, though.

**Comment by lukecologne** [comment]
Duplicate #1300
