### ISSUE TITLE
[Bug] MCDU and PFD is not working after latest MSFS update

### ISSUE THREAD

**Issue by turang** [flybywiresim/a32nx#1699]
**Mod version**
0.4.1. Stable

**Describe the bug**
I have installed fifth update of MSFS; but MCDU and PFD of A320 is not working right now. Only clr button works and types "CLR" to the screen.

**To Reproduce**
1. Born at runway or gate
2. Make sure aircraft has power.
3. Check PFD and MCDU Screens, they are not working as expected.

**Expected behavior**
Both screens should have display.

**Actual behavior**
There is no display on MCDU and PFD screens.

**References**
![Microsoft Flight Simulator Screenshot 2020 11 01 - 21 21 18 05](https://user-images.githubusercontent.com/1180435/97811016-ddf6c880-1c88-11eb-85c4-fc15082b9b12.png)

**Comment by Benjozork** [comment]
Please show the contents of the `build-info.txt` file present in the A32NX folder of the Community folder.

**Comment by turang** [comment]
Sorry @Benjozork my bad. It's already fixed. Sorry for disturbing.
