### ISSUE TITLE
[BUG] MCDU From/To same airport F-PLN issue

### ISSUE THREAD

**Issue by NiklasScheid** [flybywiresim/a32nx#1703]
**Mod Version**

0.4.1

**Describe the bug**

Insert the same airport in the From/To field on the MCDU init page. Now on the flightplan page there is the 'from airport' printed multiple times.

**To Reproduce**

1. Enter the same airport in From/To (ex. EDDR/EDDR) on the init page
2. Switch to F-PLN

**Expected behavior**

'From airport' and 'To airport' should be printed correctly.

**Actual behavior**

'From airport' gets printed multiple times

**References**

![a32x_mcdu_Bug0](https://user-images.githubusercontent.com/45736442/97813571-51003f00-1c89-11eb-8787-74888a129800.png)
![a32x_mcdu_Bug1](https://user-images.githubusercontent.com/45736442/97813573-53fb2f80-1c89-11eb-9be2-d63d11cac343.png)

**Additional context**

Was this working before/when did the issue start occurring?
Yes, < 0.4.1

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub): Niklas#6994

**Comment by MisterChocker** [comment]
this is fixed in current master

**Comment by lousybyte** [comment]
> I believe this is fixed in current master

That's correct, you can use the installer to get the latest development version if you prefer.
