### ISSUE TITLE
GS disappears on approach when AP off

### ISSUE THREAD

**Issue by SLUF4** [flybywiresim/a32nx#1705]
**Mod Version**
built: 2020-11-01T01:01:54+00:00
ref: refs/heads/master
sha: af858b4cd6c37cf087a04545ff1aa6c2b931f3b7
actor: Benjozork
event_name: push

**Describe the bug**
On an ILS with APPR engaged and AP on i have LOC and GS modes active.  When I disconnect the AP to land, aircraft goes into CLB and THR CLB on FMA.  This should still be GS/Speed as the active mode.  The thrust did not change, but it seemed to be only an indication on the FMA.

**To Reproduce**
Fly an ILS approach and engage APPR.  Disconnect autopilot and look at the FMA.

**Expected behavior**
When AP off, should stay SPEED/GS/LOC on FMA

**Actual behavior**
When I diconnected the AP, THR CLB and CLB show on FMA

**References**
A-320 pilot 

Was this working before/when did the issue start occurring?
unsure

Is this a problem in the vanilla unmodded game?
unsure
<

**Comment by MisterChocker** [comment]
Here is an images, have experienced that as well, but also with AP engaged.
Also armed G/S sometimes disappears...
![image](https://cdn.discordapp.com/attachments/747572666780745828/772081469945544714/unknown.png)

**Comment by SLUF4** [comment]
Thanks!
