### ISSUE TITLE
[BUG] Strange electrical-style noise starting upon loading in and does not stop

### ISSUE THREAD

**Issue by UNSCJohn-117** [flybywiresim/a32nx#1706]
**Mod Version:**
Master

**Description:**
When loading into the flight, there is a load and obnoxious humming coming from the aircraft
While engines are running, it is slightly audible when entering external cam or drone cam; it is not audible from the cockpit or the two interior showcams.

**To Reproduce**
1. Load a flight from either a gate or RWY (I started from LFPG)
2. 
3.

**Expected behavior**
The noise should not be there, or it should be inaudible upon APU or ENG start

**Actual behavior**
Noise continues throughout the flight

**References**

https://youtu.be/yZlKf0MmZZs

**Additional context**

Was this working before/when did the issue start occurring?
This did not occur until I updated the master ~1PM CST

Is this a problem in the vanilla unmodded game?
Unknown

Discord username (if different from GitHub): John-117#1457

**Comment by hotshotp** [comment]
that is the mech horn button to the left of all the cabin buttons. press that once and it should stop. the sound is usually supposed to play when you hold the button but this is the first time anyone has had that bug, its the button that says MECH. just press it once and it should stop

**Comment by UNSCJohn-117** [comment]
Whaddya know, that's what it was. Thanks!
