### ISSUE TITLE
[REQUEST] possibility to assign an analog axis to speed brakes

### ISSUE THREAD

**Issue by JLD95** [flybywiresim/a32nx#1711]
**Is your feature request related to a problem? Please describe.**

At now it is not possible to assign to control speed brakes (or spoilers) with a axis joystick.
Only toogle speed brakes works with a jotick button

**Describe the feature you'd like to see implemented**

Adjust the position of speed brakes lever with joystick. 

**References**

**Additional context**

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
That cannot be controlled by the mod without a hacky solution so you'll have to bring this to the MSFS forums.
