### ISSUE TITLE
[BUG] FCU knobs can only be increase/decrease by 10 with mouse-wheel

### ISSUE THREAD

**Issue by itscongq** [flybywiresim/a32nx#1712]
**Mod Version**

Latest development version

**Describe the bug**

When try to use the knobs on the FCU (altitude, speed, hdg) by scrolling the mousewheel, it only increase/decrease by 10 instead of 1.

**To Reproduce**

1. Load in
2. Load FPLN
3. try to change the numbers on FCU by scrolling mouse-wheel on knobs.

**Expected behavior**

increment of 1 and 10 if you move it really fast like before.

**Actual behavior**

Only changes in increment of 10.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Before 1.7.10 update was working fine.

Is this a problem in the vanilla unmodded game?
No.

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Please fill out the missing last two sections thanks !

**Comment by itscongq** [comment]
This bug only exists in normal flight operation with a valid FPLN activated, can't be reproduce in something like landing challenge

**Comment by ErikNL80** [comment]
I have the same issue with the latest master... Start occuring when in the air. I also have the TCA Officer Pack since yesterday. Maybe related somehow?

**Comment by FoxTrotAlpha691** [comment]
I have also experienced this issue where the Speed and Heading can only be adjusted in increments of 10. Its not as big a deal with speed but it is a killer if you need to use DCT and cannot set the correct heading for the waypoint.

**Comment by MisterChocker** [comment]
This bug is still present in latest master.

**Comment by 2hwk** [comment]
Strange, I am not getting this issue, I am able to scroll by both 1 and 10.

**Comment by MisterChocker** [comment]
There seems to be a hardware related bug.

**Comment by Saschl** [comment]
Maybe related to #2482?

**Comment by MisterChocker** [comment]
No, this exists like ever.

**Comment by beheh** [comment]
This is [scheduled to be fixed](https://forums.flightsimulator.com/t/heading-increment-bug-10-degree-instead-of-1-explained/290173/187) in Sim Update 3, expected to release on February 26th.

**Comment by MisterChocker** [comment]
This should be fixed now, waiting for confirmation.

**Comment by tracernz** [comment]
Fixed for me a while ago, I think SU3.

**Comment by MisterChocker** [comment]
Closing now, if issue persists, will reopen.
