### ISSUE TITLE
[REQUEST] Runway displayed on ND

### ISSUE THREAD

**Issue by luke-stec** [flybywiresim/a32nx#1713]
**Is your feature request related to a problem? Please describe.**
No

**Describe the feature you'd like to see implemented**
Is it possible to add a selected T/O / APPR runway to be displayed on the ND? Reference provided. Would like to see that implemented as an ND enhancement down the road!!

**References**

![InkedND_CSTR_LI](https://user-images.githubusercontent.com/73041981/97841240-a563e880-1ca2-11eb-950b-da4c1fc09d0c.jpg)

**Comment by lukecologne** [comment]
This is not really a reference, as it is from another sim. See here for proper reference: 
![grafik](https://user-images.githubusercontent.com/39596827/97858643-bee74d80-1cff-11eb-8d82-cc83fc171baa.png)

**Comment by luke-stec** [comment]
> This is not really a reference, as it is from another sim. See here for proper reference:
> 
> * How it looks: https://youtu.be/TEi-WX08ov8?t=80
> * FCOM
>   ![grafik](https://user-images.githubusercontent.com/39596827/97858643-bee74d80-1cff-11eb-8d82-cc83fc171baa.png)

My apologies! Will remember that for next time!

**Comment by ntlgr** [comment]
> This is not really a reference, as it is from another sim. See here for proper reference:
> 
> * How it looks: https://youtu.be/TEi-WX08ov8?t=80
> * FCOM
>   ![grafik](https://user-images.githubusercontent.com/39596827/97858643-bee74d80-1cff-11eb-8d82-cc83fc171baa.png)

Isn't it funny the FCOM is referencing an inexistent runway?! LSGG doesn't have 33R :D

**Comment by sidnov** [comment]
This has been implemented in the recent ND rewrite
