### ISSUE TITLE
drag reduction of the flight model

### ISSUE THREAD

**Issue by p96c42** [flybywiresim/a32nx#1716]
First of all let me thank the developers - great job. I would like to help to improve the flight model making the following experiences: 
for my opinion the drag of the flightmodel is to much reduced since the last update. I'm using simbrief for the flightplanning and in the past the simbrief given fuel was ok for flights between 1000 till 2500 Nm. Actual the fuel consumption is to low: for example only 3 000 kg for 2 hours incl climb to cruise level. Normaly we have 3000 kg for one hour on cruise level (50 kg per minute) now 25 kg per minute shown on the fuel display screen. 
This pointed out to an drag reduction of 50 % and this should be proofed for other bugs reported like swaying on cruize level, start to roll on idle thrust, nearly no decrease of speed  on idle thrust during landing and therefore nearly impossible to touch down on flare etc.
regards
Wolfgang

**Comment by Benjozork** [comment]
Does not respect provided issue template.

I recommend heading to your Discord for those kinds of questions, as GitHub issues are more for confirmed and very specific bug reports.
