### ISSUE TITLE
[BUG] MCDU does not update ZFW/ZFWCG

### ISSUE THREAD

**Issue by Watsi01** [flybywiresim/a32nx#1720]
**Mod Version**
built: 2020-11-01T23:29:49+00:00
ref: refs/heads/master
sha: 037c98e85e1e69747e3f302aaa398111eaba8413
actor: Benjozork

All versions

**Describe the bug**
If the payload is changed at the gate (with the shortcut / menu on top), the MCDU keeps the old values, inserted with the MS flightplanner _before_ starting the flight.

**To Reproduce**

1. Plan an flight (or not) and keep the weight&balance as it is (check and remember the ZWF and CG there)
2. Start the flight at a gate
3. Power up the cockpit (ext power or APU). Don't make any input to the MCDU.
4. At gate, change the payload via the top menu button 
5. Go to the INIT B page in the MCDU and push the ZFW/ZFWCG button
6. Check ZWF and CG which is given there and compare.

**Expected behavior**
MCDU should update ZFW and CG after changed.

**Actual behavior**
see above

**Additional context**

Was this working before/when did the issue start occurring?
I think this never worked. 
Could be also a vanilla problem. I even don't know if this can be solved with the possibilities of FWB.

**Comment by donstim** [comment]
I'll second this.

**Comment by lousybyte** [comment]
Should it? Doesn't the entry require manual input irl?

**Comment by donstim** [comment]
Yes, but if you (we) are going to allow the easy double click option (which I support), shouldn't it use the correct current values.
