### ISSUE TITLE
[BUG] no Ext power available and can't push bat button

### ISSUE THREAD

**Issue by Anarkand** [flybywiresim/a32nx#1721]
**Mod Version**

built: 2020-11-01T23:29:49+00:00
ref: refs/heads/master
sha: 037c98e85e1e69747e3f302aaa398111eaba8413
actor: Benjozork
event_name: push

**Describe the bug**

can't start the plane, no Ext power available and can't push bat button

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning
