### ISSUE TITLE
Altitude offset by 300ft

### ISSUE THREAD

**Issue by Baillie521** [flybywiresim/a32nx#1722]
I am posting this from my iPhone so forgive me if the template is not followed as I cannot seem to find/get it to work on my phone.

I’ve noticed weather climbing, descending or cruising the plane will fly at about 300-400ft higher than it should, wether in managed or selected altitude. I get a weird display on the PFD saying ALT* suggesting the aeroplane knows it’s too high but cannot do anything about it?

I have posted images below to illustrate this.

I would expect the plane to fly as normal as it did before the update, I’m running the updated version of MSFS and v4.1 of FlyByWire. 

Thanks again for your continued support and hard work on this, really loving this project!
![5D2A067D-2717-4252-94DF-97B63F79B934](https://user-images.githubusercontent.com/71696198/97888896-983b0e00-1d23-11eb-813c-55b564287dfe.jpeg)
![84AE653B-F4E8-4B75-BDF9-F1BABD8C41F7](https://user-images.githubusercontent.com/71696198/97888911-9bce9500-1d23-11eb-9c95-4ebd5b894d8e.jpeg)

**Comment by aviationenthusiast** [comment]
I also get this randomly for a long time now.

**Comment by Benjozork** [comment]
Your autopilot seems to not be following the FD. Try increasing your joystick / yoke deadzones, as tiny inputs can cause the autopilot to deviate without disconnecting.

P.S. please ask on the discord before opening an issue, especially if you're unable to fill the template.

**Comment by Baillie521** [comment]
I don’t have a controller plugged in on this one, this is just using the keyboard and there isn’t a dead zone on that? It happened after the update, and again I do apologise for not using the template ☹️
