### ISSUE TITLE
Double labeling of waypoints ND

### ISSUE THREAD

**Issue by wpine215** [flybywiresim/a32nx#1730]
**Mod Version**

Master

**Describe the bug**

There are two sets of overlapping text (green + white) occupying the same space next to a waypoint in the navigation display

![image](https://user-images.githubusercontent.com/28059870/97950547-39968400-1d65-11eb-8906-6637f741d1ac.png)

**To Reproduce**

1. Create IFR flight plan and fly it.
2. View nearby waypoints on plan (with and without constraints enabled)
3.

**Expected behavior**

White text should not appear.

**Actual behavior**

Overlapping text

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub): Iceman#5540

**Comment by MrMinimal** [comment]
Is there a reference on how this is supposed to behave?
Will one color always be displayed over the other? Will the labels arrange themselves to not overlap or be hidden?
If you overlay magenta, green and white, which would "win"?

**Comment by Fransan** [comment]
I'm not an expert and I'll be happy to be corrected but looking at real a320 ND screenshots it seems to me that the expected behavior would be to show the white text since it's the active/next waypoint on the active route?

**Comment by PatriceCesson** [comment]
Since the dev version of the 5 may 2021, the issue is solved with green way points but remains when a way point is displayed in green and in white over the green font.

**Comment by Benjozork** [comment]
ND is being remade anyway

**Comment by PatriceCesson** [comment]
With development version deated 7 may 2021, the blurry names on the flight plan make their comeback. 
So, this is inconsistent if it is or not fixed, for some versions yes, for others no.

**Comment by PatriceCesson** [comment]
The problem still remains in the current version.
Label with green and white fonts are almost unreadable.
Some label with double green fonts are completely broken, unreadable.
Version: 
  "built": "2021-07-08T02:19:37+00:00",
  "ref": "master",
  "sha": "d5c2c296cc55e0c1624d55ef8da4dc7d49f182cf",
  "actor": "2hwk",
  "event_name": "manual"
Thanks.

**Comment by 2hwk** [comment]
Fixed by #4953 closing ☑️
