### ISSUE TITLE
[BUG] Overlapping waypoint text on navigation display with multiple waypoints and constraints enabled

### ISSUE THREAD

**Issue by wpine215** [flybywiresim/a32nx#1731]
**Mod Version**

Master

**Describe the bug**

Overlapping magenta constraint text on nearby waypoints.

![image](https://user-images.githubusercontent.com/28059870/97950656-9db94800-1d65-11eb-8f06-d8018387fc2f.png)

**To Reproduce**

1. Turn on constraints in EFIS panel
2. Fly ILS 28R approach into KFSO via the SERFR4 arrival.

**Expected behavior**

Text should not be overlapping/conflicting

**Actual behavior**

It overlaps.

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub): Iceman#5540

**Comment by MrMinimal** [comment]
Is there a reference on how this is supposed to behave?
Will one color always be displayed over the other? Will the labels arrange themselves to not overlap or be hidden?
If you overlay magenta, green and white, which would "win"?

**Comment by MisterChocker** [comment]
Overlapping happens somehow on the one as well
![image](https://user-images.githubusercontent.com/1857322/110138849-b187c000-7dd2-11eb-9e53-331c8323f452.png)

**Comment by tracernz** [comment]
Good pic 👍. Looks like the real one just draws from earliest waypoint to last in order, so later waypoints always overlay earlier ones.

**Comment by erso44** [comment]
I am investigating this issue.

**Comment by tracernz** [comment]
> I am investigating this issue.

Be aware there is an entirely new ND being written on the autopilot-custom-fpm branch.

**Comment by 2hwk** [comment]
Fixed by #4953 closing ☑️
