### ISSUE TITLE
[BUG] Some waypoints/transitions have a completely wrong altitude constraint/prediction

### ISSUE THREAD

**Issue by wpine215** [flybywiresim/a32nx#1732]
**Mod Version**

Master

**Describe the bug**

Some waypoints in the middle of the flight plan have altitude constraints/predictions completely out of line with the altitudes of the previous or next waypoints.

![image](https://user-images.githubusercontent.com/28059870/97950866-4667a780-1d66-11eb-8e5f-bfa81520af90.png)

![image](https://user-images.githubusercontent.com/28059870/97950924-6eefa180-1d66-11eb-8213-f427978dadca.png)

![image](https://user-images.githubusercontent.com/28059870/97950977-90508d80-1d66-11eb-99a2-28a58f34f46a.png)

**To Reproduce**

1. Set up IFR (high-altitude) flight plan with a SID and STAR from almost any ICAO airport
2. Notice that some waypoints in the middle of the flight plan have altitude constraints/predictions completely out of line with the altitudes of the previous or next waypoints

**Expected behavior**

Predictions/constraints should be within the range of the surrounding two waypoints, at the bare minimum

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub): Iceman#5540

**Comment by ilyeshammadi** [comment]
I'm looking into this, I need first to get more knowledge about the MCDU and its real behavior in the real-life A320!

**Comment by MisterChocker** [comment]
This is fixed in latest stable (0.5.1)
