### ISSUE TITLE
[BUG] Some altitude constraints on the navigation display show in feet instead of flight level, even above transition altitude

### ISSUE THREAD

**Issue by wpine215** [flybywiresim/a32nx#1733]
**Mod Version**

Master

**Describe the bug**

Some altitude constraints on the navigation display show in feet instead of flight level, even above transition altitude.

![image](https://user-images.githubusercontent.com/28059870/97951050-e32a4500-1d66-11eb-9c22-54611f3d8308.png)

**To Reproduce**

1. Fly high-altitude IFR flight plan with SID and STAR. Try making changes to SID/STAR or the transition waypoints, as well.

**Expected behavior**

Should display "FL200" next to waypoint.

**Actual behavior**

Displays "20000" next to waypoint

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub): Iceman#5540

**Comment by ilyeshammadi** [comment]
I'm looking into this

**Comment by ilyeshammadi** [comment]
@wpine215 FYI:
**_Was this working before/when did the issue start occurring?_**
It was not working before since we depend on `SvgConstraintElement` 
**_Is this a problem in the vanilla unmodded game?_**
It was not implemented in the unmodded game
