### ISSUE TITLE
 [BUG] FMGC sometimes bad STAR insert

### ISSUE THREAD

**Issue by Akkifriman** [flybywiresim/a32nx#1735]
**Mod Version**

0.4.1

**Describe the bug**

STAR selection do not show up on the FMS in the correct way i.e. the FMS selects completely different wayoints despite of that the STAR i selectable and the Navigraph beta data are correct

**To Reproduce**

1. Fly EHAM to EKCH example, arrive to rwy 22L via STAR MONAK1N
2. Select MONAK1N before MONAK or CDA Codan.
3.On the FMS you should read KUTAX-CH993-CH992-CH991-CH881-LAMOX for the approach but you dont! See enclosed photos
![Missing STAR EKCH](https://user-images.githubusercontent.com/70971118/97958193-0546b600-1dad-11eb-94fb-329e650e90c7.JPG)
![Skärmklipp7](https://user-images.githubusercontent.com/70971118/97958208-0d065a80-1dad-11eb-99f5-c86cbfb90cf6.JPG)
![Skärmklipp6](https://user-images.githubusercontent.com/70971118/97958225-1394d200-1dad-11eb-9d01-ca34205e9597.JPG)

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by MisterChocker** [comment]
Please recheck with latest master

**Comment by Akkifriman** [comment]
This issue is present since the MSFS release August 18th ( unmodded original) and in existing versions of the A320nx modd, stable 0.5.1 or development version I tested as late as December 15th.
The input of the STAR (MONA1N) in combination with a certain rwy ILS ( in this case EKCH 22L) makes the approach corrupt, the ILS input twist the arrival route to the wrong (west) side of the airport, probably because the interpretation of the sole ILS is used which is not the case if arriving via the mentioned STAR. There are other cases with this corrupt situation on other airports and also examples where it is correct displayed. 
In the case above I have developed a solution by arriving with the RNAV version instead resulting in a correct displayed route.

Discord : Åke Friman

**Comment by Akkifriman** [comment]
> Please recheck with latest master

I assume you mean the latest development version - just downloaded it via the Downloader ver. 0.7?

**Comment by Akkifriman** [comment]
> Please recheck with latest master

OK, I checked with the latest master and also the latest FBW master, the latter made it even worse: 
![Skärmklipp](https://user-images.githubusercontent.com/70971118/103475028-f0d16a80-4da9-11eb-90b7-3ae1ff115f4d.JPG)

**Comment by Benjozork** [comment]
Hello, this issue is mostly resolved with the experimental flight plan system. It's currently not available but initial testing is looking promising.

I will try that specific STAR with it and show you the generated route whenever I have time so you can verify if it's correct

**Comment by Akkifriman** [comment]
The SID DEGE2W from rwy 33 in Zurich Kloten also look peculiar:
![DEGE2W-1](https://user-images.githubusercontent.com/70971118/103475209-8a4d4c00-4dab-11eb-9471-4d0a983cb4d1.JPG)
![DEGE2W-2](https://user-images.githubusercontent.com/70971118/103475210-8ae5e280-4dab-11eb-8463-20570ed78922.JPG)

**Comment by Revyn112** [comment]
I've always this problem with German Airports like (EDDB, EDDK etc.) with Navigraph Data.
Also it seems that there is a must be for VIA points.

**Comment by 2hwk** [comment]
Fixed by #4953 closing ☑️
