### ISSUE TITLE
[REQUEST] Bring back white line on throttle levers

### ISSUE THREAD

**Issue by Watsi01** [flybywiresim/a32nx#1736]
**Describe the feature you'd like to see implemented**
As I think the new textures are an improvement (latest master), I would like to suggest to bring back the white line on the throttle quadrant. Because in certain weather / light conditions (especially if the sun shines on the center pedestal) it's nearly impossible right now to see, if the throttle is set to the correct position. And most of the thottles at home don't have snap ins.

**References**

![0727825](https://user-images.githubusercontent.com/72334392/97959523-cd8d3d80-1daf-11eb-8187-457a65345880.jpg)

Discord username (if different from GitHub):

**Comment by ntlgr** [comment]
You can still see whether the throttle is at one of the detents on the upper EICAS (top right corner).

**Comment by Watsi01** [comment]
I know, but it kinda only shows, if you are "in the area" of a thrust mode. The throttle itself (in A32NX and vanilla) has some "range" inside the "zones". Ideally you would push the throttle exactly to the marker of the mode. This you can only do by looking on it, cause you don't have a physical noticable detend on your home throttle.

**Comment by AgeRay27** [comment]
I second this request to put the white line back.

It is now near impossible to tell where the marker is under pretty much all lighting conditions - and causes valuable seconds to be spent trying to put the throttle back in CL just when things are at their busiest. It was fairly easy with the white line visible. 

It might be fine in a real A320 but not on a sim as a single pilot trying to do everything with a mouse, keyboard and hand controller !!!

**Comment by collinbrady** [comment]
No wonder I was having more trouble getting back into climb mode - definitely another +1 on this.

**Comment by Watsi01** [comment]
Closing this issue cause @Pleasure0102 made it possible (thx).

**Comment by Pleasure0102** [comment]
just an FYI it was an accident it was removed :) because the decal is not really where a decal should be
