### ISSUE TITLE
[BUG] Unable to insert flightplan

### ISSUE THREAD

**Issue by nasskers98** [flybywiresim/a32nx#1737]
**Mod Version**
0.4.1

**Describe the bug**
From cold and dark, attempting to input the departure information on the F-PLN page.
pressing the button for the departure airport does nothing.
pressing the button for the arrival airport results in a message 'NOT IN DATABASE' and TMPY Insert and erase options.
With a flight plan loaded via MSFS, the issue remains - it is also not possible to amend the flight plan.
This happens both with and without the Navigraph Beta.
The base A320Neo works correctly...
![FMC initial state](https://user-images.githubusercontent.com/73882236/97973416-50b98e00-1dc6-11eb-99a6-eb65f4cd8b06.jpg)
![FMC after pressing DEST button](https://user-images.githubusercontent.com/73882236/97973436-5a42f600-1dc6-11eb-9a20-0f47d266e75e.jpg)

**To Reproduce**
1. Set up flight from EDDM to LOWI cold and dark at Gate 40.
2. Go through standard initialisation (batteries, ext pwr, lights, start IRS alignment etc.
3. INIT Page set cost index 20 and cruise FL 120
4. INIT page 2 enter ZFW/CG 53.1/31.6 and block fuel 6.4
5. PERF T/O page enter Trans Alt
6. F-PLN page - no joy...

**Expected behavior**
Pressing the From button should open the ability to enter the departure or a waypoint

**Actual behavior**
Pressing From button does nothing (well the button moves...)
Pressing the Dest button gives a NOT IN DATABASE message and tmp fpln messages... - see pics

**References**
Pics - initial state and after pressing FROM button

**Additional context**
Issue began after downloading 0.4.1
Issue occurs with and without Navigraph beta
No liveries present
Dubai and Glenforsa addons present - but these are a considerable distance away from Germany/Austria

Discord username (don't have one...):

Many thanks!
Peter

**Comment by Benjozork** [comment]
Have you tried clearing the "GPS PRIMARY" message ?

**Comment by nasskers98** [comment]
I have now! And it solved the problem - that really never occurred to me.
Many thanks for your quick response!
