### ISSUE TITLE
[BUG] A/THR Button preselects 216 knots

### ISSUE THREAD

**Issue by AdamNZ** [flybywiresim/a32nx#1738]
**Mod Version**

built: 2020-11-02T23:19:21+00:00
ref: refs/heads/master
sha: 0402635c7e9a68807453b5741c9ffc7380af9844
actor: lukecologne
event_name: push

**Describe the bug**

Whenever the A/THR button is toggled on/off it preselects/overrides the manually dialled in value with 216 knots.

**To Reproduce**

1. Select the manual managed speed mode by clicking down on the speed knob.
2. Click on the A/THR button.
3. Set a value (manually) then click on A/THR multiple times to toggle on/off.

**Expected behavior**

The dialled in speed value should be retained.

**Actual behavior**

On the ground or in flight, the value gets overwritten by 216 when A/THR is toggled.

**References**

![A320_speed_216_bug](https://user-images.githubusercontent.com/3665089/97976950-49c76580-1e30-11eb-9d69-bcab037573b3.png)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
------------------------------------------------
Used to work fine until a few dev builds ago. Haven't tested it in the unmodded 320.

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment]
Can you please recheck with latest master or stable (0.5.1)

**Comment by AdamNZ** [comment]
Thanks! Just tried with the latest DEV:
{
  "built": "2021-01-02T20:38:01+00:00",
  "ref": "",
  "sha": "",
  "actor": "Ronson1909 <Ronson1909@users.noreply.github.com>",
  "event_name": "manual"
}

... and had the same problem ... except it now inserts "222" instead of "216". Maybe that will be a clue.

I'll try it with the latest STABLE version shortly, as you suggested.
