### ISSUE TITLE
[BUG] can not start plane, no external power available and can not push battery buttons 

### ISSUE THREAD

**Issue by Anarkand** [flybywiresim/a32nx#1739]
**Mod Version**

built: 2020-11-02T23:19:21+00:00
ref: refs/heads/master
sha: 0402635c7e9a68807453b5741c9ffc7380af9844
actor: lukecologne
event_name: push

**Describe the bug**

can not start plane, no external power available and can not push battery buttons 

**To Reproduce**

1. once you try to start the plane you can not
2. no available external power
3. can not press battery buttons

**Expected behavior**

you should be able to press battery buttons or at least start the plane with external power

**Actual behavior**

can not start plane, no external power available and can not push battery buttons 

**References**

**Additional context**

Was this working before/when did the issue start occurring?
yes it was working before, 

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by RiderKickingMarco** [comment]
Cannot reproduce. Plane works fine for me.

**Comment by Anarkand** [comment]
ill post a video in a few minutes

**Comment by Anarkand** [comment]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/50266540/97986588-38536e80-1dda-11eb-9c37-772114d6da35.gif)

**Comment by Benjozork** [comment]
Hello, please list additional mods, add-ons or liveries installed.

**Comment by play3er2** [comment]
same issue. uninstalled all my livery mods, just using default a320neo.

**Comment by Anarkand** [comment]
solved, Uwa's lighting mods conflicting with a320, just deleted and it works

**Comment by play3er2** [comment]
I#m still having this issue an di have no conflicting mods that i'm aware of
