### ISSUE TITLE
Remove or atleast give us the option to remove all the button info on the buttons 

### ISSUE THREAD

**Issue by Zyonix007** [flybywiresim/a32nx#174]
Let us remove the hints on all the buttons 
![Microsoft Flight Simulator Screenshot 2020 08 28 - 00 23 40 01](https://user-images.githubusercontent.com/60050366/91521028-c4ba5000-e8c4-11ea-9804-ec49bba5fd90.png)

**Comment by NathanInnes** [comment]
New plugin got released recently to turn off tooltips.

Ref here.
https://msfsaddons.org/freeware/tooltip-remover
