### ISSUE TITLE
Altitude call outs / AP disconnect sound incorrectly routed?

### ISSUE THREAD

**Issue by ed42t** [flybywiresim/a32nx#1743]
**Mod Version**
Master

**Describe the bug**
When using the 'communications output' setting in the game sound menu (so ATC etc goes via headphones and the rest via the main speakers) some sounds (related mostly to the GPWS) seem incorrectly routed. I'm no real airbus pilot but from pax experience I've defiantly heard the AP disconnect sound loudly even in the cabin on approach, in the sim it's routed to headphones however. 

Also I'm not sure what the correct behaviour is but as it stands altitude call outs are going to the headset however the new minimums calls are going via the cockpit sounds. This may be correct but it seems a little strange that it is split like that.

**To Reproduce**
On approach with a headset and 'communication output' set in the sound menu listen to where the sounds come from
1.
2.
3.

**Expected behavior**
See above

**Actual behavior**
See above

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by lukecologne** [comment]
Duplicate #1510, also: 

> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning
