### ISSUE TITLE
[REQUEST] MCDU - PROG: Implement BRG/DIST

### ISSUE THREAD

**Issue by krangerich** [flybywiresim/a32nx#1744]
**Is your feature request related to a problem? Please describe.**

---

**Describe the feature you'd like to see implemented**

On the MCDU/PROG page, you should be able to insert a waypoint (airport icao, airport icao+rwy, VOR, ...) into 4R. In the 4th line on the left side, under the label "BRG / DIST", the current bearing + distance to this point should be shown. The data should be updated every 2 seconds. 

**References**

http://www.a320dp.com/A320_DP/nav-flight-management/sys-14.4.11.html

**Comment by MisterChocker** [comment]
When #1772 is merged this can be done easily.

**Comment by frankkopp** [comment]
+1 - doesn't seem to be too difficult if you know how to develop mods :)

**Comment by krangerich** [comment]
Implemented via #3752
