### ISSUE TITLE
No ILS trsansfer from Radio page to PFD

### ISSUE THREAD

**Issue by Captherky** [flybywiresim/a32nx#1747]
**Mod Version**

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Captherky** [comment]
I have ILS in the radio page. I dont see ILS in PFD and no GS/LOC guidance? ITS NOT TRANSFERRING to PFD and AP!
After patch #5 and 4.1 doesnt work!!!!

**Comment by Captherky** [comment]
This is 4.1 Mod
This is latest MSFS update (fuck up)
This is my Neo 32Nx which flew ok before te latest patches, now bollocksed!

**Comment by Benjozork** [comment]
Your rude passive aggressive tone will not make me want to reopen your issue.
