### ISSUE TITLE
Knobs and switches are not animated, but the function still works

### ISSUE THREAD

**Issue by A320PHX** [flybywiresim/a32nx#1748]
Version:
Most Recent Master Downloaded About 10 minutes ago.

Bug:
Knobs and switches are unresponsive as far as the animation goes. They *are* still working though. 

Reproduction/What Happens:
Load up a flight and wait 10-20 minutes after take off and the problem occurred. After a minute, things were back to normal. The sim was not frozen as I was able to pan around the cockpit, change views and manipulate the controls as needed. There was just no animation.

Expected Action
Turn/click knob/button, and have said control react to touch.

Button/knob stays in last position but does not move. It does still work.

Was this working before/when did the issue start occurring?
Worked on the master downloaded yesterday around 8:30pm.

Is this a problem in the vanilla unmodded game?
It is not, I have never experienced that before.

**Comment by Benjozork** [comment]
This is most likely a game engine problem - tagging it as such for now.

**Comment by Benjozork** [comment]
Confirmed this is a game bug. Closing.
