### ISSUE TITLE
Remove registration number from the panel under the glare shield

### ISSUE THREAD

**Issue by A320PHX** [flybywiresim/a32nx#1749]
Is there a way to remove the plane registration number from the cockpit textures? I notice that since I have downloaded the most recent master version, it has "D-AFBW" on the panel below the glare shield. This doesn't match the registration of the planes I fly and I would like to revert back to the default of no registration number.

**Comment by Benjozork** [comment]
Please respect the issue template and direct questions to the Discord server.
