### ISSUE TITLE
[BUG] MCDU Font too large

### ISSUE THREAD

**Issue by JLD95** [flybywiresim/a32nx#1752]
**Mod Version**

Release v0.4.1

**Describe the bug**

Font too large for some approaches

**To Reproduce**

1.use for example an approach LocDme 18R for airport LGRX
2.
3.

**Expected behavior**

Reduce a little the size of text

**Actual behavior**

Visibility problem
![IMG_20201104_075525](https://user-images.githubusercontent.com/5894146/98079253-c62f6800-1e73-11eb-9f83-10ea337898fa.png)

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Pleasure0102** [comment]
there is font pr up for the mcdu, which is still being activly worked on. But it something that def. has to be kept in mind.  Thanks for reporting

**Comment by tyler58546** [comment]
Fixed by #3650
