### ISSUE TITLE
[REQUEST] MCDU - Init pages should get locked

### ISSUE THREAD

**Issue by krangerich** [flybywiresim/a32nx#1753]
**Is your feature request related to a problem? Please describe.**

Improve realism

**Describe the feature you'd like to see implemented**

Inflight, you can still change some fields from INIT A and INIT B page. The INIT pages should be locked according to the current flight phase:
- INIT A should be locked outside the PREFLIGHT (before TAKEOFF) and DONE (after 30sec on ground after landing) phase
- INIT B should be locked after engine start

Locking the INIT pages in the current state might arise a problem, because you cannot change cruise FL. Changing the cruise flight level (to a lower one) during climb phase might be important because of the following reasons: You might choose a lower FL than planned (perhaps ATC assigned a lower one). 
If you never reach the planned cruise FL, the flight phase stays in CLIMB. Additionally, FMA shows "ALT" and not "ALT CRZ". This means, you don't reach the economic "soft altitude mode" (alt is allowed to change by about -50/+50ft to avoid throttling up/down)

So, when locking the INIT pages, you should also add cruise FL to the PROG page (1L). This is the preferred way for changing FL inflight, as far as I know.

**References**

From Thales MCDU manual:
![image](https://user-images.githubusercontent.com/7890659/98102566-03a3ed80-1e94-11eb-9ee7-c28a93b94849.png)

**Additional context**

none

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment]
I am looking at this

**Comment by MisterChocker** [comment]
Hey regarding init A being locked, I can't find anything in our honeywell docs.
Pilots say you can access the init a page in flight, but they don't know if you can actually change the entries, because they never did.
