### ISSUE TITLE
[BUG] Sink Rate Alarms in loop

### ISSUE THREAD

**Issue by Funda86** [flybywiresim/a32nx#1756]
**Mod Version**
Last Dev Mod (4th Nov)

**Describe the bug**
Sink rate alarms is going on loop from the departing gate till the whole flight

**To Reproduce**
1. Start a flight
2. Turn on Batteries and External Power
3.

**Expected behavior**
No Sink rate message

**Actual behavior**
Sink rate alert is going on loop

**References**

**Additional context**

Was working fine on 30th October Dev Mod

Is this a problem in the vanilla unmodded game? NO

Discord username (if different from GitHub): David Funda

**Comment by Benjozork** [comment]
Hello, the GPWS is being completely re-done according to the actual Airbus logic. Stay tuned.

**Comment by hotshotp** [comment]
sometimes its a bug when you start the flight or sim. just restart it
