### ISSUE TITLE
Upper Ecam Always Displaying TO/GA when Idle, CL, FLX/MCT

### ISSUE THREAD

**Issue by Dentar1** [flybywiresim/a32nx#1760]
Version **4.1**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behavior**

**Additional context**
<-- My additional context is to thank all of you dedicated people spending the most valuable resource we as humans have (Time), in order to produce such a wonderful collaboration of work to create the best Airbus for FS2020! Thank You Everyone! -->

Was this working before/ I believe it was...?

Is this a problem in the vanilla unmodded game? 
Negative Newest FS Update

**Comment by Benjozork** [comment]
This issue is fixed in the development version.

**Comment by Dentar1** [comment]
Hmmm... My development version is up to date though.
Apologies for not seeing that, but some other info i wrote was also excluded.
GitHub newbie... :) :(
Thanks so much for the reply!

**Comment by Benjozork** [comment]
@Dentar1 you said version 0.4.1, that is the stable version. It's not fixed in the stable version yet, only in development version.

**Comment by bisinchi** [comment]
Hi, just tried the latest build this morning and still have TOGA when not in CLB mode. Was at MCT too and TOGA was displayed
