### ISSUE TITLE
[BUG] Cabin temperature knobs not centered 

### ISSUE THREAD

**Issue by FlightSimmer7700** [flybywiresim/a32nx#1763]
**Latest master**

built: 2020-11-04T16:48:59+00:00
ref: refs/heads/master
sha: dbcd6ac1eee5a6ba875257ee88bede129ce6f91c
actor: Benjozork
event_name: push

**Describe the bug**
The cabin knobs are not fully centred and the "detents" are a little off to both the left and right

**To Reproduce**

1.Spawn in
2.look at overhead
3.turn the cabin temperature knobs using the mouse scroll wheel

**Expected behaviour**

It would look better if it was in the middle and not a little to either side

**Actual behaviour**

It stops at either side of the middle 

**References**

![Screenshot (163)](https://user-images.githubusercontent.com/70103461/98169705-abe1a280-1ee4-11eb-9d73-87414a5acb22.png)
![Screenshot (164)](https://user-images.githubusercontent.com/70103461/98169714-ae43fc80-1ee4-11eb-918f-07494b7fbdb3.png)

**Additional context**

Was this working before/when did the issue start occurring?
I can't remember if it has always been like this or not just noticed it today

Is this a problem in the vanilla unmodded game?
Not sure but shouldn't matter

Discord username (if different from GitHub): FlightSimmer7700#3468

**Comment by AdamNZ** [comment]
This cosmetic "bug" has been annoying me [slightly] ever since they got tweaked a few builds ago. Would be nice to have them looking all neat and tidy!

**Comment by lukecologne** [comment]
So, the current template uses an increment of 4 with the mousewheel. Since the value goes from 0 to 100, the problem is obviously that you can't reach 50 within increments of 4. There are 2 ways of fixing this: either, increase the increment from 4 to 5, which would speed up the mousewheel scrolling, or, the second option, you can just use the mouse button to center it, since it has an increment of 1, it can reach the middle.

**Comment by Benjozork** [comment]
@lukecologne, the number of steps needs to be uneven in order for a center position to exist. the only way is to make it either 99 or 101 states.

**Comment by lukecologne** [comment]
well, the number of states is uneven. You have to include the 0, which makes it a total of 101 states

**Comment by ImenesFBW** [comment]
#3118 may inadvertently fix #1763 since the position is centered at the start, when the user moves it back and forth by the increment set they should be able to hit the centered position.

**Comment by rare-potato** [comment]
I'm considering fixing this "bug" while working on issue #3128 to allow finer variability in initial air conditioner knob positioning.

The main downside to fixing this is going to be decreasing the speed at which a user can change the knob position with the mouse wheel, but it allows each location of the marked notches to be centered with the knob itself from what I've been able to observe.
