### ISSUE TITLE
Screens (PDF/FMC/etc) do not turn on when power applied.

### ISSUE THREAD

**Issue by dwc4195** [flybywiresim/a32nx#1764]
**Mod Version**

Master

**Describe the bug**

After starting from dark, the screens don't show up (FMC,PDF,ECAMS,etc).

**To Reproduce**

1. start A320 with master a32nx in dark mode
2. power on via EXT PWR
3. none of the monitors/screen turn on.
4. (switches/etc show normal).

**Expected behavior**

PDF/FMC, etc screens should be turned on

**Actual behavior**

PDF/FMC, etc screens are not on

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Working right after initial 1.0.7 patches

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):
dc9116

**Comment by dwc4195** [comment]
![Screenshot 2020-11-04 154016](https://user-images.githubusercontent.com/1278542/98185164-b8a8cb00-1ed1-11eb-8a2d-740ac6a5f63f.png)
![Screenshot 2020-11-04 153952](https://user-images.githubusercontent.com/1278542/98185166-b9416180-1ed1-11eb-86e0-1b4d5f56a12b.png)

**Comment by lukecologne** [comment]
How did you download the mod?

**Comment by dwc4195** [comment]
I resolved my issue.  Please disregard.

**Comment by nolanblew** [comment]
@dwc4195 how did you resolve the issue? I am experiencing the same thing

**Comment by nolanblew** [comment]
How I installed: I downloaded `master` and built from there (I like to change the ADIRS alignment time to a much more unrealistic shorter amount as I like to get airborne as soon as I can and I'm usually held up by ADIRS aligning), then I copied the built files over to the communities folder

**Comment by wpine215** [comment]
We changed our build process to use npm rather than only the python script. We recommend you use the installer or download the pre-built master in the github releases category if you are not developing.
