### ISSUE TITLE
[BUG] Battrey, Gen, and External Power switches inop.

### ISSUE THREAD

**Issue by play3er2** [flybywiresim/a32nx#1765]
**Mod Version**
Master

**Describe the bug**
Exact same as issue #1739. The overhead switches are inoperable.

**To Reproduce**
1.  Load the a32nx on the ramp or at a gate
2. try to startup
3. realise the overhead buttons don't work

**Expected behavior**
Expected behaviour is for the cockpit buttons to be clickable and the startup sequence to continue

**Actual behavior**
Cannot click or toggle any buttons on the electrics panel. All just display fault. No way to toggle external power or batteries.

**References**
*screenshot pending - stand by*

**Additional context**

Was this working before/when did the issue start occurring?
Was working a couple weeks back. Suddenly stopped working. The only thing i have is clinks liveries v10, but i removed that and it still doesn't work. 

Is this a problem in the vanilla unmodded game?
Nyet.

Discord username (if different from GitHub): Sopphic#3256

**Comment by Benjozork** [comment]
Hello, how did you install the mod ?

**Comment by Kimbyeoungjang** [comment]
> Hello, how did you install the mod ?

i also have this problem. i already removed all mods and re-install dev version(yesterday version. i'll try that again today) but all buttons not work(it can clicked but not working)

Also, battery indicator said 0V both. when i spawn on runway, engine's works(only engine working. can move aircraft but every avionics is not working(only black screen)

i try to re-install mode today.

**Comment by Kimbyeoungjang** [comment]
check your npm version and DO NOT USE build.py
i think builder build dcdu js(can't do with build.py). you should use new js and use latest npm

**Comment by Aesculab** [comment]
I've clean installed the latest DEV-build (2020-11-05 05:53:53Z) through downloader(v.0.6.1) & after startup (cold & dark) a lot of buttons at the overhead-panel are already in a false state & partly not useable.

I did a restart at the same airport & tried different airports.

Screenshot:

![asobo_bug](https://user-images.githubusercontent.com/35341633/98275783-59ac8a00-1f95-11eb-8bdb-a8efb2931dba.png)

**Comment by Kimbyeoungjang** [comment]
> I've clean installed the latest DEV-build (2020-11-05 05:53:53Z) through downloader(v.0.6.1) & after startup (cold & dark) a lot of buttons at the overhead-panel are already in a false state & partly not useable.
> 
> I did a restart at the same airport & tried different airports.
> 
> Edit: Also no Simconnect-Programs/Apps involved
> 
> Screenshot:
> 
> ![asobo_bug](https://user-images.githubusercontent.com/35341633/98275783-59ac8a00-1f95-11eb-8bdb-a8efb2931dba.png)

How about install via github master?

You can build master to use npm

Just download npm and run npm install, npm run build on github master folder/script 
And put A32NX to your community folder
