### ISSUE TITLE
[BUG] MASTER Version is not working

### ISSUE THREAD

**Issue by Kimbyeoungjang** [flybywiresim/a32nx#1766]
**Mod Version**

current master

**Describe the bug**

as a title, is not working

**To Reproduce**

1. start on ruway
2. watch avionics and overhead panel
3. everything is not working

**Expected behavior**

**Actual behavior**

**References**

![image](https://user-images.githubusercontent.com/23118756/98222903-c7a48180-1f94-11eb-983f-25dd6a407957.png)
my community folder, only A32NX in here

![image](https://user-images.githubusercontent.com/23118756/98222995-d854f780-1f94-11eb-9d97-4d889328041f.png)
overhead panel. nothing work.

![image](https://user-images.githubusercontent.com/23118756/98223029-e440b980-1f94-11eb-8a89-6e86888ce7d7.png)
front. also not working. i try to touch bright but also not working. 

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
no

Discord username (if different from GitHub):

**Comment by Kimbyeoungjang** [comment]
spawn on gate, same as upside. not working.

**Comment by myselfaaryan** [comment]
@Kimbyeoungjang Do you build it manually?

**Comment by Kimbyeoungjang** [comment]
> @Kimbyeoungjang Do you build it manually?

yes. first i using build.py not working
second i using new js builder but also not working.

it is weird. buttons working but every display is not working...

**Comment by myselfaaryan** [comment]
You just need to run 

npm install
npm run build

build.py is now completely removed from the process.

**Comment by Kimbyeoungjang** [comment]
> You just need to run
> 
> npm install
> npm run build
> 
> build.py is now completely removed from the process.

i'll re-install npm first maybe my npm version is too old.

**Comment by Kimbyeoungjang** [comment]
now working. my npm version was problem.

**Comment by Benjozork** [comment]
In the future, please remember that GitHub issues are not for support. Head to our discord for installation assistance.
