### ISSUE TITLE
[BUG] left engine reverse thrust sound 

### ISSUE THREAD

**Issue by airfirefighter** [flybywiresim/a32nx#1767]
**Mod Version**
built: 2020-11-06T05:53:09+00:00
ref: refs/heads/master
sha: 1b700dec418e910b3e9d64038972e23baf8fdc63
actor: Benjozork
event_name: push

**Describe the bug**
The sound of the reverse thrust is not working if you apply only reverse thrust in engine 1

**To Reproduce**

1.start on the runway 
2.parking brakes ON
3.apply reverse thrust only in one engine at the time first engine n1(no reverse  sound) then engine n2 (with reverse sound)

**Expected behavior**
every engine reproduce reverse sound even if you use only one lever at reverse thrust.

**Actual behavior**
you have the sound of reverse thrust only in engine 2 . engine 1 no sound of reverse thrust when u engage only that engine in reverse position 

Was this working before/when did the issue start occurring?

i dont know

**Comment by Benjozork** [comment]
> Last Dev

Please provide the contents of the `build-info.txt` file as stated in the template.

**Comment by airfirefighter** [comment]
im sorry this is my first time use github i dont know how to provide the contents of the build-info.txt file...

**Comment by Pleasure0102** [comment]
> im sorry this is my first time use github i dont know how to provide the contents of the build-info.txt file...
The file is in your mod folder:
"Community\A32NX\build_info.txt"
open it, copy paste contents in here

**Comment by airfirefighter** [comment]
Thank you very much! its ready.

**Comment by hotshotp** [comment]
Ah okay, looks like I assigned a wrong index to the reverse thrust nozzles. Will fix soon 👍

**Comment by airfirefighter** [comment]
Thank you very much for your fantastic work!!!So i close it! right?

**Comment by hotshotp** [comment]
> Thank you very much for your fantastic work!!!So i close it! right?

Nah, don't close it until it's fixed :)
