### ISSUE TITLE
[REQUEST]Add V1/VR/V2 Disagree Error Message to MCDU

### ISSUE THREAD

**Issue by donstim** [flybywiresim/a32nx#1774]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**
<!-If the user tries to input any one of the takeoff speeds that does not meet the above condition, the MCDU should not accept the entry and should display the message, "V1/VR/V2 DISAGREE." -->

**References**

![Screenshot (258)_LI](https://user-images.githubusercontent.com/70166617/98307247-345e5280-1f7a-11eb-8550-38447b901d2a.jpg)

**Additional context**

Discord username (if different from GitHub):donbikes#4084

**Comment by donstim** [comment]
More info on the type of error message displayed. Actually, it's unclear to me as to whether or not the MCDU should accept the takeoff speeds that don't adhere to the V1<=VR<=V2 condition, but an error message should definitely be displayed.
![Screenshot (260)](https://user-images.githubusercontent.com/70166617/98307745-64f2bc00-1f7b-11eb-9729-7d37a1c968d2.png)

A similar error message should also be displayed on the lower ECAM if the error condition is present during either the Takeoff Configuration check or upon selection of takeoff power.
![Screenshot (262)](https://user-images.githubusercontent.com/70166617/98308089-1f82be80-1f7c-11eb-82b1-a7144d3260e3.png)

**Comment by paul92ilm** [comment]
Working on it

**Comment by paul92ilm** [comment]
Also Fixing V1/VR/V2 range (minimum 90)
![image](https://user-images.githubusercontent.com/9373163/98439177-54178700-20f0-11eb-82a2-a9c0f8ec12c7.png)

**Comment by paul92ilm** [comment]
Also added the T.O Config test
![image](https://user-images.githubusercontent.com/9373163/98441302-b460f580-20fd-11eb-9228-cd3cbd579a4d.png)

**Comment by donstim** [comment]
Thanks!!

**Comment by beheh** [comment]
@donstim Over at the PR we're wondering exactly what you called out, namely whether the MCDU rejects the input after showing the error message or whether it does allow temporary mismatches (e.g. 150 135 137) in the PERF page. Do you have any more insight on this or an idea how we could confirm the behaviour?

**Comment by beheh** [comment]
Good news: nograb (real pilot) from Discord found this after [a short discussion](https://discord.com/channels/738864299392630914/754851312306487326/775671983231991859) ([Source, page 3](https://safetyfirst.airbus.com/app/themes/mh_newsdesk/documents/archives/the-take-off-securing-function.pdf)):

![image](https://user-images.githubusercontent.com/929769/98668381-1a44bb80-2350-11eb-8667-0fa526e9a64a.png)

I believe that clarifies this behaviour. I'll post this in the PR.

**Comment by donstim** [comment]
@beheh So, it looks like it takes it, but then displays an error message. Ok. I couldn't find any info on whether it took it or not, which is why I brought it up. If I find anything contrary, I will let you know. Thanks for checking!

**Comment by FlyingCarpet7** [comment]
If it’s not implemented yet: what’s happening if we insert a faulty flap setting on the Take Off Perf page. I tried it out. Anything else than 1, 2 and 3 gives an INVALID ENTRY in return on the scratchpad.

**Comment by beheh** [comment]
@FlyingCarpet7 I would file a separate issue for that.

**Comment by paul92ilm** [comment]
I changed my PR to match witch @beheh reference

@FlyingCarpet7 I confirm it's better to open an other issue, this one deals with V1/VR/V2 disagree message
