### ISSUE TITLE
[REQUEST] Add automatic trim setting in PERF page

### ISSUE THREAD

**Issue by starvingjavi** [flybywiresim/a32nx#1776]
**Is your feature request related to a problem? Please describe.**
No problem. Currently there is no automatic setup for flaps and trim

**Describe the feature you'd like to see implemented**
Depending on the CG it could be possible that just by adding the flaps setting on the PROG page you could get a trim setting automatically

**References**
![1 jpg 133650cf1f6bd7d84ff45ad61dfc97d7](https://user-images.githubusercontent.com/70245523/98322638-8a002280-1fad-11eb-9222-b290b94fefca.jpg)

Discord username (if different from GitHub): Javi#2557

**Comment by ImenesFBW** [comment]
![Untitled-2](https://user-images.githubusercontent.com/71195324/98324895-ce131780-1fed-11eb-89e0-a7f498ca8c8b.png)

Sorry I had to !

**Comment by starvingjavi** [comment]
Lol, changed the typo

**Comment by ilyeshammadi** [comment]
Is this feature present in the real A320 or just a handy feature that automatically fills the trim setting?

**Comment by starvingjavi** [comment]
it's a handy feature that I've seen implemented in several payware addons from XPlane and P3D

**Comment by sidnov** [comment]
Since it is not a feature on the real FMS, it is highly unlikely that it would be added to our current MCDU. Although, it can be developed as a part of the takeoff calculator, which is referenced here https://github.com/flybywiresim/a32nx/issues/4444
