### ISSUE TITLE
[BUG] MCDU FPLN adding waypoint

### ISSUE THREAD

**Issue by giova1588** [flybywiresim/a32nx#1778]
**Mod Version**
 Dev
 2020-11-06T05:53:09+00:00

**Describe the bug**
 Lack of "to" label in FPLN page during the waypoint insertion . The added waypoint doesn't appear, and the new "via" bracket doesn't appear too. However checking the temporary FPLN the waypoint is correctly added. 
If I add the "via" airway the "to" was shown.. 

**To Reproduce**

1.  EGKK --> LOWG
EGKK/08R DCT ADMAG Y312 DVR UL9 KONAN UL607 REMBA DCT LIRSU DCT
NONKO UL607 RIDSU UZ738 RIDAR Y161 MAH L173 EBEDA UL603 LATLO DCT
OBEDI DCT ABIRI ABIRI1M LOWG/35C
2. add INIT information 
3. FPLN --> EGKK --> select departure from 08R no SID (the none botton doesn't do anything)
4. select EGKK08R --> Airways --> only "via" is visible.
5. following the flightplan the next waypoint is ADMAG, no airways. I insert ADMAG, click the first top right button to insert the waypoint in the ghost "to" and nothing shown, but on the bottom the INSERT and ERASE massage appear. Clicking on insert the waypoint was correctly insert in FPL
6. Next to DVR. If i try to insert DVR directly it was the same of above, but adding the Y312 airway magically "to" bracket appears.

**Expected behavior**
 In FPN page i expect to see the "via" and "to", and the addition of a waypoint should be shown though no "via" was added (the DCT should be appear).

**Actual behavior**
 No "to" column in FPN airways page. The addition of a waypoint produce nothing, but on the bottom the insert/erase message was shown correctly

**References**

1. Departure select
![image](https://user-images.githubusercontent.com/48919009/98355044-eac94280-2021-11eb-8f46-0029a1a59561.png)

2. Waypoint addition (the "to" was not shown). Following the flight plan I have to go to ADMAG directly
![image](https://user-images.githubusercontent.com/48919009/98355218-22d08580-2022-11eb-8d27-9733cb1b3311.png)

3. Add waypoint, push the top right botton--> nothing was shown but the insert/erase message on the bottom was shown
![image](https://user-images.githubusercontent.com/48919009/98356378-c706fc00-2023-11eb-8b21-08d76e86d32a.png)
![image](https://user-images.githubusercontent.com/48919009/98355384-57dcd800-2022-11eb-9a48-3ae9fbbf83d1.png)

4. the same if i add directy DVR
![image](https://user-images.githubusercontent.com/48919009/98355459-704cf280-2022-11eb-9289-208a42f47d5c.png)

5.if I add the "via" airway, the "to" appear and then I can add DVR correctly
![image](https://user-images.githubusercontent.com/48919009/98355540-8e1a5780-2022-11eb-86d9-23a09da0c61b.png)

**Additional context**
 only Navigraph data was installed. No other mod

Was this working before/when did the issue start occurring? Yes since the last Asobo update

Is this a problem in the vanilla unmodded game? no

Discord username (if different from GitHub): badu

**Comment by duckietm** [comment]
I have the same problem :(
![image](https://user-images.githubusercontent.com/1917443/98442124-1c660a80-2103-11eb-86e2-19a3e5d7fb6c.png)

**Comment by lousybyte** [comment]
This is intended and true to life afaik.

**Comment by lukecologne** [comment]
This is not a bug. If you want to add waypoints directly, use the NEXT WPT field in the lateral revision page: 
![grafik](https://user-images.githubusercontent.com/39596827/98448093-0e77b000-212a-11eb-9ba0-16783de56fc1.png)
