### ISSUE TITLE
[REQUEST] RW F-PLAN DISCONTINUITY 

### ISSUE THREAD

**Issue by yorgosGK** [flybywiresim/a32nx#1781]
Should look into F-PLAN disco as it would solve many bent and weird spaghetti lines on the nav display since they dont have to "connect" and in a Disco you are essentially in heading select mode awaiting vectors. 

 
![1 JPG a4b4f098fb14699560649bb697ff3886](https://user-images.githubusercontent.com/74068697/98397577-8f04b680-202d-11eb-9514-a59d75339c89.jpg)

**Comment by Benjozork** [comment]
Does not respect issue template
