### ISSUE TITLE
throttle axis 1 moves throttle 1 and 2, donuts operate correctly

### ISSUE THREAD

**Issue by ttielemans** [flybywiresim/a32nx#1787]
**Mod Version**

built: 2020-11-07T06:09:50+00:00
ref: refs/heads/master
sha: f3868159ddcc5ace85486ecafdb33558a63bc670
actor: wpine215
event_name: push

**Describe the bug**

When moving throttle axis 1, the donut of engine 1 moves in the ECAM, throttle 1 and 2 both increase.
Moving throttle axis 2, the donut of engine 2 in the ECAM moves, throttle 2 does not change

**To Reproduce**

1. Move engine axis 1, donut 1 moves, throttle 1 and 2 power up
2. Move engine axis 2, donut 2 moves, no throttle 2 change.
3.

**Expected behavior**

Move throttle 1 axis: donuts 1 moves, engine 1 throttles up (or down)
Move throttle 2 axis: donuts 2 moves, engine 2 throttles up (or down)

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Yes, seems to work in the stable version 0.4.1

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
cc. @MisterChocker

**Comment by MisterChocker** [comment]
Had the same issue while #1650 was wip. Just tested on latest master and works fine.
Axis1 controlles engine1 N1% and engine1 donut,
Axis2 controlles engine1 N2% and engine2 donut.

ATHR gets limited by engine 1 or axis1.

**Comment by ttielemans** [comment]
Confirm working now.

**Comment by ttielemans** [comment]
Issue is back in version
built: 2020-11-12T19:07:16+00:00
ref: refs/heads/master
sha: 02edbe68f8b4e90cd85a908e32653e430a34056d
actor: wpine215
event_name: push

**Comment by ttielemans** [comment]
Sorry, was not working in previous dev version. In the version above it is working as it should. Bug seems to appear and disappear.
