### ISSUE TITLE
Broken textures

### ISSUE THREAD

**Issue by TrainNutter** [flybywiresim/a32nx#1788]
![2020 11 07-14 02](https://user-images.githubusercontent.com/48223268/98443313-6bf80680-2102-11eb-9f93-2ee84ca3932a.png)
![2020 11 07-14 02_01](https://user-images.githubusercontent.com/48223268/98443315-6e5a6080-2102-11eb-83a8-332dbfd8a950.png)
![2020 11 07-14 02_02](https://user-images.githubusercontent.com/48223268/98443318-70242400-2102-11eb-9159-39cd35440d2a.png)
![2020 11 07-14 02_03](https://user-images.githubusercontent.com/48223268/98443321-71555100-2102-11eb-85ce-247eaee28942.png)
![2020 11 07-14 02_04](https://user-images.githubusercontent.com/48223268/98443324-72867e00-2102-11eb-9b3a-403232559f50.png)

Latest version of MSFS, Latest v0.4.1 of A32NX

**Comment by Benjozork** [comment]
Does not respect template

**Comment by Benjozork** [comment]
Please try without any liveries installed.
