### ISSUE TITLE
Co-pilot Communications (ACP) panel non functional

### ISSUE THREAD

**Issue by dmvanderuit** [flybywiresim/a32nx#1791]
Co-pilot's ACP (where you change frequencies) is non funcitonal. Cannot change frequencies or select standby frequency. Screens do update when I alter the frequency on the pilot's side.

**To reproduce**
1. Give power to aircraft via either batteries or external
2. Try and change frequencies on co-pilot (right) side

**Expected Behaviour**
I expect the frequencies to change when I turn the nob or press the buttons.

**Comment by Benjozork** [comment]
This is a feature request, please re-open it as such

**Comment by dmvanderuit** [comment]
> This is a feature request, please re-open it as such

It is not. This is a feature that works in the vanilla aircraft. Please re-read the issue.

**Comment by lukecologne** [comment]
No, it doesn't work in vanilla. Just checked.

**Comment by Benjozork** [comment]
That's why the template contains a "Does this work in the vanilla unmodded game" section, that you removed

**Comment by dmvanderuit** [comment]
Excuse me. It was my understanding it did work. Making a feature request now.
