### ISSUE TITLE
[REQUEST] Working ACP on co-pilot side

### ISSUE THREAD

**Issue by dmvanderuit** [flybywiresim/a32nx#1792]
**Is your feature request related to a problem? Please describe.**
This is a feature request for a new feature. 

**Describe the feature you'd like to see implemented**
Create a working ACP (communication frequencies) for the co-pilot side. (Screens currently display right information as selected on pilot side, only buttons and inputs do not work). turning knob for selecting frequencies and button to swap active and stand-by frequencies. 

**References**
Exactly the same as on the pilot side. 

**Additional context**
No additional context.

**Comment by Benjozork** [comment]
Related  #1058

**Comment by lukecologne** [comment]
Not possible without a model change, both RMPs are in the same object and have the same material.
