### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by patcat7501** [flybywiresim/a32nx#1794]
**Mod Version**
 most recent dev version 
 don't have it 

**Describe the bug**
 everything works except auto pilot . Once I turn it on it pulls to the right won't follow the plan and then tries to invert . I have to take control . Is this a known issue and if so how can I fix . Thank you . Email is pshep7501@gmail.com 

**To Reproduce**

1.auto pilot engage 
2.
3.

**Expected behavior**
 follow plan and not turn to the right and try to invert the aircraft 

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring? New to the mod 

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by tareksabet** [comment]
Make sure you have the latest stable version

**Comment by patcat7501** [comment]
I had the dev version I will change over to stable . If I run into problems
I'll let you know . Thank you for the quick responses amazing service !!

**Comment by patcat7501** [comment]
Morning ,
I did try the stable version and it happened again . Once you engage auto
pilot the aircraft banks to the right then pitches down .
Any help would be appreciated!
Thank you

**Comment by Benjozork** [comment]
Please try to increase the deadzones on your controller.

We do not modify autopilot FYI.
