### ISSUE TITLE
DCT resets MCDU, reentering data crashes game

### ISSUE THREAD

**Issue by Cspielman63** [flybywiresim/a32nx#1798]
**Mod Version**

master
built: 2020-11-07T21:16:46+00:00
ref: refs/heads/master
sha: 3dd9cf63ed0f04f8eb95041ec719447dc303f171
actor: Benjozork
event_name: push

**Describe the bug**

Entering a direct to waypoint deletes flightplan and init page info. Reentering info crashes game.

**To Reproduce**

1. Enter direct to waypoint
2. check for deletion of flightplan
3.

**Expected behavior**

**Actual behavior**

Flightplan deleted and crashes game upon reentering info

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Seth-Dark** [comment]
had the same issue exactly while  i was approaching ESGG yesterday. Adding a direct to waypoint freeze MFS and crash.

**Comment by tracernz** [comment]
Have not seen this. Don't think it's been an issue for a long time.
