### ISSUE TITLE
[REQUEST] Depiction of the minimum fields is incorrect.

### ISSUE THREAD

**Issue by Pushok154** [flybywiresim/a32nx#1799]
**Is your feature request related to a problem? Please describe.**

Current depiction of the minimum fields at perf aprr page is incorrect.

**Describe the feature you'd like to see implemented**

The Honeywell FMS2 release 1a and rlease2 has Baro/Radio fields instead of MDA/DH at perf aprr page, consequently we have BARO/RADIO instead of MDA/DH at FMA minimum Column

**References**

![image](https://user-images.githubusercontent.com/74020654/98461511-a70b4000-21bd-11eb-8661-3c6d3ece8179.png)

**Additional context**

Dear developers, in generall it seems that you make thales FMS1 (older version of FMGS), nowadays all airbus aircraft are equipped with honeywell FMS2 release1a, and all NEO aircraft equipped with FMS2 release2

![image](https://user-images.githubusercontent.com/74020654/98461650-09187500-21bf-11eb-9083-b25a80699dd0.png)

Discord username (if different from GitHub):
Антон Пушков#0240

**Comment by paul92ilm** [comment]
Some references 
![image](https://user-images.githubusercontent.com/9373163/98463965-bdb29680-21bf-11eb-8a2d-59763c7eec1d.png)

There is some conditions to display BARO/MDH/MDA or RADIO/DH

**Comment by Pushok154** [comment]
ok i see you, thx for clarification, in our company all aircraft qfe pin programmed that is why we have baro/radio)), would you add this options in aircraft options menu?

**Comment by beheh** [comment]
Is this cosmetic only on the PERF page (and the PFD presumably) or is there also a functional difference?
