### ISSUE TITLE
flight controls should be locked until APU or engines started (Hydraulics simulation)

### ISSUE THREAD

**Issue by Zyonix007** [flybywiresim/a32nx#180]

**Comment by PCGamesF1Tech** [comment]
The APU only provides bleed and electricity.
The engine driven pumps (EDPs) power the green hyd system (Eng1) and yellow system (Eng2). 
You can however switch on the yellow elec pump which powers the yellow system (only around 2500 psi, enough for cargo door operation) and the green system via the PTU.

**Comment by JackZ974** [comment]
The HYD systems are not simulated yet

**Comment by PCGamesF1Tech** [comment]
There is a maintenance switch on overhead panel to power blue hydraulic on ground (e.g. for flap maintenance)

**Comment by JackZ974** [comment]
Correct, my bad.
 The Blue HYD Elec pump should start after 1st engine start
