### ISSUE TITLE
Upper ECAM Bugs

### ISSUE THREAD

**Issue by A320PHX** [flybywiresim/a32nx#1800]
**Mod Version**
Dev. Version *Downloaded on 11/7/2020 6:00 pm.

**Describe the bug**
1. On the upper ecam, no matter the position of the throttles, it is showing TOGA. 
2. TO config is showing for the duration of the flight including when landing.
3. Engines are still showing 0.0 percent N1/N2 when engines are shut down, instead of showing orange xx.x%.

**To Reproduce**
Just load up a flight and the issues should be present right from the beginning. This happens regardless of whether or not I have started cold and dark or on the runway. The last issue, you have to have started cold and dark at the gate.

**Expected behavior**
1. Upper ecam engine screens should be stating what the position is of the throttles are. 
2. TO Config should be replaced with any inputs you have selected. For example, whether or not landing lights are on, seatbelt and no smoking sign, ground spoilers armed and so on. This issue is intermittent. 
3. Engines. when off. should be displayed in the ecam as xx.x% in an orangish/red color.

**Actual behavior**
1. Toga is shown throughout the flight.
2. TO config is displayed during all phases of flight. 
3. Engine reading show a 0.00%.

**Additional context**
 I have never had issues with your display modifications before.

Was this working before/when did the issue start occurring?
Yes. These issues seem to have started just around the last update for the A32NX dev. version.

Is this a problem in the vanilla unmodded game?
It is not. Default A320neo does not have a lot of the ecam functional at this tim.

**Comment by paul92ilm** [comment]
Hello, I don't succeed to reproduce your issue
![image](https://user-images.githubusercontent.com/9373163/98464712-03259280-21c5-11eb-81b0-909e160234ca.png)
![image](https://user-images.githubusercontent.com/9373163/98464725-0ae53700-21c5-11eb-8de7-07b98ac3f320.png)
![image](https://user-images.githubusercontent.com/9373163/98465026-d2def380-21c6-11eb-8321-c5a115d8f0d7.png)

How did you install the dev version ? (installer, zip, git)

**Comment by A320PHX** [comment]
Via the installer. Here is a pic of me at the gate.

**Comment by A320PHX** [comment]
I am closing the issue as after reinstalling the default A320 and reinstalling the A32NX, everything has returned to normal.
