### ISSUE TITLE
[BUG] Com Radio: Unable to tune xxx.370MHz ie. 118.370MHz

### ISSUE THREAD

**Issue by olski320** [flybywiresim/a32nx#1802]
**Mod Version**
 master

**Describe the bug**
 unable to tune xxx.370MHz on the com radios. I.e.  118.370MHz

**To Reproduce**
 tune 118.365 now try to tune 118.370 - it will be skipped and radio will tune to 118.375

1. Vatsim ATC freq required was 120.370Mhz
2.
3.

**Expected behavior**
tune into .370MHz

**Actual behavior**
 .370MHz is skipped and radio tunes from .365 to .375MHz

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by ThatRedMelon** [comment]
Frequencies, where the hundredths digit is a 2 or a 7, do not have both 0 and 5 in the thousandths, only a 5. It is intended behaviour. When ATC instructs you a frequency like 118.37 for example you would tune 118.375 because 118.370 is not a valid frequency under the channel spacing used.

**Comment by olski320** [comment]
Thanks for the explanation, good to know that. I noticed that .345 and .395 are also skipped.

**Comment by ThatRedMelon** [comment]
That would be the same as frequencies with a 2 or 7 but the other way around. Aviation frequencies use both 25kHz and 8.33kHz spacing and some frequencies like 118.370 and 118.345 are skipped as they do not line up with the spacing.
