### ISSUE TITLE
[BUG] Unable to remove Via waypoints from arrival

### ISSUE THREAD

**Issue by andyjb103** [flybywiresim/a32nx#1806]
Via waypoints are inserted into the flightplan, even when you set 'no via' in the mcdu.

**Comment by Bartegu** [comment]
I experience the same problem with the latest master version

**Comment by jakecreates** [comment]
Seems like an issue throughout the sim. Would be nice if FBW could fix this issue though.

https://forums.flightsimulator.com/t/cant-remove-via-waypoints-in-the-approach-tbm-a320nx/307158

**Comment by 2hwk** [comment]
Fixed by #4953 closing ☑️
