### ISSUE TITLE
[REQUEST] Multiple pages on Airways Page

### ISSUE THREAD

**Issue by beregor** [flybywiresim/a32nx#1807]
**Mod Version**

Master

**Describe the bug**

In MCDU and when u add airways, you only have one page so when you filled that one out you dont get an new
page to put airways into, so only way to add more waypoints is to go into the last waypoint and press next waypoint

**To Reproduce**

Go to flight plan and AIRWAYS then add waypoints until the first page its full

**Expected behavior**

Should get an new empty page to add waypoints in

**Actual behavior**

dont get a new page

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

not tested

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by papinou57** [comment]
hello
when I enter a star in the FMS it always creates a very strange altitude for one of the points of the STAR and it is the cruising altitude .... here is a real very annoying bug which prevents the use of the autopilot managed on arrival

**Comment by beregor** [comment]
> hello
> when I enter a star in the FMS it always creates a very strange altitude for one of the points of the STAR and it is the cruising altitude .... here is a real very annoying bug which prevents the use of the autopilot managed on arrival

If you feel that is a bug please make your own bug report instead of replying to my bug report that is about a total diffrent issue.

**Comment by krangerich** [comment]
I think, it's correct to only have one page, at least for honeywell. This is from a FCOM with honeywell MCDU:

![image](https://user-images.githubusercontent.com/7890659/99190915-b3693d00-2769-11eb-9150-26bd9d43da58.png)

**Comment by tracernz** [comment]
Closing this as @krangerich's FCOM reference matches the Honeywell Pilot's Guide.
