### ISSUE TITLE
[BUG] Speed brakes can be controlled manually when armed

### ISSUE THREAD

**Issue by nistei** [flybywiresim/a32nx#1810]
**Mod Version**
master @ 3dd9cf63ed0f04f8eb95041ec719447dc303f171

**Describe the bug**
When the speed brakes are armed (lever pulled out) the speed brakes can still be controlled manually using an external input. The lever doesn't move when doing this.

**To Reproduce**
1. Map the speed brake to an input device
2. Arm the speed brakes in flight (Pull out lever)
3. Move the speed brakes using the input device

**Expected behavior**
Speed brakes can not be controlled manually or the armed mode disengages and the speed brakes + lever move.

**Actual behavior**
Speed brakes move and can be controlled manually while armed.

**References**
![image](https://user-images.githubusercontent.com/1652722/98472009-4ba67580-21f0-11eb-8594-b5fab814ca1c.png)
![image](https://user-images.githubusercontent.com/1652722/98472021-624ccc80-21f0-11eb-940a-3fa862dae386.png)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
Not tested

Discord username (if different from GitHub): nistei#1362

**Comment by frankkopp** [comment]
Can confirm this issue.

**Comment by sidnov** [comment]
> the armed mode disengages and the speed brakes + lever move.

This is the updated behavior as checked on the latest dev build.
