### ISSUE TITLE
[BUG] Inconsistent MAGENTA color between DUs

### ISSUE THREAD

**Issue by stevex77** [flybywiresim/a32nx#1814]
**Mod Version**

DEVELOPMENT
built: 2020-11-08T18:02:05+00:00
ref: refs/heads/master
sha: 9ecc85c0d81df306c5b66b2a29bc94aa9ab56ea1
actor: lukecologne
event_name: push 

**Describe the bug**

Inconsistent MAGENTA color between display units.

**To Reproduce**

1. Spawn at the gate
2. Power on DUs (at least PFD and ND)
3. Try to display some MAGENTA info on each DU, notice differences

**Expected behavior**

Color representation on all DUs should be exactly the same

**Actual behavior**

Especially MAGENTA is very different between PFD and ND.

**References**

Actual screenshot from A32nx
![02](https://user-images.githubusercontent.com/51388935/98484906-f3349f80-2212-11eb-9eaf-a7d8cfbb7801.png)

"Reference" snip from YT video:
![01REF](https://user-images.githubusercontent.com/51388935/98484917-00ea2500-2213-11eb-8baf-7d7de0d25999.png)

**Additional context**

Colors still need some tweaking, IMO the saturation is too high in some cases (green?, cyan?), sholdn't "burn out" pilot's eyes, shouldn't attract all the pilot's attention , but I'm not really sure about this...
High quality IRL reference needed.

Was this working before/when did the issue start occurring?
Yes

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):
SteveX77 [Z+0!]#1407

**Comment by Benjozork** [comment]
cc. @MisterChocker @wpine215

**Comment by Benjozork** [comment]
Being investigated

**Comment by MisterChocker** [comment]
#1812 might fix constraint color, will look for the others.

**Comment by ilyeshammadi** [comment]
I've included the changes to the color for the constraint in this #1812

**Comment by stevex77** [comment]
Just partially fixed in #1812. Where constraint number are colored to #FF94FF, these circles around constrained waypoints on the map still seem to be #FF00FF ("pure" magenta).

According to this IRL video https://www.youtube.com/watch?v=TEi-WX08ov8 all constraint elements on ND (believe all magentas on all DUs within the aircraft) should be the same color, something between magenta and pink.

**Comment by MisterChocker** [comment]
This has been fixed by now.
