### ISSUE TITLE
[BUG] APU remains available even with MASTER OFF and BLEED OFF

### ISSUE THREAD

**Issue by Pilot-leo** [flybywiresim/a32nx#1815]
**Mod Version**
 Master

**Describe the bug**
 The APU remains AVail. long after the master has been turned OFF as well as the Bleed off. The flap remains Open 

**To Reproduce**
 Load the A32ONeo at gate go through startup up to T/o 
 did a flight from EDLP to EGKK and from the moment I load the A320 up to the end ,the APU was always turned ON
1.
2.
3.

**Expected behavior**
 The APU should turn of and the flap closed

**Actual behavior**
APU ON flap ON 

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning
