### ISSUE TITLE
[REQUEST] Cost Index

### ISSUE THREAD

**Issue by luke-stec** [flybywiresim/a32nx#1816]
**Is your feature request related to a problem? Please describe.**
No

**Describe the feature you'd like to see implemented**
Would like to see Airbus CI implemented into the MCDU. Airbus reference provided below.

**References**
https://ansperformance.eu/library/airbus-cost-index.pdf

**Additional context**

Discord username (if different from GitHub):

**Comment by lousybyte** [comment]
CI does affect managed speeds to a certain degree as it stand now. Be aware that it uses the Honeywell FMS, CI values are between 0-999 instead of 0-99, so add another 0 if you pick the value from Simbrief.

**Comment by Annolago** [comment]
Follow-up question to the comment about simbrief. As the 320 Neo is not there as a selectable model what should be entered to ensure that the created flight plan is correct in its calculations?

**Comment by WoodyWoodsta** [comment]
@Annolago The readme on this project indicates the airframe this mod is designed to replicate. At the moment most of us probably use A320-200. We'd need to look around at how to get the correct airframe better represented.

**Comment by MisterChocker** [comment]
Duplicate of #345
