### ISSUE TITLE
[BUG] Typo on PERF pages (O/0)

### ISSUE THREAD

**Issue by beheh** [flybywiresim/a32nx#1823]
**Mod Version**

master@ 1bbab5800817b94fc74411c234548cb31dc5c90c (latest)

**Describe the bug**

The CLEAN O= speed has a typo on the APPR and GO AROUND phase on the PERF page. It incorrectly uses zero instead of the letter O. It's correct on the TAKE OFF phase.

**To Reproduce**

1. Start a new flight, cold and dark
2. Open the PERF page on the MCDU
3. Go through the various phases and watch the CLEAN O= speed and observe it changing

**Expected behavior**

The letter O should be used on all pages where the CLEAN speed is shown.

**Actual behavior**

TAKE OFF uses the letter O, APPR and GO AROUND use the digit zero.

**References**

![PERF TAKE OFF](https://user-images.githubusercontent.com/929769/98523984-e2b61080-2276-11eb-8493-685dce2d9573.png)
![PERF APPR](https://user-images.githubusercontent.com/929769/98523924-cdd97d00-2276-11eb-8e20-8c31c85f81b2.png)
![PERF GO AROUND](https://user-images.githubusercontent.com/929769/98524065-01b4a280-2277-11eb-9629-a47c3b6112b2.png)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game? Most likely

Discord username (if different from GitHub): BehEh#1234

**Comment by beheh** [comment]
I'm putting together my first PR for this.

**Comment by Benjozork** [comment]
Hello, please rework to fit #1830
