### ISSUE TITLE
[BUG] F-plan doesn't works

### ISSUE THREAD

**Issue by Tb3986** [flybywiresim/a32nx#1825]
**Mod Version**
0.4.1 Stable

**Describe the bug**
F-plan doesn't works. I press on the button and nothing happen. I can't choose any SID or Approches.

**To Reproduce**
1. MCDU
2. F-Plan
3. First button and i'm stuck.

**Expected behavior**
Should work like the original mod by fms2020

**Actual behavior**
Doesn't works.

**References**
Here a video

https://www.youtube.com/watch?v=yKBbkswkkCI

**Comment by Benjozork** [comment]
You need to clear the GPS PRIMARY message first.

**Comment by Tb3986** [comment]
Ok solved, i'm pretty noob, sorry ^^

Have a good day
