### ISSUE TITLE
[REQUEST] Integrate the EFB with Navigraph

### ISSUE THREAD

**Issue by zzyzxuk** [flybywiresim/a32nx#1831]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**

Some EFB's I've seen on other aircraft have the ability to display charts.  Since many of us have/use Navigraph, it would be wonderful if the FBW EFB might at some point in the future allow us to hit a button and pull up Navigraph charts on it's display.

**References**

**Additional context**

Discord username (if different from GitHub): zzyzxuk

**Comment by Pleasure0102** [comment]
This is a planned feature. We are working together with navigraph and will hopefully have that option for you in the future

**Comment by zzyzxuk** [comment]
Fantastic!

**Comment by tracernz** [comment]
Done in #4026.
