### ISSUE TITLE
[REQUEST] Integrate the MCDU with Haversine's AirFMC?

### ISSUE THREAD

**Issue by zzyzxuk** [flybywiresim/a32nx#1833]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**

haversine.com have a product called AirFMC which allows you to turn your iPad into a replica FMC, which is easier to work with than doing a lot of mouse clicking in MSFS2020.  At the moment they don't support MSFS2020 because they can't seem to get the right data out of it, but if the FBW crew end up re-writing the underlying code, might it be possible to then do that integration?  It would be fantastic if we could use our iPads in this way... :)

**References**

http://www.haversine.com/airfmc

**Additional context**

Discord username (if different from GitHub):

**Comment by sidnov** [comment]
We have our own MCDU Server for this now. https://docs.flybywiresim.com/fbw-a32nx/feature-guides/web-mcdu/
