### ISSUE TITLE
[BUG] APU never turns OFF and is directly ON

### ISSUE THREAD

**Issue by Pilot-leo** [flybywiresim/a32nx#1836]
**Mod Version**
 Master Branch (Dev Versions from downloader)

**Describe the bug**
 So, when switching the battery ON, the Lower ECAM page shows that the APU turned OFF --> OK, when switching the master ON, BUT NOT PUSHING THE APU STARTER, there is no spool up anymore and the ecam shows directly the APU n=100% and EGT=393°. Flap Open. The APU gen also shows 0% 115V and 400 Hz

**To Reproduce**

1. Load any A320 at a gate of your choice in CandD
2.Turn Battery ON 
3.Switch APU master ON

**Expected behavior**
The APu should still be turned off and should wait for the starter to be pressed before spooling up and stabilise after a few seconds/minutes

**Actual behavior**
 described above

**References**

**Additional context**

![Microsoft Flight Simulator Screenshot 2020 11 09 - 18 26 18 49](https://user-images.githubusercontent.com/74159073/98575022-f5513980-22b8-11eb-99fc-6e565e1ccaf0.png)
![Microsoft Flight Simulator Screenshot 2020 11 09 - 18 26 14 31](https://user-images.githubusercontent.com/74159073/98575030-f71afd00-22b8-11eb-8dc7-0bb6bb904019.png)

Was this working before/when did the issue start occurring? 3 days ago

Is this a problem in the vanilla unmodded game?

 
pilot_Leo
Discord username (if different from GitHub):

**Comment by MisterChocker** [comment]
Can you please recheck with latest master?

**Comment by NathanInnes** [comment]
@Pilot-leo

**Comment by Pilot-leo** [comment]
Not at home for the whole week.
Cant test anything now

Le dim. 3 janv. 2021 à 22:52, Nathan Innes <notifications@github.com> a
écrit :

**Comment by Mattyb21** [comment]
@Pilot-leo I had this same problem. It was due to a switch being flicked on my throttle which was assigned in the sim to APU. I've deleted the assignment and the problem has since been resolved.

**Comment by MisterChocker** [comment]
Closing since no response from op.
