### ISSUE TITLE
[BUG] Autobrakes are disabling when manual breaks are activated

### ISSUE THREAD

**Issue by tellurics** [flybywiresim/a32nx#1837]
**Mod Version**

**Describe the bug**
Autobrakes always turn off when I use manual brakes.

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?
This always happen.

Is this a problem in the vanilla unmodded game?
No.

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by lukecologne** [comment]
Does not respect template
