### ISSUE TITLE
[REQUEST] Delete,add,edit STARs waypoints

### ISSUE THREAD

**Issue by jsid87** [flybywiresim/a32nx#1838]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**
To be able to delete,add STAR waypoints in MCDU after selecting approach.

**References**

**Additional context**

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
)

**Comment by Benjozork** [comment]
> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning
