### ISSUE TITLE
[BUG] Cannot access PERF page on MCDU, cannot select ARRIVAL/DEPPARTURE runways

### ISSUE THREAD

**Issue by luke-stec** [flybywiresim/a32nx#1840]
**Mod Version**
Latest DEV version

**Describe the bug**
Since the last DEV update, cannot access PERF page or select runways for departure or arrival

**To Reproduce**

1.Load aircraft cold and dark
2.Load flightplan
3.Attempt to put in the flightplan, Fill out init A/B as desired, Attempt to choose runways and select PERF page

**Expected behavior**

Should be able to access runways and PERF page

**Actual behavior**

Does not work as mentioned above

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Hello, please open one issue per problem.
