### ISSUE TITLE
[BUG] Cannot select DEPARTURE/ARRIVAL runways

### ISSUE THREAD

**Issue by luke-stec** [flybywiresim/a32nx#1842]
**Mod Version**
Latest master

**Describe the bug**
When creating a flightplan, cannot select arrival or departure runways, they show up but nothing happens when selecting them

**To Reproduce**

1. Start, cold and dark or on runway
2.Create a flighplan, fill out INIT A/B as needed
3.Attempt to select departure and/or arrival runways

**Expected behavior**
Should be able to select and insert departure and arrival approach runways

**Actual behavior**
Nothing happens when clicking runways

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Issue started occurring with latest Develpment/Master
Is this a problem in the vanilla unmodded game?
No, Works in Stable 4.1 aswell

Discord username (if different from GitHub):

**Comment by ilyeshammadi** [comment]
Probably related to the exception happening in #1841

**Comment by ilyeshammadi** [comment]
I'm not having this issue anymore when cold startup after the fix in this PR https://github.com/flybywiresim/a32nx/pull/1843

**Comment by luke-stec** [comment]
PR #1843 has fixed it!
