### ISSUE TITLE
[BUG] Typo on IRS Init page

### ISSUE THREAD

**Issue by beheh** [flybywiresim/a32nx#1844]
**Mod Version**

master @ f83582cedebea9fb9c96c7c5e6a2088fbdb26f21 (latest)

**Describe the bug**

The bottom right LSK has a space between `ALIGN ON REF` and the arrow `→`.

**To Reproduce**

1. Start a new flight, cold and dark, and turn on external power
2. Switch the ADIRS to NAV
3. Open the INIT page in the MCDU and enter an airport pair in the top right, then enter the IRS ALIGN page

**Expected behavior**

The bottom right LSK item should match the reference.

**Actual behavior**

It does not.

**References**

Honeywell docs:

![IRS INIT documentation reference](https://user-images.githubusercontent.com/929769/98640637-acd26400-232a-11eb-9d29-cdff77be84be.png)

In game:

![grafik](https://user-images.githubusercontent.com/929769/98641345-e48ddb80-232b-11eb-866d-2a027d2c8b41.png)

**Additional context**

Was this working before/when did the issue start occurring? Not that I'm aware of

Is this a problem in the vanilla unmodded game? No, IRS Init page does not exist

Discord username (if different from GitHub): BehEh#1234

**Comment by beheh** [comment]
The font sizes are also slightly messed up, but #1830 should fix that.

**Comment by paul92ilm** [comment]
Are you going to include this in your PR #1830 ?
I can do a PR for it but it's only 2 lines modifications (can give you the 2 little changes for your PR)

**Comment by beheh** [comment]
I mean it's not really related. It seems like this project favors single-purpose PRs. I mostly left this here for whoever to pick up that touches this page next time as it's so small. Otherwise feel free to just file it (or I can).

FWIW I would have filed this as PR right away, but the PR docs specifically ask for filing an issue first.
