### ISSUE TITLE
[BUG] PERF key on MCDU inoperable

### ISSUE THREAD

**Issue by flitzpiepe0815** [flybywiresim/a32nx#1846]
**Mod Version**

latest master

built: 2020-11-10T00:17:10+00:00
ref: refs/heads/master
sha: f8db61f46da0bca99a13973585059bb251333e43
actor: wpine215
event_name: push

**Describe the bug**

PERF page key not working / PERF inoperable

**To Reproduce**

1. press PERF key on MCDU
2. nothing happens

**Expected behavior**

PERF page appearing after push of PERF key on MCDU

**Actual behavior**

Nothing happens, PERF page doesn't appear. Key seems inoperable.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
 • Worked with prior build.

Is this a problem in the vanilla unmodded game?
 • No. Without the mod, PERF page appears normally.

Discord username (if different from GitHub):
flitzpiepe0815#5472

**Comment by ErikNL80** [comment]
Can reproduce the issue here with the latest master as described above.

**Comment by wpine215** [comment]
Fixed with #1843
