### ISSUE TITLE
[solved(?) BUG] Descent rate too low vs taxiing with idle thrust

### ISSUE THREAD

**Issue by vlbreda** [flybywiresim/a32nx#1847]
**Mod Version**
Latest dev. (nov 10th 12.00)

**Describe the bug**
A week or so ago we had a discussion about descent rate. With the new engine tuning, the descent rate turned out to be too little. Taxiing with idle thrust however worked fine. 
Since then, I've been trying to modify the flight_model.cfg file to match a realistic descent rate with taxiing on idle thrust. Turns out the zero lift drag coeefficent plays a vital role here. By increasing this variable to 0.0437 the planes gets a realistic descent rate and taxis well on idle thrust. Don't know however whether the fuel consumption is affected by this. Hope this information may be usefull to you / other users.

**To Reproduce**

1. Open flight_model.cfg
2. Under AERODYNAMICS, change drag_coef_zero_lift into 0.0437
3.

**Expected behavior**

**Actual behavior**
Descent rate and taxiing on idle thrust are more realistic no.

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment]
if you are working on that stuff please join us in #1580 as well as the corresponding discord channel.

**Comment by Benjozork** [comment]
Not a bug report. As @MisterChocker said, please join our discord to discusss this 🙂
