### ISSUE TITLE
[REQUEST] delete,add,edit STARs waypoints

### ISSUE THREAD

**Issue by jsid87** [flybywiresim/a32nx#1848]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**
To be able to delete,add STAR waypoints in MCDU after selecting approach.

**References**

**Additional context**
I'm using Navigraph beta for navdata. Sometimes when I select approach there are missing or wrong waypoints in MCDU. So I would like to be able to edit them. 

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Duplicate of #1388
