### ISSUE TITLE
[REQUEST] Displays in separate window

### ISSUE THREAD

**Issue by OFC1983** [flybywiresim/a32nx#1849]
**Is your feature request related to a problem? Please describe.**

Yes, currently it is not possible to have any instrument or the MCDU or the FCU in a separate window. This should be possible to have these on a separate monitor and is already possible for the MSFS windows, such as Camera or ATC Control.

**Describe the feature you'd like to see implemented**

Possibility of detaching Panel parts, such as the PFD to a separate window which can be dragged to another monitor. In the end you have a monitor with important instruments and other monitors displaying i.e. the surrounding landscape.

**References**

**Additional context**

Discord username (if different from GitHub):

**Comment by ThatRedMelon** [comment]
This is possible by holding right-alt and left clicking on a display. It will pop into a separate window that can be dragged around to another display.

**Comment by OFC1983** [comment]
Unfortunately, this doesn't work. Is it possible, that there is an issue with the new update today? Latest version is 1.10.11.0...

**Comment by ThatRedMelon** [comment]
I have verified on the discord that this feature is still possible in the latest patch. The cursor should change to a magnifying glass with a plus in it to signify it can be popped out.

**Comment by OFC1983** [comment]
Thank you so much, it works! Turned out that the key assignment for the "NEW UI WINDOW MODE" in the control settings had a different key assigned. Put it back to standard and that did the magic for me :-).
