### ISSUE TITLE
Batteries have the same voltage when only 1 of them is engage

### ISSUE THREAD

**Issue by ColdChicken1** [flybywiresim/a32nx#185]
Hi, the voltage from the batteries is the same for both when only 1 of them is engage.
Expected : 1 battery not charging ∼ 25V and 1 battery charging ∼ 28V

![image](https://user-images.githubusercontent.com/70350159/91558838-4b0f7a00-e937-11ea-84e0-4ebcca4a4b8e.png)

Is this a sim bug, or can you fix it?

**Comment by JackZ974** [comment]
The battery simulation is very poor right now.

**Comment by davidwalschots** [comment]
Battery simulation was added in #3625.
