### ISSUE TITLE
[BUG] Overhead panel switches and buttons are INOP on latest dev build

### ISSUE THREAD

**Issue by kielyscott** [flybywiresim/a32nx#1851]
**Mod Version**

built: 2020-11-10T15:19:38+00:00
ref: refs/heads/master
sha: 6cb5116649c223cba11e7eec6ee39fcba9ecfb68
actor: Benjozork
event_name: push

**Describe the bug**

Overhead panel buttons and switches are non responsive. This was an aissue before the latest patch (10/11/2020) and with the latest patch. 

**To Reproduce**

1. Try and move the ADIRS knobs
2. Try and press a cabin call button
3. 

**Expected behavior**

I would expect the AIRS to move to NAV and ATT freely, but they do not. I would also expect CALLS to be pushable.

**Actual behavior**

**References**

**Additional context**

Unfortunately, I didt go through each button and switch, however a mixed variety are working and are not working. ADIRS, AIR COND, seatbelts, CALLS for sure are not working.

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub): skbtx

**Comment by wpine215** [comment]
Just ran the latest dev build and all those buttons and switches worked fine for me. Make sure you delete your entire folder before re-installing the mod, and if you're not using the installer or vmaster release, keep in mind you need to run "npm run build"

**Comment by liebbe10** [comment]
Same problem after sim update #6. Also all the liveries are gone (except for the FBY livery)

**Comment by kielyscott** [comment]
Thanks, however I did clean out my mods folder and am using the installer.

This was also happening to me before patch 6.

**Comment by martysweet** [comment]
> Same problem after sim update #6. Also all the liveries are gone (except for the FBY livery)

Might be unrelated but I just had this after updating MSFS. All custom liveries were gone apart from FBY and the game launched me into the original game version of the A320. The overhead panel was different, displays came on instantly. After closing MSFS, I redownloaded the dev version of A32NX (because I wanted to update anyway) and replaced in my community folder. After launching the game again, everything looks good now!

**Comment by Benjozork** [comment]
Do you have the YourControl shared cockpit add-on installed m

**Comment by liebbe10** [comment]
> > Same problem after sim update #6. Also all the liveries are gone (except for the FBY livery)
> 
> Might be unrelated but I just had this after updating MSFS. All custom liveries were gone apart from FBY and the game launched me into the original game version of the A320. The overhead panel was different, displays came on instantly. After closing MSFS, I redownloaded the dev version of A32NX (because I wanted to update anyway) and replaced in my community folder. After launching the game again, everything looks good now!

Thx! worked for me :)

**Comment by stevex77** [comment]
This also happened to me once.

It was immediatelly after MSFS update to 1.10.11.0 when starting a flight (at the gate) without restarting the sim.
It probably loaded default (ASOBO) A320neo.

After sim restart, A32NX mod loaded successfully.

**Comment by MatiasBordoy** [comment]
> Do you have the YourControl shared cockpit add-on installed ?

is there any problem if you have installed Shared Cokpit?

**Comment by Benjozork** [comment]
Yes, currently not compatible with the dev version of the mod, and the stable version of the mod is not compatible with latest MSFS.
