### ISSUE TITLE
[BUG] F-PLN Page with same departure/Arrival Airport

### ISSUE THREAD

**Issue by pdf31** [flybywiresim/a32nx#1852]
**Mod Version**
built: 2020-11-10T15:19:38+00:00
ref: refs/heads/master
sha: 6cb5116649c223cba11e7eec6ee39fcba9ecfb68
actor: Benjozork
event_name: push

**Describe the bug**
With same airport selected as Departure and Arrival, F-PLN page is filled on all lines with Dep Airport

**To Reproduce**

1. Select LFMN/LFMN in Init
2. Go to F-PLN Page
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Was working before loading last FS Patch and Last dev 
![pdc1](https://user-images.githubusercontent.com/55210414/98731299-d1b3ef00-239d-11eb-9624-ed7b7bc3efd4.jpg)
![pdc2](https://user-images.githubusercontent.com/55210414/98731300-d24c8580-239d-11eb-98f8-1ea9fde2b6ef.jpg)

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by frankkopp** [comment]
Can confirm the issue

Last MSFS update: 1.10.11
Uninstalled all mods
Installed FbW Dev version
Started flight at gate in KLAX
Did INIT page and changed to F-PLN - see screenshot

![image](https://user-images.githubusercontent.com/16833201/98733594-0bd2c000-23a1-11eb-95f6-aab63b5b64f2.png)
![image](https://user-images.githubusercontent.com/16833201/98733554-f8bff000-23a0-11eb-8a89-21280306c460.png)

**Comment by Benjozork** [comment]
> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning

Probably wanna remove that :p
