### ISSUE TITLE
To Low Terrain Warning after Takeoff

### ISSUE THREAD

**Issue by Steven0785** [flybywiresim/a32nx#1857]
**Mod Version**
Latest Dev Version

**Describe the bug**
Instant after Rotate on runway gpws warn To Low Terrain Sounded

**To Reproduce**
For me any Takeoff after update the dev version Today

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Steven0785** [comment]
Reinstalled the mod and now it works fine 👍

**Comment by Benjozork** [comment]
Please fill the template next time.
