### ISSUE TITLE
ND PLAN Mode shows aircraft when ADIRS off

### ISSUE THREAD

**Issue by TobitFR** [flybywiresim/a32nx#186]
Hi,

I found that the PLAN Mode of the ND haven't a no ADIRS mode, if a make FPLN in the MCDU without ADIRS on (wich is in theory impossible) the PLAN page is showing up normally, so there is missing a "MAP NOT AVAIL" in this mode. 

![image](https://user-images.githubusercontent.com/31391535/91559934-3df38a80-e939-11ea-9328-08bcf8e0fe2f.png)

Should be this :
![image](https://user-images.githubusercontent.com/31391535/91560414-1fda5a00-e93a-11ea-9982-58caae1decaf.png)

**Comment by lousybyte** [comment]
Pretty sure that's intended and normal behavior.
[https://youtu.be/MywqXeeoYos?t=746](url)

**Comment by SeaRoll** [comment]
I think its more that the aircraft needs to be invisible in plan mode when irs has not aligned yet
