### ISSUE TITLE
[BUG] MCDU goes blakk screen after entering STAR procedure

### ISSUE THREAD

**Issue by AirKoKaine** [flybywiresim/a32nx#1861]
**Mod Version**

0.4.1  -  2020-10-31 used on MSFS2020  V1.10.11.0 latest relaese

a32nx

**Describe the bug**

On MCDU, planing Flight Plan,, once entering arrival STAR it ends up that the MCDU goes black creen

**To Reproduce**

1. Enter STAR chose Appraoch runway Example LFPG ILS 26R
2. Enter ARRIVAL PROCEDURE Example OKASI4B
3. Enter "INSERT" Then screen goes black, and no other option shown on MCDU screen, the whole PL is gone.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Yes
Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by AirKoKaine** [comment]
Got the solution of that issue.
In community folder, I erased navigraph navdata  item
no more "UNTITLED" message on black screen

**Comment by JG4Thorwald** [comment]
Same for me. delete navigraph navdata folder doesn't help.
It appears also, when starting a flight with FP from MSFS with SID and STAR procedure.
Tried with the latest dev version, downloaded and installed with the downloader
