### ISSUE TITLE
[BUG] [MCDU]  "GPS PRIMARY" is always displayed and I cannot enter it.

### ISSUE THREAD

**Issue by soniccruiser** [flybywiresim/a32nx#1862]
**Mod Version**

Development version. 11th Nov 2020

**Describe the bug**

The MCDU display always shows "GPS PRIMARY" or "GPS PRIMARY LOST".
![MCDU](https://user-images.githubusercontent.com/59490312/98817349-56217300-246d-11eb-89e2-d3d45222bb42.jpg)
 When I type it, I hear a key click, but the value is not displayed and is not reflected.

**To Reproduce**

 It is generated from the initial state.  

**Expected behavior**

**Actual behavior**

Before the GPS alignment is completed, "GPS PRIMARY LOST" is displayed.
When the alignment is complete, the display changes to "GPS PRIMARY"
The screen changes according to each mode, but the "GPS **" part does not change.

**References**

**Additional context**

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by vlbreda** [comment]
Press the clr button. It will remove the displayed GPS-status.

**Comment by Benjozork** [comment]
See above, intended behavior.
