### ISSUE TITLE
VOR/NDB needed on ND. As well Bird (FPV) required!

### ISSUE THREAD

**Issue by A320321** [flybywiresim/a32nx#1864]
**Is your feature request related to a problem? 

Not possible to perform non precision approaches in raw data without any VOR/NDB depicted on the ND. Bird as well required to fly a descent angle and not descent rate.

**Describe the feature you'd like to see implemented**
VOR/NDB arrows depicted on ND when requested and FPV (flightpath angle) option.

**References**
FCOM/procedure/normal operation/approach guidence/non precision approach

**Comment by theomessin** [comment]
Suggest you break this into two separate issues...

**Comment by MisterChocker** [comment]
Duplicate of #2195
