### ISSUE TITLE
[BUG] Wrong ALT knob behavior

### ISSUE THREAD

**Issue by St54Kevin** [flybywiresim/a32nx#1871]
**Mod Version**
12/11/2020 master

**Describe the bug**

When switching the ALT knob on the FCU to 1000ft steps and turning the knob it increases current set value by 1000.

**To Reproduce**

1. Switch knob to 100ft increments
2. set something like 5500ft
3. Switch back to 1000ft increments
4. turning the knob increases ALT by 1000ft

**Expected behavior**

With the **first** turn it should round to the next 1000ft. So In my example turning it up should put it to 6000ft and **then** 1000ft steps. Same for downwards

**Actual behavior**

1000ft steps right from the first turn

**References**

Experience

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by lars-reimann** [comment]
I can have a look at this. I take it, that the same behavior should be applied when decreasing the altitude, i. e. it should go from 5500ft down to 5000ft if the decrement is 1000ft.

**Comment by lars-reimann** [comment]
Would this be the correct behavior? The left column show the original altitude and the other columns what should be displayed after the change in the header is made.

|original altitude  | -100  | +100  | -1000   | +1000   |
|---|---|---|---|---|
|   100| 100  |200   | 100  | 1000  |
|  400 |  300 | 500  | 100  | 1000  |
|  4000 | 3900  | 4100  | 3000  | 5000  |
|  4400 |  4300 |  4500 | 4000  | 5000  |
| 49000  |  48900 | 49000  | 48000  | 49000   |

**Comment by St54Kevin** [comment]
> Would this be the correct behavior? The left column show the original altitude and the other columns what should be displayed after the change in the header is made.
> 
> |original altitude  | -100  | +100  | -1000   | +1000   |
> |---|---|---|---|---|
> |   100| 100  |200   | 100  | 1000  |
> |  400 |  300 | 500  | 100  | 1000  |
> |  4000 | 3900  | 4100  | 3000  | 5000  |
> |  4400 |  4300 |  4500 | 4000  | 5000  |
> | 49000  |  48900 | 49000  | 48000  | 49000   |

Yes that's correct
