### ISSUE TITLE
[BUG] CDU destination missing

### ISSUE THREAD

**Issue by cellotako** [flybywiresim/a32nx#1873]
**Mod Version**

built: 2020-11-11T06:51:18+00:00
ref: refs/heads/master
sha: 03831bb4d7b73d0e532b73ce8872189eb05b84c7
actor: Benjozork
event_name: push

**Describe the bug**

When I input same airport, CDU flight plan shows only "FROM"

**To Reproduce**

1.hit INIT
2.RJTT/RJTT
3.F-PLN

**Expected behavior**

FROM RJTT
DEST RJTT

**Actual behavior**

FROM RJTT
FROM RJTT
FROM RJTT
...

**References**

![image](https://user-images.githubusercontent.com/73720713/98932211-621b3c80-2522-11eb-864d-483620dd3393.png)

**Additional context**

Was this working before/when did the issue start occurring?
yes
Is this a problem in the vanilla unmodded game?
yes

Discord username (if different from GitHub):

__Cellotako#1652

**Comment by beheh** [comment]
I believe this duplicates #1852 and has been since fixed with #1856.

**Comment by cellotako** [comment]
thx
