### ISSUE TITLE
[BUG] Engine Reverser

### ISSUE THREAD

**Issue by cellotako** [flybywiresim/a32nx#1874]
**Mod Version**

**Describe the bug**

Why is the cowl opening degree synchronized to the level of reverse thrust? it should be fully opened despite its thrust level. hope this will be changed.

**To Reproduce**

1.(set some axis for reverser thrust via FSUIPC)
2.see it from outside view
3.

**Expected behavior**

it should be fully opened despite its thrust level. 

**Actual behavior**

cowl opening degree synchronized to the level of reverse thrust

**References**

https://www.youtube.com/watch?v=uUw_HLNu2ZA

**Additional context**

Was this working before/when did the issue start occurring?
no
Is this a problem in the vanilla unmodded game?
yes

Discord username (if different from GitHub):

**Comment by Rameyuk** [comment]
I think you should also refer a video of what the expected behaviour of the reverse thrust cowl in relative to the applied reverse thrust lever.

**Comment by cellotako** [comment]
Should be like this
https://youtu.be/nTSCWX5pmIc
Reverser cowl CAN’T synchronized to its reverse thrust level.

**Comment by N1EL** [comment]
I agree, The reverser doors etc open to the same point regardless of reverse thrust used.
