### ISSUE TITLE
[BUG] Speedbrakes "Nerfed"

### ISSUE THREAD

**Issue by dcherrie** [flybywiresim/a32nx#1876]
**Mod Version**
Development Version as of the time of this post.

built: 2020-11-12T02:54:20+00:00
ref: refs/heads/master
sha: 421fc9e8c7426db8b69270ff55975a2a039176b1
actor: Benjozork
event_name: push

**Describe the bug**
Performance of spoilers in flight and upon landing have drastically reduced effect. 

**To Reproduce**
Deploy spoilers to 100% inflight whilst descending at a normal rate of descent and speed is barely reduced. When descending at a higher rate of descent, spoilers fail to keep the aircraft from accelerating.

**Expected behavior**
Spoilers should decelerate an aircrafts speed even if it is descending at 3000fpm by deploying 20-40%
A plane should not easily be able to take off and climbing with their spoilers deployed 100%. 

**Actual behavior**
You can land and take off with no issue with the speedbrakes fully deployed. Speedbrakes fail to manage and slow the speed of the aircraft within normal operations or make the plane approach a stall.

**References**
Landing with speedbrakes 100% during approach:
https://www.youtube.com/watch?v=ymI7CHNi-II&feature=youtu.be

Take-off with speedbrakes 100%:
https://www.youtube.com/watch?v=g5Ol4FSzBBk&feature=youtu.be

**Additional context**
Ignore the bad landing as at 10ft I got a lot of ECAM warnings that startled me.

Was this working before/when did the issue start occurring?
A developer on Discord said that they purposely nerfed the speedbrakes to make it more realistic and had no complaints from the real life pilots. I will talk with my friend who is an A320 pilot and hopefully he will be able to test out over the next few days and comment further on this.

Is this a problem in the vanilla unmodded game?
No.

Discord username (if different from GitHub): davidcherrie

**Comment by sillycornet** [comment]
Your approach video has modes of THR CLB/ OP CLB. Not sure what you did to get these on approach, but speed brakes won't help you if you're fighting the ac.

**Comment by Oberstumfuher** [comment]
Your problem is that you don't use managed speed, even if you have the spoiler, the aircraft will accelerate to maintain the speed you set.

**Comment by hotshotp** [comment]
This is intended behaviour. Please follow approach plates, but this behaviour has been confirmed by irl pilots as correct

**Comment by dcherrie** [comment]
@hotshotp @Oberstumfuher I was following the approach plates for Heathrow which is to maintain 180 knots of greater until 4 DME. When I was on descent to get down to 7000. I had a fast descent at more than 2400fpm and with the speed brakes fully deployed, I was still accelerating even with the thrust levers at idle. ATC kept telling me to decrease the speed to 220 knots as per the ALESO1H arrival but I was still at 280+ and couldn’t slow down.

I will do another couple of flights today and have my friend look at them who is an A320 pilot but spoilers should be able to maintain or decrease your speed on descent if you are descending at more than 800fpm.
