### ISSUE TITLE
MCDY not obeying speed restriction 250 below 10000[BUG] INSERT TITLE HERE

### ISSUE THREAD

**Issue by Captherky** [flybywiresim/a32nx#1878]
**Mod Version** 4.1 Dev version

**Describe the bug**

follow SID from EGKK. Aircraft accelerates to 280. Setting speed to managed 250 doesnt slow the aircraft.

**To Reproduce**

1. Follow SID in managed speed managed altitude modes.

2. Aircraft climbs at 280 knots.
3. Aircraft doesnt obey speed restriction 250 below 10000'

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning
