### ISSUE TITLE
[BUG] A320 INSTRUCTOR IN REAL LIFE

### ISSUE THREAD

**Issue by javiiberia** [flybywiresim/a32nx#1880]
**Mod Version**

**Describe the bug**

1) When selecting TO FLEX in MCDU, the N1 corresponding to that TO FLEX does not appear in upper ECAM screen.
2) Once the aircraft has taken off (being in MAN FLX mode) when the aircraft reaches reduction altitude, you reduce thrust and it changes to SPEED mode, not to THRUST CLB mode as it should be
3) Clock in the cockpit shows local time not UTC time
4) Some symbols in ND do not look like real ones
5) In cruise altitude the aircraft goes at pitch of 5º attitude when it should be at 3,5º approximately
6)Poor performance on the aircraft climbing (with low payload). It climbs at 800ft/min when has 8000ft remaining to reach optimum altitude shown in the FMC
7) Climbing, in THURST CLB mode it goes at a faster N1 than the CLB limit shown in the upper ECAM screen
8)When disconnecting the PACK 1&2 for takeoff, if you do not connect them again once taken off, it does not appear any message in the ECAM or any advisory
9) Constraints appearing in Navigation Display do not make any sense
10)When disconnecting PACKS 1&2 the sound remains the same in the cockpit of the aircraft, when it should be considerably reduced due to no airflow flowing from the air conditioning system inside the aircraft
11) When you put VOR 1&2 in the FCU on the captain´s side (also in the second first officer side) no VOR information appears in the Navigation Display. It should appear information in the Navigation Display (NM to VOR and direction TO/FROM the VOR) even though you have not selected any VOR in page RADNAV of the FMC, because the aircraft automatically detects the VOR´s with the strongest signal to appear in the ND when VOR/ADF is selected in the FCU. 
12) Cost index speed always remains the same. If you select cost index 6 for example it will show in PERF page 295kt managed speed. Later if you select a cost index of 200 the speed will show 295kt or 297kt maximum. The change in speeds in real life is larger than the aircraft shows
13) With MTOW and in cruise altitude (does not matter if at OPT ALTITUDE OR REC MAX) the PFD of the aircraft does not show the speed protection limit (yellow line), does not show the stall speed either (red line), does not show the green dot speed
.14) COND, PRESS, HYD,ELEC pages do not appear in ECAM
15) TOD nor TOC missing
16) EGT limits exceeded climbing in THRUST CLB mode.
17) STD altimeter mode in standby Integrated Standby Flight Display not appearing-->

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
Hello, please do not open a single issue for multiple problems. GitHub issues are for single confirmed issues with the template fully filled, which is not the case here.

I suggest you talk to us on our Discord beforehand, as many of those issues are being fixed at the moment or already reported. Besides, I already responded to you earlier explaining the status of many of these.

**Comment by Oberstumfuher** [comment]
https://www.youtube.com/watch?v=4NAs7DJ42eM&list=WL&index=245
