### ISSUE TITLE
[BUG] Missing glide path indicators and locator

### ISSUE THREAD

**Issue by redgonzales** [flybywiresim/a32nx#1881]
**Mod Version**
<v. 0.4.1>

**Describe the bug**
<during the approach procedure the two magenta diamonds do not appear for location and glide path, in some cases it appears for a moment and then disappears again. Before the last updates of FS2020 it worked fine. Maybe up to v. 1.10.7.0? I do not remember. For example on the flight from LIRN to LIRF (ILS34L), or from LIMJ to LIMC (ILS35R-Z), but in general it always works badly. 

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning
