### ISSUE TITLE
[BUG] Rarely, T.O cheklist remains displayed during all flight

### ISSUE THREAD

**Issue by JLD95** [flybywiresim/a32nx#1882]
**Mod Version**

Master 2020-11-10T15:19:38+00:00

**Describe the bug**

The take-off checklist remains displayed during all phases of flight

**To Reproduce**

1.  rarely, it is my first occurence
2.
3.

**Expected behavior**

check the conditions to displayed T.O checklist or to erase this message.
![2020-11-12 (2)](https://user-images.githubusercontent.com/5894146/98977423-e10b7780-2518-11eb-949b-c9e8293e3dfd.jpg)
![2020-11-12 (9)](https://user-images.githubusercontent.com/5894146/98977431-e36dd180-2518-11eb-8587-6cae1312a001.jpg)
![2020-11-12 (10)](https://user-images.githubusercontent.com/5894146/98977451-e7015880-2518-11eb-9ae4-daedae1cb0c7.jpg)

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Hello, please provide the precise version of the mod (contents of build-info.txt in the A32NX package of the Community folder) as indicated in the template.

**Comment by JLD95** [comment]
Hello, build number added

**Comment by Benjozork** [comment]
Thanks !

**Comment by CoffeePanda0** [comment]
Can agree I’ve had this maybe once in 20 landings with the same overlapping text

**Comment by lhoenig** [comment]
Also had this bug a couple of times, quite rarely.
