### ISSUE TITLE
Still in basic version MSFS and not in version A32NX 0.4.1

### ISSUE THREAD

**Issue by ciabrini** [flybywiresim/a32nx#1895]
hello, I'm a Frenchman also excuse my English please.

**Mod Version**
0.4.1

**Describe the bug**
In version 0.4.1, since the update of MSFS, I Still in basic VERSION MSFS and not in version A32NX 0.4.1

**To Reproduce**

1.Always
2.
3.

**Expected behavior**

**Actual behavior**

**References**

![image](https://user-images.githubusercontent.com/74412768/99076527-942cad00-25bb-11eb-878a-b91c1b525a4c.png)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by lukecologne** [comment]
>  0.4.1

> Master version

Can you clarify what version you are using?

**Comment by ciabrini** [comment]
> > 0.4.1
> 
> > Master version
> 
> Can you clarify what version you are using?

Excuse me, but since the last Windows update, it is another problem. I stay in the basic version of the A320

Excuse me +++

**Comment by Benjozork** [comment]
Please go to discord for installation help. GitHub issues are for plane bugs.

Make sure you don't have the YourControl add-on installed.
