### ISSUE TITLE
[REQUEST] Direct to - Radial in

### ISSUE THREAD

**Issue by linke92** [flybywiresim/a32nx#1899]
**Is your feature request related to a problem? Please describe.**
**The function is usually called “direct to - radial in” and makes it possible to align on extended centerline pretty easy and is a feature that is used a lot in real life.**

**Describe the feature you'd like to see implemented**
Be able to select the FAP (final approach point) with a radial that you want to follow leading to the point or from the point. The Lay-out from the direct to MCDU already shows the option on the right side but it’s not oparable.

**References**
MCDU direct to page already shows the input option on the right side.

**Additional context**

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by theomessin** [comment]
> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning

Feel free to open a new issue **provided you follow the given instructions**.
