### ISSUE TITLE
[BUG] Aircraft is unstable in flight 

### ISSUE THREAD

**Issue by sylatex** [flybywiresim/a32nx#1900]
[https://youtu.be/kkMOjO2GXUk](https://youtu.be/kkMOjO2GXUk) 

**Mod Version**
0.4.1

**Describe the bug**
Aircraft wobbles left and right at cruise altitude 

**To Reproduce**

1. 
2.
3.

**Expected behavior**

**Actual behavior**

Aircraft rocking left to right, unable to maintain stable flight with auto pilot at cruise altitude 

**References**

**Additional context**

Was this working before/when did the issue start occurring?

It was working fine before the newest MSFS update

Is this a problem in the vanilla unmodded game?

I haven't tried in the vanilla Aircraft 

Discord username (if different from GitHub):

**Comment by tareksabet** [comment]
Try to increase the deadzone on your controller as it is a sim bug from the vanilla plane

**Comment by sylatex** [comment]
> Try to increase the deadzone on your controller as it is a sim bug from the vanilla plane

Thanks for your suggestions but I doubt that. I only get it at altitude above FL300 plus it wasn't happening before

**Comment by Benjozork** [comment]
I don't see how either of those invalidate the workaround.

Either way, this already has been reported.

**Comment by sylatex** [comment]
> I don't see how either of those invalidate the workaround. I mean don't try it if you don't want to.
> 
> Either way, this already has been reported.

I wasn't aware it's been reported, can you please link where so I can go through the recommendations. I'll try the workaround anyway thanks

**Comment by Benjozork** [comment]
https://discord.com/channels/738864299392630914/771435594445226005/771437342577131521

**Comment by sylatex** [comment]
> https://discord.com/channels/738864299392630914/771435594445226005/771437342577131521

Thanks
