### ISSUE TITLE
[REQUEST] Missing cabin interior lighting

### ISSUE THREAD

**Issue by fingerratte** [flybywiresim/a32nx#1903]
**Is your feature request related to a problem? Please describe.**

Night flights are pretty cool in this game, but there is only dark on cabin seats. 

**Describe the feature you'd like to see implemented**

There is no cabin interior lighting (passenger seat). It would be so nice if you could ad some light to the two passenger seats, that are accessable, so night flight could be more immersive. 

**References**

I think this is obsolete.

**Additional context**

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
There is no cabin interior.

**Comment by fingerratte** [comment]
It's about the two seats by the window. Of course there is no modeled cabin. But you do have a small cutout when you look out the window. And it would be really nice if it was illuminated.

**Comment by fingerratte** [comment]
**BAD**
<a href="https://ibb.co/nQC2vD3"><img src="https://i.ibb.co/7r4c5Gg/cabin-12.jpg" alt="cabin-12" border="0"></a>
**BAD**
<a href="https://ibb.co/tCMTWqv"><img src="https://i.ibb.co/SvX49tM/Cabin-13.jpg" alt="Cabin-13" border="0"></a>
**GREAT!!! 
Well if that didn't come from the outside but from the inside ...**
<a href="https://ibb.co/PMQrMyM"><img src="https://i.ibb.co/nBCwByB/cabin-illuminated-13.jpg" alt="cabin-illuminated-13" border="0"></a>

**Comment by fingerratte** [comment]
This would be awesome guy's!

**Comment by MisterChocker** [comment]
you do know that cabin lights are dimmed or turned off to match outside conditions in case of an emergency?

**Comment by fingerratte** [comment]
Yes I know that. It was only important to me that you can see that there is no light source inside the "container" in which the small window section exists. Short question to the developer. How easy is it to add a new light source to a flight model? Just a short answer, if possible. 
I mean it's still just as dark on FL40. And that kills immersion for me (and for others, too).

**Comment by Snapmatics** [comment]
> Yes I know that. It was only important to me that you can see that there is no light source inside the "container" in which the small window section exists. The short question to the developer. How easy is it to add a new light source to a flight model? Just a short answer, if possible.
> I mean it's still just as dark on FL40. And that kills the immersion for me (and for others, too).

Alright... there is no button in the cockpit that actually controls the lights in the cabin. Only flight attendants can do that. So, that means that a panel is required into the cabin to be able to do that correctly.

**Comment by fingerratte** [comment]
> Alright... there is no button in the cockpit that actually controls the lights in the cabin. Only flight attendants can do that. So, < 

> that means that a panel is required into the cabin to be able to do that correctly. <

Maybe first with a shortcut? And the Option to dim... I could write an easy C# form (everybody could do that), to simulate that panel. But of course you will need an api.

**Comment by NathanInnes** [comment]
Going to close in favour of [Interior] #2577
