### ISSUE TITLE
Changed cockpit view in current master build

### ISSUE THREAD

**Issue by OscarLima99** [flybywiresim/a32nx#1904]
**Mod Version**
built: 2020-11-13T08:39:46+00:00
ref: refs/heads/master
sha: b5e09202ce9a3e4e62b07a4690fa44155f973fa1
actor: wpine215
event_name: push

**Describe the bug**
After installing the new master build as recommended, the standard cockpit view has changed.

**To Reproduce**
1. Start the sim
2. Load a flight
3. Observe the standard cockpit view

**Expected behavior**
The original standard view as before.

**Actual behavior**
Standard view seems to be to far ahead, slightly to high. 

Was this working before/when did the issue start occurring?
Yes/After installing the latest master build

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):
OsberticusMaximus

**Comment by Benjozork** [comment]
This is intended and more realistic as to where you'd sit in a real A320.

Please use Discord if you want to criticize changes, GitHub issues are for bugs and feature requests.
