### ISSUE TITLE
[BUG] Terrain display on ND not working

### ISSUE THREAD

**Issue by bluecew** [flybywiresim/a32nx#1905]
**Mod Version**
Latest master

**Describe the bug**
Clicking the TERR ON ND button turns it on but doesn't show any terrain on the ND. Used to work before but now it does not. I was near the ground.

**To Reproduce**
1. Fly near the ground.
2. Click the TERR ON ND button.
3. Look at the ND.

**Expected behavior**
There is supposed to be a colored terrain overlay on the ND that shows how close to the ground you are.

**Actual behavior**
Nothing happens on the ND, only the button sets to ON.

**References**

**Additional context**
This used to work two master branch updates ago. Now it is no longer working.

Was this working before/when did the issue start occurring?
Was working two master branch updates ago.

Is this a problem in the vanilla unmodded game?
No.

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Please provide the contents of the `build-info.txt` file as requested in the template.

**Comment by bluecew** [comment]
Never mind, working now. Had to reinstall the mod :D
