### ISSUE TITLE
Cold and dark crash 

### ISSUE THREAD

**Issue by ducky3333** [flybywiresim/a32nx#191]
hi.

basically, if i load aircraft to gate , the simulator working on Cold and dark mode.

and you know , When i use runway selection mode and flight is loaded, all instruments and engines are loaded with all instruments turned on.

in this status , all panel was been black.

**Comment by wpine215** [comment]
Can you provide a short video re-creating the issue?

**Comment by Curtis-VL** [comment]
Closing as no further info was provided. Please discuss this further in Discord if you need help!
