### ISSUE TITLE
[REQUEST] remain fan sound when turn on EXT PWR or APU

### ISSUE THREAD

**Issue by firstpon** [flybywiresim/a32nx#1912]
**Is your feature request related to a problem? Please describe.**

It doesn't feel right every time that the fans sound are faded down when you know it shouldn't. (Ambient sound before and after turn on the GPU are almost the same)

**Describe the feature you'd like to see implemented**

Remain fans sound after turn on the GPU and not faded down. (And maybe lower the volume of the fans by a bit)
(sound goes for engine sound after the startup too. seem to be almost the same ambient as before the startup.)

**References**

https://www.youtube.com/watch?v=Mo7A3CuVb8g
after 0:54 you can hear that the fans sound remain and not faded down.

Discord username (if different from GitHub): FIRST#9312

**Comment by hotshotp** [comment]
This has been a reported issue for the stable and has been fixed in the dev version.
