### ISSUE TITLE
[BUG] MCDU duplicated input

### ISSUE THREAD

**Issue by Kimbyeoungjang** [flybywiresim/a32nx#1916]
**Mod Version**
 current master(2020/11/14)

**Describe the bug**

when i input some value(let's value1) to MCDU some page, and i change page and try to write some value, value 1 value still remain MCDU

**To Reproduce**

1. for example, insert VOR freq on RAD NAV page on MCDU
2. going to INIT page
3. try to write Cost Index but there is a value still remaining
![1](https://user-images.githubusercontent.com/23118756/99143881-7129f800-26a4-11eb-826e-d3b4e165273a.JPG)
i write vor freq on RAD NAV page and going to init

![2](https://user-images.githubusercontent.com/23118756/99143883-7b4bf680-26a4-11eb-9a77-3f5e9da14a22.jpg)
when i press 4 for change costindex but there still value remain on mcdu

**Expected behavior**

must no value remain on mcdu

**Actual behavior**

remain on mcdu

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
No.

Discord username (if different from GitHub):

**Comment by stevex77** [comment]
I can reproduce and confirm this bug. When successfully entered some value on page "X", it disappear from "scratch line". After switching to another page and try to type anything, previously entered value appears plus newly inserted character. Not happening for various inputs at the same page.

**Comment by stevex77** [comment]
Maybe it's somehow connected with this issue (if not, I'll post a new issue), maybe I'm doing something wrong, but can't access INIT page B at all.
It alway shows me "NOT AVAILABLE" when presssing -> or <- MCDU buttons. On other MCDU pages these buttons work.

![INITB](https://user-images.githubusercontent.com/51388935/99154966-2c0dc200-26b4-11eb-911f-f1ac5a012914.png)

Also having trouble to enter ZFW/ZFWCG on the FUEL PRED page - when try something "valid", aber boxes remain empty, without any warning/error message.

![FUEL](https://user-images.githubusercontent.com/51388935/99155016-a3435600-26b4-11eb-86ae-9e8a290fd946.png)

I suspect this very complex PR https://github.com/flybywiresim/a32nx/pull/1834, but have no specific proof.

**Comment by krangerich** [comment]
> Maybe it's somehow connected with this issue (if not, I'll post a new issue), maybe I'm doing something wrong, but can't access INIT page B at all.
> It alway shows me "NOT AVAILABLE" when presssing -> or <- MCDU buttons. On other MCDU pages these buttons work.

INIT B page is locked after engine start. Perhaps the arrows should go to the Fuel Prediction page instead after engine start? We should look that up in the FCOM

**Comment by Venorcis** [comment]
Can confirm, the previous input constantly re-appears at seemingly random moments in the MCDU now on latest master.

**Comment by MisterChocker** [comment]
> Maybe it's somehow connected with this issue (if not, I'll post a new issue), maybe I'm doing something wrong, but can't access INIT page B at all.
> It alway shows me "NOT AVAILABLE" when presssing -> or <- MCDU buttons. On other MCDU pages these buttons work.
> 
> ![INITB](https://user-images.githubusercontent.com/51388935/99154966-2c0dc200-26b4-11eb-911f-f1ac5a012914.png)

This is the correct behavior after preflight.

> Also having trouble to enter ZFW/ZFWCG on the FUEL PRED page - when try something "valid", aber boxes remain empty, without any warning/error message.
> 
> ![FUEL](https://user-images.githubusercontent.com/51388935/99155016-a3435600-26b4-11eb-86ae-9e8a290fd946.png)
> 
> I suspect this very complex PR #1834, but have no specific proof.

This might be related to #1524

**Comment by MisterChocker** [comment]
Can not reproduce.

**Comment by MisterChocker** [comment]
@Benjozork Can not reproduce the input being shown after entry and switch page. Just pulled latest master.

**Comment by MisterChocker** [comment]
Update:
When entering lets say "ABC", then switching to another page (doesn't matter which one, just a different) then click clr to clear scratchpad, the "CLR" appears on the scratchpad and disappears when clicking clr again. 
Same for `.`, `+` and `-`.
The hidden content, "ABC" however becomes visible again after using any other except the listed keys above.

**Comment by MisterChocker** [comment]
Update:
Text also hides/gets invisible when clicking on the menu button for the same menu.
So no need to even change the page to trigger the event.

**Comment by MisterChocker** [comment]
However when using left/right on e.g. INIT PAGE, the content maintains visible.

**Comment by MisterChocker** [comment]
When using left/right keys on page that does not support this action or has no other menu to change to, an error message with onnextpage is not defined appears
![image](https://user-images.githubusercontent.com/1857322/99159703-490bba80-26df-11eb-95d3-3f0097a38670.png)

**Comment by MisterChocker** [comment]
Found the bad boy

**Comment by Kimbyeoungjang** [comment]
@Benjozork i retested on lastest master because @MisterChocker build hotfix but i think there is a still remain this bug.

**Comment by MisterChocker** [comment]
Which bug? the bug I found and fixed was the page switch removes input / displays an empty error message.

**Comment by Kimbyeoungjang** [comment]
> Which bug? the bug I found and fixed was the page switch removes input / displays an empty error message.

nvm. i watch github finish build master automatically and i downloaded lastest but there is no your hotfix. i re-test that and work well.

**Comment by MisterChocker** [comment]
LMAO, I fired up my flight sim to see what I missed xD Because the only thing I found got fixed.
