### ISSUE TITLE
[REQUEST] Fuel prediction doesnt work on last Master branch version.

### ISSUE THREAD

**Issue by javiiberia** [flybywiresim/a32nx#1918]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**

**References**

**Additional context**

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Rameyuk** [comment]
I find that clicking on the Fuel Prediction, populates the block that doesn't match the current FOB.

**Comment by MisterChocker** [comment]
This is intended behavior...

**Comment by Benjozork** [comment]
> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning
