### ISSUE TITLE
[BUG] Water reflections of scenery seems erroneous in cockpit view but OK with external view

### ISSUE THREAD

**Issue by JLD95** [flybywiresim/a32nx#1923]
**Mod Version**

built: 2020-11-10T15:19:38+00:00

**Describe the bug**

Water reflections of scenery seems erroneous in cockpit view but OK with external view

**To Reproduce**

1.  Difficult to reproduct this phenomenon: here at finale RWY30 of WAJJ airport
2.
3.

**Expected behavior**

Verify if modding can correct this phenomenon

**Actual behavior**

Reflections in cockpit view seems erroneous

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

In external view
![2020-11-14 (17)](https://user-images.githubusercontent.com/5894146/99153899-fc5abc00-26ab-11eb-9548-e5c178f8a497.png)

One second later, in cockpit view
![2020-11-14 (18)](https://user-images.githubusercontent.com/5894146/99153919-28763d00-26ac-11eb-90fe-43f555942e50.png)

**Comment by stevex77** [comment]
This is a vanilla game problem and has nothing to do with A32NX mod. It happens in all aircrafts, even on external views (as seen on the first screenshot on the right edge) - reflections disappear near screen borders or when obstructed by some object. It's probably some DX11 limitation, possibly a performance optimization.

Recommending wait for DX12 engine on which ASOBO is actually working.

**Comment by Benjozork** [comment]
This is inherent to how screen-space reflections work. Game feature request would be for ray-traced reflections.
