### ISSUE TITLE
Autobrake buttons 

### ISSUE THREAD

**Issue by Totti1964** [flybywiresim/a32nx#1924]
**Mod Version**

**Describe the bug**
 
autobrake buttons only work in master after pushing joystick button, not in dev

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by wpine215** [comment]
Master is the same as dev, as far as our naming conventions go. Also, you are not following the issue template. Please revise your post and tag me once it's fixed.
