### ISSUE TITLE
[BUG] Loss of flight plan and crash when changing time backwards

### ISSUE THREAD

**Issue by Fell** [flybywiresim/a32nx#1926]
**Mod Version** 

v0.4.1

**Describe the bug**

When being on a direct, and then changing time backwards (in my case about 4 hours), the flight plan disappears. Attempting to enter a new flight plan results in a crash of the simulator.

**To Reproduce**

1. Reach cruise on an IFR planned flight
2. Setup a direct to a future waypoint on the route (as often instructed by ATC)
3. Change the time backwards by about 4 hours
4. Observe that the flightplan has disappeared
5. Start a new flight plan by entering the FROM/TO information
6. Observe that the simulator crashes.

**Expected behavior**

The simulator should remain stable under all circumstances.

**Actual behavior**

The simulator crashes without an error message.

**References**

**Additional context**

I was flying on VATSIM, so vPilot was running. Except for liveries, there were no other mods installed. I was using the latest version of the simulator as of today. (I believe 1.10)

Was this working before/when did the issue start occurring?
It only happened once.

Is this a problem in the vanilla unmodded game?
I can't tell yet, I will try this out.

Discord username (if different from GitHub): Fell#4002

**Comment by MisterChocker** [comment]
Does this still occur on latest master or stable 0.5.1?

**Comment by MisterChocker** [comment]
Closing since no response from op.
