### ISSUE TITLE
[REQUEST] How to donate you team.

### ISSUE THREAD

**Issue by javiiberia** [flybywiresim/a32nx#1928]
**Is your feature request related to a problem? Please describe.**
Hey there , I am writting you here ,( sorry to post it here) , beacuse i dont find any other place to ask it .

I just want to give a bit of my money 30 Dollars for this incredible team. I think you guys deserve it.
My question is where can i donate you ?
My second question is if it is going to be a real study level aircraft , 
Thanks for everyting 

**Describe the feature you'd like to see implemented**

**References**

**Additional context**

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by stevex77** [comment]
Hey there! You can using this link https://opencollective.com/flybywire, there is the Sponsor button here - see top right portion of the page):

![SPONSOR](https://user-images.githubusercontent.com/51388935/99155333-3e3d2f80-26b7-11eb-8e72-92e02b735825.png)

The intention and motivation of flybywire is to make this aircraft as close to the reality as possible (as much study level as possible - as MSFS platform / SDK allows) :)

**Comment by javiiberia** [comment]
I just donate as i promise.

![image](https://user-images.githubusercontent.com/74369531/99156121-cbd04d80-26be-11eb-84c3-efacf7ee0e6d.png)



Keep up the hard work and i will donate more times , this development and wonderfull aircraft that you are creating worth more than the 30$ i just give you.

King regards.

**Comment by wpine215** [comment]
Thank you!

Closing this issue to keep the repo organized.
