### ISSUE TITLE
CTD Approach selected to KOMA ILS 23 

### ISSUE THREAD

**Issue by Captherky** [flybywiresim/a32nx#1929]
**Mod Version**
Master
built: 2020-11-12T19:07:16+00:00
ref: refs/heads/master
sha: 02edbe68f8b4e90cd85a908e32653e430a34056d
actor: wpine215
event_name: push

**Describe the bug**
Select APPR mode on ILS RW23 At KOMA. Result CTD Immediately.

**To Reproduce**

1. Select APPR mode on GS for ILS RE 23 KOMA
2. 2 seconds after appr selected CTD
3. LOC Blue identified on PFD

**Expected behavior**
GS Blue

**Actual behavior**
CTD!!!

**Additional context**
First time I used this latest dev mod

Was this working before/when did the issue start occurring?

YES Previous Dev mod OK

Is this a problem in the vanilla unmodded game?
NO

Thanks

**Comment by Benjozork** [comment]
Hello, can you update our development version to the latest ?

Also, how many times have you reproduced this ?

**Comment by MisterChocker** [comment]
closing since no response from OP
