### ISSUE TITLE
[BUG] Auto Brake setting in incorrect play in checklist

### ISSUE THREAD

**Issue by Figrol** [flybywiresim/a32nx#1930]
**Mod Version**
Master Version 4.1

**Describe the bug**
I am unsure if this is how the checklists are designed in real life or if there is a fault with the auto brake system but "Set the auto brake to max" checklist item is in the taxi checklist section however, if you make your selection and then brake the aircraft on the way to the runway the setting resets to blank. I feel this should probably be in the Takeoff checklist or lineup checklist as I have set it in the past and then forgotten about it before take off.

**To Reproduce**

1. Enter the aircraft anywhere in the world, open the checklist menu and navigate to the "Taxi Checklist".
2. Set the autobrake to max, taxi and use the brakes, the setting reverts to blank.

**Expected behavior**

Unsure

**Actual behavior**

Autobrake resets when using the brakes

**References**

**Additional context**

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment]
I believe this is fixed in current master since #1762.

**Comment by Benjozork** [comment]
Fixed in master.

By the way, "Master Version 4.1" is not a version. It's either master (unstable, dev) or 0.4.1 (stable)
