### ISSUE TITLE
[BUG] ELEC ECAM is not working. just show fixed value

### ISSUE THREAD

**Issue by Kimbyeoungjang** [flybywiresim/a32nx#1935]
**Mod Version**
 latest master(2020/11/15)

**Describe the bug**

as a title, lower ecam elec page just show fixed value

**To Reproduce**

1. start up aircraft
2. some elec behavior like disconnect gen 1, bat 1 etc..
3. lower ecam elec page is not showing correct value, just fixed value

**Expected behavior**

working normally

**Actual behavior**

show fixed value

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Hello,

This is known and fine, the ELEC ECAM page is only a placeholder for now.

**Comment by Kimbyeoungjang** [comment]
oh i see.
