### ISSUE TITLE
[BUG] find type error on FULE page on ECAM

### ISSUE THREAD

**Issue by Kimbyeoungjang** [flybywiresim/a32nx#1936]
**Mod Version**
 latest master

**Describe the bug**

![image](https://user-images.githubusercontent.com/23118756/99160708-4b950100-272d-11eb-82f4-40868f492cf6.png)
when i press -> on init page, MCDU showed to me NOT ALLOWED(it is normall when flying)

but when i press -> on FUEL PRED page, there is a type error 

**To Reproduce**

1. start up aircraft and takeoff
2. going to mcdu fuel pred page
3. press -> button

**Expected behavior**

not allowed i think?

**Actual behavior**

type error

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
I'm working on this

**Comment by Kimbyeoungjang** [comment]
> I'm working on this

i find some interesting point.
![image](https://user-images.githubusercontent.com/23118756/99160828-e510e280-272e-11eb-8cbd-5659af10275b.png)

if i press -> button on like RAD NAV page(there is no 2nd page), same type error appear
