### ISSUE TITLE
[BUG] ND Weather radar

### ISSUE THREAD

**Issue by PuL9** [flybywiresim/a32nx#1939]
**Mod Version**

{ "built": "2020-11-14T07:02:32+00:00", "ref": "refs/heads/master", "sha": "d34fd66220fbd970f5e22099fab913a9e339d112", "actor": "Benjozork", "event_name": "push" }

**Describe the bug**

Weather radar dissapears from ND when switching to Plan mode and back

**To Reproduce**

1. Make sure weather radar is visible https://i.imgur.com/9i43RBm.png
2. Switch to plan mode https://i.imgur.com/VgRRw71.png
3. Switch back to ARC mode (radar works on copilot ND) https://i.imgur.com/3D3Ydwp.jpeg

**Expected behavior**

Weather radar must be visible when switching back from Plan mode to ARC

**Actual behavior**

Weather radar is not visible when switching back from Plan mode to ARC

**References**

Screenshots above, in reproducing step

**Additional context**

There was an issue couple of days back when airplane on ND was not visible, switching to Plan and back fixed that (but then weather radar disappeared) looks like it doesn't happen anymore, but I haven't tested it much

**Was this working before/when did the issue start occurring?**
Not sure when it started

**Is this a problem in the vanilla unmodded game?**
No, unmodded A320 doesn't have that issue

Discord username (if different from GitHub): same

**Comment by asessa1976** [comment]
Hi, i also noted you have to switch on and then off the TERR ND button (cpt side) to view weather on ND.
The FO side doesn't have this problem

**Comment by ilyeshammadi** [comment]
@Benjozork this issue can be closed.
