### ISSUE TITLE
[BUG] MCDU PERF Does Not Take Wind Speed and Direction into Account when Calculating

### ISSUE THREAD

**Issue by TheoBearman** [flybywiresim/a32nx#1940]
**Mod Version**
0.4.1

**Describe the bug**
The MCDU PERF page does not take wind into account when calculating VAPP/VLS speeds. This is a particular issue when flying into a headwind on approach with auto-throttle engaged.

**To Reproduce**

1. Add headwind to a flying environment on approach.
2. Fly an ILS approach with auto-throttle engaged.
3. Observe that the calculated VAPP/VLS on the MCDU PERF page have not taken the headwind into account and thus that the auto-throttle will select an inappropriate speed.

**Expected behavior**
MCDU PERF page should use the weather data available to calculate VAPP/VLS speeds that take wind speed and wind direction into account.

**Actual behavior**
MCDU PERF calculates the VAPP/VLS based on the aircraft weight assuming no wind.

Was this working before/when did the issue start occurring? _Has never worked._

Is this a problem in the vanilla unmodded game? _Unknown._

Discord username (if different from GitHub): _theob_

**Comment by tareksabet** [comment]
It's been fixed in the latest master but not yet in the stable 0.4.1

**Comment by TheoBearman** [comment]
Can you confirm where? Iceman was in touch with my brother on the Discord only last night requesting it be raised as a bug.

**Comment by tareksabet** [comment]
> Can you confirm where? Iceman was in touch with my brother on the Discord only last night requesting it be raised as a bug.

@TheoBearman try to install the latest master version via the installer and I think it's called Dev version in the installer

**Comment by TheoBearman** [comment]
I was referring to which PR closed this issue?

**Comment by MisterChocker** [comment]
This one did #1295

**Comment by TheoBearman** [comment]
Thanks for the clarifcation. Happy to close here.
