### ISSUE TITLE
[REQUEST] Improved startup sound and sequence (LEAP)

### ISSUE THREAD

**Issue by GearUp-78** [flybywiresim/a32nx#1942]
**Is your feature request related to a problem? Please describe.**

Startup sequence well too short and not loud / bassy enough in comparison of real 320 neo leap startup sequence

**Describe the feature you'd like to see implemented**

new interior and exterior startup sounds trying to match real audio recordings given in reference section

**References**

interior leap startup sound: 
   https://www.youtube.com/watch?v=Mio0t3LSPi4
   https://www.youtube.com/watch?v=tuLZ84vGUbA&t=923s

exterior leap startup sound: 
   https://www.youtube.com/watch?v=Ulq4-SfOIlk
   https://www.youtube.com/watch?v=pDfmwRlfgHg&t=121s

**Additional context**

Note: on the following video, we clearly see why the starting sequence lasts longer than for older generation a320 engines: there is a cooling/ventilation phase before ignition : https://www.youtube.com/watch?v=4NAs7DJ42eM

**Comment by tareksabet** [comment]
@hotshotp look at if you can

**Comment by hotshotp** [comment]
Hey, I made the audio for the startup sounds. Currently the startup is indeed way too short and is being worked on. When the actual startup gets elongated, so will the sound. I also don't know what you mean by not bassy enough, the sound we use for engine start is very bassy.

**Comment by GearUp-78** [comment]
Hello Sir,
nice to meet you :-) 
First, congratulations for the sounds, and also for the actual startup sounds. They are wayyy better than those of the default A320, and in my opinion almost as excellent as those of BSS (for Toliss A319, FF A320...). A big big thank you for your work.

As we are all passionate people here, we are always trying to improve things, and to stick closer and closer to reality... It's endless :-) 

So my improvment request is a small detail regarding all the work that you, and the other contributors to the A32NX project, have already achieved.

You are already aware that the real LEAP startup sequence should last a bit longer because of the long "motoring/cooling" phase prior injecting fuel, and you said that it will be updated later. Thanks a lot in advance for that. 
Then, what I love with startup sounds, it's the moment where we can hear the fuel ignition. It's a moment where the bass level increases suddenly, and then the engine  spools up more quickly. On the LEAP, it's a bit special, The sound is even more bassy and even louder than "old gen" CFM 56, and the spooling phase takes a bit longer for the engine to reach ground idle. This is very hard to describe with words (specially for someone like me, not very used to speak/write english, sorry sir). That's the reason why I mentionned differents links (I am sure that you already knew these videos) where we can very clearly hear and identify the different phases of the startup sequence.

In my opinon, an improvement that could still eventually be done (very easy to say, but certainly not so easy to perform... I tried to tweak xplane startup sounds in the past... I gave up), would be to better identify the initial motoring phase (slow spool up... a bit bassy but not too much), and then the ignition moment (suddenly more bass, louder sound with the very particular sound of the LEAP at this precise moment - a massive resonance, inducing vibrations inside cockpit and cabin, as we can hear on the videos - until reaching the ground idle). I have never heard such an ignition phase sound on previous engines of the Airbus family. Beautiful and powerful sound. A sort of baby GE90... So in brief, the actual startup sounds could be a lot more punchy/bassy/louder/vibrating from the ignition phase, until the ground idle stabilization. (The initial motoring phase before ignition seems perfect, maybe a bit too quiet but not sure).
Just a suggestion based on the videos and my personal feeling. 

Once again, I really enjoy each engine startup and each flight with the A32NX. Congratulations again for your incredible work.
Do not forget to fly the A32NX from time to time, and not only code :-)

Bravo !
Regards,
S.

**Comment by Alex1337Cool** [comment]
Lol, just wanted to post the same video on the cooling process. Note that the cooling prosses is only run when there already was a flight on that day. (Refference the Comment section)

**Comment by hotshotp** [comment]
> Hello Sir,
> nice to meet you :-)
> First, congratulations for the sounds, and also for the actual startup sounds. They are wayyy better than those of the default A320, and in my opinion almost as excellent as those of BSS (for Toliss A319, FF A320...). A big big thank you for your work.
> 
> As we are all passionate people here, we are always trying to improve things, and to stick closer and closer to reality... It's endless :-)
> 
> So my improvment request is a small detail regarding all the work that you, and the other contributors to the A32NX project, have already achieved.
> 
> You are already aware that the real LEAP startup sequence should last a bit longer because of the long "motoring/cooling" phase prior injecting fuel, and you said that it will be updated later. Thanks a lot in advance for that.
> Then, what I love with startup sounds, it's the moment where we can hear the fuel ignition. It's a moment where the bass level increases suddenly, and then the engine spools up more quickly. On the LEAP, it's a bit special, The sound is even more bassy and even louder than "old gen" CFM 56, and the spooling phase takes a bit longer for the engine to reach ground idle. This is very hard to describe with words (specially for someone like me, not very used to speak/write english, sorry sir). That's the reason why I mentionned differents links (I am sure that you already knew these videos) where we can very clearly hear and identify the different phases of the startup sequence.
> 
> In my opinon, an improvement that could still eventually be done (very easy to say, but certainly not so easy to perform... I tried to tweak xplane startup sounds in the past... I gave up), would be to better identify the initial motoring phase (slow spool up... a bit bassy but not too much), and then the ignition moment (suddenly more bass, louder sound with the very particular sound of the LEAP at this precise moment - a massive resonance, inducing vibrations inside cockpit and cabin, as we can hear on the videos - until reaching the ground idle). I have never heard such an ignition phase sound on previous engines of the Airbus family. Beautiful and powerful sound. A sort of baby GE90... So in brief, the actual startup sounds could be a lot more punchy/bassy/louder/vibrating from the ignition phase, until the ground idle stabilization. (The initial motoring phase before ignition seems perfect, maybe a bit too quiet but not sure).
> Just a suggestion based on the videos and my personal feeling.
> 
> Once again, I really enjoy each engine startup and each flight with the A32NX. Congratulations again for your incredible work.
> Do not forget to fly the A32NX from time to time, and not only code :-)
> 
> Bravo !
> Regards,
> S.

Thank you for the super nice reply, I appreciate that very much! Yeah, I guess you are right, I will make the fuel flow sound more bassy and punchy. As for everything else, I guess we just have to wait until the changes are made :)

**Comment by polyefko** [comment]
I still love the Zibo 737-800 Xplane sounds. The engines are very rich and non tinny Creaking while taxing...Engines especially in all aspects..Startup  take off In flight REVERSE nice and loud and shut down the engines SLOWLY shut down over like a 15-20 second period as they wind down. Just my input

**Comment by hotshotp** [comment]
> I still love the Zibo 737-800 Xplane sounds. The engines are very rich and non tinny Creaking while taxing...Engines especially in all aspects..Startup take off In flight REVERSE nice and loud and shut down the engines SLOWLY shut down over like a 15-20 second period as they wind down. Just my input

Roger! I agree, audiobird did a really good job. Here is my input. The engines are still being tweaked, and still improving. The creaking while taxiing is recorded from a real airbus, keep in mind the a320 has different panels and instruments that make different sounds when taxiing. Engine startup and shutdown is being reworked as of now.

**Comment by polyefko** [comment]
Very nice of you to reply...and yes....keep the good work up

**Comment by hotshotp** [comment]
Hello again! My pull request with the better startup sounds has been created. In that PR you can very clearly hear the difference between motoring and fuel flow. The fuel flow is now much bassier and grittier and will most likely be very fun for you to listen to :)

**Comment by GearUp-78** [comment]
Hello again !
I've just made a short test flight this evening after work. The new sounds are awesome, In my opinion, they are very close to what we can hear on the videos for a LEAP. Congratulations, really. Fuel ignition is impressive, more bass + sort of resonance... A delight ! I can't wait to make my next flight.

Thank you again and maybe see you soon :-)
I'll keep the thread open until saturday, just in case someone would like to add some comments.
S.

**Comment by hotshotp** [comment]
> Hello again !
> I've just made a short test flight this evening after work. The new sounds are awesome, In my opinion, they are very close to what we can hear on the videos for a LEAP. Congratulations, really. Fuel ignition is impressive, more bass + sort of resonance... A delight ! I can't wait to make my next flight.
> 
> Thank you again and maybe see you soon :-)
> I'll keep the thread open until saturday, just in case someone would like to add some comments.
> S.

Great to hear! If you have any issues please contact me, I will be sure to take a look!
