### ISSUE TITLE
[REQUEST] MCDU - Implement AIRPORT button

### ISSUE THREAD

**Issue by krangerich** [flybywiresim/a32nx#1948]
**Is your feature request related to a problem? Please describe.**

Improve realism / convenience

**Describe the feature you'd like to see implemented**

The AIRPORT button on the MCDU should scroll the F-PLN page to 
a) the DEST airport (on line 4. line 5 will be the "end-of-flight-plan" marker or the first waypoint of the go-around route) on first press
b) to the ALTN airport (if implemented?) on the second press
c) to the ORIGIN airport on the third press (only when in PREFLIGHT phase)
...and then cycle again

**References**

FCOM:
![image](https://user-images.githubusercontent.com/7890659/99191939-52913300-2770-11eb-9756-fa0aff879ca1.png)

Thales New FM Pilot's Guide:
![image](https://user-images.githubusercontent.com/7890659/99192108-596c7580-2771-11eb-9266-49ab75afc309.png)

**Additional context**

Discord username (if different from GitHub):
n/a

**Comment by TheSledge-SLEJ** [comment]
I second this emotion. To some it may appear a finesse but if, like me, you like to check the flight plan by entering via the MCDU then the constant up arrow to get to the insertion point is annoying

**Comment by arseneyr** [comment]
The Honeywell FMS Pilot's Guide has conflicting information:

![image](https://user-images.githubusercontent.com/10376473/99763077-c86a0700-2aae-11eb-9c5a-cb32c1e563c7.png)

'airport pages' sounds like the lateral rev page for the airport so you can enter departures/arrivals?

**Comment by TheSledge-SLEJ** [comment]
This. IIRC the persistent DEST always stays at the bottom of the page but the AIRPORT btn cycles through the placement of DEP ARR and ALT details. The DEP details will be placed at the top so you are at the head of the fpl; the ARR and ALT details go just above the persistent DEST so that you also get the last STAR, APP or EN-ROUTE waypoints, and thereby the insertion point, at the end of the fpl.

**Comment by krangerich** [comment]
> The Honeywell FMS Pilot's Guide has conflicting information:
> 
> ![image](https://user-images.githubusercontent.com/10376473/99763077-c86a0700-2aae-11eb-9c5a-cb32c1e563c7.png)
> 
> 'airport pages' sounds like the lateral rev page for the airport so you can enter departures/arrivals?

I think thats a wording issue, since I've seen pictures (but don't find them now) where the F-PLN page with the airport at 4L or 1L  have been called "airport page". 
I could even be that there is a dedicated other page which behaves / looks 99% like the F-PLN page, but isn't one? The following passage contains some more information and indicates that ("...This logic also applies to the alternate destination and the origin, except that the origin is always displayed in field 1L..."):

![image](https://user-images.githubusercontent.com/7890659/99773563-eb2b0880-2b0c-11eb-861e-147a66ba8975.png)

The upper FCOM part is about a Honeywell FMS 2 and from 2017, so thats Honeywell, too.

Here is another FCOM from 2002:
(section 1.22.10, p.11)
![image](https://user-images.githubusercontent.com/7890659/99774904-b4ee8880-2b0e-11eb-8acc-2c39a8b21519.png)

Then I've seen videos from pilots where they showed the AIRPORT button as a convenience button to scroll to the destination airport, so thats a lot of evidence for the F-PLN scrolling for me.

**Comment by erso44** [comment]
investigating.
