### ISSUE TITLE
[BUG] CRZ FL changes when selecting altitude with FCU during CLIMB phase

### ISSUE THREAD

**Issue by krangerich** [flybywiresim/a32nx#1952]
**Mod Version**

master
{ "built": "2020-11-15T03:35:23+00:00", "ref": "refs/heads/master", "sha": "71806ad3f76a80f55019c0548bc08049a50d435b", "actor": "Benjozork", "event_name": "push" }

**Describe the bug**

When selecting a managed speed with the FCU (selected speed not tested) during CLIMB phase, the MCDU changes the cruise FL to this speed. This is not correct and often leads to a cruise FL of the first cleared FL (like FL080...).

Only when already in CRUISE phase (aircraft in soft alt mode), the cruise FL should be changed when selecting a higher managed altitude.

**To Reproduce**

1. Start a flight in IFR mode
2. Select some lower altitude (like 8000ft) using managed mode
3. CRZ FL (e.g. on the INIT A and the PROG page) changes to FL080

Could be flaky and happen just in some cases?

**Expected behavior**

CRZ FL should not change (only when changed manually in the appropriate fields on the INIT A or PROG page)

**Actual behavior**

see above

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
no

Discord username (if different from GitHub):
n/a

**Comment by MisterChocker** [comment]
![image](https://user-images.githubusercontent.com/1857322/98182460-1a832800-1f06-11eb-9771-5404469a1eed.png)

This is intended behavior.

**Comment by krangerich** [comment]
From your Honeywell Manual: "...when it is set to a HIGHER altitude". When you entered FL290 in INIT A and then select FL310, the cruise FL will of course change to FL310 (that's because it's economical to fly the exact FL entered for cruise phase. When flying in the cruise FL, the soft altitude mode will be active, allowing -+50ft deviation from target FL to avoid unnecessary throttling up/down).
But when you planned with FL290 and select FL080 using the FCU, its LOWER than FL290 and will not be inserted as permanent cruise FL. During climb, temporary altitude restrictions may apply and those would ruin your planned cruise FL. 

In FCOM it's more clear: 
![image](https://user-images.githubusercontent.com/7890659/99312321-2522b300-285e-11eb-8014-3b31530a95c0.png)

**Comment by MisterChocker** [comment]
Yes that applies during cruise. During climb, it's the "fcu selected altitude or highest climb altitude constraint in the primary flight plan".

**Comment by MisterChocker** [comment]
Yes that applies during cruise. During climb, it's the "fcu selected altitude or highest climb altitude constraint in the primary flight plan". Your's may ore may not be for cruise phase.

**Comment by krangerich** [comment]
Both passages are from the PROG page and valid for all phases. I've not seen a passage where it says you could change the final cruise FL during the climb phase using the FCU. 
Wouldn't make any sense, since the FCU is for short term tactical operations and the cruise FL in the MCDU is a long term strategic planning item.

Are we referring to the same thing? I'm not talking about the current FL during climb, but about the cruise FL.

**Comment by MisterChocker** [comment]
Oh yeah, the cruise fl shouldn't be modified, but the FL displayed on the prog should be right?

**Comment by St54Kevin** [comment]
Maybe you can also implement with this that you can just enter a small value like "3" into CRZ FL field and it automatically changes to the current FL you are flying. That only works if you are BELOW your CRZ FL. We often use that to get the plane into Cruise mode if ATC doesn't let us higher

**Comment by MisterChocker** [comment]
@St54Kevin I have added this functionality. Is this only possible during cruise and climb or always?

**Comment by St54Kevin** [comment]
> @St54Kevin I have added this functionality. Is this only possible during cruise and climb or always?

Not sure about climb

**Comment by krangerich** [comment]
> Oh yeah, the cruise fl shouldn't be modified by the fcu (if lower then the cruise fl set), but the FL displayed on the prog should be right?

1L on PROG page should always show the cruise FL for the flight, as entered in the INIT A page. Maybe St54Kevin could clarify that? 

I think I understand now, what you was referring to earlier; the first paragraph after the dash. I'll try to explain how I understand the snippet:

At first the lower part:
"- Dashes are displayed when the aircraft transitions to DESCENT or APPROACH. In this case, a cruise altitude is entered in 1L when it is at or below the current aircraft altitude. ...."
During descent or approach, the cruise phase is over and gone. Thats why there are dashes. As far es I understand, dashes here only appear during / after a descent / approach phase and stay there. 

Now the upper part:
"- If dashes are displayed when the FMS transitions from PREFLIGHT or DONE to TAKEOFF or CLB, this field changes to the FCU selected altitude, ..."
I think, this passage only applies when you had a descent / approach phase, THEN land and takeoff again? In this case there could be a transition from PREFLIGHT/DONE to TAKEOFF /CLB with dashes in 1L.
During a normal start from cold & dark, proper initialization and so on, I'd expect the cruise FL on the PROG page during TAKEOFF / CLB, not dashes. Is this correct?

**Comment by MisterChocker** [comment]
Correct.
