### ISSUE TITLE
[BUG] Flight phase randomly switches to DES during cruise

### ISSUE THREAD

**Issue by krangerich** [flybywiresim/a32nx#1953]
**Mod Version**

master 
{ "built": "2020-11-15T03:35:23+00:00", "ref": "refs/heads/master", "sha": "71806ad3f76a80f55019c0548bc08049a50d435b", "actor": "Benjozork", "event_name": "push" }

**Describe the bug**

During a IFR flight from EDDM to LSGG, somewhere at the end of the climb phase or during the first part of the cruise phase, the MCDU switched to DES (descend) phase.

**To Reproduce**

1. Start a flight from EDDM - LSGG
2. Take off
3. Climb first to 8000ft, select new FL180, select new FL250

**Expected behavior**

Flight phase should stay in cruise until T/D or descending manually

**Actual behavior**

s.above

**References**

n/a

**Additional context**

Might be related to #1952?

Was this working before/when did the issue start occurring?
n/a

Is this a problem in the vanilla unmodded game?
don't know

Discord username (if different from GitHub):
n/a

**Comment by beheh** [comment]
For PR reference, here's how the rules should be:

![grafik](https://user-images.githubusercontent.com/929769/99225757-de46a600-27e8-11eb-9ecb-d20fca189e5a.png)

**Comment by MisterChocker** [comment]
Please test with #1998 when it's ready to test. Problem may be solved if related to #1952

**Comment by MisterChocker** [comment]
Please retest with latest master

**Comment by MisterChocker** [comment]
Closing since no response from op.
