### ISSUE TITLE
[BUG] Distance in VOR 2 on ND overlaps the letters NM

### ISSUE THREAD

**Issue by jcabanascachi** [flybywiresim/a32nx#1954]
**Mod Version**
Current Dev 

{ "built": "2020-11-15T17:16:03+00:00", "ref": "refs/heads/master", "sha": "a07c515e185cd8e7dfdba410e0a32b2a2d962b7d", "actor": "Benjozork", "event_name": "push" }

**Describe the bug**

The distance shown in ND refering to VOR 2 is on top the letters "NM"

**To Reproduce**

1.Set a VOR 2 Frequency in RAD NAV page
2.When VOR 2 is in range, the distance shown in ND is on top the NM letters

**Expected behavior**

I think the distance should not overlap de NM letters

**Actual behavior**

Distance overlaps the NM letters

**References**

![NM Bug](https://user-images.githubusercontent.com/74508913/99194942-56a95a80-2748-11eb-8ed8-f5d1d7e6c4ae.png)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
Not sure

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by theomessin** [comment]
> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning

Feel free to open a new issue **provided you follow the given instructions**.
