### ISSUE TITLE
[REQUEST] Add Company Flight routes to MCDU System

### ISSUE THREAD

**Issue by H3nr1ks-C0d3** [flybywiresim/a32nx#1956]
**Is your feature request related to a problem? Please describe.**

It's quite Time-Consuming to go back to the main Menu because MSFS won't accept Simbrief files while in a session. How cool would it be to be able to store these files inside a folder and after taxiing to the Gate

**Describe the feature you'd like to see implemented**

After putting in the ICAO codes, System shouldnt say none but actually provide you with flightplans that you have (maybe) pasted in to the folder

**References**

**Additional context**

Discord username (if different from GitHub):
Henrik#6852

**Comment by lousybyte** [comment]
Duplicate #1656.
