### ISSUE TITLE
[REQUEST] Add lights below Engine main switches

### ISSUE THREAD

**Issue by H3nr1ks-C0d3** [flybywiresim/a32nx#1957]
**Is your feature request related to a problem? Please describe.**

There are two black boxes located below the Engine switches which should light up when theres an Engine Fire.

**Describe the feature you'd like to see implemented**

- light up when there is an Engine Fire or when the Annunciator Lights Switch is turned on

**References**

http://a320dp.com/A320_DP/engines/sys-5.7.4.html
![engine-fire-light](https://user-images.githubusercontent.com/62308300/99196448-b88bb380-278c-11eb-96a8-3436f8e7802d.jpg)

EDIT: Here is a perfect description for when which light should iluminate. The Website really does a perfect job: http://a320dp.com/A320_DP/engines/sys-5.5.1.html

**Additional context**

I don't really know if any of the implemented button lights are programmed to display "Fault" at any time in flight(door button for example) but it would be cool to see these switches actually turn on and not just look redundant in the entire aircraft design.

Discord username (if different from GitHub):
Henrik#6852

**Comment by tracernz** [comment]
Done a while ago.
