### ISSUE TITLE
[BUG] SEC1 button causes the "wing dip to the left" bug?

### ISSUE THREAD

**Issue by Toneking77** [flybywiresim/a32nx#1958]
**Mod Version**
Stable ver 0.4.1

**Describe the bug**
Concerns the wing dip to the left on short final.  See details below.

**To Reproduce**
Widely known bug... I just wanted to see if this thread would be beneficial to your team:
https://www.reddit.com/r/MicrosoftFlightSim/comments/juosac/simple_fix_for_a320_wing_dip_bug_plane_rolls_left/

**Expected behavior**
No wing dip on short final.

**Actual behavior**
Wing dip to the left on short final from a stabilized approach.

**References**
https://www.reddit.com/r/MicrosoftFlightSim/comments/juosac/simple_fix_for_a320_wing_dip_bug_plane_rolls_left/

**Additional context**
I thought that this may be something your team could look into.  

This is the first time I've submitted an issue on GitHub.  I apologize if I've messed this up!  

I'm **extremely** thankful for the time and energy your team has put into improving this base plane for us.  Truly Amazing!!   

Was this working before/when did the issue start occurring?
Long standing problem.

Is this a problem in the vanilla unmodded game?
Absolutely!

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Thanks, please discuss further in #974 - although this is already known.
