### ISSUE TITLE
ADF distance not shown in ND

### ISSUE THREAD

**Issue by frankkopp** [flybywiresim/a32nx#1961]
**Mod Version**
master

master
{ "built": "2020-11-15T20:41:23+00:00", "ref": "refs/heads/master", "sha": "91fd44b4ae3d44a326af75ee38d59966baaef659", "actor": "wpine215", "event_name": "push" }

**Describe the bug**
ND does not show ADF distance for NDB

**To Reproduce**

1. Start a flight in air to EDDM - active pause
(found the issue with full flight as well)
2. put in RAD NAV: ADF1: 338  (MNW)
3. turn on ADF1 in EFIS

**Expected behavior**
Distance to NDB should be shown in bottom left corner of ND
(or bottom right for ADF2)

**Actual behavior**
no distance is shown "--- NM" - see screenshot

**References**
![image](https://user-images.githubusercontent.com/16833201/99198567-cbf14b80-2799-11eb-86cf-36ab39aeaaa8.png)
![image](https://user-images.githubusercontent.com/16833201/99198482-25a54600-2799-11eb-9ea0-553d34228cfe.png)

**Additional context**
VOR DME works fine

Was this working before/when did the issue start occurring?
unknown

Is this a problem in the vanilla unmodded game?
not testet

Discord username (if different from GitHub): Cdr_Maverick

**Comment by St54Kevin** [comment]
ADFs dont have distance

**Comment by frankkopp** [comment]
Ok - makes sense. Will close.

But is it correct in showing "--- NM"?

**Comment by frankkopp** [comment]
![image](https://user-images.githubusercontent.com/16833201/99198793-26d77280-279b-11eb-83c4-6be8d9bd00dd.png)

**Comment by St54Kevin** [comment]
No thats not correct but Im sure it will improve

**Comment by frankkopp** [comment]
Not a bug - my mistake :)
