### ISSUE TITLE
[BUG] "SELF TEST IN PROGESS" Text unreadable on upper and lower ECAM

### ISSUE THREAD

**Issue by Lamao2244** [flybywiresim/a32nx#1964]
**Mod Version**

{ "built": "2020-11-15T22:36:44+00:00", "ref": "refs/heads/master", "sha": "58ecd2b5844d5f4263f0c86b87c5e3652819df82", "actor": "wpine215", "event_name": "push" }

**Describe the bug**
 Text is tiny

**To Reproduce**
 Just boot up the plane in Dark and cold and turn up the displays

1.
2.
3.

**Expected behavior**
 Text to be bigger

**Actual behavior**
 Tiny text

**References**

**Additional context**
 
![bug](https://user-images.githubusercontent.com/72637344/99234535-9dbe4b00-282f-11eb-8368-7ffad1e28b31.png)

Was this working before/when did the issue start occurring? Latest master

Is this a problem in the vanilla unmodded game? No

Discord username (if different from GitHub):LaMao

**Comment by ntlgr** [comment]
The same problem appears in the STS page, the word "NORMAL" is unreadable.

**Comment by Watsi01** [comment]
Confirmed.

**Comment by hotshotp** [comment]
same issue here
