### ISSUE TITLE
New downloader v0.7 hangs or causes BSOD

### ISSUE THREAD

**Issue by hairagon** [flybywiresim/a32nx#1966]
**Mod Version**
v0.7

**Describe the bug**
BSOD after running software

**To Reproduce**
1 Reopen downloader
2 Click 'Stable' button

**Expected behavior**
App would download and install a32NX as previous versions.

**Actual behavior**
New download and install went OK.  When i ran the update the STABLE version of the mod it hung for a while then BSOD, The only event in the event log around that time being critical was "Failed with 0x57 retrieving AppModel Runtime status for package Windows."
Rebooted fron 'C&D' and application hung but did not BSOD. 2 instances in processes section of task Manager.
All drivers / OS up to date - Windows 10 2004

**References**

N/A

**Additional context**

N/A
Was this working before/when did the issue start occurring?
Previous versions were OK

Is this a problem in the vanilla unmodded game?
NO

Discord username (if different from GitHub):

**Comment by Externoak** [comment]
@hairagon Could you please create the issue in https://github.com/Externoak/A32NX-installer/issues since that is the installer repo.
When creating the issue can you please explain your steps to follow.

**Comment by Benjozork** [comment]
Wrong repo
