### ISSUE TITLE
[BUG] ILS approach gets stuck

### ISSUE THREAD

**Issue by duckietm** [flybywiresim/a32nx#1967]
When going on ILS approach (any runway) the speed will not go below 140 and the LOC/APPR drifts to the right at alt 500 when then disconnecting the AP all is froze until touchdown (next to the runway).
i have tested this now 10 times and all the same results, when loading stable the problem is gone.

Build : https://github.com/flybywiresim/a32nx/commit/58ecd2b5844d5f4263f0c86b87c5e3652819df82
No custom mods etc. only FS2020 and A32nx

**Comment by MjrIncident** [comment]
I have been experiencing the same issue on every ILS approach.

**Comment by duckietm** [comment]
Any update on this problem ?

**Comment by duckietm** [comment]
![100](https://user-images.githubusercontent.com/1917443/100224134-b78d1b80-2f1c-11eb-99bb-eb8a4344fd83.png)
![101](https://user-images.githubusercontent.com/1917443/100224159-bfe55680-2f1c-11eb-9288-92b12b87ea27.png)
![102](https://user-images.githubusercontent.com/1917443/100224181-c7a4fb00-2f1c-11eb-9261-884f01b83237.png)

**Comment by MisterChocker** [comment]
Is this bug still happening on latest master?

**Comment by MisterChocker** [comment]
Closing since no response from op.
