### ISSUE TITLE
Flap speed dont work during takeoff

### ISSUE THREAD

**Issue by Steven0785** [flybywiresim/a32nx#1968]
**Mod Version**

Current master

**Describe the bug**
Aircraft runs in overspeed dringend takeoff with extrndet flaps

**To Reproduce**

1.configure plane
2.takeoff with flaps set
3.speed increase in clb Mode over the flap speed

**Expected behavior**

Aircraft throttle down to hold flap speeds

**Actual behavior**

Aircraft accelerate in overspeed and with no flaps below 10000 when reach 250kts patch will be up to 62000ft/min

**References**

**Additional context**

Was this working before/when did the issue start occurring?
With the latest master

Is this a problem in the vanilla unmodded game?
I dont test it

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Jochandecoster** [comment]
Can confirm this with the latest master, took off with flaps 1, left them extended, plane oversped a lot

**Comment by beheh** [comment]
This should have been fixed yesterday by #1944. What commit hashes are you running?

**Comment by Jochandecoster** [comment]
it went well past 250kt

**Comment by Steven0785** [comment]
Yes! Flap speed for f1 and f2 dont work and he accellerate so aggressive that when i pass 250kt the pitch up moment is unreal! Climb 5000+ ft/min

**Comment by MisterChocker** [comment]
> **Expected behavior**
> 
> Aircraft throttle down to hold flap speeds

no LMAO, the ATHR does not hold F or S speed on takeoff...

**Comment by Jochandecoster** [comment]
It isn't correct behaviour to go past 250kt under FL100, I guess?

**Comment by ChruutvoLuzi** [comment]
> It isn't correct behaviour to go past 250kt under FL100, I guess?
> that's the main issue here. It overspeeds and climbs way too agressively to compensate

What is your GW? If the aircraft is too light it will climb like a rocket ship.

**Comment by MisterChocker** [comment]
This is only because the AP is trash
![image](https://user-images.githubusercontent.com/1857322/99262633-7f038880-281e-11eb-9b70-cb69dacc723f.png)

**Comment by MisterChocker** [comment]
This is also correct behavior that the ATHR does not reduce thrust.

**Comment by MisterChocker** [comment]
Aircraft will then continue climb till FL100 with 250kt
![image](https://user-images.githubusercontent.com/1857322/99262846-b96d2580-281e-11eb-9d02-21e6ef0e1134.png)

**Comment by MisterChocker** [comment]
> It isn't correct behaviour to go past 250kt under FL100, I guess?
> that's the main issue here. It overspeeds and climbs way too agressively to compensate

yes actually it is, athr is not reducing thrust in THR CLB mode.

**Comment by Jochandecoster** [comment]
So you have to set the speed yourself now? Don't use managed speed under FL100?

**Comment by MisterChocker** [comment]
And for the overspend, the real FBW would increase pitch to prevent this.

**Comment by MisterChocker** [comment]
@Jochandecoster if you want to prevent this from happening (bad AP behavior) hand fly the acceleration and pitch up, then engage AP.

**Comment by Steven0785** [comment]
ok sounds understandable! thank you

**Comment by MisterChocker** [comment]
@Steven0785 np, you're welcome!

**Comment by Benjozork** [comment]
Closing
