### ISSUE TITLE
[BUG] External power can also be used when the power generator is not on the aircraft

### ISSUE THREAD

**Issue by kferrano** [flybywiresim/a32nx#1969]
**Mod Version**

master 2020-11-14T07:02:32+00:00

**Describe the bug**

External power can also be used when the power generator is not on the aircraft

**To Reproduce**

1 .Stand at any airport and look at the overhead panel
2. Land at any airport, drive to the gate and look at the overhead panel
3.

**Expected behavior**

That you can only switch on the external power when the generator has been set up and connected.

**Actual behavior**

External power can also be used when the power generator is not on the aircraft

**References**

https://www.youtube.com/watch?v=vfT-vaDDqQA

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Watsi01** [comment]
Thank god that's the case. In other words, I'm glad this bug exists. Cause my lazy power truck crew (MSFS) disconnects after a few minutes without even asking me. So please don't fix that unless Asobo has fixed their lazy ground crew.

**Comment by vlbreda** [comment]
Modern airports have power outlets in the ground near the gates, it's not always a generator truck.
