### ISSUE TITLE
[REQUEST] Make engine throttles properly separated

### ISSUE THREAD

**Issue by airfirefighter** [flybywiresim/a32nx#1970]
built: 2020-11-13T18:49:49+00:00
ref: refs/heads/master
sha: 72e7b0c830e17d7984b3aca2dd852cce8ca7662c
actor: Benjozork
event_name: push

**Describe the bug**
the left thrust lever is the  one that  control  the thrust of both engines and the right one remain inoperative without giving any thrust to the engine.This occurs when you engage the autothrust on.

**To Reproduce**
1start a flight on an airports runway 
2engage autothrust on.
3.TOGA with only left thrust lever  (both engine increase power) 
4TOGA with only right thrust lever (dont increase power).         

**Actual behavior**
every time u engage the autothrust the right thrust  lever  become inoperative and the left thrust lever controls the thrust of engine number 1 and engine number 2 
Expected behavior
left thrust lever must control thrust in engine number 1  ,   right thrust lever must control thrust in engine number 2
**References**

![Microsoft Flight Simulator 16_11_2020 17_12_06](https://user-images.githubusercontent.com/71919620/99269387-fc36f980-282e-11eb-80c6-1665414de2d4.png)
![Microsoft Flight Simulator 16_11_2020 17_12_19](https://user-images.githubusercontent.com/71919620/99269411-022cda80-282f-11eb-8167-aaebd6f11af9.png)

**Additional context**

i dont know
Is this a problem in the vanilla unmodded game?
i dont know

**Comment by Snapmatics** [comment]
At the moment, throttles are not seperated. You can not move one but two at the same time if your engine 2 fails.

**Comment by Benjozork** [comment]
Can someone rewrite this as a feature request because this is hard to understand

**Comment by airfirefighter** [comment]
> Can someone rewrite this as a feature request because this is hard to understand

i edit the post  to become more clearly this time ...i hope...im sorry im not an expert in English-speaking..im trying

**Comment by Benjozork** [comment]
No worries, I'll take care of it :)

**Comment by YuTookMyJob** [comment]
It would be great to be able to independently control the engines. Especially for users of the Thrustmaster TCA throttle quadrant.

**Comment by Mega-Touk** [comment]
If you need to try on this specific device (Thrustmaster TCA quadrant) I'm available on discord Touk#6787

**Comment by Taz5150** [comment]
Just tested both engine throttles individually (up to TOGA) and they behave as expected.
