### ISSUE TITLE
[BUG] Passing route waypoint activates pre-selected altitude

### ISSUE THREAD

**Issue by Poiuz367** [flybywiresim/a32nx#1978]
**Mod Version**
<"built": "2020-11-16T19:21:04+00:00"->

**Describe the bug**
Passing route waypoint with autopilot activates a pre-selected alitude.

Steps to reproduce the behavior
1. Autopilot on - select any altitude and activate it; for Example 22'000ft
2. pre-select diffrent altitude; for Example 17'000ft
3. pass a route waypoint
4. Plane begins desent or climb to preselected altitude; --> 17'000ft

**Expected behavior**
Passing a waypoint should not influence the selected altitude

**Actual behavior**
Passing a route waypoint sets the preselected altitude to active

**Additional context**
may be related to #1590 https://github.com/flybywiresim/a32nx/issues/1590

Was this working before/when did the issue start occurring?
no

Is this a problem in the vanilla unmodded game?
yes

Discord username (if different from GitHub):
Poiuz

**Comment by tracernz** [comment]
Is this still an issue?

**Comment by Poiuz367** [comment]
The issue is fixed! Thank you all
