### ISSUE TITLE
[BUG] Pre-selected heading disappears after ~ sec 8

### ISSUE THREAD

**Issue by Poiuz367** [flybywiresim/a32nx#1979]
**Mod Version**
<"built": "2020-11-16T19:21:04+00:00">

**Describe the bug**
With nav mode on (managed heading on) any pre-selected heading disappears after around 8 sec

**To Reproduce**
1. Autopilot on - Nav mode on (managed heading on)
2. Preselect different heading
3. The preselected heading dissapears after around 8 sec

**Expected behavior**
Pre-selected heading should stay, i think.
Like pre-selected speed when managed speed is on, or pre-selected altitude when different altitude is active.

**Actual behavior**
it disappears

Was this working before/when did the issue start occurring?
no

Is this a problem in the vanilla unmodded game?
yes

Discord: Poiuz

**Comment by Slotherby** [comment]
It depends on the phase of flight.

"The flight crew turns the HDG/TRK knob. The value in the windows first synchronizes with the current HGD/TRK, then displays the manual selection.  It remains displayed for 10 s or 45 s depending upon the FCU standard, then vanishes if the flight crew does not pull the knob (except in HDG preset)" [A320 FCOM DSC-22_30-60]

HDG/TRK preset is a function for takeoff and go-round.

**Comment by Poiuz367** [comment]
thank you for the explanation. then it is a feature, so i close this issue.
