### ISSUE TITLE
Landing Gear UNLK light color

### ISSUE THREAD

**Issue by ArthurHetem** [flybywiresim/a32nx#198]
The landing gear unlock light is gray
![UNLK_GRAY](https://user-images.githubusercontent.com/7545272/91589627-6e82f680-e930-11ea-853b-9cde9531d020.png)

The expected is to be red when operating the gear and gray when idle
![image](https://user-images.githubusercontent.com/7545272/91589702-95d9c380-e930-11ea-92b7-835f7e203d88.png)

**Comment by 2hwk** [comment]
Reference Videos:

https://youtu.be/cv41hm4JEB8?t=214

https://youtu.be/aAvQXMbiodw?t=135
