### ISSUE TITLE
[BUG] Loss of "ALT" when disconnecting autopilot

### ISSUE THREAD

**Issue by sef3613** [flybywiresim/a32nx#1981]
**Mod Version**

Latest stable

**Describe the bug**

Plane was in SPEED, ALT, HEADING with the autopilot on. Disconnected the autopilot and ALT disappeared. 

**To Reproduce**

1. Have plane in "ALT" mode with autopilot on.
2. Disconnect autopilot.
3.

**Expected behavior**

ALT mode stays, as seen in the FSLabs video.

**Actual behavior**

ALT mode mysteriously disappears, as if disconnecting the autopilot somehow interferes with pitch modes.

**References**

https://www.youtube.com/watch?v=bftYjZ4IJ8A&feature=youtu.be

https://www.youtube.com/watch?v=4NxKcYGOBTo

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment]
Autopilot disconnect gives invalid input to FMAs.
Will be fixed by wip AP.
