### ISSUE TITLE
[BUG] Plane not loading in right

### ISSUE THREAD

**Issue by lawfulrocky** [flybywiresim/a32nx#1983]
**Mod Version**
lastest dev verison
lastest msfs 2020 verison
[build_info.zip](https://github.com/flybywiresim/a32nx/files/5550681/build_info.zip)

**Describe the bug**
Plane is loading up as the wrong plane

**To Reproduce**
loading up in game

1.i load up using a flight plan
2.i delete and reinstall the mod
3.did that a few times

**Expected behavior**
suppose to be the a320nx

**Actual behavior**
show as another plane floating
**References**
![Screenshot (25)](https://user-images.githubusercontent.com/25673245/99328553-50030c00-284a-11eb-9631-df27ecaa3a60.png)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
no not at all

Discord username (if different from GitHub): lawfulrocky#4343

**Comment by MisterChocker** [comment]
Is this still a happening? Are you having other mods installed?

**Comment by NathanInnes** [comment]
@lawfulrocky

**Comment by MisterChocker** [comment]
Closing since no response from op.
