### ISSUE TITLE
MCDU Init - Page 2 "Not Available

### ISSUE THREAD

**Issue by ViciousEagle** [flybywiresim/a32nx#1984]
**Mod Version**

Using the latest master branch as of 11/16/20.  The latest stable build doesn't have this problem. 

**Describe the bug**

When using the left and right arrows to go to the second page on the init screen, you're given the "not available" message on the bottom.   

**To Reproduce**

1.Go to init screen
2.Use the left or right arrows. 
3.

**Expected behavior**

Should go to the second init page.  This worked on previous versions.  

**Actual behavior**

I get the "Not available" message and it doesn't switch screens. 

**References**

none

**Additional context**

none

Was this working before/when did the issue start occurring?
This was working on the last stable release and other master releases, but I don't know which one it stopped working on. 

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):

**Comment by wpine215** [comment]
The init B page isn't supposed to show up once the engines are started.
