### ISSUE TITLE
[BUG] Animate tiller 

### ISSUE THREAD

**Issue by yorgosGK** [flybywiresim/a32nx#1986]
**Describe the feature you'd like to see implemented**

Have a setting in the MCDU to activate the tiller and let those with Spad or any other program give an axis assignment to the nose wheel (would be killer if assignable inside the MCDU).

Animating the tiller _on its pivot_ should be easy and then its just playing with tightening up rudder controls to simulate the tighter feel of a nose wheel. Also, killing the rudder and pedals from animating if tiller mode is activated. Its how Aerosoft did theres. 

**Additional context**

**Comment by Benjozork** [comment]
> Animating the tiller on its pivot should be easy

Not possible until we can edit the 3D model, sorry.

> its just playing with tightening up rudder controls to simulate the tighter feel of a nose wheel

MSFS does not really allow that on-the-fly AFAIK.

**Comment by Benjozork** [comment]
Tiller is also assignable in MSFS already, via the Controls page.

**Comment by hotshotp** [comment]
You are able to assign this in the msfs settings and the tiller is animated, it moves when you do that input
