### ISSUE TITLE
[BUG] Not able to insert trip wind after MCDU did its fuel calculation

### ISSUE THREAD

**Issue by Watsi01** [flybywiresim/a32nx#1988]
**Mod Version**
"built": "2020-11-17T00:49:32+00:00", "ref": "refs/heads/master", "sha": "7993adf777d91172b966f8b86db2d79623a95018", "actor": "wpine215", "event_name": "push"

**Describe the bug**
After inserting INIT A and B, the MCDU takes a while to do its fuel calculations. Before that is done, you can enter a trip wind in the INIT B page. But when you do it after the calculation is done, it doesn't take any inputs anymore

**To Reproduce**

1. Start cold&dark
2. Power up the aircraft (EXT or APU)
3. Fill out all INIT parameters on page A and B (CI, FL, blockfuel and ZFW/ZFWG) 
4. Don't insert any trip wind.
5. Wait after the MCDU did its fuel calculation
6. Try to insert trip wind on INIT B 

**Expected behavior**
You should also be able to insert trip wind after MCDU has done the calculation

**Actual behavior**
see above

**Additional context**

Was this working before/when did the issue start occurring?
I think this was working before the latest major overhaul of the MCDU (about 2 weeks ago).

**Comment by Lucky38i** [comment]
just wait. Entering a new trip wind means calculations are done again to take account for this.

**Comment by Watsi01** [comment]
@Lucky38i It just doesn't take any input after the calculation is done. I don't think it is calculating again, since the wind isn't put in. But I can be wrong.

**Comment by Lucky38i** [comment]
> @Lucky38i It just doesn't take any input after the calculation is done. I don't think it is calculating again, since the wind isn't put in. But I can be wrong.

Well the logic isn't similiar to when you enter block fuel which shows the block fuel entered then does calculations. When you enter total wind after calculations are finish, the value you entered won't actually show until the calculations are finished. Which is why you should either wait or do something else and check back later. I'm gonna make a PR soon where I'll halve the calcuation time since some people are saying it's too long

**Comment by Watsi01** [comment]
Ok. I'll check that.

**Comment by Watsi01** [comment]
Closed, cause I was wrong (wroooong!!!)
