### ISSUE TITLE
Holding at waypoint not working

### ISSUE THREAD

**Issue by Roboplayer999** [flybywiresim/a32nx#1989]
**Mod Version**
Master V: 2020-11-17T00:49:32+00:00

When selecting a waypoint in the FP (Flight Plan) the aircraft simply ignores it

**To Reproduce**
1.Cold and Dark start
2.Normal startup
3.Enter FP
4.Take off
5.Go to the FP page
6.Select waypoint
7.Press Hold and Enter

**Expected behaviour**
It should draw the Holding pattern on the Nav display and follow until you press Exit on the FP waypoint

**Actual behaviour**

**References**
The aircraft simply proceeds with the next waypoint

**Comment by lousybyte** [comment]
Duplicate #1443.

**Comment by Roboplayer999** [comment]
Sorry
