### ISSUE TITLE
[BUG] Can't insert ZFW/ZFWCG

### ISSUE THREAD

**Issue by justwanttoreportabug** [flybywiresim/a32nx#1990]
**Mod Version**

dev version
built: 2020-11-12T19:07:16+00:00
ref: refs/heads/master
sha: 02edbe68f8b4e90cd85a908e32653e430a34056d
actor: wpine215
event_name: push

**Describe the bug**

Trying to enter ZFW/ZFWCG into the MCDU's 2nd init page returns FORMAT ERROR.
Same bug as https://github.com/flybywiresim/a32nx/issues/1439 which has been solved previously

**To Reproduce**

1. Follow the checklist until you get to the MCDU init B page where you need to insert ZFW/CG
2. Type in any value for ZFW/ZFWCG such as 110.3/24.2
3. Press LSK1-R to enter
4. Format error comes up

**Expected behavior**

ZFW/ZFWCG values are entered

**Actual behavior**

Format error comes up

**References**

Before trying to enter https://i.imgur.com/zFNgRl1.jpg
After https://i.imgur.com/tW3yMoY.jpg

**Additional context**

Was this working before/when did the issue start occurring?
It has been fixed before judging by the comment or the prior report of this bug.
Is this a problem in the vanilla unmodded game?
Not AFAIK

Discord username (if different from GitHub):

**Comment by beheh** [comment]
I believe that field only accepts KGS at this time, not LBS.

**Comment by Benjozork** [comment]
Hello, your dev version is pretty outdated. Please try with a new build and report back.

**Comment by kferrano** [comment]
I have to agree with justwanttoreportabug, the entry doesn't work for me either and I use the version 2020-11-17T00:49:32+00:00

**Comment by justwanttoreportabug** [comment]
> 
> 
> Hello, your dev version is pretty outdated. Please try with a new build and report back.

That's strange, the installer is saying i am up to date, maybe it's the build_info.txt that I copied the version numbers from? Opening up build_info.json I get this: { "built": "2020-11-17T00:49:32+00:00", "ref": "refs/heads/master", "sha": "7993adf777d91172b966f8b86db2d79623a95018", "actor": "wpine215", "event_name": "push" }

Also in response to beheh's comment, that is very possible, I am using pounds in the sim (the default setting), but it was working before.

**Comment by justwanttoreportabug** [comment]
I'm calling this solved. Either enter ZFW in kilograms manually, or press LSK1-R when the ZFW field is empty and it gets filled automatically.
