### ISSUE TITLE
[BUG] MCDU: Old entry reproduced after page change upon 1st key stroke

### ISSUE THREAD

**Issue by lve0200** [flybywiresim/a32nx#1992]
**Mod Version**
 

Master as of 15.11 via downloader

**Describe the bug**

After changing a MCDU page, the old perviously entered value reappears upon 1st keystroke on new page

**To Reproduce**

1. Go to PERF page and enter "5000" for TRANSITION.
2. Go to another page and enter 1; you'll see 50001
3.

**Expected behavior**

Old value from previous page should not reappear

**Actual behavior**

**References**

**Additional context**
 No

Was this working before/when did the issue start occurring?
Was working b4, but cannot determine, when it changed
Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Hello, can you try with the newest development version ? It's updated multiple times per day.

**Comment by lve0200** [comment]
OK, toss it, its gone in the latest dev version.
Thanks

**Comment by Benjozork** [comment]
Closing as resolved in master.
