### ISSUE TITLE
[BUG]New ATIS sources lead to inconsistency

### ISSUE THREAD

**Issue by lve0200** [flybywiresim/a32nx#1993]
**Mod Version**

 ALL

**Describe the bug**

The new ATIS source provides ATIS information, which is in most cases different from the internally used weather system by MSFS. During landing the internal MSFS weather prevails and the values retrieved from the selected ATIS source are inconsistent. These entered into the MCDU APPR PERF page will result in wrong behavior of the plane

**To Reproduce**

1. Get ATIS info from one source
2. Check weather (wind) during touch down
3.

**Expected behavior**

Provided ATIS information should be consistent when landing

**Actual behavior**

Provided ATIS Information is not the same as weather during touch down.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Not applicable
Is this a problem in the vanilla unmodded game?
Not applicable

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
> Get ATIS info from one source

You need to specify which source you selected.

**Comment by lve0200** [comment]
IVAO

**Comment by joniatus** [comment]
You'd be better off getting weather info from METAR using msfs as source.  ATIS is based off real-world data so it will surely vary from msfs weather.  Use atis to get active runways and other info.  Also don't expect metar to always be exact, weather is dynamic.

**Comment by lve0200** [comment]
>  Also don't expect metar to always be exact, weather is dynamic.
Yes, but I would expect that whatever weather you've got through whomever at any time, would be backward propagated into the sim, or making MSFS fool proof that it can provide its own weather decently in ATIS and be sort of consistent during landing.

**Comment by joniatus** [comment]
as I said, I propose you get weather from metar using msfs as a source.  Inaccurate weather would be a game bug

**Comment by lukecologne** [comment]
It's currently not possible to get weather from MSFS, at least not that we know of.

**Comment by lve0200** [comment]
There's no METAR in the MCDU Options

**Comment by joniatus** [comment]
yes there is.  I guess it's metoblue not directly from sim so in theory it should be accurate but you know, asobo

**Comment by Benjozork** [comment]
> > Also don't expect metar to always be exact, weather is dynamic.
> 
> Yes, but I would expect that whatever weather you've got through whomever at any time, would be backward propagated into the sim, or making MSFS fool proof that it can provide its own weather decently in ATIS and be sort of consistent during landing. If I fly, and I get a weather info form the tower, that's what it is! Since MSFS in many cases does not provide "real" weather early enough in the APP for entering it into the MCDU, what do you propose?

This is currently impossible with the present SDK.

METAR source is configurable in A32NX OPTIONS in MCDU MENU. Includes meteoblue, which is what MSFS uses. Closing as no real bug or feature request here.

**Comment by lve0200** [comment]
I'm not really very happy that you close it, because I believe that my principle point stays on, that under the current circumstances you'll never know, what weather you actually going to find, down on the RWY. Its not a FBW fault, off course, and its not a specific AB fault, as well, but I thought you could at least correct it for the AB?! or keep it open until the SDK would allow it.

**Comment by Benjozork** [comment]
Changing the weather provider of MSFS to be more realistic is out of the scope of this project. You should bring up this issue on the Asobo forums.

**Comment by lve0200** [comment]
Sorry, to come back on the issue,
but I have no METAR,
![image](https://user-images.githubusercontent.com/47894777/99435299-39bf8380-2910-11eb-921a-43f792aa3112.png)
 nor meteoblue.

**Comment by Watsi01** [comment]
This is the ATIS page. Go back. There should be a METAR page.

**Comment by Watsi01** [comment]
![metar](https://user-images.githubusercontent.com/72334392/99439555-9e311180-2915-11eb-9f69-7894c9fbc3d1.png)

**Comment by lve0200** [comment]
Sorry, I thought you were talking about an ATIS provider called METAR. I disagree! In my communication with towers for TO and Landing, the reference is ATIS "... with (ATIS) information x (Alfa-Zulu)" not METAR.  I grant you that's an ASOBO fault and that the current SDK does not provide any means 4u changing it, but if you make changes in this domain, you should at least put some caveats around it, that the ATIS received through these channels will most likely not be, what the ACFT will find on the ground, as things are now!

**Comment by lve0200** [comment]
Mofreover, in a real world plane in flight, the only resource I have is ATIS via VHF

**Comment by Watsi01** [comment]
No you don't. You also have METAR informations. You get it exactly this way.

**Comment by Benjozork** [comment]
> Moreover, in a real world plane in flight, the only resource I have is ATIS via VHF

This system is modeled after the capacities of the A320 in real life. You can absolutely obtain ATIS/METAR/TAF via AOC in the MCDU.

**Comment by lve0200** [comment]
May be, but the tower expects ATIS, so you expect the pilot to translate METAR to ATIS ?

**Comment by Watsi01** [comment]
I give up.

**Comment by lve0200** [comment]
so do I, bu t I am flying and talking to ATC almost every 2nd week!

**Comment by Benjozork** [comment]
I highly doubt you fly ever second week if you have difficulty understanding what the difference between ATIS and a METAR is.

Will lock this as arguments are not to take place on GitHub. You can join our Discord to discuss this.
