### ISSUE TITLE
[REQUEST] Implement Ground speed Mini

### ISSUE THREAD

**Issue by Alex1337Cool** [flybywiresim/a32nx#1994]
**Is your feature request related to a problem? Please describe.**

_

**Describe the feature you'd like to see implemented**

Ground speed Mini is a feature that (on final approach) compares the head wind and the wind entered in the PERF page and adds the differance in head wind to the approach speed to keep the aircraft out of a low speed situation if the head wind should suddenly change. (For better explaination watch the Video below)

**References**

Here is a great video from 320 Sim Pilot explaining the feature https://youtu.be/7QwY0Nytyds

**Additional context**

And I just want to thank you guys for the exccelent work you have done to that plane. I really love that mod :)

Discord username (if different from GitHub): Alex_123_Cool#4633

**Comment by Steven0785** [comment]
This is a awesome idea

**Comment by Watsi01** [comment]
I'm not sure, but I think wind is already part of the calculation (not the inserted one, but the actual wind). @MisterChocker ?

**Comment by MisterChocker** [comment]
Yes, but not entirely sure how good this actually is. Also the code can't differ between steady and gusts.
Actually need to test this behavior within #1580, because I did some changes.
In the current master, it will always be vref + 5kts.
