### ISSUE TITLE
[BUG] Autobrake button input not working

### ISSUE THREAD

**Issue by jjg0000075** [flybywiresim/a32nx#1997]
**1944**
Master

**Describe the bug**
When I assign one of the tca airbus sidestick buttons to the autobrake either in lo or medium setting it does not work. When I press the input button assigned to max autobrake it works. The problem only persists to lo and medium autobrake.

**To Reproduce**
1. Assign a key to lo and another to med autobrake
2.press the key to activate
3.nothing happens
4. Assign key to max autobrake
5. It works for the max autobrake

**Expected behavior**
Should be obvious

**Actual behavior**
Already stated.

**Extra notes**
It used to work normal before the version where you could use brakes and it would not disarm max autobraking while taxing. Maybe the code messed around with the code around inputs for med and lo autobrake. 

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Cronch** [comment]
Hi guys,
I noticed the same thing today.
I tested it on the default/vanilla version of the aircraft on the simulator and it works perfectly there, but is not working on this mod.

I hope this helps.

**Comment by Sandelsium** [comment]
Still the same issue with 0.5.2. CFBW version, key bind to LO and MED autobrake do not work, only MAX. This affects the Thrustmaster TCA A320 Quadrant Add-On obviously as well.

**Comment by pilotsteve88** [comment]
Can I also just add that as well as the Autobrake switch not working for LO, MED & HI on the TCA Quadrant ADD-ON, the LANDING GEAR lever doesn't work either, whether the lever on the hardware is in the up or down position there is no change in the flightdeck. It does work on the 'Vanilla/default' version of the A320.

**Comment by ErikNL80** [comment]
I have received my throttle add-on today, so if you need help testing please let me know. I can confirm autobrake MAX/Disarm is working, LO and MED are not working.

**Comment by pilotsteve88** [comment]
> I have received my throttle add-on today, so if you need help testing please let me know. I can confirm autobrake MAX/Disarm is working, LO and MED are not working (latest DEV).

Does the landing gear lever work for you? Also the MAX autobrake works on mine but disarm/LO/MED doesn't

**Comment by wxmnrpg** [comment]
I just received my quadrant add-on today. 
Autobrake MAX also works. No luck for LO, MED, and disarm.
Other buttons are working fine (e.g., landing gear lever, parking brake).

Note: I am using the v0.5.4 CFBW version.

**Comment by Garfield381981** [comment]
I have also the addon avail. But no idea how can help ?
