### ISSUE TITLE
[BUG][CDU] Duplicate Names page also shows with only one waypoint in results

### ISSUE THREAD

**Issue by St54Kevin** [flybywiresim/a32nx#2001]
**Mod Version**

master 18th Nov 20

**Describe the bug**

I am calling the mcdu.getOrSelectWaypointByIdent function in my RADNAV PR #1960 to tune navaids by identifier. But the page also opens when only one waypoint is in the results list.

**Page:**
html_ui\Pages\VCockpit\Instruments\Airliners\A320_Neo\CDU\A320_Neo_CDU_SelectWptPage.js

**To Reproduce**

1. Use my PR or use any other method to call that duplicate names page
2. Tune a VOR by its identifier or input a unique waypoint/navaid
3. If its the only one in the world, Duplicate Names page shows nevertheless

**Expected behavior**

With only one waypoint in the result, the function should give that back without opening the page

**Actual behavior**

page always opens

**References**

![image](https://user-images.githubusercontent.com/448627/99543717-c5d6b700-29b3-11eb-83ad-5c36379e9e45.png)
![image](https://user-images.githubusercontent.com/448627/99543758-d38c3c80-29b3-11eb-9dc8-e62c734957e8.png)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub): St54Kevin#3583

**Comment by lousybyte** [comment]
There are 2 `getOrSelectWaypointByIdent()` defined, one of which checks for single result and the other doesn't.

**Comment by MisterChocker** [comment]
I was about to suggest checking the lenght of the list, and automatically returning if its 1.

**Comment by St54Kevin** [comment]
> There are 2 `getOrSelectWaypointByIdent()` defined, one of which checks for single result and the other doesn't.

Uuuh okay. Have to check that

**Comment by beheh** [comment]
> There are 2 getOrSelectWaypointByIdent() defined, one of which checks for single result and the other doesn't.

You mean there is one location where this has not been fixed? Or are you saying this is intentional? Because I'm not sure there is ever a situation where the DUPLICATE NAMES page makes sense if there's only one waypoint.

**Comment by lousybyte** [comment]
No idea if it was intentional or not, the top one in the inheritance hierarchy doesn't have the check.

**Comment by St54Kevin** [comment]
> There are 2 `getOrSelectWaypointByIdent()` defined, one of which checks for single result and the other doesn't.

I´ve not found the other function you mean

**Comment by lousybyte** [comment]
`A32NX\html_ui\Pages\VCockpit\Instruments\Airliners\A320_Neo\FMC\A32NX_FMCMainDisplay.js`
`A32NX\html_ui\Pages\VCockpit\Instruments\Airliners\A320_Neo\CDU\A320_Neo_CDU_MainDisplay.js`

**Comment by St54Kevin** [comment]
Resolved by creating my own function with a check
