### ISSUE TITLE
[REQUEST] Radio Panel - Possible to speed up / accelerate radio tuning?

### ISSUE THREAD

**Issue by zzyzxuk** [flybywiresim/a32nx#2002]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**
In a VATSIM environment, it can take a long time to change radio frequencies using the tuner knobs.  Is there a way to make it scroll through the frequencies faster, or ideally, could you have it start scrolling through frequencies slowly, but then accelerate the longer you hold the mouse button down?

**References**

**Additional context**

Discord username (if different from GitHub):  zzyzxuk

**Comment by ElSrJuez** [comment]
I also noticed this, it is really slow to tune frequencies using the VC knobs.

**Comment by bdpd1** [comment]
Could make an option for 25 vs 8.33 kHz jumps depending on whether flying in Europe vs North America, for example.

**Comment by kokkatepraanot** [comment]
I hope its sorted ASAP! Its such a hassle
