### ISSUE TITLE
[BUG] Aileron rocking at cruise

### ISSUE THREAD

**Issue by nhvtmedic** [flybywiresim/a32nx#2005]
**Mod Version**
 0.4.1

**Describe the bug**

At cruise on autopilot the airplane rolls subtly back and forth. You can see the ailerons moving up and down fairly rapidly.

**To Reproduce**

Climb to cruise on autopilot. For me it starts rocking during the climb or at cruise and continues until I start descent.

**Expected behavior**

Smooth flight

**Actual behavior**

See above

**References**

**Additional context**

Was this working before/when did the issue start occurring?
I downloaded yesterday and it has happened on all four flights I've done

Is this a problem in the vanilla unmodded game?
Yes

Discord username (if different from GitHub): nhvtmedic

**Comment by Benjozork** [comment]
This is a game bug.

**Comment by nhvtmedic** [comment]
Interesting I haven't experienced it with other aircraft

**Comment by MisterChocker** [comment]
Wondering what they actually did, this is from the latest update.
![image](https://user-images.githubusercontent.com/1857322/99587025-cc335600-29e8-11eb-9195-f71b88104be6.png)

**Comment by Benjozork** [comment]
> Interesting I haven't experienced it with other aircraft

The autopilot is shared between all planes and it has bugs with the A320.

**Comment by justwanttoreportabug** [comment]
Had the same bug, switching to AP 2 fixed it

**Comment by Gamma36** [comment]
There appears to be a slight instability in the Asobo flight model. The AP amplifies this instability and lacks critical damping - switching AP off for few seconds allows the plane to settle, then turn AP back on. 

This bug and workaround are widely discussed on the MSFS forum.

**Comment by asustryme** [comment]
Try changing the rollPID 2.5,... to 0.5,... or 0.2,... in ai.cfg located in the mod folder. (I think its fixed for me)

**Comment by Knallhartmuth** [comment]
> There appears to be a slight instability in the Asobo flight model. The AP amplifies this instability and lacks critical damping - switching AP off for few seconds allows the plane to settle, then turn AP back on.

Well, but even without the AP the A320 starts rocking wildly...
