### ISSUE TITLE
[BUG] altitude constraints "At or below" not correctly managed by the AP

### ISSUE THREAD

**Issue by PatriceCesson** [flybywiresim/a32nx#2007]
)
**Mod Version**
Master

{ "built": "2020-11-18T18:36:51+00:00", "ref": "refs/heads/master", "sha": "2f9200767ccf8e008aa33df02e52021e4010ed01", "actor": "Benjozork", "event_name": "push" }. 
In fact I saw it with the dev version just before this one.

**Describe the bug**

I follow a flight plan at level 150
The next waypoint has a constraint on altitude: AT or Below FL190 (constraint extracted from the navigation database)
In this situation, the A320 will climb to FL190 instead of keeping the altitude of FL150
This waypoint being near an approach phase, the approach becomes problematic.

**To Reproduce**

1. I created a flight plan between LFRN and LFMN via Little Nav Map and loaded it in the sim and the bus. The flight level is FL150.
2. Before LFMN arrival, there are some waypoinbt with constraints "At or below alt" (ABDIL (At or Below 19000), AMFOU (At or Below 16000))
3. Execute the FP and see that the plane climbs before ABDIL (to reach level FL190) instead of keeping the level of FL150

**Expected behavior**

Flying at level FL150, the plane must keep FL150 and not climb to FL190 when the next wp has an alt cst of "at or below FL190"

**Actual behavior**

Flying at level FL150, the plane climbs to level FL190 when the next wp has an alt cst of "at or below FL190"

**References**

**Additional context**

Nothing special. The error is simple to reproduce.

Was this working before/when did the issue start occurring?
Do not know. I do not think so.

Is this a problem in the vanilla unmodded game?
Do not know.

Discord username (if different from GitHub):
PatriceCesson

**Comment by DaBeLG** [comment]
expl use the tebra1G star to EGKK with the ILS 26L approach via TIMBRA

the airbus stays to long on FL140 only the ABTUM waypoint is FL140 rest is -FL140 AP stays at FL140
