### ISSUE TITLE
Missing Ticks On Horizon Line

### ISSUE THREAD

**Issue by Al-Roker** [flybywiresim/a32nx#201]
Missing the small white ticks present on the horizon line in the PFD that are
 used to indicate a turn.

![nBu0s](https://user-images.githubusercontent.com/70357384/91606511-cd983980-e937-11ea-8b0a-66f9653286b6.gif)

**Comment by joseph-tobin** [comment]
I found where this is defined
Packages\Official\Steam\asobo-vcockpits-instruments-airliners\html_ui\Pages\VCockpit\Instruments\Airliners\Shared\PFD\AttitudeIndicator.js

Line 101-107
`            let separator = document.createElementNS(Avionics.SVG.NS, "rect");
            separator.setAttribute("fill", "#e0e0e0");
            separator.setAttribute("x", "-1500");
            separator.setAttribute("y", "-3");
            separator.setAttribute("width", "3000");
            separator.setAttribute("height", "6");
            this.bottomPart.appendChild(separator);
`

**Comment by Benjozork** [comment]
@joseph-tobin, that file is not in the a320neo files so it would have to be duplicated and have NX use the new one instead. if you overwrite the original file itself in a new package, that will probably change for all airliners. just a heads up.

**Comment by 1Revenger1** [comment]
I can work on this
