### ISSUE TITLE
Route creation failed when multiple possible locations for a waypoint

### ISSUE THREAD

**Issue by George-da-cat** [flybywiresim/a32nx#2015]
Latest developer version.

I was trying to create the Flight plan KLAS TRALR9.DVC HBU MCK IOW SAMPL.VCTRZ2 KDTW with a takeoff from runway 26R at KLAS.

Everything worked well until trying to insert the waypoint IOW, which is the Iowa City VOR. Instead of bringing up the prompt to insert the waypoint, the CDU screen went blank. None of the other waypoints caused this issue.

If I left IOW out of the route, and used DSM (Des Moines) VOR instead, everything worked fine.

I was using Navigraph cycle 2012, Rev 1

**Comment by Benjozork** [comment]
Doesn't respect template.
