### ISSUE TITLE
[REQUEST] Add support to bind throttle detents

### ISSUE THREAD

**Issue by imMatt** [flybywiresim/a32nx#2022]
**Is your feature request related to a problem? Please describe.**
I would like to be able to bind throttle detent positions to a specific button so that i can use my throttle quadrant properly.

**Describe the feature you'd like to see implemented**

Add the ability in controls to bind a key to

- [ ] set TOGA thrust
- [ ] set Flex thrust
- [ ] set Climb thrust

**References**

N/A? Relatively straight forward concept

**Additional context**

Implementation is mostly related to supporting the Thrustmaster TCA quadrant, which isn't supported well by FS2020 in its current state.

Discord username (if different from GitHub): mallen44

**Comment by Benjozork** [comment]
This is a feature that should be requested in MSFS
