### ISSUE TITLE
[BUG] Aircraft regains altitude at nose up before touchdown

### ISSUE THREAD

**Issue by Nyxtorm** [flybywiresim/a32nx#2027]
**Mod Version**

{ "built": "2020-11-19T14:59:45+00:00", "ref": "refs/heads/master", "sha": "5e57e8dd9fbcf3cbbefd119606df2576da85bd7e", "actor": "Benjozork", "event_name": "push" }

**Describe the bug**

I won't use very technical words because I'm not a pilot at all. During an approach, just before touchdown, as soon as I raise the nose of the plane a little bit to put the rear landing gear before the front, the plane goes up instead of continuing to descend the last feet.

**To Reproduce**

1. Doing an ILS approach (but I don't think this is related to the type of approach)
2. Approach at a speed of about 132 kts in a normal landing configuration
3. Disable the AP before the minimums
4. Just before touching, raise your nose a little

**Expected behavior**

With Flight Factor's A320 Ultimate, I don't see the same behavior, the plane continues to descend smoothly.

**Actual behavior**

The plane regains altitude despite the low speed and the approach.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Sorry, I don't know.

Is this a problem in the vanilla unmodded game?
I can't say because I haven't tested.

Discord username (if different from GitHub):

**Comment by Steven0785** [comment]
Same behavior here! Vls+5 @ 30ft idle, pitch roundabout 2 an @ 5ft pitch up to 5 an aircraft begins to climb

**Comment by patrickferrariuk** [comment]
I have same issue, just before touchdown, regardless if autopilot is engaged for a CAT 3 Autoland or a manual landing, the nose of the plane pitches up suddenly. If I try to recover and pitch down again for a landing the plane becomes very unstable and uncontrollable (pitch axis).

**Comment by vlbreda** [comment]
Experienced the same thing after downloading the latest dev version last week.

**Comment by floufille** [comment]
I've a similar issue with build : 

{ "built": "2020-11-16T19:52:09+00:00", "ref": "refs/heads/master", "sha": "bfadb1fb621d2a4ad2c3581d9acc361553960127", "actor": "Benjozork", "event_name": "push" }

**Comment by MisterChocker** [comment]
Yes this is an issue since #1295. We are working on this.

**Comment by ahaos** [comment]
It seems to me that this is the problem of all aircraft in MSFS 2020, and not just this.

**Comment by dickbig2** [comment]
I would say the ground effect is way too strong...

**Comment by ahaos** [comment]
Probably this is still an Asobo problem

**Comment by dickbig2** [comment]
https://www.youtube.com/watch?v=MPyHz3KP1uk&t=211s ...

**Comment by elcareflen** [comment]
> Probably this is still an Asobo problem

No, watch this:
Bug - Yesterday
2020/11/23
https://youtu.be/UIQjLn_TKBA
————————
Old version, a couple of weeks ago
Here it works fine
https://youtu.be/Nk6oieH8oEQ
————————
Today, without mod
Here it works fine
https://youtu.be/EXAPLzChBQ8

**Comment by elcareflen** [comment]
> > Probably this is still an Asobo problem
> 
> No, see this:
> Bug - Yesterday
> 2020/11/23
> https://youtu.be/UIQjLn_TKBA
> ————————
> Old version, a couple of weeks ago
> Here it works fine
> https://youtu.be/Nk6oieH8oEQ
> ————————
> Today, without mod
> Here it works fine
> https://youtu.be/EXAPLzChBQ8

**Comment by ahaos** [comment]
I would say that the aircraft without mod is also inclined to this.

**Comment by MisterChocker** [comment]
Yes this is a common problem which is being addressed in our wip flight model. No ETA on this, it will be ready when it's ready.
