### ISSUE TITLE
[REQUEST] Behavior APPR in PERF in FMGC 

### ISSUE THREAD

**Issue by FGrabi** [flybywiresim/a32nx#2031]
**Is your feature request related to a problem? Please describe.**
NO

**Describe the feature you'd like to see implemented**
Change the behavoir in FMGC -> PERF -> APP as described under the following link ("ENTER DEST DATA message appears in amber on the scratchpad when within 180 NM of the destination and data is not entered" and for the QNH "Beyond 180 NM of the destination, brackets display. Within 180 NM, amber boxes appear."):

**References**
(http://a320dp.com/A320_DP/nav-flight-management/sys-14.5.40.html)

**Additional context**
It#s a "nice 2have" feature

AND THANKS to all of you for this excellent work!

Discord username (if different from GitHub):

**Comment by lukecologne** [comment]
Will be added in #2009
