### ISSUE TITLE
[BUG] Heading Jumping when crossing 0 degree

### ISSUE THREAD

**Issue by cellotako** [flybywiresim/a32nx#2032]
**Mod Version**

built: 2020-11-12T02:54:20+00:00
ref: refs/heads/master
sha: 421fc9e8c7426db8b69270ff55975a2a039176b1
actor: Benjozork
event_name: push

**Describe the bug**

Heading on PFD is jumping when I cross 0 degree (but not every time)

**To Reproduce**

(1.join right downwind of RJOA RW10)
2.when at base leg, PFD hading sometimes jumping
3.

**Expected behavior**

smoothly going

**Actual behavior**

jumping

**References**

https://youtu.be/xRalxEtV7wc
https://youtu.be/19OFMytiK_4

**Additional context**

Was this working before/when did the issue start occurring?
 not sure but maybe yes
Is this a problem in the vanilla unmodded game? 
yes

Discord username (if different from GitHub):

**Comment by MrMinimal** [comment]
Thank you, I experienced it once an thought I was going crazy! We were flying with your controls when it happened.

Looked like an interpolation bug as the compas smoothly winded from 359° ts

**Comment by MrMinimal** [comment]
Managed to reproduce the bug reliably:

On the ground, spin the aircraft clockwise for 720 degrees. North has to be passed at least twice for it to occur.
The second time it passes from 359 degrees to 1 degrees, it spins counterclockwise. The spin rate seems to pick up with every subseqent spin.

I'm looking at the code right now!
