### ISSUE TITLE
[BUG] Brake temperature always falls to 0 degree celsius

### ISSUE THREAD

**Issue by highperformancedevelopments** [flybywiresim/a32nx#2033]
**Mod Version**
current master

**Describe the bug**
While spawning c&d brake temperature always starts at 0 degree celsius no matter what outside temperature is set in the simulator. After the brakes heat up by using, temperature falls again to 0 instead of the outside temperature.

**To Reproduce**
1. Spwan c&d on airport of your choice
2. Look at ECAM WHEEL-Page and monitor brake temperature
3. Use brakes and monitor increasing temperature
4. Monitor cooldown on WHEEL-Page

**Expected behavior**
Temperature should start at outside temperature when spawn.
Outside temperature should be reached after cooldown.

**Actual behavior**
Temperature always starts and falls to 0 degrees.

**References**

![grafik](https://user-images.githubusercontent.com/25608553/99814583-74f8c700-2b49-11eb-9329-5959df307d4d.png)

Was this working before/when did the issue start occurring?
-

Is this a problem in the vanilla unmodded game?
?

Discord username (if different from GitHub):
Tim#0335

**Comment by MrMinimal** [comment]
I'm on it!

**Comment by Benjozork** [comment]
Keep in mind a negative temperature is always displayed as 0.
