### ISSUE TITLE
[REQUEST] Unreal sound cokpit

### ISSUE THREAD

**Issue by mikecbr** [flybywiresim/a32nx#2035]
**Is your feature request related to a problem? 
Is not a real problem but it is not real as i gets.

**Describe the feature you'd like to see implemented**
While you are flying in the cokcpit specially in cruise phase the sound of the engines should not hear at all specially in the neo.
I think is so reallistic while you are rolling for taking off , or while the engines are starting up , but in cruise , specially in cockpit you cant hear the engines at all. What you really hear is the wind from outside because of the speed and the packs etc , but not the engines.
Even in a perspective of a passenger , if you are sitting next to the engines in cruise you cant hear almost the engines.

**References**

https://www.youtube.com/watch?v=qyaqX1dHnxg&t=325s    MIN : 2.20

**Additional context**

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by hotshotp** [comment]
A camera always picks up that wind noise more than engines. We already made a very loud wind sound and it's a fine balance between engine and wind sound. I'll see what I can do, maybe I'll make engines quieter the faster you go

**Comment by mikecbr** [comment]
Thank you so much , I mean all the sounds are incredible , but the only thing that just dont seems real is what i just have said , I just want this aircraft to be as real as it gets and you team are making it .Thank you so much for your fast reply and have a nice weekend.
Kind regards.

**Comment by GearUp-78** [comment]
Hello all,

> A camera always picks up that wind noise more than engines.

Absolutely correct. I fly very often, and my attemps to record sound are always corrupted by the wind noise. We can almost only hear the wind noise during cruise, with our smartphone mics, they are not sensitive enough to catch all the frequencies.  In reality in the plane, we can still hear the engines, during cruise phase too, especially extrem bass and extrem trebles. We can also feel the engine frequencies (bass) and vibrations passing through our body, this is very enjoyable :-) .Sadly, in our simulator, we cannot reproduce that, so it already lowers the immersion. I think we have to compensate with a bit of extra sound.
Please do not lower the engine volume too much in cruise, we still need to hear something.
Link to the same video sent for the startup sound, but a bit further you have climb and cruise phase.  The mic seems a bit better here, so we can still hear the bassy  "roarr" during cruise in the passenger seat.
https://youtu.be/tuLZ84vGUbA?t=844

 
Just to share my personal experience.

I wish you very good flights :-)
S.

**Comment by hotshotp** [comment]
> Hello all,
> 
> > A camera always picks up that wind noise more than engines.
> 
> Absolutely correct. I fly very often, and my attemps to record sound are always corrupted by the wind noise. We can almost only hear the wind noise during cruise, with our smartphone mics, they are not sensitive enough to catch all the frequencies. In reality in the plane, we can still hear the engines, during cruise phase too, especially extrem bass and extrem trebles. We can also feel the engine frequencies (bass) and vibrations passing through our body, this is very enjoyable :-) .Sadly, in our simulator, we cannot reproduce that, so it already lowers the immersion. I think we have to compensate with a bit of extra sound.
> Please do not lower the engine volume too much in cruise, we still need to hear something.
> Link to the same video sent for the startup sound, but a bit further you have climb and cruise phase. The mic seems a bit better here, so we can still hear the bassy "roarr" during cruise in the passenger seat.
> https://youtu.be/tuLZ84vGUbA?t=844
> 
> Just to share my personal experience.
> 
> I wish you very good flights :-)
> S.

Hey! I see you again replying on sound, your feedback is always top quality and we would love to have you on our discord server! It is a messaging app that is incredibly convenient and we get all of the info and feedback there! Please join us! https://discord.gg/JyFQHVJx

**Comment by Benjozork** [comment]
Hello, please join our Discord to discuss realism of features.
