### ISSUE TITLE
[REQUEST] Could/will we ever have all the GPWS warnings, T-CAS warnings and just other general warning sounds? 

### ISSUE THREAD

**Issue by X-PetRussian-X** [flybywiresim/a32nx#2037]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**
I'd love to see T-CAS, more GPWS sounds and warning sounds that are not in the aircraft so far. 
(Sorry for little detail)

**References**
https://www.youtube.com/watch?v=fbfVGIBcD8c&t=11s

**Additional context**
None.

**Comment by hotshotp** [comment]
Absolutely! We are working on all of that!

**Comment by X-PetRussian-X** [comment]
> Absolutely! We are working on all of that!

Ah, thank you for replying that fast! I cant wait to hear thoes AMAZING GPWS sounds.

**Comment by Benjozork** [comment]
Please use our Discord for general questions about the project.

**Comment by X-PetRussian-X** [comment]
Noth

> Please use our Discord for general questions about the project.

Dont see any channel about asking questions.

**Comment by Benjozork** [comment]
#general will do :)

**Comment by X-PetRussian-X** [comment]
> #general will do :)

Aight, thanks.
