### ISSUE TITLE
Descent seems way too slow

### ISSUE THREAD

**Issue by holz72** [flybywiresim/a32nx#2040]
So the descent speed seems way too slow especially in lower altitudes. I can hardly lose any altitude or Speed during stars and transitions and have to use my speedbrakes way too often. 
The issue happens since you guys updated the engine to be able to taxi in idle. My Impression is the engines produce too much thrust in idle and therefore hinder a good rate of descent.

**Comment by Benjozork** [comment]
Hello, please respect the issue template and in this case avoid opening issues before confirming an actual problem. Our discord is available to everyone so that you can chat with devs and real A320 pilots about this.
