### ISSUE TITLE
[BUG] THR RED / ACC ALT misbehavior

### ISSUE THREAD

**Issue by mikecbr** [flybywiresim/a32nx#2041]
**Mod Version**
Master branch and latest stable release

**Describe the bug**
In the performance page , in the section of take off ( THR RED / ACC ) if you put 3500/5000 when the aircraft pass the 3500FT alttitude will say LVR CLB , that is correct but once you reduce the throttle lever, the airplane , instead of say (THR CLB) it says SPEED , untill the airplane reach the desiree ACC alttitude 5000F. Then it changes to (THR CLB).

**To Reproduce**

![image](https://user-images.githubusercontent.com/74787268/99865062-9092ba80-2ba7-11eb-9969-06060fe31e82.png)

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring? 
No

Is this a problem in the vanilla unmodded game?
I dont think so

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning

Probably wanna remove this. Also, please fill out all required sections.

**Comment by MisterChocker** [comment]
Does die AC reduces the thrust? Otherwise it's just our FMAs not showing CLB because we are logicwise still in TO Phase.

**Comment by mikecbr** [comment]
I dont know what do you mean , What im trying to say is the the aircraft should change to THR CLB instead of speed mode , it only changes from speed mode to THR CLB when it reaches that 5000 ft that i put on the ACC mode , that is wrong

**Comment by MisterChocker** [comment]
> Does die AC reduces the thrust?

**Comment by mikecbr** [comment]
Well yes , but it selects speed mode instead of THR CLB

**Comment by mikecbr** [comment]
1   
![image](https://user-images.githubusercontent.com/74787268/99887587-c5554f00-2c45-11eb-870b-97c90ac1bd3c.png)

2  
![image](https://user-images.githubusercontent.com/74787268/99887592-cdad8a00-2c45-11eb-9ac2-6df824def219.png)

3   
![image](https://user-images.githubusercontent.com/74787268/99887597-d56d2e80-2c45-11eb-8948-d605c06e25af.png)

**Comment by MisterChocker** [comment]
yes, I don't care what the fma's showing, because the fma will most likely be showing bad info.
Is the autothrust holding a constant climb speed?

**Comment by mikecbr** [comment]
4

> yes, I don't care what the fma's showing, because the fma will most likely be showing bad info.
> Is the autothrust holding a constant climb speed?

I think we are talking about different things.... 
I dont know how to explain it better , and i dont know why you are asking me about autothrust and constant climb speed....
The bug im saying is relating to a different thing.
When the LVR CLB flashes on the FMA at 3500 , (because i already selected 3500 ft in THR RED PERFORMANCE PAGE ON THE MCDU) I set the THRUST levers to CLB position , but because I selected 5000 ft on ACC on the MCDU The FMA is showing me SPEED instead of THR CLB. So when the airplane  reach the speed bug selected automatically by the MDCU  it decelerate instead of keep giving the power as THR CLB does.
When it reaches and pass the altittude of that 5000ft that i previusly selected in the mcdu  on  the performance page - TAKE OFF  ACC it automatically starts THR CLB , and, that is wrong.

**Comment by tshomas** [comment]
Hi Guys, Mike asked for some help on the Discord to help explain what he's trying to get at!

So he's trying to do a noise abatement climb (NADP1) which has a THR RED at 3500ft, and an ACC ALT of 5000ft.

Now at 3500ft, the Autothrust changes from MAN TOGA/MAN FLX to flashing LVR CLB.

In the real aircraft in this situation, the Autothrust would then change to THR CLB while holding SRS speed, keeping the thrust on to power the aircraft away from the ground.

Apparently to Mike, (I haven't tried a noise departure yet in the mod), the mod changes Autothrust to SPD instead and holds the SRS speed target...which then means it gets to the SRS speed target and takes thrust off to maintain, which is the opposite of what you want near the ground/heavy/on a noise departure.

Hope that helps/clears it up a little, bit of lost in translation + airbus terminology doesn't help!

**Comment by MisterChocker** [comment]
> So when the airplane reach the speed bug selected automatically by the MDCU it decelerate instead of keep giving the power as THR CLB does.

Thanks, that's what I wanted to know, because I know how the systems work and I may already have a fix in my mind for that.
Need to find the time for some testing. Should be a simple fix.
I said I don't care about the FMAs was because they are not commanding anything, they are just a result of something changed. In this case the logic is most likely wrong or not implemented.

**Comment by mikecbr** [comment]
Sorry for all the mess that i created , thank you for everything.
👍

**Comment by MisterChocker** [comment]
np

**Comment by mikecbr** [comment]
Good evening , any news here ? I saw a new pr about acc but it is from a go around , I though it was related to this

**Comment by MisterChocker** [comment]
Might be working after this pr landed #3658
