### ISSUE TITLE
[BUG] knob or switch animation bug

### ISSUE THREAD

**Issue by Kimbyeoungjang** [flybywiresim/a32nx#2042]
**Mod Version**
 latest master

**Describe the bug**

if i click LAND light button, it move like static lever. just instant change to on or off or retract

but i scroll with mouse wheel, it move linear and smooth like lever.

i think it is asobo bug but we can find a reason maybe?

**To Reproduce**

1. use any lever like landing light, VOR - ADF lever
2. click with mouse left -> it move instantly like static lever
3. scrolling with mouse wheel -> it move linear like before.

**Expected behavior**

both click and scrolling must seems linear

**Actual behavior**

only scrolling seems linear

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by lukecologne** [comment]
Yeah, that is a known bug, it's happening with all 3 or more state switches, it's also in the vanilla aircraft. I think there was an issue about this but it was closed since it was for multiple issues at once

**Comment by Kimbyeoungjang** [comment]
> Yeah, that is a known bug, it's happening with all 3 or more state switches, it's also in the vanilla aircraft. I think there was an issue about this but it was closed since it was for multiple issues at once

oh... i can't find that issue on search tap sry.

but that bug was an issue? i notice that after this update.

**Comment by lukecologne** [comment]
This bug has been fixed by Asobo a few updates ago, closing.
