### ISSUE TITLE
[BUG] level off does not happen at FCU altitude (CLB/DES)

### ISSUE THREAD

**Issue by ToasterF16** [flybywiresim/a32nx#2043]
**Mod Version**
{ "built": "2020-11-20T22:55:09+00:00", "ref": "refs/heads/master", "sha": "2665e17d24ac35a2b72bdc005ef1d9df087d6ef9", "actor": "wpine215", "event_name": "push" }

**Describe the bug**
If you change the altitude in the FCU while the aircraft is in CLB/DES, it will level off at the altitude that was set when CLB was enganged, not the altitude that is currently set in the FCU.

**To Reproduce**
1. fly in ALT/NAV with AP ON, FL100
2. dial FL200 in, press CLB
3. while the aircraft climbs, change the FCU ALT to FL180 (or FL240)
4. The Aircraft will bust/never reach the FCU ALT and will level off at FL200 anyway

**Expected behavior**
ALT* -> ALT should be triggered when reaching the current dialed FCU Altitude

**Actual behavior**
Current FCU altitude is ignored by the vertical guidance in favor for the altitude that was selected when the managed vertical mode was engaged

**References**
FL240 was dialed in the FCU when CLB was engaged on FL160
![image](https://user-images.githubusercontent.com/70760313/99876173-4c2e0b80-2bf5-11eb-8d12-5eef8b17f232.png)

**Additional context**
Same thing happens with DES or when performing a Take Off after the aircraft transitions from SRS to CLB. It will remember the altitude that was set when CLB/DES went active and ignores what's currently dialed in.

Was this working before/when did the issue start occurring?
Never showed the correct behaviour.

Is this a problem in the vanilla unmodded game?
Yes.

Discord username (if different from GitHub): Toaster#7595

**Comment by Watsi01** [comment]
Strange. Never had that. Did you try it with commanded alt (pull ALT knob). Does it work then?

**Comment by ToasterF16** [comment]
> Strange. Never had that. Did you try it with commanded alt (pull ALT knob). Does it work then?

Of course it works when you press/pull the ALT knob again after dialing a new FCU altitude. But that is not the point of my bug report. It should also level off at the current FCU ALT if you **don't** press/pull the knob again.

**Comment by Watsi01** [comment]
Yes. But it works on my side. Changing alt during des or clb does in fact meet the up to date alt (FCU). At least for me. But I'm on commanded alt most of the time. So I tried to find out (with my previous question) if it only occurs for you in managed mode or in both modes.

**Comment by ToasterF16** [comment]
> Yes. But it works on my side. Changing alt during des or clb does in fact meet the up to date alt (FCU). At least for me. But I'm on commanded alt most of the time. So I tried to find out (with my previous question) if it only occurs for you in managed mode or in both modes.

As far as I have tested, it only happens in CLB/DES (managed).

**Comment by Watsi01** [comment]
Ok. I think you're right with the bug. I'll get some feedback from the pilots to be sure.

**Comment by St54Kevin** [comment]
The plane in general completely ignores a newly entered altitude. It takes it only if you push or pull again after resetting
