### ISSUE TITLE
[BUG] Temperature (ECAM) TAT SAT not right color

### ISSUE THREAD

**Issue by mikecbr** [flybywiresim/a32nx#2044]
**Mod Version**
Latest master branch and lastest stable build release 4.1

**Describe the bug**
The temperature for the ecam TAT and SAT in the real aircraft is showed in green the numbers , and in our airplane it is in white

**To Reproduce**

1.
2.
3.

**Expected behavior**
![image](https://user-images.githubusercontent.com/74787268/99877989-67ebde80-2c02-11eb-8dd6-ed80a344229e.png)

**Actual behavior**
White numbers instead of green

**References**

**Additional context**

Was this working before/when did the issue start occurring?
No

Is this a problem in the vanilla unmodded game?
Dont know

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Hello, where is that reference from ? Seems like it's an EIS1 ECAM, while we model EIS2.

**Comment by Benjozork** [comment]
Confirmed with EIS2 IRL reference.

This seems to be a regression since I distinctly remember it being green. Will look into it.

**Comment by mikecbr** [comment]
Hello , it is the only picture reference that i have , but it is the same in all 320 , CEO and NEO that the temperature numbers should be in green , thank you .
