### ISSUE TITLE
[BUG] Engine autothrust exceed

### ISSUE THREAD

**Issue by Sadawalebg** [flybywiresim/a32nx#2047]
**Mod Version**
Latest master branch and lastest stable build release 4.1

**Describe the bug**
On the ECAM when the throttle is turned on, pushing the throttle will cause it to rise higher before returning to the desired power setting.

**To Reproduce**
Increase the power between 50 and 100% to find the result.

**Expected behavior**
The power does not exceed the blue point.

**Actual behavior**
The power exceeds the blue point but goes back down to it.

**References**
![Screenshot_1](https://user-images.githubusercontent.com/73961641/99882442-d2ac1280-2c20-11eb-8cfd-8c7b1578ee6f.jpg)

https://youtu.be/Hza_TieFSRk

Links ref IRL :
https://youtu.be/cv41hm4JEB8?t=173

https://youtu.be/Q-Xvj_7N_5w?t=199

**Additional context**
I looked but nothing about it. 

Discord user: Sawada_Sensei#7960

**Comment by Benjozork** [comment]
Hello, can you please provide IRL references in the **References** section ?

**Comment by Sadawalebg** [comment]
> 
> 
> Hello, can you please provide IRL references in the **References** section ?

Its done I hope that this will be enough for you because I can't find other examples but we may have heard that the engines don't exceed the power required.

**Comment by MisterChocker** [comment]
Yes known issue, engine controller overreacts.
