### ISSUE TITLE
[REQUEST] clic right/left to managed/selected mode autopilot

### ISSUE THREAD

**Issue by Sadawalebg** [flybywiresim/a32nx#2048]
**Is your feature request related to a problem? Please describe.**
I think we agree that the asobo system with the arrows is really rotten because the click zone is already very small and the arrows are impractical.  What I suggest, if possible, is to do as on FSX/P3D.

**Describe the feature you'd like to see implemented**

Left click to engage the manage mode and right click for the selected mode. This can also apply to other buttons other than the autopilot.

**References**
![Screenshot_2](https://user-images.githubusercontent.com/73961641/99883008-b5794300-2c24-11eb-8aa7-1d502871f5ed.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/73961641/99883009-b611d980-2c24-11eb-85d3-e8d570984ab1.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/73961641/99883010-b6aa7000-2c24-11eb-9f2c-29647777a11b.jpg)

**Additional context**

Discord user: Sawada_Sensei#7960

**Comment by sidnov** [comment]
This is solved by the latest "Lock" mode implementation from Asobo, available within the sim.

**Comment by tracernz** [comment]
With lock mode you can bind whichever buttons you like to the push/pull actions.
