### ISSUE TITLE
[BUG] Simplane.getIsGrounded() initially returns false when on ground

### ISSUE THREAD

**Issue by MrMinimal** [flybywiresim/a32nx#2054]
**Mod Version**
master (2665e17d24ac35a2b72bdc005ef1d9df087d6ef9)

**Describe the bug**
`Simplane.getIsGrounded()` returns wrong values in certain conditions.

**To Reproduce**
1. Add `Simplane.getIsGrounded()` to an init() function (I put it here: https://github.com/flybywiresim/a32nx/blob/2665e17d24ac35a2b72bdc005ef1d9df087d6ef9/A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_COND.js#L18)
2. Start a flight from any airport, starting on the runway
3. Skip the intro where your plane taxies onto the runway or don't
4. `console.log()` the value `Simplane.getIsGrounded()` returned in the init() function.

Basically:
```
        init() {
            this.test = Simplane.getIsGrounded();
        }
        update(_deltaTime) {
            console.log("Simplane.getIsGrounded() returned in init(): " + this.test);
        }
```

**Expected behavior**
It should always return true when spawning on the runway.

**Actual behavior**
It returns false if flight is started for the first time from the Main Menu.
Restarting the flight using Escape -> Restart fixes it.

**Additional context**
![grafik](https://user-images.githubusercontent.com/8739690/99898144-9c61a800-2c9f-11eb-8a43-a6220375ef88.png)

Was this working before/when did the issue start occurring?
Don't know.

Is this a problem in the vanilla unmodded game?
Not applicable.

Discord username (if different from GitHub):
MrMinimal#8489

**Comment by beheh** [comment]
Yeah, similarly I've observed the Radio Altimeter sometimes returns large values (200 or more) when skipping the intro. My theory is that MSFS is still loading in the terrain and uses either a placeholder or a low-resolution mesh. By letting the intro play out the simulator has enough time to load it and so it's immediately correct.

**Comment by davidwalschots** [comment]
This is an issue of MSFS itself. We can't change this behaviour. Therefore I'm closing this issue.
