### ISSUE TITLE
[REQUEST] Registration plate could be defined in liverie folder

### ISSUE THREAD

**Issue by JLD95** [flybywiresim/a32nx#2055]
**Is your feature request related to a problem? Please describe.**

Registration plate in cockpit automaticaly change when I change liverie 

**Describe the feature you'd like to see implemented**

Possibility to the modding software to read File: "A320NEO_COCKPIT_MAINPANEL_ALBD.PNG.dds" in liverie folder and if not defined in A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/TEXTURE/ Folder

**References**

**Additional context**

Discord username (if different from GitHub):

**Comment by 2hwk** [comment]
I supposed this was already addressed by https://github.com/flybywiresim/a32nx/pull/3570, so closing. On the other hand 2850 isn't fully addressed, so that will be reopened.
