### ISSUE TITLE
[BUG] Status "Normal" msg is anomally small

### ISSUE THREAD

**Issue by Pushok154** [flybywiresim/a32nx#2056]
**Mod Version**

dev version downloaded on 22.11.2020 0940z

{ "built": "2020-11-20T22:55:09+00:00", "ref": "refs/heads/master", "sha": "2665e17d24ac35a2b72bdc005ef1d9df087d6ef9", "actor": "wpine215", "event_name": "push" }

**Describe the bug**

During prreliminary or cockpit prep or afterstart flow when checking status the "normal" message is anomaly small

**To Reproduce**

1.open status during any flight phase or cockpit preparation

**References**

![image](https://user-images.githubusercontent.com/74020654/99900308-d773d380-2cbf-11eb-9f9b-bd5d827c2368.png)

**Comment by Watsi01** [comment]
Known issue. It should be fixed already in the current master version.
