### ISSUE TITLE
[BUG] Managed Speed ignores flap setting

### ISSUE THREAD

**Issue by martysweet** [flybywiresim/a32nx#2057]
**Mod Version**

master zip
{ "built": "2020-11-20T22:55:09+00:00", "ref": "refs/heads/master", "sha": "2665e17d24ac35a2b72bdc005ef1d9df087d6ef9", "actor": "wpine215", "event_name": "push" }

**Describe the bug**

When using Managed Speed Mode, the autopilot no longer takes into account the flap settings when setting the target speed, resulting in an overspeed.
This was observed on Departure and Approach.

**To Reproduce**

1. Use the above build
2. Take-off with Flaps 2
3. Enable managed speed mode
4. Aircraft will accelerate to 250

OR

1. Use the above build
2. Set speed to 220
3. Set flaps 1
4. Enable managed speed
5. Aircraft will accelerate to 250

**Expected behavior**

Managed speed mode should not put the aircraft into overspeed.

**Actual behavior**

Managed speed mode assumes 250 knts regardless of flap setting, putting the aircraft into overspeed.

**References**

![image](https://user-images.githubusercontent.com/20517404/99900472-953e9800-2ca7-11eb-8c1f-13b4de7592a7.png)

![image](https://user-images.githubusercontent.com/20517404/99900527-c1f2af80-2ca7-11eb-92a8-eccc879da17d.png)

The magenta bug can be seen at 250, while the flags are set.

**Additional context**

Was this working before/when did the issue start occurring?
This was working properly on this build:
_built: 2020-11-10T15:19:38+00:00
ref: refs/heads/master
sha: 6cb5116649c223cba11e7eec6ee39fcba9ecfb68
actor: Benjozork
event_name: push_

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub): 

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Watsi01** [comment]
This was changed to fit reality. In Takeoff / THR clb mode, the managed mode will not respect flaps maximums. You have to handle it via your pitch up to hold speed until you retract the flaps.

During descent and approach, I'm not sure what went wrong here. It seems to me (looking at your screenshots) that the APPR mode in the MCDU is not active.

**Comment by martysweet** [comment]
Ah okay, thanks for the clarification. 

You are correct in thinking the approach mode was not activated on these screenshots. When activated, the VLS speed was immediately targetted, regardless of flap position, is this expected?

**Comment by Watsi01** [comment]
Without flaps it should target Clean speed (green dot). With flaps set it should target F speed (see top line on CDU APPR page). With flaps full it should target VAPP.

**Comment by martysweet** [comment]
Thanks for the help @Watsi01, that's all working as expected with APPR mode activated! Hopefully, this Issue helps someone else. Closing for now 👍 

![image](https://user-images.githubusercontent.com/20517404/99901205-cf5e6880-2cac-11eb-8684-8ae1430fcc07.png)

![image](https://user-images.githubusercontent.com/20517404/99901211-d84f3a00-2cac-11eb-9a13-cebdd76bc87f.png)

![image](https://user-images.githubusercontent.com/20517404/99901286-7ba04f00-2cad-11eb-8d96-2c6ca4e1110b.png)
