### ISSUE TITLE
[REQUEST] add BRG/DIST function in PROG page

### ISSUE THREAD

**Issue by giova1588** [flybywiresim/a32nx#2058]
**Is your feature request related to a problem? Please describe.**

No related problems 

**Describe the feature you'd like to see implemented**
 add the possibility to insert the icao and rwy in PROG page to calculate the BRG/DIST 

**References**

**Additional context**

Discord username (if different from GitHub): badu

**Comment by Agmagor** [comment]
Hi, I believe this duplicates #1744

**Comment by MisterChocker** [comment]
duplicate #1744
