### ISSUE TITLE
[BUG] No brakes hot warning after RTO

### ISSUE THREAD

**Issue by highperformancedevelopments** [flybywiresim/a32nx#2063]
**Mod Version**
current master

**Describe the bug**
After RTO (Rejected Takeoff) there is no brakes hot indication shown if the brake temperature is above 300°C.

**To Reproduce**
1. Spawn on Runway
2. Set Autobrake to max
3. Open ECAM WHEEL page
4. Apply TOGA
5. Reject Takeoff before V1 (thrust idle)
6. Use manual brake 
7. Monitor brake temperature
8. If brake temperature > 300°C monitor upper ECAM (E/WD) warnings

**Expected behavior**
Warning chime, "BRAKES HOT" indication in upper ECAM (E/WD) display.

**Actual behavior**
No chime, no indication in upper ECAM (E/WD)
If you apply TOGA again, the warning is displayed in the upper ECAM (E/WD)

**References**
![KEIN GAS](https://user-images.githubusercontent.com/25608553/99917764-a8d31880-2d12-11eb-8936-d6d1e006d6e4.PNG)
![VOLLGASE](https://user-images.githubusercontent.com/25608553/99917766-aa9cdc00-2d12-11eb-85db-5ffe502179cf.PNG)

**Additional context**
If I apply manual brakes after RTO there is a wrong indication in the upper ECAM (Landing) --> See [comment](https://github.com/flybywiresim/a32nx/issues/2034#issuecomment-731849107)

Was this working before/when did the issue start occurring?
Don't know

Is this a problem in the vanilla unmodded game?
Don't know

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by beheh** [comment]
Hello! Thanks for the report. The BRAKES HOT message is now correctly inhibited between landing (or a high-speed RTO) and until 5 minutes after last engine shutdown. So this is not a bug.

In an upcoming version you'll be able to recall it earlier using the RCL button, but it won't appear by itself or immediately if you just wait after RTO with engines running.
