### ISSUE TITLE
[BUG] MCDU color mismatch in some lines

### ISSUE THREAD

**Issue by Pushok154** [flybywiresim/a32nx#2067]
**Mod Version**
{ "built": "2020-11-23T06:02:35+00:00", "ref": "refs/heads/master", "sha": "214b9b81e4e218b75fdf08883bac4accc91f5768", "actor": "Benjozork", "event_name": "push" }

**Describe the bug**
Some lines and values have wrong color representation

RW SID and TRANS colour must be green

![IMG_4822](https://user-images.githubusercontent.com/74020654/99977436-b1305f80-2db5-11eb-84b2-7b53824d24c8.jpeg)

F,S,O and = symbols must be white

![IMG_4825](https://user-images.githubusercontent.com/74020654/99977522-ce652e00-2db5-11eb-8d03-aed818f81e10.jpeg)

Preselected speed and [ ] symbol on climb page must be cyan

![IMG_4826](https://user-images.githubusercontent.com/74020654/99977647-f94f8200-2db5-11eb-94a0-f613a2f75f1b.jpeg)

**References**
Derparture page

![ba72c259-a87f-4cac-91b6-a1d6fc613210](https://user-images.githubusercontent.com/74020654/99987668-cd39fe00-2dc1-11eb-9ea1-83b776ce0382.jpg)

T/O PERF page

![fc44bbdd-7d06-42f8-a23a-cb0be4f735df](https://user-images.githubusercontent.com/74020654/99987719-daef8380-2dc1-11eb-9c0a-c989753182ab.jpg)

CLB page brakets and presel speed

![3ec67cdf-f54f-4f38-99da-880ee363b56b](https://user-images.githubusercontent.com/74020654/99987841-fce90600-2dc1-11eb-9069-1a7fd414fefd.jpg)

![34e327fc-5e88-4c6c-b088-8a9fca905f89](https://user-images.githubusercontent.com/74020654/99987855-007c8d00-2dc2-11eb-9bbf-6eb53df3c574.jpg)

**Comment by Benjozork** [comment]
Hello, I reformatted your issue and removed the last one which is already reported by #2044.

Please also add references to the IRL plane in the **References** section.

**Comment by MisterChocker** [comment]
This pr #1824 takes care of the TO performance page colors.

**Comment by Pushok154** [comment]
> Please also add references to the IRL plane in the **References** section.

ok, on 25th i will fly real plane, and will take couple shots of those pages

**Comment by Pushok154** [comment]
And also i forget to tell that default MCDU values have small size and modified have bigger one!
just look at trans alt and thr red alt they are default values computed by fmgs, but acc alt was modified by crew an it has large figures! Have i open new issue?

![fc44bbdd-7d06-42f8-a23a-cb0be4f735df](https://user-images.githubusercontent.com/74020654/99988235-73860380-2dc2-11eb-82ff-8ddc2d5623ca.jpg)

**Comment by beheh** [comment]
> And also i forget to tell that default MCDU values have small size and modified have bigger one!
just look at TRANS ALT and THR RED ALT they are default values computed by fmgs and have small font size, but ACC ALT was modified by crew an it has large figures! Have i open new issue?

That is also being done as part of #1824.

**Comment by neryash** [comment]
Is this in progress, or can I start working on it?

**Comment by beheh** [comment]
The PERF part is in progress at #1824. I'm not aware of any work being done on the DEPARTURES/ARRIVALS page, but I'd suggest check if there's any draft or open pull request.
