### ISSUE TITLE
[BUG] Distance and Time incorrect

### ISSUE THREAD

**Issue by marinerhally** [flybywiresim/a32nx#2072]
**Mod Version**
Master Version off installer

**Describe the bug**
On the FMCU its was showing 0 nm to arrival and also the current time its was in the sim it did change back and show the distance left and time of arrival but then went back I have enclosed a picture to show

**To Reproduce**

1.
2.
3.

**Expected behavior**
Show remaining distance and estimated arrival time

**Actual behavior**
Showing 0 miles left and current sim time

**References**
![20201122_004955 797](https://user-images.githubusercontent.com/74931221/100010058-9cf55e00-2dc7-11eb-8289-f410918f3a5b.jpg)

**Additional context**
Just thought id bring it to your attention :)

Was this working before/when did the issue start occurring?
It did show correct then went to 0 then back to normal then back to 0 again for the rest of the flight.

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub): Mariner Hally#0715

**Comment by Benjozork** [comment]
Please provide the contents of the build-info file like indicated in the template.

**Comment by marinerhally** [comment]
Would that be the A32NX folder in my community folder? Its been updated since this happened via the installer but I’m happy to provide anything you need. Apologies for not including this is my first reports of this great MOD. Regards Sent from Mail for Windows 10 From: Benjamin DupontSent: 23 November 2020 20:29To: flybywiresim/a32nxCc: marinerhally; AuthorSubject: Re: [flybywiresim/a32nx] [BUG] Distance and Time incorrect (#2072) Please provide the contents of the build-info file like indicated in the template.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Benjozork** [comment]
Yep it would be in your A32NX folder, although I don't know what happened to your GitHub comment here 🤣

**Comment by marinerhally** [comment]
Possibly because I just replied to the email lol 
I think this is what you need if you need anything else give me a shout

[build_info.txt](https://github.com/flybywiresim/a32nx/files/5585769/build_info.txt)

Also I'm a content creator on Facebook and Twitch streaming MSFS2020 and flying the Airbus with A32NX most of the time, I'd love to get involved in the MOD promoting, testing etc if this is something I could be of use for please don't hesitate to contact me. Id love to get involved in some way :D

**Comment by Benjozork** [comment]
Your version is out of date by 10 days - please update and report back.

> Also I'm a content creator on Facebook and Twitch streaming MSFS2020 and flying the Airbus with A32NX most of the time, I'd love to get involved in the MOD promoting, testing etc if this is something I could be of use for please don't hesitate to contact me. Id love to get involved in some way :D

I will get someone to give you the role.

**Comment by marinerhally** [comment]
Hi
Is that a case of downloading development version to update. It says 10
days out of date i do check the installer most days sometime updating 2-3
times a day. The 2 bugs I reported did happen again last night while flying
i will update today and report back mate :)

Thanks for your help

**Comment by Lucky38i** [comment]
I can't comment on the distance but I know the time is determined using a simple `D=S*T` logic. So it's dependent on your speed. I believe it's just temporary until we re-write the FPLAN page. In the mean time you can use FUEL PRED to get a better look at your arrival time.

**Comment by Benjozork** [comment]
No response from author.
