### ISSUE TITLE
[BUG] Wwise(sound.xml) is not working

### ISSUE THREAD

**Issue by Kimbyeoungjang** [flybywiresim/a32nx#2077]
**Mod Version**
 current master

**Describe the bug**

![image](https://user-images.githubusercontent.com/23118756/100034529-b508c400-2e3f-11eb-8477-d45857cc4be1.png)
that code was working before(https://youtu.be/ZvsAmWWHnsY)
when disconnect a/thr, A32NX_ATHR_DISC var going to true, and Caution sound ringing once. but now, it is not working 

i think my code is not working so i change 
![image](https://user-images.githubusercontent.com/23118756/100034606-e71a2600-2e3f-11eb-866a-3e2cc1328391.png)
this. seatbelt is working well. so i change that seatbelt WwiseEvent to caution sound and that is not work

So, last
![image](https://user-images.githubusercontent.com/23118756/100034641-fbf6b980-2e3f-11eb-9b42-d9c05fc7fb35.png)
i change my code to seatbelt sound and that is working

something is problem on sound i think. but idk which part is broken

**To Reproduce**

1. use wwise event
2. i checked improved_tone_caution, cchordshort, cchordloop and that is not working all
3.

**Expected behavior**

should sound working when var is true

**Actual behavior**

sound is not working

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Please go to our Discord for development support.
