### ISSUE TITLE
[BUG] ECAM ELEC page incorrect

### ISSUE THREAD

**Issue by Watsi01** [flybywiresim/a32nx#2082]
**Mod Version**
"built": "2020-11-23T06:02:35+00:00", "ref": "refs/heads/master", "sha": "214b9b81e4e218b75fdf08883bac4accc91f5768", "actor": "Benjozork", "event_name": "push" 

**Describe the bug**
Sometimes the ELEC page shows correct configuration, sometimes not. **Did not find a way to reproduce.** 

**To Reproduce**

1. see above
2.
3.

**Expected behavior**
ELEC page showing correct ELEC config.

**Actual behavior** 
See image: took during climb with APU off and both engines running (gens on). The ELEC page shows APU running and engine Nr2 not powering the plane.

**References**
![elec](https://user-images.githubusercontent.com/72334392/100088999-4af91a80-2e51-11eb-8758-679dc392e61f.png)

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
Issue appears occasionally since ELEC page is implemented.

Discord username (if different from GitHub): RogePete

**Comment by lukecologne** [comment]
Elec page is showing placeholder information since systems are implemented in wasm, which isn't integrated into the mod yet.

**Comment by Watsi01** [comment]
@lukecologne Thx. The same for the PRESS page, I guess?
