### ISSUE TITLE
ATC chatter doesn't work with todays 11/24 dev download

### ISSUE THREAD

**Issue by RayPov** [flybywiresim/a32nx#2084]
**Mod Version**

**Describe the bug**

ATC chatter doesn't work with todays 11/24 dev download. Here is a feedback I got from the developer of the ATC Chatter App: This is likely to be another bug in that aircraft. If you enable the FS-ATC-Chatter setting to monitor radio power (The Default), then the player will monitor the SimConnect Radio Status variable that tells us if the radio is available in the aircraft and if it has power. If the aircraft is not properly maintaining that then FS-ATC-Chatter will think the radio is powered down when it isn’t. I suspect this plane has that issue, either all the time or intermittently. I suggest you turn off the radio power monitoring setting in FS-ATC-Chatter when using this plane and report the problem to the aircraft designer

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
Can you join our Discord so we can discuss issues with third-party programs ?

**Comment by RayPov** [comment]
Benjozork

> Can you join our Discord so we can discuss issues with third-party programs ?

I have been a member of Discord since the mod was first developed

**Comment by Benjozork** [comment]
Yeah, I know. But compatibility with third-part software should be discussed there. GitHub issues are for confirmed and specific issues. Support and questions should be directed to our discord.

Can you ping someperson#4953 in #general ?

**Comment by RayPov** [comment]
I was told on discord to put an issue up on GitHub.

TY

Ray

**Comment by Benjozork** [comment]
I'll advise our team to better direct users in the future.
