### ISSUE TITLE
Altitude call out too late

### ISSUE THREAD

**Issue by bisinchi** [flybywiresim/a32nx#2086]
**Mod Version**
 Master

{ "built": "2020-11-24T08:08:38+00:00", "ref": "refs/heads/master", "sha": "b570de8c53cd5b52a21c81f8120bfa57d8c53830", "actor": "wpine215", "event_name": "push" }

**Describe the bug** Altitude callout (500 hundred, 400 hundred, 300 hundred, etc seem a bit late. 

Altitude callout (500 hundred, 400 hundred, 300 hundred, etc seem a bit late. The audio seem triggered when the associated altitude is reached, whereas I believe that the audio should be completed at altitude crossing, 

**To Reproduce** execute a normal landing
 execute a normal landing and pay attention to altitude callouts. 
 Practising circuits with latest master build, I encountered this. Not sure though if this was the case in previous master or release.
1.
2.
3.

**Expected behavior**

audio should be completed at altitude crossing
**Actual behavior**

audio start at altitude crossing, meaning when the sentence is finished, the aircraft is actually below that altitude
**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
Not sure.

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
Please add a title and provide references for the behaviour you think is accurate.

**Comment by ntlgr** [comment]
The OP seems to be right. I have checked multiple videos on YT detailing the PFD on approach and it's always the case. 
Example: https://youtu.be/bjGT9aJU6jo

**Comment by lukecologne** [comment]
Documents say the callouts start a bit higher than the altitude you would expect, for example the 100 callout starts at 110 feet, or 50 feet starts a 53 feet.

**Comment by bisinchi** [comment]
> Please add a title and provide references for the behaviour you think is accurate.

Sorry, I missed out on that, it's corrected.

**Comment by Benjozork** [comment]
Still no references.

**Comment by bisinchi** [comment]
> Still no references.
I'm trying to find documents that reference the callout issue.

**Comment by krangerich** [comment]
There seems to be no exact description in the FCOM. Here the corresponding part:
![image](https://user-images.githubusercontent.com/7890659/100485469-748b9d80-3100-11eb-91c7-6976d554ce91.png)
![image](https://user-images.githubusercontent.com/7890659/100485493-96852000-3100-11eb-8f4d-32a9f8f1cb42.png)

The phrase "in the detection zone" might be just a slight indication, that the callout starts before reaching the height

**Comment by bisinchi** [comment]
Yes, saw that too, was hoping to see more details in the FCOM. Seems like we need to have FWC spec to get the logics for triggering the sounds.

**Comment by AirbusA320Pro** [comment]
The OP is correct. IRL the Airbus needs to have completed saying to the word/phrase at or before the exact height. The reason for this, as it relates to decision making. If at the exact minimum decision height (DH) the audio only starts to speak, then the aircraft will be well below the intended height before a decision can be made.

**Comment by A320PHX** [comment]
Related to the altitude callouts, is anyone experiencing every altitude being called out at least twice in a row?

**Comment by wpine215** [comment]
> Related to the altitude callouts, is anyone experiencing every altitude being called out at least twice in a row?

Yes, I've had that issue as well. Probably warrants its own separate github issue if one doesn't already exist for it

**Comment by bisinchi** [comment]
I have the double callout issue on master downloaded on 1st December. I think this should be a separate issue to this one.

**Comment by MisterChocker** [comment]
cc @hotshotp can you address this?

**Comment by hotshotp** [comment]
> cc @hotshotp can you address this?

No, it's all asobo logic for the call-outs and someone else will need to code them

**Comment by beheh** [comment]
I've found a reference for when the callout should trigger, it's usually 20ft above the actual altitude. This will be implemented in the reworked FWC, but we can probably issue a fix in the mean time as well.

**Comment by beheh** [comment]
While I can't share the exact reference, I'm aware of the following numbers:

- 2530ft to 2500ft => "Two Thousand Five Hundred"
- 2020ft to 2000ft => "Two Thousand"
- 1020ft to 1000ft => "One Thousand"
- 513ft to 500ft => "Five Hundred"
- 310ft to 300ft => "Three Hundred"
- 210ft to 200ft => "Two Hundred"
- 110ft to 100ft => "One Hundred"
- 53ft to 50t => "Fifty"
- 42ft to 40t => "Forty"
- 32ft to 30t => "Thirty"
- 22ft to 20t => "Twenty" 
- 12ft to 10t => "Ten" 
- 6ft to 5ft => "Five"
- DH <90ft, 105ft above => "Hundred Above"
- DH >=90ft, 115ft above => "Hundred Above"

**Comment by 2hwk** [comment]
I have a feeling this old issue is already addressed, if so then this can be closed.

**Comment by beheh** [comment]
@2hwk No, it's not. Our GPWS class still checks for the round altitudes, where it should be checking for the earlier ones I mentioned in an earlier comment. This will eventually be implemented by the new FWC, but somebody could take those numbers and plug it into the old GPWS class to get the correct behavior even without the new FWC.
