### ISSUE TITLE
Latest Dev Build Unflyable after 1.11.6.0 update

### ISSUE THREAD

**Issue by canadiantodd** [flybywiresim/a32nx#2088]
Multiple issues on my first flight today after downloading the FS2020 1.11.6.0 update, downloaded the latest Dev build before flying:

1) TCAS gave off an error while aligning (orange code in display), but eventually the systems came alive.
2) After takeoff, engaged AP but the aircraft wouldn't follow the flight plan in managed heading.
3) Set heading to manual, aircraft would not bank right to new heading (straight line).
4) Tried left heading instead, plane banked ~40 degrees to setting, but the flight plan line points straight and never changes.
5) Thrusters kept increasing speed to overspeed, even with lever in climb detent and autothrusters engaged.

**Comment by lukecologne** [comment]
Doesn't follow template.
