### ISSUE TITLE
[BUG] +/- button does not work on MCDU to enter temp next to FL

### ISSUE THREAD

**Issue by ArticTern2992** [flybywiresim/a32nx#2090]
**Mod Version**

v0.4.1 

**Describe the bug**

The "+/-" button does not work on the MCDU. I cannot enter negative temperatures as a part of INIT

**To Reproduce**

1. Load plane at gate/runway
2. Begin INIT by clicking the corresponding MCDU button
3. Enter FL
4. Enter "/"
5. Attempt to enter negative number for temp using the "+/-" button

**Expected behavior**

I expected to be able to enter a negative temperature

**Actual behavior**

The button does not work and I cannot enter a valid temperature for FL CRZ.

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by ArticTern2992** [comment]
Sorry, I'm very new to GitHub and don't know if I used the right format.

**Comment by Benjozork** [comment]
Can you try using the development version ?

**Comment by ArticTern2992** [comment]
Where would I find that?

**Comment by ilyeshammadi** [comment]
This feature was added yesterday, install the official downloader and use the development version.
https://github.com/Externoak/A32NX-installer/releases/latest/download/A32NX_Downloader.zip

**Comment by Rameyuk** [comment]
You also don't need to enter the temperature. Just enter the flight level (eg. 390) and it'll calculate the temperature for you automatically.

**Comment by kielyscott** [comment]
Yeah buddy, temperature isn't editable, it's calculated as ISA from your flight plan by the MCDU itself when you enter a CRZ FL. 

I do believe it should be editable in RL though. Usually positive temperatures are entered without a plus, and negative requires the - .

**Comment by ArticTern2992** [comment]
Thanks y'all. I've dl'ed the dev version as recommended and will retry the
mod this weekend on stream! Your team's responsiveness and attention to
detail is unmatched. Good work, team!
