### ISSUE TITLE
[BUG] FMGC & NAVIGATION DISPLAY issues

### ISSUE THREAD

**Issue by 2low2slow** [flybywiresim/a32nx#2094]
**Mod Version**

{ "built": "2020-11-24T08:08:38+00:00", "ref": "refs/heads/master", "sha": "b570de8c53cd5b52a21c81f8120bfa57d8c53830", "actor": "wpine215", "event_name": "push" }

**Describe the bug**

1. Hitting F-PLN key on the FMCG gives me a TITLED UNAVAILABLE with a blank screen. 
2. The flight plan is visible on the Navigation Display but selecting PLAN mode with the MODE SELECTOR knob (on EFIS Control Panel) and clicking Up/Down arrows on the F-PLN page (blank anyway) does not have any effect --> waypoints are not switching forward on the Navigation Display.

--- Flight Plan (.pln) was prepared with Navigraph +SimBrief, then uploaded via the Upload/Save function within fs2020. Flight plan looked ok within the sim prior to hitting FLY ---   

**To Reproduce**

Doing the usual pre-flight procedure by keying data into the FMCG via the Data / Init A / Flight Plan / Perf pages

1. Updated fs2020 to the latest version
2. Installed the latest FBW A320 Dev version with the A32NX Downloader this morning
3. Same issues twice with 2 different flight plans 

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?
I had not flown the FBW A320 for a few days having switched to GA aircrafts. It worked wonderfully fine previously.

Is this a problem in the vanilla unmodded game?
Have not flown the vanilla A320

Discord username (if different from GitHub):

**Comment by WelshSimmer** [comment]
Can you confirm engines were off?

**Comment by 2low2slow** [comment]
Cold & Dark 1st time it happened, assumed I fumbled procedure.
But then 2nd attempt was a Runway Start -- same issue :-(

**Comment by Benjozork** [comment]
> Unable to access INIT Page 2 after filling in FLT NBR / COST INDEX / CRZ FL. Hitting the Left or Right arrows (Up / Down too) gives me a NOT AVAILABLE on the FMCG screen bottom left corner.

This page is not available after engine start. Was that the case ?

**Comment by 2low2slow** [comment]
INIT Page 2: 
Affirmative, engines were indeed started (runway spawn) on my 2nd attempt. I may have also tried accessing INIT Page 2 after having started engines on my Cold & Dark start.  

Hitting F-PLN key on the FMCG gives me a TITLED UNAVAILABLE with a blank screen.
Has this been reported by anyone else? Will try to reproduce tomorrow although the A32NX-Downloader installed the most updated Dev version an hour ago: 
{ "built": "2020-11-25T09:44:14+00:00", "ref": "refs/heads/master", "sha": "29398d31d99ff98313277c2bef2991ec21d13ab4", "actor": "wpine215", "event_name": "push" }
Can't test at this time.

Apologies for the false bug report on the INIT Page 2.

**Comment by MisterChocker** [comment]
fixed, issue was a undefined variable
