### ISSUE TITLE
[BUG] APPR MAG WIND allows invalid values

### ISSUE THREAD

**Issue by martysweet** [flybywiresim/a32nx#2096]
**Mod Version**

{ "built": "2020-11-24T08:08:38+00:00", "ref": "refs/heads/master", "sha": "b570de8c53cd5b52a21c81f8120bfa57d8c53830", "actor": "wpine215", "event_name": "push" }

**Describe the bug**

The FMC APPR page does not correctly validate and reject invalid headings for the MAG WIND entry.

**To Reproduce**

1. Enter the APPR page
2. Enter random values for the heading of the MAG WIND

**Expected behavior**

Invalid values for heading and speed are rejected

**Actual behavior**

Invalid values for heading are stored, and invalid values for speed are rejected with "NOT ALLOWED"

**References**

![image](https://user-images.githubusercontent.com/20517404/100204782-3756be00-2efc-11eb-8eb4-eb4d7fb6cd32.png)

![image](https://user-images.githubusercontent.com/20517404/100204810-3cb40880-2efc-11eb-9e71-0761c31009c1.png)

![image](https://user-images.githubusercontent.com/20517404/100205331-e4c9d180-2efc-11eb-99a7-28bf1f2bfd89.png)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by beheh** [comment]
Will be fixed as part of #1824.

**Comment by tareksabet** [comment]
> **BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

please remove this line. Thanks for reporting this issue
