### ISSUE TITLE
[BUG] APU doesn't start

### ISSUE THREAD

**Issue by SleutelMan** [flybywiresim/a32nx#2100]
**Mod Version**

{ "built": "2020-11-25T18:46:03+00:00", "ref": "refs/heads/master", "sha": "5b0a8f2b7fa725ab7427e8092a74f1610a8c8d3a", "actor": "wpine215", "event_name": "push" }

**Describe the bug**

When going through the preliminary cockpit checklist and starting the APU, the APU doesn't start after pressing the start switch (did press the master switch, waited a few seconds, and then the start button)

**To Reproduce**

1. Go through normal preliminary cockpit prep. checklist up to and including APU fire test
2. Press APU master switch
3. Wait 3 seconds, then press the start button

**Expected behavior**

after a few seconds the APU page on the ECAM should show flap open and the APU should start spooling up.

**Actual behavior**

Nothing happens... even after waiting for several minutes

**References**

![image](https://user-images.githubusercontent.com/28038304/100282063-432d9900-2f6b-11eb-88d6-7433b6c24571.png)
![image](https://user-images.githubusercontent.com/28038304/100282136-622c2b00-2f6b-11eb-9f92-5d2d402924a3.png)

**Additional context**

Was this working before/when did the issue start occurring?
I haven't used MSFS2020 for a few weeks, so no idea if and when this was introduced
Is this a problem in the vanilla unmodded game?
No, in vanilla game the APU behaves normally (well, the default Asobo behaviour for the APU)

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Your install seems broken. Can you try without anything else in the community folder ?

**Comment by hotshotp** [comment]
this is the default a320, i can see the font is the same as the default

**Comment by Benjozork** [comment]
> this is the default a320, i can see the font is the same as the default

The default doesn't have an APU page

**Comment by hotshotp** [comment]
> > this is the default a320, i can see the font is the same as the default
> 
> The default doesn't have an APU page

it seems like its a very old master then, its recommended to update

**Comment by kielyscott** [comment]
Local issue for sure I think. Running the latest master and can't replicate this.

Latest build installer here: https://github.com/Externoak/A32NX-installer/releases/latest/download/A32NX_Downloader.zip

**Comment by hotshotp** [comment]
closing  as  issue cannot be reproduced. This also shows that you are on a very old master, probably the one before the old MSFS update which caused the APU to not be able to be restarted which is fixed for a while now.

**Comment by Benjozork** [comment]
> { "built": "2020-11-25T18:46:03+00:00", "ref": "refs/heads/master", "sha": "5b0a8f2b7fa725ab7427e8092a74f1610a8c8d3a", "actor": "wpine215", "event_name": "push" }

...

**Comment by SleutelMan** [comment]
after wiping the community folder and re-downloading A32NX the bug has finished. Probably some leftovers from a previous installation causing the bug. Sorry!
