### ISSUE TITLE
[BUG] MCDU does not reset flight phase when reentering CRZ FL

### ISSUE THREAD

**Issue by ArwynFr** [flybywiresim/a32nx#2103]
**Mod Version**

v0.4.1

**Describe the bug**

When setting the CRZ FL (in PROG page), the MCDU does not reset the current flight phase.

**To Reproduce**

1. Plan route and takeoff
2. During climb, activate APPR phase
3. Go to PROG page and enter the CRZ FL

**Expected behavior**

> If the approach phase is activated inadvertently, reentering the CRZ FL into the PROG page restores the climb phase.

**Actual behavior**

The APPR phase remains active

**References**

Expected behavior described here: http://www.a320dp.com/A320_DP/nav-flight-management/sys-14.5.23.html

**Additional context**

Was this working before/when did the issue start occurring? no

Is this a problem in the vanilla unmodded game? no

**Comment by Benjozork** [comment]
Hello, can you please try using the latest development version ?

**Comment by MisterChocker** [comment]
This feature is not yet implemented.

**Comment by canadiantodd** [comment]
Pretty sure, but not completely sure, that if you speed up and start climbing again, you come out of appr phase. At least from memory.

**Comment by MisterChocker** [comment]
> Pretty sure, but not completely sure, that if you speed up and start climbing again, you come out of appr phase. At least from memory.

There are procedures IRL to reestablish cruise phase, to my knowledge non of them are implemented yet.

**Comment by ArwynFr** [comment]
>
>
> This feature is not yet implemented.

Right, I confused with setting CRZ FL on INIT page, which works but won't change the current phase neither.


> 
> 
> Hello, can you please try using the latest development version ?

Will do that during the weekend

**Comment by ArwynFr** [comment]
I am testing latest master version :

```json
{
  "built": "2020-12-01T17:45:57+00:00",
  "ref": "",
  "sha": "",
  "actor": "DerL30N <leon.beeser@yahoo.de>",
  "event_name": "manual"
}
```

I can change the CRZ FL, both in PROG and INIT pages.
No value appears on PROG page, but changes in PROG page is propagated to INIT.
If I enter a value above current plane altitude, that yields an ENTRY OUT OF RANGE mesage.
Changing the CRZ FL does not change the current phase, either from INIT nor PROG.

**Comment by MisterChocker** [comment]
> Changing the CRZ FL does not change the current phase, either from INIT nor PROG.

To my knowledge that does not change the flight phase (currently)
Also the entry depends on the flight phase you are in.

**Comment by ArwynFr** [comment]
> To my knowledge that does not change the flight phase (currently)

Correct, which is the point of this issue :)

> Sounds like you are past cruise phase.

Yes, I am in APPR phase, and entering CRZ FL in PROG page is expected to reset to CLB phase.
Source : http://www.a320dp.com/A320_DP/nav-flight-management/sys-14.5.23.html
> If the approach phase is activated inadvertently, reentering the CRZ FL into the PROG page restores the climb phase.

**Comment by MisterChocker** [comment]
yes and no, you need to enter a valid crz fl/alt
![image](https://user-images.githubusercontent.com/1857322/98182460-1a832800-1f06-11eb-9771-5404469a1eed.png)

**Comment by ArwynFr** [comment]
Well, I wasn't expecting that entering an invalid value would do anything other than yielding an error ...
Anyway, the point was in saying that latest master looks ok regarding CRZ FL value handling in PROG page.
The only missing part is phase change, especially resetting to CLB phase through PROG CRZ FL.
Don't know if you guys want to keep that as a bug issue, convert it or have me open a feature request ?

**Comment by MisterChocker** [comment]
> Don't know if you guys want to keep that as a bug issue, convert it or have me open a feature request ?

@Benjozork wdyt?

**Comment by Benjozork** [comment]
Feature request.

**Comment by ArwynFr** [comment]
> 
> 
> Feature request.

wilco
