### ISSUE TITLE
[BUG] EFOB FLIGHT PLAN MISSING

### ISSUE THREAD

**Issue by mikecbr** [flybywiresim/a32nx#2108]
**Mod Version**
Stable and Master branch

**Describe the bug**
The EFOB is missing in The FLIGHT PLAN 

**To Reproduce**

1.  
![image](https://user-images.githubusercontent.com/74787268/100398484-0cc94a00-304f-11eb-9845-bb0f7abdfc8d.png)

2.
3.

**Expected behavior**
EFOB working

**Actual behavior**
MISSING

**References**
The real aircraft has the EFOB wich mean fuel at destination , the airplane calculates it automatically from the fuel prediction fuel , load , wind in route , cost index etc.....

**Additional context**

Was this working before/when did the issue start occurring?
NO

Is this a problem in the vanilla unmodded game?
NO

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
> **References**

Please fill in missing info about IRL references.

**Comment by mikecbr** [comment]
Sorry for my english , what is the meaning of IRL references ?   @Benjozork

**Comment by mikecbr** [comment]
Like that ? @Benjozork

**Comment by Benjozork** [comment]
Thanks

**Comment by mikecbr** [comment]
No , thank you 👍  @Benjozork

**Comment by michaeldinozzo** [comment]
Can confirm & reproduced with today's Master version (15/12) EFOB is absent from the F-PLN page (dashes instead) but you see it on the FUEL PRED page of the MCDU. Hope that helps.

**Comment by MisterChocker** [comment]
@Lucky38i seems like people have issues with displayed efob fuel pred / only refreshing after opening fuel pred page.
Can we run a update routine to refresh fuel pred calculations during the flight?

**Comment by Lucky38i** [comment]
> @Lucky38i seems like people have issues with displayed efob fuel pred / only refreshing after opening fuel pred page.
> Can we run a update routine to refresh fuel pred calculations during the flight?

The FUEL PRED page is refreshed every 1.5 seconds. I'm closing this issue as this has been implemented already.
