### ISSUE TITLE
[BUG] Can't insert ZFW/ZFWCG

### ISSUE THREAD

**Issue by Roboplayer999** [flybywiresim/a32nx#2112]
**Mod Version**
A320NX Master 2020-11-27T09:13:12+00:00

**Describe the bug**
On the fuel pred

**To Reproduce**
Startup

**Expected behavior**
It should display the entered values and calculate the predictions

**Actual behavior**
Does nothing (Warning: I did enter the values in KG and did not get an error message saying [out of range])

**References**
![Screenshot (41)](https://user-images.githubusercontent.com/69807128/100436050-1bd7e880-309f-11eb-9236-88c2fc40e23d.png)
![Screenshot (42)](https://user-images.githubusercontent.com/69807128/100436079-24c8ba00-309f-11eb-810e-0d39655be349.png)
![Screenshot (40)](https://user-images.githubusercontent.com/69807128/100436100-2d20f500-309f-11eb-800b-d569e4c06235.png)

**Comment by Rameyuk** [comment]
I usually just click on the empty ZFW/ZFWCG box, and click it again to auto-calculate.

**Comment by Roboplayer999** [comment]
sorry, I entered it on the wrong page
