### ISSUE TITLE
[BUG] HDG SEL locked to NAV when AP

### ISSUE THREAD

**Issue by cellotako** [flybywiresim/a32nx#2113]
**Mod Version**

built: 2020-11-12T02:54:20+00:00
ref: refs/heads/master
sha: 421fc9e8c7426db8b69270ff55975a2a039176b1
actor: Benjozork
event_name: push

**Describe the bug**

When i turn autopilot after editing flightplan in flight, HDG mode can't switch to HDG. remain on NAV.

**To Reproduce**

1.fly with flightplan inputted
2input some waypoint and hit HOLD to L1 button on F-PLN
3.MCP's HDG secect mode is locked to NAV(push), cant select HDG(pull) mode.
4.When i disconnect FD and AP,, it seems to be good, but when i re-turn-on Autopilot, Automatically switched to NAV mode even i selected to HDG mode.

**Expected behavior**

easy switching between HDG NAV

**Actual behavior**

Locked to nav

**References**

https://youtu.be/rooaChaU3tY

**Additional context**

Was this working before/when did the issue start occurring?
yes
Is this a problem in the vanilla unmodded game?
yes

Discord username (if different from GitHub):

**Comment by Roboplayer999** [comment]
The issue is included in the following bug report: https://github.com/flybywiresim/a32nx/issues/2089
Please close the issue

**Comment by Benjozork** [comment]
> built: 2020-11-12T02:54:20+00:00

That's pretty old. Can you try the latest dev build ?

**Comment by Roboplayer999** [comment]
You realy hate me

**Comment by Benjozork** [comment]
@Roboplayer999 please do not ask people to close issues, this may not be a duplicate of #2089.

**Comment by cellotako** [comment]
okay though i update, this build_info on my community folder doesnt change. where is the correct directory of build_info?
the software update is correctly workes, the build info cant be updated.

**Comment by cellotako** [comment]
Updated and maybe seems to be good
