### ISSUE TITLE
[BUG] MCDU Can't Clear "ENTER DEST DATA" prompt

### ISSUE THREAD

**Issue by Teslix** [flybywiresim/a32nx#2115]
**Mod Version**
Master - "built": "2020-11-27T05:59:37+00:00"

**Describe the bug**
The new-ish feature of the MCDU displaying "ENTER DEST DATA" is a great reminder to fill out the appr phase data, but sometimes this cannot be done until approaching the dest airport and getting the ATIS. Once the message is cleared, it should not come back. Currently, it re-displays every few seconds after clearing it from the panel.

**To Reproduce**
1. Initialize the MCDU, set to/from airports.
2. Do not set any data for the QNH/Winds/Temp in the Appr Perf Page
3. Watch the warning show up, clear it, it will come back.

**Expected behavior**
Message should be displayed once and not return once cleared.

**Actual behavior**
Message keeps coming back after clearing it.

**References**
N/A

**Additional context**
N/A

Was this working before/when did the issue start occurring?
Wasn't implemented until recently I believe.

Is this a problem in the vanilla unmodded game?
Not modelled in vanilla.

Discord username (if different from GitHub):
Teslix#8746

**Comment by Roboplayer999** [comment]
You need to enter the Temp, wind and qnh of the arrival airport

**Comment by beheh** [comment]
> You need to enter the Temp, wind and qnh of the arrival airport

I think the PR author is aware of that, yet:

> sometimes this cannot be done until approaching the dest airport and getting the ATIS

I doubt the real aircraft shows the message again and again if you clear it. My guess would be some logic so it's only showed once per flight (unless you divert to the alternate), and maybe it reappears at the start of DESCENT and the APPR phase, but we'll need to get some pilot feedback for this. The documentation I've seen does not specify exactly if it only shows once or what retriggers it.

**Comment by Roboplayer999** [comment]
It gets triggered 180 nm's before the destination until you enter the values

**Comment by Roboplayer999** [comment]
If you don't want to enter them, just give random values

**Comment by beheh** [comment]
I'm aware of the conditions that trigger this message (it was added in #2009). That is not the point of this report though: As the author mentions, in some cases you might not just quite have the ATIS yet or maybe you're considering a diversion and are just holding over some other airport. In that case you might want to clear the message, and it probably should not come back immediately like it does right now (currently there's just a `setInterval` check every few seconds).

I would guess there is an inhibit behaviour in the real aircraft to prevent it from showing up again and again, the question is what resets it though.

**Comment by Roboplayer999** [comment]
On the performance page

**Comment by Roboplayer999** [comment]
I just talked to a real pilot, he says that the pop up should not come back after you press clr
