### ISSUE TITLE
[BUG] APU can’t start on batteries alone

### ISSUE THREAD

**Issue by amsomers** [flybywiresim/a32nx#2116]
**Mod version**
Master

**Describe the bug**
APU can’t be started whilst on batteries only.

**To reproduce**

1. Switch both batteries on
2. Do not use external power.
3. Try and start the APU

**Expected behavior**
IRL APU can be started whilst on batteries.

**Actual behavior**
Nothing happens

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Never worked as far as I know

Is this a problem in the vanilla unmodded game?
Yes

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Please provide contents of the `build-info.json` as required in the template.

Also, are you using any other mods ?

**Comment by hotshotp** [comment]
Cannot reproduce, make sure you are using the installer when getting the mod

**Comment by Teslix** [comment]
Cannot reproduce as well, my APU starts up fine (after the minute or so of time it takes to spool up) while on batteries.

**Comment by lukecologne** [comment]
Also not able to reproduce. You need to wait for the flap to open, and after that is done, you need to wait for the turbine to spool up, it just takes a bit of time. If it still doesn't work, please comment here again

**Comment by hotshotp** [comment]
Try using the latest master also, after pressing the master switch and the starter button you should hear two soft clunks after about 5-7 seconds. That's the flap opening. Then later you should hear them again, this happens when apu reached 55% N1. So just wait until it starts up

**Comment by amsomers** [comment]
Apologies, it was merely my impatience that caused me to believe the APU was not starting. The initial sounds are so faint that it seemed nothing happened. It is working fine. Sorry for wasting everyone’s time

**Comment by hotshotp** [comment]
> Apologies, it was merely my impatience that caused me to believe the APU was not starting. The initial sounds are so faint that it seemed nothing happened. It is working fine. Sorry for wasting everyone’s time

haha, no problem at all :) enjoy the mod!
