### ISSUE TITLE
[BUG] Cannot add approach to flight plan

### ISSUE THREAD

**Issue by Moimemeicimeme** [flybywiresim/a32nx#2120]
**Mod Version**
 Stable version from the installer
v0.4.1

**Describe the bug**
At any time in the flight when I click on the destination airport in the F-PLN page to set an approach I get a "not in the database".  The MS original A320 works fine.

**To Reproduce**

1.Load and fly a flight plan without any approach defined (automatic approach)
2.Go to the F-PLN screen and click on the destination airport.
3.

**Expected behavior**
When clicking next to the destination airport on the F-PLN page the The "Last modification from DEST" page" appears, with the option to click on "Arrival" to select the approach, such as ILS.

**Actual behavior**
"Not in the database" appears at the bottom of the F-PLN page along with the option to tmpy erase or tmpy insert.

**References**

![A32NX](https://user-images.githubusercontent.com/70328925/100521397-67f35d80-3171-11eb-8533-102dfe634bb6.PNG)
![Native A320](https://user-images.githubusercontent.com/70328925/100521403-6e81d500-3171-11eb-9a1f-1cd9ee27a8a7.PNG)
[F-PLN.zip](https://github.com/flybywiresim/a32nx/files/5610957/F-PLN.zip)

**Additional context**
The folders "community" and "Official" are not in the default filepath but in a different folder.

Was this working before/when did the issue start occurring? Yes with earlier versions of MSFS or A32NX, not sure which.  Problem is recent.

Is this a problem in the vanilla unmodded game? I have the latest update of the game.  This does not happen with the native version of the A320.

Discord username (if different from GitHub): Dabalou

**Comment by MisterChocker** [comment]
can you please check if this bug is still present in the latest master?

**Comment by Moimemeicimeme** [comment]
Good day DerL30N,
I just flew with the stable version and then the development version (both
via the installer).  The stable version has the same bug but the
development version worked perfectly.
I am ecstatic.  I love your version of the A320.  My preferred plane by a
million nautical miles.

Many thanks to the team.

Daniel

**Comment by MisterChocker** [comment]
Closing since seems to work fine
