### ISSUE TITLE
Cold & Dark + Slew Mode

### ISSUE THREAD

**Issue by CapStar362** [flybywiresim/a32nx#2123]
starting a flight with cold and dark status,  going to Slew Mode,  getting airborne and returning to normal flight causes the Engine Selectors to remain in the "OFF" Position.   this causes permanent erroneous EICAS and MASTER WARNING alerts throughout the flight, and cannot be cleared even if moving the Engine Selectors to the "ON" Positions.  the only way to clear them is to shutdown the entire electrical system and reboot the entire cockpit. 

shutting down the aircraft by moving the selectors back to the "OFF" position is disabled,  shutting down the fuel pumps is also non-effective in this sequence of events. 

just a report for anyone who slews around at first and then jumps into the air and returns to normal flight from a cold and dark status.

**Comment by Benjozork** [comment]
Please follow the issue template
