### ISSUE TITLE
[BUG] Engine masters at OFF after slewing from C&D

### ISSUE THREAD

**Issue by CapStar362** [flybywiresim/a32nx#2124]
**Mod Version**

Stable version from the installer v0.4.1

**Describe the bug**

if you start a flight with the cold and dark status instead of ready on a runway,  toggling slew mode and position yourself airborne then return to normal flight the engine selector switches remain in the "OFF" position but the aircraft is powered and in flight. this causes multiple and repeated EICAS and MASTER WARN alerts to occur and pilot is unable to clear them normally.  Pilot will be unable at this point to shutdown the engines also by any manner possible. 

**Expected behavior**

Engine Selectors should be moved to "ON" position when switching from slew to normal flight if they are off, preventing EICAS and master warn alerts repeatedly activating. 

**Additional context**

Engines cannot be shut down in any method including fuel starvation, shutting down fuel pumps and/or toggling Engine Selectors to "OFF" from the "ON" position in normal procedure. 

the only way to stop the EICAS and MASTER WARN alerts is to completely cut-off all electrical and cold boot the cockpit with the engine selectors ON.  otherwise,  constant alerts pop up throughout flight indicating dual engine failure,  HYD Fail and Bleed Air Alerts. 

however, even if you cold boot the cockpit electrically you are still completely unable to shutdown the engines by any method including Selectors moved to "OFF" position.  Fuel Pumps shut down on all tanks and X-Feed Off.  setting fuel in weights menu to zero or exhausting fuel supply. 

untested against the default A320. 

Discord username (if different from GitHub):

**Comment by hotshotp** [comment]
I mean what's the point of fixing this, to be honest, slew mode shouldn't override everything, and in general it's not that critical of an issue since it's slew mode. Why would you want to slew from cold and dark anyway

**Comment by CapStar362** [comment]
i was just messing around with the sim looking at new scenery ( ImagineSim KATL ) and discovered this.  sure its a one of a kind fluke, but i assure you,  it does cause problems.

**Comment by sidnov** [comment]
As hotshot mentioned above, Slew Mode should only be used to move the physical position of the aircraft, and not influence the position of switches or the state of systems for that matter. There are specific FLT files which define these flight states (for example, spawning on approaches, runway- ready for takeoff state, cruise, etc)
