### ISSUE TITLE
[BUG] A32NX_Downloader  not work

### ISSUE THREAD

**Issue by JLD95** [flybywiresim/a32nx#2126]
**Mod Version**

v0.7

**Describe the bug**

Downloader don't want install A320NX mod because it mistakenly thinks that MSFS is started

Error displayed
![2020-11-29 (3)](https://user-images.githubusercontent.com/5894146/100535667-3b941b80-321b-11eb-8271-c8ac20bd1406.png)

Windows task manager: no FlightSimulator.exe  is listed

![2020-11-29 (4)](https://user-images.githubusercontent.com/5894146/100535792-53b86a80-321c-11eb-98a9-cf7345562e16.png)

However the result of  tasklist cmd show 2 FLightSimulator.exe with old session, none for actual session (0) :

	Line 119: FlightSimulator.exe          10600                            2        40 Ko
	Line 124: FlightSimulator.exe           9296                            4        40 Ko

Nom de l’image                 PID Nom de la sessio Numéro de s Utilisation
========================= ======== ================ =========== ============
System Idle Process              0 Services                   0         8 Ko
System                           4 Services                   0    10 124 Ko
Registry                       172 Services                   0    90 928 Ko
smss.exe                       624 Services                   0       960 Ko
csrss.exe                      868 Services                   0     5 300 Ko
wininit.exe                    968 Services                   0     6 880 Ko
services.exe                   684 Services                   0    13 732 Ko
lsass.exe                      716 Services                   0    24 972 Ko
svchost.exe                   1152 Services                   0     2 644 Ko
svchost.exe                   1176 Services                   0    34 552 Ko
fontdrvhost.exe               1184 Services                   0     3 700 Ko
WUDFHost.exe                  1204 Services                   0     6 740 Ko
svchost.exe                   1272 Services                   0    19 468 Ko
svchost.exe                   1320 Services                   0     8 720 Ko
svchost.exe                   1552 Services                   0    18 924 Ko
svchost.exe                   1596 Services                   0     8 308 Ko
svchost.exe                   1604 Services                   0     9 104 Ko
svchost.exe                   1612 Services                   0    11 196 Ko
svchost.exe                   1720 Services                   0     9 348 Ko
svchost.exe                   1760 Services                   0     5 544 Ko
svchost.exe                   1784 Services                   0     7 032 Ko
svchost.exe                   1976 Services                   0    11 924 Ko
svchost.exe                    964 Services                   0    16 376 Ko
NVDisplay.Container.exe       1484 Services                   0    19 392 Ko
svchost.exe                   1960 Services                   0     8 872 Ko
svchost.exe                   2076 Services                   0    15 384 Ko
svchost.exe                   2088 Services                   0    10 448 Ko
svchost.exe                   2196 Services                   0     4 800 Ko
svchost.exe                   2200 Services                   0    12 776 Ko
svchost.exe                   2212 Services                   0     6 920 Ko
svchost.exe                   2308 Services                   0    10 200 Ko
Memory Compression            2408 Services                   0    23 152 Ko
svchost.exe                   2476 Services                   0     7 512 Ko
svchost.exe                   2536 Services                   0     5 688 Ko
svchost.exe                   2552 Services                   0     7 648 Ko
svchost.exe                   2564 Services                   0     6 880 Ko
svchost.exe                   2768 Services                   0     6 572 Ko
svchost.exe                   2812 Services                   0     9 108 Ko
svchost.exe                   2944 Services                   0     8 876 Ko
svchost.exe                   3012 Services                   0    20 956 Ko
svchost.exe                   3148 Services                   0     8 704 Ko
svchost.exe                   3156 Services                   0     6 672 Ko
svchost.exe                   3416 Services                   0     7 516 Ko
svchost.exe                   3660 Services                   0    15 228 Ko
svchost.exe                   3796 Services                   0     5 708 Ko
svchost.exe                   3804 Services                   0    17 452 Ko
svchost.exe                   3812 Services                   0     8 952 Ko
svchost.exe                   3820 Services                   0    20 396 Ko
vsmon.exe                     3992 Services                   0    55 768 Ko
svchost.exe                   4084 Services                   0    11 636 Ko
WmiPrvSE.exe                  4072 Services                   0    10 056 Ko
WmiPrvSE.exe                  3104 Services                   0    26 356 Ko
svchost.exe                   4160 Services                   0     6 056 Ko
svchost.exe                   4196 Services                   0    13 820 Ko
dasHost.exe                   4204 Services                   0    19 344 Ko
spoolsv.exe                   4252 Services                   0    16 104 Ko
svchost.exe                   4288 Services                   0    18 980 Ko
svchost.exe                   4312 Services                   0     7 188 Ko
svchost.exe                   4556 Services                   0     7 132 Ko
svchost.exe                   4560 Services                   0     6 460 Ko
armsvc.exe                    4720 Services                   0     5 160 Ko
svchost.exe                   4732 Services                   0     4 732 Ko
svchost.exe                   4740 Services                   0    36 188 Ko
nssm.exe                      4752 Services                   0     5 644 Ko
svchost.exe                   4760 Services                   0    10 028 Ko
svchost.exe                   4768 Services                   0    45 332 Ko
MSI_Central_Service.exe       4776 Services                   0    16 324 Ko
nvcontainer.exe               4784 Services                   0    40 112 Ko
svchost.exe                   4792 Services                   0     5 432 Ko
svchost.exe                   4800 Services                   0    12 116 Ko
ICM-Service-NET.exe           4808 Services                   0    38 836 Ko
EFRService.exe                4816 Services                   0   157 952 Ko
MsMpEng.exe                   4824 Services                   0   676 080 Ko
RtkAudUService64.exe          4832 Services                   0     9 756 Ko
svchost.exe                   4840 Services                   0    22 036 Ko
Agent.exe                     4848 Services                   0    29 772 Ko
ZAARUpdateService.exe         4860 Services                   0    27 372 Ko
OfficeClickToRun.exe          4888 Services                   0    65 796 Ko
expressvpnd.exe               5216 Services                   0    35 740 Ko
svchost.exe                   5276 Services                   0    11 744 Ko
svchost.exe                   5396 Services                   0     5 244 Ko
conhost.exe                   5416 Services                   0    11 656 Ko
svchost.exe                   5420 Services                   0     8 856 Ko
NisSrv.exe                    7428 Services                   0    16 788 Ko
GamingServicesNet.exe         7552 Services                   0     3 932 Ko
svchost.exe                   7772 Services                   0    12 836 Ko
vds.exe                       7952 Services                   0    11 500 Ko
WmiPrvSE.exe                  8148 Services                   0    10 264 Ko
dllhost.exe                    760 Services                   0    10 064 Ko
svchost.exe                   7576 Services                   0     8 384 Ko
svchost.exe                   3896 Services                   0    14 100 Ko
svchost.exe                   3516 Services                   0    20 120 Ko
svchost.exe                   8412 Services                   0     7 148 Ko
svchost.exe                   8632 Services                   0    20 268 Ko
MSI.CentralServer.exe         8888 Services                   0    32 484 Ko
conhost.exe                   8932 Services                   0     9 460 Ko
GoogleCrashHandler.exe        9420 Services                   0     1 072 Ko
GoogleCrashHandler64.exe      9524 Services                   0       252 Ko
SearchIndexer.exe             9804 Services                   0    75 996 Ko
SecurityHealthService.exe    11796 Services                   0    20 108 Ko
svchost.exe                   4228 Services                   0    33 492 Ko
SBACipollaSrvHost.exe        15820 Services                   0    59 920 Ko
RemediationService.exe        8520 Services                   0    51 920 Ko
SgrmBroker.exe                7000 Services                   0     9 720 Ko
svchost.exe                  12448 Services                   0    11 156 Ko
TESvc.exe                     9016 Services                   0   119 972 Ko
svchost.exe                   9480 Services                   0    22 312 Ko
svchost.exe                  13404 Services                   0    12 008 Ko
svchost.exe                   9776 Services                   0    10 244 Ko
svchost.exe                  12436 Services                   0    10 620 Ko
regsvr32.exe                  2060 Services                   0     1 736 Ko
FlightSimulator.exe          10600                            2        40 Ko
PushbackHelper.exe           10704                            2        32 Ko
svchost.exe                   1916 Services                   0    12 112 Ko
PushbackHelper.exe           14528                            3        32 Ko
PushbackHelper.exe            2052                            5        32 Ko
FlightSimulator.exe           9296                            4        40 Ko
PushbackHelper.exe            5424                            6        28 Ko
svchost.exe                   5896 Services                   0    11 844 Ko
svchost.exe                   9788 Services                   0    11 044 Ko
csrss.exe                     1716 Console                    9     6 280 Ko
winlogon.exe                  7800 Console                    9    11 008 Ko
fontdrvhost.exe              14228 Console                    9     9 620 Ko
dwm.exe                       2960 Console                    9    91 500 Ko
NVDisplay.Container.exe      17112 Console                    9    64 420 Ko
nvcontainer.exe               5640 Console                    9    52 424 Ko
sihost.exe                    2460 Console                    9    29 584 Ko
svchost.exe                   9392 Console                    9    27 960 Ko
svchost.exe                  20012 Console                    9    37 008 Ko
taskhostw.exe                 4144 Console                    9    19 276 Ko
explorer.exe                  3760 Console                    9   160 904 Ko
svchost.exe                   5304 Console                    9    23 644 Ko
NVIDIA Web Helper.exe         6416 Console                    9     2 632 Ko
conhost.exe                  12376 Console                    9       408 Ko
StartMenuExperienceHost.e    12544 Console                    9    85 700 Ko
RuntimeBroker.exe            11620 Console                    9    26 808 Ko
SearchApp.exe                18036 Console                    9   193 876 Ko
RuntimeBroker.exe            16216 Console                    9    42 388 Ko
SettingSyncHost.exe          11044 Console                    9     6 256 Ko
ctfmon.exe                   16992 Console                    9    26 032 Ko
LockApp.exe                   7196 Console                    9    55 452 Ko
RuntimeBroker.exe            16220 Console                    9    22 660 Ko
RuntimeBroker.exe             9488 Console                    9    31 772 Ko
svchost.exe                   7648 Services                   0     5 900 Ko
YourPhone.exe                11492 Console                    9    15 216 Ko
TodoBackupService.exe         1056 Console                    9    14 044 Ko
RuntimeBroker.exe            15276 Console                    9     9 112 Ko
SecurityHealthSystray.exe     8224 Console                    9     9 544 Ko
RtkAudUService64.exe         13468 Console                    9    12 244 Ko
Yoke_Profiler.exe            11248 Console                    9    58 128 Ko
RudderPedals_Profiler.exe     1956 Console                    9    57 876 Ko
OneDrive.exe                 19172 Console                    9    89 752 Ko
ApplicationFrameHost.exe      9696 Console                    9    32 648 Ko
WinStore.App.exe             15120 Console                    9     5 916 Ko
RuntimeBroker.exe            18164 Console                    9    26 576 Ko
Discord.exe                   3864 Console                    9    78 288 Ko
Discord.exe                  14836 Console                    9   119 832 Ko
CorsairLink4.exe             12304 Console                    9   103 720 Ko
Discord.exe                   1120 Console                    9    42 268 Ko
CorsairLink4.Service.exe     18816 Services                   0    67 832 Ko
Discord.exe                  19252 Console                    9    52 092 Ko
ExpressVPN.exe                3620 Console                    9   103 544 Ko
Discord.exe                   8436 Console                    9   280 572 Ko
Discord.exe                   9996 Console                    9    57 424 Ko
lightway.exe                  5636 Services                   0     7 024 Ko
ZAAR.exe                     19480 Console                    9    76 852 Ko
TrayProcess.exe              16360 Console                    9    30 220 Ko
SystemSettings.exe            2904 Console                    9     4 520 Ko
ShellExperienceHost.exe      12828 Console                    9    60 836 Ko
RuntimeBroker.exe            16004 Console                    9    24 396 Ko
ExpressVPNNotificationSer    12252 Console                    9    62 800 Ko
FileCoAuth.exe                9304 Console                    9    22 820 Ko
svchost.exe                  12836 Console                    9    12 912 Ko
TextInputHost.exe            15244 Console                    9    51 440 Ko
UserOOBEBroker.exe           19276 Console                    9     9 140 Ko
steam.exe                    13092 Console                    9    86 272 Ko
steamwebhelper.exe           11468 Console                    9    62 616 Ko
SteamService.exe             16628 Services                   0    13 712 Ko
steamwebhelper.exe           13332 Console                    9    14 508 Ko
steamwebhelper.exe           18704 Console                    9    67 012 Ko
steamwebhelper.exe           14860 Console                    9    27 692 Ko
steamwebhelper.exe           19540 Console                    9    45 716 Ko
steamwebhelper.exe           15824 Console                    9   129 392 Ko
steamwebhelper.exe           15216 Console                    9    96 200 Ko
dllhost.exe                   8672 Console                    9    13 456 Ko
svchost.exe                  19316 Services                   0     6 172 Ko
PushbackHelper.exe            4876 Console                    9        44 Ko
svchost.exe                  17400 Services                   0    12 216 Ko
audiodg.exe                  14788 Services                   0    12 172 Ko
svchost.exe                   3052 Services                   0     8 220 Ko
svchost.exe                  10256 Services                   0     9 264 Ko
smartscreen.exe              17012 Console                    9    23 640 Ko
chrome.exe                   20352 Console                    9   215 504 Ko
chrome.exe                   10156 Console                    9     7 108 Ko
chrome.exe                    2520 Console                    9   147 476 Ko
chrome.exe                   14648 Console                    9    33 416 Ko
chrome.exe                   15604 Console                    9    14 872 Ko
chrome.exe                   18500 Console                    9    83 688 Ko
chrome.exe                   16900 Console                    9   117 084 Ko
chrome.exe                     288 Console                    9    38 528 Ko
chrome.exe                   19416 Console                    9    86 808 Ko
cmd.exe                       6784 Console                    9     4 364 Ko
conhost.exe                  11272 Console                    9    12 672 Ko
expressvpn-browser-helper    10276 Console                    9    14 196 Ko
chrome.exe                   14888 Console                    9   101 144 Ko
A32NX_Downloader.exe           260 Console                    9     4 896 Ko
A32NX_Downloader.exe         16648 Console                    9    37 864 Ko
chrome.exe                    3604 Console                    9   137 996 Ko
chrome.exe                   10120 Console                    9    49 644 Ko
chrome.exe                   16764 Console                    9    22 068 Ko
chrome.exe                   19500 Console                    9    15 024 Ko
backgroundTaskHost.exe        8448 Console                    9    29 960 Ko
SearchProtocolHost.exe       14048 Services                   0    16 368 Ko
SearchFilterHost.exe          2728 Services                   0     9 808 Ko
explorer.exe                 18876 Console                    9    65 216 Ko
svchost.exe                  13132 Services                   0    17 680 Ko
svchost.exe                  11440 Services                   0     7 836 Ko
svchost.exe                   9676 Services                   0     7 944 Ko
cmd.exe                       2064 Console                    9     4 656 Ko
conhost.exe                  12872 Console                    9    19 300 Ko
tasklist.exe                  5292 Console                    9     9 316 Ko

**Comment by NathanInnes** [comment]
Please post your issue here instead, this REPO is for the aircraft specifically. The installer repo can be found here: https://github.com/Externoak/A32NX-installer
