### ISSUE TITLE
Landing callouts are wrong

### ISSUE THREAD

**Issue by lemansgarcia** [flybywiresim/a32nx#2129]
**Master 0.4.1**

When I land with the a320neo with this mod, I always listen the landing callouts ("five hundred" "Four hundred" "Three hundred"...) But there is a "sixty" callout that shouldn't exist, also I don't listen the "ten" callout. I only listen the "five" Callout.

**To Reproduce**

1. Land and listen all the callouts 

They shouldn't sound the callout "sixty" And should sound the callout "ten".

They sound a callout that they don't exist in realife ("sixty" Callout) and they don't sound a callout ("ten" Callout).

In game video: https://s5.aconvert.com/convert/p3r68-cdx67/c3llc-s3x02.mp4
Real life (how should would be) (landing at minute 3:14): https://youtu.be/b7YfxSxJWzs

**Additional context**

A few months before, you solved this, but they returned to be bugged

Is this a problem in the vanilla unmodded game? 
Yes

Discord username (if different from GitHub): lemansgarcia#5497

**Comment by lukecologne** [comment]
> Master 0.4.1

You are using 0.4.1, not master. This has been changed in master already.
