### ISSUE TITLE
FBW should be trajectory stabilised, not pitch stabilised 

### ISSUE THREAD

**Issue by toffee2000** [flybywiresim/a32nx#213]
The Airbus FBW maintains flight path, not pitch. This means that if stick is neutral, the aircraft will maintain a constant flight path angle and pitch up or down to achieve it. Slowing the aircraft in level flight should result in pitch increasing while FPA stays at 0. Config changes should also, after initial disturbance, result in no change in FPA.

**Comment by ko-zone** [comment]
Hi, 

We have recently begun the tedious task of the FBW system, more updates on that will come soon.

Regards,
KO
