### ISSUE TITLE
[BUG] INSERT TITLE HERE

### ISSUE THREAD

**Issue by mcm71288** [flybywiresim/a32nx#2132]
**Mod Version**

**Describe the bug**
 GPS primary will not align says Gps primary lost 

**To Reproduce**

1. Align ADIR know to align 
2. Align on ref mcdu 
3. Take off activate autopilot try selected heading or managed.

**Expected behavior**
 the gps should align and gps primary should not be lost plane should follow autopilot whether it’s selected hdg or managed to follow flight plan.

**Actual behavior**
 aircraft made a sharp right turn and lost altitude when it was suppose to be in a climb. Aircraft did not follow flight plan at all under managed hdg I tried to put selected hdg and nothing happened.

**References**
 

Was this working before/when did the issue start occurring? Just started today out of nowhere never did this before. Tried to re install a32nx still no good.

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by ZigTag** [comment]
mcm, I would just like to mention that this issue is already known

**Comment by mcm71288** [comment]
Sorry about not following the template first time writing on here . Ty for the response.
