### ISSUE TITLE
[BUG] Displays blurred in A320 Stable Mod 0.4.1 after new Installation of FS2020

### ISSUE THREAD

**Issue by SM-396** [flybywiresim/a32nx#2141]
**Mod Version**
0.4.1

**Describe the bug**
All of the Displays are blurred . Only when i completely toom in it becomes sharpen . 

**To Reproduce**
1. Complete Fresh Installation of W10 and also on FS2020 

**Expected behavior**
Before the new Installation of the Sim the Displays looks good. 

**Actual behavior**
blurry Textures in the Displays 
![2020-11-30 20_00_41-Greenshot](https://user-images.githubusercontent.com/50043259/100652740-a6db0c00-3347-11eb-8165-f873d425e273.jpg)

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by hotshotp** [comment]
Make sure you have TAA anti aliasing set and make sure your render scaling is not too far below 100

**Comment by SM-396** [comment]
Hi , 
I check onesmore . I find that the Displays are more pixelatet then before . 
My Settings are : 
<img width="1103" alt="2020-12-07 09_23_49-Microsoft Flight Simulator - 1 11 6 0" src="https://user-images.githubusercontent.com/50043259/101326711-f6e92f80-386d-11eb-9a1c-4a8e63a1b017.png">

I cant use Render Scaling more the 70 because i use an 4K Monitor and then the Sim stutters und  i have too low FPS. 
Before i have with the same Settings no Problems . 

What can or should i change on my Settings ? 
Thanks

**Comment by hotshotp** [comment]
Please go to our discord to discuss individual problems, others don't seem to have this problem. Should be directed into the #help channel.
