### ISSUE TITLE
[BUG] MCDU doesn't load/show ILS freq in latest dev

### ISSUE THREAD

**Issue by vlbreda** [flybywiresim/a32nx#2144]
**Mod Version**
latest dev

**Describe the bug**
When creating a flight plan and selecting an ILS approach, the ILS freq/identifier/course is not displayed in the MCDU. Selecting approach in MCDU doesn't work either for this.

**To Reproduce**

1. Create flightplan in MSFS
2. Start flight
3. Check NAV-RAD page in MCDU

**Expected behavior**
Selected ILS + frequency is shown in MCDU

**Actual behavior**
Selected ILS + frequency is not shown in MCDU

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Yes

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):

**Comment by AdamNZ** [comment]
Confirmed here (it's been like this for a while - though it did work properly in earlier builds).
NOTE: There's also a formatting issue - LS should be ILS <??>.

**Comment by Steven0785** [comment]
Same here! Dont fill in course and frequency

**Comment by vlbreda** [comment]
Seems to be fixed in the latest dev (dec 1 13.00 CET), thanks! And a massive thank/respect for fixing the AP issue!!

**Comment by beheh** [comment]
> NOTE: There's also a formatting issue - LS should be ILS .

LS is correct (like on the FCU). It's the supercategory to which ILS belongs.
![image](https://user-images.githubusercontent.com/929769/100746692-56b08800-33e1-11eb-9408-490a583fabc6.png)

**Comment by AdamNZ** [comment]
Ah ... OK ... thanks! It's still not auto-filling it though ... is that the correct behaviour?

This was using the latest DEV build:
{
  "built": "2020-12-01T17:45:57+00:00",
  "ref": "",
  "sha": "",
  "actor": "DerL30N <leon.beeser@yahoo.de>",
  "event_name": "manual"
}

**Comment by beheh** [comment]
Are you near the final destination and in the air, or still on the ground when checking the RADIO NAV page? 

The documentation for Landing System Tuning says:

![RADIO NAV](https://user-images.githubusercontent.com/929769/100846420-c6288500-347e-11eb-9d0c-93a30298565e.png)

**Comment by AdamNZ** [comment]
> Are you near the final destination and in the air, or still on the ground when checking the RADIO NAV page?
> ...so it won't tune earlier in flight. In fact, before takeoff it would usually tune the localizer of the takeoff runway if available, but I don't think we have that yet. In any case the landing runway would probably never be tuned on the ground before takeoff according to the conditions here.

I've been doing a lot of circuits whilst testing progress on the a/p bug(s) - taking off and landing from NZWN. The flight plan is either pre-programmed in the FS launch screen or manually in the MCDU. Neither method works - as far as the auto-tuning the ILS. I never go more than 50nm from NZWN - and have tried checking RAD/NAV at all stages of the flight (including on the ground). As I said - this *used* to work in previous builds.

**Comment by LoungeFlyZ** [comment]
I tried this with the latest dev KSEA -> KSEA 16L ILS approach and it turned 110.3 correctly.  @AdamNZ does that route work for you?  (also hi from a fellow kiwi)

**Comment by AdamNZ** [comment]
Many thanks, Chris - you nailed it! I removed all my community/scenery add-ons for NZWN and it all worked perfectly.

As soon as I find out the culprit, I'll post it here - but it does look like we might be able to close this one off :)

**Comment by MisterChocker** [comment]
So this issue is related to 3rd party changes?

**Comment by 2hwk** [comment]
There were previously known issues linked with 3rd party or deluxe content airports. Sounds like the same issue.

**Comment by Awemeter** [comment]
I believe earlier in the sims development it was not possible to include ILS data in the add on which means it will not auto fill. You will need to open a chart or use an application that can be found on flightsim.to to find the freq for that airport.

**Comment by MisterChocker** [comment]
No issue on latest master.
![image](https://user-images.githubusercontent.com/1857322/104447419-10337900-559c-11eb-9b4e-122db74cb58a.png)
