### ISSUE TITLE
[BUG] HDG MANAGED OR SELECTED NOT WORK WITH LAST RELELASE OR MASTER BUILD

### ISSUE THREAD

**Issue by lorenlan** [flybywiresim/a32nx#2145]
**Mod Version**

**Describe the bug**
THE HDG NOT WORK WHEN SELECTED OR MANAGED 

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by tareksabet** [comment]
Please follow the template to be able to help you closing now
