### ISSUE TITLE
Managed flight plan altitude constraints not followed

### ISSUE THREAD

**Issue by nabil74** [flybywiresim/a32nx#215]
Entered flight plans into the MCDU.  Managed heading / altitude and speed mode and autopilot active. HOwever flight plan flight plan altitude constraints are not followed by autopilot.

**Comment by Curtis-VL** [comment]
Maybe an Asobo bug? Not sure if we have access to the code to fix issues like this right now!

**Comment by lousybyte** [comment]
Seems to be fixed on base game now.
