### ISSUE TITLE
[BUG] Autobrakes doesn`t work as expected after landing

### ISSUE THREAD

**Issue by dadavid77** [flybywiresim/a32nx#2150]
**Mod Version**
{
  "built": "2020-11-30T19:03:43+00:00",
  "ref": "",
  "sha": "",
  "actor": "Will Pine <wpine215@gmail.com>",
  "event_name": "manual"
}

**Describe the bug**
When landing on a runway, the airplane will completly stop when the autobrakes are set (lo+med -> max can not be deployed while in the air). After the airplane stopped it is not possible to deactivate the autobrakes (autobrake lights disappear, but brakes are still active). Can not move the airplane anymore (any thrust). Happened the last 2 flights (latest dev incl. autopilot bank fix). After the plane stopped on the runway i was able to set autobrakes to max again... but still have the issue that the break will not be released

**To Reproduce**
1. Activate autobrakes while in the air (low-med), max is not working while in the air
2. Land 
3. Try to deaktivate 

**Expected behavior**
Autobrakes should be deaktivated and brakes should be released.

**Actual behavior**
Please have a look into the description

**References**
![image](https://user-images.githubusercontent.com/75276225/100670458-2f18db80-335f-11eb-9a71-9483efbc5e3b.png)

**Comment by hotshotp** [comment]
You can remove them by doing manual braking. Irl, at 80 or 70 knots, you disengage thrust reversers and use manual braking which disengages the auto take. AFAIK this is how the real plane behaves

**Comment by dadavid77** [comment]
@hotshotp 
Thats the way how i do it 99,999% ;-) In this case, no way to release the brakes even if i break manually after 80knots or other speeds.

**Comment by hotshotp** [comment]
> @hotshotp 
> Thats the way how i do it 99,999% ;-) In this case, no way to release the brakes even if i break manually after 80knots or other speeds.

Ah okay, haven't flown much so I can't comment, it used to work for me

**Comment by vstaritz** [comment]
couldn't replicate with the fixed AP build. Have you tried updating or reinstalling ?

**Comment by hotshotp** [comment]
Try reinstalling the master version and make sure you are using the installer

**Comment by donstim** [comment]
Also make sure that you have not inadvertently put the parking brake on.

**Comment by dadavid77** [comment]
Parking brake was not pulled during the last flight.

Reinstalled Version Dev via Installer. Issue solved, but still not able to set max autobreaks during the flight. Light is off, also not shown on EWD

**Comment by lukecologne** [comment]
That is expected, MAX autobrakes cannot be armed in flight.
