### ISSUE TITLE
[Zero Fuel Weight Changeable and in LB and KG] INSERT TITLE HERE

### ISSUE THREAD

**Issue by nhagag** [flybywiresim/a32nx#2151]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**

**References**

**Additional context**

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by lukecologne** [comment]
> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning

**Comment by nhagag** [comment]
I am sure any Airbus fan would like to see this feature added

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by nhagag** [comment]
I like to fly the airbus with variable ZFW, passangers, fuel load etc. It makes flight planning more fun.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
