### ISSUE TITLE
Sounds missing / Init clicks after power up and hydraulic after starting engine 2

### ISSUE THREAD

**Issue by frankkopp** [flybywiresim/a32nx#2156]
**Mod Version**
master
{
  "built": "2020-11-30T01:44:17+00:00",
  "ref": "",
  "sha": "",
  "actor": "Saschl <sascharudolf46@gmail.com>",
  "event_name": "manual"
}

**Describe the bug**
Sounds missing / Init clicks after power up and hydraulic after starting engine 2
Sounds have been there in previous versions

**To Reproduce**
1. Start Cold & Dark.
2. Turn ON Batteries, then ExtP PWR
3. There should be 3 "clicks" (or beeps) to signal initializaiton done - sounds not there any more
4. go on setting up ....
5. Start Engine 2 - after avail hydraulic systems sounds should be heard  sounds not there any more

**Expected behavior**
Sounds should be there as in previous versions

**Actual behavior**
No sounds for these two events

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Yes, worked in previous versions of the mod

Is this a problem in the vanilla unmodded game?
no

Discord username (if different from GitHub): Cdr_Maverick

**Comment by hotshotp** [comment]
The triple clicks have been removed for later implementation in a more complex way as before it just used to be a sound with a delay. The hydraulic init/PTU is no longer heard in the cockpit and only in the cabin
