### ISSUE TITLE
[BUG] Elec ECAM Page displays huge text

### ISSUE THREAD

**Issue by TansyEliot** [flybywiresim/a32nx#2157]
**Mod Version**

2020-11-30T01:44:17+00:00

**Describe the bug**

Elec ECAM, see Actual behavior.

**To Reproduce**

1. Start in cold and dark
2. Turn on external power
3. See Elec ECAM

**Expected behavior**

Clean ELEC screen.

**Actual behavior**

![image](https://user-images.githubusercontent.com/72763559/100681136-dbec5c00-3351-11eb-8715-76cfcbd04680.png)

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Yes. After the latest development update.

Is this a problem in the vanilla unmodded game?
No. 

Discord username (if different from GitHub):

**Comment by tareksabet** [comment]
Do you have any other mods installed ?

**Comment by TansyEliot** [comment]
> 
> 
> Do you have any other mods installed ?
No, just A32NX.

**Comment by ntlgr** [comment]
Have never seen this. With yesterday's master build (after the AP fix was rolled out) I checked the page and it worked fine.

**Comment by LoungeFlyZ** [comment]
Couldn't confirm this either with master branch.  Turned on external power and as soon as the ECAM would let me flipped to ELEC. 

![image](https://user-images.githubusercontent.com/1360936/100936895-0c91da00-34a7-11eb-895c-fe39855c20d3.png)

**Comment by tareksabet** [comment]
@TansyEliot can you try the latest master and confirm it can't be reproduced.
