### ISSUE TITLE
[BUG] Speed dissapears in the FMA when is in approach mode

### ISSUE THREAD

**Issue by mikecbr** [flybywiresim/a32nx#2158]
**Mod Version**
Stable release , latest branch

**Describe the bug**
The speed is right in the all phases of the flight , the bug is when is click the approach buttong to localize the ILS the Speed suddenly dissapears in the FMA until you dissengage the AP thats when it is shown again in the FMA. It also when reappear is shown as mach mode instead of speed.

**To Reproduce**

1.Before land , click approach mode to localize ILS
2.Speed in the FMA will dissapear 
3.It reappears again in the FMA whehn discconect the AP.

**Expected behavior**
shouldnt dissapear at all , also, when dissengage AP  it changes to mach mode instead of speed mode.

**Actual behavior**
Dissapears when click on Approach button and the reappears when autopilot is disconnected , but it appears in mach mode instead of speed.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
NO

Is this a problem in the vanilla unmodded game?
Not sure

Discord username (if different from GitHub):

**Comment by tareksabet** [comment]
Can you upload a screenshot about your issue.

**Comment by LoungeFlyZ** [comment]
I tried this out and don't believe i saw the problem.  I'm on latest dev branch. 

Recording of transition to APPR/LOC mode, grabbed the G/S and LOC and SPEED was still showing:
https://www.dropbox.com/s/g4nl439tk840xo4/2020-12-02_13-43-58.mp4?dl=0

**Comment by mikecbr** [comment]
Yep , working now , @LoungeFlyZ  what has to change is from mach to speed mode , the mach is still active because i had a high FL  (changed by itself to amch mode) once i descent it does not change to speed

**Comment by LoungeFlyZ** [comment]
nice. @mikecbr thx, plz open a new issue for that with repro steps.

**Comment by tareksabet** [comment]
Closing now because it's fixed in latest master.
