### ISSUE TITLE
[BUG] DCDU Buttons Labelled Incorrectly

### ISSUE THREAD

**Issue by AirbusA320Pro** [flybywiresim/a32nx#2159]
**Mod Version**
0.4.1 Master

**Describe the bug**
DCDU buttons incorrectly labelled with Zero's instead of Gs.

**To Reproduce**

1. View DCDU (CPDLC) unit buttons.

**Expected behavior**

Buttons labelled as MSG+/MSG- and PGE+/PGE-
![DCDU](https://user-images.githubusercontent.com/75289637/100692360-92683500-3382-11eb-9559-4ebeb97cd464.jpg)

**Actual behavior**

Buttons labelled as MS0+/MS0- and P0E+/P0E-

**References**

Picture attached of correct labelling.

**Additional context**

Was this working before/when did the issue start occurring?
Unknown

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub): AirbusA320Pro

**Comment by tareksabet** [comment]
It's a known issue from long time but sadly we can't do anything about it. As it requires access to the model files.
