### ISSUE TITLE
Wind data on ND shows up below 100kts IAS 

### ISSUE THREAD

**Issue by mrgpnaccyt** [flybywiresim/a32nx#216]
The wind data on the ND (Top left corner) should only show up above 100kts on the takeoff roll

**Comment by PCGamesF1Tech** [comment]
I was also wondering why I had a wind indication at a parking position somewhere... 🤔

**Comment by AdenFlorian** [comment]
@NathanInnes fix from #227 is now in master, I tested it and it looks good!
