### ISSUE TITLE
[BUG] LAT REV for Arrival Airport Formatting Issue

### ISSUE THREAD

**Issue by AirbusA320Pro** [flybywiresim/a32nx#2160]
**Mod Version**
0.4.1 Master

**Describe the bug**
Lateral revision page for Arrival airfield is formatted incorrectly. MCDU display should not have a FIX INFO for airfield. 
<ARRIVAL (LSK 1L) on the left side should be on the right: ARRIVAL> (LSK 1R)

**To Reproduce**

1. Select Airfield FROM/TO in INIT A
2. Select F-PLN on MCDU
3. Select LSK for Arrival airfield.

**Expected behavior**

No FIX INFO on LAT REV page for arrival airfield.
ARRIVAL> select key should be on the right.
![LAT REV](https://user-images.githubusercontent.com/75289637/100693733-5e424380-3385-11eb-9fb5-14cbdbebe392.jpg)

**Actual behavior**

FIX INFO> displayed on right hand side.
<ARRIVAL dsplayed on left hand side.
![MCDU incorrect](https://user-images.githubusercontent.com/75289637/100693783-7ade7b80-3385-11eb-82d4-5e40534a5505.png)

**References**

Shown in attached images.

**Additional context**

Was this working before/when did the issue start occurring? Unknown

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub): AirbusA320Pro

**Comment by tareksabet** [comment]
Your issue is correct as this is how it should look like
![image](https://user-images.githubusercontent.com/70240330/100705950-c65a4f00-33b0-11eb-9345-f37465f332e7.jpeg)

**Comment by beheh** [comment]
This has already been fixed in dev for a few weeks since #1845, so I believe this bug can be closed.

**Comment by tareksabet** [comment]
So it's fixed on the latest master closing now @beheh thank for commenting.
