### ISSUE TITLE
[BUG] Rudder Trim not displaying or changing

### ISSUE THREAD

**Issue by Road-to-Hell9** [flybywiresim/a32nx#2162]
**Mod Version**
A320NX Master 2020-12-01T04:44:06+00:00

**Describe the bug**
The rudder trim does not display on the screen and does not trim

**To Reproduce**
1.Start on runway
2.Take off
3.Landing runway final
4.Trim rudder

**Expected behavior**
Trim the rudder

**Actual behavior**
Nothing

**Comment by tstopak** [comment]
A few questions:

- Does this work on the vanilla A320? 
- Can you please add reference screenshots? I assume this should be in two places, the flight controls page on the ECAM and the numeric display by the switch used to control the rudder trim.

**Comment by TansyEliot** [comment]
> 
> 
> **Mod Version**
> A320NX Master 2020-12-01T04:44:06+00:00
> 
> **Describe the bug**
> The rudder trim does not display on the screen and does not trim
> 
> **To Reproduce**
> 1.Start on runway
> 2.Take off
> 3.Landing runway final
> 4.Trim rudder
> 
> **Expected behavior**
> Trim the rudder
> 
> **Actual behavior**
> Nothing

It doesn't work with autopilot on, just disengage autopilot.

**Comment by Roboplayer999** [comment]
It somehow works now, thank you all

**Comment by Roboplayer999** [comment]
It somehow works now, thank you all

**Comment by Roboplayer999** [comment]
The issue only appears if you start on the runway, not in a cold and dark
![Screenshot (58)](https://user-images.githubusercontent.com/69807128/100868666-35f93880-349c-11eb-9f54-66724ebe55bd.png)
![Screenshot (59)](https://user-images.githubusercontent.com/69807128/100868676-385b9280-349c-11eb-877d-d374c3e61e74.png)

**Comment by MisterChocker** [comment]
This will work with wip ap
