### ISSUE TITLE
A320 neo always turning left with autopilot ON

### ISSUE THREAD

**Issue by fabmac29** [flybywiresim/a32nx#2166]
**Mod Version**

**Describe the bug**

**To Reproduce**

1. When I set the autopilot ON the plane is always turning left
2. Same issues with the A32NX-master.zip, or the Dev version
[build-info.txt](https://github.com/flybywiresim/a32nx/files/5624496/build-info.txt)

3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Does not respect template. Also, please try setting a deadzone on your controller.

**Comment by monkeh88** [comment]
i dont have deadzone , i have no controllers
