### ISSUE TITLE
[REQUEST] Allow prefill of cruise altitude in MCDU derived from flightplan

### ISSUE THREAD

**Issue by ErikNL80** [flybywiresim/a32nx#2169]
**Is your feature request related to a problem? Please describe.**

When you use the flightplanner, the MCDU is correctly filled with waypoints. In the MCDU you need to set the cruise altitude manually, although this info is known. In the vanilla version this is also prefilled. 

**Describe the feature you'd like to see implemented**

It would be nice to have the option to prefill the altitude on the INIT page in the same way as done with the V speeds.

**References**

**Additional context**

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by theomessin** [comment]
> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning

Feel free to open a new issue **provided you follow the given instructions**.
