### ISSUE TITLE
[BUG] No green dot on PFD for flaps 0 to 1 when speed decreases

### ISSUE THREAD

**Issue by phildeg31** [flybywiresim/a32nx#2173]
**Mod Version**
"built": "2020-12-01T11:54:03+00:00"

**Describe the bug**
The changes from no flaps to flaps 1 position must be done between 2 yellow or brown bars (equal-shaped) and the green dot. But the green dot is not displayed on the PFD (see screenshot). I have the green dot for take off only.

**To Reproduce**
Reduce speed for landing.

**Expected behavior**
The green dot should be displayed.

**Actual behavior**
No green dot on PFD.

**References**
https://zupimages.net/viewer.php?id=20/49/yb7s.jpg

**Comment by MisterChocker** [comment]
What was your ground weight?
Also could you show a picture of the performance page (approach)
Also green dot will only be visible when in clean config aka no flaps or slats set.

**Comment by MisterChocker** [comment]
> The changes from no flaps to flaps 1 position must be done between 2 yellow or brown bars (equal-shaped) and the green dot

yes and no, the green dot is a recommended speed to fly (which ATHR will target when in approach phase and clean config, however Vls is the minimum speed you can actually fly. (Vls stands for lowest selectable speed)

**Comment by MisterChocker** [comment]
This chart shows the relation between vspeeds and gw
![image](https://camo.githubusercontent.com/a2c9fb95a85ea66f6c3d7b349d843399cd0ceee3a9d1b312ee20554117a93d51/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3734393035303239353630363035303839362f3736373135303331323831363930323134342f756e6b6e6f776e2e706e67)

**Comment by phildeg31** [comment]
I configured the approach page as I did in a real a320 simulator with a pilote:
https://zupimages.net/viewer.php?id=20/49/g428.jpg

**Comment by MisterChocker** [comment]
according to your VLS seen in the picture your GW was 68t and the displayed GD on your performance page shows 202 which relates to GW of 58,5t.
Something is wrong here, how are you accessing the data?

**Comment by phildeg31** [comment]
I configured Init, f-pln and perf pages like I did in a real simulator and that's all before take off.

What do you mean by "accessing the data"?

**Comment by MisterChocker** [comment]
The picture you posted of the mcdu.

**Comment by phildeg31** [comment]
The last picture is not from the game but from a real simulator. I set in game some of the values set in that real simulator.

**Comment by MisterChocker** [comment]
Please also show the GW, this helps as reference as well.

**Comment by Watsi01** [comment]
Yeah, had that too. No green dot after flaps 1. GW around 60t. Speed was shown in MCDU appr page (I think it was 206), but no dot on the speed tape.

**Comment by MisterChocker** [comment]
> No green dot after flaps 1

GD only visible in clean config..

**Comment by phildeg31** [comment]
Yes green dot is with no flaps (flaps to 0). After flaps 1 you have -S.

**Comment by Watsi01** [comment]
Ok. Thanks. Didn't know.

**Comment by phildeg31** [comment]
I am doing a test with this configuration:
![Init](https://user-images.githubusercontent.com/74733393/100883324-811d4680-34b0-11eb-9da1-2f25a4a7e5e6.JPG)
![take off](https://user-images.githubusercontent.com/74733393/100883361-8a0e1800-34b0-11eb-960c-dbd662748355.JPG)
![appr](https://user-images.githubusercontent.com/74733393/100883380-909c8f80-34b0-11eb-9a21-ffac542b41fb.JPG)
![flight plan avant decollage 1](https://user-images.githubusercontent.com/74733393/100883417-9a25f780-34b0-11eb-96a7-4029f5546faf.JPG)
![flight plan avant decollage 2](https://user-images.githubusercontent.com/74733393/100883436-9f834200-34b0-11eb-9a09-f69a24074bb0.JPG)

Where is the ground weight please?

**Comment by MisterChocker** [comment]
> Where is the ground weight please?

In the lower right corner of the lower ecam.

![image](https://user-images.githubusercontent.com/1857322/100884777-2c7acb00-34b2-11eb-89b5-006fc281d3ac.png)

**Comment by phildeg31** [comment]
Ok so I have this:
![ground weight](https://user-images.githubusercontent.com/74733393/100885286-c5114b00-34b2-11eb-8ea3-8ff9063d9926.JPG)

**Comment by MisterChocker** [comment]
yes 60.8t

**Comment by phildeg31** [comment]
It is by default no? I did not change that.

**Comment by MisterChocker** [comment]
It shows your current gross weight. A lot of speeds are calculated off of that weight.

**Comment by Watsi01** [comment]
EDIT: have no green dot with flaps 0 (I knew there is something not like before).
![gd](https://user-images.githubusercontent.com/72334392/100886578-4c12f300-34b4-11eb-827c-7de1779262e5.png)

**Comment by phildeg31** [comment]
And it explains why I don't have the green dot?
![image](https://user-images.githubusercontent.com/74733393/100886843-94321580-34b4-11eb-920f-fd4e79b7cc6e.png)

**Comment by MisterChocker** [comment]
No but now I know that there is indeed no green dot..

**Comment by MisterChocker** [comment]
Did you guys checked what the ATHR was doing? did maintained GD speed or did it dropped through?

**Comment by phildeg31** [comment]
Also, is it a known issue about speed decreasing very slowly?

I need a lot of time to reach the target speed and altitude when I ask to decrease altitude and speed:
![speed and altitude](https://user-images.githubusercontent.com/74733393/100887544-613c5180-34b5-11eb-9a56-0b2f89ec9942.JPG)
![speed and altitude 2](https://user-images.githubusercontent.com/74733393/100887580-68fbf600-34b5-11eb-8ae7-aebcb8596997.JPG)
![speed and altitude 3](https://user-images.githubusercontent.com/74733393/100887584-6ac5b980-34b5-11eb-955f-95e9b4eb1b2d.JPG)

**Comment by MisterChocker** [comment]
It will take a bit of time when you try to loose speed while maintaining a vertical speed without using speedbrakes.

**Comment by phildeg31** [comment]
Ok but it takes more time than before and more time than with real a320 simulator when I did actionsat the same moment. I have to start the descent before and I cannot have flaps 2 before alignment.

**Comment by MisterChocker** [comment]
please open a separate issue for that if you feel something is wrong with that.

**Comment by phildeg31** [comment]
Ok. I do not know if it is an expected behaviour if a pilot can confirm... I will open a separate issue for that. Thank you ;).

**Comment by MisterChocker** [comment]
> Ok. I do not know if it is an expected behaviour if a pilot can confirm... I will open a separate issue for that. Thank you ;).

the flight model has been tested by IRL A320 neo pilots.

**Comment by MisterChocker** [comment]
also thank you very much for your feedback, I could spot the bug and a fix is underway.
