### ISSUE TITLE
[BUG] Nose is very up on approach using the calculated Vapp 

### ISSUE THREAD

**Issue by omarsmak** [flybywiresim/a32nx#2177]
**Mod Version**

latest master branch

**Describe the bug**

On approach, using the calculated Vapp speed, the plane's nose will go up close to 10degrees and it will trigger the stall warning. I think this is a result of [this commit ](https://github.com/flybywiresim/a32nx/commit/02da15192f41797214205a35b8ce772003f228ac)to the flight model. 

**To Reproduce**

1. Fly with the same route and the same fuel, payload as this [Simbrief report](https://drive.google.com/file/d/1yMlLsYYJp3Wf22p8F98RtkW5n9Yp4sQG/view?usp=sharing).

**Expected behavior**

The calculated approach speed shouldn't trigger the stall warning nor the plane's nose goes up close to 10 degrees. 

**Actual behavior**

The calculated approach speed is too low that causes the plane nose goes up close to 10 degree's and could trigger the stall warning.

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment]
what was the flaps configuration you flew? what was the vapp calculated by the mcdu? where you flying below Vls speed?

**Comment by omarsmak** [comment]
Hey @MisterChocker, 

It was a full flaps configurations, the calculated speed if I recall was between 139 - 137.  Nope I wasn't flying below VIs speed, I had to dial it up to 155 or more to avoid the stall and reduce the pitch nose. 
Also, I have seen similar report [here](https://www.avsim.com/forums/topic/590774-fbw-a320-approach-speed).

**Comment by MisterChocker** [comment]
Okay could you provide a clip or photos? we need a bit more information to understand what's causing this.

**Comment by omarsmak** [comment]
Sure! The next time I fly, I'd provide a clip or photo. 
Thanks

**Comment by MisterChocker** [comment]
do you remember your GW? Vapp 139kt sounds like over weight landing (GW 75t)

**Comment by MisterChocker** [comment]
can you please provide the context of build_info.json

**Comment by omarsmak** [comment]
Sorry I didn't post it earlier, here is the buld.info:
```
{
  "built": "2020-12-01T11:54:03+00:00",
  "ref": "",
  "sha": "",
  "actor": "DerL30N <leon.beeser@yahoo.de>",
  "event_name": "manual"
}
```
And for the GW, is pretty much like this:
```
ZFW 61.4
Fuel 6.5
Fuel after landing (when I looked at block) ~ 5.4 - 5.6

Therefore:
TOW ~ 68
LAW~ 66
```

I hope this answers your question.

**Comment by lars-reimann** [comment]
Not entirely sure if this has the same cause but the effect you described seems similar: https://youtu.be/MlL3ejMvgH8

I was using selected speed because I had an absurdly high pitch at the managed speed (which was about 130kt if I recall correctly) and was rapidly losing altitude without any elevator control. This still happened at 160kt with full flaps, though, as you can see in the video.

The only thing that seems different to the flights I usually do is that the approach mode is not active (my bad). As the ECAM shows, the elevators are barely moving, so this may as well be an issue with the FBW. I've had this happen a couple of times in the past but not at such high speeds.

Build info:
```
{
  "built": "2020-12-01T17:45:57+00:00",
  "ref": "",
  "sha": "",
  "actor": "DerL30N <leon.beeser@yahoo.de>",
  "event_name": "manual"
}
```

**Comment by MisterChocker** [comment]
Thanks for your feedback, we are looking into this.

**Comment by c1be** [comment]
To me, flight model feels like default one at launch, plane feels like stalling below 150 knots.

**Comment by MisterChocker** [comment]
> To me, flight model feels like default one at launch, plane feels like stalling below 150 knots.

Thanks for that info!

**Comment by MisterChocker** [comment]
Short question to all of you, did you altered the flight_model.cfg file?

**Comment by c1be** [comment]
> Short question to all of you, did you altered the flight_model.cfg file?

In my case no, i just downloaded dev version through installer.

**Comment by omarsmak** [comment]
Oh no I just used the installer. Did you try the exact route with the same payload and fuel as my simbrief report ?

**Comment by omarsmak** [comment]
Wait a minute, this is the exact behavior of the default Airbus with no mod , isnt ? Could it be the sim took the default flight model file instead of the mod one? I may try again tomorrow with the latest dev , it could be the layout json was corrupted?

**Comment by MisterChocker** [comment]
> Wait a minute, this is the exact behavior of the default Airbus with no mod , isnt ? Could it be the sim took the default flight model file instead of the mod one? I may try again tomorrow with the latest dev , it could be the layout json was corrupted?

thats exactly what I try to figure out right now, to check whats actually going on xD

**Comment by MisterChocker** [comment]
This is with correct flight model
![image](https://user-images.githubusercontent.com/1857322/100916860-a3c25600-34d6-11eb-8bb0-9f2805536234.png)

**Comment by lars-reimann** [comment]
> Short question to all of you, did you altered the flight_model.cfg file?

I did not change the mod either in any way.

**Comment by omarsmak** [comment]
Is there any way if I can check if I am using the correct flight model apart from performing the whole flight ?

**Comment by joniatus** [comment]
I assume you guys are using "modern" flight model setting and not "legacy"?

**Comment by MisterChocker** [comment]
Yes please use the modern flight model. That is needed!

**Comment by omarsmak** [comment]
Yes I am using the modern flight model

**Comment by MisterChocker** [comment]
> Is there any way if I can check if I am using the correct flight model apart from performing the whole flight ?

You could post you flight_model.cfg file. In the meantime I am checking the latest master version via the installer.

**Comment by MisterChocker** [comment]
Sounds like there is an issue with the downloader, do you which server you used?

**Comment by pareil6** [comment]
Just to add a datapoint here - yesterday the plane flew normally, but today (on the same version) it did exactly this. The only difference here was I'd tried using managed speed on two flights today, which I didn't do yesterday. After the second one, I then restarted the engines and did a circuit, and the proper flight model seemed to be back.

Going to try a couple more experiments seeing if using managed speed is doing it, it seems weird but I can't think of any other differences between the flights...

**Comment by MisterChocker** [comment]
I just flew with managed speed and the installer version downloaded via FlyByWire CDN and everything worked fine.

**Comment by pareil6** [comment]
Tried redownloading, seeing if it does the same thing - I had a quick look and the flight_model.cfg was the same between the newly downloaded version and the version I had before (which was the build version listed earlier in the thread). It seems like the mod's flight model was getting replaced slightly randomly by the default one - is there anything else worth checking to make sure it wasn't corrupted?

**Comment by MisterChocker** [comment]
I checked the flight model via downloader and it worked fine.

**Comment by pareil6** [comment]
Retried on newest master build, flight model definitely seems off regardless of what I do (full flaps at 140kts still has the nose at 10deg). I've been downloading from the vmaster build on GitHub, I'll retry with the installer now just in case the GitHub build is somehow going wrong.

**Comment by Watsi01** [comment]
Could you use exatly that link (or did you already):
https://github.com/flybywiresim/a32nx/releases/download/vmaster/A32NX-master.zip

**Comment by pareil6** [comment]
Used exactly that link.

**Comment by Watsi01** [comment]
There is something strange happening, since I didn't experience any of your problems. Last issue could be: did you install it correctly (folder)?

**Comment by Watsi01** [comment]
Maybe you installed it twice, by accident?

**Comment by pareil6** [comment]
Not entirely sure how it would be installed twice - there's no copies of the A32NX folder in the Community folder.

**Comment by c1be** [comment]
I'm not a real pilot, but when i fly FF320 xplane and compare it to a32nx with this new custom flight model, approach speeds are not even close, in order to get 3-5 degree pitch on approach i have to increase my speed by atleast 10 knots compared to FF320 with same weight. It would be nice if some real pilots would review it and give us some inputs, because this is very similar to a default model by Asobo, imo.

**Comment by omarsmak** [comment]
> I'm not a real pilot, but when i fly FF320 xplane and compare it to a32nx with this new custom flight model, approach speeds are not even close, in order to get 3-5 degree pitch on approach i have to increase my speed by atleast 10 knots compared to FF320 with same weight. It would be nice if some real pilots would review it and give us some inputs, because this is very similar to a default model by Asobo, imo.

As @MisterChocker mentioned, I think what we have been flying is not the custom flight model , it looks like is the default flight model from Asobo

**Comment by Watsi01** [comment]
Could you do me a favour and move everything in the community folder to a different place. Then make a fresh install of the A32NX only. Then try it out. (just trying to fing the issue here)

**Comment by MisterChocker** [comment]
@c1be As @omarsmak correctly pointed out, our actual flight model seems not to work for some people. And because of that we are trying to investigate what causes this.

**Comment by MisterChocker** [comment]
I recommend trying a clean installation of the mod (deleting current A32NX folder from your community folder) then redownloading via [this link](https://flybywiresim-packages.nyc3.cdn.digitaloceanspaces.com/vmaster/A32NX-master.zip) or our [installer](https://github.com/Externoak/A32NX-installer/releases/latest/download/A32NX_Downloader.zip) using the `FlyByWire CDG` server (I've tested this one and it worked for me)
![image](https://user-images.githubusercontent.com/1857322/100938280-b481c480-34f4-11eb-8781-d6c461bd06a7.png)

**Comment by omarsmak** [comment]
From my side , I removed the old one and redownload it the latest dev version. It looks to me now is using the correct flight model, for example taxi on idle thrust. However I just didn't really test it intensively, I will perhaps tomorrow try it again by re-doing the same flight again.
Thank you @MisterChocker for the help and tips , highly appreciated!

**Comment by MisterChocker** [comment]
@omarsmak you are welcome, for simplicity you could fly a simple pattern at any airport to check if the flight model works as excepted.

**Comment by c1be** [comment]
Seems to work now, only thing i did differently is changing download
server, from github to cdn.

**Comment by omarsmak** [comment]
Yeah @c1be exactly that what I did. Could it be github cdn the reason? I thought github ci will build the same zip file and then uploaded it to the cdn

**Comment by MisterChocker** [comment]
We don't know yet, anyway our CDN is faster ;p

**Comment by omarsmak** [comment]
Just tested, indeed _somewhat_ it was before using the default flight model and now it is using the custom flight model and flies beautifully! :D 
Thanks a lot again! 
I will close this ticket if you are okay with it :)

**Comment by MisterChocker** [comment]
small update on the situation, we seem to have identified the root cause of this bug.

**Comment by omarsmak** [comment]
> small update on the situation, we seem to have identified the root cause of this bug

Interesting, what was the issue ?

**Comment by MisterChocker** [comment]
sadly we actually haven't found the issue it self, but ruled out one condition where you may have something else installed (maybe a second copy of 320NX) then a wrong flight_model.cfg file is loaded.
Basically it's an false alarm and we actually haven't found the issue yet.

**Comment by c1be** [comment]
In my case, i tried several times deleting everything from community folder
and downloading with installer from github server and every time plane flew
very similar to default flight model, than i deleted it again but this time
i changed download server to cdn and plane behaved as it should. Now, like
i said, only change was different download server, nothing more, didn’t
changed anything in files, didn’t put any other folder in community folder,
nothing. I also watched Cpt Canada stream today and his landing was very
weird, plane was floating a lot, he did approach with higher speed than he
should, but still, it didn’t seem like custom flight model, more like
default one.

**Comment by MisterChocker** [comment]
Small heads up on the issue, we have identified that icing causing these type of issue.
You can see a 700fpm vs in full landing config, after enabling ice effect, the vs increases massively while applying full back stick.

**Comment by omarsmak** [comment]
> Small heads up on the issue, we have identified that icing causing these type of issue.
> You can see a 700fpm vs in full landing config, after enabling ice effect, the vs increases massively while applying full back stick.
> video: https://youtu.be/Y4TlliitIC4

Wow awesome ! Thanks a lot for the investigation. Indeed , it is pretty tricky to identify such issue .

**Comment by MisterChocker** [comment]
We are currently looking into a possible workaround. I'll keep you updated.

**Comment by MisterChocker** [comment]
Alright, a workaround is whenever you encounter high pitch, activate engine + wing anti ice, after ~30 seconds pitch should be normal again.
