### ISSUE TITLE
[BUG] Fuel flow falling to 0 after starting one engine.

### ISSUE THREAD

**Issue by j4nix** [flybywiresim/a32nx#2178]
**Mod Version**

  "built": "2020-12-01T17:45:57+00:00",
  "ref": "",
  "sha": "",
  "actor": "DerL30N <leon.beeser@yahoo.de>",
  "event_name": "manual"

**Describe the bug**

After starting "ENGINE 2" fuel flow suddenly drops to 0.

**To Reproduce**

1. Start up as per usual from C&D.
2. Try and start "ENGINE 2"

**Expected behavior**

After the engine has started up it should retain fuel flow.

**Actual behavior**

After engine has started up, (about the time the "HYD PTU" should start), fuel flow suddenly drops to 0 and consequently, the engine shuts down.

**References**

https://youtu.be/5ScOUWOATMQ

**Additional context**

After downloading the version mentioned above, (via installer), a fuse kept popping in and out in the back of the cockpit, which I think isn't supposed to happen.

These weren't problems before I installed the version mentioned above.

Allthogh I haven't tested this issue in the vanilla A320NEO, I am pretty sure this is not an issue in the vanilla game.

Discord username (if different from GitHub): j4nix.SCG#4161

**Comment by MisterChocker** [comment]
this could be due to the low FOB. I remember issues where engines magically shut down below certain FOB level.

**Comment by j4nix** [comment]
So this seems to be an issue of the vanilla game itself, that when you go under a certain value for fuel, you end up not being able to start the engines.
