### ISSUE TITLE
ECAM and MFD sometimes not readable

### ISSUE THREAD

**Issue by KemalOues** [flybywiresim/a32nx#218]
With full brightness activated, the ECAM and MFD are sometimes not readable when the sun shines on in in some angles. Perhaps this displays need more brightness

**Comment by ArthurHetem** [comment]
Can you take a screenshot when it occurs?

**Comment by Curtis-VL** [comment]
I believe this is an issue with the aircraft's model, sun can shine at just the right angle to hit the displays. Not sure this is something we can fix right now.
Please bring it up in Discord to discuss this further.

**Comment by KemalOues** [comment]
H, here is a sreenshot
![dark](https://user-images.githubusercontent.com/55877319/92300167-026c4800-ef59-11ea-8d5c-cb22f201c634.jpg)

**Comment by NathanInnes** [comment]
Are you still experiencing this issue?

**Comment by NathanInnes** [comment]
Closing issue due to no response.
