### ISSUE TITLE
navigation display shows "gps primary lost" and the other display is just blank with a couple of weird lines

### ISSUE THREAD

**Issue by cookiedough43** [flybywiresim/a32nx#2183]

**Comment by ChruutvoLuzi** [comment]
you need to Align your ADIRS on the overheady panel

**Comment by hotshotp** [comment]
That's the ADIRS. Top left of the overhead panel, but there switches to the middle position. Working as intended

**Comment by mcm71288** [comment]
they added the wait time in I had the same issue looks at your ecam it will show the wait period
