### ISSUE TITLE
[BUG] Predictive GPS 

### ISSUE THREAD

**Issue by Eaglepilot6** [flybywiresim/a32nx#2184]
**Mod Version**
Master

  "built": "2020-12-01T17:45:57+00:00",
  "ref": "",
  "sha": "",
  "actor": "DerL30N <leon.beeser@yahoo.de>",
  "event_name": "manual"

**Describe the bug**
Predictive GPS page character location and spacing is off. 

**To Reproduce**
Everytime

**Expected behavior**
"Y" or "N" values should be displayed directly under the    "-15  -10  -5  ETA  +5  +10 +15"  points. 

**Actual behavior**
Predictive RAIM is bunched as first 2, middle 3,  last 2 characters. Should be evenly spaced under times.  For added realism, the values should start as dashes, and populate one by one at various times as the system checks RAIM for time values. It's very rare to have it display anything other than "Y". 

**References**
![image](https://user-images.githubusercontent.com/70357436/100909179-6344e700-349a-11eb-99b2-9461c9b47a1a.png)

**Additional context**

Was this working before/when did the issue start occurring? No

Is this a problem in the vanilla unmodded game? Not sure this page exists in vanilla. 

Discord username Eaglepilot6

**Comment by pepperoni505** [comment]
Please provide a screenshot from the simulator

**Comment by Eaglepilot6** [comment]
![image](https://user-images.githubusercontent.com/70357436/100913703-2380fe00-34a0-11eb-9ccc-2a614c778301.png)

**Comment by MisterChocker** [comment]
fixed
