### ISSUE TITLE
[BUG] Retard voice loop after landing

### ISSUE THREAD

**Issue by JLD95** [flybywiresim/a32nx#2185]
**Mod Version**

"built": "2020-12-01T17:45:57+00:00"

**Describe the bug**

During flare, I have normal retard voice but I make a very smooth landing, after 2 "retard" messages, I have always the "retard" voice even after landing and during taxiing.

**To Reproduce**

1. During flare, wait 2 messages "retard"
2. After landing and during taxiing, I have this voice in loop. Perhaps this bug is not systematic.
3.

**Expected behavior**

No voice retard after landing

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
I don't know.

**Comment by philw06** [comment]
Same problem for me....

**Comment by Annolago** [comment]
Yes, I have also experienced it on my last flight. Kept repetering for some 20-25 seconds.

**Comment by SierraBravo1** [comment]
I had this issue, too. The Retard callout never stopped, even when the aircraft was unpowered.
The root cause was my throttle lever. It was not 100% in Idle at the lowest position. This was not really visible and the engines were obviously in idle.
Pressing F1 stopped the Retard callout immediately.

**Comment by Sateprikkert** [comment]
Same here, didn't stop looping "retard". Haven't tried @SierraBravo1 suggestion, but it wasn't there before.

...or it's commenting on my landings.

**Comment by lukecologne** [comment]
Working on a fix, will open a PR shortly
