### ISSUE TITLE
AP at cruise start going up at down with SEC1 off

### ISSUE THREAD

**Issue by FabioMike06** [flybywiresim/a32nx#2189]
**Mod Version**

built: 2020-11-10T15:19:38+00:00
ref: refs/heads/master
sha: 6cb5116649c223cba11e7eec6ee39fcba9ecfb68
actor: Benjozork
event_name: push

**Describe the bug**

When I reached the Cruise Altitude the a.p started going up and down with SEC1 off

**To Reproduce**
1. Reached Cruise altitude 
2. Turned on Anti-Ice (I don't know if this affected it)
3. Turned off SEC1

**References**

https://streamable.com/p65j3d

**Additional context**

FabioMike06#2892

Was this working before/when did the issue start occurring?

When I reached the cruise altitude

Is this a problem in the vanilla unmodded game?

I didn't try it

**Comment by hotshotp** [comment]
as far as I know SEC1 turns off your autopilot altitude control ability. So turning it off in flight has this effect. Its only mentioned to do it because it fixes the wobble issue

**Comment by MisterChocker** [comment]
Is this still an issue?

**Comment by MisterChocker** [comment]
Closing since no response from op.
