### ISSUE TITLE
[BUG] The aircraft should be deleting the route once its passing the waypoints ND and MCDU

### ISSUE THREAD

**Issue by mikecbr** [flybywiresim/a32nx#2191]
**Mod Version**
Latest branch , stable release

**Describe the bug**
The aircraft , should be deleting the route once is going through the waypoints. It does not in the mod

**To Reproduce**

1.load a flight plan and fly
2.
3.

**Expected behavior**

It should Delete the route in the ND and the waypoints once you are passing them , and in the MCDU also in the approach once you land you can see in the ND the approach

**Actual behavior**
The waypoints once you are passing them stills there , also in the approach once you land , you can see the approach in the ND

**References**

**Additional context**

Was this working before/when did the issue start occurring?
No

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):

**Comment by 2hwk** [comment]
Fixed by #4953 closing ☑️
