### ISSUE TITLE
[BUG] DECEL point not showing properly

### ISSUE THREAD

**Issue by mikecbr** [flybywiresim/a32nx#2196]
**Mod Version**
Latest branch , stable release 4.1

**Describe the bug**
The decel point in The actual branch says DECEL in green in the ND , instead of shows a D in magenta if you are flying in managed mode , or a D in white if you are flying in selected.

**To Reproduce**

1.Make a flight plan 
2.Make the flight 
3.

**Expected behavior**

It should shows a D in magenta if you are flying in managed mode , or a D if you are flying in selected. 
That D works for : It goes into the approach mode and slows to green dot
On its own if you haven't already done it

**Actual behavior**

The decel point in The actual branch says DECEL in green in the ND

**References**
![image](https://user-images.githubusercontent.com/74787268/100946947-cc614480-3504-11eb-867c-d74ffa3ccdb2.png)

**Additional context**

Was this working before/when did the issue start occurring?
No

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):

**Comment by LarrySheen** [comment]
I was thinking maybe we need to implement the DECENT frist,
like that "Downhill Arrow" in the references img of the ND.
