### ISSUE TITLE
[BUG] ADIRS will not align

### ISSUE THREAD

**Issue by mcm71288** [flybywiresim/a32nx#2197]
**Mod Version**

**Describe the bug**
 ADIRS will not align, shows GPS PRIMARY MISSING

**To Reproduce**
 try to align ADIRS and go to mcdu and align gps 

1. started a new flight,
2. did my pre flight and tried to insert my FPLAN
3. When I went to review my FPLAN it says GPS primary lost

**Expected behavior**
ENTER flight plan and GPS should show your flight plan

**Actual behavior**
GPS STATES PRIMARY LOST AND DOES NOT SHOW FLIGHT PLAN

**References**

![image](https://user-images.githubusercontent.com/75226873/100950795-29480500-34db-11eb-8652-35f17c7e6534.png)
![image](https://user-images.githubusercontent.com/75226873/100950811-32d16d00-34db-11eb-9640-0afad1f5223d.png)
![image](https://user-images.githubusercontent.com/75226873/100950830-3ebd2f00-34db-11eb-9de3-5ac11e89b0f2.png)
PUT IN PHOTOS TO SHOW I DID ALIGN CORRECTLY

**Additional context**

Was this working before/when did the issue start occurring?
this was working fine until about 5 days ago, it was acting odd before takeoff but worked then once airborne the autopilot just went out of wack and started making all kinds of crazy turns and nose dives.
Is this a problem in the vanilla unmodded game? no

Discord username (if different from GitHub):

![Microsoft Flight Simulator 12_2_2020 8_04_19 PM](https://user-images.githubusercontent.com/75226873/100950978-8e9bf600-34db-11eb-901d-fad7957aa06b.png)
![Microsoft Flight Simulator 12_2_2020 8_04_32 PM](https://user-images.githubusercontent.com/75226873/100950981-90fe5000-34db-11eb-8dc2-85eccca85a4c.png)

**Comment by lukecologne** [comment]
Did you actually set the ADIRS to nav on the overhead panel? Also you need to put the mod version (or build info) in your issue.

**Comment by Benjozork** [comment]
You are using an old version of the mod, please update to the latest development version and report back.

**Comment by mcm71288** [comment]
> Did you actually set the ADIRS to nav on the overhead panel? Also you need to put the mod version (or build info) in your issue.

Yes I did, i have been doing a ton of flights since this mod came out no issue until like 5 days ago.

**Comment by mcm71288** [comment]
> You are using an old version of the mod (can see from your screenshot), please update to the latest development version and report back.

I updated to the developmental version and it is still doing it, on the actual plane in real life the ADIRS have a light that will go off after each ADIR is aligned starting with 1 then etc.  Was there a wait time put into the updated mod?

**Comment by Benjozork** [comment]
> on the actual plane in real life the ADIRS have a light that will go off after each ADIR is aligned starting with 1 then etc. Was there a wait time put into the updated mod?

Yep, and this is implemented. Works fine on my end.

Can you try with an empty Community folder and only the mod ?

**Comment by mcm71288** [comment]
> > on the actual plane in real life the ADIRS have a light that will go off after each ADIR is aligned starting with 1 then etc. Was there a wait time put into the updated mod?
> 
> Yep, and this is implemented. Works fine on my end.
> 
> Can you try with an empty Community folder and only the mod ?

**Comment by mcm71288** [comment]
> > > on the actual plane in real life the ADIRS have a light that will go off after each ADIR is aligned starting with 1 then etc. Was there a wait time put into the updated mod?
> > 
> > 
> > Yep, and this is implemented. Works fine on my end.
> > Can you try with an empty Community folder and only the mod ?

I re installed the mod and I am going to use factory airbus no livery. I will take step by step photos , still does not work, 
![Microsoft Flight Simulator 12_2_2020 8_36_54 PM](https://user-images.githubusercontent.com/75226873/100952314-54802380-34de-11eb-8849-725ec66df8a0.png)
![Microsoft Flight Simulator 12_2_2020 8_37_09 PM](https://user-images.githubusercontent.com/75226873/100952315-5518ba00-34de-11eb-9077-9cdd1ef81862.png)
![Microsoft Flight Simulator 12_2_2020 8_37_32 PM](https://user-images.githubusercontent.com/75226873/100952317-5518ba00-34de-11eb-99de-830ddee05b18.png)

**Comment by Benjozork** [comment]
Can you show the contents of your Community folder ?

**Comment by mcm71288** [comment]
I got it working, I manually deleted the nx32 file and re installed it , it works fine now thank you.
