### ISSUE TITLE
[BUG] CRS not updated on FMGC

### ISSUE THREAD

**Issue by tush0701** [flybywiresim/a32nx#2198]
**Mod Version**
{
  "built": "2020-12-03T03:54:34+00:00",
  "ref": "",
  "sha": "",
  "actor": "KO Zone <70115175+ko-zone@users.noreply.github.com>",
  "event_name": "manual"
}

**Describe the bug**

The CRS and ILS information is not updated on the FMCG on the RAD-NAV page. Only the frequency is updated

**To Reproduce**

1. Navigate to FMCG and click on RAD-NAV button
2. Only FREQ is updated. Formatting of ILS needs to be corrected from LS to ILS

**Expected behavior**

 CRS as well as ILS information should be available. Name is ILS

**Actual behavior**
CRS and ILS is not updated. ILS is displayed as LS

**References**

Was this working before/when did the issue start occurring?
Yes

Is this a problem in the vanilla unmodded game?
No

Discord username : tbone0793

**Comment by Benjozork** [comment]
Hello, I removed the part about the PTU since that is working as intended – the PTU cannot be heard in the cockpit on A320neos due to a new dampener.

Please also provide IRL references for the naming of the LS field.

**Comment by Benjozork** [comment]
Can you also clarify what you mean by this ?

> Only FREQ is updated

**Comment by tush0701** [comment]
Hi. I mean that only the ILS frequency is updated, the CRS and the LS information (example: ILS 27) Is not updated.

**Comment by Benjozork** [comment]
Updated from what ? When selecting a new approach ?

**Comment by tush0701** [comment]
Updated from the menu, when we select ILS approach runway in "world map"

**Comment by tracernz** [comment]
This was fixed some time ago.
