### ISSUE TITLE
N1 Showing 0.1 from cold and dark

### ISSUE THREAD

**Issue by CoffeePanda0** [flybywiresim/a32nx#220]
![image](https://user-images.githubusercontent.com/34898787/91634594-69ce4900-e9e9-11ea-946e-4aa2640af5f8.png)
When I start from cold and dark, the N1 reading shows 0.1 instead of the XX, despite the fact that the engines are not running. Thanks!

**Comment by NathanInnes** [comment]
This probably isnt a bug, it was most likely wind that was causing the fan to spin.

**Comment by CoffeePanda0** [comment]
Yeah could be, but I tried starting up then shutting down both engines while staying still the whole time. After shutdown the N1 shows XX

**Comment by Curtis-VL** [comment]
Might just be an issue with the state the plane spawns in. :)

**Comment by NathanInnes** [comment]
Is this still happening for you or is it resolved? @CoffeePanda0

**Comment by CoffeePanda0** [comment]
> 
> 
> Is this still happening for you or is it resolved? @CoffeePanda0

Ah sorry, yes this has been resolved now. I'll close the issue
