### ISSUE TITLE
[BUG] Installer Keeps Saying "A32NX version is out of date, please consider updating"

### ISSUE THREAD

**Issue by speedbird5** [flybywiresim/a32nx#2204]
**Mod Version**

Development Version -  "built": "2020-12-03T06:03:11+00:00"

**Describe the bug**

Installer Keeps Saying "A32NX version is out of date, please consider updating" even though have just updated using the installer.

**To Reproduce**

1.  Run the installer once to update, then run it again and you will keep getting the "A32NX version is out of date, please consider updating"  message.

**Expected behavior**

After updated, the installer should not keep saying update...

**Actual behavior**

As above

**Comment by Jochandecoster** [comment]
can confirm

**Comment by myselfaaryan** [comment]
can confirm as well

**Comment by monkeh88** [comment]
yep its a bug

**Comment by Benjozork** [comment]
Please file this in https://github.com/Externoak/A32NX-installer/
