### ISSUE TITLE
Fuel flow and consumption 

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#2206]
**Mod Version**

master

**Describe the bug**

fuel flow and consumption are to low. In cruise the A320Neo takes ~2010-2100kg/hr. A32NX only (max) 1800.
also the consumption seems only connectet to the N1(or N2)rpm. Does not vary with altitude, density or Temperature. E.g. on Takeoff, the fuel flow is equal like the whole climb with ca 1250kg/hr. In real the A320 Neo on a normal T/O at ISA uses more than 2500-2800kg/hr PER ENGINE. That decreases with incresing ALT/Density.

Any plan to adjust that? Already worked on?

**To Reproduce**

start a flight with any weight, fuel flow is unrealistic over the whole range of flight stages, from T/O to Cruise.

1.
2.
3.

**Expected behavior**

Fuel flow should more depend on ALT/Density like in real life. Also cruise-fuel flow is to low. 

**Actual behavior**

fuel flow to low, same over any Altitudes

**References**

https://www.youtube.com/watch?v=cv41hm4JEB8 @3:25min you can see the high fuelflow on TakeOff-Roll (~2950kg per ENG) that continuesly decreases with increasing Alt, decreasing Density. Cruise ~2050kg/hr  (1000-1050 per Eng @FL340)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Please include references to IRL figures.

**Comment by andrejetcat** [comment]
example video of A320Neo T/O added.

**Comment by CBGonzalez** [comment]
TOW is a tad over 69000 kg (which shows at 4:34 in the above video, a few seconds after TO)

**Comment by donstim** [comment]
A completely new engine model is being developed.

**Comment by frittichris** [comment]
Yes thats my Problem too. Always not enough fuel burn. Real A320neo burns 2000-2100 kg/h. Your A32NX burns only about 1800kg/h. When i fly with simbrief (with the right FBW frame) or with my Airline there is a lot of fuel left at the destination.
Example: i fly LOWS to LPPT , about 1100 to 1200 nm. should consume about 6500 kg. Consumes only 4760 kg !

**Comment by Taz5150** [comment]
With the new engine/ FADEC model:

- Fuel flow is closer to expected consumption as per FCOM figures
- Corrected Fuel flow is now calculated with respect to corrected N1, altitude and Mach. Temperature ratio (theta) takes into account deviations in ISA conditions as it should.
