### ISSUE TITLE
Color of entered approach magenta iso green on ND

### ISSUE THREAD

**Issue by PCGamesF1Tech** [flybywiresim/a32nx#221]
Hey,
I've seen a picture where the entered approach (should appear when FMS flight plan distance goes below 250NM) was shown in magenta instead of green (in top of Nav Display) 
I'm not sure if this has been adressed already...?

**Comment by Brenchen** [comment]
Any chance you can provide some reference and screenshot?  Makes it easier on the devs to answer (if they answer)

**Comment by PCGamesF1Tech** [comment]
Yeah, sorry, my mistake!
Let me check the entries here, maybe I'll find it again.
(I hope it wasn't from another addon.....) 😱

**Comment by NathanInnes** [comment]
Fix #910 will solve this issue.
