### ISSUE TITLE
[BUG] A320 rocking side to side terribly 

### ISSUE THREAD

**Issue by kparsons34** [flybywiresim/a32nx#2210]
**Mod Version**

**Describe the bug**

**To Reproduce**

1. AP on and altitude set to FL380 
2.
3.

**Expected behavior**

**Actual behavior**

**References**
< >

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Duplicate of #2005 and does not have anything written in the post.
