### ISSUE TITLE
Make sure that the MCDU displays the level that you need to pass at this point.

### ISSUE THREAD

**Issue by Vippi04** [flybywiresim/a32nx#2213]
**Is your feature request related to a problem? Please describe.**
No

**Describe the feature you'd like to see implemented**
I want you to do the FL mapping in MCDU. That is, at any point it was shown on which FL should pass it.
**References**

**Additional context**

Discord username (if different from GitHub):
Vippi#7592

**Comment by Benjozork** [comment]
No IRL references were provided. Please correct this.

**Comment by N1EL** [comment]
Do you mean altitude restrictions / restraints?

**Comment by MisterChocker** [comment]
I believe he means correct altitude predictions for the fixes in the flightplan.

**Comment by Vippi04** [comment]
> Ссылки на IRL предоставлены не были. Пожалуйста, исправьте это.

What's the link?

**Comment by Vippi04** [comment]
> Вы имеете в виду ограничения / ограничения по высоте?

In FMS, in the flight plan tab on the right, where the point should be written FL, on which you must pass this point. That's what I mean.

**Comment by Benjozork** [comment]
No IRL references provided as was requested, closing.
