### ISSUE TITLE
[REQUEST] Failures system 

### ISSUE THREAD

**Issue by X-PetRussian-X** [flybywiresim/a32nx#2217]
**Is your feature request related to a problem? Please describe.**
No problem. 

**Describe the feature you'd like to see implemented**
 A app to b e downloaded with the aircraft that allows you to fail even very small systems, and the aircraft displays ECAM messages due to said system failing, like when hydraulics fail it display's a warning..

**References**
 Not possible.. 

**Additional context**
 Nope.. 

Discord username (if different from GitHub):

**Comment by aviationenthusiast** [comment]
related: #1547

**Comment by X-PetRussian-X** [comment]
its not related tho.

**Comment by Benjozork** [comment]
It is.

I will rename your issue as the title is too long.
