### ISSUE TITLE
[BUG] FD/LOC/APPR Keyboard Shortcuts not working

### ISSUE THREAD

**Issue by richardkennedy** [flybywiresim/a32nx#2220]
**Mod Version**

Developer Build
`{
  "built": "2020-12-01T11:54:03+00:00",
  "ref": "",
  "sha": "",
  "actor": "DerL30N <leon.beeser@yahoo.de>",
  "event_name": "manual"
}
`

**Describe the bug**

Several keyboard shortcuts don't appear to be working as expected.

1. Toggle FD - Appears to be inconsistent, can take 2-3 attempts on occasion
2. Toggle LOC - Not working
3. Toggle APPR - Not working
4. Toggle LS (No Shortcut)

**To Reproduce**

1. Attempt to toggle FD, LS, LOC & APPR using keyboard shortcuts

**Expected behavior**

The systems/buttons should toggle on/off when the assigned keyboard shortcut is used

**Actual behavior**

The systems/buttons aren't toggled

**References**

**Additional context**

Was this working before/when did the issue start occurring?
FD, LOC & APPR work on the default A320 model, however there's no LS shortcut in the main game.
Unknown as to whether this is a new FBW bug.

Is this a problem in the vanilla unmodded game?
As above

Discord username (if different from GitHub): Not Applicable

**Comment by PDX777** [comment]
I think these keys are actually working, as you see the right modes engaging (i.e G/S). But the lights on the corresponding buttons (LOC, APPR) do not come on as they should.

**Comment by sidnov** [comment]
Works as intended with the subsequent updates to the sim
