### ISSUE TITLE
[BUG] Autopilot Bank Oscillation

### ISSUE THREAD

**Issue by Ogeee** [flybywiresim/a32nx#2225]
**Mod Version**
0.4.2 (release)

**Describe the bug**
Just tried flying from Kopenhagen to Cologne. So from 22k feet the A320 began heavily oscillating. Bank angles up to more than 50 Degree. In the release notes of 4.2 is written, that the oscillation bug has been fixed. But that doesn't seem so.

**To Reproduce**
1. Fly with the A320 and the 0.42 release mod with realistic weather
2. Enjoy oscillating during the flight
3. Vomit

**Expected behavior**
Stable autopilot without bank oscillation.

**Actual behavior**
Unstable autopilot with heavy bank oscillation.

**References**
None, there are enough videos on YouTube.

**Additional context**

Was this working before/when did the issue start occurring?

Answer: It started for me with the 0.4.2 version. Never had that behaviour before. Or only with Boeing 747.

Is this a problem in the vanilla unmodded game?
Don't know. The vanilla airbus does not make fun to fly.

Thank you!

**Comment by wpine215** [comment]
Fixed in development (master).
