### ISSUE TITLE
[REQUEST] Ability to change default baro unit to HPa

### ISSUE THREAD

**Issue by theomessin** [flybywiresim/a32nx#2228]
**Is your feature request related to a problem? Please describe.**
If we fly in HPa regions (e.g. Europe) we currently have to manually change the baro unit selector to HPa every time we load the aircraft. 

**Describe the feature you'd like to see implemented**
I believe we need an option in the new MCDU options page that allows users to set the default baro unit to either In Hg (default as in current Asobo build) or to HPa.

**References**
I believe that real A320 pilots that operate in HPa regions (e.g. Europe) wouldn't change the baro unit selector to In Hg when leaving the a/c, meaning that the next pilots would almost always find this in HPa when they enter the cockpit. 

Discord username: Theodore Messinezis

**Comment by theomessin** [comment]
I've already coded this up. Pull request to be opened in a couple of minutes.

**Comment by ArwynFr** [comment]
That feature is questionable IMO.

Defaulting to hPa will only cause the same problem to players using inHg.
A solution would be to have a way to persist whether to use hPa or inHg.
The best way to do that would be to read user's options for metric or imperial units.

**However, all of this is problematic until MSFS does handle that setting correctly.**

Currently, if you set your game to use metric units, ATC/ATIS still sends QNH in inHg worldwide.
Defaulting to hPa means you'll have a default configuration that requires all players to do a conversion.
Perhaps defaulting to inHg until Asobo solves this is relevant ?

**Comment by ThatRedMelon** [comment]
> That feature is questionable IMO.
> 
> Defaulting to hPa will only cause the same problem to players using inHg.
> A solution would be to have a way to persist whether to use hPa or inHg.
> The best way to do that would be to read user's options for metric or imperial units.
> 
> **However, all of this is problematic until MSFS does handle that setting correctly.**
> 
> Currently, if you set your game to use metric units, ATC/ATIS still sends QNH in inHg worldwide.
> Defaulting to hPa means you'll have a default configuration that requires all players to do a conversion.
> Perhaps defaulting to inHg until Asobo solves this is relevant ?

Check the PR for this inclusion, it will become an option

**Comment by theomessin** [comment]
@ArwynFr users can decide whether they want IN HG, HPA, or AUTO as the baro unit on init. Currently, the default is still InHg (no change). Users can set this to HPA, which will mean the aircraft will be in HPA when initialised. Users can also select AUTO, in which case the value will depend on the location of the a/c on init. This is all in the options:

[![image.png](https://i.postimg.cc/XJjzjGTv/image.png)](https://postimg.cc/3yqB9RrM)

More info is in the PR, as per @ThatRedMelon
