### ISSUE TITLE
[BUG] False takeoff config warning

### ISSUE THREAD

**Issue by richgrov** [flybywiresim/a32nx#2233]
**Mod Version**
Master, 0.4.2

**Describe the bug**
When throttle levers are moved to the TO/GA position without aircraft power, the takeoff config warning will sound when the plane is turned on.

**To Reproduce**
1. Start cold and dark
2. Move throttles to TO/GA
3. Turn on batteries & ground power

**Expected behavior**
I'm not an expert, but is doesn't make sense for this to happen as the plane would have no idea the throttle levers were in this position without power.

**Actual behavior**
Takeoff config warning sounds on startup.

**References**
N/A

**Additional context**
N/A

Was this working before/when did the issue start occurring?
Unknown

Is this a problem in the vanilla unmodded game?
Unknown. Probably not, as I don't believe this is a feature in vanilla.

Discord username (if different from GitHub): HydronicDev#3730

**Comment by hotshotp** [comment]
yep, so fwc should not be initialized when the plane starts.

**Comment by beheh** [comment]
Yeah, I don't think we have a great concept yet of systems themselves being on/off. Waiting on an updated ELEC system for that.

**Comment by sidnov** [comment]
Unable to reproduce on latest dev. Also, there will be improved logic for this in the new FWC implementation
