### ISSUE TITLE
[BUG] Terrain Warning on T/O of 2nd Leg

### ISSUE THREAD

**Issue by rausmac** [flybywiresim/a32nx#2235]
**Mod Version**
Master

**Describe the bug**
I’m not sure if this is a bug or if I’m doing something incorrectly. I start cold and dark and input a flight plan manually and complete it. I shut off engines at the gate and start replacing the init page info for my second leg. Everything looks good, I can put a new flight plan in, it goes back to the takeoff performance phase, and takeoff inhibit displays as per normal during roll. The problem occurs when I leave the ground. I get “terrain pull up” warnings for about 1500’, like takeoff inhibit isn’t actually inhibiting. I have never tried a 3rd leg to test and this has never happened on a 1st leg. 

**To Reproduce**
1. Happens on any second leg, in the same session, on takeoff once my first flight plan competes and I’m shown the data page.

**Expected behavior**
“Terrain pull up” warning to be inhibited 

**Actual behavior**
“Terrain pull up” warning sounds from the beginning of climb out till about 1500’

**References**

**Additional context**

Was this working before/when did the issue start occurring?
 It’s been happening for a while. I’m not sure it’s ever not done it to me on that second leg.

Is this a problem in the vanilla unmodded game? 
Vanilla aircraft isn’t capable enough to try and reproduce.

**Comment by Steven0785** [comment]
Same behavior here!

**Comment by MisterChocker** [comment]
Yup, reproduced.

**Comment by dms492** [comment]
Getting the same. Also not showing 'SRS' or 'RWY' on the PFD on takeoff on the 2nd leg

**Comment by Marenostrum66** [comment]
same here
it seems that the inhibit function that should stop some warnings during the landing/TO phase, does not reset after the first flight.
Or may be there is a procedure (that I do not know) to reset them.
