### ISSUE TITLE
[REQUEST] Improve the exhaust power effect (blur effect)

### ISSUE THREAD

**Issue by lalloretpilou** [flybywiresim/a32nx#2237]
**Is your feature request related to a problem? Please describe.**
Change de N1 power and look the exhaust effect.

**Describe the feature you'd like to see implemented**
is it possible to improve the effect of engine exhausts and APU?
in reality, the engine exhausts exit through the center of the engine, as in the picture.
The greater the power N1 of the motor, the faster the flow, and vice versa.
For the APU it is the same principle.

**References**
![6-8-2016-a320neo_leap-blok](https://user-images.githubusercontent.com/42711915/101238026-932ffc80-36dd-11eb-80da-51c1cf186f94.jpeg)

**Additional context**

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by NathanInnes** [comment]
Needs to be improved but may take some time as we do not have access to it yet

**Comment by theomessin** [comment]
> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning

Feel free to open a new issue **provided you follow the given instructions**.
