### ISSUE TITLE
[BUG] Idle Fuel Consumption lbs->kg is wrong

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#2239]
**Mod Version**

master

**Describe the bug**

idle fuel consumption is wrong. engine.cfg - value is in kg, not in LBS - but it should be ~300 - 320kg/hr (per side/ENG), not 300lbs/hr. change it to 705lbs per hour, so the idle fuel flow on ground is nearly correct. 
thats only a small thing - the whole fuel flow is not correct, also there is no simulation of the density/altitude effect on the fuel flow. E.g. set full thrust on the ground consumes near the same as set full thrust @FL340. But I open that issue before - here i want to give just an Idea how to change idle fuel flow on ground to became a little more realistic.
GOOD JOB, FlyByWire! THANK YOU FOR YOUR WORK! TOGETHER WE MAKE THIS BIRD GREAT!

**To Reproduce**

look at idle fuel flow on ground

1.
2.
3.

**Expected behavior**

idle fuel flow IRL ~300  -  ~320kg/hr PER SIDE

**Actual behavior**

300lbs per hour. lbs->kg mixed

**References**

https://www.youtube.com/watch?v=4NAs7DJ42eM
clearly see that the idle flow is around 300kg/Hr

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by dcb99** [comment]
I'll try and fix this

**Comment by tareksabet** [comment]
Do you have any references for that issue as these values apply for the CEO but not sure for the NEO

**Comment by andrejetcat** [comment]
https://www.youtube.com/watch?v=4NAs7DJ42eM clearly see the whole startup with idle flow of around 300kg/hr

**Comment by MisterChocker** [comment]
@andrejetcat idle fuel flow is influenced by multiple parameters. Our new engine model will respect them.

**Comment by Taz5150** [comment]
Idle fuel flow at SL ISA conditions is now around 300 Kg/h (705 lbs/h).

**Comment by MisterChocker** [comment]
Closing since issue is resolved now.
