### ISSUE TITLE
4.2 mod causes plane to violently rock side to side

### ISSUE THREAD

**Issue by sperin2** [flybywiresim/a32nx#2241]
**Mod Version**

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
Fixed in dev/master.

Also, please do not ignore the provided template.

**Comment by sperin2** [comment]
Soon after take off, the plane starts to rock side to side and becomes increasingly violent as the climb continues.  It appeared to smooth out at about 30,000 feet, but continues to rock very slightly side to side.  Also the altitude under the flight plan begins to decrease on the vertical climb to about 100 feet per minute causing me to manually set the vertical climb in order to achieve the given altitude

**Comment by sperin2** [comment]
This only started to happen when I installed the 4.2 mod.  If I fly the stock A320, this does not happen

**Comment by Benjozork** [comment]
As I told you this is fix in the development version.

**Comment by sperin2** [comment]
Thank you.  Sorry for my posts.  I will look for the development version then.
