### ISSUE TITLE
[REQUEST] Give the flaps` sound from the default a320 back

### ISSUE THREAD

**Issue by AdmiralArtemiy** [flybywiresim/a32nx#2250]
The flaps` sounding of the default a320 was much better, it is just as in the reality.

**Comment by Benjozork** [comment]
First, you ignored the provided template.

Second, the new flaps sound has been verified with IRL A320 pilots. It is more realistic. They are also constantly getting improvements.

If you have feedback on sounds, please discuss this on Discord.

**Comment by hotshotp** [comment]
> The flaps` sounding of the default a320 was much better, it is just as in the reality.

lol what? the default a320 reused TBM flap sounds
