### ISSUE TITLE
A320Neo ACJ

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#2252]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**

Hello! It would be so awesome if you can create a seperate ACJ - Version auf die A32NX. There are already some ACJ liverys and I think it would be a very good option to see this beauty on long haults! 
e.g. https://flightsim.to/file/2291/acj320neo-airbus-a320neo
The original ACJ VVIP Airbus A320 have "only" 3 additional center Tanks with a additional 3000Gallons of fuel. The ACJ320neo can fly twenty-five passengers 6,000 nm/ 11,112 km or more than 13 hours non-stop. With the current system depth of the A32NX, it would be so great! 

**References**

The ACJ320neo can fly twenty-five passengers 6,000 nm/ 11,112 km or more than 13 hours non-stop.
https://www.acj.airbus.com/en/exclusive-products/acj320neo.html
https://flightsim.to/file/2291/acj320neo-airbus-a320neo
34.351liters of total JetA1

**Additional context**

Discord username (if different from GitHub):

## Update from #3195:

**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**

To my mind, the A32NX is by far the most useable plane in FS2020 by now. But we don´t have any long-haul Planes (the 787/747 are not useable with 75% inop systems...so, not interessting forenthusiasts)
What are you thinking about a A320NEO-ACJ Version of this great A32NX-MOD?
The real ACJ could carry 3000GAL more fuel in up to 4 additional Center-tanks.

https://www.acj.airbus.com/en/exclusive-products/acj320neo.html

It would be so awesome to serve VVIP long haul flight with such a nice plane!
"_The ACJ320neo can fly twenty-five passengers 6,000 nm/ 11,112 km or more than 13 hours non-stop_."

Maybe it would be possible to add/create the ACJ Version to the regular A32NX.

I think that could be very interessting. like PMDG create a "BBJ-Version" additional to their normal B737NGX version.  

**References**

https://www.acj.airbus.com/en/exclusive-products/acj320neo.html

**Additional context**

Discord username (if different from GitHub):

![tanks](https://user-images.githubusercontent.com/72918017/105845958-cc993000-5fdb-11eb-9081-363e61a3c443.jpg)

![erster_acj320neo](https://user-images.githubusercontent.com/72918017/105845456-0a498900-5fdb-11eb-8475-1811c07c0215.jpg)
![range_map](https://user-images.githubusercontent.com/72918017/105845543-37963700-5fdb-11eb-8670-df796209ee68.jpg)

**Comment by 2hwk** [comment]
For consolidating reasons I'm closing this in favor of tracking this issue on #1408 instead
