### ISSUE TITLE
[BUG] No IFR-Clearance possible by ATC

### ISSUE THREAD

**Issue by Meleman5472** [flybywiresim/a32nx#2253]
**Mod Version**
latest

**Describe the bug**
After loading an IFR-Flight (*.pln) from Simbrief in MainMenu and starting the flight, no IFR-Clearance by ATC is given.
When you use the ATC Menu all Ground-Services and ATIS is OK, but if you click on IFR-Clearance nothing happens. So you can´t get the Pushback Menu

**To Reproduce**

1. Load an FLT-File in the MainMenu
2. Start the flight
3. Try to get an IFR-Clearance via ATC-Menu

**Expected behavior**

**Actual behavior**

**References**

Nothing happens

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Meleman5472** [comment]
My fault...Sorry..

**Comment by Benjozork** [comment]
In the future, please report this with Microsoft/Asobo as we don't program ATC functionality
