### ISSUE TITLE
[BUG] TCAS knob inop

### ISSUE THREAD

**Issue by ChruutvoLuzi** [flybywiresim/a32nx#2257]
**Mod Version**

latest Master, after merged TCAS PR

**Describe the bug**

It is not possible to switch the TCAS Knob from STBY to TA and TA/RA

**To Reproduce**

1. load into the aircraft
2. try to switch the knob to another position
3.

**Expected behavior**

In order to turn on the TCAS you should be able to turn the Knob

**Actual behavior**

It seems inop

**References**

**Additional context**

Was this working before/when did the issue start occurring?
After TCAS PR merge
Is this a problem in the vanilla unmodded game?
Yes, but it was working in an earlier master

Discord username (if different from GitHub):

ChruutvoLuzi | SD-PB.ch#8902

**Comment by sidnov** [comment]
Can confirm this, had similar issues. Spawned directly on the runway with all systems running on the last dev master, TCAS knob doesn't move as expected.

**Comment by Saschl** [comment]
The buttons seem to work for me. Both C&D and spawning from runway. Also I couldn't find an "issue" in the xml templates. Perhaps an installation issue?

**Comment by ChruutvoLuzi** [comment]
> The buttons seem to work for me. Both C&D and spawning on runway. I Also couldn't find an issue in the xml templates (to my knowledge). Perhaps an installation issue? CommitId `04e91d946d7ffa329780e5b459e11203d02e5c25` reported by build_info.json
> 
> ![Microsoft Flight Simulator Screenshot 2020 12 06 - 13 24 13 76 (2)](https://user-images.githubusercontent.com/19493808/101279986-9eab2280-37c6-11eb-948d-1ea1290fda37.png)

Thats weird as i tried it twice 🤔 i will try it again in a few hours

**Comment by crisk73** [comment]
Same here thanks.

**Comment by ilyeshammadi** [comment]
@lukecologne I think it may be related to your recent changes to the TCAS

**Comment by lukecologne** [comment]
Can't reproduce, both buttons work fine.

**Comment by crisk73** [comment]
I've found that is happens only if you have the YourControls folder installed in Community.

**Comment by sidnov** [comment]
@crisk73 Thanks for the info! Have notified Sequal about it :)

**Comment by ChruutvoLuzi** [comment]
yeah that seems to fix it
