### ISSUE TITLE
[BUG] Indecisive managed speed

### ISSUE THREAD

**Issue by HurricaneTracker500** [flybywiresim/a32nx#2260]
**Mod Version**
 Latest development (Master)

{
  "built": "2020-12-06T08:38:03+00:00",
  "ref": "",
  "sha": "",
  "actor": "lukecologne <39596827+lukecologne@users.noreply.github.com>",
  "event_name": "manual"
}

**Describe the bug**

I'm not sure if this occurs randomly or closer to the destination airport, or during a turn. However, at some point in my flights the managed speed appears to be going back and fourth between my cruise speed and 250 kts. Once it begins doing this it will keep doing it for what will appear to be the rest of the flight, or once I hit a decel point. Turning on and off managed speed mode does not work as once managed speed mode gets re-engaged it continues to go back and fourth between these two speeds. I have had this bug on two consecutive flights so far. On my second flight it seemed to occur once for a short amount of time while I was in a turn on the climb out of Atlanta, however it ended up resolving itself. Later in the flight however, as I was much closer to my destination, it happened again and this time did not resolve itself and I had to turn the speed mode to selected. I do not have much memory from the first flight this happened but I'm pretty sure it was toward the end of the flight as well. I'm pretty sure that this bug continues until you hit the first decel point on the approach as that's when I turned it back to managed on the first flight and it started working again, however, I'm unsure if it really persists for this long. 

**To Reproduce**

1. Start a flight cold and dark and do not have a flight plan pre loaded (create your flight plan in the mcdu)
2.Set up the plane as normal 
3. Takeoff and proceed with the flight as normal - this bug occurred on two consecutive occasions like this. 

**Expected behavior**

The managed airspeed will stay at one speed unless it needs to be changed for any reason (speed restrictions, approach etc.) 

**Actual behavior**

The managed speed setting seems to switch constantly back and fourth between my cruise speed and 250kts at some point in the flight, usually closer to my destination.
**References**

 Airspeed mysteriously drops to 250
![Screenshot (587)](https://user-images.githubusercontent.com/75582051/101288722-12006480-37c6-11eb-8fdd-93db6dd0f148.png)

about 5-20 seconds later increases to 290 again

![Screenshot (588)](https://user-images.githubusercontent.com/75582051/101290968-5a724f00-37d3-11eb-9ccd-47660e18689c.png)

5-20 seconds later the airspeed decreases to 250 again and the cycle repeats

**Additional context**

Approach mode is confirmed not to have activated during this as I checked the mcdu as it was going on so it is not a bug with approach mode activating. 

Was this working before/when did the issue start occurring?

This seemed to start happening after World Update II, I couldn't really play the sim at the time due to the autopilot suicide bug but once that was fixed, I found out that this was an issue. I'm not sure if this issue was caused by the fixes or not. 

Is this a problem in the vanilla unmodded game?

Unknown 

Discord username (if different from GitHub):

**Comment by donstim** [comment]
From your screenshots (thanks for providing them), it looks like the autopilot lost enough altitude during your turn that it went into Alt* mode to climb back to the FCU altitude. This changed the speed to the climb speed of 290 knots. When back to the cruise FL, the speed will go to the cruise speed.

I am a little confused about why your cruise speed is so low. I thought the default is around M0.78.

**Comment by HurricaneTracker500** [comment]
> I am a little confused about why your cruise speed is so low. I thought the default is around M0.78.
It is a little low, in these screenshots but I was cruising at around M.73 for most of the flight from what I remember, so if its this low in the screenshots it was probably because in none of  the screenshots was the speed actually at the cruise speed, the managed speed normally switched before the airspeed could even hit the speed that was selected by the AP. What is interesting is how it continued to switch the speeds even after the turn was finished. If it was because of the loss of altitude it should have non been this indecisive with it's speed or stopped after the turn was finished.

**Comment by HurricaneTracker500** [comment]
> From your screenshots (thanks for providing them)
> 

Just realized the screenshots are inaccurate as they appeared to be taken at completely different times, didn't notice this before, fixing now.

**Comment by donstim** [comment]
The key is to check the FMA for whether or not the autopilot is in ALT CRZ or not. If in ALT CRZ, in managed speed it will use the cruise speed. If not in ALT CRZ, it will use the climb or descent speed, depending  on whether it is climbing or descending.

**Comment by HurricaneTracker500** [comment]
Ok, screenshots now fixed, accidentally used the wrong screenshot for the second one, see if this changes anything. It might not but just in case. As far as I can see from the new second screenshot, it seems the plane was in ALT CRZ the whole time.

**Comment by donstim** [comment]
Ok, disregard my comments then!
@Watsi01 - just want to alert you to this!

**Comment by Watsi01** [comment]
RIght now I don't know why the MCDU is commanding 250kts at CRZ. I have to check that again. I had flights with lower CRZ alts like this, and had no problems. 
@HurricaneTracker500 Could you tell me what CI you've inserted? Did you fill out all pages in the MCDU (init a and b, PERF pages)?

**Comment by HurricaneTracker500** [comment]
.
> @HurricaneTracker500 Could you tell me what CI you've inserted? Did you fill out all pages in the MCDU (init a and b, PERF pages)?

Yes, I have filled them out, I entered the CI simbrief gave me for this flight which looking back at the flightplan was 15.

**Comment by Watsi01** [comment]
That seems to be ok. 
On your screenshots, I recognized that the FCU is set to managed mode, but to speed and not to mach. Does the issue occur also, if you set the FCU to mach?

**Comment by HurricaneTracker500** [comment]
Wait, how are you able to tell it's in speed mode and not mach mode? Sorry, don't know everything about the A320. I'll try setting it to mach though, and see if that does anything when I have the time.

**Comment by Watsi01** [comment]
You can see "SPD" above the FCU speed dial. If it's on mach, you would see "mach". You can switch to mach with the little button to the left of that.

**Comment by HurricaneTracker500** [comment]
> You can see "SPD" above the FCU speed dial. 

Ah, for some reason I wasn't thinking of the fact that that display still shows whether you're in mach mode or speed mode if you're in managed since I know it does when you're on selected. When I have the time I'll try switching it and see if it helps.

**Comment by FrankGehry** [comment]
I'm having this issue too in the latest developer built: 2020-10-15T01:38:50+00:00

The MCDU will say it has reached cruise phase, and the manages speed will fluctuate from 220 knots to 290, back and forth.

**Comment by BritishAvgeek** [comment]
This has been an issue for me for over a week now (since the AP fix actually) - now it reads a speed constraint ahead for 250kts and Managed Speed will drop the speed down to that but then it'll get confused and return to cruise speed, back to constraint speed and so on.

After the constraint speed waypoint it'll then accelerate back to whatever phase it's in (often it jumps back to cruise speed)

**Comment by HurricaneTracker500** [comment]
I noticed that 320 Sim Pilot encountered this bug in his 0.5 update review and even comments on it. 
(Timestamp 22:40 - 24:09)

You can hear it start by the throttle suddenly decreasing and you can see the engines constantly changing thrust. He then comments on it at around 24:00. 

https://www.youtube.com/watch?v=mEOEwKSD9Z4&ab_channel=320SimPilot

From my own experience, it does seem to be caused by not going into Mach mode as when I went into mach mode the bug did not occur. I may have found a fix for when the bug does occur which involves going into mach mode, going back to speed mode and then changing it back into mach mode which seems to stop the issue if it has already started occuring. If it doesn't stop, maybe keep fiddling with the switch and it will stop.

**Comment by Watsi01** [comment]
@HurricaneTracker500 Regarding your own experiences: 
1. It didn't go to a different flightphase when this is happening (form crz to appr or something like that)?
2. What's on the crz page when this is happening? Still ~290kts or does it also switch back to 250 on the crz page?

It has definetly something to do with low crz alts and/or not going to mach.

**Comment by HurricaneTracker500** [comment]
@Watsi01 

It didn't seem to go into a new flight phase judging by the screenshots that I took. I didn't look at the cruise phase while this bug was occurring, I may have to look into that.

**Comment by DFWSupertrooper** [comment]
@donstim seems to be on the right track.  This description sounds accurate to what I was experiencing (to the best of my recollection).  I don’t ever change the settings in the MCDU as far as speeds (I accept what the A/C populates).  The only time I adjust anything is the speed dial if ATC limits my approach speeds and I use according to SOP (set to SPEED and select the speed overriding the managed descent speed.  The shifting began immediately before I should have begun descent in one flight and after managed descent had begun in another.
