### ISSUE TITLE
[BUG] Engines Bug

### ISSUE THREAD

**Issue by elcareflen** [flybywiresim/a32nx#2269]
**Mod Version**

Last Update MFS 2020

**Describe the bug**

--I used Google Translater--
I have a issue with the engines of the a320neo.
The engines don't turn off when I get to the airport gates.
It also happens without the FBW MOD. (Also with the mod)
I don't know if the Flybywire team is working on this issue, but I wanted to mention it.

**To Reproduce**

1. Just turning off the engines
2.
3.

**Expected behavior**

That I can turn off the engines to record the flight in my flight history.

**Actual behavior**

**References**

I have video:
https://www.youtube.com/watch?v=EBr_AWU_Tvo
**Additional context**

Was this working before/when did the issue start occurring?
After the last update of MFS 2020

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Turn off unlimited fuel

**Comment by elcareflen** [comment]
> Turn off unlimited fuel

Woow, I will try.
But is it still a problem?
or is it a normal change in the simulator?

Thank you! :)

**Comment by Jadro747** [comment]
> Turn off unlimited fuel

Wow! It's working, thank you for this solution! :)
