### ISSUE TITLE
[BUG] Flight control response- please close/delete

### ISSUE THREAD

**Issue by A320pilotIRL** [flybywiresim/a32nx#2270]
please close/delete this as I am tired of getting emails and unsubscribing has not stopped the emails

**Comment by Benjozork** [comment]
Hello,

A completely custom fly-by-wire system is currently under test by our IRL A320 pilots.

If you want to get involved in testing it, reach out on Discord.

**Comment by donstim** [comment]
Do we want an interim fix for the current airplane, or definitely wait until the new FBW system is fully implemented?

**Comment by MisterChocker** [comment]
@donstim we'll wait. Had this discussion before, where changes had side effects, I believe.

**Comment by donstim** [comment]
@MisterChocker That discussion was about a PR that attempted to severely restrict roll performance in an attempt to address the wing drop during flare issue.  I see this as similar, and maybe even complementary, to the proposed enhancement in the yaw axis to make the crosswind takeoff and landing capability consistent with the real airplane.

**Comment by pareil6** [comment]
All the PIDs need retuned (they weren't great in the default plane but now mismatch with the updated flight model), but given the custom FBW is on the way that's probably not going to be worth the time investment.

However, given the roll PID D weight was increased in #2216, it makes sense to be increasing the proportional weight with it (the D component will work against the direction of travel, so to have the same roll authority as before you'd need a larger P component), which would be a reasonably large step in the right direction for minimal effort. I've been flying with the following change for a few days (6 separate full flights I think):

`diff --git a/A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/ai.cfg b/A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/ai.cfg
index 50869a3b..5d49de4c 100644
--- a/A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/ai.cfg
+++ b/A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/ai.cfg
@@ -19,7 +19,7 @@ brakeDifferentialPID = 2.7, 0.001,10.0,1.0, 5.0
 throttleDifferentialPID = 12.0 ,0.001,25.0,10.0,40.0
 throttlePID =  20.0,1.0,15.0,20.0,1000.0
 pitchPID = 1.0, 0.1,  5.0, 1.0,  100.0
-rollPID = 2.5, 0.1,  5.0, 100.0,  100.0
+rollPID = 4.0, 0.1,  5.0, 100.0,  100.0
 headingPID = 2.0, 0.5, 2.0, 0.025, 1.0
 verticalSpeedPID = 0.5, 0.005,  0.2, 300.0,1000.0
 nav_ex1PID = 2.4, 0.05, 20.0, 0.02,  50.0`

**Comment by donstim** [comment]
Aren't the PIDs just used for autopilot control?  I thought the issue was the maximum roll rate under manual control?

**Comment by pareil6** [comment]
They're also used for Asobo's FBW implementation I think, since #2216 fixed the swaying that occurred even with the AP off. I'll do a proper test later today to confirm that though.
