### ISSUE TITLE
[BUG] LCD for radio and ATC not visible from instrument view CTRL+6

### ISSUE THREAD

**Issue by rostykk** [flybywiresim/a32nx#2272]
dev 1206 version
looking from quick instrument view (ctrl+6/7) LCD on radio or  ATC are blank but operable
![image](https://user-images.githubusercontent.com/3607571/101326739-01a3c480-386e-11eb-8d05-937c55b83ad3.png)
looking from normal pilot copilot view shows lcd on
![image](https://user-images.githubusercontent.com/3607571/101326812-1aac7580-386e-11eb-8ed9-cbb6b6f75e1d.png)

probably clipping view issue

**Comment by lukecologne** [comment]
Duplicate #717
