### ISSUE TITLE
[BUG] MCDU Radio Nav page missing ILS identifier

### ISSUE THREAD

**Issue by Akkifriman** [flybywiresim/a32nx#2273]
**Mod Version**

Master from 2020-12-04   322619 kB

**Describe the bug**

Entering an ILS approach in the MCDU do not give the Rwy ILS for instance 22L/ 109.5 but reads:  LS  ....../109.50

**To Reproduce**

1. Entering ILS rwy 22L or any other approach, potentially if applicable in addition certain STAR, Enter
2.Go to Rad/Nav page
3.Check ILS rwy (see photo enclosed)
![Skärmklipp](https://user-images.githubusercontent.com/70971118/101331894-e12b3880-3874-11eb-85a8-0ef19ee09a2a.JPG)

**Expected behavior**

**Actual behavior**

**References**

![image](https://user-images.githubusercontent.com/1857322/103394878-6bd91d80-4b2b-11eb-8003-9724b2a011ab.png)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Mega-Touk** [comment]
this is a wonderful use of an issue template. you nailed it

**Comment by Akkifriman** [comment]
OK, I am sorry, new to this...hope the message was understandable..

**Comment by Benjozork** [comment]
No IRL references are provided. 


Please correct that or we can't know what the real layout is

**Comment by Akkifriman** [comment]
Well, thats the problem: I feed the STAR and ILS is set to for instance rwy 22L (109,5) but randomly nothing show up on the RAD/NAV page (enclosed) or randomly only frequency (109,5) beyond the /.
It should read 

**ILS
22L / 109.5** 
I am not sure if some data is missing in Navigraph beta, but they claim there is no data failure.
![RAD_NAV_MCDU](https://user-images.githubusercontent.com/70971118/101644862-fef3cb80-3a35-11eb-9380-7c6c91b22811.JPG)

**Comment by Akkifriman** [comment]
Your latest Development stand version works GREAT! in combination with the 1.11.7.0 Update that came today. Just some minor issues as of above.

**Comment by Watsi01** [comment]
Yes, this is a known issue. We are on that. But I don't know the state of it right now.

**Comment by St54Kevin** [comment]
@Akkifriman Hi. The display of the identifiers is limited to the reception signal of the navaid. Are you on that airport when entering it or within 15nm airborn? For me the input is working on my test airports like EDDF EDDW and EDDM

**Comment by Akkifriman** [comment]
Ive just tested again with the latest Developer modd installed and could get the ILS notified in the MCDU RAD/NAV page despite of being closer than 15 miles away from rwy 22L at **EKCH (Copenhagen)**. After having entered the frequency ( it would not take the 22L text, the ILS worked fine on the glide scope. I have 11 photos taken from the ND and MCDU, will it serve any purpose the upload them?

**Comment by lukecologne** [comment]
> ( it would not take the 22L text, the ILS worked fine on the glide scope. I have 11 photos taken from the ND and MCDU, will it serve any purpose the upload them?

@Akkifriman The ident of the ILS is not 22L. That's just the runway number. I looked up the ILS ident for EKCH 22L, and it's OXS.

**Comment by St54Kevin** [comment]
> Ive just tested again with the latest Developer modd installed and could get the ILS notified in the MCDU RAD/NAV page despite of being closer than 15 miles away from rwy 22L at **EKCH (Copenhagen)**. After having entered the frequency ( it would not take the 22L text, the ILS worked fine on the glide scope. I have 11 photos taken from the ND and MCDU, will it serve any purpose the upload them?

An entry of 22L is not possible in an Airbus. You have to enter its actual identifier. Also you cannot enter an ILS via its identifier. You take the frequency or set it up via the arrival page

**Comment by Akkifriman** [comment]
No I am very confused:
-however it might be that the A320neo has a different graphic interface than the previous Airbus version?(See above the interface of RAD/NAV I am used to)
I have always selected the expected rwy ILS (i.e. 22L) on the Arrival page and also the actual STAR ( i.e. ERNOV1N) and got as result the ILS for 22L + frequency as of above. Now you say this is not correct (anymore)? OK, I saw that the RAD/NAV page show the OXS and corresponding frequency but is this really correct? ( with reservation for that the neo has a different setup which I dont know about)
Can we sort this out?

Another issue is the ND showing the approach not correctly: Arrival from the south instead via STAR "MONA1N" to rwy 22L should take you east of Copenhagen towards Malmoe and then a left turn for 22L ILS arrival - however the ND draw a approach West of Copenhagen with a right turn...I dont understand why- is it a Navigraph error or the MCDU/ND error? The FSX Airbus always provided the correct pathways.
![ERNOV 1N](https://user-images.githubusercontent.com/70971118/101777834-5015c500-3af3-11eb-9391-7b0c44788881.JPG)

The ND by MONA1N:
![Missing STAR EKCH_LI](https://user-images.githubusercontent.com/70971118/101778010-90754300-3af3-11eb-94e6-2bb015848f9b.jpg)
![MONA1N STAR3](https://user-images.githubusercontent.com/70971118/101778037-9b2fd800-3af3-11eb-8bf1-a5a325f74b15.JPG)

**Comment by Akkifriman** [comment]
I must admit that you are right and I am wrong regarding the Arrival page > RAD/NAV. The LS (not ILS) is a more correct version of the MCDU setup. I just tested the latest version of the Development mod and arrival to ESSA rwy 26 worked out correctly:
![Skärmklipp3](https://user-images.githubusercontent.com/70971118/101886235-7e4edf80-3b9b-11eb-8ad2-d1c89662f319.JPG)
![Skärmklipp1](https://user-images.githubusercontent.com/70971118/101886414-b9e9a980-3b9b-11eb-89f1-82f016a60a8e.JPG)
The RAD/NAV reads finally LS/FREQ  (ESA) (110.1) which is correct. In this approach the ND show the arrival correct in line with Navigraph, which is not the case in my previous post above regarding MONA1N arrival to rwy 22L EKCH. **WHY?**

**Comment by MisterChocker** [comment]
Reference:
![image](https://user-images.githubusercontent.com/1857322/103394874-5c59d480-4b2b-11eb-9c27-78608ad00bc5.png)

**Comment by MisterChocker** [comment]
Fixed on latest master
![image](https://user-images.githubusercontent.com/1857322/104447490-293c2a00-559c-11eb-8741-9aded71109b1.png)
