### ISSUE TITLE
AP not following nav and bank to death

### ISSUE THREAD

**Issue by frankkopp** [flybywiresim/a32nx#2276]
**Mod Version**
  "built": "2020-12-07T06:20:00+00:00",
  "ref": "",
  "sha": "",
  "actor": "DerL30N <leon.beeser@yahoo.de>",
  "event_name": "manual"

**Describe the bug**
I have the AP issue again where it does not follow nav but instead banks very hard (>25°) and goes into a dive. Very similar to the issue a few days back after the last MSFS update. I have uninstalled the mod, started a flight without mod and re-installed the mod via installer. Still not working. I made video of my whole startup from C&D and cut out the start and AP part (issue starts when turning on AP 1:15): 
https://www.dropbox.com/s/nalhfh98qoqcwy5/A320nFbW_AP.mp4?dl=0

Issue was not there last night (German CET time) so it might have to do with the latest commits. I did the exact same flight and process as last night.

**To Reproduce**

Route entered in MCDU after C&D start at gate:
-EDLP/24 F210 GISDI1W GISDI Y13 ALEXU N850 GISEM Z10 RUDUS Z738
 NOKDI Y163 NEKLO Y171 INKAM N850 KRH KRH1E EDDS/07
- process more a less by the book
- see video of the actual issue (have a full video from C&D state as well)

**Expected behavior**

turning on AP should follow the navigation and not bank and crash

**Actual behavior**

Banks very hard (>25°) and dives to crash

**References**

https://www.dropbox.com/s/nalhfh98qoqcwy5/A320nFbW_AP.mp4?dl=0

**Additional context**

Was this working before/when did the issue start occurring?
Worked last night (18h before now) 

Is this a problem in the vanilla unmodded game?
Havn't check but because of the AP issue in the ASOBO a320 this test wouldn't mean much

Discord username (if different from GitHub): Cdr_Maverick

![Screenshot 2020-12-07 151333](https://user-images.githubusercontent.com/16833201/101363605-e3f05280-38a1-11eb-816b-c73439877997.png)

**Comment by Benjozork** [comment]
You can see your flight director wants to go to the right to correct the bank. That means this is not an AP issue, but rather that you need to set a deadzone on your controller in sensitivity settings.

**Comment by frankkopp** [comment]
> You can see your flight director wants to go to the right to correct the bank. That means this is not an AP issue, but rather that you need to set a deadzone on your controller in sensitivity settings.

Yes, did more testing. Indeed my Thrustmaster Joystick was not in the middle in the systems settings. Never had this before. Unplugging and replugging fixed it. No everything works again. Sorry for the fuss.
