### ISSUE TITLE
THE PLANE SWINGS 

### ISSUE THREAD

**Issue by vamvas1** [flybywiresim/a32nx#2281]
the plane after 15000 feet swings like a boat left right

**Comment by Benjozork** [comment]
1. Fixed in master

2. Don't delete the template we provide

**Comment by vamvas1** [comment]
thank you i hope with the master to solve this

**Comment by AdmiralArtemiy** [comment]
In the latest dev. for today the swinging a bit from left to right on the cruise came back. In a dev. ver. before there was not this bug,
