### ISSUE TITLE
Backup Attitude indicator gone

### ISSUE THREAD

**Issue by dpoos** [flybywiresim/a32nx#2282]
**Mod Version**

"built": "2020-12-07T06:20:00+00:00",
  "ref": "",
  "sha": "",
  "actor": "DerL30N <leon.beeser@yahoo.de>",
  "event_name": "manual"

**Describe the bug**

The backup attitude indicator has stopped working.  Black box displays. All other instrumentation working.  Had been working with other builds, but stopped after USA update and hot patch.  I use the A32NX_Downloader to download the most recent "Development" version of aircraft, but appears to be present for me on the stable version as well.

**To Reproduce**

1. Activate the model in MSFS2020. Backup Att. Indicator stays off entire time.  Have tried using the + key to increase brightness but still nothing there.
2. Had worked in previous builds. Seemed to stop working after USA update and next mini patch.

**Expected behavior**

I'd like to figure out how to get instrument working again.

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Not sure. I try to not use the MSFS 2020 Default A320 if possible.

Discord username (if different from GitHub):

dpoos.  By the way, you guys (and gals if any present) are doing a fantastic job with this project.  I am a non-computer person (flight simmer only) and find this stuff to be "like magic" to me.  THANK YOU.   Dean

**Comment by Paikanx** [comment]
Same issue with backup ISI. Last time I tried, it works with Vanilla Airbus.

**Comment by dpoos** [comment]
Thank you Paikanx, yes, I can confirm that it (the back us ISI) is working in the default A320.  But the catering truck still goes to front starboard door in the default as well.  I also noticed that the pre warning audio (the chirp...chirp...chirp...advising that the APU fire test can be run) has also been lost on the development version.
Dean

**Comment by Benjozork** [comment]
The catering truck issue is unrelated to the mod and happens at badly made gates.

**Comment by LoungeFlyZ** [comment]
Not able to replicate on the lastest dev build.  

![image](https://user-images.githubusercontent.com/1360936/101537410-499b1800-3950-11eb-8ded-e109585c5d1e.png)

**Comment by Paikanx** [comment]
-- remove all add-on
-- start a flight C&D
=> ISI OK

-- Stop FS
-- Add A320NX
-- start a flight C&D
=> ISI OK
-- Exit flight
-- start a flight C&D
=> ISI OK

-- Stop FS
-- Add livery
-- Start FS
-- start a flight with default livery C&D
=> ISI OK
-- Exit flight
-- start a flight with a custom livery C&D
=> ISI OK
-- Exit flight
-- start a flight with a custom livery C&D
=> ISI OK

-- Stop FS
-- Add all my list of add-ons
-- start a flight with default livery C&D
**=> ISI KO**
![fs](https://user-images.githubusercontent.com/35568876/101631542-cb5c7580-3a24-11eb-860a-9654dcbfbb4f.png)

-- Exit flight
-- Stop FS
-- Remove all addons except A320NX
-- Start FS
-- start a flight with default livery C&D
=> ISI OK

So it seems to be a conflict or something like that. Liveries don't seem to be the problem.

**Comment by Paikanx** [comment]
So....I have done some more test, UWA's light mode seems to be the issue, using MSFS addons linker, it appears this mod generate a conflict with A32NX. By removing it, ISI came back normaly and it also resolve an issue with Flood light (it was a binary switch for me, full shutdown or full light, now the knob works as it should). So if the OP has UWA's light mod then he should try to remove it (at least the A320 part).

**Comment by dpoos** [comment]
Benjozork, LoungeFlyZ and Paikanx,
Thank you all for looking in to this. I do appreciate it!  I do use UWA's light mode for the A320.  I'll delete it a give it a go.  As for the Catering truck issue...good to know about the airport vehicles being bugged.  I just thought my ground handlers were in extreme need of drivers ed. course.
Again, thank you all for your time and efforts.
Dean
