### ISSUE TITLE
Yellow elec Hydro pump

### ISSUE THREAD

**Issue by Roboplayer999** [flybywiresim/a32nx#2288]
**Describe the feature you'd like to see implemented**
The Yellow elec Hydro pump on the overhead panel is used to pressurize hydraulics without the engines (used for flaps before engine start), it works with the APU, Ground power and the batteries although the batteries are rarely used as the get empty fairly quickly

**References**
![image](https://user-images.githubusercontent.com/69807128/101488124-7a367e00-395f-11eb-85a8-73a84db33fc2.png)

**Comment by Watsi01** [comment]
The hyrdaulic systems are in the work right now (as we speak). They should be implemented with the next _stable_ release. Well... it's done when it's done.

**Comment by Roboplayer999** [comment]
Ok, thank you for the fast response

**Comment by komp1821** [comment]
Just to clarify: Yellow Elec pump is **never** powered by batteries... That's literally impossible.

**Comment by tareksabet** [comment]
closing now as the HYD system is WIP and will be released soon.
