### ISSUE TITLE
[REQUEST] Add vertical profile prediction / VDEV

### ISSUE THREAD

**Issue by krangerich** [flybywiresim/a32nx#2293]
**Is your feature request related to a problem? Please describe.**

add realism 

**Describe the feature you'd like to see implemented**

For the descent, a vertical profile should be calculated (this might already be part of the pseudo waypoints PR). 

A deviation from the vertical profile should be indicated
* on the MCDU PROG page: deviation from the vertical profile should be shown in NAV mode in line 2R of the PROG page
* next to the altitude tape should be a green/magenta (?) dot ("donut")
* On the ND display, the interception point of the current flight path with the vertical profile is shown (see reference)

**References**

![image](https://user-images.githubusercontent.com/7890659/101543513-a0cad800-39a4-11eb-94f6-f6773ac9e1db.png)
![image](https://user-images.githubusercontent.com/7890659/101543702-dff92900-39a4-11eb-8442-645f583d09f0.png)
![image](https://user-images.githubusercontent.com/7890659/101543820-08812300-39a5-11eb-8d71-1392aa34a6bd.png)
![image](https://user-images.githubusercontent.com/7890659/101543866-22226a80-39a5-11eb-99ea-452b347025ad.png)

ND Display:
![image](https://user-images.githubusercontent.com/7890659/101544215-94934a80-39a5-11eb-8150-f63ee1cf3a5b.png)

Might require more references, because the logic seems to be rather complex?

**Additional context**

n/a

Discord username (if different from GitHub):
n/a

**Comment by MisterChocker** [comment]
might be done by #2155

**Comment by michaeldinozzo** [comment]
Fyi already requested here https://github.com/flybywiresim/a32nx/issues/1475

**Comment by jsid87** [comment]
This feature is really nice to be able to insert waypoint and get "vdev". Do you have any info when can we expect this?

**Comment by MisterChocker** [comment]
@jsid87 its wip.
