### ISSUE TITLE
[BUG] WX radar not showing fully on rose LS, VOR, and NAV

### ISSUE THREAD

**Issue by ebok1234** [flybywiresim/a32nx#2297]
**Mod Version**

"master" version

{
  "built": "2020-12-08T20:31:17+00:00",
  "ref": "",
  "sha": "",
  "actor": "pepperoni505 <49950581+pepperoni505@users.noreply.github.com>",
  "event_name": "manual"
}

**Describe the bug**

When in flight, the Rose - LS, VOR, and NAV settings do not show the full weather radar. It only shows half of the weather radar

**To Reproduce**

1. Take off from CYYC (live weather conditions) -- basically cloudy up to FL290
2. Get to cruising altitude
3. Change the rose settings on the ND to either LS, VOR, or NAV

**Expected behavior**

I was expecting the weather radar to show fully

**Actual behavior**

The weather radar only took of half of the screen on the ND

**References**

![Screenshot (48)](https://user-images.githubusercontent.com/74332080/101553040-d2be4900-3968-11eb-8498-0a225e68ef6d.png)
![Screenshot (49)](https://user-images.githubusercontent.com/74332080/101553042-d356df80-3968-11eb-8563-e7505777c369.png)
![Screenshot (50)](https://user-images.githubusercontent.com/74332080/101553044-d4880c80-3968-11eb-8746-95ad452d5175.png)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub): kobe69ebok#8600

**Comment by beheh** [comment]
The weather radar cannot see behind the aircraft - it's in the nose cone. This was intentionally changed in #1458, so I don't think this is a bug.

**Comment by ebok1234** [comment]
> The weather radar cannot see behind the aircraft - it's in the nose cone. This was intentionally changed in #1458, so I don't think this is a bug.

Ah okay, thank you. I didn't even think of that
