### ISSUE TITLE
[BUG] Wipers working while off.

### ISSUE THREAD

**Issue by TansyEliot** [flybywiresim/a32nx#2312]
**Mod Version**

2020-12-09T05:40:56+00:00

**Describe the bug**

Wipers working while off.

**To Reproduce**

1. Start cold and dark
2. Turn ON Battery.
3. See wipers.
4. Try move wipers button -> INOP

**Expected behavior**

They should be stopped,

**Actual behavior**

![image](https://user-images.githubusercontent.com/72763559/101640269-123f7080-3a0f-11eb-9f6e-0722c3151b06.png)

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Yes, this was working before, the issue start ocurring after latest development version.

Is this a problem in the vanilla unmodded game?
No.

Discord username (if different from GitHub): TansyEliot#9914

**Comment by beheh** [comment]
See https://github.com/flybywiresim/a32nx/discussions/2298.

This is most likely due to "your controls" being in your community folder. Please remove that, and see if this issue persists.

**Comment by pepperoni505** [comment]
This issue is fixed with the most recent YourControls update - https://github.com/Sequal32/yourcontrols/releases/tag/2.3.2

**Comment by TansyEliot** [comment]
> 
> 
> See #2298.
> 
> This is most likely due to "your controls" being in your community folder. Please remove that, and see if this issue persists.

> 
> 
> This issue is fixed with the most recent YourControls update - https://github.com/Sequal32/yourcontrols/releases/tag/2.3.2


Ok, thank you! Going to check rn.

**Comment by TansyEliot** [comment]
Worked.
