### ISSUE TITLE
[BUG] Activites/Ladning challenges not working when a32nx is installed

### ISSUE THREAD

**Issue by MuppetOwl** [flybywiresim/a32nx#2320]
**Mod Version**
Have been like this for the 5-6 latest dev releases

**Describe the bug**
Activities/Landing challenges does not work/start when a32nx is installed. 
Error is "Item Not downloaded" Works when mod is removed.

**To Reproduce**
1. Go to activities menu
2. start any landing challenges with the A320.

**Expected behaviour**
Start the landing challenges

**Actual behavior**
Error Item not downloaded

**References**
![content not downloaded](https://user-images.githubusercontent.com/33086105/101662672-15a41d80-3a4a-11eb-8e6f-9d612f04387c.PNG)

Is this a problem in the vanilla unmodded game?
No

**Comment by MapleNAV-TCASFAULT** [comment]
Due to the future FBW implementation, Asobo made the A32NX incompatible with the landing challenges using the a320neo
