### ISSUE TITLE
[REQUEST] Make the radio knobs turn faster

### ISSUE THREAD

**Issue by jf96g** [flybywiresim/a32nx#2321]
**Is your feature request related to a problem? Please describe.**

The default radio knobs of the a320 turn very slowly, so when you are flying on Vatsim or any other online service it becomes a pain every time they tell you to change frequency.

**Describe the feature you'd like to see implemented**

It would be great if the radio knobs turned faster so changing frequencies wasn't a pain and took your attention from flying for so long.

**References**

**Additional context**

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by lukecologne** [comment]
Duplicate #2002
