### ISSUE TITLE
Cant install the plane

### ISSUE THREAD

**Issue by CptRPeralta93** [flybywiresim/a32nx#2323]
Hello Everyone,

I´ve download the latest version on the A320nx today, i install the same way i did before, and when i star the game, it only appear the standard version on the a320neo.. i´ve copy the A320NX folder to my community folder and nothing happen. What am i doing wrong?

**Comment by Benjozork** [comment]
Hello, please open a thread in the "Discussions" tab as this is for formal bug reports.

**Comment by CptRPeralta93** [comment]
> Hello, please open a thread in the "Discussions" tab as this is for formal bug reports.

ok, i will. thks
