### ISSUE TITLE
[BUG] Cant install the plane

### ISSUE THREAD

**Issue by CptRPeralta93** [flybywiresim/a32nx#2325]
**Mod Version**

**Describe the bug**
I´ve download the latest version on the A320nx today, i install the same way i did before, and when i star the game, it only appear the standard version on the a320neo.. i´ve copy the A320NX folder to my community folder and nothing happen. What am i doing wrong?

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by LoungeFlyZ** [comment]
Delete the folder you copied into your community folder and grab the installer from here: https://github.com/Externoak/A32NX-installer/releases/latest/download/A32NX_Downloader.zip  Run that and use it to install either the latest Dev or Stable release.

**Comment by CptRPeralta93** [comment]
> Delete the folder you copied into your community folder and grab the installer from here: https://github.com/Externoak/A32NX-installer/releases/latest/download/A32NX_Downloader.zip Run that and use it to install either the latest Dev or Stable release.

thank you. it works. btw, why does the v speeds no longer appear allready set up in fmc?

**Comment by Benjozork** [comment]
In the future, please open a thread in the "Discussions" tab like asked on your other issue.

**Comment by CptRPeralta93** [comment]
> In the future, please open a thread in the "Discussions" tab instead like asked on your other issue🙂

ok i will :)
