### ISSUE TITLE
[BUG] No "Retard" callout on Landing

### ISSUE THREAD

**Issue by speedbird5** [flybywiresim/a32nx#2336]
**Mod Version**

Dev Version "built": "2020-12-10T04:54:58+00:00"

**Describe the bug**

No "Retard " call on landing

**To Reproduce**

1.  Manually land the aircraft with Autothrottle engaged.

**Expected behavior**

"Retard" callout at about 10-20 feet on landing

**Actual behavior**

No "Retard" callout

**Additional context**

Was this working before/when did the issue start occurring?
Not sure.

Is this a problem in the vanilla unmodded game?
No.  It works on standard Asobo A320

**Comment by connormiller05** [comment]
I have the same issue, no RETARD callout on the latest dev build. Works fine on the default though.

**Comment by tush0701** [comment]
Finally, the sound was there today, anyone else heard it??

**Comment by speedbird5** [comment]
> Finally, the sound was there today, anyone else heard it??

Development version or Stable ?

If development which one exactly ?

**Comment by tush0701** [comment]
Development version
{
  "built": "2020-12-11T05:42:25+00:00",
  "ref": "",
  "sha": "",
  "actor": "Kimbyeoungjang <kim9431237@naver.com>",
  "event_name": "manual"
}

**Comment by speedbird5** [comment]
I just tried the same version and it still does not work.

  "built": "2020-12-11T05:42:25+00:00",
  "ref": "",
  "sha": "",
  "actor": "Kimbyeoungjang <kim9431237@naver.com>",
  "event_name": "manual"

**Comment by tush0701** [comment]
Try keeping throttle up until 20feet(like IRL) and then flare. 

If you flare before that, there is no retard sound.

**Comment by speedbird5** [comment]
> Try keeping throttle up until 20feet(like IRL) and then flare.
> 
> If you flare before that, there is no retard sound.

Tried that but it's not working.

**Comment by tush0701** [comment]
Now stopped for me also..
