### ISSUE TITLE
Dir mode not working properly

### ISSUE THREAD

**Issue by Roboplayer999** [flybywiresim/a32nx#2338]
**Mod Version**
A32NX-master 2020-12-10T04:51:38+00:00

**Describe the bug**
When I select a waypoint on the direct page it should delete all waypoints before the waypoint selected, it has worked in previous versions

**To Reproduce*
1.Create FP
2.Select waypoint on DIR page
3.press Direct

**Expected behavior**
Delete all waypoint skipped by selecting the Dir waypoint

**Actual behavior**
Does go there but follows the FP back and does not delete the waypoints

**References**
![Screenshot (93)](https://user-images.githubusercontent.com/69807128/101754154-b559be00-3ad3-11eb-8be8-6ed36594a3b3.png)

**Comment by Benjozork** [comment]
Tracked in #1745
