### ISSUE TITLE
[BUG] asymmetric engine Values for more realism

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#2339]
**Mod Version**

master

**Describe the bug**

I notice that all values are exactly the same for each engine, like fuel flow, EGT or  oil temp or press.
it would be so more realistic when there are small differences between each side. fuel flow is nearly the same, shure, but EGT in real life is nearly never the same on both engine. 

**To Reproduce**

1. look at the values for FUEL flow , EGT, oil temp/press etc
2.
3.

**Expected behavior**

small differences on each engine

**Actual behavior**

same for both engines

**References**

**Additional context**

Was this working before/when did the issue start occurring?
no
Is this a problem in the vanilla unmodded game?
yes

Discord username (if different from GitHub):

**Comment by hotshotp** [comment]
that is actually a great idea, i will relay this to our engine dev

**Comment by mikecbr** [comment]
Also should be a delay , the actual aircraft accelerate instantly , so unrealistic
