### ISSUE TITLE
[BUG] INSERT TITLE HEREWrong message in PERF TAKE OFF page

### ISSUE THREAD

**Issue by pacha35** [flybywiresim/a32nx#2342]
**Mod Version**

0.4.2 dev
**Describe the bug**

On the MCDU, when I try to enter a speed (V1, VR, V2) this message is display (orange colour) on the scratchpad : "V1/VR/V2 DISAGREE".
The message is not shown when the after 3 speeds are written
**To Reproduce**

1. this arrive when the aircraft is ready to take off (choise "on the runway" at the world map page.
2. this is a new problem, I have not this problem with 4.1 version.
3.

**Expected behavior**

I expect nt to have this warning message when I enter speeds in TAKE OFF page of the MCDU
![Image41](https://user-images.githubusercontent.com/46076619/101806537-5ff1d100-3b14-11eb-9c3c-5aa652a6f6b5.jpg)

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by ilyeshammadi** [comment]
This is not a bug, it's actually a feature that check if the speeds are set correctly.

**Comment by Watsi01** [comment]
Just put the speed in from bottom up, and you won't have the message.
