### ISSUE TITLE
Heavy waving with the Wings

### ISSUE THREAD

**Issue by Reutii** [flybywiresim/a32nx#2344]
**Mod Version**

**Describe the bug**

I`ve got a hue waving with the wings. After I take off and engange the autopilot i hvae max. 2 min a stabel flight. After that 2 min the Airbus starts smoothly waving with the wings. It increase that waving pretty fast and pretty heawvy. I`ve got a pretty heavy bank angle. I would say 20 degress minimum.

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning

**Comment by Reutii** [comment]
?

**Comment by Benjozork** [comment]
"if this line is not removed and/or the issue template is not respected, my issue will be closed without warning"

**Comment by wpine215** [comment]
Basically, you need to fill out every part of the template and follow the instructions. We receive countless issues and it helps us keep track of them and address them properly.
