### ISSUE TITLE
[BUG] Next closest Waypoint causes troubles

### ISSUE THREAD

**Issue by lve0200** [flybywiresim/a32nx#2345]
**Mod Version**

 latest Dev Master

**Describe the bug**

If next closest Waypoint is a RWY, the plane leaves the APP path and flies OVH RWY at APP altitude. Plane flies directly from DH609 to RW15. Same applies if next WP is farer away as last RWY WP during TO. If AP is engaged too early (in distance) Plane turns back at 45 bank to RWY, which is most likeliy reason for death roll (in non modified PID settings)

**To Reproduce**

1. Fly e.g. EDDH ILS RWY 15 via NOLGO1P!! I know its not the right APP, but is shows clearly the problem!
2.
3.

**Expected behavior**

Plane should follow APP or initial climb w/out shortcutting the path.

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Can't say, but long lasting

Is this a problem in the vanilla unmodded game?
n/a

Discord username (if different from GitHub):

**Comment by lve0200** [comment]
Just found, its a 1253 duplicate, but consider that it also can happen backwards and cause sharp back turn to RWY at TO = death roll

**Comment by WoodyWoodsta** [comment]
Ah yes. I was going to open a bug about this but I couldn't quite figure out what the actual conditions were. I had this flying into EGKK via KIDL1G. I thought it was the flight phase switching from descent to approach that triggered the direct-to runway behaviour, but it makes sense that this arrival (and subsequent approaches for that matter) flies close to the runway along it's path.
