### ISSUE TITLE
[BUG] Fuel flow rises instantly from 0 to Idle flow 

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#2351]
**Mod Version**

master

**Describe the bug**

fuel flow instantly rises from 0 to idle fuel flow (also wrong value - real is **~300-320kg/h per ENG**) 

**To Reproduce**

1.make a engine start - look @ MFD fuel flow indication
2.
3.

**Expected behavior**

fuel flow should rise, connected to N2, and not from 0 instantly to idle fuel flow, while N2 is rising.

**Actual behavior**

fuel flow rises 0 to idle fuel flow instandly

**References**

**Additional context**

Was this working before/when did the issue start occurring?
no
Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment]
Fuel flow is bound to engine 1 thrust lever position instead of individual engine N1 or N2

**Comment by Taz5150** [comment]
Please test/ check with https://github.com/flybywiresim/a32nx/pull/5081
