### ISSUE TITLE
Audio that existed in a previous build for the Flight Warning Computers coming on line

### ISSUE THREAD

**Issue by dpoos** [flybywiresim/a32nx#2364]
**Mod Version**

I downloaded the Developers mode at 12/11/2020 at 09:00 CST.  I used the automated A320 Downloader to do this.

"built": "2020-12-11T05:42:25+00:00",
  "ref": "",
  "sha": "",
  "actor": "Kimbyeoungjang <kim9431237@naver.com>",
  "event_name": "manual"

**Describe the bug**

It appears that the audio that existed in a previous build for the Flight Warning Computers coming on line (see _Real Airbus Pilot A320 Cold And Dark Setup Tutorial: Microsoft Flight Simulator, 7:12 / 29:34, and my personal user experience, the three tones and triple chirps/clicks) has been lost in the most recent developers' build (I downloaded mine at 12/11/2020 at 09:00 CST).  This audio alert comes just before you conduct the APU fire test in the Checklist and appears to be the clue to the pilots that the system (Flight Warning Computers) is up and operational.

**To Reproduce**

1. Power up from Cold and Dark and listen for audio cues.
2. If using the checklist, this audio warning should happen just before the APU fire test is done, and is the clue to let you know that you can now do the APU fire test.
3. see _Real Airbus Pilot A320 Cold And Dark Setup Tutorial: Microsoft Flight Simulator, at 7:12 / 29:34

**Expected behavior**

Previously existing audio (three tones followed by chirp, chirp, chirp), that were present in a previous build and signal that the Flight Warning Computers are on line returns.

**Actual behavior**

Cold and dark start up process moves forward as expected, but tones/chirps are not being heard.

**References**

see _Real Airbus Pilot A320 Cold And Dark Setup Tutorial: Microsoft Flight Simulator, 7:12 / 29:34

**Additional context**

Was this working before/when did the issue start occurring?
I know that it was present in a previous build because I heard it.  I am not sure at what build point that it went inactive.

Is this a problem in the vanilla unmodded game?

Not tested with the default "vanilla" A320.

Discord username (if different from GitHub):

Keep up the great work guys (and gals).  I'm not a programmer, just a flight sim geek, so I think that you all are wizards.
Dean

**Comment by dpoos** [comment]
Bug Title: Audio that existed in a previous build for the Flight Warning Computers coming on line

Would someone please replace my blank Bug Title with the above.  Hit send too soon.  Thank you.

**Comment by lukecologne** [comment]
FYI: You can edit the title yourself

**Comment by beheh** [comment]
This has been deferred until we have a more accurate implementation of the Flight Warning Computer, which won't be for a weeks at least probably (not for this next stable release most likely, could be a few months in the worst case). Pinging @hotshotp to confirm that we'll just leave it as is for now, or whether we'll want a placeholder until the FWC rework is done.

**Comment by hotshotp** [comment]
As beHeh just mentioned, this is intended for now until we get a better implementation system for the self test

**Comment by beheh** [comment]
I'm fine with keeping this open until this is actually fixed, it's a legitimate bug report. But let's fix the title.

**Comment by dpoos** [comment]
Thank you gentlemen...sorry about screwing up the title.  Again...appreciate your time and effort.    Dean

**Comment by lukecologne** [comment]
Reopened. @dpoos, please add an appropriate title

**Comment by lukecologne** [comment]
Reopened. @dpoos, please add an appropriate title

**Comment by dpoos** [comment]
TY lukecologne.  Fixed title

**Comment by hotshotp** [comment]
fixed :)
