### ISSUE TITLE
[BUG] No "Altimeter Callouts"

### ISSUE THREAD

**Issue by Tastenklopper07** [flybywiresim/a32nx#2365]
**Mod Version**

{
 "built": "2020-12-11T05:42:25+00:00",
  "ref": "",
  "sha": "",
  "actor": "Kimbyeoungjang <kim9431237@naver.com>",
  "event_name": "manual"
}

**Describe the bug**

I haven't had any altimeter callouts for over a month now. I've reinstalled the sim several times, but unfortunately it didn't work.
I can still hear one thing from the GPWS, I think it was something with "terrain".

**To Reproduce**

1. I can't remember exactly, but as always I downloaded the latest dev version (sometimes also stable) of the A32NX using the installer and at some point I lost altimeter callouts.
2. I dont have any altimeter callouts. (2500ft, 1000ft, 500ft, 400ft, 300ft, 200ft, 100ft, 50ft, 40ft, 30ft, 20ft, 10ft, 5ft and retard)
3. /

**Expected behavior**

I would have expected the altimeter callouts to appear, but they do not, even after several reinstallations.

**Actual behavior**

The altimeter callouts dont appear.

**References**

/

**Additional context**

Was this working before/when did the issue start occurring?

i think almost 2 months, but i dont know exactly.

Is this a problem in the vanilla unmodded game?

i dont know, because my sim is currently always stuck in loading screen, so i need to fix that first.

Discord username (if different from GitHub): Tastenklopper07#3676

**Comment by hotshotp** [comment]
cannot reproduce

**Comment by hotshotp** [comment]
Closing as no response and not being able to reproduce
