### ISSUE TITLE
[BUG] Same wing sound as take-off on bounce of aircraft

### ISSUE THREAD

**Issue by tush0701** [flybywiresim/a32nx#2378]
**Mod Version**
Latest Dev version

**Describe the bug**
If an aircraft bounces, even minimally on the runway after touchdown, the same wing sound(vibration) is heard that is heard at T/O config during take-off. This sound should not be there during a bounce, as it is heard even on a small bounce.

**To Reproduce**

1. Land the A32NX, make a hard landing
2. Ensure that the aircraft bounces on the runway(even a small bounce would do)
3. Take-off wing sound heard as if we are taking off

**Expected behavior**
A separate/no sound for wings during a bounce

**Actual behavior**
Take-off wing sounds are heard on a bounce

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
No, as there are no distinct take-off wing sounds on the vanilla A320NEO

VIDEO ATTACHED :

[Sample bounce.zip](https://github.com/flybywiresim/a32nx/files/5682697/Sample.bounce.zip)

Discord username (if different from GitHub):

**Comment by beheh** [comment]
Pinging @hotshotp

**Comment by hotshotp** [comment]
i figured out what causes the problem! I apologize for this bug. Will make a pr with a fix today

**Comment by tush0701** [comment]
Thank you so much for the amazing work!
