### ISSUE TITLE
Overspeed band too high; should be lowered. (EDITED)

### ISSUE THREAD

**Issue by CesarEPerez** [flybywiresim/a32nx#238]
Getting "overspeed" warning while not being overspeed.
EDIT: I am actually overspeeding, it's the red band that is incorrect and should be lowered.
![image](https://user-images.githubusercontent.com/60581357/91652229-1993cd00-ea63-11ea-9adf-2e6b07c36b3d.png)

**Comment by PCGamesF1Tech** [comment]
Technically you are overspeeding at M. 083 (just numberwise, although still not in the red band.
Mmo is 0.82.

**Comment by CesarEPerez** [comment]
Oh, thank you for letting me know! So the red band should be the one that is lowered further?

**Comment by PCGamesF1Tech** [comment]
Yep!
The 300kts also seem pretty fast to me at FL340 (or 34.000ft, to be exact ;-)
Impressive however 😄

**Comment by CesarEPerez** [comment]
Yeah, I'm a little bit impatient LOL. What would be the normal cruising speed at that height? About 280?

**Comment by nobodyn0se** [comment]
Depends on the Cost Index you've chosen. 280/300 kts Indicated Airspeed is well within normal limits.

**Comment by PCGamesF1Tech** [comment]
> Yeah, I'm a little bit impatient LOL. What would be the normal 

> Yeah, I'm a little bit impatient LOL. What would be the normal cruising speed at that height? About 280?

I will check after vacation, somewhere around FL340 to have the same impression

**Comment by AdenFlorian** [comment]
I just merged in my fix which makes sure the the red vmax barber pole and the ecam overspeed warning are using the same logic, so you shouldnt hear the overspeed warning without being inside the red zone anymore. If anyone finds that the vamx is incorrect at any point, please open a new issue for that, thanks!
