### ISSUE TITLE
NO SMOKING (AUTO) chime should play when it auto turns on/off

### ISSUE THREAD

**Issue by AdenFlorian** [flybywiresim/a32nx#239]
This is issue on dev-0.1.1 branch.
Confirmed real life functionality with Milu and XavMan92NZ.

Current:
(after this PR is merged: https://github.com/wpine215/msfs-a320neo/pull/240)
When NO SMOKING is AUTO, and landing gear comes up or down and the NO SMOKING get auto turned off or on, no chime plays.

Expected:
When NO SMOKING is AUTO, and landing gear comes up or down and the NO SMOKING get auto turned off or on, the chime plays.

**Comment by AdenFlorian** [comment]
Can probably do this by adding conditions or something to the sound.xml to make it dependent on the landing gear.

A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/sound/sound.xml

**Comment by AdenFlorian** [comment]
Maybe we should make a local simvar thats just like XMLVAR_NO_SMOKING_ACTIVE which can be used by the ecam logic and the sound logic.

**Comment by Curtis-VL** [comment]
Please close the issue once the pull request has been merged! 👍
