### ISSUE TITLE
[BUG] Altitude constraints from STAR are being used during departure

### ISSUE THREAD

**Issue by zoideberg8000** [flybywiresim/a32nx#2390]
**Mod Version**
{
  "built": "2020-12-08T08:51:29+00:00",
  "ref": "",
  "sha": "",
  "actor": "pepperoni505 <49950581+pepperoni505@users.noreply.github.com>",
  "event_name": "manual"
}

**Describe the bug**

Altitude constraints from STAR being used by AP during departure
Using the following route which I entered manually
LSZH/16 VEBI3S VEBIT T51 LASUN UN176 LUMEL UT10 RLP UL613 DIDOR UT10 ALESO ALES1H EGLL/27R
FL360

The SID has 7 constraints
2000 not before D1.0 KLO
2500 at D2.1 KLO
+4000 at KLO R180/R360
+4000 at KLO R360
+5000 at BREGO
+6000 at ZH554
+7000 at ZH558

Initial clearance was FL100 - then I stopped using ATC and set to cruise (FL360) in managed climb mode, however the PFD showedFL180 in magenta and did not climb past it. The FL180 constraint is the first constraint from the ALES1H STAR (FL180 at ETVAX). I have had this issue on other flights where the STAR has altitude constraints.

**To Reproduce**
1. Enter flight plan as above
2. Takeoff and set altitude to anything above FL180

**Expected behavior**
Once passing D2.1 KLO - any altitude selected above FL70 (and also FL180) should be blue and the aircraft should continue to climb in managed climb mode

**Actual behavior**
Altitude above FL180 is magenta and aircraft will not climb past FL180 unless in open climb mode

**References**

[IMG_0716.zip](https://github.com/flybywiresim/a32nx/files/5683414/IMG_0716.zip)

**Additional context**

Was this working before/when did the issue start occurring?
It has been a problem for about 2 weeks

Is this a problem in the vanilla unmodded game?
I am not sure

Discord username (if different from GitHub):

This is my first issue report so apologies if it is not submitted correctly. I have searched both open and closed issues and I don't see one that directly matches this issue (although I can confirm that all constraints are being read as below xxx instead of at or above as applicable but I see that is a separate issue that is already reported).

**Comment by beheh** [comment]
Possibly related to #2092. Maybe @MisterChocker has an idea why this happens?

**Comment by MisterChocker** [comment]
This happens because the algorithm no longer finds the TOC due to changes that broke it afterwards.
