### ISSUE TITLE
[BUG] ADF ND Overlay Not Working/ADFs Not Received

### ISSUE THREAD

**Issue by medic6810** [flybywiresim/a32nx#2416]
**Mod Version**
master 
{
  "built": "2020-12-13T17:46:12+00:00",
  "ref": "",
  "sha": "",
  "actor": "hotshotp <70779662+hotshotp@users.noreply.github.com>",
  "event_name": "manual"
}

**Describe the bug**
ADF tuned via the MCDU. Within range of ADF. ADF direction from present position should appear on ND when 1 or 2 overlay needle activated on ND mode panel.  ADF needle overlay does not appear on ND. ADF identifier flashes on and off in lower left corner of ND. No direction ever displayed. Happens with both ADF1 and ADF2 receiver.

**To Reproduce**
Steps to reproduce the behavior. 
 We need to know how you encountered the bug to properly troubleshoot the issue. 
1. Set up for ILS Approach to RW26L at KGRR.
2. Tune "GR" locator outer marker by entering 263 into ADF1 or ADF2 field on NAV/RAD page of MCDU.
3. Activate '1' or '2' RMI needle on ND mode panel and note that needle does not appear and NDB station is not consistently identified.

**Expected behavior**
 RMI needle overlay should appear on ND and NDB station identifier and frequency should both display in lower left (for ADF1) or lower right (for ADF2) corner of ND. 

**Actual behavior**
 RMI needle does not display. NDB identifier flashes on and off. 

**References**
 N/A 

**Additional context**
 This is definitely not a range issue as I flew right over the NDB station and the RMI needle never appeared. 

Was this working before/when did the issue start occurring?

Don't know.

Is this a problem in the vanilla unmodded game?

Don't know but I presume not.

**Comment by Machmeinparaillegal** [comment]
Can confirm that this is still a problem in the newest dev as of 02.01.2021

**Comment by MisterChocker** [comment]
still an issue.

![image](https://user-images.githubusercontent.com/1857322/104447777-89cb6700-559c-11eb-9b4b-d1fbb0bb3fd0.png)

**Comment by medic6810** [comment]
This is still an issue with the latest build. Additionally, VOR needles do not appear on the ND when selected - so the issue is not just limited to NDB stations. Looks like the logic for displaying RMI needles in at least ARC mode on the ND is broken. I do think I saw something when going to VOR mode, so possibly the logic driving the RMI needle in that mode could be brought over to ARC mode.

**Comment by 2hwk** [comment]
Fixed by #4953 closing ☑️
