### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by lve0200** [flybywiresim/a32nx#2422]
Hi,
I believe to remember, that when landing and after the AP was switched OFF, the AP switched automatically to LOC to stay on the center line.
I don't see this anymore. Feature or bug ?

_Originally posted by @lve0200 in https://github.com/flybywiresim/a32nx/discussions/2361_

**Comment by lve0200** [comment]
completing the info:
FD & ACFT do not maintain Center Line during manual landing. APR/LOC are ON, but seem to have no effect.
Latest dev master,
Windows store
Was'nt there in previous versions, but hard to say, when it changed
N/a in Vanilla version.

**Comment by Highflyer2010** [comment]
When doing a "Manual Landing" you have full control of the aircraft. that said theres no Autopilot at play here so even with APR/LOC buttons are switched on as the AP is dissconnected it will not have any effect so this is normal and not an issue

**Comment by lve0200** [comment]
OK, I was apparently mislead by some other information. Maybe I confused it w/ AutoLand.
There's a good AB reference for it, here
https://safetyfirst.airbus.com/lateral-runway-excursions-upon-landing/
