### ISSUE TITLE
[BUG] periodic FPS drop in cockpit/displays - STUTTER - CoherentGTDraw low

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#2428]
**Mod Version**

MASTER

**Describe the bug**

in flight, you can recognise massive stutters - see my Video. I use:

Ryzen 7 3700X
32GB 3600mhz RAM
RTx2070Super
1TB SSD
Clean win10 install, only FS2020 on the plate

as i discribe before, the stutters NOT THERE on the ground when the Plane is fully configurated... also after landing, when turning off the engines, the stutter are away. In flight you have the phenomen you can see in the VIDEO - https://www.youtube.com/watch?v=Gz6MBc2UNP8

peridodic CoherentGTDraw decrease that causes stutter. Every ~3sec a drop to 20ms - causes stutter.

NO change when i select refreshrate to LOW or HIGH in the Sim. 

When I look out of the window with no displays in sight, stutters and phenomen is gone.

also when i turn off all displays in flight, problem is gone. only minor, because the STandby instrument is still on.

**one strange behaviour - when i select VFR map On/Off, the flightplan is gone...with this also the problem and the CoherentGTDraw problem is gone, once selecting more and more waypoints, problem comes again...**

**problem seems connected with flight plan!** 

**switching off the F.O. MFD the problem is only half intense but periodic drops in MS by CoherentGTdraw are present, but less**

**To Reproduce**

1. start a normal flight, from cold&dark until cruise, stutter became more intense over time. 
2. only standing on ground, but with the whole aircraft fired up, including IRS allign, no stutter
3. turn VFR map in the menue on and off - FPL disappear, problem gone with empty Flightplan.

**Expected behavior**

smooth like on ground, without periodic stutter and drop of CoherentGTDraw value

**Actual behavior**

https://www.youtube.com/watch?v=Gz6MBc2UNP8
as you can see

video is recorded @FL380 inbound EDDF over France

**References**

**Additional context**

Was this working before/when did the issue start occurring?
no
Is this a problem in the vanilla unmodded game?
i don´t know

Discord username (if different from GitHub):

**Comment by andrejetcat** [comment]
Flightplan empty - NO ISSUE , but as soon some waypoints are inside the FMC, the discribed issue starts to become worse

**Comment by 2hwk** [comment]
Similar to #4051 should also be fixed by SU5
