### ISSUE TITLE
A320neo engine idle EGT too low/FF too high

### ISSUE THREAD

**Issue by PCGamesF1Tech** [flybywiresim/a32nx#243]
Hey,
Idle values are bit off. 
After engine start the neo shows ceo values:
N1 20%, EGT 400°C, N2 60%, FuelFlow 300kg/h

EGT should be around 570°C
Fuelflow around 270kg/h
(ISA conditions at sea level)

**Comment by Taz5150** [comment]
Working on engine modeling; I will assign to it. BTW, it’ll be great to have a complete FCOM for a Neo with Leap-1A26.

**Comment by tareksabet** [comment]
@Taz5150 Done I assigned it for you

**Comment by Taz5150** [comment]
Thanks @tareksabet. I’ll open up a PR and close it ASAP.

**Comment by Taz5150** [comment]
New engine model is calibrated to RL values at ISA:
N1 19%
N2 68%
EGT 520º
FF 300 Kg/h
