### ISSUE TITLE
[BUG] "UNTITLED" on the dark clear screen of the FUEL/PRED page after clicking to ZFW

### ISSUE THREAD

**Issue by AdmiralArtemiy** [flybywiresim/a32nx#2430]
"built": "2020-12-14T07:18:52+00:00", and then the last update of the 13th december.

Describing:
After clicking the button near the ZFW line on the FUEL/PRED page the black clear page with the only line "UNTITLED" appears with no way to bring the normal looking FUEL/PRED page and so can not enter trimming.

To Reproduce:
1. Load the flight.
2. Fill the MCDU.
3. Go to the FUEL/PRED page.
4. Click  the button near the ZFW line on the FUEL/PRED page to enter the autocalculated ZFW and trimming or enter the values manually and click the button near the ZFW.

Expected behavior:
ZFW and trimming sets into the MCDU.

Actual behavior:
After clicking the button near the ZFW line on the FUEL/PRED page the black clear page with the only line "UNTITLED" appears with no way to bring the normal looking FUEL/PRED page and so can not enter trimming.

References:
![2020-12-14_17h48_23](https://user-images.githubusercontent.com/75565950/102096504-d7d23b00-3e35-11eb-87e3-8839ae62d611.jpg)
![2020-12-14_17h48_39](https://user-images.githubusercontent.com/75565950/102096512-dacd2b80-3e35-11eb-962e-95e3b7fdb0ab.jpg)

Was this working before/when did the issue start occurring? No. 

Is this a problem in the vanilla unmodded game? No.

**Comment by beheh** [comment]
Could you please leave your exact version you were using, like in the bug template? There was a change to some code related to this today, and from your message it's unclear on which exact version you were. "Latest dev" doesn't age well.

**Comment by AdmiralArtemiy** [comment]
> Could you please leave your exact version you were using, like in the bug template? There was a change to some code related to this today, and from your message it's unclear on which exact version you were. "Last dev" doesn't age well.

  "built": "2020-12-14T07:18:52+00:00",

**Comment by beheh** [comment]
Okay, this was probably fixed by #2251 then, as that was merged later today.

**Comment by AdmiralArtemiy** [comment]
> Okay, this was probably fixed by #2251 then, as that was merged later today.

But we see new bug with this now)

**Comment by AdmiralArtemiy** [comment]
> Okay, this was probably fixed by #2251 then, as that was merged later today.

updated to the last dev - the same.

**Comment by Lucky38i** [comment]
> > Okay, this was probably fixed by #2251 then, as that was merged later today.
> 
> updated to the last dev - the same.

Hey are you still having this problem?

**Comment by AdmiralArtemiy** [comment]
> > > Okay, this was probably fixed by #2251 then, as that was merged later today.
> > 
> > 
> > updated to the last dev - the same.
> 
> Hey are you still having this problem?

It solved with the last dev.

**Comment by Benjozork** [comment]
Glad your issue is solved! Thanks for the initial report.
