### ISSUE TITLE
[BUG] APU is starting with fuel pumps off

### ISSUE THREAD

**Issue by airfirefighter** [flybywiresim/a32nx#2440]
**Mod Version**
<"built": "2020-12-14T10:21:06+00:00",
  "ref": "",
  "sha": "",
  "actor": "Harry <43104362+Snapmatics@users.noreply.github.com>",
  "event_name": "manual"

**Describe the bug**
the apu is starting with all fuell pumps off

**To Reproduce**

1. start cold and dark 
2. start the apu without open any fuel pump
3.

**Expected behavior**
apu is working when fuel are release .

**Actual behavior**
working with fuel pumps off

**References**
https://streamable.com/hmmxbx

**Additional context**

Was this working before/when did the issue start occurring?

dont know

Discord username (if different from GitHub):

**Comment by wpine215** [comment]
Working as intended. APU has its own fuel pump.

**Comment by airfirefighter** [comment]
> Working as intended. APU has its own fuel pump.

im sorry didnt know i feel stupid !
