### ISSUE TITLE
ELEC Page shows GEN2 avail while engines off

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#2442]
**Mod Version**

master

**Describe the bug**

ELEC page shows wrong state. It shows that GEN2 is hot/working/on while on ground with engines off. 

**To Reproduce**

1. cold/dark, power up, go to ELEC page on the lower ECAM - notice that GEN2 is alive
2.
3.

**Expected behavior**

GEN´s only workling, when engines on. 

**Actual behavior**

GEN2 is on, while 

**References**

actual behaviour on ELEC page

**Additional context**

Was this working before/when did the issue start occurring?
-
Is this a problem in the vanilla unmodded game?
no

Discord username (if different from GitHub):

**Comment by hotshotp** [comment]
Elec page is a place holder and doesn't fully work
