### ISSUE TITLE
[BUG] WebUI-DevKit version 0.9 incompatible with A32NX

### ISSUE THREAD

**Issue by FittedBark75** [flybywiresim/a32nx#2444]
**Mod Version**

master

**Describe the bug**

When using the [WebUI-DevKit version 0.9](https://github.com/dga711/msfs-webui-devkit/releases/tag/0.9.0) (which is currently the latest release) with the A32NX, the UI widget is broken and does not allow hot-swapping or reloading of screens.

Reverting back to version 0.8.5 fixes the issue and returns things back to normal.

See this screenshot for the error displayed on the widget:
![Screenshot (2)](https://user-images.githubusercontent.com/70783613/102132753-080fde80-3e22-11eb-8781-865070321bdc.png)

This is likely due to the DevKit changing the way it is integrated within each screen (see the link above for new integration instructions).

**To Reproduce**

1. Install [WebUI-DevKit version 0.9](https://github.com/dga711/msfs-webui-devkit/releases/tag/0.9.0) into the Community folder.
2. Load the A32NX.
3. See the error message on the various screens.

**Expected behavior**

Hot-swapping and other DevKit features should work.

**Actual behavior**

Hot-swapping does not work.

**References**

I believe the DevKit needs to be integrated slightly differently in version 0.9. It looks like it does come with some additional features that could one day be useful to have.

**Additional context**

Was this working before/when did the issue start occurring?
After installing DevKit 0.9.

Is this a problem in the vanilla unmodded game?
Not sure.

Discord username (if different from GitHub): Ray#4712

**Comment by tracernz** [comment]
Is this still an issue? It seems to be working fine for me using the new injection method in https://github.com/dga711/msfs-webui-devkit/releases/tag/0.9.0

**Comment by tracernz** [comment]
Just found where this was fixed: https://github.com/flybywiresim/a32nx/pull/2619. I guess this issue can be closed.
