### ISSUE TITLE
[BUG] The INIT FUEL PRED. page via right arrow is not available to open to enter data

### ISSUE THREAD

**Issue by AdmiralArtemiy** [flybywiresim/a32nx#2449]
"built": "2020-12-14T07:18:52+00:00", and then the last update of the 13th december.

Describing:
After clicking on the INIT page of the MCDU I can not reach the INIT FUEL PRED. page with clicking right arrow to enter ZFW and trimming - not available line appears. 

To Reproduce:
1. Load the flight.
2. Fill the MCDU.
3. Go to the INIT page.
4. When in the INIT page click the right arrow to open the INIT FUEL PRED. page.

Expected behavior:
I see the  INIT FUEL PRED. page and able to enter there a data, for ex. ZFW/trimming.

Actual behavior:
After clicking on the INIT page of the MCDU I can not reach the INIT FUEL PRED. page with clicking right arrow to enter ZFW and trimming - not available line appears. 

Was this working before/when did the issue start occurring? No.

Is this a problem in the vanilla unmodded game? No.

**Comment by LoungeFlyZ** [comment]
It's only available prior to starting engines I believe. Was this after starting the engines?

**Comment by AdmiralArtemiy** [comment]
> It's only available prior to starting engines I believe. Was this after starting the engines?

It was in the taxi sate. After starting eng.

**Comment by pacha35** [comment]
I have the same problem : impossible to add information in the ZFW/ZFWCG from the scratchpad in the INIT B page (not available)  and also in the  FUEL PRED page.
![Image46](https://user-images.githubusercontent.com/46076619/102203393-d4d45a80-3ec8-11eb-84fc-098d08d3cb00.jpg)

**Comment by tanai12** [comment]
good

**Comment by AdmiralArtemiy** [comment]
> good

?
