### ISSUE TITLE
Pitot heat should be automatic

### ISSUE THREAD

**Issue by toffee2000** [flybywiresim/a32nx#245]
Regardless of whether PROBE WINDOW HEAT pb is pushed, heat should always be on in flight. Only on ground before ENG start will the heat be off if pb is not pushed. Otherwise, barring faults, it is always on automatically.

**Comment by ukflyer** [comment]
AUTO - The AUTO selection (no lights) provides automatic heating of probes and windows in flight. On the ground if one engine is running windows and probes are automatically heated except for TAT probes.

ON - When the probe/window heat switch is selected to ON all probes and windows are electrically heated. The ON light also illuminates blue.

**Comment by toffee2000** [comment]
Yeah, that's the one. Thanks!

**Comment by ukflyer** [comment]
could this just a labelling issue on the hover over tip? instead of saying 'turn windshield de-ice OFF'  should say 'turn windshield de-ice AUTO'.. Cheers!

**Comment by toffee2000** [comment]
No, the pitot ices over in AUTO. Hence the issue.

**Comment by AdenFlorian** [comment]
Is this a bug in the vanilla game?

**Comment by toffee2000** [comment]
Don't know for sure but I think it might be.
