### ISSUE TITLE
[バグ][Turn on engine1 Master] and [Turn on engine2 Master] does not work.

### ISSUE THREAD

**Issue by junta999** [flybywiresim/a32nx#2454]
**a32nx-0.4.2.zip**

**Describe the bug**

[Turn on engine1 Master] and [Turn on engine2 Master] does not work.
I am using X52 Professional HOTAS.
It's the same even if you assign a keyboard shortcut.

Controller settings
FUEL-1[TOGGLE ENGINE 1 FUEL VALVE] and 2[TOGGLE ENGINE 2 FUEL VALVE]

I assigned 1 and 2 to the buttons on the controller.
The default aircraft works fine. (Including animation)
When I use MOD, it doesn't work at all.
The other assigned buttons work fine.

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
Please try the development version. Also, this does not respect the provided template.
