### ISSUE TITLE
[BUG] Cabin wind noise stops or is inaudible

### ISSUE THREAD

**Issue by Aero-3D** [flybywiresim/a32nx#2457]
**Mod Version**

**Describe the bug**

Cabin wind noise stops or is inaudible 

**To Reproduce**

1.  Battery supply 1 and 2
2.  External Power "ON" -> the wind from the cabin is audible 
3.  APU + BLEED "ON"
4.  MODE AGN START
5.  ENG Master 2, 1 "ON" the engines start and after starting you can hear the wind from the cabin.
6.  After deactivating the APU + BLEED the wind in the cabin becomes inaudible and no noise at all.
7. I checked that the "CAB FANS" button on the overhead was activated and the wind is not blowing.

**Expected behavior**

**Actual behavior**

Once the APU BLEED is deactivated after starting the engines, the sound in the cabin must work.

**References**

FSLABS A320-X

**Additional context**

Was this working before/when did the issue start occurring?
non
Is this a problem in the vanilla unmodded game?
non

Discord username (if different from GitHub):

**Comment by hotshotp** [comment]
that is the packs - the packs are not properly simulated yet so they only work when the apu bleed is on
