### ISSUE TITLE
[BUG] GPWS TOO LOW TERRAIN on Approach

### ISSUE THREAD

**Issue by lekkerjonty** [flybywiresim/a32nx#2464]
**Mod Version**
latest "stable" build

**Describe the bug**
When landing, I get terrain, don't sink and pull up sirens from the GPWS even though I am just landing and not in any danger. Once i land another siren sounds and I look at the ECAM. and it says "aircraft not configured for take-off" which of course its not as I am landing, not taking off

**To Reproduce**

1. landed at airports like madiera
2. or some of the land challenges
3. every landing it happens

**Expected behavior**

The sirens should not sound

**Actual behavior**

The sirens sound when they're not supposed to 

**References**

**Additional context**

Was this working before/when did the issue start occurring?
only started happening yesterday. 14th
Is this a problem in the vanilla unmodded game?
the only mod i have is the flybywire a32nx

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Can you try with the latest development version and report back ?

**Comment by hotshotp** [comment]
when you spawn on approach or landing challenges the aircraft is still in takeoff state, thats why it behaves like that

**Comment by flyboy1628** [comment]
Verified issue with latest dev build on standard approach and landing into KMCO, aircraft configured for flaps full landing on managed speed and APPR mode, GPWS terrain aural alert sounds. Aural warnings silenced by disabling GPWS TERR mode on upper panel.

**Comment by MisterChocker** [comment]
@flyboy1628 so the GPWS works as intended?

**Comment by flyboy1628** [comment]
@MisterChocker No...unless it's one of a handful of airports that have a known terrain flag on the approach you should not get a terrain warning if you are in landing config. 

Note that at least when I reproduce I am NOT getting a TOO LOW FLAPS/GEAR warning so its recognizing the aircraft is in the proper configuration, but as you approach the ground it's throwing out a TOO LOW TERRAIN. 

Also just to make sure I had APPR mode active in the FMGC and on the FCU. And I was flying a stable ILS on the glide path.

**Comment by flyboy1628** [comment]
Update on the issue - I enabled a Flaps 3 config in the GPWS via the upper panel and got no TERRAIN warnings from the GPWS on a stable approach to 1R at KIAD. 

I'm not sure if the issues are related but I don't believe the landing flaps full config works in the FMGC yet, so it thinks you're doing a flap 3 landing every time. However, the GPWS thinks you're doing a flap full landing unless you select flap 3 setting. 

Also as a side note, when doing a flap 3 landing, the ECAM landing checklist still tells you to put flaps full. This might be captured in another bug tag. 

The mystery continues, I may dig into this a little deeper today but wanted to update the thread.

**Comment by lukecologne** [comment]
Wait, so was your actual flap position 3 or full?

**Comment by flyboy1628** [comment]
On the most recent attempt my actual flap position was Flaps 3, with Flap 3 mode configured on GPWS which works fine. 

Previous attempt to re-create original post was Flaps Full with Flaps Full config set on GPWS which resulted in TERRAIN warnings.

**Comment by sidnov** [comment]
This issue does not occur anymore with proper landing configurations, tested at LPMA
