### ISSUE TITLE
[BUG] MCDU Fuel Prediction is incorrect or fuel consumption of aircraft is not high enough

### ISSUE THREAD

**Issue by daanvb** [flybywiresim/a32nx#2469]
**Mod Version**

"built": "2020-12-15T19:53:19+00:00",
  "ref": "",
  "sha": "",
  "actor": "ThatRedMelon <34657891+ThatRedMelon@users.noreply.github.com>",
  "event_name": "manual"

**Describe the bug**

When setting up a flight in the MCDU with the loadout given via Simbrief, I keep getting a message about there not being enough fuel on board. If I ignore the message and fly the flight, I land with what has been calculated by Simbrief and more than what the Fuel Prediction screen has calculated

**To Reproduce**

1. Load fuel 3050Kgs, cargo and passenger weight approx 23000kgs 
2. Setup Route: EGKK/08R IMVUR1Z IMVUR N63 VOUGA N14 MEDOG L18 ABLIN ABLIN2X
 EIDW/28L
3. FL320/-54C

**Expected behavior**

Expect actual fuel at Destination to match much closer to what fuel is actually predicted (In this case 1.7 actual to 0.5 predicted at takeoff)

**Actual behavior**

Flight setup as per Simbrief flightplan. Set up MCDU and kept getting message Min Fuel EFOB (about 0.5 at Dest, -0.1 at alternate (EINN)
I ignored and flew flight anyway. Landed with approx 1.7 tons of fuel. (Fuel Prediction screen stopped showing any predictions around half way through the flight)

**References**

**Additional context**

regarding simbrief Fuel calc, After previous flights and observations, the fuel predication i have set for the airbus in Simbrief has an offset of -45 giving the most accurate fuel required.

Was this working before/when did the issue start occurring?

Think it has always been incorrect

Is this a problem in the vanilla unmodded game?

Probably

Discord username (if different from GitHub):
daan_vb#6541

**Comment by Lucky38i** [comment]
the current aircraft doesn't burn fuel correctly as of yet. We're missing FADEC for one as-well as the proper config. the MCDU prediction are based on real-world data. This isn't a bug with the MCDU but more so problems with the fuel burn and flight model of the aircraft

**Comment by daanvb** [comment]
Ah ok so it is an aircraft fuel burn issue...

**Comment by michaeldinozzo** [comment]
@daanvb if I may suggest a temporary workaround while further opti;ization is done by the devs. Try changing the value of "fuel_flow_scalar" in the engine.cfg file and put "1.10" (instead of 1). When I compare the actual fuel consumption in cruise vs. the Simbrief predictions it is pretty accurate (c. 2,000 kg/h). Also try changing the "Fuel factor" to M15 in Simbrief when you prepare your flight as it is based on A320 CEO and you need to adjust this to simulate the NEO variant. Hope that helps ;)

**Comment by daanvb** [comment]
@michaeldinozzo thanks for the tip, I’m going to try that. I have simbrief at M45 at the moment to match up.
