### ISSUE TITLE
Mod interfere with FLT loading

### ISSUE THREAD

**Issue by ACSoft47** [flybywiresim/a32nx#247]
If I load a FLT saved flight file, the mod make the weather attached with the FLT to fail loading. You get just a default weather.

Removing the mod and the weather of the save was loaded.

**Comment by Curtis-VL** [comment]
I think this might be an Asobo bug? I'm not sure anything in the mod can change anything on the main menu like that.

**Comment by ACSoft47** [comment]
Yes, I confirm that the mod might be not guilty in this case. I just had now weather problems while loading old FLT files and A32NX mod is actually not installed. There are some obscure behaviors for me with the way these FLT files are made in regard with weather on save. Maybe it is simply me who do understand correctly how weather is or is not included into these FLT saves.

**Comment by 2hwk** [comment]
As of 1.12.13 this is now fixed.
