### ISSUE TITLE
[BUG] Landing challenges not working anymore with A320nx mod

### ISSUE THREAD

**Issue by ErikNL80** [flybywiresim/a32nx#2476]
**Mod Version**

Master

**Describe the bug**

Today I tried to do a landing challenge with the A320. When selecting one (i.e.. PARO) I get the following error: 'One or more required items are missing. Go to the Content Manager to download them.' In the Content Manager everything is up-to-date so no clue what is happening here.

**To Reproduce**

1. Start MSFS
2. Go to the landing challenges
3. Select any landing challenge using the A320
4. Try to start the challenge

**Expected behavior**

I would expect the challenge to start

**Actual behavior**

The challenge is giving an error message as described above.

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Watsi01** [comment]
Yes. The A32NX mod is not accepted anymore for landing challenges. You need to fly the default A320 with the challenges (remove the A32NX).

**Comment by ErikNL80** [comment]
OK, clear. Maybe something to add in the ReadMe?

**Comment by Benjozork** [comment]
> 
> 
> OK, clear. Maybe something to add in the ReadMe?

Will do
