### ISSUE TITLE
[REQUEST] Battery voltage meters to behave like IRL

### ISSUE THREAD

**Issue by tush0701** [flybywiresim/a32nx#2477]
**Is your feature request related to a problem? Please describe.**

Battery voltage shows a constant 25.4 V(or similar) as soon as battery is turned on, does not change or increase incrementally. It is also same always for both batteries.

**Describe the feature you'd like to see implemented**

Battery voltage should behave as real life, surge when turn on, and not be same immediately for both batteries.

**References**

![images.jpeg-70.jpg](https://user-images.githubusercontent.com/75409941/102482061-a9986980-4088-11eb-8b3e-4866468fd685.jpg)

**Additional context**

Discord username (if different from GitHub):

**Comment by hotshotp** [comment]
this is being worked on and will be made when our electrical system is implemented :)

**Comment by davidwalschots** [comment]
A battery implementation with realistic voltages was added in #3625.
