### ISSUE TITLE
[BUG] Temp on lower ECAM not matching ATIS Metar

### ISSUE THREAD

**Issue by ErikNL80** [flybywiresim/a32nx#2478]
**Mod Version**

Master (2020-12-17T08:19:03+00:00)

**Describe the bug**

Did a flight from LOWI and found the SAT and TAT to be +21C, which is doubtful in December. When I sked for ATIS Metar, it gave me +4C.

**To Reproduce**

1. Start a flight C/D from LOWI
2. Monitor ECAM
3. Compare SAT/TAT to Metar

**Expected behavior**

I would expect the temps to be equal or near to each other.

**Actual behavior**

A huge difference in Metar and ECAM SAT/TAT

**References**

![TEMP](https://user-images.githubusercontent.com/71258178/102484363-7513b600-4066-11eb-899d-9b9807e2e2f1.png)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by wpine215** [comment]
ATIS/METAR are pulled from online live weather API's and won't always match in-game weather. This will continue to be the case until Asobo provide us native weather API functions in the SDK for us to use.
