### ISSUE TITLE
FMS distance page does not update

### ISSUE THREAD

**Issue by ALPHAMAN1906** [flybywiresim/a32nx#248]
FMS distance page does not update

**Comment by ukflyer** [comment]
the FMS predictions are way off, apparently i can get from London to Croatia in 40 minutes!!! Hopefully the guys can do something here.

**Comment by edwinbrowwn** [comment]
Please if you can take a screenshot or a quick video of this issue. Does it not update or is it inaccurate? @ALPHAMAN1906 @ukflyer

**Comment by Flyingtrader06** [comment]
Hi guys, I guess what they mean here is that the total remaining flight distance is static in FMS. When loading a flight plan, the total distance is displayed but it does not decrease as the flight goes and constantly displays the total flight distance. So basically we have no idea how many Nm are left till destination, which is quite a big deal...
