### ISSUE TITLE
[REQUEST] Add Cabin Crew Announcements to the EFB

### ISSUE THREAD

**Issue by omarsmak** [flybywiresim/a32nx#2481]
**Is your feature request related to a problem? Please describe.**

No

**Describe the feature you'd like to see implemented**

It would be nice if the EFB can include cabin crew announcements that is configurable per airline. Users can contribute with more sound packs. An example for some of these cabin crew events/announcements:

- Cabin crew music, triggered when doors are open.
- Welcome by the captain.
- Safety demonstration.
-  Level off announcements. 
- TOD announcements. 
- Seat belts On/Off

Perhaps more can be added overtime

**References**

Honestly this feature request is purely inspired by the lovely Zibo mod in X-Plane with their EFB. You can take a look at Zibo EFB docs here:
https://drive.google.com/file/d/12F6xaB_oF-6bxKNzNURAqCnp2dTpgwvl/view?usp=sharing

**Additional context**

Discord username (if different from GitHub):

**Comment by hotshotp** [comment]
we already are planning this and we have all of the announcement sounds for it

**Comment by omarsmak** [comment]
> we already are planning this and we have all of the announcement sounds for it

Awesome! Then shall I close this issue or keep it open for reference? :)

**Comment by hotshotp** [comment]
> > we already are planning this and we have all of the announcement sounds for it
> 
> Awesome! Then shall I close this issue or keep it open for reference? :)

you can do whatever you like, we will close it once its implemented

**Comment by notl3ks** [comment]
Is this issue/request/suggestion still open for discussion? I was thinking about this exact thing today (cabin announcements) and I wanted to add my input.

**Comment by sidnov** [comment]
This has been implemented recently in both dev and experimental versions. Any further additions or enhancements to the announcements can be requested through a fresh GitHub issue, or even better, through the ``#sound`` channel of our Discord. 

cc. @hotshotp
