### ISSUE TITLE
[BUG] Right wiper knob resets

### ISSUE THREAD

**Issue by pepperoni505** [flybywiresim/a32nx#2490]
**Mod Version**

master

**Describe the bug**

The wiper knob still resets, even after PR #2441
The issue is more than likely related to a circuit issue that is explained in the PR. The left wiper works fine, but trying to turn on the right wiper just resets the right knob back to off.

**To Reproduce**

1. Load onto the runway
2. Try turning the right wiper on

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):

**Comment by yardpanz** [comment]
Hi, I have a different issue.
The 2 knobs are not selectable and the right wiper is OFF, the left wiper is ON (and can't switch it off).
