### ISSUE TITLE
[BUG] A320 landing challenges arent working

### ISSUE THREAD

**Issue by PuL9** [flybywiresim/a32nx#2491]
**Mod Version**
latest dev

**Describe the bug**
A320 landing challenges aren't working while the mod is installed

**To Reproduce**
Try any landing challenge with a320

**Expected behavior**
Explained

**Actual behavior**
Explained

**References**
RIO DE JANEIRO https://i.imgur.com/3dUZgaT.png

**Additional context**
-

Was this working before/when did the issue start occurring?
Couple of weeks ago

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub): same

**Comment by Benjozork** [comment]
Landing challenges using third-party mods is disabled by Microsoft.

Also, please properly fill the template next time.

**Comment by Benjozork** [comment]
Also, #2476. Please use the search function next time 🙂
