### ISSUE TITLE
[BUG] FLAPS AND SPOLIER SOUNDS IN V5 UPDATE

### ISSUE THREAD

**Issue by daniel5800** [flybywiresim/a32nx#2495]
**Mod Version**

 A32NX Stable V5

**Describe the bug**
 The sound of the flaps being put up and down doesn't make any noise from the cockpit, and the spoilers don't make a noise when being deployed at all

Also side note, this worked fine in the V4 so maybe it was forgotten about?

Also the cargo door doesn't make any noise from the cockpit when being closed like it did before  

**To Reproduce**

1. Using flaps during takeoff and landing
2. Using Spoilers on descent 
3. Requesting baggage services at the gate

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Yes, with the newest update V5

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):

**Comment by hotshotp** [comment]
Everything you mentioned is intentional other than the cargo door which will be added back later. Please read the changelog before making such issues
