### ISSUE TITLE
[BUG] MCDU Wrong Plane Model

### ISSUE THREAD

**Issue by TobitFR** [flybywiresim/a32nx#2498]
**Mod Version**

V0.5

**Describe the bug**

On the FMGC page the model of the A320 is the wrong

**To Reproduce**

1.MCDU MENU
2.FMGC page

**Expected behavior**

On the first line sould display A320-251N according to the LEAP 1A-26 line.

**Actual behavior**

Display A320-200.
![image](https://user-images.githubusercontent.com/31391535/102602573-0431d400-4122-11eb-8848-537c696af5e3.png)

**References**

A320-211 from Thales MCDU Pilot Guide
![image](https://user-images.githubusercontent.com/31391535/102604145-0b59e180-4124-11eb-8580-7907a90c0686.png)

EASA PDF Page 36 https://www.easa.europa.eu/sites/default/files/dfu/TCDS_EASA%20A%20064_%20Airbus_%20A318_A319_A320_A321_Iss_46.pdf

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

PS : The "ENG" and "ACTIVE NAV DATA BASE" and "SECOND NAV DATA BASE" are not aligned as they should be.

**Comment by hotshotp** [comment]
well it should technically say a320-251 if its a neo with the leap engine

**Comment by myselfaaryan** [comment]
No, an A320neo [251, 271] shows A320 - 200 on the CDU.

https://youtu.be/b7YfxSxJWzs

Reference at, 4:52.

**Comment by tareksabet** [comment]
So I checked and I have a picture of an A320Neo and written on it A320-200

![image](https://user-images.githubusercontent.com/70240330/102613409-1835ff80-413b-11eb-9596-9c8b08668cc6.jpeg)

**Comment by tareksabet** [comment]
closing right now
