### ISSUE TITLE
Emergency Light´s should give EICAS Indication

### ISSUE THREAD

**Issue by EpicPrimus** [flybywiresim/a32nx#250]
I am not quite sure, but normally all aircrafts should give you a EICAS Caution / Status Message when Emergency Lights are not armed or turned on.

**Comment by lrargerich** [comment]
I don't think that's the case of the A320, that's why it has an amber light in the overhead panel when emergency lights are not armed.

**Comment by EpicPrimus** [comment]
possible, as i said i am not quite sure. just working on the emb190 and crj900 irl and they give you an eicas indication in that case. but them this can be removed

**Comment by Curtis-VL** [comment]
Need a real pilot to verify this. :)

**Comment by PCGamesF1Tech** [comment]
Maybe it's similar to the strobes:
When lifting off an ECAM memo appears "Strobes off" in case we forgot to switch them on. 
I will check the manual later...

**Comment by konjakk** [comment]
The EMER EXIT LT switch is only connected to the OFF light. I searched through all available documentation and there is no mention anywhere that it is connected to ECAM. 
From FCOM:
![FCOM Emerg exit lt](https://user-images.githubusercontent.com/70980278/92535036-975f9180-f236-11ea-818f-bc972341a8af.jpg)

**Comment by NathanInnes** [comment]
It appears to be that EMER EXIT LT is only connected to the switch not an ECAM message.

Closing issue.
