### ISSUE TITLE
[BUG] A/TH doesn't disconnect when throttle is closed   

### ISSUE THREAD

**Issue by FO321** [flybywiresim/a32nx#2502]
**Mod Version**

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by FO321** [comment]
Case issue has been closed ? Craig. On 18 Dec 2020 3:22 pm, lukecologne <notifications@github.com> wrote:
Closed #2502.

**Comment by Benjozork** [comment]
"BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning"

**Comment by FO321** [comment]
Fair enough, by bad. 1st time reporting a issue. Think I did it right a while ago . ThanksCraig. On 18 Dec 2020 3:31 pm, Benjamin Dupont <notifications@github.com> wrote:
"BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning"

**Comment by hotshotp** [comment]
Follow the template when reporting issues

**Comment by FO321** [comment]
Sorry?  CheersCraig. On 18 Dec 2020 8:45 pm, hotshotp <notifications@github.com> wrote:
Follow the template when reporting issues
