### ISSUE TITLE
[BUG] Hydraulic PTU sound not reproduced

### ISSUE THREAD

**Issue by marcocragno** [flybywiresim/a32nx#2505]
**Mod Version**
5.0

**Describe the bug**
Hydraulic PTU sound not reproduced 

**To Reproduce**
 from cold&dark, start engine 2

**Expected behavior**
Reproduce the sound PTU makes ("barking dog") when it powers hydraulic systems 

**Actual behavior**
Sound not reproduced

**References**
https://youtu.be/SCplhq1xoYE

Was this working before/when did the issue start occurring?
Working on 4.2

**Comment by ChruutvoLuzi** [comment]
Hello, the PTU is not audible from the Cockpit in Airbus A320neo Aircrafts since it has been dampened

**Comment by marcocragno** [comment]
Ah ok, thanks! I love that sound :(

**Comment by hotshotp** [comment]
> Ah ok, thanks! I love that sound :(

Go to the wing view and you will still hear it after one engine startup

**Comment by hotshotp** [comment]
> Hello, the PTU is not audible from the Cockpit in Airbus A320neo Aircrafts anymore since it has been dampened

Correction - it has never been audible in any a320, neo and ceo. It's audible in the cabin however

**Comment by marcocragno** [comment]
Many thanks for your feedback and many thanks to the full FBW team for the great job is doing. Ciao
