### ISSUE TITLE
[BUG] ND NOT WORKING

### ISSUE THREAD

**Issue by SameerAli18** [flybywiresim/a32nx#2508]
Issue was on my end you can close this.
**Mod Version**
Latest dev build
2020-12-18T04:16:22+00:00

**Describe the bug**
ND not working after using simbrief integration. Heading on ND not moving to where the airplane is facing. Red line under the Heading. Range not working.

**To Reproduce**
1.Spawn at EGKK
2.Set up plan from C/D using simbrief integration. Then P/S.
3.Then just taxi around the airport and you should see the problem on your ND.

**Expected behavior**
When P/S, heading will not move on ND, a red line will appear and the range will not work. 

**Actual behavior**
After I set everything, I P/S then I noticed that the heading wasn't moving on the ND and the range wasn't working, a red line also appeared. I taxied around the airport and the heading didn't move.

**References**
https://www.loom.com/share/0dc5202c96574fefa16dccd053f7c6bc

**Additional context**
Stand was 121 (27 using the Gatwick Scenery) from flightsim.to https://flightsim.to/file/2774/gatwick-airport-egkk
Flight was from EGKK TO LGAV
ROUTE : BOGN1X BOGNA L612 XAMAB UL612 BIBAN NUTRO ARSOB ERPOG VIE NOSTO UN7 NEMES NEME2C

Was this working before/when did the issue start occurring?
After simbrief integration was released
Is this a problem in the vanilla unmodded game?
No

Discord username : Sameer Ali #4139

**Comment by ThatRedMelon** [comment]
Do you have the WorkingTitle Citation CJ4 Beta installed? If so try downgrading to stable or uninstall until a fix releases

**Comment by SameerAli18** [comment]
Yes that seem to have worked thanks

**Comment by SameerAli18** [comment]
Thank you my plane is working now you can close this issue
