### ISSUE TITLE
[BUG] New version not compatible with OnAir manager

### ISSUE THREAD

**Issue by miguel370** [flybywiresim/a32nx#2509]
**Mod Version**

**Describe the bug**
<- I had found that the new stable version 0.5 and the developers version, both, are not compatible with OnAir manager

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by St54Kevin** [comment]
it should be the other way around. OnAir has to compatible with the aircraft. Contact the devs in their discord. They made a DC-3 compatible for me within an hour. It is due to changed engines performance and fuel tanks which are adjusted to be closer to IRL

**Comment by markuskorbel** [comment]
OnAir have actually added a new plane model for the mod, so this bug can be closed.

**Comment by kacijon** [comment]
If you are like me and bought wrong plane model you can edit the file to match it.
I have Manualy modified the flight model cfg file to match the values in on air. Edit folowing values under fuel and fuel systems. 
1878 to 1800, 2712 to 3000 and 218 to 200. Values may be a bit off but the values you edit to are correct. in total you have to edit 10 values 5 for fuel and 5 for fuel systems.

**Comment by MisterChocker** [comment]
closing since issue not related to us.
