### ISSUE TITLE
Settings in OPTIONS menu save with each new build

### ISSUE THREAD

**Issue by GlitchedYT** [flybywiresim/a32nx#2513]
**Is your feature request related to a problem? Please describe.**

Would be really nice if the preferences under the OPTIONS page save for the individual.

**Describe the feature you'd like to see implemented**

Maybe have like a config file for the OPTIONS menu get saved into the Community folder so you don't need to keep changing back to your preferences when you download a new build?

**Comment by hotshotp** [comment]
+1, this sounds like a great idea

**Comment by TansyEliot** [comment]
> 
> 
> **Is your feature request related to a problem? Please describe.**
> 
> Would be really nice if the preferences under the OPTIONS page save for the individual.
> 
> **Describe the feature you'd like to see implemented**
> 
> Maybe have like a config file for the OPTIONS menu get saved into the Community folder so you don't need to keep changing back to your preferences when you download a new build?

Yeah, it's so bad need to enter your Simbrief username every time you want to use "Init request".

**Comment by Benjozork** [comment]
This is already the case but does not work for every user due to currently unknown reason.

Can people affected by the problem report what install they have ? (Steam, MS Store, GamePass)

**Comment by FRYYYYYY** [comment]
> This is already the case but does not work for every user due to currently unknown reason.

Where the actual config file will be saved to?

**Comment by sidnov** [comment]
Issue resolved with persistent settings
