### ISSUE TITLE
[BUG] EFOB dissapears in the middle of the flight with no reason

### ISSUE THREAD

**Issue by mikecbr** [flybywiresim/a32nx#2515]
**Mod Version**
Stable release 0.5

**Describe the bug**
In the FUEL PREDICTION PAGE , Suddenly in the middle of the flight some paremetres in the same page and the EFOB dissapears

**To Reproduce**

1.
2.
3.

**Expected behavior**
Work as intended in the whole flight

**Actual behavior**
It just dissapears suddenly 

![image](https://user-images.githubusercontent.com/74787268/102666917-5dcce980-4188-11eb-9134-39bff7cee3cb.png)

**References**
![image](https://user-images.githubusercontent.com/74787268/102666929-67eee800-4188-11eb-9596-fda2e3ddf091.png)

**Additional context**

Was this working before/when did the issue start occurring?
No , it was working a week ago

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):

**Comment by vicentezc** [comment]
Same issue just happened to me as soon as I displayed the FUEL PRED page (using simbrief integration and loaded the plane through the MCDU)

**Comment by airfirefighter** [comment]
i have a question in discussion about that .....that happens 160nm before arrive at destination ,i saw the nm  in the last 2 flights and as already mentioned  above i have all the time dest efob below min even if min is 2.1  and i have 2.2 in this part of trip.

**Comment by Danimalpm** [comment]
Seems to occur at the start of the descent phase when DH appears on the PFD.

**Comment by Lucky38i** [comment]
> Seems to occur at the start of the descent phase when DH appears on the PFD. 

That's not it at all. Certain constraints aren't being fulfilled so the predictions are failing. I'll open a PR soon

**Comment by vicentezc** [comment]
I just did KDCA-KLGA, and the fuel prediction was not computed (on the ground, pre-flight), neither with the FUEL PLANNING function, neither when fuel entered manually. As a consequence the different values in the FUEL PRED page were not present. So it may be related to the remaining distance?

**Comment by mikecbr** [comment]
> I just did KDCA-KLGA, and the fuel prediction was not computed (on the ground, pre-flight), neither with the FUEL PLANNING function, neither when fuel entered manually. As a consequence the different values in the FUEL PRED page were not present. So it may be related to the remaining distance?

yepp iy happens to me also sometimes

**Comment by airfirefighter** [comment]
> > I just did KDCA-KLGA, and the fuel prediction was not computed (on the ground, pre-flight), neither with the FUEL PLANNING function, neither when fuel entered manually. As a consequence the different values in the FUEL PRED page were not present. So it may be related to the remaining distance?
> 
> yepp it happens to me also sometimes

just change the FL in 290 or more.

**Comment by mikecbr** [comment]
what @airfirefighter

**Comment by Lucky38i** [comment]
> what?   @airfirefighter 
> 
> 
> 
> 

There's a specific set of criteria that allows predictions, one of those conditions requires >FL290 for a flight above 200nm. I'm working on a pr to make these constraints a lot more lenient.

**Comment by mikecbr** [comment]
well , all my flights are above FL290  @Lucky38i  @airfirefighter

**Comment by Lucky38i** [comment]
> well , all my flights are above FL290  @Lucky38i  @airfirefighter 

Yes but you're discussing fuel pred, if you're flying and you're 200nm from your but still above 290 you'll get a prediction failure. Again, I'll open a PR to amend this.
