### ISSUE TITLE
APU starter always saying"unavailable"

### ISSUE THREAD

**Issue by GivenPaladin809** [flybywiresim/a32nx#252]
It's impossible to start the APU, because it always says that the starter is unavailable, even after some time has passed after pressing the APU Master. Also, even if after a while, it is pushable, the APU will start and be available, but the lower ECAM will show amber 
 "XX" EGT and amber "XX" N values.

**Comment by ukflyer** [comment]
believe this is being worked on in https://github.com/wpine215/msfs-a320neo/issues/53 :)

**Comment by ThePilot916** [comment]
Yup, It has been fixed already, just waiting on the merge.

**Comment by Curtis-VL** [comment]
Once the merge has been made, please close this issue! 👍

**Comment by AdenFlorian** [comment]
still seems to be an issue, working on a fix

**Comment by Inaxair** [comment]
As I believe it has been merge, I'll close the ticket. Feel free to reopen the ticket if you have other query about this issue. Thanks!

**Comment by lukecologne** [comment]
Reopened since this still appears to be an issue

**Comment by tareksabet** [comment]
@lukecologne couldn't preproduce this issue will close it

**Comment by lukecologne** [comment]
Yeah, I fixed it in #1476 but forgot to link it
