### ISSUE TITLE
[BUG] Fuel X FEED switch cannot be turned off - TCA quadrant

### ISSUE THREAD

**Issue by vicentezc** [flybywiresim/a32nx#2521]
**Mod Version**

master

{
  "built": "2020-12-18T04:16:22+00:00",
  "ref": "",
  "sha": "",
  "actor": "ZigTag <17077422+ZigTag@users.noreply.github.com>",
  "event_name": "manual"
}

**Describe the bug**

I am using the TCA quadrant for the master engine switches and the Fuel X FEED switch remains active and cannot be turned off as long as the switches are on. It was the case in previous builds, but with the implementation of the new ECAM messages it has become a higher prio.
Current assignments to TCA switches (buttons 3/4):
* TOGGLE ENGINE MASTER 1/2
* SET STARTER 1/2 (HOLD)
* SET ENGINE 1/2 FUEL VALVE
I have tried changing the assignments, but the switches won't work without assigning the "SET ENGINE 1/2 FUEL VALVE", and when assigning this action the FUEL X FEED switch is turned ON and cannot be turned off until engines are turned off.

**To Reproduce**

1. Requires TCA quadrant, or a way to use two buttons that are always active, and assign the "SET ENGINE 1/2 FUEL VALVE" action
2. Start cold & dark, prepare the plane for engine start
3. Select IGN/START
4. Start Engine 2 with assigned button => "FUEL X FEED" will be displayed in ECAM and X FEED switch will be ON in overhead panel. It cannot be turned off unless the assigned button is inactive (i.e. when engines are turned off)

**Expected behavior**

Fuel X FEED should not be turned ON automatically when "SET ENGINE 1/2 FUEL VALVE" is active

**Actual behavior**

Fuel X FEED is ON and cannot be turned OFF until engines are turned OFF

**References**

**Additional context**

Was this working before/when did the issue start occurring?
This has occurred since I started using the TCA quadrant, but was not an issue just to have the switch ON in the overhead panel. With implementation of ECAM messages it has become an issue.

Is this a problem in the vanilla unmodded game?
*EDIT: I just checked and this is also happening with the vanilla version

Discord username (if different from GitHub): vicentezc

Thanks!

**Comment by Saschl** [comment]
I'm not experiencing this issue. You could try only  setting Set Engine Fuel Valve 1/2 values, those work fine for me. Also Try removing/updating other mods that might interfere.

**Comment by vicentezc** [comment]
I have now understood the issue. I had assigned the switches to engines 3 and 4 as well (for the 747), thinking there would be no impact on 2 engine aircraft:
- Left switch: engines 1& 4
- Right switch: engines 2 & 3
I removed the assignments to engines 3 & 4 and it's now working fine.
