### ISSUE TITLE
[BUG] NEW SIMBRIEF INTEGRATION... IN GAME ATC NOT RECOGNIZING ALTITUDE CHANGES?

### ISSUE THREAD

**Issue by Dreunit1986** [flybywiresim/a32nx#2522]
**Mod Version**
 LATEST DEV

**Describe the bug**

LOADED SIMBRIEF FLIGHT PLAN USING THE INTEGRATION... ATC HAD ME FLY ENTIRE FLIGHT AT FL010 INSTEAD OF THE NORMAL CLIMB, THEN CRUISE, THEN DESCENT... ETC.

**To Reproduce**

1.INSERTED SIMBRIEF FLIGHT PLAN AND ALL OTHER DEETS FOR DEPARTURE
2.OBTAINED IFR CLEARANCE FOR FLIGHT PLAN
3.ATC INSTRUCTED TO CRUISE AT 10,000 INSTEAD OF CRUISE 320 IN PLAN.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by hotshotp** [comment]
not related to atc instructions, msfs atc is not connected to your flight plan

**Comment by Richard5644** [comment]
Since v 0.5.0 cannot get integration to work whatever I do.  INIT page keeps saying NOT IN DATABASE and NOT ALLOWED, and I have to enetr everything manually into the MCDU

**Comment by Benjozork** [comment]
@Richard5644 Please use our Discord for support, avoid commenting on unrelated tickets.
