### ISSUE TITLE
[BUG] Autopilot Bank Oscillation

### ISSUE THREAD

**Issue by blazinga350** [flybywiresim/a32nx#2525]
**Mod Version**
0.4.1

**Describe the bug**
I was flying from San Francisco to Los Angeles and the A320neo started banking heavily to the left and right above 6000. Even if the weather is clear skies, the plane banks to the left and right. 

**To Reproduce**
1. Take-off(with a full flight plan)
2. Climb to cruise
3. Enjoy the intense banking
4. 

**Expected behavior**
Autopilot to function normally without heavy banking.

**Actual behavior**
Aircraft banks heavily to the left and right.

**References**
None, no one posted anything about this.

**Additional context**

Was this working before/when did the issue start occurring?
After I installed this version, plane started banking left and right.
Is this a problem in the vanilla unmodded game?
Don't know.

I might be able to resolve this by installing 0.5 version.

Discord Username: Minkyu Koo "IO"

**Comment by Benjozork** [comment]
Version 0.4.1 is unsupported. Please upgrade to 0.5.0.
