### ISSUE TITLE
[BUG] Autopilot Heading Issue During ILS

### ISSUE THREAD

**Issue by blazinga350** [flybywiresim/a32nx#2526]
**Mod Version**
0.4.1

**Describe the bug**
Aircraft turns to the left when I put a heading degree 90 degrees right of where the airplane is heading.

**To Reproduce**
1. Takeoff
2. Fly approach into the airport. 
3. Turn right or left with heading autopilot to intercept the localizer.

**Expected behavior**
The airplane to turn right when the heading is set 90 degrees to the right of the airplane.

**Actual behavior**
Airplane turns left, away from the localizer.

**References**
None

**Additional context**
None

Was this working before/when did the issue start occurring?
Started happening today, when flying from KSFO-KLAX (SSTIK4 EBAYE DCT BURGL IRNMN2)
Is this a problem in the vanilla unmodded game?
I don't know

Discord username (if different from GitHub):
Minkyu Koo "IO"

**Comment by Benjozork** [comment]
Version 0.4.1 is unsupported. Please upgrade to 0.5.0.
