### ISSUE TITLE
Logitech Flight Radios not working with latest stable version 

### ISSUE THREAD

**Issue by jvieira21** [flybywiresim/a32nx#2528]
**Mod Version**
 release version 0.5.0

**Describe the bug**
 upon starting up with ext power and battery, radios don’t work when before it used to

**To Reproduce**

1. Ext power
2. Battery on

**Expected behavior**
 the flight radio lights should come on

**Actual behavior**

Lights don’t appear to be on

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning
