### ISSUE TITLE
[BUG] some functions are not clickable

### ISSUE THREAD

**Issue by Talent442** [flybywiresim/a32nx#2532]
**Mod Version**
latest dev version 0.5.0
build_info.json:
{
  "built": "2020-12-18T18:19:43+00:00",
  "ref": "",
  "sha": "",
  "actor": "Martin <5703553+pre-martin@users.noreply.github.com>",
  "event_name": "manual"
}

**Describe the bug**
I have found some non-clickable knobs. Including:
- wipers
- flaps (I can use them via joystick, but there is no animation and not clickable with mouse)
- parking brake (usable via keyboard, but no animations and also not clickable)
- IAS speed also not clickable and not able to configurate the speed
- TCAS not clickable

**To Reproduce**

1. deleted the FlyByWire A32NX Modfrom community folder
2. checked the vanilla aircraft (fixed the issues above, but displays are broken)
3. reinstalled the Mod (issues still exists)

**Expected behavior**
Issues will disappear --> non clickable object become clickable

**Actual behavior**
like i mentioned before the displays of the vanilla A320NEO were broken, but clickable objects became clickable.

**References**

**Additional context**
I'm working on some converted Airbus A320 family aircrafts, using the flybywire A32NX Cockpit.

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub): TALENT#1646

**Comment by Benjozork** [comment]
Seems like you have a corrupted install.

Please try with an empty Community folder and only the mod, then report back.

**Comment by Talent442** [comment]
Well okay some news: I put in the A32NX Mod only, without liveries etc and now it works properly.
