### ISSUE TITLE
[BUG] Engine not starting when using checklist automation

### ISSUE THREAD

**Issue by kthejoker20** [flybywiresim/a32nx#2539]
**Mod Version**

MASTER

**Describe the bug**

When using the checklist automation, the engines do not start.   The checklist is not enabling the fuel pumps.

If you manually enable the fuel pump buttons, the engines start.

**To Reproduce**

1.  Use checklist automation to start engines.
2.
3.

**Expected behavior**

Engines should start when using checklist automation, upon switching engine to "on".  But the checklist does not activate the fuel pumps.

**Actual behavior**

Check list automation goes to the engine 1 and holds without starting.  

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning
