### ISSUE TITLE
[BUG] Unable to enter CRS for ILS approach

### ISSUE THREAD

**Issue by kthejoker20** [flybywiresim/a32nx#2540]
**Mod Version**

Master

**Describe the bug**

CRS is locked, cannot enter a CRS for the ILS radio FREQ

**To Reproduce**

1.  go to rad/nav try to enter CRS for the ILS radio
2.
3.

**Expected behavior**

Should be able to enter CRS

**Actual behavior**

It's locked

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning
