### ISSUE TITLE
[BUG] Screen Refresh rate for PFD and ND

### ISSUE THREAD

**Issue by kthejoker20** [flybywiresim/a32nx#2542]
**Mod Version**

Master

**Describe the bug**

The refresh rate for the PFD and the ND is either to low or to hi causing visual tearing and MAJOR graphics performance impact.

**To Reproduce**

1.  Turn on display brightness to full on the PFD and the ND
2.
3.

**Expected behavior**

Should be no tearing and clean

**Actual behavior**

It is tearing and causing considering graphics lag and impacting graphics performance

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning
