### ISSUE TITLE
[BUG] Wipers not working

### ISSUE THREAD

**Issue by kthejoker20** [flybywiresim/a32nx#2543]
**Mod Version**

Master

**Describe the bug**

Wipers are not working

**To Reproduce**

1. Turn on wiper switch, wipers not working
2.
3.

**Expected behavior**

Wipers should be wiping the windows when you turn the switch

**Actual behavior**

Nothing happens.

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning

**Comment by pepperoni505** [comment]
Relates to #2490
