### ISSUE TITLE
[BUG] Increased engine power just before take off

### ISSUE THREAD

**Issue by phildeg31** [flybywiresim/a32nx#2544]
Mod Version
"built": "2020-12-19T14:11:45+00:00"

Describe the bug
The increased engine power before take off is not realistic. The needle increases too fast.

To Reproduce
Increase power (with throttle) to 50%.
Wait for engines to be at 50% and then set to TOGGA position for take off.

Expected behavior
See link for video from a real A320 simulator: https://youtu.be/Mm7HlIkqpP8

Actual behavior
I will do a video of the behaviour I saw in game.
The needle rapidly increases above 50% before descending to 50%.

**Comment by hotshotp** [comment]
Duplicate #2472

**Comment by phildeg31** [comment]
Ok thank you I did not saw this ticket :).

**Comment by hotshotp** [comment]
> Ok thank you I did not saw this ticket :). Maybe the video can be helpfull to correct this behaviour.
dont worry! this is a known issue and is being worked on
