### ISSUE TITLE
wheel isnt going down

### ISSUE THREAD

**Issue by mishal321** [flybywiresim/a32nx#2547]
**Mod Version**
dev a320nx 5.0

**Describe the bug**
the wheel wont go down

**To Reproduce**
press down the gear

**Expected behavior**
the gears go down

**Actual behavior**
they didnt ;(

**References**
https://youtu.be/FwxpvgFjutc

**Additional context**

Was this working before/when did the issue start occurring?
yes
Is this a problem in the vanilla unmodded game?
no

Discord username (if different from GitHub): mishal321

**Comment by Benjozork** [comment]
Sometimes that click zone is wonky. You might need to look at it directly, not at an angle.

Can you show a screenshot of your `Community/` folder ? Other mods such as YourControls might cause conflicts.

**Comment by hotshotp** [comment]
press g to release your gear and see if the problem persists

**Comment by mishal321** [comment]
> press g to release your gear and see if the problem persists

I pressed g, I have the latest Beta your controls, it was working fine. It just started to not work..  The only mods I have are your controls and a320nx. I also have a bunch of liveries.

**Comment by Benjozork** [comment]
Can you try without YourControls ?

If the issue is confirmed to be caused by YourControls, then the issue should be reported there.

**Comment by mishal321** [comment]
I restarted the actual sim, and it appears to be working now..
