### ISSUE TITLE
[ANFRAGE] Simbrief and MCDU 

### ISSUE THREAD

**Issue by Onkelpuh** [flybywiresim/a32nx#2548]
sorry for my english but i need google translator

Question about the flight plan and sim letter
The function works wonderfully, but how do I get it baked when I have completed a flight that I can reload from Simbrief for the next flight without going into the main menu and reloading the new flight plan when I'm at the gate?
can you reset the MCDU somehow so that you can simply enter the new data without reloading the plane?

**Comment by hotshotp** [comment]
questions are for the discord, not the github

**Comment by Benjozork** [comment]
This is not supported yet, coming in a future update

**Comment by Onkelpuh** [comment]
> Dies wird noch nicht unterstützt, kommen in einem zukünftigen Update

Thanks for Info
