### ISSUE TITLE
[BUG] MSFS2020 crashing to desktop when clicking World Map

### ISSUE THREAD

**Issue by Marshall89PL01** [flybywiresim/a32nx#2551]
**Mod Version**
master

**Describe the bug**
I have copied the folder A32NX to the Community folder. I launch the game, click "World Map" to prepare a flight. The game crashes to desktop with no popups...

**To Reproduce**
1. Launch the game
2. Click World Map

**Expected behavior**
no crash

**Actual behavior**
crash

**Additional context**
Before installing A32NX i had a problem with vanilla airbus, the problem was that all glass cockpit screens were black, nothing shown on them as if they were shut down. The plane was fully functional apart from the screens.

**Comment by Benjozork** [comment]
Can you try to install A32NX with nothing else in the Community folder ?

**Comment by Marshall89PL01** [comment]
I don't know what happened but all my content apart from 2 planes disappeared and I had to download it again via content manager. I downloaded vanilla airbus and now the A32NX works 100% fine... Dont ask me.
