### ISSUE TITLE
issue when going direct to a waypoint fmc blank flight plan disappear

### ISSUE THREAD

**Issue by ragancop123** [flybywiresim/a32nx#2552]
**Mod Version**

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by DarkOfNova** [comment]
Please follow the issue template

**Comment by tareksabet** [comment]
Please follow the template so we can help you. 

Closing it because it doesn't respect the template.

**Comment by ragancop123** [comment]
Sorry for any inconvenience this is the first time I have done this is
report a bug.

Many Thanks.
