### ISSUE TITLE
Cannot Request IFR Clearance/Taxi/Takeoff After v0.5 Stable

### ISSUE THREAD

**Issue by DFWSupertrooper** [flybywiresim/a32nx#2559]
**v0.5 Stable**

**Describe the bug**
Often, when starting cold/dark at the gate with IFR flight plan created (regardless of whether or not I use the SimBrief import function) I do not get the option to request IFR Clearance from the gate, and thus cannot also get taxi/takeoff clearance.  This _never_ occurred using v0.4.2 or earlier but _almost always_ occurs using dev versions or v0.5.

In prior stable versions and in default A/C the departure airport was listed white in the MCDU flight plan indicating active waypoint, but now the next waypoint generally is (don't know if this is an indicator of what is wrong but it is 99% correlated).

I don't know what the required function is to always get clearance from ATC to pop up using this A/C.  Need updated procedure if checklist is now wrong.

**To Reproduce**
1. Choose the A32NX and livery from the World Map function in MSFS.
2. Select a departure airport and gate/parking.
3. Select arrival airport.
4. Select IFR/high altitude jetways.
5. Select SID departure and runway option.
6. Select STAR arrival and runway option.
7. Click FLY NOW.
8. Begin power up procedure.
9. When reaching the part of the checklist that calls for _Request IFR Clearance_, click on the ATC dialogue box.
10. 99% of the time, _Request IFR Clearance_ will not function (once in a while it does).

NOTE: You can also do the SimBrief import and get the same problem.  The only way it consistently works as expected is if I load the MSFS flight plan departure/arrival options and CHANGE NOTHING (no runway/approach options, etc).

**Expected behavior**
If an IFR flight plan has been created in the World Map view, AND/OR if the SimBrief import was used to pull in an IFR flight plan, the sim should ALWAYS allow _Request IFR Clearance_ at the gate (in the appropriate checklist process).

**Actual behavior**
Again, 99% of the time, this option does not pop up.

An alternate solution would be if the Request IFR Flight Plan from Instrumentation option popped up at the gate, but it often does not even after SimBrief import.

Does the checklist/process need to be revised to ensure users can follow the 100% working process?

**References**
N/A

**Additional context**
N/A

Was this working before/when did the issue start occurring?
Yes, in all prior stable versions and in default A/C, this request for IFR worked 100%.  Problem is in all dev versions and in new stable v0.5 (something changed between 0.4.1 and 0.5).

Is this a problem in the vanilla unmodded game?
No.

Discord username (if different from GitHub):

**Comment by DFWSupertrooper** [comment]
I think this may be related: while flying once I can get through the above issue, I notice that on every route I fly now, the arrivals seem to be screwed up.  Example: I'm arriving KDFW on PNUTS.WHINY4, but it'll automatically also have the CRIED/BRAZZ/POWND leg added which I have to remove.  This happened inbound last night to KMSY also from KIAD.  Something extra is getting loaded into the MCDU flight plan when the flight is loaded.  Importing SimBrief only adds to the issue, doesn't replace the errored plan.

**Comment by DFWSupertrooper** [comment]
It also duplicates the STAR arrival as part of the base flight plan AND arrival added after a A9 point it creates in the flight plan in MCDU.

**Comment by jrdemasi** [comment]
I can get clearance just fine after a Simbrief import, but I never get the in-game ATC to actually clear me to my cruising altitude, but if I load the same plan through the world map I do.

**Comment by DFWSupertrooper** [comment]
I believe this issue is too intermittent to track.  Most of the time I can get a clearance option if I handle the process using the MSFS planning but limit changes.  Closing.
