### ISSUE TITLE
[BUG] Sounds are diferent

### ISSUE THREAD

**Issue by Tirus89** [flybywiresim/a32nx#2562]
**Mod Version 0.5.0 stable Version

Well after updating to latest Version 0.5.0 stable on cockpit preparation I notice some sounds arent Like previus Version 

till the Apu start looks everything normal with Sounds knobs Bleed everything fine! until I start the Engine number 2 and he starts spooling up I can notice one huge diference in Sound quality and the Spooling itself sounds buggy and unrealistic way to diferent from last Version!
then aplying trust to start taxi not only the trust feels stronger then before but the sound of it its just like something else 
a washmachine just unrealistic and way worst then other versions 
at first I thought it was the vanilla sounds and some instalation problems but uninstal the mod and the vanilla sounds are now better the the 0.5.0 version of a320nx!
so the problem is the installer not installing everysound our they are just missing on this version

**Comment by hotshotp** [comment]
Wow, I never heard someone more ungrateful in my life. The sounds are confirmed by 20+ real life pilots and engineers to be realistic - so why don't you as a genius look up any LEAP-1A videos on youtube and tell me how unrealistic it is.

**Comment by Tirus89** [comment]
my sounds arent realistic at all after update that why i issued this 
after update and I say again! after update my engine sounds are buggy

**Comment by hotshotp** [comment]
> my sounds arent realistic at all after update that why i issued this
> after update and I say again! after update my engine sounds are buggy

can you please show a video clip? this would help to see your issue

**Comment by Tirus89** [comment]
i will has soon has posible

**Comment by Tirus89** [comment]
Well i just did a win10 clear install and msfs with the standard comunity folder location and installed the mod again!
and well sounds are really different but they are actually ok 
still like the 0.4.2 version more but it was clearly an install issue!
i found this out cause i saw a video on youtube with new sounds and I realise there must be an install issue cant say what was but now i have good sounds back
