### ISSUE TITLE
[BUG] Weird Flightpath on arrival to EGLL

### ISSUE THREAD

**Issue by kberg93** [flybywiresim/a32nx#2563]
**Mod Version**

0.5.0 with PR #2447

**Describe the bug**

Weird arrival path look at SC.

**To Reproduce**

1. RTE: LSZH/16 VEBI3S VEBIT T51 LASUN UN176 LUMEL UT10 RLP UL613 DIDOR UT10 ALESO ALES1H EGLL/27R
2. Arrival was: **ILS 27R** Via: **None** Star: **ALES1H** Trans: **None**
3.

**Expected behavior**

Not being back and forward like this.

**Actual behavior**

Arrival path was very weird considering what was put in and what was showing in Navigraph Charts...

**References**

How it looked like:
![FlightSimulator_EGph4Dxz9M](https://user-images.githubusercontent.com/56963782/102718937-49edc880-42eb-11eb-875c-837db41ea604.png)
![FlightSimulator_jb1chC97ea](https://user-images.githubusercontent.com/56963782/102718941-4e19e600-42eb-11eb-9027-8e84ccc9d574.png)
![FlightSimulator_Xs4RtcwbBm](https://user-images.githubusercontent.com/56963782/102718943-507c4000-42eb-11eb-96e0-d5949a3a1549.png)
![FlightSimulator_TEkEnHWt3V](https://user-images.githubusercontent.com/56963782/102718947-52460380-42eb-11eb-97c8-c56dae5e8445.png)
How it should look like:
![Navigraph_Charts_lWMtpKdtf0](https://user-images.githubusercontent.com/56963782/102718949-55d98a80-42eb-11eb-92e2-ce473aa8d659.png)

**Additional context**

Was this working before/when did the issue start occurring?
Issue during a PR test :) 
Is this a problem in the vanilla unmodded game?
No idea

Discord username (if different from GitHub):
Kberg#0666

**Comment by pareil6** [comment]
This is an underlying nav data issue I think - all initial approaches out of BIG into the 27s at EGLL have had a weird shape since I got the sim. It might be worth checking this in the default A320 (or in the B748), just to see what it gives you - I don't remember it being *that* bad, so the mod somehow making it worse, but I wouldn't be surprised if the nav data is just worse now.

**Comment by kberg93** [comment]
> This is an underlying nav data issue I think - all initial approaches out of BIG into the 27s at EGLL have had a weird shape since I got the sim. It might be worth checking this in the default A320 (or in the B748), just to see what it gives you - I don't remember it being _that_ bad, so the mod somehow making it worse, but I wouldn't be surprised if the nav data is just worse now.

I will check out after the Alaska Bushtrip :)

**Comment by Samsamtheambulanceman** [comment]
Pretty sure this is a Navigraph issue

**Comment by Username23-23** [comment]
Can you post a screen recording of you actually pasting in the arrival? I want to see if the sim is forcing you to use an approach via.

**Comment by kberg93** [comment]
787(same):
![FlightSimulator_Z4aAj5WU3g](https://user-images.githubusercontent.com/56963782/102728195-999fb480-432a-11eb-9017-13909e36df98.png)

Without Navigraph:
787(little better):
![FlightSimulator_WYx7egmfQr](https://user-images.githubusercontent.com/56963782/102728469-69f1ac00-432c-11eb-8cff-67b94ddefbd9.png)

Im closing this and reporting it into the Navigraph forum instead :)
