### ISSUE TITLE
[BUG] Throttles Won't go back to Idle or Reverse

### ISSUE THREAD

**Issue by ncrh01** [flybywiresim/a32nx#2564]
**Mod Version**
0.5.0 Stable

**Describe the bug**
When using a mouse to move the throttle levers they will increase to 100% no problem but when reducing thrust I cannot move them below about 47% thrust.  Using F2 and F3 via the keyboard works fine.
When trying this with the standard unmodded A320 version this all works fine.

**To Reproduce**
Simply try to use the mouse to control the throttle levers on both the unmodded A320 and 0.5.0 stable.
On the unmodded version thrust can be reduced to idle and reverse.
On the 0.5.0 stable version the thrust can only be reduced to about 47%.

**Expected behavior**
I expect the thrust levers to come back to idle and reverse as they did before.

**Actual behavior**
Thrust levers will only come back to about 47% on the 0.5.0 stable version.

**References**
N/A

**Additional context**
I actually noticed this problem with my hardware throttles via FSUIPC but the fact that it happens natively via using a standard mouse interface shows this is nothing to do with my hardware / FSUIPC configuration. My hardware throttles work fine on the unmodded version and did so on 0.4.0 as well.

Was this working before/when did the issue start occurring?
Issue started with 0.5.0 - both stable and dev

Is this a problem in the vanilla unmodded game?
No.

Discord username (if different from GitHub): NeilC

**Comment by tareksabet** [comment]
Try again you have to click with the mouse on every detent so you would have to click at MAN TOGA Detent, MCT FLEX Deyent, CLIMB Detent, IDLE Detent then reverse.

Try that technique and tell me if it got fixed.

Thanks for reporting this issue.

**Comment by ncrh01** [comment]
Hi There,

      Thanks for the response.

      The problem appeared to be resolved a few days after I reported it - my external hardware throttles work fine and I can drag the throttles with the mouse as before (although  I never really use this method), so I don't know what was done to fix it but I am happy it all works now.
      I tried clicking with the mouse at various detents as you suggested but that does nothing on its own, I have to left click and drag the mouse to get the throttles to move but I wouldn't worry about that. As far as I am concerned all is good now.

       Keep up the good work.

       Regards,
                   Neil

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tareksabet** [comment]
Thanks for using our mod.

As it got fixed closing this issue now.

Tarek
