### ISSUE TITLE
[BUG] Missing PTU /barking noise

### ISSUE THREAD

**Issue by Jakrzysztof** [flybywiresim/a32nx#2565]
**Mod Version**
Release 0.5.0

**Describe the bug**
Guys, you did a great job adding the new sounds, A320NX sounds no much more realistic! 

The issue is, when I'm starting the first engine, I've noticed that the PTU(Barking or "woof, woof" - whatever you call it) noice is missing. This sounds is pretty typical for starting A320.

**To Reproduce**
1. Launch frist engine and wait a couple sec - You will notice that PTU sound is missed.

**Expected behavior**
PTU sounds should be hearable after the first engine is started.

**Actual behavior**
PTU sound is missed after launch first engine.

**Comment by Benjozork** [comment]
That sound can only be heard over the wing and inside the cabin, not in the cockpit.

Working as intended.
