### ISSUE TITLE
[BUG] STARs with runway-specific routing instructions not working properly

### ISSUE THREAD

**Issue by mak60062** [flybywiresim/a32nx#2567]
**Mod Version**

  "built": "2020-12-20T17:34:13+00:00",
  "ref": "",
  "sha": "",
  "actor": "John Good <judiconis@gmail.com>",
  "event_name": "manual"

**Describe the bug**

STARs that provide routing instructions based on runway are not being respected by the MCDU. 

**To Reproduce**

1. In the MCDU set the destination to an airport with a STAR that has runway-specific routing instructions. 
2. Select an approach.

**Expected behavior**

Flight plan should display the proper STAR routing to the approach for that runway.

**Actual behavior**

Flight play displays incorrect STAR routing to approach. Routing does not change based on selected runway on approach. 

**References**

ONDRE1 STAR at KATL:
![Ondre1](https://user-images.githubusercontent.com/6889399/102722086-c2915c80-42cc-11eb-8176-eaa4903fb0c1.png)

A32NX KATL ONDRE1 8L (Correct routing):
![8L Ondre1](https://user-images.githubusercontent.com/6889399/102722102-db017700-42cc-11eb-868e-fff84f254574.png)

A32NX KATL ONDRE1 9R (**Incorrect routing**):
![9R Ondre1](https://user-images.githubusercontent.com/6889399/102722127-07b58e80-42cd-11eb-9fd9-31fdd052da25.png)

Default TBM KATL ONDRE1 8L (Correct routing):
![TBM 8L Ondre1](https://user-images.githubusercontent.com/6889399/102722135-156b1400-42cd-11eb-9dad-30057b4b3cde.png)

Default TBM KATL ONDRE1 9R (Correct routing):
![tbm 9R Ondre1](https://user-images.githubusercontent.com/6889399/102722141-1d2ab880-42cd-11eb-854f-ed8299f02860.png)

**Additional context**

Was this working before/when did the issue start occurring?
Always, as far as I know. 

Is this a problem in the vanilla unmodded game?
Yes, but only on the A320. 

Discord username (if different from GitHub): Mobius_One_Fox3

**Comment by mak60062** [comment]
Replicated on BANKR2 STAR for runway 18 at KCLT

**Comment by joseG69** [comment]
It is a major bug in MSFS2020 and it affects all major airports in the USA. 
Most airports have STARs that have different paths, depending on the runway you are going to land. But they all have the same name. A good example is ROBUC3 ARR in KBOS. Although you can have all the paths in the database, the software always choose the first one when selecting the STAR in the FMC, no matter the runway you have selected.
It is possible to select the correct arrival in the world map. I believe Asobo added the number of the runway to the STAR, meaning each different path is a different arrival. In KBOS arr pull down menu  there are lots of ROBUC3 ARR, one for each runway, and they are correct. But you can´t do that after starting the simulation via FMC (there is only one ROBUC3 ARR there).
This is a major issue, as it makes almost impossible to fly online in VATSIM in the USA, as controllers are always changing runways and procedures during the flight. I don´t know any other country that problem happens.
The problems affect A32NX, default A320 and default 747 (the ones with FMC). I have never tested on G1000 GPS aircrafts.

**Comment by 2hwk** [comment]
Fixed by #4953 closing ☑️
