### ISSUE TITLE
[BUG] Cannot enter CRS under rad/nav on the fmc when you plug in ILS freq

### ISSUE THREAD

**Issue by kthejoker20** [flybywiresim/a32nx#2568]
**Mod Version**

Master

**Describe the bug**

User cannot add "CRS" under rad/nav after you plug in your ILS freq.

**To Reproduce**

1.  Cannot at CRS under RAD/NAV ils frequency.
2.
3.

**Expected behavior**

Should be able to under the course number CRS

**Actual behavior**

Doesn't do anything

**References**

**Additional context**

Was this working before/when did the issue start occurring?
No
Is this a problem in the vanilla unmodded game?
doesnt work there either

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment]
@St54Kevin Has this been fixed/changed by now?
