### ISSUE TITLE
[REQUEST] ZFW / ZFWCG readout on the fmc

### ISSUE THREAD

**Issue by kthejoker20** [flybywiresim/a32nx#2571]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**

Need ZFWCG on the fmc, can't see it once game is started

**References**

**Additional context**

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment]
Already implemented. Select the ZFW/CG field with an empty scratchpad and the current ZFW/CG will be loaded into the scratchpad.

**Comment by MisterChocker** [comment]
Already implemented. Select the ZFW/CG field with an empty scratchpad and the current ZFW/CG will be loaded into the scratchpad.
