### ISSUE TITLE
[BUG] 'UNDEFINED' appears against all fpln wps

### ISSUE THREAD

**Issue by TheSledge-SLEJ** [flybywiresim/a32nx#2585]
**Mod Version**
2020-12-21T10:11:43+00:00

**Describe the bug**
Going through MCDU flow after INIT and AOC INIT (import from Simbrief etc) on checking FPLN page 'UNDEFINED' appears above every waypoint

**To Reproduce**
1. Prep Simbrief flightplan
2. Use Simbrief integration w/flow

**Expected behavior**
Clear flightplan with any airways or routing

**Actual behavior**
'UNDEFINED' above each waypoint in MCDU
EDIT: I note there is no CRZ Flight Level in PROG Page

**References**
![Screenshot 2020-12-21 150541](https://user-images.githubusercontent.com/74037604/102797734-0a38e680-43a8-11eb-8d85-12d2ba07ee5a.jpg)

**Additional context**

Was this working before/when did the issue start occurring?
Was working fine this morning before upgrade to this version

Is this a problem in the vanilla unmodded game?
Don't know

**Comment by pareil6** [comment]
Just to make this easier to reproduce, can you share your SimBrief username as well? That allows us to pull exactly the same flight plan.

**Comment by TheSledge-SLEJ** [comment]
TheSledge

**Comment by MisterChocker** [comment]
The undefined shows up on departure and arrival afaik

**Comment by pareil6** [comment]
Doesn't reproduce for me locally, the airway is left blank for me after loading the flight plan from SimBrief and selecting 29R from CYMJ. Had you done anything else in the flightplan @TheSledge-SLEJ ?

**Comment by TheSledge-SLEJ** [comment]
Just landed it; checking again now

**Comment by TheSledge-SLEJ** [comment]
Spawn CYMJ Gate 53 - Power up - Fast Align
Init A - Init Request - FPlan Loaded; IRS INIT
F-PLN Page - As described  - All WPs 'Undefined'

**Comment by TheSledge-SLEJ** [comment]
Same Result by going first to AOC INIT/PRES and PERF/W&B
INIT A (not pre loaded even though we have already retrieved OFP); INIT REQ
WPs 'Undefined'

**Comment by TheSledge-SLEJ** [comment]
I think I know what it is; I saw this in the Garmin 1000 and it may be the same bug; it's that initial YYN wp which is either duplicated in nav database or is undefined in some way. It's valid in Navigraph and Simbrief.

**Comment by pareil6** [comment]
Are you using Navigraph? Just wondering if there's some quirk in their nav data that would explain why I don't see it on the default nav data.

**Comment by TheSledge-SLEJ** [comment]
Yup Navigraph beta user but I haven't updated it for over a week.



Sent from my Galaxy



-------- Original message --------

**Comment by ErikNL80** [comment]
Having the same issue here with standard NavBlue data and the default flight planner...

**Comment by pareil6** [comment]
Reproduced (my fault, wasn't on the latest mod version) - debugging now.
