### ISSUE TITLE
AUTOBREAK MAX turn off while taxing/breaking before T/O

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#2586]
**Mod Version**

MASTER (FBW)

**Describe the bug**

when i prepare the A/C for Takeoff after engine start and press "autobreak MAX", the preselected autobreak turnes off while taxing to the runway. Eighter when breaking or only for no reasons. it only be active for few secounds.

**To Reproduce**

1. prepare the Aircraft from Cold and dark for takeoff
2. set autobreak MAX for takeoff
3.

**Expected behavior**

autobreak MAX shoud stay on/active until Takeoff 

**Actual behavior**

autobreak MAX turn off, eighter when breaking on the way to the runway, or by itself after few secounds

**References**

-

**Additional context**

-
Was this working before/when did the issue start occurring?
worked befor 0.5.0
Is this a problem in the vanilla unmodded game?
no

Discord username (if different from GitHub):

**Comment by michaeldinozzo** [comment]
Confirm it happened to me as well today using the lastest dev build. It was working well in v0.5.0. Looks like the autobrake disengaging problem is back :(

**Comment by geoffda** [comment]
Yep. I fixed this a while back, so whoever was messing with the autobrakes last broke this. Please roll back whatever change did this, as this is a super annoying bug.

**Comment by geoffda** [comment]
It looks like after some number of seconds the switch just turns off.

**Comment by MisterChocker** [comment]
@geoffda I am pretty sure no one touched the autobrakes. I would appreciate if you can confirm.

**Comment by pareil6** [comment]
Can confirm, have been experiencing this too - setting autobrake max during taxi, a few seconds later the switch cancels (with the clicking noise). Low/med are unaffected, work as expected (even on the ground).

**Comment by Benjozork** [comment]
Most likely caused by #2510

**Comment by geoffda** [comment]
@MisterChocker @Benjozork 

Yes, looks like the autobrake code was ported to the new non-rpn macros. At a glance, it looks like line 216 in https://github.com/flybywiresim/a32nx/pull/2510/files#diff-b05a1f451e28f0824874f6fc08e4a00359063d1c73f570e4580804677dceff38 is wrong. It should be: 
onGroundWaitCounter += 1;

**Comment by geoffda** [comment]
@Benjozork 
Ah sorry, but it looks like the build process now requires Docker and the Linux Kernel. I'm not really wanting to put all of that on my Windows box right now. Can you please try making that change?

**Comment by geoffda** [comment]
Hmm. Actually it looks like I misread the diff. Not completely sure what is going on, but I'm investigating.

**Comment by pareil6** [comment]
I have a fix in mind, testing now

**Comment by geoffda** [comment]
@pareil6 One of the if conditions was ported incorrectly. I have a fix now.

**Comment by pareil6** [comment]
> @pareil6 One of the if conditions was ported incorrectly. I have a fix now.

I think we both stumbled upon the same fix at the same time by the looks of things...

**Comment by geoffda** [comment]
Yes, I wrote the original code which was affected by the change, which is why I was investigating.

**Comment by geoffda** [comment]
Next time, please don't jump on an issue that somebody else is working on as it wasted my time.

**Comment by Benjozork** [comment]
> Next time, please don't jump on an issue that somebody else is working on as doing so wastes people's time.

It's a minor correction. Not a big deal at all, let's remain civil.

**Comment by Benjozork** [comment]
Furthermore, it's developers' responsibility to open draft pull requests to signal intention of working on something.

**Comment by geoffda** [comment]
It is pretty clear that I was working on this. It was my code that was affected after all. Why on earth would anyone investigate a bug if not to fix it? It was fairly frustrating to get stepped on after having spent several hours trying to get the new docker build process to work on my machine so that I could take care of what should have been a simple fix. I didn't really want to spend my afternoon doing any of this, but I did it anyway. It would have been nice to have been shown a little courtesy.

**Comment by wpine215** [comment]
> It is pretty clear that I was working on this. It was my code that was affected after all. Why on earth would anyone investigate a bug if not to fix it? It was fairly frustrating to get stepped on after having spent several hours trying to get the new docker build process to work on my machine so that I could take care of what should have been a simple fix. I didn't really want to spend my afternoon doing any of this, but I did it anyway. It would have been nice to have been shown a little courtesy.

I’ve had this happen to me as well several times, both on this project and at my job. It’s simply the reality of working on a large project. But at this point, all that matters is the fix is done - we don’t have time travel machines so no sense in spending any more thought on this
