### ISSUE TITLE
too excessive Pitch bahaviour e.g. on rotation

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#2587]
**Mod Version**

master (FBW)

**Describe the bug**

As a real world Airbus Pilot i must say, that there is too excessive pitch behaviour on rotation. I take off with C.G. @20% an 0(!) ,  Pitch up trim for Takeoff (155PAX, 9100kg Fuel, 3,5t cargo) (real is between 1 and 1.4UP trim by this CG location) and the nose jumps up on rotation. 
That is a very unrealistic behaviour with this forward center of gravity position. 
I use the master incl. FBW with all the recommenced settings for stick sensitivity and so on. But also without FBW Mod and with the stable build, it seems to excessive compared with the overall behaviour of control inputs.

**To Reproduce**

1. make a takeoff roll with proper C.G. location and trim
2.
3.

**Expected behavior**

nose shouldn´t rise up so quick

**Actual behavior**

with only minor pitch input, the nose jumps up (C.G. @20% and Trim @ 0(!))

**References**

i have references to real world Plane A319/A320/A321

**Additional context**

Was this working before/when did the issue start occurring?
no
Is this a problem in the vanilla unmodded game?
-

Discord username (if different from GitHub):

**Comment by Aarondodd88** [comment]
I also notice this on Take off and landing. There is 2 lines that i change myself located in flight_model.cfg Look for the pitch and roll dampening they are both set at Negative (-) values. I change these back by 75%. The plane doesn't feel like a cessna and much closer to RL manouvering

**Comment by Aarondodd88** [comment]
I just flew the landing challenge in default A320 and the handling was much better and around what i expect to feel in Pitch/Roll. Not sure if the flight model transfers to A32NX mod after their updates but have another go :)

**Comment by donstim** [comment]
> I also notice this on Take off and landing. There is 2 lines that i change myself located in flight_model.cfg Look for the pitch and roll dampening they are both set at Negative (-) values. I change these back by 75%. The plane doesn't feel like a cessna and much closer to RL manouvering

 Most of the variables in the flight_model.cfg file, including the pitch and roll damping terms affect only the legacy flight model. They have no effect on the modern flight model. Go to "Options", "General", "Flight Model" in the MSFS menu and verify that you have the "MODERN" flight model set in the first option on that screen.

**Comment by donstim** [comment]
@andrejetcat Thank you for your feedback. You mentioned you believe the same problem exists for the current dev build without the new FBW system mod.  Which CONF were you in?

Can you please confirm that you are using the "Modern" flight model under "Options", "General", "Flight Model" in the MSFS menu? Excessive pitch up issues have been associated with the Legacy flight model, and some users have had their flight model changed by one of the updates without their knowledge. Not saying that's the case here, but just want to cover all the possibilities.

**Comment by andrejetcat** [comment]
sorry, what do you mean by "which CONF wer you in"?

I rechecked that the flightmodel is on "modern"

**Comment by donstim** [comment]
> @donstim sorry, what do you mean by "which CONF wer you in"?
> 
> I rechecked that the flightmodel is on "modern"

Oh, sorry, what flap setting?  I assume 1+F?

**Comment by tareksabet** [comment]
Try to put the CG at about 29% CG and try to put a convenient Pitch Trim corresponding to this CG and tell me how did it go.

**Comment by danbw9** [comment]
After my own testing, I found that the above issues are seen in the 'legacy' flight model setting. I changed this to 'modern' and the behaviour was normal. This can be done in MSFS Options in-game.

**Comment by andrejetcat** [comment]
modern flight model is set from day one. 
@tareksabet with a normal and typical domestic load (e.g. 5-8t fuel, 150-174 pax and ~2-3t payload, the C.G. is between 20 and 23% (normally! It depends on airline and other factors for shure!) trim for e.g. 23% is 1.1/1.2 up. When I leave trim to 0(!), the rotation behaviour should be more difficult. When i put the C.G. @ 29%, the trim is somethink like ~0.2 down. with this CG the pitch pitch bahviour is much more intense.

**Comment by danbw9** [comment]
@andrejetcat I would like to point out that the above details & values you describe is for the A32ceo. A320neo has very different CG/TRIM positions.

A320neo with THS set to 0 therefore corresponds to a further after CG setting (31%) instead of A320ceo (28.5%).

We have many IRL A320 pilots including neo pilots who have not had any issues with this, and custom FBW is not an issue either.

**Comment by tareksabet** [comment]
@andrejetcat So I tried your CONF for takeoff I followed your steps plus it was set in modern with the custom FBW system and the plane lifted at around 160Kt and when I tried to rotate earlier it was fine at around 135Kt.

**Comment by hotshotp** [comment]
Closing as other real world pilots can confirm the behaviour is intended and correct. Be sure to switch to modern flight model

**Comment by aguther** [comment]
One additional info:
I discovered that the neo actually has a rotation law. I put this on my list to be implemented for the custom FBW and it will streamline the rotation performance because it’s basically a pitch rate law.
