### ISSUE TITLE
Flight director

### ISSUE THREAD

**Issue by griffon55** [flybywiresim/a32nx#259]
![Screenshot_20200830-144428_YouTube](https://user-images.githubusercontent.com/70265927/91669691-ca8e7c00-eae4-11ea-9b85-909f7d4fa91b.jpg)
FD don't  follow ILS glide slope

**Comment by lrargerich** [comment]
You have autopilot turned off.

**Comment by griffon55** [comment]
Autopilot  off or on FD should follow magenta glide slope

**Comment by ukflyer** [comment]
did you have APPR mode armed on the autopilot...can't see any ILS modes on the PFD (GS/LOC)

![ilspfd](https://user-images.githubusercontent.com/70434502/91669899-887b2f80-eb10-11ea-99f1-7c0df97609bc.png)

**Comment by griffon55** [comment]
Yes autopilot off,APP activate LOC button ON. FD high airplane descent to follow magenta glide slope.

**Comment by griffon55** [comment]
I observed as well if I engage APP and disengage autopilot APP disengage  itself.

**Comment by nabil74** [comment]
Just as second opinion,
Last night flew a leg from yssy to ymml landing at ymml rwy27 ils.. captured glideslop with il and fd active worked perfectly. Disactivated autopilot 100 tarmac
 
Might be worth checking you had the ils frequency correct???
 
This was with the dev file downloaded around 8pm Melb time last night.

**Comment by griffon55** [comment]
Perhaps if you disengage autopilot 100 feet of ground  is ok.But me i disengage autopilot  about 1000 feet of ground.anyway no matter  what altitude  you disengage  autopilot  FD must follow glide slope.

**Comment by nabil74** [comment]
No issues my end with ILS and glideslope.
Landing at YMML RWY27ILS video below.

https://youtu.be/ZpG5lrGqw9I

**Comment by griffon55** [comment]
https://youtu.be/DUXp7BxAMoY

**Comment by Curtis-VL** [comment]
@griffon55 This could be an Asobo bug with the Autopilot code!
I wasn't aware the aircraft should follow LOC without AP on, and I guess Asobo wasn't either if it doesn't?

The FMA simply displays the current aircraft state, it can't affect the aircraft's actual state. 👍

**Comment by Curtis-VL** [comment]
I believe this is in the default aircraft also. :)

**Comment by SmithFR** [comment]
Also happened to me I think it's because of a bug where APP disconect itself causing the G/S to disapear from FMA when disconnecting the autopilot

**Comment by PCGamesF1Tech** [comment]
> Yes autopilot off,APP activate LOC button ON. FD high airplane descent to follow magenta glide slope.

Did you press APPR or LOC?? 
If you only arm localizer mode there is no need for the FD and/or AP to follow the glideslope

**Comment by griffon55** [comment]
Loc but it's an ils for KMIA but glide slope appear

**Comment by PCGamesF1Tech** [comment]
If there is a glideslope (full ILS) and you only press LOC the FD will never follow it! 
It does what it's supposed to do and what you tell him 😉 (so most probably just level flight). 
You have to select a vertical mode, either V/S or FPA (to descend at all) or by using APPR pb to follow the glide.
Or do it "raw data" in manual flight without even using FD at all (good training)

**Comment by griffon55** [comment]
Yes i know but as you see on picture autopilot is off and follow glide slope and FD don't  follow glide.i observed when autopilot  is off FD and glide not work together

**Comment by Curtis-VL** [comment]
Should be fixed in this pull request. #289

**Comment by Curtis-VL** [comment]
> If there is a glideslope (full ILS) and you only press LOC the FD will never follow it!
> It does what it's supposed to do and what you tell him 😉 (so most probably just level flight).
> You have to select a vertical mode, either V/S or FPA (to descend at all) or by using APPR pb to follow the glide.
> Or do it "raw data" in manual flight without even using FD at all (good training)

Right, LOC would be the lateral mode. APPR hold would be vertical, following the G/S. (But also follows lateral too)

**Comment by griffon55** [comment]
Because on the picture I'm autopilot off so I'm following the glide
manually and LOOK FD don't  follow the glide.I have aerosoft  A320 fsx and
no bug on this plane and the FD
Autopilot  off follow glide

Le mar. 1 sept. 2020 11 h 47, Curtis English <notifications@github.com> a
écrit :

**Comment by CoffeePanda0** [comment]
Griffon in the screenshot it looks like you don't have ILS in the FMA captured, only LOC. This is why it won't be following. I've done at least 20 ILS approaches and never had this happen in the A32NX, so chances are the aircraft was not configured correctly. I just tested the same approach as you there and it seemed to work fine, maybe try a newer release just incase?

**Comment by griffon55** [comment]
Problem is when i disengage autopilot APP disengage  and  LOC engage
itself.

**Comment by ukflyer** [comment]
i find the ILS capturing mode a bit hit and miss, sometimes i get G/S and sometimes not, don't know what it is. Example below pic with LOC but no G/S with autopilot engaged

![brs](https://user-images.githubusercontent.com/70434502/93003107-c5451e80-f533-11ea-91f4-1579628aede7.png)

**Comment by griffon55** [comment]
Me i get always G/S  and LOC for all ils approach but when disengage
autopilot APP disengage and LOC engage itself

**Comment by hotshotp** [comment]
issue is fixed
