### ISSUE TITLE
[BUG] auto pilot banking to Right side uncontroled 

### ISSUE THREAD

**Issue by Tirus89** [flybywiresim/a32nx#2590]
Hi! while auto pilot on Aircraft starts randomly banking to the Right!
need to force left bank with joystick canceling AP and leveling the plane again then engagin again till it starts following the Fplan again!
it seems to be very Random dis a full flight today without issues
now the second flight it happen already 2 times! 
is this a Bug our something that I config wrong?

**Comment by Benjozork** [comment]
Please do not delete the issue template. Closing.

You most likely have your deadzone set too low in your controller sensitivity settings
