### ISSUE TITLE
[BUG] Engines won't shut down

### ISSUE THREAD

**Issue by Joey92** [flybywiresim/a32nx#2591]
Since this happens in vanilla, too, I'll submit this bug report as an FYI. I haven't sat in the vanilla A320 since a while now.. Noticed it happening in the A320NX.

**Mod Version**

v0.5.0

**Describe the bug**

After landing at my destination airport the main engines do not shutdown when i cut off the master switches.

**To Reproduce**

1. Turn on the engines
2. When available and running in idle, turn off the engine master switches

**Expected behavior**

The engines should shut down when the master switch is set to off afther they were running.

**Actual behavior**

The engines are running and not turning off. Even when the fuel pumps are cut off.

Was this working before/when did the issue start occurring?
v0.5.0 - but since it's in vanilla, it might have been since the US update.

Is this a problem in the vanilla unmodded game?
Yes it is!

**Comment by lukecologne** [comment]
Do you have infinite fuel on?

**Comment by hotshotp** [comment]
fixed in latest asobo update
