### ISSUE TITLE
[BUG] Logo light doesn't go on

### ISSUE THREAD

**Issue by kthejoker20** [flybywiresim/a32nx#2592]
**Mod Version**

Master

**Describe the bug**

Turn the logo light switch on, but the logo on the plane is not illuminated

**To Reproduce**

1.  Just turn on the switch, no light
2.
3.

**Expected behavior**

Light should go on

**Actual behavior**

Nothing happens

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by mikecbr** [comment]
@kthejoker20  in the ground or in the air ?

**Comment by Benjozork** [comment]
Please respect issue template.

Also, the logo light does not come on in the air without the slats extended.
