### ISSUE TITLE
[BUG] Cannot scroll through SID Transitions 

### ISSUE THREAD

**Issue by mak60062** [flybywiresim/a32nx#2595]
**Mod Version**

{
  "built": "2020-12-20T22:57:21+00:00",
  "ref": "",
  "sha": "",
  "actor": "devsnek <me@gus.host>",
  "event_name": "manual"
}

**Describe the bug**

When selecting a SID on the MCDU and going to the available transitions, the user is unable to scroll up or down to view additional transitions when there are more than 4 of them. 

**To Reproduce**

1. Select the ORD6 Departure at KORD. 
2. Attempt press the up or down arrow to scroll through the transitions. 

**Expected behavior**

MCDU should scroll through other available transitions for the SID. 

**Actual behavior**

Arrow keys do nothing. Can only select from the transitions that initially appear, limited to 4. 

**References**

A32NX KORD ORD6 SID (cant scroll):
![image](https://user-images.githubusercontent.com/6889399/102834113-1a10f480-43c1-11eb-847d-0b41ab17a9ea.png)

Default TBM930 KORD ORD6 SID (can scroll):
![image](https://user-images.githubusercontent.com/6889399/102834226-73792380-43c1-11eb-8210-bd75311faa39.png)

**Additional context**

Was this working before/when did the issue start occurring?
Always broken. 

Is this a problem in the vanilla unmodded game?
Yes, but works fine on other aircraft such as the TBM930. 

Discord username (if different from GitHub): Mobius_One_Fox3

**Comment by MICHER79** [comment]
Hello, I confirm this issue, I think is a critical bug

**Comment by 2hwk** [comment]
Fixed by #4953 closing ☑️
