### ISSUE TITLE
[BUG] Not following glide path when perfectly lined up for ILS

### ISSUE THREAD

**Issue by kthejoker20** [flybywiresim/a32nx#2596]
**Mod Version**

Master

**Describe the bug**

Landing at PANC 07R, perfectly lined up at the glide path.  ILS indicates it is caught.  Autopilot does not fly the path.

**To Reproduce**

1.  Fly PANC 07R ILS approach
2.
3.

**Expected behavior**

Should follow the path when perfectly lined up.

**Actual behavior**

Just ignores the signal when locked onto the ILS.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
It's hit or miss, sometimes it works, sometimes it doesn't
Is this a problem in the vanilla unmodded game?

I don't think so.

Discord username (if different from GitHub):

**Comment by jmwebslave** [comment]
I think you might need to do a bit better on your bug reports.  What do you mean by "does not fly the path"?  Vertically?  Laterally?  How had you configured it to fly it?  Your steps to reproduce are pretty lazy.

Just flew the ILS into PANC 07R here and could not reproduce.  Only strangeness was a slight horizontal offset to the right, but it flew the glidepath the whole way to the piano keys.
{
  "built": "2020-12-22T06:48:39+00:00",
  "ref": "",
  "sha": "",
  "actor": "pareil6 <73158172+pareil6@users.noreply.github.com>",
  "event_name": "manual"
}

**Comment by B-KC** [comment]
> I think you might need to do a bit better on your bug reports. What do you mean by "does not fly the path"? Vertically? Laterally? How had you configured it to fly it? Your steps to reproduce are pretty lazy.

It seems pretty clear he said he was lined up laterally, therefore its safe to assume he meant it didn't pick up the vertical guidance. Perhaps instead of being condescending, you could be helpful and educate on proper terminology / testing procedures / more thorough steps to reproduce.

**Comment by MisterChocker** [comment]
@jmwebslave We have rules on how to talk to each other, please read them.

@kthejoker20 Could you give as a bit more information on how to reproduce the bug, to be a bit more specific, was the approach mode engaged and the PFD in top showing LOC and G/S?

**Comment by kthejoker20** [comment]
> @jmwebslave We have rules on how to talk to each other, please [read](https://github.com/flybywiresim/a32nx/blob/master/.github/Contributing.md) them.
> 
> @kthejoker20 Could you give us a bit more information on how to reproduce the bug, to be a bit more specific, was the approach mode engaged and the PFD in top showing LOC and G/S in green?

Yes, the approach mode was engaged.  The PFD was showing LOC G/S in green.  It kinda of followed the horizontal path but was off a mark.  The vertical path it didn't follow at all.  I tried powering off auto pilot the back on, and pressed the approach key, it would work for a couple of seconds, then veer off again.  However, the second time I did the approach, I powered off the autopilot, then back on, and pressed approach key on and off and then it grabbed the ILS.  It was still off, but it followed the trajectory both horizontal and verticle.

**Comment by MisterChocker** [comment]
I can't reproduce on latest master

**Comment by kthejoker20** [comment]
I just flew in into EHAM runway6

It's even worse there.

**Comment by P1NBA11ER** [comment]
I've started having this problem. I've tried 3 different airports so far (KORF, KORD, and KLAX) and none of them would pick up vertical guidance on the ILS. The plane captures the localizer, will horizontally align but maintains the current altitude when capturing. If you have managed speed set, the plane will slow to the appropriate approach speeds and the nose will pitch up to maintain level flight at whatever altitude it's already at. I started noticing this a couple days ago. I have had no ILS problems for months prior so long as the correct frequency was input into the MCDU.

**Comment by P1NBA11ER** [comment]
So I realized I had turned Dev Mode off at some point. Turned it back on and the ILS capture appears to be working correctly again.

**Comment by FlyByWire128** [comment]
I had the same problem with the latest development build this morning (ILS31L at KJFK).  The aircraft was in HDG and ALT Hold (green) with LOC and G/S armed (blue).  Once the localizer was intercepted, the FMA flickered between HDG and LOC*/LOC (green) and largely tracked the localizer (not perfectly).  Once the glideslope was intercepted, the FMA flickered between ALT and G/S (green) and failed to track the localizer (~300 fpm descent).  Because of this, I hand flew the approach.  The flickering continued (both lateral and vertical modes) after AP disconnect until shutdown.

**Comment by P1NBA11ER** [comment]
I installed the stable version and was able to capture the ILS at KORF. It does look like something in the dev version has broken ILS approaches in some/all situations? I have to think this topic would have a lot more action if it was 100% borked for everyone and every airport.

**Comment by Benjozork** [comment]
> 
> 
> I installed the stable version and was able to capture the ILS at KORF. It does look like something in the dev version has broken ILS approaches in some/all situations? I have to think this topic would have a lot more action if it was 100% borked for everyone at every airport.

This is reported in #2838 and we have a probable fix in #2847
