### ISSUE TITLE
[REQUEST] [INSTALLER] Optimize space

### ISSUE THREAD

**Issue by St54Kevin** [flybywiresim/a32nx#2598]
**Is your feature request related to a problem? Please describe.**

Space not used optimal

**Describe the feature you'd like to see implemented**

Optimize the space of the right side. The information text begins way too far at the bottom. The site could be used way more efficiently.

**References**

![image](https://user-images.githubusercontent.com/448627/102866637-df966e80-4437-11eb-8dfc-fbb1ea0bd752.png)

**Additional context**

Discord username (if different from GitHub): St54Kevin#3583

**Comment by wpine215** [comment]
The installer has it’s own repository, so please open an issue there, as this repo is solely for the plane itself.

https://github.com/flybywiresim/installer
