### ISSUE TITLE
[REQUEST] [INSTALLER] Update avail symbol

### ISSUE THREAD

**Issue by St54Kevin** [flybywiresim/a32nx#2599]
**Is your feature request related to a problem? Please describe.**

No

**Describe the feature you'd like to see implemented**

A little symbol at the aircraft logo on the left that indicates an available update. Maybe one for master and one for stable.

**References**

![image](https://user-images.githubusercontent.com/448627/102866814-271cfa80-4438-11eb-9cbb-82e1c77f5ebf.png)

**Additional context**

Discord username (if different from GitHub): St54Kevin#3583

**Comment by wpine215** [comment]
The installer has it’s own repository, so please open an issue there, as this repo is solely for the plane itself.

https://github.com/flybywiresim/installer
