### ISSUE TITLE
[BUG] NO ILS Frequency in RAD/NAV page after Setup Arrival in FMC

### ISSUE THREAD

**Issue by SM-396** [flybywiresim/a32nx#2601]
**Mod Version**
Stable 0.5.0 

**Describe the bug**
I choose in Flightplan the right ILS Runway but when i look in RAD/ NAV page there is no ILS Frequency

**To Reproduce**
1. Setup in Flightplan Page Arrival ILS Runway and STAR 
2. Look in RAD/ NAV Page but the Fields for ILS / FREQ are blank

**Expected behavior**
ILS Frequency should put in automatically 

**Actual behavior**
Blank filed

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by pareil6** [comment]
Asobo bug, occurs in the base game as well.

**Comment by Benjozork** [comment]
> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning
