### ISSUE TITLE
[BUG] Engine will start spoolup immediately after APU flap open

### ISSUE THREAD

**Issue by amsomers** [flybywiresim/a32nx#2607]
**Mod Version**

5.0

**Describe the bug**

It is possible to start an engine without APU bleed.

**To Reproduce**

1. Do not start APU yet
2. Setup engine one for normal start procedure. Nothing will happen yet because APU is still off.
3. Engage APU bleed
4. Start APU as per usual

Now the APU will not start untill Flap open is displayed on SD. Once it starts the engine will also immideately start the N1 spool up. However this would be impossible IRL due to the fact that APU bleed pressure will only build when APU N is around 50%. Even then I doubt whether the bleed pressure would be enough to start the engine.

**Expected behavior**

Engine can only be started once the APU is fully available and APU bleed pressure around 35PSI. This pressure will only be reached at or near the time the APU is at 100% N 

**Actual behavior**

Engine starts immediately after APU is engaged and flap opens with APU bleed on. 

**References**

https://youtu.be/qKbQVewLua8
At around 50% N the Bleed presuure starts to build gradually.

**Additional context**

Was this working before/when did the issue start occurring?
No
Is this a problem in the vanilla unmodded game?
Yes

**Comment by MisterChocker** [comment]
Is this now resolved after our own APU implementation?

**Comment by tracernz** [comment]
I don't think the bleed system is implemented yet.
