### ISSUE TITLE
[REQUEST] More realistic APU GEN font colors

### ISSUE THREAD

**Issue by amsomers** [flybywiresim/a32nx#2608]
**Is your feature request related to a problem? Please describe.**

The APU GEN status displayed on the SD is not using the correct font colors during startup phase.

**Describe the feature you'd like to see implemented**

APU GEN display should show correct font colors during startup.
When the APU is not started the words 'APU GEN' are orange like. V and HZ values are also orange-ish. only load % value is    green. At 86% N of APU the APU GEN V and HZ come alive and start to rise. V value is shown a green HZ remains orange until it is above 390HZ then it become green
![image](https://user-images.githubusercontent.com/75147099/102912378-99fc9480-447d-11eb-8331-c6ca10dd8855.png)

**References**

https://youtu.be/qKbQVewLua8

**Additional context**

**Comment by Benjozork** [comment]
The image reference is from an old EIS1 display FYI. Video is fine.

**Comment by amsomers** [comment]
Image was just to make sure you all do understand which panel I was refering to. Not sure if you call it SD as well.
