### ISSUE TITLE
Issues noted after MSFS Update: CANNOT START APU

### ISSUE THREAD

**Issue by DFWSupertrooper** [flybywiresim/a32nx#2609]
**.5 Stable**

**Describe the bug**
#2 Pumps will not depress after MSFS update 1.12.

**To Reproduce**
1. Power up procedure start.
2. Clear pump white lights on O/H panel.
3. Press #2 switches (all three).

**Expected behavior**
White light should de-illuminate.

**Actual behavior**
Remains OFF with white light.

**References**
N/A

**Additional context**
N/A

Was this working before/when did the issue start occurring?
Was working prior to MSFS update 1.12.

Is this a problem in the vanilla unmodded game?
Don't know but due to MSFS update changes no doubt.

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
Please add a title

**Comment by DFWSupertrooper** [comment]
Sorry...edited.  Cannot engage pumps so cannot start APU so cannot start engines.

**Comment by DFWSupertrooper** [comment]
#2 pumps all three inop.

**Comment by michaeldinozzo** [comment]
Confirmed & reproduced with latest dev build after updating to MSFS v1.12.13.0

**Comment by plumped** [comment]
Same here, not possible to start up APU due to no activation of Fuelpumps 2 is possible after patch

**Comment by ChronosMasterOfAllTime** [comment]
Here is the error:

![image](https://user-images.githubusercontent.com/28963807/102919023-abc64380-444d-11eb-8526-8d61fa17ac84.png)

**Comment by Ash624** [comment]
Same here, they broke our toy again, unable to start APU. And just B4 Xmas when we want to sim hard!

**Comment by ChronosMasterOfAllTime** [comment]
Did anyone try without the Mod? I assume the stock aircraft would be broken as well if this is the error being caught by the Fuel System

**Comment by rick2909** [comment]
> Did anyone try without the Mod? I assume the stock aircraft would be broken as well if this is the error being caught by the Fuel System. I was comparing interior XML files and their node ID's; both are the same.

The default A320 works like it should

**Comment by pedroglr** [comment]
And if you try to start it from the runway the sim will crash.

**Comment by ChronosMasterOfAllTime** [comment]
> > Did anyone try without the Mod? I assume the stock aircraft would be broken as well if this is the error being caught by the Fuel System. I was comparing interior XML files and their node ID's; both are the same.
> 
> The default A320 works like it should

They must be programmatically overriding the node ID's in the stock model. But what I pasted from the dev console was what I was seeing..

**Comment by vlbreda** [comment]
Tip: start the sim today without internet connection so you skip the update for now. Reconnect internet connection as soon as you are in the main menu. Install the update after a few days, when a solution is provided (I have the Steam-install, not sure if this works for other sources).

If this tip comes too late for today's update, you may remember it for the next time!

**Comment by ChronosMasterOfAllTime** [comment]
Comparing the default fuel template to what the mod has is very different.

fuel.xml

```
<Template Name="ASOBO_FUEL_Push_Pump_Template">
	<DefaultTemplateParameters>
		<PART_ID>FUEL_Push_Pump</PART_ID> 
		<ID>1</ID>
		<OFF_TOOLTIP></OFF_TOOLTIP>
		<ON_TOOLTIP></ON_TOOLTIP>
	</DefaultTemplateParameters>
```

Mod:
A32NX_Interior_misc.xml

```
    <Template Name="FBW_Airbus_Fuel_Pump">
        <UseTemplate Name="FBW_Push_Toggle">
            <SEQ2_CODE>(A:FUELSYSTEM PUMP SWITCH:#ID#, Enum) 0 ==</SEQ2_CODE>
            <LEFT_SINGLE_CODE>#ID# (&gt;K:FUELSYSTEM_PUMP_TOGGLE)</LEFT_SINGLE_CODE>
            <TOOLTIPID>%((A:FUELSYSTEM PUMP SWITCH:#ID#, Enum) 0 ==)%{if}TT:#OFF_TOOLTIP#%{else}TT:#ON_TOOLTIP#%{end}</TOOLTIPID>
        </UseTemplate>
    </Template>
```

**Comment by Captherky** [comment]
Agree APU is borked after latest helpful Asobo update?
Also Options screen in MCDU is borked, no menu after options available.

**Comment by michaeldinozzo** [comment]
Wow that was fast! Thanks

**Comment by Captherky** [comment]
Yes I’m very annoyed!

I’ve just bought AH2 and cant fly the bloody Neo with the FBW in it!

Its totally useless!

Hopefully the FBW team will undo the BOLLOX that ASOBO have made AGAIN!!

Happy Christmas!



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by SimonlePilot** [comment]
Totally cheesed off.. When everything was working really well... along came the MSFS2020 update.. totally screwed everything up.. Asobo.. please leave the A320NX alone.

**Comment by nistei** [comment]
> Totally cheesed off.. When everything was working really well... along came the MSFS2020 update.. totally screwed everything up.. Asobo.. please leave the A320NX alone.

We are working off of the base A320. Updates to the base A320 introduce incompatibilities. They are not breaking anything on purpose, rather they are trying to fix the default plane. Once we move away from working off of the default plane we won't be affected by updates as much.

**Comment by vlbreda** [comment]
@nistei: what's the reason you haven't choosen for a hard fork yet? IMO this might prevent returning issues with updates.

**Comment by maxpull82** [comment]
> Ecco l'errore:
> 
> ![image](https://user-images.githubusercontent.com/28963807/102919023-abc64380-444d-11eb-8526-8d61fa17ac84.png)

Infatti se lo fai partire a motori accesi il sim si chiude.

**Comment by maxpull82** [comment]
> > Qualcuno ha provato senza il Mod? Presumo che anche l'aereo di scorta sarebbe rotto se questo fosse l'errore colto dal sistema di alimentazione. Stavo confrontando i file XML interni e i loro ID nodo; entrambi sono uguali.
> 
> L'A320 predefinito funziona come dovrebbe

confermo

**Comment by Benjozork** [comment]
@maxpull82 Please use English for commenting on GitHub.

**Comment by nistei** [comment]
@vlbreda We are working on it. One issue is the size (MB) of the mod after hard forking, we are still trying to improve on that.

**Comment by SimonlePilot** [comment]
> @vlbreda We are working on it. One issue is the size (MB) of the mod after hard forking, we are still trying to improve on that.

Good luck... fingers crossed... such a shame that all the hard work that had gone into the A320NX and Asobo have just killed it.

**Comment by vlbreda** [comment]
@nistei: Ok, I see. Big respect for all the work you are doing!

**Comment by Captherky** [comment]
I am sick and tired of Asobo ignoring Mods that supercede their pathetic attempts at flight models.
Every update they mess up our great mods! FBW was spot on, now its no good!
If you look at what they have tried to do, they try to have copied the protocol for FSB.
But unfortunately they have borked all most everything! gain!
This sim is not good....is it?
I am giving up on this sim!

**Comment by Captherky** [comment]
The default plane was rubbish! FBW made s dim out of it. Now , just in time for Christmas , Asobo messed with the Neo, knowing full well that FBW was a huge following. I think this is malicious on Asobo's part, bad blood. They may as well, have completely excluded the Neo from their so called updates. I knew they would ruin theFBW sim. Makes me want to delete the entire sim! I'll go back to DCS!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Benjozork** [comment]
It's fixed my friend. Use the development version.

**Comment by Captherky** [comment]
You see! That's why Asobo should keep off our FBW Neo! The FBW Devs seem to have many times the computing power of ASOBO! I WISH they were a separate program! Now I await the other mods that have been destroyed? CJ4?........

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
