### ISSUE TITLE
[BUG] Fuel Pump won't start

### ISSUE THREAD

**Issue by xander1401** [flybywiresim/a32nx#2610]
**Mod Version**

Dev + Stable from the installer

**Describe the bug**

When I try to turn on the fuel pumps L TK PUMP 2, CTR TK PUMP 2 and R TK PUMP 2 stay off on the panel and on the ecam.

**To Reproduce**

1. Start the sim with an aircraft in cold and dark.
2. Switch BAT 1+2, EXT PWR, etc. on.
3. Switch all fuel pumps on.
4. The three from above will stay off.

**Expected behavior**

The white lights should turn off like the other pump switches.

**Actual behavior**

 L TK PUMP 2, CTR TK PUMP 2 and R TK PUMP 2 stay off.

**References**

Video will follow.

**Additional context**

Was this working before/when did the issue start occurring?
After an update of A32NX and FS2020.

Is this a problem in the vanilla unmodded game?
Not in general/I cannot undo the updates

Discord username (if different from GitHub):
xander

**Comment by bbrushfield** [comment]
Known issue I believe

**Comment by xander1401** [comment]
Here is the video: https://drive.google.com/file/d/1haddyuOV-vl-7KXL1-CGA2NnvunUAIF_/view?usp=drivesdk

**Comment by xander1401** [comment]
> Known issue I believe

I haven't found a bug report 5 mins ago.

**Comment by bbrushfield** [comment]
> > Known issue I believe
> 
> I haven't found a bug report 5 mins ago.

See the FlyByWire Discord

**Comment by xander1401** [comment]
It was #2609. Maybe a wrong title. Thanks @Benjozork for fixing!

**Comment by Benjozork** [comment]
Don't close until it's into dev :)

**Comment by SimonlePilot** [comment]
So annoying.. cant do an A320NX flight since the update of MSFS2020.. why should this update cause so many issues with the A320NX, why cant ASOBO leave it alone.

**Comment by maxpull82** [comment]
dopo l'aggiornamento di oggi la versione di msfs, l'A320 neo non funziona piu' a motori spenti l'apu non si avvia e se fai la prova in pista a motori accesi si chiude il simulatore. disinstallando l'aereo funziona normalmente.

**Comment by xander1401** [comment]
> Don't close until it's into dev :)

OK, thought the issue isn't necessary anymore because it's covered with #2609
