### ISSUE TITLE
[BUG] APU Start Not Becoming Avail

### ISSUE THREAD

**Issue by Blockjock47** [flybywiresim/a32nx#2616]
**Mod Version**

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
Fixed in master, does not respect template.

**Comment by Blockjock47** [comment]
Not sure what you mean? Should I repull the current master?

**Comment by Blockjock47** [comment]
It was working this morning prior to installing the update...

**Comment by Benjozork** [comment]
Yes, it is fixed in the current master.

Yes, because it was broken by the update.

**Comment by Blockjock47** [comment]
Thank you for the instant replies! Ill check it out.

**Comment by Blockjock47** [comment]
Downloaded the following: https://github.com/flybywiresim/a32nx/releases/latest/download/flybywiresim-a32nx.zip

Did not make a difference
