### ISSUE TITLE
"Runway Turn Lights" intrude into flight deck

### ISSUE THREAD

**Issue by CaptCQ** [flybywiresim/a32nx#262]
When Landing gear is retracted, the Runway Turn Lights intrude into the flight deck as if the fuselage isn't there. Also noticed they don't turn with the front wheel. Not sure if that is a normal A320 feature.

**Comment by lrargerich** [comment]
Can confirm this happens.

**Comment by PCGamesF1Tech** [comment]
The lights don't turn at all. 
The part below the steering cylinder (where the headset is located) is turning. 
The rest is fixed. 
And the lights turn off when the gear is retracted,regardless of the switch position. 

![IMG_20200831_093916_1](https://user-images.githubusercontent.com/39101086/91696475-ed19a700-eb6f-11ea-927e-ecfdb458cd39.jpg)

**Comment by CaptCQ** [comment]
@PCGamesF1Tech that would explain the no turningness. Cheers.

**Comment by PCGamesF1Tech** [comment]
Yes, unfortunately no LED Matrix lighting in an A320 yet ;-)

**Comment by Curtis-VL** [comment]
Fixed in #389, thanks for the report! 👍
