### ISSUE TITLE
[BUG] Engine two does not start

### ISSUE THREAD

**Issue by lekkerjonty** [flybywiresim/a32nx#2623]
**Mod Version**
latest stable build

**Describe the bug**
 i loaded up the aircraft for the first time and tried start engine two from cold and dark. neither engine would start, but fuel pumps for engine two isnt able to turn on. i press the button and it makes a click but nothing happens. i then tied it by spawning in on the runway and no engine were on and again the fuel switches wont work

**To Reproduce**

1. updated to the new edition
2. loaded up the sim
3. spawned in at SOU airport and tried to start aircraft from cold and dark.

**Expected behavior**

For it work normally.

**Actual behavior**

Doesnt work

**References**

**Additional context**

Was this working before/when did the issue start occurring?
After the lastest stable build update.
Is this a problem in the vanilla unmodded game?
yes

Discord username (if different from GitHub):

**Comment by akwa57** [comment]
this happen after msfs update...

**Comment by Benjozork** [comment]
Fixed in the development version. Please look at past issues before opening new ones.
