### ISSUE TITLE
cant start engine after msfs2020 update

### ISSUE THREAD

**Issue by akwa57** [flybywiresim/a32nx#2624]
**Mod Version**

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
Fixed in the development version. Also, please do not ignore the issue template.

**Comment by dellycowboy** [comment]
Same here. Cannot start the APU

**Comment by dellycowboy** [comment]
> Fixed in the development version. Also, please do not ignore the issue template.

Was that just now, because I updated it 30mins ago an I turn on 2nd fuel pumps nor start the APU?

**Comment by Benjozork** [comment]
Make sure you installed the development version and not the stable 0.5.0.

**Comment by dellycowboy** [comment]
> Make sure you installed the development version and not the stable 0.5.0.

Ok thanks will download again, did try both versions tonight but was unable to start.

**Comment by dellycowboy** [comment]
Yes all works now after redownload, thanks
