### ISSUE TITLE
latest msfs update, bug a320 neo

### ISSUE THREAD

**Issue by maxpull82** [flybywiresim/a32nx#2626]
**Mod Version**

**Describe the bug**

version 0.5.0 does not work after msfs has been updated. the apu does not start pumps 2 always stay on off. and if you try to start with engines on from the track the simulator crashes.

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
Fixed in the development version.

**Comment by B-KC** [comment]
> Fixed in the development version.

Any timeframe on when this will be moved to stable? Development version is giving me CTD's pretty consistently.

**Comment by ThatRedMelon** [comment]
0.5.1 is already out
