### ISSUE TITLE
[BUG] Autobrake max cannot be selected when airborne

### ISSUE THREAD

**Issue by clchan1234** [flybywiresim/a32nx#2629]
**Mod Version**
 master

**Describe the bug**
 Autobrake max can only be selected on the ground but not when airborne. 

**To Reproduce**
 Select autobrake max when airborne. 

1. Normal takeoff
2. Select Autobrake max above 1000ft. 
3.

**Expected behavior**
 should be able to select it when airborne. 

**Actual behavior**
 wasn't able to select when airborne. 

**References**

**Additional context**

Was this working before/when did the issue start occurring? Unknown

Is this a problem in the vanilla unmodded game? Unknown

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
That's how it works in the real plane.

**Comment by hotshotp** [comment]
working as intended
