### ISSUE TITLE
[BUG] Flight Simulator 2020 with latest VR update (v1.12.13) crashes when using the A32NX model

### ISSUE THREAD

**Issue by daves8468** [flybywiresim/a32nx#2630]
**Mod Version**
v0.5.0

**Describe the bug**
Adding in the 0.5.0 A32NX model to the Community folder using the latest MSFS 2020 version 1.12.13 (which is a required update and contains the new VR capabilities).  Starting the sim works fine, although lots of errors show up in the dev console log related to loading the A320 model after selecting it in the hangar.  When starting a flight with the A320, the sim starts loading and gets about 80% there, according to the progress bar, and then the sim crashes (no error popups or anything in the UI), it just exits completely.

**To Reproduce**
1. Install the A32NX mod in the Community folder.
2. Start MSFS2020.
3. Start a new flight in World Map, and select the A320neo aircraft.  Any airport will do.
4. Click on Fly, wait for a short time, and the sim disappears.

**Expected behavior**
The sim would load the flight properly and would show us at the selected airport.

**Actual behavior**
The sim crashes before finishing loading the flight.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
This was working in the previous version of MSFS2020, only started failing after the update to v1.12.13.

Is this a problem in the vanilla unmodded game?
No.

**Comment by Benjozork** [comment]
Fixed in latest development version.
