### ISSUE TITLE
fuel pumps not working, APU does not start after last MSFS update 

### ISSUE THREAD

**Issue by majd3994** [flybywiresim/a32nx#2632]
**Mod Version**
 0.5.0

**Describe the bug**
 after the last MSFS update 1.12.13 , only part of the fuel pumps work and the APU does not start at all. I run it without any liveries. Version 0.5.0 was working fine before 

**To Reproduce**

1. just loading the aircraft like usual 
2.
3.

**Expected behavior**
fuel pumps to work and APU to work 

**Actual behavior**
 APU does not start 

**References**

**Additional context**

Was this working before/when did the issue start occurring?
yes

Is this a problem in the vanilla unmodded game?
 no 

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
Already reported. Please look for issues before opening new ones.

Also, fixed in master.
