### ISSUE TITLE
Crash to desktop after Dec Msfs update

### ISSUE THREAD

**Issue by Kirkles53** [flybywiresim/a32nx#2633]
**Mod Version**
 latest stable version 0.5

**Describe the bug**

After installing Dec 22 update from msfs; the a32nx crashes to the desktop after loading the scenario and just before the  “ready for flight” .   If I delete the mod the sim runs fine. Interestingly the a320 landing challenge doesn’t work when the mod is installed. It says something is missing from the content manager. All other aircraft and mods work fine with the new update. 

**To Reproduce**
load any scenario with the a32nx.
tried a flight scenario using the a32nx after installing the Dec 22 MSFS update. 

**Expected behavior**
I expected it to run as it did prior to the update which was fantastic. 

**Actual behavior**

Crashes to desktop as soon as the scenario starts. 

**References**

**Additional context**

Was this working before/when did the issue start occurring?yes

Is this a problem in the vanilla unmodded game?the default a320 runs ok as long as the mod is not installed. 

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Please look for already reported issues before opening more for already fixed problems
