### ISSUE TITLE
[BUG] FUEL Panel PUMPS issues for 1.12.13.0

### ISSUE THREAD

**Issue by dc1ps2** [flybywiresim/a32nx#2634]
**Mod Version**

{
  "built": "2020-12-22T06:48:39+00:00",
  "ref": "",
  "sha": "",
  "actor": "pareil6 <73158172+pareil6@users.noreply.github.com>",
  "event_name": "manual"
}

**Describe the bug**

In the latest update version of Microsoft Flight Simulator 1.12.13.0, FUEL Panel all for PUMP 2 can't be open, always off.

**To Reproduce**

1. open battery 1 with 2 
2. open EXT power 
3. open FUEL panel L TK PUMPS > PUMP1 > PUMP2 > R TK PUMPS

**Expected behavior**

**Actual behavior**

**References**

![圖片](https://user-images.githubusercontent.com/11674129/102961953-a84fbc80-4520-11eb-8054-cd5515747391.png)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Please look for existing issues before opening new ones. This is resolved in master.
