### ISSUE TITLE
Fuel pumps not working

### ISSUE THREAD

**Issue by wildbill75** [flybywiresim/a32nx#2636]
Hello,

With your latest stable version 0.5.0 of the A320NX and with the 1.12.13.0 FS2020 version (22/12/2020 update), the fuel pumps n°2 of left center & right tanks can't be set to "on".
![2020-12-23 07_26_12-Microsoft Flight Simulator - 1 12 13 0](https://user-images.githubusercontent.com/40383856/102966702-aff76d00-44f0-11eb-8c23-f238c4ee7ca3.jpg)
![2020-12-23 07_29_12-Microsoft Flight Simulator - 1 12 13 0](https://user-images.githubusercontent.com/40383856/102966704-b0900380-44f0-11eb-9f71-370db09f8dca.jpg)
![2020-12-23 07_29_33-Microsoft Flight Simulator - 1 12 13 0](https://user-images.githubusercontent.com/40383856/102966705-b1289a00-44f0-11eb-8935-78a17f0ff94c.jpg)

Therefore, the APU is not spooling up and the engines won't start.  I tried the CTRL+E to do an auto start but doesn't work.

Cheers

**Comment by Benjozork** [comment]
Fixed in 0.5.1
