### ISSUE TITLE
roll oscillation is back after 22th update

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#2638]
**Mod Version**

DEV 0.5.1

**Describe the bug**

There is a noticable roll oscillation @cruise and decent (high, mid altitudes), like it was some updates before. not intense, but noticable.

Plane proper set, flight model to "modern"

**To Reproduce**

1.make a flight from cold to dark to onblocks, you will notice it in flight, mainly @cruise
2.
3.

**Expected behavior**

no roll oscillation

**Actual behavior**

little roll oscillation

**References**

-

**Additional context**

-
Was this working before/when did the issue start occurring?
yes
Is this a problem in the vanilla unmodded game?
-

Discord username (if different from GitHub):

**Comment by wpine215** [comment]
Can you provide a short video (<1min.) of this oscillation, providing both external views and internal views with the F/CTL ECAM page visible?

**Comment by andrejetcat** [comment]
@wpine215 i will try it. i will post it, as soon as possible.

**Comment by andrejetcat** [comment]
i can´t make a video for now, but i try the mod with the FBW, and with it, I don´t recognise the problem. It was only with the master build.

**Comment by DFWSupertrooper** [comment]
I am seeing the same but it's difficult to say if it's within the acceptable actual wobbling due to wind (at FL340 facing 54K 11 o'clock headwind about 3K above solid cloud cover) or if it's the return of the hippy-hippy shakes.  It seems to be fairly sporadic in pattern, not a complete back and forth as was observed in prior editions.

**Comment by AdmiralArtemiy** [comment]
Confirm on today`s dev.

**Comment by skelly18** [comment]
Just to say that I am experiencing the same wobble (like the 'classic' wobble that was fixed a month or so ago) [using latest dev version as of 24.12]. Present but not pronounced in cruise, but much more sever during approach at low speeds. Occurs even without wind. Turning SEC1 on/off doesn't help. Appeared after 22nd Dec update.

**Comment by DFWSupertrooper** [comment]
> Just to say that I am experiencing the same wobble (like the 'classic' wobble that was fixed a month or so ago) [using latest dev version as of 24.12]. Present but not pronounced in cruise, but much more sever during approach at low speeds. Occurs even without wind. Turning SEC1 on/off doesn't help. Appeared after 22nd Dec update.

I can confirm this description.  Every flight using stable v0.5.1 for me.  Not as pronounced as it once was, nor as steady of a beat...it's more like jiggling for lack of a better term.  The A/C acts as if it is lightweight in the wind...like a Cessna bouncing around where this A/C shouldn't move much (in my observation).  100% of flights now.  He's also right in that turning off SEC 1 does _not_ stop it.

**Comment by skelly18** [comment]
Just thought I'd share a couple of short videos to show what's happening (for me) re: the AP wobble as it's quite severe in my case, at least at lower speed / altitude. Reproducible anywhere in the world and without wind (becomes more pronounced if wind). At cruise / high speed - slight wobble, but not pronounced (video 1). At lower speeds, wobble becomes progressively more pronounced (video 2). Latest dev version, no other mods installed etc.

**Comment by skelly18** [comment]
High speed - very minor wobble

https://user-images.githubusercontent.com/76559520/103141724-5067b000-46f0-11eb-9c9e-46c4e7a83e41.mp4

**Comment by skelly18** [comment]
Low speed - much more severe wobble

https://user-images.githubusercontent.com/76559520/103141739-886ef300-46f0-11eb-99e6-73b970a79d3e.mp4

**Comment by captainjohn73** [comment]
I have the same problem- both in stable and latest dev version. I started noticing it yesterday, 12/25, and it persists today. I tried switching off SEC1, toggling AP and FD, nothing helps. Deadzones are big already too.

**Comment by Watsi01** [comment]
Can confirm slight wobbling (independend of winds).
