### ISSUE TITLE
[BUG] displays of the second officer are completely duplicated with the displays of the captain

### ISSUE THREAD

**Issue by NitroMaxx72** [flybywiresim/a32nx#2640]
**Mod Version**
Last dev 

**Describe the bug**
Second officer's displays duplicate those of the captain

**To Reproduce**
Load the plane anywhere
try to switch the map view
Also press FD and LS

**Expected behavior**
When changing modes on the part of the captain, it should not be duplicated on the part of the second officer

**Actual behavior**
Actions with displays for the second officer are completely duplicated, and the switches for the second officer do not work

**References**
https://youtu.be/rGQ5tQG0qe8

**Additional context**
Worked until yesterday's update, I think it has something to do with vanilla unmodded game

Discord username Nitro#5130

**Comment by wpine215** [comment]
Related #2639
