### ISSUE TITLE
[BUG] Can't turn off wipers and can't select TCAS mode

### ISSUE THREAD

**Issue by StefaBet** [flybywiresim/a32nx#2641]
**Mod Version**

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring? yes it was working until last time i used it which is 3 weeks ago

Is this a problem in the vanilla unmodded game? vanilla what??

Discord username (if different from GitHub): S B#3247

https://user-images.githubusercontent.com/76514859/102979566-85b0aa00-4506-11eb-9943-953a6b47ec66.mp4

**Comment by fsxmanu** [comment]
Do you have "YourControls" isntalled by any chance? Try updateing that/removing that mod and see if it helps.

**Comment by OstC6** [comment]
Or maybe the "copilot" addon, it is known to provide this kind of issue.

**Comment by LarrySheen** [comment]
Same here! update your "copilot" addons, it would help

**Comment by Benjozork** [comment]
Template not followed.
