### ISSUE TITLE
[バグ]Problems with other aircraft

### ISSUE THREAD

**Issue by junta999** [flybywiresim/a32nx#2642]
**flybywiresim-a32nx  122320 VER5.1**

**Describe the bug**
Problems with other aircraft

When I put the A32NX MOD in the community folder, the FMC of the Boeing 747-8 disappears.

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Awemeter** [comment]
Follow template please.

**Comment by valenzz2004** [comment]
can confirm ive been getting this issue as well

**Comment by Benjozork** [comment]
Probably fixed by #2672

**Comment by junta999** [comment]
After installing A32NX-master 20/12/27, it was solved.
Thank you very much.

**Comment by NathanInnes** [comment]
Closing issue as it has been resolved.
