### ISSUE TITLE
[BUG] Radio frequency always 124.850

### ISSUE THREAD

**Issue by ErikNL80** [flybywiresim/a32nx#2644]
**Mod Version**

Master (23 dec)

**Describe the bug**

The vanilla A320 received a fix for this bug, there the readio frequency is automatically updated when you use ATC. With the FBW mod, frequency always says 124.850.

**To Reproduce**

1. Start a flight with the A320nx
2. Monitor radio frequency
3. Use ATC to change frequency
4. Notice they always stay at 124.850
5. Test the same procedure in the vanilla version, there the issue is solved

**Expected behavior**

I would expect the radio frequencies to be updated visually when changing it by using ATC

**Actual behavior**

The radio frequency always stays at 124.850

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Occured after the bug was introduced in the vanilla version.

Is this a problem in the vanilla unmodded game?
No

**Comment by Benjozork** [comment]
reproduced
