### ISSUE TITLE
[BUG] Flickering Screens and Lights

### ISSUE THREAD

**Issue by Iadbound** [flybywiresim/a32nx#2647]
**Mod Version**

Development Build of 12/23 from commit cf67ef2.  A32NX installer used, v.0.7.

**Describe the bug**

Multiple screens and displays flickering on and off.

**To Reproduce**

1. Spawn a flight at EGLL on runway 27R.  Tried it with real-time weather and clear skies. 
2. Alternatively, spawn a cold and dark flight at EGLL at several different gates. Start the battery and external power.
3. Alternatively, spawn a cold and dark light at KLAS. Start the battery and external power.
4. No other actions were needed.
5. A32nx mod is the only item in the "Community" folder.  Freshly installed several times.
6. Also tried with liveries and Navigraph data installed, and got the same results. 

**Expected behavior**

No flickering.

**Actual behavior**

Flickering.

**References**

Video uploaded to Youtube
https://youtu.be/IdRvl2oG8Ig

**Additional context**

Was this working before/when did the issue start occurring?
It worked before.  New after latest MSFS 2020 Asobo-provided patch, 1.12.13.0

Is this a problem in the vanilla unmodded game?
No.  Tested it with vanilla and the screens and other displays were normal.

Discord username (if different from GitHub):
Same as discord.

**Comment by pepperoni505** [comment]
Please remove any other mods from your community folder as this may be a mod conflict

**Comment by Iadbound** [comment]
Thanks for the note.  As I noted in Item No. 5 above, the A32nx was the only mod in the Community folder.  That was also true when I made the video.

That said, I did initially try it with other mods in the Community folder.  However, when I ran into the problem, I cleared out the Community folder and did a clean install of the A32nx.  From there, all tests were done with no other mods in the Community folder.

**Comment by Sergiy0503** [comment]
I just tried to install game again and patched game on to 1.11.7.0 version.
Unfortunately the result is the same, as with stable 0.5.1 and developmen versions.

**Comment by Sergiy0503** [comment]
tried to rolled on 0.5.0 version , everything is ok

**Comment by Benjozork** [comment]
Looks like an issue with certain GPU configurations with the Asobo model changes.

Can you try re-installing your graphics drivers ?

**Comment by Iadbound** [comment]
Hmmm.  Not sure what option I have on the driver-side.  I've got a 6900xt and there is no driver newer than the one I'm using.  Also, it doesn't seem to be a problem with the vanilla A320.  I'll see what I can figure out.

**Comment by Benjozork** [comment]
I haven't experienced this issue on newest AMD drivers but I am on Polaris (RX 480).

Do you have any other GPUs to try with ?

You're the first person I see with this issue

**Comment by Iadbound** [comment]
Yes.  I have a 2070.  I did reinstall the AMD driver, but there was no change.

**Comment by pepperoni505** [comment]
If it's possible can you try with the 2070?

**Comment by Sergiy0503** [comment]
I'am again tried to update from 0.5.0 to current version 0.5.1. 

Issue reappear again, I Am also try to reinstall driver, but there was no change (GTX 1660 ti)

**Comment by Iadbound** [comment]
Not really a practical option. That’s a great many driver, setting, and other changes to run the test, but if I extra time I may try it. 

Is there anything with this setup that I can test for you?

**Comment by Iadbound** [comment]
So I put the 2070 back in. It’s still flickering with both the stable and development version. It does not flicker with the vanilla A320.

**Comment by Iadbound** [comment]
Completely reinstalled MSFS. That seemed to correct the problem, but testing is limited so far.

**Comment by pepperoni505** [comment]
Interesting. Thank you for testing this out for us. If this issue occurs again or if anyone else has this issue, please respond to this thread.

**Comment by Sergiy0503** [comment]
Good day, this problem still not solved for me if I use 0.5.1 and development version.

But with 0.5.0 is ok...

**Comment by NathanInnes** [comment]
> Completely reinstalled MSFS. That seemed to correct the problem, but testing is limited so far.

@Sergiy0503 Have you tried this solution that this person has used?

**Comment by Sergiy0503** [comment]
I will check this, and let you know.

Нд, 3 січ. 2021, 19:31 користувач Nathan Innes <notifications@github.com>
пише:

**Comment by Peles69x** [comment]
Can u help me?
Hi all, this problem still not solved for me if I use 0.5.2.
with 0.5.0 it doesn't work.
apu doesn't start.
My video card is Nvidia GeForce GTX 1050 Ti
Regards

**Comment by Benjozork** [comment]
@Peles69x Please open another ticket as this is not about the APU.

**Comment by Benjozork** [comment]
Also, no response from author.

**Comment by Peles69x** [comment]
Can u help me?
Hi all, this problem still not solved for me if I use 0.5.2.
with 0.5.0 it doesn't work.
My video card is Nvidia GeForce GTX 1050 Ti
Regards
