### ISSUE TITLE
[BUG] Unable to launch the new Paris-Charles de Gaulle landing challenge

### ISSUE THREAD

**Issue by craigusus** [flybywiresim/a32nx#2648]
**Mod Version**

Dev version from the installer
`{
  "built": "2020-12-23T08:54:29+00:00",
  "ref": "",
  "sha": "",
  "actor": "Will Pine <wpine215@gmail.com>",
  "event_name": "manual"
}`

**Describe the bug**

When attempting to launch the new Paris-Charles de Gaulle landing challenge, I'm presented with a message stating 'ITEM NOT DOWNLOADED. One or more required items are missing. Go to the Content Manager to download them.'
When taken to the Content Manager there is nothing to be downloaded.
This only happens when the FBW mod is enabled.

**To Reproduce**

1. Disabled all mods
2. Launch Sim and install the mandatory update: v1.12.13.0
3. Close Sim
4. Enabled all mods (also tried with all mods disabled except the FBW a32nx)
5. Launch Sim
6. Launch new landing challenge

**Expected behaviour**

Landing challenge to work without error

**Actual behaviour**

When attempting to launch the landing challenge I'm presented with the below:
![image](https://user-images.githubusercontent.com/6324863/102992895-15a92080-4514-11eb-9f40-7c1df7239b0e.png)
Then, when I am in the new Content Manager:
![image](https://user-images.githubusercontent.com/6324863/102992973-35d8df80-4514-11eb-84ac-8bafd28c0c92.png)

Was this working before/when did the issue start occurring?
N/A - New feature within Sim

Is this a problem in the vanilla unmodded game?
No

**Comment by ThatRedMelon** [comment]
Landing challenges are no longer supported with A32NX. If you want to perform them you will need to uninstall A32NX.

**Comment by craigusus** [comment]
Ok, thanks.
