### ISSUE TITLE
[REQUEST] Is there any way to config the TM Airbus Quadrant like in the FBW version?

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#2650]
**Is your feature request related to a problem? Please describe.**

I try the FBW version of the mod, but it is not realistic for now! so i went back to the master/Dev Build.

I use the Thrustmaster airbus throttle and i was very happy, that there was an option to config the detens proper by adding the ThrottleConfiguration.ini in the "%LOCALAPPDATA%\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalState\packages\<name of a32nx folder in community folder>\work\" -Folder.

It works great with the FBW version!

is there any way to do it with the DEV/Master build? 

**Describe the feature you'd like to see implemented**

**References**

**Additional context**

Discord username (if different from GitHub):

**Comment by ErikNL80** [comment]
This will come when the FBW is completed, so a little bit of patience here is needed ;) After the latest update you need to delete/reset your Throttle profile and create a new one. Things have changed! I.E. the IGN/Start knob now correctly moves back to norm...

**Comment by Saschl** [comment]
In addition to the previous comment I'd say that nothing fundamentally will change in the FBW. There's still some things to be sorted out but the handling will stay (I believe). That's why I'm curious what you find unrealistic about it?

**Comment by andrejetcat** [comment]
@Saschl thank you for you answer. As a real world A319/A320/A321 pilot I have good references to the feeling of the FBW system. to my mind, the Aileron/Rudder mix is a bit too much. there is to much yaw compared to roll action when moving the stick.
@ErikNL80 thank you, but i already try that and it is not as good as the FBW mod method, because the manual thrust range is much to sensitive and the detents doesn´t fit perfectly. so i hoped, that there is an option to "modify" the throttle.ini with the values for the fbw version. but, as it looks, i have to live with that now :) thank you!

**Comment by Saschl** [comment]
You can also go to the Discord server and share your feedback in the #fbw channel, I think the devs will appreciate that!

**Comment by andrejetcat** [comment]
I will do that :) and by the way, it shouldn't be criticism, I very very appreciate what is going on here!

**Comment by Saschl** [comment]
Criticism is always welcome as any feedback is. IMO it’s only important to see why something is not correct, and that’s exactly what you provided 👍

**Comment by MisterChocker** [comment]
Closing since throttle calibration is now implemented.
