### ISSUE TITLE
[BUG] Autopilot failure

### ISSUE THREAD

**Issue by dc1ps2** [flybywiresim/a32nx#2652]
**Mod Version**

Developer version: 0.5.1
Microsoft Flight Simulator:  1.12.13.0
build_info.json content:
{
  "built": "2020-12-23T08:54:29+00:00",
  "ref": "",
  "sha": "",
  "actor": "Will Pine <wpine215@gmail.com>",
  "event_name": "manual"
}

**Describe the bug**

after takeoff , turn on autopilot, then endless turn right and tilt

**To Reproduce**

1. takeoff
2. gear up
3. turn on AP
4. turn right and tilt

**References**

https://youtu.be/zjOmfyOKaww?t=2012

**Comment by kiokio0987** [comment]
Check your dead zones on your yoke, joystick.
Have you tried this?
https://github.com/flybywiresim/a32nx/releases
Common User Problems
 Autopilot sharp banking or nosediving:
 Increase your hardware deadzones to 10% or above

**Comment by AdmiralArtemiy** [comment]
On the last dev the plane rocks from left to right all the flight with the little amplitude.

**Comment by DFWSupertrooper** [comment]
> On the last dev the plane rocks from left to right all the flight with the little amplitude.

This is related to another issue reported (return of the wobbling once eliminated). #2638

**Comment by dc1ps2** [comment]
> Autopilot sharp banking or nosediving:
> Increase your hardware deadzones to 10% or above

Thanks a lot, this solution has work.
