### ISSUE TITLE
[BUG] VCRUNTIME140.dll CTD With custom liveries and A32NX

### ISSUE THREAD

**Issue by RedRun51** [flybywiresim/a32nx#2654]
**Mod Version**

Release 23-12-20

**Describe the bug**

The sim crashes within 5 minutes of reaching the main menu when custom liveries from third parties are installed (not from A32NX) with the VCRUNTIME140.dll error

**To Reproduce**

1. Install latest stable version of a32nx
2. Liveries used were KLM/Transavia from the livery megapack (but also other liveries result in this issue)
3. Load the sim and wait between 1-5 minutes

**Expected behavior**

No crash :)

**Actual behavior**

 CTD

**References**

Naam van toepassing met fout: FlightSimulator.exe, versie: 0.0.0.0, tijdstempel: 0x5fda32ba
Naam van module met fout: VCRUNTIME140.dll, versie: 14.28.29231.0, tijdstempel: 0x5f4c66c9
Uitzonderingscode: 0xc0000005
Foutmarge: 0x00000000000012de
Id van proces met fout: 0x36e8
Starttijd van toepassing met fout: 0x01d6d94b48a010be
Pad naar toepassing met fout: C:\Program Files\WindowsApps\Microsoft.FlightSimulator_1.12.13.0_x64__8wekyb3d8bbwe\FlightSimulator.exe
Pad naar module met fout: C:\Program Files\WindowsApps\Microsoft.VCLibs.140.00.UWPDesktop_14.0.29231.0_x64__8wekyb3d8bbwe\VCRUNTIME140.dll
Rapport-id: 7abd7ea4-eded-44d5-9847-fdb78a23135c
Volledige pakketnaam met fout: Microsoft.FlightSimulator_1.12.13.0_x64__8wekyb3d8bbwe
Relatieve toepassings-id van pakket met fout: App

**Additional context**

Was this working before/when did the issue start occurring?
Was working before sim and a32nx update from the last 24h

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub): RedRun#8446

**Comment by RedRun51** [comment]
Sooo..... No crash in the main menu without custom liveries, but when flying the same error appears and CTD

**Comment by Benjozork** [comment]
This is unlikely to be mod related I'm afraid

**Comment by RedRun51** [comment]
Yeah you're right, closing this issue. It has to do with the update to the sim itself it seems, did not even have this in alpha but since the VR update.... Poof, no more simming :/
