### ISSUE TITLE
[BUG] Odd A/T Behavior On/Close to Descent

### ISSUE THREAD

**Issue by DFWSupertrooper** [flybywiresim/a32nx#2655]
**Stable 0.5.1**

**Describe the bug**
When approaching TOD (perhaps when planned for descent to begin whether or not descent actually begun), A/T shifts into deceleration.  When descending, the A/T seems to bounce between idle/thrust wildly as if it cannot seem to decide upon a descent rate.

**To Reproduce**
1. Cruise with IFR flight plan active towards descent into any airport (I flew into KDEN).
2. When approaching descent observe throttle activity.
3. When cleared to begin descent by ATC, observe throttle activity.

**Expected behavior**
Relatively smooth descent maintaining planned descent speed profile.

**Actual behavior**
Volatile throttle engage/disengage every 5-7 seconds with dramatic speed and pitch changes resulting.  When engaging the speed knob instead, descent smoothed.  Thx.

**References**
N/A

**Additional context**
Also noted the wobbling left to right is somewhat back even while descending thru FL100 at 250K or less (noted in another report at CRZ).

**Was this working before/when did the issue start occurring?**
This was working prior to MSFS v1.12 update 12/22 using FBW v0.5.0.  Began after MSFS update.

**Is this a problem in the vanilla unmodded game?**
No.  Does not occur in default A320 to my knowledge (only attempted one flight after update while waiting for v0.5.1).

**Comment by A320PHX** [comment]
It happens on the dev version as well. Once I reach cruise altitude, I will take it off managed speed and it performs perfectly. You can use this as a workaround for now.

**Comment by DFWSupertrooper** [comment]
Used fixed speed to avoid managed speed...no issues using that alternative.

**Comment by donstim** [comment]
What was your cruise altitude?  Do you remember about what cost index you used?  Was there a lot of variable wind?

**Comment by DFWSupertrooper** [comment]
> What was your cruise altitude? Do you remember about what cost index you used? Was there a lot of variable wind?

Wish I could say...I don't recall.  All my flights are between FL340 and FL370 depending on the altitude S/B recommends in planning.  The last few flights I've used speed control rather than let the A/C manage so I can't report a pattern accurately.  The wind was normal (slight shifting at cruise at times, more constant on descent, speeds relatively normal and expected for weather and area at the time).

The flights it _did_ happen on, the **speed ribbon was constantly changing as well** - it wasn't just the throttle or wind.  The speed the A/C was _trying_ to maintain was changing back and forth between a slower approach speed and normal managed descent (around 289K), as if it couldn't decide every few seconds.

**Comment by donstim** [comment]
Sounds similar to this one?  #2260

**Comment by Watsi01** [comment]
@DFWSupertrooper do you have any custom liveries or other mods installed? If so, could you do me a favour and remove them and check, if this happens with the A32NX only...
The weird thing is, it doesn't occur to everyone. And you are the first one who reports this behaviour on higher crz alts.

**Comment by HurricaneTracker500** [comment]
> And you are the first one who reports this behaviour on higher crz alts.

I honestly don't think attitude has anything to do with it anymore. I really think it is an issue with the speed or mach setting, as it seems to occur when neither me or the plane switch to mach. The distance to the destination might not have any impact either as I recently had it occur pretty early on in the cruise.

**Comment by Watsi01** [comment]
Well, the problem is, the issue never happened on my plane (always latest dev). And the only thing I don't do, is flying lower crz alts (290 and below). I also switch to mach manually (if it doesn't happen automatically). BTW: with the MSFS 1.12.13.0 update you even can't switch manually between mach or speed anymore (at least when in managed mode). It's only done automatically now, on climb when reaching mach .78, on descent below FL260.

**Comment by DFWSupertrooper** [comment]
@Watsi01 I'll check ASAP using generic FBW A/C.  I also typically handle flying as you describe (all my flights CRZ is at FL340-370 depending on the FL assigned by SimBrief; I also switch to speed manually on descent only if ATC restricts speed and never switch on CLB).  

I'm flying as we speak (one of the downloaded liveries I use frequently) so I'll not switch away from managed speed on descent and see what happens and report back.  Maybe it was an isolated thing on a couple of flights for me that won't be able to be replicated...I dunno??

**Comment by DFWSupertrooper** [comment]
Completed descent into KMIA as follows (without issue using 8K EAL addon livery): CI=37, CRZ FL350, ordered descent to FL230, maintained managed speed at 287K.  Then ordered to FL130, same conditions.  Then ordered to FL030, same conditions.  Approach speed automatically began at around the correct waypoint into RNAV 09 approach.  I then activated Approach mode in the MCDU top match and setup flaps/gear for approach.  Never got a lock onto LOC but managed descent had me about 500' too high at the appropriate waypoint so that's my not accounting for the difference probably.  Switched off A/P and A/T at around 800' and landed safely.

Noted the following: knob always set to SPEED after initial descent was begun (didn't notice when it changed).  Speed tape always read MACH until some point it may/may not have changed (never noticed that - just noted the speed bug set at 287).

**Again, on this particular flight the bug did _not_ occur.**

**Comment by Watsi01** [comment]
@DFWSupertrooper Maybe it happens with low cost indexes? Above you said, you had CI 5. Now you had CI 37.

**Comment by DFWSupertrooper** [comment]
Interesting theory.  Flying right now into CYVR with CI=6 at FL360.  I'll report back after I monitor descent.

**Comment by DFWSupertrooper** [comment]
OK, so here's the scoop: again, no issue could be replicated (at least issues pertinent to this particular discussion).  Descent ordered to FL260, at which point the A/C automatically switched to SPEED mode.  Then, descent was ordered to FL140, and then down to 070.  

The approach speed automatically kicked in at around FL070 without being anywhere near the approach (in a flight plan sense) immediately dropping me down to 125K.  I engaged the speed control and held 260K until circling around to the final approach waypoint, and disengaged (returning to managed speed for the approach).  

Hit ILS 08R perfectly and landed (after recovering from the known auto-dive just above the runway).  Will report back if I encounter the error again on a future flight over the next few days and note conditions.

**Comment by DFWSupertrooper** [comment]
Happened again today for the first time in a while.  Speed bug kept changing back and forth from 240 to 280 (or whatever the managed descent speed was) on the way into KDEN.  About the middle of descent just prior to the DECEL point.  I believe the CI was 14 or something similar (don't recall exactly).  The best workaround seems to be suing the speed control instead of managed as soon as possible.

**Comment by DFWSupertrooper** [comment]
On descent into MNMG and the issue returned.  Was descending at the planned 287K and then around F230 on the way to F210, the speed bug dropped to 240.  I added speed brake to decelerate and then after a few seconds the bug instantly jumped back to 287K.  I switched to speed control at 250K from thereon.

**Comment by Watsi01** [comment]
We've made several changes, which could(!!) fix this issue. Please try the latest dev version.

**Comment by DFWSupertrooper** [comment]
> We've made several changes, which could(!!) fix this issue. Please try the latest dev version.

OK, thanks.  Using the one from this morning currently.  Will let you know.  If I see it again, I'll download again tonight just to make sure I'm using the most recent version since the last flight.  Thx.

**Comment by DFWSupertrooper** [comment]
It's doing it again on my descent into LEIB.  Bug jumps back and forth from 210K to 250K on initial descent from F370 to F320.  Engines roar and then idle, roar and then idle every 20 seconds or so.  Pitch also changes to match.

**Comment by Watsi01** [comment]
This is really strange. The last days, I did several descends with full managed speed and open descend to get your issue. Never had it.
We have one or two fixes in the next days which (also) could fix your issue. 
Where's the shared cockpit if you need it. Would like to make a flight with you to see what's happening.

**Comment by DFWSupertrooper** [comment]
Yeah right...I only get it on every third flight or so.  I'll redownload the dev version again in a few and try later _just in case_ I happened to get the _last_ version before the fix.  If I can get four flights on non-restricted speed descent without it appearing at all, I'll consider it solved.  It's like the computer can't decide the proper speed to maintain.  Weather seems to be irrelevant.

**Comment by DFWSupertrooper** [comment]
So, I'm thinking #2864 may be related.  Flying into KIAD tonight and the bug was shifting b/w 280K and 285K (give or take).  Throttle was changing with it.  Happened around GYSLO on the way into GYBBS4 arrival before TAC cleared my descent by a few minutes but where you might imagine descent in progress IRL.

**Comment by Watsi01** [comment]
What I see in this video is that the baro is not set to STD. That's the only difference I see. And it is interesting, that he saw the crz speed fluctuating on the CRZ PERF page. 

With a cost index of 30, a crz speed of 210 or 170 is impossible, regarding the calculation which is done in the code. So it can't be the crz speed calculation itself. There must be an interference with any other "speed rule" in the deep code of the mcdu somewhere. Or with any mod, livery or whatever...

Another question (just digging in the dark). What range of FLX temp do you use normaly for takeoff?

**Comment by DFWSupertrooper** [comment]
Maybe his issue is not related.  I don't generally have a problem at CRZ, except in the instance above when I was close to descent (close to by ATC's definition, maybe I should've been descending already by the A/C definition in the FPL).  

At any rate, considering I may be doing something wrong, let me ask...when you descend upon ATC instruction, do you _pull_ the knob to engage OP DES, or do you _push_ the knob to engage DES?  I've been doing the former almost exclusively.  Never had any issues until the last MSFS update which we all know changed the base A320.

**Comment by Watsi01** [comment]
I made a fix for the #2864 issue. It is pretty clear there, what's the problem. Maybe (mayyyybeeee) that's fixing your issue too. Since it seems to be a conflict between flightphase speeds and any other "speed rule".

**Comment by Watsi01** [comment]
@DFWSupertrooper I hardly fly with managed alt. CLB, CRZ and DES. I always pull the knob to open des.

**Comment by DFWSupertrooper** [comment]
Me too (OP DES).  Was just happening again on descent into LEBL as I switched to OP DES (wasn't occurring on DES).  Once it's avail I'll redownload the new version and test a few flights.

**Comment by DFWSupertrooper** [comment]
@Watsi01 so far so good.  Two beautiful descents as expected w/o issue on speed flopping (still drops to decel too early in many approaches IMHO but that's a separate issue).  I'll fly a few more tomorrow to make sure.  Beautiful work my friend.

**Comment by Watsi01** [comment]
250 is the below 10000ft restriction, which the plane is fighting with, I assume. I (test)flew my own PR for several flights so far. Again, didn't experience your issue. Managed descent means you pushed the alt knob?

**Comment by DFWSupertrooper** [comment]
Sorry, I pulled.  Not managed...OP DES.
