### ISSUE TITLE
Speeds in CRZ are wrong

### ISSUE THREAD

**Issue by Captherky** [flybywiresim/a32nx#2660]
at cruise alt, fl320, mach is set at .72, it overspeeds .
Then se mach .42 and no speed change.

**Mod Version**
master

<{
  "built": "2020-12-23T08:54:29+00:00",
  "ref": "",
  "sha": "",
  "actor": "Will Pine <wpine215@gmail.com>",
  "event_name": "manual"
}

**Describe the bug**
go to cruise alt, it overspeeds. Then need to select .42 to get out of overspeed.
The FBW speed is not connected to the aircraft.
PLUS all the SimBrief waypoints SID and STARs are lost after reaching climb. The FMC is only populated with Origin and destination!

**To Reproduce**

1.climb to fl320
2.encounter overspeed
3.reduce speed in speed commanded mode. no effect on speed

**Expected behavior**
we should have no overspeed at m.73 at fl330

**Actual behavior**overspeed at m.73 at fl330
**References**

**Additional context**

Was this working before/when did the issue start occurring?
after 12.13 mod upgrade by Arsobo

Is this a problem in the vanilla unmodded game?
yes

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by donstim** [comment]
You are correct, the airplane should not have an overspeed warning at M0.73 at FL330. Was the speed at M0.73 at FL330, or did it start out at M0.73, but then speed up until the overspeed warning started? The only way I could reproduce this was to put my thrust levers in TOGA and wait until it accelerated to the overspeed warning speed. With the thrust levers in the TOGA position, they are out of the autothrust position and thrust will not respond to changes in the commanded speed.

**Comment by MisterChocker** [comment]
@Captherky could you please respond to the above question asked?

**Comment by Captherky** [comment]
Since updating to the latest FBW Release version, there is absolutely no issue with the Neo! Thanks!

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by MisterChocker** [comment]
Great! issue solved, closing.
