### ISSUE TITLE
[BUG] A. FLOOR triggered in normal flight, followed by complete lack of control response, until crash

### ISSUE THREAD

**Issue by scelts** [flybywiresim/a32nx#2661]
**Mod Version**
Latest Development version

**Describe the bug**
On approach, going at 200+ kt, I extend the spoilers to full to slow down to flaps 2 extend speed. As the plane slows down alpha floor is triggered at around 200kt (nowhere near to stall), TO/GA activated, the plane overspeeds in a second, rolls sharply to the left, and becomes completely uncontrollable to any control inputs. Autopilot is off.

**To Reproduce**
It happened once for me.
1. Normal approach, autopilot following GS vertically, no icing, no damage activated, gear up, Flaps 1 extended, close to upper speed limit
2. Spoilers max

**Expected behavior**
It should not trigger the alpha floor, and definitely not become uncontrollable even after the autopilot is disconnected

**Actual behavior**
Opposite from expected.

Was this working before/when did the issue start occurring?
Newest MSFS version

Is this a problem in the vanilla unmodded game?
No, I have mods. 

Discord username (if different from GitHub):
celt#0516

**Comment by Tibu73-ui** [comment]
Same bug for me. Airplane dives until cash.
Also I had a CTD in one test.

**Comment by Tibu73-ui** [comment]
Same issue un last dev and stable 0.6 versions.

**Comment by Benjozork** [comment]
There is no 0.6 version.

**Comment by Tibu73-ui** [comment]
Sorry 0.5.1 versión.
The airplane lose control and dive until cash ramdomly on departure on
cruise on aproach

**Comment by Tibu73-ui** [comment]
I'm gonna do a third test without charging the Fpln from simbrief.

**Comment by donstim** [comment]
I tried to reproduce this using the steps listed, but could not. There must be something else going on as well.  Do you have any other mods installed?

How were you managing speed and thrust? What was your weight?

Not necessarily connected with what you experienced, but I suggest managing the approach differently next time. You should not be over 200 knots in CONF 1 on the glideslope. Try to follow this technique:
![Screenshot (316)](https://user-images.githubusercontent.com/70166617/103037386-92da9280-4520-11eb-9153-a06e5fc802db.png)

**Comment by Tibu73-ui** [comment]
I managed the speed manually cause I had a constraint speed 220 kts  5 miles before Decel point. 
I can't reach the LOC cause the aircraft loose the control and crash.

**Comment by Tibu73-ui** [comment]
I was in flaps conf 2 with mcdu managed speed.
I supossed at 160 / 170 kts. Still Not on final waiting for LOC.

**Comment by Tibu73-ui** [comment]
No other add ons installed,  A/THR mode at 160 kts, 2 miles to LOC signal.

**Comment by scelts** [comment]
> Not necessarily connected with what you experienced, but I suggest managing the approach differently next time. You should not be over 200 knots in CONF 1 on the glideslope. Try to follow this technique, keeping the speed on managed and the thrust levers in the CLB detent (reducing to idle at about 20-25 feet after flaring at 20-30 feet):

the weight was usual, I know how to do the approach, and the graph you put has absolutely nothing with this bug, so I don't get the comment.
everything was within normal limits. plane is slowing down, I switch to flaps 1 at the speed where you should. in this moment I intercept the glideslope a bit higher than planned, the plane starts following it, so it's not slowing down enough to my liking. I pull out the speed brakes, to slow down to flaps 2 speed to continue normally the approach, the plane first executes toga and then kamikaze to the left.

**Comment by Tibu73-ui** [comment]
> > Not necessarily connected with what you experienced, but I suggest managing the approach differently next time. You should not be over 200 knots in CONF 1 on the glideslope. Try to follow this technique, keeping the speed on managed and the thrust levers in the CLB detent (reducing to idle at about 20-25 feet after flaring at 20-30 feet):
> 
> the weight was usual, I know how to do the approach, and the graph you put has absolutely nothing with this bug, so I don't get the comment.
> everything was within normal limits. plane is slowing down, I switch to flaps 1 at the speed where you should. in this moment I intercept the glideslope a bit higher than planned, the plane starts following it, so it's not slowing down enough to my liking. I pull out the speed brakes, to slow down to flaps 2 speed to continue normally the approach, the plane first executes toga and then kamikaze to the left.

Exactly, we have thousand of hours fliying this bird, I had the same issue twice in different phases of the same flight.
Importing the FLPLN from simbrief via MCDU.

**Comment by scelts** [comment]
flightplan was imported from simbrief for me too. I didn't think it was relevant.

**Comment by Tibu73-ui** [comment]
I´m gonna test one more time writting the waypoints/airways manually in the MCDU as ussually I do.

**Comment by Tibu73-ui** [comment]
> flightplan was imported from simbrief for me too. I didn't think it was relevant.

Yeah, I think the same, but only for testing and clarify my doubts about it

**Comment by donstim** [comment]
Interesting. I wonder if  there is some funny constraint in the simbrief flight plan that is contributing. If you can reproduce this at will, can you provide a video?  I have done literally hundreds of approaches and have never encountered something like this.

Sorry @scelts , the comment I made about managing the approach should have been directed to @Tibu73-ui who described being faster than 200 knots in CONF 1 on the glideslope. Unless glideslope is being captured pretty high, that seems to be setting oneself up for an unstable approach.

**Comment by Tibu73-ui** [comment]
I've tried the same flight LEMD / LEPA without charging simbrief via MCDU. I did a direct (HDG mode) for capture ILS in a confortably 35 degree angle and step transition ADX. No bugs this time on final, but the same bug on descent phase than the past flight.
Speed increases and decreases with no sense. ( I recorded a video with the bug but I can't attach it cause is bigger than 10 MB)

@donstim I made thousands of flights with the a320. A lot of years since FS2004 /FSX P3D and X Plane 11. with the most popular payware add ons and I know what is the correct procedures for approach for this airliner and others.
I never tell I caputured a glideslope at 200 kts. Normally I capture LOC in CONF1 or 2 and perform the GS with Flaps full and gear down with the correct speeds.
I only try to report a possible bug in 0.5.1 FBW version after the last MSFS 2020 update.

**Comment by donstim** [comment]
> I've tried the same flight LEMD / LEPA without charging simbrief via MCDU. I did a direct (HDG mode) for capture ILS in a confortably 35 degree angle and step transition ADX. No bugs this time on final, but the same bug on descent phase than the past flight.
> Speed increases and decreases with no sense. ( I recorded a video with the bug but I can't attach it cause is bigger than 10 MB)
> 
> @donstim I made thousands of flights with the a320. A lot of years since FS2004 /FSX P3D and X Plane 11. with the most popular payware add ons and I know what are the correct procedures for approach for this airliner and others.
> I never tell I caputured a glideslope at 200 kts. Normally I capture LOC in CONF1 or 2 and perform the GS with Flaps full and gear down with the correct speeds.
> I only try to report a possible bug in 0.5.1 FBW version after the last MSFS 2020 update.

Well, then maybe you would like to correct your bug report -- "Normal approach, autopilot following GS vertically, no icing, no damage activated, gear up, Flaps 1 extended, close to upper speed limit" 

It is difficult enough to try to track these things down without having the correct information to start with...

**Comment by Tibu73-ui** [comment]
> > I've tried the same flight LEMD / LEPA without charging simbrief via MCDU. I did a direct (HDG mode) for capture ILS in a confortably 35 degree angle and step transition ADX. No bugs this time on final, but the same bug on descent phase than the past flight.
> > Speed increases and decreases with no sense. ( I recorded a video with the bug but I can't attach it cause is bigger than 10 MB)
> > @donstim I made thousands of flights with the a320. A lot of years since FS2004 /FSX P3D and X Plane 11. with the most popular payware add ons and I know what are the correct procedures for approach for this airliner and others.
> > I never tell I caputured a glideslope at 200 kts. Normally I capture LOC in CONF1 or 2 and perform the GS with Flaps full and gear down with the correct speeds.
> > I only try to report a possible bug in 0.5.1 FBW version after the last MSFS 2020 update.
> 
> Well, then maybe you would like to correct your bug report -- "On approach, going at 200+ kt, I extend the spoilers to full to slow down to flaps 2 extend speed. ...Normal approach, autopilot following GS vertically, no icing, no damage activated, gear up, Flaps 1 extended, close to upper speed limit"
> 
> It is difficult enough to try to track these things down without having the correct information to start with...
> 
> Maybe you can put your video on the cloud somewhere where you can share it?

Ok, I will try to explain it with more details:
First crash:
Departure from cold and dark at LEMD RWY 18R.
Take off with flaps 1. FLEX TO 41 °
Rotate normaly at 131 knots.
Positive climb,  gear up,  at 3500ft i set the levers to Climb thrust position but FD doesnt track correctly the pitch bit aircraft response to climb.  At 4500ft after flaps up aircraft actives AFloor and pitch nose down and dive untill crash..
Second crash:
Same flight than before LEMD/LEPA 
same problem with FD pitch on inicial climb on thrust reduction after Take of but aircraft climb normally to Cruise at FL320.
Start descend 100 miles from airport. But speed went down and up and I decide to set manually descent speed at 270 knots .
Manually set 250 kts at 11.000 ft , I reached the Decel point at 220 kts / 7000 ft . Once Aproach phase was activated I leave mcdu manage the speed for aproach . Reached the transition aproach ADX at green dot,  flaps 1. Actívate ILS and set LOC to intercept  the localizer. Speed 180 kts, 90 degrees angle for LOC alignement.
LOC 3 or 4 miles ahead. In this moment aircraft pitches down and dive into  the sea.

**Comment by sidnov** [comment]
Had this issue today on my flight to VILH. Plane nosedived at about 210kts, Flaps 1 and spoilers armed for approach.

**Comment by donstim** [comment]
Thank  you everyone for providing more information. One more question:  Is anyone who's experiencing this issue had it occur with any flap setting **different** than 1?

**Comment by donstim** [comment]
> Ok, I will try to explain it with more details:
> First crash:
> Departure from cold and dark at LEMD RWY 18R.
> Take off with flaps 1. FLEX TO 41 °
> Rotate normaly at 131 knots.
> Positive climb, gear up, at 3500ft i set the levers to Climb thrust position but FD doesnt track correctly the pitch bit aircraft response to climb. At 4500ft after flaps up aircraft actives AFloor and pitch nose down and dive untill crash..
> Second crash:
> Same flight than before LEMD/LEPA
> same problem with FD pitch on inicial climb on thrust reduction after Take of but aircraft climb normally to Cruise at FL320.
> Start descend 100 miles from airport. But speed went down and up and I decide to set manually descent speed at 270 knots .
> Manually set 250 kts at 11.000 ft , I reached the Decel point at 220 kts / 7000 ft . Once Aproach phase was activated I leave mcdu manage the speed for aproach . Reached the transition aproach ADX at green dot, flaps 1. Actívate ILS and set LOC to intercept the localizer. Speed 180 kts, 90 degrees angle for LOC alignement.
> LOC 3 or 4 miles ahead. In this moment aircraft pitches down and dive into the sea.

Okay, I am trying to recreate your flights, one at a time. For the first one, if your rotation speed was 131 knots, then your weight must have been around 63.5 T. Does that sound correct? Did you engage the autopilot, and if so, at what height?, What values are in the MCDU take off page for TRH RED/ACC? Were you using managed or selected speed mode, and if selected, what speed? At what speed did you retract the flaps? Without such specific information, or a video, I cannot re-create your flight. I have tried it a few times, engaging the autopilot at around 200 ft and retracting flaps at S speed and have not experienced any issues.

**Comment by Tibu73-ui** [comment]
> > Ok, I will try to explain it with more details:
> > First crash:
> > Departure from cold and dark at LEMD RWY 18R.
> > Take off with flaps 1. FLEX TO 41 °
> > Rotate normaly at 131 knots.
> > Positive climb, gear up, at 3500ft i set the levers to Climb thrust position but FD doesnt track correctly the pitch bit aircraft response to climb. At 4500ft after flaps up aircraft actives AFloor and pitch nose down and dive untill crash..
> > Second crash:
> > Same flight than before LEMD/LEPA
> > same problem with FD pitch on inicial climb on thrust reduction after Take of but aircraft climb normally to Cruise at FL320.
> > Start descend 100 miles from airport. But speed went down and up and I decide to set manually descent speed at 270 knots .
> > Manually set 250 kts at 11.000 ft , I reached the Decel point at 220 kts / 7000 ft . Once Aproach phase was activated I leave mcdu manage the speed for aproach . Reached the transition aproach ADX at green dot, flaps 1. Actívate ILS and set LOC to intercept the localizer. Speed 180 kts, 90 degrees angle for LOC alignement.
> > LOC 3 or 4 miles ahead. In this moment aircraft pitches down and dive into the sea.
> 
> Okay, I am trying to recreate your flights, one at a time. For the first one, if your rotation speed was 131 knots, then your weight must have been around 63.5 T. Does that sound correct? Did you engage the autopilot, and if so, at what height? What was your initial climb altitude, and did you use open climb, managed climb, or V/S mode? Were you using managed or selected speed mode, and if selected, what speed? At what speed did you retract the flaps? Sorry for the 100 questions, but without such specific information, or a video, I cannot re-create your flight. I have tried it a few times, engaging the autopilot at around 200-300 ft, using managed speed, open climb to 8000 feet and retracting flaps at S speed and have not experienced any issues. I've attached a link to a video of this: https://1drv.ms/v/s!Ajsy7Ey4_8uFyBrHVr1ZCv418U7-?e=7OusMI
> 
> I would really like to track this down, but I need your help..

Ok, todas I can't reproduce the flight cause I have the dinero with my family and my son is in the sim watching bears with the Cesna172 😉.
Tomorrow I will try to reproduce again the last LEMD/LEPA flight.  I hace the briefing drom last simbrief flight. I think the TOW is correct around 63.5 Tons. 
Remember I was a foggy morning at LEMD and I flew manually untill 3500 ft / THR ACEL and then engage the AP. But sincerely I don't remember the details. I was in flaps conf 1 until reach S speed.
I did the flight with last 0.5.1 stable version. No other mods installed.

**Comment by Tibu73-ui** [comment]
Sorry for Faulty words I have my corrector in spanish.

**Comment by donstim** [comment]
> Sorry for Faulty words I have my corrector in spanish.

No problem. I understand. Watching bears in the sim is good!

**Comment by Tibu73-ui** [comment]
> > > Ok, I will try to explain it with more details:
> > > First crash:
> > > Departure from cold and dark at LEMD RWY 18R.
> > > Take off with flaps 1. FLEX TO 41 °
> > > Rotate normaly at 131 knots.
> > > Positive climb, gear up, at 3500ft i set the levers to Climb thrust position but FD doesnt track correctly the pitch bit aircraft response to climb. At 4500ft after flaps up aircraft actives AFloor and pitch nose down and dive untill crash..
> > > Second crash:
> > > Same flight than before LEMD/LEPA
> > > same problem with FD pitch on inicial climb on thrust reduction after Take of but aircraft climb normally to Cruise at FL320.
> > > Start descend 100 miles from airport. But speed went down and up and I decide to set manually descent speed at 270 knots .
> > > Manually set 250 kts at 11.000 ft , I reached the Decel point at 220 kts / 7000 ft . Once Aproach phase was activated I leave mcdu manage the speed for aproach . Reached the transition aproach ADX at green dot, flaps 1. Actívate ILS and set LOC to intercept the localizer. Speed 180 kts, 90 degrees angle for LOC alignement.
> > > LOC 3 or 4 miles ahead. In this moment aircraft pitches down and dive into the sea.
> > 
> > 
> > Okay, I am trying to recreate your flights, one at a time. For the first one, if your rotation speed was 131 knots, then your weight must have been around 63.5 T. Does that sound correct? Did you engage the autopilot, and if so, at what height? What was your initial climb altitude, and did you use open climb, managed climb, or V/S mode? Were you using managed or selected speed mode, and if selected, what speed? At what speed did you retract the flaps? Sorry for the 100 questions, but without such specific information, or a video, I cannot re-create your flight. I have tried it a few times, engaging the autopilot at around 200-300 ft, using managed speed, open climb to 8000 feet and retracting flaps at S speed and have not experienced any issues. I've attached a link to a video of this: https://1drv.ms/v/s!Ajsy7Ey4_8uFyBrHVr1ZCv418U7-?e=7OusMI
> > I would really like to track this down, but I need your help..
> 
> Ok, today I can't reproduce the flight cause I have the dinner with my family and my son is in the sim watching bears with the Cesna172 😉.
> Tomorrow I will try to reproduce again the last LEMD/LEPA flight. I have the briefing from last simbrief flight. I think the TOW is correct around 63.5 Tons.
> Remember I was a foggy morning at LEMD and I flew manually untill 3500 ft / THR ACEL and then engage the AP. But sincerely I don't remember the details. I was in flaps conf 1 until reach S speed.
> I did the flight with last 0.5.1 stable version. No other mods installed.
For 2nd flight test ( crash after pass aproach star trans waypoint ADX):
I managed initial climb in OP CLB to 8000 ft  to avoid altitud constraints. Managed speed by FMC until cruise. Start descent around 100 miles to LEPA. Managed des speed was changing up and down a d I decided set manually at 270 kts until FL110 , then set 250 kts,  reached decel point at 210 kts 5 miles before ADX, set manage MCDU speed for app phase and reaching green dot 5 miles after ADX set flaps 1, then the aircraft nosedived and crash.

**Comment by donstim** [comment]
Okay. I can't re-create your takeoff issue, but I have another similar one that I have been able to duplicate. I now have a fix for that, but don't know if it will work for the approach one. Going to try to do that now based on your additional info. thanks.

**Comment by Tibu73-ui** [comment]
> Okay. I can't re-create your takeoff issue, but I have another similar one that I have been able to duplicate. I now have a fix for that, but don't know if it will work for the approach one. Going to try to do that now based on your additional info. thanks.
> 
> Is there any chance you could have inadvertently selected flaps 2, then went back to flaps 1 when you first selected flaps 1? that is the only way I can get the airplane to nosedive,and it is for the same reason that it nosedives sometimes after takeoff with flaps 1 (and I can fix that).

Is the hotfix in the last dev master version? Now I have some time to test it.

**Comment by donstim** [comment]
It's not in the dev version yet. Still needs to go through the QA process. If you have a Github account, you can download the test version here:  https://github.com/flybywiresim/a32nx/pull/2698

**Comment by Tibu73-ui** [comment]
> It's not in the dev version yet. Still needs to go through the QA process. If you have a Github account, you can download the test version here: #2698

Ok, I'm doing a test with last dev version  yo test new features  like winds aloft in FMC. 
Fliying LEMD / LFPO 
No issues at takeoff, Climb and cruise phases at the moment. 
Lets see on approach. 
By the way,  thaks a lot for your constantly work on A32X. Its really amazing what are you doing.
Best Regards.

**Comment by Tibu73-ui** [comment]
> It's not in the dev version yet. Still needs to go through the QA process. If you have a Github account, you can download the test version here: #2698

Ok this time I had no divenose issues with last dev version but still speed incresases and decreases at descent fron 280 to 220 kts more or less. Magenta speed triangle goes up and down  and I have to manage speed manually. until Decel point.
Never I tested a QR .Maybe I will try tomorrow. I have a github account.
Thanks again to entire FBW team of testers and programers. You are doing the best !

**Comment by CptPaffs** [comment]
Hi Team, just wanted to confirm that issue. I have no clue where that comes from. I have NO other mods; just the A32NX (btw thanks a lot for that amazing work). As soon as I start my approach: reducing speed to 220kts; setting flaps 1; (I have my MCDU programmed for approach) couple of seconds later FD starts going crazy and the plane goes down; completely no control; switching off the A/P doesn't help; completely no control. I'm flying in Poland - that happened to me on two default airports (EPWA and EPGD - haven't done tests on other airports yet) regardless which runway i pick which approach i pick; all the same..I'm crying..before the latest MS patch everything was brilliant. Fingers crossed you can fix that bug. In case of questions let me know; I'll do my best to support. Cheers!

**Comment by TheoBearman** [comment]
Hi team - can also confirm this issue.

**Comment by donstim** [comment]
There is a fix in work. Until then keep speed below 210 knots in with flaps 1.

**Comment by CptPaffs** [comment]
> There is a fix in work. Until then keep speed below 210 knots in with flaps 1.

Thanks so much! First attempt worked. Fingers crossed for the fix.

**Comment by depthvader** [comment]
Thanks for getting on this, it has been driving me crazy the past couple of days. Great work on the 32NX it's awesome!
