### ISSUE TITLE
ND ARC range issue after sim update

### ISSUE THREAD

**Issue by frenchPilot75** [flybywiresim/a32nx#2664]
dev
**Mod Version**

v05.01

**Describe the bug**

ND arc range is not moving up and down when CSTR button is on

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Highflyer2010** [comment]
it would help if you filled the form out properly and step by step instructions

**Comment by Benjozork** [comment]
> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning
