### ISSUE TITLE
[BUG] Aural TAWS alerts on takeoff with positive climb rate and gear up

### ISSUE THREAD

**Issue by B-KC** [flybywiresim/a32nx#2666]
**Mod Version**

0.5.1

**Describe the bug**

After landing, taxing back and taking off again. TAWS alerts go off after positive rate and gear up. 

**To Reproduce**

1. Land at any airport and take off again. Select Gear Up.
2.
3.

**Expected behavior**

When you take off with a positive rate as you would during an initial flight, you should not be getting Aural TAWS alerts for terrain.

**Actual behavior**

When you select gear up after take off you get TAWS alerts no matter the airport or surrounding terrain. Even with a positive rate of climb.

**References**

**Additional context**

Was this working before/when did the issue start occurring? Unknown

Is this a problem in the vanilla unmodded game? No. Vanilla A320 doesn't give this alert after landing and taking off again. 

Discord username (if different from GitHub):

**Comment by hotshotp** [comment]
yeah go arounds arent implemented fully yet, especially for the TAWS system, we will need to fix that at some point

**Comment by sidnov** [comment]
This issue is fixed from the time when flightphases were implemented
