### ISSUE TITLE
[BUG] Speed Brake doesn't slow like it should while in flight

### ISSUE THREAD

**Issue by B-KC** [flybywiresim/a32nx#2667]
**Mod Version**
 

0.5.1

**Describe the bug**

While on decent and you throw up 100% speed brakes to slow down, the rate by which you slow down seems off. 

**To Reproduce**

1. Fly at a level altitude and throw up 100% speed brakes or fly a decent and throw up 100% speed brakes.
2.
3.

**Expected behavior**

I would expect to see a massive slow down and rapid decrease in airspeed, but it almost has no effect at times. 

**Actual behavior**

Speed brakes appear to be slowing the plane very little at 100%

**References**

**Additional context**

Was this working before/when did the issue start occurring? Unknown. 

Is this a problem in the vanilla unmodded game? No. Speed brakes work as I would expect on the vanilla A320. When flying level and throwing up speedbrakes, the engines spool up to compensate, or if you reduce thrust to idle a significant airspeed reduction is observed. 

Discord username (if different from GitHub): N/A

**Comment by Benjozork** [comment]
No IRL references provided.

Please provide evidence for the flight model being wrong. Are you an IRL A320 pilot ?

**Comment by B-KC** [comment]
> No IRL references provided.
> 
> Please provide evidence for the flight model being wrong. Are you an IRL A320 pilot ?

No I’m not a pilot, but it’s obvious there is a problem with the mod when simply compared to the vanilla version provided out of the box.

It’s illogical for the plane to not slow and the engines not to spool up when speed brakes are fully deployed. 

Here is a great reference however from a real pilot that flew the airbus. https://youtu.be/O22eHzc8yl0

**Comment by MisterChocker** [comment]
@B-KC the vanilla flight model is far off from real life. The current effect of speed brakes is reflecting real life performance.

**Comment by Benjozork** [comment]
> No I’m not a pilot, but it’s obvious there is a problem with the mod when simply compared to the vanilla version provided out of the box.

The modded flight model has been verified by more than 10 IRL A320 pilots who work with us closely, providing reviews and suggested tweaks.

**Comment by B-KC** [comment]
> > No I’m not a pilot, but it’s obvious there is a problem with the mod when simply compared to the vanilla version provided out of the box.
> 
> The modded flight model has been verified by more than 10 IRL A320 pilots who work with us closely, providing reviews and suggested tweaks.

That may be so, but I’d love for one of them to explain to me how in level flight or even on approach and spoilers fully deployed the aircraft neither pitches down, slows down, or the engines spool up to compensate for significant drag.

https://youtu.be/r_8wl_cY4SY

**Comment by hotshotp** [comment]
our flight model has been confirmed realistic by many a320neo pilots.
