### ISSUE TITLE
[BUG] CTD when loading aircraft after msfs update today

### ISSUE THREAD

**Issue by buggieone** [flybywiresim/a32nx#2671]
**Mod Version**

  "built": "2020-12-20T02:32:50+00:00",
  "ref": "",
  "sha": "",
  "actor": "pareil6 <73158172+pareil6@users.noreply.github.com>",
  "event_name": "manual"

**Describe the bug**

CTD when loading aircraft after msfs update today, other aircraft load fine.

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by SoaringHills** [comment]
Same thing has happened to me. Unusable. 

When I copy and paste into the community file, choose A320Neo, load, I then get a CTD before the loading sequence has completed. 

I have the newest version of MSFS.

**Comment by Benjozork** [comment]
Your build is outdated, and doesn't work with the newest version of MSFS.

Please update to 0.5.1 or the development version. Thanks.
