### ISSUE TITLE
[BUG] WINDOW WIPERS WONT STOP MOVING

### ISSUE THREAD

**Issue by FlightSimCheck** [flybywiresim/a32nx#2673]
**Mod Version**

**Describe the bug**
 As soon as I give the aircraft power the window wipers start moving I have no option to move the knobs that turn them on and off

**To Reproduce**

1. I simply installed the new update, started up msfs and it started
2.
3.

**Expected behavior**

**Actual behavior**
 The window wipers won’t turn off

**References**

**Additional context**

Was this working before/when did the issue start occurring? Straight after the latest update

Is this a problem in the vanilla unmodded game?

 FlightSimCheck#5141
Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by hotshotp** [comment]
delete yourcontrols, this is an issue that is caused by it

**Comment by Benjozork** [comment]
No response
