### ISSUE TITLE
[BUG] Log Book Not Logging Properly

### ISSUE THREAD

**Issue by doolok** [flybywiresim/a32nx#2674]
Log book logs departure/arrival airport as same place, logs no info on time.

**Mod Version**

{
  "built": "2020-12-23T23:38:26+00:00",
  "ref": "",
  "sha": "",
  "actor": "DerL30N <leon.beeser@yahoo.de>",
  "event_name": "manual"
}

**Describe the bug**

When arriving at a gate, I shut my engines off, and the game then recognizes the flight is complete. When I exit and go to my profile to view the log book, the time flew is 0:00 and the departure/arrival airports are the same.

**To Reproduce**

1. Plan a route, start at a gate cold and dark
2. Fly the route, Land and taxi to gate
3. Shut engines off, then fuel pumps, then exit. View log book

**Expected behavior**

I expect the log books to accurately log flight time with the mod

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Only happens when I fly the A320 mod.

Is this a problem in the vanilla unmodded game?
no, the stock unmodded planes work just fine.

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
Are you in devmode ?

**Comment by doolok** [comment]
negative.

**Comment by doolok** [comment]
![20201223192751_1](https://user-images.githubusercontent.com/73206287/103051835-524d3a00-455d-11eb-8119-efd37864e032.jpg)

notice when the A320 is flown, its very buggy. The departure airport is wrong, and there is zero flight times. its logging it as 0 with the same departure airport as the arrival.

**Comment by Watsi01** [comment]
This isn't a A32NX issue. It's a general thing with the msfs logbook. Especially when you click "continue" at the end of a flight to shut down the plane proberly.

**Comment by Tibu73-ui** [comment]
> Log book logs departure/arrival airport as same place, logs no info on time.
> 
> **Mod Version**
> 
> {
> "built": "2020-12-23T23:38:26+00:00",
> "ref": "",
> "sha": "",
> "actor": "DerL30N [leon.beeser@yahoo.de](mailto:leon.beeser@yahoo.de)",
> "event_name": "manual"
> }
> 
> **Describe the bug**
> 
> When arriving at a gate, I shut my engines off, and the game then recognizes the flight is complete. When I exit and go to my profile to view the log book, the time flew is 0:00 and the departure/arrival airports are the same.
> 
> **To Reproduce**
> 
> 1. Plan a route, start at a gate cold and dark
> 2. Fly the route, Land and taxi to gate
> 3. Shut engines off, then fuel pumps, then exit. View log book
> 
> **Expected behavior**
> 
> I expect the log books to accurately log flight time with the mod
> 
> **Actual behavior**
> 
> **References**
> 
> **Additional context**
> 
> Was this working before/when did the issue start occurring?
> Only happens when I fly the A320 mod.
> 
> Is this a problem in the vanilla unmodded game?
> no, the stock unmodded planes work just fine.
> 
> Discord username (if different from GitHub):
> 
> **BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

I had this bug before 22/12 update

**Comment by Tibu73-ui** [comment]
When shut down engines at the arrival gate apeas a los screen showing the entire flight with the options to reinicialize flight,  end flight and continue flight.
If select end flight the sim grab the log, if select continue for complet shut down the aircraft the son doesnt grab the flight.

**Comment by doolok** [comment]
I'm asking the FBW guys to look because, as you can tell from the screeshots, it doesnt appear to happen with the other GA stock aircraft, and when I specifically fly the FBW A320, its not working.

**Comment by TheStraing** [comment]
I have this problem too with the latest development build... when I'm able to make the log screen to show up... because most of the times when I shut down the engines (and the screens turn off) all of the lights remain on, the ATC still works and the log screen doesn't get displayed.

**Comment by hotshotp** [comment]
not a bug - the new asobo update made it so your flight hours dont track with development mode on in your msfs settings

**Comment by doolok** [comment]
again, I'm not using dev mode. I've stated this several times.

**Comment by doolok** [comment]
> not a bug - the new asobo update made it so your flight hours dont track with development mode on in your msfs settings

see previous. As stated several times, I dont have dev mode enabled, nor do I use it. This isnt because of that.

**Comment by hotshotp** [comment]
> > not a bug - the new asobo update made it so your flight hours dont track with development mode on in your msfs settings
> 
> see previous. As stated several times, I dont have dev mode enabled, nor do I use it. This isnt because of that.

i apologize, didnt read through the entire post

**Comment by 2hwk** [comment]
This could also be related to liveries. Also need to check if any of the sim updates since this issue was posted have fixed the issue.

**Comment by MisterChocker** [comment]
Closing since no response from op.
