### ISSUE TITLE
ECAM displays turn off when the APU master switch is pressed

### ISSUE THREAD

**Issue by larrydingus** [flybywiresim/a32nx#268]
ECAM displays turn off when the APU master switch is pressed and I am unable to switch to another display, it is stuck on the APU page but with the screens off. After about a minute or two the displays come back on and work as normal. Changing the brightness does not do anything when the screens turn off.

Edit: seems to only happen when spawning in with plane already running

**Comment by NathanInnes** [comment]
Unable to replicate.

**Comment by larrydingus** [comment]
> Unable to replicate.

Seems to only happen when I start with the plane already running on the runway. I tried doing it cold and dark and it worked perfectly fine.

**Comment by AdenFlorian** [comment]
this was fixed according to #357
