### ISSUE TITLE
[BUG] PULL STD Decal Fault 

### ISSUE THREAD

**Issue by johnwillimas** [flybywiresim/a32nx#2688]
**Mod Version**
 MASTER
2020-11-13T08:39:46+00:00

**Describe the bug**

The "PULL STD" text appear twice on the button. ? Related to #2687 is this the illuminated part vs the button label????

**To Reproduce**

1. Load 32NX
2. Observe PULL STD button
3. 

**Expected behavior**

Text should appear once

**Actual behavior**

Text is overlapped with another PULL STD text at an angle (see image).

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Don't know. Only just noticed.

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):
![pull std](https://user-images.githubusercontent.com/38857762/103087286-db588580-45de-11eb-9723-c67ef070ad2e.png)

**Comment by johnwillimas** [comment]
Similar problem appears on CHR, UTC, and ET labels on Chronometer
![chrono](https://user-images.githubusercontent.com/38857762/103088814-e82ba800-45e3-11eb-9a17-9f06d70f49f7.png)

**Comment by FRYYYYYY** [comment]
And the button text should rotate.

**Comment by DarkOfNova** [comment]
Closing issue as both issues have been fixed with pr's #2924  and #3130

**Comment by DarkOfNova** [comment]
Closing issue as both issues have been fixed with pr's #2924 and #3130
