### ISSUE TITLE
Adding A32NX mod to community folder breaks the FMC on the default 747 aircraft

### ISSUE THREAD

**Issue by JSFamilyUK** [flybywiresim/a32nx#2689]
**Mod Version**

"built": "2020-12-24T07:44:26+00:00",
  "ref": "",
  "sha": "",
  "actor": "donstim <70166617+donstim@users.noreply.github.com>",
  "event_name": "manual"

**Describe the bug**

Whenever the Stable or Dev versions are loaded into the community folder there is an issue caused with the default 747-8. The issue is that the FMC is blank and cannot be used. The mod does not impact the FMC on the A32NX and that aircraft appears to be fully functional. 
As soon as the FBW mod is removed from the Community folder the FMC on the 747 returns to normal functionality

**To Reproduce**

1. Empty community folder of all mods
2. Check functionality of 747 FMC in FS2020
3. Install the Dev or Stable version of the FBW aircraft
4. Return to FS2020 and check functionality of the FMC

**Expected behavior**

747 aircraft will work as expected including the ability to use the FMC

**Actual behavior**

The FMC on the 747 is blank and cannot be used.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
This has only started happening since the December update to FS2020
Is this a problem in the vanilla unmodded game?
Yes

![IMG_0183](https://user-images.githubusercontent.com/20225019/103088904-3b055f80-45e4-11eb-8301-be8bf1802b10.jpg)

**Comment by TansyEliot** [comment]
A32NX break "PASS SIGNS" in 787 too.
