### ISSUE TITLE
Some status messages missing on ECAM

### ISSUE THREAD

**Issue by lrargerich** [flybywiresim/a32nx#269]
Here's a very small list of status messages missing on the right of ECAM:
APU AVAIL & APU BLEED indicating status of APU
LDG LT indicating Landing lights are on
PARK BRK when Parking brake is on

<img width="461" alt="Captura de Pantalla 2020-08-30 a la(s) 18 04 31" src="https://user-images.githubusercontent.com/7193221/91681636-6dff8100-eb25-11ea-854e-4be8711c0b3c.png">
<img width="498" alt="Captura de Pantalla 2020-08-30 a la(s) 17 56 16" src="https://user-images.githubusercontent.com/7193221/91681678-912a3080-eb25-11ea-93ef-ca1f6a14236a.png">
<img width="486" alt="Captura de Pantalla 2020-08-30 a la(s) 18 07 25" src="https://user-images.githubusercontent.com/7193221/91681816-fda52f80-eb25-11ea-98db-878fcbeeb63b.png">

**Comment by NathanInnes** [comment]
Fixed with #430. Closing issue.
