### ISSUE TITLE
[BUG] Autoland with Flare not working after latest update

### ISSUE THREAD

**Issue by ChrisM001** [flybywiresim/a32nx#2690]
**Mod Version**

0.51

**Describe the bug**

Autolanding with autopilot on until landing and only setting the thrust to idle did work fine until the latest release of MS Flightsimulator 2020 and release 0.50 of Flybywire. The aircraft was flaring from itself before landing. Since release 1.12.13.0 of MS Flightsimulator this isn't working anymore and even the Flybywire 0.51 doesn't correct this. The aircraft is bouncing away from the runway instead, because the vertical down speed is too high and the aircraft isn't flaring anymore.

**To Reproduce**

1. Land with Autopilot engaged
2. Reduce thrust to idle 30 ft before landing

**Expected behavior**

Flaring and smooth landing

**Actual behavior**

No Flaring, bouncing away from the runway instead

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Was working before. Problem started occuring with new MS Flightsimulator 2020 v. 1.12.13.0. 

Is this a problem in the vanilla unmodded game?
It could be a problem in combination of the vanilla version and Flybywire. Maybe it was never working in the vanilla game but the flybywire mod fixed it. I don't know exactly. Fact is, that it worked before the latest vanilla game update to 1.12.13.0 in combination with flybywire 0.50. 

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Autoland was never implemented
