### ISSUE TITLE
[BUG] Enabling VR mode will make the plane go back to the previous waypoint

### ISSUE THREAD

**Issue by jaoord** [flybywiresim/a32nx#2693]
**Mod Version**
{
  "built": "2020-12-24T07:44:26+00:00",
  "ref": "",
  "sha": "",
  "actor": "donstim <70166617+donstim@users.noreply.github.com>",
  "event_name": "manual"
}

**Describe the bug**
Everytime I enable VR mode (either via hotkey CTRL+V or joystick button 1), the plane will go the previous waypoint

**To Reproduce**
1. start flight, takeoff as usual. Follow course on flightplan
2. enable vr mode. The plane will now go the previous waypoint

**Expected behavior**
Plane should keep current course and change waypoints

**Actual behavior**
Plane changes waypoints and turns around

**References**

**Additional context**
Also happened on previous master version.

**Comment by Benjozork** [comment]
Does this happen in other planes ?

**Comment by jaoord** [comment]
Yes it does also happen in the TBM, even with the mod removed. I will contact MS.
