### ISSUE TITLE
[BUG] FMGS Flight Phase Doesn't get Reset by Simbrief Import if active flight phase is "Go-Around"

### ISSUE THREAD

**Issue by efortier-95** [flybywiresim/a32nx#2695]
**Mod Version**

  "built": "2020-12-24T07:44:26+00:00",
  "ref": "",
  "sha": "",
  "actor": "donstim <70166617+donstim@users.noreply.github.com>",
  "event_name": "manual"

**Describe the bug**

If the active flight phase is Go-Around (caused by moving the throttles to TOGA while on approach), a Simbrief imported flightplan will not cause the flight phase to reset to take-off during the turnaround. Not sure if this happens with manually built flightplans, however.

**To Reproduce**

1. Activate approach phase during arrival
2. During approach, temporarily set throttle to TOGA to activate GA
3. Once landed and engines shut down, set up a turnaround flight with a Simbrief import.

**Expected behavior**

I don't know...I suppose I expect the active flight phase to return to Take-Off at some point during the turnaround.

**Actual behavior**

The FMGS active flight phase remains as Go-Around.

**References**

![image](https://user-images.githubusercontent.com/56796781/103108028-e547ac00-4611-11eb-8339-daa3e173b227.png)

**Additional context**

Was this working before/when did the issue start occurring?
Unknown

Is this a problem in the vanilla unmodded game?
N/A, no Simbrief import in unmodded game.

Discord username (if different from GitHub):
Eefoe#0570

**Comment by tareksabet** [comment]
Can you confirm it's still an issue, because I think it was fixed.

**Comment by MisterChocker** [comment]
Yes this is because you are not supposed to land in go-around phase, or continue approach after initiating go-around.

**Comment by MisterChocker** [comment]
Closing since no response from op
