### ISSUE TITLE
[BUG] OUTR TK FUEL XFRD BUG

### ISSUE THREAD

**Issue by Kimbyeoungjang** [flybywiresim/a32nx#2702]
**Mod Version**

{
  "built": "2020-12-24T08:33:25+00:00",
  "ref": "refs/remotes/origin/HEAD",
  "sha": "f730007347c73daa0b62eeec1b7c2d38a6c9ac3e",
  "actor": "donstim <70166617+donstim@users.noreply.github.com>",
  "event_name": "manual"
}

**Describe the bug**

When  OUTR TK FUEL XFRD is showed on ECAM, can't stop warning light when click it
that light off when 5 sec ago maybe?

![image](https://user-images.githubusercontent.com/23118756/103134774-02a27600-46f7-11eb-8c2c-c1bafdeafdb8.png)

**To Reproduce**

1. spawn on aircraft(on gate) and connect bat and ext pwr
2. select fuel to 0(or wing fuel 0)
3. click matser caution button

**Expected behavior**

master caution will off

**Actual behavior**

master caution is not off and after 5 sec, it off.

**References**

no

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by donstim** [comment]
OUTR TK FUEL XFRD is not a warning, it is a message, just like the seat belts and no smoking messages that are displayed on the ECAM in your screenshot.  Messages do not light up the master caution button and are not cancellable by pushing that button.

I don't know what caused your master caution button to light up, but it appears to me to be connected with the display of red X's for all the engine indications.  I could not reproduce what you have in your screenshot using the steps you listed. In any case, the OUTR TK FUEL XFRD message is working as intended.

**Comment by tareksabet** [comment]
It can't be reproduced.

make sure you have the latest master version or the latest stable version 0.5.1.

thanks for reporting this issue, if you have this issue again comment to I can reopen it.
