### ISSUE TITLE
[BUG] FMC Reset FP after switch to/from VR mode

### ISSUE THREAD

**Issue by Raveldarklight** [flybywiresim/a32nx#2703]
**Mod Version**
Stable 0.5.1

**Describe the bug**
In mid flight, I used the option in MSFS2020 to go back to desktop mode. After a few second the flightplan was gone from my SFD, and also the FMC went back to de default status.
This also happens when you switch to VR in the same way.
Example in video. https://youtu.be/Tgxj89N8S1M

**To Reproduce**
1. Load flightplan via SIMBRIEF (Maby also manual)
2. Switch to VR mode / Switch to Desktop mode
3. Check FMC/SFD

**Expected behavior**
The flight plan should stay .

**Actual behavior**
Flight plan is gone... reset.

**References**
https://youtu.be/Tgxj89N8S1M

**Additional context**
Feel free to contact me for information via Discord.

Is this a problem in the vanilla unmodded game?
I dont know.

Discord username (if different from GitHub): Ravel_#9112

**Comment by sidnov** [comment]
Issue fixed as per the feedback received on Discord. Feel free to reopen if otherwise.
