### ISSUE TITLE
[BUG] Massiv stutter after Simbrief Flight Plan upload

### ISSUE THREAD

**Issue by Daboj1337** [flybywiresim/a32nx#2708]
**Mod Version**
Dev

**Describe the bug**
Massiv sutter after Simbrief Flight Plan upload

**To Reproduce**
1. Just insert a flight plan and start taxi

**References**
Before
<img width="886" alt="Before" src="https://user-images.githubusercontent.com/76589309/103138334-a8db8500-46d1-11eb-84d5-285a6b0da67d.png">

After
<img width="560" alt="After (2)" src="https://user-images.githubusercontent.com/76589309/103138337-b1cc5680-46d1-11eb-8a75-0d83ce51bd00.PNG">

**Additional context**
Hardware i9 10900k and Asus 3090ti  and 32gb ram

Is this a problem in the vanilla unmodded game?
Not tested

**Comment by andrejetcat** [comment]
I also notice a massive increase in stutter, when the flightplan is full. Also a kind of Periodic drop in CoherentGTDraw, that causes the sutter. with a empty flightplan, A32NX runs smooth as butter for me.

**Comment by Daboj1337** [comment]
> I also notice a massive increase in stutter, when the flightplan is full. Also a kind of Periodic drop in CoherentGTDraw, that causes the sutter. with a empty flightplan, A32NX runs smooth as butter for me. for me, its not only with a simbrief plan, but with hand- insert plan, too. also if there is only DEP and DEST airport insert.

Exactly!

**Comment by philipp00sk8** [comment]
same thinks for me with navigraph beta...when i enter runway for departure the stutter begin

**Comment by Benjozork** [comment]
We're integrating a custom flight plan manager system soon and will have the opportunity to investigate reduced performance.

**Comment by 2hwk** [comment]
Improved by #4953 closing ☑️
