### ISSUE TITLE
LS button does not illuminate anymore

### ISSUE THREAD

**Issue by flightsimsimon** [flybywiresim/a32nx#271]
Though all ILS functions are working, LS button no longer illuminates when pressed

Simon

**Comment by ukflyer** [comment]
Hi, 
Also raised in https://github.com/wpine215/msfs-a320neo/issues/67
If you turn up the panel brightness its fine :)

**Comment by flightsimsimon** [comment]
I see that thanks - that is still a bug though and shouldnt be affected by floodlighting

**Comment by ukflyer** [comment]
absolutely Simon i believe its on the TO DO list :)

**Comment by flightsimsimon** [comment]
Ah brill

**Comment by 2hwk** [comment]
![image](https://user-images.githubusercontent.com/15316958/91783565-341ca080-ec33-11ea-8d4b-03f2e5deb657.png)

LS brightness is linked with panel lighting brightness.

See #67

**Comment by Curtis-VL** [comment]
Fixed in #451.
