### ISSUE TITLE
[REQUEST] Wiper speed is too fast

### ISSUE THREAD

**Issue by dc1ps2** [flybywiresim/a32nx#2716]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**

Wiper speed is too fast, hope to refer to the real A320.

**References**

sim2020:
https://user-images.githubusercontent.com/11674129/103143067-7a4dc080-474a-11eb-84d5-ef4707228015.mp4

real:
https://user-images.githubusercontent.com/11674129/103143027-78373200-4749-11eb-97a8-b7cc79263a00.mp4

**Additional context**

Discord username (if different from GitHub):

**Comment by hotshotp** [comment]
is this on slow mode in the sim?

**Comment by dc1ps2** [comment]
> is this on slow mode in the sim?
yes, just turn to slow

**Comment by aviationenthusiast** [comment]
This has always bothered me.
