### ISSUE TITLE
Lever climb flashing in FMA on taxi

### ISSUE THREAD

**Issue by flightsimsimon** [flybywiresim/a32nx#272]
Lever climb flashing in FMA on taxi to runway, GS was 25

**Comment by PCGamesF1Tech** [comment]
Is A/THR on for some reason? 
It could ask for LVR CLB to have full thrust range available. 
Although useless on ground...

**Comment by flightsimsimon** [comment]
I will check and get back to you

**Comment by Curtis-VL** [comment]
Fixed in a recent merge, thanks for the report!
