### ISSUE TITLE
[BUG] Erroneous altitude constraint with SImBrief flight Plan

### ISSUE THREAD

**Issue by JLD95** [flybywiresim/a32nx#2723]
**Mod Version**

{
  "built": "2020-12-23T23:38:26+00:00",
  "ref": "",
  "sha": "",
  "actor": "DerL30N <leon.beeser@yahoo.de>",
  "event_name": "manual"
}

**Describe the bug**

Altitude constraint is erroneous because not defined in Flight Plan

**To Reproduce**

1.  SimBrief Flight Plan:  LFPO/24 OPAL8P OPALE UT421 KUNAV Y8 BANVA BANV1L EGGW/25
2. At UNDUG waypoint, MCDU display an Alt ctsr is 511 ft 
![2020-12-26 (1)](https://user-images.githubusercontent.com/5894146/103145846-f511de00-4740-11eb-8f7b-a4cf6fe5c527.jpg)
3. See SimBrief details for UNDUG waypoint
--------------------------------------------------------------------
AWY                           FL   IMT   MN    WIND  OAT  EFOB  PBRN
POSITION    LAT      EET ETO MORA  ITT  TAS    COMP  TDV
IDENT       LONG    TTLT ATO DIS  RDIS   GS     SHR  TRP  AFOB  ABRN
FREQ
--------------------------------------------------------------------
BANVA1L                      360   319  .79 332/042  M65   3.5   2.1
UNDUG       N5047.4 0003 ...  27   319  444    M041  M08
UNDUG      E00025.5 0029 ...  19   113  403       3  406  ....  ....

BANVA1L                      360   325  .79 332/042  M65   3.4   2.2
MAYFIELD    N5101.0 0003 ...  27   325  444    M041  M08
MAY        E00007.0 0032 ...  18    95  403       3  406  ....  ....
117.90

**Expected behavior**

correct altitude constraint in FP

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
not applicable

**Comment by MisterChocker** [comment]
The altitude constraint algorithm is smart enough to spot some mistakes like that and ignore the constraints.
However interesting catch.

**Comment by tareksabet** [comment]
It's been working on by a pr not yet published but very soon.

Thanks for reporting this issue.

**Comment by 2hwk** [comment]
Fixed by #4953 closing ☑️
