### ISSUE TITLE
[BUG] CTD on every flight

### ISSUE THREAD

**Issue by Hor1463** [flybywiresim/a32nx#2724]
Cince I download the last MOD 5.1 and the MSFS Update, there is every flight an CTD. Sometimes when rolling, sometimes in flight

**Mod Version**

5.1

**Describe the bug**

CTD on every flight

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Watsi01** [comment]
I hardly had any CTDs before MFSF 1.12.13.0 update. Now I have several. I found out, that it depends on the region I fly in. Could you fly another region in the world and check if you still have CTDs? I'm asking this, cause I'm not sure if this is A32NX related.

**Comment by Hor1463** [comment]
Yesterday I have 2 CTD Flight from LSZH to EDDK. Today I fly the other way (EDDK LSZH) First all works well, but then I get a CTD in the Pause mode.
Nexxt Flight from CYVR to KSFO. I will see and tell you. Nothing like this before the MSFS 1.12.13.0 with the MOD.

**Comment by Lucky38i** [comment]
Do you have any mods installed?

**Comment by Hor1463** [comment]
Only the 0. 5.1

**Comment by Hor1463** [comment]
I will do another fight EDDK LSZH without the MOD addionaly.

**Comment by Benjozork** [comment]
Please respect the template.
