### ISSUE TITLE
clock speed x2 on any aircraft

### ISSUE THREAD

**Issue by Naut85** [flybywiresim/a32nx#273]
clock speed x2 on any aircraft. Dev branch. After deleting a320nx everything becomes normal.

**Comment by JoeW9** [comment]
I'll take a look into this now however I personally have never experianced this issue.

**Comment by JoeW9** [comment]
I personally couldn't replicate your issue if your on about the clock inside the aircraft. It would be useful if you could be more specific or post a video of the issue. 

Thanks

**Comment by Meqolo** [comment]
by x2 do you mean it takes twice as long? most likely caused by an fps fix if you are using one

**Comment by Naut85** [comment]
I apologize for my English, not my native language, but I will try to explain.

Today I downloaded the mod from the dev branch, installed it according to the instructions. I created a flight plan in simbrief, loaded it into the sim, loaded the plane at the gate at the airport, turned on the batteries and saw that on the clock the seconds were running at a speed of x2. I went to the menu and loaded another plane (SR22 seems to be) and on the display of the Garmin I found the same problem with the clock. After that, I uninstalled the mod, loaded the simulator and everything was fine.

**Comment by Naut85** [comment]
> by x2 do you mean it takes twice as long? most likely caused by an fps fix if you are using one

No, seconds go twice as fast

**Comment by JoeW9** [comment]
Okay this is strange I can't replicate this bug if others can let me know if they have this issue thanks.

**Comment by aboodilatif** [comment]
this bug used to happen to me when i had the fps fix installed, 120hz monitor with 60 fps ingame. all monitors would take 2x the time to load, Self test would take around 1 min, red ATT would blink very slowly the first two times.
after removing the fps fix everything worked like normal.
hope this helps

**Comment by JoeW9** [comment]
Okay so this is resloved I take it.

**Comment by Naut85** [comment]
> this bug used to happen to me when i had the fps fix installed, 120hz monitor with 60 fps ingame. all monitors would take 2x the time to load, Self test would take around 1 min, red ATT would blink very slowly the first two times.
> after removing the fps fix everything worked like normal.
> hope this helps

But I am not using fps fix. Maybe someone from the developers accidentally pushed it into the dev-build?

**Comment by JasonO99** [comment]
I am looking at the clock above the landing gear, using [0.2.0] - 2020-09-04 version - Sim rate x1. No other mods loaded - the clock appears to run as expected. I've run a stopwatch next to it and the seconds tick over at the same time.

I'm using real time and 1.5 hours into the flight it's within +/- 30 seconds (might have paused briefly on start). 

Not sure if any fix has been applied since this was posted but unsure if OP still has the issue on latest version. Could be resolved.

**Comment by AdenFlorian** [comment]
@Naut85 can you retest this on latest master branch, with no other mods installed?

**Comment by Naut85** [comment]
> @Naut85 can you retest this on latest master branch, with no other mods installed?

version 0.2.0 works fine
