### ISSUE TITLE
[BUG] Some knobs not functioning after "restart" a flight

### ISSUE THREAD

**Issue by Watsi01** [flybywiresim/a32nx#2730]
**Mod Version**
"built": "2020-12-24T23:53:55+00:00",
  "ref": "",
  "sha": "",
  "actor": "Alex McBean <al.mcbean@outlook.com>",
  "event_name": "manual"

**Describe the bug**
If you restart a flight, using the MSFS "restart" option. Some knobs are not working. Which means, clicking them does something (they are actually working), but the knobs won't turn or show any feedback 

**To Reproduce**

1. Start a full flight, cold&dark
2. After a while (e.g. while taxiing to rwy) push ESC and "restart" the flight
3. Do your preparations and go as you normally would.
4. Check knobs and buttons during process.

**Expected behavior**
All knobs working/giving feedback.

**Actual behavior**
Knobs, switches and buttons, like engine master switch, engine ignition switch, APU bleed, APU on/off seem to do what they should, but visually beeing stuck on previous condition (no movement / no change on button light)

**References**

**Additional context**
Don't know if this can be fixed within the A32NX mod. Just wanted to file this for documentation.

Was this working before/when did the issue start occurring?
No clue.

Is this a problem in the vanilla unmodded game?
Didn't try.

**Comment by tareksabet** [comment]
I tried it it can't be reproduced.

can you try on the latest master version or even the latest stable version 0.5.1 

thanks for reporting.
