### ISSUE TITLE
[BUG] Landing Gear can be extended above 264 kts

### ISSUE THREAD

**Issue by avteknisyan** [flybywiresim/a32nx#2731]
**Mod Version**
master

**Describe the bug**

when the aircraft is above 264 knots, i was able to extend the landing gear

**To Reproduce**

1. In-flight
2. speed above 264 kts
3. select landing gear lever to "down" position

**Expected behavior**

Landing gear lever can be selected down but it will not extend the landing gear when airspeed is above 264 knots.

Landing gear can only be extended below 260 knots

**References**

A320 AMM 32-31-00-00 Normal Extension and Retraction

![safety valve 3](https://user-images.githubusercontent.com/73177405/103153521-62e5f600-4791-11eb-9c8b-643126b155af.PNG)
![safety valve](https://user-images.githubusercontent.com/73177405/103153522-637e8c80-4791-11eb-904c-358c19c2efe0.PNG)

**Additional context**

in the A320, there is a safety valve (49GA) located in the RH main landing gear bay (inside wheel well) which isolates the Green Hydraulic System from the Landing Gear if the airspeed is above 264 knots (ADIRU 1 and ADIRU 3 as source)

The valve is always energized open (speed less than 260 kts) and de-energized to closed (speed more than 264 kts)

Was this working before/when did the issue start occurring?

no

Is this a problem in the vanilla unmodded game?

yes

Discord username (if different from GitHub): avteknisyan

**Comment by hotshotp** [comment]
very good reference

**Comment by Poiuz367** [comment]
What happens when the lever is down and the speed goes from above 260 to below 260?

**Comment by avtechnician** [comment]
> What happens when the lever is down and the speed goes from above 260 to below 260?

retraction will take place.

but as a pilot, you also have to take note of speed limits on Landing Gear operation.

![safety valve 4](https://user-images.githubusercontent.com/73177405/103369307-17518600-4aca-11eb-93f0-3a316a0c7923.PNG)
![safety valve 5](https://user-images.githubusercontent.com/73177405/103369309-17ea1c80-4aca-11eb-9d81-9af63a796c27.PNG)
