### ISSUE TITLE
[REQUEST] Make Parameters Read from External Config File to Allow 3rd party (4th party?) Developers to Customize FBW A320 Systems to Full Extent

### ISSUE THREAD

**Issue by efortier-95** [flybywiresim/a32nx#2732]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the feature you'd like to see implemented**

The release of the Project Megapack A321 had me thinking, most of the flight deck across all the A320 family variants are the same. However, there will be minor variations here and there, particularly in things like FMGS/MCDU/Autopilot performance calculations or specific PID tuning variables. So one can't necessarily use the FBW A320 flight deck for the A321 and expect 1-to-1 usability.

However, this did raise the idea: What if the necessary figures that would vary from aircraft to aircraft were, instead of being hard-coded into the gauges, be read from an external .cfg containing all these variables? This external cfg would then contain parameters that the MCDU/FMGS/etc. would read when the aircraft initially loads, and then be used in performance calculations. It could contain things like:

- Optimum cruise altitude matrix for various gross weights and CI
- Various weight and fuel capacity limitations
- V1/Vr/V2 for various conditions
- Climb/cruise/descent fuel/time/distance prediction figures
- Autopilot tuning parameters that may vary from one variant to another
- etc.

That way, an A321 developer can then load this exact cockpit, except provide their own config file containing the customized parameters for their specific application. 

Not sure how feasible this could be, however. It would require the A321 developer to call-up the FBW A320 cockpit, yet somehow tell the sim or the gauge to use the specific config file provided by the developer.

**References**

N/A

**Additional context**

N/A

Discord username (if different from GitHub):
Eefoe#0570

**Comment by Benjozork** [comment]
Other developers have the right to maintain their own copy of our code with their desired changes and host it on GitHub. We suggested that to Aircraft Megapack which they refused.

It's a common practice in open source software development, and it's other developers' responsibility to do so correctly.

Creating those config files would be a time and performance challenge and for the reason stated above it does not provide any benefit.
