### ISSUE TITLE
[BUG] Possible bug with fuel pumps before start

### ISSUE THREAD

**Issue by donutsdemise** [flybywiresim/a32nx#2736]
**Mod Version**

Stable

**Describe the bug**

Fuel pumps Left TK 2, Ctr TK 2, and Right TK 2 do not turn on after I modified the a32nx engines.cfg for increase fuel burn

**To Reproduce**

1. Modify the engines.cfg file for higher fuel burn in A32NX>SimObjects>AirPlanes>Asobo_A320_NEO>engines.cfg to "idle_fuel_flow = 800 ; pound per hour", "high_fuel_flow = 5400" and "fuel_flow_max = 6250"
2. Set up a new flight
3. Buttons for these fuel pumps don't work

**Expected behavior**

The fuel pumps for L, R, and Ctr should all turn on, not only those designated as TK 1

**Actual behavior**

TK 2 pumps do not turn on

**References**

I modified the fuel burn and experienced this problem; I also found the fix if you experience it: modify the official package Asobo A320 engines.cfg file to match the same fuel burn numbers and the bug goes away

**Additional context**

Not sure if this is the right place or right way to post this, but I just wanted to make the info known.

Was this working before/when did the issue start occurring?
This started happening after the 5.0 update and still occurs with the latest release of the stable version when the user makes this modification

Is this a problem in the vanilla unmodded game?
No, the official default A320 works normally

Discord username (if different from GitHub):

**Comment by SameerAli18** [comment]
try the latest dev build

**Comment by donutsdemise** [comment]
Oh I fixed the issue I had, I just wanted to post the info here to let people know if they have the same problem. Fix is in the "References".

**Comment by donutsdemise** [comment]
I guess I should also add that without turning on the TK 2 pumps in this situation, the APU would not start and the engines would not start either.

**Comment by Benjozork** [comment]
We cannot help you if you modify the package files.

**Comment by donutsdemise** [comment]
I don't need help. I created an issue and fixed it and posted it here in case someone else does the same thing.

**Comment by Benjozork** [comment]
I am confused. You state "Fuel pumps Left TK 2, Ctr TK 2, and Right TK 2 do not turn on after I modified the a32nx engines.cfg for increase fuel burn" which to me sounds like you are having a problem after modifying the files.

Anyway, sorry but this is not really the right place. The "issues" section is strictly for bug reports with unmodified versions.

**Comment by donutsdemise** [comment]
Yeah, and then, I modified the default to fix that issue, now everything agrees and my mod works so I burn more than 1000kg of fuel on a 3 hour flight.

**Comment by Benjozork** [comment]
¯\_(ツ)_/¯
