### ISSUE TITLE
[BUG] TCAS Traffic Mode Switch 

### ISSUE THREAD

**Issue by SameerAli18** [flybywiresim/a32nx#2742]
**Mod Version**
"built": "2020-12-25T10:12:36+00:00"

**Describe the bug**
The THRT, ALL, ABV, BLW switch doesn't turn all the way .

**To Reproduce**
1.Spawn at an airport
2.Set up plane from C/D
3.Turn the traffic mode switch

**Expected behavior**
The switch to not turn all the way.

**Actual behavior**
The switch turned 4 times but didnt move much, when you turn the switch 4 time it goes to all.

**References**
https://www.loom.com/share/d7a26b50b2444b70b7d8de709ac0c610

**Additional context**
Spawned at egcc stand 11.

Was this working before/when did the issue start occurring?
When the latest dev build came out.
Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):
Sameer Ali#4139

**Comment by airfirefighter** [comment]
Also dosent work in high altitudes

**Comment by Benjozork** [comment]
There is little purpose in adding functionality to this switch at the moment, as there backing functions of TCAS are not implemented yet.

**Comment by lukecologne** [comment]
This is weird, the animation has been correct when #2242 got merged. It must have been changed in the latest MSFS update, when we integrated the model changes

**Comment by lukecologne** [comment]
I'm afraid there is not much we can do until the exporter is ready, we need to change the model to fix this.
