### ISSUE TITLE
[BUG] TO/GA not working

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#2743]
**Mod Version**

MASTER (FBW) 

**Describe the bug**

When the Bus is proper set up for Takeoff, with a Flexed Takeoff-Thrust, Engines spool up to FLEX-N1-value (with the known overshoot issuse), but when I increase the Throttle more, to go into the TO/GA mode, N1 stays @ FLEX-Value. So it is not possible to takeoff with a higher N1, than FLEX% for me.

**To Reproduce**

1. set Plane proper for Takeoff with a flex-temp value, e.g. 48C°
2. set thrust to FLEX on takeoff-roll
3. now try to increase thrust to To/GA - thrust remain the same.

**Expected behavior**

TO/GA - Thrust should be the highes avail on takeoff (depending on TEMP, Density, ect for shure!

**Actual behavior**

TO/GA Thrust = FLEX Thrust

**References**

-

**Additional context**

-
Was this working before/when did the issue start occurring?
-
Is this a problem in the vanilla unmodded game?
-

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
cc. @aguther

**Comment by hotshotp** [comment]
That's because flex is kinda broken as of now, it gives pretty much the same value as toga

**Comment by aguther** [comment]
I can confirm it with cfbw, does it happen with the default A320 as well?

**Comment by MisterChocker** [comment]
Climb Thrust, Mct/Flex and Toga are not working properly atm

**Comment by philhzss** [comment]
> Climb Thrust, Mct/Flex and Toga are not working properly atm

I've only been using this amazing add-on for a few days but I noticed I couldn't get FLEX to work (I seem to always be taking off with too much thrust). 

I thought this was my fault for using it wrong and not reading the manual enough but is it a bug haha? Just wondering. Thanks!!

**Comment by MisterChocker** [comment]
yeah thrust ratings are currently not limiting the thrust values. But we are working on ot.

**Comment by philhzss** [comment]
> yeah thrust ratings are currently not limiting the thrust values. But we are working on ot.

Ok perfect thank you!!

**Comment by aguther** [comment]
Should be fixed on dev
