### ISSUE TITLE
[BUG] Cockpit throttle quadrant, switches and knobs freeze up mid-flight

### ISSUE THREAD

**Issue by JRHorse** [flybywiresim/a32nx#2744]
**Mod Version**
0.5.1 release version

**Describe the bug**
Throttle quadrant and switches and knobs inside the cockpit randomly freeze during flight. 

**To Reproduce**
In my instance, I was flying from TNCM to KDFW. The issue occurred approximately 3 1/2 hours into the flight (for what should have been around a 5 1/2 hour flight), operating at 1x speed.

**Expected behavior**
Knobs, switches and throttle expected to operate normally throughout the entire flight.

**Actual behavior**
Around 3 1/2 hours into the flight, all cockpit knobs, switches and throttles became frozen. No visual indication of throttles moving up and down, buttons being pressed or knobs being turned. Unable to adjust panel lighting, dome lighting, brightness on panels, etc.
Adjustment to speeds and altitude in autopilot did work and was able to complete the flight, though with some difficulty.

**References**
None

**Additional context**
None

Was this working before/when did the issue start occurring? Today

Is this a problem in the vanilla unmodded game? Not yet able to reproduce, in part due to the timing of when this all occurred.

**Comment by Benjozork** [comment]
This is unfortunately a random MSFS issue that has been occuring since the sim launched.
