### ISSUE TITLE
Flight Dynamics update

### ISSUE THREAD

**Issue by frankgrivel** [flybywiresim/a32nx#275]
I've updated the flight dynamics to make the model less twitchy. After some testing I've increased the aileron effectiveness to allow the autopilot to work properly.

**Comment by frankgrivel** [comment]
Changes:
empty_weight_pitch_MOI
empty_weight_roll_MOI
empty_weight_yaw_MOI

wing_area
wing_root_chord
wing_dihedral
wing_incidence
oswald_efficiency_factor
wing_winglets_flag
wing_sweep
htail_area
htail_span
htail_sweep
vtail_area
vtail_span
vtail_sweep
fuselage_length

positive_g_limit_flaps_up
positive_g_limit_flaps_down
negative_g_limit_flaps_up
negative_g_limit_flaps_down

elevator_effectiveness
aileron_effectiveness
pitch_stability

full_flaps_stall_speed
flaps_up_stall_speed
cruise_speed
max_indicated_speed

extending-time
damaging-speed

lift_scalar
drag_scalar
pitch_scalar

**Comment by CoffeePanda0** [comment]
Hey, did you mean to make a pull request with the new changes? Thanks

**Comment by frankgrivel** [comment]
> Hey, did you mean to make a pull request with the new changes? Thanks

I did; I'm going to look into that
