### ISSUE TITLE
[REQUEST] Add FSUIPC support to seatbelt sign

### ISSUE THREAD

**Issue by ZigTag** [flybywiresim/a32nx#2752]
**Is your feature request related to a problem? Please describe.**

Currently, the seatbelt switch does not trigger the seatbelt sign in FSUIPC (for SLC or PACX)

**Describe the feature you'd like to see implemented**

Add the trigger so it can tell FSUIPC if the seatbelt sign is on or not

**References**

N/A

**Additional context**

Discord username (if different from GitHub):

**Comment by airfirefighter** [comment]
the asobo seatbelts signs are supported .only in a32nx are not supported.

**Comment by nosferatie** [comment]
So I guess the request is to use deault seatbelt and smoke switches?

**Comment by Benjozork** [comment]
> 
> 
> So I guess the request is to use deault seatbelt and smoke switches?

The default ones use `ON/OFF` while the no smoking signs in the plane have "ON/AUTO/OFF", so syncing the two is a bit tedious. Working on it atm.

**Comment by ZigTag** [comment]
Maybe you can have the actual switch be different than the asobo one, and while the a32nx one is on auto, it automatically triggers the on and off of the asobo one.

**Comment by airfirefighter** [comment]
i think the most important are the seat belt that been used from other programs too. the no smoking comes secondary .

**Comment by stsvesuk** [comment]
Any progress on this?

CABIN SEATBELTS ALERT SWITCH
CABIN NO SMOKING ALERT SWITCH

Can't wait to trigger my PA announcements on using the switches.

**Comment by stsvesuk** [comment]
No progress. Please can we add this trigger.

**Comment by Benjozork** [comment]
This is low priority behind autopilot and performance improvements, among other more pressing issues.

If you wish for a functionality to be added, you are always free to work on it and add it to the project.

**Comment by stsvesuk** [comment]
Ok, thanks for your update.

Haha, I'm a developer but not up to the class that needed for this project!

**Comment by stsvesuk** [comment]
Thanks all, one small change for the A32NX but a huge one for my flying experience!
