### ISSUE TITLE
[BUG] Spotlight/Missions and Landing Challenges Not Loading with NX Mod

### ISSUE THREAD

**Issue by VCAmyPopple** [flybywiresim/a32nx#2753]
**Mod Version**

master

**Describe the bug**

Since the latest MSFS update (1.12.13.0), the NX mod prevents the execution of any missions containing the NEO, this includes flight training and landing challenges. The sim states that additional packages from the content manager are required to fly these missions.

When loading missions with vanilla A320 NEO, the sim allows the execution of said events.

**To Reproduce**

1. Load the current 1.12.13.0 update and have the NX mod installed
2. Run the spotlight event (LFPG landing) (or LXGB Strong Wind Landing Challenge)

**Expected behavior**

The missions are available and flyable

**Actual behavior**

The sim displays an error stating that additional packages are required to run the missions.

**References**

**Additional context**

From my programming knowledge this appears to be an issue with the .FLT referencing file (but can't confirm):
```
[Sim.0]
Sim=Airbus A320 Neo Asobo
SimFile=final.FLT
```

Was this working before/when did the issue start occurring?
Yes - prior to 1.12.13.0

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):

**Comment by wpine215** [comment]
![image](https://user-images.githubusercontent.com/28059870/103165811-128e8880-47d1-11eb-849d-c41d533c0e94.png)

**Comment by VCAmyPopple** [comment]
Okie dokie, I appreciate the swift update. Shame. Thanks @wpine215 

It sounds like you have already dug into this. If I get some time I may dig around and see if I can spot a workaround, if I get my head around the files first 😉

**Comment by VCAmyPopple** [comment]
As I thought it is to do with the Missions .FLT. If you change it from:

```
[Sim.0]
Sim=Airbus A320 Neo Asobo
SimFile=final.FLT
```

to 

```
[Sim.0]
Sim=Airbus A320neo
SimFile=final.FLT
```

... the NX mod **now works**.

Will do some more digging to see if there is anything we can change in the mod to allow this without messing with Official content.

**Comment by VCAmyPopple** [comment]
Evidence:
![image](https://user-images.githubusercontent.com/42172705/103178358-0a3e5800-487a-11eb-930c-b7d14701f61d.png)

**Comment by hotshotp** [comment]
@wpine215 this is actually pretty important, take a look at above replies

**Comment by wpine215** [comment]
> As I thought it is to do with the Missions .FLT. If you change it from:
> 
> ```
> [Sim.0]
> Sim=Airbus A320 Neo Asobo
> SimFile=final.FLT
> ```
> 
> to
> 
> ```
> [Sim.0]
> Sim=Airbus A320neo
> SimFile=final.FLT
> ```
> 
> ... the NX mod **now works**.
> 
> Will do some more digging to see if there is anything we can change in the mod to allow this without messing with Official content.

Ah interesting... it was that simple. If you want, feel free to open a PR with this change and we can test it out a bit more and merge it in if everything looks good.

**Comment by robertmacnair** [comment]
I don't think this should be pushed as a PR to be honest. It's on purpose to ensure the challenges are fair, and with the mod it, and especially updated flight model etc it will give users an advantage for points over the default.

**Comment by ThatRedMelon** [comment]
I believe the A32NX folder fix would be to rename the name in aircraft.cfg to the one listed by the landing challenge, but as said above I'm not sure this should be done to keep the challenge fair.
