### ISSUE TITLE
[BUG] A32NX prohibits 787 Seatbelt sign from working

### ISSUE THREAD

**Issue by Nerbulus** [flybywiresim/a32nx#2758]
**Mod Version**
2020-12-27T00:57:27+00:00

**Describe the bug**
When A32NX is installed, the 787 seatbelt sign is stuck in the off position and cannot be moved. The tooltip does not show up either.

**To Reproduce**
1. Install A32NX, stable or dev
2. Load up default Asobo 787
3. On the overhead panel, try moving the seatbelt sign. It is inoperable with no tooltip.

**Expected behavior**
The dial should move between off and on and make the seatbelt ding (this happens when A32NX is not installed)

**Actual behavior**
Dial cannot be moved by any means and sound does not play.

**References**
Dial is stuck in this position:
![image](https://user-images.githubusercontent.com/72303381/103176733-579ed300-4842-11eb-9d16-9cc2f8510c9b.png)

**Additional context**

Was this working before/when did the issue start occurring?
Started occurring after Sim Update 2. Asobo added seatbelt/no smoking chimes to all airliners.

Is this a problem in the vanilla unmodded game?
No.

Discord username (if different from GitHub): Nerbulus

**Comment by TansyEliot** [comment]
Here seatbelt sign works after #2672.

**Comment by Nerbulus** [comment]
Roger that, works in latest dev version once more. I think I will close this issue if you want, since it is fixed. Let me know
