### ISSUE TITLE
[BUG] APU starter switch not working

### ISSUE THREAD

**Issue by apolinski** [flybywiresim/a32nx#2763]
**Mod Version**
 Both in release 0.5.1 and dev version (info below) 
{
  "built": "2020-12-27T00:57:27+00:00",
  "ref": "",
  "sha": "",
  "actor": "2hwk <15316958+2hwk@users.noreply.github.com>",
  "event_name": "manual"
}
 

**Describe the bug**
 When starting from cold and dark, performing normal startup procedure, APU does not start 

**To Reproduce**
When starting from cold and dark, perform normal startup procedure (flight plan created in MSFS planner). All fuel tank switches on. (lights out).
1. After ADIRS align, Press APU master (to on)
2. After "Flap Open" message, press APU starter.
3. APU does not start. APU start sound does not occur.

**Expected behavior**
APU should start.

**Actual behavior**
APU does not start

**References**

**Additional context**
 I set a keyboard binding for "APU starter".  When using the keyboard binding, APU starts briefly but then shuts down. I can get APU started fully only by spamming the binding,  however as soon as I stop, APU will shut down. 

Was this working before/when did the issue start occurring?
--  I have not flown the A320 in a few weeks. APU starter was working fine at that time.

Is this a problem in the vanilla unmodded game?
Yes, but I don't understand why.  I don't have any keybinds for APU on keyboard or for my joystick/throttle. I can start the Longitude APU with no issues. (as of 5 days ago). Default A320 APU starter switch illuminates for 1-2 seconds, then turns off.

mdapol#0281 (if different from GitHub):

**Comment by Benjozork** [comment]
Hello, do you have any other mods installed ?

**Comment by ishtact** [comment]
Ok so there are two things i did to make it work.
1. Removed any other similar MOD folder i had in the community folder even though i renamed A320NX by adding like A320NXDEC there was a conflict so i removed all and put the latest A320NX.
2. XFeed switch in the plane needs to be ON to make it work sometimes. Steps should be, Battery on, then APU master and the other APU one on and Xfeed on. Then APU bleed when all is powered up and you hear a good hum. Then you can proceed to starting engines.

**Comment by ishtact** [comment]
ah i just figured out the center needs fuel else you need to on XFeed switch too.

**Comment by AirbusA320Pro** [comment]
The APU draws its fuel from the Left Inner tank. It's common not to have fuel in the centre tank, so the primary fuel source should be from the main wing tank. This schematic illustrates the "normal" fuel line flow, the dotted red line shows a possible fuel flow source. The crossfeed valve should not be required for fuel to reach the APU pump unless both left and centre tanks are empty.
![A320FuelSys](https://user-images.githubusercontent.com/75289637/103350492-0d169400-4a98-11eb-9535-ea453bc5f119.jpg)

**Comment by tareksabet** [comment]
It cannot be reproduced. if it happens again comment again so I can reopen it.

Also make sure you have the latest master version and stable and also you don't have any other mods that conflicts with the plane.
