### ISSUE TITLE
[BUG] Plotted route bypasses fix by a long way...

### ISSUE THREAD

**Issue by zzyzxuk** [flybywiresim/a32nx#2764]
**Mod Version**

Latest dev build...

**Describe the bug**

Aircraft claims to be going 'direct' to a fix, but the green plotted line is way off that fix.  Was like this in pre-flight and I've had someone else verify they get the same problem.  Route is:  KLGA MERIT HFD PUT TUSKY N145B PORTI/M078F350 47N050W 49N040W 50N030W 52N020W LIMRI/N0453F350 XETBO OSGAR OSGAR2X.  

**To Reproduce**

1. File above flight plan route
2. advance through the 'plan' on the screen
3. You'll see that the green line bypasses LIMRI.

**Expected behavior**

Route should go -through- LIMRI

**Actual behavior**

Green line doesn't go through LIMRI

**References**

![image](https://user-images.githubusercontent.com/62340504/103179650-09abbe80-4886-11eb-849a-d87dfbfd9800.png)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by sidnov** [comment]
Issue fixed with custom FMS systems in place
