### ISSUE TITLE
[BUG] EFOB figure seems to be wildly off

### ISSUE THREAD

**Issue by zzyzxuk** [flybywiresim/a32nx#2765]
**Mod Version**

Latest DEV build

**Describe the bug**

EFOB seems to be off by a lot.  I'm doing a flight and according to my SIMBRIEF and other planning tools will probably have approximately 6.5 tons of fuel left, but the display makes it look like I'll be well short.  (See screenshot and note the distance to go, the FF rate, and see why I think it's wrong?)

**To Reproduce**

1. Started a long-range flight from KLGA to EIDW
2. 
3.

**Expected behavior**

Expected a more realistic figure?

**Actual behavior**

Too low figure displayed (see screenshot)

**References**

![image](https://user-images.githubusercontent.com/62340504/103179771-33b1b080-4887-11eb-9d80-ba0e26ed6202.png)

**Additional context**

Was this working before/when did the issue start occurring?
Unsure

Is this a problem in the vanilla unmodded game?
Unusure

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment]
Yes the current fuel flow is not very accurate since some game limitations, we are currently working an a new engine model which will fix several issues, including correct fuel flow.

**Comment by MisterChocker** [comment]
cc @Lucky38i

**Comment by Rolando1967** [comment]
Yes that's right I noticed yesterday too!

**Comment by michaeldinozzo** [comment]
Also something strange related to this, when you actually switch from F-PLN to FUEL PRED in flight you see that the EFOB value is different on the 2 pages. But when you switch back to F-PLN the intial value changes.

**Comment by Lucky38i** [comment]
Was the flight beyond 3100nm? Currently the fmgc can't make predictions beyond that.

@michaeldinozzo The fuel pred provides a different EFOB depending on engine condition, on or off, hence the disparity.

**Comment by mikecbr** [comment]
@Lucky38i  Why it cant make predicttions beyond that ? i mean if the airplane with full load  fuel has 19.2 , and it burns 1800 kg/h more less, the aircraft its capable to make more than 3100nm for sure , if you make the calculations , 3100 is more less 7 hours , if it burns 1800 kg/h or 2000 kg/H at its maximum its capable to make 4300 nm or 10 hours straight

**Comment by Lucky38i** [comment]
> @Lucky38i  Why it cant make predicttions beyond that ? i mean if the airplane with full load  fuel has 19.2 , and it burns 1800 kg/h more less, the aircraft its capable to make more than 3100nm for sure , if you make the calculations , 3100 is more less 7 hours , if it burns 1800 kg/h or 2000 kg/H at its maximum its capable to make 4300 nm or 10 hours straight 

PLEASE read what I said carefully. I said CURRENTLY, the fmgc can't do it. 

This is an inherit problem in the prediction implementation, so atm you can't expect prediction from flights beyond 3100nm. 

A lack of predictions doesn't prevent you from physically flying 7 hours, that's something you can go right ahead and do.

**Comment by michaeldinozzo** [comment]
Thanks @Lucky38i 
Still I find it very weird that switching from F-PLN to FUEL PRED page in flight updates the EFOB value of F-PLN when you switch back to it. In my opinion computation is rather accurate on the FUEL PRED but seems off or somehow not connected at all on F-PLN. Just doing some simple Maths looking at my FF when in cruise I just can't explain the EFOB displayed there.

**Comment by michaeldinozzo** [comment]
If you want to reproduce just try leaving the FMGC on F-PLN when you are in cruise. Even on short legs you will notice that the EFOB decreases a lot. Then try switching to FUEL PRED and see if the value is different there. When you switch back to F-PLN you should notice that the value will be updated.
If not well the problem is only on my side ;)

**Comment by mikecbr** [comment]
@michaeldinozzo it happens to me also , is not only you ;)

**Comment by Lucky38i** [comment]
> Thanks @Lucky38i 
> 
> Still I find it very weird that switching from F-PLN to FUEL PRED page in flight updates the EFOB value of F-PLN when you switch back to it. In my opinion computation is rather accurate on the FUEL PRED but seems off or somehow not connected at all on F-PLN. Just doing some simple Maths looking at my FF when in cruise I just can't explain the EFOB displayed there.

I'll look into this. Thanks for bringing it up.

**Comment by michaeldinozzo** [comment]
Sorry @Lucky38i but latest PR #2904 doesn't seem to have solved the EFOB discrepancies between the F-PLN and FUEL PRED pages. I still see major differences between the 2 pages and the EFOB seems to drain much faster on the F-PLN page. Only way to make it match is to switch pages as described above. But after some time during the flight the problem reappears.
Would you like to reopen this issue or maybe a new one?
Thanks
