### ISSUE TITLE
[BUG] Marker beacons not shown in PFD

### ISSUE THREAD

**Issue by frankkopp** [flybywiresim/a32nx#2772]
**Mod Version**
{
  "built": "2020-12-28T08:38:04+00:00",
  "ref": "",
  "sha": "",
  "actor": "Andreas Guther <andreas@guther.family>",
  "event_name": "manual"
}

**Describe the bug**
Marker Beacons not shown in PFD
Beacnos sounds are audible, but no marker display in PFD

**To Reproduce**
1. Start from any runway, wait until you hear the beacon sound - see no marker displayed in PFD

**Expected behavior**
http://www.a320dp.com/A320_DP/flight-instruments/sys-8.3.23.html

**Actual behavior**
No Marker displayed

**References**
http://www.a320dp.com/A320_DP/flight-instruments/sys-8.3.23.html

Was this working before/when did the issue start occurring?
unknown 

Is this a problem in the vanilla unmodded game?
unknown 

Discord username (if different from GitHub): Cdr Maverick

**Comment by lukecologne** [comment]
Will be fixed in the PFD rework #1866.
