### ISSUE TITLE
[BUG] FCU Controls Only Work On Captain's Side

### ISSUE THREAD

**Issue by MariusSchuller** [flybywiresim/a32nx#2773]
**Mod Version**
- stable release (installed via GitHub .zip)
- v0.5.1

**Describe the bug**
- The flight control unit controls on the first officer's side do not work (e.g. mode selector, range selector, LS-button, etc.)
- to change the mode or range one has to change those settings on the captain's side, changing them on the FO's side does not impact the displays
- activating the "LS"-button on the FO's side does not show the ILS-infos (frequency, glide-slope etc.). The button eluminates green though.

**To Reproduce**
1. Cold & Dark anywhere
2. Start APU (or connect ground power)
3. Change mode / range on the FO's side

**Expected behavior**
- The displays on the captain's side and the first officers side should be operable individually

**Actual behavior**
- The displays on the captain's side and the first officers side are only operable by the controls on the captain's side

**References**
- screencast of trying to change the FO's displays with the FCU on the FO's side and the captain's side
- [FCU_Controls_Screencast.zip](https://github.com/flybywiresim/a32nx/files/5747740/FCU_Controls_Screencast.zip)

**Additional context**
- none

Was this working before/when did the issue start occurring?
- yes, with all previous versions the two sides where operable individually
- issue first occured with v0.5.1

Is this a problem in the vanilla unmodded game?
- not tested

**Comment by Benjozork** [comment]
Hello, this is resolved in the development version.
