### ISSUE TITLE
TCAS - KNOB don´t move full range

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#2774]
**Mod Version**

MASTER (FBW)

**Describe the bug**

TCAS (ALL/ABV/BLW) - Selector knop doen´t move full range

**To Reproduce**

1. try to rotate this knop to BLW
2.
3.

**Expected behavior**

should point to each state

**Actual behavior**

don´t point on each state

**References**

**Additional context**

Was this working before/when did the issue start occurring?
i think so
Is this a problem in the vanilla unmodded game?
-

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Duplicate of #2742
