### ISSUE TITLE
CTD in Dev version

### ISSUE THREAD

**Issue by Captherky** [flybywiresim/a32nx#2775]
**Mod Version**

DEV Version from installer
{
  "built": "2020-12-28T07:17:38+00:00",
  "ref": "",
  "sha": "",
  "actor": "crisk73 <74656690+crisk73@users.noreply.github.com>",
  "event_name": "manual"
}

**Describe the bug**

CTD
Twice now.
One during climbout on SID from EGCC.
Once on Approach to EHAM.
No warning, sound stops sim CTD.

**To Reproduce**

1. Input SimBrief flight plan and set up all SimBrief weights and fuel load
2. Fly SID
3. CTD during climb to FL 120

**Expected behavior**

Continue climb to cruise alt.

**Actual behavior**

CTD before reaching climb to SONEX at fl120

**References**

**Additional context**

Latest FBW Dev mod
I use SimBrief for all MCDU plan.
I use Pilot2ATC for ATC.
I was not touching any controls before CTD

Was this working before/when did the issue start occurring?
CTD after latest FBW update (Dev)
I dont get CTD with the Stable release version.

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
FSUIPC (a framewoork used by Pilot2ATC) currently causes crashes on the latest MSFS and we cannot investigate the issue as FSUIPC is a proprietary, closed-source program we cannot debug easily. The issue lies on them to investigate.

**Comment by Captherky** [comment]
Thanks.
I am using FSUIPC7 to run Pilot2ATC. SO that’s the culprit eh?
I don’t see the CTD using the release version, so Ill try that again.
Cheers

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Benjozork** [comment]
> Thanks.
I am using FSUIPC7 to run Pilot2ATC. SO that’s the culprit eh?
I don’t see the CTD using the release version, so Ill try that again.
Cheers

Yes most likely.

It's unclear exactly what in the dev version, and since neither MSFS or FSUIPC gives useful info as to what causes crashes, we currently cannot do anything about it.

They are investigating the issue I believe. I will update if they communicate anything with us.

**Comment by Captherky** [comment]
Many thanks.
Hope something gets sorted. Pilot2ATC works great with the Neo in the sim.
Ill re fly in the release stable version and see if there are any issues!
Cheers.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by lekkerjonty** [comment]
i have just had this happen to me, i did not have fsuipc running at the time but i still have it installed on my computer. Do you think that's still the problem

**Comment by Captherky** [comment]
If FSUIPC7 wasn't loaded then no. My CTD's occurred after the latest Mod Dev upgrades. During SID and during STAR. So in the climb and descent.
I'm no beta tester, but I was getting around to trying the same route with the stable, release FBW version loaded. To see if I could replicate the CTD.
My route is EGCC to EHAM. POL5R SID and SUGOL into EHAM, done in SimBrief and everything loaded into the MCDU via SimBrief.

Could be SimBrief that's causing the CTD?

Needs further testing!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
