### ISSUE TITLE
No WHEEL page on touchdown

### ISSUE THREAD

**Issue by merryface** [flybywiresim/a32nx#278]
When you land in the real aircraft, <strike>F/CTL</strike> WHEEL page pops up so that you can see the spoilers being deployed. At the moment it stays on the engine page.

EDIT: Wheel page pops up when the gear comes down. I'm making a mess of my first submission. Sorry :/

<strike>Goes back to engine page at spoiler disarm.</strike>

**Comment by PCGamesF1Tech** [comment]
Hi,
After landing gear extension in approach the wheel page (not F/CTL) should show (real aircraft). 
There are horizontal line symbols on top of the page, above the wheels (older 320 family generations below) which show spoiler extension.
![Screenshot_20200831_145038](https://user-images.githubusercontent.com/39101086/91721816-a80a6a80-eb99-11ea-8529-d20f536e1610.jpg)

**Comment by merryface** [comment]
My mistake, yes, th wheel page not the f/ctl page. I'll change it

**Comment by PCGamesF1Tech** [comment]
The idea was neat however ;-)

**Comment by merryface** [comment]
the mistake was just me being a complete numpty. You'd think after 1100h I'd remember it was the wheel page and not the F/CTL, but noooo, my brain has to do dumb stuff :p

**Comment by PCGamesF1Tech** [comment]
Why did I even attach an image to show the situation before landing....? 😄👍🏻

**Comment by omarocasio** [comment]
Currently being worked on, hopefully I can get it in for next release if not it will be up on the dev branch on a pull request

**Comment by lukecologne** [comment]
Fixed with #603, can be closed I think
