### ISSUE TITLE
[BUG] TOD MISSING ON ND & NOT SHOWING IN MCDU

### ISSUE THREAD

**Issue by jetstarpilotmel** [flybywiresim/a32nx#2782]
**Mod Version**
<!-- Latest version
<!-- Developer Model

The TOP OF DESCENT ICON on ND is missing. TOD is missing in MCDU.

TOD icon should be visible on ND. "TOD" should display in the MCDU under FLT PLAN.

**Comment by hotshotp** [comment]
tod is not yet implemented. also not following template
