### ISSUE TITLE
[BUG] SIMBRIEF INTEGRATION... IN GAME ATC GIVES NO CLEARANCE TO CRUISE LEVEL

### ISSUE THREAD

**Issue by globinchen** [flybywiresim/a32nx#2793]
**Mod Version**
latest dev build 

**Describe the bug**
REFERING ALSO TO CLOSED ISSUE  #2522 
LOADED SIMBRIEF FLIGHT PLAN USING THE 320NX FMS INTEGRATION... ATC DOES NOT GIVE YOU CLIMB CLEARANCE TO CRUISE LEVEL FOR ENTIRE FLIGHT. 

**To Reproduce**
1. Choose departure airport in MSFS2020 main menu.
2. Load newly created flightplan from SIMBRIEF via the airplane FMS integration menu (at ramp). 
2. Obtain IFR clearance from ATC for the flightplan (SIMBRIEF) filed 
3. Follow instructions for initial climb... 

**Expected behavior**
Receive further climb clearance to cruise level after takeoff or after initial climb (departure, SID). 

**Actual behavior**
NAV data, etc all seems to be in from the plan (simbrief). ATC gives initial climb instructions somwhere between 7000 - 13000 feet but does not come back on further climb instruction for the flightlevel planned. 

**Additional context**
Was this working before/when did the issue start occurring?  I saw this with previous Dev builds as as well (got never resolved). 

Is this a problem in the vanilla unmodded game?  
No. Loading the same flightplan (from SIMBRIEF) in the MSFS2020 flight plan page prior enter the plane works fine with ATC instruction to flightlevel.

**Comment by nreyes90** [comment]
ATC can't read your flight plan via MCDU. IRL they can't and in the sim either. If you would like in-sim ATC to work you'd have to file your plan via main menu.

**Comment by Benjozork** [comment]
Sync between in-game flight plan and FMGC flight plan is not implemented, closing the issue.

You can open a feature request if you want that possibility, but please advise that due issues wit hthe MSFS flight plan system. it will probably not be implemented until that system is improved by Asobo.
