### ISSUE TITLE
[BUG] CSTR cannot be selected when in ILS mode on EFIS panel

### ISSUE THREAD

**Issue by ErikNL80** [flybywiresim/a32nx#2796]
**Mod Version**

  "built": "2020-12-29T18:35:45+00:00",
  "actor": "devsnek <me@gus.host>",
  "event_name": "manual"

**Describe the bug**

When I select the ILS mode for landing, I can have CSTR enabled. But when I disable it, I cannot enable it anymore in ILS mode. I have to switch the EFIS to another mode (NAV/ARC/PLAN) in order to enable CSTR again.

**To Reproduce**

1. Go to the EFIS panel
2. Set mode to ARC
3. Enable CSTR
4. Set mode to ILS
5. Disable CSTR
6. Try to enable CSTR again in ILS mode

**Expected behavior**

I would expect the CSTR to enable/disable at any time at any mode.

**Actual behavior**

CSTR will not enable when ILS is selected on the EFIS.

**References**

**Additional context**

![BUG](https://user-images.githubusercontent.com/71258178/103314242-c470c380-4a22-11eb-89c7-2b16a0fb1b50.png)

Was this working before/when did the issue start occurring?
Yes, think it broke after fix [#2555](url=https://github.com/flybywiresim/a32nx/commit/1008830ba3b6cd8e4f18f4893af40d183886759b)

Is this a problem in the vanilla unmodded game?
N/A

**Comment by andrejetcat** [comment]
The CSTR - button only enables Constrains to the waypoints etc. IRL in the ILS Mode, the plan is not active while you are in the ILS mode, so you can´t enable any CSTR. 
It worked before because there was an issue, that the plan was shown also in ILS mode, which is not accurate.

**Comment by hotshotp** [comment]
Working as intended
