### ISSUE TITLE
[BUG] Causes Asobo 747-8i MCDU/FMC screens to be black

### ISSUE THREAD

**Issue by munib94** [flybywiresim/a32nx#2802]
**Mod Version**

Latest stable release version (0.5.1)

**Describe the bug**

The A32NX mod causes the Asobo 747-8i MCDU/FMC screens to go black.

**To Reproduce**

1. Make sure A32NX mod is installed
2. Spawn cold start at the gate with default livery
3. Proceed through normal startup procedure

**Expected behavior**

747-8i MCDU/FMC screens should not be black

**Actual behavior**

747-8i MCDU/FMC screens are black, making them unusable

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Not sure when it started since I only just started flying 747-8i

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):

**Comment by wpine215** [comment]
Fixed in development version.

**Comment by munib94** [comment]
Ok, thank you.
