### ISSUE TITLE
Not calculating airspeeds

### ISSUE THREAD

**Issue by wftinmn** [flybywiresim/a32nx#2805]
This started after 0:5,1. I must be making an obvious mistake, but for the life of me, can’t figure out what it is.  Imported FP from Simbrief. After going through the init and perf, the flightplan shows all the waypoints, times and altitudes but there are no speeds associated with it - therefore, no managed speeds in autopilot. All of the altitude have an asterisk next to them.
In addition, I entered 134.2 as ZFW, 20.4 block, yet it calculates TOW as 131:2.
I have emptied the community folder of everything else, using lbs rather than kg as unit of measure, using a CI of 30.
Where have I gone astray?

**Comment by Benjozork** [comment]
Please do not remove the provided template.

**Comment by wftinmn** [comment]
Sorry, but I don’t know what template you are referring to. I followed the same steps that I have used all along, and it all seemed to work before the last update.
