### ISSUE TITLE
[REQUEST] Delete ATC Flight Number "1123"

### ISSUE THREAD

**Issue by MariusSchuller** [flybywiresim/a32nx#2807]
**Is your feature request related to a problem? Please describe.**
- Problem: ATC uses wrong callsign
- When using the MSFS2020-ATC with an own ATC-flight-number, "1123" is always added
- e.g. when I fly with a Lufthansa livery and pre-define the ATC callsign as "1111" in the menu, ATC calls me with "Lufthansa 1111 1123".
- If I don't pre-define an ATC callsign, ATC just calls "Lufthansa 1123"

**Describe the feature you'd like to see implemented**
- From my point of view it would be very helpful, if you'd delete the ATC callsign of 1123
- A320NX -> SimObjects -> AirPlanes -> Asobo_A320_NEO -> aircraft.cfg
- In aircraft.cfg, delte the "1123" in the parameter "atc_flight_number" for the [FLTSIM.0] model

**References**
- not required

**Additional context**
- I do know that I could delete the ATC flightnumber everytime a new version of the mod is released, but maybe not everyone reads through the .cfg files.
- btw: awesome work on the mod, I really do appreciate it! :-)

**Comment by Benjozork** [comment]
Hey - can you confirm that when you select your plane, you set "Lufthansa" in callsign and the flight number in flight number ? If you put everything in callsign, it will use the 1123.

**Comment by MariusSchuller** [comment]
Hey Benjamin,

aaaah busted - user error!

For all who stumble across this issue as well:
- Callsign is just the airline code (https://www.vatsim.net/pilot-resource-centre/general-lessons/choosing-callsign)
- Flight number adds the light number

Well, the more you know ;-)
