### ISSUE TITLE
[REQUEST] Implementation Of Weight And Balance Tool

### ISSUE THREAD

**Issue by MariusSchuller** [flybywiresim/a32nx#2808]
**Is your feature request related to a problem? Please describe.**
- More an inconvenience than a problem
- Setting the weights for business & economy class and forward & rear baggage in MSFS2020 is very inconvenient:
      - masses are in lb (or even gal for fuel)
      - one has to calculate the masses, there is no "easy" input like "number of passengers"
      - once one has calculated the masses, one has to push the masses back and forth in the search of an optimized center of gravity

**Describe the feature you'd like to see implemented**
- Easy and convenient tool that automatically caluclates the payload and the distribution of the baggage to reach a target CG
- Inputs
    - Passengers in business class [-]
    - Passengers in economy class [-]
    - Crew [-]
    - Block fuel [t]
    - Target center of gravity [% MAC]
- Outputs
    - Payload business class [lb]
    - Payload economy class [lb]
    - Payload forward baggage [lb]
    - Payload rear baggage [lb]
    - Zero fuel weight [t]
    - Zero fuel weight center of gravity [% MAC]
    - Percentage to which the tanks have to be filled [%] (for the slide-control in MSFS)

**References**
- I highly doubt that pilots are busy trying to distribute the baggage without using a tool
- Survey on weights of passengers and baggage: https://www.easa.europa.eu/sites/default/files/dfu/Weight%20Survey%20R20090095%20Final.pdf

**Additional context**
- Here comes the best part: I already figured out the math, implemented the tool as described in Excel and tested it several times (see picture below)
- I am very happy to share the Excel to developers so that they can simply copy the calculations
- I am not sure where exactly we could implement this - I guess in the MCDU does not make too much sense. Maybe there will be a tablet implemented in the future?

Screenshot of already implemented Excel-Tool:
![A320WeightsAndBalance](https://user-images.githubusercontent.com/76614781/103366087-f2f1ab80-4ac1-11eb-9d6d-3920e4e1d0be.PNG)

**Comment by MisterChocker** [comment]
probably implemented EFB

**Comment by sidnov** [comment]
The current W/B implementation on the MCDU is ready to use on both dev and experimental, and an interface for this is also planned on the EFB. The calculations mentioned above though wouldn't be of much use given the weight variant we have chosen for the A32NX.
