### ISSUE TITLE
Unable to manually enter constraints and V-speeds

### ISSUE THREAD

**Issue by larrydingus** [flybywiresim/a32nx#281]
MCDU does not allow you to manually enter altitude and airspeed constraints for the route. Also when entering a flight plan in manually (not making one in the MSFS world map) no altitudes or airspeeds appear, it is just appears as ---/". Same with V-speeds, not able to enter them in manually and it appears that they only change when the flap lever changes flap settings rather than when entering a flap setting on the MCDU.

**Comment by UncleClapton** [comment]
VSpeeds will be addressed in #557. I will be looking into constraints as well soon, but that seems to be a much larger problem than vspeeds were.
