### ISSUE TITLE
[BUG] ND stuck on ILS mode

### ISSUE THREAD

**Issue by Tzoreol** [flybywiresim/a32nx#2810]
**Mod Version**
0.5.0

**Describe the bug**
The Navigation Display is stuck in ILS mode. I'm not able to change mode or range.

**To Reproduce**
1. Turn on batteries and ground power
2. Align IRS and wait 7mn
3.

**Expected behavior**
When turnign range knob, I expect the navigation display to update.
Same thing with the ND mode knob.
I also expect to see next waypoint informations in top right corner

**Actual behavior**
No change on Navigation Display when turning either knob.
"ILS" is display in top center.
"ILS ___.___" and "CRS ____" are in top right corner

**References**

![image](https://user-images.githubusercontent.com/1432830/103372276-dd847d80-4ad1-11eb-93fe-a32948dd2bc9.png)

**Additional context**

Was this working before/when did the issue start occurring?
Works perfectly with prior version. I tried with base A320 afeter deleted package and it also works perfectly. Issue is still there afer reinstall

Is this a problem in the vanilla unmodded game?
No.

Discord username (if different from GitHub): Tzoreol

**Comment by Tzoreol** [comment]
Closing this one. Duplicate after an issue on github

**Comment by Benjozork** [comment]
Gonna close as you made two issues.
