### ISSUE TITLE
[BUG] Navigation Display stuck in ILS mode

### ISSUE THREAD

**Issue by Tzoreol** [flybywiresim/a32nx#2811]
**Mod Version**
0.5.0

**Describe the bug**
The Navigation Display is stuck in ILS mode. I'm not able to change mode or range.

**To Reproduce**
1. Turn on batteries and ground power
2. Align IRS and wait 7mn
3.

**Expected behavior**
When turnign range knob, I expect the navigation display to update.
Same thing with the ND mode knob.
I also expect to see next waypoint informations in top right corner

**Actual behavior**
No change on Navigation Display when turning either knob.
"ILS" is display in top center.
"ILS ___.___" and "CRS ____" are in top right corner

**References**

![image](https://user-images.githubusercontent.com/1432830/103372276-dd847d80-4ad1-11eb-93fe-a32948dd2bc9.png)

**Additional context**

Was this working before/when did the issue start occurring?
Works perfectly with prior version. I tried with base A320 afeter deleted package and it also works perfectly. Issue is still there afer reinstall

Is this a problem in the vanilla unmodded game?
No.

Discord username (if different from GitHub): Tzoreol

**Comment by Benjozork** [comment]
Hello, version 0.5.0 is not compatible with the current version of the simulator.

Version 0.5.1 is compatible, but I recommend you try the development version as we made fixes to the ND.

Can you try and report back ?

**Comment by DominikTV** [comment]
Had the same issue (newest version). I fixed it by changing the livery (I had the new Alpha/Beta Tester exclusive livery selected). Also the FO PDF and navdisplay are white in this livery.

**Comment by Benjozork** [comment]
> Had the same issue (newest version). I fixed it by changing the livery (I had the new Alpha/Beta Tester exclusive livery selected). Also the FO PDF and navdisplay are white in this livery.

Indeed those liveries are not compatible, as outlined in the known issues for the relwasem

**Comment by Tzoreol** [comment]
Hi all!

First of all, thank you for the quick answers ;)
After checking, it is the last version 0.5.1.

As recommanded I used another livery than the black alpha/beta tester livery. Just a quick try but it seems to work well.
I'll try deeper tomorrow.

**Comment by Tzoreol** [comment]
I can confirm the alpha/beta tester livery is bringing this problem. This issue can be closed
