### ISSUE TITLE
Managed descent profile / FLC 

### ISSUE THREAD

**Issue by bdpd1** [flybywiresim/a32nx#2812]
**Mod Version**
{
  "built": "2020-12-29T18:35:45+00:00",
  "ref": "",
  "sha": "",
  "actor": "devsnek <me@gus.host>",
  "event_name": "manual"
}

**Describe the bug**
Managed descent working like open descent.  

**To Reproduce**
1.  Start C&D; simbrief flight plan from KDCA to KLGA.  No selection of routing beside start location from Welcome / MAP main menu.  Arrival is KORRY3.  Navdata is navigraph beta 2013 rev 7. 
2.  Adjust KORRY3 fix altitude crossing restrictions to match the charted altitude crossing restrictions.  
3.  Entered target altitude of 10000 (KORRY restriction); altitude contraints on ND are depicted correctly.  

**Expected behavior**
After engaging managed descent, I would expect magenta intermediate altitude constraints to be shown and VNAV path to be adjusted according to the entered or database driven constraints on the SID/STAR or Approach as applicable. 

**Actual behavior**
No magenta intermediate altitude shown on PFD.  PFD only showing blue 10000 (as if in open descent mode).   A/P blows through altitude constraints and descends according to open descent. 

**References**
![image](https://user-images.githubusercontent.com/74915905/103372736-d729dd80-4aa0-11eb-879d-399cbf3a91de.png)
![image](https://user-images.githubusercontent.com/74915905/103372762-e9a41700-4aa0-11eb-8139-49ae61f6cfa4.png)
![image](https://user-images.githubusercontent.com/74915905/103372781-fd4f7d80-4aa0-11eb-9b3b-381493636527.png)

**Additional context**

Was this working before/when did the issue start occurring?
Working before. 

Is this a problem in the vanilla unmodded game?
Alt constraint revisions are not modeled in the vanilla as I recall 

Discord username (if different from GitHub):  nnumber

**Comment by GlitchedYT** [comment]
Hi @bdpd1,

This is a known issue that will be fixed when we have our custom Autopilot out that's being worked on by @aguther. If you would like to stay up to date on the progress of it view the "#autoflight" text channel under the "#Systems" category.

Due to this being a know issue I will be closing this for the time being.
