### ISSUE TITLE
[BUG] ALT in progress page not working propperly

### ISSUE THREAD

**Issue by mikecbr** [flybywiresim/a32nx#2816]
**Mod Version**
Latest branch

**Describe the bug**
Sometimes , not always when i set a cruise ALT 360 for example and i want to go higher late in the flight if i go to FL390 , the aircraft in the progress page does not recognize the altitude 

**To Reproduce**

1.
2.
3.

**Expected behavior**
Work as expected 

**Actual behavior**
Not showing actual altitude 

**References**
Actual FL 390
![image](https://user-images.githubusercontent.com/74787268/103380558-87bbcf80-4ae9-11eb-8be5-84cdf1261f2b.png)

![image](https://user-images.githubusercontent.com/74787268/103380582-96a28200-4ae9-11eb-8ec9-691a39dc1bb5.png)
Progress page 

INIT PAGE FL390 
![image](https://user-images.githubusercontent.com/74787268/103380599-a752f800-4ae9-11eb-8306-edba96116bf3.png)

And also in the flight plan is showing me FL390 in the points

**Additional context**

Was this working before/when did the issue start occurring?
Not sure

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment]
Please fill `To Reprodue` in order to us to check on how to reproduce the bug.

**Comment by MisterChocker** [comment]
Closing since no response from op.
