### ISSUE TITLE
FOB/fuel on board in single digits is wrong

### ISSUE THREAD

**Issue by PCGamesF1Tech** [flybywiresim/a32nx#283]
Fuel on board indication (FOB) is showing an accuracy in single digit kilograms, e.g. 8947kg.

This is wrong, it should be in increments of 20kg, so e.g. 8940kg.

**Comment by Th3Falc0n** [comment]
Working on this.

**Comment by PCGamesF1Tech** [comment]
Phew, that was quick, thanks for your effort! 👍🏻
Is it 10kg? I don't have my Laptop/OM with me on vacation

**Comment by JackZ974** [comment]
Noticed also a discrepancy between Fuel USED between Engines page and FUEL page.  The values shown are different. 
Working on it

**Comment by Th3Falc0n** [comment]
@Curtis-VL this is solved in #287 awaiting the PR to merge

**Comment by NathanInnes** [comment]
Do you have a reference to confirm this behaviour at all?

**Comment by AdenFlorian** [comment]
reference: https://www.youtube.com/watch?v=g32B8_5TbdQ

**Comment by Th3Falc0n** [comment]
I get following things from the video:

All "fuel amounts available" in 20kg increments.
All "fuel amounts used" in 10kg increments.

I will implement that and create a new PR.
