### ISSUE TITLE
[BUG] Arc would not engage in MSFS 2020

### ISSUE THREAD

**Issue by davidbuckleyni** [flybywiresim/a32nx#2830]
Hi no matter what I would do inside msfs 2020 I could not get the arc mac to engage on my sim even though all controls was switced to arc and nav. I put in a flight plan with my friend from.
MSFS Version.

1.1.13.0

MFDS Displays

![image](https://user-images.githubusercontent.com/5619229/103426834-39273780-4bb4-11eb-8ae1-ef2c746a9c3b.png)

Main Flight Panel

![image](https://user-images.githubusercontent.com/5619229/103426841-49d7ad80-4bb4-11eb-8e02-b7fd8d1b585e.png)

Top Panel

![image](https://user-images.githubusercontent.com/5619229/103426848-5e1baa80-4bb4-11eb-8bcb-d146630c40a4.png)

**Comment by hotshotp** [comment]
Hello, any mods you have installed? They sometimes conflict with the a32nx causing similar issues

**Comment by MisterChocker** [comment]
@davidbuckleyni Please follow the template provided.

**Comment by davidbuckleyni** [comment]
What template provided their no instructions in the zip file

**Comment by Benjozork** [comment]
When you open an issue there is a template given to you, you deleted it.

**Comment by MisterChocker** [comment]
@davidbuckleyni please open a new issue and follow the template.
