### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by medhat8989** [flybywiresim/a32nx#2832]
Hi I have problem never happened before to me ..when I try load the file from simbreif and I go to put my username in options,aoc,simbrief username and when I go in atsu,aoc menu,init/pres and when I press on init data req don't show me nothing and when I go in page init I press in init request don't show me nothing  he said not allowed and this is never happened before I was load the file from simbreif and I start Flight i go in Page init without I go in options and all this stuff now nothing works for me ![IMG_20210101_115742.jpg](https://user-images.githubusercontent.com/68558289/103436855-f489b380-4c28-11eb-8690-f4039411e730.jpg)![IMG_20210101_115742.jpg](https://user-images.githubusercontent.com/68558289/103436875-403c5d00-4c29-11eb-875c-5b244f296690.jpg)![IMG_20210101_120302.jpg](https://user-images.githubusercontent.com/68558289/103436878-51856980-4c29-11eb-92d7-ba50e1750fb7.jpg) please I need your help guys I'm now for 3days I can't do one flight I uninstalled the mfs and I downloaded agine still the same problem I installed New windows 10 but still some problem help thank you.

**Comment by ianhaw** [comment]
> Hi I have problem never happened before to me ..when I try load the file from simbreif and I go to put my username in options,aoc,simbrief username and when I go in atsu,aoc menu,init/pres and when I press on init data req don't show me nothing and when I go in page init I press in init request don't show me nothing he said not allowed and this is never happened before I was load the file from simbreif and I start Flight i go in Page init without I go in options and all this stuff now nothing works for me ![IMG_20210101_115742.jpg](https://user-images.githubusercontent.com/68558289/103436855-f489b380-4c28-11eb-8690-f4039411e730.jpg)![IMG_20210101_115742.jpg](https://user-images.githubusercontent.com/68558289/103436875-403c5d00-4c29-11eb-875c-5b244f296690.jpg)![IMG_20210101_120302.jpg](https://user-images.githubusercontent.com/68558289/103436878-51856980-4c29-11eb-92d7-ba50e1750fb7.jpg) please I need your help guys I'm now for 3days I can't do one flight I uninstalled the mfs and I downloaded agine still the same problem I installed New windows 10 but still some problem help thank you.

I have exactly the same issue with Simbrief not loading into the MACDO and have given up unless anyone can help too!

**Comment by ianhaw** [comment]
I have exactly the same issue with Simbrief not loading into the MACDO and have given up unless anyone can help too!

**Comment by medhat8989** [comment]
> I have exactly the same issue with Simbrief not loading into the MACDO and have given up unless anyone can help too!

Ok brother if u know samthing plzzzzz let me know brother I'm 3 days man I can't do flight I did everything 😭. Add me in discord man and tell me if u know Samthing  (medhat2020#6917).  And I hope they help us

**Comment by MapleNAV-TCASFAULT** [comment]
1. You’re not supposed to ask for help here
2. You enter your username not flight number, I’m guessing that Alitalia 89 is the flight number and not username

**Comment by Benjozork** [comment]
GitHub is not for support, please use the #help channel in the discord. Also, do not ignore the provided issue template.

**Comment by medhat8989** [comment]
> 1. You’re not supposed to ask for help here
> 2. You enter your username not flight number, I’m guessing that Alitalia 89 is the flight number and not username

No it's username not flghit number
