### ISSUE TITLE
[REQUEST] Allow for loading a new flight plan after landing

### ISSUE THREAD

**Issue by angry-bender** [flybywiresim/a32nx#2833]
**Is your feature request related to a problem? Please describe.**
Related to a problem where you can't clear a flight plan.

**Describe the feature you'd like to see implemented**

I'd like to be able to clear the loaded flight plan after landing, and request a new one from simbreif to fly a new leg.

**References**
None

**Additional context**
N.A

Discord username (if different from GitHub):same as github

**Comment by ThatRedMelon** [comment]
This is possible already if you request init from the ATSU INIT page after landing

**Comment by tracernz** [comment]
Implemented in https://github.com/flybywiresim/a32nx/pull/2593

**Comment by angry-bender** [comment]
Awesome, thanks for that, I couldn't quite figure it out from the doco
