### ISSUE TITLE
[BUG] No error message when entering trip wind in wrong format

### ISSUE THREAD

**Issue by jordankasper11** [flybywiresim/a32nx#2837]
**Mod Version**
Dev branch
```
{
  "built": "2020-12-31T18:05:31+00:00",
  "ref": "",
  "sha": "",
  "actor": "Brooke McKim <brookemckim@users.noreply.github.com>",
  "event_name": "manual"
}
```

**Describe the bug**
I generated an OFP from SimBrief that gives an AVG W/C of P031. If I try to enter P031, P31, 031, or 31, and then press the TRIP WIND button, the value stays the same and the entry line is cleared without any error message. I found out from the Discord that this should be in the format TL031, which the FMC accepts, but there should probably be an error message when entering in the incorrect format. It _does_ display an error message of "ENTRY OUT OF RANGE" if an unrealistic amount of wind is entered, such as T300.

**To Reproduce**

1. Go to INIT FUEL PREDICTION page in FMC (second INIT page)
2. Enter P031 on the keypad
3. Click the TRIP WIND button

**Expected behavior**
I'm not sure what the correct error message would be for this system (maybe ENTRY OUT OF RANGE or INVALID FORMAT?), but there should be some indication that you've entered a bad value.

**Actual behavior**
The value disappears from the entry line but the TRIP WIND value does not change.

**References**
N/A

**Additional context**
N/A

**Comment by MisterChocker** [comment]
cc @Lucky38i
