### ISSUE TITLE
[BUG] Bad flight level in STAR

### ISSUE THREAD

**Issue by fralbo** [flybywiresim/a32nx#2839]
**Mod Version**
Last development version downloaded on 01/01/2021 with downloader

**Describe the bug**
Bad altitude constraints on several points and no TOD defined on this arrival.

**To Reproduce**
Select LFRB ANLEV8C STAR, RNAV07R VIA RB500

**Expected behavior**
Correct flight levels and computed TOD

**Actual behavior**
SOPEX gives a FL60 constraint and DECEL 32 NM later gives FL360

**References**
![2021-01-02 13_34_26-Microsoft Flight Simulator - 1 12 13 0](https://user-images.githubusercontent.com/15524105/103457529-684abf80-4d00-11eb-881e-ff5917c1dacf.png)

And again later

![2021-01-02 13_46_02-Microsoft Flight Simulator - 1 12 13 0](https://user-images.githubusercontent.com/15524105/103457602-ffb01280-4d00-11eb-9ea3-ea4fc31cc873.png)

And also before in fact:

![2021-01-02 13_48_15-Microsoft Flight Simulator - 1 12 13 0](https://user-images.githubusercontent.com/15524105/103457649-4e5dac80-4d01-11eb-82a7-593927f8ba87.png)

**Additional context**

Was this working before/when did the issue start occurring?
RNAV approaches weren't supported

Is this a problem in the vanilla unmodded game?
I don't know

LIT037

**Comment by tareksabet** [comment]
it should be fixed soon 
thanks for reporting this issue.

**Comment by 2hwk** [comment]
Fixed by 4953 closing ☑️
