### ISSUE TITLE
[BUG] FMS doesn't show right AIRAC Cycle

### ISSUE THREAD

**Issue by fralbo** [flybywiresim/a32nx#2846]
**Mod Version**
0.5.1

**Describe the bug**
AIRAC cycle 2014 rev1 installed but FMS still display 03DEC - 30DEC date

**To Reproduce**
Use Navigraph to installed last available AIRAC cycle

**Expected behavior**
display January AIRAC cycle

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Not Sure

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by kiokio0987** [comment]
It seems that NAVBLUE in msfs2020 has not been updated yet. We will have to wait for an update.
https://forum.navigraph.com/t/update-airac-cycle-in-a320x-msfs-flybywire-mod/3345

**Comment by Lucky38i** [comment]
I'm assuming you installed a navigraph airac? If so then the MCDU won't show anything new, that text is hard coded. @kiokio0987 The navblue data was updated about a month ago so it's up to date.

**Comment by fralbo** [comment]
Ok many thanks for your answer and thanks for the forum link
