### ISSUE TITLE
APU start switch is too slow to be available.

### ISSUE THREAD

**Issue by lrargerich** [flybywiresim/a32nx#285]
Maybe we have another issues open for this one:

I've been watching a few streams, some from real pilots and I have collected the following comments:

(from real Airbus Pilot): The APU does not need the flap to be open to turn on, you can press the start APU switch aboput 3 seconds after turning on the master switch.

(from streammers and users): This is broken, it takes too long, etc.

So for both realism and usability I think the APU on switch should just wait about 3 seconds to become available after the master switch is turned on.

**Comment by ukflyer** [comment]
i think this has been addressed in the latest dev files
i'm able to select APU start soon after the master switch, APU then becomes avail a few minutes after that.

**Comment by lrargerich** [comment]
Ah sorry I tested the dev version last night and it was still slow.
If it has been fixed then this can be closed and buried!

**Comment by ukflyer** [comment]
no problem try the latest dev files, should be good - just tried it at the gate at AMS :)

**Comment by lrargerich** [comment]
I'm ready to close this but there's still a minor glitch: the tooltip for the APU start switch still says "unavailable" even if the switch can be pressed.

**Comment by Curtis-VL** [comment]
Oh, this is a known bug with the tooltips.

**Comment by Curtis-VL** [comment]
Could you possibly close this issue and makea new one for the tool tip issue so it's easier for people looking through the issues?

**Comment by AdenFlorian** [comment]
this is fixed in master, this issue tracks the tooltip issue: https://github.com/flybywiresim/a32nx/issues/252
