### ISSUE TITLE
[BUG] Cannot cross altitude constraint in selected mode

### ISSUE THREAD

**Issue by fralbo** [flybywiresim/a32nx#2856]
**Mod Version**
0.5.1

**Describe the bug**
Don't really know if it's a bug but I don't encounter the problem in x-Plane, the plane don't want to cross an altitude constraint, even setting a negative vertical speed.
The problem is that lower altitude was requested by ATC!

**To Reproduce**
From an altitude constraint, set lower altitude and negative vertical speed.

**Expected behavior**
descent

**Actual behavior**
remains at altitude constraint

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
don't know never use it!

Discord username (if different from GitHub): LIT037

**Comment by tareksabet** [comment]
ALT CSTR have some problems these days, it will be fixed very soon.

Also quick question were you in managed mode ( a big dot should be on the right side of the ALT )
but if in selected ALT it should work fine.

**Comment by fralbo** [comment]
Hello @tareksabet,
I'm surprised by your question because I think that the bug on the right side of ALT is managed by the vertical profile and maybe also by the TOD computation. But AFAIK, both these features are still not implemented, even in dev version and I never saw them displayed.
So?

**Comment by tareksabet** [comment]
The idea that if in managed mode it would respect the ALT CSTR but it's not always correct so I put it in selected mode. Also the autopilot has a lot of issues which it is being fixed by our new custom auto pilot which it is a WIP.

**Comment by lukecologne** [comment]
This has been fixed in the latest version, selected modes should now properly ignore constraints.
