### ISSUE TITLE
[BUG] Airspeed disappears during initial climb and decent

### ISSUE THREAD

**Issue by CapTainBeardy** [flybywiresim/a32nx#2858]
**Mod Version**
 the latest Custom FBW - happens with Stable, Dev and Custom

Custom Version
{
  "built": "2020-12-23T05:49:09+00:00",
  "ref": "",
  "sha": "",
  "actor": "Benjamin Dupont <benjozorkfr@gmail.com>",
  "event_name": "manual"
}

DEV Version 
{
  "built": "2021-01-02T20:38:01+00:00",
  "ref": "",
  "sha": "",
  "actor": "Ronson1909 <Ronson1909@users.noreply.github.com>",
  "event_name": "manual"
}

**Describe the bug**

When I am climbing out on flights, the airspeed suddenly goes as if it was a TBM / Cessna and the pitot was frozen.  I am using anti ice - also tried without no difference.  Happens also on decent, until 2500ft when it comes back alive.  When this happens the auto throttle is on 91% and the aircraft is flying fast.  I also had the engines spool up and down in cruise but the IAS was still live.  This has happened in the latest stable, dev and custom mentioned above.  Though the custom having the least issues.   On discord some helpful people tried to rectify the issue and we tested a couple of things as I recorded it.  Found it out comes back at 2500ft. 

https://www.youtube.com/watch?v=18ykxr7bcJY

at -38 mins start watching we are testing a bunch of things for a good 10-15 minutes.  Towards the end you can see how it comes back at 2500 then I climb and descend again to test it a few times.   Other aircraft mods uninstalled only using Gatwick scenery and easyjet livery - tested also without these and same issue.  

https://www.youtube.com/watch?v=RG6NTFbY9pw&t=2372s This one is with Dev build - 39 mins in you can see.

**To Reproduce**

1. Cold and dark start flight 
2. watch during intial climb and during decent until 2500ft
3.

**Expected behavior**

Airspeed to show as normal

**Actual behavior**

No airspeed show, GS and MACH still working - see video

**References**

https://www.youtube.com/watch?v=18ykxr7bcJY
https://www.youtube.com/watch?v=RG6NTFbY9pw&t=2372s 39 mins 

**Additional context**

Was this working before/when did the issue start occurring?
Working fine up until around 2 weeks ago

Is this a problem in the vanilla unmodded game?
Tested it with vanilla a320 and reinstalled a320 and no issues.  

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Saschl** [comment]
Hi, are you using any peripherals that have switches assigned to the anti-ice system (specifically pitot heat)?

**Comment by CapTainBeardy** [comment]
This was indeed the case! Thank you so much! 

Honeycomb bravo automatically mapped Pitot heat as off (didn’t know this was an option on the A320)

**Comment by MisterChocker** [comment]
Okay thanks closing since issue solved which accrued due to hardware key bind disabling Pitot heater.
