### ISSUE TITLE
When climbing in selected Altitude, the v/s gets disabled when altitude is being increased

### ISSUE THREAD

**Issue by ChruutvoLuzi** [flybywiresim/a32nx#286]
resulting in nose pitching up immensly (up to +5000fpm) due to the faulty ap 

idk if it has to be like that but it is very weird

**Comment by Curtis-VL** [comment]
Hi there,

If I recall, vertical speed doesn't affect selected altitude right now in the default aircraft or the mod!
So you can either be in selected altitude mode, or, vertical speed mode.

This is something I'd like to change, but I need to dig into it and see if the autopilot can support it. 👍

**Comment by Curtis-VL** [comment]
Hi there,

I've just reproduced this issue, will look into a solution for it!

**Comment by ChruutvoLuzi** [comment]
Update: also happens when the aircraft flies to a new waypoint

**Comment by AdenFlorian** [comment]
Was this a bug introduced by the mod, or was it already a problem in the vanilla unmodded version of the game?

**Comment by ChruutvoLuzi** [comment]
I think its from Vanilla but i am not 100% sure. Need confirmation on that

**Comment by JasonO99** [comment]
From my understanding both vanilla and this aircraft climb using a maximum VS, I imagine based on it maintaining the relevant speed? Changing the VS only seems to reset it.
