### ISSUE TITLE
747-8 fmc not working when 0.5.0 is installed[BUG] INSERT TITLE HERE

### ISSUE THREAD

**Issue by riderfan3169** [flybywiresim/a32nx#2860]
**Mod Version**
 0,5,0

**Describe the bug**
 when this is installed for the a320 the 747-8 fmc will not work delete 0,5,0 begins working again not sure how this is connected but there are many people in other forums having the same issue once 0,5,0 is deleted the fmc on the 747-8 begins working again

**To Reproduce**

1. install 0,5,0 into community folder and the issue begins
2.
3.

**Expected behavior**

the fmc in the 747-8 stops working

**Actual behavior**

the fmc in the 747-8 stops working
**References**

**Additional context**
 i am not sure how this effects the 747-8 but somehow it does. when this update is removed it works fine when istalled it comes back.

Was this working before/when did the issue start occurring? began when i installed the flybywire a320 0.5.0 update

Is this a problem in the vanilla unmodded game? no when the 0,5.0 is removed the issue resolves

Discord username (if different from GitHub): riderfan3169

**Comment by Benjozork** [comment]
0.5.0 is not the supported latest version. Closing.

Furthermore, your issue is resolved in the development version, and soon to be released 0.5.2.

**Comment by riderfan3169** [comment]
i apologize i thought it was the latest version sorry

**Comment by riderfan3169** [comment]
Sorry Benjamin. I apologize i thought it was the newest version. Thanks for the info and sorry for the inconvience Thanks for replying and the great work younl guys are doingChris Sent from my Galaxy
-------- Original message --------From: Benjamin Dupont <notifications@github.com> Date: 2021-01-03  16:01  (GMT-06:00) To: flybywiresim/a32nx <a32nx@noreply.github.com> Cc: riderfan3169 <cisted3169@sasktel.net>, Author <author@noreply.github.com> Subject: Re: [flybywiresim/a32nx] 747-8 fmc not working when 0.5.0 is installed[BUG] INSERT TITLE HERE (#2860) 
0.5.0 is not the supported latest version. Closing.
Furthermore, your issue is resolved in the development version, and soon to be released 0.5.2.
