### ISSUE TITLE
[BUG] Cruise speed oscillating between 170 and 290 when reaching cruise altitude in managed mode.

### ISSUE THREAD

**Issue by jmihalich** [flybywiresim/a32nx#2864]
**Mod Version**

master

{
  "built": "2021-01-03T01:18:30+00:00",
  "ref": "",
  "sha": "",
  "actor": "Benjamin Dupont <benjozorkfr@gmail.com>",
  "event_name": "manual"
}

**Describe the bug**

I was doing a flight from KLAX - KLAS.  25R ORCKA5 departure MISEN transition, into KEPEC6 arrival MISEN transition into ILS 01L.  Fully programmed the MCDU.  Init page was set to Cruise Alt FL290.  Perf takeoff page set to flaps 1, Flight plan set as specified.  Cost Index 30. Weather was set to live weather, and time set to 9am.  there were fog, and clouds present.

I took off on 25R turned left, and did a managed climb to cruise altitude via the SID.

When i reach cruise altitude, The cruise speed kept oscillating between 170 and 290 on the speed tape.  If i looked at the cruise perf page, the speed was changing between *170 and *290.  You can see this behavior in the video in this link:

https://www.youtube.com/watch?v=1v-3bZlko_k

**To Reproduce**

1. program MCDU as specified above ( i used the default fuel/weight numbers when programming the Init B page)
2.set weather/time (not sure if this has anything to do with it.  On the help discord, someone said it might have to do with clouds being present,
3.follow sid, climb to cruise in managed mode (speed, heading, and altitude), experience speed oscillation at cruise.

**Expected behavior**

Managed speed to be set to the value calculated, for the cost index. (~290 kts)

**Actual behavior**

Managed speed setting oscillates between 170 and 290 kts.

**References**

Video of issue here:
https://www.youtube.com/watch?v=1v-3bZlko_k

**Additional context**

Was this working before/when did the issue start occurring?

This has been an issue in the master builds for at least the last week at time of this posting.

Is this a problem in the vanilla unmodded game?
don't know, haven't trying stock 320.

Discord username (if different from GitHub):
TheJoe88

**Comment by depthvader** [comment]
have been having the same issue on descents, once it gets near 10k feet it keeps fluctuating from 288 to 250

**Comment by Watsi01** [comment]
Thanks for your video and you description. I not sure if it helps, but it does clear up some things. The problem is, that I never (never) experienced this issue. And it's hard to find out what the issue is here. As always:
 - could you check, if the issue still appears,  when no other mod, livery or external tool (using simconnect) is installed / in use.

**Comment by rodkay** [comment]
Upon watching your video do you believe it may be related to the fact the aircraft was dealing with turbulence?

**Comment by Watsi01** [comment]
@rodkay Turbulences should not interfere with crz speed at all (...should). Also the turbs here are not very heavy.

**Comment by jmihalich** [comment]
This is 100% repeatable every time on my side with the same route.  I'm not sure how you cannot reproduce it.  I don't have any other add ons (nothing in the community folder) other than this 320 mod.

**Comment by jmihalich** [comment]
also, yeah I realize i didn't have the baro set to std.  I just repeated the flight again, and did set it to std and it did the same thing.

**Comment by jmihalich** [comment]
The last time i tried it, if i set the speed to selected mode, the system honored the speed i set manually and stayed there without any problems.

**Comment by rodkay** [comment]
> @rodkay Turbulences should not interfere with crz speed at all (...should). Also the turbs here are not very heavy.

Just throwing some ideas/observations into the pot  😀

**Comment by Watsi01** [comment]
@jmihalich By the way. Did you see that you have a speed restriction on ORCKA5 at ORCKA of 210kts?

**Comment by donstim** [comment]
Okay, did the flight and found the issue.  @Watsi01 hit the nail on the head. There are speed restrictions programmed in the CDU of 210 knots at both COOPP and ORCKA for that departure procedure (although I don't see the speed restrictions on the chart). Evidently, there is a "fight" going on in managed speed/altitude mode between meeting the speed constraint and flying the programmed speed for the selected cost index. 

I don't think speed constraints are fully supported yet by the mod. @Watsi01 is there a way to either completely disregard the speed constraints or allow any speed constraints to override the cost index speed? It's not good to have this fluctuation going on.

I have a video illustrating it if you need it.

**Comment by Watsi01** [comment]
Okay, I tried your flight. And it does the same with me. Jumping around 290 and 210. In your case it's because of the speed restriction at ORCKA (later 170 at MISEN). So this is ok. What's not ok, is the jumping around between restriction and crz speed. It seems to jump around between 260 and 265 kts.
@donstim I think I could program disgregard of any speed resctriction on crz speed. Have to test a little.

**Comment by Watsi01** [comment]
... right now it actually should disregard the crz speed and hold the restriction. But that doesn't work obviously.

**Comment by Watsi01** [comment]
@donstim @jmihalich 
Ok, it actually was coded to ignore any speed restriction on crz speed (which didn't work for some reason). I try to code it now to allow and hold any speed restriction also in crz.

**Comment by jmihalich** [comment]
Excellent, thanks guys!
