### ISSUE TITLE
[BUG] No Smoking switch animation incorrect

### ISSUE THREAD

**Issue by lemansgarcia** [flybywiresim/a32nx#2867]
**Version:** A32NX 0.5.1

**Description:** When I want to set the No Smoking switch to AUTO or ON I can't because the animations stop at 2 points: The first one stops between off and auto and the second one in AUTO.

**Steps to reproduce the error:**
1. Load the aircraft.
2. Go to the overhead panel.
3. Try to set OFF, AUTO, and ON the No Smoking switch (take a good look at the animations)

**Expected behavior:** The animation of the No Smoking switch stops at OFF, AUTO, and ON

**Actual behavior:** The animation of the No Smoking switch stops at OFF, between OFF and AUTO, and in AUTO

**References:**
**OFF position**:![No Smoking switch OFF](https://user-images.githubusercontent.com/75225171/103523493-3494a480-4e7c-11eb-9994-4a6cbbb55a8e.png)
**Between OFF and AUTO position:**![No Smoking switch between OFF and AUTO](https://user-images.githubusercontent.com/75225171/103523535-46764780-4e7c-11eb-9018-2d4d22f4b522.png)
**AUTO position**:![No Smoking switch AUTO](https://user-images.githubusercontent.com/75225171/103523558-50984600-4e7c-11eb-9085-391c9c57031c.png)
**There is no ON position because it is impossible to continue.**

**Was this working before/when did the issue start occurring?** Yes

**Is this a problem in the vanilla unmodded game?** No

**Discord username:** The same as the GitHub

**Comment by hotshotp** [comment]
known issue, the on position is there its just the animation is wrong and we cant change it until exporter is done

**Comment by lemansgarcia** [comment]
> known issue, the on position is there its just the animation is wrong and we cant change it until exporter is done

Ok, and would be solved in the next updated?

**Comment by hotshotp** [comment]
it will be solved when the exporter is done which is an unknown time line

**Comment by lemansgarcia** [comment]
> it will be solved when the exporter is done which is an unknown time line

Ok, thanks. Would be soon or in like 2 months? (approximately)

**Comment by hotshotp** [comment]
we really dont know, new issues are coming up unfortunately, its a lot

**Comment by lemansgarcia** [comment]
> we really dont know, new issues are coming up unfortunately, its a lot

Ok, thanks for helping me have a nice day! Bye!
