### ISSUE TITLE
[BUG] Autopilot not engaging

### ISSUE THREAD

**Issue by anasmml** [flybywiresim/a32nx#2869]
**Mod Version**

**Describe the bug**
 the autopilot is simply not turning on!

**To Reproduce**

1.setup the aircraft 
2.ready for taxi 
3.push AP1 / AP2

**Expected behavior**

Autopilot button should've turned green and showed on the FMA

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by tracernz** [comment]
You can only engage one AP on the ground when the engines are not running but it will disengage when an engine is started. You may then only engage an autopilot at or above 100 feet AGL.

**Comment by anasmml** [comment]
Yep! Did that still not working

**Comment by Dubstyle050** [comment]
The same here.

**Comment by Benjozork** [comment]
Please properly fill the template.

Also, are you using any other mods ?

**Comment by anasmml** [comment]
No i have the stock a320 and flybywire a32nx newest stable version

**Comment by Dubstyle050** [comment]
Not using other mods. It was the dev update from 2 days ago. am now testing the stable version

**Comment by Dubstyle050** [comment]
I got it. it was my sensitivity what disconnected my AP. Put a dead zone of 15+

**Comment by NathanInnes** [comment]
Closing issue as it has been resolved.
