### ISSUE TITLE
[BUG] LOC/APP function not overriding HDG

### ISSUE THREAD

**Issue by dl1661** [flybywiresim/a32nx#2873]
**DEVELOPMENT as of 1/2/21 13:00EST**

**Describe the bug**

I was flying the updated development model two days ago in IMC conditions to KPDX. I was ~20nm out on a 30-degree angle to intercept the 10R localizer. The FMC had the correct frequency and course, as I-PDX was found and reporting on the PFD. However, when initializing the localizer capture function, the autopilot repeatedly overflew the localizer, even though the localizer was active and accurately reporting on the PFD. The approach function had the same response. I had to hand fly the ILS cat 3 approach completely blind.

**To Reproduce**

1. Be level at intercept altitude for any ILS approach and inbound on a 30 degree-or-less angle with manual heading, managed speed, and level altitude set on the MCP.
2. Turn on the LOC function, see if it intercepts.
3.

**Expected behavior**

The LOC should override manual heading and intercept the localizer course, as it was correct in the FMC and reporting accurately on the PFD.

**Actual behavior**

A/C repeatedly overshot the localizer and didn't capture gs either.

**References**

https://www.twitch.tv/videos/858905739?t=02h21m39s (first approach)
https://www.twitch.tv/videos/858905739?t=02h37m27s (second approach)

**Additional context**

Was this working before/when did the issue start occurring?

This was working in the prior dev updates, not sure if it's specific to PDX but will know in about two hours :D

Is this a problem in the vanilla unmodded game?

not sure

DL1661 on discord

**Comment by Benjozork** [comment]
This is fixed as of #2847. Please try with the latest development version and report back.

**Comment by foxmike80** [comment]
The interception of radials seems to work now, thank you. However I still do have an issue:

When on a manual intercept heading in HDG mode the aircraft turns to another intercept heading of its own. I would expect the aircraft to maintain my manual intercept heading until on the Localizer and then switch to LOC mode. In the picture I have manually selected HDG 110 to intercept the 180 RAD inbound. The plane turns automatically 
to an intercept HDG of about 120 while still displaying HDG in green in the FMA. 

![Screenshot 2021-01-04 212706](https://user-images.githubusercontent.com/76132268/103576849-122e7580-4ed4-11eb-8bef-e6a1dba75df2.png)

**Comment by hotshotp** [comment]
> The interception of radials seems to work now, thank you. However I still do have an issue:
> 
> When on a manual heading in HDG mode with LOC armed, the aircraft leaves my selected HDG and turns to an intercept heading of its own. I would expect the aircraft to maintain my selected heading. In the picture I have manually selected a HDG of 110. The plane turns automatically to an intercept HDG of about 120. Yet it is still correctly displaying HDG in green in the FMA.
> 
> ![Screenshot 2021-01-04 212706](https://user-images.githubusercontent.com/76132268/103576849-122e7580-4ed4-11eb-8bef-e6a1dba75df2.png)

this is a known issue #939
