### ISSUE TITLE
New issues

### ISSUE THREAD

**Issue by witto737** [flybywiresim/a32nx#2875]
I have the following issues, aircraft veers left and right when taxiing, taxi speed at idle thrust is too fast, around 25knts, on initial climb out aircraft either banks left or right and dives to the ground, at present aircraft is unusable.

**Comment by Benjozork** [comment]
> aircraft veers left and right when taxiing,

Make sure your rudder controls are properly centered.

> taxi speed at idle thrust is too fast, around 25knts,

No, this is how it is in real life.

> on initial climb out aircraft either banks left or right and dives to the ground,

Since you have completely ignored the template I don't know what version of the plane you have, so I cannot help you.

Closing issue as GitHub is not for support.
