### ISSUE TITLE
Reset MCDU after finished flight

### ISSUE THREAD

**Issue by ukflyer** [flybywiresim/a32nx#288]
Would there be any way to reset the MCDU after a flight so it's ready for the next, for me to do a turnaround?
I input new from/to airports in INIT page but plane still thinks its on previous flight (Approach mode still activated etc..)
Thank you!

**Comment by ukflyer** [comment]
Thanks for taking a look @Curtis-VL

**Comment by mikecbr** [comment]
Any news ?? its been 6 months with this issue ......

**Comment by AthleticEggplant** [comment]
I could be wrong but I believe it does.
