### ISSUE TITLE
[BUG] SIMBRIEF proposed A320 neo characteristics are wrong!

### ISSUE THREAD

**Issue by fralbo** [flybywiresim/a32nx#2882]
**Mod Version**

**Describe the bug**
I don't know where did you find the A320 neo characteristics but according to latest official [Airbus document](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjBuYTuoITuAhVnAGMBHSkFBnwQFjACegQIAxAC&url=https%3A%2F%2Fwww.airbus.com%2Fcontent%2Fdam%2Fcorporate-topics%2Fpublications%2Fbackgrounders%2Ftechdata%2Faircraft_characteristics%2FAirbus-Commercial-Aircraft-AC-A320.pdf&usg=AOvVaw2NZQcLH1UIEq7autR6WVzZ), I think information is wrong!
For example the MZFW of 62500 kg corresponds to aircraft types WV011, WV02, WV016, WV017, WV018 and first, none of them are "neo" version and second, none of them have a MTOW of 79000 kg.

So why to create a new Simbrief profile if it's to create a wrong one ??

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by tareksabet** [comment]
Good evening, the A320Neo profile is not in our hand but in simbrief hand because it's on their side to do the profile.
What we did is the integration of simbrief that's and no relations with the profile. 
thanks for reporting this issue, will close it now but if you have any concerns comment again so I can reopen it again.

Tarek
