### ISSUE TITLE
[REQUEST] Ability to flick switches with mouse wheel

### ISSUE THREAD

**Issue by St54Kevin** [flybywiresim/a32nx#2884]
**Is your feature request related to a problem? Please describe.**

More to inconsistency

**Describe the feature you'd like to see implemented**

I would love the ability to switch ALL non-pushbutton switches with the mouse wheel, like its currenty possible with switches with more than 2 positions (eg. landing lights)

**References**

**Additional context**

Discord username (if different from GitHub):

**Comment by hotshotp** [comment]
I personally would like an option to do that rather than have it, i dont want to accidentally scroll to zoom out and then flick my engine master switches lol. but it would be convenient for things like lights, i agree. not sure how we could do this

**Comment by NathanInnes** [comment]
Personally it frustrates me right now at the fact that when I scroll to zoom I always end up accidently flipping a switch, wish it was removed rather than added to more of them

**Comment by Valastiri** [comment]
You can rebind your "zoom" function to a mouse modifier. i.e. I have set mine to **Mouse Button 5 (Back button on mouse) + scroll in/out** 

So when I scroll to flick switches/turn knobs/interact with anything that requires a mouse wheel scroll function I don't inadvertently zoom. 

When I need to zoom I hold mouse button 5 and scroll accordingly. 

Found this "tip" from Clumsy on YouTube.

**Comment by calwalker1** [comment]
Thank you @Valastiri this is quite useful. I frequently have erroneous zooming happen in FS due to my old and tired computer mouse. I will use this setting when next in the game.

**Comment by derl30n** [comment]
Using https://github.com/flybywiresim/a32nx/issues/5298 for further tracking
