### ISSUE TITLE
New AP issue A32nx

### ISSUE THREAD

**Issue by Travel-Talk** [flybywiresim/a32nx#2886]
I was trying to do a flight on Vatsim earlier. When I took off and engaged AP the aircraft banked 90° to the right instead of following the flight path.
After testing the aircraft afterwards it turned out that the aircraft begins to horizontally loop at a 90° bank angle. I tested aircraft settings to see if it would fix it and it turns out that the bug was being caused by ELAC 1 on the flight control panel. Pretty unusual

**Comment by Travel-Talk** [comment]
This is on the latest stable build. I am going to try the dev build

**Comment by Travel-Talk** [comment]
Also ELAC 1 doesn't fully fix it. Only temporarily,  I just discovered that.

**Comment by Benjozork** [comment]
Doesn't follow provided template
