### ISSUE TITLE
[REQUEST] Break-Pressure gauge animation - smoother

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#2887]
**Is your feature request related to a problem? Please describe.**

It is not a major thing, but think it could add some more "real feel" and "life" to the Aircraft:

When set/release the parking break (or breaking) the break pressure indicator moves rapidely in its range and vice versa.
It would have a more realistic look, if the indicators "move". I don´t know the exactly rate of incresing/decreasing break pressure, but IRL you see the indicators moving. It may tooks around 0,2 to 0,5 sec from 0 to full and vice versa.

**Describe the feature you'd like to see implemented**

Pressure indicator should "move"

**References**

-

**Additional context**

-

Discord username (if different from GitHub):

**Comment by crocket63** [comment]
Can someone close this one? Solved :)
