### ISSUE TITLE
[BUG] ALT CRZ (Blue) & ALT CRZ* do not show in FMA

### ISSUE THREAD

**Issue by olibarke** [flybywiresim/a32nx#2890]
**Mod Version**
{
  "built": "2021-01-05T05:22:58+00:00",
  "ref": "",
  "sha": "",
  "actor": "donstim <70166617+donstim@users.noreply.github.com>",
  "event_name": "manual"
}

**Describe the bug**
When CRZ ALT is selected in FCU as programmed in MCDU Prog & INIT A page, the FMA does not display ALT CRZ (blue - armed) and shows ALT (blue - armed) incorrectly.  When capturing the cruise level it shows ALT* and then once captured it then displays ALT CRZ.

**To Reproduce**
1. Input desired cruise altitude in INIT A and/or PROG page on MCDU
2. Select input cruise alt in FCU window 
3. Check FMA changes from ALT (blue) to ALT CRZ (blue) and it does not

**Expected behavior**
I expect the armed altitude capture to change to ALT CRZ (blue) and the capture mode to be ALT CRZ*

**Actual behavior**
Remains ALT (blue), and ALT*

**References**
[https://app.photobucket.com/u/olibarke/p/0c502077-d4fb-417d-a0ab-d5792e33fa41](url)
[https://app.photobucket.com/u/olibarke/p/85eeec4e-1cdd-4d6c-80db-5741abd71114](url)
[https://app.photobucket.com/u/olibarke/p/f6dea9b0-717a-4c2d-b439-1f626bc45605](url)

**Additional context**

Is this a problem in the vanilla unmodded game? - Yes

Discord username (if different from GitHub): olibarke

**Comment by MisterChocker** [comment]
ALT CRZ can not be armed, in can only be targeted or captured.
ALT CRZ* and ALT CRZ exist and are shown in the FMA when reaching the cruising fl/alt.

The correct armed modes during climb are ALT or CLB when holding level at a constraint.

**Comment by olibarke** [comment]
> ALT CRZ can not be armed, in can only be targeted or captured.
> ALT CRZ* and ALT CRZ exist and are shown in the FMA when reaching the cruising fl/alt.
> 
> The correct armed modes during climb are ALT or CLB when holding level at a constraint.

Per the FCOM when the FMA displays a mode in blue it is "Armed" to be captured. 

As my screenshot shows I was capturing FL310 which was my PROG and INIT A cruise FL and yet it still said ALT*, it only said ALT CRZ once captured. 

If I select a FL below that input in the MCDU as the CRZ FL it will be ALT (blue), ALT*, and ALT. When it is the cruising FL as per the MCDU it should be ALT CRZ (blue), ALT CRZ*, and ALT CRZ.

**Comment by MisterChocker** [comment]
> As my screenshot shows

your link doesn't work

**Comment by olibarke** [comment]
> > As my screenshot shows
> 
> your link doesn't work

Just copy and paste the link into browser. Not sure why it links internally to github.

**Comment by tareksabet** [comment]
Good evening the ALT CRZ in cyan and ALT CRZ* it's not correct and here are some documentation from my FCOM. So I will close this issue. 

![Desktop Screenshot 2021 01 06 - 01 32 01 41](https://user-images.githubusercontent.com/70240330/103711147-6f532580-4fbf-11eb-8f0d-d42836fce211.png)

![Desktop Screenshot 2021 01 06 - 01 32 12 14](https://user-images.githubusercontent.com/70240330/103711160-767a3380-4fbf-11eb-8467-cab9c74a06c1.png)
