### ISSUE TITLE
FSUIPC with A32NX

### ISSUE THREAD

**Issue by MStallen** [flybywiresim/a32nx#2891]
2021-01-05T05:21:18+00:00

FSUIPC offsets (v. 7.0.4c) AP_APR_HOLD_ON and AP_LOC_HOLD don't work any more
#define KEY_AUTOBRAKE_LO_SET (KEY_ID_MIN + 1740) does not work
#define KEY_AUTOBRAKE_MED_SET (KEY_ID_MIN + 1741) does not work
#define KEY_AUTOBRAKE_HI_SET (KEY_ID_MIN + 1742) works!!

They do work in the Vanilla game.

**Comment by Benjozork** [comment]
Does not follow provided template
