### ISSUE TITLE
[BUG] FSUIPC controlls don't work

### ISSUE THREAD

**Issue by MStallen** [flybywiresim/a32nx#2894]
**Mod Version**
{
  "built": "2021-01-04T05:14:54+00:00",
  "ref": "",
  "sha": "",
  "actor": "Saschl <sascharudolf46@gmail.com>",
  "event_name": "manual"
}

**Describe the bug**
FSUIPC v 7.0.4.c offsets don't work
AP_APR_HOLD
AP_LOC_HOLD
AUTO_BRAKE_LO_SET
AUTO_BRAKE_MED_SET

AUTO_BRAKE_HI_SET works

**To Reproduce**

1. Start A32NX cold and dark, battery's and External PWR on
2. Send FSUIPC offsets (via FSUIPC or LINDA)
3.

**Expected behavior**

Engagement of systems on MCP

**Actual behavior**

No reaction at all

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Yes, or after latest update MSFS or new A32NX dev (I don't know)
Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):

**Comment by Saschl** [comment]
Hi, the autobrake events might be fixed with #2854 
About the other ones I don’t know yet. I’ll look tomorrow and see if there’s something that can be done.

**Comment by MStallen** [comment]
Any solution yet? AP_APR_HOLD and AP_LOC_HOLD still not working in FBW

**Comment by MStallen** [comment]
I did another check. FSUIPC events AP_APR_HOLD and AP_LOC_HOLD are working, but only the lights on the MCP don't come on.
In the Vanilla they do.

**Comment by Saschl** [comment]
Sorry but I didn't find any solution so far, as the mod uses a custom variable to set the lights and the logic is a bit customised as well. I guess it could be synced in some way (e.g. set the the custom variable when the key event is set) but it's not easy to find out what is set by the actual key event.

Just as a summary: when pressing the button in the cockpit, the custom variable gets set and then the corresponding key events are triggered. If we now only send the key event, the ap itself should perform normally as you already mentioned. But the light does only light up when the custom variable is set.

**Comment by MStallen** [comment]
Do you now the hexadecimal adres of this custom variable and parameter(s) send, because then I can use those in my FSUIPC.ini

**Comment by sidnov** [comment]
Due to the custom events that we added for FCU controls, this may not be an issue that can be fixed on our end. Though, there are updates from FSUIPC that could possibly use LVars to get offsets
