### ISSUE TITLE
[BUG] MCDU: Next Waypoint must be typed in twice 

### ISSUE THREAD

**Issue by marcelago** [flybywiresim/a32nx#2895]
Hello, 
I just started entering my flightplan manually into the MCDU (All Waypoints individually). I initially tried to enter them one by one, by replacing them with DECEL, but it refused to work for whatever reason. (In confirmend [green] and editorial [yellow] mode)
So I then tried to add them in the WP tab, by entering the last waypoint and setting the next WP in the NEXT WPT space. That however only rejected my input and I was returned to the Flightplan page. I insisted on trying it again, and it surprisingly worked the second time. I continued and found out that about 20% got registered on the first try, 60% on the second and 20% not at all. I initially thought, that the first issue was a result of my inexperience, but that random behavior with the NEXT WPT cannot be attibuted to my missuse. 

Flight planner: SimBrief

EDDM (Munich) to LFPG (Paris)

Additional Information: MSFS2020 1.12.13.0

I unfortunatly cannot confirm you wich exact version I have installed, but I downloaded the A320nx Installer on 30th of December and chose the non-experimental version, so I would assume that I installed the 0.5 version.

Thank you for your attention and for making such an amazing Addon!

**Comment by Benjozork** [comment]
Hey, this is going to be resolved with the new flightplan manager system I am working on. Stay tuned.

**Comment by marcelago** [comment]
That's great to hear! Thanks a lot!

**Comment by 2hwk** [comment]
Fixed by 4953 closing ☑️
