### ISSUE TITLE
[BUG] Preselection of LOC/APPR (blue) switches to managed lateral mode, even if selected mode was active (HDG green)

### ISSUE THREAD

**Issue by SierraBravo1** [flybywiresim/a32nx#2899]
**Mod Version**
master
"built": "2021-01-05T05:22:58+00:00"

**Describe the bug**
AP does not follow the selected heading (HDG green) when LOC/APPR is preselected (LOC blue, ILS not yet received).
After pressing the LOC or APPR button, it switches to managed lateral mode and returns to the latest active waypoint.
Note: I'm not 100% sure how the A320 behaves in reallity. I assume, it should follow the heading, if selected, but minimum the FMA and FCU should be consistent.

**To Reproduce**
1. Create a normal route in the MCDU to an airport with an approach pattern.
2. Fly to the destination.
3. Before the ILS can be received,
	a. switch to HDG mode and select a heading to intercept the ILS (HDG green), like radar vectors
	b. some waypoints (for example of the arrival) should be bypassed
	c. Enable LOC / APPR as preselection (LOC blue)

For example:
EDDF07C KOMI3D KOMIB T193 ERTES DCT DODAS DOD10 EDDN10
After takeoff, switch to selected HDG mode and fly direct to EDDN (~110°).
50nm before EDDN, press LOC to preselect ILS approach.

**Expected behavior**
Aircraft should follow selected heading until ILS is received and LOC mode becomes active (green).

**Actual behavior**
FMA shows correct HDG green and LOC blue.
But AP doesn't follow selected heading. Autopilot switches to managed mode when LOC/APPR button is pressed and returns to latest active waypoint.

**References**
The following picture shows that:
- HDG mode is active in FMA and LOC is preselected.
- But Managed mode is active in FCU and AP turns left to latest active waypoint, but heading was selected to 92°.
![hdg_loc](https://user-images.githubusercontent.com/76132388/103710194-b851ac80-4fb4-11eb-9531-7e91b429fbbf.png)

Was this working before/when did the issue start occurring?
I detected this issue by checking the closed issue #2873
Not checked this behavior before.

Is this a problem in the vanilla unmodded game?
Don't know.

**Comment by SameerAli18** [comment]
theres no ils frequency shown on the pfd
![Capture](https://user-images.githubusercontent.com/73446418/103780746-4f5a4b00-502d-11eb-98d1-b7896d0a9b28.PNG)

**Comment by SierraBravo1** [comment]
@SameerAli18 correct, there is no ILS frequency shown, because the localizer is not received yet.
In my case, the LOC mode is only preselected (blue).
In your case, the ILS is already received, AP switches to LOC mode (green) and and the approach is guided by ILS. This works correct, but is not the described issue.
The issue appears if the localizer is not received yet and LOC mode is only preselected (blue). For example if you are guided by radar vectors in HDG mode and preselect LOC when you've got the ILS clearance.

**Comment by joseG69** [comment]
I have the same problem. It is almost impossible to have vectors to final app in VATSIM. And that is what controllers always do! If HDG is green in FMA, managed mode shouldn´t be active in FCU (yellow dot). That should only happens when localizer is captured.

What I am doing to temporally bypass this issue is only clicking the LOC button after localizer becomes alive. But that is not the way it should be done. I kindly request priority for this issue, as it affects  flying in a critical moment (intercepting localizer in app)

Best regards

**Comment by henrikx** [comment]
Can confirm this issue. I selected APPR mode in preparation for final and it immediately started following the localizer even though the PFD said HDG mode was active.

**Comment by SierraBravo1** [comment]
Seems to be fixed in the latest experimental version with custom autopilot.
HDG remains active (green) until localizer is captured.
