### ISSUE TITLE
[BUG] Flood lighting not accurate in main displays , PFD , ECAM ND AS THE KNOB FOR IT.

### ISSUE THREAD

**Issue by mikecbr** [flybywiresim/a32nx#2901]
**Mod Version**
Latest branch

**Describe the bug**
The flood light in the main displays as i said before , PFD , ECAM , ND ETC is so inaccurate , the lowest setting for the knob in the display lights , just emits more light that it should be in real life , it should be a lot lower....

Also the knob for those (specially the knob for the main panel flood ), should be twist as the speed knob , right now its so inaccurate , its has kind of pre selected modes so it goes from nothing to so much

**To Reproduce**

1.Twist those buttons 
2.
3.

**Expected behavior**
Even lower flood light for the main displays , as in real life , i just tested , I am a Cabin crew you can check that on discord Mikecbr and the Knob for the MAIN DISPLAY PANEL should twist like the speed one.

**Actual behavior**
Not realistic , so much light even in the lowest mode for the main displays and the  Knob for the MAIN DISPLAY PANEL not twisting like it should be

**References**

**Additional context**

Was this working before/when did the issue start occurring?
No

Is this a problem in the vanilla unmodded game?
Dont think so

Discord username (if different from GitHub):

**Comment by Snapmatics** [comment]
Sabes and I searched about the brightness, but nothing has been found 'till now.

**Comment by mikecbr** [comment]
@Snapmatics  , Wells That  is not reason to close it.....

**Comment by mikecbr** [comment]
@St54Kevin ask him as he is a real life 320 pilot @Snapmatics

**Comment by St54Kevin** [comment]
It's just too bright. No other way than adjusting and let an neo pilot confirm it.

**Comment by mikecbr** [comment]
@St54Kevin  also the know for the Panel main displays etc should be fix
