### ISSUE TITLE
[BUG] Unable to launch A320 built in missions with mod

### ISSUE THREAD

**Issue by prounlocks** [flybywiresim/a32nx#2905]
**Mod Version**

{
  "built": "2020-12-23T05:49:09+00:00",
  "ref": "",
  "sha": "",
  "actor": "Benjamin Dupont <benjozorkfr@gmail.com>",
  "event_name": "manual"
}

**Describe the bug**

When trying to load any built in mission with A320 - got error "One or more required items are missing. Go to download manager to download it"  However there is no new things in content manager appeared. Deleting mod folder A32NX solving issue fully.

**To Reproduce**

1. Launch SIM
2. Launch Any built in landing mission with A320
3. Profit

**Expected behavior**

Expect to use A320 mod with all missions like vanilla

**Actual behavior**

All missions with A320 does not start

**References**

**Additional context**

Was this working before/when did the issue start occurring?
after last FS2020 update.

Is this a problem in the vanilla unmodded game?
Yes only happens with installed A32NX

Discord username (if different from GitHub):
clawhammer#9050

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by kiokio0987** [comment]
The master version after December 29th will load without problems. (#2753)
However, to keep the challenge fair, it is recommended to use the vanilla A320.
