### ISSUE TITLE
[BUG] MSFS2020 crashes with Logitech flight panels

### ISSUE THREAD

**Issue by frankspiral** [flybywiresim/a32nx#2906]
The combination of the use of Logitech flight panels and selection of a32nx causes the game to crash

**To Reproduce**

1. Flight panels plugged in
2. Game loads to create a flight screen
3. Select a32nx
4. Select any airports
5. Select either runway departure or gate
6. Flight starts to load
7. Game crashes and returns to Windows

**Expected behavior**

For the game not to crash and for the flight panels to work with the aircraft.
The flight panels work with all other aircraft. 
The a32nx works fine without the panels

**Actual behavior**

When the Logitech Pro Flight Multi Instrument, Switch and Radio Panels are plugged in and the a32nx is selected the game crashes as the flight is loading. Crashes do not occur when other planes are selected in the game and the panels work well.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Plane worked fine before the panels were installed and still works when the panels are unplugged

Is this a problem in the vanilla unmodded game?
Yes

Discord username (if different from GitHub):

**Comment by Awemeter** [comment]
Are you using fsuipc7 at the time of crash

**Comment by frankspiral** [comment]
I’ve tried it with and without fsuipc7 running and it crashes either way

**Comment by frankspiral** [comment]
I’ve reloaded msfs, Logitech and a32nx, seems to have fixed the issue! Thanks
