### ISSUE TITLE
[BUG] A32NX disables 747 MCDU

### ISSUE THREAD

**Issue by Powie** [flybywiresim/a32nx#2910]
**Mod Version**

0.5.1 Stable

**Describe the bug**

If the A32NX is installed, the Asobo 747 MCDU is "OFF" 

**To Reproduce**

1. Use the 747 - MCDU is OFF
2. Deinstall A32NX
3. 747 MCDU works

**Expected behavior**

No bug in 747 with A32NX installed

**Actual behavior**

**References**

**Additional context**

Discord username (if different from GitHub): PowieT

**Comment by Watsi01** [comment]
We fixed that already. Try the latest dev version.

**Comment by MisterChocker** [comment]
Closing since Issue is resolved in current master.
