### ISSUE TITLE
[BUG] V/S and FPA do not override altitude hold

### ISSUE THREAD

**Issue by foxmike80** [flybywiresim/a32nx#2918]
**Mod Version**

{
  "built": "2021-01-06T07:07:41+00:00",
  "ref": "",
  "sha": "",
  "actor": "devsnek <me@gus.host>",
  "event_name": "manual"
}

**Describe the bug**

Pulling the V/S button should override altitude hold and trigger a descent or climb even if the plane is at the FCU altitude.

**To Reproduce**

1. Use the autopilot to maintain an altitude of 5000'.
2. Turn the V/S FPA button to select a vertical speed of -1000fpm.
3. Pull the V/S button.
4. Watch the aircraft maintain its altitude and the digits in V/S window become dashes.

**Expected behavior**

The autopilot should command a descent with a vertical speed of -1000fpm.

**Actual behavior**

The aircraft maintains altitude.

**References**

https://youtu.be/_zs9x_hfXjY?t=1083
https://youtu.be/1IhzbfB-8pI?t=359

**Additional context**

Pulling the V/S FPA button should override FCU altitude. When doing non-precision approaches, you would arrive a given altitude, say 4.000'. On final track you would select the missed approach altitude of 5000' and at the descent point you would initiate a descent with a given FPA, say 3.0 degrees. In current state, the airplane will maintain 4.000' and not descent.

Was this working before/when did the issue start occurring?
I do not know.

Is this a problem in the vanilla unmodded game?
Yes, but differently. The vanilla version does not even allow a V/S speed to be selected when in level flight.

Discord username (if different from GitHub): froemmelm

**Comment by SierraBravo1** [comment]
Tested and agree. V/S should be executed when selected, independent of altitude setting.

**Comment by AirbusA320Pro** [comment]
Confirmed same behaviour on 0.5.2. V/S should initiate when pulled, to the target rate selected, irrespective of where ALT is set. 
Knob behaviour should work either by selecting target V/S and pulling (initiating the climb/desc), or pulling first and seeing V/S 0 on the FMAs, then selecting desired rate.
