### ISSUE TITLE
[BUG] Master version issue

### ISSUE THREAD

**Issue by moey124** [flybywiresim/a32nx#2919]
**Mod Version**
 Master
 Dev from installer

**Describe the bug**
 installed the master , wont hold altitude and airspeed drops to 110 knots while climbing . The funny thing is that my friends dont have that issue with the master just me . I did s fresh install of windows and the sim as well . I switch to stable and all is fine , usually the master would have worked for me in previous versions of it since the last two updates it went ballistic on me 

**To Reproduce**

1. Climbing altitude set to any altitude wont hold it
2. Airspeed drops during climb wont hold it 
3. Been happening since the last two updates

**Expected behavior**
 never expected this to happen since i was using the master for a month

**Actual behavior**
 it went ballistic it doesn't hold altitude at all and airspeed drops . This can be from cold and dark to runway starting it doesnt matter

**References**

**Additional context**

Was this working before/when did the issue start occurring? The master version always worked for me but since the last two updates this is a issue 
My friends dont have this issue its just me

Is this a problem in the vanilla unmodded game? N/A

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by MisterChocker** [comment]
Please add the the contents from the build_info.json as the template shows.

**Comment by moey124** [comment]
> Please add the the contents from the build_info.json as the template shows.

{
  "built": "2021-01-07T18:21:55+00:00",
  "ref": "",
  "sha": "",
  "actor": "Harry <43104362+Snapmatics@users.noreply.github.com>",
  "event_name": "manual"
}

**Comment by MisterChocker** [comment]
Do you have any other mods installed?

**Comment by moey124** [comment]
No. 


Sent from Yahoo Mail for iPhone


On Wednesday, January 13, 2021, 6:23 AM, DerL30N <notifications@github.com> wrote:




Do you have any other mods installed?

**Comment by Benjozork** [comment]
Could you record your screen while the issue is happening ?

**Comment by MisterChocker** [comment]
Closing since no response from op
