### ISSUE TITLE
[BUG] FCU not switching to mach automically

### ISSUE THREAD

**Issue by Watsi01** [flybywiresim/a32nx#2920]
**Mod Version**
"built": "2021-01-07T01:08:05+00:00",
  "ref": "",
  "sha": "",
  "actor": "Tyler Knox <16512508+tyler58546@users.noreply.github.com>",
  "event_name": "manual"

**Describe the bug**
During climb, when reaching mach .78 FCU doesn't switch to mach automatically. You have to switch to selected speed and then back to managed, to change to mach. Could be a one timer. If this is not reproducable, we can close this issue.

**To Reproduce**

1. Start Cold&D, plan a normal flight (at least with FL350 to reach .78 for sure)
2. Go and fly.
3. Watch speed indication during climb. When reaching mach .78, check FCU. 

**Expected behavior**
When reaching mach .78 the FCU should switch to mach automatically. At least that was the behaviour before.

**Actual behavior**
see above

**References**

**Additional context**
As said, this could be a one timer on my side.

Was this working before/when did the issue start occurring?
Started occuring with the latest dev (or the version before, which I didn't download).

**Comment by MisterChocker** [comment]
This is an issue since last mfsf update if I recall correctly.

**Comment by Watsi01** [comment]
Not exactly. Since latest Asobo update you can't switch manually from kts to mach or back. That's correct. But it did it automatically, when reaching mach .78 (climb) or passing FL260 (descent). My last flight, it didn't switch automatically when reaching mach .78. That is new to me. But with my second flight today, everything worked fine. So I'm not sure, if this is really an issue.

**Comment by MisterChocker** [comment]
Well in any case we can still maintain this issue and address the general switch functionality between knots and mach.
However there might be another issue open in this regard already.

**Comment by Watsi01** [comment]
Never had this specific issue again. So I might close it.
