### ISSUE TITLE
[BUG] SimBrief flight plan not correctly entered: AWY/WPT MISMATCH  

### ISSUE THREAD

**Issue by JLD95** [flybywiresim/a32nx#2923]
**Mod Version**

2021-01-07T01:08:05+00:00

**Describe the bug**

The SimBrief flight plan between FAOR to FYWH with route
VASU3A VASUR UQ24 ETOSA G653 GBV UN182 AXODO AXOD1B

Is not correctly entered

**To Reproduce**

1. On SimBrief, define a flight plan between FAOR to FYWH with route
VASU3A VASUR UQ24 ETOSA G653 GBV UN182 AXODO AXOD1B
2. On MCDU when init request, WY/WPT MISMATCH appears and the FP has no intermediate waypoints
3.

**Expected behavior**

FP entered shall be similar to SimBrief definition

**Actual behavior**

Intermediate waypoints of SimBrief Flight Plan are not entered

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
Not tested
I used also Navigraph data cycle 2014 rev2

Discord username (if different from GitHub):

**Comment by tareksabet** [comment]
If you meant about SID points and Stars point they shouldn't be loaded.

**Comment by JLD95** [comment]
I flight many flight with A320Nx and SimBrief without problems. In this flight, i have only SID and STAR points

**Comment by MisterChocker** [comment]
It can occur that routes from simbrief have waypoints or waypoints the flight plan manager cant find, therefore a message `NOT IN DATABASE` or `AWY/WPT MISMATCH` is displayed on the scratchpad.

**Comment by JLD95** [comment]
I retry this flight plan and AWY/WPT MISMATCH is displayed on the scratchpad.
I try in manual mode and I can create without problem the route defined by SimBrief: all waypoints and all airways are defined

In manual mode:
![2021-01-07 (4)](https://user-images.githubusercontent.com/5894146/103922817-97a06880-5114-11eb-9f12-6fddb1d4179d.jpg)

**Comment by MisterChocker** [comment]
The reason why this works when entering manual may be because `await lastWaypoint.infos.UpdateAirway(name)` is being used to ensure the needed data is loaded.

**Comment by AdamNZ** [comment]
I tried a flight with the revised code (thanks) ... but got the same WY/WPT MISMATCH error - and only the LIMES waypoint to my NZAA-NZWN flight plan (see #2947).

**Comment by MisterChocker** [comment]
@AdamNZ the proposed solution/code is actually only for documentation, once you modify the codes you need to run our build script.
