### ISSUE TITLE
[BUG] CTD when clicking on world map

### ISSUE THREAD

**Issue by stony112** [flybywiresim/a32nx#2925]
**Mod Version**

```
{
  "built": "2020-12-23T05:49:09+00:00",
  "ref": "",
  "sha": "",
  "actor": "Benjamin Dupont <benjozorkfr@gmail.com>",
  "event_name": "manual"
}
```

**Describe the bug**

crash to desktop when clicking on world map (doesn't happen when A32NX is not installed). Tried with stable- and dev-version. Fresh installation of MSFS (yesterday) and fresh installation of A32NX. Installed only the free contents in contentmanager of MSFS (USA, Japan, Paderborn-Lippstadt, Livery-Pack)

System:
Windows 10 20H2
AMD Ryzen 5 3600X
AMD RX5700 (non-XT)
32GB DDR4 RAM

**To Reproduce**

1. Installed A32NX (via downloadmanager / tried different versions)
2. started MSFS and clicked on World Map
3. Crash to Desktop

**Expected behavior**

World Map opens and I can configure my flight

**Actual behavior**

crash to desktop

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
yes, only A32NX and official content-updates installed (as described above)

Discord username (if different from GitHub):
Stony112

**Comment by MisterChocker** [comment]
You don't have any other mods installed, right?
Have you tried deleting/uninstalling the additional content you have installed via the content manager?

**Comment by stony112** [comment]
yes, only a32nx is installed. uninstalled all additional content of contentmanager now, but still ctd when I click on world map. Removed A32NX-folder from community-folder, now it works. But I've seen, that I've only the TBM 930 and Cessna 152 in the aircraft-selection, maybe this is the problem. I'll check it

**Comment by rollonit** [comment]
Sometimes, on a fresh install, MSFS skips bunch of default scenery and aircraft, and you'll need to install them manually through the content manager. I think if any of the default aircraft or landing challenges are not installed, the sim becomes really unstable. Try looking under not installed in the content manager.

**Comment by Benjozork** [comment]
- Please try with th development verison and report back.

**Comment by stony112** [comment]
> Sometimes, on a fresh install, MSFS skips bunch of default scenery and aircraft, and you'll need to install them manually through the content manager. I think if any of the default aircraft or landing challenges are not installed, the sim becomes really unstable. Try looking under not installed in the content manager.

yes, this was the problem, now it works. Thank you.

**Comment by MisterChocker** [comment]
Issue resolved, closing now.
