### ISSUE TITLE
[BUG] Waypoints hidden/removed when programming STAR in the CDU

### ISSUE THREAD

**Issue by August78** [flybywiresim/a32nx#2929]
**Mod Version**
Master
{
  "built": "2021-01-06T07:07:41+00:00",
  "ref": "",
  "sha": "",
  "actor": "devsnek <me@gus.host>",
  "event_name": "manual"
}

**Describe the bug**
When programming in the STAR for the destination airport (ie. ENGM or other EU airports), waypoints that fan out away from the ILS are removed or hidden. I have cause to believe that they are latent in the sim, but are not shown in the waypoint list in the flight plan page. 

**To Reproduce**

1. Enter departure airport in the world menu. You can also add the destination airport or leave it blank. 
2. Program in the waypoints, add in the SID and then lastly add the STAR for ENGM, ENVA, ENCN, EDDF or other EU airports)
3. If you add ie. GM408 as a waypoint after GM410, the hidden waypoints will be shown, but not in order, and you cannot fly it.
Look at video on youtube for more info: https://youtu.be/8yGvcTp6ssw

**Expected behavior**
The star programmed in the CDU should be similar to the published STARs for the airport. In the case of ENGM and the RIPA3L arrival, GM409, GM408 and GM407 should follow after GM410. Instead, they are cut out/hidden.

**Actual behavior**
Look above at the point about how to reproduce the bug. 

**References**
Video to display the issue: https://youtu.be/8yGvcTp6ssw

Was this working before/when did the issue start occurring?
This has never worked correctly, neither with addons or vanilla planes. Also doesnt work with navigraph or without it. 

Is this a problem in the vanilla unmodded game?
Yes.

**Comment by Benjozork** [comment]
This might be fixed by #2831.

Quick question, do you have Navigraph navdata installed ?

**Comment by August78** [comment]
is that version released yet, @Benjozork ? 
Yes, I have it installed, but I also tried it without it, and the problem is the same.

**Comment by Benjozork** [comment]
No it's not released, it's a work in progress and will take some time.

**Comment by 2hwk** [comment]
Fixed by #4953 closing ☑️
