### ISSUE TITLE
[BUG] HDG select and Airspeed 

### ISSUE THREAD

**Issue by Bryce108** [flybywiresim/a32nx#2932]
**Mod Version**
Latest development 

**Describe the bug**
When in HDG or Airspeed open mode, it only increases by 10's. IE: HDG 234 trying to move it to a new heading by one it goes to 244, or 224 instead of increments of 1

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by andrejetcat** [comment]
known issue. same here! do you have any hardware like throttle or something else? when a permanent physical button(or switch) is pressed,  these issue occur. 
You can decrease and increase e.g. heading by klicking right/left. that is how I do it until this issue is solved

**Comment by Bryce108** [comment]
Heyyy THAT WORKS! lol thanks, and yeah I just got the Airbus throttles from THrustmaster.

**Comment by andrejetcat** [comment]
same here, thrustmaster Throttle with flap-leaver and speedbreakes... but its not related to this product. I read, that it is with every hardware. I posted this issue some weeks ago, but it is maybe a Asobo-issue. but i hope FBW can fix it in any way :)

**Comment by Bryce108** [comment]
I wish i could get all the attachments lol Scalpers have been wild with tech lately....
