### ISSUE TITLE
[REQUEST] Simbrief A320NX profile needs Fuel Factor to be adjusted

### ISSUE THREAD

**Issue by crisk73** [flybywiresim/a32nx#2936]
**Is your feature request related to a problem? Please describe.**

The actual provided profile was created based on the default A320CEO powered by older CFM56-5B engines. This causes a too high amount of fuel be calculated for the Neo, powered by the more fuel efficient PW1000G. The difference should range from 15% to 20% less fuel burn. 

**Describe the feature you'd like to see implemented**

I suggest to add to the simbrief profile a Fuel Factor coefficient of something like M17 (-17%) to take this efficiency into consideration so as to adjust the calculated plane max range. 

**References**

**Additional context**

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by hotshotp** [comment]
This is not for us to do, this is for simbrief to implement

**Comment by Benjozork** [comment]
> powered by the more fuel efficient PW1000G.

We don't model the PW1000G at the moment.
