### ISSUE TITLE
max bank angle should be 33 degrees

### ISSUE THREAD

**Issue by lawfulrocky** [flybywiresim/a32nx#294]
When max bank angle is set to 33 in engine.cfg. Using autopilot changing heading to like 320 to 280 trim doesnt auto level the plane

**Comment by PCGamesF1Tech** [comment]
Hm, max bank angle really should be 66/67° (2.5g in level flight).
33° is the max bank angle the aircraft rolls back to when you release the sidestick from higher bank angles (called "spiral stability").
All this only applies in manual flight! 
AP/FD uses a maximum of 30° for turns (passenger comfort).

**Comment by lawfulrocky** [comment]
OK thanks for letting me know that. The max bank angle in the config is set to 20. Which I can fix it to 30 if the dev team doesn't mind me doing it. Ionly thing I noticed that when you are in autopilot it doesn't auto trim up with the elevator quickly enough

**Comment by PCGamesF1Tech** [comment]
Update Patch No. 2
Looks like the max bank angle is now 67° left and right and when the sidestick is released the aircraft rolls back to 33° 👍🏻

**Comment by NathanInnes** [comment]
Appears to have been changed with the latest patch. Closing issue

**Comment by Flyingtrader06** [comment]
This issue is not fixed/appears again on the latest stable release (4.0). Max bank angle is still set to 20 degress in cfg file, meaning that the aircraft constantly overshoots fixes. Can it be set to 30 degrees when A/P is engaged ?

**Comment by NathanInnes** [comment]
'max_bank = 30,15'
