### ISSUE TITLE
[BUG] Insert Star in Flight after import route without star in simbrief

### ISSUE THREAD

**Issue by DecMoonFR** [flybywiresim/a32nx#2941]
**Mod Version**

Dev branch : "built": "2020-12-25T10:12:36+00:00"

**Describe the bug**

STAR is inserted after Airport waypoint with inserted routes from simbrief without star (or with DCT) and after loading a staz in fmc

**To Reproduce**

Make a route in simbrief without star
Import route via fmc.
Start flight
Change star :
- Airport waypoint is before star, and impossible to clear it.
- I can use direct to 1st waipoint of star for by passing this bug
**Expected behavior**

**Actual behavior**

**References**

Sorry no screenshots

**Additional context**

No problem when there is already a star in simbrief. Even if I need to change star.
It's a bug with simbrief import, if I make my route manually there is no problem. So, it's not a vanilla bug (because no simbrief importation) and no A32NX bug when we fill route manually.

Discord username (if different from GitHub):

DecMoon
#9041

**Comment by bluedoors** [comment]
I find the same behaviour. When the aircraft reaches the first waypoint of the STAR it turns direct to the numbers rather than following the STAR. I've not found a workaround (apart from switching to heading mode and getting vectors).

**Comment by 2hwk** [comment]
Fixed by #4953 closing ☑️
