### ISSUE TITLE
[BUG] Cruise Wind page of the INIT A MCDU does not accept FL4000

### ISSUE THREAD

**Issue by Abriael** [flybywiresim/a32nx#2946]
**Mod Version**
2021-01-08T22:27:54+00:00

**Describe the bug**
In the cruise wind page of the MCDU INIT A I cannot insert FL400. I know that the maximum ceiling is right below that, but it seems strange that it doesn't accept it as wind data (which does appear in flight plans). Perhaps it'd be good to verify with pilots whether it should accept it 

**To Reproduce**

1. Open cruise wind page
2. insert XXX/XXX/400
3. returns invalid format response

**Expected behavior**

Likely should accept it.

**Actual behavior**

returns invalid format response. FL39 is accepted.

**References**

**Additional context**

Don't know if it ever worked before unfortunately.

Discord username (if different from GitHub):

**Comment by hotshotp** [comment]
Hello - flight level 390 is the highest altitude rated for the a320neo. Working as intended
