### ISSUE TITLE
A320 Should not start descending automatically 

### ISSUE THREAD

**Issue by Zyonix007** [flybywiresim/a32nx#295]
You should get a “decelerate” warning on the PFD if you missed ToD

**Comment by Curtis-VL** [comment]
I'm going to label this as an Asobo bug, however... I hope someone will look into it some time!
I'm just not sure we have access to the code to change that behaviour.

**Comment by leosilva7719** [comment]
Estou com dificuldade para saber o ponto exato para iniciar a descida (TOD). O TOD deveria ser mostrado na página de performance.

**Comment by NathanInnes** [comment]
Please follow the issue template.
