### ISSUE TITLE
[REQUEST] SimBrief Base Type A32N Airframe Data

### ISSUE THREAD

**Issue by CaptVirtual** [flybywiresim/a32nx#2951]
_**Is your feature request related to a problem? Please describe.**_
SimBrief does not have type data for the A320 Neo - in particular the FBW A32NX

_**Describe the feature you'd like to see implemented**_
With the talent present within this project, I would like for someone to create an A32NX A/C data set within SimBrief.  I believe it requires obtaining an API key from SimBrief founder Derek Mayer.  
I understand this request could be argued to be a SimBrief issue, which it is, however there are also many requests on their support forums with no results to date -requests dating back many years.
I also realize at this present time the FBW aircraft specs are a moving target with new engine/fuel/flight modules being created - but it would be a nice future have.

_**References**_
https://www.simbrief.com/forum/viewtopic.php?p=850#p850

_**Additional context**_
N/A

Discord username (if different from GitHub):  CaptVirtual

**Comment by foxmike80** [comment]
Is that what you are looking for? See the linked youtube video in the last but one reply. There is a link to a simbrief profile in that video, that I have been using:

[Forum](https://forums.flightsimulator.com/t/simbrief-com-airframe-for-320neo-flybywire-mod/325307/4)
[Profile](https://www.simbrief.com/system/dispatch.php?sharefleet=eyJ0cyI6IjE1OTgzNDIwNTA2NDkiLCJiYXNldHlwZSI6IkEzMjAiLCJjb21tZW50cyI6IkVaWSBBMzIwTiIsImljYW8iOiJBMjBOIiwibmFtZSI6IkEzMjAtMjAwIiwiZW5naW5lcyI6IkNGTTU2LTVCNC9QIiwicmVnIjoiRy1VWkhIIiwiZmluIjoiMjA1Iiwic2VsY2FsIjoiIiwiaGV4Y29kZSI6IiIsImNhdCI6Ik0iLCJwZXIiOiJDIiwiZXF1aXAiOiJTREUzRkdISVJXWSIsInRyYW5zcG9uZGVyIjoiTEIxIiwicGJuIjoiQTFCMUMxRDFPMVMxIiwiZXh0cmFybWsiOiIiLCJtYXhwYXgiOiIxODAiLCJ3Z3R1bml0cyI6IktHUyIsIm9ldyI6IjQxMDA1IiwibXpmdyI6IjY4MzYzIiwibXRvdyI6Ijc4OTAwIiwibWx3IjoiNjc0MDAiLCJtYXhmdWVsIjoiMjEyNzMiLCJwYXh3Z3QiOiIxMDQiLCJkZWZhdWx0Y2kiOiI4IiwiZnVlbGZhY3RvciI6IlAwMSIsImNydWlzZW9mZnNldCI6IlAwMDAwIn0-)

**Comment by CaptVirtual** [comment]
> Is that what you are looking for? See the linked youtube video in the last but one reply. There is a link to a simbrief profile in that video, that I have been using:
> 

Thanks for the reply foxmike.

Yes this is what I am referring to, however, I would prefer to have a base type setup for the A320Neo.  These parameters are the SimBrief base typeA320-200 with some changes made to reflect differences in weights & fuel flow - and in fact his numbers aren't that accurate.

**Comment by Lucky38i** [comment]
The simbrief devs have said it's not currently possible to create an accurate profile as there's a number of parameters that Airbus keeps secret regarding the Mei line.

**Comment by krieke58** [comment]
I currently use this profile for the A320Neo. Works quite well.
https://www.simbrief.com/system/dispatch.php?sharefleet=eyJ0cyI6IjE2MDMzNzc2NDg3NjQiLCJiYXNldHlwZSI6IkEzMjAiLCJjb21tZW50cyI6IiIsImljYW8iOiJBMzIwIiwibmFtZSI6IkEzMjBORU8iLCJlbmdpbmVzIjoiUFcxMTAwRy1KTSIsInJlZyI6Ik4zMjBTQiIsImZpbiI6IjYwOSIsInNlbGNhbCI6IiIsImhleGNvZGUiOiIiLCJjYXQiOiJNIiwicGVyIjoiQyIsImVxdWlwIjoiU0RFM0ZHSElSV1kiLCJ0cmFuc3BvbmRlciI6IkxCMSIsInBibiI6IkExQjFDMUQxTzFTMSIsImV4dHJhcm1rIjoiIiwibWF4cGF4IjoiMTgwIiwid2d0dW5pdHMiOiJLR1MiLCJvZXciOiI0Mzc4MCIsIm16ZnciOiI2NDMwMCIsIm10b3ciOiI3OTAwMCIsIm1sdyI6IjY3NDAwIiwibWF4ZnVlbCI6IjI2NzMwIiwicGF4d2d0IjoiMTA0IiwiZGVmYXVsdGNpIjoiIiwiZnVlbGZhY3RvciI6Ik0wNyIsImNydWlzZW9mZnNldCI6IlAwMDAwIn0-

**Comment by CaptVirtual** [comment]
> Is that what you are looking for? See the linked youtube video in the last but one reply. There is a link to a simbrief profile in that video, that I have been using:
> 

Thanks.  

Yes this is what I am referring to, however, I would prefer to have a base type setup for the A320Neo.  These parameters are the SimBrief base typeA320-200 with some changes made to reflect differences in weights & fuel flow - and in fact his numbers aren't that accurate.

I currently use these parameters  https://tinyurl.com/y34wb8bv  which seem to be quite accurate, again considering the ever changing MSFS A320 performance numbers.

**Comment by CaptVirtual** [comment]
> The simbrief devs have said it's not currently possible to create an accurate profile as there's a number of parameters that Airbus keeps secret regarding the Mei line.

Good excuse, but how do they account for all their other Airbus parameters?  Surely these would be secret as well?  😀

**Comment by Benjozork** [comment]
> I understand this request could be argued to be a SimBrief issue, which it is, however there are also many requests on their support forums with no results to date -requests dating back many years.

While I understand the frustration caused by a lack of response from the SimBrief devs, we still cannot accept this issue in this repository because it cannot be fixed by changes to the plane files.

**Comment by CaptVirtual** [comment]
Okay, fair enough

**Comment by NateHiggers88** [comment]
> The simbrief devs have said it's not currently possible to create an accurate profile as there's a number of parameters that Airbus keeps secret regarding the Mei line.

What ? This is even Public:
https://www.airbus.com/content/dam/corporate-topics/publications/backgrounders/techdata/aircraft_characteristics/Airbus-Commercial-Aircraft-AC-A320.pdf
Should be the WV054 or WV055 model
