### ISSUE TITLE
[REQUEST] FCU manage and selected function

### ISSUE THREAD

**Issue by Neirarc** [flybywiresim/a32nx#2953]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**

HI, Until recently I used FSX with FSLABS to fly, I really like the FLYBYWIRE project, but if there is something that bothers me a lot, it is the way to manipulate the FCU.

The function of manage and selected is uncomfortable, in the fslab it is very useful, mouse left button manage, right button selected and with the wheel you change the selected (numbers).

I hope you can implement these functions, because acting fast on the flybywire is very difficult and uncomfortable

Rgds
Cristobal Neira
First Officer A320 Fam

**References**

**Additional context**

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by theomessin** [comment]
I'll see if this something I can implement for #2935
