### ISSUE TITLE
[BUG] Random Anti Ice ECAM Warning

### ISSUE THREAD

**Issue by A320PHX** [flybywiresim/a32nx#2961]
**Mod Version**
Stable o.5.2

**Describe the bug**
Random Ecam message pops up stating ice detected. In non icing conditions.

**To Reproduce**
I just started a random flight from Denver with few clouds. Set weather to summer and a temp of 32*C and took off. Ice detected warning happened well above the clouds.

**Expected behavior**
No ice warning unless icing is actually occurring.

**Actual behavior**
Clear day no clouds, ecam stating icing detected. No visible ice forming.

Was this working before/when did the issue start occurring?
It was not happening in 5.1.1 to the best of my knowledge.

Is this a problem in the vanilla unmodded game?
Unknown. I don't think this ecam message is simulated in the default though.

**Comment by MisterChocker** [comment]
The ECAM Warning appears when icing is detected. Also note that the simulator is currently overdoing the ice effect.

**Comment by A320PHX** [comment]
I tried both with few clouds and no clouds. Both times, no visual icing was forming. When there were clouds, it was happening well above the clouds when they were present.

**Comment by Lucky38i** [comment]
> I tried both with few clouds and no clouds. Both times, no visual icing was forming. When there were clouds, it was happening well above the clouds when they were present.

Lack of clouds doesn't mean there's a lack of moisture in the air

**Comment by A320PHX** [comment]
That is certainly true, however I do not use live weather, only preset conditions. For this flight it was the middle of summer, 32*C ground temp, first noted long after flying through the cloud level. With my settings, there was no way there was any icing happening... Microsoft's icing texture is over exaggerated and nothing was forming on the plane. 

I am pretty sure this is just a bug with the ecam warnings.

**Comment by sidnov** [comment]
This was a simulator issue (excessive icing) which has been fixed since SU4.
https://forums.flightsimulator.com/t/excessive-icing-effect/266397/
