### ISSUE TITLE
[BUG] Map glitch and flight path glitch causing massive FPS drop

### ISSUE THREAD

**Issue by CodeSoFresh** [flybywiresim/a32nx#2962]
**Dev Version**

{
  "built": "2021-01-09T07:07:10+00:00",
  "ref": "",
  "sha": "",
  "actor": "David Walschots <davidwalschots@users.noreply.github.com>",
  "event_name": "manual"
}

**Describe the bug**

When crossing the 180 degree meridian between alaska and russia, the map on the ND display and the vfr map in the game show a track going all the way around the world in the opposite direction in order to reach the waypoint after the meridian. This is specifically limited to last waypoint in the western hemisphere and the first waypoint in the eastern hemisphere

The map glitch caused almost a 50% fps drop with constant stutters until I selected DCT to a waypoint in the eastern hemisphere closer to the destination. Then the fps went back to a normal value for me, but the ND map was still showing and oppsite track line. As soon as i crossed over the 180 meridian the ND map showed a normal flight path track and I could complete the flight as normal. The same thing also happened to my friend who I was group flying with. Both of us had the exact same dev version and had flown several legs completely fine. Just this time the whole map issue arose. 

**To Reproduce**

1. Create a flight plan which crosses the 180 meridian
2. Spawn in the sim
3. You should already encounter stutters
4. Select DCT to the first waypoint on the other hemisphere and the stutters should go away, but the ND map and VFR map should still be glitchy

**Expected behavior**

Crossing the 180 meridian shouldn't cause this kind of navigational issue, The flight path should be a constant line between waypoints

**Actual behavior**

Flight path line is glitched out and shows an opposite track between the last waypoint in the old hemisphere and first waypoint in the new hemisphere. This also causes a massive FPS drop and stutters

**References**

![Capture](https://user-images.githubusercontent.com/23385862/104109324-03c5cc80-52cd-11eb-81b6-c117010b8add.PNG)
![Alaska](https://user-images.githubusercontent.com/23385862/104109440-2e645500-52ce-11eb-8964-d01569d007a1.PNG)
![Alaska](https://user-images.githubusercontent.com/23385862/104109317-f1e42980-52cc-11eb-8cdb-778d095b49c7.PNG)

**Additional context**

Was this working before/when did the issue start occurring?

Never encountered this before as I havent flown over the pacific until now

Is this a problem in the vanilla unmodded game?

Unsure

Discord username (if different from GitHub): A. Jankovic

**Comment by kiokio0987** [comment]
This problem also occurs on the B747 and B787.
 I found this bug in version 1.8.3.0 and reported it to Zendesk, but there was no response.
![B747](https://user-images.githubusercontent.com/75520968/104114426-aae74a00-5347-11eb-8ff6-fe3666dd3da3.jpg)

**Comment by Saschl** [comment]
There seems to be an issue in SVGFlightPlanelement.js where it caluclates the longitude delta between two waypoints. As the coordinates go from -180° to 0° to 180° degrees the calculation `const deltaLong = Math.abs(lastLong - this.latLong.long);` is wrong (e.g. 178 - -179 = 357 instead of 1)

**Comment by 2hwk** [comment]
Fixed by #4953 closing ☑️
