### ISSUE TITLE
[BUG] Flaps logic on axes and plane falling

### ISSUE THREAD

**Issue by DecMoonFR** [flybywiresim/a32nx#2969]
**Mod Version**

{
  "built": "2020-12-25T10:12:36+00:00",
  "ref": "",
  "sha": "",
  "actor": "Benjamin Dupont <benjozorkfr@gmail.com>",
  "event_name": "manual"
}

**Describe the bug**

The logic for FLAPS is not the same between keys and axe.
On flight, increase flaps with key make flaps to 1. With axe, it make flaps 1+F
After 10 secondes the plane fall like a stone

**To Reproduce**

On ground after cold and dark start
1. Increase flaps with key => Flaps 1+F
2. Reduce flaps with key => No flaps
3. Increase flaps with axe => Flaps 1+F

After takeoff and a stabilized flight at any altitude, AP on with selected speed 220 kts (holding speed).
1. Increase flaps with key => Flaps 1
2. Stay 30 secondes
3. Decrease flaps with key => No flaps
4. Increase flaps with axe => Flaps 1+F
5. After 10 secondes, the plane fall to the ground

If the speed is bellow 215 kts (I try 210), it's the same except the plane don't fall.

**Expected behavior**

The logic with axe nee to be the same as key press

**Actual behavior**

**References**

https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZ_zcn29wQ1jVT2ZMplNkIJI_fDMXS2AvCLw&usqp=CAU

**Additional context**

I've got this bug with TCA Quadran Add On from Thrustmaster. This is the first time I use an axe for flaps.

In vanilla the logic for flaps is the same :
- Increase with key => 1+F on ground, 1 during flight
- Increase with axe => 1+F on ground, 1+F during flight
Except the plane don't fall after 10 secondes with seed higher than 215kts.

Discord username (if different from GitHub):

DecMoon#9041

**Comment by MisterChocker** [comment]
Please retry with latest master or latest stable (0.5.2). Should be fixed by now.

**Comment by DecMoonFR** [comment]
Ok, it seem i had a bug with my installer app who not update very well. It works with last dev

{
  "built": "2021-01-10T02:34:18+00:00",
  "ref": "",
  "sha": "",
  "actor": "Tyler Knox <16512508+tyler58546@users.noreply.github.com>",
  "event_name": "manual"
}

**Comment by MisterChocker** [comment]
Closing since issue is already resolved.
