### ISSUE TITLE
GPS not working

### ISSUE THREAD

**Issue by amanlulo** [flybywiresim/a32nx#2977]
Hi,
  whenever I try to use the ctrl+E function, the GPS doesn't work; I can't see the HSI 
![FlightSimulator 2021-01-10 20-48-50-07](https://user-images.githubusercontent.com/72014870/104133827-5c0cd500-5386-11eb-85b0-6b7bbdd329df.jpg)
Thanks for any help & regards,
      Fulvio

**Comment by Benjozork** [comment]
Does not follow issue template.

Your ADIRS is not aligned.
