### ISSUE TITLE
[BUG] parking brake, flaps and airbrake activates during flight, taxi or standing still, or gear down

### ISSUE THREAD

**Issue by cptleol** [flybywiresim/a32nx#2978]
**Mod Version**
 release version

**Describe the bug**
 When standing still, taxi or takeoff or in flight airbrakes, flaps and landing gear can activate without interakting with hardware as joystick or keyboard.

**To Reproduce**

1. Start a new flight from anywhere
2. Start making procedures preparations for flight and listen to the clicking from flaps, parking brake or air brakes and its activeted. in flight gear down can happen especially on climb and cruise.
3. Thats it.

**Expected behavior**
 Expected behavior is that i control all these.

**Actual behavior**
 i dont have control of flaps, airbrake, gear down at all on random ocations

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game? Nope

Discord username (if different from GitHub):Cmdr_King

**Comment by ErikNL80** [comment]
Which hardware are you using? Sounds like a known issue where an axis is assigned but not used may causing this. Not an A320nx issue...

**Comment by MisterChocker** [comment]
When using the Thrustmasters TCA Quadrant, unbind all key binds that are not used.

**Comment by DFWSupertrooper** [comment]
So, he may be onto something here...I haven't had _any_ control issues with this A/C in a LONG time, with TCA.  Today, mid-flight, my speed brakes and flaps fully deployed at one point at FL380, and my Throttle 1 Axis is no longer controllable using the TCA.  Went into the control settings to try to look at sensitivity and assignment, it's present but non-responsive.  I unassigned and reassigned the Throttle 1 axis and no dice...had to use the mouse to move throttle 1 back into alignment.  

This is a real bug, although I don't know what's causing it.  Perhaps someone can check this on the base A320 and se if it happens?  I'll be flying another flight after I land (assuming I can safely do so in this situation).  It did not happen until I downloaded the new dev version this morning - first flight.  TCA worked fine yesterday and all days prior.

**Comment by DFWSupertrooper** [comment]
FYI, I have deleted all missing functions to leave only what should be on the throttles (removed the ones assigned to the add-on I do not own).  Throttle 1 Axis is unable to move using TCA now.  Will recheck after restart and if missing will recalibrate to isolate actual hardware issue vs software.

**Comment by DFWSupertrooper** [comment]
After landing, exited to main menu to check control setup.  Throttle 1 still unresponsive.  Unplugged/replugged TCA and control returned.  Restarting simulator and will check next flight using Custom FBW.

**Comment by DFWSupertrooper** [comment]
Issue did not re-occur using latest FBW Custom mod after reconfiguring TCA for custom throttle ini use.  Last flight KORD-KLAS OK.

**Comment by MisterChocker** [comment]
This seems to be an already known issue to occur when having key binds to non existing hardware.

@cptleol can you please test @DFWSupertrooper 's proposed solution?

**Comment by marcsoler** [comment]
@MisterChocker Many issues are hardware-related. Maybe it would be helpful for you guys to update the bug issue template so that control-hardwares are listed.

**Comment by cptleol** [comment]
Hi, i will test tonight and see if it helps.

Den ons 13 jan. 2021 12:18DerL30N <notifications@github.com> skrev:

**Comment by MisterChocker** [comment]
Closing since no response from op
