### ISSUE TITLE
[REQUEST] Make installer images undraggable 

### ISSUE THREAD

**Issue by ErickSharp** [flybywiresim/a32nx#2981]
**Is your feature request related to a problem? Please describe.**

Yes, at the moment, the user is able to drag certain image elements on the installer such as the plane drawings of the a320 and a380, as well as the image on the engine variant. 

**Describe the feature you'd like to see implemented**

Change the code of the installer to make draggability of these image elements not possible. 

**References**

N/A

**Additional context**

Discord username (if different from GitHub): Erick [Z-6]#6484

**Comment by Benjozork** [comment]
Please create this issue on the installer repo
