### ISSUE TITLE
[BUG] Map Display broken, and flight plan altered on the VFR map.

### ISSUE THREAD

**Issue by vstaritz** [flybywiresim/a32nx#2982]
**Mod Version** 
Latest dev build

**Describe the bug**

Halfway through a KSFO/KLAX flight, i came back to the sim and the noticed the constraints on the map display were misplaced ( like two overlays not correctly matched on top of each other ).
Switching from different map types has left the display frozen. At first i thought the plane stopped following the plan but after reaching the turn towards the approach the plane kept following the plan but it was the VFP map showing incorrectly that i was meant to direct to the airport. It seems like the Approach and transition were deleted at some point during the flight and broke the map display. It probably happened as i was tabbed out but you wouldn't notice unless having the VFR map open as it happens. The instrument display seems to work fine and the correct flight plan is still in the FMC and the AP is following it. LS mode seems to work as well.
**To Reproduce**

1. KSFO/01R STIK4 EBAYE IRMN2 KLAX
2. Cold and dark regular departure.
3. ???
4. UI breaks.

**Expected behavior**

Self explanatory

**Actual behavior**

At some point the plane and the relative LNAV path is frozen, the next waypoint distance and ETA is frozen. It seems constraints keep moving. If you switch to other types like Rose or Plan some features remain stuck on the display or disappear. After switching the constraints toggle on and off constraints are entirely gone.

**References**

![image](https://user-images.githubusercontent.com/74994643/104139586-ebc57a00-53ac-11eb-8b5a-ff1ea0cb6bf9.png)

**Additional context**

Was this working before/when did the issue start occurring?
Have not seen this before. Last time i flew this plane was several weeks ago.

Is this a problem in the vanilla unmodded game?
Did no try.

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Do you have any other mods installed ?

**Comment by vstaritz** [comment]
The workingtitle G3, G1000 and G3000, CJ4, liveries and unreal weather. I have to try that again without mods, i'm trying it with the same setup right now.

**Comment by vstaritz** [comment]
Here's a clearer view of what i mean. Don't mind the heavy crosswind. For whatever reason on the VRP map EMKES isn't there. Red pen is the actual path AP is flying.
In the case of the KLAX flight in my first post, the entire approach was gone halfway through the flight but as i said the AP was still following it fine and i landed using the LS system without problems.
![image](https://user-images.githubusercontent.com/74994643/104213774-f75d8300-5436-11eb-9a75-76d1c1a902d8.png)

**Comment by vstaritz** [comment]
entirely possible there's something wrong with the game. The 208 was somehow uninstalled from last time i used it a few days back and jsut about every aircraft i had to update through the content manager

**Comment by vstaritz** [comment]
This stopped happening after removing everything. It did happen after fixing the Garmin mods so it's probably related to either them, the liveries or the TBM and 208 improvements mods.

**Comment by MisterChocker** [comment]
Closing since issue is related to a mod conflict.
