### ISSUE TITLE
[BUG] "Starter Engaged" light illuminated on Honeycomb Bravo Throttle

### ISSUE THREAD

**Issue by rduatc** [flybywiresim/a32nx#2986]
**Mod Version**

{  "built": "2021-01-11T06:11:34+00:00",
  "ref": "",
  "sha": "",
  "actor": "Vincent Koeman <koeman@chainels.com>",
  "event_name": "manual"
}

**Describe the bug**
On a Honeycomb Bravo Throttle, the annunciator light "Starter Engaged" stays illuminated. This is not an issue with the default A320Neo
**To Reproduce**
Turn on the sim, load the A320NX

1.Turn on the sim
2., load the A320NX
3.

**Expected behavior**
 Light Should be off.

**Actual behavior**
loaded A32NX aircraft in sim, then light came on and remains illuminated.

**References**

**Additional context**

Was this working before/when did the issue start occurring? Throttle Quadrant just released, no past data.

Is this a problem in the vanilla unmodded game? No

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
This is difficult to debug since I do not know what the peripheral looks at to light up that indicator.

Would it be possible for someone to contact Honeycomb Aeronautical and ask them which game parameters they read ?

**Comment by Saschl** [comment]
There is a special tool by honeycomb/aerosoft that reads the vars and sets the lights. I will check later which variables it reads, there's a configuration file for that.

**Comment by joniatus** [comment]
from the config.json file for the lights tool, not sure if this helps...

{
      "ByteIndex": 3,
      "BitIndex": 3,
      "Condition": "A:GENERAL ENG STARTER:1, bool",
      "ConditionValue": "=1",
      "EN": "Starter",
      "DE": "Starter"
    },

**Comment by Benjozork** [comment]
I will take a look. Thanks.

**Comment by Saschl** [comment]
Just fyi the light stays illuminated in the default as well after starting an engine. Only turns off after shutting down engine 1. If you haven't started yet I could have a look as well since I messed with the starter template a while ago

**Comment by jcabanascachi** [comment]
I have this problem too, the variable GENERAL ENG STARTER:1 remains in 1 while the engine is running, there is another variable named GENERAL ENGINE STARTER ACTIVE that right now that I am flying is set to 0. Let me check if this variable works to turn that light off.

**Comment by jcabanascachi** [comment]
Hi, I found a solution here but it only works for the A320, in the config.json of the AFC Bridge, change these lines:

{
"ByteIndex": 3,
"BitIndex": 3,
"Condition": "A:GENERAL ENG STARTER:1, bool",
"ConditionValue": "=1",
"EN": "Starter",
"DE": "Starter"
},

Change those lines for these ones:

{
      "ByteIndex": 3,
      "BitIndex": 3,
      "Condition": "A:TURB ENG IGNITION SWITCH EX1:1, enum",
      "ConditionValue": "=2",
      "EN": "Starter",
      "DE": "Starter"
    },

The Started Engaged light is going to be ON as far as you have the engine mode selector in IGN/START. For the 747 and 787 it won't work, For the boeings the GENERAL ENG STARTER:1 to :4 are needed but these commands will maintain the light on with the A320.

**Comment by rduatc** [comment]
Thanks @jcabanascachi for the research, I will implement the change by copying and renaming a new profile for the A320, and saving the changes there. That will leave the profiles I use for the 787 and 747 intact. I will report back on how it works out.

**Comment by rduatc** [comment]
I'm now guessing  that there is only one throttle config file that all profiles use, which explains your concerns that it only works on the A320 and that the others might be affected. I also noticed a new config file was released for the Bravo on Thursday the 21st. I'm curious to see if perhaps they may have done something to help out.

**Comment by jcabanascachi** [comment]
I got my bravo last saturday (January 23th) since then I started investigating how to configure it, I got the config file from honeycomb page and it was version 2.1. In that version, the starter engaged light was mapped to GENERAL ENG STARTER:1 wich maintains the light on as long as the engines are running. That is the main problem I have found so far, the simulator uses a lot of variables and the one I found that changes its value when I move the engine mode selector was TURB ENG IGNITION SWITCH EX1:1. That is why I use it in json file. But that variable is not used in the other airliners. If I could find a variable used by all aircrafts in MSFS indicating that the engines are starting, I would use it for the json file to have only one profile.

**Comment by rduatc** [comment]
@jcabanascachi, I tried your fix and it works well. Thanks for your help.

**Comment by jcabanascachi** [comment]
@rduatc  Great, I also have the fix for that light for the 747 and 787 if you want it, it works ok for both planes. I am also working in the whole profile with Spad.next to have fully functional the AP buttons and switches (mainly lights) and all the leds working properly for the A32NX, but an official license of spad.next will be required. Also increments by 1 in airspeed and heading inputs because that doesn't work well either.

**Comment by rduatc** [comment]
@jcabanascachi, Absolutely I would be interested in all of those things. I really like the Alpha and Bravo combination, and I would love to be able to explore all that is possible with them. The heading, airspeed tweaks are definitely must haves that I hope can be fixed.

**Comment by rduatc** [comment]
@jcabanascachi , I also will be happy to purchase a copy of Spad.next if you come up with a profile that works well.

**Comment by jcabanascachi** [comment]
I only have the Bravo, don't have plans for the Alpha. I am half way of the profile, let me finish it and I can share it. Spad.next lets you have a trial version for 15 days before purchasing the license, but wait for me to have it done. I don't know if we should continue this conversation here, my username in discord is jcachi, I am a FBW donator if it is easier that way to find me.

**Comment by rduatc** [comment]
@jcabanascachi, sent you a DM.

**Comment by jcabanascachi** [comment]
For the Honeycomb Bravo there is a new tool on flightsim.to named Better Bravo Lights, I recommend it, it is easier to configure the ligths of the Bravo and it accept LVARs

**Comment by sidnov** [comment]
A lot of default bindings are not used anymore on the A32NX and are substituted with LVars, thus, the suggestion above is the only ideal way to workaround the problem (as it is very specific to a peripheral device).
