### ISSUE TITLE
[BUG] A320NX Installer keeps saying'A320NX version is out of date, please consider updating'

### ISSUE THREAD

**Issue by ErikNL80** [flybywiresim/a32nx#2987]
**Mod Version**

  "built": "2021-01-11T06:11:34+00:00",
  "ref": "",
  "sha": "",
  "actor": "Vincent Koeman <koeman@chainels.com>",
  "event_name": "manual"

**Describe the bug**

I am using the A320NX installer, v0.7. Since a few days I have an  'out of date' message, while the files are not updated... This message keeps returning everytime the installer starts. Found a similar issue on the installer GitHub page, and they refer to the fact something might be wrong in the repository causing this: https://github.com/Externoak/A32NX-installer/issues/15

**To Reproduce**

1. Download the A320NX installer
2. Install the dev version
3. Close the installer
4. Start the installer again

**Expected behavior**

I would expect the installer saying the version is current.

**Actual behavior**

The installer keeps saying version is out of date.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Yes, was working before. Issue occured once in december, but was fixed by then.

Is this a problem in the vanilla unmodded game?
N/A

**Comment by ErikNL80** [comment]
Also mentioned the issue here: https://github.com/Externoak/A32NX-installer/issues, but since a similar issue was closed by reffering to the A320mod itself I decided to create this BR.

**Comment by Jehova-Godfather** [comment]
Same issue for me.

**Comment by Benjozork** [comment]
This is an installer bug and out of scope for this repo.

**Comment by polyefko** [comment]
Still  happening to me as well

**Comment by Benjozork** [comment]
I gave the status of the fix above your comment.

**Comment by polyefko** [comment]
thanks for clarification so quickly sorry to bother you!

**Comment by AdamNZ** [comment]
> 
> 
> This is an installer bug and out of scope for this repo. It's fixed with the upcoming installer v1.0

Thanks! Will the updater auto-upgrade or will we have to re-download it?

**Comment by Benjozork** [comment]
It will auto-update, but the switch from 0.7 to 1.0 won't.
