### ISSUE TITLE
[BUG] Can't change CRZ FL during flight

### ISSUE THREAD

**Issue by Cthulhus** [flybywiresim/a32nx#2988]
**Mod Version**
  "built": "2021-01-11T06:11:34+00:00",

**Describe the bug**
During a flight, I can't change the CRZ FL on the MCDU.

**To Reproduce**
1. Make a flight (with or without SimBrief MCDU import)
2. When you reach your targeted FL, try to change it
3. I can't and forced to stay at my first entered FL

**Expected behavior**
Be able to set the FL I want (ATC request or for fuel consumption)

**Actual behavior**
No data can be entered

**Comment by Erni1949** [comment]
@Cthulhus, you're not describing how you tried to change the FL. That makes me assuming you tried to do that in the INIT 1/2 page. However the Airbus has a strict recruising rule during climb. You should go to the PROG page and change in the left top corner the FL.
This works in the Stable version 0.5.2., I user It this afternoon.

**Comment by MisterChocker** [comment]
Also note, if on cruise alt and selecting a higher altitude via the fcu, the cruise altitude will update and the mcdu advises you with a message as well.

**Comment by Erni1949** [comment]
MisterChocker made a correct addition to my comment. I described the situation when climbing.
I have never tried the higher altitude via the FCU but I will try later this week in my own testflight.
Note: you should alsof be able when cruising on the planned altitude, to enter a lower altitude via the FCU, provided you are more than 200 NM from the destination. But I have never used that.

**Comment by MisterChocker** [comment]
> MisterChocker made a correct addition to my comment. I described the situation when climbing.
> I have never tried the higher altitude via the FCU but I will try later this week in my own testflight.
> Note: you should alsof be able when cruising on the planned altitude, to enter a lower altitude via the FCU, provided you are more than 200 NM from the destination. But I have never used that.

this might not be implemented yet.

**Comment by Cthulhus** [comment]
> @Cthulhus, you're not describing how you tried to change the FL. That makes me assuming you tried to do that in the INIT 1/2 page. However the Airbus has a strict recruising rule during climb. You should go to the PROG page and change in the left top corner the FL.
> This works in the Stable version 0.5.2., I user It this afternoon.

Thanks ! After few years of sim flying the A320 (FlightFactor / Xplane) I just realized with you that I'm doing this wrong ! Thanks a lot !

**Comment by MisterChocker** [comment]
I am closing since issue seems to be resolved.
