### ISSUE TITLE
[BUG] Packs fault light

### ISSUE THREAD

**Issue by Tibu73-ui** [flybywiresim/a32nx#2992]
I noticed that packs lights are lighting fault

**Mod Version**
 Dev version 0.6
 

**Describe the bug**
 packs are fault lighting even when I start engines.

**To Reproduce**
 start sim in cold and dark and check the packs on overhead panel.

1.
2.
3.

**Expected behavior**
 packs off / on 

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by hotshotp** [comment]
packs are not operational yet

**Comment by Benjozork** [comment]
"BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning"
