### ISSUE TITLE
[BUG] ND Rainbow screens when loading into landing challenges

### ISSUE THREAD

**Issue by Matthewlad00** [flybywiresim/a32nx#2998]
**Mod Version**
{
  "built": "2021-01-11T06:11:34+00:00",
  "ref": "",
  "sha": "",
  "actor": "Vincent Koeman <koeman@chainels.com>",
  "event_name": "manual"
}
**Describe the bug**
when i load into landing challenges the screen messes up and goes rainbow 
**To Reproduce**
1. Load into the paris landing challenge
**Expected behavior**
I expected everything to work normally and not have messed up screens
**Actual behavior**
screens went rainbow
**References**
![Screenshot (100)](https://user-images.githubusercontent.com/76802555/104224041-51147c00-543c-11eb-83a5-5e9d0162c7d5.png)
**Additional context**
Was this working before/when did the issue start occurring? It just started occuring
Is this a problem in the vanilla unmodded game? no 

Discord username (if different from GitHub): matthewlad000

**Comment by Benjozork** [comment]
Do you have any other mods installed ?

**Comment by Matthewlad00** [comment]
> Do you have any other mods installed ?

yes i do i have gatwick and unreal weather

**Comment by Matthewlad00** [comment]
@Benjozork

**Comment by Benjozork** [comment]
Alright

**Comment by Benjozork** [comment]
Is this but still present in the development version ? Issues related to screens erroring out have been resolved

**Comment by Matthewlad00** [comment]
no i do not have this issue anymore but i have an issue where when i spawn into landings/landing challenges the screens say this 
![image](https://user-images.githubusercontent.com/76802555/104950704-115c1000-59b9-11eb-9b48-4f228d214720.png) (ignore the red line its a screenshot from a youtube video as i have not been on the sim recently) @Benjozork

**Comment by Benjozork** [comment]
Please then open another issue

**Comment by Matthewlad00** [comment]
ok @Benjozork
