### ISSUE TITLE
a32NX mod don't work properly

### ISSUE THREAD

**Issue by albert1963** [flybywiresim/a32nx#3000]
Hello i have many issues with my A320 airplanes,
The wipers are kept running all the time, impossible to off it, the button is not working indeed,
I'm not able to set irs to align or nav, the buton is disabled also, same case for wings antice , engines antice.

I've tried with different versions of flybywire from the latest one to the 0.3 , but the issue are still there.
Help me please!
Thanks

**Comment by Benjozork** [comment]
Does not follow provided issue template

**Comment by pepperoni505** [comment]
@albert1963 Please update YourControls if it's installed
