### ISSUE TITLE
[BUG] Downloader says development build out of date all the time

### ISSUE THREAD

**Issue by fullerhkz** [flybywiresim/a32nx#3006]
Every time I run Downloader, the message is displayed that the build dev is out of date, even downloading the latest one directly from the github link. I already removed the A320NX from the Community folder and downloaded the Downloader again but the problem persists. This occurs immediately after each update

**Comment by sn3akz** [comment]
Can confirm

**Comment by Benjozork** [comment]
This repo is for the A32NX mod, not the installer.

We are aware of this issue and it's fixed in the upcoming installer update.
