### ISSUE TITLE
[BUG] Downloader says that the dev build is always out of date

### ISSUE THREAD

**Issue by fullerhkz** [flybywiresim/a32nx#3007]
**Mod Version**

"built": "2021-01-12T06:10:20+00:00",
  "ref": "",
  "sha": "",
  "actor": "DerL30N <leon.beeser@yahoo.de>",
  "event_name": "manual"

**Describe the bug**
Downloader says that the dev build is always out of date

**To Reproduce**

running the downloader app

1.exactly after updating the dev build, I am informed that it is out of date
2.
3.

**Expected behavior**

let the downloader inform you that the build is up to date since I just checked in seconds ago

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?
it wasn't happening / started yesterday

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
I already responded to your issue.

**Comment by fullerhkz** [comment]
Sorry, but I didn't opened another issue.

Em ter, 12 de jan de 2021 14:41, Benjamin Dupont <notifications@github.com>
escreveu:

**Comment by Benjozork** [comment]
![image](https://user-images.githubusercontent.com/4503241/104352512-c3389f80-54d4-11eb-9f96-993a751d66a2.png)
