### ISSUE TITLE
[BUG] Speed constraints erroneously in MCDU en route and slowing A/C at CRZ FL.

### ISSUE THREAD

**Issue by DFWSupertrooper** [flybywiresim/a32nx#3013]
**Mod Version**
Latest Custom FBW (D/L 12-Jan AM)

**Describe the bug**
When at CRZ, MCDU shows speed constraints at some waypoints mid-journey and A/C erroneously slows to match.  

Example: Mid-flight en route from KORD to KLAS, used following: DCT VORIN DCT IOW DCT CNOTA DCT LNK DCT MCK DCT FQF DCT SINRY DCT CHESZ DCT GGAPP SITEE4, CRZ FL360.  

At SINRY (middle of route), MCUD displayed speed constraint of 250K, while managed CRZ was 290.  A/C automatically slowed to 250K prior to SINRY and automatically increased back to 290K after passing CHESZ.

Again, at GGAPP where MCDU indicated 210K, A/C dropped to 210K mid cruise once passing.  Had to use speed hold mode from thence.  Descent wasn't to begin until much later.

**To Reproduce**
1. Plan flight using IFR/High Alt Option.
2. Load A/C cold and dark and go through pre-flight MCDU check of FPL.
3. Note any constraints mid-flight (cannot be cleared).
4. Fly planned route and pay attention at noted waypoints.

**Expected behavior**
At CRZ, A/C should maintain planned speed for CRZ until descend mode is activated, regardless of waypoints below and any constraints that may apply at such points as a part of other STAR/SID routes.  No speed constraints should load on ANY waypoints during planned route (after departure, before arrival/approach).

**Actual behavior**
A/C changes speed to match constraints in MCDU which cannot be cleared/erased.

**References**
N/A

**Additional context**
N/A

Was this working before/when did the issue start occurring?
Prior to using updated version, this was not an issue.  I believe these changes were implemented a few days ago, right around the 1/7/21 MSFS update.

Is this a problem in the vanilla unmodded game?
Doubt it since the MCDU is primitive.

Discord username (if different from GitHub):
N/A

**Comment by DFWSupertrooper** [comment]
I apologize if this is elsewhere noted.  I couldn't locate any similar posts.

**Comment by Watsi01** [comment]
Yepp, now that's happening. I'll remove the constraints in CRZ phase.

**Comment by Watsi01** [comment]
@DFWSupertrooper Change is now in the dev version. Could you check it with the same route again?

**Comment by DFWSupertrooper** [comment]
@Watsi01, is this change also applied to the FBW Custom already for testing?

**Comment by Watsi01** [comment]
I should be up to date right now. But I'm not sure.

**Comment by DFWSupertrooper** [comment]
> I should be up to date right now. But I'm not sure.

I'll check it out in a couple of hours and report back.

**Comment by DFWSupertrooper** [comment]
I had the issue on an other flight yesterday as well, but I've redownloaded the mod, in case mine yesterday had  just missed the updated fix.  I'll retry the same flight later today and let you know.  

FYI, I've made it a habit to check thru the flight plan on load to eliminate duplicate legs on arrivals anyway (which happens sometimes) and now I've begun looking for constraints at CRZ before departure as well.

**Comment by DFWSupertrooper** [comment]
OK, I loaded up the same FPL.  In the MCDU, there are constraints present at CRZ (250K@FQF and 210K@CHESZ).  I'll fly the plan and see what happens.

**Comment by DFWSupertrooper** [comment]
Great news (I think).  Overflew first listed constraint and the A/C ignored...continued on at planned CRZ.

**Comment by DFWSupertrooper** [comment]
> Great news (I think). Overflew first listed constraint and the A/C ignored...continued on at planned CRZ.

Overflew second waypoint with constraint (CHESZ) as well...no issue.  A/C ignored constraint and continued on to GGAPP. :)

**Comment by DFWSupertrooper** [comment]
@Watsi01 I think your fix worked.  Current route contains no other constraints during CRZ so no further testing can be conducted on this flight.
