### ISSUE TITLE
[REQUEST] Intuitive In Game Headphone Sound Simulation 

### ISSUE THREAD

**Issue by n9533** [flybywiresim/a32nx#3025]
What I want 

I think it would greatly add to the realism if we were able to get more realistic cockpit audio by leveraging off the game's headphone sound setting by being able to activate it within the cockpit without settings, to simulate headphones being taken on and off.  That is my main request, to be able to activate that feature in a more realistic and accessible way. One idea I had was to be able to toggle this in the upcoming EFB, labelled as "ANC ON/OFF". While the headphones are on, it would be neat if inputs like music were made to sound like a real headset. 

Here are more related features that I'd like added, even if the request above gets rejected:

- Discord audio simulated as cockpit audio: Talking over discord with friends sort of ruins the realism and immersion when flying together, so I am proposing that the audio be made to sound like it would if pilots were talking to each other over the headset microphone.

References

Most A320 pilots use Bose A20's which can be a good headset to model this after

Additional Context: 

- Discord: N9533#1915

**Comment by hotshotp** [comment]
Here is what we are doing. It would be very difficult to program headphone simulation for every sound and would take weeks of work. We are simulating certain sounds that are natural, like engine noise, avionics fans, packs without headset - but stuff like pilot monitoring callouts that are coming later, or the cockpit GPWS warnings will be simulated as through headsets. We cannot control discord audio through the sim also.

**Comment by MisterChocker** [comment]
> We cannot control discord audio through the sim also.

Maybe there is another 3rd party program on the market for doing something like that, I know stuff like this exists for teamspeak.
