### ISSUE TITLE
[BUG] Unable to select approach runway without STAR, TRANS and VIA

### ISSUE THREAD

**Issue by Leon30217** [flybywiresim/a32nx#3026]
**Mod Version**
Master Branch Build (with custom FBW)

**Describe the bug**
impossible ILS approach without STAR in the FPlan

**To Reproduce**
1. MCDU Dep EDDS25
2. press Arrival
3. select ILS25
3. STARS displayed NO STAR
4. press Appr <VIAS
4. press <- NO VIAS
5. in Arrival Page is displayed VIA NONE and NO STAR
6. press INSERT
7. In the F-Plan - Arsut Arrival is still saved in the flight plan 
 

**Actual behavior**
The same behavior abovementioned, but when you additionally select another STAR f.e. TEKSI1W, and VIA NONE,
is the Arsut Arrival always still in the FPlan

**References**

![NO-STAR](https://user-images.githubusercontent.com/77197869/104493939-11819780-55d6-11eb-87eb-44e265648004.jpg)
![ENTER_STAR](https://user-images.githubusercontent.com/77197869/104493964-1a726900-55d6-11eb-9704-55e590b8b7b9.jpg)
![NEVERTHELESS_STAR](https://user-images.githubusercontent.com/77197869/104493972-1cd4c300-55d6-11eb-80b4-6f569e0aeefb.jpg)

Was this working before/when did the issue start occurring?
no
Is this a problem in the vanilla unmodded game?
i don´t know

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Waltscarter** [comment]
I have the same problem

**Comment by Benjozork** [comment]
I think this is fixed with #2831

**Comment by jbburrows1032** [comment]
Any update on this? @Benjozork? You linked to a pull request that we cant use and this is a critical issue that makes it very difficult to fly this plane.

**Comment by Benjozork** [comment]
> Any update on this? @Benjozork?

It's being worked on. Please be patient and understand I am a volunteer dev with a real life job and college.

> You linked to a pull request that we cant use

That's why it's a draft pull request, because it's not ready.

> this is a critical issue that makes it very difficult to fly this plane.

We are well aware - however, you probably know fixing those things is not trivial.

**Comment by jbburrows1032** [comment]
> > Any update on this? @Benjozork?
> 
> It's being worked on. Please be patient and understand I am a volunteer dev with a real life job and college.
> 
> > You linked to a pull request that we cant use
> 
> That's why it's a draft pull request, because it's not ready.
> 
> > this is a critical issue that makes it very difficult to fly this plane.
> 
> We are well aware - however, you probably know fixing those things is not trivial.

I get all that. I really do. But you cant close and link people to a "solution" when they cant actually use the thing you're linking too. IMO this should be your devs top priority as everything else is fairly stable EXCEPT for this. This is a fairly critical bug in the basic function of this plane. At least get people access to the fix you are telling people if you're going to link them to it. 

They are clearly alot of people complaining about it and your only "Solution" is to tell people a fix is coming and link them to said fix but dont give them access. If you dont have a fix, dont link them at all.

**Comment by Benjozork** [comment]
> I get all that. I really do. But you cant close and link people to a "solution" when they cant actually use the thing you're linking too

I'm sorry, where did I close this issue ? Oh wait, I didn't, and the author actually did by accident.

**Comment by Benjozork** [comment]
> They are clearly alot of people complaining about it and your only "Solution" is to tell people a fix is coming and link them to said fix but dont give them access.

BECAUSE IT'S NOT READY. Did I ever say it was a solution ? No. I simply noted it was gonna fix this problem.

> If your going to be a developer, you will need to work on your PR and service skills a bit my dude. The last thing you want to do is not help your "Customers" even if they are free ones.

I don't owe you anything. I work on this in my free time and I do whatever I want. We already provide what I consider to be the best support you'll get for freeware on Discord.

Linking issues to PRs that will solve them is something every OSS developer does on GitHub. Learn about how open source development works before making rude and misplaced comments with wrong assumptions (like that I closed the issue when I literally did not)

**Comment by Benjozork** [comment]
@Leon30217 I understand this was not your doing but I'm gonna lock this issue for the time being because of the unwelcome comments. I hope you understand.

**Comment by MisterChocker** [comment]
@Leon30217 An update for you, the linked pr got closed due to integrations and other leads with our custom autopilot and flight plan manager and guidance system, this the META issue #4028 this issue is related to.

You can also follow any progress by joining our discord.

**Comment by 2hwk** [comment]
Fixed by 4953 closing ☑️
