### ISSUE TITLE
A/C does not respect FCU alt

### ISSUE THREAD

**Issue by toffee2000** [flybywiresim/a32nx#303]
During managed CLB aircraft climbs past FCU alt instead of leveling off.

**Comment by Curtis-VL** [comment]
In managed climb would it not follow the flight plan instead of the altitude set on the FCU?

**Comment by PCGamesF1Tech** [comment]
During CLB it should level off if there was a constraint  (waypoint XYZAB -12000) and FCU set to 15000.
Without or after a constraint it should level off at FCU altitude. 

The plan ist just.... a plan. 
There will be a message on the MCDU for the step climb ahead
BUT
You"ll need an ATC clearance for climb or descent!

**Comment by toffee2000** [comment]
If FCU alt is below plan alt, it will stop climbing at FCU alt. Similarly, if FCU alt is above plan alt during descent, descent will stop until the alt knob is wound down and pushed/pulled. FCU alt always has priority over FMC.

**Comment by PCGamesF1Tech** [comment]
Yeah, that's what I was meant to say, somehow...
Priority yes, but it would do a level off at the magenta constraints in managed modes (CLB/DES). 
In managed modes the constraints (if reached/passed before FCU) have priority over the FCU

**Comment by jeffies04** [comment]
Hi folks, great work so far!

The aircraft must always respect the FCU altitude set by the pilot, especially in the case of ATC clearance. For example, if you are cleared to 12000, but your flight plan constraint is for 14000, you must comply with the clearance of 12000 and level off regardless of what constaint is published. If the controller tells you to maintain an altitude, it takes priority and the aircraft cannot just be disregarding what is dialed into the FCU -- it has the final say.

**Comment by lousybyte** [comment]
This should be fine now?

**Comment by MisterChocker** [comment]
Closing since no longer an issue.
