### ISSUE TITLE
[BUG] other Waypoints stay at Direct

### ISSUE THREAD

**Issue by Leon30217** [flybywiresim/a32nx#3030]
**Mod Version**
Master Branch Build (with custom FBW)

**Describe the bug**
When you get a direct from the ATC, you enter this in the MCDU. As far as good.
But the other waypoints stay. Normally the system deleted the other waypoints until the direct

**To Reproduce**

1. Insert DS515 (EDDM-EDDS) in path DIR
2. Direct displayed on the PMD
3. but the other waypoints still stay

**Expected behavior**

**Actual behavior**

**References**

![Direct](https://user-images.githubusercontent.com/77197869/104500417-b30ce700-55de-11eb-8d78-4069534ede97.jpg)
![Direct_1](https://user-images.githubusercontent.com/77197869/104500421-b56f4100-55de-11eb-817d-1e91ece077cd.jpg)

**Additional context**

Was this working before/when did the issue start occurring?
no
Is this a problem in the vanilla unmodded game?
i don´t know

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
Stop opening issues on this repository or you will be blocked from it. You have already opened 4 and I have told you many times THE ISSUE IS ALREADY REPORTED IN #1745.

This is your last warning.

Do NOT open more issues.
