### ISSUE TITLE
[BUG]  APU Bleed/pack sounds and improved engine rumbles (#3010) Not working FBW branch

### ISSUE THREAD

**Issue by mikecbr** [flybywiresim/a32nx#3035]
**Mod Version**
Latest FBW branch

**Describe the bug**
Added APU Bleed/pack sounds and improved engine rumbles Not working , it is only working in the DEV nromal branch , but no the FBW branch

**To Reproduce**

1. Engine switch from NORM MODE TO / IGN START , You can not hear the packs , In the dev its working as expected 
2.
3.

**Expected behavior**
Work like in the dev 

**Actual behavior**
Not working at all

**References**

**Additional context**

Was this working before/when did the issue start occurring?
No

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):

**Comment by hotshotp** [comment]
this is for the flybywire branch, they will update it later
