### ISSUE TITLE
Managed speed bug should drop to VAPP when APPR phase is activated 

### ISSUE THREAD

**Issue by toffee2000** [flybywiresim/a32nx#304]
When APPR is activated in FMC, the speed bug (magenta triangle) will jump to VAPP if speed mode is managed. However, the autothrust will slow to the next flap speed (S or F speed on PFD) only, and not to the speed bug, until flaps are set for approach. Hence, the behaviour currently is correct but the display of the speed bug is wrong.

**Comment by lousybyte** [comment]
Related #854
