### ISSUE TITLE
[REQUEST] Skip ADIRS alignment requirement

### ISSUE THREAD

**Issue by hi1213345446231** [flybywiresim/a32nx#3046]
**Is your feature request related to a problem? Please describe.**

have an option to skip the need to wait for adirs alignment

**Describe the feature you'd like to see implemented**

have an option to skip the need to wait for adirs alignment be that as an option in the check list (on a separate page so some one who wants to wait doesn't accidentally skip

**References**

--------

**Additional context**

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by tracernz** [comment]
You can already do that in the realism options on the MCDU I believe? Options are instant, fast, or realistic.

**Comment by Benjozork** [comment]
This is already implemented as stated above

Please use our Discord or the Discussions section for usage in questions.
