### ISSUE TITLE
[REQUEST] Navigation Needles in ARC Modes

### ISSUE THREAD

**Issue by Hor1463** [flybywiresim/a32nx#3055]
As in the real Airbus there have to be two needles for the VOR in the ARC Mode.

**Is your feature request related to a problem? Please describe.**

No

**Describe the feature you'd like to see implemented**

Needle in ARC Mode

**References**

Every Airbus

**Additional context**

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by MisterChocker** [comment]
@Hor1463 

> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning

Also please provide references and a proper description of the feature you'd like to see implemented.

**Comment by kiokio0987** [comment]
same request (#377) (#1859)

I have looked at the FCOM and video to see what we want to include.
Below are the 2019 spec FCOMs.
These are the ones I have at the moment that I could use as a reference.
If the reference is wrong, I am sorry.

References
[VIDEOS]
  Real (This video is for the A319, but I believe it is basically the same as the A320.)
  https://youtu.be/TEi-WX08ov8?t=36 (1:00~1:20)

  FSLabs A320-X (Prepar3D addon)
   https://www.youtube.com/watch?v=1IhzbfB-8pI&t=305s (5:00~)

[FCOM]
![WS000017](https://user-images.githubusercontent.com/75520968/104816732-57ea2700-5860-11eb-93f2-efe83ecbce80.JPG)
![WS000018](https://user-images.githubusercontent.com/75520968/104816740-5d477180-5860-11eb-8703-874ed04ac857.JPG)
![WS000019](https://user-images.githubusercontent.com/75520968/104816744-5fa9cb80-5860-11eb-9cbf-50107c109ef4.JPG)
![WS000004](https://user-images.githubusercontent.com/75520968/104816764-70f2d800-5860-11eb-8732-6a870632fa48.jpg)
![WS000005](https://user-images.githubusercontent.com/75520968/104816768-73553200-5860-11eb-8249-0ad124be4bac.jpg)
