### ISSUE TITLE
[BUG] "NO DH" for DH on PERF APPR page is not always allowed even for ILS RWY

### ISSUE THREAD

**Issue by frankkopp** [flybywiresim/a32nx#3056]
**Mod Version**
{
  "built": "2021-01-16T00:39:46+00:00",
  "ref": "",
  "sha": "",
  "actor": "Andreas Guther <andreas@guther.family>",
  "event_name": "manual"
}

**Describe the bug**
On the PERF APPR page one should be able to input "NO DH" into the DH field. This is not always possible.

**To Reproduce**
1. Create a flight to LIPZ (LOWW/34 F340 OSPEN3D OSPEN DCT ABRUK DCT SETAL DCT URAVA P125 TIBRO Q707 RISOM DCT LIPZ/04R)
2. setup approach in F-PLN to 4R Trans AKADO
3. input approach data
4. try to input "NO" into DH filed - will display "NOT ALLOWED"

I do use Navigraph data. Might be relevant. 

**Expected behavior**
For ILS "NO", "NODH", NO DH" should be allowed. Code actually says:
![image](https://user-images.githubusercontent.com/16833201/104752820-731d3f80-5757-11eb-9410-4b427d739f0f.png)

So it seems that Simplane.getAutoPilotApproachType() does not return 4 for this ILS approach.
See also screenshots

**Actual behavior**
MCDU shows "NOT ALLOWED" in scratch line in this case

**References**
![image](https://user-images.githubusercontent.com/16833201/104752390-e4a8be00-5756-11eb-9f7e-c8c854bac77b.png)
![image](https://user-images.githubusercontent.com/16833201/104752420-ed998f80-5756-11eb-9618-65e4e766e2df.png)
![image](https://user-images.githubusercontent.com/16833201/104752451-f5593400-5756-11eb-8fb6-f17ab2e17d4e.png)

**Additional context**

Was this working before/when did the issue start occurring?
unknown

Is this a problem in the vanilla unmodded game?
unknown

Discord username (if different from GitHub): Cdr_Maverick

**Comment by MisterChocker** [comment]
@beheh Do have this on your radar?

**Comment by beheh** [comment]
No, haven't looked at this yet. It's unclear to me whether this is a navdata issue or something else.

**Comment by ThatRedMelon** [comment]
Update on this, occasionally the approach type is returned as 0, which is no approach type, so the check for whether it is 4 or not fails and "NO DH" is unable to be entered.
![image](https://user-images.githubusercontent.com/34657891/106181526-9d2e2300-6195-11eb-9037-bb2390587293.png)

**Comment by frankkopp** [comment]
I think this is solved since a while.
