### ISSUE TITLE
[BUG] 2500 GPWS callout on departure

### ISSUE THREAD

**Issue by Samueleonard** [flybywiresim/a32nx#3057]
**Mod Version**

{
  "built": "2021-01-15T04:52:14+00:00",
  "ref": "",
  "sha": "",
  "actor": "DerL30N <leon.beeser@yahoo.de>",
  "event_name": "manual"
}

**Describe the bug**

when climbing out, a gpws callout is called when climbing through 2500ft

**To Reproduce**

1. depart and climb out as normal
2. listen when passing 2500ft agl

**Expected behavior**

callout only plays when decending through 2500

**Actual behavior**

callout plays when climbing through

**References**

**Additional context**

Was this working before/when did the issue start occurring?
i remember it working normally a few weeks ago so it is a recent problem

Is this a problem in the vanilla unmodded game?
probably not, but the gpws callouts were inop/wrong in the default anyway

Discord username (if different from GitHub):

**Comment by hotshotp** [comment]
cannot reproduce, they only happen if the terrain goes up faster than your vspeed compared to ground
