### ISSUE TITLE
[BUG] CTD after selecting 27L/R runway arrival in SBGR

### ISSUE THREAD

**Issue by tellurics** [flybywiresim/a32nx#3058]
**Mod Version**
Latest development version

**Describe the bug**
After selecting the runway arrival in SBGR, the game freezes and close

**To Reproduce**

1. I was planning the flight from SBFI to SBGR
2. After selecting a arrival from SBGR, happens the crash to desktop
3. The runway arrival is set as 27L and all arrival from this runway happen the CTD

**Expected behavior**
After selecting the runway arrival in SBGR in the runways 27L/R the game shouldn't freeze and close.

**Actual behavior**
The game freezes and close.

**References**

![20210115133610_1](https://user-images.githubusercontent.com/74205007/104753760-317c9c80-5737-11eb-8e30-8ad3849de3d0.jpg)

The ILS27LM, ILS27LN and ILS27LO approaches do not exist in real life and if you select one of them the game freezes and closes.

**Additional context**

Was this working before/when did the issue start occurring?
There has been a time that this is happening

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub): Marco#5326

**Comment by Benjozork** [comment]
Seems like a navdata issue, gonna look into it

**Comment by MisterChocker** [comment]
Can this be related to #2911?

**Comment by tellurics** [comment]
Maybe it can be related with #2911. It seems to be a navdata bug. @Benjozork have you figured out?

**Comment by MisterChocker** [comment]
Closing in favor of #3229.
