### ISSUE TITLE
For realism: IRL Nose light and Runway Turn lights switch off when Langing gear is retracted

### ISSUE THREAD

**Issue by CaptCQ** [flybywiresim/a32nx#306]
IRL, regardless of switch position, the Nose Light and the Runway Turn Lights switch off.
Ive noticed that the Runway turn light still protrudes into the flightdeck when gear up and if switch is on. Could we program it so that the lights turn of as IRL when gear is retracted, regardless of switch position.

**Comment by ThePilot916** [comment]
This is already present in the existing implementation from asobo, probably there is a circuit mismatch thats causing it to not function, whoever is planing on taking this up can look under a320_NEO_INTERIOR.xml. Should be pretty straight forward.

**Comment by ThePilot916** [comment]
#262 same fix should work

**Comment by AdenFlorian** [comment]
fixed by #389
