### ISSUE TITLE
[BUG] Stable version RETARD repeat loop

### ISSUE THREAD

**Issue by Captherky** [flybywiresim/a32nx#3061]
Upon landing RETARD is looped. Wont turn off

**Mod Version**

import os
import sys
import json

root_dir = "."
root_ctrl_excl = ["build.py", "layout.json", "manifest.json"]
project_directories = [root_dir, "effects", "html_ui", "SimObjects", "ModelBehaviorDefs"]

manifest_entries = None
content_entries = list()
total_package_size = 0

for project_directory in project_directories:
    if (project_directory is root_dir):
        for file_name in os.listdir(project_directory):
            if not os.path.isdir(file_name) and file_name not in root_ctrl_excl:
                file_size = os.path.getsize(file_name)
                file_date = 116444736000000000 + int(os.path.getmtime(file_name) * 10000000.0)

                content_entry = {"path": file_name, "size": file_size, "date": file_date}
                content_entries.append(content_entry)

                print("Added file: " + file_name)
    else:
        for directory_path, directory_names, file_names in os.walk(project_directory):
            for file_name in file_names:
                file_path = os.path.join(directory_path, file_name)
                file_size = os.path.getsize(file_path)
                file_date = 116444736000000000 + int(os.path.getmtime(file_path) * 10000000.0)

                content_entry = {"path": file_path.replace(os.sep, "/"), "size": file_size, "date": file_date}
                content_entries.append(content_entry)

                total_package_size += file_size

                print("Added file: " + file_path)

layout_entries = {"content": content_entries}

if content_entries:
    with open("layout.json", "w") as layout_file:
        json.dump(layout_entries, layout_file, indent=2)
else:
    print("Error: layout.json not updated", file=sys.stderr)

with open("../manifest-base.json", "r") as manifest_file:
    manifest_entries = json.load(manifest_file)
    manifest_entries["total_package_size"] = str(total_package_size).zfill(20)

if manifest_entries:
    with open("manifest.json", "w") as manifest_file:
        json.dump(manifest_entries, manifest_file, indent=2)
else:
    print("Error: manifest.json not updated", file=sys.stderr)

**Describe the bug**

RETARD is looped. 

**To Reproduce**

1. Land
2. Retard is looped
3. Cant cancel it

**Expected behavior**

Retard should stop after thrust is zero

**Actual behavior**

Retard Retard...LOOPED!

**References**

**Additional context**

Was this working before/when did the issue start occurring?
After latest stable version

Is this a problem in the vanilla unmodded game?
no

Discord username (if different from GitHub):

**Comment by ZigTag** [comment]
We haven't used build.py for months, I'd reccomend updating your version and seeing if the issue persists

**Comment by Benjozork** [comment]
Hello, you put the wrong contents for the version.

Please put the contents of `build-info.json`. The file will be in the A32NX folder of your community directory.

**Comment by pepperoni505** [comment]
What version of the sim are you using?

**Comment by Captherky** [comment]
Release version from the auto download

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by MisterChocker** [comment]
Can you please post the content of the build_info.json ?

**Comment by MisterChocker** [comment]
Closing since no response from op.
