### ISSUE TITLE
[BUG] HDG MODE ERROR

### ISSUE THREAD

**Issue by daniel5800** [flybywiresim/a32nx#3062]
**Mod Version**
Latest Dev Version

**Describe the bug**

When selecting a heading it goes to it but on the display it shows the heading you were currently at and you need to manually select the heading again 

**To Reproduce**

1. Select a HDG
2. Issue will be produced
3. Have to reselect the HDG

**Expected behavior**

Supposed to select the HDG and the number should keep

**Actual behavior**

Selected HDG and the number flips back to what you were at

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Yes, latest dev version update

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):

**Comment by aguther** [comment]
Should be fixed on dev
