### ISSUE TITLE
[BUG] Midflight banking issue (often called deadzone issue)

### ISSUE THREAD

**Issue by MikeDoubleU** [flybywiresim/a32nx#3063]
**Mod Version**
{
  "built": "2021-01-15T13:41:21+00:00",
  "ref": "",
  "sha": "",
  "actor": "ThatRedMelon <34657891+ThatRedMelon@users.noreply.github.com>",
  "event_name": "manual"
}

**Describe the bug**
Sometimes during flight with AP, the banking issue, or so called deadzone issue occurs: The plane banks left or right at a 50-60° angle, doing circles in the air.
I found a method to reproduce and prevent the issue.

**To Reproduce**
1. Load into the game. Doesn't matter if its C&D, on the runway, or even in the air. I recommend in the air, because its faster if you want to reproduce the issue.
2. Stabilize the flight.
3. Toggle AP off, wait a couple of seconds and turn AP on again.
4. Hit NUM 4 or NUM 6 a couple of times and watch the plane roll, while AP stays on.
5. Hit NUM 5 to reset the Ailerons and repeat step 4 with the other NUM key. If you did this with both ways already, continue with step 6.
6. Toggle SEC1 off and after a couple of seconds on again. The plane stabilizes again.
7. After toggling SEC1, hitting NUM 4 or NUM 6 doesn't affect the plane anymore. You can reset this state by toggling the AP and restart the cycle at step 4.

Something important to observe: 
You can reproduce step 4 also by tilting the joystick, but as soon as it returns to neutral position, the plane stabilizes. So technically it can be a deadzone issue, but then it would occur as soon as you takeoff, not mid flight. 
Also, Elevator input is ignored, up to the point it deactivates AP. And if SEC1 is toggled off and on after AP is engaged, Aileron input is also ignored up to the point it deactivates AP. 

**How to prevent the issue**
Toggle SEC1 off and on again, every time you engage AP.

**Expected behavior**
AP should ignore all Aileron inputs, up to the point it deactivates AP, or correct them to stay on course. It does it for Elevators, but not the Ailerons? But I am not a pilot, so I don't really know.

**Actual behavior**
Aileron input flies AP off course.

**References**
Search for screenshots on Discord from MikeDoubleU#9826. But I believe everyone is familiar with the issue.

**Additional context**
SEC1 

Was this working before/when did the issue start occurring?
Since the MSFS Update with the banking issue.

Is this a problem in the vanilla unmodded game?
Yes, only A32NX in the Community folder.

Discord username (if different from GitHub): MikeDoubleU#9826

**Comment by Benjozork** [comment]
This is a known and understood issue of the MSFS autopilot, and not something we can fix.
