### ISSUE TITLE
[BUG] AP not following flight plan

### ISSUE THREAD

**Issue by LFSS** [flybywiresim/a32nx#3066]
**Mod Version**
Stable 0.5.2 or Dev 566d8db

**Describe the bug**
The autopilot does not follow lateral navigation but follows vertical navigation just fine.  

**To Reproduce**

1. Select A32NX
2. Load a flight plan
3. Takeoff and engage the AP

**Expected behavior**

The AP should follow both lateral and vertical navigations.

**Actual behavior**

As you can see in the video, after I press the "AP 1" button, the AP starts banking right (sometimes hard right) therefore not following the flight plan. In another occasion, even choosing the heading manually didn't work. the airplane just kept banking slightly right. 

**References**

A video reproducing the bug can be found here:
https://youtu.be/nSw6jKPY0UA

Was this working before/when did the issue start occurring?
The AP never showed this bug before v0.5.2. I made a successful flight (AP working normally) with v0.5.0

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub): Apex#5413

**Comment by Benjozork** [comment]
You have your deadzones set too low. Go to MSFS control settings and set them to 30% to isolate the issue. If it does fix AP, then reduce it until it doesn't and keep the lowest working value.

**Comment by Bigflappyboi** [comment]
Maybe you have set it in heading mode

**Comment by LFSS** [comment]
> You have your deadzones set too low. Go to MSFS control settings and set them to 30% to isolate the issue. If it does fix AP, then reduce it until it doesn't and keep the lowest working value.

Did that. No effect, the plane still banks right.

**Comment by LFSS** [comment]
> Maybe you have set it in heading mode

I even tried using HDG mode, but the plane didn't comply with the command

**Comment by LFSS** [comment]
OP here: the Deadzones fix worked for me. I've no idea why it didn't work on the first try but I recommend restarting your PC to see if it helps! 

Thanks everyone!

**Comment by dFayet** [comment]
I faced the exact same issue, applying the deadzone fix solved it. Maybe it could be nice to have a "common issues" doc?

**Comment by Benjozork** [comment]
It's mentionned in both the release notes and our discord in the #known-issues channel

**Comment by Benjozork** [comment]
Closing as resolved
