### ISSUE TITLE
[BUG] Missing PACK sounds when PACKS get Bleed Air from Engines

### ISSUE THREAD

**Issue by rahulrathnakumar** [flybywiresim/a32nx#3067]
**Mod Version**

**Describe the bug**

PACK bleed air sounds go mute after engine start and APU bleed is switched off.

**To Reproduce**

1. Start both engines.
2. Switch off APU BLEED and return ENG MODE selector switch to NORM.

**Expected behavior**

Expected behavior is the PACKS sound stays on after APU is off.

**Actual behavior**

Current behavior is the PACKS sound goes mute after APU BLEED off.

**References**

N/A

**Additional context**

N/A
Was this working before/when did the issue start occurring?
No. The APU BLEED air sounds were implemented in the current dev version
Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):
SamFisher

**Comment by Benjozork** [comment]
cc. @hotshotp

**Comment by hotshotp** [comment]
Yes - this will be fixed next update as we needed more complex logic. I now have a parameter to attach the sound to and it will be good next update :)

**Comment by MisterChocker** [comment]
> Expected behavior is the PACKS sound stays on after APU is off.

There are a couple more parameters that have influence on that, but you are correct.

**Comment by hotshotp** [comment]
Fixed in a PR three days ago
