### ISSUE TITLE
[BUG] ADF blinking on and off in ND

### ISSUE THREAD

**Issue by frankkopp** [flybywiresim/a32nx#3070]
**Mod Version**
{
  "built": "2021-01-16T00:39:46+00:00",
  "ref": "",
  "sha": "",
  "actor": "Andreas Guther <andreas@guther.family>",
  "event_name": "manual"
}

**Describe the bug**
The ADF arrow is blinking. Also ND NDB name and frequency "blink" / exchange in the same rhythm

**To Reproduce**
1. Configure ADF in range and display it on the ND

**Expected behavior**
Not blinking :)

**Actual behavior**
https://user-images.githubusercontent.com/16833201/104814475-7542d500-580f-11eb-8a1a-32d35c257a8f.mp4

Was this working before/when did the issue start occurring?
issue is there since quiet a while

Is this a problem in the vanilla unmodded game?
unknown

Discord username (if different from GitHub): Cdr_Maverick

**Comment by MisterChocker** [comment]
> **Mod Version**
> ![image](https://user-images.githubusercontent.com/16833201/104814065-36ac1b00-580d-11eb-9594-e6041a9d9012.png)

Thats not the mod version, please submit the content of the build_info.json.

**Comment by Polacanthus** [comment]
I have exactly the same issue. Noticed it on the previous stable releases too. 

{
  "built": "2021-01-16T00:33:18+00:00",
  "ref": "",
  "sha": "",
  "actor": "DerL30N <leon.beeser@yahoo.de>",
  "event_name": "manual"
}

**Comment by frankkopp** [comment]
Updated version

**Comment by Polacanthus** [comment]
I want to add it doesn't only flash on and off on the ND but also in the RAD NAV page of the MCDU. The letter code will pop in and out in the same interval as on the ND.

**Comment by Khitiara** [comment]
have the same issue on latest develop version
`{
  "built": "2021-01-17T14:41:35+00:00",
  "ref": "",
  "sha": "",
  "actor": "Jorim Jaggi <jorim.jaggi@gmail.com>",
  "event_name": "manual"
}
`

**Comment by MisterChocker** [comment]
This can also happen to the LS frequencies/signals.
This may be the result of a loss and regain of the signals.

**Comment by Polacanthus** [comment]
>  This may be the result of a loss and regain of the signals.

I doubt it. It also happens when I sit next to an NDB I am perectly in range off. Also I have not observed that to happen on any other aircraft of the game.

**Comment by blitzcaster** [comment]
This is from the sim, somehow the signal for ADF is intermittent. I've tried some workarounds but still find it unstable.

**Comment by Iunoi** [comment]
https://user-images.githubusercontent.com/19224974/106336975-51ac6f80-6290-11eb-894e-e8201a9eb930.mp4

I have the exact same problem, and i don't know how to fix it.  Dev-version: 2021-01-28T17:54:52+00:00

**Comment by AdamNZ** [comment]
Not sure what "cFPM" is, but this little problem keeps coming and going for me. It's just happened on today's DEV update (7 Aug). It's as if some old code is being re-merged with a new build.

**Comment by tracernz** [comment]
> 
> 
> Not sure what "cFPM" is, but this little problem keeps coming and going for me. It's just happened on today's DEV update (7 Aug). It's as if some old code is being re-merged with a new build.

The new custom flightplan and guidance branch. It has a whole new ND written from scratch, which doesn't have this issue.

**Comment by frankkopp** [comment]
I don't think this issue still exists. Closing it for now.

**Comment by AdamNZ** [comment]
Frank ... I hate to say this ... but it's back! :-(((

I don't know how all these (amazing) mods get merged, but I get the impression that every now and then someone merges a new/different function and is somehow merging old ADF code - instead of the most recent section [of code] that fixes the ADF flashing. Not making much sense, biut I hope you unsderstand what I mena, LOL!

**Comment by MisterChocker** [comment]
@AdamNZ no, that's most likely not happening.
 @frankkopp may be using the rewritten ND from our experimental branch as a reference for this statement.

Never the less, I'll re-open this issue with the addition that it's fixed in our custom `flight management system` aka experimental branch.

**Comment by tracernz** [comment]
Fixed in a local branch but part of a larger piece of work that will come in later (after custom nav db and flight planner).
