### ISSUE TITLE
[BUG] ILS CAT III autoland pitching down at flare

### ISSUE THREAD

**Issue by peterg928** [flybywiresim/a32nx#3071]
**Mod Version**

{
  "built": "2021-01-15T04:52:14+00:00",
  "ref": "",
  "sha": "",
  "actor": "DerL30N <leon.beeser@yahoo.de>",
  "event_name": "manual"
}

**Describe the bug**

ILS CATIII autoland, appr selected, land green, at flare always pitches down rather than up

**To Reproduce**

1. Enter full flight plan and selected ILS CAT III approach eg 28R at KORD
2. approach armed and green, land green
3. fly the approach until flare - aircraft pitches down rather than up for flare causing crash or heavy nosewheel landing

**Expected behavior**

as above but during flare aircraft should pitch up and complete autoland

**Actual behavior**

as above

**References**

**Additional context**

Was this working before/when did the issue start occurring?
this has worked until recently

Is this a problem in the vanilla unmodded game?
untested

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment]
Closing since Autoland is not supported yet
