### ISSUE TITLE
[BUG] When enignes are lost.

### ISSUE THREAD

**Issue by bigifooti** [flybywiresim/a32nx#3074]
**Mod Version**
Stable 0.5.2  built: 2021-01-09T06:59:30+00:00

**Describe the bug**
Somehow I lost both engines on a 1 hour flight beween Manchester and Schiphol.  I loaded the standard fuel/weight load(didn't touch it) which should be sufficient, but apparantly not. 

On engine shutdown, all instruments (pfd, nd, mfd, fmc) went black, including the standby instrument.  AP was still active and still functioning incl display. All lights were still working and BAT was on. 

Once I identified that I had zero fuel, I added via some extra fuel via the fuel menu. 
I tried to restart the engine right away without insturments. Didn't work. Ctrl-E short cut didn't solve it either. 
I fired up the APU and once working all instrument came back. 
After the APU was online I again tried to start the engines. APU bleed was on. Both at 240kts and at 280 kts, without any succes. 

During this ordeal I think the Probe heater was also lost, at least the Auto function didn't work. I noticed this beacuse the wind noise suddenly stopped. So I guess the wind noise is based on IAS and also affected by pitot working. As a just went through a cloud layer the pitot frose up and speed indication was lost. Setting the probe heather to ON fixed this. 

In a Gimly glider fashion I made it to the beach of the Netherland and landed without any engines and only the APU running. 

**To Reproduce**
See above, I think it was an incident. 
1. Fly on fumes
2. Loose both engines
3.

**Expected behavior**
See above
On engine failure the screens should still be on. or if this is part of a failure than the very least the standby instrument should still be on.
I would think restarting the engines midair by adding fuel would have worked. If that is part of realism than it is ok I guess.  

**Actual behavior**
See above
Screens went black on engine shut down. 
Wind noise depends on pitot working 

**Additional context**
Is this a problem in the vanilla unmodded game?
Only an Easyjet livery added. No issues on previous flights and livery does not have a panel.cfg. 

Discord username bigifooti #4912

**Comment by ChruutvoLuzi** [comment]
Can confirm, had the same issue on a few tests on the ground yesterday. Only way to solve is to reload

**Comment by asa151** [comment]
I’ve also had this issue. Low on fuel. I know tanks can ‘run out ‘ before zero but I didn’t get any low fuel warnings

**Comment by mwuertinger** [comment]
In the real aircraft only the first officer's screens and the MFD are off during a dual engine failure. The captain's screens and the ECAM screen are briefly off, then come back on battery power. You can see it in this video: https://www.youtube.com/watch?v=djd7f_azfiI

**Comment by jeremie1002** [comment]
Hi,
Stable version 0.6.1

Lost both engines at cruize altitude (FL290) with ~1500 Kg of fuel onboard. More precisely, lost left engine then right one after ~30".
Before the issue, no warning message.  
Maybe this information is important : what I remember is that all fuel was inside outer tanks and there was no transfer from outer tanks to inner tanks (no message OUTR TK Fuel XFRD). 

After lose of both engines
Elec :
- no screens on
- AP seemed to work
Hyd :
- speed brakes OK
- flaps OK
- gears NOK (no manual gears extension)

**Comment by davidwalschots** [comment]
This issue mentions various things. Wordy issues like this tend to not be cleaned up long after things were fixed due to mentioning various things. The primary issue regarding ELEC is solved. If there are other issues you feel strongly about, please create separate items, so they can be individually tracked.
