### ISSUE TITLE
[BUG] Mod broken after FPS fix merged.

### ISSUE THREAD

**Issue by Berniep94** [flybywiresim/a32nx#3077]
Master-CFBW

**Describe the bug**
Overhead, Aurtopilot, Comunications, MCDU seems to be broken.

**To Reproduce**
1.Load aircraft on gate/ also runway
2. IRS broken, knobs, apu, MCDU etc.
3.

**Expected behavior**
Fixed this issue

**References**
![image](https://user-images.githubusercontent.com/71423997/104830293-c1efd580-583a-11eb-922c-b41b12aed838.png)
![image](https://user-images.githubusercontent.com/71423997/104830297-cae0a700-583a-11eb-8f8f-e51053ea99ea.png)
![image](https://user-images.githubusercontent.com/71423997/104830306-ddf37700-583a-11eb-8a3d-19d0a4ae5c7d.png)
![image](https://user-images.githubusercontent.com/71423997/104830308-e186fe00-583a-11eb-9332-23c490773f4e.png)

Was this working before/when did the issue start occurring? yes

Is this a problem in the vanilla unmodded game? no

Discord username (if different from GitHub):

**Comment by Saschl** [comment]
Hi, are you sure you are on the experimental cfbw branch? If yes, your issues are not related to the FPS fix merge as it’s not Part of the fbw branch yet.

**Comment by MisterChocker** [comment]
> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning

Additional, do you have any other mods installed?

**Comment by Berniep94** [comment]
> > BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning
> 
> 
> 
> Additional, do you have any other mods installed?

Yes i do, i have WT CJ4 and all of the Garmin stuff from them... but thats it.... i know that might sound akward but its the first time that the aircraft broke like this, thank you

**Comment by MisterChocker** [comment]
Yeah the Garmin has conflicts.

**Comment by Berniep94** [comment]
I redownloaded all the WT stuff and A320 CFBW and it is all done... Sorry for the inconvenience!
