### ISSUE TITLE
[BUG] Freezes upon selecting arrival STAR information (YSSY)

### ISSUE THREAD

**Issue by BROADACRES16xFS17MAP** [flybywiresim/a32nx#3078]
Mod Version
Stable 0.5.2 

Describe the bug
Freezes upon selecting arrival STAR information (YSSY)

To Reproduce

    Select A32NX
    Load a flight plan from YPAD to YSSY
    Select a SID (RWY 23 PANKI3 departure)
    then select a STAR (16R RIVET 3) arrival
    It should then display the sim freezing for 30-40seconds before coming good again.
    (All done on the ground at YPAD)

Expected behavior

Should insert STAR without a pause.

Actual behavior

As above

**Comment by kiokio0987** [comment]
Is NAVDATA an MSFS original? Or is it Navigraph (2014 Revision 3)?
We have had problems with this before.(#2911)
I have checked to see if I can reproduce this issue.

[Conclusion]
 If you have Navigraph (2014 Revision 3) installed, you can reproduce the problem.

[A32NX Version]
 Stable:
  v0.5.2

 dev:
  {
  "built": "2021-01-17T03:05:32+00:00",
  "ref": "",
  "sha": "",
  "actor": "Jorim Jaggi <jorim.jaggi@gmail.com>",
  "event_name": "manual"
  }

[Verification]
 Fly from YPAD to YSSY using Navigraph and MSFS original navigation data.

[Flight plan]
 YPAD/23 PANKI3 PANKI H247 CULIN Y59 RIVET RIVET3 YSSY/16R (ILS 16R Z)

[Results]
 Stable & dev Same result.

  Typing the flight plan by hand.
    MSFS original: NOT Freezes.
    Navigraph : Freezes 30sec . (When RIVET 3 is selected)

  simbrief import.
    MSFS original: NOT Freezes.
    Navigraph : Freezes 30sec .(When RIVET 3 is selected)

**Comment by tellurics** [comment]
Can this be related to #3058?

**Comment by BROADACRES16xFS17MAP** [comment]
> Is NAVDATA an MSFS original? Or is it Navigraph (2014 Revision 3)?
> We have had problems with this before.(#2911)
> I have checked to see if I can reproduce this issue.
> 
> [Conclusion]
> If I have Navigraph (2014 Revision 3) installed, I can reproduce the problem.
> 
> [A32NX Version]
> Stable:
> v0.5.2
> 
> dev:
> {
> "built": "2021-01-17T03:05:32+00:00",
> "ref": "",
> "sha": "",
> "actor": "Jorim Jaggi [jorim.jaggi@gmail.com](mailto:jorim.jaggi@gmail.com)",
> "event_name": "manual"
> }
> 
> [Verification]
> Fly from YPAD to YSSY using Navigraph and MSFS original navigation data.
> 
> [Flight plan]
> YPAD/23 PANKI3 PANKI H247 CULIN Y59 RIVET RIVET3 YSSY/16R (ILS 16R Z)
> 
> [Results]
> Stable & dev Same result.
> 
> Typing the flight plan by hand.
> MSFS original: NOT Freezes.
> Navigraph : Freezes 30sec . (When RIVET 3 arrival is selected)
> 
> simbrief import.
> MSFS original: NOT Freezes.
> Navigraph : Freezes 30sec .(When RIVET 3 arrival is selected)

Navigraph.

**Comment by kiokio0987** [comment]
@BROADACRES16xFS17MAP Thank you for your report.
It seems that it is Navigraph that is causing the problem, not the effects of the A32NX mod.
 (This is related to #3058 and #2911)
Temporary solution is to remove the Navigraph.
I think it would be better to report the problem on the Navigraph forum.
https://forum.navigraph.com/c/msfs-beta/missing-sids-stars-apprs/29

**Comment by MisterChocker** [comment]
Closing in favor of #3078

**Comment by BROADACRES16xFS17MAP** [comment]
Yep they blame ASOBO lol
