### ISSUE TITLE
[BUG] Autopilot engages ALT* mistakenly when in CLB or DES

### ISSUE THREAD

**Issue by supdim** [flybywiresim/a32nx#3081]
**Mod Version**
only tested in Custom FBW  

**Describe the bug**
Situation: Autopilot engaged and in CLB or DES mode (not in OP CLB or OP DES mode!); You have inserted a target altitude in the FCU. If your inserting a new higher target altitude (when in CLB mode) or a lower target altitude (when in DES mode) before reaching the older target altitude, the autopilot will engage ALT* at the older target altitude und levels off. 

**To Reproduce**
for CLB:
1. After takeoff set a target altitude in the FCU (for example 10000ft), enable the autopilot in managed mode, means CLB.
2. When passing an altitude below the target altitude (for example 5000ft) raise the target altitude in the FCU (for example to 15000).
3. The plane will Level off at 10000ft and switches CLB mode to ALT*.

for DES in analogy

**Expected behavior**
Regarding to the example, the aircraft must ignore the former inserted target altitude and must climb to 15000ft

**Actual behavior**
see section "To Reproduce"

**References**
none

**Additional context**
none

**Comment by MisterChocker** [comment]
Known Issue.

**Comment by tracernz** [comment]
> 
> 
> This is a known issue, somehow there hasn't been an issue filed.

https://github.com/flybywiresim/a32nx/issues/2043
