### ISSUE TITLE
[BUG] SimBrief Loads FMS Flight Number With ICAO-Code - Changes ATC Address

### ISSUE THREAD

**Issue by MariusSchuller** [flybywiresim/a32nx#3083]
**Mod Version**
- stable build v0.5.2
- yet I think this issue has not changed since the implementation of simbrief

**Describe the bug**
- after loading a flightplan from simbrief into the FMS, ATC changes the way they call you
- Example:
	- I load a flight with callsign "Lufthansa" and flight number "1940"
	- before loading the flightplan, ATC calls me (correctly) with "Lufthansa 1940"
	- sometime later I load my simbrief flightplan into the FMS
	- now ATC calls me with "Lufthansa DLH1940"
- reason for this behaviour: As the simbrief flightplan is loaded into the FMS, the flight number is overwritten with the callsign + the flight number from simbrief (see screenshot showing the FMS flight number being "DLH1940")

**To Reproduce**
1. Create a flightplan in simbrief with specific callsign and a specific flight number (e.g. callsign "DLH" and flight number "1940")
2. Input the corresponding callsign (e.g. Lufthansa") and the same flight number (e.g. "1940") in MSFS2020
3. Start anywhere cold & dark
4. Power up the aircraft and call ATC - observe they will call you with (in this example) "Lufthansa 1940", which is correct
5. Load your simbrief flight plan into the FMS
6. Observe that in the FMS the flight number will now be displayed as "DLH1940" - that is the ICAO-Code of Lufthansa ("DLH") and the flight number ("1940") put togehter
7. Call ATC - observe they will call you with (in this example) "Lufthansa DLH1940", which is not correct

**Expected behavior**
- flight number in FMS should only display the flight number without the airlines's ICAO-Code
- ATC calls pilots with "callsign + flight number"

**Actual behavior**
- flight number in FMS displays the flight number with the airlines's ICAO-Code
- ATC calls pilots with "callsign + ICAO-Code + flight number"

**References**

Screenshot from the SimBrief flighplan used.
![SimBrief_FlighPlan](https://user-images.githubusercontent.com/76614781/104838952-5b140000-58be-11eb-8f76-74df4b9d2cc0.PNG)

Screenshot of the ATC changing (see explanation below in the next picture!)
![ATC_Changing](https://user-images.githubusercontent.com/76614781/104838945-564f4c00-58be-11eb-861b-704278603ca7.png)

Explanation of why the ATC changes.
![ATC_ChangingExplanation](https://user-images.githubusercontent.com/76614781/104838981-a4644f80-58be-11eb-8770-f94e466793de.PNG)

FMS flightplan being filled with airline's ICAO-Code and the flight number after simbrief import
![FMS_AfterLoadingSimBrief](https://user-images.githubusercontent.com/76614781/104838949-58190f80-58be-11eb-8524-f37bf0b02a11.png)

Example of FMS as I guess it should be: Only the flight number is displayed. Source: http://a320dp.com/A320_DP/nav-flight-management/sys-14.2.1.html
![FMS_InitAExample](https://user-images.githubusercontent.com/76614781/104838951-5a7b6980-58be-11eb-8b48-8c9b0168f163.PNG)

**Additional context**
- Workaround: If you put in only the flight number in the FMS's field for the flight number, ATC works fine again
- I am not a real world pilot - hence I do not know if the FMS is supposed to only display the flight number or if adding the ICAO-Code is accepted. Yet changing this to only showing the flight number would solve the described issue!

Was this working before/when did the issue start occurring?
- started with the integration of simbrief

Is this a problem in the vanilla unmodded game?
- can't be tested as the simbrief integration is not featured in the unmodded game

**Comment by tracernz** [comment]
I attempted to do this properly a while ago, but I found setting the ‘ATC AIRLINE’ simvar doesn’t have any effect on the ATC (but obviously the ‘ATC FLIGHT NUMBER’ one does...). Now I just put the number only in SimBrief as a work-around as I didn’t think there was much point changing this without a full fix.

**Comment by gizmo71** [comment]
[This page](http://www.a320dp.com/A320_DP/nav-flight-management/sys-14.6.4.html) would suggest that either should work (with or without callsign prefix), but all the real-world Airbus pilots seem to use the full callsign, which obviously doesn't work with the in-game ATC.

**Comment by tracernz** [comment]
> 
> 
> I attempted to do this properly a while ago, but I found setting the ‘ATC AIRLINE’ simvar doesn’t have any effect on the ATC (but obviously the ‘ATC FLIGHT NUMBER’ one does...). Now I just put the number only in SimBrief as a work-around as I didn’t think there was much point changing this without a full fix.

Update on this. If you set `ATC AIRLINE` in pre-flight, the in-game ATC will start using it when you hand-off to the departure controller and not before. Probably a bug Asobo should address.

**Comment by Flaxx-Rat** [comment]
The bug seems to be still there (or it popped up again). However, there is at least one thing avoiding this that could be done by FBW: 

    Change the default entry in 
    `.\SimObjects\AirPlanes\_FlyByWire_A320_NEO-LIVERY/aircraft.cfg` to `atc_airline = "" ` (that means blank)

As I didn't observe this behavior with other airliners. It might be an MS/ASOBO bug, but it's avoided by others nonetheless. If you are filling in the Airline Code and the Flight Number in SimBrief, it automatically generates both data in one field for the aircraf'ts Callsign.

![image](https://github.com/flybywiresim/aircraft/assets/109431387/e53a6a9d-0bf9-47d2-a104-066e615d1db6)
