### ISSUE TITLE
[BUG] A320NX approach button on the flight stick, but the approach light does not turn on

### ISSUE THREAD

**Issue by yiman27** [flybywiresim/a32nx#3085]
**Mod Version**

**Describe the bug**

**To Reproduce**

1.Set  approach button on the flight stick, but the approach light does not turn on
2.
3.

**Expected behavior**

 I set the A320NX approach button on the flight stick, but the approach light does not turn on. A320neo is normal. Can this be modified?

**Actual behavior**

 I set the A320NX approach button on the flight stick, but the approach light does not turn on. A320neo is normal. Can this be modified?

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by MisterChocker** [comment]
Not following template
