### ISSUE TITLE
[BUG] Issues with Thrustmaster TCA throttle quadrant

### ISSUE THREAD

**Issue by Ryder01** [flybywiresim/a32nx#3086]
**Mod Version**
latest Master build

**Describe the bug**

I am having issues with the engine switches on the Thrustmaster TCA throttle quadrant. The switches, when in their "on" button make the switches in the airbus go bezerk. When I go TO/GA, The engines will shutdown, making the A32NX unable to fly. If I move the engine switches on the thrustmaster to "off", then the switches on the airbus go back to normal and make the plane usable again.

**To Reproduce**
Read above.

1) Setup plane on the runway
2) move thrustmaster engine switches to on
3) Set plane to to/ga
4) Engines shutdown moments before liftoff.

**Expected behavior**
I sort of expect that the switches in the plane to respond to whatever the switch setting I have in the thrustmaster.

**Actual behavior**

Engine Switches in the plane flick on and off about a hundred times per second until it decides to set the switches to off and shutdown the plane.

**References**
Will add references soon

**Additional context**

Was this working before/when did the issue start occurring?
Yes, problem has only happened recently

Is this a problem in the vanilla unmodded game?
Not sure, have not tried it yet.

**Comment by ChruutvoLuzi** [comment]
Make sure to only bind these functions to the master switches and unbind all others
![image](https://user-images.githubusercontent.com/70195216/104845821-b4d4f400-58d7-11eb-856f-235466bcac33.png)

**Comment by MisterChocker** [comment]
Please report back if proposed solution is working for you.

**Comment by Ryder01** [comment]
@MisterChocker Thanks for the quick response. That worked, I do believe. and I actually only had one fuel valve control set, the other engine switch wasn't assigned to anything. This also happened to the default A320. I will test it a bit more.

**Comment by andrejetcat** [comment]
have you checked, that yo uhave the latest firmeware update from thrustmaster? That solved some problems in my case.

**Comment by Saschl** [comment]
The default bindings are quite screwed, they do this strange things

**Comment by Ryder01** [comment]
> 
> 
> have you checked, that yo uhave the latest firmeware update from thrustmaster? That solved some problems in my case.

I did it once a long time ago, but now I can't remember how to do it. Can you tell me how?

**Comment by Benjozork** [comment]
Closing as issue resolved by OP
