### ISSUE TITLE
[BUG] excessive elevator efficiency 

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#3092]
**Mod Version**

Master FBW

**Describe the bug**

I was carry out a normal landing, with a C.G. between the forward and aft limit of %Chord at ~25%. 4.000kg fuel remain, only 23% payload. Autobrake 1 and Reverse idle, full flaps.
@ around 70-60 knots I recognise that the frontwheel do not completly touched down, so I give a ~60-80% pitch-up on the stick and the nose began to rise again! and that WITH brake on low, witch also produce a pitch down moment on the ground. 
That is quite unrealistic, that you can pitch the plane up again below around ~60-70knots. That is, to my mind, also the reason for the "excessive pitch rate" on takeoff-rotation. (another problem, that was stated here from me) 

**To Reproduce**

1.in my case, carry out a normal landing with flaps full, autobrake low, ~20% payload, 4t fuel remain. 
2.you will recognise, that the front-gear don´t really want to touch the ground
3.pull back the stick @ around 70-60 knots....you will experiance an unrealistic pitchup at that low speed.

**Expected behavior**

real plane never pitch up again @ that low speeds with CG in the limits

**Actual behavior**

too excessive elevator/stabiliser efficiency

**References**

**Additional context**

I´m a real world Airbus Pilot, and when we flare, touch down and let the stick in the neutral position, the nose really clearly touches down. We also have to pitch against it that we don´t touch too hard with the front gear. especially after the brakes apply.

by the way, yes, I have selected model to "modern" in the FS ;) 

Was this working before/when did the issue start occurring?
-no
Is this a problem in the vanilla unmodded game?
-i don´t know

Discord username (if different from GitHub):

**Comment by donstim** [comment]
This issue has been brought to our attention in different forms (high takeoff rotation rate, pitch up at low speed, etc.). We are aware of it, but there are several confounding factors (some of which, like ground effect, we have no control over yet), and efforts to address this must be balanced against the effects of changes to parameters we can control to other parts of the flight envelope. The short answer is that we will continue to seek a solution to this issue, while not adversely affecting other areas. Please be patient, as it may take a while as we continue work on the flight model and custom fly-by-wire system.

**Comment by andrejetcat** [comment]
good to hear, that you are working on it and that you are aware of it :) I Didn´t know that. Thank you for all your hard work - i belive, we can expect a beautiful bird in the future! Thank you, that the plane becomes flyable more and more!
