### ISSUE TITLE
[BUG] Resume/load saved fligth causes ADIRS and Autopilot to load incorrectly

### ISSUE THREAD

**Issue by calwalker1** [flybywiresim/a32nx#3093]
**Mod Version**
{
  "built": "2021-01-09T06:59:30+00:00",
  "ref": "refs/remotes/upstream/HEAD",
  "sha": "a97147821116d4b27eb5a103e609378bf319cbc2",
  "actor": "Benjamin Dupont <benjozorkfr@gmail.com>",
  "event_name": "manual"
}

**Describe the bug**
When loading a saved flight file, some parameters will not load correctly. This includes (from what I can see, there may be others):
- ADIRS dials in NAV position but ND display showing Heading not available
- Autopilot has lost manually input altitude setting (default back to 5,000 ft)
- Barometric pressure back into 'manual' mode when previously in STANDARD mode
- Air-temperature dials on the overhead panel back at zero (leading to some popsicle passengers!)

**To Reproduce**

1. Perform a flight in A320 and midway through the flight his ESC, Save and save the flight
2. Close MSFS
2. Open MSFS 
3. Open the world-map and select 'save/load'
4. Load the newly saved flight file
5. press 'fly now'
6. Observe that some settings have not been correctly recalled including those listed above.

**Expected behavior**

Aircraft should load in the same state it was saved in.

**Actual behavior**

Aircraft loads with some avionics not maintaining their state on saving.

**References**

**Additional context**

I have no idea if this 'bug' is caused by MSFS itself not saving parameters that technically didn't 'exist' until the A320nx project created them.

Was this working before/when did the issue start occurring?
Unsure

Is this a problem in the vanilla unmodded game?
Unsure

Discord username (if different from GitHub):

**Comment by Berstad** [comment]
I was able to reproduce this. Additionally, my ADIRS was no longer aligned and my engines were off. Basically, the AC loaded in almost in a "cold and dark" configuration, although Batt 1 and 2 were on.

Build information:
```
{
  "built": "2021-01-17T18:52:24+00:00",
  "ref": "",
  "sha": "",
  "actor": "David Walschots <davidwalschots@users.noreply.github.com>",
  "event_name": "manual"
}
```

**Comment by sidnov** [comment]
Though we have introduced new code which loads all the systems correctly when spawning on approaches/runways/through save files, being able to save all parameters that are used on the flight is just not possible yet through the default sim-save system. We might implement custom save-states at a later stage, through a different method if possible
