### ISSUE TITLE
[REQUEST] MCDU BRT/DIM button hold down fuction

### ISSUE THREAD

**Issue by GlitchedYT** [flybywiresim/a32nx#3094]
**Is your feature request related to a problem? Please describe.**

No issue, just something that FSLabs has that makes it much easier to brighten/dim the MCDU screens. Currently, you need to keep clicking the bright/dim button in order to increase or lower the brightness of the display in the A32NX.

**Describe the feature you'd like to see implemented**

What i would like to see is to be able to hold down either the brighten or the dimmer button and it progressively increases or decreases the brightness, something small but it can be extremely useful.

**References**

Top video is from FSlabs, bottom is from A32NX
https://streamable.com/m4h8c6
https://streamable.com/bz02kj

**Additional context**

N/A

Discord username (if different from GitHub):

**Comment by XSJoJo** [comment]
Why not use the mouse wheel?

**Comment by tracernz** [comment]
This was done some time back when Theodore re-did the XML.
