### ISSUE TITLE
[BUG] Lost Flight Plan/Approach On Descent (Went Blank)

### ISSUE THREAD

**Issue by DFWSupertrooper** [flybywiresim/a32nx#3097]
**Mod Version**
2021-01-17T10:15:50+00:00 (FBW Custom)

**Describe the bug**
For first time, on descent into KSEA from KSAN (PADRZ2 EHF REBRG SHIMR SUNBE LMT HAWKZ7), as I was transitioning from VASHN to GRIFY, the A/C did the known turn towards 16L, so I immediately locked in HDG mode while I DIR TO GRIFY.

A few seconds later, almost at GRIFY, en route to the final turn to RNAV 16L (@ HELZR), the remainder of the flight plan and all waypoints including the arrival disappeared and the MCDU displayed an error that there was no flight plan/"blank."  While retuning to HDG mode, I tuned the RAD to ILS16L and steered towards the intercept using vector from ATC/managing FL, picked up the ILS in time and guided in safely from thence.

Honestly, I don't know if this was a one-time thing so you might not be able to reproduce (made several great flights today earlier), but...

**To Reproduce**
1. Load in posted route from above KSAN-KSEA, choose IFR/high altitude and RNAV Z 16L.
2. Fly route as expected.
3. On descent, as approaching GRIFY, pay close attention...

**Expected behavior**
A/C should fly complete route with no loss to MCDU or interruption to planned flight path/turn at RWY (known issue in default).

**Actual behavior**
Completely lost ability to follow planned route except by hand/chart into cloudy and dark KSEA area.  Was able to recover using other systems.

**References**
N/A

**Additional context**
N/A

Was this working before/when did the issue start occurring?
Yes.  Many flights w/o loss of MCDU data once prior.

Is this a problem in the vanilla unmodded game?
No idea...I never use vanilla.

Discord username (if different from GitHub):

Searched but did not find this same issue in _Issues_.  Thx.

**Comment by sinistre1973** [comment]
Can confirm this. But only with the custom FBW version. Rolled back to the normal dev version.

**Comment by DFWSupertrooper** [comment]
This hasn't happened again exactly, but today when the pesky turn towards runway thing happened, I tried to DIR TO the next waypoint and CTD.  That used to work pretty reliably but I guess I'll have to stick with the HDG mode workaround until a fix for the runway turn is in place (and I believe that's a vanilla issue too??).
