### ISSUE TITLE
[BUG] Crank Mode External View engine audio Cutting In And Out

### ISSUE THREAD

**Issue by HyperFS** [flybywiresim/a32nx#3098]
**Mod Version**

  "built": "2021-01-17T18:02:09+00:00",
  "ref": "",
  "sha": "",
  "actor": "Andreas Guther <andreas@guther.family>",
  "event_name": "manual"
}

**Describe the bug**

when using crank mode engine sound audibly cuts in and out when in external view 

**To Reproduce**

1.turn on apu and bleed and fuel pumps
2.set master switches to on and mode selector to crank
3.wait for engines to be at full crank speed 
4.go into external view and audio cuts in and out once at engines  full crank speed

**Expected behavior**

normal engine audio / noise

**Actual behavior**

audio cuts in and out with no pattern every few seconds only in external view

**References**

if needed , please contact on discord HyperFS#1846 , i am a member of the FBW Discord server

**Additional context**

Was this working before/when did the issue start occurring?
since installed
Is this a problem in the vanilla unmodded game?
no

Discord username (if different from GitHub): HyperFS#1846 , i am in FBW Discord

**Comment by hotshotp** [comment]
I'll have to tweak the derived simvars, I think it's a problem with those, I will take a look but I won't guarantee I'll fix it in the next update as it's not a priority

**Comment by hotshotp** [comment]
Fixed this in my latest PR
