### ISSUE TITLE
ECAM ENG pages are wrong and from a old CEO

### ISSUE THREAD

**Issue by Airbusinsider** [flybywiresim/a32nx#31]
A320-251N:
![SD ENG 320-251N](https://user-images.githubusercontent.com/70146837/91047093-d6c49600-e619-11ea-9199-896614130839.jpg)
A320-271N:
![SD ENG 320-271N](https://user-images.githubusercontent.com/70146837/91047095-d75d2c80-e619-11ea-9dfc-d7da887f2c73.jpg)

**Comment by noga-aviator** [comment]
i claim that.
gonna see what i can do

**Comment by noga-aviator** [comment]
but what is clearly missing

**Comment by JackZ974** [comment]
Compared to the actual one, the ENG ECAM page is completely filling the screen, no longer with an empty message column on all the 320 i felw

**Comment by noga-aviator** [comment]
ok, that page will be completly redone

**Comment by JackZ974** [comment]
Sure. We have to ccordonate to avoid redundancy. I have reworked already the APU page layout to be closer to the original, can do the same on this one.

**Comment by JackZ974** [comment]
The startup sequence makes a lot of changes on this page. FYI i am a real Airbus Pilot, but never flew the NEO unfortunately, only 318 CEO and 320

**Comment by noga-aviator** [comment]
> 
> 
> Sure. We have to coordonate to avoid redundancy. I have reworked already the APU page layout to be closer to the original, can do the same on this one.

yes do the engine one, i'm doing the BLEED one anyway

**Comment by Airbusinsider** [comment]
Before you start, you should decide, which enginge version you are going to model. There are differences.

**Comment by Emile31** [comment]
Hello,
I've noticed the same things on the ECAM engine page.
Apart from the design itself, the air starter valve symbol is inverted (open/close), and the igniter (A B or AB) is incorrect.
If needed I can provide the correct behavior.

**Comment by lukecologne** [comment]
Sounds like you are on the 0.2.0 release, the inverted starter should be fixed. If you still have issues with the engine page on master, consider opening a new issue.

**Comment by Emile31** [comment]
I will test the last version and open a new issue if needed.
But this issue is still in TO DO, shall it be moved to finished ?

**Comment by hotshotp** [comment]
Implemented
