### ISSUE TITLE
[BUG] Built in ATS keeps giving ILS clearance to the same runway

### ISSUE THREAD

**Issue by Annolago** [flybywiresim/a32nx#3103]
**Mod Version**
<!-{
  "built": "2021-01-18T02:36:25+00:00",
  "ref": "",
  "sha": "",
  "actor": "DerL30N <leon.beeser@yahoo.de>",
  "event_name": "manual" -->

**Describe the bug**
<!- Bug first experience on 14/1-2021. Always update daily with latest dev version.
Built in ATC will clear ILS to different runway that the one planned. Changin it in flight to another runway will not change ATC clearance - will always give me runway 22L -->

**To Reproduce**
Create flightplan going to EKCH - any runway but 22L. When cleared for ILS via Built in ATC it will give you 22L.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game? No

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
I don't think that's ever worked either in the mod or default 320.

**Comment by tracernz** [comment]
That seems very realistic. You change the runway/approach in the MCDU to suit what ATC request, not the other way around. You can request a different runway and/or approach through the ATC window, but that part is buggy.

**Comment by Benjozork** [comment]
Going to close as this has no analogue IRL

**Comment by Annolago** [comment]
OK - but maybe I was unclear. Should had taken a photo but missed that.
The message I got from ATC was "Clear to land ILS runway 5, expect runway 22L" Now that is bonkers.
Have tried to replicate exact same message, but now I just get "clear to KAS, expect Runway 22L" - now runway change is to be expected but not on final approach 7-8 miles before touchdown. 
Sorry if I was unclear about this..
