### ISSUE TITLE
[REQUEST] Change Default Frequencies

### ISSUE THREAD

**Issue by Samueleonard** [flybywiresim/a32nx#3108]
**Is your feature request related to a problem? Please describe.**
When loading in the acft, in any state, the default frequencies are not 'helpful' particularly to those flying online

**Describe the feature you'd like to see implemented**
change the default frequencies to 122.800 and/or 121.500 to help those flying on vatsim, and prevent people forgetting to tune it

**References**
i'm not sure how the real aircraft works with keeping frequencies when powered off, but if it does have a 'memory' then that could potentially be done in the future

**Additional context**
frequencies are stored in the .FLT files in the aircraft folder, so it should be simple just to change them, but I lack the knowhow of how to do it, or I would.

**Comment by macmmm81** [comment]
Default frequency in A320 is 118.000 and that should not be changed. Also, not everyone is flying on Vatsim.

**Comment by Samueleonard** [comment]
UNICOM for both vatsim and IVAO is 122.8, and of course guard 121.5, which everyone is required to monitor on com2 in the real world. keeping default frequencies on 118.0 has no benefit that i can see, at least having it on unicom by default would help anyone flying on a network.

**Comment by tracernz** [comment]
What does a real A320 do from cold & dark? That's the main criteria.

**Comment by hanomax24** [comment]
If you are starting C&D you can change the freq. in the apron.flt (community/A32NX/SimObjects/airplanes/Asobo_A320_neo).

But remember: You have to change it after every update.

**Comment by Samueleonard** [comment]
Closing as it has been implemented in the RMP rewrite.
