### ISSUE TITLE
[BUG] INSERT TITLE HERE

### ISSUE THREAD

**Issue by Matthewlad00** [flybywiresim/a32nx#3109]
**Mod Version**
{
  "built": "2021-01-18T02:36:25+00:00",
  "ref": "",
  "sha": "",
  "actor": "DerL30N <leon.beeser@yahoo.de>",
  "event_name": "manual"
}
**Describe the bug**
When i load into landing challenges the screens arent working. 
**To Reproduce**
1. Load into any landing challenge or approach on an airport
2. Profit
**Expected behavior**
I expected this to work normally
**Actual behavior**
Screens weren't available, This prevented me from having a good mfs 2020 experience  
**References**
![Capture](https://user-images.githubusercontent.com/76802555/104952243-048ceb80-59bc-11eb-8a4e-7de781708855.PNG)
(Ignore the red line its from a YouTube video as I have not been on the sim recently but this is what I'm experiencing)
**Additional context**

Was this working before/when did the issue start occurring? Ive had this issue for a while now

Is this a problem in the vanilla unmodded game? No

Discord username (if different from GitHub): discord: matthewlad000

**Comment by MisterChocker** [comment]
Yes this is correct the mod does not work with landing challenges.

**Comment by Matthewlad00** [comment]
oh ok @MisterChocker
