### ISSUE TITLE
[BUG] Flight number in use issue/simbrief flight plan integration

### ISSUE THREAD

**Issue by gintarasstaucejr** [flybywiresim/a32nx#3113]
**Mod Version**

Its a DEV version f81a0b1
{
  "built": "2021-01-19T01:05:05+00:00",
  "ref": "",
  "sha": "",
  "actor": "Matthew Sainsbury <matthew@sainsbury.io>",
  "event_name": "manual"
}

**Describe the bug**

1. Using simbrief integration, i need to press init request twice every time. When pressing first time i get message NOT IN DATA BASE as the last one.
2. Trying to file the flight plan LH126 from EDDF to EDDS i couldnt do it, as it was always shown FLIGHT NUMBER IN USE and blank Init A page. I could do everything, and this exact flightnumber was causing the issue. 

**To Reproduce**

1.In simbrief file the flight using flight number LH126 EDDF-EDDS
2. File the flight plan using simbrief integration on A32NX
3.Press init request.

**Expected behavior**

It would file the flight plan as normal

**Actual behavior**

Either FLIGHT PLAN IN USE and everything blank except TROPO, either its NOT IN DATA BASE and same thing, blank init A
!

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Never tried this exact flight, but yes, i had simmilar issues before, just now cant reproduce the flight and the day, but it was about 4-5 days ago.
Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub): Ginpaca

**Comment by Khitiara** [comment]
i assume you have a mod to add EDDS to the game since its missing by default due to being parly a military base?

**Comment by gintarasstaucejr** [comment]
Yes, I have a mod from flightsim.to :) I guess I will try to reinstall it,
maybe my installation wasnt correct?

2021-01-19, an 19:35, Khitiara Alyahka <notifications@github.com> rašė:

**Comment by Khitiara** [comment]
Shouldn't be relevant, just mentioning because I tried to fly there a month ago without getting the mod and was having not in database errors

**Comment by sidnov** [comment]
This issue has been fixed with minor updates to the code that pulls data from the API. Feel free to open a new issue if it reoccurs on the latest dev version
