### ISSUE TITLE
[BUG] All Button for MCDU bugged

### ISSUE THREAD

**Issue by FlightSimmer7700** [flybywiresim/a32nx#3123]
**Mod Version**

{
  "built": "2021-01-20T17:46:30+00:00",
  "ref": "",
  "sha": "",
  "actor": "DerL30N <leon.beeser@yahoo.de>",
  "event_name": "manual"
}

**Describe the bug**

When pressing the All button to cycle through ECAM pages it jumps from page to page and doesn't go in the way its supposed to so Eng then Bleed and so on but instead looks to choose what page it goes to randomly

**To Reproduce**

1.Do a normal flight
2.Hit the All button

**Expected behavior**

Cycle through pages in the right order

**Actual behavior**

Goes to random ECAM Pages

**References**

https://user-images.githubusercontent.com/70103461/105255506-9f7ff400-5b7b-11eb-8460-9d9297549635.mp4

**Additional context**

Was this working before/when did the issue start occurring? Was working before noticed today but some people have it while others don't and just to clarify, I asked the guy who made the pr (#3114) that I was flying with and he said it doesn't have anything to do with it

Is this a problem in the vanilla unmodded game? no

Discord username (if different from GitHub): FlightSimmer7700#3468

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by theomessin** [comment]
> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning

Feel free to open a new issue **provided you follow the given instructions**.
