### ISSUE TITLE
[BUG] Awful stuttering when using the A320NX when using low refresh rate.

### ISSUE THREAD

**Issue by PaulARamsay** [flybywiresim/a32nx#3129]
**Mod Version**

```
{
  "built": "2021-01-21T09:04:56+00:00",
  "ref": "",
  "sha": "",
  "actor": "Matthew Sainsbury <matthew@sainsbury.io>",
  "event_name": "manual"
}
```

**Describe the bug**

Awful performance when using the a320NX, CoherentCGDraw is taking a massive hit and causing terrible stutters when flying.

**To Reproduce**

1. Set fresh to cockpit refresh rate to low
2. Start the aircraft.
2. Watch the debug monitor.

**Expected behavior**

Less stuttering. Better performance.

**Actual behavior**

Ran A320 NX as usual.

**References**

A320
![image](https://user-images.githubusercontent.com/19417889/105356554-77c87480-5beb-11eb-8dbf-47f0e629b2f6.png)
A320NX
![image](https://user-images.githubusercontent.com/19417889/105356666-99296080-5beb-11eb-88f3-9c5ad7757716.png)

**Additional context**

  | AlphaSync Gaming Desktop PC, AMD Ryzen 7 2700X, 32GB RAM, 1TB HDD, 240GB SSD, Gigabyte RTX 2070 Super, Windows 10 Home
-- | --

Was this working before/when did the issue start occurring?

It's been an on-going issue for all versions.

Is this a problem in the vanilla unmodded game?

No, see screenshot attached. This is the comparision between the 2. As you can see there is significant stuttering.

Discord username (if different from GitHub):

Archer#9442

**Comment by PaulARamsay** [comment]
So this was caused by using low refresh rate in the settings. Changing from low to medium/high causes the above stutters.

**Comment by Daboj1337** [comment]
> So just tested and the stutters were caused by using low refresh rate in the settings. Changing from low to medium/high causes the above stutters to stop. Still seems like low fresh might need some optimization if it's giving you worse performance.

For me only the intervall from stuttering went from every second to 2-3 second when i change the refresh rate from MSFS. Ive got the 10900k and 3090 ti. After i inserted a flightplan vom simbrief the whole sim is so heavy lagging...

**Comment by Benjozork** [comment]
Closing in favour of #4051.
