### ISSUE TITLE
[BUG] "Terrain on ND" cannot be turned off, if ND is off.

### ISSUE THREAD

**Issue by marcelago** [flybywiresim/a32nx#3132]
**Mod Version**

{
  "built": "2021-01-21T09:04:56+00:00",
  "ref": "",
  "sha": "",
  "actor": "Matthew Sainsbury <matthew@sainsbury.io>",
  "event_name": "manual"
}

**Describe the bug**
 "Terrain on ND"-button can be turned on (green "ON" light illuminates) while ND (Navigation-Display) is turned off, however Terrain on ND cannot be turned off again until the ND is turned back on. (Same behaviour for Captain and Copilot)

**To Reproduce**

1. Turn ND birghtness to zero
2. Turn on "Terrain display on ND" (to the right side of the Navigation-Display)
3. Try turning off "Terrain display on ND" (Does not work in my case)

**Expected behavior**
 This is where I am not exactly sure: There are two possibilities: 1. "TERR ON ND" should be able to be turned on, as well as turned off, regardless of the ND brightness (My guess)
2. Or, TERR ON ND should not be able to be turned on, when ND is off, in the first place.

**Actual behavior**
 TERR ON ND does not turn off when ND is turned off

**References**

**Additional context**
 I used the newest experimental version from the installer (21st of Jan 2021)

Was this working before/when did the issue start occurring?
Just noticed it, after installing the new version and making a long flight (can't tell if the bug was there before)

Is this a problem in the vanilla unmodded game?
Haven' tried it yet, but I figured that you could be able to fix it anyways :)

TURBO KILLER#6095
Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by theomessin** [comment]
> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning

Feel free to open a new issue **provided you follow the given instructions**.
