### ISSUE TITLE
[BUG] HDG/TRK dial not accelerated when in TRK mode

### ISSUE THREAD

**Issue by frankkopp** [flybywiresim/a32nx#3133]
**Mod Version**
{
  "built": "2021-01-20T19:08:34+00:00",
  "ref": "",
  "sha": "",
  "actor": "Andreas Guther <andreas@guther.family>",
  "event_name": "manual"
}

**Describe the bug**
When in TRK/FPA mode the TRK/HDG dial knob does not accelerate as it does in HDG/V/S mode.
It only steps single degrees which makes dialing larger amounts very time consuming and annoying.

**To Reproduce**
1. Start the aircraft and dial HDG quickly. Should start with steps of one and then accelerate to larger steps (10s)
2. Switch TRK/FPA mode do the same

**Expected behavior**
Accelerating dial steps

**Actual behavior**
In TRK mode only single degree steps

**References**
https://www.dropbox.com/t/ZUsw96YChvXxNVk5

Discord username (if different from GitHub): Cdr_Maverick

**Comment by frankkopp** [comment]
https://user-images.githubusercontent.com/16833201/105419290-c05d4d80-5c3e-11eb-9d11-0f7cef03160f.mp4

**Comment by frankkopp** [comment]
https://user-images.githubusercontent.com/16833201/105419454-04505280-5c3f-11eb-80fd-3b87483d5574.mp4

**Comment by aguther** [comment]
Should be fixed on dev
