### ISSUE TITLE
Scrollable switches change position in "FREELOOK" mode

### ISSUE THREAD

**Issue by ExampleWasTaken** [flybywiresim/a32nx#3139]
**Mod Version**
master
```json
{
  "built": "2021-01-21T09:04:56+00:00",
  "ref": "",
  "sha": "",
  "actor": "Matthew Sainsbury <matthew@sainsbury.io>",
  "event_name": "manual"
}
```

**Describe the bug**
Scrollable switches change position when in the center of the screen, while zooming in freelook mode.

EDIT: Apparently you need to be zoomed in on the button in question.

**To Reproduce**
I will use the default cockpit camera keybinds for this description.
1. Make sure a scrollable switch (i.e. a temperature knob) is in the center of the screen
2. Right click, as if you wanted to look around
3. Scroll to zoom in (or out)

**Expected behavior**
The switch should stay in the position it was in prior to enabling the "FREELOOK" mode.

**Actual behavior**
Switch changes position as if one would scroll them in "FIXED LOOK" mode.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
This issue exists since I am using the mod - about 3 - 4 weeks.

Is this a problem in the vanilla unmodded game?
I have never flown the vanilla A320 therefore I cannot confirm or deny that.

Discord username (if different from GitHub): ExampleWasTaken#0886

**Comment by Benjozork** [comment]
This is an issue with the sim
