### ISSUE TITLE
[BUG] ILS not working in Payware airports, works for default airports

### ISSUE THREAD

**Issue by lynscrafts** [flybywiresim/a32nx#3148]
**Mod Version**

  "built": "2021-01-16T22:07:51+00:00",
  "ref": "",
  "sha": "",
  "actor": "Benjamin Dupont <benjozorkfr@gmail.com>",
  "event_name": "manual"
}

**Describe the bug**

Does not capture ILS on Payware Aiports. ILS is properly captured on the default airports.
Tested against the following payware airports:
KORF Norfolk by VerticalSIM
EDDL Dusseldorf by JustSIM
EKCH Copenhagen by FLyTampa

Tested against the following default airports:
KBWI - Baltimore Washington International
EHAM - Schiphol 

**To Reproduce**

1.  Purchase and install a payware or download a freeware aftermarket airport
2.  Pick a runway and set it as the arrival runway
3.  Do not set a departure aiport or runway. MSFS will place the plane about 10 to 11 nm out on localizer and glideslope
4.  Put the sim on active pause and go to the mcdu
5.  In the flightplan select the arrival airport
6.  Select the runway that you set as the arrival runway when you started the flight
7.  Go to the ARC Mode and set it to ILS

**Expected behavior**

The ARC display should show the captured ILS in magenta in the top rignt and show the localizer as lined up.
In Active pause turn on the autopilot, flight director, ILS, and Approach
Set the auto throttles to the climb gate
The A320 should now fly the approach in autopilot or you can fly the approach manually. Either way the ILS should track

**Actual behavior**

As illustrated in the attached photos ILS is not tracked on payware airports. ILS tracks properly on default airports.

**References**

BWI Default.jpg shows a properly captured ILS on a default airport
Schiphol Default.jpg shows a properly captured ILS on a default airport

Dusseldorf Payware.jpg shows the error on a payware airport
Katsrup Payway.jpg show the error on a payware airport
Norfolk Payware.jpg shows the error on a payware airport

**Additional context**

Was this working before/when did the issue start occurring?
Prior to this report I also had the payware KATL installed and had the same error. Deleting the payware aiport removed the error and the plane now captures ILS at KATL

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):

**Comment by A320PHX** [comment]
Are you making sure that the plane has the correct ILS freq. dialed in? Some payware airports do not automatically populate the freq. like the default airports do. I just completed a flight to fsdreamteam Zurich and it captured ILS fine with the custom FBW. Also with the most recent dev version I did another flight and into KLAS and it also captured ils perfectly.

**Comment by lynscrafts** [comment]
You are correct. The ILS freq is not being populated. Adding the Freq manually seems to allow the ILS to work properly on payware airports. Is the issue with mod or the airport. Seems odd that it ILS freq loads for other, default aircraft, but not for this mod.

**Comment by A320PHX** [comment]
It is a problem with the airport sceneries themselves. I don't think the SDK lets them mess with ILS stuff yet.

**Comment by lynscrafts** [comment]
Since there is a work around I will close this issue - thanks for the response.
