### ISSUE TITLE
MSFS 2020 crashes when your waiting for the sim to load your flight.  

### ISSUE THREAD

**Issue by cvanheuklon** [flybywiresim/a32nx#3149]
Any suggestions on how to prevent this mod from crashing MSFS 2020?  I've trouble shot removing all other MODS and only using the a32nx MOD and it only happens with this MOD.  I've used all current versions of the MOD and it does the same thing?
 
**Mod Version**

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by MisterChocker** [comment]
Please follow the template.
