### ISSUE TITLE
[BUG] Entered Flight plan not match waypoints on screen

### ISSUE THREAD

**Issue by heroicrealm** [flybywiresim/a32nx#3152]
**Mod Version**
{
  "built": "2021-01-09T06:59:30+00:00",
  "ref": "refs/remotes/upstream/HEAD",
  "sha": "a97147821116d4b27eb5a103e609378bf319cbc2",
  "actor": "Benjamin Dupont <benjozorkfr@gmail.com>",
  "event_name": "manual"
} 

**Describe the bug**
Flight plan not match actual path. Some waypoints skipped to make path shorter then entered in F-PLN
https://i.imgur.com/uQSOqvZ.png
**To Reproduce**

1. Spawn on ULLI 28R
2.Enter F-PLN:
  ULLI28R->UTET1A->UTETA->AKARU->ARAR1W->ULLI10L

**Expected behavior**
Flight path to UTETA via SID UTET1A procedure then AKARU then via STAR AKAR1W back to ULLI

**Actual behavior**
Plane builds route to waypoint LI733 then returns back to airport, not visiting UTETA/AKARU
https://i.imgur.com/4uuEVm5.png

**References**
 If applicable, add screenshots or videos to help explain your problem. -->
https://i.imgur.com/4uuEVm5.png
https://i.imgur.com/4uuEVm5.png

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):
Malloriak#9289

**Comment by sidnov** [comment]
Solved in latest dev version with custom FMS
