### ISSUE TITLE
[BUG] Very low FPS after inserting via Simbrief upload a flight plan for second leg/flight

### ISSUE THREAD

**Issue by Daboj1337** [flybywiresim/a32nx#3158]
**Mod Version**
Latest Development

**Describe the bug**
I flew first EDDT-EDDL with Simbrief flight plan. 40-60fps
Than after the first leg, i flew EDDL-EPGD again with Simbrief flight plan upload. 
After uploading the flight plan for the second leg, fps went down to 20fps with 40ms on the Main Thread.

**To Reproduce**
Fly 2 legs, with simbrief  flight plan upload.

**Expected behavior**
Same FPS and MainThread latency like on the first leg

**References**
<img width="1918" alt="Unbenannt" src="https://user-images.githubusercontent.com/76589309/105612142-62ee0b80-5dba-11eb-9f88-0188bc7e0865.PNG">

**My Hardware**
CPU: Intel Core i9-10900K
Ram: G.Skill DIMM 32 GB DDR4-3600 CL16
GPU: ASUS GeForce 3090 RTX O24G Board: ASUS ROG STRIX Z490-F GAMING
Cooling: EKWB Classic Kit S360
PSU: Corsair RMi Serie RM850i
SSD: Samsung 840 EVO 250GB
M2: Samsung 970 EVOPlus 1TB

**Comment by Saschl** [comment]
I think it might be helpful if you could put you flightplans here as well

**Comment by Saschl** [comment]
Maybe it might be helpful if you could put your complete flightplan here as well

**Comment by Daboj1337** [comment]
> Maybe it might be helpful if you could put your complete flightplan here as well

English:  Unfortunately too late now. The only thing I had discovered in the fmc was that I had an extremely large number of sides  on the leg page with the same route, but the route was only active from one side
Maybe to many waypoints in the fmc caused the mainthread latency. 

German: Nachdem ich die route uploaded hatte für den 2 zweiten Leg von Düsseldorf nach Danzig, hatte ich extrem viele Seiten in  der Leg Page mit immer wieder der gleichen Route. Ich vermute das ich so viele Waypoints im FMC hatte (wieso auch immer) das der Mainthread so langsam wurde. Es ist ja im allgemeinen ja bekannt das viele waypoints zu micro laggs führen. Mehr konnte ich nicht ausmachen.

**Comment by mreza1st** [comment]
I did a for leg flight yesterday and did not see any change in the fps or the amount of stutters. I still do get stutters though and on average the fps is about 7-8 lower than MSFS A320. Good job on improving this. Hope you can improve the stutters.

**Comment by 2hwk** [comment]
Fixed by #4953 closing ☑️
