### ISSUE TITLE
[BUG] Flaps and speed brakes auto deploy

### ISSUE THREAD

**Issue by Bryce108** [flybywiresim/a32nx#3159]
**Mod Version**
Development

**Describe the bug**
When the aircraft spawns in it spawns in with then flaps full and the speed brakes at 100%, along with that if you pause the flight to adjust a setting, when you un pause it does the same mid flight and drops the flaps to full and the speed brake at 100%

**To Reproduce**

1. Hit ESC to bring up the menu mid flight
2. Resume flight
3.

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Saschl** [comment]
Remove all unused bindings for flaps/spoilers etc. There's a bug in MSFS currently that results in this behaviour for unused, but mapped axis. Also please try to complete the template as much as possible. Especially the last lines.

**Comment by Bryce108** [comment]
> Remove all unused bindings for flaps/spoilers etc. There's a bug in MSFS currently that results in this behaviour for unused, but mapped axis. Also please try to complete the template as much as possible. Especially the last lines.

What exactly do you mean by unused mapped axis, I have all my buttons mapped, and i will definitely try better before posting next time, Thank you.

**Comment by Saschl** [comment]
I'll also try to formulate better :D Some peripherals (as the Thrustmaster TCA Quadrant) add mappings for Spoilers and Flaps axis in MSFS. If you don't use these axis (via the addons), the sim somehow gets confused and sets those axis to 100%. So a fix would be to remove the mapping for Flaps and Spoilers in the sim settings

**Comment by Bryce108** [comment]
> I'll also try to formulate better :D Some peripherals (as the Thrustmaster TCA Quadrant) add mappings for Spoilers and Flaps axis in MSFS. If you don't use these axis (via the addons), the sim somehow gets confused and sets those axis to 100%. So a fix would be to remove the mapping for Flaps and Spoilers in the sim settings

Ahhh okay, so i have them mapped on my TCA side stick, so what your saying is check and see if they are mapped somewhere else ie. keyboard and remove them.

**Comment by hotshotp** [comment]
yep, this is a hardware issue reported before. @Saschl got it right
