### ISSUE TITLE
External Power available even when truck not connected

### ISSUE THREAD

**Issue by Daktadin** [flybywiresim/a32nx#316]

**Comment by CoffeePanda0** [comment]
This seems to be a bug with every aircraft and not exclusive to the A320 mod, so it might have to be a fix from Asobo

**Comment by NathanInnes** [comment]
Looks to be an asobo bug. Just replicated and SimVar is showing EXTERNAL POWER AVAIL as true when loading up.
![image](https://user-images.githubusercontent.com/18389085/91897883-d9b32c80-ec92-11ea-87c2-5c4d99349fa3.png)

**Comment by CoffeePanda0** [comment]
> 
> 
> Looks to be an asobo bug. Just replicated and SimVar is showing EXTERNAL POWER AVAIL as true when loading up.
> ![image](https://user-images.githubusercontent.com/18389085/91897883-d9b32c80-ec92-11ea-87c2-5c4d99349fa3.png)

Hey, sorry if I shouldn't be asking here but what software is that for reading simvars? Thanks!

**Comment by omarocasio** [comment]
Comes with the SDK, go into menu and turn on Dev Tools then in help you can download the SDK in which there's a tool to track all available simvars

**Comment by NathanInnes** [comment]
As this is a core game issue I will go ahead and close this.
