### ISSUE TITLE
[BUG] Sim rate

### ISSUE THREAD

**Issue by Bryce108** [flybywiresim/a32nx#3160]
**Mod Version**
Development

**Describe the bug**
My flight last night was fine, the only thing that changed today was that I updated the development version, next thing you know I was siming at 2X didnt realize until halfway through my flight. Dont know what happened or if this is a issue with the mod but i figured id post here. Also this kinda sucked since this is more of a flight sim issue but i had no idea when I decreased the sim rate if i was at a normal rate,  the only reason i knew i was at 2X was from ACARS after i filed my flight report for my virtual airline.

**To Reproduce**
1. just try a flight and monitior somehow your sim rate?
2.
3.

**Additional context**

Was this working before/when did the issue start occurring?
yes. today it started.
Is this a problem in the vanilla unmodded game?
I have not a clue.

Discord username (if different from GitHub): Agony7D

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by hotshotp** [comment]
you probably put your simrate with the hotkeys or something, this isn't related to the mod

**Comment by Bryce108** [comment]
I know exactly what they are, I never use them, nor did I touch them during the flight, until randomly im at 2X, then paused to go remember what they were to fix it.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
