### ISSUE TITLE
[BUG] set AP Speed Hold to selected mode: initial value is not actual speed

### ISSUE THREAD

**Issue by JLD95** [flybywiresim/a32nx#3164]
**Mod Version**

2021-01-23T185306

**Describe the bug**

When I set AP Speed Hold to selected mode not via speed button in the cockpit but via Simconnect (event SPEED_SLOT_INDEX_SET), initial value is not actual speed. For information, I control FS2020 with a Behringer X-Touch Mini 
 https://github.com/maartentamboer/X-Touch-Mini-FS2020. 

**To Reproduce**

1.   In cruise flight, make a simconnect event "event": "SPEED_SLOT_INDEX_SET", "type": "manual", "value": 1 in order to et AP Speed Hold to selected mode
2.  The speed displayed is not actual speed: around half of true aircraft speed; initial value not converted ? kts vs m/s ?
3.

**Expected behavior**

Like Speed button in the cockpit, initial value of selected speed is the actual speed of the aircraft

**Actual behavior**

The inital selected speed displayed is not actual speed: around half of true aircraft speed;

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by sidnov** [comment]
Most of the controller/external input related problems are solved with the use of our updated docs or external tools/softwares. Please take a look if your issue is unsolved or visit the #support channel on the FBW Discord
https://docs.flybywiresim.com/fbw-a32nx/a32nx-api/
