### ISSUE TITLE
[BUG] Empty paper after printing?

### ISSUE THREAD

**Issue by ErikNL80** [flybywiresim/a32nx#3166]
**Mod Version**

{
  "built": "2021-01-24T08:46:59+00:00",
  "ref": "",
  "sha": "",
  "actor": "Tyler Knox <16512508+tyler58546@users.noreply.github.com>",
  "event_name": "manual"
}

**Describe the bug**

I tried the new printer functionality on my flight from ENTO to ESKN. Asked for the METAR and from the received message page clicked the print button. Paper is empty...

**To Reproduce**

1. Go to the AOC menu and ask for weather
2. Go to received messages and click print
3. Watch the output

**Expected behavior**

A printed paper with the details from the MCDU.

**Actual behavior**

An empty page.

**References**

![Empty](https://user-images.githubusercontent.com/71258178/105629691-d63c5f80-5e44-11eb-8e1c-b6c002d5c94b.png)

**Additional context**

N/A

Was this working before/when did the issue start occurring?
New functionality.

Is this a problem in the vanilla unmodded game?
N/A

Discord username (if different from GitHub):

**Comment by myselfaaryan** [comment]
This must be caused by some other addon conflicting with the files. Are you able to recreate with a clean install?

**Comment by ErikNL80** [comment]
> This must be caused by some other addon conflicting with the files. Are you able to recreate with a clean install?

This was the only livery with a custom reg in the cockpit... (Wizz Air HA-LJA). Tested with the default FBW livery and it works.

**Comment by ErikNL80** [comment]
That was a fast closure... After digging into the panel.cfg I found the livery was missing the following entries:

[VPainting02]
size_mm=1024,1024
pixel_size=1024,1024
texture=$PRINT
painting00=Printer/Printer.html?Index=0,	0, 0, 1024, 1024

[VPainting03]
size_mm=1024,1024
pixel_size=1024,1024
texture=$PRINT_STATIC
painting00=Printer/Printer.html?Index=1,	0, 0, 1024, 1024

Could this be the cause?

**Comment by Saschl** [comment]
Exactly,  liveries shouldn’t include the panel.cfg. That can also cause a lot of other problems

**Comment by hotshotp** [comment]
Yeah I closed it because it's not related to the mod. Overwriting panel.cfg should never be done by livery makers

**Comment by AdamNZ** [comment]
I have a METAR addon (that pops up a METAR search/query window) that causes this conflict. No problem - I probably won't need that addon now (!).

However - there's info provided by that addon (temperature etc.) that doesn't appear in the AOC printout. Not being an A320 pilot in RL, I've no idea what info is normally printed out.

**Comment by MudulOzan** [comment]
I have the same issue
I am not new to the game but also flight sims too, so I may have done something wrong. I was following this video: https://www.youtube.com/watch?v=MKbyRr3W2vI
![image](https://user-images.githubusercontent.com/29442243/177058529-c4eb90b0-a8c3-4c14-99a6-a6348a74e25b.png)

currently I am only using map enhancement mod but nothing else
