### ISSUE TITLE
APU bleed too loud to be heard from outside

### ISSUE THREAD

**Issue by Rolando1967** [flybywiresim/a32nx#3167]
**Mod Version**last DEV from 24.01

With the last DEV version, the APU bleed tone can be heard too loud from the outside. That was not before. Please test If switched on, hearing from the outside is louder than the API.

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by hotshotp** [comment]
that is intentional, the pack valves are much louder than the APU

**Comment by Rolando1967** [comment]
Okay, but really so loud from the outside. Thanks for the answerVon meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: hotshotp <notifications@github.com> Datum: 24.01.21  21:10  (GMT+01:00) An: flybywiresim/a32nx <a32nx@noreply.github.com> Cc: Rolando1967 <s-pilot67@gmx.de>, Author <author@noreply.github.com> Betreff: Re: [flybywiresim/a32nx] APU bleed too loud to be heard from outside
  (#3167) 
that is intentional, the pack valves are much louder than the APU

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/flybywiresim/a32nx/issues/3167#issuecomment-766423829",
"url": "https://github.com/flybywiresim/a32nx/issues/3167#issuecomment-766423829",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by hotshotp** [comment]
> Okay, but really so loud from the outside. Thanks for the answerVon meinem Samsung Galaxy Smartphone gesendet. -------- Ursprüngliche Nachricht --------Von: hotshotp <notifications@github.com> Datum: 24.01.21 21:10 (GMT+01:00) An: flybywiresim/a32nx <a32nx@noreply.github.com> Cc: Rolando1967 <s-pilot67@gmx.de>, Author <author@noreply.github.com> Betreff: Re: [flybywiresim/a32nx] APU bleed too loud to be heard from outside   (#3167) that is intentional, the pack valves are much louder than the APU —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe. [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "[#3167 (comment)](https://github.com/flybywiresim/a32nx/issues/3167#issuecomment-766423829)", "url": "[#3167 (comment)](https://github.com/flybywiresim/a32nx/issues/3167#issuecomment-766423829)", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

I actually agree, i made it a teeny bit too loud which will be changed in the next update

**Comment by Rolando1967** [comment]
Super great thank you, you are the best!Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: hotshotp <notifications@github.com> Datum: 24.01.21  23:09  (GMT+01:00) An: flybywiresim/a32nx <a32nx@noreply.github.com> Cc: Rolando1967 <s-pilot67@gmx.de>, Author <author@noreply.github.com> Betreff: Re: [flybywiresim/a32nx] APU bleed too loud to be heard from outside
  (#3167) 



Okay, but really so loud from the outside. Thanks for the answerVon meinem Samsung Galaxy Smartphone gesendet. -------- Ursprüngliche Nachricht --------Von: hotshotp notifications@github.com Datum: 24.01.21 21:10 (GMT+01:00) An: flybywiresim/a32nx a32nx@noreply.github.com Cc: Rolando1967 s-pilot67@gmx.de, Author author@noreply.github.com Betreff: Re: [flybywiresim/a32nx] APU bleed too loud to be heard from outside   (#3167) that is intentional, the pack valves are much louder than the APU —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe. [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "#3167 (comment)", "url": "#3167 (comment)", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]



I actually agree, i made it a teeny bit too loud which will be changed in the next update



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/flybywiresim/a32nx/issues/3167#issuecomment-766441104",

"url": "https://github.com/flybywiresim/a32nx/issues/3167#issuecomment-766441104",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by hotshotp** [comment]
fixed in latest dev now :D

**Comment by Rolando1967** [comment]
Super class thank you !!Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: hotshotp <notifications@github.com> Datum: 25.01.21  19:42  (GMT+01:00) An: flybywiresim/a32nx <a32nx@noreply.github.com> Cc: Rolando1967 <s-pilot67@gmx.de>, Author <author@noreply.github.com> Betreff: Re: [flybywiresim/a32nx] APU bleed too loud to be heard from outside
  (#3167) 
fixed in latest dev now :D

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/flybywiresim/a32nx/issues/3167#issuecomment-767029426",
"url": "https://github.com/flybywiresim/a32nx/issues/3167#issuecomment-767029426",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
