### ISSUE TITLE
[REQUEST] Extend engine shutdown time

### ISSUE THREAD

**Issue by Rolando1967** [flybywiresim/a32nx#3169]
**Is your feature request related to a problem? Please describe.**
Spool down the engines visually extend from the outside

**Describe the feature you'd like to see implemented**

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by hotshotp** [comment]
this issue does not follow the template, however we should not close this as its an important one

**Comment by Rolando1967** [comment]
Super thank you, I think so too!  I am happy if it is right at some point.  Thanks for that and keep it up. You are a great team!Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: hotshotp <notifications@github.com> Datum: 25.01.21  21:11  (GMT+01:00) An: flybywiresim/a32nx <a32nx@noreply.github.com> Cc: Rolando1967 <s-pilot67@gmx.de>, Author <author@noreply.github.com> Betreff: Re: [flybywiresim/a32nx] [REQUEST] Extend engine shutdown time
  (#3169) 
this issue does not follow the template, however we should not close this as its an important one

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/flybywiresim/a32nx/issues/3169#issuecomment-767082990",
"url": "https://github.com/flybywiresim/a32nx/issues/3169#issuecomment-767082990",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
