### ISSUE TITLE
[BUG] Flaps 3 landing

### ISSUE THREAD

**Issue by airlinetycoon02** [flybywiresim/a32nx#3170]
**Mod Version**

0.5.2
**Describe the bug**

The Flaps 3 Button enabling a Flaps3 landing, but it‘s normally only for the GPWS. The trigger for a Flap3 landing is in the MCDU, but it‘s enabled by the Overhead button. This is not correct. You have to set it manually in the MCDU too.

**To Reproduce**

1. press the flaps 3 button on overhead panel
2.
3.

**Expected behavior**

I want to change the flap Setting on Approach Page between flaps full and flaps 3 

**Actual behavior**

When you set Flaps 3 on the GPWS-Flap3-Button on overhead panel, flaps 3 in the MCDU is enabled and not to change 

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by tracernz** [comment]
There are two seperate things you need to do for a flaps 3 landing. The first is turn on GPWS Flaps 3 Ldg on the overhead panel, which disables GPWS warnings and switches the ECAM landing memo from flaps full to flaps 3. This was finished in #3140 and is working in the dev branch now. 

The second thing is select CONF3 on the MCDU Perf APPR page, which changes the speed calculations on that page, and Vapp target for the approach. This will be completed in #2889 which is not yet merged. 

Please see those two PRs for manual references if you need more clarification of how it should work.
