### ISSUE TITLE
Cold and dark things

### ISSUE THREAD

**Issue by Daktadin** [flybywiresim/a32nx#318]
Engine bleed and generators, including APU, are turned on. Also landing lights are retracted and not on off position(middle).

**Comment by CoffeePanda0** [comment]
Engine bleed and generators are still Inop at the moment so they have to be left default I believe. I'll look into fixing the landing light issue now, can another pilot or engineer just confirm it should be in off before I make a request?

**Comment by PCGamesF1Tech** [comment]
Hi,
Bleed and generators are not switched off when leaving the aircraft.

**Comment by AdenFlorian** [comment]
@PCGamesF1Tech Just to clarify, the retract position (the furthest down position) is never used? so we should default it to the middle (OFF) position for cold and dark?

**Comment by PCGamesF1Tech** [comment]
No, I'm sorry!
I don't know the switch labels by heart... 
I put it to on (up) when receiving takeoff clearance and put them fully down (retract obviously, which is flush with the wing and off) after landing when leaving the runway
