### ISSUE TITLE
Gear up/down shime

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#3180]
**Is your feature request related to a problem? Please describe.**

Gear operation low-shime 

**Describe the feature you'd like to see implemented**

I don´t really know if it is already implemented or worked on.
It is the low-shime, once after takeoff, when the Gear is fully retracted, and before landing, when the Gear is fully extended, after door operation is done.
 
With this shime, die emergency-exit-lights goes OFF / and ON.

I know, that not every company have it, but all the companys I fly for and i know, have a low-shime , connected to the EMER-exit signs. 
-> it is mainly for EMER-exits signs in the passenger cabin, BUT I know from my own ears, you can also hear it in the cockpit, because the speakers are right behind the cockpit door

https://youtu.be/XfhQu7GEQZM?t=461 you can hear the low shime after gear-up... (-> also after gear down)

**Additional context**

Discord username (if different from GitHub):

**Comment by Watsi01** [comment]
The chime is in, as long as you switch your no smoking to auto (that's the chime). I can't say anything about the EMER light though.

**Comment by andrejetcat** [comment]
thank you, I didn´t recognise it yet :)

**Comment by MisterChocker** [comment]
The chime comes from the NO SMOKING indication which is linked to the emergency lights. They turn on when the landing gear is extended and the chime sounds once.
NO SMOKING needs to be set to auto.

**Comment by andrejetcat** [comment]
My fault, sorry for that, I dont set the No smoking properly, because of way of movement-issue :) Thank you!
