### ISSUE TITLE
ALT cannot be in managed mode when HDG is active

### ISSUE THREAD

**Issue by nobodyn0se** [flybywiresim/a32nx#319]
ALT can be in managed mode only if the aircraft has NAV mode active. Otherwise, selected mode (HDG) will change the ALT mode from managed to OP CLB or OP DES along with two click sounds to notify mode change.

**Comment by Curtis-VL** [comment]
What mode would show in level flight in that case? I thought lateral and vertical modes were separate.

**Comment by ukflyer** [comment]
He may be right!! :D

Engagement of the managed vertical modes (CLB and DES) is not possible in non managed lateral modes (HDG or TRK). If the lateral mode is changed to a non managed mode, the vertical mode will revert to a non managed mode (OP CLIMB in climb, V/S or FPA in descent).

NAV mode may be armed when HDG or TRK mode is used for F-PLN interception if the track crosses the active leg before the TO waypoint.

https://hursts.org.uk/airbus-technical/html/ar01s02.html

**Comment by Curtis-VL** [comment]
Ahhhhh, I get what is meant by this, talked to a real pilot. Will work on this soon. 👍

**Comment by JackZ974** [comment]
Disagree. 
The ALT HOLD has nothing to do with Horizontal guidance. ALT mode only disengages when another vertical mode is engaged.

Mode reversion  will occur when NAV is switched to HDG mode (either automatically or manually) only for DES (or CLB) managed modes. The reversion (accompanied by a triple clic sound) will show in that case either OPEN CLB or V/S.
 
Source FCOM /SYS/AUTO FLIGHT/AP-FD Vertical modes & Modes reversion

**Comment by nobodyn0se** [comment]
@JackZ974 I'm also referring to the mode reversion (not ALT HOLD) upon switching from NAV to HDG which is currently not simulated.
