### ISSUE TITLE
[REQUEST] long-hauls with the A32NX? What about the ACJ-Version?

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#3195]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**

To my mind, the A32NX is by far the most useable plane in FS2020 by now. But we don´t have any long-haul Planes (the 787/747 are not useable with 75% inop systems...so, not interessting forenthusiasts)
What are you thinking about a A320NEO-ACJ Version of this great A32NX-MOD?
The real ACJ could carry 3000GAL more fuel in up to 4 additional Center-tanks.

https://www.acj.airbus.com/en/exclusive-products/acj320neo.html

It would be so awesome to serve VVIP long haul flight with such a nice plane!
"_The ACJ320neo can fly twenty-five passengers 6,000 nm/ 11,112 km or more than 13 hours non-stop_."

Maybe it would be possible to add/create the ACJ Version to the regular A32NX.

I think that could be very interessting. like PMDG create a "BBJ-Version" additional to their normal B737NGX version.  

**References**

https://www.acj.airbus.com/en/exclusive-products/acj320neo.html

**Additional context**

Discord username (if different from GitHub):

![tanks](https://user-images.githubusercontent.com/72918017/105845958-cc993000-5fdb-11eb-9081-363e61a3c443.jpg)

![erster_acj320neo](https://user-images.githubusercontent.com/72918017/105845456-0a498900-5fdb-11eb-8475-1811c07c0215.jpg)
![range_map](https://user-images.githubusercontent.com/72918017/105845543-37963700-5fdb-11eb-8670-df796209ee68.jpg)

**Comment by MisterChocker** [comment]
You requested the same issue before.

**Comment by MisterChocker** [comment]
Duplicate of #2252.
