### ISSUE TITLE
[BUG] FD only follows lateral navigation when AP engaged

### ISSUE THREAD

**Issue by jooglestumpe** [flybywiresim/a32nx#3196]
**Mod Version**
Latest experimental version

**Describe the bug**
When flying manually, the Flight Director ignores the lateral flight path. As soon as the Autopilot is engaged, it works.

**To Reproduce**
1. Enter any route into the MCDU
2. After takeoff, leave the AP off and the FD will not follow the route
3.

**Expected behavior**
FD following lateral navigation when AP off

**Actual behavior**
FD not following lateral navigation when AP off

Was this working before/when did the issue start occurring?
Yes / unknown

Is this a problem in the vanilla unmodded game?
No

**Comment by MapleNAV-TCASFAULT** [comment]
This is already a known issue

**Comment by jooglestumpe** [comment]
> This is already a known issue

I wasn't aware, thx!
