### ISSUE TITLE
[BUG] Printer should print with printer ouput selected

### ISSUE THREAD

**Issue by St54Kevin** [flybywiresim/a32nx#3198]
**Mod Version**
26th Jan 21 dev version

**Describe the bug**

When requesting weather no matter what type and output format is set to Printer, the message should print itself without going into the received messages. Only when its selected to MCDU it will not print.
![image](https://user-images.githubusercontent.com/448627/105889609-a8a31200-600e-11eb-94e4-2c99a3d657f0.png)

**To Reproduce**

1.
2.
3.

**Expected behavior**

Message should be printed automatically

**Actual behavior**

Message does not print

**References**

IRL experience

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by andrejetcat** [comment]
can confirm that from RL

**Comment by St54Kevin** [comment]
This is mainly a setting available on the ATIS page
