### ISSUE TITLE
"ON BAT" light should momentarily come on for a few seconds when aligning the IRS for each knob

### ISSUE THREAD

**Issue by larrydingus** [flybywiresim/a32nx#320]
"ON BAT" light does not come on

**Comment by Benjozork** [comment]
Can you provide a reference for that behaviour so we can keep track of those changes ? Thank you for the issue.

**Comment by larrydingus** [comment]
> Can you provide a reference for that behaviour so we can keep track of those changes ? Thank you for the issue.

Sorry I'm not sure what you mean, I'm new to this haha. Do you mean you want me to provide a link of this behavior in the real world?

**Comment by SmithFR** [comment]
Link provided by mReis#0721 
https://youtu.be/o3--ALDKLUc?t=32

**Comment by JackZ974** [comment]
That is true, and part of the Self test procedure of the IRS. each IRS will make the ON BAT flash briefly after a dozen of seconds, not immediately. The IRSes have their own backup battery used to maintain data in the event of electrical transient failure.

**Comment by tareksabet** [comment]
@Pleasure0102 anything you can do in here ?

**Comment by lukecologne** [comment]
> 
> 
> Unfortunately this feature cannot be implemented while we do not have access to the source model files from Asobo, as there is no texture associated with that light in the A320.

@tareksabet also nothing

**Comment by MudulOzan** [comment]
I think this still exists, I do not see ON BAT on stable version

**Comment by tracernz** [comment]
> I think this still exists, I do not see ON BAT on stable version

Wait about 10 seconds, as on real neos.
