### ISSUE TITLE
[BUG] Approach speed not respected

### ISSUE THREAD

**Issue by Road-to-Hell9** [flybywiresim/a32nx#3201]
**Mod Version**
A320NX Master
"built": "2021-01-26T17:57:58+00:00",
  "ref": "",
  "sha": "",
  "actor": "Imenes <71195324+ImenesFBW@users.noreply.github.com>",
  "event_name": "manual"

**Describe the bug**
Approach speed not respected, green dots ignored

**To Reproduce**
1.Start flight
2.ILS approach
3.Set speed to managed

**Expected behaviour**
In the older model of the aircraft, the aircraft removed the purple managed speed indicator and slowed down to the optimal flaps config speeds

**Actual behaviour**
In this model, the aircraft simply stays at the last managed speed before activating approach mode

Was this working before/when did the issue start occurring?
This was working the last time I tested it but that was a while ago

Is this a problem in the vanilla unmodded game?
Not sure

**Comment by MisterChocker** [comment]
Can you explain your issue with a bit more details? perhaps one or two pictures?

**Comment by Road-to-Hell9** [comment]
Of course, usually, when switching from Decent mode to Approach mode, the speed of the aircraft falls back to the first Green dot speed, but in my case, the Purple speed indicator, of the managed speed mode (Blue when speed is manually selected), just stays at the decent speed instead of calculating the landing speed and falling back to that.

**Comment by MisterChocker** [comment]
Okay that sounds odd and this is not the behavior from master (latest stable and dev version).

**Comment by Road-to-Hell9** [comment]
it appears to have been a singular error, did not reoccur, thank you for the help anyway
