### ISSUE TITLE
[BUG] Weather print service

### ISSUE THREAD

**Issue by b-flight** [flybywiresim/a32nx#3209]
Moin,
first of all thanks for this feature. Very good. Helps a lot.

I only noticed one thing on my flight from Hamburg to Oslo today. On the ground in Hamburg, the ATIS printout worked wonderfully. The only thing that ATIS could not be received in the air was it could not be printed. Metar worked, however.

On such a short flight it might not be that tragic. But with a longer one, the weather might change. And you know how the flight plan has problems with a change of approach.

Gruß
Dieter

Using the Custom FBW Mod 28d5a77 from 27.01.2020

**Comment by Benjozork** [comment]
Does not follow the provided issue template
