### ISSUE TITLE
Engine utilization at idle to 20%

### ISSUE THREAD

**Issue by EndermelonHD** [flybywiresim/a32nx#3218]
Even when the engines are idling, you start to roll because the power is at 20%

**Comment by Benjozork** [comment]
This is normal and that's how it is irl.

**Comment by N1EL** [comment]
A running engine at idle still produces thrust so 20% Idle with the engine running is what you will get.
So if your light it will roll, so Parking brake or weight will stop that effect.

Use the Parking brake if you light or going to stop for a while.
