### ISSUE TITLE
[BUG] ND Range Rings and waypoint's info distance mismatch

### ISSUE THREAD

**Issue by derl30n** [flybywiresim/a32nx#3219]
**Mod Version**

master

**Describe the bug**

Distance shown on the waypoint info does not reflect ND's range(or distance) rings.

**To Reproduce**

1. Insert a route or add a waypoint to the flight plan
2. Take Off and fly towards the waypoint
3. Compare distance from waypoint info to nd range rings

**Expected behavior**

Waypoint distance to match nd ring's range

**Actual behavior**

Waypoint distance and ring's range is off (misaligned)

**References**

![image](https://user-images.githubusercontent.com/1857322/106070036-ff3e4800-6103-11eb-867c-27be71a2e2cd.png)
![image](https://user-images.githubusercontent.com/1857322/106070041-01a0a200-6104-11eb-9f55-553122abb851.png)

**Additional context**

Was this working before/when did the issue start occurring?
I assume since ever.

Is this a problem in the vanilla unmodded game?
No Clue.

Discord username (if different from GitHub):

**Comment by AirbusA320Pro** [comment]
This looks like the USR waypoint is being calculated to the deck, rather than a virtual space above the waypoint geographic location at the same altitude as the aircraft. The slant range down to the deck would account for the extra distance reading on the ND.

**Comment by tracernz** [comment]
Alternately it could be just the top of the waypoint element is located at the desired distance rather than the centre.

**Comment by sidnov** [comment]
@tracernz Since you have contributed to the ND rewrite, would you still consider this an issue that is yet to be fixed or can we close it?

**Comment by tracernz** [comment]
No, this is about the old ND.
