### ISSUE TITLE
[REQUEST] CPDLC/PDC support on the DCDU/MCDU

### ISSUE THREAD

**Issue by Khitiara** [flybywiresim/a32nx#3222]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**

Implementation of the use of the mcdu and dcdu to communicate with ATC for departure clearances and other messages, through a provider service like [hoppie](https://www.hoppie.nl/acars/system/tech.html) which ivao uses (I am unsure if any such system is in use by vatsim or pilotedge at this time)

**References**

Some images are available in [this ICAO document](https://www.icao.int/NACC/Documents/Meetings/2016/ATS/DATALINKP13.pdf)

**Additional context**

Discord username (if different from GitHub):
Khitiara#0001

**Comment by txsty364** [comment]
possible that the DCDU implementation wont come out until a year from now I believe that they are waiting for vatsim to supply FBW with a API key to allow them to use the DCDU

**Comment by migte** [comment]
> possible that the DCDU implementation wont come out until a year from now I believe that they are waiting for vatsim to supply FBW with a API key to allow them to use the DCDU

VATSIM does not have CPDLC functionality. For this to be implemented, you would have to use HOPPIE, which is based on HTTP requests and is very easy to do.

**Comment by speedwaystar** [comment]
a stop-gap measure might be to redirect VATSIM text chat to the CPDLC screen, assuming that is visible to the API.

**Comment by sidnov** [comment]
First iteration of CPDLC been implemented in dev and experimental versions
