### ISSUE TITLE
CTD with the latest stable Version

### ISSUE THREAD

**Issue by PascalProgram** [flybywiresim/a32nx#3227]
Hello,
 
with the latest stable Version, evrery time I press on Worldmap in the beginning menu, I get a CTD. Without the A32NX folder in the Community folder it doesn´t happen.
I tryed it with the manuell download and the Installer.

With kind regards

**Comment by MisterChocker** [comment]
Please follow the provided template.

**Comment by Watsi01** [comment]
Do you have any other mod or custom livery installed? Please remove them and try again.

**Comment by PascalProgram** [comment]
Sorry, my fault. I`ll make a bug report
