### ISSUE TITLE
[REQUEST] Visible Pilot and Co-pilot Model in Cockpit

### ISSUE THREAD

**Issue by Rameyuk** [flybywiresim/a32nx#3228]
**Is your feature request related to a problem? Please describe.**

No

**Describe the feature you'd like to see implemented**

I would like to request an implementation of the Pilot and Copilot model into the cockpit.

It's possible to be done by editing this file: 
`\A32NX\SimObjects\AirPlanes\Asobo_A320_NEO\model\A320_NEO_INTERIOR_LOD00.gltf`

In it, navigate to the last nodes and add the following lines of code:

```
   {
    "name": "PILOT_0",
    "rotation": [0.0, 0.0, 0.0, 1.0],
    "scale": [1.0, 1.0, 1.0],
    "translation": [0.567698, 1.262695, 10.8251953]
}, {
    "name": "PILOT_1",
    "rotation": [0.0, 0.0, 0.0, 1.0],
    "scale": [1.0, 1.0, 1.0],
    "translation": [-0.567698, 1.262695, 10.8251953]
}
```
Then in the "nodes" number, add two additional numbers.

This will make the Pilot and Copilot model used by the default sim to be rendered inside the cockpit with its animation as well. The model itself will take from the Pilot and Copilot avatar set in each player's general options. These two lines only enables the models to be visible in LOD00 inside the cockpit.

**References**

The only reference to the real aircraft is that the A320 is designed to be flown by 2 pilots. So adding these codes into the LOD00 file will render both pilots to be visible inside the cockpit, complying with this real life requirement instead of flying in an empty cockpit.

I cannot take the credit for this. All credits go to Mugz or mixMugz for the idea. They have implemented this modification to most default aircrafts, A320 included. But it has become a maintenance nightmare for me whenever the A32NX mod has updates on the Development or Experimental Custom FBW version, which requires additional tweaking to the file everytime.

**Additional context**

Here's a screenshot of what it would look like in the cockpit when adding those two code lines. Please disregard the cockpit colour theme. That's just my personal preference and has nothing to do with this request.

![Screenshot (105)](https://user-images.githubusercontent.com/72927569/106150109-1ac25500-61cf-11eb-864b-a08efe937b0e.jpg)
![Screenshot (106)](https://user-images.githubusercontent.com/72927569/106150125-201f9f80-61cf-11eb-82bb-47bcd6e8b1da.jpg)

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment]
Please fill out the template

Also

> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning

**Comment by Rameyuk** [comment]
> Please fill out the template
> 
> Also
> 
> > BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning

Thank you.. Sorry about that. I was still typing the title of this request where my finger accidentally pressed the Enter key, and the whole request just got submitted before I even filled out the details. It's filled now.

**Comment by ErikNL80** [comment]
I am not very fond of adding these, but some people will... Can this be added as an option in the MCDU?

* pilot
* copilot
* both
* none

**Comment by Rameyuk** [comment]
Yeah, I suppose you're right. It is very subjective.
As for the possibility to be added as an option in the MCDU. I find it unlikely. Because these pilot models are all belong to the entire cockpit model file. So I can't think of any way to make it possible for the MCDU options to load an entire cockpit model with optional pilot models. I can only think of doing it from the installer side. But the developers would have to maintain all 4 versions of the cockpit every single time there's an update to the cockpit model. Which I believe is also a maintenance nightmare. But who knows, the FlyByWire team has been known for pulling off miracles. So maybe it's possible.

If you're wondering how it performs in the cockpit, here's a snippet that you can watch and see for yourself.
https://youtu.be/7KXIbb484Ys?t=4955

**Comment by DarkOfNova** [comment]
This will be much more plausible when we can edit the models and have an efb. So hopefully in the future, you'll have these options.

**Comment by Rameyuk** [comment]
I'm not even sure if using the EFB would make it possible. I don't know how the sim could reload an entire model file from within the current active flight session. I would have thought that the models would get loaded when you start the sim. So even if it's possible from using the EFB. Best case scenario, it would probably require us to restart the sim. And what happens during any update to the mod, by default it would get reset to the empty cockpit and we have to do the EFB thing again, and restart the sim again to get the pilots back. I suppose if everyone is okay with that process and the FlyByWire team could make it possible, then I guess it's fine.

As for editing the model of the pilots and co-pilots themselves, that can already be done by default using the pilot avatar choices in the general options/settings in the sim. Choosing the different avatar face and uniform will instantly change the pilot models in the cockpit as well.

**Comment by Benjozork** [comment]
You can have a model be set invisible using code.

**Comment by jydsj** [comment]
thank you！I like it very much. But it couldn't be displayed correctly. My cockpit disappeared. Only a32nx are installed in the community folder.

**Comment by Benjozork** [comment]
@jydsj this thread is a feature request - please seek support on our discord and avoid commenting on other unrelated discussions.

**Comment by Rameyuk** [comment]
@jydsj This feature request is for developers view. So I deliberately only include the necessary coding needed for this to make it work, since I assumed the developers would understand what I'm trying to do here. If you're doing it yourself and it breaks your cockpit. That means you put the code in the wrong place and/or you forgot to add the additional numbers in the nodes array.

I suggest you look for the original mod posted by Mugz on flightsim.to. And download the mod from there. It won't work since the version they made wasn't designed for the latest dev/experimental version of the A32NX mod. But you can open the file using notepad++ and look for where the line is put. then you can follow it and edit the cockpit LOD model in the A32NX folder yourself.

But once you know how to do and make it work, like me. You'll get the hang of it, whenever you update the dev/experimental version everyday, you just know what to do by muscle memory.

**Comment by jydsj** [comment]
@Rameyuk  Thanks a lot for your explanation.

**Comment by mixMugz** [comment]
> I suggest you look for the original mod posted by Mugz on flightsim.to. And download the mod from there. It won't work since the version they made wasn't designed for the latest dev/experimental version of the A32NX mod. But you can open the file using notepad++ and look for where the line is put. then you can follow it and edit the cockpit LOD model in the A32NX folder yourself.

I think will be better if mod will include by default. ;)
