### ISSUE TITLE
[BUG] Navigraph causes CTD

### ISSUE THREAD

**Issue by MisterChocker** [flybywiresim/a32nx#3229]
**Mod Version**

As of now.

**Describe the bug**

Navigraph seems to cause CTDs.
This happens in different phases of flight, e.g. on Preflight or Cruise or Approach.

A temporary solution is to remove the Navigraph.

**Linked Issues**
#3078
#2911
#3058

CDT without 3rd party software #1137

**Comment by Watsi01** [comment]
Could this also be the AI traffic / simconnect issue?

**Comment by tellurics** [comment]
@MisterChocker you closed #3058 but I'm not using Navigraph.

**Comment by MisterChocker** [comment]
> @MisterChocker you closed #3058 but I'm not using Navigraph.

Same as #1137

**Comment by mreza1st** [comment]
I am having the same issue when I start the flight without MSFS flight planner, set up the plan through simbrief and upload to the FMS system. Everytime flying from OIII to OIKK get a CTD a little after start of descent, about 80-85nm to OIKK. Tried the same route with MSFS flight planner, no problem.

**Comment by donstim** [comment]
I use Navigraph with the MSFS flight planner and have not experienced this issue. Is it only happening with Simbrief flight plans, or does it also happen when you input the flight plan manually?

**Comment by Funda86** [comment]
Just had the same problem. I was using fs 2020 with native fligh planner. At LIMC I opened navigraph to look at the jepson chart and after few minutes crashed. Could be the simlink of the app

**Comment by hsoerensen** [comment]
Same problem here, and only when there's a combo of FBW a32nx (sha `52854021623e006352e45057a9b8675065e3336a` from earlier today) + Navigraph. Using default Asobo works, and same when Navigraph is not on the latest cycle and using the above SHA.

Whether spawning at runway or C/D seems to make no difference

I can trigger a consistent crash with this combo by doing the following:
1) On MCDU setup a flight to LIML (example: LIPE/LIML in the MCDU INIT page)
2) On the F-PLN page select LIML -> ARRIVAL
3) Select runway ILS 36Z
4) Select ASTI1J as a STAR

At step 4 the game hangs, and it shows a list of VIA's where there's empty entries: ["NO VIAS", "", "DIXER", "", ..] 

It appears that there's stars that only shows when using the Navigraph / FBW a32nx mod. If using the default Asobo 320n there's no empty entries, and similarly if not using the Navigraph data.

**Comment by hsoerensen** [comment]
As I were typing the above hang up I came back to my computer and realized the game was responsive. Upon starting a new flight it seemed that the game simply is unresponsive for about 50 seconds when the above (https://github.com/flybywiresim/a32nx/issues/3229#issuecomment-778856464) is triggered.

**Comment by aguther** [comment]
Feel free to reopen this case if you think it’s still a problem. I fly everyday with Navigraph without issues.
