### ISSUE TITLE
Missing Cockpit Textures as of 1/28/21

### ISSUE THREAD

**Issue by golfcart22** [flybywiresim/a32nx#3231]
**Mod Version**

Both current table and DEV  version

**Describe the bug**

Please see screenshot - I have no more cockpit textures ? If I remove the folder from "community" everything works fine.

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

![Capture3](https://user-images.githubusercontent.com/78165777/106171174-4279d480-615f-11eb-824e-4239b2a54cfb.JPG)

**Comment by killyourradio** [comment]
Please try and remove all other mods/liveries from the community folder and test our mod again. This will help rule out mod conflicts.

Report back the result of this test.

**Comment by hotshotp** [comment]
This is what happens when you use liveries that modify panel.cfg - try using it without liveries

**Comment by killyourradio** [comment]
> 
> 
> This is what happens when you use liveries that modify panel.cfg - try using it without liveries

lately it's more often the copilot mod, but yeah, mod conflict.

**Comment by golfcart22** [comment]
Was the co-pilot mod - please close the ticket.

Thanks guys!  ( Great work so far )
