### ISSUE TITLE
[BUG] Landing Gear Handle Vibrates - Gear Drops/Extends without user action

### ISSUE THREAD

**Issue by lynscrafts** [flybywiresim/a32nx#3232]
**Mod Version**

{
  "built": "2021-01-27T02:18:03+00:00",
  "ref": "",
  "sha": "",
  "actor": "Michael Corcoran <tracer@outlook.co.nz>",
  "event_name": "manual"
}

**Describe the bug**

Landing gear handle spontaneously starts to vibrate, the gear is dropped. I did not move the gear handles nor drop the gear with a keyboard command. The issue seems to happen randomly while inflight or on approach.

**To Reproduce**

1.  Setup an approach
2.  Fly the approach and wait - usually withing 2 to 3 mins the gear handle start to vibrate. The gear will raise without user intervention.
3.  You can repeat the steps

**Expected behavior**

The gear handle should not vibrate/shutter at any point in the flight.
Raised gear stays up/lowered gear stays down

**Actual behavior**

Handle will vibrate and either raise or lower the gear without user intervention. 

**References**

Please see the attached video clip.

**Additional context**

Was this working before/when did the issue start occurring?
Latest dev release

Is this a problem in the vanilla unmodded game?
No

Discord username (ajs5mz2):

https://user-images.githubusercontent.com/71336522/106182384-ba023080-616c-11eb-986d-934019342cb1.mp4

**Comment by tracernz** [comment]
Check your bindings for all your different control devices, especially if you have something bound to toggle gear rather than up or down. Looks awfully like something is toggling it rapidly. Try with all other mods removed (including the Boeing cockpit texture).

**Comment by lynscrafts** [comment]
yes this was a binding issue.
