### ISSUE TITLE
[REQUEST] 【Clock】Function to stop or reset the Elapsed Time (ET)

### ISSUE THREAD

**Issue by kiokio0987** [flybywiresim/a32nx#3238]
**Is your feature request related to a problem? Please describe.**

Clock enhancements

**Describe the feature you'd like to see implemented**

I would like a function to stop or reset the elapsed time (ET).

**References**

VIDEO (2:15~)
*There is backlighting and it is difficult to see.
https://youtu.be/xczl6YiLRl0?t=138

FCOM
![ET0](https://user-images.githubusercontent.com/75520968/106255886-f1043f00-625d-11eb-8a4c-3617a8669c56.jpg)
![ET1](https://user-images.githubusercontent.com/75520968/106255890-f2ce0280-625d-11eb-9c7b-a4ead36aa505.jpg)
![ET2](https://user-images.githubusercontent.com/75520968/106255894-f497c600-625d-11eb-8cec-ad000683c655.jpg)

**Additional context**

I hope that one day it will be implemented.

Discord username (if different from GitHub):

**Comment by Samueleonard** [comment]
i dont know how easy this would be to implement but i feel it should be looked at quite soon as it is quite a big problem. the clock is used most pilots every flight, to track block/air times, and currently, it just instantly starts counting when you load in, with no way to disable it. ideally it would be in STP when you load in, and then the pilot can control it
