### ISSUE TITLE
Apu Gen active and Gen 1 off with Apu shutted down

### ISSUE THREAD

**Issue by lucagigli** [flybywiresim/a32nx#3240]
**Mod Version**
 Custom FBW 3fea682

**Describe the bug**
On the Eicam, electric screen shows Apu generatin power and Geni-Bat 1 off, but Apu is shutted down

**To Reproduce**

1.
2.
3.

**Expected behavior**
I expected that Apu shows 0 and Gen-Bat 1 is on as Gen-Bat 2. I have tried to swtich off on the overhead Apu Gen, and switched on again, but the Eicam screen eletric is still the same
![Cattura1](https://user-images.githubusercontent.com/78207482/106265000-b7641180-6226-11eb-94b3-18258308da99.JPG)
![Cattura2](https://user-images.githubusercontent.com/78207482/106265004-b7fca800-6226-11eb-9f1c-7bd0118ea771.JPG)
![Cattura3](https://user-images.githubusercontent.com/78207482/106265005-b8953e80-6226-11eb-9949-4a42974a157c.JPG)

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Watsi01** [comment]
The electrical page on ECAM is a placeholder right now (until we implement a correct electrical system) and is showing kind of nonsense.

**Comment by lucagigli** [comment]
Thank you

**Comment by davidwalschots** [comment]
As indicated by @Watsi01 ELEC isn't implemented yet. It will come sooooooon.
