### ISSUE TITLE
[BUG] Flight Simulator Crashes with message "crash exception breakpoint"

### ISSUE THREAD

**Issue by Lane-HOY** [flybywiresim/a32nx#3245]
- Using A32NX Experimental, updated today
- Windows 10.0.21301.1000
- Crash occurred just after T/O, during gear retraction, prior to thrust reduction.
- Event Viewer Exception code: 0xc00001ad
- Other applications running: SimBrief, Navigraph, OpenTrack, SmoothTrack
-----------------------------------------------------------------------------------------------------------
![Exception Break](https://user-images.githubusercontent.com/76738433/106354621-7980ef00-62f3-11eb-875e-1ab5d3308d54.png)

**Comment by mreza1st** [comment]
Try flying with MSFS flight planner see if you still have the issue.

**Comment by hotshotp** [comment]
Closing as no response
