### ISSUE TITLE
[BUG] Flaps and Speed break fully extended after pause in custom fbw

### ISSUE THREAD

**Issue by parker10101** [flybywiresim/a32nx#3254]
**Mod Version**

{
  "built": "2021-01-28T23:15:26+00:00",
  "ref": "",
  "sha": "",
  "actor": "Andreas Guther <andreas@guther.family>",
  "event_name": "manual"
}

**Describe the bug**

After press the ESC key to pause and resume, flaps and speedbreaks automatically extend to FULL/100%。

**To Reproduce**

1.start a flight
2.press the esc key to pause then resume
3.flaps and speedbreaks automatically extend to FULL/100%

**Expected behavior**

Nothing happened after pausing like the non-cfbw version.

**Actual behavior**

Flaps and Speed break fully extended after a pause.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
This bug has not appeared in the non-cfbw version.
Is this a problem in the vanilla unmodded game?
I've modified ThrottleConfiguration.ini for Thrustmaster TCA.

Discord username (if different from GitHub):parker10101

**Comment by aguther** [comment]
I assume you don't have the TCA add-on (yet)? I had the same, the issue is not related to cfbw. Sometimes it happens, sometimes not. Remove the assignment of flaps and speedbrakes from your TCA until you have the add-on. Fixed it on my end. Now I have the add-on and it's fine with the mapping in place.

**Comment by aguther** [comment]
Please test if it's working that way - if not, please reopen the bug.

**Comment by lancealotg** [comment]
Thanks so much for finding the solution, this problem was driving me crazy.
