### ISSUE TITLE
Feature Request Fahrenheit  vs Celsius   

### ISSUE THREAD

**Issue by Tinpanva** [flybywiresim/a32nx#3266]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**

[https://i.gyazo.com/82c58d0ec1b5a1c7e94e6ab890b74728.png](url)

**References**

**Additional context**

Discord username (if different from GitHub):

https://i.gyazo.com/82c58d0ec1b5a1c7e94e6ab890b74728.png

**Comment by davidwalschots** [comment]
Yeah... No... Please try again with some actual text.
