### ISSUE TITLE
[REQUEST] Change to temperature displayed

### ISSUE THREAD

**Issue by Tinpanva** [flybywiresim/a32nx#3267]
**Is your feature request related to a problem? Please describe.**
It is not related to a problem in any way

**Describe the feature you'd like to see implemented**
We have the option to display imperial vs metric, I would like to extend that to the temperature display, so we can get Fahrenheit and not just Celsius

**References**

**Additional context**
Resubmitting the request as I goofed up the previous one

Discord username (if different from GitHub):

[https://i.gyazo.com/82c58d0ec1b5a1c7e94e6ab890b74728.png](url)

**Comment by beheh** [comment]
The weight change is an option for the real aircraft. I don't think the temperature unit can be changed, as things like ISA don't work as nicely in Fahrenheit.

**Comment by sidnov** [comment]
I don't see this being implemented in the A32NX since it requires a significant change and diverts away from the realistic behavior of an actual A320neo
