### ISSUE TITLE
[BUG] A32nx Overwrites Base-Game Files

### ISSUE THREAD

**Issue by Clink1234** [flybywiresim/a32nx#3272]
**Mod Version**
master, latest version, all versions

**Describe the bug**
In the a32nx folder (the one that goes in community), there are multiple folders in line with how the game organizes things. These are effects, html_ui, ModelBehaviorDefs, SimObjects, etc. On load time, these files are all "merged" with Official and with any other mods, so that in a sense the game reads its single merged Simobjects folder, its merged html_ui folder, etc.

In its current state, A32nx overwrites many A320neo files from Asobo on load time. This is good, it enabled the player to get an upgraded version of the plane, but its a drawback too, as now any mod makers do not have access to the base Asobo files. 

For example, lets say I wanted to use the MFD from the A320neo. I can link it inside my simobjects > etc. > panel > panel.xml, but the game would grab the A32nx MFD instead, since A32nx overwrites the base game on load. Since this occurs, all other mod makers are locked into using A32nx files if that's what the user has installed, which means their config files etc. must all be A32nx based.

However, A32nx is always updating, so mod makers are then locked into updating their mod in line with all A32nx updates, a hard thing to do.

What is the solution? To make A32nx completely standalone. To not overwrite Asobo files but "rename" them so that the game sees it as something new. This has already been done with the lights, they are named differently than the Asobo lights. Some of the panels are properly done too, like A32nx_Core and A32nx_Utils in the html_ui folder. The game will see these as new because the folders they are in are newly named specific to A32nx.

The issues occur where things are in the exact same folder structure and file name as the base game. These are the things that overwrite the Asobo files on load. It would not be that hard to fix, all that is required is to do the following...

1. Rename the files or the folders they are in to be A32nx specific (vCockpit > Instruments > A320_Neo becomes vCockpit > Instruments > A32nx)
2. Reference these files in the panel.xml or appropriate file (where is now says A320_Neo it would then say A32nx)

If this process is repeated for all files, and the SimObject folder was renamed (that's literally all that needs to happen), then the plane would be forked and the base files would be unaffected!

I understand this seems confusing, and I am happy to even work with a developer on fixing it. I know for a fact that making the A32nx standalone would aid many other mod developers and help the community, and I am ready to help make it happen.

**Expected behavior**
Expected behavior is that the A32nx files are standalone, that they do not overwrite any of the game's own files on load time.

**Actual behavior**
Actual behavior is that only some of the files are standalone, while many overwrite the base game's files, making them inaccessible to any other mods in community folder.

**References**
Here is a forum post I wrote on the subject, which explains some of what I said above... [https://forums.flightsimulator.com/t/load-time-file-structure-in-msfs-2020-using-base-files-in-your-mod/341217](https://forums.flightsimulator.com/t/load-time-file-structure-in-msfs-2020-using-base-files-in-your-mod/341217)

Was this working before/when did the issue start occurring?
This has been an issue since A32nx first released.

Is this a problem in the vanilla unmodded game?
The problem is not a problem in the vanilla game, but prevents mod makers from using the Asobo base files as explained above.

Clink123#4567

**Comment by tracernz** [comment]
https://github.com/flybywiresim/a32nx/issues/1215

**Comment by hotshotp** [comment]
Duplicate #1215
