### ISSUE TITLE
[REQUEST] TCAS warning sounds

### ISSUE THREAD

**Issue by Gsonz04** [flybywiresim/a32nx#3274]
**Is your feature request related to a problem? Please describe.**
No

**Describe the feature you'd like to see implemented**
I'd like to see the TCAS warnings implemented, at least the simple ones like "Traffic! Traffic!" 

**References**
https://www.youtube.com/watch?v=P7i_06vOOWQ
https://www.youtube.com/watch?v=H35wuyqIRjE

**Additional context**
It once happened to me that an AI plane was actually flying towards me at the same flight level. So I think that this feature actually has some relevance. If you are interested, look here: https://www.youtube.com/watch?v=B5i5KSUlWkY

Discord username (if different from GitHub): Gsonz#4539

**Comment by Jpv60** [comment]
Very good idea !

**Comment by MisterChocker** [comment]
TCAS META ISSUE #1097
