### ISSUE TITLE
Autopilot and Speed tape bugs.... See video attached. Current Dev file.

### ISSUE THREAD

**Issue by nabil74** [flybywiresim/a32nx#329]
Refer video file below
https://youtu.be/hJjwXSzt7cc

At 8-9 seconds speed tape jumps (drecreases to 0)

At 17seconds it comes back eradically. and demonstration that autopilot is not activating. 

AT 40 seconds turn off autothrottle and turn back on.. autoopilot still not activating.

At 45seconds VS +1700 shows up on FFD (even though mode is managed as part of flight plan)

**Comment by nabil74** [comment]
Reloaded game and tested again but autopilot worked the second time.
Weird.

**Comment by Brenchen** [comment]
> Reloaded game and tested again but autopilot worked the second time.
> Weird.

Did you want to try it a few more times and see how you go?  It might just be a glitch in the game itself, I had that happen to me with other parts.

**Comment by 0nnyx** [comment]
Had similar issue with the 0.2.0 downloaded yesterday: 
Speed going to 0 from time to time on the PFD then autothrottle pushing engines to max. After 5 to 10 seconds, the speed ribbon gets back to the normal speed and autothrottle settles back to assigned speed.
This happened only during leveled flight / CRZ mode and repeated approx every 5 minutes.
This problem wasn't present in the 0.1.1 from 3 days ago.

**Comment by NathanInnes** [comment]
Closing as #1121 describes a little more about this and follows the template.
