### ISSUE TITLE
[BUG] Can´t adjust view in cockpit with right click holded

### ISSUE THREAD

**Issue by PHBCGN** [flybywiresim/a32nx#3292]
In cockpit mode, after instalaltion using exte and stable mode it is not possible anymore to adjust the view with the mouse having right button on mouse holded. 

Please fix cause it´s pretty hard when flying to switch thru all the windows for the setups.

Except that bug I´m very happy with the work you did and I´m fully excited to see what is coming up in the future!

All the best!

**Comment by Benjozork** [comment]
Does not follow provided template
