### ISSUE TITLE
QNH/STD not blinking when passing Transition Alt

### ISSUE THREAD

**Issue by elastisteve** [flybywiresim/a32nx#3293]
**Mod Version**
Custom FWB c705061

**Describe the bug**
I've set both the Transition Altitude and Level in the FMC, but when passing them the STD / QNH box doesn't blink / flash on the PFD. In fact I never saw it flashing ever, even with other versions (stable, dev etc).

Yesterday I removed the A32NX folder and reinstalled the mod again from scratch, with the same result.

**To Reproduce**
1. Load flight plan from Simbrief - for example going from LOWW to LOWI
2. Set Transition Altitude at 10000 and Transition Level at 11000 in the PERF TAKE OFF and APPR pages.
3. In OPTIONS > FMGC > I have Default Baro set to *AUTO or *HPA (tried both) and Weight Unit to *kg
4. Set QNH to 1025 before take off
5. Set QNH to STD after passing the TA

**Expected behavior**
QNH 1025 should start flashing in the PFD between 10000 and 11000 when climbing
STD should start flashing in the PFD when descending between 110000 and 10000

**Actual behavior**
QNH 1025 and STD (in the PDF) won't flash/blink

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Never saw it working. I'm using the mod for several months.

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub): elastisteve#7446

**Comment by Kimbyeoungjang** [comment]
how to install A32NX? through installer?

I was working on it and it is working normally(because it is same as Altitude indicator flashing logic).

I checked that yesterday.

make sure you have correct transition altitude on DEV mode in sim.
you can check that enable dev mode in settings, top of the sim - model behavior -> local var -> search TRANS

Also, maybe simbrief flightplan is problem i think? because i have both manually inserted flightplan and automatically insert by asobo worldmap.

**Comment by elastisteve** [comment]
@Kimbyeoungjang  thanks!

I've tried what you said. TRANS was showing both correct TA and TL (I've used 10000 and 11000).

Did a short hop without simbrief and had the exact same problem. I had set QNH 1007 and it didn't flash at any point all the way up to by CRZ level of FL180. I then changed to STD and on the descent no flash anywhere from 10000 to 11000. At 9000 I then changed to QNH again. It just never blinks.

Everything else just works perfect. I'm really puzzled.

**Comment by Kimbyeoungjang** [comment]
> @Kimbyeoungjang thanks!
> 
> I've tried what you said. TRANS in local var was showing both correct TA and TL (I've used 10000 and 11000).
> 
> Did a short hop without simbrief and had the exact same problem. I had set QNH 1007 and it didn't flash at any point all the way up to by CRZ level of FL180. I then changed to STD and on the descent no flash anywhere from 10000 to 11000. At 9000 I then changed to QNH again. It just never blinks.
> 
> Everything else just works perfect. I'm really puzzled.

https://drive.google.com/file/d/1XVDdeoiObUjVr4uQF5pHDo3aXYcmU8PC/view?usp=sharing
i tested with fbw branch to using installer. both working correctly

**Comment by elastisteve** [comment]
> https://drive.google.com/file/d/1XVDdeoiObUjVr4uQF5pHDo3aXYcmU8PC/view?usp=sharing
> i tested with fbw branch to using installer. both working correctly

Thanks for sharing, but it doesn't work here.

[https://drive.google.com/file/d/1hM-PazcALDc37pcwTp6RxO6ex80KofeZ/view?usp=sharing](https://drive.google.com/file/d/1hM-PazcALDc37pcwTp6RxO6ex80KofeZ/view?usp=sharing)

Here is a short flight. I also use the installer, latest version from today. On the FMC you can see (very small) a Trans Alt of 6000, which can also be seen in the Dev Model Var window at the bottom left.

QNH is set 1008.

I never blinks/flashes.

I have the default FBW livery.

I do have a bit of payware scenery (most from ORBX, Justsim, etc), no other planes or liveries.
And MS2020 Premium Deluxe. 

I can't explain the behaviour. Everything else works exactly as it should.

**Comment by Kimbyeoungjang** [comment]
> > https://drive.google.com/file/d/1XVDdeoiObUjVr4uQF5pHDo3aXYcmU8PC/view?usp=sharing
> > i tested with fbw branch to using installer. both working correctly
> 
> Thanks for sharing, but it doesn't work here.
> 
> https://drive.google.com/file/d/1hM-PazcALDc37pcwTp6RxO6ex80KofeZ/view?usp=sharing
> 
> Here is a short flight. I also use the installer, latest version from today. On the FMC you can see (very small) a Trans Alt of 6000, which can also be seen in the Dev Model Var window at the bottom left.
> 
> QNH is set 1008.
> 
> I never blinks/flashes.
> 
> I have the default FBW livery.
> 
> I do have a bit of payware scenery (most from ORBX, Justsim, etc), no other planes or liveries.
> And MS2020 Premium Deluxe.
> 
> I can't explain the behaviour. Everything else works exactly as it should.

Please test without any mods. Just move everything in community folder to other location(there is only fbw a32nx) and test again please.


I tested again with remove fs2020, re-install, using installer - install a32nx and working normally.

**Comment by A320PHX** [comment]
I'll chime in here, same as elastisteve. No blinking on my end no matter what I try. Fresh install using the installer. I'm on version 099000bc.

**Comment by RichardPilbery** [comment]
@elastisteve @A320PHX Were you using live weather for your tests? If so, @Kimbyeoungjang it would be worth testing again with live weather.

**Comment by elastisteve** [comment]
@RichardPilbery Yes, I always use live weather.

**Comment by Kimbyeoungjang** [comment]
I also use live weather.
QNH Flashing logic is using AIRLINER_TRANS_ALT & FWC Flight Phase. So, we have to check both value.

but idk why that is not working. maybe if you using teleport in-game or something else, maybe not working...

I can't understand why that is not working because it is very simple code

**Comment by RichardPilbery** [comment]
The issue appears to be related to adding the blink class. The _blinkQNH() function is definitely being called at the right time but I'm not seeing any blinking...

**Comment by Kimbyeoungjang** [comment]
We checked that this is not working when enter other value in mcdu - takeoff transition altitude.

we fix that with new 2 pull request :) thank you for bug report.

**Comment by elastisteve** [comment]
> We checked that this is not working when enter other value in mcdu - takeoff transition altitude.
> 
> we fix that with new 2 pull request :) thank you for bug report.

I tried everything, but it's not flashing as @RichardPilbery said earlier. The fault also occurs when I don't enter "other value in mcdu". If I leave it at the default 10000 TA, still no blinking.

**Comment by Kimbyeoungjang** [comment]
> > We checked that this is not working when enter other value in mcdu - takeoff transition altitude.
> > we fix that with new 2 pull request :) thank you for bug report.
> 
> I tried everything, but it's not flashing as @RichardPilbery said earlier. The fault also occurs when I don't enter "other value in mcdu". If I leave it at the default 10000 TA, still no blinking.

i also fix that. just fwc phase problem(on my code). it will fix when merge TA logic.
