### ISSUE TITLE
[BUG] Mouse view adjustment in cockpit not possible

### ISSUE THREAD

**Issue by PHBCGN** [flybywiresim/a32nx#3294]
**Mod Version**
0.52 installed using installer

**Describe the bug**
With the mod it is not possible to use right click view adjustment with the mouse

**To Reproduce**
1. Open up MSFS with A32NX at any airport
2. Right click on mouse and movie it in cockpit view
3. No movement possible except zoom with wheel

**Expected behavior**
When keeping right ouse button on hold and moving mouse it´s supposed to change sight

**Actual behavior**
Actually nothing happens :P

**References**
-na-

**Additional context**
-na- 

Was this working before/when did the issue start occurring?
- Idk

Is this a problem in the vanilla unmodded game?
- No

Discord username (if different from GitHub): 

- APHK_SLX

Best regards and sorry for the mistake before!

**Comment by hotshotp** [comment]
This is not a problem with the mod, but rather your bindings on the freelook

**Comment by PHBCGN** [comment]
Actually it is not cause with the other aircrafts it´s working, only with the A320NX mod, even though this is happening I will for sure still use it and this is not meant to be offending.Freelok bindings seem to be okay because I haven´t changed the standard ones and in extern view or in pedestal and overhead it is working. only in pilot and co pilot view it is not.
