### ISSUE TITLE
[REQUEST] Show PAX and Cargo Loading on the EFB

### ISSUE THREAD

**Issue by Zyonix007** [flybywiresim/a32nx#3297]
**Is your feature request related to a problem? Please describe.**
no

**Describe the feature you'd like to see implemented**

I think when you start up the plane you can hit "load cargo" or "load pax" and watch the pax load in real time as the weight increases as they board. this would add a ton of realism 

**References**

**Additional context**

other aircraft have this feature in xplane 11

Discord username (if different from GitHub): Zyonix007

**Comment by Zyonix007** [comment]
![image](https://user-images.githubusercontent.com/60050366/106671321-4c933d00-657c-11eb-8d57-a34f572d47db.png)
having the seats turn green would be soo cool!!

**Comment by Rameyuk** [comment]
I wonder if the seat layout can be configured ourselves. I like to have 3-class layout with First class, business class, and premium economy.

**Comment by tracernz** [comment]
I think different layouts becomes infeasible if/when the cabin is modelled.
