### ISSUE TITLE
[BUG] Simbrief Fuel Factor M20

### ISSUE THREAD

**Issue by TVOpium** [flybywiresim/a32nx#3298]
**Mod Version**
FBW Version - MSFS 1.12.3.0

**Describe the bug**
Hello, during my flights on the mod, I noticed that the check made at Top Of Climb Fuel, and Top Of Descent Fuel was different by at least 1 to 2 tons. This is due to the fact that Simbrief does not have a 320 NEO which consumes 20% less than the 320. A feature in Simbrief where we can adjust the Fuel Factor here is the link of the corrected file.

https://www.simbrief.com/system/dispatch.php?sharefleet=eyJ0cyI6IjE2MTA4MjczMjI3NzYiLCJiYXNldHlwZSI6IkEzMjAiLCJjb21tZW50cyI6IkZMWSBCWSBXSVJFIiwiaWNhbyI6IkEyME4iLCJuYW1lIjoiQTMyME5FTyBGQlciLCJlbmdpbmVzIjoiTEVBUC0xQTI2IiwicmVnIjoiRC1BRkJXIiwiZmluIjoiMTA1Iiwic2VsY2FsIjoiIiwiaGV4Y29kZSI6IiIsImNhdCI6Ik0iLCJwZXIiOiJDIiwiZXF1aXAiOiJTREUzRkdISVJXWSIsInRyYW5zcG9uZGVyIjoiTEIxIiwicGJuIjoiQTFCMUMxRDFPMVMxIiwiZXh0cmFybWsiOiJDUy9MVU5BSVIgUlZSIDEwMCIsIm1heHBheCI6IjE4MCIsIndndHVuaXRzIjoiS0dTIiwib2V3IjoiNDEwMDAiLCJtemZ3IjoiNjI1MDAiLCJtdG93IjoiNzkwMDAiLCJtbHciOiI2NjAwMCIsIm1heGZ1ZWwiOiIyMTI3MyIsInBheHdndCI6IjEwNCIsImRlZmF1bHRjaSI6IiIsImZ1ZWxmYWN0b3IiOiJNMjAiLCJjcnVpc2VvZmZzZXQiOiJQMDAwMCJ9

**References**
Airliners
Simbrief
A320
A320 NEO

**Comment by ZigTag** [comment]
File a PR, not a bug report

**Comment by MisterChocker** [comment]
Current fuel consumption is not correct, our new wip engine model will take care of that.

**Comment by sidnov** [comment]
The profile for the A32NX does not require a fuel factor to be set anymore as verified with the latest dev version
