### ISSUE TITLE
[BUG] Incorrect weights in both recommended Simbrief Profile and EFB

### ISSUE THREAD

**Issue by donstim** [flybywiresim/a32nx#3299]
Neither the Simbrief recommended profile (labeled "Simbrief Airframe with correct weights") on the A32NX main github page, nor the Dispatch Overview page of the EFB recently added to the dev version of mod correctly reflect the A320NEO airplane weight variant being represented.  The weight values quoted in these two locations are different from each other as well.

**Mod Version**

{
  "built": "2021-02-02T21:02:00+00:00",
  "ref": "master",
  "sha": "5bc77ed72527f921a7a329e75c80553a0874950e",
  "actor": "ZigTag",
  "event_name": "manual"
}

**Describe the bug**

Transport airplanes are typically certified with a number of different weight variants. There is no certified weight variant with the weights specified in the Simbrief profile. The weights shown by the EFB appear to reflect the correct weight variant, but the numbers are rounded up to the next hundred pounds and therefore shows weights that are not legally permissible. Also, the EFB shows an incorrect fuel capacity.

The maximum takeoff weight and the empty weight are contained in the flight_model.cfg file.  The values for these are 174,165 lb (79,000 kg) and 90,400 (41,005 kg), respectively. While there are two different weight variants (WV54 and WV55) that have 79,000 kg as the maximum takeoff weight, I believe we have settled on WV55 as the one we are simulating. (WV54 has a lower max zero fuel weight and max landing weight.)

The weights for WV55 are available from multiple sources, I've included a screenshot of a page from the Airport Planning Document. The certified weights are specified in kilograms, so any time they are expressed in pounds it will be a converted number that is not (and should not be) rounded off. The weights are:

Maximum Ramp Weight (MRW): 79,400 kg (175,047 lb)
Maximum Takeoff Weight (MTOW or MTW): 79,000 kg (174,165 lb)
Maximum Landing Weight (MLW): 67,400 kg (148,591 lb)
Maximum Zero Fuel Weight (MZFW): 64,300 kg (141,757 lb)

The maximum fuel capacity is also contained in the flight_model.cfg file, with backup info provided in https://github.com/flybywiresim/a32nx/pull/2286. The fuel capacity is stated in that cfg file in terms of US gallons, but MSFS converts it into a weight (lbs or kg depending on the units selected in the options menu) where it can be seen in the fuel and loading menu. The fuel capacity is 41,989 lb or 19,046 kg.

![Screenshot (609)](https://user-images.githubusercontent.com/70166617/106676887-97a55400-656c-11eb-9de0-eb78488d3686.png)

Discord username (if different from GitHub):donbikes#4084

**Comment by viniciusfont** [comment]
We can include the fix for this issue on the PR (https://github.com/flybywiresim/a32nx/pull/3474)
