### ISSUE TITLE
[REQUEST] Adjustable EFB brightness

### ISSUE THREAD

**Issue by FoxtrotSierra6829** [flybywiresim/a32nx#3301]
**Is your feature request related to a problem? Please describe.**
No

**Describe the feature you'd like to see implemented**
Make the EFB brightness adjustable by either a slider inside the EFB itself (e.g. in the Settings), and/or adjust it based on environment variables. [time, PFD brightness, ND brightness, dome light, integ lights, flood... what ever seams reasonable] - (even better, but requires more work and testing). Currently, in night flights, the EFB is sometimes too bright.

Discord username (if different from GitHub):
Foxtrot Sierra#6420

**Comment by Benjozork** [comment]
Done
