### ISSUE TITLE
[BUG] High angle of attack at Cruise

### ISSUE THREAD

**Issue by Slowwwww** [flybywiresim/a32nx#3303]
**Mod Version**
0.5.2

**Describe the bug**
At crusing altitude of the angle of attack is excessive usually more than 3°

**To Reproduce**
Load up at any Airport on the runway and climb to cruising altitude with altitude hold and speed hold on.

**Expected behavior**
From my research should be 1-2°

**Actual behavior**
AOA is 4° which is in the yellow zone.
![1612312759648292719979881545133](https://user-images.githubusercontent.com/38446619/106681405-3fbf1b00-6575-11eb-867c-4ce31a0d9f36.jpg)

Was this working before/when did the issue start occurring?
 Was not working before.

Is this a problem in the vanilla unmodded game?
I do have other mods installed (scenery and aircraft.)

**Comment by donstim** [comment]
You say that from your research the angle-of-attack at cruise should be 1-2 degrees. Please supply your reference. The weight, speed, flight level, and cg are also relevant.

**Comment by Watsi01** [comment]
Please also check your icing. If engines or wings are iced, it could behave like that. Activate anti-ice for a while and see, if it's getting better (lower AOA).

**Comment by Slowwwww** [comment]
Must have found some bad numbers originally: https://www.airliners.net/forum/viewtopic.php?t=749969 although it is difficult to find a consensus: https://www.quora.com/What-is-the-pitch-of-an-airliner-flying-at-cruising-high-altitude. 

I tried flying at FL 350 at 300knots (indicated) and was not able to replicate the issue as the AOA was 2 degrees.
