### ISSUE TITLE
[BUG] EFB MAP ISSUE

### ISSUE THREAD

**Issue by airfirefighter** [flybywiresim/a32nx#3306]
**Mod Version**
"built": "2021-02-03T02:46:16+00:00",
  "ref": "master",
  "sha": "58226331dc863b799bffeb77bceaefc7655982cb",
  "actor": "Benjozork",
  "event_name": "manual"

**Describe the bug**
At the map if u press openstreetmap contributors at the bottom u go to another page and make unable to go back to previous main page or turn off the efb. 
![Microsoft Flight Simulator 3_2_2021 08_48_41](https://user-images.githubusercontent.com/71919620/106710178-2f9f4e00-65fe-11eb-87fc-4ec5743a0785.png)
Also from that page every time u move away from efb u got graphic problems
![Microsoft Flight Simulator 3_2_2021 08_50_00](https://user-images.githubusercontent.com/71919620/106710418-94f33f00-65fe-11eb-90fb-982ba040d6a0.png)

**To Reproduce**
![Microsoft Flight Simulator 3_2_2021 09_08_39_LI](https://user-images.githubusercontent.com/71919620/106711196-d0dad400-65ff-11eb-85bd-2457f8622373.jpg)

**Comment by Benjozork** [comment]
Note that we cannot block those links due to map copyright

**Comment by airfirefighter** [comment]
> Note that we cannot block those links due to map copyright

i understand maybe a way to be able to return at the previous page and not getting blocked in those links.

**Comment by TansyEliot** [comment]
> Note that we cannot block those links due to map copyright

I think a "Reset/Restart EFB" Button is going to be great for these cases. This button could be placed on one side of EFB. When pressing this button, the EFB is going to restart/reset and back to default state.

**Comment by bouveng** [comment]
Closing, as fixed by #5400
