### ISSUE TITLE
[BUG] Wrong fuel value(unit) on EFB shown

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#3307]
**Mod Version**

Dev + FBW

**Describe the bug**

The fuel value on the EFB is wrong. It shows 26.725kg. The right fuel capacity is 26.730 LITERS (density = 0.785 kg/l)

**To Reproduce**

1.turn on EFB, go to DISPATCH, look at fuel capacity
2.
3.

**Expected behavior**

fuel capacity should show in kg´s

**Actual behavior**

shows fuel capacity in Liters but with KG unit). so, wrong unit.  IRL we only use kg´s units

**References**

**Additional context**

Was this working before/when did the issue start occurring?
-
Is this a problem in the vanilla unmodded game?
-

Discord username (if different from GitHub):

![efb](https://user-images.githubusercontent.com/72918017/106723360-51e99980-6607-11eb-812a-1a60d322db28.jpg)
![fuel capacity](https://user-images.githubusercontent.com/72918017/106723365-52823000-6607-11eb-94d2-2c8e9e9f0bc6.jpg)

**Comment by Watsi01** [comment]
Please don't file issues regarding the EFB, since this isn't even in the dev version. It's not even beta and work in progress.

**Comment by ThatRedMelon** [comment]
It was released into dev yesterday

**Comment by Watsi01** [comment]
WHAT? Did I miss something?

**Comment by ThatRedMelon** [comment]
#3252 was merged

**Comment by andrejetcat** [comment]
I know that is still under development... but i only want to point that out... maybe it is useful to point it out in time, before other thinks build up on wrong values/units :)

**Comment by donstim** [comment]
The maximum fuel capacity for the variant being simulated is 6267 US Gal, which is 23724 (or 5, depending on data source) liters. See https://github.com/flybywiresim/a32nx/pull/2286. This for a 3-tank configuration, which is what is represented in the sim.
