### ISSUE TITLE
EFB/SIMBRIEF Username Input Failure

### ISSUE THREAD

**Issue by MjrIncident** [flybywiresim/a32nx#3309]
**Mod Version**
Latest Dev Version

**Describe the bug**
EFB - I was climbing from EGKK at approx 3000ft, when I went to enter my Simbrief username into the EFB for the first time.
I pressed SHIFT and M and immediately the plane went dark, with all electrics gone (and I crashed and killed a cow I think ^_^).

**To Reproduce**

1. Pressed SHIFT and M (first letter of my username) into Simbrief text field in EFB.
2. 
3.

**Expected behavior**
Expected to continue adding my complete username into the simbrief text field and getting connected to the Simbrief api.

**Actual behavior**
Pressed SHIFT and M (first letter of my username) into Simbrief text field in EFB. Instead of accepting my first entered character, it crashed the displays and all electrics to the plane.

Will try again later without using the CAPS button, to see if that helps.

**References**
n/a

**Additional context**
Was watching a live stream the day before - shortly after launch of EFB into the dev master branch and he had also triggered this bug while using the EFB, but I cannot confirm if it was because he used the CAPS button or not. He could not recall what he had pressed when trying to enter his username in Simbrief field of the EFB but it did also crash the plane electrics.

Was this working before/when did the issue start occurring?
It happened yesterday 1 hour after you put the EFB public.
Is this a problem in the vanilla unmodded game?
n/a

Discord username (if different from GitHub):

**Comment by Saschl** [comment]
Unfortunately, the EFB does not prevent keybindings from working. And it happens that SHIFT + M turns off master battery + alternator which might cause your issue.
![image](https://user-images.githubusercontent.com/19493808/106747566-5e301f80-6624-11eb-9bb5-4eaf2496738d.png)

Try with caps lock or do it on the ground. The username should be persistent across flights.

**Comment by MjrIncident** [comment]
UPDATE:-
Re-tried EFB on the ground and successfully added Username as you suggested - worked great.
On pushback I pressed a key (cant recall which one sorry but not SHIFT & M) and the electrics went again.

The EFB not preventing keybindings is most likely the cause. But I didnt use the same keys and it powered down again.
![Screenshot_8](https://user-images.githubusercontent.com/72098504/106751369-fdebae80-6620-11eb-95a7-ff616921e7c8.png)

**Comment by MjrIncident** [comment]
Would it be fixable by adding a dedicated "keyboard" rendered onscreen on the EFB itself, so pilots tap the character on screen. Just an idea.

**Comment by Saschl** [comment]
Yeah I think it was already discussed in the discord and will probably added at some point. Especially as there are more features planned which would need those inputs.

**Comment by MjrIncident** [comment]
Thank you for the update @Saschl.
