### ISSUE TITLE
[BUG] Captain and FO RMP Issue

### ISSUE THREAD

**Issue by Lunatic104** [flybywiresim/a32nx#3311]
**Mod Version**
997cbd8

"built": "2021-02-03T02:46:16+00:00",
  "ref": "master",
  "sha": "58226331dc863b799bffeb77bceaefc7655982cb",
  "actor": "Benjozork",
  "event_name": "manual"

**Describe the bug**

When using the logitech radio panel, COM1 only controls the Captains RMP, and COM2 the FOs RMP

**To Reproduce**

1. Switch the Capts radio to Comm2, adjust the frequency, watch the Comm2 standby freq.
2. Switch FOs radio to Comm1, adjust the freqeuncy watch the FOs standby freq.
3. Notice that on both RMP with these conditions the frequency seen doesn't change.

**Expected behavior**

RMPs should display the freq as programmed on the controller independently of each other.

**Actual behavior**

When using the logitech radio panel, COM1 only controls the Captains RMP, and COM2 the FOs RMP

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub): Lunatic#7920

**Comment by sidnov** [comment]
@Lunatic104 Is this issue still valid?

**Comment by Lunatic104** [comment]
I'll take a look today and report back.

**Comment by tracernz** [comment]
This would be up to however your Logitech panel interfaces with the sim wouldn't it?

**Comment by sidnov** [comment]
Mav suggested it was possible to work around these issues with either the updated hardware api docs or using an external tool to map the interactions. https://docs.flybywiresim.com/fbw-a32nx/a32nx-api/hardware/
