### ISSUE TITLE
[BUG] You can just walk out of the cockpit into the air

### ISSUE THREAD

**Issue by mishal321** [flybywiresim/a32nx#3316]
**Mod Version**

{
  "built": "2021-02-03T06:38:11+00:00",
  "ref": "fbw",
  "sha": "caa41491a156cd8b053d81e0facc2f7c86d0361d",
  "actor": "aguther",
  "event_name": "manual"
}

**Describe the bug**

**To Reproduce**

1. Go into cockpit mode
2. Move around, and try getting out of the cockpit by slamming into the windows.
3. ur outside the cockpit now gg

**Expected behavior**

**Actual behavior**

**References**

![image](https://user-images.githubusercontent.com/72044822/106786455-2e791b80-6614-11eb-8b63-18b6a583dd3a.png)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by ZigTag** [comment]
This is not something that needs to be fixed
