### ISSUE TITLE
Displays should self test every time turned up from brightness 0

### ISSUE THREAD

**Issue by benjwri** [flybywiresim/a32nx#332]
By setting the brightness of the PFD, MFD or ECAM to 0 you are entirely turning them off, and therefore whenever the brightness is subsequently turned up, the self test cycle should run.

**Comment by Benjozork** [comment]
see #165

**Comment by benjwri** [comment]
> re. #165

Don’t see how they are related, that’s them not turning off completely. You can see the functionality isn’t implemented from the code, and also the fact that when you power up the aircraft but wait to turn up the displays they don’t self test.

**Comment by Benjozork** [comment]
> Don’t see how they are related, that’s them not turning off completely. You can see the functionality isn’t implemented from the code, and also the fact that when you power up the aircraft but wait to turn up the displays they don’t self test.

Yes, and the other issue has discussions about them turning off / doing self-tests.

**Comment by topiek-fs** [comment]
Currently working on this, I have the EICAS working so far!

**Comment by topiek-fs** [comment]
(almost) Fixed in #363 

**BUT: ** The captain and FO PFD and MFD are the same panel, which means that if the FO changes his knob from off to a value, it also tests the captains panel. Nothing we can do about that except make another issue for when we do find a way to seperate the panels.

**Comment by AdenFlorian** [comment]
confirmed fixed by #363 

regarding self test be independent between the 2 sides of the plane, that will eventually be addressed as part of https://github.com/flybywiresim/a32nx/issues/427
