### ISSUE TITLE
[BUG] improve the gear animmation

### ISSUE THREAD

**Issue by lalloretpilou** [flybywiresim/a32nx#3320]
**Mod Version** dev mod
In reality the animation of the landing gear is slightly asynchronous. In addition, it takes about 40 seconds to enter and exit the landing gear.

**Describe the bug**

**To Reproduce**
1.Gear UP
2.Gear DOWN
3.

**Expected behavior**
https://www.youtube.com/watch?v=PUA50SzzmBU

**Actual behavior**

**References**
https://www.youtube.com/watch?v=PUA50SzzmBU

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by hotshotp** [comment]
This is wrong. This shows the aircraft without full engine hydraulics. The speed of the gear in the sim is realistic.
