### ISSUE TITLE
[BUG] Alternate fuel entry greater than 3.0 lbs displays "Entry out of range"

### ISSUE THREAD

**Issue by daveetasac** [flybywiresim/a32nx#3321]
**Mod Version**
{
  "built": "2021-02-03T19:03:44+00:00",
  "ref": "master",
  "sha": "b9245c886074dc9a8a8e6cdfd7724a5a3f8077c5",
  "actor": "Benjozork",
  "event_name": "manual"
}

**Describe the bug**
When entering the actual amount of alternate fuel (ie. 4.2 for 4,200 lbs) on the INIT B page, I get an "ENTRY OUT OF RANGE" message on the scratchpad.

**To Reproduce**

1. Powered up the aircraft at gate on batteries, then GPU.
2. Aligned IRUs and verified accurate position.
3. Entered KDFW/KSTL on INIT A, KMEM as alternate, CI of 20, CRZ of FL330.
4. Within INIT B page, clicked 1R twice to enter current ZFW/CG and entered block fuel.
5. Entered desired alternate fuel of 4.2 (4,200 lbs) into the scratchpad and pressed 4L to enter that value into the ALTN blue placeholder and received the "ENTRY OUT OF RANGE" message on scratchpad.

**Expected behavior**
It should have displayed a large 4.2, followed by a "/" and a green time in minutes, calculated from that entered value.

**Actual behavior**
Instead, a value of 4.2 gave the "ENTRY OUT OF RANGE" message. Accepted values are within the range of 0.1 - 3.0. Please read below for additional context and explanation.

**References**
![ALT-TIME-bug-github-screen](https://user-images.githubusercontent.com/4588613/106811839-858ee880-6634-11eb-811c-8e70bead05e2.png)

**Additional context**
Entering a value of 0.1 results in 0.5 lbs/3 minutes of reserve fuel. Entering a value of 3.0 results 14.6 lbs/-2856 minutes of reserve fuel. Anything outside of this range results in "ENTRY OUT OF RANGE." It appears the amount entered is being manipulated during insertion somehow.

Was this working before/when did the issue start occurring?
It has been an issue for at least a month.

Is this a problem in the vanilla unmodded game?
This feature not available in the vanilla unmodded game.

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment]
cc. @Lucky38i

**Comment by daveetasac** [comment]
I tested this functionality using KG (Metric) and it works fine. What is typed in scratchpad is properly stored. It appears to be an issue only while using the LBS (Imperial) system of measurement, and affects more than just the ALTN/TIME field. For example, I entered a MIN DEST FOB value of 6.5 lbs, and this resulted in 31.6 being stored. RTE RSV/% and TRIP WIND fields are working as expected.

INIT B fields confirmed affected while using LBS (Imperial system):

1. TAXI
2. ALT/TIME
3. MIN DEST FOB

**Comment by felixharnstrom** [comment]
I think I know what's causing these three fields to misbehave. When storing the entered values in the MCDU, they are are multiplied by the weight conversion factor (lb per kg) (so 1 lb is stored as 2.2 kg):

https://github.com/flybywiresim/a32nx/blob/da1f42236b04235a87c57966017050a9241ebf42/A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js#L1352

For the other fields, the input value is correctly divided by the conversion factor instead. This is the zfw setter for example:

https://github.com/flybywiresim/a32nx/blob/da1f42236b04235a87c57966017050a9241ebf42/A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js#L2411

Then, when drawing the INIT page, the stored value is multiplied by the conversion factor again:

https://github.com/flybywiresim/a32nx/blob/da1f42236b04235a87c57966017050a9241ebf42/A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_InitPage.js#L378

So it seems to me that the fix is to divide by the conversion factor instead of multiplying by it.
I can put ut a PR for this later, unless someone spots an error in my reasoning :)

**Comment by MisterChocker** [comment]
You are absolutely right, I had this issue on my radar all the time but haven't had the time to look into it.

The system unit is always KG, so every entry gets converted to KG, (divided by the factor of the unit the user selected in the options page) and when displaying the systems KG get multiplied the the same unit factor.

You can go ahead and open a pr.

**Comment by MisterChocker** [comment]
I would appreciate the effort if you find time to also look into this [issue](https://github.com/flybywiresim/a32nx/issues/3525) and check if it's caused by the same bad conversion.

**Comment by felixharnstrom** [comment]
I did some digging around after opening that issue (#3525) and while it's not exactly the same, it's in the same ballpark. It seems that the code for inputting the fuel values doesn't take the conversion factor into consideration at all (the entered value is just inserted 'raw' as kg):

https://github.com/flybywiresim/a32nx/blob/da1f42236b04235a87c57966017050a9241ebf42/A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_OFPData.js#L125

I'll open a couple of PR's with fixes for these issues some time later today. Unless we should merge them to a new issue about imperial unit conversions in general?

**Comment by MisterChocker** [comment]
> EDIT: Also, depending on whether the possible issue discussed [here](https://github.com/flybywiresim/a32nx/discussions/2845#discussion-1246561) is the intended behavior, it's possible that the PERF/W&B page might need more work than just an input conversion.

No, the ECAM rounds the FOB, and one shows only usable fuel whilst the other shows usable fuel + unusable fuel.

For the other, I'd suggest only making one PR to fix this.

**Comment by felixharnstrom** [comment]
> No, the ECAM rounds the FOB, and one shows only usable fuel whilst the other shows usable fuel + unusable fuel.
> 
> For the other, I'd suggest only making one PR to fix this.

Gotcha. What I was referring to specifically was that the PERF/W&B page allows you to load more fuel than usable + unusable combined. I wrote a bug report about that here: #3528. Of course I may be wrong and that's actually intended behavior, but it feels a bit odd to me. But that is a separate issue, so I'll try not to stray further off topic here :)
