### ISSUE TITLE
[BUG] Glide Ratio too high

### ISSUE THREAD

**Issue by CaptainOveur** [flybywiresim/a32nx#3322]
**Mod Version**

master

{
  "built": "2021-02-03T19:03:44+00:00",
  "ref": "master",
  "sha": "b9245c886074dc9a8a8e6cdfd7724a5a3f8077c5",
  "actor": "Benjozork",
  "event_name": "manual"
}

**Describe the bug**

I switched off both engines and flew approximately green dot speed. Winds calm. This resulted in a TAS and ground speed of 234 kt and a sink rate of 900 ft/min. This is a glide ratio of approximately 26:1. As far as I know the best glide ratio of an A320 is about 16, so the number in the simulation is much too high.

Great addon by the way!!!

My background:
Private pilot licence
C172, Aquila 211, Robin 2160 D, Super Decathlon, DA20
No A320

**To Reproduce**

1. Climb to FL140 in clean configuration
2. Switch on APU
3. Fly a stable green dot speed using pitch.
4. Note the numbers at about FL100 They should be like the ones described above.

**Expected behavior**

I would expect a much lower glide ratio.

**Actual behavior**

The glide ratio was much too high, around 26:1.

**References**

I got the glide ratio of a A320 from here (there should be better sources and it depends on weight and type of course, but 26:1 seems much too high:
https://aviation.stackexchange.com/questions/14814/could-a-commercial-plane-like-airbus-a320-glide-with-no-working-engines-from-110

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
In the original FS2020 A320 the glide ratio is a bit lower, but still too high.

Discord username (if different from GitHub):
![Cockpit Screens](https://user-images.githubusercontent.com/78443566/106813828-ceb15d80-6671-11eb-9104-72a7fce205df.PNG)

**Comment by MisterChocker** [comment]
Yes the current flight model still is not very accurate, we are currently working on a brand new engine model and will also improve the flight model along.

**Comment by aguther** [comment]
It should be much improved now on dev version. Feel free to reopen if you think it’s still wrong.
