### ISSUE TITLE
[BUG] EFB Text Tiny 4K Monitor and Have to Re-Enter Simbrief Username Every Time

### ISSUE THREAD

**Issue by speedbird5** [flybywiresim/a32nx#3327]
**Mod Version**
  "built": "2021-02-04T05:57:54+00:00",
  "ref": "master",
  "sha": "a9c1b726a814bbfb0255d9961193288bd010e8a5",
  "actor": "ZigTag",
  "event_name": "manual"

**Describe the bug**
1. EFB Text is tiny on a 4K Monitor - See attached image and text circled in red.
2. Also, I have to Re-Enter my Simbrief Username Every Time

**To Reproduce**

1.  On a 4 K monitor, look at EFB Dashboard page and observe tiny text as in image circled in red.
2.  Cannot load Simbrief from EFB Dashboard button, must re-enter Simbrief  username each time.

![InkedCapture_LI](https://user-images.githubusercontent.com/20328510/106858970-230a1b00-670e-11eb-875b-b2a583b493f8.jpg)

Was this working before/when did the issue start occurring?  Not sure

Is this a problem in the vanilla unmodded game?  Not sure

**Comment by Benjozork** [comment]
cc. @ZigTag

**Comment by tracernz** [comment]
Running 4k, don't have this issue...
![image](https://user-images.githubusercontent.com/9995998/106863904-0b428f00-672e-11eb-9588-9548133d836d.png)
What's your render scaling?
![image](https://user-images.githubusercontent.com/9995998/106863966-26150380-672e-11eb-8074-bec0ce8795df.png)
UI settings?
![image](https://user-images.githubusercontent.com/9995998/106864041-3e851e00-672e-11eb-917b-94eeea4408b8.png)

The interface scale setting makes the EFB button text smaller for me, but nothing else on the EFB.

**Comment by speedbird5** [comment]
Thanks.  The issue was indeed the Interface Scale Size.  I had to change it to 100.   BTW, for the interface scale change to take effect, I had to change the Render Scaling up and then back down.

I still have the problem with having to re-enter my username each time.  The FMGC>Options>Simbrief does retain my username.  It just seems to be the EFB.

**Comment by tracernz** [comment]
> Thanks. The issue was indeed the Interface Scale Size. I had to change it to 100. BTW, for the interface scale change to take effect, I had to change the Render Scaling up and then back down.
> 
> It's not a big issue, but why should the interface scaling affect the EFB text size ? The interface scaling doesn't affect the PFD or Nav or other displays.....

Yes, I think this bug is definitely valid still.

> I still have the problem with having to re-enter my username each time. The FMGC>Options>Simbrief does retain my username. It just seems to be the EFB.

I also noticed this. Not sure if a bug has already been filed.

**Comment by sidnov** [comment]
This issue is fixed in the current EFB version and more accessibility improvements are under development in flyPad OS v3
