### ISSUE TITLE
BRK LEVER shouldn't be able to be moved UP on the Ground

### ISSUE THREAD

**Issue by JackZ974** [flybywiresim/a32nx#333]
In the real Airplane, there is an electromechanical lock that prevent accidental operation of the gear lever when the A/C is on the ground. 
Not implemented in MSFS, but can be implemented in code

**Comment by omarocasio** [comment]
Okay will add that with the wheel system

**Comment by Benjozork** [comment]
Needs reference to behaviour of IRL plane.

**Comment by Caluka** [comment]
@Benjozork 
![image](https://user-images.githubusercontent.com/46251202/92039655-6ae1dc00-ed43-11ea-8c59-36d456bc5d3f.png)

**Comment by JackZ974** [comment]
Thanks Caluka, you saved me the hassle to dig into my FCOM for every mention I make. @Benjozork FYI I am an A320 Pilot IRL, if you want just follow our technical discussions on the Discord .

**Comment by Benjozork** [comment]
> Thanks Caluka, you saved me the hassle to dig into my FCOM for every mention I make. @Benjozork FYI I am an A320 Pilot IRL, if you want just follow our technical discussions on the Discord .

Yep I am aware, but for back referencing it is ideal to provide those references on PRs and issues.

A discord screenshot is enough.

**Comment by Benjozork** [comment]
@Caluka thank you :smile:

**Comment by JackZ974** [comment]
> 
> 
> Okay will add that with the wheel system

Actually the best IMHO would be to prevent the lever to be actuated while the "ON THE GROUND" status is true.

**Comment by JackZ974** [comment]
> 
> 
> > Thanks Caluka, you saved me the hassle to dig into my FCOM for every mention I make. @Benjozork FYI I am an A320 Pilot IRL, if you want just follow our technical discussions on the Discord .
> 
> Yep I am aware, but for back referencing it is ideal to provide those references on PRs and issues. Not everybody knows you are a pilot.
> 
> A discord screenshot / link is enough.

Anyways, Caluka has been faster than me on this one! 
But you remark is a good one, will submit pictures/screenshots from now on.
