### ISSUE TITLE
[REQUEST] Improve contrast if textures when lit

### ISSUE THREAD

**Issue by lalloretpilou** [flybywiresim/a32nx#3333]
**Is your feature request related to a problem? Please describe.**
It would be nice to improve the textures when they are lit by the sun. Look at my photo, the dashboard becomes unreadable with the sun. Everything is white and the shadows are poorly modeled.

**Describe the feature you'd like to see implemented**
![Microsoft Flight Simulator Screenshot 2021 02 03 - 17 36 45 95](https://user-images.githubusercontent.com/42711915/106904086-09130d00-66fb-11eb-82b7-f63d7b265804.png)

**References**

**Additional context**

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by hotshotp** [comment]
The textures are being worked on. Check the #progress channel on discord to see some sweet previews!

**Comment by sidnov** [comment]
We now have textures that were updated a couple of times after this
