### ISSUE TITLE
[BUG] Plane never stop when taxi

### ISSUE THREAD

**Issue by jeremygovi** [flybywiresim/a32nx#3338]
**Mod Version**
master branch:
{
  "built": "2021-02-03T17:13:22+00:00",
  "ref": "master",
  "sha": "8448f048fa55360c87583fa25490040bed3b94c7",
  "actor": "ZigTag",
  "event_name": "manual"
}

**Describe the bug**
When Taxiing, plane never stop until triggering reverse throttle or parking break

**To Reproduce**
1. On the ground, actionate the throttles to 50% for 3-4 seconds
2.  then go back to idle

**Expected behavior**
The plane accelerate to 10-20 knots average and would stop slowly because of aero dynamics and wheels frictions to the ground

**Actual behavior**
The plane continue to accelerate very slowly. You can turn arounnd the airport undefinitely, the plane will never stop

**References**
https://youtu.be/DuSTF3zin4k

**Additional context**

Removed  all mods or custom liveries, issue still occurs

**Comment by Benjozork** [comment]
This is correct behavior and that's how it works IRL, as confirmed by the IRL pilots we talk to.
