### ISSUE TITLE
[BUG] Performance Pages DES and APP disappear and become [Untitled] after performing WX Request

### ISSUE THREAD

**Issue by flyingpaul1980** [flybywiresim/a32nx#3348]
**Mod Version**

"built": "2021-02-05T07:14:46+00:00",
  "ref": "master",
  "sha": "b0d5993637530589055bfed267d7586d3a846ce3",
  "actor": "ZigTag",
  "event_name": "manual"

**Describe the bug**

Performance Pages für DES and APP disappear and become [Untitled] after performing WX Request. 

**To Reproduce**

1. Started the A320N Cold and Dark and Initialized a flightbrief via the Simbrief connection of the A320NX
2. Initialized, set up speeds and values for each performance pages from Takeoff to Approach
3. Did a WX Request METAR and Printed it out
4. Re-checked the performance pages and DES and Approach were gone, replaced with a blank page that says  [untitled]

**Expected behavior**

 I expect the WX request not to have any effect on the performance pages

**Actual behavior**

Performance pages of MCDU disappeared

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by JEP795** [comment]
I had same issue except I didn’t do a WX request. I had set up the page about 30 min before landing. And then on final approach it went blank with untitled message. Came back after landing. Someone else other than me had same issue in discord chat.

**Comment by FU2Max** [comment]
Having the exact same issue as OP.

**Comment by DFWSupertrooper** [comment]
Same issues on 2/7 flights today.  No WX request, just before getting into APPR mode.

**Comment by flyingpaul1980** [comment]
It might be unrelated to the wx request, i was able to reproduce it 3 times but it happened another time a bit later when i didnt request and print metar

**Comment by tracernz** [comment]
Just had this myself but luckily with WebUI-Devkit running. The bug is https://github.com/flybywiresim/a32nx/blob/master/A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js#L991 @MisterChocker

**Comment by FoxTrotAlpha691** [comment]
Greetings, glad someone is tracking this issue, I had it myself the last two days. Yesterday I emptied my Community folder, reinstalled the mod only and still had the same results, the PERF pages after CRZ all said UNTITLED at the top of the page.

https://user-images.githubusercontent.com/42688750/107116582-efc4aa80-6839-11eb-996b-d3e4e5028233.mp4

**Comment by Samueleonard** [comment]
Ive had this issue when selecting sid/star in the mcdu using navigraph on certain sids
