### ISSUE TITLE
[BUG] Can not set a ILS FREQ om the custom FBW version 

### ISSUE THREAD

**Issue by IDKLOLSS** [flybywiresim/a32nx#3359]
**Mod Version**

**Describe the bug**

**To Reproduce**

1. Click the NAV button by where you change the FREQ for ATC 

**Expected behavior**

**Actual behavior**

Was this working before/when did the issue start occurring?
I tried this a couple weeks ago and it worker

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub): Elon Kerman#9252

**Comment by Benjozork** [comment]
Please respect the issue template and be more specific

**Comment by tracernz** [comment]
Dup of https://github.com/flybywiresim/a32nx/issues/3268 anyway I think.
