### ISSUE TITLE
[BUG] Incorrect values on RMP at startup

### ISSUE THREAD

**Issue by DonMatberto** [flybywiresim/a32nx#3362]
**Mod Version**
Latest Developer Version from Installer
{
  "built": "2021-02-06T17:55:54+00:00",
  "ref": "master",
  "sha": "05c413683627fa74aea71646308fe02d60b1acc6",
  "actor": "Benjozork",
  "event_name": "manual"
}

**Describe the bug**
VHF1 on Captain Side and VHF2 on First Officer side are showing 0.00000 on Startup as the active frequency. 

**To Reproduce**

1. Turn on the batterys
2. Turn on the external Power
3. Turn on the RMP

**Expected behavior**
The RMP shows a valid active frequency.

**Actual behavior**
The active Frequency on VHF1 on Captain side should show 0.00000, the active Frequency on VHF2 on First Officer Side should show the same.

**References**
![grafik](https://user-images.githubusercontent.com/78639709/107113843-dc2d3a00-6861-11eb-8e12-e281c7f4ebd5.png)

**Additional context**
On the ATC menue it shows 0.000 for COM1 and COM2. By setting another frequency on ATC menue the frequency on VHF1 and VHF2 on RMP is changing too

Was this working before/when did the issue start occurring?

The issue came with one of the latest updates of the developer version yesterday

Is this a problem in the vanilla unmodded game?

No, its not

**Comment by MisterChocker** [comment]
Please post the content of the build_info.json

**Comment by theomessin** [comment]
RMP? That's me!

**Comment by foxmike80** [comment]
I'm having the same issue. Any solution yet?

**Comment by SierraBravo1** [comment]
Same for me.
Active frequency starts with 0.00000 for VHF1 and VHF2 from C&D.
But VHF3 starts with 121.950.

**Comment by theomessin** [comment]
> I'm having the same issue. Any solution yet?

Nope. We'll fix it at some point (definitely before releasing this feature to stable).

**Comment by davidwalschots** [comment]
This was fixed in #3980 by accident.
