### ISSUE TITLE
[BUG] Reverb G2 flashing black in lenses when looking at glass cockpits in developer version 359af5b

### ISSUE THREAD

**Issue by babyaby1** [flybywiresim/a32nx#3363]
**Mod Version**

Master build - 359af5b

**Describe the bug**

Using a Reverb G2 in VR, when I look at any of the glass screen in the cockpit (especially the tablet), the lenses flicker black randomly (looks like I am blinking).  This doesn't occur on your stable or if you look out the cockpit.  Only when looking at the ECAM, PFD and tablet.  This is not happening on when using an Oculus headset, only the Reverb G2.
This is not happening on your stable build at all.
My computer specs are AMD 5900x with a 3090 graphics card and 32gb ram.

**To Reproduce**

1.Use Reverb G2
2.Use build 359af5b
3.Look at glass screens, ECAM, tablet and PFD - screen will flicker black.  This is not airport dependent.

**Expected behavior**

Screen will flicker black randomly when looking at the glass screens.  Particularly bad when looking at the tablet.

**Actual behavior**

Screen will flicker black randomly when looking at the glass screens.  Particularly bad when looking at the tablet.

**References**

cannot give a screen shot of this problem

**Additional context**

Was this working before/when did the issue start occurring?
This works correctly in the stable v.0.5.2
Is this a problem in the vanilla unmodded game?
no.

Discord username (if different from GitHub):
abycrew#7289

**Comment by ChunkyDog** [comment]
I've had what sounds like this issue too, but on an Oculus Rift.  It doesn't occur on the default A320NEO or on the current stable version of the mod, but like babyaby1, it does appear to happen when looking at the EFB or a menu item, like the ATC window..

Strangely, for me it happens far more when I have the Dome Light switched on, dim or bright, whether it is dark outside or not.

**Comment by ChruutvoLuzi** [comment]
Can confirm, i had the exact same issue too last week with the G2. Thought it was a power issue but it only happens in the A32NX

**Comment by Benjozork** [comment]
Needs to be fixed in the MSFS rendering engine
