### ISSUE TITLE
Aileron droop & aileron spoilers@landing

### ISSUE THREAD

**Issue by PCGamesF1Tech** [flybywiresim/a32nx#337]
Hi,
this is more of a question as I didn't have the chance to try it yet:

1.Is the aileron droop simulated? (ailerons drop a few degrees down when flaps are extended) 

2. Are the ailerons raised (left&right) together with the spoilers after landing?

Thanks!

**Comment by Benjozork** [comment]
GitHub issues are for bug reports, please ask questions in our Discord :slightly_smiling_face: :

**Comment by wpine215** [comment]
1. I do not believe it is simulated in the default aircraft, it will have to be something we add when completely re-writing the FBW system.
2. I do not believe this A320 is equipped with a Florence kit (ailerons up at landing), which is an optional modification.

**Comment by PCGamesF1Tech** [comment]
Thanks for your inputs!
I've only seen this ailerons up "Florence kit" (nice to know 👍🏻) on our aircraft so far, I thought every new Airbus (neo) has it...

**Comment by PCGamesF1Tech** [comment]
For future reference:
Aileron droop (ailerons 5° down) when flaps are extended.
During landing roll they deflect 20° up (maximum deflection), called "Anti aileron droop" 😄 (at least in our manual)

**Comment by PCGamesF1Tech** [comment]
Reported this via Zendesk a few days ago (aileron droop & anti droop).
Meanwhile it's marked as "Solved". 
Lets see.....

**Comment by tareksabet** [comment]
I think it's fixed closing now
