### ISSUE TITLE
[BUG] Thrustmaster TCA A320 Throttle issues

### ISSUE THREAD

**Issue by Shutthup** [flybywiresim/a32nx#3370]
**Mod Version**

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

My Thrustmaster TCS a320 throttle is not working correctly in the dev build. It works fine in the stable version. The idle setting is roughly 50% throttle, and you have to go into the quadrants reverser mode to drop to idle, leaving reversers non-existant. There is on way that I have found to rectify the issue in sensitivities. The forward sensitivities are correct in the sense that I still hit my detents required, but the rest (IDLE and lack of reverse) is a mess.

Was this working before/when did the issue start occurring?
This started when switching from stable build to Experimental
Is this a problem in the vanilla unmodded game?
Yes

Discord username (if different from GitHub):

**Comment by HuguesTournier** [comment]
Bonjour
J'ai le même problème. Impossible de le régler !
Comment faire ?
Merci à vous 
Cordialement
Hugues

**Comment by Spartan3001961** [comment]
I'm using the custom build, and have no issues with the airbus throttle quadrant. I had a similar issue using either either the stable or dev versions though. With the custom build, I changed my ThrottleConfiguration.ini file as per the github doc too...

[Throttle]
Log = true
Enabled = true
ReverseOnAxis = true
ReverseIdle = true
DetentDeadZone = 2.5
DetentReverseIdle = -0.90
DetentReverseFull = -1.00
DetentIdle = -0.42
DetentClimb = 0.01
DetentFlexMct = 0.53
DetentTakeOffGoAround = 1.00

**Comment by HuguesTournier** [comment]
Ok merci. Ou trouve t-on ce fichier ?
cordialement

De : Spartan3001961 <notifications@github.com>
Envoyé : samedi 6 février 2021 17:05
À : flybywiresim/a32nx <a32nx@noreply.github.com>
Cc : HuguesTournier <htournier1@hotmail.fr>; Comment <comment@noreply.github.com>
Objet : Re: [flybywiresim/a32nx] Thrustmaster TCA A320 Throttle issues (#3370)


I'm using the custom build, and have no issues with the airbus throttle quadrant. I had a similar issue using either either the stable or dev versions though. With the custom build, I changed my ThrottleConfiguration.ini file as per the github doc too...

[Throttle]
Log = true
Enabled = true
ReverseOnAxis = true
ReverseIdle = true
DetentDeadZone = 2.5
DetentReverseIdle = -0.90
DetentReverseFull = -1.00
DetentIdle = -0.42
DetentClimb = 0.01
DetentFlexMct = 0.53
DetentTakeOffGoAround = 1.00

**Comment by Shutthup** [comment]
Thanks, it seems my ini is the issue here.

**Comment by Spartan3001961** [comment]
Glad I could help

**Comment by MisterChocker** [comment]
Closing since issue resolved.

**Comment by Shutthup** [comment]
It turns out this solves the main problem but now my detent spots are way
off due to having to lower neutral position almost all the way negative to
get idle.

**Comment by Shutthup** [comment]
Disregard, I kept playing with it and it seems to be good to go now.
