### ISSUE TITLE
[BUG] Impossible to change Flight level

### ISSUE THREAD

**Issue by CaptainRafael** [flybywiresim/a32nx#3371]
**Mod Version**

```json
{
  "built": "2021-02-05T20:14:24+00:00",
  "ref": "fbw",
  "sha": "f7846195758709be4cc058846ebc6bf2f0428a07",
  "actor": "aguther",
  "event_name": "manual"
}
```

**Describe the bug**

Impossible to change FL after simbrief import ( i haven't try without simbrief import )
**To Reproduce**

1. Generate Simbrief OFP 
2. Import it to the MCDU
3. Try to change FL  ( also note this is the 2nd leg of the plane ) 

**Expected behavior**

Able to change FL

**Actual behavior**

Impossible to change FL 

**References**

None as its obvious its a bug

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
Maybe not sure

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment]
This could be due to second leg since we still have no done flight phase.

**Comment by MisterChocker** [comment]
Duplicate of #3110
