### ISSUE TITLE
[BUG] RMP active frequencies no longer sync when RMP1 and RMP2 are both set to VHF1

### ISSUE THREAD

**Issue by joniatus** [flybywiresim/a32nx#3374]
**Mod Version**
 "built": "2021-02-06T14:57:17+00:00",
  "ref": "master",
  "sha": "cb2f6379eb0fc00ee72c592b194b065b2b07b33d",
  "actor": "ko-zone",
  "event_name": "manual"

**Describe the bug**
When both radio panels are set to VHF1, the active frequencies do not sync.  Syncing was a feature of the RMP rework using react and was verified working

**To Reproduce**

1. Start C&D, turn on power
2. Set both RMPs to VHF1
3. Change the active frequency on either panel and observe if they sync

**Expected behavior**
When you change the active frequency on one RMP it should sync the active frequency to the other  RMP

**Actual behavior**
It is no longer syncing active frequencies

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Yes was working after RMP rework using react.  Not sure if it's related to the RMP fix as I haven't flown for a couple days

Is this a problem in the vanilla unmodded game?
N/A

Discord username (if different from GitHub):

![rmp](https://user-images.githubusercontent.com/71446004/107125370-97ac9900-6877-11eb-80a6-0fd08fa45f31.png)

**Comment by theomessin** [comment]
Reproduced. Good catch!
