### ISSUE TITLE
[BUG] WEATHER RADAR DOESN´T DISPLAY

### ISSUE THREAD

**Issue by nrsproj** [flybywiresim/a32nx#3377]
**Mod Version**
 MASTER

{
  "built": "2021-02-06T14:57:17+00:00",
  "ref": "master",
  "sha": "cb2f6379eb0fc00ee72c592b194b065b2b07b33d",
  "actor": "ko-zone",
  "event_name": "manual"
}

**Describe the bug**

Weather radar doesn't display. 

**To Reproduce**

1. by turning on sys to 1
2. mode WX+T
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
"BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning"
