### ISSUE TITLE
[BUG] FP Page Distance not updating

### ISSUE THREAD

**Issue by mikecbr** [flybywiresim/a32nx#3379]
**Mod Version**
LATEST DEV ,AND ALSO  AP CUSTOM BRANCH 

**Describe the bug**
The distance miles in the MCDU FP page its not moving , is stuck.

**To Reproduce**

1.Load  A FLIGHT PLAN
2.
3.

**Expected behavior**
get the exact miles , its not moving

**Actual behavior**
Stuck miles MCD FP PAGE

**References**

**Additional context**

Was this working before/when did the issue start occurring? NO , IT WAS WORKING YESTERDAY 

Is this a problem in the vanilla unmodded game? NO

Discord username (if different from GitHub):

**Comment by GlitchedYT** [comment]
Also ND seems to be lagging a bit more now/refresh rate it much lower than before

Just adding this in case it was lowered from pr #3262

**Comment by mikecbr** [comment]
> Also ND seems to be lagging a bit more now/refresh rate it much lower than before
> 
> Just adding this in case it was lowered from pr #3262

Just opened a new report related to this ;)

**Comment by omarsmak** [comment]
If it is because of that performance PR, can we just revert it back?

**Comment by XSJoJo** [comment]
I'll have a look today.

**Comment by mikecbr** [comment]
> If it is because of that performance PR, can we just revert it back?

Revert it back ? Why? , no , its one of the best pr performance so far  just fix the problem , but dont revert this pr please  @XSJoJo   @omarsmak

**Comment by Saschl** [comment]
I'll leave my usual guess here, maybe it helps: (A32NX_FlightPlanManager.js)


` updateFlightPlan(callback = () => { }, log = false) {

        const newVersion = SimVar.GetSimVarValue("L:A32NX_FLIGHT_PLAN_VERSION", 'number');
        if (newVersion === this._currentFlightPlanVersion) {
            if (callback) {
                callback();
            }
            //     return;
        }`
Maybe the skipped update when no new flightplan version is being created leads to the distance not being updated properly as well? I commented out the return to have a quick check and distances seem to update now. Maybe you can apply your magic on that :)

**Comment by XSJoJo** [comment]
Ok I identified the issue and have a fix almost ready

> Maybe the skipped update when the flightplan version is not being incremented leads to the distance not being updated properly as well?

Yes you're 100% right. I didn't notice that updating the time/distance is done in the same place where we load all the waypoints.

**Comment by omarsmak** [comment]
> Ok I identified the issue and have a fix almost ready
> 
> > Maybe the skipped update when the flightplan version is not being incremented leads to the distance not being updated properly as well?
> 
> Yes you're 100% right. I didn't notice that updating the time/distance is done in the same place where we load all the waypoints.

Awesome! Will it fix this issue as well https://github.com/flybywiresim/a32nx/issues/3380 as I think they are somehow related.

**Comment by XSJoJo** [comment]
> Awesome! Will it fix this issue as well #3380 as I think they are somehow related.

Doesn't look like it. Investigating...

**Comment by doolok** [comment]
any update? I just grabbed the latest dev version and still noticed it wasnt working. I do notice its working on the navigation FMC display on the pilots side. The one that shows the weather radar, terrain and such.
