### ISSUE TITLE
[BUG] ND REFRESH VERY SLOW WHILE THE AC IS FLYING

### ISSUE THREAD

**Issue by mikecbr** [flybywiresim/a32nx#3380]
**Mod Version**
LATEST DEV

**Describe the bug**
The aircraft , specially when its flying , the ND instead of refrsh while its moving nicely like it was doing it before , its like its jumping forward , I think its related because of the optimization performance on long fligh plan PR 

**To Reproduce**

1.LOAD A FP 
2. CHECK THE ND WHILE THE AIRCRAFT IS FLYING 
3.

**Expected behavior**
Work as it was working before performance optimizations PR nice refresh but with the same performance as the new PR 

**Actual behavior**
Refresh jumping , not refreshing nicely 

**References**

**Additional context**

Was this working before/when did the issue start occurring?yes , it started ocurring after performance optimization long flight plans PR

Is this a problem in the vanilla unmodded game?NO

Discord username (if different from GitHub):

**Comment by mikecbr** [comment]
PR #3262

**Comment by pareil6** [comment]
Also reproduced - see the waypoints jumping every few seconds (ignore the T/D marker going mad):
![image](https://user-images.githubusercontent.com/73158172/107140936-7bfbce00-691d-11eb-9045-b5903fcb658c.gif)

**Comment by mikecbr** [comment]
> Also reproduced - see the waypoints jumping every few seconds (ignore the T/D marker going mad):
> ![image](https://user-images.githubusercontent.com/73158172/107140936-7bfbce00-691d-11eb-9045-b5903fcb658c.gif)


Yes , that's exactly what I'm talking about  :)

**Comment by XSJoJo** [comment]
That is super weird. I mean it's way that refresh isn't that high, and maybe it's a little bit too low now, but this weird jumping behavior shouldn't exist.

I can repro here as well.

**Comment by XSJoJo** [comment]
Ok this is weird - I can only repro if I open the ND in a separate window (Pressing Alt Gr + Left mouse Click).

Are you folks seeing that as well?

**Comment by pareil6** [comment]
I have the same behaviour even without the ND popped out - I'll record a gif shortly.

**Comment by XSJoJo** [comment]
Oh maybe it has something to do with lower FPS.

**Comment by XSJoJo** [comment]
Ok, found the issue: This seems to be caused by some weird smoothing algorithm in SvgMap.js when updating the plan position. Does anybody know what would that be good for? I'm wondering whether I can just remove it.

**Comment by ErikNL80** [comment]
Experienced the same. ND is very slow and visually it looks stuttering... Hope the PR fixes the issue!
