### ISSUE TITLE
[BUG] AutoPilot issues and Deviation 

### ISSUE THREAD

**Issue by maxrouter2** [flybywiresim/a32nx#3381]
**Mod Version**
developer version: 359af5b
{
  "built": "2021-02-06T17:55:54+00:00",
  "ref": "master",
  "sha": "05c413683627fa74aea71646308fe02d60b1acc6",
  "actor": "Benjozork",
  "event_name": "manual"
}

**Describe the bug**
1) aircraft deviates flightplan course randomly throughout the flight when autopilot is swithed on. (especially when approaching ils)
2) when taking off or landing the aircraft pulls to the left mainly and requires excessive rudder control to get straight
3) top of descent marker doesnt always appear and it seems the aircraft has trouble caluclating rate of descent and doesnt seem to get the ils approach at the desired altitutde 

**To Reproduce**
1. fly anyhwere in the dev version ( 359af5b) with autopilot and flightplan
2. observe 
3.

**Expected behavior**
1.follow flightplan accordingly with no deviation unless manual mode is stwitched on
2. aircarft keeps mainly straight and doesnt pull in any direction that darastically
3. top of descent marker (arrow) to always appear on routing and after initating decent at that point the autopilot gets to desired alitudue at an appropriate rate

**Actual behavior**
1. deviation constanlty along route (require autopilot disconnect and reconnect to get back on plan)\
2. taking off or landing aircraft pulled dramatically to one side making it difficult to control 
3. top of descent marker not always displayed and for the autpilot to calculate an appropriate rate of descent ( and for speed to be appropriate)

**References**
cannot screen record (n/a)

**Additional context**
i5-9300h 2.4ghz oc to 4.10ghz
gtx 1050
ram 8gb

Was this working before/when did the issue start occurring?
no/ since updating to devs version 359af5b
Is this a problem in the vanilla unmodded game?
not sure

**Comment by Benjozork** [comment]
Hello,

First, 359af5b is an EFB related commit.

> aircraft deviates flightplan course randomly throughout the flight when autopilot is swithed on. (especially when approaching ils)

This is two issues:

1. Controller overrides AP - solution: set a proper deadzone on aileron/elevator axis
2. AP goes direct to runway instead of following arrival - known in #939 

> when taking off or landing the aircraft pulls to the left mainly and requires excessive rudder control to get straight

Your rudder axis is not centered.

> top of descent marker doesnt always appear and it seems the aircraft has trouble caluclating rate of descent and doesnt seem to get the ils approach at the desired altitutde

Top-of-descent is not implemented, and neither is VNAV in any way currently.

Closing this issue as there is no previously unknown problem here.
