### ISSUE TITLE
[REQUEST] Change the button size slightly on the Chronometer display

### ISSUE THREAD

**Issue by zzyzxuk** [flybywiresim/a32nx#3384]
**Is your feature request related to a problem? Please describe.**

The 'date set' button on the chronometer is modelled in such a way that it obscures the first digit of the UTC time display from most seating positions, including the 'default' cockpit view.  I find it odd that Airbus would design a real-life instrument in a way that all of it couldn't be read, and I suspect that in real-life, the button is either smaller, or a little further to the left so it doesn't obscure the display.  

SImilarly, the thickness of the bezel on the panel itself, and the depth of the recess on the LCD display means that in the default seated view, the top bars of the 'ET display' are also obscured.

I know some of you will suggest that we simply change the viewing position, but one would really have to move the viewing position quite a bit to get this readable, and I suspect that the modelling isn't quite accurate yet.

**Describe the feature you'd like to see implemented**

Would like to see if a real-life pilot could verify this as a thing, and if so, would suggest either making the 'date set' button smaller, or shift it slightly to the left?

**References**

**Additional context**

Discord username (if different from GitHub):  zzyzxuk

![Capture](https://user-images.githubusercontent.com/62340504/107141446-a7cc8300-6920-11eb-924a-cd4ed55a380a.PNG)

**Comment by derl30n** [comment]
Issue resolved ![image](https://user-images.githubusercontent.com/1857322/162617500-9c0022e4-f4f9-4a20-b5ec-a54235c827c2.png)
