### ISSUE TITLE
[BUG] Landing light switches not fully independent

### ISSUE THREAD

**Issue by chssn** [flybywiresim/a32nx#3387]
**Mod Version**
master (05c4136)
{
  "built": "2021-02-07T05:52:09+00:00",
  "ref": "master",
  "sha": "0f2481ad9161e49a97ed3a379a5f8c3293e42461",
  "actor": "tyler58546",
  "event_name": "manual"
}

**Describe the bug**
Additional to #1022 - Landing light switches don't operate as expected in isolation. Operating one switch will cause both landing lights to move from retracted to un-retracted positions. Actual light function is separate as expected. _Operating the landing light switches will also move landing lights to and from retracted position when the aircraft is powered off._

**To Reproduce**
1. With aircraft powered **off**, check both landing light switches are in "OFF" position
2. Left and right landing lights remain in retracted position and are switched off.
3. Move left **or** right landing light switch to "OFF" position
4. Left **and** right landing lights move to approx 45 degrees and remain switched off.
5. Move opposite landing light switch to "OFF" position
6. Left **and** right landing lights move to fully (approx 90 degrees) un-retracted position and are switched off.
7. 3. Move left **or** right landing light switch to "OFF" position
8. Left **and** right landing lights return to approx 45 degrees and remain switched off.
9. Move opposite landing light switch to "OFF" position.
10. Both landing lights return to fully retracted position.
11. Power aircraft on with both batteries and external power.
12. Move left **or** right landing light switch to "OFF" position
13. Left **and** right landing lights move to approx 45 degrees and remain switched off.
14. Move same switch to "ON" position. Observe corresponding landing light turn on however both lights remain at approx 45 degrees. Opposite landing light remains off.
15. Move opposite switch to "OFF" position. First light remains turned on and both lights move to fully un-retracted position.
16. Move the same switch to the "ON" position (both landing light switches "ON")
17. Observe both landing lights switched on and fully retracted.

**Expected behavior**
1. Operating the left landing light switch will **only** operate the left landing light.
2. Operating the right landing light switch will **only** operate the right landing light.
3. Moving either landing light switch to the "OFF" position should move the corresponding light to the fully un-retracted position with no interim (45 degree) position.
4. When aircraft is cold and dark, operating the landing light switches should have no effect on the position of the landing lights.

**Actual behavior**
1. Moving either landing light switch to the "OFF" position will move both landing lights to a semi-un-retracted position whether the aircraft is powered or not.

**References**
http://www.a320dp.com/A320_DP/electrical/sys-3.5.5.html

![20210207115447_1](https://user-images.githubusercontent.com/33300267/107146410-f0476900-693f-11eb-903a-a05f6c32351f.jpg)

**Additional context**

Was this working before/when did the issue start occurring? Unsure

Is this a problem in the vanilla unmodded game? Yes

Discord username (if different from GitHub): shiftyghost

**Comment by Snapmatics** [comment]
We will have to see if there is an animation for the landing light otherwise we will have to wait for our exporter to be completely finished.

**Comment by tracernz** [comment]
The animation is now fixed. Remaining task is to add the logic for when the lights can/cannot extend/retract.

**Comment by bouveng** [comment]
> The animation is now fixed. Remaining task is to add the logic for when the lights can/cannot extend/retract.

I can have a look at that as part of my PR and the things I wanted to add to the lights. Just need a ref. to what powers the lights and their mechanism.

**Comment by derl30n** [comment]
No longer an issue
