### ISSUE TITLE
[BUG] ADIRS align light have a blue square on background

### ISSUE THREAD

**Issue by ArthurHetem** [flybywiresim/a32nx#339]
**Describe the bug**
ADIRS align light have a blue square on backrgound

**To Reproduce**
1. Start Batteries and EXT/APU
2. Put the ADIRS switches into NAV

**Expected behavior**
The light don't have the blue square on the background as we can see on this video: https://youtu.be/DyqCGsP7Tls?t=16

**Screenshots or Videos**
If applicable, add screenshots or videos to help explain your problem.
![image](https://user-images.githubusercontent.com/7545272/92049838-e6eb1c80-ed61-11ea-9e3c-75a33fbe858a.png)

**Comment by NathanInnes** [comment]
Working on it now

**Comment by NathanInnes** [comment]
Doing some digging, you would need the UV map I think in order to actually fix this so at this moment in time I don't believe I can fix it.

**Comment by lukecologne** [comment]
Reopened as this is still an issue

**Comment by wpine215** [comment]
ALIGN light is no longer used. Closing.
