### ISSUE TITLE
[BUG] Climbout Acceleration

### ISSUE THREAD

**Issue by lonewulf47** [flybywiresim/a32nx#3390]
**Mod Version**

0.5.2

**Describe the bug**

Acceleration when changing from SRS to CLB mode is too fast. At present the A/C aims for a level off during the whole acceleration phase, thus reducing Climb Profile considerably. 

**To Reproduce**

1. coduct normal managed climbout
2.
3.

**Expected behavior**

Acceleration msut be done in a shallow climb. Typical Climb Rate would be around 1000 to 1500 FPM depending on A/C weight

**Actual behavior**

Attemption Level-off

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment]
This is already resolved in our wip custom autopilot. Stay tuned!
