### ISSUE TITLE
[BUG] Misbehavior of FGS on initial descent

### ISSUE THREAD

**Issue by lonewulf47** [flybywiresim/a32nx#3391]
**Mod Version**

0.5.2

**Describe the bug**

When in CRZ mode and dialing in a lower Altitude, the A/C starts a shallow descent (~700FPM) and the FMA reverts to ALT*.

**To Reproduce**

1. Dial a lower altitude
2.
3.

**Expected behavior**

Nothing. the Airbus Logic does not permit to start a descent uncommanded

**Actual behavior**

Descent starts uncommanded

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment]
Please enter a title

**Comment by depthvader** [comment]
Can duplicate only when using bound control on throttle,  on screen knob causes desired lack of response. But when using Virpil encoder bound to altitude selection, a shallow descent begin automatically.

**Comment by lonewulf47** [comment]
Yes, you might be correct in your assumptions. I use LINDA in vonnection with a VRI MCP COMBO, which sets altitude via FSUIPC addresses. Nevertheless this issue shound be eliminated also when altering altitude this way.

**Comment by MisterChocker** [comment]
This will be fixed by our custom AP.
