### ISSUE TITLE
[BUG] Default Speed Reduction Managed Descent

### ISSUE THREAD

**Issue by lonewulf47** [flybywiresim/a32nx#3392]
**Mod Version**

0.5.2

**Describe the bug**

Speed reduction to 250 KIAS/FL100 in Managed Descent happens too late

**To Reproduce**

1.Descend through FL100 in Managed Descent Mode
2.
3.

**Expected behavior**

Speed reduction must happen in anticipation of a certain speed band allowing deceleration inorder to reach 250KIAS AT FL100/10'000ft

**Actual behavior**

Speed reduction happens AT FL00/10'000ft only

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment]
Please enter a title.
