### ISSUE TITLE
[BUG] Instruments update at half rate when in separate window

### ISSUE THREAD

**Issue by XSJoJo** [flybywiresim/a32nx#3398]
**Mod Version**
master ToT (Tip-of-Tree)

**Describe the bug**
Instruments update at half rate when in separate window

**To Reproduce**
1. Hover over ND and press Alt Gr + Left Mouse click

**Expected behavior**
Smooth update rate

**Actual behavior**
Update rate is half of the expected rate (only ~2fps)

**Additional context**

Was this working before/when did the issue start occurring?
Regression from the throttling PRs

Is this a problem in the vanilla unmodded game? No

Discord username (if different from GitHub): JoJo#7105

**Comment by XSJoJo** [comment]
Ok looked into this some. The root cause here is that _deltaTime that gets passed into all the instruments if half the expected value. Weird. If I use my own DeltaTimeCalculator, then it works, but that's some overhead.

**Comment by XSJoJo** [comment]
Aha, looks like this is caused by some logic in BaseInstrument/NavSystem: 

- It seems that when the instrument is in a separate window, the "quality" is set to high meaning that it only updates every 2nd frame.
- Then, NavSystem calls CanUpdate() in Update() but then it returns false for every 2nd frame, but deltaTime() gets still updated, cutting deltaTime in half.

**Comment by GlitchedYT** [comment]
https://drive.google.com/file/d/1l9sePbXG-H8F6nql2eCTiW6kvvOl_ZtG/view?usp=sharing

**Comment by omarsmak** [comment]
Yeah it happens to me as well, I guess this happens when you have the sim running on the window mode
