### ISSUE TITLE
[BUG] Performance degrading over time after RMP and FPM fixes.

### ISSUE THREAD

**Issue by GlitchedYT** [flybywiresim/a32nx#3399]
**Mod Version**
Custom AP Branch
 

```json
"built": "2021-02-07T08:29:56+00:00",
"ref": "autopilot",
"sha": "125b62b71bd15ef22cbb6ed14f4e55dd7d3ab487",
"actor": "aguther",
"event_name": "manual"
```

**Describe the bug**

After around 2h and 30mins into the flight i'm noticing almost identical performance issues we had before the RMP perf fix was implemented, though this time i don't think it's the RMP that's causing the issue. To be honest i have no clue what's causing it this time.

**To Reproduce**

1. Load C&D at KSAN
2. Load MCDU for this flight : https://www.simbrief.com/ofp/flightplans/KSANKJFK_PDF_1612707148.pdf
2. Perform flight like you normally would.
3. After around 2 - 2 1/2 hours observe FPS, CohorentGTDraw, and Frame time.

**Expected behavior**

Shouldn't have any issue with performance after the RMP fix and flight plan perf fixes were both merged.

**Actual behavior**

Experiencing minor to major performance issues after being in the air for more than 2 hours

**References**

About 2h 30mins into flight.
https://streamable.com/kg6v56
Around 2h 40mins into flight.
https://streamable.com/4r8um8
3h into flight
https://streamable.com/6bkb2m

**Additional context**

Was this working before/when did the issue start occurring? Not sure if it was happening before RMP and flight plan perf fixes.

Is this a problem in the vanilla unmodded game? No

Discord username (if different from GitHub):

**Comment by Firstofficerjose** [comment]
How can i fix this guys? this is what is happening to me lately, I got 10-17fps after 1hr flying during cruise, decent and landing phase...

**Comment by Benjozork** [comment]
This is being investigated. Please use stable if you don't want unexpected performance issue.

**Comment by MapleNAV-TCASFAULT** [comment]
https://streamable.com/qf85ug This was recreated after loading on appr with the same fpln as the original flight that had exact results, without fpln FPS was fine

**Comment by GlitchedYT** [comment]
Okay wow so this is probs related to the route... that's what I had though tbh

**Comment by XSJoJo** [comment]
Ok looks like this is still due to RMP. Something seems to leak with react. Attached are full JSON dumps of the entire DOM, at the beginning of the flight, and then a minute later.

[rmp_later.txt](https://github.com/flybywiresim/a32nx/files/5969396/rmp_later.txt)
[rmp_start.txt](https://github.com/flybywiresim/a32nx/files/5969397/rmp_start.txt)

**Comment by XSJoJo** [comment]
"cyclic" here means that we've seen the same object/value before already, so we don't traverse it again.

**Comment by XSJoJo** [comment]
For reference, here is the code that's being used to produce the json output:

```
function flatten(object, visited) {
    let result = {};
    if (typeof object === 'object' && object !== null) {
        let keys = Object.getOwnPropertyNames(object);
        for (let i = 0; i < keys.length; i++) {
            let key = keys[i];
            let child = object[keys[i]];
            if (!visited.has(child)) {
                visited.add(child);
                result[key] = flatten(child, visited);
            } else {
                result[key] = "cyclic";
            }
        }
    } else if (Array.isArray(object)) {
        for (let i = 0; i < object.length; i++) {
            let child = object[i];
            if (!visited.has(child)) {
                visited.add(child);
                result[i] = flatten(child, visited);
            } else {
                result[i] = "cyclic";
            }
        }
    } else {
        return object;
    }
    return result;
}

function flattenDom(dom, visited) {
    let result = flatten(dom, visited);
    result["nodeName"] = dom.nodeName;
    result["children"] = [];
    for (let i = 0; i < dom.children.length; i++) {
        result["children"].push(flattenDom(dom.children[i], visited));
    }
    return result;
}

const dataToSend = JSON.stringify(flattenDom(document.getRootNode(), new Set()));
```

**Comment by sidnov** [comment]
Looks like this issue hasn't occurred again in a long time after the RMP fixes. Feel free to re-open otherwise
