### ISSUE TITLE
[BUG] Wrong ETA calculation on FUELPRED page

### ISSUE THREAD

**Issue by Watsi01** [flybywiresim/a32nx#3401]
**Mod Version**
master

**Describe the bug**
FUELPRED page seems to calculate the ETA for destination airport wrong, hence prediction of fuel left is wrong.

**To Reproduce**

1. Make a full flight (at least >1h flighttime)
2. Fill out the MCDU as normal.
3. Climb to crz and wait a while,
4. Compare F-PLN page ETA for destination and FUELPRED page. Also watch estimated fuel going down.

**References**
![fuelpred1](https://user-images.githubusercontent.com/72334392/107155270-d3c72300-6977-11eb-8974-56c070569e65.jpg)

![fuelpred2](https://user-images.githubusercontent.com/72334392/107155275-d9bd0400-6977-11eb-81f1-3fe5a152043e.jpg)

Was this working before/when did the issue start occurring?

Not sure. One or two dev versions before, it worked. 

Discord username (if different from GitHub): RogePete

**Comment by MisterChocker** [comment]
cc @Lucky38i

**Comment by captainjohn73** [comment]
This and the distance counter doesn't work either. They both worked well until a few days ago.

**Comment by Benjozork** [comment]
@captainjohn73 this is fixed since today, it was a bug in dev.

**Comment by Watsi01** [comment]
It also fixed the FUELPRED page. So I'll close this.
