### ISSUE TITLE
[BUG] Add 'STS' text to ECAM

### ISSUE THREAD

**Issue by ErikNL80** [flybywiresim/a32nx#3402]
**Mod Version**

  "built": "2021-02-07T13:04:27+00:00",
  "ref": "master",
  "sha": "c676c434d2d048b74f9793467b750b3d5a251056",
  "actor": "wpine215",
  "event_name": "manual"

**Describe the bug**

Current ECAM page does not include the STS text where the status messages are shown. Found a RL video where you can clearly see it.

**To Reproduce**

1. Start a flight at the runway
2. Check the ECAM
3. Compare it with the one from the screenshot/video.

**Expected behavior**

I would expect the STS text to be on the ECAM page.

**Actual behavior**

STS text is not on the ECAM page.

**References**

https://www.youtube.com/watch?v=cv41hm4JEB8
![ECAM](https://user-images.githubusercontent.com/71258178/107156309-ed6b6900-697d-11eb-84ff-ea017091db49.png)

**Additional context**

This is how it looks in the sim now
![ECAM2](https://user-images.githubusercontent.com/71258178/107156323-fc521b80-697d-11eb-9c44-3cb859d697a6.png)

Was this working before/when did the issue start occurring?
N/A
Is this a problem in the vanilla unmodded game?
N/A

**Comment by ErikNL80** [comment]
Might need some additional references from real world pilots. Just saw another video (https://www.youtube.com/watch?v=FODhSJucbK0) and there the STS is only available when parked/at gate. When in flight or landing this text is not visible...

![ECAM](https://user-images.githubusercontent.com/71258178/107158044-cca81100-6987-11eb-85c8-9f7c56b0d0e1.png)
![ECAMSTSNotVisible](https://user-images.githubusercontent.com/71258178/107158046-ce71d480-6987-11eb-9168-2446f9d0779a.png)

**Comment by lukecologne** [comment]
The status reminder is only shown when there are statuses displayed on the status page on the SD.

**Comment by ErikNL80** [comment]
> The status reminder is only shown when there is a status displayed on the status page on the SD, or there is a maintenance status (in that case it is only displayed on ground)

Thanks for clarifying. Is it already in the A320nx? Could not find it?

**Comment by beheh** [comment]
I don't think so. This will be part of the FWC rework.

**Comment by MisterChocker** [comment]
Closing since requested feature is already implemented

**Comment by MisterChocker** [comment]
For tracking of the issue follow #3503
