### ISSUE TITLE
 TOC icon location is inaccurately shown in arc mode

### ISSUE THREAD

**Issue by nabil74** [flybywiresim/a32nx#341]
**Describe the bug**
TOC (top of climb) icon (blue bent arrow) location is inaccurately shown in arc mode at high magnitudes

**To Reproduce**
Change arc magnification to see the different positioning of icon at high magnitures. At low 320 and160 seems closer to path line but at higher magnitudes 10-80 the arrow is to the right of the path line.

**Expected behavior**
TOC icon should be shown on map  accurately on path at all magnitures

**Screenshots or Videos**
https://youtu.be/IO7SuIUEUFs

image shows arrow off the path line.
![toc tod](https://user-images.githubusercontent.com/70311304/92060657-b1811600-edd7-11ea-98d3-f942d58f9b2a.JPG)

**Comment by MisterChocker** [comment]
using #436 for tracking instead
