### ISSUE TITLE
[BUG] Flightplan loading option from simbrief not available in MCDU 

### ISSUE THREAD

**Issue by gofly22** [flybywiresim/a32nx#3410]
Flightplan loading option from simbrief not available in MCDU 

```
  "built": "2021-02-04T22:08:22+00:00",
  "ref": "master",
  "sha": "1dc3115e0251f810a4de39160688d8ccbd0b1248",
  "actor": "Benjozork",
  "event_name": "manual
```
Option of loading simbrief flightplan not available in Init A page.First of all go to AOC and load fuel / payload but once I goto Init A no option for flightplan upload.I have downloaded from using the A32NX installer dev version.

AOC Load fuel / payload etc
Move across to Iniit A no option to load flightplan

Load flightplan from Init A page

**Actual behavior**
 Iniit A no option to load flightplan

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by MisterChocker** [comment]
You need to link your simbrief account first.
(if I recall correctly)
You can do this by accessing the OPTIONS page on the MCDU then AOC then SIMBRIEF.

Also


> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning

**Comment by gofly22** [comment]
It pulls across the fuel and payload information from simbrief into the MCDU AOC page so I am assuming it is taking across the flightplan info.

**Comment by pareil6** [comment]
Have you selected the destination airport in the game main menu? Doing that will disable the INIT REQUEST option.

**Comment by gofly22** [comment]
pareil6 - That has sorted the issue by not selecting the destination, many thanks

**Comment by joaoatavares** [comment]
Sorry to come to a closed issue but:
What is the  sense of disabling INIT REQUEST option when we select a destination airport on the game menu?

**Comment by pareil6** [comment]
In the real aircraft, INIT REQUEST is hidden once FROM/TO are populated - if you select a destination airport in the main menu, FROM/TO are pre-filled, so it's a side effect of this rather than an intentional decision.

**Comment by joaoatavares** [comment]
Thank you very much
