### ISSUE TITLE
[BUG] version 0.5.0 cockpit doesn't flickering by apu doesn't start

### ISSUE THREAD

**Issue by Peles69x** [flybywiresim/a32nx#3412]
**Mod Version**

**Describe the bug**

with the version 0.5.2 it does't work cockpit flickering by installing
version 0.5.0 cockpit ok by apu doesn't start.

**To Reproduce**

1. cockpit flickering
2. My video card is Nvidia GeForce GTX 1050 Ti
3. version 0.5.0 cockpit ok by apu doesn't start.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
Do you have any other mods in your community folder ?

We also don't support v0.5.0.

**Comment by Peles69x** [comment]
> Do you have any other mods in your community folder ?


Thx for reply,
no, no plane in the folder only a32nx.

**Comment by Peles69x** [comment]
after external power, when pump 1 CTR TK is active, the dispay starts flickering

**Comment by ThatRedMelon** [comment]
Where did you get the sim from and what version is it on?

**Comment by Peles69x** [comment]
[https://drive.google.com/file/d/1Okvgq7ZfzIASpKipB3s9rQR2gEKpR5TL/view?usp=sharing](url)

**Comment by Peles69x** [comment]
the sim is a gift from a friend the version is 1.9.5.0

**Comment by Benjozork** [comment]
We don't support pirated or illegally transferred versions.

**Comment by Peles69x** [comment]
ok regards
