### ISSUE TITLE
[REQUEST] Add support for throttles with detents

### ISSUE THREAD

**Issue by eliasvitali** [flybywiresim/a32nx#3418]
**Is your feature request related to a problem? Please describe.**
It is impossible (for me at least) to line up the axis sensitivity with the proper detents on my TCA airbus throttle quadrant. Of course full throttle will always be TO/GA but currently I can't use the reversers since they share the same axis as the throttle and that's just not an option in MFS to have the reverse throttle on the same axis as the throttle so it makes the really neat feature of the Airbus Throttle Quadrant completely useless.

**Describe the feature you'd like to see implemented**
I would love to see a setting (e.g. on the upcoming EFB) where you can define the axis value which corresponds to the detents. For example since the game can't automatically detect detents let us just manually configure them i.e.:

axis value 1.00 = TO/GA
axis value 0.82 = FLEX
axis value 0.21 = IDLE
axis value <0.21 = Reverse Thrust

I've attached a picture below of how the XP11 Toliss A319 has implemented this feature

![Screenshot 2021-02-08 145317](https://user-images.githubusercontent.com/1341505/107228966-8ef5c780-6a1d-11eb-8d71-6f3629807991.png)

**References**
None -- this is a simulation hardware issue only, there is no IRL counterpart.

**Additional context**
I have not found anything in the menus that will let me do this, but if I missed it then I'm sorry, please point me to it! Obviously not super high urgency, but it would be a really nice feature to have.

Discord username (if different from GitHub): `Bankosphere#9478`

**Comment by Rameyuk** [comment]
Throttles wiuth detents like the TCA Airbus edition is already supported by this mod. You just have to download and install the Experimental Custom FBW version of this mod, which has a throttle configuration ini file that you can use. Refer to the Experimental Custom FBW document page in this Github for the guide on how to set the throttle config.

**Comment by eliasvitali** [comment]
> Throttles with detents like the TCA Airbus edition is already supported by this mod. You just have to download and install the Experimental Custom FBW version of this mod, which has a throttle configuration ini file that you can use. Refer to the Experimental Custom FBW document page in this Github for the guide on how to set the throttle config. All you need is this, and to set all the sensitivity in the sim to 0,0,0 linear neutral. And they should have perfect detents once you configure them properly.
> 
> https://github.com/flybywiresim/a32nx/tree/fbw/docs

Thank you for your help, that's great news! Sometime in the future, when you don't have more important things to worry about I would recommend making it more user-friendly rather than editing a config file, but this is an awesome solution for now. Keep up the great work!

**Comment by parlock** [comment]
A better idea in my mind, is a UI.  That lets you move the throttle to the detent, then click it and record the position for them into the config file.   That would make it easier for non-techie people to set them based on their config/throttle..  It took me some hand tweaking and using the debug console to find mine for the TCA Airbus edition..

**Comment by Rameyuk** [comment]
Maybe integrate this throttle config in the EFB as a slider or something?

**Comment by Sateprikkert** [comment]
> A better idea in my mind, is a UI. That lets you move the throttle to the detent, then click it and record the position for them into the config file. That would make it easier for non-techie people to set them based on their config/throttle.. It took me some hand tweaking and using the debug console to find mine for the TCA Airbus edition..

This would be extremely helpful indeed!

**Comment by parlock** [comment]
Take a look at the new Aerosoft CRJ settings page for the throttle.  This is what I was talking about.  It lets you move the throttle to the position and then click set to record it for each detent...

**Comment by tracernz** [comment]
> 
> 
> Take a look at the new Aerosoft CRJ settings page for the throttle. This is what I was talking about. It lets you move the throttle to the position and then click set to record it for each detent...

There is already an implementation of something similar. Can't remember if it's a PR or just on Discord.
