### ISSUE TITLE
[BUG] Installer possible memory leak following update

### ISSUE THREAD

**Issue by BobbyFuzzy** [flybywiresim/a32nx#3421]
**Mod Version**
Installer 1.0.4

**Describe the bug**
Installer process stays open and continually uses more and more memory. May only be related to updating installer version as I cannot reproduce by opening and closing the installer again.

**To Reproduce**
Update installer from old version to latest.

**Expected behavior**
Installer process to fully close once update is completed and installer closed.

**Actual behavior**
Despite installer window closed, process stays open consuming memory - see below screenshot.

**References**
![image](https://user-images.githubusercontent.com/5226010/107244566-11828500-6a26-11eb-9f11-baf69bac59f2.png)

**Additional context**
I updated the installer today to the latest version, after doing so I updated the experimental version of the mod to latest, closed the installer following both updates as normal. Did not think anything of it until my PC started freezing up. Checked task manager to see the above.

**Was this working before/when did the issue start occurring?**
I have been using the installer since it was released and have not noticed this issue until this latest update. So yes - working fine before this update.

**Is this a problem in the vanilla unmodded game?**
NA

**Discord username (if different from GitHub):**
BobbyFuzzy#4615

**Comment by Benjozork** [comment]
This is already reported, in the installer repository. This repo is strictly for the A32NX addon

https://github.com/flybywiresim/installer/issues/106

**Comment by BobbyFuzzy** [comment]
Apologies - didn't realize there was a separate repo for it. Thanks, will star it for future ref.
