### ISSUE TITLE
[BUG] New Glass reflections are looking too bluish 

### ISSUE THREAD

**Issue by Daboj1337** [flybywiresim/a32nx#3440]
**Mod Version**
Experimental

**Describe the bug**
New Glass Cockpit relfections are too bluish

**To Reproduce**
Start a flight with fbw mod

**Expected behavior**
the reflections must be significantly darker

**Actual behavior**
Too bluish. It looks not realistic

**References**

<img width="1751" alt="Unbenannt" src="https://user-images.githubusercontent.com/76589309/107355933-72669780-6ad0-11eb-8fe0-767b4c7e83db.png">

**Comment by St54Kevin** [comment]
I can surely confirm current reflections implementation is spot on compared to the real displays! No need to change it if we want to stay realistic.
you dont even have your PFD brightness turned fully up

**Comment by ChruutvoLuzi** [comment]
For Reference:
https://user-images.githubusercontent.com/16512508/105945094-70ed9780-6019-11eb-8775-67fca38f3996.png

Spot on, as Kevin mentioned

**Comment by Daboj1337** [comment]
> For Reference:
> https://user-images.githubusercontent.com/16512508/105945094-70ed9780-6019-11eb-8775-67fca38f3996.png
> 
> Spot on, as Kevin mentioned

You can clearly see on the reference picture, that there must be much more contrast on all screens and much more reflections than actually implemented. And yes ive now turn the brightness to max

**Comment by ChruutvoLuzi** [comment]
Currently MSFS does not support adding a reflective material, as soon as the exporter is done this might be possible

**Comment by St54Kevin** [comment]
> > For Reference:
> > https://user-images.githubusercontent.com/16512508/105945094-70ed9780-6019-11eb-8775-67fca38f3996.png
> > Spot on, as Kevin mentioned
> 
> You can clearly see on the reference picture, that there must be much more contrast on all screens and much more reflections than actually implemented. And yes ive now turn the brightness to max

You simply cannot compare a photo to what your eyes see ;) Also that image is taken 1500ft! Sunshine is TOTALLY different at 36000ft

**Comment by MisterChocker** [comment]
Working as intended
