### ISSUE TITLE
[BUG] Need to enter and validate altitude constrants 2 times

### ISSUE THREAD

**Issue by phildeg31** [flybywiresim/a32nx#3444]
Mod Version
"built": "2021-02-09T07:03:20+00:00"
"ref": "fbw"

**Describe the bug**
When modifying altitude constraints in flight plan before take off, I have to enter and validate the constraint 2 times before it was taken into account.

I do not need to enter and validate 2 times with a previous mod version:
"built": "2021-02-04T06:24:14+00:00"
"ref": "fbw"

**To Reproduce**
1. Click to edit the altitude constraint on a waypoint
2. Enter a constraint (ex: 100 for FL100 or 10000) and INSERT -> Nothing is changed
3. Enter this constraint again (ex: 100 for FL100 or 10000) and INSERT -> Constraint is taken into account

**Expected behavior**
I should be able to enter and validate the constraint the first time.

**Actual behavior**
The constraint is taken into account the second time.

**Comment by pareil6** [comment]
I've seen this too - likely also related to #3262, see the discussion in #3407 around flight plan update throttling with the FP version SimVar not updating quickly enough causing delays in updateFightPlan getting called. If I remember correctly, the altitude constraint comes directly from the FPM - so the updateFlightPlan call triggered by entering it being skipped would explain the altitude constraint not appearing on screen refresh, with a second attempt to enter it triggering the update that was skipped. I'll verify the fix in #3407 against this as well.

**Comment by phildeg31** [comment]
Sorry I don't have time to test for now with work and family (children). I will try to test it next week-end.
