### ISSUE TITLE
MCDU Distance/Time to Waypoint Not Working, AP Not Tracking Waypoints

### ISSUE THREAD

**Issue by captainjohn73** [flybywiresim/a32nx#3451]
Hi folks, 

I've been in the experimental version for a few days. Ran great, then all of a sudden the distance stopped counting down in the MCDU, along with the time to waypoints, and the AP isn't following certain waypoints anymore. En-route and on STARS. Direct helps, but only for that waypoint- we need to manually hit dir for every subsequent waypoint until I take manual control of the Aircraft. Haven't tried it in the dev version yet, but this only started recently. CaptainGoldfish#5921 on discord. Thx.

**Comment by Valastiri** [comment]
Does not respect the template.
