### ISSUE TITLE
[REQUEST] NEW WINGVIEWS

### ISSUE THREAD

**Issue by LEDFlighter** [flybywiresim/a32nx#3452]
**Is your feature request related to a problem? Please describe.**
I don't like the standard-wingviews of the A320 NEO...

**Describe the feature you'd like to see implemented**
Better Wingviews so that you can see the full wing with wingtip and the engine

**References**
I have no direct references

**Additional context**
I already have a solution for that, change the last blocks in the "cameras.cfg" to this:

[CAMERADEFINITION.32]
Title ="FixedOnPlane_Porthole01"
Guid ="{3196F576-0B43-46C5-B683-2089682FC7E7}"
Description =""
Origin ="Center"
MomentumEffect =1
SnapPbhAdjust ="Swivel"
SnapPbhReturn =0
PanPbhAdjust ="Swivel"
PanPbhReturn =0
Track ="None"
ShowAxis ="NO"
AllowZoom =1
InitialZoom =0.35
SmoothZoomTime =2
ZoomPanScalar =1
ShowWeather =1
XyzAdjust =1
ShowLensFlare =0
Category ="FixedOnPlane"
SubCategory ="FixedOnPlaneIntern"
SubCategoryItem ="None"
PitchPanRate =20
HeadingPanRate =60
InitialXyz = -1.71, 2, -7.98
InitialPbh = -5, 0, -79
NodesToHide =""
ClipMode ="Normal"
BoundingBoxRadius =0.1
UITitle="TT:GAME.PANEL_CAMERA_FIXEDONPLANE_13"
TargetCategory="None"
CycleHidden=0
CycleHideRadius=0
ShowPanel=0
InstancedBased=0
NoSortTitle=0
Transition=0
PanAcceleratorTime=5
XYZRate=0.25
XYZAcceleratorTime=0

[CAMERADEFINITION.33]
Title ="FixedOnPlane_Porthole02"
Guid ="{880D6889-4223-4A42-917A-AC5CC177C0FC}"
Description =""
Origin ="Center"
MomentumEffect =1
SnapPbhAdjust ="Swivel"
SnapPbhReturn =0
PanPbhAdjust ="Swivel"
PanPbhReturn =0
Track ="None"
ShowAxis ="NO"
AllowZoom =1
InitialZoom =0.35
SmoothZoomTime =2
ZoomPanScalar =1
ShowWeather =1
XyzAdjust =1
ShowLensFlare =0
Category ="FixedOnPlane"
SubCategory ="FixedOnPlaneIntern"
SubCategoryItem ="None"
PitchPanRate =20
HeadingPanRate =60
InitialXyz = 1.74, 2, 0.70
InitialPbh = -4, 0, 101
NodesToHide =""
ClipMode ="Normal"
BoundingBoxRadius =0.1
UITitle="TT:GAME.PANEL_CAMERA_FIXEDONPLANE_14"
TargetCategory="None"
CycleHidden=0
CycleHideRadius=0
ShowPanel=0
InstancedBased=0
NoSortTitle=0
Transition=0
PanAcceleratorTime=5
XYZRate=0.25
XYZAcceleratorTime=0

Then the showcase-cameras 12 & 13 will be better.

Discord username (if different from GitHub): LEDFlighter#7712

**Comment by Rameyuk** [comment]
Can we quickly switch to this view from the cockpit view without opening the camera top menu and switch to showcase?

**Comment by LEDFlighter** [comment]
> 
> 
> Can we quickly switch to this view from the cockpit view without opening the camera top menu and switch to showcase?

No, i don't think so, because it is a showcase-view only... but if you have a shortcut/keybinding for that you can do that of course!

**Comment by Watsi01** [comment]
Funny, I have made wingviews for myself, which are showing _more_ of the ground/landscape and less wing/engine. Wanted so see something, looking out of the windows... :)

**Comment by LEDFlighter** [comment]
> 
> 
> Funny, I have made wingviews for myself, which are showing _more_ of the ground/landscape and less wing/engine. Wanted so see something, looking out of the windows... :)

It's okay, I think it is the best to simply add more showcase-cameras (not only up to 13, so that more variants of such views can be implemented). You can also add your wingviews as 14, 15 etc. (if it works to add the blocks, i don't know much about the structure and the functions of the "cameras.cfg"-file...

**Comment by Watsi01** [comment]
Yeah, I added them (in addition to the default wingviews).

**Comment by LEDFlighter** [comment]
> 
> 
> Yeah, I added them (in addition to the default wingviews).

Okay great! Do you also have added mine?

**Comment by Watsi01** [comment]
Not yet. I'm thinking about adding a jumpseat view.

**Comment by LEDFlighter** [comment]
> 
> 
> Not yet. I'm thinking about adding a jumpseat view.

A jumpseat-view would also be great to have! If you can add it, please add it!

**Comment by hotshotp** [comment]
You can look up how to get custom camera views on youtube. We will probably not add this because it would overwrite the ones that people have set for themselves.
