### ISSUE TITLE
[BUG] ILS/ LOC mode/ APPR mode

### ISSUE THREAD

**Issue by IlanMoshe** [flybywiresim/a32nx#3453]
**Mod Version**
"built": "2021-01-09T06:59:30+00:00",
 "ref": "refs/remotes/upstream/HEAD",

**Describe the bug**

When ATC gives me a radar vectoring to capture the ILS and not to follow the STAR or the transition published, the last clearance should be like:
"AFR200, fly heading 070, cleared ILS RWY 04 L".
So, as a pilot, I set heading 070, and press on LOC or APPR and have to wait to the capture of the ILS.
But, the A320 NX behaves quite differently, indeed after be stable on 070 and pressed on LOC/APPR mode, it seems that it starts to capture the ILS even though it didn't cross the radial.

When you press on LOC, you're arming the LOC but it is not necessary and immediately became engaged. Arm the LOC should not deviate the airbus from 070 until the interception.

**To Reproduce**

1. received the instruction from the ATC to fly HDG 070 to intercept ILS 04
2. set HDG 070
3. Press on LOC 
4. The airbus start to turn before the interception.

**Expected behavior**
The airbus should continue to fly HDG 070 until the interception.

**Actual behavior**
The airbus started to turn before the interception.

**Comment by AbAndyBar** [comment]
Can confirm that, happened me yesterday as well.

**Comment by IlanMoshe** [comment]
> Skiped Loc and press directly Appr mode has worked.
Even press APPR deviate the airbus from the present heading before the interception ...

**Comment by AbAndyBar** [comment]
I have to try that on next flight. First it doesn’t follow the STAR and now this problem. Very annoying, every developer build make it more worst.

**Comment by michaeldinozzo** [comment]
@AbAndyBar this project is in constant development and improves as time goes. Please stop blaming developers for doing all this amazing work for free...

**Comment by MisterChocker** [comment]
Fixed by custom autopilot.

**Comment by AbAndyBar** [comment]
> @AbAndyBar this project is in constant development and improves as time goes. Please stop blaming developers for doing all this amazing work for free...

I’m not blaming anyone. They did an amazing job indeed. But instead of enhancements like EFB and generating new bugs, the existing problems should be solved first.

**Comment by Saschl** [comment]
They are being fixed. It's just other devs working on other parts of the project.

**Comment by IlanMoshe** [comment]
@MisterChocker What do you mean by "This is already fixed" ? We have to wait the next release ?

Thank you for the amazing job already done.

**Comment by MisterChocker** [comment]
> > @AbAndyBar this project is in constant development and improves as time goes. Please stop blaming developers for doing all this amazing work for free...
> 
> I’m not blaming anyone. They did an amazing job indeed. But instead of enhancements like EFB and generating new bugs, the existing problems should be solved first.

Everybody contributing to this project does it in their spare time, you are welcome to join our discord if you fell the need to discuss some things, but github is the wrong place for it.

**Comment by MisterChocker** [comment]
> @MisterChocker What do you mean by "This is already fixed" ? We have to wait the next release ?
> 
> Thank you for the amazing job already done.

What I meant by this, that our work in progress custom autopilot currently has resolved the issue reported.

**Comment by IlanMoshe** [comment]
Okay, thank you @MisterChocker

**Comment by Benjozork** [comment]
> I have to try that on next flight. First it doesn’t follow the STAR and now this problem. Very annoying, every developer build make it more worst.

Do you know what a "developer" build is ?

That's right. It's bound to have problems. If you don't want unexpected issues, you should pick stable.

**Comment by MjrIncident** [comment]
Tis like trying to get your new car off the production line before section 6 and paint spray section ;-)

**Comment by robinottawa** [comment]
Stable has similar problems, and the dev version is often touted as being better than the stable. If I comment about a dev version, it's to try to influence the priorities. If no one in MSFS is flying STARs and arrivals on AP, or having to fight AP to do it, it seems it should be a priority. 

(Maybe it is but I can't tell so I express some frustration. I can't tell because I find navigating the whole discord and github thing way over my head.) I blame MS, of course. It's their product.

**Comment by MisterChocker** [comment]
> Stable has similar problems, and the dev version is often touted as being better than the stable. If I comment about a dev version, it's to try to influence the priorities. If no one in MSFS is flying STARs and arrivals on AP, or having to fight AP to do it, it seems it should be a priority.
> 
> (Maybe it is but I can't tell so I express some frustration. I can't tell because I find navigating the whole discord and github thing way over my head.) I blame MS, of course. It's their product.

As already said before, our wip custom autopilot will fix this. Stay tuned!

**Comment by IlanMoshe** [comment]
Hey @MisterChocker , 
Is it fixed in the v0.5.3 ? :)
Thank you !

**Comment by MisterChocker** [comment]
> Hey @MisterChocker ,
> Is it fixed in the v0.5.3 ? :)
> Thank you !

No, our 0.5.3 release only contains compatibility updates and small fixes/improvements.
