### ISSUE TITLE
[BUG] Fuel for alt arrival airport often shows a negative valuse after some time.

### ISSUE THREAD

**Issue by GlitchedYT** [flybywiresim/a32nx#3464]
**Mod Version**
 Custom AP, but is also present in dev build i believe

**Describe the bug**

EFOB for alt arrival shows a negative value after not visiting the FUEL PRED page for a while

**To Reproduce**

1. Start any flight that includes an alt arrival airport (preferably one made through simbrief)
2. After setting up the flight and taking off wait around 30-45 mins and go to the FUEL PRED page 
3. Observe how the alt airrival airport first shows a negative or wrong value then updates after a few seconds.

**Expected behavior**

EFOB for alt arrival airport should be upto date and accurate without having to open the FUEL PRED page

**Actual behavior**

EFOB for alt arrival airport is incorrect and sometimes negative

**References**

https://streamable.com/idc0b0

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game? I dont think vanilla has the fuel pred page

Discord username (if different from GitHub): Glitched

**Comment by erso44** [comment]
your references are not working.

**Comment by erso44** [comment]
![image](https://user-images.githubusercontent.com/39134287/122035277-9ade0580-cdd2-11eb-8a02-3c2103bf4e92.png)

**Comment by erso44** [comment]
fixed.

**Comment by erso44** [comment]
From reference (private messages with pilots) ALT DST EFOB below 0.8 will be displayed amber.
800 KG of fuel is the min amount of fuel which is needed for alternating.

It is still not clear what will be displayed at or below 0.0.

One pilot said that a negative figure will be displayed when EFOB is below zero.
Two pilots said they are not sure.

a320dp.com (http://www.a320dp.com/A320_DP/nav-flight-management/sys-14.10.1.html) says when extra fuel is negativ dashes will be displayed. For consistency on FUELDPRED side I have decide to display ambered dashes when ALT DST EFOB is at/below zero.

I did not find any documentation about the honeywell pegasus 2.
Thales also does not include informations.
We can later change this behaviour if we get more detailed references.
Also keep in mind that this situation could be very rare.

I can imagine that this case could be documentet in the emergency handling procedures (for example when in mid-flight fuel is leaking) but I do not think that we will get access.

This is the current solution:
![image](https://user-images.githubusercontent.com/39134287/122646023-89239780-d11d-11eb-9c40-dd7a858a79cd.png)
![image](https://user-images.githubusercontent.com/39134287/122646038-95a7f000-d11d-11eb-8a5b-9f8a4152eb3b.png)
