### ISSUE TITLE
[BUG] Knobs and screens disappearing in long flight

### ISSUE THREAD

**Issue by mico975** [flybywiresim/a32nx#3468]
**Mod Version**
Custom FBW from installer (b95c71e)

**Describe the bug**
Knobs and screens disappear after 3-4 hours of flight.

**To Reproduce**
1. Go on to long flight.
2. Wait.
3. After 3-4 hours the displays/knobs are not visible anymore.

**Expected behavior**
Knobs should be visible.

**Actual behavior**
Knobs and screens disappear after 3-4 hours of long flight. 

**References**
![149263505_164171052178507_269700481414745013_n](https://user-images.githubusercontent.com/78908672/107633726-c86e4300-6c68-11eb-88bd-8dc70f58b6d6.png)

![149327116_504396790959099_1782747964586442149_n](https://user-images.githubusercontent.com/78908672/107630749-4aa83880-6c64-11eb-8d00-c67f12ffe854.png)

**Additional context**
Maybe the issue is in the vanilla code since PFDs, which are desynced in mod, work normally

Was this working before/when did the issue start occurring?
Probably not applicable but I think it has happened in most of my "long haul" flights (4h+) with A32NX.

Is this a problem in the vanilla unmodded game?
Do not know actually.

**Comment by hotshotp** [comment]
this is a vanilla issue where the plane takes a few moments to load. this goes away after waiting for a while

**Comment by mico975** [comment]
Didn't came back for two hours today. As long as Asobo knows about that it's probably good and I'm hoping they fix it. You are certainly not here to fix this kind of vanilla issues. :)

**Comment by LeifSbr** [comment]
this just happened to me too. also got a fright when there was suddenly pilot & copilot in the seats (cockpit is normally empty). this is the experimental version.
![2021-04-12 16_57_28-Greenshot](https://user-images.githubusercontent.com/28689427/114416000-8140f780-9bb0-11eb-8e58-503a09c71b40.jpg)

**Comment by Benjozork** [comment]
As stated above this is an MSFS issue and there's nothing we can do about it.
