### ISSUE TITLE
[BUG] APU,FMC & Light Bugs

### ISSUE THREAD

**Issue by doudi19** [flybywiresim/a32nx#3470]
**Mod Version**

**Describe the bug**

**To Reproduce**

1.Just load into the sim normally and u won't be able any of the bugs stated above.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by armankir** [comment]
Can you clarify a bit or give more context?

**Comment by Benjozork** [comment]
Does not follow template.
