### ISSUE TITLE
[BUG] INSERT TITLE HERE

### ISSUE THREAD

**Issue by WUBingfeng1984** [flybywiresim/a32nx#3475]
<！-⚠⚠不要刪除此問題模板！ ⚠⚠->
<！-不使用問題模板的問題很可能會被忽略並關閉。 ->

** Mod版本**
<！-是最新版本的master分支的發行版或“ master”。 ->
<！-如果您使用的是A32NX-master.zip或安裝程序中的Dev版本，請在此處將build_info.json中的內容粘貼->

**描述錯誤**
<！-關於錯誤的清楚簡潔的描述。 ->

**重現**
<！-重現行為的步驟。 ->
<！-我們需要知道您是如何遇到該錯誤的，以便正確地解決此問題。 ->
1。
2。
3。

**預期行為**
<！-對您期望發生的事情的簡潔明了的描述。 ->

**實際行為**
<！-清晰簡潔地描述實際發生的情況。 ->

**參考**
<！-如果適用，請添加屏幕截圖或視頻以幫助解釋您的問題。 ->

**其他內容**
<！-在此處添加有關該問題的任何其他上下文。 ->

在問題開始之前/何時開始，這是否可行？

在未經修改的原始遊戲中這是問題嗎？

<！-您可以選擇提供不和諧的用戶名，以便我們可以就此問題直接與您聯繫。 ->
Discord用戶名（如果與GitHub不同）：

**通過刪除此行，我認為我已經遵循了發布模板並提供了標題，並蒐索了其他可能重複的問題。我確認如果未刪除此行和/或未遵循問題模板，則將在沒有警告的情況下關閉我的問題**

**Comment by pepperoni505** [comment]
Please follow the template, and use English

**Comment by davidwalschots** [comment]
你寫的沒有問題。應為你寫中文我們不能幫你。請下一個問題用英文。
