### ISSUE TITLE
[BUG] Radios off and EFB just flickering white

### ISSUE THREAD

**Issue by foxmike80** [flybywiresim/a32nx#3476]
**Mod Version**
{
  "built": "2021-02-11T19:13:57+00:00",
  "ref": "master",
  "sha": "bab7ef7382340a154c2e407ebd68ce4b26d526a4",
  "actor": "tyler58546",
  "event_name": "manual"
}

**Describe the bug**
Radios do not show a frequency - displays are blank and the EFB is just white and flickering wildly.

**To Reproduce**
1. Load flight with A32NX
2. Observe the EFB flickering white with all batteries and ground power still off
3. Start Battery and Ground Power
4. Observe that all Displays are on but the radios remain off

**Expected behavior**
EFB and radios should show work.

**Actual behavior**
see above

**References**
<img width="1049" alt="Screenshot 2021-02-11 223530" src="https://user-images.githubusercontent.com/76132268/107701657-7c97ba00-6cb9-11eb-991a-cee6db6e0de8.png">

**Additional context**
Might be an interference with other addons. I was using the new Trinidad 21 and WT CJ4. But I have removed both addons and restarted to sim with no effect.

Was this working before/when did the issue start occurring?
Just today.

Is this a problem in the vanilla unmodded game?
I do not know.

Discord username (if different from GitHub):

**Comment by Gian85** [comment]
is a livery problem

**Comment by foxmike80** [comment]
Will check - don't think I'm using any liveries.

**Comment by Gian85** [comment]
this happened to me for this problem.

**Comment by foxmike80** [comment]
I tried FBW livery and I do not have any liveries installed in the community folder. Still no luck.

**Comment by Gian85** [comment]
try to reinstall the mod

**Comment by MisterChocker** [comment]
@foxmike80 Do you have any other mods installed?

**Comment by foxmike80** [comment]
I'm in the process of troubleshooting. Just emptied my community folder, deleted cache and restarted the pc. I will report any findings...

**Comment by foxmike80** [comment]
I think I can narrow it down to YourControls - which is weird as the first time the problem occurred was when a friend and I were trying to fly online earlier tonight. We always make sure to use the same version of the airbus (latest) and YourControls (2.4.1) and my friend didn't have the problem. We only noticed the issue when I switched on batteries and external power and his radios came to life when mine didn't. I just completely re-installed YourControls and will report back if it works again.

**Comment by foxmike80** [comment]
Alright, after re-installing everything it must have been something with YourControls. However, after a clean re-install of YourControls everything seems to be be back to normal. I haven't had the chance to try connecting YourControls to a buddy yet.
