### ISSUE TITLE
[BUG] Adirs do not align at CYYC airport

### ISSUE THREAD

**Issue by jer2929** [flybywiresim/a32nx#3490]
**Mod Version**

"built": "2021-02-12T06:54:37+00:00",
  "ref": "fbw",
  "sha": "2d2a45e7e53fb7d57c7c2394480bac5f690a8e4a",
  "actor": "aguther",
  "event_name": "manual"

**Describe the bug**

The ADIRS simply do not align anywhere at CYYC airport. Tried various gates. Simply says NAV TCAS STBY on the ECAM. 

**To Reproduce**

1. Load in C&D at a gate
2. Battery on -->external on--> Adirs to NAV
3. ADIRS never align

**Expected behavior**

Adirs should have aligned.

**Actual behavior**

 They did not

**References**

**Additional context**

Was this working before/when did the issue start occurring?
-First time loading into CYYC with the A32NX mod. 

Is this a problem in the vanilla unmodded game?
Dont think so. I dont think any of the default aircraft have adirs alignment.

Discord username (if different from GitHub):

Jer2929(PunchDkns99)

**Comment by pepperoni505** [comment]
BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning

**Comment by tshomas** [comment]
Sent Jer from #help.  Discord: Shomas

Through my testing at Calgary CYYC with three stand positions can replicate issue. No addon scenery in use.

The amber ECAM warning of NAV TCAS STBY is appearing immediately on aircraft power on and hides the timer underneath. Tested with the ADIRS starting their alignment and without touching any switches at all, same TCAS STBY appears straight away after DU self test.

Using CLR on the ECAM removes the fault, returning the EWD DU to the IRS memo of alignment time. RCL brings back the amber TCAS STBY ECAM even during alignment.

Moved to other airports and cannot replicate, ECAM warning does not appear at all.

Possibility of the air ground logic associated with the TCAS STBY warning has an issue?

**Comment by tshomas** [comment]
Aircraft aligns fine and operates normally, except for the TCAS STBY warning remains. Turning the TCAS to TA/RA removes the warning, but immediately returns when it is switched back to STBY, even on the ground.

**Comment by pepperoni505** [comment]
> Through my testing at Calgary CYYC with three stand positions can replicate issue. No addon scenery in use.
Which stands?

**Comment by tshomas** [comment]
103 was one of them, let me get you a couple more.

**Comment by pepperoni505** [comment]
> 103 was one of them, let me get you a couple more.

Just tested at one of the stands with commit 32f0fbe8, I had the same issue as you. I tried again with master and it seemed to work for me. Can you double check on the latest master?

**Comment by tshomas** [comment]
Yeah sorry I should have said I was on experimental for testing that, am switching to Dev 32f0fbe to see as well

**Comment by pepperoni505** [comment]
You should use the latest dev version, 32f0fbe had its own issues.

**Comment by beheh** [comment]
I'll fix this, it's an ECAM thing were the warning appears at the wrong time.
