### ISSUE TITLE
[BUG] After setting Thrust to TOGA with Airbus Quadrant, right thrust lever is ignored

### ISSUE THREAD

**Issue by mleimer** [flybywiresim/a32nx#3491]
**Mod Version**

Development bab7ef7

**Describe the bug**

After having set Thrust to TOGA with the Airbus Quadrant, the inputs of the right thrust levers are ignored.

**To Reproduce**

1. Start from any airport with the A32NX
2. Put both thrust levers to TOGA
3. Right thrust lever setting is ignored thereinafter

**Expected behavior**

- Thrust levers setting is represented correctly with the green dot on the screen.
- Thrust follows green dot represented on the screen. 
- Actual thrust is set according to right thrust lever setting beyond TOGA
- TOGA message should probably be removed from screen, too - However, as I am not an A320 pilot, this is just an assumption.

**Actual behavior**

- Thrust levers setting is represented correctly with the green dot on the screen.
- Right thrust does NOT follow green dot represented on the screen. 
- Actual thrust is in sync to actual thrust of left engine
- TOGA message keeps being displayed beyond TOGA

**References**

![image](https://user-images.githubusercontent.com/14271564/107800290-e5853d80-6d5e-11eb-808b-e215dc65831d.png)

**Additional context**

Was this working before/when did the issue start occurring?
It never worked

Is this a problem in the vanilla unmodded game?
I haven't tried that out yet.

**Comment by aguther** [comment]
I did a test some time ago, and it seems it's related to the default ATHR system and it's not happening only with TOGA. Whenever the ATHR system is enabled it seems to happen.

Solution will be the upcoming custom ATHR system.

**Comment by aguther** [comment]
Have you tested with the new experimental version? Should be fixed in it.

**Comment by mleimer** [comment]
Thanks a lot. I can confirm that it got fixed in the latest release.
