### ISSUE TITLE
[BUG] Unable to use EFB when in VR

### ISSUE THREAD

**Issue by RichieDee** [flybywiresim/a32nx#3493]
**Mod Version**
master branch (7e585da)

**Describe the bug**
The virtual finger (mouse pointer) does not touch the surface of the efb (as it does for any other switch/knob within the cockpit) but hovers a couple of cm above it.
It's difficult (near impossible) to select anything on the efb. :-(

**To Reproduce**
1. Enter VR
2. Prod the efb screen with virtual digit... (to power it on)
3. Try to select anything!

**Expected behavior**
VR mouse pointer should be close enough to the efb so that you can make selections.

**Actual behavior**
VR mouse pointer hovers some distance away from the efb making it impossible to select items.

**References**
Not applicable.

**Additional context**
-

Was this working before/when did the issue start occurring?
Has always been an issue since introduction of efb.

Is this a problem in the vanilla unmodded game?
only a32nx 

Discord username (if different from GitHub):

**Comment by Tokolosh** [comment]
I agree with the claims made. It would be nice to be able to use the efb in VR but in its current state this is not possible.

**Comment by 2hwk** [comment]
https://docs.flightsimulator.com/html/index.htm?rhsearch=Keyboard%20Events&rhhlterm=events%20event#rhsearch=Keyboard%20Events&t=Asset_Creation%2F3D_Models%2FAircraft%2FAircraft_Cockpit.htm&rhhlterm=aircraft

Relevant SDK page (?)

**Comment by ErickSharp** [comment]
I have heard that this has recently been fixed, is this the case? I will be closing this issue in a couple of days if I don't hear back from anyone that continues to have issues with this.

**Comment by mduft** [comment]
I have tested the FlyPad in VR recently on experimental and it works fine now, yes, you can close this.
