### ISSUE TITLE
[BUG] FOB information is reset when Refuel *LOAD pressed in MCDU mid-flight

### ISSUE THREAD

**Issue by LaTtEX** [flybywiresim/a32nx#3502]
**Mod Version**
Latest stable v0.5.2

**Describe the bug**
While in mid flight, pressing on the Refuel *LOAD button resets the FOB value of the aircraft.

I was performing a flight from RPLL -> RJAA and was navigating through my MCDU when I inadvertently pressed the Refuel *LOAD button. While I had already spent a significant amount of fuel at this point, FOB was reset to what it was at the beginning of my flight (27333 lbs). 

This Block Fuel value was taken from Simbrief, which I had loaded into the MCDU.

**To Reproduce**
1. Load a Simbrief flight plan to the MCDU
2. Take off and fly to your CRZ altitude or any point where there's a significant amount of fuel burn already
3. Press MCDU MENU -> ATSU -> AOC MENU -> PEFR/W&B screen
4. Press the button beside Refuel *LOAD

**Expected behavior**
FOB will reflect actual remaining fuel on board

**Actual behavior**
FOB resets to Block Fuel value set in Simbrief

**References**
ECAM lower display shows the fuel spent at 10830 lbs, but FOB value here and at the Upper ECAM display shows 25480 lbs, after about 10 minutes flight time since pressing the Refuel *LOAD button:
![FOBBug](https://user-images.githubusercontent.com/390216/107848714-a4f5f480-6e30-11eb-9b68-303e484275ed.png)

**Additional context**
The Block Fuel value comes from Simbrief.

**Comment by erso44** [comment]
investigating issue.

**Comment by erso44** [comment]
The idea would be to deactivate the *LOAD button depending on aircraft speed.
The *LOAD Button is only used when an aircraft is on ground.

Button should be clickable when aircraft speed is at speed zero.
Button should be not clickable when aircraft speed is above zero.

**Comment by erso44** [comment]
Idea: Ground control is only used when aircraft is at gate and this is the only case where an aircraft can be fueled. In all other cases like taxiing, flying etc ground control is off and in all this cases an aircraft can not be fueled.

Implementation works for:
*LOAD button is clickable when ground control is on.
*LOAD button is not clickable when ground control is off.

Tested.
