### ISSUE TITLE
[BUG] Upper ECAM STS is too small

### ISSUE THREAD

**Issue by Kimbyeoungjang** [flybywiresim/a32nx#3503]
**Mod Version**

current master

**Describe the bug**

![image](https://user-images.githubusercontent.com/23118756/107852729-b998b380-6e55-11eb-8f46-1643a943c43b.png)
STS is too small

**To Reproduce**

1. fly
2. shutdown engine 1 or 2
3. watch ecam

**Expected behavior**

STS is normal

**Actual behavior**

STS is small

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by hotshotp** [comment]
this will be fixed with the rewrite of the displays
