### ISSUE TITLE
[BUG] Autoland V/S Bug

### ISSUE THREAD

**Issue by xRaynex** [flybywiresim/a32nx#3507]
**Mod Version**
Autoflight Channel Master
{
  "built": "2021-02-13T10:08:15+00:00",
  "ref": "autopilot",
  "sha": "3a2532188ff05ab38ad8c150d80acdc05c24b42b",
  "actor": "aguther",
  "event_name": "manual"
}

**Describe the bug**
On a CATIII Dual approach, attempting to autoland, maybe 300ft above runway (or less), the approach will break and the plane will suddenly activate a neutral or positive V/S rate. The primary display will have LAND overlayed with the V/S texture, so they're both visible.

**To Reproduce**
1. Prepare an ILS Approach for autolanding
2. Allow the FMS to do its thing
3. At a point not far above the runway, the plane will deviate from the approach by changing over to V/S.

**Expected behavior**
Expected behavior is for the plane to land properly, without issue.

**Actual behavior**
The plane deviates from the approach and either maintains level flight just above the runway, or begins to ascend.

**References**
N/A --- Will make a recording and provide it.

**Additional context**
Appears to happen at any airport I attempt to CATIII Dual land at.

Was this working before/when did the issue start occurring?
Not for me, no. However watching videos shows it to be working fine for others.

Is this a problem in the vanilla unmodded game?
Is not an issue pertinent to the vanilla game.

Discord username (if different from GitHub): Lawliet#4568

**Comment by xRaynex** [comment]
Oh the irony. I go to take a video, it works perfectly. So I have no idea what it could be.

**Comment by GlitchedYT** [comment]
I can confirm i've had this issue as well at KJFK when spawning from the runway, taking off, programmed the MCDU for ILS landing on RWY 13L, at about 300ft the plane changed to v/s and leveled off. Forgot to report it a few days ago my bad.

**Comment by xRaynex** [comment]
The only difference I can think of between this one working and the ones normally not is I ordinarily didn't know to hit the check button for the cabin. Thought it would automatically clear. Is it possible that not having completed the landing checklist could've done it? Dunno if you've got the same problem, GlitchedYT.

**Comment by aguther** [comment]
I think it's a bit exaggerated to say it happens always, I do a lot of landings in my testing and did not have it a long time.

In the current implementation, the only way to get out of LAND mode is a radio altitude > 400 ft. I suspect that this might happen shortly on certain approaches and of course needs to be fixed (latching LAND mode).

**Comment by aguther** [comment]
Bugfix is pushed:
https://github.com/flybywiresim/a32nx/commit/d129ad23c7e52008ea1148289af0ef6783b1dd69
