### ISSUE TITLE
[BUG] LVR MCT displayed in cold and dark start (dev 0.1.1) 

### ISSUE THREAD

**Issue by nobodyn0se** [flybywiresim/a32nx#351]
**Describe the bug**
LVR MCT is displayed on the FMA when starting from a cold and dark state. While waiting for the IRS to align, this message can be seen. It then changes to LVL CLB while taxiing as noted in issue #272 

**To Reproduce**
Start from cold and dark state, shortly after the PFD is alive, this message can be seen until engine startup / taxi phase.  

**Expected behavior**
LVR MCT shows up only when the thrust lever is supposed to be in MCT detent (but is not) or when green dot speed is relevant, during takeoff/missed approach profile. It should not be seen during startup or taxi. 

**Screenshots or Videos**
![Screenshot (690)](https://user-images.githubusercontent.com/48710616/92101300-8eb42900-edfa-11ea-9435-e375031d5dcc.png)

**Additional context**
Latest dev-0.1.1 branch. I do not have the FCOM handy right now, but here are some references : 
http://www.a320dp.com/A320_DP/nav-autoflight/sys-13.3.14.html
http://www.smartcockpit.com/docs/A320-Powerplant.pdf [Page 13 ref]

**Comment by Benjozork** [comment]
Please respect the issue templates and provide expected behaviour - what should we be seeing in this case and where can we verify that's the correct behaviour ?

**Comment by nobodyn0se** [comment]
Edited with correct template.

**Comment by Benjozork** [comment]
Thank you :) will try to look into it.

**Comment by Benjozork** [comment]
@nobodyn0se will work on this after #330 is merged because this modifies the same file.

**Comment by Benjozork** [comment]
@nobodyn0se, can you test this on 0.2.0 ? Cannot reproduce it.

**Comment by Benjozork** [comment]
Reproduced.

Looks like it thinks the aircraft is in takeoff.

![image](https://user-images.githubusercontent.com/4503241/92292409-1aa57e00-eeeb-11ea-959c-1185d1d5d785.png)

**Comment by Benjozork** [comment]
@nobodyn0se according to an IRL 320 pilot, this message is only displayed in single-engine operations.

See, in your reference here, where "EO" means "Engine Out" :

http://www.a320dp.com/A320_DP/nav-autoflight/sys-13.3.14.html

I will think about whether or not we can fix this, and will keep updating you.

**Comment by nobodyn0se** [comment]
Sure, thank you :)

**Comment by nobodyn0se** [comment]
Fixed by #399
