### ISSUE TITLE
[Fehler] Co-pilot displays and tablet glow white

### ISSUE THREAD

**Issue by Andi-ger** [flybywiresim/a32nx#3510]
**Mod Version**

dev_7da6cf1 and stable 0.5.2 (without Tablet)

**Describe the bug**

I have the problem that the CO pilots displays and the tablet only lights white

**To Reproduce**

1. start the game normally
2.
3.

**Expected behavior**

The displays are the same as for the pilot

**Actual behavior**

The displays light up white

**References**

**Additional context**

I have already uninstalled and reinstalled the whole game only the a32nx mod is in use

Was this working before/when did the issue start occurring?

I have this behavior since version v0.5.0

Is this a problem in the vanilla unmodded game?

The problem does not occur in the unmodded game

Discord username (if different from GitHub):

Pictures:

![cockpit_1](https://user-images.githubusercontent.com/78974049/107858476-94e01400-6e34-11eb-9b27-8b4bd3882bd5.jpg)
![cockpit_2](https://user-images.githubusercontent.com/78974049/107858480-9d384f00-6e34-11eb-97ab-7d7755085b3e.jpg)

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
This is 99% likely due to a mod conflict. Please remove everything from your community folder except A32NX and try again.

**Comment by Andi-ger** [comment]
after the reinstallation i have reinstalled the a320nx mod via the installation.
Since I do not use other mods my community folder is only provided with a32nx mod

**Comment by Andi-ger** [comment]
after the reinstallation i have reinstalled the a320nx mod via the installation.
Since I do not use other mods my community folder is only provided with a32nx mod

**Comment by Benjozork** [comment]
Do you have any liveries ?

**Comment by Andi-ger** [comment]
Thank you very much for your help,

I used the test pilot (Microsoft beta user) paint. after I am on the standard now everything goes. Thanks for the quick help.

**Comment by Benjozork** [comment]
Yeah, this livery is not compatible due to how MSFS Liveries work.
