### ISSUE TITLE
[BUG] QNH not flashing when passing transition altitude

### ISSUE THREAD

**Issue by wokadoka** [flybywiresim/a32nx#3534]
**Mod Version**

Stable v0.5.2

**Describe the bug**

QNH not flashing when passing transition altitude

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Kimbyeoungjang** [comment]
Duplicated #3293 

I fix that on #3342

**Comment by hotshotp** [comment]
duplicate #3293
