### ISSUE TITLE
[BUG] Squawk number keep changing when flying on Vatsim 

### ISSUE THREAD

**Issue by regisbiass** [flybywiresim/a32nx#3537]
Squawk number keep changing when flying on Vatsim 

**Mod Version**

All versions -  stable and latest development

**Describe the bug**

Squawk number keep changing when flying on Vatsim 

**To Reproduce**

1.  Go to Vatsim fly
2.
3.

**Expected behavior**

**Actual behavior**

Squawk keep changing

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by CoffeePanda0** [comment]
Do you have AI control ATC on?

**Comment by regisbiass** [comment]
Hi Alex,

Where is the AI control ATC !? in MSFS2020.

I am.flying on vatsim. I will check shortly.

Thanks,
Rehis

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by regisbiass** [comment]
Hi Alex,
I had it turned ON. I have disabled it. Gona try a flight now and report back.




Best Regards,

Regis Biassala

Tel: 00353864052190

________________________________

**Comment by theomessin** [comment]
> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning

Feel free to open a new issue **provided you follow the given instructions**.
