### ISSUE TITLE
[BUG] ND flight plan line doesn't show up on past waypoints

### ISSUE THREAD

**Issue by mythicfci** [flybywiresim/a32nx#354]
**Describe the bug**
The ND flight plan line doesn't show up on past waypoints, only on future waypoints.

**To Reproduce**
1. Load (or set in the MCDU) a flight plan, then take off & climb to cruise.
2. Switch the ND to NAV and switch the view range to anything above 10nm

**Expected behavior**
The ND flight plan line should extend to past waypoints as well as future ones. However, it doesn't - only the waypoints are shown.

**Screenshots or Videos**
See attached screenshot.

**Additional context**
I'm running the latest dev build on MSFS v1.7.14.0 (i.e. the latest patch).
![a320 line](https://user-images.githubusercontent.com/49729038/92121097-78bf5c00-ee2c-11ea-87f4-e9604a743ee6.png)

**Comment by 2hwk** [comment]
This appears to have been fixed at some point, 
![image](https://user-images.githubusercontent.com/15316958/101972835-eff85d80-3c6f-11eb-84b5-dc227e2144e3.png)
Closing
