### ISSUE TITLE
[BUG] AUTO BRK MAX doesn't slow down the aircraft

### ISSUE THREAD

**Issue by GlitchedYT** [flybywiresim/a32nx#3546]
**Mod Version**
 Custom AP 2/15/21

**Describe the bug**

AUTO BRK MAX doesn't slow the plane down at all on a rejected T/O

**To Reproduce**

1. Perform a rejected T/O with AUTO BRK MAX armed
2.
3.

**Expected behavior**

Plane should decel very quickly and decel should be shown below the speed tape on the PFD

**Actual behavior**

Plane barely decelerates (1 knots per second)

**References**

https://streamable.com/dyqulu

**Additional context**

Was this working before/when did the issue start occurring? Not sure, doesn't work on any build currently

Is this a problem in the vanilla unmodded game? Not sure

Discord username (if different from GitHub):

**Comment by donstim** [comment]
I checked this with the current developer version, not the custom autopilot. Here is what I found:  I started on the runway, not C&D. If I immediately did an RTO like you did, the autobrakes did not activate. However, if I first clicked the Max Autobrake setting off, then back on, it worked fine.  It appears to be an initialization issue, at least with starting on the runway. The indicator and the PFD will show that it has been selected, but it has not been initialized properly.

**Comment by Asianblade** [comment]
The reason that explains: Spoilers MUST DEPLOY when rejected T/O, or else nothing will happen. It's mentioned before.

**Comment by donstim** [comment]
Spoiler deployment is automatic.

**Comment by Aseinsha** [comment]
I believe this is the same as https://github.com/flybywiresim/a32nx/issues/3042#issue-786037056 ?

**Comment by donstim** [comment]
> I believe this is the same as [#3042 (comment)](https://github.com/flybywiresim/a32nx/issues/3042#issue-786037056) ?

Good catch! @GlitchedYT If you agree, can you close this and add your report to that issue?

**Comment by aguther** [comment]
See #4771
