### ISSUE TITLE
Blitzer funktionieren nicht richtig

### ISSUE THREAD

**Issue by hundkessi** [flybywiresim/a32nx#3551]
**Mod Version**

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by hundkessi** [comment]
Der weiße Blitzer an den Flügelenden stimmt nicht. Er blitzt immer gleichmäßig. Airbus hat aber bei allen seinen Flugzeugen einen Doppelblitz.

**Comment by Alex1337Cool** [comment]
@hundkessi ich glaube du solltest das ganze auf Englisch schreiben, weil die glaube ich kein Deutsch sprechen. :)

**Comment by Watsi01** [comment]
Einige schon. Aber so langer das Issue Template nicht einhält, wird er halt wieder geschlossen.

**Comment by marcman86** [comment]
Bitte  Issue Template einhalten.

Das Problem ist bekannt.

**Comment by lukecologne** [comment]
> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning

Bitte die Vorlage einhalten, und issues auf englisch verfassen, damit es auch alle verstehen können. Das Problem ist bekannt, eigentlich sollten die strobes an den Flügeln auch im Mod double strobes sein. Versuch mal, den Strobe switch aus und wieder ein zu schalten.
