### ISSUE TITLE
Scheibenwischer funktionieren nicht richtig

### ISSUE THREAD

**Issue by hundkessi** [flybywiresim/a32nx#3553]
**Mod Version**

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by hundkessi** [comment]
Die Scheibenwischen laufen zwar, aber sie wischen nicht. Die Regentopfen bleiben erhalten.

**Comment by ChruutvoLuzi** [comment]
Zwei Sachen:

1. Du solltest unbedingt die Bug Vorlage benutzen und richtig ausfüllen, da sonst die Devs dir das Ticket ohne Vorwarnung schliessen können

2. Das mit den Regentropfen ist ein Problem des Sims selber, ich bezweifle dass FBW im moment etqas tun kann, evtl wenn der Exporter fertig ist

**Comment by Valastiri** [comment]
As stated by @ChruutvoLuzi. 

Does not follow the template.
