### ISSUE TITLE
[BUG] ND showing flying off course

### ISSUE THREAD

**Issue by ukflyer** [flybywiresim/a32nx#356]
**Describe the bug**
The ND shows me flying off course and not following programmed route, this was after hitting direct to button
Latest dev files, possibly Asobo bug that can't be fixed here :)

**Expected behavior**
Expect it to follow green line

**Screenshots or Videos**
![offtrack](https://user-images.githubusercontent.com/70434502/92144395-8f56ba80-ee0e-11ea-8546-eaff20e4cf8e.PNG)

**Comment by NathanInnes** [comment]
https://prnt.sc/ubo0m0

Just a test, can you confirm this is off or on?

**Comment by ukflyer** [comment]
i have that setting to on

**Comment by NathanInnes** [comment]
If you turn it off do you have the same issue?

**Comment by ukflyer** [comment]
can't seem to recreate this Nathan i'll close it off for now. thanks
