### ISSUE TITLE
Custom FBW: Colour improvments possible?

### ISSUE THREAD

**Issue by Mickepilot** [flybywiresim/a32nx#3567]
**Custom FBW 9e6857d**

**1) Instrument panel and pedestal panel has two different shades of "Airbus blue" colour
   2) Display panels has little bit too much "milky" haze surface
   3) White index mark, on the side of the throttle handle, is missing again
   4) Most gray switches has an unatural look, like made of almost clear plastik, for ex:
top of some switches looks "bright" gray, and bottom of same switches has too much shadow (darkness)**

**Comment by Benjozork** [comment]
Does not follow issue template
