### ISSUE TITLE
[BUG] when taking off the engine power starts going up and down

### ISSUE THREAD

**Issue by Mrsmith4135** [flybywiresim/a32nx#3580]
**Mod Version**
Development version 38607b7

**Describe the bug**
When putting the throttle to max upon take off it will start putting the throttle up and down. If you look on the centre instrument you can see the engine going from red to green

**To Reproduce**
spawn at any international airport at any runway. set the throttle to max for take-off then the throttle will start going up and down and if you look at the ecam instrument where engine pressure etc. is you will see the engine pressure going green to red after take off. it will continue to do this for the flight. you can hear the engine power cut and then increase and reduce again

**Expected behavior**
it should just be full throttle and then the power should be smooth and the engine pressure should not be going into the red

**Actual behavior**
after putting to full power and taking off the engine power started going up and down
![Capture](https://user-images.githubusercontent.com/79224644/108262618-0eda0b00-715d-11eb-98a0-fd34ad7049b6.PNG)

Was this working before/when did the issue start occurring?
It was working before world update 3

discord username: Louis cammy

**Comment by Benjozork** [comment]
Please provide the contents of the build info file as required by the template.

**Comment by Mrsmith4135** [comment]
I have a video of what is happening but cant send it because it is 16mb and i cant compress it anymore.
Do you have a discord I could send it into?

**Comment by Mrsmith4135** [comment]
I'm going to close this because i have found the issue. I just removed mods that might have been interfering. but I did also delete the cache so that might have been the issue
