### ISSUE TITLE
[BUG]flight model

### ISSUE THREAD

**Issue by A320pilotIRL** [flybywiresim/a32nx#359]
Ground friction is WAY too high. The real jet will easily and fairly quickly accelerate to 40lts with just idle thrust on both engines. Should never need to add breakaway thrust to get moving with both running. Airplane should never stop on it’s own when taxiing on flat surface. Idle thrust is sufficient. In the sim you need a lot of thrust to get going and a lot of thrust to keep going. The real plane, you ride the brakes the whole time because idle thrust is so much. Even on 1 engine, at times. 

Flight model flies at a much higher AOA and pitch angle than the real plane. Definitely needs a fix. On an ILS at Vapp with no wind the pitch should be 2.5-3 degrees lower. Noticed excessive nose up pitch is required to maintain altitude at ALL configs.

**Comment by NathanInnes** [comment]
Pretty sure this is out of the current scope of this project. To my knowledge this is something we can't actually fix.

**Comment by benjwri** [comment]
There is a way to edit the flight model, I'm currently having a look to see if this is something that is documented through the SDK right now.

**Comment by benjwri** [comment]
As far as I have been able to find, disappointingly, there doesn't seem to be a way to change the ground friction through the SDK. The SDK is based of that of FSX, which also didn't have a way to change it, and therefore there isn't a way I can find to change the value if it is possible. At this point it doesn't look like it is possible to change without going outside the SDK, which isn't an option at the moment. The other bits might be possible to fix with a lot of testing.

**Comment by Taz5150** [comment]
I am trying to find a way to solve this issue with some techniques which have been used already in FSX/ P3D (I will auto-assign it if I believe I can work it out).
