### ISSUE TITLE
[BUG] Chrono units Text shimmering

### ISSUE THREAD

**Issue by ChruutvoLuzi** [flybywiresim/a32nx#3596]
**Mod Version**

latest Dev + CFBW Branch

**Describe the bug**

On the new Textures, the Unit Text of the Chronometer shimmers in certain conditions but is not visible when looking directly at it

**To Reproduce**

1. Load the AC
2. Drone around the Chronometer
3.

**Expected behavior**

it should be visible without shimmering

**Actual behavior**

![image](https://user-images.githubusercontent.com/70195216/108318207-b851e880-71bf-11eb-8ce8-ffe95db35bed.png)
![image](https://user-images.githubusercontent.com/70195216/108318241-c4d64100-71bf-11eb-98cc-4cfd634b93bc.png)
![image](https://user-images.githubusercontent.com/70195216/108318222-be47c980-71bf-11eb-9a7e-6c26143fb3ab.png)

**References**

![image](https://user-images.githubusercontent.com/70195216/108318455-2696ab00-71c0-11eb-81a0-5106089ee7a7.png)

**Additional context**

mentioned in #3571 

Was this working before/when did the issue start occurring?
With the new textures
Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):

**Comment by ImenesFBW** [comment]
I think the problem has been solved by @MoreRightRudder with the latest texture rework. If you have the time, please test on the current dev and close it if you agree it's gone @ChruutvoLuzi .

**Comment by ChruutvoLuzi** [comment]
> I think the problem has been solved by @MoreRightRudder with the latest texture rework. If you have the time, please test on the current dev and close it if you agree it's gone @ChruutvoLuzi . 

Will check today and report back

**Comment by ChruutvoLuzi** [comment]
yep, fixed with new normals
