### ISSUE TITLE
[REQUEST] Automated installer

### ISSUE THREAD

**Issue by davwheat** [flybywiresim/a32nx#360]
**Is your feature request related to a problem? Please describe.**
At the moment, updating the version involves redownloading the latest release/current state of the dev branch.

**Describe the features you'd like to see implemented**
An automated installer utility which can clone the GH repo and copy the A32NX folder to Community.

**Additional context**
At the moment I and some others are working on an installer for the livery megapack. I'd like to include this project in there as another possible project to install.

**Comment by Benjozork** [comment]
I'm not sure what is needed on our end here. If you are working on an installer yourself, is there anything we'd need to do to enable that ?

**Comment by davwheat** [comment]
It was more me just asking if it's alright with you guys, and a place for you to ask me for updates or something :P

**Comment by iiMeqaDev** [comment]
I'm currently working on one

**Comment by UncleClapton** [comment]
There was something being shown of in the discord about an auto-updater a little while back. not sure what happened with it.

**Comment by Meqolo** [comment]
I'm working on one as a side project

**Comment by Kaerbr** [comment]
I guess this issue can be closed.
See: https://github.com/Externoak/A32NX-installer

**Comment by davwheat** [comment]
I still plan on adding it to our add-on manager, too. Up to you if you want to keep the issue open or not. :)

**Comment by AdenFlorian** [comment]
externo's installer seems to meet this issue's ask. If our mod needs changes to be able to support other 3rd party installers, please create a new issue specifically for that, thanks!
