### ISSUE TITLE
Recent MSFS Update UK and Ireland

### ISSUE THREAD

**Issue by CP241** [flybywiresim/a32nx#3603]
After updating Flight Simulator, the FlyByWire plane acts very erratically. Selection of flaps causes erratic climb/descent, constraints on the flight route are not adhered to, and the aircraft leaves the altitude/level although a constraint exists. Routes are not followed and the plane just suddenly turns off the assigned route/flight path. This morning, on the ILS02 in Sante Fe, New Mexico, US, (APP button engaged) the aircraft descended well before the descent point and would have struck the ground without intervention.
PS.
Version 0.5.2 was unflyable, erratic climb/descent on departure.
Development version produced the above problems

Claus Pohl

**Comment by ChruutvoLuzi** [comment]
Try the Development Version. Flaps Drag has been fixed there and will make it into Stable soon with 0.5.3

**Comment by MisterChocker** [comment]
Closing since issue is outdated.
