### ISSUE TITLE
[BUG] FCU value reset happens too fast

### ISSUE THREAD

**Issue by leonlehmann** [flybywiresim/a32nx#3604]
**Mod Version**
master

**Describe the bug**
After changing HDG /TRK or V/S the windows resets to dashed display mode after just 5 seconds. In the real Airbus this happens after 45 seconds for  HDG /TRK and VS/FPA and after 10 seconds for  SPD/MACH.

**To Reproduce**
1. AP on
2. V/S mode
3. set a vertical speed but don't engage yet
4. the V/S window resets after just 5 seconds

**Expected behavior**
The HDG/TRK and VS/FPA windows should reset to the dashes after 45 seconds and the SPD/MACH windows should reset after 10 seconds.

**References**
- From the A320 FCOM:
_In managed guidance (lateral, vertical guidance or managed speed), the corresponding
window is dashed. Turning a knob without pulling it, displays a value that is the sum of the
current target and the turn action value. The display remains 45 s on the HDG /TRK and
V/S windows and 10 s on the SPD/MACH window before the dashes reappear. This rule
does not apply to the ALT knob/window._

- Youtube video from 320 Sim Pilot showing this problem with FPA: https://youtu.be/7ElFBOUhnMQ?t=1056

Was this working before/when did the issue start occurring?
No.

Discord username (if different from GitHub): ll3hm4nn#4549

**Comment by leonlehmann** [comment]
Can someone please assign me for this issue? I would like to contribute :-)

**Comment by Awemeter** [comment]
You don't need to be assigned just make a pr and state you are fixing this issue. If you need help making a pr check out the contributing.md or ask in dev support in the server.

**Comment by lukecologne** [comment]
Before you work on anything: The video from A320 sim pilot is from the custom autopilot branch, in which this issue is already fixed

**Comment by leonlehmann** [comment]
@lukecologne alright, sorry I didn't notice that. Should we cherry pick this over into a new PR for master or just wait for the custom autopilot branch to land?

**Comment by aguther** [comment]
I did change that already on the code for the upcoming custom autopilot system.

**Comment by aguther** [comment]
> @lukecologne alright, sorry I didn't notice that. Should we cherry pick this over into a new PR for master or just wait for the custom autopilot branch to land?

I think it's not much to be changed to increase the timeout, question is more if there are not any additional issues happening then.

Just doing a cherry pick will not work, because on the custom Autopilot branch there was more change to the FCU to fix also other issues with it. For example it needs to take into account states from that system and those are not available on the master branch.

**Comment by leonlehmann** [comment]
@aguther I just had a glance on your custom-ap branch. Just a quick suggestion: To implement it like stated in FCOM, `backToIdleTimeout` also needs to be implemented and set to 10s for SPD/MACH.

As I could see, TRK/HDG and VS/FPA are already set to 45s. That's great!

**Comment by aguther** [comment]
Up to now I did not touch the speed, but you're right. At some point I would also like to fix the scrolling of speed (to it's consistently changing 1 kn instead of sometimes 10 and sometimes 1).
