### ISSUE TITLE
SRS misbehaviour as from MSFS Update 1.13.16.0

### ISSUE THREAD

**Issue by lonewulf47** [flybywiresim/a32nx#3605]
0.5.2

**Mod Version**

master

**Describe the bug**

the SRS mode entered upon takeoff does not apply enough pitch to maintain V2+10

**To Reproduce**

1.issue normal takeoff with all managed modes
2.
3.

**Expected behavior**

The pitch in SRS mode should be enought to maintain V2+10 until acceleration mode to managed speed is entered

**Actual behavior**

The pitch applied in SRS mode results in slow acceleration which is incorrect during this phase

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by aguther** [comment]
The SRS law on master is provided by the default Autopilot system and cannot be changed by us other than creating a custom system. Therefore it will be fixed by the upcoming custom Autopilot system.
