### ISSUE TITLE
[BUG] ILS localizers not establishing

### ISSUE THREAD

**Issue by mio9** [flybywiresim/a32nx#3612]
**Mod Version**

Custom FBW 2fc6746

**Describe the bug**

Aircraft not showing any sign of glideslope/localizer being intercepted, it just shows empty

**To Reproduce**

1. Create and input a flight plan with destination airport equipped with ILS
2. Select the runway, with ILS
3. Fly to the approach with APPR mode on and LS mode on

**Expected behavior**

ILS glideslope and localizer markings should appear as soon as localizer being intercepted, and the aircraft would follow if autopilot is engaged

**Actual behavior**

As if the runway has no ILS equipped

**References**

**Additional context**

Was this working before/when did the issue start occurring?
It breaks after updating the simulator to the UK world update

Is this a problem in the vanilla unmodded game?
No, it is not

Discord username (if different from GitHub):

**Comment by Brownyb68** [comment]
I also had this issue and had to input the ILS for the runway into the RAD/NAV page. I loaded my flight plan from simbrief

**Comment by i2icho** [comment]
Same issue here after UK update. FBW custom mod re installed after UK update.

NAV/Radio page empty 

Filling in manually ils freq. Still not following g/s

**Comment by Drachondius** [comment]
NAV/RAD page does not get info from simbrief flightplan anymore it seems.
Putting in the right ILS Freq manually fixed it for me! ILS worked fine for 4 APPR!!!

**Comment by ThatRedMelon** [comment]
This will be fixed by #3599

**Comment by Richard5644** [comment]
Same issue here.   Also despite reinstalling FS2020 and fbw dev version, MCdu will still not load simbrie flightplan.  simply says "nopt in database", and "not allowed.   had this problem since stable version 0.5.0

**Comment by mio9** [comment]
are there any method i could manually input the ILS frequency into the CDU for now?

**Comment by Drachondius** [comment]
Sure, get the desired ILS Frequency from a chart and put it in the RAD/NAV
page on the FMCU.

MIO.sh <notifications@github.com> schrieb am Fr. 19. Feb. 2021 um 19:05:

**Comment by Drachondius** [comment]
> Same issue here. Also despite reinstalling FS2020 and fbw dev version, MCdu will still not load simbrie flightplan. simply says "nopt in database", and "not allowed. had this problem since stable version 0.5.0

Delete STARs and SIDs in SimBrief OFP. Then try again (restart flight!) and Plan STAR and SID manually. Worked for me.

**Comment by mio9** [comment]
> NAV/RAD page does not get info from simbrief flightplan anymore it seems.
> Putting in the right ILS Freq manually fixed it for me! ILS worked fine for 4 APPR!!!

it simply says NOT ALLOWED for whatever format and content i input to the slot

**Comment by pacha35** [comment]
HI,
same issue at LFRN ILS28 : nothing on the PFD display, impossible to enter ILS frequency in the RAD/Com page of MCDU.
MSFS V1.13.16.0, A32NX V 5.2 dev #a4dc39a
Regards
