### ISSUE TITLE
[BUG] Unable to dial x20 after decimal in com

### ISSUE THREAD

**Issue by evpoppel** [flybywiresim/a32nx#3614]
**Mod Version**
master

**Describe the bug**
trying do dial in 119.220 EHAM_W_TWR in vatsim, via A32NX master as of 2/18/21 
only possibilities 119.215 then direct 119.225..  no .220??

Then connected outside of vatsim (no vPilot running)  and started on rwy at EHAM. 
result: still no .120, .220, .320 etc.  possible

**Comment by joniatus** [comment]
See issue#1802 this is intended behavior. You can reach them on 119.225. just ignore the thousandth

**Comment by beheh** [comment]
[See here for an explanation of the 8.33khz spacing](https://mediawiki.ivao.aero/index.php?title=Frequency#8.33_kHz).

**Comment by evpoppel** [comment]
Ty for lifting my ignorance.

Verzonden vanuit Mail voor Windows 10

Van: Benedict Etzel
Verzonden: vrijdag 19 februari 2021 11:28
Aan: flybywiresim/a32nx
CC: evpoppel; Author
Onderwerp: Re: [flybywiresim/a32nx] [BUG] Unable to dial x20 after decimal in com (#3614)

See here for an explanation of the 8.33khz spacing.
