### ISSUE TITLE
[BUG] Texture problem in outdoor camera 

### ISSUE THREAD

**Issue by Manuaero3** [flybywiresim/a32nx#3615]
**Mod Version**

  "built": "2021-02-18T11:11:07+00:00",
  "ref": "master",
  "sha": "4b05219952414bc470edc3036cecb8e1e65012c1",
  "actor": "nistei",
  "event_name": "manual"
}

**Describe the bug**

Erasing of some textures by zooming out (tested with different liveries)

**To Reproduce**

1. Spawn on gate or ramp with A32NX
2. Put yourself in outside view or drone camera
3. zoom in and out or move farther or closer to the plane

**Expected behavior**

restoration of the textures in case of moving away from the aircraft

**References**

**Additional context**

No context

https://user-images.githubusercontent.com/71601864/108429067-ccd5c580-723f-11eb-8a28-b919ae9197a6.mp4

Was this working before/when did the issue start occurring?
Yes.
Does not work since the last update of Asobo

Is this a problem in the vanilla unmodded game?
No tested

Discord username (if different from GitHub):

**Comment by sidnov** [comment]
Seems to be an isolated issue, not been able to reproduce on the latest sim/addon version
