### ISSUE TITLE
Make it clearer what data you collect from users

### ISSUE THREAD

**Issue by Carlgo11** [flybywiresim/a32nx#3619]
I just noticed that my flight (starting airport, current pos, destination airport, flight number, livery) is displayed on https://flybywiresim.com/.

I understand that this could be a cool thing to have but it should be clear to the user that such data is being collected and it should be an opt-in thing.
Furthermore there should be a clear privacy policy detailing what kind of other data is collected, who is collecting it (legal entiy and address), how it's being used, where it's being used and how said data can be removed should the user wish to do so.
The current [policy](https://raw.githubusercontent.com/flybywiresim/manuals/master/pdf/Privacy%20Policy.pdf) doesn't address this at all.

I love the airplane but I don't think I should have to decide between the mod or my privacy 😞

**Comment by FoxinTale** [comment]
My understanding , and a developer is free to correct me, is as follows. You opt in to this by enabling freetext in the MCDU, and can opt out by disabling freetext. It only collects information about the sim status.  Location (in sim only, not geo-location) , and the status of your flight such as speed and altitude.  No actual personal data is collected.  

Now, there is a valid point of the privacy policy is not clear and somewhat hidden. This is something that I have brought up in the past, but as no data is collected currently, there's not a reason to update it.

**Comment by Benjozork** [comment]
Hello,

The collection of data is already **opt-in** and a warning clearly states flight info is collected if you enabled online features the first time you enabled the mod, as well as every time you enable / disabled them. If you did not get that warning, please open an issue ticket about that.

Regarding the privacy policy, it currently only applies to the website. It will be edited to provide info about TELEX as well.

To clarify further, no personally identifying information (PII) is collected. IP addresses are not logged and client information isn't either.

**Comment by wpine215** [comment]
This is the code for the dialog that is displayed when you use the mod for the first time (and available later through the OPTIONS menu). As Benjozork said, by default it is opt-out.

https://github.com/flybywiresim/a32nx/blob/master/A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_TELEX.js

**Comment by Carlgo11** [comment]
Hmm 🤔
I have that option disabled. Guessing it’s a bug then?

**Comment by rodney1710** [comment]
This data (starting airport, current pos, destination airport, flight number, livery) would not be regarded as personal data as defined under article 4(1) UK GDPR/ EU GDPR. Therefore the regulation does not apply, including the requirement for transparency under articles 12, 13 and 14.

R

**Comment by wpine215** [comment]
> 
> 
> Hmm 🤔
> I have that option disabled. Guessing it’s a bug then?

if it says "disable", then you actually have it enabled, since the label on that button indicates what happens after you press it.
