### ISSUE TITLE
[BUG] Extreme memory usage

### ISSUE THREAD

**Issue by BitsAndDroids** [flybywiresim/a32nx#3642]
**Mod Version**

FlyByWire installer

**Describe the bug**

After hibernating my pc overnight the Flybywire RAM usage peaked at 16GB

**To Reproduce**

I updated the a320 neo -> closed the app -> played game -> put windows in sleep mode -> resume flight -> notice lag -> installer using 16gb RAM

**Expected behavior**

to not use 16GB of RAM ;)

**Actual behavior**

Used 16GB of RAM

**References**

Added screenshot

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):
Bits and Droids#6718

![image](https://user-images.githubusercontent.com/77780263/108592326-aa41ca80-736d-11eb-8b8f-e25e6e798b44.png)

**Comment by Daboj1337** [comment]
Yesterday i had the same issue. Suddenly 32gb ram was used by the installer and my pc crashed

**Comment by FSC190** [comment]
Yes, that was after updating the installer himself.

**Comment by hotshotp** [comment]
This is not the installer repo, please make an issue there

**Comment by Valastiri** [comment]
Just to follow up. This issue already exists as well and is under investigation. 
https://github.com/flybywiresim/installer/issues/106
