### ISSUE TITLE
Extreme low FPS since last update

### ISSUE THREAD

**Issue by Passi27** [flybywiresim/a32nx#3645]
Hey,
since the new release of MSFS, I am unable to play with it with the A32NX. I tried everything, deleted the community folder (only left the A32NX there), but when loading the game I have not more than 8 FPS. Before the update it was no problem, my hardware is also not in max use, I tried also on low and med settings, but didnt change a thing. Had even more FPS on ultra settings.
Only when I delete the A32NX, the game runs smoth like before

**Comment by DieProgrammIDE** [comment]
How are you installing A32NX?

Have you tried fully deleting A32NX, downloading/using the [official Installer](https://api.flybywiresim.com/installer) and Installing the Stable Build?

**Comment by Passi27** [comment]
yes did also that, always using the installer. 
there are many problems with performance since the last update, Also without the mod

**Comment by Benjozork** [comment]
You did not follow the provided template, closing.

Additionally, as you said yourself, this is an MSFS issue:

> https://flybywiresim-packages.b-cdn.net/stable/A32NX-stable.zip
