### ISSUE TITLE
[BUG] INSERT TITLE HERE

### ISSUE THREAD

**Issue by Punkcito** [flybywiresim/a32nx#3646]
**Mod Version**

{
  "built": "2021-01-09T06:59:30+00:00",
  "ref": "refs/remotes/upstream/HEAD",
  "sha": "a97147821116d4b27eb5a103e609378bf319cbc2",
  "actor": "Benjamin Dupont <benjozorkfr@gmail.com>",
  "event_name": "manual"
}

**Describe the bug**

I just noticed in the MSFS known issues that the lift effects for flaps is doubled.  It mentions a workaround of dividing the lift_coef_flaps setting by 2 in flight_model.cfg.  Looking at this value in both the stock 320 (world update 3) and a32nx I see a large difference in values.  Stock uses lift_coef_flaps = 1.45380 and a32nx uses lift_coef_flaps = 2.4

Is the a32nx value still correct for MSVS world update 3?

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Valastiri** [comment]
BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning

Additionally, this has been solved in development and the recent stable 0.5.3.

**Comment by hotshotp** [comment]
this is different in our a320 because we changed it, the stock is incorrect
