### ISSUE TITLE
[BUG] React PFD causes bad frame drops every 2-3 seconds (due to GC pressure)

### ISSUE THREAD

**Issue by XSJoJo** [flybywiresim/a32nx#3652]
**Mod Version**
origin/autopilot ToT as of 20/02/21

System: i9900k with 2080 Ti

**Describe the bug**
When using the React-style PFD, I get a series of really slow frames in CoherentGT, followed by a big frame drop (~30-40ms) every 2-3 seconds in the sim.

**To Reproduce**
1. Set glass cockpit refresh rate to high.
2. Scale down graphics options to ensure you're limited by MainThread/CoherentGT
3. Spawn in a low-density place (small islands work well, like PHLI)

**Expected behavior**
Mostly smooth FPS without drops.

**Actual behavior**
I get a series of really slow frames in CoherentGT, followed by a big frame drop (~30-40ms) every 2-3 seconds in the sim.

**References**
![PXL_20210220_231247685_2](https://user-images.githubusercontent.com/3019329/108610902-b7949e80-73d9-11eb-9bf7-3f2c52a6341a.jpg)

**Additional context**
I've investigated this quite a big and I'm 95% sure this is the garbage collector that seems to run synchronously on the main thread. I simulated allocating 5k objects/per frame without the old PFD and bingo, I get the exact frame drop pattern.

We also get occasional frame drops on master, but they are a lot less pronounced and less frequent.

Additionally, I've also been seeing this long flight plans as well, so I think we have the exact same issue there where we create a ton of objects for redrawing the flight plan.

I also captured a trace (with my custom tracing infra, PR incoming soon) where I can see the pattern pretty well. You can open it with chrome://tracing with Google Chrome. (You'll need to extract the traces first)

[traces.zip](https://github.com/flybywiresim/a32nx/files/6016818/traces.zip)

Looking at the React PFD, it seems that the entire tree will be recalculated for every frame, since we invalidate it here: 

https://github.com/flybywiresim/a32nx/blob/autopilot/src/instruments/src/PFD/index.jsx#L81

The JSX part at the end of the render method (and at the end of every element function) is essentially a shorthand for React.createElement, which seems to create a bunch of objects [https://reactjs.org/docs/introducing-jsx.html#jsx-represents-objects]. Now, since these are quite a few of them, I could easily see how this creates hundreds if not thousands of objects for every frame (x2 for Captain and FO).

**Comment by Benjozork** [comment]
With a deep component tree in React it's important we make sure to not render everything every frame. Gonna have to look more into this.

**Comment by lionhell** [comment]
Don't know if it is the same subject but since before-last DEV update (2 days ago) the **left PFD** shows wrong speed and altitude, causing crash after takeoff the 1st time because overspeed with flaps extended. Didnt understand what was happening !
I realised on the 2nd flight that pfd indocations were wrong !!!!
Fortunately right PFD is working well, but not pleasant to juggle between left and right seat !

**Comment by XSJoJo** [comment]
> Don't know if it is the same subject but since before-last DEV update (2 days ago) the **left PFD** shows wrong speed and altitude, causing crash after takeoff the 1st time because overspeed with flaps extended. Didnt understand what was happening !
> I realised on the 2nd flight that pfd indications were wrong !!!!
> Strange thing is that on arrival, in the STAR, **left PFD** recovers normal behaviour !? I have the sensation that it is in relation with aircraft config: flaps, or appr or I dont know what.. but at the end of flight **left PFD** works normally !
> 
> Fortunately right PFD is working well, but not pleasant to juggle between left and right seat !

That seems unrelated. Can you open a separate bug for this?

**Comment by lukecologne** [comment]
Can you confirm you are using the new react PFD? on which branch are you? Please post the build info

**Comment by lionhell** [comment]
I'm using FBW installer, updating DEV version : **525dc7c**

**Comment by lukecologne** [comment]
The dev version does not include the new PFD, so it is unrelated to this issue.

**Comment by lionhell** [comment]
I don't know what is react PFD ??? Is it a stable dev feature ?

**Comment by Benjozork** [comment]
@lionhell Please open a new issue. This issue is for something unrelated to your problem.

**Comment by aguther** [comment]
Feel free to reopen when needed. My experience is that there is no issue right now on dev.
