### ISSUE TITLE
[BUG] MILES TO DESTINATION STOP AT 78 NM MCDU.

### ISSUE THREAD

**Issue by mikecbr** [flybywiresim/a32nx#3657]
**Mod Version**
Latest master brancg

**Describe the bug**
The miles to destination stop at 78 nm at some waypoints , then once you past the waypoint where it stops (the miles) , it shows up again  the real distance to destination.
This is happening due to some performance optmizations PR for the ND:  #3379   AND #3380 

**To Reproduce**

1.Load a FP normally 
2.Check out close to destination , more less 78 nm that in the MCDU the miles freeze
3.

**Expected behavior**
Shouldnt freeze at all

**Actual behavior**
The miles to destination stop at 78 nm at some waypoints , then once you past the waypoint where it stops (the miles) once the aircraft ctch up the next point  , it shows up again  the real distance to destination 

**References**

**Additional context**

Was this working before/when did the issue start occurring?
I think its working in the stable 

Is this a problem in the vanilla unmodded game?
NO

Discord username (if different from GitHub):

**Comment by Silvaronn** [comment]
I have the same problem.
It had been fixed, but it seems that in the last update it came back.

**Comment by 2hwk** [comment]
Fixed by 4953 closing ☑️
