### ISSUE TITLE
[BUG] EFB screen flickers

### ISSUE THREAD

**Issue by PiotrMKG** [flybywiresim/a32nx#3660]
**Mod Version**

acb6222

**Describe the bug**

After spawning into cockpit EFB is on and screen flickers

**To Reproduce**

1. Load at any airport 
2. After updating yesterday (20.02 around 22:00 previously installed version was fine.
3.

**Expected behavior**

EFB should be off and screen do not flicker.

**Actual behavior**

After updating yesterday (20.02 around 22:00 previously installed version was fine.
![Zrzut ekranu (15)](https://user-images.githubusercontent.com/71447128/108621086-d5d9b900-7430-11eb-85df-cb1378b60fb8.png)

**References**

**Additional context**

Stable build 0.5.3 works fine.
Was this working before/when did the issue start occurring?
It was working fine on saturday morning.
Is this a problem in the vanilla unmodded game?
No, stable version works fine.

Discord username (if different from GitHub):
PiotrMKG #4262

**Comment by wpine215** [comment]
Are you using a non-default livery?

**Comment by PiotrMKG** [comment]
> Are you using a non-default livery?

Yes, on that flight I was using Wizz Air https://flightsim.to/file/590/a320neo-wizz-air-ha-lja-8k
