### ISSUE TITLE
[BUG] APU won't start

### ISSUE THREAD

**Issue by PiotrMKG** [flybywiresim/a32nx#3661]
![Zrzut ekranu (16)](https://user-images.githubusercontent.com/71447128/108621330-65339c00-7432-11eb-8c7b-50bc9ef26cf6.png)

**Mod Version**

acb6222

**Describe the bug**

APU won't start, APU flap doesn't open

**To Reproduce**

1. Load into cocpit, power on batteries, connect extrernal power, wait untill selftest ends.
2. Press APU Master SW wait for Flap Open (nothing happens)
3. Press APU Start (nothing happens

**Expected behavior**

After pressing APU Master SW flap should open and after pressing APU start APU should start spool up.

**Actual behavior**

After updating dev ver. APU won't start

**References**

**Additional context**

Was this working before/when did the issue start occurring?
It was working before I updated dev version on Saturday ca. 22:00
Is this a problem in the vanilla unmodded game?
No, Stable ver. 0.5.3 works fine

Discord username (if different from GitHub):
PiotrMKG #4262

**Comment by PiotrMKG** [comment]
I think Wizz Air livery causes that, I will test with default one and report back.

**Comment by ChruutvoLuzi** [comment]
Yes, the wizz air one edits the registration number so it has another mainpanel file in it which causes issues

**Comment by Valastiri** [comment]
Please use our #help channel in discord and ensure have tested with no mods/liveries in your community before opening a ticket.

**Comment by hotshotp** [comment]
liveries that edit panel cfg like yours will not be able to have the APU work
