### ISSUE TITLE
[BUG] Flight Control Issue, after restarting the simulator, Expermental Version.

### ISSUE THREAD

**Issue by pboelcskei** [flybywiresim/a32nx#3662]
**Mod Version**

- {
  "built": "2021-02-21T04:08:04+00:00",
  "ref": "master",
  "sha": "007d8edc347ea0ec86eb25c6bf429175730064d5",
  "actor": "Benjozork",
  "event_name": "manual"
}

**Describe the bug**

- If I install the FBW A320, Experimental Version, on the first start of MSFS2020, the controls (aileron, elevator, rudder, and throttle) work normally, however, after restarting MSFS2020 (closing it, and opening it again), the controls do not work anymore. With the stable and development version, everything works normally. If I then go into the following folder: C:\Users\Philip\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalState\packages\a32nx 
and delete everything in this folder, and restart the MSFS2020, everything works normally again, until I restart the Simulator.

**To Reproduce**

- 1. Install MSFS2020, and the FlyByWire A320 Experimental Version.
- 2. Start the simulator once, and load the FBW A320.
- 3. Restart the simulator (Close it completely) and start it again, load the FBW A320.

**Expected behavior**

- Normal Control Behaviour, regarding Elevator, Aileron, Throttle, and Rudder.

**Actual behavior**

- No Control authority regarding Elevator, Aileron, Throttle, or Rudder.

**References**

- Discord Ticket: philip2083

**Additional context**

- This problem only persists with the experimental version of the FBW A320. The stable, as well as the development ones, work fine. If I delete the following Folder: 
C:\Users\Philip\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalState\packages\a32nx
and restart the simulator, the problem is solved, until I restart the simulator again.

Was this working before/when did the issue start occurring? 
- About 1 week ago, it came out of nothing.

Is this a problem in the vanilla unmodded game? 
- Yes

Discord username (if different from GitHub):
- Philip#2083

**Comment by pareil6** [comment]
cc @aguther

**Comment by pboelcskei** [comment]
Problem solved: The issue, was a simconnect.cfg from an addon called "Kinetic Assistant". This file is located in the Documents Folder. I deleted this file, and now, everything is working as it should. Thanks for your great support on Discord!
