### ISSUE TITLE
[REQUEST] Show only relevant airports on ND

### ISSUE THREAD

**Issue by krangerich** [flybywiresim/a32nx#3663]
**Is your feature request related to a problem? Please describe.**

When you choose ARPT on the EFIS panel and choose a larger range like 80nm, the ND is cluttered with airports. On the real airplane, there is not every existing little airfield displayed, but rather a list of airports the aircraft could divert to. I think, the list of displayed airports is being determined by the operator.

**Describe the feature you'd like to see implemented**

Filter the airports displayed on the ND (when in ARPT mode) by some simple heuristic, e.g. display only airports with at least one runway with a length of 4.500ft or more (for example). 

**References**

-/-

**Additional context**

-/-

Discord username (if different from GitHub):
-/-

**Comment by sidnov** [comment]
@tracernz I think we have docs for this, coming from the ND rewrite? Feel free to close the issue if we have already implemented this correctly

**Comment by tracernz** [comment]
Yeah, this is already done.
