### ISSUE TITLE
[BUG] BLANk monitors No FLB tablet

### ISSUE THREAD

**Issue by mixsiak** [flybywiresim/a32nx#3674]
**0.5.3 master**

**Describe the bug**
on the dark cold starr up.. 
no tbalet no coffee cup
on first time no power on displays 

**To Reproduce**

1.no tablet
2.on fly one in the middle route display switch off and switch o  Back again
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
0.5.3 does not contain the EFB or coffee cup. Please read the changelog.

For the displays, that's most likely a mod conflict. Try with nothing else in your community folder.

Going to close your issue as there isn't a bug here.

**Comment by mixsiak** [comment]
so where is flb tablet with Desert calculatorthanksOdoslané z môjho smartfónu Samsung Galaxy NOTE 10
-------- Pôvodná správa --------Od: Benjamin Dupont <notifications@github.com> Dátum: 21. 2. 2021  22:59  (GMT+01:00) Komu: flybywiresim/a32nx <a32nx@noreply.github.com> Kópia: mixsiak <michal.kolcun@gmail.com>, Author <author@noreply.github.com> Predmet: Re: [flybywiresim/a32nx] [BUG] BLANk monitors No FLB tablet (#3674) 
0.5.3 does not contain the EFB or coffee cup. Please read the changelog.
For the displays, that's most likely a mod conflict. Try with nothing else in your community folder.
Going to close your issue as there isn't a bug here.

**Comment by Benjozork** [comment]
In the development version
