### ISSUE TITLE
[BUG] 'UNTITLED' in pg2 of

### ISSUE THREAD

**Issue by Owenwilsonsnose** [flybywiresim/a32nx#3676]
**Mod Version**
<Latest stable version>

**Describe the bug**
 After filling out the block fuel manually and hitting next pg, received a black screen with only the words 'UNTITLED' in all caps

**To Reproduce**

1. Fill out block fuel in INIT page
2. Click next page
3.

**Expected behavior**
 Able to proceed to next page

**Actual behavior**
 All black screen with 'UNTILTED' in white

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game? Yes

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by beheh** [comment]
Please follow the template next time opening an issue, and read the instructions carefully:

> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning
