### ISSUE TITLE
[BUG] LEDS and Korrys are all on as in “Light test” during flight.

### ISSUE THREAD

**Issue by sodgaard** [flybywiresim/a32nx#3677]
![8CFCC4EB-A5A8-4C54-9116-4F6E16121CF9](https://user-images.githubusercontent.com/44952678/108641632-87640300-74a0-11eb-9e76-4b080d92e83e.png)

**Mod Version**

Latest release version .53 installed via the installer. The MSFS version is the latest with UK update.

During the flight suddenly all KORRYs land LED light up with all lamps on.

**To Reproduce**

1. Created a MSFS flight EKCH-EKAH
2. Created a SimFlight plan which was succesfully imported
3. Updated Fuel and payload via SimFlight import window
4. The INIT A “Request Init” did not show.
5. Started Pushback and startup
6. Changed DEP RWY and SID.
7. Departed - all systems good.
8. After departure the KORRY and LED all showed up lit. The Aircraft continued to behave as expected, including MCDU and Button pushes both on the OH, MIP, PED, and Glare. This however did not turn off any KORRY, LED, but affected the PFD, ND etc.
**Expected behavior**

Normal KORRY and LED Status information

**Actual behavior**

All KORRY and LED lit.

**References**

See screenshot after landing.

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):
sso

**Comment by sodgaard** [comment]
Not sure why the following did not show above:
Mod version .53 stable release auto installed by Installer.
FS version - latest Update III incl. UK.

**Comment by ThatRedMelon** [comment]
This is most likely due to a mod conflict. Try without anything in the community folder but a32nx.

**Comment by MisterChocker** [comment]
Closing since no response from op
