### ISSUE TITLE
Installer using over 18GB RAM

### ISSUE THREAD

**Issue by markgossa** [flybywiresim/a32nx#3678]
**Mod Version**
master

**Describe the bug**
After install and working for a while, computer almost crashes then I find that the installer is using 18GB RAM.

**To Reproduce**
Not able to reproduce but this is how it happened:
1. Install the latest master version
2. Fly flight simulator

**Expected behavior**
Installer to not use 18GB RAM

**Actual behavior**
Installer using 18GB RAM as per screenshot below

**References**
![image](https://user-images.githubusercontent.com/16326726/108643038-b4181a80-74a0-11eb-9586-660a5c0e4eb0.png)

**Additional context**
Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

**Comment by Benjozork** [comment]
This is the repository for the A32NX addon.

Your issue is already known in the installer repository.

**Comment by markgossa** [comment]
Okay, thanks. Apologies - I didn't know there was an installer repository.
