### ISSUE TITLE
[REQUEST] efb Navigraph Charts page

### ISSUE THREAD

**Issue by airfirefighter** [flybywiresim/a32nx#3679]
**Is your feature request related to a problem? Please describe.**
negative

**Describe the feature you'd like to see implemented**
possibility in efb to have a page with navigraph charts

**Comment by Awemeter** [comment]
This feature is already being worked on.

**Comment by Awemeter** [comment]
Duplicate of #1831 too

**Comment by airfirefighter** [comment]
sorry i havent see it im closing it
