### ISSUE TITLE
[BUG] VS mode deselects when altitude changed on FCU

### ISSUE THREAD

**Issue by rbnov** [flybywiresim/a32nx#3688]
**Mod Version**
Development version 23a99e1
MSFS last version with UK.

**Describe the bug**
As explained in the title, Vertical Speed mode of autopilot deselects and reverts to OP DES when changing the altitude on the FCU. Changing the target altitude should not change the ALT mode of the autopilot.

**To Reproduce**
1. When in CRZ, start descend to a lower altitude.
2. Engage Vertical Speed mode
3. Change the target altitude by rotating the altitude bug on the FCU

**Expected behavior**
Vertical Speed mode should remain active.

**Actual behavior**
OP DES mode engages.

**References**
Not found

**Additional context**
Not applicable

Discord username : rbnov#9383

**Comment by aguther** [comment]
Will be fixed with custom AP system.
