### ISSUE TITLE
[BUG] target speed bug is gone

### ISSUE THREAD

**Issue by AdenFlorian** [flybywiresim/a32nx#369]
**Branch**
dev

**Describe the bug**
target speed bug is not visible anymore, it used to be

**To Reproduce**
spawn in cruise
go to selected speed mode

**Expected behavior**
should see a cyan speed bug on left of PFD

**Screenshots or Videos**
![image](https://user-images.githubusercontent.com/3533988/92203485-e11b3700-ee46-11ea-8b53-4631031e5606.png)

**Additional context**
n/a

**Comment by tyler58546** [comment]
I think this is because the takeoff phase is not ending if the acceleration altitude is not set.

**Comment by AdenFlorian** [comment]
> I think this is because the takeoff phase is not ending if the acceleration altitude is not set.

Yup, it is.

https://github.com/wpine215/msfs-a320neo/pull/322/files#r483424857

**Comment by UncleClapton** [comment]
We probably need to set a default value for that in the MCDU. Not sure if it should be set automatically all the time, or if it should be set when starting from runway or flight, though. @AdenFlorian mentioned in #322 that someone starting from the runway should be able to "spawn on the runway, turn off parking brake, and takeoff without any other changes". FWIW I agree, and I also think most players would expect that to be the case.

**Comment by CoffeePanda0** [comment]
> 
> 
> We probably need to set a default value for that in the MCDU. Not sure if it should be set automatically all the time, or if it should be set when starting from runway or flight, though. @AdenFlorian mentioned in #322 that someone starting from the runway should be able to "spawn on the runway, turn off parking brake, and takeoff without any other changes". FWIW I agree, and I also think most players would expect that to be the case.

I had this issue today starting from cold and dark even, the MCDU was stuck into the takeoff PERF page so managed speed didn't work even on latest commit

**Comment by AdenFlorian** [comment]
this should be fixed by https://github.com/flybywiresim/a32nx/commit/773b8499adace5834367b6044c4ef1faa6f9d4e5

**Comment by AdenFlorian** [comment]
The fix made it so that you should transition out of the takeoff phase when one of the following conditions is met:
- agl > acceleration altitude
- agl > thrustReductionAltitude
- agl >1500

**Comment by Coralec** [comment]
The aircraft will now begin climb phase once the aircraft is 1500ft above sea-level *if* no acceleration speed is set in the MCDU. The new fix is working correctly.
