### ISSUE TITLE
[BUG] Setting simvar `GENERAL ENG THROTTLE LEVER POSITION:index` does not move the thrust lever in Custom FBW version

### ISSUE THREAD

**Issue by nguyenquyhy** [flybywiresim/a32nx#3703]
**Mod Version**
Custom FBW 32e23ff

**Describe the bug**
Using SimConnect, setting `GENERAL ENG THROTTLE LEVER POSITION:1` or `GENERAL ENG THROTTLE LEVER POSITION:2` has no effect on the thrust lever. This works correctly in Stable and Development version.

**To Reproduce**
1. Using SimConnect to set `GENERAL ENG THROTTLE LEVER POSITION:1` or `GENERAL ENG THROTTLE LEVER POSITION:2` to any random value
2. Observe the thrust lever in the flight deck

**Expected behavior**
Thrust levers should move to the requested value.

**Actual behavior**
Thrust levers do not react and stay still.

**Additional context**

Was this working before/when did the issue start occurring?
Yes. This works in Stable (0.5.3) and Development (d6d5f02).

Is this a problem in the vanilla unmodded game?
Yes, the game is unmodded (except from this mod). I have also tried to remove SimConnect.cfg file to prevent potential conflict.

Discord username (if different from GitHub): Hy#7819

**Comment by aguther** [comment]
Due to limitations we are faced with the sim (e.g. throttle levers are completely frozen when default FBW is disabled and ATHR is on). Therefore the custom FBW needs to do this in order to allow a normal usage.

If you need to move the throttles, please use the appropriate events, like KEY_THROTTLE_SET or KEY_AXIS_THROTTLE_SET.

**Comment by nguyenquyhy** [comment]
Is there any simvar that correlate to the input passed to `THROTTLE_SET` or `AXIS_THROTTLE_SET`?

As far as I know `GENERAL ENG THROTTLE LEVER POSITION:index` value cannot be passed directly to those events, and I really don't know how to get the axis mapping from SimConnect.

**Comment by aguther** [comment]
The range of the events is -16384 to +16384. You can get the input if you subscribe to those events. Ensure you take the highest priority in SimConnect without masking the events. Then you will get every update.

I can understand that this might be a bit painful for your use case, but it's currently the only way I know. We have simply also no other options than doing it the way we do it now.

**Comment by nguyenquyhy** [comment]
Thanks for the explanation. I will try that out as I really don't want to lose support for the 32NX once the FBW version is out. 

But honestly losing thrust control completely is a real bummer. If this is a problem with the default FBW, should we push Asobo for a fix?

**Comment by aguther** [comment]
Honestly I would expect that other add-ons that need to decouple the throttles also will behave very similar. For example the upcoming CRJ from Aerosoft has also a throttle mapping feature (there was a screenshot from the EFB how it can be configured). So I think it's a good investment to change capturing and injection to this event system.

I don't expect any changes like this in the base in a near time frame, there are so many other priorities.
