### ISSUE TITLE
[BUG] Setting simvar `SPOILERS HANDLE POSITION` does not move the speed brake handle

### ISSUE THREAD

**Issue by nguyenquyhy** [flybywiresim/a32nx#3704]
**Mod Version**
Stable (0.5.3), Development (d6d5f02) and Experimental (32e23ff)

**Describe the bug**
When using SimConnect to set `SPOILERS HANDLE POSITION`, the spoilers on the wing move correctly, but the handle in the flight deck does not move at all.

**To Reproduce**
1. Use SimConnect to set `SPOILERS HANDLE POSITION` to any value.
2. Observe that the spoilers on the wing move
3. Observe that the handle in the flight deck has no reaction

**Expected behavior**
The speed brake handle in the flight deck should move to the requested value.

**Actual behavior**
The speed brake handle in the flight deck stays still.

**Additional context**

Was this working before/when did the issue start occurring?
It was not working before.

Is this a problem in the vanilla unmodded game?
Yes the sim is unmodded (except from the 32NX).

Discord username (if different from GitHub): Hy#7819

**Comment by ErickSharp** [comment]
This is because the spoiler level of deployment is tied to the simvar for the spoilers handle position, but the spoilers lever is not affected by the simvar because the lever has the express purpose of affecting that simvar in the first place.

**Comment by nguyenquyhy** [comment]
This explanation is very reversed from the spirit of settable simvar... 
Settleable simvar should be settable from the outside to affect the aircraft. This is more or less the same as COM/NAV frequency.

Also setting this simvar works correctly in all default aircraft. I really hope flybywire can try to make the 32NX on par with default on this regard...

**Comment by ErickSharp** [comment]
Yes but isn't the com/nav frequency a digital reading, not an actual animation? I don't actually know how beneficial this would be, as I cant imagine a system that, for example, pulls the speed brake handle for you.

**Comment by nguyenquyhy** [comment]
Right now I have a replay tool that does exactly that, which work correctly on aircraft other than the 32NX. I can think of a lot other applications that want to control spoiler too. That is basically why SimConnect is so useful and extensible.

If this problem is purely aesthetics and the team is not able to fix, I think we can just put it aside. It just looks weird when the handle doesn't move but the external spoiler does.

**Comment by ErickSharp** [comment]
> Right now I have a replay tool that does exactly that, which work correctly on aircraft other than the 32NX. I can think of a lot other applications that want to control spoiler too. That is basically why SimConnect is so useful and extensible.
> 
> If this problem is purely aesthetics and the team is not able to fix, I think we can just put it aside. It just looks weird when the handle doesn't move but the external spoiler does.

Yes, that seems like a good usage of this. I will look into it, thanks for mentioning : D

**Comment by nguyenquyhy** [comment]
Awesome. Many thanks for looking into small things like this, which make the 32NX the best aircraft so far.

**Comment by gizmo71** [comment]
The spoiler handle definitely _does_ move in the sim based on setting that variable - at least in the dev version of the A32NX. [Here](https://github.com/gizmo71/Wasmo/blob/main/Spoilerzmo/Spoilerzmo.cpp)'s some source which does just that.

One 'gotcha' is that if the ground spoilers are armed, the handle may not appear to move until you disarm them - then (IIRC) it'll jump to the selected position.

**Comment by jmihalich** [comment]
Yes that is exactly my experience using the brave throttle.  if it's armed, and i pull the lever on the throttle, the spoilers go up and down in the sim on the wings but lever on the pedestal does not move.  Once you unarm it by pulling it down in the cockpit, it moves correctly as i move the lever on the throttle.

**Comment by aguther** [comment]
Custom spoiler logic does not take this into account yet. If would be possible to allow overrides when a replay is running. Need a standard to make the logic aware. We will not do specific for every replay tool.

This kind of logic will also be needed for state save and load function. Until then working as intended.
