### ISSUE TITLE
[BUG] EIDW WAYPOINT REPEATED TWICE AND SKIPS APP WAYPOINTS

### ISSUE THREAD

**Issue by ebisettia** [flybywiresim/a32nx#3708]
**d6d5f02**

"built": "2021-02-24T14:59:32+00:00",
  "ref": "master",
  "sha": "d6d5f02a8676e4496b6082246796dfc8b7bf1425",
  "actor": "lukecologne",
  "event_name": "manual"

**EIDW WAYPOINT REPEATED TWICE AND SKIPS APP WAYPOINTS**
Hello: After creating my OFP in SIMBRIEF, I imported it to the MCDU and then to Navigraph, then completed the FP using the Navigraph's FP with the SID, STAR and APP on the MCDU. The FP was EGGL to EIDW. I encountered 2 issues. The first issue was that a waypoint that wasn't in the flight plan was added, curiously was EIDW after (DECEL) and BAGSO (image 1). I wasn't able to delete it, no matter how many times I tried, instead, every time I tried to delete it, MCDU deleted the waypoint before EIDW, every time. Then the issue N. 2 was that after KERAV waypoint, the MCDU selected EIDW (video 1) so I had to select the next waypoint manually, but, after that next waypoint I selected, MCDU selected went back to the waypoint BAGSO (video 2).

FP from Navigfraph: EGLL/27R CPT3F CPT UL9 KENET N14 MEDOG L18 ABLIN DCT BAGSO BAGS1K EIDW/KERAV.I16

![Microsoft Flight Simulator Screenshot 2021 02 23 - 18 46 23 85](https://user-images.githubusercontent.com/75552858/109082367-da70cc80-76d1-11eb-907a-8810a6420742.png)

https://drive.google.com/file/d/1sBPxAxEM6zwoOIumkxD0VbsigXemV9Va/view?usp=sharing
https://drive.google.com/file/d/1RBEndZilTY7SGH7_rP7rCaBwle0Jh6Oc/view?usp=sharing

**To Reproduce**

Issue No.1:
1. Create OFP at SIMBRIEF from EGLL to EIDW
2. Import it to the MCDU and Navigraph
3. Complete the FP with the SID, STAR and APP shown.
4. EIDW will appear twice.

Issue No. 2:
1. Flight the waypoints to KERAV and after that waypoint, MCDU will skip to EIDW.
2. Select the next waypoint and flight to it, and MCDU will skip it to BAGSO

**Expected behavior**
There shouldn't be an EIDW waypoint repeated
AP must follow all waypoints sequentially

**Actual behavior**
MCDU created EIDW waypoint twice and won't allow me to delete it.
AP didn't follow the waypoints sequentially.

Was this working before/when did the issue start occurring? - Not sure, it was my first time flying that FP.

Is this a problem in the vanilla unmodded game? - I'm not sure, I stopped using it a long time ago.

Discord username: ebisettiayala

PS.- I hope I was clear with my issue, English is not my first language, I just wanna help. Cheers from Peru, South America.

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by AthleticEggplant** [comment]
I have seen similar issues. One that is common for me is if the are waypoints on the arrival that are along side(Downwind) the approach. It decides its faster to just go to the closest one rather than following the way points. Turning final much to close.

**Comment by 2hwk** [comment]
Fixed by 4953 closing ☑️
