### ISSUE TITLE
[BUG] Spoilers won't automatically retract after landing

### ISSUE THREAD

**Issue by ErikNL80** [flybywiresim/a32nx#3709]
**Mod Version**

  "built": "2021-02-24T23:55:45+00:00",
  "ref": "master",
  "sha": "525dc7c817da20b8c16dd0d674649c2cb12de511",
  "actor": "wpine215",
  "event_name": "manual"

**Describe the bug**

After landing the spoilers need to be manually retracted, instead of retracting automatically when thrust is in idle or higher. The flight_model.cfg file contains this line: auto_spoiler_auto_retracts = 0 ; Auto spoilers retracts automatically true/false Setting the value to 1 solves the issue, would be nice to have this included as default (see references).

**To Reproduce**

1. Spawn at approach
2. Land the plane
3. Monitor spoiler behaviour

**Expected behavior**

I would expect the spoilers to retract automaticaly when thrust goed to idle and above.

**Actual behavior**

Spoilers remain up, and need to be retracted manually.

**References**

http://www.a320dp.com/A320_DP/flight-controls/sys-7.10.2.html

**Additional context**

N/A

Was this working before/when did the issue start occurring?
Yes, after a change in the flight_model this is not working anymore.

Is this a problem in the vanilla unmodded game?
No.

Discord username (if different from GitHub):

**Comment by Awemeter** [comment]
In real life you have to retract manually.

**Comment by ErikNL80** [comment]
> In real life you have to retract manually.

Thanks! But in the link above it says "The ground spoilers retract when the thrust levers are at idle and the speed brake lever is disarmed, or when at least one thrust lever is above idle."

**Comment by Awemeter** [comment]
This is a ceo reference not the neo. Also the speed brake disarm is a signal that is used irl. This tells the pilot monitoring to start the after landing flows.

**Comment by Benjozork** [comment]
> Thanks! But in the link above it says "The ground spoilers retract when the thrust levers are at idle and the speed brake lever is disarmed, or when at least one thrust lever is above idle."

Which exactly of those two conditions you observe isn't met? Please be more specific.

**Comment by lukecologne** [comment]
Duplicate #791. Will probably only be resolved with custom ground spoiler logic
