### ISSUE TITLE
[BUG] Massive drop in fps - Performance issues

### ISSUE THREAD

**Issue by tush0701** [flybywiresim/a32nx#3710]
**Mod Version**
{
  "built": "2021-02-24T23:55:45+00:00",
  "ref": "master",
  "sha": "525dc7c817da20b8c16dd0d674649c2cb12de511",
  "actor": "wpine215",
  "event_name": "manual"
}

**Describe the bug**
The cockpit view has been causing the fps to drop significantly even near scantily populated airports. FPS drop disappears as soon as cockpit view is removed(e.g. External view is enabled). It might have something to do with the custom textures.
VRAM usage also increases in the cockpit view.

**To Reproduce**

1. Spawn in A32NX at any airport
2.  Toggle cockpit view and check framerate

**Expected behavior**
Smooth performance and optimal framerate as per hardware

**Actual behavior**
VRAM usage is increased while in cockpit view, and FPS reduces significantly

**References**

**Additional context**
AMD Ryzen5 3550H 
16GB RAM
Raedon 560X 4GB VRAM
512GB SDD
Medium settings

Was this working before/when did the issue start occurring?
After texture changes

Is this a problem in the vanilla unmodded game?

No, and other planes/ A320NEO without the mod run fine.

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Your system is below minimum graphics spec.

**Comment by tush0701** [comment]
Hi, but it runs fine around 20fps for other airplanes, and even A320 vanilla. It used to be smooth even for previous versions of A32NX. Could you please help me?

Thanks in advance

**Comment by Benjozork** [comment]
> With the new versions, it drops down to 8 fps.

Can you provide a screenshot of your FPS counter ?

Our testing shows the new textures do not have a performance impact for above spec users.

**Comment by Viopassch** [comment]
I got the same Issue. With the version "built": "2021-02-24T23:55:45+00:00" it drops from 25fps to 10fps in cockpit view.

AMD Ryzen 7
32GB RAM
Nvidia GTX 1070
512GB SDD
Medium settings

**Comment by Benjozork** [comment]
Please show your MSFS FPS counter otherwise this is little help for us to diagnose the issue.

**Comment by scottfranks84** [comment]
Hi there. I have also noticed a drop in FPS and alot more jitters. I flew SFO-JFK and even at FL370 I was only getting around 32 FPS where I used to get nearly 50. Arriving into JFK I was getting 22 FPS where is would normally be over 30 and alot of jitters. Not very smooth. My specs are;

Intel core i9-10900K
32GB RAM
4TB hDD  1TB SSD
ROG STRIX RTX 2080Ti

**Comment by tush0701** [comment]
I suppose this issue is now occurring for other users except for me too, so please have a look into it devs.

Thank you for the amazing work with A32NX!

**Comment by Benjozork** [comment]
Please show the **MSFS DevMode FPS counter, not any external apps.* Without that we cannot see the source of the lag.

**Comment by SergeySoprykin** [comment]
Confirm fps drop. It happened twice on ground and on approach. The drop was significant and clearly seen (from ~30 to 7 fps).

**Comment by mikecbr** [comment]
same to me , i have a high end

**Comment by CBGonzalez** [comment]
After the UK update I´m recurrent performance drops / stutters with many aircraft, not only the A32NX. Ryzen 3700X / Radeon 5700XT

**Comment by LordNecton** [comment]
Yeah since the UK update Flying in VR in any aircraft is a no go for me right now, And flat screen iv had to lower a few settings to stop stutters 
Specs  i7 9700k RTX 3080  32GB ram

**Comment by tush0701** [comment]
From reading the comments, it seems that the issue is for all after the UK update, and is not only occuring for A32NX Mod.

Hence, I wouls like to close the ticket.

Thank you.
