### ISSUE TITLE
[BUG] Normal maps too prominent in some lighting conditions

### ISSUE THREAD

**Issue by jmwebslave** [flybywiresim/a32nx#3711]
**Mod Version** 
{
  "built": "2021-02-24T23:55:45+00:00",
  "ref": "master",
  "sha": "525dc7c817da20b8c16dd0d674649c2cb12de511",
  "actor": "wpine215",
  "event_name": "manual"
}

**Describe the bug**
Having read about the updates from PR #3707 I was interested to see the new cockpit view. Whilst I'm not a pilot of the aircraft, to my eye the texture/map looks very prominent and large, and potentially is stretched across multiple faces.

![image](https://user-images.githubusercontent.com/6118262/109148334-3f9fed00-77ba-11eb-9a5b-827b1322c3d8.png)

Apologies if this is just my ignorance of the actual aircraft, it just didn't feel 'right'.

**To Reproduce**
1. Spawn C&D, weather as shown below
2. Observe

![image](https://user-images.githubusercontent.com/6118262/109148547-84c41f00-77ba-11eb-8a93-7d1d91d0c41d.png)

**Expected behavior**
At this sort of distance I didn't expect natural creases in leather/material to be so large/prominent.

**Actual behavior**
![image](https://user-images.githubusercontent.com/6118262/109148647-a3c2b100-77ba-11eb-8b04-2392ccf2f183.png)

**References**
Couldn't find any good ones to reference against.  This video (https://www.youtube.com/watch?v=cv41hm4JEB8) doesn't really give an ideal video of it, but it doesn't jump out either.

**Additional context**

Was this working before/when did the issue start occurring?
After PR #3707 

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub): Webslave#8201

**Comment by hotshotp** [comment]
This is correct and looks like the real life leather. This has been tweaked with real pilot feedback and is correct.

**Comment by mohcheb** [comment]
hi,
I concur what @jmwebslave mentioned in his comment above.
the normal map should definitely be toned down. It is too prominent/ overkill. all textures including leather and metal trims are too rough and does not look natural.
