### ISSUE TITLE
[BUG] Thrustmaster TCA Add On - Auto-Brake does not work

### ISSUE THREAD

**Issue by TomMuc1** [flybywiresim/a32nx#3713]
**Mod Version**
v0.5.3 and actual master

**Describe the bug**
Thrustmaster TCA Add On - Auto-Brake does not work at all and speedbreak lever only after mouse-click on lever in cockpit. 

**To Reproduce**
like described above

**Expected behavior**
obviously - auto-brake works in standard asobo a320. speedbrake same bug in asobo a320.

**Actual behavior**
like described above

**References**
not needed

**Comment by Naviador** [comment]
Buenos dias.
Yo llevo el mismo problema que el que posteo el fallo.
El fallo desaparece cuando se desintala vuestro mod. 
ya funciona perfectamente al instante. 
con otros aviones como Boing 747 787 jets etc probado funciona correctamente. sin alteraciones ni fallos.
Solo cuando cargo el A320 NX. Sucede el error con la mascara original de serie.
Luego si quito el mod ya funciona correctamente. Probable mente al meter los parametros sobre cabina. ASOBO studio y vosotros cargais los mismos parametros.

PD: Se puede activar de mala manera el revers pero luego el mando se vuelve loco y ademas se engancha en la posicion solo revers. A mi me ha pasado eso  probando añadir comandos a los ejes.

**Comment by tracernz** [comment]
The big problem is that the add-on is still not available so unless somebody that already has one can fix up that PR...

**Comment by sidnov** [comment]
Fixed with https://github.com/flybywiresim/a32nx/pull/5584
