### ISSUE TITLE
No waypints on Fly pln page

### ISSUE THREAD

**Issue by Gnacino** [flybywiresim/a32nx#3716]
Cannot open Flight plan page and no waypionts are shown between departure and arrival airports either using Simbreif or MSFS.
Gnacino

**Comment by Benjozork** [comment]
You delete the provided template.

**Comment by Gnacino** [comment]
I didn't see any template.  I just reported the problem in the box provided like it is here.
Gnacino

**Comment by Benjozork** [comment]
![image](https://user-images.githubusercontent.com/4503241/109214085-65f46700-777f-11eb-8389-942447661986.png)
