### ISSUE TITLE
The line in the middle of the switches is lided on the overhead panel

### ISSUE THREAD

**Issue by Chirodes** [flybywiresim/a32nx#3717]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**

**References**

https://www.youtube.com/watch?v=myBmuhsJf90&t=791s
**Additional context**
https://www.youtube.com/watch?v=myBmuhsJf90&t=791s

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
You didn't respect the template and I don't understand what you're asking.

Also your reference is from an old A320 with CRT screens.
