### ISSUE TITLE
AIRCRAFT CHARACTERISTICS AIRPORT AND MAINTENANCE PLANNING

### ISSUE THREAD

**Issue by Chirodes** [flybywiresim/a32nx#3718]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**

**References**

[Airbus-Commercial-Aircraft-AC-A320.pdf](https://github.com/flybywiresim/a32nx/files/6045130/Airbus-Commercial-Aircraft-AC-A320.pdf)

**Additional context**

Discord username (if different from GitHub):
Chirodes
**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
What's your feature request??
