### ISSUE TITLE
[REQUEST] DME distances missing in lower ND

### ISSUE THREAD

**Issue by ohnoitsBlarry** [flybywiresim/a32nx#372]
Both VOR indicators in the lower left and right corner of the ND don't show the distance to the selected VOR/DME, as they would on the real-word aircraft. Monitoring distance to and from Navaids is quite necessary for IFR flight, with many airport approach procedures requiring working DME equipment.

**Describe the features you'd like to see implemented**
A simple 'xx.x NM' line of text below the VOR indicators in the lower left and right corners of the ND, with the distance in green text and 'NM' in teal. 

**Additional context**
Attached is a photo of the real-world aircraft's ND, showing the distance to the VOR/DME selected in the FMS/radio panel.
![A320ND](https://user-images.githubusercontent.com/70750265/92223666-15234600-eea1-11ea-9718-95367a3c3083.png)

**Comment by e4rthdog** [comment]
A must! I confirm that this is valid also to my setup
