### ISSUE TITLE
[BUG] Simbrief FPLN doesn't load in altitudes properly

### ISSUE THREAD

**Issue by crgmu** [flybywiresim/a32nx#3720]
**Mod Version**
{
  "built": "2021-02-25T21:43:01+00:00",
  "ref": "master",
  "sha": "472cf527726e63d24e95608b6ac66d3430ffaacb",
  "actor": "Benjozork",
  "event_name": "manual"
}

**Describe the bug**
When importing a flight plan from Simbrief the waypoint altitudes are not properly imported. Waypoint shows cruising altitude, even though still in climb phase. Descent waypoints tend to work fine. Must go through to manually adjust altitude cstr, however this breaks ATC and causes it to not give instructions after clearing to departure altitude.

**To Reproduce**
1. Generate OFP in Simbrief, recent flights have been EGPK-EGLL, EGAC-EGKK, EHAM-EGLL, however all flights replicate issue.
2. Load OFP via MCDU, can either go through INIT and request immediately or go through ATSU>AOC MENU>INIT (both replicate it)
3. Navigate to F-PLN, issue is on page
(FOR ATC ISSUE)
4. Adjust altitude cstr for each waypoint
5. Startup procedure, request clearance, taxi, etc.
6. On initial climb-out, ATC will give an altitude clearance - gives no further altitude clearances after

**Expected behavior**
Correct altitudes are imported via Simbrief, ATC responds with clearances

**Actual behavior**
Altitudes imported are incorrect, ATC does not give additional clearances after first clearance on climb-out (only frequency changes)

**References**
Will add video to thread after test flight this evening.

Was this working before/when did the issue start occurring?
Worked previously, issue began occurring approx. 2-3 weeks ago. Original issue placed waypoints out of order (or missing waypoints) along with altitude issue, missing waypoints was fixed on updated dev release.

Is this a problem in the vanilla unmodded game?
Unknown, presuming not since no simbrief integration with unmodded

Discord username (if different from GitHub): apglegalish#8792

**Comment by tracernz** [comment]
It wouldn't make sense to import altitudes from SimBrief (other than cruise, and in future step alts) as they are estimates only, and the aircraft determines it's climb/descent profile in real time based on a number of factors. Constraints come from SIDs and STARs which are not imported from SimBrief, but selected from within the F-PLN page afterwards, with data sourced from the sim nav-data.

**Comment by MisterChocker** [comment]
Closing since this is not a real issue.
