### ISSUE TITLE
[BUG] CChord working wrong

### ISSUE THREAD

**Issue by Kimbyeoungjang** [flybywiresim/a32nx#3721]
**Mod Version**

current master

**Describe the bug**

When capture G/S, sometimes Cchord is not inhibit.

It fixed on Custom Autopilot(Caused by current FMA. I think it changed sometimes slowly so Cchord can't recognize G/S Caputred).

this is just issue upload for current "master"

**To Reproduce**

1. capture G/S
2. manually follow G/S
3. check Cchord.

**Expected behavior**

do not working

**Actual behavior**

sometimes working

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
no

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Please follow the template
