### ISSUE TITLE
MCDU STAR inputs in flight

### ISSUE THREAD

**Issue by Rick-Briggs** [flybywiresim/a32nx#3722]
When approaching a destination airport and leaving ATC to inform you of the approach and runway in use, entering the runway and transition information into the MCDU from ATC often causes the aircraft to circle back to an earlier waypoint. I am guessing this is because you sometimes have already passed the transition waypoint. The only way to prevent this seems to be to insert a 'direct to' through the MCDU to the next waypoint in the flightplan. The problem with this is that once the aircraft reaches that waypoint it seems to have lost connection to the flightplan and wanders off course.

**Comment by Benjozork** [comment]
Does not follow provided issue template

**Comment by Rick-Briggs** [comment]
As a retired Senior Software Testing Consultant I think I know how to report a defect. What's your problem?

**Comment by xRaynex** [comment]
Maybe if you followed the biiiig 'ol template it gave you when you started to report an issue. I feel like if you've been in any sort of software business you should be aware that templates are pretty common boilerplate to follow.

**Comment by Benjozork** [comment]
> As a retired Senior Software Testing Consultant I think I know how to report a defect. What's your problem?

You're telling me a Senior Software Testing Consultant is unable to provide a build number, reproduction steps, expected and actual behaviour in a testing report ?
