### ISSUE TITLE
[BUG] Master Alarm for TakeOff with Parking Brake on cannot be switched off

### ISSUE THREAD

**Issue by OFC1983** [flybywiresim/a32nx#3727]
**Mod Version**
  "built": "2021-02-25T21:43:01+00:00",
  "ref": "master",
  "sha": "472cf527726e63d24e95608b6ac66d3430ffaacb",
  "actor": "Benjozork",
  "event_name": "manual"

**Describe the bug**
The Master Caution Alert cannot be switched off, when on a Runway, setting Thrust to TakeOff and having the Parking Brake still set to on.

**To Reproduce**
1. Load a new flight on any runway at any airport
2. Set Thrust to TakeOff or Max and leave the Parking Brake on
3. Try to disable the alarm - it won't switch off, even if you set the parking brake to off and try again.

**Expected behavior**
Master alarm can be cleared and alarm sound disappears

**Actual behavior**
Master alarm remains on all the time

**References**
- none

**Additional context**

Was this working before/when did the issue start occurring?
Haven't tried this for a very long time, but it used to work fine.

Is this a problem in the vanilla unmodded game?
No, a master alarm does not appear in the unmodded game at all.

**Comment by Kimbyeoungjang** [comment]
this will be fixed on #3288

**Comment by beheh** [comment]
For clarification, the alarm should not go away if you unset the parking brake, intentionally (that's an FWC behaviour). However it should be mutable by pressing the Master Warning button. Right now you can clear it by pressing the CLR button.

**Comment by sidnov** [comment]
#4770 fixes this

cc: @davidwalschots
