### ISSUE TITLE
[REQUEST] Keep customized placard when updating via installer

### ISSUE THREAD

**Issue by frankkopp** [flybywiresim/a32nx#3734]
**Is your feature request related to a problem? Please describe.**
Updates overwrite a customized placard. When using dev or exp this means to re-do the customization after each update (at least copy the already customized placard into the mod)

**Describe the feature you'd like to see implemented**
Keep a customized placard when updating (e.g. by moving the file to tmp then do the update and move it back)

Discord username (if different from GitHub): Cdr_Maverick

**Comment by hotshotp** [comment]
this is not the installer repo

**Comment by tracernz** [comment]
The best way is for the placard texture to reside in another package e.g. the livery it belongs with.
