### ISSUE TITLE
Aircraft Swaying Subtly During Cruise

### ISSUE THREAD

**Issue by captainjohn73** [flybywiresim/a32nx#3736]
**Mod Version**

"2021-02-26T15:49:39+00:00"

**Describe the bug**

The aircraft rolls gently to the left and right while tracking waypoints. It's been happening for a number of versions now. I've flown in different locations with different weather at different times during the past week and the swaying is there intermittently. 
**To Reproduce**

Just fly a flight with a flightplan and autopilot on with live weather active. 

1. Noticed the swaying while flying the flight plan
2.
3.

**Expected behavior**

Smooth flight

**Actual behavior**

Gentle rocking back and forth intermittently
**References**

**Additional context**

Was this working before/when did the issue start occurring?

I thought the swaying stopped weeks ago, but I could be wrong. I just started to notice it this week during normal flights. 

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
This will be resolved with the custom autopilot, and cannot be fixed by us while the default autopilot is there.

**Comment by captainjohn73** [comment]
Great, thanks for the update and thanks for everything you are doing.
