### ISSUE TITLE
ECAM Panel button light should go off if select twice

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#3738]
**Mod Version**

DEV + FBW

**Describe the bug**

If you select a ECAM page by the ECAM panel, the selected button is eluminated and shows the associated ECAM page. Works great.
->BUT if you select it again, the light should go off and no ECAM button light sould be on. The page-logic, that it shows the page with the highest priority in relation to the actual flight phase is correct and also works good. But the button-light from the previous selected page remains on. 

**To Reproduce**

1.start up cold and dark
2.select a radom ecam page
3.select it twice -> button stays illuminated

**Expected behavior**

if you select a button twice, it should go off.

**Actual behavior**

button light remains on, untill you select an other page.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
can´t remember
Is this a problem in the vanilla unmodded game?
i don´t know

Discord username (if different from GitHub):

**Comment by beheh** [comment]
Will be fixed by #3735.

**Comment by andrejetcat** [comment]
Sorry, I didn't properly search for this problem before posting that! :) I thought it was a new one

**Comment by beheh** [comment]
This bug report is fine, I merely linked the pull request that fixes the issue from this report.
