### ISSUE TITLE
I want Flypad to be able to display any image I want.

### ISSUE THREAD

**Issue by Risechocolate** [flybywiresim/a32nx#3740]
I'd like to be able to display any png or jpg image I want on Flypad, like the PMDG Boeing 777 Addon and other addons.

**Comment by MisterChocker** [comment]
Please follow the use the [feature request](https://github.com/flybywiresim/a32nx/issues/new?assignees=&labels=Bug&template=bug_report.md&title=%5BBUG%5D+INSERT+TITLE+HERE) or [bug report](https://github.com/flybywiresim/a32nx/issues/new?assignees=&labels=Bug&template=bug_report.md&title=%5BBUG%5D+INSERT+TITLE+HERE) template to open issues.
