### ISSUE TITLE
[BUG] Entered transponder code is not visible

### ISSUE THREAD

**Issue by BjoernHund** [flybywiresim/a32nx#3754]
**Mod Version**

```json
{
  "built": "2021-02-27T17:01:19+00:00",
  "ref": "master",
  "sha": "7873fcd87260361af50357744829dd3f17a4ff51",
  "actor": "beheh",
  "event_name": "manual"
}
```

**Describe the bug**
Enter a transponder code does not change it. It is still 7000

**To Reproduce**

1. Go to a gate of your choice
2. Startup the batteries / external power
3. Enter a new transponder code
4. The transponder code is still 7000

**Expected behavior**

The entered transponder code is visible in the display

**Actual behavior**
The visible transponder code is still 7000

**References**

In the next flight I will take a screenshot

**Additional context**

Was this working before/when did the issue start occurring?
It was working before PR #3675 

Is this a problem in the vanilla unmodded game?
Not tested.

Discord username (if different from GitHub): Björn#7582

**Comment by tracernz** [comment]
Hit clear twice, then enter.

**Comment by BjoernHund** [comment]
Thx works like a charm.
