### ISSUE TITLE
[BUG] A320 Autopilot non functional and constant AP Chirps

### ISSUE THREAD

**Issue by mangotree333** [flybywiresim/a32nx#3756]
**Mod Version**

**Describe the bug**
I take off and start to hear the autopilot chirps and cant either turn it off or on, it appears to be cycling through on/off and either pressing the AP button with the mouse click or pressing Z does nothing? ,I tried the default model and issue is replicated there also

**To Reproduce**

1.  Take off and AP does not work? not sure what else you need?
2.
3.

**Expected behavior**
AP to function and be able to be turned off and on, not matter what i press the AP chirps are always present...

**Actual behavior**
Just hear AP chirps and cant do anything to remedy the situation

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game? yes exact same issue for me!

Discord username (if different from GitHub):

**Comment by FrankDevin-dev** [comment]
did you set any deadzones in your controls sensitivity? If not, please set a deadzone of like 3% and then try again

**Comment by Benjozork** [comment]
@FrankDevin-dev this is not the deadzone issue

@mangotree333 it seems like you have some weird keybindings

**Comment by Benjozork** [comment]
Since this is not an A32NX issue, I will close the ticket. Please use our #help channel for support.

**Comment by mangotree333** [comment]
what sort of key bindings nothing is set to AP except default Z key?
