### ISSUE TITLE
[BUG] stable version is not seen by simulator

### ISSUE THREAD

**Issue by renzfe** [flybywiresim/a32nx#3757]
**Mod Version**
0.5.3

**Describe the bug**
I installed using official installer. The mod is not seen by simulator. Everything works if I swith to development version.

**To Reproduce**
1. Install the version using installer
2.start the simulator
3. check specific feature. for example the new ipad and it is not present.

**Expected behavior**
The mod working

**Actual behavior**
The mod is not available

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
Yes

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
The stable version does not contain the flyPad. Please read the changelog.

**Comment by renzfe** [comment]
Oh. Sorry for the mistake. Correct.
