### ISSUE TITLE
[BUG] ILS issue, Glide Scope not descending or turning green unless I disconnect the Autopilot.

### ISSUE THREAD

**Issue by SyphiliticWeasel** [flybywiresim/a32nx#3759]
I am using the latest custom FBW a320 and since the update to the sim, the LOC now takes me a good 100 feet to the left or right of the runway. 

The APPR G/S or turns green if I disconnect the AP and then it does not descend I just keep flying around aimlessly.

I have made sure all the assists are off and that I manually enter the correct ILS frequency before I even depart the airport...

**Comment by Benjozork** [comment]
Please do not ignore the provided issue template.
