### ISSUE TITLE
[BUG] ILS not working. 

### ISSUE THREAD

**Issue by SyphiliticWeasel** [flybywiresim/a32nx#3761]
**Mod Version**

Unstable Master Branch Build (with custom FBW)

**Describe the bug**
When turning on the LOC the plane will be off the runway to the left or right sometimes by a few hundred feet. 

The glide scope with not turn green unless the autopilot is turned off but then the plane does not descend and just flies around. 

**To Reproduce**
1. Use ILS 01L at KLAS or any other airport so far. 

**Expected behavior**
Prior to MSFS update the LOC would line up with the runway and the glide scope would turn green with the AP on and the plane would descend on its own. 

**Actual behavior**
The plane will be far off the runway to the left or right. The APPR turns the G/S blue and to make it green I must turn off the AP but then the plane doesn’t descend or flow the flight plan so I have to hand fly the plane. 

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Started after the world update 3. 

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by mreza1st** [comment]
Yeah I think the recent dev. version has some issues with approach and ILS. I also had plan turning randomly and not following the path during the approach. Had to switch to control heading. I am sure it will get fixed soon.

**Comment by ukflyer** [comment]
is there also an issue with autoland, cant seem to engage AP1+2

**Comment by ChruutvoLuzi** [comment]
> is there also an issue with autoland, cant seem to engage AP1+2

thats only available in the custom autopilot branch

**Comment by ukflyer** [comment]
> > is there also an issue with autoland, cant seem to engage AP1+2
> 
> thats only available in the custom autopilot branch

I got the custom FBW version installed

**Comment by ChruutvoLuzi** [comment]
> > > is there also an issue with autoland, cant seem to engage AP1+2
> > 
> > 
> > thats only available in the custom autopilot branch
> 
> I got the custom FBW version installed

you need the custom autopilot not flybywire to have a working autoland
Its not in the installer yet but will be added soon

**Comment by ukflyer** [comment]
> > > > is there also an issue with autoland, cant seem to engage AP1+2
> > > 
> > > 
> > > thats only available in the custom autopilot branch
> > 
> > 
> > I got the custom FBW version installed
> 
> you need the custom autopilot not flybywire to have a working autoland
> Its not in the installer yet but will be added soon

ah see! Thank you

**Comment by Biniou671** [comment]
Looks like the ILS is broken, even with the **stable Version 0.5.3**.
After few flights on Dev. version and Stable version 0.5.3, for my side I can confirm I had no ILS captured, at least for the following airport:
EGLC; LIRQ; LIML; EGCC.

**Comment by Benjozork** [comment]
I cannot reproduce the issue here.

Can someone record a video which:

- shows the contents of the RAD NAV page prior to activating the localizer
- shows the FCU and PFD when activating the localizer

**Comment by MisterChocker** [comment]
Closing since no response.
