### ISSUE TITLE
Vitesse de l'A.320 en déplacement sur le tarmac

### ISSUE THREAD

**Issue by Tony5959** [flybywiresim/a32nx#3765]
Bonjour
Pouvez vous corriger la vitesse de déplacement de l'avion A320 FlyByWire lors de son déplacement sur le tarmac pour se diriger soit vers son lieu de stationnement ou son départ sur piste. En effet cet avion se déplace naturellement avec parfois plus de 30 noeuds sans toucher à la manette des gazs. C'est un problème qui existe depuis la création de cet avion. Merçi de vérifier et de prendre en considération ce bug. Antoine

**Comment by ImenesFBW** [comment]
Bonjour,

L'A320NEO se déplace au sol au ralenti, c'est-à-dire avec un comportement correct et fidèle à l'avion réel. Veuillez également utiliser l'anglais pour ouvrir les questions, car la communauté est internationale. 

Veuillez clore le sujet.

Bien à Vous

**Comment by Tony5959** [comment]
Hello, I'm sorry, but your plane is naturally moving at over 30 knots without touching the throttle while the speed limit for airplanes on the tarmac is less than 20 knots maximum. There is a bug on your plane that is moving at a gradual rate that can reach 30 knots and more. Thank you for checking my comments for no conclusive tests. Antony

**Comment by ThatRedMelon** [comment]
This is intended behaviour verified by IRL pilots. The specific engine we model (the CFM LEAP1A) has enough thrust at idle to accelerate to 30kts and more on a moderately light load.

**Comment by Tony5959** [comment]
Thank you for your reply. I would nevertheless like to congratulate you for the work accomplished on this aircraft. I remain skeptical about the fact that an A320 is naturally moving at more than 30 knots on the tarmac. It is an abnormal speed to react by the pilots on the unforeseen ones being on the tarmac. Good luck for the future and the evolution of your aircraft which deserves full satisfaction.

**Comment by lukecologne** [comment]
Of course neos will not actually always taxi at 30 knots, the pilots have to actively apply brakes if they want to taxi slower. This behaviour is confirmed by IRL neo pilots. Closing this issue as behaving as intended.
