### ISSUE TITLE
[REQUEST] ND in ARC mode missing VOR/ADF 1 and 2 needles

### ISSUE THREAD

**Issue by MattPaxtonBel** [flybywiresim/a32nx#377]
**Is your feature request related to a problem? Please describe.**
In addition to the missing DME distance on the ND in ARC mode, I also don't see the VOR or ADF needles when selected with the appropriate switch. 

**Describe the features you'd like to see implemented**
Would it be possible to add those needles ? 
**Additional context**
No additional context

**Comment by tareksabet** [comment]
Now the DME appears on ND but still the needles

**Comment by MisterChocker** [comment]
Using #3055 for tracking since it has more details.
