### ISSUE TITLE
ECAM EIS Text bug

### ISSUE THREAD

**Issue by ternium1** [flybywiresim/a32nx#3771]
**Version**
Custom FBW (72c965f)

**Describe the bug**
When Testing EIS using the MCDU, "Maintenance Mode" is printed small;
In test mode, the text color is not enough visible

**To Reproduce**
Test EIS 1,2,3 and on switching panel, Potentiometer n°3 should be set to either 1 or 3

**Expected Behaviour**
The text should be bigger in Maintenance Mode, and text should be darker in Test Mode

![ecam](https://user-images.githubusercontent.com/32877621/109539056-1edcdd80-7ac1-11eb-9385-504b459bc75f.png)
![ecam2](https://user-images.githubusercontent.com/32877621/109539060-1f757400-7ac1-11eb-8ce0-9ace19b295ea.png)

**Comment by sidnov** [comment]
Reproducible, have been looking for a fix for a bit. Should be ready by tomorrow

**Comment by sidnov** [comment]
Holding off on this, as it will be fixed sooner or later. The files around this function are quite messed up

**Comment by davidwalschots** [comment]
@sidnov has verified that the test mode has darker text now. The maintenance mode text is also bigger in all displays, but still unequal between PFD/ND and the MFD. So that part remains to be fixed 😀.

**Comment by juliansebline** [comment]
@davidwalschots Could someone check if it's still working ? I don't know how it works. I've managed to see the test mode once but couldn't once again.

@sidnov  @ternium1

**Comment by Maverickwoe** [comment]
I think this issue might need to be closed and or associated with a new issue to implement again this feature as the maintenance or test display do not appear anymore on the dev branch.
Test in progress but nothing shown
![image](https://user-images.githubusercontent.com/12175224/220983775-0084cc24-c2e5-49db-b92a-0d5a1faa3e5b.png)
