### ISSUE TITLE
Transponder code change procedure--NOT A BUG

### ISSUE THREAD

**Issue by Ash624** [flybywiresim/a32nx#3778]
Latest DEV version (03-02-21)caught me out. The transponder code cannot be changed just by direct input of new code like it used to be. The "CLR" button has to be pressed first I have found out. Just for Info

**Mod Version**

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Valastiri** [comment]
BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning

And this is not a forum for providing info. This is for reporting issues.
