### ISSUE TITLE
[Fix Flaps] When flaps 0 aircraft shouldn't be able to take off

### ISSUE THREAD

**Issue by Chirodes** [flybywiresim/a32nx#3781]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**

When using flaps 0 aircraft shouldn't be able to take off. The warning signs work fine but even so using flaps in 0 position shouldn't be able to take off.

**References**

**Additional context**

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by ChruutvoLuzi** [comment]
How do you mean shouldnt? Flaps 0 still gnerates Lift, it just requires a higher speed. Offcourse you wouldnt perform a T/O with Flaps zero but seen physically it is possible.

**Comment by Chirodes** [comment]
I'm not sure about A320. I mean it's a heavy aircraft and plus the payload loaded physically something is not right. If you have more info about flaps please check it out.

**Comment by ChruutvoLuzi** [comment]
> I'm not sure about A320. I mean it's a heavy aircraft and plus the payload loaded physically something is not right. If you have more info about flaps please check it out.

So what? After Take Off the A320 will fly with Flaps 0 aswell and does it descend? No

**Comment by Chirodes** [comment]
Check this out maybe you can uderstand it better. https://aviation.stackexchange.com/questions/42926/is-the-a320-family-allowed-to-take-off-with-the-flaps-retracted

**Comment by MisterChocker** [comment]
if this is a bug please open an bug report issue and follow the template.

**Comment by ChruutvoLuzi** [comment]
> Check this out maybe you can uderstand it better. https://aviation.stackexchange.com/questions/42926/is-the-a320-family-allowed-to-take-off-with-the-flaps-retracted

there is a difference between allowed and being able to do so.

**Comment by lukecologne** [comment]
> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning.

Pretty much every aircraft would be able to take off without flaps, given enough runway length to accelerate.

**Comment by andrejetcat** [comment]
as a real life Airbus Pilot, can confirm, it is not allowed, but it is physically possible, for shure! Even we train to land the Bus without flaps in case of an failure (only in the Sim). So, there should be the T/O warning, but it won´t prevent you from a takeoff.

**Comment by BritishAvgeek** [comment]
Shame we can't gif in Github

**Comment by St54Kevin** [comment]
Im also very unsure if in IRL the aircraft is even possible to take off with the front door being open. I think it should be able to take off at all because all the flight attendants and pilots would be sucked out as soon as you´ll reach 50+ knots.

**Comment by BritishAvgeek** [comment]
> Im also very unsure if in IRL the aircraft is even possible to take off with the front door being open. I think it should be able to take off at all because all the flight attendants and pilots would be sucked out as soon as you´ll reach 50+ knots.

and you wouldn't get your coffee
