### ISSUE TITLE
[BUG] ND (map) is no longer synchronized when I change the range

### ISSUE THREAD

**Issue by doggydogg13** [flybywiresim/a32nx#3791]
**Mod Version**

 Custom version

**Describe the bug**
 After 1 hour of flight, most of time on the approach or final approach (but can appears before), the captain ND (map) is no longer "alive" with my flight course. I have to check the FO ND to know where I am on the plan or on my STAR. Sometimes I just have to play with the range and it works again but last time, even if I change it, the ND wasn't alive till I land.

**To Reproduce**
 Start flight from LICJ  on a ramp with A32Nx custom (updated by the FBW app) / Import flight by MCDU from simbrief to LFKJ (ILS 02). Live weather. custom Livery
 
1. When I start to descent and going on approach, I used to change the range of the ND to get a better view on my STAR's waypoint and constraints.
2. Then the bug could appears randomly
3. ND is no longer alive whereas I play with the range button / Sometimes, randomly, when the ND is not alive, I change the range and it make it works well again.

**Expected behavior**
 ND has to be alive for the whole flight. Moreover if I change the range in/out, the ND has to zoom in/out. 

**Actual behavior**
 Randomly the ND stop being alive. When I turn the range in/out the ND doesn't zoom in/out.
But sometimes, when the ND is not alive, I change change the range and it make it works fine again.
Very strange.

**References**

**Additional context**

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by 2hwk** [comment]
Fixed by 4953 closing ☑️
