### ISSUE TITLE
[BUG] Arrival waypoints not loading fully

### ISSUE THREAD

**Issue by jcallum** [flybywiresim/a32nx#3792]
**Mod Version**

Custom FBW 

**Describe the bug**

Flying CYVR to CYEG - loaded the ESKIE2 arrival and RNAV Z 20 approach. The arrival was loaded up to waypoint APKIT and then went direct to DUDKO, the IAF for the approach. Missed three intermediate waypoints.

**To Reproduce**

1. Reflew the flight
2.
3.

**Expected behavior**

Should have inserted three more waypoints at the end of the arrival.

**Actual behavior**

Ignored three waypoints

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):
jcallum

**Comment by MisterChocker** [comment]
Please post the content of the build_info.json

**Comment by jcallum** [comment]
Contents of build_info.json
{
  "built": "2021-03-04T06:16:21+00:00",
  "ref": "fbw",
  "sha": "8e54ce5d332afb1b7a1d4535c2fab75eab61f6ab",
  "actor": "aguther",
  "event_name": "manual"
}

**Comment by 2hwk** [comment]
Fixed by #4953 closing ☑️
