### ISSUE TITLE
[REQUEST]  Tail illumination intensity is too high

### ISSUE THREAD

**Issue by nikron1986** [flybywiresim/a32nx#3793]
Tail illumination intensity is too high
Please convert lighting to a more realistic glow
the brightness is too great and it should not be so
![22](https://user-images.githubusercontent.com/25241172/109872067-f4d01a80-7c7c-11eb-97cc-230d610aa0ae.JPG)
![33](https://user-images.githubusercontent.com/25241172/109872069-f6014780-7c7c-11eb-8b06-f1b87d43c224.JPG)

**Comment by beheh** [comment]
Please follow the template.

**Comment by hotshotp** [comment]
Fixed in dev version

**Comment by Snapmatics** [comment]
Hey mate, you are using a very old version. Please download the latest dev/or custom FBW.

![image](https://user-images.githubusercontent.com/43104362/109874765-3611fb80-7c78-11eb-81af-10a08e06e844.png)
![image](https://user-images.githubusercontent.com/43104362/109874816-4cb85280-7c78-11eb-9ee3-6b07a55aa9f2.png)

**Comment by nikron1986** [comment]
![444](https://user-images.githubusercontent.com/25241172/110101901-2d730f80-7db5-11eb-82eb-bfb8151a5e73.JPG)
downloaded the current dev version the problem with tail lighting remained
