### ISSUE TITLE
[BUG] Seatbelt switch detection with CABIN SEATBELTS ALERT SWITCH

### ISSUE THREAD

**Issue by Vdrummer-td12** [flybywiresim/a32nx#3803]
**Mod Version**

latest stable and custom version

**Describe the bug**

cannot read seatbelt switch through simconnect with 'CABIN SEATBELTS ALERT SWITCH', works in the vanilla A320

**To Reproduce**

in python (need to install simconnect)
sm = SimConnect()
aq = AircraftRequests(sm, _time=0)
sleep(2) #wait for sim connect
beacon = aq.get('LIGHT_BEACON')
print('beacon light = ',beacon)  #-->this works
seatbelt = aq.get('CABIN_SEATBELTS_ALERT_SWITCH')
print('Seatbelt sign = ',seatbelt ) #-->no joy

**Expected behavior**

should change from False to True depending on switch position

**Actual behavior**

always reads False

**References**

none

**Additional context**

Was this working before/when did the issue start occurring? don't know, just used now

Is this a problem in the vanilla unmodded game? works in the vanilla A320

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment]
This is the simvar used by us `L:XMLVAR_SWITCH_OVHD_INTLT_SEATBELT_Position`.

Not sure if this is appropriate to be discussed on github, you might want to hop onto our discord server.

**Comment by Vdrummer-td12** [comment]
where in you discord would be the appropriate place to start a discussion on this topic?

**Comment by MisterChocker** [comment]
Maybe system/general-sys

**Comment by MisterChocker** [comment]
Closing issue. Continuing discussion on dc.
