### ISSUE TITLE
Fuel Efficiency wrong

### ISSUE THREAD

**Issue by Road-to-Hell9** [flybywiresim/a32nx#3806]
**Mod Version**
A32NX-master 77e6042

**Describe the bug**
Fuel Efficiency wrong uses way to little fuel, less than 50% of intended

**To Reproduce**
1.File FP on Simbrieg with A320NX airframe
2.Start flight
3.Land

**Expected behavior**
Usage from LOWW - EDDM should have been about 2100 KG

**Actual behavior**
Usage from LOWW - EDDM actually 800 KG

Was this working before/when did the issue start occurring?
Was working before the World Update England

Is this a problem in the vanilla unmodded game?
N/A

**Comment by Benjozork** [comment]
Issue does not reference IRL data

**Comment by Road-to-Hell9** [comment]
Could you maybe explain what IRL means

**Comment by Benjozork** [comment]
in real life. as in, real life data which proves there is a problem with the fuel efficiency

**Comment by Road-to-Hell9** [comment]
Are you saying that this could be accurate fuel consumption or that you aren't sure, because before the world update the fuel usage was very different

**Comment by Benjozork** [comment]
I am saying that you are claiming something is inaccurate without any evidence or pointers towards correct values.

**Comment by Road-to-Hell9** [comment]
I am just comparing the Simbrief profile provided by the FBW team with an actual flight

**Comment by Benjozork** [comment]
Well, the issue could then be with the simBrief profile.

**Comment by Road-to-Hell9** [comment]
I just don't know, can't get any answers from the Internet. I only noticed an extream drop in fuel consumption after World update which I noticed because the FBW simbrief profile was accurate beforehand

**Comment by MisterChocker** [comment]
Duplicate of #2206
