### ISSUE TITLE
[BUG] Can't insert squawk

### ISSUE THREAD

**Issue by Kimbyeoungjang** [flybywiresim/a32nx#3807]
**Mod Version**

download via installer, custom fbw

{
  "built": "2021-03-04T06:16:21+00:00",
  "ref": "fbw",
  "sha": "8e54ce5d332afb1b7a1d4535c2fab75eab61f6ab",
  "actor": "aguther",
  "event_name": "manual"
}

**Describe the bug**

if you insert squawk 0006(provided by ATC), it can't insert 0006. displayed 006

if press 000, showed normally, and insert 6, 3rd 0 changed to 6 so finally displayed 006.

**To Reproduce**

1. spawn on aircraft
2. squawk set to 0006 or other number like 0001
3. 

**Expected behavior**

should set to 0006

**Actual behavior**

![image](https://user-images.githubusercontent.com/23118756/110047951-2be42000-7d92-11eb-9572-c6368c807439.png)

set to 006

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by lukecologne** [comment]
I have opened a PR to fix this issue

**Comment by Kimbyeoungjang** [comment]
> I have opened a PR to fix this issue

one more, before version(before react i think?), if there is a squawk code already, can insert.

Like there is a squawk code 1234, on that situation, i add new number like 5678, can duplicate on 1234.
But now, should press CLR twice due to remove all numbers. is it correct behavior?

**Comment by lukecologne** [comment]
Yes, you need to press clear when entering a new code.

**Comment by Kimbyeoungjang** [comment]
ok! thank you for fix this :)!

**Comment by lukecologne** [comment]
No problem, thank you for reporting!
