### ISSUE TITLE
[BUG] downloaded the current dev version the problem with tail lighting remained

### ISSUE THREAD

**Issue by nikron1986** [flybywiresim/a32nx#3809]
**Mod Version**

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by nikron1986** [comment]
![444](https://user-images.githubusercontent.com/25241172/110102114-6d39f700-7db5-11eb-8ff1-70608ea26489.JPG)
downloaded the current dev version the problem with tail lighting remained

**Comment by nikron1986** [comment]
downloaded the current dev version the problem with tail lighting remained
light falls on the lower part of the fisilage under the tail. this is not correct

**Comment by beheh** [comment]
Once again, **please follow the template**. Read and understand each part of it, and fill out the required information before submitting your bug. Between Discord and GitHub we get dozens of issues reported per day, and we can't chase issues where we're missing crucial information like exactly which version you were using.

> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning
