### ISSUE TITLE
[BUG]  OP CLB mode does not use the manually set speed

### ISSUE THREAD

**Issue by squashplayer** [flybywiresim/a32nx#3815]
**Mod Version**
0.5.3

**Describe the bug**
After activating OP CLB mode and setting a speed, for example 290 kts, the plane continues at 250 kts.

**To Reproduce**
1. Takeoff
2. Engage OP CLB mode
3. Set a speed, for example 290 kts

**Expected behavior**
I expected that the plane follows OP CLB mode using the 290 kts which I manually set

**Actual behavior**
Plane follows OP CLB mode at 250 kts

**References**
https://imgur.com/a/V9yE9vV

**Additional context**
This seems to happen not every time.

**Comment by MisterChocker** [comment]
Works on current master (dev)

**Comment by MisterChocker** [comment]
Closing since issue does not persist.
