### ISSUE TITLE
[BUG] Estimated fuel at destination EFOB shows current fuel

### ISSUE THREAD

**Issue by squashplayer** [flybywiresim/a32nx#3816]
**Mod Version**
0.5.3 stable

**Describe the bug**
In the FMS, the calculated fuel at destination shows the current fuel instead of calculated fuel at destination

**To Reproduce**
1. Start a flight
2. Fuel the aircraft
3. Program the FMS
4. On the F-PLN page, look at the EFOB on the F-PLN page

**Expected behavior**
The calculated fuel at destination is expected (EFOB)

**Actual behavior**
The current fuel is displayed

**References**
![fuel_wrong](https://user-images.githubusercontent.com/80104611/110126900-3835a080-7dc5-11eb-8a12-6f05056772f0.png)

**Additional context**

**Comment by tracernz** [comment]
What have you entered on init page?

**Comment by squashplayer** [comment]
> What have you entered on init page?

I auto-entered the ZFW and for fuel I entered 17.7

**Comment by MisterChocker** [comment]
I could not reproduce the issue, does the issue still occur?

**Comment by MisterChocker** [comment]
Closing since no response from op.
