### ISSUE TITLE
[REQUEST] Transponder and Rudder display brightness

### ISSUE THREAD

**Issue by gkkes** [flybywiresim/a32nx#3818]
**Is your feature request related to a problem? Please describe.**
In ambient light it is difficult to read the displays in both Transponder and Rudder Trim displays.

**Describe the feature you'd like to see implemented**
I would expect the intensity to vary with the setting of the INTEG LT pot on the pedestal

**References**

**Additional context**

gkkes#1982

**Comment by MisterChocker** [comment]
Please provide references

**Comment by AirbusA320Pro** [comment]
The pedestal backlight illumination is controlled as @gkkes suggests. That's how the real aircraft works IRL.

**Comment by MisterChocker** [comment]
Closing since no response from OP and no reference provided.
