### ISSUE TITLE
BUG on TABLET : TOD CALCULATOR

### ISSUE THREAD

**Issue by samyemara88** [flybywiresim/a32nx#3819]
Hi,

Every time i change a value in the TOD calculator section on the tablet my plane starts to fall down and crash everytime.
Thanks

**Comment by DavidEGTE** [comment]
Can you please provide a video or some sort of log of this issue please

**Comment by DavidEGTE** [comment]
> Hi,
> 
> Every time i change a value in the TOD calculator section on the tablet my plane starts to fall down and crash everytime.
> Thanks

Can you please provide a video or some sort of log of this issue please

**Comment by Benjozork** [comment]
You need to input numbers using the numbers row and not the numpad, since numpad keys are bound to control surfaces by default.

Also, please do not ignore the provided issue template we provided for you.
