### ISSUE TITLE
In maintain flight level, start to descent

### ISSUE THREAD

**Issue by robro8** [flybywiresim/a32nx#3820]
Hey there. I am using the latest fbw dev mod. When i am on maintain flightlevel, they start to descent and when i follow the flightplan thith AP they start to climp then i turn to left or right. And i have seen that on maintain flight level the flight director bar is to low. I think therefor will it descent. 

I hope you can help me or fix it or anybody has a solution...

**Comment by Benjozork** [comment]
Please follow the provided template
