### ISSUE TITLE
[BUG] Already overflown waypoints re-appear in the F-PLN

### ISSUE THREAD

**Issue by squashplayer** [flybywiresim/a32nx#3822]
**Mod Version**
0.5.3 stable

**Describe the bug**
When I was flying from LPMA to EDDH, suddenly waypoints that I had already passsed showed up on the F-PLN page. Also, a strange "double" route was shown on the ND. A "DIRECT TO" one of the waypoints ahead of me did *not* delete the waypoints before that waypoint, as it is usually the case in the A320.

**To Reproduce**
I had this behaviour several times but can't remember how it happened. It might have something to do with the selection of the destination runway at EDDH, but I am not sure.

**Expected behavior**
When waypoints have already been overflown, I expect them not to return to the F-PLN, they should be deleted. Also, a "DIRECT TO" a certain waypoint must delete all waypoints "before" that waypoint.

**Actual behavior**
The whole route "returns" under unknown circumstances. A "DIRECT TO" does not delete the waypoints before the DIRECT TO waypoint.

**References**
![passed_waypoints_show_again](https://user-images.githubusercontent.com/80104611/110188505-3519cf00-7e1c-11eb-8abf-f20d78a409e8.png)

**Additional context**

**Comment by Paytheon** [comment]
I can confirm this has happened to many many times in the past 3 days.

**Comment by Benjozork** [comment]
this will resolved with our custom autopilot and flight plan system

**Comment by squashplayer** [comment]
Sounds great, keep up the good work!

**Comment by Tiebo** [comment]
@Benjozork will the custom model also include "direct to radial in" functionality?

**Comment by 2hwk** [comment]
Fixed by #4953 closing ☑️
