### ISSUE TITLE
[BUG] ALL THE BUTTONS ARE ON

### ISSUE THREAD

**Issue by georgiies** [flybywiresim/a32nx#3826]
When I start a flight with a320 neo with a32nx, i can't fly because I can't touh any buttons, and those buttons are all "ON"
I don't know what to do, I've try a lot of versions of the mod

**Comment by georgiies** [comment]
> When I start a flight with a320 neo with a32nx, i can't fly because I can't touch any buttons, and those buttons are all "ON"
> I don't know what to do, I've try a lot of versions of the mod

**Comment by Benjozork** [comment]
Most likely a mod conflict or pirated copy of MSFS

Please do not ignore the provided issue template. Technical support is available on our discord. GitHub is for confirmed bug reports.
