### ISSUE TITLE
No fuel consumption

### ISSUE THREAD

**Issue by Bik59** [flybywiresim/a32nx#3834]
**Mod Version**
0.53
**Describe the bug**
The fuel on the tank is used up during the flight. Refuel at 15.0 and when landing there is still 15.0 of fuel on board

**To Reproduce**
This happens with every flight

**Expected behavior**
According to the fuel calculations, 2.4 remaining fuel should have been left on board.

**Actual behavior**
During the flight, the fuel quantity does not change from 15.0. According to the display, MCDU 15.0 fuel remained on board after landing

Bik59

**Comment by Watsi01** [comment]
Do you have "unlimited fuel" turned on (assistant settings)?

**Comment by Bik59** [comment]
Do I have to look in the MFS2020 or in the A320?

**Comment by Bik59** [comment]
I had unlimited fuel on. Turn it off and try it .. Thank you
