### ISSUE TITLE
Transponder not working on updated FBW A320 Dev Mod

### ISSUE THREAD

**Issue by jaymo10** [flybywiresim/a32nx#3839]
**Mod Version**

**Describe the bug**

**To Reproduce**

1. 
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by lukecologne** [comment]
> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning

**Comment by tracernz** [comment]
Please follow the template, and double press clear before entering code, as on a real aircraft.

**Comment by jaymo10** [comment]
Thank you Michael- but I cannot CLear  with mouse on transponder- I click and nothing becomes active.
Any ideas?

**Comment by Benjozork** [comment]
You need to CLR twice.

**Comment by jaymo10** [comment]
Can’t CLR anything- the transponder keys are unclickable..

**Comment by Benjozork** [comment]
This sounds like a mod conflict or installation error.

What is your MSFS version?

Also, please try with an empty community folder.

**Comment by jaymo10** [comment]
MSFS 2020 with all the updates.
The transponder keys are unclickable...
Everything else works good.. strange.
I’ll try it with an empty community Folder..

**Comment by jaymo10** [comment]
Found the problem- the Copilot mod! It worked on earlier Dev mode but not on the latest Dev mod.. thanks!
