### ISSUE TITLE
[BUG]Beacon light seen in cockpit

### ISSUE THREAD

**Issue by hotshotp** [flybywiresim/a32nx#384]
**Branch**
Both branches

**Describe the bug**
The beacon light is seen reflecting and illuminating the  inside of the cockpit.

**To Reproduce**
Steps to reproduce the behavior: more easily seen at night, turn on beacon

**Expected behavior**
So it's not seen in cockpit is the normal behavior

**Additional context**
Also seen at night in wing views reflecting off of the window from inside

This isn't a big issue, so it's probably low priority, but it is present so I submitted it

**Comment by SmithFR** [comment]
If you are talking about the red light it's the BEACON light strobes are the white flash

**Comment by hotshotp** [comment]
> If you are talking about the red light it's the BEACON light strobes are the white flash

you are absolutely right

**Comment by Snapmatics** [comment]
Just fixed it 👍
