### ISSUE TITLE
[Feature] Cabin Call Key Binding

### ISSUE THREAD

**Issue by AthleticEggplant** [flybywiresim/a32nx#3840]
**Is your feature request related to a problem? Please describe.**
No, Its entirely for convenience.

**Describe the feature you'd like to see implemented**
I would like to be able to set key bindings for additional buttons/functions. More specifically the Cabin Call button. I'm able to bind everything else so I don't have to be looking around the aircraft on approach. The only exception is the Cabin Call.

**References**
N/A

**Additional context**
I do realize this is a VERY VERY minor thing so feel free to sweep it under the rug to work with higher priority items. I wont be upset. Thanks! :)

Discord username (if different from GitHub): 
_Athletic Eggplant#3628_

**Comment by Benjozork** [comment]
This is not possible currently with MSFS, but is planned in the future in the sim.

For now, you can use SPAD.neXt (commercial software) to achieve this.
