### ISSUE TITLE
[BUG]EFB typing username changes views

### ISSUE THREAD

**Issue by rick2909** [flybywiresim/a32nx#3846]
**Mod Version**

Dev version AFC3F4F

**Describe the bug**

while typing in my simbrief username in the EFB i use numblock to enter the numbers in my name but those keys are also bound to change cockpit views. Also if you have somthing bound to a one single key that will also happen. the pressed key will be enterd in the textbox  and the bount action is also executed

**To Reproduce**

1. have something bount to one single key.
2. try to enter it in the simbrief textfield on the EFB

**Expected behavior**

That I can enter every character and won't execute the bound action.

**Actual behavior**

see description

**References**

**Additional context**

this also happend to the streamer chewwy94, 
https://clips.twitch.tv/RelatedEnjoyableRedpandaFreakinStinkin-gXiE31y9q44Q7JA5

Was this working before/when did the issue start occurring?
it was since the EFB got into dev it is there.

Is this a problem in the vanilla unmodded game?
I don't know if there are text inputs in the vannilla planes

Discord username (if different from GitHub):
rick2909#1996

**Comment by Paytheon** [comment]
A temporary solution I use to get around this typing issue is I copy simbrief user name to the clipboard and then Ctrl+V paste into the text field.

**Comment by MapleNAV-TCASFAULT** [comment]
a way to avoid that is to pop out the efb onto a separate tab, so right alt click on the efb and it'll open up a new window dedicated for the efb screen. from there you should be able to type on it without interfering with any bound keys.

**Comment by Benjozork** [comment]
This is a bug with MSFS

**Comment by rick2909** [comment]
> a way to avoid that is to pop out the efb onto a separate tab, so right alt click on the efb and it'll open up a new window dedicated for the efb screen. from there you should be able to type on it without interfering with any bound keys. But the FBW team is trying to integrate an on-screen keyboard for the efb to prevent issues like this.

thx for this, maybey also  add a paste button to paste the coppied username.
