### ISSUE TITLE
[REQUEST] Engine spool times

### ISSUE THREAD

**Issue by squashplayer** [flybywiresim/a32nx#3851]
**Is your feature request related to a problem? Please describe.**
When I press and hold F3, the engine RPM increase at an unrealistic fast rate like in a toy plane.
Same goes for F2 and F1. In real life, the engines accelerate slowly in the lower RPMs and faster in the higher RPM range.

**Describe the feature you'd like to see implemented**
Engine acceleration and deceleration at realistic rates, because it adds so much realism!

**References**

Please watch this Youtube video:
https://www.youtube.com/watch?v=cv41hm4JEB8
Engine acceleration start at time 2:57 and stabilizes at medium RPM at 3:06 (9 seconds).
From medium RPM to full thrust 3:06 until 3:10 (4 seconds)

So the RPM acceleration rate has to be a curve with an initial slow increase and then a steep increase (X-Axis=time, Y-Axis=RPM).

**Additional context**
This is modeled very good in the FSLabs A320, the A320neo behaves similar according to Youtube videos.

**Comment by hotshotp** [comment]
this is already in the custom autopilot branch

**Comment by rhbarber98** [comment]
I don’t see this as an issue with the A32nx. Engine spooling as demonstrated in the attached video is part of the normal SOP for pilots. They don’t just jam the throttles full forward straight away - they push throttles ~50%, let the ECIAS stabilize, and then set FLEX/TOGA power according to performance refs. 

Additionally if you’re using the keyboard shortcut, you’re never going to have a smooth increase - it’s not how the sim operates. You’ll naturally get stepped increments for each keypress. For full throttle control, it’s recommended to use a hardware controller.

**Comment by squashplayer** [comment]
Sorry, I cannot agree with this.

On the real airplane, the pilot will advance the throttles to 50% in about 0.2 seconds. Then the engines spool up in about 9 seconds. That's what I mean.

I know that FS standard functions do not work like this. But please, look at the FSLabs A320 for FSX. They did it! Nice and slow spool up on takeoff. And I think if you find a workaround, you can do it as well.

The reason why I insist on this is that it feels like a toy plane when thrust goes to 50% in 1 second. It just doesn't feel like the real thing. So this is all about immersion.

**Comment by wpine215** [comment]
> 
> 
> Sorry, I cannot agree with this.
> 
> On the real airplane, the pilot will advance the throttles to 50% in about 0.2 seconds. Then the engines spool up in about 9 seconds. That's what I mean.
> 
> I know that FS standard functions do not work like this. But please, look at the FSLabs A320 for FSX. They did it! Nice and slow spool up on takeoff. And I think if you find a workaround, you can do it as well.
> 
> The reason why I insist on this is that it feels like a toy plane when thrust goes to 50% in 1 second. It just doesn't feel like the real thing. So this is all about immersion.

Please read the above reply:




> 
> 
> this is already in the custom autopilot branch

**Comment by Benjozork** [comment]
> But please, look at the FSLabs A320 for FSX

While your intuition about spool up times is correct, please note that the FSLabs uses a different engine than this plane does.

**Comment by MisterChocker** [comment]
#3117 will take care of this.
