### ISSUE TITLE
[BUG] FMA displays "RWY" on stand when TOGA or MAN MCT thrust is set

### ISSUE THREAD

**Issue by ExampleWasTaken** [flybywiresim/a32nx#3853]
**Mod Version**
master
```json
{
  "built": "2021-03-08T04:17:40+00:00",
  "ref": "master",
  "sha": "afc3f4fd39ccb5171ae3a287a0372bd2e466acf1",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

**Describe the bug**
The FMAs show "RWY" on stand when thrust is set to "TOGA" or "MAN MCT". (Possible addition to #1116)

**To Reproduce**
1. Load C&D
2. Turn batteries and EXT PWR on
3. Turn FD on
4. Set thrust to "TOGA" or "MAN MCT"
5-. Check FMA displaying "RWY"

**Expected behavior**
As [this](https://discord.com/channels/738864299392630914/754851312306487326/818495327618596885) Discord message explains "RWY" should only be displayed if a LOC signal is received and the current heading is within 20° of the LOC course.

**Actual behavior**
RWY is display even when standing 90° to the runway while no IRS is aligned.

**References**
![Microsoft Flight Simulator Screenshot 2021 03 08 - 17 02 10 06](https://user-images.githubusercontent.com/58574351/110349443-0295ef00-8033-11eb-8ac2-7d52126e2d74.png)
![Microsoft Flight Simulator Screenshot 2021 03 08 - 17 24 15 20](https://user-images.githubusercontent.com/58574351/110349666-33762400-8033-11eb-9dd5-4e4c06d218fc.png)

Aircraft position in relation to the runway:
![Microsoft Flight Simulator Screenshot 2021 03 08 - 17 02 49 49](https://user-images.githubusercontent.com/58574351/110349704-3ec94f80-8033-11eb-8ed1-cb30b69e87c6.png)

Was this working before/when did the issue start occurring?
I can't say. Noticed it while testing another PR.

Is this a problem in the vanilla unmodded game?
Probably not.

Discord username (if different from GitHub):
ExampleWasTaken#0886

**Comment by aguther** [comment]
Will be fixed with custom autopilot.
