### ISSUE TITLE
[BUG] ACP VHF1 and VHF2 selection issues

### ISSUE THREAD

**Issue by foxmike80** [flybywiresim/a32nx#3854]
**Mod Version**

"built": "2021-03-05T15:03:28+00:00",
  "ref": "master",

**Describe the bug**
I was trying to use the VHF1 on VATSIM as active frequency for transmitting and receiving and VHF2 for receiving only. When I select the "Call" button for VHF1 the VATSIM client recognizes this correctly. When I push the VHF2 button, however, VATSIM does not use VHF2 for receiving. The only way I got it to work was to select a combination of VHF2 on the CPT side and VHF3 on the F/O side or the other way around. This was the only way I could get VATSIM so use VHF for receiving. It seems I have to activate at least one of the VHF3 buttons in order to get VHF2 to work.

**To Reproduce**

1. Spawn at any airport
2. launch the VATSIM client
3. select different frequencies for VHF1 and VHF2
4. Set VHF1 to "CALL"
5. Activate "VHF2" and observe that VATSIM client does not receive on VHF2 (COM2 RX box in the top right corner of VATSIM client)
6. activate VHF3 on either side and observe that VATSIM client now receives on VHF2

**Expected behavior**

When selecting VHF2 VATSIM should receive on VHF2.

**Actual behavior**

VHF2 is only recognized by VATSIM when VHF2 and at least one VHF3 are selected. 

**References**

![image](https://user-images.githubusercontent.com/76132268/110377184-61b82b80-8054-11eb-906f-8fb936229c7e.png)

![image](https://user-images.githubusercontent.com/76132268/110377261-7c8aa000-8054-11eb-80dc-12d470c79c2f.png)

![image](https://user-images.githubusercontent.com/76132268/110377638-f0c54380-8054-11eb-858c-48dc80c9ae1f.png)

![image](https://user-images.githubusercontent.com/76132268/110377731-0b97b800-8055-11eb-8cc0-f57466c0c1d6.png)

![image](https://user-images.githubusercontent.com/76132268/110378011-5fa29c80-8055-11eb-9856-cc5b74618366.png)

**Additional context**

Was this working before/when did the issue start occurring?
I do not know.

Is this a problem in the vanilla unmodded game?
I do not know.

Discord username (if different from GitHub): foxmike1080

**Comment by frankkopp** [comment]
Can confirm the issue. The latest CJ4 from Working Title has this working fine so it seems not to be not an ASABO issue.
Would be great to have this fixed for VATSIM.

**Comment by jonashouben** [comment]
Just looked into this a little further, as this Bug also had annoyed me in the past.

vPilot is apparently requiring all 3 Radios set to minimum "Receive" at the same time for this to work. For example:

- VHF1 transmit, VHF2+3 receive => COM2 RX is on
- VHF2 transmit, VHF1+3 receive => COM1 RX is on

I also checked the receiving Simvars, and they are set correctly, see screenshots.
![screenshot_1](https://user-images.githubusercontent.com/10519180/123845986-213b3100-d915-11eb-98ec-820420157757.png)
![screenshot_2](https://user-images.githubusercontent.com/10519180/123845989-226c5e00-d915-11eb-8526-887e35f00284.png)

**Comment by John-UK** [comment]
There is a simple workaround for this. Select call on VHF 3. Cycle the VHF1 and VHF2 volume buttons (light on / off). Then select call on VHF1. VHF1 is then for TX RX. VHF2 is off and will RX if selected to on. 
The TX (call light) and RX (volume light) should operate independent ie you TX on VHF1 and RX on VHF2 if on the same freq.
It seems there is some duplication in the code of com 1 and com2 the audio buttons. VHF2 on either unit will set the RX on com2 in VPilot.

**Comment by sidnov** [comment]
It's a vPilot bug. They need ``COM RECEIVE:ALL`` enabled to receive on both VHF1&2 to support older sims like FSX. On the A32NX, we have coded it as it would be on the real aircraft, thus ``COM RECEIVE:ALL`` is only set to true when all VHF channels (1,2,3) are set to receive.

**Comment by czarnetz** [comment]
I have again wrote about this in the vPilot-Forum and hope, that they will implemented the switchable option.
https://forums.vatsim.net/topic/32835-listen-on-com2-not-correct-works/

**Comment by tracernz** [comment]
I don't necessarily disagree with Ross' take TBH. We should check how the default aircraft behave...

**Comment by frankkopp** [comment]
> I don't necessarily disagree with Ross' take TBH. We should check how the default aircraft behave...

I also see his point. 
We could add a setting in the EFB called "Compatibility with vPilot" and change the rmp behavior to use 1+2=ALL when set to true.

**Comment by tracernz** [comment]
If the simvar really is supposed to only consider VHF1+2 then we should just match that. We shouldn't re-define it's meaning arbitrarily (we can create Lvars where we want to do that).

**Comment by tracernz** [comment]
Confirm the default A320 has exactly the same behaviour (all COM receivers defined in systemf.cfg need to be on before COM RECEIVE ALL comes on). This is a vPilot problem so there's nothing for us to do.
