### ISSUE TITLE
[BUG] V/S mode does not engage

### ISSUE THREAD

**Issue by squashplayer** [flybywiresim/a32nx#3857]
**Mod Version**
Development afc3f4f

**Describe the bug**
V/S mode does not engage although I press the button correct (lower half)

**To Reproduce**
1. Climb to 23000 ft
2. At 23000 ft, select ALT 13000 ft
3. Press lower half of V/S button
4. V/S mode does not engage, also I cannot select the actual vertical speed

**Expected behavior**
I expected V/S mode to come on so that I can descent from 23000 to 13000 ft. Strangely, sometimes it works.

**Actual behavior**
V/S mode does not activate

**References**
![VS_mode_not_engage](https://user-images.githubusercontent.com/80104611/110400716-727a9880-8078-11eb-8f32-b511d8973557.png)

**Additional context**
I suspect that it has never worked correctly also in the Vanilla version

**Comment by squashplayer** [comment]
Ok...thanks. And where can I download this cAP build? Or is it a future release?

**Comment by ExampleWasTaken** [comment]
It's a future release still.

**Comment by ExampleWasTaken** [comment]
> @ExampleWasTaken No, just no, currently there is no issue in place that describes the following issue. There are similar but not describing this situation.
> @squashplayer The Custom Autopilot is not yet shared publicly but it will be added to the installer soon.
> If you are interested you can take a look at the autoflight channel on our discord

You're right, there is no issue about that. The problem is known though. At least I've seen developers talk about it.

**Comment by MisterChocker** [comment]
@ExampleWasTaken yes it is known, yet we don't had it documented.

**Comment by ExampleWasTaken** [comment]
@MisterChocker I used the term "known issue" incorrectly I agree.

**Comment by AdamNZ** [comment]
> 
> 
> This is a known issue and already fixed in the cAP build. A workaround for now is to first select `OP DES` and then set the the V/S

Nope. That didn't work for me. I can keep "forcing it" that way, but the maximum V/S I can get is -1500. The knob rotates, but nothing happens.
