### ISSUE TITLE
[REQUEST] BOTH MCDU STAYS ON THE SAME PAGE

### ISSUE THREAD

**Issue by lcmiguez** [flybywiresim/a32nx#3866]
ON REAL AIRCRAFT PAGES ON THE MCDU CAN BE VIEWED SEPARATELY

**Comment by ExampleWasTaken** [comment]
Please following the "Feature Request" template to suggest a feature.

**Comment by Benjozork** [comment]
Please stop spamming issues while completely ignoring the template. This is already reported.
