### ISSUE TITLE
[BUG] Simbrief Uplink of Route not working

### ISSUE THREAD

**Issue by 10Exahertz** [flybywiresim/a32nx#3869]
**Mod Version**

v 0.5.3

**Describe the bug**

When I try to load the route via Simbrief in the Init page nothing changes. While in the other pages the flight number, block fuel and other information does change. I also cannot put in a manual route as a back-up.

**To Reproduce**

1. Load the aircraft in cold and dark state, turn it on
2. Load the simbrief info in the AOC pages
3. Attempt and fail to uplink the route information (wait several min to be sure)

**Expected behavior**

It loads the route

**Actual behavior**

Nothing changes

**References**

**Additional context**

I am using an old simbrief airac (the default one), I also have devMode on
Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):

**Comment by tracernz** [comment]
Which AIRAC version are you using on SimBrief? Which AIRAC cycle are you using in the sim (do you have Navigraph?)?

**Comment by ExampleWasTaken** [comment]
Just to be sure for testing: You can load the route in the AOC menu. It's the INIT REQUEST that's not working. Am I correct?

**Comment by tracernz** [comment]
> DCT WAVEY DCT EMJAY J174 ORF J121 CHS DCT IGARY Q85 LPERD DCT OMN CWRLD4

> Your route is valid for AIRAC 2102!

Not that then... hmm. If I get time later I'll try a SimBrief import.

**Comment by 10Exahertz** [comment]
I got rid of the FPS Fix mod and installed the Developer Version of the plane. It works now!
