### ISSUE TITLE
[BUG] Flaps 1 cause massive drag

### ISSUE THREAD

**Issue by pkoecker** [flybywiresim/a32nx#3873]
**Mod Version**
{
  "built": "2021-03-09T16:17:31+00:00",
  "ref": "master",
  "sha": "769da50970cbf3ef0f3e68dbd789553896084d1b",
  "actor": "Benjozork",
  "event_name": "manual"
}

**Describe the bug**
Flaps 1 cause massive drag. When settings the flaps to 1 even with full thrust it is very hard to climb or achieve any speed. When flaps are retracted the aircraft suddenly accelerates. Flaps 2, 3 and Full seem to work as expected. 

**To Reproduce**
1. Start with cold and dark cockpit
2. Takeoff with flaps 1 or set flaps 1 in flight
3. Observe massive drag

**Expected behavior**
Flaps 1 should not cause massive drag

**Actual behavior**

**References**
See https://youtu.be/ZvrGHqNNYP4 (Video is not listed publicly) 
Acceleration when flaps are retracted around 02:08
Deceleration with flaps 1 around 02:37

**Additional context**
No further modifications installed that might affect this behavior AFAIK

Was this working before/when did the issue start occurring?
The issue started with the new update to MSFS2020 today

Is this a problem in the vanilla unmodded game?
I do not know

**Comment by DFWSupertrooper** [comment]
I concur the same after today's update.  Immediately prior to update - was fine.  Using FBW Custom.  Thx.

**Comment by Benjozork** [comment]
This is known and listed in our announcement message.
