### ISSUE TITLE
[BUG] Autopilot Very Jerky Upon First Engagement 

### ISSUE THREAD

**Issue by A320PHX** [flybywiresim/a32nx#3875]
**Mod Version**
769da50

**Describe the bug**
When activating autopilot, the plane jerks into position almost instantly. 

**To Reproduce**
Load up flight
Take off
Engage autopilot

**Expected behavior**
Turn on autopilot and have it gently move the plane into position to follow flight directors.

**Actual behavior**
Plane violently and suddenly jumps into position. All other autopilot movements seem ok.

Was this working before/when did the issue start occurring?
Yes, the dev version from yesterday performed great. Nice dampened movements to align the plane on course.

Is this a problem in the vanilla unmodded game?
I do not know. I haven't used that version.

**Comment by aguther** [comment]
1) This will be much improved with custom AP. For now nothing we can do with the default one

Some additional guidance:
Even on the real plane, it's not recommended to not follow the FD and then to enable the AP. In case one does not want to follow the FD it should be turned off, also to ensure SPEED mode of ATHR is engaged.

There are some things to protect the plane from weird behavior, still it's not recommended. I give an example: if you have AP off and FCU ALT is set to 5000 ft, FMA shows ALT and you engage the AP on an altitude of 5500 ft (which is more than 250 ft deviation from FCU ALT). What happens in that case is that the AP cancels the V/S of the plane (if there is) and holds then the altitude.

This is by the way already implemented on the custom AP.
