### ISSUE TITLE
[BUG] Vertical Speed dial and EFB not working

### ISSUE THREAD

**Issue by FSFlyer** [flybywiresim/a32nx#3879]
**Mod Version**

769da50

**Describe the bug**

When you interact with either the EFB or the vertical speed dial, when the AP is in VS mode, no response happens.

**To Reproduce**

1. Load the flight
2. (For the EFB) Launch the flypad tablet and the issue presents itself
3. (For the VS) Fly the aircraft to a point where AP can be turned on, turn on autopilot and then use the VS dial

**Expected behavior**

Both the VS and EFB should respond as normal as before Sim Update 3.

**Actual behavior**

No response occurs from both of these instruments

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Was working before Sim Update 3, so Asbro has probably edited the code to make it not work.
Is this a problem in the vanilla unmodded game?
Unsure but I think it worked prior.

Discord username (if different from GitHub):
Flyer#4404

**Comment by DFWSupertrooper** [comment]
I see the same with EFB...did not engage the VS knob, so cannot confirm/deny.

**Comment by picklertune** [comment]
i have the exact same issue. vertical speed knob is stuck and will not work anymore. i am on DEV version. The stable version none of the instrument panels light up and displays are black. this all happened after today's update. i tried reinstalling FBW and removing everything in community but nothing helps.

**Comment by Saschl** [comment]
Could you elaborate what altitude you were at and what altitude was selected when engaging the AP?

**Comment by FSFlyer** [comment]
> Could you elaborate what altitude you were at and what altitude was selected when engaging the AP?

It happened at any altitude. I was doing a test flight and turned on the AP at about 1,000 feet. FL was initially set at FL240 then FL300 and it made no difference. When I engaged VS, it was set to whatever the vertical speed of the aircraft was at the specific moment in time.

**Comment by Benjozork** [comment]
This is already in the #known-issues channel on Discord

**Comment by MisterChocker** [comment]
@Benjozork closing this pr?
