### ISSUE TITLE
[BUG] VOR/ADF on PFDs not showing on pilot side

### ISSUE THREAD

**Issue by frankkopp** [flybywiresim/a32nx#3880]
**Mod Version**
{
  "built": "2021-03-09T19:00:13+00:00",
  "ref": "fbw",
  "sha": "ccb4e9c90cfdc727c4e5eb6165c3401dc271bac9",
  "actor": "aguther",
  "event_name": "manual"
}

**Describe the bug**
The VOR/ADF info is not showing on the pilot although switched ON.
On the FO side they are always showing although switched OFF
Switching to ADF still shows VOR on FO side

**To Reproduce**
1. Start C&D turn on EXT PWR
2. See VOR info displayed on FO side although switch is off
3. Switch VOR on on pilot side - no info is displyed

**Expected behavior**
VOR info displayed according to switches for pilot or FO side

**Actual behavior**
See above

**References**
![image](https://user-images.githubusercontent.com/16833201/110551657-3574db80-8136-11eb-9491-6115afed5655.png)
![image](https://user-images.githubusercontent.com/16833201/110551690-458cbb00-8136-11eb-96e4-80cb41b031b2.png)

Was this working before/when did the issue start occurring?
Yes - worked before fbw updates on 9th for MSFS 1.14.5

Is this a problem in the vanilla unmodded game?
unknown

Discord username (if different from GitHub): Cdr_Maverick

**Comment by tracernz** [comment]
Confirmed, and I think known already with sim update 3.

Side note: what happened to your pedestal? It's a weird colour.

**Comment by frankkopp** [comment]
Haven't found it on Discord under known-issues.

> Side note: what happened to your pedestal? It's a weird colour.
It's at EDDM gate 214 (paid scenery) with a lot of light from the stand flood lights. Makes colors very interesting :)
