### ISSUE TITLE
[BUG] All Screens black after recent update.

### ISSUE THREAD

**Issue by Avationz** [flybywiresim/a32nx#3882]
**Mod Version**

**Describe the bug**

**To Reproduce**

1. After the update I noticed it
2. Tried restarting and that did not work
3. No GPWS callouts are present 

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring? It was working before and just after the update

Is this a problem in the vanilla unmodded game? Unknown

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
You completely ignored the issue template.

By the way, this is solved in the development and experimental versions.

**Comment by Avationz** [comment]
So how do I solve this because it is still broken for me

**Comment by Benjozork** [comment]
You need the development or experimental versions.

**Comment by Benjozork** [comment]
Our installer lets you get all those versions

https://api.flybywiresim.com/installer

**Comment by Avationz** [comment]
thx

**Comment by Paytheon** [comment]
BTW, I "HIGHLY" recommend you go to the 'CONTENT MANAGER' in MSFS 2020 and update everything as well. It solves MANY issues.
