### ISSUE TITLE
[BUG] EFB flyPad not Working After Sim Update 3, MSFS Version 1.14.5.0

### ISSUE THREAD

**Issue by speedbird5** [flybywiresim/a32nx#3887]
**Mod Version**

  I am using the Development Version
  "built": "2021-03-10T00:43:09+00:00",
  "ref": "master",
  "sha": "f26a1291f98e395d85427fa4caf9414ef663e0ca",
  "actor": "Benjozork",
  "event_name": "manual"

**Describe the bug**

After Sim Update 3, MSFS  Version 1.14.5.0 the flyPad is non responsive at all.  It turns on by clicking but when I click on any of the functions there is no response.  Also, the flyPad brightness is very dim.

**To Reproduce**

1.  Update sim to version 1.14.5.0, use the above A32NX version and check the flyPad.

**Comment by Benjozork** [comment]
Being investigated

**Comment by speedbird5** [comment]
Can you confirm this issue ?

**Comment by Benjozork** [comment]
Yes. We do not know the cause yet, but it's being looked into, possibly with Asobo

**Comment by Benjozork** [comment]
Ok found the issue working on a fix.
