### ISSUE TITLE
[BUG] Master caution light & aural warning can’t be disabled after Sim Update 3, MSFS Version 1.14.5.0

### ISSUE THREAD

**Issue by speedbird5** [flybywiresim/a32nx#3888]
**Mod Version**

I am using the Development Version
"built": "2021-03-10T00:43:09+00:00",
"ref": "master",
"sha": "f26a1291f98e395d85427fa4caf9414ef663e0ca",
"actor": "Benjozork",
"event_name": "manual"

**Describe the bug**

Master caution light & aural warning can’t be disabled. I got a master caution and couldn’t disable/cancel it after I pressed the master caution button.

**To Reproduce**

1.   Update sim to latest version and cause a master caution warning, then try to cancel it by pressing the master caustion button.

**Comment by Kimbyeoungjang** [comment]
What kind of warning was in that situation?

**Comment by speedbird5** [comment]
Takeoff configuration with full flaps and hot brakes after landing....

**Comment by Kimbyeoungjang** [comment]
> Takeoff configuration with full flaps and hot brakes after landing....

that is known bug not by recent update. will fix on my pr.

**Comment by speedbird5** [comment]
Another user on the MSFS forums also reported the same problem but in his case the master caution was caused during engine start.  Sorry but I can't find the post...

**Comment by Kimbyeoungjang** [comment]
ohhhhhh I start sim and find that problemmm

**Comment by aviationenthusiast** [comment]
Pressing the warning button in cases of overspeed does nothing either. Have to clear the ECAM message for the warning to stop. It's been like this for a while even before sim update 3.

**Comment by wezzer** [comment]
> Pressing the warning button in cases of overspeed does nothing either. Have to clear the ECAM message for the warning to stop. It's been like this for a while even before sim update 3.

Overspeed warning can't be cancelled via master warning button in real aircraft either. It has to be cancelled via "EMER CANC" button on the ECAM control panel.

Ref: https://www.smartcockpit.com/docs/A320-Indicating_and_Recording_Systems.pdf (see page 13) for following information: 
![320-overspeed-warning-emer-canc](https://user-images.githubusercontent.com/12997174/110682561-c0f87600-81e3-11eb-8f61-337832dfdd7e.png)

**Comment by Kimbyeoungjang** [comment]
Yes overspeed & LG Not down can't cancel with master warning. Already insert that in my pr :)

**Comment by kgaviation** [comment]
Has this bug been fixed yet because it's still happening on my end. I can't acknowledge the master caution button.

**Comment by kgaviation** [comment]
I'm still getting this issue where I'm unable to disable the master caution warning after multiple installations of the latest dev. and custom versions. Also, I'm getting a master caution warning after starting the second engine and after retracting the landing gear after takeoff.

**Comment by Kimbyeoungjang** [comment]
not fixed yet. working in https://github.com/flybywiresim/a32nx/pull/3824 here

**Comment by davidwalschots** [comment]
Fixed in #4770.
