### ISSUE TITLE
Blank avionics after Sim update 3

### ISSUE THREAD

**Issue by Falcon0703** [flybywiresim/a32nx#3890]
Deleted all additional Asobo liveries and reinstalled A32nx stable version using the installer. Stock version is working just fine.

**Comment by melliiii** [comment]
I had the same issue, switching to dev and then back to experimental fixed the issue for me.

Also Stable Version doesnt have the fix included as stated in the #server-announcements channel on the discord server

**Comment by tracernz** [comment]
Please follow the issue template when opening a new bug.

Stable does not currently work, dev does. A new stable release will be coming.

**Comment by sammohan12** [comment]
v.0.5.3 has blank avionics screen after latest MFSF 2020 patch. Is there a fix?

**Comment by myselfaaryan** [comment]
The stable version for 1.14.5.0 is yet to be released. Until then please use the dev version.
