### ISSUE TITLE
Autopilot VS

### ISSUE THREAD

**Issue by LinconshireRP** [flybywiresim/a32nx#3891]
Just updated it, I'm using the dev build and its now only staying at VS climb rate of 1500, And I'm unable to change the digits, I'm able to turn the knob but thats about it.

**Comment by pickels98** [comment]
Have the same problem. can't change the digits in VS. climb rate of 1500 can't be changed.
master warning knob don't work.
using last master build.

**Comment by myselfaaryan** [comment]
Please respect the issue template. This issue will be fixed after #3881 is merged. Thanks.

**Comment by pickels98** [comment]
ok will do sorry
