### ISSUE TITLE
[BUG] On take off OR on landing the plane rudder zig zags and loses control of the plane

### ISSUE THREAD

**Issue by regisbiass** [flybywiresim/a32nx#3895]
On take off OR on landing the plane rudder zig zags and loses control as soon as I disconnect the autopilot.  It does happen from different development version from time to time.

I am using TCA airbus stick   (latest software and calibrated)
I am also using the TCA airbus throttle + Addons for flaps
I am alsp Saitek Rudder.

Note:
The issue only happens when I disconnect the autopilot to take control of the plan using the stick and sometimes when I take off before engaging the autopilot.

**Mod Version**

Mod version (currently experiencing the issue now) 769da50

**Describe the bug**

I am happy the record and provide you video if needed....

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning
