### ISSUE TITLE
[BUG] AP Managed Heading / Managed Speed / Flight Phase

### ISSUE THREAD

**Issue by salzsalz** [flybywiresim/a32nx#3896]
**Mod Version**

"built": "2021-03-10T10:03:43+00:00",
  "ref": "master",
  "sha": "3524c1756717803cdc4302fb7d4b349dccf42fc2",
  "actor": "myselfaaryan",
  "event_name": "manual"

**Describe the bug**

Starting C&D ( tried spawning on rwy as well, same outcome, loading up FP via Simbrief. Taking off, getting to intercept altitude and activating AP.
After activation of AP ( FD, A/thr = ON, managed speed and heading ) the plane is heading to 360°
and staying there. When I press "LOC", it certainly follows the waypoints.
After takeoff, flightphase stays in clb, but the speed is not rising above 150kts. Its a little weird.

**To Reproduce**

1. Spawn C&D or RWY
2. load FP
3. takeoff
4. activate AP ( managed heading / speed = ON )

**Expected behavior**

Expectation is to follow the FP and managed speeds.

**Actual behavior**

AP doesnt follows the FP and goes to a heading of 360

**References**

![2021-03-10 11_21_54-Microsoft Flight Simulator - 1 14 5 0](https://user-images.githubusercontent.com/80407162/110648023-a8bf3180-81b8-11eb-87ca-754075c6f7d6.jpg)
![2021-03-10 11_22_51-Microsoft Flight Simulator - 1 14 5 0](https://user-images.githubusercontent.com/80407162/110648110-b83e7a80-81b8-11eb-80ca-bcb1e451fc8d.jpg)
![2021-03-10 11_23_29-Microsoft Flight Simulator - 1 14 5 0](https://user-images.githubusercontent.com/80407162/110648172-c5f40000-81b8-11eb-9965-d7eed5d22d34.jpg)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
no, tried it with the base A320 and it worked like before.

Discord username (if different from GitHub):

SalzSalz

**Comment by Benjozork** [comment]
Could be relayed to heading holder variable index changes in 1.14, which is what broke vertical speed

**Comment by MisterChocker** [comment]
Looks like the aircraft is in approach phase.

**Comment by salzsalz** [comment]
> 
> 
> Looks like the aircraft is in approach phase.
> Can you please provide screenshots from the mcdu performance page?

![2021-03-10 11_20_21-Microsoft Flight Simulator - 1 14 5 0](https://user-images.githubusercontent.com/80407162/110720799-7d1b6600-820f-11eb-92a4-0240b7e29f6d.jpg)

**Comment by AirbusA320Pro** [comment]
This looks like the MCDU is all out of sequence and not set up correctly. The FMA shouldn't be reading CLB blue on takeoff without SRS being active, also on takeoff the FMA should read MAN FLX or TOGA - not SPEED. And the first screenshot shows the LDG config ECAM memo. Confident of a bad MCDU setup.

**Comment by heeshung** [comment]
> This looks like the MCDU is all out of sequence and not set up correctly. The FMA shouldn't be reading CLB blue on takeoff without SRS being active, also on takeoff the FMA should read MAN FLX or TOGA - not SPEED. And the first screenshot shows the LDG config ECAM memo. Confident of a bad MCDU setup.

Everything mentioned that _should_ be happening did before update 3, but I'm getting the same symptoms as the screenshots above as well as the original reported issue after update 3.  Managed speed isn't working, and managed heading always turns the plane to heading 360.

**Comment by LordNecton** [comment]
Im also getting the Same problems. As soon as i activate AP the plane turns to a 360 heading and stays there

**Comment by salzsalz** [comment]
UPDATE: 
After the last devbuild -> {
  "built": "2021-03-10T21:57:57+00:00",
  "ref": "master",
  "sha": "640ea13fae829c1a486924fb5755fef2fff5bfa6",
  "actor": "Benjozork",
  "event_name": "manual"
}

It seems to follow the FP again, Im trying to reproduce it now.

**Comment by salzsalz** [comment]
> 
> 
> This looks like the MCDU is all out of sequence and not set up correctly. The FMA shouldn't be reading CLB blue on takeoff without SRS being active, also on takeoff the FMA should read MAN FLX or TOGA - not SPEED. And the first screenshot shows the LDG config ECAM memo. Confident of a bad MCDU setup.

You are right with the MAN FLX / TOGA, so when not going to TOGA / MAN at takeoff and remaining at CLB, it wouldnt follow FP, cause it wasnt leaving the takeoff config phase. tryed with man / TOGA, after takeoff thrust to clb and it follows FP and climbs regular. 

If this is the solution, Id be damned sry and feel pretty stupid now, jeez. 
But also it worked before this exactly way..

**Comment by MisterChocker** [comment]
When not setting takeoff thrust, the AC does not transition from preflight into takeoff phase. Thats also how the real ac works.

**Comment by AirbusA320Pro** [comment]
I guess as the A32NX get more and more lifelike, phrases like "it used to do it" when setup incorrectly may have had more tolerances - but the real aircraft doesn't have those tolerances. If the MCDU isn't set up correctly, then the real aircraft won't behave correctly. The old adage of "shit in, shit out" when it comes to the autopilot is very relevant.

**Comment by salzsalz** [comment]
> 
> 
> When not setting takeoff thrust, the AC does not transition from preflight into takeoff phase. Thats also how the real ac works.

Yep, it was all my fault. But I dont know, why it worked before, even though it was wrong.
Now taking off with man flx / toga, afterwards set to clb, it notices the next flightphase. 
"Problem" solved and lesson learned. My bad for using all of your time:)

**Comment by MisterChocker** [comment]
There will be a pr coming up with a lot of improvements to the flight phase manager (to further improve the system and behave like the real one)

**Comment by AirbusA320Pro** [comment]
Probably because the simulator just acknowledged the a/c was off the ground and therefore "must" be in flight phase. But as the devs make continual major improvements to make this more realistic, the sim won't behave the same way. As MisterChocker says, having a proper flight phase manager will change what the sim used to do, into something much more real-world!

**Comment by LordNecton** [comment]
Thats all well and good, But for me who sets up a flight plan via in sim itself as im no expert pilot could make this great mod for me Un  flyable...

**Comment by AirbusA320Pro** [comment]
@LordNecton unfortunately that's a trade off between making this the most realistic A320 simulator and it being a "game". There's still a lot of assistance offered by the software and community if you get stuck.

**Comment by tracernz** [comment]
> 
> 
> Thats all well and good, But for me who sets up a flight plan via in sim itself as im no expert pilot could make this great mod for me Un flyable...

Documentation is in the works to make it all clear. There aren't actually too many things that need doing.

**Comment by tomola2** [comment]
Yes, clicking "LOC" will work - it will follow normal FP.
