### ISSUE TITLE
[BUG] On take off OR on landing the plane rudder zig zags and loses control of the plane

### ISSUE THREAD

**Issue by regisbiass** [flybywiresim/a32nx#3898]
**Mod Version**
Development - 769da50

**Describe the bug**
Hardware:
TCA airbus Stick
TCA airbus Throttle
TCA Airbus quadrant Addons (flaps)
Saitek Rudder pedals

Description of the problem:
On take off, as soon as I engage the autopilot (from the stick, red button), the plane rudder pedals (seen on the plane) zig zags left and right, the plane then starts to veer left out of control.
On landing, as soon as I desengage the autopilot (from the stick, red button), the plane rudder pedals (seen on the plane) zig zags left and right , the plane then starts to veer left out of control.

IMPORTANT:
On some of the version of A320 DEV mod, I have NOT experienced it, Same Hardware. Everytime there is an update, I update the mod, and then boom the issue reappears again.
I am confused as to if the TCA airbus stick is the problem or some sort file that the update keep putting back that is faulty from time to time.

Also  - TCA latest drivers, calibrated, tried dead zones etc....

**To Reproduce**
Take off and engage autopilot  -  OR when landing and disconnect the autopilot.  I have seen this issue previously on other Dev versions. It is something that comes from time to time. It is recurring.

**Expected behavior**
I expect when I engage the autopilot, the rudder to not twitch and zig zag left and right causing the plane to veer left to crash

**Actual behavior**
As soon as I engage the autopilot on takeoff OR desengage the autopilot landing, the rudder pedals (seen on the plane) twitches and causes the plan ziga zag and veer left or right

**References**
I have recorded it and uploaded on my youtube as the video size more than 500Mb
Link is here: https://youtu.be/Z1PkpxwiwJg

**Additional context**
Link is here: https://youtu.be/Z1PkpxwiwJg
I have uploaded a test case video now...See as I roll circa 1.12 (the way the rudder on the plane twitches) and also watch the rest of the video, you should see how that twitch causes me to lose the plane. Notice there was also heavy winds pushing me to the right as I rolled...but that as nothing to do with the rudder losing it all the time.

Was this working before/when did the issue start occurring?
On some old version of the mode, this issue has appeared in the past. And on some, I have not noticed the problem.

Is this a problem in the vanilla unmodded game?
I have not tested it against the vanilla  - will do shortly and update the ticket if appropriate.

Discord username (if different from GitHub): regisb

**Comment by regisbiass** [comment]
Hi Val,

Thanks.  I have been doing this. I will try again.


Best Regards,

Regis Biassala

Tel: 00353864052190

________________________________

**Comment by MisterChocker** [comment]
Please retest with the latest master or stable version.

**Comment by MisterChocker** [comment]
Closing since no response from op.

**Comment by regisbiass** [comment]
Hi Val,

The issue has re-occured again with the latest development version. No change in the settings.

The only thing I have done is Update my installer to latest to get the A320nx separation with Asobo.


Best Regards,

Regis Biassala

Tel: 00353864052190

________________________________

**Comment by regisbiass** [comment]
Issue seems to have resolved. What I noticed with TCA stick, there is button (lock) to prevent it from being used as rudder. I had that button clicked (disable rudder on the stick) as I have saitek rudder.  And this was causing twich and zig zag.

Leaving to default....the issue has gone on the same plane.


Best Regards,

Regis Biassala

Tel: 00353864052190

________________________________
