### ISSUE TITLE
[BUG] INSERT TITLE HERE

### ISSUE THREAD

**Issue by dobemason** [flybywiresim/a32nx#3904]
**Mod Version**
V0.5.3

{
  "built": "2021-02-20T01:06:35+00:00",
  "ref": "refs/remotes/upstream/HEAD",
  "sha": "f70e084cd82e1c16b28827df5694ae65657d0bf2",
  "actor": "benjozork <benjamin.dupont.984@gmail.com>",
  "event_name": "manual"
}

**Describe the bug**
 All screens are off after Mar 9 update of MSFS. I removed and reinstalled the stable mod in the community folder.  
![Screenshot (21)](https://user-images.githubusercontent.com/78941611/110681317-b4562c80-81a7-11eb-899a-928c5a729c08.png)

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?  All screens are on in the unmodded version.

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by dobemason** [comment]
Also i noticed the LS button stop working
![LS button](https://user-images.githubusercontent.com/78941611/110682722-414db580-81a9-11eb-8526-97bbc8dd1620.jpg)

**Comment by Benjozork** [comment]
As I told you in your other issue you opened, the stable version does not work.

By the way, we announced on all our social media platform and on Discord that only the development version works.

**Comment by dobemason** [comment]
Much appreciated. I missed it,
