### ISSUE TITLE
EFB not working after MSFS update to 1.14.5.0

### ISSUE THREAD

**Issue by PatriceCesson** [flybywiresim/a32nx#3907]
**Mod Version**
{
  "built": "2021-03-10T17:48:23+00:00",
  "ref": "master",
  "sha": "67e859e4fac9276321ee32b53d9a777b760a9d8d",
  "actor": "myselfaaryan",
  "event_name": "manual"
}

**Describe the bug**
When in flight, we cannot use the efb: no action works (even detach the efb as a separate window)
None of the efb menu items works, no interaction possible

**To Reproduce**
Start a flight
Try to use the efb: nothing works.

**Expected behavior**
We should be able to:
- detach the window
- Use any item of the menu (or if menu is empty, see that it is empty).

**Actual behavior**
None of the above works.

**References**
No need.

**Additional context**
None.

Was this working before/when did the issue start occurring?
Yes.

Is this a problem in the vanilla unmodded game?
Not applicable.

Discord username (if different from GitHub):

**Comment by myselfaaryan** [comment]
this has been fixed in the latest dev version. please update your mod. thanks!

**Comment by myselfaaryan** [comment]
Try Downloading From Here: https://github.com/flybywiresim/a32nx/releases/download/vmaster/A32NX-master.zip

**Comment by PatriceCesson** [comment]
Ok
I have found the culprit: it was a conflict with the A330 I have also and the compatibility mod allowing the two to be in the community folder. If I remove the A330, no problems, the EFB works as expected.
Sorry for this false issue.
