### ISSUE TITLE
[BUG] Strong left bank on final

### ISSUE THREAD

**Issue by Road-to-Hell9** [flybywiresim/a32nx#3911]
**Mod Version**
A320NX Master: 640ea13fae829c1a486924fb5755fef2fff5bfa6

**Describe the bug**
On final, about 50ft AGL, the aircraft starts a random left bank, like it did a long time ago

**To Reproduce**
1.Make flight
2.ILS approach, disconnect AP at 1000ft AGL
3.Land

**Expected behavior**
Normal landing only influenced by wind

**Actual behavior**
Strong random left bank 

Was this working before/when did the issue start occurring?
Started occurring after I updated

**Comment by hotshotp** [comment]
This has been fixed in custom flybywire
