### ISSUE TITLE
Dashboard gauges not turning on

### ISSUE THREAD

**Issue by Macca0410t** [flybywiresim/a32nx#3912]
**Mod Version**

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning

Plus, you are most likely using the stable release, and we have stated already on social media and discord that only the development version works.

**Comment by Macca0410t** [comment]
Hi Benjamin,

Many thanks for your help.  The Development version worked beautifully.

My apologies for not using or understanding and using social media and discords. I have trouble chasing down appropriate threads on forums.

Using the “Old card here”  73 not out and  VERY willing to learn.

Again many thanks for your prompt reply and solution and deepest apologies for using your valuable time on another newbie.

Kindest Regards,

John

**Comment by Benjozork** [comment]
No worrries! Sorry if I seemed a bit abrupt. We have a TON of messages about issues/compatibility the past few days, has been making us all a bit stressed out.

Glad the development version worked.
