### ISSUE TITLE
[BUG] Take off w/ flaps - Hard to gain speed at 10 degree pitch

### ISSUE THREAD

**Issue by mreza1st** [flybywiresim/a32nx#3913]
**Mod Version**

**Describe the bug**

After Sim 3 update, the aircraft does not gain speed upon takeoff and at 10 degree pitch! Would think this is reported by other but I can't find this being reported! The speed stays at 140 knots.

**To Reproduce**

1. Do a take off at 10 degree pitch and flaps 1+f
2.
3.

**Expected behavior**

The plane was gaining speed before the Sim update 3. With fuel at 5,000 KG, these planes should gain speed quickly at 10-12 degree pitch.

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Yes, it was somewhat working before the Sim 3 update.
Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by tracernz** [comment]
https://github.com/flybywiresim/a32nx/pull/3878

**Comment by robro8** [comment]
Same issue. And The accelaration on rwy is with FLAPS 1 CONFIG is to slow

**Comment by tush0701** [comment]
Same issue, speed gain is impossible and infact, speed reduces as fuel weight is increased

**Comment by mreza1st** [comment]
Hi all,

Here is a video with focus on PFD on A320 (seems heavy) take off. Thank you FBW for looking into this.

https://www.youtube.com/watch?v=n3TJMro_NzA&t=353s

**Comment by donstim** [comment]
We're aware of the issue and are actively working on it.
