### ISSUE TITLE
[REQUEST] can you fix V/S from CRZ ALT? 

### ISSUE THREAD

**Issue by ducky3333** [flybywiresim/a32nx#392]
**Is your feature request related to a problem? Please describe.**

**Describe the features you'd like to see implemented**

**Additional context**

when i try to descend from CRZ ALT , PFD V/S value doesnt move from + 0 .

in this step , i have to use open des instead of v/s , and then v/s working start.

would you add feature this please?
![수정됨_Microsoft Flight Simulator Screenshot 2020 09 05 - 11 03 16 03](https://user-images.githubusercontent.com/38446386/92294736-d906e880-ef67-11ea-8b71-757bf344a5df.jpg)

**Comment by MisterChocker** [comment]
closing since duplicate and not following template correctly
