### ISSUE TITLE
[BUG] MFD not working since sim update 3 on stable version

### ISSUE THREAD

**Issue by Soufiane974** [flybywiresim/a32nx#3922]
**Mod Version**
A320NX Master: 0.5.3 Stable

**Describe the bug**
All MFD screens are black, not showing anything after switching batteries ON.
The issue is not present on Development version and Custom FBW version, only on stable.

**To Reproduce**
1. Start a cold and dark flight
2. Switch ON battery switches 1 and 2
3. Try to increase luminosity

**Expected behavior**
MFD showing Self-Testing 40 seconds max

**Actual behavior**
Black screen, not showing anything
![image](https://user-images.githubusercontent.com/6583981/110807027-0ed0b500-829c-11eb-9a08-7199dfd51257.png)

**Comment by SantiagoReg** [comment]
I have the same problem, and it doesn't work if I start on the runway with the plane up and running

**Comment by mpearce2** [comment]
Same issue here.

**Comment by Stenodin** [comment]
same issue

**Comment by najibus** [comment]
Same here
Try instable version ??

**Comment by Watsi01** [comment]
Right now the fixes for the latest MSFS update are only in developer or custom version. Stable will follow (don't know when yet).

**Comment by Benjozork** [comment]
People, as we have announced on our social media and on our Discord, **the stable version does not work currently.**

Please do the minimum amount of research.
