### ISSUE TITLE
Wings geometrie and Main animation Gear

### ISSUE THREAD

**Issue by Chris-TBM940** [flybywiresim/a32nx#3926]
Please can you remove the Forward main landing Gear animation (dafault Bug from Asobo!) 
I open a ticket since 4 Months or so on Asobo/Microsoft no reacts.
And the  Wings profil is to Fat. The Stabilizer postion 0 (from autside is Wrong . 
Thank you

https://de.wikipedia.org/wiki/Datei:Estabilizador_horizontal-Airbus_A320.jpg

https://www.flickr.com/photos/a380spotter/40761796135

https://www.deviantart.com/hyppthe/art/Airbus-A320-Wing-View-369002557

![Screenshot (162)](https://user-images.githubusercontent.com/80477579/110824489-6880b180-8293-11eb-80c2-e2bf7caf4a9d.png)
![Screenshot (163)](https://user-images.githubusercontent.com/80477579/110824515-6caccf00-8293-11eb-9fdc-162a323e46ba.png)
![Screenshot (168)](https://user-images.githubusercontent.com/80477579/110824520-6f0f2900-8293-11eb-828a-e2684386213c.png)

 best regards

**Comment by Benjozork** [comment]
Hello, you need to follow the ticket templates when requesting a change or reporting a bug.

**Comment by hotshotp** [comment]
Please next time be more specific about the issue rather than "remove the wheel animation" - which animation? What's wrong with it?
