### ISSUE TITLE
Screens not working

### ISSUE THREAD

**Issue by tnick25** [flybywiresim/a32nx#3929]
Hello, 

I have tried all of the troubleshooting steps from the recommendation on the latest release. I am still encountering issues where all screens in the cockpit are non-functional. I also used the installer to install. Changing brightness or anything along those lines does not affect the screens.
Windows version
![image](https://user-images.githubusercontent.com/54631358/110844161-4e7caa00-8266-11eb-89b4-474da2b67f65.png)
FS Build:
![image](https://user-images.githubusercontent.com/54631358/110844290-7966fe00-8266-11eb-98c6-b9d9c292d047.png)

**Comment by Valastiri** [comment]
Please use the template provided to you. See known issues on our discord or https://docs.flybywiresim.com/start/reported-issues/.

Stable is currently not compatible.
