### ISSUE TITLE
Message on PFD that indicates normal LAW

### ISSUE THREAD

**Issue by Zyonix007** [flybywiresim/a32nx#393]
Make Normal law show on pfd 

![image](https://user-images.githubusercontent.com/60050366/92295663-d2428c00-eefb-11ea-8e5f-f4018c677fb6.png)

**Comment by Benjozork** [comment]
Please follow issue templates.

**Comment by tareksabet** [comment]
closing now as it's not respecting the issue template it would be good if you opened it again would be great. 
Thank you
