### ISSUE TITLE
ND display crash

### ISSUE THREAD

**Issue by loganisflying** [flybywiresim/a32nx#3931]
**Mod Version**
DEV Version (Installed with installer)

{
  "built": "2021-03-10T21:57:57+00:00",
  "ref": "master",
  "sha": "640ea13fae829c1a486924fb5755fef2fff5bfa6",
  "actor": "Benjozork",
  "event_name": "manual"
}

**Describe the bug**
The screen was not showing up, but as soon as I started the engines, this weird image popped up.

**To Reproduce**
I genuinely have no clue what I did to trigger this, but this is what I did:
1. Created a flight-plan in world map from LA to Vegas using a departure and an ILS approach
2. Spawned at LAX at a gate, turned on battery power and all GPS knobs (sorry, I'm kind of new and don't know the proper terminology lol)
3. The screen was blank until I turned the engines on, in which the weird rainbow screen popped up

**Expected behavior**
I expect that, once the power and GPS knobs are turned on, the navigation screens will begin loading.

**Actual behavior**
The screen on the right did not turn on until I turned the engines on

**References**
![Microsoft Flight Simulator 3_11_2021 4_32_10 PM](https://user-images.githubusercontent.com/80489554/110859925-29019780-828a-11eb-9a38-a1f8fe4fa7d7.png)

**Additional context**

**Was this working before/when did the issue start occurring?**
I ran the the mod this morning without issues

**Is this a problem in the vanilla unmodded game?**

I'm not sure

**Comment by Benjozork** [comment]
Can you reproduce this 100%

**Comment by oiram101** [comment]
I have no display anymore, after the update.

**Comment by loganisflying** [comment]
> Can you reproduce this 100%

Sure. Should I screen record it?

**Comment by Benjozork** [comment]
@oiram101 this is unrelated to this issue - you need to use the development version.

**Comment by loganisflying** [comment]
I am using the development version, however, I think it has something to do with loading a flight plan from the World Map (in game). I exited out, made the flight plan in SimBrief instead (same routes, runway, etc) and everything was smooth sailing. 

In conclusion, it may be a World Map/Vanilla issue

**Comment by tracernz** [comment]
If you can write down a set of steps to reproduce the issue from the world map that’d be helpful still.

**Comment by fackprod** [comment]
Issue only occurred for me with v5.03 stable version default livery  AFTER March 11 MSFS2020 update.  No display gauges whatsoever, no battery lvl display and APU will not start in cold and dark. Tried loading an old Simbrief file starting on runway. Aircraft good to go in every respect but no displays. MS update causing conflict?

**Comment by ternium1** [comment]
I had the exact same issue a while back when performing a landing challenge. I just started a new flight and it was gone.

**Comment by Benjozork** [comment]
As we have stated on our Discord and Social Media multiple times, only the development and experimental versions are currently compatible.

**Comment by BalaBalaYi** [comment]
ND will crash when using .PLN or .FLT. (tried with stable and dev)

**Comment by 2hwk** [comment]
This issue seems too general and we need a way to reproduce it, there are several existing ND crash/maintenance screen issues up so I'm inclined to close this if there is no way to reproduce.
