### ISSUE TITLE
[BUG] unable to shutdown APU when GroundPower is on/avail

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#3933]
**Mod Version**

Master + FBW

{
  "built": "2021-03-11T06:11:22+00:00",
  "ref": "fbw",
  "sha": "f4fc87c3e18bf84de6c71a0f426140da9451f99b",
  "actor": "aguther",
  "event_name": "manual"
}

**Describe the bug**

Unable to shutdown the APU on stand while Groundpower is connected/avail
Try to fire up the plane for testing, proper cold and dark start after checklist as in real life to program FMS etc. Fire test, APU start. After programming the FMS and look into the new features of the mod, I try to shut down the plane. Try to shut down the APU FAIL. APU remain ON also when the master switch pressed to off. Problem is still there when Groundpower is only avail or in use.
If you taxi out, and the groundpower don´t show "avail", you can shut down the APU normally.

**To Reproduce**

1. start APU on stand while groundpower is connected
2.try to shut down APU while groundpower is connected/avail
3.try to shut down APU after angine start when groundpower is not avail. (e.g. while taxi)

**Expected behavior**

you shoud able to shut down the APU, regardless Groundpower is on/avail or not avail

**Actual behavior**

APU is unable to shut down while on stand with groundpower on/avail

**References**

-

**Additional context**

-
Was this working before/when did the issue start occurring?
don´t know
Is this a problem in the vanilla unmodded game?
-

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
cc. @davidwalschots

**Comment by davidwalschots** [comment]
@andrejetcat I'm unable to reproduce your problem. Note that I didn't test with the custom FBW but with the regular version.
1. I started the APU on a stand with EXT PWR ON.
2. I pushed EXT PWR off, so AVAIL was indicated.
3. I pushed the MASTER SW to OFF.

The APU shut down.

Note that when BLEED AIR was used in the two minutes prior to pressing APU MASTER SW to OFF, the APU will keep running for up to two minutes for cooldown purposes.

**Comment by andrejetcat** [comment]
all right, I tested it again, without anything in the community folder. 
APU works a it should. I filled up the communitiy folder and it works also. 
There has to be an issue with one of an older version of a workingtitle mod. But now its disappear.
You can close this report, sorry that the problem was on my side... I could swear it wasn´t :) 

Thank you for you help, support and you hard work on this outstanding Project!

**Comment by andrejetcat** [comment]
..but another thing, i recognise...

when the Bleed is on, the 2 X´es should disappear and show the bleed pressure, like it does on the bleed ecam page. 
![apu_bleed](https://user-images.githubusercontent.com/72918017/110923847-a2989480-8321-11eb-9c6f-9209ea4a0239.jpg)

**Comment by davidwalschots** [comment]
@andrejetcat I see you deleted a comment on another issue:
> ..but another thing, i recognise... when the Bleed is on, the 2 X´es should disappear and show the bleed pressure, like it does on the bleed ecam page.

Just for your information. Whether or not the bleed data is displayed depends on the ADIRS1 position which must be NAV. Otherwise this value is not measured and therefore not displayed.

We are aware that if you switch the displays to DMC 3, then ADIRU 3 is the one providing the data, and the same is true when you select the air data selector to CAPT ON 3. However, those particulars have not been implemented yet.
