### ISSUE TITLE
sound on efb push back 

### ISSUE THREAD

**Issue by airfirefighter** [flybywiresim/a32nx#3937]
**Is your feature request related to a problem? Please describe.**
no

**Describe the feature you'd like to see implemented**
The God of sound Boris if can add sounds like ground to cockpit release parking brakes, u can start ur engines etc... in efb push back

**Comment by hotshotp** [comment]
Yeah that's definitely possible in the future. It's probably better to make our own pushback service at that point because the default is so limited

**Comment by lionomega** [comment]
if the gpws warnings sounded louder it would be incredible!

**Comment by hotshotp** [comment]
> if the gpws warnings sounded louder it would be incredible!

I promise I will do this in a few days as it is a very highly requested feature

**Comment by hotshotp** [comment]
I was trying to add this before but the msfs pushback simvars are so extremely limited i cannot do this without running into several bugs.
