### ISSUE TITLE
APU start switch should have a delay

### ISSUE THREAD

**Issue by Zyonix007** [flybywiresim/a32nx#394]
it used to have a delay but it was removed for some reason

**Comment by Benjozork** [comment]
Please follow issue templates.

**Comment by UncleClapton** [comment]
not a bug. intentional change after feedback from **MANY** pilots and engineers. This is how it's supposed to work based on everything we've been given.

**Comment by JackZ974** [comment]
Yes. The "delay" between APU MASTER and APU START lighting up is a myth. 
There is an AIRBUS recommendation to wait AT LEAST 3 seconds before pushing the START button in the procedures, but that's it. 

Anyways, the APU itself won't start till the intake flap is fully opened, that takes between 8 to 20 seconds depending on the type of actuators, it's apparently faster on the NEO/

**Comment by NathanInnes** [comment]
Closing this issue as it seems to be intentional.
