### ISSUE TITLE
Overshoots altitude 

### ISSUE THREAD

**Issue by NicklasWabra** [flybywiresim/a32nx#3940]
**Mod Version**
Custom FBW 4cfc87c

**Describe the bug**
When you set and altitude or you make the plane follow managed, it overshoots the altitude

**To Reproduce**
1. Created IFR flight plan 
2. Start at runway
3. After takeoff, engage the autopilot and let the aircraft climb and set an alititude 

**Expected behavior**
Expected to stop at set altitude 

**Actual behavior**
Overshoots altitude 

**References**

**Additional context**

Was this working before/when did the issue start occurring?
It was working before the world update

Is this a problem in the vanilla unmodded game?
not sure, haven't tested 

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Please provide a video recording of the issue.

**Comment by C4n0nymous** [comment]
Same issue happened.
Only vertical speed mod or Level Off the aircraft work. 
![01](https://user-images.githubusercontent.com/9797291/111057308-656b0880-84c1-11eb-999d-e49f0c456f4a.PNG)
![02](https://user-images.githubusercontent.com/9797291/111057309-669c3580-84c1-11eb-9134-745268d24fc8.PNG)
![03](https://user-images.githubusercontent.com/9797291/111057310-6734cc00-84c1-11eb-9b64-98d026268088.PNG)

**Comment by MisterChocker** [comment]
Please show a picture of the performance page.

**Comment by C4n0nymous** [comment]
![01](https://user-images.githubusercontent.com/9797291/111150620-46f03480-85c9-11eb-898a-5316911982fb.PNG)
![02](https://user-images.githubusercontent.com/9797291/111150611-43f54400-85c9-11eb-8125-a8a7eedc2c9a.PNG)
![03](https://user-images.githubusercontent.com/9797291/111150617-46579e00-85c9-11eb-994e-4e56972ce2a1.PNG)

Mod Version
development bbc7ec0

I have reproduce the same situation.

However, I found out that the issue only happen when honeycomb bravo have connected to the PC.
Once connected, ALT mod, OP DES or OP CLB will not work. The autopilot will not control the pitch angle when selected the mentioned mod.
Only vertical speed mod will be work. But the autopilot will not enter to ALT mod and level off the plain when reach the selected altitude.  

I try to disconnect the honeycomb bravo during the flight. The autopilot will resume normal when I re-engage the autopilot.

**Comment by NicklasWabra** [comment]
Can confirm this works. I have the same problem with the bravo
