### ISSUE TITLE
Aircaft dips when engaging AP after takeoff

### ISSUE THREAD

**Issue by simcapt676** [flybywiresim/a32nx#3942]
**Mod Version**
Custom FBW mod via downloader

**Describe the bug**
Shortly after take-off when engaging the autopilot the Aircraft will dive instead of continuing the climb the speed then goes into overspeed before it corrects itself and the proceeds to operate normally  

**To Reproduce**

1.set takeoff power takeoff normally 
2. At acceleration  altitude reduce to climb 
3. Engage AP

**Expected behavior**
Aircraft should continue its managed climb after engaging the AP

**Actual behavior**
Aircraft dives towards the earth causing an overspeed

**References**

**Additional context**

Was this working before/when did the issue start occurring?
I believe it started after the update its a bug that hasn’t corrected with subsequent 
Custom fbw updates

Is this a problem in the vanilla unmodded game? i don’t know have not tested it

Discord username: dragonsnbeer

**Comment by bytetonight** [comment]
Additionally to nose dipping after enabling autopilot after take off and over 400 feet, my aircraft refused to climb, even when pulling the knob which should override constraints I believe.

**Comment by mreza1st** [comment]
The aircraft doesn't gain speed with flaps. They are trying to fix the issue. Do you engage AP before flaps are fully retracted? If yes, then the AP will push the nose down to gain speed.

**Comment by kgaviation** [comment]
For me, engaging the AP is also causing the aircraft to bank hard left and hard right. I keep having this problem along with the AP not following the FP. I’m flying dead on the line and it suddenly banks right for n reason and then back left to correct itself.

**Comment by MisterChocker** [comment]
Please retest with latest dev or stable.

**Comment by MisterChocker** [comment]
Closing since no response from op.

**Comment by simcapt676** [comment]
Its fixed in dev and stable sorry i got busy
