### ISSUE TITLE
NWS INOP on Dev Version 

### ISSUE THREAD

**Issue by Captherky** [flybywiresim/a32nx#3944]
**Mod Version**
Dev Version 64oea13
"built": "2021-03-11T21:22:01+00:00",
  "ref": "master",
  "sha": "e34ae7de64064acc5eb35e452cbdfb4fc62f45cc",
  "actor": "wpine215",
  "event_name": "manual"

**Describe the bug**
After engine start, NWS not working. Flight controls all OK, just NWS INOP.

**To Reproduce**

1. Start Engines.
2. All hydraulics OK All flight controls working
3. NWS switch is on Anti Skid is on, no nose wheel steering.

**Expected behavior**
NWS should work with system activated.

**Actual behavior**
Nose wheel doesnt turn

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Using dev mod  64oeA13 its not working. Release stable version is ok.

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by beheh** [comment]
Are you getting the ECAM warning? Or is it just not working?

**Comment by ChruutvoLuzi** [comment]
have you used the pushback from the efb? the tug sometimes bugs out and stands in place but invisibly

**Comment by davidwalschots** [comment]
As there hasn't been any response to the questions asked. I'm closing this issue.
