### ISSUE TITLE
[BUG] APU and engines will not start

### ISSUE THREAD

**Issue by 512uk** [flybywiresim/a32nx#3947]
**Mod Version**

`{
  "built": "2021-03-11T21:22:01+00:00",
  "ref": "master",
  "sha": "e34ae7de64064acc5eb35e452cbdfb4fc62f45cc",
  "actor": "wpine215",
  "event_name": "manual"
}`

**Describe the bug**

APU and engines will not start in dev branch since latest sim update.

**To Reproduce**

1. Install dev version
2. Launch A32nx in cold and dark
3. Turn on ext power, batteries, pumps, and APU master switch, or engine to IGN and start either engine.

**Expected behavior**

FLAP OPEN to appear on APU ECAM.  Then APU to start when you turn on the APU starter.

**Actual behavior**

* FLAP OPEN does not appear on ECAM.
* Graphical glitch on APU EGT display.
* APU does not start.

**References**

![egt](https://i.imgur.com/0yjI3Rl.png)

**Additional context**

Battery displays on overhead also report 0.0v.

Was this working before/when did the issue start occurring? It worked before the latest update.

Is this a problem in the vanilla unmodded game?

No

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Can you try with no other mods or liveries in your Community folder and report back ?

**Comment by 512uk** [comment]
Yup that fixed it. It seems livery related.  The only things in the Community folder were the Wizzair livery and KLM livery.

**Comment by Benjozork** [comment]
Wizzair livery is known to overwrite the panel definitions, which makes the APU and ELEC modules unable to load.
