### ISSUE TITLE
[BUG] ECAM's, ND, and PFD are not showing correctly

### ISSUE THREAD

**Issue by AI12Gaming** [flybywiresim/a32nx#3948]
**Mod Version**

5.3

**Describe the bug**

The ECAM, PFD, and ND are not working even when Batteries are on

**To Reproduce**

1. I started the game with the mod installed
2. I set a flight plan
3.  I then start the plane

**Expected behavior**

**For ECAM, ND, and PFD to show when i turn on the batteries**

**Actual behavior**

**ECAM, ND, and PFD wont show anything**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by DavidEGTE** [comment]
@AI12Gaming Stable version is not working, try DEV or EXPERIMENTAL

**Comment by AI12Gaming** [comment]
Thanks
