### ISSUE TITLE
Random poor performance

### ISSUE THREAD

**Issue by LFSS** [flybywiresim/a32nx#3949]
**Mod Version**

Dev e34ae7d

**Describe the bug**

All of a sudden, the performance of the whole game drops from 40+ FPS to 1-3 FPS at cruise, clear skies. I could not find anything that might've triggered this behavior, it is truly random

**To Reproduce**

1. Go into a flight using the A32NX 
2. Wait for the poor performance (as I said, it's random)

**Expected behavior**

The performance should be the same as it was with previous versions, something like 40-50 FPS in cruise/clear skies

**Actual behavior**

Performance was horrible and the simulation became just unenjoyable

**References**

**Additional context**

My PC Specs:
i7-6700
GTX 1070
16GB RAM
No other programs running in the background

Was this working before/when did the issue start occurring?
In previous versions, I did not suffer from this poor performance

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
It's extremely unlikely that this is caused by the A32NX

**Comment by Benjozork** [comment]
Can you show a screenshot of your MSFS FPS counter when it happens ?

**Comment by omarsmak** [comment]
I think this has nothing to do with the mod. There are like tons of reports in the official fourms about the performance issues and the stutters that happen every now and then.

**Comment by LFSS** [comment]
> I think this has nothing to do with the mod. There are like tons of reports in the official fourms about the performance issues and the stutters that happen every now and then after SU3

Could be, but never happened to me.

**Comment by LFSS** [comment]
> Can you show a screenshot of your MSFS FPS counter when it happens ?

I forgot to screenshot it, but it literally went from 40 to 2 in a second and stayed like that. 
Out of the same blue, it jumped from 2 to 40 and the cycle repeated 2 more times

**Comment by Paytheon** [comment]
Performance issues are being reported to MSFS 2020 which are not related to A32NX. 
1. https://forums.flightsimulator.com/t/performance-degradation-with-1-14-5-0-upgrade/376202
2. https://forums.flightsimulator.com/t/severe-performance-problem-in-1-14-5-0-identified-and-reported/376863/5
3. https://forums.flightsimulator.com/t/intermittent-performance-spikes-high-time-in-manipulators/368197
4. https://forums.flightsimulator.com/t/fps-drops-again-and-again/377780

This is just a guess, but you should be seeing if this performance issue happens with other ACFT in MSFS too.

**Comment by LFSS** [comment]
> Performance issues are being reported to MSFS 2020 which are not related to A32NX.
> 
> 1. https://forums.flightsimulator.com/t/performance-degradation-with-1-14-5-0-upgrade/376202
> 2. https://forums.flightsimulator.com/t/severe-performance-problem-in-1-14-5-0-identified-and-reported/376863/5
> 3. https://forums.flightsimulator.com/t/intermittent-performance-spikes-high-time-in-manipulators/368197
> 4. https://forums.flightsimulator.com/t/fps-drops-again-and-again/377780
> 
> This is just a guess, but you should be seeing if this performance issue happens with other ACFT in MSFS too.

As I said, it never occurred to me until today, but I see this is something bigger than this mod :) 
Thanks for the links

**Comment by fragtion** [comment]
I've experienced the same exact behavior. Coincidentally, I was using the A32NX mod at the time. I'll personally keep an eye out if this happens with any other planes..

**Comment by DtotheAtotheVtotheE** [comment]
I've had this happen twice with the JustFlight Arrow & once with the stock 172 G1000 since the latest MSFS patch.  I flew 6 hrs in the A320 this weekend and it didn't happen in that.  It's not A32X specific,
