### ISSUE TITLE
Seatbelt audio no longer works without APU or external power 

### ISSUE THREAD

**Issue by Zyonix007** [flybywiresim/a32nx#395]
the seatbelts not longer play sound

**Comment by Benjozork** [comment]
Please follow issue templates.

**Comment by UncleClapton** [comment]
Unable to reproduce. Please ensure you're fully updated to the latest release.

**Comment by JasonO99** [comment]
Tried to reproduce. On battery only and with battery and engines the audio works for me.

**Comment by AdenFlorian** [comment]
closed since we can't repro. If you still see the problem, please provide specific reproduction steps.
