### ISSUE TITLE
FlyPad (pilot's tablet) not saving SimBrief login credentials, and conflicts with aircraft shortcuts.

### ISSUE THREAD

**Issue by notl3ks** [flybywiresim/a32nx#3951]
The FlyPad tablet does not retain the username for SimBrief in-between flights, and has to be re-entered each time a new flight starts. It also conflicts with aircraft shortcuts when punching it into the tablet. For example, when you enter your SB username, you've also flicked/toggled a load of switches in the process, and you have to scan the cockpit again for any changes.

**Comment by Paytheon** [comment]
Just a tid-bit to how I get around the shortcut key conflict with the skypay SB username, I put my SB username on my clipboard and Cntr+V (paste) into the text field.

**Comment by notl3ks** [comment]
> 
> 
> Just a tid-bit to how I get around the shortcut key conflict with the skypay SB username, I put my SB username on my clipboard and Cntr+V (paste) into the text field.

So just copy/paste? Never thought of that, quite a good idea. In regards to having to re-enter it every time, it would be nice if it saves it in some kind of file so it doesn't have to be re-entered each time. I don't know if that's possible with a simple config file?

**Comment by Benjozork** [comment]
Don't ignore the provided issue template

**Comment by notl3ks** [comment]
> 
> 
> Don't ignore the provided issue template

Sorry, I'm not sure what you mean?

**Comment by Benjozork** [comment]
![Uploading image.png…]()

**Comment by notl3ks** [comment]
Oh sorry, it wasn’t there when I made this. Otherwise I would of put that in. I apologise.
