### ISSUE TITLE
[BUG] Nose dives on final just before flare

### ISSUE THREAD

**Issue by fragtion** [flybywiresim/a32nx#3956]
**Mod Version**

Custom FBW d8bfdc0

**Describe the bug**

When approaching the runway, the nose dives abruptly somewhere around 30ft from ground, which needs to be compensated for by pulling back the sidestick harder than normal

**To Reproduce**

1. Initiate landing (Ideally in clear conditions, default (un-customized) plane fuel/load/weights)
2. Take manual control and pass through 50 ft (relative to ground), speed somewhere between 120-130 kts
3. Everything continues normally until nose suddenly pushes downwards for no apparent reason
4. Try another airport with same or different wind/weather conditions, and the same behavior still occurs

**Expected behavior**

Consistent, smooth and predictable descent rate

**Actual behavior**

Sharp, notable nose-diving effect just prior to flare

**References**

**Additional context**

Was this working before/when did the issue start occurring?
This is a new problem since the recent updates and changes to flaps dynamics

Is this a problem in the vanilla unmodded game?
Not sure

Discord username (if different from GitHub): FragtioN

**Comment by LordNecton** [comment]
Im getting the same problem decending under 200kts going to flap 1... Nose dives

**Comment by loganisflying** [comment]
I have had this same problem. What I did to fix this is disable autopilot

**Comment by aguther** [comment]
The custom FBW version implements the flare law according to FCOM information. That means:
- filtered pitch attitude over ~ 20s is memorized at 50 ft
- at 50 ft this memorized value is used as setpoint for a then enabled pitch attitude law
- at 30 ft this pitch attitude is reduced to -2° over 8s

It could be that it's somehow related to the still existing flap issue. For that purpose I pushed the preliminary fix for the fbw branch. It would be a lot better with it.

In regards to AP: if you're on the experimental version with AP turned on you get the default AP and custom FBW taking off it's hands.
