### ISSUE TITLE
[BUG] change the name of this to something normal 

### ISSUE THREAD

**Issue by Zyonix007** [flybywiresim/a32nx#396]
![Microsoft Flight Simulator Screenshot 2020 09 04 - 22 19 43 09](https://user-images.githubusercontent.com/60050366/92295900-1c783d00-eefd-11ea-955a-1bcefd44ef8f.png)

change the name of this

**Comment by Benjozork** [comment]
Please follow issue templates.

**Comment by oliverpope03** [comment]
This can be closed @Benjozork i fixed it the other day didnt realise this was related to that till i saw the picture :)
