### ISSUE TITLE
Dome Light Inop When C&D

### ISSUE THREAD

**Issue by AirbusA320Pro** [flybywiresim/a32nx#3962]
**Mod Version**
{
  "built": "2021-03-14T16:34:50+00:00",
  "ref": "fbw",
  "sha": "bb815b6684d344563b6d16ee2136f81d9b9ff7d8",
  "actor": "aguther",
  "event_name": "manual"
}

**Describe the bug**
When aircraft is spawned cold and dark, dome light switch doesn't turn dome light on

**To Reproduce**

1. Spawn aircraft cold and dark
2. Operate Dome Light switch
3.

**Expected behavior**
Dome light should operate even when there is no electrical power to the aircraft.

**Actual behavior**
Light does not illuminate.

**References**
Dome light is hard wired to the battery bus, so will always illuminate under any/all electrical configs - including cold and dark.

**Additional context**
In event of complete electrical failure, the dome light is the only source of lighting in the flight deck. 

Was this working before/when did the issue start occurring? No.

Is this a problem in the vanilla unmodded game? Yes

Discord username (if different from GitHub): AirbusA320Pro

**Comment by tshomas** [comment]
Hi, can I check your references, as from experience (and many times having to use my phone flashlight) the only way the Dome light functions is with one battery in the ON position?

At the moment, the mod incorrectly puts on both Dome lights with the batteries on and in the Full Bright position which is also wrong. I have references and experience that the only setting with just batteries on is the right hand FO light and also only in DIM.

![IMG_0086](https://user-images.githubusercontent.com/74841560/111079234-01603880-84f1-11eb-9e14-8a22d7a559c6.jpeg)

I do also know from experience that the Dome lights function fine if the Ground Bus has been switched on with a GPU connected but not running the systems, and with the batteries off, is that what you are thinking of?

Discord: Shomas

**Comment by komp1821** [comment]
> Dome light is hard wired to the battery bus, so will always illuminate under any/all electrical configs - including cold and dark.

This is incorrect. The captain's Dome light is attached to DC Ground Service Bus and the F/O's Dome light is DC ESS bus. So you need the ground service network supplied when external power is off. Note that we decided not to model the DC Ground Service Bus for the simulation, because except from that specific function there is no benefit from it.

**Comment by AirbusA320Pro** [comment]
I stand corrected on the HOT bus front in that case. I used to fly the Dash-8 Q400 as well, and that is definitely "agricultural" in it's approach to hot buses etc. 
As @tshomas mentioned above, the sim illuminates both Dome lights on application of at least one battery switch, which is incorrect, no?

**Comment by komp1821** [comment]
> As @tshomas mentioned above, the sim illuminates both Dome lights on application of at least one battery switch, which is incorrect, no?

This is indeed wrong. I'd recommend to keep this issue open. When the ELEC system is fully implemented, we will be able to assign busses to individual devices.
