### ISSUE TITLE
[BUG] ALL Flight controls are now dark / not functional

### ISSUE THREAD

**Issue by HINDSITE2021** [flybywiresim/a32nx#3969]
**Mod Version**
 v0.5.3

**Describe the bug**
 All screens are dark, all digital displays are dark & not functional.  I've tried multiple ways to start the aircraft without any success on the screens.  I've downloaded the development version in the installer, and the screens appear normal.  I then reverted back to the v.0.5.3 with the same results.  

**To Reproduce**
 Start aircraft on the runway
 Noticed the bug when starting a flight from KPIE to KCLT ... it is the same with any airport.
1.
2.
3.

**Expected behavior**
 I expected to use the screens as normal

**Actual behavior**
 No screens / controls

**References**

![image](https://user-images.githubusercontent.com/80644429/111080685-0499fb00-84d6-11eb-9000-5969467b1f8f.png)
![image](https://user-images.githubusercontent.com/80644429/111080696-15e30780-84d6-11eb-86c7-d7e32d36f1ef.png)
![image](https://user-images.githubusercontent.com/80644429/111080765-53e02b80-84d6-11eb-8193-42138960d1f8.png)

**Additional context**

Was this working before/when did the issue start occurring? Yes, working before microsoft update

Is this a problem in the vanilla unmodded game? No mods other than MegaPack liveries and FlyByWire

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
v0.5.3 is not compatible with Sim Update 3
