### ISSUE TITLE
[BUG] Autopilot does not follow the waypoints

### ISSUE THREAD

**Issue by Viopassch** [flybywiresim/a32nx#3972]
**Mod Version**

 "built": "2021-03-14T10:22:15+00:00",
  "ref": "master",
  "sha": "b95fdbffb2eae9bb7e31e166ef00ceabc0b527bb",
  "actor": "Benjozork",
  "event_name": "manual"

**Describe the bug**
When a flight plan is loaded from SIMBRIEF, the airplane goes after the start with engaged AP into a right turn and does not follow the waypoints.

**To Reproduce**

Fly the following route 
LSZH/28 ZUE2V ZUE T163 EMPAX EMPAX1B EDDF/25L
1. Start from 28
2. Engage the AP

**Expected behavior**
The airplane should follow the waypoints

**Actual behavior**
The airplane does not follow the waypoints and starts to bank more and more,

**References**

![image](https://user-images.githubusercontent.com/78740747/111082018-6eca9400-8506-11eb-8958-934751b03565.png)

**Additional context**

Was this working before/when did the issue start occurring?
After the latest MSDS2020 update 1.14.5.0

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by FoxtrotSierra6829** [comment]
Please add a title

**Comment by Benjozork** [comment]
You need to set higher deadzones on your control axis. I can tell they're overriding the AP with drifting because the FD lines are not being followed.

**Comment by Viopassch** [comment]
Thanks for the TIP. It works now.
