### ISSUE TITLE
Hard Bank to the Right, Then Left When Engaging AP

### ISSUE THREAD

**Issue by kgaviation** [flybywiresim/a32nx#3973]
**Mod Version**

Dev. version

**Describe the bug**

After takeoff, when I engage the AP, the aircraft banks hard right and then back left to correct itself.

**To Reproduce**

1. Takeoff
2. Set throttle to CLB detent
3. Set AP to follow the route/FP

**Expected behavior**

The aircraft should smoothly transition into AP and follow the FP. It shouldn’t bank to the right and then back left when flying straight on the line for the flight path.

**Actual behavior**

I created my flight plan using the world map feature in the sim. After take off, I set the throttle to FLX. I then reduced the throttle to the CLB detent and set the AP to follow the flight plan. As soon as I engaged the AP, it immediately banked violently to the right and then back to the left to correct itself and eventually fly straight to follow the flight plan.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Yes. After sim update 3.

Is this a problem in the vanilla unmodded game?
Not sure, I don’t use the vanilla/default A320.

Discord username (if different from GitHub):

**Comment by andrejetcat** [comment]
can confirm that. Do a traffic pattern with vectors to final @ KTEB. While on right downwind RWY29 the plane suddenly turns hard right without any input from my side. I had to turn off the A/P @ nearly 60-70° bank. I was in the Heading mode.

**Comment by MisterChocker** [comment]
Please check your deadzones and attach screenshots.

**Comment by kgaviation** [comment]
All of my deadzones are and have been set at 15%. And I'm not able to take screen shots at the moment.

**Comment by MisterChocker** [comment]
Please provide screenshots.

**Comment by mreza1st** [comment]
I have a similar issue except I get a very hard bank to the left when I engage AP and flight director is also to the left. When AP corrects to the right the bank rate is normal. This started with the new MSFS update, at least as far as I can tell. Not a deadzone issue.

**Comment by loganisflying** [comment]
I have found that this is usually an issue with waypoints. if this happens, go direct to the next waypoint

**Comment by kutak11** [comment]
same here... following FD and when engaging AP lateral part of FD suddenly move left or right causing sharp turn,,, then slowly returning back to original direction

**Comment by kgaviation** [comment]
> same here... following FD and when engaging AP lateral part of FD suddenly move left or right causing sharp turn,,, then slowly returning back to original direction

This is exactly what I keep experiencing. Idk if I'm doing something wrong, but this exact problem keeps persisting. No matter what airport or what route I plan, with the FD centered, it abruptly banks right and then gradually back left to correct itself because it made itself fly off course.

**Comment by MisterChocker** [comment]
Can you please provide screenshots or video footage with the PFD, and MCDU (performance page) visible.

**Comment by Watsi01** [comment]
I can confirm that now. I did a flight imported from simbrief for the first time. And now this appears. Turn to the right and then to the left (FD does the same) to go back on track. Flights planned with the worldmap or another tool don't show this behaviour. It seems to be the simbrief import.

**Comment by kgaviation** [comment]
I can confirm SimBrief is not the issue here. Idk about you, but I always use the worldmap to plan my flights and I'm still experiencing the bank off course and then opposite bank the other way to get back on course. I experience the same behavior with the worldmap. This is a really annoying and unrealistic issue that has lasted a while now.

**Comment by Watsi01** [comment]
Strange, this happened for the first time ever on my side (using simbrief for the first time).

**Comment by Watsi01** [comment]
I still get this with simbrief only (every time). Planning routes with LittleNavMap and export it to MSFS (.pln), I don't get the slightest wobble when activating the AP.
