### ISSUE TITLE
[BUG] Text size in ELEC page in Lower ECAM

### ISSUE THREAD

**Issue by vicentezc** [flybywiresim/a32nx#3974]
**Mod Version**

{
  "built": "2021-03-14T20:39:46+00:00",
  "ref": "fbw",
  "sha": "3a34df3c8c476837beaf362093c6b8a097c0dc4a",
  "actor": "aguther",
  "event_name": "manual"
}

**Describe the bug**

Text size in ELEC  page in Lower ECAM is oversized and doesn't fit the boxes as before. All other ECAM pages are OK.

**To Reproduce**

1. Started cold & dark in KDCA.
2. Imported Simbrief flight plan KDCA-KLGA, flying on Vatsim.

**Expected behavior**

Normal text size in ELEC page to fit the boxes.

**Actual behavior**

Text font in ELEC page is oversized.

**References**

![Screenshot 2021-03-14 231113](https://user-images.githubusercontent.com/74352566/111087209-99c1e180-8520-11eb-9853-fd7f1821fefa.png)

**Additional context**

Issue started when I updated to the latest release.
I had done an update earlier today and the ELEC page didn't have this issue. So the bug was introduced with the last update.
I did a previous flight where ELEC page was OK, I had to restart the sim after that flight, so I updated to the latest CFBW release via the installer. Issue appeared after that update.

Discord username (if different from GitHub): vicentezc

Thanks!

**Comment by davidwalschots** [comment]
I've been unable to reproduce this issue on my machine. There is something interesting regarding the ELEC page compared to other pages, which is that it's the only ECAM page to not have a separate CSS file. I highly doubt that is causing it but it is something I could change.

**Comment by vicentezc** [comment]
Hello,

I updated to today's latest FBW version and I don't have the issue anymore (I forgot to test again with the previous version I had installed).
So can be closed as unreproducible, and will open again if it happens again (next time I will try to remember all the steps I did to reproduce).
I let you close it unless you want to use this issue to create a dedicated CSS file?

Thanks!
