### ISSUE TITLE
unknown CTD from 3 weeks ago. 

### ISSUE THREAD

**Issue by ducky3333** [flybywiresim/a32nx#3977]
**Mod Version**

Lastest DEV/EXT version both same.

**Describe the bug**

cannot certain whichi is causing CTD.  CTD casuing from 3weeks ago, i have been updating everyday , still crashing.

**To Reproduce**

1. updating 
2. switch version. 
3. re-install livery packs.

**Expected behavior**

click overhead panel or MCDU set up

**Actual behavior**

click overhead panel or MCDU set up 
crashed

**References**

https://youtu.be/uaNs6hwhpSw

**Additional context**

I have no idea where the crash is coming from

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

yes. the others aircrafts are fully working . 

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by MisterChocker** [comment]
Do you have any other mods/addons installed?

**Comment by LordNecton** [comment]
Latest DEV Build Im getting CTD as soon as i request Pushback  Not sure if this is related

**Comment by ducky3333** [comment]
> Do you have any other mods/addons installed?

my commnutifolder 
![image](https://user-images.githubusercontent.com/38446386/111422251-b5500680-8731-11eb-8b03-c1b0b2d8dd22.png)

**Comment by MisterChocker** [comment]
Have you tried with only the A32NX installed? (You can move the other folders into a temporary folder)

**Comment by ducky3333** [comment]
> Have you tried with only the A32NX installed? (You can move the other folders into a temporary folder)

![22222](https://user-images.githubusercontent.com/38446386/111466100-332e0500-8766-11eb-8e4f-9109166c1052.JPG)
![11111](https://user-images.githubusercontent.com/38446386/111466102-33c69b80-8766-11eb-8b6f-ab80b356b17e.JPG)

hi. i m just trying these settings.

it has crashed when i taking off .

**Comment by brunocfalcao** [comment]
It might be related with other configuration parameters. I would propose you to check this link:

https://forums.flightsimulator.com/t/walkthrough-avoiding-ctd-s-community-troubleshooting-guide/233847

**Comment by MisterChocker** [comment]
Do you know the RAM usage when the CTD occurs?

**Comment by MisterChocker** [comment]
Closing since no response from the op.
