### ISSUE TITLE
The simulator freezes when importing the flight plan

### ISSUE THREAD

**Issue by NitroMaxx72** [flybywiresim/a32nx#3978]
**Mod Version**
Last Dev/Custom

**Describe the bug**
As soon as I click the Init request button, the simulator freezes, no mods other than A32NX are installed, the problem started 3 days ago on the Custom version, now switched to the Dev version all the same

**To Reproduce**

1. Load up at UUWW Airport at the gate
2. Try importing a flight plan from simbrief UUWW-URSS
3. The simulator freezes

**Expected behavior**
The simulator should not freeze when importing the flight plan

**Actual behavior**
Freezes when importing a flight plan to the MCDU from Simbrief

**References**
![завис](https://user-images.githubusercontent.com/76514417/111123885-e9d09080-8580-11eb-86d0-d813e77381ae.jpg)
![завис1](https://user-images.githubusercontent.com/76514417/111123922-f5bc5280-8580-11eb-8ea7-a4fc3328dd4a.jpg)

Was this working before/when did the issue start occurring?
Yes, it used to work, the problem appeared 3 days ago

Is this a problem in the vanilla unmodded game?
NO

Discord username (if different from GitHub):  Nitro #5130

**Comment by MisterChocker** [comment]
Please post the content of the build_info.json. Also we don't have a version which is called dev/custom.

**Comment by Asianblade** [comment]
pretty sure this guy is trying to cause problems.

**Comment by MisterChocker** [comment]
Closing since no response from the op.
