### ISSUE TITLE
[REQUEST] Quick IRS align

### ISSUE THREAD

**Issue by Alexr03** [flybywiresim/a32nx#398]
**Is your feature request related to a problem? Please describe.**
As per the request in PR #196 this issue is being created.

**Describe the features you'd like to see implemented**
When we get a EFB integrated into the aircraft, we should allow a way to set the speed of IRS alignment. This is the "standard" in most payware level aircrafts in other sims, they allow a way to change the IRS align speed.

**Additional context**
N/A

**Comment by NathanInnes** [comment]
PR #196

**Comment by AdenFlorian** [comment]
We can make a hidden MCDU CHEATS page, that should not be able to be stumbled upon by players, and we can add something for quick align in there.

**Comment by madmonkeyfpv** [comment]
> We can make a hidden MCDU CHEATS page, that should not be able to be stumbled upon by players, and we can add something for quick align in there.

Is this happening and when?

**Comment by ntlgr** [comment]
Would love to see that soon. With the amount of trouble we have with sim bugs and CTDs, having to wait 10 minutes to restart a failed flight is way too much for me.

**Comment by wpine215** [comment]
Implemented.

**Comment by madmonkeyfpv** [comment]
implemented is excellent news, any guide on how we actually do it?

**Comment by scott-vincent** [comment]
I'd like to know how to do this too. I agree with all the FS2020 bugs it's a pain to have to wait 7 minutes for alignment each time.

**Comment by ThatRedMelon** [comment]
In the dev version, it is in MCDU Menu->Options->Align Time. There are 3 options: real, fast and instant, corresponding to align times of 7 minutes+, 90 seconds, and instant. It's not in stable currently.

**Comment by scott-vincent** [comment]
Works great. Thank you.
