### ISSUE TITLE
F-PLN button doesn't work

### ISSUE THREAD

**Issue by Jetleg100** [flybywiresim/a32nx#3984]
**Mod Version**

 Issue with DEV and Master version (all released the last week) 
All fltsim updates. 
All drivers updated. 

**Describe the bug**

Not possible to se the flight plan in DEV mode. It has been like that the latest week (all versions released the latest week) 
Moreover the route is not shown in plan mode, only waypoints. 

When using master branch, all screens are black. 
I have removed most in community folder, but still the same issue. 
Tried to use the installer, still the same. 

**To Reproduce**

1. Start up from cold and dark
2. Power on the aircraft
3. Setup the MCDU (import f-pln from Simbrief into FLTSIM), 
4. Press F-PLN 

![image](https://user-images.githubusercontent.com/80633942/111155578-eba44f00-8594-11eb-844f-71630382f763.png)

**Expected behavior**

Flight plan should be visible and possible to change and look at

**Actual behavior**

Nothing happens
**References**

**Additional context**

Was this working before/when did the issue start occurring?
It was ok before the last Microsoft update. 
Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by ntlgr** [comment]
From your screenshot, it seems all displays are functioning. Have you tried increasing the brightness?

**Comment by Benjozork** [comment]
All your screens seem to work ?

**Comment by Jetleg100** [comment]
All screens work well with DEV version. Problem there is that flight plan in MCDU is not present(button dosen`t work, nothing happen when pressing button).
With master branch installed, all screens are black and nothing happens when adjusting brightness buttons.

**Comment by Jetleg100** [comment]
Video showing F-PLN issue

https://www.youtube.com/watch?v=y-QB0XbmNRw

**Comment by Jetleg100** [comment]
If starting at RWY,  F-PLN button work and shows the complete plan. Seems like this issue occur only from cold and dark.

**Comment by Jetleg100** [comment]
Now i have tried everything.
Both Master ans stable version.
Still had the same issue. 
Deleted all in community folder and installed only the most wanted addons. 
After that all was ok again. 

Thank you very much for suggestions.
