### ISSUE TITLE
Engine models are not symmetric

### ISSUE THREAD

**Issue by YasinLaw** [flybywiresim/a32nx#3997]
**Mod Version**
Stable v 0.5.4

**Describe the bug**
The engine model is not symmetric

![Microsoft Flight Simulator 2021_3_16 17_40_21_LI](https://user-images.githubusercontent.com/36468321/111289966-a2312e00-8680-11eb-9582-05937034de00.jpg)
![Microsoft Flight Simulator 2021_3_16 17_40_01_LI](https://user-images.githubusercontent.com/36468321/111289999-a9583c00-8680-11eb-8f83-8fb0dee0aaa0.jpg)

The left engine has a lump on the left side, but the right engine's lump is also on the left side.

**To Reproduce**
Any liveries reproduce

**Expected behavior**
Two engines are symmetric

**Actual behavior**
Two engines are NOT symmetric

**Comment by ChruutvoLuzi** [comment]
Thats how the LEAP looks like in Reallife

**Comment by YasinLaw** [comment]
> Thats how the LEAP looks like in Reallife

Your words made me feel better now, thx
