### ISSUE TITLE
Speedbrakes deployed at aircraft load

### ISSUE THREAD

**Issue by St54Kevin** [flybywiresim/a32nx#3998]
**Mod Version**

Current dev version as of 16.03.21

**Describe the bug**

When loading the plane, especially on the runway, the speedbrakes are deployed causing a TO warning when setting TO thrust. Speedbrake lever is armed. Same happened to me when spawning at a stand (this was not consistent though).

**To Reproduce**

1. Load onto the runway
2. Check Speedbrake position on the outside view
3. Check lever in armed
4. Disarming will retract the speedbrakes

**Expected behavior**

Speedbrakes should be down

**Actual behavior**

Speedbrakes are up

**References**

![image](https://user-images.githubusercontent.com/448627/111305013-bbbd8000-8656-11eb-9c5f-eb22dfc832e1.png)
![image](https://user-images.githubusercontent.com/448627/111305050-c710ab80-8656-11eb-9b15-72df67484b28.png)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by AirbusA320Pro** [comment]
I've had a similar problem when reloading the aircraft in Dev Mode - the spoilers are armed/deployed, and the flaps are set to Full. Was a bit of surprise when I reloaded to a massive flap overspeed when airborne!

**Comment by donstim** [comment]
Strange. I've never experienced this issue, and been doing tons of starting and restarting on the runway for testing. Could this be a controller or key binding issue?
![Screenshot (725)](https://user-images.githubusercontent.com/70166617/111399657-0523c480-8683-11eb-8b7a-62071c0a91f8.png)

**Comment by beheh** [comment]
Are the affected users potentially using the Thrustmaster TCA Throttle Quadrant *without* the flaps/speedbrake addon? In that case MSFS automatically assign the flaps and speedbrake axes even though they're not connected, and I've seen this presence of bound, yet non-existing axes sporadically cause this behaviour.
The fix is to go into the MSFS joystick settings and unassign these non-existant axes.

**Comment by AirbusA320Pro** [comment]
@beheh you are absolutely correct. I recently got the TMTCATQ without the add-on (although, I'm trying my hardest to get the add-on!), I'll test later to confirm key bindings issue.

**Comment by St54Kevin** [comment]
> Are the affected users potentially using the Thrustmaster TCA Throttle Quadrant *without* the flaps/speedbrake addon? In that case MSFS automatically assign the flaps and speedbrake axes even though they're not connected, and I've seen this presence of bound, yet non-existing axes sporadically cause this behaviour when pausing or restarting the flight.
> The fix is to go into the MSFS joystick settings and unassign these nonexistent axes.

I'm using a normal thrustmaster T16000M HOTAS

**Comment by St54Kevin** [comment]
I could solve this issue by deleting an asssigned Spoilers axis, which somehow got assigned to my Throttle Hardware. Closed
