### ISSUE TITLE
Cannot power up aircraft

### ISSUE THREAD

**Issue by addaw987** [flybywiresim/a32nx#3999]
<!S-- ⚠⚠ Do not delete this issue template! ⚠⚠ -->

**Mod Version**
Latest stable release
**Describe the bug**
Since the simulator update on 9th March I have not been able to power up the aircraft displays.

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Watsi01** [comment]
Are you sure you have the latest stable release (0.5.4) installed?

**Comment by addaw987** [comment]
I downloaded the package A32NX-stable from flybywiresim.com yesterday with the same result

**Comment by Watsi01** [comment]
Pls donwload it again. It was updated 13h ago.

**Comment by addaw987** [comment]
That worked-thanks

**Comment by MisterChocker** [comment]
Please will out the template.

Also
> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning

**Comment by MisterChocker** [comment]
Looks like issue has been resolved.
