### ISSUE TITLE
[BUG] PTU sound too loud

### ISSUE THREAD

**Issue by AdenFlorian** [flybywiresim/a32nx#400]
**Branch**
master

**Describe the bug**
PTU sound too loud when starting the first engine.

**To Reproduce**
1. Start an engine and listen for the PTU barking sound

**Expected behavior**
Should be more quiet, but still audible

**Screenshots or Videos**
n/a

**Additional context**
related: #375

**Comment by JackZ974** [comment]
Actually, IRL the PTU is NEVER heard from the cockpit with the door closed, as the PTU pump itself is located nearly 13meters behind the pilots, right in the main landing gear bay. 

Same applies to the APU whose exhaust is located nearly 30meters and AWAY from the cockpit. Passengers barely hear the APU, how come the pilot could?

This is true as much as any "ambiance" sound such as passenger briefing, cabin chat/noise and the like (even applause), which are never heard from the cockpit. 
Just remember that this is a front Office there, so the minimal amount of sound distraction is required.  ;-)

**Comment by MattPaxtonBel** [comment]
I agree with @JackZ974, PTU noise and APU start and run sound shouldn't be heard in the cockpit especially in an A320neo, when the cockpit door stays open , which less often the case thesis days, we can hear the the CCM greeting the passengers and the PAX briefing during taxi. But the pack sound that goes on when APU/ENG BLEED is applied should stay as this is heard in the cockpit.

**Comment by tareksabet** [comment]
closing now I think it was fixed by #1160
