### ISSUE TITLE
Support for aviaCDU

### ISSUE THREAD

**Issue by aviaworx** [flybywiresim/a32nx#4000]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**

Hi Dev Team,

my name is Mark Foti and I'm the author of www.aviaworx.com.
I would like to discuss with you of adding support for my remote CDU app called aviaCDU.
This can be done fairly easily by using SimConnect. The upcoming Aerosoft CRJ for FS2020 will already feature this and I would love to support the A320!

**References**

**Additional context**

Discord username (if different from GitHub):

**Comment by AndersHogqvist** [comment]
Yes please!!!

**Comment by Benjozork** [comment]
Hello, can you please get in contact with a member of the Development Team on Discord ?

**Comment by aviaworx** [comment]
Sorry, I don't know who the dev team is. Do you have an email address for
them?

**Comment by Benjozork** [comment]
You can write us at:

contact@flybywiresim.com

**Comment by aviaworx** [comment]
Thanks!

**Comment by Narvik-Ramius** [comment]
Definitely FBW support for Aviaworx would be fantastic !

**Comment by Azores77** [comment]
Can you guys at FBW team make this work please?
Using Aviaworx with the CRJ is been a great experience and I would love to have the option to have the FBW A320 cdu working on my tablet as well.

**Comment by tracernz** [comment]
> Can you guys at FBW team make this work please?

As always, patches welcome. I don't see any details on what's actually being requested here so it's difficult to action anything.

**Comment by Azores77** [comment]
> > Can you guys at FBW team make this work please?
> 
> As always, patches welcome. I don't see any details on what's actually being requested here so it's difficult to action anything.

Support to get the cdu working in a tablet like a iPad or Samsung.
The creator of Aviaworx already left a comment above explaining so I don’t understand why you’re not seen any details regarding this.

**Comment by ranXeron** [comment]
Any news about aviaCDU support? Would like to see this working...

**Comment by Benjozork** [comment]
Waiting on the dev to contact me on Discord

**Comment by tracernz** [comment]
> > > Can you guys at FBW team make this work please?
> > 
> > 
> > As always, patches welcome. I don't see any details on what's actually being requested here so it's difficult to action anything.
> 
> Support to get the cdu working in a tablet like a iPad or Samsung.
> The creator of Aviaworx already left a comment above explaining so I don’t understand why you’re not seen any details regarding this.

There are zero details, just a vague proposal.

**Comment by Benjozork** [comment]
I'm talking with the dev.

No promises about anything or any date.

**Comment by judgementkazzy** [comment]
Hello any news on this ??

**Comment by judgementkazzy** [comment]
Any news on this ??

**Comment by tracernz** [comment]
> Any news on this ??

The issue will be closed automatically when any required work is done. No need to ping everybody.

**Comment by judgementkazzy** [comment]
Aha that means it will take 3 years for you guys to create a simple fix for this solution lol, i wish this fuckin game was bigger so we didn't have to rely on fucking third party trash like this for airplanes.

**Comment by Benjozork** [comment]
How about you go make it yourself? Patches welcome.

**Comment by Saschl** [comment]
There is absolutely no need to get rude. And if you already know how to enable the support you are very free to add an enhancement to this project. But this kind of feedback doesn’t bring us anywhere.

**Comment by tracernz** [comment]
> Aha that means it will take 3 years for you guys to create a simple fix for this solution lol, i wish this fuckin game was bigger so we didn't have to rely on fucking third party trash like this for airplanes.

There is only one party you are paying money to here and it isn’t FBW. You are of course free to write the patches yourself, as we all do for the features we desire.

**Comment by Maximilian-Reuter** [comment]
> > Aha that means it will take 3 years for you guys to create a simple fix for this solution lol, i wish this fuckin game was bigger so we didn't have to rely on fucking third party trash like this for airplanes.
> 
> Ah yes, a simple fix. If it's so simple do it yourself and no need to be rude :)

I take it someone pm'd you aswell ? :D

**Comment by aviaworx** [comment]
> Aha that means it will take 3 years for you guys to create a simple fix for this solution lol, i wish this fuckin game was bigger so we didn't have to rely on fucking third party trash like this for airplanes.

I don't know who you are but you, sir, might just be responsible for ruining any motivation these developers invest (for free!!) into developing a very high quality simulation.
I am truly sorry that this type of behavior is being shown and I would like to make it very clear that I admire the work the FBW team is investing into this addon. And I am sure the majority of simmers out there share this opinion and we are thankful for your initiative! Let's all step in and make sure individuals like this don't ruin our hobby! 👍

**Comment by LentuloBatiato** [comment]
> Aha that means it will take 3 years for you guys to create a simple fix for this solution lol, i wish this fuckin game was bigger so we didn't have to rely on fucking third party trash like this for airplanes.

I don't know how you got into the simulation, but I can assure you that you are clueless, an ignorant layman and a person with little or no human qualities, judging by this unpleasant comment. Go back to your sad life and leave those of us who want to enjoy this exciting hobby alone.

Cheer up FlyByWire, I know I don't need to say it, but don't let people like this take away your enthusiasm for your great work and spirit of collaboration with the MSFS community.

**Comment by cavok1984** [comment]
Keep up the fantastic work Flybywire. Perfection cannot be rushed and hearing and reading how you guys work via various media platforms, you don't need to change how you do things. If I had more thumbs you'd certainly get more than two from me

**Comment by Carliolian** [comment]
As a long time user of simserver I would love to see this working with MSFS2020. FBY is fantastic.

**Comment by pre-martin** [comment]
> As always, patches welcome. I don't see any details on what's actually being requested here so it's difficult to action anything.

Basically it is about getting access to the screens of the MCDUs and being able to send events to the MCDU to trigger the keys.

E.g. in P3D you can get access to the CDU screen with the following lines of code:

```
simConnect.MapClientDataNameToID(SDK.PMDG_NGX_CDU_1_NAME, SDK.IDs.PMDG_NGX_CDU_1_ID);
simConnect.AddToClientDataDefinition(SDK.IDs.PMDG_NGX_CDU_1_DEFINITION, 0, (uint) cduDataAreaSize, 0.0f, SimConnect.SIMCONNECT_UNUSED);
simConnect.RegisterClientDataDefineStruct<SDK.PMDG_NGX_CDU_Screen>(SDK.IDs.PMDG_NGX_CDU_1_DEFINITION);
simConnect.RequestClientData(SDK.IDs.PMDG_NGX_CDU_1_ID, DataRequests.CduRightRequest, SDK.IDs.PMDG_NGX_CDU_1_DEFINITION, SIMCONNECT_CLIENT_DATA_PERIOD.ON_SET, SIMCONNECT_CLIENT_DATA_REQUEST_FLAG.CHANGED, 0, 0, 0);
```

No idea if there are other ways in MSFS. At least the [MSFS SDK](https://docs.flightsimulator.com/html/index.htm#t=Programming_Tools%2FSimConnect%2FSimConnect_API_Reference.htm) still contains these functions.

It looks like if the relevant data is in [A320_Neo_CDU_MainDisplay.js](https://github.com/flybywiresim/a32nx/blob/master/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js)

**Comment by Benjozork** [comment]
The CDU is made in JavaScript and not C++ so therefore it doesn't use simconnect. This makes it especially complicated for us.

I'm working on a way to address this with the new MCDU @Lucky38i is working on.

**Comment by pre-martin** [comment]
If there is something that I could test for you (concerning access to the MCDU), please feel free to come back to me.

**Comment by scheffchoch** [comment]
Ah yes, I've been looking for this. Looking forward to when we get it working!

**Comment by EcstaticAviator** [comment]
This would be huge for the FBWA320

**Comment by Lunatic104** [comment]
This is a must have, saves a lot on a hardware CDU.

**Comment by Neld** [comment]
Would love this! Have all my support!

**Comment by joeherwig** [comment]
Did you notice #1616 Web MCDU Request?
As i know, there is already a PR in #3467 which also seems to adress that.

See also the [discussions](https://github.com/flybywiresim/a32nx/search?q=websocket&type=discussions).

I'm just missing an easy approach to grab the display of the MCDU (including colors) to build it.
so if you have an idea for that as well... ;-)

**Comment by pre-martin** [comment]
@joeherwig The PR #3467 that you mentioned, is now merged on the master. This feature also transmits the screen content over a websocket. For example:

```
{
    "right": {
        "lines": [
            [
                "",
                "{white}SELECT {end}",
                ""
            ],
            [
                "{green}<FMGC (REQ){end}",
                "{white}NAV B/UP>{end}",
                ""
```

So it should be quite easy to use this websocket for your own purposes.

As #3467 already contains a complete MCDU for the browser, I think that there is no need for aviaCDU. Or aviaCDU could use this websocket instead of SimConnect.

**Comment by sidnov** [comment]
Pre-requisite framework for a web/app-based MCDU is available on the development version https://docs.flybywiresim.com/fbw-a32nx/feature-guides/web-mcdu/
