### ISSUE TITLE
Entering Simbrief username in "Company" tab (EFB), turns off multiple lights

### ISSUE THREAD

**Issue by bgey** [flybywiresim/a32nx#4004]
**Mod Version**

{
  "built": "2021-03-15T18:52:38+00:00",
  "ref": "fbw",
  "sha": "ccf27c4bd620603d50c861424b17f7d9141f8adf",
  "actor": "aguther",
  "event_name": "manual"
}

**Describe the bug**

When entering my Simbrief username in the company tab of the iPad/EFB, several lights turn off (dome light, integral lights and others). The switch / knobs remain in place but the light is not displayed any more. Manipulating the switches and/or knobs, turns the lights on again.

**To Reproduce**

1. Start cold and dark
2. Turn on batteries
3. Turn on iPad
4. Turn on external power
5. Increase brightness of cockpit lights and turn on dome lights
6. Go to the "company" tab on the iPad
7. Enter a username
8. Dome light and integral lights go dark

**Expected behavior**

Lighting effects should not be affected by entering a username on the iPad.

**Actual behavior**

Dome light and integral lights (among others) go dark.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Don't really know, have just started using the A320nx mod intensively

Is this a problem in the vanilla unmodded game?
n.a.

Discord username (if different from GitHub): Benny (CEO)

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
This is a limitation of MSFS
