### ISSUE TITLE
MCDU PROGRESS PAGE: add bearing and distance to waypoint functionality 

### ISSUE THREAD

**Issue by Tiebo** [flybywiresim/a32nx#4006]
**Is your feature request related to a problem? Please describe.**
no

**Describe the feature you'd like to see implemented**
On the mcdu PROG page you should be able to insert any waypoint or runway threshold into the BRG / DIST TO field via LSK4R.
It should then calculate the bearing in degree and the direct distance in NM. 

**References**
https://www.aerofly.com/dokuwiki/lib/exe/fetch.php/wiki:a320_mcdu_progress_bearing.jpg?w=300&tok=a27ca4
![image](https://user-images.githubusercontent.com/44509310/111376764-2a72fb80-86a0-11eb-80c6-6f239272ccef.png)

**Additional context**
This does not sound like an important field, but it is a main tool for pilots to calculate the descent profile.

Discord username (if different from GitHub): Tiebo

**Comment by tracernz** [comment]
https://github.com/flybywiresim/a32nx/pull/3752

**Comment by Tiebo** [comment]
@tracernz good to hear that it's already taken care of. I'd appreciate a ping when the pr is open
