### ISSUE TITLE
EFB: add possibility to change the efb side to FO or CPT 

### ISSUE THREAD

**Issue by tmaihoff** [flybywiresim/a32nx#4008]
**Is your feature request related to a problem? Please describe.**
I'm flying the A320 from the right side and it's quite annoying to have the efb on the left side only. 

**Describe the feature you'd like to see implemented**
It would be nice to either have the efb duplicated or add the setting to choose the position (CPT or FO) 

Discord username (if different from GitHub): Tiebo

**Comment by St54Kevin** [comment]
I also would love this

**Comment by MariusSchuller** [comment]
Hey guys,
I don`t quite get why this request has not drawn more attention to it. Having the EFB only on the CPT side makes the flight experience so much less enjoyable for anybody flying on the FO side (and I guess that`s a lot of people).

Wouldn`t it be possible to "mirror" the EFB on the FO side (screens linked) or even "copy-paste" the code on the FO side for two completely separete EFB? I don`t think having the possibility to chose the side is the right way to go, just having the EFB on both sides by default would be appreciated by so many people!
