### ISSUE TITLE
MCDU, pushing the F-PLN key, UTC and DIST values don't work

### ISSUE THREAD

**Issue by Res72** [flybywiresim/a32nx#4009]
**Mod Version**

0.5.4

**Describe the bug**

UTC and DIST indications on MCDU remain the same during the flight

**To Reproduce**

1. Load any IFR flight
2. Push F-PLN key on MCDU and observe UTC and DIST values.
3. Start the flight and you see that they don’t change during it.

**Expected behavior**

Like in the 0.5.3 version, UTC and DIST values show the estimated time of arrival and the remaining distance to destination and they change during the flight.

**Actual behavior**

In 0.5.4 version, UTC and DIST values displayed on MCDU remain the same during the flight.

**References**

For example, like in the Asobo A320 Neo, which has a non-accurate MCDU, the DIST value is a fixed number that represents the total distance to destination and it remain the same during the flight instead of decrease when the aircraft is reaching the destination. This was an error that was not present on the accurate A32NX MCDU and worked perfectly up to release 0.5.3

**Additional context**

These 2 values displayed on MCDU (UTC and DIST) still work good in the developer version of A32NX.

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by MisterChocker** [comment]
Please follow the template in fill in the fields.

Also

> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning

**Comment by Res72** [comment]
Hi. 
Mod Version: 0.5.4

Describe the bug
UTC and DIST indications on MCDU remain the same during the flight

To Reproduce
1) Load any IFR flight 
2) Push F-PLN key on MCDU and observe UTC and DIST values. 
3) Start the flight and you see that they don’t change during it. 

Expected behavior
Like in the 0.5.3 version, UTC and DIST values show the estimated time of arrival and the remaining distance to destination and they change during the flight. 

Actual behavior
In 0.5.4 version, UTC and DIST values displayed on MCDU remain the same during the flight. 

References
For example, like in the Asobo A320 Neo, which has a non-accurate MCDU, the DIST value is a fixed number that represents the total distance to destination and it remain the same during the flight instead of decrease when the aircraft is reaching the destination. This was an error that was not present on the accurate A32NX MCDU and worked perfectly up to release 0.5.3

Additional context
These 2 values displayed on MCDU (UTC and DIST) still work good in the developer version of A32NX. 

Kind Regards.

**Comment by MisterChocker** [comment]
Thanks for the response, I've updated your issue with your response. You can edit it yourself by clicking on the menu and then select edit. 
![image](https://user-images.githubusercontent.com/1857322/111542200-b6088d00-8771-11eb-8c73-93dc95612977.png)

**Comment by Res72** [comment]
Thanks a lot!

Arcangelo Zurlo 
(Inviato da iPhone)

**Comment by Res72** [comment]
Thanks a lot!

**Comment by ed196312339** [comment]
I have noticed the same issue with the flight plan in the FMC during flight. The distance between way points stays the same and the distance to the airport also. I am flying the latest stable version.

**Comment by Res72** [comment]
Hi. What do you mean for latest stable version? The 0.5.3? In my case I tried too, but all displays and MCDU remain dark using 0.5.3 version. 
Regards.

**Comment by Benjozork** [comment]
> Hi. What do you mean for latest stable version? The 0.5.3? In my case I tried too, but all displays and MCDU remain dark using 0.5.3 version. 
> Regards. 

The latest version is 0.5.4

**Comment by Res72** [comment]
Ok, I know. And the issue I opened on flight plan on FMC is related to release 0.5.4 in my case

**Comment by erso44** [comment]
I checked and it is working fine.

**Comment by Res72** [comment]
Yes, thanks. But I was talking about version 0.5.4

Arcangelo Zurlo 
(Inviato da iPhone)

**Comment by Benjozork** [comment]
Version 0.5.4 is unsupported, please use 0.6.1 or dev

**Comment by Res72** [comment]
Ok. Maybe there’s an issue due to my English. I try to explain another time: when I wrote about the MCDU issue I was referring to the current (at that time) version, which was the 0.5.4. 
Starting from next version, the issue was solved and now I’m flying with 0.6.1 stable version without any issue. 
Kind Regards 

Arcangelo Zurlo 
(Inviato da iPhone)
