### ISSUE TITLE
Black display

### ISSUE THREAD

**Issue by CptRPeralta93** [flybywiresim/a32nx#4014]
Hello everyone,

I have the latest development version and the latest update of the game, and about 2/3 days ago, my display that show HDG is completly black and i dont know how to fix it. 
![320Cockpit](https://user-images.githubusercontent.com/72822967/111517245-c3f7e700-874c-11eb-988f-67af9cdeff74.jpg)

**Comment by Benjozork** [comment]
First, please respect the provided template.

Second, this is a known issue listed in the MSFS known issues on the Sim Update 3 changelog. Please follow the workaround described there, which is to restart the flight.

**Comment by BillyGeoThink2020** [comment]
Fantastic my laptop waS also like that and I broke it into pieces. Can't fuckin belive it

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________
