### ISSUE TITLE
flaps control by axis issue with "flaps1/1+F"

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#4015]
**Mod Version**

Dev + FBW

**Describe the bug**

If you try to extend flaps with e.g. flap-lever (thrustmaster Airbus edition) or any other device, with control the flap via an axis, the flaps do not move correctely to position "flaps 1" on approach. They move into the Flaps 1+F possition, which is for takeoff.
If you select the flaps bei "F7" or clicking the flap lever in the cockpit, it works as it should. 

**To Reproduce**

1.start cold and dark
2.make a flight of your choice
3.try to lower the flaps on approach via a flap axis VS. button control/mouse by clicking flap lever

**Expected behavior**

flaps should work with axis device as with button control

**Actual behavior**

"Flaps1" on approach is always "Flaps1+F" if selected by an axis device

**References**

-

**Additional context**

-
Was this working before/when did the issue start occurring?
-
Is this a problem in the vanilla unmodded game?
-

Discord username (if different from GitHub):

**Comment by ErikNL80** [comment]
Noticed the same yesterday... Could it be related to the latest Sim Update? There was a difference in flaps 1 and flaps 1+F, but since SU3 there is only 1+F, which also caused the drag issues?

**Comment by donstim** [comment]
Please follow the template. You did not indicate whether this is a problem with the vanilla unmodded game, so I had to do that. It is an MS/Asobo issue, not a FBW one. I suggest you fill out a Zendesk report.  There is nothing we can do about this.

**Comment by andrejetcat** [comment]
sorry about that

**Comment by donstim** [comment]
I guess this kind of goes together with the recently introduced bug in MSFS where it uses the same lift and drag for CONF 1 and 1+F anyway. :-)

**Comment by Rameyuk** [comment]
Can we have a custom Flapsconfig.ini file and Spoilerconfig.ini file with custom level? I wonder if having a custom flaps level would allow the sim to interpret between conf 1 vs conf 1+F.

I'm also thinking of the custom spoilers config ini file to re-scale the spoilers when using a Spoilers axis. This is to set a deadzone and ignore the first 25% as input and assign it as a Arm ground spoilers without deploying the speed brake. Then the remaining axis is a valid speedbrake input.

**Comment by donstim** [comment]
> Can we have a custom Flapsconfig.ini file and Spoilerconfig.ini file with custom level? I wonder if having a custom flaps level would allow the sim to interpret between conf 1 vs conf 1+F.
> 
No, this would not affect the CONF 1 and 1+F issue. Both configurations share a single "position within the flight model. There is no separation between CONF 1 and 1+F in terms of an axis position.  

There is a function within the MSFS flight model that prevents the flap portion from deploying when going from flaps up to CONF 1 in the air. In the air within MSFS  you can only get to 1+F if selecting it from CONF 2. The problem appears to be that when you set flaps to an axis, it always "reads" it as approaching from CONF 2. I've tried reversing the axis and going from each direction, and it doesn't seem to matter.

**Comment by aguther** [comment]
> Can we have a custom Flapsconfig.ini file and Spoilerconfig.ini file with custom level? I wonder if having a custom flaps level would allow the sim to interpret between conf 1 vs conf 1+F.
> 
> I'm also thinking of the custom spoilers config ini file to re-scale the spoilers when using a Spoilers axis. This is to set a deadzone and ignore the first 25% as input and assign it as a Arm ground spoilers without deploying the speed brake. Then the remaining axis is a valid speedbrake input.

Well, in the experimental version there is now custom spoiler and flaps handling and I already thought about what you said about the spoiler axis.

At the moment the custom flaps handling is behaving like before, but @donstim is working on a updated flight model that will contain distinct positions for 1 and 1+F. When this is done I can easily switch to the new one and it will work properly and following the logic from FCOM. For example, when going from handler position 2 -> 1 below 210 kts it should go to 1+F, but when doing the same from 0 -> 1 it will be 1.

**Comment by aguther** [comment]
Available on development version now.
