### ISSUE TITLE
HOT AIR pushbutton ECAM representation

### ISSUE THREAD

**Issue by mjuhe** [flybywiresim/a32nx#4018]
**Mod Version**

  "built": "2021-03-17T21:42:54+00:00",
  "ref": "master",
  "sha": "5882d47b8e8dc4ce3e011dd9c8d32aaec4181ad5",
  "actor": "MisterChocker",
  "event_name": "manual"

**Describe the bug**

According to the FCOM, when the HOT AIR pb is depressed and OFF, the COND page should show the valve as closed in amber. It currently shows the valve as closed in green.

**To Reproduce**

1. Spawn in C&D, runway or in the air.
2. Switch the lower ECAM page to COND
3. Depress the HOT AIR pb in the AIR COND overhead panel and observe what happens on the ECAM display

**Expected behavior**

The COND page should show the valve closed in amber instead of green.

**Actual behavior**

The COND page shows the hot air valve closed in green.

**References**

![image](https://user-images.githubusercontent.com/60938089/111614886-09152b00-87d8-11eb-90be-f5cecc47987d.png)
![image](https://user-images.githubusercontent.com/60938089/111615437-a7a18c00-87d8-11eb-9fb5-6db0d341d244.png)

**Additional context**

Was this working before/when did the issue start occurring?
To my knowledge this hasn't been changed since the introduction of the COND page to the mod.

Is this a problem in the vanilla unmodded game?
Yes, no other mods installed.

Discord username (if different from GitHub): Commander Ga#1548

**Comment by tracernz** [comment]
cc @RichardPilbery

**Comment by mjuhe** [comment]
I can try to submit a small PR myself if no one is currently working on this.

**Comment by RichardPilbery** [comment]
I'm just testing my PR now!
