### ISSUE TITLE
[BUG] Self test coming on when starting APU with external power on

### ISSUE THREAD

**Issue by AdenFlorian** [flybywiresim/a32nx#402]
**Branch**
master

**Describe the bug**
I think this is causing PFD and MFD to go into self test when turning on the APU, even though I'm on external power.

Also causes self test when leaving external power, even though my apu or engine is up and running.

**To Reproduce**
spawn cold and dark
turn on batteries and external power
turn on PFD/ND/ECAM displays
wait for self test to finish
turn on apu master and starter
wait for lap to open and apu to start spinning up
once that happens the PFD and MFD go into self test, but this shouldn't happen because we are on external power

**Expected behavior**

**Screenshots or Videos**
![image](https://user-images.githubusercontent.com/3533988/92298848-c7dfbc80-ef12-11ea-86f6-e3e71b04b3ae.png)

**Additional context**
We think it's caused by #363

**Comment by CoffeePanda0** [comment]
Yep I can agree with this, had the same issue starting and turning off APU since #363

**Comment by topiek-fs** [comment]
Since I caused this, I might aswell fix it, working on it! Thanks for reporting :)

**Comment by CoffeePanda0** [comment]
> 
> 
> Since I caused this, I might aswell fix it, working on it! Thanks for reporting :)

I found the issue, it is here:
```
if((FOKnobChanged || CAPKnobChanged || (externalPowerChanged || apuStatusChanged)) && !this.selfTestTimerStarted) {
            this.selfTestDiv.style.display = "block";
            this.selfTestTimer = 14.25;
``` apuStatusChanged needs to be removed
Do you wanna make the pull request?

**Comment by topiek-fs** [comment]
> 
> 
> > Since I caused this, I might aswell fix it, working on it! Thanks for reporting :)
> 
> I found the issue, it is here:
> 
> ```
> if((FOKnobChanged || CAPKnobChanged || (externalPowerChanged || apuStatusChanged)) && !this.selfTestTimerStarted) {
>             this.selfTestDiv.style.display = "block";
>             this.selfTestTimer = 14.25;
> ```
> 
> apuStatusChanged needs to be removed
> Do you wanna make the pull request?

That doesn't completely fix it though, as you can turn on the APU without ever being connected to external power, and they should still self test.

**Comment by topiek-fs** [comment]
I looked into it more, but I can't find a fix that will fix this quickly. As I don't have alot of time, please feel free to fix this issue if you know how to fix it properly.

**Comment by JasonO99** [comment]
Noted this, had the same issue when switching between.

Am I right in thinking they should only self-test when power is taken away from them and then restored?

**Comment by CoffeePanda0** [comment]
> 
> 
> > > Since I caused this, I might aswell fix it, working on it! Thanks for reporting :)
> > 
> > 
> > I found the issue, it is here:
> > ```
> > if((FOKnobChanged || CAPKnobChanged || (externalPowerChanged || apuStatusChanged)) && !this.selfTestTimerStarted) {
> >             this.selfTestDiv.style.display = "block";
> >             this.selfTestTimer = 14.25;
> > ```
> > 
> > 
> > apuStatusChanged needs to be removed
> > Do you wanna make the pull request?
> 
> That doesn't completely fix it though, as you can turn on the APU without ever being connected to external power, and they should still self test.

Yeah true, is there a var to see if ground power or engine gen power is connected?

**Comment by ThePilot916** [comment]
> > Since I caused this, I might aswell fix it, working on it! Thanks for reporting :)
> 
> I found the issue, it is here:
> 
> ```
> if((FOKnobChanged || CAPKnobChanged || (externalPowerChanged || apuStatusChanged)) && !this.selfTestTimerStarted) {
>             this.selfTestDiv.style.display = "block";
>             this.selfTestTimer = 14.25;
> ```
> 
> apuStatusChanged needs to be removed
> Do you wanna make the pull request?

I'm working on remodeling the whole of electrical systems right now(will take some time, quite handful)

I'd suggest you all to not worry about fixing this until the electrical system modeling is completed, but will send in a simple fix with a PR soon.

**Comment by AdenFlorian** [comment]
i tested the PR before merging and it works
