### ISSUE TITLE
Takeoff and landing checklists displayed at the same time

### ISSUE THREAD

**Issue by 03vmate** [flybywiresim/a32nx#4025]
**Mod Version**
Custom FBW(545c472)

**Describe the bug**
Takeoff and landing checklists are displayed at the same time overlaid on each other after takeoff.

**To Reproduce**
Didn't have time to narrow down what exactly causes this, but doing the following reproduces it consistently:
Takeoff with flaps 3, no autothrottle
Retract gears right after rotate and turn on autothrottle
Set flaps to full, and don't climb

I'll update this issue later when I can narrow down the simplest configuration that causes this problem

**Expected behavior**
Not exactly sure about what the correct behavior should be, but both checklists shouldn't be shown overlaid on top of each other.

**Actual behavior**
Takeoff and landing checklists are displayed at the same time overlaid on top of each other

**References**
https://imgur.com/N2uALxy

**Additional context**
Latest version of MSFS as of March 18

Was this working before/when did the issue start occurring?
No

Is this a problem in the vanilla unmodded game?
Yes

Discord username (if different from GitHub): Green#4747

**Comment by MisterChocker** [comment]
You need to set takeoff thrust (FLX or TOGA)
