### ISSUE TITLE
Wrong value-description in approach-phase on performance page

### ISSUE THREAD

**Issue by Docretro** [flybywiresim/a32nx#4039]
**Mod Version**

  "built": "2021-03-18T05:12:53+00:00",
  "ref": "fbw",
  "sha": "545c47204bd9d7c99197555c5687dc2bd79c2f6c",
  "actor": "Benjozork",
  "event_name": "manual"

**Describe the bug**
When entering the speed in the takeoff phase in the perf-page of the MCDU the
descriptions "V2" and "VR" are switched. 

**To Reproduce**

1. spawn at any place
2. Energize cockpit and got into MCDU Perf and scroll to the takeoff phase

**Expected behavior**
 It should be the sequence
"V1, V2, VR"

**Actual behavior**
it is "V1,VR,V2"

**References**
See screenshot

**Additional context**

Was this working before/when did the issue start occurring?

worked within the last dev mods

Is this a problem in the vanilla unmodded game?

no

Discord username (if different from GitHub):
![MCDU perf page](https://user-images.githubusercontent.com/77463033/111876738-652aab80-89a0-11eb-998d-8c2d6a998207.png)

**Comment by ThatRedMelon** [comment]
The current format is correct, it should go V1, VR, V2
![image](https://user-images.githubusercontent.com/34657891/111876795-4aeccf80-8998-11eb-9627-f3aa1ebfe10e.png)

**Comment by Docretro** [comment]
sorry, have to correct.  I read it wrong and therefore I close the issue.
Thanks for the info @ThatRedMelon
