### ISSUE TITLE
[RMP] Backup Tuning

### ISSUE THREAD

**Issue by Adi-18** [flybywiresim/a32nx#4044]
**Mod Version**
Released v0.5.4 (by installer)

**Describe the bug**
Since v0.5.4 I cannot set NAV → ILS. Light is on, but the knop is changing previous activation i.e. VOR, NAV or COM

**To Reproduce**
1. Start FS
2. Start Game in cold-and-dark or direct fly with A32NX
3. Init cockpit and wait to all ready (if c-n-d)
4. Press NAV→VOR
5. Use tuning knob → it will change correct frequency
6. Press i.e. VHF-1
7. Use tuning knob → it will change correct frequency
8. Press NAV→ILS
9. Use tuning knob → it will change **VHF-1** frequency

**Expected behavior**
Changing frequency for ILS using knop.

**Actual behavior**
Change of wrong (previous selected radio control) frequency.

**References**
![image](https://user-images.githubusercontent.com/29123730/111898135-6a313e80-8a24-11eb-85c1-0290144d9f58.png)

**Additional context**

Was this working before/when did the issue start occurring?
It works with previous  released version

Is this a problem in the vanilla unmodded game?
No

**Comment by Rameyuk** [comment]
I actually never use the radio stack to tune in to ILS. I always use the MCDU, NAV RAD page, and enter the ILS frequency there. Never failed me.

**Comment by Adi-18** [comment]
Yes on MCDU it works. But if there is an button as designated, its much easy to use this, especially in using my checklist procedure for my touch & go manoeuvre flying.

**Comment by tracernz** [comment]
RMP is a backup option for navaid tuning and should not normally be used in the real aircraft as it de-activates radionav positioning in the FMGC. It’s also not currently possible with the new RMP in dev version, but not sure why it wouldn’t work in 0.5.4.

**Comment by AirbusA320Pro** [comment]
@Adi-18 just purely from a "proper use" point of view: the Nav backup selector is not something we'd use in real life. It's a "guarded switch" which means you'd use it under very specific circumstances and only with confirmation from a second pilot. Because it's a backup, it has limited effectivity. It will have consequences for the FMGC, Nav accuracy etc as you're bypassing the normal tuning methods. 
You mention it's easier to use, but in my experience dialling a frequency takes much more "heads down" time using the radio stack. Why not type the three letter ILS code into the RAD NAV page? It's much less time and effort.

**Comment by jfwharton3975** [comment]
Well now it seems to be broken in both the stable and dev versions.  I cannot enter an ILS frequency and course in the nav panel and I cannot enter them into the MCDU either.  The frequency I can enter but it will not let me enter a course.  I have loaded the approach into the MCDU which normally sets up the ILS frequency and course in the MCDU.  I removed the mod and tried the default A320 and can't enter an ILS frequency in the default either.

**Comment by tracernz** [comment]
You can't enter a course because that is not yet implemented.

**Comment by Adi-18** [comment]
Now after long break flying A320, I tried to fly from LSZH to EDDH

I did not have any landing runway until clearance near to destination.
After clearance for ILS23 I inserted it in F-PLN:
![image](https://user-images.githubusercontent.com/29123730/114315753-9e1df200-9b00-11eb-8958-3f482fb99d11.png)

But no ILS is found (I activated LS). So I go to RAD NAV and inserted code (IHHW) and I have "NOT ALLOWED:
![image](https://user-images.githubusercontent.com/29123730/114315857-2dc3a080-9b01-11eb-9e6f-1a4f90930765.png)

So I am not able to set ILS and had a blind landing...

BTW for my root question: In real live you can enter ILS by pressing NAV→VOR (in confirmation of F/O panel of course) so please implement those again 🙏

**Comment by tracernz** [comment]
Entering IDENT for ILS is also not yet implemented. You can enter the frequency.

**Comment by juliansebline** [comment]
Can try to fix with within #7105

**Comment by juliansebline** [comment]
For reference:

https://www.smartcockpit.com/docs/A320-Navigation.pdf (PAGE 24)

https://youtu.be/qpL23wnNNEI?t=1770

**Comment by juliansebline** [comment]
I am not going to fix in [the RMP fix](https://github.com/flybywiresim/a32nx/pull/7105), I'd rather create a new branch as it's a feature

**Comment by tracernz** [comment]
Yes, I'd rather wait until the FMGC side is tackled in fms-v2, or it cannot really work.
