### ISSUE TITLE
All avionics dead since latest Installer and DEV update

### ISSUE THREAD

**Issue by AdamNZ** [flybywiresim/a32nx#4046]
**Mod Version**

{
  "built": "2021-03-20T16:23:25+00:00",
  "ref": "master",
  "sha": "a0ec8ec484503d3750a6801f2feb09898fc6c40e",
  "actor": "MisterChocker",
  "event_name": "manual"
}

**Describe the bug**

I've not had this problem before (though I've seen other people reporting it in the past). It started happening after the latest downloader update and corresponding new/last DEV version.

I have *nothing* in the Community folder apart from the [new] flybywire-aircraft-a320-neo folder.

Neither Cold & Dark nor runway start work.

Will now test the latest STABLE version (via the new downloader).

**To Reproduce**

1. Usual aircraft selection and start - either C&D or on runway.
2.
3.

**Expected behavior**

Avionics should come alive after APU start.

**Actual behavior**

It's dead, Jim LOL!

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Worked fin up until the latest update(s).

Is this a problem in the vanilla unmodded game?

No ... works fine.

Discord username (if different from GitHub):

[LINE REMOVED!]

**Comment by mrlund** [comment]
Can concur. Interesting observation is that it might affect other aircraft too. I started in the King Air 350 and had the avionics die on me after a few minutes of flight. Starting in the Airbus avionics are out from the start, and power voltage reads 0 for both, regardsless of engine gen/apu/battery state.

**Comment by BjoernHund** [comment]
I noticed the same bug with the new installer this morning. I installed the latest developer version. With the new renamed folder for the A32NX the displays are all black.

After I installed the latest dev version manually - folder name A32NX - everything works as expected.

This version works
```json
{
  "built": "2021-03-20T16:23:25+00:00",
  "ref": "master",
  "sha": "a0ec8ec484503d3750a6801f2feb09898fc6c40e",
  "actor": "MisterChocker",
  "event_name": "manual"
}
```

**Comment by AdamNZ** [comment]
I'd love to say "good catch" ... but that didn't work for me!!

**Comment by MisteurJ** [comment]
Same thing here, with the new installer this morning...
Tried the dev, stable and fbw version, same things, batteries are 0v, screens are blank.

**Comment by BjoernHund** [comment]
> I'd love to say "good catch" ... but that didn't work for me!!

You must manually remove the new created folder from your community folder. Then extract the manually downloaded version in your community folder.

**Comment by BjoernHund** [comment]
I noticed that the version downloaded by the new installer is missing the `layout.json`.

**Comment by BjoernHund** [comment]
The next thing I noticed is, that all the instruments in the folder `flybywire-aircraft-a320-neo\html_ui\Pages\VCockpit\Instruments\A320_Neo` are missing.

I think, that's a problem of the packages in the cdn and not a problem with the installer

**Comment by wlouckx** [comment]
> > I'd love to say "good catch" ... but that didn't work for me!!
> 
> You must manually remove the new created folder `flybywire-aircraft-a320-neo` from your community folder. Then extract the manually downloaded version in your community folder.

For some reason this gives me the stock A320..

**Comment by BjoernHund** [comment]
> or some reason th

You must remove the folder `flybywire-aircraft-a320-neo` from the community folder. Then download the version you wish from the github site. Then you must extract that zip in your community folder. After that, there must exist a folder with the name `A32NX`

**Comment by wlouckx** [comment]
> > or some reason th
> 
> You must remove the folder `flybywire-aircraft-a320-neo` from the community folder. Then download the version you wish from the github site. Then you must extract that zip in your community folder. After that, there must exist a folder with the name `A32NX`
![image](https://user-images.githubusercontent.com/31593025/111905662-6e298480-8a55-11eb-9625-6777ae4b0b4b.png)

**Comment by BjoernHund** [comment]
> > You must remove the folder `flybywire-aircraft-a320-neo` from the community folder. Then download the version you wish from the github site. Then you must extract that zip in your community folder. After that, there must exist a folder with the name `A32NX`
> 
> ![image](https://user-images.githubusercontent.com/31593025/111905662-6e298480-8a55-11eb-9625-6777ae4b0b4b.png)

Which version did you install? I have the dev version it works perfect.

**Comment by wlouckx** [comment]
> Which version did you install? I have the dev version it works perfect.

I was dumb, I downloaded the master branch and copied the A32NX folder from there, probably it's different than the link from the Readme.md

It works now

**Comment by BjoernHund** [comment]
The installer was fixed.
