### ISSUE TITLE
Impossible to load in the SIM the dev version from the 21 march 2021, any version before the 21 march loads OK.

### ISSUE THREAD

**Issue by PatriceCesson** [flybywiresim/a32nx#4048]
**Mod Version**
{
  "built": "2021-03-20T16:23:25+00:00",
  "ref": "master",
  "sha": "a0ec8ec484503d3750a6801f2feb09898fc6c40e",
  "actor": "MisterChocker",
  "event_name": "manual"
}

**Describe the bug**
This morning (21 march 2021) I updated my A32NX dev version to the last dev version via the installer.
By the way the installer has been updated automatically to version 1.1.0.
So, I downloaded the last dev version after the installer has been upgraded.
Now the installer creates a new folder named "flybywire-aircraft-a320-neo" instead of "A32NX"
After that I load the SIM and the bus (any livery) and now I see the bus version from ASOBO untouched being loaded instead of the FBW dev one.
The PFD colors are different, the MCDU has very few pages. There is no placard about the airplane id in the cockpit, the cockpit textures are different, etc.
Notice I use Addon Linker to manage my addons.

**To Reproduce**

1.Update the A32NX dev version to the last one using the installer (and update the installer by the same way).
2.Load the SIM and select the A320 in the planes (any livery or standard one).
3.the plane loaded inb the SIM is not the one of FBW, but the one of Asobo.

**Expected behavior**

The loaded plane shall be the one of FBW, not the one from Asobo.

**Actual behavior**

See above.

**References**

No need 

**Additional context**
I tried with some other liveries >> failure.
I removed all my A32NX liveries from the community folder (plane loaded with default livery) >> failure.
I reverted back to version from the 20 march 2021 >> Behavior OK, Success, right plane is loaded in the **SIM.**

I had no problems before today with this new dev version version.

Is this a problem in the vanilla unmodded game?
NC, as the vanilla model is loaded instaed of the FBW one.

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by PatriceCesson** [comment]
Manual installation of the A32NX solves the problem. Definitely, there is a problem in the installer 1.1.0

**Comment by ErikNL80** [comment]
layout.json is not generated by the Installer, therefore the aircraft is not recognised...

**Comment by PatriceCesson** [comment]
So the problem is in the installer.

**Comment by chkgk** [comment]
This has been fixed with installer version 1.1.1.
Update the installer, then do a clean install of the mod.

**Comment by andrejetcat** [comment]
thank you for the fast installer update. but, now the Installer creates a new ThrottleConfiguration.ini in a new folder, because its renamed from A32NX to flybywire-aircraft-a320-neo. So the trottle config for the TM Airbus Throttle are gone. just copy from outside the old, still existing A32NX folder, it works again.

**Comment by rmpercussion** [comment]
@andrejetcat I am so glad I found your comment-couldn't figure out what had changed with the ThrottleConfig and didn't realize they had changed the name-Thanks a ton!

**Comment by MisterChocker** [comment]
I assume issue is resolved?

**Comment by PatriceCesson** [comment]
Yes I think issue is solved.

**Comment by MisterChocker** [comment]
Closing since issue is resolved.
