### ISSUE TITLE
Weird Bug in the PFD

### ISSUE THREAD

**Issue by xZreai** [flybywiresim/a32nx#4049]
**Mod Version**

a0ec8ec Dev Version from Installer

**Describe the bug**

Originally found by a screenshot I posted in the #a32nxchat channel in the Discord Server.  PFD Shows  "FINAL" and "APP NAV" while in Cruise.  Also does not respond altitude setting. Have to change altitude using the Vertical Speed button.

**To Reproduce**

1. Filed a flight plan using the MSFS default planner from LFPG to Gibraltar for RNAV 09 Approach
2. Started from cold and dark and took off as normal
3. Saw the things in the PFD [Sorry couldnt be too detailed about it]

**Expected behavior**

**Actual behavior**

**References**

https://discord.com/channels/738864299392630914/738864300818432023/823128511933579264
https://media.discordapp.net/attachments/738864300818432023/823128508522954792/unknown.png?width=1440&height=578

**Additional context**

Was told by a Discord Mod to Submit the issue here, it was briefly discussed in the Server.

Was this working before/when did the issue start occurring?
 
 Latest Dev Version afaik.
Is this a problem in the vanilla unmodded game?

Not sure but probably not?

Discord username (if different from GitHub): Cleon#5802

**Comment by AirbusA320Pro** [comment]
Couple of things to unpick here. Your thrust levers aren't sitting in the CLB gate, that's why you've got (incorrectly) THR LVR in the FMA - that'll affect the way the auto thrust works, just double check the lever positions. 
By the looks of the armed modes, the FMGC has had approach phase activated and the APPR pushbutton on the FCU. The PFD shows the magenta "brick" which only appears after pressing APPR, along with FINAL APP NAV.
It could be a "bug", but it looks more like an incorrect use of the FMGC/FCU.

**Comment by tshomas** [comment]
![1](https://user-images.githubusercontent.com/74841560/111902449-707be680-8a35-11eb-861a-9def3a8c8fad.png)
![2](https://user-images.githubusercontent.com/74841560/111902451-71ad1380-8a35-11eb-9203-7bb9b0254d05.png)
![3](https://user-images.githubusercontent.com/74841560/111902453-75409a80-8a35-11eb-9e45-4d1d8d5d7256.png)
![4](https://user-images.githubusercontent.com/74841560/111902456-783b8b00-8a35-11eb-91ce-9122b525ee4c.png)
![5](https://user-images.githubusercontent.com/74841560/111902460-7a9de500-8a35-11eb-8bf3-e8f9a64e0b3e.png)
![6](https://user-images.githubusercontent.com/74841560/111902463-7c67a880-8a35-11eb-978c-63163ee88155.png)

Here are the images from the Discord that were shown to us while troubleshooting - Shomas

**Comment by AirbusA320Pro** [comment]
@tshomas that's fair, I was just working with what I could see. Interestingly, that last image show LOC G/S blue (armed), which indicates that the APPR pushbutton has again been triggered whilst an ILS approach is selected in the FMGC. 
Is there some form of phantom APPR pb selection being triggered from something?

**Comment by Gringo2885** [comment]
The FINAL and APP NAV at CRZ i haven't got but the RNAV approach lately for me it's kind of 50/50 in Custom FBW version

**Comment by MisterChocker** [comment]
@AirbusA320Pro A phantom APPR pb is impossible. So there is no way the approach phase got activated by accident or itself in this phase of flight.
