### ISSUE TITLE
Route changes when VIA is taken into account

### ISSUE THREAD

**Issue by phildeg31** [flybywiresim/a32nx#4054]
**Mod Version**
"built": "2021-03-18T05:12:53+00:00",
"ref": "fbw",

**Describe the bug**
Flight plan changes on the navigation display when VIA is taken into account. Only the previous flight plan is changed and not the one to come so there is no impact on the flight. I did not have this behavior before.

**To Reproduce**
When VIA is taken into account on Navigation Display, see the previous route on it.

**Expected behavior**
Previous route should not change.

**Actual behavior**
Previous route changes (previous past points are not taken into account anymore).

**References**
On this screen, you can see that previous past points (ex: ROLOL, LERGI) are not part of the route anymore when the VIA is targeted.
![image](https://user-images.githubusercontent.com/74733393/111913180-447c5780-8a6d-11eb-8ee0-3ca0d8edb6cd.png)

Additional screens:
Before Star (VELIN):
![2](https://user-images.githubusercontent.com/74733393/112033069-54fc0300-8b3d-11eb-9916-2a9a7fbfe228.JPG)
When VIA is taken into account:
![3](https://user-images.githubusercontent.com/74733393/112033144-69400000-8b3d-11eb-9739-e9e42c974556.JPG)
Previous route has changed.

**Comment by 2hwk** [comment]
Fixed by #4953 closing ☑️
