### ISSUE TITLE
Can't go back to main menu after flight with the FBW

### ISSUE THREAD

**Issue by flyingpaul1980** [flybywiresim/a32nx#4059]
**Mod Version**
5d033b3

**Describe the bug**
Ending a Flight and clicking "back to Main Menu" leads to being stuck on the loading screen permanently

**To Reproduce**

1. Start flight on World Map with different plane, end flight and go back to main menu
2. Start the exact same Flight with FBW a320neo, end flight and get stuck on Loading Screen with Cessna
3.

**Expected behavior**
I would appreciate to be able to go back to main menu, because restarting the program takes ages

**Actual behavior**
I got stock on Loading screen after clicking "back to main menu"

**References**

Was this working before/when did the issue start occurring?

This has not happened before today, only since the FBW and the installer itself were updated today

Is this a problem in the vanilla unmodded game?

no

**Comment by davidwalschots** [comment]
Is this still a problem at the moment?

**Comment by flyingpaul1980** [comment]
> Is this still a problem at the moment?

Hi David, this problem sorted itself out a while after. it's currently not an issue :)
