### ISSUE TITLE
[BUG] Different Font on EICAS and PFD/ND

### ISSUE THREAD

**Issue by KemalOues** [flybywiresim/a32nx#406]
Stable 1.2.0

The font size and the green color type on PFD/ND and EICAS is not the same. The fonts aon the EICAS seems to be a litte bit smaller and darker, expecially the fonts for N1, EGT, N2 and FF are less readable.
![dark](https://user-images.githubusercontent.com/55877319/92300206-6b53c000-ef59-11ea-8a96-9e484cfe9184.jpg)

**Comment by nabil74** [comment]
Turn the brightness up on the EICAS SCREEN using the brightness knob???

 

Regards
Nabil Abaki

**Comment by KemalOues** [comment]
The brightness is on max setting here!
