### ISSUE TITLE
NAV mode not engaging when autopilot engaged.

### ISSUE THREAD

**Issue by nbillo** [flybywiresim/a32nx#4066]
**Mod Version**

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

12e8314 Development version updated through the FBW installer.

Since the development version was updated 2 days ago now which would be the 20th March, there seems to be an issue with the autopilot holding Nav track mode.
I add my Simbrief flight plan as I've always done through the MCDU and the flight plan is accepted. I complete the MCDU setup on the performance and INIT pages. I take off as normal, but on selecting the autopilot after take off, the system no longer tracks the flight plan and just veers off to the left or right. Even correcting the turn and putting the aircraft back on track, the autopilot refuses to track the navigation. The NAV is set, as is the speed and the altitude as its always been, but each time the autopilot is selected, the navigation is not picked up.
I have also noticed that if when using Aviasoft flight planning software, any selection made in this software on my networked connected laptop changes the navigation path in the MCDU.
The navigation path is also changed when you set the decent and landing data in the MCDU.

**Comment by Valastiri** [comment]
BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning

**Comment by nbillo** [comment]
I'm new to all this so I'm not really sure how to go about using this system. When you are of a senior age, it all becomes a little confusing, especially when you just want to report a bug or glitch!!

**Comment by tracernz** [comment]
Try to make sure you have the PERF takeoff page setup on the MCDU, and advance your throttles all the way to TOGA (maximum). There was a bit of an issue with the flight phases not advancing if certain conditions are not met, and so it doesn’t get to the phase where nav guidance begins. There is a patch but I’m not sure off hand if it has been merged yet.

**Comment by nbillo** [comment]
Thank you for your reply. I've been using a FLEX temp which is calculated from an online page, and yes I always add the performance data, but not what is calculated through the MCDU when adding the fuel and load, would this be a reason for it not engaging? So to be clear then, I need to use TOGA?

**Comment by tracernz** [comment]
> Thank you for your reply. I've been using a FLEX temp which is calculated from an online page, and yes I always add the performance data, but not what is calculated through the MCDU when adding the fuel and load, would this be a reason for it not engaging? So to be clear then, I need to use TOGA?

Flex should also work, but I wanted to say TOGA just to make sure it’s not that. Sounds like you’re doing everything right...

**Comment by tracernz** [comment]
The last changes which were intended to fix this issue were merged 3 days ago. Sounds like that’s when your issue began?
https://github.com/flybywiresim/a32nx/pull/3924

**Comment by nbillo** [comment]
I've noticed that this happens from time to time. We have an excellent version where everything works, and then something gets changed and there are issues. I know this is a WIP development and its fantastic we have these clever people who work on the aircraft. And yes, you're right, it was at that time a few days ago where my problems began. Thank you for your help though.

**Comment by nbillo** [comment]
@ tracernz; do you download the update from here, or do you use the installer?

**Comment by tracernz** [comment]
The installer is the way to go. 👍

**Comment by nbillo** [comment]
> The installer is the way to go. 👍

Thanks, I'll keep with it, as it is rather good, and very easy to update 👍

**Comment by tracernz** [comment]
One thing you can do if this happens, is press the PERF button on the MCDU and see which page it goes to (that will tell you which flight phase it thinks it’s in).

**Comment by Valastiri** [comment]
@nbillo Apologies as the template does exist and the disclaimer provides a reason. I've re-read over your issue. I believe tracernz has covered most of the bases. 

Some extra notes below:

Firstly if you'd like to redo your issue and fill out the template we could re-open this issue. 

This was the original issue with flight phases: https://github.com/flybywiresim/a32nx/issues/3934
and subsequent merged PR: https://github.com/flybywiresim/a32nx/pull/3924 to fix it. 

As for your other issues please also ensure that you have set some deadzones as per the first common issue described here https://docs.flybywiresim.com/start/reported-issues/

I'd also like to stress we generally don't ensure compatibility with 3rd party applications that we are not partnered or working with. I believe Aviasoft was mentioned. The extraneous behaviors with that application and our addon we can't control.

**Comment by nbillo** [comment]
@Valastiri Thank you for your explanation, I can see now after reading different reporting, I hadn't followed the simple ruling. I apologise for that. I will endeavour to fill out my reporting correctly in the future.
Thank you for the links to the original problems. I will investigate these further. To complete my flight, I did revert back to the sable version and all aspects of my flight went through without incident. I do however really like the extras you guys have implemented to the development version, so it's a real shame we have these flight following issues back. I'm going to try the development version again with my next flight, and I shall try out the responses to the original submitted bugs.
I fully understand that you are not able to comment on third party developers programs causing issues, I threw that in to see if it had been reported earlier. I should do the right thing and search myself 😂 Thanks for all the time and effort you guys contribute to this project. It's marvellous what the community does for the flight sim world 👍😊
