### ISSUE TITLE
Bug new Installer v1.1.1

### ISSUE THREAD

**Issue by Pitou75** [flybywiresim/a32nx#4067]
**Mod Version**

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Pitou75** [comment]
Bug new installer v1.1.1 : installer doesn't install the update. It stays freezed at "PREPARING THE UPDATE". I can't load the dev mod. It worked perfectly before this update version !! Thank you 
I have the lastest version of MSF.

**Comment by Valastiri** [comment]
Does not follow the template. https://docs.flybywiresim.com/start/reported-issues/

Visit the discord for support and restart your installer.
