### ISSUE TITLE
EFB - Display OFP with a Fixed Font

### ISSUE THREAD

**Issue by cowreth** [flybywiresim/a32nx#4069]
**Is your feature request related to a problem? Please describe.**
In the EFB, OFP are less readable when not displayed in Monospaced fonts

**Describe the feature you'd like to see implemented**
In the EFB, display OFP with a monospaced font

**References**
I used the development branch, installed today (March 22nd)

**First Issue in the Project**
I just wanted to add a massive thanks.

**Comment by beheh** [comment]
Fixed by #4058. Duplicates #4057.

**Comment by beheh** [comment]
@cowreth Are you absolutely sure you're on the latest version of the master branch? This was merged around 16 hours ago. If you're sure, could you please follow the bug template and supply your `build_info.json`?
