### ISSUE TITLE
FCU - From cool&dark  remain off

### ISSUE THREAD

**Issue by Andreatat69** [flybywiresim/a32nx#407]
Hi Sir, there is a reason why in the Airbus neo MOD FCU panal remain completely OFF ??
This it happen from the cool and dark state, while if I start the plane from the rnw it works..

any reason ??
Tks for y help

**Comment by ukflyer** [comment]
Turn up the brightness knobs underneath the control panel :)

**Comment by Andreatat69** [comment]
sorry can y tell me which knobs ?? I tryed all but some of them can not be turn 
Thank y

**Comment by ukflyer** [comment]
Just underneath the autopilot controls

![mcpbuttons](https://user-images.githubusercontent.com/70434502/92301162-2b8cd880-ef59-11ea-86b7-bd85ac2acf5d.PNG)

**Comment by Benjozork** [comment]
Please respect the issue templates.

**Comment by Andreatat69** [comment]
Tks a lot for y help
