### ISSUE TITLE
VOR needles do not show up on ROSE NAV or ARC mode

### ISSUE THREAD

**Issue by ccapilot** [flybywiresim/a32nx#4070]
**Mod Version**
545c472

**Describe the bug**
VOR/ADF needles when selected and in range are not being displayed while on ROSE NAV or ARC modes, they are being displayed only while on ROSE VOR mode.

**To Reproduce**

1. Make Sure you are flying within range of a VOR, tune the VOR, select VOR 1 and/or VOR 2 select ROSE VOR mode and see the VOR needles correctly displayed, change to ROSE NAV or ARC modes and see that the VOR needles are not displayed.
2.
3.

**Expected behavior**
VOR/ADF needles should be always displayed when selected and when receiving valid navaid signals in ROSE NAV and ARC modes as well as in ROSE VOR modes.

**Actual behavior**
VOR/ADF needles are being displayed only while on ROSE VOR mode, they fail to be displayed on other modes like ROSE NAV and ARC modes.

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by CptBayer** [comment]
it is on the to do list .... see m thread in discussions ...


greets Klaus

**Comment by tracernz** [comment]
You're running a 5 day old build. This was added 3 days ago ;). https://github.com/flybywiresim/a32nx/pull/3886

**Comment by ccapilot** [comment]
thanks I can see that now, I was running experimental model that has not been updated, with the development I can see this already fixed, thanks

**Comment by tracernz** [comment]
There's a little holdup with experimental at the moment but it will come in due course.
