### ISSUE TITLE
small white triangles missing in ND ROSE modes

### ISSUE THREAD

**Issue by ccapilot** [flybywiresim/a32nx#4071]
**Is your feature request related to a problem? Please describe.**
the are small fixed white triangles pointing towards 45, 90, 135, 180, 225, 270 and 315 degrees on the outside or ROSE modes on ND that are missing.

**Describe the feature you'd like to see implemented**

**References**
enclosing a pic with the references in red circles
![ND ROSE triangles](https://user-images.githubusercontent.com/71601106/111973746-40f1da80-8b18-11eb-87b9-2e44dd238410.jpg)

**Additional context**

Discord username (if different from GitHub):

**Comment by tracernz** [comment]
Do we have a photo of a real one? FCOM is often not the best reference from graphical things.

**Comment by MisterChocker** [comment]
> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning

You might want to take care of this.

**Comment by ccapilot** [comment]
> > BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning
> 
> You might want to take care of this.

thanks, line removed...

**Comment by ccapilot** [comment]
here is the pic of the real airplane, hope that helps as a reference.
![real ND rose](https://user-images.githubusercontent.com/71601106/112130697-2edc6e80-8be2-11eb-82c7-dc7817ce9075.jpg)

**Comment by 2hwk** [comment]
Fixed by #4953 closing ☑️
