### ISSUE TITLE
My installer does not update the development version.

### ISSUE THREAD

**Issue by LuizNavarro** [flybywiresim/a32nx#4073]
**Mod Version**

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by LuizNavarro** [comment]
My installer does not update the development version.

**Comment by Benjozork** [comment]
This is not the installer repository

**Comment by LuizNavarro** [comment]
Is the development version being updated? Or just the stable?
