### ISSUE TITLE
VR - Mouse interaction with EFB 

### ISSUE THREAD

**Issue by ThubHulk** [flybywiresim/a32nx#4074]
**Is your feature request related to a problem? Please describe.**

When I am on VR mode, it is very difficult to "click" on the good item on the EFB. The mouse cursor seems too far from the EFB

**Describe the feature you'd like to see implemented**

**References**

**Additional context**

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
This is a limitation of MSFS and nothing we can control at the moment
