### ISSUE TITLE
OFP on EFB does not use mono-spaced font

### ISSUE THREAD

**Issue by frankkopp** [flybywiresim/a32nx#4075]
**Mod Version**
  "built": "2021-03-22T12:58:17+00:00",
  "ref": "master",
  "sha": "316984c4eb8f1fafc83647a549a1c7b514b867d6",
  "actor": "MisterChocker",
  "event_name": "manual"

**Describe the bug**
OFB on EFB does not use mono-spaced font as per [4064]( https://github.com/flybywiresim/a32nx/pull/4064)

**To Reproduce**
Start EFB and load flight plan

**References**
![image](https://user-images.githubusercontent.com/16833201/112018205-a5b82f80-8b2e-11eb-90ef-da3a0891e6ac.png)

Discord username (if different from GitHub): CdrMaverick

**Comment by MisterChocker** [comment]
This shouldn't be an issue any more since #4058.
However #4026 will also bring a couple of changes.

**Comment by frankkopp** [comment]
> This shouldn't be an issue any more since #4058.
> 
> However #4026 will also bring a couple of changes.

I looged my issue after 4058. That PR/commit said it should be mono now but it wasn't on my system. I thought I updated after that commit (it was actually the reason for my update). I will double check tomorrow. Maybe I did not get this PR in my update.

**Comment by frankkopp** [comment]
The screenshot below is from this morning (23.3.2021 9:40 UTC+1) after all updates done on Dev through the installer. 

![image](https://user-images.githubusercontent.com/16833201/112117879-1d806b80-8bbc-11eb-9b84-1fb775408e52.png)
