### ISSUE TITLE
Black Screens

### ISSUE THREAD

**Issue by DINOBAT** [flybywiresim/a32nx#4078]
**Mod Version**

Custom FBW
**Describe the bug**

All screens are black (after batteries / external power on)

**To Reproduce**

1. Loaded MSFS as usual.
2. Loaded plane at gate.
3. Push batteries and external power buttons.
4. All screens remained black.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
"BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning"

**Comment by DINOBAT** [comment]
Hello,

Not sure what I did wrong. I can re-open as needed.

Please advise.

Many thanks.

JD

**Comment by Benjozork** [comment]
You did not fill the required template.

Did you install using the installer or manually ?

**Comment by DINOBAT** [comment]
Apologies. I thought I followed the template.

I have tried with both, first with the installer, then I went to manual and nothing worked.

I know this is not your fault, it is just that MSFS has been so frustrating so far...

Thank you for your time.

**Comment by Benjozork** [comment]
Make sure you delete all existing A32NX folders (including A32NX and flybywire-aircraft-a320neo) before reinstalling

**Comment by DINOBAT** [comment]
Yes, I had done that and still no luck...

**Comment by DINOBAT** [comment]
This is what I get now...

![2021-03-22 13_43_40-Microsoft Flight Simulator - 1 14 5 0](https://user-images.githubusercontent.com/79408320/112034408-d55a3e00-8b14-11eb-8065-7c02fca8b62f.png)

**Comment by Benjozork** [comment]
This is a random issue with all planes since Sim Update 3, just reload the flight.

**Comment by DINOBAT** [comment]
Thank you.

**Comment by FRYYYYYY** [comment]
> Make sure you delete all existing A32NX folders (including A32NX and flybywire-aircraft-a320neo) before reinstalling

Where can I find the "flybywire-aircraft-a320neo" directory?
