### ISSUE TITLE
ILS

### ISSUE THREAD

**Issue by IoulianosVoudouris** [flybywiresim/a32nx#4080]
**Mod Version**

{
  "built": "2021-03-15T00:58:58+00:00",
  "ref": "refs/remotes/upstream/HEAD",
  "sha": "cd4402452bafee8391bd09a81d1ce362cc2d75f1",
  "actor": "benjozork <benjamin.dupont.984@gmail.com>",
  "event_name": "manual"
}

**Describe the bug**
 ILS digits are not activated by the "ILS" button. They are activated by the "VOR" button, but then again the "pappies" do not appear on approach, and the ILS does not work.  

**To Reproduce**
Press twice on the "NAV" button and next on "ILS" button. Digits do not change in ILS frequencies so they cannot be set. If you press the "VOR" button the ILS frequencies appear alright and can be set. Even so the "diamonds" do not appear on ILS -
approach and ILS airplane guiding is not enabled  

1.  I set the proper destination ILS frequency by pressing "VOR" (to activate) the ILS frequency digits
2.  I pressed ILS button
3.  I landed manually...  :)

**Expected behavior**
 I expected the ILS to work

**Actual behavior**
 ILS did not guide the aircraft

**References**

https://user-images.githubusercontent.com/63018983/112042955-c8f3d680-8b50-11eb-90a0-b4212222082e.mp4

**Additional context**
 Windows 10 Pro & MSFS 2020 Fully Updated

Was this working before/when did the issue start occurring? It worked on the first use of A32NX 0.5.4 only.

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub): JulianGeorge (Discord)

**Comment by ThatRedMelon** [comment]
The nav functionality of the RMP was removed in a rewrite of the panel and therefore becomes unusable. Since it should only be used in a dual fmgc failure, the functionality during the rewrite was not readded to be more accurate and instead the rad nav page of the mcdu should be used instead.

**Comment by lukecologne** [comment]
Manual radio nav tuning is currently not supported. It has worked previously, but since the react rework of the RMP, this feature does not work anymore. But you don't need to tune navaids via the RMP, the normal way is to tune via the MCDU RAD NAV page, or through auto tuning by the FMGC. To display the ILS indication on the PFD, you need to press the LS button on the EFIS control panel on the glarshield.

**Comment by IoulianosVoudouris** [comment]
Than you very much for the quick responses! I am very obliged!
JulianGeorge

**Comment by IoulianosVoudouris** [comment]
Thank you for your instructions! ISSUE RESOLVED! ILS works perfectly
*v.pixart *
video-graphics
+30 210 2018 517 - +30 693 2463 847
