### ISSUE TITLE
ILS For Wrong Runway Flown When RNAV Selected For Other Runway

### ISSUE THREAD

**Issue by AirbusA320Pro** [flybywiresim/a32nx#4082]
**Mod Version**
{
  "built": "2021-03-18T05:12:53+00:00",
  "ref": "fbw",
  "sha": "545c47204bd9d7c99197555c5687dc2bd79c2f6c",
  "actor": "Benjozork",
  "event_name": "manual"
}

**Describe the bug**
Selecting RNAV approach EGCC23L whilst airborne, aircraft perfectly flew the transition to the final approach course. However, FMAs read "FINAL APP" **AND** "CAT 3 SINGLE". The aircraft followed the ILS 23R perfectly to a full autoland on 23R. 
FMGC clearly showed RNAV23L selected, FINAL APP and magenta brick confirmed RNAV approach (supposedly) being flown on PFD, but aircraft captured and flew ILS 23R.

**To Reproduce**

1. Spawn EGCC23R, take off, level off. 
2. Use FMGC to select RNAV 23L whilst airborne.
3. Fly transition to final approach course. 
4. Observe aircraft on ILS 23R centreline instead of 23L as programmed. (Backed up my CAT 3 SINGLE on FMA)

**Expected behavior**

Aircraft should capture and fly RNAV appr 23L.

**Actual behavior**
Aircraft captured and flew ILS 23R to conclusion.

**References**

<img width="1000" alt="Screenshot 2021-03-23 002216" src="https://user-images.githubusercontent.com/75289637/112074565-7e815280-8b6e-11eb-9923-abadad07b709.png">

**Additional context**

Screenshot shows the variety of approach elements all being displayed. External view shows runway 23R being approached, when 23L should be being flown.

Was this working before/when did the issue start occurring?
First time I've seen this happen.

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub): AirbusA320Pro

**Comment by tracernz** [comment]
So it tuned 23R frequency?

**Comment by AirbusA320Pro** [comment]
@tracernz Would appear so. INN 109.5 is displayed in the bottom left of the PFD (which is the correct freq and ident for ILS 23R), but the selected approach is RNAV 23L (as confirmed by the ND displaying RW23L as the "to" waypoint.
Also, as part of the RNAV procedure, pressing the APPR pushbutton alone should arm the magenta blocks on the PFD - you shouldn't need the LS pushbutton pressed to display the magenta overlay.

**Comment by tracernz** [comment]
Thanks. The algorithm to pick the ILS freq is not very robust. I can’t remember the specifics to see if it would cause this but it makes me even more certain to replace it with a different approach (ha!).

**Comment by AirbusA320Pro** [comment]
Just for clarity, I wanted to fly the RNAV, not the ILS. It shouldn't have picked up any ILS frequency.

**Comment by MisterChocker** [comment]
Tbf RNAV is not yet supported (working)
