### ISSUE TITLE
FBW installer failed to install Dev Build

### ISSUE THREAD

**Issue by A320nx** [flybywiresim/a32nx#4087]
**Mod Version**
FBW Installer 1.1.1
Sim Version: 1.14.5.0

**Describe the bug**
- The installer shows (failed to install) when downloading dev build. and the install button shows (Error).
- FBW Windows notification : Download failed! Oops, something went wrong.

**To Reproduce**
1. Uninstall FBW installer and install it again.
2. Removed all mods/liveries from the community folder (empty).
3. Restart the PC.

**Expected behavior**

**Actual behavior**
- Failed to install Dev Build.

**References**
https://postimg.cc/JHzH0SRQ

**Additional context**

Was this working before/when did the issue start occurring?

- Was working with FBW v1.0.5.
- In v1.1.0 the installer was working and i can download the Dev Build, but the FBW A320nx was not in the Sim.
- The problem start in FBW v1.1.1

**Comment by Valastiri** [comment]
Please delete the A32NX folder as a precautionary measure. Ensure v1.1.1 in the installer download a clean copy of our addon. 

The package is no longer called A32NX and is now flybywire-aircraft---- 

We have been troubleshooting and the install issues should be resolved.

**Comment by MicroCire** [comment]
i think after install "Installer" go to settings in left bottom and verify that the install directory is a good one. For me after install the settings was C:\Users\Utilisateur\AppData\Local\MSFSPackages\Community\ and the download was effective but when you go to this path there is nothing. So i modified by C:\Users\Utilisateur\AppData\Local\MSFSPackages\Community (without \ at the end of line) and now is correct.

**Comment by A320nx** [comment]
> 
> 
> Please delete the A32NX folder as a precautionary measure. Ensure v1.1.1 in the installer download a clean copy of our addon.
> 
> The package is no longer called A32NX and is now flybywire-aircraft----
> 
> We have been troubleshooting and the install issues should be resolved.

**Hello Valastiri**
I already mentioned that i removed everything in Community folder and it is Empty.
No A32NX or flybywire-aircraft folder in Community.

**Comment by Valastiri** [comment]
"Preparing Update"
https://github.com/flybywiresim/installer/issues/179
"Failed to install"
https://github.com/flybywiresim/installer/issues/181

Please see the following two issues with instructions on how to debug your installer. 

Failed to install "should" be resolved at this time as I just ran a test myself a few hours back. You can also check / clean the following directories of either folder i mentioned earlier.

MS Store: `C:\Users[YOUR USERNAME]\AppData\Local\Packages\Microsoft.FlightSimulator_[RANDOM LETTERS]\LocalCache\Packages\Community`

Steam: `C:\Users[YOUR USERNAME]\AppData\Roaming\Microsoft Flight Simulator\Packages\Community`

**Comment by A320nx** [comment]
> 
> 
> "Preparing Update"
> [flybywiresim/installer#179](https://github.com/flybywiresim/installer/issues/179)
> "Failed to install"
> [flybywiresim/installer#181](https://github.com/flybywiresim/installer/issues/181)
> 
> Please see the following two issues with instructions on how to debug your installer.
> 
> Failed to install "should" be resolved at this time as I just ran a test myself a few hours back. You can also check / clean the following directories of either folder i mentioned earlier.
> 
> MS Store: `C:\Users[YOUR USERNAME]\AppData\Local\Packages\Microsoft.FlightSimulator_[RANDOM LETTERS]\LocalCache\Packages\Community`
> 
> Steam: `C:\Users[YOUR USERNAME]\AppData\Roaming\Microsoft Flight Simulator\Packages\Community`

**Valastiri** _Thanks_
