### ISSUE TITLE
[BUG] ND shows star instead of runway symbol

### ISSUE THREAD

**Issue by ukflyer** [flybywiresim/a32nx#409]
**Branch**
Stable 0.2.0

**Describe the bug**
On arrival/departure ND shows star instead of runway symbol when runway has been selected in MCDU

**Expected behavior**
ND should show runway symbol instead of a star

**Screenshots or Videos**
https://www.youtube.com/watch?v=cv41hm4JEB8&t=16s

**Comment by AdenFlorian** [comment]
ACTUAL (master):
![image](https://user-images.githubusercontent.com/3533988/92434405-5481b900-f165-11ea-93b4-ef9002995517.png)

EXPECTED:
![image](https://user-images.githubusercontent.com/3533988/92434505-9f9bcc00-f165-11ea-9fb4-7b6573ffb067.png)

**Comment by rhpa23** [comment]
For me, this is a major bug of the ND. Without the runway symbol, some routes and approaches can be very confusing.

**Comment by MisterChocker** [comment]
using #1713 instead for tracking
