### ISSUE TITLE
Route reserved fuel not included in block/extra fuel calculation

### ISSUE THREAD

**Issue by felixharnstrom** [flybywiresim/a32nx#4093]
**Mod Version**

```
{
  "built": "2021-03-23T03:51:43+00:00",
  "ref": "master",
  "sha": "9dfce11f233cfdbf862024bcd5e22f362a8d2c03",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

**Describe the bug**

I think have a spotted an inconsistency in the calculated block fuel value on the fuel prediction page in what I'm seeing in the simulator vs various other references.

In the sim, the default block fuel is calculated as: `BLOCK = TAXI + TRIP + MIN DEST FOB` (where `MIN DEST = ALTN + FINAL` by default). When entering a block fuel value manually, any value that is in excess of the default calculated value is added as `EXTRA`. In this case, extra fuel will be calculated as: `EXTRA = BLOCK - TAXI - TRIP - MIN DEST FOB`).

*Screenshot showing the automatically calculated block fuel value*
![insim_automatic_block](https://user-images.githubusercontent.com/5500848/112166848-4d496680-8bf0-11eb-971e-f8f2c4e150f3.PNG)

*Screenshot with a manually entered block fuel value*
![insim_manual_block](https://user-images.githubusercontent.com/5500848/112167032-72d67000-8bf0-11eb-89f9-c63508d37295.PNG)

However, when comparing this to other sources I think I'm seeing something different in that the route reserved fuel is also factored into this calculation.

In both the Honeywell Pilot's Guide and the cockpit recording linked below, it seems that `BLOCK = TAXI + TRIP + RTE RSV + MIN DEST FOB + EXTRA `, i.e. the route reserved fuel is included in the automatic block fuel calculation (or the extra fuel calculation if the block fuel is manually entered).

The referenced paragraph from the FCOM also seems to confirm that the route reserved fuel should be included in the calculation such that extra is calculated as: `EXTRA = BLOCK - TAXI - TRIP - RSV - MIN DEST FOB`

I am aware that the route reserved fuel is 'converted' to extra fuel after takeoff, however my understanding is that this is just a difference in how it is displayed. Shouldn't the numbers during the preflight initialization all add up like they seemingly do in the references below?

Of course it's also possible (or perhaps likely) that I'm just misunderstanding something - if so I would be happy to be corrected :)

**To Reproduce**

1. Enter FROM/TO and ALTN on INIT A. The settings I used to test this are seen in the screenshot below.
2. Check both the calculated block fuel value using the fuel planner and the calculated extra fuel value when using a manually entered block fuel value  on INIT B

![insim_init_a](https://user-images.githubusercontent.com/5500848/112164255-05294480-8bee-11eb-8c7e-1a1e4235f969.PNG)

**Expected behavior**

I am not 100% sure, but my understanding is that the automatically calculated block fuel value should be: `BLOCK = TAXI + TRIP + RSV + MIN DEST FOB`
And when entering a manual block fuel value, extra should be calculated as: `EXTRA = BLOCK - TAXI - TRIP - RSV - MIN DEST FOB`

**Actual behavior**

The automatically calculated block fuel is: `BLOCK = TAXI + TRIP + MIN DEST FOB`
When entering a manual block fuel value, extra is calculated as: `EXTRA = BLOCK - TAXI - TRIP - MIN DEST FOB`

**References**

These sources seem to include the route reserved fuel in the block/extra calculation:

*Screenshot showing the INIT B page from this Youtube video:* https://www.youtube.com/watch?v=DP8soiH_4jE&t=122s
![cockpit_view](https://user-images.githubusercontent.com/5500848/112165944-7caba380-8bef-11eb-9bf2-428c132612ea.PNG)

*Honeywell Pilot's Guide*
![pilots_guide](https://user-images.githubusercontent.com/5500848/112166277-c6948980-8bef-11eb-87e1-bb2348d2cb93.PNG)

*CCM Airlines FCOM*
![fcom](https://user-images.githubusercontent.com/5500848/112165791-584fc700-8bef-11eb-89bd-4446c12c6b32.PNG)

**Additional context**

Was this working before/when did the issue start occurring?

Unknown

Is this a problem in the vanilla unmodded game?

Unknown

Discord username (if different from GitHub): Jethro#4431

**Comment by MisterChocker** [comment]
cc. @Lucky38i

**Comment by felixharnstrom** [comment]
I also just now noticed that the route reserve value in the sim is calculated as a percentage of block fuel:

https://github.com/flybywiresim/a32nx/blob/9dfce11f233cfdbf862024bcd5e22f362a8d2c03/A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js#L2203

However, shouldn't it be a percentage of *trip* fuel if I'm reading these sources correctly?

*Honeywell Pilot's Guide*
![rte_rsv_pilots_guide](https://user-images.githubusercontent.com/5500848/112175686-bd0f1f80-8bf7-11eb-9ca7-ff527ea90304.PNG)

*CCM Airlines FCOM*
![rte_rsv_fcom](https://user-images.githubusercontent.com/5500848/112175700-c0a2a680-8bf7-11eb-818e-07f53c1301a1.PNG)

**Comment by MisterChocker** [comment]
@felixharnstrom There are both reserve fuel weight and percentage.

**Comment by felixharnstrom** [comment]
@MisterChocker Sure, but the way I'm reading these sources is that if you enter the route reserved fuel as a percentage - let's say that you use the default value of 5% - then theroute reserved fuel weight should be calculated as "5% of trip fuel". However, as it is now we calculate it as "5% of block fuel" (see the code snippet I linked to in my previous comment).

The way I'm reading the sources in my previous comment it should be calculated as a percentage of the trip fuel weight, but maybe I'm misunderstanding something here?

**Comment by Lucky38i** [comment]
Nice find Felix, I'll try and push a fix in the coming days.
