### ISSUE TITLE
Screens inside cockpit all stay black on start

### ISSUE THREAD

**Issue by joshh1309** [flybywiresim/a32nx#4097]
**Mod Version**
545c472 (cFBW)

"built": "2021-03-18T05:12:53+00:00",
  "ref": "fbw",
  "sha": "545c47204bd9d7c99197555c5687dc2bd79c2f6c",
  "actor": "Benjozork",
  "event_name": "manual"

**Describe the bug**

When the aircraft is started without a flight plan at a gate, even when turning on aircraft batteries, apu, engines and adjusting brightness of the screens (so they are not just all dark), the efb, mcdu, ecam, nd, pfd still won't display anything and just show a black screen

**To Reproduce**

1. Loaded a32nx at EGCC with no flight plan, live traffic and live weather, with sufficient fuel
2. Turn on batteries, apu, even engines

**Expected behavior**

When batteries are turned on the displays should light up and display the relevant stuff

**Actual behavior**

Displays do not turn on

Also tried using the checklists and not using the checklists to try and make it work, and tried using CTRL-E to start the engines to see if that would do it, still did not work.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Only noticed this start on this build but have not used in a while

Is this a problem in the vanilla unmodded game?
Unsure

Discord username (if different from GitHub): joshh #8095

**Comment by Benjozork** [comment]
Can you try without anything else in the Community folder and a clean reinstall of the plane ?

**Comment by joshh1309** [comment]
It did work after removing everything from the community folder and performing a clean reinstall of the plane, displays switched on when ground power switched on, so thanks for the help :)
