### ISSUE TITLE
Thrust reverse not working after new installer

### ISSUE THREAD

**Issue by jcallum** [flybywiresim/a32nx#4098]
**Mod Version**

FBW 
{
  "built": "2021-03-18T05:12:53+00:00",
  "ref": "fbw",
  "sha": "545c47204bd9d7c99197555c5687dc2bd79c2f6c",
  "actor": "Benjozork",
  "event_name": "manual"
}

**Describe the bug**

After using the installer to install the FBW mod, the throttles no longer move into the reverse detente. When I install the same build into the community folder manually (keeping the same folder name - i.e. A32NX - the throttles then move into the revere detente.

**To Reproduce**

1. Reinstalled using the installer with the same result. Throttles don't move to the reverse detente.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
The package was renamed. Move your throttle configuration file. Working as intended.

**Comment by jcallum** [comment]
Thanks. My bad.
____
John Callum
56 Rowanwood Av
Toronto, M4W1Y9
(647) 241-7564
