### ISSUE TITLE
ECAM ELEC Page Text Issue

### ISSUE THREAD

**Issue by ManyPandas** [flybywiresim/a32nx#4099]
**Mod Version**

{
  "built": "2021-03-23T03:51:43+00:00",
  "ref": "master",
  "sha": "9dfce11f233cfdbf862024bcd5e22f362a8d2c03",
  "actor": "Benjozork",
  "event_name": "manual"
}

**Describe the bug**

The font size for the ECAM Electrical Page is incorrect. The Text appears as a jumbled mess of letters and numbers.

**To Reproduce**

1. Spawn Aircraft at Gate in a cold and dark state
2. Follow Checklist through 'Cockpit Preparation' to 'ECAM Elec Page' after 'Pack Flow'
3. Jumbled mess appears for ECAM ELECPage.

**Expected behavior**

I expected the ELEC page to appear as it normally would.

**Actual behavior**

A Jumbled mess of text, numbers, and letters appeared on the lower ECAM screen.

**References**

![image](https://user-images.githubusercontent.com/21292503/112248009-9bc82680-8c2b-11eb-9b11-0d4d6bb46b8d.png)

**Additional context**

Was this working before/when did the issue start occurring?

The issue occurred after I updated the mod to the latest dev version from the installer.

Is this a problem in the vanilla unmodded game? No.

Discord username (if different from GitHub):

**Comment by tracernz** [comment]
cc @davidwalschots Another one... weird.

**Comment by Snapmatics** [comment]
Check if you have a folder called `flybywire-aircraft-a320-neo` in your community folder. If yes, report back, delete it and let us know.

**Comment by tracernz** [comment]
In your community folder you don’t happen to have both an A32NX and a flybywire-aircraft-a320-neo folder do you?

**Comment by ManyPandas** [comment]
None of the aforementioned folders exist in either directory. In fact, the Microsoft.FlightSimulator_8wekyb3d8bbwe folder doesn't exist in the \Local directory
