### ISSUE TITLE
Sim event from SPAD.next not taken into account

### ISSUE THREAD

**Issue by phildeg31** [flybywiresim/a32nx#4101]
**Mod Version**
"built": "2021-03-18T05:12:53+00:00",
"ref": "fbw",

**Describe the bug**
After investigating on a problem for this ticket https://github.com/flybywiresim/a32nx/issues/4052#event-4498857164, the identified problem is that the sim event ALTITUDE_SLOT_INDEX_SET sent by SPAD.next for my Logitech/Saitek autopilot panel is taken into account only by game (good display on PFD and on FCU panel for target altitude for the descent) and not by the mod.

The mode is not selected in game directly so there is no `H:A320_Neo_CDU_MODE_SELECTED_ALTITUDE` or `H:A320_Neo_CDU_MODE_MANAGED_ALTITUDE` event with a call to onEvent function in A32NX_FMCMainDisplay.js that call then handleFcuInput function in A32NX_FlightPhaseManager.js (call to `this.changeFlightPhase(FmgcFlightPhases.DESCENT);` in it). So, the descent phase is not activated and then the approach phase is not activated automatically on deceleration point. 

It worked fine before (at least for the approach phase activated on deceleration point) but it seems to be since a FlightPhaseManager has been added and a refactor has been done for phase management.

SPAD.next works only with sim vars for now (reply on the SPAD.next discord: "You can manage LVARs , not (yet) HVARs").

It would be good to have a way to intercept the events or to take into account changes made by the events sent to the sim directly with sim vars (like ALTITUDE_SLOT_INDEX_SET).

The aim of this ticket is also to think about a way to keep sim var events working with the mod. A user that has configured everything to work with the simulator (it can take a lot of time depending to the external devices used) should not have to change this configuration to use the mod (because the events are differents between both).

**To Reproduce**
Use Logitech/Saitek autopilot panel to change target altitude to the approach altitude (3000ft for example) and click on the button configured with SPAD.next to send a ALTITUDE_SLOT_INDEX_SET event to the SIM directly.

**Expected behavior**
The descent phase should be activated.

**Actual behavior**
The descent phase is not activated because event sent to sim directly and not taken into account by the mod.

**References**
N/A

**Additional context**
Use autopilot panel from Logitech/Saitek with SPAD.next sending a ALTITUDE_SLOT_INDEX_SET with value 1 for selected mode and 2 for managed mode when clicking on ALT button of the panel.

Was this working before/when did the issue start occurring?
It was working with a mod version of February (at least for the approach phase activated on deceleration point).

My discord if needed to exchange: phildeg31#1453

**Comment by aguther** [comment]
You find documentation of working events here:
https://docs.flybywiresim.com/start/autopilot-fbw/

Some helpful files can also be found here for FSUIPC and SPAD.neXt:
https://github.com/flybywiresim/a32nx/tree/master/docs
