### ISSUE TITLE
when ACCEL changed and CLB is selected after takeoff, AT goes to SPEED instead of THR CLB

### ISSUE THREAD

**Issue by ccapilot** [flybywiresim/a32nx#4102]
**Mod Version**
9dfce11

**Describe the bug**
when acceleration altitude has been changed for example to do a NADP, when you engage CLB thrust, AT goes to SPEED instead of THR CLB.

**To Reproduce**
1. load the airplane at any runway and configure for takeoff as normal with no SID
2. select a NADP(A) by changing THR RED/ACC on PERF page to 1500/3000 at a sea level airport
3. do a normal takeoff when LVR CLB flashes, select CLB thrust
4. look at the FMA that AT goes into SPEED mode.

**Expected behavior**
when you select CLB thrust with a modified acceleration altitude, always the AT should change to THR CLB

**Actual behavior**
when CLB thrust is selected with a modified acceleration altitude, AT mode goes to SPEED

**References**

**Additional context**

Was this working before/when did the issue start occurring?
I am not sure, probably not.

Is this a problem in the vanilla unmodded game?
I don't know, I don't use that...

Discord username (if different from GitHub):

**Comment by derl30n** [comment]
Is this still an issue?

**Comment by aguther** [comment]
I don't think it's right that in any case ATHR should move to THR CLB. It depends on a few more things. For example if you don't enter a V2, it will not engage CLB/OP CLB but VS with current VS as target. The means the ATHR will engage SPEED mode. When you additionally didn't update the speed target, that means the ATHR pulls out engine thrust to reach 100 kts. As far as I can tell this the actual behavior of the real plane and no bug at all.
