### ISSUE TITLE
decal problem on thrust levers

### ISSUE THREAD

**Issue by JLD95** [flybywiresim/a32nx#4106]
**Mod Version**

2021-03-24T18:18:10+00:00

**Describe the bug**

On Flex position TOGA is displayed

**To Reproduce**

1.   In Flight, on Flex position during take off, TOGA is displayed
2.  
![2021-03-25 (1)](https://user-images.githubusercontent.com/5894146/112437902-c3141600-8d47-11eb-88a4-2de8cd49ac7d.jpg)

3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by tracernz** [comment]
You're past the FLX/MCT detent there.

**Comment by JLD95** [comment]
it is my mistake, no flex temperature is entered in perf page
