### ISSUE TITLE
TO wpt in ND whould be white

### ISSUE THREAD

**Issue by ccapilot** [flybywiresim/a32nx#4108]
**Mod Version**
  "built": "2021-03-24T18:18:10+00:00",
  "ref": "master",
  "sha": "a81ec5b30f7af1106e2140ded249321625a64cb2",
  "actor": "tracernz",
  "event_name": "manual"

**Describe the bug**
TO waypoint in ND should always be white in color.
At the moment is changing to white only when you overfly it, which is wrong.

**To Reproduce**
1. look at the TO waypoint on ND and see that is green, when it should be white
2. when you overfly the TO waypoint, it changes to white, which is wrong.
3.

**Expected behavior**
TO waypoint in ND should always be color white, when you overfly the current TO waypoint, the next active "TO" waypoint should change to white.

**Actual behavior**
TO waypoint is color green and changes to white when you overfly the waypoint, which is incorrect.

**References**
![ND to wpt green](https://user-images.githubusercontent.com/71601106/112482443-7f45fe80-8d91-11eb-981f-d7e173b8a7d1.jpg)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by beheh** [comment]
I've been looking at this in the new FPLN branch, and t he logic exists in theory, however it's an SVG that is never cleared but always drawn upon. So I think the green covers up the white text beneath.

**Comment by ccapilot** [comment]
I have seen a couple of times that during the approach phase, it looks like the proper white TO waypoints work fine, just during climb/cruise/descent do not work for some reason, but it seems to be working during app... wierd.

**Comment by 2hwk** [comment]
Fixed by 4953 closing ☑️
