### ISSUE TITLE
managed lvl change dot should not appear while on cruise

### ISSUE THREAD

**Issue by ccapilot** [flybywiresim/a32nx#4109]
**Mod Version**
  "built": "2021-03-24T18:18:10+00:00",
  "ref": "master",
  "sha": "a81ec5b30f7af1106e2140ded249321625a64cb2",
  "actor": "tracernz",
  "event_name": "manual"

**Describe the bug**
while in cruise phase, (ALT CRZ), the managed lvl change dot should not be lit.

**To Reproduce**
1. while in cruise (ALT CRZ) see that the managed lvl change dot is illuminated on FCU
2.
3.

**Expected behavior**
while in cruise phase, the dot should not be illuminated.

**Actual behavior**
while in cruise phase the dot is illuminated.

**References**
![managed lvl change dot](https://user-images.githubusercontent.com/71601106/112486657-85d67500-8d95-11eb-86c9-b5303a28c7e1.jpg)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by AirbusA320Pro** [comment]
Can confirm managed dot should not be illuminated when A/C is at ALT CRZ and no further altitude is selected. 
![IMG_6957](https://user-images.githubusercontent.com/75289637/112560894-0021ec00-8dcc-11eb-920b-9be951b70ba8.jpg)

**Comment by tracernz** [comment]
I think this may be fixed in custom AP branch, based on a screenshot I saw, but not 100%.

**Comment by MisterChocker** [comment]
Yes in our autopilot this is already resolved.

> I think this may be fixed in custom AP branch, based on a screenshot I saw, but not 100%.

**Comment by MisterChocker** [comment]
Closing since is issue is resolved in our experimental version.
