### ISSUE TITLE
[BUG]HI Airways automatically changed to LOW

### ISSUE THREAD

**Issue by alfalfasecas** [flybywiresim/a32nx#412]
**Branch**
 Stable 0.2.0

**Describe the bug**
Once a HIGH airway is introduced, it is automatically changed to a LOW airway after the introduction of the waypoint, despite the CRZ Level is beyond FL300

**To Reproduce**
1. Go to INIT page, LXGB/LEMD airports, FL360
2. In the FPL page, introduce the next FPL: DCT PIMOS UN869 BLN UN865 MORAL
3. UN869 is inserted, but after selecting BLN as waypoint it is automatically changed to B11 airway (LOW Airway). The same from BLN to MORAL (J865 instead of UN865)

**Expected behavior**
As the CRZ Level is selected to FL360, it is expected to HIGH Airways be chosen (UN869, UN865) insted of B11 and J865

**Screenshots or Videos**
https://streamable.com/u8hkpk

**Additional context**

**Comment by UncleClapton** [comment]
Hi.

The MCDU has a lot of issues, and it seems like this is another one of those things. A complete rework of the MCDU is being worked on, and it might address this problem.

**Comment by tareksabet** [comment]
Hi, It supposed to be fixed by #1544 I will close it, but I would like you to try again and it should work if it didn't then create a new issue.
Thanks for reporting.
