### ISSUE TITLE
Power/Flight Plan Issue

### ISSUE THREAD

**Issue by vbuff721** [flybywiresim/a32nx#4120]
**Mod Version**
Latest Dev build

**Describe the bug**
Not sure if related to the add-on or latest MSFS update. When starting from cold & dark, (more often then not) when cutting external power after starting and running the APU, MSFS seems to think power has been completely cut to the aircraft, bringing up the Flight Log you would normally see after completion of a flight. After this occurs, the MCDU completely erases the flight plan and FD will no longer follow a flight path.

**To Reproduce**
1. Start aircraft in cold and dark state
2. Turn on external power 
3. Turn on APU Master Switch
4. Start APU, wait for 100%
5. Turn on APU Bleed
6. Disconnect EXT PWR

**Expected behavior**
Aircraft should continue to run on APU after EXT PWR has been disconnected, flight plan and flight path should remain unchanged.

**Actual behavior**
Aircraft will either remain running or all instruments/displays will flash as if there was a power surge, thereby eliminating the flight plan in the MCDU. Some of the flight plan fixes will remain on the NAV display but there will not be any flight path for them to follow. Manual headings then have to be used to follow NAV aids. Managed heading mode will not work or aircraft will continue to bank in circles.

**References**
![Screenshot 2021-03-25 233245](https://user-images.githubusercontent.com/81400973/112573375-8c2f1600-8dc2-11eb-9547-affd06c28c60.png)

Was this working before/when did the issue start occurring?
Started after latest MSFS update.

Is this a problem in the vanilla unmodded game?
No

**Comment by MisterChocker** [comment]
I've never seen that issue before. Can you provide a short video?
