### ISSUE TITLE
New engine model - fuel flow imperial unit fix

### ISSUE THREAD

**Issue by Taz5150** [flybywiresim/a32nx#4131]
**Mod Version**

New engine model issue where fuel flow does not show values in imperial Units (LBS/H), although Unit title is correct.

**To Reproduce**

1. Turn On LBS Units in the MCDU
2. Reload the A/C
3. Check EWD

**Expected behavior**

Sample test - On ground, at Idle, fuel flow should be around 700 LBS/H.

**Actual behavior**

Sample test - On ground, at Idle, fuel flow shows around 300 LBS/H (300 corresponds to KG/H)

**References**

**Additional context**

Was this working before/when did the issue start occurring?
It works in the Stable versión. Bug started with new engine model.

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment]
Yes, already mentioned this in the pr, the conversion was removed.

**Comment by MisterChocker** [comment]
Issue has been resolved.
