### ISSUE TITLE
could not reach cruise level

### ISSUE THREAD

**Issue by youngryan7** [flybywiresim/a32nx#4135]
**Mod Version**
 custom mod

**Describe the bug**
 could not reach FL got to FL300 and wouldnt climb any higher due to speed - even set thrust to TOGA

**To Reproduce**

1. thrust  cl
2. FL360
3. stopped climb FL300 to maintain the speed - drag or thrust issue - engines were at 90% toga still loosing speed.

**Expected behavior**

expect to climb even at a low rate to reach FL and maintain speed

**Actual behavior**

had to divert couldnt keep the speed or FL

**References**

**Additional context**

Was this working before/when did the issue start occurring? after updated custom mod today 26/3

Is this a problem in the vanilla unmodded game?no

Discord username (if different from GitHub): ryanyoung26

**Comment by MisterChocker** [comment]
Please post the content of the build_info.json and provide sreenshots from PFD and lower ECAM. What was your GW?

**Comment by jwsteens** [comment]
I had this issue as well. Gross Weight was about 61 tons. Almost stalled at FL300, FL260 was safe. Here is a screenshot during descent:
![image](https://user-images.githubusercontent.com/74742373/112724742-0d96bd80-8f15-11eb-96e0-28f67c6228b3.png)

build_info.json:
`{
  "built": "2021-03-27T05:01:07+00:00",
  "ref": "autopilot",
  "sha": "683d55037e05dab68ac80dff914854f9984f2d00",
  "actor": "aguther",
  "event_name": "manual"
}
`

**Comment by youngryan7** [comment]
![2021-03-29 (1)](https://user-images.githubusercontent.com/59422760/112897267-5007f800-90d7-11eb-843c-9f71d8ebdb9c.png)
![2021-03-29](https://user-images.githubusercontent.com/59422760/112897272-51d1bb80-90d7-11eb-8eaa-b657a4151f17.png)

**Comment by youngryan7** [comment]
Still same issue. reduced speed to get up to cruise and now speed decreasing with TOGA
![2021-03-29](https://user-images.githubusercontent.com/59422760/112897547-ab39ea80-90d7-11eb-99cb-ac080f09e5ea.png)

91dadbc custom build

**Comment by youngryan7** [comment]
{
  "built": "2021-03-28T21:44:58+00:00",
  "ref": "autopilot",
  "sha": "91dadbc6573dada0477402cdd2b671b6426f30fd",
  "actor": "aguther",
  "event_name": "manual"
}

**Comment by MisterChocker** [comment]
Are you using the modern flight model?

**Comment by aguther** [comment]
> Still same issue. reduced speed to get up to cruise and now speed decreasing with TOGA
> ![2021-03-29](https://user-images.githubusercontent.com/59422760/112897547-ab39ea80-90d7-11eb-99cb-ac080f09e5ea.png)
> 
> [91dadbc](https://github.com/flybywiresim/a32nx/commit/91dadbc6573dada0477402cdd2b671b6426f30fd) custom build

Can you update to the lastest experimental version and try again? I’ve added more engines parameters to the flight data recorder in that build. If it still happens we would be interested getting the FDR files of your problematic flights. Maybe that helps finding out the issue.

**Comment by N822KL** [comment]
I too have suffered  with this apparent inability to climb above FL300 or 320. Just figured the the A320 felt at home there! Just kidding, I have had this happen in the default MS A320, the NX stable, developmental, and experimental builds. I have seen this behavior for many months, and just had it happen on a flight a couple of days ago. My only work around was to reduce speed to 240 or 220 on climb, but still couldn't reach upper 30s. Usually have to ask ATC to stay at FL310 or 320. Suspected a weight driven issue. Frustrating, good on anyone who solves this!

**Comment by Kamegohan** [comment]
Had some similar issue where speed was slowly decreasing and plane was trying to compensate due to pitching up the trimming. At this very moment the plane seemed to be okay. I later recognized that the plane was  covered with ice a bit.
After activating de-icing plane stabilized again.

**Comment by youngryan7** [comment]
![2021-03-30](https://user-images.githubusercontent.com/59422760/113028710-800cd500-9183-11eb-9fc9-8c86859031d3.png)
this is the best VS at the moment to get up to cruise. 

im not sure what you mean by flight model - i am using the flybywire installer and most recent updates!

**Comment by youngryan7** [comment]
picture above 


{
  "built": "2021-03-29T22:59:15+00:00",
  "ref": "autopilot",
  "sha": "d76765816421af5f95a5a239c91b6e58cbd53e7c",
  "actor": "aguther",
  "event_name": "manual"
}

**Comment by lukecologne** [comment]
It's a sim setting, Options->general->flight model

**Comment by youngryan7** [comment]
![2021-03-30 (1)](https://user-images.githubusercontent.com/59422760/113032057-52c22600-9187-11eb-92c2-07118b81bd31.png)

**Comment by youngryan7** [comment]
flight model was set to legacy - i will retry the flight now. 
where does it say that this should be selected when installing flybywire - thanks

**Comment by youngryan7** [comment]
![2021-03-30 (2)](https://user-images.githubusercontent.com/59422760/113035558-3f18be80-918b-11eb-9005-c5d7bb94bdd4.png)
Success thanks!

**Comment by MisterChocker** [comment]
Closing since issue resolved.
