### ISSUE TITLE
FBW Installer - Memory Leak / Application Running in Background

### ISSUE THREAD

**Issue by badgenes** [flybywiresim/a32nx#4139]
**Mod Version**

**Describe the bug**

I launched the version of the installer I had already installed in order to update it and then update the dev version of the a/c in order to obtain the custom AP (yay!).  All of that went as expected and following the a/c update I quit the FBW Installer.  12 hours later my PC is beginning to crawl and I start searching for the culprit.  FBW Installer had a working set of 27GB and climbing.  Windows was beginning to swap, etc.  I took a screenshot and killed the process, right about the time I decided I should inspect it with VS debugger and Process Explorer / Monitor to see exactly what it was doing.  Order of operations is always a PITA.  If it happens again I will definitely examine it and its actions.

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
This is not the installer repository.

The issue is already known and being worked on btw.
