### ISSUE TITLE
Nose gear NOT appearing

### ISSUE THREAD

**Issue by Sami244110** [flybywiresim/a32nx#4144]
**Mod Version**
0.5.4

**Describe the bug**
All lights in the cockpit are on and non of the knobs is working
From outside the nose gear does not show up

**To Reproduce**
![FlightSimulator 2021-03-27 12-43-34-51](https://user-images.githubusercontent.com/81465942/112717023-59406b80-8f03-11eb-8d0c-15dae1353218.png)
![FlightSimulator 2021-03-27 12-44-04-75](https://user-images.githubusercontent.com/81465942/112717026-5cd3f280-8f03-11eb-9c74-583bdc5f1655.png)

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by nyhmbo** [comment]
buy the game
