### ISSUE TITLE
strange engine parameters before starup

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#4146]
**Mod Version**

latest FBW Dev Version via Installer

**Describe the bug**

I see strange engine parameters before startup and also during start. EGT Value is high without engine runing. (see Pictures)
EGT starts to drop when the engine ignites. (overall strange values)
![EGT](https://user-images.githubusercontent.com/72918017/112719666-47a69600-8efa-11eb-91ce-e36db6ac89af.jpg)
![EGT_2](https://user-images.githubusercontent.com/72918017/112719668-4b3a1d00-8efa-11eb-8f51-3af53d644e31.jpg)

also Oil-Pressure is unrealistically high with over 200PSI

**To Reproduce**

1.cold and dark startup
2.look @ ECAM and engine page
3.engine start according checklist

**Expected behavior**

EGT should rise @ eng-start. / EGT is not ~700C° with ENG´s off

**Actual behavior**

look @ pictures - Strange values over all

**References**

see above

**Additional context**

Was this working before/when did the issue start occurring?
yes
Is this a problem in the vanilla unmodded game?
no

Discord username (if different from GitHub):

**Comment by tracernz** [comment]
Known issues with the experimental custom engine model.

**Comment by MisterChocker** [comment]
cc. @Taz5150

**Comment by tracernz** [comment]
Closing as known issue and already covered in #3117
