### ISSUE TITLE
Radio frequency selection knob jumping steps

### ISSUE THREAD

**Issue by mio9** [flybywiresim/a32nx#4150]
**Mod Version**

Experimental, 683d550

**Describe the bug**

Radio frequency selection knob jumping steps

**To Reproduce**

1. Start up the aircraft and get the radio working
2. Turn frequency knob to adjust frequency after decimal place
3. Weird 0.010 jumps occurs in some places

**Expected behavior**

For each time I turn the knob, it should be a steady 0.005 change, there should not be any weird jumps

**Actual behavior**

When turning the small knob, the increment jumps by 0.010 for some frequencies e.g. XXX.X15 jumps to XXX.X25 directly. Even when using VATSIM's vPilot command to adjust frequency, the radio refuse to set value that's being jumped

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Never used unmodded A320, but problem does not occur before.

Discord username (if different from GitHub):
MiO9#0109

**Comment by MisterChocker** [comment]
The knob uses some acceleration (the real one has this too).
This is the reason the knob "jumps" frequencies.

**Comment by tracernz** [comment]
The reason it jumps is 8.33 kHz/25 kHz spacing. See https://833radio.com/news/show/7 for more info on that.

**Comment by mio9** [comment]
Oh thank you so much for the information, closing the issue as it is not really an issue by now. Confirming radios are intended to jump those frequencies for spacing.
