### ISSUE TITLE
THR LVR position (animation) doesn't match actual thrust lever pos

### ISSUE THREAD

**Issue by ghosh9691** [flybywiresim/a32nx#4151]
**Mod Version**

{
  "built": "2021-03-27T05:01:07+00:00",
  "ref": "autopilot",
  "sha": "683d55037e05dab68ac80dff914854f9984f2d00",
  "actor": "aguther",
  "event_name": "manual"
}

**Describe the bug**

After calibrating the throttle (Logitech Extreme 3D Pro) using the EFB, the "LVR CLB" message on PFD keeps flashing despite throttle being at the CLB detent and "THR LVR" being shown in green on the PFD. The message keeps flashing even in CRZ mode.

**To Reproduce**

1. Make sure throttle is calibrated via EFB settings page
2. Operate the aircraft normally by engaging auto throttle and auto pilot as appropriate
3. Reduce throttle to "CLB" setting when commanded

**Expected behavior**

Expect PFD to annunciate "THR LVR" for speed mode and white "LVR CLB" message to stop flashing

**Actual behavior**

The THR LVR message is annunciated but LVR CLB never goes away

**References**

**Additional context**

![Screenshot (10)_LI](https://user-images.githubusercontent.com/3387895/112724518-2b026200-8eea-11eb-8033-cbe6479b9781.jpg)
![Microsoft Flight Simulator Screenshot 2021 03 27 - 10 37 43 96_LI](https://user-images.githubusercontent.com/3387895/112724541-42d9e600-8eea-11eb-8b44-27bb0866d49f.jpg)

Was this working before/when did the issue start occurring?  Yes

Is this a problem in the vanilla unmodded game?  N/A

Discord username (if different from GitHub):

**Comment by gb09f** [comment]
I'm also seeing this bug - latest experimental build via installer.
(Custom autopilot is beautiful work).

**Comment by trystanghk** [comment]
Also experiencing this on the latest experimental build via installer. TCA Thrustmaster.

**Comment by Spartan3001961** [comment]
Same here with Airbus throttle quadrant, even though its all set up ok. I also noticed that the PFD doesn't show that its in FLEX mode either when taking off, but shows MAN THT. In the old Custom version it used to show the FLEX and Temp. I import all my  plans via SimBrief and fully set up the MCDU as well.

**Comment by LentuloBatiato** [comment]
Same problem here. And after takeoff it appears the message "T.O. Inhibited" in red, and/or ASYM. THRUST (if I remember correctly).

**Comment by MisterChocker** [comment]
To bring some light into the darkness, the animation that shows the thrust levers position is "rounded" hence less accurate than the position information we use to determine the thrust levers positions.
Long story short, if the FMA shows your thrust levers are not set correctly, it's right.

**Comment by MisterChocker** [comment]
Closing since working as intended, I'll check whether there is anything we can do.

**Comment by Azphilosopher** [comment]
maybe this is why my auto throttle seems to not work despite placing the throttle detent clearly where it's supposed to be.  Had some very weird flights at 450+ kts.  It really messes with your ability to successfully change altitude too.

**Comment by Saschl** [comment]
Hi, could you also try to post your ThrottleConfiguration.ini here? I think this issue might also be related to the range for the detents

**Comment by ghosh9691** [comment]
@Saschl , here's the throttle config:



[throttle_common]
reverse_on_axis = false

[throttle_axis_1]
reverse_low = 0.000000
reverse_high = 0.000000
reverse_idle_low = 0.000000
reverse_idle_high = 0.000000
idle_low = -1.000000
idle_high = -1.000000
climb_low = 0.520000
climb_high = 0.520000
flex_mct_low = 0.840000
flex_mct_high = 0.840000
toga_low = 1.000000
toga_high = 1.000000

[throttle_axis_2]
reverse_low = 0.000000
reverse_high = 0.000000
reverse_idle_low = 0.000000
reverse_idle_high = 0.000000
idle_low = -1.000000
idle_high = -1.000000
climb_low = 0.520000
climb_high = 0.520000
flex_mct_low = 0.840000
flex_mct_high = 0.840000
toga_low = 1.000000
toga_high = 1.000000

@MisterChocker , I don't think that's an accurate statement. This is not just an animation issue. I have moved the throttle through the entire range very slowly and at no point does the "LVR CLB" prompt go away!!! The FMA does annunciate "THR CLB" and then if the throttle is moved further, it annunciates "MAN THR" and then "MAN TOGA". Also, at MAN TOGA, it no longer annunciates "NAV". It only annunciates "SRS".

**Comment by tracernz** [comment]
Hi @ghosh9691. You may want to add a bit of a deadband on each of the detents. Try subtracting 0.02 on the low values, and adding 0.02 on the high values.

**Comment by Saschl** [comment]
@ghosh9691 thank you so much. As @tracernz already mentioned you’re missing some range around the detents. We’re aware that this might not be clear through the UI and are looking into improvements

**Comment by ghosh9691** [comment]
@tracernz , I will try that out tomorrow and report back here. Btw, the above was written out by the EFB throttle configuration screen. So maybe if we need a small band, then the EFB screen should add that by itself.

**Comment by ghosh9691** [comment]
After making the changes suggested by @tracernz  above, and updating to build (as stated below), this is no longer an issue. I have also noticed the following in this new build:

- The FMA now correctly annunciates: MAN FLX with SRS & NAV, also MAN TOGA with SRS & NAV (was not doing so in previous build
- Correctly annunciates THR CLB and no longer has the "LVR CLB" flashing message
- A/P no longer does the happy (?) S-dance when approaching a waypoint as it was doing in previous build (a left turn followed by a right turn followed by correct turn to capture track to next waypoint)

Given the above, I am closing this bug as "RESOLVED"
