### ISSUE TITLE
[REQUEST] PDF Checklists

### ISSUE THREAD

**Issue by SimonVanacco** [flybywiresim/a32nx#4156]
Hi, 
I would find it really cool to have the A32NX checklists available as PDF download, so that i could print them and follow them IRL instead of using the MSFS20 Checklist UI !

I am not sure if this request is really in the scope of this repository, feel free to close without comments if that's the case :) Thanks for the amazing work on this aircraft !

**Comment by Benjozork** [comment]
Please follow the provided feature request template and then I can reopen
