### ISSUE TITLE
ATC frequencies blank and left-side NAV stuck in ILS

### ISSUE THREAD

**Issue by Haeleus** [flybywiresim/a32nx#4157]
**Mod Version**

Both Development c5daad1 and Experimental 965e2b0

**Describe the bug**

Two chronic issues:
1. left-side NAV is stuck in ILS display regardless of mode set. Can change dial but stays in ILS even if for dial set to arc, plan, etc. As a result constraint view also not working on left-side. Right-side nav functioning as expected.
2. ATC frequencies are black/blank and will not display.

**To Reproduce**

Occurs every time since start of week no both developer and experimental versions. No exceptions.

**Expected behavior**

Left-side nav should display range and mode selected in dials.
ATC frequency should be visible both active and standby.

**Actual behavior**

Left-side nav stuck in ILS mode.
ATC frequencies not displaying.

**References**

Screenshot of both issues: [https://ibb.co/rGxhv1q](url)

**Additional context**

Was this working before/when did the issue start occurring?
Both working as intended before this week.

Is this a problem in the vanilla unmodded game?
Not sure. I deleted any other non-livery mods such as a Longitude mod. I can't tell if this is a sympton of another setting or some sort of cache I need to delete.

**Comment by blazinga350** [comment]
i also have this problem

**Comment by Benjozork** [comment]
Can you try without anything else in your Community folder  ?

**Comment by blazinga350** [comment]
it still occurs

**Comment by Haeleus** [comment]
I only have liveries and the FBW A320 in my community folder. I deleted FBW and tried the stock A320 and the nav/freq loaded fine. Then used installer and launched again with the issue re-occurring.

**Comment by MisterChocker** [comment]
You might want to try without any additional liveries.

**Comment by MisterChocker** [comment]
Closing since no response from op.
