### ISSUE TITLE
Errors / Lack of details in the cockpit.

### ISSUE THREAD

**Issue by AntoineXWB** [flybywiresim/a32nx#4159]
**Is your feature request related to a problem? Please describe.**

Good evening to you,  I have a small list of things to change aesthetically
Here is the list :

 - There is no emergency white rope (In MFS) to descend from the cockpit to the outside if the cabin is closed.
 - The "Disk Stowage" signs are on the two doors on either side of the cockpit. In general the floppy disks and CDs are put on the Captain's side and if there is no more room, the rest is put on the F / O side.
- The "CVR HEAD SET" in MFS is shown as a button while it is a silver headphone jack.
- The light control buttons on the currently inoperative windows are not smooth but "jagged" on the outline like those below the autopilot controls.
- When ANN LT is set to "TEST" the "Side Stick Priority" does not come on completely, the arrow on each of the LEDs is missing.
- Still on ANN LT, when "DIM" is actuated, the pushbutton lights should decrease their brightness by approximately 50% when the "DIM" position is maintained.

**Describe the feature you'd like to see implemented**

**References**

I have been in several A320 Neo cockpits over the past two weeks (FlyNas, Saudia Arabia, Spring Air, TAP)
![image](https://user-images.githubusercontent.com/81491742/112735579-51a5b480-8f4d-11eb-9c09-aff167a6e724.png)
![image](https://user-images.githubusercontent.com/81491742/112735580-566a6880-8f4d-11eb-9e77-c96b9b9ddf02.png)
![image](https://user-images.githubusercontent.com/81491742/112735581-59fdef80-8f4d-11eb-976d-80f3ca8b4290.png)
![image](https://user-images.githubusercontent.com/81491742/112735583-5cf8e000-8f4d-11eb-829d-bd5d1b7c8b95.png)
![image](https://user-images.githubusercontent.com/81491742/112735585-61bd9400-8f4d-11eb-9984-a71c57c43fcb.png)
![image](https://user-images.githubusercontent.com/81491742/112735586-641fee00-8f4d-11eb-909a-a1be34786591.png)
![image](https://user-images.githubusercontent.com/81491742/112735589-684c0b80-8f4d-11eb-830c-969ba685d3b4.png)

**Additional context**

Discord username (if different from GitHub):
@AXWB on Discord

**Comment by MisterChocker** [comment]
Please open an issue for every single issue you have posted. We can't track multiple issue in one single issue.
I'll close this issue now, please do go ahead open a new issue for every item you listed. Feedback is highly appreciated!
