### ISSUE TITLE
[BUG] Airspeed indicator abruptly stops working during descent from cruise alt in managed alt/speed mode

### ISSUE THREAD

**Issue by mythicfci** [flybywiresim/a32nx#416]
**Branch**
Stable 0.20

**Describe the bug**
Airspeed indicator stops working (drops to 0) during managed alt/speed descent from cruise, causing the plane to pitch down rapidly to gain speed. After some time, the airspeed indicator starts working again. This has happened on 2 flights in a row for me now.

**To Reproduce**
1. Start a flight, take off, climb to cruise as normal.
2. Descend on managed alt/speed mode.
3. At around ~20,000ft (+/- a few thousand feet), the airspeed indicator will suddenly drop all the way below the minimum airspeed on the gauge, and the autopilot accordingly will pitch the aircraft steeply down.
4. Some time (I didn't measure this exactly, but I'd guess around 30s-1min) later, the airspeed indicator goes back to normal.

**Expected behavior**
The airspeed indicator should work properly all throughout descent.

**Additional context**
This has happened twice now to me, on two flights in a row on Stable 0.20. The second time, the pitch down was so dramatic that MSFS triggered a plane crash due to airframe overstress.

**Comment by MattPaxtonBel** [comment]
Try probe heat to ON, seems that the AUTO mode of the probe heat doesn't work in the A320neo.

**Comment by CPU-Blanc** [comment]
Hey there!
Whilst I'm not on the dev team, I've had this issue before due to ice on the pitot tubes. What was the TAT when this happened, and was your probe anti-ice turned on? I don't believe it defaults to auto like it should currently.

**Comment by mythicfci** [comment]
I don't believe I touched probe heating throughout the flight, I assumed it was working on auto like it should've been. I'll try that the next time I get a chance to fly.

If that is the issue, then perhaps @ devs we could get a fix to the anti-ice, to get everything working on auto as it should? (Thanks so much!)

**Comment by 0nnyx** [comment]
Had the same behavior when going through clouds or reaching high altitude only. This is addressed by turning probe heat manually ON. You should change your bug to Make auto probe heat work or set to ON by default as workaround if unable.

**Comment by olidoc2000** [comment]
I still get the same issue even though probe  heat is set to ON right from the beginning of the flight. Do you guys still experiment this issue ?
