### ISSUE TITLE
Rudder Issues

### ISSUE THREAD

**Issue by blazinga350** [flybywiresim/a32nx#4160]
**Mod Version**
Stable Version
**Describe the bug**
Rudder moves left to right very slowly even when my feet are off the rudder pedals in the air. This makes the autopilot automatically input the opposite aileron, but then my plane continues to fly in a slanted position. On the ground, the rudder severely inputs left rudder when my feet are off the rudder pedals. When I went to the F CTL page, I could see the rudder moving even though I did not touch the rudder. My dead zones are set to 10%.

**To Reproduce**
1. Taxi on ground
2. Take off with a fully configured flight plan.
3. Engage autopilot when needed.

**Expected behavior**
Rudder stays in the middle and does not move.

**Actual behavior**
Rudder moves left to right slowly in the air. And moves severely to the left on the ground.

**References**
Not right now.

**Additional context**

Was this working before/when did the issue start occurring?
After 5.4 stable update.
Is this a problem in the vanilla unmodded game?
IDK

None.

**Comment by MisterChocker** [comment]
Please check your deadzones.

**Comment by blazinga350** [comment]
should i increase them?

**Comment by MisterChocker** [comment]
Following your description of the situation, this sounds like a deadzone issue.
You should try to increase you sensitive on the rudder axis until you don't you no longer see invalid inputs.

**Comment by blazinga350** [comment]
so should i increase my deadzones to 20%? i am a bit confused

**Comment by MisterChocker** [comment]
You should to try to increase your deadzone until the issue fixed.

**Comment by blazinga350** [comment]
It still occurs.

**Comment by blazinga350** [comment]
like the rudder moves by itself even though I don't touch the rudder pedals. Also if I increase the dead zone too much, it makes larger movements once I am out of the deadzone

**Comment by gestegassy** [comment]
This occurred to for me as well today after installing Experimental c7e6cbf. The rudder (virtualfly ruddo+) has become unusable. When I depress a pedal, in the sim I can see both pedals slightly moving at the same time). Rudder is not usable at this point (it was fine before). Thanks for the awesome work!

**Comment by MisterChocker** [comment]
Closing since issue is resolved.
