### ISSUE TITLE
emmisive: side stick priority not accurate

### ISSUE THREAD

**Issue by AntoineXWB** [flybywiresim/a32nx#4171]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**

When ANN LT is set to "TEST" the "Side Stick Priority" does not come on completely, the arrow on each of the light is missing.
Still on ANN LT, when "DIM" is actuated, the pushbutton lights should decrease their brightness by approximately 50% when the "DIM" position is maintained.

**References**

![image](https://user-images.githubusercontent.com/81491742/112745128-6cf0de00-8fa6-11eb-900b-824c73c3c03a.png)
I haven't found a photo yet.

**Additional context**

Discord username (if different from GitHub):
@AXWB

**Comment by tracernz** [comment]
Fixed in #4929
