### ISSUE TITLE
PDF checklists

### ISSUE THREAD

**Issue by SimonVanacco** [flybywiresim/a32nx#4174]
**Is your feature request related to a problem? Please describe.**
My request is not related to a problem 

**Describe the feature you'd like to see implemented**
I would really enjoy having the a32nx checklists as downloadable pdf files so that I can look at them irl instead of using the checklist UI in msfs2020 which I don't personally like 

**References**
It could look like that : https://i.stack.imgur.com/okOMC.jpg

**Comment by MisterChocker** [comment]
we do have a checklist. https://cdn.discordapp.com/attachments/747571948342476850/813173610205544458/FBW_A32NX_CHECKLIST_V1.2.pdf
