### ISSUE TITLE
Speed and Heading knobs become fixed to +/- 10 kts/degs and cannot increment or decrement single figures any more

### ISSUE THREAD

**Issue by 74Captain** [flybywiresim/a32nx#4179]
**Mod Version**

Dev version, updated via installer earlier today 28/03/2021, but this also appeared in the previous day's build as I first encountered it yesterday (and reported in the #help discord channel
{
  "built": "2021-03-28T12:59:20+00:00",
  "ref": "master",
  "sha": "81b60295737ef23e2b47c75e18cdf7239967d6ad",
  "actor": "MisterChocker",
  "event_name": "manual"
}

**Describe the bug**

At a certain point during approach to my final destination, if I try to override the autopilot flying the approach, the SPD and HDG knobs only effect in +/- 10 kts/deg increments, cannot to just 1kt / 1deg at a time any more.

**To Reproduce**

1. I was flying the following route from LSZH to EGLL: LSZH/28 F380 VEBIT3H VEBIT T51 LASUN UT10 RLP UL613 DIDOR UT10
 ALESO ALESO1H EGLL/27L
2. I controlled the descent manually using V/S of -2200ft/min down to FL180 @ ETVAX, then to FL70 @ BIG.
3. At this point, the AP had me flying on a heading of approx 316 deg to BIG. I was flying VATSIM and hadn't been contacted by Heathrow controller yet so entered the hold. I engaged manual heading mode and attempted to dial in 122 deg as per the ALESO 1H arrival chart, but it weirdly stuck in increments of 10, so I could really only select 126 deg as the closest heading...
4. Once on the outbound leg I enabled manual SPD mode and attempted to dial my speed back to 220 kts as I realised I was too fast. Once again, this was restricted to multiples of 10, so I couldn't exactly dial in 220.
5. Once established contact with Heathrow Approach they of course gave me vectors, and I was unable to follow them exactly - so when they told me to leave BIG heading 265 deg, I could only select 266 (close enough!) The same persisted as they gave me a left turn 080 and I could only select 076 or 086, etc.  
6. Equally when told to reduce to 180 kts, then 160 kts I could only select other 'nearby values' (I can't remember what now) 

**Expected behavior**

Simply to ensure that single-digit entry on the autopilot is possible

**Actual behavior**

As above - was only able to select SPD and HDG in 10's so for example to turn from 266 to 086, instead of whizzing through 180 separate degrees, it went 266-276-286-296-306-316-326-336-346-356-006-016-026-036-046-056-066-076-086

**References**

Sadly was too busy trying to manage ATC on VATSIM and didn't think to take a video of the behaviour

**Additional context**

The same thing occurred on my "outbound" journey yesterday - from EGLL to LSZH.  Having arrived via the BLM 2Z STAR, and passing over GIPOL, I decided that instead of following the programmed route in the MCDU & on-screen, I would instead fly as per chart 11-3 for LSZH (ILS OR LOC RWY 28) which involves flying 096 from GIPOL to the KLO VOR (overhead the airport) then an outbound course 082. As I approached GIPOL on heading 107 from BLM, then tried to change it to 096 it was again stuck in increments of 10, so I selected 097. When I got overhead KLO I had to select 076 (choosing 086 would have resulted in an un-doable hard right turn onto ILS for 28 so thought it better to take it a little wider).

Was this working before/when did the issue start occurring?
Yes this used to work - it seems the Dev version from a couple of days ago has introduced this issue?

Is this a problem in the vanilla unmodded game?
I do not know.

Discord username (if different from GitHub):
Mike T#2970

**Comment by Benjozork** [comment]
This is an issue with MSFS which was supposed to be fixed with Sim Update 3 but wasn't

**Comment by 74Captain** [comment]
Interesting...When I mentioned it yesterday in the Discord - Kiwi2022[Z+1] said that if I reproduced it to report it here... No mention of a known issue from anyone then.  Sorry to have wasted your time!

**Comment by FRYYYYYY** [comment]
> Interesting...When I mentioned it yesterday in the Discord - Kiwi2022[Z+1] said that if I reproduced it to report it here... No mention of a known issue from anyone then.  Sorry to have wasted your time!
> 
> 

What hardware are you using? I have a TCA quadrant and set some special actions. After resetting it to the default it was gone. Please try to use default config.
