### ISSUE TITLE
[BUG] APU start, Electrical, and screen brightness

### ISSUE THREAD

**Issue by A320pilotIRL** [flybywiresim/a32nx#418]
I am running the latest "stable" release. 
Loaded up cold and dark and turned batteries on. 

Even after tediously turning every screen brightness up (not realistic IRL), I noticed NO cockpit screens power up when battery power is applied. This is incorrect as the batteries should power some of the DU's. 

Also noted that starting the APU did not give me any AC power. The APU would complete start up, show AVAIL on the start Pb, and yet NO power to the airplane. 

To reproduce... start cold and dark, turn screens on, turn batteries on. Nothing. Then start the APU. Nothing. 
I had to use EXT power to get the screens on, then once I turned that off, I could keep power from the APU.

Also noted that if you don't start in "cold and dark", but rather start on the runway, the ECAM has tons of issues (like no APU or Bleed page), can't start the APU, etc

PFD brightness is a bit over-done. Shouldn't reduce the contrast and make it hard to read.

**Comment by NathanInnes** [comment]
Is this still an issue for you? @A320pilotIRL

**Comment by A320pilotIRL** [comment]
Nope seems fixed

**Comment by NathanInnes** [comment]
Closing issue as you stated it has been resolved. If you have further issues with this please reopen this issue.
