### ISSUE TITLE
Hardware inputs not recognized by FCU

### ISSUE THREAD

**Issue by bmorera8** [flybywiresim/a32nx#4180]
**Mod Version**
Experimental 9803984

  "built": "2021-03-28T12:59:20+00:00",
  "ref": "master",
  "sha": "81b60295737ef23e2b47c75e18cdf7239967d6ad",
  "actor": "MisterChocker",
  "event_name": "manual"

**Describe the bug**
When using the Experimental Version with the new CFBW, I no longer have the ability to change heading or airspeed (I believe the same applies to VS) using the two scroll wheels on the HC Bravo's autopilot panel. For some reason, the ability to select altitude has not been affected.

**To Reproduce**

1. Use Experimental Version with new Custom Fly by Wire. 
2. Use Honeycomb Bravo Throttle Quadrant.
3. Use the left scroll wheel on the HC Bravo to select HDG, then use the right scroll wheel to increase/decrease the heading, but nothing will happen.
4. Repeat step 3 but set the left scroll wheel to IAS.
5. Repeat with VS.

**Expected behavior**

Setting the left scroll wheel to HDG and subsequently moving the right scroll wheel left/right should increase/decrease the selected heading. Same goes for IAS, VS, and ALT.

**Actual behavior**

For HDG, IAS, and VS, nothing happens. I found that ALT seems unaffected by this bug and works normally. 

**References**

**Additional context**

Was this working before/when did the issue start occurring? This issue only started occurring when the new CFBW was released in the Experimental version. These features still work fine in the Development and Stable releases.

Is this a problem in the vanilla unmodded game? no

Discord username (if different from GitHub): BryanMorera#6040

**Comment by aguther** [comment]
We are currently using custom variables for those things and need to analyze if and how it's possible to use the original values (to be sure no other component is manipulating it and we get the info that it changed).

Descriptions:
https://github.com/flybywiresim/a32nx/blob/autopilot/docs/a320-simvars.md
https://github.com/flybywiresim/a32nx/blob/autopilot/docs/a320-events.md

**Comment by bmorera8** [comment]
Thanks! I just wanted to make sure the team was aware of it. You guys are truly doing an exceptional job!

**Comment by bisinchi** [comment]
Hi, I seem to have similar issue with the Warthog joystick to which I have with the AP & ATHR disconnect. Worked fine before, still works fine with development version.

**Comment by ferryvanaesch** [comment]
Is it possible to update these variables through FSUIPC, or Spad.Next or something?

**Comment by aguther** [comment]
Please read the docu here:
https://docs.flybywiresim.com/start/autopilot-fbw/

If you look here you will find even two files that might help you for FSUIPC or SPAD.neXt:
https://github.com/flybywiresim/a32nx/tree/master/docs
