### ISSUE TITLE
Amplified roll oscillations when AP on with increased sim rate.

### ISSUE THREAD

**Issue by domaubert** [flybywiresim/a32nx#4183]
**Mod Version**

Latest custom Dev version with custom AP.

**Describe the bug**

With AP on, the plane starts to oscillates along the roll axis when increasing the sim rate until it becomes very unstable.

**To Reproduce**

1. Set up a flight plan, turn on AP, reach cruise altitude
2. Increase the sim rate by two or more 'levels' above the standard rate

**Expected behavior**

The plane should remain "roughly" stable along the roll axis as the sim rate is increased by two or more levels.

**Actual behavior**

When the sim rate is increased by one level with AP on, the plane behaves as expected, staying on course with no or very little roll corrections. When the sim rate is increased by two (or more levels), oscillations along the roll axis appear and are amplified until the plane becomes dangerously unstable. This unstable regime disappears when the sim rate is lowered back to the standard one or the standard one +1. 

**Additional context**

Was this working before/when did the issue start occurring?
No problem with the previous custom dev version, I used to increase the sim rate by two or more levels for long flights.
It appeared with the new AP.

Is this a problem in the vanilla unmodded game?

No idea, I don't use it.

**Comment by aguther** [comment]
Increased sim rate is something we can look into when features settle. Feedback in another ticket was that it seems to be ok up to 2x but not beyond.

I hope at a certain point it can be solved at least for cruise flight by multiplication of overall outputs etc. otherwise it will be very difficult to support it. It‘s also about understanding how the sim does the increased update rate. Could be that it‘s for the AP like a massive drop in frame rate.

**Comment by Kamegohan** [comment]
I am not very deep in programming or something but had this issue with stock A320neo about one or two months after MSFS was released.
AP was going well up to 4x sim rate but plane was wiggling (thought it could be due to compensating the wind effects) a lot.

Just as additional input...

**Comment by aguther** [comment]
In general it's about flight control loop stability and Nyquist-Shannon...

**Comment by Kamegohan** [comment]
As I am always trying to learn how to fly more realistic (routines, navigation, manouvres,...) I usually don't use this fast-forward function.
Did not want to skip the flight as a friend called and asked to come over in a few minutes, so I decided to give it a try.

But to be honest, personally, I won't miss this feature/function from the sim if it can't be implemented correctly as you already stated - in IRL its not possible to fast-forward the flight.

Just wanted to state that it's not a pure A32NX problem and it seems to come from the sim itself.

**Comment by aguther** [comment]
I did some tests and it's indeed that the sim behaves like reducing the framerate when simulation rate is increased. That also means that it gets worse when you already have not so good performance.

I was able to use 4x without any issues, but with 8x it was also oscillating.

![unknown](https://user-images.githubusercontent.com/6629914/115970162-09c08000-a541-11eb-8357-29b6b878da88.png)

**Comment by sidnov** [comment]
Thanks to Andreas for his work on improving the AP stability while being able to simrate to a permissible limit which fixes this issue
