### ISSUE TITLE
ISIS brightness buttons should be push&hold

### ISSUE THREAD

**Issue by St54Kevin** [flybywiresim/a32nx#4184]
**Mod Version**

{
  "built": "2021-03-28T16:25:26+00:00",
  "ref": "merge",
  "sha": "b280541409b0d46dd7513703640de179ccfb2126",
  "actor": "Duncan10",
  "event_name": "manual"
}

**Describe the bug**

The + and - brightness buttons on the ISIS need to be clicked repeatedly.
![image](https://user-images.githubusercontent.com/448627/112814731-dee92600-907f-11eb-8848-b60580563edd.png)

**To Reproduce**

1. Load up the plane
2. Change ISIS brightness
3.

**Expected behavior**

You should be able to click and hold the two buttons like you are able to with the MCDU brightness buttons

**Actual behavior**

**References**

IRL experience

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by davidwalschots** [comment]
@komp1821 provided additional information on the press duration to go from least bright to full brightness. It can be found [here](https://discord.com/channels/738864299392630914/758126266859388948/832178638852980746).

**Comment by 2hwk** [comment]
Reopened as the PR was reverted, new PR has been created that fixes the issue that caused the rollback to begin with.
