### ISSUE TITLE
More Interactive stuff with cabin

### ISSUE THREAD

**Issue by nick2332f** [flybywiresim/a32nx#4185]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**

I want to see more stuff like the pilot speaks when its cruise and when descent starts.

**References**

**Additional context**

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by MisterChocker** [comment]
Please discribe the feature you are requesting with more details!

Also:

> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning

**Comment by nick2332f** [comment]
for example, in flights some good pilots who care about passangers speak to them... Like we are about to start descent.... Well not exactly that but more stuff like the tray table working... Its kind of hard to know.

**Comment by MisterChocker** [comment]
Please fill the details into the provided template.
What you described is very airline specific and has nothing todo with the pilots itself.

**Comment by nick2332f** [comment]
thats the thing, How?

**Comment by nick2332f** [comment]
my title is more interactive stuff, then lets talk about the table and the cabinets...

**Comment by MisterChocker** [comment]
Please join our discord for discussions like this (or use the github discussions tab).
Github issues are for tracking requested features and bug reports only.

**Comment by Benjozork** [comment]
Going to close this as it's not requesting a specific fwtaure.

**Comment by nick2332f** [comment]
tray table

**Comment by Benjozork** [comment]
The tray table is already planned to be added

**Comment by nick2332f** [comment]
great! About those cabinets on the left side and behind the seat? Also i noticed more buttons that need to be switched on like some cabin controlls on pmp a321, will you add them too?

**Comment by Benjozork** [comment]
Maybe we'll add the cabinets. Priority is on fixing the modelling mistakes from Asobo though.

Can you be more specific on what cabin controls you're referring to ?
