### ISSUE TITLE
[BUG] LRV MCT displayed on aircraft power-up

### ISSUE THREAD

**Issue by A320pilotIRL** [flybywiresim/a32nx#419]
I started up the airplane on external power, leaving the thrust levers in the idle position the entire time from load up, and the FMA is displaying lever MCT, before I have even started the engines

Using the latest stable release￼￼￼

**Comment by Benjozork** [comment]
Duplicate of #351

**Comment by Curtis-VL** [comment]
Fixed in the following PR #399 - Thanks for the report!
