### ISSUE TITLE
Large fuel burn imbalance

### ISSUE THREAD

**Issue by Alien217** [flybywiresim/a32nx#4194]
**Mod Version**
Experimental

**Describe the bug**
Large fuel imbalance between left and right wing tanks during long flight, not consistent with differences in fuel flow to engines 1 and 2. Fuel crossfeed doesn't work to solve the problem.

**To Reproduce**
1. Take off from KJFK with 12.9 tons of fuel
2. In cruise notice that engine 2 is burning 40 kg/hour more fuel than engine 1. Multiplied by 5.5 hours, this would translate in an extra total fuel burn of 220 kg by engine 2. Notice before midway in the flight that the fuel imbalance between left and right tanks exceeds already 400 kgs. Turn on fuel crossfeed.
3. Land in KLAX with about 2 tons of fuel in the left tanks and 1 ton of fuel on the right tanks, despite fuel crossfeed on during most of the flight.

**Expected behavior**
The difference in fuel burn between engines 1 and 2 is realistic, no two engines are the same in the real world. However one would expect a fuel imbalance of about 220 kgs at landing without using crossfeed, and no fuel imbalance with crossfeed on.

**Actual behavior**
Landed with 1 ton fuel imbalance despite fuel crossfeed on.

**References**
![Screenshot 2021-03-28 225743](https://user-images.githubusercontent.com/81567107/112836412-16f56680-908a-11eb-94dd-40710bd37f64.png)

**Additional context**

Was this working before/when did the issue start occurring?
This was my first long flight with the new experimental version, and third flight overall. Before that I was using the custom fbw.

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub): predator117

**Comment by Taz5150** [comment]
Thank you so much for the feedback. Will run long range tests once we have the FDR set for engine/ fuel parameters and sort out where the problem is.

**Comment by Taz5150** [comment]
Update: I have pin-pointed the issue. Will have a solution shortly.

**Comment by Taz5150** [comment]
New fuel model has been pushed in the autopilot branch and is ready to be re-tested. Let me please know how it goes.

**Comment by Alien217** [comment]
> New fuel model has been pushed in the autopilot branch and is ready to be re-tested. Let me please know how it goes.

Just did a 3,5 hour flight and the difference in fuel between the two wings at the end was just 25 Kg. Great job!
