### ISSUE TITLE
MCDU Approach Activation

### ISSUE THREAD

**Issue by noodles4186** [flybywiresim/a32nx#4198]
When the MCDU reaches or if you select APPROACH Mode on the Perf page it deletes the FP and does a direct to and from the airports and deletes the waypoints on the experimental version

**Comment by Benjozork** [comment]
Please do not delete the issue template.

**Comment by noodles4186** [comment]
What issue template?

**Comment by FRYYYYYY** [comment]
> What issue template?

![image](https://user-images.githubusercontent.com/13643787/113036624-d7677100-9194-11eb-96db-9edfbb732e67.png)

This. Please follow the template!

**Comment by noodles4186** [comment]
There wasn’t any template there I click open ticket and that’s how it came like that

Chris
________________________________
