### ISSUE TITLE
[BUG] FCU

### ISSUE THREAD

**Issue by A320pilotIRL** [flybywiresim/a32nx#420]
Spinning the ALT knob to change PFD altitude only works properly in the air

Running latest stable release.

**Comment by Curtis-VL** [comment]
Can you explain what is meant by this further? How should the behaviour be different on the ground? etc.

Please follow the issue template also otherwise future issues may be removed! 👍

**Comment by A320pilotIRL** [comment]
My bad Curtis, I mean the way you have the ALT knob behave in the air is perfect. Any spinning of the knob will affect the PFD altitude. On the ground, you are forced to push/pull the ALT knob to get the PFD altitude to change.

**Comment by Curtis-VL** [comment]
I'll have a look into this! I didn't notice this personally,
