### ISSUE TITLE
Consecutive waypoints with the same name but a different location are removed from the flight plan

### ISSUE THREAD

**Issue by davidwalschots** [flybywiresim/a32nx#4201]
**Mod Version**
master

**Describe the bug**
Consecutive waypoints with the same name but a different location are removed from the flight plan.

**To Reproduce**
1. Go to `MCDU INIT` and enter `EHAM/EHRD` in `FROM/TO`.
2. Go to `F-PLN`.
3. Add `SPL` after `EHAM`, select the closest one.
4. Add `SPL` after `SPL`, select another `SPL` than the one previously selected.

**Expected behavior**
There are two consecutive `SPL` waypoints.

**Actual behavior**
There is only one `SPL` waypoint, despite having selected `SPL` at different locations.

**Additional context**

Discord username (if different from GitHub): SjotgunSjonnie#9623

**Comment by 2hwk** [comment]
Fixed by 4953 closing ☑️
