### ISSUE TITLE
EVAC COMMAND lights does not illuminate

### ISSUE THREAD

**Issue by davidwalschots** [flybywiresim/a32nx#4204]
**Mod Version**
master

**Describe the bug**
The EVAC COMMAND button seems to not work as intended. The alarm sounds, but lights do not illuminate. The push button when pressed moves outward instead of inward.

**To Reproduce**
1. Remove the COMMAND guard.
2. Press the COMMAND button.

**Expected behavior**

- [ ] 1. The COMMAND button's ON light turns on.
- [ ] 2. The COMMAND button's EVAC light flashes in red.
- [x] 3. The COMMAND button is pushed inward.

**Actual behavior**

1. The COMMAND button's ON light does not turn on.
2. The COMMAND button's EVAC light does not turn on. 
3. ~~The COMMAND button is pushed outward.~~

**References**
The button in the pressed state:

![image](https://user-images.githubusercontent.com/1074786/113001756-682c5580-9171-11eb-8f9f-3f3e2c3a7f0e.png)

Information on the intended behaviour of the button:

![image](https://user-images.githubusercontent.com/1074786/113001662-52b72b80-9171-11eb-93af-148d6f8a8251.png)

Discord username (if different from GitHub): SjotgunSjonnie#9623

**Comment by hotshotp** [comment]
Yeah I think someone messed up the template when making the button animation for it, I made the sound a while ago just for the fun of it, not really functional yet

**Comment by davidwalschots** [comment]
I see. It should also be noted that pressing the HORN SHUTOFF button does indeed stop the alarm sound. However, it will also stop the alarm sound on consecutive presses of the COMMAND button (i.e. without pressing HORN SHUTOFF again). I doubt that is correct behaviour, but have no source to confirm this.

**Comment by ImenesFBW** [comment]
For now, we are missing a label for now only FAULT is there, the push-in behavior can be fixed with XML I'll look into it. Tarek did confirm that the button should be pushed in and should stay in when pushed.

![image](https://user-images.githubusercontent.com/71195324/113005760-07068100-9175-11eb-921a-428971532a58.png)

**Comment by 2hwk** [comment]
Updated issue description to match with current status as of 16/05/21
