### ISSUE TITLE
Weak Engines since the last Update

### ISSUE THREAD

**Issue by mart1n-toxit** [flybywiresim/a32nx#4206]
**Mod Version**

Experimental

**Describe the bug**

Engines are weaker since the last Update. If you fly a plane of 65 Tons, you cant reach FL310 in CLB Mode. With TOGA Thrust you can max reach FL310. The N1 Values seems to be correct (not sure) but the Engines doesnt generate enough Thrust.
As a result, it takes a long time to climb and you cant go higher than FL310.
And it looks like the plane uses way too much fuel.

**To Reproduce**

1. Start a Flight at a Gate (cold and dark)
2. Import Flightplan from Simbrief via FMC and Load Cargo and Fuel via FMC
3. Start the plane and try to fly the Flightplan

**Expected behavior**

It should be fixed

**Actual behavior**

Nothing

**References**

**Additional context**

Iam not sure if other people have the same problem

Was this working before/when did the issue start occurring?
Not sure - i think the whole time
Is this a problem in the vanilla unmodded game?
no

Discord username (if different from GitHub):
mart1n#6107

**Comment by dani143lund** [comment]
I had the exact same problem, my planned flight level was FL360 but I had to decrease my payload settings inflight and mantain FL300, as my engines didn't have the power to keep it up. Also when I was taxiing at ground I realized that I had to put more thrust to move the plane.

**Comment by Benjozork** [comment]
It would help if some video recording, actual data figures and such were provided.

**Comment by mart1n-toxit** [comment]
no problem, this clip shows how i try to climb but the plane cant hold the speed. The plane is at 64 tons.

[http://toxit.dyndns.org/engine.mp4](url)

**Comment by MisterChocker** [comment]
We do not support the legacy flight model, please switch to the modern flight model in your Microsoft flight simulator settings.

**Comment by mart1n-toxit** [comment]
> 
> 
> We do not support the legacy flight model, please switch to the modern flight model in your Microsoft flight simulator settings.

Iam not sure what do you mean with legacy or modern flight model

**Comment by mart1n-toxit** [comment]
OH ok, i switched to Modern now ... i didnt saw this yet.

AND now it seems to be fine!
Thank you really MUCH :D 
Guys, you are the best!

**Comment by MisterChocker** [comment]
Closing since issue resolved.
