### ISSUE TITLE
Units are not saved

### ISSUE THREAD

**Issue by Risechocolate** [flybywiresim/a32nx#4208]
{
  "built": "2021-03-30T11:29:16+00:00",
  "ref": "master",
  "sha": "0a4d6c3030a241da8dfa0dad541d78b386615e39",
  "actor": "davidwalschots",
  "event_name": "manual"
}

KG is changed to lbs in MCDU settings, but reverts back to KG after reboot.

1. Start with A32NX
2. Change WEIGHT UNIT from KG to lbs in MCDU options.
Quit the flight once and start up again with A32NX.
4. Change from lbs back to KG

Does not save when set to lbs
It is saved when I choose to restart.

Was this working before/when did the issue start occurring?
→From the previous version of FlybyWire Installer

Is this a problem in the vanilla unmodded game?
→Unmodified vanilla game.

Discord username (if different from GitHub):rise_chocolate#2757

**Comment by MisterChocker** [comment]
In order to safe the changes made in the options menu, you have to exit the simulator normally (returning to main menu -> click exit).

**Comment by MisterChocker** [comment]
Closing since no response from the op.
