### ISSUE TITLE
Autoland Pitch Down on Flare

### ISSUE THREAD

**Issue by hoodyFPS** [flybywiresim/a32nx#4209]
I've been trying to do some autolands in the A320 because the system has always fascinated me. I watched a few videos on how to set up the system correctly and when I did my first landing all was well. I had CAT3 landing displayed, the computer said LAND, then when it came to FLARE suddenly the nose pitched violently into the ground and slammed the aircraft into the runway at around 500fpm. I thought it was a one-off issue but sure enough, the same issue happened 5 more times. Is this a common issue? Did I configure something wrong? I'm at a loss for why this would be happening.

**Comment by Benjozork** [comment]
First, you didn't follow the template. Closing.

Second, are you sure you're using the experimental version ? Autoland is only available there.

Also, I suggest using Discord for that kind of question. GitHub is for formal documented bug reports.
