### ISSUE TITLE
[BUG] no electrical power from APU

### ISSUE THREAD

**Issue by A320pilotIRL** [flybywiresim/a32nx#421]
Started the APU only to find that once it said AVAIL on the button, no electrical power was coming from it.

So I had the APU running with zero electrical power to all 6 screens.... 

Used EXT power to power things up.... then when I turned off EXT power, things stayed on

**Comment by UncleClapton** [comment]
so the difference here is what can be powered by DC power and what can be powered by AC power. Could you please detail what you expect to turn on with DC and what you expect with AC? A reference on what powers what would be best for the programmers to implement correctly.

Do note that the entire electrical system is in a somewhat half working state, and a rework has been planned.

**Comment by AdenFlorian** [comment]
don't know whether the screens should work with only battery power, but I'm pretty sure they should work with once APU is avail, looking into it...

**Comment by A320pilotIRL** [comment]
I mean DC power definitely powers the DU's, otherwise how would one see the APU page on the lower ECAM when starting the APU from cold and dark? How else would the pilots see their primary instruments if AC power was lost in flight?  As far as which DU's, I'm looking into that right now. Trying to find it in a manual

**Comment by nabil74** [comment]
Same issue reported here
https://github.com/flybywiresim/a32nx/issues/434#issue-694217120

**Comment by AdenFlorian** [comment]
The problem is there is code in the APU js that slowly opens the flap, but theres other code that will auto switch to the DOOR page, causing the APU update code to no longer run, so the flap dont open and the apu never starts.

Will be working on a fix tonight.

**Comment by A320pilotIRL** [comment]
> The problem is there is code in the APU js that slowly opens the flap, but theres other code that will auto switch to the DOOR page, causing the APU update code to no longer run, so the flap dont open and the apu never starts.
> 
> 
> 
> Will be working on a fix tonight.
> 
> 
> 
> EDIT: The flap not opening isn't the problem, but there's code in the APU js that sets some vars related to APU GEN which will only happen if  the APU page is still selected.

I mean the APU starts fine, just isn't supplying AC power

**Comment by AdenFlorian** [comment]
Right, there's code in the js for the APU page that kind of makes it supply power to everything else.
