### ISSUE TITLE
Experimental: No change for STANDARD asked

### ISSUE THREAD

**Issue by phildeg31** [flybywiresim/a32nx#4219]
**Mod Version**
"built": "2021-03-31T15:16:20+00:00",
  "ref": "autopilot",

**Describe the bug**
Change for STANDARD must be asked at transition altitude but the QNH does not flash on PFD when transition altitude has been reached (meaning that I have to change for STANDARD).

**To Reproduce**
Set transition altitude to 5000ft for example in take-off page of the MCDU.
After take-off, when transition altitude has been reached, see QNH value on PFD.

**Expected behavior**
The QNH should flash on PFD meaning that I have to change for STANDARD.

**Actual behavior**
It does not flash.

**References**

**Comment by DanP77** [comment]
Confirmed behavior also at the TL in descent.

**Comment by AirbusA320Pro** [comment]
Logic being addressed in bug report #3992

**Comment by phildeg31** [comment]
Thank you. That is good to have real pilots helping for the mod ;).

**Comment by aguther** [comment]
Implemented in development version.
