### ISSUE TITLE
FIX SUGGESTION - FMA AFTER TAKEOFF

### ISSUE THREAD

**Issue by A320pilotIRL** [flybywiresim/a32nx#422]
After some testing I finally have discovered what's been bugging me on takeoffs.

I reproduced the issue several times in the simulator, and I compared it to an A320 simulation software my company provided me.

I discovered that in the initial climb, as soon as you bring the thrust levers back to the climb position, there are two incorrect things happening. First, the managed speed target is not changing to climb speed, which typically would be 250, Until the flaps are retracted. This should not happen. As soon as the aircraft enters THR CLB, CLB, The speed target should move to 250. This will allow the airplane to accelerate and retract flaps. The A320NX Is incorrectly managing a speed of 180 knots, and only increasing the speed target when flap retraction occurs. 

The other more serious issue I noted, Was that THR CLB was REDUCING THRUST to maintain this 180kts, which is a big problem, as THR CLB is a fixed – thrust mode, and should remain at full climb thrust. It is behaving like SPEED mode. 

If you can fix these two problems together, the take offs will perfectly mimic the real airplane

**Comment by Benjozork** [comment]
Please do not ignore issue templates. They are here for a reason.

**Comment by A320pilotIRL** [comment]
It's not an issue so I didn't use an issue template

**Comment by Curtis-VL** [comment]
Are you sure you have an acceleration altitude set in the MCDU to switch to the CLB phase of the flight from TAKEOFF? This will remove SRS/RWY and change the speeds.

The other issues aren't FMA issues, they're Asobo autopilot code issues. Asobo plans to update the autopilot code, but, we're trying to look into what we're allowed to edit in the meantime! 👍

**Comment by A320pilotIRL** [comment]
Yes this is with acceleration and thrust reduction altitudes set properly

**Comment by Curtis-VL** [comment]
Ah, right, these may well just be Asobo autopilot issues then in that case! We're always looking into ways to improve this, but can't guarantee it'll be possible without Asobo improving the situation on their end. :)
