### ISSUE TITLE
Experimental: Altitude during cruise not match with reality

### ISSUE THREAD

**Issue by alfalfasecas** [flybywiresim/a32nx#4222]
**Mod Version**

Experimental f1f64d3

**Describe the bug**

During cruise phase, with the altimeter in STD, the altitude of the plane does not match with the real one. If you choose FL350, the plane of the sim mantains FL350, but if you check the current altitude on IVAO, VATSIM, ProjectFly, Simtoolkitpro, etc... it says that you are above FL350. This bug makes not possible to fly on this kind of online networks on which ATC slots you an specific FL.

**To Reproduce**

1. Prepare a fly between 2 airports
2. Fulfill the MCDU. Fly up to cruise altitude. Put the altimeter in STD above TRA
3. Check the altitude of the simulator with the altitude on IVAO, ProjectFly, VATSIM, Simtoolkitpro...

**Expected behavior**

FL of the simulator should be the same as on the other programs/networks

**Actual behavior**

The FL on the simulator doesn't match with the real FL detected by that stuffs

**References**

![imagen](https://user-images.githubusercontent.com/70801345/113268666-e9056180-92d7-11eb-9718-8385a480341e.png)
![imagen](https://user-images.githubusercontent.com/70801345/113268414-a2176c00-92d7-11eb-830a-3f079d86ace0.png)
![imagen](https://user-images.githubusercontent.com/70801345/113268562-cc692980-92d7-11eb-9748-4701c81be840.png)

**Additional context**

Was this working before/when did the issue start occurring? 
It worked before. The issue started with the last experimental update (dated on 03/26/21)

Is this a problem in the vanilla unmodded game? 
I don't know

Discord username (if different from GitHub):

**Comment by ChruutvoLuzi** [comment]
STD is just a way to unify all Aircrafts flying above Transition Altitude. so you dont have to adjust the qnh all the time while in cruise. While your Altimeter gets set to the 1013/29.92 the outside Pressure still varies from place to place and naturally, is above or below the true height depending on the outside pressure

**Comment by MisterChocker** [comment]
Altitude pressure currently isn't simulated by the sim correctly, nothing we can do about.

**Comment by aguther** [comment]
I say it's even not a bug. Real planes do not fly with GPS altitude either, as said before they fly on a certain flight level which is by definition pressure altitude which is the altitude with a given pressure. Pressure altitude can be measured by setting the altimeter to STD / 29.92". Even when MS will implement pressure altitude correctly, the plane will be off. By way: this will happen to more planes then.
