### ISSUE TITLE
cockpit display not working

### ISSUE THREAD

**Issue by mahmod67** [flybywiresim/a32nx#4225]
**Mod Version**

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by mahmod67** [comment]
just updated 320 development and now the cockpit displays are off

**Comment by Awemeter** [comment]
you need to fill out the template

**Comment by Awemeter** [comment]
> just updated 320 development and now the cockpit displays are off

could be a mod conflict

**Comment by mahmod67** [comment]
what tamplate

**Comment by mahmod67** [comment]
any solution

**Comment by mahmod67** [comment]
hello

**Comment by Awemeter** [comment]
> what tamplate

when you make the issue you need to fill it out

**Comment by mahmod67** [comment]
fill out where

**Comment by Awemeter** [comment]
> hello

are you in the discord server if so just got to #help it will be way easier

**Comment by mahmod67** [comment]
ok sir thank you
i will delete and install again
thank you

**Comment by Awemeter** [comment]
> ok sir thank you
> i will delete and install again
> thank you

you should move take out all other mods that are not a32nx from the community folder and then try

**Comment by mahmod67** [comment]
now its not downloading 
downloading module 0%
what is wrong

**Comment by BritishAvgeek** [comment]
![image](https://user-images.githubusercontent.com/71381591/113283607-6634d480-92e0-11eb-973c-84c38fb73a6f.png)

**Comment by Maximilian-Reuter** [comment]
> now its not downloading
> downloading module 0%
> what is wrong

Move to discord and continue there, this is not the right place for help.
This should be closed!

**Comment by Valastiri** [comment]
BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning

Please follow the template next time or join the discord for support.
