### ISSUE TITLE
When loading the A32NX custom, it suddenly becomes an Avro RJ

### ISSUE THREAD

**Issue by Watsi01** [flybywiresim/a32nx#4226]
**Mod Version**
Latest experimental version

**Describe the bug**
When loading the A32NX custom, it suddenly becomes an Avro Regional Jet.

**To Reproduce**

1. Install the A32NX custom
2. Spawn at EDDH on the runway
3. Check outside view

**Expected behavior**
Should be an A320Neo

**Actual behavior**
Is an Avro

**References**

![14202-bae146hxzip-2-bae-hx](https://user-images.githubusercontent.com/72334392/113295050-fb8f9300-92f7-11eb-99d9-3e0da1fbd78d.jpg)

**Additional context**
It's only happening in Hamburg.

Is this a problem in the vanilla unmodded game?
No.

Discord username (if different from GitHub):

**BY NOT REMOVING THIS LINE, I ATTEST THAT I WAS DRUNK AND ALSO WASN'T ABLE TO SEE MY HANDS ANYMORE**

**Comment by Paytheon** [comment]
Well? Did you fly it? I would have jumped in the Captain's chair on that puppy!

**Comment by scoopscode** [comment]
Have you tried putting it and rice? 😂

**Comment by ImenesFBW** [comment]
This is a known issue!

**Comment by ko-zone** [comment]
I've been having this bug very frequently now..

**Comment by Lantarius** [comment]
**Weird for me it looks like this though**
![image](https://user-images.githubusercontent.com/64409640/113303073-61d0e180-9309-11eb-9fda-01a23c1c24de.png)

**Comment by Benjozork** [comment]
Not an issue! Why would anyone **NOT** want that beautiful plane? Closing, blasphemy!
