### ISSUE TITLE
VOR and ADF needles are  not displayed on ND in NAV and ARC mode

### ISSUE THREAD

**Issue by gillesvana** [flybywiresim/a32nx#4228]
Hi, normally these needles should appear in all modes, including ARC and NAV. only ILS and VOR mode display them today. it would be a plus to have them.
thank you for your work and good luck

**Mod Version**

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by scoopscode** [comment]
Hello, it looks as if you didn't follow the format that is needed for the issue. Please reopen a new request with all the requirements, thanks!
