### ISSUE TITLE
VOR and ADF needles

### ISSUE THREAD

**Issue by gillesvana** [flybywiresim/a32nx#4229]
**Mod Version**

Custom FBW and all ather DEV
c5daad1

**Describe the bug**

Hi, normally these needles should appear in all modes, including ARC and NAV. only ILS and VOR mode display them today. it would be a plus to have them.
thank you for your work and good luck

**To Reproduce**

1.normal use... adjust ADF and VOR frequency  near your position
2.Set the switches ADF1 - VOR1  as ADF1    and ADF2 VOR 2  as VOR2 
3. in flight look the ND in NAV and ARC mode... no needle displayed

**Expected behavior**

these needles are displayed in ILS, VOR,NAV and ARC

**Actual behavior**

no display in ARC and NAV mode

**References**

**Additional context**

Was this working before/when did the issue start occurring?
no never since beguin 

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment]
Since #3886 VOR and ADF needles are already added to the ND on ARC mode.

**Comment by gillesvana** [comment]
HI, thank for this good job.
but i just tested id, it's ok Merge branch Master for VOR, NAV et ARC... but the needles don't appears now on this release.
normaly needles are presents on all mode.
best regards

**Comment by gillesvana** [comment]
sorry , HI, thank for this good job.
but i just tested id, it's ok Merge branch Master for VOR, NAV et ARC... but the needles don't appears now on this release **### in ILS mode.**
normaly needles are presents on all  4 modes.
best regards

**Comment by antoineva33** [comment]
@MisterChocker  regarding this (real) video, needles (vor and adf) are to be displayed in ils mode too.
