### ISSUE TITLE
Manual heading won't arm and FMA is doesn't display any information. Custom AP.

### ISSUE THREAD

**Issue by InhumanReactions** [flybywiresim/a32nx#4231]
**Mod Version**
 Experimental from the installer. 
 Experimental build 223ebc1 

**Describe the bug**
Even after turning on the Flight Directors, I couldn't set the heading knob to NAV. I tried many times, but it remained on the selected heading. Speed was working fine, but I believe altitude was also not working. After pushback, I tested my flight controls, however there was no indication of movement on the PFD, even though the ailerons were physically moving. The QNH dial worked. The main PFD and FMA were the issue. 

**To Reproduce**

1. Spawned at LFSB, stand 20. FSDT scenery, if that is relevant.
2. Used simbrief to import this flight plan (TORP7N TORPA UT10 RLP UL613 SOVAT L613 SANDY UN57 WELIN T420 TNT DAYN2A). 
3. Set takeoff performance in the MCDU, turned on the Flight Directors, and armed the speed. The altitude and heading remained on selected. 
4. Turned on the engines and tested the flight controls.

**Expected behavior**
I expected the heading to switch to NAV, the altitude to be armed, the FMA to reflect these, and the PFD to display flight control imput. 

**Actual behavior**
The altitude and heading didn't arm. The FMA didn't show anything aside from 1 FD 2. The PFD didn't show any movement even though the ailerons and flight controls were fully working.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
 I did a flight on the previous build a few hours ago. It all worked fine. The issue began once I began this flight.

Is this a problem in the vanilla unmodded game?
This has never happened on any branch I have used before.

Discord username (if different from GitHub): InhumanReactions #9858

**Comment by aguther** [comment]
Please update you version. There was an issue with the wasm completely missing. The issue you are describing with the flight controls tells me that the input events have not been masked (that's why they worked). But the display in the PFD are driven by a local variable that is only written by the wasm code. So if that's not there nothing works, also no FMA etc.

I close the bug, feel free to reopen if problem persists after update.
