### ISSUE TITLE
Both Nav Lights appear RED from above

### ISSUE THREAD

**Issue by gkkes** [flybywiresim/a32nx#4233]
**Mod Version**

Experimental d909f0f

**Describe the bug**

Viewed from above at night the aircraft appears to have both NAV lights as red.

**To Reproduce**

1. Turn on NAV lights
2. Set darkness hours
3. Set view above

**Expected behavior**

I imagine right wing should glow green?

**Actual behavior**

Both wings have a cast Red glow

**References**

![navlights](https://user-images.githubusercontent.com/16132247/113382588-c461c600-9379-11eb-9f73-34343ba72609.png)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by tracernz** [comment]
That's the beacon flash...

**Comment by tracernz** [comment]
![image](https://user-images.githubusercontent.com/9995998/113385145-045d9300-93e4-11eb-80eb-4db6a1ee9031.png)
![image](https://user-images.githubusercontent.com/9995998/113385153-09224700-93e4-11eb-8259-ffe080fbbbec.png)
