### ISSUE TITLE
Both engines down during the flight.

### ISSUE THREAD

**Issue by yoshi-mu** [flybywiresim/a32nx#4235]
**Mod Version**
{
  "built": "2021-04-01T23:12:53+00:00",
  "ref": "master",
  "sha": "198b1c664ec86db524b2eb374f831e987cf9bccf",
  "actor": "wpine215",
  "event_name": "manual"
}

**Describe the bug**

Every time in my flight, at first, No.1 engine goes down at the middle or final phase of flight. Then, No.2 also goes down and all display out.
So I can't reach the destination.

**Comment by Benjozork** [comment]
Template not followed
