### ISSUE TITLE
EFOB and FUEL PRED get dashed out at TOD

### ISSUE THREAD

**Issue by ExampleWasTaken** [flybywiresim/a32nx#4236]
**Mod Version**

master
build_info:
```json
{
  "built": "2021-04-01T23:12:53+00:00",
  "ref": "master",
  "sha": "198b1c664ec86db524b2eb374f831e987cf9bccf",
  "actor": "wpine215",
  "event_name": "manual"
}
```

**Describe the bug**

At around 70nm remaining to destination the EFOB on the F-PLN page, as well as the entire FUEL PRED page get dashed out.

**To Reproduce**

1. Loaded C&D
2. Complete MCDU setup (DIFSRIP)
3. Perform normal flight
4. Observe EFOB on F-PLN page and FUEL PRED 

**Expected behavior**

Neither the EFOB on the F-PLN nor the FUEL PRED page should be dashed out at 70nm after correctly setting up the MCDU pre-engine start.

**Actual behavior**

EFOB on the F-PLN page and FUEL PRED page get dashed out at around 70nm to go.

**References**

![Microsoft Flight Simulator Screenshot 2021 04 02 - 21 34 44 72](https://user-images.githubusercontent.com/58574351/113448019-5231c580-93fb-11eb-8b73-a40ddaa6ab21.png)

**Additional context**

The screenshot is taken after landing but is an exact representation of what the page looked like inflight.

Was this working before/when did the issue start occurring?
I can't say when the issue started occurring but it used to work. 

Is this a problem in the vanilla unmodded game?
Probably not, as it used to work as expected.

Discord username (if different from GitHub): ExampleWasTaken#0886

**Comment by airfirefighter** [comment]
for me this happening every time i starting descent.

**Comment by ExampleWasTaken** [comment]
> 
> 
> for me this happening every time i starting descent.

Yes maybe that's the point at which is it happening. Gonna test that if I find time.

**Comment by ExampleWasTaken** [comment]
> 
> 
> for me this happening every time i starting descent.

Can confirm

**Comment by erso44** [comment]
Invastigating.
