### ISSUE TITLE
CTD after some minutes into flight

### ISSUE THREAD

**Issue by gabrik** [flybywiresim/a32nx#4237]
**Mod Version**
Experimental

**Describe the bug**
Some minutes after take-off the sim crashes to desktop.
Actually first all screen becomes black, like the video driver crashes, then the sim dies.

**To Reproduce**
1. Start a new flight with A32NX
2. Do some flight prep
3. take off

**Expected behavior**
Should not crash

**Actual behavior**
Crashes

**References**
Report from windows event viewer:

```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2021-04-02T20:44:18.0813196Z" /> 
  <EventRecordID>56303</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>Tano-W10</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>FlightSimulator.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>60420f33</Data> 
  <Data>VCRUNTIME140.dll</Data> 
  <Data>14.28.29231.0</Data> 
  <Data>5f4c66c9</Data> 
  <Data>c0000005</Data> 
  <Data>00000000000014b4</Data> 
  <Data>3244</Data> 
  <Data>01d727fb27c5b59f</Data> 
  <Data>C:\Program Files\WindowsApps\Microsoft.FlightSimulator_1.14.6.0_x64__8wekyb3d8bbwe\FlightSimulator.exe</Data> 
  <Data>C:\Program Files\WindowsApps\Microsoft.VCLibs.140.00.UWPDesktop_14.0.29231.0_x64__8wekyb3d8bbwe\VCRUNTIME140.dll</Data> 
  <Data>7b8cb95e-9431-4335-87cf-a5ec058c82a6</Data> 
  <Data>Microsoft.FlightSimulator_1.14.6.0_x64__8wekyb3d8bbwe</Data> 
  <Data>App</Data> 
  </EventData>
  </Event>
```

**Additional context**
I had some recent issue with NVidia Drivers with the IVAO client, here my setup:
AMD 3900X
64GB DDR4 3200Mhz
RTX3070 FE
Windows 10 20H2
NVidia Drivers: 465.89 (with Resizable BAR enabled, cannot go back to older drivers)
Latest MSFS2020 (Game Pass edition)
Gear: TCA Officer Pack (Stick + Throttle quadrant) 

Was this working before/when did the issue start occurring?
With older version of the driver everything was working fine, but I did't had the new experimental version, just the Custom FBW one.

Is this a problem in the vanilla unmodded game?
Not 100% have to remove A32NX and test it

Please let me know if you need more informations

**Comment by Benjozork** [comment]
This is unlikely to be related to the A32NX. Many people are reporting crashes with newer Nvidia drivers.

**Comment by gabrik** [comment]
Then I'll just close this, thanks for the prompt response
