### ISSUE TITLE
Missing Callout

### ISSUE THREAD

**Issue by DanP77** [flybywiresim/a32nx#4238]
**Mod Version**
Experimental

**Describe the bug**
Recently the experimental no more has callout
"Hundred Above"
"Minima"

**To Reproduce**
1. Set the Minima in MCDU
2. Perform an instrumental approach
3. wait for the callout

**Expected behavior**
All callout executed

**Actual behavior**
Missing callout

**References**
-

**Additional context**
-

Was this working before/when did the issue start occurring?
About latest week

Is this a problem in the vanilla unmodded game?
IDK

**Comment by youngryan7** [comment]
also no RETARD callout

**Comment by FRYYYYYY** [comment]
For me it's working. Can you please post your starting airport and steps to reproduce?

**Comment by DanP77** [comment]
Todays flight was ok. I will check again in next flights
