### ISSUE TITLE
FlyPad change view and turn on ext lights.

### ISSUE THREAD

**Issue by carlospm63** [flybywiresim/a32nx#4239]
**Mod Version**

Development 198b1c6

**Describe the bug**

When I type my SimBrief username on the Flypad all the exterior lights turn on and the view of the Flypad is removed

**To Reproduce**

1. Bat 1&2 on
2. Flypad on
3. Type my SimBrief username in the Flypad
4. All exterior light turn on and the Flypad view change.

**Expected behavior**

That the view of the Flypad does not move when type the SimBrief username and the lights do not turn on by themselves.

**Actual behavior**

When you type a few characters in the SimBrief username field, the view of the Flypad disappears because it moves to another angle and all the exterior lights turn on by themselves.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
It happens in the latest versions. I could not specify it but at least in the last five or six
Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):
carlospe63#3035

https://user-images.githubusercontent.com/74715619/113463601-0f85e280-9427-11eb-9e01-f8863c2e73cb.mp4

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by FRYYYYYY** [comment]
Currently it works as designed. With typing in your username you are also using the keyboard bindings. 

As a workaround please copy your username within windows and paste it to EFB.

**Comment by scoopscode** [comment]
Hey, so about this. It happens to everyone who does this because FBW hasn't implemented the a in-screen keyboard or a focused keyboard into the EFB. At this point, you'll have to keep going with this until FBW has added that.

**Comment by carlospm63** [comment]
Hi,

Thank you very much for the reply and thank you very much for your great
work.  I will try to help where possible.

Kind Regards.
Carlos Perez.

**Comment by carlospm63** [comment]
Thank you very much. You do an excellent job.

Kind Regards.
Carlos Perez.

**Comment by carlospm63** [comment]
Thank you for your effort and you can count on me if I can help you with something within my limited possibilities.

**Comment by FRYYYYYY** [comment]
> Thank you for your effort and you can count on me if I can help you with something within my limited possibilities.

Same for me.... I got the hint with copy&paste from the issue section 😬😊

**Comment by carlospm63** [comment]
👍😏

**Comment by Kacper848** [comment]
You can also use click ALTGR while hovering your mouse over the EFB. This will pop it out into a new window, where you can normally type without it being recognised as simulator shortcuts.

**Comment by carlospm63** [comment]
OK, thanks a lot. I will do that.

Regards.
Carlos Perez.
