### ISSUE TITLE
[BUG] Accu/brake press gauge illuminated when cold & dark

### ISSUE THREAD

**Issue by veikkos** [flybywiresim/a32nx#424]
**Branch**
master

**Describe the bug**
Accu/brake press gauge is illuminated when cold & dark.

**To Reproduce**
1. Go to gate/park at night, cold & dark

**Expected behavior**
Cockpit should be completely dark when no power is on.

**Screenshots or Videos**
![kuva](https://user-images.githubusercontent.com/24453333/92312821-48fb8a00-efcd-11ea-893d-a7faaeb7a948.png)
![kuva](https://user-images.githubusercontent.com/24453333/92312798-0a65cf80-efcd-11ea-87b4-98d3146e3774.png)

**Additional context**
-

**Comment by UncleClapton** [comment]
This was originally deemed intentional but since we know the electricity state we could probably tie the brightness to that.

**Comment by veikkos** [comment]
> This was originally deemed intentional but since we know the electricity state we could probably tie the brightness to that.

Yea, indeed, that's what I'd expect 👍
