### ISSUE TITLE
Can't arm spoilers

### ISSUE THREAD

**Issue by billyinlasvegas** [flybywiresim/a32nx#4240]
**Mod Version**

Experimental 5528278

**Describe the bug**

Cannot arm the spoilers

**To Reproduce**

1. Try to arm spoilers by pulling with mouse or with keyboard shortcut
2.
3.

**Expected behavior**

Spoilers should have armed and it should clear from takeoff and landing ecam checklist 

**Actual behavior**

Nothing happens, handle returns to previous position

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Worked fine with previous versions

Is this a problem in the vanilla unmodded game?
no

Discord username (if different from GitHub): billyinlasvegas

**Comment by FRYYYYYY** [comment]
Please try to reset your control settings (keyboard or other hardware) and try again. I had something similar and this was related to a misconfiguration.

**Comment by jetstream2x4** [comment]
Same issue for me, but the interesting issue is:
1. Armed spoilers via mouse pull
2. The spoiler slided up but immediately slid back to spoilers armed off/ retracted position. 
3. Yet the EWD indicated: Spoilers armed...

May be a bug in visualisation?

**Comment by FRYYYYYY** [comment]
> Same issue for me, but the interesting issue is:
> 
> 1. Armed spoilers via mouse pull
> 
> 2. The spoiler slided up but immediately slid back to spoilers armed off/ retracted position. 
> 
> 3. Yet the EWD indicated: Spoilers armed...
> 
> 
> 
> May be a bug in visualisation?

Do you have any hardware which is able to retract the spoilers? Please check every control which is plugged in. In past the problem was a misconfiguration of the TCA quadrant.

**Comment by MisterChocker** [comment]
This maybe an issue until https://github.com/flybywiresim/a32nx/pull/4220 has been integrated.
I'll try to come back with an answer soon.

**Comment by aguther** [comment]
What events / keys did you use?

**Comment by jetstream2x4** [comment]
Howdy Mr. Guther ... 

I used TCA throttle quadrant for inputs ... Anyway, I did a full reinstall of the fbw when catching up that the bird has now a seperate model and initially changed to Developers Version without custom fbw ... This solved my issues ... :-) Thanks for the assistance :-)

**Comment by aguther** [comment]
Great!
