### ISSUE TITLE
Transponder and Rudder display brightness

### ISSUE THREAD

**Issue by gkkes** [flybywiresim/a32nx#4241]
**Is your feature request related to a problem? Please describe.**

In ambient light, it is difficult to read the displays in both the Transponder and Rudder Trim displays.

**Describe the feature you'd like to see implemented**

I would expect the intensity to vary with the setting of the INTEG LT potentiometer on the pedestal. Is this possible?

**References**

AirbusA320Pro "The pedestal backlight illumination is controlled as @gkkes suggests. That's how the real aircraft works IRL".

**Additional context**

Evidence of lower illumination are evident here between the radio brightness and the TX and Rudder Trim intensity.
![txlevel](https://user-images.githubusercontent.com/16132247/113469553-47505280-9446-11eb-9572-e41ecda6e365.png)

Discord username (if different from GitHub): gkkes#1982

**Comment by Watsi01** [comment]
Yes, and also the main clock.
