### ISSUE TITLE
Throttle gets stuck (Custom AP)

### ISSUE THREAD

**Issue by InhumanReactions** [flybywiresim/a32nx#4243]
**Mod Version**
Experimental
Version from installer, before the latest rebase

**Describe the bug**
After a FLX+29 take-off at LFSB, I was unable to move the throttle axis. It registered movement in the EFB and I re-binded my settings, but this didn't work.

**To Reproduce**

1. Spawn C&D at LFSB, gate 20.
2. Start up the aircraft, set FLX+29 and taxi to runway 33.
3. Take-off with the FLX detent.

**Expected behavior**

I expected to be able to retract the throttle into the CLB detent, and have full control of the throttle levers.

**Actual behavior**

I was unable to retract the throttle, or even move it at all. I shut down both engines, disabled AP and tried to turn off the A/THR, but this didn't work due to the position of the throttle.

**References**

![FlightSimulator_69gZRKyspe](https://user-images.githubusercontent.com/73650962/113474911-a031e200-946a-11eb-90b2-52ff8466662f.png)

**Additional context**

Was this working before/when did the issue start occurring?

This is the first time I've experienced this issue.
Is this a problem in the vanilla unmodded game?

It hasn't happened on any branch or flight before.

Discord username (if different from GitHub): InhumanReactions #9858

**Comment by Matthew-Christopher** [comment]
I can also confirm this in the experimental build, it happended with a TOGA and FLEX departure.

**Comment by jetstream2x4** [comment]
Same issue for me in the current experimental version

**Comment by aguther** [comment]
Can you please redownload? There was a small window where there was a bug.

**Comment by InhumanReactions** [comment]
Okay, I'll redownload now to use later. Is the branch hardforked yet, or can I still use my liveries? Thanks for the response :)

**Comment by jetstream2x4** [comment]
Thanks for the help, Sir ... I did a full reinstall for the FBW A320. This cleared the issue with the spoilers ... So my Issue can be considered as solved.
