### ISSUE TITLE
Invisible aircraft, no default livery after installing 3a6f05b development branch

### ISSUE THREAD

**Issue by brion** [flybywiresim/a32nx#4250]
**Mod Version**

dev version from installer
```json
{
  "built": "2021-04-03T11:17:53+00:00",
  "ref": "master",
  "sha": "3a6f05bfcfdf9d5560aa9d4eeb2df848bc191c4e",
  "actor": "wpine215",
  "event_name": "manual"
}
```

**Describe the bug**

No icon in aircraft selector, no liveries available (not even a default), and the aircraft is invisible in both cockpit and external view after spawning.

**To Reproduce**

1. Switch from release to 3a6f05b development branch with installer
2. Launch MSFS
3. Select FlyByWire A32NX
4. See there's no icon in the aircraft selector (in some menus it shows the previously selected aircraft's icon)
5. See there's no liveries
6. Spawn at an airport (tried KSAN, runway 9)
7. Look and see there's no instrument panel, cockpit, or any other models in the aircraft interior
8. Go to external view and see there's no aircraft model

**Expected behavior**

Aircraft should have an icon in the aircraft selector, at least one default livery, and should have a visible cockpit/instrument panel and exterior model.

**Actual behavior**

Aircraft does not have an icon in the aircraft selector, has no liveries, and does not have a visible cockpit/instrument panel or exterior model.

**References**

![Microsoft Flight Simulator Screenshot 2021 04 03 - 07 42 17 45](https://user-images.githubusercontent.com/103075/113482106-ee86b700-9451-11eb-8de2-9dc979bfdaf2.jpg)
![Microsoft Flight Simulator Screenshot 2021 04 03 - 07 42 14 23](https://user-images.githubusercontent.com/103075/113482112-f21a3e00-9451-11eb-9186-39b650cd2647.jpg)

**Additional context**

Was this working before/when did the issue start occurring?

This was shortly after the announcement of the change to the new separate aircraft entry.

Is this a problem in the vanilla unmodded game?

The FlyByWire aircraft does not exist in the unmodded game. The unmodded Airbus does not have this problem.

Discord username (if different from GitHub):

**Comment by brion** [comment]
On the suggestion of an MSFS forum user, I tried moving the entire `flybywire-aircraft-a320-neo` mod folder out of `Community` and reinstalling fresh.

I notice that the folders are very different!

The old folder, where I used the installer to switch branches, contains two separate aircraft in the `SimObjects\AirPlanes` directory.

The new folder, where I used the installer to install a new branch fresh, contains only one, the new `FlyByWire_A320_NEO` entry.

When it finishes loading, we'll see if the FBW version works...

It does seem the installer is failing to remove old files, though. Does that matter? No idea yet.

**Comment by brion** [comment]
Aircraft selector works on fresh run of MSFS after having done a complete reinstall of the FBW mod. I now see two liveries. So far so good.

**Comment by brion** [comment]
Ok, fresh install of mod works. So it may be that the installer is failing to clean up the old directories when switching branches, and the additional files are causing weird failures in the sim?

**Comment by BjoernHund** [comment]
@brion 
The devs are already working on this issue. There is a release candidate for the installer with the fix already made.

**Comment by DaviSouzaR** [comment]
Switch inop, no EFB, whats happened?

**Comment by brion** [comment]
Thanks @BjoernHund!

**Comment by brion** [comment]
I'll go ahead and close this out (as technically it belongs on the updater, and the release candidate should resolve this)

**Comment by BjoernHund** [comment]
@brion The new installer is out now. If you start your installer it should autmatic update. Wait until finished. The new version should be 1.1.4

**Comment by thegeorges** [comment]
I have the same problem after installing the stable v0.7.0. Removed old flybywire-aircraft-a320-neo folder from the community folder, but ended up with no aircraft showing - cockpit and external view.
