### ISSUE TITLE
MCDU Going To Climb Page When Spawning On Runway

### ISSUE THREAD

**Issue by h20genie** [flybywiresim/a32nx#4251]
**Mod Version**
Custom Auto Pilot

**Describe the bug**
When spawning on the runway with a FLT or PLN file, the MCDU Perf Page will skip to CLB page. Hitting escape and restarting the flight seems to fix the issue as a work around. 

**To Reproduce**

1. Load a flight with either a PLN or FLT file and spawn on the runway
2. Press the Perf button on the MCDU
3. Observe if it goes to the CLB page instead of the Take Off Page

**Expected behavior**

When spawning on a runway when loading a PLN or FLT file, pressing the PERF button on MCDU should load the Take Off page and not the Climb Page.

**Actual behavior**

MCDU Perf button loads the CLB page when spawning on a runway when using a CLB or FLT file instead of the Take Off page.

**References**

**Additional context**

Was this working before/when did the issue start occurring?

This was working before the Custom AP branch had changed to flight phases. 

Is this a problem in the vanilla unmodded game?

No game is not modded. 

Build.json contet:

{
  "built": "2021-04-03T22:55:05+00:00",
  "ref": "autopilot",
  "sha": "633909760b507af5ff8885cad490e4ba1c81d1a1",
  "actor": "aguther",
  "event_name": "manual"
}

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by MisterChocker** [comment]
Please post the content of the build_info.json

and

> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning
