### ISSUE TITLE
Plane turned default after last update?

### ISSUE THREAD

**Issue by DaviSouzaR** [flybywiresim/a32nx#4253]
![Sem título-1](https://user-images.githubusercontent.com/81820315/113486062-44298680-9487-11eb-89c7-56a4e4c82c31.jpg)

**Mod Version**

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Matthew-Christopher** [comment]
The development an dexperimental brancheshas been forked from the Asobo aircraft so you should now select the FlyByWire (LEAP) aircraft and not the default (Asobo) A320.

**Comment by DaviSouzaR** [comment]
Thank you!

**Comment by gilcon2** [comment]
Same issue.  Just updated the Development version (3a6f05b) with the installer and now goes to default 320.  Was working fine before.

**Comment by Matthew-Christopher** [comment]
> 
> 
> Same issue. Just updated the Development version ([3a6f05b](https://github.com/flybywiresim/a32nx/commit/3a6f05bfcfdf9d5560aa9d4eeb2df848bc191c4e)) with the installer and now goes to default 320. Was working fine before.

Please see my above comment and failing that remove the aircraft from your community folder and reinstall again, ensuring that you select the correct aircraft in the main menu.

**Comment by Benjozork** [comment]
@gilcon2 read the above solutions
