### ISSUE TITLE
AP/Plane waypoint in the wrong position when going direct to. 

### ISSUE THREAD

**Issue by ninoz** [flybywiresim/a32nx#4254]
**Mod Version**
Experimental - a56c2ed

**Describe the bug**
When setting an approach within the MCDU the flightplan for some reasons doubles back on itself to the previous waypoint.  Setting the MCDU to go direct to the first approach waypoint doesn't work as for some reason it thinks the previous waypoint is the correct location.  This is explained better below:

**To Reproduce**
Start a flight from the main menu and set EGKK and Gate 106 as the departure, do not set a destination.

Spawn in and setup as normally, fill the to/from in the MCDU  (EGKK/EBBR)
![image](https://user-images.githubusercontent.com/1727961/113488250-b2387280-94b4-11eb-87be-dd230bec77f1.png)
Request IFR clearance and then set the departure runway etc as instructed by ATC
![image](https://user-images.githubusercontent.com/1727961/113488020-5a4d3c00-94b3-11eb-9ad8-96dc2f2da7c9.png)
The resulting flight plan looks correct:
![image](https://user-images.githubusercontent.com/1727961/113488029-65a06780-94b3-11eb-8bc4-3be4a4d967e3.png)
Take off and fly the route, not there is a bug in the vanilla game which makes you refile your IFR shortly after  take off.
![image](https://user-images.githubusercontent.com/1727961/113488036-781aa100-94b3-11eb-8c0a-956b596c9b74.png)
When you are close to EBBR the ATC will give you approach instructions
![image](https://user-images.githubusercontent.com/1727961/113488059-a8fad600-94b3-11eb-9e65-735e72f5a3d2.png)
Load these into the MCDU
![image](https://user-images.githubusercontent.com/1727961/113488070-b44e0180-94b3-11eb-97d2-bd57ecd96956.png)
Notice the flight plan has updated, whilst the PDF says the next waypoint is FLO and the AP brings us back to the previous WIZAD waypoint:
![image](https://user-images.githubusercontent.com/1727961/113488094-da73a180-94b3-11eb-8454-e5a5ec8db736.png)
![image](https://user-images.githubusercontent.com/1727961/113488090-d3e52a00-94b3-11eb-9c74-c42efb7fbd30.png)
When arriving at WIZAD the ND shows:
![image](https://user-images.githubusercontent.com/1727961/113488104-e8292700-94b3-11eb-8757-b954f04e9c3e.png)
![image](https://user-images.githubusercontent.com/1727961/113488106-ea8b8100-94b3-11eb-9a38-28d4adc5ee61.png)
The waypoint then updates the distance to the correct FLO once you get to WIZAD
![image](https://user-images.githubusercontent.com/1727961/113488123-f9723380-94b3-11eb-9d62-a604c2072555.png)
The flight then continues as normal, below is documented the vanilla issue.

I suspect the issue of going to the previous waypoint is a MSF2020 issues, however the mod does seem to break the DIR TO function 

**Expected behavior**

Within the vanilla A320 the same actions were taken, upon entering the approach data the flight plan does get confused:
![image](https://user-images.githubusercontent.com/1727961/113488164-38a08480-94b4-11eb-9542-5bc3a72d722c.png)
However when setting DIR TO FLO the plan updates and the flight plan updates:
![image](https://user-images.githubusercontent.com/1727961/113488310-2bd06080-94b5-11eb-9c1e-47912b0b1614.png)

**Actual behavior**
As above

**References**
As above

**Additional context**
No mods installed, just the FBWa32nx

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

**Comment by aguther** [comment]
Unfortunately the source for NAV is still the default FPM will all it's glory.

**Comment by ninoz** [comment]
I tried this again using the latest version and the DIR TO function worked, the issue for the flight plan being messed up when adding the approach is an ASBO issue so I’ll close this :)

thanks
