### ISSUE TITLE
Livery and Aircraft Problems

### ISSUE THREAD

**Issue by rh5588** [flybywiresim/a32nx#4256]
**Mod Version**
Experimental Version a56c2ed

**Describe the bug**
When I try and select a livery the sim crashes out and the only way I can get onto the sim is if I use the default livery but when i get into the main sim there is no plane there and no lights are on 

**To Reproduce**
1. For the first issue go onto the livery page and try and select a livery. 
2. For the second issue just select an airport with just the default livery.
3. Spawn into an airport

**Expected behavior**
I expected to be able to see a cockpit and the exterior model of the plane and also expected to normally choose a livery and then continue into the sim and start flying. 

**Actual behavior**
The sim crashes when I select a livery and if I choose the default livery and enter the main sim I don't see an aircraft. 

**References**
None

**Additional context**
None

Was this working before/when did the issue start occurring?
The issue started today (3/4/21) and it was working before 

Is this a problem in the vanilla unmodded game?
No 

Discord username (if different from GitHub):
CptRhys UK#5777

**Comment by NitroMaxx72** [comment]
I have exactly the same problems

**Comment by Rukenshia** [comment]
From the README:

```
Warning: The development (master) and experimental versions have been forked as a separate package/aircraft in MSFS, and will appear separate from the default A320neo. Existing Asobo A320neo liveries will be incompatible with the new package.
```

**Comment by rh5588** [comment]
Hiya 
I had downloaded A32nx fork compatible liveries from flightsim.to because I was aware that the liveries that I used to have for the A32nx wouldn’t work

**Comment by rh5588** [comment]
This is a video of the issue

**Comment by rh5588** [comment]
And also the issue is not solved when I have updated the aircraft.

**Comment by rh5588** [comment]
Could I have a discord username that I could send my video to its too big to put on github

**Comment by MisterChocker** [comment]
![image](https://user-images.githubusercontent.com/1857322/113511081-5c200980-955e-11eb-8b5b-82ee9f78e900.png)

Closing as it's a known issue.
