### ISSUE TITLE
[BUG] ECAMs has electric power but wont go on after half hour 

### ISSUE THREAD

**Issue by luiskjr** [flybywiresim/a32nx#426]
Dev 0.2 using latest flybywiresim.
Previously i used to have problems because i was downloading the "code" zip file instead of the main latest.

Installed and followed engine start procedure, lit up instruments using knobs, started the engines, but no luck with the ECAMs upper and lower. See picture. Did I miss any button, all 3 knobs are aligned and on
![a32ecam](https://user-images.githubusercontent.com/70416990/92314479-42a9e580-efae-11ea-86f6-07e145f6a498.png)

**Comment by Benjozork** [comment]
Please do not remove the issue template.

**Comment by luiskjr** [comment]
sorry, Im new to the procedures here. next time...

**Comment by Benjozork** [comment]
All good ! it's fine for this time 🙂

**Comment by Benjozork** [comment]
> Dev 0.2 using latest flybywiresim.
Previously i used to have problems because i was downloading the "code" zip file instead of the main latest.

The latest version is now "master", so the "code" zip should be the latest one.

Can you reinstall using that and tell me if it still happens ?

**Comment by luiskjr** [comment]
I have two zip files
flybywiresim-a32nx.zip 73.719KB
a32nx-master.zip 76.242KB

which is the latest or valid?

**Comment by Benjozork** [comment]
No idea. Just download it again here : https://github.com/flybywiresim/a32nx/archive/master.zip

**Comment by luiskjr** [comment]
Now its working, it was the second zip
thanks issue closed

**Comment by Benjozork** [comment]
@luiskjr use the close button to close it :)
