### ISSUE TITLE
No sounds in new version

### ISSUE THREAD

**Issue by ukflyer** [flybywiresim/a32nx#4262]
**Mod Version**
Experimental

**Describe the bug**
No sounds on startup

**To Reproduce**
1. Start sim with A32NX
2. No sounds 

**Expected behavior**
Sounds like previous version

**Actual behavior**
No sounds

**References**
none

**Additional context**
None

Was this working before/when did the issue start occurring?
Yes, latest version separate a/c

Is this a problem in the vanilla unmodded game?
No

**Comment by ukflyer** [comment]
All ok after deleting files and reinstalling :)

**Comment by PX1181** [comment]
Delete the A32NX content in the community folder and re-download.
I had the same issue a few minutes ago and that's what i did.
The sound is back again.

**Comment by ukflyer** [comment]
Cheers
