### ISSUE TITLE
CTD when getting Tug for Pushback at Experimental version

### ISSUE THREAD

**Issue by CYB4** [flybywiresim/a32nx#4263]
Todays release of experimental FBW A320 crashed several times to desktop, when ordering the tug for pushback. That happened at EDNY Aerosoft scenery, havn't tested it at other airports

**Comment by ukflyer** [comment]
same, pushback fine when using the flypad

**Comment by Saschl** [comment]
This can sometimes happen due to a bug in the game. Some “gates” are wrongly declared as gates and can cause this. Please try with other airports. If it works there report the issue to the scenery developer if possible

**Comment by MisterChocker** [comment]
Please open a new issue and follow this template https://github.com/flybywiresim/a32nx/issues/new?assignees=&labels=Bug&template=bug_report.md
