### ISSUE TITLE
MCDU - DIR: Improvement - DIR TO should engage NAV mode

### ISSUE THREAD

**Issue by CptBlondBeard** [flybywiresim/a32nx#4264]
**Is your feature request related to a problem? Please describe.**

Missing feature for DIR TO function.

I initially figured someone would have mentioned this already but I finally got around to going through the Github and do not see this issue/enhancement mentioned so here goes. 

**Describe the feature you'd like to see implemented**

Changes to DIR TO execution:

I'm going to just quote direct from the FCOM as it is self explanatory (not a NEO FCOM, from the -200 series I operate, so not sure if the functionality has changed in the NEO):

"If the autopilot or flight director is in the heading/track or localizer mode, the "DIR TO" function engages the NAV mode."

"DIR TO defines a direct leg from the present position to a specified waypoint. NAV mode simultaneously engages upon DIR TO selection."

**References**

See below FCOM screenshot.

![Direct To should engage Nav mode](https://user-images.githubusercontent.com/5530831/113503310-54963b80-9531-11eb-8865-9e93d5d141e4.png)

**Additional context**

Discord username (if different from GitHub): Charlie [Z+2]

**Comment by mightywarriorr** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> Missing feature for DIR TO function.
> 
> I initially figured someone would have mentioned this already but I finally got around to going through the Github and do not see this issue/enhancement mentioned so here goes.
> 
> **Describe the feature you'd like to see implemented**
> 
> Changes to DIR TO execution:
> 
> I'm going to just quote direct from the FCOM as it is self explanatory (not a NEO FCOM, from the -200 series I operate, so not sure if the functionality has changed in the NEO):
> 
> "If the autopilot or flight director is in the heading/track or localizer mode, the "DIR TO" function engages the NAV mode."
> 
> "DIR TO defines a direct leg from the present position to a specified waypoint. NAV mode simultaneously engages upon DIR TO selection."
> 
> **References**
> 
> See below FCOM screenshot.
> 
> ![Direct To should engage Nav mode](https://user-images.githubusercontent.com/5530831/113503310-54963b80-9531-11eb-8865-9e93d5d141e4.png)
> 
> **Additional context**
> 
> Discord username (if different from GitHub): Charlie

I operate both the 200 series and NEOs and they work in the same way in regards the DIR to function.

**Comment by tracernz** [comment]
This should be implemented in the experimental version.
