### ISSUE TITLE
'Destination Path Too Long after rename from A32NX -> flybywire-aircraft-a320-neo #3932 on windows 10 with long file names enabled for Microsoft Store install

### ISSUE THREAD

**Issue by jagilber** [flybywiresim/a32nx#4265]
'Destination Path Too Long after rename from A32NX -> flybywire-aircraft-a320-neo #3932 on windows 10 with long file names enabled for Microsoft Store install

community path:
E:\WpSystem\S-1-5-21-xxxxxxxxxx-xxxxxxxxx-xxxxxxxxxx-1001\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\Community

**Mod Version**

master

**Describe the bug**

E:\WpSystem\S-1-5-21-xxxxxxxxxx-xxxxxxxxx-xxxxxxxxxx-1001\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\Community\flybywire-aircraft-a320-neo\html_ui\Pages\VCockpit\Instruments\Airliners\FlyByWire_A320_Neo\CDU\AIDS <--- == 251 chars

**To Reproduce**

1. use A32NX downloader with latest development build
2. copy newly renamed folder flybywire-aircraft-a320-neo into 'community' folder

**Expected behavior**

expected results is copy should happen without error

**Actual behavior**

actual results is error on path too long

**References**

**Additional context**

long path names are enabled in registry 
PS C:\> reg query "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem" -v LongPathsEnabled

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem
    LongPathsEnabled    REG_DWORD    0x1
Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game? no

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Valastiri** [comment]
> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning

The directory issue is a native windows issue. I'd advise moving your community folder out of the `S-1-5-21-xxxxxxxxxx-xxxxxxxxx-xxxxxxxxxx-` path as your registry hack may not work.

**Comment by Benjozork** [comment]
This is not the installer repository

**Comment by jagilber** [comment]
it actually is for 'community'. other mods go there when bought through the game. this is where i have always placed a32nx without issue. i chose different drive than c:\ for msfs install due to space, but didnt think you got to choose path. example of other users with similar paths in thread here: https://www.flightsim.com/vbfs/content.php?21235-Finding-The-MSFS-2020-Community-Folder#:~:text=While%20running%20MSFS%202020%20do%20the%20following%3A%201,folder%20location%20can%20be%20found%20under%20%22Watched%20Bases%22

**Comment by Benjozork** [comment]
Different mods / versions get longer subfolder structures / file names.
