### ISSUE TITLE
Mod seems like not active

### ISSUE THREAD

**Issue by Dndre** [flybywiresim/a32nx#4267]
**Experimental**

**Since a few days the mod seems not active in the Sim, but i have installed it via the installer. The standard A320 is loading instead of the Flybywire A320.
I tried often to uninstall and install the mod again, but it doesn´t solve the problem.**

**To Reproduce**

1.
2.
3.

**Flybywire A320 mod should show up in the Sim**

**The standard A320 is loading up **

**References**

**Additional context**

Was working fine before, and start a few days before
Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub): dndre#8338

**Comment by FRYYYYYY** [comment]
Please have a look at the readme or issue #4253

**Comment by Dndre** [comment]
Thank you.
