### ISSUE TITLE
Experimental Version.

### ISSUE THREAD

**Issue by Pineypower** [flybywiresim/a32nx#4269]
Latest version 4/4/21 has blown up & no instruments are showing !!

**Comment by tellurics** [comment]
Please follow the template issue.

**Comment by Valastiri** [comment]
Template ignored.

**Comment by MisterChocker** [comment]
If you don't find it yourself, here is the [bug template](https://github.com/flybywiresim/a32nx/issues/new?assignees=&labels=Bug&template=bug_report.md)
