### ISSUE TITLE
[Experimental cd80138] TCA Thrustmaster quadrant - Throttle not calibrated

### ISSUE THREAD

**Issue by thechrissou** [flybywiresim/a32nx#4276]
**Mod Version**

Experimental cd80138

**Describe the bug**

Using TCA Thrustmaster quadrant, the throttle is not calibrated correctly. 
Reverse are not taken into account.

**To Reproduce**

1. Using the TCA thrustmaster quadrant throttle, load a flight. 
2. Move the Thrustmaster throttle to full reverse, in the Flight Sim plane the throttle is shown iddle.
3. While increasing the throttle of the TCA physical device, the a320 throttle moves accordingly but is not in the correct position

**Expected behavior**

Physical TCA quadrant must match the a320 sim throttle position

**Actual behavior**

Physical TCA quadrant full reverse = a320 sim throttle idle
Physical TCA quadrant neutral = a320 sim throttle manual ~50%
Physical TCA quadrant climb = a320 sim throttle flx
Physical TCA quadrant flx = a320 sim throttle toga
Physical TCA quadrant toga = a320 sim throttle toga

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Starting since the last update. 0.5.4

Is this a problem in the vanilla unmodded game?
Not. Working with the default a320 from asobo

Discord username (if different from GitHub):
TheChrissou#0878

**Comment by 1Revenger1** [comment]
Have you done the calibration in the EFB? Turn it on and look under the settings cog on the very far right. Make sure "Reverse on Axis" is enabled, and set all the values for the different detents.

**Comment by thechrissou** [comment]
I did not changed anything in the MSFS options or "Target" software. 
Each throttle position is working correctly with the default Asobo a320.
Not sure what is the EFB that you are refering but I can have a try I guess. Where can I find this EFB?

**Comment by Benjozork** [comment]
As you can see in the experimental version usage guide, you have to configure the throttle mapping in the tablet before using it.

https://github.com/flybywiresim/a32nx/tree/autopilot/docs

**Comment by thechrissou** [comment]
Was not aware of this option in the EFB. Sorry for opening the bug for that but thank you so much for helping me. 
I'll close this as "not a bug"
