### ISSUE TITLE
Autothurst is not working (Experimental)

### ISSUE THREAD

**Issue by NiklasScheid** [flybywiresim/a32nx#4278]
**Mod Version**
```
 "built": "2021-04-04T09:45:06+00:00",
  "ref": "autopilot",
  "sha": "cd80138dd28a777480b730e4c1392e754d0e7ad7",
  "actor": "aguther",
  "event_name": "manual"
```

**Describe the bug**

Autothurst is engaged but the PFD reads MAN THR and no FLEX or CLB is possible. The ATHR doesn't throttle down, even in overspeed.

**To Reproduce**

1. T/O with FLEX
2. Climb through thrust red. alt
3. Select climb thrust

**Expected behavior**

T/O with FLEX, use CLB in flight

**Actual behavior**

Well no autothrust

**References**
![image](https://user-images.githubusercontent.com/45736442/113520019-7b378f00-9590-11eb-9216-0915304df193.png)
![image](https://user-images.githubusercontent.com/45736442/113520174-98209200-9591-11eb-8513-491a6c6ee53b.png)

Was this working before/when did the issue start occurring?
Yes

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):
Niklas#6994

**Comment by Benjozork** [comment]
Did you calibrate your throttle via the EFB as required ?

**Comment by NiklasScheid** [comment]
yes, my quadrant is perfectly synced with the fbw

**Comment by Benjozork** [comment]
Make sure to add a bit of a range in the CLB detent, so that it doesn't leave the detent all the time.

**Comment by NiklasScheid** [comment]
I don't think that it's a calibration issue. As you can see here, ATHR is engaged, THR CLB and the AC is way too fast but no counter actions by ATHR or AP 
![image](https://user-images.githubusercontent.com/45736442/113520721-7d501c80-9595-11eb-946e-830c4366c516.png)

**Comment by Benjozork** [comment]
because the ATHR does not see you in CLB...

**Comment by NiklasScheid** [comment]
Strange, after a reset and 'recalibration' the ATHR is working again.

**Comment by lukecologne** [comment]
The FMA is not indicating THR CLB, but MAN THR, which means you are somewhere between the CLB and TOGA detents, but not in one. You have probably not set enough of a deadzone for your detents.
