### ISSUE TITLE
ADD ON NOT WORK

### ISSUE THREAD

**Issue by lorenlan** [flybywiresim/a32nx#4288]
**Mod Version**
latest master build

**Describe the bug**
added the folder flybywire a 320 into community folder and in the game there is only dafault a320 model

**To Reproduce**
1.download latest master version
2.put it into community folder
3.the airplane in the game is the default a320

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?
I DOWNLOADED FAR DAYS AGO ONE OF THE MASTER VERSION AND IT WORK, THE BUG IS WITH THE RECENTS MASTER BUILD, FOR ME
Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by DavidEGTE** [comment]
@lorenlan have you used the search bar in the aircraft selection? try typing neo, you should have the Asobo and FBW versions, please let us know if FBW aircraft is visibile
![Microsoft Flight Simulator 02_04_2021 21_11_46 (2)](https://user-images.githubusercontent.com/19428125/113557595-2dee0880-95f6-11eb-9fb5-cb0b2fd19ef4.png)

**Comment by lorenlan** [comment]
thank you for the fast reply, ill try it soon

**Comment by Valastiri** [comment]
> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning

Please amend your issue and there's no need to use all caps in your text. 

Please see this -> https://docs.flybywiresim.com/start/reported-issues/

**Comment by CptRPeralta93** [comment]
i had the same problem but i allready solve it, but now i dont have the liveries that i had

**Comment by Benjozork** [comment]
@CptRPeralta93 As we explained in our initial announcement on both Discord and all social media, liveries have to be converted.

Compatible liveries are available here:

https://flightsim.to/c/liveries/flybywire-a32nx/

**Comment by CptRPeralta93** [comment]
i dind´t knew that.. but thank you for you help and for the link.

**Comment by artscout** [comment]
What about test pilot livery, it it going to be supported at all? :)

**Comment by Benjozork** [comment]
@artscout We only officially support the FBW livery.
