### ISSUE TITLE
switch version impossible

### ISSUE THREAD

**Issue by snypa972** [flybywiresim/a32nx#4291]
**Mod Version**

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by scoopscode** [comment]
Once again from your second request, it seems as if you arent following the template. I recommend you join the [Discord](https://discord.gg/flybywire) for a very quick response to this issue.

**Comment by MisterChocker** [comment]
Please open a new issue on the [installer repo](https://github.com/flybywiresim/installer/issues/new?assignees=&labels=Bug&template=bug_report.md&title=%5BBUG%5D+INSERT+TITLE+HERE) and fill out the provided template.
