### ISSUE TITLE
hi, only stable version 0.5.4 works for me, i have already uninstall / reinstall the FlyByWire simulations, but cannot upgrade to Development or experimental version. Can you help me please ?

### ISSUE THREAD

**Issue by snypa972** [flybywiresim/a32nx#4292]
**Mod Version**

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by scoopscode** [comment]
Hello, thanks for opening an issue. It seems as if you haven't followed the template and proceeded to state your issue in the title. However, I just want to make sure you are on the latest installer and not the old one. If you would like faster responses to your issue you can certainly join the [Discord.](https://discord.gg/flybywire)
