### ISSUE TITLE
3D modeling

### ISSUE THREAD

**Issue by vsm87** [flybywiresim/a32nx#4299]
**Is your feature request related to a problem? Please describe.**
A32nx 3D model improvements.
![89EBB732-0316-4410-AD19-2F6B7834239D](https://user-images.githubusercontent.com/81991260/113620292-6c1d1380-965a-11eb-8d61-bb0cb1c14438.jpeg)
![13B48CBB-2182-432D-AFA1-3AB0122C691A](https://user-images.githubusercontent.com/81991260/113620299-6f180400-965a-11eb-8c12-3335c5f356ab.jpeg)

**Describe the feature you'd like to see implemented**.

1. Nose icing lines/strips: above MSN 6xxx Airbus removed them, also for NEO version.
2. Improvement por whippers icing detectors from exterior.
3. Improvement for cockpit textures: air flow difusors in front the windshield.
4. Nose  landing gear angle.

**References**
Some pics attached and FCOM.

**Additional context**

Discord username (if different from GitHub):
vsm87

**Comment by MisterChocker** [comment]
Github issues only allow one issue per github issue (for tracking etc).
So please do go ahead and open a new issue for every issue you do like to report and ensure this issue only covers a single issue.

**Comment by MisterChocker** [comment]
Closing since no response from op.
