### ISSUE TITLE
switch version installer impossible

### ISSUE THREAD

**Issue by snypa972** [flybywiresim/a32nx#4300]
Salut, je ne peux pas utiliser les versions development et experimental depuis l'installer FlyByWire. je ne peux utiliser uniquement la version stable 0.5.4
pouvez-vous m'aider svp ?

**Comment by Benjozork** [comment]
Bonjour,

Assurez vous de bien sélectionner la version séparée de l'A320neo si vous êtes sur une dev ou exp récente.

Guide en français:

https://youtu.be/RAUZ7kpzZuo

**Comment by snypa972** [comment]
Oook donc je dois dorénavant télécharger et installer les 3 versions séparément ??

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : Benjamin ***@***.***>
Envoyé le :lundi 5 avril 2021 18:40
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [flybywiresim/a32nx] switch version installer impossible (#4300)


Bonjour,

Assurez vous de bien sélectionner la version séparée de l'A320neo si vous êtes sur une dev ou exp récente.

Guide en français:

https://youtu.be/RAUZ7kpzZuo

**Comment by Benjozork** [comment]
> Oook donc je dois dorénavant télécharger et installer les 3 versions séparément ??

Non. Avec les versions dev et expérimental, vous devez séléctionner le "**FlyByWire Simulations** A320neo (LEAP)" séparément dans le sélécteur d'avions dans MSFS. Vous ne pouvez plus prendre l'A320neo de base de MSFS, car maintenant il est séparé pour éviter les conflits avec les MAJ d'Asobo.

**Comment by Benjozork** [comment]
Ce n'est pas le cas avec la v0.5.4 stable, mais ça le sera avec la v0.6.0.

**Comment by snypa972** [comment]
Merci, excellent . je n’avais pas vue votre article sur votre page facebook qui parle de la dissociation avec l’avion d’origine de ASOBO. Je trouve que c’est une très bonne idée de votre part de l’avoir fait d’ailleurs. Mais quand est-il des livrées que je possédais ? j’ai vue qu’ils n’apparaissent plus dans la liste.

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : Benjamin ***@***.***>
Envoyé le :lundi 5 avril 2021 19:01
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [flybywiresim/a32nx] switch version installer impossible (#4300)


Ce n'est pas le cas avec la v0.5.4 stable, mais ça le sera avec la v0.6.0.

**Comment by Benjozork** [comment]
> Mais quand est-il des livrées que je possédais ? j’ai vue qu’ils n’apparaissent plus dans la liste.


flightsim.to offre déja plus de 190 liverées compatibles:

https://flightsim.to/c/liveries/flybywire-a32nx/

Un outil de conversion sera aussi disponible dans l'installateur d'ici quelques jours.

**Comment by snypa972** [comment]
Très bien, merci beaucoup pour toute ces informations

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : Benjamin ***@***.***>
Envoyé le :lundi 5 avril 2021 19:10
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [flybywiresim/a32nx] switch version installer impossible (#4300)


Mais quand est-il des livrées que je possédais ? j’ai vue qu’ils n’apparaissent plus dans la liste.

flightsim.to offre déja plus de 190 liverées compatibles:

https://flightsim.to/c/liveries/flybywire-a32nx/

Un outil de conversion sera aussi disponible dans l'installateur d'ici quelques jours.
