### ISSUE TITLE
Game crash after later update

### ISSUE THREAD

**Issue by CptRPeralta93** [flybywiresim/a32nx#4301]
**Mod Version**

**Describe the bug**

Today i install the latest development update, and after that, the game keep crashing, i uninstall the files, and install the version that i download on march 30th and the game just works fine

**To Reproduce**

1.Game Crash
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?
yes/today, after i downloaded and install the latest development version
Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
"BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning"
