### ISSUE TITLE
[BUG] Gross weight never changes in ECAM

### ISSUE THREAD

**Issue by theersink** [flybywiresim/a32nx#431]
**Mod Version**
 Master

**Describe the bug**
 Fuel page that displays GW never changes with fuel usage. I am not sure if this is an Asobo bug where the aircraft itself never changes in GW or if it is just a display issue.

**To Reproduce**

1. Load any flight
2. Monitor ECAM
3. GW weight always stays at what was loaded at the beginning of flight

**Expected behavior**
 GW should drop with fuel usage

**Actual behavior**
 Never goes down.

**References**
 Flight from San Fran to Hawaii. This is 3 1/2 hrs in to flight. 0 change in GW
![3hrs into flight](https://user-images.githubusercontent.com/70825153/92315506-1a20ec00-efac-11ea-9e0b-a6721e7e7bae.JPG)

![3hrs into flight_2](https://user-images.githubusercontent.com/70825153/92315518-581e1000-efac-11ea-834b-197752140572.JPG)

**Additional context**

**Comment by UncleClapton** [comment]
This will be fixed by #410

**Comment by AdenFlorian** [comment]
fixed by #410
