### ISSUE TITLE
[MCDU] Simbrief import uses flight number instead of callsign in INIT A

### ISSUE THREAD

**Issue by St54Kevin** [flybywiresim/a32nx#4311]
**Mod Version**

All versions as of 6th April 21.
Used version:
{
  "built": "2021-04-05T20:55:06+00:00",
  "ref": "autopilot",
  "sha": "62a7f9af5b4329e2497a6a4a8682ec296ee1c256",
  "actor": "aguther",
  "event_name": "manual"
}

**Describe the bug**

Loading the simbrief flight plan via ACARS it fills the FLT NBR field on INIT A with the simbrief flight number

**To Reproduce**

1. Make a simbrief plan with a specified ATC callsign (extra field)
2. Load the plan via MCDU ACARS Init
3. Load into INIT and check FLT NBR field
4. It will say DLH12345 instead of DLH54M or being empty

**Expected behavior**

After checking with another IRL pilot the FLT NBR field should stay EMPTY after ACARS load, so the callsign has to be entered manually. Even if not, it should take the callsign from the simbrief plan rather than the flight number

**Actual behavior**

Loads whatever you put into the flight number field in simbrief
![image](https://user-images.githubusercontent.com/448627/113725752-ebaaf100-96f3-11eb-9b07-68f223972d17.png)

**References**

IRL experience and FMS manual (field should contain callsign, not commercial flight number)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by tracernz** [comment]
https://github.com/flybywiresim/a32nx/issues/3083 somewhat related.
