### ISSUE TITLE
FBW A320 Checklist Takeoff CG vs Trim Pos Reference Line Mismatch

### ISSUE THREAD

**Issue by CptBlondBeard** [flybywiresim/a32nx#4312]
**Mod Version**

Dev and Experimental (I don't use stable so haven't checked)

**Describe the bug**

Saw today FBW recently released a nice branded checklist to go with the A32NX, nicely done! However there is a large mismatch between the Takeoff CG/Trim Pos reference line in the checklist and the trim wheel CG/Trim Pos reference line of the aircraft itself. Looks like the checklist is the erroneous party. 

**To Reproduce**

1. Not an aircraft bug but a documentation bug, see attached screenshot.
2.
3.

**Expected behavior**

Checklist reference line should match the aircraft trim wheel reference line. 

**Actual behavior**

See above points.

**References**

![Checklist TO CG and Trim POS Mismatch](https://user-images.githubusercontent.com/5530831/113736174-2a917480-96fd-11eb-9651-769c1de303bb.png)

**Additional context**

Was this working before/when did the issue start occurring? 
N/A / Release of FBW A320 Checklist

Is this a problem in the vanilla unmodded game?
No.

Discord username (if different from GitHub): Charlie [Z+2]

**Comment by MisterChocker** [comment]
Neo:

![image](https://cdn.discordapp.com/attachments/767586833491558401/838006979753803836/20201223_105858.jpg)
