### ISSUE TITLE
[BUG] Nose Lights Not Turned On in "Taxi"

### ISSUE THREAD

**Issue by Coralec** [flybywiresim/a32nx#432]
**Mod Version**

e25ee3d

**Describe the bug**

Nose lights are not turning on when set to taxi. They are operating properly when in Takeoff, and the runway turnoff lights are operating properly.

**To Reproduce**

1. Land at night (bug encountered at KIAD)
2. Set nose lights from takeoff to taxi after exiting the runway
3.

**Expected behavior**

The taxi lights should turn on and illuminate the taxiway.

**Actual behavior**

Lights do not turn on, and taxiway remains dark. 

**References**

**Additional context**

**Comment by Coralec** [comment]
Bug replicated after spawning at KBOS.

**Comment by 0nnyx** [comment]
Confirming this behavior too : nose taxi lights not working and same as off

**Comment by myselfaaryan** [comment]
Can confirm this too. I was just about to open an issue.

**Comment by nobodyn0se** [comment]
I noticed this issue with the default A320 in the initial days after release, it seemed to be fixed with the mod.  Will see if the latest master has it.

**Comment by UncleClapton** [comment]
I seem to have found the root of this problem by mistake. PR to fix this incoming
