### ISSUE TITLE
Improve the cockpit door

### ISSUE THREAD

**Issue by fluffyGamingCat** [flybywiresim/a32nx#4320]
**Is your feature request related to a problem? Please describe.**

"I am always frustrated when I immerse myself in the fantastic Airbus cockpit and get my sense for perfection and realism and true graphics quality disturbed every time when I see that annoying and intrusive graphics glitch on the cockpit door...."

**Describe the feature you'd like to see implemented**

I have noticed that you can do superb 3D modelling and also modify the 3D-aspects of the airbus cockpit (for example adding this FlyPad) that`s why I assume you can manage to remove this graphics glitch. That`s why I would absolutely love if you fix the Airbus door frame bug because only you can do this (Asobo does not care about the vanilla planes anymore and will never fix anything anymore related to the planes in their monthly Flight Sim patches - only scenery and stuff will be fixed in the future.) That`s why only you can become the saviour of the Airbus Neo ;)

**References**

The real airplane does not have this graphics bug at the door.

**Additional context**

Discord username (if different from GitHub):
My Discord username is Murmeltier Deluxe#9219 and I can answer to you in German or English.

![Microsoft Flight Simulator 06 04 2021 18_27_50](https://user-images.githubusercontent.com/82053568/113757372-d1ccd680-9712-11eb-9524-c2b58ce4929d.png)
![Microsoft Flight Simulator 06 04 2021 18_28_04](https://user-images.githubusercontent.com/82053568/113757388-d5f8f400-9712-11eb-8892-e6a632468237.png)

**Comment by Benjozork** [comment]
We can only add models not modify them for now

**Comment by tyler58546** [comment]
> 
> 
> We can only add models not modify them for now

how bout i do anyway
