### ISSUE TITLE
[BUG] Liveries do not default to FBW

### ISSUE THREAD

**Issue by Zyonix007** [flybywiresim/a32nx#4321]
**Mod Version**

**Describe the bug**

**To Reproduce**

1.Load sim
2.See that liveries are not resorting to the default. 
3.

**Expected behavior**
The livery should automatically use the Flybywire livery in the menu 

**Actual behavior**
It keeps resorting to my livery 

**References**
![image](https://user-images.githubusercontent.com/60050366/113759488-1fc9e600-96e3-11eb-9ee6-5528be97f796.png)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
No

Zyonix

**Comment by Valastiri** [comment]
Usually an issue with a poorly converted livery see -> https://docs.flybywiresim.com/start/convert-liveries/ which was recently updated. Also see PR https://github.com/flybywiresim/a32nx/pull/4303

**Comment by Zyonix007** [comment]
i know I already saw that and tried it. it still does not do what it supposed to. I even tried installing more liveries and all it does is set the new installed livery as default

**Comment by Valastiri** [comment]
As I understand you're talking about when you "click" off the FBW Airbus the livery does not return to the "house or default" livery? 

From your template I was operating under the assumption of "load in sim" which retains your last flown livery. 

I can replicate the issue of:

**FlyByWire Card**

- Select Livery in FBW Airbus
- Switch aircraft in aircraft selection
- Livery selected remains on the package card.

**All other aircraft**
- Select livery
- Switch aircraft
- Livery selected returns to default on the package card

If that is the isssue

**Comment by Zyonix007** [comment]
correct. after selecting a livery and then changing it. then selecting another plane the livery reverts not to the house livery like it should. even if you change the livery. the replicating is correct

**Comment by MisterChocker** [comment]
I actually don't mind if the livery stays the same from my last flight.

**Comment by sidnov** [comment]
The last used livery showing up on the thumbnail is how the sim works. Not much we could do here I guess
