### ISSUE TITLE
Elevator Stuck after disabling Autopilot with active ILS approach 

### ISSUE THREAD

**Issue by heikotroetsch** [flybywiresim/a32nx#4325]
**Mod Version**
v0.5.3
Stable Version Installer

**Describe the bug**
After having used a localizer ILS approach and enabling the Approach the Elevator is stuck and can only point down. This happens after the autopilot is disabled while the approach is active. The plane can be maneuvered in every direction besides pulling up. 

**To Reproduce**
1. Fly ILS approach with intersect less than 30 degrees.
2. Align on localizer. Afterwards enable approach to capture glide slope. 
3. At about 500m above ground disable autopilot and continue manually. The elevator control then gets stuck. 

**Expected behavior**
Full elevator function.

**Actual behavior**
Stuck elevator that can't pull up but can be used to descend further. 

**References**
None, will add in comments when encountered again. 

**Additional context**
IVAO was active with Pilot client and Air Berlin livery was used. 

Was this working before/when did the issue start occurring?
The Issue started occurring when the plane was reinstalled with installer instead of moving to community folder. Old version was removed. 

Is this a problem in the vanilla unmodded game?
Game is not modded. Only IVAO Pilot client and Livery Pack is added.

**Comment by Benjozork** [comment]
Version 0.5.3 is not supported. Please update.

**Comment by heikotroetsch** [comment]
I installed it yesterday and it says its up to date. Am I missing something? Is this a bug of the installer? Otherwise I will manually install it again.

**Comment by MisterChocker** [comment]
The latest stable version 0.5.4.

**Comment by heikotroetsch** [comment]
Let me Upgrade and reopen the Issue in case it persists.

**Comment by heikotroetsch** [comment]
Issue keeps occurring with the newest version

**Comment by MisterChocker** [comment]
Please ensure you are not using the numpad or any other key that manipulates the aerodynamic surfaces.

**Comment by heikotroetsch** [comment]
I have been trying to reproduce this for over two hours now and i seem to only be able to reproduce this when flying a complete route on IVAO. There is no usage of the Numpad and resetting it does not help unstuck the elevator. The elevator is free to travel down, but the up position is stuck.
