### ISSUE TITLE
Add FT.SIM Soundpack as Default [REQUEST]

### ISSUE THREAD

**Issue by Zyonix007** [flybywiresim/a32nx#433]
**Is your feature request related to a problem? Please describe.**

You can make the sound better

**Describe the feature you'd like to see implemented**

Please add FTSim Sound pack as part of the mod by default 

**References**

https://mfsim-sounds.blogspot.com/2020/09/a320neosp-fs2020.html

**Comment by Benjozork** [comment]
We will see if there is interest for this, but this project is modeled after LEAP 1A engines and not the P&W ones.

**Comment by hotshotp** [comment]
Old issue, but I am STRONGLY against this. I am making high quality sounds which I plan to be even better than the ones of FT.SIM. I plan to also make high quality leap 1a sounds rather than the PW and of course add many more sounds than there are already in the ft.sim sound pack.
