### ISSUE TITLE
high EGT before engine start 

### ISSUE THREAD

**Issue by kutak11** [flybywiresim/a32nx#4332]
**Mod Version**

Experimental 6f4c662

**Describe the bug**

high EGT before engine start - cold engine shows high temperature

**To Reproduce**

1. Start engine no. 2 a see EGT on Engine no.1 
2.
3.

**Expected behavior**

normal increasing of temperature from low values 

**Actual behavior**

Engine show 680°C EGT even before start

**References**

![Microsoft Flight Simulator Screenshot 2021 04 06 - 22 55 51 100](https://user-images.githubusercontent.com/72166387/113880693-fd57cb80-97bb-11eb-92ad-2564fff3d377.png)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment]
Known issue, engine start up sequence not yet implemented.
Please take a look at our [documentation](https://github.com/flybywiresim/a32nx/tree/autopilot/docs) first and check for known issues.
