### ISSUE TITLE
Game hangs when insterting Airways and Waypoints due to bad Navigraph data

### ISSUE THREAD

**Issue by cchard360** [flybywiresim/a32nx#4338]
**Mod Version**

Issue is present in both Stable 0.5.4 and Dev

{
  "built": "2021-04-07T18:22:09+00:00",
  "ref": "master",
  "sha": "a0f56fc05b8840dbd9d3e706a51137439b789663",
  "actor": "Benjozork",
  "event_name": "manual"
}

**Describe the bug**

With the Navigraph FS2020 data installed attempting to load an airway with bad data into the MCDU causes the game to freeze for about 1-2 minutes. After it unfreezes the flightplan appears correct. This happens with the Simbrief importer and manual flight plan entry. Although the issue is bad Navigraph data the plane could handle the bad data better without freezing. 

**To Reproduce**

Full SimBrief routings:
LSGG MEDA5Q MEDAM UM730 ATMAD M730 KALMO Q223 TINKU Q705 XIBIL XIBI3C LIRF
LSGG MEDA5P MEDAM UM730 ATMAD M730 LOMED Z910 ERIKA M736 TEA TEA2D LIRN

1. Install the Navigraph Beta data (AIRAC 2103 rev2) from the installer
2. Install the A320 stable (or dev) using the installer
3. Launched FS2020 and loaded into LSGG
4. I loaded the flight plan from SimBrief into the MCDU via AOC
5. On the INIT A clicked the button (Init Request) to import the data and plan. The INIT A page updated with the correct data (From/To, Flt#, CCI, CRZ, etc) but then the game froze at that point with “UPLINK INSERT IN PROG” on the scratchpad.
6. I waited and after about 2 mins the game unfroze and I got “AOC ACT F-PLN UPLINK” message.
7. I was able to manually add SID and STAR and the Flight Plan looked like it added all the Airways and waypoints correctly.

You can also attempt to load the same flight plan without the Simbrief and the game will also freeze. It appears to happen after getting UM730 to ATMAD entered correctly I attempted to insert M730 to LOMED. Airway entry was fine but as soon as I tried to insert LOMED the game froze again.

After uninstalling the Navigraph data the game no longer freezes when adding the same flight plan via SimBrief.

**Expected behavior**

Since the import does work if you wait through the freeze it would be ideal if it could not freeze at all on bad data while still adding the full route/airway/waypoints.

However if that can't happen in the event of bad data (from Navigraph, stock FS, or other) the game should not freeze and the MCDU could give an error message or some other more user friendly response. 

**Actual behavior**

With bad data the game freezes for about 1-2 minutes, after it unfreezes the flight plan is loaded correctly with no missing waypoints or airways. 

**References**

I also reported the issue to Navigraph and included a screenshot of the 787 giving an error instead of freezing. Another user also reported the same issue in Italy on different airways: https://forum.navigraph.com/t/had-my-first-issue-with-the-msfs-beta-when-adding-a-specific-airway/4764/2

**Additional context**

I have not tried the CJ4 but on Discord there was a report that the game did not freeze attempting to load the same flight plan on that plane: https://discord.com/channels/738864299392630914/785976111875751956/828676639080579072  in addition to my 787 test this shows it should be possible to handle the bad data without the freeze. 

Was this working before/when did the issue start occurring?

I have not used that Airway before this issue appeared but this was the first time I had this issue after using the Dev and Navigraph data for about a month.

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):
Zero One#4399

**Comment by jengle53** [comment]
Also had issue with a waypoint, with the sim freezing:
*
I am unable to enter a full flight plan. I’ve flown the flybywire probably 10 times at least, and not had this problem. Three times I entered manually, and twice attempted direct simbrief. LDZA/LPPT with route of KOTO1V KOTOR DCT RJK DCT NAKIT DCT LABIN DCT LURUT DCT GOLAS DCT ENOBA DCT BORDI Z185 BADBA UZ185 KOLON UM984 BISBA UN975 BGR UT410 ARBEK DCT OSLAP UN975 CCS DCT EXONA EXON8A generated by simbrief. Twice I entered the flight plan up to ENOBA and then it froze. The third manual attempt I entered and inserted each waypoint and it died at ENOBA. When I said “died” the SIM freezes. I have to end program using task manager. When I try to import Simbrief I get “not in database”, “Not allowed”, “uplink in progress”. Using Simbrief only flight plan nothing from MSFS. This is the first time using the uplink feature, but I always manually enter flight plan - many 3 or 4 hours with lots of waypoints. - Wait - it finally came back after ENOBA entered after about 5 minutes. Let me chug along… Sorry - I’m usually patient, but 5 minutes with a complete Sim freeze is strange. Ok… update: got the flight plan entered. Just took FOREVER to add ENOBA.*

**Comment by Watsi01** [comment]
My personal experience is, if the navigraph airac is sorted wrong in the context.xml (MSFS), it's causing many issues and CTDs. Please use the official Navigraph installer for MSFS to place it correctly. I'm using the latest AIRAC (rev 2, I think) and for me it works fine.

**Comment by tracernz** [comment]
I can reproduce this issue (although it only freezes for approx. 30 seconds) with latest Navigraph revision (2103.2). https://gist.github.com/tracernz/59ea5804d250c33bef1ca6123dff7377

**Comment by cchard360** [comment]
> 
> 
> My personal experience is, if the navigraph airac is sorted wrong in the context.xml (MSFS), it's causing many issues and CTDs. Please use the official Navigraph installer for MSFS to place it correctly. I'm using the latest AIRAC (rev 2, I think) and for me it works fine.

Thanks but I did only use the Navigraph installer for MSFS and uninstalled and reinstalled the data several times for testing purposes.

**Comment by 2hwk** [comment]
Fixed by #4953 closing ☑️

**Comment by sidnov** [comment]
It's been a long time now that we've had freezes/crashes due to navdata. Please open a fresh issue if needed with updated issue details, or drop by the #support channel on the FBW Discord
