### ISSUE TITLE
Plane moves far too much on takeoff and after touchdown

### ISSUE THREAD

**Issue by ErickSharp** [flybywiresim/a32nx#4341]
**Mod Version**
Latest Experimental, Development, occurs in most, if not all 5.0 and later buids

**Describe the bug**

When taking off and after touchdown as well as when slowing down, there is an excess amount of movement on the runway which the player needs to counteract with a large amount of rudder input, making the plane violently swerve on the runway.

**To Reproduce**

1. Try and takeoff.
2. Land and observe the violent handling.
3.

**Expected behavior**

It should be much more stable and shouldn't require such a large amount of rudder input.

**Actual behavior**

The plane almost violently swerves on the runway and frequently tries to veer from the runway centerline.

**References**

Ask @danbw9

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game? No, the default airplane has better handling on the ground than the mod 😹

Discord username (if different from GitHub): Erick [Z-6]#6484

**Comment by MisterChocker** [comment]
Following the discussion on our dc channel flight-model, this only occurs on crosswind scenarios.

**Comment by ErickSharp** [comment]
Here's a video that I sent in the Discord. I was landing on runway 25R at KLAX with a 13-knot crosswind blowing in from the right at heading 340. I come into land with a crab and input rudder once on the ground as normal, and upon landing, I try to maintain centerline, and at the end you just see me give up and the plane veers to the right. 

https://www.swisstransfer.com/d/56adc1c5-74f3-46fa-858c-fb38408b7207

**Comment by ErickSharp** [comment]
Please let me know if you guys are also experiencing this issue!

**Comment by rowanw87** [comment]
I recognize this issue!

**Comment by CptBayer** [comment]
me too. My plane is always drifting to the right. During taxi, takeoff and in flight as well. I set the DEAD Zone of my rudder to 10 and the sensibility to -80 %. Also increased the dead zone of my ailerons. That doesn´t fix the drift. 

Greets Klaus

**Comment by donstim** [comment]
Excessive weathervaning on the ground has been a long term MSFS issue that affects all airplanes, not just ours - https://forums.flightsimulator.com/t/wind-causes-aircraft-to-turn-only-on-the-ground-as-if-theres-full-rudder/378471. It also exists on the MSFS A320. Have you determined it to be significantly worse on our mod?

**Comment by cchard360** [comment]
Someone asked if the Auto Rudder on TO assist option would help. I've been using that since the game came out because I don't have rudder pedals (I use the twist on my joystick). I hadn't really noticed this issue with the Assist on but when I turned it off to test I immediately noticed the plane swerving across the runway. 

So the Assist function could be a workaround if people need one.

**Comment by donstim** [comment]
> Here's a video that I sent in the Discord. I was landing on runway 25R at KLAX with a 13-knot crosswind blowing in from the right at heading 340. I come into land with a crab and input rudder once on the ground as normal, and upon landing, I try to maintain centerline, and at the end you just see me give up and the plane veers to the right.
> 
> https://www.swisstransfer.com/d/56adc1c5-74f3-46fa-858c-fb38408b7207

After watching your video, I am confused over what the issue is. It looks like you have no trouble maintaining centerline during your rollout. I don't know why you "gave up," but by that speed, the rudder is not effective anyway.

**Comment by Silvaronn** [comment]
I have the same problem. This had been fixed before, in the old '' custom fbw ''. After the last update it came back as if it were the default A320 .

**Comment by donstim** [comment]
> I have the same problem. This had been fixed before, in the old '' custom fbw ''. After the last update it came back as if it were the default A320 .

Can you explain exactly what the "same problem" is?

**Comment by Silvaronn** [comment]
> > Tenho o mesmo problema. Isso já havia sido corrigido antes, no antigo '' costume fbw ''. Após a última atualização, ele voltou como se fosse o A320 padrão .
> 
> Pode explicar exatamente qual é o "mesmo problema"?

during takeoff and landing the aircraft moves excessively.
