### ISSUE TITLE
Able to move trim wheels beyond their stopping point.

### ISSUE THREAD

**Issue by ErickSharp** [flybywiresim/a32nx#4342]
**Mod Version**
Latest experimental, development, and most builds of v0.5.X

**Describe the bug**

You can move the left trim wheel all the way to its maximum and then keep on moving the right trim wheel.

**To Reproduce**

1. Put the trim on the left trim wheel to the highest downwards trim.
2. Try and trim the right trim wheel even further down.
3. Profit

**Expected behavior**

After going to the max trim, you shouldn't be able to move either of the trim wheels past the limit.

**Actual behavior**

You can keep on spinning the right-hand trim wheel. 

**References**

https://user-images.githubusercontent.com/30361843/113952059-82ea7400-97da-11eb-868d-cb8fb57bb4c1.mp4

**Additional context**

Was this working before/when did the issue start occurring?
Started happening a while ago, perhaps before the release of version 0.5.0, I just now decided to open a bug report.
Is this a problem in the vanilla unmodded game? No

Discord username (if different from GitHub): Erick [Z-6]#6484

**Comment by lukecologne** [comment]
Currently looking into a fix
