### ISSUE TITLE
Visible Pilot and copilot 

### ISSUE THREAD

**Issue by 4791pg** [flybywiresim/a32nx#4343]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**

**References**

**Additional context**

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by MisterChocker** [comment]
Just a small heads-up, this has already been requested #3228 and implemented #3426 once and got removed https://github.com/flybywiresim/a32nx/commit/7e585dace9a1c8516fe0318c576a62bd1bf56d39 afterwards.

Please fill in the provided template, so we can better understand your request. Thanks!

**Comment by 4791pg** [comment]
No idea what that means, I clicked on the ! asterisk on the installer and I saw a button for suggests/requests and its one thing I think it should defiantly have.

________________________________

**Comment by MisterChocker** [comment]
All good, I just told you that we once added this feature and then removed it again. That doesn't mean your request has no valid point.

Please don't forget to fill in the template we provided, you can edit it by clicking on the three dots in the top-right corner of your first comment.
![image](https://user-images.githubusercontent.com/1857322/113955835-c1088780-981c-11eb-906c-fae49088f3e9.png)

**Comment by 4791pg** [comment]
Many thanks.

Sorry for any inconvenience caused.



On Apr 7, 2021, at 19:45, DerL30N ***@***.***> wrote:

﻿

All good, I just told you that we once added this feature and then removed it again. That doesn't mean your request has no valid point.

Please don't forget to fill in the template we provided, you can edit it by clicking on the three dots in the top-right corner of your first comment.
[image]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F1857322%2F113955835-c1088780-981c-11eb-906c-fae49088f3e9.png&data=04%7C01%7C%7C4c1054317f774d07bc2608d8fa2ff0f9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637534431093425126%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9LJ57UQ%2FaRancU1fdY72bSGOV%2Bf%2B1ITDBmZaGvDqusI%3D&reserved=0>

**Comment by MisterChocker** [comment]
We have decided we won't introduce this feature until we have our own pilot models.
Closing this issue now.
