### ISSUE TITLE
MCDU Menu options cannot be selected

### ISSUE THREAD

**Issue by cchard360** [flybywiresim/a32nx#4345]
**Mod Version**

{
  "built": "2021-04-07T23:34:58+00:00",
  "ref": "master",
  "sha": "e8e2d3f43c7627c283ee2aef1828ffe77cc62fc7",
  "actor": "MisterChocker",
  "event_name": "manual"
}

**Describe the bug**

MCDU Menu options (FMGC, ATSU, AIDS, CFDS) cannot be selected and page does not change. 

**To Reproduce**

1. Go to MCDU menu (default on startup or from pressing menu button
2. Attempt to select FMGC, ATSU, AIDS, or CFDS
3. Observe that the page you selected does not load

**Expected behavior**

Selecting the option would load that page

**Actual behavior**

The screen remains on the MCDU menu and the option selected changes to blue text with (SEL) label. You are able to change all the options to blue in this way but the page never changes. 

The FMGC pages can still be loaded with the "physical" buttons but there is no workaround for the others.

**References**

https://cdn.discordapp.com/attachments/785976111875751956/829561894079037480/20210407234126_1.jpg

**Additional context**

Maybe related to https://github.com/flybywiresim/a32nx/commit/e8e2d3f43c7627c283ee2aef1828ffe77cc62fc7

Was this working before/when did the issue start occurring?
It was working earlier on 4/7/21 but stopped after an update on 4/7/21. 

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):

Zero One#4399

**Comment by airfirefighter** [comment]
same here....

**Comment by Watsi01** [comment]
Please remove any livery and an other mod from you community folder and try again.

**Comment by admon67** [comment]
Hi @all 

the same issue here!
All other mods was removed from the community folder.

thx

**Comment by Watsi01** [comment]
Ok thanks. We'll check that.

**Comment by AdamNZ** [comment]
Same here. No other aircraft modes active. The buttons worked fine for the first few updates after the fork - just this last one appears to have gone awry.
