### ISSUE TITLE
No display on MCP[BUG]

### ISSUE THREAD

**Issue by benwal91** [flybywiresim/a32nx#435]
**Mod Version**

0.2.0

**Describe the bug**

No display on MCP.
**To Reproduce**

1. Turned on battery. Selected Ext. Power. Started APU
2. Align - Removed Ext. Power when APU was available
3.Started engines

**Expected behavior**

Expected MCP to come on with either battery or the start of APU/Ext power.

**Actual behavior**

No MCP display or Altimeter setting display. Checked upper panel to ensure nothing was missed. No lights indicating everything is normal. 

**References**

![mcp](https://user-images.githubusercontent.com/8030534/92315965-aab2f880-efbb-11ea-9537-6677948345b4.png)
Copilot displays show, the brightness was just turned down. But issue is with MCP. 

**Additional context**

**Comment by UncleClapton** [comment]
Please make sure the brightness nobs are turned up.

![](https://cdn.discordapp.com/attachments/738864300818432023/750409540918444072/A320_screens.png)

**Comment by benwal91** [comment]
Oh. Did not notice those. Assumed they just come on. Thanks.
