### ISSUE TITLE
[BUG] altitude alert 

### ISSUE THREAD

**Issue by Aseinsha** [flybywiresim/a32nx#4354]
**Mod Version:** Experimental 

{
  "built": "2021-04-07T20:06:18+00:00",
  "ref": "autopilot",
  "sha": "8998b9e388f50581c292ebb17f24e3f67ded7106",
  "actor": "MisterChocker",
  "event_name": "manual"
}

**Describe the bug**

If you are reaching or leaving your preselect or managed altitude there should be an alert sound. pull #3281 had initially fixed this but its half broken now, the C-chord only sounds when leaving your pre-selected altitude now, not when reaching your your selected or managed altitude. 

**To Reproduce**

1.set altitude
2.climb
3.reach altitude

OR 

1.set altitude
2.descend
3.reach altitude

**Expected behavior**
Altitude C chord to sound when reaching selected or managed altitude.

**Actual behavior**
No altitude c chord warning when reaching selected or managed altitude.

**Additional context**
Similar to [BUG] altitude alert #1227 which was closed by feat: add altitude C chord warning sounds #3281
[PFD] Add altitude C chord warning sounds #2136 which was closed by feat: add altitude C chord warning sounds #3281

Discord username (if different from GitHub): aseinsha#0455

**Comment by AirbusA320Pro** [comment]
IRL the altitude alert "C chord" does not sound when the autopilot is engaged. Except when the altitude deviates from its FCU selected value during ALT lock. 
Altitude alerting is inhibited when slats extended and gear selected down, or after G/S capture, or when the gear is downlocked.

**Comment by Aseinsha** [comment]
I couldn't find any document about how autopilot would affect this, but will take your work :)
