### ISSUE TITLE
Slow climb / cannot reach 390

### ISSUE THREAD

**Issue by ukflyer** [flybywiresim/a32nx#4359]
**Mod Version**
Experimental

**Describe the bug**
Slow climb to cruise altitude

**To Reproduce**
1. FOB 10,780
2. GW 70,500
3. slow climb to FL390

**Expected behavior**
Better performance to FL390 at GW 70,500

**Actual behavior**
hardly any climb rate above FL360

**References**

**Additional context**
None

Was this working before/when did the issue start occurring?
Maybe few experimental versions back it was fine

Is this a problem in the vanilla unmodded game?
N/A

![Capture](https://user-images.githubusercontent.com/70434502/114155280-35285580-9919-11eb-9a3a-b903a0ed6298.JPG)

**Comment by ukflyer** [comment]
max ALT 380, i think i have to many passengers!

**Comment by Saschl** [comment]
Could be one reason! But we're also aware that the new engine model can sometimes be a bit too weak. But rest assured it will be constantly improved

**Comment by ukflyer** [comment]
thanks MCDU has MAX alt 380, but was following a EZY flight to TFS and they were climbing 2,000ft/min past 36,000. Think it must be light passenger load. Not sure how much it can climb at 70,000 GW

**Comment by Khitiara** [comment]
the max altitude the a320 is certified to even get to is 39000 anyway afaik
