### ISSUE TITLE
Strange line on ND on huge DCT leg, crossing the International Date Line

### ISSUE THREAD

**Issue by ferryvanaesch** [flybywiresim/a32nx#4361]
**Mod Version**
{
  "built": "2021-04-08T20:02:11+00:00",
  "ref": "autopilot",
  "sha": "cd98a0a89e6cc6c1682212b030801036a3a51d0f",
  "actor": "aguther",
  "event_name": "manual"
}

**Describe the bug**
A strange line appearing on the ND when on flightplan GUTB1P GRETA DCT VEMET/N0440F350 DCT EMRAD G599 TEKOT DCT AROBA AROB3V from NZCH to NTAA.
Range set to 320nm, on leg GRETA DCT VEMET. This is a huge dct (currently still 953nm out), and probably not the most sophisticated flight plan :-) I get a line from the bottom left of the ND to the middle top, connecting to the line going to VEMET. 

**To Reproduce**

1. Enter flight plan as per above
2. Verify in Plan mode that the route is ok.
3. Climb out on the SID and set the range to 320nm on the ND.

**Expected behavior**
A straight line to VEMET, with VEMET not being visible yet.

**Actual behavior**
A straight line ahead, which stops more or less at the 240nm mark, then a sharp left line disappearing off the bottom left side of the ND.

**References**
See screenshot
![Microsoft Flight Simulator Screenshot 2021 04 09 - 10 16 26 05](https://user-images.githubusercontent.com/81757587/114160924-5ab85d80-991f-11eb-90bc-d4c7078d38ec.png)

**Additional context**

Was this working before/when did the issue start occurring?
Unknown

Is this a problem in the vanilla unmodded game?
Not tested

Discord username (if different from GitHub): fva

**Comment by ferryvanaesch** [comment]
Also appearing on 160nm range now
![Microsoft Flight Simulator Screenshot 2021 04 09 - 10 38 12 100](https://user-images.githubusercontent.com/81757587/114161402-e92cdf00-991f-11eb-8a3c-025ee5750c6f.png)

**Comment by ferryvanaesch** [comment]
![Microsoft Flight Simulator Screenshot 2021 04 09 - 10 47 03 94](https://user-images.githubusercontent.com/81757587/114162697-42494280-9921-11eb-882b-b027c46b7e00.jpg)
![Microsoft Flight Simulator Screenshot 2021 04 09 - 10 47 01 22](https://user-images.githubusercontent.com/81757587/114162700-437a6f80-9921-11eb-8648-93abcc6b373c.jpg)

Can reproduce it in Plan mode as well, as long as you zoom out a lot. Once you get to VEMET the issue disappears.

**Comment by ferryvanaesch** [comment]
![Microsoft Flight Simulator Screenshot 2021 04 09 - 11 08 02 66](https://user-images.githubusercontent.com/81757587/114165016-e502c080-9923-11eb-8848-b3758d6ef7e6.png)

I was half expecting a proper CTD when crossing that point, but this happened instead.

**Comment by ferryvanaesch** [comment]
I'm also not convinced I'm on the right track now. Not sure if this is a Navigraph thing or whether I'm actually way off course...

![Navigraph](https://user-images.githubusercontent.com/81757587/114165707-be915500-9924-11eb-8aa5-b0efc1c9b679.jpg)

**Comment by ferryvanaesch** [comment]
That sudden realisation that I crossed the International Date Line at that point...

**Comment by ferryvanaesch** [comment]
![Microsoft Flight Simulator Screenshot 2021 04 09 - 15 47 45 29](https://user-images.githubusercontent.com/81757587/114202034-b817d300-994e-11eb-9ccd-245134563f14.png)

Happened again during descend.

**Comment by 2hwk** [comment]
Fixed by #4953 closing ☑️
