### ISSUE TITLE
Glareshield modeling

### ISSUE THREAD

**Issue by Sacha-Bombard** [flybywiresim/a32nx#4368]
Hello, I noticed that the Glareshield modeling was not very realistic due to its curvature at the ends. (see pictures)

**Describe the feature you'd like to see implemented**

I would like to see a realistic glareshield because it drives me crazy ahah.

**References**

Thanks to TriggerMaru for these photos.

![Image](https://forums.flightsimulator.com/uploads/default/original/3X/8/1/818c9ab5b24e8a7cb9069efbda7acbb2edd3e939.png)
![Image](https://forums.flightsimulator.com/uploads/default/original/3X/3/0/30de7572ab828a662e97f9cc33b932bb3c0b5760.png)
![Image](https://forums.flightsimulator.com/uploads/default/original/3X/2/2/225bb3659a275fcf1fa9204964b700dd70f556a3.png)
![Image](https://forums.flightsimulator.com/uploads/default/original/3X/4/0/4059f5784599dd0511d92a3f7d45cea6fc572f9b.jpeg)

Discord username (if different from GitHub):
Sacha#5166

Thanks in advance !

**Comment by TLSY2** [comment]
The IRL A320 cockpit looks a bit different with the textures and colour of the plastic. But im sure you guys will get there.

**Comment by Benjozork** [comment]
@TLSY2 Please keep In mind the textures are made with feedback from IRL pilots and from pictures taken by the team inside a real cockpit. There are many variations of colors and different manufacturers of parts, which cause variations in what you see.

**Comment by TLSY2** [comment]
> eedback from IRL pilots and from pictures taken by the te

I dont doubt that, Its even the graphics because its a game but i mean the real plane looks like a bit more smooth and clear if you get me. But we are thankful for what we have.

**Comment by Benjozork** [comment]
Again - there are airplanes which are older, newer, everything in between. Different color specifications for parts. Different manufacturers with slight visual changes between them.

It's like if you search A320 cockpit takeoff on YouTube - a lot of people will tell you our engine sounds are very different - but that's because we model a very specific engine which has a very particular sound that differs from most jet engines.

**Comment by Sacha-Bombard** [comment]
Please discuss on another place this is not the point of this issue. 
Thanks

**Comment by TLSY2** [comment]
> Again - there are airplanes which are older, newer, everything in between. Different color specifications for parts. Different manufacturers with slight visual changes between them. The one we used is probably not the same one as the one you compared with.
> 
> It's like if you search A320 cockpit takeoff on YouTube - a lot of people will tell you our engine sounds are very different - but that's because we model a very specific engine which has a very particular sound that differs from most jet engines.

I agree.

**Comment by Speedmarque** [comment]
It's the 3D geometry, not the textures that really *triggers* me and a few others, as it's constantly visible when in forward view. Whoever did the 3D scanning at Asobo clearly didn't do it correctly, as the glareshield in the real aircraft (CEO and NEO) doesn't have this kind of slanted look.

Source: Northwest608 @ MSFS Forums
![image](https://user-images.githubusercontent.com/31601021/115243816-6bff3680-a177-11eb-8b26-de00bba97793.png)

**Comment by TLSY2** [comment]
Anyway, for this to be achieved by the devs, they need the Blendrrr mporter xporter.

**Comment by Sacha-Bombard** [comment]
Up

**Comment by Benjozork** [comment]
Please do not reply with "Up" or "Bump", it brings nothing to the discussion.

This will be done when it's possible to do so.

**Comment by tracernz** [comment]
> Please do not reply with "Up" or "Bump", it brings nothing to the discussion and issues are not sorted by activity.

Bump. 🤣

**Comment by Sacha-Bombard** [comment]
How can I help you to solve this glareshield modeling ?

**Comment by sidnov** [comment]
Duplicate of #2795
