### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by h20genie** [flybywiresim/a32nx#437]
**Mod Version**
<Version 0.2.0>

**Describe the bug**
<GPWS Callouts skip everything between 100 and 30. GPWS Does "30"... "Retard" then "5" when wheels are already on the ground. TOGA fluctuates its range between 90%-95% on take off when AT/THR is enabled as well>

**To Reproduce**
<ILS Landing or Localizer (maybe use assisted landing)>

<Conducted assisted ILS landing with LOC at KLAS>
1. Set speed 155 for landing
2. TOGA Bounces between 90-95% when using TOGA
3.

**Expected behavior**
<GPWS Should do 2,500 - 1,000 , 500, 400, 300, 200, 100, 50-40-30-20-10 - Retard (continue until wheels hit ground). TOGA should be stable at about 94-95% thrust. acceleration needs to be increased slightly>

**Actual behavior**
<GPWS was inaccurate on callouts and did not use all altitudes. TOGA acceleration is too slow. AT/THR issue appears at about 85KTS >

**References**

**Additional context**

**Comment by Benjozork** [comment]
> <GPWS Callouts skip everything between 100 and 30. GPWS Does "30"... "Retard" then "5" when wheels are already on the ground. TOGA fluctuates its range between 90%-95% on take off when AT/THR is enabled as well>

1. Those are two different bug reports.

2. For the first, this behaviour has not been reproduced in-sim. Could you provide a video ? For the second, as far as we know that's an Asobo bug and we cannot fix it for now 🙁

**Comment by wpine215** [comment]
Please re-submit, and have individual issues correspond to a single bug in the aircraft. Also, please include a title next time.
