### ISSUE TITLE
Pilot Weather Radar Not Showing - Until Display Option Changed Once

### ISSUE THREAD

**Issue by MjrIncident** [flybywiresim/a32nx#4374]
**Mod Version**
Release Version:   e049d43 - Dev Version
{
  "built": "2021-04-09T16:57:59+00:00",
  "ref": "master",
  "sha": "e049d433cbb5d8c53ce083a4631626309c13c86a",
  "actor": "pepperoni505",
  "event_name": "manual"
}

**Describe the bug**
Many CD starts with previous versions of your MOD. <3 it!
Every flight, my (pilots) display, does not show the radar.
It shows instantly for the co-pilot, but I have to select a different mode (e.g. Plan), and then I
see half of the weather across the top 50% of the display, and then when I select another display mode it renders fully.

**To Reproduce**
1. Launch Dev aircraft cold & dark.
2. Sequence the startup procedures including lower console configurations.
3. Switch radar on and 2way switch to display 1 or 2.

**Expected behavior**
To see weather radar results on/off on both screens instantly it is turned on/off.

**Actual behavior**
Every flight, my (pilots) display, does not show the weather radar, but it shows instantly for the co-pilot display.

**References**
![Screenshot_a](https://user-images.githubusercontent.com/72098504/114254724-f641e080-99a8-11eb-967d-2f8f945c1d61.png)

**Additional context**
It has always done this for me. Every version for months tbh.

Was this working before/when did the issue start occurring?
Don't know. I have never seen it working.
Is this a problem in the vanilla unmodded game?
No.

Discord username: MAJOR INCIDENT#8950

**Comment by MisterChocker** [comment]
Do you have any other mods/addons installed or in the community folder?

**Comment by MjrIncident** [comment]
Yes. some of the latest liveries (approx15), Gatwick, Fueltruck skin,EasyJetGroundhandling.
I should test with no plugins/addons/liveries - just the FBW default one?

**Comment by MjrIncident** [comment]
Tested as you profiled - i.e. no extras and it doesn't do it! Outshtanding sir! Apologies for wasting your time on this.
