### ISSUE TITLE
After fuelling by flypad the Aircraft cannot be moved

### ISSUE THREAD

**Issue by uzytkownik** [flybywiresim/a32nx#4375]
**Mod Version**
Development e049d43

**Describe the bug**
If I fuel using flypad the aircraft cannot be moved from gate (either by pushback or engines).

**To Reproduce**
1. Set fuel to 0 during initialization
2. Fuel at the gate
3. Try to request pushback or rev the jet engines

**Expected behavior**
Airplane moves away from gate

**Actual behavior**
No error/warning is displayed but the aircraft does not move

**References**

**Additional context**
Was this working before/when did the issue start occurring?

It never worked for me.

Is this a problem in the vanilla unmodded game?

Not applicable to vanilla.

**Comment by lionomega** [comment]
same here

**Comment by pilot204** [comment]
I have the same problem. When the plane was integrated into the OSOBO, everything was fine. And when it became a separate aircraft, it does not move with the help of a towing vehicle and at full jet thrust.

**Comment by ZigTag** [comment]
Have you guys tried to see if you have active pause mode enabled?

**Comment by uzytkownik** [comment]
Yes. The engine spinned up based on throttle and the push back truck (sorry - don't know its name) was responding to push left/right. Also I was able to turn on the engines after push back did not succeeded.

**Comment by uzytkownik** [comment]
@MisterChocker I think tag 'Waiting For Response' should be removed now?

**Comment by scoopscode** [comment]
@uzytkownik Someone had an issue like this not too long ago and they were way over the MTOW, I just wanna make sure you aren't also over the MTOW to the point where the aircraft can't move.

**Comment by sidnov** [comment]
Unable to reproduce on the latest dev version, feel free to (re)open with fresh details if it still occurs
