### ISSUE TITLE
ND ROSE mode issues with scale and arcs

### ISSUE THREAD

**Issue by ccapilot** [flybywiresim/a32nx#4377]
**Mod Version**
"built": "2021-04-10T07:26:10+00:00"

**Describe the bug**
ND scale while in ROSE mode, should be half the selected scale, so if scale is selected as 10, the inner circle on ND ROSE NAV should be 2.5 and the full circle should be 5.
Also the inner circle (1/4 of the selected range) should be dashed circle and not full circle.

**To Reproduce**
1. select ROSE mode on ND and look the scales and the solid circle...
2. 
3.

**Expected behavior**
while on ROSE mode (either LS, VOR or NAV) should have 1/4 of the selected scale the middle circle and 1/2 selected scale the outer circle. also middle circle should be dashed. 

**Actual behavior**
while on ROSE mode, middle circle is full line and is 1/2 selected scale while full circle is 1 selected scale (instead on 1/4 and 1/2 respectively).

**References**
enclosing some pics for your reference:
![22ecc1f5-3544-40f4-a503-f325480ddf24](https://user-images.githubusercontent.com/71601106/114263881-fff33480-99f8-11eb-894e-0963d38c5d4c.JPG)
![59f2b565-2308-4e4d-a119-fccd3d984e08](https://user-images.githubusercontent.com/71601106/114263885-041f5200-99f9-11eb-930f-5bcf88916563.JPG)
![2322c29a-2f08-44d3-afaf-f5eb0e066fb8](https://user-images.githubusercontent.com/71601106/114263889-071a4280-99f9-11eb-990a-4112c2b2b61c.JPG)
![069836f2-f5e0-4c70-9e04-f35ea72932aa](https://user-images.githubusercontent.com/71601106/114263892-097c9c80-99f9-11eb-98a7-7c3a680e0ec6.JPG)
![96152fe9-37fd-41de-89bd-2baee21010aa](https://user-images.githubusercontent.com/71601106/114263898-0ed9e700-99f9-11eb-8ebb-c9c9f0be2566.JPG)
![dda768ba-33c0-448d-80ee-55d0e5608c29](https://user-images.githubusercontent.com/71601106/114263900-126d6e00-99f9-11eb-84f1-12692cda77f4.JPG)

**Additional context**

Was this working before/when did the issue start occurring?
YES

Is this a problem in the vanilla unmodded game?
I don't know.

Discord username (if different from GitHub):

**Comment by tracernz** [comment]
Yes, I have a branch that will soon become a PR and fix this. See #4164 for other issues.

**Comment by tracernz** [comment]
Fixed some time ago when we merged the FBW ND.
