### ISSUE TITLE
Rudder in Experimental

### ISSUE THREAD

**Issue by TLSY2** [flybywiresim/a32nx#4378]
**Is your feature request related to a problem? Please describe.**

When i land the plane starts drifting off the runway because the rudder moves too slow (experimental version) This happens because my joystick doesnt have rudder option and i dont have rudder pedals and i use keyboard.

**Describe the feature you'd like to see implemented**

The rudder speed to move back to original like in dev and stable
or
A option to adjust speed

**References**

In the real aircraft the rudder can move fast.

**Additional context**

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by aguther** [comment]
Which keys are you using?

**Comment by TLSY2** [comment]
> Which keys are you using?

num locked and 0 for left rudder, enter right rudder + recenter and . brake. And not even that, I noticed the autopilot when it autolands the rudder moves way too slow and it almost exits the runway.

**Comment by aguther** [comment]
Ok, thank you for the info.

In regards to Autoland this seems to be a rare behavior that you describe. I did a lot of tests with crosswind and from other feedback this is at least not a common issue. Some say even the opposite that it's a bit too aggressive in decrab.

Let us just not mix those things. Feel free to open a new issue about the Autoland and please provide Video / Screenshots or at best an FDR file from the work folder that shows the specific landing.

**Comment by TLSY2** [comment]
thats fine, no need i dont care about autoland, my issue is the rudder speed, because now with experimental its way too sensitive for keyboard, i mean any wind above 3 knots cant land, feel free to try.

**Comment by aguther** [comment]
Ok, what is now the problem? Too fast or too slow? In you last comment you wrote it's way too sensitive and in the original post you write it moves too slow...

**Comment by aguther** [comment]
I've added a configuration parameters that allows the configuration of the key events. The example shows default config for all flight controls. You can also skip the ones you don't wont to configure, they are then using defaults.

Create/open file "ModelConfiguration.ini" in work folder and add the following section:
```
[FLIGHT_CONTROLS]
KEY_CHANGE_AILERON = 0.02
KEY_CHANGE_ELEVATOR = 0.02
KEY_CHANGE_RUDDER = 0.02
```

**Comment by TLSY2** [comment]
> Ok, what is now the problem? Too fast or too slow? In you last comment you wrote it's way too sensitive and in the original post you write it moves too slow...

oh my god, i just realized how bad my English is even tho I live in London. I meant too slow.

**Comment by TLSY2** [comment]
> I've added a configuration parameters that allows the configuration of the key events. The example shows default config for all flight controls. You can also skip the ones you don't wont to configure, they are then using defaults.
> 
> Create/open file "ModelConfiguration.ini" in work folder and add the following section:
> 
> ```
> [FLIGHT_CONTROLS]
> KEY_CHANGE_AILERON = 0.02
> KEY_CHANGE_ELEVATOR = 0.02
> KEY_CHANGE_RUDDER = 0.02
> ```

could you be more specific to which folder? And the location. I cant find a modelconfig.ini in your flybywire mod folder, ive looked everywhere, and by create, if i was to create where?

**Comment by TLSY2** [comment]
Hi, Im not sure if you are getting my replies... I dont understand where to add that code and how to create that... Can you please help me, i saw you made for me a lot of code it would be a shame not to be able to use it.... 

So, where do i find that folder and where do i put that code?

Thanks very much!

**Comment by Benjozork** [comment]
@TLSY2 The "work" folder is located here for me, for exmaple:

`C:\Users\<user>\AppData\Roaming\Microsoft Flight Simulator\Packages\a32nx\work`

be careful - it's NOT in the Community package of the a32nx!

**Comment by TLSY2** [comment]
> @TLSY2 The "work" folder is located here for me, for example:
> 
> `C:\Users\<user>\AppData\Roaming\Microsoft Flight Simulator\Packages\a32nx\work`
> 
> be careful - it's NOT in the Community package of the a32nx!

Thanks, I found it. Next thing, if i create that folder, what should i do it on? Notepad?

**Comment by lukecologne** [comment]
@TLSY2 Watch out, the correct folder since the hard-fork is 
`C:\Users\<user>\AppData\Roaming\Microsoft Flight Simulator\Packages\flybywire-aircraft-a320-neo\work`
and NOT a32nx

**Comment by Benjozork** [comment]
You have to create a **file** called `ModelConfiguration.ini`. What you make it with doesn't really matter

**Comment by TLSY2** [comment]
> You have to create a **file** called `ModelConfiguration.ini`. What you make it with doesn't really matter

Ok, so notepad will work, Thanks for the help!

**Comment by TLSY2** [comment]
I have made the file but it doesnt seem to do anything to change the sensitivity. It still is 50 buttons to press to get it to work.
