### ISSUE TITLE
Impossible to correctly program arrival with no STAR

### ISSUE THREAD

**Issue by evilstiefel** [flybywiresim/a32nx#4379]
**Mod Version**

{
  "built": "2021-04-08T20:02:11+00:00",
  "ref": "autopilot",
  "sha": "cd98a0a89e6cc6c1682212b030801036a3a51d0f",
  "actor": "aguther",
  "event_name": "manual"
}

**Describe the bug**
When trying to program an arrival into an airport like EDDB, which has no traditional STARs, but just transitions, the FMS will not let me create an arrival without a VIA.

**To Reproduce**

1. Init a flight e.g. `EDDP/EDDB`
2. Select FPL and add an arrival
3. Select `OGBER25L`
4. Click on VIAS and select `NO VIAS`
5. Click insert

**Expected behavior**
Just the transition should be added, no VIA

**Actual behavior**
The transition is added, but waypoints for `VIA ATGUP` are also inserted into the arrival

**References**
MCDU settings
![image](https://user-images.githubusercontent.com/8029370/114267777-f91af080-99fd-11eb-924f-c1ff679d4a21.png)

Resulting FPL
![image](https://user-images.githubusercontent.com/8029370/114267792-16e85580-99fe-11eb-8aba-b9f17308f83d.png)

Expected FPL
![image](https://user-images.githubusercontent.com/8029370/114267797-223b8100-99fe-11eb-8674-6a9a9ce19b66.png)

**Additional context**
It seems like a VIA is forced into the arrival, since I can choose another VIA and not get ATGUP in my FPL. No vias is ignored.

Discord username (if different from GitHub): steffen#7300

**Comment by tellurics** [comment]
Duplicate. Known issue.

**Comment by evilstiefel** [comment]
Mind linking it for reference?

**Comment by aguther** [comment]
Please link the duplicate and close the issue.

**Comment by tellurics** [comment]
I can't close it.  Duplicate of #3026

**Comment by evilstiefel** [comment]
Closed
