### ISSUE TITLE
Idle thrust too weak for taxi

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#4380]
**Mod Version**

Experimental + FBW

**Describe the bug**

I recognise, that the IDLE Thrust is reduced after the last updates in the past. So the Plane decelerates while taxiing @ around 15-20 knots with moderate payload for short haul. IRL the plane still slowly accelerates (slow, but it will) with Thrust idle. e.g. when you taxi @ 20kts, the plane is still capable to hold this speed with idle thrust. You even have to touch the brakes a little. In the recent version the plane slowly decelerates (6.5t fuel, 1/3 payload, dry taxiway, no slope)

**To Reproduce**

1.cold&dark start
2. try to taxi with idle thrust
3. watch GS decreasing 

**Expected behavior**

Idle Thrust should be high enough to taxi without deceleration (while @ normal taxi speed) IRL you even have to brake a little. 
 
**Actual behavior**

Idle Thrust is not powerful enough

**References**

not needed

**Additional context**

-
Was this working before/when did the issue start occurring?
yes, it was better before the update that brings us the EGT-indication bug (~700C° with engines off etc)...
Is this a problem in the vanilla unmodded game?
no

Discord username (if different from GitHub):
-

**Comment by aguther** [comment]
A new flight model is in the works that will improve the situation. It will also feature distinct flap/slat position for 1 and 1+F.

**Comment by andrejetcat** [comment]
Thank you for your answer. I would really try it out! How can I test it?

**Comment by aguther** [comment]
Instructions are in the PR how to download the artifact, but here you go:
https://github.com/flybywiresim/a32nx/pull/4220/checks?check_run_id=2316330566

On the right side you find "Artifacts (1)" where you can download it.

**Comment by aguther** [comment]
The behavior should be improved now. If it's not satisfying please reopen the issue.
