### ISSUE TITLE
No sounds inside cockpit

### ISSUE THREAD

**Issue by petepawn64** [flybywiresim/a32nx#4382]
**Mod Version**

ceccd03 dev version

**Describe the bug**
In the cockpit there are absolutely so sounds, no click sound from buttons, no sound of APU but ATC sounds works and outside the plane ( spotview) you can hear noise of the airport

**To Reproduce**
Normal start

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by petepawn64** [comment]
And there is no plane sound outside - engines running but completely silent. Environment friendly..

**Comment by kiwi2021** [comment]
Perform a complete fresh install of the A32NX. Delete the aircraft folder from your Community folder and reinstall via the installer.

**Comment by petepawn64** [comment]
Thanks, I'll try that.

**Comment by petepawn64** [comment]
It worked.
