### ISSUE TITLE
bad engines performance

### ISSUE THREAD

**Issue by naf125** [flybywiresim/a32nx#4384]
**Mod Version**
Experimental a2ffd1f

**Describe the bug**
unable to climb to a decent cruiselevel

**To Reproduce**
1. I load the plane (fuel and pax) via simbrief
2. I read normal values
3. I start the plane and depart from an airport

**Expected behavior**
In the FMS PRG page an rec max of FL390 is showing

**Actual behavior**
The plane is unable to climb further then roughly FL300. This has to be done via step climbs like a normal 777 with large amounts of fuel on board. A straight climb is almost impossible due the decrease of the speed. Many times i need to maintain MAN TOGO to maintaine the cruiselevel FL300 

Discord username (if different from GitHub): Peter van de Witte#9546

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by tracernz** [comment]
What payloads and fuel loads are you using?

**Comment by naf125** [comment]
Current flight at Vatsim. I need to maintain FL300 to keep mach .76

 

REC max at MFS is FL390.

 

Peter

**Comment by naf125** [comment]
https://forums.flightsimulator.com/t/airbus-a320-neo-lacking-climb-performance-after-update/326847/86

 

I also tried this trick. Not successful.

**Comment by naf125** [comment]
current attitude
![attitude](https://user-images.githubusercontent.com/82272795/114273247-ce826500-9a08-11eb-8f48-639b134f6cc7.PNG)

**Comment by naf125** [comment]
![fms](https://user-images.githubusercontent.com/82272795/114273270-f07be780-9a08-11eb-8828-6c1fd8551c14.PNG)
FMS

**Comment by naf125** [comment]
Current fuel status

![weight and fuel](https://user-images.githubusercontent.com/82272795/114273313-11dcd380-9a09-11eb-8aac-4d660b178368.PNG)

**Comment by tshomas** [comment]
What flight model are you using in MSFS settings menu? You should be on modern for the sim to work with newly created mods?

**Comment by naf125** [comment]
Asobo_A320_NEO-Martinair2

**Comment by tshomas** [comment]
Flight model as in the MSFS settings menu, in the simulator itself?

![image](https://user-images.githubusercontent.com/74841560/114273513-34bfb580-9a12-11eb-9ab4-2585be7c1213.png)

**Comment by naf125** [comment]
![current](https://user-images.githubusercontent.com/82272795/114273989-f7f0c000-9a0b-11eb-94e3-a257517fdb74.jpg)

**Comment by Benjozork** [comment]
We only support the Modern flight model. The Legacy model is only for compatibility for FSX imported aircraft. You will get significantly less realistic behaviour and many issue using it,.

**Comment by naf125** [comment]
ok, wasn't aware of that. Then I will look for it. Because this is an amazing aircraft.

**Comment by Benjozork** [comment]
You can switch using the arrows on each side of the "LEGACY" selection

**Comment by naf125** [comment]
will do that. I haven't imported any plane from FSX. So no use to have this setting for me. Thank you for the quick support

**Comment by aguther** [comment]
I close it for now, feel free to reopen it it's not fixed with modern flight model.
