### ISSUE TITLE
Experimental: MCDU: FPLN Page Showing ETE Instead of ETA

### ISSUE THREAD

**Issue by tshomas** [flybywiresim/a32nx#4389]
**Mod Version**
{
  "built": "2021-04-10T14:14:56+00:00",
  "ref": "autopilot",
  "sha": "05a0c08565d51d846a06cebbc0432087b83f7e27",
  "actor": "tracernz",
  "event_name": "manual"
}

**Describe the bug**
FPLN page is maintaining ETE airborne, instead of switching to ETA as per expected. Dev behaviour is correct. ThatRedMelon suggested possibly since the throttle variables have changed in experimental, it might not be transitioning to flight.

**To Reproduce**
1. Plan aircraft as normal on ground, see ETE on the ground.
2. Once airborne, flight times remain as ETE, do not switch to ETA. Including bottom line time of expected arrival.

**Expected behavior**
ETE to switch to ETA once airborne, using the ETE times and current sim Z time.

**Actual behavior**
ETE remains.

**Additional**
Seen by myself in all last few days, two users reported in #help tonight, with their images attached below.

**References**

User images:

![unknown](https://user-images.githubusercontent.com/74841560/114284151-e2988780-9a45-11eb-958e-84e181405c8b.png)
Discord: oddspbriquet

![20210410_120529](https://user-images.githubusercontent.com/74841560/114284154-e5937800-9a45-11eb-96de-e192db7790fe.jpg)
Discord: Gilbnx

ThatRedMelon's code snippet where possible error may lie

![Screenshot_20210410-203854__01](https://user-images.githubusercontent.com/74841560/114284162-f217d080-9a45-11eb-8c76-2e2aa352d7c0.jpg)

Was this working before/when did the issue start occurring?
Yes, I saw it first on the 07/04/2021, seen it since as well, user reports on 10/04/2021.

Is this a problem in the vanilla unmodded game?
N/A

Discord username (if different from GitHub):
Shomas

**Comment by Valastiri** [comment]
Just chiming in, on the ground with development version. 

Current UTC + fpln view of time. 

![image](https://user-images.githubusercontent.com/1619968/114286265-befa2f00-9a8f-11eb-8595-2577a4fda176.png)

**Comment by tracernz** [comment]
The code snippet above is from master branch and not relevant here. The actual code on experimental is:
https://github.com/flybywiresim/a32nx/blob/autopilot/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js#L15
```js
const isFlying = SimVar.GetSimVarValue("L:A32NX_FWC_FLIGHT_PHASE:1", "Enum") === 5;
```
Should be fixed in https://github.com/flybywiresim/a32nx/commit/2becbd360389055c8bbef1adc79001117e86f448

**Comment by tshomas** [comment]
Cheers Tracer! I’ll close this as it’s been committed, awesome job 👍
