### ISSUE TITLE
Controls (x and y axes) sensitive since hard fork

### ISSUE THREAD

**Issue by Mermaid313** [flybywiresim/a32nx#4394]
**Mod Version**

**Describe the bug**

The inputs (x and y axes) are super sensitive.

**To Reproduce**

1. Fly the A320nx manually. 
2. Espesically if you take off or land (retard) you'll feel it. Descreasing the sensitivity in the options doesn't solve this problem. 
3.

**Expected behavior**

Smoothly go up or retard.

**Actual behavior**

Now a tail strike is quickly possible. 

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by aguther** [comment]
You do not provide and info on the version you are using neither you provided any evidence about you issue. Sorry this way it is impossible to investigate further. Add those information otherwise this bug will be closed.

**Comment by hotshotp** [comment]
Since a32nx is now standalone your settings for it have to be redone - probably why it's sensitive

**Comment by TLSY2** [comment]
I noticed this issue too, its just way too fast. Like i have to barely move my joystick holding it from the lowest point to move it slowly, and if you move it all the way it rolls like a fighter jet doing flips.

**Comment by TLSY2** [comment]
> Since a32nx is now standalone your settings for it have to be redone - probably why it's sensitive

How? By adjusting the sensitivity in game settings he says it doesnt change anything and I noticed too the same problem, Is there a cfg page somewhere with sensitivity?

**Comment by aguther** [comment]
> > Since a32nx is now standalone your settings for it have to be redone - probably why it's sensitive
> 
> How? By adjusting the sensitivity in game settings he says it doesnt change anything and I noticed too the same problem, Is there a cfg page somewhere with sensitivity?

Really?

I've added based on your feature request a way to configure the keys. For all other: use the sensitivity settings from the sim.
