### ISSUE TITLE
Lost heading bug after this update

### ISSUE THREAD

**Issue by DMullert** [flybywiresim/a32nx#44]
Hey gang!  Anyone else lost the heading bug after this update?

Thanks.  Dennis

**Comment by noga-aviator** [comment]
we haven't touched at that i think ? What is the heading bug in more details ?

**Comment by DMullert** [comment]
OK - I just reverted to original state and it looks like the heading bug is there when you select the ARC and NAV, but it's missing in the LS and VOR modes.  The heading bug is the little diamond that moves around the compass when you change your heading.  It points to your heading to let you know what your heading setting is.  Hope this helps.  Dennis

**Comment by wpine215** [comment]
Labeling issue as enhancement and leaving it open since it's an issue with the default A320neo that we can eventually fix.

**Comment by PCGamesF1Tech** [comment]
The heading bug only appears in HDG mode (pull HDG...).
The 747 e.g. has it's heading bug always visible but the AP doesn't follow it unless you switch to heading select mode (in LNAV you can turn it around as you like, the AP follows the FMS nav track)

**Comment by NathanInnes** [comment]
Any update about how this issue went? Is it still an issue?

**Comment by hotshotp** [comment]
Not an issue anymore
