### ISSUE TITLE
Thrust Lever / Speedbreake Lever / Flaps Lever don´t move / No Lever Value in the FlyPad 

### ISSUE THREAD

**Issue by robro8** [flybywiresim/a32nx#4400]
**Mod Version**

current Experimental Version download 11.04.21 / 13:00 (4a4afb1), installed with the Installer

**Describe the bug**

since the latest version the Thrust Lerver, Speedbreak Lever / Flaps Lever no longer move. But they still work when you look outside.  the engines also run up (see ECAM) and the aircraft accelerates (see outside photo in the appendix). Reverse thrust also works in the fly pad, with throttle calibration no current value is displayed (see photo in the appendix). I use the Bravo Throttle Quadrant. I tried another throttle myself, but I couldn't move the thrust lever / speedbreak lever / flaps lever completely without the throttle, for example with the mouse. And the rudders are overly sensitive. is not due to my attitudes, they have not changed. I have already done a completely new fresh installation with the installer 

**To Reproduce**

1. Start a new flight from cold and dark or in Take Off config at LEBL or whatever 
2.look at the Throttle Lever / Flap Lever / Speedbreak Lever / FlyPad
3.

**Expected behavior**

moving Levers and a value in the FlyPad

**Actual behavior**

Levers dont move in the 3D Cockpit / no Value in the Flypad

**References**

**Additional context**

Was this working before/when did the issue start occurring?
before the latest version everything went great 
Is this a problem in the vanilla unmodded game?
not testet, default A 320 is not installed, only FBW A32NX installed

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**
![1](https://user-images.githubusercontent.com/59294315/114303278-96912580-9acd-11eb-9247-14077fc2c509.PNG)
![2](https://user-images.githubusercontent.com/59294315/114303282-9b55d980-9acd-11eb-96f6-c77381def80f.PNG)
![3](https://user-images.githubusercontent.com/59294315/114303287-9e50ca00-9acd-11eb-9fe0-c3904fb29721.PNG)

**Comment by roxter69** [comment]
I to have the same problem,was fine last night,experimental latest version

**Comment by slebr** [comment]
Same - also AP Nav/Clb don't work after IRS aligned and FD on

**Comment by Watsi01** [comment]
Confirmed.

**Comment by Watsi01** [comment]
Should be fixed in the next update.

**Comment by Saschl** [comment]
Is fixed, give the build a few minutes. Issue can be closed though.

**Comment by robro8** [comment]
thank you gyus..
