### ISSUE TITLE
While using EFB Auto pilot does not follow route.

### ISSUE THREAD

**Issue by 1golem1** [flybywiresim/a32nx#4401]
I am using the DEV version and recently I noticed that every time I am using the EFB to calculate the TOD, the ap stops following the route and I have to disengage the ap and return manually to the route and only than the ap can be activated.

**Comment by Benjozork** [comment]
Please follow the template.

This is most likely due to a clash between the number inputs on your numpad also being bound to aileron controls.

You can either use the number row, unbind aileron controls or wait for Asobo to disable those keybinds when interacting with a text field.
