### ISSUE TITLE
Crash to desktop after a few seconds when loading world map

### ISSUE THREAD

**Issue by LEDFlighter** [flybywiresim/a32nx#4407]
**Mod Version**
{
  "built": "2021-04-11T17:49:02+00:00",
  "ref": "master",
  "sha": "6226809131ec6ec98313262b5b3dd969924fbd14",
  "actor": "ko-zone",
  "event_name": "manual"
}

**Describe the bug**
The sim crashes to desktop every time after loading world map, no matter which aircraft is selected.

**To Reproduce**
1. Install newest development-version with the installer
2. Start up the simulator
3. Go to "world map" and wait a few seconds

**Expected behavior**
The sim should not crash to desktop after loading the world map.

**Actual behavior**
The sim crashes to desktop after a few seconds when loading world map.

**References**
No references.

**Additional context**
Without installed A32NX, the sim runs normal and fine, but with latest development-version it crashes to desktop when loading the world map.

Was this working before/when did the issue start occurring?
It was working before, the issue started occuring at the development-version a few days ago.

Is this a problem in the vanilla unmodded game?
No.

Discord username (if different from GitHub): LEDFlighter#7712

**Comment by MisterChocker** [comment]
Sounds like a mod conflict, do you have any other addons installed? or anything else in your community folder?

**Comment by LEDFlighter** [comment]
> 
> 
> Sounds like a mod conflict, do you have any other addons installed? or anything else in your community folder?

I tried it with different setups to figure out what causes the CTDs, in one had only the A32NX in my community-folder and it crashed, I removed the A32NX and it worked fine!

**Comment by MisterChocker** [comment]
have your checked in with out help channel on discord? We have some pretty competent people helping in there.

**Comment by LEDFlighter** [comment]
> 
> 
> have your checked in with out help channel on discord? We have some pretty competent people helping in there.

No, not yet, I am trying to find a solution to the problem by copying different packages into my community-folder and try again...

**Comment by LEDFlighter** [comment]
> 
> 
> Sounds like a mod conflict, do you have any other addons installed? or anything else in your community folder?

Okay, we can close this now, because it is mod-conflict and not a problem of the A32NX, but I haven't figured out yet which mod causes the crashes...
