### ISSUE TITLE
pas de capteur loc à l'approche

### ISSUE THREAD

**Issue by snypa972** [flybywiresim/a32nx#4409]
**Mod Version**
Development 6226809

**Describe the bug**
les capteurs LOC ne s'affiche pas à l'approche (même a 2000ft) pourtant les commandes "APPR" et "LS" sont bien activées
(voir capture d'écran en pièce jointe)

**To Reproduce**

1. phase d'approche activé
2. pression sur le bouton "LS"
3. et bouton "APPR" activé

**Expected behavior**
affichage des capteurs LOC

**Actual behavior**
aucun affichage des capteurs LOC

**References**
sur mes captures d'écrans j'ai entouré en rose mes actions.

**Additional context**

Was this working before/when did the issue start occurring?
oui, mais seulement sur la version stable

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

![bug loc](https://user-images.githubusercontent.com/81974626/114335882-b3544a00-9b1b-11eb-8525-a1a68ccb91f7.jpg)
![Inked20210411200211_1_LI](https://user-images.githubusercontent.com/81974626/114335887-b4857700-9b1b-11eb-8419-07bcc574d022.jpg)

**Comment by Benjozork** [comment]
Bonjour, présentement dans MSFS il y a un bug avec l'auto-tuning des ILS. Il arrive souvent que lorsqu'une apprroche ILS est séléctionnée dans le MCDU, le sim ne vas pas la propager vers les radios ILS. Il faut alors manuellement entrer les fréquences ILS dans la page RADIO NAV du MCDU.

**Comment by PatriceCesson** [comment]
Perso je vérifie toujours les données ILS dans la page RAD/NAV du MCDU. En général, si le plan de vol est bien suivi, elles sont correctes. Sinon je les insère manuellement.

**Comment by davidwalschots** [comment]
請只用英文，我們不會讀法文。
