### ISSUE TITLE
ADD wing movements, IMPROVE engine rotation

### ISSUE THREAD

**Issue by lalloretpilou** [flybywiresim/a32nx#4410]
Today, the wings are frozen and the engine effects are invisible.

**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**
· During taxiing, take-off and all other phases of flight, the wings have physical constraints and therefore create movements. On the video we can clearly see the movements of the wings.
For engines, it would be necessary to improve the rotation of the engines on ignition and improve the effect when changing the engine speed (see video

**References**
https://www.youtube.com/watch?v=XfhQu7GEQZM&t=476s

**Comment by Benjozork** [comment]
Might wanna remove that last line

**Comment by MisterChocker** [comment]
Wing movement is already implemented.

**Comment by lalloretpilou** [comment]
therefore it should be improved and optimized. Because the movements are not very realistic.

**Comment by MisterChocker** [comment]
Please provide accurate references.

**Comment by MisterChocker** [comment]
Closing since no response from OP
