### ISSUE TITLE
Fuel flow 0 after disconnecting Autopilot

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#4412]
**Mod Version**

Experimental FBW 2a9920b

**Describe the bug**

I was on the ILS Rwy 27L @ EGLL. I disconnect the AP @ around 1000ft AGL, when I notice the fuel flow instantly drop to 0 on the upper ECAM.

**To Reproduce**

1.cold & dark start
2.commence a normal flight to any Airport
3.look @ fuel flow when you disconnect the AP on final Approach.

**Expected behavior**

Fuel flow should not affected + fuel flow could not be 0 if engines running normally

**Actual behavior**

fuel flow drop to 0 after AP disconnect on final

**References**

![fuel_flow_bug](https://user-images.githubusercontent.com/72918017/114402409-14bffb80-9ba4-11eb-813c-c519fc36ebc2.jpg)

**Additional context**

Was this working before/when did the issue start occurring?
i can remember, yes
Is this a problem in the vanilla unmodded game?
no

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment]
cc. @aguther @Taz5150

**Comment by MisterChocker** [comment]
Do you have a FDR file of that flight?
it can be found here %LOCALAPPDATA%\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalState\packages\flybywire-aircraft-a320-neo\work

**Comment by andrejetcat** [comment]
Yes, i can found the FDR data, but i can´t open it. 
By the way, the data has a size of 200MB! Is it a kind of flight recorder-data? Is there an option to turn off this flight recording to safe dataspace?

**Comment by MisterChocker** [comment]
If possible please send me the file so we can check what happened.

Yes it is a Flight Data Recorder, and yes you can disable it. You can also limit the amount of files and the max amount for each file.
This can be done in the config 

This is the content of the config file, to turn it off, set `enabled = false`
```
[flight_data_recorder]
enabled = true
maximum_number_of_files = 15
maximum_number_of_entries_per_file = 864000
```

**Comment by andrejetcat** [comment]
okay, thank you for this tip! Does it have a effect on performance?
I don´t know how to send it to you because of its size. can I load it up somewhere?

**Comment by MisterChocker** [comment]
Yes you can upload it to e.g. google drive.
No there is no significant performance impact.

**Comment by andrejetcat** [comment]
https://drive.google.com/file/d/1P-viLANhng0Htm5AD_fvR8Sg8968rI9L/view?usp=sharing

I hope it works

**Comment by kmoze2001** [comment]
I think it's fascinating that it's got an FDR in the first place!  Though I can see the troubleshooting value of it!

**Comment by kmoze2001** [comment]
It's when y'all implement a CVR that I'm getting scared...  ;-)

**Comment by Taz5150** [comment]
I have gone over the FDR and it is and engine issue, the AP did not have anything to do with it. The problem is with the definition of flight phases and transitions. I will put it in the pipeline and work on it ASAP.

Thanks for the feedback!

**Comment by CptChaos0815** [comment]
Dear all,

to me it seems as if the fuel flow always cuts at 500ft AGL. I added 2 fdr files of flights where I had this issue. It is on hot airports like Medina with 37°C OAT and includes engine fluctuation from 250ft AGL to touchdown. At Frankfurt with 12°C OAT it was only the FF drop with no engine fluctuation.

https://www.youtube.com/watch?v=ofoErF2B3mI&t=746s

{
  "built": "2021-04-18T16:55:51+00:00",
  "ref": "experimental",
  "sha": "f52894be67d287a02fe2918e9963d7464e5d8d7b",
  "actor": "aguther",
  "event_name": "manual"
}

[2021-04-19-18-33-22.zip](https://github.com/flybywiresim/a32nx/files/6338619/2021-04-19-18-33-22.zip)

**Comment by Taz5150** [comment]
Yes, this is a known and identified issue we are working on right now. The new fuel flow model is being retrained. Should have it ready by mid- this week.

Thank you.

**Comment by Taz5150** [comment]
This issue has been solved with the new engine FADEC provided.
