### ISSUE TITLE
LNAV issue with DIR TO

### ISSUE THREAD

**Issue by jwsteens** [flybywiresim/a32nx#4413]
**Mod Version**

Latest experimental

**Describe the bug**

When selecting a direct waypoint (DIR page) the distance on the ND is shown as 0nm. This causes the A32NX to turn on the spot. I haven't tested it throughout, but the turning on the spot issue only seems to happen in approach phase. The distance issue seems to happen all the time when selecting a direct route.

**To Reproduce**

1. Fly (with flightplan)
2. Select waypoint on DIR page
3. See how distance and bearing on ND stay at 0
4. Activate approach phase
5. Select a direct waypoint again, see how the distance and bearing stay at 0 and how the aircraft starts orbiting

**Expected behavior**

Expected behaviour is that distance and bearing are shown on ND

**Actual behavior**

Distance and bearing are not shown on ND, in approach phase it starts orbiting rather than following the direct path.

**References**

This is a screenshot of PFD and ND with approach phase activated. At this point the aircraft is coming around for the 360 turn, not to catch the LNAV path.
![image](https://user-images.githubusercontent.com/74742373/114396211-99f3e200-9b9d-11eb-9f7c-b8a8906ab929.png)

Was this working before/when did the issue start occurring?
It seems like this issue has been around for a while, but I think I've found its origin just now.

Is this a problem in the vanilla unmodded game?
A32NX mod with a livery.

Discord username (if different from GitHub): willem#5819

**Comment by jwsteens** [comment]
UPDATE: The orbiting issue seems to happen regardless of approach phase activated, and regardless of the bearing and distance showing. 
![image](https://user-images.githubusercontent.com/74742373/114412746-a8e29080-9bad-11eb-9344-419d987d7da1.png)

**Comment by MisterChocker** [comment]
DirTO feature is not yet fully supported/implemented and we currently have also no 'LNAV' implemented

**Comment by 2hwk** [comment]
Fixed by 4953 closing ☑️
