### ISSUE TITLE
Flight plan gets removed after inputting an altitude restriction 

### ISSUE THREAD

**Issue by rg2001** [flybywiresim/a32nx#4417]
**Mod Version**

Experimental

**Describe the bug**

While at cruise I went to the flight plan page and click on a waypoint to insert an alt restriction and it just cleared all the flight plan
and removed all INIT page

**To Reproduce**

1.Input a flight plan then
2.click on a waypoint
3.type 100 or 10000
4.click button to insert alt restriction 

**Expected behavior**

An altitude restriction should be placed at that waypoint

**Actual behavior**

Clears flight plan.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
First time I tried this

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):
IsoNotSocial#0652

**Comment by MisterChocker** [comment]
Can you please attach a screenshot or video?

**Comment by obadvw** [comment]
Same thing happened to me too , when you go to INIT page you found it empty too , same behavior if you use DIRECT TO , flight plan just disappears

**Comment by MisterChocker** [comment]
Closing since no response from OP.
