### ISSUE TITLE
[REQUEST] Compatibilization with PFD fps limiter script

### ISSUE THREAD

**Issue by rodrifo6** [flybywiresim/a32nx#442]
The chronometer runs way slower if I use a framerate limiter for the screens on the aircraft. As we've known for a while, ASOBO aircraft displays are very unefficient on the airliners, which makes them prohibitively resource intensive to some people. That's why some choose to run FPS limiting mods to allow for a bit more performance out of the sim.

As some features on this aircraft seem to be reliant on the rate of refresh of the panels, some features may end up malfunctioning, like the chronometer for example.

With that in mind, maybe the aicraft could include itself a fps limiter on the displays, or maybe make it compatible with available scripts for that purpose.

**Comment by UncleClapton** [comment]
I can see a way we can re-implement this to fix this problem. Working on this now.

**Comment by UncleClapton** [comment]
Fix has been submitted. Feel free to track it here: #445

**Comment by rodrifo6** [comment]
> 
> 
> Fix has been submitted. Feel free to track it here: #445

Nice, i just tested it on the dev version and it works perfectly now. Great work
