### ISSUE TITLE
[Graphics] There is a sort of blue halo around the throttle levers

### ISSUE THREAD

**Issue by PatriceCesson** [flybywiresim/a32nx#4423]
**Mod Version**
{
  "built": "2021-04-12T23:00:10+00:00",
  "ref": "autopilot",
  "sha": "2a04c98677e05b75b296de1accd8a5dce8e313e3",
  "actor": "aguther",
  "event_name": "manual"
}

**Describe the bug**
There is a sort of halo around the throttles levers. See screenshot arrows pointing to the problem.

**To Reproduce**
Start a flight with the experimental version.
Check the throttle levers: a blue halo is sourrounfing the levers.
![snap059](https://user-images.githubusercontent.com/30781354/114534685-8c973000-9c4f-11eb-847d-fa23cedb96ed.png)

**Expected behavior**
No halo!

**Actual behavior**
Blue halo!

**References**

**Additional context**

Was this working before/when did the issue start occurring?
I do not know. I thgink the problem is here since at least 2 weeks, perhaps more.

Is this a problem in the vanilla unmodded game?
I do not know.

**Comment by andrejetcat** [comment]
this phenomen is nt only limited to the Throttle. It appears all over the plane, especially outside. It is a graphic "bug" from the SIM, not caused by the Mod. I recognise it also when i increase the "ambient occlusion". 
(correct me when I´m wrong)
