### ISSUE TITLE
REMOVE cockpit alarm in cabin view & ADD passenger sound ambiance in cabin view

### ISSUE THREAD

**Issue by lalloretpilou** [flybywiresim/a32nx#4431]
**Is your feature request related to a problem? Please describe.**
in the cabin view, we hear the alarms and the voices of the cockpit.

**Describe the feature you'd like to see implemented**
The cockpit voices and alarms must be removed in the Wings views and replaced by the ambient voices of passengers (people talking, crying baby, noise of seats, .....)

**Comment by davidwalschots** [comment]
@hotshotp

**Comment by hotshotp** [comment]
You no longer hear alarms in cabin view in development version and passenger sounds are already planned and have been requested in #2481
