### ISSUE TITLE
Inconsistency between S speed on PFD vs MCDU

### ISSUE THREAD

**Issue by donstim** [flybywiresim/a32nx#4432]
**Mod Version**

 "built": "2021-04-12T22:59:31+00:00",
  "ref": "merge",
  "sha": "d33247ad38de47ae1b82b88ab370a2da392c0a14",
  "actor": "aguther",
  "event_name": "manual"

**Describe the bug**

The S speed shown by the marker on the speed tape on the PFD is different than the S speed given by the MCDU. The autoflight system is targeting the speed given by the MCDU, which appears to be the correct S speed for the weight.

**To Reproduce**

1. Load up the sim at the default weight at a normal altitude for initial approach (3000-5000 feet). Engage the autopilot in heading and altitude hold and engage autothrust.
2. Select managed speeds, select approach phase in the MCDU. 
3. Select CONF 1.
4. Compare S speed shown by the MCDU to the S speed marker on the PFD. Note the speed the autoflight system is targeting.

**Expected behavior**

S speed shown by MCDU to be the same as the S speed marker on the PFD and flown by the autoflight system

**Actual behavior**

See screenshot where S speed on the MCDU is 185, but PFD marker is at 190.
![Screenshot (755)](https://user-images.githubusercontent.com/70166617/114618191-ee5e9680-9c5d-11eb-9194-510966669405.png)

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):donbikes#4084

**Comment by tracernz** [comment]
At 60t (you are slightly under), S speed should be about 186 kts according to the QRH I have.

The speeds shown on the approach page are calculated based on estimated landing weight through descent phase, and then live gross weight from approach phase onwards, and you are in approach phase, so 185 kts looks to be correct.
https://github.com/flybywiresim/a32nx/blob/autopilot/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js#L889-L901
The speeds come directly from this table:
https://github.com/flybywiresim/a32nx/blob/2a04c98677e05b75b296de1accd8a5dce8e313e3/flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Utils/NXSpeeds.js#L274-L290
If we do the math by hand:
`178 + (59.629 - 55) * 1.6 = 185.4 kts`

Now we've established the MCDU is right, where is the PFD getting it's speed:
https://github.com/flybywiresim/a32nx/blob/autopilot/src/instruments/src/PFD/SpeedIndicator.jsx#L120-L121
That comes from the same table via NXSpeeds...
https://github.com/flybywiresim/a32nx/blob/autopilot/flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_Speeds.js#L65

Next I would like to check `L:A32NX_SPEEDS_S` in flight...
![image](https://user-images.githubusercontent.com/9995998/114640731-ce45da80-9d24-11eb-9516-16d6a9a5aa69.png)
Looks like the PFD scaling is a little off @lukecologne

**Comment by lukecologne** [comment]
Weird. I'll have to take a closer look tomorrow

**Comment by donstim** [comment]
> 
> Next I would like to check `L:A32NX_SPEEDS_S` in flight...
> ![image](https://user-images.githubusercontent.com/9995998/114640995-54622100-9d25-11eb-89bb-8abd1d7e90ab.png)
> 
> Looks like the PFD scaling is a little off @lukecologne

Yes, I had worked with @MisterChocker to get the speeds in there originally and double-checked that the table in NXSpeeds.js are correct. I made sure I was in the approach phase so that they would reflect the actual weight. I just didn't know where the PFD got the speed for its marker.

**Comment by lukecologne** [comment]
Alright, found the issue, the paths/positions of the Flaps and Slats indicators were just wrong, I pushed a fix for the issue.

**Comment by tracernz** [comment]
Thanks for the quick fix! I guess we can close this now.

**Comment by MisterChocker** [comment]
altho it's resolved, the tables within NXSpeeds are FCOM based.
(I also ran a small "simulation" to check for every weight within a possible range)

**Comment by MisterChocker** [comment]
Why has the issue been closed tho?
The main issue reported is that the approach page during approach phase does not use live weights.

**Comment by tracernz** [comment]
> The main issue reported is that the approach page during approach phase does not use live weights.

It does though?

**Comment by MisterChocker** [comment]
No doesn't seem to be, but someone told me it would...

**Comment by tracernz** [comment]
> 
> 
> No doesn't seem to be, but someone told me it would...

Code looks right to me. https://github.com/flybywiresim/a32nx/blob/autopilot/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js#L893

Bogus ZFW on init to make the predicted speeds too high so we can see...
![20210415011357_1](https://user-images.githubusercontent.com/9995998/114716381-1c3ffa00-9d88-11eb-8466-b53b762f734e.jpg)
![20210415011408_1](https://user-images.githubusercontent.com/9995998/114716388-1e09bd80-9d88-11eb-9a0e-1199d6deffc3.jpg)

Maybe I'm misunderstanding what you're saying?

**Comment by MisterChocker** [comment]
Can you cross check the predicted LW with the Speeds.

**Comment by tracernz** [comment]
> 
> 
> Can you cross check the predicted LW with the Speeds.

Unfortunately I already had engines running when I setup the bogus ZFW and screenshotted FUEL PRED, so I don't have the exact figure from INIT FUEL PRED, but I can guestimate it from what I do have.
![20210415010820_1](https://user-images.githubusercontent.com/9995998/114800608-1ed53a80-9dee-11eb-9d5d-0f6fbe2a9f43.jpg)
(bogus) ZFW 70 t, FOB is 9.6 t at takeoff, and my F-PLAN was depart 34 and turn right while climbing to 3000, do 90 degrees around the DME arc and join ILS34 to land again, so predicted fuel burn would be small, maybe 0.4 t? So 79.2 t LW, Sspeed = `207 + 1.4 * (79.2 - 75) = 212.9 kts`. You can check the others if you like.

**Comment by MisterChocker** [comment]
What I asked for (to see if it works, plan a 4 hour flight, where you will see a significant difference between predicted and actual GW.

**Comment by tracernz** [comment]
> 
> 
> What I asked for (to see if it works, plan a 4 hour flight, where you will see a significant difference between predicted and actual GW.

Ah, yes, I don't think our success there will be limited without a reasonable VNAV implementation. Lucky did a good job with the limited data available though. You can see the code in https://github.com/flybywiresim/a32nx/blob/ff5dcddb5b2598f02df30cb7a52be5d2d613a731/flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_FuelPred.js#L205
