### ISSUE TITLE
1.15.7.0 PAUSE with Honeycomb Bravo causes throttles to move to ~50% and Flaps 1

### ISSUE THREAD

**Issue by kmoze2001** [flybywiresim/a32nx#4434]
**Mod Version**

{
  "built": "2021-04-13T16:07:20+00:00",
  "ref": "master",
  "sha": "5d7fc959975cfc372b47198a12e808238c46b18f",
  "actor": "davidwalschots",
  "event_name": "manual"
}

**Describe the bug**

 
After unpausing the sim with a Honeycomb Bravo, the throttle is set to ~50% and Flaps 1

**To Reproduce**

1.  Flying out of YMML, dest YSSY, plan DOSEL1 DOSEL Y59 RIVET DCT BOOGI DCT DUDOK DCT NASHO DCT KAMPI DCT SUZAN DCT
2.  Pause during initial climb
3.  Unpause and throttles are set at 50%, flaps 1, overspeed alarm blaring, and hitting the master alarm button does not silence it.  Resetting controls solves the problem.

**Expected behavior**

I expected it to return to throttle set to CL and flaps 0.  The physical position of the TQS did not change in between.

**Actual behavior**

As stated above.

**References**

None.

**Additional context**

None.

Was this working before/when did the issue start occurring?

Yes, trouble started on first flight after 1.15.7.0 upgrade.

Is this a problem in the vanilla unmodded game?

Unknown

Discord username (if different from GitHub):
 
KevyKevTPA#6583

**Comment by Benjozork** [comment]
This is likely to be an MSFS bug.

**Comment by kmoze2001** [comment]
I'm as sure as a non-programmer can be that it has something to do with the 10/1 bug fix that came with today's patch.  But I couldn't code my way out of a paper bag, so who knows.  But it happened several times.

**Comment by tracernz** [comment]
Happens without Honeycomb too. Noted by Andreas already and an MSFS bug.

**Comment by p493z3r0** [comment]
I had a similar issue with my Thrustmaster 320 set.  I could resolve it by clearing all unused bindings to flaps and spoilers. Probably related.

**Comment by SierraBravo1** [comment]
This is an Asobo bug and happens with all aircraft and also other throttel types.
Please vote for this bug in the MSFS forum and create a zendesk ticket:
https://forums.flightsimulator.com/t/throttle-flaps-mixture-speedbrake-etc-axis-at-50-when-exiting-menu-wu-iv-1-15-7-0/390383

**Comment by tracernz** [comment]
> 
> 
> I had a similar issue with my Thrustmaster 320 set. I could resolve it by clearing all unused bindings to flaps and spoilers. Probably related.

That's a different (non) bug that's been present since the beginning.

**Comment by FRYYYYYY** [comment]
Same here with TCA Quadrant. After resuming from menu, Thrust lever is set to Climb, Flaps 1, speed brakes 50%.
It began after installing latest MSFS patch.

**Comment by tshomas** [comment]
As above, this is not a mod issue but an Asobo issue, please follow the link above.

**Comment by MisterChocker** [comment]
Sounds like the the same issue where something similar happened when you had keybinds to not existing buttons.

**Comment by Benjozork** [comment]
Closing as unrelated to the A32NX
