### ISSUE TITLE
MSFS not recognizing A32NX [RESOLVED]

### ISSUE THREAD

**Issue by marcelago** [flybywiresim/a32nx#4435]
So I currently came back from taking a 2 month break from MSFS and tried to download a fresh version of the A32NX (did not work with the old installer, had to download the new installer), but for whatever reason the game did not show the mod, or rather the changes made by the mod (EFB, textured, added functionality, added livery,... ect.)
I tried multiple things and could not get it to work, giving my feedback here, or in forums, is my last hope.

Everything I tried:
- restart computer
- Experimental version instead of stable version install
- raw install of inzipped file 
- just copy-pasted the zipped file directly into the community folder
- reinstalled MSFS 
- reinstalled FBW installer (the new one)
- renamed unzipped folder to "A32NX" (because of troubleshooting advice on github front page)
- changed directory in the installer and just copied the unzipped folder into the community folder manually
- deleted all other mods (just liveries)

Things to note:
- the community directory is correct (checked in dev mode), other mods (Liveries) do work [F:\MSFS2020\Community]
- I own a hardcopy (with 10 disks, wow) of the game and I installed it through the Microsoft Store [DVD works as a digital key]
- Game is stored on a harddrive but disk-space is abundant 

Now I am not entirely sure if my issue is related to FBW or MSFS or just a weird freak accident, but I hope that somebody can help me out, since this mod is to great to miss out on. Thank you for everything and I wish everyone a great day.

**Comment by Benjozork** [comment]
Make sure that you select the FBW A320neo (if using dev or exp) as they are separate from the default Asobo one now. You can click on the "Airliners" category to see it more easily.

Btw, you need to follow the given template when opening issues.

**Comment by marcelago** [comment]
I just checked and that was in fact the issue, I can't thank you enough for your help and sorry for the incorrect layout :)
