### ISSUE TITLE
Autopilot and autothrottle disengage on autopilot bind not working since new update.

### ISSUE THREAD

**Issue by TLSY2** [flybywiresim/a32nx#4437]
**Mod Version**

```json
"built": "2021-04-14T18:47:54+00:00",
"ref": "autopilot",
"sha": "fd5dcb5204b486f2f145f0fb400651c85e74e084",
"actor": "aguther",
"event_name": "manual"
```

**Describe the bug**

I have buttons binded on joystick to disengage autopilot and autothrtottle but they dont work since new update that makes the plane individual.

**To Reproduce**

1. I was just coming in for a landing
2. At 1000 ft i pressed the buttons nothing
3. I manually disengaged 

**Expected behavior**

upon pressing the buttons on joystick the autopilot/autothrottle should disengage.

**Actual behavior**

Nothing

**References**

**Additional context**

Was this working before/when did the issue start occurring?
it was working before the update where the plane is individual

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
#4028

**Comment by MisterChocker** [comment]
Which version do you use? Stable, Development or Experimental?
Also please post the content of the build_info,json (found in the main directory of the plane).

For the future please select the Bug Report to report bugs. (Currently you used the Feature Request functionality)

**Comment by TLSY2** [comment]
> Which version do you use? Stable, Development or Experimental?
> Also please post the content of the build_info,json (found in the main directory of the plane).
> 
> For the future please select the Bug Report to report bugs. (Currently you used the Feature Request functionality)

experimental, yeah, i just realized it says enhancement.

The main directory is it in app data and roaming...?

**Comment by MisterChocker** [comment]
I've changed this issue to a bug report. Can you please fill in the remaining fields on the updated template?

**Comment by TLSY2** [comment]
yes.

**Comment by Benjozork** [comment]
Why did you change the issue from being about flight plans to keybindings

**Comment by TLSY2** [comment]
> Why did you change the issue from being about flight plans to keybindings

I did after you told me to do for each issue independent and i remembered that issue. Is that a problem? The title is the new one right?

**Comment by Benjozork** [comment]
Keep in mind these issues may be linked somewhere in our discord for tracking and if they change it might get confusing.

But it's fine

**Comment by TLSY2** [comment]
> Keep in mind these issues may be linked somewhere in our discord for tracking and if they change it might get confusing.
> 
> But it's fine

Ok thanks!

**Comment by aguther** [comment]
Well, I don't know which buttons you press on your joystick and which function you have mapped to them.

I assume it's a sim issue, bc the usual bindings like AP Master, AP Disconnect or ATHR Toggle work properly for me.

Honestly I have no idea now to help this way.

**Comment by awaylands** [comment]
I have this issue as well with the current Experimental version build. Would you please provide the correct specific bindings for AP and AT disconnect within MSFS? There are several mapping options within the sim.

**Comment by TLSY2** [comment]
> ping options within the sim.

I have it on my joystick (Logitech Attack 3) (I know its a piece of s... but it does the job got it for 3 pounds :D) anyway i think it goes down as button 4 and 2

**Comment by TLSY2** [comment]
> Well, I don't know which buttons you press on your joystick and which function you have mapped to them.
> 
> I assume it's a sim issue, bc the usual bindings like AP Master, AP Disconnect or ATHR Toggle work properly for me.
> 
> Honestly I have no idea how to help this way.

They work on any other plane, except the a32nx exp since the update where the plane is now individual.

**Comment by awaylands** [comment]
> > Well, I don't know which buttons you press on your joystick and which function you have mapped to them.
> > I assume it's a sim issue, bc the usual bindings like AP Master, AP Disconnect or ATHR Toggle work properly for me.
> > Honestly I have no idea how to help this way.
> 
> They work on any other plane, except the a32nx exp since the update where the plane is now individual.

I see in the latest Exp build when I hover over the AP disconnect button on the stick it now says "AP disconnect" or something like that, but the last Exp build it said "Take control" or something? Was hoping this was updated. AP disconnect on the stick and AT disconnect are the two most crucial bindings as they're used on approach. Hope this gets updated soon. Let me know if there's a workaround, thanks!

**Comment by TLSY2** [comment]
> > > Well, I don't know which buttons you press on your joystick and which function you have mapped to them.
> > > I assume it's a sim issue, bc the usual bindings like AP Master, AP Disconnect or ATHR Toggle work properly for me.
> > > Honestly I have no idea how to help this way.
> > 
> > 
> > They work on any other plane, except the a32nx exp since the update where the plane is now individual.
> 
> I see in the latest Exp build when I hover over the AP disconnect button on the stick it now says "AP disconnect" or something like that, but the last Exp build it said "Take control" or something? Was hoping this was updated. AP disconnect on the stick and AT disconnect are the two most crucial bindings as they're used on approach. Hope this gets updated soon. Let me know if there's a workaround, thanks!

Wait, I noticed something else too. If i press the disengage buttons from the sidestick in game, (so in game not at my house) nothing happens and on the autothrottle the side button

Also, for me it doesnt show the text with the functions anymore, guess because my settings are on hard mode. So i didnt notice that text you are saying, the workaround is easy click the buttons from autopilot controlls..

**Comment by awaylands** [comment]
> > > > Well, I don't know which buttons you press on your joystick and which function you have mapped to them.
> > > > I assume it's a sim issue, bc the usual bindings like AP Master, AP Disconnect or ATHR Toggle work properly for me.
> > > > Honestly I have no idea how to help this way.
> > > 
> > > 
> > > They work on any other plane, except the a32nx exp since the update where the plane is now individual.
> > 
> > 
> > I see in the latest Exp build when I hover over the AP disconnect button on the stick it now says "AP disconnect" or something like that, but the last Exp build it said "Take control" or something? Was hoping this was updated. AP disconnect on the stick and AT disconnect are the two most crucial bindings as they're used on approach. Hope this gets updated soon. Let me know if there's a workaround, thanks!
> 
> Wait, I noticed something else too. If i press the disengage buttons from the sidestick in game, (so in game not at my house) nothing happens and on the autothrottle the side button
> 
> Also, for me it doesnt show the text with the functions anymore, guess because my settings are on hard mode. So i didnt notice that text you are saying, the workaround is easy click the buttons from autopilot controls..
> 
> And oh yeah, some a320 pilot was talking about how when they engage autopilot the sidestick clicks in place and for it to be moved to disengage autopilot takes pressure. Maybe a feature will be added where to disengage it you move your joystick more than half way so it disconects.

I'm just asking about binding the sim events to my joystick and throttle. The sidestick AP disconnect and the AT disconnect button on the throttle. Have you been able to do this on the current Exp build?

**Comment by TLSY2** [comment]
> > > > > Well, I don't know which buttons you press on your joystick and which function you have mapped to them.
> > > > > I assume it's a sim issue, bc the usual bindings like AP Master, AP Disconnect or ATHR Toggle work properly for me.
> > > > > Honestly I have no idea how to help this way.
> > > > 
> > > > 
> > > > They work on any other plane, except the a32nx exp since the update where the plane is now individual.
> > > 
> > > 
> > > I see in the latest Exp build when I hover over the AP disconnect button on the stick it now says "AP disconnect" or something like that, but the last Exp build it said "Take control" or something? Was hoping this was updated. AP disconnect on the stick and AT disconnect are the two most crucial bindings as they're used on approach. Hope this gets updated soon. Let me know if there's a workaround, thanks!
> > 
> > 
> > Wait, I noticed something else too. If i press the disengage buttons from the sidestick in game, (so in game not at my house) nothing happens and on the autothrottle the side button
> > Also, for me it doesnt show the text with the functions anymore, guess because my settings are on hard mode. So i didnt notice that text you are saying, the workaround is easy click the buttons from autopilot controls..
> > And oh yeah, some a320 pilot was talking about how when they engage autopilot the sidestick clicks in place and for it to be moved to disengage autopilot takes pressure. Maybe a feature will be added where to disengage it you move your joystick more than half way so it disconects.
> 
> I'm just asking about binding the sim events to my joystick and throttle. The sidestick AP disconnect and the AT disconnect button on the throttle. Have you been able to do this on the current Exp build?

No, like i said, I think those buttons on autothrottle and sidestick functionality has been removed thats why they dont work. Because it makes sense, when i used to press the joystick then the in game sidestick was pressing it. Currently no workaround as there may not be a way, probably needs recoding. 

My only coding skills are not even 'print hello world' ;D

**Comment by aguther** [comment]
Rumor has it, huh?

I just checked, the red buttons on the throttle work and also the red button on the sidestick. Keep in mind, that the sidestick button only disconnects the AP, it does *not* engage it.

The events I use are:
AUTOPILOT OFF
TOGGLE AUTOPILOT MASTER
ARM AUTO THROTTLE

Because seeing is believing, here you go:
https://youtu.be/gGQ3kKEO7GQ

**Comment by awaylands** [comment]
> Rumor has it, huh?
> 
> I just checked, the red buttons on the throttle work and also the red button on the sidestick. Keep in mind, that the sidestick button only disconnects the AP, it does _not_ engage it.
> 
> The events I use are:
> AUTOPILOT OFF
> TOGGLE AUTOPILOT MASTER
> ARM AUTO THROTTLE
> 
> Because seeing is believing, here you go (at the beginning I use keyboard and then joystick):
> https://youtu.be/gGQ3kKEO7GQ
> 
> By the way the display of the events trigger is also in the version of the installer, so you can open the console and check if the events are fired. If the don't, it's a sim issue.

CHAMPION!! This is it. 

The events for the Exp version are different from the Stable/Dev version.

Thanks!

**Comment by aguther** [comment]
Out of curiosity: which events did you use with stable/dev?

**Comment by awaylands** [comment]
> Out of curiosity: which events did you use with stable/dev?

I believe I was using:

SET AUTOPILOT DISENGAGE or TOGGLE DISENGAGE AUTOPILOT

for autothrottle disconnect I was using:

AUTOTHROTTLE DISCONNECT

(seems logical?)

**Comment by TLSY2** [comment]
> Rumor has it, huh?
> 
> 
> 
> I just checked, the red buttons on the throttle work and also the red button on the sidestick. Keep in mind, that the sidestick button only disconnects the AP, it does *not* engage it.
> 
> 
> 
> The events I use are:
> 
> AUTOPILOT OFF
> 
> TOGGLE AUTOPILOT MASTER
> 
> ARM AUTO THROTTLE
> 
> 
> 
> Because seeing is believing, here you go (at the beginning I use keyboard and then joystick):
> 
> https://youtu.be/gGQ3kKEO7GQ
> 
> 
> 
> By the way the display of the events trigger is also in the version of the installer, so you can open the console and check if the events are fired. If the don't, it's a sim issue.

I see it works for you.

I will try to rebind.

I will let you know tomorrow which events i had binded.

**Comment by aguther** [comment]
If there are more events, I will recheck to add them. Unfortunately they are not all documented in the SDK, so I was not aware.

**Comment by awaylands** [comment]
> If there are more events, I will recheck to add them. Unfortunately they are not all documented in the SDK, so I was not aware.

Thank you, that would be great! And thank you for your help. :)

**Comment by TLSY2** [comment]
My events were:

AUTOTHROTTLE DISCONECT

SET AUTOPILOT DISENGAGE.

Now i have binded:

TOGGLE AUTOPILOT MASTER

ARM AUTOTHROTTLE

now these new binds work but they engage it too, I mean realistically it should be my first added binds that work for this.
Anyway i am thankful for your help and maybe you can code if you want the other events for disengage.

Thanks!

**Comment by aguther** [comment]
I've improved the key bindings, will come later this day to experimental version:
https://github.com/flybywiresim/a32nx/tree/autopilot/docs

**Comment by aguther** [comment]
The changes are now on experimental and build is done. I close this issue now, feel free to reopen if needed.

**Comment by TLSY2** [comment]
You are the best @aguther , have a great day!
