### ISSUE TITLE
Simbrief Flight Plan not downloaded into MCDU.

### ISSUE THREAD

**Issue by Biniou671** [flybywiresim/a32nx#4438]
**Mod Version**
  

Mod version: Dev. version (fef8cc8) from A32NX installer v. 1.1.4, as of today 15Apr2021.

{
  "built": "2021-04-15T02:20:10+00:00",
  "ref": "master",
  "sha": "fef8cc806a7abd025bac474f5a65042c34a29c5f",
  "actor": "Benjozork",
  "event_name": "manual"
}

**Describe the bug**

Flight Plan from Simbrief not downloaded into the MCDU.

**To Reproduce**

1. Flight Plan generated in Simbrief (EGLL-LSZH)
2. Flight Plan details: EGLL/09L F370 MODMI1K MODMI UM185 MID UL612 RESMI UN491 MELKO UM606 BLM BLM2G LSZH/34
3. Starting A32NX cold and dark.
4. Simbrief Pilot ID, correctly in the MCDU.
5. INIT PAGE 1 -> INIT request -> Data appearing is correct, but having the remarks down the MCDU screen "AWY/WPT MISMATCH"
6. INIT page 2 -> all data showing (no issue here)
7. PERF -> Entering all necessary data (no issue here)
8. F-PLN -> Flight plan waypoints not appearing. Available data on the page are only: 
   Airport of Departure (EGLL),
   (DECEL) point,
   Airport of Arrival (LSZH)

**Expected behavior**

Having the full flight plan from Simbrief downloaded into MCDU, as it was before new installer version 1.1.4.
I have not been able to fly A32NX due to bugs coming since the installer new version 1.1.4

**Actual behavior**

No flight plan in the MCDU, and cannot add any waypoint manually.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
A32NX flight plan was working fine until new A32NX installer came out, and since folder renamed as "flybywire-aircraft-a320-neo"

Is this a problem in the vanilla unmodded game?
Not too sure. untill now I was only flying A32NX from FlyByWire.

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by tracernz** [comment]
What nav data are you using for the sim? What navdata are you using in SimBrief?

**Comment by Biniou671** [comment]
I am using Navigraph with current AIRAC 2103.

**Comment by tracernz** [comment]
Just to confirm you have installed the navigraph data into MSFS with the beta installer? https://forum.navigraph.com/t/navigraph-navdata-beta/133
This flight plan imported okay for me.

**Comment by Biniou671** [comment]
Yes, I use the Navigraph data installer beta 2.3, too.

**Comment by Biniou671** [comment]
I am wondering how the MCDU is retrieving the FP: Is it directly from Simbrief website, or is it from a local folder in my PC?
Could the issue come from a change of folder path? Currently my Simbrief FP are store in this path:
C:\Users\xxx\AppData\Local\Packages\Microsoft.549981C3F5F10_8wekyb3d8bbwe\LocalState

**Comment by Biniou671** [comment]
Hi,
After the today update (3db5a28). I have been able to download the flight plan into MCDU.
I completed my flight from EGLL to LSZH, everything was smooth.
You may close the case.
Thanks for your support ;)
