### ISSUE TITLE
[BUG] FMC not triggering DES phase : Speed remaining at cruise

### ISSUE THREAD

**Issue by 0nnyx** [flybywiresim/a32nx#444]
**Mod Version**
0.2.0 and previous

**Describe the bug**
The FMC doesn't trigger DES phase on PERF page after reaching the top of descent.
As consequence, the FMC remains in CRZ mode for the descent causing the speed to remain at the cruise speed instead of going to descent speed.
Depending on your ILS approach, the flight path might not cross the decel point. See workaround below if happening.

**To Reproduce**
Perform any flight planned via the world map using an ILS approach.

**Expected behavior**
I'm no real pilot. From the FSlabs A320, we should get a Decelerate message when reaching top of descent.
At that point, when setting a lower altitude and pushing the knob, the FMC PERF should change to DES and reach the DES speed instead of remaining at cruise speed.

**Actual behavior**
The speed remains at cruise speed instead of going to descent/approach speed when descending/reaching approach point.

**References**
FSlabs A320 descent video of expected behavior: https://www.youtube.com/watch?v=mGVGOxbtRK8

**Workaround**
When reaching top of descent: manually set the speed on the Flight control Unit to the descent speed and set the altitude according to the ATC : the top of descent looks properly estimated to remain at or close to idle thrust for the descent speed on the DES PERF page.
When coming in range of the localizer (LOC* or LOC), manually trigger the approach phase on the FMC and set back the speed to managed (---) on the FCU.

Example of DECEL point out of flight path requiring to trigger approach manually
![93127320-4c5cd880-f693-11ea-9af2-32981764813d](https://user-images.githubusercontent.com/54419678/93304887-0708ea00-f7fe-11ea-8d72-e4913f6f96ed.png)

**Extra note**
Thanks guys for all the job done on improving the default A320 :)

**Comment by UncleClapton** [comment]
I was able to replicate this, but not sure exactly whats causing it. Perhaps the phase change logic still has a few kinks. @tyler58546, Would you happen to know why this might be happening?

**Comment by Venorcis** [comment]
I do always get the Approach mode when reaching the DECEL waypoint, but the Descent mode indeed never triggers.

**Comment by 0nnyx** [comment]
Trying with other flight plans, I agree with the comment above that the DECEL point triggers the APPR phase.
My usual test flight (Schipol -> Brussels ILS25R : 15minutes) has a default approach following an arc and the DECEL point sits at the center of that arc instead of being on the arc, hence DECEL is never reached, which in turn doesn't trigger APPR phase. I guess this is a bug in the flight planner or original FMC code.

**Comment by anazhd** [comment]
> Trying with other flight plans, I agree with the comment above that the DECEL point triggers the APPR phase.
> My usual test flight (Schipol -> Brussels ILS25R : 15minutes) has a default approach following an arc and the DECEL point sits at the center of that arc instead of being on the arc, hence DECEL is never reached, which in turn doesn't trigger APPR phase. I guess this is a bug in the flight planner or original FMC code.

most probably the original fmc is the culprit. I switch between A32NX and original A20N (A320neo) multiple times, no matter what type of flight plan (simbrief, world map,manual), FMC never trigger DES mode. Instead, on DECEL it kicks in APPR. Just like you said. Plus with the ATC not recognizing your flight plan and constantly asking to climb back to 12000ft 5 miles before landing, it's quite frustrating haha.

**Comment by MattPaxtonBel** [comment]
I was also able to replicate the problem that the aircraft doesn't trigger the descent phase after leaving ALT CRZ altitude. What I also observed, is that after starting DES or OP DES from ALT CRZ, when you level off at a lower altitude due to ATC request, the ALT CRZ message is still mentioned on the FMA, it should be ALT (not ALT CRZ). This could be a symptom or a cause of the DESCENT phase to triggered. 

I also confirm that the APPR phase is automatically entered by the aircraft passing the DECEL point on the ND. 

Due to the fact that DES phase is not entered, you can't force APPR phase before the DECEL point. 

I had also on a short test flight (LFKJ-LFBD) the ATC clearing me for a VORDME approche on RWY 23, clearing me a 6700 ft, few seconds after that clearance, I was issue another clearance to climb FL180, which I didn't follow despite multiple ATC requests. Finally, turning on final course I was cleared to land.

**Comment by 0nnyx** [comment]
Given the limitation of the vanilla autopilot and if unable to trigger the DES phase, I suggest as Enhancement and if possible to implement the DECELERATE message when reaching the top of descent until selecting a lower altitude, as shown http://www.a320dp.com/A320_DP/nav-autoflight/sys-13.3.66.html

**Comment by AdenFlorian** [comment]
i have a fix for this, pr going up soon
