### ISSUE TITLE
Checklists on EFB

### ISSUE THREAD

**Issue by TLSY2** [flybywiresim/a32nx#4443]
**Is your feature request related to a problem? Please describe.**

Can we get checklist on EFB? I dont think its that hard to implement since its already on the toolbar. It would be great. 
**Describe the feature you'd like to see implemented**

**References**

**Additional context**

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by tracernz** [comment]
Please open a separate issue for the flex temp calculator. That is an unrelated non-trivial change that is unlikely to be done at the same time as checklists.

**Comment by TLSY2** [comment]
> Please open a separate issue for the flex temp calculator. That is an unrelated non-trivial change that is unlikely to be done at the same time as checklists.

ok, for each thing individual? Because i have more suggestions that i think are quite needed.

**Comment by MisterChocker** [comment]
> ok, for each thing individual? Because i have more suggestions that i think are quite needed.

Please do go ahead and open a separate issue for each one of them.

**Comment by TLSY2** [comment]
> > ok, for each thing individual? Because i have more suggestions that i think are quite needed.
> 
> Please do go ahead and open a separate issue for each one of them.

haha, someone says one thing someone other. It would be easier to do one because the issues get bigger and biger.

**Comment by TLSY2** [comment]
Will this be added to a list of things to do you guys have? Or I dont know what im talking about.

**Comment by Benjozork** [comment]
@TLSY2 the functionality will be added if someone wants to work on it. You can do it yourself if you have the programming knowledge.

Adding labels is only done by maintainers.

**Comment by TLSY2** [comment]
> @TLSY2 the functionality will be added if someone wants to work on it. You can do it yourself if you have the programming knowledge. Otherwise someone probably - will in the future.
> 
> Adding labels is only done by maintainers.

But do you have a list to add things to so people that want to work on have ideas? 

How do i become a maintainer? I want to be part of the github help chat.

**Comment by Benjozork** [comment]
> But do you have a list to add things to so people that want to work on have ideas?

You're there right now. Just filter by the "enhancement" label.

> How do i become a maintainer? I want to be part of the github help chat.

The maintainer team is invite only and is constituted from the Development Team on Discord.

You can freely chat here and answer people's questions already - we will add the labels if necessary.

**Comment by TLSY2** [comment]
> > But do you have a list to add things to so people that want to work on have ideas?
> 
> You're there right now. Just filter by the "enhancement" label. In the issues list.
> 
> > How do i become a maintainer? I want to be part of the github help chat.
> 
> The maintainer team is invite only and is constituted from the Development Team on Discord.
> 
> You can freely chat here and answer people's questions already - we will add the labels if necessary.

I understand now. Thanks!

**Comment by antonyisoardi** [comment]
I'm willing to pick this one up, though you already have the interactive checklist built into MSFS. How is this done in the real world through EFB? Any ideas/examples would be handy.

**Comment by tshomas** [comment]
![E2E52749-7352-4072-A6CD-39C95AF322A1](https://user-images.githubusercontent.com/74841560/119218600-151fb080-bad9-11eb-9358-5ead511945e8.jpeg)

We’ve just had this added to our work iPads that we use as EFBs, it has the full paper checklist on there and also QRH ones. You tap on the items to “tick” them off as such and change the colour. We’re not using them yet but I can imagine we will be doing soon!

**Comment by TLSY2** [comment]
> I'm willing to pick this one up, though you already have the interactive checklist built into MSFS. How is this done in the real world through EFB? Any ideas/examples would be handy.

I hate the hud in MFS and i turn it off, I just like to have things look clean in the efb.

My idea is that you have a page for the checklist and in that page the titles  for example (Cold and Dark), (Before engine start) (Take off). And once you click on the specific one you have the checklist and you just click on each required thing, probably a check box.

**Comment by antonyisoardi** [comment]
Cheers @tshomas - is there actually any integration with the aircraft, or is it simply standalone?

@TLSY2 totally agree with you. For actual checklists, are we able to get the real-world ones to base this off and implement where we are able to? Also, wondering whether or not checklists are the same every single time or whether there are certain scenarios where checklists will have alternate / additional steps?

**Comment by tshomas** [comment]
For the 320 family I’ve only ever seen standalone electronic checklists so far, but no clue if there is an option offered out there for it!

**Comment by TLSY2** [comment]
> Cheers @tshomas - is there actually any integration with the aircraft, or is it simply standalone?
> 
> @TLSY2 totally agree with you. For actual checklists, are we able to get the real-world ones to base this off and implement where we are able to? Also, wondering whether or not checklists are the same every single time or whether there are certain scenarios where checklists will have alternate / additional steps?

I will be future probably a320 pilot, from what i think I know there is different checklists for example not always the plane is cold and dark, for example plane just landed and is leaving again in 30 min, they wont stop all, irs still is aligned... We need a real a320 pilot here to clear this issue.

**Comment by TLSY2** [comment]
> For the 320 family I’ve only ever seen standalone electronic checklists so far, but no clue if there is an option offered out there for it!

the checklist mod from flightsimto isnt full checklist, like when airplane is cold and dark at least they check all systems, I found more buttons like cargo smoke.... Ground control. I dont think there is one available unless a real pilot clears this issue, maybe we can get 320sim pilot's attention?

**Comment by antonyisoardi** [comment]
Let me see what I can rustle up :)

**Comment by tshomas** [comment]
Yeah just let me know if you want more images of the EFB that my company is using 👍
It depends if you want a full SOP tick box such as the MSFS checklist, or to do it like the real one we use, which is a simplified checklist for referring to when operating the aircraft!

BTW TLSY2, no need to go searching for a real A320 pilot, you’ve got one here! 😜

**Comment by antonyisoardi** [comment]
Right on 💯 

Let's base it on what you've got. Are we able to get a list of the checklists you'd use @tshomas ? From there we can work out what is and isn't available in a32nx and go from there

**Comment by tshomas** [comment]
So effectively, what we get in the EFB at the moment in terms of normal checklists is very similar to the FBW paper checklist:
[FBW_A32NX_CHECKLIST_V1.2.pdf](https://github.com/flybywiresim/a32nx/files/6526794/FBW_A32NX_CHECKLIST_V1.2.pdf)

Here is the main title page, and also some examples, apologies for the quality as it has to be photos of the iPad screen as the EFBs are protected from exporting:
![IMG_1767](https://user-images.githubusercontent.com/74841560/119234152-3b1e7280-bb24-11eb-8067-695040a36dc3.JPEG)
![IMG_1768](https://user-images.githubusercontent.com/74841560/119234153-3d80cc80-bb24-11eb-9e7c-afa2b466074c.JPEG)
![IMG_1769](https://user-images.githubusercontent.com/74841560/119234148-3659be80-bb24-11eb-802a-a40e1bab95f7.JPEG)
![IMG_1770](https://user-images.githubusercontent.com/74841560/119234149-38bc1880-bb24-11eb-9d55-6c926018259b.JPEG)

As you can see, the format is extremely similar to the FBW one.

On top of this, we also get the QRH abnormal and emergency checklists, operations and supplementary information guides as well.

**Comment by tshomas** [comment]
Now it depends if you want the basic checklist which the IRL use, or you expand it out to the full checklist that we learn off by heart, but may be useful for simulation purposes.

**Comment by antonyisoardi** [comment]
Awesome 👍  the current FBW one is similar to the basic one or the full one?

**Comment by tshomas** [comment]
The PDF one I linked was also written by one of our A320 pilots, and it's extremely close to the basic one we use in the cockpit!

**Comment by antonyisoardi** [comment]
How about we start with that one for now. Perhaps we can look at ways at a later date in order to provide the full checklist as an alternate experience.

Looks like EFBv2 isn't too far away as well, so will see how we can factor it into that. 

Are we right to assume that Check List should be accessed from the top-level navigation on the EFB?

**Comment by TLSY2** [comment]
thats great! What is the letters at the top? AME, ABN... and what is meant by (silent)?

**Comment by tshomas** [comment]
So it’s:
AME Amendments
ABN Abnormals and Emergency Checklists
OPS Operational Documents
OEB Operational Engineering Bulletins (last minute edits/special checklists to fix serious bugs with the aircraft)
SI Supplementary Information (extra info and guides)
 C/L The normal checklist

(Silent) on a checklist means it is done by the pilot reading it without saying it out loud, so it’s just a reminder list rather than calling out each item for the other pilot to respond to, which is what we do for all the other checklists that don’t have silent on them.

**Comment by TLSY2** [comment]
Thanks! This is perfect! Cant wait for someone to make this into the EFB.

**Comment by antonyisoardi** [comment]
First pass, built on top of the new EFB
![image](https://user-images.githubusercontent.com/5309174/119255487-b0567a00-bbee-11eb-9f6a-29bc0004c592.png)

**Comment by tracernz** [comment]
Looks great! Maybe don't need to duplicate the ECAM memo since it's on the ECAM?

**Comment by antonyisoardi** [comment]
Cheers @tracernz can do, though what is the purpose of it? Purely a cross-reference for the expected state?

**Comment by tracernz** [comment]
> 
> 
> Cheers @tracernz can do, though what is the purpose of it? Purely a cross-reference for the expected state?

It's a live memo on the ECAM. Items not completed are shown in cyan. and completed ones in green. Here's the takeoff memo partially completed:
![image](https://user-images.githubusercontent.com/9995998/119316073-a013cd00-bcca-11eb-8a0c-cc3888d3663a.png)

**Comment by antonyisoardi** [comment]
Cheers @tracernz got it. The ECAM memo in the checklist isn't tied to the ECAM, so from that point of view, it's purely for reference. Happy to remove it if you guys think it's unnecessary.

@tshomas noticed also on your EFB checklists that a few items are actually asterisked, is this also something worth including.

**Comment by tshomas** [comment]
All up to you! The asterisks on the preliminary cockpit checklist shows the ones we have to do on a turnaround reset, as there’s not much point doing all of the preliminary checks every single time 😁

**Comment by antonyisoardi** [comment]
Hey, you guys are the subject matter experts! 😁

**Comment by TLSY2** [comment]
> First pass, built on top of the new EFB
> 
> Looking back over @tshomas pictures of their EFB, wondering whether it is better to mark each item done, or just mark the entire checklist.
> 
> ![image](https://user-images.githubusercontent.com/5309174/119255487-b0567a00-bbee-11eb-9f6a-29bc0004c592.png)

I think mark each one and after all are marked the checklist title is marked as done too.

**Comment by TLSY2** [comment]
> Cheers @tracernz got it. The ECAM memo in the checklist isn't tied to the ECAM, so from that point of view, it's purely for reference. Happy to remove it if you guys think it's unnecessary.
> 
> @tshomas noticed also on your EFB checklists that a few items are actually asterisked, is this also something worth including.

I do think its not worth writing ecam memo on efb as you have to look twice at the same thing. What you could do is change the title from ecam memo an just write the required, (landing gerar down...)

**Comment by antonyisoardi** [comment]
Almost there.

Can you guys take a look at the tabs at the top and make some suggestions on what these "should" be, again it was just taken straight from the PDF, and I've had to abbreviate a few due to the length of their titles. Happy to change these to whatever makes sense.

![image](https://user-images.githubusercontent.com/5309174/119342740-16fb9680-bcc8-11eb-8b09-2b048e22c547.png)

**Comment by TLSY2** [comment]
> Almost there.
> 
> Can you guys take a look at the tabs at the top and make some suggestions on what these "should" be, again it was just taken straight from the PDF, and I've had to abbreviate a few due to the length of their titles. Happy to change these to whatever makes sense.
> 
> ![image](https://user-images.githubusercontent.com/5309174/119342953-5b873200-bcc8-11eb-879c-e02f1aa88522.png)

Maybe put a folder before all this for example you have: Cold and dark, Turnaround. > then you have the Before start...

**Comment by antonyisoardi** [comment]
All of this constitutes "Normal Checklist" similar to what @tshomas provided under C/L in his photo. Can potentially look at revising after flyPadOS v2 gets the green light and this code gets merged in

**Comment by TLSY2** [comment]
Hey! Whats the status of this? Or whats up?

**Comment by tracernz** [comment]
> I do think its not worth writing ecam memo on efb as you have to look twice at the same thing. What you could do is change the title from ecam memo an just write the required, (landing gerar down...)

It would be better if we follow real line EFBs.

**Comment by schmidHolger** [comment]
Is there anybody working on that? There is a stale pull request but nothing happened with that one for a while. 
If nobody is working on that, I would volunteer to give it a try.
