### ISSUE TITLE
MCDU F-Plan Page

### ISSUE THREAD

**Issue by Bik59** [flybywiresim/a32nx#4446]
I have selected a flight. After I selected the Appr Runway under DEPP / APPR, I could not activate INSERT. After that, the F-Plan Page can no longer be called up either.
Delelopment version is active.
Latest version is installed.

Best regards
Jürgen

**Comment by Benjozork** [comment]
Please do not delete the provided template when opening issues.

**Comment by Bik59** [comment]
With the stable version I get an error message: Tetrying livery mode ERROR

**Comment by Bik59** [comment]
Good Morning,
the problem persists even after the latest version V 0.6.0 Development. As soon as I call up the Arrival Airport in the F-Plan Page and activate the current runway, the F-Plan Page can no longer be called up.

**Comment by MisterChocker** [comment]
Please open a new [bug report](https://github.com/flybywiresim/a32nx/issues/new?assignees=&labels=Bug&template=bug_report.md) and follow and fill in the provided template.
