### ISSUE TITLE
A32NX not loading in even after reloading and reinstalling. 

### ISSUE THREAD

**Issue by sahajshah21** [flybywiresim/a32nx#4447]
For some reason maybe with the new update I am not able to have the A32NX loaded in. I only have the default version showing up. I reinstalled from the browser and also from the flybywire app. Is there an issue? Thank you

**Comment by Benjozork** [comment]
Make sure to select the FBW A320neo, not the Default Asobo one.

Also, please do not delete the provided issue template.
