### ISSUE TITLE
F-Plan Page 

### ISSUE THREAD

**Issue by Bik59** [flybywiresim/a32nx#4459]
**Mod Version**

```json
{
  "built": "2021-04-15T22:57:32+00:00",
  "ref": "v0.6.0",
  "sha": "981b2e4b0e89998d21a70fe26de54a2f10066f6e",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

**Describe the bug**

After selecting the active runway at the destination airport, the F-Plan Page can no longer select it

**To Reproduce**

1.Flight plan loaded via Simbrief
2. Klick F-Plan Page
3. Selecting the active runway at the destination airport
4. F-Plan Page no longer active. Can click on it, but nothing happens

**Expected behavior**

That the F-Plan page is activated by the runway is active. Was she at war before?

**References**

https://ibb.co/f4VmW2S
[Unbenannt1](https://user-images.githubusercontent.com/79966104/115058705-d00acc00-9ee5-11eb-87dd-5279438adf09.JPG)

**Additional context**

Was this working before/when did the issue start occurring?
Before the last Microsoft update

c

Discord username (if different from GitHub):

Best regards 

Bik59

**Comment by MisterChocker** [comment]
What is the issue you are experiencing?

**Comment by Bik59** [comment]
After selecting the active runway, I cannot click INSERT. After that, the F-Plan Page can no longer be clicked. Everything is described and visible in the picture !

**Comment by MisterChocker** [comment]
Do you have any other mods/addons or liveries installed?

**Comment by adam-tychoniewicz** [comment]
I also have this bug. Can't click insert in f-plan. But when change to another page, I can't enter F-Plane page back. This looks like the button does nothing.

**Comment by Bik59** [comment]
I have now solved the problem: Navigraph AIRAC cycle (Program) once on Remove and then on Install. Now it looks good again.

**Comment by MisterChocker** [comment]
Glad you managed to fix it for yourself. Closing since issue resolved.
