### ISSUE TITLE
Aircraft oversteers in ROLLOUT stage.

### ISSUE THREAD

**Issue by Hibanan** [flybywiresim/a32nx#4460]
**Mod Version**

```json
{
  "built": "2021-04-12T23:00:10+00:00",
  "ref": "autopilot",
  "sha": "2a04c98677e05b75b296de1accd8a5dce8e313e3",
  "actor": "aguther",
  "event_name": "manual"
}
```

**Describe the bug**

After landing with autoland (CAT 3 DUAL) and the plane enters the ROLLOUT stage, it starts to oversteer (even in no wind) and oscillates from left to right while slowly veering off the runway to one side.

**To Reproduce**

1. Land at any runway using the autoland/autopilot and wait for the plane to enter the ROLLOUT stage.
2. Watch as the plane starts shaking from left to right.

**Expected behavior**

Plane keeps itself on the center line of the runway via small rudder adjustments.

**Actual behavior**

Plane oversteers massively and leaves the runway even without wind.

**References**

https://send.tresorit.com/a#NUlIsHD5yKWyxbVu6LvWeg - Landing done in custom weather with 0 kt wind and no controllers connected, no input from my part other than the reverser.

**Additional context**

Was this working before/when did the issue start occurring?
Since I've started using it about 2 weeks ago.

Is this a problem in the vanilla unmodded game?
The vanilla aircraft doesn't have autoland as far as I'm aware.

Discord username (if different from GitHub): -

**Comment by TLSY2** [comment]
Thats what i experienced, 3 autolands i done all of them resulted in oversteer.

**Comment by aguther** [comment]
FYI: your link cannot be downloaded anymore.

I know that the ROLL OUT needs some further tuning, although it seems strange to me that you have it in this extreme form. For most people it works very well, including me - and I do A LOT of them.

I have some additional questions:
- what was your frame rate?
- was the LOC still alive?

**Comment by aguther** [comment]
https://youtu.be/qIqNuPXJwwc

**Comment by Hibanan** [comment]
I've been messing around with my settings like turning off online functionality to try and eliminate the stuttering when landing and from what I've seen the issue does seem to come from low FPS, at around 20 or below. I've done 2 landings and both times the ROLLOUT stage worked mostly fine (kept centerline with small oscillation at the end, just before coming to a stop). To answer your other question the LOC was not the issue in any of my tests.

**Comment by aguther** [comment]
I did a test on my development laptop that has lower performance than my desktop:
https://youtu.be/b9KhOHFg0Ag

I will a performance warning print out that will state that function is not guaranteed below say 17 fps.
