### ISSUE TITLE
High idle N2

### ISSUE THREAD

**Issue by bisinchi** [flybywiresim/a32nx#4463]
**Mod Version**

```json
{
  "built": "2021-04-15T21:44:03+00:00",
  "ref": "experimental",
  "sha": "d1026985aa101b317cc2ca0f2c710816a1d4dd06",
  "actor": "aguther",
  "event_name": "manual"
}

```

**Describe the bug**

N2 with engine at idle seem very high, in the just over 68%, when I'm expecting a idle N2 of around 58%.

**To Reproduce**

1. take off (or even stay on the ground)
2. set engine to idle
3.N2 idle is set to something around 68%

**Expected behavior**

N2 idle is set to around 58%

**Actual behavior**

NZ idle is set to around 68%

**References**

**Additional context**

 Observed with flying around Nantes with real weather, SAT was around 21°C.

Was this working before/when did the issue start occurring?
As far as I remember, N2 usually was around 58%

Is this a problem in the vanilla unmodded game?
Haven"t tried that.

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment]
Can you prove the FDR file from that flight/issue?
path: `%LOCALAPPDATA%\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalState\packages\flybywire-aircraft-a320-neo\work`

**Comment by bisinchi** [comment]
Hi, sorry, I don't know how to open the FDR file.
But I did try again just now on same airport, here are 2 screen shots
Packs & anti ice off:
![pack off](https://user-images.githubusercontent.com/71987677/115118276-b085a900-9fa2-11eb-92f4-692d3b5163f7.jpg)
Packs & anti ice on.
![packs on](https://user-images.githubusercontent.com/71987677/115118280-b11e3f80-9fa2-11eb-86ab-04b9bb8e44d3.jpg)

**Comment by MisterChocker** [comment]
Yeah the Flight Data Recorder File needs to be loaded into a program in order to "view" it.
We'd appreciate if you are able to upload it somewhere and send us the link so we can look at the data from the flight and figure out what happened.

**Comment by hotshotp** [comment]
https://www.youtube.com/watch?v=cv41hm4JEB8&t=63s as you can see from this leap reference it is correct and intentional

**Comment by MisterChocker** [comment]
@bisinchi The figures you described are for CFM56 engines. We are modeling the Leap engine.
With this said, the values you see on the upper ecam correctly represent the Leap engine.

**Comment by bisinchi** [comment]
Hi guys,
Thanks for the explanation. Seems like the figures I describe seem also close to what I would expect for the PW1100J engine. I knew the idle n2 were high on the leap, but not that high.
Regards,
François
    On Sunday, April 18, 2021, 10:58:42 AM GMT+2, DerL30N ***@***.***> wrote:  
 
 


@bisinchi The figures you described are for CFM56 engines. We are modeling the Leap engine.
With this said, the values you see on the upper ecam correctly represent the Leap engine.
