### ISSUE TITLE
No OUTR TK FUEL XFRD when aircraft is loaded with 0kg and refueled via the efb

### ISSUE THREAD

**Issue by sschw56** [flybywiresim/a32nx#4465]
**Mod Version**

```json
{
  "built": "2021-04-15T21:44:03+00:00",
  "ref": "experimental",
  "sha": "d1026985aa101b317cc2ca0f2c710816a1d4dd06",
  "actor": "aguther",
  "event_name": "manual"
}
```

**Describe the bug**

The airplane doesn't pump fuel from the outer tanks to the inner tanks when loaded with 0 fuel selected in the main menu and filled via the efb.

However, if you start the plane with enough fuel (lets say the standard 6.461kg) and reduce the amount of fuel to 1.500kg via the efb there is no problem and everything works as expected.

**To Reproduce**

1. Load aircraft C&D with **0kg fuel** selected in the main menu
2. Load fuel (I used 1.500kg, so the wing tanks are full and there is a minimum in the inner tanks)
3. Start the airplane (batteries, apu, engines)
4. No Fuel transfer from outer tanks to inner tanks and the apu and the engines shut down after a short period (when the inner tanks are empty). The 680 kg in each outer tank are still there.

**Expected behavior**

There should be a message in the ECAM "OUTR TK FUEL XFRD" and the fuel from the outer tanks should be pumped into the inner tanks.

**Actual behavior**

No "OUTR TK FUEL XFRD" message and no usage of the fuel in the outer tanks, even when it means, that the engine turns off because of no fuel

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):
Chefkoch#7862

**Comment by donstim** [comment]
This is a known issue with the default Asobo fuel transfer system. The outer to inner tank transfer starts when the inner tank fuel level passes through a trigger level of 239 U.S. gallons (~905 liters or 726 kg). If you don't load at least this much fuel in an inner tank (regardless of whether you load it via the EFB of the MSFS weight and balance window), the trigger level is never crossed and the outer to inner wing tank fuel transfer never starts.

**Comment by sschw56** [comment]
Obviously a known issue.
