### ISSUE TITLE
Approach Performance QNH ending on 0 not accepted

### ISSUE THREAD

**Issue by OddSobriquet** [flybywiresim/a32nx#4468]
**Mod Version**

```json
{
  "built": "2021-04-15T21:44:03+00:00",
  "ref": "experimental",
  "sha": "d1026985aa101b317cc2ca0f2c710816a1d4dd06",
  "actor": "aguther",
  "event_name": "manual"
}

```

**Describe the bug**

entering a qnh ending in 0 (29.70) returns format error

**To Reproduce**

1. load into sim
2. MCDU APPR PERF Page 
3. enter qnh inHg ending in 0

**Expected behavior**

value accepted

**Actual behavior**

value not accepted

**References**

https://user-images.githubusercontent.com/72888738/115117634-e1181380-9f9f-11eb-8a04-ba1609fb2e7d.mp4

**Additional context**

Was this working before/when did the issue start occurring?
unknown

Is this a problem in the vanilla unmodded game?
unknown

Discord username (if different from GitHub):

**Comment by tracernz** [comment]
Good catch. This has been a bug for a long time (since #1583), and I carried it through my changes to this code without noticing! As a work-around you can enter 2970 (no decimal point).

Fix is in https://github.com/flybywiresim/a32nx/pull/4478
