### ISSUE TITLE
[BUG] Starting from saved flight has some invalid switch states

### ISSUE THREAD

**Issue by UncleClapton** [flybywiresim/a32nx#447]
**Mod Version**

master

**Describe the bug**

When loading from a saved flight, various button states are invalid.
* Landing lights are on
* Wing lights are on
* Engine bleeds are off
* No smoking is off
* Flight Director is off

**To Reproduce**

1. start a flight
2. save it mid flight
3. reload the game and load the saved flight
4. start flying and notice invalid states

**Expected behavior**

Landing lights to be off, Wing lights are off, engine bleed is on, flight director is on, and no-smoking is on.

**Actual behavior**

Landing lights is on, Wing lights are on, both engine bleeds are off, flight director is if, and no-smoking is off.

**References**

![](https://clapton.dev/u/2009/d0976334.png)
![](https://clapton.dev/u/2009/c6c0e3be.png)

**Additional context**

**Comment by Venorcis** [comment]
IIRC the plane is also in Takeoff mode when loading a save file (being in Cruise before).

**Comment by lousybyte** [comment]
The flight plan is also erased when you load a save.

**Comment by 2hwk** [comment]
As of 0.5.1 the state of the light switches should be correct, however the flight plan is erased so this issue is still to be addressed

**Comment by davidwalschots** [comment]
Closing this as the main issue is solved.
