### ISSUE TITLE
FLY by Wire Installer looking for an S drive

### ISSUE THREAD

**Issue by CANADACLIPPER1953** [flybywiresim/a32nx#4470]
**Mod Version**

```json

```

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by CANADACLIPPER1953** [comment]
I tried to update the FBW installer this morning and I am getting this message. 



I tried to update the installer this morning and got this message. "No such file or directory, scandir 'E:\Users\name\AppData\Local\Packages\FlightSimulator_8wekyb3d8bbwe\Local Cache\Community'                                            at Object.reddirSync FS.js:959:3
at Object.E.readdir Sync ( electron/js2c/asar_bundle.js:5:10231
at Function. remove AllTemp (File:///C:Users/name/AppData/Local/fbw_installer/app-1.2.0/resources/app .webpack/renderer/main_window/index.js:27:952108)
at file:///C:Users/name/AppData/Loal/fbw_installer/app-1.2.0/resources/app/.webpack/renderer/main_window/index.js:32:971357"

  The latest msfs2020 update broke my simulator and I did a complete reinstall of msfs2020. I do have the sim on my E drive and the previous version of the installer worked great.
Any help would be greatly appreciated. Thanks in advance.

**Comment by tellurics** [comment]
Please fill out the template

**Comment by Benjozork** [comment]
This is the A32NX repository not the installer one.

Anyway this is a known issue when you move your MSFS installer before updating the installer and not changing the settings of the installer to match it.

You can work around it by creating the folder at `E:\Users\name\AppData\Local\Packages\FlightSimulator_8wekyb3d8bbwe\Local Cache\Community` and then opening the installer, to then change it to the correct path in Settings

**Comment by CANADACLIPPER1953** [comment]
Thank you for your quick response Ben. I already have that folder in my E drive and that's why I'm stuck. I can't figure out why the installer can't find it.

**Comment by Benjozork** [comment]
Are you entirely sure it had the exact same path ?

**Comment by CANADACLIPPER1953** [comment]
Sorry to keep bothering you. I just went back and checked. my path is E\
Users\name\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LoacalCache\Community

**Comment by CANADACLIPPER1953** [comment]
Just found the problem Ben. In my folder I had LocalCache as one word with
no space. Looks like I'm good to go now. Thanks again.

**Comment by Benjozork** [comment]
Perfect. No worries.

In the next installer release the message will be clearer and will give the option to re-specify the path.
