### ISSUE TITLE
Stable version .6 and latest Dev version crash my sim.

### ISSUE THREAD

**Issue by Jab50broncs** [flybywiresim/a32nx#4475]
When I updated my flybywire mod to version .6 and updated all the liveries my sim crashed on me.  The first thing I did was go to the discord and the response I got was to delete turn off dev mode then reinstall. I did this which confirmed it was the flybywire that was causing it.  I turned off dev mode in the sim and tried again and the sim crashed.  I tried the dev version as well and it also just crashed.  This is a true crash it will load in and nothing out of the ordinary is about the loading times but when the loading bar gets almost to the end the sim will either just close or there will be an error message.  It has happened 4 times in the last 30 minutes of trying for me. Any help would be appreciated.  

How to reproduce issue:
Get the flybywire .6 version of the mod
Go into MSFS2020
Wait until almost done loading
Sim crash

**Comment by Benjozork** [comment]
Please do not ignore the provided template.

**Comment by Benjozork** [comment]
You should try loading the plane without anything else in the community folder. It can't be asserted that it causes the crashes until you try that.
