### ISSUE TITLE
Bad stutter 

### ISSUE THREAD

**Issue by NeptuneP2V** [flybywiresim/a32nx#4486]
**Mod Version**

```json

```

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**
<Bad stutter occured both at LFRS and LFMN starting the bird from cold and dark in both stable and dev versions 0.6.0 with MSFS 1.15.8.0. using the FlyByWire livery. I tried with the Airbus House livery  on a full flight from these two airports and it worked pretty fine. I retried with the FlyByWire livery and stutter was back again, making the Sim nearly unplayable. It seemed however to be somewhat better in flight away from the airports. No FPS decrease was noticed. Anybody coming across the same bug?

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by andrejetcat** [comment]
uninstalling "broken" windows update KB5001330 makes a huge difference in my case! give it a try! ...And next time, please fill out the bug report by following the template.

**Comment by MisterChocker** [comment]
Please fill out the provided template.

**Comment by NeptuneP2V** [comment]
Sorry, first msg on the post.

**Comment by NeptuneP2V** [comment]
Tried again with Airbus House livery at dusk, and stutter is back even with this livery. Maybe my sim settings are too high. See tomorrow. I will try uninstalling win update KB5001330 too and let you know.

**Comment by NeptuneP2V** [comment]
Hi,
I uninstalled Win KB5001330, lowered graphic settings and stutter is still there. Anybody can help?
Thanx.

**Comment by andrejetcat** [comment]
may helpful to tell us your specs?!

**Comment by gsm350** [comment]
Hi NeptuneP2V - i have also same problem with 0.6 version, bad stutter. i have clean install and everything tried but no luck. The MS Airplanes and payware B737 have no problem at all. Could not find why only with this bird.

**Comment by Benjozork** [comment]
The MS airplanes and that 737 are extremely basic planes with no functionality. You have to expect it will not tax any system.

Anywho, can you try the development version? It could bring you better performance as I added an optimization for the EFB bundle size which could improve things.

**Comment by solidhorizon** [comment]
I have the same problems about stutter, after upgrade the airbus, and when flying in the near of airports, and when landing or departing there is bad stutter.
When in the air, it is okay I think.

**Comment by Benjozork** [comment]
We do not provide the MSFS multiplayer functionality. This is on Asobo to solve.

**Comment by BjoernHund** [comment]
I only want to inform the tread creator about our tests. From my site it was no reported error to the fbw team ;)

**Comment by gsm350** [comment]
I think thats the problem with rendering the other aircrafts, because it happens landing and in airports, if i am flying no issues

**Comment by NeptuneP2V** [comment]
hi
you're right BjoernHund. I deactivated the multiplayer mode into the sim and now the bird works like a charm. Thanx a lot for your great work but for sure Asobo has to solve this point.
