### ISSUE TITLE
Lights and light textures not loaded/present

### ISSUE THREAD

**Issue by tush0701** [flybywiresim/a32nx#4487]
**Mod Version**
```json
{
  "built": "2021-04-18T13:08:24+00:00",
  "ref": "master",
  "sha": "150539a70a45d45ac4b70801180d90b4cd25431c",
  "actor": "tracernz",
  "event_name": "manual"
}
```

**Describe the bug**
No lights are showing on the aircraft inside as well as outside. Only instrument lights visible.
Landing lights, Strobe lights, Dome lights, Panel lights light up, but no illuminations are present.

Issue for default as well as converted liveries.

**To Reproduce**

1. Select Fly-by-wire a32n and fly(preferably at night for better view)
2. Turn on lights(all through switches)
3. Some lights come on, without illumination, others like Landing lights, strobe lights etc. don't come on at all.

**Expected behavior**
All lights should behave as expected

**Actual behavior**
Lights either don't illuminate, or don't light up at all

**References**

![Screenshot (55)](https://user-images.githubusercontent.com/75409941/115148720-80133d00-a07e-11eb-98bf-54bb01eab342.png)
![Screenshot (56)](https://user-images.githubusercontent.com/75409941/115148725-81dd0080-a07e-11eb-92af-ad91f9eaabba.png)

**Additional context**

Was this working before/when did the issue start occurring?
Latest release

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment]
Please remove everything except the A32NX from your community folder and try again.

**Comment by tush0701** [comment]
It worked, reconverted all liveries. Things are fine now.
Thanks!

**Comment by MikeRos** [comment]
Looks like I'm having similar issue. There is nothing but Dev version of a32nx in Community folder. All EXT lights are not visible as Dome one. Dome lights panels brightness is changing, but there is no "rays". If you have any ideas how to solve it please tell me.

**Comment by tush0701** [comment]
Delete the addon aircraft and make a fresh install. Worked for me.

**Comment by MikeRos** [comment]
Thanks! Complete mod reinstalling worked.
