### ISSUE TITLE
Manual heading doesn't work after LOC APP go around

### ISSUE THREAD

**Issue by AverageInter** [flybywiresim/a32nx#4488]
**Mod Version**

```json
{
  "built": "2021-04-16T11:30:08+00:00",
  "ref": "master",
  "sha": "871b7d55fa7b57f1a4985e93f91f4e13f6380550",
  "actor": "tracernz",
  "event_name": "manual"
}
```

**Describe the bug**
After going around after doing a LOC approach, the manual heading selection does only work when LOC mode is engaged.

**To Reproduce**

1. LOC approach with TRK/FPA, multiple changes to FPA
2. Go around, leave LOC engaged
3. Engage Selected Heading mode

**Expected behavior**
Plane flies the selected heading

**Actual behavior**
Plane flies the selected ehading only when LOC mode is engaged

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):
AverageInter#2163

**Comment by Sacha-Bombard** [comment]
I also had this “bug” and the only solution I found is to disengage LOC and APPR as well.

**Comment by MisterChocker** [comment]
Can you retest this with the Experimental version?

**Comment by aguther** [comment]
Should be fixed with latest version, feel free to reopen if needed.
