### ISSUE TITLE
Aircraft Textures Don't Show Up

### ISSUE THREAD

**Issue by blazinga350** [flybywiresim/a32nx#4494]
**Mod Version**
```json
{
  "built": "2021-04-15T22:57:32+00:00",
  "ref": "v0.6.0",
  "sha": "981b2e4b0e89998d21a70fe26de54a2f10066f6e",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

**Describe the bug**
The aircraft does not show up when loaded into game. Only the exterior lights are shown. Even the cockpit does not show up. Image (Attached below) shows the navigation lights.

**To Reproduce**
1. Load aircraft onto a runway 30L or 30R at ksjc
2. 
3.

**Expected behavior**
The outside fuselage, wings, tail show up and the interior cockpit shows, so that i can interact with the buttons.

**Actual behavior**
Aircraft is loaded, but only exterior lights are shown.

**References**
![Capture](https://user-images.githubusercontent.com/76239244/115177362-e6e72500-a083-11eb-844e-5b6a5e92e1fa.jpg)

**Additional context**
This is not a livery issue because first i used a third-party livery, but then i tried the flybywire house livery and it still did not work.

Was this working before/when did the issue start occurring?
Today, after i updated to 0.6.0 stable.
Is this a problem in the vanilla unmodded game?
IDK

none

**Comment by blazinga350** [comment]
for some reason image does not show up. if you copy and paste image link it will show up.

**Comment by tracernz** [comment]
> 
> 
> for some reason image does not show up. if you copy and paste image link it will show up.

You are supposed to put the contents of `build_info.json` in between the backtick lines.

````
<!-- Please paste the contents from the build_info.json (located inside main aircraft folder) into the field (code block) below -->
```json
copy and paste build_info.json contents here
```
````

**Comment by tracernz** [comment]
Under flybywire-aircraft-a320-neo In your MSFS community packages folder.

**Comment by blazinga350** [comment]
It says that it does support .json file type

**Comment by blazinga350** [comment]
nvm it says
{
  "built": "2021-04-15T22:57:32+00:00",
  "ref": "v0.6.0",
  "sha": "981b2e4b0e89998d21a70fe26de54a2f10066f6e",
  "actor": "Benjozork",
  "event_name": "manual"
}

**Comment by MisterChocker** [comment]
Please try again with nothing except the a32nx in your community folder.

**Comment by MisterChocker** [comment]
This can also be caused by an incompatible livery.

**Comment by blazinga350** [comment]
It’s not an incompatible livery because the flyby wire house livery also does not work

**Comment by blazinga350** [comment]
When I have nothing in my community folder, the issue still occurs.

**Comment by MisterChocker** [comment]
Since no other have reported any issues like this, this looks like an issue on your end, if the issue still persist for you please do not hesitate to join our discord or github discussion tab to find a solution.
