### ISSUE TITLE
A320nx not loading anymore after computer change

### ISSUE THREAD

**Issue by jimihendrix272** [flybywiresim/a32nx#4499]
New computer, re-downloaded and installed MSFS2020, used the FlyByWire Installer and Stable tab.

"flybywire-aircraft-a320-neo" is in the Community folder and in there are the normal folders and json files etc. in there.
When I run the sim, it's obvious that A320nx has not loaded. 
It was so wonderful before but now back to the original MS version...
Hope you can help.
https://prnt.sc/11phqzy

**Comment by hotshotp** [comment]
please fill in the template provided to you, and then reopen the issue.

**Comment by jimihendrix272** [comment]
Ok, thanks. I shall try and find out where this "template" is to be filled out.
Many thanks

**Comment by Kamegohan** [comment]
In the installer look into the upper right corner, next to the "minimize" button. Click onto the "i"-button and you will be forwarded.
