### ISSUE TITLE
"refueling" during push back

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#4504]
**Aircraft Version**

```json
{
  "built": "2021-04-19T15:55:42+00:00",
  "ref": "experimental",
  "sha": "45c43f75b2297617d9cd9e621ff0004c9346303d",
  "actor": "aguther",
  "event_name": "manual"
}
```

**Describe the bug**

I was loading the plane in the SIM´s menu with ~9200kg (it was like 9187 or somethink because of the slider in the menue not accurate to every 1kg or so)
after loading the flight, cold&dark @ LEPA on the gate, FOB show 9060kg. Enough for the flight, so i continue with flight preparations. everthing normal until pushback. After connection the pushback-truck and start to push, i see the FOB rising to (exactly) 9200kg (during pushback!) i could see it onto the EFB fuel page, and also on the FOB indication @ upper ECAM. 
(I don´t want to point out the problem with the different fuel values - in the menu and after in the bus.)

**To Reproduce**

1. try to load the plane in the sims menu with ~9200kg
2. start the flight...FOB should indicate less than preselected in the sim
3. make a proper preflight, until pushback
4. watch fuel rising during pushback

**Expected behavior**

fuel should not rising during push back

**Actual behavior**

Fuel start rising during pushback to nearly preselected value earlier in the sims menu

**References**

-

**Additional context**

-
Was this working before/when did the issue start occurring?
i don´t know
Is this a problem in the vanilla unmodded game?
no

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment]
Have you used the EFB to managed FOB?

**Comment by andrejetcat** [comment]
no, i did not use the EFB refueling system. I set the fuel in the sim menu. Today, I´ve made another flight, same behaviour. start the flight with 10060kg. Start APU and make a 30 min preflight. shortly before push, the fuel was like 9980 or so (APU use) during pushback (via the EFB) the value starts rising to 10060 again. I don´t have screeshots or videos, but i try.

**Comment by CptBayer** [comment]
....the other "unwanted" refueling is after landing and taxi in. Fuel consumptuion is negativ ! always -12kg/hr... Fuel burn is sinking the fuel in the tanks is rising :-p ... funny ... saves money ... I wrote this in the general forum. I think this is a known issue  and will be fixed soon with the entire engine config ...

Greets Klaus

**Comment by MisterChocker** [comment]
@CptBayer which version of the aircraft do you use? (stable, master or experimental)

**Comment by solarisfire** [comment]
I had positive fuel flow during pushback today. Gained almost 1000kg of fuel pushing back and starting the engines under APU and taxiing out to the rwy. Hadn't touched the EFB.

**Comment by solarisfire** [comment]
Caught this on video: https://youtu.be/gEYzztKBNoo?t=413 (sorry for the crappy quality and lack of audio).

I don't think it's pushback related. Once engine 2 was stable I started engine 1 and that's when the magical fuel started appearing. This looks to be related to a few other GitHub issues to do with magical fuel creation at engine start.

**Comment by solarisfire** [comment]
Also the EGT starts rising before any FF which isn't logical. Fingers crossed the engine rework happens soon :-)

**Comment by MisterChocker** [comment]
@solarisfire This is already the new engine, startup procedure is just not yet modeled alongside many other things.

**Comment by MisterChocker** [comment]
Is this still an issue?

**Comment by MisterChocker** [comment]
Closing since no response from the op.
