### ISSUE TITLE
"Braking" applied upon sharp turns with Nose Landing Gear Steering

### ISSUE THREAD

**Issue by ghost** [flybywiresim/a32nx#4505]
**Aircraft Version**
{
  "built": "2021-04-18T16:55:51+00:00",
  "ref": "experimental",
  "sha": "f52894be67d287a02fe2918e9963d7464e5d8d7b",
  "actor": "aguther",
  "event_name": "manual"
}

**Describe the bug**
When doing tight turns on ground the aircraft seems to brake. It is impossible to make a full hand tiller displacement without harsh braking action. Even when the tiller is turned very slowly upon a certain degree the aircraft slows down drastically.

**To Reproduce**
Rolling with less than 10 knots and making full turns with the NLG steering.

**Expected behavior**
Sharp turns should be possible with the remaining kinetic energy. Real aircraft that park at stands A1 or B10 at Frankfurt have to make very sharp turns and they can do this without adding power.

**Actual behavior**
The aircraft stops when sharp turns are being done with the hand tiller.

**References**
This video shows parking at EDDF gate A01. Even though it is a V powered A321 the same applies to the LEAP NEO.
https://youtu.be/t0eDH212F60?t=1633

**Additional context**

Was this working before/when did the issue start occurring?
All versions I've tested before had the same behaviour.

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):
Cpt. Chaos
#3721

**Comment by MisterChocker** [comment]
The max amount you can steer the nosewheel without understeer is limited by the planes ground speed.
The reference you provided shows an A321 performing a sharp turn with less than 5kt gs (while the pilot applies thrust on the left engine).

**Comment by CptChaos0815** [comment]
Thank you for the explanation. I tried it again with the ground speed you mentioned at it worked much better. However, it steel feels to me that too much thrust is required to make tight turns. The aircraft slows down too quickly for my taste. But that should be judged by a real-world pilot which I am not. Please find attached a video of my tries.

https://www.youtube.com/watch?v=p4HxgQdIE00

**Comment by MisterChocker** [comment]
You are right, the roll resistance (ground/tire friction) simulation by the simulator is a bit off.

**Comment by CptChaos0815** [comment]
Maybe FBW can pass this on to Asobo and then your work might be done and this topic could be closed but watched/tracked?

**Comment by MisterChocker** [comment]
> Maybe FBW can pass this on to Asobo and then your work might be done and this topic could be closed but watched/tracked?

We are in contact with Asobo, but right now I cant say much more.

**Comment by donstim** [comment]
While there may be issues with ground friction and maybe the amount of friction added by wheel scrubbing, these can be overcome, but at the potential loss of realism in other aspects. For example, enough thrust can be added to the low speed, ground idle condition to provide what you would like to see.  But, this would also result in the airplane accelerating faster and reaching higher speeds when traveling in a straight line.

See the following example video: https://1drv.ms/v/s!Ajsy7Ey4_8uFznP9yzweyVTeFVsg?e=WaKIYf. In that video, thrust has been increased enough to allow a full 360 degree turn to be made, starting at 7 knots ground speed (well in looking at the video, it may have touched 8) without adding any additional thrust above idle. (I have questions about how realistic that is.) Look how quickly it then accelerates when moving in a straight line, reaching a ground speed of 54 knots by the end of the runway.

Maybe there is room for something in between that would improve on what we have now. But it should be based on some real data or pilot experience at what sort of acceleration rate to expect when traveling in a straight line (e.g, 0 to 20 or 30  in x seconds) and what sort of turn should the airplane be capable of and from what speed without adding thrust.

**Comment by sidnov** [comment]
Please check again with the new tiller implementation and feel free to reopen if needed
