### ISSUE TITLE
A/C spawns in different ADIRS status

### ISSUE THREAD

**Issue by ghost** [flybywiresim/a32nx#4506]
**Aircraft Version**
{
  "built": "2021-04-18T16:55:51+00:00",
  "ref": "experimental",
  "sha": "f52894be67d287a02fe2918e9963d7464e5d8d7b",
  "actor": "aguther",
  "event_name": "manual"
}

The aircraft spawns in various configs. Sometimes the ADIRS are aligned, sometimes not.

**To Reproduce**

Hitting the Fly Now button causes the a/c to "reboot" as all relays are clicking again and the engines start to spool up again. They don't shut down but when the aircraft gets spawned from the holding point onto the runway it seems as some systems re-initialize.

**Expected behavior**
Once the a/c has completely loaded it shouldn't re-initialize when the fly now button is clicked.

**Actual behavior**

Hitting the Fly Now button causes the a/c to "reboot" as all relays are clicking again and the engines start to spool up again. They don't shut down but when the aircraft gets spawned from the holding point onto the runway it seems as some systems re-initialize.

**References**

N/A

**Additional context**

Was this working before/when did the issue start occurring?
This issue is relatively new but I can't remember how many updates before this was introduced.

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):
Cpt. Chaos
#3721

**Comment by CptChaos0815** [comment]
This also applies to the displays. Sometimes they're in the 40sec test pattern, sometimes fully loaded. The aircraft doesn't seem to like the respawning from the holding point onto the active runway. If I load on a parking position everyathing is fine. But loading "on a runway" (which basically loads you at the hoalding point, hitting the fly now button confuses the just loaded Airbus.

**Comment by airfirefighter** [comment]
same problem here also 2 times it was everything completely dark and i didnt have the test pattern.
