### ISSUE TITLE
Unable to switch to Cockpit camera view from Showcase view

### ISSUE THREAD

**Issue by venkatm0106** [flybywiresim/a32nx#4510]
**Aircraft Version** A32NX FlybyWire V0.6.0

```json
{
  "built": "2021-04-15T22:57:32+00:00",
  "ref": "v0.6.0",
  "sha": "981b2e4b0e89998d21a70fe26de54a2f10066f6e",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

**Describe the bug**

When the Simbrief user ID is entered in the Company tab of the Electronic Flypad (EFB Tablet) and Enter is pressed on the Keyboard, the camera automatically goes into Showcase view and it is not possible to switch back to the Cockpit camera view. Even if the Cockpit camera tab is clicked, it still remains on Showcase. We have tried various buttons on the Keyboard as well such as 'End', 'Insert', Alt+Tab, Ctrl+Tab etc. , but it still remains on Showcase mode and we are unable to switch back to Cockpit camera view.

**To Reproduce**

1. Enter the Simbrief user ID in the Company tab of the EFB Tablet Electronic Flypad
2. Press Enter on the Keyboard
3. The camera automatically switches to Showcase view and remains in this view not allowing us to switch back to Cockpit view.

**Expected behavior**

Did not expect the camera to switch to Showcase view when Simbrief user ID is entered in the Flypad EFB Tablet.

**Actual behavior**

The camera automatically switches to Showcase view and remains in this view not allowing us to switch back to Cockpit view.

**References**

**Additional context**

Was this working before/when did the issue start occurring? After installing Flybywire V0.6.0

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
This is an MSFS issue with the sim not ignoring keybinds when using text fields.

**Comment by venkatm0106** [comment]
Hi Benjozork - How do we get around this issue at the moment? What is the workaround?

**Comment by Benjozork** [comment]
Using the enter key which isn't bound to cameras would work.
