### ISSUE TITLE
No fuelpump on checklist before engine and apu startup

### ISSUE THREAD

**Issue by Tech-Maou** [flybywiresim/a32nx#4513]
**Is your feature request related to a problem? Please describe.**

I am a newbie in MSFS and did want to start up the 320 via CHECKLIST. But there was no "fuel pump on" on either of those checklists before "Engine Start". Maybe im blind, but i did use following checklists in this order: 
- preliminary cockpit prep.
- cockpit preperation
- before start (non-interactive)
- engine startup
- after engine startup

**Describe the feature you'd like to see implemented**

add the checkpoints to turn on fuel pump for engines and apu

**References**

**Additional context**

As stated before im a beginner, but i think this is missing? When im wrong and those points are in the checklists, i did not find them... 
ANYWAY Thank you sooo much for this mod and the hard work!!! 

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by sidnov** [comment]
I checked this and can confirm. Opening a PR shortly to fix it :)

**Comment by krangerich** [comment]
There is no explicit fuel pumps step in the A320 SOPs. Fuel pumps are being activated at the "cockpit preparation" procedure, during the overhead scan. 

The corresponding part of the FCOM (Flight crew operating manual) looks like this:
![image](https://user-images.githubusercontent.com/7890659/115463860-8fd08400-a22c-11eb-8691-9e526ad86517.png)

**Comment by sidnov** [comment]
> There is no explicit fuel pumps step in the A320 SOPs. Fuel pumps are being activated at the "cockpit preparation" procedure, during the overhead scan.
> 
> The corresponding part of the FCOM (Flight crew operating manual) looks like this:
> ![image](https://user-images.githubusercontent.com/7890659/115463860-8fd08400-a22c-11eb-8691-9e526ad86517.png)

I was originally looking for this under Cockpit Preparation while it is sandwiched somewhere in Preliminary Prep :P
Anyway, I have added it only as a verification item, that can be ticked and skipped, and it does not need the fuel pump switches to be pressed in order to proceed with the rest of the flow.
