### ISSUE TITLE
Black screens

### ISSUE THREAD

**Issue by SergioGabi** [flybywiresim/a32nx#4514]
**Aircraft Version**

```json

```
A32NX

**Describe the bug**

Cant do anything to switch on.

**To Reproduce**

1.Start the fly with A320NX
2.
3.

**Expected behavior**

screens working

**Actual behavior**

black screens

**References**

**Additional context**

I dont have any kind of mod, the game is clear and it`s installed with flybywire installer
Was this working before/when did the issue start occurring?
with the updating 5.4
Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
Make sure to try with nothing else in your community folder.

Please also properly fill the provided template including the version number.

**Comment by SergioGabi** [comment]
> Make sure to try with nothing else in your community folder.
> 
> Please also properly fill the provided template including the version number.

Yeah, community folder is empty.

**Comment by Benjozork** [comment]
Which MSFS version?

**Comment by SergioGabi** [comment]
> Which MSFS version?

1.13.16

**Comment by MisterChocker** [comment]
@SergioGabi do you have any other liveries installed that are incompatible?

**Comment by SergioGabi** [comment]
> @SergioGabi do you have any other liveries installed that are incompatible?

No, any livery or external file

**Comment by wadie** [comment]
>  Is this a problem in the vanilla unmodded game?

Yes, at least for me it was the case.

I experienced the same issue you described, but with the vanilla a320.
A32NX (Leap) works fine.

Try to remove anything that has to do with a320, including anything in the official directory or parent directories.

**Comment by killyourradio** [comment]
> 
> 
> > Which MSFS version?
> 
> 1.13.16

Well, there's your problem.

**Comment by Benjozork** [comment]
@SergioGabi Buy the game.
