### ISSUE TITLE
ECAM ELEC Page Font Sizes

### ISSUE THREAD

**Issue by david4bu** [flybywiresim/a32nx#4515]
**Aircraft Version**

```json
{
  "built": "2021-04-19T18:55:39+00:00",
  "ref": "experimental",
  "sha": "c0b494cd0fc448ade05bc1a394fcbdaaae3e5de8",
  "actor": "aguther",
  "event_name": "manual"
}

```

**Describe the bug**

ECAM ELEC font sizes are incorrect

**To Reproduce**

1. Load any cold and dark flight
2. Perform normal startup proceedure
3. Select the ELEC page on the Lower ECAM

**Expected behavior**

Font Sizes Display as normal

**Actual behavior**

![image](https://user-images.githubusercontent.com/69039919/115447379-59850b80-a210-11eb-9eaa-dabe7d869f02.png)

**References**

![image](https://user-images.githubusercontent.com/69039919/115447557-8c2f0400-a210-11eb-8780-77525d02f7ef.png)

**Additional context**

Was this working before/when did the issue start occurring?
Yes, reflected upon downloading the latest experimental build [c0b494c](https://github.com/flybywiresim/a32nx/commit/c0b494cd0fc448ade05bc1a394fcbdaaae3e5de8) today at 17:00Z

Is this a problem in the vanilla unmodded game?
N/A (INOP)

Discord username (if different from GitHub): davcpas1234

**Comment by andrejetcat** [comment]
I do not have this issuein this version above..., until todays latest experimental: 

  "built": "2021-04-22T15:34:07+00:00",
  "ref": "experimental",
  "sha": "d98100079403696b1ede709969a97961ee1fed39",
  "actor": "aguther",
  "event_name": "manual"

**Comment by juztinp** [comment]
Saw this happen on a twitch stream 

https://www.twitch.tv/videos/996600709?t=7621s

**Comment by davidwalschots** [comment]
This very seldomly happens to some users. Restarting the flight should help. I've been unable to reproduce it. We've decided it's probably best to wait for the rewrite of the ELEC page to React.
