### ISSUE TITLE
Support Vatsim/Ivao integration EFB

### ISSUE THREAD

**Issue by artscout** [flybywiresim/a32nx#4519]
**Is your feature request related to a problem? Please describe.**

No, that's not really a problem, just the thing that most VR players would benefit mostly (probably)

**Describe the feature you'd like to see implemented**

Latest stable release (0.6.0) shown us left side tablet with simbrief and other features. That got me thinking, as I frequently flying with Ivao and it's a pain to take of your HMD to answer on some requets or to type commands, etc, would it be possible to communicate with Vatsim/Ivao/etc. clients and create simple interface that would allow pilot to enter commands for clients, along with virtual keyboard support? Cause solutions like virtual dekstop dash in oculus software, which allows us brind windows to VR doesn't really work, as MSFS-2020 too heavy and even trying to bring window in VR causes hangups. Of course that's a huge feature, but if there's  a chance to be implemented - it would be a great boon. 

**References**

**Additional context**

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment]
What type of commands are you talking about?

**Comment by myselfaaryan** [comment]
If you're talking commands such as .com1 .x then no, we have no plans to implement those for the moment.

**Comment by artscout** [comment]
Ok, thank you for info. Yep I meant those commands.
