### ISSUE TITLE
autopilot picks random waypoints from f-plan after passing a waypoint

### ISSUE THREAD

**Issue by uzytkownik** [flybywiresim/a32nx#4524]
**Aircraft Version**
Development cfcff47

**Describe the bug**
Sometimes (I haven't determined when but it happened to me on both flights after update) autopilot picks a random waypoint (usually a transition or via) as a next one. This causes plane in middle to ILS landing to try to go to STAR transition for example.

**To Reproduce**
1. Program flight
2. Check the plan is correct
3. Take off and turn on AP

**Expected behavior**
AP flies the path

**Actual behavior**
AP picks sometimes a random waypoint as a next one.

**Additional context**
Was this working before/when did the issue start occurring?

It was. It started after update from ae1feb6 to cfcff47.

Is this a problem in the vanilla unmodded game?

I haven't checked yet but only recent change that I recall was update of FBW.

**Comment by MisterChocker** [comment]
Impossible to be related to changes made in-between the noted version.

**Comment by uzytkownik** [comment]
I cannot repro it anymore.

**Comment by MisterChocker** [comment]
Closing since issue resolved.
