### ISSUE TITLE
LVR CLB don't flashing

### ISSUE THREAD

**Issue by manosony** [flybywiresim/a32nx#4525]
**Aircraft Version**

{
"built": "2021-04-19T18:55:39+00:00",
"ref": "experimental",
"sha": "c0b494cd0fc448ade05bc1a394fcbdaaae3e5de8",
"actor": "aguther",
"event_name": "manual"
}

Experimental Version

**Describe the bug**

 The LVR CLB doesn't flash when it reaches the right altitude to reduce Throttle to CLB position.

**To Reproduce**

1.Juts take off

**Expected behavior**

The LVR CLB is expected to appear blinking

**Actual behavior**

The LVR CLB simply appears and stays there until it reduces to CLB

**References**

The behavior

https://user-images.githubusercontent.com/32557880/115595287-1f1d7c00-a2ad-11eb-9480-610f2d9e40bc.mp4

**Additional context**

Discord username (if different from GitHub):

**Comment by lukecologne** [comment]
Please enable "menu animations" in the sim settings (general->accessibility), that should fix the issue

**Comment by manosony** [comment]
I'll see if it fixed now, it was really disabled

**Comment by manosony** [comment]
It remains the same, with the same bug

**Comment by MisterChocker** [comment]
please post the content of the build_info.json (as requested by the template).

**Comment by manosony** [comment]
{
  "built": "2021-04-19T18:55:39+00:00",
  "ref": "experimental",
  "sha": "c0b494cd0fc448ade05bc1a394fcbdaaae3e5de8",
  "actor": "aguther",
  "event_name": "manual"
}

**Comment by aguther** [comment]
Please restart the sim and try again.

**Comment by manosony** [comment]
It worked. It's working normally now.
