### ISSUE TITLE
The aircraft continuing gain speed even with Throttle on idle.

### ISSUE THREAD

**Issue by manosony** [flybywiresim/a32nx#4526]
**Aircraft Version**

```json

```
Experimental Version

**Describe the bug**

The aircraft continuing gain speed even with Throttle on idle.

**To Reproduce**

1. Give a little power to the aircraft to gain speed;
2.Then put Thrust in IDLE;

**Expected behavior**

The aircraft should lose speed over time

**Actual behavior**

Even in IDLE the aircraft continues to gain speed

**References**

https://user-images.githubusercontent.com/32557880/115596191-3741cb00-a2ae-11eb-9f44-e273f1102a80.mp4

**Additional context**

Discord username (if different from GitHub): ShelledTY

**Comment by Benjozork** [comment]
This is how it works in real life.

Please provide IRL references before claiming something is unrealistic.
