### ISSUE TITLE
vitesse élevé au roulage

### ISSUE THREAD

**Issue by snypa972** [flybywiresim/a32nx#4529]
**Is your feature request related to a problem? Please describe.**
l'A320 est très rapide au roulage (avec la version stable 0.6.0)  , même à 20Kts, le roulage est très élevé

**Describe the feature you'd like to see implemented**

**References**

**Additional context**

**Comment by Benjozork** [comment]
Bonjour, cela est fidèle au comportement de l'A320. Ce n'est pas un bug.

**Comment by snypa972** [comment]
Ok très bien.



Envoyé depuis mon appareil Galaxy



-------- Message d'origine --------
De : Benjamin Dupont ***@***.***>
Date : 21/04/2021 19:50 (GMT-04:00)
À : flybywiresim/a32nx ***@***.***>
Cc : snypa972 ***@***.***>, Author ***@***.***>
Objet : Re: [flybywiresim/a32nx] vitesse élevé au roulage (#4529)


Bonjour, cela est fidèle au comportement de l'A320. Ce n'est pas un bug.
