### ISSUE TITLE
Level positions resetting after hitting esc button

### ISSUE THREAD

**Issue by damour33** [flybywiresim/a32nx#4530]
**Aircraft Version**

```json
{
  "built": "2021-04-15T22:57:32+00:00",
  "ref": "v0.6.0",
  "sha": "981b2e4b0e89998d21a70fe26de54a2f10066f6e",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

**Describe the bug**

When ever I return to the sim after hitting the Esc key to go into settings, the throttle, speed break and flaps levers all seem to be centered, resulting in wrong power setting, 50% speed break deployed and a flaps 2 setting. I've tried deleting the Fly by wire 320 folder and reinstalling but the issue remains. Since I am using a Honeycomb Bravo throttle quadrant and those three levers are all mapped to the throttle levers, I suspect it has something to do with not remembering the settings.

**To Reproduce**

1. (using a Bravo throttle quadrat) - Start a flight
2. hit the Esc key (on the ground or in flight, doesn't matter)
3. Hit Esc again or use the mouse to return to the sim (making or not making option changes doesn't seem to matter)

**Expected behavior**

The lever settings should match the physical lever settings on the Bravo throttle quadrant.

**Actual behavior**

The power, speed break ad flaps levers in the sim all reset to %50 position.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Didn't have this problem before. I recently reinstalled the whole sim and the 320NX mod - right before world update 4 came out. 

Is this a problem in the vanilla unmodded game?
haven't tried. I am using the stand alone A320NX.

Discord username (if different from GitHub):
damour#1820
*

**Comment by Benjozork** [comment]
This is an MSFS bug in world update 4

**Comment by damour33** [comment]
Thanks.

Lior
