### ISSUE TITLE
PERF CLB Pre-Selected Speed not adhered to

### ISSUE THREAD

**Issue by frankkopp** [flybywiresim/a32nx#4531]
**Aircraft Version**
```json
{
  "built": "2021-04-19T18:55:39+00:00",
  "ref": "experimental",
  "sha": "c0b494cd0fc448ade05bc1a394fcbdaaae3e5de8",
  "actor": "aguther",
  "event_name": "manual"
}
```

**Describe the bug**
To be able to have the plane limit speed after take off (after SRS) you can use the PERF CLB page to set a pre selected speed. 
The page exists and you can enter a value. But the plane does not adhere to this speed and speeds up to 250kts. 

**To Reproduce**
1. Start any flight 
2. Enter a Speed into the PERF CLB page
3. Take Off and wait until CLB phase - look at speed

**Expected behavior**
According to Shomas the plane should adhere to the selected speed in the MCDU:
![Screenshot 2021-04-22 101206](https://user-images.githubusercontent.com/16833201/115680246-b1785b00-a353-11eb-8219-51ca3f05bf80.png)

**Actual behavior**
Plane accelerates to 250kts:
![Screenshot 2021-04-22 101140](https://user-images.githubusercontent.com/16833201/115680292-bd641d00-a353-11eb-8c99-c1b028304c60.png)

**References**
![Screenshot 2021-04-22 094319](https://user-images.githubusercontent.com/16833201/115680312-c05f0d80-a353-11eb-83ac-f02e59ab4438.png)

Was this working before/when did the issue start occurring?
unknown

Is this a problem in the vanilla unmodded game?
surely not :)

Discord username (if different from GitHub): Cdr_Maverick

**Comment by MisterChocker** [comment]
This should actually work, I'll need to check

**Comment by frankkopp** [comment]
I tested it three times now and it does not adhere to the CLB speed.
Of course I might be doing something wrong but from would I have understand so far it should not be complicated.
