### ISSUE TITLE
brake-temp after autobrakeLOW/manual brake landing 

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#4532]
**Aircraft Version**

{
  "built": "2021-04-19T18:55:39+00:00",
  "ref": "experimental",
  "sha": "c0b494cd0fc448ade05bc1a394fcbdaaae3e5de8",
  "actor": "aguther",
  "event_name": "manual"
}

**Describe the bug**

Was was on a Approach into GCTS. Autobrake for landing - LOW. After touchdown i do not really feel a deceleration with the LOW setting, so I used MANUAL braking (both(!) pedals press to floor) to reach the highspeed taxiway to the right. after I was clear of RWY, I had a look onto the lower ECAM and recognise, that the right brakes are even more hot than the left ones like my screenshot show. It seems that the left ones did not brake significantly. Again, the Autobrake light stays on while switch to MANUAL braking, as discribed in my other bug report. I know, brakes do not heat up 100% equal while braking, but there must be an issue if the brakes are only 60°C after a landing with a loaded A320.

**To Reproduce**

1. make a approach followed by a landing with autobrake low selected
2. after couple of secounds after touch down, apply manual braking
3.look @ lower ECAM - BRAKE TEMP - hopefully see what my screenshot is about.
![brake temp bug](https://user-images.githubusercontent.com/72918017/115706950-7c2d3680-a36e-11eb-9b66-a76dcedc27c6.jpg)

**Expected behavior**

brakes should work nearly equal when autobrake is used or when manual brakes are used with BOTH(!) pedals equal press

**Actual behavior**

brakes do now work equal , as you can see on brake temp. (NO ASYMETRIC brakes were used)

**References**

see screenshot above

**Additional context**

Was this working before/when did the issue start occurring?
yes, as I remember
Is this a problem in the vanilla unmodded game?
no

Discord username (if different from GitHub):

**Comment by donstim** [comment]
I don't know what is going on with your airplane, but I could not re-create your issue.  What type of controller are you using for braking and how do you have it set up?  I have rudder pedals with separate axes for right and left pedals.

First test:  Autobrake medium. Screenshot during braking showing symmetric braking and brake temps:
![Screenshot (769)](https://user-images.githubusercontent.com/70166617/115793134-76d8e780-a380-11eb-8735-c9fff6197ef1.png)
After stopping, autobrakes off, consistent brake temps:
![Screenshot (770)](https://user-images.githubusercontent.com/70166617/115793249-a5ef5900-a380-11eb-8702-316f7d835415.png)

Second test: Manual braking. After stopping, brake temps:

![Screenshot (772)](https://user-images.githubusercontent.com/70166617/115793607-46457d80-a381-11eb-8997-0d76bac5e864.png)

**Comment by andrejetcat** [comment]
I use the thrustmaster Pedals, also with each side individually. I will try it again - i have the thrustmaster Airbus throttle and a keybinding to arm the autospoilers. Maybe the issue is connected with that! I try it as soon as I can!

**Comment by andrejetcat** [comment]
problem found from my side - it was the keybinding "arm autospoiler". Arming via cockpit, problem is gone!  Sorry for that!

**Comment by donstim** [comment]
That's great! Glad you found the problem.
