### ISSUE TITLE
Installer v1.2.0 Hangs up each time I try to do a update!! The website freezes up and I have to go to the Device Manager to End Task!! What I've been doing is completely removing the Aircraft and reinstalling the update!! Thanks

### ISSUE THREAD

**Issue by Razor1968** [flybywiresim/a32nx#4533]
**Aircraft Version**

```json

```

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by scoopscode** [comment]
Hello, please follow the template rather than stating your issue in the title. This issue may or may not be closed soon by a maintainer.

**Comment by Benjozork** [comment]
This is not the installer or website repository.
