### ISSUE TITLE
Airplane Behaviour on ILS

### ISSUE THREAD

**Issue by Majakk01** [flybywiresim/a32nx#4535]
**Aircraft Version**

```json
{
  "built": "2021-04-22T15:34:07+00:00",
  "ref": "experimental",
  "sha": "d98100079403696b1ede709969a97961ee1fed39",
  "actor": "aguther",
  "event_name": "manual"
}
```

**Describe the bug**

When established on the ILS, I put flaps 3, after this the plane violently pitched down to about -10 degrees. But regardless of that it started climbing at 2000 fpm and my speed started dropping. The same happened when I put flaps full and even when flying manually.

**To Reproduce**

1. The plane in APP mode and fully established on the ILS.
2. Setting flaps to 3 or Full.

**Expected behavior**

**Actual behavior**

Small pitch corrections and maintaining the correct speed and glideslope.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
It was working before, it's the first time I encountered this.

Is this a problem in the vanilla unmodded game?
Not as for as I know

Discord username (if different from GitHub):
Brent Cornelis#8107

**Comment by donstim** [comment]
Does this occur every time you try an ILS approach? Can you provide a video?

**Comment by MapleNAV-TCASFAULT** [comment]
You're most likely on the Legacy flight model, it is highly recommended to use the Modern flight model!

**Comment by Majakk01** [comment]
> You're most likely on the Legacy flight model, it is highly recommended to use the Modern flight model!

Yes you are correct. I didn't know this. Is there maybe an install guide somewhere that I missed?

**Comment by mbakker96** [comment]
Yesterday I was not able to reproduce this on the EHRD ILS 6 approach.

**Comment by tracernz** [comment]
When we say modern flight model, we mean this:
![image](https://user-images.githubusercontent.com/9995998/115845139-a8cb7600-a474-11eb-94a9-1ac3d96217e5.png)
Also make sure you're actually using the FBW A320 and not the Asobo one.
Asobo: 
![image](https://user-images.githubusercontent.com/9995998/115845314-d2849d00-a474-11eb-99ef-5b627ee82477.png)
FBW:
![image](https://user-images.githubusercontent.com/9995998/115845349-dc0e0500-a474-11eb-913e-fc57704acf5f.png)

**Comment by Majakk01** [comment]
> When we say modern flight model, we mean this:
> ![image](https://user-images.githubusercontent.com/9995998/115845139-a8cb7600-a474-11eb-94a9-1ac3d96217e5.png)
> Also make sure you're actually using the FBW A320 and not the Asobo one.
> Asobo:
> ![image](https://user-images.githubusercontent.com/9995998/115845314-d2849d00-a474-11eb-99ef-5b627ee82477.png)
> FBW:
> ![image](https://user-images.githubusercontent.com/9995998/115845420-f0ea9880-a474-11eb-9925-4f12bf120664.png)

Yes I know what you mean and what the flight model is. I just didn't know it was required to be on 'modern' for the fbw

**Comment by aguther** [comment]
> > You're most likely on the Legacy flight model, it is highly recommended to use the Modern flight model!
> 
> Yes you are correct. I didn't know this. Is there maybe an install guide somewhere that I missed?

If you have a look on the Important section in the readme linked in the dialogue of experimental install:
https://github.com/flybywiresim/a32nx/tree/experimental/docs

**Comment by Majakk01** [comment]
> > > You're most likely on the Legacy flight model, it is highly recommended to use the Modern flight model!
> > 
> > 
> > Yes you are correct. I didn't know this. Is there maybe an install guide somewhere that I missed?
> 
> If you have a look on the Important section in the readme linked in the dialogue of experimental install:
> https://github.com/flybywiresim/a32nx/tree/experimental/docs

Okay it's all on me then. My apologies :)

**Comment by aguther** [comment]
No problem, we also had to learn that. So it was not from the beginning clear that this is needed…there are so many different conditions / configurations and sometimes stuff that you just imagine could make a difference…
