### ISSUE TITLE
Extreme lag and stutter

### ISSUE THREAD

**Issue by Jetleg100** [flybywiresim/a32nx#4538]
**Aircraft Version**
Devolop and stable version 0.6

**Describe the bug**
After the last world update with France and Benelux, it was not possible to fly from any of these countrys. A lot of stutter (1-2 fps). 
All the last development versions have been like this. Same goes for stable version. Today, Microsoft released a update. This didn`t help.   
I have a high end computer. Tried to downgrade the driver in order to a previous version when the simulator were ok. This issue is only present with the A32NX. When i flyes the Aerosoft CRJ or any other aircraft, everything runs smooth. 

Hope any can help me here. I love the A32NX, bit like it is now, it`s useless. 

**To Reproduce**
I made a short video showing pushback. There you can see the stutter. And it only get worse when accelerating down the runway.  
https://youtu.be/AOcJuhzW7Rw

We need to know how you encountered the bug to properly troubleshoot the issue. -->
1. After the last world update
2.
3.

**Expected behavior**
Smooth with good fps

**Actual behavior**
stutter with very low fps

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
Can you try disabling multiplayer in MSFS settings, it's a known issue with some aircraft since world update 4

**Comment by Paytheon** [comment]
Microsoft so much as admits there is FPS performance issues with this last update: 
![image](https://user-images.githubusercontent.com/7406643/115781269-007fb980-a36f-11eb-803e-e2543d37ca51.png)

**Comment by Jetleg100** [comment]
Solved! 
Issue were caused by the Multiplayer option enabled. Changed to off and everything was ok again. Fantastic:) Can finally continue with this wonderful aircraft:) 
But nevertheless, since this only happen with the A32NX,  it must be an issue with the sim or aircraft?

**Comment by Benjozork** [comment]
It also happens with other planes and is most likely unrelated to their aircraft.
