### ISSUE TITLE
[BUG] No Display on FCU

### ISSUE THREAD

**Issue by majc888** [flybywiresim/a32nx#454]
**Mod Version**

master

**Describe the bug**

All my displays work except for the FMU and Pressure displays.

**To Reproduce**

1. Downloaded mod and the issue was there when i started the airplane
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

**Comment by NathanInnes** [comment]
Not sure what you are trying to describe. Can you please provide a screenshot?

**Comment by TheTreeThatGrows** [comment]
increase the brightness and light on the FCU. It is turned to lowest brightness at the beginning and needs to be turned on manually

**Comment by majc888** [comment]
Sorry guys. First time posting. On my FCU Display and Altimeter Setting [ SPD HDG AP/AT ALT V/S ]  I have no visual display, just a black screen. I tried adjusting the all the dials i see but still no display. Thanks for responding though

**Comment by NathanInnes** [comment]
Make sure you are using this one please. 
![image](https://user-images.githubusercontent.com/18389085/92330004-9aeeef00-f063-11ea-8634-2fe67c154b69.png)

**Comment by TheTreeThatGrows** [comment]
There is a dial under the "exped" button on hte FCU just below the altitude dial. It says "Increase FD brightness", turn it up

**Comment by TheTreeThatGrows** [comment]
yeas that one hahhaha

**Comment by majc888** [comment]
Ok, did not realize the knob below dash, feel like an idiot! Everything is working great. Thanks again for help.

**Comment by NathanInnes** [comment]
In future please use discord for problems. GitHub is used for bugs. If you do have any more problems then try asking around on discord first :)

Please close this issue.
