### ISSUE TITLE
Add REFUELG for EFB Refuelling 

### ISSUE THREAD

**Issue by tshomas** [flybywiresim/a32nx#4542]
**Is your feature request related to a problem? Please describe.**
Addition of ECAM Memo, REFUELG for when EFB refuelling is ongoing.

**Describe the feature you'd like to see implemented**
REFUELG is in real life the opening of the refuelling panel on the A320, but we could connect it to the EFB refuelling page in the same logic that we already have built into the mod as for when the MSFS fuel truck arrives. I don't have the experience required to code this, but I would hazard as a layman that the possibility of setting a variable to be active while the refuelling is happening and this would trigger the memo active state?

**References**
![image0](https://user-images.githubusercontent.com/74841560/115794858-af031900-a3c6-11eb-9c1a-10b0c546d429.jpg)

![ewd jpg 8f11b46b0368945060a0b51cf203c13f](https://user-images.githubusercontent.com/74841560/115794906-c9d58d80-a3c6-11eb-84dc-dba85da590fd.jpg)

**Additional context**

Current REFUELG Memo Logic (I hope if I found it right?)
https://github.com/flybywiresim/a32nx/blob/3cc1593326720076d018f0f9be878bbf46ff6ab3/A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js#L980-L983

Discord username (if different from GitHub): Shomas

**Comment by sidnov** [comment]
@tshomas Thanks a ton for the code reference, made work a lot easier. Would be opening a PR in a few mins 😄 

![image](https://user-images.githubusercontent.com/29005005/115843947-ffb55900-a43c-11eb-97f3-f504c9955a7e.png)

**Comment by tshomas** [comment]
Awesome, I did look at the code and thought it would be better suited for someone waaaaaay more intelligent than myself!
