### ISSUE TITLE
When will MCDU be programmed for RNAV or VOR approaches?

### ISSUE THREAD

**Issue by alainzu** [flybywiresim/a32nx#4545]
**Is your feature request related to a problem? Please describe.**

MCDU does not allow correct GPS or VOR/DME approaches.

**Describe the feature you'd like to see implemented**

The V/DEV needs to be implemented to allow correct altitude reduction during final approach.

**References**

**Additional context**

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by tracernz** [comment]
See https://github.com/flybywiresim/a32nx/issues/4028 for next steps. Patches welcome.

Well known issue so I don't think we need another.
