### ISSUE TITLE
When will the MCDU be programmed for RNAV or VOR DME approaches

### ISSUE THREAD

**Issue by alainzu** [flybywiresim/a32nx#4548]
**Aircraft Version**

```json

```

**Describe the bug**

The Asobo A320 or A32NX do not allow a precise non-precision approach (RNAV GPS or VOR DME).
There is no indication of the V/DEV from the calculated glideslope.

**To Reproduce**

1. Program the MCDU for a RNAV arrival
2. Just before the FAF engage APPR
3. You need to set the alt below the missed altitude if you want the aircraft to descend down to the MDA
4. The aircraft may begin its descent but there is no indication of V/DEV on the PFD
5. In practice, the aircraft does not follow the glide with accuracy in the majority of the cases

**Expected behavior**

I expect: 1-indication of V/DEV on the PFD, 2-a correct descent alt

**Actual behavior**

The aircraft does not follow the glide when a non-precision approach is selected

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by aguther** [comment]
See #4028 for next steps. Patches welcome.

Well known issue so I don't think we need another.
