### ISSUE TITLE
Changes to the weight unit in the MCDU are not persisted

### ISSUE THREAD

**Issue by BjoernHund** [flybywiresim/a32nx#4554]
**Aircraft Version**

```json
{
  "built": "2021-04-23T22:07:54+00:00",
  "ref": "master",
  "sha": "c43d0267084cae66e5cb3950c1c76e9b78bf43d0",
  "actor": "aguther",
  "event_name": "manual"
}
```

**Describe the bug**

Changes to to weight unit in the options menu of the MCDU are not persisted when closing the sim

**To Reproduce**

- Change the weight unit in the options menu of the MCDU from `kg` to `lbs`
- Go back to the main menu and start a new flight
- The weight unit is still `lbs` as expected
- Restart the sim
- The weight unit has been reset to `kg`

In the sim I use the US-System

**Expected behavior**

Changes to the weight unit are persited 

**Actual behavior**
Changes to the weight unit are not persited when closing the sim

Was this working before/when did the issue start occurring?

In the previsous dev version, the weight unit was persisted, even when closing the sim

Discord username: Björn#7582

**Comment by MisterChocker** [comment]
How did you `Restart the sim` ?
Did you used `alt`+`F4` or exited the sim normally?

**Comment by BjoernHund** [comment]
I exited the sim normals via the menu as everytime. In about 2 hours I will do another test. I set it again, fly an existed the sim normal

**Comment by BjoernHund** [comment]
Can you tell me, were it would be stored, then I can look for it. I can also try to look in the source code

**Comment by BjoernHund** [comment]
@MisterChocker 
You can close these issue. I started now the sim again, and the correct, previously stored weight unit was loaded. I don't know what the first time was going wrong. After every bigger update from you, I do the same. Delete the flybywire folder, install the dev version new, go to the sim and change and save the settings.

Sorry. I hope you have not spend so mutch time for it.

**Comment by BjoernHund** [comment]
@MisterChocker 
It is back again. Another flight with a new started sim. I turned on the batteries, an the weight united is reseted to `kg`.

**Comment by MisterChocker** [comment]
Changing the unit and then exiting the sim via the menu and not ALT + F4 should save the settings.
I confirmed this again with our contributors.

**Comment by BjoernHund** [comment]
@MisterChocker 
Can it have something todo with updating the sim via the installer. Yesterday, before it was reset to `kg`, I updated the dev version from `c43d026` to `43a8c41`.

I'v also reviewed the code and couldn't find anything that explains this error. 

Can you tell me, were it will be stored, so I have the change to save this setting?

**Comment by MisterChocker** [comment]
Yeah, updating the AC version can reset settings.
Iirc it's stored somewhere in the sims cache and you can't easy edit it due to the way/format it's saved.

**Comment by BjoernHund** [comment]
@MisterChocker 
Thanks for the information. I now know what can cause my issue. I will close this. 

Thanks for your help.
