### ISSUE TITLE
Switching from VR to Desktop mode triggers AP to fly back to previous waypoint on flightplan

### ISSUE THREAD

**Issue by Funkythrusta** [flybywiresim/a32nx#4558]
A320neo v.0.6 in VR mode at cruising attitute.
Switching back to desktop mode with Strg-Tab triggers AP to return to previous waypoint. 
Need to reconfigure flightplan manually to get back on track. Using HP Proverb G2.
Otherwise exciting sim plane!

**Comment by 2hwk** [comment]
Fixed by 4953 closing ☑️
