### ISSUE TITLE
battery voltages are zero and screens are completely black when loaded in

### ISSUE THREAD

**Issue by willc246** [flybywiresim/a32nx#4560]
**Aircraft Version**

```json

```

**Describe the bug**

when i load in to the plane at the gate or on the runway the battery voltages are shown as zero and the screens are black or wont turn on. the plane worked completely fine yesterday it was only after i downloaded the recent developer build this morning that the problem occurred. after this i tried the stable build and the same problem happened. i could still fly the plane though

**To Reproduce**

1. i downloaded the latest developer build
2.
3.

**Expected behavior**

the plane to work normally and the screens to turn on

**Actual behavior**

battery voltages were zero and screens didn't turn on but i could still fly the plane

**References**

**Additional context**

Was this working before/when did the issue start occurring?
this was working perfectly yesterday before i downloaded the new developer build
Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub): willc

**Comment by airfirefighter** [comment]
i mention in 4506 that i had 2 times also this issue

**Comment by airfirefighter** [comment]
i use co pilot mode i delete it and i didnt have again this problem do u use it ?

**Comment by Andrey2222222ship** [comment]
А как использовать второго пилота?

**Comment by Benjozork** [comment]
@hotshotp

**Comment by hotshotp** [comment]
> А как использовать второго пилота?

Эта модификация не поддерживается нашим модом.

**Comment by Andrey2222222ship** [comment]
А что можно еще сделать?

**Comment by Andrey2222222ship** [comment]
Я уже все пробывал, даже и не знаю что уже делать

**Comment by Andrey2222222ship** [comment]
У меня просто аналогичная проблема, не показывает напряжение и экраны не горят

**Comment by Andrey2222222ship** [comment]
@hotshotp

**Comment by hotshotp** [comment]
> @hotshotp 

Используйте мод а32nx с пустой папкой "community". Там должно быть пусто кроме flybywire-aircraft-a320-neo

**Comment by Benjozork** [comment]
You can use liveries and other things but the second pilot mod is broken

**Comment by Andrey2222222ship** [comment]
В папке ничего нету

**Comment by Andrey2222222ship** [comment]
Только сам пак на А320 и все

**Comment by Andrey2222222ship** [comment]
@hotshotp

**Comment by hotshotp** [comment]
> @hotshotp 

Я тогда не знаю, извините

**Comment by MisterChocker** [comment]
Has this issue been resolved? Whats the status?

**Comment by willc246** [comment]
Yes thanks. I had to reinstall the mod a few times and eventually it worked.
