### ISSUE TITLE
EGT back to high indication with ENG off

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#4561]
**Aircraft Version**

```json
  "built": "2021-04-23T22:37:56+00:00",
  "ref": "experimental",
  "sha": "c43d0267084cae66e5cb3950c1c76e9b78bf43d0",
  "actor": "aguther",
  "event_name": "manual"
```
BUT SAME WITH DEVELOPER Version from this date - TRIED BOTH

**Describe the bug**

adressed in #4146 i pointed out the high engine-EGT prior engine start/with ENG off. this is marked as SOLVED within the new engine-model, but after todays update (experimental and Developer) the phenomena is back again.
![highEGT](https://user-images.githubusercontent.com/72918017/115967802-e8599700-a534-11eb-87cd-c28ec0ee1e29.jpg)
high EGT with ENG off

at this point, I can´t find out, if this is a known bug with ne new model, so I want to point it out again. If its known, please close 

**To Reproduce**

1. BAT 1+2 on, look @ ECAM´s EGT
2.
3.

**Expected behavior**

EGT should more or less equal to OAT prior engine start. (no flight before, shure)

**Actual behavior**

EGT ~400°C with ENG off

**References**

![highEGT](https://user-images.githubusercontent.com/72918017/115967884-687ffc80-a535-11eb-8cff-7926d42c3ce5.jpg)

**Additional context**

Was this working before/when did the issue start occurring?
yes, the last updated, it was working. EGT only rise, after ENG start.
Is this a problem in the vanilla unmodded game?
no

Discord username (if different from GitHub):

**Comment by Taz5150** [comment]
This is a known issue due to the new engine model. Will be solved when the start-up procedure has been programmed.
