### ISSUE TITLE
Altitude not engage after TA

### ISSUE THREAD

**Issue by manosony** [flybywiresim/a32nx#4566]
**Aircraft Version**

```json
{
  "built": "2021-04-24T19:05:06+00:00",
  "ref": "master",
  "sha": "43a8c41776d5b381af620ecc47fcfdaab29bee3b",
  "actor": "aguther",
  "event_name": "manual"
}
```

**Describe the bug**

Altitude is not maintained or reached after changing from STD to QNH at Transition Altitude. Even engaged or managed

**To Reproduce**

1.Pass Transition Altitude and hit the adjust button

**Expected behavior**

The plane is expected to maintain the previously designated altitude, for example, in this case 4000, but this does not happen.

**Actual behavior**

https://user-images.githubusercontent.com/32557880/115973015-5c417280-a528-11eb-9816-2c17741cadf0.mp4

**References**

https://youtu.be/oQ_PbkICljk?t=2305 At 38:35 minutes, the aircraft tries to maintain an altitude of 6,000 feet before the pilot changes to 3,000 feet.

**Additional context**

In the video I pull and push the altitude button, but the aircraft does not respond to the command and does not maintain 4000 feet unless I change the altitude.

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment]
Please also fill in `Expected behavior`, `Actual behavior` and `References`

**Comment by manosony** [comment]
Changes made

**Comment by MisterChocker** [comment]
What does `hit the adjust button` mean?

**Comment by manosony** [comment]
Press the button to switch from STD to QNH 29.90, for example

**Comment by AirbusA320Pro** [comment]
From the video, the ALT selector remains at 4000', you don't select any other altitude, the aircraft remains ALT locked at 4000'. You don't Pull STD, nor adjust QNH. From what I can see in the video, there is nothing wrong with the aircraft behaviour. Incorrect equipment usage is suspected.

**Comment by manosony** [comment]
What happens in the video is that after I press the button I change from STD to QNH, due to this change the altitude also changes, causing 3960 feet to appear, for me the correct behavior would be for the aircraft to start climbing to 4000 feet, but it doesn't. Sometimes when the difference in barometric pressure is greater, the difference in altitude is also greater, reaching up to 1000 feet of difference, for example. But even so, the aircraft does not correct the altitude.

**Comment by tracernz** [comment]
ALT mode memorises the target altitude when it engages, and is not affected by changes to FCU or baro setting. To make it climb you have to engage another vertical guidance mode (e.g. press/pull the alt knob).

**Comment by manosony** [comment]
Apparently it’s being affected and doesn’t maintain altitude, but I’m going to do another test

**Comment by tracernz** [comment]
Your baro correction will change the ALT tape on the PFD, but not the ALT mode target, by the FCOM:
![image](https://user-images.githubusercontent.com/9995998/115979183-95392000-a5d8-11eb-8eda-0ba482a4070f.png)

**Comment by manosony** [comment]
But why does he apparently not keep 4000 feet ?? It is at 3960 and does not go up alone.

**Comment by aguther** [comment]
Because it memorizes pressure altitude on engage of ALT mode. Any change of baro settings after that will have no effect. The other thing is there are requirements to altitude difference etc. to engage another mode.
Recommendation: set QNH during descend and not after you have reached an ALT.
