### ISSUE TITLE
Incorrect EFB Fuel Tank Capacities (Again)

### ISSUE THREAD

**Issue by donstim** [flybywiresim/a32nx#4569]
**Aircraft Version**

```json
"built": "2021-04-24T19:05:06+00:00",
  "ref": "master",
  "sha": "43a8c41776d5b381af620ecc47fcfdaab29bee3b",
  "actor": "aguther",
  "event_name": "manual"
```

**Describe the bug**

The EFB fuel tank capacities are incorrect. The latest developer version of the mod reverted https://github.com/flybywiresim/a32nx/pull/4391, which had fixed them and closed https://github.com/flybywiresim/a32nx/issues/4322.  Due to changes in how the fuel flow system is used in the new developer version, the previous fix to this issue cannot be used in its entirety. (Portions of it could still be used to at least partly fix this issue.)

Someone who understands exactly what changes were made to fuel system that prevents the previous fix from working needs to address this, either by making changes that will allow the previous fix to be applied again, or by providing a new fix that will work with the new fuel system. I would be glad to work with whoever that may be to get this issue fixed (again).

This screenshot illustrates the issue. Note the differences between the fuel tank capacities shown in the EFB compared to the MSFS weight and balance window.
![Screenshot (783)](https://user-images.githubusercontent.com/70166617/115974821-6c4f5700-a514-11eb-8dfd-0ca741c40e49.png)

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

For more information, see the previous issue and pr referenced above.
Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):donbikes#4084

**Comment by CptChaos0815** [comment]
The capacities of the aircraft itself seem to be off too as this screenshot shows:

![Unbenannt-1](https://user-images.githubusercontent.com/82841421/116003775-ba8d5480-a5ff-11eb-8b8e-7c5c381a448c.jpg)

**Comment by donstim** [comment]
No, the usable fuel quantities are correct as explained in the previous PR referenced above. MSFS fuel tank capacity is in U.S. Gallons. Other units are derived using MSFS conversions, which may be (are) different than used in the tables you provided.  Note that the weights in those table are based on a specific gravity of 0.785, which is a density of about 6.55 lb/gal. MSFS uses a fuel density of about 6.7 lb gal.

Unusable fuel is not handled correctly by the MSFS new fuel system, also explained the previous pr.
