### ISSUE TITLE
Issue with Navigraph

### ISSUE THREAD

**Issue by danpowel** [flybywiresim/a32nx#4571]
is this text block where i report a bug in fbw a32nx and not get deleated by moderator? ,,please advise, will follow your procedures....is this OK

**Aircraft Version**

```json

```

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
There is a template below what you typed that you needed to follow. You have not.

If you prefer more informal support, you should ask in our #suopport channel on Discord.

**Comment by danpowel** [comment]
ok... some of the template doesn't apply, some do.....also after abidding to the template do i deleate it as it seems t does

**Comment by Benjozork** [comment]
You just put the required information under the titles.

Again I heavily suggest you use our Discord server for this.

Otherwise I can help here. What issue are you having

**Comment by danpowel** [comment]
thx so much.....can't use discord because i dont have cell phone, just landline.. in my late 70's and i never got one.....the FBW A32nx was just upgraded w/ver V0.6.0 and my mcdu went crazy.  cant put a star in mcdu locksup and cant get back to fltpln page to look at waypoints etc.  Tried deleating the mod and reinstalling it but it got worse...fyi--the original a320neo MCDU works ok
cant figure it out...any help would be thankful

**Comment by Benjozork** [comment]
No worries there. The cell phone requirement is sadly necessary because we get a lot of people who try to evade bans.

Do you happen to have the Navigraph navdata installed on your flight sim?

I've heard reports of it causing problems like that for some people.

If you do, could you try disabling it so we can isolate the issue?

**Comment by danpowel** [comment]
Just thought of somthing else Navigraph bought simbreif    ..........I was just going to tell you this

**Comment by danpowel** [comment]
i was downloading simbreif plns into mcdu

**Comment by danpowel** [comment]
how does one disable navigraph...arnt the already populated

**Comment by danpowel** [comment]
there is a navigraph file in community folder ...is that what your referring to?

**Comment by danpowel** [comment]
still there

**Comment by Benjozork** [comment]
Yes.

Try without that to see if it still happens.

**Comment by danpowel** [comment]
took it out of community folder but lost all navaids...going to try uninstalling navigraph and reinstalling

**Comment by danpowel** [comment]
did a new install of navigraph on "C" drive.....it can't find my msfs2020, which part of it is on C and community folder is on D....Soooo I reinstalled it in my Commuity folder and a prompt came up in the navigraph installation saying it recognizes that i have msfs2020 on 2 drives.  I loaded sim @ KDCA &  manually entered flt pln to KBOS.  It worked...no lockups and was able to bring up fltpln page in fms.  Wow such trouble for all of this and i think they should give us a better install.  Having said all this i am going to see if i can download a fltpln from simbreif...wish me luck

**Comment by danpowel** [comment]
simbreif worked fine now i'm gonna fly maybe tis might help others w/same issue & thx for help!

**Comment by Benjozork** [comment]
Good to hear! have a good day

**Comment by danpowel** [comment]
thanks again...fyi:  flew 4 different flight w/no issues, although putting "Navigrah" in community folder seems weird but it works.  Navigraph manager still doesn't have msfs2020 in its list of sims
