### ISSUE TITLE
Variables for status of  arm spoiler and for swicth HDG managed/set

### ISSUE THREAD

**Issue by JLD95** [flybywiresim/a32nx#4573]
**Aircraft Version**

```json
"built": "2021-04-24T19:05:06+00:00"
```

**Describe the bug**

Hi, I use X-Touch-Mini-FS2020 in order to adjust AP, spoilers, parking brake. With last dev, I noticed some function don't work anymore: before for status of  arm  spoiler, I used this var "SPOILERS_ARMED"  and for switch heading managed/set I used this var "HEADING_SLOT_INDEX_SET". Can  you tell me where I can find the new variables ?

**To Reproduce**

1.  Press arm spoiler but the var "SPOILERS_ARMED" is not true
2.  Set the var "HEADING_SLOT_INDEX_SET" but no effect on HDG mode
3.

**Expected behavior**

Can  you tell me where I can find the names of new variables ?

**Actual behavior**

see before

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by aguther** [comment]
FCU stuff:
https://docs.flybywiresim.com/start/autopilot-fbw/

For other variables:
https://github.com/flybywiresim/a32nx/blob/master/docs/a320-simvars.md
