### ISSUE TITLE
No hardware input in DEV version

### ISSUE THREAD

**Issue by AdamNZ** [flybywiresim/a32nx#4574]
**Aircraft Version**

```json
{
  "built": "2021-04-24T19:05:06+00:00",
  "ref": "master",
  "sha": "43a8c41776d5b381af620ecc47fcfdaab29bee3b",
  "actor": "aguther",
  "event_name": "manual"
}
```

**Describe the bug**

No hardware inputs at all from my X52Pro - with or without FSUIPC. A *totally* clean Community foldsr - with only yhe DEV mod installed.

**To Reproduce**

1. Cold and dark startup.
2. Fire up all electrics etc.
3. Fire up EFB and attempt to calibrate.

**Expected behavior**

All control inputs should work (as before).

**Actual behavior**

No VC animations nor external movement - though the throttle is actually working behind the scenes (sort of).

**References**

**Additional context**

Tries totally removing all traces of the FBW installer and in the Community folder. Did a clean install right from scratch a couple of times. Still no joy.

Was this working before/when did the issue start occurring?
Before the latest DEV build was fine.

Is this a problem in the vanilla unmodded game?
No.

Discord username (if different from GitHub):

**Comment by aguther** [comment]
Please check the following (headline Autopilot, FADEC, electrical system unwanted behavior):
https://docs.flybywiresim.com/start/reported-issues/

* Are flaps / spoilers working?
* What control assignments do you have?

**Comment by AdamNZ** [comment]
Yep (sorry) I forgot to mention - I'd already scoured that page.

The odd thing is that it did actually work (once). I could calibrate (and see the sliders move in the EFB) - and I even completed a CAT3 ILS autoland. Go figure.

I have no fancy assignments of any kind. Just the usual axis mappings (but NO spoiler/slider axis mapped at all).

**Comment by aguther** [comment]
Hmm, so it was once working an then it stopped working.

can you check if there is a SimConnect.cfg anywhere on your user Profile?

How does the SimConnect.cfg file look like in the sim folder (just search for it on your computer drive(s)…?

**Comment by AdamNZ** [comment]
Thanks for that link - I'll back up and delete my current version (in Users/Documents). Meanwhile, here are the contents:

[SimConnect]
Protocol=Ipv4
Address=127.0.0.1
Port=500

**Comment by aguther** [comment]
Yeah just go vanilla for the start by removing the file completely and if that works you can add it again and try to fix as it was mentioned in the Aerosoft forum.

**Comment by AdamNZ** [comment]
BINGO!!!!!!!!!!!!! Wow - the FBW community is so amazing!!! :)

I suspect that some nasty little add-on created that [malformed] file ... and that simply disabling all addons in Community will have no real effect, as the [bad] simconnect.cfg remains there in Documents.

For thew benefit of others, I'll keep my eye on things and see if I can nail the culprit. Maybe keep this issue open for a short while in case I spot it.

Many, many thanks!

**Comment by aguther** [comment]
Great!

I heard an old version of KinectAssistant installed that file. Lastest version should not do it anymore (it should not be needed anymore).

**Comment by AdamNZ** [comment]
Hmmm ... I've run that in the past ... but not for a fair while. I'll keep testing. All still looking good though!
BTW: The date on simconnect.cfg was 25/01/2021 (25th Jan) ... if that helps others.
