### ISSUE TITLE
EFB UI enhancement

### ISSUE THREAD

**Issue by darkfury334** [flybywiresim/a32nx#4575]
**Is your feature request related to a problem? Please describe.**
I get frustrated when I can not read the efb due to colour scheme.

**Describe the feature you'd like to see implemented**
updated UI with better colour scheme to make easier to read and better icons or tabs.

**References**
![efb](https://user-images.githubusercontent.com/78447787/115990471-53e64780-a5bb-11eb-9e68-4a20a46860fa.jpg)

**Additional context**

Discord username DarkFury#4936

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by sidnov** [comment]
You might wanna have a look at #4026 ;)

**Comment by darkfury334** [comment]
I just had a look at #4026 . it looks good and can see what work has been done. must have missed the pull request. maybe this can be put with the other pull request.

**Comment by Benjozork** [comment]
The color scheme meets WCAG standards.

Are you sure you don't mean the test size ?

**Comment by darkfury334** [comment]
![image](https://user-images.githubusercontent.com/78447787/116001886-cd4b5d80-a5ee-11eb-9b2a-f560d31afbb4.png)

text size and colours. I find using the efb hard as I have issues with certain colours being used together so i have to be zoomed in close to be able to use it. If i knew how to code to change the colours, i could change it to make it easier well for me anyways.

**Comment by darkfury334** [comment]
Would it possible to add a colour customisation option?

**Comment by antonyisoardi** [comment]
https://github.com/flybywiresim/a32nx/issues/4601 - could consider this as well at the same time.

Perhaps might be worthwhile considering some higher contrast option in settings.

@darkfury334 for me contrast is fine - do you think perhaps the font makes it hard to read? You can already adjust the size of the text on the bottom right there.

**Comment by darkfury334** [comment]
> #4601 - could consider this as well at the same time.
> 
> Perhaps might be worthwhile considering some higher contrast option in settings.
> 
> @darkfury334 for me contrast is fine - do you think perhaps the font makes it hard to read? You can already adjust the size of the text on the bottom right there.

Adjusting the size of text on OFP makes it a little better but you can't do that for the rest of EFB. I have issues with certain colours used together makes it hard for me to focus or read.

**Comment by antonyisoardi** [comment]
Got ya - do you think you'd find it easier to read if it were only theme change (say if it were inverted) - or would you still need some changes around font sizes etc?

**Comment by darkfury334** [comment]
A theme change (not inverted) would make it easier as the background makes the font slightly blurry and the contrast between all the colours does not help. the font is ok.

**Comment by antonyisoardi** [comment]
I'll look into this. this week. I'm a bit hesitant to do anything on v2 at the moment considering it's just about ready to be rolled out by the looks of things. Might be best to wait until next week after it's merged.
