### ISSUE TITLE
[BUG] Waypoint ETA on ND is displaying in local time not UTC.

### ISSUE THREAD

**Issue by Coralec** [flybywiresim/a32nx#458]
**Mod Version**

cef39ab (master)

**Describe the bug**

When the pfd displays the ETA to the next way-point on the flight-plan, it displays the time in the local time corresponding to the position of the aircraft instead of UTC. I checked with one of our irl A320 pilots, and he says that he believes that those ETA's should display in UTC. It doesn't make much sense for the ETA display local time when the chrono in the aircraft displays UTC.

**To Reproduce**

1. Start a flight with a flight-plan in the MCDU
2. Takeoff from your departure airport and engage the A/P and proceed with your flight normally
3. Note that the next way-point ETA in the top right of the right PFD display is indicated in the local time and not in utc (picture below for reference).

**Expected behavior**

The ETA should display in UTC not the aircraft's local time.

**Actual behavior**

The ETA displays in local time.

**References**

![image](https://user-images.githubusercontent.com/4960953/92333022-1050c480-f050-11ea-93a2-2a74f19571f6.png)

Note the ETA circled in red on the left, and the chrono displaying the correct UTC time on the right. 

**Additional context**

**Comment by UncleClapton** [comment]
I can take a look into this
