### ISSUE TITLE
Wrong ND TCAS Display Range

### ISSUE THREAD

**Issue by airfirefighter** [flybywiresim/a32nx#4581]
**Aircraft Version**

```json
{
  "built": "2021-04-24T19:05:06+00:00",
  "ref": "master",
  "sha": "43a8c41776d5b381af620ecc47fcfdaab29bee3b",
  "actor": "aguther",
  "event_name": "manual"
}
```

**Describe the bug**
if u select a range more than 20 nm on ND you cant see the diamonds of the tcas traffic. 

**To Reproduce**

1.leave the pilots ND in 20nm range 
2.change the copilot side in more than 20nm range ND 
3. u will see all the traffic from tcas all the diamonds etc in all the altitudes working in the side of the pilot 
4.if u find a traffic symbol and u change from 20nm to 40nm the symbol is dissappear 

**Expected behavior**
to see the tcas symbols in all the range of ND from 10nm to 180nm

**Actual behavior**
u can see the tcas symbol (diamond or circle at every altitude but only in selected range of 20nm on ND

**References**

as u can see tcas is working for me at all altitudes and for all traffic 37000ft i just keep the pilot side always at 20nm range on ND

![Microsoft Flight Simulator 25_4_2021 11_43_53](https://user-images.githubusercontent.com/71919620/115995648-c4558e80-a5e4-11eb-8b34-ed408d433580.png)
![Microsoft Flight Simulator 25_4_2021 09_34_28](https://user-images.githubusercontent.com/71919620/115995677-f36c0000-a5e4-11eb-8c8a-750331ccb540.png)

**Comment by sidnov** [comment]
Can you confirm if this observation was on an online network such as VATSIM? 

TCAS works with the default AI traffic, also with real life traffic enabled, but not with online networks' traffic. As far as the range is concerned, I have had a chance to look into the code a few weeks back, and as of now, it looks like a sim limitation.

**Comment by airfirefighter** [comment]
> Can you confirm if this observation was on an online network such as VATSIM?
> 
> TCAS works with the default AI traffic, also with real life traffic enabled, but not with online networks' traffic. As far as the range is concerned, I have had a chance to look into the code a few weeks back, and as of now, it looks like a sim limitation.

no it wasn't on an on line network it was the asobo on line traffic.

**Comment by 2hwk** [comment]
iirc the maximum TCAS detection range is ~30 nm. Not to be confused with ADS-B, which is in development along with the ND rewrite.  

In addition I have multiple sources saying that in the A320, the TCAS symbols are only shown when the range is below 40 nm, but I will ask around to confirm. 

https://www.aviationmatters.co/tcas-guide/
http://a320dp.com/A320_DP/warning-systems/sys-16.3.2.html
https://www.icao.int/APAC/Meetings/2011_ADS_B_SITF10/SP07b_Airbus%20-%20ADS-B%20IN.pdf
https://www.aviatorsbuzz.com/techtalks/a320s-traffic-alert-and-collision-avoidance-system-tcas/

**Comment by 2hwk** [comment]
Correction:
> TCAS intruders shall be displayed on ND Capt and F/O in all Rose modes and ARC mode:
> * **Full time option installed**: For all ranges except in ZOOM ranges, NDRange > 9NM,
> * **Full time option not installed**: For all ranges <=41 nm except ZOOM ranges: NDRANGE > 9nm
