### ISSUE TITLE
ELEC page has no arrows to BATs when being charged

### ISSUE THREAD

**Issue by ghost** [flybywiresim/a32nx#4590]
**Aircraft Version**
{
  "built": "2021-04-23T22:37:56+00:00",
  "ref": "experimental",
  "sha": "c43d0267084cae66e5cb3950c1c76e9b78bf43d0",
  "actor": "aguther",
  "event_name": "manual"
}

**Describe the bug**
The green lines and arrows pointing form the ELEC bus to the BATs when they're being charged are missing.

**To Reproduce**
Charge the BATs (see Amp Indictaion of each BAT on the ELEC page).

**Expected behavior**

**Actual behavior**

**References**
full batteries:
https://pilotspace.co.uk/guides/a320-systems-electrical/

batteries being charged (thumbnail of the video/no need to play):
https://www.youtube.com/watch?v=qxobIsySGFA

**Additional context**
N/A

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
N/A

Discord username (if different from GitHub):

**Comment by davidwalschots** [comment]
You'll have to be very specific on the state of the aircraft. Please provide screenshots of the ECAM and the overhead panel state. It might be that the battery isn't connected to the BAT BUS, and the discharge you see on the ECAM is discharge towards the hot bus.

**Comment by CptChaos0815** [comment]
I have more than 3A charging current to my bats and no arrow is visible. All systems normal, all lights on the elec panel off.

![grafik](https://user-images.githubusercontent.com/82841421/116009913-4e6d1980-a61c-11eb-8f69-7b3b0cdc3a39.png)

![Screenshot_2021-04-25 AMM - A318,A319,A320,A321 - DLH - Rev num 121 - 01-Feb-2021 - Figure 31-67-24-30500-00-AM (SHEET 1) -](https://user-images.githubusercontent.com/82841421/116009949-778daa00-a61c-11eb-89a4-44d0e33ce03f.png)

Item (3)
Battery 1 charge/discharge operation
Case 1
This link is displayed in green and represents a charging arrow toward the battery, when the BAT1 contactor is ON (6PB1 energized), **the battery charging current is over 1A** and the current value is correctly transmitted by the SDAC.
Case 2
The link is displayed in amber and represents a discharging arrow away from the battery, when the BAT1 contactor is ON, the discharging current is over 1A and the current value is correctly transmitted by the SDAC.
Case 3
The link is displayed in green and bears no arrow when the BAT1 contactor is ON, the current is in the range -1A / +1A, or the current value is not available from the SDAC.
Case 4
The link is not displayed when the BAT1 contactor is OFF (6PB1 not energized) or when the contactor status is not correctly transmitted by the SDAC.

**Comment by komp1821** [comment]
The arrows disappear when the charging current is less than 4A for more than 10 seconds on ground or more than 30 minutes when in the air or following an APU start.

**Comment by davidwalschots** [comment]
Those timings relate to how long the battery is connected to the BAT BUS @komp1821.

Arrows will appear when charge or discharge current from/to the BAT BUS is over 1A for 15 seconds or more. Most likely those 15 seconds haven't passed yet.

**Comment by komp1821** [comment]
![Screenshot 2021-04-25 233705](https://user-images.githubusercontent.com/71044068/116010450-4cf12080-a61f-11eb-9423-54a5b4962ffc.png)

Just saying...

**Comment by davidwalschots** [comment]
A @ghost won't respond.
