### ISSUE TITLE
SEL light on RMP comes on without a cause

### ISSUE THREAD

**Issue by ghost** [flybywiresim/a32nx#4591]
**Aircraft Version**
{
  "built": "2021-04-23T22:37:56+00:00",
  "ref": "experimental",
  "sha": "c43d0267084cae66e5cb3950c1c76e9b78bf43d0",
  "actor": "aguther",
  "event_name": "manual"
}

**Describe the bug**
The SEL lights of CPT and F/O RMP don't work properly when VHF3 is selected.

**To Reproduce**
Select VHF 3 on CPT or F/O RMP.

**Expected behavior**
The SEL light should only come on on the RMP that has selected another xceifer than its own and on the RMP whose xceiver is being accessed by another RMP. So if I select VHF2 on RMP1 the SEL light on RMP 1 and 2 will come on.

But when I select VHF3 on RMP1 the SEL light on the RMP1 shall come on only. Not the one of RMP2 which controls its own xceifer.

**Actual behavior**
The SEL light comes on on RMP1 and 2 when VHF3 is selected. 

**References**
N/A

**Additional context**
N/A

Was this working before/when did the issue start occurring?
UNKNOWN
Is this a problem in the vanilla unmodded game?
UNKNOWN

Discord username (if different from GitHub):

**Comment by juliansebline** [comment]
I will have to check with #7105 and fix it if needed

**Comment by juliansebline** [comment]
Fixed

**Comment by juliansebline** [comment]
Please have a look to this video. Are you sure of what you saying?

 https://www.youtube.com/watch?v=wvuWGTKRMGg
