### ISSUE TITLE
LEDs in pushbutton switches light up too slow

### ISSUE THREAD

**Issue by CptChaos0815** [flybywiresim/a32nx#4594]
**Aircraft Version**
{
  "built": "2021-04-23T22:37:56+00:00",
  "ref": "experimental",
  "sha": "c43d0267084cae66e5cb3950c1c76e9b78bf43d0",
  "actor": "aguther",
  "event_name": "manual"
}

**Describe the bug**
The lights in the pushbuttons are LED type in the NEO. In the FBW A320 they light up even slower than a traditional bulp.

**To Reproduce**
do the eng or apu fire test. or lock the cockpit door to extinguish the cockpit door open light. all these LED lights in the pushbuttons take to long for LED type lights to come on bright.

**Expected behavior**
Like LEDs. Ping! On! 

**Actual behavior**
Lights in buttons are slow and look broken.

**References**
https://youtu.be/ivCHanu8NrM?t=44

**Additional context**
N/A

Was this working before/when did the issue start occurring?
UNKNOWN

Is this a problem in the vanilla unmodded game?
UNKNOWN

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Caused by MSFS engine
