### ISSUE TITLE
Fire handles can't be stowed

### ISSUE THREAD

**Issue by ghost** [flybywiresim/a32nx#4596]
**Aircraft Version**

{
  "built": "2021-04-23T22:37:56+00:00",
  "ref": "experimental",
  "sha": "c43d0267084cae66e5cb3950c1c76e9b78bf43d0",
  "actor": "aguther",
  "event_name": "manual"
}

**Describe the bug**
Once a fire handle is pushed and released I can not stow it back by any means.

**To Reproduce**
Open the cover, push and relase the fire handle and try to reset it.

**Expected behavior**
The handle should be stowable by clicking on the released button.

**Actual behavior**
Once out it stays out.

**References**
N/A

**Additional context**
N/A

Was this working before/when did the issue start occurring?
UNKNOWN

Is this a problem in the vanilla unmodded game?
UNKOWN

Discord username (if different from GitHub):

**Comment by hotshotp** [comment]
IRL you would not be able to do anything once you pulled them out other than have engineers come in and fix it for you. maybe we could make it so it can be pushed back in, but then it would render the engine useless anyway

**Comment by tracernz** [comment]
We could do things like that on the maintenance page of the EFB.

**Comment by komp1821** [comment]
> 
> 
> IRL you would not be able to do anything once you pulled them out other than have engineers come in and fix it for you. maybe we could make it so it can be pushed back in, but then it would render the engine useless anyway

You should still be able to restow the handle and everything that happened should be undone. Obviously the engine won't come back to life on its own, but you can still restart it. No need to reset anything actually.

**Comment by AirbusA320Pro** [comment]
@komp1821 in the real aircraft the fire handle can be restowed, but none of the connected systems reset etc. That's an engineering/maintenance function. If the A32NX is aiming to be "real world" accurate, you should NOT be able to restart the engine after the fire handle is released.

**Comment by lukecologne** [comment]
> in the real aircraft the fire handle can be restowed, but none of the connected systems reset etc. That's an engineering/maintenance function. If the A32NX is aiming to be "real world" accurate, you should NOT be able to restart the engine after the fire handle is released.

Do you have a source for that? The user you were replying to is an A320 engineer.

**Comment by airfirefighter** [comment]
i dont know if this video can help.....at 6:16 https://www.youtube.com/watch?v=DjYoh5wDLy4&t=1s

**Comment by AirbusA320Pro** [comment]
@lukecologne I'm struggling to find a manual reference (although I have limited manuals tbf) but that's what we're taught during training. It's been the same training with 3 different airlines, so can only assume it's for the same reason I stated. 
@airfirefighter whilst I can't understand what is being said in the video, notice how he only presses the APU fire pb, and only opens the cover on the engine fire pb, but does NOT press it. I'm pretty confident that if he did, it would need maintenance action afterwards and was told not to press it.

**Comment by airfirefighter** [comment]
![image](https://user-images.githubusercontent.com/71919620/116646211-311fae80-a980-11eb-9b55-a3d44374a08e.png) 
All those system are reversible without maintenance if iam correct except IDG that is deactivate and no disconnect (that is also reverse without maintenance) if that pdf is correct u need maintenance.....

**Comment by komp1821** [comment]
You can always call maintenance to reset what you have done. But literally, the only thing we would do is push the button in (and probably swear at you while walking out the door). Unless there has been an actual fire event of course. But that's a totally different story. 
The fire handle is simply a shortcut, so you don't have to switch the related pushbuttons manually. The IDG does *not* physically disconnect with this button. It just opens the Power-Ready Relay, which de-energizes the IDG and as a consequence opens the Generator Line Contactor. It may or may not be an operator's procedure to disconnect the IDG additionally.

I can go even one step further: There's a routine maintenance check in AMM 26-21-00, performed every 18.000 FH, that lets you check exactly this behavior. In a nutshell:
- Release the fire handle, check that the fuel, hydraulic, bleed, pack valves close. Check that you cannot override them by pushing any of the push buttons. 
- Push the button in. Check that the valves return to their normal position and that you can operate them with the related push buttons.

**Comment by Illuminati270** [comment]
Guys, to date, this issue is still happening.

I confirm that the fire button should be able to be pushed back!

A very common thing to happen on recurrent trainings is to push them back after an emergency drill.

**Comment by milaandahiya** [comment]
Just accidentally experienced this myself. I believe the only case where the handle **cannot** be pushed back if the extinguisher bottles discharged in the event there was actually a fire (or sim-induced failure, we will assume the bottles were discharged). In that case, we would not allow for the engine to be restarted by leaving the the fuel, hydraulic, bleed, and pack valves closed (maybe this could be "fixed" through maintenance in the EFB).

Here's the expected behavior to my understanding, please correct me if I am wrong:

Return the fuel, hydraulic, bleed, and pack valves to normal position when the handle is pushed back. Allow the push buttons to control these functions again. To restart the engine, just change engine mode selector to IGN/START, and then flip the engine start switch to ON. If the start switch was already on, I'm presuming it would be required to reset the start switch to the OFF position first.

**Comment by juliansebline** [comment]
I'm having a look right now

**Comment by juliansebline** [comment]
Hello ! Fixed here https://github.com/flybywiresim/a32nx/pull/7088

I have noticed many bugs still exist. For example, the engine does not shutdown when the fire push button is released.
