### ISSUE TITLE
Time delay for continuous repetitive chime at fire test too short

### ISSUE THREAD

**Issue by ghost** [flybywiresim/a32nx#4598]
**Aircraft Version**
{
  "built": "2021-04-23T22:37:56+00:00",
  "ref": "experimental",
  "sha": "c43d0267084cae66e5cb3950c1c76e9b78bf43d0",
  "actor": "aguther",
  "event_name": "manual"
}

The fire sound comes on too quick when testing the system.

**To Reproduce**
Click any fire test switch and compare with the video below.

**Expected behavior**
Delay the chime.

**Actual behavior**
Chime sounds too early.

**References**
https://www.youtube.com/watch?v=uRS-gwCBUzE&t=20s

**Additional context**
N/A

Was this working before/when did the issue start occurring?
UNKNOWN

Is this a problem in the vanilla unmodded game?
UNKNOWN

Discord username (if different from GitHub):

**Comment by davidwalschots** [comment]
@hotshotp

**Comment by hotshotp** [comment]
> @hotshotp 

I haven't touched the delay, it's just the CRC sound that has logic somewhere in JS. I'm not the one who programmed it

**Comment by hotshotp** [comment]
i tested this recently and this does not seem to be an issue anymore
