### ISSUE TITLE
Engine Bleed does not come via HPV when in idle

### ISSUE THREAD

**Issue by ghost** [flybywiresim/a32nx#4600]
**Aircraft Version**
{
  "built": "2021-04-23T22:37:56+00:00",
  "ref": "experimental",
  "sha": "c43d0267084cae66e5cb3950c1c76e9b78bf43d0",
  "actor": "aguther",
  "event_name": "manual"
}

**Describe the bug**
When in idle the engines don't tap the bleed from the high pressure bleed valve when in idle.

**To Reproduce**
1. Throttles at idle with engines running.
2. Open ECAM Bleed Page
3. HPV is closed and IPV is open.

**Expected behavior**
When in idle the engines produce less bleed pressure and therefore need to tap the bleed from the high pressure bleed valve. When increasing thrust at a certain pint the HPV will be commanded closed and the intermediate pressure check valve (butterlfy type) will open.

**Actual behavior**
When in idle the engines don't tap the bleed from the high pressure bleed valve.

**References**
Test procedure and screenshots for reference:
![12](https://user-images.githubusercontent.com/82841421/116011077-554b5a80-a623-11eb-9f5c-ce6bfc16aa58.jpg)

Screenshot 1
![grafik](https://user-images.githubusercontent.com/82841421/116010936-55972600-a622-11eb-94b8-84aa3b732301.png)

Screenshot 2
![grafik](https://user-images.githubusercontent.com/82841421/116010958-719ac780-a622-11eb-811e-94f8fe1905d8.png)

Screenshot 3
![grafik](https://user-images.githubusercontent.com/82841421/116010975-8aa37880-a622-11eb-813b-c16804aea35a.png)

**Additional context**
N/A

Was this working before/when did the issue start occurring?
UNKNOWN

Is this a problem in the vanilla unmodded game?
UNKNOWN

Discord username (if different from GitHub):

Cpt. Chaos
#3721

**Comment by Maximilian-Reuter** [comment]
fixed in #5384
