### ISSUE TITLE
LOC and APP button doesn't work, development version 8cc7d5f

### ISSUE THREAD

**Issue by DaviSouzaR** [flybywiresim/a32nx#4608]
i try to use this button, but doesn't work more.

**Comment by Benjozork** [comment]
You didn't follow the provided template.

For future reference, we recommend using discord for support requests (if possible) unless instructed by a team member to use GitHub.

Can you show a video of this happening ?

You also need to be more precise in your reports. What does "doesn't work anymore" ? What did you expect to happen nf what happened instead ? This is the reason we provided the template.

**Comment by MisterChocker** [comment]
Please open a new issue by following this [bug report template](https://github.com/flybywiresim/a32nx/issues/new?assignees=&labels=Bug&template=bug_report.md)
