### ISSUE TITLE
[REQUEST] Fix broken radio frequencies

### ISSUE THREAD

**Issue by efortier-95** [flybywiresim/a32nx#461]
Some com frequencies ending in .XX5 actually end up being .XX4 in vPilot. I think this is an aircraft-specific issue. Notable example is 134.425, though the reproducability is ~50%

It seems like an easy fix if you can read the source code (I can't); is it possible to incorporate this change by v0.3?

**Comment by Benjozork** [comment]
Please respect the provided issue template.

**Comment by efortier-95** [comment]
#
