### ISSUE TITLE
transponder malfunctioning 

### ISSUE THREAD

**Issue by captioncrunch666** [flybywiresim/a32nx#4610]
**Aircraft Version** 6.0 stable

```json

```

**Describe the bug**

transponder appears inoperative or malfunctioning during ifr flight and can not enter code 

**To Reproduce**
 fly any ifr plan

1.fly any ifr plan 
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by markmiller30** [comment]
Have you tried pressing CLR twice?

**Comment by Benjozork** [comment]
Does not follow template

**Comment by captioncrunch666** [comment]
I reinstalled the stable version and it works fine now On Apr. 26, 2021 8:15 p.m., markmiller30 ***@***.***> wrote:
Have you tried pressing CLR twice?

**Comment by tracernz** [comment]
It must be an old stable version from before we made the transponder code handling realistic?
