### ISSUE TITLE
Throttle Calibration Apply and Apply and save buttons in flypad not active.

### ISSUE THREAD

**Issue by Dompep** [flybywiresim/a32nx#4614]
**Aircraft Version**
8cc7d5f
```json

```

**Describe the bug**
When I want calibrate my 2 Saitek throttles with the flypad process, I cann't apply and save the settings because the two buttons are not active

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Watsi01** [comment]
Please use the above template to describe your problem and the version you use,

**Comment by MisterChocker** [comment]
Please fill in the provided template and also attach pictures showing the issue.

**Comment by ExampleWasTaken** [comment]
I'm 99% sure you have overlap issue. If there is red text below the configuration card, you need to resolve the there mentioned errors before being able to apply the changes.

**Comment by Dompep** [comment]
> I'm 99% sure you have overlap issue. If there is red text below the configuration card, you need to resolve the there mentioned errors before being able to apply the changes.

**Comment by Dompep** [comment]
Yes, i have overlap red message. But I don't know how to  solve it.........

**Comment by Watsi01** [comment]
Try to reduce the deadzone entry. Most of the time, the deadzone entry is to high when overlapping occurs.

**Comment by Dompep** [comment]
I have understood how to configure calibration. Evrything is OK now.
Thanks!
