### ISSUE TITLE
ecam throttle stay stuck at 80% the whole time

### ISSUE THREAD

**Issue by frap99** [flybywiresim/a32nx#4615]
**Aircraft Version**

```json
dev 8cc7d5f
```

**Describe the bug**
 

even when i set up throttle it stay stuck at 80%+ clb the whole flight

**To Reproduce**

1.use the thrust on taxi and show 84% and stay like that
2.on taxi its stays stuck on 84% flex and on takeoff it says clb for the whole flight
3.

**Expected behavior**

i expected the ecam to show me correct throttle display but it dont

**Actual behavior**

stay stuck for the whole flight no matter what i do

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Watsi01** [comment]
I don't know exactly what you mean. But if you say, that the ECAM says CLB the whole flight? This is correct and how it should be (also in real life). It's kind of an Airbus thing. Once the lever is on CLB position, it stays there until touchdown/flare. Otherwise the autothrust won't work,

**Comment by frap99** [comment]
its stuck on 84% the whole flight.. gate, taxi, to, clb, crz, des, appr, taxi again.. it just never adjust depending on how much power i input

**Comment by Watsi01** [comment]
Did you calibrate you throttle controller via the EFB?

**Comment by frap99** [comment]
yea but im using a controller. does it has to do with something?

**Comment by Watsi01** [comment]
That's what I meant. I mean, did you do this:
https://www.youtube.com/watch?v=9oqFfAMXCcc

**Comment by frap99** [comment]
yes i did

**Comment by MisterChocker** [comment]
@frap99 do you mean this value? 
![image](https://user-images.githubusercontent.com/1857322/116251867-58536180-a76f-11eb-8ac2-ec5ac78eb066.png)

**Comment by frap99** [comment]
exactly, it stay stuck on whatever number its going to show, usually its 80% or so

**Comment by Benjozork** [comment]
No references to IRL behavior given

**Comment by MisterChocker** [comment]
This displays the engine thrust rating mode and thrust rating value. (nothing todo with thr lvr position).

**Comment by aguther** [comment]
Example here:
https://youtu.be/cJAnpefmwRw
