### ISSUE TITLE
AOC free text warning doesn't respect display dimensions and has invalid characters

### ISSUE THREAD

**Issue by komp1821** [flybywiresim/a32nx#4616]
**Aircraft Version**

```json
{
  "built": "2021-04-25T22:16:34+00:00",
  "ref": "master",
  "sha": "8cc7d5fd1cd3b962c03ae3276f47e386b902985c",
  "actor": "davidwalschots",
  "event_name": "manual"
}

```

**Describe the bug**

The warning text when changing the AOC free text option continues invisibly beyond the right border of the MCDU display and shows rectangles in places with supposedly invalid characters.

**To Reproduce**

1. MCDU MENU - (5R) OPTIONS - (1L) AOC - (1R) FREE TEXT ENABLE/DISABLE
2. See that the warning does not respect the display dimensions and has invalid characters
3. Feel the urge to file a github report

**Expected behavior**

Normal text without rectangles that respects the boundaries of the MCDU display

**Actual behavior**

Refer to screenshot.

**References**

![Screenshot 2021-04-27 150718](https://user-images.githubusercontent.com/71044068/116246549-62269600-a76a-11eb-9a31-193f31d9e8c7.png)

**Additional context**

Was this working before/when did the issue start occurring?
Has been around for a while. At least a month. I asked in Discord if this is known but didn't get a reply.

Is this a problem in the vanilla unmodded game?
It's an FBW feature.

Discord username (if different from GitHub):
komp#1821

**Comment by ExampleWasTaken** [comment]
I'm taking a look at it right now.
