### ISSUE TITLE
a320flybywire swing around at gate

### ISSUE THREAD

**Issue by Fontbase** [flybywiresim/a32nx#4619]
**Aircraft Version**

```json stable and developed version can only find layout.json and manifesto.json

```

**Describe the bug**

stand at gate (by the way there are no gates at my sim anymore after last update) pushing ready to fly button aircraft swing around with engines running moving forward a bit after a few seconds engines stops. cockpit are cold&dark

**To Reproduce**

1.chose aircraft
2.place at any gate
3.pushing ready to fly buttton

**Expected behavior**

aircraft should stay at gate cold&dark no engines running

**Actual behavior**

aircraft swing around with engines running

**References**

https://user-images.githubusercontent.com/83249445/116269658-b0459480-a77e-11eb-99dc-20d474634a83.mp4

**Additional context**

cant find info.json file in fs2020! in devmode tools packages info says that asobo-jetway package unmounted haserror! Is this apart of the issue?
Was this working before/when did the issue start occurring?
after the last big update with benelux countries this issue started
Is this a problem in the vanilla unmodded game?
??

Discord username (if different from GitHub):
Basefont

**Comment by Benjozork** [comment]
That doesn't have to do with the A32NX and looks like a simulator bug
