### ISSUE TITLE
During start of Engine 1, Engine 2 consumes negative fuel

### ISSUE THREAD

**Issue by uzytkownik** [flybywiresim/a32nx#4621]
**Aircraft Version**
Development 8cc7d5f

**Describe the bug**
When starting engine, Engine 1 does not consume any fuel and Engine 2 has negative fuel flow

**To Reproduce**
1. Start APU, APU bleed etc.
2. Turn on IGN mode
3. Switch Engine 1 master switch

**Expected behavior**
Engine 1 starts consuming fuel

**Actual behavior**
Engine 2 consumes negative fuel (start producing fuel?)

**Additional context**
Was this working before/when did the issue start occurring?

It worked in version before  c43d026

Is this a problem in the vanilla unmodded game?

Yes

**Comment by paul92ilm** [comment]
I tried to reproduce it
The Fuel Flow (FF on upper ECAM) stay to 0 for both engine until both engines are available
![image](https://user-images.githubusercontent.com/9373163/116313920-b5223c80-a7ae-11eb-983a-3318fba6d92e.png)

But The Fuel Used (F. Used on lower ECAM) seems to go to a negative value during engine start
![image](https://user-images.githubusercontent.com/9373163/116313568-3927f480-a7ae-11eb-912c-587e0f846891.png)

After few analysis, it looks like Fuel Used decrease on the engine off when the other one is running
 ![image](https://user-images.githubusercontent.com/9373163/116314519-7c369780-a7af-11eb-828f-3b598fab4f93.png)

**Comment by ExampleWasTaken** [comment]
As [this](https://github.com/flybywiresim/a32nx/tree/master/docs#engines) document states the engine model does not yet exist for startup. The values will fix themselves as soon as the engine is running.

**Comment by kutak11** [comment]
I have noticed also there is increase of "fuel on board" after start up by around 100kg ...

**Comment by ExampleWasTaken** [comment]
@kutak11 see [this](https://github.com/flybywiresim/a32nx/issues/4621#issuecomment-828024645)

**Comment by Taz5150** [comment]
Please test/ check with https://github.com/flybywiresim/a32nx/pull/5081
