### ISSUE TITLE
Support the AUTOPILOT_ON event

### ISSUE THREAD

**Issue by gizmo71** [flybywiresim/a32nx#4622]
**Is your feature request related to a problem? Please describe.**

The A32NX WebAssembly module captures and swallows the `AUTOPILOT_ON` event, and does so using the highest maskable priority it can lay its hands on (which depends on whether anything else gets there first). See #4609. This makes it impossible to use `AUTOPILOT_ON` from in-game bindings with the aircraft.

**Describe the feature you'd like to see implemented**

Instead of silently swallowing the event, please activate AP1 if it is not already active, by checking `A32NX_AUTOPILOT_1_ACTIVE` and sending `A32NX.FCU_AP_1_PUSH` (or calling equivalent code).
Optionally, call the AP2 version if AP1 is already active, thus effectively swapping between them during normal flight, or engaging the second AP if APPR mode is active.

**References**

**Additional context**

Discord username (if different from GitHub): `Gizmo#3618`

**Comment by aguther** [comment]
You’re right, at the moment this event is not working and I agree it should. Will look into it the next week.
