### ISSUE TITLE
AI Copilot not able to taxi

### ISSUE THREAD

**Issue by Danbaz100** [flybywiresim/a32nx#4623]
**Aircraft Version**
Development 8cc7d5f

**Describe the bug**
AI Copilot seems to not have thrust control as it is unable to start to taxi after pushback

**To Reproduce**
1. Start a flight from A to B, I did EHRD, ramp 2C to LFMN
2. Handover control to AI Copilot directly, so he will do everything
3. When pushed back and the tug has gone he should taxi away, but he can't. 

**Expected behavior**
When pushed back and the tug has gone he should taxi away, but he can't.

**Actual behavior**
The plane Just sits at the ramp, ready to taxi, but does not move

**References**
Will think about this for a next issue

**Additional context**
None

Was this working before/when did the issue start occurring?
This did work until a few days ago

Is this a problem in the vanilla unmodded game?
Yes. Just have liveries installed, nothing else.

Discord username (if different from GitHub): Danbaz

**Comment by Benjozork** [comment]
AI copilot is not supported as we have no way of controlling Its behaviour

**Comment by Danbaz100** [comment]
> AI copilot is not supported as we have no way of controlling Its behaviour

Thanks for letting me know.

I was let to think otherwise as it is still working on the stable version and it works different and better for the FBW version than for the default Asobo version. 

So either you have some control after all or Asobo has kindly improved the AI Copilot just for FBW. Pls could you check once more to make sure?

Kind regards,

Daniel

**Comment by Benjozork** [comment]
We have not changed anything related to the AI copilot because there simply is no ability for us to do so.

If it worked better in some version, that's purely a coincidence

**Comment by Benjozork** [comment]
If Asobo was to document it and allow third party developers to change its behavior, maybe it would be possible.
