### ISSUE TITLE
Using AI assist to control, aircraft thrust drops on runway departure

### ISSUE THREAD

**Issue by wpritch** [flybywiresim/a32nx#4624]
**Aircraft Version**

```json

```

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment]
You ignored the provided template.

Also, AI copilot is not supported as we have no way of controlling Its behaviour

**Comment by wpritch** [comment]
The stable release works fine.

Im sorry for no template, will try to use this in the future, just moments before signed up/

 

 

 

 

 

William F Pritchard

***@***.***

 

 





On Apr 27, 2021, at 4:16 PM, Benjamin Dupont ***@***.***> wrote:

 

 

You ignored the provided template.

Also, AI copilot is not supported as we have no way of controlling Its behaviour

**Comment by Benjozork** [comment]
While we understand this used to work before the introduction of the custom autopilot, we have no control over the AI copilot and cannot perform any fix. It only works with the default autopilot.

I'm sorry for the inconveniences caused, but this is a limitation of MSFS.

**Comment by wpritch** [comment]
Thanks for all your efforts

Sent from my iPad

William F Pritchard
***@***.***
