### ISSUE TITLE
(MCDU) All PERF pages are still accessible at a particular situation during approach

### ISSUE THREAD

**Issue by sidnov** [flybywiresim/a32nx#4635]
**Aircraft Version**

```json
{
  "built": "2021-04-28T03:09:12+00:00",
  "ref": "master",
  "sha": "ac38d5908a21967d040bacfe97b31d76f3ec202d",
  "actor": "Benjozork",
  "event_name": "manual"
}

```

**Describe the bug**

Looks like something that was fixed in https://github.com/flybywiresim/a32nx/pull/2940

There is still a way to access all the previous MCDU PERF pages such as climb, takeoff, etc. When on descent, scroll to the APPR page, fill the details such as TRANS ALT, QNH, TEMP, etc. and continue descent to an extent where you cross the DECEL point, and/or are below 9500ft (approx., as per my test airport VOML), basically **until the Approach phase gets automatically engaged on the MCDU,** without any intervention such as clicking the confirm activate APPR button, etc.

Once the MCDU approach phase is engaged, try using the "PREV PHASE" option (which is still visible , while it should have disappeared right after APPR is engaged [possible code hint] ) to scroll back through the earlier phases.

https://cdn.discordapp.com/attachments/754130199804772372/836987727135637504/Desktop_2021.04.28_-_20.59.33.03.mp4

**To Reproduce**

1. Descend normally, with APPR page opened on the MCDU, and all the details filled up
2. Do not engage MCDU Approach Phase manually on DES page, fly through the decel point, and continue on the approach with the APPR page open
3. Click the PREV PHASE option and observe older PERF pages showing up

**Expected behavior**

When the MCDU approach phase is engaged automatically while the MCDU displays the APPR page, an update code needs to run to hide the "PREV PHASE" option, or simply put, update the status of the page.

**Actual behavior**

Even though the Approach phase was engaged automatically, the PREV PHASE option still remained on display, allowing access to all the previous phases

**References**

**Additional context**

Was this working before/when did the issue start occurring?
This is a very rare situation, may have existed all this time, but went unnoticed

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub): sidnov#8337

**Comment by tracernz** [comment]
We should probably request a redraw of whichever page is active each time the flight phase changes, as many of them change with at least one of the flight phase transitions.

**Comment by MisterChocker** [comment]
> We should probably request a redraw of whichever page is active each time the flight phase changes, as many of them change with at least one of the flight phase transitions.

We already do that, but I kind of like your idea, just say, reload the page and than we have central handler that does that.

There is only a small thing I did not thought through when I wrote that code. Should be an easy fix.
