### ISSUE TITLE
[BUG] Chronometer doesn't scale time properly

### ISSUE THREAD

**Issue by Wikipediano** [flybywiresim/a32nx#464]
**Mod Version**

master

**Describe the bug**

The chronometer that has been added always runs at 1x speed (real time), even when the simulation speed is set to something higher like 2x or 4x

**To Reproduce**

1. Start the chronometer
2. Change the simulation rate
3. Observe chronometer timing relative to clock timing

**Expected behavior**

The chronometer should speed up when the simulation speed is increased.

**Actual behavior**

The chronometer always records elapsed time at 1x speed (real time).

**References**

**Additional context**

**Comment by Coralec** [comment]
I don't think Asobo is really supporting changes to simulation rate in MSFS so I don't think this is a bug.

**Comment by UncleClapton** [comment]
The entire clock is based on real world time so there really isn't much we can do about it. This is really more a limitation of how the whole thing works.
