### ISSUE TITLE
DEV 630eaed : AP bugs

### ISSUE THREAD

**Issue by lionhell** [flybywiresim/a32nx#4642]
**Aircraft Version**

```json

```

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

1/ On T/O ►
. V1 bug is absent.
. Autothrust does not work and one must reduce speed by exeperience, not by PFD indicatons ! If no reduction by the feeling overspeed and crash guaranteed !

2/ Cruise ►
. Level or altitude change works in strange manner. Sometime managed alt chg does not work, acft do not chg its altitude and one must select manual chg to force the descent.

3/ On APPR ►
. A320 flies dct rwy, one must set DIR to appr wpt.

RMK ►
All these bugs are new and popped up since the last 3 or 4 dev updates (when hdh-vs/trk-fpa selection was not implemented these bugs didnt exist).

**Comment by lukecologne** [comment]
Does not follow template.

**Comment by aguther** [comment]
Please be specific in regards what you really mean.
- Did you follow correct procedures?
- Did you enter all needed information into the FMGC?
- Which FMA where you in and which inputs did you do? Which modes did you expect then?

**Comment by Benjozork** [comment]
> All these bugs are new and popped up since the last 3 or 4 dev updates (when hdh-vs/trk-fpa selection was not implemented these bugs didnt exist).

well TRK/FPA has been here for months

**Comment by lionhell** [comment]
Hello,

I’m not a Professional pilot but I’m pretty sure I followed the procedure as requested.
I tried several times in different ways but no success…

Lionel


De : Andreas Guther
Envoyé le :jeudi 29 avril 2021 17:32
À : flybywiresim/a32nx
Cc : lionhell; Author
Objet :Re: [flybywiresim/a32nx] DEV 630eaed : AP bugs (#4642)

Please be specific in regards what you really mean.
• Did you follow correct procedures?
• Did you enter all needed information into the FMGC?
• Which FMA where you in and which inputs did you do? Which modes did you expect then?

**Comment by aguther** [comment]
Sorry that way we cannot support. What you're saying is like: "my computer doesn't work".

**Comment by lionhell** [comment]
Sorry I tried to follow the procedure but it is not clear to me… there is a line « do not erase template… » I then wrote my text behind.

Apologize ! But for the time dev version seems unserviceable on T/O, no V1 bug, auto-thrust CL not working (no warning on PFD and overspeed).

Lionel


De : Andreas Guther
Envoyé le :jeudi 29 avril 2021 22:20
À : flybywiresim/a32nx
Cc : lionhell; Author
Objet :Re: [flybywiresim/a32nx] DEV 630eaed : AP bugs (#4642)

Sorry that way we cannot support. What you're saying is like: "my computer doesn't work".

**Comment by aguther** [comment]
> Sorry I tried to follow the procedure but it is not clear to me… there is a line « do not erase template… » I then wrote my text behind. Apologize ! But for the time dev version seems unserviceable on T/O, no V1 bug, auto-thrust CL not working (no warning on PFD and overspeed). Lionel De : Andreas Guther Envoyé le :jeudi 29 avril 2021 22:20 À : flybywiresim/a32nx Cc : lionhell; Author Objet :Re: [flybywiresim/a32nx] DEV [630eaed](https://github.com/flybywiresim/a32nx/commit/630eaed2bb76a30b09301ba289cc99f23d7d1f9f) : AP bugs (#4642) Sorry that way we cannot support. What you're saying is like: "my computer doesn't work". — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

This is just not true:
https://youtu.be/sT6pMThX1bc

I’m now pretty sure it’s a throttle calibration and usage issue but to me it seems you’re not really interested into getting a solution than telling us that it’s not working.

That’s the end of my invest of time here.
