### ISSUE TITLE
!!not related to aircraft!!

### ISSUE THREAD

**Issue by frap99** [flybywiresim/a32nx#4644]
**Aircraft Version**

```json

```

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by frap99** [comment]
![Capture d’écran (90)](https://user-images.githubusercontent.com/83285939/116557977-f7da3680-a8cc-11eb-9f50-9a828c81f975.png)

**Comment by frap99** [comment]
why does the installer does this?

**Comment by markmiller30** [comment]
You should go to the Discord and the #support channel, you can get help there. This error is caused by the installing looking for a specific folder at the directory listed in that first line. You need to create the folder it is looking for at the exact path listed.

**Comment by frap99** [comment]
thank you mark but i figured it out. sorry for wasting your time mate.
