### ISSUE TITLE
Problem with aligning with flightpath after turn

### ISSUE THREAD

**Issue by ZerdNerd** [flybywiresim/a32nx#4645]
**Aircraft Version**
```json
"built": "2021-04-29T12:09:53+00:00",
  "ref": "master",
  "sha": "d0698c45b28b79db86b19fbed4af533b25f2c3ab",
  "actor": "lukecologne",
  "event_name": "manual"
```

**Describe the bug**
With new AP rolling out in Dev, I see that the plane seems to have problems after turning at waypoints. I know that flying exactly as the flightplan says is not possible and plane has to turn a bit earlier, but... previously, the plane had no problem with aligning with the path after the turn was started; now, it seems to get the longest route to "capture" the path between the points.

**To Reproduce**
1. Load the plane in Munich, runway 26R (exactly as I am flying at the moment)
2. Select SID ROTA3N and fill all necessary things
3. Takeoff and engage AP.

**Expected behavior**
Plane turning before the waypoint and aligning with the flightpath between previous and next waypoint as soon as possible after turning.

**Actual behavior**
Plane turns before the waypoint, but flies the longest possible route to "capture" the flightpath between previous and next waypoint.

**References**
This is how it looks like on the map via SimToolkitPro. Example: at LAKOL, the actual flightpath should be much closer to the point instead of going like... it's going.
![ImageOfMap](https://i.imgur.com/Is1N0XH.png)

Was this working before/when did the issue start occurring?
It started occuring most probably after new AP was added to Dev - previous flights were perfect in these terms.

Is this a problem in the vanilla unmodded game?
No.

**Comment by 2hwk** [comment]
Fixed by #4953 closing ☑️
