### ISSUE TITLE
Automatic deselction of Autothrottle and APP at FCP

### ISSUE THREAD

**Issue by lonewulf47** [flybywiresim/a32nx#4652]
**Aircraft Version**

```json
v0.6.0
```

**Describe the bug**

After touchdown Autothrottle and APP mode remain active on FCP

**To Reproduce**

1.Check FCP after touchdown
2.
3.

**Expected behavior**

Autothrottle and APP should automatically be deactivated ater toochdown

**Actual behavior**

After touchdown Autothrottle and APP mode remain active on FCP

**References**

--

**Additional context**

--
Was this working before/when did the issue start occurring?
no
Is this a problem in the vanilla unmodded game?
yes

Discord username (if different from GitHub):

**Comment by aguther** [comment]
FYI:
The behavior will be much more realistic with the upcoming version that contains custom AP and ATHR system.

Beside that, it's just not true that it should happen as you described. The ATHR should automatically disengage when putting throttles to IDLE. The APP remains engaged until LAND mode disengages (LAND mode contains LOC, G/S, LAND, FLARE, ROLL OUT).

Maybe you can elaborate a bit more what you mean.

I also expect that this will not be solved for current stable version, bc the new major version coming will solve it anyway.

**Comment by aguther** [comment]
Does it look and work differently for you as in my video?

**Comment by aguther** [comment]
Closed to due inactivity. Feel free to reopen to provide more info.
