### ISSUE TITLE
Typing into the FlyPad adjusts airplane according to keybindings

### ISSUE THREAD

**Issue by eatmorepies-dev** [flybywiresim/a32nx#4667]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-04-15T22:57:32+00:00",
  "ref": "v0.6.0",
  "sha": "981b2e4b0e89998d21a70fe26de54a2f10066f6e",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

Typing in a search box in the FlyPad (for example, Company->Username), adjusts the airplane according to the plane's keybindings as defined in the game settings (text input is still captured and placed in the textbox)

### Expected behavior

I expect the keybindings to not be in effect when I'm typing in a search box, so I can type without adjusting my plane

### Steps to reproduce

1. Turn on the FlyPad
2. Access a textbox (ex: Company->Username)
3. Type in the textbox

### Discord Username (optional)

eatmorepies-dev

**Comment by Valastiri** [comment]
As a solution you can pop out the EFB by using `right ALT + left click` so as not to trigger keybinds when interacting with elements in the aircraft. 

See this response as another reference relating to interaction with sim limitations -> https://github.com/flybywiresim/a32nx/issues/3445#issuecomment-785388104

**Comment by Benjozork** [comment]
MSFS issue
