### ISSUE TITLE
Overwriting an altitude constraint in F-Plan

### ISSUE THREAD

**Issue by GatwickFlyer** [flybywiresim/a32nx#4671]
I took my first flight in the A320NX this morning. On reaching the decent phase I started looking through the remaining waypoints entered in the FPlan to ensure the entered attitude constraints matched the Arrival and Approach documentation. One waypoint had a constraint of FL350 which was incongruous as it followed one with a constraint of 5000 feet. I tried to amend the offending constraint but nothing I did seemed to work. I tried clearing the constraint, I tried overwriting the constraint using the correct attitude typed into the scratchpad but that didn't work. I tried inserting the attitude in various formats  (FL050, 5000 etc) proceeded by a / but no joy.

I would be grateful if someone could advise me on the correct procedure for amending waypoint data listed in the FPlan. Thanks and apologies if this has already been asked.

**Comment by kiwi2021** [comment]
This is due to the default fpm that we are using at the moment. This will be resolved in our custom fpm. For future issues use the issue form provided, or speak to us on Discord.
