### ISSUE TITLE
MASTER WARN and MASTER CAUTION buttons do not work

### ISSUE THREAD

**Issue by mcaparula** [flybywiresim/a32nx#4675]
In Stable 0.6, pressing MATER WARN and MATER CAUTION buttons do not shut off warning sounds.  I put too much thrust on exiting runway after landing and warnings came up that I was not configured for takeoff, but I could not turn off the warning sounds.

**Comment by kiwi2021** [comment]
You need to press clr on the ECAM Control panel. Follow the forms provided in future.
