### ISSUE TITLE
gel du cockpit

### ISSUE THREAD

**Issue by iron944** [flybywiresim/a32nx#4676]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-04-15T22:57:32+00:00",
  "ref": "v0.6.0",
  "sha": "981b2e4b0e89998d21a70fe26de54a2f10066f6e",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

plusieurs fois par vol , tout les boutons du cockpit ce gel pendant un temp variable , je n'ai pas d'autre mods d'installé , a part navigraf et navigraf simlink

### Expected behavior

que tout marche tout le temp

### Steps to reproduce

1.
2.
3.
...
a n'importe quel moment du vol , en altitude de croisiere

**Comment by Benjozork** [comment]
Bonjour, ceci est un bug de MSFS sur lequel nous n'avons aucun contrôle. La seule solution est d'attendre et d'essayer de séléctionner les caméras extérieures puis de retourner dans le cockpit quelques fois.
