### ISSUE TITLE
Egg timer in vr 

### ISSUE THREAD

**Issue by bambam1919** [flybywiresim/a32nx#4681]
Egg timer causing bad stutter and fps since latest update and fbw mod updates using development version 

< Happens when loading flight at gates and is that bad you can not even turn on systems i.e. battery etc>

## Expected functionality
< Fbw mod always been fine and smooth until recent updates all other aircraft do not produce this bad performance >

## Steps to reproduce
< load at any airport gate in cold and dark in vr oculus rift s and egg timer should just keep going and going rendering the plane unusable >

## Additional information
< Intel i9 9900k
32gm ram 3000mhz
1tb adata m.2 ssd
Rtx 2080s 
Oculus rift s

all drivers up to date>

**Comment by Benjozork** [comment]
I have no clue what an "Egg timer" is

**Comment by kevinkiloechovictor** [comment]
> I have no clue what an "Egg timer" is

So I did some research and turns out it's an hourglass icon on a black screen page that usually appears when it's loading. In this case, it looks like the hourglass keeps popping up, freezing their game for a bit every now and then.

**Comment by Awemeter** [comment]
The egg timmer is a steam vr thing. It happens when steam vr thinks the game is frozen and it will spin the glass until it un-freezes or crashes.

**Comment by bambam1919** [comment]
Im not using steam vr though just oculus runtime

**Comment by bambam1919** [comment]
caused by multiplayer and custom liveries
