### ISSUE TITLE
F-PLAN deleted as MDCU change destination to origin

### ISSUE THREAD

**Issue by uzytkownik** [flybywiresim/a32nx#4682]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-01T17:57:16+00:00",
  "ref": "master",
  "sha": "6e71264d7618dc1d98193a567e4036583d0b865b",
  "actor": "MisterChoker",
  "event_name": "manual"
}
```

### Describe the bug

When approaching KSFO from SERFR4 just before EDDYY MDCU deleted plan and set KLAX as destination.

### Expected behavior

MDCU sets EDDYY as next waypoint

### Steps to reproduce

Unknown. It happened once so far.

**Comment by solarisfire** [comment]
This happened to me earlier today. I was on the ALAXI1F transitioning to the ILS15Y at LIRA (ROME CIAMPINO
) and the whole flight plan just got wiped...

**Comment by AlphaMA1** [comment]
I've had this on multiple occasions.
Every time I experienced it, it was on the second flight after having done a "turn around" on the ground, i.e. I have flown and completed a flight, parked at the gate, shut down engines, and the reporgrammed the MCDU with a new Origin/Destination combo and requested the SimBrief FPLN and data.

I had some turn around flights which did not suffer any problems.

**Comment by AlphaMA1** [comment]
This evening experienced the same on the one and only flight I did.
EGLL to EDDF imported via SimBrief.
No arrival procedure set in the MCDU until advised by tower. Eventually advised to UNOKO1D for ILS Y RWY07L direct via DF454. At the point I programmed the MCDU for the approach, I was already past the first nav point of the STAR, which was IBVIL. I was approaching RAMOB, but the autopilot decided to turn back on itself and fly to back to IBVIL. I proceeded to the DIR screen to select DIR to RAMOB to continue on my approach from the point where I was. MCDU then set RAMOB as next waypoint and deleted the entire flight plan, and reset the INIT screen to be EGLL/EGLL and giving me the SImBrief Init button option.

Had to re-import the flight plan from SimBrief and set the arrival procedure all again and DIR to the next waypoint again, which time this time worked fine.

**Comment by Bryce108** [comment]
I've had this happen to me twice now when I'm flying on vatsim and they give me a direct too, it cancels my whole flight plan. I was heading into KATL tonight, got a go direct GAASS on my arrival, did so, then boom whole flight plan gone.

**Comment by AlphaMA1** [comment]
I am on the experimental version ff7f81f.
What seems to happen is that when pressing Direct To the MCDU temporarily deletes all waypoints in the FPLN other than origin and destination, and then after about 2-3 seconds re-instates them.
When pressing Direct To it may at first appear that the MCDU did not react. So as a user I am inclined to press Direct To again and when I do to before it re-instated the waypoints then they are gone for good.

The exception to that rule is that I did have flights where flying with auto pilot on cruising altitude without manually intervening with the AP it did on two occasions lose the way points entirely.

**Comment by DecMoonFR** [comment]
Same problem here. Flight on IVAO. Flight from LHBT to ESSA. Long direct given by ATC from LUBEN to PENOR, and F-PLAN erased. It was a long direct si I can construct again F-PLAN.

It's more complicated on RNAV. On EFHK, STAR DIVAM 3W for RNP33 arrival, AP go direct alone to HK900 at 10nm from HK947, I made direct to SOPOS for trying to continue normal procedure, and all F-PLAN gone, including RNP33
