### ISSUE TITLE
Flaps and Gear don't go down during dual engine loss with APU on

### ISSUE THREAD

**Issue by Villason** [flybywiresim/a32nx#4684]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-04-15T22:57:32+00:00",
  "ref": "v0.6.0",
  "sha": "981b2e4b0e89998d21a70fe26de54a2f10066f6e",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

During a dual engine loss, after switching the APU, nor flaps nor gear work.

### Expected behavior

Flaps and Gear should work during dual engine loss with APU on.

### Steps to reproduce

- Configure a dual engine loss failure.
- Switch on APU.
- Enable APU bleed.
- Modify flap conf or lower the gear. It won't work.

**Comment by komp1821** [comment]
That's correct behavior. The APU or Bleed system has nothing to do with hydraulics.

If you turn off both engines, you lose green and yellow hydraulic system. Landing gear is connected to the green system, flaps are green and yellow (and slats blue additionally, but doesn't matter in this situation).
