### ISSUE TITLE
EFOB , FULEPRED values mismatch

### ISSUE THREAD

**Issue by Parshva8888** [flybywiresim/a32nx#4688]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-01T22:21:52+00:00",
  "ref": "master",
  "sha": "b63c33db9b402dd4188cdf341e224eeaa71d6a57",
  "actor": "MisterChocker",
  "event_name": "manual"
}
```

### Describe the bug

![Screenshot (294)](https://user-images.githubusercontent.com/83544814/116817159-b2df2a00-ab82-11eb-8ff9-7cf196311054.png)
![Screenshot (295)](https://user-images.githubusercontent.com/83544814/116817161-b4a8ed80-ab82-11eb-8d2c-c224333157ed.png)
![Screenshot (296)](https://user-images.githubusercontent.com/83544814/116817164-b5da1a80-ab82-11eb-94d1-53c63c827c52.png)

EFOB and FUELPRED  page mismatch 

### Expected behavior

Same values on both pages 

### Steps to reproduce

while performing a couple of flights 

### Discord Username (optional)

Parshva8888#1339

**Comment by erso44** [comment]
I will investigate this issue.

**Comment by erso44** [comment]
I do not see any problem. Fuel value is on both displays the same.
![Screenshot 2021-06-13 214718](https://user-images.githubusercontent.com/39134287/121820088-1c2d7f00-cc91-11eb-9c33-90dc0309e741.JPG)

**Comment by erso44** [comment]
I do not understand the issue of the issue creator and Just to be clear how the systems are working on the FUELPRED side:
The FOB value on the EWSD (Engine warning and system display) is the current loaded fuel.
The FOB on the MCDU on Page FUELRPED is how much fuel is really needed for the whole flight.
The first line on FUELPRED is how much fuel will be left when airriving at destination X.
The second line is the same just for alternate destination Y.

In your picture I can see that you have curently 8660 KG of fuel.
When you arrive at VIDP you will have 800 KG fuel.
At OPLA the same amount of fuel.
For your flight you need 8000 KG of fuel.

What is the issue ?

**Comment by erso44** [comment]
I need to correct this ticket.
The issue is that destination EFOB on F-PLN is different to destination EFOB on FUELPRED.
Also the documentation from Thales states it must be the same value.

Reference:
https://www.smartcockpit.com/docs/Smiths_Thales_A_1_0_1_FM_Pilot_Guide.pdf

**Comment by erso44** [comment]
Did not make any changes but EFOB values are the same.
![image](https://user-images.githubusercontent.com/39134287/122048675-e1872c00-cde1-11eb-9f23-78c9a968b0e4.png)
![image](https://user-images.githubusercontent.com/39134287/122048696-e6e47680-cde1-11eb-900c-b0d861820534.png)

This ticket can be closed.

**Comment by Parshva8888** [comment]
the issue is that the efob value often goes into -ve and when I open fuel
pred the efob then updates to what the fuel pred value is

**Comment by Parshva8888** [comment]
well my video states otherwise

**Comment by erso44** [comment]
Sry, I don't understand. Maybe someone else can work here if the issue still exists.

**Comment by Parshva8888** [comment]
check out the video I sent you
Look at the initial EFOB in FPLAN then see me go to fuel pred see how there
is a disparity in values then when I go back to the EFOB it changes back to
what it was in FUEL PRED which it should have been from the start

**Comment by moonfog7** [comment]
I can confirm that. EFOB for destination on FPL and FUEL PRED differ. If you click on FUEL PRED they are in sync for a moment and after a while these values diverge again.

**Comment by tracernz** [comment]
The fuel prediction is not continuously updated. That's listed as a TODO in the code... At the moment I don't think it's accurate for the new engine model either, but not sure.

**Comment by erso44** [comment]
> The fuel prediction is not continuously updated (this also affects the PERF APPR page, which is why it's on my "too look at" list). That's listed as a TODO in the code... At the moment I don't think it's accurate for the new engine model either, but not sure.

I have seen.
