### ISSUE TITLE
SELECT GROUND MARTIAL TO A SPECIFIC GATE 

### ISSUE THREAD

**Issue by Parshva8888** [flybywiresim/a32nx#4691]
### Aircraft Version

Development

### Description

When flying on vatsim it is not upto us as to which gate we get assigned to park to and there is no AGNIS available to any airports yet . So my idea is to integrate the airport map to the efb with gates and be able to select a gate where we want the ground crew to spawn to for a safe guided and precise parking. Please do consider making this if its possible it will be extremely helpful.  

### References (optional)

![image_2021-05-02_205944](https://user-images.githubusercontent.com/83544814/116818507-52072000-ab89-11eb-903c-fc0adf2d9236.png)

Interface like this but in the EFB and a PARK button when selected a specific gate confirming the spawning of the ground crew 

### Discord Username (optional)

Parshva8888#1339

**Comment by Benjozork** [comment]
Not related to the A32NX
