### ISSUE TITLE
AP erratic ascent/descent under turbulence

### ISSUE THREAD

**Issue by cedricyu803** [flybywiresim/a32nx#4692]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-01T16:15:19+00:00",
  "ref": "master",
  "sha": "dde55f7be56efe117b422af2bc75f8d5f308dbff",
  "actor": "lukecologne",
  "event_name": "manual"
}
```

### Describe the bug

I was flying the 05/01/2021 dev version with the new custom AP, from CYXY to CYVR. I was cruising at altitude 13,000ft, using the managed altitude mode (ALT CRZ). There was turbulence so the altimeter kept changing (and I kept being yelled at by ATC). The plane kept trying to catch up with the target altitude, and at some point, AP started switching itself to V/S, and the V/S rate changed erratically (ranging from +1100 to -1000 ft/min). Then, AP even decided to enter descent mode (when it should still be cruising). I had to switch to "selected altitude" and "level off aircraft" by hand.
The old dev version with the stock AP didn't have this problem.
I don't know if it is like that in real life, but that's what I observed. Thanks!

### Expected behavior

AP should remain in ALT CRZ mode.

### Steps to reproduce

1. Cruise below transition altitude
2. managed altitude mode
3. turbulence (altimeter changes rapidly)

**Comment by aguther** [comment]
Can you please provide a FDR file of that flight?

Please have a look here, section reporting issues:
https://docs.flybywiresim.com/start/autopilot-fbw/

Thanks!

**Comment by aguther** [comment]
Please also recheck the build info, the actor seems not matching to the commit.

**Comment by cedricyu803** [comment]
Hi, thanks for the reply. The build info is correct. In the description, "05/01/2021" is Eastern time; I tried this version at night, hours after I downloaded it. 
I have uploaded my FDR files with Simbrief flight plan on my Google Drive:
https://drive.google.com/drive/folders/1Jlgz3Ms9uNjWnFETZe3xGT7QH0T_0M4T?usp=sharing
Happened between DUXAR and CEESE

**Comment by aguther** [comment]
![image](https://user-images.githubusercontent.com/6629914/116973673-28e7ac00-acbd-11eb-8583-e8b2ab4720a0.png)
![image](https://user-images.githubusercontent.com/6629914/116973718-3b61e580-acbd-11eb-8543-296c572a9244.png)
![image](https://user-images.githubusercontent.com/6629914/116973749-47e63e00-acbd-11eb-89d3-9c798522501f.png)
![image](https://user-images.githubusercontent.com/6629914/116973781-52083c80-acbd-11eb-9b82-4b9211e3492a.png)

Based on that info I can tell:
- you only shortly stepped back to simulation rate 1x
- every switch of the AP mode was initiated by a push of the ALT knob on the FCU
- from the delta times I can see that you have been around 25 fps (at least from code perspective) which means with time compression of 2x you have been quite below the 17 fps

Reminder:
Time compression is not supported (yet) as stated https://docs.flybywiresim.com/start/autopilot-fbw/
