### ISSUE TITLE
Flypad CTD - Calling For Pushback Truck

### ISSUE THREAD

**Issue by Highflyer2010** [flybywiresim/a32nx#4698]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-02T22:18:21+00:00",
  "ref": "master",
  "sha": "8f323817ceb5336e0b069f532a07c0d4fe1fc429",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

Loaded into ENGM C&D. Setup aircraft then ready for push back. As soon as i called for the pushback truck that was when i crashed out. i've attatched a screenshot from the event viewer in references section

### Expected behavior

Pushback truck gets connected then pushes me back

### Steps to reproduce

1. Load in
2. Setup from cold and dark
3. call for pushback truck on flypad

### References (optional)

![Screenshot 2021-05-03 091839](https://user-images.githubusercontent.com/10485829/116855110-b8735900-abf0-11eb-8875-8b00db862a43.jpg)

### Discord Username (optional)

Highflyer2010#8932

**Comment by Saschl** [comment]
That's unfortunately an issue in the sim and some 3rd party sceneries. Sometimes gates are marked wrong (or misinterpreted by the sim) and that causes the issue. Not much we can do from our side.

**Comment by Highflyer2010** [comment]
okay thanks for your feedback. it's an access violation issue so is this compleatly normal and no need to repair or reinstall MSFS?

**Comment by Saschl** [comment]
Well I wouldn't call it "normal"  but yes your sim is just fine. Just remember to try and select another gate next time.

**Comment by Benjozork** [comment]
MSFS issue we have no control over
