### ISSUE TITLE
[BUG] Seat Belt, No Smoking Signs button, Ann LT and Emer Exit LT switches are not working

### ISSUE THREAD

**Issue by theersink** [flybywiresim/a32nx#470]
**Mod Version**
 Master

**Describe the bug**
 
Seat Belt, No Smoking Signs button, Ann LT and Emer Exit LT switches are not working and unable to be moved. No tooltips show for these as well. The signs button cursor changes to a finger but pressing does nothing.

**To Reproduce**

1. Load any flight 
2. Check switches on Instrument 8 panel
3. Does not matter if aircraft is started or not.
4. This make T.O config impossible to complete

**Expected behavior**

Switches should change position

**Actual behavior**

They cannot be interacted with in present Master build

**References**

![Non working switches](https://user-images.githubusercontent.com/70825153/92343211-bf10f700-f088-11ea-8afb-56c518f353e0.JPG)

**Additional context**

N/A

**Comment by wpine215** [comment]
Most likely cause appears to be #459

**Comment by AdenFlorian** [comment]
sorry!
