### ISSUE TITLE
On engine re-start N2 freezes at 25%

### ISSUE THREAD

**Issue by Taz5150** [flybywiresim/a32nx#4701]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-04-25T22:16:34+00:00",
  "ref": "master",
  "sha": "8cc7d5fd1cd3b962c03ae3276f47e386b902985c",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

On certain conditions (still to be investigated), when engine is turned off and re-started N2 does not go above 25% and the start-up procedure is frozen and does not advance.

A condition where this happens always is when fuel on board goes down to 0, and the engine shuts down automatically. When you put some fuel back again through the UI, and re-start the engine (APU Bleed On), the engine spools up until 25% N2.

### Expected behavior

If no other constraints are triggered (i.e. temperature, ...), engine should start-up as usual. 

### Steps to reproduce

1. Start aircraft on runway
2. Let fuel on board drop down to 0 and check engine shuts down
3. Turn APU on and APU Bleed ON
4. Set Engine Mode to Ignition and turn engine master (1 or 2) to ON
5. Let the engine spool up. It will stop at N2 25%.

### Additional info (optional)

This is not a FBW issue since it also happen on the vanilla version.

### Discord Username (optional)

TazX [Z+2]#0405

**Comment by mak60062** [comment]
Replicated.

**Comment by kiwi2021** [comment]
Test

**Comment by wpine215** [comment]
I no longer believe this issue exists, so will close. Feel free to re-open if not the case
