### ISSUE TITLE
APU starting issue

### ISSUE THREAD

**Issue by MrCooke13** [flybywiresim/a32nx#4705]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-04-15T22:57:32+00:00",
  "ref": "v0.6.0",
  "sha": "981b2e4b0e89998d21a70fe26de54a2f10066f6e",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

Unable to start the APU. I have tried the following with Shomas on Discord.

1) Batteries checked on, and fuel in the left inner
2) Clean reinstall
3) Empty community
4) UTF-8 Beta test enabled
5) Checked for keybinds related to APU
6) Checked sim version

![Microsoft Flight Simulator 03_05_2021 17_37_12](https://user-images.githubusercontent.com/83602641/116905834-6ace0f00-ac37-11eb-9821-fb215e932e1b.png)
![Microsoft Flight Simulator 03_05_2021 17_35_31](https://user-images.githubusercontent.com/83602641/116905841-6d306900-ac37-11eb-920c-f777dede714a.png)
![Uploading Microsoft Flight Simulator 03_05_2021 17_13_21.png…]()
![Microsoft Flight Simulator 03_05_2021 17_10_58](https://user-images.githubusercontent.com/83602641/116905878-7ae5ee80-ac37-11eb-980d-0607be3a3d8f.png)

### Expected behavior

Expected the APU to start after turning the master switch on and pressing the start button. Instead an error message displays on the PFD.

### Steps to reproduce

It happens every time while attempting to start the APU.

### Discord Username (optional)

MrCooke13

**Comment by MisterChocker** [comment]
> Instead an error message displays on the PFD.

Could you post a screenshot of that error message on the pfd?

And if you are able to see error messages on DUs the community folder is not empty besides the a32nx

**Comment by davidwalschots** [comment]
No response.
