### ISSUE TITLE
"Cabin crew seats for landing" is played twice

### ISSUE THREAD

**Issue by jaoord** [flybywiresim/a32nx#4706]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-02T22:18:21+00:00",
  "ref": "master",
  "sha": "8f323817ceb5336e0b069f532a07c0d4fe1fc429",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

When I press the "All" calls button before landing, the announcement is played twice with a couple of milliseconds difference

### Expected behavior

The announcement should only play once

### Steps to reproduce

1. Fly a normal flight
2. Start the descent
3. After a while you have to check if the cabin is ready
4. Press the All button in the calls section
5. The sound is played twice

**Comment by ExampleWasTaken** [comment]
Just did a flight on the latest version and the issue did not occur.

**Comment by jaoord** [comment]
I think it only happens when the blue text is there (check cabin ready?) because it also didn't happen to me yesterday. I will see if I can do some more testing tomorrow to find out under what circumstances it is happening.

**Comment by ExampleWasTaken** [comment]
The ECAM memo was blue. I pressed it in order for it to become green.

**Comment by hotshotp** [comment]
Could not reproduce. Please take a video of this issue happening

**Comment by jaoord** [comment]
I did another test today and again it worked fine. So I will close this ticket. 

Nice to see that bugs get auto-fixed just by creating an issue :)

**Comment by ExampleWasTaken** [comment]
> 
> 
> I did another test today and again it worked fine. So I will close this ticket.
> 
> Nice to see that bugs get auto-fixed just by creating an issue :)

😂 I wished it worked like that!
