### ISSUE TITLE
strange AP behaviour (?)

### ISSUE THREAD

**Issue by DerHofnarr** [flybywiresim/a32nx#4722]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-04-15T22:57:32+00:00",
  "ref": "v0.6.0",
  "sha": "981b2e4b0e89998d21a70fe26de54a2f10066f6e",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

Number 1: Sometimes the AP wants to fly a left-hand turn around a waypoint. Without input from the pilot or something. It happens suddenly and without warning. And the AP flies the turn in a really hard angle (20° or more I guess).

Number 2: sometimes when I make a ILS landing the AP disconnects 50 ft over the runway and goes into a hard nose down flight like a STUKA. 

### Expected behavior

Maybe no left-hand turns and not a so hard nose down flight? 

### Steps to reproduce

by fling and landing

### Additional info (optional)

I would like to thank you all for making this plane as it is and all that keeps the plane updated. Thank you verry much i love it and its perfect for the msfs2020!!! <3 :-)

**Comment by MisterChocker** [comment]
Regarding No1.
What does the flight director indicate? can you post a screenshot?

Regarding No.2
The latest stable version does not have the autoland functionality.

**Comment by DerHofnarr** [comment]
hi. thanks for the quick response. regarding no.2 thanks i understand now :) 

to number 1. the FD shows nothing just the green cross on the display goes to the left thats all. no warnings, no informations, just flying to the left and circle arround the waypoint. Im about to fly rn so maybe it happens again then i will make a video and post it. thanks for your help so far :)

**Comment by MisterChocker** [comment]
Well, when the FDs command the AP to fly to the left, then the AP will do that.

**Comment by DerHofnarr** [comment]
> 
> 
> Well, when the FDs command the AP to fly to the left, then the AP will do that.

hey yeah i know but the question is why he does that in midflight when im not touching anything?... hmmm.... i will keep an eye out if it happens again and i will post a video of that then maybe that helps figure it out why it happens. 

Cheers mate :-)

**Comment by MisterChocker** [comment]
Well it's important whether the FDs command a turn, or the turn happens on it's own.

The one would be an issue with the guidance in general, the other one would be a hint for some hardware noise, aka too low deadzone.

**Comment by Scotty4681** [comment]
Having the same issue AP on will fly towards waypoint then starts to drift left after recorrect to next waypoint as soon as it passes the waypoint aircraft again drifts to the left while AP is engaged happens at almost every waypoint  without any input from any controls and occurs at all altitude levels

**Comment by MisterChocker** [comment]
@Scotty4681 please post a screenshot of the pfd with FlightDirectors on.

**Comment by DerHofnarr** [comment]
im so sorry for let you wait. i had work. here is a video captured the behaviour: https://www.file-upload.net/download-14582824/APiscrazy.mov.html

**Comment by Valastiri** [comment]
> im so sorry for let you wait. i had work. here is a video captured the behaviour: https://www.file-upload.net/download-14582824/APiscrazy.mov.html

Since you are on stable you may have to set / increase your deadzones due to micro inputs not being detected where the AP does not disconnect and you encounter this issue. 

See -> [Reported Issues](https://docs.flybywiresim.com/start/reported-issues/#common-issues)

**Comment by DerHofnarr** [comment]
> 
> 
> > im so sorry for let you wait. i had work. here is a video captured the behaviour: https://www.file-upload.net/download-14582824/APiscrazy.mov.html
> 
> Since you are on stable you may have to set / increase your deadzones due to micro inputs not being detected where the AP does not disconnect and you encounter this issue.
> 
> See -> [Reported Issues](https://docs.flybywiresim.com/start/reported-issues/#common-issues)

thanks for the quick response i will try it. for now the options showing me 0% deadzone. do you think i should put this up? btw im playing with the T.A320 Pilot Sidestick by Thrustmaster (TCA). But right now i can tell that this shouldnt be the problem. :)

**Comment by MisterChocker** [comment]
> 0% deadzone

Yes, you have to increase the deadzone until your inputs are no longer getting any noise.

**Comment by Scotty4681** [comment]
I am trying to send you a video to show but its 2 minutes long and the website wont allow it is there any other way to show you whats going on ?

**Comment by Scotty4681** [comment]
![00E8DC88-1ECD-4B2E-9A88-27995B800F52](https://user-images.githubusercontent.com/82464582/119258556-2e3b6680-bb98-11eb-8b68-3525d2f7a754.png)
These are my settings

**Comment by MisterChocker** [comment]
@Scotty4681 

> @Scotty4681 please post a screenshot of the pfd with FlightDirectors on.

**Comment by Scotty4681** [comment]
![26E5788F-5DAD-4A79-BF01-65415D9FF124](https://user-images.githubusercontent.com/82464582/119375500-ddf00180-bc88-11eb-908f-e8faf591c8c1.png)
![F221DFE5-380A-462E-9570-52D2848AC4FD](https://user-images.githubusercontent.com/82464582/119375517-e2b4b580-bc88-11eb-95e3-18644bbc9b89.png)
They really dont show much both fd switches are on when ap is on plane heads to waypoint turns before the waypoint and then just keeps turning left without any inputs if i switch off the ap then back on then it heads back towards the waypoint until it nears it then does it all over again

**Comment by MisterChocker** [comment]
Well, this is not the ap thats doing this, the AP wants to fly to the right where the FD bars indicate.

So there is an input that causes this issue.

**Comment by MisterChocker** [comment]
Please join our discord and seek help in our support channel.

**Comment by Scotty4681** [comment]
Ok so which input causes this issue my settings are in the first screen shot i sent the other day

**Comment by MisterChocker** [comment]
Either you still have noise in your inputs or you press some keys on your keyboard that manipulate aerodynamic surfaces (maybe used the numpad?)
