### ISSUE TITLE
Black screen after Ready to Fly when starting from a parking spot

### ISSUE THREAD

**Issue by fahdriyami** [flybywiresim/a32nx#4727]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-05-05T23:03:06+00:00",
  "ref": "v0.6.1",
  "sha": "4a1cccc90ab3997109e394402ab9b41a80fbf325",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

When starting a flight from a parking spot, after loading and clicking Ready to Fly, the screen is black and remains black. Unable to even switch views. Sim completely unresponsive.

This only happens when starting from a parking spot. When starting from a runway, everything the sim loads fine. It's almost as if when starting from a parking spot, the plane is not able to change state to cold and dark or something. Preventing anything from loading.

### Expected behavior

Load into the cockpit.

### Steps to reproduce

1. Start a new flight from World Map. Load a SimBrief Flight Plan (departure Nice LFMN).
2. Select aircraft (in my case FBW A320NX with a British Airways livery)
3. Select Gate 44.
4. Start flight.
5. After loading completes, select Ready to Fly.

### Additional info (optional)

I also have Volanta, Navigraph Charts, and SimLink running.

I attempted uninstalling the A320NX and reinstalling the latest Stable version using the FBW Installer. Same issue.

Flight Simulator Version: 1.15.10.0 (Steam Edition)

**Comment by scoopscode** [comment]
This is most likely an MSFS issue.

**Comment by solarisfire** [comment]
I had this earlier, maybe something to do with patch 1.15.10.0?

I found if I just left the sim for a few minutes (possibly 10, I'd given up thinking it had crashed and walked away to do something else while leaving it running) everything would come back to life.

**Comment by fahdriyami** [comment]
> I had this earlier, maybe something to do with patch 1.15.10.0?
> 
> I found if I just left the sim for a few minutes (possibly 10, I'd given up thinking it had crashed and walked away to do something else while leaving it running) everything would come back to life.

That might be the case, as the sim does really crash, its just a black screen. I'll try waiting for longer to see if it comes back.

**Comment by fahdriyami** [comment]
I left it running for 20 minutes. Still on a black screen. I did notice that Task Manager says the sim is unresponsive.

I should mention that I also tried uninstalling and reinstalling the A320NX using the FBW Installer. Same issue.

![FBW-BlackScreen](https://user-images.githubusercontent.com/39507780/117341431-28186b00-aeb3-11eb-81c2-2804216fce89.JPG)

**Comment by scoopscode** [comment]
Have you tried using a different aircraft to see if the FBW is the only one causing this issue?

**Comment by fahdriyami** [comment]
> Have you tried using a different aircraft to see if the FBW is the only one causing this issue?

Yes, I tried with the default A320 and the Icon A5. They load normally.

**Comment by scoopscode** [comment]
Also, what are your MSFS settings?

**Comment by fahdriyami** [comment]
> Also, what are your MSFS settings?

Graphics is set to Ultra at 3440x1440. Data is on, Flight model at modern, dev mode off, assistance settings set to hard.

**Comment by scoopscode** [comment]
What's your GPU?

**Comment by fahdriyami** [comment]
> What's your GPU?

i7-9700K, RTX 3090 FE, 32GB RAM, sim is installed on a 500GB NVMe drive.

**Comment by fahdriyami** [comment]
Surprisingly, I decided to try it from a gate at OMDB, and it loaded just fine. Something about LFMN maybe?

**Comment by MisterChocker** [comment]
Do you have by any chance custom scenery/airport for LFMN?

**Comment by MisterChocker** [comment]
Is this still an issue? I am unable to reproduce the issue.

**Comment by fahdriyami** [comment]
I just gave it a try again after days of flying different routes without issue. Im attaching the flight plan file I used. I changed the extension from .pln to .txt to upload.

Do you also have the France World Update installed? I believe it has a handcrafted LFMN that might be contributing?

[LFMNEGGP_FSX_06May21.txt](https://github.com/flybywiresim/a32nx/files/6488142/LFMNEGGP_FSX_06May21.txt)

**Comment by MisterChocker** [comment]
> Do you also have the France World Update installed?

I don't know, I assume so, my sim is up to date.

**Comment by fahdriyami** [comment]
> > Do you also have the France World Update installed?
> 
> I don't know, I assume so, my sim is up to date.

Sim updates are different. World Updates need to be installed manually from the Content Manager.

**Comment by MisterChocker** [comment]
Has the recent SU changed anything for you?

**Comment by MisterChocker** [comment]
Closing since no response.
