### ISSUE TITLE
AP disconnecting all the time

### ISSUE THREAD

**Issue by Mermaid313** [flybywiresim/a32nx#4728]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-05T13:39:44+00:00",
  "ref": "master",
  "sha": "7601e1813408fb0844d9a7773b6789aefcbd58d2",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

Aircraft constantly disconnects AP over and over again while flying (no matter which part of the flight). It seems to be arbitrary.  Sometimes fly for minutes without disconnecting.

No problem with the Stable Version. 

### Expected behavior

Like in the stable version: Keeping the AP enabled. 

### Steps to reproduce

1. Latest development versions (have been doing this for one week with diverent development versions)
2. Fly IFR
3. Mostly during climb phase this occurs

### References (optional)

Video of problem:

https://www.dropbox.com/s/irnx3o6ka2u8knl/2021-05-06%2008-15-01.mp4?dl=0

**Comment by solarisfire** [comment]
Are you using any specific hardware? I've seen certain HOTAS's throw phantom inputs (both buttons and axis inputs) that can disconnect the AP.

**Comment by MapleNAV-TCASFAULT** [comment]
If you have a lot of noise coming from your controller, it may disconnect your autopilot. I would suggest you to disconnect your controller and see if it persists. If it stops it means that you need to up your deadzones. If it still continues you may want to check your keybindings.

**Comment by aguther** [comment]
First of all it seems even in your video not "disconnecting all the time".

The here a few recommendations / questions:
- Do you have any unknown/double bindings on a key or button to disconnect the AP?
- Are you sure there is no noise on your hardware inputs?
- Have you tried to increase your dead-zones of the hardware?

Right now, the only things that might disconnect the AP are:
- Disconnection due to protection being active (not your case)
- Disconnection by hardware input
  - more than 50% of roll
  - more than 50% of pitch
  - more than 40% of rudder

And to be clear: I have very small dead-zones on my Thrustmaster Warthog and Thrustmaster TPR Rudder and no issues at all.

**Comment by MisterChocker** [comment]
@Mermaid313 Looks like your mouse dose unwanted double clicks.

**Comment by Mermaid313** [comment]
Dear all,

Thanks for your quick and helpful answers. I adjusted the deadzones to 40% on all axes, but the problem still existed. 
Then I unplugged my joystick and the problem was gone. I have to confess that I have a very cheap joystick (Speedlink Black Widow) and I had the **same problem** one year ago with the JARDESIGN A320n at X-Plane. I guess I have to upgrade my hardware. 

However, in the stable version (without the newly implemented throttle setting) my joystick works fine.

**Comment by aguther** [comment]
Based on the info that even with a very large dead-zone it’s not solved I would guess it’s not about that.
I guess it‘s more related to an button assignment. Please recheck all the buttons that are assigned for that specific joystick and see if it works then. Maybe just remove all assignments and then add one by one.

**Comment by Mermaid313** [comment]
Your doubts motivated me to just change the USB jack. Since that action, I haven't noticed this problem in my first two test flights. It that even possible?

**Comment by aguther** [comment]
> Your doubts motivated me to just change the USB jack. Since that action, I haven't noticed this problem in my first two test flights. It that even possible?

Sounds strange to me. But you never know. I have a KVM switch at home and when I switch there and back again the sim hangs for 20 s or so…so who knows…
