### ISSUE TITLE
Throttle lever resets itself

### ISSUE THREAD

**Issue by sinistre1973** [flybywiresim/a32nx#4730]
### Aircraft Version

Development

### Build info

```json
"built": "2021-05-06T07:02:50+00:00",
"ref": "master",
"sha": "73ed584d7be313f72b2869618582d8af77fca1e0",
"actor": "Benjozork",
"event_name": "manual"
```

### Describe the bug

When accessing the Options (i.e. with the Escape key) and resuming the flight, the throttle resets itself to just about the positions where the "A" (from A/THR) is.

### Expected behavior

The throttle should not move by itself

### Steps to reproduce

1. Spawn anywhere
2. Calibrate throttle in the EFB
3. Focus your cockpit camera on the throttle
3. Press "escape"
4. Click options
5. resume the flight to the cockpit

### Discord Username (optional)

sinistre#6294

**Comment by sinistre1973** [comment]
Update: it seems to only do this after calibrating the throttlein the EFB

**Comment by Saschl** [comment]
It probably also deploys flaps and speedbrakes when entering the menu. It’s unfortunately an issue from world update 4y

**Comment by sinistre1973** [comment]
I can confirm that the speedbrakes are also deployed
