### ISSUE TITLE
Changing metric to imperial units no longer works

### ISSUE THREAD

**Issue by Owenwilsonsnose** [flybywiresim/a32nx#4731]
### Aircraft Version

Development

### Build info

```json
TBD
```

### Describe the bug

Changing units in the mcdu from kgs to lbs no longer works / saves. This also includes the EFB (specifically the fuel page) not properly updating either

### Expected behavior

Being able to change units to imperial

### Steps to reproduce

1. power on aircraft
2. go to mcdu>options and change units from kg to LB
3. restart sim
4. FBW plane defaults back to metric

**Comment by solarisfire** [comment]
Yeah, this is doing the same for me on the latest dev build.

**Comment by solarisfire** [comment]
Did this ever work?

Looks like the logic is in:
/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Fuel.js

and totally hardcoded to KG...

**Comment by tracernz** [comment]
> restart sim

Can you expand on this? The settings will not save if you Alt+F4 or otherwise force FS to close. You have to quit through the button on the main menu.

**Comment by MisterChocker** [comment]
Changing units requires to reload the aircraft, this can be done by exiting to the main menu and then starting a new flight.

**Comment by MisterChocker** [comment]
> Looks like the logic is in:

The "logic" for the unit switch is in the options section.
Every DisplayUnit that uses a unit such as KG/LBS simply reads the corresponding unit during initialization and then sticks with it.

> /Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Fuel.js
> 
> and totally hardcoded to KG...

Do you have a line in that file us to check? Btw it's not hardcoded

**Comment by MisterChocker** [comment]
Closing since no response from op.
