### ISSUE TITLE
spoilers keep deploying random

### ISSUE THREAD

**Issue by csimms1099** [flybywiresim/a32nx#4735]
### Aircraft Version

Stable

### Build info

```json
"built": "2021-05-05T23:03:06+00:00",
  "ref": "v0.6.1",
  "sha": "4a1cccc90ab3997109e394402ab9b41a80fbf325",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

hi  i just updated my fbw a320 and my spoliers are deployed a little bit i put them to retract and lock and it still happens pls help me if anyone can thanks from csimms1099
![image](https://user-images.githubusercontent.com/83798079/117389261-15edfb00-aeba-11eb-8da0-152ef053c39d.png)
![image](https://user-images.githubusercontent.com/83798079/117389289-1f776300-aeba-11eb-9a8d-f28ab2e005b4.png)

### Expected behavior

i was expecting the aircraft to have no issues when i updated it worked fine for me before

### Steps to reproduce

1 i load my flight and i turn my battery on then check every thing outside and i notice the spoilers are up a little bit i lock my spoilers then it puts it down then it comes up again

### References (optional)

![image](https://user-images.githubusercontent.com/83798079/117389778-e7bceb00-aeba-11eb-8504-2313bf51310d.png)
![image](https://user-images.githubusercontent.com/83798079/117389789-ed1a3580-aeba-11eb-9da1-3b54484ef67d.png)

### Discord Username (optional)

csimms #9970

**Comment by Valastiri** [comment]
Discussed on Discord. 

Discovery led to a possible hardware issue where the knob used for the spoiler axis wasn't fully utilizing the entire range of motion causing the issues described above.
