### ISSUE TITLE
[REQUEST] Add "CABIN READY" T.O. Config Memo

### ISSUE THREAD

**Issue by wpine215** [flybywiresim/a32nx#474]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the feature you'd like to see implemented**

Add "CABIN READY" memo to T.O. Config, which should turn from blue to green when either the FWD or ALL flight attendant call button is pressed (lower left overhead). Normally this would be accomplished through the FAP (flight attendant panel), however that is not modeled or implemented in this or any other aircraft. Using the call button as a way of fulfilling the CABIN READY memo is used in the ToLiss A319/21, for example.

**Comment by wpine215** [comment]
Should also be added to landing config ECAM memo as well.

**Comment by aap007freak** [comment]
Imho the better way to implement this is to automatically show the CABIN READY message 3-5 minutes after engine start. No need to press call buttons.
