### ISSUE TITLE
Aircraft trimming itself 

### ISSUE THREAD

**Issue by Oliverski001** [flybywiresim/a32nx#4740]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-07T08:06:42+00:00",
  "ref": "master",
  "sha": "ff965b22730e27b972aff4026e76b14170c3106d",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

When using the aircraft off autopilot the aircraft can randomly trim itself. When on autopilot you can see the autopilot working against the trim wheel resulting in the trim wheel flickering.

### Expected behavior

The trim wheel should stay where it is lest unless on autopilot

### Steps to reproduce

1. Use the plane off autopilot

### Discord Username (optional)

Oliverski001#1816

**Comment by CBGonzalez** [comment]
I think you´re thinking Boeing. In the Airbus the trim will move even without AP engaged, trying to maintain whatever attitude you commanded with the stick (i. e. it will be reacting to wind changes, throttle changes etc.). That´s my understanding, at least.

**Comment by solarisfire** [comment]
Yeah, this is as intended... the Flight Computer has Auto-leveler, Bank and Pitch Limiters and will trim all by itself. It should stop if you turn off sec 2 / sec 3 flt ctl on the overhead but not sure if this is modelled...

**Comment by aguther** [comment]
This is called auto trim function and works as intended.

**Comment by hotshotp** [comment]
This is working as intended

**Comment by Oliverski001** [comment]
I think there has been a miss understanding of what I am saying I have attached a video link.
https://youtu.be/nZXFYgu_Kxs

**Comment by aguther** [comment]
So you’re talking about ground. Never seen doing it that way. Although it’s not completely what you’re doing to be honest. 

- Why are you moving the throttles?
- How can you move the trim with the move even when not over the trim wheel?
- Have checked all your assignments and are your sure no hidden assignments are there?

**Comment by Oliverski001** [comment]
I am throttling up for takeoff or taxi and it will just move the trim wheel by itself. I am not moving it after setting the initial trim. when in the air you can see the aircraft trying to do the same thing but autopilot stops it from happening.

**Comment by Oliverski001** [comment]
thank you for your help turns out my rudder peddles had trim bound to them
