### ISSUE TITLE
Wont load

### ISSUE THREAD

**Issue by TinnyTerr** [flybywiresim/a32nx#4745]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-05-05T23:03:06+00:00",
  "ref": "v0.6.1",
  "sha": "4a1cccc90ab3997109e394402ab9b41a80fbf325",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

Aircraft won't load in the A32NX mod, I have deleted all other mods and liveries for MSFS. Only mod is the aircraft mod. 
![image](https://user-images.githubusercontent.com/74470480/117537438-ba765700-aff8-11eb-803c-ce18198201af.png)

### Expected behavior

Aircraft load and features not default

### Steps to reproduce

1. Download using flybywire installer
2. Open MSFS
3. Load into any airport with said A320
4. Attempt any added features and 

### Additional info (optional)

Stopped working since the V0.5.4 batch

### Discord Username (optional)

Mr. Reee#2133

**Comment by tshomas** [comment]
Have you selected the flybywire A320 on the aircraft selector list? You should see two A320s now alongside the 747/Cessnas etc etc?

**Comment by TinnyTerr** [comment]
> Have you selected the flybywire A320 on the aircraft selector list? You should see two A320s now alongside the 747/Cessnas etc etc?

Yea I have, its weird

**Comment by tshomas** [comment]
And you see the FBW livery? Is the iPad visible on the left hand side of the cockpit when you load in?

**Comment by TinnyTerr** [comment]
> And you see the FBW livery? Is the iPad visible on the left hand side of the cockpit when you load in?

Let me try it, be a minute

**Comment by TinnyTerr** [comment]
> And you see the FBW livery? Is the iPad visible on the left hand side of the cockpit when you load in?

Just tried it, switched liverys and seems to work weirdly :/ Working for now.
