### ISSUE TITLE
KEYBOARD BINDING

### ISSUE THREAD

**Issue by leka1986** [flybywiresim/a32nx#4747]
### Aircraft Version

Experimental

### Description

Key bindings for Battery master

**Comment by solarisfire** [comment]
Would be nice... I'd love to stick more of the overhead panel buttons onto my streamdeck.

APU master / Start / both batt buttons / ground power / fuel pumps? All keybindable?

**Comment by Benjozork** [comment]
Key bindings are controller by MSFS
