### ISSUE TITLE
[BUG] Without external power screens not turning on even if apu power avail.

### ISSUE THREAD

**Issue by enesaydogan** [flybywiresim/a32nx#475]
**Mod Version**
 "master" 

**Describe the bug**
Without external power screens not turning on even if apu power avail.

**To Reproduce**

1. Turn on batteries
2. Start apu
3. Apu gen on
4. Screens still off ?
5. Activate external powers screens comes on?

**Expected behavior**
Screens should turn on on apu powers.

**Actual behavior**
Without external power screens not turning.

**References**
![11](https://user-images.githubusercontent.com/20522050/92360934-4ba5ce80-f0f6-11ea-96ff-ce3af99ae3b9.JPG)
![12222](https://user-images.githubusercontent.com/20522050/92360938-4f395580-f0f6-11ea-9806-1f564c50fa8f.JPG)

**Additional context**
Yes i turned brightness knobs to full before anyone asking for it.
**Even after self test completed turning off external power while apu running turns screens off.**
To fix problem i had to shut down apu and start again.

**Comment by Venorcis** [comment]
I had this issue, then I didn't, and then I had again. I'm still trying to figure out what the exact configuration in which this happens is, but there's indeed still a problem somewhere. With either EXT PWR or the engines started, there's never a problem, but with just the APU there sometimes is.

**Comment by enesaydogan** [comment]
#421 #418 sorry for duplicates saw these after posting 🤦‍♂️.

**Comment by AdenFlorian** [comment]
closing duplicate
