### ISSUE TITLE
New simvars doesn't work

### ISSUE THREAD

**Issue by SchmidtDawid** [flybywiresim/a32nx#4757]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-09T13:56:29+00:00",
  "ref": "master",
  "sha": "9e66321a2021f4635c89c287466633cbd879ed53",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

Read simvar in unable. I'm using simconnect directly and i got error like:
Error add SimVar ( A32NX.FCU_LOC_MODE_ACTIVE ) in AddToDataDefinition :    
`Error add SimVar ( A32NX_AUTOPILOT_HEADING_SELECTED ) in AddToDataDefinition : SIMCONNECT_EXCEPTION_NAME_UNRECOGNIZED. Please control name ( A32NX_AUTOPILOT_HEADING_SELECTED ) and unit ( Number )`
I tried with many variations like:
A32NX_AUTOPILOT_HEADING_SELECTED
A32NX.AUTOPILOT_HEADING_SELECTED
A32NX AUTOPILOT HEADING SELECTED
A32NX.AUTOPILOT HEADING SELECTED
A32NX. AUTOPILOT HEADING SELECTED

i tried to use simvars from here:
https://github.com/flybywiresim/a32nx/blob/experimental/docs/a320-simvars.md

### Expected behavior

read simvars by simconnect

### Steps to reproduce

Try to register any simvar in simconnect

### Discord Username (optional)

DraveS

**Comment by aguther** [comment]
Local variables cannot be read via SimConnect. That is a limitation of the SimConnect API we cannot control. Please open a ticket on MSFS.
