### ISSUE TITLE
Custom A/P Problems

### ISSUE THREAD

**Issue by DecMoonFR** [flybywiresim/a32nx#4758]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-09T09:30:41+00:00",
  "ref": "master",
  "sha": "855f6f23179f21c205cb42ae29dd99b288bf3351",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

I've got the same problem with flx temperature set than #4753 

This and many more problems

One event spammed (speed)
377328 *** EVENT: Cntrl= 67042 (0x000105e2), Param= 100 (0x00000064) LIGHT_POTENTIOMETER_24_SET

After start APU, another event spammed
539500 *** EVENT: Cntrl= 65891 (0x00010163), Param= 1 (0x00000001) AP_PANEL_SPEED_HOLD

For departure, a sync flight plan with simbrief, activate FD, set speeds, flaps and temperature setting in t/o phase
Switch speed to selected (230), heading Managed, and altitude to managed

Just after take/off heading go to selected, and altitude to vs/speed at +2200

   812265 *** EVENT: Cntrl= 66079 (0x0001021f), Param= 0 (0x00000000) GEAR_UP
   812312 *** EVENT: Cntrl= 67076 (0x00010604), Param= 2 (0x00000002) ELECTRICAL_BUS_TO_CIRCUIT_CONNECTION_TOGGLE
   812312 *** EVENT: Cntrl= 67076 (0x00010604), Param= 2 (0x00000002) ELECTRICAL_BUS_TO_CIRCUIT_CONNECTION_TOGGLE
   812312 *** EVENT: Cntrl= 67076 (0x00010604), Param= 3 (0x00000003) ELECTRICAL_BUS_TO_CIRCUIT_CONNECTION_TOGGLE
   812312 *** EVENT: Cntrl= 67076 (0x00010604), Param= 3 (0x00000003) ELECTRICAL_BUS_TO_CIRCUIT_CONNECTION_TOGGLE

813578 Button changed: bRef=0, Joy=0 (A), Btn=3, Pressed
   813578 [Buttons.Airbus A320 Neo Air France 80 Ans (A32NX Converted)] 0=PA,3,C32768,0
   813578 *** EVENT (Custom): Cntrl= 32768 (0x00008000), Param= 0 (0x00000000) A32NX.FCU_AP_1_PUSH
   813578 FS Control Sent: Ctrl=32768, Param=0 :A32NX.FCU_AP_1_PUSH
   813781 Button changed: bRef=0, Joy=0 (A), Btn=3, Released

A/P didn't engage. Can't do anything with hardware or in cockpit about A/P, heading managed don't do anything.

Speed stay very low (just above stall)

Flight Test : LFKJ to LFMN via LONSU

### Expected behavior

A/P can be activated via hardware (i'v got FSUIPC)

Heading stay to managed after take/off
Free climbing to selected altitude at speed selected

### Steps to reproduce

- Start cold/dark lfkj
- Align IRS
- Sync F-PLAN
- Add SID
- Add Star (very short flight)
- Set T/O Phase parameters
- Set Speed selected (230)
- Set Heading Managed (---)
- Set Altitude Managed (21000 with a dot)
- Taxi to runway
- Take/off

**Comment by aguther** [comment]
Your issue is very confusing in the sense that I don't understand what the Gear Up events have to do with the custom AP.

I tested all the events and they work fine also with FSUIPC and SPAD.neXt.

Maybe there is the reason that you can't turn on AP?

For example AP is inhibited for 5s after lift-off and 100 ft RA. Same goes for when you are in alpha protection mode.

So in those cases it will not engage whatever you do and it's completely correct behavior.

So please provide evidence why you're sure it should engage and also post screenshots. Feel free to reopen then.
