### ISSUE TITLE
EFB Plane Flashing/Flickering and ADF Identifier Flashing/Flickering

### ISSUE THREAD

**Issue by Iunoi** [flybywiresim/a32nx#4760]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2021-05-05T06:28:31+00:00",
  "ref": "experimental",
  "sha": "ff7f81fbff658ba8a69c77f6a16754ad1bffabea",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

EFB Plane on the Map is flickering and flashing.
I have the same issue in the RAD/NAV page ( ADF1/2 identifier is flashing) 

### Expected behavior

They should not flash.

### Steps to reproduce

1. Load the plane, turn on Batteries, and external power.
2. EFB plane is already flashing.
3. FMC - RAD/NAV Page enter an nearby ADF Freq. 

### References (optional)

https://user-images.githubusercontent.com/19224974/117581119-88015280-b0fb-11eb-8f77-bb6dd71698c8.mp4

### Discord Username (optional)

iunoi#8403

**Comment by tracernz** [comment]
Please, one issue per issue. EFB flashing icon is a known issue (#4643) since world update 4, and the ADF reception glitching is also a known issue (#3070).
