### ISSUE TITLE
EFB Map Buttons show Boxes

### ISSUE THREAD

**Issue by Iunoi** [flybywiresim/a32nx#4761]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2021-05-05T06:28:31+00:00",
  "ref": "experimental",
  "sha": "ff7f81fbff658ba8a69c77f6a16754ad1bffabea",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

EFB Map Buttons are Boxy

### Expected behavior

There should be a - / + or other buttons.

### Steps to reproduce

Power up EFB
Look on the lower right side of the map

### References (optional)

![image](https://user-images.githubusercontent.com/19224974/117581153-b1ba7980-b0fb-11eb-81df-5740492d606c.png)

### Discord Username (optional)

iunoi#8403

**Comment by antonyisoardi** [comment]
Looks as though the characters that leaflet uses are "special" that are not included in whichever font is being loaded, that's why nm and + are still visible. The font might actually be missed at build.

**Comment by antonyisoardi** [comment]
With further investigation, font is being loaded from Google Fonts, which looks to be the same one that's actually used in the map component. Even using the unicode it renders as an absent character. Oddly the map component renders the characters correctly in Storybook.eeeeeeeeeee

```
<h1 className="text-white font-medium mb-4 text-2xl">Map&#8614;</h1>
```

![image](https://user-images.githubusercontent.com/5309174/119204811-121cc400-bac9-11eb-9545-53628a876cf5.png)
