### ISSUE TITLE
Cockpit lighting knobs not working

### ISSUE THREAD

**Issue by 64Bandmaster** [flybywiresim/a32nx#4765]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2021-05-05T06:28:31+00:00",
  "ref": "experimental",
  "sha": "ff7f81fbff658ba8a69c77f6a16754ad1bffabea",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

Overhead panel and pedestal integrated lighting brightness knobs don't seem to work now.

### Expected behavior

Should control the brightness of the lighting

### Steps to reproduce

Tried to adjust cockpit lighting.

**Comment by 64Bandmaster** [comment]
Actually, now there are many knobs in the cockpit not working.  almost none.  I'm in a flight now and can't change altitude, range, heading...  basically nothing.

**Comment by Benjozork** [comment]
This is an MSFS issue that happens rarely and randomly. The most common solution is to either wait until it does away or try switching from internal to external cams a few times.

By the way, as we announced on all social media and Discord, experimental has been discontinued for a few weeks now and all its features merged into dev. You shouldn't be using it, although that's not related to your bug.
