### ISSUE TITLE
Batteries with no voltage - showing 0,0v

### ISSUE THREAD

**Issue by SibbeK** [flybywiresim/a32nx#4778]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-05-05T23:03:06+00:00",
  "ref": "v0.6.1",
  "sha": "4a1cccc90ab3997109e394402ab9b41a80fbf325",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

Batteries showing 0,0v
I tried starting at the gate as well as on the RWY but voltage is in all setups shown with 0,0v

### Expected behavior

When starting the Airbis from cold&dark even screens for batteries should be dark.
When starting batteries voltage should be OK and not 0,0v

### Steps to reproduce

Set up flight in world map from EDDT to EDDM (and different destinations) starting from gate as well as starting from RWY.

### References (optional)

![Batteries](https://user-images.githubusercontent.com/84012724/117794025-1cc79580-b24d-11eb-94b9-19b74f32449d.jpg)

**Comment by SibbeK** [comment]
yes it does

**Comment by scoopscode** [comment]
> yes it does

I believe that is what is causing the issue here.

**Comment by Benjozork** [comment]
From our reported issues page...

![image](https://user-images.githubusercontent.com/4503241/117889189-1d7a1f00-b281-11eb-91ea-84df562d44b2.png)
