### ISSUE TITLE
APU won't start after a dual engine fault

### ISSUE THREAD

**Issue by Villason** [flybywiresim/a32nx#4781]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-05-05T23:03:06+00:00",
  "ref": "v0.6.1",
  "sha": "4a1cccc90ab3997109e394402ab9b41a80fbf325",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

APU won't start after a dual engine fault.

![vlcsnap-2021-05-11-16h17m12s403](https://user-images.githubusercontent.com/5116259/117831517-edc51a00-b274-11eb-8f27-e325fbebf045.png)

### Expected behavior

APU should start, if requested, after a dual engine failure.

### Steps to reproduce

1. Configure a dual engine loss at a certain altitude/time.
2. Engines fail.
2. APU MASTER SW on.
3. APU START pb.
4. APU FAULT.

**Comment by davidwalschots** [comment]
Currently the MASTER SW fault light can illuminate in three situations:
1. One or both BAT push buttons OFF (starter motor doesn't get powered).
2. No fuel remaining in the left inner wing tank.
3. APU fire button released.

Did any of these apply to you?

**Comment by Villason** [comment]
Nope. Batteries ON, take off fuel, no fire in APU.

**Comment by davidwalschots** [comment]
Ah. You are using the stable version. In stable the engines out scenario isn't supported yet. I've just tested it in the latest development version and there an APU start in the air without engines running works well.

**Comment by Villason** [comment]
> 
> 
> Ah. You are using the stable version. In stable the engines out scenario isn't supported yet. I've just tested it in the latest development version and there an APU start in the air without engines running works well.

I noticed in the dev build the APU still won't start if in the same scenario you didn't retract the landing gear.

**Comment by davidwalschots** [comment]
That is correct behaviour. When the landing gear is not up and locked in an emergency electrical situation the battery charge limiter opens the contactor towards the DC BAT BUS (which powers the APU starter motor). Refer to #3625 for details.
