### ISSUE TITLE
Sometimes any arrival option gets ignored

### ISSUE THREAD

**Issue by wilpin** [flybywiresim/a32nx#4782]
### Aircraft Version

Stable

### Build info

```json
"built": "2021-05-05T23:03:06+00:00",
  "ref": "v0.6.1",
  "sha": "4a1cccc90ab3997109e394402ab9b41a80fbf325",
  "actor": "Benjozork",
  "event_name": "manual"
```

### Describe the bug

I'm using v0.6.1 stable and as a good example in Hong Kong ,any ILS approach selected in the fms for  ZGSZ initially is followed showing the waypoint name its flying to in white but at the next waypoint the route is gets ignored and all waypoint texts are green withplane  turning left and flying direct to airport it self not runway. This has happened on another occasion somewhere in India and I know a fried has the same issues.
I ,then, cannot 'undot' heading unless I ,strangely, select the loc option , then I can change heading but plane doesn't respond. As soon as I unselect loc  my heading gets 'dotted' , managed.
I've used the same ILS appraches using the msfs2020 airbus with no issues at all.
This is such a shame  as it's such a nice plane to fly but given this issue and the fact that as a result you cannot specify your own heading and do your own ILS approach, I have to revert to the ms version :(
As you can tell from my terminology , I'm not a real pilot but enjoy testing software.

### Expected behavior

You expect the plane not to deviate from the approach programmed in the fms

### Steps to reproduce

Import simbrief flightplan into fms or
Take off from ZGSZ and program FMS VMML/ZGSZ (Macao - Hong Kong)
Interestingly it accepts ZGSZ/ZGSZ  
Take off from Hong Kong and after a a minute:
add ILS apprach to ZGSZ 
This works well in the default ms airbus

**Comment by hotshotp** [comment]
Duplicate #939
