### ISSUE TITLE
seatbelt sign dont work

### ISSUE THREAD

**Issue by airfirefighter** [flybywiresim/a32nx#4787]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-11T18:24:30+00:00",
  "ref": "master",
  "sha": "304755d87433eebe94b6936cca7ac41eee8dea69",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

the seatbelt sign dont work from the plane to pacx or slc but work from pacx and slc to plane.So u cant control the seatbelt signs direct from plane but u can control them from other programs 

### Expected behavior

control thru the aircraft button the seatbelt to all the other programs that use fsuipc for seat belt .

### Steps to reproduce

1.just open the slc or pacs and use the seatbelt sign button of the plane. dosent control nothing
2. use the buttons from any of the programs and u can see that controls the seatbelt of the plane

**Comment by aguther** [comment]
What is pacx and slc?

**Comment by Saschl** [comment]
I just did a quick test again and it does sync into both directions for me. I suggest you try again and if nothing helps a clean reinstall of the mod and a FSUIPC update is advised. If it still doesn't help I would need a screenshot and/or video from the situation.

@aguther SLC (Self Loading Cargo) and PACX are passenger simulation tools which rate your flight etc.

**Comment by frankkopp** [comment]
It works for me with FSUICP (for SLC=Self Loading Cargo) and also with SPAD.neXt. There must be something in your environment.

**Comment by Watsi01** [comment]
I use FSUIPC and tested it yesterday. It works. Plane > PACX. @airfirefighter which FSUIPC version do you use?

**Comment by airfirefighter** [comment]
> I use FSUIPC and tested it yesterday. It works. Plane > PACX. @airfirefighter which FSUIPC version do you use?

i dont know were to look about the version maybe its better if i delete the fsuip and reinstall it.Can u plz if its possible to provide a link to download the latest version if its possible?thanks a lot!!

**Comment by frankkopp** [comment]
> > I use FSUIPC and tested it yesterday. It works. Plane > PACX. @airfirefighter which FSUIPC version do you use?
> 
> i dont know were to look about the version maybe its better if i delete the fsuip and reinstall it.Can u plz if its possible to provide a link to download the latest version if its possible?thanks a lot!!

![image](https://user-images.githubusercontent.com/16833201/117940959-ec91fc80-b309-11eb-92cd-1af34d4ad1c9.png)

http://www.fsuipc.com/

**Comment by airfirefighter** [comment]
> > > I use FSUIPC and tested it yesterday. It works. Plane > PACX. @airfirefighter which FSUIPC version do you use?
> > 
> > 
> > i dont know were to look about the version maybe its better if i delete the fsuip and reinstall it.Can u plz if its possible to provide a link to download the latest version if its possible?thanks a lot!!
> 
> ![image](https://user-images.githubusercontent.com/16833201/117940959-ec91fc80-b309-11eb-92cd-1af34d4ad1c9.png)
> 
> http://www.fsuipc.com/

i have 7.0.0

**Comment by Watsi01** [comment]
The latest version is 1.0
See here:
https://forum.simflight.com/topic/80977-updated-modules/

**Comment by frankkopp** [comment]
> The latest version is 1.0
> See here:
> https://forum.simflight.com/topic/80977-updated-modules/

you mean 7.1.0 - yea need to update as well :) - but the seat belt sign works with 7.0.9 in any case.

**Comment by Watsi01** [comment]
@airfirefighter  7.0.0  is for sure too old.

**Comment by airfirefighter** [comment]
i just install  7.1.0 and i still have the same problem......

**Comment by airfirefighter** [comment]
its working the reason that wasn't work was another time the add on co pilot....i remove it and everything is ok......Thanks a lot for your help guys and iam sorry for the bug report....the bug is in my head... : /    iam closing  the report thanks alot!!!!!!!
