### ISSUE TITLE
Cruise Level changes when new Alt is set on the AP panel

### ISSUE THREAD

**Issue by nowhereman62** [flybywiresim/a32nx#4789]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-11T18:24:30+00:00",
  "ref": "master",
  "sha": "304755d87433eebe94b6936cca7ac41eee8dea69",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

I get an altitude on Vatsim, say FL140, and even though the cruise level in the PROG and INIT page is FL380, a new cruise level gets validated (FL140) in the FMS. This happens with any altitude below the original cruise level. 

In the video in references, I put FL370 in the AP while my CL was FL380. 
Check -> "new crz alt" message.

**this happens both when using managed or selected ALT mode**

### Expected behavior

The original cruise level should not change in the system to the ALT I set on the AP panel, unless in case the new ALT is above the original CL.

### Steps to reproduce

Insert a cruise level for a random test flight or add a FP if preferred, and set any ALT below that cruise level when airborne.

I have yet to see whether this occurs during the descent phase, but I do not think so. Will update in case it does. 

### References (optional)

https://user-images.githubusercontent.com/84073735/117956284-31715f80-b319-11eb-9c7c-9142e7c112c1.mp4

### Discord Username (optional)

Charley#9996

**Comment by Venorcis** [comment]
Can confirm, getting a lot of NEW CRZ ALT messages the past few days.
