### ISSUE TITLE
Forward pushback button EFB

### ISSUE THREAD

**Issue by evroon** [flybywiresim/a32nx#4801]
### Aircraft Version

Experimental

### Description

The EFB has three directional buttons for controlling the direction of pushback: straight backwards, left and right. However, there is no option for a forward direction, which the [PushbackHelper](https://github.com/metindikbas/msfs-pushback-helper-app) tool does have. It can be handy if you for example overshoot the taxiway centerline and want to correct the alignment of the aircraft easily.

### Discord Username (optional)

Erik Vroon#0182

**Comment by TLSY2** [comment]
That would be good, Pushback helper mod has that and also has speed, that would be good addition too. But what would a greater addition that the pushback goes where you set it to go from before the pushback.

**Comment by evroon** [comment]
> That would be good, Pushback helper mod has that and also has speed, that would be good addition too. 

Yes, but pushback helper uses some tricks (basically setting the speed of the aircraft itself instead of the tug) to do the (forward) pushback. 

> But what would a greater addition that the pushback goes where you set it to go from before the pushback.

Do you mean how PMDG allows you to set (in the FMC) the amount of distance the pushback tug goes straight after which it makes a turn of a chosen angle? I think that could be useful, but you will always have more complex situations where you want to manually and interactively handle the pushback, for which that does not work so well.

**Comment by evroon** [comment]
Maybe you mean how Better Pushback for X-Plane works: ![](https://assets-global.website-files.com/5b27a494dc3d312fe5c01da8/5c33c4a2c8f133d8a8ddc21f_8.jpg)

**Comment by TLSY2** [comment]
> Maybe you mean how Better Pushback for X-Plane works: ![](https://camo.githubusercontent.com/5f153f097bd55eaab9d97186a6ffbd004fdebe1588101e68bcb83e445c52c1b5/68747470733a2f2f6173736574732d676c6f62616c2e776562736974652d66696c65732e636f6d2f3562323761343934646333643331326665356330316461382f3563333363346132633866313333643861386464633231665f382e6a7067)

oh yeah that, but I dont expect it to be in the plane, but you know you are flybywire, you can make a mod like that?

**Comment by BHoggs** [comment]
> > Maybe you mean how Better Pushback for X-Plane works: ![](https://camo.githubusercontent.com/5f153f097bd55eaab9d97186a6ffbd004fdebe1588101e68bcb83e445c52c1b5/68747470733a2f2f6173736574732d676c6f62616c2e776562736974652d66696c65732e636f6d2f3562323761343934646333643331326665356330316461382f3563333363346132633866313333643861386464633231665f382e6a7067)
> 
> oh yeah that, but I dont expect it to be in the plane, but you know you are flybywire, you can make a mod like that?

This is now supported in the latest version of the "Toolbar Pushback" add-on. :) Still doesn't seem to support pushing forward in the planner, but best to raise that as an issue with that addon.

Q: With external Addons like this coming to maturity, is there really any point to having pushback buttons on the EFB? I find them pretty clunky to use anyway
