### ISSUE TITLE
Erratic behavior on approach

### ISSUE THREAD

**Issue by FlyingBerlin** [flybywiresim/a32nx#4804]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-13T14:28:05+00:00",
  "ref": "master",
  "sha": "e84e7b2219752dd2fdae0e0c237aa3822f09f1cc",
  "actor": "beheh",
  "event_name": "manual"
}
```

### Describe the bug

On any approach (ILS using AP,  Flying Manual) when selecting Flaps 2 or higher, the airplane pulls up without any reason and loses speed. Then, to gain speed and follow the flightpath, the autopilot tries to push down. However, with the nose pitching down 15°, no altitude will be lost. Same is happening with manual controls. 

### Expected behavior

Following the flight plan and being controllable. 

### Steps to reproduce

1. Fly Route EDDB-EDDP
2. ILS Approach 26L
3. Establish on ILS
4. Extend Flaps 2

**Comment by aguther** [comment]
Which flight model of MSFS are you using?

**Comment by FlyingBerlin** [comment]
> Which flight model of MSFS are you using?

Hi! What's meant by flight model and how can I find out which one is

**Comment by FlyingBerlin** [comment]
Indeed, the bug was operating the sidestick. Flight model has been switched somehow with the last update of MSFS. After resetting it, the plane autolanded very smooth. Thanks for the help!
