### ISSUE TITLE
Aileron Droop

### ISSUE THREAD

**Issue by AviationSpotter** [flybywiresim/a32nx#4805]
### Aircraft Version

Development

### Description

Newer 320's come with modified Flight Control Computers which can have the aileron droop when flaps are deployed or have the ailerons undroop during ground spoiler deployment. The ailerons can both droop (aileron lowers to increase lift) or undroop (aileron rises to reduce lift). Currently, the ailerons do not droop and I believe it should due to the fact that the "aileron droop" is becoming more common, modified on newer 320's, and also because it looks nice.

### References (optional)

![image](https://user-images.githubusercontent.com/72807945/118200195-9795d980-b422-11eb-989f-6ea3e3625a6e.png)

https://www.youtube.com/watch?v=CmHPzIs38sY
Timestamp: 
1:30 - First notch of flaps and aileron droop.
4:12 - Ground spoilers deployed alongside with aileron undroop.
5:28 - Spoilers retracted and end of aileron undroop.
5:39 - Video ends but ailerons were still drooped because of flaps. Aileron drooping will end when the flaps have been fully retracted.

### Additional info (optional)

Aileron drooping reacts with flaps and not slats!

### Discord Username (optional)

Aviation Spotter#9102

**Comment by aguther** [comment]
I'm aware that this feature is missing up to now. The main reason it's missing is because it's yet not fully clear how this can be implemented (it needs that flight control surfaces are controlled individually).

**Comment by hotshotp** [comment]
> I'm aware that this feature is missing up to now. The main reason it's missing is because it's yet not fully clear how this can be implemented (it needs that flight control surfaces are controlled individually).

If this helps, I'm pretty sure this feature is called aileron control law and the ailerons can be used as spoilers on landing for example.
