### ISSUE TITLE
Spoiler lever remains "Armed" after landing, even though spoilers are deployed

### ISSUE THREAD

**Issue by tush0701** [flybywiresim/a32nx#4808]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-13T21:11:12+00:00",
  "ref": "master",
  "sha": "5481edb118cb0c00437f1ebea1d0532eeecee3a5",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

Spoilers are deployed on landing the aircraft, but the spoiler lever remains in "ARMED" position, and the ECAM shows "SPOILERS ARMED" throughout.
(reverse thrust activates spoilers anyways)
I am currently using Thrustmaster TCA throttle WITHOUT the add-on flap and spoiler lever.

To close the spoilers, the toggle spoiler key has to be pressed twice.

### Expected behavior

Spoiler lever should go from "ARMED" to fully extended after landing

### Steps to reproduce

1. Arm spoilers on approach(any auto-brake 0-full)
2. Land the aircraft on runway
3. Use reverse thrust
4. Check outside view, spoilers are extended
4. ECAM still shows "SPLRS ARM"(reverse thrust activates spoilers anyways)

**Comment by andrejetcat** [comment]
Work like in real life :) Spoiler lever do not move in real life either after landing. it sill stay in "armed" position. the lever in the Boeing´s AC´s instead move. also ECAM massage shows armed, until you disarm the spoiler after landing roll.

**Comment by Benjozork** [comment]
Working as intended. Please provide references to IRL behaviour if you make an - [ ] issue about something being inscxur

**Comment by aguther** [comment]
I also just checked and after landing for me it was not necessary to use the toggle button twice. One key press was enough to bring it out of the ARM position resulting in the spoilers to retract.

**Comment by solarisfire** [comment]
If you have a spoiler axis, you can also move the axis up and down ever so slightly and it will disarm and retract them.

**Comment by tush0701** [comment]
Ok, will try that. Thanks a ton!
