### ISSUE TITLE
[BUG] SELF TEST 40 SEC still during start up and after switch electrical alimentation

### ISSUE THREAD

**Issue by L-1011** [flybywiresim/a32nx#481]
**Mod Version**
0.2.0

**Describe the bug**
after start APU and also Engines all monitors went to SELF TEST 40 SEC again and again.

**To Reproduce**
1. start up from C&D
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

**Comment by AdenFlorian** [comment]
should be fixed on master branch, please reopen with more detailed steps if you still see this happening
