### ISSUE TITLE
RNAV approach : unable to arm APP

### ISSUE THREAD

**Issue by alainzu** [flybywiresim/a32nx#4813]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-14T13:50:48+00:00",
  "ref": "master",
  "sha": "e9d23e7e24979c92e52a5131efe00a4e8db77ea9",
  "actor": "lukecologne",
  "event_name": "manual"
}
```

### Describe the bug

RNAV approach is not functioning correctly: impossible to arm APP and get an AP glideslope descent

### Expected behavior

When an RNAV approach is selected, ND should display RNV APP, before FDPoint, APP should be armed to initiate the descent according to the glideslope, during glideslope descent, PFD should display ALT/APP NAV 

### Steps to reproduce

1. select an RNAV approach
2. 20 nM from the airport, PFD displays the vert/dev square
3. ND should display RNV APP
4. Before the final descent point, it is impossible to arm APP
5. vert speed should be selected manually to follow the glide indicated by the vert/dev square

**Comment by aguther** [comment]
We know it and it's currently not implemented and it will come with custom LNAV/VNAV:
https://docs.flybywiresim.com/start/autopilot-fbw/

**Comment by fabrcro** [comment]
Hello, I hope can help

I tested with stable 0.6.1 and the today development 3086a27
Route with RNAV approach LIRF 16L - (SUVOK - OXERU - RF741)

With 0.6.1 APP works, goes lite, APP NAV appear but the square does not show up or appear/disappear. Seems follow G/S but after RF741 autopilot goes crasy turn 90' degree random

With the Development, APP does not work, nothing change remain NAV but G/S square appear and you can follow it manually disengaging AP

Cheers and compliments to all the developers for this fantastic MOD
