### ISSUE TITLE
erease FPL during climb[BUG]

### ISSUE THREAD

**Issue by L-1011** [flybywiresim/a32nx#482]
**Mod Version**
0.2.0

**Describe the bug**
durinf climb after reach a direct wpy the flightplan totally esere by itself 

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

**Comment by wpine215** [comment]
Please open a new issue, use correct grammar, and fill out the remainder of the template (at least reproduction steps, behavior, and possibly a screenshot).
