### ISSUE TITLE
Both Batteries 0.0 V

### ISSUE THREAD

**Issue by canert64** [flybywiresim/a32nx#4822]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-04-15T22:57:32+00:00",
  "ref": "v0.6.0",
  "sha": "981b2e4b0e89998d21a70fe26de54a2f10066f6e",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

I have tried 0.6.1 stable version, 0.6.0 stable version and development build versions many times in many different airfields. I've reinstalled over and over again. But the result does not change. Batteries always start at 0.0 volt. And this situation does not change, no matter what I do. I can run the engines with Ctrl+E and I can take off from the runway by plane. But batteries always at 0.0 volt.

There is 3 photo of the bug:

![aa](https://user-images.githubusercontent.com/84224306/118353971-6c6dd000-b571-11eb-9f9f-b816d459c035.jpg)
![bb](https://user-images.githubusercontent.com/84224306/118353988-8c9d8f00-b571-11eb-9d8f-3ed6e5b09c25.jpg)
![cc](https://user-images.githubusercontent.com/84224306/118354005-a343e600-b571-11eb-9816-ca785b81230c.jpg)

### Expected behavior

Please help me.

### Steps to reproduce

Batteries always start at 0.0 volt

**Comment by solarisfire** [comment]
This seems to happen to a lot of people...

I think the answer is uninstalling and making sure the flybywire-aircraft-a320-neo has been totally deleted from your community folder before installing.

Could really do with a "battery replacement" button somewhere 😅

**Comment by solarisfire** [comment]
Or could be a non-English character in your windows username?

https://github.com/flybywiresim/a32nx/issues/4778

**Comment by canert64** [comment]
> Or could be a non-English character in your windows username?
> 
> [# 4778](https://github.com/flybywiresim/a32nx/issues/4778)

My windows username "tiras", there is not a non-English character. Many times I completely removed flybywire-aircraft-a320-neo folder from Community folder and restart my computer, and reinstalled, but it didn't worked.

Thanks for your solution offers.

**Comment by odulkanberoglu** [comment]
Thank you, @solarisfire. The solution proposed in #4778 worked for me. Even though my Windows user name doesn't contain any non-English characters either, the locale for non-Unicode programs was set to Turkish (Turkey).

**Comment by Septus10** [comment]
Not sure if this will prove to be helpful for anyone else, but it seemed to happen to me when I loaded in with the Asobo version of the A320 (which was still set as my default aircraft since that's how the A32nx was loaded previously). The issue resolved itself when I explicitly selected the A320 from FlyByWire instead of the base game A320 in the aircraft selection menu .

**Comment by scoopscode** [comment]
I've heard Holland (@Benjozork) talk about this before on how it's something regarding changing your UTF to -8 or -16. I'm not entirely sure but hopefully I helped out here

**Comment by canert64** [comment]
Hi again, I solved it with @Benjozork 's advices at this subject: https://github.com/flybywiresim/a32nx/issues/4778

Thanks everybody.

**Comment by eu204** [comment]
I have same problem after last update of development version. I changed my setting UTF8 and even change my language to english, but problem still here

**Comment by OFC1983** [comment]
Same for me! Aircraft won't even start the displays anymore. Tried deleting the entire community folder and reinstall A32NX with no luck. Also changed to UTF8 support. I've been doing so many flights without any issues even the last couple of days and now out of the blue can't get the displays to start with Batteries at 0.0V. Also APU does not start and shows "fault" light. Even when the aircraft starts on the runways and the engines are running, no luck.

**Comment by fstokke** [comment]
Same problem here. Just updated to the latest dev version. No non-english characters in my username. I have tried to reinstall and setting UTF-8 as suggested in #4778, but still getting 0 volts.

**Comment by scoopscode** [comment]
For those of you unaware of the current situation, the development build is currently having issues and we are working on a resolution for this issue

**Comment by MisterChocker** [comment]
So has this been fixed?

**Comment by davidwalschots** [comment]
The person creating the issue stated it was fixed for them. Closing this one.

**Comment by blilnl123** [comment]
![image](https://user-images.githubusercontent.com/89497045/140607200-bff4f97e-20da-43a5-9740-24b79abf69c4.png)
why my screens are black :( can u guys help me

**Comment by derl30n** [comment]
open a new issue or seek help via github discussion or join our dc.

**Comment by SteveZane** [comment]
> ![image](https://user-images.githubusercontent.com/89497045/140607200-bff4f97e-20da-43a5-9740-24b79abf69c4.png)为什么我的屏幕是黑:(你们能帮我吗

  I cant figure it out too.
