### ISSUE TITLE
Changing LVAR:A32NX_BARO_BRIGHTNESS does not change SAI brightness 

### ISSUE THREAD

**Issue by frankkopp** [flybywiresim/a32nx#4831]
### Aircraft Version

Development

### Description

When changing the LVAR for the SAI the brightness does not change. It needs a push on plus or minus to update to the new brightness.

### References (optional)

Can provide video if issue is unclear.

### Additional info (optional)

Other lights/brightness seeting (e.g. PFD, ND, etc.) can be changed by simply changing the LVAR which directly updates the brightness of the respective instrument. 

### Discord Username (optional)

Cdr_Maverick#6475

**Comment by davidwalschots** [comment]
Other displays use the sim's potentiometer system to dim or brighten the display. The SAI does not use this system and instead handles it by setting some CSS opacity. When one presses the `+` or `-` a call to `updateBrightness` is executed which updates the SVG's CSS. Thus, simply changing `L:A32NX_BARO_BRIGHTNESS` is not enough.

The best solution to this problem would be using the same method as all other displays: a potentiometer.

**Comment by Benjozork** [comment]
> The best solution to this problem would be using the same method as all other displays: a potentiometer.

This is not done because this screen is shared with other small displays IIRC

**Comment by davidwalschots** [comment]
I went through the `A320_NEO_INTERIOR.xml` and found that the `ASOBO_GT_Component_Emissive_Gauge` for the SAI is commented out. @2hwk Benjozork told me you have more details on why this isn't possible at the moment. Would you mind briefly elaborating on it here?

**Comment by 2hwk** [comment]
> I went through the `A320_NEO_INTERIOR.xml` and found that the `ASOBO_GT_Component_Emissive_Gauge` for the SAI is commented out. @2hwk Benjozork told me you have more details on why this isn't possible at the moment. Would you mind briefly elaborating on it here?

This texture is shared with the clock, as well as the brake gauge, so its a workaround until the model can be updated to seperate it.

**Comment by 2hwk** [comment]
![image](https://user-images.githubusercontent.com/15316958/119211996-46ec4380-bae8-11eb-90dd-627941e1e0f0.png)

^ These are the displays that share the same emissive % right now, it's not possible just to affect the ISIS without changing the model.

Also some notes in case this is unblocked, this is not just a simple change, it will require some thought to fully resolve, as the brightness +/- push buttons are also used for navigation/UI on the ISIS i.e. to select bugs on the bugs page, unlike in other cases. XML is fun.
