### ISSUE TITLE
Cannot load SimBrief account in the MCDU

### ISSUE THREAD

**Issue by fabrcro** [flybywiresim/a32nx#4835]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-16T17:57:19+00:00",
  "ref": "master",
  "sha": "d2db4825d37827c956f3cb13341297cd12e3fc50",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

When I try to insert my SimBrief account or the Pilot ID in the MCDU it does not appear - Tablet with same account works

### Expected behavior

Inssrting SimBrief account should apper in the MCDU and allow flight plan load

### Steps to reproduce

1. MCDU MENU
2. OPTIONS
3. AOC
4. SIMBRIEF

### References (optional)

Video 

https://user-images.githubusercontent.com/51434695/118410244-c3b59280-b68e-11eb-8903-aa72ae9e6326.mp4

### Additional info (optional)

Same issue with the STABLE version

**Comment by Nitrox1122** [comment]
the fly tablet doesn't let me lode the SimBrief root to  MCDU form fly tablet 
ill put a video on when next on fs 2020

**Comment by scoopscode** [comment]
> the fly tablet doesn't let me lode the SimBrief root to  MCDU form fly tablet 
> 
> ill put a video on when next on fs 2020
> 
> 

The FlyPad won't load it into the MCDU as they aren't connected. However, I've never seen an issue like this before but maybe the developers know more than me.

**Comment by MisterChocker** [comment]
@fabrcro Does the issue still persist?

**Comment by fabrcro** [comment]
> 
> 
> @fabrcro Does the issue still persist?

Hello
yes, tested now with development 3086a27 and the issue is present: It is not accepted in the password field, remain empty... looks weird

**Comment by MisterChocker** [comment]
Well it works for me, I typed your username in the field and the received your user id: 
![Uploading image.png…]()

**Comment by fabrcro** [comment]
Happy for you 😊

Da: DerL30N ***@***.***>
Inviato: lunedì 24 maggio 2021 17:51
A: flybywiresim/a32nx ***@***.***>
Cc: fabrizio croce ***@***.***>; Mention ***@***.***>
Oggetto: Re: [flybywiresim/a32nx] Cannot load SimBrief account in the MCDU (#4835)


Well it works for me, I typed your username in the field and the received your user id:

**Comment by tracernz** [comment]
What happens if you go to https://www.simbrief.com/api/xml.fetcher.php?json=1&username=FABRIZIOCROCE in a web browser on the same machine you run MSFS?

**Comment by fabrcro** [comment]
> 
> 
> What happens if you go to https://www.simbrief.com/api/xml.fetcher.php?json=1&username=FABRIZIOCROCE in a web browser on the same machine you run MSFS?

Hello Michael
Thanks for your reply

I did and I suppose the API works, I get in the browser a list of flight plan parameters etc

![immagine](https://user-images.githubusercontent.com/51434695/119462585-2965e680-bd41-11eb-81c5-be4333312d71.png)

**Comment by tracernz** [comment]
> 
> Hello Michael
> Thanks for your reply
> 
> I did and I suppose the API works, I get in the browser a list of flight plan parameters etc
> 
Yes, that looks correct. Hmmm. I am running out of ideas.

**Comment by AdamNZ** [comment]
Have you tried editing/resaving the Simbrief flight plan - and then regenerating the OFP? I've had occasions where it looks like the flight plan got outdated - and wouldn't load in the MCDU. Generating a new OFP (even when in the sim) seems to kick things off.

**Comment by fabrcro** [comment]
> 
> 
> Have you tried editing/resaving the Simbrief flight plan - and then regenerating the OFP? I've had occasions where it looks like the flight plan got outdated - and wouldn't load in the MCDU. Generating a new OFP (even when in the sim) seems to kick things off.

Hello, yes just now. Created a OSPF new but again in MCDU when insert my simbried account the field remain empty. Seems it does no communicate outside (maybe...)

**Comment by BjoernHund** [comment]
Did you try it with your pilot id in the MCDU?

**Comment by fabrcro** [comment]
Yes... same result
________________________________

**Comment by LogRol** [comment]
Not sure about this but maybe your firewall/antivirus is blocking something?

**Comment by fabrcro** [comment]
> 
> 
> Not sure about this but maybe your firewall/antivirus is blocking something?

My friend you're an IT genious. I was thinking everything but this ;-) 

Actually was my firewall stripping the simbrief response because thought 'unsafe' - I put an exception and now it works !! 
![Immagine 2021-05-25 190539](https://user-images.githubusercontent.com/51434695/119540564-dbc39b00-bd8d-11eb-84ad-37243e3e8b4f.jpg)

Thanks again !

**Comment by fabrcro** [comment]
Suggestion: if your using an application firewall put an exception for *.simbrief.* or its IP 192.195.16.233 otherwise API XML response cult be cut. Cheers

**Comment by tracernz** [comment]
> > Not sure about this but maybe your firewall/antivirus is blocking something?
> 
> My friend you're an IT genious. I was thinking everything but this ;-)
> 
> Actually was my firewall stripping the simbrief response because thought 'unsafe' - I put an exception and now it works !!
> ![Immagine 2021-05-25 190539](https://user-images.githubusercontent.com/51434695/119540564-dbc39b00-bd8d-11eb-84ad-37243e3e8b4f.jpg)
> 
> Thanks again !

Ha! That’s what I was thinking about when testing with the web browser.

**Comment by WghzEB2219** [comment]
I have no options button in the mcdu?

**Comment by tracernz** [comment]
> 
> 
> I have no options button in the mcdu?

It's moved to the flyPad settings pages.
