### ISSUE TITLE
Settable Cockpit States

### ISSUE THREAD

**Issue by ajs117** [flybywiresim/a32nx#4840]
### Aircraft Version

Development

### Description

Store default cockpit setups (i.e. cold and dark, turn around etc) and have the ability to load these states in sim or set a default start up.

### Additional info (optional)

Aerosoft's A320 implementation
![Capture PNG 6f92b56a74c2b42818d343732c20fb8c](https://user-images.githubusercontent.com/34308197/118481933-f9e52780-b70b-11eb-9fcf-ee9430c08bf4.png)

**Comment by scoopscode** [comment]
Someone asked this on the Discord and may or may not be answered for In the Hangar 6.

**Comment by lefortludovic** [comment]
Hello, I'm trying to develop this one

**Comment by tracernz** [comment]
> Hello, I'm trying to develop this one

Probably best to discuss whether this should go in the EFB (my initial preference) or the MCDU before going too far.

**Comment by ajs117** [comment]
> > Hello, I'm trying to develop this one
> 
> Probably best to discuss whether this should go in the EFB (my initial preference) or the MCDU before going too far.

I second this, the EFB would be the best place IMO.

**Comment by Saschl** [comment]
In the end it's probably best to have the logic separated so that the implementation in either the MCDU or EFB is "just the UI". If possible of course as I'm not quite sure which access to what is needed exactly :D

**Comment by lefortludovic** [comment]
@tracernz when you say "my inital preference" which page are you talking about ?

**Comment by tracernz** [comment]
> @tracernz when you say "my inital preference" which page are you talking about ?

I mean I am inclined to prefer doing it on the EFB, but I can be swayed by a good argument for doing it on the MCDU.

**Comment by lefortludovic** [comment]
@tracernz I agree with you that the EFB seems to be a good place to have that option and keep the MCDU for "real" features
Settings page is already quiet full. Maybe a new tab called "aircraft" for everything touching aircraft configuration.

**Comment by ajs117** [comment]
IMO the FMC should be 100% as the real one with no sim settings or nothing in, then the EFB should handle anything sim related even IRS align speed.

**Comment by MisterChocker** [comment]
> IMO the FMC should be 100% as the real one with no sim settings or nothing in, then the EFB should handle anything sim related even IRS align speed.

Thats the plan

**Comment by bouveng** [comment]
One of my wishes that touches upon this feature, is not settable states as such, but a setting that allows the aircraft to remember its state between sessions.

When I return/load the aircraft, it should be as I left it in terms of configuration, knobs, lights, switches etc.

I think this can be easily done by either saving out a `current-state.flt` that is loaded instead of the normal one, if this setting i activated.

**Comment by frankkopp** [comment]
This is implemented in the new flyPad version: #6528
