### ISSUE TITLE
Logbook is always showing FBW title + first livery?

### ISSUE THREAD

**Issue by ErikNL80** [flybywiresim/a32nx#4853]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-18T21:03:24+00:00",
  "ref": "master",
  "sha": "84fd988f5badc09a413cdf280b27d727c0565e20",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

Recently I fount that the logbook does not correctly sets the plane title in the logbook. Normally it should take plane + livery, but in my case it always takes the first livery in the list (in my case British Airways). So even when I fly Transavia or KLM, it always shows British Airways...

![Logbook](https://user-images.githubusercontent.com/71258178/118786850-828dd000-b892-11eb-87e4-93fa39069629.png)

### Expected behavior

I would expect the logbook to log the plae with the correct livery, as it used to work.

### Steps to reproduce

1. Make sure you have a few custom liveries installed
2. Do a couple of flights in various liveries
3. Check the logbook

### References (optional)

N/A

### Additional info (optional)

N/A

**Comment by PX1181** [comment]
I have the same thing. Only for me it's always FBW Cathay Pacific, even though i only fly with KLM Orange Pride livery.
Started happening, for me, after i used the livery converter in the FBW Installer.
Don't know if that's actually the cause though.

**Comment by Kimbyeoungjang** [comment]
It caused by msfs not a fbw a32nx

**Comment by hotshotp** [comment]
Yep, this is a sim issue not a32nx
