### ISSUE TITLE
ATC does not indicate the altitude to which you must climb until you reach cruise when load from simbrief 

### ISSUE THREAD

**Issue by MaskaBrown** [flybywiresim/a32nx#4859]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-20T04:13:08+00:00",
  "ref": "master",
  "sha": "8f032505d193d5a85dfba4aba6fe31109638baa1",
  "actor": "MisterChocker",
  "event_name": "manual"
}
```

### Describe the bug

When I request the SimBrief flight plan from the MCDU it is loaded correctly, but when flying the ATC does not indicate the altitude to which you must climb until you reach cruise.

When the flight plan is created manually, ATC does indicate these intermediate altitudes.

### Expected behavior

I hope ATC indicate correct altitude to reach cruise

### Steps to reproduce

load from Simbrief plan
Call ATC

**Comment by scoopscode** [comment]
This is an MSFS issue/maybe not implemented as far as I know.

**Comment by hotshotp** [comment]
This is in no way related to the A32NX

**Comment by tracernz** [comment]
Open a bug on MSFS help platform requesting an API (/simvar) where we can set the ATC cruise altitude if you would like us to be able to implement it one day, because currently none exists.
