### ISSUE TITLE
Ecam Reset With Brightness Change

### ISSUE THREAD

**Issue by JacobKreindler** [flybywiresim/a32nx#486]
**Mod Version**

master

**Describe the bug**

When you turn the ECAM brightness all the way down and then turn it back up it is self test mode again.

**To Reproduce**

1. Start the aircraft
2. Turn either of the ECAM brightness's all the way down and back up
3.

**Expected behavior**

The ECAM should return to a normal state with the selected brightness

**Actual behavior**

The ECAM went into self test mode

**References**

[A320X Ecam Bug.zip](https://github.com/flybywiresim/a32nx/files/5184579/A320X.Ecam.Bug.zip)

**Additional context**

**Comment by NathanInnes** [comment]
This was discussed and it's the way it's supposed to be as this also happens on the real aircraft. Not a bug, it's a feature.

**Comment by JacobKreindler** [comment]
Oh, there were 3 people in the Discord who all decided that it was a bug so I guess we all learned something! =). Thanks!
