### ISSUE TITLE
keyboard entry option on MCDU

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#4862]
### Aircraft Version

Development

### Description

I don´t know if there is already a request or idea like this.

It would be a helpful and effective feature, if we can use the keyboard to use the MCDU. I don´t know if it was the PMDG´s @ FSX but there you could click on a point @ the FMS. After this your keyboard was "connected" with the keyboad on the MCDU/FMS. after clicking again, it was back to normal use.

Just an Idea and maybe interessting.

**Comment by charliemenem** [comment]
the are you are talking about of the MCDU/FMC is called the scratchpad, i think your idea is great, should be implemented, tired of clicking

**Comment by RvEijk1990** [comment]
I would like the virtual MCDU to be able to use my Tablet as MCDU 
Xplane used a app for that called X-panels 

there was also a app for use with PMDG not sure about the name anymore

**Comment by 2hwk** [comment]
I have a rudimentary solution for this so far but there are a few issues. Will post draft PR soon.

I can't figure out how to disable keybinds (for camera movement, instrument and switch adjustment shortcuts/keybinds, etc) when the MCDU is in focus, so you will probably need to unbind all controls on the alphanumeric cluster on your keyboard (or move them into modifier + key binds) for this to be actually useful. 

IMO this is especially bad for the inexperienced if you have the default keybinds set up (I can already see people happily using the MCDU with this feature with the default keybinds, hitting Y, going into slew mode and then being "stuck".)

Secondly from a UX perspective it would be good to have some kind of visual display that the MCDU is currently in focus (so you don't input things when you don't mean to) 

And finally it should be a toggleable option in the options menu.
