### ISSUE TITLE
EFB Settings view layout update

### ISSUE THREAD

**Issue by antonyisoardi** [flybywiresim/a32nx#4865]
### Aircraft Version

Development

### Description

Currently, the EFB settings view is running out of room for additional settings - as EFB evolves it's going to need the ability to customize/tailor it and I am already seeing additional inputs being required.

Suggesting the separation of EFB settings into views based on their current grouping, perhaps with a tabs-based approach exactly like what is being used in the Dispatch view.

### References (optional)

![image](https://user-images.githubusercontent.com/5309174/119213925-6d64ab80-baf5-11eb-8698-4a205368911b.png)

### Discord Username (optional)

antiso#8258

**Comment by MisterChocker** [comment]
Maybe something for #4026?

**Comment by antonyisoardi** [comment]
Yep agree. Though 4026 is about ready to go by the looks?

**Comment by antonyisoardi** [comment]
Being addressed in PR https://github.com/flybywiresim/a32nx/pull/5524
