### ISSUE TITLE
At Flaps full, flaps emerge out of spoilers. 

### ISSUE THREAD

**Issue by tush0701** [flybywiresim/a32nx#4866]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-21T16:57:18+00:00",
  "ref": "master",
  "sha": "d0de90baad9cda6c10442fa9cb3eb340de7008c0",
  "actor": "MisterChocker",
  "event_name": "manual"
}
```

### Describe the bug

When landing flaps full, if you see the window-view, the flaps seem to be tearing apart the closed spoilers, and seem to be visible over the spoilers. 
![Screenshot (1)_LI](https://user-images.githubusercontent.com/75409941/119214531-2ec6f500-bae5-11eb-8a0d-6cdc86ffb872.jpg)

### Expected behavior

Flaps should be completely extended back and under the spoilers as IRL Screenshot attached.
![maxresdefault](https://user-images.githubusercontent.com/75409941/119214504-017a4700-bae5-11eb-9726-43da2944c37d.jpg)

### Steps to reproduce

1. During landing, extend flaps to full
2. Change to window/wing view
3. Visible flaps above the spoilers

**Comment by tush0701** [comment]
![Screenshot (1)_LI](https://user-images.githubusercontent.com/75409941/119214531-2ec6f500-bae5-11eb-8a0d-6cdc86ffb872.jpg)
For some reason, screenshot of issue was not uploaded

**Comment by hotshotp** [comment]
in general the flaps animations are wrong and we are working on fixing it in the future

**Comment by tush0701** [comment]
@hotshotp That is great news. Thanks for making the A32N so much detailed and amazing!

**Comment by MisterChocker** [comment]
Using #4941 for tracking
