### ISSUE TITLE
Question: Does it support MacOS installation?

### ISSUE THREAD

**Issue by inglesuniversal** [flybywiresim/a32nx#487]
If so... are there any system or special setup requirements?

Thanks

**Comment by SeaRoll** [comment]
If you want to play MSFS on mac, you will have to setup a bootcamp (windows) installation

**Comment by Benjozork** [comment]
1. Please respect issue template

2. This game does not run on MacOS officially. Look at https://github.com/ValveSoftware/Proton/issues/4134.
