### ISSUE TITLE
CoherentUIGT.dll causing CTD

### ISSUE THREAD

**Issue by speedbird5** [flybywiresim/a32nx#4871]
### Aircraft Version

Experimental

### Build info

```json
"built": "2021-05-05T06:28:31+00:00",
  "ref": "experimental",
  "sha": "ff7f81fbff658ba8a69c77f6a16754ad1bffabea",
  "actor": "aguther",
  "event_name": "manual"
```

### Describe the bug

Consistently CTD after about 30-40 minutes due CoherentUIGT.dll.....

Faulting application name: FlightSimulator.exe, version: 0.0.0.0, time stamp: 0x6087d3ea
Faulting module name: CoherentUIGT.dll, version: 2.9.5.0, time stamp: 0x5fc6aa59
Exception code: 0xc0000005
Fault offset: 0x000000000013edb2
Faulting process id: 0xb70
Faulting application start time: 0x01d74fb15a01ee9e
Faulting application path: C:\Program Files\WindowsApps\Microsoft.FlightSimulator_1.15.10.0_x64__8wekyb3d8bbwe\FlightSimulator.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.FlightSimulator_1.15.10.0_x64__8wekyb3d8bbwe\CoherentUIGT.dll
Report Id: 42759d3b-c3f8-4c23-8a3d-aedcf8f75c86
Faulting package full name: Microsoft.FlightSimulator_1.15.10.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

### Expected behavior

No CTD

### Steps to reproduce

Fly A32NX experimental and after about 30 - 40 minutes get CTD with fault as above...

**Comment by aguther** [comment]
Please don't use experimental for now...as announced it's not updated anymore.

Beside that I do not have this issue and therefore unable to reproduce...

**Comment by speedbird5** [comment]
OK Thank you.  I did not know it is no longer updated.  Are you also using the development version and if so are there any CTD issues ?

**Comment by aguther** [comment]
Yes…I’m obviously using the developer version when developing ;-).

I do not have the issues with it. So please try and you will see. These things can also change with upcoming SU4…unfortunately kind of out of control for us. As I said, even if a piece of code in our Codebase is triggering the issue we have no possibility to trace it down. Analyzing a crash dump without the debug Information is hard and guess into the dark. This possibility is exclusive to MS/Asobo.

**Comment by speedbird5** [comment]
Thanks for the reply and greatly appreciate the wok you guys are doing !!

**Comment by Benjozork** [comment]
This cannot be debugged by us and we cannot find any info from it. This DLL should not crash in the first place, even with a bug in our code.
