### ISSUE TITLE
Random CTD with CoherentUIGT.dll error

### ISSUE THREAD

**Issue by forcebio** [flybywiresim/a32nx#4876]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-23T18:30:39+00:00",
  "ref": "master",
  "sha": "6d550c2f28d0d22806039b1115fcee013e0f13fc",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

I've got ramdoms CTD when flying withe the A32NX, sometimes after 30 minutes, 3 hours, and sometimes the flight is going fine.
I've tried all I can (nothing in Community), flying without 3rd party softwares...
I can't fix this problem...

### Expected behavior

No CTD

### Steps to reproduce

Impossible to give steps, CTD occurs randomly...

**Comment by hotshotp** [comment]
This cannot be debugged by us and we cannot find any info from it. This DLL should not crash in the first place, even with a bug in our code.

**Comment by jetstream2x4** [comment]
howdy and good morning ... I hope you guys are all fine ... 

Actually I encounter the same issue, but mostly during early descent. I wonder whether the issue is connected to BKC thread from early march: "CTD when loading an arrival"

Greets ...
