### ISSUE TITLE
Command/Switch Joystick association for engage FLC and Vertical Speed (once selected).

### ISSUE THREAD

**Issue by MarcoM1973** [flybywiresim/a32nx#4882]
### Aircraft Version

Experimental

### Description

Please Help!!
Joystick (X56 Hotas) Command for Engage FLC and Vertical Speed on A320XN.
I can set both command for increase or decrese them but I don't find a command to associate to a joystick switc (X56 Logitech) in order to activate or engage them once selectet. Is there a particular order swicht association to follow? At the moment the only way to activate them is with the mouse cursor, clicking on appropriate button on the heading AP panel.
Thank you so much....anyway....
Marco

**Comment by Benjozork** [comment]
There is no way for us to create custom bindings, unless you use software like SPAD.neXt or FSUIPC.

This is a limitation of MSFS.

Closing as out of scope.
