### ISSUE TITLE
Unable to climb above FL210 at 78t

### ISSUE THREAD

**Issue by mico975** [flybywiresim/a32nx#4887]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-24T01:02:09+00:00",
  "ref": "master",
  "sha": "3086a27044464e5d1b44c7eeb029df24c10f966a",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

MTOW takeoff, then requested FL320 as per opt/max cruise alt in MCDU and got stuck at FL210 with slow climb just above stall speed with 6 degrees AOA. I unfortunately have no idea what AOA is supposed to be related to stall with clean config on A20N.

Moments later I also got alpha floor at approximate FL180 and 300 knots indicated, which does not seem right :D

### Expected behavior

Climb to at least FL2x0 should be possible after MTOW takeoff.

### Steps to reproduce

1. MTOW takeoff - 79t.
2. Request climb to FL3x0 or whatever MCDU says is optimal.
3. Get stuck at lower FL and wonder :)

### References (optional)

![image](https://user-images.githubusercontent.com/78908672/119327904-c82c0d80-bc83-11eb-9455-ee94a9327eb7.png)
![image](https://user-images.githubusercontent.com/78908672/119327926-ce21ee80-bc83-11eb-8570-d972ee2de1ca.png)
![image](https://user-images.githubusercontent.com/78908672/119327938-d1b57580-bc83-11eb-88b5-221bf904c3e0.png)
![image](https://user-images.githubusercontent.com/78908672/119328670-a5e6bf80-bc84-11eb-993c-b575a9e99cf7.png)

![image](https://user-images.githubusercontent.com/78908672/119329308-5d7bd180-bc85-11eb-8339-50a0ac965e56.png)

### Additional info (optional)

This was working before but I have no idea for how long it does not work since this is my first MTOW departure in months.

**Comment by tracernz** [comment]
Make sure you're using modern flight model, not legacy, in MSFS Options > General > Flight Model.

**Comment by mico975** [comment]
Always using modern flight model in MSFS. After further investigation I concluded that this was probably caused by ice building up, which was not reported as a warning in cockpit. That's another problem with cokpit not refreshing, but it's a known bug. This bug can probably be closed (as long as nobody reproduces it).

**Comment by MisterChocker** [comment]
Closing as requested by op.
