### ISSUE TITLE
[BUG] with the last patch the instruments and lights of the height of the spedd etc. are no longer turned on

### ISSUE THREAD

**Issue by uguccione1** [flybywiresim/a32nx#490]
**Mod Version**

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

**Comment by CaptainStealthy** [comment]
Can we add a setting to make the displays bright by default?

**Comment by NathanInnes** [comment]
Once the EFB is made then I could look into making state saves

**Comment by AdenFlorian** [comment]
sounds like you didn't turn on the displays, if this sounds wrong, please provide screenshots and steps to reproduce
