### ISSUE TITLE
FPL Appears broken in Stable after SU4 Update

### ISSUE THREAD

**Issue by sfi-nate** [flybywiresim/a32nx#4904]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-05-05T23:03:06+00:00",
  "ref": "v0.6.1",
  "sha": "4a1cccc90ab3997109e394402ab9b41a80fbf325",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

FPL appears broken when using in-sim flight planning after SU4 update today. I am unable to see both the visual indicators / tracking on the MFD as well as the MCDU FPL button being non-functional.

### Expected behavior

FPL in MCDU should display FPL in its entirety with scrolling / dep / arr / etc

### Steps to reproduce

1. In-sim FPL planning always results in FPL malfunction.

### Discord Username (optional)

CptPajamas#6327

**Comment by sfi-nate** [comment]
Found the problem - it's not with FBW. Sorry for the false report!

**Comment by mreza1st** [comment]
I also have the same issue! The FPL doesn't work after the first leg! How did you fix it?

**Comment by sfi-nate** [comment]
> I also have the same issue! The FPL doesn't work after the first leg! How did you fix it?

I use Navigraph AIRAC cycle data and forgot to uninstall/reinstall after SU4 update.
