### ISSUE TITLE
Seat belt sign off when spawning on runway

### ISSUE THREAD

**Issue by St54Kevin** [flybywiresim/a32nx#4908]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-25T22:19:11+00:00",
  "ref": "merge",
  "sha": "1aeef0973accd7d8eaeeae52c18a49a6427c2884",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

When spawning on the runway, the seat belt sign is turned OFF.

### Expected behavior

Should be turned on

### Steps to reproduce

1. Spawn on a runway

**Comment by MisterChocker** [comment]
Well, same for no smoking/portable devises.

**Comment by St54Kevin** [comment]
> Well, same for no smoking/portable devises.

That one is on AUTO, which is correct. At least to my knowledge for most european airlines

**Comment by Saschl** [comment]
Mhh I’ll check this, I had this issue once when adapting the seatbelt signs but I got it fixed prior the update.. I hope it’s not the cause

**Comment by MisterChocker** [comment]
> > Well, same for no smoking/portable devises.
> 
> That one is on AUTO, which is correct. At least to my knowledge for most european airlines

A couple of days ago it was off (not on auto) when spawning on runway, no clue if has changed since.

**Comment by 2hwk** [comment]
Also wrong for spawning in cruise.

**Comment by derl30n** [comment]
Issue no longer present
