### ISSUE TITLE
Support for MSFSTrafficService

### ISSUE THREAD

**Issue by rick2909** [flybywiresim/a32nx#4915]
### Aircraft Version

Development

### Description

the working titlemode G3000 just updated and came with the support for [MSFSTrafficService](https://github.com/laurinius/MSFSTrafficService) this will enable the navigation display to show traffic on the TA/RA and all other modes.

### Discord Username (optional)

rick2909#1996

**Comment by Benjozork** [comment]
TCAS is already functional since Sim update 4

**Comment by tracernz** [comment]
And was functional for some traffic before that.
