### ISSUE TITLE
Aircraft unflyable after latest msfs patch 

### ISSUE THREAD

**Issue by lorenlan** [flybywiresim/a32nx#4916]
### Aircraft Version

Stable

### Build info

```json
{
  "name": "a32nx",
  "version": "0.6.1",
  "scripts": {
    "lint": "eslint --cache **/*.{js,mjs,jsx,ts,tsx}",
    "lint-fix": "npm run lint -- --fix",
    "prettier": "prettier --write **/*.json **/*.yml src/instruments/**/*.css",
    "build:instruments": "rollup -c src/instruments/rollup.config.js",
    "serve:efb": "cd src/instruments/src/EFB/ && rollup -wc ./rollup.development.config.js"
  },
```

### Describe the bug

When set flaps 2 or 4 there is a critical speed reduction with a fast v/s increase. All this after last msfs update 

### Expected behavior

Expect the normal work like ever 

### Steps to reproduce

1. Flight phase approach
2. Set flaps 2 or 4
3. Lose speed with critical v/s increase

**Comment by Saschl** [comment]
Are you by any chance on the legacy flightmodel in the msfs settings?

**Comment by lorenlan** [comment]
> Are you by any chance on the legacy flightmodel in the msfs settings?

I didn't try it.. Thanks

**Comment by MisterChocker** [comment]
@lorenlan Has your issue been resolved by switching to the modern flight model?

**Comment by lorenlan** [comment]
> @lorenlan Has your issue been resolved by switching to the modern flight model?

Now I can't do it.. I'll try tonight thanks

**Comment by carlossainz00** [comment]
the same issue and in modern flight model

**Comment by Emerson2021M** [comment]
Also the same problem here, with a modern flight model!

**Comment by wgpowell3** [comment]
FY- I just flew a precision ILS approach against a 20kt headwind and saw no issues with the stable build (0.6.1) running on the latest MSFS release (1.16.2.0) .  No sudden speed decrease and no dramatic change in vertical speed as flaps were deployed.

**Comment by carlossainz00** [comment]
> You provided the contents of package.json, which isn't in the insyall.
> 
> Please provide the right file, build_info.json

what does it mean that?

**Comment by lorenlan** [comment]
> @lorenlan Has your issue been resolved by switching to the modern flight model?

I do it but the issue isn't resolved.. Before patch I had it only with dev and experimental versions, while the stable worked fine. After patch, disaster

**Comment by lorenlan** [comment]
> You provided the contents of package.json, which isn't in the insyall.
> 
> Please provide the right file, build_info.json

I didn't find it sorry.. I'll search better

**Comment by Benjozork** [comment]
It's in the package inside community folder

**Comment by carlossainz00** [comment]
> > You provided the contents of package.json, which isn't in the insyall.
> > Please provide the right file, build_info.json
> 
> I didn't find it sorry.. I'll search better

u can search in the flight simulator the package.json, if u dont have try to search the build_info.json

**Comment by carlossainz00** [comment]
> It's in the package inside community folder

i dont have the package.json, with the build_info.json could work?

**Comment by AdamNZ** [comment]
Can the build info be made to display in the downloader/updater app? This would save so much confusion ...

**Comment by Benjozork** [comment]
Yes, build_info is the file we need.

**Comment by Benjozork** [comment]
@AdamNZ please open a feature request on the installer repository

**Comment by AdamNZ** [comment]
Thanks - will do! Feel free to delete that post (and this one!). :-)

**Comment by lorenlan** [comment]
Thanks for the support guys, I'll send the file soon

**Comment by lorenlan** [comment]
> You provided the contents of package.json, which isn't in the insyall.
> 
> Please provide the right file, build_info.json

{
  "built": "2021-05-05T23:03:06+00:00",
  "ref": "v0.6.1",
  "sha": "4a1cccc90ab3997109e394402ab9b41a80fbf325",
  "actor": "Benjozork",
  "event_name": "manual"
}

**Comment by Benjozork** [comment]
Thanks.

Can you try the development version ?

**Comment by lorenlan** [comment]
> Thanks.
> 
> Can you try the development version ?

I've tried all 3 version with same issue

**Comment by Sgcarter** [comment]
Hey Guys i have the Same issue. This Kind of Bug was in a Version maybe 3 Werks ago too. But today i Update via the Installer (Developer Version) and had massive upforce at depature and arrival. Was on ILS Glidepath and at Flaps 2 the Plane was reduce speed under 100 knots and pull the nose up to 7000 feet climb. There Was no way to stablize it anymore. I tried to put it back in no flaps but i go down like a dead bird.

**Comment by tracernz** [comment]
> 
> 
> > Thanks.
> > Can you try the development version ?
> 
> I've tried all 3 version with same issue

There was a fix added to dev 16 hours ago. Have you tried dev since then?
https://github.com/flybywiresim/a32nx/commit/4091db44bb202f571ea9d70416177b1101160b76

**Comment by lorenlan** [comment]
> > > Thanks.
> > > Can you try the development version ?
> > 
> > 
> > I've tried all 3 version with same issue
> 
> There was a fix added to dev 16 hours ago. Have you tried dev since then?
> [4091db4](https://github.com/flybywiresim/a32nx/commit/4091db44bb202f571ea9d70416177b1101160b76)

I've tried last dev version, with modern flight model in settings and there isn't issues thanks to all

**Comment by MisterChocker** [comment]
Closing since issue resolved
