### ISSUE TITLE
problème radar météo 

### ISSUE THREAD

**Issue by oxolalune** [flybywiresim/a32nx#4926]
### Aircraft Version

Development

### Build info

```json
"built": "2021-05-26T09:08:11+00:00",
  "ref": "master",
  "sha": "a4c7ec6882f1b36cb65435f0c4ceb0e423ed6a09",
  "actor": "tracernz",
  "event_name": "manual"
```

### Describe the bug

le problème plus de radar qui s'affiche météo de puis hier merci

### Expected behavior

le problème plus de radar qui s'affiche météo de puis hier merci

### Steps to reproduce

de puis la mise a jour j ai fait la mise a jour et plus météo
 radar

### Discord Username (optional)

oxolalune

**Comment by aguther** [comment]
Please follow template properly and use English as language. I don't get what is your problem. It seems your bug and the expected behavior are the same...so no issue ;-)

**Comment by Benjozork** [comment]
Bonjour,

Merci de fournir une capture d'écran.

**Comment by oxolalune** [comment]
![image](https://user-images.githubusercontent.com/84932052/119946259-b9e93480-bf96-11eb-99f4-2629d5c6e1a3.png)
