### ISSUE TITLE
Future compatibility with upcoming Cockpit Master MCDU

### ISSUE THREAD

**Issue by ErikNL80** [flybywiresim/a32nx#4942]
### Aircraft Version

Development

### Description

Cockpit Master has developed a CDU for the 737, and they are planning a A320 MCDU as well. It will have MSFS compatibility, but it would be great if it would also work with the FBW A320nx. I hope you can reach out to the dev so on launch we can use the MCDU with the A320nx.

### References (optional)

https://cockpit-master.com contains all info and links to YouTube, so you can see how it operates...

### Additional info (optional)

Allan can be reached via contact@cockpit-master.com

**Comment by Benjozork** [comment]
We will have an open protocol for this, it is up to the dev to implement compatibility for it.

**Comment by ErikNL80** [comment]
Thanks, already had a short conversation. They pointed out there are no plans to support the A320nx sine the MCDU is approx. 30% complete (their words). Pointed them to some PR's to show the WIP.

**Comment by Benjozork** [comment]
Our protocol sends the display information, and receives events.

The % of completion is not relevant in a technical sense.

**Comment by sidnov** [comment]
Pre-requisite framework for a web/app-based MCDU is available on the development version https://docs.flybywiresim.com/fbw-a32nx/feature-guides/web-mcdu/

Rest of the work on this needs to be looked into by the developer of the interface
