### ISSUE TITLE
Impossible to engage autopilot with dev version dated 28 may 2021

### ISSUE THREAD

**Issue by PatriceCesson** [flybywiresim/a32nx#4943]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-28T18:51:08+00:00",
  "ref": "master",
  "sha": "dbeb055429f12b7dc7e8a06def0ede2e720f6768",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

Sim version : SU4 from 26 may 2021

I have a FP generated by navigraph. FP is from LFRB (Brest) to LFRN (Rennes). Few waypoints, altitude 6000.
I choose the A32NX with livery AFR 80 years anniversary
I load the FP from the sim flight configuration screen.
Weather: real weather.
So I load the plane in a ready state on the runway 7R at LFRB
I check all flight parameters (Init page, Perf page, FCU, Spoilers, autobrake)
I start the flight with toga power
Once airborne I wait the indication to set LVR CLB on the FMA.
Once present, I set the throttle levers to CLB and normally I activate the Autopilot and then the FP is follwed as planned.

But here, impossible to activate the autopilot. I press the button on the FCU and a small noise but the autopilot does not engage. I tried several presses and nothing happens.
As a consequence, the plane deviates from the FP and I abort the flight.
I tried deleting the plane folder in the community folder and reloaded it via the installer. Same test and same behaviour.

### Expected behavior

The autopilot shall engage and after that the FP shall be followed.

### Steps to reproduce

See above.

### References (optional)

None.

### Additional info (optional)

I have the habit to make this flight regulalrly and had no problems before.
One time before I had some strange behaviour and then I deleted the plane folder and redownloaded it via the installer and things returned to normal behaviour.
I use only development version.
I will try with a preceding version of the A32NX.

### Discord Username (optional)

PatriceCesson

**Comment by Benjozork** [comment]
Are you entirely sure you are not in alpha protection (A. FLOOR) ?

**Comment by PatriceCesson** [comment]
so I restored this version dated 21 may 2021
{
  "built": "2021-05-21T16:57:18+00:00",
  "ref": "master",
  "sha": "d0de90baad9cda6c10442fa9cb3eb340de7008c0",
  "actor": "MisterChocker",
  "event_name": "manual"
}
And it works as expected. Autopilot activation is ok.

**Comment by PatriceCesson** [comment]
> Are you entirely sure you are not in alpha protection (A. FLOOR) ?

Never been in alpha protection mode (very simple take off ok in all cases).

**Comment by Benjozork** [comment]
Are you sure you use the modern flight model in MSFS settings ?

**Comment by PatriceCesson** [comment]
I never changed this setting.
And the fact that the restored version works ok confirms this.

**Comment by PatriceCesson** [comment]
Hi,
Why did you close this issue? Could you explain?
Thanks.

**Comment by Benjozork** [comment]
Probably a mistake.

> I never changed this setting.

Is it on modern or not ?

**Comment by forcebio** [comment]
Hi, with my flight yesterday night, I've got the same problem !
Departure at LFRS (Nantes), to LKKJ (Ajaccio).
A32NX too, AirFrance liverie (but not the 80's one).
But for me, I was able to engage correctly AP after FL140...
Before, wads possible for me to set AP at 5000ft if I wanted too...

**Comment by Benjozork** [comment]
@forcebio are you sure you weren't in alpha protection

**Comment by forcebio** [comment]
@Benjozork Sorry, but how to know if we are in alpha protection ? (I've got the vid of this flight)

**Comment by Benjozork** [comment]
A. FLOOR on the PFD.

Means you're stalling the aircraft and it's protecting itself.

**Comment by PatriceCesson** [comment]
> Probably a mistake.
> 
> > I never changed this setting.
> 
> Is it on modern or not ?

The flight model has always been on modern.

So, I redownloaded this version  (the same version at the problem origin) this saturday morning
{
  "built": "2021-05-28T18:51:08+00:00",
  "ref": "master",
  "sha": "dbeb055429f12b7dc7e8a06def0ede2e720f6768",
  "actor": "davidwalschots",
  "event_name": "manual"
}
I retried several times the same flight and the results are inconsistent: sometimes it is ok, sometimes this problem occurs.
I have activated the flight data recorder and here are some files you could investigate. Some are ok, others not (at least the 2 most recent ones are ok).

[work fdr files.zip](https://github.com/flybywiresim/a32nx/files/6564313/work.fdr.files.zip)

**Comment by Benjozork** [comment]
cc @aguther

**Comment by forcebio** [comment]
After watching the video, no A.FLOOR on the PFD.
But, it seems thats the AP disconnect after I retract flaps, and go to the limit of stalling... Perhaps it's the A.FLOOR protection, but no displaying it by the way !

**Comment by aguther** [comment]
There is a difference between being in high alpha protection law and alpha floor. If getting slowly into this protection is likely that AP gets disconnected before alpha floor is activated.

AP is disconnected on alpha protection + 1°.

According to screenshot you’re clearly in alpha protection. Works as intended.

**Comment by forcebio** [comment]
Ok :)
So, no A.FLOOR on the PFD is normal ?

**Comment by aguther** [comment]
It depends, when you get into that protection and the alpha is getting high enough you will get A.FLOOR. What I tried to say is that you can be in the high AoA protection without getting alpha floor.

This is a quite nice video about it (from a Level-D sim):
https://youtu.be/xerF-n9SJ_4

As you can see, the AP disconnects at a certain point and no A.FLOOR being activated. It gets activated when the pilots pulls on the stick which then commands alpha max instead of alpha protection which is obviously higher than alpha floor. alpha floor is a alpha between alpha protection and alpha max which is as the others depending on configuration.

**Comment by forcebio** [comment]
Ok, thanks for the complete answer !
All fine, now I know ;)

**Comment by PatriceCesson** [comment]
Hi,
I followed your discussion and I think I am facing the same problem of alpha floor, despite not indicated in the FMA.
In fact the plane climbs too fast and at a certain point it may or may not enter the alpha protection and in this case the AP may disconnects. Exiting the alpha protectio allows the AP to be activated again.
So, we can say this issue is a "non-issue" and can be closed with no problem.
Thanks for your explanations.

**Comment by frogmonkey2** [comment]
> Are you entirely sure you are not in alpha protection (A. FLOOR) ?

so what is A. Floor and where do you find it to turn off?... mine is showing that TIA

**Comment by tracernz** [comment]
> 
> 
> > Are you entirely sure you are not in alpha protection (A. FLOOR) ?
> 
> so what is A. Floor and where do you find it to turn off?... mine is showing that TIA

Pitch your nose down to gain speed and get below protection angle of attack, you will then be in TOGA.LK, with thrust locked at TOGA. Disengage autothrottle, and re-engage to go back to normal.

**Comment by frogmonkey2** [comment]
> > Are you entirely sure you are not in alpha protection (A. FLOOR) ?
> 
> so what is A. Floor and where do you find it to turn off?... mine is showing that TIA

I now see the above link... it's been driving me bananas however when I push autopilot there's no way I'm at 'stall' speed... the result is basically it GOES to a stall... I have to take over attempt to get it all back... by that time I usually bail...

**Comment by frogmonkey2** [comment]
> > > Are you entirely sure you are not in alpha protection (A. FLOOR) ?
> > 
> > 
> > so what is A. Floor and where do you find it to turn off?... mine is showing that TIA
> 
> A.FLOOR is alpha floor protection, which stops the aircraft from stalling when angle of attack is getting too high (too slow + too much pitch up). Pitch your nose down to gain speed and get below protection angle of attack, you will then be in TOGA.LK, with thrust locked at TOGA. Disengage autothrottle, and re-engage to go back to normal.

THX... all new... II had to take care of some biz, and quite frankly all the changes a bit back coupled with Asebo was a tad much...
