### ISSUE TITLE
TCAS fault when starting from runway

### ISSUE THREAD

**Issue by oldmanbishop** [flybywiresim/a32nx#4945]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2021-05-05T06:28:31+00:00",
  "ref": "experimental",
  "sha": "ff7f81fbff658ba8a69c77f6a16754ad1bffabea",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

When starting directly from the runway, TCAS throws a fault and isn't usable. The plane flies normally otherwise. ECAM message is "NAV TCAS FAULT". TCAS works as expected when starting up from cold/dark at a gate.

### Expected behavior

No faults and a fully setup aircraft when loading to runway

### Steps to reproduce

1) select an airport an runway on the world map
2) select fly
3) allow plane to load

**Comment by Benjozork** [comment]
Self duplicated by #4946
