### ISSUE TITLE
Tiller Steering 

### ISSUE THREAD

**Issue by Swaluver88** [flybywiresim/a32nx#4947]
### Aircraft Version

Stable

### Description

Current stable version, i have FSUIPC 7 running straight input, no axis's assigned in sim (profile made just for FBW320). have the tiller steering set and the rudder set. they should be separate as i have the Axis's separated with different hardware. however, thats not the case the tiller steering is rudder steering. it would be nice to have separate steering if possible ) 

### References (optional)

PMDG planes tiller steering option than the normal rudder option 

### Discord Username (optional)

alex k#8228

**Comment by tracernz** [comment]
MSFS doesn't even have a separate binding, so tiller steering cannot be done without payware at the moment.

**Comment by Swaluver88** [comment]
thats cool to know. realistic.... cant even support separate bindings...yet. thanks for the info hopefully it will in the near future
