### ISSUE TITLE
Both AP should be able to engage after G/S captured

### ISSUE THREAD

**Issue by yzgyyang** [flybywiresim/a32nx#4949]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-05-05T23:03:06+00:00",
  "ref": "v0.6.1",
  "sha": "4a1cccc90ab3997109e394402ab9b41a80fbf325",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

I cannot engage both AP1 and AP2 after LOC and G/S captured.

### Expected behavior

Both AP should be able to engage after G/S captured.

### Steps to reproduce

1. Establish an ILS approach
2. Try to engage both Autopilots

### Discord Username (optional)

yzgyyang#3140

**Comment by tracernz** [comment]
Fixed in dev.
