### ISSUE TITLE
QNH Indicator Does not Blink when Reaching Transition Altitude

### ISSUE THREAD

**Issue by ManyPandas** [flybywiresim/a32nx#4950]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-29T11:34:13+00:00",
  "ref": "master",
  "sha": "c4918cd39934c8e575cf0762c9bd41e46ccad823",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

The title pretty much explains it. Even with the implementation of the feature with #4892, it doesn't appear to be working.

Something that may be loosely related is that THR LVR annunciation does not appear to blink when it should. If I recall correctly, it should blink when passing the acceleration altitude.

### Expected behavior

I expect the QNH Indicator to flash when I reach the transition altitude, as previously implemented by #4892

### Steps to reproduce

1. Start Cold and Dark
2. Execute standard MCDU procedures (making sure especially to fill in a Transition Alt.)
3. Take off and climb as normal.
4. Reach transition altitude, and indicator does not flash.

### References (optional)

https://user-images.githubusercontent.com/21292503/120082103-16c81600-c08f-11eb-8a27-ae281334922e.mp4

### Discord Username (optional)

ManyPandas#0839

**Comment by aguther** [comment]
Please enable menu animations in the MSFS options and restart your sim. Reopen the issue if it does not fix it.
