### ISSUE TITLE
TCAS ND Display Error - stops displaying air traffic, exception prints to console

### ISSUE THREAD

**Issue by 2hwk** [flybywiresim/a32nx#4952]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-29T03:58:33+00:00",
  "ref": "HEAD",
  "sha": "823a86ff0d87b39db4108ba0b4fe9d29d7b2aa94",
  "actor": "2hwk",
  "event_name": "manual"
}
```

### Describe the bug

When around any airport with Live Traffic on, sometimes TCAS ND Display will bug out and stop displaying. A typerror - object is undefined exception is printed to js console.

### Expected behavior

TCAS should function normally, showing surrounding air traffic

### Steps to reproduce

Launch either at a gate or in mid-air at busy airport and wait for a plane to spawn in (May take some time)
Occasionally this will bug out the display

### References (optional)

![image](https://user-images.githubusercontent.com/15316958/120093460-0a09f780-c14d-11eb-84d1-31733600f1ed.png)
![image](https://cdn.discordapp.com/attachments/747571985831297145/848435070255759360/unknown.png)
![image](https://user-images.githubusercontent.com/15316958/120093541-94525b80-c14d-11eb-95d9-647ee52ce5fa.png)

### Additional info (optional)

Noticed it while sitting at YBAS while testing some other PRs. This is a fairly remote airport with little traffic, so I switched to various other busier locations and confirmed its a recurring and reproducible issue.

### Discord Username (optional)

2Cas#1022

**Comment by ManyPandas** [comment]
I can confirm that this issue exists. I haven't seen an exception in the console, but I have noticed a strange lack of TCAS blips while flying on VATSIM, especially when I can see aircraft within my vicinity with the VFR map.

**Comment by Amorisia** [comment]
I confirm too. As soon as I get the ND stop displaying (ranges 10 and 20), I put TCAS to STBY and it works again. Then, I can put TCAS on again and it can works, so this seems to be random ?

**Comment by 2hwk** [comment]
![image](https://user-images.githubusercontent.com/15316958/121137582-61a11500-c869-11eb-9f81-a81437e9cfff.png)

Coherent GT Debugger Stack Trace for this error
