### ISSUE TITLE
SETWA : Single Engine Taxi Without APU

### ISSUE THREAD

**Issue by tush0701** [flybywiresim/a32nx#4957]
### Aircraft Version

Development

### Description

Request you to add SETWA, or Single engine Taxi without APU, which does not require APU to be on while taxi on single engine, and other one can be turned on later before take off.

You can keep it optional, with a switch probably on the tablet.

### References (optional)

IRL, as per Airbus:
The Single Engine Taxi Without APU solution “SETWA” is designed specifically to allow our A320 family customers to taxi on a single engine without the APU (Auxiliary Power Unit).

SETWA is both economical and ecological. There are significant fuel savings per year per aircraft and SETWA helps the airline save an estimated 50,000 USD per aircraft, per year.
The SETWA solution consists of a wiring modification in the pylon and around the engine fire handle. It can be embodied in an overnight shift. The solution allows compliance with JAR/FAR 25.1195. Thus, 2 fire extinguishing bottles remain available when using one engine instead of two in line with regulatory needs.

https://services.airbus.com/en/flight-operations/system-upgrades/fuel-efficiency/single-engine-taxi-without-apu.html

### Additional info (optional)

Benefits of SETWA: Significant reduction in fuel burn
Cost reduction in the taxiing phase at both take off and landing

Benefits in SIM: Fuel consumption less
Realism enhanced

### Discord Username (optional)

tbone0793

**Comment by tracernz** [comment]
What exactly is missing for this? Cross-bleed start is the only thing I know of, and that's covered by https://github.com/flybywiresim/a32nx/issues/820.

**Comment by tush0701** [comment]
Hi, yes it is the same thing. Sorry could not find it myself. Thanks for the reference.

**Comment by beheh** [comment]
If that's the only requirement, I'm closing this then. Duplicates #820
