### ISSUE TITLE
A32NX not loading in Sim Update 4

### ISSUE THREAD

**Issue by sebastianbk** [flybywiresim/a32nx#4959]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-05-05T23:03:06+00:00",
  "ref": "v0.6.1",
  "sha": "4a1cccc90ab3997109e394402ab9b41a80fbf325",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

When I load up a flight with the A320neo in MSFS (version 1.16.2.0), I get the default A320neo that ships with MSFS rather than the A320nx mod. I have tried uninstalling all other mods (both from my Community as well as my purchases via the in-game store). However, I can't get A32NX to load.

I've used the installer to install the mod and verified that I do indeed have the latest stable build installed.

![image](https://user-images.githubusercontent.com/660576/120119068-f3d45980-c195-11eb-9191-5043c3a64d2d.png)

### Expected behavior

Expect to see the A32NX mod, including the EFB and the other features of the mod. However, I just see the standard layout.

![image](https://i.imgur.com/InuM8tT.jpg)

### Steps to reproduce

Load up a flight from anywhere, selecting the A320neo. As you can see in the screenshot below, I have no other mods installed.

![image](https://user-images.githubusercontent.com/660576/120118993-9b9d5780-c195-11eb-9cbf-6396288da364.png)

**Comment by Benjozork** [comment]
Have you tried the development version

**Comment by aguther** [comment]
Did you select the FlyByWire A320 or the default one? Those are two planes...

**Comment by sebastianbk** [comment]
I just tried installing A32NX via the marketplace in MSFS. Now it works. 🤔

I think I will reinstall my MSFS. It seems corrupted.

**Comment by LentuloBatiato** [comment]
> I just tried installing A32NX via the marketplace in MSFS. Now it works. 🤔
> 
> I think I will reinstall my MSFS. It seems corrupted.

Don't need to do dat, the A320NX is an airplane apart the default A320, if you installed the A320NX via Marketplace, no it's all right. ;)

**Comment by Benjozork** [comment]
Stable v0.6.1 and the marketplace edition are at the moment identical.
