### ISSUE TITLE
instant atsu request fail

### ISSUE THREAD

**Issue by Samueleonard** [flybywiresim/a32nx#4961]
### Aircraft Version

Development

### Description

when requesting something through the atsu (for example weather or atis) it can be annoying to wait 10 seconds or so to get a failure message back.
it would be better if it would instantly reply if there was a failure to retrieve, so we didnt have to wait

of course, keep the delay if there was a successful response

**Comment by Annolago** [comment]
Think ATIS only work if you are connected to VATSIM. Never had an issue with weather..

**Comment by Samueleonard** [comment]
> Think ATIS only work if you are connected to VATSIM. Never had an issue with weather..

No, it just fetched through the vatsim API, the plane has no way of knowing if you are connected to vatsim

**Comment by sidnov** [comment]
Uplink delay is now simulated with options in the EFB
