### ISSUE TITLE
F-Plan and ILS problem

### ISSUE THREAD

**Issue by MStallen** [flybywiresim/a32nx#4962]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-28T11:09:14+00:00",
  "ref": "master",
  "sha": "aea711f8547eed2669c774481200330670eb3085",
  "actor": "tracernz",
  "event_name": "manual"
}
```

### Describe the bug

Selecting approach and ILS (during flight) on FMCU gives two problems:

1. ILS frequency is not filed in automatically (tried several airports for instance ILS 04R LFMN)
2. A/C won't follow F-PLAN anymore

### Expected behavior

1. LS/Freq automatically filled in on RADNAV page FMCU when selecting ILS approach
2. A/C follows adjusted F-Plan

### Steps to reproduce

1. Take-off from LFKJ with SID to Lonsu
2. During flight add ILS04 with Lonsu STAR
3.  (aircraft will fly to Lonsu but than continu to flight straight forward)

### Additional info (optional)

Was working before on DEV-mode (don't know which version)

**Comment by MStallen** [comment]
Also tried:

1. AP off and on
2. DIR to Lonsu
3. Selecting another runway

**Comment by sidnov** [comment]
You can check out the response from tracernz in the discussion (#4918). There may be improvements to this sometime soon.

**Comment by sidnov** [comment]
Unable to reproduce with the latest development version. Please reopen if needed with fresh details of the issue
