### ISSUE TITLE
Any modification on MCDU (Direct or adding STAR) will cancel IFR planning on Native ATC System

### ISSUE THREAD

**Issue by mickaelfardini** [flybywiresim/a32nx#4971]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-29T11:34:13+00:00",
  "ref": "master",
  "sha": "c4918cd39934c8e575cf0762c9bd41e46ccad823",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

After filling a plan through MCDU, and then request an IFR to native ATC system, things going great, until you're making a DIRECT ou modifying/adding WP/STAR in any kind, the IFR is cancelled.
We need to re-request an IFR to the ATC.

### Expected behavior

The IFR continue without having to request it again.

### Steps to reproduce

1. Fill a plan, a short one or what ever.
2. Ask for IFR in the native ATC window
3. Take off and fly or taxi.
4. Either you can : 
- Direct to your next WP, which do not change the route in anyway, or even if it did.
- Modify STAR (SID also if still on ground)
5. Re-ask for IFR every time you're modifying your route.

### Additional info (optional)

I believe this start to happens after a few commit to the 0.6.1 in dev, probably due to the recent MFS Update.

### Discord Username (optional)

Marshall#7876

**Comment by sidnov** [comment]
With the new FMS systems, we move further away from the buggy default ATC systems. The intention is to only provide basic flightplan-syncing through appropriate options in the EFB settings. Feel free to re-open the issue with fresh details of the issue if it occurs on the latest development version.
