### ISSUE TITLE
Keyboard braking not effective anymore with newest dev version.

### ISSUE THREAD

**Issue by A320PHX** [flybywiresim/a32nx#4972]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-31T21:33:13+00:00",
  "ref": "master",
  "sha": "d7556f04a219d83101afd74665f2a96781cd5a04",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

I can no longer stop the plane using multiple taps of the num pad delete "." key. This is only after upgrading to the newest dev version with the new braking system. I can no longer brake the plane with any precision as multiple taps of the num pad don't register unless I hold it down, which then causes the plane to slam to stop.

### Expected behavior

I expect to be able to stop the plane smoothly using multiple taps of the num pad del button as in previous dev versions. 

### Steps to reproduce

Plane is moving.
Hit num pad del to slow plane.

Nothing happens unless you hold down num pad del and then the plane comes to a complete and sudden stop.

### Discord Username (optional)

AzFlyGuy

**Comment by crocket63** [comment]
Hi there! The behaviour changed in last dev indeed, so you might have to use brakes differently.

Did you try a first long press until you reach the brake force you want, then repeated key presses to maintain it?

Doing this I have no issue to brake using keyboard on my side.

**Comment by A320PHX** [comment]
That's what I have tried, but it didn't work out well. Before I could easily stop it where I wanted to precisely. Now I overshoot and then slam the brakes on. 

I am sure it could be possible to make a version for people without rudder/brake pedals. Otherwise, I will have to pack this plane up. :( Such a shame as it flies beautifully now.

**Comment by sidnov** [comment]
It does not look like a bug and more like a personal preference. On the real Airbus, pilots don't multiple tap or multiple press the brake pedals. It is one long press to bring the speed to the desired number and continuing taxi/rollout. The number of applications is directly proportional to brake wear too. The new brake and hydraulic system tries to simulate exactly this.

**Comment by A320PHX** [comment]
Completely get it, just saying as it is a sim, some people might want some things to be more casual sim friendly. I love the systems side of things and have been happily carrying on with my xbox controller, but now I cannot taxi the plane any longer. 

Maybe, make two branches is all I am saying. Just keep some things easier for people that don't have the peripherals.

**Comment by crocket63** [comment]
My main concern is I really have no issue at all to brake and having pedals slower than before feels easier to "modulate". I can make it faster to test if any improvement, but not sure it would help.  
Are you really sure you are not just used to do it the old way? I mean maybe it's easier for me just because I didn't use keyboard before :p

**Comment by frankkopp** [comment]
I just tested it. I always use a button on my flight stick and the new "pedal speed" is really good. You push the button and brake and you release the button when brake force is strong enough. Much better than before in my opinion. As @crocket63  said better to modulate. 
In any case the title of this issue is not correct - brakes are very effective. Just their handling has changed a bit and this might be a matter of taste and getting used to.

**Comment by crocket63** [comment]
Thanks for the feedback!  
I quickly tested with faster pedal response and it's a nightmare to modulate then.  I would even make those slower if you let me change this :D

**Comment by A320PHX** [comment]
I guess I am having a hard time understanding how you want me to modulate a button. I have tried to hold down the num pad del. button until the desired braking level is reached, but then when I press it repeatedly, the brakes just continue to decrease and then I overshoot where I was wanted to brake. If I hold down the brakes, if I release at say 6 knots, it comes to a complete hault. 

I would love to continue flying this plane as it gets better, but am unable to taxi at all. This means I cannot use your wonderful mod any more :(.  Would anyone happen to have a back up of the dev version, right before  the hydraulics update? I will just have to settle for that as I could at least get the plane around on the ground.

**Comment by crocket63** [comment]
Tried again and really have no issue.
Smooth and spot on https://www.youtube.com/watch?v=wQtqYNe1xm4

**Comment by hotshotp** [comment]
> Completely get it, just saying as it is a sim, some people might want some things to be more casual sim friendly..

If you want casual, the default is the option then, we try to simulate everything as the real airbus. It's not difficult to get used to the new braking, just takes a small bit of practice. We are not making two branches for this either.
