### ISSUE TITLE
High N1 Causes Higher Fuel Burn

### ISSUE THREAD

**Issue by Cspielman63** [flybywiresim/a32nx#4978]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-31T21:33:13+00:00",
  "ref": "master",
  "sha": "d7556f04a219d83101afd74665f2a96781cd5a04",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

On my flights the N1 sits around 84.0% to holf Mach .78. This is higher than the data I'm seeing it should be. This causes a higher fuel burn and less fuel than should be left upon landing.

### Expected behavior

Fuel burn and N1 to represent actual values needed.

### Steps to reproduce

1, Start a flight
2. Check fuel consumption and N1 at cruise altitude

**Comment by JRascagneres** [comment]
When you see this can you verify the outside temperature? 
There's been a bug recently in live weather that caused the outside temperature to be higher than it should be resulting in lower engine performance, requiring more fuel and higher N1

**Comment by Cspielman63** [comment]
I will verify on my next flight with it

**Comment by donstim** [comment]
N1 value for cruise at M0.78 also varies with weight and altitude, so please provide that information as well. For example, at 66T, FL390, ISA+10 C, N1 should be right at 84%.

**Comment by CoffeePanda0** [comment]
For me here:
TAT = -26c
SAT = -56c
N1 = 84%

M0.78
FL370, TOW was 70T

Fuel flow seems quite high though, 2580kg an hour which seems normal, but for some reason more fuel is being burnt than indicated? Did a 1hr30 flight yesterday and burnt over 6 tonnes of fuel - never used to be this high in the fbw mod until recently.

43 Mins into current flight, sitting at cruise, and total fuel used is 4.8Tonnes. Isn't that way too high for 43 mins? 5 tonnes an hour seems a lot higher than what i've seen

**Comment by donstim** [comment]
I don't know what to tell you. I just tried to reproduce your results and couldn't do it. Took off at 70 T and climbed to FL370. Same temp as you at FL 370. N1, fuel flow, and fuel used all look as expected compared to FCOM values.

![Screenshot (926)](https://user-images.githubusercontent.com/70166617/120916048-0c43e880-c65c-11eb-9150-157e158b3b56.png)
![Screenshot (927)](https://user-images.githubusercontent.com/70166617/120916053-0f3ed900-c65c-11eb-9f86-c52dc0de5415.png)

**Comment by Cspielman63** [comment]
Im now burning 3120 LBS/HR, at 84.8% N1, TAT -14C, SAT -43C, ISA 13.9, at 133700 LBS in cruise

**Comment by donstim** [comment]
And what are you expecting it to be?  Are you making sure that you are in a stable cruise (N1 not fluctuating much) before recording the numbers?  Here is what I get when I try to reproduce your scenario:
![Screenshot (931)](https://user-images.githubusercontent.com/70166617/121259919-85faf280-c865-11eb-86d5-5b2c429fac84.png)
![Screenshot (930)](https://user-images.githubusercontent.com/70166617/121259930-885d4c80-c865-11eb-8439-fe64d287baf0.png)
(Ignore fuel used - I started pretty close to your condition so I didn't burn any fuel getting there. Everything else looks nominal.

It would be helpful if you were to provide a video or at least some screenshots so we can see what is going on. It obviously is not happening when I try to reproduce it, so there is something different going on. Do you have any liveries or anything else in your community folder?

**Comment by MisterChocker** [comment]
Closing since no response from op.
