### ISSUE TITLE
PBE not working with current build

### ISSUE THREAD

**Issue by DrSt333v3** [flybywiresim/a32nx#4984]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-31T21:33:13+00:00",
  "ref": "master",
  "sha": "d7556f04a219d83101afd74665f2a96781cd5a04",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

When using the PBE addon when calling the pushback I get a message from the addon asking me to make sure the parking brake is set, setting the brake has no effect.
After talking to devs on discord we think that the new braking system is not being recognized by the PBE addon.
PBE could update to look for the variable you are now using, also maybe you could still change the "state" of the parking brake variable when the custom FBW brake is set to maintain compatibility with mods and addons that would look for this information.

### Expected behavior

PBE addon should recognize when the parking brake is set.

### Steps to reproduce

Load flight with A32nx dev version, load PBE, call for pushback from addon.

### Additional info (optional)

Reply from dev on Discord.
Saschl — Today at 4:21 PM
We recently implemented our own braking system and the default parking brake state is probably not updated anymore. Probably PBE needs an update for that

### Discord Username (optional)

DrSteeeve #6703

**Comment by crocket63** [comment]
Yup, I confirm we do not output BRAKE PARKING POSITION any more as we just use standard brake outputs for both brakes and parking. Checking our new variable of parking brake lever position would do the trick for sure.  Generating again parking position to solve this once and for all could lead to brake issues so it would need quite some testing to make sure it doesn't mess anything.

**Comment by crocket63** [comment]
Alternatively and to not be A32NX specific, why don't they just check parking position OR brake position standard simvars?  Should work for every plane, and achieves what we want : make sure no brakes are in use.

**Comment by Benjozork** [comment]
Please make a specific request, we don't provide support third party software.

We encourage the author to contact us for any questions.
