### ISSUE TITLE
[REQUEST] Let us enter Altitude Restrictions

### ISSUE THREAD

**Issue by Zyonix007** [flybywiresim/a32nx#499]
**Is your feature request related to a problem? Please describe.**
On the real airbus you can enter speed and alt restrictions in the MCDU

**Describe the feature you'd like to see implemented**
 enter restrictions in mcdu 
(see link)

**References**

http://www.a320dp.com/A320_DP/nav-flight-management/sys-14.8.13.html

**Additional context**

**Comment by Sierramike71** [comment]
additionally some restriction provided are wrong and have to be manually corrected. I experienced this on a STAR at LFMN: 12000A instead of 6000A

**Comment by SeaRoll** [comment]
I believe this is a bug from asobo's side

**Comment by lousybyte** [comment]
I've seen some code that might help with this, but this page is missing completely atm, so the UI needs to be built first, might take this over the weekend. Still unsure if anyone is still working on a CDU overhaul or not.

**Comment by lousybyte** [comment]
Found a way to set alt constraints, but the API and documentation is really limited, cannot change the modifiers for the inserted altitude at this time, meaning if it's `+5000` in the flight plan, you can change the value but the `+` will remain, meaning it will still interpret it as  `+<your value>`. 
For fixed altitudes this doesn't matter, but if the restriction has above/below constraints there's no known way of changing the prefix requirements at this time.
Will submit a PR with the current possible implementation soon, at least will help with most of the cases.

**Comment by wpine215** [comment]
@lousybyte Any update?

**Comment by lousybyte** [comment]
@wpine215 Not from what I noticed, maybe #1695 would help with this.
