### ISSUE TITLE
Strange Brake Responsiveness

### ISSUE THREAD

**Issue by kgaviation** [flybywiresim/a32nx#4995]
### Aircraft Version

Development

### Build info

```json
Development build 7231eee v0.6.1
```

### Describe the bug

After installing the latest development version of the mod, I flew a flight from KOAK (Oakland) to PHLI (Lihue). During my taxi before departure, I noticed strange behavior and responsiveness from the brakes than before. The brakes have a delayed response to my joystick control input. I use a Logitech Attack 3 joystick with a trigger button for my brakes. The brakes don't respond when I press the trigger. I have to hold it down for a few seconds for the brakes to respond and when they respond, it is delayed and results in a large, sudden drop in my taxi speed. Also, if I am holding the brakes for taxi and I add thrust, the aircraft has a delayed starting movement. It takes a few seconds from when I release the brakes with my joystick to when the aircraft actually begins moving and the brakes are released.

### Expected behavior

The brakes should respond to my joystick control/trigger inputs. If I am trying to "tap the brakes" to control my taxi speed, the brakes should respond accordingly and without a few second delay.

### Steps to reproduce

1. Plan a flight from Oakland (KOAK) to Lihue (PHLI)
2. Begin cold and dark from the gate 
3. Begin taxiing to the runway for takeoff and try to adjust your taxi speed with the brakes as you normally would for turns and for holding before takeoff. Also, use the brakes for landing as normal.

### Additional info (optional)

Yes, my brakes were working normally before the latest sim update and before re-installing the latest developer version of the mod. My joystick control trigger/brake responsiveness was immediate.

**Comment by crocket63** [comment]
Due to the new hydraulic brakes implementation, you have to change the way you modulate brakes using keyboard or button.
Basically you should keep pressed until reaching the brake force you want, then regularily tap the button to keep that brake force.
https://www.youtube.com/watch?v=wQtqYNe1xm4
