### ISSUE TITLE
Automatic ECAM page switching shouldn't illuminate associated ECAM button

### ISSUE THREAD

**Issue by wpine215** [flybywiresim/a32nx#50]
In the real aircraft, any ECAM page displayed/changed by the system itself (such as Door on door open, APU on APU master on, ENG on ignition, etc.) doesn't light up the associated ECAM button. If another ECAM button, or the same ECAM button, is pressed, then it illuminates as normal, but if it is pressed again the light goes out and the ECAM returns to the default, computer-dictated ECAM page.

**Comment by noga-aviator** [comment]
this is a technical limitation of the baseEICAS system, i don't know if i can do much about it

**Comment by lukecologne** [comment]
Mostly fixed with #603, but still wrong when engine mode selector is turned, so I think this issue should stay open until that is fixed

**Comment by lukecologne** [comment]
Fixed in #705

**Comment by paul92ilm** [comment]
Tested on ground and in flight, LGTM
#705 fixed this issue
I think this issue can be closed

**Comment by lukecologne** [comment]
Yep, forgot to close this in the mentioned PR. Closing as fixed.
