### ISSUE TITLE
Fuel Flow no longer ramping up during engine start sequence + EGT bump

### ISSUE THREAD

**Issue by TheSquirtingPantin** [flybywiresim/a32nx#5001]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-28T15:17:02+00:00",
  "ref": "merge",
  "sha": "e6e2c8e772f6f835c8b9b251236e1df1b9b464f2",
  "actor": "tracernz",
  "event_name": "manual"
}
```

### Describe the bug

The fix provided by PR #4658 is no longer working during engine start.
During the start sequence, fuel flow is no longer ramping up. The fuel flow is only displayed post start-up sequence (as AVAIL disappears) alongside with a huge EGT bump (412° to 530° in a split second). 

### Expected behavior

Expectations are: 
- Fuel ramping up during start sequence (as per PR #4658, around 40%N1 for start point due to FADEC model)
- EGT slowly rising as fuel is being introduced by FADEC.  

### Steps to reproduce

1. Perform an ENG 1 or ENG 2 start with APU. 
2. Check behavior of fuel flow on ECAM display
3. Check EGT bump

### References (optional)

PR #4658 is the main reference

### Additional info (optional)

Discovered post update to 1.16. It was working properly before. 

### Discord Username (optional)

Remi#8871

**Comment by Cryptic56** [comment]
Same issue. The fuel flow does ramp up if I shut down the aircraft and start it again, the fuel flow starts at ~8%N1.

**Comment by fsendventd** [comment]
Also experiencing this.

**Comment by Taz5150** [comment]
Please test/ check with https://github.com/flybywiresim/a32nx/pull/5081.
