### ISSUE TITLE
APU exhaust effect contact point

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#5007]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-04T17:58:47+00:00",
  "ref": "master",
  "sha": "361e1c56e70029eaca2b89c02fba45ed0ef01656",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

APU exhaust-effect "starts" way to far behind APU exhaust. maybe Contact-point is wrong.
I try to make a screenshot, I hope you can see it. 

![APU effect](https://user-images.githubusercontent.com/72918017/120848545-37074180-c575-11eb-98b0-5a5a30476520.jpg)

### Expected behavior

effect should start closer behind exhaust from APU

### Steps to reproduce

1.start APU
2.look at the effect

**Comment by davidwalschots** [comment]
@wpine215

**Comment by wpine215** [comment]
I'm currently using the closest contact point to the APU exhaust port, the tail navigation light contact point used for the APU sound. Unfortunately, the exhaust effect itself has a gap from the contact point to where it begins, which is what you're seeing.

The easiest solution would be to add a custom contact point a bit further into the fuselage (and slightly up) to be accurate. Possibly something @tyler58546 can look at when he has free time?
