### ISSUE TITLE
Aircraft flickers on the EFB map

### ISSUE THREAD

**Issue by antonyisoardi** [flybywiresim/a32nx#5010]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-05-05T23:03:06+00:00",
  "ref": "v0.6.1",
  "sha": "4a1cccc90ab3997109e394402ab9b41a80fbf325",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

The aircraft marker flickers on EFB map.

### Expected behavior

The aircraft marker displays the current position and should remain solid.

### Steps to reproduce

1. Start new flick
2. Start EFB
3. Observe the aircraft marker on the map on the EFB dashboard

### Additional info (optional)

It appears as though the flickering coincides with the refresh of data on the aircraft position and the flickering could be a result of data changes/rerender on the aircraft marker.

### Discord Username (optional)

antiso

**Comment by MisterChocker** [comment]
Reproduced on master

**Comment by ErickSharp** [comment]
We are temporarily getting rid of this map on flypados 3 for this reason and will come back to it later to improve it and we may reinclude it at that time.

**Comment by 2hwk** [comment]
Stale as of flyPad OS 3 merge. Closing.
