### ISSUE TITLE
EFB Map units not updating when display units changed

### ISSUE THREAD

**Issue by antonyisoardi** [flybywiresim/a32nx#5011]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-05-05T23:03:06+00:00",
  "ref": "v0.6.1",
  "sha": "4a1cccc90ab3997109e394402ab9b41a80fbf325",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

When the measurement units are changed on the EFB, the unit distance indicator in the lower left corner of the map doesn't change with it.

Subsequently, when using the track tool, it will only display the unit value in the measures on each point of what was on the display measurement at the time the waypoint was added.

The same is also true for the website map (https://www.flybywiresim.com/map) as it also shares the same component.

### Expected behavior

The unit distance indicator should display the same unit of measurement that is toggled to in the right hand side control panel.

All waypoint data should also display its measurement units in the same unit of measurement that is toggled to in the right hand side control panel.

### Steps to reproduce

1. Start a new flight
2. Turn on the EFB
3. View dashboard
4. Observe the behavior of the unit distance indicator when clicking on the measurement unit button in the control panel on the lower right of the map
5. Observe the behavior when using the tracking tool to track while changing the unit of measurement.

### References (optional)

**Sim**
![image](https://user-images.githubusercontent.com/5309174/120883089-d0823200-c60d-11eb-8d7e-b60dd6ba61c2.png)

**Website**
![image](https://user-images.githubusercontent.com/5309174/120883082-c5c79d00-c60d-11eb-8728-17d8f2b84641.png)

### Discord Username (optional)

antiso

**Comment by BlueberryKing** [comment]
Not that this helps you, but this is a bug in the library we're using (https://www.npmjs.com/package/@datenpate/leaflet.polylinemeasure). Notice how this also happens on their demo: https://ppete2.github.io/Leaflet.PolylineMeasure/demo1.html.

The bug only occurs when you change units while you're still drawing a path, i.e before you've clicked on the last point.
