### ISSUE TITLE
EFB Map showing incorrect theme

### ISSUE THREAD

**Issue by antonyisoardi** [flybywiresim/a32nx#5015]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-05T18:07:53+00:00",
  "ref": "HEAD",
  "sha": "53b18c2f5a2c65254b5e4edaadf8ba64e6d1ff34",
  "actor": "Andreas Guther <andreas@guther.family>",
  "event_name": "manual"
}
```

### Describe the bug

The EFB Map is displaying in the light theme

### Expected behavior

The EFB Map should be displayed in the dark theme displayed

### Steps to reproduce

1. Start flight
2. Turn on EFB
3. Observe map

### References (optional)

![Uploading image.png…]()

### Discord Username (optional)

antiso

**Comment by Benjozork** [comment]
You say "development" but your `build_info` is from stable v0.6.1?

**Comment by antonyisoardi** [comment]
> You say "development" but your `build_info` is from stable v0.6.1?

Pulled from wrong copy. Fixed now.
