### ISSUE TITLE
A/THR incorrectly being armed / Unexpected FMA

### ISSUE THREAD

**Issue by Illuminati270** [flybywiresim/a32nx#5016]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-04T17:58:47+00:00",
  "ref": "master",
  "sha": "361e1c56e70029eaca2b89c02fba45ed0ef01656",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

When FDs are selected OFF on takeoff, the A/THR is armed, and the unexpected FMAs "MAN FLX 60" / "MAN TOGA" come up.

### Expected behavior

When on ground, FMA is supposed to stay clean if FDs are off. Regardless to what thrust detent is selected.

In-flight, the FMAs "MAN MCT" or "MAN TOGA" should come up.

### Steps to reproduce

1. Turn FDs off
2. Push thrust levers to FLX/MCT or TOGA
3. FMA displaying "MAN FLX XX" or "MAN TOGA" will come up (they shouldn't)
4. A/THR will also become armed (it shouldn't).

### Discord Username (optional)

Illuminati

**Comment by aguther** [comment]
According to my document this is not true. Please provide evidence by reference documentation.

**Comment by aguther** [comment]
Feel free to reopen this issue when you have a reference.

**Comment by aguther** [comment]
![image](https://user-images.githubusercontent.com/6629914/120906574-f08c1280-c65a-11eb-87ad-3cbf85f0840d.png)

**Comment by Illuminati270** [comment]
> Beside the information in the FCOM, as reference the ToLISS A319:
> ![image](https://user-images.githubusercontent.com/6629914/120906584-01d51f00-c65b-11eb-864a-bef41ca0293b.png)
> ![image](https://user-images.githubusercontent.com/6629914/120906619-42cd3380-c65b-11eb-8ad3-3ce5925a0608.png)

Hi there Aguther,

I thought you guys were willing to develop a very high-end airliner for FS2020, the best one ever made. For that, count on me. I've taken off multiple times the A320 without the flight directors **(reallife)**, and I can assure you that in real life it won't arm.

Other than that, if you have real "document", you'll find that out at: FCOM-PRO-NOR-SRP-01-30 PXX/XX (depends on revision you are at) "NO FLIGHT DIRECTOR TAKEOFF" where it states the following:

If a takeoff is initiated without FDs, the system responds as follow:
‐ There are no FD bars.
**‐ There is no A/THR arming.**
‐ There is no guidance available.
‐ The target speed on the PFD is that selected on the FCU or is defaulted to 100 kt.
**‐ Setting the thrust levers to the CL detent does not activate A/THR.**
**Note: Do not engage the autothrust prior to selecting a target speed on the FCU.**


Showing a Toliss model won't help at all. I'm talking about the real thing.

![fcom1](https://user-images.githubusercontent.com/85410344/120906865-52d11d00-c633-11eb-9bd3-c3cdb694735d.jpg)

**Comment by Illuminati270** [comment]
So, if you could be gentle and reopen the issue (which is, *indeed* an issue), that would be very nice!

**Comment by Benjozork** [comment]
The passive agressive tone will end right now.

**Comment by MisterChocker** [comment]
> Showing a Toliss model won't help at all. I'm talking about the real thing.

You need to read closely...

> Beside the information in the FCOM, as reference the ToLISS A319:

**Comment by aguther** [comment]
Ok, I have some questions about it.

- When I read the text in regards to the `THR RED ALT` I assume the A/THR does not automatically activate when thrust levers are put to CLB detent. Is that correct?
- does `LVR CLB` flash when `THR RED ALT` is reached (it's only mentioned when FD *fail* after take-off)?
- How can FD bars disappear when FD fail that have been not showing before (due to deactivation)?
- Why does it say "autothrust remains armed" when flight directors fail?
- Does it use FLX thrust limit when setup and thrust levers are put into FLX detent?
- How does the system react when FDs are not activated on THR RED ALT?
  - when you put thrust levers to CLB and then above them, will it show `MAN THR` and `MAN MCT` etc?
  - when you put thrust levers to CLB and then above will it then arm the A/THR?

**Comment by Illuminati270** [comment]
> Ok, I have some questions about it.
> 
> * When I read the text in regards to the `THR RED ALT` I assume the A/THR does not automatically activate when thrust levers are put to CLB detent. Is that correct?

**Correct**. When you takeoff FDs ON, the A/THR will come in blue once you set the Thrust Levers to FLX/TOGA. It will become white once you bring back the thrust levers to CLB detent, where the FMA will change from MAN FLX / MAN TOGA to "THR CLB".

> * does `LVR CLB` flash when `THR RED ALT` is reached (it's only mentioned when FD _fail_ after take-off)?

**Yes**. That's another issue that I was about to report: The "LVR CLB" is flashing below the THR RED altitude. Basically:

- At or above THR RED: "LVR CLB" flashes
- Accel ALT: SRS becomes now CLB (OR VS+XXXX if you don't have a valid mode).

If you are taking off WITHOUT the FDs, there will be NO "LVR CLB". (A common error from pilots when taking off FDs OFF: forgetting to bring back the thrust levers to CLB, thus, the PM forgets to turn on the packs when the takeoff was performed as "Packs off")

> * How can FD bars disappear when FD fail that have been not showing before (due to deactivation)?

When the FMA is showing: 1 FD 2 or 1 FD 1, or 2 FD 2, at any given time, if the FDs fail, there will be a red "flag" on the PFD writen **FD** (can't paint it red here, not sure how). The bars will, therefor,e immediately disappear (AF 447 video might help to understand what I'm saying).

If you had the FDs off and they failed, nothing will happen, unless you press one of the FDs push-buttons, and all you'll get is the same red flag.

> * Why does it say "autothrust remains armed" when flight directors fail?

That's a very specific situation when you start rolling (At least thrust levers on FLX/TOGA) and the FDs fail. You'll still have "MAN TOGA" / "MAN FLX" on the FMA, A/THR will still be blue, but once you reach THR RED, instead of "THR CLB" you'll only have "SPEED" mode available, which might surprise you to have nose pointed upwards while the thrust eventually gets reduced due to reaching F-Speed! That's the "warning" they are giving.

> * Does it use FLX thrust limit when setup and thrust levers are put into FLX detent?

**Yes!** That's why it's very important to check and callout "Thrust set". If there's a FLX value selected of course. If not, there'll be a ECAM "LEVERS..........TOGA", and if you still don't do it, the engines will spool up on their own to TOGA N1.

> * How does the system react when FDs are not activated on THR RED ALT?

The system will remain quiet! Until you turn anything on.


>   * when you put thrust levers to CLB and then above: will it show `MAN THR` and `MAN MCT` etc?
>   * when you put thrust levers to CLB and then above: will it then arm the A/THR?

These last two questions, I believe there's a good difference among the aircrafts.

There's a optional called "Automatic FD Bar engagement at Go-Around". If the airplane has this feature, I believe you'll see:

MAN MCT / MAN TOGA, FDs will come on (SRS/GA TRK), and the A/THR will arm (blue) until you get back to CL detent.

If the aircraft does not have such feature installed, I **believe** there will be also no FMA nor A/THR arming. (Never pushed MCT/TOGA above THR RED when FDs OFF in real life to assure you).

**Comment by Illuminati270** [comment]
[https://www.youtube.com/watch?v=DpZzwcDyaDY](url)

**Comment by aguther** [comment]
Ok, I filed a PR that introduces support for this procedure. I just checked, the `LVR CLB` should also be fixed by it, it seems the conditions for it have been correct in the sense that it automatically covered now this situation as well (without a need to change it). Feel free to try the PR out, you find a link to download the build here:
https://github.com/flybywiresim/a32nx/actions/runs/911810695

**Comment by Illuminati270** [comment]
> Ok, I filed a PR that introduces support for this procedure. I just checked, the `LVR CLB` should also be fixed by it, it seems the conditions for it have been correct in the sense that it automatically covered now this situation as well (without a need to change it). Feel free to try the PR out, you find a link to download the build here:
> https://github.com/flybywiresim/a32nx/actions/runs/911810695

I tested it. Congratulations. Well done. Feels like the real aircraft right now!!

I couldn't find a way to feedback/evaluate though.

The video I linked is the AF447'S FDR to help on the question about the FD flag.

**Comment by aguther** [comment]
Thank you for testing, the feedback as comment was enough for me.

Approving PRs can only be done by maintainers.
