### ISSUE TITLE
"THR LK" incorrectly happening when disconnecting the A/THR through instinctive buttons.

### ISSUE THREAD

**Issue by Illuminati270** [flybywiresim/a32nx#5020]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-05T12:23:20+00:00",
  "ref": "master",
  "sha": "48b478d5d7764b80102a5ba39d91b0aa30133251",
  "actor": "hiaaryan",
  "event_name": "manual"
}
```

### Describe the bug

When you disconnect the A/THR through the instinctive button it becomes a "THR LK", which is correct to happen only when the A/THR fails (Itself or due to another system-related) or it gets disconnected by the push-button on the FCU.

### Expected behavior

When you disconnect the A/THR through the instinctive push-buttons (those red ones on the thrust levers) the thrust is supposed to match the thrust lever positions immediately, from wherever it is.

### Steps to reproduce

1. Aircraft flying; A/THR ON.
2. Thrust levers at CL detent.
3. Select a very low speed. Engines will roll back.
4. Press the red buttons on the Thrust levers.
5. Thrust should immediately run willing to match the available CLB N1. But they don't, engines will stay at Thrust Lock instead.

### References (optional)

FCOM

**Comment by aguther** [comment]
Again, please provide documentation about it.

**Comment by aguther** [comment]
Found it in the meantime. If you don’t want to post the info directly, please at least provide the chapter and headline where this information can be found. This saves a lot of time.

**Comment by Illuminati270** [comment]
Ok, sorry aguther. I thought the explanation was clear enough to program/patch/tweak the model! It comes out of my own observations! =)

Glad you found it!
