### ISSUE TITLE
A list of possible improvements [FMGS INIT A/PERF] [ACP/RMP] [VENT]

### ISSUE THREAD

**Issue by Illuminati270** [flybywiresim/a32nx#5026]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-06T15:12:39+00:00",
  "ref": "master",
  "sha": "ff9425ae19d607662e1e8adb6732dd0509aacb9f",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

[FMGS]

The TROPO field (INIT A) doesn't accept values it should.

The Approach page layout doesn't look like that.

[ACP/RMP]

SEL light lights up green

Whenever I press the microphone button, it presses back the volume knob corresponding to that microphone.

[VENT]

Nothing happens when BLOWER/EXTRACT are pressed

### Expected behavior

[FMGS]

On Honeywell systems, whenever you enter any value from 0 - 60000 on TROPO field (INIT A), it will accept as is.

600 = 600ft.

[ACP/RMP]

SEL light is amber, and it lights up the whole "key".

Selecting a microphone shouldn't have any influence on the volume knobs.

[VENT]

Whenever EXTRACT is pressed, we'll get a slightly reduced air sound.

When BLOWER is pressed, there will be peace in the cockpit, almost no air sound.

### Steps to reproduce

[FMGS]

Many values aren't accepted displaying a "NOT ALLOWED" on the scratchpad.

[ACP/RMP]

1. Pop the VHF2 volume knob.
2. Press the VHF2 microphone.
3. The volume knob will push itself back in, that doesn't happen.

[VENT]

1. Press either BLOWER / EXTRACT
2. Not following proper logic; No sound change.

### References (optional)

[ACP/RMP]

![vhf](https://user-images.githubusercontent.com/85410344/120936144-b4999180-c6dc-11eb-8756-35f9db30b19b.jpeg)

[FMGS]

tracerZ posted a quote at Discord FMS section stating the following:

"Any tropopause altitude up to 60,000 ft is able to be entered. The tropopause altitude cannot be entered as a flight level. Feet must be entered (i.e., do not enter 380 for FL380, the FMS interprets as 380 ft)"

For the correct approach perf layout page, refer to:

DSC-22_20-30-20-25

![perf](https://user-images.githubusercontent.com/85410344/120936652-47d3c680-c6df-11eb-9f0e-65c1fc7d59aa.jpg)

[VENT]

DSC-21-30-60 and further info at DSC-21-30-20 for the ground/flight threshold temperatures

![blower](https://user-images.githubusercontent.com/85410344/120936844-77cf9980-c6e0-11eb-8a76-29bc8b7f032e.jpg)

### Discord Username (optional)

Illuminati

**Comment by Benjozork** [comment]
Please keep in mind for the future that GitHub issues must be for exactly one problem / suggestion.

**Comment by Illuminati270** [comment]
> Please keep in mind for the future that GitHub issues must be for exactly one problem / suggestion.

ok, wilco.

**Comment by tshomas** [comment]
Regarding the APPR Page: The page is currently accurate to the Honeywell New Revision 2 software that the FMGC software is being modelled to, commonly seen on Honeywell NEO aircraft at the moment and also newer Honeywell CEO. 

![D1C485B1-4568-436F-B965-9C7461CE6C85](https://user-images.githubusercontent.com/74841560/120937856-d1978a00-c707-11eb-90db-4c660028df1c.jpeg)
NEO FCOM DSC-22_20-50-10-25

**Comment by Illuminati270** [comment]
> Regarding the APPR Page: The page is currently accurate to the Honeywell New Revision 2 software that the FMGC software is being modelled to, commonly seen on Honeywell NEO aircraft at the moment and also newer Honeywell CEO.
> 
> ![D1C485B1-4568-436F-B965-9C7461CE6C85](https://user-images.githubusercontent.com/74841560/120937856-d1978a00-c707-11eb-90db-4c660028df1c.jpeg)
> NEO FCOM DSC-22_20-50-10-25

Oh! Cool, I wasn't aware that the new layout was like this.

**Comment by davidwalschots** [comment]
Benjozork indicated future issues should be one suggestion/bug and allowed this issue to remain open. Not having split issues leads to a readability problem. One needs to scan to more information which might not be relevant for what a developer is looking for. It also becomes impossible to refer to this issue from a PR to automatically close it when the PR gets merged.

For these reasons, I'll close this issue now and request that you recreate individual issues for these items. Thank you 😃.

**Comment by Illuminati270** [comment]
> Benjozork indicated future issues should be one suggestion/bug and allowed this issue to remain open. Not having split issues leads to a readability problem. One needs to scan to more information which might not be relevant for what a developer is looking for. It also becomes impossible to refer to this issue from a PR to automatically close it when the PR gets merged.
> 
> For these reasons, I'll close this issue now and request that you recreate individual issues for these items. Thank you 😃.

It's my second day actively using GitHub. Give me a few more hours to sort everything out! I think I managed to "split" them!  🥇 :)

:-) 


Ok, I give up. Can't place a simple emoji correctly...
