### ISSUE TITLE
DELTA ISA <*| Optional feature

### ISSUE THREAD

**Issue by Illuminati270** [flybywiresim/a32nx#5029]
### Aircraft Version

Development

### Description

When the CM1 altimeter knob is pulled (STD MODE) and there is a valid SAT value, the ISA DEV is shown like this:

![DSC-31-20x](https://user-images.githubusercontent.com/85410344/120937626-ee6e9600-c6e4-11eb-8bd6-1fec1dcbeb1c.jpg)

### References (optional)

Refer to DSC-31-20 for further info:

![DSC-31-20](https://user-images.githubusercontent.com/85410344/120937639-faf2ee80-c6e4-11eb-8dba-17d42ad1377a.jpg)

### Discord Username (optional)

Illuminati

**Comment by Benjozork** [comment]
EIS2 S13-2 ref

`Delta ISA = SAT + (ALTstd * 2 / 1000) - 15`
