### ISSUE TITLE
[POWERPLANT] ENG START

### ISSUE THREAD

**Issue by Illuminati270** [flybywiresim/a32nx#5030]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-06T15:12:39+00:00",
  "ref": "master",
  "sha": "ff9425ae19d607662e1e8adb6732dd0509aacb9f",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

Issue 1

Engines are cranking regardless of ENG MODE SEL knob position. 

Issue 2

Air pressure is already there when ENG MODE sel is set to IGN/START. 

Issue 3

The MAN START pb doesn't start the ENG crank as it should.

### Expected behavior

Issue 1

Engines are supposed to start cranking only on IGN/START mode for an AUTO start when Master sw is set to ON. Or, when on IGN/START mode for an MAN start when MAN START pb is set to ON. Or, when on CRANK mode for a DRY crank when MAN START pb is also set to ON.

Issue 2

Pressure takes a while to increase after ENG MODE sel is set to IGN/START (no longer than 10s I'm sure). The pressure also drops a little when the START VLV opens.

Issue 3

When MAN START pb is pressed and with the ENG MODE SEL set to IGN/START, the start vlv shall open and the engine should start cranking. When master sw is set to ON, then Fuel Flow should rise.

### Steps to reproduce

Issue 1

Just select ENG MASTER sw to ON and you'll see it cranking. Should not.

Issue 2

When you turn ENG MODE sel to IGN/START, the pressure is there waiting for you.

Issue 3

When you press the ENG MAN START pb, absolutely nothing happens.

### References (optional)

Issue 1

DSC-70-90-20

Issue 2

My own experience flying the 320neo LEAP1A26

Issue 3

DSC-70-90-10

### Discord Username (optional)

Illuminati

**Comment by MisterChocker** [comment]
Regarding engines, please see #3117

**Comment by davidwalschots** [comment]
Closing as this is three bugs in one issue. As previously indicated in #5026 issues should be separated. Also, please refrain from using "tags" in the title (i.e. [POWERPLANT]). We will assign the appropriate label after issue creation.
