### ISSUE TITLE
Breaks only heats with manual action

### ISSUE THREAD

**Issue by Cassiano-Gunji** [flybywiresim/a32nx#5031]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-06T15:12:39+00:00",
  "ref": "master",
  "sha": "ff9425ae19d607662e1e8adb6732dd0509aacb9f",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

I don't see the breaks heating when landing with MIN or MED autobreaks. They only heat if I apply manual breaks, with or without autobreaks enabled. Also, they seem to be heating by less than half what they used to do on the experimental build.

### Expected behavior

Considering the behavior of the experimental build, I expected the breaks to heat to about 150º on MIN autobreak and low weight and up to 500 º with MED breaks or max manual breaks, high weight and hot air temperature.

### Steps to reproduce

1. Land normally with autobreaks enabled.
2. Note the breaks temperatures don't raise past ambient temperature.

### Discord Username (optional)

CassiKess

**Comment by Benjozork** [comment]
That's cause my old break temp code I did with @lukecologne only takes into account the brake position, which I think isn't populated by @crocket63's auto break.

This will be entirely replaced with a new much better calculation soon though.

**Comment by crocket63** [comment]
Known issue of new brakes PR merged recently because fs2020 auto brake applies magical force :). This is solved by new auto brakes to come.
