### ISSUE TITLE
[FMGS] TROPO field INIT A

### ISSUE THREAD

**Issue by Illuminati270** [flybywiresim/a32nx#5032]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-06T15:12:39+00:00",
  "ref": "master",
  "sha": "ff9425ae19d607662e1e8adb6732dd0509aacb9f",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

The TROPO field (INIT A) doesn't accept values it should.

### Expected behavior

On Honeywell systems, whenever you enter any value from 0 - 60000 on TROPO field (INIT A), it will accept as is.

600 = 600ft.

### Steps to reproduce

Many values aren't accepted displaying a "NOT ALLOWED" on the scratchpad.

### References (optional)

tracerZ posted a quote at Discord FMS section stating the following:

"Any tropopause altitude up to 60,000 ft is able to be entered. The tropopause altitude cannot be entered as a flight level. Feet must be entered (i.e., do not enter 380 for FL380, the FMS interprets as 380 ft)"

### Discord Username (optional)

Illuminati

**Comment by MisterChocker** [comment]
Tropo functionality currently is not implemented.
