### ISSUE TITLE
Audio Knob pushing itself down when respective MIC is selected

### ISSUE THREAD

**Issue by Illuminati270** [flybywiresim/a32nx#5033]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-06T15:12:39+00:00",
  "ref": "master",
  "sha": "ff9425ae19d607662e1e8adb6732dd0509aacb9f",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

[ACP/RMP]

- SEL light lights up green

- Whenever I press the microphone button, it presses back the volume knob corresponding to that microphone.

### Expected behavior

- SEL light is amber, and it lights up the whole "key".

- Selecting a microphone shouldn't have any influence on the volume knobs.

### Steps to reproduce

1. Pop the VHF2 volume knob.
2. Press the VHF2 microphone.
3. The volume knob will push itself back in, that's not supposed to happen by no means.

### References (optional)

![vhf](https://user-images.githubusercontent.com/85410344/120942383-f89d8e00-c6fe-11eb-8438-5639bb83e9fd.jpeg)

### Discord Username (optional)

Illuminati

**Comment by Benjozork** [comment]
Please change the title to not be empty.

**Comment by Illuminati270** [comment]
> Please change the title to not be empty.

Done

**Comment by juliansebline** [comment]
To check with #7105

If same behavior, I'll fix it
