### ISSUE TITLE
Pilot waypoints

### ISSUE THREAD

**Issue by faker320** [flybywiresim/a32nx#5038]
### Aircraft Version

Development

### Description

It seems that the "pilot waypoints" function in the mcdu is not working. Could you please make this function work? I would like to add some personal waypoints to the mcdu.

**Comment by MisterChocker** [comment]
Needs #4028, may be part of #4953

**Comment by tracernz** [comment]
Needs some way to write files from JS, or to transfer data from JS to WASM, or increased local storage. We would need Microsoft to do one of those first.

**Comment by derl30n** [comment]
Duplicate of #1380
