### ISSUE TITLE
Exposing PFD events and information to other Add-Ons

### ISSUE THREAD

**Issue by h-rezaei** [flybywiresim/a32nx#5039]
### Aircraft Version

Development

### Description

I fly using a co-pilot add on, Multi Crew Experience. At the moment, the co-pilot does not have access to the PFD events so it is unable to announce things like "srs", "runway", "autothrust blue", "nav", etc.
Is it possible for the flybywire team to expose the PFD information to developers so they can have access to it?
I am not quite sure if this has to be done from asobo's side or the wasm module but i thought i make a suggestion request here.

### Discord Username (optional)

Hadi#1904

**Comment by aguther** [comment]
The FMA information is already available as local variable. How this is transported to another computer is out of our scope, but the information is available. The PFD reads it also by those variables:
- A32NX_FMA_*
- A32NX_ApproachCapability
- A32NX_AUTOTHRUST_STATUS
- A32NX_AUTOTHRUST_MODE
- A32NX_AUTOTHRUST_MODE_MESSAGE

See here for full description (what values they can take and their meaning):
https://github.com/flybywiresim/a32nx/blob/master/docs/a320-simvars.md#autopilot-system
