### ISSUE TITLE
EGT high on sim load into cold and dark

### ISSUE THREAD

**Issue by ajs117** [flybywiresim/a32nx#5041]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-06T10:57:16+00:00",
  "ref": "master",
  "sha": "56337b10b51308a9d09f732141e2ded306ca9921",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

EGT high on sim load into cold and dark

![Microsoft Flight Simulator 07_06_2021 13_20_16](https://user-images.githubusercontent.com/34308197/121015860-5f6c8700-c793-11eb-8461-9919b3995607.png)

### Expected behavior

Needs reference regarding A320 specific display behaviour, however physically it should be the same as ambient temperature.

### Steps to reproduce

1. Load aircraft in sim
2. Observe EGTs

**Comment by Benjozork** [comment]
As stated [here](https://docs.flybywiresim.com/start/autopilot-fbw/), start-up sequence is not yet implemented.
