### ISSUE TITLE
Direct to a WPT erases whole flight plan in MCDU

### ISSUE THREAD

**Issue by mico975** [flybywiresim/a32nx#5042]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-06T15:12:39+00:00",
  "ref": "master",
  "sha": "ff9425ae19d607662e1e8adb6732dd0509aacb9f",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

Requested direct to a waypoint and flight plan got erased in MCDU.

### Expected behavior

Direct to a waypoint should erase waypoints up to the direct and not the whole flight plan

### Steps to reproduce

1. Load a flightplan and take off.
2. Request a direct to enroute waypoint. Flight plan gets erased.

### References (optional)

![image](https://user-images.githubusercontent.com/78908672/121016074-ffc6a980-c79b-11eb-8032-ea5b1444bae8.png)
![image](https://user-images.githubusercontent.com/78908672/121016101-06edb780-c79c-11eb-9112-ffbf76fddb60.png)

### Additional info (optional)

This was working better before since it at least didn't erase the whole flight plan. I don't know how much is this related to MSDS own issues.

**Comment by Benjozork** [comment]
Fixed in upcoming custom flight plan manager

**Comment by ryan1336** [comment]
Makes the aircraft unusable on VATSIM

**Comment by Venorcis** [comment]
> Makes the aircraft unusable on VATSIM

It doesn't always happen; not sure under what circumstances it does (maybe low FPS?) but I had it only once and then even the FROM/TO on the INIT page was cleared.
