### ISSUE TITLE
Wrong thrust mode indication

### ISSUE THREAD

**Issue by lonewulf47** [flybywiresim/a32nx#5045]
### Aircraft Version

Stable

### Build info

```json
0.6.1 last stable
```

### Describe the bug

I use standard NAP climb with 1500/3000 ft AGL thurst reduction/acceleration height. When reducing to CLB THR at 1500 ft AGL the Thrust Window changes to SPEED despite still being in SRS climb. After passing acceleration height  3000 ft the Thrust Window change to - correct - THR CLB. The SPEED indication in the Thrust Window during the recuced PWR Climb is wrong. It must be THR CLB also, as this can be no SPEED mode at all in SRS mode.

### Expected behavior

After reducing (commanded) to Climb Thrust during NAP the Thrust Window must show THR CLB

### Steps to reproduce

- set Thrust Reduction and Acceleration altitudes on PERF page according to standard NAP 1500/3000 ft AGL
- Take-off with TOGA
- reduce to Climb Thrust when commanded

**Comment by aguther** [comment]
This issue is already fixed in the development version.
