### ISSUE TITLE
CTD when loading an arrival

### ISSUE THREAD

**Issue by B-KC** [flybywiresim/a32nx#5060]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-08T10:56:21+00:00",
  "ref": "master",
  "sha": "4306724b4b1a923cf1ac3681861e365314c421c8",
  "actor": "MisterChocker",
  "event_name": "manual"
}
```

### Describe the bug

When loading in an arrival to KMCI and selecting ILS 1L, via EMP the sim crashes consistently. 

### Expected behavior

The sim shouldn't crash while loading arrivals.

### Steps to reproduce

1. Load in to any airport cold and dark
2. Fire up the A320 
3. Configure your INIT page with KMCI as your destination
4. Load your FPLN and set your arrival for 1L, and change the VIA from BUM to EMP and you crash.

**Comment by talzahr** [comment]
I'm having the same exact issue. Tried two different builds, the previous one master branch from about 4 days ago. Creating a flight on the MCDU and setting arrival it crashes every time just as I select the STAR transition. If needed for debug purposes the flight plan so far was: KABI(17L) DIESL GUSHR3 KIAH(ILS 27L) 

`{
  "built": "2021-06-13T20:38:36+00:00",
  "ref": "master",
  "sha": "68dfae0ec88ef384acd87da748f52e66f59d9d7e",
  "actor": "MisterChocker",
  "event_name": "manual"
}
`

**MSFS version:** 0.1.162 (Standard Xbox App)

**System:**
  DX12
  nVidia 466.77 Game Ready Driver
  Windows 10 Pro build 19042
  Ryzen 3700X
  32GB RAM
  nVidia 3070 FE
  Gigabyte X570 Aurous Elite rev.1

**Comment by talzahr** [comment]
After about 30 crashes and a few hours of testing, this is not a FBW bug. When creating a flight plan on the MCDU with any departure airport without SIDs, the game will CTD on selecting an arrival transition navaid. It will not crash if there is a SID selected in the departure screen. This happens on both the FBW A32NX and the Asobo A320neo MCDUs on my system for some reason despite removing everything else from the community directory and having everything updated.
