### ISSUE TITLE
Sudden massive memory Consumption

### ISSUE THREAD

**Issue by JustCodeIt4Head** [flybywiresim/a32nx#5061]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-05-05T23:03:06+00:00",
  "ref": "v0.6.1",
  "sha": "4a1cccc90ab3997109e394402ab9b41a80fbf325",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

I installed the A32NX today for my MSFS2020 and played around a bit. I closed both the Game and the Launcher (was not in the Background as far as I'm aware) and had no Issues for Hours.
I was watching some YouTube when suddenly my System began to "lag" and basically Chrome and other Applications I had open (like MS Teams) began to crash.
I managed to open up the Task manager and my System Monitoring and seen that the Flybywire Application was actively using around 50 to 55 GB of RAM, around 50% CPU and 1.5 MB/s DiskIO.

I seen Reports about the known Memory Leak, but as far as I could tell that only occurred when People Installed / Updated the Add-on or Played the Game. I did not play the Game at this Time, had both Applications closed and after opening / closing the FlyByWire Launcher it does not appear open in the Task manager or in my Program Monitoring.
So the Launcher seemd to, somehow, started itself (as said I watched some YouTube Video at the Time and did nothing else) and almost caused my System to crash

### Expected behavior

The Launcher should not start / open Itselfe when not activly started by the User

### Steps to reproduce

1. Install current A32NX
2. Start Game 
3. Exit Game
4. Close Launcher (FlyByWire Application)
5. Wait

### Additional info (optional)

Could not find anything wrong with the System and my System Monitoring did not register me starting the Launcher.

### Discord Username (optional)

Illiminator#5169

**Comment by ExampleWasTaken** [comment]
This is a known issue. It only happens once after installing/updating the installer.
Simply kill the process in the task manager.

**Comment by JustCodeIt4Head** [comment]
> This is a known issue. It only happens once after installing/updating the installer.
> Simply kill the process in the task manager.

Ah okay,
i seen the known Issue about the leak, but from what i gathered from other People it happend like described.
Since i Log all my System Actions etc with a Agent i will let you know if i find the Issue
