### ISSUE TITLE
Random Rudder Input Spikes Disconnect AutoPilot

### ISSUE THREAD

**Issue by speedbird5** [flybywiresim/a32nx#5070]
### Aircraft Version

Development

### Build info

```json
"built": "2021-06-08T21:41:41+00:00",
  "ref": "master",
  "sha": "bda03c6c08a45df4a4d72bae3040666ad40b6561",
  "actor": "aguther",
  "event_name": "manual"
```

### Describe the bug

When flying with the autopilot engaged. i get occasional Random Rudder Input Spikes which Disconnect AutoPilot.  I can see the rudder pedals rapidly move left and right.

I have recalibrated my rudder pedals and they are working normally. 

### Expected behavior

No random rudder inputs.

### Steps to reproduce

Use this mod and try to fly with A/P engaged.  The rudder spikes are not frequent.

**Comment by Watsi01** [comment]
I never had that > unless my controller had issues. I would assume this comes from your periphery and not from the A32NX itself. Could also be a misconfig with your key-/ axisbindings. Check out your controllers (windows settings). See if the rudder controls spike there too occasionally. Wiggle the cables, etc.

**Comment by speedbird5** [comment]
> I never had that > unless my controller had issues. I would assume this comes from your periphery and not from the A32NX itself. Could also be a misconfig with your key-/ axisbindings. Check out your controllers (windows settings). See if the rudder controls spike there too occasionally. Wiggle the cables, etc.

I have done all that and more. The rudders - MFG Crosswind - work flawlessly in other flight sims.

**Comment by aguther** [comment]
I‘m pretty sure this is still an issue related to you setup. I never had this a single one and tbh right now I have no idea how I should fix that for you. Everything that is done is capture the events that the sim provides and use that as input.

Maybe those questions will help to shed a light on the issue you have:
- what hardware do you have?
- do you use assignment in MSFS or via external tool?
- if assignment in MSFS, what is your sensitivity setting (screenshot please)?
- if external tool: which one and how does the config for that look like?

**Comment by Watsi01** [comment]
Also (just to be sure): remove any other mod or custom livery from you community folder and try again.

**Comment by speedbird5** [comment]
I have just run some joystick monitoring software for an hour and the rudder did not move once.

I do have some custom liveries so i will remove them.  I was using the Air Canada  livery from flightsim.to

And i will also download a fresh latest version.

**Comment by tracernz** [comment]
Make sure there are no other controllers bound to rudder axes in your MSFS settings.

**Comment by speedbird5** [comment]
> Make sure there are no other controllers bound to rudder axes in your MSFS settings.

That was the first thing I checked

**Comment by aguther** [comment]
> > Make sure there are no other controllers bound to rudder axes in your MSFS settings.
> 
> That was the first thing I checked

Did you also check other events on the keyboard? There are multiple ways to manipulate the rudder, not only axis.

**Comment by speedbird5** [comment]
Yes I deleted even keyboard binds to control the rudder, and then went through every controller and checked there was nothing assigned.  This is both within MSFS and FSUIPC.

First:  I deleted everything from the community folder entirely and check with the default A320 and no problems.

Second:  I then downloaded a fresh install of the latest dev build and straight away the problem came back.

I then deleted both the rudder and the left and right brake bindings and noticed that through FSUIPC there are a constant stream of left and right brake applications being sent to the sim.  See attached.

I re checked all my bindings - within MSFS and FSUIPC -  for any spurious brake assignments but there were none.

When I had the same FSUIPC monitor up in the default A320 there were no spurious Left and Right brake applications.

It seems the A32NX is sending a constant stream of commands for Left and Right Brake.  Not sure if it is relevant to this problem.

I will be away from my computer for the next two days so will not be able to test further until i return.

thanks.

![2021-06-09 21_53_41-Select FSUIPC7 Console Log](https://user-images.githubusercontent.com/20328510/121351231-e32e9b00-c96e-11eb-9d3c-b34a4d98f035.png)

**Comment by aguther** [comment]
The `AXIS_LEFT_BRAKE_SET` and `AXIS_RIGHT_BRAKE_SET` events are from the custom braking implementation and are not related to the rudder events.

The following events are relevant for rudder:
* RUDDER_SET
* RUDDER_LEFT
* RUDDER_AXIS_PLUS
* RUDDER_CENTER
* RUDDER_RIGHT
* RUDDER_AXIS_MINUS

The rudder pedals in the sim are now bound solely to trim and rudder input. So when they move rapidly it‘s coming as input. When AP is engaged and the input is more than 40% of the possible travel the AP disconnects.

**Comment by aguther** [comment]
As an additional info: I think you don’t see the rudder events in FSUIPC because the FBW masks those events with a high priority.

**Comment by speedbird5** [comment]
Hi all, after extensive testing it looks like it may be a rare problem with my rudder hardware.  Please close the topic and thanks.

**Comment by sidnov** [comment]
Closed as per author's respond
