### ISSUE TITLE
Left ND stuck and left flood lighs not working on aircraft reload through developer mode

### ISSUE THREAD

**Issue by tush0701** [flybywiresim/a32nx#5071]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-08T21:41:41+00:00",
  "ref": "master",
  "sha": "bda03c6c08a45df4a4d72bae3040666ad40b6561",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

When the aircraft is loaded again at a gate/parking through Developer mode > Windows > Load Aircraft > Press load,
the aircraft loads in Take-off config(engines running, lights on, T.O. Config. checked, IRS on NAV, aligned etc.) as it would load on a runway.

The 2 floodlights on the left don't illuminate(although the light is on, can be seen by directly looking at them)and the flight plan  on the left ND gets stuck at the location of the aircraft. However, the heading reading is always correct, and changes when aircraft turns. Flight plan on the right ND, as well as the floodlights works correctly.

Also in such cases, the pilot logbook shows 00:00:00 as total time of flight. Screenshot attached.(This might be a default game bug!!)
![Screenshot (24)](https://user-images.githubusercontent.com/75409941/121316042-89a27e00-c926-11eb-9bd8-b2cf5add1b0d.png)

### Expected behavior

At a gate, or parking, the aircraft should load in cold and dark mode, and not in take-off mode

### Steps to reproduce

1. Load a32NX from the menu at any airport gate
2. Leave aircraft cold n dark, or alternatively turn on battery and APU
3. Turn on developer mode
4. From Windows > Aircraft Selector
5. Directly click on Load
6. Enter a flight plan
7. Aircraft loads in take off state, ND gets stuck

### Additional info (optional)

I was using this re-load as a workaround for the default game problem of not flushing the aircraft load memory to avoid stutters and lags. Using this workaround, aircraft runs smoother.

I use 
ASUS ROG Strix G17 
Ryzen 9 
RTX3070 Laptop GPU 
16 GB RAM

**Comment by tracernz** [comment]
We cannot support developer mode and have no control over it. The logbook issue is present always when developer mode is enabled.
