### ISSUE TITLE
Add-ons using FSUIPC or simconnect are unable to read parking break state

### ISSUE THREAD

**Issue by h-rezaei** [flybywiresim/a32nx#5074]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-09T07:52:45+00:00",
  "ref": "master",
  "sha": "e3cda27aa50d6a8173363ccb7ae256888dc67842",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

add ons such as pushback express or various virtual airline acar software are unable to read the parking break state since one or two days ago.
They do think the parking break is released and setting it and releasing it will not have any effect

### Expected behavior

Before this issue appeared, when using different add-ons such as pushback express (uses simconnect) and my virtual airline acar software (uses FSUIPC), They were able to detect and read if the parking breaks were set or released as soon as you have set them or released them in the plane.

### Steps to reproduce

1. load the aircraft cold and dark
2. Use an add on that uses simconnect or FSUIPC to connect to the sim, something like pushback express or your virtual airline software
3. When you set or release the parking breaks, the add ons are unable to read or detect it.

### References (optional)

I believe this can be tested with watching FSUIPC offsets but i do not know how to do this properly.

### Additional info (optional)

This worked before. It appears to have happened a day or two days ago.

**Comment by Watsi01** [comment]
This is a known issue, since we are using custom LVARs for braking now. I spoke to the FS2Crew crew - Pushback Express will work again with version 2.1 (release soon). Regarding FSUIPC, I don't know.

**Comment by crocket63** [comment]
Cable park brake was removed from the A320 indeed :)  I'm yet unable to write the PARKING POSITION again while keep functionallity we want

**Comment by 2hwk** [comment]
Repeat of #5006, closing.
