### ISSUE TITLE
HYD PTU memo on ECAM incorrect behaviour

### ISSUE THREAD

**Issue by raeliass** [flybywiresim/a32nx#5077]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-09T07:52:45+00:00",
  "ref": "master",
  "sha": "e3cda27aa50d6a8173363ccb7ae256888dc67842",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

On a single engine taxi procedure, after you start engine 1 and turn on the hyd yellow eletric pump, you can check on the HYD sys page that the PTU is correctally inactive, since pressure is beeing provided by engine 1 on the blue sys and the eletric pump on the green sys

Even tho the PTU is OFF as confirmed by the ECAM HYD page, the HYD PTU memo is present on the ECAM.

On a related matter HYD PTU memo also shows on the ground even if the PTU and ELEC pumps are off and pressure on the Yellow sys is 0 on the ground (screenshot included)

Also, HYD PTU memo does not show in flight even if it's in fact active due to ENG 2 (or 1) PUMP beeing set off or if the engine 2 (or 1) itself is off

### Expected behavior

HYD PTU ecam memo should only appear if the PTU is in fact active (HYD pressure difference between yellow and green systems > 500 PSI

### Steps to reproduce

1. Go throught normal pre-flight
2. Perform a single engine taxi out procedure:
2b.Start engine 1
2c Set ignition normal
2d. Set APU bleed off
2e. Set Yellow Hyd eletric pump ON
3. Verify PTU ON memo on ECAM, very that the PTU is actually of in the HYD sys page

HYD PTU memo will also show if Eng1 is on, Yellow electric pump is off and there is not pressure on the yellow line (PTU inactive on the ground)

### References (optional)

![image](https://user-images.githubusercontent.com/74863536/121422529-b4e89580-c945-11eb-9753-0c80366d6a3e.png)

![image](https://user-images.githubusercontent.com/74863536/121423084-45bf7100-c946-11eb-9d59-e938afda7153.png)

![image](https://user-images.githubusercontent.com/74863536/121423132-5243c980-c946-11eb-9184-8d6289930b79.png)

![image](https://user-images.githubusercontent.com/74863536/121424167-6dfb9f80-c947-11eb-8fa8-22c42f15bfb6.png)

![image](https://user-images.githubusercontent.com/74863536/121423977-312fa880-c947-11eb-98ab-1250bbbb8217.png)

![image](https://user-images.githubusercontent.com/74863536/121427755-77870680-c94b-11eb-8ddf-7349c170c4d4.png)

![image](https://user-images.githubusercontent.com/74863536/121423723-f594de80-c946-11eb-8d99-e967d9ca4d27.png)

![image](https://user-images.githubusercontent.com/74863536/121423812-0c3b3580-c947-11eb-8f1d-54f73af935f8.png)

### Discord Username (optional)

raelias #5157

**Comment by beheh** [comment]
Yep, the current implementation is very simplified. Somebody can tackle this, or it will be fixed in the mid-term via our new FWC.

**Comment by raeliass** [comment]
> Yep, the current implementation is very simplified. Somebody can tackle this, or it will be fixed in the mid-term via our new FWC.

Yeah it's funny, HYD PTU shows when it should not and does not show when it should, it's almost like it's logic is inverted

**Comment by crocket63** [comment]
Nothing is inverted it's just totally  different logic which is not linked to actual hydraulics.   I don't know what is the exact logic for upper ecam though, is it the same as hyd ecam screen?
Beheh: will the FWC integrate the logic part or can we already implement something in wasm?

**Comment by beheh** [comment]
> Beheh: will the FWC integrate the logic part or can we already implement something in wasm?

The FWC will implement the logic part in WASM :-) Work is underway on signal acquiry and initial flight phase calculation to nail down the API for the logic parts. The next thing then are message passing from WASM->ECAM and flight phase inhibitons. I'd say we're at least 4-6 weeks away from people working on actual memos and warnings, so for now I would suggest either waiting for a bit longer or if you really want implementing it in the old-style UpperECAM (but I would suggest not spending hours and hours on that code any more).

**Comment by crocket63** [comment]
Could be possibly faked using the actual ptu state from hydraulics as a placeholder. Will see if I have time to look into this!

**Comment by raeliass** [comment]
> Could be possibly faked using the actual ptu state from hydraulics as a placeholder. Will see if I have time to look into this!

On my book that would be very much good enogh for now

**Comment by tush0701** [comment]
A small doubt/request. Could/would we also have the "bark" PTU sound the moment pump is switched off on single engine, just like IRL?
At the moment the PTU sound just occurs when PTU is initially turned on after one engine is fully started.

Thanks team!

**Comment by hotshotp** [comment]
> A small doubt/request. Could/would we also have the "bark" PTU sound the moment pump is switched off on single engine, just like IRL?
> At the moment the PTU sound just occurs when PTU is initially turned on after one engine is fully started.
> 
> Thanks team!

ive said before, i am only going to do this once the physical ptu model is in or it will sound inaccurate
