### ISSUE TITLE
XPNDR Altitude Reporting Button movement

### ISSUE THREAD

**Issue by Illuminati270** [flybywiresim/a32nx#5078]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-09T07:52:45+00:00",
  "ref": "master",
  "sha": "e3cda27aa50d6a8173363ccb7ae256888dc67842",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

The button is slowly increasing from OFF to ON

### Expected behavior

Actual button is a switch OFF/ON, just a click.

### Steps to reproduce

1. Turn on or off the ALT RPTG button

### Discord Username (optional)

Illuminati

**Comment by BlueberryKing** [comment]
I believe this has been addressed in https://github.com/flybywiresim/a32nx/pull/6159.
