### ISSUE TITLE
MCDU TO PERF PAGE Won't accept triple digit ACC/RED Alt

### ISSUE THREAD

**Issue by raeliass** [flybywiresim/a32nx#5079]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-09T07:52:45+00:00",
  "ref": "master",
  "sha": "e3cda27aa50d6a8173363ccb7ae256888dc67842",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

Takeoff Page won't accept triple digits on THR RED/ACC alts (IE 420/420), it requires to be insert 0420/0420 otherwise ir returns the FORMAT ERROR msg

Honeywell's build does accept the triple digits variant, even tho Thales' does not (it would require 0420) my understanding is that we are simulating the Honeywell so it should be accepted.

Also, after you input a triple digits ACC ALT (0420/0420), it inserts a blank space between the "420" and the left side of the display.

I could not find the required format specified on the manual so you guys are gonna have to trust me on this one as a real A320 pilot, all I could find is the minimum altitude of 400ft above runway elevation which is correctly modeled

### Expected behavior

Honneywell should accept a triple digit format normally, also there should not be a blank space before a triple digit altitude

### Steps to reproduce

Try to insert a triple digit ACC ALT on the TAKE OFF PERF page

### References (optional)

![image](https://user-images.githubusercontent.com/74863536/121426593-262a4780-c94a-11eb-9d77-d2ed1d9a546d.png)

![image](https://user-images.githubusercontent.com/74863536/121426872-730e1e00-c94a-11eb-98e0-c556875832a7.png)

![image](https://user-images.githubusercontent.com/74863536/121426881-76a1a500-c94a-11eb-8250-0d837c0cea0d.png)

![image](https://user-images.githubusercontent.com/74863536/121426896-7a352c00-c94a-11eb-8134-ede4df311b82.png)

![image](https://user-images.githubusercontent.com/74863536/121426901-7bfeef80-c94a-11eb-9803-62e62c6b526e.png)

### Discord Username (optional)

raelias #5157

**Comment by raeliass** [comment]
I get it that most things needs a manual reference, but on this case there is simply no mention of accepted format on the manual at all, I'm gonna heve to reference it on 2,000h flight time on the A320 IRL, feel free to confirm the info with other Honeywell pilots if necessary.

**Comment by Illuminati270** [comment]
> I get it that most things needs a manual reference, but on this case there is simply no mention of accepted format on the manual at all, I'm gonna heve to reference it on 2,000h flight time on the A320 IRL, feel free to confirm the info with other Honeywell pilots if necessary.

I can confirm that.

**Comment by lukecologne** [comment]
This is from the Honeywell FMS Pegasus Step 1A manual, which should be the most modern version after the FMS Release 2, Not sure how it is there, but this is probably the reference the current implementation is modeled after.
![grafik](https://user-images.githubusercontent.com/39596827/121444401-be96eb00-c98f-11eb-8d28-7fee167da400.png)

**Comment by raeliass** [comment]
Well don't know what to tell you, in 3 years operating A320/A320N on Honeywell Pegasus I have never seen an invalid format for a 3 digit acc alt

**Comment by MisterChocker** [comment]
@raeliass maybe this is different on Pegasus II?

**Comment by beheh** [comment]
I'm happy to defer to pilot experience here for someone with Honeywell units. This would not be the first time that the manual isn't 100% precise.

**Comment by raeliass** [comment]
> I'm happy to defer to pilot experience here for someone having access to a Honeywell unit. This would not be the first time that the manual isn't 100% precise.

Oh this is a common Airbus trend haha, I'd love to hear others opinions on the matter



> @raeliass maybe this is different on Pegasus II? (which is the version we are recreating)

Maybe, I couldn't say for sure the exact CDU build, my company had very old with CRT screens to very new and shinny NEOs and they all accepted the 3 digit,
