### ISSUE TITLE
MCDU CLR button hold behaviour incorrect

### ISSUE THREAD

**Issue by raeliass** [flybywiresim/a32nx#5080]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-09T07:52:45+00:00",
  "ref": "master",
  "sha": "e3cda27aa50d6a8173363ccb7ae256888dc67842",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

Holding the CLR button on the MCDU only clears the last digit, same as a brief press

### Expected behavior

Holding the CLR button on the MCU for 3 seconds should clear the whole scratchpad
Addition: On NEOs and never CEOs it's ~1 second.

### Steps to reproduce

1. Type random stuff on the MCDU
2. Hold CLR and observe only the last digit is erased

### References (optional)

![image](https://user-images.githubusercontent.com/74863536/121428147-dcdaf780-c94b-11eb-8428-dd2590e53cfb.png)

### Discord Username (optional)

raelias #5157

**Comment by marcman86** [comment]
Quality Assurance Tester Report
Discord:marcman86#4907
Object of testing: #5046
Tier of Testing: 1
Date: 10/06/2021

Testing Process: 
- Spawned C&D at EDDP
- Turned on bat. and ext. power
- Press CLR to clear GPS PRIMARY LOST
- Type in some digits
- Press CLR to clear single digits
- Press and hold CLR to clear all digits
- Align ADIRS
- Press and hold CLR to clear GPS PRIMARY

Negatives: I dont know the behaviour in real life but when pressed and hold first the last digit clears and then after a second the rest. This looks awkward. When hold down should the single clear be inhibit?
Testing Results: Passed, when found a reference for the issue.
Conclusions: Works in general
Media: -
Hope this helps :-)
