### ISSUE TITLE
Displays black after using drone camera

### ISSUE THREAD

**Issue by ajts1958** [flybywiresim/a32nx#5083]
**Installer Version** Dev 22f0244 version

**Describe the bug**

after a drone view I found the cockpit lost most of its instruments
**To Reproduce**

1. climbing from Munich to Amsterdam at FL220
2. tried to look outside with drone camera
3. back to cockpit I lost most of the instruments
![Microsoft Flight Simulator Screenshot 2021 06 05 - 22 36 24 47](https://user-images.githubusercontent.com/75549266/120906291-1b249e00-c650-11eb-8713-0695297a152a.png)

**Expected behavior**

**Additional context**

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by tracernz** [comment]
Needs to be fixed by Microsoft/Asobo. As a workaround, you can try waiting for a bit and often they come back, or maybe try pause/unpause, changing views, etc.
