### ISSUE TITLE
2.5nm Range ring does not appear when TCAS is ON!

### ISSUE THREAD

**Issue by Illuminati270** [flybywiresim/a32nx#5088]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-10T09:49:19+00:00",
  "ref": "master",
  "sha": "1578f4fa852800ef1d7c46ad6460f21bf92a2c3a",
  "actor": "MisterChocker",
  "event_name": "manual"
}
```

### Describe the bug

Turning ON the TCAS doesn't show the 2.5nm Range ring.

### Expected behavior

When TCAS is turned ON (TA or TA/RA), a 2.5nm distinct range ring should come up.

### Steps to reproduce

1. Position the aircraft on the runway
2. Select range to 10/20nm
3. Turn TCAS to TA or TA/RA
4. A 2.5nm range ring is expected if 20nm selected. 
5. The 2.5nm range ring is expected to change from continuosly dashed lines to vertical widely separated lines if 10nm is selected.

### References (optional)

![TCAS](https://user-images.githubusercontent.com/85410344/121649073-903c0d00-ca6e-11eb-9ac5-f22b5949f3f2.jpg)
![TCAS2](https://user-images.githubusercontent.com/85410344/121649074-903c0d00-ca6e-11eb-8c43-f9f56b233ebc.jpg)

### Discord Username (optional)

Illuminati

**Comment by tracernz** [comment]
This was going to be fixed in #4383, but instead I have fixed it in the new ND being built on the autopilot-custom-fpm branch.
