### ISSUE TITLE
[BUG] EICAS messages sometimes flicker at regular intervals

### ISSUE THREAD

**Issue by UncleClapton** [flybywiresim/a32nx#509]
**Mod Version**

master

**Describe the bug**

Normal EICAS messages can flicker periodically. See video for demonstration.

**To Reproduce**

1. Load into plane (from runway)
2. check EICAS messages

**Expected behavior**

No weird flickering

**Actual behavior**

immersion-breaking text flickering. 😄 

**References**

video: https://imgur.com/a/gfv7ufG

**Additional context**

**Comment by devHazz** [comment]
Can't seem to reproduce this. Does it flicker in specific intervals?

**Comment by UncleClapton** [comment]
it's specific intervals when it happens, but when it happens is weirdly inconsistent.

**Comment by UncleClapton** [comment]
This no longer happens for me and nobody else is really reporting it so I'm going to close this.
