### ISSUE TITLE
15s rule for A/THR deactivation

### ISSUE THREAD

**Issue by Illuminati270** [flybywiresim/a32nx#5092]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-11T10:53:14+00:00",
  "ref": "master",
  "sha": "61806933977ff5d448a5ec2a38785e227c8310e6",
  "actor": "MisterChocker",
  "event_name": "manual"
}
```

### Describe the bug

After holding the A/THR instinctive disconnect pb, the A/THR can be armed again.

### Expected behavior

After 15s of that pb being held, the A/THR should not be able to arm, engage or reconnect ever again, until the next FMGS power up. A.FLOOR is then lost.

### Steps to reproduce

1. Press the A/THR instinctive disconnect pb for 15s
2. A/THR will engage normally if requested.

### References (optional)

![image](https://user-images.githubusercontent.com/85410344/121754816-ee5b0580-caeb-11eb-8d52-5ea1387be6e6.png)

### Discord Username (optional)

Illuminati

**Comment by MisterChocker** [comment]
Requires implementation of #5048 first.

**Comment by tracernz** [comment]
Can we detect a hardware button being held down? We could do it for mouse clicks on the 3D cockpit buttons.

**Comment by aguther** [comment]
The 15s deactivate is already implemented and works correctly, just tried it again a few days ago also for A.FLOOR. But you need to assign the correct event for your button. See also https://docs.flybywiresim.com/start/autopilot-fbw/ for the two events. One correspondent to the FCU push button and the other correspond to the red button on the throttles.

I don’t thing the reset after landing is enough. It says power-up so it needs a power-cycle. This is not yet implemented and I need to add a reset signal. Question is then when this gets triggered.

**Comment by Illuminati270** [comment]
Hi @aguther 

You are indeed right! Through the Joystick button it will work. Using the mouse button, however, it won't!

**Comment by MisterChocker** [comment]
@aguther do you have an event or local variable for me to use when re-initializing the fmgc?

#5048

**Comment by aguther** [comment]
@MisterChocker I've added an event:
`A32NX.ATHR_RESET_DISABLE`

**Comment by aguther** [comment]
The reset with FMGC will come with PR#5048
