### ISSUE TITLE
Throttle detents not working correctly

### ISSUE THREAD

**Issue by ngorden** [flybywiresim/a32nx#5098]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-12T12:11:38+00:00",
  "ref": "master",
  "sha": "8a134d1903f04bf0c722b6ae6af1467f62b72c01",
  "actor": "tracernz",
  "event_name": "manual"
}
```

### Describe the bug

After take off, when directed to move the throttle from FLEX  climb thrust, the new throttle setting is not realized on the PFD; please see the images below.

Note: the behavior of the aircraft is correct, the speed is held, it's just the PFD that is incorrect.

### Expected behavior

Given I have just taken off
And Given I have thrust settings at FLEX
When LVR CLB appears blinking on the PFD
And When I move the throttle from FLEX to CLIMB
Then the PFD no  longer blinks LVR CLB

### Steps to reproduce

1. Spawn at the runway
2. Take off with FLEX

### References (optional)

![20210612075304_1](https://user-images.githubusercontent.com/8162701/121780128-cef7c300-cb53-11eb-9382-0a801f6cba40.jpg)
![20210612075309_1](https://user-images.githubusercontent.com/8162701/121780133-d15a1d00-cb53-11eb-98ba-e0f7ee43f15c.jpg)

### Discord Username (optional)

stonkilla4

**Comment by BlueberryKing** [comment]
Are you sure you have given your detents large enough deadzones? Try increasing them to see if that helps.

**Comment by ngorden** [comment]
Just tried this, turning the dead zone up actually made it worse.

**Comment by BlueberryKing** [comment]
When you put your thrust levers to CLB and open up the calibration on the EFB. Can you see something like this?

Notice how the "current value" is in the deadzone, meaning in between 0.00 and 0.04.
![efb-calibration](https://user-images.githubusercontent.com/22713769/121781367-a0560880-cba4-11eb-9091-ca4607224947.png)

**Comment by lanzaks** [comment]
I have the same problem: climb speed not recognized. The takeoff thrust positon does not matter. 
Going back to the stable version solves it, updating to the current dev version breaks it again.
The bug was introduced quite recently, as I had no problems with the dev build from a few days ago.

**Comment by BlueberryKing** [comment]
There are a lot of changes happening on the development branch all the time, so throttle calibrations may get messed up. Try going through the calibration process again. Put your throttle into all of the detents and press "Set from Throttle". Make sure you use reasonable deadzones. Also make sure to save & apply your changes!

**Comment by oldmanbishop** [comment]
This seems independent of a throttle controller, in case there's confusion. I was having issues just using a controller (which obviously has no detents). I had to recalibrate just the base in-sim throttle. Not sure if there's a bug there, but I would expect the calibration defaults to work when just manipulating the sim itself.

**Comment by lanzaks** [comment]
Yes, same for me, only using gamepad. I was also able to solve it via calibration. 
I had never used calibration before, as the defaults always worked before.

**Comment by aguther** [comment]
Ensure that you have your throttles properly calibrated, this is your issue. If you need help, I suggest coming to support channel on discord.
