### ISSUE TITLE
Autobrake improvement

### ISSUE THREAD

**Issue by Illuminati270** [flybywiresim/a32nx#5099]
### Aircraft Version

Development

### Description

When you land on A/BRK MED (3m/s² decel rate) and you eventually select LO (2m/s² decel rate) during the ground roll, brakes will be alleviated, the other way around would press the brakes a little more. If you select "MAX" by accident (many people have done it trying to turn brake fan on, and they will still be doing it over the next years) the aircraft will literally anchor on the runway.

Also, given the following:

 LO + NO REV = Landing distance X = Brake temperature Y
 LO + REV = Landing distance X = Brake temperature <Y
 MED + NO REV = Landing distance <X = Brake temperature >>Y
 MED + REV = Landing distance <X = Brake temperature >Y
 MAN BRK + NO REV = Landing distance <<<X = Brake temperature >>>>Y
 MAN BRK + REV = Landing distance <<<<X = Brake temperature >>>Y
 
So, it's correct to assume that using the combination of A/BRK + REV, won't change the landing distance for the same A/BRK setting, since the REV will alleviate the brakes in order to keep the desired decel rate. Solely being able to avoid higher brake temperatures!
 
 
 

### References (optional)

FCOM / Personal experience on A320neo IRL and FFS tests

### Discord Username (optional)

Illuminati

**Comment by MisterChocker** [comment]
Do this pr's changes meet your expectations?

**Comment by Illuminati270** [comment]
> Do this pr's changes meet your expectations? #4970

Downloaded, now testing. I'll publish first impressions.

**Comment by Illuminati270** [comment]
@MisterChocker 

Not sure if we can merge this one to that. So far, I see a nice improvement!

However, brake temps are way off! 

At MTOW, V1 cut, NO REV you'd expect to see really high temperatures after an RTO (>700C)

It stays at no more than 340C, though, and it hardly changes from LO/MED/MAX, while IRL it makes a huge difference.

![image](https://user-images.githubusercontent.com/85410344/121789421-393c5200-cbac-11eb-95ec-fc141dbe4590.png)
![image](https://user-images.githubusercontent.com/85410344/121789435-48bb9b00-cbac-11eb-9ee5-fce331332741.png)
![image](https://user-images.githubusercontent.com/85410344/121789429-40636000-cbac-11eb-98cd-8a58548568ec.png)
![image](https://user-images.githubusercontent.com/85410344/121789414-2c1f6300-cbac-11eb-8233-e404f8ef682d.png)
