### ISSUE TITLE
[BUG] EGT value on upper ecam remains red despite being under the threshold

### ISSUE THREAD

**Issue by Samueleonard** [flybywiresim/a32nx#510]
**Mod Version**
Latest master branch build

**Describe the bug**
EGT value on upper ecam remains red despite being under the threshold

**To Reproduce**
1. Load Plane as normal and fly
2.
3.

**Expected behavior**
EGT value on upper ecam text colour is green when below the hotstart threshold

**Actual behavior**
EGT value remains red depite being under the threshold - as per picture
https://i.imgur.com/jgohefq.png

**Comment by asessa1976** [comment]
I confirm , it occours when you go in CLB mode.
it turns green again if you decrease the throttle a little (in CLB)

**Comment by olibarke** [comment]
[https://app.photobucket.com/u/olibarke/p/3bd63a3f-7f41-4c99-80f2-098490767ed7](url)

**Comment by Taz5150** [comment]
EGT does not go into the red zone at normal temperature values.
