### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by cintula187** [flybywiresim/a32nx#511]
**Mod Version**
FlyByWire A32NX - Stable 0.2.0

**Describe the bug**
After take off with flaps 2 the flaps are moving to position 1 without any key input. AI control is off. 
After landing after the atc gives me the gate. the plane follows the blue arrows. all this without input. AI control is off. 

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**
https://youtu.be/ZL0nzSqh4o0

**Additional context**

**Comment by omarocasio** [comment]
What

**Comment by Curtis-VL** [comment]
Hi,

This is a bug with FS2020 not our mod specifically, please report it on their support desk!

https://flightsimulator.zendesk.com/hc/en-us/requests/new
