### ISSUE TITLE
Throttle lever

### ISSUE THREAD

**Issue by Gresmaksim** [flybywiresim/a32nx#5113]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-14T12:47:32+00:00",
  "ref": "master",
  "sha": "5f697b19d622af507ec5ca4854c253d375e105c8",
  "actor": "sidnov",
  "event_name": "manual"
}
```

### Describe the bug

Lowest avaailable engine bug position on joystick  became equal to full reverse thrust.
ALso  pushing joystick button which  is responsible  reverse thrust hold  doesn't make any sense now.
 

### Expected behavior

As it was before, lowest engine slider position on joystick is equal to idle thrust.

### Steps to reproduce

1. Load at any airport, doesn't matter cold and dark or on the runway.
2. move joystic slider from lowest position to any. First you will see the reverser activated.

### References (optional)

![1](https://user-images.githubusercontent.com/85883009/121899186-d920e980-cd2c-11eb-836b-f1bdbb99b416.jpg)
![2](https://user-images.githubusercontent.com/85883009/121899190-d9b98000-cd2c-11eb-95ca-0d70dbd38111.jpg)
![3](https://user-images.githubusercontent.com/85883009/121899196-db834380-cd2c-11eb-97ca-af5b597593b0.jpg)

### Additional info (optional)

1 screen is just after loading with idle position on joystic slider.
2 is after moving it to power up the engine but it is seen reverser instead
3 Sensetivity in settings

Such behaviour isn't observed on default planes or A320NX stable version.
Could you please check.

### Discord Username (optional)

Scane#5745

**Comment by hotshotp** [comment]
You must calibrate your throttles in the EFB. Also, you must have a linear throttle configuration in MSFS settings. Ask on discord for more help calibrating.

**Comment by Gresmaksim** [comment]
Thanks
