### ISSUE TITLE
Low performance(Low FPS) and issue in menu mode

### ISSUE THREAD

**Issue by York1964** [flybywiresim/a32nx#5116]
### Aircraft Version

Development

### Build info

```json
"built": "2021-06-14T12:47:32+00:00",
  "ref": "master",
  "sha": "5f697b19d622af507ec5ca4854c253d375e105c8",
  "actor": "sidnov",
  "event_name": "manual"
```

### Describe the bug

I have low FPS and stutter on the ground and on approach, also when I enter the configuration menu and exit, the flaps and spoliers have fully deployed

### Expected behavior

that this be corrected

### Steps to reproduce

since the last update of the MFS2020

### Discord Username (optional)

jenriquejh23

**Comment by ErikNL80** [comment]
Which hardware are you using? Most of the time this is caused by double assignments. And low performance, enable devmode to give some more insights.

**Comment by aguther** [comment]
What is your sim version?

**Comment by York1964** [comment]
Cpu Intel core i5-8400 @2.8ghz
Memory 2x8G @2400Mhz
Disco SSD 500G M2
GPU Nvidia  Geforce RTX 2060 6G

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: ***@***.***>
Enviado: lunes, 14 de junio de 2021 12:59 p. m.
Para: ***@***.***>
CC: ***@***.***>; ***@***.***>
Asunto: Re: [flybywiresim/a32nx] Low performance(Low FPS) and issue in menu mode (#5116)


Which hardware are you using? Most of the time this is caused by double assignments. And low performance, enable devmode to give some more insights.

**Comment by York1964** [comment]
My Sim Ver 1.16.2.0

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: Andreas ***@***.***>
Enviado: lunes, 14 de junio de 2021 2:38 p. m.
Para: ***@***.***>
CC: ***@***.***>; ***@***.***>
Asunto: Re: [flybywiresim/a32nx] Low performance(Low FPS) and issue in menu mode (#5116)


What is your sim version?

**Comment by aguther** [comment]
Please double check your assignments for any hidden ones. Please try also with the default A320 is the same happens or not. Can you send a screenshot of the devmode FPS when you have stutters?

**Comment by York1964** [comment]
***@***.******@***.******@***.******@***.******@***.******@***.***D7615E.B4448B10]

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: Andreas ***@***.***>
Enviado: lunes, 14 de junio de 2021 4:38 p. m.
Para: ***@***.***>
CC: ***@***.***>; ***@***.***>
Asunto: Re: [flybywiresim/a32nx] Low performance(Low FPS) and issue in menu mode (#5116)


Please double check your assignments for any hidden ones. Please try also with the default A320 is the same happens or not. Can you send a screenshot of the devmode FPS when you have stutters?

**Comment by Benjozork** [comment]
Please do not open issue threads for multiple problems.

**Comment by York1964** [comment]
***@***.******@***.***D76164.DA8F5790]

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: Andreas ***@***.***>
Enviado: lunes, 14 de junio de 2021 4:38 p. m.
Para: ***@***.***>
CC: ***@***.***>; ***@***.***>
Asunto: Re: [flybywiresim/a32nx] Low performance(Low FPS) and issue in menu mode (#5116)


Please double check your assignments for any hidden ones. Please try also with the default A320 is the same happens or not. Can you send a screenshot of the devmode FPS when you have stutters?

**Comment by aguther** [comment]
That is how your response looks like, no idea if you wrote something:
![image](https://user-images.githubusercontent.com/6629914/122283374-c228f580-ceec-11eb-85f9-8b3ab014b778.jpeg)

**Comment by Benjozork** [comment]
No response.
