### ISSUE TITLE
Spoolup: Stable vs Dev build

### ISSUE THREAD

**Issue by Sovcat** [flybywiresim/a32nx#5119]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-14T12:47:32+00:00",
  "ref": "master",
  "sha": "5f697b19d622af507ec5ca4854c253d375e105c8",
  "actor": "sidnov",
  "event_name": "manual"
}
```

### Describe the bug

Zero turbine spool until ingitnion.

### Expected behavior

In the stable build, all works normal. Spool starts slowly from APU.

### Steps to reproduce

1. Engage engine start (APU bleed)
2. View engine fan blades
3. No rotation until ignition

### Discord Username (optional)

Sovcat#2083

**Comment by hotshotp** [comment]
thats because we use new custom variables for the engine n1 and n2. The animation is still connected to the old n1, im guessing it is not too hard to fix and will be fixed pretty soon, as I understand all we would need to do is change the variable that the animation follows.

**Comment by hotshotp** [comment]
Not a priority right now. It will be worked on at some point
