### ISSUE TITLE
[BUG] 1FD2 should not have been corrected to 1 FD 2

### ISSUE THREAD

**Issue by Bernister** [flybywiresim/a32nx#512]
**Mod Version**

V0.2.0

**Describe the bug**

V0.2.0 Change note state:-
[FMA] Corrected '1FD2' to '1 FD 2' on FMA

However, there are no spaces on real FMA !

**To Reproduce**

1. Annunciation shown on FMA when FD active. 
2.
3.

**Expected behavior**

Asobo stock code showed it correctly.

**Actual behavior**

Spaces are shown between "1" and "FD" and "2", where there should be none. 

**References**

![image](https://user-images.githubusercontent.com/70965703/92500129-9d348300-f1f4-11ea-8b96-158203d8bf58.png)

**Additional context**

**Comment by veikkos** [comment]
![kuva](https://user-images.githubusercontent.com/24453333/92501457-43898400-f207-11ea-89ec-691712cf2fa4.png)

[This video](https://youtu.be/cv41hm4JEB8?t=94) suggest that the spaces are correct.

**Comment by chkgk** [comment]
It appears there has been a cockpit refresh at some point. Most pictures I can find of the older version (rounded display borders) show "1FD2". The newer onces (square display borders), appear to show "1 FD 2".

new: 
[Airbus A320 Cockpit tour](https://ccntservice.airbus.com/apps/cockpits/a320/)
[Flickr](https://www.flickr.com/photos/103042494@N07/9914931355/)

old:
[Wikipedia](https://commons.wikimedia.org/wiki/File:Primary_flight_display_of_an_A320_during_cruise.jpg)
[Flickr](https://www.flickriver.com/photos/26436024@N06/3566687582/)

The newer version is modeled in MSFS, so I guess the spaces were indeed correct.

**Comment by Bernister** [comment]
I stand corrected, my bad.

It did occur to me after I posted that the NEO may have had a refresh.
Messed up on my first contribution.Sorry.  :-(

**Comment by chkgk** [comment]
I just realized that this issue has been fixed in the current master branch, I verified "1 FD 2" in sim. It is also fixed in #236.
I guess no action is needed and this can be closed (?).
