### ISSUE TITLE
Fuel XFEED doesn't work

### ISSUE THREAD

**Issue by Cassiano-Gunji** [flybywiresim/a32nx#5124]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-15T09:33:40+00:00",
  "ref": "master",
  "sha": "bcdc52c59d7ec4235aaeb0a6036143b6ac0587a6",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

The fuel cross-feed doesn't seem to work. When active, one engine cannot consume fuel from the opposite fuel tank.

### Expected behavior

One engine should be able to consume the fuel from the opposite tank if it has fuel and its pumps are working.

### Steps to reproduce

1. Spawn anywhere with center tank empty or with its pumps turned off.
2. Engage fuel XFEED.
3. Turn off the fuel pumps from one of the wing tanks.
4. The engine from the same wing will not get fuel from the cross-feed and will starve and spool down.

### Discord Username (optional)

CassiKess

**Comment by BlueberryKing** [comment]
I assume this will be fixed once the new fuel system is implemented.

**Comment by 2hwk** [comment]
Repeat of #3120 closing
