### ISSUE TITLE
ILS Frequency not autopopulating in the RADNAV page/

### ISSUE THREAD

**Issue by Cryptic56** [flybywiresim/a32nx#5129]
### Aircraft Version

Development

### Build info

```json
"built": "2021-06-15T09:33:40+00:00",
  "ref": "master",
  "sha": "bcdc52c59d7ec4235aaeb0a6036143b6ac0587a6",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

When I select the ILS in my arrival on the flight plan page, it no longer auto fills the frequency in the RADNAV page. It stopped working after I updated to the latest dev and its not working on the same airports that i can confirm worked before.

### Expected behavior

It should auto populate the ILS Frequency field in the RADNAV page after selecting it in the flight plan page

### Steps to reproduce

Spawn at the gate.
Import or set up a flight plan.
Select arrival ILS
Check RADNAV page

### Discord Username (optional)

Cryptic#4731

**Comment by tracernz** [comment]
Which airports and runways. MS or Navigraph navdata?

**Comment by Cryptic56** [comment]
> Which airports and runways. MS or Navigraph navdata?

Ive tried YPAD 23 and YMML 16. Navigraph Navdata

**Comment by Cryptic56** [comment]
> Which airports and runways. MS or Navigraph navdata?

Also just tried YSSY 34L, didn't work.

**Comment by tracernz** [comment]
You are going past takeoff flight phase before checking right? The FMGC will auto-tune the departure runway (if possible) during preflight and takeoff phase (so you get RWY mode and yaw bar during takeoff roll), and approach runway from climb phase onwards.

**Comment by CoffeePanda0** [comment]
Can agree this has happened to me on about 50% of my flights
I usually check once descending, and again after engaging APPR in the PERF page. Both times, the majority of airports do not tune.
Example is GCTS RWY 07
A large amount of airports in europe do not autotune in the FBW mod but do in the default A320
Using default nav data. Works fine in default A320

**Comment by h-rezaei** [comment]
Happened to me today.
-arrival and star set during climb to EBBR runway 25l.
-checked the rad nav page. no freq was entered
-using navigraph navdata

**Comment by tracernz** [comment]
I talked a bit with Cryptic56 yesterday evening. The navdata for one of the ILS approaches at YMML is missing the ILS navaid. Seeking some further info from Navigraph, although I’m seeing some other strange things that make me think the bad navdata isn’t from them… I will experiment more.

**Comment by AdamNZ** [comment]
I really think this is an airport problem - and not an FBW one.

I used to have the same problem with NZAA and NZWN - but the last few updates fixed it. :)

**Comment by Cryptic56** [comment]
Just tested and it works normally on stable, but not development.

**Comment by Wombii** [comment]
I can confirm autotuning works on the marketplace version but has an issue in the dev version. 
Specifically, the dev version won't autotune if the ILS has a suffix. ILS 24 works fine. ILS 35W, ILS 11Z or ILS 07X does not work on the dev version.

**Comment by wpine215** [comment]
The PR linked above should fix the issue, as it has a better filter for allowing ILS's with suffixes.
