### ISSUE TITLE
[BUG] EMER CANC button visual is glitchy

### ISSUE THREAD

**Issue by veikkos** [flybywiresim/a32nx#513]
**Mod Version**
master

**Describe the bug**
EMER CANC button has weird partial flying cover on it (see screenshot).

**To Reproduce**

1. Just open the aircraft, check EMER CANC button. You may need to play around with light angle a bit.

**Expected behavior**
No glitch on the button.

**Actual behavior**
Glitch on top of the button.

**References**

![kuva](https://user-images.githubusercontent.com/24453333/92507058-13de7a00-f20f-11ea-8dc9-2a93d680afa8.png)

**Additional context**

**Comment by konjakk** [comment]
Here is a real A320 ECAM panel. As you see there is a clear cover over the EMER CANC switch.
![A320 ECAM PANEL (2)](https://user-images.githubusercontent.com/70980278/92527605-8f4c2580-f227-11ea-9e6f-ae37897baa98.jpg)

**Comment by veikkos** [comment]
Ok, thanks. I took a better look zooming and the lid also has a faint hinge which I missed. In the light I saw it made it look like there is just floating glass. Closing.
