### ISSUE TITLE
AP2 no longer working during approach

### ISSUE THREAD

**Issue by martialblaizot** [flybywiresim/a32nx#5130]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-15T09:33:40+00:00",
  "ref": "master",
  "sha": "bcdc52c59d7ec4235aaeb0a6036143b6ac0587a6",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

While approaching an airport for an ILS approach, both localiser and glideslope are active and the ILS frequency is entered in the MCDU but when AP2 is pressed it keeps switching from one AP to the other but do not lit together. I have tried uninstalling and reinstalling FBW A32NX by making sure nothing was in the community folder while installing as advised but still not working. 

### Expected behavior

During approach and for ex for autoland if all conditions are met as above both AP should be able to activate together 

### Steps to reproduce

Tried once and thought I might have forgotten something (I was then using exp version)
Tried again and did not work and been advised to use dev version instead
After full reinstall tried again with dev version. Still nothing

**Comment by aguther** [comment]
Did the FMA show LOC and G/S blue or was any of those mode engaged (shown in green)?

**Comment by martialblaizot** [comment]
Hi

I tried when they were blue and the diamonds were moving into place and it didn’t engage. I then waited until loc and GS were green and tried again but it did not engage either.

Martial

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by aguther** [comment]
I will try to reproduce it in the evening.

**Comment by martialblaizot** [comment]
Thanks very much!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by aguther** [comment]
There was no change on the AP for days and when I did my last tests everything worked.

Would it be possible that you do and share a video / screenshot of it?

**Comment by martialblaizot** [comment]
Yes of course I am not sure how to do that but I will look into it. I am going to test it again today. Don’t get me wrong maybe it is me who has done something wrong but I really can’t see what it is. I will try and send you a screen shot.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by aguther** [comment]
We will find it out…

**Comment by tracernz** [comment]
Just tried it and seemed good to me.
{
  "built": "2021-06-16T06:50:04+00:00",
  "ref": "HEAD",
  "sha": "b2d7668d7dcbef695cf7462635c9800234b5967c",
  "actor": "BBK <22713769+BlueberryKing@users.noreply.github.com>",
  "event_name": "manual"
}

![20210616203005_1](https://user-images.githubusercontent.com/9995998/122186348-1084c700-cee2-11eb-8c76-ea3116a2beed.jpg)

**Comment by martialblaizot** [comment]
Hi Andreas,

Just to let you know I have done another flight today and tried to use the AP2 again. So far I had no luck. Hopefully you will be luckier than me 😊

Martial

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by aguther** [comment]
Screenshot?

**Comment by aguther** [comment]
If fear it will work for me…

**Comment by martialblaizot** [comment]
Oh yeah shoot I forgot about the screenshot!! I will do another flight now and try again. Is there any particular conditions that I am not aware of for the AP2 to engage? I am really confused as to why it would work with you and not with me…..

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by aguther** [comment]
The condition is that you arm/engage APPR, so the green light of that button on the FCU must be on. Then you can engage both autopilots….when that light is off no second autopilot.

**Comment by martialblaizot** [comment]
Yep that’s fine that was on as well. I am doinf a descent now so will send you a screenshot when on final approach.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by aguther** [comment]
Ok

**Comment by martialblaizot** [comment]
Hi Andreas,

There are the screen shots I have taken just now…As you can see, in the fist picture the AP1 is on as well as the APPR armed, both loc and GS are green. In the second picture I have pressed AP2 but AP1 then turns itself off… the nav frequency in the third picture is entered as it should. I am really confused as to what I am doing wrong. I will have to send you the screenshots all separately as otherwise it is too big and it won’t send sorry about ***@***.***D762E3.92F30FA0]


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by martialblaizot** [comment]
***@***.***D762E3.9B8F5880]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by aguther** [comment]
No pictures here, please attach it directly on GitHub and not via E-Mail

**Comment by aguther** [comment]
https://www.youtube.com/watch?v=r-kPbIydFXg

**Comment by aguther** [comment]
FYI, this is how it looks like for us on GitHub:
![image](https://user-images.githubusercontent.com/6629914/122283693-1a5ff780-ceed-11eb-8ed9-aacbee85a545.jpeg)

**Comment by martialblaizot** [comment]
Here are the screen shots you were asking for.
![Screenshot (5)](https://user-images.githubusercontent.com/57486169/122458441-b5b5a300-cfa7-11eb-94f1-cafe0cd29490.png)
![Screenshot (6)](https://user-images.githubusercontent.com/57486169/122458493-c5cd8280-cfa7-11eb-8803-22d66ba7ee0c.png)
![Screenshot (7)](https://user-images.githubusercontent.com/57486169/122458540-d54ccb80-cfa7-11eb-9045-aa26d63cb6fc.png)
I really don't understand what I am doing wrong. I have been using A319/A320 for years I am so confused...

**Comment by aguther** [comment]
You’re using the stable version. I see that on the PFD.

**Comment by martialblaizot** [comment]
Even left the altitude as managed (with the dot next to it) today and tried again but it would not work either...

**Comment by martialblaizot** [comment]
Really?????

**Comment by martialblaizot** [comment]
If I open the FBW installer it says it is the dev version....huh i am going to look again

**Comment by aguther** [comment]
Yes it’s for sure. Look closely on the PFD…the new PFD has all the green normal law protection marks…

**Comment by martialblaizot** [comment]
![Screenshot (8)](https://user-images.githubusercontent.com/57486169/122459331-bac72200-cfa8-11eb-9e19-261582120508.png)
That is so weird....

**Comment by aguther** [comment]
Have you also installed it via marketplace once?

**Comment by Benjozork** [comment]
Are you sure the installer is using the right Community folder ? Especially if you reinstalled the sim.

**Comment by aguther** [comment]
I agree that’s strange…

**Comment by martialblaizot** [comment]
No actually I have done it via the installer not marketplace..

**Comment by aguther** [comment]
![image](https://user-images.githubusercontent.com/6629914/122459543-565c9080-cfb1-11eb-8689-7b9770a88c33.jpeg)![image](https://user-images.githubusercontent.com/6629914/122459561-5bb9db00-cfb1-11eb-876b-142f42912a16.jpeg)

**Comment by martialblaizot** [comment]
![Screenshot (9)](https://user-images.githubusercontent.com/57486169/122459664-1691ab00-cfa9-11eb-8e9d-4d8ea0840b10.png)

**Comment by martialblaizot** [comment]
This is the way it is supposed to look like right?

**Comment by aguther** [comment]
Did you install it via marketplace at any point in time?

**Comment by martialblaizot** [comment]
Let me try and uninstall and install again via marketplace. That might change things around. Sorry about this guys I must sound like a complete nutjob lol

**Comment by martialblaizot** [comment]
> Did you install it via marketplace at any point in time?

Nope

**Comment by aguther** [comment]
No not marketplace then you get stable. Sorry overseen your response.

**Comment by aguther** [comment]
Uninstall it completely and remove the directory then install the dev version.

**Comment by martialblaizot** [comment]
> Uninstall it completely and remove the directory then install the dev version.

Via market place or the installer?

**Comment by martialblaizot** [comment]
> Uninstall it completely and remove the directory then install the dev version.

I will do that. I never actually uninstalled it completely I just removed the directory so maybe that is why it never got rid of it compltely. I will try again. Thank you Andreas

**Comment by Benjozork** [comment]
We recommend sticking to our installer.

**Comment by aguther** [comment]
Let us know if it worked

**Comment by martialblaizot** [comment]
I looked into market place. I had one installed via marketplace and one into the community folder via the installer in my list which I think is why the stable version took priority over the community folder. I am reinstalling it now only via the installer. I will try again and I think that is where the issue came from, I will let you know. Thanks a lot for your help.
