### ISSUE TITLE
No N1% display

### ISSUE THREAD

**Issue by St54Kevin** [flybywiresim/a32nx#5132]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-15T09:33:40+00:00",
  "ref": "master",
  "sha": "bcdc52c59d7ec4235aaeb0a6036143b6ac0587a6",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

No N1 indication throughout the whole flight (C&D to parking)

### Expected behavior

N1 display

### Steps to reproduce

After a PR test, I reinstalled master via the installer. The flight was the first flight after this install, without any reloading.
I just quickly checked wether a new spawn on a RW will fix it. But still the same
So really hard to reproduce or tell, what caused this.

### References (optional)

After start. Both ENG running
![image](https://user-images.githubusercontent.com/448627/122177101-96bef000-ce85-11eb-8b37-1a3c75fa0314.png)

After takeoff
![image](https://user-images.githubusercontent.com/448627/122177136-9d4d6780-ce85-11eb-9100-92a59baea771.png)

**Comment by aguther** [comment]
Hmm, did also a fresh install via installer today and it worked without issues. Was this one time are permanently?

**Comment by St54Kevin** [comment]
> Hmm, did also a fresh install via installer today and it worked without issues. Was this one time are permanently?

It was a permanent issue on any airport with any weather. Just did a full reinstall of the mod (folder delete and reinstall) and that fixed the issue.
