### ISSUE TITLE
Cold & dark issue : EXT PWR does'nt work with batteries 0V

### ISSUE THREAD

**Issue by SmallHead95** [flybywiresim/a32nx#5136]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-06-16T09:59:28+00:00",
  "ref": "master",
  "sha": "5b6ecdf1c75a95ae843a7132ea95b1ed3a44d3d1",
  "actor": "MisterChocker",
  "event_name": "manual"
}
```

### Describe the bug

Hello

During a cold & dark start, EXT PWR button has no effect as the batteries are to 0.0V. So it is impossible to start the Flybywire A320.

![Capture d’écran 2021-06-16 161543](https://user-images.githubusercontent.com/86006292/122235799-46b04f80-cebe-11eb-8b14-2de516a59b58.png)

It occurs with both Stable & Dev A320Nx.
It does'nt occur with standard A320 from ASOBO.
I have no other mods in my community folder.

I tried the Flybywire recommandation herebelow. Actually it solves the issue but when I use the Beta UTF-8, I have other issues such as ATF not working.

_Autopilot, FADEC, electrical system unwanted behavior
In rare cases the above mentioned systems may not start or behave erratically. This is in part due to UTF-8 language support beta not enabled on your machine.
Solution:

> - Open Windows Control Panel -> Region.
> - Go to the Administrative tab and click Change system locale...
> - Make sure the check mark next to Beta: Use UTF-8 for worldwide language support is selected.
> - Click OK and restart your computer._

Thank you for helping

### Expected behavior

Batteries should be 25.4V by default during a cold & dark start. 

### Steps to reproduce

During a cold & dark start

**Comment by davidwalschots** [comment]
> I have other issues such as ATF not working.

Could you tell me what ATF is?

**Comment by MisterChocker** [comment]
Closing since no response from the op.
