### ISSUE TITLE
Include ANN LT TEST in the checklist

### ISSUE THREAD

**Issue by davidwalschots** [flybywiresim/a32nx#5138]
### Aircraft Version

Development

### Description

The ANN LT TEST should be included in the MSFS checklist.

This issue is created to split up the remaining items in #528 so they can be individually tracked.

### Discord Username (optional)

SjotgunSjonnie#9623

**Comment by BlueberryKing** [comment]
Hey, is there a specific position you want the item to be? I don't have a reference, but I think somewhere in the preliminary cockpit prep. would make sense. Maybe between "External power" and "APU Fire Test"?

![checklist](https://user-images.githubusercontent.com/22713769/122685618-cfa3ef80-d20c-11eb-810b-c18a165fd634.png)

**Comment by davidwalschots** [comment]
No. I have no opinion about this issue at all. The only reason for me to create this issue was so that it could be individually tracked, as opposed to being tracked within #528 as one of its many items.

**Comment by BlueberryKing** [comment]
Ok, thank you for your quick response. Tagging @AdenFlorian to if he has a reference. I don't see a reason to have it in the checklist otherwise.

**Comment by bouveng** [comment]
Hi All!

In my extensive checklist it sits in the `COCKPIT PREPARATION` section as the last point related to light setup, just after `EMERGENCY EXIT LIGHTS ... ARM`

![checklist](https://user-images.githubusercontent.com/433429/124521530-1fc7a800-ddf0-11eb-86be-d2e9e3817c47.png)

**Comment by davidwalschots** [comment]
@bouveng you made this checklist yourself, correct?

**Comment by bouveng** [comment]
> @bouveng you made this checklist yourself, correct?

@davidwalschots Ish. I took something someone else done, and cut it up into one long one suited for my iPad, and made it dark. I wanted a pretty "complete" one and this was what I find. So yes, no, I cant verify its validity.
