### ISSUE TITLE
BUG  App disengage  when AP off and loc engage 

### ISSUE THREAD

**Issue by griffon55** [flybywiresim/a32nx#514]
**master**

**when I disengage autopilot app disengage and loc engage itself**

**To Reproduce**

1.
2.
3.

**when disengage autopilot app must stay engage and no loc engage**

**Actual behavior**

**References**

**Additional context**

**Comment by Benjozork** [comment]
You didn't write anything in the issue.

**Comment by SmithFR** [comment]
Duplicate of #146 and #323

**Comment by griffon55** [comment]
I tried but no text appear. Anyway problem  is in the title

**Comment by Benjozork** [comment]
> I tried but no text appear. Anyway problem  is in the title

You need to provide all the required information. it is needed to help us reproduce the problem.

**Comment by griffon55** [comment]
https://s.amsu.ng/S05LqvE791oN

**Comment by tareksabet** [comment]
closing now it's fixed by #1715
