### ISSUE TITLE
False "AUTO" condition to trigger Transponder Mode C

### ISSUE THREAD

**Issue by chromkoo** [flybywiresim/a32nx#5145]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2021-05-05T06:28:31+00:00",
  "ref": "experimental",
  "sha": "ff7f81fbff658ba8a69c77f6a16754ad1bffabea",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

When Transponder mode "AUTO" is enabled, it switches to Mode C when **both engines spool up.**
It disables Mode C when **both engines shut down.**

This especially is important for Vatsim or any kind of online network since it can cause conflicts on ATC's radar.

### Expected behavior

When Transponder mode "AUTO" is enabled, it switches to Mode C when **becoming airborne.**
It disables Mode C when **being on ground (again).**

_For reference: To be more specific, "AUTO" mode should force the transponder to activate Mode S when being on the ground  and activate MODE A and C when being airborne... but I'm not even sure whether Mode S is implemented in modern online networks. For now, i think just changing the condition of Mode C should be fine._

### Steps to reproduce

Simply set Transponder Mode to "AUTO" and check when Mode C triggers with appropriate software.

→ Start the engines, you should notice Mode C enabling.
→ Stop the engines, you should notice Mode C disabling.

You can use vPilot to track the status of Mode C (at least i did).

### References (optional)

https://forum.aerosoft.com/index.php?/topic/138514-a320-ultimade-aktivierung-atctcas/
https://www.flightforum.ch/board/topic/96594-transponder-panel-im-a320-funktionen/

(Those are german threads but they explain it very well and simple.)

### Additional info (optional)

The fix should be pretty easy to implement since the condition of being airborne is already defined somewhere else due to some features like the landing gear depending on this condition (you can't retract the landing gear while being on the ground).

### Discord Username (optional)

lǝnuɐɯ#6153

**Comment by solarisfire** [comment]
Experimental hasn't been updated since the 4th May.
Switching to Development will give you newer features.

However, I don't think I've seen any transponder changes in a while. This would actually be pretty handy for VATSIM, although I tend to just set Mode C manually out of habit.
