### ISSUE TITLE
the ailerons do not work for keyboard devices

### ISSUE THREAD

**Issue by airman50** [flybywiresim/a32nx#5148]
### Aircraft Version

Development

### Build info

```json
"built": "2021-06-16T09:59:28+00:00",
  "ref": "master",
  "sha": "5b6ecdf1c75a95ae843a7132ea95b1ed3a44d3d1",
  "actor": "MisterChocker",
  "event_name": "manual"
```

### Describe the bug

the side stick does not move to the left or the right and the ailerons do not move when I presss the bank left button on the keyboard and the bank right

### Expected behavior

i expected the sidestick to move left and right and the ailerons to move accordingly 

### Steps to reproduce

use a keyboard and press bank left and bank right

### Discord Username (optional)

AirMan#5967

**Comment by Valastiri** [comment]
https://docs.flybywiresim.com/start/autopilot-fbw/

This should probably be relevant 
![image](https://user-images.githubusercontent.com/1619968/122571855-c20d2f00-d07f-11eb-90d3-3f8f4b875968.png)

**Comment by tracernz** [comment]
Microsoft/Asobo bug unfortunately. If/when the events become available for our use the bug can be re-opened.
