### ISSUE TITLE
SIDs and STARs for KLGA not showing up

### ISSUE THREAD

**Issue by Thingyman-DEV** [flybywiresim/a32nx#5150]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-16T09:59:28+00:00",
  "ref": "master",
  "sha": "5b6ecdf1c75a95ae843a7132ea95b1ed3a44d3d1",
  "actor": "MisterChocker",
  "event_name": "manual"
}
```

### Describe the bug

When I try to fly into or out of KLGA, all the SIDS and STARS are missing.

### Expected behavior

The proper SIDS and STARS should appear in the MCDU

### Steps to reproduce

1. Spawn into KLGA
2. In the INIT menu, set the route to KLGA to anything
3. In F-PLN, click on KLGA
4. Select DEPARTURE
5. Pick any runway
6. See that there are no SIDs

Same idea with arrivals and same result

### References (optional)

![image](https://user-images.githubusercontent.com/67653706/122614673-1ea72480-d055-11eb-84ce-db7e879911e1.png)
![image](https://user-images.githubusercontent.com/67653706/122614779-4b5b3c00-d055-11eb-972c-806d3b04d735.png)

### Discord Username (optional)

Thingyman#5841

**Comment by tracernz** [comment]
MSFS or Navigraph navdata? Add-on scenery?

**Comment by Thingyman-DEV** [comment]
I have tried both MSFS data and Navigraph data and I do use KLGA scenery

**Comment by alex-johnson** [comment]
I’m constantly having the same issue with add on scenery and navigraph data. Nothing to do with a32nx though.

Good news is there is a fix. Check out this thread:
https://forum.navigraph.com/t/no-sid-or-stars-at-kord/4763/3

**Comment by CptBayer** [comment]
from navigraph all steps to do:


 close the sim
 IMPORTANT!! open our “Navigraph Navdata Installer” and remove the installed AIRAC cycle
 make sure, that you have installed the latest “Navigraph Navdata Installer”, when not uninstall the Installer (via the normal Windows10 functionality “Add or remove programs”) and install the newest one - you can download the newest installer from here 133
    delete the content.xml file - depending on your installation (Steam or Marketplace) you find here 219 the corresponding folder, where this file is located
    start the sim
    close the sim again
    start our “Navigraph Navdata client” and install the AIRAC cycle again
    start the sim and enjoy your flights

**Comment by Thingyman-DEV** [comment]
I tried that and it did not work, the only fix was no more scenery. It’s ok I guess

**Comment by MisterChocker** [comment]
Closing since issue resolved and we are aware of these issues.
