### ISSUE TITLE
fly by wire bug

### ISSUE THREAD

**Issue by captinalex** [flybywiresim/a32nx#5152]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-05T06:28:31+00:00",
  "ref": "experimental",
  "sha": "ff7f81fbff658ba8a69c77f6a16754ad1bffabea",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

the bug i found on the develementsl version is that on my pfd it flickers and on my nd the nave line blinkes second when i deploy my flap to max and i have spolilers they retract 

### Expected behavior

for them to fix it and me being able to get flying again

### References (optional)

.

### Additional info (optional)

.

### Discord Username (optional)

captin alex

**Comment by scoopscode** [comment]
I am very very confused as to what the actual issue is. I highly suggest you visit the Discord #support channel for instant support as it seems that this is an urgent bug that requires support quickly.

**Comment by Benjozork** [comment]
This does not really follow what we ask in the template, "fix it" is not expected behaviour.

Also, your title is unrelated to the description. Closing.

By the way, the experimental version is discontinued as all the features are in dev now. This means your build is months old now.
