### ISSUE TITLE
Installation is not working

### ISSUE THREAD

**Issue by schoonhein** [flybywiresim/a32nx#5155]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-05-05T23:03:06+00:00",
  "ref": "v0.6.1",
  "sha": "4a1cccc90ab3997109e394402ab9b41a80fbf325",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

My installation is not working. I've tried everything (i think). 
- Install via installer
- Tried manual installation
- Checked where Community folder is via Developer mode.
![Knipsel](https://user-images.githubusercontent.com/59023435/122637618-fddfdd00-d0ef-11eb-9e4b-fbc4e4062be5.PNG)

Please help! It has worked, but after reinstalling FS2020 a32nx stopped working...

### Expected behavior

I excpected it to work...

### Steps to reproduce

I reinstalled FS2020

### References (optional)

![Knipsel2](https://user-images.githubusercontent.com/59023435/122637678-531bee80-d0f0-11eb-82b3-593949a79ed6.PNG)

### Discord Username (optional)

schoonhein

**Comment by BlueberryKing** [comment]
> Please help! It has worked, but after reinstalling FS2020 a32nx stopped working...

What do you mean by this? Is the aircraft not showing up in-game? A32NX is a separate aircraft now. Make sure to select that and not the default A320neo from Asobo.

**Comment by schoonhein** [comment]
When I select a a320 neo it is the defaut a320

**Comment by Benjozork** [comment]
You need to select the FBW A32NX specifically, it's not overriding the default anymore.

**Comment by schoonhein** [comment]
But it’s not among my liveries…?

**Comment by tracernz** [comment]
> 
> 
> But it’s not among my liveries…?

No, it's an entirely separate aircraft, under FlyByWire Simulations A320neo (LEAP), rather than Airbus A320neo (that is the Asobo A320). Liveries can be found at https://flightsim.to/c/liveries/flybywire-a32nx/

**Comment by schoonhein** [comment]
Yes that was it!!! Thanks so much. 👍

**Comment by MisterChocker** [comment]
Closing since issue resolved
