### ISSUE TITLE
Additional F/O EFB for Shared Cockpit use

### ISSUE THREAD

**Issue by Phil7789** [flybywiresim/a32nx#5156]
### Aircraft Version

Development

### Description

If possible (performancewise) a second EFB would be a nice addition for shared cockpit simmers. While the PF might have opened e.g. approach charts the PM could read out the checklist without switching the PF tabs in the EFB.

I don't know if the code is able to handle arrays so different information could be cached, e.g. if one EFB has opened the TOD calculator, the second EFB doesn't need to do the same calculations if a different page is opened.

I think this would be a late implementation (if applicable at all) as there are more important features before this with an already available EFB.

### Discord Username (optional)

Phil7789#0191

**Comment by tracernz** [comment]
Duplicate #4008
