### ISSUE TITLE
(new) shime fades out to quick

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#5157]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-19T04:23:24+00:00",
  "ref": "master",
  "sha": "ff9f83e498bfbfd90edd3335f99daf1575fcd5fd",
  "actor": "wpine215",
  "event_name": "manual"
}
```

### Describe the bug

after the new sound-update i recognize, that the Shime fades out to quick compared to the previous version. To my mind the previous version was the more realistic one. I work on an A319/A320 and I hear it every day a couple of times. It would be nice to have the old one back to have more realism. 

### Expected behavior

old shime was the more realistic one

### Steps to reproduce

1. compare old to new

**Comment by hotshotp** [comment]
The old one was a sine wave and sounded very flat. The new one is a bit of a shorter one but an actual recording. I guess I can make it a bit longer by slowing down the tempo of it or something for next update
