### ISSUE TITLE
[REQUEST] Systems lose power when external power is pulled without APU

### ISSUE THREAD

**Issue by Zyonix007** [flybywiresim/a32nx#516]
**Is your feature request related to a problem? Please describe.**

If GPU power is pulled when the apu or engines are off and the aircraft is on the ground the plane will lose IRS and core system functions 

**Describe the feature you'd like to see implemented**

The FO and main IRS should all fail and the systems should lose hydraulics 

**References**

https://www.youtube.com/watch?v=djd7f_azfiI

See aircraft lose systems when both engines are lost 

**Additional context**

**Comment by UncleClapton** [comment]
Was able to replicate. Investigating

**Comment by UncleClapton** [comment]
This is actually a bug with power systems, and not expected behavior. Was able to replicate and I have already found a fix for it.
