### ISSUE TITLE
Auto break button not working

### ISSUE THREAD

**Issue by regisbiass** [flybywiresim/a32nx#5160]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-19T04:23:24+00:00",
  "ref": "master",
  "sha": "ff9f83e498bfbfd90edd3335f99daf1575fcd5fd",
  "actor": "wpine215",
  "event_name": "manual"
}
```

### Describe the bug

Just clicking on the auto break (1,2 or max) button does not work.

See video I have made for your perusal:

https://youtu.be/UTeMHWUrtPY

### Expected behavior

For auto break to work.

Auto break  button for 1,2 or Max is not working.

### Steps to reproduce

Click auto break button (any level  -  1, 2 or max)

**Comment by Illuminati270** [comment]
A320 IRL is not supposed to ARM A/BRK MAX in-flt. LO and MED should work, though...

**Comment by regisbiass** [comment]
Hey mate,

I have downloaded the latest dev as of today (25/06/2021, time 21:30 BST). The issue is always same.

Problem:

  1.  I cannot arm AUTO BREAK to max for take off
  2.  I cannot arm AUO BREAK to 1 or 2 or max for Landing

Please advise.  The issue is frustrating  at best.

Many thanks,


Best Regards,

Regis Biassala

Tel: 00353864052190

________________________________

**Comment by BlueberryKing** [comment]
This seems like a keybinding issue to me. Check your settings to make sure that only the keys you want to use for auto brake are bound to it. Also, try unbinding all auto brake keybindings and checking if just activating it with your mouse works.

**Comment by MStallen** [comment]
In my case it's possible to set the autobrakes. Works for RTO (with trick that MAX isn't disabled when applying brakes). But in the air it's possible to set lo en med (via FSUIPC setting the LVAR to 1 or 2 (XMLVAR_Autobrakes_Level)) but no autobraking on landing and no decel light (can't find the lvar for this one either (A32NX_AUTOBRAKES_ACTIVATED, A32NX_AUTOBRAKES_BRAKING do not change).
If I set MED or LO on the screen still no autobraking occurs.

**Comment by regisbiass** [comment]
Hi,

I am just giving up...I am not the only person having this issue.

On the ground, before take off AUTOBRAKE set MAX. ....This does not work.

On approach, set AUTOBRAKE to LO or MED or MAX, nothing work.

I give up.

Thankw

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Saschl** [comment]
@MStallen XMLVAR_Autobrakes_Level only controls the light, not the actual autobrake system unfortunately. You can use the default sim events, they work fine now. 

@regisbiass something really seems to interfere. Try without any external tools and double check any keybinds please.

**Comment by regisbiass** [comment]
oK -  I have narrowed it down to my TCA Airbus Thrust which has the add-ons for flaps and autobrake......but looking at assigned I can't still figure out where is the issue.

I will update as soon as I found out.

I changed my mind   - I am NOT giving up.


Best Regards,

Regis Biassala

Tel: 00353864052190

________________________________

**Comment by regisbiass** [comment]
Issue is now fixed.  AUTOBRAKE on the TCA was set to BTV  instead of DISARM....My Daugther playing with my stuff.  I need to move house.

Thanks

Best Regards,

Regis Biassala

Tel: 00353864052190

________________________________

**Comment by MStallen** [comment]
Hee super news. Gonna try that again tomorrow. Does that also fixex that using the brakes doesn't reset the autobrake max before take-off anymore?



Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Comment by regisbiass** [comment]
Yes....everything is working as expected.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Benjozork** [comment]
Great to hear. Will close the issue then. Safe skies.
