### ISSUE TITLE
Full Reverse Thrust when Thrust Levers at idle

### ISSUE THREAD

**Issue by mipla23** [flybywiresim/a32nx#5165]
### Aircraft Version

Development

### Description

I noticed thrust lever behavior has been changed to apply reverse thrust when hardware input is near 0.
This is not working well for me because my hardware levers are now too sensitive. It often accidentally moves the thrust lever out of climb power or even initiates go around on approach when I press a button on my hardware throttle levers. (Saitek X56 Hotas)
I see the benefits for users with other hardware controllers, but the way it worked before (one hw axis as thrustlever and a button to change to reversers) was much better for me.
I'd suggest a option to switch to the "old" behavior.

Regards
Michael

And, hey, I also want to thank all the devs for their amazing work!

### References (optional)

![Screenshot 2021-06-20 152801](https://user-images.githubusercontent.com/28810691/122676057-7d4ada80-d1dc-11eb-80f4-55b2333cb3cc.png)
Hardware Levers at 0%

![Screenshot 2021-06-20 152924](https://user-images.githubusercontent.com/28810691/122676060-820f8e80-d1dc-11eb-88d6-b8347f52a84b.png)
Hardware Levers at ~20%

![Screenshot 2021-06-20 153744](https://user-images.githubusercontent.com/28810691/122676242-8c7e5800-d1dd-11eb-9c10-d2b893ec72b1.png)

### Discord Username (optional)

mipla23

**Comment by Illuminati270** [comment]
Open up the EFB and try to calibrate for your thrust levers =) See if works.

**Comment by muddyfunkster** [comment]
i set my thrustmaster throttles to idle then moved cockpit throttles from rev to idle then calibrated it

**Comment by MisterChocker** [comment]
Maybe this helps calibrating your detents https://www.youtube.com/watch?v=8yZuv2L4jPA

**Comment by mipla23** [comment]
Thank you very much for the answers.
I haven't seen the calibration page in the EFB before. That's exactly what I was looking for.
