### ISSUE TITLE
Sim crash due to MCDU operation - NDB approach

### ISSUE THREAD

**Issue by Iukki** [flybywiresim/a32nx#5167]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-20T10:23:56+00:00",
  "ref": "master",
  "sha": "84964e339507e06694ff2e96bdda518824c85aa4",
  "actor": "MisterChocker",
  "event_name": "manual"
}
```

### Describe the bug

I was about to descend down to Ibiza (LEIB) airport when the sim crashed due to MCDU operation.

I had an approach (LEIB, RW 24, ILS X), STAR and FINAL, dialled in the MCDU when I decided to go for an NDB approach. In the MCDU I selected FPLAN/LEIB/Arrivals/NDB RW24 but when I pressed NO TRANS, the simulator crashed without delay.

### Expected behavior

DISCLAIMER! I am definitely not an expert on Airbus aircraft so my prediction may not be accurate or even close.

If I remember correctly, there was some sort of transition selected by default but I wanted to get rid of it. By pressing "no transition" it should have deleted the transition, not crash.

### Steps to reproduce

1. Preselect an ILS X approach for RW 24 (LEIB)
2. Be on an approach to LEIB (TOLSO 5N, directing GISLU, about 50 NMs out)
2. FPLAN/LEIB/Arrivals/NDB RW24
3. Select NO TRANS

### Discord Username (optional)

Iukki#4228

**Comment by Benjozork** [comment]
MSFS bug
