### ISSUE TITLE
Nose gear lock 

### ISSUE THREAD

**Issue by Zyonix007** [flybywiresim/a32nx#517]
**Is your feature request related to a problem? Please describe.**

Let us lock the nose gear with a button 

**Describe the feature you'd like to see implemented**

![Microsoft Flight Simulator Screenshot 2020 09 08 - 13 50 10 54](https://user-images.githubusercontent.com/60050366/92510779-59cd1b00-f1da-11ea-8cb0-06356f4cacff.png)

When pressed in the button will lock the nose gear from moving and only will control the rudder 

**References**

https://www.youtube.com/watch?v=yo4tzTgdJwI

4:15

**Comment by crocket63** [comment]
I'd say this is now solved from tiller update
