### ISSUE TITLE
Engine keeps jumping.

### ISSUE THREAD

**Issue by xusmcxjasonx** [flybywiresim/a32nx#5171]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-20T10:23:56+00:00",
  "ref": "master",
  "sha": "84964e339507e06694ff2e96bdda518824c85aa4",
  "actor": "MisterChocker",
  "event_name": "manual"
}
```

### Describe the bug

Engine keep jumping from normal speed to around +20 or so knots

### Expected behavior

Normal autopilot operation

### Steps to reproduce

Normal flying here from cold and dark at the ramp to takeoff.

### Discord Username (optional)

J. Mullins#0001

**Comment by Benjozork** [comment]
Can you please record a video of the issue with PFD and upper ECAM visible ?

**Comment by xusmcxjasonx** [comment]
Here you go: https://drive.google.com/file/d/17NOESYMgOo9bT0XafOgVX2qwYvcVwpbS/view

**Comment by Illuminati270** [comment]
> Here you go: https://drive.google.com/file/d/17NOESYMgOo9bT0XafOgVX2qwYvcVwpbS/view

Hi @xusmcxjasonx

I'm no code expert, but I can assure you that exactly the same would happen if you were to face the same temperature change flying the real aircraft.

The SAT happened to jump from -56C to -34C in a split of a second, thus affecting everything else influenced by temperature itself. Try to turn Live WX off and see if it still happens.

**Comment by hotshotp** [comment]
yes this is clearly the issue of the temperature, so not a32nx related

**Comment by tracernz** [comment]
Is this with REX weather? MSFS default live weather seems reasonably good at smoothing weather changes.
