### ISSUE TITLE
Throttle Calibration in FlyPad not appearing in Settings page.

### ISSUE THREAD

**Issue by EDZET9428** [flybywiresim/a32nx#5172]
### Aircraft Version

Development

### Build info

```json
Development version 84964e3. Clean full module install.
```

### Describe the bug

The Flypad doesn't recognise my Honeycomb Bravo Throttle quadrant is connected to MSFS. Hence when opening up the settings on the Flypad there is no throttle calibration section as expected under the Audio tab. I installed the Dev version clean from the start by deleting the A320NX folder in Community. This was supposed to fix the issue for some.
My throttles are actually working OK in the sim and the calibration is not bad anyway, perfectly flyable. 
I do have other software running which may affect the issue.
Brunner CLS NG yoke.  Lorby Si OHS, Go Flight Interface tool by Pollypot. All of which work perfectly with the FBW A320.

### Expected behavior

The Flypad should show a throttle calibration app on the settings page, however, all I see is the Audio settings and under that is the brightness slider.

### Steps to reproduce

1. Position FBW A320 at GCXO Gate 15 Small and power up the aircraft with battery master 1 and 2 on and ground power.
2. Fire up FlyPad and open the settings page.
3. Note the absence of throttle calibration app.

### Additional info (optional)

I have never had this app working yet. My Bravo is new. The calibration app has never shown up before or since I bought it.

**Comment by Benjozork** [comment]
You are probably running the Stable version, probably because you installed from the marketplace after installing from the installer, OR your community folder setting is wrong in the installer.

**Comment by EDZET9428** [comment]
No I'm running the Development version noted above which I installed from fresh this morning. The Installer is finding my Community folder just fine.

**Comment by Benjozork** [comment]
The development version does not detect any throttles and it shows the calibration page regardless of what hardware you have.

Can you show a screenshot of your PFD ?

**Comment by EDZET9428** [comment]
I can get one tomorrow now. And I'll copy and paste the build info json data too.  Everything is disconnected at the moment.

**Comment by aguther** [comment]
Please ensure that in your official store folder (`Official\OneStore` instead of community) no A32NX is present. When you once downloaded the A32NX through the marketplace and didn't remove it, it takes precedence whatever you put in community folder.

Was the same with this:
#5130

**Comment by EDZET9428** [comment]
Yes, this is exactly what has happened. I went to the Content Manager and uninstalled the A32NX by deleting it. Went to my Community folder and removed the Flybywire A320 neo from there. Ran the installer again and bingo, issue sorted. Is the plane settings side of the screen greyed out on purpose ? 
![2021-06-21 (1)](https://user-images.githubusercontent.com/70298738/122795092-df770e80-d2b4-11eb-99b8-346d0352126d.png)

**Comment by Benjozork** [comment]
Yes, they are not implemented there yet, but rather in the MCDU at the moment

**Comment by EDZET9428** [comment]
Fantastic support guys. I had a reply within 2 minutes of posting the issue and it was early hours of the morning. This is becoming one of my all time favourite FS aircraft and to be honest I wasn't really an Airbus fan, I cut my teeth on PMDG Boeing aircraft. You are right up there now.

**Comment by aguther** [comment]
Great to hear!

My understanding is that you issue is solved, therefore I close the issue.
