### ISSUE TITLE
Cargo door opens faster than IRL

### ISSUE THREAD

**Issue by tush0701** [flybywiresim/a32nx#5175]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-20T23:50:13+00:00",
  "ref": "master",
  "sha": "85470d645814125ff79304bfd19a438e721c736d",
  "actor": "MisterChocker",
  "event_name": "manual"
}
```

### Describe the bug

The new sound of the hydraulic cargo door opening and closing is very realistic, but the speed of the cargo door opening and closing is very fast

### Expected behavior

Cargo Door open/close animation should be a bit slower

### Steps to reproduce

1. Load A32NX at any airport parking/gate
2. Look at the cargo door using external/wing/drone(any) view
3. Call for luggage, or open cargo door using PushbackHelper(3rd party, so not recommended)
4. Door opens within 2 - 3 seconds, whereas sound lasts accurately.

### References (optional)

https://www.youtube.com/watch?v=a2k4i_Su__o

Cargo door opens slower IRL

### Additional info (optional)

This could qualify as an enhancement, so if required, you may change the tag please.

### Discord Username (optional)

tbone0793

**Comment by hotshotp** [comment]
Okay so two things:

1. You are correct about the cargo door opening too fast, it should not be 2-3 seconds. As far as I know our hydraulics modeller is looking for a way to slow it down.

2. The sound of it, the yellow electric pump still lasts several seconds after the door has been opened, so even with realistic opening speeds it will stay running for a bit after fully opening/closing

**Comment by tush0701** [comment]
Point no. 2 is perfect. Looking forward to fixing on point 1.😃
Thank you.

**Comment by davidwalschots** [comment]
@crocket63 FYI.

**Comment by crocket63** [comment]
Yup! Cargo door will have realistic motion when actuators are implemented

**Comment by crocket63** [comment]
Done 🥳
