### ISSUE TITLE
Rear door triggering cargo door hydraulic sound

### ISSUE THREAD

**Issue by tush0701** [flybywiresim/a32nx#5185]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-21T15:16:44+00:00",
  "ref": "master",
  "sha": "f048d36f0dc95bd0c006544c0d181d43211d4324",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

The rear door opening/closing while catering is triggering the cargo door sound effect.

### Expected behavior

Rear door opening/closing should not trigger cargo door sound effect.

### Steps to reproduce

1. Load aircraft at any airport
2. Call for catering
3. Cargo door sound is triggered

### References (optional)

https://drive.google.com/file/d/1s1e41Ew4WnDEriBa5K2-ClQWiTRPD8Cm/view?usp=sharing

**Comment by davidwalschots** [comment]
@crocket63 FYI. I vaguely remember seeing something about the rear door being used to simulate the cargo door in the HYD.

**Comment by crocket63** [comment]
Well yes, as far as I know we don't have an animated rear cargo door do we?
I can just disable read door until we have a correct animated read cargo panel.

**Comment by tush0701** [comment]
Won't disabling the read rear door also disable the sound?

In that case, could you please let it be as it is at the moment, and fix it whenever possible?

The audio really adds a great realism to the model otherwise.

We won't call catering and fly as a low cost carrier until then.😂

**Comment by hotshotp** [comment]
> Won't disabling the read rear door also disable the sound when the actual cargo door opens?
> 

No it won't? He said rear cargo door isn't animated
