### ISSUE TITLE
Using parking brake resets the trim wheel to max position

### ISSUE THREAD

**Issue by Phil7789** [flybywiresim/a32nx#5191]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-21T15:16:44+00:00",
  "ref": "master",
  "sha": "f048d36f0dc95bd0c006544c0d181d43211d4324",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

When using the parking brake the trim wheel gets set to max up position (13 degrees)

### Expected behavior

Setting the parking brake should not reset the trim wheel

### Steps to reproduce

1. Prepare the aircraft from C&D state
2. Call TUG
3. Release parking brake

### References (optional)

In the video you can see the tug coming in. I then release the parking brake and the trim wheel snaps.

https://user-images.githubusercontent.com/21036064/123012040-d1fb7a80-d3c1-11eb-82fa-cbc6c7fad9ef.mp4

### Additional info (optional)

I had the above problem also during taxiing when I'm recalling this right. In my tests the trim wheel snapped e.g. setting the parking brake after pushback, releasing the tug and then releasing the parking brake again. So I am not 100% sure if the state shown in the video is the only one.

Additionally I was only able to reproduce this bug with a freshly started sim. After reloading the flight and after going back to the main menu and loading a new flight the bug didn't appear to happen if it happend once.

### Discord Username (optional)

Phil7789#0191

**Comment by Phil7789** [comment]
Updated the inital report with a video file and new steps to reproduce as it happend while releasing the parking brake for the tug and not while taxiing

**Comment by hotshotp** [comment]
Please check your keybinds, this is definitely something keybind related on your side and not a problem with the mod

**Comment by Phil7789** [comment]
> Please check your keybinds, this is definitely something keybind related on your side and not a problem with the mod

I have checked the keybinds and the button for setting/releasing the parking brake is just set for only this function. I am using a Saitek X56 Rhino Throttle (Joystick Button 9 - this is the lower middle toggle button on the throttle).
I also double checked the keyboard parking brake button (which is B) and it is also set only for this one function.
Furthermore there is no other button double assigned for any trimming and the parking brake.

I know that in the past setting the parking did not interfere with the trim wheel, unfortunately I cannot tell when exactly this behaviour occured.

As this only happens once after starting the sim (as far as I was able to reproduce) I am not sure how this could be linked to my keybinds, but I am happy about any hints.
Could this perhaps be Asobo related? I only tested this with FBW yet.

**Comment by Phil7789** [comment]
After a complete reinstall (Installer & Aircraft) the problem appears to have magically disappeared. Maybe this was an update hickup leaving some remains that caused this bug.

As I cannot reproduce any longer and nobody else seems to have this problem I would close this issue.
