### ISSUE TITLE
[BUG] Can't turn 

### ISSUE THREAD

**Issue by Askiz** [flybywiresim/a32nx#5198]
**Installer Version** 
c8815b8
**Describe the bug**
So, i can't turn plane :3
**To Reproduce**

1. I've checked settings
2. 
3.

**Expected behavior**
i wanted to fly

**Additional context**

Discord username (if different from GitHub): dwarf#8888

**Comment by MisterChocker** [comment]
@Askiz please follow [this template to open a new issue](https://github.com/flybywiresim/a32nx/issues/new?assignees=&labels=Bug&template=bug_report_beta.yaml).

If you need help following the instructions on the template please ask them here.
I am going to close this issue so your new one isn't a duplicate.
You can still write here and we'll still get notified to respond to you.
