### ISSUE TITLE
Dep/Arr airport not prefilled anymore in AOC Weather Request page

### ISSUE THREAD

**Issue by ErikNL80** [flybywiresim/a32nx#5199]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-23T08:49:38+00:00",
  "ref": "master",
  "sha": "02cf0511ad13fb9416ac5c1a7bc837661dc37962",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

Previously, when going to the AOC Weather Request both the departure and arrival airport were prefilled. Since a few days this is not the case anymore and the entire list is empty.

### Expected behavior

I would expect the departure and arrival airport to come up automaticallly as before.

### Steps to reproduce

1. Create a flight with departure and arrival
2. Go to the AOC Weather Request page
3. Verirfy that the departure and arrival airport are not prefilled anymore

### References (optional)

Before the page looked like this:
![Before](https://user-images.githubusercontent.com/71258178/123098972-03139380-d432-11eb-91d0-6bde7ee43f87.png)

Now it looks like this:
![After](https://user-images.githubusercontent.com/71258178/123099019-0eff5580-d432-11eb-967c-8af19cdc6b17.png)

**Comment by MisterChocker** [comment]
Can you  provide a picture from the Init-A as well please.

**Comment by ErikNL80** [comment]
When starting the flight the airports are there (in green). Normally I only retrieve the weather before landing (to fill the APPR page), and then the page is empty.

INIT:
![INIT](https://user-images.githubusercontent.com/71258178/123117077-bc2d9a00-d441-11eb-950c-49a474d5d6fe.png)"

Flightplan:
![FP](https://user-images.githubusercontent.com/71258178/123117118-c51e6b80-d441-11eb-95b5-fe8dc2b73056.png)

AOC:
![AOC](https://user-images.githubusercontent.com/71258178/123117132-c8b1f280-d441-11eb-87e0-f91cee328b08.png)

**Comment by MisterChocker** [comment]
Yes, when the FMGC from/to (also alt) are not defined, the fmgc will show blue brackets for the associated rows.

**Comment by ErikNL80** [comment]
Will do another test with screenshots

**Comment by 2hwk** [comment]
I tried but I can't reproduce this issue, always works for me.

**Comment by ErikNL80** [comment]
Did another test flight. Short hop from EKCH to EKBI.

Init:
![Init](https://user-images.githubusercontent.com/71258178/123240168-5ba16a00-d4e0-11eb-874d-48b6ca2cfe03.png)

Flightplan:
![FP](https://user-images.githubusercontent.com/71258178/123240184-60661e00-d4e0-11eb-9236-ec834dc19995.png)

AOC page:
![AOC](https://user-images.githubusercontent.com/71258178/123240201-64923b80-d4e0-11eb-8409-f6ebb2777a5c.png)

So far so good...

After I started the engines, and was ready for taxi the AOC page was empty again. Here are 2 screenshots, taken from the holding point before RWY 22R:
![BeforeTaxi](https://user-images.githubusercontent.com/71258178/123240575-b5099900-d4e0-11eb-848d-4caa48c217fe.png)
![Detailed](https://user-images.githubusercontent.com/71258178/123240596-b89d2000-d4e0-11eb-917a-7a89dd8d4069.png)

**Comment by MisterChocker** [comment]
@ErikNL80 please post a screenshot of the init-a when the aoc airport list becomes "empty".

**Comment by ErikNL80** [comment]
> @ErikNL80 please post a screenshot of the init-a when the aoc airport list becomes "empty". I looks the same as already posted...

**Comment by MisterChocker** [comment]
Unable to reproduce with the steps described above.

Ready for taxi:
![image](https://user-images.githubusercontent.com/1857322/123254298-c6f23880-d4ee-11eb-834e-abbef376148b.png)

Same when ready for to.

**Comment by ErikNL80** [comment]
Why do you have 3 airports? And how can I make sure this is becoming a yes/no game? What can I further check?

**Comment by ErikNL80** [comment]
Maybe it is good to add that I am using the default flightplanner, so no SimBrief or manually entering of the FP.

**Comment by MisterChocker** [comment]
> Why do you have 3 airports?

I've entered an alternate during my workflow.

> And how can I make sure this is becoming a yes/no game?

What do you mean by this?

> Maybe it is good to add that I am using the default flightplanner, so no SimBrief or manually entering of the FP.

All three types are supported.
I've tested again with only using the msfs flight planner and also wasn't able to reproduce.

> What can I further check?

If possible, you can try to capture a video which shows the aoc page in both states (the correct one) and then the bug.
So the video shows the aoc page working as intended, whats happening in-between until the aoc page becomes empty.
