### ISSUE TITLE
 Park brake param in FSUIPC

### ISSUE THREAD

**Issue by EmpireKicking** [flybywiresim/a32nx#5201]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-21T15:16:44+00:00",
  "ref": "master",
  "sha": "f048d36f0dc95bd0c006544c0d181d43211d4324",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

It's not a bug as such however the brakes system on your FlyBywire isn't set right, the  Park brake param in FSUIPC7 and for FSUIPC7 isn't detecting that the brakes are on. No idea if aware however seems to work with default aircraft. Part of a VA network and not able to do this right. 

### Expected behavior

![Capture](https://user-images.githubusercontent.com/47917870/123254015-08cab100-d4e6-11eb-9655-bd0ef9bd8911.jpg)

### Steps to reproduce

Open sim, FSUIPC7 starts autmatic
Spawn at the gate with brakes set and engines off
Start third party Acars and says that you are not at the gate with brakes set.
Fully update, did clean install on all things and nothing

**Comment by tracernz** [comment]
We don't have a cable-style park brake, but rather a hydraulic one that uses the same system as the foot brakes, and unfortunately that is not possible with the MSFS built-in park brake system. You can use the Lvar `A32NX_PARK_BRAKE_LEVER_POS`.
