### ISSUE TITLE
Setup the Display Brightness via LUA Script

### ISSUE THREAD

**Issue by A350Pilot** [flybywiresim/a32nx#5204]
### Aircraft Version

Experimental

### Description

I do many Things to Power up the A32NX from Cold and Dark via a LUA Script. That works fine. But the
last Thing that i miss, is the Ability to turn those Potentiometers for the Display Brightness and also the FCU Display Brightness via LUA Script. Hope, my Issue would be implemented. Thanks a Lot in Advance.
![image](https://user-images.githubusercontent.com/86430047/123308751-57973b80-d524-11eb-8070-b0bae36bde4e.png)

### Discord Username (optional)

A350Pilot

**Comment by Seb-a320** [comment]
that would be a very useful feature!

**Comment by Ducksneedhelp** [comment]
Its cool that you are using Lua. I have used that programming language a lot in different APIs

**Comment by A350Pilot** [comment]
> that would be a very useful feature!

Thanks for supporting my Issue.

**Comment by A350Pilot** [comment]
> Its cool that you are using Lua. I have used that programming language a lot in different APIs

In my daily Job, i am a Software Engineer for IBM Mainframe. So, i program many Things in private with LUA and VBA. Especially for XPlane and now for MSFS2020.

**Comment by frankkopp** [comment]
This works already if you use the right variables. Here my one button solution for SPAD.neXt:

![image](https://user-images.githubusercontent.com/16833201/124190729-08707e00-dac3-11eb-8519-0f8cc236c6c3.png)

I assume this should be easy for a script to do as well.

**Comment by A350Pilot** [comment]
> This works already if you use the right variables. Here my one button solution for SPAD.neXt:
> 
> ![image](https://user-images.githubusercontent.com/16833201/124190729-08707e00-dac3-11eb-8519-0f8cc236c6c3.png)
> 
> I assume this should be easy for a script to do as well.

Unfortunally it seems not to work. I've tried a variety of Syntax in LUA, but it always leads to LUA Errors.
Assuming they are Lvars, i tried this Syntax as an Example. I don't really know, how to use the Brackets in this Case.
      ipc.writeLvar("L:LIGHT_POTENTIOMETER_SET:"[86], 100)
Maybe you or another Member knows the correct LUA Syntax?

**Comment by frankkopp** [comment]
> Unfortunally it seems not to work. I've tried a variety of Syntax in LUA, but it always leads to LUA Errors.
> Assuming they are Lvars, i tried this Syntax as an Example. I don't really know, how to use the Brackets in this Case.
> ipc.writeLvar("L:LIGHT_POTENTIOMETER_SET:"[86], 100)
> Maybe you or another Member knows the correct LUA Syntax?

I'm sorry - never done anything with LUA - just wanted to give you the hint that the variables are there and work.

**Comment by A350Pilot** [comment]
Thanks frankkopp for trying to help. Maybe an other User has a hint, how to setup those Brackets?

**Comment by 2hwk** [comment]
As noted this should already be possible. Leaving this issue up as clearly we need better documentation for LVars + HEvents that affect aircraft states and controls.
