### ISSUE TITLE
Error In Wx Data

### ISSUE THREAD

**Issue by LievreAI** [flybywiresim/a32nx#5207]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-06-24T00:03:32+00:00",
  "ref": "master",
  "sha": "0d9f1df19b398d07c28646b89dfa5bd2b721ad7e",
  "actor": "MisterChocker",
  "event_name": "manual"
}
```

### Describe the bug

[
![20210625173441_1](https://user-images.githubusercontent.com/84988313/123441014-11051800-d5dc-11eb-88d7-3f15e79b27c6.jpg)
](url)

this panel not active i cant get a weather data "color" on my radar

i cant also get access the discord server to speak there.
the game is steam version

### Expected behavior

in the game there is a storm uselly there is a red or yellow colors on the radar but
the pabel is not working so the system cannot work

### Steps to reproduce

what is the photo show is what i tired to do

### Discord Username (optional)

#Katrin7037

**Comment by wpine215** [comment]
We need a photo of both the weather panel and the navigation display in the same screenshot, along with an open weather dialog from the toolbar indicating there is precipitation ( you can set the mode to "rain")

**Comment by MisterChocker** [comment]
You have selected `stable version` as the aircraft version your are flying, but your build info clearly shows a `development version`.
How is that? Have you accidentally selected stable instead of development on the template?

**Comment by LievreAI** [comment]
how i can access the discord server?

**Comment by scoopscode** [comment]
> how i can access the discord server?
> 
> ![1](https://user-images.githubusercontent.com/84988313/123458807-2420e380-d5ee-11eb-8114-43418185aec5.png)
> 
> 

Try this,

https://discord.gg/flybywire

**Comment by Benjozork** [comment]
Screenshot suspiciously looks like a default A320.

Did you manage to join our Discord ?

**Comment by LievreAI** [comment]
i cant connect , can you send me a dm to Katrin#7037
if i remember i was in this discord and been kicked cuz i used a pirate software
but now i have it on steam

**Comment by 2hwk** [comment]
Firstly this is the default A320
Secondly, the WX radar was fixed to only show precipitation and not just clouds by Asobo in SU4.

Closing.
