### ISSUE TITLE
Pause at TOD

### ISSUE THREAD

**Issue by chrisbgp** [flybywiresim/a32nx#5211]
### Aircraft Version

Development

### Description

An option to enable pause at top of descent would be useful.

**Comment by Benjozork** [comment]
This is not possible in MSFS.

**Comment by Benjozork** [comment]
Actually, it might be.

**Comment by Swaluver88** [comment]
still in the pipeline. got confirmation that other aircraft developers will have this feature and it would be awesome if it can be implemented still with the VNAV implementation when that comes along.

**Comment by fahdriyami** [comment]
Now that VNAV is here in the experimental build, TOD would be a very welcome addition.
