### ISSUE TITLE
FBW module not affecting control surfaces

### ISSUE THREAD

**Issue by Benjozork** [flybywiresim/a32nx#5216]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-25T21:46:21+00:00",
  "ref": "HEAD",
  "sha": "1f9462ceda1a2c63c61437cd67ed60bc7b30cd2c",
  "actor": "benjozork <benjamin.dupont.984@gmail.com>",
  "event_name": "manual"
}
```

### Describe the bug

**SIM UPDATE 5 / PC 2.0**

The FBW and AP system cannot affect control surfaces. The sidestick is inoperative.

### Expected behavior

The FBW system correctly affects control surfaces.

### Steps to reproduce

1. Load flight
2. Attempt takeoff

### Discord Username (optional)

someperson#4953

**Comment by aguther** [comment]
Reassign your axes.
