### ISSUE TITLE
[REQUEST] DIR functionality for all waypoints

### ISSUE THREAD

**Issue by toffee2000** [flybywiresim/a32nx#522]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to go direct to waypoints on an approach, such as the initial approach fix or final approach fix. This is particularly an issue when flying online, as we cannot accept direct to commands. This issue also makes runway changes a hassle as NAV will turn to the IAF even if it is behind the aircraft.

**Describe the feature you'd like to see implemented**
The DIR page should list all waypoints of the flight plan including approach fixes, and allow them to be selected and flown direct to.

**References**
http://www.a320dp.com/A320_DP/nav-flight-management/sys-14.3.0.html

**Comment by Flyingtrader06** [comment]
I would say only the REMAINING waypoints should be displayed on the DIR page.
