### ISSUE TITLE
ISIS Landing System

### ISSUE THREAD

**Issue by AviationSpotter** [flybywiresim/a32nx#5222]
### Aircraft Version

Development

### Description

Similar to the PFD's LS, the ISIS also has an LS.

### References (optional)

![image](https://user-images.githubusercontent.com/72807945/123526128-c64ed300-d6a3-11eb-83a7-cf4997b72a56.png)
![image](https://user-images.githubusercontent.com/72807945/123526160-f8603500-d6a3-11eb-9722-ac6d6cc6da54.png)

### Discord Username (optional)

Aviation Spotter#9102

**Comment by BlueberryKing** [comment]
Thank you for opening an issue. I am currently rewriting the ISIS in React, so I am working on this. :)
