### ISSUE TITLE
Some VARs not updating as per the documentation

### ISSUE THREAD

**Issue by ferryvanaesch** [flybywiresim/a32nx#5229]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-28T07:23:55+00:00",
  "ref": "master",
  "sha": "ac6847baf2d64bc836c9793bc224ae0e34910ae6",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

I see at least 3 VARs that aren't updating in Spad.Next, even though I believe they should as per the documentation:
A32NX_RADAR_GCS_AUTO, A32NX_RADAR_MULTISCAN_AUTO and XMLVAR_AUTO.

### Expected behavior

As I flick the switches / dial the knobs, I'd expect these variables to update.
Also, setting these LVARs should have an effect on the switches on the fligthdeck.

### Steps to reproduce

1. Start the data monitor in Spad.Next
2. Flick the switches / dial the knobs

### Discord Username (optional)

fva#1444

**Comment by tracernz** [comment]
None of these functions are implemented, nor can they be implemented currently so this is unlikely to be resolved for some time, unless somebody really wants to hook inop variables to the buttons/dials.

**Comment by ferryvanaesch** [comment]
That's fair, except for I believe XMLVAR_AUTO: shouldn't that one flick the ATC switch between Standby, Auto and On?

**Comment by tracernz** [comment]
Good point. That one is actually in I var, not an L var: `I:XMLVAR_Auto`. Not sure if SPAD can access I vars?

**Comment by ferryvanaesch** [comment]
I'm not 100% sure, have a look at the picture.
![Screenshot 2021-07-02 111409](https://user-images.githubusercontent.com/81757587/124259602-9762b200-db26-11eb-8fdb-1a3411781fb5.png)

**Comment by Narvik-Ramius** [comment]
Hi all, did someone found how to use the ATC STDBY/AUTO/ON switch with SPAD.NEXT ?
looks related to this XMLVAR_AUTO variable having no effect
