### ISSUE TITLE
Working clock while in cold and dark state

### ISSUE THREAD

**Issue by ErikNL80** [flybywiresim/a32nx#5230]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-28T07:23:55+00:00",
  "ref": "master",
  "sha": "ac6847baf2d64bc836c9793bc224ae0e34910ae6",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

I load the aircraft cold and dark, everything is off as it should, expect the clock is working...

### Expected behavior

I would expect the clock not to be working in a cold and dark state.

### Steps to reproduce

1. Load the A320nx
2. Start a flight at a gate/parking so it is spawned cold and dark
3. Verify the clock is working

### References (optional)

![CD](https://user-images.githubusercontent.com/71258178/123656867-92ed7f00-d830-11eb-9940-bdf6a70a6bf7.png)

**Comment by sidnov** [comment]
Any proper reference? The clock is connected to DC HOT BUS 1 which stays powered even when the aircraft batteries are off/ cold and dark state.

**Comment by davidwalschots** [comment]
In #3980 I built this to be on whenever DC HOT BUS 1 is powered. It turns out that there's a slight change in specs, so indeed it should be based on DC ESS being powered. Thanks for your report.

**Comment by davidwalschots** [comment]
The chrono and elapsed time keep counting even when the display is OFF (DC HOT BUS 1 is powering that). When the display is off, the buttons/switches to turn on/off the chrono/elapsed time don't work.
