### ISSUE TITLE
RAD NAV ILS Frequency

### ISSUE THREAD

**Issue by jockel1893** [flybywiresim/a32nx#5240]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-06-29T09:04:22+00:00",
  "ref": "master",
  "sha": "51c06af09bb23ab0d9d79c8e224306ad71c09087",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

Since the last update the RAD NAV (ILS Freq) does not work anymore. Usually you got fix it by entering the approach again in the Flight plan but no nothing happens and the ILS Freq stay empty.

### Expected behavior

ILS Freq in MCDU

### Steps to reproduce

1. Start flight plan in MS FS
2. Mostly the RAD NAV is empty but with entering the arrival again it updated the RAD NAV

### Discord Username (optional)

s

**Comment by tracernz** [comment]
It will tune the localiser for the departure runway (if selected) during the preflight and takeoff phases. Once within 250 NM of the destination and in climb phase or later, the approach localiser will be tuned (if/when an ILS/LOC approach is selected). Are you expecting the approach ILS to be tuned before you takeoff, as our A320 incorrectly did before?

**Comment by jockel1893** [comment]
Yes, I did not know that this was a wrong behavior (I am still learning). So it means I only select the FREQ when I took off. Does this still happen automatically when I select the approach?

**Comment by tracernz** [comment]
Yes, when you have selected an approach and you get within 250 NM of the destination runway it will auto-tune the approach ILS. Please re-open if you find any further issues. 👍
