### ISSUE TITLE
Spoilers Arrows visible with spoilers down post RTO/Flight

### ISSUE THREAD

**Issue by TheSquirtingPantin** [flybywiresim/a32nx#5245]
### Aircraft Version

Development

### Build info

```json
"built": "2021-06-29T17:19:17+00:00",
  "ref": "merge",
  "sha": "d330b3b36d43b95a5b253dd6e5529ae49cc9a0be",
  "actor": "crocket63",
  "event_name": "manual"
```

### Describe the bug

WHEEL ECAM page is displaying an improper masking for spoilers arrows. Some part of the arrows are still visible despite having the spoilers down. 

### Expected behavior

With spoilers down, the spoilers arrows should not be visible

### Steps to reproduce

1) Perform an RTO with spoiler activation (above 72kts) or a full flight. 
2) Retract/Disarm spoilers post RTO/Landing
3) Check WHEEL ECAM page, closely look for remains of spoilers arrows at the top of the page

This bug is not visible during initial taxi to runway in use if starting from Cold&Dark situation.

### References (optional)

![masking_Spoilers](https://user-images.githubusercontent.com/19536495/123962289-e9fd6c00-d976-11eb-963e-b62c6c857bca.PNG)

### Additional info (optional)

NONE

### Discord Username (optional)

Remi#8871

**Comment by avielmenter** [comment]
I tried reproducing this bug both after a full flight and an RTO with spoiler activation, and in neither case did the middle three spoilers stay up after being disarmed.

**Comment by wpine215** [comment]
Reported as fixed
