### ISSUE TITLE
When retarding throttle, reverse thrust is enabled without activation

### ISSUE THREAD

**Issue by lekkerjonty** [flybywiresim/a32nx#5246]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-06-28T07:23:55+00:00",
  "ref": "master",
  "sha": "ac6847baf2d64bc836c9793bc224ae0e34910ae6",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

When loading into the sim and also when pulling back the throttle on my Thrustmaster hotas x, reverse thrusters are deployed without any input from me. I have checked with other aircraft in the sim, and they do not do this. I have tested both Propeller and normal. I have also reset the settings and presets on my hotas and well as in-game. These don't make a difference.

### Expected behavior

When idling reverse thrust is engaged

### Steps to reproduce

Entered the sim.
Tried to move. 
Retarded the throttle,
Reverse thrust was then applied.

### References (optional)

![image](https://user-images.githubusercontent.com/76077409/124030269-efe26400-d9ed-11eb-8c3d-27ba2a2a9e9e.png)
![image](https://user-images.githubusercontent.com/76077409/124030301-f7097200-d9ed-11eb-8934-4e0b117a279d.png)

### Discord Username (optional)

lekkerjonty

**Comment by hotshotp** [comment]
please calibrate your throttles in the EFB
