### ISSUE TITLE
not able to set flex thrust

### ISSUE THREAD

**Issue by lorenlan** [flybywiresim/a32nx#5249]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-30T20:22:58+00:00",
  "ref": "master",
  "sha": "8d47df90665e10f885b54a2a871adcbd87af6e13",
  "actor": "MisterChocker",
  "event_name": "manual"
}
```

### Describe the bug

On take off, when set thrust to flex/mct ( tca airbus trhustmaster) on ecam it's displayed " flex/mct not set".
All perf page's fields are compilated.
after take off i had to set auto-thrust manually and then works fine, only on the ground there is this bug

### Expected behavior

expect that on take off i'll be able to engage auto thrust, with all function working fine

### Steps to reproduce

1. set flex temp and all other values in perf page MCDU
2. set throttle flex/mct on take off
3. auto trusth not engaged and message on ecam " flex/mct" not set

**Comment by Benjozork** [comment]
Did you properly calibrate your throttles in the EFB ?

**Comment by lorenlan** [comment]
yes, in the game the throttle moves like i move the real throttle

**Comment by Benjozork** [comment]
It might, but you still need the detents correctly set in the EFB. When you're on the ground at the gate, can you hear a "click" for every detent ?

**Comment by aguther** [comment]
FLEX in general works properly.

Please add more info and more important, add screenshots of:
- MCDU page with FLX temperature set
- Upper ECAM so we can see the thrust limit
- Lower ECAM so we can see the outside temperature
- PFD with thrust levers in FLX detent to see the FMA you’re getting

**Comment by aguther** [comment]
![FLEX-TO-1](https://user-images.githubusercontent.com/6629914/124195361-956b0580-daca-11eb-93f7-5f0c56f2b16b.png)
![FLEX-TO-2](https://user-images.githubusercontent.com/6629914/124195351-8f752480-daca-11eb-825f-ce2c277b1af2.png)
