### ISSUE TITLE
With TCA Quadrant, CLB thrust never engages

### ISSUE THREAD

**Issue by AriesFR** [flybywiresim/a32nx#5253]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-01T14:38:08+00:00",
  "ref": "master",
  "sha": "2a23f44e7faf992b6345bbae8bae43ab2031e022",
  "actor": "MisterChocker",
  "event_name": "manual"
}
```

### Describe the bug

I'm using the Thrustmaster TCA quadrant thrust lever. 
In the Stable version, after take-off, when I retire the thrust lever to the first notch (CL), I correctly get "THR CLB" engaged. 
Using the Development version (to correctly get the FLEX take-off), when I do the same, I incorrectly revert to MAN THR with a blinking "LVR CLB". There is no position where Climb Thrust engages.
During the flight, the ATHR pretends to engage, but if I remain in the CL position with the levers, the thrust contantly remains at Max continuous thrust, resulting in overspeed when in level flight or descent.
FYI, this error has been occurring for several development versions already.

### Expected behavior

Shortly after take-off, the PFD signals the need to set CLB thrust by retiring the thrust levers to the first notch (CL). It should switch the ATHR to THR CLB, then to SPEED or MACH in level flight, and if required, to DES or OP DES

### Steps to reproduce

1. take off using FLEX TO
2. Wait for THR CLB to blink on the PFD
3. Retire the thrust levers to CL position
4. Watch the PFD indication

### References (optional)

![image](https://user-images.githubusercontent.com/42541989/124174070-31394900-daac-11eb-9416-25976d1f0910.png)
This is despite the thrust lever being in CL position

**Comment by Beedan1G** [comment]
I have the same issue with mines too since I updated to the latest version before I started my flight

**Comment by Benjozork** [comment]
Have you properly calibrated the throttles in the EFB?

**Comment by tracernz** [comment]
Calibrate your thrust levers on the EFB. You have reverser on axis and independent axis with the TCA. https://www.youtube.com/watch?v=9oqFfAMXCcc

Before that best to create a profile for use with FBW, CRJ, etc. and change the levers to linear on the MSFS sensitivity options.

**Comment by bouveng** [comment]
First detent is not CL, it is FLX/MCT
The second detent it the CL one.

**Comment by hotshotp** [comment]
> First detent is not CL, it is FLX/MCT
> The second detent it the CL one.

that is wrong, first detent is CL and MCT is after

**Comment by Benjozork** [comment]
The first detent is CL

![image](https://user-images.githubusercontent.com/4503241/124191316-a0ee0a80-da91-11eb-82d6-95d5938411ec.png)

**Comment by AriesFR** [comment]
> Calibrate your thrust levers on the EFB. You have reverser on axis and independent axis with the TCA. https://www.youtube.com/watch?v=9oqFfAMXCcc
> 
> Before that best to create a profile for use with FBW, CRJ, etc. and change the levers to linear on the MSFS sensitivity options.

Hi, I did both.
I tried both the original calibration and the updated linear one. I even tried by recalibrating the hardware itself using the procedure provided by Thrustmaster.
And to confirm the issue really lies with the development version, I even reverted to the stable one and it worked fine. Just without the Flex capability and other improvements like the hydraulic page.
Just as extra information if it has any link (although I'd besurprised), the quadrant is linked to the two add-ons and the TFRP rudder.
Thanks

**Comment by tracernz** [comment]
What did you set the deadzone to on each detent?

**Comment by aguther** [comment]
I can tell you that I also own and always use the Thrustmaster TCA quadrant thrust lever and have no issues at all. The problem is your setup.

The stable version has no custom autothrottle system and therefore does not need to capture throttle axis. That's the reason why stable works for you. So I guess it's a combination of assignment, sensitivity setting and throttle calibration that is appropriate.

**Comment by AriesFR** [comment]
> What did you set the deadzone to on each detent? I can assure you that the TCA quadrant works very well when calibrated correctly. 

The TCA quadrant is indeed a great tool. It would have been perfect with a bit more space between the retard and the CL detent, like on the real plane, but I love it nonetheless. 

I did not set any deadzone on the detents, and again, it works fine on the stable release, so I can see no reason for the exact same profile in FS not to work anymore on thedevelopment one.

It did work fine on previous development releases. 

Shall I add also that it also works fine on the stock aircraft. I took the time to check!

The only remaining suspect, to me, is a bug in the dev version

**Comment by AriesFR** [comment]
> I can tell you that I also own and always use the Thrustmaster TCA quadrant thrust lever and have no issues at all. The problem is your setup.
> 
> The stable version has no custom autothrottle system and therefore does not need to capture throttle axis. That's the reason why stable works for you. So I guess it's a combination of assignment, sensitivity setting and throttle calibration that is not appropriate.

Sorry, but I checked this possibility in different scenarios multiple times before posting this bug. I also fully uninstalled the FBW aircraft to make sure it didn't come from previous upgrade remains. And I seem not to be the only one having this issue with a recent version...

**Comment by Benjozork** [comment]
> And to confirm the issue really lies with the development version, I even reverted to the stable one and it worked fine. Just without the Flex capability and other improvements like the hydraulic page.

The stable version does not have independent throttle calibration.

> I did not set any deadzone on the detents, and again, it works fine on the stable release, so I can see no reason for the exact same profile in FS not to work anymore on thedevelopment one.

You **need** to calibrate the throttles in the EFB properly and set a deadzone for the detents to work correctly. It is not optional.

**Comment by tracernz** [comment]
I start to wonder if we should make the default calibration all zeros so nothing works at all until you’ve properly calibrated. At least then it would be very clear.

**Comment by AriesFR** [comment]
OK, I'll try this tomorrow, I didn't see any information about this in the installer. I'll check if some documentation is available for the dev version somewhere 
Thanks

**Comment by tracernz** [comment]
Try the docs on the autopilot and autothrottle system in the dev version: https://docs.flybywiresim.com/start/autopilot-fbw/

**Comment by bouveng** [comment]
> > First detent is not CL, it is FLX/MCT
> > The second detent it the CL one.
> 
> that is wrong, first detent is CL and MCT is after

Well I was talking about the "first" from the TOGA-position, when we talk about "retire" thrust on from takeoff.

> "after take-off, when I retire the thrust lever to the first notch (CL)"

So I assumed he meant that he pulled back on throttle one notch from TOGA.

**Comment by AriesFR** [comment]
Hi all,
First, thank you to all of you who answered. Indeed, I never saw the configuration in the EFB. When I configure it, it's immediately much better...
If I may make a comment, however, the documentation on the topic might be improved by including this EFB configuration prerequisite at then end of the Installation section (with screenshots). The suggestion of presetting everything to 0 could also be replaced by a message on the first EFB start that this setting if mandatory and that it is not possible to use the EFB until a visit has been made to this setting page...
Again, it was my mistake in the beginning, thank you all.
Cheers,

**Comment by tracernz** [comment]
It's good that you managed to resolve it, and also good to gather data on the difficulties people have so we can see how to make things better. It's a little awkward for the dev version because if we write all the documentation for it, then it is not applicable to the stable version.

**Comment by bertez884** [comment]
> > What did you set the deadzone to on each detent? I can assure you that the TCA quadrant works very well when calibrated correctly.
> 
> The TCA quadrant is indeed a great tool. It would have been perfect with a bit more space between the retard and the CL detent, like on the real plane, but I love it nonetheless.
> 
> I did not set any deadzone on the detents, and again, it works fine on the stable release, so I can see no reason for the exact same profile in FS not to work anymore on thedevelopment one.
> 
> It did work fine on previous development releases.
> 
> Shall I add also that it also works fine on the stock aircraft. I took the time to check!
> 
> The only remaining suspect, to me, is a bug in the dev version

Complete agreement with you! Same problem, ONLY works correctly on STABLE!

**Comment by bertez884** [comment]
We go nowhere insisting to say it's only a configuration TCA matter! It works properly on STABLE, always with no problems indeed!

**Comment by AriesFR** [comment]
Hi,
No, I was wrong. It works perfectly on the DEV version. The only problem is that the requirement for the initial configuration in the Electronic Flight Bag (the tablet on the side) is not clearly stated. I've been using successfully the TCA with the dev version ever since I did this initial config.
This is the reason I did the post-mortem message to explain the solution I found... Please take the time to perform this first-time initialization and it works like a charm.
Cheers,

**Comment by tracernz** [comment]
> Complete agreement with you! Same problem, ONLY works correctly on STABLE!

It cannot work correctly on stable, because you can either have the detents working OR the manual throttle range between IDLE and CL very non-linear, not both. Read AriesFR's messages, then watch our video on how to calibrate https://www.youtube.com/watch?v=8yZuv2L4jPA

**Comment by bertez884** [comment]
Can you pls send me the link for proper setup?


Il giorno ven 16 lug 2021 alle 13:23 Michael Corcoran <
***@***.***> ha scritto:

**Comment by Beedan1G** [comment]
The only issue I am having is I have setup the EFB calibration with my Thrustmaster Hotas Warthog, it was working before until I updated it on the latest Dev version.

I had read somewhere that the reason other throttles don't work like the Hotas is due to the FlyByWire added support for the TCA and it broke the calibration for all the others in the process, like for example if I go back to the V0.6.1 Dev my throttles work again no issues, but if I update they break, something between the TCA support to the latest broke it and I am now unable to fly the FlyByWire until this is resolved.

**Comment by aguther** [comment]
The defaults have been changed in the meantime meaning if you have properly setup your throttles and saved the config you’re not affected by this change.

Ensure that you don’t have conflicts when doing the setup and then save the config.

I’m using the throttles on develop version without any issues with the TCA Throttles but also with the Honeycomb Bravo and also that he TCA Sidestick (in single config without any other).

Please look at the videos how to setup your throttles correctly it’s really not a bug in the A32NX.

**Comment by Beedan1G** [comment]
Yeh that is not something I did, I just pressed Apply, I wonder if I go back to 0.6.1 and set it up correctly and save it, then update again I wonder if it will break my hotas calibration

**Comment by aguther** [comment]
Again, the stable version does not have the throttle calibration!

**Comment by Beedan1G** [comment]
Yeh I use the dev version but if I go back to dev 0.6.1 it works perfect

**Comment by aguther** [comment]
There is no dev 0.6.1
