### ISSUE TITLE
[BUG] PFD not flashing LVL CLB and QNH

### ISSUE THREAD

**Issue by jpccaldas** [flybywiresim/a32nx#5257]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-01T14:38:08+00:00",
  "ref": "master",
  "sha": "2a23f44e7faf992b6345bbae8bae43ab2031e022",
  "actor": "MisterChocker",
  "event_name": "manual"
}
```

### Describe the bug

On PDF, LVL CLB and QNH are not flashing.

### Expected behavior

LVL CLB should flash white when shows up and QNH should flash passing TA or TL.

### Steps to reproduce

1. Load a flight
2. Setup performande take-off page
3. Take off
4. Watch PFD announcements not flashing

### Additional info (optional)

It worked on earlier builds. Tested with only FBW A32NX mod inside "Community" folder. Windows Store MSFS version.

### Discord Username (optional)

jpccaldas#8164

**Comment by tracernz** [comment]
Turn menu animations on in MSFS settings and see if it works.

**Comment by jpccaldas** [comment]
> Turn menu animations on in MSFS settings and see if it works.

Genius, working after turning on menu animations and restarting the sim (needed to restart). Thank you very much.
