### ISSUE TITLE
[BUG] ground cursor on PFD does not display when spawning on runway

### ISSUE THREAD

**Issue by AdenFlorian** [flybywiresim/a32nx#526]
**Mod Version**

**Describe the bug**

**To Reproduce**

1. spawn on runway
2. look at pfd
3.

**Expected behavior**

should see the ground cursor and limits

**Actual behavior**

no ground cursor or limits unless i turn an engine switch off and then back on

**References**

**Additional context**

**Comment by AdenFlorian** [comment]
@FarukEroglu2048 interested in taking a look at this one?

**Comment by FarukEroglu2048** [comment]
> @FarukEroglu2048 interested in taking a look at this one?

Another contributor have modified the code after the pull request to make the behavior more accurate, by displaying it once one of the engine switches are toggled. I suspect that's what introduced the bug, as it wasn't there in my pull request.

As a fix, an "or" condition might be added to the logic to detect the runway spawn case, where both of the master switches are already in on position.

**Comment by AdenFlorian** [comment]
this is working on master
