### ISSUE TITLE
throttle in ‘CL’ position but showing ‘LVR CLB’ in FMA

### ISSUE THREAD

**Issue by AKULA160** [flybywiresim/a32nx#5260]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-01T14:38:08+00:00",
  "ref": "master",
  "sha": "2a23f44e7faf992b6345bbae8bae43ab2031e022",
  "actor": "MisterChocker",
  "event_name": "manual"
}
```

### Describe the bug

my throttle is in ‘CL’ position but showing ‘LVR CLB’ in FMA.
 btw I'm using TWCS throttle.

### Expected behavior

FMA shouldn't show the ‘LVR CLB’ information if throttle is in ‘CL’ position.

### Steps to reproduce

just take off and set the throttle in ‘CL’ position, maybe you should using TWCS throttle.

**Comment by Benjozork** [comment]
Please calibrate your throttles in the EFB.

**Comment by AKULA160** [comment]
Thank u very much
