### ISSUE TITLE
Thrust response from idle too slow

### ISSUE THREAD

**Issue by donstim** [flybywiresim/a32nx#5262]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-24T13:54:04+00:00",
  "ref": "merge",
  "sha": "70bb38388d993123ebf6d7962e1d114d94f9c1f7",
  "actor": "crocket63",
  "event_name": "manual"
}
```

### Describe the bug

During turns with autopilot/autothrust engaged with idle thrust in CONF 2, thrust response is too slow to prevent speed from decaying to alpha prot. This can happen when approaching the level off altitude after an open descent.  Problem does not occur in level flight, where the engine response if very quick, nor in descent, where it just leads to a higher descent rate.

Issue first identified in this video (at 2:39:02 and again around 2:39:39): https://youtu.be/s841bTMG2Wo?t=9514

I replicated it in this video, which shows no issue with a turn in level flight, or in open descent. Only when the airplane is in idle near levelling off, where thrust must increase fast enough to both handle the level off and the drag increase due to the turn. https://1drv.ms/v/s!Ajsy7Ey4_8uFzy68wL5GBN7_dpUp?e=KxfpJ6

### Expected behavior

Thrust to increase fast enough to hold speed in this situation.

### Steps to reproduce

1. At 3000 ft, autopilot/autothrust engaged, APPR mode selected in MCDU, managed speed, CONF 2, 3, or 4 (speed decay happens with flaps up and CONF 1 as well, but there is a bit more margin to alpha prot).
2. Initiate an open descent to 2500 ft
3. At 50-100 feet before leveling off (i.e., before the thrust starts to increase), initiate a turn with the autopilot. Select a large enough heading or track change to cause the airplane to continue through the turn as it levels off.
4. Note speed decay

### Additional info (optional)

Issue brought up here: https://discord.com/channels/738864299392630914/738864300818432023/860825069357760542

### Discord Username (optional)

donbikes#4084

**Comment by Abriael** [comment]
It can happen regardless of whether you're in a turn or not. 

Happened to me several times on approach to ILSY on runway 17R at shanghai pudong. It's a fully straight approach when the aircraft levels off after descending to 3000 feet fully configured for landing (full flaps + gear) just before intercepting the glideslope in managed speed. 

Engines will be too slow to spool up when leveling off, causing alpha protection to kick in. Only way to prevent it is to set airspeed higher manually and go back into managed mode after the glidesope has been captured and the aircraft is descending again.

**Comment by donstim** [comment]
@Abriael Yep, understood. We found that out, too. Still working on the solution.

**Comment by donstim** [comment]
I think it has helped a bit, but it does not completely solve the issue.

**Comment by sidnov** [comment]
@aguther @donstim Is this still an issue on the latest development version after the recent tuning updates?

**Comment by aguther** [comment]
I think it is resolved.

**Comment by donstim** [comment]
I just flew it and can confirm it has been resolved. Good work!
