### ISSUE TITLE
Electrics & Tablet not working latest dev build

### ISSUE THREAD

**Issue by iangarratt** [flybywiresim/a32nx#5264]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-01T14:38:08+00:00",
  "ref": "master",
  "sha": "2a23f44e7faf992b6345bbae8bae43ab2031e022",
  "actor": "MisterChocker",
  "event_name": "manual"
}
```

### Describe the bug

With the latest developer build the tablet has disappeared (does not load in) and the battery does not turn on. 

### Expected behavior

Tablet to show, and battery to turn on / discharge 

### Steps to reproduce

1. Download dev build & load aircraft
2. Tablet missing & battery does not turn on

**Comment by 2hwk** [comment]
Unable to reproduce. Try cleaning your community folder (including a32nx), and redownload again.

**Comment by bouveng** [comment]
Cant reproduce this either.

**Comment by tracernz** [comment]
Only time I see this is when I check out a branch and forget to build before loading the aircraft.

**Comment by iangarratt** [comment]
Thanks everyone, i removed the community folder in its entirety and works now. Thanks for all the time and effort the devs put into this aircraft!
