### ISSUE TITLE
”No Smoking“ Chime

### ISSUE THREAD

**Issue by KeepGamingLP** [flybywiresim/a32nx#5271]
### Aircraft Version

Development

### Description

When „No Smoking“ is in auto Mode there should be a chime when the gear gets retracted. Also on approach when the gear gets extended.

### References (optional)

https://user-images.githubusercontent.com/72626508/124498419-977bdf80-ddbc-11eb-8c12-e4e82bb9778e.MOV

### Additional info (optional)

IRL when „No Smoking“ is in Auto mode as soon as the gear get extractet/retractet the emergency Exit lights go on/off and you can hear the chime as in the video.

**Comment by scoopscode** [comment]
This is just a call button being pressed on t/o, I don't believe it has anything to do with the gear being retracted.

**Comment by hotshotp** [comment]
> This is just a call button being pressed on t/o, I don't believe it has anything to do with the gear being retracted.

Wrong. This is already implemented in the a32nx, and you have to make sure the switch is in the middle position because the animation for it is wrong.
