### ISSUE TITLE
TCA autobrake keybind not working

### ISSUE THREAD

**Issue by ErikNL80** [flybywiresim/a32nx#5272]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-05T11:26:37+00:00",
  "ref": "master",
  "sha": "fc3d05f309dc4d1e366701402e9ee76ba6e36f8f",
  "actor": "2hwk",
  "event_name": "manual"
}
```

### Describe the bug

After https://github.com/flybywiresim/a32nx/pull/4970 the keybindings of my TCA throttle do not work anymore... When selecting LOW of MEDIUM the autobrake illuminate for a second and then go out again. Autobrake max does not work at all.

### Expected behavior

I would expect the key bindings of my TCA throttle to work for LOW MED and MAX.

### Steps to reproduce

1. Spawn on the runway
2. Test autobrake functionality using the TCA throttle
3. Compare this to the default A320 behaviour.

**Comment by crocket63** [comment]
Keybindings for LO MED and HI are handled by new autobrake, but I suspect the TCA knob to constantly "press" the key, which makes it first going on then off due to FS2020 key handling.

Is it possible to change TCA behaviour so it sends the command only once when set in position?  This will solve the issue.

**Comment by ErikNL80** [comment]
Yes, in disarm position it is off, if you select other options the key is probably being pressed as you say. I do not have options to change this behaviour, not in the TCA config and not in MSFS... Since the TCA quadrant is made for the A320 it would be a real pity if this is not going to work.

**Comment by crocket63** [comment]
If it's made for a320 they put the wrong knob :)
Sadly making this work for the wrong knob would prevent it to work as it should using 3 buttons. I'm sure it can be changed on the tca side using a dedicated software

**Comment by tracernz** [comment]
We really need to come up with a workaround for this if we can. TCA is by far the most popular and we don’t want to require non-free tools to get it working.

**Comment by ErikNL80** [comment]
The code is already there (at least was)... You can also put an option in the EFB for TCA users?

**Comment by tracernz** [comment]
> 
> 
> The code is already there (at least was)... You can also put an option in the EFB for TCA users?

The autobrake system has been entirely replaced with a custom implementation. We won't go back to the MSFS built-in implementation.

**Comment by Saschl** [comment]
Ultimately, using a third party tool like spad.next, Axis and Ohs or FSUIPC seems inevitable with more custom systems coming in. That is if the sim won’t get the more options to  configure aircraft specific Events.. maybe that’s worth a Zendesk Ticket

**Comment by ErikNL80** [comment]
Guys please, can we please think of a solution? I know the TCA autobrake is from the A350, but a lot of people not understand why it works in the default A320 and not in the A320nx. An EFB option (like PTU sound) would be great!

**Comment by Benjozork** [comment]
> Guys please, can we please think of a solution?

You are more than welcome to submit a PR if you know a solution.

**Comment by Benjozork** [comment]
> An EFB option (like PTU sound) would be great!

Not possible.

**Comment by tracernz** [comment]
> Ultimately, using a third party tool like spad.next, Axis and Ohs or FSUIPC seems inevitable with more custom systems coming in. That is if the sim won’t get the more options to configure aircraft specific Events.. maybe that’s worth a Zendesk Ticket

We need to build a FOSS equivalent with Theo’s Jetbridge then IMO.

**Comment by crocket63** [comment]
Could be worth asking Asobo why we don't receive correct key events for continuously pressed inputs.
I have same issue with keyboard braking.

**Comment by 2hwk** [comment]
https://github.com/wnzlff/msfs-parking-brake-toggle

A compatibility tool similar to this may be one kind of solution.

**Comment by crocket63** [comment]
No programming tool available for TCA by the way? You can do pretty much what you want with thrustmaster A10 hotas using their target software

**Comment by 2hwk** [comment]
> Keybindings for LO MED and HI are handled by new autobrake, but I suspect the TCA knob to constantly "press" the key, which makes it first going on then off due to FS2020 key handling.
> 
> Is it possible to change TCA behaviour so it sends the command only once when set in position? This will solve the issue.

I've noticed the same thing will happen using the keyboard if you press and hold down the key binding for autobrake, so this is likely the issue.

**Comment by crocket63** [comment]
Yup and this is directly because of how we receive keyboard events. A continuous press generates one short press followed by a constant press.  If we have a general solution for that damn keyboard press handling, all internal code is already capable to handle both buttons and TCA rotating knob

**Comment by ErikNL80** [comment]
Maybe someone can open a topic/wish on the MSFS forum? Then we can all vote on it? I don't think I can explain the issue in a clear way so would be great if someone is capable of doing so...
