### ISSUE TITLE
Full flaps on landing elevating the aircraft

### ISSUE THREAD

**Issue by krgaba** [flybywiresim/a32nx#5273]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-05-05T23:03:06+00:00",
  "ref": "v0.6.1",
  "sha": "4a1cccc90ab3997109e394402ab9b41a80fbf325",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

On ILS landing, full laps with the correct landing speeed, aircraft starts elevating.

### Expected behavior

Aircraft should not elevate even when the nose is down

### Steps to reproduce

1. Click on world map
2. Select landing destination
3. Select Flybywire A320 neo
4. Try to land the aircraft with full laps and 135 landing speed.

**Comment by sidnov** [comment]
Can you check your sim settings-> Flight Model -> and make sure it is set to MODERN?

**Comment by krgaba** [comment]
That works! Thanks
