### ISSUE TITLE
FCU LED Display Functioning During C&D

### ISSUE THREAD

**Issue by AviationSpotter** [flybywiresim/a32nx#5275]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-05T11:26:37+00:00",
  "ref": "master",
  "sha": "fc3d05f309dc4d1e366701402e9ee76ba6e36f8f",
  "actor": "2hwk",
  "event_name": "manual"
}
```

### Describe the bug

FCU LED Display is still functioning without power

### Expected behavior

FCU LED Display not able to function without power

### Steps to reproduce

1. Spawn C&D
2. Up the brightness on FCU LED Display

### References (optional)

https://user-images.githubusercontent.com/72807945/124516488-be7fe480-ddaf-11eb-8fb0-96c7ee37f1e7.mp4

### Discord Username (optional)

Aviation Spotter#9102

**Comment by bouveng** [comment]
Will pick this up in a short wile.
