### ISSUE TITLE
Unable to select "CL"  on thrust lever with keyboard input

### ISSUE THREAD

**Issue by crazyfx1** [flybywiresim/a32nx#5281]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-06T00:49:05+00:00",
  "ref": "master",
  "sha": "f60a97a3bad2e962a76d0dd3376c0b1421e05d29",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

I want to select "CL" on the thrust lever with the keyboard keys (default F2 and F3). The lever jumps right over CL, it's not possible to select it. 

### Expected behavior

The lever should snap to CL and then go further.

### Steps to reproduce

1. Use F3 on the keyboard to select CL.

### References (optional)

Video: https://streamable.com/hiyqbb

### Additional info (optional)

It works in the Asobo A320neo.

**Comment by Failfail2603** [comment]
Same problem accures by using an X-Box controller. The lever can go to full TO-GA and snaps to FLEX but cant be put to CL. As a result the PFD flashes "LVR CLB".
![Screenshot_5](https://user-images.githubusercontent.com/24842315/125514863-ebdfc1ef-e8ad-4623-8b8f-e9740dd72465.png)
![Screenshot_6](https://user-images.githubusercontent.com/24842315/125514873-943e4565-2214-4560-bdcc-486851bfc22d.png)

**Comment by Eriadus85** [comment]
And I will add that when you succeed in selecting CL, it comes back by itself in A / THR position or in FLX or TOGA

**Comment by monkeh88** [comment]
yeah i noticed this too last 3 days

**Comment by hiroooo1997** [comment]
Detents Calibration in "flyPad" Option page may be solution for this.

**Comment by monkeh88** [comment]
> Detents Calibration in "flyPad" Option page may be solution for this.

hi, when put throttle on climb the other throttle is delayed how i fix that , they dont move both to climb

**Comment by crazyfx1** [comment]
> Detents Calibration in "flyPad" Option page may be solution for this.

Yes you can calibrate to fix it. But I believe it should work for keyboard without calibration .

**Comment by monkeh88** [comment]
thank you ill try

**Comment by aguther** [comment]
Search also closed issues for keywords we had one with a similar issue where throttles have been misaligned.

**Comment by monkeh88** [comment]
yeah that will help , thank you

**Comment by marcelago** [comment]
I have the same issue with a controller since recently and i increase/decrease thurst with two buttons. I, too, cannot select Climb Thrust directly and have to select a slightly lower detend (exactly like the image shown above. But I have an additional issue:
when I lock the levers with my mouse in the exact CL position it locks in as it should but the plane does not recognize it as CL but it just says MAN THR (I believe) as if I pushed them to MCT. So I either get a "LVR CLB" or "MAN THR" but I cannot get it into a green "SPEED" anymore and its mildly annoying
