### ISSUE TITLE
Can't reach cruise altitude

### ISSUE THREAD

**Issue by cache86** [flybywiresim/a32nx#5283]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-05-05T23:03:06+00:00",
  "ref": "v0.6.1",
  "sha": "4a1cccc90ab3997109e394402ab9b41a80fbf325",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

When setting high altitudes de AP always remain 300 ft below target

### Expected behavior

Have the same altitudes established on the AP as in the flying controls

### Steps to reproduce

1. Take-off
2. Set any altitude above the transition altitude
3. The AP will always remain 300 ft below the set value
 
![image](https://user-images.githubusercontent.com/87046987/124680995-353edf80-de8d-11eb-9cb8-f8e7908786dd.png)
![image](https://user-images.githubusercontent.com/87046987/124681025-4687ec00-de8d-11eb-8b8e-4ab0c5cf776c.png)

**Comment by Benjozork** [comment]
Are you using MSFS live weather?

**Comment by cache86** [comment]
> Are you using MSFS live weather?

Yes, I do!!

**Comment by Benjozork** [comment]
It seems like your outside temperature is a bit too high for this altitude.

Try using a weather preset instead.

**Comment by cache86** [comment]
> It's a known bug with live weather, switch to a weather preset like "clear skies" and it should climb. 

Thank you, I will wait for the hotfix and try what you mentioned. Was strange that even from FL200 was the same issue.
