### ISSUE TITLE
VOR not clearing

### ISSUE THREAD

**Issue by Beedan1G** [flybywiresim/a32nx#5284]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-25T14:50:34+00:00",
  "ref": "master",
  "sha": "1f9462ceda1a2c63c61437cd67ed60bc7b30cd2c",
  "actor": "tracernz",
  "event_name": "manual"
}
```

### Describe the bug

When completing a flight from a location to the next and when you shut down the engines and the MCDU and every reset and go back to how it looks in cold and dark, the VOR frequency still shows inputted but if you go to the RAD NAV page it is blank
![FlightSimulator_M5cGqu1dH4](https://user-images.githubusercontent.com/29601998/124684941-2c1f3400-dec8-11eb-992d-df7ab9f1abb2.png)

### Expected behavior

It should clear like everything else does in the MCDU or correspond with the MCDU

### Steps to reproduce

1. Do one flight to and from a airport with all the arrival information inputted.
2. After shutdown of the engines and the MCDU goes back to cold and dark state, look at your ND.
3. Then check the RAD NAV page and see if any data is there.

### Discord Username (optional)

Beedan🎗#3838

**Comment by tracernz** [comment]
I’m not sure what the radios do when neither the FMGC nor the RMP (backup tuning) are setting the frequency. Holding the last tuned one seems reasonable.

**Comment by tracernz** [comment]
I believe the MMR will just keep the last frequency as long as nothing is telling it to tune a new one. The behaviour we have matches what I see in videos, and what I read in documentation.
