### ISSUE TITLE
not in database When I enter the airport code on the init page

### ISSUE THREAD

**Issue by ljk811** [flybywiresim/a32nx#5289]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-08T23:44:52+00:00",
  "ref": "master",
  "sha": "7e50b9097e9526d439a7a0c3d82bb87fd23f6d15",
  "actor": "wpine215",
  "event_name": "manual"
}
```

### Describe the bug

Recently, I was a tester for the performance version of msfs. When I fly FBW320, enter the airport code on the mcdu init page. When I fill in the airport code and enter it, it will display "not in database". The default 320 will not have this situation.

### Expected behavior

Recently, I was a tester for the performance version of msfs. When I fly FBW320, enter the airport code on the mcdu init page. When I fill in the airport code and enter it, it will display "not in database". The default 320 will not have this situation.

### Steps to reproduce

Requires Microsoft Flight Simulator version 1.18.9.0 to be installed. To reproduce this bug

### Discord Username (optional)

Roger

**Comment by Benjozork** [comment]
Beta versions of the simulator are not supported.

We will release fixes for the beta one day one.
