### ISSUE TITLE
night lighting 

### ISSUE THREAD

**Issue by youngryan7** [flybywiresim/a32nx#5292]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-09T09:10:37+00:00",
  "ref": "master",
  "sha": "28e101078a975b13546a15746ef93233b8fe54b6",
  "actor": "2hwk",
  "event_name": "manual"
}
```

### Describe the bug

lighting in cockpit not working

### Expected behavior

pedestal and flood lights at night time 

### Steps to reproduce

night time 
turn up pedestal and flood light 

### References (optional)

![2021-07-09 (1)](https://user-images.githubusercontent.com/59422760/125137035-cb7c3b00-e103-11eb-8715-050f9661f071.png)
![2021-07-09](https://user-images.githubusercontent.com/59422760/125137040-ce772b80-e103-11eb-916c-8588505e21d2.png)

**Comment by hotshotp** [comment]
this is an issue on your end, i cant reproduce. try reinstalling

**Comment by Logater** [comment]
I unfortunately have the same problem. I tried reinstalling and switching versions but that didn't help. Not sure what's happening

**Comment by Watsi01** [comment]
Could be a conflict with another mod? Try without any other mods or custom liveries in you community folder.

**Comment by bouveng** [comment]
Hi!

I can't reproduce this either.
Please try to reinstall the aircraft, and make sure no other mods or liveries is interfering.

**Comment by tush0701** [comment]
Hi. I have the same problem. Reinstalling did not resolve the problem for me too.

**Comment by youngryan7** [comment]
tried with different liveries and no luck. its the pedestal light and the light between the pfd and nd not working. i don't have anything in my community folder that would effect it. and its worked fine before - only thing is only recently done night time flights and realised. not sure how long its not been working for.

**Comment by Logater** [comment]
Exactly... it’s so weird

**Comment by BjoernHund** [comment]
Did you ever install the stable version from the marketplace?

**Comment by tush0701** [comment]
@BjoernHund Never installed the stable version from the marketplace, however had the stable version installed in a different "Community" folder long time ago. I don't think that should affect the lights as this seems to be a recent problem. However, if any files of the stable are found, and could be cleared, could you please let us know the location.
Thanks in adv :)

**Comment by tush0701** [comment]
One more update:

I deleted the Dev version, and switched to stable, all lights worked. The moment I shifted back to Dev, they stopped working again,

**Comment by bouveng** [comment]
> The lights to lighten up, but there is no illumination(check screenshots below). Note the darkness right below the lights.

In that above scenario, what happens if you turn the time to night?

Br.

**Comment by tush0701** [comment]
@bouveng Voila! Lights working at night again for me, but the moment a single ray of sun falls on the aircraft, no illumination.
Screenshot of night:
![Screenshot (62)](https://user-images.githubusercontent.com/75409941/125558880-1ea46fa0-f4e5-4fbf-93a5-eb2c04e3f0a7.png)
Now, shifting time to around half an hour before sunset:
![image](https://user-images.githubusercontent.com/75409941/125558920-ed38768c-fbb6-42b3-a2ad-040b9d3c54d9.png)

So I think the problem is, during daylight hours, the light shafts seem to be inactive.

Becomes unrealistic especially during stormy weather as the cockpit is quite dark, and there are no light shafts from the floodlights.

**Comment by tush0701** [comment]
Another reference to time:

6:41 PM, lights don't illuminate
![image](https://user-images.githubusercontent.com/75409941/125559249-f9392a23-54ce-46d4-a86c-d8ca6dda6082.png)

Increase time ever so slightly, lights start illuminating.
![image](https://user-images.githubusercontent.com/75409941/125559282-d69e4c62-d92a-4387-bc4f-72e9a54f992b.png)

**Comment by bouveng** [comment]
@tush0701 Thank you! Very useful for debugging!

**Comment by bouveng** [comment]
@tush0701 For reference. Timelapse I did during development of the new knobs.

![image](https://user-images.githubusercontent.com/433429/124051080-17e8bc00-da1c-11eb-85d4-ab83e9073064.gif)

**Comment by tush0701** [comment]
That is perfect!

**Comment by bouveng** [comment]
@tush0701 Should be all good now! =))

**Comment by youngryan7** [comment]
still not fixed for me
