### ISSUE TITLE
Make All Toggle Switches Operable With Mouse Wheel

### ISSUE THREAD

**Issue by tracernz** [flybywiresim/a32nx#5298]
### Aircraft Version

Development

### Description

The three position toggle switches on the overhead are operable with the mouse wheel, but the two position ones are not. Operating them with the mouse wheel is more convenient and less error prone.

Toggle switches that are not operable with the mouse wheel are circled in red:
![image](https://user-images.githubusercontent.com/9995998/125183178-83c2f400-e268-11eb-8c86-35e3427fb770.png)

**Comment by bouveng** [comment]
The `NAV & LOGO` switch should also be a three way switch?

**Comment by tracernz** [comment]
> The `NAV & LOGO` switch should also be a three way switch?

Yes it should. Looks like there is no existing issue for that..

**Comment by ghitier** [comment]
It looks to me like no other aircraft implement this (default: DR400, C172, B747). Therefore I think it could be confusing if only the 32NX did this.

**Comment by tracernz** [comment]
> 
> 
> It looks to me like no other aircraft implement this (default: DR400, C172, B747). Therefore I think it could be confusing if only the 32NX did this.

On the other hand all the other A320s I know of do... it's rather annoying not having it, and I don't see how it would hurt anyone that doesn't use it, as they can still click.

**Comment by ghitier** [comment]
> > 
> > 
> > It looks to me like no other aircraft implement this (default: DR400, C172, B747). Therefore I think it could be confusing if only the 32NX did this.
> 
> On the other hand all the other A320s I know of do... it's rather annoying not having it, and I don't see how it would hurt anyone that doesn't use it, as they can still click.

Fair point, I don't know to much about other one s.
