### ISSUE TITLE
No control inputs works

### ISSUE THREAD

**Issue by ChrizzyO** [flybywiresim/a32nx#5306]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-12T16:47:00+00:00",
  "ref": "master",
  "sha": "27c0c2a532eeae67681ddce877ec042dce03cdbe",
  "actor": "RichardPilbery",
  "event_name": "manual"
}
```

### Describe the bug

No surface control inputs works. 
Using Honeycomb Yoke, Saitek Quadrant and Saitek rudder pedals. 
Throttle, spoilers, flaps, parking brake, doesnt work. 
Works great on the Stable FBW320 release but not on the Dev version.

Video: https://drive.google.com/file/d/1D24x1cxFoJG0eQt5LvEaAhcth-ypa9h0/view?usp=sharing

### Expected behavior

Aircraft to work?

### Steps to reproduce

Load up at RW

### References (optional)

https://drive.google.com/file/d/1D24x1cxFoJG0eQt5LvEaAhcth-ypa9h0/view?usp=sharing

### Additional info (optional)

Had issues prev and talked with discord group members but noone have managed to given an idea about what´s causing this! 
I went so far that I re-installed windows 10 completly but issue persists.

### Discord Username (optional)

ChrisO#0319

**Comment by 2hwk** [comment]
Quite strange, since we've already tried everyone, it could be core file corruption maybe?
![image](https://user-images.githubusercontent.com/15316958/125380701-327c4700-e3c5-11eb-8218-6044c1266b38.png)

Try moving all these folders out of your Official (not community) folder, then restart the sim. It will prompt you to redownload the files. Try that.

**Comment by ChrizzyO** [comment]
> Quite strange, since we've already tried everything, it could be core file corruption maybe?
> ![image](https://user-images.githubusercontent.com/15316958/125380701-327c4700-e3c5-11eb-8218-6044c1266b38.png)
> 
> Try moving all these (highlighted) folders out of your Official (not community) folder, then restart the sim. It will prompt you to redownload the files. Try that.
> 
> Also it works with all peripherals detached? If it does, this is a strange one.

I have re-installed MSFS twice + formatted windows. So I dont think it´s a core file issue sadly but I´ll try what you wrote.

**Comment by 2hwk** [comment]
https://github.com/flybywiresim/a32nx/releases/download/vmaster/A32NX-master.zip

**Comment by ChrizzyO** [comment]
> https://github.com/flybywiresim/a32nx/releases/download/vmaster/A32NX-master.zip

That´s another build than the one I got downloaded via the FBW installer.. Let´s see if the one u sent works.

**Comment by Benjozork** [comment]
Do you have a `SimConnect.cfg` file in your Documents folder ?

**Comment by ChrizzyO** [comment]
> Do you have a `SimConnect.cfg` file in your Documents folder ?

Yes I actually do. Should I delete that one?
![image](https://user-images.githubusercontent.com/32465570/125395479-8d08a980-e3ab-11eb-9215-cc288baf5637.png)

**Comment by ChrizzyO** [comment]
It´s finally solved! Benjozork came with the solving question!! I did in fact have a simconnect.cfg in my Documents folder that I removed and voila - everything is working again! Not sure how that simconnect.cfg file came there though... My guess is that this solution can be helpful for others as well. Some might take a backup of this file and place in Documents folders etc. and stand clueless if the aircraft systems stops working.

**Comment by aguther** [comment]
https://docs.flybywiresim.com/start/autopilot-fbw/

„Flight controls are not working after reload of the sim or airplane“

Not new…

**Comment by ChrizzyO** [comment]
> https://docs.flybywiresim.com/start/autopilot-fbw/
> 
> „Flight controls are not working after reload of the sim or airplane“
> 
> Not new…

„Flight controls are not working after reload of the sim or airplane“ <--- not the issue I was having and the link you posted does NOT have anything that says: Remove simconnect.cfg from Documents folder if you have one there which I had. Removed it and the plane started working as it should! So not sure what your post was all about since it doesnt add any value to the issue I had.
