### ISSUE TITLE
Navigraph charts page in EFB not cached

### ISSUE THREAD

**Issue by GrimGrandZero** [flybywiresim/a32nx#5307]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-12T22:06:06+00:00",
  "ref": "master",
  "sha": "cf88fc3c16e212978f26186cebfb6dc7deef7af1",
  "actor": "hiaaryan",
  "event_name": "manual"
}
```

### Describe the bug

The Navigraph charts are not cached. So every time you leave the charts page and re-engage it, one has to dial in the ICAO code for the desired airport again. 

### Expected behavior

Cached charts

### Steps to reproduce

Start EFB, go to charts page, enter ICAO code, leave charts page

### Discord Username (optional)

GrandZero#5475

**Comment by Venorcis** [comment]
Just wanted to add this is indeed a very annoying issue, rendering the charts in the EFB near useless for me; I want to be able to switch to the TOD calculator, VATSIM frequencies, etc. without losing my current chart.

**Comment by sidnov** [comment]
Should be taken care of by the new state management in flyPadOS v3
