### ISSUE TITLE
Implement React Hook for GameVarValue

### ISSUE THREAD

**Issue by Lucky38i** [flybywiresim/a32nx#5311]
### Aircraft Version

Development

### Description

I was wondering is someone could create a react hook for the gameVarValue to be used for the retrieval of things like `FLIGHT NAV DATA RANGE`.
![Image](https://i.imgur.com/D7eYNjj.png)

### Discord Username (optional)

Lucky38#3550

**Comment by 2hwk** [comment]
Completed by #5483 closing.
