### ISSUE TITLE
Left engine heat blur effect emitter coordinates a little too high

### ISSUE THREAD

**Issue by santiagoluib3** [flybywiresim/a32nx#5325]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-05-05T23:03:06+00:00",
  "ref": "v0.6.1",
  "sha": "4a1cccc90ab3997109e394402ab9b41a80fbf325",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

The heat blur effect emitter coordinates for the left engine (#1) is a little too high.  If viewed externally at the rear of the aircraft, the left engine heat blur seemed to be emitting more from the wing than from the engine exhaust. This is also noticeable if you use the passenger window-wing view. 

### Expected behavior

Heat blur effects from left engine should be similar to the right engine in that it aligns with the exhaust.

### Steps to reproduce

1. Start engines
2. Got to external view and position camera behind the aircraft.
3. Compare the heat blurs of both engines and notice the blur effect from the left engine is not aligned with the exhaust.

### Discord Username (optional)

861-Lima

**Comment by tracernz** [comment]
They seem to be aligned correctly in the model...
![image](https://user-images.githubusercontent.com/9995998/125895767-f1bfacb4-92cd-4c67-8361-b2ba8a5e128c.png)
![image](https://user-images.githubusercontent.com/9995998/125895798-f5dfad61-d73d-42d7-8be7-c3f990e69918.png)

**Comment by tracernz** [comment]
Anyway, to move the nodes, you simply need to replace the translation values following the example of https://github.com/flybywiresim/a32nx/commit/5055d9adcd7cf9644197aebe8ac8fb8556259c6a#diff-01a9759946ddbe7f0be0c713bc0f29754130e54118cfb0e9112c8c9541e067e2

**Comment by bouveng** [comment]
@tracernz I was thinking of moving the asobo fx into our effects folder, then try to positioning it using the XML api.
