### ISSUE TITLE
Please revert cabin announcements prior to #5314

### ISSUE THREAD

**Issue by ErikNL80** [flybywiresim/a32nx#5328]
### Aircraft Version

Development

### Description

Since PR #5314 there are new sounds before take-off and before landing when pressing the call buttons. I really liked the old ones, new ones are too loud and too American to my taste. Would it be possible to revert back to the old ones?

**Comment by hotshotp** [comment]
We have gotten recordings of all PAs such as welcome aboard, seatbelts, level off, etc from this person. I made sure that they aren't too loud when the efb sliders are set to their default positions. The previous ones were very american too.
