### ISSUE TITLE
Overall ND visual design issues

### ISSUE THREAD

**Issue by AdenFlorian** [flybywiresim/a32nx#533]
This is the master tracking issue for visual fidelity issues on the ND, things like fonts, size, positions, etc.

- [ ] text in top left and right should be flush with corner of screen
- [ ] compass headings numbers font too thicc
- [ ] the circle dashes are to long and too spread apart
- [x] compass should spin when coming out of alignment - https://github.com/flybywiresim/a32nx/pull/538
- ...

**Comment by AdenFlorian** [comment]
I'm starting work on this.

**Comment by PCGamesF1Tech** [comment]
Approach type on top middle part should be green, not magenta (#221)

**Comment by cobrafast** [comment]
Terrain on ND should show ocean (in blue).

**Comment by cobrafast** [comment]
Blue end of climb/descent distance estimation arrows are missing.

http://www.a320dp.com/A320_DP/flight-instruments/images/ndairportvor.jpg

Afaik they should also appear when not on a flight plan, as soon as the selected altitude is different from the current altitude.

**Comment by Benjozork** [comment]
@AdenFlorian according to Tarek on the discord, the ILS indicaton on the ND should always be green.

Do you want to do this as part of your fixes in this issue or can I open a PR for it ?

**Comment by mikecbr** [comment]
Any news on this ?

**Comment by davidwalschots** [comment]
@tracernz FYI. Might contain items which are fixed or will be fixed by ND changes in cFPM branch.
Feel free to close this one if needed, as it's another one of those "many issues in one ticket" things.

**Comment by tracernz** [comment]
Yes, no need to track this anymore.
