### ISSUE TITLE
[BUG] after landing you get the ECAM MEMO for T.O configuration

### ISSUE THREAD

**Issue by starvingjavi** [flybywiresim/a32nx#534]
**Mod Version**
Master

**Describe the bug**
Upon landing, when taxiing to a gate you get the ECAM MEMO for T.O configuration

**To Reproduce**

1. After landing, start APU and continue taxiing to gate
2. Check ECAM for TO MEMO

**Expected behavior**
There should not be a Take off configuration memo on the ECAM after landing. 

**Actual behavior**
TO Config MEMO after landing when taxiing to gate

**Comment by NathanInnes** [comment]
Duplicate report same as #527
