### ISSUE TITLE
Autothrottles: Uncommanded TOGA on low approach

### ISSUE THREAD

**Issue by geoffda** [flybywiresim/a32nx#5343]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-17T12:02:12+00:00",
  "ref": "master",
  "sha": "a545c20df9d5d127e95903ad5b7648e46bf7404b",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

With the last two or three development builds, more often than not, when I get below 1000' AGL, in approach mode, autopilot disengaged, auto throttles engaged and in a stable approach, the auto throttles inexplicably go into TOGA mode. It is as if I pressed the go around button, except that I didn't. This is not an always repro, but today it happened several times. The first time, I went around and the auto throttles behaved correctly on the subsequent approach and landing. The second time (at a different airport), I thought things were behaving correctly as the aircraft maintained appropriate speed and I retarded the throttles at 20 feet. I engaged full reverse (short runway), and then I realized the engines didn't reverse and instead were spooling up to TOGA despite the throttles being in reverse. I quickly slammed the throttles to TOGA and went around for a third try at the approach. This time, the auto throttles would not fly green dot speed (even though I confirmed that I was in approach phase) so I had to manually set my approach speed and was able to finally land.

I've attached a screenshot showing the problem. Note that the FMA appears to be as expected, but the EWD shows TOGA power has been applied. Auto throttles can be seen to be engaged and the throttles are in the climb detent (not visible from the screen shot). 

I have hundreds of sim hours in A32NX, so I don't think this is a case of operator error. I've never experienced this behavior before the last few builds.

### Expected behavior

I expect the auto throttles to maintain the approach speed until I retard the throttles, at which point, I expect the auto throttles to disconnect.

### Steps to reproduce

Set up for an ILS approach with auto pilot engaged, auto throttles engaged, throttles in climb detent
After decel waypoint, confirm the aircraft is in approach phase, speed in managed, and allow aircraft to decelerate to 200KIAS
Press the approach button and allow the auto pilot to perform localizer and glideslope intercept
At 10nm go to flaps 1
Once the airspeed falls below the orange "eyebrows" set flaps 2
As the glide slope comes in, gear down
Set flaps 3 followed by flaps full
Aircraft should decelerate to approach speed
At the 1000' callout disconnect the autopilot
Uncommanded TOGA may occur at any point during the remainder of the approach
Disconnecting the auto throttles will work at that point, but it will likely be too late to save the approach.

### References (optional)

![toga-bug](https://user-images.githubusercontent.com/11096477/126053794-6f627b21-2e03-4b29-b7ec-2fa37cb26861.png)

### Additional info (optional)

Hardware is Thrustmaster TCA Quadrant

### Discord Username (optional)

geoffda

**Comment by lukecologne** [comment]
Please upload an FDR file from a flight where this occured, a video might also be helpful (see [here](https://docs.flybywiresim.com/start/autopilot-fbw/#reporting-issues) for where to get the FDR file). In the image you posted it looks like the thrust levers are outside the A/THR active zone (i.e. somewhere between CLB/MCT or between MCT/TOGA), can you confirm this is not the case? (Could also maybe be a hardware issue)

**Comment by geoffda** [comment]
Hmm, GitHub doesn't seem to allow me to upload the .fdr file. Is there some trick to it? 

I may well have instinctively pulled the throttles out of the climb detent when auto throttles went to TOGA, but I don't remember. I'll try recalibrating them tomorrow to see if that makes a difference. If not, I'll see if I can get a video for you.

**Comment by lukecologne** [comment]
Just use any file hosting service and post the link

**Comment by lukecologne** [comment]
Just use any file hosting service and post the link

**Comment by AdamNZ** [comment]
I've had this happen n most of my flights lately. For this last one, I've enclosed the FDR files etc. 
{
  "built": "2021-07-17T21:22:24+00:00",
  "ref": "master",
  "sha": "652d1a2a90d476478480dc4eddaf9b452a329421",
  "actor": "Benjozork",
  "event_name": "manual"
}

Enclosed are the FDR files etc.

A few issues with this flight (NZAA-NZWN - my usual "test flight"):

35' MCDU didn't clear KARRL - had to manually remove it then proceed to LADIT as per normal.
45' LADIT was skipped and the MCDU went straight to HECTA.
46' Throttle lever went to IDLE (uncommanded).
47' Throttle lever went to CLB (uncommanded) - and started acceleraqting/racing. Auto/throttle disconnected around here somewhere.
    Had to manually put the throttle into IDLE to reduce speed.
48' Had to manually select CLB and re-enable autothrottle.
57' APPR mode didn't auto-engage, so activated it manually (unusual, this - as it isn't normally a problem).

Full ILS landing completed without any problems.

**Comment by lukecologne** [comment]
The thrust levers went to idle, but the A/THR itself worked as expected. I don't know why this happened, I would speculate either a hardware problem, or a problem with the throttle configuration. As for the other problems you mentioned, they are not really related to this issue, but rather with the flight management.

**Comment by AdamNZ** [comment]
No ... it's definitely not a hardware problem. I've run the same (test) flight many times with an add-on that shows control inputs - and nothing gets sent by the hardware - yet you can see the thrust going up gradually (uncommanded) up to and around the time when the a/thr disconnects.

Sorry - I shouldn't have added the other (unrelated) flight plan problems to this topic.

**Comment by lukecologne** [comment]
Well, from what I can tell from the FDR data is that at around 2860 seconds, the A/THR was disabled from the thrust levers being set to idle, thus disengaging A/THR. Then, at around 2950 seconds, they were set to the CLB detent again, without re-engaging autothrust, so the engines spooled up to CLB thrust. Then, a few seconds later, A/THR was re-engaged, and the engines began to spool down. Then, A/THR was disengaged again by the thrust levers being set to idle (although the engines were already at idle at that point). Then, A/THR was re-engaged, and the flight continued. A video would be good to clarify the issue.

**Comment by AdamNZ** [comment]
Yes - it does look like things started going weird when the thrust lever was moved back to idle (uncommanded). I was nowhere near the keyboard or controls at the time, but saw the lever physically slide back. Much of what happened *after* that was me manually trying to recover the situation.

I'll do some more tests. It's been a long time since I've recorded a video in a sim ... what do you recommend?

**Comment by lukecologne** [comment]
If you have an nvidia GPU you can use the nvidia overlay to record, it's pretty simple to set up. Or, you can use OBS, it's open source but a bit more complicated to set up. You can upload it to youtube, or to a file sharing service, or if you don't want to share your youtube account, you can also upload to https://streamable.com/

**Comment by AdamNZ** [comment]
Thanks for that ... I was thinking of using the nVidia overlay, but will try OBS as well. For the benefit of others, the URL for that is: https://obsproject.com/welcome

**Comment by lukecologne** [comment]
For your info, if you open the MSFS console (enable devmode, then go to windows, then console I think), you should be able to see the events (like the throttle lever event) logged by the FBW/AP wasm module. Those could be helpful in debugging

**Comment by geoffda** [comment]
I'm still trying to figure out what is going on, but I suspect it may be hardware in my case. I saw uncommanded throttle movement in other airplanes today, so I'm now thinking that all of the problems are the same.

**Comment by AdamNZ** [comment]
I had a similar thing happen in the PMDG DC-6. Again - I was nowhere near the controls. My current theory is that it's Asobo/MSFS-related - not specifically a hardware issue, more a case of the sim losing track of something, then attempting to do a rapid "catch-up".

Sod's law - I had all my video recordings set up and running and the flight went without a hitch!!! However - I'll keep trying to film this annoying little problem ...

**Comment by tracernz** [comment]
Triple-check you don't have anything else bound to any of the throttle axis inputs (Throttle Axis, Throttle Axis 0-100%, etc.).

**Comment by AdamNZ** [comment]
> Triple-check you don't have anything else bound to any of the throttle axis inputs (Throttle Axis, Throttle Axis 0-100%, etc.).

Checked and triple-checked (a fair few times over the last few months).

{
  "built": "2021-07-19T09:09:21+00:00",
  "ref": "master",
  "sha": "8db12ddd9ebadf9e659881d2073765a6ce295405",
  "actor": "Benjozork",
  "event_name": "manual"
}

Enclosed are the FDR files etc.
https://www.dropbox.com/s/7li5y7z5smcfhc4/FBW_fdr_adamNZ_02.zip?dl=0

Around 27'40 on the chronometer:
The throttle races for no obvious reason.
https://youtu.be/-z-0YJbzXcQ

Around 37'56 on the chronometer:
Throttle goes to idle (uncommanded) then auto-throttle disconnects.
https://youtu.be/pJe0oKHD7Yk

For anyone looking at the fdr file(s) ... ignore everything after around 40' ... I mistakenly hit F9 (flaps) when I meant to hit Alt-F( (record) - and my final approach was a shocker as recording knackered my framerate.

**Comment by AdamNZ** [comment]
Any progress on this? I'm getting mutliple a/t disconnects now on every flight - making the 320 pretty well unflyable. I've checked my bindings and tried various dead-zones in sensitivity ... and have run out of ideas. Anything else I could be looking it?

**Comment by aguther** [comment]
You said that you experienced the same with the DC-6. Now why do you think it’s still an issue of the A32NX?

For me it’s a proof that it’s either an issue of MSFS with your hardware or your hardware itself…

**Comment by geoffda** [comment]
I don’t. I said I agree that it is probably hardware. I’d close the issue, but somebody else was having similar issues that they don’t think is hardware.

**Comment by AdamNZ** [comment]
> You said that you experienced the same with the DC-6. Now why do you think it’s still an issue of the A32NX?
> For me it’s a proof that it’s either an issue of MSFS with your hardware or your hardware itself…

The issue I had with the DC-6 was the throttle *racing* - not an a/t disconnect ... and I only saw it happen once.

A while back (and a few builds ago), I never had these problems with the A32NX (Dev) ... but the problem has got steadily worse. Other than checking/re-checking my controller bindings, nothing on my system has changed.

**Comment by aguther** [comment]
@geoffda Sorry I was answering to @AdamNZ.

Whatever throttle racing is....but the sentence was "I had a similar thing happen in the PMDG DC-6". The A/THR disconnects when thrust levers are put at idle, also when this is for a short time. That could be the reason for your disconnect.

I suggest to recheck your throttle config, it looks a bit strange to me, because you do not use the full range:
```
[throttle_common]
reverse_on_axis = true

[throttle_axis_1]
reverse_low = -0.229951
reverse_high = -0.169951
reverse_idle_low = -0.150000
reverse_idle_high = -0.090000
idle_low = 0.270000
idle_high = 0.430000
climb_low = 0.543252
climb_high = 0.623252
flex_mct_low = 0.700000
flex_mct_high = 0.780000
toga_low = 0.970000
toga_high = 1.000000

[throttle_axis_2]
reverse_low = -0.229951
reverse_high = -0.169951
reverse_idle_low = -0.150000
reverse_idle_high = -0.090000
idle_low = 0.270000
idle_high = 0.430000
climb_low = 0.543252
climb_high = 0.623252
flex_mct_low = 0.700000
flex_mct_high = 0.780000
toga_low = 0.970000
toga_high = 1.000000
```

Beside that it seems you didn't change the default throttle config for an older experimental version. Based on that information I question that the config is as it should be for your setup.

In the FDR files you've provided (which is 4 files but only 1 actual flight), there is only one disconnection of the A/THR and it's due to the throttles being set to 0:
![image](https://user-images.githubusercontent.com/6629914/126739483-0408edae-cea8-43ba-9ae8-647fd76e9c28.png)
![image](https://user-images.githubusercontent.com/6629914/126739552-e599d5fb-5520-4d0b-8d1b-bec856a1810c.png)

Now this is what the A32NX receives based on events from MSFS. If you now say I don't do anything, I suggest opening a ticket with MS, because there is nothing that can be done if those events are received that like and but hardware didn't move. It's clearly an MSFS issue then.

**Comment by AdamNZ** [comment]
Thanks for the info! I started again from scratch. For the benefit of others, here's what I did:

1) Basic X52 Pro calibration in Windows (checked no deadzones etc. - all looked OK).
2) Checked that FSUIPC wasn't processing the throttle axis (it wasn't).
3) Checked for any unwanted keybindings in MSFS (none found).
4) Reset axis sensitivities in MSFS (set deadzone to zero for the next step).
5) Recalibrated via the pad.

This gave me a more orthodox ini:
[Throttle]
Log = true
Enabled = true
ReverseOnAxis = false
ReverseIdle = true
DetentDeadZone = 2.0
DetentReverseFull = -1.00
DetentReverseIdle = -0.90
DetentIdle = -1.00
DetentClimb = 0.89
DetentFlexMct = 0.95
DetentTakeOffGoAround = 1.00

[throttle_common]
reverse_on_axis = true

[throttle_axis_1]
reverse_low = -1.000000
reverse_high = -0.950000
reverse_idle_low = -0.048311
reverse_idle_high = 0.011689
idle_low = 0.135190
idle_high = 0.255190
climb_low = 0.478503
climb_high = 0.578503
flex_mct_low = 0.662830
flex_mct_high = 0.762830
toga_low = 0.970000
toga_high = 1.000000

[throttle_axis_2]
reverse_low = -1.000000
reverse_high = -0.950000
reverse_idle_low = -0.048311
reverse_idle_high = 0.011689
idle_low = 0.135190
idle_high = 0.255190
climb_low = 0.478503
climb_high = 0.578503
flex_mct_low = 0.662830
flex_mct_high = 0.762830
toga_low = 0.970000
toga_high = 1.000000

===========================

Only managed one test flight (so far) but it behaved *perfectly* - so many thanks for the input! I'll continue to test - and maybe add a small deadzone (15%?) in MSFS.

BTW - as regards fdr files ... I seem to get multiple files even with the same flight. Should I be sending just the last/latest?

Once again, thanks for your patience!

**Comment by MisterChocker** [comment]
Closing since issue has been resolved.
