### ISSUE TITLE
Autopilot banks hard right when updating flight plan mid flight - e.g. adding arrival data, direct to waypoint

### ISSUE THREAD

**Issue by iangarratt** [flybywiresim/a32nx#5345]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-17T21:22:24+00:00",
  "ref": "master",
  "sha": "652d1a2a90d476478480dc4eddaf9b452a329421",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

During flight when inserting arrival data (runway / STAR) or if you insert a DIR waypoint the aircraft starts banking right (making my passengers scream in self loading cargo which does give me a sense of joy) and it just seems to continue banking right. I have found if you then immediately reinsert the next waypoint in the DIR it will re-establish its LNAV control correctly.

If this isn't a known / common bug I can upload a video of it happening, and note I have done a fresh install and clear community folder before submitting this report, issue persists after fresh install.

### Expected behavior

Follow LNAV until new flight data is inserted

### Steps to reproduce

1. Fly
2. En-route to a waypoint / VOR update arrival data, or select DIR
3. Enjoy the sweet sweet sound of your passengers screaming

**Comment by GuillemPallares** [comment]
I had the same behaviour but I had it when instructed to change LDG RWY and STAR mid flight, and suddenly started banking LEFT. I recovered control as you say, DIR to next WayPoint.

**Comment by iangarratt** [comment]
> 
> 
> I had the same behaviour but I had it when instructed to change LDG RWY and STAR mid flight, and suddenly started banking LEFT. I recovered control as you say, DIR to next WayPoint.

Interesting, mine always seems to bank right. I might try on my next flight (in 2 hrs when turned around) to play about with it at various times in the flight and see if i can reproduce it as you say after the message in the MCDU.

**Comment by tracernz** [comment]
The sims built in flight plan manager is a bit of a black box and we can’t control much of its behaviour. We have our own flight planning and guidance system in progress at the moment, so please hold on until then.

**Comment by iangarratt** [comment]
> 
> 
> The sims built in flight plan manager is a bit of a black box and we can’t control much of its behaviour. We have our own flight planning and guidance system in progress at the moment, so please hold on until then.

No worries, thanks for letting us know! I'll close this issue pending the update! Cheers for the work you guys put in!
