### ISSUE TITLE
AP not following G/S

### ISSUE THREAD

**Issue by LukasGNN** [flybywiresim/a32nx#5348]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-17T21:22:24+00:00",
  "ref": "master",
  "sha": "652d1a2a90d476478480dc4eddaf9b452a329421",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

AP not following G/S. No respons to G/S. THe airplane follows the center line but not descenting acc to G/S
![bilde](https://user-images.githubusercontent.com/46678717/126075387-d85c7579-92e2-4205-afb8-00d47e45beae.png)

I have  set up STAR with both managed and selected mode, turned on/off AP during approche. checked correct rex for ILS.
No clue what alse can be done. 

### Expected behavior

Descent acc to G/S

### Steps to reproduce

1. AP on
2. Tunes ILS freq
3. Press APP

**Comment by tracernz** [comment]
G/S* mode hasn't engaged because you haven't come close enough to the G/S. You have to put the aircraft on a path to intercept and only once G/S* engages will the autopilot actively start to track the G/S.

**Comment by LukasGNN** [comment]
Are you sure about that?
how close do i need to be? here i was 7NM from the rwy. Otherwise the ILS indicator "went throught"  the yellow line (from top to the shown position). 
After that point i had to descent 2400ft/min to manage to land otherwise i would over shoot the landing.

**Comment by lukecologne** [comment]
Yes, to capture the glideslope you need to be capturing or be established on the localizer, which, in the picture, you are not. Please note that GitHub is not for support, for that, please go to our discord server.
