### ISSUE TITLE
[BUG] ND PLAN mode centered on wrong waypoint

### ISSUE THREAD

**Issue by AdenFlorian** [flybywiresim/a32nx#535]
**Mod Version**

master

**Describe the bug**

The ND in PLAN mode should be centered around the 2nd waypoint (TG002) from the top in the flight plan page on the MCDU, but it is centered on the first waypoint (TG030).

![image](https://user-images.githubusercontent.com/3533988/92556025-8a3ea480-f22e-11ea-9fd2-3c82c0456864.png)

**References**

Tiago A320 pilot in discord

**Additional context**

**Comment by Benjozork** [comment]
note: the scrolling is already broken as the centered waypoint is the `(n+1)`th one in the list after scrolling through the list `n` times

**Comment by MisterChocker** [comment]
this has been fixed
