### ISSUE TITLE
Autoland Flare Issue

### ISSUE THREAD

**Issue by ViperAUT** [flybywiresim/a32nx#5360]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-05-05T23:03:06+00:00",
  "ref": "v0.6.1",
  "sha": "4a1cccc90ab3997109e394402ab9b41a80fbf325",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

After usually handlanding my aircraft, i decided to try the autoland function these days, and on both occasions, while the aircraft was fully configured and the approach was stable, the aircraft in all its wisdom decided it is a great idea to pitch the nose down instead of up during flare.

### Expected behavior

Well, a nose up attitude at flare during autoland ;)

### Steps to reproduce

the aircraft was fully configured for a full flap landing at radio altimeter of about 1500
localizer and glideslope was captured
the approach was stable and as expected until the 50ft callout
there, the aircraft entered flare mode and pushed the nose down

**Comment by lukecologne** [comment]
Autoland does not work in the stable version. Please use the current development version for our custom AP/FBW system, which supports autoland.

**Comment by ViperAUT** [comment]
Holy hell, that was fast... thank you!
