### ISSUE TITLE
Cabin

### ISSUE THREAD

**Issue by Mrhaidar** [flybywiresim/a32nx#5364]
### Describe the bug

When i press ALL button to check if the cabin is ready
I see on ecam cabin is ready
But i don't hear the message from pilot
"Cabin crew please take your seat for take off"
On stable version no issue

### Steps to reproduce

Reinstall many times
Press the All button many times

### Discord Username (optional)

Mrhaidar

**Comment by Benjozork** [comment]
Template not followed properly

**Comment by Mrhaidar** [comment]
I don't understand

**Comment by Benjozork** [comment]
The bug reporting form has many fields that were not filled.

Please add the missing information so I can re-open your issue.

**Comment by Mrhaidar** [comment]
Sorry about that but i don't understand everything in the form
Can i explain the issue directly for you?

**Comment by Benjozork** [comment]
I think I get what you mean. It sometimes does not work properly. Can you try pressing the FWD button and then the ALL button ?

**Comment by Mrhaidar** [comment]
I tried to many times
The problem just on development version
When i switch to stable version everything work fine

**Comment by Mrhaidar** [comment]
Please if you know how i can resolve this issue please let me know

**Comment by Mrhaidar** [comment]
Hello
Any update on this?

**Comment by sidnov** [comment]
At the moment, we only have 1 report about this. And none of the members are able to reproduce this issue. We really cannot do anything about it. Try using the mod without any other mods to rule out mod conflict. Check the sound volumes in the EFB settings.
