### ISSUE TITLE
Approach button

### ISSUE THREAD

**Issue by JustiETS2** [flybywiresim/a32nx#5370]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-21T23:15:28+00:00",
  "ref": "master",
  "sha": "ce44f46607ba7f309c53d4be0b5f371dee7948b3",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

Approach button on FCU doesnt work.

### Expected behavior

After I clicked approach button, I expected it to turn green.

### Steps to reproduce

1. Batteries and ground power on
2. Clicked on approach button on FCU

**Comment by aguther** [comment]
Why do you want to engage APPR on ground?

**Comment by donstim** [comment]
And you need to be above 400 ft radio altitude.

**Comment by tracernz** [comment]
Needs > 400 ft RA, ILS/LOC tuned, and not TOGA thrust, as above.
