### ISSUE TITLE
Import OFP via simbrief button on flypad not working

### ISSUE THREAD

**Issue by magoosteruk** [flybywiresim/a32nx#5373]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-21T23:15:28+00:00",
  "ref": "master",
  "sha": "ce44f46607ba7f309c53d4be0b5f371dee7948b3",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

Navigraph and simbrief subscriptions linked fine

Launch flypad
press green simbrief button on front page of flypad to bring in OFP from simbrief into flypad
Nothing happens
Can still bring in OFP using import functionality within MCDU directly but nothing in flypad

### Expected behavior

OFP should populate on flypad by clicking green simbrief button

### Steps to reproduce

launch flypad
click green simbrief button on main page
nothing happens

### Discord Username (optional)

magoosteruk

**Comment by Pat15250** [comment]
Hello,
Normaly it works perfectly: But have you filed your Simbrief Username in settings section of the flypad ?
Best regards.
Patrick

**Comment by magoosteruk** [comment]
Hi Patrick
Ignore me, I hadn't done that. I set up the navigraph page on the flypad and assumed it was carrying over my username to the main page. Totally missed the simbrief box on the settings page new flypad version! Works perfectly.
Many thanks, keep up the great work!

**Comment by MisterChocker** [comment]
Closing since issue resolved
