### ISSUE TITLE
CLB detent not working in climb & losing 3000kg of fuel during 

### ISSUE THREAD

**Issue by NvTacticalz** [flybywiresim/a32nx#5374]
### Aircraft Version

Development

### Build info

```json
No idea what this is I'm afraid....its the FBW A20N developmental version (the most up to date one)
```

### Describe the bug

From EGCC (Manchester)  to EDDL (Dusseldorf) - CLB thrust engaged and climbing to FL370. Aircraft went from holding 280kts on climb and dropped down immediately to 210kts, causing the aircraft to stop climb. Throttles were in CLB detent but showing 42% thrust and would not increase, auto pilot disengaged to rectify and auto thrust disabled but throttles would not increase. Anti ice not on.  Occurred 3 times  and after around 5 mins the thrust engaged and the aircraft climbed. Also took approx 3000kg of fuel from the aircraft. 

### Expected behavior

Aircraft to accelerate from 250kts to 280kts in CLB detent and maintain CLB until reaching cruise.

### Steps to reproduce

Waypoint East of HON at FL270
Waypoints over the North Sea at FL350
Aircraft eventually reached cruise before EHAM.

**Comment by NatalieGates** [comment]
This is happening to me as well today. The exact same issue as described by @NvTacticalz accept my aircraft never engaged and I was using the stable version not the developmental version. I have been flying for the past week with zero issues. The only thing I can think of is that I updated the nvidia driver. I'm hoping that's not the issue because I don't want to revert back.

Personal Note: It's very frustrating because this is the only reliable aircraft in the sim atm and if it stops working the sim becomes useless for me.

**Comment by Saschl** [comment]
Please check your SAT and ISA temps on the lower ecam. MSFS live weather has been crazy today which likely causes your issues. Use a static preset in the weather menu if possible

**Comment by NatalieGates** [comment]
You know that might be it. Because when it happens it feels like a massive gust of wind smashes into the plane. Then all things go crazy.

![fbw](https://user-images.githubusercontent.com/47909481/126724035-78a6eb79-af0d-4472-86c3-93a3eba230f2.gif)

**Comment by tush0701** [comment]
Happening to me too. Aircraft refused to climb, and thrust levels reduced even when set to CLB. Windy conditions.

**Comment by Skkkitzo** [comment]
This appears to be a problem game-wide and not just limited to the A32NX, Microsoft acknowledges that there can be problems with the way they obtain weather information which can be found [here](https://support.microsoft.com/en-us/topic/known-issues-with-the-real-world-weather-feature-in-flight-simulator-49564ea2-62bf-ea99-c951-362b66a3e1ad).

**Comment by NvTacticalz** [comment]
My issue wasn't a gust of wind or the weather. ISA & SAT temperatures across the UK yesterday were find and a 5 mile tailwind expected eastbound.
The aircraft just decided the throttles didn't want to work and as stated the throttle % was at 42 and would not go up until after about 5 mins each time when whatever the bug was it allowed the throttle to reach 89% CLB thrust which then allowed the aircraft to climb in CLB detent. 
First time this has happened after hundreds of hours of flying the FBW and a number of weather conditions. On descent there were no issues.

**Comment by NvTacticalz** [comment]
For me the aircraft was stuck....no changes in N1 and they remained at a frozen point (Inc the throttle). Moved to FLEX & TOGA to avoid a stall but throttle did not increase past 42%. Throttle percentage increased using FLEX and TOGA detents but aircraft ISA did not increase past 220kts at and above FL270. 
The bug also removed 3000kg of fuel (in the space of 30 miles flight) causing a mid fuel change to ensure the destination was reached. 
Once the bug disappeared throttle percentages were increased back to 85+% and CLB speed to 280kts reached. 
As said, there were no differences in N1 (as shown by another user) so the wind or weather in the game was not a factor (as there was wind Cruise expected of T3).

**Comment by Skkkitzo** [comment]
Can you confirm that TAT and SAT are below 0?

**Comment by Phil7789** [comment]
> For me the aircraft was stuck....no changes in N1 and they remained at a frozen point (Inc the throttle). Moved to FLEX & TOGA to avoid a stall but throttle did not increase past 42%. Throttle percentage increased using FLEX and TOGA detents but aircraft ISA did not increase past 220kts at and above FL270.
> The bug also removed 3000kg of fuel (in the space of 30 miles flight) causing a mid fuel change to ensure the destination was reached.
> Once the bug disappeared throttle percentages were increased back to 85+% and CLB speed to 280kts reached.
> As said, there were no differences in N1 (as shown by another user) so the wind or weather in the game was not a factor (as there was wind Cruise expected of T3).

I had this exact same issue yesterday. My fuel flow was ~ 4.000 kg/h for each engine and the aircraft was almost stalling / not accelerating. In my case this was due to the wrong temperatures from live weather (check the lower ecam, ISA is not your speed but International Standard Atmosphere).
Also it is possible that you encountered another bug everything you describe matches perfectly the wrong outside temperatures (SAT, TAT and ISA should not be positive during climb, they should get colder the higher you get as Skkkitzo mentioned). Setting the weather to clear sky is a good workaround and instantly corrects the temperatures.

**Comment by 2hwk** [comment]
Try again on the clear skies or any weather preset. The issue with outside temperatures on live weather is intermittent. It's not something we can do anything about sadly.

**Comment by NvTacticalz** [comment]
The outside temp I do not recall I'm afraid (on all of them). So it may be this (confused why the sim removed so much fuel). Will fly the same route again this aft and let you know. Never had any problems previously on climb, just yesterday.

**Comment by Skkkitzo** [comment]
Please do let us know the outside temperature, as it is very likely to be the problem. MSFS2020's weather reporting system has been broken for about 24 hours now giving very high temperatures at all altitudes.

**Comment by Pat15250** [comment]
Hello, I'am actually flying between DIAP and FNLU: The same bug appeared after T/O: During climb with climb detend, it was 77% N1, Fuel Flow: more than 4000 Kg/h/engine and even by switching detend to TOGA, it was very difficult to climb. 
Actually, FL 310 established, TAT=+1°C, SAT=-30°C, ISA=+17°C with real weather.
For information, ZFW=61000 Kg, TOW=73887 Kg and cost index=60.
See you soon,
Patrick

**Comment by Skkkitzo** [comment]
Maybe try pre-set weather to see if it solves the problem?

**Comment by NvTacticalz** [comment]
im just about to send you screen shots of EGCC to EDDL (currently fliying now)

**Comment by NvTacticalz** [comment]
![at FL115](https://user-images.githubusercontent.com/77071002/126805597-8e91531b-ebe3-4a56-b3f5-9be79f60797c.png)
![at FL200](https://user-images.githubusercontent.com/77071002/126805631-08a3e88a-49b2-45fc-851c-2fcf4d21a8e9.png)
![at FL300 Honley](https://user-images.githubusercontent.com/77071002/126805656-e6bfd636-4131-485a-8dc8-f9c09b27781f.png)
![at FL350  - cruise is FL370](https://user-images.githubusercontent.com/77071002/126805675-3630dad5-2922-49e1-bdb1-883f472d1d64.png)

**Comment by NvTacticalz** [comment]
No issues today, aircraft maintained CLB detent thrust from FL100 to FL370 and fuel flow at 600 for each engine.

**Comment by Skkkitzo** [comment]
Maybe they have fixed their live weather service. Who knows.

**Comment by NvTacticalz** [comment]
who knows but seems to be an issue that is affecting the aircraft. If it occurs again i will report it.

**Comment by Pat15250** [comment]
Thanks for the pictures: your temperatures seem to be in adequacy with reality.
I can't preset weather now, because I'm logged on IVAO, but I'll try a few later.
Patrick

**Comment by NUTTTTTTTT** [comment]
> who knows but seems to be an issue that is affecting the aircraft. If it occurs again i will report it.

Just to clarify on previous points made by the FBW team, this is a current issue with the live weather data in MSFS and will affect most if not all aircraft as the issue isn't based on the aircraft, more the air around it.

The current solution while the data is crazy is to use a weather preset, otherwise you find the temps are all over the place, you can barely get any thrust, and climbing/maintaining airspeed becomes almost impossible at higher altitudes, hopefully Asobo get's it sorted soon. :)

**Comment by olski320** [comment]
MSFS2020 weather engine seems to not be working properly today as well. Look at the screenshot: ISA +72 at FL350! 

FL350 ISA temp is -55, here it's 72 deg warmer, hence engines are burning almost 4t each. I hope they will fix it soon.

![Screenshot (2042)](https://user-images.githubusercontent.com/72993299/126809390-43ed117e-be88-4a22-839a-d6d7aa5ee87c.png)
