### ISSUE TITLE
climb thrust/rate/vs

### ISSUE THREAD

**Issue by youngryan7** [flybywiresim/a32nx#5378]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-23T01:56:21+00:00",
  "ref": "master",
  "sha": "654061fb237cfa03b4daa89afe1fe9c980bccb4e",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

during climb not able to keep speed or climb rate - not sure if its a fs2020 weather issue and pressure or fbw 

### Expected behavior

climb speed and thrust to remain the same with vs changing to keep speed

### Steps to reproduce

set up aircraft
climb to cruise level
check thurst % and speed on climb and v/s

### References (optional)

![2021-07-22 (1)](https://user-images.githubusercontent.com/59422760/126758492-a947bca7-9cfa-49b5-9ba3-7c3ada6b216a.png)
![2021-07-22 (2)](https://user-images.githubusercontent.com/59422760/126758496-05ac629f-1415-4a4b-a9f9-0cd9f701d0a3.png)
![2021-07-22 (3)](https://user-images.githubusercontent.com/59422760/126758501-9a94c112-031b-4395-b3cf-df20507e0351.png)
![2021-07-22](https://user-images.githubusercontent.com/59422760/126758503-304965ae-b354-43c2-b28d-e2ed7b94130d.png)
![2021-07-23](https://user-images.githubusercontent.com/59422760/126758509-447caa6a-9a3e-4b31-ab9c-2c315c9f7fdc.png)

### Additional info (optional)

was working fine before it does switch so not sure if its a weather issue speed will be 290 on climb then suddenly drop to 220 and thrust not at 90% on climb around 80%
i know you've just updated pressure in the fbw so not sure if thats the issue or fs2020

**Comment by youngryan7** [comment]
also check OPT FL in FMGS

**Comment by Benjozork** [comment]
MSFS live weather issue as you can see on your outside temperature.
