### ISSUE TITLE
ADIRS not aligning

### ISSUE THREAD

**Issue by FgPunisher** [flybywiresim/a32nx#5387]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-24T10:58:59+00:00",
  "ref": "master",
  "sha": "144d0c36f2a3f26cbdee7e3e4b039917ef499a20",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

ADIRS wont align.

Display is stating IR 1+2+3 in att align. 

### Expected behavior

While switchen the ADIRS to NAV they should load normaly. Display should also state alignment in progress ang give some time indication. Last version worked so seemes to me to be buged.

### Steps to reproduce

1. Switching ADIRS to OFF then to NAV
2. Changing Realism settings

**Comment by davidwalschots** [comment]
Could you provide a screenshot of the overhead panel and ECAM?

**Comment by FgPunisher** [comment]
Unfortunately I could not reoroduce this issue. The last flight I tried was running as expected. Maybe it was due to some issue on my side.
