### ISSUE TITLE
Make pixelated screens optional

### ISSUE THREAD

**Issue by foxmike80** [flybywiresim/a32nx#5389]
### Aircraft Version

Development

### Description

The new pixelated screen give me a horrible looking moiree effect on my screen. Any chance to make that optional in the aircraft settings?

**Comment by bouveng** [comment]
@foxmike80 Hi. What resolution are you running sim in?

**Comment by foxmike80** [comment]
> @foxmike80 Hi. What resolution are you running sim in?

2560x1440 at 80% render scale. 

This gives me the best quality/performance ratio on my 32" 4K screen.
Don't get me wrong, I totally like the idea of pixalated screens as this adds to immersion and most people will love it. I just would like to have the possiblity to opt out of that feature as the moiree effect totally kills my immersion.

**Comment by bouveng** [comment]
@foxmike80 Okay. And you you run `2045x1152` @100% ? Same effect then?
There is a fix out, soon, that lowers the opacity on the pixel effect. Lets see if that makes it better for you.

**Comment by bouveng** [comment]
Fix that lowers the opacity of the pixel-effect is now in development branch.

Is the moiré effect still significant?

**Comment by foxmike80** [comment]
Thanks a lot for looking into this. This is much appreciated. The fix helped a lot, but the effect is still there - but much better. I tried other resolutions and render scale settings an it never really disappears. However, it is now at a level I really can live with. Thank you.
