### ISSUE TITLE
Turning off right PFD also disables left one.

### ISSUE THREAD

**Issue by marcsoler** [flybywiresim/a32nx#5390]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-24T10:58:59+00:00",
  "ref": "master",
  "sha": "144d0c36f2a3f26cbdee7e3e4b039917ef499a20",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

Decreasing the FO's PFD to 0% turns off the captain's PFD. Same doesn't happen vice-versa. Turning the Captain's PFD off doesn't affect the FO's PFD. Doesn't happend with the ND.

### Expected behavior

Captain's PFD shouldn't turn off.

### Steps to reproduce

Decrease FO's (right) PFD to 0%.

### Additional info (optional)

This issue didn't happend in the dev version last week. (I usually turn off the FO's PFD and ND

### Discord Username (optional)

Th3Alchemist#2043

**Comment by tshomas** [comment]
Confirmed issue from multiple users on Discord.

**Comment by youngryan7** [comment]
also climbing and now showing vs
![2021-07-25 (2)](https://user-images.githubusercontent.com/59422760/126895097-5ed8d0a8-a980-4ba0-8dcb-4d491adfaeb5.png)

**Comment by Benjozork** [comment]
Yes, this issue is already reported.

**Comment by 2hwk** [comment]
We've found the cause, fix coming soon.

**Comment by bouveng** [comment]
@marcsoler Fix is in deveopment branch now.

**Comment by marcsoler** [comment]
> @marcsoler Fix is in deveopment branch now.

Nice work! Thanks
