### ISSUE TITLE
Throttle axis value stepely change when the main app window looses/gets focus

### ISSUE THREAD

**Issue by marquinhosue** [flybywiresim/a32nx#5393]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-24T15:49:50+00:00",
  "ref": "master",
  "sha": "aa817de90d5bf2eaad6d7b9e069d70e524e4ae3d",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

When I change the focus between the main msfs app window and the IVAO client window, the throttle axis value stepely change. First time I got this situation was during an ILS approach, and on the short final I went FLEX. Other times, being at the iddle position the REV suddenly starts. I am using the logitech extreme 3D pro, Altitude 1.10.4b (IVAO client) and msfs is up to date. I think, I had a similar behaviour several days ago but always the sim window lost focus, no matter the app I am clicking on. Today, as far as I could check, this behaviour is only happening with the IVAO client. 
My detent values, if needed: 1  0.96, 0.84 0.72, 0.67 0.07, 0.03 -0.37, -0.63 -0.83, -0.97 -1.

https://user-images.githubusercontent.com/70656524/126880475-b4f68c2d-0903-4d4a-9eda-a0f065504e3c.mp4

### Expected behavior

Axis value would remain unchanged

### Steps to reproduce

1. Just start at an airport, even cold and dark, and do nothing except exchanging the window app focus between msfs2020 main window and the IVAO pilot client window.

**Comment by aguther** [comment]
The events the A32NX is receiving are provided by MSFS, it does not query input controllers itself. That means the issue you are seeing is with a very high probability caused by MSFS somehow.

Some ideas for things you can check:
- did you assign your hardware in MSFS or via FSUIPC or such?
- does it happen in other planes as well?
- are there any unintended double bindings with buttons or even other axis or anything?

**Comment by marquinhosue** [comment]
Dear aguther, thanks for your reply. It is certainly a msfs - hardware config issue. Nothing particular concerning the a32nx.
Thanks again for your time, sorry :(.
Closed.
