### ISSUE TITLE
VSI indicators looks locked at 0 ftm

### ISSUE THREAD

**Issue by Cassiano-Gunji** [flybywiresim/a32nx#5395]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-24T20:18:52+00:00",
  "ref": "master",
  "sha": "05a0bbda844850568c82ae6dab6217e509a46aa2",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

The VSI on the PFD of both the captain and first officer seems stuck at 0 ftm (they actually move, but very little). It seems they've been applied the wrong multiplier. On external view, the virtual VSI  works as expected.

### Expected behavior

The VSI should display the correct vertical speed.

### Steps to reproduce

1. Spawn anywhere
2. Pitch up or down
3. Watch as VSI indicator moves very little as attitude changes.

### Additional info (optional)

I've missed a few PRs, so I can't tell on which one exactly this problem started for me.

### Discord Username (optional)

CassiKess

**Comment by AdamNZ** [comment]
Same here ...

{
  "built": "2021-07-24T20:18:52+00:00",
  "ref": "master",
  "sha": "05a0bbda844850568c82ae6dab6217e509a46aa2",
  "actor": "davidwalschots",
  "event_name": "manual"
}

**Comment by BjoernHund** [comment]
{
  "built": "2021-07-24T20:18:52+00:00",
  "ref": "master",
  "sha": "05a0bbda844850568c82ae6dab6217e509a46aa2",
  "actor": "davidwalschots",
  "event_name": "manual"
}

![image](https://user-images.githubusercontent.com/20350757/126888372-8d46d3eb-8f00-4110-ac12-c745b9526552.png)

I have the same problem. The indicator for the VS shows 0 ftm.  Everything else works fine.

**Comment by Watsi01** [comment]
We are aware of that. Working on a fix.

**Comment by AdamNZ** [comment]
Confirmed FIXED ... many thanks!
