### ISSUE TITLE
Problème de manche/Joystick problem

### ISSUE THREAD

**Issue by Dhouly952** [flybywiresim/a32nx#5396]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-24T20:18:52+00:00",
  "ref": "master",
  "sha": "05a0bbda844850568c82ae6dab6217e509a46aa2",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

FR. Quand on joue sur clavier, le joysick de l'A32NX ne fonctionne pas sur l'axe horizontal, c'est à dire que, quand j'appuie sur les raccourcis du pavé numérique NUM4 et NUM6, rien ne se passe. Je ne sais pas si je suis un cas isolé ou s'il est général

Je vous remercie d'avance pour la résolution.

EN. When playing on the keyboard, the A32NX joysick does not work on the horizontal axis, i.e. when I press the NUM4 and NUM6 keypad shortcuts, nothing happens. I don't know if I am an isolated case or if it is general

Thank you in advance for the resolution.

### Expected behavior

FR. Je m'attendais à ce qu'en appuie sur Num4 et Num6, le joystick de l'avion réponde horizontalement en virant à gauche ou a droite.

EN. I expected that pressing Num4 and Num6 would cause the aircraft's joystick to respond horizontally by turning left or right.

### Steps to reproduce

1.
FR. Démarrer les moteurs de l'A32NX
EN. Start the A32NX engines
2.
FR. Décoller
EN. To take off
3.
FR. Essayer les raccourcis Num4 et/ou Num6, mais ils ne fonctionneront pas
EN. Try the Num4 and / or Num6 shortcuts, but they won't work

### Discord Username (optional)

dhouly95200#3930

**Comment by Benjozork** [comment]
Bonjour, avez-vous vérifié que cela fonctionne dans d'autres avions ?

**Comment by Dhouly952** [comment]
Oui, sur les autres avions cela fonctionne parfaitement, mais quand j'utilise le raccourcis Num 4 ou 6, sur l'A32NX, j'ai l'impression que quelque chose se passe, mais ça reste bloqué

**Comment by aguther** [comment]
Have a look here (Ailerons are not working when using the keyboard):
https://docs.flybywiresim.com/start/autopilot-fbw/#typical-issues-and-how-to-solve-them

Unfortunately a bug that needs to be solved in MSFS.

**Comment by Benjozork** [comment]
Malheureusement comme Andreas a commenté, on ne peut pas lier les entrées clavier pour les ailerons à notre système de commandes custom. Le problème a déjà été rapporté a Asobo.

**Comment by Dhouly952** [comment]
D'accord, merci quand meme
