### ISSUE TITLE
Altitude HUD stuck on 5000' regardless of flight level selected

### ISSUE THREAD

**Issue by Mickg56** [flybywiresim/a32nx#5399]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-25T10:35:39+00:00",
  "ref": "master",
  "sha": "5b92056f50dc6c6baa0346e882e29c58909d690c",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

Altitude HUD stuck on 5000' regardless of flight level selected

### Expected behavior

The selected altitude should be displayed in blue under heading Altitude in external HUD

### Steps to reproduce

It is present all the time

### Discord Username (optional)

mickg56

**Comment by aguther** [comment]
You provided quite few information what is really the issue. What HUD do you mean? Is it an external application or even external hardware?

I suspect that the HUD does not read the value being used by the A32NX. 

See for description of the used variables and events also here:
https://docs.flybywiresim.com/start/autopilot-fbw/

**Comment by Mickg56** [comment]
Hi aguther!
The HUD (Altitude) outside of cockpit..ie when you are outside of aircraft....the value used to show what altitude selected in cockpit...but hasnt for a few weeks now...I removed FBW A320 from my community folder so the default Asobo A320 would be used...the Altitude figure change worked as it should...so its a problem with the FBW A320.

Thanks!

**Comment by tracernz** [comment]
It’s not something we stopped supporting on purpose, but the A32NX isn’t really intended to be flown outside the flight deck.

I wish there was a way to get rid of that overlay in the outside view actually. 😂

**Comment by aguther** [comment]
Ok that one you mean. I have disabled it that’s why I didn’t know what you mean.

it needs to be tried out which value it takes but then it shouldn’t be a big thing.

**Comment by St54Kevin** [comment]
> It’s not something we stopped supporting on purpose, but the A32NX isn’t really intended to be flown outside the flight deck.
> 
> I wish there was a way to get rid of that overlay in the outside view actually. 😂

Well there is! I turned it off on day 1 :D have a look into settings

**Comment by 2hwk** [comment]
As of SU5 this is not fixed, and HUD is no longer showing the correct airliner HUD.

**Comment by donstim** [comment]
HUD is working fine here.
![Screenshot (1045)](https://user-images.githubusercontent.com/70166617/127539975-88892124-f2e3-41c9-98ad-7717fd9d1ac8.png)
![Screenshot (1046)](https://user-images.githubusercontent.com/70166617/127539996-88803042-7440-422d-8062-565716bab97b.png)
Always has for me...

**Comment by Mickg56** [comment]
Thanks for the input gentlemen...this is now redundant since SU5.
