### ISSUE TITLE
The gauges, buttons, and external models do not respond normally

### ISSUE THREAD

**Issue by SIXOSN** [flybywiresim/a32nx#5401]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2021-05-05T06:28:31+00:00",
  "ref": "experimental",
  "sha": "ff7f81fbff658ba8a69c77f6a16754ad1bffabea",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

The gauges, buttons, and external models do not respond normally
https://youtu.be/AfxGcrFJ-r0

### Expected behavior

The gauges and buttons as well as the external model can reflect normally

### Steps to reproduce

1. Fly some longer routes (such as ZBAA-RJAA)
2. This problem may occur during cruise

### Discord Username (optional)

SIXONS#8410

**Comment by aguther** [comment]
The experimental version is very old now and is not maintained anymore. Please use the development version that includes everything from experimental + other changes.

**Comment by SIXOSN** [comment]
> The experimental version is very old now and is not maintained anymore. Please use the development version that includes everything from experimental + other changes.

But I can't update it because the FBW Program says it's the latest version
![Uploading -10f3f4fbc2685071.png…]()

**Comment by hotshotp** [comment]
Yes you can't update the experimental. Download the development. Thanks.
