### ISSUE TITLE
Display Units and other Items Occasionally Freeze, can Lead to Crash to Desktop

### ISSUE THREAD

**Issue by Grooben** [flybywiresim/a32nx#5402]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-05-05T23:03:06+00:00",
  "ref": "v0.6.1",
  "sha": "4a1cccc90ab3997109e394402ab9b41a80fbf325",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

Apologies, as this happens at random I have not been able to grab any footage. I've been experiencing on some flights freezes of random Display Units on the aircraft, for example, my previous flight climbing out of Gatwick, the Captain's side ND froze, the outline of the arc turned red, and as I tried to toggle the zoom level to see if that would knock it back into life, the game crashed to desktop. I do also experience similar issues with the lower ECAM display - however, they have not led to a CTD yet.

I've had similar issues with entire models too - for example, the speed brake would get stuck in a certain position, however would still work i.e the lever would be at 47% but due to controls on my stick, I can still move it to the armed position, and the aircraft would react to that. 

### Expected behavior

Displays would not freeze, nor would controls.

### Steps to reproduce

By simply being inflight, observe and interact with elements, eventually, one _may_ freeze.

### Discord Username (optional)

Grooben# 0066

**Comment by Grooben** [comment]
This may be similar to #5401...

**Comment by sidnov** [comment]
There are optimizations coming up with the next sim update, we can wait until then and try to replicate this issue again

**Comment by Grooben** [comment]
Closing issue for now to await Sim updates.
