### ISSUE TITLE
Pop Out Panels

### ISSUE THREAD

**Issue by HankL340i** [flybywiresim/a32nx#5403]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-25T10:59:19+00:00",
  "ref": "master",
  "sha": "63df888a4695e4cf2a7f4da4668c603daf958611",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

Pop out panels show main screen instead of panel face. Using Development Build 63df888. It may not be all available pop out panels, I didn't try all but Cap't and FO PFD and MFD for sure, Did try another aircraft and pop out panels functioned as expected.

### Expected behavior

Popping out a panel should show that panel face and current state

### Steps to reproduce

Setup flight
Fly Now
Right ALT and Left CLICK on panel (say, Cap't PFD)
Panel show a low res image of the current main view rather than the panel

### References (optional)

Can provide screenshot if needed but I think this is straightforward to reproduce.

### Discord Username (optional)

Hank

**Comment by aguther** [comment]
Screenshots to underline what is the issue would be helpful.

**Comment by HankL340i** [comment]
![PopOut_Sample_1](https://user-images.githubusercontent.com/84216221/126904155-0f0c4f04-fb3a-4604-9ad5-980475b5fee0.jpg)
Andreas, here is an screenshot. Please let me know if you require any additional information and thank you for a quick reply. Regards, Hank

**Comment by NUTTTTTTTT** [comment]
Can I just confirm the issue is present with the aircraft powered too? There's nothing for the pop out to show in your screenshot, although it would usually just show a black screen.

**Comment by HankL340i** [comment]
NUTTTTTTTT, No issue with the aircraft powered. I used available external power, battery power alone is not sufficient.  
![image](https://user-images.githubusercontent.com/84216221/126905160-38101279-b674-47b0-b25b-9f6e4627226a.png)
