### ISSUE TITLE
Innapropriate engine shut down and cabin depressurization

### ISSUE THREAD

**Issue by michaelderiso** [flybywiresim/a32nx#5418]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-26T15:33:16+00:00",
  "ref": "master",
  "sha": "b8d899c4748506968946fd028b5ff54eb5404e87",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

I started out the flight completely fine, cold and dark at KATL. I started the Airbus A320neo up and followed all of the normal steps that I usually use for cold and dark to start. I pushed back, started the engines, and there was no indication of any issues with the engines or packs. About 17,000 FT after takeoff, I got a cabin depressurization warning, which was unusual because the packs were set properly and the cabin pressure was reading below 7,000 FT. It seemed normal for this altitude.

![Screenshot 2021-07-26 200526](https://user-images.githubusercontent.com/55963741/127080564-bb20a7e3-16aa-40ac-ab84-7a541f7f75d6.jpg)

At cruise, I was unable to keep climbing as a rapidly lost speed if I attempted a climb, even at TOGA and FLX thrust. I was only climbing to 35,000 FT but was only able to reach about 34,000 FT, something unusual for the FlyByWire A32NX.

Around top of descent, the plane's engines randomly failed, and the flight was very much over at this point. I don't understand what may have caused these failures so I am assuming they are a bug in the latest development version.

In terms of hardware, I am using the TCA Throttle Sidestick and Throttle Quadrant, and I have Set Fuel Valve 1 and Set Fuel Valve 2 set to the engine switches on my throttle quadrant.

### Expected behavior

A32NX should continue to climb to 35,000 FT and cabin depressurization alert should not trigger unless the cabin's altitude is too high. The engines should not shut down towards the end of the flight.

### Steps to reproduce

It is not possible to provide steps to reproduce this issue.

**Comment by Kimbyeoungjang** [comment]
Seems msfs weather issue. look at that ecam isa temp. it is abnormal on FL170

**Comment by NUTTTTTTTT** [comment]
Yep, as mentioned above. MSFS live weather is currently bugged causing issues with aircraft performance, airspeed/climb rate etc- Use a static weather preset for now if seeing issues.

You also have UnrealWeather as an option which has been spoken of quite highly since the bug started although I've yet to try it, just a heads up :slight_smile:

**Comment by tush0701** [comment]
ISA temps are crazy up there. It is another Microsoft Live Weather issues. Switch to preset weather and things would be fine.

**Comment by tracernz** [comment]
Weather/atmosphere modelling bug needs to be fixed by Microsoft/Asobo. We can’t do anything about ISA+49.
