### ISSUE TITLE
The cockpit buttons and aircraft model do not respond normally

### ISSUE THREAD

**Issue by SIXOSN** [flybywiresim/a32nx#5419]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-26T15:33:16+00:00",
  "ref": "master",
  "sha": "b8d899c4748506968946fd028b5ff54eb5404e87",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

The cockpit buttons and aircraft model do not respond normally, and this problem will appear every time I fly, and no matter what I do, I can’t get the buttons to work properly, like this https://www.youtube.com/watch?v=K0N6wXvHaI4 ，and this problem also appears in the Experimental version.

I only used REX-WEATHER FORCE FSUIPC7 BIJAN HABASHI-4 SEASON PACK these plug-ins

### Expected behavior

The cockpit buttons and airplane model can react normally to my operations, rather than being motionless

### Steps to reproduce

1.Fly a longer flight (ZBAA-RJAA) cruise altitude at FL330
2.There will be problems with buttons and models not responding during 1-2 hours of cruising

### Discord Username (optional)

SIXONS#8410

**Comment by aguther** [comment]
As far as I know this is not a FBW bug but a bug of MSFS. Never happened to me yet but seen from others.

**Comment by SIXOSN** [comment]
> As far as I know this is not a FBW bug but a bug of MSFS. Never happened to me yet but seen from others.

I don't have this problem when I use the CRJ of aerosoft

**Comment by Benjozork** [comment]
> I don't have this problem when I use the CRJ of aerosoft

That's because the issue is very rare.

Unrelated to the aircraft.

**Comment by SIXOSN** [comment]
> > I don't have this problem when I use the CRJ of aerosoft
> 
> That's because the issue is very rare.
> 
> Unrelated to the aircraft.

Then why are others FBW special when they have no problems?

**Comment by SIXOSN** [comment]
> > I don't have this problem when I use the CRJ of aerosoft
> 
> That's because the issue is very rare.
> 
> Unrelated to the aircraft.

Then why does a32nx have problems when others have no problems?

**Comment by Benjozork** [comment]
The A32NX addon cannot do anything or change anything that can cause this to happen. We have hundreds of people flying this aircraft and this issue is extremely rare to occur.

I have had this happen exactly once in 1,500 hours of playing this sim.

There is nothing we can do about this unfortunately. I suggest re-installing your simulator.
