### ISSUE TITLE
cant pull or push knobs with new cockpit interaction of SU5

### ISSUE THREAD

**Issue by wined2310** [flybywiresim/a32nx#5427]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-27T15:17:50+00:00",
  "ref": "master",
  "sha": "9d2c91076f200ee2b484e7252ee1062f83698312",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

since SU5 with the new cockpit interaction the knobs for Altimeter, Speed, Altitude and Heading can be turned to dial in the desired avlue, but cannot be pulled or pushed to toggle modes.

### Expected behavior

like other 3-way switches to be working

### Steps to reproduce

1. switch any autopilot between managed and manual mode
2. switch between manual altimeter setting and STD

**Comment by NUTTTTTTTT** [comment]
Hi, this isn't related to the FBW, this is a new MSFS setting. You can either disable it and go back to how it was under Menu > general, > accessibility > set cockpit interaction system too legacy, or you can use the new system as shown in the screenshot attached. If using the new system, right click has been replaced with scroll wheel click afaik.

![Locked interaction system](https://user-images.githubusercontent.com/87286435/127230017-0211bb65-3e93-4387-88fb-61427f697b79.png)

**Comment by wined2310** [comment]
okay, maybe I wasn't precise enough:

I ´When I push the left nutton to lock the knob and then - while keeping the left button pushed - hit the right button, nothing happens.
So I cannot get the push/pull function of the knobs working with the new mode on the latest Dev-Build.

As I read that the mod was updated fpr ne SU5 features, I wanted to report that this one is not working for me.

Can you explain how, on the new mode the altitude knob can be switched between the managed and selected mode or how to activate HDG mode, please?

Or do we have to switch to legacy mode to use the FBW mod?

**Comment by sidnov** [comment]
We recommend using the legacy for full functionality. The new interaction system may be supported in a future update, but doesn't seem to be a priority for now

**Comment by tracernz** [comment]
Legacy mode is the normal mouse interaction we’re all used to. The new x-box interaction mode is not documented and we don’t support it yet. It’s also counterproductive for PC users IMO.
