### ISSUE TITLE
push pull buttons ie baro, altitude button

### ISSUE THREAD

**Issue by FU2Max** [flybywiresim/a32nx#5428]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-27T15:17:50+00:00",
  "ref": "master",
  "sha": "9d2c91076f200ee2b484e7252ee1062f83698312",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

Unable to push or pull buttons. For example barometric or the altitude button after new update. 

### Expected behavior

To be able to push or pull

### Steps to reproduce

1. enter sim
2. try setting standard on baro

**Comment by Benjozork** [comment]
![image](https://user-images.githubusercontent.com/4503241/127238923-0579bb35-576d-4eb0-8a10-cea60805d583.png)
