### ISSUE TITLE
 [REQUEST] Integrate this mod in FS2020 Marketplace?

### ISSUE THREAD

**Issue by tomber42** [flybywiresim/a32nx#543]
**Is your feature request related to a problem? Please describe.**

No problem..only an request to keep all simple. Integrate this mod in the marketplace would solve install and update issues and would be more comfortable.

**Describe the feature you'd like to see implemented**
Integrate this mod in Microsoft MS2020 marketplace for installing and upgrade

**Comment by DoToAdventures** [comment]
There is multiple problems about this:
1) To offer content on the you need to be an approved partner, which you can only be if you apply through Microsoft  
2) I don't think they currently support freeware on there
3) Licensing issues potentially, I don't know how much they'd like modifications to their stuff on their official store

**Comment by tomber42** [comment]
maybe ask microsoft..as i heard they will support freeware too in the marketplace.

**Comment by Benjozork** [comment]
How exactly would this be more convenient ?

**Comment by lousybyte** [comment]
Even if they will accept freeware, you would still need to be an approved partner/developer (and pay the required fees), and I assume they would have some quality standards to meet that an ongoing early alpha project like this will be far from, their store is nothing like Steam's workshop wild west.

**Comment by JasonO99** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> No problem..only an request to keep all simple. Integrate this mod in the marketplace would solve install and update issues and would be more comfortable.
> 
> **Describe the feature you'd like to see implemented**
> Integrate this mod in Microsoft MS2020 marketplace for installing and upgrade

I don't think the installation could be made more simple than what it is, without having some software to perhaps install it for you but then that's unnecessary. I think anything else just means more work for the FlyByWire team when really downloading and drag and dropping is straight forward enough as it is.

**Comment by fourdragons** [comment]
> I don't think the installation could be made more simple than what it is, without having some software to perhaps install it for you but then that's unnecessary. I think anything else just means more work for the FlyByWire team when really downloading and drag and dropping is straight forward enough as it is.

Agreed. Not to be unkind, but just to be realistic, people that can't copy-n-paste a directory shouldn't be using this alpha/beta software, anyway.

**Comment by aguther** [comment]
Stable version now available via marketplace.
