### ISSUE TITLE
MCDU Does'nt recognize any airports

### ISSUE THREAD

**Issue by OneTwo509** [flybywiresim/a32nx#5430]
### Aircraft Version

Development

### Build info

```json
"built": "2021-05-05T06:28:31+00:00",
  "ref": "experimental",
  "sha": "ff7f81fbff658ba8a69c77f6a16754ad1bffabea",
  "actor": "aguther",
  "event_name": "manual"
```

### Describe the bug

Since SU5 - Can no longer input airports into MCDU - also tried to import from Simbrief - "Not in database"  - At least a couple others reporting same issue in support chat - no workaround known at this time.

### Expected behavior

Either manually enter or import from Simbrief a flight plan - doesn't recognize any airports and says Not In Database

### Steps to reproduce

Start a new Flight
Pick Starting Airport without destination
Input starting/destination airports in MCDU
Import from Simbrief 
Error Not In Database 

### Additional info (optional)

 Support chat tried to help but no known solution at this time

### Discord Username (optional)

OneTwo509

**Comment by Kimbyeoungjang** [comment]
You use experimental version that update 2 month ago.

Please try with latest development version on installer

**Comment by OneTwo509** [comment]
Sorry - i forgot to mention that when it didn't work on latest development, I clean installed exp version to try it

**Comment by OneTwo509** [comment]
What's strange is - before I even did anything, I updated FBW knowing about the update.  I was in latest dev version and it didn't work.  Just did 3rd clean install, and it is working now.  
Cheers
