### ISSUE TITLE
Square Blocks Appearing With Certain External Lights On

### ISSUE THREAD

**Issue by speedbird5** [flybywiresim/a32nx#5432]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-27T15:17:50+00:00",
  "ref": "master",
  "sha": "9d2c91076f200ee2b484e7252ee1062f83698312",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

See attached image below,
On the ground, square blocks showing when landing lights or runway turn-off lights are on.
The blocks go away when those lights are turned off.
Other external lights are OK.
RTX 3070 GPU with latest driver 471.41

### Expected behavior

Square blocks should not appear.

### Steps to reproduce

On ground in external view, turn on runway turn-off lights and/or landing lights then rotate external view until the blocks appear.

The blocks go away when those lights are turned off.

Other external lights are OK.

![Capture](https://user-images.githubusercontent.com/20328510/127306461-411b8eaf-5ac4-41b1-b9d6-9fc4fa8ea567.PNG)

**Comment by sidnov** [comment]
This is an issue with the simulator's graphic engine. Please open up a report on MSFS Forums if it doesn't exist there already, or try contacting MSFS support on Zendesk

**Comment by mshamash** [comment]
I've been having a similar issue @sidnov, just not sure if it is the same as the original post above or not, and whether I should open a new GitHub issue for this... I've attached a video clip for reference. This is using the GeForce Game Ready Driver 471.41 on an RTX 2060 Super, Ryzen 9 5900X CPU, and latest MSFS ad A32NX versions (dev branch of A32NX). Video recorded at KDTW airport on August 14, 2021 in the evening.

https://youtu.be/9UG1YaFZFJI

**Comment by Squall-Leonhart** [comment]
A potential workaround is to disable Tiled caching with Profile inspector, instructions are available @ https://www.reddit.com/r/nvidia/comments/k0d45i/nvidia_profile_inspector_where_to_find_tiled_cache/

**Comment by PandyAir** [comment]
I am getting similar issue but I do not think its related to the A32NX, as I get the same issue with the stock A320neo. I suspect its a problem with the sim which I only noticed after the WU5.

**Comment by 2hwk** [comment]
Seemingly fixed by WU6, if this still occurs reopen the issue. May be related to nvidia driver issues.
