### ISSUE TITLE
Detent option not available

### ISSUE THREAD

**Issue by CapJambo** [flybywiresim/a32nx#5433]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2021-05-05T23:03:06+00:00",
  "ref": "v0.6.1",
  "sha": "4a1cccc90ab3997109e394402ab9b41a80fbf325",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

It looks like I have A32NX updated. But in reality, the flypad, is not. I can't set detents. That option is not available! I can't set detents for my TCA throttle quadrant.

### Expected behavior

I expected to, after update, I could set detents in the options menu.

### Steps to reproduce

<img width="1280" alt="Microsoft Flight Simulator Screenshot 2021 07 28 - 13 04 46 94" src="https://user-images.githubusercontent.com/88090584/127319305-ef60394f-dc83-4136-b9b6-89b31c115eb3.png">

### References (optional)

This happens regardless which version I use. Experimental, development or stable version.

### Additional info (optional)

I think I used to update fine until A320NX detached from original A320. I reckon the problem began there.

**Comment by tshomas** [comment]
You are currently using stable, at the moment the only version that works and also the only version with the calibration too is development! Please switch using the installer.

**Comment by CapJambo** [comment]
Cheers tshomas. I will try when the 40gigs update finishes.

**Comment by CapJambo** [comment]
So after update this is what I get from the flyplad

<img width="1280" alt="Microsoft Flight Simulator Screenshot 2021 07 28 - 18 53 53 01" src="https://user-images.githubusercontent.com/88090584/127372286-fd65e2dc-f832-4115-a1a4-6cce0ce8482d.png">

I guess we will have to wait for an update. Or is it only me?
Cheers

**Comment by marcsoler** [comment]
@CapJambo have you tried to clean install the a32nx?

https://docs.flybywiresim.com/start/reported-issues/
https://docs.flybywiresim.com/start/installation/#clean-install-steps

**Comment by CapJambo** [comment]
The problem was that I had 2 copies of a32nx. One in the community and the other in the official folder.

Cheers
