### ISSUE TITLE
Climb Problems

### ISSUE THREAD

**Issue by TominYEEET** [flybywiresim/a32nx#5434]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-27T15:17:50+00:00",
  "ref": "master",
  "sha": "9d2c91076f200ee2b484e7252ee1062f83698312",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

While the temperature SAT or TAT (i don't know which one is responsible for that) is high the aircraft seems to have problems climbing because it seems its thinking its flying at a lower speed than it actually is causing it to level off and try reaching a higher speed which is not possible. I just think this can't be right.

### Expected behavior

Actually i don't quite know because i don't understand too much in terms of the relationship between temperatures and airspeed.

### Steps to reproduce

Just do a normal flight and hope you're flying through warmer airspace's i guess

### References (optional)

![Screenshot_1](https://user-images.githubusercontent.com/71587956/127324532-9f8e7efd-21c7-4b37-b19b-8308ecd1085a.png)
Screenshot 1: Both temperatures TAT and SAT well even ISA jump in to a positive value, the airspeed jumps to a lower state

![Screenshot_2](https://user-images.githubusercontent.com/71587956/127324736-cd8fcfb8-e875-4c7e-b1b0-2b8b6a0eb42c.png)
Screenshot 2: When both TAT and SAT jump to a negative value and the ISA jumping to a still positive but a lower value, the airspeed jumps to a higher value (normal/expected value)

![Screenshot_3](https://user-images.githubusercontent.com/71587956/127324997-8bd182ec-a03b-47f6-8117-c8ff67a475ca.png)
Screenshot 3: Basically the same as on Screenshot 1 but happened a while after.

### Additional info (optional)

I just think there is something wrong. I cant imagine that aircraft cannot climb while they are in warmer airspace's. It just seems unrealistic to me. Also i don't know if this is a problem from you or Microsoft/Asobo.

### Discord Username (optional)

Timon#6690

**Comment by aguther** [comment]
Unfortunately this is a problem of live weather of MSFS and not an issue of A32NX. A workaround for those cases is to use a weather preset.

**Comment by TominYEEET** [comment]
> 
> 
> Unfortunately this is a problem of live weather of MSFS and not an issue of A32NX. A workaround for those cases is to use a weather preset.

**Comment by DerHofnarr** [comment]
i think i have the same here. TAT shows +43°C (IN FL 320!!) and SAT +18 AND the MCDU´s PROG page shows OPT FL208 (jumping arround from FL200 until FL400). Idy maybe is  real beahvior? 

Cheers ~ DerHofnarr :)

**Comment by aguther** [comment]
Yes, this is anyway not the first „bug“ being opened for that. It‘s an MSFS issue and *NOT* A32NX.
