### ISSUE TITLE
Engine bug after MSFS2020 update(?)

### ISSUE THREAD

**Issue by DerHofnarr** [flybywiresim/a32nx#5435]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-27T15:17:50+00:00",
  "ref": "master",
  "sha": "9d2c91076f200ee2b484e7252ee1062f83698312",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

So after todays update of MSFS2020 (28. july 2021) whenever i set my engine 1 to "ON" on my thrustmaster airbus quadrant ( https://www.thrustmaster.com/de_DE/produkte/tca-quadrant-airbus-edition ) nothing happens.

Than i reassigned the buttons but still nothing. When i let the leaver switched off i can start eng. 1 with "ctrl + E" but when i THAN switch the leaver back ON the leaver inside the aircraft switches off. anyone with a similar problem and/or solution. thank you verry much :)

DerHofnarr

### Expected behavior

leaver on quadrant is on the leaver inside the aircraft should be on

### Steps to reproduce

switch on aircraft engine leaver
switch on quadrant leaver

### Discord Username (optional)

DerHofnarr#4532

**Comment by kiokio0987** [comment]
The solution to starting the engine seems to be answered here. (#5426 )Have you tried this?

**Comment by DerHofnarr** [comment]
> The solution to starting the engine seems to be answered here. (#5426 )Have you tried this?

Oi. Thank you really much mate. I just delated the fuel valve buttons and now its working lol 😅. I guess thread is solved and closed 👍🏼

Cheers ~ Hofnarr
