### ISSUE TITLE
After SU5 Climb Performance @ MTOW

### ISSUE THREAD

**Issue by DanP77** [flybywiresim/a32nx#5439]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-27T15:17:50+00:00",
  "ref": "master",
  "sha": "9d2c91076f200ee2b484e7252ee1062f83698312",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

In Managed Climb at about FL220 do not want to continue to climb (Cruise fixed at FL360)

### Expected behavior

Climb ad by manual at about 290 Ktn than climb at fixed MN

### Steps to reproduce

Set Aircraft at MTOW
Observe performance in Climb and Managed
Climb till FL360

### Additional info (optional)

I will check in further flight

**Comment by Benjozork** [comment]
MSFS Live weather issue. Please try with a fixed preset.

**Comment by Benjozork** [comment]
Btw, this is indicated in our Reported Issues page:

https://docs.flybywiresim.com/start/reported-issues/#msfs-live-weather

**Comment by DanP77** [comment]
> Btw, this is indicated in our Reported Issues page:
> 
> https://docs.flybywiresim.com/start/reported-issues/#msfs-live-weather


Thank you, may be that's the prblem...
