### ISSUE TITLE
Pixelated screens!

### ISSUE THREAD

**Issue by TLSY2** [flybywiresim/a32nx#5441]
### Aircraft Version

Development

### Description

I dont know if this fits under bug too!

The screens are way too pixelated, i cant even read them from a higher fov! How do i remove the pixelated stuff?

**Comment by ErickSharp** [comment]
related to #5424

**Comment by TLSY2** [comment]
> related to #5424

Is everything on this feature request related :))) All my new posts are related to something!

**Comment by MisterChocker** [comment]
Duplicate of #5424
