### ISSUE TITLE
AA Causing Flickering on the buttons, etc.

### ISSUE THREAD

**Issue by wizardkitty** [flybywiresim/a32nx#5442]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-05-05T23:03:06+00:00",
  "ref": "v0.6.1",
  "sha": "4a1cccc90ab3997109e394402ab9b41a80fbf325",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

AA Causing Flickering of buttons, text, etc.

TAA is currently the one I know of. Ill check the others soon.

### Expected behavior

No flicking

### Steps to reproduce

1. Settings preset to high-end
2. Look around the cockpit but don't zoom

### Additional info (optional)

This only started occurring after Sim Update 5.

It could be the sims fault but I don't see the issue in the stock a320.

### Discord Username (optional)

wizzerdkitty#7383

**Comment by wizardkitty** [comment]
Confirmed its TAA only.

**Comment by wizardkitty** [comment]
I realize this is part of one reported issue: Decal fickering.

This is due to TAA. Zooming in will stop the effect but zooming out will make it reappear. It could be somthing changed with TAA. But Setting AA to anything else stops the issue.

**Comment by ribase** [comment]
same for me as well, thx for posting this issue

**Comment by LordNecton** [comment]
Its fine on the latest Dev build using TAA

**Comment by 2hwk** [comment]
Fixed by https://github.com/flybywiresim/a32nx/pull/5460
