### ISSUE TITLE
DB is missing LOWI airport, working on other planes

### ISSUE THREAD

**Issue by chiponn** [flybywiresim/a32nx#5443]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-05-05T23:03:06+00:00",
  "ref": "v0.6.1",
  "sha": "4a1cccc90ab3997109e394402ab9b41a80fbf325",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

When trying to add LOWI into the INIT page I receive a "Not In Database" error. 
Verified that some other airports work. 

### Expected behavior

MCDU recognizes the LOWI ICAO

### Steps to reproduce

1. Start in a random airport
2. In the INIT page, try to set your flight from/to LOWI
3. Error "Not In Database" will be received. 

* Doesn't reproduce on default NEO

**Comment by NUTTTTTTTT** [comment]
You need to be updated to the latest development version. If you're currently using the marketplace version, remove via content manager prior to installing the development version via the installer. SU5 bug fixed on dev. 

![image](https://user-images.githubusercontent.com/87286435/127403430-5efd9f99-67ed-4e86-9a16-edfd8ff8e73b.png)

**Comment by tracernz** [comment]
This is fixed in dev (master).
