### ISSUE TITLE
Strobe and Landing Lights switches have inverted assignment to the simulator controls after SU5

### ISSUE THREAD

**Issue by SierraBravo1** [flybywiresim/a32nx#5444]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-27T15:17:50+00:00",
  "ref": "master",
  "sha": "9d2c91076f200ee2b484e7252ee1062f83698312",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

The strobe and landing Lights switches have an inverted assignment to the simulator controls after SU5.
Simulator Control "Landing Lights On" switches the airbus' landing lights off.
Simulator Control "Landing Lights Off" switches the airbus' landing lights on.
Simulator Control "Strobes On" switches the strobes off.
Simulator Control "Strobes Off" switches the strobes auto.

### Expected behavior

Same as before SU5:
Simulator Control "Landing Lights On" switches the landing lights on and Nose light to T.O
Simulator Control "Landing Lights Off" switches the landing lights off or better retract and Nose light off.
Simulator Control "Strobes On" switches the strobes on or auto.
Simulator Control "Strobes Off" switches the strobes off.

### Steps to reproduce

1. Assign the simulator controls "Landing Lights On/Off" and "Strobes On/Off" to hardware buttons or switches.
2. Switch the buttons.
3. Validate the state of the switches in the exterior light section of the overhead panel.

**Comment by 2hwk** [comment]
This is also a bug with the default aircraft

**Comment by ribase** [comment]
> This is also a bug with the default aircraft

is there any link to a thread where this issues is discussed?

**Comment by ErickSharp** [comment]
> > This is also a bug with the default aircraft
> 
> is there any link to a thread where this issues is discussed?

This issue is not talked about frequently, but nevertheless has still been brought up here and there: 

https://forums.flightsimulator.com/t/am-i-the-only-one-still-experiencing-certain-light-switches-not-working-on-honeycomb-alpha/406606

**Comment by 10Exahertz** [comment]
For me the landing lights straight up dont work if I try toggling via mouse.
You guys get the same issue?

**Comment by Kebushay** [comment]
Same here, can't toggle via mouse

**Comment by tracernz** [comment]
Try mouse wheel. I haven't tried clicking, but wheel still works.

**Comment by SierraBravo1** [comment]
The issue which is discussed here is not about toggling the switches in the cockpit with the mouse.
There is an issue - even with the vanilla A320 - if you assign the landing lights and strobe to external hardware buttons (for example Honeycomb Bravo) by the simulator control configuration in the MSFS menu after SU5.

**Comment by lukitas1978** [comment]
bueina tarde, alguien logro solucionar el problema de los botones de las luces de nav de aterrizaje, 
y TAxi que estan invertidas. gracias x la ayuda.

**Comment by 2hwk** [comment]
Will be tracking this in https://github.com/flybywiresim/a32nx/issues/5932, closing.
