### ISSUE TITLE
A320 FBW is causing crash after msfs update

### ISSUE THREAD

**Issue by xjanat** [flybywiresim/a32nx#5445]
### Aircraft Version

Stable

### Build info

```json
don´t know - just fix it
```

### Describe the bug

A320 is causing MSFS crash to desktop after latest msfs update

### Expected behavior

Plane is causing crash during LKPR loading.

### Steps to reproduce

when I tried to use this airplane at LKPR

### Discord Username (optional)

xjanakt

**Comment by wpine215** [comment]
Stable has not yet been updated for SU5 compatibility, use development version. Next time follow issue instructions and provide proper build info.

**Comment by xjanat** [comment]
thank you but development version is totally unstable, I tried to use it a few weeks ago . Throttle position 0 means by this version revers , it´s very hard to fly with  it.  Autothrothle is not working , flight level is unstable...
 I have feeling like airplane after serious fault. Development version is not ready for use...  FBW stable version has also so many bugs ( IRS has stop working , you need to reset it but during approach...not nice , steering has stop to work before landing ..... Stable version was +- usable also with bugs but development version is much worst.  Sorry for that but if is stable version not working, I can´t use this plane any more because it´s flying bug.

**Comment by Benjozork** [comment]
Um, I'm flying the dev version with the custom FMS every day and I have none of the issues you're describing.

I suggest you go to our support channel on Discord so we can figure out what's going wrong.

**Comment by xjanat** [comment]
Beleive me, I have so many issues.....  could you please send me discord link?  I dont´t know if it is normal but when I have throtle on my joystick in 0 position, it can not be translated as revers, revers is key F2 . I tried to use development version  on the route UUEE-LKKV, autopilot was disconnected houndred times , autothrotle was disconnect too...it was adventure flight :D

**Comment by Benjozork** [comment]
https://discord.gg/flybywire

AP disconnect is usually caused by A FLOOR protection engaged due to misconfigured throttle axis. See the #support chat and we can help you out !

**Comment by xjanat** [comment]
strange...can´t accept invitation :/

**Comment by Benjozork** [comment]
You might need to verify your phone number.

**Comment by xjanat** [comment]
![image](https://user-images.githubusercontent.com/88117274/127411576-4d2be0d0-46c5-4817-bc50-ddeb722c89aa.png)

**Comment by xjanat** [comment]
there is no option how to verify phone number...  in any case, development version is in compare with stable version very unstable. This is may be for profesional airbus pilots with own home cockpit and real airbus throtle device, so if is stable version not usable any more..whole aircraft is unusable too.

**Comment by Benjozork** [comment]
I'm sorry man but I have the cheapest HOTAS and no home cockpit and I'm the farthest thing from an Airbus pilot. And everything works for me.

I recommend you make sure your throttle is calibrated using one of the many tutorials on YouTube or our own on our channel.

**Comment by xjanat** [comment]
Im sorry but for me it does not work like stable version, anyway thank you for your help and quick reply.  I´m using many airplanes, all are working fine except FBW . Especially down position of throtle on joystick must be idling , not revers. And another point... airplane must be stable in sim rate 4x - stable version can handle it without any problems, development not. There is a lot of things..  Good night :)

**Comment by Benjozork** [comment]
The simrate issue is a limitation of the simulator with our custom autopilot. We cannot do anything about it.

For the throttle problem - again, your throttle is misconfigured. Please follow a tutorial online.

**Comment by 2hwk** [comment]
Calibrate your throttles here: 
![InkedFlightSimulator_D4XdhgkaQA_LI](https://user-images.githubusercontent.com/15316958/127415223-a69505d9-44df-42cb-b271-4dc0cd6ad667.jpg)
https://www.youtube.com/watch?v=8yZuv2L4jPA

**Comment by lukecologne** [comment]
The sim rate stability is not the sim's fault directly, it depends on the time interval for each frame, so it depends on framerate.
If you want to read about it: <https://en.wikipedia.org/wiki/Nyquist%E2%80%93Shannon_sampling_theorem>

**Comment by xjanat** [comment]
Thank you, it´s partly fixed but I do not need revers on my joystick - down position must be iddle , revers is for me always key F2.  Is it possible to set like this? also steering is not working automatically as by previous stable version... (I do not have pedals, trim is automatic) , where can I set up steering? 

TJ

**Comment by xjanat** [comment]
It looks better now, it works. Anyway, it´s quite bad that revers can not be fully removed from settings. I´m using usually key F2 as revers, not joystick but plane is now flyable.  Thank you for your help :)

**Comment by NUTTTTTTTT** [comment]
> It looks better now, it works. Anyway, it´s quite bad that revers can not be fully removed from settings. I´m using usually key F2 as revers, not joystick but plane is now flyable. Thank you for your help :)

It can - EFB > throttle calibration > disable "reverser on axis". Save and continue. 👍
Make sure you've got a button under MSFS controls set to activate reverse thrust if you've done this.

**Comment by aguther** [comment]
Yeah and if you change that button ensure your calibration is still as you want it.

**Comment by LentuloBatiato** [comment]
> The sim rate stability is not the sim's fault directly, it depends on the time interval for each frame, so it depends on framerate.
> If you want to read about it: https://en.wikipedia.org/wiki/Nyquist%E2%80%93Shannon_sampling_theorem

No one has said here that it is a sim's fault. What I have read is that it is a limitation of the simulator with their custom autopilot.

**Comment by Benjozork** [comment]
Let's keep this issue on topic.

**Comment by xjanat** [comment]
Thank you, aircraft is now OK for me :)

**Comment by xjanat** [comment]
as I see sim is crashing with new FBW dev version now too :/ that´s crazy... this msfs update caused more problems than solved :/

**Comment by aguther** [comment]
Please comment reports on CTDs on this thread:
https://github.com/flybywiresim/a32nx/issues/5446

**Comment by OhItsLaz** [comment]
> thank you but development version is totally unstable, I tried to use it a few weeks ago . Throttle position 0 means by this version revers , it´s very hard to fly with it. Autothrothle is not working , flight level is unstable...
> I have feeling like airplane after serious fault. Development version is not ready for use... FBW stable version has also so many bugs ( IRS has stop working , you need to reset it but during approach...not nice , steering has stop to work before landing ..... Stable version was +- usable also with bugs but development version is much worst. Sorry for that but if is stable version not working, I can´t use this plane any more because it´s flying bug.

The dev version does NOT work. I read the directions and am not joining a discord to help someone else solve their product's issue if everyone is going to be so rude.   MSFS fresh install after SU5, NOTHING in community folder, just pick FBW A320N, and load into JFK.. dont pick anything else.. CRASH..   If it does load, the lights all all flickering.  So, basically unusable.  Tried, DEV, Expertimental, Stable, and loading it via MSFS marketplace.   Is that enough info?  Ok thanks bye.  All my other planes work fine.

**Comment by aguther** [comment]
@OhItsLaz Well we are not a company and all of the people at FBW are doing the planes and the maintenance of them in their free time as a hobby.

The instability in usage of the plane is not coming from our plane although it might look like it. It’s coming from the platform. Beside that the plane runs quite well on my end without any CTD. 

Comments like yours are not constructive and are not motivating for developers to work in their free time.

Always remember that no one forces you to use the A32NX, but we hope to provide a good plane that can be used by many. Instabilities of the platform it runs on are out of our control.
