### ISSUE TITLE
crash avec la version stable 0.6.1

### ISSUE THREAD

**Issue by snypa972** [flybywiresim/a32nx#5447]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-05-05T23:03:06+00:00",
  "ref": "v0.6.1",
  "sha": "4a1cccc90ab3997109e394402ab9b41a80fbf325",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

j'ai un crash return desktop à chaque fois que je lance mon vol avec l'A320 FBW. je n'ai pas ce crash avec l'A320 de ASOBO.
et j'ai ce crash uniquement avec la version stable. dès que je passe sur la version dev ou expériment le vol se lance sans problème.

### Expected behavior

que la version stable soit effectivement stable

### Steps to reproduce

Dès que je choisis la version stable, quand le lance le vol. à l'écran de chargement du vol, le jeu reviens violemment sur le bureau windows.

### Additional info (optional)

oui cela fonctionnait avant. et j'ai commencé à avoir les bugs après la grosse et récente mise à jour de MSFS2020 (la mise à jour qui améliore les fps)

**Comment by delta5150** [comment]
Same

**Comment by Benjozork** [comment]
Bonjour, comme indiqué sur les annonces discord et sur les posts twitter/facebook la version stable n'est pas supportée avec la sim update 5

**Comment by snypa972** [comment]
Ah Ok, Je n’avais pas l’infos, j’attendrais alors, merci beaucoup

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : Benjamin ***@***.***>
Envoyé le :mercredi 28 juillet 2021 23:03
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [flybywiresim/a32nx] crash avec la version stable 0.6.1 (#5447)


Bonjour, comme indiqué sur les annonces discord et sur les posts twitter/facebook la version stable n'est pas supportée avec la sim update 5
