### ISSUE TITLE
Keep current chart open when changing flypad tab

### ISSUE THREAD

**Issue by ToLaTE4u** [flybywiresim/a32nx#5452]
### Aircraft Version

Development

### Description

Hey guys!
It would be cool to keep the latest  navigraph chart open when selecting another tab in flypad. At the current situation when selecting thr e.g. ground tab and then the charts tab again, you completely have to type in the airport and search your chart again.

Maybe its a misusing on my side, but having that would be great and would enhance the atmosphere!

Greetings!

**Comment by antonyisoardi** [comment]
This one is to be addressed with state management updates after we redo routing
