### ISSUE TITLE
Problem with MCDU/SimBrief

### ISSUE THREAD

**Issue by KejuBartin** [flybywiresim/a32nx#5461]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-29T11:41:32+00:00",
  "ref": "master",
  "sha": "6bafd4940941cc711e337e8a3275fcebb68a1610",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

I already have a SimBrief Pilot ID entered into my MCDU (blue color) but now i have a diffrent Pilot ID which i wanted to enter into the MCDU (overwrite the old one). That is not possible. I type the new ID into the scratchpad and click LSK2L to enter it into the correct line. But the new ID doesn't show up in that line. It just stays with the old one. I even tried to delete the A32NX completely out of the community folder and to install the development version again so that the old ID maybe gets deleted with the mod. That didn't work either. The ID just stayd there untouched.

### Expected behavior

I expectet that the new ID shows up in the correct line instead of the old ID.

### Steps to reproduce

1. Have a plane with a SimBrief ID already in it
2. Restart the Simulator
3. Try to enter a new Simbrief ID

### Additional info (optional)

Yesterday I entered the SimBrief Pilot ID from a streamer on Twitch to fly his route. But today I wanted to fly my own route so I wanted to enter my SimBrief ID. Then I had this problem. I freshly updated the A32NX today. So yesterday I had an older version, also with an entered SimBrief ID. And as i can remember it, it is not the version before the version i mentioned earlier, it is the version before that. So I did two updates after it just worked fine.

### Discord Username (optional)

Mr. All#9299

**Comment by alecdurberville** [comment]
Same problem - simbrief ID populated with something unknown and won't allow overwrite.  Also, 'INIT REQUEST' key only retrieves the flight number and displays 'NOT IN DATABASE', will not populate FROM/TO or F-PLAN legs.

**Comment by NUTTTTTTTT** [comment]
> Same problem - simbrief ID populated with something unknown and won't allow overwrite. Also, 'INIT REQUEST' key only retrieves the flight number and displays 'NOT IN DATABASE', will not populate FROM/TO or F-PLAN legs.

Make sure you're on the latest development version. If showing installed on the installer, check there is no marketplace version in content manager before reinstalling dev.

**Comment by Onkelpuh** [comment]
> Gleiches Problem - Simbrief-ID mit etwas Unbekanntem gefüllt und lässt kein Überschreiben zu. Außerdem ruft der Schlüssel "INIT REQUEST" nur die Flugnummer ab und zeigt "NOT IN DATABASE" an, füllt keine FROM/ TO- oder F-PLAN-Beine.

have the same problem despite updated current FBW dev version

**Comment by tracernz** [comment]
We have no chance of debugging this without knowing your exact route, and which navdata you are using in your simulator (navigraph beta, or default).

**Comment by glad2021** [comment]
After the SU5, I also have problems entering data into the MCDU. On the init page, I tried to enter EDDF/EDDG and EDDF/EDDM into the FROM/TO field. For both inputs, I got the "not in database error". I think right now, it wont take any route as input

**Comment by tracernz** [comment]
> 
> 
> After the SU5, I also have problems entering data into the MCDU. On the init page, I tried to enter EDDF/EDDG and EDDF/EDDM into the FROM/TO field. For both inputs, I got the "not in database error". I think right now, it wont take any route as input

That happens if you're not running the latest dev version of A32NX.

**Comment by Onkelpuh** [comment]
> > Nach der SU5 habe ich auch Probleme, Daten in die MCDU einzugeben. Auf der init-Seite habe ich versucht, EDDF / EDDG und EDDF / EDDM in das Feld FROM / TO einzugeben. Für beide Eingaben habe ich den Fehler "nicht in der Datenbank" erhalten. Ich denke, im Moment wird es keine Route als Eingabe nehmen
> 
> Das passiert, wenn Sie nicht die neueste Entwicklungsversion von A32NX ausführen.

this also happens with the latest version of the FBW

**Comment by 2hwk** [comment]
Closed as MCDU no longer has a seperate simbrief user from the EFB, it is all driven by the EFB setting now.
