### ISSUE TITLE
Anyone else with unrealistic temperatures on Flight Level?

### ISSUE THREAD

**Issue by Daboj1337** [flybywiresim/a32nx#5462]
### Aircraft Version

Development

### Build info

```json
"built": "2021-07-29T11:41:32+00:00",
  "ref": "master",
  "sha": "6bafd4940941cc711e337e8a3275fcebb68a1610",
  "actor": "davidwalschots",
  "event_name": "manual"
```

### Describe the bug

FL360 over Germany. High temperatures, high fuel flow and wrong airpeeds

<img width="370" alt="Unbenannt" src="https://user-images.githubusercontent.com/76589309/127523692-54e6e365-c423-4d30-983d-0526dd679f81.PNG">

### Expected behavior

Normal temperatures. 

### Steps to reproduce

Climb to Cruise Level

**Comment by NUTTTTTTTT** [comment]
Hi, this is MSFS live weather, it's been crazy for days, use a weather preset. Please see known issues: https://docs.flybywiresim.com/start/reported-issues/#msfs-live-weather
