### ISSUE TITLE
Bug at speed.

### ISSUE THREAD

**Issue by luisreib** [flybywiresim/a32nx#5464]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-29T11:41:32+00:00",
  "ref": "master",
  "sha": "6bafd4940941cc711e337e8a3275fcebb68a1610",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

Speed goes down from 270 to 180 or 170 flying at high alttitudes (FL360, 370, 380 ,.....)
Later speed goes well again and a some miles later goes down again.
I can see that when speed goes down, TAT,SAT,ISA temperatures change from negative data (-50,-51....) to positive datas (+13,+14...) and is not step by step, this changes are inmediatly. As soon as temperatures return to negative then speed goes well.

### Expected behavior

Expecting repair bug

### Steps to reproduce

1. speed goes down
2. Temperatures goes down too.
3.

**Comment by Benjozork** [comment]
This is an MSFS live weather issue.
