### ISSUE TITLE
the first engine does not turn on on the TCA Quadrant Airbus edition 

### ISSUE THREAD

**Issue by NitroMaxx72** [flybywiresim/a32nx#5467]
### Aircraft Version

Development

### Build info

```json
"built": "2021-07-29T17:14:16+00:00",
  "ref": "master",
  "sha": "aa61b135820ad527ce2511786fee5ebd4bcd3bfb",
  "actor": "MisterChocker",
  "event_name": "manual"
}
```

### Describe the bug

After the update, the pre-switch of the first engine stopped working

### Expected behavior

Must repeat switching

### Steps to reproduce

Must repeat switching

### Discord Username (optional)

Nitro #5130

**Comment by Benjozork** [comment]
https://docs.flybywiresim.com/start/reported-issues/#su5-issues
