### ISSUE TITLE
Lbs Fuel Flow Broken

### ISSUE THREAD

**Issue by ShadowFrost3** [flybywiresim/a32nx#5468]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-29T17:14:16+00:00",
  "ref": "master",
  "sha": "aa61b135820ad527ce2511786fee5ebd4bcd3bfb",
  "actor": "MisterChocker",
  "event_name": "manual"
}
```

### Describe the bug

No indicated fuel flow on upper ECAM in LBS unit

### Expected behavior

There should be fuel flown on upper ECAM in LBS unit

### Steps to reproduce

Cold and dark A320 with LBS weight unit, watch as there is no indicated fuel flow on ECAM with engines running. 

### References (optional)

![image](https://user-images.githubusercontent.com/87394534/127576054-a7bc8de5-2e9b-4da4-bdc6-64f3d5b6089a.png)

**Comment by tracernz** [comment]
Duplicate https://github.com/flybywiresim/a32nx/issues/5316

**Comment by ShadowFrost3** [comment]
Whoops, couldn't find via search on fuel flow so my bad.
