### ISSUE TITLE
FCU Managed/Selected switch functionality no more working/proposed.

### ISSUE THREAD

**Issue by Biniou671** [flybywiresim/a32nx#5471]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-29T17:14:16+00:00",
  "ref": "master",
  "sha": "aa61b135820ad527ce2511786fee5ebd4bcd3bfb",
  "actor": "MisterChocker",
  "event_name": "manual"
}
```

### Describe the bug

Since MSFS last update, the functionality to switch from managed/selected speed, managed/selected heading and managed/selected flight level, on the FCU, doesn't exist anymore.
There is no option proposal appearing when putting the mouse cursor on the buttons.

### Expected behavior

For each button speed, heading and flight level, to have the option proposal to switch from managed to selected functionality.

### Steps to reproduce

1. During pre-flight preparation, getting ATIS info.
2. Request for IFR clearance
3. Update transition flight level as requested by ATC.
4. Update runway heading for take-off
5. Update climb speed (240knt)
6. After take-off no possibility to switch from selected speed/heading/flight level to managed/speed/heading/flight level.

**Comment by Benjozork** [comment]
https://docs.flybywiresim.com/start/reported-issues/#fcu-heading-knob
