### ISSUE TITLE
Clicking STA causes CTD

### ISSUE THREAD

**Issue by Machete3000** [flybywiresim/a32nx#5481]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-30T08:31:00+00:00",
  "ref": "master",
  "sha": "35319ba865066bd2b1d8603cfb43ec9dbc340353",
  "actor": "beheh",
  "event_name": "manual"
}
```

### Describe the bug

Clicking STA causes CTD

### Expected behavior

no CTD

### Steps to reproduce

Click STA to bring up status page. Tested twice on runway before takeoff. CTD consistently.

**Comment by kilocharlie1** [comment]
I don't have that issue

**Comment by Machete3000** [comment]
No longer an issue.
