### ISSUE TITLE
Cannot pull-back throttle from TOGA/FLEX to CL

### ISSUE THREAD

**Issue by Skkkitzo** [flybywiresim/a32nx#5482]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-29T17:14:16+00:00",
  "ref": "master",
  "sha": "aa61b135820ad527ce2511786fee5ebd4bcd3bfb",
  "actor": "MisterChocker",
  "event_name": "manual"
}
```

### Describe the bug

After taking off (in this case using TOGA), the PFD will display a flashing "LVR CLB" indicating that I need to pull back the throttle to the CL indent. However using my XBOX controller I am unable to set the throttles to the CL position, it is either slightly higher or lower. 

The sensitivity settings for increase and decrease throttle on the controller are too wild, but it seems to only be a problem on the A32NX. 

![Throttle just slightly below CL indent](https://user-images.githubusercontent.com/20148107/127686887-4f070225-9638-4005-8884-7b2d9301426e.png)

![Throttle just slightly above CL indent](https://user-images.githubusercontent.com/20148107/127686955-3233f072-7d99-49ef-b0cd-508843885b80.png)

### Expected behavior

I expect to pull back the throttle to the CL indent easily, as is the case in the stable release last I checked.

### Steps to reproduce

1. Take-off using FLEX or TOGA
2. Wait for LVR CLB to flash on PFD
3. Try to pull back throttle using XBOX controller to CL indent

### Discord Username (optional)

Skkkitzo#3692

**Comment by aguther** [comment]
Please calibrate your throttles properly using the EFB:
https://youtu.be/8yZuv2L4jPA
