### ISSUE TITLE
No heading, no control level, after update msfs2020

### ISSUE THREAD

**Issue by solidhorizon** [flybywiresim/a32nx#5484]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-17T12:02:12+00:00",
  "ref": "master",
  "sha": "a545c20df9d5d127e95903ad5b7648e46bf7404b",
  "actor": "davidwalschots",
  "event_name": "manual"
```

### Describe the bug

after update msfs2020 no control heading and level and speed

### Expected behavior

working hdg, working leveler, and working ap/speed

### Steps to reproduce

after updating msfs2020 (last update)

### Discord Username (optional)

solidhorizon

**Comment by Benjozork** [comment]
Please provide a video of the issue, I have a very hard time understanding what you mean.

**Comment by Node-Ninja** [comment]
They are most probably referring to this issue #5479 where the heading and/or the speed selectors are not working. Might be a duplicate.

**Comment by Andy672334** [comment]
After the SU5 update the Altitude selector, Heading selector and speed selector knobs are unresponsive. It is not possible to enter 'managed' mode with any of them. With autopilot engaged it is not possible to change aircraft direction, it continues in a straight line,

**Comment by glad2021** [comment]
I had the same issue after the SU5, but I think it's not a bug. They just changed the way you interact with the knobs. You can now pull and push the buttons using Mouse4 and Mouse5 keys. For me these are the keys at the side of the mouse.

**Comment by Andy672334** [comment]
Hi,

Thanks. Everything works fine now. You have been very helpful.

Regards

________________________________

**Comment by solidhorizon** [comment]
I will try to explain, the hdg knob is working, but the speedknob, when I
push it, there is no reaction of the airplain, I have since the update
msfs2020 no control about it anymore, also the levelknob is not working
anymore sometimes the AP refuse to work, also the auto thrust button when I
pushed it , it refuse to work proper, the other problem is, when I choose
to fly with the flybywire airbus the sim crashes sometimes, pl help, asobo
ruined my weekend.

Op za 31 jul. 2021 om 12:13 schreef Andy672334 ***@***.***>:

**Comment by Andy672334** [comment]
If you are using a mouse,  use the side buttons when it is over the knob.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by solidhorizon** [comment]
No reaction, I know what you mean, but I have no control over the airplane
anymore, I read many people got the same issue

Op za 31 jul. 2021 om 14:59 schreef Andy672334 ***@***.***>:

**Comment by aguther** [comment]
if you mean the „new“ interaction system we don’t support it. Please switch from „Lock“ to „Legacy“ in the accessibility options.
