### ISSUE TITLE
Metar print report

### ISSUE THREAD

**Issue by Philly5Alive** [flybywiresim/a32nx#5485]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-30T14:00:27+00:00",
  "ref": "master",
  "sha": "5668670c9fdcd56a31b2a46c95272013fb65e013",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

I get CTD when I try to print the Metar report from the MCDU

### Expected behavior

Printout from the printer

### Steps to reproduce

Load a flight plan from simbrief
request METAR
Print
CTD

**Comment by Samueleonard** [comment]
Also just had a CTD the second i pressed print

**Comment by 2hwk** [comment]
Repeat of #5429, please consolidate discussion about this issue there. Thank you.
