### ISSUE TITLE
Fuel burn does not reset on turn over flight

### ISSUE THREAD

**Issue by jetstarpilotmel** [flybywiresim/a32nx#5486]
### Aircraft Version

Development

### Build info

```json
N/a - using the latest MSFS hotfix (July30/21) & the latest development version of FBW A320.
```

### Describe the bug

Hello Team,

I have noticed that the fuel burn for each engine and total fuel burn for both engines displayed on the lower ECAM display does not reset when completing a turn around flight (second flight)

### Expected behavior

The real plane automatically resets the total fuel burn for each engine and total fuel burn for both engines once each engine has started.

### Steps to reproduce

1. Complete a flight
2. Turn engine 1 & engine 2 off
3. Start engine 1 & engine 2
4. Monitor fuel page to verify total fuel burn and each engines fuel burn has reset to 0.00

### Additional info (optional)

I have noticed this problem before WU5 and the problem still exists with the latest WU5 & MSFS 2020 Hotfix.

### Discord Username (optional)

JetstarcaptainJK#8904

**Comment by RichardPilbery** [comment]
Do you have a reference for this behaviour?

**Comment by John-UK** [comment]
I have implemented this (left engine). I have assumed that a reset would occur anytime the engine is restarted on the ground. If that is the case I will implement for engine 2.

**Comment by RichardPilbery** [comment]
Thanks @John-UK. We really need to ensure that we have the correct logic before implementing. @jetstarpilotmel or @tracernz : do you have a reference for this?

**Comment by tracernz** [comment]
> 
> 
> Thanks @John-UK. We really need to ensure that we have the correct logic before implementing. @jetstarpilotmel or @tracernz : do you have a reference for this?

Yeah, answered on Discord.
> The fuel used indication should reset "when the engine is started on the ground"
and also when the 3 DMCs (display management controllers) are reset (powered off for >= 5 s).
We don't exactly have DMCs implemented yet so I wouldn't worry too much about that one for now.

**Comment by ewold** [comment]
Quality Assurance Tester/Trainee Report

Discord: E-wold#8195
Object of testing: #5486
Tier of Testing: 1
Date: 19/08/2021

Testing Process:
Power up both engines and watch fuel used - OK
Turn off engine 1 - Fuel used value engine 1 remains
Turn on engine 1 - Fuel used value engine 1 resets to 0
Turn off engine 2 - Fuel used value engine 2 remans 
Turn on engine 2 - Fuel used value engine resets to 0 

Negatives: Maybe not for this PR but when switching lower ECAM from FUEL: to ENG page, the used fuel was sometimes updated later on the FUEL page. for example the ENG page showed 90 while the FUEL page showed 80. Maybe rounding is different. 
Testing Results: Passed

Conclusions: Starting engines sets fuel used to 0
