### ISSUE TITLE
[REQUEST] Functional FIX Page

### ISSUE THREAD

**Issue by MrYorkiesWorld** [flybywiresim/a32nx#549]
**Is your feature request related to a problem? Please describe.**
The request is not related to any problem.

**Describe the feature you'd like to see implemented**
A functional FIX page inside of the FMC of the aircraft, allowing users to set custom FIX rings around waypoints or ICAOs

**References**
Not Applicable

**Additional context**
Not Applicable

**Comment by lousybyte** [comment]
Closing since a duplicate issue with more details was opened #1181.
