### ISSUE TITLE
Left engine stops completely directly at the beginning of flight

### ISSUE THREAD

**Issue by transwarp20** [flybywiresim/a32nx#5491]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-30T14:00:27+00:00",
  "ref": "master",
  "sha": "5668670c9fdcd56a31b2a46c95272013fb65e013",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

When beginning a flight just on the runway (no cold & dark), the left engine deactivates immediately. The left engine ignite switch is in the state off and won't move to on. Not with mouseclick or with the switch on the Thrustmaster Throttle quadrant. Right switch and engine is ok. Restart doesn't solve the problem.

### Expected behavior

Left engine stays on, switch works in every state.

### Steps to reproduce

Start MSFS
Start Flight on any Runway (my tests on EDLP, RWY 24)
Begin flight
Left engine shuts down
igniter switch left won't move to on

### Additional info (optional)

This problem occurs since Update V, last hotfix.

**Comment by bouveng** [comment]
I think this is related to key mappings.

Are you using Thrustmaster TCA?
If so, try to remove the bindings for "Toggle Engine 1 Fuel Valve" and "Toggle Engine 2 Fuel Valve".

**Comment by transwarp20** [comment]
Yes, that seems to solve my problem. Many thanks!
