### ISSUE TITLE
Light reflections causes pixels on the textures

### ISSUE THREAD

**Issue by Daboj1337** [flybywiresim/a32nx#5493]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-30T14:00:27+00:00",
  "ref": "master",
  "sha": "5668670c9fdcd56a31b2a46c95272013fb65e013",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

The problem occurs on all surfaces where the light from the Airplane reflects 

<img width="1132" alt="Unbenannt" src="https://user-images.githubusercontent.com/76589309/127745805-316bccf2-8243-4810-9fea-c52957da199a.PNG">

### Expected behavior

No pixelated Textures

### Steps to reproduce

Start a flight turn on all lights

**Comment by NUTTTTTTTT** [comment]
Please try the default FBW livery, this seems like a livery issue after Sim update 5.

**Comment by 2hwk** [comment]
This is an issue with the liveries, not our addon.

**Comment by Daboj1337** [comment]
> This is an issue with the liveries, not our addon.

Okay thanks. I will try!
