### ISSUE TITLE
The Airac database 2107 is not updated on the MCDU

### ISSUE THREAD

**Issue by AngelMSFS2020** [flybywiresim/a32nx#5500]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-31T20:53:08+00:00",
  "ref": "master",
  "sha": "12dd02fba9f16606942a76176c73dfb3da230cfa",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

The Airac database 2107 is not updated on the MCDU. 
It is not possible to fly from a flight plan designed by Simbrief SID, STAR and Waypoint's are not available 

### Expected behavior

![image](https://user-images.githubusercontent.com/88264191/127761287-c54631ac-7a01-45fc-856c-c5d8ecf8d6da.png)

### Steps to reproduce

By programming the MCDU

**Comment by sidnov** [comment]
A32NX uses whatever navdata is available to it. This could be the default in-sim navdata or Navigraph, if you have a subscription. Make sure to reinstall Navigraph if that is causing your issue.
