### ISSUE TITLE
Fuel Flow too high at cruise level

### ISSUE THREAD

**Issue by brunocfalcao** [flybywiresim/a32nx#5501]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-01T07:00:26+00:00",
  "ref": "master",
  "sha": "5a19f07b56ca9ef74916f2ff9532aa72a02ba6f9",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

After aprox. 15 minutes at cruise speed, and without doing anything specific out or ordinary, the fuel flow unexpectedly increased to a very high level.

You can see in the picture it was like 3.8T/h both engines.

![image](https://user-images.githubusercontent.com/34269950/127767309-50f47a10-e1ed-4be0-90c0-6d3b0744a82b.png)

### Expected behavior

The FF shouldn't have increased to that level.

### Steps to reproduce

1. Was executing a flight from SPJC to SEQM
2. SID ATA2F, final FL380
3. After 15 minutes at cruise level, FF climbed up unexpectedly on both engines

### Discord Username (optional)

#6814

**Comment by Spartan3001961** [comment]
The speed tape looks all wrong. What was the outside temps?

**Comment by aguther** [comment]
Please show a screenshot of the lower ECAM. There is currently a live weather issue in MSFS that leads to extreme temperatures and that causes this issue.

**Comment by brunocfalcao** [comment]
I'll redo the flight and check the temps, be right back

**Comment by aguther** [comment]
I did some flights as well last days and it's sometimes also on and off behavior. Temperatures are fine and then they are much too high.

**Comment by brunocfalcao** [comment]
Indeed that was the issue @aguther. Those temperatures are off the grid for this Flight Level.

Since it's not related with our FBW A320neo version but with bugs introduced by SU5 I'm then closing this issue.

![image](https://user-images.githubusercontent.com/34269950/127769623-51026f8d-4baf-4fd8-8b4b-edf6fce85e7b.png)
