### ISSUE TITLE
EFB Navigraph Charts Missed

### ISSUE THREAD

**Issue by Janlu92** [flybywiresim/a32nx#5502]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-31T20:53:08+00:00",
  "ref": "master",
  "sha": "12dd02fba9f16606942a76176c73dfb3da230cfa",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

Navigraph Charts on EFB stop loading in all flights. 

### Expected behavior

I exept to see charts on EFB from start to end of a flight.

### Steps to reproduce

When I start a flight I can see charts of every airport.
Usually during climb/descent charts are no more avaiable. I have to start a new flight to see them.
The problem occur in any single flight.

### References (optional)

![sadasd](https://user-images.githubusercontent.com/88261677/127768831-2ca76535-71bc-4b98-9a4f-2b0230b88a4c.png)
![edmm](https://user-images.githubusercontent.com/88261677/127768834-2bbd6a30-5dda-437d-a555-41f6eab1b8c3.png)
![sadas](https://user-images.githubusercontent.com/88261677/127768837-7ea66256-0a7b-4c2a-abaf-76b376d4c88d.png)

### Additional info (optional)

I tried:
-clean fbw install
-clean community folder-
-using no liveries (included EFB and Cup ones)
Nothing worked.

Charts worked fine for me first 2 days after flypadV2 lunch on DEV version. After 2 day's the problem started.

### Discord Username (optional)

JANLU.92#5583

**Comment by Venorcis** [comment]
Experienced this too yesterday, you can see at https://www.twitch.tv/videos/1116256719?t=01h24m45s that I was just climbing out of LSGG when the charts stopped loading (I tried several times also during my approach to LFMN later without succes).

**Comment by TheOftedal** [comment]
I'm currently working on a complete rewrite of the EFB Navigation page and this issue should get fixed in the upcoming version (which also will include many new features). Unfortunately I currently have no ETA for this as it is dependent on some other PR's, but the page itself is near completion.

**Comment by Benjozork** [comment]
@TheOftedal are you on our Discord so we can discuss this ?

**Comment by Janlu92** [comment]
> I'm currently working on a complete rewrite of the EFB Navigation page and this issue should get fixed in the upcoming version (which also will include many new features). Unfortunately I currently have no ETA for this as it is dependent on some other PR's, but the page itself is near completion.

Nice to hear that!

**Comment by TheOftedal** [comment]
> @TheOftedal are you on our Discord so we can discuss this ?

Yeah, My Discord username is `DrPopsicle#8400`

**Comment by 2hwk** [comment]
Seems outdated/Stale and not relevant with the flyPad overhaul, reopen if still an issue with flyPad OS 3.
