### ISSUE TITLE
TAT SAT temp is too high, engine performance loss

### ISSUE THREAD

**Issue by marci1229** [flybywiresim/a32nx#5503]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-30T14:00:27+00:00",
  "ref": "master",
  "sha": "5668670c9fdcd56a31b2a46c95272013fb65e013",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

During longer flights, the TAT SAT temperatures are much higher than normal even in higher altitudes. This cause the problem that your plane can't fly over FL320 and can't reach the cruising speed even with TOGA. It happens randomly during the flight. I flew with live weather.

### Expected behavior

TAT and SAT temperatures at FL350 should be around -40 celsius. In the sim during this bug its more than +30 celsius.

### Steps to reproduce

Start an IFR flight with FBW A320 which is more than 1:30 and the bug reproduces itself during the flight. The bug comes when you reach your assigned altitude at around FL300-350.

### References (optional)

![BUG 1](https://user-images.githubusercontent.com/72943374/127773766-ee86c537-084f-45f0-b83f-e99c4c02468d.png)
![BUG 2](https://user-images.githubusercontent.com/72943374/127773770-6ae35668-f486-4f5f-b5fc-cc036f6503b0.png)

### Additional info (optional)

Is there any solution? This bug cause alsp the FMGC won't compute your flightplan remaining miles, and also can't climb.

**Comment by sidnov** [comment]
This is a bug with MSFS Live Weather. We recommend using a weather preset until there is a fix from Asobo in place. Closing as it is not related to the FBW A32NX
