### ISSUE TITLE
[BUG] LDG FLAP 3 NOT ON

### ISSUE THREAD

**Issue by TobitFR** [flybywiresim/a32nx#551]
**Mod Version**

Master

**Describe the bug**

The LDG FLAP 3 switch display "OFF" when pressed, it should be "ON"

**To Reproduce**

Click on the LDG FLAP 3 buton

**Expected behavior**

**Actual behavior**

**References**

![image](https://user-images.githubusercontent.com/31391535/92658891-99d5f000-f2f7-11ea-8731-bb61029cd778.png)
![image](https://user-images.githubusercontent.com/31391535/92658915-a8bca280-f2f7-11ea-8c86-4458a4c3adaa.png)

**Additional context**

**Comment by devHazz** [comment]
For the Off to be switched to On, the button model itself would need to be remodelled.

**Comment by NathanInnes** [comment]
Closing this issue in favour of issue #803 being more detailed.
