### ISSUE TITLE
Throttle 2 (right) jumps randomly with XBOX One Controller

### ISSUE THREAD

**Issue by BreakerHUN** [flybywiresim/a32nx#5510]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-01T23:22:07+00:00",
  "ref": "master",
  "sha": "f8d49da80d3be111423026deb08360ddecf37b2b",
  "actor": "MisterChocker",
  "event_name": "manual"
}
```

### Describe the bug

Using XBOX One controller (wireless), the right throttle jumps forward when pressing button A (throttle UP binded there).
Independent Axis is DISABLED on EFB, therfore it should move together

### Expected behavior

They have to move together when "Throttle increase" is pressed and also "Throttle decrease".

### Steps to reproduce

Press the button "Throttle increase" (in my case binded to button A on controller)
The left throttle behaves normal according to how many times the button pressed. 
However right throttle suddenly jumps to CL or FLX causing issues. It randomly jumps to different position.

I DO NOT have any throttle joystick only xbox one controller.

### Additional info (optional)

I have removed the FBW mod completely, and tested on default A320 airplane. The problem DOES NOT happen there. Both throttle levers move together. This concludes something with the mod.

### Discord Username (optional)

BreakerHUN#3986

**Comment by aguther** [comment]
Please show all bindings you have in regards to throttles.

**Comment by BreakerHUN** [comment]
> Please show all bindings you have in regards to throttles.

![image](https://user-images.githubusercontent.com/71471788/127821196-0bfbca16-8f97-441f-8370-c12180339e78.png)

**Comment by BreakerHUN** [comment]
> Please show all bindings you have in regards to throttles.

I have made a video about it, you can watch it here:

https://youtu.be/-W2QxOD6GqY

**Comment by aguther** [comment]
Please resolve the red warning below on the EFB and then click save and apply (I cannot read the text). Your setting was not really saved and applied.

**Comment by BreakerHUN** [comment]
> Please resolve the red warning below on the EFB and then click save and apply (I cannot read the text). Your setting was not really saved and applied.

I did. And saved it. But the problem still occurs.
![image](https://user-images.githubusercontent.com/71471788/127837834-ec9d0c06-d4c4-4481-bb52-26d847ee6d28.png)

**Comment by gb09f** [comment]
Hi folks,

I am also seeing problems with engine 2 thrust lever.  Video below is my Saitek AV8R (don't laugh) calibrated via the EFB:
https://photos.app.goo.gl/WMg2HeaTKLAWJhFB7

Here is the same test with the default Dreamliner:
https://photos.app.goo.gl/APKJoMFrbrH5B4fW6

**Comment by BreakerHUN** [comment]
Gents, did additional testing and resolving the red error message (reverse idle overlapped with idle), allowed me to save the setting. But I had to exit the game and restart and then they indeed move together now.
If others can repair this way then this issue can be closed
