### ISSUE TITLE
Inputted flight level does not match PFD

### ISSUE THREAD

**Issue by sebby1983** [flybywiresim/a32nx#5514]
### Aircraft Version

Development

### Build info

```json
Development
```

### Describe the bug

Inputted 11,000 into the autopilot in managed decent. Cleared level in PFD indicated FL111

### Expected behavior

PFD should display FL110

### Steps to reproduce

Select 11,000 in autopilot in managed decent mode

### References (optional)

![20210801_230721](https://user-images.githubusercontent.com/72167462/127828070-bd76b899-ddca-4589-bc8d-5c48784d4a11.jpg)

### Discord Username (optional)

sebby1983

**Comment by tracernz** [comment]
It's magenta. i.e. a constraint... You can even see on the next waypoint FL111 constraint.
