### ISSUE TITLE
Autobrake issue (Buttons dont stay illuminated) with TCA Quadrant Add-on

### ISSUE THREAD

**Issue by flyingpaul1980** [flybywiresim/a32nx#5516]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-02T01:07:42+00:00",
  "ref": "master",
  "sha": "738f163b180942ba00b626c1f6ca947bd1997103",
  "actor": "2hwk",
  "event_name": "manual"
}
```

### Describe the bug

Reposting of Topic, as requested by AGuther,

When selecting an Autobrake value (lo/med/max), the button lights up, but without further activities it will stop glowing after a while. Sometimes it will illuminate again, and go off again.. in an interval of a few seconds to up to 20-30 seconds.
This results in set autobrakes on final that then don't work after touchdown because the button somehow deactivated.

I know the Autobrake logic was altered after it didnt work anymore some time before SU5, but now it seems to require attention once again.

(key bindings were checked and found to be correct)

When using the Stock Boeings (with a knob in the cockpit), the functionality is flawless.

The problem is even worse in the Stock Asobo A320, where the Autobrake knob has no functionality anymore at all.

Still, the TCA Quadrant was built to give an experience of great immersion for the A320(nx), so i would appreciate if a way for this to work again could be found.

Pre Sim Update 5, the Autobrakes via TCA Quadrant worked flawlessly.

### Expected behavior

Knob on TCA Addon should dial in the Autobrake setting, Setting should be permanent, if nothing in Plane/flight altered.

### Steps to reproduce

1.) Spawn on Runway
2.) Set Autobrake to max
3.) Wait / Read something on the EFB
4.) Watch Button Light turn off and maybe back on later

**Comment by maxpain** [comment]
Same problem with TCA

**Comment by ErikNL80** [comment]
Can also reproduce the issue here with latest dev.

**Comment by crocket63** [comment]
Can't reproduce using a 3way switch to emulate a TCA rotating knob. Works flawlessly.
Dunno what was altered in keyboard events handling?
Can set a higher delay to avoid a long stutter above 650ms to retrigger the button, but that's only idea I have right now

**Comment by ErikNL80** [comment]
> Can't reproduce using a 3way switch to emulate a TCA rotating knob. Works flawlessly.
> Dunno what was altered in keyboard events handling?
> Can set a higher delay to avoid a long stutter above 650ms to retrigger the button, but that's only idea I have right now

It is worth the try!

**Comment by crocket63** [comment]
If you can give it a try!
https://github.com/flybywiresim/a32nx/pull/5584

**Comment by ErikNL80** [comment]
Going to do a test flight right away!

**Comment by ErikNL80** [comment]
> If you can give it a try!
> #5584

Did a succesful test flight, put my report in the PR!
