### ISSUE TITLE
Speed bug in cruise altitude

### ISSUE THREAD

**Issue by miguel370** [flybywiresim/a32nx#5523]
### Aircraft Version

Development

### Build info

```json
{
  "dependencies": [],
  "content_type": "AIRCRAFT",
  "title": "FBW PIIQ Airways",
  "manufacturer": "Airbus",
  "creator": "S. Dikilitas",
  "package_version": "1.0.1",
  "minimum_game_version": "1.7.12",
  "release_notes": {
    "neutral": {
      "LastUpdate": "",
      "OlderHistory": ""
```

### Describe the bug

I apreciate a bug in the speed cruising at 37000ft i am at 250 knots and suddenly it jumps to 200knots and stay there 5 or 6 minuts without touching anything and burning 8800 lbs/h

### Expected behavior

a linear speed during cruise and no jumps

### Steps to reproduce

1.climb at 290 until 35000ft with autothrottle 
2.Suddenly the speed drops to 200knots, burning 8000lbs/h, without touching anything and recovers about 5 or 6 minutes later

**Comment by NUTTTTTTTT** [comment]
MSFS live weather is currently bugged - recommended to use a weather preset until this is patched, not specific to the FlyByWire.

See for more info: https://docs.flybywiresim.com/start/reported-issues/#msfs-live-weather
