### ISSUE TITLE
A320nx issues after MS Update

### ISSUE THREAD

**Issue by dashawn11** [flybywiresim/a32nx#5525]
### Aircraft Version

Development

### Build info

```json
Current unstable master branch build as stable build was removed from MS Marketplace
```

### Describe the bug

I downloaded the plane from marketplace today after installing latet MS update. All lights are not properly working correctly. Lights stay on and can't be turned off. Plane takes too long to climb and stay stuck on altitude level for a long time before climbing again if it climbs at all. Not following destination line correctly and keep going off course. This is a constant since newest Microsoft update. Annoyed. Know how to operate this plane. 

### Expected behavior

The way plane used to behave prior to MS update. 

### Steps to reproduce

Just fly the plane as normally would.

**Comment by Benjozork** [comment]
The marketplace version (stable) is not functional as we have announced. Please use dev from the installer.

**Comment by dashawn11** [comment]
I am receiving error message using installer. Can you send me link to the installer please in case there is issue with one I downloaded.
