### ISSUE TITLE
CTD

### ISSUE THREAD

**Issue by CapJambo** [flybywiresim/a32nx#5526]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-08-04T00:57:39+00:00",
  "ref": "v0.6.2",
  "sha": "1f940ca300187689e4f86881744cffc1afecf4d7",
  "actor": "2hwk",
  "event_name": "manual"
}
```

### Describe the bug

tried to load the aircraft on a terminal at KSFO. Instant CTD.

### Expected behavior

Load to aircraft

### Steps to reproduce

1-Load aircraft
2-Choose terminal
3-Fly
4-CTD

**Comment by Benjozork** [comment]
Please read the release notes:

![image](https://user-images.githubusercontent.com/4503241/128111069-2cf0830b-2d24-4b36-94e3-535159834100.png)
