### ISSUE TITLE
"Retard" callouts after 10ft, and not 20 feet, as IRL

### ISSUE THREAD

**Issue by tush0701** [flybywiresim/a32nx#5527]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-03T21:21:36+00:00",
  "ref": "master",
  "sha": "bf3cbdd401722582fbb129c1108b0836ae783a31",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

In the latest dev release, the "Retard" callout is heard after crossing 10ft, rather than 20 feet as it is IRL.

Reference: https://safetyfirst.airbus.com/a-focus-on-the-landing-flare/

Text quoted: The A320 FCTM explains that the flight crew can rapidly retard all thrust levers to IDLE either earlier or later than the 20 ft “RETARD” auto callout reminder depending on the conditions. 

However, it is occurring at 10 feet at all airports I tested.

### Expected behavior

Retard callout should occur at 20 feet

### Steps to reproduce

1. Fly approach any airport with A/T (LVR CLB)
2. Retard is heard at 10 feet.

### References (optional)

IRL : https://safetyfirst.airbus.com/a-focus-on-the-landing-flare/

### Discord Username (optional)

tbone0793

**Comment by wpine215** [comment]
Noticed this as well.

**Comment by tush0701** [comment]
Initially I thought the callout was not there at all, but then I tested and got it at 10 feet.

**Comment by tracernz** [comment]
Should be 10 feet when conducting an autoland, so we're half right. 😆

**Comment by tush0701** [comment]
That is true, at that stage it's an "order", unlike during manual landing, when at 20ft it's a "Reminder".

**Comment by Hurricane83b** [comment]
Same issue here... When will this be updated?

**Comment by Benjozork** [comment]
We do not provide release dates or ETAs.
