### ISSUE TITLE
New 6.2 stable version problems

### ISSUE THREAD

**Issue by pacha35** [flybywiresim/a32nx#5528]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-08-04T00:57:39+00:00",
  "ref": "v0.6.2",
  "sha": "1f940ca300187689e4f86881744cffc1afecf4d7",
  "actor": "2hwk",
  "event_name": "manual"
}
```

### Describe the bug

Hello,
I have tested the new 6.2.0 stable without and with Air France livery : no difference.
- as in the precedent versions, in RNAV flight, at the landing, the plane does not up the nose just before to touch down (as in the real plane) : we need to land in manual.
- sometimes, to move switches in the head panel (external lights) with the mouse, we need to use the letf button and the scroll wheel, but sometimes no !
- There is no Keybord option in the reaelism menu of the MCDU (see picture)
- AutoBreak selector use only the max position (it's work fine in dev version).
Regards,
Pacha35
![realism_01](https://user-images.githubusercontent.com/46076619/128170757-104ec631-eaf5-4fbc-bcb2-44f3ce24d760.jpg)

### Expected behavior

I hope to land as in real life when I choose RNAV approach flight mode : leave the plane touch down before to youse joystick commands.

### Steps to reproduce

- a32nx without any other addons in Community
- a32nx with Air France livery
- RNAV flight on a short flight (35 mn) from LFRN to LFRB
- meteo: cavok
-  Cold and dark starting flight
- FPL entered directly in the MCDU
- TCA Quadrant + addons + T-rudder (Thrustmaster)

### Discord Username (optional)

Pacha35#2999

**Comment by Benjozork** [comment]
This stable version is based off of the previous v0.6.1. Therefore it is normal and expected that the features in v0.7.0-dev are not there.

**Comment by pacha35** [comment]
Hi,
I have never spoken about 7.0 version, I just test the 6.2 and read the internet page about it on the FBW site. 

![V6 2 0_002](https://user-images.githubusercontent.com/46076619/128180640-05f8690f-4170-426b-a485-1aff7c12f1ad.jpg)

**Comment by NUTTTTTTTT** [comment]
> Thanks in your answer.
> Another question, in the stable version, we need to enter TCA Throttle parameters by MSFS and in the dev version by EFB (but it's not so precise). In the future what system do you keep ?
> Regards

Development version is what will Stable will become over time, and pretty much everything on dev will make its way to stable version 0.7.0.

The difference is just that development version updates with these features as they're built and implemented, whereas stable gets less frequent but more ironed out builds as they've been tested over the previous few months on development by the majority of users already. It's basically the "in progress stable version 0.7.0". :)

**Comment by Valastiri** [comment]
> Hi,
> I have never spoken about 7.0 version, I just test the 6.2 and read the internet page about it on the FBW site.
> 
> ![V6 2 0_002](https://user-images.githubusercontent.com/46076619/128180640-05f8690f-4170-426b-a485-1aff7c12f1ad.jpg)

Apologies here. This page will be updated to reflect only available on development.

**Comment by tracernz** [comment]
> I hope to land as in real life when I choose RNAV approach flight mode : leave the plane touch down before to youse joystick commands.

RNAV is a non-precision approach. IRL the autopilot will disconnect automatically when descending below minimums.

**Comment by pacha35** [comment]
Yes, the flight is RNAV but I spoke about an ILS approach with DH=20

**Comment by davidwalschots** [comment]
> Yes, the flight is RNAV but I spoke about an ILS approach with DH=20

This is the first time the word "ILS" is used within this topic.

Seems to me there has been enough explanation on why certain features are missing on that version. I'll close this.
