### ISSUE TITLE
Manual breaking (on landing) does not disengage autobraking

### ISSUE THREAD

**Issue by Teslix** [flybywiresim/a32nx#5533]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-30T14:00:27+00:00",
  "ref": "master",
  "sha": "5668670c9fdcd56a31b2a46c95272013fb65e013",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

Autobrake set low or med for landing. After landing, braking is applied according to low/med autobrake. Once slowed enough, tapping the manual brakes to disengage the autobraking no longer disengages them and the aircraft will come to a complete stop unless the autobrake is disengaged manually by pressing the relevant button.

### Expected behavior

Tapping the brakes manually during a landing should disengage the autobraking system.

### Steps to reproduce

1. Fly an approach normally, set autobraking to low or medium.
2. Land the aircraft, autobraking is applied automatically.
3. Tap or hold the manual breaks and then release them, autobrake should turn off but doesn't and the aircraft will stop.
4. Turning off autobrake by clicking the lit autobrake light/button will turn off the braking action.

**Comment by NUTTTTTTTT** [comment]
Please update to the latest development version and test, you do need to hold the brakes for a sec to disengage auto brake.

**Comment by Teslix** [comment]
I updated to the latest dev release and the problem is gone. Weird, as I was only one or two versions back at most, but definitely couldn't disengage the autobrakes with manual breaking in my last 5-6 flights. Works great now though!
