### ISSUE TITLE
Passenger Bridge clipping into the Plane (Asobo Bug?)

### ISSUE THREAD

**Issue by KeepGamingLP** [flybywiresim/a32nx#5534]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-04T11:40:50+00:00",
  "ref": "master",
  "sha": "fe97ce409e1f9d55b11185de38ce069915934bc9",
  "actor": "MisterChocker",
  "event_name": "manual"
}
```

### Describe the bug

The passenger-bridge at airports clip into the aircraft/cockpit

### Expected behavior

the passenger bridge should not clip into the aircraft

### Steps to reproduce

Load in at airport
connect the bridge to the aircraft

### References (optional)

![Microsoft Flight Simulator Screenshot 2021 08 04 - 17 58 14 91](https://user-images.githubusercontent.com/72626508/128220649-e7688b30-836a-451f-9eb7-0b7e0d0c6443.png)

### Discord Username (optional)

KeepGamingLP#4346

**Comment by scoopscode** [comment]
Yes this is an Asobo bug
