### ISSUE TITLE
QNH in PFD not flashing when climbing past transition alt. (Dev. Version).

### ISSUE THREAD

**Issue by PM3Delta** [flybywiresim/a32nx#5535]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-03T21:21:36+00:00",
  "ref": "master",
  "sha": "bf3cbdd401722582fbb129c1108b0836ae783a31",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

The QNH in the PFD is not flashing anymore, when climbing past the set transition altitude (in PERF e.g. 10000ft).  The Menu Animations are switched On.  The QNH was set to 1012 (Live Weather Off).  (Departure EDDF, RWY18, CINDY 1L).

![Screenshot (430)](https://user-images.githubusercontent.com/60411051/128229546-348f09be-c3d1-4832-95ee-35b8ce98c7c2.png)

However, when descending and passing the trans. alt from above, the STD in the PFD does flash as expected.

Thanks a lot.

### Expected behavior

The QNH to be flashing when passing the trans. alt and therefore warning to switch to STD.

### Steps to reproduce

Ensure PERF: Trans. Alt set to 10000ft
Menu Animations ON
Live Weather OFF (due to Asobo SU5 bug).
Set QNH different to 1013.
Take off.
Pass Trans. Alt. 
Observe PFD.

### Discord Username (optional)

SierraHotel2873#5470

**Comment by aguther** [comment]
I think the issue happens whenever the default transition altitude is used.

**Comment by Kimbyeoungjang** [comment]
If you use the default TA located in PERF - Takeoff page (10,000ft), QNH won't flash because it is not initialized to 10,000ft.

So, Can you try with custom TA like 12,000ft? I mean you should enter TA(not a default TA)

**Comment by aguther** [comment]
@Kimbyeoungjang Using a custom transition altitude works.
