### ISSUE TITLE
Acceleration Altitude Altitude Not Obeyed

### ISSUE THREAD

**Issue by avielmenter** [flybywiresim/a32nx#5537]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-02T20:07:45+00:00",
  "ref": "master",
  "sha": "62a565f79ef6bbc4db5c2e521cd69fba932ad717",
  "actor": "wpine215",
  "event_name": "manual"
}
```

### Describe the bug

The a32nx in the dev version seems to ignore the acceleration altitude set in the MCDU. This was working fine on stable, but is now presenting me an issue in the development build. Instead, when the thrust reduction altitude is below the acceleration altitude, the a32nx begins to accelerate right when thrust is reduced, without waiting for the acceleration altitude.

### Expected behavior

The a32nx should only begin to accelerate to managed speed after passing the configured acceleration altitude, whether or not climb thrust has been set.

### Steps to reproduce

1. Load into KSNA
2. Configure the PERF page such that THR RED/ACC is 860/3060
3. Take off RWY 20R
4. Reduce to climb thrust at 860 ft
5. Watch as the a32nx begins to acccelerate

### Discord Username (optional)

avi#0885

**Comment by aguther** [comment]
I cannot reproduce the problem:
https://youtu.be/apAPjZhFD08

One important thing to know is that the SRS law has a pitch limitation to 18°. That could mean that if you're very light that the plane will accelerate because the SRS law is not allowed to further pitch up.

**Comment by avielmenter** [comment]
Further testing suggests I may just have not been entering the climb detent fast enough—takes some time getting used to the new config. Thank you for testing it.
