### ISSUE TITLE
flicker displays when changing power source

### ISSUE THREAD

**Issue by ErickSharp** [flybywiresim/a32nx#5542]
### Aircraft Version

Development

### Description

When the power source of the displays transfers from one to another, the displays should have a brief flickering effect.

### Discord Username (optional)

Erick [Z-6]#6484

**Comment by Samueleonard** [comment]
i dont think this is a problem anymore in the newer MSNs, airbus came up with a solution

**Comment by hotshotp** [comment]
this is true, this no longer happens. only some indicators on the displays like the flaps flicker
