### ISSUE TITLE
Bad LVAR value for A32NX_AUTOPILOT_FPA_SELECTED

### ISSUE THREAD

**Issue by phildeg31** [flybywiresim/a32nx#5543]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-04T11:40:50+00:00",
  "ref": "master",
  "sha": "fe97ce409e1f9d55b11185de38ce069915934bc9",
  "actor": "MisterChocker",
  "event_name": "manual"
}
```

### Describe the bug

When setting 0 for Vertical Speed, the LVAR A32NX_AUTOPILOT_VS_SELECTED is set to 0 and the LVAR A32NX_AUTOPILOT_FPA_SELECTED is set to 0 too:
![FPA value to 0](https://user-images.githubusercontent.com/74733393/128375191-2986d30f-904a-4146-915b-819cc4ffd304.JPG)

When setting a value other than 0 for Vertical Speed (for example +400 or +500), the LVAR A32NX_AUTOPILOT_VS_SELECTED is set to this value but the LVAR A32NX_AUTOPILOT_FPA_SELECTED is always set to 9.8999 and not to 0:
![FPA value not 0](https://user-images.githubusercontent.com/74733393/128375221-267fb9c7-3598-4fdb-b166-7ae740f04f9e.JPG)

Also, it seems that, when changing from VS mode to TRK/FPA mode or vice-versa, the LVAR A32NX_FCU_MODE_REVERSION_TRK_FPA_ACTIVE is always to 0 (This LVAR should indicate if TRK/FPA mode is activated or not right?).

### Expected behavior

The LVAR A32NX_AUTOPILOT_FPA_SELECTED should be always 0 when I am in vertical speed mode and only the LVAR A32NX_AUTOPILOT_VS_SELECTED should be updated.

### Steps to reproduce

1. In VS mode, set the VS to 0 -> The value of both LVARs should be 0
2. Set an other VS value -> The value of A32NX_AUTOPILOT_VS_SELECTED is correct but the value for A32NX_AUTOPILOT_FPA_SELECTED is incorrect (always 9.8999)

**Comment by aguther** [comment]
In regards to the variable `A32NX_FCU_MODE_REVERSION_TRK_FPA_ACTIVE`:
> Triggers the FCU to revert to HDG/VS mode

See also https://github.com/flybywiresim/a32nx/blob/master/docs/a320-simvars.md#autopilot-system

In regards to the other variable you‘re right it can be 0 but I don‘t see a „must“ tbh. It‘s not being used when the mode is not active.

**Comment by phildeg31** [comment]
For A32NX_FCU_MODE_REVERSION_TRK_FPA_ACTIVE, is there a LVAR permitting to know that the TRK/FPA mode is active or not (if not then we are in VS mode)?
It is to display A32NX_AUTOPILOT_FPA_SELECTED value instead of A32NX_AUTOPILOT_VS_SELECTED if I am in TRK/FPA mode.

**Comment by aguther** [comment]
It’s documented in the link I provided.

**Comment by phildeg31** [comment]
I do not find a LVAR for it. I checked some LVAR available thanks to SPAD.next but I do not find one having its value updated when switching in TRK/FPA mode... :/

**Comment by aguther** [comment]
A search for FPA on the linked document reveals:
`A32NX_TRK_FPA_MODE_ACTIVE`

**Comment by phildeg31** [comment]
Ok I will try thank you.
