### ISSUE TITLE
Add a LVAR for selected speed

### ISSUE THREAD

**Issue by phildeg31** [flybywiresim/a32nx#5544]
### Aircraft Version

Development

### Description

There is a LVAR for A32NX_AUTOPILOT_HEADING_SELECTED to have the selected heading but it seems that there is no LVAR to have selected speed. Because of that I use AUTOPILOT AIRSPEED HOLD VAR but the value is set in it only when I activate selected mode and not when I select the value in managed mode (by turning the selector with the dot displayed) BEFORE pulling the button to be in selected mode.

**Comment by aguther** [comment]
Thank you for you suggestion. Please create a separate issue for each request because it eases the handling.

**Comment by phildeg31** [comment]
I created an other ticket for event ;)
