### ISSUE TITLE
Add an event to change altitude increment

### ISSUE THREAD

**Issue by phildeg31** [flybywiresim/a32nx#5545]
### Aircraft Version

Development

### Description

Is it possible to have an event to change the altitude increment from 100 to 1000 or vice-versa please? 

For now, I have to change it in game before turning the selector (I use events A32NX.FCU_ALT_INC and A32NX.FCU_ALT_DEC for selector).

**Comment by aguther** [comment]
Just for your information, you can send the desired increment with the event:
![image](https://user-images.githubusercontent.com/6629914/128419840-4375bf1f-2dbf-42f5-8605-e5730f4189fb.png)

https://docs.flybywiresim.com/start/autopilot-fbw/#default-events

**Comment by aguther** [comment]
I will go ahead and close the issue, if you feel the need for an event to switch the "physical" switch on the FCU feel free to reopen. In my eyes the events should give you what you need.

**Comment by phildeg31** [comment]
The aim is to have an event to change the increment on the FCU yeah because when you configure the events A32NX.FCU_ALT_INC and A32NX.FCU_ALT_DEC, the value is not dynamic :/

**Comment by aguther** [comment]
I really must ask you if you really click on my links and have a look. They are dynamic. It’s documented. Please read it.

**Comment by phildeg31** [comment]
When configuring the event in SPAD.Next, you configure an action for the click on the button or when turning the selector in that case. This action will be the event sending with 100 or with 1000 as parameter in xml file (the SPAD.Next file is an XML file). So for me it is "static". 
I can try to have something dynamic according to the value of a local variable having its value changing by pressing a button (the button for which I wouldmike to send an event to change the increment). By doing that, maybe I can send the event with parameter 100 or an other one with parameter 1000 according to a condition based on this local variable. 
It would be easier to send an event to change increment on FCU by pressing the button and then turning the selector to send event with parameter equal to 0 (meaning that it uses the increment in game). This will be dynamic according to the increment in game and not a static increment in parameter. This is what I mean by "dynamic".
Thank you.

**Comment by aguther** [comment]
As you see I reopened the issue, will try to add an event after work.
