### ISSUE TITLE
Altitude does not continue to decrease during approach

### ISSUE THREAD

**Issue by phildeg31** [flybywiresim/a32nx#5546]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-04T11:40:50+00:00",
  "ref": "master",
  "sha": "fe97ce409e1f9d55b11185de38ce069915934bc9",
  "actor": "MisterChocker",
  "event_name": "manual"
}
```

### Describe the bug

I set the approach altitude in managed mode, the altitude descreases until a waypoint with a constraint:
![before deceleration point](https://user-images.githubusercontent.com/74733393/128390780-a01c9c4d-d174-469d-993f-8b46e35cfd2c.JPG)
 

After that, it seems to stay blocked to that altitude (here 9000 ft for the last waypoint with a constraint). Here I waited after deceleration point to see how altitude was managed:
![after deceleration point](https://user-images.githubusercontent.com/74733393/128390805-be7c1181-59a3-4a25-bde5-aeb7a805da96.JPG)

I have to set the altitude in selected mode to have the altitude decreasing again (without setting a specific VS).

I had a similar issue before but I think it was solved (it was a problem due to the altitude constraint set for the waypoint -> this altitude was kept by the autopilot). I have this issue again.

### Expected behavior

The altitude should continue decreasing.

### Steps to reproduce

Top of descent was not displayed but I set the approach altitude (ie 3000 ft) when the top of descent should be displayed (the next waypoints have altitude constraints).

**Comment by MisterChocker** [comment]
@phildeg31 which approach is this?

@aguther any ideas how that can be?

**Comment by phildeg31** [comment]
It is an ILS.

Here is the previous ticket: https://github.com/flybywiresim/a32nx/issues/4221#issuecomment-811768953

**Comment by aguther** [comment]
Well, you’re in ALT CST, which means the AP has captured an altitude constraint.

i guess there was one at 9000 ft. Maybe the variable was not cleared correctly.

**Comment by phildeg31** [comment]
Yes like I said, and you can see it on first screen, there are 2 waypoints with an altitude constraint. The first one with 10000ft and the second one with 9000ft.

**Comment by aguther** [comment]
This issues is related to flight plan manager. I pretty sure it will be fixed with the new flight plan manager in the works. As a workaround in the meantime you can engage OP DES which ignores the altitude constraint.

**Comment by MisterChocker** [comment]
The ting is that the constraint manager does it job as seen in the image, the target altitude correctly changes, however the AP and FMA seem to "ignore" this. Not sure what the guidance underneath that receive. However the contraint alt simvar is being correctly updated.

**Comment by aguther** [comment]
If anyone has an FDR file for me from a flight where it happened it would help analyzing the issue.

**Comment by phildeg31** [comment]
Hi, I am in holidays but I can try to provide you a FDR file at the end of next week if you explain me how to do it please ;).

I found this documentation saying that FDR file can be found in work folder:
https://docs.flybywiresim.com/start/autopilot-fbw/
Is there something to configure or to do before the flight?

**Comment by aguther** [comment]
That would be good. You just need to do the flight. The FDR is always running.

**Comment by phildeg31** [comment]
Ok I will do the flight when I will come back at home at the end of my holidays (end of next week).
There is one FDR file by flight?

**Comment by aguther** [comment]
Yes

**Comment by phildeg31** [comment]
Hi, sorry someone of my family is at the hospital so I am not at home this week-end to do the flight. I will do the flight next week-end (I do not forget).

**Comment by phildeg31** [comment]
I did the flight today but I cannot add the FDR file because format is not allowed and a zip is too big (100MB).

**Comment by phildeg31** [comment]
Lien vers Google drive où j'ai mis le fichier: https://drive.google.com/file/d/1SAAEz-2zrSH1ICuO5hi22q4F5Osq2yC1/view?usp=sharing

**Comment by derl30n** [comment]
I assume this has been fixed?

**Comment by tracernz** [comment]
Yes. 👍
