### ISSUE TITLE
Callout of 5 feet!

### ISSUE THREAD

**Issue by TLSY2** [flybywiresim/a32nx#5549]
### Aircraft Version

Development

### Description

I never heard callout of 5, and my landings are butter!

**Comment by aguther** [comment]
The call-out is already implemented on development version:
https://user-images.githubusercontent.com/6629914/128423377-fd005ca9-0827-446a-a7c0-146317d3f71b.mp4

**Comment by aguther** [comment]
The plane needs to be in the right state. Maybe do a Video?
