### ISSUE TITLE
Everything is too bright after SU5

### ISSUE THREAD

**Issue by TLSY2** [flybywiresim/a32nx#5550]
### Aircraft Version

Development

### Build info

```json
newest!
```

### Describe the bug

Since su5, everything is too bright in cabin.

### Expected behavior

not as bright!

### Steps to reproduce

turn brightnes up to 40% at night and its bright like before 100%

**Comment by Benjozork** [comment]
Please provide screenshots..

**Comment by TLSY2** [comment]
![20210805220224_1](https://user-images.githubusercontent.com/81220083/128406536-917d8107-2026-43df-b5c2-6d312824fd03.jpg)
Dont know if you can tell from this (low res too) but they look very bright!

**Comment by hotshotp** [comment]
This looks perfectly correct

**Comment by TLSY2** [comment]
![20210808132717_1](https://user-images.githubusercontent.com/81220083/128629076-a27930f1-97dc-4111-9adb-f858858731c8.jpg)
![20210808132821_1](https://user-images.githubusercontent.com/81220083/128629080-7a031e37-03ed-458f-b172-af0ef0bb2c28.jpg)
![20210808132714_1](https://user-images.githubusercontent.com/81220083/128629081-e2c97595-d708-4671-bf40-0af7293d28cf.jpg)

**Comment by TLSY2** [comment]
half brightness!
