### ISSUE TITLE
A32NX broken since WU 5

### ISSUE THREAD

**Issue by worlfire23** [flybywiresim/a32nx#5565]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-06T01:30:48+00:00",
  "ref": "master",
  "sha": "7b0ae75be56893c10c3bde1a18b548609355ac02",
  "actor": "tracernz",
  "event_name": "manual"
}
```

### Describe the bug

Tryed every version with the installer, an clean installation of MS2020, differrent airports, removing all mods (liverys) and  so on still the same outcome. Sometimes game crashes completly when loading in, and when it loads -> this happens... tried a lot of things would appreciate a response. Other planes are completly fine. Before sim update 5 everything worked completly fine.
![Microsoft Flight Simulator Screenshot 2021 08 06 - 20 34 02 51](https://user-images.githubusercontent.com/88556804/128556485-bcc646c0-c0d1-4fd8-a35b-600f879121f1.png)
![Microsoft Flight Simulator Screenshot 2021 08 06 - 20 33 08 84](https://user-images.githubusercontent.com/88556804/128556491-bb74cbc3-c7cf-4425-a817-1c1d604939f5.png)
![Microsoft Flight Simulator Screenshot 2021 08 06 - 20 33 55 17](https://user-images.githubusercontent.com/88556804/128556495-3ac10b4c-1a89-447e-b163-d939e1f92c35.png)

### Expected behavior

Normal textures, working displays, no crashes 

### Steps to reproduce

1. Launch Game
2. select Fly By Wire A32NX
3. Gate/Airport of choice 
4. Load in 

### Discord Username (optional)

DavE#0369

**Comment by NUTTTTTTTT** [comment]
That's a livery issue afaik, try the default FlyByWire (not the Asobo one shown) livery, or a livery known to be compatible.

**Comment by aguther** [comment]
Be sure you removed the A32NX from the content manager

**Comment by worlfire23** [comment]
Guys thanks for the great and fast response, the update solved the crashing and it seems like i actually had a double copy installed. So everything is fixed after 2 days of heartbreaks. Just wanna say thank you, you really created a piece of art for the community and this support is top notch. Much better then the support on payware aircrafts. KEEP UP THE GOOD WORK. Blue skies !!

**Comment by sidnov** [comment]
Issue resolved ✅
