### ISSUE TITLE
strobe lights

### ISSUE THREAD

**Issue by youngryan7** [flybywiresim/a32nx#5574]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-07T04:01:01+00:00",
  "ref": "master",
  "sha": "10169b43abb8568044bab599783275b34f2bca70",
  "actor": "tracernz",
  "event_name": "manual"
}
```

### Describe the bug

strobe lights on when switched to off position

### Expected behavior

strobe lights off when switch is off

### Steps to reproduce

load up
turn strobe lights off
look outside at lights

### References (optional)

lights are off in auto position and on position

**Comment by ryan205** [comment]
See pull request #5595
