### ISSUE TITLE
Tooltips missing, SU5 ModelBehavior XML Errors (To console)

### ISSUE THREAD

**Issue by 2hwk** [flybywiresim/a32nx#5575]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-30T02:31:34+00:00",
  "ref": "master",
  "sha": "bab6a451346ee9fb2a28abe20bf4ec454933e371",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

The tooltips for the strobe and taxi lights are now missing (used to reflect state of these lights), and the model Behavior XML Errors are being printed to console. These should be cleaned up. Good first issue.

![image](https://user-images.githubusercontent.com/15316958/128595674-58f38949-1919-42eb-81fb-6b557b67b2cc.png)

### Expected behavior

Tooltips display and no errors are being passed to the console.

### Steps to reproduce

1. Load in with A32NX
2. Old Tooltips are missing from Strobe and Taxi Lights.
3. Have Developer mode turned on, press ~ to open console
4. Observe that Model Behavior errors are being printed

### References (optional)

N/A

### Discord Username (optional)

2Cas#1022

**Comment by kpotschi** [comment]
What language are you running MSFS in?

**Comment by 2hwk** [comment]
English

**Comment by derl30n** [comment]
Since two prs should've closed this issue, I'll close it now manually, if any issues persist please re-open or open a new issue.

**Comment by derl30n** [comment]
Whats the status of this?

**Comment by juliansebline** [comment]
@aguther It's fixed. I cannot find the commit because most of them are mixed with other files but I cannot see the console errors nor the TT missing.

@derl30n @2hwk
