### ISSUE TITLE
ECAM not showing engine pressure after exceeding 130 PSI

### ISSUE THREAD

**Issue by rickvandijck** [flybywiresim/a32nx#5576]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-07T04:01:01+00:00",
  "ref": "master",
  "sha": "10169b43abb8568044bab599783275b34f2bca70",
  "actor": "tracernz",
  "event_name": "manual"
}
```

### Describe the bug

Engine pressure disappears from lower ECAM display when it exceeds 130 PSI

### Expected behavior

ECAM display showing engine pressure at all times

### Steps to reproduce

1. Follow normal startup procedure
2. ENGINE MODE > START
3. TURN ON ENG 2 MASTER

### References (optional)

![Uploading PRSGONE.png…]()

### Discord Username (optional)

Rick#1234

**Comment by andrejetcat** [comment]
you mean engine Oil pressure? 
It beacause this value is still not implementated. (engine model) The real life value is around 25-30, so this indicated 120 is still beyond the range.

**Comment by DomWin02** [comment]
![20210815124820_1](https://user-images.githubusercontent.com/88674959/129475932-c4487e16-a4f1-408d-991e-8a208c82a94a.jpg)

I can agree

**Comment by juliansebline** [comment]
related to #6861

Enable the animations in the game parameters and it will work but it's a workaround as everything is being refactored
