### ISSUE TITLE
Where Is The Download Link For The Dev Version?

### ISSUE THREAD

**Issue by NatalieGates** [flybywiresim/a32nx#5579]
### Aircraft Version

Development

### Build info

```json
Where is the download link for the dev version? Doesn't it take multiple people to approve decisions to remove links? More than two people decided it would be a good idea to remove the download link from github readme file and make us go to the website to then download the dev link?

Bravo!
```

### Describe the bug

Where is the download link for the dev version? Doesn't it take multiple people to approve decisions to remove links? More than two people decided it would be a good idea to remove the download link from github readme file and make us go to the website to then download the dev link?

Bravo!

### Expected behavior

Where is the download link for the dev version? Doesn't it take multiple people to approve decisions to remove links? More than two people decided it would be a good idea to remove the download link from github readme file and make us go to the website to then download the dev link?

Bravo!

### Steps to reproduce

Where is the download link for the dev version? Doesn't it take multiple people to approve decisions to remove links? More than two people decided it would be a good idea to remove the download link from github readme file and make us go to the website to then download the dev link?

Bravo!

**Comment by NatalieGates** [comment]
No Seriously, where is the github dev file? I went to the website and I am only presented with the installer. I don't want a messy installer. I want the zip folder from github.

So ridiculous whoever approved those changes!

**Comment by NatalieGates** [comment]
More than two people thought this was a good idea? Wow! Amazing work maintainers, amazing work!

**Comment by sidnov** [comment]
![Screenshot_20210808-032244~2.png](https://user-images.githubusercontent.com/29005005/128614771-6f6034e6-3782-4098-8fb1-06a341623fc1.png)

**Comment by Benjozork** [comment]
Impolite comments is not tolerated here.

**Comment by sidnov** [comment]
- Please follow the issue template
- Please maintain an appropriate tone while communicating your problems. Bashing here is not appreciated by anyone

**Comment by davidwalschots** [comment]
I removed the download links. GitHub is a platform for developers and less so for the average user. Thus, the now smaller README redirects users to our website which is far easier to use. The installer in itself is easier to use as well. As sidnov has shown you are still able to do a direct download there.

If you have an organisational vision on how to make companies more corporate and less efficient, then I suggest you roll that vision out in a company run by yourself. Bravo!
