### ISSUE TITLE
psi indicator number light fading in and out 

### ISSUE THREAD

**Issue by youngryan7** [flybywiresim/a32nx#5580]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-07T04:01:01+00:00",
  "ref": "master",
  "sha": "10169b43abb8568044bab599783275b34f2bca70",
  "actor": "tracernz",
  "event_name": "manual"
}
```

### Describe the bug

psi number light of number fading in and out 

### Expected behavior

not to fade in and out

### Steps to reproduce

load up
start engines 
watch psi indicator 

### References (optional)

![2021-08-07 (1)](https://user-images.githubusercontent.com/59422760/128614929-369dce20-16d6-4e0d-a2d1-821394259073.png)

**Comment by sidnov** [comment]
The pulsing is a feature on the EICAS. Any references to prove it's a bug?
