### ISSUE TITLE
when zoomed out screens unreadable

### ISSUE THREAD

**Issue by TLSY2** [flybywiresim/a32nx#5583]
### Aircraft Version

Development

### Build info

```json
}
"built": "2021-08-07T04:01:01+00:00",
"ref": "master",
"sha": "10169b43abb8568044bab599783275b34f2bca70",
"actor": "tracernz",
"event_name": "manual"
}
```

### Describe the bug

When you zoom out more the screens are unreadable because of their thin writing

### Expected behavior

readable at any zoom

### Steps to reproduce

zoom out

**Comment by 2hwk** [comment]
Something was changed with how displays are rendered in SU5. Not sure if we can or will fix this one.

**Comment by TLSY2** [comment]
> Something was changed with how displays are rendered in SU5. Not sure if we can or will fix this one.

It was before as well but it was more readable, after the pixelasation of the screens it was more!

**Comment by MisterChocker** [comment]
@TLSY2 please provide the build info.

**Comment by TLSY2** [comment]
> @TLSY2 please provide the build info.

10169b4

**Comment by MisterChocker** [comment]
Thats not the build info, 
![image](https://user-images.githubusercontent.com/1857322/128637636-19058937-cff8-474f-b96e-fe9947ad551d.png)

**Comment by TLSY2** [comment]
> > [10169b4](https://github.com/flybywiresim/a32nx/commit/10169b43abb8568044bab599783275b34f2bca70)
> 
> Thats not the build info
> 
> ![image](https://user-images.githubusercontent.com/1857322/128637636-19058937-cff8-474f-b96e-fe9947ad551d.png)

  "built": "2021-08-07T04:01:01+00:00",
  "ref": "master",
  "sha": "10169b43abb8568044bab599783275b34f2bca70",
  "actor": "tracernz",
  "event_name": "manual"
}

I dont know how this helps you, but its for everyone issue?

**Comment by MisterChocker** [comment]
Thanks for providing the build info.

Do you have by any change a screenshot that shows the issue?

**Comment by TLSY2** [comment]
> Thanks for providing the build info.
> 
> Do you have by any change a screenshot that shows the issue?
> 
> Also what's your games resolution and render scale?

screenshots later,

Res scale 100 (1920x1080)
render 150

**Comment by deiks** [comment]
Similar for me. Looks like everything is in blur. When I zoom, I can see it clearly.
Like it expects to be in 4K.

GTX 1070 (1920x1080), using High-end with some settings on Ultra.

**Comment by sidnov** [comment]
Some liveries can cause that. Try with the default livery to check if the issue persists and attach screenshots too.

**Comment by TLSY2** [comment]
![20210809185524_1](https://user-images.githubusercontent.com/81220083/128736322-e66a2599-5c8b-4330-89cf-78c61962de32.jpg)
![20210809185527_1](https://user-images.githubusercontent.com/81220083/128736325-6cebabf6-bbec-47a8-a356-4dbc0ecb975a.jpg)
![20210809185517_1](https://user-images.githubusercontent.com/81220083/128736328-3ab9b506-5a97-4984-8b39-e54d867e3c14.jpg)
![20210809185521_1](https://user-images.githubusercontent.com/81220083/128736331-a5f1914d-af5f-4410-b06c-526ec796efad.jpg)
only when zoomed in a lot you can read it! this was with the deafault livery!

**Comment by TLSY2** [comment]
I dont know what to do to fix it
I dont think its from my graphics problem since in other aircraft its fine.

**Comment by TLSY2** [comment]
![20210811163317_1](https://user-images.githubusercontent.com/81220083/129038349-f4640c1f-6c92-4ecf-b441-3e1cb58339d4.jpg)
![20210811163321_1](https://user-images.githubusercontent.com/81220083/129038353-2cb3a021-8de7-40ec-b365-797bd89e12c2.jpg)

it even looks blury.

**Comment by MisterChocker** [comment]
Tbh I don't really know what to expect when one zoom out that much and get this fish eye like scenario.

The other images are looking good to me, maybe a lack of antialiasing?

**Comment by MisterChocker** [comment]
> Similar for me. Looks like everything is in blur. When I zoom, I can see it clearly.
> Like it expects to be in 4K.
> 
> GTX 1070 (1920x1080), using High-end with some settings on Ultra.

Sounds to me like your render scale is lower than 80%

**Comment by TLSY2** [comment]
> > Similar for me. Looks like everything is in blur. When I zoom, I can see it clearly.
> > Like it expects to be in 4K.
> > GTX 1070 (1920x1080), using High-end with some settings on Ultra.
> 
> Sounds to me like your render scale is lower than 80%

scale 100, anti aliasing taa!

**Comment by TLSY2** [comment]
What can this be? Does anyone else have this issue?

**Comment by tracernz** [comment]
It might be at 1080p the graphics engine can only do so much unfortunately. It looks quite clear at 4k.

**Comment by MisterChocker** [comment]
> It might be at 1080p the graphics engine can only do so much unfortunately. It looks quite clear at 4k.

It does, even with 4k and render scale at 80%.

**Comment by TLSY2** [comment]
> > It might be at 1080p the graphics engine can only do so much unfortunately. It looks quite clear at 4k.
> 
> 
> 
> It does, even with 4k and render scale at 80%.
> 
> 
> 
> 

This sounds then like a sim issue. But im going to try and increase my res.

**Comment by MisterChocker** [comment]
> This sounds then like a sim issue. But im going to try and increase my res.

@TLSY2 Did you had any success doing so?

**Comment by TLSY2** [comment]
> > This sounds then like a sim issue. But im going to try and increase my res.
> 
> @TLSY2 Do you had any success doing so?

I have made a query and they passed it on to bugs...

**Comment by 2hwk** [comment]
Bloom and shader issues seem to be resolved by WU6. If this still occurs re-open the issue.

**Comment by TLSY2** [comment]
This is still a bugging issue. Nothing changes and its not just for me. 
![20210918163055_1](https://user-images.githubusercontent.com/81220083/133894227-231ae699-55e8-4f95-bc47-1f6ea6cac882.jpg)
![20210918162734_1](https://user-images.githubusercontent.com/81220083/133894228-ba0da593-2565-419e-a67e-96731154df6b.jpg)

**Comment by Benjozork** [comment]
You're never going to have a clear display even at 4K when zoomed out that far.

They are 768x768 screens. They need to be minimum 35% of your screen height to be full res.

**Comment by TLSY2** [comment]
> You're never going to have a clear display even at 4K when zoomed out that far.
> 
> They are 768x768 screens. They need to be minimum 35% of your screen height to be full res.

Then, whats the solution? Cant you make them bigger?

**Comment by Benjozork** [comment]
No, I mean, you need to zoom in more.

This is a problem of physics. You have a 768x768 screen, on a 3840x2160 monitor.

To display each pixel properly (and therefore not have blurriness or aliasing) you need the display to occupy 35% of your screen height.

We cannot break the laws of physics - we can't render at a higher resolution than your screen.

That, or you wait for 8K screens to come out.

**Comment by TLSY2** [comment]
> No, I mean, you need to zoom in more.
> 
> 
> 
> This is a problem of physics. You have a 768x768 screen, on a 3840x2160 monitor.
> 
> 
> 
> To display each pixel properly (and therefore not have blurriness or aliasing) you need the display to occupy 35% of your screen height.
> 
> 
> 
> We cannot break the laws of physics - we can't render at a higher resolution than your screen.
> 
> 
> 
> That, or you wait for 8K screens to come out.

Is this also an issue on other sims?

**Comment by Benjozork** [comment]
This is an issue of everything rendered on a screen.

Take this 1920x1080 picture with a PFD on it.

![image](https://user-images.githubusercontent.com/4503241/133909544-af09d43e-3f17-4c63-9d7b-44ffc2c55d50.png)

This looks good, right ? That's because I put the native resolution image directly on the 1920x1080 image. So it is the same resolution as it is originally.

But now look at this when the PFD is smaller.

![image](https://user-images.githubusercontent.com/4503241/133909606-9eda7788-e32f-44d7-8818-01da7c9856a8.png)

Obviously, you cannot fit the same amount of pixels as you could on a 678x786 area in a smaller square. So stuff gets blurrier and it gets low res.

**Comment by TLSY2** [comment]
> This is an issue of everything rendered on a screen.
> 
> 
> 
> Take this 1920x1080 picture with a PFD on it.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/4503241/133909544-af09d43e-3f17-4c63-9d7b-44ffc2c55d50.png)
> 
> 
> 
> This looks good, right ? That's because I put the native resolution image directly on the 1920x1080 image. So it is the same resolution as it is originally.
> 
> 
> 
> But now look at this when the PFD is smaller.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/4503241/133909606-9eda7788-e32f-44d7-8818-01da7c9856a8.png)
> 
> 
> 
> Obviously, you cannot fit the same amount of pixels as you could on a 678x786 area in a smaller square. So stuff gets blurrier and it gets low res.

That is logic.

**Comment by TLSY2** [comment]
However, is it just me or does everything in this plane seem small like the buttons, the screens... on Xplane they look bigger...

**Comment by SVitalini** [comment]
Just move your camera closer. Your viewpoint is way too far from a realistic position, imho.

**Comment by TLSY2** [comment]
> Just move your camera closer. Your viewpoint is way too far from a realistic position, imho.

Its too close, all i see is just the 2 screens...

**Comment by lukecologne** [comment]
Your seating position in your latest screenshots is wrong, you are too far back. The default position should be pretty accurate. This is how my view looks, with the default camera position. I can read the displays just fine, and I only have a 1080p monitor.
![grafik](https://user-images.githubusercontent.com/39596827/133911895-d1d031b6-27ea-49ec-8d6c-9a33505a3629.png)

**Comment by TLSY2** [comment]
> Your seating position in your latest screenshots is wrong, you are too far back. The default position should be pretty accurate. This is how my view looks, with the default camera position. I can read the displays just fine, and I only have a 1080p monitor.
> 
> ![grafik](https://user-images.githubusercontent.com/39596827/133911895-d1d031b6-27ea-49ec-8d6c-9a33505a3629.png)
> 
> 

I guess so... this is annoying.

**Comment by TLSY2** [comment]
I think the solution to this is to increase the text size. If you cant do the pixels do the text size, even at normal zoom its low res af.

**Comment by NUTTTTTTTT** [comment]
> I think the solution to this is to increase the text size. If you cant do the pixels do the text size, even at normal zoom its low res af.

That's the text size in the plane. The solution is to zoom in and look closer.

**Comment by TLSY2** [comment]
> > I think the solution to this is to increase the text size. If you cant do the pixels do the text size, even at normal zoom its low res af.
> 
> 
> 
> That's the text size in the plane. The solution is to zoom in and look closer. 

Too much zoom for flying,
