### ISSUE TITLE
Auto brake not selectable

### ISSUE THREAD

**Issue by pickels98** [flybywiresim/a32nx#5586]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-07T04:01:01+00:00",
  "ref": "master",
  "sha": "10169b43abb8568044bab599783275b34f2bca70",
  "actor": "tracernz",
  "event_name": "manual"
}
```

### Describe the bug

Auto break not selectable. 

### Expected behavior

To be able to select one of the settings.

### Steps to reproduce

1. start a flight
2. try to select max brk

### References (optional)

![auto brk](https://user-images.githubusercontent.com/56848184/128635226-8ad388ae-2fbc-4e4d-8d46-03830235cd53.jpg)

**Comment by donstim** [comment]
Your screenshot shows that you are 37,000 feet. According to your "steps to reproduce," you say to try to select the max autobrake setting. That setting is not selectable in flight, It is only selectable on the ground. (It is used for autobraking during a rejected takeoff.) You should be able to select any other autobrake setting in flight.  Please check and see if you can do this. If not, report back exactly how to reproduce this. I started an airplane in flight at 37,000 feet (as shown by your screenshot) and had no trouble selecting "MED" or "LO" autobrakes. (I also started a flight on the runway and had no trouble selecting any of the autobrake settings.)

**Comment by pickels98** [comment]
could not response for a few days.
I updated today to the last development version.( see built info) New screenshot. started cold and dark at LEIB. unable to select one of  auto brk. settings. the tree options stays illumnated. I cannot click on one of these.

{
  "built": "2021-08-14T06:41:53+00:00",
  "ref": "master",
  "sha": "a67f7ac36d9805949846f1531c14c16453e29ae3",
  "actor": "aguther",
  "event_name": "manual"
}

![afbeelding_2021-08-14_103242](https://user-images.githubusercontent.com/56848184/129440128-23a26652-c22e-481f-bf19-13b21b9ecf9b.png)
