### ISSUE TITLE
Ingame throttle going to reverse position instead of 0 when setting IRL to minimum

### ISSUE THREAD

**Issue by cursorzero** [flybywiresim/a32nx#5588]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-07T04:01:01+00:00",
  "ref": "master",
  "sha": "10169b43abb8568044bab599783275b34f2bca70",
  "actor": "tracernz",
  "event_name": "manual"
}
```

### Describe the bug

It only happens with the Dev. version.
When you set your IRL throttle to minimum it goes on reverse thrust instead of going to 0/Idle.

### Expected behavior

Minimum throttle should go to 0/Idle position instead of Reverse.

### Steps to reproduce

1. Load in game.
2. Set your throttle to minimum.

### Additional info (optional)

I tried with the experimental version and it works in that version

**Comment by 2hwk** [comment]
Have you calibrated your throttles using the flyPad EFB?

![image](https://user-images.githubusercontent.com/15316958/128638660-79d4d644-7a60-487c-a2a1-d67f3d1f8ef7.png)

**Comment by cursorzero** [comment]
Yep, that did it, thank you !
