### ISSUE TITLE
PFD Display not correct on takeoff [BUG]

### ISSUE THREAD

**Issue by Ares1378** [flybywiresim/a32nx#559]
**Mod Version**
<Latest version>

**Describe the bug**
<the runway center line indicator should be displayed underneath the Side stick cross hair for lateral guidance. This indicator uses the runways localizer to obtain this information. If the runway does not have a localizer,  neither the RWY FMA nor the runway center line will be displayed on the PFD. Once the thrust levers have been moved to either the FLX or TOGO thrust, the SRS vertical bars will appear for vertical guidance. Once the aircraft leaves the ground the side stick indicator will disappear and the RWY TRACK indicator will disappear. The RWY FMA will change to either NAV( if armed) or RWY TRACK if HDG/TRK is pre-selected at 30ft RA.

**References**
< Use this for reference: https://www.youtube.com/watch?v=ECV3IBkzZLc or message Ares on discord.>

**Comment by tareksabet** [comment]
@Ares1378 I think it was fixed can you confirm

**Comment by MisterChocker** [comment]
using #1145 for tracking
