### ISSUE TITLE
"Retard" Callout Not Happening After 20 Feet

### ISSUE THREAD

**Issue by CookieMonsta85** [flybywiresim/a32nx#5594]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-08T15:20:59+00:00",
  "ref": "master",
  "sha": "3d6a19f58a509da73f3dc47be05ef05966a78ce7",
  "actor": "sidnov",
  "event_name": "manual"
}
```

### Describe the bug

Retard callout is now occurring after 10 feet when landing. It should be at or after 20 feet.

### Expected behavior

Retard callout should happen right after the 20 feet callout.

### Steps to reproduce

Everytime when on final approach and about to land, the "retard" callout occurs after 10 feet.

**Comment by 2hwk** [comment]
Repeat of https://github.com/flybywiresim/a32nx/issues/5527 closing
