### ISSUE TITLE
Aircraft levels off in climb and overspeeds in manged speed and Open Climb [BUG]

### ISSUE THREAD

**Issue by Ares1378** [flybywiresim/a32nx#560]
**Mod Version**
<Latest>

**Describe the bug**
Aircraft will randomly level off in climb in either CLB or OP CLB modes, and when in manged speed the A/THR will not stop the aircraft from accelerating past the managed buged speed. You have to pull speed to stop accelerating so you do not overspeed and kick off the AP and climb manually to your desired altitude. It has always happened climbing above 10k and the transition from 250kts to 320kts managed speed.

**Comment by MisterChocker** [comment]
this has been fixed
