### ISSUE TITLE
Low Exterior light execept Logo light

### ISSUE THREAD

**Issue by DomWin02** [flybywiresim/a32nx#5603]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-09T04:50:23+00:00",
  "ref": "master",
  "sha": "42e4134f9235ff0a1842edc10aad7c56a52b7989",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

Exterior lights are very low illuminated (except logo and landinglights), F.e. Strobe light is nearly not visible

### Expected behavior

Low exterior lightning

### Steps to reproduce

1. turn on the lights :-)

### Discord Username (optional)

DomenicHAJ#0457

**Comment by KeepGamingLP** [comment]
I can confirm this.

**Comment by MisterChocker** [comment]
For strobe lights see https://github.com/flybywiresim/a32nx/issues/5585
