### ISSUE TITLE
get rid of fake efb loading screen

### ISSUE THREAD

**Issue by ErickSharp** [flybywiresim/a32nx#5604]
### Aircraft Version

Development

### Description

We should get rid of the fake efb loading screen. #getRidOfFakeLoadingScreen

**Comment by Benjozork** [comment]
The flyPad is meant to emulate a real tablet. Therefore the loading screen should be kept.

**Comment by ErickSharp** [comment]
> The flyPad is meant to emulate a real tablet. Therefore the loading screen should be kept.

Currently, there is no different 'Power Down' and 'Turn Off' option. It makes sense to have a fake loading screen after coming out of a powered down state, but if you are just turning the tablet back on, it makes no sense.

**Comment by MisterChocker** [comment]
I see both sides, using modern Tablets you only have a "loading" screen when you start up the device, but not when the device is already running but the display only got turned off. 

So turning the display on off should not behave like on start up.

**Comment by bouveng** [comment]
It could also be done using a simple css-animation instead of this heavy js component.

**Comment by glowfishDE** [comment]
The loading screen makes sense and its legit to be there. The EFB wouldnt be left powered on between flights and most likely it would drain its battery if the "bus" is not used very often. So as a pilot i would turn it off after a flight. And when i turn it on its good for realism and immersion to have that loading screen. Just my 2 cents.

btw: how can i turn the efb off or reset it? Is that possible in case it needs a reboot ?

**Comment by sidnov** [comment]
> btw: how can i turn the efb off or reset it? Is that possible in case it needs a reboot ?

Click the battery icon on the top right to turn off the EFB

**Comment by glowfishDE** [comment]
> > btw: how can i turn the efb off or reset it? Is that possible in case it needs a reboot ?
> 
> Click the battery icon on the top right to turn off the EFB

So cool! Thank you :)

**Comment by ErickSharp** [comment]
The logic in flypados 3 will improve upon this issue. There will be a standby and powered off state. Only when going from powered off to loaded will this animation show itself.
