### ISSUE TITLE
0.6.3 did not fix CTD when loading into the world

### ISSUE THREAD

**Issue by kilocharlie1** [flybywiresim/a32nx#5608]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-08-09T18:57:24+00:00",
  "ref": "v0.6.3",
  "sha": "7222a9516e4114742a7fec84080a2f63ea527428",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

The sim still crashes to desktop when loading into the world. This has never happened before 0.6.2

### Expected behavior

The sim runs smoothly and does not CTD

### Steps to reproduce

1. Create a flight from George Bush Intercontinental to Charlotte Intl. 
2. Load into the world

### Additional info (optional)

This has never happened to me before patch 0.6.2 on the online version of the mod, and it doesn't happen with any other plane

**Comment by NUTTTTTTTT** [comment]
Have you tried the steps listed below and are you able to load into different airports? 

Crash To Desktop - Resolution Steps
https://docs.flybywiresim.com/start/reported-issues/#ctd-resolution

**Comment by kilocharlie1** [comment]
It turns out it was just the livery I was using that was causing the problem

**Comment by NUTTTTTTTT** [comment]
Glad you were able to find the cause of the issues, I'd recommend making sure anything in your community folder is up to date and compatible with recent changes/sim updates. If you have any issues, it's always best to check by clearing your community folder first as add-ons can often be the cause. 👍
