### ISSUE TITLE
Primary flight displays turn off when external power is disconnected

### ISSUE THREAD

**Issue by kilocharlie1** [flybywiresim/a32nx#5609]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-08-09T18:57:24+00:00",
  "ref": "v0.6.3",
  "sha": "7222a9516e4114742a7fec84080a2f63ea527428",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

The primary flight displays turn off when external power is disconnected, even when the APU is running and available

### Expected behavior

The flight instruments stay on because the APU is providing AC power

### Steps to reproduce

1. Spawn at a gate of your choosing at any airport
2. Start the APU, make sure it is on and AVAIL is lit
3. Disconnect external power

### References (optional)

![20210810103110_1](https://user-images.githubusercontent.com/88682168/128886697-2565bcf9-b6c8-4619-bf2e-c38086c40030.jpg)

### Additional info (optional)

This was working before 0.6.2

**Comment by davidwalschots** [comment]
What's the status of the ELEC overhead panel?

**Comment by colibriz** [comment]
Yeah same happens to me with stable version

**Comment by MisterChocker** [comment]
Please provide a screenshot of the ELEC panel while the issue is present.

**Comment by MisterChocker** [comment]
Closing since no response from the OP.

**Comment by Nufflee** [comment]
I can reproduce this bug as well. This is the status of the overhead panels before turning off the external power:
![image](https://user-images.githubusercontent.com/19150550/131260859-2512c4dd-63ef-40e2-960b-3693bb9ee2d1.png)

And here you can see that the APU is available:
![image](https://user-images.githubusercontent.com/19150550/131260950-441601db-1105-4e98-9dd2-33fac0e42471.png)

But when the external power is turned off, all displays turn off as well even though the APU is running.

**Comment by lukecologne** [comment]
Your APU generator is turned off (see the overhead panel). The APU page should also say "OFF" in the APU GEN section, looks like this is either a bug or not implemented.

**Comment by MisterChocker** [comment]
Either way the stable has neither the new apu model nor elec system implemented which do exist and work in the development version.
