### ISSUE TITLE
Wrong Approach is displayed on ND durring approach.[BUG]

### ISSUE THREAD

**Issue by Ares1378** [flybywiresim/a32nx#561]
**Mod Version**
<Latest>

**Describe the bug**
<Coming in on the LAWGER1 arrival into KDEN, the ILS 34R was programed into the MCDU, once the LS pb was pressed the ND displayed the ILS for 16L. I checked the MCDU RAD nav page to double check what was displayed and it was correct for 34R. Also it should be displayed in Green for the approach on the ND not magenta. >

![wrong approach  and loc displayed on ND and PFD](https://user-images.githubusercontent.com/70821584/92669354-e957f400-f2d6-11ea-98f6-53da9d4e18d6.png)

**Comment by PCGamesF1Tech** [comment]
The color on top of ND is also wrong:
Should be green, is magenta (see #221)

**Comment by PCGamesF1Tech** [comment]
See also #221

**Comment by kielyscott** [comment]
Confirmed, happened to me at Charlotte Douglas. 05L and 05C confused.

**Comment by tareksabet** [comment]
fixed in pr #1672 also check  it if it worked
