### ISSUE TITLE
FlyPad battery life

### ISSUE THREAD

**Issue by kilocharlie1** [flybywiresim/a32nx#5615]
### Aircraft Version

Stable

### Description

If you look up at the top right corner of the Flypad, you see the battery meter and how it is always charging. I think it should be that while AC power isn't being supplied to the plane (Both APU and exterior power are off) the flypad doesn't charge and the battery starts to drain, like how the flight instruments aren't powered.

### Additional info (optional)

Similar to how the flight instruments are not powered when neither the APU or EXT PWR is avail, the same should be for the FlyPad's charging supply.

**Comment by davidwalschots** [comment]
For anyone picking this up in the future: the captain EFB powered by DC BUS 2, the F/O EFB is powered by DC ESS SHED.

**Comment by Benjozork** [comment]
Would be cool to have USB ports in the new model (present in newer airbuses) with a cable plugging animation.

I assume those are powered by the busses David mentions.

**Comment by davidwalschots** [comment]
Yep!

**Comment by kiemdoder** [comment]
I'd like to implement this feature.

**Comment by kiemdoder** [comment]
@davidwalschots  mentioned that the F/O EFB is powered by DC ESS SHED. Are there plans to have an EFB for the F/O as well?

**Comment by tracernz** [comment]
> 
> 
> @davidwalschots mentioned that the F/O EFB is powered by DC ESS SHED. Are there plans to have an EFB for the F/O as well?

No immediate plans. The tablet holder is only in the cockpit mesh on the captain's side in the Asobo 3D model.

**Comment by fvdnabee** [comment]
@kiemdoder did you start on this? If not, I could look at picking it up.

**Comment by kiemdoder** [comment]
Hi @fvdnabee. I did start on it and have something that I think is worth including but @Benjozork said I should wait until the EFB battery is modeled in the electrical system. Please send me a message on discord if you would like to discuss it further.

**Comment by davidwalschots** [comment]
FYI @ErickSharp once there's an EFBv3 PR, it should link this issue as fixed.

**Comment by ErickSharp** [comment]
> FYI @ErickSharp once there's an EFBv3 PR, it should link this issue as fixed.

So we prefer including the fix in the feature PR going into the main feature branch than including the “Fixes #XXXX” in the flypadosv3 PR in the future?

**Comment by davidwalschots** [comment]
> So we prefer including the fix in the feature PR going into the main feature branch than including the “Fixes #XXXX” in the flypadosv3 PR in the future?

I'm not sure. I think the expectation would be that it is fixed in the development version. However, that won't be the case yet.

**Comment by ErickSharp** [comment]
> > So we prefer including the fix in the feature PR going into the main feature branch than including the “Fixes #XXXX” in the flypadosv3 PR in the future?
> 
> I'm not sure. I think the expectation would be that it is fixed in the development version. However, that won't be the case yet.

Oh yes sorry I read your message wrong. In the description of the OSV3 PR it will feature a compilation of the issues we can comfortably close 😃
