### ISSUE TITLE
Flight physiks of asobo are more realistic

### ISSUE THREAD

**Issue by DomWin02** [flybywiresim/a32nx#5619]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-11T07:29:20+00:00",
  "ref": "master",
  "sha": "1c5335ec13ec6b7d29319db3371299da5e4fb880",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

The flight physics of default Asobo A320 are more realstic, if you Could implement the physics of default with the rest of the FBW A320  it will be perfect. At the moment it is nearly not possible to land the ACFT safely and realistic.

### Expected behavior

/

### Steps to reproduce

1.  Fly with it

### Discord Username (optional)

DomenicHAJ#0457

**Comment by DomWin02** [comment]
#

> What is the basis of your statement? Please elaborate how the default is better than the A32NX in terms of flights "physiks" which has been entirely remodeled using complex platforms such as Simulink.

At the moment with the flight physics at this point, it is nearly  unpossible to land the A32NX safely and realistic. So if only the physics of Asobos A320neo is implemented in A32NX and the rest from FBW it will  be perfect

**Comment by sidnov** [comment]
> At the moment with the flight physics at this point, it is nearly unpossible to land the A32NX safely and realistic. So if only the physics of Asobos A320neo is implemented in A32NX and the rest from FBW it will be perfect

I would suggest going over some tutorials in that case, that teach how to land properly

**Comment by DomWin02** [comment]
> > At the moment with the flight physics at this point, it is nearly unpossible to land the A32NX safely and realistic. So if only the physics of Asobos A320neo is implemented in A32NX and the rest from FBW it will be perfect
> 
> I would suggest going over some tutorials in that case, that teach how to land properly

Sry? I am using P3D and X-Plane 11 for years an flying FSLabs A320, and this is the most realstic Airbus DLC for Flightsims ever and is used for oilotseducation... and Asobos fkight dynamic is closer to FSLabs than FBW

**Comment by sidnov** [comment]
> > > At the moment with the flight physics at this point, it is nearly unpossible to land the A32NX safely and realistic. So if only the physics of Asobos A320neo is implemented in A32NX and the rest from FBW it will be perfect
> > 
> > 
> > I would suggest going over some tutorials in that case, that teach how to land properly
> 
> Sry? I am using P3D and X-Plane 11 for years an flying FSLabs A320, and this is the most realstic Airbus DLC for Flightsims ever and is used for oilotseducation... and Asobos fkight dynamic is closer to FSLabs than FBW

We rely on actual documentation and feedback from IRL pilots and engineers, and not some other XYZ addons which claim to be "realistic". If you have issues calibrating your setup according to the MSFS settings, feel free to drop a message in the support channel of our Discord.

**Comment by hotshotp** [comment]
Our pilots and engineers say our aircraft is amazing to hand fly and feels a lot like the real thing. The asobo flight characteristics are in no way more realistic than our new implementation. For the autopilot to work smoothly, it is required to have 17 fps steadily. I'm guessing your issue is that you are getting less than that and the autopilot doesn't behave right. In that case turn down your graphics settings.

**Comment by DomWin02** [comment]
> Our pilots and engineers say our aircraft is amazing to hand fly and feels a lot like the real thing. The asobo flight characteristics are in no way more realistic than our new implementation. For the autopilot to work smoothly, it is required to have 17 fps steadily. I'm guessing your issue is that you are getting less than that and the autopilot doesn't behave right. In that case turn down your graphics settings.

I only have problems in landing, there it is very unstable, i will provide a video of my landing in about 1 hour on Discord server in the support channel

**Comment by DomWin02** [comment]
> > > Our pilots and engineers say our aircraft is amazing to hand fly and feels a lot like the real thing. The asobo flight characteristics are in no way more realistic than our new implementation. For the autopilot to work smoothly, it is required to have 17 fps steadily. I'm guessing your issue is that you are getting less than that and the autopilot doesn't behave right. In that case turn down your graphics settings.
> > 
> > 
> > I only have problems in landing, there it is very unstable, i will provide a video of my landing in about 1 hour on Discord server in the support channel
> 
> Please do. This will help us fix your issue.

It is in the support channel, Here is the link to: https://www.dropbox.com/sh/73o73qgv789jwe4/AAAr4FUhIOkisv9z-fMwTaX8a?dl=0  Also there is an txt from me. Pls read it before watching the video. Thx

**Comment by ZigTag** [comment]
You are using way too much input when trying to land the plane, it requires a lot of finesse to be able to land properly. It also seems like when you are pulling back you are then letting go of the joystick to let it recenter. Not only will that destroy your joystick, but it is also very rough and shouldn't be done while landing.

**Comment by DomWin02** [comment]
> You are using way too much input when trying to land the plane, it requires a lot of finesse to be able to land properly. It also seems like when you are pulling back you are then letting go of the joystick to let it recenter. Not only will that destroy your joystick, but it is also very rough and shouldn't be done while landing.

I swaer, I moved my stick about 2-5mm in real...

**Comment by aguther** [comment]
Well, there can be a lot of discussion around that topic. Some time ago one pilot said the nose-down effect is even not strong enough others say it‘s fine. I think it‘s also depending on the hardware.

How does the sensitivity curve of your joystick look like?

**Comment by DomWin02** [comment]
> Well, there can be a lot of discussion around that topic. Some time ago one pilot said the nose-down effect is even not strong enough others say it‘s fine. I think it‘s also depending on the hardware.
> 
> How does the sensitivity curve of your joystick in MSFS look like?

![20210812104344_1](https://user-images.githubusercontent.com/88674959/129167023-ff5dee8e-2079-41dc-a06a-f39973740d01.jpg)
I will now try it with these setting, therefore iot was on normal so +/-0

**Comment by aguther** [comment]
It might interest you:
https://github.com/flybywiresim/a32nx/pull/5711
