### ISSUE TITLE
On Subsequent flights aircraft will not cycle to the CLB phase [BUG]

### ISSUE THREAD

**Issue by DABUS320** [flybywiresim/a32nx#562]
**Mod Version**

Latest

**Describe the bug**

If you do 2 consecutive flights, on the second flight -  the aircraft is stuck in the takeoff phase.

**To Reproduce**

1.Fly to an airport land, and take off to another airport in the same session.

**Expected behavior**

It should not be stuck in the takeoff phase.

**Actual behavior**

**References**

**Additional context**

**Comment by UncleClapton** [comment]
Was able to replicate multiple times. seems the phase reset logic isn't quite right

**Comment by rodrifo6** [comment]
I had this problem many times. I get stuck with the T.O. INHIBIT message and the A/P will not follow the LNAV route.
