### ISSUE TITLE
Landing Lights Toggle Button

### ISSUE THREAD

**Issue by jpccaldas** [flybywiresim/a32nx#5621]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-11T07:29:20+00:00",
  "ref": "master",
  "sha": "1c5335ec13ec6b7d29319db3371299da5e4fb880",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

On earlier releases the Landing Lights toggle button used to move the overhead Landing Lights and TO light from Retract and Off to On and TO (respectively), but now it switches between On and Off, and TO and Taxi (respectively).

### Expected behavior

Would like to act as earlier, from Retract to On and from Off to TO and vice versa.

### Steps to reproduce

1. Click Landing Lights assigned button.

### Discord Username (optional)

jpccaldas#8164

**Comment by derl30n** [comment]
Resolved
