### ISSUE TITLE
Font Style in the MCDU.

### ISSUE THREAD

**Issue by what042306** [flybywiresim/a32nx#5622]
### Aircraft Version

Stable

### Description

This is not a very big problem but personally, I think would make the MCDU even more realistic than it already is. The font style in the MCDU is not accurate, it just seems to be a little bit off.

### References (optional)

![image_2021-08-11_163657](https://user-images.githubusercontent.com/64486859/129106808-6598509f-d7a9-4e16-b23d-372e59b18857.png)
![image_2021-08-11_163801](https://user-images.githubusercontent.com/64486859/129106909-3c4ed78d-719f-4e49-886b-5a3ec77a1a7f.png)

### Additional info (optional)

First picture is FBW MCDU, second picture is the real deal.

### Discord Username (optional)

What?#6635

**Comment by Benjozork** [comment]
Your irl reference is a Thales MCDU.

The A32NX has a Honeywell MCDU.

**Comment by beheh** [comment]
@what042306 For comparison: Here's a video with a Honeywell MCDU (which we model)

https://www.youtube.com/watch?v=D7HjVlvKd8o
