### ISSUE TITLE
Brakes are too sensitive

### ISSUE THREAD

**Issue by MartinLM96** [flybywiresim/a32nx#5629]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-12T18:29:03+00:00",
  "ref": "master",
  "sha": "2d7733ba4fe63fe269dcef555cbca3d34b98118a",
  "actor": "bouveng",
  "event_name": "manual"
}
```

### Describe the bug

I'm using the Thrustmaster TFRP T.Flight Rudder Pedals, and ever since the brakes was last changed I find them to be way too sensitive. 

Before I was able to ride the brakes when taxing to keep a certain speed, but now I get almost full brakes and the plane comes to a complete stop whenever I try to that, just pressing the brakes very lightly. Have discussed this in the discord and multiple users are reporting taxing and parking to be tricky after the brakes was last changed. 

### Expected behavior

Brakes should be more progressive. The harder you press, the harder braking you get. Now, pressing the brakes very lightly gives around 60-70% braking, and pressing them a little bit harder gives instantly 100% braking and the plane comes to a stop.

### Steps to reproduce

Accelerate to taxi speed and try maintaining speed by the riding brakes.

### Discord Username (optional)

Martin M#5250

**Comment by vdaal-asml** [comment]
Seems related to https://github.com/flybywiresim/a32nx/issues/5627

**Comment by vvdaal** [comment]
Seems related to https://github.com/flybywiresim/a32nx/issues/5627#issuecomment-897866327

**Comment by MartinLM96** [comment]
It's as if the plane doesn't recognize first 50% of the brake input on the rudder pedals. This problem doesn't occour with the default A320.

**Comment by crocket63** [comment]
You are using analogue axis right?  Are you able to slighly move the pedals so that pedals in the cockpit just slightly move too?
I can definitly apply a super small amount of brakes using an analogue input so I'd more suspect an input controller issue here?

**Comment by tracernz** [comment]
> 
> 
> You are using analogue axis? Are you able to slighly move the pedals so that pedals in the cockpit just slightly move too?
> I can definitly apply a super small amount of brakes using an analogue input so I'd more suspect an input controller issue here.

I have the Thrustmaster pedals and they also work okay for small amounts of braking. Seems to be something going on with controller axis settings maybe MartinLM96?

What do you see in here when you apply a small amount of braking? What does it do through the range? Mine proceeds smoothly from left to right.
![image](https://user-images.githubusercontent.com/9995998/131203998-392ab1ac-1a8e-45d8-babc-a8b19277f403.png)

**Comment by MartinLM96** [comment]
> > You are using analogue axis? Are you able to slighly move the pedals so that pedals in the cockpit just slightly move too?
> > I can definitly apply a super small amount of brakes using an analogue input so I'd more suspect an input controller issue here.
> 
> I have the Thrustmaster pedals and they also work okay for small amounts of braking. Seems to be something going on with controller axis settings maybe MartinLM96?
> 
> What do you see in here when you apply a small amount of braking? What does it do through the range? Mine proceeds smoothly from left to right.
> ![image](https://user-images.githubusercontent.com/9995998/131203998-392ab1ac-1a8e-45d8-babc-a8b19277f403.png)

No mine activate at 50% input on the pedals. Weird.. Any idea how I can fix this?

**Comment by tracernz** [comment]
Check L axis X and Y in the sensitivity settings (upper left of the config screen) and make sure they’re linear etc. Also check you have bound L axis X rather than L axis X+ or X-.

**Comment by MartinLM96** [comment]
My settings are identical to yours but for some reason the brakes activate right as I pass 50% brake input. Very weird.

**Comment by MartinLM96** [comment]
I fixed it, turns out at some point I must have tried calibrating the brakes using the default windows joy.cpl method - Does not work. It centers the brakes at 50%. Reset this setting and they work as expected again. Not related to the FBW, sorry! And also thanks for looking into it.

**Comment by tracernz** [comment]
> 
> 
> I fixed it, turns out at some point I must have tried calibrating the brakes using the default windows joy.cpl method - Does not work. It centers the brakes at 50%. Reset this setting and they work as expected again. Not related to the FBW, sorry! And also thanks for looking into it.

Thanks for following up. This is another one we can add to our support knowledge. 😄
