### ISSUE TITLE
autopilot and light switches not working properly

### ISSUE THREAD

**Issue by Maverick0482** [flybywiresim/a32nx#5631]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-08-09T18:57:24+00:00",
  "ref": "v0.6.3",
  "sha": "7222a9516e4114742a7fec84080a2f63ea527428",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

Some of the light switches on the overhead panel don't work. The only ones that do work is the strobe light, logo light and the runway/taxi light switches. However, all the lights turn on if you press L on the keyboard to turn on all the lights but the switches don't show them on. 

The autopilot buttons don't work neither. The speed, altitude and VS buttons don't work. And the speed doesn't adjust on the main display according to what the autopilot is set to. For example, if you set the speed to 330KT, the marker on the main display doesn't show it.

The tablet is glitchy too. Sometimes it turns on and sometimes it doesn't.

Even with everything updated, the sim does still crash to the desktop when loading but if you restart the sim, it works. 

### Expected behavior

When setting the autopilot V/S, it doesn't turn on nor adjust accordingly. Some of the light switches don't turn on but the lights will turn on when you turn them all on together pressing L on the keyboard. The autopilot speed doesn't adjust accordingly. 

### Steps to reproduce

Try to turn on the light switches from the overhead panel. 
Press the knob on the autopilot for the speed, altitude and V/S. 

### Additional info (optional)

The problem didn't start until the Sim Update 5.

**Comment by tracernz** [comment]
Try with no liveries installed. Failing that jump onto the #support channel on Discord.

**Comment by CapJambo** [comment]
Make sure you didn't install a second copy of a32nx. 
If you do not have it for install in-game, it means you have 2 copies installed.
Check inside the official forder for it. If you find it delete.
Cheers

**Comment by Maverick0482** [comment]
It did have 2 copies installed so I deleted the official folder one and it fixed some of the issues but the autopilot is still not working right. It flys the course when the autopilot is on but the V/S and speed buttons still don't work right and it doesn't mark the speed or the V/S that the autopilot is set to on the main display.

**Comment by CapJambo** [comment]
> 
> 
> It did have 2 copies installed so I deleted the official folder one and it fixed some of the issues but the autopilot is still not working right. It flys the course when the autopilot is on but the V/S and speed buttons still don't work right and it doesn't mark the speed or the V/S that the autopilot is set to on the main display.

I would recommend  you make a reinstall. Delete Fly-by-wire from Community and from App Data. See if it works.

Cheers

**Comment by MissiR50** [comment]
Same problem. After deleting copies, the light began to work. Autopilot is not working (V/S).

[Google translator]

**Comment by t90125** [comment]
Same here: some light switches and autopilot didn't work. I did a clean install, and the light switches began to work, but not autopilot. Also can't push or pull speed and altitude autopilot knobs, only rotate. The little arrows to push/pull don't appear when hovering the mouse cursor on the edge of the knobs as they did before.

**Comment by aguther** [comment]
Do you use the old or new interaction system?

**Comment by t90125** [comment]
> Do you use the old or new interaction system?

I think you solved it for me, many thanks! I changed the "cockpit interaction system" to "Legacy", and at least now I'm able to push/pull the autopilot controls again!

**Comment by MisterChocker** [comment]
Closing since issue resolved.
