### ISSUE TITLE
Rudder pedals don´t work like in the vanilla planes

### ISSUE THREAD

**Issue by NiklasWGC** [flybywiresim/a32nx#5633]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-11T07:29:20+00:00",
  "ref": "master",
  "sha": "1c5335ec13ec6b7d29319db3371299da5e4fb880",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

I use my racing pedals as rudder pedals.In MSFS there are setting to set the left rudder on the one pedal and the right rudder on another.In the vanilla planes it works fine and I can use the pedals as rudders.The FBW makes problems with that.He registers only one pedal at once and its registered as a rudder axis on a joystick.I don´t know how I can fix it and espescially why it only doesn´t work with the FBW.

### Expected behavior

I hope it will be fixed so that also Racing pedals user can use their pedals as rudders without any software.Maybe I made a mistake and I hope you can help me to fix the problem.

### Steps to reproduce

1.I set the bindings to the pedals
2.I tested it in the FBW and it doesnßt work.
3.I tested it with a few vanilla planes and it works.
4.I tested it again with thee FBW and it doesn´t work again.

### References (optional)

#
![1](https://user-images.githubusercontent.com/57032532/129319695-4dd3e707-1e69-4679-956f-69c7ca88bdad.PNG)
[](url)     That are my settings.

https://youtu.be/0fhp1Tv4Xw8   Here is a link to my video which describes my problem?The is the difference between the vanilla a320 and the FBW.

### Additional info (optional)

I got the issue yesterday beacause I have tested it yesterday.

### Discord Username (optional)

Niklas#1780

**Comment by aguther** [comment]
I've created a PR that fixes the issues you showed. It's important though to test this with an XBOX controller because in the past it was tuned for usage with this. The feedback at that time was then that it's working fine. So the question is now if this PR will break XBOX controller or not before it gets merged.

**Comment by NiklasWGC** [comment]
Ok,thanks for the fast answer.I hope it will work then.It would be nice if you can send me a message in which update it will be.
By the way: Can you tell me what PR stands for?

**Comment by aguther** [comment]
You can see it yourself, the the pull request (PR) says "Merged" it's in the source code of the mainline = development version. After this is done it takes around 30 minutes until a build of that version is available and can be downloaded via installer. The PR is linked to the issue if you go up a bit.

![image](https://user-images.githubusercontent.com/6629914/129376271-5947000f-0e94-4fae-a422-edd12d0c9b28.png)

**Comment by aguther** [comment]
You can test the build if you want:
https://github.com/flybywiresim/a32nx/suites/3493702647/artifacts/83196367

**Comment by NiklasWGC** [comment]
ok,I downloaded it now,I will test it in a hour and will give you a feedback if it works.thank you

**Comment by aguther** [comment]
Ok, I have some feedback from one of our testers ne it turns out that my memory wasn't wrong. The event handling as it was right now works for XBOX controllers.

That means fixing your issue will cause XBOX controllers to stop working.

What I can do is to add an option that needs to be put in a config file to disable the XBOX compatibility and to use the processing as proposed in the linked PR.

**Comment by aguther** [comment]
@NiklasWGC Its now planned that there will be an option that you can turn off the XBOX compatibility by putting the file `ModelConfiguration.ini` with the following content into the work folder:
```
[flight_controls]
disable_xbox_compatibility_rudder_axis_plus_minus = true
```

**Comment by NiklasWGC** [comment]
Ok thank you,where do I find this folder?

**Comment by aguther** [comment]
Reminder: this will be there when it’s merged.

Search for „Work folder location“ here:
https://docs.flybywiresim.com/start/autopilot-fbw/

**Comment by NiklasWGC** [comment]
Thanks,i tried it out and I found the folder but i doesn´t work.The problem is there yet.

**Comment by NiklasWGC** [comment]
Is it possible to show you that on Discord?

**Comment by aguther** [comment]
Well as I said, I coded it but it’s not yet merged. You don’t have that change yet.

**Comment by aguther** [comment]
Did you try the build I’ve linked? You didn’t give feedback yet on that build as promised.

**Comment by NiklasWGC** [comment]
No,I downloaded it from the installer.I think I misunderstand something.My English is not so good because I´m from Germany.I´m downloading it now.

**Comment by aguther** [comment]
Ok no problem.

**Comment by NiklasWGC** [comment]
Ok I installed the FBW from your link and the problem is still there.Maybe I did something wrong but I don´t know what.I deleted the old version and put your version into the folder and I added the ini into the work folder.

**Comment by aguther** [comment]
Have you tried to reverse both axes?

I tested it my self with my rudder pedals by using the two brake axes instead of the rudder axis and it worked as it should be for me. But in my case the axes are reversed.

**Comment by NiklasWGC** [comment]
I will try it in a second and give you a feedback.

**Comment by NiklasWGC** [comment]
Yes it works with the FBW.But I had first set the extremity dead zone to 50%.I have to turn it to 0% for the FBW.But if i let it so I have the problem with the vanilla planes that the pedal is fully pressed in MSFS but only 50% in real life.

**Comment by aguther** [comment]
Well the Xbox controller also put the axis to 50% when neutral. When the PR is merged you have the choice: either use it like Xbox controller then the axis should be in the middle when pedals are not pressed or you have the full range but then it needs to be 0 when pedals not pressed.

I hope you understand that I will not add a further calibration for the rudder. The sensitivity settings of MSFS should be enough to get it work in one of the two cases.

**Comment by NiklasWGC** [comment]
Ok,it is ok if I change the setting when I change from the FBW to a vanilla plane.Thank you for the help.

**Comment by aguther** [comment]
Ok, the issue will close with the PR being merged.

**Comment by NiklasWGC** [comment]
Ok,then I can download it normally from the installer right?
