### ISSUE TITLE
EFB: Dashboard Always Shows QNH in hPa

### ISSUE THREAD

**Issue by Peter-Mary-Jo** [flybywiresim/a32nx#5634]
### Aircraft Version

Development

### Description

EFB units: Using inHg instead of Hpa --> this would be a convenient improvement for those flying over US

~~EFB Font colors: for the OFP and the EFB map, possibility to have black Font on a white page.~~ (#4601)

**Comment by 2hwk** [comment]
The first is already implemented. Not sure about the second.

**Comment by Peter-Mary-Jo** [comment]
You are right it's possible to choose between Hpa and inHg in the EFP parameter page but it seems that this setting has no effect on the weather indication for origine and destination airport: QNH is indicated in Hpa even if the Metar which is printed on board use inHg

**Comment by tracernz** [comment]
> 
> 
> You are right it's possible to choose between Hpa and inHg in the EFP parameter page but it seems that this setting has no effect on the weather indication for origine and destination airport: QNH is indicated in Hpa even if the Metar which is printed on board use inHg

It depends which METAR source you select. The text comes through raw from the source. If you select MSFS for example you will get right now:
`KLAX 131253Z VRB03KT 10SM FEW008 19/16 A3002 RMK AO2 SLP163 T01890156` = 30.02 in.Hg.

**Comment by ErickSharp** [comment]
Addressed in #6373
