### ISSUE TITLE
[BUG] Auto-brakes shouldn't disarm when using the manual (foot) brakes

### ISSUE THREAD

**Issue by Venorcis** [flybywiresim/a32nx#564]
**Mod Version**
master

**Describe the bug**
On the runway, having the auto-brakes armed and set, you should be able to use the foot brakes without disconnecting the auto-brakes.

**To Reproduce**
See https://youtu.be/Zsk72luNZvc?t=988

**Expected behavior**
Auto-brakes should stay armed when using the footbrakes.

**Actual behavior**
Auto-brakes automatically disarm when using the footbrakes.

**Comment by PCGamesF1Tech** [comment]
See #255

**Comment by Venorcis** [comment]
> See #255

Ah, thanks, I'll close this as a duplicate then.
