### ISSUE TITLE
PFD decent dot

### ISSUE THREAD

**Issue by DomWin02** [flybywiresim/a32nx#5642]
### Aircraft Version

Development

### Description

A magenta decent dot at left ahnd side of Altitute band which indicates if you are on glide path or to high or to low on decent

### References (optional)

https://lh3.googleusercontent.com/proxy/r15ZKh05u_s4QRRxjQw5GlDk77D2yW8vEoWhhyvKsIWlPo302bCZ0gN6en22zLmxh-DBOTPW4tM8mc3E-YoG6DZ9P13vrCLjSaSwjNBhlxw5JFnvtJ5Qx_-BAuVFHUpao39KSwjCKyc

### Discord Username (optional)

DomenicHAJ#0457

**Comment by lukecologne** [comment]
Will be added with VNAV. BTW, in more modern A320, the dot is green instead of magenta
