### ISSUE TITLE
Sync beacon and strobe light

### ISSUE THREAD

**Issue by DomWin02** [flybywiresim/a32nx#5643]
### Aircraft Version

Development

### Description

Becon light is blinking between the intervall of the strobe lights in real. At the moment not

### References (optional)

https://www.youtube.com/watch?v=apiD-YMJnoY

At 2:20 on the right side

### Discord Username (optional)

DomenicHAJ#0457

**Comment by tracernz** [comment]
@Inaxair @bouveng has already done this over the last couple of weeks, but is just finalising some details I beleive.
