### ISSUE TITLE
Fuel Capacity from SIMBRIEF to LOW

### ISSUE THREAD

**Issue by FGrabi** [flybywiresim/a32nx#5646]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-13T16:43:15+00:00",
  "ref": "master",
  "sha": "18573fcf7a6727c7c49d9916353bb07c66fe6bcd",
  "actor": "tracernz",
  "event_name": "manual"
}
```

### Describe the bug

Since a few days with daily update of the DEV Version (always keep it at the actual version), if one plans a flight within SIMBRIEF, the calculation for the FUEL seems to be way to low. Used the SIMBRIEF "Flight Model" that comes from the FBW Documentation and also with the SIMBRIEF provided A320-251N model. E.G. the calculation fpr the BLOCK Fuel for a Plan LOWI-LMML (see screenshot from OFP in the Reference section) gives me **only** 5822kg of fuel. After loading the SIMBRIEF into the MCDU and fill out the INIT1/2 the FPL with SIDs/STAR/Appr and the PERF. it shows in the FUEL PRED only 0.6 EFOB. Duriong the flight one receive a Warning that the EFOB is too low and the EFOB in FUEL PRED will show "---".

Learned, that there were changes in the W&B. Maybe this causes problems with the SIMBRIEF calculations?

### Expected behavior

That the calculation works as before...it always left roundabout 2 tons of fuel as EFOB

### Steps to reproduce

1. Plan LOWI-LMML in SIMBRIEF
2. Load SIMBRIEF Data into MCDU
3. Reload Fuel and Payload from SIMBRIEF in MCDU W&B
4. Load SIMBRIEF Data in INIT Page 1
5. EDIT Flightplan with Departure and Arrival DATA
6. Check Radio NAV
7. INIT 2 (Fill Block, Wind and ZFWCG (Click 2 times to Load the data)
8. Fill PERF with DATA from OFP and Navigraph Charts
9. Check FUEL EFOB - way too low

### References (optional)

[ OFP ]
--------------------------------------------------------------------
OFP 1      AUAG2K2  / AUAG2K2        +2.00 LOWI/INN - LMML/MLA +2.00
CALC 1853Z FOR ETD 1850Z 13AUG21        OBS 1312 PROG 1318 1321 1400
	
A320-251N-LEAP-1A26 - MSN     - OE-LBU - PERF FACTOR +0.0

      EST   MAX   |LOWI/INN  OUT    OFF     SLOT  |CO RTE   INNMLA01
DOW  41005        |STD 1850Z                      |ALTN         LICB
PYLD 13272        |          .....  .....   ..... |FLT NBR   AUAG2K2
ZFW  54277 64300L |LMML/MLA  IN     ON            |CI             19
FUEL  5822 19046  |STA 2110Z                      |CRZ FL      FL290
TOW  60099 79000  |          .....  .....         |CRZ TEMP      -33
TRIP  3671        |          BLK    FLT           |TROPO       43897
LW   56428 67400  |                               |ZFW          54.3
ULD  10023        |BLK 2.20  .....  ..... 1.50 TET|TRIP WIND     T19

**Comment by FGrabi** [comment]
Maybe it is related to #5651?

**Comment by donstim** [comment]
Sorry it's not documented as a Github issue, but we know that fuel burn is too high at temperatures above ISA. We are investigating and will provide a fix.

**Comment by aguther** [comment]
Duplicate #5651
