### ISSUE TITLE
Cruise page shows NAN for fuel used

### ISSUE THREAD

**Issue by rbywater** [flybywiresim/a32nx#5647]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-14T06:41:53+00:00",
  "ref": "master",
  "sha": "a67f7ac36d9805949846f1531c14c16453e29ae3",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

When flying, the Cruise page shows NAN for the F.USED values. Have also noticed in LittleNavMap that the fuel flow is being reported as 0kg/hr so not sure if related.

### Expected behavior

A valid F.USED value is shown.

### Steps to reproduce

1. Perform a flight and review Cruise ECAM page

### References (optional)

![NaNCruisePage](https://user-images.githubusercontent.com/384963/129441317-354f7970-cfe3-446e-bb27-953e63a094e0.png)

### Discord Username (optional)

r2b2nz#7629

**Comment by rbywater** [comment]
(Actually just noticed that its showing LBS under F.USED too which I'm assuming is also not expected)

**Comment by Venorcis** [comment]
Yeah I noticed this too, though it's not very consistent when it happens. On one of my latest flights it seemed to have happened right on flap retraction, see https://www.twitch.tv/videos/1113043109?t=00h20m55s, though on some other flights it didn't occur (all with latest development version).

**Comment by ErickSharp** [comment]
Hello, is this an issue that you have witnessed happening on the ENG page as well?

**Comment by Venorcis** [comment]
> Hello, is this an issue that you have witnessed happening on the ENG page as well?

I looked it up for you; seems to be the CRUISE page only (see e.g. https://www.twitch.tv/videos/1111986289?t=00h14m35s)

**Comment by ErickSharp** [comment]
> > Hello, is this an issue that you have witnessed happening on the ENG page as well?
> 
> I looked it up for you; seems to be the CRUISE page only (see e.g. https://www.twitch.tv/videos/1111986289?t=00h14m35s)

Awesome, I will prepare a fix tomorrow : )

**Comment by wpine215** [comment]
> > > Hello, is this an issue that you have witnessed happening on the ENG page as well?
> > 
> > 
> > I looked it up for you; seems to be the CRUISE page only (see e.g. https://www.twitch.tv/videos/1111986289?t=00h14m35s)
> 
> Awesome, I will prepare a fix tomorrow : )

This was fixed, correct?

**Comment by sidnov** [comment]
> I haven't seen this happening anymore in a long time now

Thanks for confirming!

General note, if anyone still notices the issue occuring, feel free to reopen the issue with appropriate build_info and screenshots.
