### ISSUE TITLE
ND not working in northern regions of the earth

### ISSUE THREAD

**Issue by DomWin02** [flybywiresim/a32nx#5648]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-11T07:29:20+00:00",
  "ref": "master",
  "sha": "1c5335ec13ec6b7d29319db3371299da5e4fb880",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

ND is frozen in cruise shortly before decent from flight ENTC to ENSB (Tromso to Longyearbyen). VFR Map and ND are not able to move more nothern that WPT PITOL(76°19'60.0"N  014°53'2.5"E) Plan mode is still operating where ACFT Symbol is moving. 

### Expected behavior

Not able to fly safely about 75 degres or nothern

### Steps to reproduce

1. Start sim
2. fly to longyearbyen
3. cross 75 noth or WPT PITOL

### References (optional)

![20210814125825_1](https://user-images.githubusercontent.com/88674959/129444299-67a02873-89d9-41d2-a976-b08837e3573d.jpg)
![20210814125835_1](https://user-images.githubusercontent.com/88674959/129444300-2f536f95-018d-429c-936b-acacae8492a6.jpg)

### Additional info (optional)

Plan mode is still working but all other ND-Modes not working. When switching back from PLan mode to ARC the route is appearing fro a second and then away

### Discord Username (optional)

DomenicHAJ#0457

**Comment by tracernz** [comment]
On custom FPM branch, all appears okay when departing ENSB, so probably fixed in that branch with the new ND + FMS.
![image](https://user-images.githubusercontent.com/9995998/129444468-50cb1dcc-afe8-4faf-8407-677fbc175917.png)

**Comment by 2hwk** [comment]
Fixed by 4953 closing ☑️
