### ISSUE TITLE
Performance decreases after 1-2 hours in flight and continues decreasing

### ISSUE THREAD

**Issue by eze1510** [flybywiresim/a32nx#5649]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-14T06:41:53+00:00",
  "ref": "master",
  "sha": "a67f7ac36d9805949846f1531c14c16453e29ae3",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

FPS starts consistent with no decrease or lag. After 1-2 hours enroute the FPS continually decrease. This does not matter where the takeoff/landing/enroute portion was. Could be over ocean, clouds or busy airports. FPS continues to decrease and main thread usage continues to increase

### Expected behavior

Consistent FPS throughout entire flight, notwithstanding scenery rendering requirements

### Steps to reproduce

Fly for over 1-2 hours
No addons

**Comment by Benjozork** [comment]
Without any screenshots of the FPS counter (the one included with MSFS) we can't check anything.

**Comment by JJKHub** [comment]
Maybe related:
https://forums.flightsimulator.com/t/after-playing-a-few-hours-fps-drops-from-40-to-5fps/389603

**Comment by Benjozork** [comment]
Since there's been multiple reports of it happening with other aircraft here and elsewhere, I will close this as it is very likely to be an MSFS issue.
