### ISSUE TITLE
[BUG] S-speed shouldn't be targeted when climbing with flaps

### ISSUE THREAD

**Issue by Venorcis** [flybywiresim/a32nx#565]
**Mod Version**
master

**Describe the bug**
When climbing with flaps extended, the S-speed is taken as the overall speed limit, which is incorrect.

**To Reproduce**
See https://youtu.be/Zsk72luNZvc?t=1098

**Expected behavior**
The airplane should keep accelerating (unless there's some alterior speed limit set, but that's unrelated to the S-speed anyway).

**Actual behavior**
The aircraft keeps S-speed until the flaps are retracted.

**Comment by doratown** [comment]
That's correct if it's after acceleration altitude

before acceleration altitude it should target at v2 instead of s speed

**Comment by SLUF4** [comment]
I noticed this too.  The aircraft will accelerate toward 250knots, which is how you keep on your flap retraction schedule.  It shouldn't stop at the S speed like it does in the flight sim.
