### ISSUE TITLE
Fuel consumption much higher than planned on long haul

### ISSUE THREAD

**Issue by kutak11** [flybywiresim/a32nx#5651]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-14T06:41:53+00:00",
  "ref": "master",
  "sha": "a67f7ac36d9805949846f1531c14c16453e29ae3",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

The aircraft burns much more fuel on cruise level then calculated on simbrief. Then is also constant decreasing of EFOB at destination on MCDU fuel page during the flight.
Planned trip fuel was 12700Kg, actual was 16500Kg (23% difference). All weather conditions (wind, temperatures) were accurate comparing OFP and simulator.

### Expected behavior

Planed trip fuel should be accurate with some reasonable tolerance. 

### Steps to reproduce

1. Plan long haul flight for eaxmple LKPR-OMDB
2. Compare fuel on board with OFP during flight
3. Check MCDU fuel page for fuel prediction at destination

### Additional info (optional)

May it is caused by high temperature at cruising level. ISA +18 degrees. But this is also planned on OFP and matched the sim reality prefectly.

**Comment by Benjozork** [comment]
Fuel prediction should be more accurate when VNAV is implemented (#5293)

**Comment by aguther** [comment]
Could you please provide us the FDR of your flight together with the OFP?

That would help us analyzing and checking.

**Comment by kutak11** [comment]
what FDR software you recomend to use? 
[OMDBLKPR_PDF_1628964751.pdf](https://github.com/flybywiresim/a32nx/files/6987202/OMDBLKPR_PDF_1628964751.pdf)
![Microsoft Flight Simulator Screenshot 2021 08 14 - 23 18 58 18](https://user-images.githubusercontent.com/72166387/129460355-41567feb-5daf-4b3e-87dc-4d4e2d48096d.png)

as an example I post screenshot and OFP at least. Check status at UMH waypoint. Wind, temp. all good but Fuel Flow, FOB, and "Fuel used" number are well higher causing I have unsufficient fuel indication even with 2 tons extra before half on my way.

**Comment by aguther** [comment]
Just have a look into the work folder, the A32NX has an built-in FDR, see also here:
https://docs.flybywiresim.com/start/autopilot-fbw/#reporting-issues

**Comment by kutak11** [comment]
[https://drive.google.com/file/d/1uvhIsPktUFUajxPRSC5WZFIf1KhhwnVZ/view?usp=sharing](url)
more than 500MB file

I have just noticed when ISA temperature went slowly down from +18 to +5 the Fuel flow is much lower and it is near the average kg/hr value in OFP. So definitely it is about ISA high temperature condition (near Middle east now). Maybe Simbrief can not calculate it correctly. But the difference is huge.

**Comment by donstim** [comment]
Though we don't have it documented here in the issues on Github, we are aware that the fuel burn is too high at temperatures higher than ISA. It is under active investigation and will be fixed.

**Comment by FGrabi** [comment]
Should I close my Issue #5646?

**Comment by aguther** [comment]
@kutak11 FYI this is from the data you provided to us, it will help us checking if the fuel flow is fine:

![image](https://user-images.githubusercontent.com/6629914/129947027-7ef23144-9b4d-4cab-a878-4009c66f271b.png)
![image](https://user-images.githubusercontent.com/6629914/129947080-033dc391-e9ab-4687-b9e5-712b05acd2f4.png)

**Comment by Taz5150** [comment]
> data.

Thanks @aguther. Right now there are a number of issues regarding fuel consumption as well as fuel flow at non-ISA conditions as @donstim commented. I would leave this issue open until we are able to solve all these.

**Comment by sidnov** [comment]
As per donbikes' recent testing, non-ISA performance has improved to a great extent with recent updates. Thus, closing this issue until more improvements arrive with the engine model updates (which can be tracked on the Fuel/Engine META issues).
