### ISSUE TITLE
Blender Cube in plane.

### ISSUE THREAD

**Issue by Awemeter** [flybywiresim/a32nx#5652]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-14T06:41:53+00:00",
  "ref": "master",
  "sha": "a67f7ac36d9805949846f1531c14c16453e29ae3",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

A bunch of blender cubes on the engine cones and Foward and aft doors.

### Expected behavior

For there to not be blender cubes

### Steps to reproduce

Load the plane

### References (optional)

![image](https://user-images.githubusercontent.com/71922517/129461763-5bbf6c63-e925-40d7-8e29-fdf8f0ddc6cf.png)
No blender cubes here (IRL IMAGE)

![image](https://user-images.githubusercontent.com/71922517/129461771-56b2e2ae-b5bc-4bbe-928f-62c9e400dffa.png)
![image](https://user-images.githubusercontent.com/71922517/129461782-11f420e4-4f52-4ac8-ba87-c82c81462ee0.png)
![image](https://user-images.githubusercontent.com/71922517/129461830-3556a687-0795-4bac-b71a-7bf78f4cdd5b.png)

### Discord Username (optional)

Awemeter#3110

**Comment by Benjozork** [comment]
Sounds like an issue with the model merging script perhaps ?

**Comment by tracernz** [comment]
The material lost it’s invisibility cloak in the last PR. https://github.com/flybywiresim/a32nx/pull/5520/files#diff-5fe291e6f3058c8d1ce7b144a078934609ef5dac2ab725eca3f81dea151103abL564
