### ISSUE TITLE
Game Freezes When Paused

### ISSUE THREAD

**Issue by awolfden3** [flybywiresim/a32nx#5653]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-08-09T18:57:24+00:00",
  "ref": "v0.6.3",
  "sha": "7222a9516e4114742a7fec84080a2f63ea527428",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

Upon pressing the "esc" key the game pauses as normally, but the UIs do not come up and it becomes impossible to un-pause, I simply have to restart or return to homescreen. (This issue seems to only occur when using this aircraft)

### Expected behavior

I would like to see a normal pause screen!

### Steps to reproduce

1. Press "esc"

### Discord Username (optional)

AWolfDen#2527

**Comment by DomWin02** [comment]
I agree with it

**Comment by sidnov** [comment]
It's a simulator bug that came with SU5. Does not happen every time and is quite difficult to reproduce. Something Asobo can fix and is not related to the A32NX
