### ISSUE TITLE
Weather radar tilt & gain 

### ISSUE THREAD

**Issue by pwnorbitals** [flybywiresim/a32nx#5657]
### Aircraft Version

Development

### Description

Wondering if this is a feature in dev, considered, or blocked by the limitations of Asobo weather system. Couldn't find an issue related to this topic, but I wouldn't be surprised if I missed it somewhere. Thanks for considering

### Discord Username (optional)

Chris [pwnOrbitals]#5363

**Comment by Benjozork** [comment]
This is currently impossible due to lack of support in MSFS weather radar system.

**Comment by pwnorbitals** [comment]
I understand. Thanks for the quick answer
