### ISSUE TITLE
Aircraft crashes to a runway at FLARE

### ISSUE THREAD

**Issue by maxpain** [flybywiresim/a32nx#5666]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-08-09T18:57:24+00:00",
  "ref": "v0.6.3",
  "sha": "7222a9516e4114742a7fec84080a2f63ea527428",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

Watch my YouTube video, I did not disable autopilot, it was engaged all the time:

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/rPP6O9DzTsY/0.jpg)](https://www.youtube.com/watch?v=rPP6O9DzTsY&t=868s)

### Expected behavior

Aircraft should land smoothly

### Steps to reproduce

Do ILS 14R approach in UUDD

### Discord Username (optional)

Maxim Makarov#1337

**Comment by sidnov** [comment]
There is no autoland in the current stable version. Please use the development version for advanced autopilot capabilities such as autoland.

**Comment by sidnov** [comment]
Also, a detailed list of features available in the development version can be found here: https://docs.flybywiresim.com/start/fbw-versions/#version-comparison
