### ISSUE TITLE
Pilot2ATC does not work well with FBWA320

### ISSUE THREAD

**Issue by alainzu** [flybywiresim/a32nx#5673]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-17T07:39:33+00:00",
  "ref": "master",
  "sha": "59fa86a68bce86ce72423c9f50e964b1dbeebd12",
  "actor": "2hwk",
  "event_name": "manual"
}
```

### Describe the bug

Hello since a recent update, Pilot2ATC does not work properly when loading FBWA320 at a gate: no ATIS, no controller voice, no speech recognition. P2ATC works fine with the stock MSFSA320.

### Expected behavior

When P2ATC is connected, ATIS is emitted and when pilot calls TWR, pilot's speech is recognized and result in a controller answer.

### Steps to reproduce

1. Load MSFS2020
2. Load FBWA320/Gate
3. Upper pannel external power supply to get the radios active
3. Load P2ATC and connect
4. Then the bug is as previously described

**Comment by chromkoo** [comment]
Same happened to me. I suggest updating FSUIPC to the newest version (i guess it was 7.2.6 but not sure) since this fixed the issue for me, now it works perfectly fine without any issues.

**Comment by aguther** [comment]
I have no idea how this software is interfacing with the sim tbh. Have you also asked in the support of Pilot2ATC?
