### ISSUE TITLE
ENG1 master with TCA quadrant not available

### ISSUE THREAD

**Issue by cellotako** [flybywiresim/a32nx#5676]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-17T07:39:33+00:00",
  "ref": "master",
  "sha": "59fa86a68bce86ce72423c9f50e964b1dbeebd12",
  "actor": "2hwk",
  "event_name": "manual"
}
```

### Describe the bug

ENG1 master with TCA quadrant not available.
During turning on quadrant, clicking eng 1 knob in simulator doesnt work.
but i turning off it on quadrant, clicking can be accepted.

### Expected behavior

follow its behavior as same as quadrant

### Steps to reproduce

1. turn on eng 1 master on quadrant
2. doesnt work
3. clicking eng1 master on sim
4. doesnt work
5. turn off eng1 master on quadrant
6. clicking eng1 on sim workes, but not match

**Comment by tracernz** [comment]
Are you carrying over a control profile from prior to SU5? [Please check reported issues](https://docs.flybywiresim.com/start/reported-issues/#tca-thrustmaster-hardware), and if that fails #support on Discord is the best place to get help.

**Comment by cellotako** [comment]
im really sorry and thx for information.

**Comment by tracernz** [comment]
> 
> 
> im really sorry and thx for information.

It's all good. 😃 GitHub is just not the best place for these kinds of issues due to slow responses vs. Discord that is real time.
