### ISSUE TITLE
No Cockpit noises with FBW A"éà

### ISSUE THREAD

**Issue by alainzu** [flybywiresim/a32nx#5677]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-17T07:39:33+00:00",
  "ref": "master",
  "sha": "59fa86a68bce86ce72423c9f50e964b1dbeebd12",
  "actor": "2hwk",
  "event_name": "manual"
}
```

### Describe the bug

I do not hear any cockpit noise (engines, APU) in cockpit view.
Engine noises are audible in external view
Cockpit noises are audible when other stock aircrafts are loaded (A320, TBM930)

### Expected behavior

I should hear cockpit noises in cockpit view

### Steps to reproduce

1. load FS2020
2. select any FBWA320 on any airport RW
3. select cockpit view: no cockpit noise
4. select external view: engines noises are loud

**Comment by tracernz** [comment]
Check the sound settings in the flyPad. The engines are somewhat audible on the ground, but in-flight the wind is much louder and the engines cannot really be heard on an A320neo.

**Comment by alainzu** [comment]
I have set the sound settings to max in both flypad and FS2020 sound settings and I just hear a small fly noise, wheras engine noise is 65 dB in exterior view
Did you hear the engine sound in a real Airbus during takeoff? It is almost 90 dB

**Comment by hotshotp** [comment]
This is only an issue when you have two versions of the a32nx installed. Remove any marketplace version and such, and reinstall with the FBW installer. For more support come over to our discord as GitHub is not the place for support.
