### ISSUE TITLE
Waypoint  and SID  have been missing since the last dev version

### ISSUE THREAD

**Issue by Pat15250** [flybywiresim/a32nx#5682]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-18T21:30:52+00:00",
  "ref": "master",
  "sha": "b7076762217e0fa89881c4425816500a5d9f5b6a",
  "actor": "bouveng",
  "event_name": "manual"
}
```

### Describe the bug

Hello,
I was preparing a flight between WADL to YPDN.
On FMS, after have imported flight plan from simbrief, all waypoint was missing.
SID was also missing.
I tried to select waypoint manuelly, but they were unknow.
I'm wondering if airac have not been lost
Thanks a lot for your job.
Patrick

### Expected behavior

Possibility to import the whole flight plan from simbrief with waypoint (as it worked well before).

### Steps to reproduce

Place the plane to WADL
On FMS, import flight plan from simbrief  (waypoint missing)
Select RWY 13 and SID (no SID).
Try to select waypoint manually (no way point available)

**Comment by tracernz** [comment]
Hi Pat. Do you get a `NOT IN DATABASE` message on the scratchpad when this happens? If so, try the suggestions in https://docs.flybywiresim.com/start/reported-issues/#not-in-database-when-loading-flight-plan

**Comment by Pat15250** [comment]
Hi tracernz,

I thank you for your advice.
It's not a bug, but many waypoints and SID/STAR are natively missing in asobo flight sim.
I have found this solution: I have updated airac in flight simulator with navigraph nav data center, and it now works perfectly.
Then I close the bug.
Patrick
