### ISSUE TITLE
[BUG] APU start possible with batteries switched off

### ISSUE THREAD

**Issue by komp1821** [flybywiresim/a32nx#569]
**Mod Version**

Latest master, downloaded on Sep, 10th - 10:00 UTC

**Describe the bug**

Starting the APU is possible with batteries switched off. However, APU start requires batteries to be switched on.

**To Reproduce**

1. Energize the aircraft from external power but keep batteries switched off.
2. Turn on APU MASTER SW pushbutton and APU START pushbutton
3. APU N increases, EGT rises.

**Expected behavior**

With batteries off, APU, APU N stays at 0%. 
After a few seconds, an ECAM caution "APU AUTO SHUT DOWN" is generated along with a single chime. The fault light in the APU MASTER SW pushbutton illuminates.
There might be further ECAM indications, like INOP SYS APU, but I cannot confirm yet. Will check it next time at work though.

**Actual behavior**

APU starts normally.

**References**

I can provide a short video showing the actual irl behaviour, but it will take a few days.

**Additional context**

Find me in the Discord channel, komp#1821

**Comment by omarocasio** [comment]
Confirmed can start APU, regardless of battery on or off

**Comment by UncleClapton** [comment]
confirmed. seems like the APU Core doesn't take electricity into account. I can take a look into resolving this

**Comment by UncleClapton** [comment]
Final solution will likely be hooking the button into the new electrical system, along with electricity being taken into account in the APU core. 

For now I have tied both buttons to the electrical bus and called it good
