### ISSUE TITLE
Slow Climb Rates

### ISSUE THREAD

**Issue by Honest989** [flybywiresim/a32nx#5690]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-20T08:03:46+00:00",
  "ref": "master",
  "sha": "9ff3810c9c49dd54a4407b5046a4a27bd4b88517",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

Climb rates above FL100 slow down to between 500 - 1600 feet per minute. This is quite slow and means an excessive amount of fuel is consumed during the climb. Changing the climb mode to vertical speed, on the other hand, will result in the aircraft losing speed until it automatically levels out or reaches a rate of climb where the plane does not lose speed.

### Expected behavior

climb rates of at least 1800-2000 feet per minute.

### Steps to reproduce

Enter Flight Plan, either manually, via sim brief import or through the main menu screen
Set desired cruise altitude
Take off from airport and activate autopilot
Observe behaviour after FL150

**Comment by aguther** [comment]
Can you please provide more information like outside temperature, screenshots or a FDR file of flights in question?

I ask this because I do not have this behavior, so it's not a common issue.

**Comment by Honest989** [comment]
I will try to reply next week with this as I'm going to be out of the
country for the next couple of days.

Interestingly enough I didn't experience the issue this morning after
writing up the bug!!

**Comment by ErikNL80** [comment]
Can you please watch the temperatures? There was a bug in the sim that caused very high temperatures affecting the a/c performance...

**Comment by TLSY2** [comment]
Ive also experienced this before, sometimes it was buggy af, plane wasnt even loaded and toga and couldn even climb, it was losing speed when v speed 0.

**Comment by aguther** [comment]
@TLSY2 What a helpful comment, we know almost nothing from it.

First of all it’s completely unclear if this issue is really about a bug or not, right now I highly doubt it.

Secondly there are so many things that also can be done by the pilot and I also don’t know if you’re experienced or not. Today in support someone complained about climb performance and guess what: the gear was still down. Thanks to the screenshot this was easy to detect and help could be provided. There are also other things that can happen like too high temperature etc.

Keep in mind that running behind all this takes a lot of time in some which is then not going into development. So I ask you to provide more quality feedback. Thank you.

**Comment by TLSY2** [comment]
> @TLSY2 What a helpful comment, we know almost nothing from it.
> 
> 
> 
> First of all it’s completely unclear if this issue is really about a bug or not, right now I highly doubt it.
> 
> 
> 
> Secondly there are so many things that also can be done by the pilot and I also don’t know if you’re experienced or not. Today in support someone complained about climb performance and guess what: the gear was still down. Thanks to the screenshot this was easy to detect and help could be provided. There are also other things that can happen like too high temperature etc.
> 
> 
> 
> Keep in mind that running behind all this takes a lot of time in sum which is then not going into development. So I ask you to provide more quality feedback. Thank you. 

I dont know what you want to hear, it was a normal takeoff, gear up, flaps up the plane wasnt even loaded much like 59 tonns tow and after take off it was losing speed, i pushed the nose down to 1 degree still losing speed, i hardly managed to climb to 7000ft and i held it level for a while and after that i gained a little speed and started to climb .5 degrees and i was losing speed, it got to 150 knots below the red, at that point i lowered the nose to 1 degree and not even then it wasnt gaining speed (this was at an altitude of 17000 ft)

**Comment by aguther** [comment]
Ok, this is at least a start. Why do I need to ask to get a better description?

Unfortunately even this description is not helping finding the issue. I have no idea what the outside conditions have been nor what you FMA said. Sorry in that way it’s impossible to find the root cause. Screenshots or an FDR file can help much better in that.

**Comment by Honest989** [comment]
Hey - now back. 
There was an update to the development version somewhere between when i left for the weekend and today, the 24/8/21.
A couple of pieces of information:
I flew this on preset conditions (clear) with real traffic
It was a cold and dark start
I then loaded in Rex Weather force Weather
I generated a plan in sim brief
I loaded flex values of 143(v1), 144(v2), 144(v3), F1/Up0.8, 61 degrees c.
I left all other pre selected performance values as were
Then I took off. I now attach some photos - the early part of the climb was fine but with high consumption rates. Above FL200, climb rates were erratic - between 1000 to 3600 fpm.

![Microsoft Flight Simulator Screenshot 2021 08 24 - 01 18 01 33](https://user-images.githubusercontent.com/67310316/130536660-4af6bd30-edb5-432d-b14c-538e48716fd8.png)
![Microsoft Flight Simulator Screenshot 2021 08 24 - 01 21 11 78](https://user-images.githubusercontent.com/67310316/130536664-a143d3e4-b161-4c23-8a38-1c674b58ab5e.png)
![Microsoft Flight Simulator Screenshot 2021 08 24 - 01 23 38 83](https://user-images.githubusercontent.com/67310316/130536665-b4210f8e-ac56-4421-bedc-bdd4e7516a3d.png)
![Microsoft Flight Simulator Screenshot 2021 08 24 - 01 23 49 75](https://user-images.githubusercontent.com/67310316/130536668-cf6c8e38-080a-421b-b373-5b63c27fc644.png)
![Microsoft Flight Simulator Screenshot 2021 08 24 - 01 24 23 99](https://user-images.githubusercontent.com/67310316/130536670-61da8fd0-1b6c-4fe7-8c93-0209fbd53252.png)
![Microsoft Flight Simulator Screenshot 2021 08 24 - 01 24 56 21](https://user-images.githubusercontent.com/67310316/130536671-06f7b420-4755-4fdb-a8dd-f7cd4745a156.png)

**Comment by donstim** [comment]
In general, climb rates in the screenshots look appropriate to me for the weight, altitude, speed, and temperature. That is, there is no evidence of an abnormally slow climb rate as alleged in the title of this issue. The temperatures are pretty darn high, but are possible depending on where  you are flying. The only known issue with the airplane at these temperatures is that fuel flow is too high. Thrust and the resulting climb rate will be lower than at lower temperatures, but they are accurate. 

As for the "erratic" climb rate in the last few screenshots, it looks like there is something that caused the airplane trade speed for climb rate, This resulted in higher climb rate, but a speed excursion below the target airspeed. When the airplane reacted to regain speed, it had to lower the climb rate to do so. In the last screenshot, the speed and climb rate are back to stable values. It might be possible to determine what caused the upset if you can provide the FDR file for the flight. See https://docs.flybywiresim.com/fbw-a32nx/feature-guides/autopilot-fbw/ for how to find that file.

**Comment by donstim** [comment]
> > @TLSY2 What a helpful comment, we know almost nothing from it.
> > First of all it’s completely unclear if this issue is really about a bug or not, right now I highly doubt it.
> > Secondly there are so many things that also can be done by the pilot and I also don’t know if you’re experienced or not. Today in support someone complained about climb performance and guess what: the gear was still down. Thanks to the screenshot this was easy to detect and help could be provided. There are also other things that can happen like too high temperature etc.
> > Keep in mind that running behind all this takes a lot of time in sum which is then not going into development. So I ask you to provide more quality feedback. Thank you.
> 
> I dont know what you want to hear, it was a normal takeoff, gear up, flaps up the plane wasnt even loaded much like 59 tonns tow and after take off it was losing speed, i pushed the nose down to 1 degree still losing speed, i hardly managed to climb to 7000ft and i held it level for a while and after that i gained a little speed and started to climb .5 degrees and i was losing speed, it got to 150 knots below the red, at that point i lowered the nose to 1 degree and not even then it wasnt gaining speed (this was at an altitude of 17000 ft)

I know it's a bit of a pain, but can you repeat this and make a video out of it?  Still tough to diagnose off this description.

**Comment by MisterChocker** [comment]
Looking at the ecam I can see a ISA deviation of +19°C which also has an impact on the climb performance.

**Comment by MisterChocker** [comment]
Closing since no response from the op.
