### ISSUE TITLE
Seatbelt/No smoking signs volume differences

### ISSUE THREAD

**Issue by ErikNL80** [flybywiresim/a32nx#5695]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-20T22:39:37+00:00",
  "ref": "master",
  "sha": "d83e0f4308e4916f452f370d75bdaeb3493f4f4f",
  "actor": "RichardPilbery",
  "event_name": "manual"
}
```

### Describe the bug

With the change of the sounds I found a difference in volume for both the seatbelt signs and no smoking signs. When initializing the aircraft both sounds can be heard very good. But after take-off, after gear is retracted sounds are less loud. Also at 10.000 feet when switching seatbelt signs off the sound is also very heard to hear. Same after landing at the gate when disabling the signs...

### Expected behavior

I would expect the sound volume to be consistent.

### Steps to reproduce

1. Start a flight C&D
2. Set the seatbelt/no smoking signs
3. Take-off, and observe signs behaviour
4. Land and park the aircraft and test the sounds.

**Comment by sidnov** [comment]
Cabin sounds are more audible with doors open, which is the case with spawning cold and dark, whereas it is not audible with closed doors. This was an intentional change made to improve realism, and not a bug.

**Comment by hotshotp** [comment]
Indeed. The cockpit door position is controlled by the lock switch. If it's unlocked it counts as if it is open, making sounds like the chimes louder.
