### ISSUE TITLE
Vertical speed sync 

### ISSUE THREAD

**Issue by TheRealEdge** [flybywiresim/a32nx#5698]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-22T09:34:12+00:00",
  "ref": "master",
  "sha": "41c0ae58d650410bcd438f7b020dec641c86be44",
  "actor": "2hwk",
  "event_name": "manual"
}
```

### Describe the bug

I was using flypad when i wanted to predict the descent with the mode "top of descent". then when i clicked on Sync on vertical speed, my fps goes from 60 to 15

### Expected behavior

Nothing, the system worked but my fps fell.

### Steps to reproduce

1. open flypad
2. go in the top of descent mode (near the landing prediction)
3. then go to descent angle and click the red X
4. click SYNC on vertical speed
5. and then the frames will drop

### Additional info (optional)

the issue start occurring from today

### Discord Username (optional)

TheRealEdge#1727

**Comment by NUTTTTTTTT** [comment]
Tested and verified issue persists for both V/S and FPA sync in descent calculator - looks to be related to https://github.com/flybywiresim/a32nx/pull/5541 being merged.

**Comment by frankkopp** [comment]
Confirmed - see video 

https://user-images.githubusercontent.com/16833201/130357852-ace067e2-4de4-4adc-98e0-8104c79062dc.mp4

**Comment by NUTTTTTTTT** [comment]
@TheRealEdge There is a fix for this in progress. :)
