### ISSUE TITLE
Removal of Taxi Map on ND 

### ISSUE THREAD

**Issue by davidonthereg** [flybywiresim/a32nx#57]
The taxi map on ND is currently too illegible, and inaccurate.

**Comment by AdenFlorian** [comment]
I'm working on this, almost got it, maybe.

**Comment by AdenFlorian** [comment]
Got a fix, will clean up and put up a PR tomorrow for it.

**Comment by AdenFlorian** [comment]
Only have half a fix, but better than nothing! #232

**Comment by Curtis-VL** [comment]
Corrected as best as we can in #232, waiting for Asobo fixes to allow it to be off when the weather radar is off! Thanks for the report! 👍

**Comment by AdenFlorian** [comment]
reopening as its still an issue, we can track progress on asobo's side on this ticket

I created a zendesk ticket about it a while ago and got this email today:

![image](https://user-images.githubusercontent.com/3533988/93129429-985d4c80-f696-11ea-939b-1d27f3de8b56.png)

**Comment by hotshotp** [comment]
issue is fixed

**Comment by AdenFlorian** [comment]
only half fixed

**Comment by hotshotp** [comment]
we decided to close the issue as it is fixed with the terrain/wxr not showing at lower altitudes
