### ISSUE TITLE
[BUG] APU shutdown rpm drop too slow

### ISSUE THREAD

**Issue by komp1821** [flybywiresim/a32nx#570]
**Mod Version**

Latest master, downloaded on Sep, 10th - 10 UTC

**Describe the bug**

APU N (RPM) decreases very slowly during shutdown.

**To Reproduce**

1. Start the APU
2. Select APU SD 
3. Shut down the APU and monitor APU page

**Expected behavior**

RPM drops very fast after shutdown. See example video. 

**Actual behavior**

**References**

https://www.youtube.com/watch?v=Q5hFUwuFWTI

**Additional context**

**Comment by ThePilot916** [comment]
I'm afraid that this can only be updated to a cosmetic upgrade since the rate at which apu rpm increases or decreases is a constant of 0.01pct/sec until we can figure out a way to change the very underlying system functions.

**Comment by tareksabet** [comment]
fixed by pr #1295

**Comment by davidwalschots** [comment]
@komp1821 will provide us with a video of the APS3200 APU shutdown. Once that video is available we can easily integrate it into APU system code. For now N reduces by 2 per second (#3004).
