### ISSUE TITLE
Auto-Brightness

### ISSUE THREAD

**Issue by Tinpanva** [flybywiresim/a32nx#5700]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-22T09:34:12+00:00",
  "ref": "master",
  "sha": "41c0ae58d650410bcd438f7b020dec641c86be44",
  "actor": "2hwk",
  "event_name": "manual"
}
```

### Describe the bug

Once auto brightness is selected on the flypad there is no way to save the setting. Once the next flight is started you have to re-select it all over again

### Expected behavior

Select it once and forget

### Steps to reproduce

select auto brightness
close program and restart
you have to select autobrightness all over again

**Comment by ErickSharp** [comment]
This is a comprehensive issue with persistent properties themselves. However, this issue should only primarily be occurring after a flight restart. It should be persisting if you exit the flight, and start a new one.

**Comment by ErickSharp** [comment]
Will be investigating, thanks for bringing it up : )

**Comment by ErickSharp** [comment]
This issue is also happening with brightness itself.

**Comment by TLSY2** [comment]
having this too!

**Comment by derl30n** [comment]
Is this still an issue?

**Comment by 2hwk** [comment]
Should be fixed by flyPad OS 3
