### ISSUE TITLE
No notification sound when seat belts is turned off/on during flight

### ISSUE THREAD

**Issue by Titux69** [flybywiresim/a32nx#5701]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-22T09:34:12+00:00",
  "ref": "master",
  "sha": "41c0ae58d650410bcd438f7b020dec641c86be44",
  "actor": "2hwk",
  "event_name": "manual"
}
```

### Describe the bug

There is no more sound when "seat belts" commutator is set to OFF nor ON during the flight.
There is notification sound only when the plane is on the ground.

### Expected behavior

A notification sound should be heard.

### Steps to reproduce

Set seat belts commutator to ON on the ground (sound OK)
take-off and flight to FL100
Turn OFF seat belts (no sound)
Turn ON seat belts (no sound)

**Comment by sidnov** [comment]
Cabin sounds are more audible with doors open, which is the case with spawning cold and dark, whereas it is not audible with closed doors. This was an intentional change made to improve realism, and not a bug.

**Comment by sidnov** [comment]
Refer to https://github.com/flybywiresim/a32nx/issues/5696
