### ISSUE TITLE
FMGC reset + huge fps drop after a while

### ISSUE THREAD

**Issue by TLSY2** [flybywiresim/a32nx#5702]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-22T09:34:12+00:00",
  "ref": "master",
  "sha": "41c0ae58d650410bcd438f7b020dec641c86be44",
  "actor": "2hwk",
  "event_name": "manual"
}
```

### Describe the bug

After flying for a while i noticed my fmgc reset and the plane was going back to its original destination, for example i was flying from EGGW/EPLB, after flying for 1 hour and 30 min it was showing EGGW/EGGW and the plane had a straight line going randomly, not even at the eggw heading.

Also there is fps drop from 50 when i took off to 20 max when im 300nm away from destination. I dont know how this is...

### Expected behavior

to work smoothly

### Steps to reproduce

fly around to any destination, this happened to me before like 1-2 times, its a bug that dont happen always

**Comment by MisterChocker** [comment]
Did you used the DIR TO feature?

**Comment by TLSY2** [comment]
> Have you used the DIR TO functionality on the flights where the issue occurred? Possibly related https://github.com/flybywiresim/a32nx/issues/5687

Yeah i used direct to a waypoint.

**Comment by MisterChocker** [comment]
Can you confirm that the two issue https://github.com/flybywiresim/a32nx/issues/5650 and #5687 represent the issues you encounter?

**Comment by TLSY2** [comment]
They all match!

**Comment by MisterChocker** [comment]
Closing then since the listed issues have already open reports.
