### ISSUE TITLE
No fuel displayed on ECAM

### ISSUE THREAD

**Issue by tellurics** [flybywiresim/a32nx#5704]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-23T03:21:49+00:00",
  "ref": "master",
  "sha": "2b0aad448865746469e7cbf7c74f898474910f70",
  "actor": "2hwk",
  "event_name": "manual"
}
```

### Describe the bug

When I load A32XN in MSFS, there's no fuel displayed on ECAM. I tried to refuel the aircraft but nothing happens
![20210823144152_1](https://user-images.githubusercontent.com/74205007/130493370-5978e003-a1a7-4094-8d42-afe01b86e6cf.jpg)

### Expected behavior

Fuel gauge showing correctly. 
(A picture of an old version, 0.5.0, there's no issue)
![ex](https://user-images.githubusercontent.com/74205007/130493261-4cd92115-322e-4ab1-b688-15331175b356.jpg)

### Steps to reproduce

1. Load the aircraft in some airport
2. Start the aircraft
3. And this happens

**Comment by NUTTTTTTTT** [comment]
Change to KG's in the MCDU options, then reload the flight. Then change back to LB's in the MCDU options and reload again, should be all good to go! Don't change this in the flyPad/EFB - this is broken atm, fix in progress.

**Comment by tellurics** [comment]
@NUTTTTTTTT, Fixed! Thank you.

**Comment by MisterChocker** [comment]
Closing since issue resolved
