### ISSUE TITLE
VHF1 always resets

### ISSUE THREAD

**Issue by alexmaryin** [flybywiresim/a32nx#5708]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2021-08-21T11:08:24+00:00",
  "ref": "experimental",
  "sha": "95f777b3c861367698dce8a1add297e86b11ccfa",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

After changing radio VHF1 and pressing <-> button selected frequency sets to 1 sec then immediately resets to previous.

### Expected behavior

Selected frequency sets to working VHS1 and stays tuned.

### Steps to reproduce

1. Select any freq. on VHS1 
2. Click <-> button.

### References (optional)

The same behavior then selecting freq. in pad.

**Comment by tracernz** [comment]
I thought we were watching films for a moment. You mean VHF1? Are you sure you don’t have the AI co-pilot tuning your radios? Check the AI assistance on the pop up toolbar at the top.

**Comment by alexmaryin** [comment]
VHF, of course. Due to vatsim flights, any assistance including COMs always off. I will try again today.

**Comment by globin** [comment]
Check in the assistance window opened from the menu bar. It turns itself on for me regularly, haven't found a solution so far for that thouth.

**Comment by alexmaryin** [comment]
It works correct today! Close the issue.
