### ISSUE TITLE
ND draws wrong track between waypoint in some SID/STAR, but it seems the plane flies correct via procedure.

### ISSUE THREAD

**Issue by alexmaryin** [flybywiresim/a32nx#5709]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2021-08-21T11:08:24+00:00",
  "ref": "experimental",
  "sha": "95f777b3c861367698dce8a1add297e86b11ccfa",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

We have difficult and long RNAV SID/STAR procedures In UUDD airport. These procedures have been drawn on ND with incorrect track (as in attach.), but plane flies correct via procedure. 
![FlightSimulator_20210823222001_hL208fqHxO](https://user-images.githubusercontent.com/74375962/130581836-79058027-4c3b-4cfa-97cb-ca122852a908.png)
![FlightSimulator_20210823222018_XKXO28R9rI](https://user-images.githubusercontent.com/74375962/130581839-9d4c0970-9579-487f-b51d-bb03b8b21b79.png)
![FlightSimulator_20210823222021_M9ylAem3kP](https://user-images.githubusercontent.com/74375962/130581847-8722f3eb-b063-48be-a8a7-ef53866fb50b.png)
![FlightSimulator_20210823222247_xilKyevYQ5](https://user-images.githubusercontent.com/74375962/130581849-b4214725-03da-4141-a638-cd4e3f07673b.png)

### Expected behavior

Track on ND shall join waypoints with single besier-line.

### Steps to reproduce

1. Select any RNAV STAR in UUDD, for example URAGO1N, insert into flight plan.
2. See visual wrong loops between next two waypoints on ND in flight plan mode.

**Comment by Benjozork** [comment]
![image](https://user-images.githubusercontent.com/4503241/130583396-b3553545-a27f-448b-95b0-ffebc90eb7bf.png)
