### ISSUE TITLE
I would like to have, please!

### ISSUE THREAD

**Issue by freakflyer** [flybywiresim/a32nx#5716]
### Aircraft Version

Development

### Description

outside view "mini" instrument indications:
Need: temperature and wind indications.
Need: that the altitude choosed in the autopilot appears correct and not always Blue 5000.
Need: Simple indication when reverse thrust is ON.
Less but Need: active Autopilot functions or simply if autopilot keeps ON.

### Discord Username (optional)

Francisco Aurélio #7986

**Comment by freakflyer** [comment]
Wishing the best to all team ! Thks a lot !

**Comment by Benjozork** [comment]
The outside view is controlled by msfs not us. Unfortunately we cannot add to it as far as we know.
