### ISSUE TITLE
Flight plan track symbols and colors

### ISSUE THREAD

**Issue by Eaglepilot6** [flybywiresim/a32nx#5718]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-14T20:40:24+00:00",
  "ref": "master",
  "sha": "2019690439abe7de5735af4730ef51f1d723e8b6",
  "actor": "MisterChocker",
  "event_name": "manual"
}
```

### Describe the bug

Flight plan should be solid green when in managed nav mode. If a direct to fix is used, the aircraft will go into managed nav and display the leg to the active waypoint as solid green. All subsequent legs of the flight plan are dashed green. The aircraft will continue to fly in managed nav and track the course line, but will continue to display a dashed green line.

Solution: Pushing the heading knob for managed nav turns the entire flight plan solid green, but this step should not be necessary. 

### Expected behavior

In managed nav mode, the entire flight plan should be displayed as a solid green line.
In selected heading/track mode, the flight plan should be displayed as a dashed green line. 
Temporary flight plan should be displayed as dashed yellow line.
Missed approach should be displayed as solid blue line. 

### Steps to reproduce

1. Create a flight plan.
2. While in managed nav, insert direct to a waypoint along the flight plan.

### References (optional)

A320 Vol 2:
The active flight plan (the flight plan the aircraft is actually following when the NAV mode is engaged) is represented by a continuous green line. The ND shows only the part of the flight plan that is ahead of the aircraft, as well as the waypoints that are still to be overflown and the waypoint from which the aircraft is coming. 
If the primary flight plan is not active, it is represented by a dotted green line.
Flight plan capture:
When the aircraft is off the primary flight plan and is flying toward it in HDG mode with the NAV mode armed, the ND shows the new active flight plan as a continuous green line if the FMGC has computed the intercept path. The part of the flight plan before the interception point shows as a dotted green line. 

### Additional info (optional)

**Workaround Solution:** Pushing the heading knob for managed nav turns the entire flight plan solid green, but this step should not be necessary. 

### Discord Username (optional)

Eaglepilot6

**Comment by tracernz** [comment]
We have built our own ND with the new flight plan manager (see experimental version), so this issue regarding the MS/Asobo ND can be closed.
