### ISSUE TITLE
System in Selftest[BUG]   

### ISSUE THREAD

**Issue by H3nr1ks-C0d3** [flybywiresim/a32nx#572]
**Mod Version**
V.0.2.0

**Describe the bug**
System in Selftest on ...window not properly formatted

**To Reproduce**

1. Turn on power
2. Turn on all screens
3. Press bleed button

**Expected behavior**
Just see System in self testing

**Actual behavior**
Half of the Text that says Bleed is visible above

**References**

![Lower ECAM SYSTEM Screen](https://user-images.githubusercontent.com/62308300/92745280-82901480-f382-11ea-8d36-f3f6670c6aa1.jpg)

![Lower ECAM SYSTEM Screen ENGINE](https://user-images.githubusercontent.com/62308300/92745851-00542000-f383-11ea-8a52-59b68a03161d.jpg)

**Additional context**

Also, the APU powers down way to slow and the system in self testing should only appear when power is initially put on, not when you put the brightness down and up again. This also means that you shouldnt be able to see the screen if power has been at full capacity for 10 minutes and the brightness has been at zero. That way it would be more realistic

**Comment by komp1821** [comment]
>  the system in self testing should only appear when power is initially put on, not when you put the brightness down and up again. This also means that you shouldnt be able to see the screen if power has been at full capacity for 10 minutes and the brightness has been at zero. That way it would be more realistic

I disagree with that. The controls for the display brightness have a switch at the lower end to switch the display off entirely. These are not just simple potentiometers. By the way, that's why it says "OFF" on the scale and not "DIM" or something. It is literally switched off and has to power-up again.

**Comment by H3nr1ks-C0d3** [comment]
> > the system in self testing should only appear when power is initially put on, not when you put the brightness down and up again. This also means that you shouldnt be able to see the screen if power has been at full capacity for 10 minutes and the brightness has been at zero. That way it would be more realistic
> 
> I disagree with that. The controls for the display brightness have a switch at the lower end to switch the display off entirely. These are not just simple potentiometers. By the way, that's why it says "OFF" in the legend and not "DIM" or something. It is literally switched off and has to power-up again.

okay point taken, I'll retract that. 
cheers

**Comment by NathanInnes** [comment]
Working on fixing css now.
