### ISSUE TITLE
EFB PTU Sound setting not saved

### ISSUE THREAD

**Issue by ErikNL80** [flybywiresim/a32nx#5722]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-25T07:03:31+00:00",
  "ref": "master",
  "sha": "eb7ab6f30c5e276062cde6cb23b6e261afbee09f",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

Recently I found that I did not hear the PTU sound anymore. When checking the EFB this setting was disabled. I enabled it and could hear the PTU sound. However, after closing and starting the sim again the setting is again defaulted to off...

### Expected behavior

I would expect the setting is stored so you only need to touch it when you want to change it.

### Steps to reproduce

1. Start a flight, check the EFB for the PTU sound setting
2. Verify it is OFF
3. Set it to ON and do a flight as normal
4. Check the PTU sound on start-up
5. Close MSFS
6. Start MSFS again and check the EFB setting again...

### References (optional)

![PTUSetting](https://user-images.githubusercontent.com/71258178/130842112-3382979f-aae6-46d8-9f4e-55f172cf7687.png)

**Comment by tracernz** [comment]
What exactly does 
> 5. Close MSFS

mean? The settings are only saved if you quit "properly" through the main menu. `Alt + F4` etc. will not save settings.

**Comment by ErikNL80** [comment]
> What exactly does
> 
> > 1. Close MSFS
> 
> mean? The settings are only saved if you quit "properly" through the main menu. `Alt + F4` etc. will not save settings.

With close I mean leaving MSFS properly. End your flight, at the main menu choose exit...

**Comment by tracernz** [comment]
I've just taken a look at the code in the meantime, and yeah, there is definitely an issue.

**Comment by ErikNL80** [comment]
> I've just taken a look at the code in the meantime, and yeah, there is definitely an issue.

Can you please remove the label 'Waiting for response' since I commented on the initial question?

**Comment by ErikNL80** [comment]
Thanks!
