### ISSUE TITLE
EFB: Move the Telex Prompt and Setting from MCDU to EFB

### ISSUE THREAD

**Issue by tracernz** [flybywiresim/a32nx#5726]
### Aircraft Version

Development

### Description

Move the telex prompt (on first use) and setting from the MCDU to the EFB. It is one of the last 3 remaining "sim" options to be removed after #5344.

**Comment by 2hwk** [comment]
Note: A good opportunity to make use of utilities first introduced in #5261

**Comment by ErickSharp** [comment]
Picking this issue up.

**Comment by ErickSharp** [comment]
> Note: A good opportunity to make use of utilities first introduced in #5261

Would you like selecting this option to bring up an in-sim notification using the utilities you implemented or would you prefer some sort of modal?
