### ISSUE TITLE
flyPad: Landing Calculator Unit Toggles

### ISSUE THREAD

**Issue by kennedy4273** [flybywiresim/a32nx#5734]
### Aircraft Version

master

### Description

Add toggles to some/all of the units in the landing calculator. For example, QNH in mb to in Hg. Big one is LDA to feet, since all the US charts reference runway lengths in feet.

Ideally this would also toggle the output into feet as well.

The kg/LB toggle could probably use the setting already present in the flyPad settings.

### References (optional)

![image](https://user-images.githubusercontent.com/89625057/131072903-b86373eb-db89-48c3-906f-db216efa8e6c.png)

### Discord Username (optional)

Kennedy#6132

**Comment by MisterChocker** [comment]
EFB should be reading which unit system is selected for the AC

**Comment by ErickSharp** [comment]
> EFB should be reading which unit system is selected for the AC

Would you prefer I add a toggle or just read the preferred unit setting?

**Comment by MisterChocker** [comment]
@ErickSharp Settings should all go into EFB.

**Comment by ErickSharp** [comment]
> @ErickSharp Settings should all go into EFB.

Yes but how should we handle picking what unit to use for the input into the calculator? Do we read strictly the preferred unit, have a toggle on the calculator, or have a toggle on the calculator with the initial value being the preferred unit?

**Comment by Benjozork** [comment]
Don't we already have a unit setting for the whole a/c...?

**Comment by Benjozork** [comment]
Here is my proposal

Read the a/c unit and provide a manual (TEMPORARY) change on the landing calc page
