### ISSUE TITLE
Issue with the shared texture of the cargo doors

### ISSUE THREAD

**Issue by Nyxtorm** [flybywiresim/a32nx#5736]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2021-08-26T10:35:24+00:00",
  "ref": "experimental",
  "sha": "14a5718876e99aefde0a96682f609f7dc2e82b99",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

The upper part of the cargo hatch uses a texture shared between the rear and front hatch.

### Expected behavior

Hatches textures should be separated

### Steps to reproduce

1. Load a flight with a texture where the hatches should be different (EasyJet with Neo logo, Vueling Disneyland 25, etc...)

### References (optional)

![textureissue](https://user-images.githubusercontent.com/20800786/131132388-333c5f95-2e16-4d67-b9b5-6d382fe61775.png)

### Additional info (optional)

Sorry for my English and if this has already been requested, I could not find an equivalent request open.

**Comment by tracernz** [comment]
Yes. I know Grinde has done some work on this. Would be a nice fix for many liveries, especially special variants.

**Comment by bouveng** [comment]
> Yes. I know Grinde has done some work on this. 

Ask him for the files, and put them in. I think his work on that part is complete.

**Comment by bouveng** [comment]
@Nyxtorm Soon™️
