### ISSUE TITLE
[REQUEST] License

### ISSUE THREAD

**Issue by scsinke** [flybywiresim/a32nx#574]
**Is your feature request related to a problem? Please describe.**

Please at a license to this project. Public repositories on GitHub are often used to share open source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.

**Describe the feature you'd like to see implemented**

Visit [creating-cloning-and-archiving-repositories](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository) and choose a possible license

**References**

**Additional context**

**Comment by maniuraPL** [comment]
Pull request with MIT License submitted

**Comment by dancek** [comment]
I strongly agree.

There are two difficulties, though:
- A lot of the content is copied from MSFS and as such cannot be relicensed. Even redistributing as is done in this repo might be technically illegal.
- There are already 51 contributors and every one of them must give explicit permission to license their contributions.

IMHO it would be best to explicitly specify that the original files are Copyright 2020 Microsoft (or Asobo, I'm not sure). And the modifications should be licensed under a specific FLOSS license, e.g. MIT.

If redistributing ever becomes a problem, distributing a set of patches that must be manually run should be legal. I've done that for a mobile game in https://github.com/dancek/re-retry , though considering the hoops that must be jumped I don't think I have any users.

**Comment by scsinke** [comment]
I don't know if this is possible. But maybe we can separate the msfs content from the newly created content? This way the new content can be MIT while the MSFS content can be a relicensing issue.

**Comment by Benjozork** [comment]
One of our medium-term plans (as I have hard, I am not a project leader) is to move entirely to our own code.

**Comment by wpine215** [comment]
Done.
