### ISSUE TITLE
cFMS did not respect waypoint constraint 

### ISSUE THREAD

**Issue by lab44Hub** [flybywiresim/a32nx#5744]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2021-08-26T10:35:24+00:00",
  "ref": "experimental",
  "sha": "14a5718876e99aefde0a96682f609f7dc2e82b99",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

The A/C was in a managed decent, it descended beyond the constraints set in the cFMC for the STAR. 

### Expected behavior

In managed mode the A/C FMC should respect the constraints as set

### Steps to reproduce

EGKK to EHAM
ILS6
REDF1A 

At SUGOL the A/C descended beyond the constraints set in the cFMS, as pictured. 

### References (optional)

![FlightSimulator_2021-08-29_11-39-18](https://user-images.githubusercontent.com/26007462/131247621-0c3eb8f9-9166-4cd0-aa4b-97e090177920.jpg)
![FlightSimulator_2021-08-29_11-39-29](https://user-images.githubusercontent.com/26007462/131247622-dab78ec3-3914-449b-922e-cc404ce81b79.jpg)
![FlightSimulator_2021-08-29_11-39-23](https://user-images.githubusercontent.com/26007462/131247623-11c6663f-a7fd-46d2-8dbf-1c374ce86958.jpg)

### Discord Username (optional)

DamianVanDoom#5760

**Comment by Benjozork** [comment]
There are no VNAV features yet, and as the documentation says, issues are not taken on GitHub for experimental
