### ISSUE TITLE
Fps drop from com 2 to com 1

### ISSUE THREAD

**Issue by thomazz123** [flybywiresim/a32nx#5748]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-26T23:08:19+00:00",
  "ref": "master",
  "sha": "55913173181c1e528a2d3d4f77cb42558f7c2d84",
  "actor": "tracernz",
  "event_name": "manual"
}
```

### Describe the bug

Extreme fps drop from com2 to com1. Going from 40's to 10's.

### Expected behavior

Switching between com2 to com1 should be no fps drop.

### Steps to reproduce

crusing at fl370 during the day, either significant cloud coverage under or scatter clouds, either or same fps drop

**Comment by EisernUnion** [comment]
Observed it today, too ... after landing at an airport, i had problems with activationg com 1 ... no atc voices;... after switching to com 2 for the next leg and shortly before landing; i got to work... the whole sim performance droped .... it felt like when pc is runing on low memory.... (but it wasnt low... around 40%)...

**Comment by derl30n** [comment]
Closing since no response from op
