### ISSUE TITLE
TA ONLY displays wrong

### ISSUE THREAD

**Issue by DomWin02** [flybywiresim/a32nx#5750]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2021-08-26T10:35:24+00:00",
  "ref": "experimental",
  "sha": "14a5718876e99aefde0a96682f609f7dc2e82b99",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

TA Only in ND is not correct

### Expected behavior

not real

### Steps to reproduce

turn on TCAS

### References (optional)

![20210829225612_1](https://user-images.githubusercontent.com/88674959/131265395-88f6879b-f11c-4232-9ad1-96392c11385d.jpg)

### Discord Username (optional)

DomenicHAJ#0457

**Comment by Benjozork** [comment]
Re-open when proper explanations of what you think is inaccurate and proof to back it up are provided.

**Comment by BlueberryKing** [comment]
The experimental branch is very much work in progress, so there is no need to provide bug reports. Check this out: https://docs.flybywiresim.com/fbw-a32nx/support/exp

**Comment by tracernz** [comment]
If you're talking about the horizontal alignment, it is correct. When ATSAW is installed the left half of this line is used for TCAS messages and the right half for ATSAW. Without ATSAW it would be centred, as you will see on many older A320s.

Here's an example for you https://www.youtube.com/watch?v=0B1yu7Ju7fM&t=672s
