### ISSUE TITLE
Hangar views not showing correctly

### ISSUE THREAD

**Issue by ErikNL80** [flybywiresim/a32nx#5753]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-29T19:55:12+00:00",
  "ref": "master",
  "sha": "638ce34be7f6f75e1687eecec6707056687ef19e",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

I use the hangar view time to time to view newly installed liveries. With the default A320, all the views show fine, but with the A320nx you have some strange exterior views (see below).

### Expected behavior

I would expect the same views as with the default A320.

### Steps to reproduce

1. Go to your hangar
2. Select the default A320
3. Watch the views
4. Now switch to the A320nx
5. Watch the views again and notice the strange views

### References (optional)

Below some screenshots:
![001](https://user-images.githubusercontent.com/71258178/131348588-f03182bb-0987-464f-b4e0-d9525276992b.png)
![002](https://user-images.githubusercontent.com/71258178/131348595-088873ea-43c7-4825-a51e-12da91e4ef96.png)

**Comment by latamsimpilot** [comment]
Same problem here. I have tried uninstalling and installing again. Once i formatted the pc and installed everything again, and problem persist. Development or experimental version. Havent tried stable one.
![image](https://user-images.githubusercontent.com/92053621/136264370-a06ae165-ab6d-497b-bc34-8cc399037ca0.png)


{
  "built": "2021-10-03T13:38:40+00:00",
  "ref": "master",
  "sha": "1322d775fb8f52e8292a141573829424901b69a6",
  "actor": "IbrahimK42",
  "event_name": "manual"
}

**Comment by derl30n** [comment]
![image](https://user-images.githubusercontent.com/1857322/162620284-13cf322c-1200-490c-ba07-5b87a7c159ae.png)
