### ISSUE TITLE
[BUG] Performance problems on latest master

### ISSUE THREAD

**Issue by UncleClapton** [flybywiresim/a32nx#576]
**Mod Version**

346891d7381de37c3b83815bcfbc95a8abd4c1ba

previous version I had where performance was "normal"
ee26bb637ddf673e3e0f340198184410677c122b

**Describe the bug**

Something has changed in the past day which has tanked GT draw time and overall performance. I seem to be much more prone to frame dips and stutter. 

**To Reproduce**

1. test fps on old version
2. test fps on new version

**Expected behavior**

stable fps

**Actual behavior**

not so stable fps

**References**

![](https://clapton.dev/u/2009/12ec4724.png)

**Additional context**

I'm making this ticket to document that something is affecting performance that was added in the past day. I'll be investigating the issue further later on, but would appreciate if others could test / confirm a difference in performance between the versions listed.

We should also probably look at performance difference between `0.2` and `master`

**Comment by UncleClapton** [comment]
Looks like the cruise page has a part in this.

having it open increases CoherentGTDraw significantly.

**Comment by NathanInnes** [comment]
Is this still an issue or has it been resolved?

**Comment by mixMugz** [comment]
6 fps now at last master.
i9900k/2080ti/32gb 
Ultra settings
https://www.youtube.com/watch?v=A-EA3hnPDO0

**Comment by MisterChocker** [comment]
using #1341 for tracking
