### ISSUE TITLE
Rotation like a rocket, Touchdown ends up with CTD

### ISSUE THREAD

**Issue by obsidian-mint** [flybywiresim/a32nx#5762]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-30T20:21:18+00:00",
  "ref": "master",
  "sha": "cd0b1351c4439e22a3a400c7dd3a973ca5adfdcb",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

Even with a nose-down pitch (pushing the sidestick [Thrustmaster T-Flight Hotas X] down) it's very hard to hold the plane on the ground -> not even reaching VR. With a extreme hard push down of the sidestick it's possible but then it's climbing extremly fast. DIRECTLY after lifting off the plane acts as normal as always, perfect pitch, trim seems to be perfect. 

That's not all. When trying to land on any runway directly after touchdown and putting the reversers the sim crashes to Desktop. Iam not sure if the CTD is in any relation to the pitch behaviours as described above but I think it has to be in mind as well. 

### Expected behavior

- I would expect the plane to takeoff smoothly at VR and so rapidly as described. 
- I would expect that the sim won't crash while touchdown at landing and putting the reversers. 

### Steps to reproduce

Provoking my Issue:
1. Simbrief-Plan (attached pdf file): 
[EDDHEDDK_PDF_1630429365.pdf](https://github.com/flybywiresim/a32nx/files/7085590/EDDHEDDK_PDF_1630429365.pdf)
2. Bring the plane up from Cold And Dark mode while standing on any Gate / Apron / Ramp. 
3. Programm the MCDU exactly like me (https://youtu.be/m7muh6cRzws)
4. Depart with TOGA

Provoking a smooth takeoff: 
1. Depart straight from any runway (only setting the altitude) with TOGA. 

### References (optional)

When it WILL happen: While TOGA Takeoff after programming my MCDU and bringing the plane up from Cold And Dark mode: 
-> https://youtu.be/m7muh6cRzws

Of course you can watch without my flight planning too: 
-> https://youtu.be/m7muh6cRzws?t=630

When it WON'T happen: Departing straight from any runway without programming my MCDU, just setting a certain altitude. Nose behaves as expected and a smooth takeoff is possible.:
-> https://youtu.be/mDlxbgHCimY

Landing on any runway causes a CTD right after touch down and setting the reversers: 
-> https://youtu.be/9g2ugiSyLec

### Additional info (optional)

- Completely reinstalled MSFS and wiped everything (APPDATA, Steam Directory and reg entries as well)
- Installed FBW via Installer (DEV)
- Community folder completely wiped (only FBW Mod)
- Graphics (high with some exceptions on middle)
- VSYNC: Off
- Flight model: Modern. 
- LiveTraffic: ON (turning off makes REALLY no difference)
- LiveWeather: ON (turning off makes REALLY no difference)
- NVIDIA drivers: Updated to last version (NOT overclocked, CPU as well)
- Evtvwr output when CTD: 

"Name der fehlerhaften Anwendung: FlightSimulator.exe, Version: 1.18.15.0, Zeitstempel: 0x00000000
Name des fehlerhaften Moduls: FlightSimulator.exe, Version: 1.18.15.0, Zeitstempel: 0x00000000
Ausnahmecode: 0xc0000005
Fehleroffset: 0x0000000000925a4b
ID des fehlerhaften Prozesses: 0x60a8
Startzeit der fehlerhaften Anwendung: 0x01d79e5ffcff5063
Pfad der fehlerhaften Anwendung: E:\SteamLibrary02\steamapps\common\MicrosoftFlightSimulator\FlightSimulator.exe
Pfad des fehlerhaften Moduls: E:\SteamLibrary02\steamapps\common\MicrosoftFlightSimulator\FlightSimulator.exe
Berichtskennung: 1f5eecef-8cdb-4d99-84d6-922acd8713d5
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist" -> ERROR-ID: 1000

- Peripherals: Thrustmaster T-Flight HOTAS X
- Calibrated on DEV: YES
- NVIDIA System-Information: 
[NVIDIA System Information 08-31-2021 19-17-45.txt](https://github.com/flybywiresim/a32nx/files/7085690/NVIDIA.System.Information.08-31-2021.19-17-45.txt)

If i forgot anything please let me know. My english ist not the best but i think we will come together. 

### Discord Username (optional)

kaeptn_baloo

**Comment by obsidian-mint** [comment]
-> Hint: If you watch closely you can see my first waypoint is a USR waypoint -> could this cause my problems? nevery tried to kill those waypoints.

**Comment by sidnov** [comment]
Seems to be a wrong axis binding with the pitch trim as it can be seen moving with rudder movement. Also, 8.6UP is drastic 
![image](https://user-images.githubusercontent.com/29005005/131549963-03a67bfa-0538-49e5-ae54-47cf2e93e018.png)


Try looking for any conflicting bindings in the MSFS Controls settings, such as "Pitch trim"

**Comment by obsidian-mint** [comment]
> Seems to be a wrong axis binding with the pitch trim as it can be seen moving with rudder movement. Also, 8.6UP is drastic
> ![image](https://user-images.githubusercontent.com/29005005/131549963-03a67bfa-0538-49e5-ae54-47cf2e93e018.png)
> 
> Try looking for any conflicting bindings in the MSFS Controls settings, such as "Pitch trim"

-> will give it a try! thanks in advance!

**Comment by obsidian-mint** [comment]
@sidnov you are completely right. The trimming value depends on how i move the rudder... damn i didn't notice that. will check the bindings and will give feedback!
https://youtu.be/hMWZg9irXIs

**Comment by obsidian-mint** [comment]
@sidnov that did the trick! Thank you so much! Even the CTD's at appoaches (landing) are gone now! You saved me so much time, have a nice day!

**Comment by sidnov** [comment]
> @sidnov that did the trick! Thank you so much! Even the CTD's at appoaches (landing) are gone now! You saved me so much time, have a nice day!

Glad it helped! :)
