### ISSUE TITLE
Chrono RST switch should be spring loaded

### ISSUE THREAD

**Issue by St54Kevin** [flybywiresim/a32nx#5766]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2021-08-31T04:29:40+00:00",
  "ref": "experimental",
  "sha": "5cb4212a6fa7af59e0241164a4da99091998cd44",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

The switch for the chrono timer reset currently is a permanent switch position.

### Expected behavior

The switch for the chrono timer reset should be a momentary, spring loaded switch position. So when turning the switch to the RST position it should spring back to the STP position.

### Steps to reproduce

1. Turn chrono timer switch to RST.
2. switch stays at this position

### References (optional)

![image](https://user-images.githubusercontent.com/448627/131652958-089fd7dc-06c3-44cd-9791-adc826808187.png)

**Comment by AirbusA320Pro** [comment]
Can confirm, RST switch is sprung loaded in the real aircraft as per the bug description.
