### ISSUE TITLE
APU not starting after dual engine shut down, in flight.

### ISSUE THREAD

**Issue by georgea04** [flybywiresim/a32nx#5767]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-31T22:01:26+00:00",
  "ref": "master",
  "sha": "3da40053b6e34d2803ff4fbb80bde5f85007ce60",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

Hi! Not sure if I'm doing something wrong, but the APU won't start in the case of a dual engine failure IN FLIGHT. In my first video, I show that the APU starts perfectly fine when the engines are on, and then in my second video, I show that the APU will not start after having switched the engines off.
I communicated with @Cdr_Maverick#6475 on Discord (support tab), and he checked that I wasn't starving it of fuel, or leaving the batteries off (which I'm not). Not sure what else I should do. Hope I'm posting this in the right section. Videos attached.

https://user-images.githubusercontent.com/89860540/131679111-18391347-1c25-4f91-ae2d-d6d9b69cb793.mp4

https://user-images.githubusercontent.com/89860540/131680672-52566dd6-d772-4412-98c7-a70ed7680659.mp4

### Expected behavior

APU should start when both engines are off, in flight.

### Steps to reproduce

1. Get airborne in the FBW A320.
2. Switch off both engines and wait a minute or so.
3. Try and start APU. The master switch comes on, but it won't start.

### Additional info (optional)

Works in the Asobo A320 and in stable version of FBW's.

### Discord Username (optional)

georgea#9644

**Comment by davidwalschots** [comment]
The APU requires batteries to be connected to the DC BAT BUS to start. There are constraints on when the batteries are connected to the DC BAT BUS. When in an EMER ELEC situation like in your second video, the batteries are only connected to the DC BAT BUS when the gear is up and locked, which isn't the case here and thus causes you to be unable to start the APU. Please take a look at #3625 to see the other conditions that apply.
