### ISSUE TITLE
SRS/GA TRK issues

### ISSUE THREAD

**Issue by 2hwk** [flybywiresim/a32nx#5771]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2021-09-02T03:35:34+00:00",
  "ref": "HEAD",
  "sha": "ad8d4b1549903ba9727ac33e46b6c9a6178ade25",
  "actor": "Benjamin Dupont <benjozorkfr@gmail.com>",
  "event_name": "manual"
}
```

### Describe the bug

On final approach, when MAN TOGA is entered for a moment and SRS GA/TRK is shown as engaged on the PFD, (i.e. autoflight has placed us into a go-around state) the MCDU will still show the current phase as approach even though GO AROUND has been initiated. 

To correct the abnormal state, you have to place the thrust lever to select TOGA power until GO AROUND is displayed on the MCDU.

### Expected behavior

FMA and FMGC should agree on the current flight phase, aka PFD and MCDU should indicate the go around state.

### Steps to reproduce

1. Push throttle lever to TOGA for a moment (very quickly), before returning to the CLB detent. 
2. MAN TOGA will flash, then SRS/GA TRK will activate, observe the PFD. 

To ensure that the exact condition has been reproduced, ensure that the MCDU does NOT show the current phase as GO-AROUND.

### References (optional)

https://clips.twitch.tv/SpeedyEnchantingTarsierKippa-TzE4NnovTbgv2C4a

### Additional info (optional)

 Yet to personally reproduce. See VOD. 

### Discord Username (optional)

2Cas#1022

**Comment by donstim** [comment]
Would you be able to provide a video (showing the cockpit) of this occurring?  Using the info you provided in "Steps to reproduce," I could not do it. When I disconnected autothrust, the FMA thrust designation went to a flashing THR LCK indication as expected.  See https://1drv.ms/v/s!Ajsy7Ey4_8uFz2NMnD-TCTzLRtp1?e=RYvcdb
