### ISSUE TITLE
ILS Manual Tuning Ident + Course

### ISSUE THREAD

**Issue by G3NSVRV** [flybywiresim/a32nx#5788]
I was trying to configure the ILS for approach and this same happened to me:

https://github.com/flybywiresim/a32nx/issues/2273

I was trying to configure ICEP and ICEP/109.9 but I got "NOT ALLOWED"; I also tried with 02 and 02Y and it says "OUT OF RANGE".

The only way that I can barely configure is specifying only the freq.

This is for SCIE ILS Y RWY 02
![image](https://user-images.githubusercontent.com/11720535/132164863-6c3798a8-ed76-42b6-9767-65e9b1ede353.jpeg)

**Comment by tracernz** [comment]
That is correct. There is no way to directly retreive an ILS frequency by ident with the MSFS navdata API. You can either enter the frequency, or select the ILS approach in the F-PLN and it will be auto-tuned. Not sure what RNAV has to do with it though.

**Comment by G3NSVRV** [comment]
@tracernz well, I configured the approach on the flight plan but it didn't fill out the radio nav page

**Comment by tracernz** [comment]
At which stage of the flight are you checking to see if it's auto-tuned?

**Comment by G3NSVRV** [comment]
@tracernz arrival on dest

**Comment by tracernz** [comment]
> 
> 
> @tracernz arrival on dest.

Works okay for me with Navigraph data. Are you using MS or Navigraph navdata? Possible there is a coding error.
![image](https://user-images.githubusercontent.com/9995998/132278936-988a32fd-fe51-4d03-a439-c66d9fa58fe6.png)

> the problem also is that I cannot configure the CRS properly, on this case it says 20º and on the MCDU is grey

It is not implemented correctly ATM... in the future it is entirely replaced with some work I have in progress...

**Comment by G3NSVRV** [comment]
@tracernz im not sure, im using the default, probably MS... btw, once I arrive to the ILS broadcast, it fixes the name automatically but not the CRS. I will try next time using navigraph data.

**Comment by tracernz** [comment]
> 
> 
> @tracernz im not sure, im using the default, probably MS... btw, once I arrive to the ILS broadcast, it fixes the name automatically but not the CRS. I will try next time using navigraph data.

I can check the default data. As I said, we will make some improvements in due course r.e. manual tuning by ident and setting course.

**Comment by G3NSVRV** [comment]
> -e- Wait... how did you create this issue without filling out the template... and what version of A32NX are you using? If you're using the old stable version (0.6.3) that explains why it doesn't tune automatically...

@tracernz I'm using the Latest Stable:
```json
{
  "built": "2021-08-09T18:57:24+00:00",
  "ref": "v0.6.3",
  "sha": "7222a9516e4114742a7fec84080a2f63ea527428",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

**Comment by tracernz** [comment]
Try the dev or experimental versions. The autotuning is much improved in those already.

**Comment by Valastiri** [comment]
@G3NSVRV 

Can you please provide a screenshot of your sim version? And are you on our Discord by any chance?

**Comment by G3NSVRV** [comment]
I’m using the newer, it got updated yesterday. I’m on discord but since I don’t have my phone number on it I cannot interact with the server.

Kind Regards,
Jonathan Garces

On 08-09-2021, at 9:27 AM, Val ***@***.***> wrote:

﻿

@G3NSVRV<https://github.com/G3NSVRV>

Can you please provide a screenshot of your sim version? And are you on our Discord by any chance?

**Comment by telumletiferum** [comment]
@G3NSVRV So this bug is kinda interesting. So far, right now, I suggest you just put the ILS freq and leave it be for the flight. At around 25 NM the plane will grab the signal of the ILS and show it in the PFD if you have LS turned on. That's how I do it. If you try to properly configure it by typing ICEP/109.90, it will always say "NOT ALLOWED", so for now you just have to put the freq or just leave the ILS tuning to the plane, it usually sets it automatically.

**Comment by G3NSVRV** [comment]
> @G3NSVRV So this bug is kinda interesting. So far, right now, I suggest you just put the ILS freq and leave it be for the flight. At around 25 NM the plane will grab the signal of the ILS and show it in the PFD if you have LS turned on. That's how I do it. If you try to properly configure it by typing ICEP/109.90, it will always say "NOT ALLOWED", so for now you just have to put the freq or just leave the ILS tuning to the plane, it usually sets it automatically.

yup, that's what I do now, it got autofilled when I'm close to the airport.

**Comment by tracernz** [comment]
> If you try to properly configure it by typing ICEP/109.90

You can tune _either_ the frequency or the identifier, not both. Tuning the identifier doesn't yet work in the dev version...

**Comment by G3NSVRV** [comment]
> > If you try to properly configure it by typing ICEP/109.90
> 
> You can tune _either_ the frequency or the identifier, not both. Tuning the identifier doesn't yet work in the dev version...

For me it only works with the frequency, not the identifier.
