### ISSUE TITLE
A32NX aircraft model do not display in game after MSFS 1.19.80 update

### ISSUE THREAD

**Issue by cqhhy2001** [flybywiresim/a32nx#5793]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-08-09T18:57:24+00:00",
  "ref": "v0.6.3",
  "sha": "7222a9516e4114742a7fec84080a2f63ea527428",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

A32NX aircraft model dose display in game after MSFS 1.19.80 update
![image](https://user-images.githubusercontent.com/21079967/132442886-d2dda863-c667-4599-86e7-694849988e44.png)

### Expected behavior

it should be displayed correctly since FWBA32NX is  an aircraft model mod

### Steps to reproduce

start the flight as normal.

**Comment by Benjozork** [comment]
Uninstall and reinstall the aircraft

**Comment by cqhhy2001** [comment]
> Uninstall and reinstall the aircraft

I have reinstalled when I encountered the problem, and the problem remains

**Comment by Benjozork** [comment]
Make sure to remove any removable marketplace versions from the Content Manager.

**Comment by cqhhy2001** [comment]
Thank you, the problem has been resolved.
What happened to the Marketplace version of A32NX? Has it been deprecated?

**Comment by sidnov** [comment]
> What happened to the Marketplace version of A32NX? Has it been deprecated?

Yes. For now, the installer is the most viable way to download the aircraft, and we recommend the development version since it gets updated quite frequently.

Closing as issue is resolved
