### ISSUE TITLE
Save throttle/detent calibration to file (or give instructions for how to create file)

### ISSUE THREAD

**Issue by Altycoder** [flybywiresim/a32nx#5798]
### Aircraft Version

Development

### Description

In the throttle/detent calibration page in the flypad there is an option to load a calibration from file, but no option to save to a file; and I can't find any instructions for how to create a calibration file by hand.

I've had to recalibrate my throttle a few times now after moving back and forth between stable and development versions (and possibly even with new development versions overwriting the values?) so being able to import a file would be excellent.

**Comment by tracernz** [comment]
That is exactly what happens when you press save. The file is saved to the "work" directory, the only location that can be written, which for me with the steam edition is `%APPDATA%\Microsoft Flight Simulator\Packages\flybywire-aircraft-a320-neo\work\ThrottleConfiguration.ini`.

**Comment by Altycoder** [comment]
OK great, I didn't come across anywhere that was documented. I wanted to copy the file so I could re-load it in the future
