### ISSUE TITLE
Real Life A320 Sound Pack

### ISSUE THREAD

**Issue by DemonRem** [flybywiresim/a32nx#5799]
### Aircraft Version

Stable

### Description

hey guys i would like to know how i can replace the current GPWS Flight Computer
sounds i have a real life sound of the a320 direct from the cockpit

### Discord Username (optional)

#Katrin7037

**Comment by hotshotp** [comment]
Can you please elaborate? You are on stable which is months out of date. However in both development and experimental versions all the aircraft warnings have been completely replaced from their asobo counterparts with real recordings. I suggest you try that version.

**Comment by DemonRem** [comment]
ok thanks

**Comment by DemonRem** [comment]
ya know this version fucked all the aircraft moving a bit the thorttle bring it to toga on a taxi
i just asked how to edit the sound pack but i already get my answer thanks for microsoft
i revert the aircraft to stable version

**Comment by aguther** [comment]
On development you need to calibrate your throttles.

**Comment by NUTTTTTTTT** [comment]
I suggest following the development calibration guide: https://docs.flybywiresim.com/fbw-a32nx/feature-guides/flyPad/throttle-calibration/
