### ISSUE TITLE
[BUG] LDG LT MEMO

### ISSUE THREAD

**Issue by becas22** [flybywiresim/a32nx#580]
**Mod Version**

**Describe the bug**

**To Reproduce**

1.Turn ON LDG LTs
2.Retract both LDG LTs

**Expected behavior**

**Actual behavior**

**References**

![image](https://user-images.githubusercontent.com/11005754/92791079-440b5180-f3a4-11ea-9fb4-3a6999a5638e.png)
DSC-33-20-20

**Comment by lukecologne** [comment]
Looking into this. Is the message also displayed if the Nose light is on takeoff position? (IRL i mean)

**Comment by PCGamesF1Tech** [comment]
Hi,
there's no indication for the taxi or takeoff light other than it just stays dark outside... 😉

**Comment by becas22** [comment]
> Looking into this. Is the message also displayed if the Nose light is on takeoff position? (IRL i mean)

No, nothing for those.

**Comment by lukecologne** [comment]
Great, that's how I implemented it, so it is correct now
