### ISSUE TITLE
FBW A320

### ISSUE THREAD

**Issue by Schobukan** [flybywiresim/a32nx#5802]
### Aircraft Version

Development

### Build info

```json
0.6.3
```

### Describe the bug

Since the new Ms2020 update the Airbus is not showing in the hangar. i can load it but there is no Aircraft showing

### Expected behavior

fix that problem pls

### Steps to reproduce

deleted the installer

### Additional info (optional)

i delet the aircraft from community folder
i delet the installer
reintalled the aircraft with the installer but its not in the sim

### Discord Username (optional)

Schobukan

**Comment by Pat15250** [comment]
Hi,

Here is the solution:
1. Open Fly By Ware Simulation installer.
2. Click on Settings
3. On settings, click on "Reset settings to default"

After that it should find the correct directory to install the aircraft.

After that, I advice you to close the installer, restart the computer, and re-install fly by ware by running fly by ware installer.
Normaly, by following those steps, you should find the Airbus in the hangar.

I had exactly the same problem, and now it works fine for me.

Patrick

**Comment by NUTTTTTTTT** [comment]
You need to go to the content manager from the main menu, search A32NX and remove any old versions, you may have one in the content manager and another in community folder, delete all of them. Once done load back up, search for A32NX again and make sure there is no FBW aircraft at all showing in the sim. Then reinstall via the installer and ensure it's installed to the correct community folder. :)

**Comment by walouigi** [comment]
Thank you guys, that worked for me :)
