### ISSUE TITLE
[BUG] Incorrect VMO

### ISSUE THREAD

**Issue by becas22** [flybywiresim/a32nx#581]
**Mod Version**

MASTER

**Describe the bug**

VMO has wrong value

**Expected behavior**

VMO is displayed at 350kts.

**Actual behavior**

VMO is displayed at 360kts.

**References**

![image](https://user-images.githubusercontent.com/11005754/92791613-b7ad5e80-f3a4-11ea-9628-d9be2bb4b352.png)
![image](https://user-images.githubusercontent.com/11005754/92791630-bc721280-f3a4-11ea-8d09-67e633bfea5e.png)

**Comment by PCGamesF1Tech** [comment]
Also see #238

**Comment by AdenFlorian** [comment]
working on a fix
