### ISSUE TITLE
Changing wind speed/direction critical autopilot issue

### ISSUE THREAD

**Issue by sebby1983** [flybywiresim/a32nx#5817]
### Aircraft Version

Experimental

### Build info

```json
Experimental
```

### Describe the bug

Whilst climbing out of BIKF in changing strong wind speeds between FL220 and FL320 the autopilot over corrects throwing the aircraft into an uncontrollable dive. I have replicated this 4 times. Ailerons shift from full left to full right continuously.

### Expected behavior

Minor aileron adjustment to counteract wind

### Steps to reproduce

Climb out of BIKF on  OSKUM3C to Ratsu climbing to FL390 with autopilot engaged in current strong winds

### Discord Username (optional)

Sebby1983

**Comment by aguther** [comment]
Duplicate of #5820
