### ISSUE TITLE
First load of aircraft always has a high fuel load. Request a lower value

### ISSUE THREAD

**Issue by N1EL** [flybywiresim/a32nx#5828]
### Aircraft Version

Development

### Description

Would it be possible to ha e a random initial fuel load that is more realistic than we currently get.  which usually is quite high and in most of my flights require a defuel which doesn't happen very often at all IRL.

A random fuel level of say between 2000 KG and 4000KG would be great.

### Discord Username (optional)

Neil_M_UK#7250

**Comment by Prescia** [comment]
This is not a bug, all aircrafts start with 50% fuel if you do not set them before loading.

**Comment by N1EL** [comment]
Sorry this wasn't meant to be an issue but a enhansment request.  But the knowledge of it be set at 50% would explain why its not that realistic then.

Could the figure be lowered a little so I actually have to load fuel and not defuel?? Wouldn't 25% be more likely?

**Comment by tracernz** [comment]
> 
> 
> Sorry this wasn't meant to be an issue but a enhansment request. But the knowledge of it be set at 50% would explain why its not that realistic then.
> 
> Could the figure be lowered a little so I actually have to load fuel and not defuel?? Wouldn't 25% be more likely?

You are the one that decides the initial load, in the MSFS aircraft selection screen. This is not a function of the A32NX.

**Comment by N1EL** [comment]
Yes I agree.   But then why have the EFB to add fuel then if the screen does it. 

The fact the 320NX can interact with the fuel load and able to refuel via the EFB it would be a shame to resort to the MSFS loading screen to change the values you start at. I get its there to do it but just seems a step backwards.

As I say it was an idea to make it more realistic.

But if those that control what is added and what's not arnt able to move it to say 25% or feel it should be moved  
then no harm done.

**Comment by 2hwk** [comment]
> Yes I agree. But then why have the EFB to add fuel then if the screen does it.
> 
> The fact the 320NX can interact with the fuel load and able to refuel via the EFB it would be a shame to resort to the MSFS loading screen to change the values you start at. I get its there to do it but just seems a step backwards.
> 
> As I say it was an idea to make it more realistic.
> 
> But if those that control what is added and what's not arnt able to move it to say 25% or feel it should be moved
> then no harm done.

If we did this it would be overriding the default menu, which now would not work, which would confuse people who do use the menu. When we overhaul the fuel system we may do this, but it does not make sense to do this right now when it would be a trade-off of making some users happy over others, it has to be an improvement for everyone. 

If you desire realistic fuel loads on setup I suggest using simbrief to generate a OFP then load in payload/fuel on cockpit prep, or setting it in the default menu before spawning in.

**Comment by N1EL** [comment]
Ok understood.   Thanks.

**Comment by Prescia** [comment]
> Yes I agree. But then why have the EFB to add fuel then if the screen does it.
> 
> The fact the 320NX can interact with the fuel load and able to refuel via the EFB it would be a shame to resort to the MSFS loading screen to change the values you start at. I get its there to do it but just seems a step backwards.
 
The EFB is just a fancy/more realist way to interact with it, you can still also change fuel quantity on the overhead bar menu at any flight time.

> As I say it was an idea to make it more realistic.

I don't get how it is more realist to set a random amount of fuel every time you start. In reality, pilots will already have calculated how much fuel they need and requested beforehand (if first trip of the day) or request the fuel truck on tarmak. In no way a random amount is realist, pilots don't drop by with no clue unless in emergencies, even in pilot rotation the fuel for the next trip is already calculated and set, if the next pilot wants to change it he can ask for fuel, no random stuff going on.

**Comment by N1EL** [comment]
> The EFB is just a fancy/more realist way to interact with it, you can still also change fuel quantity on the overhead bar menu at any flight time.
Yep, That's why I prefer not to use the overhead bar. So as you say the EFB is more realistic.

> I don't get how it is more realist to set a random amount of fuel every time you start. In reality, pilots will already have calculated how much fuel they need and requested beforehand (if first trip of the day) or request the fuel truck on tarmak. In no way a random amount is realist, pilots don't drop by with no clue unless in emergencies, even in pilot rotation the fuel for the next trip is already calculated and set, if the next pilot wants to change it he can ask for fuel, no random stuff going on, and hardly any pilot will request a fuel drop if there is more than what he wants on the tanks.

You said yourself the fuel would request beforehand and the fuel normally loaded when then crew on site.
My point about it being realistic is that the crew would request fuel to be added not removed.
So an aircraft with 2000-4000kg on it when you arrive at the aircraft and having it refuelled is more realistic than an aircraft with 50% fuel and Defuelling it.

The random side of things was to give a realistic fuel load that would find the aircraft at before refuelling, at the lower end so then you will always take fuel on.   
It doesn't have to be random just 25% instead of 50% would mean you always have to load fuel and never remove fuel.

As I said this was an idea based on making an enhancement,

**Comment by Prescia** [comment]
That has nothing to do with A32nx, is not realistic but rather a personal opinion, and can still be done in 3 different ways ingame.

**Comment by N1EL** [comment]
Ok Well I will just adapt change my OFP off block fuel to the value of fuel loaded if there's is more fuel than I need.

If there's more fuel needed I just load it.

I don't think you understand what I asking for but thanks for the discussion about it.

**Comment by N1EL** [comment]
It looks as those its not possible to do this enhancement thanks for the discussion I will close this request 

Thank You.
