### ISSUE TITLE
Disable Pilot Voice

### ISSUE THREAD

**Issue by zoideberg8000** [flybywiresim/a32nx#5834]
### Aircraft Version

Development

### Description

Is it possible to disable the pilot voice (flight attendants please prepare for landing)? I checked here and on discord but couldn’t find if it’s possible.

**Comment by TLSY2** [comment]
the old voice was better

**Comment by bouveng** [comment]
This will be a setting soon, to be able to choose, and perhaps disable completely.
@hotshotp ?

**Comment by hotshotp** [comment]
Yes exactly. In the near future.

**Comment by ErickSharp** [comment]
This will be coming to the efb soon as a part of an overall bundle of more sound settings.

**Comment by derl30n** [comment]
![image](https://user-images.githubusercontent.com/1857322/162619948-36db1726-b9e3-413b-a003-e00d33b7678a.png)
