### ISSUE TITLE
[BUG] Background below TERR ON ND button is flickering in flight

### ISSUE THREAD

**Issue by furukama** [flybywiresim/a32nx#584]
**Mod Version**

0.2.0

**Describe the bug**

TERR ON ND button seems to have transparent space below (or not properly aligned), so the background world textures seem to flicker behind it whenever the plane rolls from side to side.

**To Reproduce**

1. Fly by day. Zoom in to front instrument view and watch TERR ON ND button

**Expected behavior**

Background should stay the same.

**Actual behavior**

Background is flickering.

**References**

**Additional context**

**Comment by MisterChocker** [comment]
seems to be no longer existent
