### ISSUE TITLE
Freezes when you press the redey to Fly button

### ISSUE THREAD

**Issue by teru5601** [flybywiresim/a32nx#5845]
### Aircraft Version

Stable

### Build info

```json
Ver 0.7.0
```

### Describe the bug

When you press the redey to fly button at the start of the game, it will move to the takeoff airport and freeze.

### Expected behavior

Normal flight start

### Steps to reproduce

When doing a free flight using fly-by-wire a32NX on a world flight
Always occur every time

**Comment by JRH3221** [comment]
You could turn on developer mode and get some info from how your hardware is managing, and send the what comes up in the console when your game freezes.

**Comment by teru5601** [comment]
Development mode is also unavailable due to freeze

**Comment by astthecat** [comment]
Same issue here. Started happening after updating to the latest nvidia driver, updating msfs and the FBW A32NX mod. All of this happened on yesterday. No idea which one causes the CTD. The outside "showcase view" of the aircraft is fine until you press the Ready to Fly button. As soon as the game puts you in the cockpit, it freezes and CTDs after a few minutes of hanging.

**Comment by frankkopp** [comment]
We had success with a user reverting back to an older gfx driver. 
Maybe worth giving it a try report back here.
NVidia 471.96

**Comment by astthecat** [comment]
Sadly no driver downgrading, nor a complete reinstall of the game helped. Clueless about this.

**Comment by teru5601** [comment]
I am currently flying with FBWA32NX Ver0.6.3.
I hope it will be improved.

**Comment by ThunderDan97** [comment]
I experienced the same issue since 0.7.0 on a full AMD setup, it was loading way too long & after klicking "ready to fly" the game freezed within the very first frames - i switched the stable/dev versions around several times & upgraded the gpu driver (Adrenalin 21.8.2) and now it's already crashing on the loading screen. It loads several minutes, then the task dies while it starts to reserve all the RAM available to MSFS. Also, in the stable version the plane is invisible in the hangar view from what i've experienced.

**Comment by frankkopp** [comment]
> I am currently flying with FBWA32NX Ver0.6.3.
> I hope it will be improved.

Current Stable version is 0.7.0, current Development is 0.8.0-dev ==> please update.

**Comment by frankkopp** [comment]
> I experienced the same issue since 0.7.0 on a full AMD setup, it was loading way too long & after klicking "ready to fly" the game freezed within the very first frames - i switched the stable/dev versions around several times & upgraded the gpu driver (Adrenalin 21.8.2) and now it's already crashing on the loading screen. It loads several minutes, then the task dies while it starts to reserve all the RAM available to MSFS. Also, in the stable version the plane is invisible in the hangar view from what i've experienced.

That last issue (invisible plane) is probably independent: https://docs.flybywiresim.com/fbw-a32nx/support/reported-issues/#installation-version-conflicts.
Raise this in the Discord #support channel if you need help.

**Comment by derl30n** [comment]
Has this issue been resolved?

**Comment by frankkopp** [comment]
> Has this issue been resolved?

You can close this
