### ISSUE TITLE
automatical simrate reduce mechanism not optimal

### ISSUE THREAD

**Issue by mihunet** [flybywiresim/a32nx#5849]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-09-18T17:47:55+00:00",
  "ref": "master",
  "sha": "363a5fac10e2790fa29ee9628c62a0fa8f742cd4",
  "actor": "sidnov",
  "event_name": "manual"
}
```

### Describe the bug

Since the introduction of the automatic reduction of the simualtion rate from 4x -> 2x -> 1x, the use of higher rates is no longer possible in a meaningful way. 

I have a high performance setup 
i7-10000k @ 5.2
rtx3080 @ 60fps stable @ ultra

In a longer test I noticed that in different situations e.g. ATC requests or every few minutes it comes to small frame drops. This causes the reduction of the newly implented mechanism. Despite this, the frame rate is on average around 60fps. 

### Expected behavior

The use of a maximum sim rate of 2x / 4x , or at least have the decision to use it. 

I understand the reason behind it, but at least more experienced users should be given the opportunity to use this feature, even if it could cause performance problems. 

### Steps to reproduce

1. full flight EGPE -> ENAT
EPGE DCT PIPEM L613 BAMRA DCT RIXUN/M079F370 DCT BARUD/N0452F370 DCT NOGBO/N0447F390 T65 GILEN DCT BDF Z205 BADIX BADI1Q ENAT
2. multiplayer live & 3. weather disabled (clear sky)
3. using 4x over the sea between UK and Norway

### Additional info (optional)

I never had problems with the higher sim rate (max. 4x). Never oszilation or other issues. 

### Discord Username (optional)

MIHU#8724

**Comment by YuTookMyJob** [comment]
I use FS SimRate Bandit on long haul flights and the sim rate reduction mechanism is highly annoying. It would be handy for it to be an optional setting as I also haven't had issues at sim rate 4

**Comment by sidnov** [comment]
A recent update to the addon is causing this bug. It is not an intentional change and will be fixed eventually.

**Comment by aguther** [comment]
Luke made an adjustment to the algorithm to make it less aggressive, but we had also reports from people complaining about performance and oscillations from the AP and it‘s just not easy to solve that with a very low frame rate (as seen by the AP/FBW in case of time compression).

What can be an option is that the reduction mechanism is turned off via config file so advanced users can do that. Same is for the maximum already implemented, it can be changed via config file but is then your own responsibility.

Overall this is needed for less experienced users to reduce the chance that they run into any issues.

**Comment by mihunet** [comment]
Sure, it's understandable, I've been following the issue with the AP for a while and surely it's better to regulate this to ensure a reliable use for everyone. Especially since there is such a heterogeneous amount of HW setups out there from low to high end. 

The possibility to regulate this in a config-file, of course at your own risk, sounds like a great approach. So everyone can decide this for themselves. 

But in any case great that you treat the topic so quickly.

**Comment by stmihajlo** [comment]
Which config file and which line exactly do I need to change to remove the sim rate reduction mechanism? As I understand why it's implemented but personally I don't like the restriction.

**Comment by aguther** [comment]
It‘s not yet implemented.

**Comment by stmihajlo** [comment]
Thanks for answering that fast! I suppose I'll have to wait for it then. Take your time!
P.S. Thanks for making such a great aircraft for us! I'm really satisfied what we allready have :D

**Comment by runningdavid** [comment]
About every minute or so a loading spin icon appears at the bottom right of my sim which cause the FPS to drop temporarily as MSFS is loading some data I believe. The auto sim rate kicks in everytime and reduced my sim rate, so I have to manually increase it 
every minute. Please have an option to disable it soon, thanks!

**Comment by mihunet** [comment]
A PR to solve this problem is already in development. Please be patient, it will be released soon.

**Comment by runningdavid** [comment]
Thanks so much for the quick fix.
