### ISSUE TITLE
Workaround for lack of tiller steering

### ISSUE THREAD

**Issue by Villason** [flybywiresim/a32nx#5851]
### Aircraft Version

Development

### Description

There is no workable tiller binding in the sim. NWS is programmed with realistic angles according to pedals input. It's requested to override the realistic rudder wheel steering with tiller steering angles otherwise we cannot taxi properly.

### References (optional)

FCTM:

TILLER AND RUDDER PEDALS USE

Pedals control nosewheel steering at low speed (± 6 ° with full pedal deflection). Therefore, on straight taxiways and on shallow turns, the pilot can use the pedals to steer the aircraft, keeping a hand on the tiller. In sharper turns, the pilot must use the tiller.

### Additional info (optional)

Not being able to taxi properly is worse than not having realistic wheel steering angles with pedals input.

**Comment by ErikNL80** [comment]
Noticing the same with the TCA sidestick...

**Comment by Villason** [comment]
@MisterChocker I think we need to upgrade this to a bug introduced by pr #769.

We are having 6 degrees of steering at 40knots instead of the 37.5 degrees the real aircraft can give you.

**Comment by MisterChocker** [comment]
@Villason there is no upgrade or downgrade of issues.

This issue is a request type issue and therefore I marked it as such since the label hasn't been automatically added.
