### ISSUE TITLE
Issue with Custom Events since last DEV/Stable Version

### ISSUE THREAD

**Issue by vincenzo34** [flybywiresim/a32nx#5852]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-09-19T13:44:38+00:00",
  "ref": "master",
  "sha": "80496bdd2b5281884df0ba379713b0cefbdce7fa",
  "actor": "2hwk",
  "event_name": "manual"
}
```

### Describe the bug

Hello,

There is an issue since the last update with Custom Events ( https://docs.flybywiresim.com/fbw-a32nx/feature-guides/autopilot-fbw/#custom-events ). When a custom event is called, this calls the same event twice ... 
For example SPD_INC +2, SPD_DEC -2 ... for all events...

Tested with Spad.next.

Thx
Vincent

### Expected behavior

One event = One Call

### Steps to reproduce

With Spad.next...

Ex : 
A32NX.FCU_SPD_INC
A32NX.FCU_SPD_DEC
...
All events

**Comment by vincenzo34** [comment]
![Capture d’écran 2021-09-19 163706](https://user-images.githubusercontent.com/11474776/133932581-f01bd1b2-9f6f-411a-9c60-5f055223af7f.jpg)

**Comment by vincenzo34** [comment]
count : 2 ... for 1 call...

**Comment by vincenzo34** [comment]
The problem only seems to concern custom events and not default events ...

**Comment by aguther** [comment]
I cannot reproduce your issue, on my end it works without any issues with SPAD.neXt:
https://user-images.githubusercontent.com/6629914/134576336-1c33c926-aa5d-4b10-ab41-276850db7e4f.mp4

**Comment by vincenzo34** [comment]
Thanks you for your response.
But I can't seem to correct the problem ...
I cleanly reinstalled the DEV version of FBW.
Deleted cache files in AppDat / Roaming ...
But still the same ...
For information, spad.next works perfectly with other planes like the aerosoft CRJ ... and worked well before the stable 0.7.0 version...
Do you have an idea ?

See my video : https://www.youtube.com/watch?v=tFmfLfI4HLs

**Comment by vincenzo34** [comment]
OK issue solved !

I used this custom events : A32NX.FCU_SPD_INC from spad next profile xml : https://github.com/flybywiresim/a32nx/blob/master/docs/SPAD.neXt/flybywire-aircraft-a320-neo.xml

I switch from : SIMCONNECT FCU SPD INC and it works !!!

I think there was an interference between the SIM CONNECT events and CUSTOMS events ...

Thx you for your job !
