### ISSUE TITLE
SimRate not going over 2 and reduces to 1 after a few seconds

### ISSUE THREAD

**Issue by NEXADR** [flybywiresim/a32nx#5853]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-09-19T13:44:38+00:00",
  "ref": "master",
  "sha": "80496bdd2b5281884df0ba379713b0cefbdce7fa",
  "actor": "2hwk",
  "event_name": "manual"
}
```

### Describe the bug

When I try to use simrate while on cruise, it only goes up to 2x and after a few seconds it goes back to 1x

### Expected behavior

Increase up to 8x

### Steps to reproduce

Always does not work atm. No special things to reproduve

**Comment by mihunet** [comment]
Same like issue #5849
