### ISSUE TITLE
Cant use custom panel.cfg with livery

### ISSUE THREAD

**Issue by mixMugz** [flybywiresim/a32nx#5856]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-09-19T13:44:38+00:00",
  "ref": "master",
  "sha": "80496bdd2b5281884df0ba379713b0cefbdce7fa",
  "actor": "2hwk",
  "event_name": "manual"
}
```

### Describe the bug

If i try create custom panel.cfg for livery all aircraft systems stop work. In all defaults aircrafts this trick is work perfect.

Example panel.cfg file:
```
[VARIATION]
override_base_container = 0

[VPainting01]
size_mm                = 2048,512
texture                = $RegistrationNumber
location             = exterior
painting00=Registration/Registration.html?font_color=0xab0200,    0, 0, 2048, 512
```

### Expected behavior

Using panel.cfg does not break systems.

### Steps to reproduce

1. Create sample livery
2. Create custom panel.cfg (example above) just for changing external registration text
3. Load aircraft with livery
4. Check same situation with another aircraft

**Comment by Benjozork** [comment]
This panel.cfg is invalid as it does not load any avionics or system modules... That's expected.

**Comment by mixMugz** [comment]
> This panel.cfg is invalid as it does not load any avionics or system modules... That's expected.

Why it's invalid? In another aircrafts it works as it should

**Comment by Benjozork** [comment]
The A32NX loads system components using WASM modules and they must be referenced in the panel.cfg.

If this is supposed to extend the base panel.cfg, then that's a sim feature, and there's really nothing we can do about that.

**Comment by 2hwk** [comment]
> > This panel.cfg is invalid as it does not load any avionics or system modules... That's expected.
> 
> Why it's invalid? In another aircrafts it works as it should

WT CJ4 has the same quirk. Livery authors should NOT be modifying panel.cfg.
