### ISSUE TITLE
Since 0.7.0  no Power / black display

### ISSUE THREAD

**Issue by Adi-18** [flybywiresim/a32nx#5860]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-09-18T00:34:38+00:00",
  "ref": "v0.7.0",
  "sha": "e8ea73b3648d48437ca5df55e280a945fd11dab6",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

Since Update 0.7.0 Tablet on the side is not turning on.
Displays for voltage on OH-Panel are black.
When I press Bat1 and Bat2  the sound of electromagnetic relay are hearing and some lights on panel comes active.
I can press APU Master on and Start, but all Displays stays dark. ASABO A320 is not installed.

### Expected behavior

After start MSFS, load flight with FBW A32NEO (i.e. LSZH or EDDK)
- Voltage Display should light around 28.00V
- With pressing on Tabled on left side, it should turn on

### Steps to reproduce

1. Start Windows
2. Start MSFS,
3. Load flight with FBW A32NEO  LSZH or EDDK
4. See overhead panel
5. See and press Tablet

### Discord Username (optional)

Adi#1912

**Comment by ErickSharp** [comment]
Does changing your livery to the standard flybywire livery have any effect?

**Comment by Adi-18** [comment]
Thanks for repkay. Its also on standard livery.
But it looks like conflict with "ZZZ JD GTN750 A32NX FBW Stable panel" addon

I removed it and it works now. Sorry
