### ISSUE TITLE
since 0.7   black displays

### ISSUE THREAD

**Issue by DieterKuep** [flybywiresim/a32nx#5866]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-09-19T20:59:10+00:00",
  "ref": "master",
  "sha": "74045fb5eb77b3043f816d8d26028c33fb63bfd4",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

after loading the plane on runway, i get black displays.

### Expected behavior

working displays

### Steps to reproduce

1. starting msfs 2020 1.19.9.0
2. choosing a 320 fbw
3. choosing airport and runway

### Discord Username (optional)

Dieter K

**Comment by ErickSharp** [comment]
Please confirm you are not using a livery alongside the FBW A320 Neo

**Comment by Adi-18** [comment]
I had the same problem. Did you also installed the "ZZZ JD GTN750 A32NX FBW Stable panel" plugin?

**Comment by DieterKuep** [comment]
first answer: i am using some liveries - OK i delete them

where can i find the ZZZ JD GTN750 A32NX FBW Stable panel" plugin?
Thanks for help

**Comment by Adi-18** [comment]
Every addons/plugins you also will find it in C:\Users\**<USER>**\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\Community

**Comment by DieterKuep** [comment]
i can`t find this pluggin in my community folder

**Comment by Adi-18** [comment]
Ok, so maybe you will have other conflict in community folder.

**Comment by YuTookMyJob** [comment]
Do you have the Mugz Co-Pilot add-on installed? I had the same issue and this was the cause, if you don't have that add-on then it's worth removing all add-ons and plugins except A32NX. If the displays work then start adding your add-ons and plugins back in one by one and see which one has caused it.

**Comment by MisterChocker** [comment]
Closing due to no response.
