### ISSUE TITLE
Engine Startup Sequence not working

### ISSUE THREAD

**Issue by VVingnut** [flybywiresim/a32nx#5867]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-09-18T00:34:38+00:00",
  "ref": "v0.7.0",
  "sha": "e8ea73b3648d48437ca5df55e280a945fd11dab6",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

Unable to start Engines.  PSI builds on one engine and then the other tries to start and both fail.

### Expected behavior

Engine spool-up sequence not working.  CTRL-E also has the same result.

### Steps to reproduce

Start Ext Power
Start Pumps
Start APU
Start ADIRS
Start Engines - Fail

### References (optional)

https://youtu.be/_hVQvbY8mKA

After trying many options, I uninstalled and reinstalled both FS2020 and FBW A32NX in new folders. This did not fix the issue

### Additional info (optional)

It fails on the Stable, Development, and Experimental version.

### Discord Username (optional)

TWC_VVingnut#2135

**Comment by MisterChocker** [comment]
As you can see you have no bleed air pressure because you have forgot to open the apu bleed air valve

![image](https://user-images.githubusercontent.com/1857322/134017648-37296f2a-497f-4862-9b0f-18117c4b1989.png)

**Comment by VVingnut** [comment]
Will do.  The APU Bleed was not on - may have been the issue.  Thanks for checking.
