### ISSUE TITLE
Brakes not releasing in taxi.

### ISSUE THREAD

**Issue by barryflight1** [flybywiresim/a32nx#5869]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-09-18T00:34:38+00:00",
  "ref": "v0.7.0",
  "sha": "e8ea73b3648d48437ca5df55e280a945fd11dab6",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

When taxing brakes do not release after stopping. It is impossible to move the aircraft in any way. Even full throttle or reverse thrust makes no impression. Although the aircraft moves up/down as it would with power applied against the brakes.
I have had consistently had the same result in all three version. Up to Update 5 in MSFGS FS this did not happen. Only this aircraft is effected. All default and other add ons work fine. I am running in an otherwise empty community file.

### Expected behavior

Brakes should apply and release not restricting movement.

### Steps to reproduce

Taxi aircraft. Apply brakes then attempt to move off again.

### Discord Username (optional)

barryflight1

**Comment by MisterChocker** [comment]
Are you using a keyboard?

**Comment by barryflight1** [comment]
Hi

Thanks for prompt response.

This issue affects the aircraft if it is necessary to stop during taxi to
the runway or after landing if forward momentum is not maintained. In other
words if I am vacating the runway and touch the brakes, I ain't moving no
more.

If I continuously taxi to runway without stopping and roll to immediate
take off, no problem. I can complete the flight until I land. As long as I
don't brake before arriving at the gate, no problem.

Keyboard is for instrument views and G = landing gear.

Logitech Extreme 3D pro joystick for external view, flaps, spoilers,
throttle and rudder bound for nose wheel steering, CH Pro rudder pedals and
mouse for pointing and selecting menu's and switches etc.

This fault only occurs with this aircraft (the Asobo default is not
effected) and only since Update 5. I have Update 6 and the hotfix released
a couple of days ago installed. I am using the Steam version.

The A320 NX is Stable 7.0 installed today. Experimental and Developers
versions both produce the same result. I have installed to empty community
folder. All other add-ons and aircraft are in "oldcommunity" folder

If I go to external view and set full throttle forward and reverse thrust
the aircraft rocks back and forth as it would if the parking brake was on.
It isn't and neither are the landing brakes or spoilers activated.

I have tried various settings for throttle and brakes including ensuring
that I am not bound to propeller outputs and that all the axis are
correctly set for brakes and throttle and the sensitivities are all correct
with null zones etc set up as they should be.

I have been "flying" A320's for several years including Aerosoft and have
never had this issue before.

Now I am just baffled!

Any advice would be very welcome.

Regards Barry

**Comment by John-UK** [comment]
You best option could be ask support channel in the discord. It may be a bug, but that is not likely.

As it is also not likely to be an error on your part. The most likely culprit is a binding or rogue control signal. Can you see the brake pedals in the footwell of model apply and release in response to the brakes being applied and released on the controls while you are stuck?

**Comment by barryflight1** [comment]
Hi John Maguire

Thanks for the help and as you suspected the issue was caused by a weird
binding in my CH Pro Pedals set up.

Somehow the pedals were set to left and right brakes respectively but left
brake also was bound to right brake axis! The pedals worked fine before
applying brakes but after they simply could not release.

But all is good now. Many thanks for your help.

Best wishes
Barry

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by MisterChocker** [comment]
Glad to hear you were able to fix it!

Closing since issue resolved.
