### ISSUE TITLE
Weird turn back when punching in approach in flight

### ISSUE THREAD

**Issue by mduft** [flybywiresim/a32nx#5875]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-09-21T14:48:27+00:00",
  "ref": "master",
  "sha": "9e7914c58dc65a18945a8d6eec4ed5fded31c806",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

I started a flight without a flight plan loaded, and punched a quick flight LOWK/LOWS into the FMGC. I filed the plan with ATC and punched in the departure given. Then enroute I added the approach I was given by ATC. Then things got weird.

1) The F-PLAN showed FL NAN instead of the expected flight level for the next waypoint. (Also rendering the A weirdly).
2) The plane started a sharp left turn. I initially thought it would want to turn back to the new track after changing the route, but it kept on turning until it was headed ~200° into the wrong direction, away from the now active (shown active in the F-PLAN) `SBG` waypoint. Also it showed that heading (the wrong one) in the ND next to the active waypoint name.
3) I proceeded to put in a DIR to `SBG` which made the plane turn back to `SBG`, however with the drawback that it now no longer flew the nice and smooth approach turn *before* SBG which it would have done otherwise.

I have had the same (or similar) behavior before on route to LOWG, EDDM and LOWW.

### Expected behavior

I am not 100% sure I'm not doing something stupid and the plane is correct, since I'm no pilot xD However I would expect it to continue to the next, now active waypoint after punching in an approach, regardless of whether I'm adding or modifying an approach.

### Steps to reproduce

1. start without flight plan in LOWK
2. enter LOWK/LOWS flight, no departure, no approach.
3. enter departure given by ATC.
4. fly some.
5. enter appraoch given by ATC while enroute. In this case ILS15 via SBG.
6. plane does crazy stuff, turning back to LOWK instead of continuing to SBG even though it is marked active in ND and FMGC/F-PLAN.

### Additional info (optional)

As noted I had the issue before, not with development but with the stable versions, must have been some 0.6.* version.

**Comment by Benjozork** [comment]
Fixed by upcoming custom flight plan manager

**Comment by mduft** [comment]
Nice - to be expected on development or experimental?

**Comment by Benjozork** [comment]
It's already on experimental.

Will be in dev soon.
