### ISSUE TITLE
Flipping A/SKID & NW STRG Switch Causes Warning Chime while Cold and Dark

### ISSUE THREAD

**Issue by ManyPandas** [flybywiresim/a32nx#5877]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2021-09-21T19:02:25+00:00",
  "ref": "HEAD",
  "sha": "9e7914c58dc65a18945a8d6eec4ed5fded31c806",
  "actor": "Andreas Guther <andreas@guther.family>",
  "event_name": "manual"
}
```

### Describe the bug

When the A/SKID switch is moved to the OFF position, the warning system sounds a warning bell sound

### Expected behavior

I do not believe the aircraft should produce a warning bell in the cold and dark state, even though moving this switch would create a warning chime if the aircraft is powered on.

### Steps to reproduce

1. Load Aircraft Cold and Dark
2. Toggle A/SKID switch on and off

### References (optional)

https://user-images.githubusercontent.com/21292503/134236090-511af6be-8229-46ec-9e09-fd859dbd78ad.mp4

### Discord Username (optional)

ManyPandas#0839

**Comment by beheh** [comment]
Very similar to #2233. This will be fixed once we have an FWS that cares about being powered.

**Comment by derl30n** [comment]
Issue resolved
