### ISSUE TITLE
AutoThrust disabled after hitting „Esc“ during flight

### ISSUE THREAD

**Issue by Peyto79** [flybywiresim/a32nx#5880]
### Aircraft Version

Development

### Build info

```json
Current Version
```

### Describe the bug

When I hit „ESC“ during CRZ flight to get into the FS menue (lets say to check some settings or online status of friends) and I go back to the flight, the AutoThrust is disabled.

### Expected behavior

I would expect that no changes happen to the current flight settings (Autothrust engagement) if I temporarily checked the menue.

### Steps to reproduce

Fly with Autothrust and AP engaged.
Hit ESC on the keyboard to get to the FS menue.
Hit ESC again to go back to the flight (or click „return“ in the menue. It doesnt matter how you go back to the flight)
AutoThrust is then disabled.

**Comment by aguther** [comment]
Please check for any double key bindings. I cannot reproduce your issue and I never heard from someone else that this happens.

**Comment by Peyto79** [comment]
My keyboard profile is the standard one.
It used to work fine but with one of the dev updates this behaviour started.

Its not a big issue. I just enable AutoThrust again when coming back to the flight.

**Comment by aguther** [comment]
Hmm, strange indeed then.

Could you enable dev mode and open the console, filter for WASM, clear the logs and then go to pause and back again to retrigger the situation? Would be interesting what logs are shown then...

**Comment by MisterChocker** [comment]
Closing due to no response from op.
