### ISSUE TITLE
Save fuel state for next flight

### ISSUE THREAD

**Issue by oim1** [flybywiresim/a32nx#5881]
### Aircraft Version

Experimental

### Description

Instead of the plane loading with a set amount of fuel on every load, it should save the fuel quantity from the previous flight and use that as the amount of fuel the plane loads in with. It would be nice to have as it feels weird having to unload fuel every time. 

Maybe it could be done similar to the way settings are saved in the EFB although I'm not too sure how it would be done or if it can be done. 

### Discord Username (optional)

oim#0001

**Comment by MisterChocker** [comment]
There has been a similar request #5828.

The issue with the plane always having to much fuel onboard is due to the weight and balance menu from the simulator itself.
Hence these weights will be loaded initially.

Maybe there is a way to manipulate/lower the default settings in the weight and balance page from the msfs aircraft selector.

**Comment by juliansebline** [comment]
Hello,

I have been working on it and found two solutions. 

1. Persistent value in React
    1. Unfortunately, there's a problem of sync between React and C++. My code works if the loading page is slow, only.  
2. Write values in a file
    1. Unfortunately, I have discovered WASM is a sandbox (thanks @Taz5150), therefore we are unable to read/write files.

The only suitable one is the latter but we have to hope MS will let us read/write files.

**Comment by aguther** [comment]
Oh you can read and write files. Just look at the FBW. It reads and writes configuration settings and even has a flight data recorder function. It’s just limited where you can read and write files.

**Comment by aguther** [comment]
https://github.com/flybywiresim/a32nx/blob/master/src/fbw/src/FlyByWireInterface.cpp#L127
https://github.com/flybywiresim/a32nx/blob/master/src/fbw/src/ThrottleAxisMapping.cpp
https://github.com/flybywiresim/a32nx/blob/master/src/fbw/src/FlightDataRecorder.cpp

**Comment by juliansebline** [comment]
> https://github.com/flybywiresim/a32nx/blob/master/src/fbw/src/FlyByWireInterface.cpp#L127 https://github.com/flybywiresim/a32nx/blob/master/src/fbw/src/ThrottleAxisMapping.cpp https://github.com/flybywiresim/a32nx/blob/master/src/fbw/src/FlightDataRecorder.cpp

You saved my life

**Comment by aguther** [comment]
I suggest using an ini file as the FBW to store this state and reload it…clean interface that in question can also be edited manually.

**Comment by tracernz** [comment]
Potentially with a section for each livery... giving the flexibility to add more keys for other parameters at a later date.

**Comment by Gurgel100** [comment]
We could do it like PMDG: each livery has it's own state file

**Comment by Gurgel100** [comment]
I think PMDG is doing with the aircraft registration. I don't know how to get to this information though.

**Comment by juliansebline** [comment]
I’ve set default values if the file is not found therefore it would work with another file.

About aircraft.cfg, we need to copy it in /work folder when installing a livery. I suggest to modify the installer

**Comment by Gurgel100** [comment]
You can just fallback to the value set in aircraft.cfg of the aircraft itself. (Which is "ASX320" currently).

**Comment by juliansebline** [comment]
Ok I'll do that.

One more thing: What quantity unit should be used ? All the calculations are made in pounds but then converted to gallons to be stored in the sim. If stored in gallons in the file, the quantities would be converted to pounds straight the way so is it worth to store them in gallons ?

**Comment by juliansebline** [comment]
Fixed. PR available here: https://github.com/flybywiresim/a32nx/pull/7170

**Comment by juliansebline** [comment]
I'm facing a problem: I cannot create any directory. filesystem (C++17) and some Windows headers are disabled in the SDK.

Even though I remove the protections for filesystem, it does not compile, same error: "_The Filesystem library is not supported by this configuration of libc++_"

It does not find _"direct.h"_ not _"Windows.h"_ for instance.

If anyone can test... I suggest to write files at the root of work in the meantime.

**Comment by tracernz** [comment]
What if you just try to write the file in the subdirectory without creating the subdirectory? Does MSFS magically create it or does the open call fail?

**Comment by juliansebline** [comment]
The open call fails. That's how I've noticed the problem

**Comment by Gurgel100** [comment]
After some testing from @Saschl he found out that `mkdir` works.
So you can do something like this (you can test out different permissions):
```C
#include <sys/stat.h>
mkdir("\\work\\AircraftStates", 777);
```

**Comment by juliansebline** [comment]
It works, indeed. Thank you very much. I did not know stat.h included such a function. I'm running some tests.
