### ISSUE TITLE
Someone please change a new wiper sound, it's quite noisy

### ISSUE THREAD

**Issue by Soap1422** [flybywiresim/a32nx#5882]
Aircraft Version

Development(actually every version)

Someone please change a new wiper sound, it's quite noisy.
it drives me crazy I am using it, pretty annoying.

**Comment by Soap1422** [comment]
In the cockpit, it sounds like outdoor sound without sound insulation.
I think something goes wrong when I am using wiper. or maybe just no sound insulation effect of wiper in cockpit
thanks, I wish you the best

**Comment by tracernz** [comment]
Here we have a real A320 pilot who thinks the sounds are extremely realistic.... https://youtu.be/_tkXN9yaZb8?t=3001. I don't think we will be changing them.

**Comment by hotshotp** [comment]
This is an interior recording made with a high quality microphone and mixed according to the feedback of multiple pilots and engineers. Here is an IRL video showing how they sound. They are harsh IRL, and we will not be changing the sound. https://youtu.be/qswzaaiT05w

**Comment by Soap1422** [comment]
well, maybe lower its volume a little bit, it's like wiping with cockpit window open.
maybe I am wrong. if I am, sorry about it.
thank you, wish you guys the best and thanks for the great job of A32nx

**Comment by tracernz** [comment]
> well, maybe lower its volume a little bit, it's like wiping with cockpit window open.
> maybe I am wrong. if I am, sorry about it.
> thank you, wish you guys the best and thanks for the great job of A32nx

It's all good, we understand where you're coming from, but the wipers are equally annoying in the real A320 according to the pilots, and we want to capture everything as accurately as we can. 😆

**Comment by Soap1422** [comment]
> > well, maybe lower its volume a little bit, it's like wiping with cockpit window open.
> > maybe I am wrong. if I am, sorry about it.
> > thank you, wish you guys the best and thanks for the great job of A32nx
> 
> It's all good, we understand where you're coming from, but the wipers are equally annoying in the real A320 according to the pilots, and we want to capture everything as accurately as we can. 😆

Thank you for telling me this, thanks so much.
by the way how did you know where I am coming from? I am curious that how did you get my info...

**Comment by Soap1422** [comment]
Thanks guys for telling me this, sorry for bother coz of my mistake.
Wish y'all the best.

**Comment by tracernz** [comment]
> by the way how did you know where I am coming from? you mean nation? and sorry about it.
> coz English is not my daily language.

Don't worry! It's a phrase the means I understand what you're saying. English is fun like that. 😀

**Comment by Soap1422** [comment]
> > by the way how did you know where I am coming from? you mean nation? and sorry about it.
> > coz English is not my daily language.
> 
> Don't worry! It's a phrase the means I understand what you're saying. English is fun like that. 😀

oh my god, thanks dude.
well, I am Chinese speaking guy, and it's been a pleasure to chat with you.
and I do have other cases on this forum. tickets are  5883 and 5888. 
you may wanna visit them if you are interested, and you are welcome to leave replies
Thanks so much Tracernz
