### ISSUE TITLE
Take radio altimeter device location into account on rotation

### ISSUE THREAD

**Issue by Soap1422** [flybywiresim/a32nx#5883]
### Aircraft Version

Well, actually every version

### Request Describe

A320's Low Range Radio Altimeter device is at bottom of the aircraft, near tail side.
let me explain it, coz  PFD shows 0(Radio Altimeter's height) before you rotate, and it still shows 0 when you rotate, 
well. it turns to be 1 , 2 ... after you rotate(of course, coz plane has off the ground).
the problem is when you rotate the plane, it still shows 0( if plane is still running on the ground).
it should be showed -1 when you rotate the plane, coz radio altimeter device is under the aircraft near its tail.
when you rotate, nose goes up, but tail goes down. so does that radio altimeter device. that's the exact reason why it should be showed -1 in the bottom of PFD.
yeah, A32nx's radio altimeter device is at the bottom of the aircraft but not close enough to its tail.
Flybywire guys and pilots of MSFS, I ain't here messing around, I wanna do something helpful that improve A32nx to be the best in future. sorry about my English, I ain't good at speaking English, but I will do my best to explain to you all if you have questions about my report.
thank you, I wish everybody the best.

**Comment by Soap1422** [comment]
Well, sorry about my English again, I can describe it in Chinese if you guys wanna. XD
I have leant that how to avoid friction between the tail of A320 and the ground while taking off.
that's a important stuff while you rotating A320 on the runway, it gotta be -1 most of the times(actually everytime, depends on condition)

**Comment by beheh** [comment]
Thanks for the report! I can corroborate this from various videos where there is a 1-2ft decrease during rotation. I'm sure we'll look at this when we implement the actual Radio Altimeters in the aircraft (which I'm planning to do soon).

**Comment by davidwalschots** [comment]
你英文寫得不錯！加油！

**Comment by Soap1422** [comment]
> 你英文寫得不錯！加油！

Thank you and sorry for that bug label. 
have a good day

**Comment by Soap1422** [comment]
> Thanks for the report! I can corroborate this from various videos where there is a 1-2ft decrease during rotation. I'm sure we'll look at this when we implement the actual Radio Altimeters in the aircraft (which I'm planning to do soon).

Thank you! 
have a nice day
