### ISSUE TITLE
Auto throttle calibration page with (apply and apply/save) greyed out

### ISSUE THREAD

**Issue by lasoh45** [flybywiresim/a32nx#5884]
### Aircraft Version

Development

### Build info

```json
Developmental version 9e7914c in MFS content manager says version 8.0 installed
```

### Describe the bug

1-calibration page greyed out both apply and apply/save buttons
2-cannot calibrate the throttles
3-cannot push in AP 
4-cannot fly the plane

### Expected behavior

tell me how to calibrate the throttle it is confusing for me

### Steps to reproduce

after the version 7 update on 9/18/21

### Discord Username (optional)

lasoh45

**Comment by lasoh45** [comment]
my e mail is lasoh45@gmail.com
305-588-4873 USA EDT

**Comment by Benjozork** [comment]
If the buttons are greyed out there is usually an error message you should read in the middle of the screen.

You can watch a video guide here:

https://youtu.be/8yZuv2L4jPA

**Comment by lasoh45** [comment]
Benjamin I have followed those instructions and understand how the calibration is the key for flying this plane . The buttons are greyed out sir ! Is there something I am missing here ! Version 8.0 developmental ! 
Should the engines be on while doing this calibration. 

Javier O Delgado
Certified Business Coach
www.people-too.com
***@***.***

**Comment by Benjozork** [comment]
Again - is there an error message in the bottom center of the screen?

This is the only reason I can remember for buttons being grayed out.

No, engines do not have to be on.

**Comment by lasoh45** [comment]
Here are the respective screen shots at each detent level and what it says. Click and open!

 

 

 

 

Javier O. Delgado

President & Founder                      

PeopleToo LLC

305-588-4873

www.people-too.com

***@***.***

**Comment by Benjozork** [comment]
I cannot see the screenshots.

It seems you are responding via an email client - we discourage that as images and other attachments will not work properly. I recommend using the github UI.

**Comment by lasoh45** [comment]
You should be able to open, click open and the shots are there. I give up I cant calibrate this model, I will fly the Neo regular version. I am not very sharp with software issues,  cannot get the button to apply save to be functionable.

 

Thanks any way! 

 

 

 

 

 

Javier O. Delgado

President & Founder                      

PeopleToo LLC

305-588-4873

www.people-too.com

***@***.***

**Comment by Benjozork** [comment]
I explained exactly what the issue was with the screenshots. Anyway.

**Comment by lasoh45** [comment]
With all due respect this ticket is not closed .
You have not helped a user as you should . An IT person tried to calibrate the auto throttle  based on the instructions on your installer page and could not  get it to calibrate successfully ! We finally got some calibration done and got the apply save button to work . However on TO on TOGO all is well but then the AP will not engage and the lever will not de tent back to CL for the rest of the flight !
Your company has made this very difficult to follow and do this ; instead FBW should have done this internally so the user could actually enjoy the product ! Ala versión 6.
If you don’t want help fine get someone else that wants to . I will be putting this out on social media because there are many like me out there !

Javier O Delgado
***@***.***

**Comment by Benjozork** [comment]
We've told you many, many, times to join our Discord for support as this is not ideal for us to help, and you've ignored that.

We've told you to not respond with the GitHub email because we couldn't see attachments, and you acted like I was lying or something.

Thousands of people fly everyday without issues. You maybe need to let us help you because by refusing to do the most basic things to give us more information it's not gonna work.

**Comment by Saschl** [comment]
Just to add. This is no company, it's all a bunch of volunteers that do this in their free time.

**Comment by sidnov** [comment]
Here's what we see when you say you have attached screenshots. And without screenshots we cannot diagnose anything.
![Screenshot_20210924-205522.png](https://user-images.githubusercontent.com/29005005/134700778-3fb366aa-50bc-4f9b-89e6-e3561651f4a9.png)

**Comment by lasoh45** [comment]
Discard says they don’t support your group . Tell me the missing step . 
1- we have calibrated the EFB and apply and saved .
2- we fly all good on takeoff with TOGA 
3-at that point the AP button does not engage 
4-throttle does not Change or show back to CL detent .
We are just regular people we fly the plane properly we expected the systems to work . We are not engineers or software developers like your team! This calibration should already be done by you as it was in version 6!
Thanks 


Javier O Delgado
Certified Business Coach
www.people-too.com
***@***.***

**Comment by sidnov** [comment]
What throttle setup do you have? Is it a keyboard or a throttle like Thrustmaster TCA or an Xbox controller?

**Comment by sidnov** [comment]
Please open https://github.com/flybywiresim/a32nx/issues/5884 , login to your account and reply to the thread. We CANNOT receive any valuable information such as screenshots sent via email

**Comment by lasoh45** [comment]
I will thank you ! Your product is far superior and I need to succeed in getting this done correctly !

Javier O Delgado
Certified Business Coach
www.people-too.com
***@***.***
