### ISSUE TITLE
Two light problems that I found on A32nx

### ISSUE THREAD

**Issue by Soap1422** [flybywiresim/a32nx#5888]
### Aircraft Version

Every Version of A32nx

### Describe the bug

Hello, me again. (ticket #5883's author)
Nav & Logo light has position 1, position 2 and position off options, but I see only position 2 and off can be switched on, position 1 is missing.

### Expected behavior

Here's another light problem, and it's just a small problem.
after you set parking brake on, there's a very tiny red light should be up.
that light is on nose gear where is between right turn off light and left turn off light.
it's on a small box. and after you released parking brake, it will be dark .
I am a new guy on github and I don't know how to send you all a picture about it.
but I can provide you a link which my picture will remain there for two weeks, copy this link to your browser if you can't click it open.
https://paste.pics/DYGR9
![image](https://user-images.githubusercontent.com/1857322/134751582-9056635e-54c8-4070-947f-862e909f93ae.png)

I have pointed out that little bad boy out on that picture with red arrow, that's the exact stuff that works together with parking break.
well, maybe someone has already report those two light issues before I do.
but thank you for your great job, flybywire workers. I just wanna do something that helpful here.
I wish everyone the best and have a nice day.

**Comment by bouveng** [comment]
@Soap1422 Feel free to create a fresh issue for the NAV lights, provided you find a NEO with 2 states on that switch for the LED lights.

Br.

/J
