### ISSUE TITLE
Prevent EFB Crash on loading Invalid OFP Format

### ISSUE THREAD

**Issue by TheSledge-SLEJ** [flybywiresim/a32nx#5889]
### Aircraft Version

Development

### Description

Catch the exception when e.g. loading a BAW or other non-LIDO OFP format causes the EFB to crash and having to restart flight/go to World Map.

Instead, display an EFB message which says 'Invalid OFP Format' when trying to load from Simbrief, thus allowing a reformat and seamless continuity.

Would be a nice touch.

### Discord Username (optional)

The Sledge

**Comment by tracernz** [comment]
Duplicate #4708
