### ISSUE TITLE
No further descent when changing from Std to QNH

### ISSUE THREAD

**Issue by PM3Delta** [flybywiresim/a32nx#5892]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-09-21T04:28:49+00:00",
  "ref": "master",
  "sha": "5aa13749c38b71725802d104a32d44d4141e5088",
  "actor": "2hwk",
  "event_name": "manual"
}
```

### Describe the bug

The plane did not descent to the CST altitude (10000ft) when changing the baro at the transition level (FL100) from Std to QNH.

### Expected behavior

I would have expected the the aircraft continues to descent although the switch to QNH led to a slightly higher altitude (here ca. 10400ft) and not stop descending based on the previous baro setting (std).

### Steps to reproduce

Set up Transition with e.g. an altitude constraint of 10000ft (here into EDDS, BADSO 25)
Set transition altitude to 10000 in the APPR  PERF page
Start managed descent by dialing in e.g. 4000ft into the FCU
Aircraft will stop descending when reaching FL100 (which is correct according to the constraint of 10000)
Now as you also reached the transition altitude switch baro to a higher QNH e.g. 1025hPa, which will lead to indicate an altitude of ca. 10400ft.
Note that aircraft will not descent the 400ft to match the newly resulting altitude (green box) of 10000ft.

### References (optional)

![Screenshot (482)](https://user-images.githubusercontent.com/60411051/134503238-4f7f34f3-eac9-4a5e-9fe4-7862ae3ad17d.png)

### Additional info (optional)

I did not observe if it was working before.
Afterall it is not a "killer" bug either, but just to let you know.
Thx. Hightly appreciate your work.

### Discord Username (optional)

SierraHotel2873#5470

**Comment by aguther** [comment]
If you change the baro when ALT, ALT CST or ALT CRZ is engaged it is IRL and intended behavior that the plane does not follow the changes altitude. The above mentioned modes are following pressure altitude when the modes have been engaged.

**Comment by PM3Delta** [comment]
> If you change the baro when ALT, ALT CST or ALT CRZ is engaged it is IRL and intended behavior that the plane does not follow the changed altitude. The above mentioned modes are following pressure altitude when the modes have been engaged (according to documentation in FCOM).

Sorry I did not know that. Sth learned. Sorry for the bother. Thx.
