### ISSUE TITLE
#5884 Request  AP after calibration

### ISSUE THREAD

**Issue by lasoh45** [flybywiresim/a32nx#5900]
### Aircraft Version

Stable

### Build info

```json
version 7.0
```

### Describe the bug

after calibration and apply/save was completed the plane took off on TOGA and it reached altitude the AP button would not push in and engage.
The throttle would move to CL but the engines would not change in power

### Expected behavior

AP should work and permit the pilot to follow the navigation flight plan via the managed button

### Steps to reproduce

After the update to version 7 on 9/18/21

### Discord Username (optional)

lasoh45

**Comment by Benjozork** [comment]
Can you show a screenshot of the flight deck while the AP is not engaging ?

With PFD and FCU visible.

**Comment by MisterChocker** [comment]
Quick follow up question, are you perhaps using a key bind to engage/disengage the ap or do you click on the ap button with the mouse?

**Comment by fudge76** [comment]
I am having the same problem with the stable version 7. The AP worked with the previous stable version only, not the other two versions. I have tried with nothing but the stable version 7 in my community folder with no luck. I can hear a click but the AP does not turn on. Everything else seems to work okay. 
Sometimes when I click on the AP button the AP sign flashes once in the PFD but the AP does not turn on.
It appears to me that the problem may be connected with the type of controllers being used.
I have the following connected - Thrustmaster TPR Pendular Rudder Pedals, Honeycomb Alpha Flight Controls, Logitech Flight Throttle Quadrant. I have also tried using my Logitech switch panel with this aircraft but when the gear up lever is used everything electrical shuts down and the engines stop. I now have this unplugged when flying the FBW A320. ( The gear up lever also affects other large aircraft )

**Comment by Benjozork** [comment]
> Sometimes when I click on the AP button the AP sign flashes once in the PFD but the AP does not turn on.

This sounds like you are going too slow. It is important you identify why the AP is not activating.

Did you calibrate your throttles in the EFB?

**Comment by fudge76** [comment]
Yes I have calibrated the throttles. 
I may have sorted out the problem. I have redownloaded the stable version 7 and tried again. Before takeoff I checked and found that I had the AP connected to the white button on the rear of the left hand side of the yoke handle. I disconnected this and now everything works fine when mouse clicking on the AP button. 
I have a separate setup for the yoke, throttle etc for the A320. This yoke button works fine for the AP on other aircraft.
I will try this fix on the other two versions as well.

**Comment by tracernz** [comment]
Whenever you have automation issues in an Airbus, check the FMA. Always post what the FMA says in your bug reports for these types of issues.

**Comment by lasoh45** [comment]
I use the mouse to engage the AP.

 

 

 

 

 

Javier O. Delgado

President & Founder                      

PeopleToo LLC

305-588-4873

www.people-too.com

***@***.***

**Comment by NUTTTTTTTT** [comment]
@lasoh45 Please stop using emails to reply on Github. If you have issues, reach out on our Discord where we can help properly as asked.

**Comment by lasoh45** [comment]
I get this message from DISCORD that they don’t support your FBW team, so confusing friend, what is the channel to get to you for  support.

Totally confusing!

 

John (Discord) 

Sep 21, 2021, 10:47 PDT 

Hey Javier,

Sorry for the confusion here! Just to clarify, our app is not affiliated with Airbus, so sadly we won't be able to provide support for this issue, and you may want to directly ask their support team about this.

If you have any specific questions about the Discord app though, please let me know here!

Cheers,
John

 

 

 

 

Javier O. Delgado

President & Founder                      

PeopleToo LLC

305-588-4873

www.people-too.com

***@***.***

**Comment by sidnov** [comment]
https://discord.gg/flybywire

**Comment by MisterChocker** [comment]
Closing due to no response from op.
