### ISSUE TITLE
No visuals of aircraft in either cockpit or external view

### ISSUE THREAD

**Issue by peteralun1** [flybywiresim/a32nx#5901]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-09-18T00:34:38+00:00",
  "ref": "v0.7.0",
  "sha": "e8ea73b3648d48437ca5df55e280a945fd11dab6",
  "actor": "Benjozork",
  "event_name": "manual"
```

### Describe the bug

After installing ver 0.7 into my MSFS community folder and starting MSFS, I selected the A32nx aircraft in the World view but the Aircraft did not appear in the hanger. After selecting a random flight and pressing the Fly button, the aircraft does not appear at the location, neither in Cockpit or External view. There is sound however.

### Expected behavior

Normal appearance of the aircraft

### Steps to reproduce

Tried a reinstall after deleting the downloaded version, same result.

**Comment by Benjozork** [comment]
Please follow this procedure:

![image](https://user-images.githubusercontent.com/4503241/134739958-6b371260-64dc-4316-8be3-738767453ede.png)

**Comment by MARIOESTEVES** [comment]
same to me!
![Screenshot (119)](https://user-images.githubusercontent.com/72155035/134782490-0437cab4-ad32-4d9d-b96b-c9a00c4dca4e.png)
![Screenshot (120)](https://user-images.githubusercontent.com/72155035/134782496-17c9ddf3-5c41-4b5a-bd6e-c5e1485ec455.png)

please help!

**Comment by NUTTTTTTTT** [comment]
> same to me!
> ![Screenshot (119)](https://user-images.githubusercontent.com/72155035/134782490-0437cab4-ad32-4d9d-b96b-c9a00c4dca4e.png)
> ![Screenshot (120)](https://user-images.githubusercontent.com/72155035/134782496-17c9ddf3-5c41-4b5a-bd6e-c5e1485ec455.png)
> 
> please help!

Delete that version from the content manager, then re-install one of our latest versions using our FBW installer from our website.

**Comment by Triplecorpse** [comment]
I had that issue when I had AC installed from MSFS Store and after update 5. I needed to completely and manually remove correspondent folder from Official folder in MSFS directory and then reinstall it from FBW installer

**Comment by MisterChocker** [comment]
Closing due to no response from op.
