### ISSUE TITLE
VOR Identifyer not accepted by RAD/NAV

### ISSUE THREAD

**Issue by PM3Delta** [flybywiresim/a32nx#5905]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2021-09-24T15:56:41+00:00",
  "ref": "experimental",
  "sha": "f96ac408fa31686be361dc8c2907a5de78b011f8",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

Trying to enter a VOR via its identifyer seems to be broken in the experimental version from Sept. 24th.

Example.  VOR DKB can not be entered, nor e.g. WLD on the way to EDDM from the north, despite being in range. However, entering the respective frequencies 117.8 or 112.8 still does work and the needles are showing correctly in the ND display.

Could you please look into it if you get the time?  I am pretty sure it worked in previous versions, although I am not 1000% sure, as I might get the Dev, Exp. confused.  thx.

### Expected behavior

Entering the VOR identifyer e.g. DKB, WLD etc. into the RAD/NAV should be accepted and populate the respective frequency.

### Steps to reproduce

Type DKB in RADNAV
Press upper left button on MCDU
Nothing happens.

### References (optional)

![image](https://user-images.githubusercontent.com/60411051/134765298-10496dd2-89a0-4310-a07d-1b56df5a591c.png)

**Comment by tracernz** [comment]
Experimental is not supported, and this is working fine for me with the latest experimental..?
![image](https://user-images.githubusercontent.com/9995998/134767129-91a181e6-55a8-44da-9a98-31d671f66f25.png)
