### ISSUE TITLE
MCP displays doesnt work [BUG]

### ISSUE THREAD

**Issue by Shimi1612** [flybywiresim/a32nx#591]
![MCP](https://user-images.githubusercontent.com/71125097/92899082-cf292d80-f41e-11ea-902f-c83cf3ec2216.png)

**Mod Version**
 

-V0.2.0

**Describe the bug**

-The MCP works but doesnt show the adjusted numbers at the MCP displays. You only see die adjusted config on the PFD.

**To Reproduce**

1. BUG is all the time. The MCP is dark from Start to End of flight. 
2.
3.

**Expected behavior**

-That the MCP shows die adjusted config.

**Actual behavior**

**References**

-Screenshot is attached.

**Additional context**

**Comment by ninjomcs** [comment]
Not a bug, it’s just that your fcu brightness is turned all the way down

**Comment by i-TechSoftware** [comment]
Turn on the indication with this knob
![Screenshot_1](https://user-images.githubusercontent.com/48829872/92903729-f554ca80-f42a-11ea-96f8-a401c534d98d.png)

**Comment by Shimi1612** [comment]
Thank you very much, testet and it works.
