### ISSUE TITLE
Assign hardware buttons

### ISSUE THREAD

**Issue by Triplecorpse** [flybywiresim/a32nx#5910]
### Aircraft Version

Stable

### Description

I have 2 issues assigning buttons on my throttle hardware.
1. I managed to switch mode to IGN but I cannot find master switch options to assign buttons to.
2. I managed to assign rotators to AP altitude/VS adjust but I cannot find how to assign buttons to "Engage selected altitude/VS".

Why not make some mapping to show which control settings is responsible for which AC function?

**Comment by aguther** [comment]
We have it:
https://docs.flybywiresim.com/fbw-a32nx/feature-guides/autopilot-fbw/
