### ISSUE TITLE
Path drawn incorrectly between waypoints

### ISSUE THREAD

**Issue by lolisec** [flybywiresim/a32nx#5914]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2021-09-25T12:52:53+00:00",
  "ref": "experimental",
  "sha": "bc41b1c2caea32346c2588ea811cc1e33d654ea2",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

When flying from KATL to KCLT the path between the waypoint PHIIL and CNTLR was drawn incorrectly and seemed concerning to me as this is the first time I've seen this happen.

### Expected behavior

A perfectly drawn path between the two waypoints.

### Steps to reproduce

fly from KATl to KCTL with route: KATL/27R PHIIL2 PHIIL CNTLR EVRRR BANKR2 KCLT/36L

### References (optional)

![image](https://user-images.githubusercontent.com/50394269/134812446-d708a441-a3f2-4bbe-a688-8f9ad2bb4b99.png)

**Comment by sidnov** [comment]
No support for experimental, and opening GitHub issues for known errors is not appreciated. Please check the CFMS LNAV Bugs thread on #ata-22-fms on Discord
