### ISSUE TITLE
Random Flap/Parking Brake/Spoilers Activation - Electrical Bus to Circuit Connection

### ISSUE THREAD

**Issue by PottiMc** [flybywiresim/a32nx#5916]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-09-26T06:44:22+00:00",
  "ref": "master",
  "sha": "de453f3dacee4dff43ba3afe1b4af1e19ec2cf58",
  "actor": "bouveng",
  "event_name": "manual"
}
```

### Describe the bug

While flying I get random activations of Flaps to 1, the parking brake is switched on and spoilers get fully activated.

Can't figure out why and I am not pressing any buttons at all. When looking into the event log at FSUIPC it shows the following inputs:

![image](https://user-images.githubusercontent.com/39881308/134911528-a34785d9-6521-47c2-b862-7aa8565a66ca.png)

### Expected behavior

No random inputs when not pressing a button

### Steps to reproduce

1. I start in a dark plane on the gate and go through all the checklists
2. Start and fly (AP or not makes no difference for me)

**Comment by PottiMc** [comment]
Okay, I maybe solved the issue by myself because I have ghosting in my throttle as mentioned here:
https://forums.flightsimulator.com/t/solved-hotas-x56-throttle-causes-ghost-inputs/193896

**Comment by MisterChocker** [comment]
Make sure you have no events bound to none existing hardware (e.g. when using the Thrustmaster Airbus Throttle).

**Comment by PottiMc** [comment]
I actually solved this issue. It is not related to A32NX. It's because of ghosting inputs of my X56 HOTAS throttle.

Was not able to completely get rid of the ghosting yet, but I am trying different solutions. This issue can be closed.

Thank you for answering!

**Comment by MisterChocker** [comment]
I had the same issue with my Thrustmaster throttle quadrant, check every assignment you have in your controls (maybe even for all input devices, perhaps except keyboard). This has proven to be a good approach to fix the issue.
