### ISSUE TITLE
Gears do not deploy in air with engines shut off and APU running

### ISSUE THREAD

**Issue by oyvindgjerde** [flybywiresim/a32nx#5917]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-09-18T00:34:38+00:00",
  "ref": "v0.7.0",
  "sha": "e8ea73b3648d48437ca5df55e280a945fd11dab6",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

Gears do not deploy in air with engine shut off, and APU running. I assume the APU should be able to run the hydraulic system, thus lowering the gear without the engines running. The flaps works as normal. 

### Expected behavior

The gear should deploy with APU running and engine shut off in air

### Steps to reproduce

1. While airborne, turn off engines
2. Start APU and wait for it to become online
3. deploy landing gear

### Discord Username (optional)

oyvindgjerde

**Comment by tshomas** [comment]
As Gizmo says in their last bracketed lines, no hydraulics means no landing gear deployment, it's not recommended to use the yellow elec hyd pump through the PTU to drop it either, so gravity gear extension is the only way to drop the gear. The APU itself doesn't actually aid the hydraulics in any form apart from possibly being the only power source for the yellow elec pump.

At the moment, gravity gear extension isn't in the mod as far as I'm aware!

**Comment by MisterChocker** [comment]
Working as intended
