### ISSUE TITLE
[REQUEST] Screens and panel lights should be dimmed, not completely off, at startup.

### ISSUE THREAD

**Issue by FlyingCarpet7** [flybywiresim/a32nx#592]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**

Our airline SOP and other ones that I new about never leave the screens completely off or dark when leaving or securing the aircraft.  It should be dim downed to lowest setting, where you still can see that the screens and panels are on/lit, and then left in that state for the next crew.

(Should also prevent new user of our mod to think that there installation is broken with  dark screens at startup.

**References**

Real life SOP

**Additional context**

**Comment by becas22** [comment]
It's even an Airbus SOP
![image](https://user-images.githubusercontent.com/11005754/92925575-9bf09980-f432-11ea-8754-ce8758397dee.png)

**Comment by PCGamesF1Tech** [comment]
I can confirm this!
One reason was, that older aircraft generations still had CRTs as displays which don't really like beeing switched on and off completely all the time.

**Comment by UncleClapton** [comment]
We have seen SOPs go both ways, and most of the airline SOPs we got said turn them all off. This is why the decision was made to start it all in the off state. Maybe this should be reconsidered though? People who provide support for the mod shouldn't also be trainers of how to fly the aircraft, but thats how it's been for a while :)

**Comment by FlyingCarpet7** [comment]
I raised the question on discord if any of the IRL pilots there had it stated OFF in the SOP but only got replies of them having it on and dimmed only.

**Comment by UncleClapton** [comment]
I'm working on this now.
