### ISSUE TITLE
NW STRG DISC on ECAM missing during pushback[REQUEST]

### ISSUE THREAD

**Issue by Blumski1** [flybywiresim/a32nx#593]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**

Would like to see the nose wheel steering disconnected during push back. 

**References**

NW STRG DISC or N WHEEL STEERG DISC message should be displayed. The message depends on the version of software.

**Additional context**

**Comment by lukecologne** [comment]
I'll look into it
