### ISSUE TITLE
Moving windows

### ISSUE THREAD

**Issue by boomcreeper11** [flybywiresim/a32nx#5933]
### Aircraft Version

Stable

### Description

I think the A32nx could really benefit from moving windows. You'd be able to open windows and move your camera slightly outside the plane, adding to the realsim

### Discord Username (optional)

Scrub Man#4699

**Comment by Benjozork** [comment]
This will be included in the upcoming re-modeled cockpit and exterior.

**Comment by MisterChocker** [comment]
Duplicate of #4589
