### ISSUE TITLE
GPS from Simbrief

### ISSUE THREAD

**Issue by dashawn11** [flybywiresim/a32nx#5946]
### Aircraft Version
Experimental

### Build info

```json
{
  "built": "2021-09-30T04:55:13+00:00",
  "ref": "experimental",
  "sha": "7a5c6d97f4e156a33db1209c5384256be2294b21",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

When I download map from Simbrief, it shows up correctly on selection screen in world wide map. Then when I start it on A320NX (in stable, development, and experimental versions) the map only has one or two turns or straight line but not programmed flight path from gate or runway at any airport. And joystick that I been using with no problems before on A320NX when I lower speed on joystick it goes to thrust reverse. I deleted community folder and started flight simulator with no mods and still having this problem. Weather is another issue. I can no longer save live weather. It started with update 5. I been doing this since 2004 very familiar with how to use A320. Only plane I use. 

### Expected behavior

Correct behavior so issues described above are not happening 

### Steps to reproduce

Weather for saving is shaded. So can't save it. Very familiar how to use the weather. Online traffic and all is working. Live weather is working as well. Using Simbrief for flight path can reproduce the map issue described above. Same with joystick issue.

**Comment by frankkopp** [comment]
You need to import SimBrief directly in the MCDU - ignore the World Map
https://docs.flybywiresim.com/fbw-a32nx/feature-guides/simbrief/
