### ISSUE TITLE
2 Light panel event bugs using  FBW/A320-dev events (via Mobiflight)

### ISSUE THREAD

**Issue by Rascal650** [flybywiresim/a32nx#5949]
### Aircraft Version

Development

### Build info

```json
5c122cf
```

### Describe the bug

Hi,

I just  finished a homemade panel for the EXT LT and I'm trying to program it using Mobiflight and MSFS2020 Events.

FYI: I'm using the A320-Dev build (updated today, build#5c122cf).   

 I'm not sure I know the difference between the Fly By Wire/A320/Lights and Fly By Wire/A320-Dev/Lights in the event list dropdown in Mobiflight.  I tried a lot of different scenarios and the A320-Dev/Lights section seems to work better than the non dev version (Fly By Wire/A320/Lights)

Using the A320-Dev section, all the light events work fine except the following scenarios, which I believe are bugs:

1- Strobe:   Calling a STROBE_LIGHTS_AUTO after STROBE_LIGHTS_OFF should put the strobe switch back into AUTO position, but it will go to ON (skipping the AUTO selection).   As reference, calling STROBE_LIGHTS_AUTO after STROBE_LIGHTS_ON works fine (i.e. switch ends up in AUTO mode)

2- For the LEFT landing light,  the LANDING_LIGHTS_L_OFF and LANDING_LIGHTS_L_ON event seem to be reversed (when looking at the action on the screen).  In other words,  LANDING_LIGHTS_L_ON goes into the middle position (designated as OFF on screen) and LANDING_LIGHTS_L_OFF goes into the top position (designated as ON on screen).
For reference,  the RIGHT landing light does NOT have this problem.

Other than that,  I also build the EFIS and FCU panels and was able to fully program them using the FBW events listed in Mobiflight;  AWESOME work guys!!!!

Thanks!

Pascal

### Expected behavior

See above

### Steps to reproduce

See above

**Comment by frankkopp** [comment]
See https://github.com/flybywiresim/a32nx/issues/5932

**Comment by 2hwk** [comment]
Closing as duplicate, we will be tracking this issue in #5932
