### ISSUE TITLE
FBY/A320/Radio/A320_Neo_FBW_BTN_L_VHF2  does not change the channel (same for VHF1 and VHF3)

### ISSUE THREAD

**Issue by Rascal650** [flybywiresim/a32nx#5950]
### Aircraft Version

Development

### Build info

```json
5c122cf
```

### Describe the bug

in Mobiflight, I'm using Fly By Wire/A320/Radio to program my homemade cockpit. (the radio panel in that case)     The following events don't seem to switch the COMM channel:

- A320_Neo_FBW_BTN_L_VHF1
- A320_Neo_FBW_BTN_L_VHF2
- A320_Neo_FBW_BTN_L_VHF3

The selected channel remains whatever it was before the event was called

### Expected behavior

Should change the selected VHF to the respective channel after the even was called.

### Steps to reproduce

see above

**Comment by frankkopp** [comment]
A320_Neo_FBW_BTN_L_VHF2 are not for the A32NX.

All A32NX variables and events start with A32NX_... .

See https://docs.flybywiresim.com/fbw-a32nx/a32nx-api/
and https://docs.flybywiresim.com/fbw-a32nx/a32nx-api/lvars-events/
https://github.com/flybywiresim/a32nx/blob/master/docs/a320-simvars.md
https://github.com/flybywiresim/a32nx/blob/master/docs/a320-events.md

**Comment by Rascal650** [comment]
Thanks for the reply.  I'm a bit confused about these events.  
When I load Mobiflight and select the "MSFS2020 events", I see a lot of different groups.  There are quite a few "Fly By Wire" groups (among many other airplanes).  Some groups are labelled "Fly By Wire\A320\xxx" and others are "Fly By Wire\A320-dev\xxx".  The list of the events from these sections contain a combination of A320_Neo and A32NX_ events. For instance,  Fly By Wire\A320-dev\Autopilot section contains all the possible actions as "A32NX" such as "A32NX_FCU_SPD_DEC".     
For the EFIS,  there is no "A320-dev" section so I have to choose "Fly By Wire\A320\EFIS".  Under that group,  all the "EFIS" actions are listed but they are all A320_Neo_FBW_xxx  (not A32NX events).  Note that all these "EFIS" A320_Neo events work fine with the latest dev build though (5c122cf).   Other A320_Neo_xxx events don't work though.
Where is Mobiflight building these lists from?  
Also regarding Fly By Wire\A320-dev\Autopilot,  all the A32NX events seem to be working for my FCU panel except for one action: Speed pull (putting speed into selected mode).     The Speed pull event should be labelled "A32NX_FCU_SPD_PULL" to be consistent with the other events (like A32NX_FCU_HDG_PULL).  But this specific event shows up in the drop down as "A32NX_FCU_SPD_PULL_ " (with a _ at the end, followed by a bunch of space). If I select "A32NX_FCU_SPD_PULL_ ", Mobiflight will work fine for that session (i.e. I can change the speed into selected mode). However, when I quit Mobiflight and relaunch it, the rule that uses this event will be broken and I have to reselect this event. I suspect it's because of the typo in the name. Can I fix that myself or do I need to wait for a fix in the next FBW dev build?
I attached a snapshot that shows the apparent typo.
Thanks for your help & support!
Pascal
    On Friday, October 1, 2021, 06:37:25 AM PDT, Frank Kopp ***@***.***> wrote:  
 
 


A320_Neo_FBW_BTN_L_VHF2 are not for the A32NX.

All A32NX variables and events start with A32NX_... .

See https://docs.flybywiresim.com/fbw-a32nx/a32nx-api/
and https://docs.flybywiresim.com/fbw-a32nx/a32nx-api/lvars-events/
https://github.com/flybywiresim/a32nx/blob/master/docs/a320-simvars.md
https://github.com/flybywiresim/a32nx/blob/master/docs/a320-events.md

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by frankkopp** [comment]
I don't think we can give you a lot if information about Mobiflight. You will have to ask them most of your questions. 

We do not support any specific 3rd party application - the industry norm is that these applications need to support the custom aircraft they want to control. 

I have sent you our documentation but of course I'm aware that this might not help you with Mobiflight. Best is you ask them if they support the FlyByWire A32NX and which version (Stable/Dev).

**Comment by Rascal650** [comment]
Thanks for the reply, Frank.   
I had assumed (wrongly it seems) that FBW was making its list of events available (from a XML file for instance or through the SDK) for Mobiflight (and other 3rd party programs) to query and aggregate.
I will try to get help from the Mobiflight community at this point.
FYI:  During my "speed" testing yesterday, I noticed that if I push the speed knob to go to managed mode (using the screen and mouse) and then turn the knob left or right (also using the screen and mouse), the speed value gets displayed next to the "managed" dot.  Is that expected?
Pascal
    On Sunday, October 3, 2021, 05:40:16 AM PDT, Frank Kopp ***@***.***> wrote:  
 
 


I don't think we can give you a lot if information about Mobiflight. You will have to ask them most of your questions.

We do not support any specific 3rd party application - the industry norm is that these applications need to support the custom aircraft they want to control.

I have sent you our documentation but of course I'm aware that this might not help you with Mobiflight. Best is you ask them if they support the FlyByWire A32NX and which version (Stable/Dev).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by frankkopp** [comment]
> support

If you read the link I sent above you see that we have documented our available LVARS and Events for any body to use. 
As we are still in development this is not complete or finalized yet. But anybody incl. Mobiflight has the chance to use it. 

If you read further you see that I have a profile for SPAD which uses many of the variables and esp. the FCU can be fully used on hardware. 

You can DM me on discord. Cdr_Maverick#6475

Also you can close this issue as it is not something we can do fix on our side.

**Comment by Rascal650** [comment]
Thanks Frank;  I'll review the LVARS and events.   FYI: I found out that Mobiflight has a giant list of all the events which include MS' events and all the 3rd party ones (including FBW).  The Mobiflight team helped me on Discord; there was a typo in the event name and I got it fixed.
I'll close the bug report too!
Pascal
    On Sunday, October 3, 2021, 05:06:25 PM PDT, Frank Kopp ***@***.***> wrote:  
 
 



support


If you read the link I sent above you see that we have documented our available LVARS and Events for any body to use.
As we are still in development this is not complete or finalized yet. But anybody incl. Mobiflight has the chance to use it.

If you read further you see that I have a profile for SPAD which uses many of the variables and esp. the FCU can be fully used on hardware.

You can DM me on discord. Cdr_Maverick#6475

Also you can close this issue as it is not something we can do fix on our side.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Rascal650** [comment]
Not an issue after talking to Frank.  Closing
