### ISSUE TITLE
Make all displays text larger

### ISSUE THREAD

**Issue by TLSY2** [flybywiresim/a32nx#5951]
### Aircraft Version

Development

### Description

Hi. 

Since me and many others who like to play at a higher fov, we cant read the PFD'S because of the pixel limitation, however, if the text is bigger we might get more range. 

Maybe this can be integrated as an option or just in general make all the text bigger, it seems too small to me since the begining.

 Thanks in advance!

**Comment by Benjozork** [comment]
The text sizes are realistic for the EIS2 display system present in the A320neo.

**Comment by Benjozork** [comment]
To expand on the above, providing an option to increase them, unless that is possible in the IRL A320 (and I am 99% certain it is not) would break the realism of the aircraft.

**Comment by TLSY2** [comment]
> To expand on the above, providing an option to increase them, unless that is possible in the IRL A320 (and I am 99% certain it is not) would break the realism of the aircraft.

How do you scale IRL to a game or a screen?

**Comment by Benjozork** [comment]
> How do you scale IRL to a game or a screen?

The displays define font sizes that occupy a certain height in pixels on the screen. Those are defined by Airbus and at the moment, we generally respect those exact values.

> Is an option not possible?

It is possible in theory, but not only would it be unrealistic, it would also be complicated to maintain two different text layouts.

**Comment by TLSY2** [comment]
> > How do you scale IRL to a game or a screen?
> 
> The displays define font sizes that occupy a certain height in pixels on the screen. Those are defined by Airbus and at the moment, we generally respect those exact values.
> 
> > Is an option not possible?
> 
> It is possible in theory, but not only would it be unrealistic, it would also be complicated to maintain two different text layouts.

However, the scale in this sim for me it doesnt seem that realistic, things dont look that big... Thats why the text looks extremely small on all the displays.

**Comment by Benjozork** [comment]
We are remodeling the cockpit. However, keep in mind some camera distortion in MSFS might make some scales impossible to get right

**Comment by TLSY2** [comment]
> We are remodeling the cockpit. However, keep in mind some camera distortion in MSFS might make some scales impossible to get right

ok. Its just really annoying that the text is soo small that when fov is over 50 its unreadable especially because of size, the pixels is understandable but with bigger texts more pixels.

**Comment by 2hwk** [comment]
This is actually a bug that was introduced in SU5, before this displays were perfectly readable even at a distance. This is something that Asobo will have to fix.

**Comment by TLSY2** [comment]
> This is actually a bug that was introduced in SU5, before this displays were perfectly readable even at a distance. This is something that Asobo will have to fix. We will not be changing the fonts to be unrealistic. Closing.

I thought this was an Assobo issue, thanks for confirming!
