### ISSUE TITLE
ILS bug

### ISSUE THREAD

**Issue by blooper5** [flybywiresim/a32nx#5953]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-09-29T18:17:16+00:00",
  "ref": "master",
  "sha": "ede8f3216f204d0afcdfd5b9f5864b6cb4d1c5f0",
  "actor": "bouveng",
  "event_name": "manual"
}
```

### Describe the bug

Ils isn't showing up at all when landig ILS KORD and misc other places

### Expected behavior

APPR button green, continues with approach

### Steps to reproduce

1. went on ILS Path 
2. hit appr
3. nothing happened

**Comment by Benjozork** [comment]
Please be more clear. Do you see the ILS diamonds on the PFD ?

**Comment by blooper5** [comment]
its fixed now, nevermind, i just needed to be closer
