### ISSUE TITLE
Fuel consumption ignores time compression

### ISSUE THREAD

**Issue by lonewulf47** [flybywiresim/a32nx#5954]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-10-01T00:43:50+00:00",
  "ref": "master",
  "sha": "5c122cf71ae36739539d9ff5b97951dfa63a96a3",
  "actor": "bouveng",
  "event_name": "manual"
}
```

### Describe the bug

When using time compression the Fuel Consumption/Fuel on Board is not corrected accordingly.

### Expected behavior

Fuel Consumption should be increased accordingto Time Compression Factor

### Steps to reproduce

Fly with Time Compression and check Fuel used

**Comment by donstim** [comment]
Duplicate?  https://github.com/flybywiresim/a32nx/issues/4938
