### ISSUE TITLE
Violent swaying

### ISSUE THREAD

**Issue by blooper5** [flybywiresim/a32nx#5957]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-09-29T18:17:16+00:00",
  "ref": "master",
  "sha": "ede8f3216f204d0afcdfd5b9f5864b6cb4d1c5f0",
  "actor": "bouveng",
  "event_name": "manual"
}
```

### Describe the bug

When i am flying in alaska it starts swaying in the middle of a flight in about 90* sways unconrollibly

### Expected behavior

fly normally

### Steps to reproduce

1. fly in alaska
2. fly
3. SWAY
SWAY
SWAY

**Comment by Benjozork** [comment]
What was your fps at that moment?

**Comment by blooper5** [comment]
felt like 20-70

**Comment by IbrahimK42** [comment]
Did you use high Sim Rate?

**Comment by IbrahimK42** [comment]
A new update in development should solve the issue.

**Comment by blooper5** [comment]
i was +2 sim rate btw the first time, the second i was 0 sim rate not fast or slow

**Comment by IbrahimK42** [comment]
All right. Please test it again with the new version development. If you should any further issues let me know.
