### ISSUE TITLE
[BUG] Decel annunciation-light will always light up for autobreak low

### ISSUE THREAD

**Issue by Kaerbr** [flybywiresim/a32nx#596]
**Mod Version**
V0.2.0

**Describe the bug**
The "decel" light of the autobreak is always lighting up in the low autobreak field, regardless of the autobreak type I chose

**To Reproduce**
1. pick autobreak for landing
2. land the aircraft
3. let the autobreak kick in

**Expected behavior**
In my understanding it should light "decel" which one I ever chose

**Actual behavior**
It will always light up the "decel" light of the low autobreak even if you choose medium

**References**
I chose med. autboreak but the decel light is in low autobreak.
![grafik](https://user-images.githubusercontent.com/70379879/92951953-7a59d700-f45f-11ea-9c67-0619a3a5faf2.png)

**Comment by Coralec** [comment]
Bug replicated.

**Comment by lukecologne** [comment]
Looking into this
