### ISSUE TITLE
Request about the new lights PR. 

### ISSUE THREAD

**Issue by brufervelit** [flybywiresim/a32nx#5962]
### Aircraft Version

Experimental

### Description

sync of the lights now after the PR. But i barely can see the nav lights reflected on the ground from a window view. IRL Its like it was before the PR. You can see them reflected on the ground. (At night obviously) Also happens with the strobe lights, they are weaker than before and you can barely see them reflected in the ground. IRL its like it was before the PR.  Strong reflection on the ground at night from broth nav and strobe lights. Beacon is awesome. Nothing to say about that. 

### Additional info (optional)

I cant see lights as strong as before from the window view. IRL you can see them. Its kinda littlw the portion of terrain that they iluminates now with this new PR. Besides that, beacon is awesome and the synchronisation of the lights is awesome too. 

### Discord Username (optional)

brufervelit#9807

**Comment by brufervelit** [comment]
Some news about this?

**Comment by Benjozork** [comment]
No references provided.

**Comment by brufervelit** [comment]
I described it above. Maybe you need some pics?
