### ISSUE TITLE
Can get into a state where the speed is managed (dot) but the speed value shows instead of ---

### ISSUE THREAD

**Issue by Rascal650** [flybywiresim/a32nx#5963]
### Aircraft Version

Development

### Build info

```json
5c122cf
```

### Describe the bug

I'm getting a speed value with the "managed" dot at the same time.  I think it's a bug. Easy to repro (see steps below)

### Expected behavior

I don't think the speed value should show if the "managed" dot is on.  I believe that it it's in managed mode, we have ---.

I don't think the speed dial should be functional when it's in managed dot.  

### Steps to reproduce

1. During flight, Push the speed knob.  We are in managed mode (--- o)
2.  Now turn the speed knob,   the speed value shows up but the dot is still there (250 o).

**Comment by tracernz** [comment]
That is correct behaviour and allows you to dial in your desired speed before arming selected mode.
