### ISSUE TITLE
Boarding with calculated SimBrief Pax Weight

### ISSUE THREAD

**Issue by Godehardt2003** [flybywiresim/a32nx#5999]
### Aircraft Version

Experimental

### Description

Hello,
I have a virtual airline wich calculates a dynamic passenger weight by the number of male and female people on board. Would it be possible to read this field in the SimBrief XML to calculate the correct weights for the boarding page on the MCDU (https://github.com/flybywiresim/a32nx/pull/5895)?
The pax weight can be read in the XML via "weights->pax_weight" (in lbs).

Actually the weights are only correct with the standard SimBrief pax weight of 104 lbs. 

### Discord Username (optional)

Tom Kadler#9460

**Comment by donstim** [comment]
Just for clarification, the dynamic passenger weight you are referring to is the average passenger weight based on the number of male and female passengers?  For example, if you have 50 male passengers at 180 pounds and 50 female passengers at 140 pounds, you use 100 passengers at 160 pounds each in Simbrief? Does your virtual airline per passenger weight include their baggage weight, or do you add that separately as cargo?

**Comment by Godehardt2003** [comment]
> Just for clarification, the dynamic passenger weight you are referring to is the average passenger weight based on the number of male and female passengers? For example, if you have 50 male passengers at 180 pounds and 50 female passengers at 140 pounds, you use 100 passengers at 160 pounds each in Simbrief? Does your virtual airline per passenger weight include their baggage weight, or do you add that separately as cargo?

Exactly! The weights include the baggage weight. I spoke with some real pilots and they had extremely different values than the default simbrief weight. SimBrief uses 104 KG per pax and one pilot said to me that a male person weights 84 KG including the baggage (baggage which is loaded in the cabin) so it would be a way more realistic if the W&B page could detect the average passenger weight...

**Comment by tracernz** [comment]
> Exactly! The weights include the baggage weight. I spoke with some real pilots and they had extremely different values than the default simbrief weight. SimBrief uses 104 KG per pax and one pilot said to me that a male person weights 84 KG including the baggage (baggage which is loaded in the cabin) so it would be a way more realistic if the W&B page could detect the average passenger weight...

SimBrief uses whatever you set in your airframe:
<img width="342" alt="image" src="https://user-images.githubusercontent.com/9995998/144297532-ee88942b-0558-4046-a77e-769a04835676.png">

**Comment by donstim** [comment]
> 
> Exactly! The weights include the baggage weight. I spoke with some real pilots and they had extremely different values than >the default simbrief weight. SimBrief uses 104 KG per pax and one pilot said to me that a male person weights 84 KG >including the baggage (baggage which is loaded in the cabin) so it would be a way more realistic if the W&B page could >detect the average passenger weight...

Different operators, under different regulatory requirements, can use different passenger weights. Our 84 kg/pax is consistent with the data from here:  https://www.cdc.gov/nchs/fastats/body-measurements.htm. It is represents an average of 50% male/50% female distribution. It does not include either clothing weight or carry-on bag weight. We have elected not to include an additional allowance for clothing or carry-on bags, just the 20 kg for bags loaded into the cargo section.

This is a work in progress. The current plan is to move the passenger/cargo loading into the EFB and to provide more flexibility in loading.  But it may be worth looking into at least allowing the use of a user-specified Simbrief passenger weight.

**Comment by donstim** [comment]
> 
> > When planning a flight, SimBrief calculates your payload by multiplying this value by the number of selected passengers. By default, it's set to 230 lbs (104 kgs), which includes 175 lbs for the passenger and 55 lbs for their bags.
> 
> > You may choose any value. For example, if you prefer to specify the baggage manually using the cargo option, simply enter a value that does not include any baggage weight.

Although you can use any value for passenger weight in Simbrief, 104 kg per passenger (84 pax weight + 20 bags) is hardcoded in the airplane. So if you choose a different weight in Simbrief, the payload in the airplane will not match the Simbrief payload.

**Comment by tracernz** [comment]
> Although you can use any value for passenger weight in Simbrief, 104 kg per passenger (84 pax weight + 20 bags) is hardcoded in the airplane. So if you choose a different weight in Simbrief, the payload in the airplane will not match the Simbrief payload.

What are your thoughts on making use of the SimBrief value when loading from a SimBrief OFP? It might be desirable to allow that flexibility if there are no downsides.

**Comment by Godehardt2003** [comment]
> > Exactly! The weights include the baggage weight. I spoke with some real pilots and they had extremely different values than the default simbrief weight. SimBrief uses 104 KG per pax and one pilot said to me that a male person weights 84 KG including the baggage (baggage which is loaded in the cabin) so it would be a way more realistic if the W&B page could detect the average passenger weight...
> 
> SimBrief uses whatever you set in your airframe:
> <img width="342" alt="image" src="https://user-images.githubusercontent.com/9995998/144297532-ee88942b-0558-4046-a77e-769a04835676.png">
> The help:
> > When planning a flight, SimBrief calculates your payload by multiplying this value by the number of selected passengers. By default, it's set to 230 lbs (104 kgs), which includes 175 lbs for the passenger and 55 lbs for their bags.
> 
> > You may choose any value. For example, if you prefer to specify the baggage manually using the cargo option, simply enter a value that does not include any baggage weight.

Jeah but you can change the pax weight in the API which the va uses. The va system calculates different male and female numbers and calculates then the average pax weight. This is then passed to simbrief.

**Comment by sidnov** [comment]
I think this issue should stand resolved with the new system that separates pax and baggage weight as per the updated Simbrief API.
