### ISSUE TITLE
A32NX flaps usage no longer triggers corresponding FSUIPC event

### ISSUE THREAD

**Issue by EldrichThames** [flybywiresim/a32nx#6005]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-10-12T09:52:50+00:00",
  "ref": "master",
  "sha": "47b8cbfbf808466ff260a1602ed0fffc6203e2f1",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

Functionality-wise, the flaps are working just fine; the problem lies in the fact that the flaps down events don't seem to be registered by FSUIPC anymore (in other words FSIUPC believes I'm not using flaps at all, at any point during a flight).

I'm sorry I can provide any more technical details concerning this issue, as I use FSIUPC mainly to connect the sim to both STKP and a third-party app that records my flight and sends the resulting report back to my virtual airline.

I updated the A32NX to the latest development version this morning before doing my VA flight, and after finishing and checking my report I noticed I had several penalties because supposedly I didn't use flaps at all during takeoff and landing, which naturally wasn't the case.

I'm attaching the FSUIPC log from the affected flight in case it has useful information for you guys. If you need any other files let me know (I won't be using MSFS until this issue is solved, as I only do flights for my VA and right now MSFS is unusable to me).

[FSUIPC7.log](https://github.com/flybywiresim/a32nx/files/7333323/FSUIPC7.log)

### Expected behavior

Flaps down events should be registered by FSIUPC and forwarded to any apps connected to it.

### Steps to reproduce

- Run MSFS with FSUIPC
- Set your flaps down (not sure if there's a way to check for FSIUPC events while running, though)

### References (optional)

I'm attaching screenshot of my VA's flight report, showing the phases where flaps are expected to be deployed by pilots. I've never had this issue before today, and I've always flown with the A32NX.

![Taxi_Out](https://user-images.githubusercontent.com/92403194/137033917-651d9f0d-a219-4d28-b1de-0bd8b833cac0.jpg)

![Initial_Approach](https://user-images.githubusercontent.com/92403194/137033940-cd5a3a82-1e8a-479a-bdab-20dc8e07a0fb.jpg)

![Final_Approach](https://user-images.githubusercontent.com/92403194/137033950-86ea7daa-3ccc-4452-a67d-9328bfa73374.jpg)

### Additional info (optional)

I'm using FSUIPC7 version 7.2.10 (which is the latest one, I think), and I used this same version of FSUIPC about 18 days ago, with the latest dev version of the A32NX of that day, with no issues whatsoever.

### Discord Username (optional)

Eldrich Thames#9392

**Comment by crocket63** [comment]
Possibly yes. Solution of just writing this back and hope it doesn't break the positions we directly write would still possibly help

**Comment by EldrichThames** [comment]
As commented on Issue #6014 , the changes made to the flaps logic has been reverted, so the problem described here should also been solved. I'll close this issue. Thank you for your assistance, and keep up the amazing work you guys are doing! O7
