### ISSUE TITLE
[BUG] Brake temp continuously increases in air when brakes are held down

### ISSUE THREAD

**Issue by ThatRedMelon** [flybywiresim/a32nx#601]
**Mod Version**

Master

**Describe the bug**

If brakes are held down, even when wheels are stopped (and in the air), the brake temp on the WHEEL ECAM page continuously increases as a rapid rate.

**To Reproduce**

1. Go in the air (I have verified it occurs on takeoff and approach.
2. Lower landing gear
3. Hold down brakes

**Expected behavior**

Brake temp (on WHEEL ECAM) increases a small amount if wheels are spinning, and then stop increasing when wheels are stopped.

**Actual behavior**

Brake temp (on WHEEL ECAM) continuously increases, even when wheels are held down.

**References**

Can't get a video but here is a screenshot of the high temperatures (they increase far above this)
![1250410_20200911183958_1](https://user-images.githubusercontent.com/34657891/92956216-6792d280-f45e-11ea-8bae-263519cc953d.png)

**Additional context**

First experienced on approach into Ankara Esenboga Airport but tested on multiple airports at different parts of the flight and tested on multiple liveries.

**Comment by Benjozork** [comment]
I will look into this.

**Comment by Coralec** [comment]
Bug replicated.

**Comment by ThatRedMelon** [comment]
Fixed in #618
