### ISSUE TITLE
Knob selection acceleration

### ISSUE THREAD

**Issue by Arsaphes** [flybywiresim/a32nx#6033]
### Aircraft Version

Development

### Description

When using the mouse wheel on a knob, for setting a heading for example, as soon as I turn the mouse wheel "too fast", there is no direct relation between 1 degree and 1 wheel click any more. So, if you turn the wheel slowly, one wheel click change the heading by 1 degree. If you turn it faster, let's say that 10 wheel clicks change the heading by 4 degrees. Finally, it takes a long time to set a new heading, which could be uncomfortable when you're flying under ATC like IVAO for instance.
Of course, it my be related to my own configuration as well, no clue.
But generally speaking, such systems use an acceleration logic. When you turn the knob slowly, one click will change the setting by 1 unit. But if you turn it faster, one click will change the setting by several degrees. This "acceleration" logic let the pilot to easelly and quickly set a new value on the desired system.
Once again, I only get access to my own configuration, so I don't know if this problem is known by other users. Sorry if it's only me.

And thanks a lot for your great job, I forgot the FlightFactor A320 on x-plane to this add-on, totally worth it!

PS: Sorry, I just had a look at the repo and noticed the `getRotationSpeed()` function within the `A320_Neo_FCU_Heading` class used to change the selectedValue value. So, it's just not working for me...

**Comment by derl30n** [comment]
Issue resolved
