### ISSUE TITLE
Mouse interaction with systems

### ISSUE THREAD

**Issue by Arsaphes** [flybywiresim/a32nx#6036]
### Aircraft Version

Development

### Description

Using this A320 with IVAO, with radar guidance provided, is very difficult. Because of the interactions implementation with the FCU (and all the others systems), it's not realistically flyable. It's very hard, for instance, to pull the heading knob, doing other things at the same time. Trying to make the little down arrow is just too hard and take too much time. (I'm using the "legacy" mode with a mouse). What's more, when you turn, the whole panel move, so the mouse cursor, so... 
Any chance to have an implementation like the FSLab A320? The way they setup the interactions with the systems using the mouse is just so natural... Very intuitive and easy to use, in every situations.

Thanks again for all your work, fantastic job!

**Comment by derl30n** [comment]
Please search for similar issues first before opening new ones.

https://github.com/flybywiresim/a32nx/issues/2953 and https://github.com/flybywiresim/a32nx/issues/2884
