### ISSUE TITLE
Add simulation variables for the Clock

### ISSUE THREAD

**Issue by MedicoreV8** [flybywiresim/a32nx#6049]
### Aircraft Version

Stable

### Description

Currently the Clock/Chronograph has two events: A32NX_CHRONO_TOGGLE and A32NX_CHRONO_RST.
The display is done via JS or something?
It would be nice to have all the events/vars at our disposal as explained on the Documentation: https://docs.flybywiresim.com/pilots-corner/a32nx-briefing/flight-deck/front/clock/

### Discord Username (optional)

Wokkel#7194

**Comment by kacpersurf** [comment]
Hi, just been advised of this request and it would great to have it as i'm trying to map the clock with chrono, utc and ET on 7seg displays in my home cockpit, but seems there is no ref available. is there a plan to introduce this? only inputs are available but not outputs

is there any plans to implement it in near future?

**Comment by ssewell** [comment]
I'm currently working on a digital clock module for my A320 MIP. I'll look into adding the simvars for the CHR and ET clock displays to the Clock component.

**Comment by kacpersurf** [comment]
that is awesome!
what about the UTC part?

**Comment by ssewell** [comment]
@kacpersurf The UTC portion of the Clock instrument is already accessible, as the FBW A32NX uses the Generic MS/Asobo simvars. Here's the list with their corresponding data types.
```
(E:ZULU TIME, second)
(E:ZULU DAY OF MONTH, number)
(E:ZULU MONTH OF YEAR, number)
(E:ZULU YEAR, number)
```
