### ISSUE TITLE
[REQUEST] Automatically calculate ZFWCG after putting in the ZFW

### ISSUE THREAD

**Issue by Delgado123321** [flybywiresim/a32nx#605]
**Is your feature request related to a problem? Please describe.**

-

**Describe the feature you'd like to see implemented**

I would like to see the ZFWCG to be calculated after putting in the ZFW in the MCDU.

**References**

**Additional context**

**Comment by lousybyte** [comment]
Is this true to real life or custom request?

**Comment by UncleClapton** [comment]
Will need second confirmation but I believe both values need to be added manually.

In sims, however, it's common to have an option to calculate the value, or to have a easy way to get the correct value.

I'm not sure what approach is best here. Maybe let the calculated value fill in the input like with v-speeds?

**Comment by lousybyte** [comment]
ZFW is already entered and the ZFWCG is also already available from the sim's fuel management page, I'm all up for automating it in the CDU as well, unless someone has strong feelings against this.

**Comment by Delgado123321** [comment]
I think you have to put it in manually in the real plane, however it would be nice to have that option as the ZWFCG can only be viewed in the main menu and not ingame. Maybe also make a option to have it put in automatically.

**Comment by lousybyte** [comment]
Already pushed a PR, see above.

**Comment by lousybyte** [comment]
This is already in base game.
