### ISSUE TITLE
GW != ZFW + BLOCK After second Flight

### ISSUE THREAD

**Issue by Lucky38i** [flybywiresim/a32nx#6053]
### Aircraft Version

Development

### Build info

```json
Latest Build
```

### Describe the bug

The GW does not match up with the ZFW + BLOCK as reported on the the FUEL PRED Page. This inconsistency is also reflected in the PERF Page which uses the incorrect GW.

![gw](https://cdn.discordapp.com/attachments/738864300818432023/900713434419716146/unknown.png)

This ticket is in reference to a conversation had with raelias#5157 starting [here](https://discord.com/channels/738864299392630914/738864300818432023/900713437716418560).

### Expected behavior

The GW should match ZFW + BLOCK

### Steps to reproduce

1. Select aircraft and choose fuel, leave weights as default
2. Load aircraft and fly route.
3. Land aircraft and refuel using toolbar, leave weights as default.
4. Observe FUEL PRED page for inconsistency

### Discord Username (optional)

raelias#5157

**Comment by donstim** [comment]
Really?  I wasn't aware there was an overt decision to dumb the airplane down like this. I was under the impression we were going for maximum realism. May as well close this issue as it is a natural consequence of that decision. 🙁

**Comment by tracernz** [comment]
> 
> 
> Really? I wasn't aware there was an overt decision to dumb the airplane down like this. I was under the impression we were going for maximum realism. May as well close this issue as it is a natural consequence of that decision. 🙁

I don't think we really decided. Just didn't change it yet... We should change it though as you say. 👍

**Comment by derl30n** [comment]
So has it actually changed by now?

**Comment by tracernz** [comment]
No I don't think so. We really do need to sort this, and the related warnings about ZFW/ZFWCG/GW as they are required for more and more systems, especially VNAV.

**Comment by sidnov** [comment]
This issue should now be fixed with the merge of #7291 and #5895
