### ISSUE TITLE
Rain is not audible in cockpit

### ISSUE THREAD

**Issue by jaoord** [flybywiresim/a32nx#6055]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-10-21T07:55:04+00:00",
  "ref": "master",
  "sha": "d3754f4b5ee5f6b6f44eaa787e0ec4c27f105748",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

When it's raining, you don't hear it in the cockpit

### Expected behavior

I think it should be audible in the cockpit but I'm not a RL 320neo pilot

### Steps to reproduce

1. Spawn in a place where it's raining
2. with everything off, I think you should be able to hear the rain

**Comment by hotshotp** [comment]
Yep. I will work on this soon

**Comment by doggydogg13** [comment]
Hi! any news about this?

**Comment by hotshotp** [comment]
> Hi! any news about this?

No. It is not a pressing issue and I have enough sound stuff on my hands. I will work on it when I feel motivated to, as now there are a lot of things to do, such as a380 sounds.
