### ISSUE TITLE
correct speed constraint handling

### ISSUE THREAD

**Issue by Rascal650** [flybywiresim/a32nx#6056]
### Aircraft Version

Development

### Build info

```json
d3754f4 (and before) Also repro in stable
```

### Describe the bug

When comparing the flight plan in the ND against the navigraph chart,   I noticed that often the SPEED constraint is shown at the PRECEDING waypoint instead of the expected one

### Expected behavior

Speed  constraints in FP should match the Navigraph chart

### Steps to reproduce

1 - I created a SimBrief flight from KSJC (origin does not really matter) to KPDX.
2- From FBW A320 (latest dev release), I spawned on KSJC runway.
3- Go to MCDU → init: load the flight plan
4- MCDU → F-PLN, select KPDX, choose arrival
5- Select ILS10R runway, then selectTMBRS2 STAR (GALLO transition)
6- Check the F-PLAN (by scrolling up and down arrow on MCDU).
7- Noticed that the speed restrictions are there but they show up on the flight plan one waypoint too early.

Examples:
PORTL has the 270kn restriction on the chart but it shows up at MOXEE
Same things for TMBRS and VANTZ, MYCRO and SSAIL

See snapshots. below

### References (optional)

![TMBRS2](https://user-images.githubusercontent.com/88073848/138353428-c6ae6fa3-a366-44d2-875e-7af737b9109f.jpg)
![20211021_091712](https://user-images.githubusercontent.com/88073848/138353450-7ebbfe03-c7b3-4dae-ac85-a1b434550799.jpg)
![20211021_094409](https://user-images.githubusercontent.com/88073848/138353462-e56701a7-ab06-4211-b4e1-3e55030a6f85.jpg)

### Additional info (optional)

I first  sent this report to NAVIGRAPH.  They were able to check that with another plane,  the flight plan shows the speed constraint at the right place.   Here is a link to my chat with Navigraph:

https://forum.navigraph.com/t/constraint-alt-speed-are-not-consistent-between-nav-display-and-chart-using-flybywire-320/6414

Note: I'll file the missing mandatory ALT constraint (@ ARCHI, SFO approach) as a different bug since it seems to be missing (as opposed to show early).

**Comment by Kimbyeoungjang** [comment]
> Ignore my rookie question: What's cFPM?

Custom Flight Plan Manager

You can try it via installer Experimental version or you can check https://github.com/flybywiresim/a32nx/tree/autopilot-custom-fpm this branch

**Comment by Rascal650** [comment]
I understand the  VNAV dependency.  However the magenta CSTR markers on the ND should match the Navigraph maps.   Right now,  it's confusing because there are many inconsistencies and I end up looking at the charts all the time.    I'm not using VATSIM (yet) but I can imagine that the navigation display's magenta CSTRs are useless when using VATSIM because they contradict the navigraph charts (which I believe are the gold standard for ATC).

Slowing down at the waypoint (not after) is the pilot's responsibility.  When looking at a STAR or SID navigraph chart,  the speed constraint is at the expected waypoint and the pilot has to anticipate the speed change if needed before reaching the waypoint.  I would expect it to be the same on the A320 ND when the CSTR button is turned on.  According Richard @ Navigraph, that's how it works for the Working Title C4 (which seems to be the reference for Navigraph).

If it's difficult to compute the "optimal" speed for each waypoint because VNAV is not working, at least we could show the speed constraints at the CORRECT waypoint in the ND for now. This way,  the CSTR button would be in sync with the charts and a useful feature until VNAV and the new cfpm is implemented.  Just my view as a user...:)

**Comment by tracernz** [comment]
> I understand the VNAV dependency. However the magenta CSTR markers on the ND should match the Navigraph maps. 

They do in the new ND on the experimental branch. dev is still using the Asobo ND and flight plan manager where it is not correct.

> Slowing down at the waypoint (not after) is the pilot's responsibility. When looking at a STAR or SID navigraph chart, the speed constraint is at the expected waypoint and the pilot has to anticipate the speed change if needed before reaching the waypoint.

No, the A320 anticipates and slows down for you in managed speed mode. The CJ4 autoflight system is much more primitive.

**Comment by Rascal650** [comment]
Excellent! I created a quick FP with the same TMBRS2 approach with the EXPERIMENTAL version and you are right;  CSTR shows the right ALT and SPEED restriction (at the correct waypoints).  That was my main complain with the DEV version.  

Here are the new snapshots

There is a discontinuity between PUBBB and TRAYL. What would cause that?

![experimentalND](https://user-images.githubusercontent.com/88073848/138388766-dd3b8a68-8f3a-4cdf-8b5f-0376e86c27f7.jpg)
![experimentalFP](https://user-images.githubusercontent.com/88073848/138388772-b60ab454-f272-4ab2-b5ed-3981cbb1b77b.jpg)

**Comment by Benjozork** [comment]
There is a MANUAL leg coded in the navdata, which is a segment that never sequences. This is normal and not a bug. You cannot clear those discontinuities - you would usually perform a DIRECT TO to TRAYL or any other waypoint after.

**Comment by tracernz** [comment]
> 
> 
> Discontinuity's can be cleared. Unless this has changed as of late. Video reference in real life @ 8:12 https://www.youtube.com/watch?v=twwUjHXdNVU

That is not after a manual leg. Only some discontinuities can be cleared... others require changes to the flightplan before they can be cleared (or disappear).

**Comment by derl30n** [comment]
Whats the status on this issue?

**Comment by tracernz** [comment]
Sorted. 👍
