### ISSUE TITLE
Part of the MFD is broken, and NAV mode is broken.

### ISSUE THREAD

**Issue by Pappy100** [flybywiresim/a32nx#6057]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-09-18T00:34:38+00:00",
  "ref": "v0.7.0",
  "sha": "e8ea73b3648d48437ca5df55e280a945fd11dab6",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

I manually loaded a flight plan into the MCDU as usual, from LSZH to UKBB. After takeoff, I engaged the autopilot and engaged Managed Heading Mode. The top part of the MFD was frozen, and all values except the wind indicator and the TAS indicator, showed zero. The rest of the MFD worked fine, as you can see in the image. The NAV mode, or Managed Heading Mode, turned the plane to heading 00°, and it stayed there until I manually changed the heading.

Image of the PFD and MFD.
![image](https://user-images.githubusercontent.com/53382314/138350478-0d5d9d87-6e43-4492-b50f-397333fe4bbe.png)

Image of the VFR map, showing my location, and the route the plane should follow.
![image](https://user-images.githubusercontent.com/53382314/138352455-c173aa94-d591-4925-b842-41c0f3d212a8.png)

### Expected behavior

The top part of the MFD should be showing proper values, such as my ground speed and the heading, distance, and ETA of the next waypoint. With the autopilot and NAV mode engaged, the plane should be following my flight plan.

### Steps to reproduce

Load into an airport's gate, and manually input a flight plan into the MCDU. Take off, and engage the Autopilot with Managed Heading Mode engaged. Part of the MFD will be broken, and the plane follows heading 00°.

### Additional info (optional)

I have had many successful flights with Stable version 0.7.0, but some have had various issues with NAV mode. This last one was the worst one so far, with NAV mode being completely broken, and only following a heading of 00°.

### Discord Username (optional)

Pappy100#7123

**Comment by tracernz** [comment]
> v0.7.0

This version does not fully work on SU6.

**Comment by Pappy100** [comment]
I flew the same departure, using the same flight plan, with both the developmental and experimental versions, and both worked correctly.

**Comment by tracernz** [comment]
Thanks for checking. :)
