### ISSUE TITLE
missing ALT constraints in approach (Navigraph data & chart)

### ISSUE THREAD

**Issue by Rascal650** [flybywiresim/a32nx#6058]
### Aircraft Version

Development

### Build info

```json
d3754f4  (also repro in stable)
```

### Describe the bug

Was flying to KSFO, using the ILS28R approach.    I noticed that the mandatory  7K ft @ ARCHI did not make it to the flight plan. I loaded the FP from Simbrief (if that's relevant).   Problem may be more rampant than this single occurence.

### Expected behavior

ALT restriction should be added to the A320 FP  (like it is in the WT CJ4 plane that Navigraph tested, see below)

### Steps to reproduce

1 Create a flight plan, from KSMF to KSFO from Simbrief, export it
2-  From the departing runway,   go to INIT to load simbrief, then go to F-PLN to add the approach
3- Choose the ILS28R  Approach
4-  Check the ARCHI waypoint on the Navigraph chart:  must be at 7K ft
5- Check the flight plan: there is no restriction.

See snapshots below

### References (optional)

![sfo-ils28r](https://user-images.githubusercontent.com/88073848/138354661-6cf47dd0-4c8e-4bef-ba05-4867960cd0e2.jpg)
![sfo-approach](https://user-images.githubusercontent.com/88073848/138354704-1a0af0d6-46fc-4446-841a-6d16dbbd7dab.jpg)

### Additional info (optional)

I sent this to Navigraph and they confirmed that, using the WT CJ4 mod airplane,   that the FP had a 7k restriction in the FP.  Here is a link to the Navigraph chat  (ignore the other problem of SPEED restriction showing too early, I reported another bug for that)

https://forum.navigraph.com/t/constraint-alt-speed-are-not-consistent-between-nav-display-and-chart-using-flybywire-320/6414

**Comment by tracernz** [comment]
I can’t remember exactly what cfpm does off-hand, but I suspect what it does is delete the IF leg when joining the previous legs up, losing it’s constraints in the process. This should be correct in the the new fpm as I discussed it a few times with Ashie.

**Comment by 2hwk** [comment]
Fixed by 4953 closing ☑️
