### ISSUE TITLE
[BUG] "NO DH" displayed without entered minimum

### ISSUE THREAD

**Issue by PCGamesF1Tech** [flybywiresim/a32nx#606]
**Mod Version**

0.2

**Describe the bug**

"NO DH" is displayed on PFD after activating approach phase. 
This is not correct. 
It's not a reminder function for a forgotten minimum. 
It is an actual/lowest minimum for CAT 3 DUAL approaches and needs "NO" to be entered as a DH on PERF APPR page. 

**To Reproduce**

1. Choose an airport for departure (LPMA Rwy23) 
2. No entries whatsoever, TOGA, Flaps 3 and into the pattern
3. <- Activate Appr Phase on base 
4. "NO DH" appears on PFD

**Expected behavior**

Line in PFD should be blank

**Actual behavior**

"NO DH" displayed without any data on the PERF APPR page entered

**References**

**Additional context**

**Comment by devHazz** [comment]
FIxing this, expect a pull request from me soon.

**Comment by devHazz** [comment]
How did you replicate this exactly? did you put in Point A to Point B or did you just set a departure?

**Comment by Benjozork** [comment]
@PCGamesF1Tech, please include reproduction steps in bug reports ;)

**Comment by PCGamesF1Tech** [comment]
Added steps to reproduce!

**Comment by devHazz** [comment]
Cheers, I've chucked my fix into the game and I'll see if its fixed.

**Comment by devHazz** [comment]
[https://github.com/flybywiresim/a32nx/pull/646](url)

**Comment by devHazz** [comment]
#646

**Comment by hotshotp** [comment]
decision height now implemented
