### ISSUE TITLE
[BUG] Vfe indication wrong

### ISSUE THREAD

**Issue by PCGamesF1Tech** [flybywiresim/a32nx#608]
**Mod Version**

0.2

**Describe the bug**

Vfe next (max speed for next flap setting, two little amber dashes = on speed tape) is too low (215kt), it should be 230kt

**To Reproduce**

1. Fly around... 

**Expected behavior**

Amber dashes at 230kt. 
Should also change the max speed red band after "Flaps 1" (slats only) to 230kt.

**Actual behavior**

Vfe next (Flaps 1) at 215kt

**References**

Clean, Vfe at 215kt (iso 230kt)

![IMG_20200913_013714](https://user-images.githubusercontent.com/39101086/93007060-4d431c80-f564-11ea-9721-aeba833e08f9.jpg)

Flaps 1 - Vfe next at 200kt OK - red band at 215kt wrong
AND
Green dot speed still displayed (should disappear with Flaps 1 and on)

![IMG_20200913_013750](https://user-images.githubusercontent.com/39101086/93007053-44eae180-f564-11ea-8ea1-2c5f090d899e.jpg)

Flaps 2 - Vfe next at 185 OK - red band at 200kt OK (green dot still displayed...) 

![IMG_20200913_013902](https://user-images.githubusercontent.com/39101086/93007068-6fd53580-f564-11ea-90d3-d92d0a66589e.jpg)

**Additional context**

**Comment by PCGamesF1Tech** [comment]
Reported via Zendesk as well...

**Comment by MisterChocker** [comment]
fixed by #2722
