### ISSUE TITLE
[BUG] no altimeter setting on ISIS

### ISSUE THREAD

**Issue by PCGamesF1Tech** [flybywiresim/a32nx#609]
**Mod Version**

0.2

**Describe the bug**

There is no altimeter setting shown on ISIS (QNH or STD) 

**To Reproduce**

1. Have a look

**Expected behavior**

A line should show the current altimeter setting

**Actual behavior**

No altimeter setting at all

**References**

**Additional context**

**Comment by UncleClapton** [comment]
I could look into adding this but will need reference photos to get it right.

**Comment by UncleClapton** [comment]
RL:
![](https://clapton.dev/u/2009/0bf7ca59.png)

![](https://clapton.dev/u/2009/e89f15dc.jpg)

From sim planes:
![](https://clapton.dev/u/2009/277fd2ea.png)

**Comment by PCGamesF1Tech** [comment]
Exactly, thanks!
