### ISSUE TITLE
Flight Plan randomized 

### ISSUE THREAD

**Issue by Shituation** [flybywiresim/a32nx#6091]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-09-18T00:34:38+00:00",
  "ref": "v0.7.0",
  "sha": "e8ea73b3648d48437ca5df55e280a945fd11dab6",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

Been tired of MS embedded flight planner that didn't work too, so I made my plan with little navmap.
Made a flight plan from SUMU to SABE (this is SABE approach segment):
![sumu to sabe navmap](https://user-images.githubusercontent.com/43975882/139120281-35523262-6348-4b8a-980a-29c7e32f4c66.jpg)

Then loaded the plan on MSFS, but look at SABE approach:
![sumu to sabe](https://user-images.githubusercontent.com/43975882/139120396-67ee684c-4aec-48b5-aa9e-98db84b94fea.jpg)

Then once in the plane, look at what de ND shows for flight plan:

![sumu to sabe MCDU](https://user-images.githubusercontent.com/43975882/139120481-e747a795-0136-4ec4-8d0b-a8be8c8336ee.jpg)

This didn't happen with stock asobo's A320.

### Expected behavior

To be able to make a flight plan and for it to be honored by the flight sim.

### Steps to reproduce

1. Use the attached .pln (flight plan) and load it into MSFS
2. Look at the flight plan searching for inconsistencies
3. Start the flight and check what is actually loaded on the pla
[(SUMU) to (SABE).zip](https://github.com/flybywiresim/a32nx/files/7428345/SUMU.to.SABE.zip)
ne

**Comment by revargne** [comment]
I have this issue without the MSFS planner. Tried entering the flight plan through MCDU and loading from simBrief.

The flight plan looks good until I enter the arrival. The arrival is always screwed up and I would have to fly funny loops and impossible angles.

Tested it a few hours with every version (stable/dev/experimental) but it makes no difference. At the moment I'm not able to create a usable flight plan in the fbw a320.

(In addition to that the experimental shows flight plan discontinuities where there are none)

**Comment by Benjozork** [comment]
> I have this issue without the MSFS planner. Tried entering the flight plan through MCDU and loading from simBrief.
> 
> The flight plan looks good until I enter the arrival. The arrival is always screwed up and I would have to fly funny loops and impossible angles.
> 
> Tested it a few hours with every version (stable/dev/experimental) but it makes no difference. At the moment I'm not able to create a usable flight plan in the fbw a320.
> 
> (In addition to that the experimental shows flight plan discontinuities where there are none)

Please provide more information. Screenshots, routes, etc.

Also, I'm confused by your comment about discontinuities. What makes you say there should not be a discontinuity?

We can't help with no details at all about your issue.

**Comment by revargne** [comment]
Will provide some screenshots later this day. It's 12:40am here.
Just the two routes I tried today:
EDDH-EDDF
EDDH-LSZF

For the latter one the route from simBrief is:
EDDH/15 IDEKO7D IDEKO N850 NIE DCT EDEGA DCT OMOGI T721 RILAX
RILAX2A LSZH/34

As soon as I enter the STAR RILAX2A the VIA AMIKI and a lot of crap waypoints are filled in. I tried to set NO VIA but this is ignored. Always AMIKI plus crap.

About the discontinuities:
They appeared in the middle of a flight plan loaded from simBrief. I tried to fill the gap but in the end got something like:
...
EDEGA
F-PLAN DISCONTINUITY
EDEGA
...

Entering the same waypoint again was my last try to fill the gap as no other attempt worked.

**Comment by revargne** [comment]
I've to look into the flight plan some more. It seems that only some arrivals producing a strange route.

The problem with the discontinuities is reproducdable in experimental. Same flight plan is working fine in stable and dev.
When I open the last waypoint before the discontinuity it shows the correct airway to the next waypoint.

![fplan](https://user-images.githubusercontent.com/93453376/139601776-af935d95-8d47-4e8b-aa7c-52d0630a0cb6.jpg)
.

**Comment by elcosomalo1** [comment]
This is kind of funny...
![image](https://user-images.githubusercontent.com/43975882/139605872-b9203a69-a29b-47a3-8684-2b5d62278684.png)

And yes..  flight plan gets random descontinuities for me too:
![image](https://user-images.githubusercontent.com/43975882/139605888-1de165d8-3aa1-46b2-9091-9a58094295b8.png)

**Comment by elcosomalo1** [comment]
Using the new stable version 0.7.1

Flight plan loaded better now at least on the last session I played.

On the approach part, something weird happened.
I was flying straight to VANAR. AP was connected, green line on target on the ND.
Suddenly the green line disappeared and reappeared on a different angle. I had no mayor problems since the plane kept flying to VANAR.

(blue line was the flight plan original path)
![image](https://user-images.githubusercontent.com/43975882/139714176-25471297-2144-4dd4-860a-d124745fa542.png)

**Comment by elcosomalo1** [comment]
Flight plan seems to be loaded better now (tried a couple of flights SUMU to SABE and vice versa), the only weird behavior that I experienced is the one from the post above and only on flights from SUMU to SABE and only on that part of the flight.

**Comment by tracernz** [comment]
Is this still an issue?

**Comment by derl30n** [comment]
Please retry with current master aka development version and re-open if still an issue.

**Comment by Shituation** [comment]
https://github.com/flybywiresim/a32nx/issues/7007#issue-1191028709
