### ISSUE TITLE
FBW Bank Angle Protection Error

### ISSUE THREAD

**Issue by xdashdriver** [flybywiresim/a32nx#61]
There appears to be bank angle protection at 66 degrees to the left but no protection when rolling to the right.

**Comment by blitzcaster** [comment]
Bank Angle Protection also does not displayed correctly on PFD. There should be "green equal sign" when flying on normal law.
![Bank Angle Protection](http://www.a320dp.com/A320_DP/flight-controls/images/pfdbankprotection.jpg)
Source: http://www.a320dp.com/A320_DP/flight-controls/sys-7.3.18.html

**Comment by xdashdriver** [comment]
If we're including symbology in this thread then the same green equals signs are missing from the pitch and overspeed limitations too.

**Comment by ko-zone** [comment]
Hey guys, 

So as of recently, we have started reworking on the FBW and Autopilot implementation, we hope to improve the current FBW system and will have more information soon!

Regards, 
KO

**Comment by PCGamesF1Tech** [comment]
Bank angle protection seems correct now on 2nd update for Fs2020.
67° left&right max (max deflection) and rolls back to 33° (no deflection)

**Comment by NathanInnes** [comment]
Closing issue as latest patch resolves issue.
