### ISSUE TITLE
[REQUEST] IRS INIT> Button on MCDU INIT Page

### ISSUE THREAD

**Issue by Zyonix007** [flybywiresim/a32nx#610]
The current MCDU does not have a ~~align IRS~~ IRS INIT button

**Describe the feature you'd like to see implemented**

The MCDU should have a ~~Align IRS~~ IRS INIT button when the IRS is set to nav

**References**
 
toliss

**Comment by Benjozork** [comment]
note to anyone who wants to work on this : This is not a real A320 feature, but a QoL shortcut.

**Comment by Zyonix007** [comment]
It is a real thing. It's like pos init on Boeing

**Comment by Benjozork** [comment]
> It is a real thing. It's like pos init on Boeing

No, ADIRS takes time to align. POS INIT is for setting the initial position and IRS will still take time to align.

**Comment by Zyonix007** [comment]
Correct Airbus has a button called align IRS that functions like pos unit.
See here https://youtu.be/o3--ALDKLUc

**Comment by UncleClapton** [comment]
For quick visual reference of page design

![](https://clapton.dev/u/2009/9a3386f9.png)

**Comment by Externoak** [comment]
I'm currently working on a IRS INIT page.

Current status:
![image](https://user-images.githubusercontent.com/17742637/93017547-e8221200-f5c9-11ea-9a90-9821ae8eb316.png)

**Comment by Externoak** [comment]
Mentioning issue https://github.com/flybywiresim/a32nx/issues/401

**Comment by UncleClapton** [comment]
Looks great!

**Comment by AdenFlorian** [comment]
trying to figure out if this issue is for the QoL feature, or the IRS INIT page...

**Comment by AdenFlorian** [comment]
@Zyonix007 please provide a picture of this "align IRS button" that you're talking about.

**Comment by Zyonix007** [comment]
IRS init is what i mean

**Comment by Zyonix007** [comment]
[image: image.png]

**Comment by Externoak** [comment]
@AdenFlorian I think previous versions of airbus had a Align IRS button (not 100% sure since i'm no pilot) check my comment https://github.com/flybywiresim/a32nx/pull/629#issuecomment-691631469 first reference.

**Comment by AdenFlorian** [comment]
@Externoak that reference is for the old CRTs, this video shows the newer LCDs which show IRS INIT: https://www.youtube.com/watch?v=o3--ALDKLUc&feature=youtu.be

**Comment by AdenFlorian** [comment]
@Zyonix007 the image didn't upload

**Comment by Externoak** [comment]
@AdenFlorian I thought so :), currently working on it as shown: https://github.com/flybywiresim/a32nx/issues/610#issuecomment-691662904
