### ISSUE TITLE
Shimmering landing lights?

### ISSUE THREAD

**Issue by ErikNL80** [flybywiresim/a32nx#6100]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-10-28T23:33:40+00:00",
  "ref": "master",
  "sha": "cb3c2d6612fa6337eb3345fdfd0675a082fab47c",
  "actor": "BlueberryKing",
  "event_name": "manual"
}
```

### Describe the bug

Haven't flown for a while, and after updating to the latest DEV and Sim Update 6 I notice the landing lights are shimmering if you are in external view. It looks really odd, just like they flicker like a strobe.

### Expected behavior

I would expect a solid beam of the landing lights as it was before.

### Steps to reproduce

1. Start a flight
2. Enable landing lights
3. Take off
4. Watch the landing lights from an external view
![LandingLightds](https://user-images.githubusercontent.com/71258178/139395201-ea856629-51f6-4927-8e28-6db12e8798df.png)

**Comment by BlueberryKing** [comment]
As pointed out by @youngryan7, have you tried this in other aircraft?

**Comment by ErikNL80** [comment]
Confirm it happens on other aircraft as well..

**Comment by 2hwk** [comment]
Closing as this is a MSFS and not A32NX bug.
