### ISSUE TITLE
Incorrect altitude bug on external view

### ISSUE THREAD

**Issue by hiroooo1997** [flybywiresim/a32nx#6104]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-10-28T23:33:40+00:00",
  "ref": "master",
  "sha": "cb3c2d6612fa6337eb3345fdfd0675a082fab47c",
  "actor": "BlueberryKing",
  "event_name": "manual"
}
```

### Describe the bug

Altitude bug on external view always indicates 5000 no matter what altitude is selected.

### Expected behavior

Altitude bug is the same as selected altitude.

### Steps to reproduce

1.  Start up and select any altitude.
2. Go to external view.
3. Altitude bug indicates incorrect altitude.

### References (optional)

![Microsoft Flight Simulator 2021_10_29 19_34_39](https://user-images.githubusercontent.com/11900168/139422442-41a94cf5-abc9-483d-b35a-334a8af1e756.png
![Microsoft Flight Simulator 2021_10_29 19_36_03](https://user-images.githubusercontent.com/11900168/139422454-15b4fe1f-0da3-4080-8729-638b20159251.png)
)
Altitude bug indicates 5000 while selected altitude is FL260.

### Additional info (optional)

Heading bug and speed bug have no problem.
Vanilla A320neo doesn't have this problem.

**Comment by sidnov** [comment]
Issue fixed, checked on latest dev build (21/02/2022)
