### ISSUE TITLE
cabin pressure error

### ISSUE THREAD

**Issue by youngryan7** [flybywiresim/a32nx#6111]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2021-10-24T07:24:01+00:00",
  "ref": "experimental",
  "sha": "cac9488f3e619e565602ed4ccf7a0da5f248d4f1",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

cabin pressure exces res after landing and engine shutdown 
still no tcas update

### Expected behavior

not to error

### Steps to reproduce

load up and fly
land and engine shut down with apu

### References (optional)

![2021-10-30 (1)](https://user-images.githubusercontent.com/59422760/139533177-d01fda6f-9c1b-4b4f-aab6-43562d0d3e8c.png)

### Additional info (optional)

any timing on when tcas to be released as well

thanks

**Comment by Silvaronn** [comment]
It's been fixed in the development version, the experimental version doesn't, it needs more updates.

**Comment by BlueberryKing** [comment]
Closing this since it has been fixed in an updated version. Please let me know if you're still running into this and I can reopen the issue.
