### ISSUE TITLE
Some airports don't have weather information

### ISSUE THREAD

**Issue by Jannomag** [flybywiresim/a32nx#6112]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-10-28T18:01:48+00:00",
  "ref": "v0.7.1",
  "sha": "8d8fb7132f1be95a336f25a6e8441b1420d74989",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

Requesting a WX Report or using the EFB for weather information doesn't work for some airports. 
I noticed it on NZQN  (official addon) and EIKY (iniBuilds).

Using the MCDUs WX Request it gives just "Station not available", using the EFB the information stays empty / at 0.

Tried with live weather and static weather as well.

### Expected behavior

Weather information should be shown correctly

### Steps to reproduce

1. Request WX report on MCDU
2. Or use EFB

**Comment by tracernz** [comment]
The data is simply not available from your selected source (in the EFB settings), and there is no way to retrieve the sim weather.
