### ISSUE TITLE
Option to reset Throttle Calibration Values

### ISSUE THREAD

**Issue by frankkopp** [flybywiresim/a32nx#6113]
### Aircraft Version

Development

### Description

To make it easier to for users to start with a fresh set of default values and also to make it easier for #support we should have a button to reset the calibration values to the default values. 

This would spare the user and support to have to remove ThrottleCalibration.ini (and restart the sim) when the user managed to somehow mess up the calibration. 

DM me for questions. 

### References (optional)

n/a

### Additional info (optional)

n/a

### Discord Username (optional)

Cdr_Maverick#6475

**Comment by Saschl** [comment]
Good point. Although there’s no real way to mess up the calibration completely it will be a good assistance to have a clean state again👌I will try and have a look as the page itself needs a refresher

**Comment by frankkopp** [comment]
> Good point. Although there’s no real way to mess up the calibration completely it will be a good assistance to have a clean state again👌I will try and have a look as the page itself needs a refresher

That is actually the idea - clean slate so that the user and support(!) exactly know where they are. 
Easier to guide a user through.

Let me know if you change stuff - happy to test and also update any docs of course.

**Comment by Unsspeakable21** [comment]
Anyone having issues with the throttle? When my quadrant is at idle, the plane goes full reverse thrust.. Any way to fix this? Thanks!

**Comment by Benjozork** [comment]
You need to calibrate your throttles.

Please do not comment on unrelated issue tickets. Use our discord server for support.

**Comment by Unsspeakable21** [comment]
Sorry for commenting on here, parents won’t let me have discord… How do I recalibrate them?

**Comment by Unsspeakable21** [comment]
I thought this was a new issue ticket..

**Comment by Benjozork** [comment]
This guide can help.

https://docs.flybywiresim.com/fbw-a32nx/feature-guides/flyPad/throttle-calibration/

**Comment by Unsspeakable21** [comment]
Thanks so much man!!
