### ISSUE TITLE
I CAN'T STEER THE PLANE WHEN STARTING FROM GATE

### ISSUE THREAD

**Issue by DAMARCIO** [flybywiresim/a32nx#6116]
### Aircraft Version

Stable

### Build info

```json
{
      "name": "American Airlines",
      "package_version": "1.0"
    }
  ],
  "content_type": "AIRCRAFT",
  "title": "American Airlines",
  "manufacturer": "Airbus",
  "creator": "LAZ#3444",
  "package_version": "1.0",
  "minimum_game_version": "1.7.12",
  "release_notes": {
    "neutral": {
      "LastUpdate": "",
      "OlderHistory": ""
    }
  },
  "total_package_size": "00000000000000000000"
}
```

### Describe the bug

Hi I"m having issues with steering the airplane when starting flights from gate since version 7.0 was released.  Once the tug is disconnected the rudders while not function correctly.  If i turn right the plane wants to continue going right and wont go back left etc.  Interestingly enough if i start a flight from the runway I don't have this issue and the plane responds according to all of the joystick bindings.  The issue is only when starting from the gate.

### Expected behavior

to be able to steer the plane in order to taxi to the appropriate runway

### Steps to reproduce

started flight at various points
tried with different airplanes
the issue is with airbus flybywire a32nx version 7

### References (optional)

none

### Additional info (optional)

none

### Discord Username (optional)

damarcio

**Comment by Kimbyeoungjang** [comment]
Can you try again without any liveries in your community folder?

**Comment by DAMARCIO** [comment]
yes i have removed everything from the community folder.  I was able to get the airplane out the gate at times but I"m having problems steering it.  When i increase the throttle on the runway for takeoff there is a point where the plane is no longer able to be controlled and it veers off to the right.  Then it climbs but will not climb very much.  
    On Sunday, October 31, 2021, 10:54:41 PM MST, Kimbyeoungjang ***@***.***> wrote:  
 
 


Can you try again without any liveries in your community folder?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by DAMARCIO** [comment]
yes i have removed everything from the community folder.  I was able to get the airplane out the gate at times but I"m having problems steering it.  When i increase the throttle on the runway for takeoff there is a point where the plane is no longer able to be controlled and it veers off to the right.  Then it climbs but will not climb very much.

**Comment by Kimbyeoungjang** [comment]
Can you join discord? We can help you on discord

**Comment by chrisalexander0617** [comment]
What has worked for me is ensuring that the CALL TUG is disconnected after pushback. You can access this from the flypad

<img width="994" alt="Screen Shot 2021-11-19 at 3 32 35 PM" src="https://user-images.githubusercontent.com/44784345/142688117-e7ccb933-1c21-4f78-9e20-daa03882135b.png">
