### ISSUE TITLE
Take Off Speed Can't be Calculated

### ISSUE THREAD

**Issue by cqhhy2001** [flybywiresim/a32nx#6117]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-10-28T18:01:48+00:00",
  "ref": "v0.7.1",
  "sha": "8d8fb7132f1be95a336f25a6e8441b1420d74989",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

Tack off speed in PERF page can't be calculated.
however i can type the speed manually.
https://user-images.githubusercontent.com/21079967/139622864-30976f3e-ce39-4823-ad1c-ace6bd82bc1f.mp4

### Expected behavior

it should calculate the speed and fill the boxes automatically when i press the botton in the left 

### Steps to reproduce

Open External Power and Battery 
Navigate to PERF
Click Botton in the left to calculate the V1 VR V2 Speeds
It shows format error.
Tried to clear button, the issues remain 
however i can type the speed manually.

### Additional info (optional)

It shouldn't be the problem caused by other mod , I have only installed FWBA32NX

**Comment by sidnov** [comment]
Add Flaps setting and retry
