### ISSUE TITLE
Black displays, non-working traction levers and non-working flaps release lever

### ISSUE THREAD

**Issue by sergAy3500** [flybywiresim/a32nx#6125]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-10-28T18:01:48+00:00",
  "ref": "v0.7.1",
  "sha": "8d8fb7132f1be95a336f25a6e8441b1420d74989",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

when I launching the airplane version 0.7.1 I have black displays, non-working traction levers and non-working flaps release lever.

### Expected behavior

serviceable displays, working traction levers and working flaps release lever

### Steps to reproduce

1. I installed the stable version (0.7.1) using your installer
2. I have launched the MSFS 2020 game
3. I have been launched on this plane at different airports
4. I have encountered this error (I wrote it above)

### Additional info (optional)

my community folder has only flybywire-aircraft-a320-neo. I didn't install any add-ons in the Community folder.
![20211102140425_1](https://user-images.githubusercontent.com/93487958/139839217-bb78d70e-372b-4756-b2c8-c210112c3395.jpg)
![20211102140416_1](https://user-images.githubusercontent.com/93487958/139839218-0e3fbc64-df98-4d9a-ac88-18d4873a4a8d.jpg)

**Comment by frankkopp** [comment]
Please come to our Discord #support channel so we can help you. 
This requires some investigation as it is not a bug but something on your side. 
As there are several possible causes we need to go through some troubleshooting. 
https://docs.flybywiresim.com/fbw-a32nx/support/#4-report-issue-on-discord
