### ISSUE TITLE
Steady FPS drop over time with Developer Version

### ISSUE THREAD

**Issue by Richdem** [flybywiresim/a32nx#6129]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-11-02T16:49:58+00:00",
  "ref": "master",
  "sha": "8268d733d38d9dfb585dfb198fbe340f967023f9",
  "actor": "bouveng",
  "event_name": "manual"
}
```

### Describe the bug

I have noticed that while flying the Developer version the fps seem to drop over time. First I noticed this when doing multiple legs around 2 hours, once I arrive at the destination and perform a turn around I see a degradation in performance

### Expected behavior

Flight to be undertaken without this performance degredation

### Steps to reproduce

I started a flight at CYHM Ramp 10 with live weather & time (I don't believe this is a specific airport/gate issue) powered on the aircraft and connected to ground power, added stairs, catering & baggage. Set all display brightness to 50% (Using the Developer version)

I left the aircraft alone and did nothing, after 1 hour the fps dropped too around 50fps then after 2 hours I was seeing around 38 fps. I loaded the default A320 and performed the same test without issues. Then I loaded the stable version and again had no issues. I even flew 3 legs of around 2.5 hours each and did not have an issue. Next I loaded the Experimental version and let it sit for 2 hours after powering on and again did not see a problem. Finally I downloaded a fresh copy of the Developer version and ran the same test. After 2 hours I saw a drop to around 40fps

### Discord Username (optional)

RJC_68

**Comment by frankkopp** [comment]
I do think this is a known MSFS issue (https://forums.flightsimulator.com/search?expanded=true&q=FPS%20drop%20long%20flights) and not specific for the a32nx.

**Comment by Richdem** [comment]
> I do think this is a known MSFS issue (https://forums.flightsimulator.com/search?expanded=true&q=FPS%20drop%20long%20flights) and not specific for the a32nx.

The interesting thing here though is I did the same test with the default A320, I even left it for over 6 hours and didn’t see this issue. Yesterday I flew multiple legs over 8 hours with the stable version and again I didn’t see this. For whatever reason in my case the developer version seems to exhibit the problem much sooner.

**Comment by 2hwk** [comment]
There is a known memory leak with the EFB, for long haul flights please switch it off, this should help with the issue until this is fixed.

**Comment by 2hwk** [comment]
https://github.com/flybywiresim/a32nx/issues/4388

Closing as this is being tracked here
