### ISSUE TITLE
Auto Pilot Disarm

### ISSUE THREAD

**Issue by CptJohn34** [flybywiresim/a32nx#6133]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-10-28T18:01:48+00:00",
  "ref": "v0.7.1",
  "sha": "8d8fb7132f1be95a336f25a6e8441b1420d74989",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

when in flight with the autopilot engaged it disarms. Unable to rearm it.

### Expected behavior

expect the aircraft to continue to fly controlled by the autopilot

### Steps to reproduce

Bug occurred during flights in Europe.

### Additional info (optional)

I hadn't noticed this problem prior to the v0.7.1 update.

### Discord Username (optional)

CPTJOHN34

**Comment by Benjozork** [comment]
Please read [this](https://docs.flybywiresim.com/fbw-a32nx/feature-guides/afloor/) and make sure this is not your situation.

**Comment by aguther** [comment]
Did you use EFB to calculate descend and typed in numbers using the numpad?
