### ISSUE TITLE
The A32NX.FCU_ALT_INC event doesn't increment the FCUs selected altitude, while FCU_ALT_DEC decrements properly

### ISSUE THREAD

**Issue by joeherwig** [flybywiresim/a32nx#6137]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2021-10-24T07:24:01+00:00",
  "ref": "experimental",
  "sha": "cac9488f3e619e565602ed4ccf7a0da5f248d4f1",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

Using the "A32NX.FCU_ALT_INC" event via FSUIPC doesn't increment the FCUs selected altitude at all.

https://github.com/flybywiresim/a32nx/blob/9375c98cecd79a9f90f0b8f4266a485f5a1fa081/src/fbw/src/interface/SimConnectInterface.cpp#L1237

### Expected behavior

the Event **A32NX.FCU_ALT_INC** triggered via Simconnect / FSUIPC should increment the FCU alt, in the same way the **A32NX.FCU_ALT_DEC** decrements the selected altitude.

### Steps to reproduce

1. load a flight with the before mentioned A32nx
2. (try to) increment the selected altitude via the event (i'm using FSUIPC, but i'm quite sure, it applies to all simconnect based approaches)
3. Increment it now within the VCs FCU
4. decrement the selected altitude via the event (it will work and sync the value displayed in the VCs FCU. Now it decrements, but only increments via VC not via events.

### References (optional)

I'm using the events as mentioned within https://github.com/flybywiresim/a32nx/blob/master/docs/a320-events.md#non-internal-events / https://docs.flybywiresim.com/fbw-a32nx/feature-guides/autopilot-fbw/
together with the event file like https://github.com/flybywiresim/a32nx/blob/master/docs/FSUIPC/flybywire-aircraft-a320-neo.evt for FSUIPC and FSUIPC 7.2.10.

### Additional info (optional)

I noticed that within [src/fbw/src/interface/SimConnectInterface.cpp](https://github.com/flybywiresim/a32nx/blob/9375c98cecd79a9f90f0b8f4266a485f5a1fa081/src/fbw/src/interface/SimConnectInterface.cpp) the case for faulty [A32NX_FCU_ALT_INC](https://github.com/flybywiresim/a32nx/blob/9375c98cecd79a9f90f0b8f4266a485f5a1fa081/src/fbw/src/interface/SimConnectInterface.cpp#L1237) looks completely different than to the one from the working [A32NX_FCU_ALT_DEC](https://github.com/flybywiresim/a32nx/blob/9375c98cecd79a9f90f0b8f4266a485f5a1fa081/src/fbw/src/interface/SimConnectInterface.cpp#L1262)

Futhermore - even though probably not relevant for this: Could it be that [#L1283](https://github.com/flybywiresim/a32nx/blob/9375c98cecd79a9f90f0b8f4266a485f5a1fa081/src/fbw/src/interface/SimConnectInterface.cpp#L1283) is an copy-paste error of [#L1258](https://github.com/flybywiresim/a32nx/blob/9375c98cecd79a9f90f0b8f4266a485f5a1fa081/src/fbw/src/interface/SimConnectInterface.cpp#L1258)?

### Discord Username (optional)

joeherwig#0456

**Comment by tracernz** [comment]
Should be more like this?
```
            "3 (A:AUTOPILOT ALTITUDE LOCK VAR:3, feet) 1000 % 1000 + 49000 min (>K:2:AP_ALT_VAR_SET_ENGLISH)"
            " (>H:AP_KNOB_Up)"
            " (>H:A320_Neo_CDU_AP_INC_ALT)"
```

**Comment by aguther** [comment]
* I cannot reproduce the issue. I just tried it using FSUIPC and for me it works.
* I can confirm the copy-paste-error.

**Comment by aguther** [comment]
https://user-images.githubusercontent.com/6629914/140465912-42ce94ae-9958-4fa5-92af-0b712a53a39e.mp4
