### ISSUE TITLE
FIX INFO option is displayed only if the selected waypoint is the next waypoint

### ISSUE THREAD

**Issue by Tprocheira** [flybywiresim/a32nx#6142]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2021-11-05T07:50:54+00:00",
  "ref": "experimental",
  "sha": "7cf33556da868f83124ea179f3f27774eecde325",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

MSFS Version: 1.20.6
FBW Version: 7cf3355 (experimental)

FIX INFO page is not shown in the LAT REV page if the waypoint selected is not the next waypoint (RDE in this case) in the Flight Plan, even if the page is scrolled down.

Cockpit
![fix info](https://user-images.githubusercontent.com/88292967/140569901-089080a0-01a2-4cb0-8313-ae6101320b13.png)

Next waypoint
![next wpt](https://user-images.githubusercontent.com/88292967/140569925-5140c487-eae9-4c4a-b3f2-16a95f497b0b.png)

Any other waypoint
![other wpt](https://user-images.githubusercontent.com/88292967/140569979-119274fb-4926-4169-926c-8ce48b22a749.png)

### Expected behavior

FIX INFO should be shown in the LAT REV page of the Flight Plan waypoints for any waypoint along the route, not just the first waypoint available to be selected.

### Steps to reproduce

1. Plan a SimBrief flight plan (not tested with MSFS built-in flight plans)
2. Sync the plan with A32NX link
3. Try to open any waypoint LAT REV page

### Discord Username (optional)

Tprocheira#0278

**Comment by Benjozork** [comment]
Please provide real world references to support that this is not accurate.

**Comment by tracernz** [comment]
That is correct behaviour.
