### ISSUE TITLE
lower ECAM size problem

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#6143]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2021-11-05T07:50:54+00:00",
  "ref": "experimental",
  "sha": "7cf33556da868f83124ea179f3f27774eecde325",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

as you can see on the screenshot, the lower ECAM cuts parts of the pages. 

### Expected behavior

whole display area should fit into the display frame

### Steps to reproduce

1. start at any gate/position
2. look at lower ECAM
3. switch ECAM pages
![Lower ECAM bug](https://user-images.githubusercontent.com/72918017/140572570-2a9dcb7a-40c8-43bd-bd61-fc22d9a58882.jpg)

**Comment by tracernz** [comment]
Almost certainly #6110.

**Comment by bouveng** [comment]
> Almost certainly #6110.

Why you think that? :eyes:

**Comment by tracernz** [comment]
> 
> 
> > Almost certainly #6110.
> 
> Why you think that? 👀 It is fine in dev.

I thought that one changed the display resolution... looks like it doesn't... was it removed? The commit that changed the resolutions is only in experimental, and different to the one in master 😨  https://github.com/flybywiresim/a32nx/commit/be683c1ad6c2d8a1e78a5547a9e1d0d75b97c830

**Comment by Aarondodd88** [comment]
On the mcdu (experimental version) i can middle click mouse button and move the page around the mcdu, where it ends up looking like this in all four directions.

**Comment by sidnov** [comment]
I've been unable to reproduce this issue with the latest dev, feel free to re-open if that's not the case 😄
