### ISSUE TITLE
Install problem: 0x80010135: Path Too Long

### ISSUE THREAD

**Issue by OgreTransporter** [flybywiresim/a32nx#6151]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-10-28T18:01:48+00:00",
  "ref": "v0.7.1",
  "sha": "8d8fb7132f1be95a336f25a6e8441b1420d74989",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

I have tried to install the current aircraft according to the instructions

> Microsoft Store and/or Game Pass Edition
> - Copy the flybywire-aircraft-a320-neo folder into your community package folder.
>
> It is located in:
> - C:\Users\[YOURUSERNAME]\AppData\Local\Packages\Microsoft.FlightSimulator_<RANDOMLETTERS>\LocalCache\Packages\Community.

When unpacking the file into the directory, I get the Windows error message `0x80010135: Path Too Long` for the file `A320_Neo_CDU_CFDS_Test_Inst_ECAM_Menu.js`.

### Expected behavior

Just unzip

### Steps to reproduce

1. Download A32NX-stable.zip
2. Open file with the Explorer
3. Drag & Drop the flybywire-aircraft-a320-neo folder into community package folder

### Additional info (optional)

You must not use Windows to unzip the files but use a program like 7zip, then it works. The internally used Windows API does not support more than 260 characters. Alternatively you can unpack the directory somewhere else, rename it (e.g. A320NX), move it to the community directory and finally rename it back. It would be better if the filenames were not longer than 260 characters. Alternatively, perhaps a note in the installation instructions would be useful.

### Discord Username (optional)

Transporter#0581

**Comment by Benjozork** [comment]
This is a limitation of Microsoft Windows.

**Comment by OgreTransporter** [comment]
Yes, and MSFS is made for Windows. So the Addons should take care about the limitation of Windows.

**Comment by Benjozork** [comment]
And you do not seem to be using the installer. Which means you are using a third-party zip tool, which we cannot support.

Can you reproduce this using the installer?
