### ISSUE TITLE
[EFB Request] Add a way for users to manually add a certain value for EFB Audio Settings

### ISSUE THREAD

**Issue by GhostEagle68** [flybywiresim/a32nx#6160]
### Aircraft Version

Experimental

### Description

![image](https://user-images.githubusercontent.com/62395728/140824350-35798b33-c829-48fa-acd8-d0aacc766df5.png)

On the EFB Audio settings, I found that it could be quite annoying trying to get a certain value by using the slider. I think it would be more user-friendly to add a way that users can input a value from -100 to +100.  Maybe if the numbers on the left of the sliders are clicked, then you can input a certain value. 

### Discord Username (optional)

GhostEagle68#0030

**Comment by ErickSharp** [comment]
Going to put this in with the other stuff coming in FlyPadOS 3.
