### ISSUE TITLE
Waypoint dis on MCDU

### ISSUE THREAD

**Issue by Bentebert** [flybywiresim/a32nx#6164]
### Aircraft Version

Development

### Description

Hi thanks for info.  
I have a questions regards waypoint distance.
There are a fault in waypoint distance in the MCDU flightplan.
Distance from waypoint to waypoint include aircraft altitude. Ex if you fly FL 350 and the flight plan show you are ex 25 miles to next waypoint, then on the MCDU it´s shows 27 miles.
That are wrong because the altitude are >NOT include in the distance (GPS), only in VOR distance (line of sight).

Regards Bent Ebert

**Comment by tracernz** [comment]
The built-in MS flight planner is entirely replaced with a custom implementation in experimental. Once that merges this will also be fixed in master.
