### ISSUE TITLE
Support events INCREASE / DECREASE AUTOPILOT REFERENCE ALTITUDE

### ISSUE THREAD

**Issue by INTJMastermind** [flybywiresim/a32nx#6166]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2021-11-10T16:35:00+00:00",
  "ref": "experimental",
  "sha": "75b93d18005213b98823137a80966fff131fe62c",
  "actor": "Saschl",
  "event_name": "manual"
}
```

### Describe the bug

Currently there is a problem when setting the altitude on the FCU. The scrolling mouse wheel on the altitude knob and using the button binds for INCREASE / DECREASE AUTOPILOT REFERENCE ALTITUDE do not do the same thing.

When you use the inc/dec autopilot altitude button binds, it first starts from 5000 ft (instead of 0100 ft), so if you press INC in a fresh jet, the first altitude you see is 5100 ft (instead of 200 ft). Also, when you use the mouse wheel after setting the altitude using the button binds, no matter what altitude you set it to, the next time you use the button binds, it will change the altitude based on the last altitude set using buttons, not scroll wheel.

### Expected behavior

The mouse wheel and button binds both change the altitude on the FCU consistently.

### Steps to reproduce

1. Start hot on runway for simplicity. Note altitude field in the FCU starts at 0100.
2. Press the joystick button bound to INC AUTOPILOT REFERENCE ALTITUDE. **BUG 1:** The altitude jumps to 5100 instead of 0200.
3. Use the mouse scroll wheel on the altitude knob to set 10000 ft (doesn't matter if the knob is set to 100 or 1000 ft per click).
4. Press the joystick button bound to DEC AUTOPILOT REFERENCE ALTITUDE. **BUG 2:** The altitude jumps to 5000 ft (down from 5100 ft) instead of 9900 ft as expected)

### Discord Username (optional)

Bear.is.flying#5605

**Comment by INTJMastermind** [comment]
**BUG3:** You can also set the altitude to negative values using the DEC AUTOPILOT REFERENCE ALTITUDE. The negative values display on the PFD, but the FCU still shows 0100. The FCU value is unresponsive until raising the altitude back to positive values, at which point it works normally.

**Comment by aguther** [comment]
I don’t know when these key binds have been added tbh. MS/Asobo often adds new keys in updates and I do not check them everytime.

Here you find a list of **supported** events and variables:
https://docs.flybywiresim.com/fbw-a32nx/feature-guides/autopilot-fbw/

There is no guarantee that all events in the sim can be catchend, but next time I do changes on the AP I can check if the above events can be supported. In the meantime please use a supported event. Those events work very well.

**Comment by aguther** [comment]
FYI on experimental the events are now supported.
