### ISSUE TITLE
DOME Light operating when BAT and Ext.PWR is off

### ISSUE THREAD

**Issue by DomWin02** [flybywiresim/a32nx#6170]
### Aircraft Version

Development

### Description

In real life,(I have saw it on an Insta story of an A320 pilot of DLH) the DOME Light is Operating when BAT and Ext. PWR is off.

### Discord Username (optional)

DomenicHAJ#0457

**Comment by tracernz** [comment]
Which dome light, and was the service bus energised?

**Comment by DomWin02** [comment]
> Which dome light, and was the service bus energised?

The normal Cokcpit Dome light. No It was normaly shutdown.

**Comment by davidwalschots** [comment]
There are two dome lights. The captain dome light is powered by DC 2. DC 2 is never powered when there is no TR energising it. The F/O dome light is powered by DC ESS. DC ESS is powered when velocity < 50 knots and both batteries are connected to the DC BAT BUS, or when velocity >= 50 knots.

**Comment by komp1821** [comment]
> The captain dome light is powered by DC 2. DC 2 is never powered when there is no TR energising it. The F/O dome light is powered by DC ESS.

This sounds like we have a mistake in our implementation. Could be a relict from the time we decided not to implement Ground Service Busses and assign their consumers to the next higher 'parent' bus. 
One of the Dome Lights, I believe it is the Captain's, is definitely supplied by DC ground service bus. I'll have a look tomorrow.

**Comment by tracernz** [comment]
> One of the Dome Lights, I believe it is the Captain's, is definitely supplied by DC ground service bus. I'll have a look tomorrow.

Yes, that's what I was thinking of above. If the ground service bus is energised the captain's side dome light is powered.

**Comment by davidwalschots** [comment]
> Could be a relict from the time we decided not to implement Ground Service Busses and assign their consumers to the next higher 'parent' bus.

This is probably the culprit then, yeah. I always refer back to the tables in #3980 for this information.

**Comment by komp1821** [comment]
Can confirm now that the Captain's Dome light is on 601PP DC Ground Service Bus.
As far as I remember, our Service Busses are always energized when External Power is connected. Should be an easy fix then. 

> I always refer back to the tables in #3980 for this information.

Took a look at the table. The good news is that the rest of the lights has no connection to any Service Bus. There is one exception though: Nav Lights. But that doesn't belong here. I'll open a separate issue.

**Comment by davidwalschots** [comment]
I've updated the table based on this feedback.
