### ISSUE TITLE
Unable to Move Windshield Wiper Speed Dial

### ISSUE THREAD

**Issue by maxhades** [flybywiresim/a32nx#6173]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-11-10T22:52:08+00:00",
  "ref": "master",
  "sha": "d3b39374d923c4c2d3a45680b765096788b37613",
  "actor": "bouveng",
  "event_name": "manual"
}
```

### Describe the bug

Non funtion wipers

### Expected behavior

Not able to move the wiper switches to low/fast/off position

### Steps to reproduce

Always in off position. Not possible to move the switch as before latest dev. update.

### Discord Username (optional)

maxhades

**Comment by BlueberryKing** [comment]
Make sure you don't have any keybindings set to it. If possible, please send a video of the bug occurring.

**Comment by maxhades** [comment]
Hi
I have no keybindings for that. I can not switch the wiper via mouse as before.

https://www.youtube.com/watch?v=vB0ACoz-rMc

**Comment by 2hwk** [comment]
Can't reproduce and stale, so closing. Reopen if this is still an issue.
