### ISSUE TITLE
Nav Lights: Incorrect assigment of power source

### ISSUE THREAD

**Issue by komp1821** [flybywiresim/a32nx#6174]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-11-10T22:52:08+00:00",
  "ref": "master",
  "sha": "d3b39374d923c4c2d3a45680b765096788b37613",
  "actor": "bouveng",
  "event_name": "manual"
}
```

### Describe the bug

At the time we introduced our custom electrical system implementation ([#3980](https://github.com/flybywiresim/a32nx/pull/3980)) the decision was made that Ground Service Busses won't be simulated due to lack of control options and a low benefit from the extra work. Therefore, all consumers connected to any Ground Service Bus were assigned to the next higher 'parent' bus.

#4544 added the Ground Service Bus functionality later, making it available when External Power is connected (but not turned on) or AC BUS 2 is powered.

Nav Lights are currently assigned to AC Bus 1 and 2.

### Expected behavior

Nav Lights should be assigned to AC Ground Service.

_Note: Nav lights share a switch with Logo lights. The Logo lights remain as they are on AC BUS 1 and 2._

### Steps to reproduce

1. Connect External Power - **do not** turn it on.
2. Set Nav&Logo Light switch to position 1 and 2. Nav lights are not working.

### Additional info (optional)

Same applies to the Captain's Dome light (#6170).
As far as I can tell other consumers are not affected by this.
Relevant Ground Service Bus consumers are cargo door (i. e. Y Elec Pump during cargo door operation + door control circuits), cabin lights, cargo compartment lights, vacuum generator.

### Discord Username (optional)

komp#1821

**Comment by davidwalschots** [comment]
@komp1821 Currently these two lights are also classified as NAV lights, but that might not be correct. Should these lights also be assigned to the AC GND SVC BUS? If not, should they keep their assignment to AC 1 and AC 2?

![image](https://user-images.githubusercontent.com/1074786/141678108-c7edb42d-66c7-42a1-9d2c-cfcd53f56fe5.png)

**Comment by komp1821** [comment]
Yes, they are also on AC gcalledround Service and called Nav lights. Tail Nav lights or White Nav lights, whichever you prefer.
