### ISSUE TITLE
failure in thrustmaster tca quadrant add-on airbus

### ISSUE THREAD

**Issue by Emenuez** [flybywiresim/a32nx#6177]
### Aircraft Version

Development

### Build info

```json
"built": "2021-11-06T18:00:29+00:00",
  "ref": "master",
  "sha": "3fbce50cbd1d71f841aadbf19585f04628f97703",
  "actor": "aguther",
  "event_name": "manual"
```

### Describe the bug

on the thrustmaster tca quadrant add-on airbus the flaps and air brakes cannot be activated. Occurs since the Sim VI update

### Expected behavior

both the air brakes and the flaps should activate as I lower the corresponding levers. Currently they go from 0 to 100 without intermediate positions

### Steps to reproduce

the error occurred after installing the Sim update VI

### Discord Username (optional)

Emenuez

**Comment by aguther** [comment]
What binding do you use?

**Comment by Emenuez** [comment]
Hello:
These are the configurations that I have made.
Thank you very much for your help
![2021-11-15](https://user-images.githubusercontent.com/91392418/141755509-23ada999-7e66-41a2-80ed-a5368637ef1c.png)
![2021-11-15 (2)](https://user-images.githubusercontent.com/91392418/141755574-2ffee387-c1a3-4ca2-aaf1-1bfffa1e125a.png)
![2021-11-15 (1)](https://user-images.githubusercontent.com/91392418/141755605-09cf53a9-91ac-4608-9396-8ed53921215b.png)

**Comment by aguther** [comment]
A bit hard with the language, but I think you have double binding. I would try to just bind the spoiler to the axis and nothing else.

**Comment by aguther** [comment]
Please approach support channel in Discord in in case you need additional help.

**Comment by Emenuez** [comment]
Couldn't you pass me the configuration of your quadrant?
