### ISSUE TITLE
hPa and inHg issue with aircraft

### ISSUE THREAD

**Issue by marinofranz** [flybywiresim/a32nx#6181]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-11-14T01:51:53+00:00",
  "ref": "master",
  "sha": "e59f501867235bbe321b60ebfb67743985bca5b5",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

Basically, you know how you can change the altimeter setting for the ISIS in the EFB, but I noticed you can't change the altimeter setting on the home page of the EFB, where the METAR loads in after you import a flight plan from SimBrief.

### Expected behavior

What is supposed to happen is that you should be able to change the METAR altimeter setting through the EFB.

### Steps to reproduce

1. Import a flight plan in the EFB from SimBrief in the EFB home page.

### References (optional)

![image](https://user-images.githubusercontent.com/48334228/141692469-68c1d79b-3406-46f4-9df6-9836e9a7b279.png)

### Discord Username (optional)

`marino!#0001`

**Comment by tracernz** [comment]
Duplicate https://github.com/flybywiresim/a32nx/issues/5634
