### ISSUE TITLE
CTD when approach phase starts

### ISSUE THREAD

**Issue by Vitorcm86** [flybywiresim/a32nx#6182]
### Aircraft Version

Stable

### Build info

```json
V.0.7.2
```

### Describe the bug

Approach phase drives CTD every single time whatever the scenarios is. It happens only on stable version but not on experimental.

### Expected behavior

Don't CTD

### Steps to reproduce

Start approach phase

**Comment by aguther** [comment]
Can you please make a video of the situation?

**Comment by derl30n** [comment]
> I am facing the same problem. Especially when I try to capture the ILS and make an automatic landing, it feels like it's happening.

can you please try and explain what you meant with your comment?

**Comment by Benjozork** [comment]
No response
