### ISSUE TITLE
No Simbrief user?

### ISSUE THREAD

**Issue by ErikNL80** [flybywiresim/a32nx#6183]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-11-15T12:40:44+00:00",
  "ref": "master",
  "sha": "81ab288c0d3c33c6fe340c4d249a630aa59fc834",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

Today I started a flight from EGCC to LEMD via the MSFS flight planner. I am not using Simbrief. When aligning the ADIRS I get an error 'No Simbrief user'. That is correct since I do not use that.

As a result the flightplan is still visible in the PFD, but not in the MCDU?

Any clues?

### Expected behavior

I would expect the MCDU to show the data from the MSFS flight planner into the MCDU...

### Steps to reproduce

1. Set-up a C&D flight
2. Align the ADIRS
3. Check the MCDU for this message

### References (optional)

![MCDU](https://user-images.githubusercontent.com/71258178/141789283-5fc5949e-6c0f-4a94-ad53-6c418aa62ca6.png)

![2](https://user-images.githubusercontent.com/71258178/141789340-305e767b-c6b2-4f73-b1fd-2b82b2b66e80.png)

![3](https://user-images.githubusercontent.com/71258178/141789347-fdfd77bc-588f-4f6d-a7b2-48a9a5f57bdc.png)

**Comment by ErikNL80** [comment]
After a few succesful flights I am having the same issue when doing a flight from EHEH to LEAL...

**Comment by ErikNL80** [comment]
I also tested by adding and removing a value in the EFB for SimBrief user, but somehow I cannot clear the field. In my case a 9 cannot be deleted. Where is this setting stored?

![SimBrief](https://user-images.githubusercontent.com/71258178/141989243-dc4f80ab-99c2-48c5-998f-16db1e18ae16.png)

**Comment by ErikNL80** [comment]
Today same issue when doing a flight from UUEE (Drzewiecki Design) to EDDK (Aerosoft)... PFD flightplan OK, MCDU is empty. Please guys, what is going on here?

![UUEE](https://user-images.githubusercontent.com/71258178/142195276-f646e7a1-d485-4a0a-b7e5-c8154b91138c.png)

**Comment by ErikNL80** [comment]
I found a workaround, and that is when the issue occur to restart the flight. Next time INIT was OK and the flightplan was recognized in the MCDU. Hope it helps you guys in troubleshooting...

**Comment by knokbak** [comment]
I am having the same issue, but on stable v0.7.4. EGCC -> EGPH via POL1Y POL N601 INPIP INPI1E. The Simbrief API returns the correct data (https://www.simbrief.com/api/xml.fetcher.php?username=knokbak) and the ATSU loads the flight plan as expected.

![Microsoft Flight Simulator 2_6_2022 10_59_18 AM](https://user-images.githubusercontent.com/65198941/152678088-9f4de910-b0bf-46b9-8c31-c48dfeaa544e.png)
![Microsoft Flight Simulator 2_6_2022 10_59_02 AM](https://user-images.githubusercontent.com/65198941/152678095-8877a1eb-35d7-4e86-847a-f80083ba2795.png)
![Microsoft Flight Simulator 2_6_2022 11_13_54 AM](https://user-images.githubusercontent.com/65198941/152678133-ac651f5d-317f-4404-b99b-f28cc7992558.png)

**Comment by sidnov** [comment]
Issue fixed for user with restart (not reproducible)
