### ISSUE TITLE
AP NAV Drifting off course when flying in crosswind

### ISSUE THREAD

**Issue by RSpeekenbrink** [flybywiresim/a32nx#6190]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-11-08T18:43:55+00:00",
  "ref": "v0.7.2",
  "sha": "db3e3d606b3f003adbf16f38ed031fd4a6d85642",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

When flying on AP NAV with slight crosswind the aircraft drifts off course.

### Expected behavior

Aircraft corrects itself on course

### Steps to reproduce

1. Fly with slight crosswind.
2. Have a long leg
3. Engage AP and NAV
4. Wait and see the aircraft drift off course

### References (optional)

![FlightSimulator_eArEJ5Blx4](https://user-images.githubusercontent.com/7093216/142398757-3b4938e2-6dd0-4255-a695-28dc3952d4ed.jpg)

### Additional info (optional)

My route when this occured:

LPMA/05 F360 DEGUN DCT LAMDI DCT AGADO DCT KORUL UN866 BERAD UM30 SALCO UN864 DAWLY DCT EGGD/27

Wind conditions: 072/20 (Happened between DEGUN and LAMDI)

### Discord Username (optional)

Fisher#8536

**Comment by aguther** [comment]
This not not due to crosswind. This is due to earth being round. It seems the default FPM guidance has an issue here.

This will be fixed with custom flight plan manager and it’s own guidance. Feel free to try out in the experimental version.
