### ISSUE TITLE
Engine Oil pressure constantly too high

### ISSUE THREAD

**Issue by BAW277** [flybywiresim/a32nx#6193]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-11-17T00:50:00+00:00",
  "ref": "master",
  "sha": "ed67c6025ae4e23bef574acdd89c0f6412fde99e",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

After engine start the engine oil pressure is linking on the ENG EICAS page. Does never stop doing that and the value seems to be unrealistically high.

### Expected behavior

Cold engine should have a higher ENG OIL PRES than a hot engine, not sure about the exact values.

### Steps to reproduce

1. Set at a gate cold and dark
2. Start the engines
3. Watch ENG OIL PRES

**Comment by frankkopp** [comment]
This is know and not yet implemented:
See #3117

You can close this.

**Comment by BAW277** [comment]
already known.
