### ISSUE TITLE
MCDU FROM/TO Flight plan does not work on GOTY (update 7)

### ISSUE THREAD

**Issue by G3NSVRV** [flybywiresim/a32nx#6196]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-11-08T18:43:55+00:00",
  "ref": "v0.7.2",
  "sha": "db3e3d606b3f003adbf16f38ed031fd4a6d85642",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

MCDU FROM/TO Flight plan does not work on GOTY (update 7)

### Expected behavior

Configure Flight Plan

### Steps to reproduce

1. MCDU
2. INIT
3. SCSE/SCEL
4. FROM/TO
5. ????

### References (optional)

![image](https://user-images.githubusercontent.com/11720535/142470514-84327002-68b5-4cb4-b637-4c8567bdc347.png)

### Discord Username (optional)

G3NSVRV#7693

**Comment by ErikNL80** [comment]
Same issue as I reported here: https://github.com/flybywiresim/a32nx/issues/6183 already occured in SU6... For now I found the only way to resolve is to restart the flight...

**Comment by Benjozork** [comment]
do you use navigraph navdat?

**Comment by Benjozork** [comment]
@ErikNL80 Not sure this is the same issue as yours?

**Comment by ErikNL80** [comment]
> @ErikNL80 Not sure this is the same issue as yours?

I am using stock data and the default MSFS flight planner. I also get this MCDU screen which should only be visible when using SimBrief?

**Comment by Benjozork** [comment]
No, this is INIT A, which is visible also when not using simbrief. Also the description seems unrelated to me.

**Comment by G3NSVRV** [comment]
> do you use navigraph navdata?

I'm using everything by default, before the update worked just fine.

I gonna give it another try. I found it really weird because this is the first time that I get this issue, I never got it on the update 6.

**Comment by Benjozork** [comment]
We have a lead as to what is causing the issue.

**Comment by G3NSVRV** [comment]
same issue after closing and opening the game again.

https://user-images.githubusercontent.com/11720535/142477956-8b68c402-f699-46b2-ba22-092c65176eb3.mp4

**Comment by Benjozork** [comment]
We believe only experimental works for now.

**Comment by G3NSVRV** [comment]
> We believe only experimental works for now.

yup, it worked:

![image](https://user-images.githubusercontent.com/11720535/142480172-350184bc-94e2-49ba-b35b-c2fff8087f01.png)

```json
{
  "built": "2021-11-17T23:44:30+00:00",
  "ref": "experimental",
  "sha": "baa8e695f75e6c4aaa9925e8e9b3f3457235053b",
  "actor": "aguther",
  "event_name": "manual"
}
```

BTW, what happened to the screens??? looks very bleached, I like it more on the 0.72

**Comment by Benjozork** [comment]
We removed the glass due to brightness issues.

**Comment by G3NSVRV** [comment]
idk if it is here or not, but something weird I noticed with the flightplan, the ATC does not give me the IFR clearance by MCDU:

![image](https://user-images.githubusercontent.com/11720535/142483689-2098c63c-8ba2-419a-b090-a0c79102241e.png)

**Comment by tracernz** [comment]
> 
> 
> idk if it is here or not, but something weird I noticed with the flightplan, the ATC does not give me the IFR clearance by MCDU:
> 
> ![image](https://user-images.githubusercontent.com/11720535/142483689-2098c63c-8ba2-419a-b090-a0c79102241e.png)

There is an option in the EFB to sync the flightplan with the MSFS flight planner... but be warned that it is known to causes CTDs, particularly when you do things that were disabled in previous versions of the A32NX like deleting legs in SID/STAR/approaches. There are reasons we are building our own flight planning and guidance system. ;)
