### ISSUE TITLE
[BUG] Both PFDs and both NDs self test when one of each is restarted

### ISSUE THREAD

**Issue by dark-swordsman** [flybywiresim/a32nx#620]
**Mod Version**

Master - Commit [cd0769d](https://github.com/flybywiresim/a32nx/commit/cd0769d7e9fcd5d5cea80085675d7c795f711f54)

**Describe the bug**

Both PFDs and both NDs are tied together when doing Self Tests.

**To Reproduce**

1. From cold and dark, turn on the batteries and external power
2. Turn on both NDs and PFDs using the brightness knobs
3. Left and Right PFDs and the Left and Right NDs finish at the same time (which shouldn't happen)
4. Turn one PFD off then back on
5. Both PFDs will Self Test
6. Turn one ND off then back on
7. Both NDs will Self Test

**Expected behavior**

Each PFD and ND should self test individually. They should not be tied to the other PFD and ND. 

**Actual behavior**

Both PFDs and both NDs finish their self tests together, and the opposite PFD or ND will re-self test when the other is turned off then back on.

**References**

Problem video: https://streamable.com/1kncnu

Real life reference: From the linked timestamp in [this video](https://youtu.be/Mo7A3CuVb8g?t=94), you can see the right PFD finish first, second ND right after, then the left ND and PFD finishing later.

**Other Notes**
I am not sure if this is possible to fix since I know many things like the wipers are tied together (which they also shouldn't be).

**Comment by UncleClapton** [comment]
This is a limitation of the display logic Asobo created. The screens are mirrored so if one self tests, the other must as well. We can't do much about it, either, as there would be a significant performance impact in separating the panels.

**Comment by dark-swordsman** [comment]
Yeah, I had a feeling that was the case.

Should I just close this as won't-fix then?

**Comment by UncleClapton** [comment]
please do. This is something we will want to fix eventually, but I think a ticket has already been made for it.
