### ISSUE TITLE
Proposal to make the simbrief-import more straight forward

### ISSUE THREAD

**Issue by oMrSmith** [flybywiresim/a32nx#6202]
### Aircraft Version

Development

### Description

Would it be thinkable
to merge the simbrief-import function
into one MCDU command
and move this to the INIT A page
so that it will load the flight-plan,
_preselect_ the fuel
and _preselect_ the pax?

### Additional info (optional)

PS: Currently if I import a flight from simbrief
it will preselect the fuel but not the pax.
So there is a slight inconsistency.

(I loaded the flightplan in the world map before
in order to file the flight plan for default ATC...)

**Comment by tracernz** [comment]
It is intended to simulate the ATSU/AOC functionality of the real A320. The payload loading parts will soon be moved to the EFB instead.

**Comment by oMrSmith** [comment]
Ah, I see. That sounds awesome! Thanks for all your effort on this project.
