### ISSUE TITLE
F CTL + WHEEL pages show amber

### ISSUE THREAD

**Issue by bouveng** [flybywiresim/a32nx#6203]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-11-19T15:09:52+00:00",
  "ref": "HEAD",
  "sha": "860e15695db836a7840d9390a613de3426b1b0fc",
  "actor": "Johan Bouveng <jb@oddlogic.se>",
  "event_name": "manual"
}
```

### Describe the bug

`F CTL` and `WHEEL` pages show amber statues in ECAM.
![f-ctl](https://user-images.githubusercontent.com/433429/142700811-d6c668ec-f858-40f3-b300-d8453e71207d.png)
![wheel](https://user-images.githubusercontent.com/433429/142700821-6d2dd6d3-695a-438e-8092-82aff0a6f73d.png)

### Expected behavior

No amber indications on `F CTL` and `WHEEL` pages.

### Steps to reproduce

1. Spawn
2. Startup aircraft
3. Observe ecam pages.

### References (optional)

N/A

### Additional info (optional)

Worked prior to https://github.com/flybywiresim/a32nx/pull/4799

### Discord Username (optional)

bouveng

**Comment by crocket63** [comment]
Local build issue only apparently. 

Run setup script. 
Then build again. 

Problem solved.

**Comment by bouveng** [comment]
Cant replicate anymore. Closing.
