### ISSUE TITLE
FMS flight plan broken

### ISSUE THREAD

**Issue by Lolloilpazzo** [flybywiresim/a32nx#6204]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-11-08T18:43:55+00:00",
  "ref": "v0.7.2",
  "sha": "db3e3d606b3f003adbf16f38ed031fd4a6d85642",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

After the lastest sim update (game of the year edition) I noticed impossible to add/clear or modify waypoints on the F-plan page of the FMS. You would click on the key and the computer simply does nothing.
I found the same issue with inserting departures and arrivals, after getting the runway page you can't click on a runway to see the available departures/arrivals

### Expected behavior

The behavior should be as previously. You should be able to edit / add or clear waypoints, same thing you should be able to add departures and approaches.

### Steps to reproduce

Log in to a flight with a flight plan generated from the game (i usually do High altitude airways), do not have a departure or approach selected.

Start the aircraft

Go on the FMS and try to enter a departure for the airport you're in, after getting on the available runways page you will not be able to continue as the computer simply will not do anything.

### Discord Username (optional)

Lolloilpazzo

**Comment by Benjozork** [comment]
As we have announced only development and experimental are currently compatible.

I suggest keeping up with either our Discord server announcements or our social media for up to date info on updates.
