### ISSUE TITLE
Issue with init request on INIT page

### ISSUE THREAD

**Issue by Antoniucc** [flybywiresim/a32nx#6205]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-11-08T18:43:55+00:00",
  "ref": "v0.7.2",
  "sha": "db3e3d606b3f003adbf16f38ed031fd4a6d85642",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

INIT page doesn't load flight plan from simbrief. All the data are correctly downoaded from the aoc pages (w/b; init/pres) but as soon as I enter the INIT page and request, the flight plan doesn't load. UPLINK INSERT IN PROG stays on the mfdcu and nothing happens. 

### Expected behavior

As soon as I press INIT request the flight plan is loaded 

### Steps to reproduce

1. After all the AOC data are correctly loaded go to INIT page and press INIT REQUEST

**Comment by Benjozork** [comment]
As we have announced only development and experimental are currently compatible.

I suggest keeping up with either our Discord server announcements or our social media for up to date info on updates.
