### ISSUE TITLE
Cockpit controls interaction is difficult

### ISSUE THREAD

**Issue by elcosomalo1** [flybywiresim/a32nx#6210]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-11-21T03:03:13+00:00",
  "ref": "master",
  "sha": "0dc51e1e1c08435c6a6530adf544179cb4ea88f3",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

Internal aircraft controls are much more difficult to click and interact with. Looks like the click "hitboxes" are moved away from the actual objects. Some controls are only possible to interact with on the closest zoom levels.

### Expected behavior

be able to easily interact with internal aircraft controls on the farthest zoom level (like before).

### Steps to reproduce

1. go to cockpit view
2. try to interact with the controls (the farther the camera zoom, the harder)

**Comment by tracernz** [comment]
Disable “lens correction” in MSFS settings. New sim bug in SU7.

**Comment by 2hwk** [comment]
Not a bug with the addon, this is a sim bug caused by having Lens Correction on. This was working before SU7, please report to the Asobo MSFS Zendesk.
