### ISSUE TITLE
A32NX Autopilot Problems

### ISSUE THREAD

**Issue by minkyusimmer** [flybywiresim/a32nx#6211]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-11-19T14:33:32+00:00",
  "ref": "master",
  "sha": "860e15695db836a7840d9390a613de3426b1b0fc",
  "actor": "tracernz",
  "event_name": "manual"
}
```

### Describe the bug

Multiple Problems with the Autopilot
1. The aircraft climbs past the cruise altitude, even when managed altitude is set.
2. Aircraft automatically disconnects from the autopilot, and won't reconnect.

### Expected behavior

The aircraft climbs to cruise altitude and stays there. The autopilot remains on until it is turned off.

### Steps to reproduce

1. Takeoff with a full route.
2. Enable autopilot, with managed altitude.

### Additional info (optional)

This issue started occuring a week ago, even before SU7. It first happened when I was on a flight from KSJC-KSAN.

**Comment by aguther** [comment]
This is quite few information for a non-general issue.

Please provide an FDR file of a flight where this happened. You find the FDR file in the work folder (see https://docs.flybywiresim.com/fbw-a32nx/feature-guides/autopilot-fbw/?h=autop#work-folder-location). Upload the file to a file transfer service like (https://www.swisstransfer.com) and put the link in this issue.

I guess you‘re either getting into a protection like high angle of attack (stall protection) or there is an issue with inputs.

The AP disconnects if:
- sidestick input > 50% (after calibration)
- rudder input > 40% (after calibration)
- any protection active (high speed protection, high angle of attack protection)
- Pitch is > 25°
- Pitch is < -13°
- Bank angle is > 45°
- on ground and go around is initiated
- ROLL OUT mode is disengaged on ground (in case of Autoland)

There are NO other reasons it disconnects.

**Comment by minkyusimmer** [comment]
> * What did you set on the FCU?

Speed was managed, Heading was managed, and Cruise Altitude set to 13000 (Flying from PHNL-PHOG)

> * What did the FMA say in those flights, especially when it climbed past your target altitude? Was the AP active in that moment?

THR CLB | ALT | NAV | AP1, 1 FD 2, A/THR

Autopilot was active during the climb and after it passed 13000, there was the long beep to signal you have crossed your desired altitude.

> * Did you setup the FMGC?

Yes I setup the MCDU correctly. And all the necessary information was inputted.

> * What was your speed?

My cruise speed was 290 knots or around 0.55 Mach.

> To answer so questions and to make it simple for us: Please provide an FDR file of a flight where this happened. You find the FDR file in the work folder (see https://docs.flybywiresim.com/fbw-a32nx/feature-guides/autopilot-fbw/?h=autop#work-folder-location). Upload the file to a file transfer service like (https://www.swisstransfer.com) and put the link in this issue.

Two links, I think the latter is the one for the full flight, and the first one is just a reattempt of a landing yesterday.
https://drive.google.com/file/d/1sB7kC6I12_dfk1pHrIiug-OCMEfAVqyq/view?usp=sharing
https://drive.google.com/file/d/1IgYHY-m1CUgD-hlYJQrAjPg5KoTQhXGI/view?usp=sharing
 
> The AP disconnects if:
> 
> * sidestick input > 50% (after calibration)
> * rudder input > 40% (after calibration)
> * any protection active (high speed protection, high angle of attack protection)
> * Pitch is > 25°
> * Pitch is < -13°
> * Bank angle is > 45°
> * on ground and go around is initiated
> * ROLL OUT mode is disengaged on ground (in case of Autoland)
> 
> There are NO other reasons it disconnects.

This may be true. My rudder pedals naturally stays a bit left even when I am not touching them, I do not know how to recalibrate them to center them.

**Comment by minkyusimmer** [comment]
I have updated to the latest version under Benjozork last night after my flight, but did not test it again.

**Comment by aguther** [comment]
Thank you for providing the files.

The airplane was not capturing the altitude because the AP was simply not engaged, because it disconnected during ALT*:
![image](https://user-images.githubusercontent.com/6629914/142774046-7bfd251e-e5bb-4642-a35c-c92cc1251c37.png)

The reason can be seen in the next diagram. The rudder was reaching -0.4 which is 40% of travel which disconnects AP:
![image](https://user-images.githubusercontent.com/6629914/142774084-80aa9a12-2bac-4002-8d9a-c60650e23660.png)

Here we can see that it got worse and worse with the rudder and that you tried to re-engage the AP:
![image](https://user-images.githubusercontent.com/6629914/142774154-9abfb979-9277-479e-a25f-3b09751817e7.png)

Some additional questions:
* did you use the EFB?
* did you use the Navigraph In-Game Panel?
* did you use any other UI llike weather etc?
* did you somehow press NumPad 0 or any Enter key several times?

The reason I ask this is because some UI (also a part, not all of the EFB) do not correctly mask keybindings and when you press Enter or NumPad 0 it moves the rudder unintentionally. For the EFB a fix is underway but for some other UI we cannot fix it.

A solution is either to regularly press NumPad 5 (to reset rudder) or slightly move the rudder axis after using some of that stuff. The other way is of course to remove the keybinding.

**Comment by minkyusimmer** [comment]
> * did you use the EFB?

I use the EFB, but I do not type anything in there. I use it for ground services.

> * did you use the Navigraph In-Game Panel?

I don't have Navigraph

> * did you use any other UI llike weather etc?

No other weather programs, just default MSFS weather.

> * did you somehow press NumPad 0 or any Enter key several times?
 
I did press NumPad 0 because that is the keybind that I saved to my Cockpit view.

> A solution is either to regularly press NumPad 5 (to reset rudder) or slightly move the rudder axis after using some of that stuff. The other way is of course to remove the keybinding.

Is there a way I can recalibrate the rudder in MSFS? When I go to the F/CTL page in the A32nx, my rudder is slightly to the left.

**Comment by aguther** [comment]
I didn’t mean another weather application, I meant using the user interface of MSFS. In the end everything that makes you press NumPad 0 or Enter is a potential problem.

If you have the NumPad 0 mapped to cockpit view I highly recommend to remove the key binding for rudder.

If you axis is off you should calibrate it in Windows settings.

**Comment by minkyusimmer** [comment]
Thank you very much! I unbinded all the keybinds for flight control surfaces!

**Comment by minkyusimmer** [comment]
> Thank you for providing the files.
> 
> The airplane was not capturing the altitude because the AP was simply not engaged, because it disconnected during ALT*: ![image](https://user-images.githubusercontent.com/6629914/142774046-7bfd251e-e5bb-4642-a35c-c92cc1251c37.png)
> 
> The reason can be seen in the next diagram. The rudder was reaching -0.4 which is 40% of travel which disconnects AP: ![image](https://user-images.githubusercontent.com/6629914/142774084-80aa9a12-2bac-4002-8d9a-c60650e23660.png)
> 
> Here we can see that it got worse and worse with the rudder and that you tried to re-engage the AP: ![image](https://user-images.githubusercontent.com/6629914/142774154-9abfb979-9277-479e-a25f-3b09751817e7.png)


Since the rudder was more than 40% deflected, does that explain why the AP was disconnected and why it did not re-enable?

**Comment by aguther** [comment]
Yes! That was exactly the issue. The problem is that when rudder is moved using keys it doesn’t return automatically and an axis does not override it as long as it’s not moving.
