### ISSUE TITLE
joystick does not work

### ISSUE THREAD

**Issue by filippo0076** [flybywiresim/a32nx#6215]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-11-21T01:55:55+00:00",
  "ref": "v0.7.3",
  "sha": "e6fb4129367d266aa6f77a979e37f66d458a2575",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

Joystick only reacts when tilting the aircraft forwards or backwards
Turning the Plane is impossible, because the Joystick and the rudder (the rudder in the wings, not in the tail) do not react to pressing the Turn Button (to tilt the Plane) in the chosen direction 
On other Aircraft ( Regular A320, Capitansim 777-300ER and 747-8i ) this problem does not occur, and each of the listed Aircraft works fine
Greetings Philip 

Translated with www.DeepL.com/Translator (free version)

### Expected behavior

I expected the aircraft to react appropriately to a pressed turn (roll) key

### Steps to reproduce

1. I created a flight plan
2. I clicked "fly".
When I tried to turn, neither the aircraft nor the joystick responded.

### Discord Username (optional)

fajlip#7638

**Comment by aguther** [comment]
Keyboard is currently not supported.
