### ISSUE TITLE
Flightplan issues with custom FPM

### ISSUE THREAD

**Issue by ErikNL80** [flybywiresim/a32nx#6229]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-11-23T12:47:29+00:00",
  "ref": "master",
  "sha": "ef1189745bcafbe6f2bb23a73a93d35a3de88362",
  "actor": "bouveng",
  "event_name": "manual"
}
```

### Describe the bug

I am using the built-in flightplanner to plan a flight, including departure and arrival. I am not using Navigraph, just standard Metoblue data... Prior to merging of the custom FPM this was OK most of the time, expect for a few (known) issues.

Now I have done some flights the past few days, and notice the following issues:
- The flight number (from the aircraft page) is not filled in the MCDU
- The cruise altitude is not filled in the MCDU
- DISCO's in every flightplan (can be resolved easily)
- Strange routing (sometimes strange lines)
- Strange approaches

I am trying to check the route prior to departure and remove the DISCO's, but still getting some strange routing issues, especially on arrival.

I feel the FBW is having focus more on importing from i.e. SimBrief and the use of Navigraph then the use of the (maybe) limited features of the default flightplanner and navdata...

I sincerely hope you will keep supporting the use of the built-in flight planner instead of using all kinds of external tools to fly.

### Expected behavior

I would expect the route created in the built-in flight planner is correctly shown in the MCDU including departure and arrival. Without strange routing and DISCO's.

### Steps to reproduce

1. Create a flight using the built-in flightplanner (i.e. LEAL to EGKK, EHRD to LGAV), including departure and arrival
2. Start a flight and check the MCDU/PFD, compare it with the VFR map as well
3. Observe DISCO's and arrival routing

**Comment by ErikNL80** [comment]
> Discontinuities are not an error or a bug.
> 
> See https://docs.flybywiresim.com/pilots-corner/beginner-guide/preparing-mcdu/#discontinuity.
> 
> As for the flight number and cruise altitude I can look into it. For the "strange path and approach" please provide visual examples or concrete routes otherwise we can't help.

Thanks for the quick reply, would be great if you can look into flight number and cruise altitude. Meanwhile I keep an eye on strange routing issues and will report back in this thread.

**Comment by lorenlan** [comment]
Hi everyone, I think I have the same bug about strange lines in FP on App.. I see this bug specially approaching EDDM. I send some pictures 
![Uploading IMG_20211123_233226.jpg…]()

**Comment by lorenlan** [comment]
![Uploading IMG_20211123_233226.jpg…]()

**Comment by lorenlan** [comment]
![IMG_20211123_233226](https://user-images.githubusercontent.com/70802921/143209610-c147216f-697b-4f03-a224-3eaeebb47a3d.jpg)

**Comment by Benjozork** [comment]
> Hi everyone, I think I have the same bug about strange lines in FP on App.. I see this bug specially approaching EDDM. I send some pictures. I see "manual" followed by discontinuity when select app and vias in the mcdu. Deleting manual and discontinuity the FP its right, but when I'm close to airport the lines be strange. Like in the picture, and this is for all rwy's. I've see this issue also with other airports like egkk and other

MANUAl legs are there for a reason. It's not always possible for the flight plan to connect there and for the FMS to make a flyable turn. You should not be deleting them.

See https://docs.flybywiresim.com/pilots-corner/beginner-guide/preparing-mcdu/#discontinuity.

**Comment by lorenlan** [comment]
So I don't have to delete manual, I have to make the plane follow the plan?

**Comment by Benjozork** [comment]
As explained in the guide:

> A MANUAL leg stays on a constant TRK or HDG and has no termination point. When the aircraft is flying a MANUAL leg, the NAV mode remains engaged and predictions assume that the aircraft will fly a direct leg from its present position to the next waypoint (DIR TO). When the aircraft is cleared to fly to the next waypoint of the flight plan, the flight crew performs a DIR TO.

This means when you recieve vectors from ATC you sequence manually using DIR TO. If you do not have ATC then just do it when you are far enougj behind the final approach as to not cause too tight of an angle.

**Comment by lorenlan** [comment]
Ok thank you for te patience to reply.. Now understood.. Thank you for hard work,  FREE

**Comment by MStallen** [comment]
I have the same strange legs as I select an existing SID or STAR. They worked in the last dev's but with the new cFMC  not anymore.

**Comment by Benjozork** [comment]
Please provide a screenshot otherwise we cannot help.

**Comment by MStallen** [comment]
Tomorrow I will provide some examples

**Comment by ErikNL80** [comment]
Here is an issue; flight from EKCH to EDDH. Chosen an ILS15 approach without STAR, see the difference between the VFR map and the PFD:

![EDDH](https://user-images.githubusercontent.com/71258178/143300986-5f95bb87-334d-46d9-a56d-04f85cc69b74.png)

**Comment by RodneyKoolman** [comment]
I also get really weird flight plans from the MCDU. Using simbrief to generate multiple. The route looks good on the VFR map but is all over the place in the PFD.

**Comment by Benjozork** [comment]
@RodneyKoolman 
Please provide screenshots. Otherwise we cannot do anything.

**Comment by Benjozork** [comment]
> Here is an issue; flight from EKCH to EDDH. Chosen an ILS15 approach without STAR, see the difference between the VFR map and the PFD:
> 
> ![EDDH](https://user-images.githubusercontent.com/71258178/143300986-5f95bb87-334d-46d9-a56d-04f85cc69b74.png)
> 
> LUB is not recognized and HAM is inserted?

Syncing to the sim is not guaranteed to work perfectly.
