### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by Middi25X** [flybywiresim/a32nx#623]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**

**References**

**Additional context**

Wish that when you fly turns will be more smootly,also when you come to a waypoint that aircraft turn smooth and not rapdly  :/ I also hope OP Clmb and OP Descent will be fix,sometimes it not climb when i click open climb or descent and have to use V/S some times... :(

**Comment by devHazz** [comment]
Can you go more in to detail with the ascent/descent patterns that are occuring?

**Comment by Middi25X** [comment]
yes sure, after takeoff when i push open climb or just climb is just level off then i need to use V/S to get it to climb and same with descent to, sometimes it work sometimes not dont know why this is happening :S have check in the mcdu for any altitide restrict but all seems good. sorry for bad english im from Norway xD

**Comment by cobrafast** [comment]
I have noticed something similar: Autothrottle is unnecessarily slow at increasing/reducing power for climbs/descents and as a result the plane needs some time to pick up vertical speed. If you manually dial in a VS to workaround this, autothrottle will react quicker as it will try to maintain the selected airspeed.

**Comment by Benjozork** [comment]
This is not a feature request.
