### ISSUE TITLE
Option to configure PFD's/Screen Brightness using config files or EFB

### ISSUE THREAD

**Issue by SagiEran** [flybywiresim/a32nx#6230]
### Aircraft Version

Development

### Description

I wish we could configure PFD's or Screen Brightness using configuration file or the EFB to save the effort and process of using the brightness knobs.
Sometimes, launching the flight in bad weather or full day time , will require large brightness adjustments.
I find my self constantly adjusting the brightness on each flight and will love to set those settings in s pre defined state (such as configuration files) or use the EFB for fast brightness settings.

Thanks !

### Discord Username (optional)

Eran.S WW5446#2617

**Comment by bouveng** [comment]
Related issue https://github.com/flybywiresim/a32nx/issues/5451

**Comment by 2hwk** [comment]
For the purposes of consolidation I'll be closing this issue, #5451 is more active.
