### ISSUE TITLE
Issue with destination data?

### ISSUE THREAD

**Issue by oMrSmith** [flybywiresim/a32nx#6231]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-11-23T13:37:26+00:00",
  "ref": "master",
  "sha": "6c72eb63d8a5aede7ce2f5225d8d87b8bf27720a",
  "actor": "crocket63",
  "event_name": "manual"
}
```

### Describe the bug

The message "ENTER DEST DATA"
still appears 
even if the mandatory (orange) fields
(QNH and TEMP) have already been entered.

Is that correct?

### Expected behavior

The message "ENTER DEST DATA"
should not appear if the mandatory (orange) fields
(QNH and TEMP) have already been entered.

### Steps to reproduce

Enter destination data (QNH and TEMP) before message plops up.

**Comment by Benjozork** [comment]
Please provide a screenshot of the PERF page at that moment

**Comment by Benjozork** [comment]
Did you enter a BARO/RADIO ? (MDA/DH) ?

**Comment by oMrSmith** [comment]
I'll have to recheck. I suppose, entering either one should satisfy MCDU, correct?

**Comment by ErikNL80** [comment]
I also see this, even with one of these filled... Should they be filled both?

**Comment by Benjozork** [comment]
@derl30n

**Comment by oMrSmith** [comment]
![image](https://user-images.githubusercontent.com/78870770/143062821-62c8118e-2d6b-4050-bb5b-acce2d86f973.png)

**Comment by tracernz** [comment]
You have to enter wind. This is true to life even though it’s not amber.
