### ISSUE TITLE
SInce SU 7, build-in ATC not possible when using Simbrief-imported flight plan

### ISSUE THREAD

**Issue by flytester** [flybywiresim/a32nx#6233]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-11-23T13:37:26+00:00",
  "ref": "master",
  "sha": "6c72eb63d8a5aede7ce2f5225d8d87b8bf27720a",
  "actor": "crocket63",
  "event_name": "manual"
}
```

### Describe the bug

Since SU 7, it is not possible to file your Simbrief-imported flight plan with ATC. The ATC-menu used to have an option to do this, but it seems to have vanished. is this an Asobo-issue or something that will be fixed in the A32NX?

### Expected behavior

Possibility to file IFR-Flight plan

### Steps to reproduce

Start flight, import FP from simbrief, try to file with ATC

**Comment by ErikNL80** [comment]
Have you enabled the EFB option to sync the plan with MSFS?

**Comment by flytester** [comment]
No, will try it tomorrow. Thanks for the advice!

**Comment by Guipid** [comment]
I confirm this bug. The in development version the option to ask for an IFR clearance does not appear on ATC list anymore.

**Comment by Kimbyeoungjang** [comment]
I believe this caused by merge #4953 

I think this will be not fixed because development version now use Custom Flight Plan not a asobo thing

**Comment by tracernz** [comment]
> Have you enabled the EFB option to sync the plan with MSFS?

This is the answer. Syncing the flight-plan to MSFS is disabled by default because some flight plan modifications can cause CTDs.

**Comment by Guipid** [comment]
Yes this is the answer. If you change in the EFB Sim Options the config 'Sync MSFS Flight Plan' to 'Save' (default is 'Load Only') solves the matter.

Now i can file the IFR with FS2020 ATC with no problem.
