### ISSUE TITLE
No Avionic displayed (black screen) - Solved -

### ISSUE THREAD

**Issue by Biniou671** [flybywiresim/a32nx#6234]
### Aircraft Version

Development

### Build info

```json
"built": "2021-11-23T13:37:26+00:00",
  "ref": "master",
  "sha": "6c72eb63d8a5aede7ce2f5225d8d87b8bf27720a",
  "actor": "crocket63",
  "event_name": "manual"
```

### Describe the bug

After entering the cockpit, and switching on the GPU, avionic screens remain black, PDU, ECAM, MCDU, Chrono, etc... including the altitude, speed, heading displays.
I noticed this since the last 2-3 Dev updates, but was waiting for a solution before to highlight.
Beside, I also noticed all the button VOR D, WPT, APT, etc.. are all on, when entering the cockpit 

### Expected behavior

I expect to have all the avionics screen, and cockpit light on, when starting the GPU.

### Steps to reproduce

1. Enter the cockpit
2. switch on the batteries
3. Switch on the GPU.
[A32NX_ Dev_V. 6c72eb6.docx](https://github.com/flybywiresim/a32nx/files/7593720/A32NX_.Dev_V.6c72eb6.docx)

### Additional info (optional)

Was this working before?
Yes.

 When did the issue start occurring?
After the last 2-3 Dev version updates.

**Comment by maxhades** [comment]
Same here. Black screens, Buttons VOR...all set to on...

I have done a fresh re install. Doesn't help.

Max

**Comment by Biniou671** [comment]
Hi Dev Team,

I don't know about Maxhades, but as far I am concerned, the latest Dev. update # 6803283, solved my avionic issue.
Just know, I have been able to complete a flight LTAI-EDDK gate-to-gate without issue.
Thanks again.
