### ISSUE TITLE
[BUG] Autobrake application doesn't affect brake temps on WHEEL page

### ISSUE THREAD

**Issue by wpine215** [flybywiresim/a32nx#624]
**Mod Version**

Master

**Describe the bug**

Autobrake application doesn't affect brake temps on WHEEL page

**To Reproduce**

1. Start on runway, release parking brake, select WHEEL page and set takeoff power
2. At 100 kts, reduce power to IDLE
3. Aircraft should perform RTO and apply max autobrake, but brake temps will stay the same

**Comment by Benjozork** [comment]
I'm going to look into this as I am working on the WHEEL page right now.

**Comment by Coralec** [comment]
Bug replicated.

**Comment by CoffeePanda0** [comment]
Can confirm this, just did some testing

**Comment by Benjozork** [comment]
The issue is caused because the BrakeTemp logic currently only increases the temperature if the brake position is above 30 000.

MAX autobrake setting does not go beyond that threshold, so it does not trigger a temperature increase.

I will probably change the threshold to a coefficient obtained from an exponential function. Any opinions or alternatives ?

**Comment by Coralec** [comment]
I mean, if anything is gonna cause hot breaks its gonna be an aborted takeoff.

**Comment by lukecologne** [comment]
Alternative would be to implement a more or less (mostly less) accurate temperature simulation, with dissipation etc. Then we wouldn't need a threshold. But maybe that should be done at a later state. Also what is weird is that max autobrakes doesn't actually apply max braking, maybe we need to look into that

**Comment by Benjozork** [comment]
> Alternative would be to implement a more or less (mostly less) accurate temperature simulation, with dissipation etc. Then we wouldn't need a threshold. But maybe that should be done at a later state. Also what is weird is that max autobrakes doesn't actually apply max braking, maybe we need to look into that

I have this planned in the future taking into account heat transfer coefficients and ambient temperature ! Stay tuned !

**Comment by CoffeePanda0** [comment]
> 
> 
> I mean, if anything is gonna cause hot breaks its gonna be an aborted takeoff.

Yeah I tried a few, RTOs don't cause  hot brakes with autobrake and only with toe brakes

**Comment by Benjozork** [comment]
> I mean, if anything is gonna cause hot breaks its gonna be an aborted takeoff.

When I say 30,000, I am refering to brake position. Not altitude.

**Comment by lukecologne** [comment]
> 
> 
> > Alternative would be to implement a more or less (mostly less) accurate temperature simulation, with dissipation etc. Then we wouldn't need a threshold. But maybe that should be done at a later state. Also what is weird is that max autobrakes doesn't actually apply max braking, maybe we need to look into that
> 
> I have this planned in the future taking into account heat transfer coefficients and ambient temperature ! Stay tuned !

Very nice. When you say in the future, how long are we talking about? If it's a bit longer then maybe we could implement a rudimentary solution as a bridge, because obviously the current solution isn't that good
