### ISSUE TITLE
FMS trajectory - LEPA - ILS06 approach

### ISSUE THREAD

**Issue by JLD95** [flybywiresim/a32nx#6250]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-11-26T05:55:34+00:00",
  "ref": "master",
  "sha": "2e492320644f1ad416a2fd5d962709d2b4ea7378",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

Final patch miss CF06, need to make a small manual in order to reach CF06.
I use SimBrief route: LFMN/04R RUBA6A RUBAS UN736 BALEN UT250 RIXOT RIXO1J  LEPA/06L

### Expected behavior

FMS patch shall be fly over CF06

### Steps to reproduce

use SimBrief route: LFMN/04R RUBA6A RUBAS UN736 BALEN UT250 RIXOT RIXO1J  LEPA/06L
Approach : ILS06L

### Additional info (optional)

![2021-11-26 (1)](https://user-images.githubusercontent.com/5894146/143617522-7dd0052f-3ca0-4225-abe5-2f0cfbf655e2.jpg)

### Discord Username (optional)

JLD95#4438

**Comment by CptBayer** [comment]
hi, this isn´t the case only at LEPA .... I guess the developer team know that issue and they are working hard for us :-) .... thanx folks !!!

**Comment by tracernz** [comment]
Overfly is not supported, nor intended to be supported at this time, as is the nature of an aircraft this early in the development cycle. It will come later. I will close this for now as this issue is already noted as a known issue.
