### ISSUE TITLE
ZFWCG not available before boarding completes

### ISSUE THREAD

**Issue by SeagullCGN** [flybywiresim/a32nx#6254]
### Aircraft Version

Development

### Description

Insertion of a possibility to calculate or read out the ZWFCG

Due to the new loading system, the information from the ZFWCG is only received very late, since simbrief does not calculate this and output it in the OFB. However, the actual CG is required for entering the INIT B page. To wait with the programming of the page until the boarding process is finished, delays the flight process in my opinion

### Discord Username (optional)

DLH22706 I Jens#6576

**Comment by John-UK** [comment]
You can set the passenger loading speed to an unrealistic value in the EFB. Then they can load instantly.
