### ISSUE TITLE
Multi GPU and performance

### ISSUE THREAD

**Issue by DanP77** [flybywiresim/a32nx#6256]
### Aircraft Version

Development

### Description

Please add the capability to render panels on a secondary GPU if that is available to improve performance.

**Comment by Benjozork** [comment]
We cannot control how the simulator renders displays.

**Comment by Benjozork** [comment]
By the way, display rendering is far from the most expensive things. It takes 1-2 ms at most. Avionics and FMS code is the biggest hit.

**Comment by DanP77** [comment]
> By the way, display rendering is far from the most expensive things.

what I see is that in many case from Outside view I've an higher FPS than from Cockpit.
From Inside often my GPU is not able to work more than 70%, switching outside I reach 100%.

**Comment by DanP77** [comment]
Check also this

https://forums.flightsimulator.com/t/coherent-gt-and-performance-decreasing-during-flight/407244/59

**Comment by Benjozork** [comment]
There is a difference between `CoherentGTDraw` thread and `CoherentGTUIThread`. The former is actual rendering (and I have never seen it go above 1-2ms) and the latter is FMS/Avionics code, which is the one which is hit the most.

Unless you see `CoherentGTDraw` (not `UIThread`!) be abnormally high, this is not related to display rendering.

**Comment by tracernz** [comment]
As a small thought experiment, think about what's on the (2D) displays and how hard it would be for the GPU to draw... just lines and arcs... vs. the flight deck, what's outside the window, etc...
