### ISSUE TITLE
Add option to import fuel from simbrief to EFB

### ISSUE THREAD

**Issue by foxmike80** [flybywiresim/a32nx#6263]
### Aircraft Version

Development

### Description

With the new w&b and fuel management one has to manually select the desired fuel on the dispatch /fuel page in the EFB.
Could you add an "import fuel from simbrief" button to that page?

### Discord Username (optional)

foxmike1080

**Comment by John-UK** [comment]
There was an import from SIMBRIEF fuel. The fuel loaded is not for example 6758kg that is the tanks value from the OFP like before. The dispatcher or captain would never uplift that EXACT amount. You make a decision on the amount of fuel needed.  Do you need at add 3 tonnes or 4.5 tonnes to the current FOB.

**Comment by tracernz** [comment]
There should be a button to copy the OFP block fuel into the refueling target... you can then adjust from there as required before starting the fueling.

**Comment by sidnov** [comment]
> There should be a button to copy the OFP block fuel into the refueling target... you can then adjust from there as required before starting the fueling.

Trying to make the "FROM SIMBRIEF" button on the EFB Dashboard do that for us, instead of adding another button on the fuelpage specifically. Will update how it goes

**Comment by oMrSmith** [comment]
Proposal für the Fuel Page (EFB):
First value shows the FOB  
Second value the target fuel.

Only the "target fuel" can be edited.
By default this value is automatically set to
the block fuel drom Simbrief, if the data has been catched on the dashboard...

**Comment by FRYYYYYY** [comment]
Or: Just pre-fill the estimated fuel by the amount of fuel generated by Simbrief. So that you just have to use the "start fuel" button if you want to use the calculated fuel.
