### ISSUE TITLE
Waypoint on wrong Radial

### ISSUE THREAD

**Issue by FSC190** [flybywiresim/a32nx#6268]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-11-26T19:06:28+00:00",
  "ref": "master",
  "sha": "6803283d85f97decbccf60eb3162d701ec71b217",
  "actor": "sidnov",
  "event_name": "manual"
}
```

### Describe the bug

On Approach where a waypoint is fixed as a Bearing Distance WP (See Screenshot) the Point is placed on the side of e.E. the VOR. instead of R090 it is R270. See screen shot below.
<img width="932" alt="Screenshot 2021-11-29 135939" src="https://user-images.githubusercontent.com/36174809/143872922-adb66cb3-86bb-4460-9573-2742b4197288.png">

### Expected behavior

Waypoint is placed on the right side. (R090)

### Steps to reproduce

LFML/31R MAMES6N MAMES UM984 BISBA UN975 ADUXO ADUXO1D LEMD/32R
ILS Z RWY 32R Aspin Transition

### Additional info (optional)

This is a long standing problem since the custom Lnav is used in the formal Experimental Version now in the Developer Version.

### Discord Username (optional)

FSC190

**Comment by tracernz** [comment]
Are you using MS navdata, or have you installed Navigraph data with the Navdata Center app? This doesn't look like what's in the Navigraph db...

**Comment by FSC190** [comment]
No I don't use Navigraph, to many problems with incorrect Data in the past.
Do you think I should use it now?

**Comment by FSC190** [comment]
I tried Navigraph data, latest AIRAC and with this data it looks good. So it's maybe a problem with the MSFS-Data.

**Comment by tracernz** [comment]
> No I don't use Navigraph, to many problems with incorrect Data in the past.
Do you think I should use it now?

Navigraph data should work well with our own flight planning and guidance system now in the dev version of A32NX.

> I tried Navigraph data, latest AIRAC and with this data it looks good. So it's maybe a problem with the MSFS-Data.

I thought that might be the case... but it's still a problem because not everybody uses Navigraph.

**Comment by tracernz** [comment]
I don't think this is an issue anymore, but hard to check because this approach transition doesn't exist anymore, and the new ones have a different coding.
