### ISSUE TITLE
FUEL boarding faulting

### ISSUE THREAD

**Issue by grignafly** [flybywiresim/a32nx#6270]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-11-26T19:06:28+00:00",
  "ref": "master",
  "sha": "6803283d85f97decbccf60eb3162d701ec71b217",
  "actor": "sidnov",
  "event_name": "manual"
}
```

### Describe the bug

After Importing an FP from SIMBRIEF an arbitrary quantity of FUEL is loaded, around 3800-4000 KG.
Trying to add additional fuel with MSFS UI, after increasing slider at 100% too,  it go back itself to original fuel quantity and there no way to change Fuel On Board
I have removed any additionl livery from Community

### Expected behavior

This issue happens with both Stable & Development download by Installer

### Steps to reproduce

Import FP from SIMBRIEF and try to add FUEL

**Comment by sidnov** [comment]
In-Sim Fuel UI has been disabled. You need to use the EFB fuel page to refuel now

**Comment by sidnov** [comment]
Side note: importing fuel value from Simbrief OFP automatically is being worked on

**Comment by grignafly** [comment]
> In-Sim Fuel UI has been disabled. You need to use the EFB fuel page to refuel now

Sorry, but what you intend with "EFB fuel page"? Where is this page?
Thanks

**Comment by globin** [comment]
https://docs.flybywiresim.com/fbw-a32nx/feature-guides/loading-fuel-weight/
