### ISSUE TITLE
Sometimes the AP don´t follow WP and start manual HEADING

### ISSUE THREAD

**Issue by sergclio** [flybywiresim/a32nx#6285]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-11-26T19:06:28+00:00",
  "ref": "master",
  "sha": "6803283d85f97decbccf60eb3162d701ec71b217",
  "actor": "sidnov",
  "event_name": "manual"
}
```

### Describe the bug

When you're flying with a F-Plan previously imported of Sim-Brief, the AP loose the WP heading and becames manually HDG.

### Expected behavior

The AP follows the heading of the WP

### Steps to reproduce

1. Import a F-Plan from Sim-Brief
2. Take Off and a few minutes the AP don´t follow the WP heading

### Discord Username (optional)

sergii1917#9417

**Comment by Benjozork** [comment]
Are you sure you didn't sequence a waypoint with a discontinuity ?

**Comment by sergclio** [comment]
I'm sure. i clear all discontinuity of the f-plan by clear button of mcdu

**Comment by aguther** [comment]
Maybe XTK for some reason gets larger than 11 NM…and then it disengages. The other possibility is that the availability variable gets 0

**Comment by LordNecton** [comment]
Im having the same problem, manual Heading mode automatically engages for me sometimes  just after take off and sometimes 40nm out from landing and there is no way of turning it off to resume the flight plan i set up from within the sim

**Comment by John-UK** [comment]
FPS drop nearing a more detailed scenery especially after a longer flight.

**Comment by aguther** [comment]
If you have an FDR file from a flight where this happens it would be good to get it, then I can tell more about it:
https://docs.flybywiresim.com/fdr

**Comment by aguther** [comment]
@imperatormatthias Thank you for providing the file. Can you re-upload it? It seems it got corrupted somehow (zip extraction errror).

**Comment by imperatormatthias** [comment]
I re-uploaded however I got the same error so here is a google drive link. https://drive.google.com/file/d/1MMOpROC0tzdPTqod3J_1odHp4g4utYHz/view?usp=sharing

**Comment by aguther** [comment]
Ok, I've analyzed it. As we can see an HDG pull event was triggering the switch from NAV to HDG. The NAV condition in the AP was 1 in the moment in question (therefore XTK was also within 10 NM range, but it was large for a moment). Now HDG pull can either be triggered manually on the FCU or an assignment or when the FM parts processes a discontinuity.

I assume for any reason the latter was the case: a discontinuity was causing the issue. Why that's the golden question when you say there was none in the flight plan.

![image](https://user-images.githubusercontent.com/6629914/144321715-daef2363-0b9b-49d6-b976-8ad063d1e544.png)
![image](https://user-images.githubusercontent.com/6629914/144322438-074140c5-4465-4736-85d6-5e2278499760.png)
![image](https://user-images.githubusercontent.com/6629914/144321843-4bc13164-25bb-41b3-91af-5371de5422a9.png)
![image](https://user-images.githubusercontent.com/6629914/144321891-ee7ea169-5842-40e0-8ec7-a30ef3145808.png)
![image](https://user-images.githubusercontent.com/6629914/144322175-fdca7678-985f-427c-a104-78bc65a87ed3.png)

**Comment by imperatormatthias** [comment]
I'm 99.9% certain there were no discontinuities being displayed in the MCDU at least. Before the flight from the FDR I uploaded I had experienced this bug two times and I found this issue on github before I flew the latest flight so I made sure to check multiple times for discontinuities to make sure that was not the issue.

**Comment by aguther** [comment]
No worries, right now I would assume a bug in processing somehow like the plane sometimes turns quite early on approach.

There is an update in development that improves all of that.

**Comment by sergclio** [comment]
thanks so much! Have a nice day!
