### ISSUE TITLE
  TAT is +271C, SAT+ 248C  when reaching > FL 250 (approx) using  Dev build 8dc5bc7; all hell break loose from there

### ISSUE THREAD

**Issue by Rascal650** [flybywiresim/a32nx#6288]
### Aircraft Version

Development

### Build info

```json
8dc5bc7
```

### Describe the bug

Using this latest dev build  (8dc5bc7),   I'm getting crazy TAT and SAT numbers (> 200c) when crossing FL250 to FL300.  At this point,  you get a master warning.  Speed is off the chart and fuel consumption is humongous.

Descending to a lower FL seems to fix the problem.

My flight is from KATL to KTPA, taking off 27R,  BANNG2 SID.  This problem happened twice in a row using this build.  I had never seen that before (I last upgraded the day before)

### Expected behavior

SAT and TAT should be correct at all FLs

### Steps to reproduce

KATL to KTPA, taking off 27R,  BANNG2 SID.  (using real weather, real time - 3h to get sunlight)

Follow your flight plan, once you get into F250 - FL300,   the SAT and TAT temps go crazy

**Comment by Rascal650** [comment]
![20211202_144951](https://user-images.githubusercontent.com/88073848/144523937-269a0b7f-5338-4247-bcbe-f340e5a567f4.jpg)

The weather in Florida is unseasonably hot this winter....

**Comment by sidnov** [comment]
This is a known simulator issue, and not something that could be fixed on the add-on side. It's recommended to use preset weather instead of live until MS/Asobo fix the issue
