### ISSUE TITLE
Inappropriate engine runup to N1 120% or greater at FL260

### ISSUE THREAD

**Issue by xrafa89** [flybywiresim/a32nx#6289]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-12-02T01:37:49+00:00",
  "ref": "master",
  "sha": "8dc5bc79bbbd69f4a90c20816c0ea5e22575cbad",
  "actor": "tracernz",
  "event_name": "manual"
}
```

### Describe the bug

Spontaneous, intermittent run up of engines from cruise/ auto-throttle to N1 120%+, followed by rundown to idle and slow N1 increase to previous.  This is consistently occurring at approx FL260; replicated four times.

### Expected behavior

N1/ engine performance consistent with appropriate power level associated with climb or cruise.

### Steps to reproduce

1.  Ascend as per normal with autopilot and A/T.

### Discord Username (optional)

xrafa89

**Comment by tshomas** [comment]
This is a current simulator issue with the live weather bug, outside air temperatures are hitting plus +200C above FL240 which is causing the engine issues.
Unable to be fixed on the addon side, it’s down to asobo to repair.

**Comment by Benjozork** [comment]
Simulator issue.

**Comment by xrafa89** [comment]
Wasn't aware of that. Thanks for the update!
