### ISSUE TITLE
Massive fuel flow increase above FL 238

### ISSUE THREAD

**Issue by EisernUnion** [flybywiresim/a32nx#6293]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-12-02T01:37:49+00:00",
  "ref": "master",
  "sha": "8dc5bc79bbbd69f4a90c20816c0ea5e22575cbad",
  "actor": "tracernz",
  "event_name": "manual"
}
```

### Describe the bug

When climbing above FL 238 Fuel Flow increases up 100 000 kg/h ....below it goes back to normal .... Video Link 

https://youtu.be/26q_B9PWWGA

Its reproducible, happend yesterday and today (maybe since last version)

### Expected behavior

No increasing FF at FL 238

### Steps to reproduce

Just Fly above FL 238

### References (optional)

https://youtu.be/26q_B9PWWGA

**Comment by Saschl** [comment]
MSFS live weather is currently having issues, you will see outside temperatures up to 300°C in which the plane cannot operate. Nothing we can do about, see https://docs.flybywiresim.com/fbw-a32nx/support/reported-issues/#altitude-issues and https://forums.flightsimulator.com/t/oat-of-248-c-at-fl285/478029

**Comment by EisernUnion** [comment]
A thats the climate change what is anyone talking about^^
