### ISSUE TITLE
Aircraft loses control when climbing past FL250

### ISSUE THREAD

**Issue by atoi2008** [flybywiresim/a32nx#6294]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-12-02T01:37:49+00:00",
  "ref": "master",
  "sha": "8dc5bc79bbbd69f4a90c20816c0ea5e22575cbad",
  "actor": "tracernz",
  "event_name": "manual"
}
```

### Describe the bug

When climbing past 25,000 ft MSL, the aircraft will violently pitch down and drop altitude, never to exceed FL250. 

### Expected behavior

Normal climb to cruise altitude

### Steps to reproduce

Attempt to climb past FL250 using autopilot in latest development build.

**Comment by Benjozork** [comment]
Live weather sim issue

**Comment by atoi2008** [comment]
I thought Asobo fixed this a while ago

**Comment by Benjozork** [comment]
As per #server-announcements:

![image](https://user-images.githubusercontent.com/4503241/144628631-d8096782-183a-452a-8958-3d90a3c63d7a.png)

For now, any time you see extreme temperatures on your lower ECAM (you should check for that when getting poor engine or climb performance), it's from the sim, as we do not have our own temperature sensor implementation for now.
