### ISSUE TITLE
Load SIMBRIEF Flight Plan

### ISSUE THREAD

**Issue by CptJohn34** [flybywiresim/a32nx#6295]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-11-21T01:55:55+00:00",
  "ref": "v0.7.3",
  "sha": "e6fb4129367d266aa6f77a979e37f66d458a2575",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

I have now changed to the Stable version because on Setting Up MCDU MENU in the DEVELOPMENT Version I discovered that there is no OPTIONS field shown although there is in the Stable version. The Build Info that I have pasted into the above page is from the Stable version that I am currently using and, which works fine. The DEVELOPMENT version that I was using was the same version as this.

### Expected behavior

I expected to see the OPTIONS field on the MCDU page so that I could navigate to the SIMBRIEF options and enter my user details.

### Steps to reproduce

I removed the DEVELOPMENT version which contains the omission and loaded the STABLE version which works fine.

### Additional info (optional)

I first noticed this following the update to Windows 11, the Massive update to MS FS2020 then the update to the A32NX.

### Discord Username (optional)

CPTJOHN34

**Comment by imperatormatthias** [comment]
simbrief username goes in the EFB now

**Comment by tracernz** [comment]
Doco https://docs.flybywiresim.com/fbw-a32nx/feature-guides/flyPad/settings/#atsuaoc https://docs.flybywiresim.com/fbw-a32nx/feature-guides/simbrief/#flight-planning-with-simbrief
