### ISSUE TITLE
Engine N1 suddenly decrease to 50%. Speed lost. TAT/SAT/ISA increases to more than 250°C !

### ISSUE THREAD

**Issue by Titux69** [flybywiresim/a32nx#6296]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-12-02T01:37:49+00:00",
  "ref": "master",
  "sha": "8dc5bc79bbbd69f4a90c20816c0ea5e22575cbad",
  "actor": "tracernz",
  "event_name": "manual"
}
```

### Describe the bug

During the flight, both engine N1 suddenly decrease to 50%. (The throttle position remain at CLB.)
The speed also decrease (from 290 to 200 or less).
TAT/SAT/ISA temperatures go over 250°C

This behaviour continues during few seconds and returns to normal, before starting over.

![Screen](https://user-images.githubusercontent.com/89352157/144671837-66cf89c9-2330-4b7a-88b1-2729f61eb84d.png)

### Expected behavior

No change on engine/speed/T°C

### Steps to reproduce

1. Take off from LFLL 17R
2. Set alt to FL370
2. Go to ROMAN
3. Go to KURIR
4. Go to MTL

I reproduce the issue twice and it always happen near KURIR/MTL

Flight Plan : LFLL/17R ROMAM2S ROMAM UY23 MTL UT161 DIVKO UN852 VERSO UL129 LUNIK LUNIK2J LEPA/06L

### References (optional)

https://user-images.githubusercontent.com/89352157/144673564-f524dcf1-cde2-44b4-815e-89f245b9da9d.mp4

**Comment by Benjozork** [comment]
This is a simulator issue with live weather and not related to the the aircraft.

Please look through closed github issues and our announcements before opening tickets.

**Comment by flytester** [comment]
Is an Asobo-bug. See youtube contribution from Easyjetsimpilot for a temporary fix: https://www.youtube.com/watch?v=WJxliMgfIJg&t=485s[](https://www.youtube.com/watch?v=WJxliMgfIJg&t=485s)
