### ISSUE TITLE
Cant change fuel qty and sudden engine overload in climb

### ISSUE THREAD

**Issue by Peyto79** [flybywiresim/a32nx#6300]
### Aircraft Version

Development

### Build info

```json
Current Dev Version - Bug not present in stable version
```

### Describe the bug

Before spawning the standard fuel qty is set to 50%. 
After spawning, the plane shows a FOB of 3600 (sometime 4010) kg of fuel. 
I open the fuel page of the sim and the sliders show 19% of fuel on board. 
I move the sliders to 50%. After 2 or 5 seconds the sliders jump by themselfs back to 19%
It‘s not possible to change the fuel qty.

When taking of with 19% of fuel on board the climb phase begins. Somewhere above 20.000 feet, still in climb, the engines „N1“ suddenly jump into the red area above 100% and directly go to idle afterwards. No Master Alert. Autopilot trims down to hold speed.
After a few seconds the airspeed drops from 290knots to 160 knots instantly.
The FF KG/h show a fuel burn of more then 10.000kg per h. Fuel QTY counts down rapidly. Throttly still on idle.
 
After a minute or so the airspeed suddenly jumps back to 290 knots and when I move the throttle levers, the engine goes back to normal climb thrust and it seems everything is ok again.

But after a couple of seconds it start over and over again. 

The rest of the airplane works normal. I was able to land manually without using thrust.

### Expected behavior

As it was a dev version before.

### Steps to reproduce

1) Start cold and dark and try to change fuel qty
2) Takeoff, flying with AP and A/Thr on, wait until bug occours (you hear it when the engines go crazy)
3) Watch Airspeed and fuel burn.

### Additional info (optional)

I flew once with another aircraft with „Unlimited Fuel“ = ON
Next time I flew with the A320NX and still had this option set. I switched it back to OFF.

I dont know if this is somehow linked to the bug I now experience. Maybe the A320NX still „thinks“ that Unlimited Fuel is on, but it isnt. I already switch it On/Off again to see if it somehow fixes the situation.

Maybe I have now a corrupt config file somewhere.
I already tried to switch versions (Stable/Dev) but it didnt fix the bug.

**Comment by Benjozork** [comment]
The MSFS fuel and weight UI is not supported anymore as we announced. I suggest you follow our Discord or social media for updates.

Guide here:

https://docs.flybywiresim.com/fbw-a32nx/feature-guides/loading-fuel-weight/

As for the engine issue, MSFS has been having live weather hiccups recently. Try a static preset until that is resolved. This was also announced via our usual channels.
