### ISSUE TITLE
Distinct buttons for DEP, DEST, ALT 

### ISSUE THREAD

**Issue by sodgaard** [flybywiresim/a32nx#6302]
### Aircraft Version

Development

### Description

On the FlyPad Navigraph Chart page - Add buttons for direct selection of the DEP, DEST, ALT airports so no keyboard input is needed.

In particular in VR that would be an enourmous help.

### Discord Username (optional)

sso#6947

**Comment by sodgaard** [comment]
Airport of departure, destination and alternate. 

/Stephen

**Comment by derl30n** [comment]
Perhaps part of https://github.com/flybywiresim/a32nx/pull/6528

**Comment by tracernz** [comment]
Do we not have this already in flypadOS v3?
