### ISSUE TITLE
aircraft at high altitudes loses power and cannot climb to for example FL390. Had to go to lower altitudes. 

### ISSUE THREAD

**Issue by lasoh45** [flybywiresim/a32nx#6303]
### Aircraft Version

Stable

### Build info

```json
As is
```

### Describe the bug

aircraft cannot climb to FL390 in winds of 40 to 50 knots.  aircraft rocks up and down.
this has happened after the merge of the versions.
engine loses power.

### Expected behavior

climb as directed by pilot

### Steps to reproduce

AP
climb 
steady climb

**Comment by Benjozork** [comment]
There is currently an issue with MSFS live weather causing climb performance problems. Please use a weather preset.

**Comment by lasoh45** [comment]
Thanks Benjamin by the way I have been flying beautiful in your mod stable version ! Just awesome flights !
Thanks !

Javier O Delgado
Certified Business Coach
www.people-too.com
***@***.***
