### ISSUE TITLE
Gross weight should not be displayed before engine start

### ISSUE THREAD

**Issue by BlueberryKing** [flybywiresim/a32nx#6305]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-12-04T18:06:51+00:00",
  "ref": "HEAD",
  "sha": "8dc5bc79bbbd69f4a90c20816c0ea5e22575cbad",
  "actor": "BlueberryKing <22713769+BlueberryKing@users.noreply.github.com>",
  "event_name": "manual"
}
```

### Describe the bug

The gross weight value GW is displayed before engine start.
![image](https://user-images.githubusercontent.com/22713769/144724729-fdd69319-e67f-469b-a9fa-87ac75decd82.png)

### Expected behavior

The indication of GW should only show up once the first engine is started. Before that point, blue dashes should be displayed.

### Steps to reproduce

1. Load up the aircraft
2. Observe GW showing before engine start

### References (optional)

- FBW-31-04

- FCOM:

![image](https://user-images.githubusercontent.com/22713769/144724665-9c8e903d-3654-4c79-9e6c-63e545b3277d.png)

### Discord Username (optional)

BlueberryKing#6641

**Comment by tracernz** [comment]
I think one of the reasons nobody did this yet is because it’s convenient during development. 😆

**Comment by Benjozork** [comment]
Added ref FBW-31-04
