### ISSUE TITLE
FMC Glitches

### ISSUE THREAD

**Issue by runningdavid** [flybywiresim/a32nx#6310]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-12-05T12:05:42+00:00",
  "ref": "master",
  "sha": "8a1e6c977d4f320d267bb7dfbf7d749939b2685f",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

Yesterday I tried out the new development version on my flight from EKCH to LSZH, found a few glitches.

1. FMC seems to be drawing weird arcs when selecting LSZH  ILS14L as approach with whatever sid/stars selected.
2. After changing the approach sid several times the whole ND blackscreened (both Captain and FO side).
3. Upon taking off from EKCH, most waypoints (except the approach ones) disappear from FMC FPLN and also ND. Had to manually enter them back in flight.

### Expected behavior

The aircraft should not exhibit any of those behaviors.

### Steps to reproduce

I used in-game flight planner to set DEP/ARR airports and then set the plan mode to be "High Altitude IFR". Then I simply loaded in and encountered these issues.

I will try flying it for more routes today and see if issue still exists.

I also observe that when using game flight plan seems like the same approach plan is double loaded in FMC (same sids appear twice which results in drawing being weird)

Simbrief flight plans seem to work better. Will continue testing.

Update 12/7/2021:
Haven't encountered the same glitch using simbrief for the past 3 days. It seems to only occur if the FPLN is loaded from game (I suspect it is due to the approach procedure being double loaded).

**Comment by Benjozork** [comment]
> After changing the approach sid several times the whole PFD blackscreened (both Captain and FO side).

Are you sure you don't mean ND?

Also, please provide more screenshots.

**Comment by runningdavid** [comment]
> > After changing the approach sid several times the whole PFD blackscreened (both Captain and FO side).
> 
> Are you sure you don't mean ND?
> 
> Also, please provide more screenshots.

My bad. I'm also using Navigraph Airac 2112 rev.2

**Comment by derl30n** [comment]
Closing since no response from op
