### ISSUE TITLE
NDB frequency not showing correctly on ND

### ISSUE THREAD

**Issue by GetReadyFreddi** [flybywiresim/a32nx#6311]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-12-05T12:05:42+00:00",
  "ref": "master",
  "sha": "8a1e6c977d4f320d267bb7dfbf7d749939b2685f",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

When trying to enter a NBD with a frequency that doesn't end with 0 (307.5 http://www.openaip.net/node/2634152) the ND won't show the correct frequency. Entering a NDB that ends with 0-4 only won't show the last digit (intended with 0 ofc), but entering a NDB that ends with 5-9 will make the last digit glitch into the place of the third
picture: 
![unknown](https://user-images.githubusercontent.com/60944093/144767596-a8fc35cc-d0de-4254-85a9-04c5780be10a.png)

### Expected behavior

the ND should show the correct frequency 
Problem: I couldn't find anything on whether the A320 can show NDBs like the real one at Palma mentioned above

### Steps to reproduce

1. I spawned into the aircraft
2. Powered it up (GPU, batteries, beacon lights, ADIRS)
3. I selected ADF1 & ADF2 on the FCU
4. Put in the frequencies into the RAD NAV page

### Discord Username (optional)

Freddi#9981

**Comment by skyelaird** [comment]
@GetReadyFreddi  Unfortunately your data source is inaccurate and the frequency you chose is out of range for an NDB. NDB frequencies are in the frequency band of 190 to 535 kilohertz (kHz) and have no decimals. Your PA NDB frequency is actually 307 KHz. see https://skyvector.com/airport/LEPA/Palma-De-Mallorca-Airport for a free reference.

This appears to not be a bug unless you can reproduce with whole integers in the 190 - 535 range.

cheers

**Comment by GetReadyFreddi** [comment]
![image](https://user-images.githubusercontent.com/60944093/144770774-902dd0ec-f145-4dbd-b923-e4eca2e2d0bf.png)
![image](https://user-images.githubusercontent.com/60944093/144770783-c61621fb-0591-42a9-9c98-ee062ecd8033.png)

So the first one from ChartFox and the second one from what I guess is Navigraph (2nd picture provided by Cdr_Maverick#6475) are wrong?

![image](https://user-images.githubusercontent.com/60944093/144770902-7fb0fef1-7935-4c4d-8329-453794c05176.png)

In that picture I set 307.5 and the game seems to have "found" it (AIRAC cycle 2111), I sadly didn't test 307.0

**Comment by skyelaird** [comment]
Yeah - maybe from the AIP itself? It's strange that a couple of sources would have the same error unless the source's QA failed.
I've never seen an NDB published with decimals anywhere. Would love to be proved wrong :)

**Comment by GetReadyFreddi** [comment]
I think I found something quite interesting:
There are quite a couple of NBS that end with .5 kHz, but all of those can also be tuned on the next lower whole number.
They are use mostly used on big airports, but why... remains a question.
https://www.pprune.org/questions/72056-ndb-frequency-decimals.html
https://www.pprune.org/questions/69833-ndb-frequencies.html?highlight=ndb

**Comment by skyelaird** [comment]
That's indeed unusual. I was also thinking about the older analog NDB tuning we had(have) with rotary dial selectors - they were always tuning to 3 digits.
I went flying today and went into the A32NX MDCU and selected NDBs by identifier. That works great. I found quite a few PA NDBs but didn't have your coordinates in mind to select the right one (I was also in another hemisphere ;-) )

Be well :)

**Comment by skyelaird** [comment]
Hi again
Just popped over to LEPA. Called up PA NDB and got this listing:

***@***.***

Brgds

**Comment by Benjozork** [comment]
Hi. Please do not respond via email, as we cannot see attachments this way. Use the GitHub website.
