### ISSUE TITLE
FMS: Wrong departure path on the ND

### ISSUE THREAD

**Issue by spiner2000** [flybywiresim/a32nx#6315]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-12-05T22:59:20+00:00",
  "ref": "master",
  "sha": "e7bdd9796930970cbce0267a894bfff052d9f714",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

Wrong departure path. Looks like runway direction was inverted:
LFMN SID:BASI6A
![LFMN-SID-BASI6A fbw32x](https://user-images.githubusercontent.com/1374700/144819159-6b08bfde-9ff8-424d-acf0-93fb1439bbe5.png)
UMKK SID:KRAK3N
![UMKK-KRAK3N](https://user-images.githubusercontent.com/1374700/144819894-a595d313-b9cd-42a8-9b79-a8819dca60af.png)

Navigraph and simulator AIRAC Cycle: 2112 

### Expected behavior

Depatrure path on the ND must be the same as in navigraph charts.

### Steps to reproduce

1. flight plan was loaded from simbrief.
2. Manually  select SID from MCDU.

**Comment by tracernz** [comment]
These leg types are not supported in the initial version of the new FMS, as noted in the release notes. This will change when the current development work finishes up.
