### ISSUE TITLE
EFIS LVAR in Stable Version

### ISSUE THREAD

**Issue by didierma34** [flybywiresim/a32nx#6316]
### Aircraft Version

Stable

### Description

Hi,

Is it possible to introduce all "L:" var of EFIS in Stable Version.
I saw in Dev Version, there is this L: var.
I saw that in the development version, these variables exist.
And I saw that you defined them in the A32NX_Interior_EFIS.xml file (folder / flybywire-aircraft-a320-neo / ModelBehaviorDefs / A32NX / generated); and that this file is called via A32NX_Interior_Includes.xml

### References (optional)

A32NX_Interior_EFIS.xml file (folder /flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/generated)
A32NX_Interior_Includes.xml (folder /flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/interior)

### Discord Username (optional)

🛩 Didierma34_Didier 🛩

**Comment by tracernz** [comment]
The next stable version (0.8) will have these.

**Comment by didierma34** [comment]
Very good !
Thank's !!!!

**Comment by derl30n** [comment]
Closing since this is not an actual request, this will automatically be implemented when releasing the next major stable version.
