### ISSUE TITLE
MSFS Public beta (v1.21.18.0) keeps loading with 320NX

### ISSUE THREAD

**Issue by ErikNL80** [flybywiresim/a32nx#6328]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-12-08T08:12:12+00:00",
  "ref": "master",
  "sha": "873deb80a8fd3d94ba4bedd3d366ae9aa8272c58",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

Have updated to the latest public beta of MSFS and cleared my Community folder. Sim loads OK. After adding the A320NX the sim keeps hanging on 100% when loading a flight.

### Expected behavior

I would expect the A320NX to load properly.

### Steps to reproduce

1. Update to the latest public beta (v1.21.18.0), using the Xbox Insider Hub app for PC
2. Make sure everything is updated and the Comminity folder is empty or renamed
3. Load the sim with a default plane
4. Check if the sim works OK
5. Now install the latest DEV 
6. Check to see if sim completes loading

**Comment by ErikNL80** [comment]
I also tried my entire Community folder without the A320nx and that works as well.

**Comment by andrejetcat** [comment]
same here. endless loading screen with the A32NX :(

**Comment by Guenseli** [comment]
Can confirm, that FBW Bus is not loading with latest 21.18 beta.
Tried several times, other addons are ok.

**Comment by CaptMikeDK** [comment]
Confirmed, and signing out of the Beta program and reinstall gives the same result, you are stuck with the MSFS Public beta (v1.21.18.0)

**Comment by Benjozork** [comment]
We do not support beta releases of the sim. Please use the feedback thread on the MSFS forums.

**Comment by Benjozork** [comment]
Possible fix in

https://github.com/flybywiresim/a32nx/pull/6330
