### ISSUE TITLE
Proposal: One (1) additional loading tip

### ISSUE THREAD

**Issue by etkaar** [flybywiresim/a32nx#6329]
### Aircraft Version

Stable

### Description

# German
"A32NX.LOADING.TIPS.A320NEO_**n**": "Um nur einen einzigen Airbus A380 zu lackieren, wird rund eine Tonne Farbe benötigt."

# English
"A32NX.LOADING.TIPS.A320NEO_**n**": "Around one ton (2204 lb) of paint is needed to paint just one Airbus A380."

### References (optional)

https://aeroreport.de/de/aviation/wie-flugzeuge-lackiert-werden

**Comment by bouveng** [comment]
There is also about 1 ton of air inside the cabin.

**Comment by etkaar** [comment]
> There is also about 1 ton of air inside the cabin.

I hope I don't understand you wrong, but is this sarcasm or another proposal for a loading tip?

**Comment by etkaar** [comment]
> There is also about 1 ton of air inside the cabin.

@bouveng: I hope I don't understand you wrong, but is this sarcasm or another proposal for a loading tip?

**Comment by davidwalschots** [comment]
The tooltip mentions the A380, not the A320. Is this intentional?

**Comment by etkaar** [comment]
> The tooltip mentions the A380, not the A320. Is this intentional?

Yes.

@bouveng: Could you please clarify?

**Comment by davidwalschots** [comment]
I'm going to close this request due to the tooltip text relating to the A380, whereas this repository is for the A320.
