### ISSUE TITLE
Real-life printable METAR 

### ISSUE THREAD

**Issue by DeltaFox09** [flybywiresim/a32nx#6331]
### Aircraft Version

Development

### Description

My idea for the FBW is from the FSLabs Airbus.
There it is possible to print a METAR, TAF, Telex and other stuff from the FMC directly to a seperate printer that you can choose. Maybe like a bill in a supermarket. 

If someone can do that it would be awesome. 

### References (optional)

![7516aa22-cd4d-4648-9a11-424d8d031976](https://user-images.githubusercontent.com/95764487/145241087-6d7994a8-042a-4ce8-9a71-e641653a79de.jpg)
![ac1eafef-ac5e-4500-aad2-168710c09066](https://user-images.githubusercontent.com/95764487/145241094-9902ba7c-6796-494b-8185-bc852b9684a3.jpg)

### Discord Username (optional)

DeltaFox

**Comment by tracernz** [comment]
Already done this before with a small patch to #3467. Didn’t know it had been done before. 😞

**Comment by edouard320** [comment]
That would be awesome to be able to send it to a small thermal printer and print the METAR, TAF and Pre-departure clearances just like at work !
