### ISSUE TITLE
Custom LVARs for External Power no longer working

### ISSUE THREAD

**Issue by zaphod69** [flybywiresim/a32nx#6339]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-12-09T06:34:19+00:00",
  "ref": "master",
  "sha": "db33c928e39ec4554e1247ea5ed145ac1e9bde2f",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

Custom LVARs "A32NX_OVHD_ELEC_EXT_PWR_PB_IS_AVAILABLE" and "A32NX_OVHD_ELEC_EXT_PWR_PB_IS_ON" are no longer working.

Overhead panel is showing External Power AVAIL and ON when pressed but the Custom LVARs are always set to zero.

### Expected behavior

Customer LVARs updated with correct values.

### Steps to reproduce

Start a random flight and check LVAR values.

**Comment by davidwalschots** [comment]
These variables were previously written as LVars, but that was unintentional. This is also why they weren't previously documented in `a320-simvars.md`. I'd recommend using `EXTERNAL POWER AVAILABLE` and `EXTERNAL POWER ON` instead.

**Comment by zaphod69** [comment]
OK but I'm following the https://docs.flybywiresim.com/pilots-corner/a32nx-briefing/a32nx_api/#elec-panel API reference and these Custom LVARs (and many many others) are not in in the a320-simvars.md doc.  If these LVARs are no longer to be used maybe the the API docs need to be updated in line with this.

**Comment by davidwalschots** [comment]
I'm going to tag in @frankkopp as he is primarily working on the [docs repository](https://github.com/flybywiresim/docs).

**Comment by frankkopp** [comment]
@zaphod69 @davidwalschots 
Thanks

As clearly stated in the docs:
![image](https://user-images.githubusercontent.com/16833201/145578621-d5eb37a4-24b5-43e8-9a8c-0e31bf4c1341.png)

As we are still very much in development there will be many changes to come and we will try our best to update the user documentation accordingly. 

I will check this on docs.

**Comment by frankkopp** [comment]
I have removed these from the API docs page. 
Will close this issue.
