### ISSUE TITLE
Add loading tip about air quantity in cabin

### ISSUE THREAD

**Issue by etkaar** [flybywiresim/a32nx#6344]
### Aircraft Version

Stable

### Description

# German
"A32NX.LOADING.TIPS.A320NEO_**n**": "Im Inneren der Kabine eines A320 befindet sich rund eine Tonne Luft."

# English
"A32NX.LOADING.TIPS.A320NEO_**n**": "Around one ton (2204 lb) of air is inside the cabine of an Airbus A320."

### References (optional)

>There is also about 1 ton of air inside the cabin.
>
>_Originally posted by @bouveng in https://github.com/flybywiresim/a32nx/issues/6329#issuecomment-989824253_

**Comment by davidwalschots** [comment]
I think we should avoid creating issues for small things like this, as managing and keeping track of issues also takes effort that could be spent elsewhere. I see that you've recently opened a PR (#6326). Might I suggest you open another PR to add this loading tip?

**Comment by etkaar** [comment]
I thought about that, but I was not sure about the current number (**n**). A PR might conflict with additionally previously added tips. But if it is okay, I'll just create a PR for that and this issue can thus be closed ☺️

**Comment by davidwalschots** [comment]
In general there aren't many loading tips being added at the same time, so the risk of collisions is rather low. I would like to note that I think @bouveng's remark on the one ton of air in the cabin is to be taken with a grain of salt. I'm not sure it's accurate, and it will definitely depend on cabin altitude.

**Comment by etkaar** [comment]
> [...] I would like to note that I think @bouveng's remark on the one ton of air in the cabin is to be taken with a grain of salt. I'm not sure it's accurate, and it will definitely depend on cabin altitude.

Well, I hope he did _not_ made fun of me (even if it looks exactly like that) – otherwise I would need to remove him from the project as we do not tolerate any form of disrespectful behaviour within the contributors community.

**Comment by davidwalschots** [comment]
@etkaar Are you sure you're adding these issues to the right project? You don't have any permissions to remove people from this project 😀.

**Comment by etkaar** [comment]
> @etkaar Are you sure you're adding these issues to the right project? You don't have any permissions to remove people from this project 😀.

Yes. I am member of the _International Institute for Fighting Against Disrespectful Behaviour within the GitHub or any other Open-Source Driven Community_ (IIFADBGCOSDC). So, of course I can remove him from this project in case the investigations show multiple cases of disrespectful behaviour against other contributors.

However – at this time – we don't intend any further investigations in this case.

**Comment by bouveng** [comment]
@etkaar 
@davidwalschots 

> Well, I hope he did _not_ made fun of me (even if it looks exactly like that) 

I did not. The 1 ton of air is true for the B747, and would probably be valid for the A380 as well since it has larger interior than the 747, but not true for the A320 of course.

Here is a first hand source straight from Boeing to support my bold claim. 😎  

![ton-air-src](https://user-images.githubusercontent.com/433429/145775902-4016d5da-02dd-4f17-807b-1df0c92a565e.png)

**Comment by bouveng** [comment]
For the A380 the air inside the cabin, unpressurised would be 2.18 ton, calculated at 1686 m3 of volume inside aircraft.

**Comment by etkaar** [comment]
@bouveng: Thank you 🤗
