### ISSUE TITLE
Release the Experimental version in the installer again. 

### ISSUE THREAD

**Issue by Silvaronn** [flybywiresim/a32nx#6347]
### Aircraft Version

Experimental

### Description

I see the exp version is getting constant updates, release it for us. It is more intuitive and easier than downloading directly from the website. If this is not possible, do you have any plans to release it again? TKS!!

**Comment by Benjozork** [comment]
This is not related to an issue or feature request for the aircraft itself. Please open a discussion (not issue) thread in GitHub or bring this up on discord. Thanks!

**Comment by Silvaronn** [comment]
> This is not related to an issue or feature request for the aircraft itself. Please open a discussion (not issue) thread in GitHub or bring this up on discord. Thanks!

OK.. tks!
