### ISSUE TITLE
[BUG] SRS mode does not engage when TOGA thrust is set

### ISSUE THREAD

**Issue by toffee2000** [flybywiresim/a32nx#636]
**Mod Version**

master

**Describe the bug**

SRS should engage when TOGA is selected with flaps out of UP, whether in flight or on ground. 

**To Reproduce**

In flight:
1. Set flaps 1 or greater. 
2. Push thrust levers to TOGA detent  
3. SRS does not engage. 

On ground:
1. Set flaps 1 or greater.  
2. Push thrust levers to FLEX or TOGA detent  
3. SRS does not engage. 

**Expected behavior**

SRS should engage if TOGA is selected with flaps in all cases, and if TOGA or FLEX is selected on the ground. 

**Actual behavior**

FMA is unchanged. 

**References**

http://www.a320dp.com/A320_DP/nav-autoflight/sys-13.3.16.html

**Additional context**

**Comment by hotshotp** [comment]
it now does work the way described
