### ISSUE TITLE
"UNTITLED" screen in the MCDU

### ISSUE THREAD

**Issue by BergischNRW** [flybywiresim/a32nx#6360]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-12-14T16:05:41+00:00",
  "ref": "master",
  "sha": "a1759973509ae3716264d8b178729c91d5af7593",
  "actor": "BlueberryKing",
  "event_name": "manual"
}
```

### Describe the bug

MCDU shows a screen called "UNTITLED". I´m not sure if that is correct.

### Expected behavior

Probably show something different than "UNTITLED". Maybe "NOTIFICATION".

### Steps to reproduce

On the MCDU:

1. MCDU MENU (button)
2. ATSU
3. ATC MENU
4. CONNECTION
5. NOTIFICATION

### References (optional)

[Screenshot](https://imgur.com/a/XsV0lVf)

### Discord Username (optional)

BergischNRW#1337

**Comment by frankkopp** [comment]
Please visit our Discord support channel to investigate this. There is currently no such issue and this is most likely some conflict on your side.
