### ISSUE TITLE
Not Arrival - "untitled"

### ISSUE THREAD

**Issue by jgau13** [flybywiresim/a32nx#6362]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-11-21T01:55:55+00:00",
  "ref": "v0.7.3",
  "sha": "e6fb4129367d266aa6f77a979e37f66d458a2575",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

this thread was a year ago, but there is no clear answer or solution. Has anyone been able to resolve the promise that arrival information at airports cannot be entered? by pressing "arrival" it says "untitled"

### Expected behavior

FMC A32NX section ARRIVAL - > UNTITLED

### Steps to reproduce

arrival in FMC a32nx

**Comment by frankkopp** [comment]
There is no such issue currently. Please visit our Discord support channel to help investigate why it does not work on your system.
