### ISSUE TITLE
MCDU Webserver on old Devices

### ISSUE THREAD

**Issue by airlinetycoon02** [flybywiresim/a32nx#6365]
### Aircraft Version

Experimental

### Build info

```json
"built": "2021-12-15T02:09:14+00:00",
  "ref": "experimental",
  "sha": "f0e1c20531d50cd7aef50ff1dcdeee1cf2bf02f8",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

The new MCDU on Tablet feature works great on iPhone 12 and a new iPad, but it doesn’t work on my old iPad 3 (iOS 9.3.5). Any idea why? All are in the same WiFi. 

### Expected behavior

Please gtry to find a way to use the MCDU Webserver on old devices like Ipad 2/3

### Steps to reproduce

Tried with all available browsers, no success. Aviaworx for P3d works great on this ipad3. My other ios devices (all newer) can handle the FBW webserver.

**Comment by frankkopp** [comment]
This feature is not even  finished and let alone released yet.
Also it will not be possible to support all browsers available. 
Once we are testing we will generate a list of compatible browsers. 
Please follow the PR for more info: https://github.com/flybywiresim/a32nx/pull/3467
