### ISSUE TITLE
GRD PWR & APU BLEED not working after onblock @ destination

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#6367]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-12-15T08:37:21+00:00",
  "ref": "master",
  "sha": "0b3797e50dce40e025ae534de6965f179edb312f",
  "actor": "Saschl",
  "event_name": "manual"
}
```

### Describe the bug

I was flying trip EDDL-EGLL today with the latest version. 
Ground Power and APU work well at the Departure Airport. 
But after Landing in EGLL both GRD PWR and APU BLEED do not work anymore.

### Expected behavior

APU BLEED and GROUND Power should work as before.

### Steps to reproduce

1. start C&D
2. try GRD POWER and APU BLEED @ DEP Aerodrome (work)
3. after Onblock/landing @ DEST try to select APU BLEED and GRD PWR (when onblock)
4. look @ behavior - not work anymore in my case

**Comment by frankkopp** [comment]
This has been fixed yesterday already. 
Please verify and close this issue.
