### ISSUE TITLE
CTD's after climbing

### ISSUE THREAD

**Issue by 65Manne** [flybywiresim/a32nx#6374]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-12-16T15:31:39+00:00",
  "ref": "master",
  "sha": "ceb8298db8861369aeed76c9582418a3930f86fd",
  "actor": "BlueberryKing",
  "event_name": "manual"
}
```

### Describe the bug

After starting at about 10,000 nm altitude ctd

### Expected behavior

no ctd

### Steps to reproduce

1. cold and dark start
2. configure mcdu and so on
3. Simbrief import fllightplan and manage flightplan
4. Pushback express v 2.2.3
5. start
6. cdt at about 10000

### Discord Username (optional)

manne65

**Comment by BlueberryKing** [comment]
Hello! Does this happen consistently or have you only seen this happening once?

**Comment by derl30n** [comment]
Closing since no response from op
