### ISSUE TITLE
Steering Wheel issue

### ISSUE THREAD

**Issue by hseskar** [flybywiresim/a32nx#6377]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-12-17T20:00:07+00:00",
  "ref": "master",
  "sha": "173105c63369fcdc5fed4884effa398e31072ad3",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

Steering wheel moves very slow. It is impossible to taxi

### Expected behavior

Before last update (yesterday) stearing worked normaly.

### Steps to reproduce

Can not taxi at all. Plane on the ground react very slow when trying to steer.

**Comment by tracernz** [comment]
How slow is "very slow"? The tiller is intentionally changed to be much more realistic. https://docs.flybywiresim.com/fbw-a32nx/feature-guides/nw-tiller/#using-the-tiller-and-rudder

**Comment by Saschl** [comment]
Hi, we recently implemented steering according to the real aircraft. Can you try and follow this guide https://docs.flybywiresim.com/fbw-a32nx/feature-guides/nw-tiller/?h=tiller#what-is-the-tiller ?

Naturally it has become a bit more difficult, but it is more accurate to the real plane now so it will require some adaptions

**Comment by aguther** [comment]
This is not a bug, it's adding realism. This has been confirmed by real-world pilots.

**Comment by hseskar** [comment]
Thank You for very fast response and explanation. Problem was in my auto rudder setting - ON.
Done acording to your explanation. Everything working fine now.
