### ISSUE TITLE
Flight Controls Reversed and not responding properly

### ISSUE THREAD

**Issue by kwstoudt** [flybywiresim/a32nx#6380]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-12-18T13:34:37+00:00",
  "ref": "master",
  "sha": "43fd58494ccc7eb7967f4eaa58a8d23c4f3142b3",
  "actor": "tracernz",
  "event_name": "manual"
}
```

### Describe the bug

After updating to latest development, I noticed on taxi that my rudder and primary flight controls seemed reversed. I went into the settings and ticked the "Reverse Axis" checkbox for them, and they appeared to move correctly with the exception of the rudder, which still seemed reversed.

I then enabled the Nosewheel tiller in the EFB, which seemed to correct the rudder. (I did not change the control options to fully enable it)

When I went to take off, I found my elevator and ailerons still reversed and I could not control the aircraft.

### Expected behavior

Expected to take off as normal and have full control over flight control surfaces.

### Steps to reproduce

1. Update to Development 43fd584
2. Load aircraft
3. Move contorl surfaces
4. Attempt takeoff

### Additional info (optional)

Everything was working properly prior to dev 43fd584.

### Discord Username (optional)

kwstoudt#0622

**Comment by kwstoudt** [comment]
Turns out I missed a setting. Sorry.

**Comment by wimrev** [comment]
Hi, which setting did you miss ? I have the same problem since today but i did not change my settings

**Comment by kwstoudt** [comment]
Assistance > flight control surfaces (might be wrong, im not looking at it right now) > Auto Rudder > Off (turn off all assists in this section)
