### ISSUE TITLE
Dual engine failure during approach phase

### ISSUE THREAD

**Issue by Flyingtrader06** [flybywiresim/a32nx#6381]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-12-18T13:34:37+00:00",
  "ref": "master",
  "sha": "43fd58494ccc7eb7967f4eaa58a8d23c4f3142b3",
  "actor": "tracernz",
  "event_name": "manual"
}
```

### Describe the bug

I've done 5 flights in the last 2 days and systematically on approach phase, a dual engine failure occurs with complete loss of all instruments and sources a power. It happens regardless of airfield of procedure. 

### Expected behavior

Engines should remain functioning unless shut down

### Steps to reproduce

1. Perform any flight until approach phase
2. Before establishing the aircraft on final approach, dual engine failure occurs

### Additional info (optional)

It started occuring around the 16th of December

**Comment by aguther** [comment]
How much fuel did you have?

**Comment by Flyingtrader06** [comment]
More than 3 tons, I doubt this is the reason.

**Comment by Flyingtrader06** [comment]
I am attaching some screenshots of the issue. It just happened again today during all flights so I simply cannot fly anymore. As you can see there was more than enough fuel left and somehow when switching on ignition/start after the dual engine failure,  ECAM shows engines are on idle but there is no power whatsoever. Very strange behaviour. Hope that helps.

![dual engine failure](https://user-images.githubusercontent.com/71842778/146679455-06419fa1-94e8-40f8-bfec-7acf39f51a65.PNG)
![with ignition start](https://user-images.githubusercontent.com/71842778/146679457-e538ccc5-ae48-463f-8e8f-3fcd97a03ef3.PNG)

**Comment by John-UK** [comment]
Your lower ECAM is blank. Possible addon conflict.

**Comment by Flyingtrader06** [comment]
It becomes blank after the dual engine failure... I have no addon except Rex Weather Force and Rex Airport Textures and it was working just fine before with both these add ons.

**Comment by SVitalini** [comment]
Maybe a conflicting button setting that somehow kills your engines? Do you use any peripherals, like saitek panels or similar?

**Comment by gb09f** [comment]
Not saying you ran out of fuel, but how did you fuel the aircraft? Did you refuel using the EFB?

**Comment by Flyingtrader06** [comment]
> Maybe a conflicting button setting that somehow kills your engines? Do you use any peripherals, like saitek panels or similar?

 No I don't, it happens without any particular action from my side so I don't think that's the reason. 

> Not saying you ran out of fuel, but how did you fuel the aircraft? Did you refuel using the EFB? And there's a definite texture problem. The screens either side of your lower ECAM look different to mine. What livery did you have?

Yes I always refuel using EFB. I use the default FBW livery, nothing custom.

**Comment by donstim** [comment]
Can you provide a copy (or a link) to an FDR file for a flight showing this behavior?  https://docs.flybywiresim.com/fbw-a32nx/support/?h=fdr#fdr-files

**Comment by alexg0102** [comment]
Can you show your upper panel?

**Comment by Flyingtrader06** [comment]
> Can you provide a copy (or a link) to an FDR file for a flight showing this behavior? https://docs.flybywiresim.com/fbw-a32nx/support/?h=fdr#fdr-files

Sure, here it is : https://www.swisstransfer.com/d/2ebca25a-07e0-43f0-9487-f98210a57140

> Can you show your upper panel?

Don't have any screenshot available unfortunately... Will take one if it happens again. What's your idea regarding upper panel though?

**Comment by alexg0102** [comment]
> > Can you provide a copy (or a link) to an FDR file for a flight showing this behavior? https://docs.flybywiresim.com/fbw-a32nx/support/?h=fdr#fdr-files
> 
> Sure, here it is : https://www.swisstransfer.com/d/2ebca25a-07e0-43f0-9487-f98210a57140
> 
> > Can you show your upper panel?
> 
> Don't have any screenshot available unfortunately... Will take one if it happens again. What's your idea regarding upper panel though?

I don't know if there is a problem with your upper panel. I just want to see if the Upper Panel says "Fault" somewhere or if something does not match with a "normal" upper panel in the Approach Phase.

**Comment by donstim** [comment]
Thank you for providing the FDR file. At this point, I haven't been able to pinpoint anything out of the ordinary that might cause this. As you said, you have plenty of fuel. We do have issues with the outer to inner fuel tank transfer not taking place when it should, but when your engines failed there was still plenty of fuel in the inner tanks. The need to transfer fuel had not been reached yet.

About all I can offer for now is to try the UTF-8 fix if you haven't done so already (https://docs.flybywiresim.com/fbw-a32nx/support/reported-issues/?h=utf#autopilot-fadec-electrical-systems-not-working-as-intended-utf8-issue) and to try flying without any liveries or other add-ons in your community folder.  Please report back if it continues to occur.

**Comment by Flyingtrader06** [comment]
> Thank you for providing the FDR file. At this point, I haven't been able to pinpoint anything out of the ordinary that might cause this. As you said, you have plenty of fuel. We do have issues with the outer to inner fuel tank transfer not taking place when it should, but when your engines failed there was still plenty of fuel in the inner tanks. The need to transfer fuel had not been reached yet.
> 
> About all I can offer for now is to try the UTF-8 fix if you haven't done so already (https://docs.flybywiresim.com/fbw-a32nx/support/reported-issues/?h=utf#autopilot-fadec-electrical-systems-not-working-as-intended-utf8-issue) and to try flying without any liveries or other add-ons in your community folder. Please report back if it continues to occur.

Thanks a lot for the help. I've applied the changes, will run a flight and let you know :)

**Comment by Flyingtrader06** [comment]
> > Thank you for providing the FDR file. At this point, I haven't been able to pinpoint anything out of the ordinary that might cause this. As you said, you have plenty of fuel. We do have issues with the outer to inner fuel tank transfer not taking place when it should, but when your engines failed there was still plenty of fuel in the inner tanks. The need to transfer fuel had not been reached yet.
> > About all I can offer for now is to try the UTF-8 fix if you haven't done so already (https://docs.flybywiresim.com/fbw-a32nx/support/reported-issues/?h=utf#autopilot-fadec-electrical-systems-not-working-as-intended-utf8-issue) and to try flying without any liveries or other add-ons in your community folder. Please report back if it continues to occur.
> 
> Thanks a lot for the help. I've applied the changes, will run a flight and let you know :)

Happy to report that after applying the above fix and making a few test flights, the issue does not occur anymore. Closing this issue and thanks a lot again for the help, very much appreciated!

**Comment by Flyingtrader06** [comment]
Hi guys, 

Unfortunately I have to reopen this ticket because the exact same issue is back again (I saw another ticket reporting the same issue as well) even after applying the UTF-8 fix. As you can see on the screenshots below, the issue occurs just when establishing the aircraft on the localizer. Tried on multiple flights and it happens systematically while using the latest development version. 

https://gyazo.com/5183eafa59803fd32ef7145e7e94d9d9
https://gyazo.com/337d6e74c0856a045de915a950d7ac8d

Thanks in advance for your support!

**Comment by donstim** [comment]
Please double-check your keybinds. Sometimes these can change for some reason with no input from the user. In particular, check "Instruments and Systems" - "Fuel" and "Engine Instruments." The "Auto Start Engine" under "Engine Instruments" has been known to cause this. And since autostart is a process it goes through, it may not happen immediately after a key action.

**Comment by Flyingtrader06** [comment]
You are right, a shortcut had somehow been assigned on my joystick that caused both flaps to extend and auto start engine... Now it's fixed. Thanks a lot for your help!
