### ISSUE TITLE
[BUG] ALT not shown as armed below active vertical mode

### ISSUE THREAD

**Issue by toffee2000** [flybywiresim/a32nx#639]
**Mod Version**

master

**Describe the bug**

ALT does not display as armed in most vertical modes. 

**To Reproduce**

1. Engage a vertical mode using the FCU. 
2. ALT does not display armed, in blue, below the active mode. 

**Expected behavior**

ALT should arm when a vertical mode is engaged. 

**Actual behavior**

See above. 

**References**

http://www.a320dp.com/A320_DP/nav-autoflight/sys-13.3.17.html

**Comment by lousybyte** [comment]
This seems to be fixed.
