### ISSUE TITLE
FMS

### ISSUE THREAD

**Issue by dementie** [flybywiresim/a32nx#6390]
### Aircraft Version

Development

### Description

input 2nd flight plan ? fms

**Comment by dementie** [comment]
WHEN CAN I ENTER A SECOND FLIGHTPLAN IN A320NX

**Comment by rodrigoluk** [comment]
I'm getting dark screens on 0.7.3 dev.  Any suggestions?

**Comment by tracernz** [comment]
Duplicate #1797
