### ISSUE TITLE
Aircraft keeps turning for few seconds after input is stopped- Separate tiller from rudder DISABLED

### ISSUE THREAD

**Issue by tush0701** [flybywiresim/a32nx#6395]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-12-20T05:05:56+00:00",
  "ref": "master",
  "sha": "a99b560d9965eb0331292679adb12cdea365ad18",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

I have the settings "Separate tiller from rudder inputs" disabled.
This causes the aircraft to turn in a very strange way, and aircraft keeps turning even after the input is removed completely.

Due to this, the input removal has to be timed in such a way that the aircraft points where you want after some time of removal of input.

Issue seems to occur when the tiller is "activated" on higher level of input, and small corrections work fine.

The animation of tiller and rudder moves with the input, but the actual gear does not.

### Expected behavior

Aircraft should stop turning as soon as tiller/rudder combined input is removed.

### Steps to reproduce

1. On EFB, disable "Separate tiller from rudder input"
2. Taxi out, and try turning the aircraft.
3. stop input for turning
4. Aircraft keeps turning

**Comment by Benjozork** [comment]
Hello, do you have "auto rudder" enabled in MSFS assistance settings ? Like all assists, it must be disabled with this aircraft.

**Comment by tush0701** [comment]
Hi,

Please find screenshot for reference, all assists are off, including Auto Rudder. Is it to be done from somewhere else also, in case I missed it?
![image](https://user-images.githubusercontent.com/75409941/146879280-09ca5c94-ac74-4aa4-99f1-027c342d7bfd.png)

**Comment by crotchetycoder** [comment]
Rotating the nose wheel takes a considerable amount of force and is hydraulically actuated. I think the turning speed of the gear is something around 20 degrees/second. So for large deflections, it will take a couple of seconds to straighten itself out again.

This _does_ take a bit of "timing" and anticipation not to over or undershoot your turns. But remember that you're operating a ~60 ton vehicle that simply cannot accelerate or turn on the spot.

**Comment by tush0701** [comment]
> Rotating the nose wheel takes a considerable amount of force and is hydraulically actuated. I think the turning speed of the gear is something around 20 degrees/second. So for large deflections, it will take a couple of seconds to straighten itself out again.
> 
> This _does_ take a bit of "timing" and anticipation not to over or undershoot your turns. But remember that you're operating a ~60 ton vehicle that simply cannot accelerate or turn on the spot.

Totally agreed. :)

Just I feel that in the sim, the aircraft keeps turning with the same intensity, and then suddenly stops turning, rather than gradually stopping the turn. Should that also be the case, as per IRL?

**Comment by crotchetycoder** [comment]
> Just I feel that in the sim, the aircraft keeps turning with the same intensity, and then suddenly stops turning, rather than gradually stopping the turn. Should that also be the case, as per IRL?

I think the gear should straighten itself pretty linearly and not abruptly. To confirm whether your feeling is correct in this case please just check the gear from an outside view, whether it straightens gradually or abruptly after you return the tiller/rudder to center. I'm afraid I don't have the sim at hand at the moment to check myself.

**Comment by crocket63** [comment]
Agreed it will not center itself faster than 20°/s, so that's a feature not a bug :)

**Comment by tush0701** [comment]
Got a hang of it, it gradually decreases, and perfectly so!

Closing the ticket. Thanks!
