### ISSUE TITLE
Flight path line on ND is dotted when loading in. Fuel can not be loaded

### ISSUE THREAD

**Issue by relaval** [flybywiresim/a32nx#6405]
### Installer Version

v.7.3

### Describe the bug

Hello,
Can you help me  please,
I have 2 problems I d'ont undersyand what happends.
1) When i load A320FBW version stable and then I load a flight plan with simBrief for example (LFPG-LSGG) the route is always dotted line.
When I load A320 FBW version development it is impossible to change the fuel quantity, it always stay bloqued at 3.500 Kgs.

Looking forward to hearing from you.
Best regards.
René Laval

 

### Expected behavior

When the flight plan is loaded the route should not be in dotted line.

The fuel quantity can be adjusted.

### Steps to reproduce

1) I load A320FBW version stable
2) I load a flight plan with simBrief for example (LFPG-LSGG)
3) The route is always dotted line.

1)  I load A320 FBW version development
2) It is impossible to change the fuel quantity, it always stay bloqued at 3.500 Kgs.

### References (optional)

![Fuel](https://user-images.githubusercontent.com/92246074/147067578-3f97df59-342f-4a8b-ac5f-6ada3ce96d51.PNG)
![plan de vol](https://user-images.githubusercontent.com/92246074/147067620-cedb0e15-e168-4d65-be73-75940aaa7989.PNG)

**Comment by sqlstatement** [comment]
Hi!

As far as I know the dotted line is normal unless you engage the autopilot and put it into automatic mode.
Also, the fuel has to be changed using the EFB (the tablet on the left of the cockpit) now, the MSFS fuel menu therefore has no effect.

**Comment by derl30n** [comment]
Closing since no response
