### ISSUE TITLE
Bad FMS route for LFTH ILS05 PERU3T via PALME

### ISSUE THREAD

**Issue by JLD95** [flybywiresim/a32nx#6406]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-12-22T08:33:19+00:00",
  "ref": "master",
  "sha": "c29987db65566a0b3098abc2f80b7710a2d73864",
  "actor": "crocket63",
  "event_name": "manual"
}
```

### Describe the bug

Bad FMS route for LFTH ILS05 PERU3T via PALME: AMFOU, GILON, CUERS TLN are not in FPL

### Expected behavior

PERU3T arrival shall route on AMFOU, GILON, CUERS TLN

### Steps to reproduce

select arrival on LFTH (I mad a flight from LFPO)
select ILS05
select PERUS 3T arrival
select via PALME

### References (optional)

![Presse-papiers-1](https://user-images.githubusercontent.com/5894146/147221180-2a4abc98-ac80-490c-955e-6181a2a2cefe.jpg)
![2021-12-23](https://user-images.githubusercontent.com/5894146/147221195-0862fd83-2607-467f-8422-5d699d265cf4.jpg)
![2021-12-232](https://user-images.githubusercontent.com/5894146/147221199-e152087b-0768-4d59-84a6-de1db4f1aea4.jpg)

**Comment by derl30n** [comment]
Can you retest to see if it is still present with the master aka development version of today?

**Comment by JLD95** [comment]
Hi,
works for me, thank

![2022-04-10](https://user-images.githubusercontent.com/5894146/162605303-18fead7d-dc74-49e3-ab0b-af17cc64e406.jpg)
s
