### ISSUE TITLE
0.0 batteries voltage and black all displays

### ISSUE THREAD

**Issue by Windozer** [flybywiresim/a32nx#6413]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-11-21T01:55:55+00:00",
  "ref": "v0.7.3",
  "sha": "e6fb4129367d266aa6f77a979e37f66d458a2575",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

The battery voltage is 0.0v. All flight, navigation displays, even radio transmitters do not work after connecting power from a ground source, APU, engine generators

### Expected behavior

I expected that I wouldn't have any bugs and I expected that I could just take off the plane and take off.

### Steps to reproduce

1. Launch MSFS 2020
2. Select A32NX FlyByWire aircraft
3. Start flight
4. Get into the cockpit and connect any power source

### Discord Username (optional)

Nyan+#8782

**Comment by Windozer** [comment]
P.S: Option "Beta: Use UTF-8 for worldwide language support" is enabled and my username don't have non-english symbols

**Comment by kiwi2021** [comment]
Have you tried testing the aircraft without anything else in your 'Community' folder to eradicate the potential of mod conflicts, then performing a fresh reinstall of the aircraft?

**Comment by Windozer** [comment]
Yes, i deleted all from Community folder and reinstall flybywire aircraft, my MSFS2020 not have any mods

**Comment by kiwi2021** [comment]
Have you performed a clean install using the following steps: https://docs.flybywiresim.com/fbw-a32nx/installation/#clean-install-steps

**Comment by Windozer** [comment]
i performed a clean install, nothing changed

**Comment by kiwi2021** [comment]
Can you install dev version and try with that.

**Comment by Windozer** [comment]
I installed DEV version, i can't use any power source, it very bugged

**Comment by kiwi2021** [comment]
What is your sim version, can you provide a screenshot please.

**Comment by Windozer** [comment]
how to check that?

**Comment by kiwi2021** [comment]
![image](https://user-images.githubusercontent.com/50173847/147417486-5bb6a9f2-3e6b-46d8-a83a-31d0fa5881d9.png)

**Comment by Windozer** [comment]
My MSFS2020 version is 1.12.13.0

**Comment by kiwi2021** [comment]
Can you send a screenshot the same as the example shown please.

**Comment by Windozer** [comment]
Now i can't, i installing a new MSFS2020 from Xbox

**Comment by Windozer** [comment]
If flybywire will not works in new MSFS2020, i send a screenshot

**Comment by Windozer** [comment]
Wow, after update all features are working!
