### ISSUE TITLE
Did not capture Localizer

### ISSUE THREAD

**Issue by minkyusimmer** [flybywiresim/a32nx#6414]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-12-25T19:32:18+00:00",
  "ref": "master",
  "sha": "ed16b41706c8f8a97144b3f22c3a0a28eb9eb327",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

The aircraft did not intercept the localizer even when the correct frequency was there at San Jose International KSJC.

### Expected behavior

The LOC is captured and lines up with runway.

### Steps to reproduce

1. Takeoff Monterey
2. Direct KLIDE
3. Intercept KSJC Localizer 30L (110.90)

### Discord Username (optional)

Minkyu Koo #7946

**Comment by aguther** [comment]
Cannot reproduce:
![Microsoft Flight Simulator Screenshot 2021 12 26 - 09 20 32 28](https://user-images.githubusercontent.com/6629914/147402898-29c0827f-fcae-4276-9378-ad2919301309.png)
![Microsoft Flight Simulator Screenshot 2021 12 26 - 09 20 39 88](https://user-images.githubusercontent.com/6629914/147402902-d549b12a-8519-4728-bdd3-af8dc9db5d90.png)
![Microsoft Flight Simulator Screenshot 2021 12 26 - 09 21 34 73](https://user-images.githubusercontent.com/6629914/147402903-1b0a4e49-e781-430c-a78c-cad16b7f0d67.png)

**Comment by minkyusimmer** [comment]
> Cannot reproduce: ![Microsoft Flight Simulator Screenshot 2021 12 26 - 09 20 32 28](https://user-images.githubusercontent.com/6629914/147402898-29c0827f-fcae-4276-9378-ad2919301309.png) ![Microsoft Flight Simulator Screenshot 2021 12 26 - 09 20 39 88](https://user-images.githubusercontent.com/6629914/147402902-d549b12a-8519-4728-bdd3-af8dc9db5d90.png) ![Microsoft Flight Simulator Screenshot 2021 12 26 - 09 21 34 73](https://user-images.githubusercontent.com/6629914/147402903-1b0a4e49-e781-430c-a78c-cad16b7f0d67.png)

I'm using the [freeware KSJC](https://flightsim.to/file/5979/norman-y-mineta-san-jose-international-airport-ksjc). Would that have anything to do with the LOC Capture?

**Comment by aguther** [comment]
You initially provided very few information, so how should I know?

The scenery of course plays a big role. ILS could be wrongly modeled, maybe the reception range is smaller.

Did you see the LOC signal or identifier when switching on LS button or not?

It would be helpful to get more info but right now I highly doubt that it’s an issue of the A32NX.

**Comment by minkyusimmer** [comment]
> You initially provided very few information, so how should I know?
> 
> The scenery of course plays a big role. ILS could be wrongly modeled, maybe the reception range is smaller.
> 
> Did you see the LOC signal or identifier when switching on LS button or not?
> 
> It would be helpful to get more info but right now I highly doubt that it’s an issue of the A32NX.

Today I attempted a flight from KMRY-KSJC. The airplane did not capture the loc or the g/s so I tried going to Moffet(KNUQ) but it did not capture Moffet's ILS either. Do you recommend reinstalling the aircraft?

**Comment by aguther** [comment]
Can you maybe post screenshots of your situation? What did you engage, what showed the PFD, …

**Comment by minkyusimmer** [comment]
> Can you maybe post screenshots of your situation? What did you engage, what showed the PFD, …

Would sending my work file work? I already reinstalled the FBW A32NX.

**Comment by minkyusimmer** [comment]
> Can you maybe post screenshots of your situation? What did you engage, what showed the PFD, …

Can I send a video?

**Comment by aguther** [comment]
Sure, you can just upload it to GitHub.

**Comment by minkyusimmer** [comment]
> Sure, you can just upload it to GitHub.

So I just tested it out today again with the reinstalled aircraft. The LOC did capture but it said that the aircraft was lined up but it was slanted. I tested KSFO's ILS28R approach and it worked perfectly. Can you test with the freeware KSJC and see if there is a ILS problem?

**Comment by aguther** [comment]
What about you try it again and provide a video of the situation?

You can upload the video to either GitHub, YouTube or something like https://streamable.com/.

**Comment by aguther** [comment]
This airport has serious issues with the ILS. Seems it was not updated for changes in magnetic variation. The bearing of the ILS should be 306°. No issues capturing the ILS though.

![image](https://user-images.githubusercontent.com/6629914/147594682-933ec31c-8fed-44e2-bb52-87d7d1e379ca.png)
![Microsoft Flight Simulator Screenshot 2021 12 28 - 19 11 02 17](https://user-images.githubusercontent.com/6629914/147594787-522f3e7a-566c-441f-8dfd-7bec7fcdb300.png)
![Microsoft Flight Simulator Screenshot 2021 12 28 - 19 10 40 39](https://user-images.githubusercontent.com/6629914/147594816-e58f86ed-ad45-46d2-9835-7411877ba23b.png)
![Microsoft Flight Simulator Screenshot 2021 12 28 - 19 11 02 17](https://user-images.githubusercontent.com/6629914/147594820-365e5f0b-74de-4242-84ab-005a7da1fca4.png)

**Comment by MinkyuSimulations** [comment]
> This airport has serious issues with the ILS. Seems it was not updated for changes in magnetic variation. The bearing of the ILS should be 306°. No issues capturing the ILS though.
Yes this is exactly what I saw when I flew yesterday. I will contact the developer.

**Comment by MinkyuSimulations** [comment]
> This airport has serious issues with the ILS. Seems it was not updated for changes in magnetic variation. The bearing of the ILS should be 306°. No issues capturing the ILS though.
> 
This is exactly what I experience when flying yesterday. I will contact the developer.

P.S. This is the same person as minkyusimmer, just on a different account.

**Comment by MinkyuSimulations** [comment]
> ![image](https://user-images.githubusercontent.com/6629914/147594682-933ec31c-8fed-44e2-bb52-87d7d1e379ca.png) 
>
Do you know if I can manually adjust the bearing?
