### ISSUE TITLE
a320 DEV loses all electrical after a few minutes of taxiing after COLD start 

### ISSUE THREAD

**Issue by emailrobert** [flybywiresim/a32nx#6415]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-11-21T01:55:55+00:00",
  "ref": "v0.7.3",
  "sha": "e6fb4129367d266aa6f77a979e37f66d458a2575",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

See this video [https://youtu.be/g6vki6wsHSc] that shows exactly what is happening. I do a by the book cold start checklist for the a320 and after a few minutes the cockpit goes dead and loses all electrical. You can see the generators lose connection on the ELEC screen just before it goes dark. There is nothing else in my community folder. This is an unlisted video so only folks with this link can see it. 

### Expected behavior

Like the stable version, which works great, I would expect the cold start checklist to provide a fly-ready aircraft. 

### Steps to reproduce

Load the DEV version of the a320 FlyByWire aircraft into Community Folder
Follow the standard checklist to cold start the a320
Taxi to the runway
Aircraft loses electrical after a few minutes of taxiing

### References (optional)

https://youtu.be/g6vki6wsHSc

### Discord Username (optional)

LordPresidente

**Comment by kiwi2021** [comment]
Hi, could I ask what version the sim is?

**Comment by emailrobert** [comment]
MSFS version 1.21.13.0

**Comment by emailrobert** [comment]
> MSFS version 1.21.13.0



> Hi, could I ask what version the sim is?

MSFS version 1.21.13.0

**Comment by kiwi2021** [comment]
Could you try this please?

### FlyByWire A32NX | UTF-8

In rare cases the Autopilot, FADEC and electrical systems may not start or behave erratically. This is in part due to UTF-8 language support beta not enabled on your machine.

Solution:

1. Open Windows Control Panel -> Region
2. Go to the Administrative tab and click Change system locale
3. Make sure the check mark next to Beta: Use UTF-8 for worldwide language support is selected
4. Click OK and restart your computer

**Comment by emailrobert** [comment]
> Could you try this please?
> 
> ### FlyByWire A32NX | UTF-8
> In rare cases the Autopilot, FADEC and electrical systems may not start or behave erratically. This is in part due to UTF-8 language support beta not enabled on your machine.
> 
> Solution:
> 
> 1. Open Windows Control Panel -> Region
> 2. Go to the Administrative tab and click Change system locale
> 3. Make sure the check mark next to Beta: Use UTF-8 for worldwide language support is selected
> 4. Click OK and restart your computer

Same result. Followed these instructions, the check mark was NOT checked, so I checked it, restarted and followed the same procedure in the video with the same result. Aircraft lost power during taxi.

**Comment by frankkopp** [comment]
@emailrobert what throttle and controller do you use?
Can you do the same test please while these are unplugged using only the mouse in the UI cockpit?
You can come to our discord and ping me if you want: Cdr_Maverick#6475

**Comment by emailrobert** [comment]
So everything I've tried so far...

1) Made sure I had fuel in ALL tanks and all fuel pumps were on
2) Made sure I didn't have any key/joystick bindings that would kill the power. Someone noticed that it seemed to turn off after I fully ruddered the aircraft to straighten up.

**Comment by frankkopp** [comment]
> So everything I've tried so far...
> 
>     1. Made sure I had fuel in ALL tanks and all fuel pumps were on
> 
>     2. Made sure I didn't have any key/joystick bindings that would kill the power. Someone noticed that it seemed to turn off after I fully ruddered the aircraft to straighten up.

Which controller for throttle and stick do you have?
Could you test with them unplugged?

**Comment by emailrobert** [comment]
> > So everything I've tried so far...
> > ```
> > 1. Made sure I had fuel in ALL tanks and all fuel pumps were on
> > 
> > 2. Made sure I didn't have any key/joystick bindings that would kill the power. Someone noticed that it seemed to turn off after I fully ruddered the aircraft to straighten up.
> > ```
> 
> Which controller for throttle and stick do you have? Could you test with them unplugged?

Very interesting. With the controller unplugged, it did not lose power for two complete laps around the taxiway and runway (never lost power). Also, when I first change from stable to dev or vice versa, with the throttle plugged it (Thrustmaster TFLIGHT HOTAS ONE) it takes 3-4 minutes or longer for the flight to load (the first time), but then only takes a few seconds after that first time. But with the throttle unplugged, it only took 5 seconds to load the first time after I switched back to DEV mode.

**Comment by frankkopp** [comment]
> 

That confirms my suspicion.
Try checking your USB devices HUBs and controllers for USB Powersave and turn it OFF). This might be the cause. (https://www.youtube.com/watch?v=3IaQb0OAfbQ)
Or something else on you PC interferes with your controllers. 

Regarding the loading time - after an update of the ad-on (normal update or change of version) MSFS needs to compile a few files (called WASM files). This compilation takes a while. It does this only once after an update. Each subsequent start should be much faster. 

This is the compilation and you see how long it takes on my machine:
![image](https://user-images.githubusercontent.com/16833201/147423751-a39a64b5-46b3-406e-bb96-97ebd57c8204.png)

**Comment by emailrobert** [comment]
PROBLEM SOLVED: I had set the X key on the joystick to brakes and must have missed that it was also bound to autostart. So when I hit the brakes on the taxiway to slow down, it triggered the autostart in the DEV (which Im told isnt implemented) and within 30 seconds shut down the aircraft. I removed the X from autostart binding and did two whole laps around the airfield.
