### ISSUE TITLE
Long trip makes Flight Simulator drop FPS (my case from 60 to 7)

### ISSUE THREAD

**Issue by G3NSVRV** [flybywiresim/a32nx#6419]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-11-21T01:55:55+00:00",
  "ref": "v0.7.3",
  "sha": "e6fb4129367d266aa6f77a979e37f66d458a2575",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

yesterday I took a long trip, 9 hours from point A to B. I started the flight, went to sleep, and this morning when I got back everything was running at 7 FPS, normally is 60 FPS...

I'm posting this here because **I resolved by reloading the aircraft** (workaround), idk if it is an issue with this aircraft because I'm using the FBW A32NX 0.73 or it is an issue how the game handles the aircraft models...

### Expected behavior

not having FPS drops after many hours of continue flight

### Steps to reproduce

1. Setup the flight for 9 hours trip
2. Wait

### Discord Username (optional)

G3NSVRV#7693

**Comment by Benjozork** [comment]
Without seeing the MSFS fps counter over time there is nothing we can do about this.

**Comment by czarnetz** [comment]
Hi, i have the same issue - how you have reload the aircraft to solve this problem?

**Comment by G3NSVRV** [comment]
> Hi, i have the same issue - how you have reload the aircraft to solve this problem?

using the developer menu > window > aircraft selector > load

**Comment by Venorcis** [comment]
Interestingly I had the same issue just now after roughly 1.5 hours of flying, also down to ~7FPS.

**Comment by Samuel-78** [comment]
This is a FS issue, not concerned to FBW. It also happens with many other aircrafts. In my case, was solved after last Sim Update, but I know there is thread with users still reporting FPS drops issues.

**Comment by Daboj1337** [comment]
Same issue here. After 2 HRS flight my frames are dropping as hell even with my 3090

**Comment by Benjozork** [comment]
Guys - we need screenshots over time or videos of the MSFS FPS counter in order to see if this is related to the aircraft. Otherwise we cannot do anything about this.

**Comment by Mmucha83** [comment]
Delete/uninstall "Your Controls" mod from Community folder. Even when it's not running it can decrease FPS, in my case down to 2-3 fps after 6h-flights.
In my case uninstalling helped.

**Comment by G3NSVRV** [comment]
> Delete/uninstall "Your Controls" mod from Community folder. Even when it's not running it can decrease FPS, in my case down to 2-3 fps after 6h-flights. In my case uninstalling helped.

i dont have that and still got the issue, running just fs2020 vanilla with fbw a32nx

**Comment by Mmucha83** [comment]
try also to install the beta-patch, on Steam it's named "sim_update_vii_update - Sim Update VII".

**Comment by tracernz** [comment]
Duplicate #5650.
