### ISSUE TITLE
Anti-icing does not work unless engines are running

### ISSUE THREAD

**Issue by CrossHyparu** [flybywiresim/a32nx#6420]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-05T23:03:06+00:00",
  "ref": "v0.6.1",
  "sha": "4a1cccc90ab3997109e394402ab9b41a80fbf325",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

The probe/window heat, engine anti-icing, and wing anti-icing do not work unless the engines are turned on. Running the systems with only electrical or APU power do not remove the icing

### Expected behavior

Anti-icing systems to work with electrical power as normal for the A320

### Steps to reproduce

Switch the systems on using only external power or the APU

**Comment by Benjozork** [comment]
You're using an unsupported version from 7 months ago, you need to update.

**Comment by aguther** [comment]
Beside that: wing and engine anti-ice system is using hot air and is not electrical.
