### ISSUE TITLE
Coordinates north of 8959.9N/0000.0E cause the sim to freeze

### ISSUE THREAD

**Issue by Gamer-0999** [flybywiresim/a32nx#6421]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-12-25T19:32:18+00:00",
  "ref": "master",
  "sha": "ed16b41706c8f8a97144b3f22c3a0a28eb9eb327",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

1. when I try to enter coordinates north of 8959.9N/0000.0E into the MCDU (e.g. 9000.0N/0000.0E), the simulation freezes. Or the MCDU gives me the feedback that it is an incorrect format.

It freezes with stored waypoints, but also with direct input (see video).

2. if I fly from the south to the waypoint NOPOL, the sim freezes as soon as I pass the coordinates 8959.9N/0000.0E (see screenshot).

3. when I enter the coordinates 8950.0N/0000.0E, the entry is automatically changed to 8949.10N/00000.0E (but maybe this is another bug)

https://user-images.githubusercontent.com/96742598/147495337-32ad208a-6ccd-46b9-8f2b-0ef01923612a.mp4
![Northpole](https://user-images.githubusercontent.com/96742598/147495606-a56da065-c48c-441a-ae2c-d3a16d8b3f19.PNG)

### Expected behavior

1. 
- Entering the coordinates 9000.0N/0000.0E should have the same effect as entering the waypoint NOPOL.

- The sim should not freeze when entering the coordinates 9000.0N/0000.0E.

- the MCDU should accept e.g. the coordinates 8995.0N/0000.0E without error message.

2. the simulator should not freeze when flying north of 8959.9N/0000.0E.

3. the coordinates 8950.0N/0000.0E should not be changed automatically, but should be kept exactly as entered.

### Steps to reproduce

FIRST PROBLEM:
1. enter the departure and arrival airports
2. enter the coordinates 9000.0N/0000.0E
3. insert the coordinates after the airport of departure.
4. -> simulator freezes

SECOND PROBLEM:
1. spawn near the north pole
2. enter the waypoint nopol into the mcdu
3. fly towards the waypoint
4. -> simulator freezes exactly at coordinates 8959.9N/0000.0E

THIRD PROBLEM:
1. enter the coordinates 8950.0N/0000.0E as stored waypoint.
2. call up the stored waypoints
3. -> coordinates have been changed to 8949.10N/00000.0E

### Discord Username (optional)

Gamer_0999

**Comment by tracernz** [comment]
True south pole does the same. BlueberryKing reported it does not happen without the ND, and I verified PROG BRG/DIST handles it just fine, so it seems to be an issue with the ND.

**Comment by tracernz** [comment]
Keep in mind also that the A320 is not permitted to fly beyond north of 70°N and south of 60°S, per the limitations section in the FCOM.

**Comment by juliansebline** [comment]
I cannot reproduce theses bugs. To me, it's fixed.

**Comment by tracernz** [comment]
Yeah, not an issue really anyway as the aircraft isn't certified to fly at these latitudes.
