### ISSUE TITLE
Extreme FPS drop when ATC sends you on VFR flight plan

### ISSUE THREAD

**Issue by Gamer-0999** [flybywiresim/a32nx#6422]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-12-25T19:32:18+00:00",
  "ref": "master",
  "sha": "ed16b41706c8f8a97144b3f22c3a0a28eb9eb327",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

If you don't answer ATC calls and it switches you to vfr after a while, there is an extreme fps drop at that point. (see video)

The FPS drop can be fixed by requesting the flight plan to IFR again.

https://user-images.githubusercontent.com/96742598/147497696-50430ab9-b257-467d-85a6-d377b4dbbc02.mp4

### Expected behavior

After the switch to VFR, the simulator should have the same FPS as an IFR flight.

### Steps to reproduce

1. create flight plan ingame
2. do not reply to the ATC on the assigned flightlevels after take-off
3. wait until the ATC switches you to VFR
4. -> FPS drop

### Discord Username (optional)

Gamer_0999

**Comment by Benjozork** [comment]
the `Manipulators` thread we see causing the drop in your video is MSFS internal and therefore this is not related to the aircraft
