### ISSUE TITLE
Backlight bleed CSS is applied twice in both the PFD and ND

### ISSUE THREAD

**Issue by ssewell** [flybywiresim/a32nx#6425]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-12-23T13:15:43+00:00",
  "ref": "master",
  "sha": "89b5be90e4b3e533ad55af2e389288948498ea4a",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

The BacklightBleed class is being to the rendered in the PFD (and ND) twice since BacklightBleed is applied to a div in both displayUnit.tsx and the index.tsx for the actual instruments.

### Expected behavior

Backlight bleed class is only applied once to the PFD and ND, each.

### Steps to reproduce

View the PFD or ND in the Coherent GT debugger, the backlight bleed is applied to a div within the MSFS_REACT_MOUNT div, and then again within a child div (see reference below)

### References (optional)

![image](https://user-images.githubusercontent.com/2242776/147533190-15170fb7-bd3c-4e6b-9c9e-eefdb4fa8970.png)

### Additional info (optional)

The backlightbleed should probably be removed from the PFD and ND instrument's index.tsx file, since they gain this effect through use of displayUnit.tsx.

### Discord Username (optional)

AntennaRex#9906

**Comment by 2hwk** [comment]
Well spotted, this will be cleaned up shortly.
