### ISSUE TITLE
Toe brake "stuck" and won't brake after first usage

### ISSUE THREAD

**Issue by KemalOues** [flybywiresim/a32nx#6426]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-12-25T19:32:18+00:00",
  "ref": "master",
  "sha": "ed16b41706c8f8a97144b3f22c3a0a28eb9eb327",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

After starting the a/c from cold and dark and taxing to the rwy, the brake pedals won't response anymore after the first usage and I am unable to brake again. Have to use the parking brake to stop during taxing.

### Expected behavior

Brake should work every time

### Steps to reproduce

I've tried different axis, axis in fsuipc and in game and other a/c.
Problem is only with the fbw mod and no other a/c.

### Additional info (optional)

I've tried different axis, axis in fsuipc and in game and other a/c.
Problem is only with the fbw mod and no other a/c.

### Discord Username (optional)

COL001

**Comment by derl30n** [comment]
Is the issue still persistent?

**Comment by KemalOues** [comment]
I've to test it again, but it seems to be fixed after last SU

**Comment by derl30n** [comment]
Closing since issue seems resolved, if it appears again re-open or open a new issue.
