### ISSUE TITLE
Incorrect behavior for Cockpit door video button on overhead panel

### ISSUE THREAD

**Issue by xZreai** [flybywiresim/a32nx#6428]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-12-20T05:05:56+00:00",
  "ref": "master",
  "sha": "a99b560d9965eb0331292679adb12cdea365ad18",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

Cockpit door video when activated using VIDEO button on lower panel, on the lower ECAM display unit does not turn off when COCKPIT DOOR VIDEO switch on overhead panel is turned off.  The VIDEO button on the lower panel near the door switch works as intended. This is just a minor bug that I had noticed.

A video to the same was posted in ATA-24-electrical: https://discord.com/channels/738864299392630914/748248319548981379/923314834362220605

### Expected behavior

Cockpit door video when activated using the VIDEO button on the pedestal on the lower ECAM display unit should turn off when COCKPIT DOOR VIDEO switch on the overhead panel is turned off. 

### Steps to reproduce

1. Turn on aircraft using either APU or External Power
2. Turn on cockpit door video on the lower ECAM using the VIDEO button on the lower pedestal on the CAPT side
3. Turn off COCKPIT DOOR VIDEO switch on overhead panel.

### References (optional)

https://discord.com/channels/738864299392630914/748248319548981379/923314834362220605

### Discord Username (optional)

Cleon#5802

**Comment by 2hwk** [comment]
The reference provided is insufficient, a pointer to an airbus service manual or similar would be needed to implement this correctly.

**Comment by xZreai** [comment]
> The reference provided is insufficient, a pointer to an airbus service manual or similar would be needed to implement this correctly.

Had a brief look through the A320 family ESLD, didn't find COCKPIT DOOR VIDEO or anything along the lines properly documented, someone on the team might have an updated version or some other document with the correct logic for this. 

However would it not make more sense to assume that the cockpit door video should turn off when the button is pressed on the overhead?

**Comment by FlyingCarpet7** [comment]
![4FAEDD42-3E9A-4823-9DF3-D408E1ACF7AF](https://user-images.githubusercontent.com/71129337/147774279-48855c48-8186-4e5a-b71b-d01519b3bb82.jpeg)
We can assume that the system will not work if the “master” button on the overhead panel is pressed and the system is de-energized.

The buttons on the pedestal will be remodelled with the new model I also assume 
![1E8587CC-C495-4FDC-B76B-A3A220040B56](https://user-images.githubusercontent.com/71129337/147774559-79aeb956-aea3-4e47-9050-6dd1e8d27014.jpeg)
