### ISSUE TITLE
[BUG] SRS does not maintain V2+10

### ISSUE THREAD

**Issue by toffee2000** [flybywiresim/a32nx#643]
**Mod Version**

master

**Describe the bug**

SRS should command a pitch that maintains V2+10 on takeoff, or the speed when TOGA was set on go around. 

**To Reproduce**

1. Set TOGA/FLEX thrust for takeoff. 
2. SRS commands acceleration to a speed far above V2+10. 

**Expected behavior**

Pitch bar should command V2+10. 

**Actual behavior**

See above. 

**References**

http://www.a320dp.com/A320_DP/nav-autoflight/sys-13.3.16.html

**Additional context**

Until the go around SRS issue is fixed, SRS won't work for go around. It should work in that case too.

**Comment by becas22** [comment]
What pitch does SRS command?

**Comment by toffee2000** [comment]
15 or so, but it should not target pitch directly, instead pitch for speed.

**Comment by becas22** [comment]
It aims for V2+10 up until maximum of 18º.

**Comment by veikkos** [comment]
Working on this.
