### ISSUE TITLE
Autoswitch between tiller and rudder for those with one axis

### ISSUE THREAD

**Issue by winkerbie** [flybywiresim/a32nx#6431]
### Aircraft Version

Development

### Description

I only have one Z axis on my joystick for rudder input. I know the recent feature update allows separation of the tiller and rudder, but I cant do this due to limited axes. 

A useful feature might be that whilst on the ground with speed <30kts the rudder inputs get automatically diverted to the tiller, but on take-off (i.e. throttles set at FLX/MCT or TOGA) the inputs feed the rudder with the reduced nose-wheel steering like the real aircraft. 

I suggest considering both the speed and throttle setting variables because on landing we would ideally need rudder steering to maintain the centre line but the throttle would be idle/reverse.

Cheers

**Comment by frankkopp** [comment]
This is basically what the default MSFS rudder does - you can use rudder and tiller with one axis. 
What you describe would not make much difference. 
The idea of the separation of tiller and rudder is specifically targeted to when you have two axis so you can use them independently. 
For separation any axis would do btw. - I use the little slider on my stick for tiller, the twist for rudder.

**Comment by frankkopp** [comment]
As this has been addressed I will close this.
