### ISSUE TITLE
MCDU Server Page not loading on external device

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#6433]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-12-29T09:33:08+00:00",
  "ref": "master",
  "sha": "d30717c1a6e2ae918f42a7bcdb9cff6f05a54a66",
  "actor": "tyler58546",
  "event_name": "manual"
}
```

### Describe the bug

the new feature is awesome but only works on the Sim-device, not on external device in the network.

The Adress given by the "Power Shell" program for external devices do not load. tried on Android, Apple and Windows devices, but the page is not loading.

### Expected behavior

page should load on external device with given (IP-) adress

### Steps to reproduce

1. Start MSFS
2. start MCDU server
3. Try to connect from a external device via the given IP adress
4. see page with program-given-adress do not load/stops loading

**Comment by DavidEGTE** [comment]
did you open port via windows firewall? 8125 seems to be the default one

**Comment by andrejetcat** [comment]
My fault, I do not know that, thank you for the fast reply! :)

**Comment by andrejetcat** [comment]
BUT, if i open the port, now MCDU loads and appears on my external device. But without any content - MCDU is back. and no button clickable :(

**Comment by DavidEGTE** [comment]
I still haven't tried it yet as I'm doing a turnaround at LEIB, but if the issue persist I think one of the devs will shortly be available to see what is your issue

**Comment by DavidEGTE** [comment]
![383B94B9-B5CD-48E5-AE50-B795E1F351D7](https://user-images.githubusercontent.com/19428125/147662023-3a4821db-98b5-41e1-b697-4457e2355e00.jpeg)

all good from my side

**Comment by andrejetcat** [comment]
no matter what I do, evertime only the MCDU empty MCDU is shown on my device, regardless on what device and browser I try it. :(

**Comment by VohnMclane** [comment]
mine is fine also. did have a ctd when changing simbrief route

**Comment by andrejetcat** [comment]
so, now it works, BUT only if i turn off the Firewall on my private network in Windows. It do not work with the "open ports" method. :(

**Comment by DavidEGTE** [comment]
are you sure you added the port on inbound rules @andrejetcat  ?

**Comment by andrejetcat** [comment]
yes, defentely! I try it several times based on the manual on the flybywire site. inbound/outbound and both, do not work. Only picture of the MCDU is shown with the inbound rules. If i turn of the "private network" firewall, it works perfect, but not with the port-method. :(

**Comment by tyler58546** [comment]
> did you open port via windows firewall? 8125 seems to be the default one

You may also need to open port `8080`.

**Comment by andrejetcat** [comment]
NOW it works with PORT 8080 also open! THANK YOU SO MUCH!!!
mysterious, because the server Client show me port 8125!

**Comment by andrejetcat** [comment]
does anybody know, if it supports a small Thermal Receipt Printer ?  like this one:
https://techmasternet.com/product/netum-nt-1809dd-58mm-bluetooth-thermal-receipt-printer-for-android-ios-windows-and-5890t-rs232-port-receipt-printer-pos-portable/
