### ISSUE TITLE
Windows 10 updates causing freezing

### ISSUE THREAD

**Issue by zaphod69** [flybywiresim/a32nx#6437]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-12-29T14:55:05+00:00",
  "ref": "master",
  "sha": "ef4c442c9aa891d042bf90ef6fba816c2b359282",
  "actor": "2hwk",
  "event_name": "manual"
}
```

### Describe the bug

After applying Windows 10 feature update 21H2 I've had no end of issues trying to use the A32NX.

I've tried removing all mods and nothing fixes the issue except rolling back to 21H1, then everything seems to be OK.

Is there something in the mod affected by the 21H2 update ?

### Expected behavior

To work in 21H2.

### Steps to reproduce

Install Windows 10 feature update 21H2 and try to load the A32NX.

**Comment by ErikNL80** [comment]
I run Windows 21H2 without any issues. Have you thought about updating your drivers (videocard) after the update?

**Comment by NGS31** [comment]
Hi!

No problem for me with W10/21H2.

The first NVidia's driver of December is not compatible with FS2020, for information.

Please install the last driver if not did yet.

**Comment by zaphod69** [comment]
Yes, tried driver version 497.29 but if anything this made it worse as it suffered stutters and freezing during the loading screen and never makes it to the ready to fly screen before getting the "Not responding" state.

I tried all the diagnostics steps recommended by other people sufferiung issues with 21H2 and the only thing that worked was uninstalling 21H2 (which has now broken Windows Update).

**Comment by zaphod69** [comment]
OK, back in 21H1 and problem returned after the following updates were installed:

KB5006365 Cumulative Update for .NET Framework 3.5 and 4.8
KB5007289 Cumulative Update Preview for .NET Framework 3.5 and 4.8

I would assume these updates are part of 21H2 also, so there is some sort of .NET update issue going on?

**Comment by aguther** [comment]
The A32NX does not use .NET at all. Therefore nothing we can do here.
