### ISSUE TITLE
[BUG] TCAS IDENT button is counted as a blank input for squawk code.

### ISSUE THREAD

**Issue by UncleClapton** [flybywiresim/a32nx#644]
**Mod Version**

master

**Describe the bug**

clicking "IDENT" gets counted as an input on the TCAS input panel.

**To Reproduce**

1. click IDENT
2. click other numbers
3. See IDENT is counted as a `-` input

**Expected behavior**

The IDENT button to essentially do nothing, and not screw up my transponder 😆 

**Actual behavior**

ATC yells at me for an invalid transponder code.

**References**

![](https://clapton.dev/u/2009/41c2244a.png)

**Additional context**

**Comment by UncleClapton** [comment]
I can work on this one.

**Comment by UncleClapton** [comment]
Found why it's happening. now we need to see if we can do anything with that input without just throwing it out.

**Comment by toffee2000** [comment]
Can we link it with VATSIM/vpilot?

**Comment by UncleClapton** [comment]
@toffee2000 Not at the moment. There doesn't seem to be a simvar visible over SimConnect that vPilot can hook into. It's not working with any other plane at the moment, either. A simvar would need to be added by Asobo and vPilot would need to start listening to it before we can integrate it into the mod.
