### ISSUE TITLE
(Remote MCDU) External device access IP bug.

### ISSUE THREAD

**Issue by pitch15** [flybywiresim/a32nx#6445]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-12-29T14:55:05+00:00",
  "ref": "master",
  "sha": "ef4c442c9aa891d042bf90ef6fba816c2b359282",
  "actor": "2hwk",
  "event_name": "manual"
}
```

### Describe the bug

There is a bug in the MCDU server.

The MCDU server works well, but the external access IP is wrong.

192.168.106.1:8125 was displayed, but it was not connected from another device.

So when I checked my Ethernet adapter, my local IP address was 192.168.0.100.

I tried to connect with this IP, and it worked fine.

192.168.106.1 was my VMware Ethernet adapter address.

Perhaps, there is a problem with VMware or multiple Ethernet adapters.

I hope it helps. Thank you FBW.

========================================================
Windows IP Configuration

Ethernet adapter VPN - VPN Client:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Ethernet adapter 이더넷:

   Connection-specific DNS Suffix  . : UNICORN
   Link-local IPv6 Address . . . . . : 
   IPv4 Address. . . . . . . . . . . : 192.168.0.100
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 192.168.0.1

Ethernet adapter VMware Network Adapter VMnet1:

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : 
   IPv4 Address. . . . . . . . . . . : 192.168.220.1
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . :

Ethernet adapter VMware Network Adapter VMnet8:

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : 
   IPv4 Address. . . . . . . . . . . : 192.168.106.1
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . :

### Expected behavior

"

### Steps to reproduce

"

**Comment by flytester** [comment]
I encountered a similar problem: layout of the MCDU was shown on the external device, but the screen stayed blank after starting up the aircraft. Using the provided external adress on the PC where FS runs for just one second made the external device work however.

**Comment by andrejetcat** [comment]
I had the same problem, so i opended port 8080 also. after that, it works, however the Server say port 8125.

try Port 8080

**Comment by frankkopp** [comment]
The IP detection is not always reliable and this is documented in our docs page for the feature:

https://docs.flybywiresim.com/fbw-a32nx/feature-guides/web-mcdu/#browser-on-remote-device
![image](https://user-images.githubusercontent.com/16833201/147860529-ecf49036-1da6-4b3f-9142-627c85a2c1c3.png)

Currently we see no way to improve this but we are still looking into. 
@tyler58546

**Comment by frankkopp** [comment]
As this issue has been answered I will close it for now.
