### ISSUE TITLE
(Remote MCDU) Can't run server.exe

### ISSUE THREAD

**Issue by GrotenM** [flybywiresim/a32nx#6448]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-12-29T14:55:05+00:00",
  "ref": "master",
  "sha": "ef4c442c9aa891d042bf90ef6fba816c2b359282",
  "actor": "2hwk",
  "event_name": "manual"
}
```

### Describe the bug

Hey I can't start the MCDU Remote Server. When i start the server.exe I always get the error listen EACCES: permission denied 0.0.0.0:8126. 

So as you can see I already changed the port as metioned in the docs, but didnt work though.

![Screenshot 2021-12-31 014736](https://user-images.githubusercontent.com/19939085/147796793-4e1b3b26-597a-44c6-bfd0-89c5401c1cbd.jpg)

Thanks for your help & effort!
 

### Expected behavior

Remote MCDU should spin up on localhost.

### Steps to reproduce

Start MCDU 

### Additional info (optional)

Windows 11 Version 10.0.22000 Build 22000

**Comment by alexg0102** [comment]
Have you tried to run the program as admin?

**Comment by GrotenM** [comment]
Yes when I run the exe as admin the terminal closes directly after choosing printer y/n, without any error.

**Comment by killyourradio** [comment]
https://docs.flybywiresim.com/fbw-a32nx/feature-guides/web-mcdu/#occupied-port

Looks like you trying to use a port that it already in use. Try following the solutions in the link.

**Comment by GrotenM** [comment]
> https://docs.flybywiresim.com/fbw-a32nx/feature-guides/web-mcdu/#occupied-port
> 
> Looks like you trying to use a port that it already in use. Try following the solutions in the link.

As you can see in my starting post thats what ive done.
