### ISSUE TITLE
Point Bearing Distance waypoints

### ISSUE THREAD

**Issue by 0x070E** [flybywiresim/a32nx#6449]
### Aircraft Version

Development

### Description

Capability of adding custom waypoints like this:

BOMBI/232/0.7 

At the flpn next waypoint option to add a usr waypoint outbound of BOMBI course 232° for 0,7nm (for example) would bei awesome and the better Part, its also possible in an IRL A320 ;) 

### References (optional)

Shown in this Video

https://youtu.be/E9uH0jdZttw

### Additional info (optional)

Would bei ideal for the custom fpm

**Comment by 0x070E** [comment]
Sorry closed for Duplicate of #4376

**Comment by Benjozork** [comment]
This is already done in dev, btw

**Comment by 0x070E** [comment]
> 

Does it? i tried it recently, but didnt seems to work, can you confirm the format i was using to enter the PBD like i entered above?
