### ISSUE TITLE
Remote MCDU events not triggered by external software

### ISSUE THREAD

**Issue by Narvik-Ramius** [flybywiresim/a32nx#6455]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-12-29T14:55:05+00:00",
  "ref": "master",
  "sha": "ef4c442c9aa891d042bf90ef6fba816c2b359282",
  "actor": "2hwk",
  "event_name": "manual"
}
```

### Describe the bug

When using the remote MCDU, the events sent to the sim are not "seen" by external software.
For example, if you start the SPAD.NEXT event/variables log, none of the inputs on the remote CDU appear (while they appear when using the CDU in the virtual cockpit).
(Probably) as a consequence, the remote CDU is not usable with YourControls.

### Expected behavior

Input on the remote CDU should behave the same as in the virtual cockpit, wich apparently isn't the case

### Steps to reproduce

1. Start a flight
2. Start SPAD.NEXT Data Monitor
3. Enter data on the remote MCDU : nothing appears in the data monitor
4. Enter the same data on the virtual cockpit MCDU : events appear in the data monitor

### Discord Username (optional)

Deunz#6796

**Comment by Nufflee** [comment]
Can confirm that remote MCDU is not usable with YourControls.

**Comment by John-UK** [comment]
I agree complex aircraft should aim to facilitate multi crew operations. Although IRL pilots use the MCDU not an iPad. 
choosing to use the IPad is an ease of use and unrealistic option that makes it easier for single pilots to get things done.

**Comment by frankkopp** [comment]
@Narvik-Ramius Can you clarify which events you mean specifically? Because you say events but then you say "Start SPAD.NEXT Data Monitor" - events and data are two different things.

**Comment by Narvik-Ramius** [comment]
@frankkopp hi and thanks for your rply.
I indeed wasn't very clear :-)
For the MCDU actions, YourControls synchronizes LVAR data between computers. As it doesn't work with the remote MCDU, I tried to look for what was going on, so I used SPAD.NEXT data monitor.
If for example, user 1 clicks (on the virtual cockpit MCDU) on INIT button, the A32NX_MCDU_PUSH_ANIM1_INIT changes values 3 times (0 => 0.8 , 0.8 => 0.2 , 0.2 => 0).
If user 1 clicks (on the remote MCDU) on INIT button, no data change in SPAD data monitor.
Therefore, I suppose YourControls syncs actions thanks to this LVAR (which as you mentionned are only used to control animation). Could it be possible to implement those animations with the remote MCDU ? Even beside the YourControl aspect, it would add the click noise and bouton animations for everybody ...

**Comment by frankkopp** [comment]
> Could it be possible to implement those animations with the remote MCDU ? Even beside the YourControl aspect, it would add the click noise and bouton animations for everybody ...

As I said this is possible but there are probably better ways than to use ANIM variables which are not intended for this purpose. 
May you could create a feature request instead a bug report as this is not a "bug" but simply a feature not yet implemented. 

Thanks

**Comment by Narvik-Ramius** [comment]
That makes sense, thanks for your replies.
I'll open a feature request right now !

**Comment by Narvik-Ramius** [comment]
closing - opening feature reaquest instead
