### ISSUE TITLE
Wont load

### ISSUE THREAD

**Issue by cabokid** [flybywiresim/a32nx#6464]
### Aircraft Version

Experimental

### Build info

```json
-
```

### Describe the bug

Whene i load the aircraft my flight sim is just stuck, you can hear the sounds but it doest doe anything. i tried every version of the 320nx. 

### Expected behavior

whene i load i just expect it to load at the gate

### Steps to reproduce

1. i select the airplane
2. i choose my wheights
3. i put in the airport oce (EHAM) and a random gate
4. i say fly now
5. it takes 5 minutes to load
6. afther loading i press fly now
7. the aircarft wont load you hear the sounds of the startup
8. in task manager it says wont respond

### Discord Username (optional)

cabokid#9333

**Comment by sidnov** [comment]
Please try to reproduce the issue with development version
