### ISSUE TITLE
Physical printing on POS style thermal printers is unreadable

### ISSUE THREAD

**Issue by plhought** [flybywiresim/a32nx#6468]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-01-01T15:56:48+00:00",
  "ref": "master",
  "sha": "e43e61e317489340a6b11e4960bcb72e72b0e722",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

Utilizing the new print interface of the MCDU server, when utilizing a widely avialiable and inexpensive POS style thermal printer ("POS-58" type - which is widely re-branded as resold under a number of different brands - TEROW, WAVA, MUNBYN, Zjiang etc etc), the text is very small an unreadable - along with going through about a foot and half of thermal paper before actually attempting to print something.
![20220101_121800](https://user-images.githubusercontent.com/96991444/147883368-08deeb52-caeb-4341-835c-d32404492785.jpg)
This is in contrast to a similar function on the FSLabs Airbus, which actually includes pre-built settings to support POS-58 thermal printers, as they are widely utilized by some of their userbase.

### Expected behavior

The text would print more in a manner similar to the actual aircraft - which also uses a thermal-printer - although wider.

### Steps to reproduce

1. Have a POS-58 type thermal printer
2. Correctly set up the MCDU Server print option
3. Attempt to print something via the ATSU in the MCDU 

### References (optional)

![20220101_121800](https://user-images.githubusercontent.com/96991444/147883396-aec82128-bcc9-4481-a757-54112afb4c93.jpg)

### Discord Username (optional)

Patrick#2854

**Comment by andrejetcat** [comment]
I think, it would solve the "problem" when the MCDU program gives out a normal word or .txt document.

**Comment by tracernz** [comment]
One workaround is to increase the font size in the server code (I found 28 works well). It gives imperfect but perfectly readable output. This could be made an option.

The other way is to print directly to the printer in raw mode.. this is very easy in Python using the excellent escpos library but I cannot find a good JS library (the “escpos” library on npm is unrelated unfortunately). At the moment I am using a small Python script that connects to the MCDU websocket server, listens for print events, and prints in raw mode. It’s by no means production ready; there is no error handling or reconnect logic, everything is hardcoded including the printer name. Dependencies are [escpos](https://pypi.org/project/python-escpos/) and [websockets](https://pypi.org/project/websockets/) (you will need to install these with pip). 

```py 
#!/usr/bin/env python3

import asyncio
import json
import websockets
from escpos.printer import Win32Raw

def printer(message):
    print(message)
    p = Win32Raw('HP Receipt')
    p.open()
    p.set(align='left', smooth=True)
    p.text(message + "\n")
    p.print_and_feed(n=3)
    p.cut(mode='PART')
    p.close()

async def printer_relay():
    async with websockets.connect("ws://localhost:8080") as websocket:
        while True:
            message = await websocket.recv()
            if message.startswith('print:'):
                msg = json.loads(message[6:])
                lines = [m.replace('\\n', '\n') for m in msg['lines']]
                printer('\n'.join(lines).strip() + '\n')

asyncio.run(printer_relay())
```

**Comment by andrejetcat** [comment]
thank you @tracernz , but its very hard to understand for no-Pro´s and even hard to replicate/dublicate :/

**Comment by Watsi01** [comment]
> thank you @tracernz , but its very hard to understand for no-Pro´s and even hard to replicate/dublicate :/

Don't worry. We think about something to configure it.

**Comment by Ryane37** [comment]
Exact same issue with another thermal printer printed a lot of waste at the top then unreadable tiny text.

**Comment by Ryane37** [comment]
Do you think it’s an easy fix to sort.

**Comment by Georgelumkin** [comment]
I also have a POS-58 printer and would really love this to be solved! Here is a photo of a .txt file printed (left) vs the MCDU PDF (right), and also the printer I’m using.

![319D47CA-AB63-41D7-B02F-BFDFCD373538](https://user-images.githubusercontent.com/97069357/148039059-3eecd355-3daa-4dd0-8717-d9d3bfac436e.jpeg)
![E7A06190-C5E1-42B0-BE9E-60188427CCF4](https://user-images.githubusercontent.com/97069357/148039063-19a2ad9e-3046-4b17-83f2-d64399e7991d.jpeg)

**Comment by Ryane37** [comment]
Has anybody tried it on the exp version check if that works.

**Comment by Ryane37** [comment]
> I also have a POS-58 printer and would really love this to be solved! Here is a photo of a .txt file printed (right) vs the MCDU PDF (left), and also the printer I’m using.
> 
> ![319D47CA-AB63-41D7-B02F-BFDFCD373538](https://user-images.githubusercontent.com/97069357/148039059-3eecd355-3daa-4dd0-8717-d9d3bfac436e.jpeg) ![E7A06190-C5E1-42B0-BE9E-60188427CCF4](https://user-images.githubusercontent.com/97069357/148039063-19a2ad9e-3046-4b17-83f2-d64399e7991d.jpeg)

Hi does this auto cut the paper

**Comment by frankkopp** [comment]
> Has anybody tried it on the exp version check if that works.

Experimental is only different for LNAV - otherwise identical to Dev

**Comment by wogapat** [comment]
Same issue for me, different printer. It is a thermal printer though.

**Comment by frankkopp** [comment]
Several improvements in development:
https://github.com/flybywiresim/a32nx/pull/6446

New parameters font-size and paper-size to adapt output to different printers.

**Comment by Georgelumkin** [comment]
> Several improvements in development: #6446
> 
> New parameters font-size and paper-size to adapt output to different printers.

Amazing! What variable do need to enter after the new —paper-size argument ?

**Comment by frankkopp** [comment]
> > Several improvements in development: #6446
> > New parameters font-size and paper-size to adapt output to different printers.
> 
> Amazing! What variable do need to enter after the new —paper-size argument ?

This will all be documented - a draft of the documentation (which will be removed after the feature is released) is here:
https://docs-git-fork-frankkopp-updt-webmcdu-docs-flybywire.vercel.app/fbw-a32nx/feature-guides/web-mcdu/#advanced-start-options
Note: This is all still in development and subject to change!!

**Comment by andrejetcat** [comment]
would it be possible that the MCDU gives out a .txt/word file, or is it just a .pdf?

**Comment by Georgelumkin** [comment]
Sorry folks I’m new to all this, are these changes now live in either the Development or experimental versions in the installer? Or can I download the server exe from here on GitHub?

thanks in advance from an enthusiastic newbie!!

**Comment by frankkopp** [comment]
> Sorry folks I’m new to all this, are these changes now live in either the Development or experimental versions in the installer? Or can I download the server exe from here on GitHub?
> 
> thanks in advance from an enthusiastic newbie!!

Patience please :) - the PR with the improvements is still in development.
https://github.com/flybywiresim/a32nx/pull/6446

**Comment by Georgelumkin** [comment]
> > Sorry folks I’m new to all this, are these changes now live in either the Development or experimental versions in the installer? Or can I download the server exe from here on GitHub?
> > thanks in advance from an enthusiastic newbie!!
> 
> Patience please :) - the PR with the improvements is still in development. #6446

Ah understood! Thank you @frankkopp, I will sit down and wait in line with everyone else 😬 thanks for the amazing work!

**Comment by plhought** [comment]
> > > Several improvements in development: #6446
> > > New parameters font-size and paper-size to adapt output to different printers.
> > 
> > 
> > Amazing! What variable do need to enter after the new —paper-size argument ?
> 
> This will all be documented - a draft of the documentation (which will be removed after the feature is released) is here: https://docs-git-fork-frankkopp-updt-webmcdu-docs-flybywire.vercel.app/fbw-a32nx/feature-guides/web-mcdu/#advanced-start-options Note: This is all still in development and subject to change!!

The paper-size option doesn't really help with thermal-printers though? Won't it just spit out unneccesary lengths of blank thermal paper before printing the text itself?

**Comment by frankkopp** [comment]
> > > > Several improvements in development: #6446
> 
> > > > New parameters font-size and paper-size to adapt output to different printers.
> 
> > > 
> 
> > > 
> 
> > > Amazing! What variable do need to enter after the new —paper-size argument ?
> 
> > 
> 
> > This will all be documented - a draft of the documentation (which will be removed after the feature is released) is here: https://docs-git-fork-frankkopp-updt-webmcdu-docs-flybywire.vercel.app/fbw-a32nx/feature-guides/web-mcdu/#advanced-start-options Note: This is all still in development and subject to change!!
> 
> 
> 
> The paper-size option doesn't really help with thermal-printers though? Won't it just spit out unneccesary lengths of blank thermal paper before printing the text itself?

Not according to the users who already tested this.

**Comment by tracernz** [comment]
> The paper-size option doesn't really help with thermal-printers though? Won't it just spit out unneccesary lengths of blank thermal paper before printing the text itself?

It does for me. The smaller the paper size the larger the text comes out.

**Comment by Tuftymeercat37** [comment]
Just tried this with my GoojPrt PT-200 58mm thermal printer (Paper Size set to C8 & font size10). The printout is perfect :-)

**Comment by msoehl** [comment]
How can I get this option? I have only the old one's

**Comment by VohnMclane** [comment]
I don't appear to have the options to change the text and the paper size they are not appearing on my command line

**Comment by frankkopp** [comment]
> I don't appear to have the options to change the text and the paper size they are not appearing on my command line 

This improvement feature is not yet released.

**Comment by VohnMclane** [comment]
ahh okay just wasn't sure as @Tuftymeercat37 seem to have changed theirs

**Comment by Tuftymeercat37** [comment]
I have just purchased the thermal printer so I was testing it by downloading/installing the build from PR #6446. This is not merged into the published Dev or Experimental versions yet. Hopefully it will be soon as it looks like it's just waiting for review.
