### ISSUE TITLE
SimBrief ZFW Import on INIT Page

### ISSUE THREAD

**Issue by cavaricooper** [flybywiresim/a32nx#6469]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-01-02T12:14:39+00:00",
  "ref": "experimental",
  "sha": "0dbab2de61272912e9fee4548dccb937e4754b89",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

When importing (Request and Load) via ATSU from SimBrief- the ZFW is consistently wrong in the LBS version of Fifi.  In KGs the ZFW comes across properly.  Also, overtyping does not seem to change the ZFWCG.

### Expected behavior

LBs should important as correctly as KGs

### Steps to reproduce

Create a FP in SimBrief with LBS
Use ATSU to import
View the incorrect ZFW
Overtype from FP
Observe no change in CG

### Additional info (optional)

About November 2021

### Discord Username (optional)

cavaricooper

**Comment by donstim** [comment]
Did you set the weight units to lbs in the EFB Aircraft Configuration settings?
![Screenshot (1441)](https://user-images.githubusercontent.com/70166617/147994742-efbadddd-8072-461d-88bd-187a23535b2c.png)
![Screenshot (1442)](https://user-images.githubusercontent.com/70166617/147994750-51d77803-6e17-40bc-993c-2d7032e56d28.png)

**Comment by cavaricooper** [comment]
Yes, repeatedly- with multiple full reboots over several days- still repeatable,

**Comment by donstim** [comment]
Check that your Simbrief profile didn't get reverted. I used your "steps to reproduce" from above and as you can see from my screenshots, the MCDU ZFW and payload match the ones in Simbrief. Can you provide screenshots of your OFP, Simbrief profile, and MCDU W/B page?

**Comment by cavaricooper** [comment]
You are correct- redownloading the Experimental Profile and planning gives me correct weights.  Thanks for the pointer! C

**Comment by donstim** [comment]
That's great!
