### ISSUE TITLE
Allow FlyPad to show undocked a la MCDU please

### ISSUE THREAD

**Issue by cavaricooper** [flybywiresim/a32nx#6470]
### Aircraft Version

Experimental

### Description

I appreciate the MCDU web interface and would love this same capability for the FlyPad, so it could show on a second computer in the RL location.  Ta!

### Discord Username (optional)

cavaricooper

**Comment by gustavocontin** [comment]
great idea, it would be great to have the flypad on an external tablet

**Comment by Benjozork** [comment]
This is planned and I am working on a protocol to run any instrument externally.

**Comment by gustavocontin** [comment]
> Benjozork

Good job Benjozork, i'm imagining other panels (G1000, G3000, fpd...), future will be amazing for simulation in MSFS2020.

**Comment by schmidHolger** [comment]
Issue #6124 and #4213 might also be solved by this.

**Comment by tigert** [comment]
@Benjozork we have a lot of interest in the MobiFlight community on remote instruments when we are building enclosed cockpit simulators and desktop panels with MSFS.

**Comment by derl30n** [comment]
https://github.com/flybywiresim/a32nx/issues/6978#issuecomment-1081228496

**Comment by 2hwk** [comment]
Duplicate of #6978 closing
