### ISSUE TITLE
Batter Switches 0.0V Error

### ISSUE THREAD

**Issue by brkayaoglu** [flybywiresim/a32nx#6473]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-11-21T01:55:55+00:00",
  "ref": "v0.7.3",
  "sha": "e6fb4129367d266aa6f77a979e37f66d458a2575",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

I tried lots of time but I can not turn on the batter switches because of they are 0.0V

### Expected behavior

I expect battery switches turn on when I press the batter switches button

### Steps to reproduce

1. I enter the flight infos.
2. I start the flight.
3. But when I try make pre-cockpit staff, battery switches not working

### Additional info (optional)

![image](https://user-images.githubusercontent.com/32249108/147921957-d5f27ecf-54f0-4278-83b7-001052170877.png)

### Discord Username (optional)

berkayrkayaoglu#9507

**Comment by Selim3535** [comment]
If you are using pilot avatar, deactivate the avatar and try again.

**Comment by tshomas** [comment]
Hi, we see this battery problem with a language error in Windows, could you try the below and if that helps?

![image](https://user-images.githubusercontent.com/74841560/147927842-26068139-4e91-47cc-b442-e49b414c5d64.png)

**Comment by brkayaoglu** [comment]
> Hi, we see this battery problem with a language error in Windows, could you try the below and if that helps?
> 
> ![image](https://user-images.githubusercontent.com/74841560/147927842-26068139-4e91-47cc-b442-e49b414c5d64.png)

this worked for me thanks :)
