### ISSUE TITLE
Seatbelt Sign Switch 

### ISSUE THREAD

**Issue by alexg0102** [flybywiresim/a32nx#6480]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-01-04T06:33:26+00:00",
  "ref": "master",
  "sha": "93b60b06f5db427fe1d9bf93531a513a3562845f",
  "actor": "tracernz",
  "event_name": "manual"
}
```

### Describe the bug

The Seatbelt Sign Switch is not assigned to the XMLVAR_SWITCH_OVHD_INTLT_SEATBELT_Position event. If you press the Switch, the number at the LocalVariables Tab in the Behaviour Panel for XMLVAR_SWITCH_OVHD_INTLT_SEATBELT_Position does not change. The other switches work.

### Expected behavior

The Number for XMLVAR_SWITCH_OVHD_INTLT_SEATBELT_Position should change between 1 and 0 when i press the switch.

### Steps to reproduce

1. Load into the Aircraft
2. Open the Behaviour Panel via DevMode
3. Go to LocalVariables
4. Search for XMLVAR_SWITCH_OVHD_INTLT_SEATBELT_Position 
5. Press the Seatbelt sign Switch

### References (optional)

https://user-images.githubusercontent.com/96475052/148058570-56113694-b686-4d27-90ac-2d06a1ce77ba.mp4

**Comment by frankkopp** [comment]
The seatbelt switch is assigned to "SIMCONNECT:CABIN_SEATBELT_ALERT_SWITCH_TOGGLE".

As you can see here https://docs.flybywiresim.com/pilots-corner/a32nx-briefing/a32nx_api/#signs-panel
