### ISSUE TITLE
Remote MCDU: 'ENTER DEST DATA' color should be amber, not white

### ISSUE THREAD

**Issue by ErikNL80** [flybywiresim/a32nx#6481]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-01-04T08:12:39+00:00",
  "ref": "experimental",
  "sha": "00c94c19d48c6d75b813cc5d8abd0d7b64c47b02",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

I really enjoy the remote MCDU, I noticed that the 'ENTER DEST DATA' message is shown in amber on the MCDU, but on the remote MCDU the message is shown in white. Can this please be fixed?

### Expected behavior

I would expect the message to come up in amber...

### Steps to reproduce

1. Start a flight with the remote MCDU
2. During the DES phase check for the 'ENTER DEST DATA' message
3. Compare the color of the MCDU message with the color of the remote MCDU message.

### Additional info (optional)
![MCDU](https://user-images.githubusercontent.com/71258178/148082903-9065a872-d366-411b-bf3c-8952cf9a666b.png)
_No response_

**Comment by kiwi2021** [comment]
Has been noticed, awaiting PR.
