### ISSUE TITLE
MSFS crashes with FBW A320 Dev 94b60b0 started

### ISSUE THREAD

**Issue by scotflieger** [flybywiresim/a32nx#6486]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-01-04T06:33:26+00:00",
  "ref": "master",
  "sha": "93b60b06f5db427fe1d9bf93531a513a3562845f",
  "actor": "tracernz",
  "event_name": "manual"
}
```

### Describe the bug

When dev v93b60b0 started from World Map FLY, MSFS2020 v1.21.13.0 while loading. Debug indicates an unhandled win32 exception in FlightSimulator.exe.

### Expected behavior

Aircraft to appear at selected airport.

### Steps to reproduce

Use FlyByWire Installer to update to Development version.
Start MSFS with A32NX.
Click on FLY.

**Comment by Benjozork** [comment]
Cannot reproduce.

Please try clean install steps documented below.

https://docs.flybywiresim.com/fbw-a32nx/installation/

**Comment by scotflieger** [comment]
Carried out a clean install of Dev version 93b60b0 using FBW Installer as suggested. However, MSFS still crashes after selecting FBW A32nx, airport and FLY. Crash occurs some 15 secs into load. I tried to switch back to Stable v0.7.3 but installer failed with error installing livery module.

Completed another clean installed with Stable version and MSFS opened without problems.

**Comment by tshomas** [comment]
Hi, if it’s crashing during the loading bar, could you possibly try the fix below?

https://docs.flybywiresim.com/fbw-a32nx/support/reported-issues/#load-modules-async-causes-ctd

**Comment by scotflieger** [comment]
@tshomas That was the cause. As a developer (LINDA with FSUIPC7) I had switched on developer options **Load Modules Asynchronously** and **Fast WASM Compilation**.
