### ISSUE TITLE
Brake pressure in air 

### ISSUE THREAD

**Issue by ShadowFrost3** [flybywiresim/a32nx#6488]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-01-04T06:33:26+00:00",
  "ref": "master",
  "sha": "93b60b06f5db427fe1d9bf93531a513a3562845f",
  "actor": "tracernz",
  "event_name": "manual"
}
```

### Describe the bug

![image](https://user-images.githubusercontent.com/87394534/148276572-4fd746b0-e392-4a32-a849-23ff8ed9c501.png)

### Expected behavior

@crocket63 Says its wrong. But I don't have access to super secret manuals to verify. 

### Steps to reproduce

Be at cruise 
Kill green pump by variety of methods
Drop gear
press brake pedal

**Comment by crocket63** [comment]
Ok that was a brain fart on my side, with gear down this is totally normal!  Sorry for this one
