### ISSUE TITLE
Implement A32NX_MCDU_PUSH_ANIM1_* LVARS for Remote MCDU

### ISSUE THREAD

**Issue by Narvik-Ramius** [flybywiresim/a32nx#6489]
### Aircraft Version

Development

### Description

Hi,

Is it please possible to add the use of the A32NX_MCDU_PUSH_ANIM1_* LVARS when using the Remote MCDU ?

That would allow :
- to see the push button animations in the virtual cockpit
- to hear the button clicks
- to allow synchronization of the events  for YourControls (as it is currently the only way available for YourControls to synchronize MCDU events and therefore flight plan changes between shared cockpits)

This feature request follows the closed bug [#6455](https://github.com/flybywiresim/a32nx/issues/6455) (as it appears it's not really a bug) 

### Additional info (optional)

Without those LVARS, there's no workaround to make remote MCDU use visible outside the plane (YourControls, external hardware, ...)

### Discord Username (optional)

Deunz#6796

**Comment by rthom91** [comment]
The ANIM local vars are simply for visual animation. YourControls reads the H-event for each key in the virtual pit and is then transmitted to clients.
