### ISSUE TITLE
After Update sim 7 when select FBW plane SIM keeps loading screen after click in FLY button

### ISSUE THREAD

**Issue by Ixoman** [flybywiresim/a32nx#6494]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-11-21T01:55:55+00:00",
  "ref": "v0.7.3",
  "sha": "e6fb4129367d266aa6f77a979e37f66d458a2575",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

After Update sim 7 when select FBW plane SIM keeps loading screen after click in FLY button

### Expected behavior

I have selected other native aircraft and sim is loading to fly normally

### Steps to reproduce

1. select FBW plane a320n
2. Select any departure
3. Click to fly button

### Discord Username (optional)

Ixoman0#3533

**Comment by Benjozork** [comment]
As stated on Discord and on all our communication channels, Stable is not yet compatible with the SU7 hotfix.
