### ISSUE TITLE
Fuel Burn does not reset on turnover flight

### ISSUE THREAD

**Issue by jetstarpilotmel** [flybywiresim/a32nx#6496]
### Aircraft Version

Experimental

### Build info

```json
Latest MSFS 2020 Hotfix (January 2022)
```

### Describe the bug

Hello Team,

I have noticed that the fuel burn for each engine and total fuel burn for both engines displayed on the lower ECAM display does not reset when completing a turn around flight (second flight)

This issue i have raised before (June/July last year) and it was fixed. Sometime between now and then it has become an issue again on both Development & Experimental versions of the FBW A320.

### Expected behavior

The real plane automatically resets the total fuel burn for each engine and total fuel burn for both engines once each engine has started.

### Steps to reproduce

Complete a flight
Turn engine 1 & engine 2 off
Start engine 1 & engine 2
Monitor fuel page to verify total fuel burn and each engines fuel burn has reset to 0.00
References (optional)

### Discord Username (optional)

JetstarcaptainJK#8904

**Comment by John-UK** [comment]
I put the original fix in and will take a look. I don’t fly multi sectors myself so it’s not something I use.

**Comment by 2hwk** [comment]
I feel the current behavior is correct, as fuel used is only reset when the engine is started, but we will keep verifying @Taz5150

**Comment by 2hwk** [comment]
(After landing and on ground fuel used 1+2: 780)

![image](https://user-images.githubusercontent.com/15316958/168587030-d104dfce-4d57-4e89-a9c0-cd097522ec26.png)

When engine 1 is started 

![image](https://user-images.githubusercontent.com/15316958/168587475-c2e6856b-97be-4142-953d-f9a9fa0f2930.png)

When engine 1+2 is started
