### ISSUE TITLE
FBW A320 New Stable 7.3 does not load  the mod after 1/6/22 MFS update 1.21.18.0

### ISSUE THREAD

**Issue by lasoh45** [flybywiresim/a32nx#6502]
### Aircraft Version

Stable

### Build info

```json
FBW A320 New Stable 7.3 does not load the mod after 1/6/22 MFS update 1.21.18.0
```

### Describe the bug

After the 1/6/22 update from MFS 1.21.18.0, when inputting a flight on the FBW A320 Neo, the flight loads  meaning that the long blue line at the bottom of the screen goes to 100% but the load does not happen.

Other aircraft in the MFS loads fine and the stock A320 Asovo loads fine as well.

### Expected behavior

Flight loads and appears on the screen

### Steps to reproduce

load and fly
on loading 
by doing a routing flight

**Comment by Benjozork** [comment]
Hello, as we have announced on socials and on Discord the current stable version doesn't work in the new MSFS patch. Please use the development version or wait until 0.7.4 comes out

**Comment by TenPatrol** [comment]
> ### Aircraft Version
> ### Describe the bug
> After the 1/6/22 update from MFS 1.21.18.0, when inputting a flight on the FBW A320 Neo, the flight loads meaning that the long blue line at the bottom of the screen goes to 100% but the load does not happen.

Workaround.
If you want to run the stable version go to -> [https://forums.flightsimulator.com/t/stuck-on-loading-screen-before-flight/487535/11](url)

**Comment by DaniloSakovic** [comment]
https://forums.flightsimulator.com/t/stuck-on-loading-screen-before-flight/487535/11

for dirty quick fix

**Comment by etkaar** [comment]
**Note:** In case an update to 0.7.4 does not help, you may have to fall back to the default livery.

**Comment by lasoh45** [comment]
Benjamin, updated Stable 4.0 today and we are good to go.  Thanks to the team, you guys are great!!!

 

 

 

 

 

Javier O. Delgado

President & Founder                      

PeopleToo LLC

305-588-4873

www.people-too.com

***@***.***
