### ISSUE TITLE
Different performance in FS stable vs experimental

### ISSUE THREAD

**Issue by flytester** [flybywiresim/a32nx#6509]
### Aircraft Version

Experimental

### Description

When comparing the stable version to the experimental version, I notice that the latter has worse framerates and more stutters, probably due to less effecient coding. Will this be fixed as soon as features from the experimental version make it to the stable version?

**Comment by Benjozork** [comment]
Most people have been reporting a performance increase in experimental. Also, it is necessary to provide screenshots of the MSFS FPS counter to showcase your issue.

Regardless, as stated in the known issues documentation, please do not open GitHub issues for experimental.

**Comment by flytester** [comment]
Hi Benjozork, thank for your swift reply. On my system, especially the microstuttering is more prominent in dev/exp compared to stable. Sorry for opening an 'experimental' issue. Since -experimental- was in the pull-down menu under -aircraft-, I didn't realize this was unwanted.

**Comment by Benjozork** [comment]
If you have screenshots of the MSFS FPS counter before and after, you can report them in the discord thread for experimental.
