### ISSUE TITLE
[BUG] Cruise Page no longer Displays on ECAM

### ISSUE THREAD

**Issue by KozziOS** [flybywiresim/a32nx#651]
**Mod Version**
Master #638 

**Describe the bug**
When no ECAM page is selected the CRUISE page should be shown. Currently defaulting to the ENGINE page.

**To Reproduce**
1. Be at cruise
2. Ensure no ECAM buttons are selected on the pedastal
3. ENGINE page is displayed instead of CRUISE

**Expected behavior**

CRUISE page to be displayed

**Actual behavior**

ENGINE page is displayed

**Comment by UncleClapton** [comment]
Unable to reproduce on latest master. 

![](https://clapton.dev/u/2009/c6325de2.png)

**Comment by ErikNL80** [comment]
I can confirm everything is working as well, also using the latest master. So nu bug IMHO.

**Comment by KozziOS** [comment]
Now unable to replicate in lastest master version - closing ticket :)
