### ISSUE TITLE
Custom LVARs for ISIS STD Button

### ISSUE THREAD

**Issue by mihunet** [flybywiresim/a32nx#6516]
### Aircraft Version

Development

### Description

Hi development team, 

Would it possible to get an LVARs

- ISIS Switch normal / STD-Mode

This would be helpful to get more functionality to home cockpit Solutions. 

Thank you :-)

### Additional info (optional)

It would be needed to implement also the ISIS Baro on the Behringer X-Touch MINI Device with the AAO MIDI Interface

### Discord Username (optional)

MIHU#8724

**Comment by tracernz** [comment]
The altimeter (2) is just a standard MSFS one so nothing FBW specific required to increment that. STD would require the code to be refactored as it’s implemented in XML at the moment.

**Comment by mihunet** [comment]
Thanks @tracernz for the reply. I asked for the altimeter because I didn't found any variable in the docs, but I will try it soon. 

The STD button LVar is taken to your development roadmap or is this planned for the next releases?

**Comment by mihunet** [comment]
ISIS Baro could be controled by (K:KOHLSMAN_SET), so only the STD Variable is still missing 👍

**Comment by mihunet** [comment]
I took a look into the code again and find a solution for this. The LVAR L:A32NX_ISIS_BARO_MODE can do what I need :-)
