### ISSUE TITLE
Loading airport freezing issue.

### ISSUE THREAD

**Issue by JosephPULid** [flybywiresim/a32nx#6518]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-10-28T18:01:48+00:00",
  "ref": "v0.7.1",
  "sha": "8d8fb7132f1be95a336f25a6e8441b1420d74989",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

When loading the airport, the blue loading bar increases slower than expected and when reaches the top it suddenly frezzes. However, music still run and the airport does not execute.

### Expected behavior

Expect succesfully loading screen as well as the airport.

### Steps to reproduce

1.Select a320nx from flybywire
2.select an airport, in this case I selected SKBO
3.Click ready to fly.

**Comment by aguther** [comment]
Please update to latest stable 0.7.4 that is needed for compatibility with latest sim version.

Feel free to reopen the issue when it’s not solved by that.

**Comment by JosephPULid** [comment]
Greetings auguther, I already did that and is not working though. Thanks 
![Captura de pantalla (175)](https://user-images.githubusercontent.com/97534862/149011576-205ed751-43f3-4e80-ab4b-b428036bf1ee.png)
![Captura de pantalla (176)](https://user-images.githubusercontent.com/97534862/149011590-e37b13c3-23d3-45d6-9eaa-8d8bf7ab92bf.png)
