### ISSUE TITLE
Flight plan issue when loading from Simbrief

### ISSUE THREAD

**Issue by Patsch78** [flybywiresim/a32nx#6520]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-01-10T23:30:14+00:00",
  "ref": "experimental",
  "sha": "da8b99f352f8dc7fd11745a66b5918dc2f97cb66",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

When loading a flight plan via SimBrief (some) waypoints get doubled, sometimes they are "split" by a discontinuity. When there are doubled waypoints in the plan, the route becomes a weird arc around this doubled waypoint when you get airborne. The flight plan seems ok as long as you stay on ground. In the case of a discontinuity between doubled waypoints, the discontinuity isn't displayed in the ND.

PS: if a discontinuity is between doubled waypoints its easy to spot them and delete one of them too, but if it is in the middle of a continuous plan its hard to spot them which results in an unexpected maneuver.

### Expected behavior

1. flight plan should not generate doubled waypoints when the SimBrief plan contains only one of each
2. discontinuity should be displayed correctly in the ND

### Steps to reproduce

1. load flight plan from SimBrief
2. check MCDU F-PLN page and ND

### References (optional)

![image](https://user-images.githubusercontent.com/54373982/149029856-d63ef0c6-ba77-4c86-9531-7f71967c4b82.png)
![image](https://user-images.githubusercontent.com/54373982/149029901-48a399e6-fba2-42f8-bf05-f6e5fbe1cd43.png)
![image](https://user-images.githubusercontent.com/54373982/149029930-023b3c5d-5634-4a87-a86c-97ac9bde0380.png)

SimBrief
![image](https://user-images.githubusercontent.com/54373982/149029986-29d8c996-9de0-467d-b2b1-1152efa55ac0.png)
![image](https://user-images.githubusercontent.com/54373982/149030523-d259307c-d658-4673-b06f-cde1e6f81dec.png)

### Additional info (optional)

Example plan:

WMKK/33 F370 PIBOS1F PIBOS R208 IGARI/F370 M765 BITOD M753 ADBOP
 HOTUN1F VVPQ/10

### Discord Username (optional)

ThePatsch78#0516

**Comment by tracernz** [comment]
The experimental version is not supported as it is an integration of a number of WIP features. Flight plan stringing is not expected to be correct yet (new flight plan system underway).

**Comment by Patsch78** [comment]
Oh, my bad. I didn't see that bug reports for experimental are not supported. Sorry for that. But what does "flight plan stringing" mean?

**Comment by tracernz** [comment]
Stringing the flight plan legs together, which is where we decide if a discontinuity exists and so on.
