### ISSUE TITLE
[BUG] SimBrief flight plan not correctly entered: AWY/WPT MISMATCH

### ISSUE THREAD

**Issue by JXKXB30** [flybywiresim/a32nx#6523]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-01-09T13:57:38+00:00",
  "ref": "master",
  "sha": "bcedb86e023614782713158deccf2b4d128d6a50",
  "actor": "crocket63",
  "event_name": "manual"
}
```

### Describe the bug

I always used the feature to import a Flightplan from simBrief into the MCDU but for 2 Weeks it simply doesn´t work. 

I normally generate a Flightplan. I enter the Flightplan into the AOC-Menu and this works exactly as before.

But when I want to Enter the INIT-Page to press the "INIT REQUEST" Button there is always the  Mistake "AWY/WPT Mismatch"

When you look at the "F-Plan" Page there is only the Departure and Arrival.

This happens on any Flight from simBrief 

### Expected behavior

that the Flightplan has all the Waypoints from simBrief.

### Steps to reproduce

1. Reinstalled the Game
2. Switched between the Fly by Wire Versions
3. Reinstalled the Mod

### Discord Username (optional)

JXKXB#9030

**Comment by Georgelumkin** [comment]
Have you got navigraph nav data? I found that this happened when my nav data was out of date or not installed properly

**Comment by JXKXB30** [comment]
No, I don´t have it in the sim I try to install it and then tell you if it´s fixed or not.

> Have you got navigraph nav data in the sim? I found that this happened when my nav data was out of date or not installed properly

**Comment by tracernz** [comment]
What is the route?

> No, I don´t have it in the sim but is there a possibility to solve this without paying for Navigraph

Depends on the issue. If the airway has been removed/amended since the old AIRAC cycle you get for free with SimBrief there's nothing you can do other than choose a different route that hasn't changed for a couple of years.

**Comment by JXKXB30** [comment]
I tried a lot and found out that the MCDU in my Plane is in a general way buggy. I Generated a new Simbrief Account and added it to my Plane and the Flightplan is right inserted, but the Arrival is pretty buggy. 

For example from EDDH to EDDM. 

ROUTE ID: DEFRTE
EDDH/33 AMLUH8G AMLUH M852 POVEL Z94 GALMA T703 LULAR T105 LANDU DCT
EDDM/26R


![Unbenannt](https://user-images.githubusercontent.com/97354947/149516277-c909c5dc-17d5-49d3-8db6-5464dad9ab57.PNG)

**Comment by tracernz** [comment]
Selecting the appropriate APPR VIA (LANDU) gets me a correct route here.

On exp even with the wrong via you will get a non-borked route but it will be ugly due to inappropriate approach direction.

**Comment by JXKXB30** [comment]
I selected LANDU as VIA but it looks not much better.
![Unbenannt](https://user-images.githubusercontent.com/97354947/149533802-8660e650-7578-4b75-8df9-08a0ecdb42bf.PNG)
![Unbenannt1](https://user-images.githubusercontent.com/97354947/149533806-7844f0b0-ff77-4bcb-addb-34b85ee474ff.PNG)
