### ISSUE TITLE
From/To page does not work.

### ISSUE THREAD

**Issue by FCTL3314** [flybywiresim/a32nx#6533]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-01-08T01:22:50+00:00",
  "ref": "v0.7.4",
  "sha": "5adc0dc1ee3bd9cf9386c312b798a5f8ca7b391b",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

*I am using google translate to write my problem* When I just start the plane and get to the point where I have to specify the airport of departure and arrival((From/To)(Init page)), I cannot enter the data. When i click on a From/To it just disappears and nothing is filled.

### Expected behavior

The airport of departure and arrival(From/To) had to be filled.

### Steps to reproduce

1. Open Init page in MCDU.
2. Try to fill in the airport of departure and arrival(From/To)

### References (optional)

![firefox_hTTQrkkdtS](https://user-images.githubusercontent.com/97694131/149382838-2e79c978-9609-4e89-acf4-3cd6b27777fc.png)

### Additional info (optional)

This problem has been from the very first installation and launch of this aircraft.
Tried uninstalling and reinstalling navdata but didn't help.

**Comment by scottfranks84** [comment]
How are you entering the from/to? Which format. If you were to fly from London Heathrow to Manchester for example you would enter   EGLL/EGCC   in that exact format

**Comment by FCTL3314** [comment]
@scottfranks84 Yes, that's how I enter it. In my case, LFPG/LIRF

**Comment by tracernz** [comment]
Are you able to fill any other fields on the MCDU?

**Comment by FCTL3314** [comment]
@tracernz Yes, all other fields are filled

**Comment by FCTL3314** [comment]
@tracernz As I noticed also not filled: Cost Index and CRZ FL/TEMP

**Comment by tracernz** [comment]
You are aware that in the Airbus you type what you want into the scratchpad, and then after press the key next to that line? Some other FMS are the opposite way around.

**Comment by FCTL3314** [comment]
Thanks to everyone for the answers, it helped me to upgrade to the latest version of the simulator.
