### ISSUE TITLE
Ошибка в FlyByWire Installer

### ISSUE THREAD

**Issue by KENTIKKIRILL** [flybywiresim/a32nx#6541]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-11-21T01:55:55+00:00",
  "ref": "v0.7.3",
  "sha": "e6fb4129367d266aa6f77a979e37f66d458a2575",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

Я хотел обновить самолёт до последней версии(v0.7.4). Зашёл в FlyByWire Installer, нажал обновить, далее появилась надпись подготовка к обновлению, а дальше ничего не происходило. Долго ждал ничего не происходило. Попробовал перезапустить приложение и начать заново, остановился на том же шаге. Подскажите пожалуйста что делать.

### Expected behavior

Начало обновления 

### Steps to reproduce

1. Зашёл в FlyByWire Installer
2. Нажал обновить

**Comment by Benjozork** [comment]
@hotshotp
