### ISSUE TITLE
When I try to select an arrival, I get a black screen with the words "UNTITLED"

### ISSUE THREAD

**Issue by FCTL3314** [flybywiresim/a32nx#6542]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2022-01-08T01:22:50+00:00",
  "ref": "v0.7.4",
  "sha": "5adc0dc1ee3bd9cf9386c312b798a5f8ca7b391b",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

I use google translator to describe the problem. I can't choose a STAR. When I try to select an arrival, I get a black screen with the words "UNTITLED"
![изображение](https://user-images.githubusercontent.com/97694131/149560592-5d7a015d-610d-4026-adff-5d6b951bc159.png)
After pressing:
![изображение](https://user-images.githubusercontent.com/97694131/149560652-e3967a39-a35c-42fe-8a49-e78af67262b9.png)
To be honest, I've already tried a lot of ways to solve this problem.
I completely reinstalled MFS2020, Tried to install developer version(There I have a lot of other problems so it's easier to solve this one), Deleted and updated the database but none of that helped.
The strangest thing is that I can choose SID:
![изображение](https://user-images.githubusercontent.com/97694131/149561270-3ebba3fc-69b1-444f-b0f9-65c90cf62911.png)
![изображение](https://user-images.githubusercontent.com/97694131/149561317-6694de88-df2e-45a3-86d9-adc4db7ce0e0.png)

### Expected behavior

I expected that I can choose the scheme and the runway

### Steps to reproduce

1. Open F-PLN in MCDU:
![изображение](https://user-images.githubusercontent.com/97694131/149565306-a89ad8ae-d116-4ea1-8c41-95f71f1c3f20.png)
2. Click on arrival airport:
![изображение](https://user-images.githubusercontent.com/97694131/149566960-25993fc1-7575-4291-8b98-5dc8bd8f3a96.png)
3. Click on ARRIVAL:
![изображение](https://user-images.githubusercontent.com/97694131/149566988-6c85385d-c9a7-443d-862c-f6b02df13da1.png)
4. UNTITLED:
![изображение](https://user-images.githubusercontent.com/97694131/149567043-ff4752a0-a2d6-4ef4-a248-adeab1675147.png)

### Additional info (optional)

This problem has been from the first installation and launch of this aircraft. Pls help. I want to fly this plane but I can't do it because of this problem :(

**Comment by FCTL3314** [comment]
I want to fly this plane but I can't do it because of this problem :(

**Comment by FCTL3314** [comment]
I found a solution to this problem. Need to change to version v.0.7.0. Maybe it’s possible for a newer one, but I haven’t checked it yet.

**Comment by FCTL3314** [comment]
It also works on version v.0.7.1

**Comment by FCTL3314** [comment]
Doesn't work since version 0.7.2

**Comment by FCTL3314** [comment]
Maybe it's related to this thing in the update list - "[MCDU] Sort approaches by type - @tracernz (Mike)"

**Comment by Valastiri** [comment]
@FCTL3314 What sim version are you using? Please provide a screenshot.

**Comment by tracernz** [comment]
Can’t reproduce this with cfms. Need to try stable some time.

**Comment by FCTL3314** [comment]
Thanks to everyone for the answers, it helped me to upgrade to the latest version of the simulator.
