### ISSUE TITLE
Sensitivity display on the PFD

### ISSUE THREAD

**Issue by Jaspology** [flybywiresim/a32nx#6544]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-01-14T20:14:31+00:00",
  "ref": "experimental",
  "sha": "2363d4439dad404470769c05dd35a4dfe7937b80",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

On the right PFD is a Sensitivity thing wich shows:
DMOD: 
TAU THR: 
Z THR:
ALIM:

### Expected behavior

No such display of the sensitivity

### Steps to reproduce

Just loaded into the Aircraft 

### Discord Username (optional)

Jasper S.#9275

**Comment by aguther** [comment]
Please do not open GitHub issues for experimental version. Report it on Discord in the channel for this version (within Support).

If you make that report please also provide a screenshot.
