### ISSUE TITLE
[BUG] ILS disarms when AP disconnected, engages LOC instead

### ISSUE THREAD

**Issue by CoffeePanda0** [flybywiresim/a32nx#655]
**Mod Version: 

Latest Dev - Default A320 (all have the issue)**

**Describe the bug**

When disengaging autopilot on an ILS approach, ILS is disarmed and instead LOC is turned on. This has happened to lots of people I have spoken to and is present in both the A32NX and stock Asobo A320

**To Reproduce**

1. Fly an ILS approach
2. Disengage AP when fully established
3. Watch the FMA and FCU

**Expected behavior**

ILS should stay engaged when AP is disconnected

**Actual behavior**

ILS is disconnected and instead LOC is engaged

**Comment by tareksabet** [comment]
fixed by pr #1715
