### ISSUE TITLE
A new 7.5 stable version wanted

### ISSUE THREAD

**Issue by ACSoft47** [flybywiresim/a32nx#6551]
### Aircraft Version

Stable

### Description

Stable version "weight & balance documentation" is wrong : "Press LSK5L to instantly load your planned payload and pax" is incorrect.

In fact, you have to press LSK6R and you do NOT obtain an instant load as documented (a kind of slow boarding time is simulated). You also cannot add additonal Cargo and you don't have the option to choose the loading speed of the "PAX & Cargo" in the Flypad.

I propose to implement into a new stable version 7.5, the actual design of Development version, which include just a single "W/B" page plus a working Cargo addition feature and the Flypad option which allow to choose the speed of "PAX & Cargo" load.

But please, do NOT include your new custom FMS in this version. For somebody like me, not using Simbrief and Navigraph datas, this FMS is a real nightmare whereas the stable version 7.4 work perfectly with original simulation flight plans & navigation datas. This  why I dream to have this new stable 7.5 version.

Thanks in forward to take my proposition into consideration.

**Comment by Benjozork** [comment]
The amount of work to make this kind of special version is a bit too high for the added benefit compared to the urgent items we are trying to focus on, like VNAV and improved FMS functionality, so I'm afraid it is unlikely this will be done.

As a side note - what exactly is the issue with the custom FMS and the MSFS flight plans ? As long as you use the world map and NOT .flt or .pln files, it should work fine enough for simple flights.

**Comment by frankkopp** [comment]
> Stable version "weight & balance documentation" is wrong : "Press LSK5L to instantly load your planned payload and pax" is incorrect.

Fixed in docs.

> In fact, you have to press LSK6R and you do NOT obtain an instant load as documented (a kind of slow boarding time is simulated). You also cannot add additonal Cargo and you don't have the option to choose the loading speed of the "PAX & Cargo" in the Flypad.

This is implemented in Development and will be in v0.8.0.

**Comment by tracernz** [comment]
Patch releases for stable versions are made on an as-needed basis. No new functionality should be included in patch releases. As there is nothing actionable I will close the issue. Discord is the best venue for general discussion.

**Comment by ACSoft47** [comment]
@tracernz to my humble opinion, you are wrong. Stable version is supposed to be a consistent version and in 0.7.4, the addition of PAX, Cargo & fuel is obviously a not finished feature, EVEN BUGGED (addition of Cargo dont work). Just look how this feature work now in dev version ! It is the main reason why I have proposed this minor update.

@Benjozork, a kind of special version ? No just a further minor version update (7.4 to 7.5) more consistent. Isn't it what you say in your documentation about stable version ? To much work to add a feature already done now into the dev version ?!? Sorry, but I cant believe that !

What kind of issue I have ? Maybe you would be inspired to test by yourself to fly without using Simbrief & Navigraph datas. You may try, for example, from LSGG  to LFML 31R or LFKJ to LSGG rwy ILS22, trying different STAR. You will have duplified waypoints, serie of missing waypoints, inconsistency with VFR map and more...

But with such a negative return, I am not motivated to explain in details.

In any cases, you already closed this thread.

**Comment by Benjozork** [comment]
He's not wrong, the versioning system dictates that no changes that aren't fixes are back-ported to stable versions.

Besides, not sure if you've done professional software development, but taking parts of new systems and adding them to old versions is nothing trivial, and a lot of things can break.

Every single time you have an issue, you accumulate them and then go rudely complain to our devs instead of making proper bug reports like everyone. Please - if you want your reports to be taken seriously, go ask us on Discord for help on specific issues you encounter so that we can see what is happening. The MSFS world map and default navdata are supported - but please make individual bug reports one at a time so that we can look into it properly.

**Comment by ACSoft47** [comment]
Sorry but my first message was not rude at all. I just mentionned facts in a neutral way and made a proposition, which I continue to think it could have been done, very easily, despite all your explanations. Maybe you had this feeling because of my reply to you and your collegue first reaction. If it is the case, don't be surprised, because such an unfair and incorrect argumentation against my proposition was totally unecessary and not something to make me feel good. Next time, just say something like: "Sorry but we are not interested by your proposition". Period !

And finally,  Benjozork,  about your lesson on how I must behave, I will answer to you in private.
