### ISSUE TITLE
random engine shut off

### ISSUE THREAD

**Issue by Dreamz23** [flybywiresim/a32nx#6552]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-01-14T19:41:33+00:00",
  "ref": "master",
  "sha": "6bc33978e4ea9611bba6ae0b1b7b15f990946c04",
  "actor": "crocket63",
  "event_name": "manual"
}
```

### Describe the bug

When doing a flight from kbos to kmco over an hour in the aircraft completely shut down and was unable to restart again causing flight to be worthless. it has happened a couple of times and i am sure there was enough fuel in plane. 

### Expected behavior

you shouyld be able to fly for a few hours no failures if they are turned off in settings

### Steps to reproduce

fly as normal usually happens after about 1hour

**Comment by frankkopp** [comment]
There are no known issue causing this. Check your fuel and key mappings.
We had many users who had keys mapped to engine or fuel switches. 
Come to our Discord for support and also to provide screenshots of the moments the engines fail for you.

**Comment by 2hwk** [comment]
Stale, will close if no update
