### ISSUE TITLE
off-axis in some buttons

### ISSUE THREAD

**Issue by Deltaflight84** [flybywiresim/a32nx#6554]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-01-16T22:24:51+00:00",
  "ref": "experimental",
  "sha": "341114947ef97050379336b7609ca0d032b29b15",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

Hello,
I noticed for a few days that pressing the key to turn on the APU does not center the command well (see screenshot attached) this does it in other cases, that is, the cursor does not center well the command of the key and you have to work with precision to do it that this command is pressed.
let me know if is an issue in my system.
Thx in advance

### Expected behavior

![66_17_01_2022](https://user-images.githubusercontent.com/76566744/149730878-302a6e6f-006a-420e-b39a-908022d173e2.jpg)
![68_17_01_2022](https://user-images.githubusercontent.com/76566744/149730882-9b7e2f4d-ccc8-4f1d-9e5f-d8b3d2fca14e.jpg)
![67_17_01_2022](https://user-images.githubusercontent.com/76566744/149730892-2cad62bf-022c-4623-894e-6bbbdaae04ce.jpg)

### Steps to reproduce

1. in flight when I press some required keys it is not possible to do this

### Discord Username (optional)

Doonydark#9006

**Comment by tracernz** [comment]
Turn off lens correction in MSFS settings. Since SU7 it doesn’t work properly.
