### ISSUE TITLE
TOD marker

### ISSUE THREAD

**Issue by ANC101** [flybywiresim/a32nx#6555]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-01-13T21:47:56+00:00",
  "ref": "master",
  "sha": "f808039638890cba8a27195b9617929971bd9c7e",
  "actor": "beheh",
  "event_name": "manual"
}
```

### Describe the bug

I've been flying the A320NX for the last month, and honestly I've enjoyed it more than any other aircraft in MSFS, though I've encountered one problem: there is no TOD bug. All I can see is the DECEL bug, but it never gives me the required distance to descend to the next altitude.

### Expected behavior

I think that (just like in the Cessna Citation CJ4 and B737NG) there should be a TOD marker on your MFD, to let you know when do you need to start your descend in order to reach the required altitude, by thee required waypoint/location.

### Steps to reproduce

1. Load up FBW A32NX
2. In the MCDU load up a SID and a STAR for my route
3. Expect a TOD marker, though there is none.

### Additional info (optional)

I think that the problem has something to do with the way I set up my MCDU, or is a thing that isn't implemented yet.

**Comment by ToLaTE4u** [comment]
Hey, as far as I know VNAV with a TOD Marker isn't implemented yet.

**Comment by ANC101** [comment]
Ok, thanks!

**Comment by scottfranks84** [comment]
Yeah it’s 100% not implemented yet. It is coming though

**Comment by ANC101** [comment]
Good to know!

**Comment by beheh** [comment]
Part of #5966.
