### ISSUE TITLE
Take off performance tool to the efb

### ISSUE THREAD

**Issue by doggydogg13** [flybywiresim/a32nx#6556]
### Aircraft Version

Experimental

### Description

It would be great to have a take-off performance tool integrated to the EFB which allows you to get: 
- Flex temperature
- flaps/THS
- V1, Vr, V2
According to the airplane load (fuel & paylod), to the runway LDA and the weather/runway condition.
I don't know if this feature is already in the pipeline, if it doesn't it would be nice!

### References (optional)

https://www.youtube.com/watch?v=5-HfqDdV9dw
go to 3:00 of this video

**Comment by BlueberryKing** [comment]
Hi, thank you for your suggestion! As I'm sure you are already aware, you can automatically compute V1, V$, and V2 by pressing the buttons next to the corresponding fields in the MCDU on the PERF page.

The problem with Flex temperature and flaps calculations is that we don't have the necessary performance data available for NEO aircraft that we could use to implement such a tool. Performance calculators that airlines use are very clever in that they take into account the conditions for every individual runway and the terrain around it for example to compute necessary climb gradients and such and make a recommendation based on those conditions. This is why we would need a lot of data to make a realistic implementation of such a tool.

We are of course always looking for possibilities to enable this, but it's not really something we can do right now.

**Comment by tracernz** [comment]
Duplicate #4444
