### ISSUE TITLE
[BUG] Glareshield not showing the numbers

### ISSUE THREAD

**Issue by noctlukadudu** [flybywiresim/a32nx#656]
**Mod Version**
Lastest A32NX stable ver.

**Describe the bug**
The EFIS Barometer referene and the FCU windows are not turning on when powering up the aircraft.
They remain blackened with no numbers visible.

**To Reproduce**

1. Start at the ramp (colçd&dark)
2. Turn on the batteries
3. Go to main cockpit view and stare at the glareshield.

**Comment by Benjozork** [comment]
You need to increase the screen brightness.

![image](https://user-images.githubusercontent.com/4503241/93028781-22001200-f5e4-11ea-9e6f-fd3287205886.png)

**Comment by noctlukadudu** [comment]
It´s obvious I had increased screen brightness.
All PFD are ok, except EFIS and FCU

**Comment by Benjozork** [comment]
> It´s obvious I had increased screen brightness.

https://i.imgur.com/rOYiXfx.png

**Comment by noctlukadudu** [comment]
LOL
Turned ALL the knobs , except these 2 black ones, btw they are difficult to see... 
Thanks!
