### ISSUE TITLE
VNAV 

### ISSUE THREAD

**Issue by ANC101** [flybywiresim/a32nx#6561]
### Aircraft Version

Development

### Description

I think it would be extremely useful, and would make the A32NX much more fun if there would be VNAV integrated. Things like the TOD marker would take a lot of workload off the pilot, and overall be extremely fun to use.

**Comment by beheh** [comment]
Hey, thanks for filing an issue. Please make sure to search the list of issues for duplicates. This even has the same title as the duplicate.

**Comment by beheh** [comment]
Duplicate of #5966
