### ISSUE TITLE
No syncing of MCDU FP with MSFS after 1.21.18.0

### ISSUE THREAD

**Issue by MStallen** [flybywiresim/a32nx#6562]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-01-18T21:08:51+00:00",
  "ref": "master",
  "sha": "e919a7be7ce86ed69dc053078e1c004fd0310b86",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

No syncing of MCDU FP with MSFS after 1.21.18.0. If I enter the STAR during flight ATC of MSFS doesn't use that.

### Expected behavior

Sync of MSFS with changes in MCDU flightplan

### Steps to reproduce

1. Cold and Dark Startup EHAM
2. Import FP via Simbrief to EHEH
3. Insert SID
4. Fly
5. During flight (halfway) insert STAR

### Additional info (optional)

Was working before update 1.21.18.0.
In EFB safe option sync MSFS Flight plan selected.

**Comment by tracernz** [comment]
Have you read the instructions here? https://docs.flybywiresim.com/fbw-a32nx/feature-guides/cFMS/#special-notes. Please be aware that if you have this option enabled you may experience CTDs which we cannot support.

**Comment by MStallen** [comment]
Yes I've read them.
What I found out that's when you only have a departure and an arrival airport and a discontinuity in between in your flightplan then it doesn't work.
If you add at least one waypoint like EHAM-LOPIK-discontinuity-EHEH it works.

**Comment by 2hwk** [comment]
At least on this latest SU I am unable to reproduce

**Comment by 2hwk** [comment]
Closing because stale, reopen if this is still an issue.
