### ISSUE TITLE
 in der MCDU bei FBW 32NX  das AOC Menu nicht vorhanden

### ISSUE THREAD

**Issue by Pensi8911** [flybywiresim/a32nx#6566]
### Aircraft Version

Development

### Build info

```json
ich kann das leider nicht finden.
```

### Describe the bug

wenn ich den Simbrief laden will gehe ich ins Cockpit zue MCDU. Bei klick auf das MCDU Menue tut sich nichts da das AOC Menu nicht aufscheint, kann ich den Flug nicht laden

### Expected behavior

das es irgendwann wieder funktioniert.

### Steps to reproduce

Kann den Flug nicht eingeben

### References (optional)

![AOC Menu](https://user-images.githubusercontent.com/87388554/150573122-ee7c5842-ac85-43d0-b6e1-2c6c4379a4fd.jpg)

### Additional info (optional)

Es hat schon einmal funktioniert, aber das ist schon eine Weile her.

### Discord Username (optional)

pensi8911

**Comment by BlueberryKing** [comment]
Hi, das AOC MENU solltest du auf der rechten Seite sehen, wenn du zuerst auf ATSU klickst im Menü, das im Screenshot zu sehen ist.

**Comment by Pensi8911** [comment]
Alles ok, aber er fragt nicht mehr nach Simbrief und meiner Usernummer. Es fehlt der Check.
Lg.Pensi

**Comment by BlueberryKing** [comment]
Das wird jetzt im EFB gemacht. Am besten schaust du dir unseren Guide dazu an: https://docs.flybywiresim.com/fbw-a32nx/feature-guides/simbrief

**Comment by BlueberryKing** [comment]
Kein Problem, melde dich am besten auf unserem Discord, wenn du weitere Probleme oder Fragen hast, da können wir dir am besten helfen: https://discord.gg/TjBn6neZdf 😄
