### ISSUE TITLE
MCDU -> ATSU -> AOC Menu -> W&S: Page 1  missing, no page index

### ISSUE THREAD

**Issue by Adi-18** [flybywiresim/a32nx#6574]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-01-23T05:07:32+00:00",
  "ref": "master",
  "sha": "3003740d40aa28c78300bd5aff8ac84a9c929558",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

As descripte [here](https://youtu.be/wZKyZFf0pY0?list=PLS-87vj4aRgMcYCkqhUpF3DUjbGhpBJ2w&t=266)  there should be Page one for Block Fuel (also on Checklist from JD).

But I cannot see Block fuel:
![image](https://user-images.githubusercontent.com/29123730/150672605-faefb554-4099-4048-9211-2af9d60f84c9.png)
So the block fuel was competently wrong.

### Expected behavior

For W/B Page 1 and Page two (1/2 and 2/2)

### Steps to reproduce

Use Build as above
Go to menu

### Discord Username (optional)

Adi#1912

**Comment by John-UK** [comment]
Block fuel has been in the EFB for quite a few weeks now.

**Comment by marcsoler** [comment]
https://docs.flybywiresim.com/fbw-a32nx/feature-guides/flyPad/dispatch/#ofp-page
