### ISSUE TITLE
Flaps and spoilers deploy when charging headset

### ISSUE THREAD

**Issue by smodin32** [flybywiresim/a32nx#6575]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-01-23T05:07:32+00:00",
  "ref": "master",
  "sha": "3003740d40aa28c78300bd5aff8ac84a9c929558",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

When i plug my headset (razer nari ultimate gaming headset) for charging in the computer, Flaps and Spoilers exstends every time.

### Expected behavior

Expect nothing to happen.

### Steps to reproduce

1. crusing to destination 
2. plug headset in 

### Discord Username (optional)

smodin#9658

**Comment by John-UK** [comment]
MSFS does not like connecting or disconnecting any USB in flight. Not really a FBW issue.

**Comment by aguther** [comment]
This is an MSFS issue.
