### ISSUE TITLE
[BUG] MCDU stuck in take off phase after a landing with full stop

### ISSUE THREAD

**Issue by MaitreKit** [flybywiresim/a32nx#658]
**Mod Version**

Latest Dev - Default A320 (all have the issue)

**Describe the bug**

After a landing with full stop, the MCDU go back to the start up page and the perf page is stuck in take off phase.
After a 2nd take off, the take off phase nerver ended and APPR Phase can't be activated.

**To Reproduce**

1. Take off and reach THR RED/ACC altitude
2. Activate APPR Phase on the MCDU
3. Land with full stop
4. Take off. The MCDU is stuck in take off phase.

**Expected behavior**

The MCDU should end the take off phase when you reach THR RED/ACC altitude and start CLB phase.
APPR Phase should be available.

**Actual behavior**

After a landing with full stop, the MCDU perf page seems to be stuck in take off phase.

**References**

**Additional context**

**Comment by CoffeePanda0** [comment]
A bug report has already been opened for this #562 
A PR is waiting to go through that should fix this so this shouldn’t be an issue in a day or two hopefully anyway

**Comment by MisterChocker** [comment]
this most likely is fixed by now
