### ISSUE TITLE
no spoiler wind-sound since today

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#6581]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-01-23T08:52:00+00:00",
  "ref": "experimental",
  "sha": "f40d8e557f93b802c3f950fb80e08e5e6782de27",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

on todays flight I do not hear any spoiler sound upon spoiler deployment in flight like the typical air turbulence sound.

### Expected behavior

air turbulence sound like before

### Steps to reproduce

deploy spoiler in flight

**Comment by hotshotp** [comment]
I did not change this last PR

**Comment by Watsi01** [comment]
Also affirmed. Even it's gone or much lower volume.

**Comment by hotshotp** [comment]
Yeah looks like I got some bug fixing to do tonight with the touchdown sound and spoiler wind 😄
