### ISSUE TITLE
No audio sound now when using the hand torch on/off command

### ISSUE THREAD

**Issue by MjrIncident** [flybywiresim/a32nx#6583]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-01-23T17:25:08+00:00",
  "ref": "master",
  "sha": "ca74a03c6b8456acb416b176d9a12743a033d075",
  "actor": "IbrahimK42",
  "event_name": "manual"
}
```

### Describe the bug

C&D start sometimes requires a hand torch ( Alt+l ) to help see the battery/power buttons etc.
When pressing Alt+l we turn on/off the handheld torch - but there are no sounds. These are no longer heard.

### Expected behavior

To hear the audio beep when torch is turned on.
To hear the audio beep when torch is turned off.

### Steps to reproduce

Press Alt + L - no sound.

### Additional info (optional)

There used to be on/off audio sounds in previous version. Noted absence of the sound started probably about 2-3 months ago iirc.

**Comment by sidnov** [comment]
Can you record a short video clip of this sound if it works with other aircrafts? (Default preferably)

**Comment by sidnov** [comment]
Checked with default aircraft, issue is sim-side
