### ISSUE TITLE
Handling of ice accretion weight

### ISSUE THREAD

**Issue by donstim** [flybywiresim/a32nx#6584]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-01-19T05:55:43+00:00",
  "ref": "experimental",
  "sha": "44e9ed3ea1d214791968f7e90d175e5007910ce4",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

As part of the MSFS simulation of icing, Ice accreting on the airplane can add significant weight, much more than would occur IRL. When deicing occurs, the airplane weight decreases. The airplane's weight can be observed in two places in the A32NX: 1) on the lower ECAM screen (after engine start); and 2) on the MCDU Fuel Prediction page. The airplane's weight is also used in calculating the takeoff speeds shown on the MCDU PERF TAKE OFF RWY page and the VLS and approach speed shown on the MCDU PERF APPR. The ZFW shown on the MCDU Fuel prediction page is also affected; the ZFW will change if the LSK is pressed at different times while icing or de-icing is occuring.

The gross weight shown on the MCDU fuel prediction page includes the weight of the ice. The gross weight shown on the lower ECAM page does not include the weight of the ice, so there is an inconsistency in the weights shown in these two places.  See the following screenshot:
![Screenshot (1491)_LI](https://user-images.githubusercontent.com/70166617/150731812-63955115-9967-4452-9b6b-9a99d4440109.jpg)

Additionally, Vapp and VLS shown on the MCDU PERF APPR page appear to be based on the same gross weight shown on the lower ECAM and will also not reflect the weight of any ice accreted. In contrast, the takeoff speeds on the MCDU PERF TAKE OFF RWY page do appear to reflect the weight of any ice accreted.

The effect of the increased weight is that the stall speeds will increase. In MSFS, the weight can increase by up to 2300 kg, which leads to about a 2-3 knot increase in VLS for flaps full, for example. Since this is within the 5 knot minimum additive to VLS to determine Vapp, it should not cause any significant issues on approach and landing. It is also within the margins already applied to the takeoff speeds. Since the low speed/high angle-of-attack envelope protection system is based on AOA rather than the airplane weight value, any weight error resulting from ice accretion should not matter there either.

### Expected behavior

The airplane weights displayed on the lower ECAM and on the MCDU Fuel Prediction page should be the same. They should not include the weight of ice accreted on the airplane as they would not include this IRL. The weights shown on these pages are not sensed directly by the airplane.

Similarly, neither the takeoff nor the VLS and approach speeds shown on the MCDU Perf pages should include the weight of the ice. They should be derived using the input payload added to the OEW and the weight of the current fuel load.

### Steps to reproduce

Covered in the description

### Discord Username (optional)

donbikes#4084

**Comment by milaandahiya** [comment]
Pardon my ignorance, but how can the A320 actually calculate the GW with ice accretion IRL?

**Comment by donstim** [comment]
> Pardon my ignorance, but how can the A320 actually calculate the GW with ice accretion IRL?

Not ignorant at all. In fact hat is a very good question. The answer is that it doesn't. As I noted in the description, there normally would not be any appreciable weight added by accreted ice on the A320neo. However, the MSFS icing affects are overdone such that up to 2300 kg of weight can be added due to ice. This will increase the stall speed of the airplane and should be compensated for by increasing the takeoff and approach speeds. Due to how these speeds are programmed in the current A32NX, the takeoff speeds will include the weight of the ice, but the approach speeds will not.

But thanks to your question, I've rethought the solution. The stall speed increase due to the weight added by the ice is only a few knots at the maximum, which is within the margins that are already applied to the takeoff and approach speeds. So, although the safety margins on these speeds are reduced, it shouldn't cause any immediate issues.

The bigger issue is the inconsistency between the weights displayed by the ECAM and the MCDU FUEL PRED page, and the weight used in computing the takeoff and approach speeds on the MCDU PERF pages. I have updated the issue description to recommend removing the weight due to icing from the MCDU FUEL PRED page and the effect of the additional weight on the takeoff speeds shown on the MCDU PERF TAKE OFF RWY page.

Thank you for this question.

**Comment by milaandahiya** [comment]
Thanks for your answer. It seems the best solution here would be to change the behavior of the MCDU to that of the ECAM (like you said) but also change the way MSFS icing affects the weight of the aircraft, if that's possible (maybe by adjusting the planes weight downward in icing conditions mathematically to have more realistic weight addition due to ice).

**Comment by sidnov** [comment]
@donstim This should be an easy fix. A few questions before I make any changes:

1. What is the source of the values on the Lower ECAM GW section (IRL)? Is it an estimation of what's input to the systems?

2. Considering the above situation, would it be alright to simply use the source of value displayed in the ECAM instead of pulling total weight? (which is the case currently)

**Comment by donstim** [comment]
> @donstim This should be an easy fix. A few questions before I make any changes:
> 
> 1. What is the source of the values on the Lower ECAM GW section (IRL)? Is it an estimation of what's input to the systems?
ZFW + Block Fuel inserted in the INIT B (Fuel Pred) page of the MCDU, then subtracting fuel used during the flight. (I haven't checked, but I think the GW on our lower ECAM page may use the ZFW and fuel values regardless of whether or not they are actually inserted in the MCDU. I don't think the real airplane would do that, but don't know for certain,)
> 2. Considering the above situation, would it be alright to simply use the source of value displayed in the ECAM instead of pulling total weight? (which is the case currently)
Yes, I think that would be correct. Would of course have to QA it to make sure it doesn't lead to any unforeseen issues.

**Comment by sidnov** [comment]
> > @donstim This should be an easy fix. A few questions before I make any changes:
> > 
> > 1. What is the source of the values on the Lower ECAM GW section (IRL)? Is it an estimation of what's input to the systems?
> >    ZFW + Block Fuel inserted in the INIT B (Fuel Pred) page of the MCDU, then subtracting fuel used during the flight. (I haven't checked, but I think the GW on our lower ECAM page may use the ZFW and fuel values regardless of whether or not they are actually inserted in the MCDU. I don't think the real airplane would do that, but don't know for certain,)
> > 2. Considering the above situation, would it be alright to simply use the source of value displayed in the ECAM instead of pulling total weight? (which is the case currently)
> >    Yes, I think that would be correct. Would of course have to QA it to make sure it doesn't lead to any unforeseen issues.

Thanks for confirming, I'll see what can be done to fix this 👍🏻
