### ISSUE TITLE
problem with fueling, max 3,7 !

### ISSUE THREAD

**Issue by zww55** [flybywiresim/a32nx#6588]
### Aircraft Version

Experimental

### Build info

```json
latest
```

### Describe the bug

sorry, bad eglish, from simbrief import only small amout

### Expected behavior

........

### Steps to reproduce

.............

### References (optional)

.............

### Additional info (optional)

................

**Comment by andrejetcat** [comment]
you have to set your fuel manually via the EFB.

**Comment by zww55** [comment]
I set in msfs, start aircraftand still 3.6🙂

**Comment by andrejetcat** [comment]
This do NOT work with the A32NX. You have to Set it via the EFB after loading the flight

**Comment by zww55** [comment]
Thanks! I will take a look what it is.

**Comment by andrejetcat** [comment]
The EFB is the small tablet on the left of the pilot :-) there you mußte serach the Option "Fuel" the you can fillup your tanks as you need 🙂

**Comment by zww55** [comment]
It will be a good thing, i think i never seen fuel, tomorrow i take a look, thanks!

**Comment by zww55** [comment]
Yes! In tablet is fueling, and works🙂 Thanks!

**Comment by NUTTTTTTTT** [comment]
As above, this is to be done via the EFB. See more here: https://docs.flybywiresim.com/fbw-a32nx/feature-guides/loading-fuel-weight/ :) 

![image](https://user-images.githubusercontent.com/87286435/151058623-65750b1e-9944-49a7-ab48-76da1fae768d.png)
