### ISSUE TITLE
Since  "built": "2022-01-23T05:07:32+00:00",

### ISSUE THREAD

**Issue by Adi-18** [flybywiresim/a32nx#6589]
Since  "built": "2022-01-23T05:07:32+00:00",

After preparing Flight , take off and climb over 5000(?) ft, there starts a deeb sound monotonously (about 60 Hz or so).

There is no warning lights or corresponding messages in ECAM and its horrible until the end of the flight.

What may it be?

_Originally posted by @Adi-18 in https://github.com/flybywiresim/a32nx/discussions/6579_

**Comment by Benjozork** [comment]
Please do not delete the pre-existing issue template.
