### ISSUE TITLE
Since "built": "2022-01-23T05:07:32+00:00"

### ISSUE THREAD

**Issue by Adi-18** [flybywiresim/a32nx#6590]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-01-23T05:07:32+00:00",
  "ref": "master",
  "sha": "3003740d40aa28c78300bd5aff8ac84a9c929558",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

Because of no answer in Discussions maby a bug?

Since "built": "2022-01-23T05:07:32+00:00",

After preparing Flight , take off and climb over 5000(?) ft, there starts a deeb sound monotonously (about 60 Hz or so).
There is no warning lights or corresponding messages in ECAM and its horrible until the end of the flight.

Maybe I reached level configured in INIT -> FL?

I cannot find any documentation nor an answer. What could it be and how to resolve it?

### Expected behavior

No sound?
Warning messages?
Documentation?

### Steps to reproduce

Load flight plan
start fly
start everything airplane
configure  MCDU
Start to fly and Take off
Wait
Start with nerves sound

### References (optional)
On YT I have published an flight example. At the end, the sound stopped and started again. For landing they stopped.
[Flight from LPPT - LPMA Lisbon to Madeira](https://youtu.be/UGrircOKroA)

_No response_

**Comment by hotshotp** [comment]
update your a32nx, this was an issue that was fixed yesterday
