### ISSUE TITLE
Strange LNAV behaviour during SID and STAR

### ISSUE THREAD

**Issue by DanP77** [flybywiresim/a32nx#6591]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-01-24T21:05:11+00:00",
  "ref": "experimental",
  "sha": "8dc50e3fdf88bd35031820ced880e7ba396802f4",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

Strange LNAV behaviour during SID and STAR

### Expected behavior

Linear Behaviours as by chart Navigraph (I'm using Navigraph charts with Navigraph Navdata)

### Steps to reproduce

I'm using Navigraph current navdata.
Check ERIG3N departure from LFRS or IMVU1Z on EGKK airport. (but not only)
A lot of strange behaviours.

I will append photos on next flights when it happen and/or I will test with other Airplane.

**Comment by aguther** [comment]
No tickets for experimental, please report it on Discord
