### ISSUE TITLE
[webMCDU] clickspots create blue link markers on click

### ISSUE THREAD

**Issue by St54Kevin** [flybywiresim/a32nx#6593]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-01-25T18:51:44+00:00",
  "ref": "experimental",
  "sha": "77ea421b1482f2f560d1e9c76293781f73a338c1",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

clicking on buttons on the webMCDU create blue link markers. The ones for the LSK and RSK keys even go deep into the display. 
Im on Android with Chrome browser. As a test I also tried the default Huawei Browser and the ones on my phones. Same behavior on all of them.
![image](https://user-images.githubusercontent.com/448627/151067814-45abdf48-c756-4120-a1c7-247eea5f5b52.png)

### Expected behavior

correct LSK/RSK clickspots. No blue marking

### Steps to reproduce

Use the webMCDU

### Discord Username (optional)

St54Kevin#3583

**Comment by frankkopp** [comment]
Why would that be an issue? A visual indication on a touch device is a good thing. 
Also the touch clickspot is indeed larger with as the buttons per design - you can click on the line on the display as well.
Please close this as this is not a bug. You can create a feature request if you think this is worth a change.

**Comment by St54Kevin** [comment]
> 

Because when using the buttons, as you are supposed to (the real thing does not have a touch screen, why would you click the line itself then?), Its very distracting because the blue marker goes over half the display. For me thats a design issue, not a feature.

**Comment by frankkopp** [comment]
As I said - it is like this per design. So not a bug. 
I agree that one could have a different opinion if this is a good design or not. 
Therefore I recommend to create a feature/enhancement request. 

PS: Personally I like tit like this as it makes it easier to hit the correct button esp. on smaller devices.

**Comment by St54Kevin** [comment]
Hm i dont understand why adding an unrealistic feature without an option to disable it. I would prefer not having those markers at all. It reminds you are on a computer rather the real thing. I will make this a copy paste into a feature request

**Comment by St54Kevin** [comment]
https://github.com/flybywiresim/a32nx/issues/6595
