### ISSUE TITLE
[webMCDU] disable clickspots blue link markers on click

### ISSUE THREAD

**Issue by St54Kevin** [flybywiresim/a32nx#6595]
### Aircraft Version

Experimental

### Description

clicking on buttons on the webMCDU create blue link markers. The ones for the LSK and RSK keys even go deep into the display. 
Im on Android with Chrome browser. As a test I also tried the default Huawei Browser and the ones on my phones. Same behavior on all of them. I would like to see an option to either reduce the LSK clickspot size to the real button or/and an option to disable the blue marker entirely, as it distracts and is unreal imo.
![image](https://user-images.githubusercontent.com/448627/151067814-45abdf48-c756-4120-a1c7-247eea5f5b52.png)

### Discord Username (optional)

St54Kevin#3583

**Comment by St54Kevin** [comment]
If you want to have a feedback for a button click, is it not possible to add button animations?

**Comment by frankkopp** [comment]
Might be a possible enhancement - also a click sound.
Currently the MCDU itself is just a simple image with linked areas.
