### ISSUE TITLE
Missing realism settings in EFB

### ISSUE THREAD

**Issue by demonguy** [flybywiresim/a32nx#6599]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2022-01-08T01:22:50+00:00",
  "ref": "v0.7.4",
  "sha": "5adc0dc1ee3bd9cf9386c312b798a5f8ca7b391b",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

I cannot find "Seperate tiller with rudder input" options. which prevent me from using joystick to controll nose wheel

![image](https://user-images.githubusercontent.com/1451096/151208113-6b84c53c-6df1-4e01-adc6-93dc02232f3c.png)

### Expected behavior

should be in realism settings

### Steps to reproduce

as screenshot shows

**Comment by killyourradio** [comment]
"Seperate tiller with rudder input" is only available on dev or exp. You are on stable.

**Comment by sidnov** [comment]
Please try again with development/experimental version as mentioned above
