### ISSUE TITLE
[REQUEST]F/CTL ECAM Page

### ISSUE THREAD

**Issue by tareksabet** [flybywiresim/a32nx#660]
**Is your feature request related to a problem? Please describe.**
Yes

In the F/CTL Page on the lower ECAM is appeared in green Prior Engine Start 
![Microsoft Flight Simulator 9_14_2020 12_51_36 AM](https://user-images.githubusercontent.com/70240330/93032048-7bd9f980-f62f-11ea-846c-5107580c2cc0.png)

**Describe the feature you'd like to see implemented**
In the F/CTL page on lower ECAM should appear in amber 

**References**

![image0](https://user-images.githubusercontent.com/70240330/93031991-200f7080-f62f-11ea-95b6-e55cbf112976.jpg)

**Additional context**

**Comment by Benjozork** [comment]
I will look into this.

**Comment by lukecologne** [comment]
It displays in amber when hydraulic pressure is insufficient. Since we do not have a hydraulics system currently, We would need to "fake" it by simply turning it amber when engines are stopped

**Comment by JackZ974** [comment]
Better to wait till the HYD system is implemented IMHO. It's in the works anyways

**Comment by wpine215** [comment]
Fixed with merged PR.
