### ISSUE TITLE
Cant start fs2020 with the a320nx

### ISSUE THREAD

**Issue by cabokid** [flybywiresim/a32nx#6601]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2022-01-08T01:22:50+00:00",
  "ref": "v0.7.4",
  "sha": "5adc0dc1ee3bd9cf9386c312b798a5f8ca7b391b",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

I select the a320nx and the airport. i press fly now, the games loads normaly. but whene i press fly now my screen freezes. and whenei check the task manager it says fs2020 wont respond.

### Expected behavior

I expect it to load

### Steps to reproduce

1. you select the a320nx
2. you select the airport and gate
3. press fly
4. wait to load
5. press fly now
6. screen freeses

### Discord Username (optional)

cabokid#9333

**Comment by nalgris** [comment]
I have such a problem. The community folder is empty. No other mods are installed.

**Comment by nalgris** [comment]
Solving the problem:

Step 1. Make a backup of the Community folder (or just rename it and create an empty one).
Step 2. Delete everything related to FBW in Application Data, including the installer.
Step 3. Run the installer and install the LATEST development build (not stable release).
Step 4. Launch the sim and choose the default FBW livery and launch the game.

The first download will be decent in time (15-20 minutes), but then it will load and everything will be OK.

**Comment by cabokid** [comment]
> Solving the problem:
> 
> Step 1. Make a backup of the Community folder (or just rename it and create an empty one).
> Step 2. Delete everything related to FBW in Application Data, including the installer.
> Step 3. Run the installer and install the LATEST development build (not stable release).
> Step 4. Launch the sim and choose the default FBW livery and launch the game.
> 
> The first download will be decent in time (15-20 minutes), but then it will load and everything will be OK.

I have done that but i didnt try it with the development built. I will let you know

**Comment by Zulunia** [comment]
Had a similar problem with the loadscreen getting seemingly stuck near/at the end. Tried several versions of the addon to no avail.
Solved by 
1. Removing the Addon from the Content Manager ingame (in the profile menu) as there was an entry for the 0.6 version from the store
2. Made sure all the base packages were up to date in the Content Manager (deluxe had an update, no idea if this was a factor
3. Deleting the flybywire-aircraft-a320-neo folder from the MicrosoftFlightSimulator\Packages\Community folder
4. Installed from the FlyByWire Installer (0.74 stable)
5. Restart the game and it properly loaded in after pressing 'fly now' (load time did take a couple of minutes)

**Comment by cabokid** [comment]
> Had a similar problem with the loadscreen getting seemingly stuck near/at the end. Tried several versions of the addon to no avail.
> Solved by 
> 1. Removing the Addon from the Content Manager ingame (in the profile menu) as there was an entry for the 0.6 version from the store
> 2. Made sure all the base packages were up to date in the Content Manager (deluxe had an update, no idea if this was a factor
> 3. Deleting the flybywire-aircraft-a320-neo folder from the MicrosoftFlightSimulator\Packages\Community folder
> 4. Installed from the FlyByWire Installer (0.74 stable)
> 5. Restart the game and it properly loaded in after pressing 'fly now' (load time did take a couple of minutes)

Still did not work...

**Comment by Saschl** [comment]
Please try this https://docs.flybywiresim.com/fbw-a32nx/support/reported-issues/?h=utf8#autopilot-fadec-electrical-systems-not-working-as-intended-utf8-issue

**Comment by cabokid** [comment]
> Please try this https://docs.flybywiresim.com/fbw-a32nx/support/reported-issues/?h=utf8#autopilot-fadec-electrical-systems-not-working-as-intended-utf8-issue
> 
> For quicker support please also join our discord :)

It worked thanks!
