### ISSUE TITLE
[EFB] Keep the ICAO METAR on front page (when inserted by hand)

### ISSUE THREAD

**Issue by Watsi01** [flybywiresim/a32nx#6602]
### Aircraft Version

Development

### Description

For Dev and Exp version: Right now, if you **_don't_** use SimBrief import on the EFB and type your departure and destination in by hand (METAR > front page of EFB), the EFB forgets the ICAO codes / METARs when switching to another page or turning the EFB off for a while during flight/session.

I would suggest to make the EFB remember this information during a session - when switching pages but also when turning the EFB off during the flight / the same session. The codes could be cleared automatically once the plane or MSFS is shut down.  

### References (optional)

Nope

### Discord Username (optional)

RogePete

**Comment by galtonova** [comment]
Yea this annoys me too. I switch between descent calculator and main page when transition alt comes and I need to enter airport code again to get QNH

**Comment by 2hwk** [comment]
Will fix this when able

**Comment by 2hwk** [comment]
Already solved in flypad v3
