### ISSUE TITLE
Main gear touchdown sound too quiet

### ISSUE THREAD

**Issue by jooglestumpe** [flybywiresim/a32nx#6604]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-01-27T05:34:39+00:00",
  "ref": "experimental",
  "sha": "d675fa2614b907735521a658b77c002481e87fe9",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

During the last sound changes in the experimental version, the main gear touchdown sound must have been extremley toned down or removed, as it is virtually impossible to hear it. I had quite a few landings now where I was holding the nose up thinking I'm still floating though the main gear was already on the ground without me noticing.

I don't know how much of this is intended, but I would appreciate bringing the old sound back. The new callouts are superbe however!

### Expected behavior

Main gear touchdown clearly noticible in the cockpit (soundwise)

### Steps to reproduce

Land anywhere

**Comment by hotshotp** [comment]
Is there a way to reproduce this? I'm 99% sure I didn't change it but I might have accidentally did something. I'll try to see what I did wrong soon

**Comment by doggydogg13** [comment]
I have the same issue for the gear touchdown sound

**Comment by scottfranks84** [comment]
Yeah I have notice this also. I just thought I was getting better at butter landings until I read this. Dam it haha. But yeah it’s a lot quieter now. Again not sure if intended.

**Comment by Watsi01** [comment]
Affirmative.

**Comment by andrejetcat** [comment]
also confirm that after the last changes some sounds are gone, unnoticable or change. same with the Spoiler sound.

**Comment by hotshotp** [comment]
Yeah looks like I got some bug fixing to do tonight with the touchdown sound and spoilers. I'll try something out tonight and maybe make a PR if I can figure out what's up with it
