### ISSUE TITLE
I freeze when I press the ready to fly button

### ISSUE THREAD

**Issue by mayerbalint** [flybywiresim/a32nx#6619]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2022-01-08T01:22:50+00:00",
  "ref": "v0.7.4",
  "sha": "5adc0dc1ee3bd9cf9386c312b798a5f8ca7b391b",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

When I press the ready to fly button my plane freezes. The memory spins up and runs at more than 99%!

### Expected behavior

Proper loading and flight

### Steps to reproduce

1.I choose the plane
2.I start it (I load it somewhere) 
3.I press a button ready to fly

### References (optional)

Uploading 2022-01-30 07-35-58.mp4…

### Discord Username (optional)

CRAZYL0O7ER#2177

**Comment by Saschl** [comment]
Solved via discord
