### ISSUE TITLE
Aircraft Turning Wrong Way

### ISSUE THREAD

**Issue by scotflieger** [flybywiresim/a32nx#6623]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-01-28T16:01:31+00:00",
  "ref": "experimental",
  "sha": "b79485d4d67b7e9c57a855925fdd1515c62822fe",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

When flying a test route from Edinburgh to Edinburgh (EGPH) the route displayed on the ND predicts a left hand turn at the return point. On reaching the end point the aircraft turned to the right before resuming the route.
 

### Expected behavior

The aircraft should turn in the direction of the ND displayed route. 

### Steps to reproduce

1. The A32NX was positioned on runway 24 at Edinburgh (**EGPH**). 
2. Select World Map.
3. IFR (High-alt airways) selected.
4. SID set to GOSAM1C.
5. STAR set to **INPI1E** for ILS runway 24.
6. No other route points added.
7. Click FLY.
8. Fly route with AP at any FL over 7000,
9. On approaching waypoint **INPIP**, ND displays left hand loop back towards **INREV**.
10. On reaching **INPIP** aircraft starts right hand turn (see attached file).
11. Aircraft returns to predicted track before **INREV**.

As mentioned in the experimental notes the flyPad / Sim Options / Sync MSFS Flight Plan was set to Save.

![ND WRONG TURN](https://user-images.githubusercontent.com/8685475/151707287-c4a9b87a-9328-4f5b-b066-67e26b113876.png)
.

**Comment by Benjozork** [comment]
As indicated on the known issues page, do not open GitHub issues for experimental. Use the discord support thread.
