### ISSUE TITLE
Unable to do 1 Engine taxi in

### ISSUE THREAD

**Issue by scottfranks84** [flybywiresim/a32nx#6624]
### Aircraft Version

Experimental

### Build info

```json
Experimental
```

### Describe the bug

I landed onto EGLL this evening and tried to complete a 1 engine taxi in. As soon as I shut engine 1 down the entire aircraft went into darkness and no engine sounds. From the outside view engine 2 was still running though. I started the APU and after a minute the aircraft came back to life visually however still no engine sounds although on the engine panel engine 2 was still running. Using my throttle I have engine 2 some power but no thrust came from it. I started both engines again and replicated. Aircraft behaved the same only this time not going into darkness as I kept the APU on.

### Expected behavior

I used to be able to perform 1 engine taxi’s in. I would expect that by shutting down 1 engine that the other would still be running, with thrust available and still proving electrical power to the aircraft. 

### Steps to reproduce

After starting both engines, do a little taxi then shut down 1 engine and see what happens. May only trigger after a landing I’m not so sure. 

### References (optional)

![693F3C3F-33BE-40D8-AA0F-09C3C55EC00F](https://user-images.githubusercontent.com/71073984/151717378-11d9bc33-46ab-4886-8da9-aedb340bff2b.jpeg)
![54778C3D-A04A-4357-A452-774BF72B7266](https://user-images.githubusercontent.com/71073984/151717383-f0b0cbd5-1c52-4037-9be8-2ed311731c60.jpeg)

### Discord Username (optional)

scottf#3530

**Comment by scottfranks84** [comment]
Just to elobrate, this happens when I shut down engine 1 every time. I have not replicated it by shutting down engine 2 instead

**Comment by tracernz** [comment]
SOP for single engine taxi is to shut down engine 2 and turn on Y elec pump. Not sure if the behaviour is correct though either way.

**Comment by scottfranks84** [comment]
> SOP for single engine taxi is to shut down engine 2 and turn on Y elec pump. Not sure if the behaviour is correct though either way.

Yeah I just saw an article about that. Makes sense but what I don’t get is why my engine 2 was still visibly running both outside and from the engine instrument but no sound or thrust

**Comment by derl30n** [comment]
Is this still an issue?

**Comment by scottfranks84** [comment]
I tried it again the other day and same thing happening. Turn off 1 engine taxiing in and the whole aircraft looses power from both engines.

**Comment by derl30n** [comment]
Can you please send us a screenshot of the ecam elec page when this issue is present (after you shut down the engine, and the ac looses power the ecam page may not be accessible), so a pic from the elec overhead panel may also be helpful.
Do you have by any chance a key bind that also turns off the elec gen?

**Comment by tracernz** [comment]
I can taxi in on engine 2 okay on dev (master):
![image](https://user-images.githubusercontent.com/9995998/162575580-03b12637-76cc-4ae2-b176-3433540c0d4b.png)

**Comment by tracernz** [comment]
Please do a re-install using the latest installer from https://flybywiresim.com/

**Comment by derl30n** [comment]
@scottfranks84 We have a [beginners guide](https://docs.flybywiresim.com/pilots-corner/beginner-guide/overview/) and a [full wiki](https://docs.flybywiresim.com/pilots-corner/) to help explain systems and procedures, also a [discord](https://discord.gg/UjzuHMU) server with people to help you understand if needed.
