### ISSUE TITLE
FBW A32NX Taxigeschwindigkeit

### ISSUE THREAD

**Issue by Pensi8911** [flybywiresim/a32nx#6628]
### Aircraft Version

Development

### Build info

```json
{
  "content": [
    {
      "path": "MSFSLayoutGenerator.exe",
      "size": 363520,
      "date": 132611232998667776
    },
    {
      "path": "SimObjects/AirPlanes/A320neo_LAUDAAAMA/aircraft.cfg",
      "size": 411,
      "date": 132725412457718550
    },
    {
      "path": "SimObjects/AirPlanes/A320neo_LAUDAAAMA/MODEL.main/model.cfg",
      "size": 277,
      "date": 132621991540000000
    },
    {
      "path": "SimObjects/AirPlanes/A320neo_LAUDAAAMA/TEXTURE.LAUDAAAMA/A320NEO_AIRFRAME_DECALS_ALBD.PNG.DDS",
      "size": 5592580,
      "date": 132642936760000000
    },
```

### Describe the bug

Wenn ich auf der Rollbahn bin und zum Gate will, wird die Taxigeschwindigkeit immer größer, ich muss immer bremsen.
was tun?

### Expected behavior

Lösung des Problems

### Steps to reproduce

ich wurde beim rollen zum Gate mit der Geschwindigkeit immer schneller

### Discord Username (optional)

pensi8911

**Comment by killyourradio** [comment]
_When I am on the taxiway and want to go to the gate, the cab speed is increasing, I always have to brake.
what to do?_

Brake in intervals to avoid going too fast. This is normal behaviour.

_Wenn ich auf der Rollbahn bin und zum Gate will, wird die Taxigeschwindigkeit immer größer, ich muss immer bremsen.
was tun?_

Zwischendurch runterbremsen und das Flugzeug wieder beschleunigen lassen. Ist auch so im echten Leben.
