### ISSUE TITLE
[BUG]Missing G/S and LOC indicator when using navidata from navigraph

### ISSUE THREAD

**Issue by Captain-Sushi021** [flybywiresim/a32nx#663]
**Mod Version**

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

**Comment by Benjozork** [comment]
Please respect the issue template.

**Comment by UncleClapton** [comment]
Is this problem occurring only with the mod? if not, then this is the wrong place to report this problem.

**Comment by August78** [comment]
I can attest to the loc and gs modes dont get announced only with the combo of a320nx mod AND the navigraph nav database. With navigraph nav database installed and not using the nx mod, the announciator works fine.

**Comment by lousybyte** [comment]
Not sure this is a game bug, Navigraph had a lot of fixes recently to their AIRAC data regarding ILS and G/S, can see the changes [here](https://forum.navigraph.com/viewtopic.php?f=14&t=10324) if you have an account, worth trying removing and reinstalling the newest data.

**Comment by Captain-Sushi021** [comment]
Indeed，when reinstalling the newest data，ILS worked~ thank you
