### ISSUE TITLE
vor dme

### ISSUE THREAD

**Issue by zww55** [flybywiresim/a32nx#6644]
### Aircraft Version

Experimental

### Description

Good afternoon. “What if I don't have access to Jefferson cards, then I can't do vor dme with 32 nx, which is often required at airports?”
Thakyou.

### Discord Username (optional)

zww55

**Comment by meta-system** [comment]
I'm not affiliated with FBW development. But if you're just looking for an alternative to Jeppesen, may I suggest chartfox.org? They have lots of charts already easily accessible, for free (you need a free Vatsim account). Alternatively, you can often manually google airports or official AIPs. 
Examples: [FAA](https://www.faa.gov/air_traffic/flight_info/aeronav/procedures/) [NATS](https://www.aurora.nats.co.uk/htmlAIP/Publications/2022-01-27-AIRAC/html/index-en-GB.html)

**Comment by zww55** [comment]
Seems good, i will take a trie after end flight to arlanda. Thank you very much!

**Comment by frankkopp** [comment]
> ### Aircraft Version
> Experimental
> 
> ### Description
> Good afternoon. “What if I don't have access to Jefferson cards, then I can't do vor dme with 32 nx, which is often required at airports?” Thakyou.
> 
> ### References (optional)
> _No response_
> 
> ### Additional info (optional)
> _No response_
> 
> ### Discord Username (optional)
> zww55

How is this a bug or issue of the A32NX?
I'm not seeing what we could do about it. 
Please close this. 
Thanks
