### ISSUE TITLE
Rollgeschwindigkeit

### ISSUE THREAD

**Issue by Pensi8911** [flybywiresim/a32nx#6648]
### Aircraft Version

Development

### Build info

```json
"content": [
    {
      "path": "Business.json",
      "size": 125,
      "date": 132884535858313630
    },
    {
      "path": "CUSTOMIZE/EDIT_REGISTRATION.psd",
      "size": 2306619,
      "date": 132884535858393630
    },
```

### Describe the bug

Die Rollgeschwindigkeit bei FBW A32NX wird immer schneller, obwohl der Schubregler auf 0 steht, dadurch wird das Flugzeug immer schneller, das ist bei anderen Flugzeugen nicht der Fall. Bitte um korrigieren des Fehlers.

### Expected behavior

Abstellung dieses Verhalten des Flugzeuges bei FBW im Programm.

### Steps to reproduce

Muss bei rollen vom Flugzeug FBW A32NX immer bremsen.

### Additional info (optional)

habe schon einmal eine Antwort erhalten, aber das war nicht befriedigend.
LG. erwin

### Discord Username (optional)

pensi8911

**Comment by tracernz** [comment]
This is not an error and in-fact matches the real A320neo with CFM LEAP-1A engines.

**Comment by aguther** [comment]
Wie bereits geschrieben handelt es sich hierbei nicht um einen Fehler, sondern um ein Verhalten wie es im echten Flieger anzutreffen ist. Die Piloten müssen daher auch immer wieder auf die Bremse steigen und bremsen z.B. auf 10 kn herunter. Es wird dabei nicht empfohlen, ständig auf den Bremsen zu bleiben, sondern wie bereits geschrieben auf 10 kn zu bremsen, dann das Flugzeug wieder auf 30 kn beschleunigen zu lassen und wieder zu bremsen.

Auch das weitere öffnen von Tickets wird daran nichts ändern und ich bitte daher davon abzusehen.

**Comment by Pensi8911** [comment]
Danke für die ausführliche Erklärung. Es hat mich nur gewundert dass dieses Verhalten nur bei FBW A32NX passiert, sonst nicht bei Boeing 787, 747 und auch nicht beim A320 Neo.
Vielen dank noch
Mfg. Erwin
