### ISSUE TITLE
Cannot Enter Flight Number on INIT Page

### ISSUE THREAD

**Issue by A320PHX** [flybywiresim/a32nx#6666]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-02-07T17:06:44+00:00",
  "ref": "experimental",
  "sha": "64a5f4297816d5e9895568c94dc2d5ba112269dc",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

Cannot import or manually input the flight number on the INIT page of the MCDU

### Expected behavior

That the MCDU takes the selected flight number. This was working before I updated the plane today.

### Steps to reproduce

1. Load up flight
2. Import flight from simbrief
3. Flight number not populated nor will it allow me to populate the field.

**Comment by NUTTTTTTTT** [comment]
enabling TELEX in the EFB should work as a temp workaround, a fix is already in the works with https://github.com/flybywiresim/a32nx/pull/6665

**Comment by A320PHX** [comment]
Enabling telex did the trick! Thank you!

**Comment by notl3ks** [comment]
I was wondering why I couldn't do this today. I had the same issue when preparing my flight, and I was scratching my head thinking what did I do. I'm on "1502efb" development.
