### ISSUE TITLE
Breakes temperature won't reset after restarting

### ISSUE THREAD

**Issue by Pedro-Pessoa** [flybywiresim/a32nx#6670]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2022-01-08T01:22:50+00:00",
  "ref": "v0.7.4",
  "sha": "5adc0dc1ee3bd9cf9386c312b798a5f8ca7b391b",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

When training landing (i.e. spawning in the air near to a runway), after about 3-4 lands, the brake temperature do not reset and start heating up. 

### Expected behavior

After landing, I always press `esc` then click on the `restart` button (`HOME` button is the default shortcut) and I expect the aircraft to be fully reset, including the brake temperature after the previous landing.

### Steps to reproduce

1. Spawn in the air near a runway
2. Do a few landings (usually 3-4)
3. Restart using the MSFS restart option
4. See the aircraft spawn with the brake temperature high

### References (optional)

Brake temperature after the third landing (fourth spawn)
![brake-temp](https://user-images.githubusercontent.com/3849946/152908296-a63b336e-70e6-4fa2-9c58-a9ad0a4df780.png)

Brake temperature warning after the fifth landing (sixth respawn)
![brake-temp-2](https://user-images.githubusercontent.com/3849946/152908371-b91a6d35-03e8-4b34-9544-7c2df66690eb.png)

### Discord Username (optional)

Pedro Pessoa#8177

**Comment by tracernz** [comment]
This is something the changed in sim updates. The aircraft state is no longer fully re-initialised by restarting the flight, which makes restart much quicker, but has these side effects.

**Comment by 2hwk** [comment]
Has been changed as of SU9 I'm not seeing this anymore
