### ISSUE TITLE
Not able to enter Flight Number

### ISSUE THREAD

**Issue by theaudience** [flybywiresim/a32nx#6675]
### Aircraft Version

Experimental

### Build info

```json
Current experimental
```

### Describe the bug

Entering of the Flight Number on the MCDU Init Page is not possible. Also applies for the new CPDLC Page. 

### Expected behavior

Entering the flight number is possible. 

### Steps to reproduce

Starting the Aircraft Cold & Dark. 
Switching Bat 1 & 2 on. 
Go to the Init Page in the MCDU. 
Enter DLH123 on the Scratchpad and press the line select key for the flight number. 
Contents of the Scratchpad disappears. 
Flight number is still empty. 

### Additional info (optional)

Flight number is also empty, when loading a Simbrief Flight Plan on the Init Page of the MCDU. 

### Discord Username (optional)

audience#2536

**Comment by svengcz** [comment]
This issue should be fixed with https://github.com/flybywiresim/a32nx/pull/6665
Try to update your A32NX.

**Comment by sidnov** [comment]
Closed via #6665
