### ISSUE TITLE
[REQUEST] HUD

### ISSUE THREAD

**Issue by Tankieboy** [flybywiresim/a32nx#668]
**Is your feature request related to a problem? Please describe.**

Not a problem

**Describe the feature you'd like to see implemented**

The implementation of a HUD, any plans, possible?

**References**

[https://www.youtube.com/watch?v=LqfCKdS7wkI](url)

**Additional context**

[https://www.flightglobal.com/airbus-u-turns-on-head-up-displays/42797.article](url)

**Comment by GodOfJapan** [comment]
Adding the HUD will be possible when we'll be able to edit the 3d model.

**Comment by Tankieboy** [comment]
Fantastic, thank you
