### ISSUE TITLE
ATC does not use the correct callsign on ground and after landing

### ISSUE THREAD

**Issue by ErikNL80** [flybywiresim/a32nx#6681]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-02-09T08:32:07+00:00",
  "ref": "experimental",
  "sha": "056b4356da3efd804615bd8fb352aa7277109ed8",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

Today I did a flight as "Air Portugal 3344". I started cold & dark and noticed ATC calling me "Airbus" instead. After departure ATC correctly calls me "Air Portugal 3344". When parked shut down engines and asking for ground services, ATC is calling me "Airbus" again.

### Expected behavior

I would expect ATC to use my callsign from C&D to shutdown.

### Steps to reproduce

1. Set-up an IFR flight 
2. Make sure you have entered a callsign and flight number
3. Start your flight C&D
4. Contact ATC and verify it is not picking up the callsign and flight number
5. Do a departure and verify ATC is using your callsign and flight number again
6. Land and park the aircraft, shutdown and ask for ground services and verify callsign and flight number not being used

### References (optional)
Here are some screenshot from a flight in the default livery, using default airports (Vueling 33):
[
![1](https://user-images.githubusercontent.com/71258178/153175407-de145ae6-28cd-44b2-8ec7-1a3c23968809.png)
![2](https://user-images.githubusercontent.com/71258178/153175443-687b4c67-0c16-40ed-b4f9-73e0365396b4.png)
![3](https://user-images.githubusercontent.com/71258178/153175467-984cc86a-4110-4e94-a1f4-cebf8db7435b.png)
](url)

**Comment by Watsi01** [comment]
Can confirm this. Came with the PDC/CPDLC implementation, I think.

**Comment by svengcz** [comment]
Will be fixed with https://github.com/flybywiresim/a32nx/pull/6685

**Comment by frankkopp** [comment]
Please use Development and test there before reporting issues on github. 

Please close this issue here - we do not yet want any github issues for Experimental at the moment as it is still in development.
This is also documented here: https://docs.flybywiresim.com/fbw-a32nx/support/exp/#how-to-report-issues

**Comment by derl30n** [comment]
Fixed in https://github.com/flybywiresim/a32nx/pull/6685
