### ISSUE TITLE
Approach Phase activating while in Hold

### ISSUE THREAD

**Issue by peterg928** [flybywiresim/a32nx#6683]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-02-09T11:37:19+00:00",
  "ref": "experimental",
  "sha": "0b621dce84226becf2c1d4cee1f2db05019ae223",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

If the approach phase activates in the hold (ie automatically because you fly near the purple D), the aircraft prematurely exits the hold. 

### Expected behavior

stay in the hold until either you exit or manually activate approach phase

### Steps to reproduce

1. enter a hold near an approach eg Jersey VOR on LELNA1J ILS 26
2. pass the approach phase activation
3. plane turns wrong direction and alters speed.

**Comment by frankkopp** [comment]
Please close this issue here - we do not yet want any github issues for Experimental at the moment as it is still in development.
This is also documented here: https://docs.flybywiresim.com/fbw-a32nx/support/exp/#how-to-report-issues
