### ISSUE TITLE
EFB Goes Dark When Loading Simbrief OFP

### ISSUE THREAD

**Issue by igormagun** [flybywiresim/a32nx#6686]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-02-09T19:25:26+00:00",
  "ref": "experimental",
  "sha": "240b01796df95f8d3ded6e9daa018abd89b776c3",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

Created a Simbrief OFP from LSZH to LOWI. Loaded into the A32NX, turned on the EFB, and shortly after I hit the "From Simbrief" button on the main page, the screen of the EFB goes dark. Hitting the power button on the EFB does not bring it back to life. I have been able to consistently recreate this 3 times in a row now.

### Expected behavior

The EFB should remain usable after loading the Simbrief OFP.

### Steps to reproduce

1. Load into the aircraft
2. Turn on the EFB
3. Hit the "Load from Simbrief" button.
4. Observe the EFB screen go dark after a second.

I'm not sure if any LSZH-LOWI flight plan will do or if something in particular is wrong about mine - you can reach out to me on Discord for my Simbrief ID if you need the exact OFP to recreate this.

### Discord Username (optional)

LazyEvul#1046

**Comment by frankkopp** [comment]
Experimental version has no support. Can you try to reproduce this on the development version and then come to the Discord support to have the team support you with investigating the issue. 
Also check other airports. We suspect the metar of one of the two airports is broken and causes the crash.

**Comment by derl30n** [comment]
Closing since no response
