### ISSUE TITLE
Plane glitches while turning on autopilot 

### ISSUE THREAD

**Issue by Paul5287** [flybywiresim/a32nx#6687]
### Aircraft Version

Experimental

### Build info

```json
Latest exp version
```

### Describe the bug

While on autopilot and making a turn the plane glitches for a few seconds and then continues flying correctly 

### Expected behavior

Smooth turns 

### Steps to reproduce

Autopilot armed. Following flight plan 

### Discord Username (optional)

Paul5287

**Comment by aguther** [comment]
Experimental version is not supported on GitHub. Beside that your issue is very unclear what you mean and what happens.
