### ISSUE TITLE
All monitors are black

### ISSUE THREAD

**Issue by icetigerCZ** [flybywiresim/a32nx#6695]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-02-11T09:59:05+00:00",
  "ref": "master",
  "sha": "9671d84d6646f08bdfb151aedb8b81a6f85199ec",
  "actor": "sidnov",
  "event_name": "manual"
}
```

### Describe the bug

BAT = no function
MCDU and monitors are black

### Expected behavior

![Snímek obrazovky (5)](https://user-images.githubusercontent.com/99480899/153590490-bca58214-36e1-47e7-ab32-06e46d1b197c.png)
![Snímek obrazovky (6)](https://user-images.githubusercontent.com/99480899/153590495-30b3083a-d41a-47c3-a720-c6306daab753.png)
![Snímek obrazovky (7)](https://user-images.githubusercontent.com/99480899/153590504-fc4fc8b7-0223-47bc-9605-1d289b5a801a.png)

### Steps to reproduce

Daily I updated FBW Dev version. I see this problem last days.

### Discord Username (optional)

icetigerCZ

**Comment by juancalvorotger** [comment]
Do you use the "Pilot/Copilot mod"?

**Comment by icetigerCZ** [comment]
Yes

**Comment by icetigerCZ** [comment]
Copilot mod was the problem.

**Comment by juancalvorotger** [comment]
You have to disable the mod till it's updated!
