### ISSUE TITLE
ILS info display button work but doesn't light up

### ISSUE THREAD

**Issue by noga-aviator** [flybywiresim/a32nx#67]
as you can see ils info is displayed but the button doesn't light up
![](https://cdn.discordapp.com/attachments/747526179640312019/747760814295089253/unknown.png)

**Comment by ocram9** [comment]
Mine is the exact opposite, the ILS info is disabled but the button is lit up.

![Screenshot_5](https://user-images.githubusercontent.com/49008532/91173837-bc082500-e6de-11ea-9a88-208851114c1f.png)

**Comment by miniarmagb** [comment]
sometimes it works sometimes it doesn't. Probably something Asobo may address

**Comment by ukflyer** [comment]
this issue seems to be related to turning up/down the panel brightness. The button works to show the ILS info but the button light isn't working correctly - it only changes with panel brightness and not when its selected.

**Comment by Curtis-VL** [comment]
Fixed in #451.
