### ISSUE TITLE
Remote MCDU not working

### ISSUE THREAD

**Issue by GrimGrandZero** [flybywiresim/a32nx#6703]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-02-11T17:18:17+00:00",
  "ref": "experimental",
  "sha": "77085f215ba5a4622898f678e76b1beab56df9b5",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

After reading through and trying out all troubleshooting suggestions in the remote MCDU guide, it still won't work for me.
Ports aren't occupied by something else, even with the firewall turned off completely, my ipad and phone won't connect. I tried several browsers. I tried different ports and sockets to no success.
It runs fine on the local browser on PC. 
Network discovery on PC is turned on. The devices are definitely on the same network.
Unfortunately, I'm out of ideas now.

### Expected behavior

Remote device to connect to MCDU

### Steps to reproduce

1. Run MCDU server
2. Start Flight Simulator
3. Connect remote device via browser

**Comment by ErikNL80** [comment]
Which browser are you using on the remote devices?

**Comment by GrimGrandZero** [comment]
Strangely it's working now after uninstalling NordVPN.
The VPN wasn't active, the app was even closed when I tried hooking up the MCDU.
A bit weird. Is there a way of making it work with that software installed?
