### ISSUE TITLE
CTD with Exp. Version

### ISSUE THREAD

**Issue by simson166** [flybywiresim/a32nx#6708]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-02-12T23:52:50+00:00",
  "ref": "experimental",
  "sha": "5577e11ccf53dcd9d16833bb407cbbe20fef63fe",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

Hello, since yesterday I always get CTD (already 3 times) with the exp. version during the cockpit preparation.
With the Dev. Version I can complete the flight to the end.
And for about 4 days now, the installer has been reporting "Download failed!" (for Dev. and Exp. version). However, when the installer is restarted, it reports that the latest version is installed.
Are these problems already known?
If it is necessary, I can send you the fdr files.

### Expected behavior

no CTD

### Steps to reproduce

1. Start Fly
2. cockpit preparation
3. CTD

**Comment by flieger28** [comment]
Have the same since yesterday. 3 times while boarding passengers and now as i entered FROM/TO into the MCDU

 "built": "2022-02-13T11:42:01+00:00",
  "ref": "experimental",
  "sha": "36232d9ef83af1df2ceff62167f2165940514898",
  "actor": "aguther",
  "event_name": "manual"

**Comment by Watsi01** [comment]
I'm flying the 3623.... without any problem. Did you try a clean install?
https://docs.flybywiresim.com/fbw-a32nx/installation/#clean-install-steps

Also pls try without any other mod or custom livery in your community folder (some liveries can cause problems).

**Comment by simson166** [comment]
Hi Watsi01,
Just did a clean install and was actually able to finish a full flight with the latest build "c6beeef" without any problems.
If flieger28 no longer has a problem, you could close this report.

**Comment by HWR-Micha** [comment]
Just out of curiosity: did you guys fly online with VATSIM (vPilot)?
