### ISSUE TITLE
[BUG] Controls Altitude and VS Not Working Properly

### ISSUE THREAD

**Issue by MatiasBordoy** [flybywiresim/a32nx#671]
**Mod Version**

0.2.0

**Describe the bug**

Some Controls doesn't work well in this plane.

**To Reproduce**

For example: Decrease Autopilot Reference VS - (CTRL + END)
                      Increase Autopilot Reference VS - CTRL + HOME

Those two controls, only shows changes in the AP if you first manually move the VS selector in the cokpit. Then you can use the Controls. 
But they are alyays actually changing the VS (and you don't see the value).

The Autopilot VS Toggle Key it's also not working.

Altitude controls have a weird behaviour. If you don't move the selector manually the first time, they doesn't do anything.
After you move the first time the selector, they start working and you can increase or decrease the altitude with the Control Keys.

But the control TOGGLER to activate/deactivate it is not working.

**Expected behavior**

It should be great to be able to manage the aircraft with custom controls, without needing to touch manually in the selectors.

**Actual behavior**

**References**

**Additional context**

**Comment by TMSergey** [comment]
A similar problem. It is not possible to change the altitude and vertical speed.

**Comment by lukecologne** [comment]
This may have been fixed in the newest release with our custom AP system. If this is still an issue in the newest release, please open a new issue.
