### ISSUE TITLE
TCA Flaps Mapping Randomly Changes

### ISSUE THREAD

**Issue by zoideberg8000** [flybywiresim/a32nx#6713]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-02-07T23:47:20+00:00",
  "ref": "experimental",
  "sha": "22647fcb2bc2f040368015c0ec9a49f6a42864d2",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

About half of the time the mapping for the flaps either stops working or changes positions. For example, I got an overspeed warning while descending into London but my speed was 250 kts at FL140. I realized the cause was that my flaps had gone to full while the lever was still at the 0 position. After experimenting i determined the assignment had changed to flaps full with lever at 0, for flaps 2 was lever at 3, for flaps 0 was lever at full , and there did not seem to be an assignment for flaps 1 or 2, and lever at 1 and 2 did not do anything. The parking break and rudder trim which are on the same part were both working. This has happened intermittently. Additionally, sometimes the mapping does not work at all. this only affects landing and typically after a longer flight. As mentioned, I have this issue about 50% of flights. When it occurs, about 75% of the time the mapping does not work (moving the lever does nothing) and the other 25% of the time the mapping changes but randomly, not always as experienced today. 

### Expected behavior

Flap lever setting and flaps in sim should agree.

### Steps to reproduce

On descent, use Thrustmaster TCA (Airbus with add on) and see if mapping is retained.

**Comment by aguther** [comment]
Check for any double bindings, this is not a commonly known issue.

**Comment by brenosilver** [comment]
This happens to me every time I pause the sim with ESC. When I come back the flaps go to full and speed brakes are activated. Very annoying.

**Comment by tracernz** [comment]
Hmmm... this happens with dev tools since a few sim updates ago but I haven't seen it in normal user menus (esc/pause etc.).

**Comment by aguther** [comment]
> This happens to me every time I pause the sim with ESC. When I come back the flaps go to full and speed brakes are activated. Very annoying.
> 
> edit: I don't have TCA flaps, Only throttle. Experimental branch.

That is a sim issue sending events with 0.

**Comment by overgee** [comment]
This issue used to appear to me when using TCA throttle quadrant only. It happened to all MSFS aircrafts, it was not specifically an issue with the FBW A32NX. Thus, it seems likely to be a problem with MSFS. Since I connected the Thrustmaster flaps add-on to the throttle quadrant the problem would not have reappeared.

**Comment by zoideberg8000** [comment]
> Check for any double bindings, this is not a commonly known issue. If it would be we would see a ton of reports.
> 
> The flap settings are always processed in the same way, there is no way to configure it. But there are multiple events that the sim might send. Therefore ensure everything is configured properly.

I confirmed I don't have multiple bindings. I should note that unplugging the quadrant and plugging it back in fixes it. I also checked the quadrant configuration while it was happening and confirmed it was working as expected outside the sim.

**Comment by aguther** [comment]
MSFS issue.
