### ISSUE TITLE
Add option to EFB for interior lights potentiometer default states

### ISSUE THREAD

**Issue by GrimGrandZero** [flybywiresim/a32nx#6723]
### Aircraft Version

Experimental

### Description

I would love to have the option to load up the aircraft with all interior light potentiometers in the medium or high settings.
It is becoming very tiring to dial them up all the way with every new flight via the mouse wheel. 
So it would be great to have the option of defining the desired default state for those or having a state saving function similar to the JustFlight Piper Arrows.
Either that or a dramatic speed / sensitivity increase when using a mouse wheel would be well appreciated.

**Comment by GrimGrandZero** [comment]
Shameless bump....

**Comment by 2hwk** [comment]
Already partially completed in FlyPad OS 3, although there is some setup required. You can create a lighting preset with the desired lighting conditions, Still lacking an automatic load by default option.

**Comment by SpiritZephyr** [comment]
I'd be interested in trying to implement the auto load functionality as a first issue if not already done.
