### ISSUE TITLE
Spoilers can be deployed with no source of power

### ISSUE THREAD

**Issue by FreshDave29** [flybywiresim/a32nx#6726]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-02-15T06:29:18+00:00",
  "ref": "master",
  "sha": "b8d21d99a50c2063bb08b0272bc1fd1d1e821fe0",
  "actor": "Benjozork",
  "event_name": "manual",
  "pretty_release_name": "master:b8d21d99"
}
```

### Describe the bug

Spoilers are moved despite aircraft has no hydraulic source powered - engines and APU are off, elec. pump off.

### Expected behavior

No spoilers actuated similar to flaps.

### Steps to reproduce

Start C&D
Move Spoiler lever
See spoilers deploy magically

### References (optional)

![1](https://user-images.githubusercontent.com/72436866/154034261-9c103af9-86b2-42b1-b9c0-9371410fa3c8.png)
![2](https://user-images.githubusercontent.com/72436866/154034266-9776e1f2-0b9a-42cc-b94f-d72db603b624.png)
![3](https://user-images.githubusercontent.com/72436866/154034311-2a1aaa50-7bf3-439e-be29-47ae9474479b.png)
![4](https://user-images.githubusercontent.com/72436866/154034314-6737830d-7765-428b-b059-a3da21fac3cd.png)

**Comment by tracernz** [comment]
Duplicate #1555. This is not so much a bug as not implemented yet (Davy is actively working on it the last couple of weeks actually).
