### ISSUE TITLE
EFB Not Importing Latest SimBrief Flight Plan

### ISSUE THREAD

**Issue by jaymo10** [flybywiresim/a32nx#6728]
### Aircraft Version

Development

### Build info

```json
"built": "2022-02-04T13:17:19+00:00",
  "ref": "master",
  "sha": "191cdba3a2f447b0332b64fa3c4b1992984774d6",
  "actor": "IbrahimK42",
  "event_name": "manual"
}
```

### Describe the bug

EFB- I imported a Simbrief Flt Pln, KSFB-KEYW , as usual a while ago-completed flight, no problems. Few days later, I went to import another SImbrief Flight Plan in EFB, but it loads up the old flight plan KSFB-KEYW over and over, even though Im trying to load KGSP-KORF!.  Been trying for days to import a new flight plan, but i get same old flight plan in EFB and MCDU! How do I get rid of that? Seems like it's hung up in the EFB.

### Expected behavior

To be able to import a fresh Flight Plan from Simbrief into the EFB. .

### Steps to reproduce

load a  Simbrief Flt Pln in EFB.

### Additional info (optional)

was working , say a few weeks ago..

### Discord Username (optional)

jaymo

**Comment by frankkopp** [comment]
Try this:
https://www.simbrief.com/api/xml.fetcher.php?username=<YOURSIMBRIEFUSERNAME>

If this also shows the old OFP then it is an issue on simbrief side or your side (not generating a new plan maybe)?

If this shows the new OFP but the aircraft shows the old one I would be very very surprised but we then will need to look into it further.

**Comment by ErickSharp** [comment]
Any word on this? Have you tried what @frankkopp suggested?

**Comment by derl30n** [comment]
Closing since no response
