### ISSUE TITLE
[REQUEST] Holding

### ISSUE THREAD

**Issue by sepiroth887** [flybywiresim/a32nx#673]
**Is your feature request related to a problem? Please describe.**
Selecting waypoints in the MCDU shows a HOLD button which is not working further. 

**Describe the feature you'd like to see implemented**

It should allow to be depressed and then enter hold details such as entry pattern, turn direction, `time/distance etc.
[as shown here](http://www.a320dp.com/A320_DP/nav-flight-management/sys-14.8.17.html)

**References**

[A320 MCDU Hold](http://www.a320dp.com/A320_DP/nav-flight-management/sys-14.8.17.html)

**Additional context**

**Comment by Gusineas** [comment]
Any updates so far? :)

**Comment by Benjozork** [comment]
@Gusineas holding will be supported in the future after the custom autopilot system makes it in

**Comment by MisterChocker** [comment]
Duplicate of #1443

**Comment by angry-bender** [comment]
Still Open, including in Dev Autopilot Version 6.0.0, @MisterChocker , Not yet implemented

**Comment by SandaleAir** [comment]
Any Updates at this function.

**Comment by svalencia014** [comment]
Any updates?

**Comment by tracernz** [comment]
> Any updates?

https://twitter.com/FlyByWireSim/status/1463557442487439364

No ETA as always.

**Comment by martwana** [comment]
It's been a while since the demo video was put on social media and it showed that the hold pattern worked pretty well. Do we have any kind of update now?

**Comment by Benjozork** [comment]
It already works for holds embedded in procedures on experimental and manual holding just requires a few more fixes

**Comment by martwana** [comment]
@Benjozork could you explain a little further then on how to activate a hold. I'm using latest experimental and cannot figure out how to activate it. 

For example, my home airport is EGPF (Glasgow) and say I'm using the RIBEL1G STAR. It has a documented hold at LANAK in the charts. The HOLD option is grey on my FMC when pressing the button next to LANAK. 

I'm sure I did try this one time and had it working.

**Comment by Benjozork** [comment]
When I said embedded in procedures I meant part of the routing. That hold is optional, thus it's a databse hold - something not possible at all with MSFS navdata.

The option to manually hold is not available right now. It is being worked on.

**Comment by martwana** [comment]
Okay thank you for clarifying. Have been doing them manually until now so can continue doing that.

**Comment by wpine215** [comment]
Now in master branch.
