### ISSUE TITLE
[MCDU] Rare RAD NAV page crash due to bad VOR freq

### ISSUE THREAD

**Issue by vkrizan** [flybywiresim/a32nx#6735]
### Aircraft Version

Development

### Build info

```json
commit hash: 97c254905ea72fcd4c2c475f226e7dadae2eb773
(apologies, I haven't captured the build info)
```

### Describe the bug

MCDU RAD NAV page breaks in very rare cases when incorrect VOR frequency is received, possibly due to race condition.
```
TypeError: undefined is not an object (evaluating 'mcdu.vor1Frequency.toFixed')`
```

![IMG_20220129_230259](https://user-images.githubusercontent.com/7695766/154270538-cfa86d71-bed4-47fc-a26b-62e167e18d47.jpg)

This happened to me during Simbrief route (`EDDH` -> `LKKV`) import while adding `KVY` dme to VOR1 box. Note, that `KVY` does not exist in msfs (or was not able to be retrieved as VOR).

### Expected behavior

MCDU to either show message "NOT IN DATABASE" or assign correct VOR/DME freq.

### Steps to reproduce

(intermittent)
1. Prepare route from `EDDH` to `LKKV` on Simbrief,
2. Request Simbrief import on INIT A page,
3. Immediately go to RAD NAV page and input `KVY` for VOR 1.

### Additional info (optional)

With sentry.io this might be capture better if it ever happens for anyone else.

### Discord Username (optional)

coolll.sk#0022

**Comment by frankkopp** [comment]
Can' reproduce - btw. KVY is an ILS and not a VOR - you can only enter it into VOR with the frequency.
If you enter it in the ILS field as KVY it works.
See video. 
I'm using Navigraph data - do you have the latest Navigraph AIRAC?

Tested on "master:bbb804a8" - maybe you should update to this version and try again to reproduce yourself. Add additional info like Community folder empty yes/no (apart a32nx, Navigraph), other 3rd party off (e.g. YouControls, etc.)

How rare is it for you? I tried several times and could not reproduce.

https://user-images.githubusercontent.com/16833201/154368092-f3f1ec0d-e665-49d8-abc9-2a5f029db703.mp4

**Comment by tracernz** [comment]
I'm wondering if this is associated with some other failure, where the FMCMainDisplay didn't fully init, as the vor1Frequency is always a number after the first init. Nonetheless it still makes sense to make the rad nav code more robust and I beleive Frank has prepared a patch for this.

**Comment by vkrizan** [comment]
Thanks @frankkopp for taking a look. I can certainly retry and find some reproducer. I'm worried that if this is a race condition, it would be hard to find. It only happened only once. I only have default AIRAC from msfs, and multiple mods present in the Community folder.

This happened to me a while ago, but as you've discovered that the `KVY` can be put into ILS I'm remembering that it happened right after selecting departure and/or destination rwy. I suspect it could have happened during auto-tune of ILS while me putting `KVY` into VOR1.

@tracernz indeed, I do not know how the `undefined` got there, hence my guess with race-condition with other facility data/freq retrieval. Definitely protection on `undefined` value there would prevent the crash. Not sure if it would protect it from other undefined state.

Feel free to keep this as reference. I'm also okay with closing this. Just wanted to capture it.
Thank you all.

**Comment by frankkopp** [comment]
> This happened to me a while ago, but as you've discovered that the `KVY` can be put into ILS I'm remembering that it happened right after selecting departure and/or destination rwy. I suspect it could have happened during auto-tune of ILS while me putting `KVY` into VOR1.

That's good info - I can re-test it with this information.
