### ISSUE TITLE
[BUG] MCDU > PERF TAKE OFF > FLAPS/THS input not limited, Vspeeds implausible

### ISSUE THREAD

**Issue by chkgk** [flybywiresim/a32nx#674]
**Mod Version**

master

**Describe the bug**

Possible bug: The MCDU > PERF > TAKE OFF page allows entering values for the FLAPS setting which are not in {0, 1, 2, 3, 4}.
Clearly, this is low priority.

**To Reproduce**

1. Go to the TAKE OFF PERF page on the MCDU
2. Enter a value > 4 (preferably 99) for the FLAPS.
3. Press v1 twice to set v1 to an automatically calculate value.

**Expected behavior**

Flaps should not be allowed to be set to values outside of {0, 1, 2, 3, 4}. Attempting to do so should result in an invalid entry error.
If however values larger 4 are deemed okay (I am lacking reference material), V speed calculation should not be possible.

**Actual behavior**

Settings larger 4 are accepted and Vspeed calculation is attempted.

**References**

In-game screenshot of the issue:
![Image of issue](https://ckgk.de/screens/flaps99_vspeeds.png)

Snippet from A320 non-neo reference material:
![A320 non-neo refeence](https://ckgk.de/screens/flaps_ref.png)

**Additional context**

In A320 reference material I found that this info is only for reference and no input limits are given. So, it is not a big issue in terms of realism. However, currently the setting is used for the QOL feature that allows automatic calcilation of Vspeeds. With wrong flap settings, the Vspeeds are also implausible. So I think the input on the flap page should be limited.

Related: No input is accepted for the /THS part, but I get that it is just not implemented, yet.

**Comment by UncleClapton** [comment]
I'll be honest. the result of this is hilarious.

I can look into this one.

**Comment by UncleClapton** [comment]
THS technically should be implemented as at least a display value. If it's not inputting correctly then I can look into that too

**Comment by UncleClapton** [comment]
Looked into the code. right now the input parser only accepts the specific formats `UP X.X` or `DN X.X`. I can correct this as well.

**Comment by PCGamesF1Tech** [comment]
FYI:
Flaps 0 ("Up") and Flaps 4 ("Full") are NOT takeoff flap settings! 
Only {1,2,3}

**Comment by chkgk** [comment]
Thank you for the correction, PCGamesF1Tech.
Entering FLAPS and THS simultaneously as `1/UP1.5` for example works. I can also edit the value by re-entering both values.
Should it be possible to edit these indivdually? Like entering `/UP2.0`? If so, that does not work (but might not be intended to work - I just do not know).

**Comment by UncleClapton** [comment]
right now the code requires a flaps input. I can change this quite easily, though.

Is there limits for THS as well?

**Comment by PCGamesF1Tech** [comment]
Hi,
yes, we enter the flap setting (e.g. 1) during preparation, so just hit 1 and then LSK for the line. 
When the Loadsheet arrives we put in the trim setting (hit "/" then the numbers "0.5" and then the same LSK) which will be crosschecked after engine start when it is actually set with the trimwheel as the hydraulic is working now)

**Comment by PCGamesF1Tech** [comment]
Ah, one thing just came to my mind:
On newer aircraft there is a check function for the actual flap setting vs. the flap setting on perf page when pressing T.O.Config/actual Takeoff. 
If it's not identical an amber caution "F/CTL FLAP/MCDU DISAGREE" is triggered.
Keeping this in mind it makes sense to limit the MCDU flap entry to {1,2,3} only

**Comment by UncleClapton** [comment]
> I don't know of any (you mean on Perf page?), can check the manuals if required...?
Should be within green range on trim wheel for takeoff obviously...
@PCGamesF1Tech 

I think I'll set the THS limit to 2.5 and we can easily change it if someone makes a (valid) complaint.

**Comment by PCGamesF1Tech** [comment]
Corresponds to the green range, should be ok 👍🏻 (just checked a photo online, don't know however if this was from a neo or if all 3xx have the same wheel...)
