### ISSUE TITLE
Option to sync captain and first officer FD/LS/baro controls

### ISSUE THREAD

**Issue by tracernz** [flybywiresim/a32nx#6744]
### Aircraft Version

Development

### Description

Add an option to sync the FD, LS, baro controls, and anything else the makes sense between captain and first officer sides for single pilot ops in the sim.

Relates to https://github.com/flybywiresim/a32nx/issues/6717 for the baro correction knobs.

**Comment by Eagle941** [comment]
Taking this task as first contribution

**Comment by frankkopp** [comment]
@tracernz wouldn't that go against the "must be in the real aircraft" paradigm?

https://docs.flybywiresim.com/dev-corner/dev-guide/contribute/#references-material-real-life-aircraft

**Comment by Eagle941** [comment]
Stricly speaking yes, which is why the option is disabled by default. Secondly, in the simulator it's not as easy as extending your arm to press the opposite side switches.

**Comment by NathanInnes** [comment]
I see this as a good ease of life feature.
