### ISSUE TITLE
SID / STAR entering wrong behaviour

### ISSUE THREAD

**Issue by MicahBCode** [flybywiresim/a32nx#6745]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-02-17T06:05:45+00:00",
  "ref": "experimental",
  "sha": "4927ace0e17cbc397f6bc2dc3635ecd808e9d23a",
  "actor": "aguther",
  "event_name": "manual",
  "pretty_release_name": "experimental:4927ace0"
}
```

### Describe the bug

Example: LOWG - LSZH via ABIRI DCT ERKIR L608 KPT L856 NEGRA
Before getting clearence I entered the route in the FMC. Therefore using Init Page entering "LOWG/LSZH". Afterwards heading to Flightplan page. Here I select LOWG and then enter next waypoint "ABIRI". Afterwards I enter the rest of the route.

Now, when entering the SID via LOWG -> Departure -> RWY 16C -> ABIRI4G it enters the SID in but instead of connecting the SID with the route like so:
WG607 ABIRI ERKIR ... it enters WG607 ABIRI ABIRI ERKIR or sometimes (e.g. in LSZH departure DEGES4L) it entered {SID} DEGES FPLN DISC DEGES ...

Entering the STAR has wrong behaviour as well.
When entering a star ending at another waypoint than an IAF it should add a flightplan discontinunity between the star and the approach.

instead when the last waypoint of the STAR matches the first waypoint of the approach it should connect them according the SID behaviour.

### Expected behavior

Connecting waypoints if they match otherwise add a flightplan discontinunity in between.

### Steps to reproduce

Stated above in the bugs description

### Discord Username (optional)

Micah#3002

**Comment by Benjozork** [comment]
This will be fixed in version 2 of the custom FMS.

**Comment by tracernz** [comment]
We are not taking issue reports for experimental on github, but rather in the Discord thread so I'll close this for now. As noted above we are already looking at the issue.
![image](https://user-images.githubusercontent.com/9995998/154797428-72ba3bca-e698-4dba-b658-ec33298272e1.png)
