### ISSUE TITLE
MCDU Flight plan completely erasing during flight

### ISSUE THREAD

**Issue by jnmonks47** [flybywiresim/a32nx#6747]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-02-18T07:12:42+00:00",
  "ref": "experimental",
  "sha": "85a6c86bb31360dc9dfd381eb3d51b8deee1e868",
  "actor": "aguther",
  "event_name": "manual",
  "pretty_release_name": "experimental:85a6c86b"
}
```

### Describe the bug

MCDU Flight plan erasing during flight. Happened three times consecutively now. 
Latest flight, flight plan completely erased on SID approx 3 minutes after takeoff. 
Previous flight, plan erased on STAR into LSGG. 

### Expected behavior

Flight plan not to erase randomly 

### Steps to reproduce

1. Enter flight plan on MCDU. 
2. Depart and fly
3. Random flight plan erase at different stages of flight. Seems to be more on SIDs and STARs

### Discord Username (optional)

jnmonks47

**Comment by Benjozork** [comment]
We are aware of this issue

**Comment by tracernz** [comment]
We are not taking issue reports for experimental on github, but rather in the Discord thread so I'll close this for now. As noted above we are already looking at the issue.
![image](https://user-images.githubusercontent.com/9995998/154797428-72ba3bca-e698-4dba-b658-ec33298272e1.png)
