### ISSUE TITLE
QNH not blinking when passing transition alt or transition level

### ISSUE THREAD

**Issue by Mitch00783** [flybywiresim/a32nx#6749]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-02-17T23:17:18+00:00",
  "ref": "master",
  "sha": "591fcd2d0de71ff78e28dfd7e4bef3c5f941130a",
  "actor": "Benjozork",
  "event_name": "manual",
  "pretty_release_name": "master:591fcd2d"
}
```

### Describe the bug

QNH not blinking/flashing when passin TA or TL on PFD

Transition Altitude is always set on the PERF page (MCDU)

Tried to remove all the add-on from the community folder and re-installing the A32NX

Exept that, everything is working just fine :)

### Expected behavior

QNH should flash passing TA on climb
STD shuold flash passing TL on descent

### Steps to reproduce

1- Load flight plan from Simbrief
2- Set Transition Altitude on MCDU-PERF page takeoff and approach

**Comment by tracernz** [comment]
Do you have menu animations enabled in MSFS settings?

**Comment by Mitch00783** [comment]
> Do you have menu animations enabled in MSFS settings?

Spot on Sir !! menu animations was disabled in MSFS setting

Thanks a lot  for your help

**Comment by tracernz** [comment]
I'll make a patch, so re-opening this for now..
