### ISSUE TITLE
Coloured METAR text is sometimes too hard to read

### ISSUE THREAD

**Issue by jaoord** [flybywiresim/a32nx#6751]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-02-18T14:19:26+00:00",
  "ref": "master",
  "sha": "493040807cfbbf1c22f7196c7f2b2de423892faf",
  "actor": "davidwalschots",
  "event_name": "manual",
  "pretty_release_name": "master:49304080"
}
```

### Describe the bug

Pull request #6620 added colored METAR in the EFB.
For me as a colourblind person (and maybe others too), the red text is sometimes too hard to read in certain conditions.

### Expected behavior

Text is readable.

### Steps to reproduce

1. start flight 
2. request metar in efb
3. under certain weather/time of day conditions the text get too hard to read

### References (optional)

Screenshots taken at EHAM rwy 24. Can't zoom in further in MSFS

![Screenshot (1964)](https://user-images.githubusercontent.com/6464609/154722794-e1289ae0-c730-4231-81dd-a8235a5dd3ee.png)

![Screenshot (1965)](https://user-images.githubusercontent.com/6464609/154722777-5db21d2d-10c7-48ef-9462-d15ba2a6f52e.png)

**Comment by frankkopp** [comment]
For you as a color blind person would it be better to simple have everything as before or would a lighter red work?
We could add an option in the settings to toggle old style vs. colored.

**Comment by jaoord** [comment]
I think the colours are a nice addition. I think why I have a hard time reading it is because there's not enough contrast between the background colour and the text colour. So maybe your suggestion of a lighter colour would work.
I later found an option in the EFB to increase the brightness but unfortunately that doesn't solve it.

**Comment by frankkopp** [comment]
> I think the colours are a nice addition. I think why I have a hard time reading it is because there's not enough contrast between the background colour and the text colour. So maybe your suggestion of a lighter colour would work. I later found an option in the EFB to increase the brightness but unfortunately that doesn't solve it.

I will look into it. Are you on Discord and may I sent you example images (or even test versions) so you can judge if it works for you?

**Comment by jaoord** [comment]
Yep, speedy#0413
