### ISSUE TITLE
EFB Typing Issue Causing Uncontrol of Camera and Aircraft

### ISSUE THREAD

**Issue by TGP246** [flybywiresim/a32nx#6753]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-02-17T17:54:51+00:00",
  "ref": "experimental",
  "sha": "758a1263ccfc078281180742c6593a20d744459b",
  "actor": "aguther",
  "event_name": "manual",
  "pretty_release_name": "experimental:758a1263"
}
```

### Describe the bug

Found a VERY annoying little thing today and I think I know the cause. So it's not technically a bug but whenever you type in the FlyPad, it disables you from interacting with anything else because when you're typing you don't want buttons to get pressed in the cockpit etc. I was putting in some TOD calculations and had clicked the type box to put in altitude but then I switched my camera and didn't click outside of the type box. This lead me to looking away from the FlyPad and not being able to click outside to stop typing so any keyboard shortcuts were not working for camera changing nor my sidestick for controlling the aircraft. Somehow my curser disappeared and I couldn't manually switch anything through the tool bar. I tried going into the developer mode but nothing fixed it. There was no way I could get out of the type box on the FlyPad, therefore leading to nothing else responding on the aircraft. There was nothing I could so I had to quit towards the end of a long flight.

### Expected behavior

I expected to be able to control the camera when typing on the FlyPad.

### Steps to reproduce

1) Click a type box on the FlyPad.

2) Move the camera to where you're not looking at EFB (I did it via the camera toolbar since keyboard shortcuts and mouse dragging do not work while typing)

3) Because you are "typing" any keyboard shortcuts, mouse movements, and sidestick/yoke & throttle controls do not respond therefore making it impossible to look at the EFB to disable typing.

4) When "Freelook" and "Fixed look" are clicked on the camera toolbar, curser disappears and no mouse, keyboard, or peripherals respond because it is "typing"

### Discord Username (optional)

TGP246#0655

**Comment by aguther** [comment]
Well it’s always how you see it. When we didn’t have it, people changed their rudder leading to AP disconnects when entering numbers because every binding of the sim was then still active. Now it’s not active and now we have other complaints. What solution do you suggest to fit both?

**Comment by TGP246** [comment]
I honestly don't know what could be done. It doesn't really need to change because this was the first time it's happened to me but when it does occur, there is nothing you can possibly do to continue flight. A little frustration when it happens. I suppose the only fix would be to be careful when changing camera while typing since camera operation and active buttons mapped to the aircraft cannot be separated.

**Comment by Saschl** [comment]
Once locked out you can always do this as a last measure: https://docs.flybywiresim.com/fbw-a32nx/support/reported-issues/#mouse-lock-caused-by-efb-input-field

But I'm a bit confused on how it happens, I was under the impression that no camera change is possible once the input is locked. But it is possible via the toolbar?

**Comment by TGP246** [comment]
> 

Correct, once you're locked on the input, camera cannot be moved with mouse or keyboard shortcuts. It can however be moved with the camera toolbar and that is what happened to me, I never clicked outside the input box and moved my camera through the toolbar and got locked out of controlling the aircraft and camera. Thanks for that link. I will recreate the issue once more and try the console command resolution.

**Comment by tracernz** [comment]
I think we may be able to determine when the camera moves by more than a set threshold and unfocus input fields (EFB and MCDU) in that case.

**Comment by ErickSharp** [comment]
> I think we may be able to determine when the camera moves by more than a set threshold and unfocus input fields (EFB and MCDU) in that case.

I was thinking this as well, but the question is where do we put it? Ideally we just put it in somewhere that is always in scope that triggers the coherent unfocus event but I'm not sure where that place is.

**Comment by grandfred29** [comment]
Hello, i had this problem this evening, After 5 hours i was decending to my destination, during this descente i need to check distance to a certain altitude with the efb. Follow a total freeze of the cockpit, plane continue to follow descent and Flight path but i wasn't able to change view, altitude, and my physical command bravo and alpha throttle were inresponsive too. By chance i was able to return to efb by caméra shortcut and plane became controlable.
Thanks, i use the experimental version.

**Comment by 2hwk** [comment]
> I think we may be able to determine when the camera moves by more than a set threshold and unfocus input fields (EFB and MCDU) in that case.
> 
> I was thinking this as well, but the question is where do we put it? Ideally we just put it in somewhere that is always in scope that triggers the coherent unfocus event but I'm not sure where that place is.

My solution for this problem with the MCDU Keyboard input function was to firstly make the entire screen a focus-able element so that you can easily unfocus when needed, and also to set a timeout upon the last key press that would send the unfocus event if no input was detected for a set amount of time.

**Comment by aguther** [comment]
Barley seen further reports and therefore closing it. Feel free to reopen when needed.

**Comment by gandalfthewhite19890404** [comment]
Issue is persist, encountered yesterday
