### ISSUE TITLE
distance Disagree on ND and MCDU

### ISSUE THREAD

**Issue by cqhhy2001** [flybywiresim/a32nx#6757]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2022-01-08T01:22:50+00:00",
  "ref": "v0.7.4",
  "sha": "5adc0dc1ee3bd9cf9386c312b798a5f8ca7b391b",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

distance on ND(5NM) and MCDU( 3855MM) disagreed but the path graph is correct.
![image](https://user-images.githubusercontent.com/21079967/154800428-b94df307-33ea-4c9d-ad08-de8a9b68f6da.png)
![image](https://user-images.githubusercontent.com/21079967/154800436-2dd870f0-edc3-459b-bbd9-0f3d1a59e2ee.png)

### Expected behavior

they should sync the correct value

### Steps to reproduce

enter Departure and Destination on MSFS using built-in map
choose the departure and arrivals using built-in map
use default path generated by MSFS
start the aircraft as usual

**Comment by tracernz** [comment]
Technically a valid bug... but the MSFS flight plan manager and guidance has long since been replaced in the development (master) and experimental versions so there's really nothing we will do here, other than release a new stable version 0.8 based on the current development when ready.
