### ISSUE TITLE
CPDLC Active ATC not recognized if ATC respond after timeout 

### ISSUE THREAD

**Issue by fsxmanu** [flybywiresim/a32nx#6759]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-02-19T08:26:20+00:00",
  "ref": "experimental",
  "sha": "6e6dc9f25a77a73bb2b43df0189fff31e9dca59a",
  "actor": "aguther",
  "event_name": "manual",
  "pretty_release_name": "experimental:6e6dc9f2"
}
```

### Describe the bug

I sent a logon request via CPDLC to EDWA Center and they did not respont in the 5 minutes so the request times out and I got the usual fail message. However I received a "Logon Accepted" Message about a minute later and the CPDLC device showed me that EDWA is my current ATC. My MCDU did not recognize that and showed me that I don't have an active ATC. So now I can't choose "All ATC Disconnect " 
![image](https://user-images.githubusercontent.com/22397350/154805391-836f0bce-7ae3-4ebc-bbb6-2c10198c5c0f.png)

### Expected behavior

After the Timeout, either no accepted logon message can be received or the MCDU has to recognize the active ATC too.

### Steps to reproduce

1. Request logon on a Vatsim controller during flight
2. Wait/Hope the request times out
3. Get the controller to accept it after the timeout

### Discord Username (optional)

CucumberBush#9167

**Comment by svengcz** [comment]
You can send the notification a second time as a temporary workaround.
Will be fixed with one of the upcoming PRs

**Comment by fsxmanu** [comment]
@svengcz alright. Should we leave this issue open for others to see if they have the same issue? Or should we close it?

**Comment by svengcz** [comment]
Let's keep it open until it is fixed.

**Comment by svengcz** [comment]
Should be fixed with the last CPDLC PR
