### ISSUE TITLE
"MACH SEL" Display Issue

### ISSUE THREAD

**Issue by jpccaldas** [flybywiresim/a32nx#6774]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-02-19T18:40:18+00:00",
  "ref": "experimental",
  "sha": "ea5ba8fe269c06bc503fb10c31a22739f7071eb3",
  "actor": "aguther",
  "event_name": "manual",
  "pretty_release_name": "experimental:ea5ba8fe"
}
```

### Describe the bug

Bug with "MACH SEL" when climbing.

![image](https://user-images.githubusercontent.com/77206541/154865556-7ed5291c-11ee-4674-b96e-b5f75dddd8fd.png)

### Expected behavior

"MACH SEL" should not be behing the white line.

### Steps to reproduce

1. On climb mode, select a speed to reach when on cruise mode.

### Discord Username (optional)

jpccaldas#8164

**Comment by salvapatuel** [comment]
I am fixing this one.
