### ISSUE TITLE
[BUG] ELEC GEN 1 & 2 tooltips incorrect

### ISSUE THREAD

**Issue by Venorcis** [flybywiresim/a32nx#678]
**Mod Version**
Master

**Describe the bug**
The tooltips for the GEN 1 and GEN 2 buttons on the overhead ELEC panel say that pressing them turns the engine 1 or 2 generator ON, whilst pressing one those buttons actually turns the generator off.

**Comment by lukecologne** [comment]
This seems to have been fixed, as I don't have this issue with latest master anymore.
