### ISSUE TITLE
weird line 

### ISSUE THREAD

**Issue by david187210** [flybywiresim/a32nx#6782]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-02-21T12:29:35+00:00",
  "ref": "master",
  "sha": "1bba3e196e13b2ff7b3259dedf61324066a27525",
  "actor": "aguther",
  "event_name": "manual",
  "pretty_release_name": "master:1bba3e19"
}
```

### Describe the bug

![image](https://user-images.githubusercontent.com/65577051/155095893-7d5e573a-0993-4c01-abd5-0066d085012c.png)

I have imported from simbreif has been a problem in the EGPF to EGLL and EGLL to LEBL i am sorry if my wording is not correct i am not good at descrbing things 

my simbreif name is david187210

this was following simbreifs plan of NORB1H NORBO T256 ROVLA UT256 DCS UL612 LAKEY DCT NUGRA NUGR1H 

i hope some of can look into this again fantastic work you are doing just want this prblem fixed so we can all have a lot more fun thanks take care and stay safe 

### Expected behavior

i am sure there should be a straight line after you take out the disconunitys but there is not seems the plane wants to go back on itself at times i hope this makes sense take care and stay safe 

### Steps to reproduce

im ported from simbreif 
![image](https://user-images.githubusercontent.com/65577051/155097869-f4fc9971-b738-429f-a279-37073d7eb62a.png)

**Comment by Benjozork** [comment]
You had two duplicate waypoints.

![image](https://user-images.githubusercontent.com/4503241/155145494-2d6081e9-f42c-457f-af18-8190cfa3d861.png)

**Comment by david187210** [comment]
I know but should that not come up with discontinuity thanks

**Comment by Benjozork** [comment]
It should just not come up

This will be fixed in FMS v2
