### ISSUE TITLE
RWY only on Arrival page for visual approaches

### ISSUE THREAD

**Issue by Illuminati270** [flybywiresim/a32nx#6785]
### Aircraft Version

Experimental

### Description

Hi there guys! 

A missing feature that doesn't seem to face any difficulty for now:

Despite every approach on the arrival page (ILS/RNAV/VOR etc) the Airbus features a "RWY only" option, which, by default, sets up a waypoint called "CF" 5nm from theshold to be crossed at 1500' AGL.

That helps on visual approaches by simply being useful to calculate the aircraft's performance and nothing else (sometimes a little help with vertical profile as well)

### Discord Username (optional)

Illuminati

**Comment by Benjozork** [comment]
This is planned for cFMS v2.

**Comment by tracernz** [comment]
Duplicate #954.
