### ISSUE TITLE
Dome light works without electricity

### ISSUE THREAD

**Issue by NoName824** [flybywiresim/a32nx#6794]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-02-23T10:37:57+00:00",
  "ref": "experimental",
  "sha": "e3e4f4d1e51d9970fffd49725e75f2af183045c1",
  "actor": "aguther",
  "event_name": "manual",
  "pretty_release_name": "experimental:e3e4f4d1"
}
```

### Describe the bug

When no energy source is activa and you select the dome switch it gets brighter while the lamp stays off.

### Expected behavior

No matter the position of the switch, it should not get brighter when all power systems are deactivated. (batteries, APU and Engine)

### Steps to reproduce

1. Spaw on any park position or gate
2. Turn on the dome light in the cold and dark stage

### References (optional)

Cold and dark all off
![FlightSimulator_2022 02 23-19 53](https://user-images.githubusercontent.com/58403846/155387895-de890562-303d-4a78-8a67-98acd24acf38.png)

Cold and dark all except dome off
![FlightSimulator_2022 02 23-19 53_1](https://user-images.githubusercontent.com/58403846/155388012-10231855-394d-44c4-b2a3-4de606e6634d.png)

Same as before but with batteries on
![FlightSimulator_2022 02 23-19 53_2](https://user-images.githubusercontent.com/58403846/155388190-55a75891-3db6-4876-bc68-61080d4af503.png)

### Additional info (optional)

Same thing happens in the dev version. The stable version work as intended

### Discord Username (optional)

NoName#1057

**Comment by sidnov** [comment]
Check Captain's dome light for illumination. Both Capt. Dome and FO Dome are connected to separate busses.

**Comment by tracernz** [comment]
Working as intended. The captain side dome light is powered by the DC ground service bus which is always powered when ext power is connected (which seems to always be the case in MSFS when near a gate).
