### ISSUE TITLE
Negative EFOB and blank fuel pred window

### ISSUE THREAD

**Issue by KLM1009** [flybywiresim/a32nx#6798]
### Aircraft Version

Development

### Build info

```json
{
  "bu{
  "built": "2022-02-24T11:13:11+00:00",
  "ref": "master",
  "sha": "27b2b71b4c9520b8343b690e0a24a825b4c609a0",
  "actor": "svengcz",
  "event_name": "manual",
  "pretty_release_name": "master:27b2b71b"
}
```

### Describe the bug

Unexpected (negative) EFOB value that is not in accord with simbrief.
Flight from Frankfurt to Gibraltar. EFOB -1.7
The fuel prediction window also turned blank.

### Expected behavior

Expected 5 tons left at arrival Gibraltar.

### Steps to reproduce

1. simbrief OFP from EDDF to LXGB with 3tons extra fuel.
2. OFP: EDDF ANEK1F ANEKI Y163 HERBI Y164 OLBEN N869 NEMOS DCT GVA DCT INCUS DCT BALSI UN852 DIVKO UN975 BCN UM985 PIMOS DCT LXGB
3. FL350, two engines operational
4. EFOB value of -1.7 and increases
5. press the soft key on the right side of the left MCDU in the fuel pred that shows the ZFW value.
6. The MCDU will now show a black screen on the FUEL PRED window

### References (optional)

![image](https://user-images.githubusercontent.com/100361815/155539729-2fc9f301-4c7d-42ab-9730-69dcbbade84d.png)
![image](https://user-images.githubusercontent.com/100361815/155539776-02edb022-fb65-45db-9600-dc51b520b8af.png)

### Discord Username (optional)

Warpig1017 / Roland#0520

**Comment by BlueberryKing** [comment]
Thanks for the report! This is something that we will tackle as part of the VNAV implementation. The aircraft will be able to predict the fuel burn much better then.

**Comment by OFC1983** [comment]
Have the same issue with the negative EFOB value. However, for me it works as a workaround that if I switch to the INIT -> Fuel Pred Page the values in the F-PLN Section of the MCDU are fixed.
