### ISSUE TITLE
TO PERF does not have 1+F setting

### ISSUE THREAD

**Issue by toffee2000** [flybywiresim/a32nx#68]
When entering flap setting, if “1” is entered on MCDU, 1+F should show.

**Comment by Meqolo** [comment]
All the photos I've seen show that it should just be 1

**Comment by becas22** [comment]
Affirm, only 1, not 1+F.

**Comment by PCGamesF1Tech** [comment]
The entry on the perf page is e.g. "1/0.5DN", there is no "1+F" (only on flap indication on ECAM).

**Comment by NathanInnes** [comment]
This is true to life behaviour according to @ares1378
