### ISSUE TITLE
Payload from W&B MCDU page doesn't match SimConnect

### ISSUE THREAD

**Issue by sushiat** [flybywiresim/a32nx#6802]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-02-24T09:08:44+00:00",
  "ref": "experimental",
  "sha": "de06bd495e9b3ea39de89fb23658824d6838c8d5",
  "actor": "aguther",
  "event_name": "manual",
  "pretty_release_name": "experimental:de06bd49"
}
```

### Describe the bug

When monitoring the total amount of payload loaded accross all payload stations I noticed the following behaviour:

MCDU Paylod: 0kg => 2.0 lbs / 0.9 kg reported on SimConnect
MCDU 1 PAX: 104 kg => 231.1 lbs / 104.8 kg
MCDU 10 PAX: 1040 kg => 2292.9 lbs / 1040.1 kg
100 PAX: 10400 kg => 22911.2 lbs / 10392.4 kg

I was trying to add a "loading calculator" helper to our application, trying to work out how pax/extra cargo to use to reach the desired target payload. I'm diving all LBS values by 2.20462 to get to KG.

### Expected behavior

The KG amount displayed in the MCDU should match the reported value on the simconnect payload stations

### Steps to reproduce

Turn on power
Go to W&B page in ATSU -> AOC Menu
Enter PAX number and compare to reported total payload stations on simconnect

**Comment by mattsains** [comment]
Why was this issue closed? I don't see any commits recently that addresses W&B. According to https://github.com/flybywiresim/a32nx/issues/7082#issuecomment-1101284793 , the issue will be addressed by https://github.com/flybywiresim/a32nx/pull/7078 which is not merged yet.
