### ISSUE TITLE
[MCDU] Airways interface broken after Simbrief import

### ISSUE THREAD

**Issue by vkrizan** [flybywiresim/a32nx#6803]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-02-26T01:09:36+00:00",
  "ref": "master",
  "sha": "9e4832780c4a5f639c2e6cb3f1e8d67e05801df0",
  "actor": "Benjozork",
  "event_name": "manual",
  "pretty_release_name": "master:9e483278"
}
```

### Describe the bug

Airways page on MCDU F-Plan breaks on Simbrief import when some of the airway is missing (or is incorrect). One of the correct airways is always present on the Airways page for every waypoint up to the last waypoint of the airway. It is not possible to add or change the airways, as well as cannot clear the existing one (that is stuck).

Route:
```
LOWW/34 MEDIX1D MEDIX DCT RENKA UL610 LOHRE UL984 NOSPA DCT IDOSA
UN857 RENSA RENSA7E LFPO/07
```

The stuck airway is `UN857` to `RENSA`.
The incorrect airway is `RENKA UL610 LOHRE`. Correct airway is `L610` however that is not possible to be used due to the stuck one. Adding `L610` results in `AWY/WPT MISMATCH`.

Note that this the route is invalid for current MSFS-default AIRAC cycle (due 23 Feb).

### Expected behavior

I guess the Airways page should only display airways that are applicable in between the airways waypoints.

When Airways page is open for example on `RENKA` waypoint, the page should not show the stuck airway and allow to add correct airway that is relevant to `RENKA` airway.

I'd expect to have the ability to CLR the airway, but I'm not sure if that's how it is IRL.

### Steps to reproduce

1. Prepare Simbrief flightplan from `LOWW` to `LFPO`.
2. Use the route id from the description.
3. Import Simbrief on INIT page
4. Open Airways for `MEDIX` waypoint, observe existing airways
5. Open Airways for `RENKA` waypoint, try to add `L610` airway to `GONBA`

### Additional info (optional)

MSFS-default AIRAC cycle (due 23 Feb) was used.

### Discord Username (optional)

coolll.sk#0022

**Comment by Gurgel100** [comment]
I also encountered this problem that when you want to add an arway before an already existing waypoint the airways page shows the airways entered for the route but you can't add another airway in front of the list.

**Comment by vkrizan** [comment]
@tracernz Are you able to share some references for the Airways page. I might have a stab at it.
