### ISSUE TITLE
[BUG] PDF and ND brightness knob tooltips are wrong

### ISSUE THREAD

**Issue by Venorcis** [flybywiresim/a32nx#681]
**Mod Version**
master

**Describe the bug**
Both buttons show the same behaviour: the tooltip for turning the knob left shows it will increase the PFD/ND brightness (wilst it actually decreases it), and the tooltip for turning the knob right shows it will increase floodlight brightness (which is unrelated).

**Comment by UncleClapton** [comment]
Confirmed. Looking into this.

**Comment by UncleClapton** [comment]
I think this might be worth reporting to asobo directly. We haven't touched these tooltips from the looks of it, and the problem seems to exist in the localization files themselves, which we don't override in the mod yet.

**Comment by Venorcis** [comment]
> I think this might be worth reporting to asobo directly. We haven't touched these tooltips from the looks of it, and the problem seems to exist in the localization files themselves, which we don't override in the mod yet.

I'd say we override them in the mod then, is there anything against that?

**Comment by lrargerich** [comment]
Sorry to ask here but there's no way to remove the tooltips completely yet right?
I find them annoying as hell.
