### ISSUE TITLE
SCALAR is not a valid accessor type for WEIGHTS_0 by the glTF specification

### ISSUE THREAD

**Issue by pzgulyas** [flybywiresim/a32nx#6813]
### Aircraft Version

Experimental

### Build info

```json
-
```

### Describe the bug

SCALAR is not a valid accessor type for WEIGHTS_0 by the glTF specification. Only VEC4 is allowed.
https://github.com/flybywiresim/a32nx/blob/e9ad53792f5d9a7c992842a56e7dcb451d9328d7/src/model/a320-exterior/A320_NEO_LOD03.gltf#L17143-L17148

See: https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#meshes-overview

### Expected behavior

-

### Steps to reproduce

-

**Comment by tracernz** [comment]
These are MSFS extensions by Asobo. We must work to the MSFS GLTF "spec", not the official Khronos one.

**Comment by pzgulyas** [comment]
With respect, I don't think it is true. Everywhere an ASOBO extension is in place, there is an "extensions": { } section in the gltf, end at these nodes there isn't anything such.

Also, look at the corresponding joints: they are of type VEC4. The relevant shader in the graphics engine looks like this:
`	float4x4 skinTransform = 0;

	skinTransform += Bones[Joints.x] * Weights.x;
	skinTransform += Bones[Joints.y] * Weights.y;
	skinTransform += Bones[Joints.z] * Weights.z;
	skinTransform += Bones[Joints.w] * Weights.w;`
Think of the math: If the weight is a SCALAR, how does it connect to the VEC4 joint?

And this error was not present in the 1-2 months old stable model, so this is actually a regression.

I would suggest at least to investigate if this is an exporter failure or an issue within the source model.

**Comment by Benjozork** [comment]
The model files are straight from the simulator.

**Comment by pzgulyas** [comment]
> Those model files are straight from the simulator.

@Benjozork , "from"? These model are (targeted) "to" simulator. Their "from" source is some authoring tool, such as Blender or 3DSMAX.

**Comment by tracernz** [comment]
These parts are directly from the Asobo A320 model built with their official tools.

> With respect, I don't think it is true. Everywhere an ASOBO extension is in place, there is an "extensions": { } section in the gltf, and at these nodes there isn't anything such.

That is definitely not true. They do various things in standard/non-extension parts that are not compliant with the spec, e.g. the seigned short datatype (5122) is not an signed short in MSFS, rather a 16-bit float, and the sim does not accept many things that are allowed by the spec.

**Comment by Benjozork** [comment]
> > Those model files are straight from the simulator.
> 
> @Benjozork , "from"? These models are (targeted) "to" simulator. Their "from" source is some authoring tool, such as Blender or 3DSMAX.

I'm not quite sure what the point of arguing over semantics is. As tracer said, the files are taken straight from the base A320 model. We do not change those, except some interior files and the highest exterior LOD.

**Comment by pzgulyas** [comment]
> I'm not quite sure what the point of arguing over semantics is. As tracer said, the files are taken straight from the base A320 model. We do not change those, except some interior files and the highest exterior LOD.
The point was that I did not know that, and without this knowledge the semantic didn't make any sense to me.

**Comment by Benjozork** [comment]
Gotcha. All good then.

**Comment by pzgulyas** [comment]
> They do various things in standard/non-extension parts that are not compliant with the spec, e.g. the signed short datatype (5122) is not an signed short in MSFS, rather a 16-bit float

Hmmm, that's intresting, although I wouldn't call it clever.

**Comment by tracernz** [comment]
> > They do various things in standard/non-extension parts that are not compliant with the spec, e.g. the signed short datatype (5122) is not an signed short in MSFS, rather a 16-bit float
> 
> Hmmm, that's intresting, although I wouldn't call it clever. :)

I know... I don't know why they didn't use an off-the-shelf GLTF implementation and just add *all* of their extensions as proper GLTF extensions, and do any weird stuff in a different layer so it's not exposed like this.
