### ISSUE TITLE
VEC4 is not a valid accessor type for NORMAL vertex attributes by the glTF specification. Only VEC3 is allowed.

### ISSUE THREAD

**Issue by pzgulyas** [flybywiresim/a32nx#6814]
### Aircraft Version

Experimental

### Build info

```json
-
```

### Describe the bug

VEC4 is not a valid accessor type for NORMAL vertex attributes by the glTF specification. Only VEC3 is allowed.
https://github.com/flybywiresim/a32nx/blob/e9ad53792f5d9a7c992842a56e7dcb451d9328d7/src/model/a320-exterior/A320_NEO_LOD03.gltf#L7018-L7023
See: https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#meshes-overview

### Expected behavior

-

### Steps to reproduce

-

**Comment by tracernz** [comment]
These are MSFS extensions by Asobo. We must work to the MSFS GLTF "spec", not the official Khronos one.
