### ISSUE TITLE
"Black hole" obstructing flight path on ND

### ISSUE THREAD

**Issue by GrimGrandZero** [flybywiresim/a32nx#6821]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-03-01T05:37:18+00:00",
  "ref": "experimental",
  "sha": "33581a699f2482f8502d7e79ce43b313dc314067",
  "actor": "aguther",
  "event_name": "manual",
  "pretty_release_name": "experimental:33581a69"
}
```

### Describe the bug

There's some sort of a circular "black hole" in the bottom right corner of the ND.
It covers the flight path's green line. 

### Expected behavior

No black hole

### Steps to reproduce

Fly a SID or STAR with right hand turns.

### References (optional)

![Screenshot_1](https://user-images.githubusercontent.com/85913413/156123671-09d55101-9657-4f45-90d9-f4104f904f55.png)
![Screenshot_2](https://user-images.githubusercontent.com/85913413/156123675-4239b89d-7bd7-47b6-a793-b9f33d8c8f5c.png)

**Comment by sidnov** [comment]
It's a masking for the VOR/ADF indicators, same as the IRL bus
