### ISSUE TITLE
Nose- & Runway Turnoff Lights Flashing

### ISSUE THREAD

**Issue by MariusSchuller** [flybywiresim/a32nx#6826]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-02-26T07:59:01+00:00",
  "ref": "experimental",
  "sha": "cd7561d6d63be65ce07bcb41b6e837e2b04a86c3",
  "actor": "aguther",
  "event_name": "manual",
  "pretty_release_name": "experimental:cd7561d6"
}
```

### Describe the bug

Nose- and runway turnoff lights are flashing.

### Expected behavior

Nose- and runway turnoff lights are illuminated steadily.

### Steps to reproduce

Start Cold and dark
Fly from A to B
"Turn airplane around"
Switch on the lights for taxi

### References (optional)

https://user-images.githubusercontent.com/76614781/156221876-63eecf36-7afe-4be5-a185-590dda4c2968.mp4

### Additional info (optional)

Has always been working before.
I only noticed this after turnaround (second flight).
Due to long time to reproduce I have not tried it a second time.
Switching the lights on / off did not help.

**Comment by Andrenilin** [comment]
I have tried this with the taxi lights on during approach and also off and then turning them on once on the runway.
They did not flicker at all. I completed 4 flights and could not get this to happen once.

**Comment by MariusSchuller** [comment]
Hey @Andrenilin, thanks for your feedback! 

In that case I will close this issue for now as it is currently not reproducible. If I encounter this issue again, I'll re-open.
