### ISSUE TITLE
METAR via IVAO broken

### ISSUE THREAD

**Issue by FRYYYYYY** [flybywiresim/a32nx#6829]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-03-01T16:52:36+00:00",
  "ref": "master",
  "sha": "d3b9189b947866bf37ab5a96e332980fdd26758b",
  "actor": "frankkopp",
  "event_name": "manual",
  "pretty_release_name": "master:d3b9189b"
}
```

### Describe the bug

The METAR display and request does not work once IVAO is selected as the network.

The following error message is displayed within the EFB:
"TypeError: undefined is not an object (evaluating 'metarString.trim')"

![2022-03-02 (4)](https://user-images.githubusercontent.com/13643787/156352904-f24d8648-c7ca-49f7-9016-a2d27de535da.png)

Within the MCDU, the request is broken:

![2022-03-02 (5)](https://user-images.githubusercontent.com/13643787/156353216-6b13588f-5a9d-4c87-82e8-95bbfcee69ff.png)

### Expected behavior

In previous versions it was possible to display METAR via IVAO. It works via VATSIM etc., but not via IVAO.

### Steps to reproduce

EFB

1. EFB configured to "IVAO" (Settings --> ATSU/AOC)
2. Load flight plan "FROM SIMBRIEF"

MCDU

1. Request weather via MCDU menu

**Comment by aguther** [comment]
Please retest with development version and reopen the ticket if issue persists.

The experimental version is not supported and issues should be reported in Discord.

**Comment by FRYYYYYY** [comment]
> Please retest with development version and reopen the ticket if issue persists.
> 
> The experimental version is not supported and issues should be reported in Discord.

I am not able to re-open the issue.

**Comment by Benjozork** [comment]
IVAO have deprecated the METAR API we use.

We are awaiting on a key from them to switch to the new one. In the mean time, we are deploying a server-side change that will fallback to VATSIM to prevent errors.

**Comment by Benjozork** [comment]
Closing as further changes will be server-side.
