### ISSUE TITLE
Radio Altimieter indicates "0" on final approach

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#6831]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-03-02T06:45:54+00:00",
  "ref": "experimental",
  "sha": "9173ddc981def400af4a4709149ad6bfeeb7a55f",
  "actor": "aguther",
  "event_name": "manual",
  "pretty_release_name": "experimental:9173ddc9"
}
```

### Describe the bug

RA on PFD indicates 0 feet the whole time 

### Expected behavior

Radio altimeter should indicate height above ground

### Steps to reproduce

make an approach, look at radio altimeter
![RA bug](https://user-images.githubusercontent.com/72918017/156362984-cb2160c9-a85f-4814-b852-6bf9b1481be4.jpg)

**Comment by aguther** [comment]
Please retest with development version and reopen the ticket if issue persists.
