### ISSUE TITLE
Mcdu Info On Resizable Window For Home Cockpit Mcdu Hardware

### ISSUE THREAD

**Issue by vagelisdrivas** [flybywiresim/a32nx#6839]
### Aircraft Version

Development

### Description

If it is possible to display mcdu information only (not mcdu profile as it is on the server app) to a resizable window without borders in order to append it on a different small lcd screen (home made mcdu). Thank you.

### References (optional)

![mcdu 1](https://user-images.githubusercontent.com/100070299/156641991-6bf9fd16-a7f3-4a37-a78d-f16c9d6f4b05.jpg)
![mcdu2](https://user-images.githubusercontent.com/100070299/156642116-e90b2d45-85ac-4fc0-941c-9c61ebd6444f.jpg)

### Discord Username (optional)

Vagelis Drivas#1940

**Comment by tracernz** [comment]
Already possible by adding /fullscreen to the URL. Please re-open if you have further issues.
