### ISSUE TITLE
Baro knob push in lock mode auto-repeats since SU8

### ISSUE THREAD

**Issue by tracernz** [flybywiresim/a32nx#6841]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-03-04T04:37:56+00:00",
  "ref": "HEAD",
  "sha": "b2d7668d7dcbef695cf7462635c9800234b5967c",
  "actor": "Andreas Guther <andreas@guther.family>",
  "event_name": "manual",
  "pretty_release_name": "experimental:b2d7668d"
}
```

### Describe the bug

Since SU8 something has changed in the XML templates or underlying implementation so now these pushable knobs auto-repeat, causing the push/pull action to be glitchy if it switches between different options e.g. QNH/QFE on the FCU EFIS panel, or QNH/STD on the ISIS. Affects all versions of A32NX.

### Expected behavior

Only one push/pull action per push/pull from the mouse.

### Steps to reproduce

As above.

**Comment by Andrenilin** [comment]
I've tested this today and mine seems to be all good... I've tried to make it glitch. The only thing I noticed that it was quite a positive change.. like flicking a light switch as opposed to a soft movement but that seemed good to me.

**Comment by derl30n** [comment]
Is this still an issue?

**Comment by tracernz** [comment]
Yeah, this is an issue with the base sim mouse events in lock mode that affects all Asobo aircraft, introduced in SU8. There is no way to work around it without major side effects so I hope they will fix it.

**Comment by derl30n** [comment]
So I never experienced it since I am on legacy interaction mode hehe

**Comment by tracernz** [comment]
This is fixed, I think in SU10, or maybe 9.
