### ISSUE TITLE
Change Mcdu Server Fullscreen Mode Lines Height

### ISSUE THREAD

**Issue by vagelisdrivas** [flybywiresim/a32nx#6842]
### Aircraft Version

Development

### Description

Good morning. Is it possible to alter the html code of server in order to change the x-y coordinates of the lines, or is it possible to add a function like up / down left/right so you can move the lines? The problem is that the lines are not perfectly alligned with the physical mcdu panel (see picture below). Thank you in advance and my sincere congratulations for your work. I'm also a programmer and if you need any assistance i'll be more than glad to help you. 

### References (optional)

![Untitled-1](https://user-images.githubusercontent.com/100070299/156722366-695716b5-c96d-4bd6-9e82-213d997c372b.jpg)

### Discord Username (optional)

Vagelis Drivas#1940

**Comment by tracernz** [comment]
You might be able to do this with a custom stylesheet and a few `!important` directives in it.

**Comment by vagelisdrivas** [comment]
> You might be able to do this with a custom stylesheet in the browser you're using to render the MCDU screen, and a few `!important` directives in it.

Thank you for the answer. I understand what you imply but the problem is that i can't figure out where the files are located so i can change the code, As far as i can understand the server loads some javascripts and html's but where they are located?

**Comment by frankkopp** [comment]
@tracernz I'll look into this - maybe we can do something with a ratio option to accommodate for these different screen.

**Comment by vagelisdrivas** [comment]
Thank you for your answer. Maybe you can pass a parameter via html to manual assign x - y coordinates like /x-something/y-something.

**Comment by sunday747** [comment]
Any news about it? I know its not a high prio issue, so i just want to ask.
