### ISSUE TITLE
[BUG] NAV mode INOP on second flights (continuation in Sim)

### ISSUE THREAD

**Issue by slebr** [flybywiresim/a32nx#685]
**Mod Version**

Master 0.2

**Describe the bug**

When conducting a second flight without exiting the sim (landing, manually entering FPL for a second flight and continuing) the Managed Mode NAV does not fly correctly. The airplane will bank either left or right and do a 180 degree turn. Restarting at the gate or reloading the Sim gets rid of the issue.

Airplane won't fly FPL in NAV/Managed mode correctly

**To Reproduce**

1. Conduct a second flight after completing a first flight without closing the sim (continuation)
2.
3.

**Expected behavior**

Plane to fly route on NAV and follow the line

**Actual behavior**

Airplane turns around

**References**

**Additional context**

**Comment by speedwaystar** [comment]
i have noticed this happening in GA aircraft since the patch, for what it's worth.

**Comment by MisterChocker** [comment]
this has been fixed by now
