### ISSUE TITLE
more audible roll sound/noise 

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#6852]
### Aircraft Version

Development

### Description

The actual soundset of the plane is awesome and becomes better everytime.
But, i recognize that in the past there were a more "intensive" roll sound while taxi on ground. 

To my feel and with comparison to real world airbus cockpit experiences there should be a more audible roll/(rumble) sound. 
I know, there a very smooth taxiways out there in real life, where taxi is not much audible (also depend on much other factors, i know) 
Also, as everybody knows, the main "feel" of taxi comes from feeling, like wiggle, rumble etc. So that should be a bit underlined with sound, i think.
But it would be good, if you could "feel" (via audio) the ground roll more like in the actual soundpack :)

**Comment by hotshotp** [comment]
This is a bug that's on my pipeline to fix, I don't know what I did but I somehow got rid of it. Not to worry, it'll be fixed soon

**Comment by andrejetcat** [comment]
glad to hear!! :( thank you! take your time!
