### ISSUE TITLE
ILS Frequency not transferred to RADNAV Page

### ISSUE THREAD

**Issue by cyrax87** [flybywiresim/a32nx#6854]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-03-05T07:54:00+00:00",
  "ref": "master",
  "sha": "299aa708a7d08fad0bc8e21e96cc635dee90569b",
  "actor": "tracernz",
  "event_name": "manual",
  "pretty_release_name": "master:299aa708"
}
```

### Describe the bug

After selecting the arrival Runway in the MCDU the RADNAV page stays emtpy. Hence the "APP" mode cannot be activated and no signal is captured. 

If the freuency is tuned manually everything works as desired.

The Issue popped up after the last SimUpdate - both the DEV and EXP Versions show exactly the same behaviour. 
I tested multipe Airports.

EDDS
EDDF
EKCH
KJFK

### Expected behavior

After the selection of the arrival runway the ILS frequency and CRS should be filled in the RADNAV Page.
APP mode selector can be activated, ILS is captured.

### Steps to reproduce

1. Load into a flight and take off
2. after takeoff select an arrival airport and runway
3. observe the RADNAV page

### Additional info (optional)

Communityfolder completely empty apart from FBW A32NX

### Discord Username (optional)

Matthias_D#4577

**Comment by TayDex** [comment]
Also had the same problem on about 3 flights everywhere around Europe. Glad I finally found the cause for it, hope it gets fixed soon, manual typing in till then I guess.

**Comment by donstim** [comment]
![Screenshot (1964)](https://user-images.githubusercontent.com/70166617/156905859-2b48661f-617b-41ef-af23-d0fe1ba6227f.png)

**Comment by TayDex** [comment]
> It will not autotune if you are still in the takeoff phase, or if you are more than 250NM from the destination.

Well it never did for me, noticed it cause I couldn't active APPR, literally right Infront of the runway. 

Did another test flight and same problems, Tuning the ILS frequency manually also resulted in it getting picked up once close to the airport.

**Comment by donstim** [comment]
Which runway(s)?

**Comment by tracernz** [comment]
> > It will not autotune if you are still in the takeoff phase, or if you are more than 250NM from the destination.
> 
> Well it never did for me, noticed it cause I couldn't active APPR, literally right Infront of the runway.
> 
> Did another test flight and same problems, Tuning the ILS frequency manually also resulted in it getting picked up once close to the airport.

Were you using Navigraph 2202 rev. 2 navdata? That has a problem that causes missed approach legs to be included at the end of the final approach segment and consequently stops the autotune from working (as the missed approach legs don't have the ILS coded as the recommended navaid).

**Comment by cyrax87** [comment]
THis is really weird.
Now the Radnav get filled after updating to rev 3 but still I cannot activate the app button.
I am really close to the runway when I try that, normally it should.
I'm lost...

**Comment by TayDex** [comment]
> Were you using Navigraph 2202 rev. 2 navdata? That has a problem that causes missed approach legs to be included at the end of the final approach segment and consequently stops the autotune from working (as the missed approach legs don't have the ILS coded as the recommended navaid). The solution in that case is to update to 2202 rev. 3.

Could be it, will do another test flight today and report on the result.

**Comment by cyrax87** [comment]
Rev 3 did the trick after reinstalling the Aircraft!

**Comment by TayDex** [comment]
Yep Rev3 works, even without reinstall for me.
