### ISSUE TITLE
Lines between waypoints aren't visible

### ISSUE THREAD

**Issue by michaelfsanchez** [flybywiresim/a32nx#6858]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-03-06T12:04:49+00:00",
  "ref": "experimental",
  "sha": "5ef0d7aca0257a63bcc744e33e35f9e601c57ad7",
  "actor": "aguther",
  "event_name": "manual",
  "pretty_release_name": "experimental:5ef0d7ac"
}
```

### Describe the bug

The green lines between the waypoints of flight plan aren't visible.

![image](https://user-images.githubusercontent.com/34313628/156924692-afc6aa3c-1f7e-4d36-b096-9b9d630e0696.png)

### Expected behavior

When I create the flight plan I want to see the lines to verify the route the plane wil follow.

### Steps to reproduce

1. Delete prev folder
2. Install again

**Comment by aguther** [comment]
Experimental version is not supported on GitHub. Please retest with development version and feel free to reopen this issue if the error persists.

**Comment by michaelfsanchez** [comment]
Same in development version, i don't have any more mods installed,

![image](https://user-images.githubusercontent.com/101052831/156930336-570421c8-a8b4-4908-91ea-5faf36645743.png)
