### ISSUE TITLE
PFD lagging behind after takeoff

### ISSUE THREAD

**Issue by GlitchedYT** [flybywiresim/a32nx#6859]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-03-06T12:04:49+00:00",
  "ref": "experimental",
  "sha": "5ef0d7aca0257a63bcc744e33e35f9e601c57ad7",
  "actor": "aguther",
  "event_name": "manual",
  "pretty_release_name": "experimental:5ef0d7ac"
}
```

### Describe the bug

After taking off the PFD (both captain anf fo) got really slow and laggy up until around 18000ft. Glass cockpit refresh rate is on Medium.

### Expected behavior

PFD should not slow down and be laggy (almost like it dropped framerate or something)

### Steps to reproduce

1. Create a flight KORD -KJFK
2. during takeoff observe PFD starts lagging behind up until 18000ft

### References (optional)

didnt have the time to take a video but will if it happens again

### Discord Username (optional)

Glitched#0740

**Comment by aguther** [comment]
Thank you for the report, but experimental version is not supported on GitHub. Please try again with the development version and if the issue persists feel free to reopen this issue.
