### ISSUE TITLE
[REQUEST] Upload zip artifact from CI

### ISSUE THREAD

**Issue by AdenFlorian** [flybywiresim/a32nx#686]
for master, CI should zip up only the A32NX folder, after running build.py, then upload it as an artifact, which should be linked from the main README.md so people have easy access to a prepped zip file for master.

for PR's, it should do the same thing, but also comment on the PR with a link to the zip, and it should redo this for every new push on that PR.

https://docs.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts

- [x] PRs #1138
- [x] master #1157
- [x] releases

**Comment by AdenFlorian** [comment]
i've done this for PRs, still need to do for master merges and then for tagged releases.

**Comment by AdenFlorian** [comment]
i still want to do something for releases

**Comment by Gentoli** [comment]
Will changing the name of the zip file to `a32nx-{commit-hash}.zip` for PR and `flybywiresim-a32nx-{version}.zip` for releases be better?

Currently downloading releases results in this:
![image](https://user-images.githubusercontent.com/4814426/97133232-a388ab00-171f-11eb-9ea4-d74f485af06a.png)



Also I think archiving master build in GitHub Action artifacts will also be helpful if someone want to test a certain commit on master.

**Comment by wpine215** [comment]
Release workflow has been added in a recent PR.
