### ISSUE TITLE
Aircraft Turnaround State Values

### ISSUE THREAD

**Issue by OFC1983** [flybywiresim/a32nx#6862]
### Aircraft Version

Development

### Description

I would love to see that when I click on "Delete all" on the MCDU after a flight is completed that the W&B Passenger Values are set to 0 and also that the Fuel Used Values on the FUEL ECAM Page are set to 0 again.

**Comment by tracernz** [comment]
W&B is being reworked in the EFB and will be removed from the MCDU as it is not a page in the real MCDU. Fuel used should reset on the next engine start, as on the real A320. If you're talking about the stored data DELETE ALL that's only for deleting stored waypoints/runways/navaids/routes, as in the real MCDU.

**Comment by OFC1983** [comment]
W&B will be republished in the EFB - checked. Unfortunately, the Fuel Used values were not reset after engine restart. I will try again next weekend.

**Comment by Taz5150** [comment]
Used fuel reset is being taken care of in PR #6876.

Thank you!
