### ISSUE TITLE
Boarding Music

### ISSUE THREAD

**Issue by OFC1983** [flybywiresim/a32nx#6863]
### Aircraft Version

Development

### Description

I really like the new Boarding Music that is being played while passengers are boarding the aircraft. It would be great to have this music file customizable, i.e. by selecting an mp3 in the EFB or by making available an option via the installer to select a user mp3.

**Comment by Benjozork** [comment]
Not possible in MSFS

**Comment by notl3ks** [comment]
> Not possible in MSFS

I'm not sure if I'm thinking about this correctly. But if you took the sound files for the new boarding sounds, pop it into Audacity (or whichever program is used), put in a new track with the desired music, adjust the volume, then just export the sound file back and replace it?

**Comment by Benjozork** [comment]
> > Not possible in MSFS
> 
> I'm not sure if I'm thinking about this correctly. But if you took the sound files for the new boarding sounds, pop it into Audacity (or whichever program is used), put in a new track with the desired music, adjust the volume, then just export the sound file back and replace it?

They are in compressed encrypted archives (.pck files) due to how MSFS works. You cannot just do that.
