### ISSUE TITLE
Signs....On in ECAM doesn't turn off

### ISSUE THREAD

**Issue by FSC190** [flybywiresim/a32nx#6866]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-03-06T23:48:44+00:00",
  "ref": "experimental",
  "sha": "481c416b0bb5e376173ffcf9aea864ee01a2103c",
  "actor": "aguther",
  "event_name": "manual",
  "pretty_release_name": "experimental:481c416b"
}
```

### Describe the bug

Even if all switches are set to On, the message in the ECAM signs on remains in blue

### Expected behavior

Expecting "no blue" in ECAM

### Steps to reproduce

Start any flight 
power on the aircraft.
Setup until ready to taxi

### References (optional)

<img width="395" alt="image" src="https://user-images.githubusercontent.com/36174809/157089614-73128a57-6d76-465b-ad30-4da6ea122384.png">
<img width="334" alt="Screenshot 2022-03-07 184748" src="https://user-images.githubusercontent.com/36174809/157089662-e9a6b92e-9a6b-460f-a570-f37478ef79af.png">

### Discord Username (optional)

FSC190

**Comment by Benjozork** [comment]
identified and fixed soon, also we do not take github issues for experimental as noted in the documentation

**Comment by aguther** [comment]
Dicsord

**Comment by FSC190** [comment]
THX
