### ISSUE TITLE
Hydraulics gone wonky or something

### ISSUE THREAD

**Issue by GlitchedYT** [flybywiresim/a32nx#6868]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-03-07T21:54:32+00:00",
  "ref": "master",
  "sha": "b9b784797c2ec35c21cdbe2f5f08084e37a1828c",
  "actor": "tracernz",
  "event_name": "manual",
  "pretty_release_name": "master:b9b78479"
}
```

### Describe the bug

while testing the aircraft for performance related issues during engine start the upper ecam never change values whatsoever and the hydralics were showing as orangish meaning no fluid was running through. community folder is empty other than navdata

### Expected behavior

upper ecam should populate with information and hydraulic fluid should be fed during engine start phase

### Steps to reproduce

honestly not even sure how to reproduce i just started a flight from ksfo-ksan and did my normal procedures and realized the upper ecam looked wrong during engine start phase

### References (optional)

https://drive.google.com/file/d/1iRcUIQU8bbgyHctKAgwlHinGNLo2D-fa/view?usp=sharing

### Discord Username (optional)

Glitched#0740

**Comment by ssewell** [comment]
Previous mention is a typo. Disregard.

**Comment by GlitchedYT** [comment]
Stand-by on trying to reproduce this in any way I mentioned in the discord it could 100% be on my end when I cleared out my community folder and screwed something up. Will try again tomorrow after work and a full removal of the community folder as a fresh start.

**Comment by crocket63** [comment]
Was it first launch after updating A32NX ?

Looks like a total WASM module crash.

**Comment by derl30n** [comment]
Closing since no response
