### ISSUE TITLE
[BUG] T.O. ECAM Memo comes back on after landing and vacating runway

### ISSUE THREAD

**Issue by GlitchedYT** [flybywiresim/a32nx#687]
**Describe the bug**

After landing, vacating the runway and cleaning up the aircraft the T.O. Ecam memo comes back on

**To Reproduce**

1. land fully configured at any airport in the world
2. after vacating the runway clean up the aircraft
3. notice how the t.o. ecam memo returns to the upper ecam

**Expected behavior**

t.o. ecam memo shouldn't come back after you initially take off at your departure airport

**Actual behavior**

t.o. ecam memo comes back on after vacating and cleaning up the aircraft after you've landed

**References**

https://imgur.com/F47ZydG

**Additional context**

Discord username:

**Comment by Coralec** [comment]
This is a known result of the currently rudimentary implementation of the ECAM Memo system. We can expect a full reworking of the ECAM Memo system once more of them are completed. When this happens, this issue will be resolved.
