### ISSUE TITLE
el avión ha desaparecido

### ISSUE THREAD

**Issue by lordstout** [flybywiresim/a32nx#6871]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2022-01-08T01:22:50+00:00",
  "ref": "v0.7.4",
  "sha": "5adc0dc1ee3bd9cf9386c312b798a5f8ca7b391b",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

no se ve el avión, Te sitúa en la posición donde debería de estar el avión pero no hay nada.
sucede lo mismo con la versión de desarrollo y con diversas livery

### Expected behavior

que el avión aparezca

### Steps to reproduce

intentando hacer un vuelo

**Comment by ErickSharp** [comment]
> Hello,
> 
> This issue is explained in the "known issues" page of the FBW project website:
> 
> https://docs.flybywiresim.com/fbw-a32nx/support/reported-issues/ (see "invisible aircraft")
> 
> You very likely have the old FBW version installed from the simulator marketplace, uninstall it via content manager. The above page explains the problem.

El dijo que es porque tienes un version viejo del avión. Puedes instalar un version más reciente en el instalador del flybywire

**Comment by apachebcn** [comment]
> > Hello,
> > This issue is explained in the "known issues" page of the FBW project website:
> > https://docs.flybywiresim.com/fbw-a32nx/support/reported-issues/ (see "invisible aircraft")
> > You very likely have the old FBW version installed from the simulator marketplace, uninstall it via content manager. The above page explains the problem.
> 
> El dijo que es porque tienes un version viejo del avión. Puedes instalar un version más reciente en el instalador de flybywire

A mi me está sucediendo ahora en Diciembre de 2023 y es recién descargado la versión estable
