### ISSUE TITLE
APU Flap Animation

### ISSUE THREAD

**Issue by LeDerpLegend** [flybywiresim/a32nx#6874]
### Aircraft Version

Development

### Description

Recommended to add APU Flap logic, sounds, and animation of both the flap opening and closing. 

### References (optional)

Not a320neo exactly but a video for basic reference. https://youtube.com/shorts/oBYR1Z_jhqo?feature=share

### Additional info (optional)

Currently the APU Flap is stuck open and seems rather quick to open and close. 

### Discord Username (optional)

LeDerpLegend#0109

**Comment by hotshotp** [comment]
The APU flap is fully simulated, opening and closing at it's correct stages, and has sounds. The video you linked is a different apu (Honeywell) than the one we simulate (APS). It just doesn't have an animation, but definitely will on the new model
