### ISSUE TITLE
Game crashes when I input the flight number

### ISSUE THREAD

**Issue by acerbisgianluca** [flybywiresim/a32nx#6884]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-03-09T02:07:38+00:00",
  "ref": "master",
  "sha": "1c25455bb17e2a0015cb22c9d9c1ad299bf2bfa5",
  "actor": "tracernz",
  "event_name": "manual",
  "pretty_release_name": "master:1c25455b"
}
```

### Describe the bug

When I input the flight number inside the init page, the game starts lagging for a few seconds, then it crashes.

### Expected behavior

Game should't crash. It used to work until March 7-8th.

### Steps to reproduce

1. Spawn at an airport
2. Go to AOC menu and fill the fields
3. Go to init page
4. Input departure and arrival airports
5. Input flight number
6. Game starts lagging, then it crashes

**Comment by aguther** [comment]
You really think this a problem of the A32NX and not MSFS?

Try the following steps, unfortunately the sim seems to tend to crash when aircraft is updated:
https://docs.flybywiresim.com/fbw-a32nx/installation/#clean-install-steps
