### ISSUE TITLE
[REQUEST] Fuel Predictions aren't calculated

### ISSUE THREAD

**Issue by Lucky38i** [flybywiresim/a32nx#689]
**Is your feature request related to a problem? Please describe.**
Yes, the current FUEL PRED page remains blank of any information. Fuel prediction is essential to any pilot to ensure they have enough fuel onboard for their trip as well as seeing fuel information during flight. It is also used after an engine is started and INIT B is no longer used.

**Describe the feature you'd like to see implemented**
The fuel predictions page implemented per the fcom 

**References**

FCOM 4.03.20 P14

**Additional context**

http://www.a320dp.com/A320_DP/nav-flight-management/sys-14.10.0.html

Discord username: Lucky38#3550

**Comment by Lucky38i** [comment]
Currently attempting to do this. https://github.com/Lucky38i/a32nx/tree/cdu-fuelpred

**Comment by Lucky38i** [comment]
For fluidity I will be implenting the full function of the INIT B page first, or atleast attempting to.

**Comment by LuisPhSilva** [comment]
We really need a fuel computation in this aircraft!
