### ISSUE TITLE
SPEED + CLB modes at the same time

### ISSUE THREAD

**Issue by Illuminati270** [flybywiresim/a32nx#6890]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-03-11T07:05:00+00:00",
  "ref": "experimental",
  "sha": "b572c4dacf33c9386a11ee7810d04afd6e76591c",
  "actor": "aguther",
  "event_name": "manual",
  "pretty_release_name": "experimental:b572c4da"
}
```

### Describe the bug

![image](https://user-images.githubusercontent.com/85410344/157903662-c9e43588-e5f4-4206-86df-8a48351d57a5.png)

That's pretty much how it looks. Instead of THR CLB on CLB / OP CLB modes, the A/THR triggers SPEED mode, which shouldn't happen.

### Expected behavior

When at CLB/OP CLB modes, A/THR is always set to THR CLB / THR MCT / MAN modes

### Steps to reproduce

Can't tell exactly when it happens and why, but it happens sometimes, that's the third time I've seen it, at least.

**Comment by lukecologne** [comment]
This is correct, for level changes smaller than 1200ft, in OP CLB mode, the guidance will use V/S mode with a traget of +1000 ft/min, and the A/THR in speed mode. Although I'm not sure if this also applies to the CLB mode, or only OP CLB. The documentation seems to suggest it's only for OP CLB.

**Comment by Illuminati270** [comment]
> 

Hi there Luke. Not quite.

As you can see, I was still taking off, slightly above acceleration altitude, when the aircraft changed from MAN TOGA / SRS to SPEED / CLB.

Therefore, surely not the case you suggested (1000fpm limit for FL CHG of less when initiating a FL CHG itself).

Also: I don't recall ever seeing SPEED when in CLB. I also believe that if there's any chance of SPEED coming up, that would be when the aircraft is under OP CLB.

**Comment by lukecologne** [comment]
That is exactly what I meant. The reference doesn't specify if this only applies to when the mode is engaged by pulling on the alt knob, or also for automatic mode switches. As I said, we might need to correct this for the managed CLB mode. Further, I think that this 1000ft/min target can currently also happen in OP DES or DES (in our logic), which is also not correct, the reference states that this is only for climb, not descent. (And also only when A/THR is active).

**Comment by aguther** [comment]
> Hi there Luke. Not quite.
> 
> As you can see, I was still taking off, slightly above acceleration altitude, when the aircraft changed from MAN TOGA / SRS to SPEED / CLB.
> 
> Therefore, surely not the case you suggested (1000fpm limit for FL CHG of less when initiating a FL CHG itself).
> 
> Also: I don't recall ever seeing SPEED when in CLB. I also believe that if there's any chance of SPEED coming up, that would be when the aircraft is under OP CLB.

Depends on which altitude it engaged.

But I also checked and no idea why I assumed it’s for all modes (CLB, DES, OP CLB, OP DES). Just also checked it, it seems that should only apply for OP CLB. Easy to change and will do it later.

**Comment by aguther** [comment]
It's now fixed on experimental.
