### ISSUE TITLE
Add a built-in browser to the efb

### ISSUE THREAD

**Issue by chfkmm** [flybywiresim/a32nx#6899]
### Aircraft Version

Development

### Description

请给飞行ipad上个浏览器吧

**Comment by davidwalschots** [comment]
不好意思不可能。瀏覽器在ipad上太慢了。

**Comment by chfkmm** [comment]
> 不好意思不可能。瀏覽器在ipad上太慢了。
我知道了，谢谢你的回答![63302862e99cd964.jpg](https://user-images.githubusercontent.com/94957472/158060729-8972b31b-1042-4127-acc2-c730eae2724a.jpg)
