### ISSUE TITLE
[BUG] Lower ECAM self-test doesn't block entire screen

### ISSUE THREAD

**Issue by UncleClapton** [flybywiresim/a32nx#690]
**Mod Version**

master

**Describe the bug**

Lower ecam is weird.

**To Reproduce**

1. start flight (midflight works best)
2. look at screen

**Expected behavior**

self-test should block entire screen

**Actual behavior**

very top of screen is not blocked.

**References**

![](https://clapton.dev/u/2009/60f0b339.png)

**Additional context**

Discord username:

**Comment by UncleClapton** [comment]
I'm already working on this issue. Reporting it here for the record.

**Comment by topiek-fs** [comment]
Are you sure this isn't due to the javascript console at the top? I haven't noticed this issue yet.

**Comment by UncleClapton** [comment]
@topiek-fs The JS console is positioned separately from the rest of the page, so it should never interfere. I have already found the problem anyway, and it turns out that this was happening because the bottom ECAM screen is being pushed down 5%. It's some really weird styling.

**Comment by 2hwk** [comment]
Similar to #572
