### ISSUE TITLE
Rudder pedals shake or don't move at all when using throttle slider instead of joystick axis.

### ISSUE THREAD

**Issue by flrolsteins** [flybywiresim/a32nx#6908]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-03-13T16:40:31+00:00",
  "ref": "master",
  "sha": "9786b9a0cc80fd670708563e7fb4e985f933b76b",
  "actor": "beheh",
  "event_name": "manual",
  "pretty_release_name": "master:9786b9a0"
}
```

### Describe the bug

I've used the A32NX mod for a while now, and the issue that I'm about to describe only started occurring around a week ago. 
So basically, when I use my Thrustmasters flight Hotas X throttle slider for rudder, it doesn't properly move. The rudder pedals instead start seizure-like moving (they move very fast and only slightly in regards to what I input). Sometimes they don't move at all.  For example, if I hold my slider fully towards the right, the rudder pedals will move only slightly to the right and will instead shake and keep going back to the neutral position as if there was some sort of conflict. I should also mention whenever the rudder pedals shake, the nose wheel tiller also just violently spins. However, when I use my joystick's R-axis Z (which I had configured a long time ago), then they work properly. I don't normally twist my joystick for rudder, since it feels uncomfortable but at the moment its the only way to use rudder and nose wheel steering. I'm not using the separate tiller from rudder option, but it doesn't make a difference at all. So in conclusion, whenever I use my throttle's slider for rudder, the tiller and the rudder pedals just shake abnormally and it's not possible to steer the plane correctly, but when I use my joystick's axis, they both work. 
**Note:** that I have checked in MSFS options that my rudder slider works properly and it displays the correct input

### Expected behavior

I expected my rudder, rudder pedals and nose wheel steering work just as it normally did. It should have moved accordingly to my inputs on my throttle slider instead of shaking and deviating.

### Steps to reproduce

1. Have a throttle slider and joystick R-axis Z both set up for your rudder. (I have Thrustmaster Flight Hotas X)
![rudder](https://user-images.githubusercontent.com/65949463/158074655-aea2071b-62e3-47e5-9f01-a595f502db5a.JPG)

2. Launch in the game, check the airplane's F CTL.
3. When using the throttle's slider, the rudder pedals and nose wheel slider will begin to shake very quickly or spin violently.
![throttelslider](https://user-images.githubusercontent.com/65949463/158074954-fae9c45a-ad78-4580-8fb8-ff2214a84576.JPG)
 

### References (optional)

**1. Here's a video of what happens when I'm using my throttle slider:**

https://user-images.githubusercontent.com/65949463/158075033-5ba11daf-03ff-48f0-bbb5-a345c7c8d297.mp4

**2. Here's a video of what happens when I'm twisting my joystick's axis:**

https://user-images.githubusercontent.com/65949463/158075049-a7ef8844-fbb5-4e45-bf85-20661692430a.mp4

### Additional info (optional)

Been flying close to year now with my current setup and never had this issue. It appeared around a week ago alongside with the current known issues that have happened at the moment. 

### Discord Username (optional)

flrolsteins#6269

**Comment by tracernz** [comment]
Do you have both bound to rudder axis?

**Comment by flrolsteins** [comment]
> Do you have both bound to rudder axis?



> Do you have both bound to rudder axis?

Yes, I believe so, however it had worked earlier before.

**Comment by frankkopp** [comment]
This is definitely not a bug but a conflict on the controller mappings on your side. 
I recommend to join our Discord and ask for help in the support channel if you can't solve it yourself.
