### ISSUE TITLE
Mouse stutter while engines spooling up

### ISSUE THREAD

**Issue by Scheddi** [flybywiresim/a32nx#6914]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-03-13T10:55:26+00:00",
  "ref": "experimental",
  "sha": "b6bb37462f60633811c3a8344d60f246325239cf",
  "actor": "aguther",
  "event_name": "manual",
  "pretty_release_name": "experimental:b6bb3746"
}
```

### Describe the bug

I'm experiencing heavy mouse stutter effects while engines are starting up. It starts when flipping the engine 2 master switch. Stuttering stops again when engines indicate "AVAIL" on ECAM page. FPS stays constant during startup, only mouse movement is stuttering.

I'm in VR mode.

### Expected behavior

no mouse movement stuttering during engine startup

### Steps to reproduce

1. load into cold and dark airplane
2. power up airplane and start engines
3. while engines spool up, watch for mouse movement artifacts

### Additional info (optional)

I only tested this in VR.

### Discord Username (optional)

Scheddi

**Comment by Scheddi** [comment]
I just checked. I don't see this effect in non-VR mode.

**Comment by Benjozork** [comment]
Mouse rendering is not controlled by the aircraft, therefore this is a sim issue.
