### ISSUE TITLE
VFR does wired things

### ISSUE THREAD

**Issue by diehummel** [flybywiresim/a32nx#6928]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-03-15T18:49:30+00:00",
  "ref": "master",
  "sha": "2eef99aa8340295d74f2b60df54240be840dbd08",
  "actor": "davidwalschots",
  "event_name": "manual",
  "pretty_release_name": "master:2eef99aa"
}
```

### Describe the bug

Just want to mention, that the MSFS VFR often does display wired routes, and therefore, the ATC is not working correct.
My testflight is from LOWS 23 to EDDM ILS 08R.
The VFR looks like
![2022-03-17 09_19_30-Microsoft Flight Simulator - 1 23 12 0](https://user-images.githubusercontent.com/18324187/158768452-f0e35012-4f90-4dc6-a09f-a1e10da949b3.png)

Is this something you can fix or MS has to do?
thanks

### Expected behavior

Should be
![2022-03-17 09_27_19-Microsoft Flight Simulator - 1 23 12 0](https://user-images.githubusercontent.com/18324187/158769129-2f756564-6a45-4241-abad-cde5e7dce6b5.png)

### Steps to reproduce

1. Start from LOWS Parking 06
2. Load from SIMBRIEF (SBG2A SBG OTT)
3. Set Departure and Approach and delete FFPL Discontinued line.

**Comment by Benjozork** [comment]
The VFR map is part of MSFS, not the aircraft, and has very primitive drawing capabilities. Therefore it won't be worked on.
