### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by chfkmm** [flybywiresim/a32nx#6934]
### Aircraft Version

Development

### Build info

```json
对不起我找不到
```

### Describe the bug

蜂窝油门不能进行反推操作

### Expected behavior

希望能对蜂窝油门进行支持

### Steps to reproduce

1.反推不能进行操作

**Comment by BalaBalaYi** [comment]
It's not a bug. u can use 'decrease throttle' as reverse for honeycomb bravo.

**Comment by frankkopp** [comment]
https://docs.flybywiresim.com/fbw-a32nx/feature-guides/flyPad/throttle-calibration/

Also please post issue reports only in English!
