### ISSUE TITLE
The ATC System Knob (1-2) is not updated when the LVAR "A32NX_TRANSPONDER_SYSTEM" is updated

### ISSUE THREAD

**Issue by YLevesque34** [flybywiresim/a32nx#6938]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-03-08T20:03:36+00:00",
  "ref": "master",
  "sha": "ad9a63ae880e14334e2c90d7960320f92e3e3971",
  "actor": "aguther",
  "event_name": "manual",
  "pretty_release_name": "master:ad9a63ae"
}
```

### Describe the bug

When the LVAR "A32NX_TRANSPONDER_SYSTEM" is updated using an external program as Air Manager or directly in DevMode/WIndows/Behaviour/Local Variables, the System Knob on the ATC/TCAS instrument doesn't change.

### Expected behavior

The knob rotates when the LVAR changed

### Steps to reproduce

Initial state:  The ATC System (1-2) knob is at 1 and LVAR "A32NX_TRANSPONDER_SYSTEM" is 0
Changes LVAR "A32NX_TRANSPONDER_SYSTEM" in DevMode/WIndows/Behaviour/Local Variables from 0 to 1
The LVAR is updated but the knob doesn't move

### Discord Username (optional)

ylevesque#0416

**Comment by 2hwk** [comment]
Good report, PR #7095 will fix
