### ISSUE TITLE
TCAS broken mid flight

### ISSUE THREAD

**Issue by blooper5** [flybywiresim/a32nx#6943]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-03-16T04:30:32+00:00",
  "ref": "experimental",
  "sha": "5580de440529c19877fe6955f5aa00b6a86721e9",
  "actor": "tracernz",
  "event_name": "manual",
  "pretty_release_name": "experimental:5580de44"
}
```

### Describe the bug

When I was at cruise on vatsim at FL380 I randomly got a traffic advisory in front of me, +11 through +2 alt, sometimes lower, but when I look, nothing is there.

### Expected behavior

No TCAS advisories

### Steps to reproduce

1. cruise inbetween KBWI FND and KMTN right on the border of the NYARTCC at 38000 FT

### Discord Username (optional)

Sad Axolotl#4517

**Comment by blooper5** [comment]
theyve multiplied
![image](https://user-images.githubusercontent.com/46218341/159143660-10ef036f-190a-4666-91dd-0e75a9442bc2.png)

**Comment by TayDex** [comment]
Have you checked if the plane is actually there just not rendered, like an error with model matching for example? Just a guess, had something similar, couldn't see the plane in sim got it on the TCAS tho, looked at Simaware and there actually was a plane.

**Comment by blooper5** [comment]
they were both not there on VFR map and when I turned it to day temporarily, the aircraft was still not there

**Comment by Benjozork** [comment]
The VFR map does not display traffic, and is there is no reason to rely on it with the A32NX. It does not display any data from the plane.

**Comment by blooper5** [comment]
I don't exactly how to check for the aircraft except to physically look, and it wasn't there. on the good side, now I don't have the problem further in my flight.

**Comment by beheh** [comment]
Seems like we can close this issue then if aircraft were indeed present.
