### ISSUE TITLE
Speedbrakes don't extend fully when autopilot is disconnected

### ISSUE THREAD

**Issue by donstim** [flybywiresim/a32nx#6949]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-03-21T05:20:30+00:00",
  "ref": "master",
  "sha": "1e805fb6b8c429f7fb991a8d1fdd205efc4af07c",
  "actor": "tracernz",
  "event_name": "manual",
  "pretty_release_name": "master:1e805fb6"
}
```

### Describe the bug

The maximum speedbreak deflection in flight differs between when the airplane is in manual flight and when the autopilot is engaged:
![Screenshot (2003)](https://user-images.githubusercontent.com/70166617/159217505-3adc7042-e6a6-4878-ae32-6453dc768455.png)
This has been implemented in the A32NX, but there is one issue -- when the speedbrakes are deployed with the autopilot engaged, if the autopilot is then disconnected, the speedbrakes should fully deploy. Currently, they do not. If they are cycled, they will then fully deploy.

If the autopilot is not engaged, when the speedbrakes are deployed, and then the autopilot is engaged, the speedbrakes do correctly go to the lesser deflection angle.

### Expected behavior

When the autopilot is disconnected while the speedbrakes are deployed, the speedbrakes should go to the fully extended position (along with the associated drag increase).

### Steps to reproduce

1. Set up an inflight condition with autopilot engaged.
2. Deploy speedbrakes and note the deflection angle and/or drag level (the latter will be in the speed debug window of the aircraft editor in dev mode).
3. Disconnect autopilot and observe no change in speedbrake deflection or drag.
4. Retract and then deploy speedbrakes again with autopilot still disconnected.
5. Note the higher speedbrake deflection angle and drag level.

### Discord Username (optional)

donbikes#4084

**Comment by crocket63** [comment]
I doubt this to be caused by the hydraulic integration, nor the ground spoiler group we already discussed I think. Need to check FBW demand A32NX_SPOILER_XXX_DEFLECTION_DEMAND first

**Comment by donstim** [comment]
I don't know which PR fixed this, but it has been fixed.
