### ISSUE TITLE
Outer tank fuel transfer ocurring on only the right side

### ISSUE THREAD

**Issue by Venorcis** [flybywiresim/a32nx#6965]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-03-24T17:31:46+00:00",
  "ref": "master",
  "sha": "cdb1a6281a8da541cbce47ff45fd5edf66fccb08",
  "actor": "RichardPilbery",
  "event_name": "manual",
  "pretty_release_name": "master:cdb1a628"
}
```

### Describe the bug

Not sure if this is 100% a bug, but an outer tank fuel transfer started whilst taxiing into the gate (after landing). However when checking the FUEL page after shutdown a few minutes later, the fuel was only being transfered on the right fuel tanks. Not sure if this is related to the APU running on the left fuel tanks, but still strange that this can lead to such a fuel inbalance.

### Expected behavior

Either the fuel transfer not starting after landing or the transfer happening on both sides.

### Steps to reproduce

1. Land with fuel just about the transfer limit.
2. Taxi to the gate, getting below the transfer limit.
3. Start the APU, shutdown the engines, and observe the FUEL ECAM page.

### References (optional)

See https://www.twitch.tv/videos/1435505521?t=01h29m45s for the OUTR TK FUEL XFRD memo to appear for the first time on the ECAM. At https://www.twitch.tv/videos/1435505521?t=01h32m48s I check the ECAM fuel page to see only the right side being transferred.

**Comment by ardyking** [comment]
hello   a320  hdg not working .....why?

**Comment by sidnov** [comment]
> hello   a320  hdg not working .....why?
> 

please use the Discord support channel for this

**Comment by donstim** [comment]
What I see is your left inner tank just above the threshold that would open the transfer valve. Since the fuel used by the engines is not exactly symmetrical, the right inner tank must have dipped below the threshold and started the automatic outer tank to inner tank transfer on that side. Once it starts, it does not stop until you refuel. Since you shut down the engines before the left outer to inner transfer started, you never got below the triggering threshold on that side.

**Comment by Venorcis** [comment]
> What I see is your left inner tank just above the threshold that would open the transfer valve. Since the fuel used by the engines is not exactly symmetrical, the right inner tank must have dipped below the threshold and started the automatic outer tank to inner tank transfer on that side. Once it starts, it does not stop until you refuel. Since you shut down the engines before the left outer to inner transfer started, you never got below the triggering threshold on that side.

makes sense, quite an edge case; wonder if this 'one-side-only' fuel transfer would actually happen on the real airplane too though

**Comment by donstim** [comment]
Why not?

**Comment by Venorcis** [comment]
> Why not?

I'm not an expert at all (that's why I added "Not sure if this is 100% a bug" in the issue), but having a full outer tank on one side and an empty one on the other side seems like a weird situation to get in, you would maybe expect some limit on the fuel transfer on one side if the other didn't start (again, not sure at all about this).

**Comment by donstim** [comment]
Whenever **one** inner tank reaches the level that results in fuel transfer from the outer tank, it starts the transfer from **both** outer tanks. This ensures simultaneous transfer for both wings. Thank you for your question. I will look into changing this.
