### ISSUE TITLE
[BUG] Commercial and Gally & Cab buttons are silent when pressed

### ISSUE THREAD

**Issue by Coralec** [flybywiresim/a32nx#697]
**Mod Version**

965374a (Master)

**Describe the bug**

The Commercial and Gally & Cab buttons do not make any sound when pressed. 

**To Reproduce**

1. Load into aircraft
2. Press Commercial and Gally & Cab buttons on overhead pannel
3.

**Expected behavior**

The buttons should use the same clicking sound that the rest of the overhead buttons use.

**Actual behavior**

No sound is made when they are pressed.

**References**

**Additional context**

Discord username:
@Coralec#5169

**Comment by AdenFlorian** [comment]
@ramon54321 interested in doing this? Should just be a little bit of xml
