### ISSUE TITLE
Logitech radio panels don't work very well with A20NX

### ISSUE THREAD

**Issue by JLD95** [flybywiresim/a32nx#6973]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-03-26T07:17:01+00:00",
  "ref": "master",
  "sha": "37e5f73187f05a420e2e4779f016af102bc0be35",
  "actor": "RichardPilbery",
  "event_name": "manual",
  "pretty_release_name": "master:37e5f731"
}
```

### Describe the bug

With a cold start, Logitech radio panel has no lights on ground or during climb. Works only dury descent. Testing on more 10 flights. It as working fine about a month ago with A20NX

### Expected behavior

Logitech radio panel works during all flight phases like old previous versions of A20NX.

### Steps to reproduce

Select a cold start
On ground, Logitech radio panel has no lights: no possibility to enter XPDR code.
During flight, generally at cruise level, Logitech radio works. On landing, it don't works again

![IMG_20220327_084218](https://user-images.githubusercontent.com/5894146/160271270-d47b5e45-5cf1-4c97-b66e-ae0c043bdeb9.jpg)
.

**Comment by Itherflight** [comment]
Radio works fine if you bind a button to "AVIONICS MASTER 1 ON" & "AVIONICS MASTER 2 ON".

FBW are you able to address this?

**Comment by tracernz** [comment]
I'm not sure that anybody on the team has such hardware, so we'd need somebody to determine the true root cause. Sounds like it's not clear if it's working during some stages of flight.

**Comment by JLD95** [comment]
Hi, if I install trial version of SPAD.neXt, can I solve the bug with appropriate event for Avionics Master Button of Logitech Panel ?

![Presse-papiers-1](https://user-images.githubusercontent.com/5894146/163770364-8d604d47-1f04-4f86-b956-0fa5e0ea9548.jpg)

**Comment by Ithergames** [comment]
> I'm not sure that anybody on the team has such hardware, so we'd need somebody to determine the true root cause. Sounds like it's not clear if it's working during some stages of flight.

Hi there, that is what I did -- it appears that turning on the batteries does not engage a bus that the Logitech radio panel is searching for. It doesn't appear that in MSFS itself that we can tell the Logitech Radio plugin to use something else -- so best course of action is to make sure that when turning on the batteries that AVIONICS BUS 1 ON and AVIONICS BUS 2 ON are triggered.

The radio worked perfectly fine throughout my flight by manually binding keys and doing this.

FYI--this also happens on the default Airbus A320 too--so definitely not FBW code but it should be easy to fix by adding extra event to the battery switches (or even making each battery trigger avionics too) - so Battery 1 also triggers Avionics Bus 1 and Battery 2 for Avionic Bus 2.

**Comment by tracernz** [comment]
Any idea why it starts working during the flight? I'd prefer to understand exactly what the Logitech panel is looking at.

**Comment by Ithergames** [comment]
> Any idea why it starts working during the flight? I'd prefer to understand exactly what the Logitech panel is looking at.

Let me do some digging -- I just realized the original poster said his/her come on midway -- mine never came on the 2 flights I did in the most recent update until I setup the keybinds. I found the keybind hook from a thread on the Flightsim forum.

**Comment by JLD95** [comment]
Hi, 
The problem is solved but I don't know if last Dev has a correction or if I installed and desinstalled SPAD freeware version. I made 4 flights without problems.

**Comment by JLD95** [comment]
Hi, 
The problem is solved but I don't know if last Dev has a correction or if I installed and desinstalled SPAD freeware version. I made 4 flights without problems.

Edit 2022-04-29. Today, with last Dev version, radios panel don't work anymore. 😭

**Comment by aguther** [comment]
There was nothing changed on our side.

**Comment by JLD95** [comment]
I confirm that radio panel works all time only if I set AVIONICS_MASTER_1 & AVIONICS_MASTER_2 even if these 2 variables are not mentionned in FBW API

A32NX_AVIONICS1_ON#1 (>K:AVIONICS_MASTER_1_SET)
A32NX_AVIONICS2_ON#1 (>K:AVIONICS_MASTER_2_SET)

**Comment by aguther** [comment]
@frankkopp
