### ISSUE TITLE
HDG mode, too steep bank angle at low altitude

### ISSUE THREAD

**Issue by FX5F** [flybywiresim/a32nx#6974]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-03-26T22:37:20+00:00",
  "ref": "experimental",
  "sha": "27e5c95f031decd2e66a1dd1d6bbb0ebb39e3529",
  "actor": "aguther",
  "event_name": "manual",
  "pretty_release_name": "experimental:27e5c95f"
}
```

### Describe the bug

When turning in HDG mode at low altitude at low speed the bank angle of the autopilot is 30°. 

### Expected behavior

Then bank angle should be 25° maximum.

### Steps to reproduce

Climb to 5000ft with 220 IAS, turn Autpilot on, fly a turn by turning the HDG knob.

### References (optional)

I found this: https://www.pprune.org/tech-log/377244-a320-321-ap-bank-angle-limits.html#post4988679

**Comment by tracernz** [comment]
Re: the ref, those are the rolls limits for the FM part, during managed guidance. HDG guidance is purely FG.

**Comment by FX5F** [comment]
Here is another possible reference, i know it's just a video, but unfortunately I don't have a reference in a manual.
https://youtu.be/mMNaIOhKcDg?t=148
I have also asked a real world A320 instructor, and he confirmed me that usually it's about 25°.
I know, not really robust references, maybe some else have better ones.

**Comment by tracernz** [comment]
25
![image](https://user-images.githubusercontent.com/9995998/160449058-df154711-3a17-4432-b561-f90ba5634ac2.png)

**Comment by aguther** [comment]
I've pushed an updated bank angle limit calculation to experimental version.

It applies the following rule:
- when not in LOC or LAND:
  - 0 kn TAS = 15°
  - 100 kn = 25°
  - 368 kn = 25°
  - >= 450 kn = 19°
- when in LOC or LAND:
  - 0 kn TAS = 15°
  - 150 kn = 30°
  - 300 kn = 30°
  - >= 450 kn = 19°
- when in LOC or LAND and < 700 ft RA:
  - 10°
