### ISSUE TITLE
Landing lights not extending

### ISSUE THREAD

**Issue by ktafsim** [flybywiresim/a32nx#6976]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-03-27T21:28:03+00:00",
  "ref": "experimental",
  "sha": "f0ac1c851e246770c0906e7295ab62dcb358821b",
  "actor": "BlueberryKing",
  "event_name": "manual",
  "pretty_release_name": "experimental:f0ac1c85"
}
```

### Describe the bug

Landing lights not extending when selected in position on/extended.

The landing lights turn on but do not extended as such the beam points downward instead of forward

### Expected behavior

Landing lights should be extended to point beam forward

### Steps to reproduce

1. Landing Lights lever in position ON

**Comment by tracernz** [comment]
Can't reproduce. Are you turning them on using the switches on the overhead, or some hardware/external binding? Experimental is also not supported.

**Comment by ktafsim** [comment]
No external hardware using the overhead switches. 

Understand experimental not supported, just reporting observed bug

**Comment by ktafsim** [comment]
Problem is due to the livery, in this case Jed Asobo A32NX - ChinaSouthern.

**Comment by BlueberryKing** [comment]
Glad you could fix the issue and thanks for keeping us updated!
