### ISSUE TITLE
Jump-to-waypoint feature

### ISSUE THREAD

**Issue by bluecew** [flybywiresim/a32nx#6979]
### Aircraft Version

Development

### Description

Not sure if anyone even wants this feature and if anyone at FBW are willing to implement something like this, but I would like a jump-to-waypoint feature. I love doing 2-3 hour flights with the A32NX and do a lot of them but I think the cruise is a very boring part of flights. I want to make the cruise shorter so I try to increase the simrate, unfortunately it's limited depending on FPS and in my case, to only 2x speed. I think a feature that allowed the airplane to jump to a waypoint would be handy to have. For example, once I reach my cruising altitude, I could jump immediately to a waypoint near my TOD and skip the boring cruise part where the plane is on autopilot. This isn't really a problem with other airliner addons (MSFS, XP11, P3D) because I haven't encountered one that limits the simrate, I simply increase the simrate a bunch during cruise until the TOD.
This would just be a background feature that people can not use if they don't want to, it's just handy when you need it. But of course, the A320 is short-haul and this feature is entirely not necessary.

### References (optional)

The FlightSimLabs A320 in Prepar3D has the exact feature I'm talking about for reference. It's located in the MCDU by pressing MCDU MENU. It allows you to jump to a waypoint in your flight plan and even allows you to select speed, altitude, heading, etc to jump to and takes into account your fuel and reduces it depending on how far you jump.

### Additional info (optional)

If the 2x simrate limitation didn't exist, then nobody would need a jump-to-waypoint feature. It's the simrate limitation in the A32NX that's annoying.

### Discord Username (optional)

bluecew#7025

**Comment by tracernz** [comment]
Would be a cool feature for the flypad. Also very useful for development.
