### ISSUE TITLE
[BUG] A380X - missing upper deck

### ISSUE THREAD

**Issue by Watsi01** [flybywiresim/a32nx#6985]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-04-01T15:76:86+00:00",
  "ref": "master",
  "sha": "1337wtf7700404",
  "actor": "AGuther",
  "event_name": "manual",
  "pretty_release_name": "master:1337wtf"
}
```

### Describe the bug

Thanks for the first beta release of A380X. I really appreciate it. Such a nice plane. Overall it flies pretty well. There's only one thing: I have only one deck. The upper deck is missing. Maybe I'm doing something wrong. Is there an EFB setting to activate the upper deck???

### Expected behavior

Missing upper deck

### Steps to reproduce

1. Download the A380X beta
2. Go to outside view and check if there's an upper deck

### References (optional)

![A32NX-Einst-02](https://user-images.githubusercontent.com/72334392/161226235-2098c49e-e96d-4dac-ad1b-26f515a7a25a.jpg)

### Additional info (optional)

Oh, and by the way, zhe plane also seems a bit tiny. But I think that's how it always is. Things look bigger irl.

### Discord Username (optional)

RogePete

**Comment by hotshotp** [comment]
My fault, I shouldn't be trusted with a shrink ray 😟

**Comment by derl30n** [comment]
Same issue here, thought missing two engines no?

**Comment by jose07eses** [comment]
how to dowload the a380x???

**Comment by Watsi01** [comment]
Oh shit. I really did miss the 4 engine part. Really.  :-D
