### ISSUE TITLE
Terrain ND show INOP

### ISSUE THREAD

**Issue by ge90toga** [flybywiresim/a32nx#6987]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-03-31T01:30:15+00:00",
  "ref": "master",
  "sha": "e8339b5075a3299e631efcfce803d5f12731d574",
  "actor": "bouveng",
  "event_name": "manual",
  "pretty_release_name": "master:e8339b50"
}
```

### Describe the bug

The Terrian show on ND doesn't seem to work and there is an `INOP` sign next to it.?

### Expected behavior

Terrian should show when close to the ground and there should not be an INOP sign

### Steps to reproduce

1. Load Flybywire 320

### References (optional)

![Uploading image.png…]()

**Comment by ge90toga** [comment]
![Capture](https://user-images.githubusercontent.com/18625029/161253097-e0cfb34c-eaf4-4536-b9eb-ea9e81dabaea.PNG)

**Comment by tracernz** [comment]
This is intended and not a bug. This function is not available as MSFS does not provide access to such data natively and we have not finished building a custom solution.
