### ISSUE TITLE
[BUG] Clicking MCDU MENU button makes MCDU look weird and logs lots or warnings

### ISSUE THREAD

**Issue by AdenFlorian** [flybywiresim/a32nx#699]
**Mod Version**

master b5ff4e910c9a22f325be18c3e8d8877098392d7a

**Describe the bug**

**To Reproduce**

1. cold and dark
2. ext pwr on and batteries on
3. click MCDU MENU button

**Expected behavior**

either nothing should happen if the page isn't implemented, or it should show the menu page.

**Actual behavior**

It starts logging a warning every frame and shifts up the mcdu screen up some pixels so it's not aligned anymore (might be because of the debug thing, but not sure)
![image](https://user-images.githubusercontent.com/3533988/93281159-261d6280-f791-11ea-9987-c8f6a4dc0ac2.png)

**References**

n/a

**Comment by Benjozork** [comment]
> (might be because of the debug thing, but not sure)

Yep, dga told me it's a known issue of the devtools

**Comment by MisterChocker** [comment]
fixed by now
