### ISSUE TITLE
SU9 If you´re seeing this, React didn´t load.

### ISSUE THREAD

**Issue by Daboj1337** [flybywiresim/a32nx#6999]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-04-02T08:14:34+00:00",
  "ref": "experimental",
  "sha": "f73c396d5d75acc2066d9bdbadf979b05dc4c981",
  "actor": "aguther",
  "event_name": "manual",
  "pretty_release_name": "experimental:f73c396d"
}
```

### Describe the bug

Tablet is not working on SU9 Beta

### Expected behavior

Tablet should working

### Steps to reproduce

Open a new flight with the fbw a320

**Comment by SandaleAir** [comment]
Hello,

i have the same Problem without SU9 Beta here.

Greetings,
Sascha.

**Comment by wined2310** [comment]
Same here after latest update of experimental version just minutes ago

**Comment by basilbaby97** [comment]
Same error here. I was prepping for the CTP.

**Comment by Dubstyle050** [comment]
same here

**Comment by mico975** [comment]
Known issue, investigation is ongoing. Switch to dev for now.

**Comment by Daboj1337** [comment]
Seems like it´s fixed now!
