### ISSUE TITLE
Limit microstutters by reducing number of calculations/second

### ISSUE THREAD

**Issue by flytester** [flybywiresim/a32nx#7005]
### Aircraft Version

Development

### Description

Microstuttering seems to be getting worse with the new FMS-system implemented and extended. I recently bought a high-end system and compared to other (paywire) aircraft the A32NX is getting more and more behind in terms of smoothness. My suggestion is to limit the number of calculations wich is being made per second by the FMS. The main thread is reaching its limit very soon now, even on a fast CPU. Hope you can improve the plane this way!

**Comment by Benjozork** [comment]
The FMS does not run on the mainthread.

**Comment by Benjozork** [comment]
Performance optimizations are constantly being worked on - a new PFD and data sync method in experimental already improves things.

I will close this issue as this isn't really a specific bug or request. Let's keep in mind that it's never as simple as it seems.

**Comment by flytester** [comment]
Hi Benjamin,
  
  
   
  
  
   Thanks for your reply. Managed to improve microstuttering by turning off the EFB and cranking up the CPU - speed. Hope you keep up the great job you're doing!!
  
  
   
  
  
   Kind regards,
  
  
   
  
  
   Vincent
  
  
   
  
  
   
    Op 03-04-2022 23:15 schreef Benjamin Dupont ***@***.***>:
   
   
    
   
   
    
   
   
   The FMS does not run on the mainthread.
