### ISSUE TITLE
[BUGS] Autopilot stops following path | TCAS puts on stby by itself | Copilot starts communication with ATC before powering up the plane.

### ISSUE THREAD

**Issue by Shituation** [flybywiresim/a32nx#7007]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-04-02T21:08:17+00:00",
  "ref": "master",
  "sha": "63e97d9837ea95f996630bc831c5d16b10ddf090",
  "actor": "aguther",
  "event_name": "manual",
  "pretty_release_name": "master:63e97d98"
}
```

### Describe the bug

1 - Plane just stops following the path and instead steers away from it to nowhere. Flight plan created with MSFS. Worse results while using LittleNavmap (flight plan gets imported wrong having a lot of "discontinuities".
2 - TCAS sets to "stby" by itself after take off for no reason. ATC warns about "TCAS failure".
3 - Copilot starts communications with ATC even before starting up the plane electrical systems (cold & dark).

### Expected behavior

1 - That the plane follows the plan to the end.
2 - TCAS should stay on AUTO.
3 - That the copilot starts communications AFTER the electrical systems are operational.

### Steps to reproduce

1 - Make a flight plan with msfs, then load it. Fly and see when this happens (random). I'm using SUMU and SABE as starting and ending points respectively.

2- Follow step 1, then after a couple of seconds after TO, ATC may warn about TCAS malfunction.

3 - Follow step 1, it should happen immediately after the flight is ready when cold & dark.

**Comment by Benjozork** [comment]
> 1 - Plane just stops following the path and instead steers away from it to nowhere. Flight plan created with MSFS. Worse results while using LittleNavmap (flight plan gets imported wrong having a lot of "discontinuities".

Without screenshots provided of the ND, FMA and FPLN page we do not know what happened here.

>  2 - TCAS sets to "stby" by itself after take off for no reason. ATC warns about "TCAS failure".

Make sure to check your bindings are correct and no AI copilot funcitons are active.

>  3 - That the copilot starts communications AFTER the electrical systems are operational.

MSFS AI Copilot is not supported and should be deactivated. We have no influence over this feature and cannot assist you with it.

Please note that we do not accept issue tickets on GitHub for multiple issues at the same time.

**Comment by Shituation** [comment]
You guys have this section for any purpose? 

DO YOU HAVE SCREENSHOTS?
YES -> "its microsoft fault" -> closed.
NO -> "no screenshots, no problem" -> closed.

You are getting too far from the base program here and this will result in more and more problems as you get far from main microsoft code, coding your "own stuff" that is not compatible with the base simulator.

I'll stop using the development version since its too buggy and you think the simulator should follow it instead of the addon follow the simulator.

Now the copilot "is not supported" but in the stable FBW version, everything works... this is just bad predisposition.

"thanks" (?)

**Comment by Benjozork** [comment]
Our Discord is more appropriate for getting help like this. GitHub is for already researched, documented issue reports.

> You are getting too far from the base program here and this will result in more and more problems as you get far from main microsoft code, coding your "own stuff" that is not compatible with the base simulator.

I'll stop using the development version since its too buggy and you think the simulator should follow it instead of the addon follow the simulator.

Now the copilot "is not supported" but in the stable FBW version, everything works... this is just bad predisposition.

We are not going to stop development of the aircraft because MSFS does not allow interfacing with its base functionality. This is the exact same as in P3D, FSX, etc. Base features like ATC or the stock autopilot are not made to be customizable since everyone making a serious aircraft implements their own anyway.

For the ATC issue for example - we do not know what MSFS checks to report the message you encounter. We have no way of knowing, since MSFS is proprietary software and we cannot analyze it. This is not documented in the SDK either.

**Comment by Shituation** [comment]
If you make a free product with your time and let things undone, sooner or later you will run into problems with users. That should be something you should have thought before starting the project.. do you really think that I believe that you are doing this for "pure altruism"?.   

TO USERS READING THIS, DISABLE SENDING STATISTICS. THEY SELL YOUR DATA.

If reality hurts your feelings, what can I say, stop developing.

**Comment by tankaan** [comment]
> If you make a free product with your time and let things undone (or things that worked that now don't), sooner or later you will run into problems with users. That should be something you should have thought before starting the project.. do you really think that I believe that you are doing this whole thing for "pure altruism"?... I would like the recipe for paying servers bills out of nothing too.
> 
> TO USERS READING THIS, DISABLE SENDING STATISTICS WHEN INSTALLING, THEY SELL YOUR DATA.
> 
> If reporting bugs hurts your feelings, what can I say, stop developing.
> 
> On a side note, I don't know why developers in general have these bug reporting enabled since all I read in most githubs is the same response: "I do this for free [...insert some excuse and morals here...], so I'm closing this". Then some young virtual hipsters appear on scene to back this claims.
> 
> PS: Discord is just another way to send private data to who-knows-who. Why use discord? why do you force people to use that shitty platform instead of this one (which also sucks private data like all online services). Why do you force people to have another account created on another shitty service when this one has the tools?. Every service has its own "privacy agreement" meaning they suck your private browsing data, location and many others, keep what they want and sell all to other companies. Why do you support that?

you're not helping anyone

**Comment by Shituation** [comment]
> > If you make a free product with your time and let things undone (or things that worked that now don't), sooner or later you will run into problems with users. That should be something you should have thought before starting the project.. do you really think that I believe that you are doing this whole thing for "pure altruism"?... I would like the recipe for paying servers bills out of nothing too.
> > TO USERS READING THIS, DISABLE SENDING STATISTICS WHEN INSTALLING, THEY SELL YOUR DATA.
> > If reporting bugs hurts your feelings, what can I say, stop developing.
> > On a side note, I don't know why developers in general have these bug reporting enabled since all I read in most githubs is the same response: "I do this for free [...insert some excuse and morals here...], so I'm closing this". Then some young virtual hipsters appear on scene to back this claims.
> > PS: Discord is just another way to send private data to who-knows-who. Why use discord? why do you force people to use that shitty platform instead of this one (which also sucks private data like all online services). Why do you force people to have another account created on another shitty service when this one has the tools?. Every service has its own "privacy agreement" meaning they suck your private browsing data, location and many others, keep what they want and sell all to other companies. Why do you support that?
> 
> you're not helping anyone

You are not helping either. They are not helping either. So what gives?

**Comment by sidnov** [comment]
>recipe for paying server bills

https://opencollective.com/flybywire

Feel free to send proofs supporting your claims that we sell any form of data, and kindly requesting you to find a different place to express the frustration you may have in your life.
