### ISSUE TITLE
Go around/missed approach - FMC flight plan bug

### ISSUE THREAD

**Issue by Altycoder** [flybywiresim/a32nx#7015]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-04-07T06:10:36+00:00",
  "ref": "master",
  "sha": "a2906c70d9f97f6effc8276357a025fc3b700fc8",
  "actor": "tracernz",
  "event_name": "manual",
  "pretty_release_name": "master:a2906c70"
}
```

### Describe the bug

On final approach, being told to go around by ATC, once immediate steps taken (thrust, lift nose, gear, flaps etc) the flight plan page of the FMC shows four square boxes.  

To rectify need to go back to init page, reinsert start/finish airport code which re-initialises the flight plan page so that the destination can be selected and the new approach, via etc can be inserted.

### Expected behavior

Flight plan page on FMC should continue to show destination airport and/or alternate flight plan / missed approach rather than showing four white square boxes.

### Steps to reproduce

1. ATC calls out go around
2. TOGA thrust, raise nose, gear and flaps to 1
3. Fly runway heading to 5,000 feet (or safe alt)
4. Declare missed approach on ATC window
5. Switch ATC frequency as direct
6. Await new approach instructions
7. Go to FMC flight plan page to input new approach but cannot as FMC looks like it has crashed (four white square boxes shown).

**Comment by derl30n** [comment]
Can you attach a screenshot of the flight plan page with the error and also post your flight plan aka route.

**Comment by tracernz** [comment]
Know about this one, but haven't managed to investigate deeper yet. Something crashes in the FMGC.

**Comment by Altycoder** [comment]
I didn't take a screenshot at the time I'm afraid and I can retrieve the
simbrief flight plan but it was tweaked in game as I was assigned a
different star or via once I got close (too close) to the destination
(EDDM).

Would the original simbrief flight plan help or not?
