### ISSUE TITLE
ND line not drawn correctly after second direct to same point

### ISSUE THREAD

**Issue by FX5F** [flybywiresim/a32nx#7016]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-04-07T09:44:59+00:00",
  "ref": "experimental",
  "sha": "472f73d68d6e97d0d4cb01a519c6fb6bf33b4544",
  "actor": "tracernz",
  "event_name": "manual",
  "pretty_release_name": "experimental:472f73d6"
}
```

### Describe the bug

When you select a direct to a waypoint a second time, the ND line is not updated to the new T-P point. It seems like only the visual line is affected, but the aircraft is flying it correctly.

Wrong line on ND:
![grafik](https://user-images.githubusercontent.com/77800397/162202469-b04a9078-56da-42c3-8032-5a64c67c873f.png)

### Expected behavior

The line should be drawn from the new and now current T-P.

### Steps to reproduce

1. Spawn EDDM 26R, engines running, enter route EDDM-EDDM, route DM425,DM426,DM427,DM428,DM429, ILS26R.
2. Depart straight ahead, enter DCT DM425 (now the line is correctly drawn)
3. Switch back immediately to HDG mode and fly a few miles straight ahead on runway track
4. Enter again DCT DM425 (important that it's again the same waypoint)

**Comment by gestudio** [comment]
**It happens with any waypoint.** 
Even on route, if you set a DCT to a waypoint, then HDG for a few minutes, and DCT again, the plotted track on the ND does not update and the aircraft flies back to the first direct track plotted initially.

**Comment by tracernz** [comment]
See #7114
