### ISSUE TITLE
flypad pushback page hard to use

### ISSUE THREAD

**Issue by Zchulski** [flybywiresim/a32nx#7019]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-04-07T18:11:40+00:00",
  "ref": "experimental",
  "sha": "10afacbd52729f45a2be22088b677f8978d74330",
  "actor": "aguther",
  "event_name": "manual",
  "pretty_release_name": "experimental:10afacbd"
}
```

### Describe the bug

The pushback page on the Flypad is extremely hard to use.  When you call for the pushback truck the pushback starts right away.  The halt button is inop so once you start pushback you can't stop it without disconnecting the push truck.  

I am also unable to click and drag the sliders for the push speed and turn direction.  Seems you can click a spot you want it but cannot drag the actual bubble.

### Expected behavior

I would expect the pushback truck to connect but not immediately start pushing without pilot consent. I would also expect to be able to drag the speed and turn slider bubble instead of just clicking where you want it.

### Steps to reproduce

1. open flypad after cockpit configured for flight and connect the pushtruck
2. try to initiate a turn while trying to drag the slider

**Comment by tracernz** [comment]
Thanks for the feedback. `experimental` is not supported and as such bug reports are not taken on Github. The pushback page in the upcoming flypadOS is an early WIP, and will be further developed before being merged to a supported version.
