### ISSUE TITLE
cANNOT start extern.l P

### ISSUE THREAD

**Issue by nikolatr71** [flybywiresim/a32nx#7024]
### Aircraft Version

Experimental

### Build info

```json
"built": "2022-04-07T18:11:40+00:00",
  "ref": "experimental",
  "sha": "10afacbd52729f45a2be22088b677f8978d74330",
  "actor": "aguther",
  "event_name": "manual",
  "pretty_release_name": "experimental:10afacbd"
```

### Describe the bug

I noticed in a last few ones that couldn't start external PU, when clicking on that button on overhd. custom view (#8). Namely, after awhile batt P drops from 27.7 Voltages down to 27 when some tm. passed by. 

### Expected behavior

Expected behavior was a default one, w/out goin too much into details: once u press ext. P buton, you should hear click and fan ll start alongside with overhd. electricity.

### Steps to reproduce

Unsure I could ustnd. your query. 

B- ln.: Plane could not be started stuck in cold en dark state. Please fix it.

### References (optional)

> [https://youtu.be/MRdC5MOMLsw]

1. [ ] 

### Discord Username (optional)

nikolatr

**Comment by hotshotp** [comment]
not all airports will have external power available, you need to start the apu in that case
