### ISSUE TITLE
Opening EFB after Toolbar Pushback stops aircraft midair

### ISSUE THREAD

**Issue by peregrine-developments** [flybywiresim/a32nx#7026]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-04-08T20:24:47+00:00",
  "ref": "experimental",
  "sha": "b60966afe46312e7f2db4c8e05e15c4b8fdb8506",
  "actor": "aguther",
  "event_name": "manual",
  "pretty_release_name": "experimental:b60966af"
}
```

### Describe the bug

When using Toolbar Pushback, opening the pushback menu in the EFB can lead to the aircraft being stopped in midair and falling from the sky

### Expected behavior

Opening pushback menu should not stop the aircraft midair

### Steps to reproduce

1. Start a flight
2. Open pushback page on EFB
3. Open Toolbar Pushback
4. Call tug from pushback page of EFB, Toolbar Pushback will also begin
5. Navigate to different page on EFB and complete pushback using Toolbar Pushback
6. Take off
7. Reopen pushback page on EFB

### References (optional)

https://user-images.githubusercontent.com/64386329/162557099-0f9d43e3-a199-4374-9f55-1ce195f92679.mp4

### Additional info (optional)

Problem does not occur if pushback is completed entirely from within Toolbar Pushback, i.e tug is called from Toolbar Pushback and not pushback page of EFB.

### Discord Username (optional)

pererry#8489

**Comment by peregrine-developments** [comment]
Worth noting is the "Call Tug" button on the EFB pushback being illuminated momentarily after reopening the page

**Comment by aguther** [comment]
Can you please retest with the latest experimental?

**Comment by peregrine-developments** [comment]
Retested with build
```json
{
  "built": "2022-04-24T06:52:21+00:00",
  "ref": "experimental",
  "sha": "5d3ebae10f6b42470e24dbd0cc3ce441b83c6c46",
  "actor": "aguther",
  "event_name": "manual",
  "pretty_release_name": "experimental:5d3ebae1"
}
```
Identical steps to reproduce, issue persists

https://user-images.githubusercontent.com/64386329/164967811-1c854710-6879-4afe-9c58-997c575e88d9.mp4

**Comment by aguther** [comment]
To be fair, I used also the add-on and didn’t run into the issue. I think I understand why. you call the tug with the EFB but then use pushback add-on for the rest, correct?

**Comment by peregrine-developments** [comment]
Correct, although the issue also occurs if the tug is called from EFB, and then the in-game ATC is used to end pushback

**Comment by aighes** [comment]
Maybe it would be better to be able to deactivate pages like facility control and pushback in the EFB realism page. So user who don't use it in EFB can avoid using it by mistake.

**Comment by foxmike80** [comment]
You could also just make the pushback page unavailable or disappear if the groundspeed exceeds, say 40kts or so.

**Comment by frankkopp** [comment]
This should be fixed with the latest changes (pushback has been completely overhauled). 
As this was on Experimental I will close this now and not wait until the flyPadOS 3 PR is merged.
