### ISSUE TITLE
Ability to Disembark or Reset Passengers

### ISSUE THREAD

**Issue by AviationSpotter** [flybywiresim/a32nx#7040]
### Aircraft Version

Experimental

### Description

The ability to disembark or reset passengers would add immersion to completing a flight or doing multiple legs without having to reload the aircraft. Even if this is not looked as necessary, I think there should at least be a "reset" button to set the number of passengers back to zero.

### Discord Username (optional)

Aviation Spotter#9102

**Comment by Saschl** [comment]
While a dedicated button/option to start deboarding would be more explicit, you can already do this as of today by entering "0" in the PAX count :)

**Comment by AviationSpotter** [comment]
> While a dedicated button/option to start deboarding would be more explicit, you can already do this as of today by entering "0" in the PAX count and start the (de-)boarding process. :)

I feel stupid for not knowing about this. Would it be better to leave the issue or close?

**Comment by sidnov** [comment]
I think we can close it since it's also documented in the A32NX docs under the WB section
