### ISSUE TITLE
auto pilot bug

### ISSUE THREAD

**Issue by romfootvff** [flybywiresim/a32nx#7053]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2022-01-08T01:22:50+00:00",
  "ref": "v0.7.4",
  "sha": "5adc0dc1ee3bd9cf9386c312b798a5f8ca7b391b",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

Everything works great in the plane except the autopilot, it does not follow any planned trajectory, does not want to follow the selected altitude, as for the flight trajectory, it turns left or right for a long time and returns stable at some point but the plane completely deviates from its flight plan? in terms of altitude if I go down or up the plane does not react.

### Expected behavior

So I expected the autopilot to react and work normally, I notably cleaned up the community folder, made the various updates, but nothing helped.

### Steps to reproduce

1. Launch an IFR flight plan in startup
2. Start the aircraft from A to Z (with request for IFR flight and taxiing)
3. Take off and put the autopilot at the end of the retracted landing gear
4. For me the autopilot does not follow the flight plan

### References (optional)

version msfs : 1.24.5.0
version A23nx : 0.7.4

**Comment by Benjozork** [comment]
* Are you pushing for managed heading / altitude ?
* What is your FMA at the time ?
* Do you have a screen recording / screenshot of the issue ?

**Comment by romfootvff** [comment]
I just want the autopilot to follow the flight plan with the trajectory and also the altitude that I tell it.

what is **FMA?**

This for trajectory : 
https://user-images.githubusercontent.com/103595329/163243340-cf412dcb-c18b-47c1-8e4e-02e870d6bc72.mp4

This for altitude
https://user-images.githubusercontent.com/103595329/163243406-a384ceae-9ba2-42a9-8725-c0a47221f606.mp4

**Comment by Benjozork** [comment]
The FMA is the flight mode annunciator. It is very important to understand in order to know what your plane is doing.

https://docs.flybywiresim.com/pilots-corner/a32nx-briefing/pfd/fma/

**Comment by Benjozork** [comment]
From your first video, you are in RWY TRK. This means you did not engage NAV mode (managed heading) properly.

I recommend going through the beginners guide to learn how to operate the autopilot:

https://docs.flybywiresim.com/pilots-corner/beginner-guide/overview/

And documentation about the lateral modes:

https://docs.flybywiresim.com/pilots-corner/advanced-guides/flight-guidance/overview/#managed-modes

**Comment by Benjozork** [comment]
Two more issues - you stay in V/S for climbing, which is a big no-no - refer to the guide.

Furthermore, you are still in TOGA while the plane is asking you go to back to CLB - see flashing "LVR CLB".

I heavily recommend reading the guide and taking time to familiarize yourself with the aircraft and its FMGC. I will close this issue as this is not a technical bug.

**Comment by romfootvff** [comment]
Ok, thank you very much, it's because the plane is very complete, so you taught me a lot of things, thank you very much.
