### ISSUE TITLE
LPMA: impossible to use GOSG1E SID

### ISSUE THREAD

**Issue by JLD95** [flybywiresim/a32nx#7060]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-04-14T09:21:27+00:00",
  "ref": "master",
  "sha": "c14892868bb801ac1a08b9f98753dbe088a8c34c",
  "actor": "svengcz",
  "event_name": "manual",
  "pretty_release_name": "master:c1489286"
}
```

### Describe the bug

With Simbrief import (LPMA/05, GOSG1E GOSGA UQ143 ORTIS ORTI1X, GCTS/07), at start, when I select GOSG1E SID, impossible to insert SID. I have last Navigraph AIRAC

### Expected behavior

possiblity to valid SID choice

### Steps to reproduce

Start at LPMA gate
Simbrief import (LPMA/05, GOSG1E GOSGA UQ143 ORTIS ORTI1X, GCTS/07)
Select RWY05
Select GOSG1E  

### References (optional)

After Simbrief import

![2022-04-15 (7)](https://user-images.githubusercontent.com/5894146/163601455-17245d0a-3518-43f1-92eb-278f02725042.jpg)

Select RWY05 et select GOSG1E SID
![2022-04-15 (8)](https://user-images.githubusercontent.com/5894146/163601558-b15a7838-4d81-4645-9b3a-14dfdf659e01.jpg)

After ERASE SID because I can't INSERT, LPMA is erased in FPLN

![2022-04-15 (9)](https://user-images.githubusercontent.com/5894146/163601623-5abe814d-199a-40b6-b921-77041506442a.jpg)

**Comment by juliansebline** [comment]
Hello! What if you use the arrows to put another SID in Left 5 then press this key ?

**Comment by JLD95** [comment]
Hi, yes another SID works and now with current Dev, GALO1E works also.

**Comment by tracernz** [comment]
https://github.com/flybywiresim/a32nx/pull/7122 fixed this I believe. Give it a try with the latest dev version.

**Comment by JLD95** [comment]
Hi, to be closed , the last dev works fine now for the SID GOSG1E

![2022-04-30 (1)](https://user-images.githubusercontent.com/5894146/166110080-1a2dae21-1006-452e-960d-1636d198f79c.jpg)

**Comment by tracernz** [comment]
Although.. you will notice the first leg isn't quite interpreted correctly... I've seen the same bug at Madeira.. so will fix soon. I'll close this now as the not loading bug is fixed. Thanks for confirming.
