### ISSUE TITLE
Airspeed night ribbon color.

### ISSUE THREAD

**Issue by KoplaNum** [flybywiresim/a32nx#7066]
### Aircraft Version

Stable

### Description

The Airspeed and Altitude ribbon color doesn't
![545458715454](https://user-images.githubusercontent.com/77222925/163685990-b32f106c-23f9-4a10-8ec5-6c53b7e68b5e.jpg)
 seem right at night.

**Comment by BlueberryKing** [comment]
Lighting is hard to get right in simulators. What I have found helps quite a bit is turning the brightness down at night, so the bloom effect is not as strong.

**Comment by derl30n** [comment]
Turn down the brightness with the brightness selection knobs.

**Comment by KoplaNum** [comment]
Thank you very much for your reply,
