### ISSUE TITLE
Autobrake not arming

### ISSUE THREAD

**Issue by atsbob** [flybywiresim/a32nx#7071]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-04-16T21:51:30+00:00",
  "ref": "experimental",
  "sha": "87e026e1e6410cb82a94715565fa2869077b1d5d",
  "actor": "aguther",
  "event_name": "manual",
  "pretty_release_name": "experimental:87e026e1"
}
```

### Describe the bug

Unable to arm autobrake (Low, Medium and MAX not working). When the button is selected, the arm light quickly flashes and disappears. It also flashes on the PFD as well, and the ECAM memo autobrake item remains blue/incomplete.

### Expected behavior

Should be able to arm when engines are started and ready for takeoff. Also for landing, etc. 

### Steps to reproduce

INIT/Flight Plan/Perf pages completed
Engines started
Flaps set and trim set
Spoiler armed
At this point I would set Autobrake to MAX, but it fails.

### References (optional)

https://www.youtube.com/watch?v=-wsEpqJiUmU

**Comment by Benjozork** [comment]
As indicated in the documentation GitHub issues are not accepted for Experimental. Please reproduce this on dev before we can reopen it.

**Comment by cowreth** [comment]
Also, try to "double right-click". For me, it reenable the autobrake. I guess you're using the Thrustmaster TCA.
You may want to read that : https://docs.flybywiresim.com/fbw-a32nx/support/reported-issues/#tca-throttle-autobrake-disengages-while-looking-around

**Comment by atsbob** [comment]
> Also, try to "double right-click". For me, it reenable the autobrake. I guess you're using the Thrustmaster TCA. You may want to read that : https://docs.flybywiresim.com/fbw-a32nx/support/reported-issues/#tca-throttle-autobrake-disengages-while-looking-around

Nah not using TCA but I'll have to look to see if I have any conflicting key bindings. However I don't see why this is a problem since this problem only popped up within the last 24 hours after build cb62cb7.

**Comment by aighes** [comment]
Using TCA and can confirm, since about yesterday Autobrake can't be controlled anymore neither by TCA nor by clicking the button in Cockpit (doesn't matter which button position of TCA). Before it had the issue with using the free view. But it could be avoided by don't using it before Take Off and during final descent.
