### ISSUE TITLE
Checklist addition/fix

### ISSUE THREAD

**Issue by AkuDaPapua** [flybywiresim/a32nx#7072]
### Aircraft Version

Stable

### Description

Hey guys,
Been enjoying the project so far. It fly's great and everything. I noticed a minor problem with the included Checklist though. Its missing the check to turn on the fuel pumps either in the Engine start or prestart checklist.
Cheers,
Aku

### Discord Username (optional)

AkuDaPapua#3641

**Comment by tracernz** [comment]
Is this check on the latest version of the standard Airbus SOP? AFAIK ours matches it exactly except it doesn't have the runway change checklist.

**Comment by AkuDaPapua** [comment]
Sorta, it's part of the white light extinguishing portion of the Cockpit preparation. It may be that some notes should be made on it. I'm referencing a BAA Training video for the A320 so the guy knows what he is doing. I just noticed that it wasn't an obvious part of the flow and could use some explaining or maybe a secondary checklist under it. If there's official documentation for the checklist it probably has the explanation in that documentation. The documentation would have been read by the pilots before flying the aircraft so they would know when to activate the Fuel Pumps. Considering we don't get that documentation some extra information might be useful.

**Comment by tracernz** [comment]
The Airbus SOPs and checklists were overhauled in late 2021 and most extraneous checks that would safely be detected by some other means were removed. If this was previously on there that's probably why it's gone.

**Comment by AkuDaPapua** [comment]
So I've identified the problem. The in-game checklist is not clear. "Fuel pumps--------check."
What am I supposed to check? It may be advisable to change to "Fuel Pumps On ---------- check"

![16504213620536085872250387981106](https://user-images.githubusercontent.com/103870107/164134278-e1f95e02-06d3-4870-b1e4-fae06f98cae9.jpg)

**Comment by tracernz** [comment]
Ah... that "checklist" is really an SOP rather than a checklist... and is probably quite outdated.

**Comment by AkuDaPapua** [comment]
Ok that's fair. I just was going through the lists and found this as an issue. There seems to be a ton of copied actions now that I think about it. Like I said, I love the project and have been flying the aircraft a ton and am hopefully getting ready to start flight school so I've been practicing stuff like the checklists and everything because I'm wanting to go Commercial. Just trying to help the project by pointing out something that seems to be missing
