### ISSUE TITLE
FBW Crash to desktop when moving camera around

### ISSUE THREAD

**Issue by StewartPS** [flybywiresim/a32nx#7076]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-04-15T14:27:59+00:00",
  "ref": "master",
  "sha": "f50742546923d6741432de63b084e48b409eb343",
  "actor": "svengcz",
  "event_name": "manual",
  "pretty_release_name": "master:f5074254"
}
```

### Describe the bug

I load into FS2020 ready to do a flight, I look around the stunning visuals of the aircraft/scenery and a get a hard crash to desktop. No error messages, nothing. This is reproducable everytime i load into FS2020. It doesn't matter if it's internal or external, the crash still occurs but it's always when moving the camera around. If i keep the camera still, it seems to play ball.

### Expected behavior

To be able to look around the cockpit, external views of the aircraft etc.. but instead there's a CTD.

### Steps to reproduce

1. When loaded I switch to the exterior view
2. I then quickly move the mouse around and after 1-2 seconds I get a stutter, then audio jump and a CTD
3. This is happening everytime now

### Additional info (optional)

I've reinstalled the whole game, cleared community folder, started as amin, made sure everything is up to date but it's still doing it. I reinstalled FS2020 about 2 days ago, since then it's been as good as gold, no crashed at all and I've been able to look around without a crash to desktop. Until I did a flight from Cairo > Dubai of which i decided to download a EgyptAir livery... since doing that it's gone back to before and crashing. I deleted the livery and it's gone back to doing it. I don't want to have to download another 120GB+

### Discord Username (optional)

StewartPS#3743

**Comment by StewartPS** [comment]
I forgot to mention in the original post. I've tried other aircraft and they don't make it crash, so this issue is absolutely relating to FBW as a pose to FS2020. I've tried a handful of different aircraft, locations etc but nothing makes it crash. Soon as I jump in the FBW A320, look around, it then crashes.

**Comment by TayDex** [comment]
Do you use Razer Synapse? Had a similair problem which disappeared after stopping Razer Synapse a few months ago

**Comment by Benjozork** [comment]
How much VRAM do you have?

**Comment by Benjozork** [comment]
Please keep in mind it is also not possible for us to debug CTDs (as they happen in sim code). I recommend opening a ticket on ZenDesk and seeing this guide for common fixes:

**Comment by StewartPS** [comment]
> How much VRAM do you have?

Hi there, i have 32GB of ram. Thanks for the link, I'll open a ticket on ZenDesk. I've already been through those tips religiously but still struggling.

**Comment by StewartPS** [comment]
> Do you use Razer Synapse? Had a similair problem which disappeared after stopping Razer Synapse a few months ago

Just uninstalled it, it deffintely made it last longer before crashing! But ultimately still crashed after about a minute of camera movement

**Comment by Benjozork** [comment]
> Hi there, i have 32GB of ram. Thanks for the link, I'll open a ticket on ZenDesk. I've already been through those tips religiously but still struggling.

Clarifying, I need **V**RAM, so the memory of your graphics card.

**Comment by StewartPS** [comment]
> > Hi there, i have 32GB of ram. Thanks for the link, I'll open a ticket on ZenDesk. I've already been through those tips religiously but still struggling.
> 
> Clarifying, I need **V**RAM, so the memory of your graphics card.

My apoloigies i've got 10GB - Nvidia 3080 is my GPU

**Comment by aguther** [comment]
Do you use any overclocking or CPU, RAM or GPU?

**Comment by pdeswardt** [comment]
I overclocked my GPU (probably a bit too far) and had the same CTD issue when panning around. I backed down the overclock and not had it since.

**Comment by aguther** [comment]
My experience is as well that even slight overclocking can cause a lot of CTD with MSFS. Therefore I recommend trying without any overclocking or tuning first.

**Comment by flieger0815** [comment]
I have the same experiance and no overclocked GPU.

**Comment by aguther** [comment]
I'm not only talking about GPU by the way. In my case I even had issues when using XMP.

In any case: there is not much we can do. At best you send crash reports to Microsoft:
https://devsupport.flightsimulator.com/articles/5483/how-to-report-a-bug-or-crash.html

The last analysis we got from some users related to the experimental version was the deletion of local variable which is impossible to do with the API. Seems an internal error of the sim we have no control about.

**Comment by cowreth** [comment]
Have you looked at this ? https://forums.flightsimulator.com/t/next-pilot-position-action-causes-sim-to-freeze-pc-xbox/472823

I know you're sure about A32x, but I hint you to hint though, out of precaution, having myself tracked the wrong rabbit for a while when chasing this bug.
