### ISSUE TITLE
[EFB] Hoppie login button removed vs Internet Connection Lost

### ISSUE THREAD

**Issue by cowreth** [flybywiresim/a32nx#7077]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-04-16T12:45:03+00:00",
  "ref": "experimental",
  "sha": "f19dfb144e260107370d577b50d94fb3438b10b1",
  "actor": "aguther",
  "event_name": "manual",
  "pretty_release_name": "experimental:f19dfb14"
}
```

### Describe the bug

EFB : There's no more "connect to Hoppie" button, which prevent reconnecting after loss of connection.

### Expected behavior

Usually after a loss of connection, I would expect to be able to reconnect to Hoppie. I can't :)

### Steps to reproduce

1. Start a flight
2. Hoppie will connect automatically
3. Disconnect from Internet
4. Hoppie will not automatically reconnect

**Comment by svengcz** [comment]
What do you mean by loss of connection? I don't know how you can identify an unreachable hoppie-website
