### ISSUE TITLE
[BUG] PFD Altitude indicator "tape" rolls to current flight level when switching views

### ISSUE THREAD

**Issue by chkgk** [flybywiresim/a32nx#708]
**Mod Version**

master

**Describe the bug**

When switching from external views to the cockpit view during climb or descent, you can see the altitude indicator tape (for the lack of the correct phrase) on the PFD play catch up and roll to the current altitude. Low priority, but breaks immersion.

**To Reproduce**

1. Fly level
2. Switch to external view.
3. Increase or decrease altitude (for best effect go +/-5000 feet or more) without switching to the cockpit
4. When target altitude is reached, switch to cockpit view, observe the altitude tape catch up.

**Expected behavior**

There should not be a roll animation of the altitude tape when switching views. It should be at the correct position to not break immersion.

**Actual behavior**

Altitude "tape" rolls to correct position.  

**References**

see [Video](https://youtu.be/Tvbd4V6ZAY8)

**Additional context**

Notably, airspeed indicator tape behaves correctly.

Discord username (if different from GitHub):
Chriskgk

**Comment by Venorcis** [comment]
Can confirm this always happens since 1.8.3.0, quite an annoying visual bug.

**Comment by hotshotp** [comment]
just tested and its fixed
