### ISSUE TITLE
Correct the glareshield model

### ISSUE THREAD

**Issue by kilocharlie1** [flybywiresim/a32nx#7085]
### Aircraft Version

Stable

### Description

The bottom of the glareshield should be flat across, not what it is currently

### References (optional)

![actualA320](https://user-images.githubusercontent.com/88682168/163891968-0b9dab17-b0b5-4ccf-b8be-3eed1fb0f86b.jpeg)
![Inked20220418190802_1_LI](https://user-images.githubusercontent.com/88682168/163892065-151c5243-ff32-417b-b4df-b16f77282341.jpg)

### Discord Username (optional)

GeeMeeKee#9761

**Comment by beheh** [comment]
Thanks for the report. However, please [search for duplicates](https://github.com/flybywiresim/a32nx/issues?q=is%3Aissue+is%3Aopen+glareshield) before filing issues.

Duplicate of #2795

**Comment by beheh** [comment]
Duplicate of #2795

**Comment by kilocharlie1** [comment]
It was filed two years ago and it's still not fixed.

**Comment by Benjozork** [comment]
We're not saying it's not a real issue :) it's just a duplicate of an existing issue already opened.

If is not fixed because our custom model isn't out yet.
