### ISSUE TITLE
The altitude data of STAR and Approach is lost.

### ISSUE THREAD

**Issue by Jek790** [flybywiresim/a32nx#7089]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-04-18T18:11:06+00:00",
  "ref": "experimental",
  "sha": "ae74a666f50b158864851e3f6a8756039ee57839",
  "actor": "aguther",
  "event_name": "manual",
  "pretty_release_name": "experimental:ae74a666"
}
```

### Describe the bug

If you select STAR and Approach at any airport, the first waypoint STAR and the last waypoint Approach have no altitude data in the MCDU. But, the Nav Data has height data for these waypoints. 

### Expected behavior

If you select any STAR and Approach of any airport, the MCDU should show restrictions or indications of altitude and speed for each point. This data should be the same as in Charts. All STAR and Approach points, including the first and last one.

### Steps to reproduce

1. Create a flight plan on the INIT page. For example: LIRF/LEMD.
![image](https://user-images.githubusercontent.com/99715045/164081621-0c9ceb4e-5288-48f9-84f6-3c0bc1571d6e.png)

2. Go to F-PLN and select LEMD => Arrival => ILS Z 32L => ADUXO 1D => trans ASBIN
![image](https://user-images.githubusercontent.com/99715045/164081776-ec0d5448-2260-4354-aab6-167f8444dd5a.png)

3. Return to F-PLN and check altitude limits according to Charts:
ADUXO - B21000.
SIRGU - B14000
...
ASBIN - A6000 .
PDT - A5000
CI(CF)32L - A4000
FI(FF)32 - 4000
![image](https://user-images.githubusercontent.com/99715045/164083269-4dfe24e5-2d51-4120-b0e0-e8fc0c1f2a9b.png)

4. In the MCDU the altitude data of points ASBIN and FF32L is missing. It often happens that the first STAR point also has no altitude in the MCDU.
![image](https://user-images.githubusercontent.com/99715045/164081989-0f45a285-1dde-4557-96c1-4767393d7619.png)

This can also be checked at any airport. The result will be similar.
I use NavBlue, but my comrades checked this problem with Navigraph installed. The result was the same.

### Discord Username (optional)

Пётр Мамонтов#2769

**Comment by Jek790** [comment]
For comparison, this is how these waypoints look at our colleagues from Working Title and Aerosoft
![image](https://user-images.githubusercontent.com/99715045/164084749-8f7a8e25-b626-40bf-a762-efa0fe6aeb25.png)
![image](https://user-images.githubusercontent.com/99715045/164085478-61115aeb-6528-4838-b637-5881b06c0b4c.png)
![image](https://user-images.githubusercontent.com/99715045/164086204-268b51de-7504-4e36-a163-488425a418a4.png)

**Comment by BlueberryKing** [comment]
This is correct behavior. The altitude of the final approach fix is not shown as a constraint on the ND or in the MCDU. This was implemented here: https://github.com/flybywiresim/a32nx/pull/6933.

Particularly, see that there is no constraint altitude shown at EMOSU in the image from the real plane.

**Comment by Jek790** [comment]
I cannot insist that I am right, because I had no experience of a real aircraft.  Versions of the A320 from other simulators had an accurate Faf height.  But I want to ask a question.  If the FI32L point does not determine the exact height, then where is the aircraft descending?  The set altitude on the FCU can be reached on the FI32L or RW32L or after 20 miles.  The aircraft has no target and no limits after passing CI32L, and is descending at -1000 fpm to the target altitude.  What if I set the FCU height to 1900 instead of 4000?  How will the plane behave in this case?  Where will he take the indicated height?

**Comment by BlueberryKing** [comment]
So the way it works to my knowledge is that this is more of a display thing. The aircraft still computes a descent profile which takes this constraint into account, however, it does not treat it as a constraint per see. 

The aircraft uses a database which contains the glidepath angle as well as the final descent point altitude, but this altitude is not shown as a constraint. It is however shown as a G/S intercept on the vertical revision page of the destination airport.

See this, slightly blurry, picture below:
![](https://user-images.githubusercontent.com/9995998/158930090-1f517e72-5711-457f-a969-768eef997e5b.PNG)

Hopefully this makes sense.

**Comment by Jek790** [comment]
This fact is still not assimilated in my head, because I have gaps in the knowledge of Airbus logic.  You are personally involved in the development of a vertical navigation system.  If you are sure that this is correct, then it remains for me to believe you.  Thanks for answers.  Enjoy the project!
