### ISSUE TITLE
Commercial , Galy & Cab

### ISSUE THREAD

**Issue by tareksabet** [flybywiresim/a32nx#709]
**Mod Version**

Master

**Describe the bug**

Commercial , Galy & Cab in Default are off

**To Reproduce**

1.Started the sim
2.Loaded the plane on a gate 
3. Cold & Dark state 

**Expected behavior**

Commercial , Galy & Cab supposed to be On

**Actual behavior**

Commercial , Galy & Cab in Default are off

**References**

![Desktop Screenshot 2020 09 16 - 18 15 42 47](https://user-images.githubusercontent.com/70240330/93365007-8a036200-f849-11ea-8366-7fe079198200.png)

**Additional context**

tarek_sabet#7946 (if different from GitHub):

**Comment by ramon54321** [comment]
This should be a simple fix, simply changing:

A32NX_ELEC_COMMERCIAL_TOGGLE=1
A32NX_ELEC_GALYCAB_TOGGLE=1

In the apron.FLT file.

Saying that though, this would likely become redundant once the electrical system is hooked in.
