### ISSUE TITLE
ND Stuck and Disagreed

### ISSUE THREAD

**Issue by cqhhy2001** [flybywiresim/a32nx#7096]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2022-01-08T01:22:50+00:00",
  "ref": "v0.7.4",
  "sha": "5adc0dc1ee3bd9cf9386c312b798a5f8ca7b391b",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

ND stops displaying the status of the airplane
![image](https://user-images.githubusercontent.com/21079967/164723494-904bc578-d6fb-428a-81b4-796f9493abb8.png)
![image](https://user-images.githubusercontent.com/21079967/164723524-d098e03f-7f97-4ed4-b484-5f58fa4301d1.png)

### Expected behavior

it should update the ARC info

### Steps to reproduce

fly the route as usual

### References (optional)

i was in a multiplayer session with my friend, he had encounter same problem
here's the route 
UKBB/UUEE
KURO3Z KUROS N180 BERUN T296 BUKUB BUKU3E

**Comment by tracernz** [comment]
This has been fixed months ago by replacing the entire ND with our own. Closing this as there's nothing to do.
