### ISSUE TITLE
Spoiler sound gone (again)

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#7097]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-04-22T09:21:28+00:00",
  "ref": "experimental",
  "sha": "8287d87cddfa5d5b495366c8a29115480ab10a18",
  "actor": "aguther",
  "event_name": "manual",
  "pretty_release_name": "experimental:8287d87c"
}
```

### Describe the bug

spoiler sound is gone again - like some weeks ago

### Expected behavior

hear spoiler (wind) sound when using spoilers

### Steps to reproduce

use spoiler in flight

**Comment by hotshotp** [comment]
Just had another person test exp and they hear the drag sounds, this looks like a local issue

**Comment by andrejetcat** [comment]
i also do not have them when landing light are retracted. but I hear the lights

**Comment by hotshotp** [comment]
> i also do not have them when landing light are retracted. but I hear the lights

I fixed your issue last night, try updating and it should be fine now

**Comment by mreza1st** [comment]
Hello, are you sure this issue is resolved? I don't get any spoiler sound even at high speeds. Also, I don't have the cargo door sound with the latest Experimental version (downloaded clean on 4/25/2022). Thanks.

**Comment by andrejetcat** [comment]
I also do not have any spoiler sound in the latest upload from today.

**Comment by hotshotp** [comment]
Oh man, I see what I did in the latest commit, I changed up the SimVar I used but it has a range of 0-1, and I kept the old one in the sound pack which was 0-100... As for the yellow pump I got two reports which is incredibly strange as it worked the previous commit.

Sorry for all the issues haha, I will hopefully fix them today. I guess that's the point of experimental 😄

**Comment by mreza1st** [comment]
No worries! You guys are awesome and I love the new sounds.

**Comment by mreza1st** [comment]
Haha! I think it's too quiet now! Lol! It's pretty loud in real planes specially when deployed at high speed and usually you have the shaking too. 

But, yeah, really thanks for the hard work FBW! You guys are the ones that have made this game fun (at least for me)!

**Comment by hotshotp** [comment]
😆 thanks a lot guys, I'll take your feedback into account and I'll ask some more pilots to check it out as well.

**Comment by aguther** [comment]
I guess for now it’s solved. Feel free to reopen if it appears again. Related to loudness of the sound I suggest opening a separate issue.
