### ISSUE TITLE
AP will not engage if you do a second flight within the same session.

### ISSUE THREAD

**Issue by Ares1378** [flybywiresim/a32nx#712]
**Mod Version**

Newest Master

**Describe the bug**

AP will not engage if you do a second flight in the same session. After takeoff AP1 or AP2 would not engage.

**To Reproduce**

1. Do a flight to a destination, Land Power down. 
2.  Reinit the box to a new destination.
3. Take off, AP1 or AP2 will not engage after takeoff.

**Expected behavior**

AP should be able to engage. 

**Actual behavior**

**References**

**Additional context**

Discord username (if different from GitHub):

**Comment by AdenFlorian** [comment]
did this ever happen before the latest patch?

**Comment by Ares1378** [comment]
No it did not. The only issue I had prior to this patch was the takeoff phase issue on subsequent flights. It will not cycle out of the takeoff phase. It remains in SRS mode and t/o inhibited remains displayed, perf page shows takeoff.

**Comment by MisterChocker** [comment]
has been fixed by now
