### ISSUE TITLE
Sudden 0 ground speed whilst cruising

### ISSUE THREAD

**Issue by Venorcis** [flybywiresim/a32nx#7121]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-04-27T17:53:01+00:00",
  "ref": "master",
  "sha": "53c9747d0806a8b84120a450de021c331b4bcfa4",
  "actor": "aguther",
  "event_name": "manual",
  "pretty_release_name": "master:53c9747d"
}
```

### Describe the bug

I have no idea if this is a generic MSFS bug or not, but I suddenly had 0 ground speed whilst cruising at FL380. Everything still worked and I couldn't find any way to get moving again; even slewing did not help.

### Expected behavior

Keep flying...

### Steps to reproduce

It seemed to have happened out of the blue, I was cruising on a long leg in German airspace.

### References (optional)

https://drive.google.com/file/d/1CeQntIHCmSRBWgDBBcW7J2M3WmxMXYzX

**Comment by aguther** [comment]
You activated Active Pause which does this. Can be seen on the left in the top bar.
