### ISSUE TITLE
pfd: spd flag when pushback tug connected

### ISSUE THREAD

**Issue by tracernz** [flybywiresim/a32nx#7124]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-04-29T11:01:34+00:00",
  "ref": "master",
  "sha": "fa7ea7acf4620dfc3c058edd64d7aef98df7a837",
  "actor": "crocket63",
  "event_name": "manual"
}
```

### Describe the bug

When the toolbar pushback tug connects and lifts the nose of the aircraft, the LGCIU prox sensor simulation detects that the nose wheel is no longer on the ground... the PFD uses the nose wheel prox to determine if it should consider CAS NCD as invalid speed => the speed failure flag.

![image](https://user-images.githubusercontent.com/9995998/165932781-5b0601bd-f007-4c81-bec0-d6f68cba4421.png)

### Expected behavior

Nose wheel strut should remain compressed by the aircraft weight when the pushback tug picks it up.

### Steps to reproduce

1. Power up the aircraft and prepare as normal with all 3 ADIRUs fully aligned in NAV mode etc.
2. Request pushback with the pushback toolbar, can be manual or automatic
3. Upon lifting of the nosewheel, note the SPD flag appears on the PFD

**Comment by Mega-Touk** [comment]
I'm still amazed by the level of details you guys are working on. Thanks everyone working on a32nx who can see this comment.
