### ISSUE TITLE
Master Warning / Caution does not trigger when failure occurs a second time

### ISSUE THREAD

**Issue by aguther** [flybywiresim/a32nx#7126]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-04-29T11:01:34+00:00",
  "ref": "master",
  "sha": "fa7ea7acf4620dfc3c058edd64d7aef98df7a837",
  "actor": "crocket63",
  "event_name": "manual"
}
```

### Describe the bug

When a failure is detected, it usually triggers a master warning or caution depending on the failure. When the failure is resolved, the sound usually stops.

Now when the same failure occurs at minimum the second time, this does not trigger a master warning / caution anymore.

### Expected behavior

Failures should trigger master warning / caution independently if it is the first or a subsequent time.

### Steps to reproduce

1. Spawn on runway with engines running
2. Set flaps to 1+F
3. Set parking brake
4. Put thrust levers to TOGA
5. -> Master Warning with illuminated button and sound, ECAM in red: `CONFIG: PARK BRK ON`
6. Put thrust levers to IDLE
7. -> Sound stops, button distinguishes, ECAM cleared
8. Put thrust levers to TOGA
9. -> No illuminated button, no sound, ECAM in red: `CONFIG: PARK BRK ON`
10. Put thrust levers to IDLE
11. -> ECAM cleared
12. Set flaps to 0
13. Release parking brake
14. Put thrust levers to TOGA
15. -> Master Warning with illuminated button and sound, ECAM in red hinting slats and flaps not in TO config
16. Put thrust levers to IDLE
17. -> Sound stops, button distinguishes, ECAM cleared
18. Put thrust levers to TOGA
19. -> No illuminated button, no sound, ECAM in red hinting slats and flaps not in TO config

**Comment by juliansebline** [comment]
I have found the bug, I'm working on it
