### ISSUE TITLE
Incorrect vertical FMA when AP is disengaged [BUG]

### ISSUE THREAD

**Issue by Ares1378** [flybywiresim/a32nx#713]
**Mod Version**

Newest Master

**Describe the bug**

When in OP CLB or OP DES with AP engaged, when disengaged it reverts to CLB or DES. Also if you are flying with AP disengaged if you pull OP CLB or OP DES it will not change it is stuck in CLB or DES 

**To Reproduce**

1. Takeoff, engage AP. Pull OP CLB or OP DES
2. Disengage AP it will revert to CLB or DES
3.

**Expected behavior**

it should stay in the either managed or Open modes and if you don't have AP engaged and if it was in CLB or DES you should still be able to PULL OP CLB or OP DES if AP is not engaged.
**Actual behavior**

**References**

**Additional context**

Discord username (if different from GitHub):

**Comment by AdenFlorian** [comment]
did this happen before the patch last wednesday?

**Comment by AdenFlorian** [comment]
@Inaxair Are you sure this is an asobo bug? We've done a lot of changes with FMA's, we could've broken something, unless this is how its always acted in game, in which case its a vanilla bug/enhancement.

@DABUS320 Did this ever work as expected in the mod?

**Comment by Inaxair** [comment]
> @Inaxair Are you sure this is an asobo bug? We've done a lot of changes with FMA's, we could've broken something, unless this is how its always acted in game, in which case its a vanilla bug/enhancement.
> 
Well like Autopilot is Asobo's problem

**Comment by MisterChocker** [comment]
using #1981 for tracking
