### ISSUE TITLE
Thrust drops to 20% right after take off

### ISSUE THREAD

**Issue by BanziDuck** [flybywiresim/a32nx#7130]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-04-30T08:12:55+00:00",
  "ref": "master",
  "sha": "cfce7f8c8925c39fc235ef03bd6b0ac4a78055ad",
  "actor": "BlueberryKing",
  "event_name": "manual",
  "pretty_release_name": "master:cfce7f8c"
}
```

### Describe the bug

When taking off as soon as plane leaves the ground engine thrust drops to 20% and plane stalls out.  See video:
[https://youtu.be/l_fe4we8tas](url)  Throttle become un-responsive.

### Expected behavior

Plane should take off and climb.

### Steps to reproduce

Load MSFS2020
Start at gate or runway
Initiate TO
Throttle to TOGA
Reach V rotate
Leave ground and engines reduce thrust on their own.

### References (optional)

[https://youtu.be/l_fe4we8tas](url)

### Additional info (optional)

I have removed and re-installed MSFS and FBW, I have seen issue with Stable and Dev.

**Comment by killyourradio** [comment]
Please check if all your MSFS assistance options are set to off. That usually fixes it.

**Comment by BanziDuck** [comment]
Ok I will double check.

**Comment by BanziDuck** [comment]
Well I did clean install of current Stable, also read a post about Auto Throttle being set at 100kts to start. Sure enough set spd to 210kts and plane took off fine. Never had to worry about that before but learning lesson here. All seems back to normal now.
Thank you

**Comment by tracernz** [comment]
> Well I did clean install of current Stable, also read a post about Auto Throttle being set at 100kts to start. Sure enough set spd to 210kts and plane took off fine. Never had to worry about that before but learning lesson here. All seems back to normal now. Thank you

Please set V speeds on the PERF TO page! You will then get correct thrust and SRS guidance during initial climb.
