### ISSUE TITLE
Bothe engines fail on takeoff

### ISSUE THREAD

**Issue by Scotty4681** [flybywiresim/a32nx#7135]
### Aircraft Version

Stable

### Build info

```json
Latest version
```

### Describe the bug

When taking off from any airport on the a320 engines spool up to toga and once airborne the shut down and cannot restart 

### Expected behavior

Engines to stay running

### Steps to reproduce

Just start any flight as soon as rotate both engines fail

**Comment by Benjozork** [comment]
Please actually fill out the build info like requested.

Are your engines actually **shutting down** or going back to idle?

If they go back to idle, please disable assisted takeoff in MSFS assistance options.

**Comment by Scotty4681** [comment]
Sorry im  not that tech savy ill try your suggestion thanks
