### ISSUE TITLE
[BUG] NO LOADED FLIGHTPLAN (After creating one)

### ISSUE THREAD

**Issue by MillerPC** [flybywiresim/a32nx#714]
**Master**

**When generating a flightplan, the flightplan does not load into the aircraft. No magenta line is created and the Arrival and departure airport is empty in the MCDU.**

**To Reproduce**

1. Create a flightplan, E.G: KPHX TO KLAX
2. Use High ALT airways and use an ILS approach.
3. Start at a ramp, gate or cargo area and proceed to start the aircraft up
4. Look into the MCDU and see that there is no DEP/ARR airport codes input.
5. Go into plan mode and notice there is no magenta line to skip through. 

**Expected behavior**

You are supposed to be able to have a loaded flight plan after creating said plan in the MCDU. You are supposed to have a MAGENTA LINE on the PFD and radar to follow side flightplan.

**Actual behavior**

No flight plan, no magenta line, no flight plan in the MCDU or DEP/ARR ICAO codes. 

**References**

![image](https://user-images.githubusercontent.com/71403725/93376487-ac848380-f827-11ea-9302-51accc5ca2ff.png)
![image](https://user-images.githubusercontent.com/71403725/93376512-b7d7af00-f827-11ea-83c4-6033ecb122b7.png)
![image](https://user-images.githubusercontent.com/71403725/93376543-c45c0780-f827-11ea-946a-baa9672c147f.png)
![image](https://user-images.githubusercontent.com/71403725/93376580-cfaf3300-f827-11ea-80d9-3caa75c5caa5.png)

**Additional context**

Discord username (if different from GitHub):

Miller#0480

**Comment by fourdragons** [comment]
Unless this is a result of today's update, this sounds like a one-off thing. I've certainly never experienced it.

**Comment by MillerPC** [comment]
> Unless this is a result of today's update, this sounds like a one-off thing. I've certainly never experienced it.

This is the result of the update.

**Comment by fourdragons** [comment]
> > Unless this is a result of today's update, this sounds like a one-off thing. I've certainly never experienced it.
> 
> This is the result of the update.

Yeah, I’m already seeing reports of people having to remove this mod due to the update. Mine is still downloading. I won’t even go there, and just remove this mod’s folder. Sucks for these developers, though.

**Comment by ewokninja** [comment]
> > > Unless this is a result of today's update, this sounds like a one-off thing. I've certainly never experienced it.
> > 
> > 
> > This is the result of the update.
> 
> Yeah, I’m already seeing reports of people having to remove this mod due to the update. Mine is still downloading. I won’t even go there, and just remove this mod’s folder. Sucks for these developers, though.

This appears to be an issue in the base game as well - I've removed the mod and am still running into the problem.

**Comment by NathanInnes** [comment]
@MillerPC can you confirm if you're using an FPS mod?

**Comment by MillerPC** [comment]
Not using one, however it seems like ALL of my aircraft has this issue. So i don't think this is linked to A320NX actually.

**Comment by racoonapps** [comment]
I also removed the FPSFix mod from my community folder and the Bus loads the Flightplan now correctly. Seems a problem on that mod.

**Comment by Ares1378** [comment]
I could not replicate this issue. I built a flight plan on the world map KDEN/.KOMA flight plan loaded in correctly. All info is displayed in the MCDU, all fixes showed on the ND going through the plan mode for the route built.

**Comment by 2hwk** [comment]
Investigate if this issue is linked with https://np.reddit.com/r/MicrosoftFlightSim/comments/iw6mis/plane_exorcisms_or_how_i_seem_to_have_reduced_or/

(in this case I doubt it but worth a shot)

**Comment by Venorcis** [comment]
I've never experienced this issue, using several iterations of the master. The old FPS-mod is the likely culprit.

**Comment by veikkos** [comment]
> 
> 
> I've never experienced this issue, using several iterations of the master. The old FPS-mod is the likely culprit.

Removing FPS mode has fixed this issue for everyone I've seen. I think this issue can be closed.

**Comment by MillerPC** [comment]
After cleaning the community folder, my flightplans seems to load. Probably was an issue with the folder? I didn't have the fps mod in so its weird. Regardless, this can be closed since it has nothing to do with A32NX i suppose

**Comment by Prophet2122** [comment]
I had this bug after the update. Fixed by reinstalling the whole game.

**Comment by NathanInnes** [comment]
Going to go ahead and assume this is resolved. If it happens again feel free to reopen.
