### ISSUE TITLE
Aircraft not on Radar.

### ISSUE THREAD

**Issue by KoplaNum** [flybywiresim/a32nx#7142]
### Aircraft Version

Stable

### Description

The Aircraft seen at a very close distance is not appearing on the Radar.
![Aircraft not appearing on Radar](https://user-images.githubusercontent.com/77222925/166142520-cdff50fb-3b63-4ebd-a976-d6b84c1f098f.jpg)

**Comment by aguther** [comment]
What kind of traffic was this, Live, VATSIM, Multiplayer?

Beside that it depends also on the setting of the TCAS if those planes are shown.

**Comment by 2hwk** [comment]
Closed as this should be fixed in all versions (release/dev/exp) as of the release of 0.8.0
