### ISSUE TITLE
TCAS - While AP is doing an avoidance maneuver, switching TCAS to STBY and then to ON again breaks the TCAS system

### ISSUE THREAD

**Issue by Repa24** [flybywiresim/a32nx#7152]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-04-30T15:36:00+00:00",
  "ref": "master",
  "sha": "02f35e12bcaa465975fd11daed12c11c4e6983ee",
  "actor": "aguther",
  "event_name": "manual",
  "pretty_release_name": "master:02f35e12"
}
```

### Describe the bug

When flying towards an airplane with TCAS enabled (ON, ATC 2, ALT RPTG ON, ABV, TA/RA) the system warns you and, when getting closer to traffic, takes over control (as expected). 
But if you switch TCAS to STBY while the autopilot is doing the maneuver, press the MASTER CAUTION button and switch TCAS to ON again, the orange ECAM message ("NAV - TCAS SBY") stays on and TCAS does not really work anymore (no visual/acoustic warnings). Other planes stay still visible on the ND, but apart from that, TCAS is not taking action anymore.

### Expected behavior

Once TCAS is switched ON again, the ECAM message should dissappear and the TCAS system should work just like before the maneuver by the autopilot. (note: I don't know if this is the expected behaviour of the plane in real life)

### Steps to reproduce

1. Fly towards traffic with TCAS enabled (ON, ATC 2, ALT RPTG ON, ABV, TA/RA) - these are the only settings I've tried
2. Wait for the TCAS/autopilot to take over control when approaching other planes
3. While AP is doing the avoidance maneuver, switch TCAS to STBY and press the MASTER CAUTION button (unclear, if pressing the MASTER CAUTION button is crucial for reproducing the bug)
4. Switch TCAS to ON again - result should be as described above

### Discord Username (optional)

Repa24#9413

**Comment by aguther** [comment]
I tested it and I can confirm this. Reason unclear yet. I think it’s not related to the AP itself, but more the TCAS being in an RA and then getting disabled. After that I saw traffic again but no TA or RA anymore.
