### ISSUE TITLE
[BUG] The engine 1 is shutting down

### ISSUE THREAD

**Issue by LorDawid** [flybywiresim/a32nx#716]
**Mod Version**

Master & The newest game version

**Describe the bug**

The engine 1 has shut down at the holding point after retarding the throttle, stopping completely, checking the takeoff config and during the "Cabin Crew please be seated for takeoff" my engine has started shutting down. I have also forgot to turn the IGN/STARE off. Now my engine cannot startup because for some reason the N1 stays at 1% and the N2 stays at 25%

**To Reproduce**

**This is what i have done. Im not sure if it will work the same way**

1. Spawn at the gate, turn the aircraft on (skip the MCDU and flaps), make a dual engine startup and push back
2. Taxi, click the t.o config button, then move the flaps into the 1+F position
3. Taxi onto the holding point, retard the throttle, stop the aircraft from rolling but dont use the parking brake, click the T.O Config button, turn some lights on

**Expected behavior**

The engine should still run

**Actual behavior**

The engine 1 shuts down

Discord username (if different from GitHub): LorDawid#6403

**Comment by MillerPC** [comment]
Just had this issue as well

**Comment by ukflyer** [comment]
same here :(

**Comment by ErikNL80** [comment]
Is an issue in the default Airbus, not from the mod. Without the mod I cannot even start the plane cold & dark. https://forums.flightsimulator.com/t/1-8-13-a320-cold-dark-not-working-anymore

**Comment by ukflyer** [comment]
ah starting on the runway seems fine

**Comment by LorDawid** [comment]
@ErikNL80 Some people cant even start the engine 1, and the fact that it started is i think because i had done a dual engine startup

**Comment by lousybyte** [comment]
Confirmed as a default vanilla bug.

**Comment by CoffeePanda0** [comment]
Can agree, engine can't be restarted either

**Comment by Venorcis** [comment]
> Is an issue in the default Airbus, not from the mod. Without the mod I cannot even start the plane cold & dark. https://forums.flightsimulator.com/t/1-8-13-a320-cold-dark-not-working-anymore

That seems more related to #718, this issue is probably https://forums.flightsimulator.com/t/after-patch-a320-left-engine-starts-then-dies-wont-start-again/273503

**Comment by CoffeePanda0** [comment]
To fix:
Turn off left fuel tank
Open crossfeed
Turn on APU switch and bleed and leave them on
Start right engine first until N1, then N2

**Comment by CoffeePanda0** [comment]
Issue seems to lie in fs-base-aircraft-common/ModelBehaviorDefs/Asobo/Common/Fuel.xml

**Comment by davcpas1234** [comment]
Can confirm the issue is to do with the new fuel balancing code in the base core fuel.xml.

It's seems engine 1 staying alive is dependent on the status of the centre tank fuel quantity when the APU shuts down. If the APU is powered off when the centre tank is empty, engine 1 powers down too, otherwise it remains powered.

So, as long as there is fuel remaining in the centre tank when the APU is powered down, after that, the engine will continue to run normally irrespective of the centre tank even if the fuel subsequently is expended mid flight.

So to temporarily fix the issue make sure you put additional fuel in the centre tank upon startup. (By default MSFS loads with this at 0%).

This also explains why the aircraft is stable if not starting from C&D.

**Comment by nabil74** [comment]
> Can confirm the issue is to do with the new fuel balancing code in the base core fuel.xml.
> 
> It's seems engine 1 staying alive is dependent on the status of the centre tank fuel quantity when the APU shuts down. If the APU is powered off when the centre tank is empty, engine 1 powers down too, otherwise it remains powered.
> 
> So, as long as there is fuel remaining in the centre tank when the APU is powered down, after that, the engine will continue to run normally irrespective of the centre tank even if the fuel subsequently is expended mid flight.
> 
> So to temporarily fix the issue make sure you put additional fuel in the centre tank upon startup. (By default MSFS loads with this at 0%).
> 
> This also explains why the aircraft is stable if not starting from C&D.

Can confirm this behaviour from a few flights.
I now load A320 with enough centre fuel to get me past engine start and apu shutdown.
engines remain active throughout flight.

**Comment by gustavsingh** [comment]
I have the same issue, where engine 1 is shutting down every time I fly.

**Comment by CoffeePanda0** [comment]
Can confirm latest update from iceman no longer has this issue, flying on magic fuel now!

**Comment by Onkelpuh** [comment]
the last beta version from yesterday doesn't work for me
I still have engine 1 going off
I now use the solution with the middle tank
