### ISSUE TITLE
Excessive pitch down below 70ft landing 

### ISSUE THREAD

**Issue by dg1234567** [flybywiresim/a32nx#7161]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-05-05T17:24:46+00:00",
  "ref": "master",
  "sha": "a35b908154e6f0c7951d3e99581d7fd27518aa26",
  "actor": "aguther",
  "event_name": "manual",
  "pretty_release_name": "master:a35b9081"
}
```

### Describe the bug

At approx. below 70ft during landing, there is an excessive pitch down motion induced on the aircraft. I understand there is supposed to be slight pitch down during the flare mode but this happens before the flare mode initiates. Also, the weird thing is, this only happens when landing at a USA airport  

### Expected behavior

Slight pitch down when flare mode is activated at 30ft  

### Steps to reproduce

Land at any airport in the USA

### Discord Username (optional)

dg1234567

**Comment by aguther** [comment]
I tried it in KJFK and cannot reproduce it:
https://user-images.githubusercontent.com/6629914/167085534-1172adec-fd48-4177-be20-d599709c54c9.mp4

I also see now the reason from the code this should be related to location. Providing a bit more information (i.e. having a video) could be helpful and I recommend doing that on the support channel of discord.
