### ISSUE TITLE
Pushback Toolbar lifting the aircraft causes MCDU reset and probably a memory leak

### ISSUE THREAD

**Issue by snobile** [flybywiresim/a32nx#7166]
### Aircraft Version

Experimental

### Build info

```json
{
    "built": "2022-05-07T13:50:10+00:00",
    "ref": "refs/heads/experimental",
    "sha": "19b0c57355ac298f874b75cfe3a45137501d07dd",
    "actor": "aguther",
    "event_name": "manual",
    "pretty_release_name": "experimental:19b0c573"
}
```

### Describe the bug

When Pushback Toolbar starts lifting the aircraft the MCDU will reset and the frames start to drop. CPU memory is also infinitely increasing, as well as MainThread time is increasing.

Screenshots below.

### Expected behavior

Pushback Toolbar can lift the aircraft without causing a MCDU reset and the other above-mentioned issues.

### Steps to reproduce

1. Start MSFS
2. Load FBW A20N Exp on any airport
3. Import any flightplan from simbrief or enter the plan manually
4. set up the plane until you want to pushback
5. open Pushback Toolbar and pre plan the pushback
6. start pushback

### References (optional)

Screenshot before lifting:
![Microsoft Flight Simulator Screenshot 2022 05 07 - 19 29 04 56](https://user-images.githubusercontent.com/11709450/167265599-b8574c8f-0eac-4600-b6ec-cfb3e7b10bb9.png)

Screenshot right after lifting:
![Microsoft Flight Simulator Screenshot 2022 05 07 - 19 29 49 81](https://user-images.githubusercontent.com/11709450/167265619-bff47bbb-3f3c-4511-af98-27c0455f30ec.png)

Screenshot 2 minutes later - already gained 1.7 GB CPU mem (normally i never exceed 9-10 GB)
![Microsoft Flight Simulator Screenshot 2022 05 07 - 19 31 06 76](https://user-images.githubusercontent.com/11709450/167265656-8725d7a6-004e-4628-bf09-821e280e094c.png)

### Additional info (optional)

Pushback Toolbar was working before - last time I used it with Exp was on May, 1st 2022.
Issue started (for me) today with Exp version cff12bc.

When disabling the lifting feature inside Pushback Toolbar it works as intended.

### Discord Username (optional)

Arne#1288

**Comment by Benjozork** [comment]
Please report this on discord - we do not take github issues for the experimental branch. The issue is known
