### ISSUE TITLE
Gravity gear

### ISSUE THREAD

**Issue by Triplecorpse** [flybywiresim/a32nx#7167]
### Aircraft Version

Stable

### Description

Hi. Sometimes I like role-playing and imitate dual engine malfunction. Sometimes I even reach an airport. But I can’t extend the landing gear as it is not functioning. Is it possible to add such feature?

### Discord Username (optional)

Eldar Khaitov#2805

**Comment by crocket63** [comment]
This was just added in dev version, you can switch to dev for your next role plays :)

**Comment by Triplecorpse** [comment]
Thank you a lot, will try.
Thank you for developing such a thing, despite I am a JS dev, I understand nothing in planebuilding :)
Thank you for the recent update
