### ISSUE TITLE
Cockpit Door Video Screen not closing

### ISSUE THREAD

**Issue by MicahBCode** [flybywiresim/a32nx#7168]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-05-04T11:45:46+00:00",
  "ref": "master",
  "sha": "51cf9b4dd0ce7d7af1d3fc7884d654839927750a",
  "actor": "2hwk",
  "event_name": "manual",
  "pretty_release_name": "master:51cf9b4d"
}
```

### Describe the bug

I opened the Cockpit door video view using the VIDEO button in the pedestal panel. Afterwards I wanted to view another page like the ENG page using the ENG button.

This led to showing the ENG page behind the videos view. The video doesn't disapear.

### Expected behavior

I expected the video view to disapear when selecting another view.

The behaviour might have been affected due to using the "COCKPIT DOOR VIDEO" Switch in the overhead panel.

### Steps to reproduce

As described above.

**Comment by MicahBCode** [comment]
Was able to close it again by turning the "COCKPIT DOOR VIDEO" switch in the overhead to ON and then again using the "VIDEO" button in the pedestal.

But anyway I think that must be closable in any case.

**Comment by bouveng** [comment]
You can turn it off by pressing the video button again on the pedestal.

**Comment by komp1821** [comment]
Still sounds like a bug to me. Cockpit door video has the lowest priority of all pages. So selecting any page on the ECAM Control Panel should override the video display. 

I'll verify that later. If needed, I can get a video showing the correct behavior.
