### ISSUE TITLE
[BUG] Dead displays on RADIO and TCAS panels (after MSFS Patch#2)

### ISSUE THREAD

**Issue by stevex77** [flybywiresim/a32nx#717]
**Mod Version**

master / newest MSFS build

**Describe the bug**

Dead displays on RADIO and TCAS panels. Not showing numbers.

**To Reproduce**

1. Spawn at the gate in C&D state
2. Turn on Battery / External power switches
3. Switch to RADIO / TCAS cockpit view

**Expected behavior**

Displays should show numbers when there is electrical power on the bus.

**Actual behavior**

Just dark

**References**

No ref.

**Additional context**

Radios seems to be working but displays are dead when looking through some cockpit views.
When using free look on these views, displays turn on at some angles.
Seems to be related to some cockpit performance optimizations they did in Patch#2.
It's a ASOBO's bug - it's there even without a32nx mod being load.
Don't know if it's fixable here or should be fixed by ASOBO.

Discord username (if different from GitHub):
n/a

**Comment by cradle77** [comment]
I can manage to get them working by zooming out the visualisation and scrolling, they do turn off with the preset camera

Definitely part of their optimisations, IMHO

**Comment by UncleClapton** [comment]
Confirmed Asobo bug. We are looking into what we can do to hotfix it, but this one is ultimately on them.

**Comment by MattPaxtonBel** [comment]
See my comment in Issue #780

**Comment by 2hwk** [comment]
Investigate if this issue is linked with https://np.reddit.com/r/MicrosoftFlightSim/comments/iw6mis/plane_exorcisms_or_how_i_seem_to_have_reduced_or/

**Comment by Venorcis** [comment]
> Investigate if this issue is linked with https://np.reddit.com/r/MicrosoftFlightSim/comments/iw6mis/plane_exorcisms_or_how_i_seem_to_have_reduced_or/

It seems to me that this issue is more related to specific camera positions and according optimalisation mistakes.

**Comment by Highflyer2010** [comment]
this happens with some presets or if your using your using, in my case to adjust the height of the cockpit view if i raise so far down then the they just go blank
