### ISSUE TITLE
CRASH TO DESKTOP. NOT WORKING.

### ISSUE THREAD

**Issue by masterofobzene** [flybywiresim/a32nx#7171]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2022-05-04T09:36:46+00:00",
  "ref": "v0.8.0",
  "sha": "5fc4da3bd95febcc57863bca96231c657e65df51",
  "actor": "aguther",
  "event_name": "manual",
  "pretty_release_name": "stable/v0.8.0"
}
```

### Describe the bug

game crashes before loading flight.

### Expected behavior

to work

### Steps to reproduce

play with FBW plane.
THIS DOESN'T HAPPEN WITH VAINILLA A320.

**Comment by masterofobzene** [comment]
Seems the simulator doesn't like "precission curve" tunning using AMD's PBO.
Setting that to "auto" seems to fix the crashes.

**Comment by aguther** [comment]
The A32NX is more demanding like the vanilla A320 and therefore puts the sim under more load. This increases the probability of crashes, but most of the time they remain a sim issue.

I'm still surprised how fast and often the A32NX gets blamed for those crashes.

Anyway thank you for closing this issue yourself after Resolution this helps reducing work load.
