### ISSUE TITLE
Keyboard binded throttle

### ISSUE THREAD

**Issue by Ostron1** [flybywiresim/a32nx#7183]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-05-06T17:02:10+00:00",
  "ref": "experimental",
  "sha": "3d90866c8c73d12d64fd0012e6f85870c4c56e20",
  "actor": "aguther",
  "event_name": "manual",
  "pretty_release_name": "experimental:3d90866c"
}
```

### Describe the bug

First using the throttle in a session makes the throttle go to climb thrust att first click, i think it should go to minimal thrust instead of climb. This is if your not using a throttle axis.

### Expected behavior

ABOVE

### Steps to reproduce

1. First loading into session
2. With keyboard binded throttle
3. Throttle will go to climb thrust instead of "open thrust".

**Comment by aguther** [comment]
I've created a PR to fix the initial position and pushed that fix also to the experimental version. Should be available in ~ 30 min.
