### ISSUE TITLE
Game crash after click "READY TO FLY" if using dx12

### ISSUE THREAD

**Issue by a20034294** [flybywiresim/a32nx#7195]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2022-05-04T09:36:46+00:00",
  "ref": "v0.8.0",
  "sha": "5fc4da3bd95febcc57863bca96231c657e65df51",
  "actor": "aguther",
  "event_name": "manual",
  "pretty_release_name": "stable/v0.8.0"
}
```

### Describe the bug

Game crash in several seconds after click "READY TO FLY". I use default livery of A32NX, no other plugin and test 3 different ariports. But it's work fine if I use original A320neo in MSFS.

System Spec:
- CPU: 3700x
- GPU: RX570 4G with driver 22.5.1(newest)
- RAM: 16G
- 2560x1440 with render scaling 75%(1920x1080)

Please feel free to let me know if I can provide any information.

Thanks

### Expected behavior

Start normally.

### Steps to reproduce

1. Set render engine to DX12
2. Restart game to take effect
3. Start a flight in world map
4. Click "READY TO FLY"

**Comment by aguther** [comment]
Honestly no idea what we should be about it. If that is the case this needs to be fixed in MSFS. Keep in mind that DX12 is still Beta in MSFS.
