### ISSUE TITLE
MCDU not prefilled with flightplan

### ISSUE THREAD

**Issue by ErikNL80** [flybywiresim/a32nx#7214]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2022-05-16T22:07:55+00:00",
    "ref": "refs/heads/master",
    "sha": "700b4969f7306d0836a9defe3d8a7a9b2b76b5e1",
    "actor": "lukecologne",
    "event_name": "manual",
    "pretty_release_name": "master:700b4969"
}
```

### Describe the bug

I just clean installed the latest DEV version and planned a flight from GCLP to EHRD using the MSFS flight planner. I start the aircraft and go to the INIT and see the flightplan is empty there. After restarting the flight or going back to the world menu, create the flightplan again it *sometimes* works.

### Expected behavior

I would expect the flightplan to be filled in the MCDU.

### Steps to reproduce

1. Create a flight using the MSFS World map planner
2. Start a flight cold & dark
3. Bring the aircraft to life
4. Check the MCDU
5. Verify if the flightplan is correctly loaded

### References (optional)

Flightplan:
![GCLP_EHRD](https://user-images.githubusercontent.com/71258178/168877708-82e66a36-d2b9-4dc2-bc69-5b1690c16950.png)

MCDU after pressing INIT
![EMPTY](https://user-images.githubusercontent.com/71258178/168877691-3e168ffe-dfc6-4774-a82e-52f917e3fdbc.png)

EFB settings are set to MSFS LOAD ONLY.

### Additional info (optional)

This issue also occured in stable, but less often then in the DEV version.

**Comment by 2hwk** [comment]
Can't reproduce, if you can provide the entire flight plan routing then I can take another look (Tried 03L with same STAR/SID and ILS APPR but had no issues with the flight plan showing up)

**Comment by ErikNL80** [comment]
It cannot be reproduced every time, that makes it really hard... I will add some examples if they occur...

**Comment by ErikNL80** [comment]
Cannot reproduce it anymore as well...
