### ISSUE TITLE
ND issues after #7180

### ISSUE THREAD

**Issue by ErikNL80** [flybywiresim/a32nx#7216]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2022-05-18T19:03:16+00:00",
    "ref": "refs/heads/master",
    "sha": "9b67261c0e10ea026958e179c6132c80388da893",
    "actor": "aguther",
    "event_name": "manual",
    "pretty_release_name": "master:9b67261c"
}
```

### Describe the bug

I just did a first flight after #7180 was merged. Noticed issues of the ND not properly refreshing. My refresh rate setting is set to medium. Also the T/O config button is not responsive and needed a few extra clicks in order to work.

### Expected behavior

I would expect the ND to work properly and responsive.

### Steps to reproduce

1. Start a flight cold and dark
2.  Set-up the aircraft and taxi out
3. Observe ND and check other button functionality

### References (optional)

Here is the view when on runway 14L at EDDK:

![EDDK](https://user-images.githubusercontent.com/71258178/169233672-e8ccb5c1-646f-4272-adca-91cabcb8d2a0.png)

**Comment by jcc1953** [comment]
I have the same bug but I don't think it's a refresh problem. The plane is on the good route but the flightplan is not displayed correctly when the selection button is on ARC. If you select NAV it's OK and if you go back to ARC it's now also OK.

**Comment by 2hwk** [comment]
Selected HDG also does not work

**Comment by incredibleoxman** [comment]
Exactly the same problem for me too. Aircraft flies LNAV track correctly but ND doesn't refresh. Having to switch back and forth between NAV and ARC to refresh.

**Comment by MStallen** [comment]
Same problem

**Comment by Venorcis** [comment]
Same problem, NAV - ARC switch works indeed as a workaround

**Comment by dg1234567** [comment]
Same issue here including having to press to config multiple times
