### ISSUE TITLE
[BUG] brightness knobs scroll themselves down with no user input

### ISSUE THREAD

**Issue by A320pilotIRL** [flybywiresim/a32nx#722]
STARTED ONCE THE LATEST PATCH CAME OUT
**Mod Version**
 2.0 stable release 

**Describe the bug**
 cockpit brightness knobs turn themselves down with no input during flight. For example on a normal flight I was just in ALT CRZ chilling and not touching any keys or changing any views, hands off the keyboard, and brightness knobs for bot PFD and NDs and the FCU sporadically scroll themselves down, making the flying experience miserable.￼

**To Reproduce**

Conduct normal flight. I flew KPAE to KSEA 

1. Just fly a normal flight. Occasionally use mouse wheel to change zoom or spin knobs
2.
3.

**Expected behavior**

Shouldn't happen

**Actual behavior**
 happened

**References**

**Additional context**

Discord username (if different from GitHub):

**Comment by nabil74** [comment]
Is this before or after MS patch two?

**Comment by PCGamesF1Tech** [comment]
I also had (only) my PFD completely dark (knob turned down) after some minutes of flying around and when switching view from outside back to the cockpit.

**Comment by ChruutvoLuzi** [comment]
Can confirm, my pfd just went black while in final approach :/ you can also hear the clicks of the potentiometer going down

**Comment by davydecorps** [comment]
Well for what's worth after having lot of crashes after new patch I had to clear whole community folder and had that same behaviour on default A320. So doubt it's caused by the mod.

**Comment by 0nnyx** [comment]
Didn't have this problem with the default A320 (didn't try with the modded version). Also got the problem with the modded 787 but not the default 787. Might need more feedbacks before setting bug-vanilla tag

**Comment by PCGamesF1Tech** [comment]
Yep, default 320, dark PFD now after "patch".... 🙄

**Comment by polyefko** [comment]
confirm as well after 1.8.3 u[pdate

**Comment by wststreet2** [comment]
I can confirm it's happpening to me too, but in my case it always happens on approach, there is this time during the approach where the game lags quite a lot (below 1fps while my average is 40fps)

**Comment by 2hwk** [comment]
Investigate if this issue is linked with this 
https://np.reddit.com/r/MicrosoftFlightSim/comments/iw6mis/plane_exorcisms_or_how_i_seem_to_have_reduced_or/
