### ISSUE TITLE
RJTT OPPAR3 is not flown correctly

### ISSUE THREAD

**Issue by nickchen120235** [flybywiresim/a32nx#7220]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2022-05-18T19:03:16+00:00",
    "ref": "refs/heads/master",
    "sha": "9b67261c0e10ea026958e179c6132c80388da893",
    "actor": "aguther",
    "event_name": "manual",
    "pretty_release_name": "master:9b67261c"
}
```

### Describe the bug

When departing from 16L/R, there's a continuous left turn till heading 239 to intercept radial outbound to fix leg. It's being flown by right turn direct instead of following the procedure. ND is rendering the turn correctly (if ignoring the recent heading-incorrect issue). MSFS default nav data is used.

Btw the rendering of the intercept leg is also wrong.

### Expected behavior

It should be flown according to the chart.

### Steps to reproduce

1. Spawn cold & dark at RJTT
2. Route: RJTT OPPAR3 UTIBO, **make sure depart rwy 16L/R is chosen**
3. Taxi out and take off, turn on autopilot after airborne
4. Observe the issue after passing `HME/08` waypoint

### References (optional)

Official chart
![Official chart](https://user-images.githubusercontent.com/45678482/169341779-69a772f2-9b0c-41eb-af5f-4f5bc6c802a0.png)

Wrong INTCPT rendering
![Wrong INTCPT rendering](https://user-images.githubusercontent.com/45678482/169341645-7862f92b-10e8-4d6b-851d-b178d6c1d54c.png)

[Recording](https://youtu.be/zov87-fvOMs)

### Additional info (optional)

Not sure if this type of leg is fully implemented/supported.

### Discord Username (optional)

nickchen120235#9303

**Comment by tracernz** [comment]
With navigraph data... the forced turn not being respected by guidance in some cases is know... need to fix.
![image](https://user-images.githubusercontent.com/9995998/170829906-077b536e-8a4a-46de-9bf3-d4fe64a549e2.png)
