### ISSUE TITLE
ND is Freezing with latest Dev Version

### ISSUE THREAD

**Issue by Koellerman** [flybywiresim/a32nx#7226]
### Aircraft Version

Development

### Build info

```json
"built": "2022-05-20T00:50:23+00:00",
    "ref": "refs/heads/master",
    "sha": "b488ef8a6dc16c966e8423cbf373b9e37dfa0ca7",
    "actor": "lukecologne",
    "event_name": "manual",
    "pretty_release_name": "master:b488ef8a"
```

### Describe the bug

Start a flight and after takeoff, and the ND is starting to freez when you follow the flightpath in ARC mode. When you swith on the EFIS Panel between Plan and ARC its like refreshing the position after a while its freezing again but just with the wrong heading. the yellow flight symbol is following the the path but shows the completly wrong direction 

### Expected behavior

The yellow flightsymbol should follow the flight Path with the correct heading and is moving when you fly a left or right turn

### Steps to reproduce

After starting the flight. On the ground everythink works fine.

**Comment by Saschl** [comment]
Please update to the lastest version. This issue has been fixed with #7219 :)
