### ISSUE TITLE
f-pln page in fms is empty

### ISSUE THREAD

**Issue by karimoDev** [flybywiresim/a32nx#7233]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2022-05-22T15:30:00+00:00",
    "ref": "refs/heads/master",
    "sha": "d52a9f331e49ac9f91a6e71334d849accba9f035",
    "actor": "2hwk",
    "event_name": "manual",
    "pretty_release_name": "master:d52a9f33"
}
```

### Describe the bug

when I click in fpln button to enter the route it s always empty

![FPLN](https://user-images.githubusercontent.com/59665986/170289487-24839493-893a-4c24-8f28-ae28adb82101.png)

 when I use to install the v0.7.5 everything it s ok

### Expected behavior

normally it should be something like this
![ba03ebd5026260c02e4cbf1db72b7223f7c0372f_2_690x388](https://user-images.githubusercontent.com/59665986/169908395-bc1b0b88-4ce2-457e-abdb-a0c4f88560f2.jpeg)

### Steps to reproduce

power the aircraft
init the flight by entering from/to airport
once I want to enter the flight route the page it s empty as I mention before
I try to reinstall the fbw plane using the fbw installer but I still got the same issue

**Comment by klauscritchley** [comment]
having the same issue

**Comment by klauscritchley** [comment]
> 

literally every route I have tried I get this issue

**Comment by Benjozork** [comment]
Please fix your bug image upload as it's invalid right now so we don't see what you mean

**Comment by karimoDev** [comment]
i just upload the bug image

**Comment by 2hwk** [comment]
Try this:
https://docs.flybywiresim.com/fbw-a32nx/settings/?h=utf8#utf8-support

**Comment by karimoDev** [comment]
I still have the same problème

But when i Rey to install old versions liké v0.7.5 it work perfectly thé only problème is that i Can t find stars or arrival runway

**Comment by karimoDev** [comment]
https://youtu.be/zfDwFXzailo

**Comment by 2hwk** [comment]
Try asking in our support channel in discord, I think it would be easier to help figure out the issue there.

**Comment by 2hwk** [comment]
also make sure you are on the latest MSFS version.
