### ISSUE TITLE
Autopilot LVAR gone AWOL

### ISSUE THREAD

**Issue by AdamNZ** [flybywiresim/a32nx#7234]
### Aircraft Version

Development

### Description

A short while ago, I wrote a script for FSUIPC that disabled control inputs whilst in autopilot:
https://flightsim.to/file/31296/autopilot-freeze-controls-lua-scripts

This would allow me to pan around, taking fancy screenshots, without disturbing the aircraft whenever I accidentally moved the stick.

The script looked for a specific LVAR (A32NX_AUTOPILOT_1_ACTIVE) - but the current version of the FBW A320 doesn't seem to present this variable any more. Either that, or SU9 and/or recent versions of FSUIPC aren't seeing it.

Does anyone know if there's a similar variable I could scan for?

TIA - and keep up the good work!!!!

**Comment by tracernz** [comment]
That variable drives the FMA on the PFD... so if you can see AP1 on the top right it is working. 

You can check Lvars in general with the dev mode in MSFS... Windows menu -> Behaviors -> LocalVariables tab
![image](https://user-images.githubusercontent.com/9995998/169979643-c4d644c7-0fd5-4b2b-bfd3-c44a791aaa36.png). In this dialog you can search for Lvars, view their values, and even change their values.

https://docs.flightsimulator.com/html/Developer_Mode/Menus/Windows/Behaviors_Debug.htm

**Comment by AdamNZ** [comment]
Thanks for the info!!! Yes - the autopilot status is being displayed in the debug window (as well as in FSUIPC). Not sure why it wasn't working before, but it all appears good now - with no changes to the script. Handy to know I can access these values from the SDK as well.
Thanks again!
