### ISSUE TITLE
FBW development and experimental

### ISSUE THREAD

**Issue by joefly64** [flybywiresim/a32nx#7235]
### Aircraft Version

Development

### Build info

```json
last
```

### Describe the bug

when I m in Climb NAV in visor goes in HDG and it is not possible then  go in managed mod,it can depend from the livery?

### Expected behavior

none

### Steps to reproduce

none

**Comment by derl30n** [comment]
Please specify step by step what happens/leads to the issue. Please also submit your flight plan including the SID as well.
Please also fill in `Expected behavior` what you think should happen.

**Comment by derl30n** [comment]
Closing since no response from the op.
