### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JacobKreindler** [flybywiresim/a32nx#724]
**Mod Version**

master

**Describe the bug**

The side stick snaps to the side when pushed left and right more than 70%

**To Reproduce**

1. Start a flight and move the side stick left or right
2. Watch the in game side stick snap to it's limit when the IRL joystick/yoke is too far left tor right
3.

**Expected behavior**

The side stick should be smooth from 0% - 100% of it's movement

**Actual behavior**

The stick snaps to the 100% mark when the joystick is still at 70%-80%

**References**

**Additional context**

Discord username (if different from GitHub):
JacobK

[A32NX Sidestick Snap.zip](https://github.com/flybywiresim/a32nx/files/5235779/A32NX.Sidestick.Snap.zip)

**Comment by ChruutvoLuzi** [comment]
Works for me. Check your Joystick sensitivity as it is set up as a non linear curve as default.

**Comment by UncleClapton** [comment]
This is likely due to the default control curves in your settings. Our mod hasn't really done anything low of enough level to affect the plane like this yet.

**Comment by JacobKreindler** [comment]
My curves were set to 0% and it was even worse they are set to about 40% right now.


Jacob K

**Comment by AdenFlorian** [comment]
if its an issue with the game, then its probably a vanilla bug.
