### ISSUE TITLE
Rogue Rudder Controls

### ISSUE THREAD

**Issue by dg1234567** [flybywiresim/a32nx#7240]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2022-05-25T15:31:49+00:00",
    "ref": "refs/heads/master",
    "sha": "b74e38f0a84c7ba156253d43007285ba931dd23d",
    "actor": "2hwk",
    "event_name": "manual",
    "pretty_release_name": "master:b74e38f0"
}
```

### Describe the bug

Random extreme rudder movements not done by the myseld, and i am sure of that because i use the thrustmaster sidestich as my rudder and i have a deadzone of 45% so i dont accidentally twist the joystick. See both videos uploaded; one shows the outside view and one shows the fltcntrl view of the ecam page. im not sure if there is something wrong my joystick or there actually is an issue which is why im making the bug report. the aileron and elevator inputs were done by me. just the rudder 

Flight control view
https://imgur.com/a/hikurL4   

external view
https://www.veed.io/download/666d7d21-3271-4a60-bf80-a1d5fb76f549?source=compressor-sharing

### Expected behavior

No random unprovoked rudder inputs

### Steps to reproduce

Land at any airport

### Discord Username (optional)

dg1234567

**Comment by Benjozork** [comment]
Do you have the "Auto Rudder" assistance on in MSFS ? If so, disable it.

**Comment by dg1234567** [comment]
I don't believe I do but I will double check when I get back from work tonight.

**Comment by derl30n** [comment]
Please check your input devices axis in e.g. device manager and see what movements are being recognized to ensure your device in functioning properly.

**Comment by dg1234567** [comment]
done, everything appears to be normal from the device manager side

**Comment by dg1234567** [comment]
Turned out to be the sensor inside my thrustamster stick that was loose but I go it to work in the end.
