### ISSUE TITLE
Problème MCDU et plan de vol

### ISSUE THREAD

**Issue by romfootvff** [flybywiresim/a32nx#7245]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2022-04-26T18:03:23+00:00",
  "ref": "v0.7.5",
  "sha": "1ae566e18183f6dfd44a21ff47083a8a17c1f8a3",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

J'ai un problème lorsque je veux saisir le SID, car soit celui que je cherche n'y est pas soit par exemple dans mon plan de vol j'ai "IRMAR6A" tandis que dans le MCDU j'ai "IRMA7A", ce qui ensuite fait défaut aux voies respiratoires et les waypoint.

### Expected behavior

Je m'attends donc à pouvoir entrer plan de vol comme indiqué que je génère via SimBrief sachant que je suis parfaitement la procédure de programmation du MCDU avec le guide FLYBYWIRE.

### Steps to reproduce

1. Générer un plan de vol via SimBrief
2. Suivre le guide de préparation du MCDU FlyByWire
3. Arriver à l'étape SID

### References (optional)

![image](https://user-images.githubusercontent.com/103595329/170718935-27309f4f-f182-4097-bf5d-19bf628e78cd.png)

![image](https://user-images.githubusercontent.com/103595329/170719433-31e23d25-854d-43e1-9911-180cd11aaf98.png)

**Comment by Benjozork** [comment]
Quand les noms de SID différent d'un chiffre comme ça c'est généralement car l'AIRAC utilisé sur simBrief est pas le même que celui installé sur le sim.

**Comment by romfootvff** [comment]
Il faut faire quoi pour avoir le même AIRAC ou pour régler ce problème du coup ?

**Comment by romfootvff** [comment]
D'accord et bien merci beaucoup pour cette réponse.
