### ISSUE TITLE
[BUG]Changing outside view to inside lights

### ISSUE THREAD

**Issue by Berniep94** [flybywiresim/a32nx#725]
**Mod Version**
0.2.0

**Describe the bug**
When you change your camera outside, then you came back to the cockpit the overhead lights just sarts to light in a reverse disolve.

**To Reproduce**
1.
2.
3.

**Expected behavior**
just to fix it, i dont know if its an asobo thing.

**Actual behavior**

**References**
[<a href="https://ibb.co/yBny4XD"><img src="https://i.ibb.co/bRgBbPx/Flight-Simulator-b-K3bf-Os-FSj.jpg" alt="Flight-Simulator-b-K3bf-Os-FSj" border="0"></a>](url)

**Additional context**
none, great job guys keep it up!
Discord username (if different from GitHub):

**Comment by DoToAdventures** [comment]
What graphic settings are you running? 
I have observed this behaviour to a much milder extend myself. I believe this is to do with the rendering the engine does.

**Comment by aboodilatif** [comment]
experianced this myself yesterday, not sure if it was present before the latest patch, but i never noticed it before. it has the same behaviour of the light 'turning on' slowly, similar to the "align" light when setting the ADIRS to NAV

**Comment by NathanInnes** [comment]
Always been a thing since the start of the sim, happens with all light sources

**Comment by AdenFlorian** [comment]
try a different AA mode.
