### ISSUE TITLE
[BUG] ZFW CG Incorrect

### ISSUE THREAD

**Issue by donstim** [flybywiresim/a32nx#726]
**Mod Version**
Master

**Describe the bug**
On INIT page 2 of the FMGC, the ZFWCG appears to now be automatically entered. However, the value entered appears to be the value taken directly from the flight planner weights page. This value is not the zero fuel weight (ZFW) CG, it is the CG for the current weight. You can verify this by moving the fuel slider to zero, so that the airplane weight is the zero fuel weight. The CG changes. It is this CG that is the ZFW CG.

**To Reproduce**
see above

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Discord username (if different from GitHub):donbikes

**Comment by CoffeePanda0** [comment]
I believe #648 should help fix this, it is currently in a draft status but hopefully should be out soon

**Comment by lousybyte** [comment]
I don't think the sim uses ZFWCG at all internally, even if there are `zfwcg` named variables around in the code, they all use the actual current CG provided by the API. 
Haven't noticed any way to get the ZFWCG without doing some hacks around with the fuel quantity, unless it's not documented yet.

**Comment by lousybyte** [comment]
Related #605
