### ISSUE TITLE
A320NX Fuel auto reset

### ISSUE THREAD

**Issue by noobielameo** [flybywiresim/a32nx#7270]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2022-05-14T22:16:17+00:00",
    "ref": "refs/tags/v0.8.1",
    "sha": "19e968cadc00d3c28df3b54996da92ce975b0c92",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.8.1"
}
```

### Describe the bug

The fuel level keeps resetting to a low level. Unable to make a permanent change.

### Expected behavior

Able to change at fuel page and do not auto-reset the fuel level

### Steps to reproduce

1.After loading
2.Open Fuel Page
3. Change the fuel level by sliding the fuel level bar
4. wait 1 secs and it will auto-reset

### References (optional)

(https://drive.google.com/file/d/10i8RR9Gd_o0GjJTSALq2bVgk3Mj7Snj1/view?usp=sharing)

**Comment by killyourradio** [comment]
Refueling is done through the efb.

Read here: [docs.flybywiresim.com](https://docs.flybywiresim.com/fbw-a32nx/feature-guides/loading-fuel-weight/)
