### ISSUE TITLE
[REQUEST] Icing enhancements and fixes

### ISSUE THREAD

**Issue by donstim** [flybywiresim/a32nx#728]
**Is your feature request related to a problem? Please describe.**
The icing simulation in MSFS is in some ways a step forward, but in other ways is very unrealistic. From a visual standpoint, the airframe, flap track fairings, and other surfaces directly impinged upon by any fluid in the air would NOT ice up. The visuals of the A320 in icing conditions are very unrealistic.

Also, in the A320, the pitot probes and windows are automatically heated. There is no need to turn them on using the switch on the overhead panel. However, in MSFS in icing conditions, the probes and windows will ice up if they are not turned on via the switch. If the pitot probes ice up, airspeed can be lost. 

The use of engine and/or airframe anti-ice results in a penalty to airplane performance because hot air is bled from the engines. The engine flight idle speed is increased and there is a small loss of thrust at a given N1. If engine anti-ice is not used in icing conditions, there can be an even greater loss of thrust and increase in drag to due icing of the nacelles and fan blades. If the wing anti-ice is not used in icing conditions, there can be an increase in stall speed (loss of Cl at a given AOA) and increase in drag. I don't know how well this is modeled in MSFS.

**Describe the feature you'd like to see implemented**

1. Change the visual representation of icing on the A320 airframe. Ice should only build up on certain surfaces that are directly impinged by an fluid in the atmosphere (e.g,, engine nacelles and fan blades and wing leading edges).
2. Set whatever switch needs to be set such that window and probe heat are always on.
3. Check to see if use of wing and/or engine anti-ice reduces engine thrust and increases engine idle N1. If not, implement this.
4. Check to see what effect wing or engine ice has on airplane performance -- stall speed, drag, engine thrust - - fix as necessary.

**References**
I think you guys have all the FCOM stuff you would need for the A320 anti-icing system and performance effects, but if not, I may be able to provide additional general info on icing in transport category airplanes.

**Additional context**
Have been interested in this for a while, but finally decided to put this in as a result of having my concerns echoed in this YouTube video:  https://www.youtube.com/watch?v=O170fbsUTgU

Discord username (if different from GitHub):donbikes

**Comment by UncleClapton** [comment]
Icing is a core feature of the game, and not necessarily something we have control over. Further, Pitot heat issues might have been fixed with the latest Asobo patch, but we haven't confirmed that the changes we've seen in their code works.

**Comment by donstim** [comment]
I don't understand the comment. Icing may be a core feature of the game, but you don't have any way to control the effects on any particular airplane, such as visual and performance effects, or the functioning of any systems dealing with icing?

**Comment by donstim** [comment]
As a first step, is there a way to have the window/probe heat always active (as on the real airplane) without having to select it on the overhead and without illuminating the overhead switch?

**Comment by donstim** [comment]
Thanks. I see that auto pitot heating has been added. I am hoping that A/I bleed effect on thrust and icing drag effects can be added later. I may make a proposal on the latter in due time.
