### ISSUE TITLE
msfs 2020 will not load a flight 

### ISSUE THREAD

**Issue by Maverick0482** [flybywiresim/a32nx#7287]
### Aircraft Version

Development

### Build info

```json
built	"2022-06-08T22:16:02+00:00"
ref	"refs/heads/master"
sha	"b94277fba4b5a3014c4693afd0e4e75b6c1fc8a0"
actor	"frankkopp"
event_name	"manual"
pretty_release_name	"master:b94277fb"
```

### Describe the bug

When loading a flight with the flybywire a32nx, msfs gets stuck on the load screen. I tried deleting the aircraft from the community folder and switching to the stable 8.1 version with the same result. 

### Expected behavior

load flight at designated airport. 

### Steps to reproduce

Load any flight

### Additional info (optional)

I'm not sure if it would affect it or not but this did not start happening until after installing the PMDG 737 that just came out.

**Comment by tocuarzo** [comment]
It happens to me too, but it is not stucked, it only takes a lot of time to load, if i leave it there for about 15 mins or so (no joke...), it eventually loads. It looks like an issue of the sim, rather than the FBW plane

**Comment by Benjozork** [comment]
Please send a screenshot of the Content Manager screen in MSFS, while searching for "a32nx".

**Comment by KoplaNum** [comment]
Yes, it has common with mine also.

**Comment by Benjozork** [comment]
@KoplaNum this issue is about the flight not starting at all

**Comment by sidnov** [comment]
Please try this https://docs.flybywiresim.com/fbw-a32nx/installation/#clean-install-steps and report back if it doesn't solve the issue. We recommend using the #a32nx-support channel on our Discord for common issues like this one.

**Comment by kilocharlie1** [comment]
> It happens to me too, but it is not stucked, it only takes a lot of time to load, if i leave it there for about 15 mins or so (no joke...), it eventually loads. It looks like an issue of the sim, rather than the FBW plane

I have been sitting here for the past 45 minutes and it is still loading
