### ISSUE TITLE
VR Controllers - throttles should move together like the Asobo version

### ISSUE THREAD

**Issue by dataslug1** [flybywiresim/a32nx#7295]
### Aircraft Version

Development

### Build info

```json
All builds since release
```

### Describe the bug

Currently throttles move independently when grabbed with VR controller, this makes it impossible to fly with.  This was also the case in the default Asobo aircraft (including A320) for some months until they released an update which made all default multi throttles move together with VR controllers.  Please could this be added to the FBW? Many thanks

### Expected behavior

Both throttles move together when one of them is grabbed and moved with VR controller, as in Asobo A320.

### Steps to reproduce

Fly with VR controllers

**Comment by 2hwk** [comment]
Duplicate for https://github.com/flybywiresim/a32nx/issues/6385 closing, 

Note that as few of the core team possess VR headsets, this is not a high priority item on our backlog, a community fix is usually needed for issues relating to VR.
