### ISSUE TITLE
Constraint not taken into account after changing to OP DES and then DES again

### ISSUE THREAD

**Issue by phildeg31** [flybywiresim/a32nx#7299]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2022-06-13T18:39:58+00:00",
    "ref": "refs/heads/master",
    "sha": "11bad99366da9bc8e47e03a86a20912486ab85bd",
    "actor": "tracernz",
    "event_name": "manual",
    "pretty_release_name": "master:11bad993"
}
```

### Describe the bug

The constraint seems not to be taken into account after changing from DES to OP DES and then from OP DES to DES again.

### Expected behavior

The plane should stop descending at constraint level because I am in DES mode after last change but continue the descent.

### Steps to reproduce

1. Change the altitude to start the descent in DES mode
2. Click on the button to change to OP DES on the FCU panel (in my case I use the event)
3. Click on the button to change to DES again on the FCU panel (in my case I use the event)

### References (optional)

![image](https://user-images.githubusercontent.com/74733393/173513407-98ba8efb-e186-42e2-934c-fa2e2f1d03f0.png)

**Comment by tracernz** [comment]
Do you have a good reference for behaviour when DES is engaged while below profile and already below the next constraining altitude?

**Comment by BalaBalaYi** [comment]
> Do you have a good reference for behaviour when DES is engaged while below profile and already below the next constraining altitude?

should the climb mode engaged instead of descent if the current altitude below the profile in fmc?

**Comment by phildeg31** [comment]
Hi,
Sorry I was in Holidays and not at home and was not able to test before.
I tested again today after updating the A32NX and everything works fine. I was not able to reproduce.
I close this ticket.
