### ISSUE TITLE
All displays inside aircraft are blurry

### ISSUE THREAD

**Issue by dg1234567** [flybywiresim/a32nx#7304]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2022-06-15T21:28:11+00:00",
    "ref": "refs/heads/master",
    "sha": "4c934c8266c6fdea362259b59989709f1f81dc36",
    "actor": "frankkopp",
    "event_name": "manual",
    "pretty_release_name": "master:4c934c82"
}
```

### Describe the bug

All digital displays in the cockpit appear blurry

### Expected behavior

Normal looking displays

### Steps to reproduce

Spawn anywhere
Turn on electronics
look at this digital displays in the cockpit

### References (optional)

![20220619_141129](https://user-images.githubusercontent.com/34901212/174494887-40965b93-173b-4bfc-9a00-3ac44f7b0522.jpg)

**Comment by dg1234567** [comment]
and no its not my camera thats blurry, it really is that blurry. already checked graphics settings

**Comment by Benjozork** [comment]
Do you use render scale =100% in MSFS ?

**Comment by dg1234567** [comment]
no im on 70

**Comment by dg1234567** [comment]
but i just put it to 100 and it works.
thanks so much

**Comment by Benjozork** [comment]
Yeah, Glass cockpits do not scale well with render scale. Tried it myself back in the day.

**Comment by dg1234567** [comment]
Thank you
