### ISSUE TITLE
flight-plan does not work

### ISSUE THREAD

**Issue by SashaRu2020** [flybywiresim/a32nx#7307]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2022-06-23T03:50:21+00:00",
    "ref": "refs/heads/master",
    "sha": "c79a547bc162efe3b67eabb170e6f20d857936c6",
    "actor": "ErickSharp",
    "event_name": "manual",
    "pretty_release_name": "master:c79a547b"
}
```

### Describe the bug

My flight plan is not working

### Expected behavior

I reinstalled flybywire, completely deleted the mod files and still didn't help

### Steps to reproduce

1.I installed flybywire for the first time
2.After I entered everything into MCDU init and went into fpln there was nothing there

### References (optional)

![image](https://user-images.githubusercontent.com/107981813/175221509-5148ceac-5abc-4468-b534-d369ba225286.png)

### Discord Username (optional)

Holoma#2262

**Comment by Benjozork** [comment]
I suggest heading to our discord #a32nx-support channel for better assistance. GitHub is more for specific and reproducible bug reports.

Can you send a screenshot of the MSFS content manager (searching for a32nx in the search bar) ?

**Comment by SashaRu2020** [comment]
![image](https://user-images.githubusercontent.com/107981813/175233933-cd117c29-feb4-419e-90f7-34f5649255b6.png)

**Comment by SashaRu2020** [comment]
write to me in a personal account in the discord, I do not receive sms to my phone number

**Comment by sidnov** [comment]
What is the sim version you are currently using? https://docs.flybywiresim.com/fbw-a32nx/support/#msfs-version

Also, try the steps here if you download the A32NX using our installer and report back. https://docs.flybywiresim.com/fbw-a32nx/installation/#clean-install-steps

**Comment by sidnov** [comment]
Closing for now, can be reopened if needed
