### ISSUE TITLE
All lights on buttons not clickable

### ISSUE THREAD

**Issue by WillBarouch** [flybywiresim/a32nx#7312]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2022-06-27T14:37:32+00:00",
    "ref": "refs/heads/master",
    "sha": "3aff66f3df74a527cb68e4502f7930c501ee9f15",
    "actor": "2hwk",
    "event_name": "manual",
    "pretty_release_name": "master:3aff66f3"
}
```

### Describe the bug

When loading into the aircraft all the lights are on and none of the buttons or switches are clickable. However the flypad works perfectly

### Expected behavior

Only correct lights are on and buttons are clickable

### Steps to reproduce

Load into a320nx
Go to cockpit view

### Discord Username (optional)

WillDill1311

**Comment by tracernz** [comment]
Did you build the code yourself? If so make sure you do a clean build of everything (`--no-cache`).

**Comment by WillBarouch** [comment]
> Did you build the code yourself? If so make sure you do a clean build of everything (`--no-cache`).

Nope, installed via the installer

**Comment by rduatc** [comment]
I have the same issue. Sounds are messed up too. Any solutions?

**Comment by rduatc** [comment]
I just tried uninstalling the developmental build, and reinstalled the stable build and all is well again. Thinking of trying the developmental build again, but since it's working now, I don't think I want to "fix it".

**Comment by sidnov** [comment]
If you are using the installer to download the A32NX, I'd suggest try the steps mentioned here https://docs.flybywiresim.com/fbw-a32nx/installation/#clean-install-steps and report back if it doesn't solve the issue. We recommend using the #a32nx-support channel on our Discord for common issues like this one.
