### ISSUE TITLE
Не работают дисплеи

### ISSUE THREAD

**Issue by Freeziiiik** [flybywiresim/a32nx#7320]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2022-07-03T08:01:37+00:00",
    "ref": "refs/heads/master",
    "sha": "cbb0da58d54e2f8b1e431baea3b4201b4eb91ba7",
    "actor": "tyler58546",
    "event_name": "manual",
    "pretty_release_name": "master:cbb0da58"
}
```

### Describe the bug

При появлении в кабине, запускается EXT PWR. Но при этом на оверхеде показывает AVAIL. Напряжение BAT1 и BAT2 - 0v.
Не работают все дисплеи!

### Expected behavior

Всё должно быть, как надо.

### Steps to reproduce

1. Выбрал FBW A32NX
2. Загрузился в аэропорту
3. Нажал на кнопку "Полетели!"
4. Столкнулся с данной проблемой

### References (optional)

![Screenshot_30](https://user-images.githubusercontent.com/108878730/177783844-2fcd8d26-b0ad-4b2b-8702-a44eff66fe6c.png)
![Screenshot_29](https://user-images.githubusercontent.com/108878730/177783913-f634c3da-c0d5-46e5-8fe6-72fb315cf738.png)

**Comment by sidnov** [comment]
Please reach out to us on the #a32nx-support channel on the Discord with more information about your sim version

**Comment by Sayyod11** [comment]
did you solve this problem?
