### ISSUE TITLE
Can't load (Card blue bar)

### ISSUE THREAD

**Issue by Superseven2333** [flybywiresim/a32nx#7325]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2022-07-08T13:46:05+00:00",
    "ref": "refs/heads/master",
    "sha": "78b85e56c2aabf62982e4a9e83c721f2029da587",
    "actor": "sidnov",
    "event_name": "manual",
    "pretty_release_name": "master:78b85e56"
}
```

### Describe the bug

When i try to load it Card blue bar , i unistall and install again and again but it also Card blue bar.
So i try delete MSFS but nothing else.
Here can you tell me how to repair it ?
Thank You!

### Expected behavior

successfully to load it :)

### Steps to reproduce

1.Open MSFS 
2.Select FLYBYWIREA320
3.Select Airport
4.Fly 
5.Card blue bar

### Additional info (optional)

Last month i can use it but now i can't load it.

**Comment by sidnov** [comment]
Please try this https://docs.flybywiresim.com/fbw-a32nx/installation/#clean-install-steps and report back if it doesn't solve the issue. We recommend using the #a32nx-support channel on our Discord for common issues like this one.
