### ISSUE TITLE
MCDU F-PLN page crashes

### ISSUE THREAD

**Issue by JRH3221** [flybywiresim/a32nx#7354]
### Aircraft Version

Experimental

### Build info

```json
{
    "built": "2022-07-23T05:11:28+00:00",
    "ref": "refs/heads/experimental",
    "sha": "0f6af6bdae9a26e56a4aa4c27146a0eff5b73eee",
    "actor": "tracernz",
    "event_name": "manual",
    "pretty_release_name": "experimental:0f6af6bd"
}
```

### Describe the bug

After clearing a flight plan discontinuity the screen blanked out with a few symbols at the top. The screen goes back to normal after going back to the flight plan page but blanks out again after scrolling to a certain point.

### Expected behavior

The flight plan discontinuity would clear

### Steps to reproduce

Enter a full flight plan
clear discontinuity

### References (optional)

![Capture](https://user-images.githubusercontent.com/72972623/180597758-a7271581-76f2-42ce-af88-93c484392a40.JPG)

### Additional info (optional)

If needed the flight is:
EGLL/27R UMLA1F UMLAT T418 WELIN T420 TNT UN57 POL UN601 INPIP INPI1E EGPH/06

**Comment by Spartan3001961** [comment]
Happened with me this morning as well fly from Bristol to Amsterdam. I'm also using the Experimental build as well.

Flight Plan generated from SimBrief;
EGGD/27 F290 BADIM1X BADIM Q63 KENET UL9 CPT M197 REDFA REDFA1A
 EHAM/36R

**Comment by 2hwk** [comment]
Should be resolved in latest exp update, closing.
