### ISSUE TITLE
Cockpit not working

### ISSUE THREAD

**Issue by aitalinassim** [flybywiresim/a32nx#7356]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2022-07-19T21:20:21+00:00",
    "ref": "refs/heads/master",
    "sha": "494b201240db5c2af2d53872c27408f008104a15",
    "actor": "Saschl",
    "event_name": "manual",
    "pretty_release_name": "master:494b2012"
}
```

### Describe the bug

When loading the aircraft model and started a new flight, a bizzar sound is played and all buttons are on and screens are black.
When click on any button, no response, only the sound (a bizzar sound, not the sound of engine or other)
Same for experimental or development versions, even when downloaded from master branch.

### Expected behavior

Cockpit works.

### Steps to reproduce

1. Install MSFS 2000
2. Install FBY installer
3. Install any version
4. Launch MSFS
5. Start a fly with FBW A32nx

### References (optional)

![00r0mquuej981](https://user-images.githubusercontent.com/28365138/180620993-e52164e5-f0c3-480d-ac62-376cd18f3ef0.jpg)

### Additional info (optional)

Asus Asrock gaming Motherboard
I7 processor
Nvidia GTX 1060 6 GB
1 Tb Nvme SSD
32 GB RAM

Some times it crashes to desktop when loading simulator or when loading a flight
No, no and no problems with the default A320neo.
Community folder is containing this FBW only folder after installation

**Comment by kiwi2021** [comment]
Please share a screenshot of your sim version.

**Comment by aitalinassim** [comment]
![32131](https://user-images.githubusercontent.com/28365138/180661053-eb6ccf47-2167-4ec5-8e4b-525a85c58eb5.PNG)

**Comment by ImenesFBW** [comment]
> ![32131](https://user-images.githubusercontent.com/28365138/180661053-eb6ccf47-2167-4ec5-8e4b-525a85c58eb5.PNG)

We don't support pirated versions of the sim! Buy the sim and it will work.
