### ISSUE TITLE
MCDU malfunction 

### ISSUE THREAD

**Issue by DavidEGTE** [flybywiresim/a32nx#7359]
### Aircraft Version

Experimental

### Build info

```json
{
    "built": "2022-07-23T05:11:28+00:00",
    "ref": "refs/heads/experimental",
    "sha": "0f6af6bdae9a26e56a4aa4c27146a0eff5b73eee",
    "actor": "tracernz",
    "event_name": "manual",
    "pretty_release_name": "experimental:0f6af6bd"
}
```

### Describe the bug

Scrolling down F-PLN I get a blank screen with unknown character
All this happen half way during cruise

### Expected behavior

Just normal scroll down to arrival ICAO

### Steps to reproduce

LIRN/24 ISKI6G ISKIA M603 PNZ/N0400F320 DCT TOBGA DCT DOBIM UM616 KOTIT/N0325F180 Y42 LASUR Z42 PINED PINE5N LFLL/35L

### References (optional)

https://vimeo.com/manage/videos/732933397

### Discord Username (optional)

David#2177

**Comment by BlueberryKing** [comment]
Hi, this bug should be fixed in the newest version. Make sure to update from the installer. I am closing this issue for now, but feel free to reopen if the issue persists. 🙂
