### ISSUE TITLE
Target Altitude indidactors

### ISSUE THREAD

**Issue by gunterat** [flybywiresim/a32nx#7372]
### Aircraft Version

Development

### Description

I really miss that in the ND the Target Altitude indidactors are not displayed. (hockey sticks). These make vertical navigation more easy.
Will there be such in the near future?
Thank you for your hard work.
Günter

### Discord Username (optional)

gunterat

**Comment by tracernz** [comment]
Try the experimental version for a preview of these features.

**Comment by tracernz** [comment]
Duplicate #856
