### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by fe3l1n** [flybywiresim/a32nx#7374]
### Aircraft Version

Experimental

### Description

1. V/DEV n L/DEV for RNP Approach
2. Glide Slope Warning
3. Windshear Warning
4. Terrain Radar
5. Weather Radar

### Discord Username (optional)

Stefanus#4308

**Comment by tracernz** [comment]
Please just one feature per issue. You will find most or all of these already have issues, and many are already in progress. Wx radar and pre-emptive  windshear warnings not really feasible until suitable data is available from the sim. L/DEV is already implemented… you just need a suitable RNP (PROG page) to trigger it… MSFS navdata does not provide leg RNP values so until FMS-v2 it will only have flight area defaults automatically. Barometric v/dev is problematic in MSFS at the moment (https://devsupport.flightsimulator.com/questions/9906/altimetry-issues-with-live-weather.html). There is already a PR open for terrain map (A320 doesn’t have a terrain radar).
