### ISSUE TITLE
/sound option not working anymore for remote MCDU connected with FBW-simbridge

### ISSUE THREAD

**Issue by Rascal650** [flybywiresim/a32nx#7379]
### Aircraft Version

Experimental

### Build info

```json
{
    "built": "2022-07-29T17:10:58+00:00",
    "ref": "refs/heads/experimental",
    "sha": "0c85b683e355c0df91ff5e7f883dbe6836e41b34",
    "actor": "2hwk",
    "event_name": "manual",
    "pretty_release_name": "experimental:0c85b683"
}
```

### Describe the bug

Using the 7/29 build (with FBW-simbridge) enabled,  I changed my remote MCDU URL to:

http://192.168.68.133:8380/interfaces/mcdu/sound

The remote MCDU seems to work great  (same as the old MCDU server). however I don't hear the "clicks" on my tablets anymore when I click on the remote MCDU keys.  I  USED TO hear the "clicks" coming from my tablet using the "URL/sound" option and the __old remote MCDU server__.  (sound is not muted on the tablet)

### Expected behavior

Would like to hear  the "clicks" coming from my tablet when using the /sound option (as before)

### Steps to reproduce

See above

**Comment by pdellaert** [comment]
Looking at some of the code, could you try using a GET parameter instead:
`http://192.168.68.133:8380/interfaces/mcdu?sound`
Can't test right now, will try later today.

**Comment by Rascal650** [comment]
Yup;  ?sound works!  

 If it's the new syntax,  I recommend updating the documentation  https://docs.flybywiresim.com/simbridge/remote-displays/remote-mcdu/#opening-the-mcdu-remote-display  which still refers to the "/" for the sound and fullscreen options.

**Comment by pdellaert** [comment]
Thanks for the feedback, I'll let the devs decide on the right approach as it's their design. But yeah, documentation should be in line.

**Comment by Valastiri** [comment]
Realized after the fact this issue was linked. Apologies. Documentation is now updated with the current implementation + usage.
