### ISSUE TITLE
Wrong option names in the EFB

### ISSUE THREAD

**Issue by westereq-dot** [flybywiresim/a32nx#7381]
### Aircraft Version

Experimental

### Build info

```json
{
    "built": "2022-07-30T10:44:27+00:00",
    "ref": "refs/heads/experimental",
    "sha": "82e5fe2044b454adbfb70f424051b46bbeab912d",
    "actor": "2hwk",
    "event_name": "manual",
    "pretty_release_name": "experimental:82e5fe20"
}
```

### Describe the bug

![image](https://user-images.githubusercontent.com/61510763/181933373-5c3939ed-cd1d-41aa-8de5-33c6ff5a605f.png)

### Expected behavior

Options (to me) should be Enable Simbridge, Simbridge port instead of what they are

### Steps to reproduce

1. Load in
2. Press on the EFB
3. Head to settings > Sim Options

### Discord Username (optional)

westereq#0122

**Comment by 2hwk** [comment]
Fixed in latest exp
