### ISSUE TITLE
Reversing throttle with button

### ISSUE THREAD

**Issue by erick0z** [flybywiresim/a32nx#7382]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2022-07-29T17:18:58+00:00",
    "ref": "refs/heads/master",
    "sha": "f6c49bf04813ff04949f8f94c4d951796a54940d",
    "actor": "tyler58546",
    "event_name": "manual",
    "pretty_release_name": "master:f6c49bf0"
}
```

### Describe the bug

When toggling the "Reverse Thrust" with a button it glitches because the thrust axis is sending it's position to the sim, not enabling to "Hold" or "Toggle" the reverse thrust.

### Expected behavior

When toggling off "Reversing on Axis" button, the Aircraft should be able to use another source for the reverse thrust signal. When the "Reverse Thrust" toggle is received from a button from a controller, Keyboard or another axis, the main axis signal should stop sending the thrust signal to the sim. Enabling the reverse thrust. In my case, using the Saitek Throttle Quadrant, which has a "Button" next at the end of the Axis (The reverse function is not part of the axis itself, the lever has a programable button at the end of its travel).

### Steps to reproduce

1.- Disable "Reverser on axis"
2.- Set Throttle to idle
3.- Toggle or Hold Reverse thrust with a button or another axis.

### Additional info (optional)

The default A320 has this functionality working. I guess it is this flypad or this mod handler which keeps sending the throttle signal to the aircraft/sim

### Discord Username (optional)

ecardona#9232

**Comment by erick0z** [comment]
Ok, so I took a little dive to the code and I see this behaviour handled by `ThrottleAxisMapping::onEventReverseToggle()`, `ThrottleAxisMapping::onEventReverseHold(bool isButtonHold)` and `ThrottleAxisMapping::setCurrentValue(double value)` in https://github.com/flybywiresim/a32nx/blob/5e75bdfd7c6880c720f8f8377d0dd8f46bafe8ef/src/fbw/src/ThrottleAxisMapping.cpp#L233

So, the current behaviour is that if the reverse toggle button is pressed, suddenly the Thrust Axis flips. That means that in order to activate the reverse thrust, the levers must go up again. For me that's not very intuitive and I don't know if that's what the majority of the community uses or are used to. I think that the toggle button at least is self explanatory, the button should actually toggle the reverse thrust directly to full. And the fix for this should be very simple, just set `newTLA = TLA_REVERSE;` in https://github.com/flybywiresim/a32nx/blob/5e75bdfd7c6880c720f8f8377d0dd8f46bafe8ef/src/fbw/src/ThrottleAxisMapping.cpp#L234

But again, I'm not familiar with all the hardware out there and how is used. I'd love to hear other's opinions.

**Comment by 2hwk** [comment]
See https://docs.flybywiresim.com/fbw-a32nx/feature-guides/flypados3/throttle-calibration/?h=bravo#toga for an existing solution for this.
