### ISSUE TITLE
Flypad OS 3 Problem

### ISSUE THREAD

**Issue by EvilWuZhi** [flybywiresim/a32nx#7398]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2022-07-22T10:46:39+00:00",
    "ref": "refs/heads/master",
    "sha": "abbc34fd196d1d04c705f528a9b34172205206e4",
    "actor": "BlueberryKing",
    "event_name": "manual",
    "pretty_release_name": "master:abbc34fd"
}
```

### Describe the bug

（My English is very low, So I use Chinese）
我更新了开发版A320 但是我发现这个Flypad OS2 并非我想要的OS3! 
I Updated the Development Version (6647ffd), But Flypad is OS2.

### Expected behavior

 我想使用FlypadOS3， 我该怎么做？
 I want to use the OS3, How can i do?

### Steps to reproduce

1.Nothing.

**Comment by 2hwk** [comment]
Ensure you only have one version of the addon installed.
Try cleaning out your community folder,
then try again with a clean install from the installer.

**Comment by 2hwk** [comment]
Closing for staleness
