### ISSUE TITLE
New Battery Issue | Voltage ".0"

### ISSUE THREAD

**Issue by Hakkermans** [flybywiresim/a32nx#7399]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2022-08-04T11:40:30+00:00",
    "ref": "refs/heads/master",
    "sha": "0e825f47d0e3850d961c85c21632e56db4a82c2f",
    "actor": "tracernz",
    "event_name": "manual",
    "pretty_release_name": "master:0e825f47"
}
```

### Describe the bug

Upon loading in the aircraft, the voltage on the batteries read .0
I've seen issues before where they have read as 0.0, but this isn't even that.
I am unable to power the batteries.

### Expected behavior

Voltage should be around 25.5 on startup

### Steps to reproduce

1. Load into any location

### References (optional)

![Screenshot (14)](https://user-images.githubusercontent.com/110154916/183222903-1482afba-5342-4183-93cd-edf4f7eec2d9.png)
![Screenshot (16)](https://user-images.githubusercontent.com/110154916/183222926-39efc9fa-1c0b-4b81-9695-191b81c47cd9.png)
![Screenshot (15)](https://user-images.githubusercontent.com/110154916/183222914-f6841b6b-596f-4d85-a25c-76a2bdffaaa4.png)

### Discord Username (optional)

Hakkermans#0001

**Comment by tracernz** [comment]
I’ve seen this during development when the instruments crash during start up…

**Comment by Hakkermans** [comment]
Any idea on what causes it, or if theres any way to fix it? It makes the development build unflyable
