### ISSUE TITLE
Save an edited flight plan from within the MCDU

### ISSUE THREAD

**Issue by AdamNZ** [flybywiresim/a32nx#7406]
### Aircraft Version

Development

### Description

Apologies if this has already been requested.

I often have to make quite substantial edits to an imported (Simbrief) flight plan.

If I'm flying an identical plan (for testing) I find it quite repetitive/time consuming to re-enter all the amendments.

Would it be possible to SAVE a customised flight plan (for later recall) from within the MCDU? I've no idea whether it's possible in RL, but it'd be a handy option for a simulation.

Adam.

### Discord Username (optional)

Adamski_NZ

**Comment by 2hwk** [comment]
What you are asking for would be covered under https://github.com/flybywiresim/a32nx/issues/6178, therefore this will be closed to consolidate this into one issue, however there are substantial blocking issues that have to be resolved first.
