### ISSUE TITLE
Flypad services screen goes blank

### ISSUE THREAD

**Issue by ecortinas** [flybywiresim/a32nx#7412]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2022-08-12T17:01:34+00:00",
    "ref": "refs/heads/master",
    "sha": "050f64530475c68b7156f0a64fa55ac7d5c46738",
    "actor": "2hwk",
    "event_name": "manual",
    "pretty_release_name": "master:050f6453"
}
```

### Describe the bug

Somewhere along the flight the services page goes blank, and nothing can be done to get it back aside from starting over.

### Expected behavior

Services page should be present throughout entire flight.

### Steps to reproduce

Unsure of where and when the services page goes blank.

### References (optional)

![image](https://user-images.githubusercontent.com/88294949/184523969-8c6c4ee7-af6b-46b6-a648-ff2a7c57780c.png)

**Comment by alexg0102** [comment]
Have the same issue
But only after i landed.
![image](https://user-images.githubusercontent.com/96475052/184540127-7bb22df6-a806-4cfd-b099-59f00daf7a1f.png)

**Comment by 2hwk** [comment]
Need more information, such as when this occurs and how this can be reproduced, so far have not seen it in action.

**Comment by 2hwk** [comment]
For reference its the pushback page, quite hard to reproduce but if you go into pushback, and toggle between the external and internal camera, it will happen eventually.
