### ISSUE TITLE
Problème mcdu et carburant

### ISSUE THREAD

**Issue by romfootvff** [flybywiresim/a32nx#7419]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2022-06-18T02:11:53+00:00",
    "ref": "refs/tags/v0.8.2",
    "sha": "5cfa8478aea0fd20ae4a3e6f624714d0e04fab60",
    "actor": "Benjozork",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.8.2"
}
```

### Describe the bug

J'ai deux problèmes, le premier est que j'ai une discontinuité du plan de vol sur le mcdu lorsque je le génère via fsms2020 se qui pose problème pour le pilote automatique et également la route manquante sur le nd.

La deuxième chose est le carburant de l'avion ne veut pas dépasser 20% peut importe les manipulations que je fais le carburant ne veut pas augmenter.

### Expected behavior

Le plan de vol du mcdu doit être correcte et je devrai également pouvoir mettre le carburant souhaité.

### Steps to reproduce

1- essayer d'ajouter du carburant
2- voir qu'il se réinitialise
3- faire un vol depuis msfs2020 et voir le plan de vol dans le mcdu
4- voir la discontinuité du plan de vol

**Comment by tracernz** [comment]
Try creating your flight plan in the MCDU, rather than MSFS world map... results will be much better.

You must set fuel via the EFB/flyPad.. the MSFS fuel/payload dialog gives incorrect distribution thus is disabled.

**Comment by romfootvff** [comment]
J'ai donc créer un plan de vol via sim brief, je l'ai ensuite importer dans le mcdu mais il y a toujours des problèmes de discontinuité, et par ailleurs je n'arrive pas à obtenir une autorisation IFR lorsque le plan de vol ne viens pas de la carte du monde.

**Comment by Benjozork** [comment]
> J'ai donc créer un plan de vol via sim brief, je l'ai ensuite importer dans le mcdu mais il y a toujours des problèmes de discontinuité

Une discontinuité c'est pas nécéssairement un problème, ça dépend justement de ou elle se situe et après quoi.

Je recommande de lire ce guide pour comprendre mieux: https://docs.flybywiresim.com/pilots-corner/advanced-guides/flight-planning/disco/

> et par ailleurs je n'arrive pas à obtenir une autorisation IFR lorsque le plan de vol ne viens pas de la carte du monde.

Si vous voulez utiliser l'ATC de MSFS, il faut activer une option dans la tablette via cette procédure: https://docs.flybywiresim.com/fbw-a32nx/feature-guides/cFMS/#sync-mcdu-to-msfs

Faut par contre noter que l'ATC ne comprend rien au plans de vol complexes que l'A320 peut générer et qu'il faut alors être prêt à se diriger manuellement surtout sur des approaches complexes.

**Comment by romfootvff** [comment]
D'accord je vais essayer cela. 
Merci.

**Comment by romfootvff** [comment]
J'ai également pas le bonne AIRAC est ce que ca peut venir de cela ?

**Comment by romfootvff** [comment]
J'ai donc reussi à mettre le plan de vol dans le mcdu mais maintenant le problème est que la trajectoire de l'avion n'apparait pas sur le ND le pilote automatique ne suit donc pas la bonne trajectoire

**Comment by Benjozork** [comment]
> J'ai également pas le bonne AIRAC est ce que ca peut venir de cela ?

Oui.

> le problème est que la trajectoire de l'avion n'apparait pas sur le ND le pilote automatique ne suit donc pas la bonne trajectoire

Possible d'envoyer un screenshot du la page FPLN du MCDU et du ND ?

**Comment by romfootvff** [comment]
![image](https://user-images.githubusercontent.com/103595329/185638139-d26131cb-4b24-4188-a548-4f1bfde9c916.png)
![image](https://user-images.githubusercontent.com/103595329/185638273-14291b3a-8fcf-4aa5-807a-2cb90c6842b0.png)

**Comment by romfootvff** [comment]
L'avion ne suit pas du tout le plan de vol

**Comment by Benjozork** [comment]
Vous n'avez pas programmé de départ (piste de décollage et SID) et présentement ça cause ce problème.

**Comment by romfootvff** [comment]
Je vais corriger cela au prochain vol.

Mais par contre la fonction direct to ne me fais pas revenir sur la route.

**Comment by juliansebline** [comment]
Any updates on that?

> Je vais corriger cela au prochain vol.
> 
> Mais par contre la fonction direct to ne me fais pas revenir sur la route.

Have you turned on the AP and pushed the heading knob (managed mode)?


Des nouvelles sur ce sujet?

> Je vais corriger cela au prochain vol.
> 
> Mais par contre la fonction direct to ne me fais pas revenir sur la route.

Avez-vous appuyé sur le knob de heading pour être en mode managé? Je suppose que oui mais je demande quand même.

**Comment by romfootvff** [comment]
Oui j’ai résolu le problème en enlevant tout les modules ajouter je pense qu’il y a certain qui pose problème pour réaliser des plan de vol. Après pourquoi un module ajouter ferait cela bonne question.
