### ISSUE TITLE
[BUG] MAN TOGA on FMA only has half a box around it.

### ISSUE THREAD

**Issue by UncleClapton** [flybywiresim/a32nx#742]
**Mod Version**

master

**Describe the bug**

MAN TOGA on the FMA should have a full box around it, but only half of it is shown.

**To Reproduce**

1. Spawn on runway.
2. Turn that throttle up to ~~11~~ 12.
3. Get disapointed in the lack of full boxage around MAN TOGA

**Expected behavior**

A nice sturdy box to hold my TOGA annunciator.

**Actual behavior**

MAN TOGA is falling out of it's box and it makes me sad. 😢 

**References**

![](https://clapton.dev/u/2009/d618beb8.png)

**Comment by Coralec** [comment]
Bug replicated. I believe this has been a problem for a very long time. Would be nice to get a fix.

**Comment by AdenFlorian** [comment]
should also check man flx and any other modes that have a two line box
