### ISSUE TITLE
A32NX - fix all doors since GSX Pro Release

### ISSUE THREAD

**Issue by CaptRami777** [flybywiresim/a32nx#7436]
### Aircraft Version

Development

### Description

I would like to have all doors open, Since GSX Pro just released, it would be nice to get all doors open. 
I would like that so fbw can be more realistic. I wanted for the coming update if you can make it possible as right away if not then I will have to just wait thank you

### Discord Username (optional)

Capt Rami777

**Comment by Gurgel100** [comment]
This is currently not possible as we are using the model from Asobo. But we are working on a custom model which will make this possible.

**Comment by CaptRami777** [comment]
ok thank you

**Comment by Tankieboy** [comment]
Can you share a timeframe for the new model please?

**Comment by Gurgel100** [comment]
Unfortunately not. Currently the modelling is focusing on the a380 and when done we will do a32nx. All I can say is: It will be done when it's done.
