### ISSUE TITLE
Simbridge autostart on MSFS launch or A32NX load

### ISSUE THREAD

**Issue by Octonath** [flybywiresim/a32nx#7440]
### Aircraft Version

Experimental

### Description

So for now Simbridge can only autostart when you log into the windows session but that would be good if it could launch only when MSFS start or when you load into the plane. Could it be possible ?

### Discord Username (optional)

Octonath#2600

**Comment by 2hwk** [comment]
Currently only possible by using context.xml, which comes with its own set of less desirable problems, so this has already been ruled out.
