### ISSUE TITLE
Aircraft spawns with gear up, loud noise and all lights illuminated.

### ISSUE THREAD

**Issue by CaptAngryEyes** [flybywiresim/a32nx#7447]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2022-08-27T09:17:26+00:00",
    "ref": "refs/heads/master",
    "sha": "230c701f7210af8a25825a10668ee0133df538b7",
    "actor": "2hwk",
    "event_name": "manual",
    "pretty_release_name": "master:230c701f"
}
```

### Describe the bug

When selecting the A32NG and loading in any gate or runway, the aircraft spawns in with every light illuminated, it makes a noise that reminds of the landing gear extension sound, the controls don't work, the switches don't work, nothing works.

MSFS version: 1.7.12.0
A32NG version: Stable v0.8.2 OR Development 230c701

### Expected behavior

I expected to load in a cold and dark cockpit and have a controllable working aircraft.

### Steps to reproduce

Install either the stable or experimental version of A32NG and the latest version of SimBridge

Start MSFS, go to World map, and select the A32NG aircraft

Go to any airport and click "Ready to Fly"

### References (optional)

This is at a gate where the aircraft was expected to be cold and dark
![1](https://user-images.githubusercontent.com/69366501/187047938-80061a8f-5127-4694-afdd-67908d287898.png)
![2](https://user-images.githubusercontent.com/69366501/187047945-f3a416dd-0316-4306-b044-9d1ab4b9aacb.png)

### Additional info (optional)

The community folder only contains the Flybywire A32NG mod.

The work folder is empty

**Comment by MjrIncident** [comment]
Same for me. Experimental.

**Comment by crocket63** [comment]
Does it happen only on pirated game or also if you have bought it?

**Comment by MjrIncident** [comment]
> 

what?

**Comment by crocket63** [comment]
> > 
> 
> what?

I mean you state you are on MSFS version: 1.7.12.0, so this is basically not an official version.
