### ISSUE TITLE
[BUG] Throttle goes to idle when engaging CL after takeoff

### ISSUE THREAD

**Issue by BrianBash** [flybywiresim/a32nx#745]
**Mod Version**

Latest Master branch

**Describe the bug**

After takeoff, when engaging the throttle from FLEX/TOGA to CL, the engines spool down to idle before slowly coming back up to CL power.

**To Reproduce**

1. Normal Takeoff
2. When THR CLB is indicated, move the throttle to the CL position

**Expected behavior**

Power should not go to idle after engaging CL. A smooth power transition from FLX to CL is expected.

**Actual behavior**

Throttle goes to idle before climbing back up to CL thrust. Massive decrease in airspeed with a imminent stall if not handled quickly.

**References**

**Additional context**

Discord username (if different from GitHub): BBash

**Comment by nabil74** [comment]
Yes ive experienced this stalled and recovered LOL.

**Comment by kayfabe9** [comment]
I have experienced this on a couple of flights. along with the ATC asking me to reset squawk code. The solution i found is to engage manual speed at 250 knots and then reduce thrust to CL

**Comment by g0per** [comment]
> 
> 
> I have experienced this on a couple of flights. along with the ATC asking me to reset squawk code. The solution i found is to engage manual speed at 250 knots **and then reduce thrust to CL**

You should be on CL 99% of the flight tho.

**Comment by Venorcis** [comment]
> Yes ive experienced this stalled and recovered LOL.

Same, the protections kick in, but this is really weird takeoff behavior.

**Comment by bisinchi** [comment]
Same behavior seen on my side. Actually, with AP OFF and ATHR ON, reverting from TOGA or MCT to CLB during climb would set the managed speed to speed seen at change to CLB detent, hence resulting in engines going to idle before going back to expected thrust.
With AP OFF, I would expect the thrust to stay at CLB thrust (and independant of speed set in FCU).

**Comment by hotshotp** [comment]
fixed with new thrust red and accel alts
