### ISSUE TITLE
[BUG] - Radio LCD does not get updated with frequency from ATC menu.

### ISSUE THREAD

**Issue by BreakerHUN** [flybywiresim/a32nx#746]
**Mod Version**
BUG appears without any mod.

**Describe the bug**
When tuning radio frequencies via the menu, the radio LCD does not get updated with the selected value.

**To Reproduce**
1. Open ATC menu
2. Click on "Tune in xxxx.x" menu to tune in the specified frequency
3. Check the radio LCD - no changes have been made.

**Expected behavior**
Radio LCD should be updated with the new frequency.

**Actual behavior**
Radio frequency LCD does not change at all.

**References**
BEFORE:
![image](https://user-images.githubusercontent.com/71471788/93663561-3a02e600-fa69-11ea-802f-ca86025fb166.png)

AFTER:
![image](https://user-images.githubusercontent.com/71471788/93663575-49822f00-fa69-11ea-8a68-efa565c2ff17.png)

**Additional context**
I believe this is on Asobo, and not really critical however if there is an "easy" fix then please. Many thanks.

Discord username (if different from GitHub):
BreakerHUN#3986

**Comment by stevex77** [comment]
This one is "asobo bug" - I observed this behavior during alphpa / beta phase of MSFS development. So this should be tagged as asobo / vanilla bug.

**Comment by Venorcis** [comment]
Turning the radio off (which has no real effect too) and then on again updates the numbers, but would indeed be nice if we can auto-update this better than Asobo :P

**Comment by davidwalschots** [comment]
Fixed.
