### ISSUE TITLE
Quick Travel Mode (allow higher simrates)

### ISSUE THREAD

**Issue by sebastianpicklum** [flybywiresim/a32nx#7467]
### Aircraft Version

Experimental

### Description

When doing longer flights, the cruise is kinda boring. To not waste time and precious electric energy, it would be great to be able to increase the sim rate to 8x or even 16x.

My suggestion is to allow higher sim rates by reducing the complexity of the simulation depending on the simrate, i.e. 1x and 2x runs as is, >=4x the plane is practically just in slew mode flying with cruise speed towards the next waypoint.

Ideally, a quick travel model is implemented that when activated accelerates to a higher sim rate when flying straight and then temporarily slows down before each waypoint to allow turning with high fidelity. And when the right heading is achieved, the sim rate can be increased again.

### Additional info (optional)

There is also a request about a teleport feature that would also address this isse: #6093

**Comment by 2hwk** [comment]
This would not be technically possible, teleport is viable but this would not be. Closing. 

See https://github.com/flybywiresim/a32nx/issues/6093
