### ISSUE TITLE
[BUG] Low Frames when entering APP Phase.

### ISSUE THREAD

**Issue by Berniep94** [flybywiresim/a32nx#747]
**Mod Version**
0.2.0 (19/09/20)

**Describe the bug**
I lost half of frames on approach, and taxing, but when i hit full brakes on gate, my fps restore. All of this only in cabin mode, outside view continues with good fps.

**To Reproduce**
1. Descending
2. Intercept IOC
3. Start Low FPS
4. Land
5. Vacte rwy and taxi
6. Set full brakes
7. FPS restore.
8.  Set parking brakes

**References**
<a href="https://ibb.co/7J0zppY"><img src="https://i.ibb.co/HD92PPF/Flight-Simulator-7-I6-SDPi7-Uk.jpg" alt="Flight-Simulator-7-I6-SDPi7-Uk" border="0"></a>
<a href="https://ibb.co/gTrXdtY"><img src="https://i.ibb.co/bB6yFNt/Flight-Simulator-UG2-C2-WDc-Le.jpg" alt="Flight-Simulator-UG2-C2-WDc-Le" border="0"></a>
<a href="https://ibb.co/n6T6tkt"><img src="https://i.ibb.co/vVbVRzR/Flight-Simulator-m-Rnqx-V0-Dx-T.jpg" alt="Flight-Simulator-m-Rnqx-V0-Dx-T" border="0"></a>

**Additional context**
Thanks guys

Discord username (if different from GitHub):

**Comment by g0per** [comment]
Which ICAO is that happening on?

**Comment by PiotrMKG** [comment]
Had the same problem while on route EGLC-ENVA around Norwegian coast. Down from 40fps to 3fps, canceled the flight, loaded again everything back to normal atleast at London City didn’t have time to make another flight to test it.

**Comment by rcavinash123** [comment]
See if this fixes the issue.

https://forums.flightsimulator.com/t/limited-by-coherentgtdraw-issue/275843/28

**Comment by Berniep94** [comment]
> See if this fixes the issue.
> 
> https://forums.flightsimulator.com/t/limited-by-coherentgtdraw-issue/275843/28

No, it only happens in APP Phaze, not in the entire flight,  untile i hit full brakes on gate. I get back my FPS.

**Comment by Berniep94** [comment]
> Which ICAO is that happening on?

This was LEZL, Sevilla Spain

**Comment by Venorcis** [comment]
> Had the same problem while on route EGLC-ENVA around Norwegian coast. Down from 40fps to 3fps, canceled the flight, loaded again everything back to normal atleast at London City didn’t have time to make another flight to test it.

Had a similar issue cruising over north-west Germany on my way to Berlin, though it resolved itself after like 5 minutes or so. I doubt if it's related to this mod at all though.

**Comment by PiotrMKG** [comment]
> > Had the same problem while on route EGLC-ENVA around Norwegian coast. Down from 40fps to 3fps, canceled the flight, loaded again everything back to normal atleast at London City didn’t have time to make another flight to test it.
> 
> Had a similar issue cruising over north-west Germany on my way to Berlin, though it resolved itself after like 5 minutes or so. I doubt if it's related to this mod at all though.

I tested the same route yesterday and the same happened, this time on last 10nm until touchdown. Non of the switches, knobs, buttons worked, felt dissapointed after 2h of flight.  Today I will try shorter route EDDT-LOWW

**Comment by MisterChocker** [comment]
seems to be resolved
