### ISSUE TITLE
Le ND n'affiche pas correctement le plan de vol et l'avion ne suit pas le plan de vol dans le MCDU.

### ISSUE THREAD

**Issue by Draconic112** [flybywiresim/a32nx#7472]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2022-06-18T02:11:53+00:00",
    "ref": "refs/tags/v0.8.2",
    "sha": "5cfa8478aea0fd20ae4a3e6f624714d0e04fab60",
    "actor": "Benjozork",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.8.2"
}
```

### Describe the bug

Bonjour,
Mon problème est plutôt simple mais très embêtant : le plan de vol ne s'affiche pas correctement sur le ND, et sur le MCDU il m'affiche des discontinuités alors que je suis passé par Simbrief pour créer le plan de vol. De plus, sur le HUD, en haut à gauche sur le GPS, il ne m'affiche aucune trajectoire, comme si le plan de vol n'était pas pris en compte par le GPS. 

Je n'ai pourtant que le A32NX d'installé dans mon dossier community, et je l'ai installé via le launcher (à jour) de FBW.

De plus, la tour de contrôle ne considere me donne pas la possibilité de demander une clearance IFR, seulement VFR...

### Expected behavior

Que l'avion suive sa trajectoire normalement et interprète le plan de vol correctement...

### Steps to reproduce

1. Créer un plan de vol sur Simbrief
2. L'importer dans le FBW via les instructions données par le wiki de FBW
3. Constater les erreurs dans le MCDU et le ND.

### References (optional)

![image](https://user-images.githubusercontent.com/54067295/188322674-c74e0f41-5cb1-4537-971b-39d8e3e50b6e.png)
![image](https://user-images.githubusercontent.com/54067295/188322690-5caddcba-62bb-47f6-bff5-c4681d6e6f34.png)

### Additional info (optional)

Cela se passe sur la version stable de l'A32NX. Tout est à jour, et aucun programme n'est installé dans le dossier community à part l'A32NX.

### Discord Username (optional)

Draconic_112#1096

**Comment by Benjozork** [comment]
>  il m'affiche des discontinuités alors que je suis passé par Simbrief pour créer le plan de vol

Les discontinuités ne sont pas de bugs et ce n'est pas un problème d'en avoir. Dans ce cas vous en avez car vous avez choisi une approche ILS vers LFPG sans avoir une arrivée (STAR) qui la connecte. Notez que sans savoir votre route (donné sur le site simbrief) il est très difficile de comprendre ce qui manque.

> De plus, la tour de contrôle ne considere me donne pas la possibilité de demander une clearance IFR, seulement VFR...

Le contrôle aérien de MSFS ne peut pas interpréter les plans de vol de l'A320 correctement car MSFS utilise un modèle simplifié vers lequel il n'est pas pratique de convertir.

Si vous souhaitez quand même essayer d'enrigistrer les plans de vol du FMS vers MSFS, vous pouvez activer la fonction comme expliqué ici.

https://docs.flybywiresim.com/fbw-a32nx/feature-guides/cFMS/#sync-mcdu-to-msfs

p.s.: il est recommandé d'utiliser l'anglais sur GitHub et Discord et d'utiliser des outils comme DeepL (https://www.deepl.com/translator) pour traduire si vous ne parlez pas anglais.

**Comment by Draconic112** [comment]
Bonjour,
J'avais bel et bien rentré la STAR indiquée dans Simbrief dans le MCDU, d'où mon incomprehension.

Merci pour votre réponse à propose de la tour de contrôle, et j'utiliserai l'anglais à l'avenir, désolé.
