### ISSUE TITLE
radar

### ISSUE THREAD

**Issue by saviomarco1** [flybywiresim/a32nx#7478]
### Aircraft Version

Stable

### Description

When will radar and terrain be active again in the stable version?
Thank you and good day

**Comment by Valastiri** [comment]
Hello! Unfortunately, this isn't the proper utilization of our GitHub issues but to take a moment to answer - we'll release features into a new Stable version when we are happy with their stability and performance in our other branches.

To ask quick questions as such I suggest joining our Discord where our community would be more than happy to help! https://discord.gg/flybywire

For reference:
Weather Status: [MSFS Forum Post](https://forums.flightsimulator.com/t/implement-weather-and-terrain-api-s-for-aircraft-developers-to-implement-accurate-radar-predictive-windshear-egpws-and-metar-wind-uplink/442016)
Terrain Radar Availability: [SimBridge](https://docs.flybywiresim.com/simbridge/)
