### ISSUE TITLE
[BUG] Throttle indicator on upper ECAM stuck on 100% IDLE before applying MCT or TOGA

### ISSUE THREAD

**Issue by CoffeePanda0** [flybywiresim/a32nx#748]
**Mod Version**

**Describe the bug**

When throttle is at idle, the upper ECAM still shows 100% under IDLE if you have not yet applied MCT, CLB or TOGA

**To Reproduce**

1. Spawn in on the apron from cold and dark
2. Look at the upper ECAM throttle display when the thrust lever is set to idle, it is stuck at 100% 
3. Once you take off and apply MCT, CLB or TOGA, the N1 is correct. When going back to IDLE after this, it now shows 0% like it is meant to

**Expected behavior**

**Actual behavior**

Throttle indicator should show 0% when throttle is idle on the ground

**References**

![image](https://user-images.githubusercontent.com/34898787/93664422-d4adf580-fa66-11ea-85fb-ce32d0b80a28.png)

**Additional context**

Discord username (if different from GitHub): obama
#6262

**Comment by UncleClapton** [comment]
Hi, which version of the mod are you running? are you able to reproduce this on the latest master?

**Comment by CoffeePanda0** [comment]
> 
> 
> Hi, which version of the mod are you running? are you able to reproduce this on the latest master?

Ah sorry, I am on latest master and have only started having this issue since the new asobo update

**Comment by Benjozork** [comment]
I will be working on this.

**Comment by resir014** [comment]
This happens to me too, albeit with a slightly different number (88.4%), latest stable (v0.3.0). Though when I arm the autothrottle it will briefly flicker with the normal throttle readings.

**Comment by hotshotp** [comment]
fixed in the pr linked to the above linked issue
