### ISSUE TITLE
W/B in the AOC menu is greyed

### ISSUE THREAD

**Issue by Koellerman** [flybywiresim/a32nx#7486]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2022-09-09T10:52:10+00:00",
    "ref": "refs/heads/master",
    "sha": "9a216dfe61228d3a6889f7afb82b42808a7836fa",
    "actor": "frankkopp",
    "event_name": "manual",
    "pretty_release_name": "master:9a216dfe"
}
```

### Describe the bug

When I want to calculate the W/B in the AOC menu of the FMC, the W/B point is greyed and i can‘t push the Button to get into the W/B page

### Expected behavior

Push the W/B button to load Pax and Cargo and Start the boarding

### Steps to reproduce

Load a flight from the Gate with a flightplan from msfs. No link to simbrief. In the EFB i can load Pax and Cargo

### References (optional)

![AC269A3C-0E24-450D-B711-A004ED19140C](https://user-images.githubusercontent.com/80482994/189885837-431cb20c-ca67-43b4-ba2c-2a8775c70f1d.jpeg)

**Comment by Benjozork** [comment]
As indicated in the [documentation](https://docs.flybywiresim.com/fbw-a32nx/feature-guides/loading-fuel-weight/) and announced on Discord and social media, the weight and balance is now on the flyPad for versions other than Stable.

p.s.: please prefer discord for questions in the future - github is more for confirmed bug reports.
