### ISSUE TITLE
Web ND, PFD, Engine display, System display and EFB 

### ISSUE THREAD

**Issue by ryucz** [flybywiresim/a32nx#7490]
### Aircraft Version

Development

### Description

 Primary Flight Display, Navigation Display, Engine Display, System Display and EFB should be available via web interface as MCDU is. 

This is often reqested feature by cockpit builders. 

The **most important one would be the EFB**, because this interface needs to be controlled, but displaying it as pop-out doesn't work very well.

**Comment by frankkopp** [comment]
duplicate of #6712
