### ISSUE TITLE
wont let AI fly the plane

### ISSUE THREAD

**Issue by tonygard** [flybywiresim/a32nx#7492]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2022-06-18T02:11:53+00:00",
    "ref": "refs/tags/v0.8.2",
    "sha": "5cfa8478aea0fd20ae4a3e6f624714d0e04fab60",
    "actor": "Benjozork",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.8.2"
}
```

### Describe the bug

wont let AI fly the plane

### Expected behavior

ai to fly plane

### Steps to reproduce

choose ai to fly plane

### Discord Username (optional)

toxo2436

**Comment by Benjozork** [comment]
AI is not supported.
