### ISSUE TITLE
W/B page unavailable

### ISSUE THREAD

**Issue by tonnyc2** [flybywiresim/a32nx#7493]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2022-09-09T10:52:10+00:00",
    "ref": "refs/heads/master",
    "sha": "9a216dfe61228d3a6889f7afb82b42808a7836fa",
    "actor": "frankkopp",
    "event_name": "manual",
    "pretty_release_name": "master:9a216dfe"
}
```

### Describe the bug

![20220917104905_1](https://user-images.githubusercontent.com/113764366/190848769-434fce55-3407-4a91-ac9b-27033509d55d.jpg)

Missing the W/B menu page on the MCDU. It's been there in previous builds, but not there anymore. To me it was a crucial part of the realism and experience. 
Has it been removed, or do I need to do some tweaking?

### Expected behavior

W/B menu needs to be present on the MCDU.

### Steps to reproduce

Not showing at all.

**Comment by ErikNL80** [comment]
Is moved to the EFB, there you can load fuel, pax and cargo...
