### ISSUE TITLE
All lights on, cant interact with anything and front landing gear gone

### ISSUE THREAD

**Issue by gamingatmax3090** [flybywiresim/a32nx#7496]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2022-09-18T10:41:35+00:00",
    "ref": "refs/heads/master",
    "sha": "d8b0884d8176922f7d19cdf590a2be78e4eb946a",
    "actor": "frankkopp",
    "event_name": "manual",
    "pretty_release_name": "master:d8b0884d"
}
```

### Describe the bug

When I spawn in the A32NX at any airport, all of the lights in the cockpit are on and I can't click any of the buttons or move anything like the throttle, flaps lever, trim, etc. I also noticed that the front landing gear is either invisible or just not there. I have no liveries or mods installed except the A32NX. Believe me when I say I have tried everything. I have tried older versions (including so old that it integrates with the vanilla A320NEO) and have had the same issue with all of them. I have also tried stable, development, and experimental versions of the aircraft. I have tried spawning at 8 different airports. I have tried switching the flight model. None of it works.

### Expected behavior

The aircraft spawns in a cold and dark state with only lights that are supposed to be illuminated,

### Steps to reproduce

Use any version of the aircraft.

### Additional info (optional)

MSFS v1.7.12.0

**Comment by Benjozork** [comment]
The A32NX only works with the latest version of MSFS. Please buy the game.
