### ISSUE TITLE
server.exe not existing on MCDU SERVER folder

### ISSUE THREAD

**Issue by hartt20** [flybywiresim/a32nx#7513]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2022-09-25T06:00:00+00:00",
    "ref": "refs/heads/master",
    "sha": "75a81d290b24023050c518a6ef529464ae565571",
    "actor": "svengcz",
    "event_name": "manual",
    "pretty_release_name": "master:75a81d29"
}
```

### Describe the bug

server.exe doesn't exist on MCDU SERVER folder on the route C:\Users\Msi\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\Community\flybywire-aircraft-a320-neo\MCDU SERVER

It just shows an MCDU SERVER direct access.

### Expected behavior

As shown in documentation, the folder MCDU SERVER should contain a server.exe file to launch MCDU web interface

### Steps to reproduce

I just opened the MCDU SERVER folder

### References (optional)

![image](https://user-images.githubusercontent.com/114355286/192156034-27dfdfb5-4dc3-43af-8d36-4a76be07aae5.png)

### Discord Username (optional)

hartt20

**Comment by Finn-D-AEWG** [comment]
You can open the Web MCDU via SimBridge:
https://docs.flybywiresim.com/simbridge/remote-displays/remote-mcdu/

**Comment by hartt20** [comment]
Thank you for your answer but it’s not valid at all since this is launching the local MCDU web browser. I need the address to open it from my iPad.

Thanks

Santi P.
________________________________
De: Finn-D-AEWG ***@***.***>
Enviado: Sunday, September 25, 2022 7:27:54 PM
Para: flybywiresim/a32nx ***@***.***>
Cc: hartt20 ***@***.***>; Author ***@***.***>
Asunto: Re: [flybywiresim/a32nx] server.exe not existing on MCDU SERVER folder (Issue #7513)


You can open the Web MCDU via SimBridge:
https://docs.flybywiresim.com/simbridge/remote-displays/remote-mcdu/

**Comment by Finn-D-AEWG** [comment]
If you read through the document you‘ll find the section „How to open the remote MCDU Display“. There you can see what you have to do to open it on another device.

Open your browser of choice and navigate to http://{[IP Address](https://docs.flybywiresim.com/simbridge/troubleshooting/#network-configuration)}:{[Port](https://docs.flybywiresim.com/simbridge/configuration/#server-settings)}/interfaces/mcdu

**Comment by tyler58546** [comment]
The MCDU Server has been replaced by SimBridge. As @Finn-D-AEWG mentioned, the documentation for this is available at https://docs.flybywiresim.com/simbridge/remote-displays/remote-mcdu/.
