### ISSUE TITLE
Flickering Screens/MCDU since SU10

### ISSUE THREAD

**Issue by TobiasM26** [flybywiresim/a32nx#7514]
### Aircraft Version

Experimental

### Build info

```json
{
    "built": "2022-09-24T09:18:07+00:00",
    "ref": "refs/heads/experimental",
    "sha": "4be5a14e590bf233d960b7ad87a0bc133d0a5f8b",
    "actor": "tracernz",
    "event_name": "manual",
    "pretty_release_name": "experimental:4be5a14e"
}
```

### Describe the bug

Since Sim Update 10 the screens, MCDU and the radio frequency started to flicker.

The problem gets bigger the more i zoom out. 

Graphic-Settings didnt chance since the update. DLSS is not in use. (Problem exists if TAA is in use)

(See also attached video)

### Expected behavior

I want to report the bug to the FBW team, maybe I can get also tips how can i fix it for myself. (maybe local problem)

### Steps to reproduce

The problem exists at every launch when TAA is activated. 

### References (optional)

Uploading Microsoft Flight Simulator - 1.27.21.0 2022-09-25 20-42-47.mp4…

**Comment by TobiasM26** [comment]
https://user-images.githubusercontent.com/114358833/192160022-e90ce1ed-e280-4792-85ed-9e4bbad8aa0e.mp4

**Comment by NicoCaptn** [comment]
I have the exact same issue. And furthermore some flickerings shadows: https://github.com/flybywiresim/a32nx/issues/7510

I was in the su 10 beta and the problem didn't existed there.

**Comment by TwattyBollox** [comment]
Same here - development version
RX 6600 current WQHL drivers 22.5.2
Not noticeable at standard cockpit viewpoint - zooming backwards (out) it gets worse with every notch backwards
Can confirm - TAA only, DLAA and FXAA do not cause the issue.
