### ISSUE TITLE
Replay Gears

### ISSUE THREAD

**Issue by Stiixxy** [flybywiresim/a32nx#7530]
### Aircraft Version

Experimental

### Build info

```json
{
    "built": "2022-09-29T11:39:30+00:00",
    "ref": "refs/heads/experimental",
    "sha": "8df6e5933035d9c318faf8e42a291a9092f73faf",
    "actor": "Saschl",
    "event_name": "manual",
    "pretty_release_name": "experimental:8df6e593"
}
```

### Describe the bug

Gear status is no longer honored in replay. Data is send coorrectly, but not replayed.

I've tested it using replay tools such as SkyDolly and FlightRecorder, flight recorded (https://flightsim.to/file/8163/flight-recorder) also mentions the following: 
Incompatibiity

- FBW A32NX

  - The 32NX starts to replace existing code that works with SimConnect with new code that ignores SimConnect. This means the aircraft will ignore the replay data Flight Recorder send to the sim. You will see that certain variables get replayed as in other aircraft, and the rest don't.

  - Workaround (suggested by Abriael): since the recording still has correct data, you can replay it on stable/dev variant of the 32NX, or even the default A320.

Making a recording with the expirimental version and then using the Stable version the gears do move correctly. So the data is recorded correctly and has even worked before, but the behavious has changed in experimental

The flight surfaces also dont seem to move correctly but this might have a bigger underlying issue as mentioned in https://github.com/flybywiresim/a32nx/issues/5927

### Expected behavior

Expect the gears to move correctly when using a replay tool as they have before
It works as expected in stable, but not in dev or experimental

### Steps to reproduce

Use a tool such as SkyDolly or FlightRecorder to record a flight
Replay the flight and the gears wont show correctly in experimental
Any other version and the gears will show correctly

**Comment by Benjozork** [comment]
The gear system was entirely replaced with a physically simulated one and therefore compatibility with replay tools is going to be limited.

If the replay tool supports reading LVars then this can be fixed by the developer if they made a special A32NX profile or allowed people to do so. If it doesn't then this is unfortunately not fixable at the moment.

**Comment by Stiixxy** [comment]
Interesting, so it likely is more linked to the issue above. As mentioned though the reading seems to be fine, it seems more to do with an issue of writing, correct?

**Comment by Benjozork** [comment]
I don't know what you mean by reading and writing in this context.

**Comment by Stiixxy** [comment]
When replaying the data to the default a320 (or stable version). The gear state shows up correctly. 

So it reads or records the data correctly. The recording knows whether they are open or closed. 

When replaying the same data to the experimental version the gear state doesn't sync. (It stays at the state before the replay was started. So either they never close or never open). 

So it seems the replay software knows when the gears are opened or closed. It's just not able to replay that state to the plane

**Comment by Benjozork** [comment]
Yeah, because the plane is made to use data from our physically simulated system and not the stock sim data.

If there is some indication of a replay going on, it might be possible to make it read that data exclusively during replay, but I don't know of such thing.

**Comment by Stiixxy** [comment]
Ahh right that makes sense. 

But is there no variable for the gear state that's written on replay? Maybe it only has to synchronize the state, and not the actual position, this can then be simulated again. 

(I understand this is a small QoL issue, but would be a nice fix)

**Comment by Benjozork** [comment]
It is written. But we do not read it because we use our own simulation instead.

If there was an indication that a replay was happening we could use it in that case only.
