### ISSUE TITLE
Latest Dev Build ist not working

### ISSUE THREAD

**Issue by NicoCaptn** [flybywiresim/a32nx#7541]
### Aircraft Version

Development

### Build info

```json
.
```

### Describe the bug

Latest Dev build is not working. When I start a flight for the first time it's normal that It takes arround 5 minutes due to WASM compilation. But with the latest build I have to abort It after 10 minutes. Going back to the last Dev build its working fine.

### Expected behavior

Startup with a new build for the first time should not take longer than 5-7 minutes.

### Steps to reproduce

Upgrade to the latest dev build and start a flight.

**Comment by Benjozork** [comment]
> Startup with a new build for the first time should not take longer than 5-7 minutes.

This is not correct, it can take up to 20 minutes on some systems.

Please use Discord for installation support.
