### ISSUE TITLE
1

### ISSUE THREAD

**Issue by biker18** [flybywiresim/a32nx#7553]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2022-06-18T02:11:53+00:00",
    "ref": "refs/tags/v0.8.2",
    "sha": "5cfa8478aea0fd20ae4a3e6f624714d0e04fab60",
    "actor": "Benjozork",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.8.2"
}
```

### Describe the bug

43MTHYZBRBKJGW 

### Expected behavior

error install fsltl injector

### Steps to reproduce

1 2 3

**Comment by 2hwk** [comment]
Issue should be in installer repo, closing.
