### ISSUE TITLE
[BUG] Autobrakes MAX before take-off disarm when braking

### ISSUE THREAD

**Issue by ErikNL80** [flybywiresim/a32nx#756]
**Mod Version**

Master

**Describe the bug**

Before take-off one of the items on the checklist is putting the autobrakes to MAX instead of an RTO. However, when you use the brake the autobrake disarms. When landing this is normal behaviour, but not when taking off.

**To Reproduce**

1. Set-up a flight and follow the T/O config settings
2. After verifying autobrakes MAX settings, apply brakes
3. Autobrakes MAX has been disarmed and needs to be set again

**Expected behavior**

When using the autobrakes MAX option before take-off this setting should not be undone by braking.

**Actual behavior**

When setting the autobrakes to MAX and applying brakes, autobrake disarms.

**References**

**Additional context**

Discord username (if different from GitHub):

**Comment by Venorcis** [comment]
Already reported multiple times; see #255

**Comment by ErikNL80** [comment]
Sorry for double reporting. Used the search function but could nof find a similar report. Maybe good to follow up in the original thread.
