### ISSUE TITLE
Deboarding Button

### ISSUE THREAD

**Issue by JustARaceThing** [flybywiresim/a32nx#7561]
### Aircraft Version

Experimental

### Description

As someone who files around 2 legs a day, one major gripe I have had in the turn around phase of flight is the fact that deboarding the plane is a bit more cumbersome then I would like. Right now there is no natural way to deboard the aircraft after completing the flight. What I would like to see which is a small addition, which could be a large quality of life improvement, is the ability to deboard the plane through a button upon completion of a flight. As of right now the setting pax to 0 method causes hiccups with the payload tab as it forces the boarding time to instant and sometimes I have had it lock in that state even after importing a new flight plan from simbrief. It is all a bit "hacky" in my opinion.

It would be great to include a dedicated button to deboard the plane which preserves the boarding time state and the pax still deboard in a realistic fashion. Much like a inverse boarding button. Initially just having the button in place the whole time is totally fine by me, but maybe in future iterations it can detect when one has arrived at their destination and present itself then.  

### References (optional)

![Screenshot_1](https://user-images.githubusercontent.com/114666086/197272619-7777a185-8882-4f66-a0c4-b23891c46857.png)

this is one from the fenix as one may have used, simple yet gets the job done

**Comment by gizmo71** [comment]
It would also be nice to have an option to automatically trigger this when the seat belt sign is off and the front cabin door is open.
