### ISSUE TITLE
a32nx flybywire fallure

### ISSUE THREAD

**Issue by ninounet60** [flybywiresim/a32nx#7564]
### Aircraft Version

Development

### Build info

```json
I don’t know what his
```

### Describe the bug

The simulator works until I launch a flight with the flybywire A32nx and the flight loading screen never ends and I have to make an end of task to not be blocked anymore.

### Expected behavior

I’m waiting to be told how to deal with this.

### Steps to reproduce

Launching a flight with the flybywire A32nx after the last update.

### Discord Username (optional)

ninounet60

**Comment by Gurgel100** [comment]
How long are you waiting in the loading screen? In the first load after an update the WASM must be compiled which can take up to 20 minutes.

**Comment by frankkopp** [comment]
Please report this on Discord to get support - this is not a propper Issue report we can work on. 
Closing this.
