### ISSUE TITLE
Chrono push button programmatic access

### ISSUE THREAD

**Issue by emmanuelcohenlaroque** [flybywiresim/a32nx#7579]
### Aircraft Version

Development

### Description

Afaik, there is no event associated to the Chrono start/stop push button (the one on the left side of the FCU near the right joystick priority button). As I am developing a home cockpit, I would like to know how the hardware could activate that button. May be adding a route on Simbridge ? Thanks a lot

### Discord Username (optional)

isaa A320N#8225

**Comment by gizmo71** [comment]
Isn't that `A32NX.EFIS_L_CHRONO_PUSHED`?

**Comment by emmanuelcohenlaroque** [comment]
> Isn't that `A32NX.EFIS_L_CHRONO_PUSHED`?
Thanks @gizmo71 
Can this event be accessed using SimConnect or any other network access ?

**Comment by gizmo71** [comment]
> > Can this event be accessed using SimConnect or any other network access ?

Yes, that's how I use it from some custom software. Unlike LVars, customs events are fully supported by SimConnect just like built in MSFS events.

**Comment by frankkopp** [comment]
https://docs.flybywiresim.com/fbw-a32nx/a32nx-api/a32nx-flightdeck-api/#warning-panel

Closing as this has been answered.
