### ISSUE TITLE
[BUG] Unable to input From/To into INIT page on MCDU

### ISSUE THREAD

**Issue by GamingAstronamy** [flybywiresim/a32nx#758]
**Mod Version**
Master 

**Describe the bug**
When trying to enter KJFK/KMSP into the From/To section on the INIT page of the MCDU it says “Not In Database.” If I try to enter the same route in again it just disappears. I then have to type KJFK/KMSP again and it still doesn’t work. I’ve also tried using KJFK/KMCO and KLAX/KLAS, same thing happened. Also, nothing is entered into the F-PLN page, so this isn’t a visual bug,

**To Reproduce**
1. Begin a flight, cold and dark.
2. Get to the MCDU part of the checklist
3. Type your route into the MCDU. EI:(KJFK/KMSP)
4. Enter what you type into the From/To section of the INIT page

**Expected behavior**
The route that I typed in should appear below From/To
and both airports should appear in the f-pln page

**Actual behavior**
Nothing appears below From/To or on the F-PLN page

**References**
https://imgur.com/a/Ax5aNDo

**Additional context**
Discovered this bug while on the ground at JFK
Bug appeared after new MSFS update

Discord username: GamingAstronamy (#1341)

**Comment by olafsmit** [comment]
Same here mate, did you find a solution yet? Many thanks

**Comment by mariusrisan** [comment]
Same issue here. Even if I choose a route from the built-in flightplanner nothing appears.

**Comment by mariusrisan** [comment]
After deleting "Highonsnow_InstrumentRefreshFPSPatch_0.1.03" the problem disappeared for me.

**Comment by MaoamDEV** [comment]
Can confirm that this is a bug caused by the High on Snow Mod. (Which isn't needed anymore at all after the last Update from MS.)

**Comment by olafsmit** [comment]
You guys are legends!...

**Comment by LUFTHANSA51** [comment]
How can I find “ Highonsnow_InstrumentRefreshFPSPatch_0.1.03”?
Is in the mfs2020 file?

**Comment by LUFTHANSA51** [comment]
> After deleting "Highonsnow_InstrumentRefreshFPSPatch_0.1.03" the problem disappeared for me.
How can I find “ Highonsnow_InstrumentRefreshFPSPatch_0.1.03”?
Is in the mfs2020 file?

**Comment by olafsmit** [comment]
I believe it is called FPS-fix in the community folder

**Comment by MaoamDEV** [comment]
> > After deleting "Highonsnow_InstrumentRefreshFPSPatch_0.1.03" the problem disappeared for me.
> > How can I find “ Highonsnow_InstrumentRefreshFPSPatch_0.1.03”?
> > Is in the mfs2020 file?

Either its called "FPS-fix" or "HighonSnow_[...]", but should be in the Community folder. If these mods don't say you anything, than I guess you don't got them installed.

**Comment by resir014** [comment]
I'm putting this here from the Discord for future reference, but I'm also getting the "not in database" bug when entering dep/dest airports on the init page as well. **But I don't have the FPS fix installed, nor do I ever have it installed.**

![](https://cdn.discordapp.com/attachments/748731242912022649/759024356989992960/unknown.png)

Other things to note:

- This bug also exists on the vanilla A320.
- I've tried doing everything that's suggested to me on the discord (full restart of PC + MSFS, rebuilding the community folder entirely, etc.)
- if I set a DCT route between my 2 airports, the F-PLN screen on the MCDU is absolutely bugged (happens on both the mod and vanilla), nor can I enter departures/airways from it.

![](https://cdn.discordapp.com/attachments/748731242912022649/759033972293894184/unknown.png)

**Comment by MaoamDEV** [comment]
> I'm putting this here from the Discord for future reference, but I'm also getting the "not in database" bug when entering dep/dest airports on the init page as well. **But I don't have the FPS fix installed, nor do I ever have it installed.**
> 
> ![](https://camo.githubusercontent.com/66f5460eca9041ddef86c97766a73d80d3797db4/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3734383733313234323931323032323634392f3735393032343335363938393939323936302f756e6b6e6f776e2e706e67)
> 
> Other things to note:
> 
> * This bug also exists on the vanilla A320.
> * Also happens after a clean reinstall of the sim.
> * I've tried doing everything that's suggested to me on the discord (full restart of PC + MSFS, rebuilding the community folder entirely, etc.)
> * if I set a DCT route between my 2 airports, the F-PLN screen on the MCDU is absolutely bugged (happens on both the mod and vanilla), nor can I enter departures/airways from it.
> 
> ![](https://camo.githubusercontent.com/92ee5027d091509bfb6f8321bc18e0ea9180ec42/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3734383733313234323931323032323634392f3735393033333937323239333839343138342f756e6b6e6f776e2e706e67)

Looks pretty the same as it did before I deleted the mod. But as you stated you never got it installed, so this is really strange. 

Can you please check if the FMC is working on other Airliner e.g. the 747? 
Do you got any other software running that is communicating to the sim?

**Comment by resir014** [comment]
@MaoamDEV It apparently also didn't work with other aircrafts.

Also as a quick update - doing a complete reinstall of MSFS (including deleting the packages folder + deleting the `%AppData%\Microsoft Flight Simulator` folder) seemed to work - A32NX seemed to work fine now and will see if it works fine with all my liveries installed.

**Comment by MaoamDEV** [comment]
> @MaoamDEV It apparently also didn't work with other aircrafts.
> 
> Also as a quick update - doing a complete reinstall of MSFS (including deleting the packages folder + deleting the `%AppData%\Microsoft Flight Simulator` folder) seemed to work - A32NX seemed to work fine now and will see if it works fine with all my liveries installed.

Thanks for the Update! So this is definitely a vanilla MSFS bug. There are some post in the FS-Forums as well, who are mostly referring to vanilla aircraft. I guess its another issue caused be 1.8.3.0. Lets hope the next patch is getting better.

**Comment by Eloeloell** [comment]
Hey! Have you guys found a solution to this problem? I have had the same problem for the past couple days.
