### ISSUE TITLE
"Retard" callout and "ldg" tab appear on ECAM on Takeoff

### ISSUE THREAD

**Issue by lionlggnd** [flybywiresim/a32nx#7580]
### Aircraft Version

Experimental

### Build info

```json
{
    "built": "2022-09-26T12:46:56+00:00",
    "ref": "refs/heads/experimental",
    "sha": "af2da3e3fbf824b917e46b848bd183496d528e35",
    "actor": "Saschl",
    "event_name": "manual",
    "pretty_release_name": "experimental:af2da3e3"
}
```

### Describe the bug

hi
in the experimental version of the a32nx, i'm having some issues on takeoff.
During taxing for TO (FLX) on runway, after 110knots i hear "retard" callout, as i'm landing, and LDG checklist appears on ECAM.
i'm not landing!
this issue isn't in the dev version.

flaps 2
spd brk arm
autobrakes not armed
seatbelts on
no smoking on

### Expected behavior

Not applicable

### Steps to reproduce

1. Press "fly"
2. Fuel load 6000kg (last flight)
3. payload 174 pax (15kg baggage\pax; pax:80kg)
4. seatbelts on, no smoke on, apu start, eng 2 start, eng 1 start
5. pushback and taxi from gate to runway
6. On runway, flap 2, FLX throttle
7. On 110 knots, **issue happens.**

**Comment by beheh** [comment]
You're most likely not setting your thrust lever to the correct value. Which FMA on your PFD (top row) and which thrust lever detent are you in when you get the callout?

**Comment by lionlggnd** [comment]
FLX/MCT Inviato da Posta per Windows Da: Benedict EtzelInviato: giovedì 3 novembre 2022 23:41A: flybywiresim/a32nxCc: lionlggnd; AuthorOggetto: Re: [flybywiresim/a32nx] "Retard" callout and "ldg" tab appear on ECAM on Takeoff (Issue #7580) You're most likely not setting your thrust lever to the correct value. Which FMA on your PFD (top row) and which thrust lever detent are you in when you get the callout?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by beheh** [comment]
Have you actually set a flex temperature in the MCDU? And if possible, please share a screenshot of the FMA next time this happens.

**Comment by lionlggnd** [comment]
I insert ZFW, ZFWCG, and routing.
From zfw zfwcg the mcdu automatically calculate other parameters.

**Comment by beheh** [comment]
Firstly, you're on a really old experimental - 2022-09-26T12:46:56+00:00. Please make sure to update.

And secondly, you will have to explicitly enter a FLEX TO TEMP on the PERF TO page. Doing the INIT process is not enough if you intend on doing a flex take-off. Alternatively you can just advance your thrust levers to TO/GA.

**Comment by lionlggnd** [comment]
A32nx is a a320neo.
Flx performance are not public.
How i calculate flx to temp

**Comment by frankkopp** [comment]
We do not accept github issue for Experimental - please use Discord to report issues and get help analyzing them while you are in the sim.
