### ISSUE TITLE
Minimum values should only be transmitted from FMGC in CRZ and later

### ISSUE THREAD

**Issue by beheh** [flybywiresim/a32nx#7610]
### Aircraft Version

Experimental

### Description

The FMGC should only expose the minimum settings after it has reached the CRZ phase or later and is at least within 200NM of the destination.

This should eventually resolve:
- the FMA showing the minimum even if set e.g. during preflight
- the experimental FWC calling out minimum if set during preflight

### References (optional)

https://discord.com/channels/738864299392630914/850710355877560350/1044558618982363176

**Comment by MarkusOlesenMohr** [comment]
Curious about this. The `L:AIRLINER_MINIMUM_DESCENT_ALTITUDE`, and `L:AIRLINER_DECISION_HEIGHT` are the default simvars, so its something that needs to be handled for the FMA, AltitudeReadout and AltitudeIndicator right?

**Comment by tracernz** [comment]
It would be either NCD or not transmitted prior to that time.

**Comment by MikioDK** [comment]
As far as I can see so far, the FMA gets the minimum values directly from the simvar, and the experimental FWC gets `minimum_for_mda_mdh_request_1` and `minimum_for_mda_mdh_request_1` from a discrete status word, but im a bit oblivious as to where it is being sent from, and where it is being handled by the FMGC .

**Comment by beheh** [comment]
I believe it should be sent by a DMC simulation (which we really don't have yet). That logic is temporarily in input.rs in the experimental FWS.

**Comment by beheh** [comment]
Reopening as #7830 was reverted.
