### ISSUE TITLE
[Dev Version] Wing light not toggleable

### ISSUE THREAD

**Issue by Mtuart** [flybywiresim/a32nx#7614]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2022-11-26T14:29:23+00:00",
    "ref": "refs/heads/master",
    "sha": "7d9e36c551a73705a64662c318a145f2ea8aaff3",
    "actor": "frankkopp",
    "event_name": "manual",
    "pretty_release_name": "master:7d9e36c5"
}
```

### Describe the bug

Wing Light can be turnt on (only left wing), yet is stuck in "ON" position with light showing on the left wing.

### Expected behavior

Wing Light should be toggleable

### Steps to reproduce

1. Turn on Wing Lights
2. Try turning off Wing Lights

### References (optional)

https://user-images.githubusercontent.com/96501232/204109508-c7b8e312-f1ec-4a67-a440-8706a30a3371.mp4

### Discord Username (optional)

Stuart#0420

**Comment by juliansebline** [comment]
Hello! Thank you for your report.

We have identified the issue and we'll fix it soon.

It appeared with a very recent commit to be able to use the mouse wheel on switches. Several switches do not work as they should.
