### ISSUE TITLE
Add option to toggle switches with mousewheel

### ISSUE THREAD

**Issue by michael60634** [flybywiresim/a32nx#7615]
### Aircraft Version

Development

### Description

In a recent merged [pull request](https://github.com/flybywiresim/a32nx/pull/7605), the ability to toggle switches with the mousewheel was added. It might be a good idea to add a toggle for this feature in the flyPad settings, as some users may prefer clicking or clicking and dragging to toggle switches. I know I personally have issues with accidentally toggling switches when trying to zoom in or out of something.

### Discord Username (optional)

michael60634#4776

**Comment by frankkopp** [comment]
I don't think that makes sense as most switches and knobs already use the mouse wheel. This PR simply makes the few which didn't also be usable for the wheel.

Btw. you can change the zoom mapping to a combination of another mouse button or keyboard press plus the wheel as zooming already often hits a switch/knobs.

**Comment by michael60634** [comment]
> I don't think that makes sense as most switches and knobs already use the mouse wheel. This PR simply makes the few which didn't also be usable for the wheel.
> 
> Btw. you can change the zoom mapping to a combination of another mouse button or keyboard press plus the wheel as zooming already often hits a switch/knobs.

I wasn't aware of this. Thanks for letting me know. In that case, I'll close the issue.
