### ISSUE TITLE
A32NX crashes MSFS to desktop after loading

### ISSUE THREAD

**Issue by DedaL54** [flybywiresim/a32nx#7619]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2022-06-18T02:11:53+00:00",
    "ref": "refs/tags/v0.8.2",
    "sha": "5cfa8478aea0fd20ae4a3e6f624714d0e04fab60",
    "actor": "Benjozork",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.8.2"
}
```

### Describe the bug

When I select the airport and start, after a long loading I wait a few minutes.... the MSFS simulation stops and I find myself on the desktop. 
I note that I installed the A32NX using the installer , and that the second plane 74S is loaded without problems! 
I think I tried all the tips and instructions related to the mentioned problem, but nothing gave results .....
I also note that I do not receive any message about any malfunction!!

### Expected behavior

I expect help in discovering the cause of the impossibility of starting the A32NX in the simulation

### Steps to reproduce

1. The error occurs every time I try to start a specific flight from point A to point B ....everything else is fine!

### Additional info (optional)

The problem appeared after SU10 .... before that I successfully flew on A32NX .... And it continues even after SU11 ...

### Discord Username (optional)

DedaL

**Comment by frankkopp** [comment]
As already explained on Discord there is nothing we can do and your issue report does not any additional facts that help us help you. 

Here is all we can help you with:

CTDs are mostly a MSFS sim issue and very hard to analyze. Here a collection of tips:
https://docs.flybywiresim.com/fbw-a32nx/support/reported-issues/#crash-to-desktop-ctd
also use the MSFS Forum:
https://forums.flightsimulator.com/c/bugs-and-issues/ctds/260
