### ISSUE TITLE
[BUG] build.py sometimes wipes the entire manifest.json / layout.json

### ISSUE THREAD

**Issue by TheOriginalBabu** [flybywiresim/a32nx#763]
**Mod Version**

masterrrrrr

**Describe the bug**

build.py likes to clear manifest.json or layout.json completely and crashes partway through

**To Reproduce**

1. run build.py
2. 
3.

**Expected behavior**

build.py to generate the manifest/layout.json's

**Actual behavior**

build.py ends up corrupting the layout.json/manifest.json some of the time

**References**

python closes,

**Additional context**

Discord username (if different from GitHub):

**Comment by UncleClapton** [comment]
Are you running build while the game is running? This sounds like a file lock issue.

**Comment by TheOriginalBabu** [comment]
No. Files are not even open in text editor.

**Comment by UncleClapton** [comment]
so I've been trying to test this out under various conditions in both cmd and powershell and it's always worked for me. We could add some safeguards to roll back the files if saving fails, but It would be nice to know exactly why this is happening on your system.

Could you provide some more information? I need to know:
  * What shell you're running from (`cmd`, `pwsh`, `wsl`, etc..). If running the script directly then it's likely `cmd`.
  * Python version (run `python.exe --version`)
  * Windows version (`1909`, `2004`, etc..)
  * Any errors that might output when you run the script.

**Comment by TheOriginalBabu** [comment]
Running from command prompt,
Python 3.7.8 x64
Windows build 2004

Couldnt find any errors, just straight out closing.
I recall it happening on a32nx version, but I use the custom modified build.py in 78x repo https://github.com/lmk02/B787-XE/blob/master/B787-XE/z_build.py
