### ISSUE TITLE
Minimum Fuel Scenario, the planes seemed to add 1000 LBS of fuel into each main tank at decent phase.

### ISSUE THREAD

**Issue by tomvachon** [flybywiresim/a32nx#7636]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2022-12-02T13:05:37+00:00",
    "ref": "refs/heads/master",
    "sha": "af3ff37cbb5977a7a2e7bf936cec78dbcef5d97a",
    "actor": "crocket63",
    "event_name": "manual",
    "pretty_release_name": "master:af3ff37c"
}
```

### Describe the bug

I was in a minimum fuel scenario yesterday where I had about 0.1 of extra fuel left if I had to divert and do a go-round.  I had about 1.3 for the main field and 0.8 for the alternate.  All fuel was loaded via the EFB with SimBrief as the source.

I was in a heavy turbulence situation which caused my flight to consume far more fuel even with the significant tail wind than expected. About 300 nm from field when I got the fuel consumption into the reserves alert.  I monitored it closely and called a Minimum Fuel to ATC which prioritized my landing.  The plane started transferring my outer tanks into the main wing tanks and once they were empty I believe I had about 300 lbs in each main wing tank.  

I then began my decent and all of a sudden my Fuel prediction page cleared out all its data with dashes and the ECAM fuel on the lower ECAM page showed I had exactly 1000 pounds in each tank.  This seems impossible as my Simbrief load sheet was as below. 

I know that the MSFS weight and balance page isn't to be used in the A32NX but I think its important data here.  Please see the screenshots below.   I can't tell if this is a prediction issue and I was never this bad on fuel or if something made the plane add fuel mid-flight

```
         PLANNED FUEL
---------------------------------
FUEL           ARPT   FUEL   TIME
---------------------------------
TRIP            DEN   3070   0143
CONT 15 MIN            447   0015
ALTN            COS    882   0028
FINRES                 788   0030
---------------------------------
MINIMUM T/OFF FUEL    5187   0256
---------------------------------
EXTRA                    0   0000
---------------------------------
T/OFF FUEL            5187   0256
TAXI            SAN    230   0020
---------------------------------
BLOCK FUEL      SAN   5417
PIC EXTRA            .....
TOTAL FUEL           .....
REASON FOR PIC EXTRA ............
```

I was able to capture the FDR data (but it doesn't seem helpful, let me know if you want it) but also these screenshots which I think are very important.
![Screenshot 2022-12-04 221723](https://user-images.githubusercontent.com/331845/205644433-9e04c396-949a-4381-bc04-df9324bd214b.png)
![Screenshot 2022-12-04 221742](https://user-images.githubusercontent.com/331845/205644439-904e2da4-7a67-4fa5-a020-d79dc2ad5aab.png)
![Screenshot 2022-12-04 221804](https://user-images.githubusercontent.com/331845/205644452-b6b92c83-368f-4527-926d-368f77455538.png)

### Expected behavior

The fuel level should not randomly increase and stay predictable

### Steps to reproduce

1. Fly into a fuel minimum situation where you have less than 1000 lbs for your primary and alternate
2. Begin decent
3. See fuel changes

### Discord Username (optional)

Thomas Vachon#6268

**Comment by tomvachon** [comment]
I just noticed that my W&B page was uploaded in gallons too, so that is not as helpful as I thought.  It still seems very weird, it could have been a bad prediction but I was monitoring the EMAC fuel page not the fuel prediction FMC page/

**Comment by donstim** [comment]
I don't think the fuel prediction has been corrected yet. I don't see anything amiss in your screenshots. If you had a screenshot showing the amount of fuel in the tanks (either the lower ECAM or EFB shots like the ones you provided) that were earlier and showed a lower amount of fuel than the screenshots you provided, then there would definitely be an issue.

As it is, your screenshots show that the airplane has used 2990 kg of fuel ("F. USED" on the lower ECAM page) and has 2425 kg of fuel remaining (2420 in FOB, 2425 by adding the tank values shown on the lower ECAM page, and 2430 shown on the EFB page -- all subject to their own tolerances). Adding the fuel used to the fuel remaining, 2990+2425, gives 5415 kg, which agrees with the simBrief OFP block fuel.

**Comment by tomvachon** [comment]
Yea. The ECAM page definitely was under 2000 before it “fueled” up. Is it
possible the ECAM page is also based off the fuel predictions and not the
per-tank volumes?

**Comment by donstim** [comment]
The ECAM page is based on actual fuel quantity. It's not a predicted value.

**Comment by tomvachon** [comment]
OK, I'm going to close this, if I get to this scenario again, I will be sure to get more data.
