### ISSUE TITLE
ATC COMM - SATCOM INSTALLED

### ISSUE THREAD

**Issue by Oyu-De** [flybywiresim/a32nx#7641]
### Aircraft Version

Experimental

### Description

![resim](https://user-images.githubusercontent.com/66401072/206268185-23646a6f-0984-4a5a-9e0e-e681c7a8a9f2.png)

Link EFB SATCOM option to ATC COMM DATALINK STATUS page so that it displays "SATCOM INSTALLED" instead of "NOT INSTALLED"

### Discord Username (optional)

Oyu#1741

**Comment by frankkopp** [comment]
Reference:
![image](https://user-images.githubusercontent.com/16833201/206714742-ab1781f4-9c45-46cc-a419-189a6b669bf9.png)

**Comment by StenAfMARS** [comment]
I wouldn't mind taking a stab at this issue

**Comment by frankkopp** [comment]
> I wouldn't mind taking a stab at this issue

Go ahead :) - ask on Discord #dev-support if you need help.

**Comment by svengcz** [comment]
Here is a press release about SATCOM for crews:
https://aircraft.airbus.com/en/newsroom/news/2022-04-cockpit-satcom

The SATCOM for the crew can be also available without this big antenna. Multiple configurations exist.

Don't know how you want to handle this, but we will later also have SATCOM without this antenna

**Comment by StenAfMARS** [comment]
Just to get my feet wet, with this project, I'll just stick to implementing the basics aka. Satcom enabled = DLK AVAIL.
After that I might look into the whole LCS thing

**Comment by mico975** [comment]
Fixed by #7656
