### ISSUE TITLE
[REQUEST] Interfacing custom switches with SimConnect

### ISSUE THREAD

**Issue by omrygin** [flybywiresim/a32nx#765]
**Is your feature request related to a problem? Please describe.**

FSUIPC not recognizing switch toggling of smoke sign, seat belts, emergency exists etc.

**Describe the feature you'd like to see implemented**

For interfacing with e.g. Arduino to make home cockpits, one needs these EventIDs to bind them to switches on the board.

**References**

**Additional context**

Discord username (if different from GitHub): omryg

**Comment by Venorcis** [comment]
See #597

**Comment by UncleClapton** [comment]
The tl;dr here is that this is really out of our control at the moment. The simvars we introduce for various buttons are really more for our internal use, but not because we want it that way. If we knew of a way we could expose them over simconnect we would.

**Comment by GRnice** [comment]
Hi,

I've found a thread in FSDeveloper about this subject
https://www.fsdeveloper.com/forum/threads/simconnect-accessing-local-variables.448704/

from what I understood, currently it's not easy to expose custom simvar

**Comment by omrygin** [comment]
It seems as some variables are exposed. How can that be? Here's what I found using spad.next:

![image](https://user-images.githubusercontent.com/56735767/93809228-b823e000-fc55-11ea-8675-68cb7be4dea3.png)

**Comment by lukecologne** [comment]
Those are default SimVars.

**Comment by GRnice** [comment]
Specific commands (example: PTU button ON/OFF) can't be exposed from default SimVars.
But for your initial request @omrygin  I think it's possible to enable/disable smoke sign & seat belts sign by using default SimVars. A3NX must use these simvars:

CABIN_SEATBELTS_ALERT_SWITCH
CABIN_NO_SMOKING_ALERT_SWITCH
