### ISSUE TITLE
Flight plan page breaks

### ISSUE THREAD

**Issue by johnpmaguire** [flybywiresim/a32nx#7671]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2022-12-27T12:43:56+00:00",
    "ref": "refs/heads/master",
    "sha": "18f7db2c972568e7b27746ef6ed34667dfbb6022",
    "actor": "crocket63",
    "event_name": "manual",
    "pretty_release_name": "master:18f7db2c"
```

### Describe the bug

When the route was entered the destination (EGLL) line on the flight plan page had the letter N instead of the time and distance. When scrolling down into the STAR section the page broke and was blank. 

### Expected behavior

The destination should show the arrival UTC and Distance. 

### Steps to reproduce

Using Dev 18f7db2 and AIRAC 2103 with the following route.
EGNM EGLL POL2X POL MCT LISTO L612 HON HON1H via BNN ILS27L

![image](https://user-images.githubusercontent.com/31592841/209687583-b8aa63f5-6e86-4d6d-ae31-c934153891a4.png)

![image](https://user-images.githubusercontent.com/31592841/209687506-fbfbd225-4d90-4ab1-b082-87a99b13a8eb.png)

The same dev version with latest navigraph AIRAC works.
![image](https://user-images.githubusercontent.com/31592841/209687226-0e231871-1842-4fdb-a690-c5715d5b6459.png)

### Discord Username (optional)

john P Maguire#9027

**Comment by johnpmaguire** [comment]
The route was imported from SB with AIRAC 2103 into MSFS with default nav data. The route is valid for 2103 and the current AIRAC.

**Comment by tracernz** [comment]
I couldn't reproduce this on the current `master` branch with default data or Navigraph, imported from SimBrief or manually.

**Comment by johnpmaguire** [comment]
> I couldn't reproduce this on the current `master` branch with default data or Navigraph, imported from SimBrief or manually.

Thanks Tracer. I think we have narrowed it down to having iniScene EGLL scenery and default nav data. All other combinations of 
MSFS default or premium EGLL with default or navigraph have worked correctly. Only iniScene and default seem to mess up the SID and STAR at EGLL.

**Comment by johnpmaguire** [comment]
Another report that is most likely the same was reported in flight school channel at 1515z today by Nickslon#9181 at EDDV.

**Comment by tracernz** [comment]
I’ll give it another go with that scenery enabled in a couple of days. 👍

**Comment by Saschl** [comment]
If it helps, here's the logs that come up when loading the approach

**Comment by tracernz** [comment]
Known issue with Ini's EGLL causing all the waypoints to be deleted from the database. Nothing we can do about it unfortunately.
