### ISSUE TITLE
Targeting last selected speed even when in managed speed

### ISSUE THREAD

**Issue by ttrcatbus** [flybywiresim/a32nx#7672]
### Aircraft Version

Experimental

### Build info

```json
{
    "built": "2022-12-26T15:50:58+00:00",
    "ref": "refs/heads/experimental",
    "sha": "0c3703da7f87d79e2027e55ea3de38456484bce0",
    "actor": "frankkopp",
    "event_name": "manual",
    "pretty_release_name": "experimental:0c3703da",
    "version": "v0.10.0-exp.0c3703d"
}
```

### Describe the bug

Despite managing speed in FCU, aircraft will still target the last selected speed. Occurs in climb, cruise, and descent from what I've tested.

### Expected behavior

If aircraft is faster/slower than target speed, then it will adjust pitch or thrust (depending on phase of flight) for said target speed.

### Steps to reproduce

1. Depart in A32NX
2. Note managed speed target
3. Set new selected speed different from managed speed
4. Aircraft should adjust accordingly
5. Manage speed once again
6. Aircraft should stay at the last selected speed

### References (optional)

https://streamable.com/bo5yfs (Cruise, highlights @ 0:31, 0:43)
https://streamable.com/60wv0b (Cruise, highlights @ 0:03, 0:22)
https://streamable.com/ldmu4h (Descent, highlights @ 0:02, 0:14)

### Additional info (optional)

Using MSFS Addons Linker.

### Discord Username (optional)

pochi#4630

**Comment by BlueberryKing** [comment]
This is probably an issue related to VNAV. I will investigate 👍.

**Comment by BlueberryKing** [comment]
Hi, when you have the chance, would you mind testing this again? This should have been fixed with a recent VNAV update (Experimental only)

**Comment by ttrcatbus** [comment]
Sounds good, will test tonight or tomorrow!

**Comment by ttrcatbus** [comment]
Tested and working now, thank you and the team for all your hard work!

**Comment by BlueberryKing** [comment]
Excellent. Thank you for testing and the kind words!
