### ISSUE TITLE
SimBridge doesn't stop

### ISSUE THREAD

**Issue by jcc1953** [flybywiresim/a32nx#7673]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2022-12-28T10:27:24+00:00",
    "ref": "refs/heads/master",
    "sha": "dae734104cdc4b5e0211f4e21f86ffe0c9b9d042",
    "actor": "frankkopp",
    "event_name": "manual",
    "pretty_release_name": "master:dae73410"
}
```

### Describe the bug

Sometimes Simbridge still runs, with a big load on the processor, after pushing the stop button.

### Expected behavior

Simbridge must stop every time the stop button is pushed.

### Steps to reproduce

1. Activate Simbridge
2. Stop Simbridge

### References (optional)

![SimBridge](https://user-images.githubusercontent.com/75140388/209956562-d487ced1-9850-4ff4-a705-de3aa10af010.jpg)

**Comment by 2hwk** [comment]
https://github.com/flybywiresim/simbridge/issues/62
Tracked here, closing.
