### ISSUE TITLE
Wrong labels Overhead upper maintenance panel and CVR HEAD SET wrongly modeled

### ISSUE THREAD

**Issue by tomprovence2** [flybywiresim/a32nx#7682]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2022-12-07T00:57:56+00:00",
    "ref": "refs/heads/master",
    "sha": "5697964080ec93223b3271ad5ac1ea626959cc49",
    "actor": "tracernz",
    "event_name": "manual",
    "pretty_release_name": "master:56979640"
}
```

### Describe the bug

1) CVR HEAD SET not a push button but an audio jack headset
2) Incorrect label for SVGE INT OVRD, right label is SVCE INT OVRD
3) Incorrect label for APU AUTO EXITING, right label is APU AUTO EXTING

### Expected behavior

Modify shape of CVR HEAD SET and modify incorrect labels

### Steps to reproduce

1. Modify shape of CVR HEAD SET into the right one (audio jack female adapter 3.5 mm ?)
2. Rename incorrect labels

### References (optional)

https://www.smartcockpit.com/aircraft-ressources/A320-Overhead_Panel.html
https://www.youtube.com/watch?v=E3-uOqD63-o&list=PLdOwRGupI0JerxH2yupf782i4iO9Zf-vG&index=7

![Maintenance panel upper overhead2](https://user-images.githubusercontent.com/121734823/210156365-761b0eed-fbce-4eaf-a7a2-7cb3f759815d.png)

![Maintenance panel upper overhead](https://user-images.githubusercontent.com/121734823/210156215-14bf166a-ac12-4c6c-8356-512c7aa437f4.png)

![Overhead upper](https://user-images.githubusercontent.com/121734823/210156478-77c85701-c7be-4ba9-b1a4-f6406ac79ca6.png)

### Discord Username (optional)

tomprovence#3513

**Comment by frankkopp** [comment]
Asobo modeled it after this:

https://ccntservice.airbus.com/apps/cockpits/a320/
![image](https://user-images.githubusercontent.com/16833201/210169037-74662346-4ca4-4cf5-9635-2cc3c5dbd1ef.png)

There are several such small mistakes Asobo made - we are not planning to fix them. 
But we are working on our own model anyway which will then be correct.

**Comment by tomprovence2** [comment]
Ok, thank you for your answer and your terrific work
Any deadline for your own model ?
Any way to help you other than reporting bugs / requests ? 
Let me know how I can be useful even if I have no programming skills (Testing quality of new features before release for example ?)

**Comment by tomprovence2** [comment]
I would like very much to contribute to this wonderful project even for a small task

**Comment by tracernz** [comment]
This is all covered in https://github.com/flybywiresim/a32nx/issues/1410, https://github.com/flybywiresim/a32nx/issues/575, and https://github.com/flybywiresim/a32nx/issues/29
