### ISSUE TITLE
Wrong labels Overhead CARGO section

### ISSUE THREAD

**Issue by tomprovence2** [flybywiresim/a32nx#7683]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2022-12-07T00:57:56+00:00",
    "ref": "refs/heads/master",
    "sha": "5697964080ec93223b3271ad5ac1ea626959cc49",
    "actor": "tracernz",
    "event_name": "manual",
    "pretty_release_name": "master:56979640"
}
```

### Describe the bug

1) Incorrect label for CARGO VENT, right label is CARGO HEAT
2) Missing buttons in the CARGO HEAT panel
3) Incorrect label in the right part of the CARGO SMOKE panel, FWD instead of AFT

### Expected behavior

Modify incorrect labels
Model FWD ISOL VALVE & HOT AIR Buttons
Model FWD & AFT temperature selector buttons

### Steps to reproduce

Have a look at the lower Overhead

### References (optional)

https://www.smartcockpit.com/aircraft-ressources/A320-Overhead_Panel.html
https://www.youtube.com/watch?v=lua53_GqPfM&list=PL91baicFu7lqeSSbQYchNABZ1YgnHqSpH&index=6
https://www.youtube.com/watch?v=4z3CSuNvHE4&list=PLdOwRGupI0JerxH2yupf782i4iO9Zf-vG&index=31

![Cargo](https://user-images.githubusercontent.com/121734823/210157060-ede5e8e3-47da-4b98-a2e6-4c89f06ac194.png)

![Overhead](https://user-images.githubusercontent.com/121734823/210157063-92dddfd7-05e0-437e-9897-6c4320453076.png)

![Cargo2](https://user-images.githubusercontent.com/121734823/210157080-82ea4a17-8411-454e-a046-15e27bdf97c1.png)

### Discord Username (optional)

tomprovence#3513

**Comment by frankkopp** [comment]
Asobo modelled it after this:

https://ccntservice.airbus.com/apps/cockpits/a320/
![image](https://user-images.githubusercontent.com/16833201/210168641-de15069a-f2a2-46a1-8a9f-59526faf1639.png)

There are several models/variations of this. 
So it is "correct". 
But we are working on our own model anyway which will then likely change a few things.
