### ISSUE TITLE
CTD when checking the batteries in the before start checklist

### ISSUE THREAD

**Issue by ysahukara360** [flybywiresim/a32nx#7690]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2023-01-04T14:43:15+00:00",
    "ref": "refs/heads/master",
    "sha": "07674ec6cff7e2b1b59b83402d1c7f0eb735b6d2",
    "actor": "frankkopp",
    "event_name": "manual",
    "pretty_release_name": "master:07674ec6"
}
```

### Describe the bug

In the before-start checklist when we are supposed to switch the ecam page to 'elec' and turn off the bat1 and bat2 one by one, the sim freezes and crashes to the desktop. This issue only started when I switched to the development version from stable.

### Expected behavior

The sim should work just like the stable version

### Steps to reproduce

switch ecam to elec
turn off bat1 then check ecam
turn on bat1
turn off bat2 then check ecam
turn on bat2

**Comment by Maximilian-Reuter** [comment]
I cannot reproduce that issue on the latest development version. Can you confirm this still happens to you on the latest dev version?

**Comment by frankkopp** [comment]
Can't reproduce either - will close unless until a reliable way to reproduce is described.

Also: 

CTDs are mostly a MSFS sim issue and very hard to analyze. Here a collection of tips:
https://docs.flybywiresim.com/fbw-a32nx/support/reported-issues/#crash-to-desktop-ctd
also use the MSFS Forum:
https://forums.flightsimulator.com/c/bugs-and-issues/ctds/260
