### ISSUE TITLE
[Experimental] Seatbelt sign, runway swtich and a couple other switches does not work

### ISSUE THREAD

**Issue by runningdavid** [flybywiresim/a32nx#7697]
### Aircraft Version

Experimental

### Build info

```json
{
    "built": "2023-01-06T12:06:08+00:00",
    "ref": "refs/heads/experimental",
    "sha": "2f0590e8016d9ff6525930beb21a2d5cfbd93669",
    "actor": "frankkopp",
    "event_name": "manual",
    "pretty_release_name": "experimental:2f0590e8",
    "version": "v0.10.0-exp.2f0590e"
}
```

### Describe the bug

Seatbelt sign and runway switch are not clickable (along with some other random swtiches).

### Expected behavior

They should be clickable.

### Steps to reproduce

1. Load into aircraft
2. Test overhead panel switches

**Comment by Benjozork** [comment]
Cannot reproduce on the exact same build.

I would go through these steps:

https://docs.flybywiresim.com/fbw-a32nx/support/#2-how-to-troubleshoot

**Comment by Benjozork** [comment]
Will reopen if it does turn out to be an issue with the aircraft.

**Comment by runningdavid** [comment]
Maybe it's livery issue, or a settings issue. All my settings are reset during yesterday's sim update for no reason.

**Comment by runningdavid** [comment]
Interesting, didn't work for me even with default livery and control option set to "legacy".

**Comment by runningdavid** [comment]
Ahhh.. Found out the issue is with LVFR A321 FBW compablility mod. Removed it and everything works.

**Comment by Benjozork** [comment]
The installer should have prompted you to remove it. Did you not get any message ?

Also, <https://docs.flybywiresim.com/fbw-a32nx/support/reported-issues/#incompatible-and-problematic-add-onsmods>

**Comment by runningdavid** [comment]
I noticed it when I uninstall then reinstall the A320, but maybe not when I update it.
