### ISSUE TITLE
Sim se congela en el segundo segmento del despegue

### ISSUE THREAD

**Issue by anferbar** [flybywiresim/a32nx#7700]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2022-12-01T22:21:09+00:00",
    "ref": "refs/tags/v0.9.1",
    "sha": "219cccffcf27fc4c757d2ec479c945b82a169d0b",
    "actor": "Saschl",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.9.1"
}
```

### Describe the bug

Con V0.8.2 todo perfecto. Pasado a V0.9.1 desde el principio ha venido dando el mismo error. El despegue bien, configuración limpia y a los dos minutos de vuelo más o menos iniciando el segundo segmento el sim se congela. Si se despega desde la pista sin hacer cold and Dark no ocurre. No pasa con otros aviones. Cuando inicio  de nuevo el sim me sale una indicación de Fs2020 que por error inicie en forma segura. He desinstalado en instalado mil veces quitando todo el contenido de la carpeta de la  Comunidad. He desinstalado Fs2020 y todo sigue igual. Les agradecería que den solución  a este error.      

### Expected behavior

Tengo confianza en que lo solucionaran.

### Steps to reproduce

Al inicia por primera vez el vuelo con stable/V0.9.1

### Additional info (optional)

Con stable/V0.8.2  no ocurría 

### Discord Username (optional)

anferbar

**Comment by frankkopp** [comment]
Please re-open a new issue in English. This will be closed.

**Comment by anferbar** [comment]
Doy por cerrado #7700  Gracias
