### ISSUE TITLE
Some Cabin Crew Announcements for play twice

### ISSUE THREAD

**Issue by frankkopp** [flybywiresim/a32nx#7701]
### Aircraft Version

Development

### Build info

```json
Dev/Exp
```

### Describe the bug

The cabin crew announcement for "doors in flight" and "safety briefing" play twice if the Beacon light is on (the actual light) and the Strobe light is turned on. As these light are synchronized the algorithm to synchronize them sets the beacon light shortly to off again to bring it in sync with the strobe. This causes the announcements to be played again. 

### Expected behavior

Cabin announcements should only play once per flight. 

### Steps to reproduce

Turn on aircraft from cold&dark - BAT1+2 and Ext.PWR
Set beacon light switch to on (light is on because ac is powered)
Await announcement.
Set Strobe LT switch to on - announcement will play again.
If you watch the LIGHT BEACON ON var you can see it shortly flips off and on after switching Strobe on).

### Discord Username (optional)

Cdr_Maverick#6475

**Comment by MStallen** [comment]
I encountered the same problem
