### ISSUE TITLE
After Update to dev.dc81f48 strange noise starting

### ISSUE THREAD

**Issue by Adi-18** [flybywiresim/a32nx#7718]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2023-01-14T13:06:58+00:00",
    "ref": "refs/heads/master",
    "sha": "dc81f48c7ec980a4cf2f4c6d9f17c3c117b3f18b",
    "actor": "frankkopp",
    "event_name": "manual",
    "pretty_release_name": "master:dc81f48c",
    "version": "v0.10.0-dev.dc81f48"
}
```

### Describe the bug

After update, suddenly, a strange noise starts. First on the ground Then several times during the flight.
See here: https://youtu.be/kSN8beAU1nI

### Expected behavior

No noise or clear explanation?

### Steps to reproduce

I don't know.
See video

**Comment by hotshotp** [comment]
That seems like quite the sound bug... Do you by any chance have fsrealistic?

**Comment by Adi-18** [comment]
Thank you

> That seems like quite the sound bug... Do you by any chance have fsrealistic?
No I don't.

**Comment by hotshotp** [comment]
> Thank you
> 
> > That seems like quite the sound bug... Do you by any chance have fsrealistic?
> 
> No I don't.

Is this big reproduceable at all? This is the first time I've ever seen something like this

**Comment by Adi-18** [comment]
Since Update two of two times. First time while preparing flight. Second time while flying -> video

**Comment by Adi-18** [comment]
Since last update no more problem like this.
