### ISSUE TITLE
[BUG] APU Bleed and start have to be separate after landing

### ISSUE THREAD

**Issue by CoffeePanda0** [flybywiresim/a32nx#772]
**Mod Version**

Latest master branch

**Describe the bug**

When you land, if you "APU START" and "APU MASTER SWITCH" at the same time instead of waiting for the APU Flap to open then the APU flap does not open. If you start them separately and wait for the flap to open then start then it works fine

**To Reproduce**

1. Do a full flight with APU off in flight
2. Land and press both APU Start and master at the same time
3. Watch and the APU flap does not open

**Expected behavior**

The APU should open the flap and wait, then start the APU

**Actual behavior**

The flap will not open at all if master switch and APU start are turned on at the same time after a full flight

**References**

Discord username (if different from GitHub): obama#6262

**Comment by NathanInnes** [comment]
Do you have screen refresh rate set to low?

**Comment by CoffeePanda0** [comment]
> Do you have screen refresh rate set to low?

Nope but I’ve got them on medium. I had this issue with the old FPS fix mod on low as well

**Comment by Ares1378** [comment]
The APU master switch needs to be pressed prior to starting the APU. If you are pressing the APU ON pb prior to the Master switch the APU will not start. The APU master switch does the following - ECB self test, Fuel Isolation Valve opens, Fuel Pump turns on, Flap opens, and the ECAM page appears.

**Comment by Ares1378** [comment]
So I have replicated the issue. If you press the START pb the APU should start automatically once the flap is opened. 
How I replicated
1) Loaded in cold and dark
2) BAT 1 and 2 ON
3) EXT PWR on 
4) APU MASTER pb ON
5) Immediately pressed the APU START pb 

The APU would not start. 

What I had to do to resolve the issue as a work around:
1) Turned APU MASTER pb OFF
2) Turned APU MASTER pb ON
3) Waited for flap to open
4) APU START pb ON
APU starts.

The correct function should start the APU even if you press the APU START pb prior to the flap being opened. Once the FLAP is open the APU should start. 
![image](https://user-images.githubusercontent.com/70821584/93729412-f784fa80-fb89-11ea-97ad-af40d0a88bf2.png)

**Comment by NathanInnes** [comment]
Has this issue been solved for you with the latest master?

**Comment by CoffeePanda0** [comment]
Ah yes sorry
