### ISSUE TITLE
Setting HVAR on ECAM to select page no longer works

### ISSUE THREAD

**Issue by Muyz** [flybywiresim/a32nx#7720]
### Aircraft Version

Experimental

### Build info

```json
{
    "built": "2023-01-14T15:47:05+00:00",
    "ref": "refs/heads/experimental",
    "sha": "3ee2277a37ae77db20630f7441fb19d06256e09c",
    "actor": "Saschl",
    "event_name": "manual",
    "pretty_release_name": "experimental:3ee2277a",
    "version": "v0.10.0-exp.3ee2277"
}
```

### Describe the bug

Selecting an ECAM page used to work by setting the proper HVAR, e.g. H:A320_Neo_EICAS_2_ECAM_CHANGE_PAGE_ENG for ENG. While this does still work on the default A320neo, this no longer works on the FBW.

### Expected behavior

Set HVAR H:A320_Neo_EICAS_2_ECAM_CHANGE_PAGE_ENG should select ENG on ECAM. Instead, nothing happens.

### Steps to reproduce

1. Start FSUIPC 7.3.16 with FBW A32NX loaded in MSFS
2. From menus, select Add-ons -> WASM -> Activate HVAR
3. Select HVAR H:A320_Neo_EICAS_2_ECAM_CHANGE_PAGE_ENG and press "Activate"
4. Nothing happens

### Additional info (optional)

This was working before. My guess is that it broke between 5th December, 2022 and January 15th, 2023. Sorry, but I cannot be more accurate.

### Discord Username (optional)

Muyz#0866

**Comment by frankkopp** [comment]
Indeed this has changed - docs are not yet update. 

See this video how it works now:
https://user-images.githubusercontent.com/16833201/213013845-927fb52e-cd58-49cc-8d6c-b93942d12166.mp4

I will close this - this not a a32nx issue but a docs issue

**Comment by Muyz** [comment]
Thanks
