### ISSUE TITLE
[REQUEST] Tail/Logo light behaviour

### ISSUE THREAD

**Issue by ErikNL80** [flybywiresim/a32nx#773]
**Is your feature request related to a problem? Please describe.**

Currently the tail/logo light is on when the nav lights are on, also the cabin lights. This is not correct, since the tail/logo light is switched off automaticallly when the flaps are retraced and comes on automatically when the gear is lowered...

**Describe the feature you'd like to see implemented**

I would like to see that the tail/logo light is extinguished when flaps are retracted to 0 and the tail/logo light is on when the gear goes down.

**References**

http://www.smartcockpit.com/docs/A320-Lights.pdf

**Additional context**

Discord username (if different from GitHub):

**Comment by Ares1378** [comment]
You are partially correct on this issue. The logo lights should only stay illuminated when the main landing gear is compressed, OR depending on the aircraft config, when flaps are extended (at least 15 degrees on some aircraft) or slats extended. The cabin lights are controlled via the FAP panel in the cabin. The cockpit has no control over the cabin lighting, this is controlled via the FAP. 
![image](https://user-images.githubusercontent.com/70821584/93728527-ecc86680-fb85-11ea-9ad6-ec506de3153e.png)

This item has been escalated to the dev team to add. 

Thank you,

Ares
