### ISSUE TITLE
Switch "Prepare for Take Off" announcement from TCAS to Strobes

### ISSUE THREAD

**Issue by lirondco** [flybywiresim/a32nx#7733]
### Aircraft Version

Experimental

### Description

At some airports on VATSIM, TA/RA is required on taxiways so switching TCAS to that will trigger the "prepare for take off" announcement even when you're far from ready. However, strobes are turned on when entering a runway, so it makes more sense to trigger it from there. 

I can work on this one if people agree on the change.

### Discord Username (optional)

liron_#2849

**Comment by Eearslya** [comment]
I'm not sure this is a good solution either, as strobes are required when entering or crossing ANY runway, not just the one you're going to be taking off from.

**Comment by PecorinoDev** [comment]
How about triggering the announcement when the nose landing gear EXT LT change from "taxi" to "T.O."?

**Comment by lirondco** [comment]
> 

not sure about that, as that light is also used for landing / approach at gear down.

**Comment by Eearslya** [comment]
> not sure about that, as that light is also used for landing / approach at gear down.

I don't think that would be an issue, since we can easily check if the wheels are on the ground.

**Comment by PecorinoDev** [comment]
I actually never turn off the Nose light after takeoff as they're automatically turned off when the gear has retracted, so technically it'll only trigger the announcement once before takeoff.

I can't think of anything else that'll trigger once before takeoff (other than switching TCAS to TA/RA).

**Comment by AceM110** [comment]
I’d suggest using the Taxi Light switch to trigger the announcement once it is toggled to the T.O detent. Otherwise the current method works okay.

**Comment by Maximilian-Reuter** [comment]
https://github.com/flybywiresim/a32nx/pull/7402
There was a big discussion of this already many times and the current choice is the result. 

There is no solution that is perfect as with all automated announcements. 

According to my understanding VATSIM requires you to squawk mode C on the ground in certain airports. Which seems to not have anything to do with the TCAS switch. It should be enough to set the top left switch to ON from AUTO or OFF and have the ALT RPTG to ON

For reference: https://docs.flybywiresim.com/pilots-corner/assets/a32nx-briefing/pedestal/ATC-TCAS.jpg

**Comment by tracernz** [comment]
> According to this: #6697 vPilot should see even the AUTO setting as Mode C. So I really don't see why VATSIM could want you to set the TCAS switch to anything since that really doesn't control that part. As such there does not seem to be any issue beyond maybe VATSIM controllers being confused.

Yeah, VATSIM don't care about the difference between mode S and mode C because they don't have the RF limitations of real life, so they treat both as "mode C".

**Comment by hotshotp** [comment]
We discussed with several pilots and changed this trigger probably over 5 times at this point. By SOP, most if not all airlines switch the transponder as their before takeoff flow/checks, and that's why this is the most consistent option.
