### ISSUE TITLE
[BUG] ILS runway-change confusion

### ISSUE THREAD

**Issue by Pixel1191** [flybywiresim/a32nx#774]
**Mod Version**
Current master.

**Describe the bug**
Don't know if this is "vanilla" behavior or not. The plane seems to have some issues picking up the correct ILS when changing arrival runways on the same ILS frequency.

I noticed it at Heathrow. Had 27R in the flight plan, which autofilled the RAD/NAV and ATC switched me to 09L when I got there, which is on the same ILS frequency (110.30) I changed the runway on the flightplan and it correctly switched to 09L on RAD/NAV.

However, the autopilot was still working off the ILS for 27R. The PFD was showing IRR and the ND showed ILS 27R. Putting the frequency into the MCDU again did not help, turning the ILS off and on did not help, either. Only deleting the frequency completely helped, for some reason. Leaving 09L in the RAD/NAV, with the frequency blank, made the ILS switch to the correct one, the PFD was showing IAA and the ND said ILS 09L. The indicators were correct and the approach worked properly.

Or maybe my assumption as to the expected behavior is incorrect? Not terribly experienced on the Airbus.

**To Reproduce**
1. Enter arrival runway into the MCDU flight plan
2. turn on the ILS when close to the airport
3. Check that the PFD and ND are showing the ILS data
4. Change the arrival runway in the MCDU to the one going in the opposite direction that shares the same frequency (i.e. 09L and 27R at Heathrow)
5. Check if PFD and ND are still showing the ILS for the old runway
6. Go into RAD/NAV and clear out the ILS frequency
7. Check PFD and ND again, the correct ILS will be shown

**Expected behavior**
Expected the system to switch to the correct ILS after changing the runway in the MCDU, even if they're on the same frequency. At least expected it to take the correct one after entering the frequency again, manually, with the new runway selected.

**Actual behavior**
The system stubbornly stuck with the ILS of the previously selected runway, until the frequency was deleted from RAD/NAV without entering a new one.

**References**
Did, unfortunately, not take a screenshot, as I was suddenly more busy than expected landing the plane....

**Additional context**
Don't know if it's maybe a Heathrow problem? Didn't yet have the time to try again, somewhere else. Altho the setup with shared frequencies doesn't seem that uncommon.

**Comment by Ares1378** [comment]
I can confirm this issue, and has been replicated. Refer to Issue#56. I have already submitted an issue for this. 

Thanks,

Ares

**Comment by tracernz** [comment]
This should be fixed in #4973. Please test and re-open if not.
