### ISSUE TITLE
APU Fehler

### ISSUE THREAD

**Issue by broeselpilot** [flybywiresim/a32nx#7750]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2023-01-08T23:16:53+00:00",
    "ref": "HEAD",
    "sha": "81a8ee3a2e03a24da13cc0bcc4cf3a7d51f188a6",
    "actor": "Saschl <sascharudolf46@gmail.com>",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.9.1"
}
```

### Describe the bug

Die APU startet nicht!

### Expected behavior

Die APU müßte nach einiger Zeit Hochlaufen, es kommt eine Fehlermeldung!

### Steps to reproduce

FBW A320 Version stable 0.9.1
Nach dem Einschalten der Batterien bei Cold and dark, Start der APU, läuft nicht hoch.

### References (optional)

[Fehler nach APU-Start.pdf](https://github.com/flybywiresim/a32nx/files/10535036/Fehler.nach.APU-Start.pdf)

**Comment by BlueberryKing** [comment]
Hi, es sieht so aus als hättest du kein Treibstoff an Board. Du kannst den Flieger über das Tablet tanken: https://docs.flybywiresim.com/fbw-a32nx/feature-guides/loading-fuel-weight/#loading-fuel-and-weight

Hi, it looks like you have no fuel on board. You can refuel the plane via the tablet:
https://docs.flybywiresim.com/fbw-a32nx/feature-guides/loading-fuel-weight/#loading-fuel-and-weight

**Comment by broeselpilot** [comment]
Hallo, danke für den Hinweis, ich habe das Flugzeug bedankt über das flypad und alles hat wieder funktioniert.

Die APU ist hochgelaufen und hat Strom geliefert, alles Gut.

 

Danke nochmal für den entscheidenden Hinweis

Grüße broeselpilot

 

Von: BBK ***@***.***> 
Gesendet: Montag, 30. Januar 2023 11:58
An: flybywiresim/a32nx ***@***.***>
Cc: broeselpilot ***@***.***>; Author ***@***.***>
Betreff: Re: [flybywiresim/a32nx] APU Fehler (Issue #7750)

 

Hi, es sieht so aus als hättest du kein Treibstoff an Board. Du kannst den Flieger über das Tablet tanken: https://docs.flybywiresim.com/fbw-a32nx/feature-guides/loading-fuel-weight/#loading-fuel-and-weight

Hi, it looks like you have no fuel on board. You can refuel the plane via the tablet:
https://docs.flybywiresim.com/fbw-a32nx/feature-guides/loading-fuel-weight/#loading-fuel-and-weight
