### ISSUE TITLE
Data Entry into Hardware MCDU Anomalies

### ISSUE THREAD

**Issue by DFWFlyDC9** [flybywiresim/a32nx#7752]
### Aircraft Version

Development

### Build info

```json
"built": "2023-01-28T16:44:36+00:00",
    "ref": "refs/heads/master",
    "sha": "9eb9672fd715643c450c181f0d3e94f5cb55b9ef",
    "actor": "frankkopp",
    "event_name": "manual",
    "pretty_release_name": "master:9eb9672f",
    "version": "v0.10.0-dev.9eb9672"
}
```

### Describe the bug

While entering data into the FDS ENET A320 MCDU anomalies are occurring that I am not seeing with the remote MCDU or the MCDU in-sim.

Examples:
Entering any FL on INIT A page such as 220 produces 022 in MCDU. Remote and in-sim MCDU work normally.
Entering any ZFW/ZFWCG on INIT B produces "Entry out of Range". Remote and in-sim MCDU work normally.
Entering any combination of Flap Settings/THS on PERF Takeoff Page produce "Format Error". Remote and in-sim MCDU work normally.
Entering wind data on APPR Page produces "Format Error". Remote and in-sim MCDU work normally.

### Expected behavior

Proper data entry was expected via the MCDU as Device Manager Interface is using the proper MCDU sim commands for the A320 Neo MCDU and remote and in-sim MCDU work normally.

### Steps to reproduce

Attach FDS A320 MCDU via ethernet
Run Device Interface Manager and point to FDS MCDU ip Address
Test data entry via hardware MCDU

### References (optional)

![MCDU](https://user-images.githubusercontent.com/121818898/215547791-e79a1ea4-f597-4d31-ac56-043a41951cf9.jpg)

### Discord Username (optional)

mmajdeski #3427

**Comment by tracernz** [comment]
Unfortunately we are not familiar with how the FDS software works and to the best of my knowledge none of our team has FDS hardware to do any testing. You will have to seek support from FDS.
