### ISSUE TITLE
PERF APPR page transition

### ISSUE THREAD

**Issue by mutti82** [flybywiresim/a32nx#7759]
### Aircraft Version

Experimental

### Description

FMS PERF menu, APPR phase... should have TRANS FL, not TRANS ALT. 
Screenshot from real A20N attached.

### References (optional)

![fms](https://user-images.githubusercontent.com/104828306/216432409-bf06a891-2529-44a2-9364-1809d3f9b844.jpg)

### Discord Username (optional)

Mika Pennanen#5103

**Comment by tracernz** [comment]
The attached picture is a Thales MCDU, and also a Thales FMGC, as Honeywell does not have TRANS FL on this page.
Honeywell H3 for reference:
![image](https://user-images.githubusercontent.com/9995998/216436448-ad7e4f8c-79ca-4039-bb4f-d85783967149.png)

**Comment by mutti82** [comment]
Ok. Well have to say that is confusing when need to define TRANS FL when descending but has to input it as feet. But as I'm not a real world pilot... copy this.

**Comment by tracernz** [comment]
Yeah, I wish Honeywell would change it, but unless that happens we are stuck with "TRANS ALT".

**Comment by mutti82** [comment]
I can't even understand why Honeywell wants it like that... as it is against all terminology which are taught in at least this side of Atlantic. :)
