### ISSUE TITLE
Incorrect Fuel Values [BUG]

### ISSUE THREAD

**Issue by kayfabe9** [flybywiresim/a32nx#776]
**Mod Version**

Latest Master

**Describe the bug**

I load the flight with 3000kg of fuel but when the flight loads it has over 10000 kg fuel.

**To Reproduce**

1. Set Manual Fuel in Weight & Balance
2. Load flight at runway
3. Check fuel quantity

**Expected behavior**

Should load the fuel according to the value provided in the Weight & balance section in flight planner.

**Actual behavior**

Flight always loads with around 10500 kg of fuel.

**References**

**Additional context**

Discord username (if different from GitHub):

**Comment by ferics** [comment]
Been wondering about this as well. I also notice that the CG never changes from 21.6% even when I load more/less fuel/payload :( Seems like fuel is not being factored in within the sim which is one of the crucial part.

**Comment by UncleClapton** [comment]
It seems like CG is affected by fuel to a limited degree, but it's almost like all of the fuel weight points are along the center of the plane. It's so weird.

As for the issue reported, it seems like the fuel density differs between flight planner and in-game. 6.0 lb/g in the menu, 6.7 lb/g in game. This might be the cause. Unfortunately this might not be something that we can fix.

**Comment by ferics** [comment]
Understandable, but as per prior to the patch (I think) we could at least enter the trip fuel and CG. Now it's just a static 21.6% (haven't tried removing the mod to see if it happens to vanilla too)

**Comment by kayfabe9** [comment]
I don't have this issue with the 2 day old master build. This just happened 10 hours back, haven't tried it after that.
