### ISSUE TITLE
Basic Controls/Switches still lacking in API

### ISSUE THREAD

**Issue by Fragtality** [flybywiresim/a32nx#7773]
### Aircraft Version

Development

### Description

Even the most basic Switches are still lacking in the API - Stuff like Interior and Exterior Lights for Example.
Please add them either as L-Var (which toggles the Light and the Switch) or as separate Up/Down Commands with a Variable to read the true Status.

**Comment by Fragtality** [comment]
Sure (as well as a320-simvars.md and a320-events.md).

You don't find that lacking?!

**Comment by Saschl** [comment]
Could you maybe list some examples of missing switches?

**Comment by Fragtality** [comment]
It is not about missing Switches - it is about missing functionality/controllability in the API for the already existing.

I mean do you honestly look at this external/internal Light Table and say "yep, thats perfect, nothing to do here" ?

**Comment by frankkopp** [comment]
This all works since months for many users and cockpit builders. 
Unless you come up with a specific issue where you can't accomplish something with the current API I will close this. 
And please do show some more respect - in the end we all do this for free in our free time.
Btw. why do you not open a PR with the suggested improvements?

**Comment by Fragtality** [comment]
Sorry if it was perceived as disrespectful, it surely was not meant that way. I was just wondered that we look at the same Table and the perception of it being so different.
I also know how time consuming it is to provide something for free in the private/free time (although not that complex & big!). The Reason I'm struggeling is about building/improving something (a StreamDeck Profile) mainly for others.

Then some Examples:
- OVHD INTEG Lt / LIGHT POTENTIOMETER:86 => only readable. write does not change switch or light
- DOME / TOGGLE_CABIN_LIGHTS => does not do anything
- DOME / LIGHT POTENTIOMETER:7 => only readable. write does not change knob or light
- EMER EXIT => No Indication for "Off" Warning (next to the Switch)
- STROBE / LIGHTING_STROBE_0 => only readable. write does change switch but not the light
- STROBE / the Rest => can not control a 3-State Switch
- NAV & LOGO => does need two inputs for one Switch
- NOSE / LAND => Working but just unneccessary and breaks compatibility

On other Planes, e.g. FSL or Fenix, this is either different Events in conjunction with a L-Var or it just one L-Var for both read & set. 

Another Reason I'm so wondered/puzzled: I can achieve more Complex Things way more easier (e.g. the whole FCU or the Brake Pressure Gauges) but it is a struggle to manipulate the Lights of the Aircraft.
It would just be nice if the API could be improved in the long run in terms of useability and controllability.

**Comment by Fragtality** [comment]
Sorry, no Time for a PR - I'll focus on the other free Stuff I'm sharing 😉
