### ISSUE TITLE
A32NX WINDOW OPEN AND CLOSE, CLOSE N1 LIMIT, A380X

### ISSUE THREAD

**Issue by BATUHANN51** [flybywiresim/a32nx#7775]
### Aircraft Version

Stable

### Description

Can you make the window open and close? How can I close the N1 limitation of engines? And I want to use A380X When it was going to release and can you sand experimental versionn of it. Thanks

**Comment by StenAfMARS** [comment]
The window can not be opened or closed with the current 3D model of the A32NX.  
  
You can't.  
  
There is no set release date for the A380X project and no you can not have an experimental version of the aircraft. You will just have to wait like everybody else I'm afraid.

**Comment by frankkopp** [comment]
I will close this as this is not a serious or constructive issue. 
Point 1 has been answered. 
Point 2 come to our Discord to clarify your question.
Point 3 has no place on the A32NX Issue list.
