### ISSUE TITLE
A32NX boarding completed announce not playing anymore in experimental version

### ISSUE THREAD

**Issue by Jovzin** [flybywiresim/a32nx#7778]
### Aircraft Version

Experimental

### Build info

```json
{
    "built": "2023-02-05T05:49:38+00:00",
    "ref": "refs/heads/experimental",
    "sha": "4d5c4f9f3f448a40fa35484322d3b6e70748eb67",
    "actor": "tracernz",
    "event_name": "manual",
    "pretty_release_name": "experimental:4d5c4f9f",
    "version": "v0.10.0-exp.4d5c4f9"
}
```

### Describe the bug

The stewardess announce "Boarding completed"  is not playing anymore in new experimental version.

I am sure I was hearing this in previous experimental version  after all passengers boarded.  It was quite funny voice  so I am sure I know it was playing. The previous experimental build was :  "version": "v0.10.0-exp.8cc2839"  

### Expected behavior

There should be a nice lady voice calling : Boarding completed, after all passengers are boarded. 

### Steps to reproduce

Turn on MSFS2020 and start flight in any airport
2/ Import simbrief flight plan to EFB and click on Ground/Payload tab.  Click  on import from simbrief for the passengers and baggage. 
3/ Click in GSX menu  to Start Boarding.   Wait till the boarding is complete.
4/ No announce of "Boarding completed" is playing.  Only the one announce from GSX addon.

**Comment by Jovzin** [comment]
One more thing.  
Somehow I think it could be issue of the GSX sound taking priority over Fly by Wire sounds.  Because when I start boarding I do not hear the boarding music at all. Only the GSX sound of people boarding and saying hello etc etc.  
Will try without GSX enabled today if the sound and boarding music will work.

But it is interesting that other announcements and sounds I can hear all of them. Like captain speaking , or security briefing etc. 
Just the boarding sound and Boarding Completed sound is somehow not playing.

**Comment by Sleinmaster** [comment]
The boarding sounds got deactivated if the gsx boarding integration is active to not have the sounds from the plane and gsx play over each other. The a32nx we can control, the gsx sounds we can't.

**Comment by Yellow118** [comment]
I like the sound of both A32NX and GSX, so I do not enable GSX integration and play both sounds.
I would be happy to have an option to play the A32NX sound even with GSX Integration enabled, since the boarding sound is completely comfortable when played at the same time, and the boarding completion announcement and music are elements that GSX does not have.

**Comment by Maximilian-Reuter** [comment]
> Ok so yeah I tested today closed the coautl.exe program and Boarding music was playing and even heard that lady saying boarding completed :) So yeah pitty GSX is taking over the sound during boarding.

As this is expected and documented behaviour this is definitely not a bug. If anything this is a request to be able to enable the announcement sounds in connection with GSX. 

Might want to change the tags
