### ISSUE TITLE
[BUG] Radio displays remain 888.888 after ANN LT TEST

### ISSUE THREAD

**Issue by stevex77** [flybywiresim/a32nx#778]
**Mod Version**

master

**Describe the bug**

Both RADIO displays remain all 888.888 after ANN LT TEST

**To Reproduce**

1. Switch on BATT or EXT power
2. Perform an ANN LTT TEST and switch back to BRT or DIM
3. Check RADIO displays

**Expected behavior**

After ANN LT TEST displays should show previous values

**Actual behavior**

Test 888.888 values remain

**References**

Maybe connected to #746

**Additional context**

n/a

Discord username (if different from GitHub):
n/a
![A320NX_RADIOS](https://user-images.githubusercontent.com/51388935/93723653-c2d06d80-fba0-11ea-8b85-04d00062442a.jpg)

**Comment by Ares1378** [comment]
This item has been replicated exactly how the OP stated. attached is the evidence I found.
 
![image](https://user-images.githubusercontent.com/70821584/93728677-8c85f480-fb86-11ea-8899-593a8b65e59b.png)

**Comment by AdenFlorian** [comment]
my bad, will fix
