### ISSUE TITLE
Realistic GPU

### ISSUE THREAD

**Issue by TGNDevans1** [flybywiresim/a32nx#7784]
### Aircraft Version

Experimental

### Description

Not fully sure if this is possible, after having a look through the SDK myself and playing with SimConnect and SimVarWatcher but it would be nice if the External Power wouldn't be available unless the GPU is connected.

**Comment by tracernz** [comment]
There are two problems with that:
- MSFS doesn't simulate ext power from the gate, only GPU
- Many airports do not have GPU available that should have either GPU or gate power
