### ISSUE TITLE
Text on displays dissapear on the pedestal (already reported in #717) [BUG]

### ISSUE THREAD

**Issue by sharksfan166269** [flybywiresim/a32nx#780]
**Mod Version**

Master

**Describe the bug**

When I position my camera close to the pedestal, the text on the radio panel, transponder panel, and rudder trim disappear. This only happens at a certain distance, so at the F/O seat, the text on those displays appear fine. This does not seem to happen to any other part of the flight deck.

**To Reproduce**

1. Power on the plane and move the camera close to the pedestal
2. Make sure the screens are on and visible
3. Move the camera close to the displays on the pedestal

**Expected behavior**

I'd expect it to not disappear

**Actual behavior**

The text on the displays on the radio panel, transponder and rudder trim disappear. There's no back light on these displays, so they just appear off.

**References**

https://imgur.com/a/TeEbAHj
You can see, once the camera moves closer, the displays disappear in both day and night lighting situations

**Additional context**

Discord username (if different from GitHub):

**Comment by stevex77** [comment]
Already reported as vanilla/asobo bug. See https://github.com/flybywiresim/a32nx/issues/717

**Comment by sharksfan166269** [comment]
> 
> 
> Already reported as vanilla/asobo bug. See #717

Oh okay, my bad. I'd never seen it before today so I thought I'd report it just in case

**Comment by stevex77** [comment]
No problem, thanks.

**Comment by Ares1378** [comment]
This item has been replicated. Attached is the evidence that was found. 
![image](https://user-images.githubusercontent.com/70821584/93728808-4d0bd800-fb87-11ea-8d18-2e4f02104be4.png)

Thank you,

Ares

**Comment by MattPaxtonBel** [comment]
In this video at timecode : 21:40
https://www.youtube.com/watch?v=hJU4n1IDOLo

you can observe this bug. 

Unknown Version of the A32NX

**Comment by AdenFlorian** [comment]
closing as it is a duplicate
