### ISSUE TITLE
cargo door rivets bug 

### ISSUE THREAD

**Issue by drunkpupper25** [flybywiresim/a32nx#7805]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2022-12-01T22:21:09+00:00",
    "ref": "refs/tags/v0.9.1",
    "sha": "219cccffcf27fc4c757d2ec479c945b82a169d0b",
    "actor": "Saschl",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.9.1"
}
```

### Describe the bug

the rivet layer of the cargo door rotates 8 nodes more than the door itself, it also doesn't use the same rotation sequence. 

### Expected behavior

i expect that the rivets rotate with the door

### Steps to reproduce

1. open the cargo door
2. watch closely in free cam

### References (optional)

https://user-images.githubusercontent.com/125760342/219881580-ca888afc-042c-462b-ba8c-34e2df1b30ad.mp4

### Discord Username (optional)

drunk pupper25#5458

**Comment by drunkpupper25** [comment]
fixed it myself, 
do teh following in the model XML
replace 
`            <UseTemplate Name="ASOBO_DOOR_InteractivePoint_Template">
                <ID>5</ID>
                <ANIM_NAME>Ribbons_Cargo-Anim</ANIM_NAME>
            </UseTemplate>`
  with
`            <UseTemplate Name="ASOBO_GT_Anim">
                <ANIM_NAME>Ribbons_Cargo-Anim</ANIM_NAME>
                <ANIM_CODE>(L:A32NX_FWD_DOOR_CARGO_POSITION)</ANIM_CODE>
                <ANIM_LENGTH>100</ANIM_LENGTH>
            </UseTemplate>`

**Comment by Gurgel100** [comment]
Would you mind making a PR so that it gets fixed?

**Comment by drunkpupper25** [comment]
> Would you mind making a PR so that it gets fixed?

Sorry a what? I'm just a livery maker not a dev
