### ISSUE TITLE
SRS and managed speed modes not working correctly.[BUG]

### ISSUE THREAD

**Issue by Ares1378** [flybywiresim/a32nx#782]
**Mod Version**
Master

**Describe the bug**

Aircraft should maintain v2+10 in SRS mode until Thrust reduction attitude once out of SRS mode and the thrust levers set to the CL detent the aircraft will not accelerate past S speed for min slat retraction even with  MAN TOGA thrust. The airspeed will settle and maintain 160 knots give or take. Also, The managed speed bug should not be at S speed once out of SRS, it should be set to 250 knots if below 10 or set managed cruise climb speed. The only way to make the aircraft accelerate is to retract the slats which almost triggers A. Floor being as it is to low of an airspeed to select FLAPS 0. Once selecting FLAPS 0 the aircraft will then accelerate and maintain an airspeed 10-15 knots lower than what is managed. I.E 250 knots or 320 knots above 10k.

**To Reproduce**

1. takeoff 
2.
3.

**Expected behavior**

The following video is what it should look like. 
https://www.youtube.com/watch?reload=9&v=ECV3IBkzZLc

**Actual behavior**

**References**

**Additional context**

Discord username (if different from GitHub):
Please message me on discord if you have any questions and I can better explain this issue Ares#3394

**Comment by Venorcis** [comment]
Already reported in #760, #565, and maybe more.

**Comment by lousybyte** [comment]
Related #210, #855
