### ISSUE TITLE
Change to 8,33 kHz with the AIRAC Update 2302

### ISSUE THREAD

**Issue by PaulaBras** [flybywiresim/a32nx#7824]
### Aircraft Version

Stable

### Description

The value in the following file should be changed, because tomorrow with the airac update 8,33 will be in EDDH applied. My request is to make the change simpler, to enable 8,33 by default to enable a smooth change to it, when it will be VATEUD wide used.

```
fbw-a32nx/src/systems/instruments/src/RMP/Components/StandbyFrequency.tsx:        
spacing = usePersistentProperty('RMP_VHF_SPACING_25KHZ', '0')[0] === '0' ? 8.33 : 25;
```

**Comment by tracernz** [comment]
I don't quite understand what you're saying. The default spacing is 8.33 kHz but you can change to 25 kHz only in the settings pages on the flyPad. See "RMP VHF Spacing" https://docs.flybywiresim.com/fbw-a32nx/feature-guides/flypados3/settings/#aircraft-options-pin-programs

**Comment by PaulaBras** [comment]
Yeah, all fine. It wasn't the default. That could confuse pilots. sadly, this project got killed by the BoG.
