### ISSUE TITLE
N1 "10" scale indication digits overlapping with red limit

### ISSUE THREAD

**Issue by BravoMike99** [flybywiresim/a32nx#7849]
### Aircraft Version

Experimental

### Build info

```json
{
    "built": "2023-03-01T07:23:07+00:00",
    "ref": "refs/heads/experimental",
    "sha": "27038a43eae9efb860dfffb94582c41c74cb478b",
    "actor": "Saschl",
    "event_name": "manual",
    "pretty_release_name": "experimental:27038a43",
    "version": "v0.10.0-exp.27038a4"
}
```

### Describe the bug

As visible, the "10" indication on the N1 gauge seems to be overlapping with the N1 limit
![PopUp](https://user-images.githubusercontent.com/119708186/222960017-b4fc21a7-6854-4929-8f53-644a2e1a20ad.PNG)
![N1Digits](https://user-images.githubusercontent.com/119708186/222960029-54d3de0b-3ff4-4177-a77b-35b95f906bdc.PNG)

### Expected behavior

"10" indication should be located a bit more towards the left side to prevent the overlap, just like how it was on previous versions.

### Steps to reproduce

N/A

### References (optional)

(from #7251 )
![image](https://user-images.githubusercontent.com/119708186/222960261-b0853416-d9a9-46e0-b484-b50f97bcfc8e.png)

### Discord Username (optional)

Bruno_pt99#5802

**Comment by tracernz** [comment]
Confirmed on my side too, good spot.
