### ISSUE TITLE
[BUG] ENG 1 shuts down during taxi to the runway

### ISSUE THREAD

**Issue by AkaiTheOrca** [flybywiresim/a32nx#785]
**Mod Version**
 Master 0.2.0 with the latest github folders

**Describe the bug**
 During taxi to the runway, ENG 1 fails and shuts down, and there is no way to restart it. I have tried to reload the sim, redownload the A32NX file, and try other things in the sim, but it happens every time now and I'm not sure what's going on. I haven't had this issue before.

**To Reproduce**

1. Started the aircraft from cold and dark and began to taxi to the runway
2. As soon as the throttles were advanced incrementally during taxi (after roughly 5 minutes) engine #1 failed
3. Cannot restart engine 1

**Expected behavior**

**Actual behavior**

**References**

![Capture28](https://user-images.githubusercontent.com/71623548/93734173-0a4cfe80-fb8d-11ea-87ab-c45c713029df.PNG)
![Capture29](https://user-images.githubusercontent.com/71623548/93734194-20f35580-fb8d-11ea-95c0-b27f7be47be8.PNG)

**Additional context**

Discord username (if different from GitHub): AkaiTheOrca#1925

**Comment by Benjozork** [comment]
> Master 0.2.0 with the latest github folders 

`master` and `0.2.0` and different things.

To use the `master` files you need to download the mod using this link: https://github.com/flybywiresim/a32nx/archive/master.zip

0.2.0 is an outdated version.

Make sure you are actually downloading master, which is not 0.2.0.

**Comment by wpine215** [comment]
Also make sure you're turning all your fuel pumps off... there should be no OFF indicators on the overhead.

**Comment by BinaryAscension** [comment]
This is a known bug of the GAME, not the mod, the master branch currently has a fix for it until MSFS fix it themselves.

**Comment by AdenFlorian** [comment]
this is fixed in master
