### ISSUE TITLE
Flaps not in T.O. config after landing

### ISSUE THREAD

**Issue by MStallen** [flybywiresim/a32nx#7850]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2023-03-04T16:44:07+00:00",
    "ref": "refs/heads/master",
    "sha": "4a38c4328bcbeb62b8d91ae5ce7f2d6560a0ab11",
    "actor": "tracernz",
    "event_name": "manual",
    "pretty_release_name": "master:4a38c432",
    "version": "v0.10.0-dev.4a38c43"
}
```

### Describe the bug

After landing I get the message Flaps not in T.O. config. The only way to get rid of it by setting the flaps to 1.
This was not the case before downloading last release.

### Expected behavior

No before take-off messages after T.O ...

### Steps to reproduce

- Landing full flaps, autobrake medium, spoilers armed.
- Reverse on landing, spoliers deploid -> reverse to idle, spoilers disarm 
- Master Caution comes on with the Flaps not in T.O. config

### Additional info (optional)

Was the first flight(s) after fix  : #7652

**Comment by Eearslya** [comment]
Are you using a Stream Deck or other external control software? There was a recent change that made it so the T.O CONFIG button is now held down instead of a momentary press. Some Stream Deck profiles have not updated to release the button properly yet.

**Comment by Rascal650** [comment]
I experience the same bug every time I land. I also use Stream Deck (with a button assigned specifically to TO CONFIG).   Is there a new MOBIFLIGHT code update for "TO CONFIG"?

**Comment by Eearslya** [comment]
> I experience the same bug every time I land. I also use Stream Deck (with a button assigned specifically to TO CONFIG). Is there a new MOBIFLIGHT code update for "TO CONFIG"?

I've never used Mobiflight and I'm not sure how they work, but solving the issue should be simple if you know a bit about what you're doing. Pressing the button sets the LVar `A32NX_BTN_TOCONFIG` to 1. All you need to do is make it so releasing the button sets that same LVar back to 0.

**Comment by Rascal650** [comment]
I'm not the author of this bug but as explained earlier,  I was experiencing this bug after clicking "TO CONFIG" on my Stream Deck during the take off checklist.

 I just mplemented the  "press" (1 (>L:A32NX_BTN_TOCONFIG))  and release (0 (>L:A32NX_BTN_TOCONFIG)) as suggested and I can confirm that I'm not getting these ECAM warnings after landing anymore.
