### ISSUE TITLE
Popout ISIS see-through with no ELEC power

### ISSUE THREAD

**Issue by MStallen** [flybywiresim/a32nx#7854]
### Aircraft Version

Dev

### Build info

```json
{
    "built": "2023-03-04T16:44:07+00:00",
    "ref": "refs/heads/master",
    "sha": "4a38c4328bcbeb62b8d91ae5ce7f2d6560a0ab11",
    "actor": "tracernz",
    "event_name": "manual",
    "pretty_release_name": "master:4a38c432",
    "version": "v0.10.0-dev.4a38c43"
}
```

### Describe the bug

If you pop out the ISIS I can see a image outside the aircraft (if I look arround the image is also changing.
I'm using homecockpit mode in the EFB and all other popouts are black.

ISIS in the virtual cockpit is black

### Expected behavior

Black background of ISIS in popout

### Steps to reproduce

Use FBW A32NX and pop out ISIS

### References (optional)

![image](https://user-images.githubusercontent.com/75130831/223966520-db1e4f99-96be-4264-b94f-9820d04fdf22.png)

**Comment by tracernz** [comment]
Can't reproduce this one, on or off.
![image](https://user-images.githubusercontent.com/9995998/227501043-f5331049-3dde-443c-80a5-a82c9aaada46.png)
![image](https://user-images.githubusercontent.com/9995998/227501076-533dcc5e-6564-489f-a465-b8c719c426d4.png)

**Comment by beheh** [comment]
Is it possible this is from the SU12 beta? I know there were some changes around external window handling.

**Comment by MStallen** [comment]
Also in SU12 it's still the same problem.

Using DX12

**Comment by tracernz** [comment]
Which graphics card do you have? The ISIS definitely has an opaque background, and I can't reproduce this issue at all with NVidia drivers.

**Comment by 2hwk** [comment]
Reproduced with AMD Graphics and DX11. Background is transparent when the A/C is in a powered off state.

**Comment by tracernz** [comment]
I'm not sure a graphics driver issue is "Good First Issue" :D. You can see my screenshot above with NVidia and ISIS powered off where the background is rendered correctly.

**Comment by MStallen** [comment]
I've a NVidia Titan X with the latest drivers. My problem still exists. And this problem is already there for months. I remember that the problem was gone for a while, but I don't remember when it reoccurred,
