### ISSUE TITLE
Overspeed alert in cruise level

### ISSUE THREAD

**Issue by FoxMulder1974** [flybywiresim/a32nx#7875]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2023-03-12T02:18:53+00:00",
    "ref": "refs/heads/master",
    "sha": "f1bf742950278be4d4c226a01ae72d8a7af2246d",
    "actor": "frankkopp",
    "event_name": "manual",
    "pretty_release_name": "master:f1bf7429",
    "version": "v0.10.0-dev.f1bf742"
}
```

### Describe the bug

1. load your flight planner normally
2. insert a FL >= 320
3.go to MCDU -> PERF -> CRZ and insert in PRESEL SPEED 320 (I know that the speed is not correct due to FL but try)
4. take off, climb and reach FL
5. you can see that the aircraft is in overspeed but any warnings system (chime, warning light) will work.
6. after few minutes you will see failure in ECAM

### Expected behavior

when the aircraft is in overspeed warning system (chime, warning light) will work.

### Steps to reproduce

1. load your flight planner normally
2. insert a FL >= 320
3.go to MCDU -> PERF -> CRZ and insert in PRESEL SPEED 320 (I know that the speed is not correct due to FL but try)
4. take off, climb and reach FL
5. you can see that the aircraft is in overspeed but any warnings system (chime, warning light) will work.
6. after few minutes you will see failure in ECAM

**Comment by donstim** [comment]
I could not reproduce the issue using your instructions. I set a cruise FL of 330 and a PRESEL SPEED of 320 (which is well above VMO at that flight level). The airplane reached the cruise flight level and switched to the preselected speed. However, the FMGS correctly limited the speed to VMO. At no time did the airplane get into an overspeed situation.

Do you have any other airplane mods/liveries installed in your community folder?

Is this a repeatable issue for you?
![Screenshot (2698)](https://user-images.githubusercontent.com/70166617/226092199-2b27dc8d-a65c-431e-a89b-faf035e783e4.png)
