### ISSUE TITLE
[BUG] LS button stay illuminated 

### ISSUE THREAD

**Issue by ZiCongQ** [flybywiresim/a32nx#788]
**Mod Version**
Latest master branch with 1030 commits.

**Describe the bug**
The "LS" button stays illuminated, can't be turned off

**To Reproduce**

1.Load in to a GATE
2.start aircraft cold and dark

**Expected behavior**
Click on LS button and the light go away.

**Actual behavior**
light stays illuminated

**References**

**Additional context**

Discord username (if different from GitHub):

**Comment by UncleClapton** [comment]
I'm unable to replicate this. weird...

**Comment by DoToAdventures** [comment]
I am also unable to replicate this, the LS light is turned off by default for me, turning it on and off works.

**Comment by ErikNL80** [comment]
Can you please check again after putting the ground traffic slider to 0 and/or trying it at another airport?

**Comment by lousybyte** [comment]
Closing since can't replicate and no feedback was given.
