### ISSUE TITLE
[BUG] Crash after APU Start button

### ISSUE THREAD

**Issue by x4nthx** [flybywiresim/a32nx#789]
**Mod Version**
 Last master

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Discord username (if different from GitHub):

**Comment by x4nthx** [comment]
Sorry for the post.. i got messy lol


**Mod Version**
 Last master


**Describe the bug**



**To Reproduce**

<!-- I updated the game, I deleted a320nx and installed the last one (patch indicated), first time external power waa not available. I rebooted the game, external power was available. But apu start on the dark and cold procedure get crash. 3 times after rebooting the game. It still happens

**Comment by x4nthx** [comment]
1- bat 1 and 2 ON --- 2- External power ON --- 3- Packs ON (4 buttons) --- 4- RSI ON (3 of them) --- NAV lights, probe ON, SMOKE AUTO --- 5- (after fmc stuff) APU START ON, wait for flaps open.. CRASH

**Comment by DoToAdventures** [comment]
> 
> 
> 1- bat 1 and 2 ON --- 2- External power ON --- 3- Packs ON (4 buttons) --- 4- RSI ON (3 of them) --- NAV lights, probe ON, SMOKE AUTO --- 5- (after fmc stuff) APU START ON, wait for flaps open.. CRASH
> I updated the game, I deleted a320nx and installed the last one (patch indicated), first time external power was not available. I rebooted the game, external power was available. But apu start on the dark and cold procedure get crash. 3 times after rebooting the game. It still happens.
> 
> LAST MASTER version
> 
> Sorry for the messy.. I got confused posting

Please edit your original issue post for easier readability and following of the template instead. It's there for a reason.
