### ISSUE TITLE
COOLING prior to ENG START

### ISSUE THREAD

**Issue by flogross89** [flybywiresim/a32nx#7895]
### Aircraft Version

Development

### Description

Not sure whether to what extent this also applies to the LEAP power plants, but here are my observations:

Goal: To prevent bowed rotors, which could damage the engine and reduce power/longevity.

Engine behavior: During engine start, if the engine EGT exceeds a certain threshold [1], the engines are cranked/motored for a certain period of time (~ between 30 and 90 seconds) with a specific N2 [2] before continuing with the engine start. 
For PW engines, 

Display behavior (only EWD): 
For PW aircraft, "COOLING x' y''" with x being minutes, and y being seconds is displayed as a countdown next to N2. 
For LEAP aircraft, I couldn't find a reference for such a COOLING message, but it still seems to take place.

Open questions: 
[1] What is the EGT threshold? Cooling doesn't seem to occur after engine shutdowns longer than 6 hours. 
[2] What is the maximum N2? For PW it seems to be 10%, for LEAP somewhat higher? 
[3] How does the EWD visualization look like? (see display behavior)

### References (optional)

https://www.pprune.org/tech-log/645333-cfm-leap-1a-cooling-time.html
https://www.pprune.org/tech-log/635501-a20n-engine-start.html
https://www.pprune.org/tech-log/636160-cooling-time-pw1100g-a320.html

https://www.youtube.com/watch?v=4NAs7DJ42eM (PW)
https://www.youtube.com/watch?v=ytnLBAkRFQE (LEAP)
https://www.youtube.com/watch?v=Y1yQziRUFNY (PW)
https://www.youtube.com/watch?v=k29x140Nle8 (PW)

### Additional info (optional)

I would offer to implement these changes, I identified the respective part in the engine logic. However, I'm missing technical info (see questions above).

**Comment by tracernz** [comment]
The LEAP does do it, but with no indication and no dual cooling mode.

**Comment by flogross89** [comment]
> The LEAP does do it, but with no indication and no dual cooling mode.

Thanks! Without it being that apparent for a user, is this still something which should be implemented? Or is it not worth collecting the technical data and implementing it?

**Comment by tracernz** [comment]
Definitely worth doing!

**Comment by Taz5150** [comment]
I believe engine cooling is not discrete, but continuous; meaning there is no EGT threshold. Engine start performance will change probably inversely proportional to ITT (which is related to EGT, but not linearly).

My concern here is that to do temperature dependent engine starts, we have to tweak (recalculate) the complex polynomial and re-work the regression model to include engine temperature and maybe even pressure. 

In any case, is within the plan: https://github.com/flybywiresim/a32nx/issues/3117
