### ISSUE TITLE
[BUG] The rate of climb on the autopilot goes up to 6000 ft / s

### ISSUE THREAD

**Issue by Nentorro** [flybywiresim/a32nx#790]
**newest**
Master

**Describe the bug**
The rate of climb on the autopilot goes up to 6000 ft / s

**To Reproduce**
When I have planned a flight and then start the flight. I go through the normal start-up procedure and then turn on the autopilot. Then the A320 goes extremely into the rate of climb of up to 6000 ft / s,

**Comment by AdenFlorian** [comment]
is this the same as this issue? https://github.com/flybywiresim/a32nx/issues/732

**Comment by Nentorro** [comment]
My English is not the best. But as I read it is the same or something like that

**Comment by AdenFlorian** [comment]
cool, closing this as it is a duplicate then
