### ISSUE TITLE
APU Fire test PB clickspot misaligned

### ISSUE THREAD

**Issue by St54Kevin** [flybywiresim/a32nx#7912]
### Aircraft Version

Experimental

### Build info

```json
{
    "built": "2023-03-27T03:47:43+00:00",
    "ref": "refs/heads/experimental",
    "sha": "f560618022825d93ed8b6c9c85fa6dc979f82e1d",
    "actor": "2hwk",
    "event_name": "manual",
    "pretty_release_name": "experimental:f5606180",
    "version": "v0.10.0-exp.f560618"
}
```

### Describe the bug

I set up a view to see the whole overhead panel. In this view its very hard to reach the APU fire test pb. The Fire guard switch clickspot overlaps the button. Just at the very bottom of the APU fire test pb there is a small clickspot for it.

This is the view. Could get the mouse on it though:
![Screenshot (6)](https://user-images.githubusercontent.com/448627/227930872-20e05d31-fd09-4b07-bd2c-6671dc4b30c8.png)

### Expected behavior

Fire guard should not overlap test pb

### Steps to reproduce

Set a view very low and centered to see the overhead panel. Try to press APU fire test pb without opening the guard

### Discord Username (optional)

St54Kevin#3583

**Comment by gizmo71** [comment]
It's easy to catch the guard instead of the button even in the default view of the overhead panel.
