### ISSUE TITLE
[MCDU] Not possible to input just ZFW into INIT B page

### ISSUE THREAD

**Issue by St54Kevin** [flybywiresim/a32nx#7913]
### Aircraft Version

Experimental

### Build info

```json
{
    "built": "2023-03-27T03:47:43+00:00",
    "ref": "refs/heads/experimental",
    "sha": "f560618022825d93ed8b6c9c85fa6dc979f82e1d",
    "actor": "2hwk",
    "event_name": "manual",
    "pretty_release_name": "experimental:f5606180",
    "version": "v0.10.0-exp.f560618"
}
```

### Describe the bug

In the cockpit preparation the planned ZFW is usually put in into the INIT B page WITHOUT the ZFWCG (because usually you get that with the loadsheet) in order to get first fuel planning values onto the MCDU. It is not possible here to input eg. "63.8" or "63.8/" into LSK1R.

![image](https://user-images.githubusercontent.com/448627/227931661-82d12512-3104-46f5-a51a-dbfbb4681bb5.png)

### Expected behavior

Should be possible to just put in ZFW with the ZFWCG to stay empty (amber boxes). This + blockfuel input should start the fuel calculation of the system

### Steps to reproduce

see above

### References (optional)

IRL experience with Thales, I think it isnt different here

### Discord Username (optional)

St54Kevin#3583

**Comment by St54Kevin** [comment]
Yeah that manual seems to be very old, although I have not seen an up to date one. It is something I would have guessed to be updated by Airbus

**Comment by tracernz** [comment]
We have two different Honeywell pilots that have confirmed this in the past when it came up. It's only possible to enter ZFW only, if the ZFW/ZFWCG pair has been previously entered.

**Comment by St54Kevin** [comment]
> We have two different Honeywell pilots that have confirmed this in the past when it came up. It's only possible to enter ZFW only, if the ZFW/ZFWCG pair has been previously entered.

Okay thanks than I will close this one
