### ISSUE TITLE
[EWD] negative engine parameters

### ISSUE THREAD

**Issue by BravoMike99** [flybywiresim/a32nx#7916]
### Aircraft Version

Experimental

### Build info

```json
{
    "built": "2023-03-25T10:38:40+00:00",
    "ref": "refs/heads/experimental",
    "sha": "5bc0e37c5c256eedabb235060ac8ae23d54342ec",
    "actor": "2hwk",
    "event_name": "manual",
    "pretty_release_name": "experimental:5bc0e37c",
    "version": "v0.10.0-exp.5bc0e37"
}
```

### Describe the bug

Sometimes when loading the aircraft from the cold and dark N2 shows as a negative value on one of the engines.
![neg](https://user-images.githubusercontent.com/119708186/228049018-6ef66bf6-55e4-4b23-a2ed-4106d71300eb.PNG)
![Neg two](https://user-images.githubusercontent.com/119708186/228049024-923122e2-acc9-4851-98a3-434a66d36336.PNG)
In addition, when shutting down the engine sometimes a negative fuel flow value is visible on engine number one.
![image](https://user-images.githubusercontent.com/119708186/228078410-2c407fbd-b350-477f-9a63-6c5ee72c4579.png)
(issue updated to include negative fuel flow)
### Expected behavior

N2 and Fuel flow not going below 0.

### Steps to reproduce

Haven't been able to find an exact trigger yet but it has happened in the last three flights in a row to me, two of them at AMS. 
Here's one of the metars if it helps: EHAM 32007KT 300V360 9999 VCSH FEW025CB 04/01 Q1025 NOSIG

### Discord Username (optional)

Bruno_pt99#5802

**Comment by tracernz** [comment]
I don't believe it will even measure N2 below about 3% or so IRL anyway. Not sure if it can measure spin direction.

**Comment by Taz5150** [comment]
Good call. Simple fix coming right away.
