### ISSUE TITLE
Round up fuel quantity

### ISSUE THREAD

**Issue by Keight8** [flybywiresim/a32nx#7923]
### Aircraft Version

Experimental

### Description

Currently the total fuel is being imported with an exact number as in simbrief. On the refuel panel of a real thing there are only the tenths place values (e.g. 7.4). So it would be more realistic if the imported values rounded up to the next hundred (e.g. 7349 -> 7400).

### Discord Username (optional)

K8#4795

**Comment by juliansebline** [comment]
What if 7310 for example?

**Comment by Keight8** [comment]
Obviously you don't want to take less fuel than required so you still order 7.4 tons to stay on the safe side.

**Comment by MikioDK** [comment]
This is what you expect right 
![image](https://user-images.githubusercontent.com/13847452/232139719-6ce643de-e777-41d1-a95a-9707788ed136.png)
