### ISSUE TITLE
UNPLAYABLE!!!!!!!

### ISSUE THREAD

**Issue by Watsi01** [flybywiresim/a32nx#7930]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2023-03-29T19:59:27+00:00",
    "ref": "refs/heads/experimental",
    "sha": "7188d4a6394f6965ad54583647d2c54d13adf89e",
    "actor": "beheh",
    "event_name": "manual",
    "pretty_release_name": "experimental:7188d4a6",
    "version": "v0.10.0-exp.7188d4a"
}
```

### Describe the bug

I can't believe you could get away with this for such a long time!!!!

This plane is UNFLYABLE!!!!

I can't start it. Tried everything. Nothing works!!!! 
But a friend of mine is a real A320 pilot and I showed him the plane. And he immedialty knew what is wrong.

**This so called 'high fidelity' plane is missing a KEY FEATURE!!
No wonder I can't get it started.**

Seriously!?? Study Level?!?!**

I attached a picture of a real A320 cockpit my friend send me from his workplace.

![A320realcockpit3](https://user-images.githubusercontent.com/72334392/229274651-52ed346c-5477-418e-9847-ca22e938b663.jpg)

This should get fixed ASAP!!!!

### Expected behavior

Being study level!!!!!!

### Steps to reproduce

1. enter the plane
2. search for your ignition key

### Discord Username (optional)

RogePete

**Comment by juliansebline** [comment]
Hi! Thank you for your report.

We'll fix that ASAP!!!!

**Comment by ko-zone** [comment]
I 100% agree, this better be sorted ASAP!

**Comment by tracernz** [comment]
Waiting for your patch @ko-zone .
