### ISSUE TITLE
Remote Simbridge does not reset if enabled then disabled

### ISSUE THREAD

**Issue by 2hwk** [flybywiresim/a32nx#7933]
### Aircraft Version

Development/Experimental

### Describe the bug

If you set the simbridge host machine to a remote PC, enter a custom IP, then disable the remote simbridge feature (i.e. localhost only), local simbridge will no longer work.

To restore it, you must reenable remote simbridge, enter ``localhost`` as the IP address, then disable remote simbridge.

### Expected behavior

Remote Simbridge toggle restores local simbridge without having to override the IP address manually (workaround)

### Steps to reproduce

1. Open EFB Settings Page > Sim Options 
2. Select ``Remote PC`` for the Simbridge Host Machine option
3. Enter a custom IP for Simbridge
4. Select ``This PC`` for Simbridge Host Machine
5. Start local simbridge
6. Simbridge will no longer connect if hosted locally

To fix: 

7. Select ``Remote PC`` for the Simbridge Host Machine option
8. Rename the custom IP back to ``localhost``
9. Select ``This PC`` for Simbridge Host Machine
10. Start local simbridge
11. Simbridge (local) will now work as per normal (use EFB setting to force connection if it has timed out).

### Discord Username (optional)

2Cas#1022

**Comment by Cassiano-Gunji** [comment]
I've seen the same behavior.
Also, when running SimBridge on a remote computer, Experimental FBW doesn't display terrain map, but remote MCDU works. When launching SimBridge in the simulator computer, the map shows up immediatly, with the EFB still pointing to the remote SimBridge.
