### ISSUE TITLE
Display self test for msfs avionics instrument broken

### ISSUE THREAD

**Issue by Saschl** [flybywiresim/a32nx#7936]
### Aircraft Version

Dev/Exp

### Build info

```json
{
    "built": "2023-02-02T09:20:09+00:00",
    "ref": "HEAD",
    "sha": "fa3b5e6d545c188c3ff6c596655c2f1acaba33bb",
    "actor": "Saschl",
    "event_name": "manual",
    "pretty_release_name": "experimental:fa3b5e6d",
    "version": "v0.10.0-exp.fa3b5e6"
}
```

### Describe the bug

Seems like https://github.com/flybywiresim/a32nx/commit/0128220b4a299aa6a172a65d8091079334f7f119#diff-82000ba2ab1fe4d3630f1b900e314818002445fa45d58e9642da9adcd3a6d1e1R67-R80 introduced a bug that prevents msfs avionics from displaying the self test screen.

### Expected behavior

Self test screen showing after plane/display is being powered up.

Currently, the added logic for the DMC maintenance screens is running in a loop, which interferes with the event driven approach we use to determine the other states of the screen (e.g. self-test).

The following might act as a rough guide to fix the issue:

1. Move the determination of the ```L:A32NX_DMC_DISPLAYTEST:${this.supplyingDmc}``` to a SwitchableProvider, probably a new one is needed (example is AdirsValueProvider from the PFD)
2. Create a sub for the variable, provide as a variable to displayUnit (or even subscribe there directly). Then set the state like it is done with power and brightness

### Steps to reproduce

1. Launch C&D
3. Turn on ext power
4. PFD and EWD immediately are "ready", or the self test screen disappears after roughly 1 second instead of the configured time

**Comment by MStallen** [comment]
Reproduced
