### ISSUE TITLE
Window open

### ISSUE THREAD

**Issue by XpNvH** [flybywiresim/a32nx#7938]
### Aircraft Version

Stable

### Description

I would like to see the ability to open the window like you can in real life. (The cockpit windows.)

### References (optional)

Video i found from the internet of opening an A320 Window:

https://www.youtube.com/watch?v=qMHZ1uFPS54

### Additional info (optional)

It would be cool if the window couldn't open at high altitude because of air pressure.

**Comment by BlueberryKing** [comment]
Duplicate of #4589
