### ISSUE TITLE
Wrong input format in STEP ALTS page

### ISSUE THREAD

**Issue by pinatacolada** [flybywiresim/a32nx#7944]
### Aircraft Version

Experimental

### Build info

```json
{
    "built": "2023-04-03T09:45:25+00:00",
    "ref": "refs/heads/experimental",
    "sha": "107e1b66c243593a7b23eace34e2af808e971c3b",
    "actor": "2hwk",
    "event_name": "manual",
    "pretty_release_name": "experimental:107e1b66",
    "version": "v0.10.0-exp.107e1b6"
}
```

### Describe the bug

The STEP ALTS page is incorrectly accepting the ALT format, and rejecting the xxx part of the FLIGHT LEVEL format.

### Expected behavior

ALT (NNNN or NNNNN, max 39000) format should be rejected and only FLIGHT LEVEL (NNN or FLNNN, max FL390) should be accepted.

Using`360/GUNTI` or `FL360/GUNTI` as a valid format. 

Trying `36000/GUNTI` or `4000/GUNTI` or `FL391/GUNTI` or `39100/GUNTI`should result in INVALID FORMAT

### Steps to reproduce

- [ ] Create a flightplan with at least 6 points enroute
- [ ] On the STEP ALTs page try to insert 360/WPT01
- [ ] Insert 9000/WPT02
- [ ] insert 36000/WPT03
- [ ] insert 4000/WPT04
- [ ] insert FL391/WPT05
- [ ] insert 39100/WPT06

### References (optional)

FCOM DSC-22 20-50-30 CONTROLS AND INDICATORS - MCDU - DATA FORMAT LIST - ALT and on the same table FLIGHT LEVEL

**Comment by patmack14** [comment]
@BlueberryKing are you still planning on tackling this one?

**Comment by BlueberryKing** [comment]
> @BlueberryKing are you still planning on tackling this one?  

Yes, I am currently working in this for VNAV.
