### ISSUE TITLE
[Bleed]- High bleed temperatures when using APU bleed

### ISSUE THREAD

**Issue by BravoMike99** [flybywiresim/a32nx#7953]
### Aircraft Version

Experimental

### Build info

```json
{
    "built": "2023-04-05T04:30:51+00:00",
    "ref": "refs/heads/experimental",
    "sha": "24d74520ff50aaaf330063674057ed7595a384a2",
    "actor": "2hwk",
    "event_name": "manual",
    "pretty_release_name": "experimental:24d74520",
    "version": "v0.10.0-exp.24d7452"
}
```

### Describe the bug

When using the APU bleed as the only bleed source, pack compressor and precooler temperatures reach values above the overhead threshold, resulting in amber indications. This seems to be the case as long as the APU bleed is kept on.
![bleed](https://user-images.githubusercontent.com/119708186/230651310-ba1de1ac-1891-4613-bcd5-92e5e1b068f8.PNG)
![Bleed 2](https://user-images.githubusercontent.com/119708186/230651316-59ea5c98-7287-469d-80d2-88a669fb6c83.PNG)

### Expected behavior

Temperatures to stay  in normal operation range.

### Steps to reproduce

1) Turn on APU Bleed
2) Observe the temperature indications on the bleed page

### Discord Username (optional)

Bruno_pt99#5802

**Comment by BlueberryKing** [comment]
Hi, good catch. You'll be happy to know that this is being fixed in #7943 😄 .
