### ISSUE TITLE
LVAR LIGHTING_TAXI_2 doesn't return any data

### ISSUE THREAD

**Issue by richardkennedy** [flybywiresim/a32nx#7956]
### Aircraft Version

Experimental

### Build info

```json
{
    "built": "2023-04-05T04:30:51+00:00",
    "ref": "refs/heads/experimental",
    "sha": "24d74520ff50aaaf330063674057ed7595a384a2",
    "actor": "2hwk",
    "event_name": "manual",
    "pretty_release_name": "experimental:24d74520",
    "version": "v0.10.0-exp.24d7452"
}
```

### Describe the bug

The LIGHTING_TAXI_2 LVAR doesn't return any data (Runway Turn Off Lights).

### Expected behavior

Per documentation, this LVAR should return 0|1.
https://github.com/flybywiresim/docs/blob/053f7c7b0310f7888e2798f4d7261b64328eb6f3/docs/fbw-a32nx/a32nx-api/a32nx-flightdeck-api.md

### Steps to reproduce

1. Attempt to read the LVAR LIGHTING_TAXI_2

**Comment by tracernz** [comment]
Depending on what you want you can just read the `CIRCUIT ON` or `CIRCUIT SWITCH ON` A vars. No need to Lvar overhead.

**Comment by tracernz** [comment]
Was removed by https://github.com/flybywiresim/a32nx/pull/7605 as it was merely an internal implementation detail of one of the Asobo templates.

**Comment by 2hwk** [comment]
So there's several undocumented ways you can achieve this, either use the circuit on vars noted above, or alternatively, ``A:LIGHT TAXI:2`` and ``A:LIGHT TAXI:3`` are also readable.

**Comment by 2hwk** [comment]
This will be documented in a fbw-docs update, closed. (I would open an issue in the docs repo but this will be merged fairly soon anyway.)
