### ISSUE TITLE
[Fuel] Amber center tanks during normal operation on fuel ecam

### ISSUE THREAD

**Issue by BravoMike99** [flybywiresim/a32nx#7968]
### Aircraft Version

Experimental

### Build info

```json
{
    "built": "2023-04-14T14:28:11+00:00",
    "ref": "refs/heads/experimental",
    "sha": "49faa5cb317e1fa71bfa29cd18157dd2735b733c",
    "actor": "2hwk",
    "event_name": "manual",
    "pretty_release_name": "experimental:49faa5cb",
    "version": "v0.10.0-exp.49faa5c"
}
```

### Describe the bug

If the center tanks are empty and the center tank fuel pumps are on while the aircraft is in the air, their indications appears as amber in the lower ecam. When the aircraft is on the ground, they show up as green.
![FUEL](https://user-images.githubusercontent.com/119708186/232165066-621ebd27-974f-42d3-ad32-319a44546433.PNG)

### Expected behavior

Center tank indications to be green since they are in normal operation.

### Steps to reproduce

1) Load the aircraft without any fuel in center tanks
2) Take it airborne and check the fuel SD page

### References (optional)

E.g.: https://youtu.be/VUjfYWNijA8?t=14

### Discord Username (optional)

Bruno_pt99#5802

**Comment by donstim** [comment]
@tracernz

**Comment by Benjozork** [comment]
Do you have the newlight mod ?

**Comment by BravoMike99** [comment]
> Do you have the newlight mod ?

Nop
