### ISSUE TITLE
[BUG] ECAM STS and CLR buttons do not light up

### ISSUE THREAD

**Issue by lukecologne** [flybywiresim/a32nx#797]
**Mod Version**

Master

**Describe the bug**

Status page button LED not lighting when STS page selected, ECAM CLR button not lighting up when there is an issue to clear

**To Reproduce**

1. Spawn
2. Press the ECAM STS button / Cause an ECAM warning
3.

**Expected behavior**

STS and CLR buttons light up accordingly.

**Actual behavior**

Both do not light up.

**References**

![grafik](https://user-images.githubusercontent.com/39596827/93838059-a3ad0b00-fc88-11ea-9ac8-e5c11a58c555.png)

**Comment by Ares1378** [comment]
I also can confirm this issue.

Ares

**Comment by lukecologne** [comment]
I think I got a solution ready, will open a PR shortly
