### ISSUE TITLE
APU Bleed Display INOP

### ISSUE THREAD

**Issue by Luz5020** [flybywiresim/a32nx#7973]
### Aircraft Version

Experimental

### Build info

```json
{
    "built": "2023-04-15T13:57:47+00:00",
    "ref": "refs/heads/experimental",
    "sha": "df9b2e907563c9dc1d1020fe3d9b66a4054e7533",
    "actor": "2hwk",
    "event_name": "manual",
    "pretty_release_name": "experimental:df9b2e90",
    "version": "v0.10.0-exp.df9b2e9"
}
```

### Describe the bug

The APU Page shows the Amber XX indication on the Bleed Pressure indicator.

### Expected behavior

The Bleed Pressure indicator should display the pressure of Bleed Air that's sent into the Bleed Air system

### Steps to reproduce

1. Spawn at gate
2. Start APU and turn on bleed
3. Check APU ECAM Page

### References (optional)

![image](https://user-images.githubusercontent.com/43752735/232842869-f9909204-0287-42d3-b69b-74e5016d0929.png)

### Additional info (optional)

The screenshot above was taken after the flight, although I'm sure the issue persists, if it can't be replicated, a flight should be conducted prior.

**Comment by tracernz** [comment]
Are the ADRs switched off here? APU bleed pressure is not computed without air data.

**Comment by Luz5020** [comment]
ADIRS units, I assume that's what you mean where turned off at this point. I have opened this issue on specific request by a fbw dev on discord. After providing OHP Image I was told this was a "known issue/bug" if this was a mistake feel free to close. But please refer to the conversation on discord as well. ![image](https://user-images.githubusercontent.com/43752735/232900655-52043cb6-91f1-4479-ac05-f7cda1910fa8.png)

**Comment by lukecologne** [comment]
This is correct behaviour. APU bleed pressure is displayed with the ambient pressure subtracted. If the ambient pressure (provided by the ADRs) is not available, which seems to be the case here (TAT and SAT are also marked invalid), the APU bleed pressure will be invalid. If you can confirm that the ADRs are indeed unavailable (either ADR buttons off, or mode selector in OFF) and that the indication returns when the ADR static pressure is available, we can close the issue

**Comment by Luz5020** [comment]
I'll double check with ADRs on tomorrow, will close when able to attain bleed pressure

**Comment by tshomas** [comment]
![PXL_20230421_111747743](https://user-images.githubusercontent.com/74841560/233623249-d5d67c94-5cfd-44cc-9558-36b162c0ed1c.jpg)


For reference, either ADIRS 1 or 2

**Comment by Luz5020** [comment]
Ok, works when ADR is on, therfore resolved
