### ISSUE TITLE
Integrate Flypad with Chartfox

### ISSUE THREAD

**Issue by Pugsrgreat** [flybywiresim/a32nx#7974]
### Aircraft Version

Stable

### Description

It would be nice for people who do not have any money to be able to easily access charts. This is why I think that integrating with chartfox and allowing us to search for and pin charts (like how it works with navigraph). This would be amazing for people who do not want to buy a subscription or do not have a credit card. 

### Discord Username (optional)

Mpugs#1778

**Comment by beheh** [comment]
Duplcates #5768
