### ISSUE TITLE
[BUG] MCDU not able to show added waypoints or airways into flightplan

### ISSUE THREAD

**Issue by starvingjavi** [flybywiresim/a32nx#798]
**Mod Version**
master

**Describe the bug**
When making adding a flight plan manually in the MCDU, when trying to add airways or waypoints they will not appear after being added, even though the page seems to have accepted the waypoint.

**To Reproduce**

1. Start flight at gate
2. Start airplane normally
3. Input FROM/TO on MCDU
4. Select F-PLAN button
5. Select starting airport. Select DEPARTURES. Select the departure runway and procedure. Select "TMPY INSERT*"
6. Select the last waypoint on flight plan. Select "AIRWAYS>". Write the next waypoint in the flightplan and write it under "TO".

**Expected behavior**
Airway or waypoint would appear after they are input in the MCDU.

**Actual behavior**
If the bug happens you won't be able to see what you just input, but the you will get a message to insert said waypoints into the flightplan

**References**
![Captura de pantalla 2020-09-21 231211](https://user-images.githubusercontent.com/70245523/93843605-0211c380-fc60-11ea-9368-62822c446148.png)
![Captura de pantalla 2020-09-21 231228](https://user-images.githubusercontent.com/70245523/93843606-0342f080-fc60-11ea-94f7-6df9b2c7fea6.png)

Discord username (if different from GitHub): javi#2557

**Comment by Ares1378** [comment]
This is a confirmed issue. 

Ares

**Comment by UncleClapton** [comment]
I've noticed this before (before the patch even). I've got a theory that something went wrong with the fix we did to make airways have multiple pages.
