### ISSUE TITLE
Frame Drops

### ISSUE THREAD

**Issue by dg1234567** [flybywiresim/a32nx#8002]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2023-05-03T13:59:29+00:00",
    "ref": "refs/heads/master",
    "sha": "627b55661cb28692c7324e5aa841796a885d3d9a",
    "actor": "frankkopp",
    "event_name": "manual",
    "pretty_release_name": "master:627b5566",
    "version": "v0.10.0-dev.627b556"
}
```

### Describe the bug

Significant frame drops at random points especially when interacting with the tablet; ATC filters also very buggy on tablet

### Expected behavior

ATC filters for the appropriate tab, but it seems to just put random frequencies together under a certain tab. Also frame rates should be normal or very little loss in frame rate.

### Steps to reproduce

Spawn anywhere
Interact with tablet

### Discord Username (optional)

dg1234

**Comment by Benjozork** [comment]
What are your specs and are you on DX11 or DX12?

**Comment by dg1234567** [comment]
DX11; also the ATC filtering issue went away when i restarted the sim
