### ISSUE TITLE
[BUG] Engine One Rollback

### ISSUE THREAD

**Issue by Baillie521** [flybywiresim/a32nx#801]
**Mod Version**

Release 0.2.0

**Describe the bug**
 When starting up engines they both idle fine until end of taxi/just after takeoff where engine one will rollback and stop working.

**To Reproduce**

1. Start aircraft from cold and dark.
2. Start engines as per the checklist and/or known procedures.
3. Watch the N1 go no further than 1.0 and N2 go no higher than about 24.9

**Expected behavior**

I would’ve expected the engines to continue working correctly.

**Actual behavior**

When the engine rolls back it will then not go above N1 - 1.0 and N2 ~ 24.8. Even when I try to restart the engine or even use the Cntrl + E key combo I’m getting the same symptoms, the engine will not go above these values. This happened when I installed the 0.2.0 release.

**References**

**Additional context**

I have also noticed that the APU will not support any of the ECAM or PFD screens electronics when the engines are off and the ground power is disconnected.

Discord username (if different from GitHub): N/A

**Comment by nobodyn0se** [comment]
Are you sure this is not the engine shutdown issue after the recent patch, already noted in #716 and #740 ?

**Comment by Baillie521** [comment]
I will try one of the solutions in the #716 and see if that works later. I am unaware that this was an issue as I am a little behind and only updated to the second patch yesterday. If this issue continues is this something to do with Asobo or the mod? If so is there a way of fixing it? Thanks! :)

**Comment by Benjozork** [comment]
> If this issue continues is this something to do with Asobo or the mod? If so is there a way of fixing it? Thanks! :)

This is an Asobo bug, but we have a fix in the development (`master`) version. So use that instead of the stable 0.2.0 if you want it fixed almost seamlessly.

**Comment by UncleClapton** [comment]
I'm going to close this as it's a problem reported for an unsupported version of the mod. For future reference, please search for your bug in the issue list before creating a bug report.

**Comment by Baillie521** [comment]
Thanks, guys! Funnily enough, I have actually installed the master version so will give this a test in the coming days around work. I just wanna say on a side note, thank you very much and I really love and appreciate this mod, it's an absolute stunning mod!
