### ISSUE TITLE
GC59ZRNVZ5CBEH

### ISSUE THREAD

**Issue by MotyanichSakh** [flybywiresim/a32nx#8030]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2023-01-08T23:16:53+00:00",
    "ref": "HEAD",
    "sha": "81a8ee3a2e03a24da13cc0bcc4cf3a7d51f188a6",
    "actor": "Saschl <sascharudolf46@gmail.com>",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.9.1"
}
```

### Describe the bug

[-1684407299294.log](https://github.com/flybywiresim/a32nx/files/11507087/-1684407299294.log)
[-1684407295576.log](https://github.com/flybywiresim/a32nx/files/11507088/-1684407295576.log)
[-1684407290988.log](https://github.com/flybywiresim/a32nx/files/11507089/-1684407290988.log)
![Снимок экрана (438)](https://github.com/flybywiresim/a32nx/assets/52563479/86e42877-4e20-42e1-87a0-73cb5578a7d9)

### Expected behavior

I'm sorry, I don't understand English well, and I don't know what exactly you want to learn in this paragraph

### Steps to reproduce

I wanted to install an airplane update and install FSLTL Traffic, and such an error crashes

### Discord Username (optional)

Кто?#6370

**Comment by Luz5020** [comment]
head over to our discord for support https://discord.gg/flybywire

**Comment by MotyanichSakh** [comment]
I came in, wrote to support a320, and the bot threw me a lot of links, then some user wrote: look at the pinned messages

**Comment by 2hwk** [comment]
note: Not an issue with the codebase for the A32NX addon, for support for please use the installer specific discord support channels. Closing the issue.

**Comment by MotyanichSakh** [comment]
I told you, I wrote to the installer channel

**Comment by Luz5020** [comment]
> I told you, I wrote to the installer channel

You wrote to the support channel, you were told to make a thread in the installer channel but you never did
