### ISSUE TITLE
Colour accuracy fix accros all ECAMs

### ISSUE THREAD

**Issue by AnXWB** [flybywiresim/a32nx#8036]
### Aircraft Version

Experimental

### Build info

```json
{
    "built": "2023-05-17T19:05:00+00:00",
    "ref": "refs/heads/experimental",
    "sha": "e2da961b511bf8d5c29524ff135cfbe41aa2d83f",
    "actor": "beheh",
    "event_name": "manual",
    "pretty_release_name": "experimental:e2da961b",
    "version": "v0.10.0-exp.e2da961"
}
```

### Describe the bug

It was found that there has been a possible regression about some visuals on ECAMs. 
Some elements are in white instead of grey, they are listed below :
> EWD :
- Lines between N2 Values
- Lines between FF
- Lines dividing the EWD sections
> ND :
- Squares at the bottom (GPS PRIMARY / TA ONLY / ...) 
> Bottom SD pages :
- Lines dividing the temperature, time and GW sections
> BLEED :
- Square around values for air to air exchanger
> ELEC :
- Squares around any TR/GEN/APU/EXT/BAT and ESS TR
> FUEL :
- Fuel tank symbology
- Sqare around FOB (not the text inside)
- Lines between F. USED
> APU :
- Square around bleed pressure from APU
> DOOR :
Well it is hard to find either the SLIDE text should be white, and the aircraft symbology is in grey as it should either aircraft symbology is in white and should be grey and SLIDE text doesn't pop to the eyes enoughµ

All of those should be in grey instead of white (like the wing on the EWD for flaps/slats).

### Expected behavior

See above description and all red circles in the attached files

### Steps to reproduce

Start the aircraft
Look at ECAMs

### References (optional)

For Dev Team, feel free to ask in appropriate chanels.
![Capture d'écran 2023-05-20 142840](https://github.com/flybywiresim/a32nx/assets/108609629/0e9d1156-58e2-471e-90e6-b6cd38f55e0a)
![Capture d'écran 2023-05-20 142946](https://github.com/flybywiresim/a32nx/assets/108609629/0cb983c6-4414-41f8-bc33-89c1a29e9600)
![Capture d'écran 2023-05-20 143122](https://github.com/flybywiresim/a32nx/assets/108609629/8b7c49fb-8ddd-4b11-92df-e26b6eef6132)
![Capture d'écran 2023-05-20 143229](https://github.com/flybywiresim/a32nx/assets/108609629/7db61c90-2741-4ee4-81cf-a8a0dd6c5cc5)
![Capture d'écran 2023-05-20 143338](https://github.com/flybywiresim/a32nx/assets/108609629/6690989b-9608-4727-8b1d-70b872c2684d)
![Capture d'écran 2023-05-20 143503](https://github.com/flybywiresim/a32nx/assets/108609629/53648cb2-1f71-444c-9f33-cc8df9b159db)
![Capture d'écran 2023-05-20 143558](https://github.com/flybywiresim/a32nx/assets/108609629/4b3cfc0f-1fa2-4789-8849-2d77cdd15584)
![Capture d'écran 2023-05-20 143746](https://github.com/flybywiresim/a32nx/assets/108609629/3946c534-1918-4ad1-8ce6-1282de9b3c4f)

### Discord Username (optional)

AXWB [Z+2]#4622

**Comment by tracernz** [comment]
> Picking up this issue!

Hey, I think Luke has already done quite a bit of work on this.
