### ISSUE TITLE
STS page on ecam

### ISSUE THREAD

**Issue by mrshiljo** [flybywiresim/a32nx#8046]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2023-05-23T08:10:56+00:00",
    "ref": "refs/heads/experimental",
    "sha": "7ac70bfd908988bfdc68879b16a169d26bf0c72c",
    "actor": "Saschl",
    "event_name": "manual",
    "pretty_release_name": "experimental:7ac70bfd",
    "version": "v0.10.0-exp.7ac70bf"
}
```

### Describe the bug

Well, when you push STS button on ECAM control panel, then status page is shown, Thats ok. But when status is normal, which is inidicated with word normal on middle of ecam, then page returns itself to previous mode, whichever that was. Normally if there are any faults or messages, it would stay, but in FBW case it stays even if itas normaly, And thats not correct, if its normaly it should roll back to one before in 4 second, lets say 4. Kind regards

### Expected behavior

explained before

### Steps to reproduce

STS need to roll back if status is normal to page we were before, or at least to first one. And when in cruise, to cruise page

### Discord Username (optional)

addict2flight

**Comment by pluce** [comment]
Found pushbutton logic in [FCOM](http://repo.poltekbangsby.ac.id/571/1/A318_A319_A320_A321%20%28%20PDFDrive%20%29.pdf) (page 1190)

<img width="508" alt="STS_button" src="https://github.com/flybywiresim/a32nx/assets/2952153/93edd5d0-f4c2-4ab9-ac55-22bd0f4a28cf">

**Comment by pluce** [comment]
- [ ] Return to previous screen if no status message after 3s

For the "single ECAM on" scenarios, I'm not sure it's a scenario currently available.
