### ISSUE TITLE
Recognition/auto-import of PDF eAIP charts in flyPadOS

### ISSUE THREAD

**Issue by MM-coder** [flybywiresim/a32nx#8049]
### Aircraft Version

Stable

### Description

# Introduction

Most European countries provide charts to all of their aerodromes/aiports via their eAIS packages. 
These can easily be found by searching eAIS + Country Name in your search engine of choice. 

Most of these eAIS packages use the same if not extremely similar formatting, as such recognizing and possibly even importing eAIS charts would be possible with some work (given that some eAIS packages require an account/login).

Further, it could be possible, however recognizably resource intensive to detect the charts in the `resources/pdfs` folder, this would give the user a much more streamlined experience similar to what they get with Navigraph.

# Suggested Methodology 

![image](https://github.com/flybywiresim/a32nx/assets/22800592/babafbb2-f27a-4e3a-bdd6-eac096370e26)
Fig 1. - eAIS package for EGLL [src](https://www.aurora.nats.co.uk/htmlAIP/Publications/2023-05-18-AIRAC/html/index-en-GB.html#EGLL-AD-2.24)

Most eAIS packages have a table at the end of each aerodrome's information section with the relevant correspondence between the name, so say `RNAV5 (DME/DME or GNSS) STANDARD ARRIVAL CHART - INSTRUMENT (STAR) ALESO 1H LAM 1X TANET 1Z - ICAO` and the filename `AD 2.EGLL-7-2.pdf`

Further note that the PDF location is usually under the `/graphics/` folder making generalization cross-country easier.

It would be possible to compile an index of charts and their corresponding information to provide a display to the user similar to the one provided by the Navigraph integration.

This index could be updated either via a Github Action or by running it when the aircraft is initially loaded or even by developing an API inside of simbridge to update and cache this data.

 

### References (optional)

UK eAIS: https://www.aurora.nats.co.uk/htmlAIP/Publications/2023-05-18-AIRAC/html/index-en-GB.html
Portugal eAIS: https://ais.nav.pt/online-eaip-en/

More of these are surprisingly similar.

### Additional info (optional)

I am happy to assist in this, I'll just need to read up on the current EFB codebase and how that works as I'm not experienced in FS add-on development.

Objective of this issue is looking to see if the community is receptive to this idea or even has a better suggested methodology.

### Discord Username (optional)

itsMM#8175

**Comment by tracernz** [comment]
This could be feasible... perhaps as a tool to pull the charts into a format suitable for SimBridge to consume. Could be a community project outside FBW.

**Comment by MM-coder** [comment]
@tracernz Chartfox already compiles eAIP data. ChartFox is integrated to the latest version of the model.
