### ISSUE TITLE
[BUG] Deployment of Speedbrake and Landing Gear.

### ISSUE THREAD

**Issue by TheMrAJT** [flybywiresim/a32nx#805]
**Mod Version**
Master

**Describe the bug**
During flight the Speed Brake deploys to 100% and landing gear comes down. This happened 3 times while at cruising altitude on a flight from Berlin to Leeds/Bradford and again today on a flight from Heathrow to Paris.

**To Reproduce**
Each time it has happened I've been doing different things. Once in an external camera, another while in the cockpit and another 2 times when not touching any controls at all.

Very strange behaviour and wondered if this has happened to anyone else or a problem possibly with my HOTAS although they are mapped to different switches away from each other - will do further tests without the buttons mapped.

**Expected behavior**
For the speed brake and landing gear not to deploy!

**Actual behavior**
The speed brake and landing gear deployed.

**References**

**Additional context**

Discord username (if different from GitHub): TheMrAJT

**Comment by NathanInnes** [comment]
Really strange.. never had this happen to me but I'll do a flight and test some conditions and give my result soon

**Comment by Venorcis** [comment]
Might be the ground traffic AI bug at work?

**Comment by NathanInnes** [comment]
Possible. I don't fly with AI turned on and every time I deploy speedbrakes the L/G does not come down. I will do some further digging to see if I can find anything.

**Comment by donstim** [comment]
I've never seen this behavior either. Are you sure you don't have these actions mapped to any other keyboard, mouse, or controller inputs?

**Comment by NathanInnes** [comment]
Can't replicate this at all. I will keep an eye on this thread. If this continues to happen then feel free to re-open.
