### ISSUE TITLE
Deboarding doesn't set target PAX to 0

### ISSUE THREAD

**Issue by GeheimagentNr1** [flybywiresim/a32nx#8056]
### Aircraft Version

Experimental

### Build info

```json
{
    "built": "2023-05-23T08:10:56+00:00",
    "ref": "refs/heads/experimental",
    "sha": "7ac70bfd908988bfdc68879b16a169d26bf0c72c",
    "actor": "Saschl",
    "event_name": "manual",
    "pretty_release_name": "experimental:7ac70bfd",
    "version": "v0.10.0-exp.7ac70bf"
}
```

### Describe the bug

When pressing the "Deboard" button on the Payload Page in the EFB, only the Cargo and not the PAX are set to a wanted amount of 0. And the announcement sound "Boarding complete" is played.

### Expected behavior

Both PAX and cargo are set to the target amount of 0 and the announcement "Boarding complete" or a new announcement "Deboarding complete" is only played, when the Aircraft is empty.

### Steps to reproduce

1. Board some PAX and Cargo/PAX Bags
2. Click the "Deboad" Button in the EFB (And "Yes" in the modal)

### Discord Username (optional)

SecretAgentNo1#5094

**Comment by edgarcnp** [comment]
Do you happen to have the toolbar pushback addon? Cause this is what happened to me not too long ago and I had to remove it from the community folder and the deboarding button works as intended again.

**Comment by GeheimagentNr1** [comment]
Toolbar Pushpack addon is not installed, but I check, with the default livery and it worked.  
So it seems to be an issue with the livery.
