### ISSUE TITLE
NEW ACC ALT scratchpad message keeps popping up

### ISSUE THREAD

**Issue by BlueberryKing** [flybywiresim/a32nx#8057]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2023-06-02T15:15:04+00:00",
    "ref": "HEAD",
    "sha": "fc987369d3653758020ba40475d11d4b8f907c9e",
    "actor": "Michael Corcoran <tracer@outlook.co.nz>",
    "event_name": "manual",
    "pretty_release_name": "master:fc987369",
    "version": "v0.10.0-dev.fc98736"
}
```

### Describe the bug

When the acceleration altitude is the same as the altitude of the first altitude constraint, the "NEW ACC ALT" keeps popping up on the scratchpad after clearing it with the CLR key. This was reported by user "zzzap#1112" on Discord.

This can be replicated at KOAK, runway 30 with the CNDEL5, SUSEY transition.

### Expected behavior

The "NEW ACC ALT-2000" should pop up once, but not anymore once cleared.

### Steps to reproduce

1. Load up at KOAK, runway 30.
2. Enter the CNDEL5 SID.
3. Recognize that clearing the "NEW ACC ALT-2000" will make it pop up again.

### Discord Username (optional)

BlueberryKing#6641

**Comment by tracernz** [comment]
Dev Team Quality Assurance Report

Discord : tracernz#3313
Object of testing: https://github.com/flybywiresim/a32nx/pull/8057
Tier of Testing : 1
Date : 07/06/23

Testing Process:

- Load up at EEDH, select a departure, add an AT constraint at the THR RED/ACC ALT. Got the message and cleared it. Repeated various combos of THR RED, ACC, and AT and AT OR BELOW contraints. No problems found and messages always able to be cleared. No loss of functionality confirmed.
- Load up KOAD CNDEL5 from runway 30. Set ACC ALT and THR RED to values above and constrain and at the constraint. Could always clear the message and never reappeared. Bug fixed confirmed.
  
Negatives:
N/A

Testing Results:
Passed

Conclusions:
LGTM
