### ISSUE TITLE
[BUG] FMA does not change from THR IDLE to SPEED when going from OP DES to V/S

### ISSUE THREAD

**Issue by A320pilotIRL** [flybywiresim/a32nx#806]
**Mod Version**
 0.2.0
Msfs latest update 183

**Describe the bug**

FMA does not change but autothrust behaves properly 

**To Reproduce**

1. Start a descent OPEN DES
2.pull and set vertical speed
3. Observe that autothrust increases N1 as it should but the FMA still reads THR IDLE

**Expected behavior**

The left column on the FMA should show speed when activating a vertical speed descent. VS mode is always a SPEED autothrust mode￼. 

**Actual behavior**

When switching from open dissent to vertical speed dissent, the FMA thrust mode does not change from￼￼ THR IDLE to SPEED

**References**

**Additional context**

Discord username (if different from GitHub):

**Comment by bouill** [comment]
+1 on that issue.
Happens both on climb and on descent: 
From a  THR IDLE | OPEN DES or from a CLB THR | OPEN CLIMB , the effect of pulling VS on the FCU is to revert to SPEED | VS.
The aircraft is actually doing that with the thrust, but the FMA thrust mode dispayed is then THR IDLE | V/S or OPEN CLIMB | V/S, which is incorrect
![Microsoft Flight Simulator Screenshot 2020 10 08 - 11 41 17 27 (2)](https://user-images.githubusercontent.com/72552323/95448140-227d9580-0963-11eb-9a0c-9eafe7a2abf5.png)

**Comment by MisterChocker** [comment]
Small hint from me, ATHR also does not engage when reaching green dot speed or minimum flaps speed as well.

**Comment by MisterChocker** [comment]
I believe this is fixed by now
