### ISSUE TITLE
refuel and boarding impossible

### ISSUE THREAD

**Issue by romfootvff** [flybywiresim/a32nx#8076]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2023-05-15T13:42:40+00:00",
    "ref": "refs/tags/v0.10.0",
    "sha": "b0b83346027796b7526415ff8aa13b726308bf36",
    "actor": "Saschl",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.10.0",
    "version": "v0.10.0-rel.b0b8334"
}
```

### Describe the bug

Le refuel et le boarding est impossible, j'ai les boutons pour les lancer mais ils sont grisés.

### Expected behavior

Je devrais y avoir accès.

### Steps to reproduce

Accéder à la tablette

**Comment by Benjozork** [comment]
Please provide screenshots

**Comment by romfootvff** [comment]
@Benjozork 
![Capture d’écran 2023-06-18 154230](https://github.com/flybywiresim/a32nx/assets/103595329/2c2c437e-1dea-4746-86d8-2bdbb14d62af)
![Capture d’écran 2023-06-18 154207](https://github.com/flybywiresim/a32nx/assets/103595329/e68dc8ab-0877-4530-a765-23fa5578f1b8)

**Comment by Luz5020** [comment]
disabel gsx integration

**Comment by romfootvff** [comment]
@Luz5020 I don’t have gsx yet

**Comment by Luz5020** [comment]
> @Luz5020 I don’t have gsx yet

that's why you should disable the integration of course

**Comment by romfootvff** [comment]
Ok, it's good, thanks !
