### ISSUE TITLE
[BUG]Minimum Call

### ISSUE THREAD

**Issue by Gian85** [flybywiresim/a32nx#808]
**Mod Version**
Master
**Describe the bug**
I set the mda value, compiled all the appr page, set the qnh value but  i haven't minimum call

**To Reproduce**

1.Set mda value
2.Starting approche
3.arrived at the minimum altitude there is no call

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Discord username (if different from GitHub):

**Comment by Ares1378** [comment]
I can confirm this does not happen at the DDA/DA i.e. what is entered in the MDA box on the MCDU perf approach page

**Comment by NickyNiclas** [comment]
https://streamable.com/nizei6
There is a sound for minimums, I think? Or does that beeping mean something entirely different? But yeah there is no voice callout.
@Ares1378

**Comment by Gian85** [comment]
the beeping you hear is the marker beacon, I also hear the call "minimum", can you tell me what you put in the mcdu exactly?@NickyNiclas

**Comment by Gian85** [comment]
The sound that you hear is the marker, in addition to the call "minimum" there is the call "100 above" .... so I don't know if I'm wrong or there aren't these two calls.

**Comment by NickyNiclas** [comment]
@Gian85, TIL. I had no idea about the VHF marker beacon but that makes sense, it just happened at the time when I would expect to hear "minimums" which made me think they had used the wrong sound for minimums.
For the configuration I only filled out the ILS approach plan and the approach phase performance for the landing, nothing else.

**Comment by Gian85** [comment]
the markers are not present in all the runways and they are independent from the minimum call so there is no error in this sense, the minimums depend on the GPWRS.

**Comment by Ares1378** [comment]
There should be a minimums call out at the DDA/DA and a 100 above call. 
![image](https://user-images.githubusercontent.com/70821584/94024240-ca4c6e00-fd7c-11ea-8f0e-e9811e481360.png)

Ares

**Comment by Gian85** [comment]
On landing
The GPWS also warns the distance from the ground during landing with:

"Twenty-Five Hundred": We are located at 2500 feet at ground level
"Two Thousand": You are at 2000 feet at ground level
"Fifteen Hundred": We are located 1500 feet at ground level
"One Thousand": You are 1000 feet at ground level
"Five Hundred": You are located 500 feet at ground level
"Four Hundred" We are located 400 feet at ground level
"Approaching minimums": You are 100 feet above the decision height
"Three Hundred" We are located 300 feet at ground level
"Minimums": The decision height has been reached
"Two Hundred": You are located 200 feet at ground level
"One Hundred": You are 100 feet at ground level, indicate to deactivate Autothrottle
"Fifty": You are located 50 feet at ground level
"Forty": We are located 40 feet at ground level
"Thirty": You are 30 feet above ground level
"Twenty": You are located 20 feet at ground level
"Retard": Indicates to position the throttle at minimum
"Ten": You are 10 feet at ground level

**Comment by Ares1378** [comment]
Where are you getting this info? please post your reference

**Comment by Ares1378** [comment]
These callouts are not a function of the GPWS. They are a function of the FWC using RA1 and 2 or if a failure of 1 RA occurs the system will use the working RA and is displayed on both PFDs.... GPWS MODES 1-5 Do the following:
![image](https://user-images.githubusercontent.com/70821584/94055267-51600d00-fda2-11ea-8189-a1e295d90a29.png)
![image](https://user-images.githubusercontent.com/70821584/94055308-62108300-fda2-11ea-917f-57d226cdca18.png)
![image](https://user-images.githubusercontent.com/70821584/94055354-748abc80-fda2-11ea-8802-4819c064d27f.png)
![image](https://user-images.githubusercontent.com/70821584/94055400-7d7b8e00-fda2-11ea-8b87-e8fb92367e1f.png)
![image](https://user-images.githubusercontent.com/70821584/94055437-908e5e00-fda2-11ea-9dff-34168dcf654d.png)
![image](https://user-images.githubusercontent.com/70821584/94055585-c59ab080-fda2-11ea-9f98-92dfc94eb821.png)
![image](https://user-images.githubusercontent.com/70821584/94055602-cf241880-fda2-11ea-860e-8a3ca5697f3b.png)


The associated O Procedure for the modes of the GPWS that have been MEL'd none of which require the PM to callout RA callouts for Height above ground:
![image](https://user-images.githubusercontent.com/70821584/94055631-dd723480-fda2-11ea-9819-f5803ac749a6.png)

THE FWC DOES THE FOLLOWING:
![image](https://user-images.githubusercontent.com/70821584/94055875-21653980-fda3-11ea-983f-ea6ca3c58064.png)
![image](https://user-images.githubusercontent.com/70821584/94055920-2f1abf00-fda3-11ea-8cb5-ddbedb5c417f.png)

**Comment by AdenFlorian** [comment]
do this work in the vanilla unmodded game?

**Comment by Ares1378** [comment]
@AdenFlorian it does not work in the vanilla game

**Comment by hotshotp** [comment]
Minimums call is now being worked on
