### ISSUE TITLE
Passengers seats are oriented backwards

### ISSUE THREAD

**Issue by EasyNetDev** [flybywiresim/a32nx#8082]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2023-06-19T14:24:58+00:00",
    "ref": "refs/heads/master",
    "sha": "f862deb4db29cd6faf819c30d3f9cc7c761aa3c5",
    "actor": "lukecologne",
    "event_name": "manual",
    "pretty_release_name": "master:f862deb4",
    "version": "v0.10.0-dev.f862deb"
}
```

### Describe the bug

When you fly with the drone around the airplane you will notice that passengers seats are oriented backwards.

![20230620155203_1](https://github.com/flybywiresim/a32nx/assets/1823016/773e7abb-8c1e-4db5-8449-d65b45162ffe)
![20230620155234_1](https://github.com/flybywiresim/a32nx/assets/1823016/03396c59-d480-4ad8-aa39-c8c5b81f41e3)

### Expected behavior

Seats should be oriented forward.

### Steps to reproduce

1. Start a simulation
2. Use drone camera and fly around the plane.

**Comment by tracernz** [comment]
Duplicate https://github.com/flybywiresim/a32nx/issues/4207
