### ISSUE TITLE
[BUG]when opening the atc the game crashes

### ISSUE THREAD

**Issue by massi72** [flybywiresim/a32nx#809]
**Mod Version**

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Discord username (if different from GitHub):

**Comment by wpine215** [comment]
There is a template for a reason. Please make a new issue and fill it out in its entirety as there is absolutely no way we can confirm or even fix bugs without a detailed description.
