### ISSUE TITLE
[BUG] Coherent GT Draw limitation from ND

### ISSUE THREAD

**Issue by LissomPineapple** [flybywiresim/a32nx#816]
**Mod Version**
Master Sep 22/2020 0205 UTC

**Describe the bug**
Sudden drop in frames may occur. Problem associated with NAV display. Frames drop from 50+ (mainthread limited) to 20 (Coherent GT Draw limited). Switching to PLAN view on the NAV display results in normal operation. Switching back to any other NAV display results in Coherent GT Draw limitation again. Outside view functions as normal.

**To Reproduce**
1. Happened every time flying from CYYZ-MMMX upon short final at MMMX
2. Happened upon takeoff from CYVR
3. Difficult to determine exactly when this happens.

**Expected behavior**
No Coherent GT Draw limitation expected. 

**Actual behavior**
Coherent GT Draw limitation occurs

**References**
![inside](https://user-images.githubusercontent.com/71742527/93956492-32f90380-fd07-11ea-9ed4-be3e0edf96eb.PNG)
![outside](https://user-images.githubusercontent.com/71742527/93956501-37bdb780-fd07-11ea-8628-851ccd115763.PNG)
![PLAN](https://user-images.githubusercontent.com/71742527/93956506-3c826b80-fd07-11ea-943a-1db750f9e745.PNG)
![ARC](https://user-images.githubusercontent.com/71742527/93956572-5ae86700-fd07-11ea-9651-bccb3a897395.PNG)

**Additional context**
My PC specs are adequate:
1. i7-10700k @ 5.1 GHz
2. RTX 2080 Super OC @ 1960 MHz
3. 32 GB DDR4 3600 MHz ram 

Discord User: ShadwNova

**Comment by NathanInnes** [comment]
When this happens is your MCDU in APP phase?

**Comment by LissomPineapple** [comment]
> When this happens is your MCDU in APP phase?

Was not for this particular flight; happened on takeoff. I will try again either tonight or tomorrow and check.
It is possible that on short final at MMMX it was in APP phase.

**Comment by nikotina91** [comment]
disabling the vfr map in the top bar fixed it for me, used to appear after a couple of hours in flight no matter the destination, haven't had the problem ever since

**Comment by LissomPineapple** [comment]
> disabling the vfr map in the top bar fixed it for me, used to appear after a couple of hours in flight no matter the destination, haven't had the problem ever since

Thanks for that suggestion. I saw this on the MSFS forum. The VFR map was actually turned off when this glitch occurred.

**Comment by LissomPineapple** [comment]
Hi All. Issue does not appear to be associated with this mod. Certain approaches into MMMX resulted in two adjacent waypoints connected by a path which travels more than halfway around the world. This must have triggered the CoherentGTDraw.  A different approach into MMMX fixed this issue.
