### ISSUE TITLE
AP goes into a rapid descent midflight

### ISSUE THREAD

**Issue by Simulator4515** [flybywiresim/a32nx#817]
**Mod Version**

Latest Master Branch

**Describe the bug**

During midflight, the A320 Autopilot rapidly descends to -10k fpm for several seconds before pulling back up rapidly towards normal cruising altitude. This happened on a flight I attempted two separate times from KRIC to KMCO; FPLN: KRIC/02 HPW V213 MAZON IGARY LPERD OMN LEESE2 KMCO/18R; happens right before LPERD waypoint. Also notable that the speed tape goes awry during the incident.

**To Reproduce**

1.Flight Plan KRIC-KMCO
2.Take-OFF
3.Cruise/right before LPERD this occurs

**Expected behavior**

To remain at cruising altitude without a random nosedive.

**Actual behavior**

Aircraft quickly descends into a 10k+ fpm descent for several seconds before going back to cruise level

**References**

[![Image from Gyazo](https://i.gyazo.com/8a702c5ac3d19f34c9bf2113881f0cc1.jpg)](https://gyazo.com/8a702c5ac3d19f34c9bf2113881f0cc1)

[![Image from Gyazo](https://i.gyazo.com/f0be4f0c6abd13bc7ac415a071e09585.jpg)](https://gyazo.com/f0be4f0c6abd13bc7ac415a071e09585)

**Additional context**

The first flight attempt happened on 9/22 latest master branch on that night. second attempt 9/23 with the latest master branch that night; I flew with no issues for the past few weeks on any given master branch update before these two nights. Last stable flight was on 9/20 from KORD to KACY.

Discord username (if different from GitHub): same as GitHub

**Comment by ShiforGitHub222** [comment]
Can confirm I'm having the same issue. Just tried a flight from EGLL to EDDF and over the channel the speed indicator died and the plane trimmed the nose all the way down and entered a dive, I recovered by resetting the trim and bringing the plane back into a steady climb, only for the same bug to repeat itself a minute later. Occured at around FL220.

**Comment by NathanInnes** [comment]
Here's my theory:

The IAS Probe froze with ice, PFD loses IAS and Ottopilot tries to compensate

**Comment by NickyNiclas** [comment]
This has occurred for me when the petot froze so I would agree with Nathan. Airspeed showing 0 is the giveaway.

**Comment by Pixel1191** [comment]
The default auto-mode for the pitot anti-ice is not working as it should.

Turn it on manually and this won't happen.

**Comment by Simulator4515** [comment]
Alright thanks guys. I didn't think anything of that before cause I have had it freeze over in the past without that behavior.
