### ISSUE TITLE
Thrust seems low[BUG]

### ISSUE THREAD

**Issue by PGTV9** [flybywiresim/a32nx#824]
**Mod Version**

1.8.3

**Describe the bug**

Aircraft has a really hard time climbing. I believe thrust is too low.

**To Reproduce**

1.Go to FL300 and try to climb FL380 at V/S of 1000 engines do not have enough power to maintain speed
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Discord username (if different from GitHub):

**Comment by ultranoobian** [comment]
Just as a sanity check for incorrect configuration of auto-throttle/auto-pilot, the throttle is in a non-reduced thrust position (ala in CLIMB, FLEX/MCT or TOGA)?

**Comment by aboodilatif** [comment]
Had this issue while flying last night [UTC:1900] on live weather from KDEN - KLAS. After FL250 the aircraft struggles to climb above 900fpm, and after FL300 the V/S was almost down to 600fpm. Throttles were on CL for the whole flight, double and triple checked my throttle positions. 
Wasn't sure if this was a "corrected" version, but the thrust feels way less that the master files a week ago

**Comment by fourdragons** [comment]
Can confirm as well. Higher altitudes it really struggles, now.

**Comment by jacf182** [comment]
I feel it this way too when taking off from SEQM (8000 feet rwy elevation). Setting up a flexmax or 64 like the calculator tells me. Initiao climb is way too low, struggling to stay at 160/170. I have to decrease flaps way early to gain some speed.

**Comment by PCGamesF1Tech** [comment]
Hi,
what was the gross weight of the aircraft?
60836kg? (indication bug, doesn't change with fuel burn)
Is the GW calculated correctly within the sim (so the GW on SD is just a fixed text for now)?
Flex 64 and 8000ft elevation is also a rather demanding combination. At what OAT? Although 60t is quite a light weight... 
How long is the runway?

**Comment by DanielBosi1977** [comment]
Realmente Impuxo muito baixo acima de FL300 ele quase para!!!

**Comment by jacf182** [comment]
> Hi,
> what was the gross weight of the aircraft?
> 60836kg? (indication bug, doesn't change with fuel burn)
> Is the GW calculated correctly within the sim (so the GW on SD is just a fixed text for now)?
> What climb speed? Around .77/78 or .80?
> 
> Flex 64 and 8000ft elevation is also a rather demanding combination. At what OAT? Although 60t is quite a light weight...
> @aboodilatif
> Flex is for takeoff only, shouldn't alter the inflight performance in any way
> 
> And FYI:
> Even the 747 (-400 and - 8) IRL had troubles departing from MEX (~7000ft elevation).
> High altitude and high temperature (high DA) is just not helpful for climb performance.
> A few degrees temp more or a few knots less headwind and the MATOW was reduced by a few tons(!)

Don't have the exact GW, but fuel was about 12000 LBS and the payload about 40000 LBS, so not too heavy.
Flex calculations were done via [http://wabpro.cz/A320/](url) with flaps 1.

**Comment by AdenFlorian** [comment]
when did this issue start happening?

is it a problem in the vanilla unmodded game?

**Comment by DanielBosi1977** [comment]
Pode ser que o problema seja do Jogo mesmo, não sei...começou faz pouco tempo, talvez depois da atualização...
