### ISSUE TITLE
IR'S should have no Align Light [BUG]

### ISSUE THREAD

**Issue by Ares1378** [flybywiresim/a32nx#828]
**Mod Version**

Master

**Describe the bug**

This model of the ADIRS panel should not have an align light for the IR's. Only FAULT and OFF

**To Reproduce**

1.Load in and place IR selector into NAV - the Align Light comes on (there should be no Align Light, only Fault and OFF)
2.
3.

**Expected behavior**

The fault light will come on for a second and then extinguish when placing the respective IR switch into NAV

**Actual behavior**

**References**

![image](https://user-images.githubusercontent.com/70821584/94096470-c9055a80-fde9-11ea-95c6-d991791e2e56.png)

**Additional context**

Discord username (if different from GitHub):

**Comment by tareksabet** [comment]
plus the On Bat thing but from what I heard it's still need to be modeled

**Comment by lukecologne** [comment]
More or less fixed in #1355, the align light is not lighting up anymore, but it hasn't been replaced yet with an off emissive, since we can't edit the model.
