### ISSUE TITLE
When AP is disengaged vertical FMA reverts to CLB[BUG]

### ISSUE THREAD

**Issue by Ares1378** [flybywiresim/a32nx#829]
**Mod Version**

Master

**Describe the bug**

If you are in OP CLB or G/S captured with AP engaged and you disengage the AP the vertical mode reverts to CLB. 
Also, if you do not have the AP engaged you can only be in CLB mode. 

**To Reproduce**

1.Take off with out AP try to use OP CLB by pulling the ALT knob on the FCU
2. Disengage the AP while doing an ILS or in OP CLB and it will revert to CLB mode.
3.

**Expected behavior**

It should not revert to CLB mode when AP is disengaged also you should be able to use selected modes without the AP engaged. 

**Actual behavior**

**References**

**Additional context**

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
logic for OP CLB

```js
static IsActive_OPCLB() {
    if ((Simplane.getAutoPilotAltitudeSelected() || Simplane.getAutoPilotAltitudeArmed()) && Airbus_FMA.CurrentPlaneState.anyFlightDirectorsActive && Airbus_FMA.CurrentPlaneState.anyAutoPilotsActive) {
        let targetAltitude = Simplane.getAutoPilotAltitudeLockValue("feets");
        let altitude = Simplane.getAltitude();
        if (altitude < targetAltitude - 100) {
            return true;
        }
    }
}
````

**Comment by MisterChocker** [comment]
using this issue for tracking instead #1981
