### ISSUE TITLE
Nav lights/ Beacon & Strobe

### ISSUE THREAD

**Issue by Hamiltonoshane** [flybywiresim/a32nx#830]
I watched youtube for 320NEO and i noticed different video and in sim and it not enough brighten reflect against ground for example this video and also for strobe it very powerful and bright but in sim it not really brighten 

https://www.youtube.com/watch?v=YUA-yvz_DNA

**Comment by NathanInnes** [comment]
![image](https://user-images.githubusercontent.com/18389085/94132701-909c6580-fe57-11ea-95a9-72b8586903ab.png)
This looks close to what's in the sim for me for the nav lights.

**Comment by NathanInnes** [comment]
Going to close this issue for now.

**Comment by Hamiltonoshane** [comment]
What about wing view from back wing it didnt show strobe much compare to engine wing
