### ISSUE TITLE
[REQUEST] Autolanding and CATII & CATIII

### ISSUE THREAD

**Issue by imkow** [flybywiresim/a32nx#831]
**Mod Version**

Master

**Describe the bug**

using flight plan in MCDU, it can detect and show CAT II or CAT III and LAND status, and autoland, but not without flight plan in MCDU and ILS frequency only in RadioNav page (it can detect LOC and G/S, and approach, but cannot activate CAT status and LAND mode above 350ft), tested at PAKT.

**To Reproduce**

1. No plan before take off, in flight, just input ILS frequency in the RadioNav page of MCDU

2. Manually intercept Loc and G/S
3. Activate APPR and AP

**Expected behavior**

Follow plan in MCDU it can detect CAT II or CAT III and autoland, but not the scenario I described.
I don't know if this is a bug, just ask what's the behavior of real A320 neo.

**Actual behavior**

**References**

**Additional context**

**Comment by Ares1378** [comment]
Please describe the bug.....? and no you cannot activate an autoland in the MCDU

**Comment by Ares1378** [comment]
I am not understanding the issue that you are having. The aircraft will perform an autoland as long as the aircraft is not downgraded to CAT1 as an autloand with a CAT1 FMA is not authorized.

**Comment by imkow** [comment]
@Ares1378 just some typos, corrected the question

**Comment by Ares1378** [comment]
Yes and I am still not understanding what the point of this post was. This is for actual bugs to be reported, you are simply asking a question about the automation of the aircraft. If you have questions about the aircraft systems please join the discord and someone can help you there. https://discord.gg/rmGJwA

**Comment by Ares1378** [comment]
Autloand is not a function of the MCDU, the aircraft will autloand as long as it is not downgraded to CAT1 and the required systems are available for an autoland and an ILS is being performed.

**Comment by imkow** [comment]
@Ares1378 I know, but it cannot be activated when I don't input plan in MCDU, just input ILS frequency before land, not very late, off course

**Comment by Ares1378** [comment]
As long as you engage the APPR pb and have an ILS freq in the box you should have atleast a CAT3 SINGLE FMA which allows an autolan. Currently the Autoland function is bugged due to the FLARE mode not working properly

**Comment by imkow** [comment]
@Ares1378 yes, yes. I'm not talking about the imperfect of autoland function. I'm talking about the behaviors are different between using flight plan in MCDU and input ILS frequency only during flight before land. 

using flight plan in MCDU, it can detect CAT II or CAT III and airplane, but not without flight plan in MCDU and ILS frequency only in RadioNav page (it can detect LOC and G/S, and approach, but cannot activate CAT display and LAND above 350ft), tested at PAKT.

**Comment by lionomega** [comment]
I do not know if it is the same problem but in my case if you are in flight and TC gives you the ILS information and you enter it immediately in MCDU, the plane makes a 180 degree turn and takes the wrong direction

**Comment by imkow** [comment]
@lionomega not same problem

**Comment by angry-bender** [comment]
CAT III Autoland is working, but on minimums, it does smash you down
