### ISSUE TITLE
[BUG] Not loading into Sim, only showing base version

### ISSUE THREAD

**Issue by mynottt** [flybywiresim/a32nx#832]
**Mod Version**

up to date version as of 24/09/2020

**Describe the bug**

Based model only loading into sim. Folder correctly installed.

**To Reproduce**

1. as above. Copied into folder (AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\Community\A32NX)
2.
3.

**Expected behavior**

![A320NX](https://user-images.githubusercontent.com/71814013/94118044-e0bdfc80-fe44-11ea-8ed8-bbb589c04a4d.png)

**Actual behavior**

**References**

**Additional context**

Discord username (if different from GitHub):

**Comment by NathanInnes** [comment]
Make sure inside the A32NX folder it looks like this 
![image](https://user-images.githubusercontent.com/18389085/94127578-018c4f00-fe51-11ea-8a3c-4b9d59d3e404.png)

**Comment by mynottt** [comment]
![A320NX](https://user-images.githubusercontent.com/71814013/94128273-d81ff300-fe51-11ea-86b8-598c93fb2ba2.png)
see image attached.

Currently, this folder works fine with the livery pack but not sure if that could be corputing it?

**Comment by mynottt** [comment]
thanks for your help.

**Comment by NathanInnes** [comment]
Are you saying the mod works without the liveries?

**Comment by mynottt** [comment]
Neither currently. I have no idea why...... the instructions for install are really simple so not sure if it is anything to do with my file path?

**Comment by Benjozork** [comment]
> Based model only loading into sim

Did you actually not see the modifications in-game or are you basing it off only seeing one A320neo on the aircraft selector ? Because as we state in the README, the mod replaces the default A320neo.

**Comment by mynottt** [comment]
no modifications showing in-game. When starting from cold it is still the same, unfortunately.

**Comment by DaBeLG** [comment]
Same issue today after installing livery’s the FlyByWire mod is not working no batt 1 & batt 2 master switch are working.

Only can load default a320 neo with dev mode select airplane and then bedault plane is also working.

Also got random mfd screen dimming when close to airports ILS ? ( got it with default plane also )

**Comment by AdenFlorian** [comment]
@DaBeLG see #718

Also, until the next asobo patch, I recommend flying with all multiplayer, ai, and ground traffic off

**Comment by DaBeLG** [comment]
@AdenFlorian  Thnx this worked for me . still lot off bugs in this game 

- [x]

**Comment by NathanInnes** [comment]
@mynottt did the above solve your issue?
