### ISSUE TITLE
SPEED AND PITCH BEHAVE WHILE FLAP EXTENDED[BUG]

### ISSUE THREAD

**Issue by patrickferrariuk** [flybywiresim/a32nx#834]
**Mod Version**
Master

**Describe the bug**
After take-off the A/THR or manual speed select won't follow the correct speed or pitch however when flaps are retracted the aircraft will behave normally. The same happen before land when flaps are extended, aircraft won't follow the correct speed and pitch.

**To Reproduce**

1. Flap selected
2. A/THR or Manual speed are not followed by aircraft
3. Aircraft pitches down even though on PFD shows is climbing
4. When flaps are retracted aircraft behave normally
5. Same happens before landing, once flaps are extended aircraft won't follow the right speed/pitch

![image](https://user-images.githubusercontent.com/71822674/94246816-1ed62180-ff14-11ea-8401-2bbcada01f5d.png)

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Discord username (if different from GitHub):

**Comment by Berniep94** [comment]
I got the same issue, when flaps are set add extream drag, even on approach i set flaps 2 and AP just pitch the nose waaaaay to down, but the aircraft dosent loose any altitude, just pitch extremely down.

**Comment by AdenFlorian** [comment]
Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

**Comment by patrickferrariuk** [comment]
Yes, no addons or modifications in the sim. Just using A32NX master version. Before MSFS last update it was working fine, happen all after the update.

**Comment by hotshotp** [comment]
has been fixed
