### ISSUE TITLE
[BUG] After landing, switching on the APU causes electrical problem

### ISSUE THREAD

**Issue by cintula187** [flybywiresim/a32nx#835]
**Mod Version**
master

**Describe the bug**
after landing. i have turned on the APU then all of the displays turned off and the engines almost were shut off for a few seconds. Then it came back online.
is there something going on with the APU / electric systems?
i did not do anything weird. left the runway turned on the apu
and the aircraft reacted like i shut downed the engines and the plane stayed without electricity

**To Reproduce**

1. land
2. leave runway
3. turn on APU

**Expected behavior**
I have expected a turned on APU

**Actual behavior**
Te aircraft reacted like i shut downed the engines and the plane stayed without electricity. All of the displays, onboard lights turned off

Dave

**Comment by tareksabet** [comment]
Good evening @cintula187, I did the steps as you did and to confirm to you on my side nothing happened .
Can you tell me which version of the mod are you on and plus if it happened again to you can you take couple of screenshots that would help the devs more.

**Comment by AdenFlorian** [comment]
please try all multiplayer, ai, and ground traffic turned off/set to 0.

**Comment by hotshotp** [comment]
no longer reproduceable
