### ISSUE TITLE
BRT adjust button washes out cyan component of MCDU

### ISSUE THREAD

**Issue by speedwaystar** [flybywiresim/a32nx#836]
**Mod Version**

master

**Describe the bug**

with every click of the BRT button the cyan text gradually becomes more and more washed out until it approaches pure white.

**To Reproduce**

1. click the BRT button repeatedly
2. notice that the cyan text becomes increasingly difficult to distinguish from the white text, as more and more white component is added to it.

**Expected behavior**

All the MCDU colours including cyan should become clearer and brighter without losing their distinct hue, as below:
![expected maximum brightness](https://i.imgur.com/EA9OG6h.png)

**Actual behavior**

The cyan component of the MCDU becomes more and more difficult to distinguish as it approaches pure white.
![minimum brightness](https://i.imgur.com/hymftKr.png)
![default brightness](https://i.imgur.com/GdQqy7G.png)
![maximum brightness](https://i.imgur.com/Iizv0PU.png)

**References**

![expected maximum brightness](https://i.imgur.com/996l7YS.png)

**Additional context**

Discord username (if different from GitHub):

**Comment by AdenFlorian** [comment]
please use IRL photo references for this type of issue

**Comment by speedwaystar** [comment]
https://www.youtube.com/watch?v=hzknF9qIUm4

**Comment by speedwaystar** [comment]
seems to have been addressed in this patch: 

@@ -105,16 +105,16 @@ a320-neo-cdu-main-display::after {
  color: white; }

.blue {
  color: #99ceff; }
  color: #00ffff; }

.yellow {
  color: #f9dd02; }

.green {
  color: #1daa05; }
  color: #00ff00; }

.red {
  color: #ff886d; }
  color: #ff9a00; }

https://github.com/flybywiresim/a32nx/commit/23d6f4b340761f9c74a060ef3a8d4f2b3d84025c

![](https://i.imgur.com/0iMPuJJ.png)

nice work
