### ISSUE TITLE
[BUG] Autopilot Stuck at 5000 feet

### ISSUE THREAD

**Issue by billyinlasvegas** [flybywiresim/a32nx#839]
**Mod Version**

Master

**Describe the bug**

Autopilot is stuck at 5000 feet, can't get it to change

**To Reproduce**

1. Start any flight with A320
2. Try to change AP altitude

**Expected behavior**

Should be able to adjust AP altitude

**Actual behavior**

Button turns and clicks but nothing changes

**References**

Here's a video
[https://streamable.com/6f3m0k](url)

**Additional context**

Discord username (if different from GitHub):Billyinlasvegas

**Comment by AdenFlorian** [comment]
Can you try with multiplayer, ai, and ground traffic all set to off/0? Might be linked to last assobo patch the ghost plane issues

**Comment by MylesKingsnorth** [comment]
Think this is the same issue [https://github.com/flybywiresim/a32nx/issues/810](https://github.com/flybywiresim/a32nx/issues/810) appears to be non-related to this mod

**Comment by AdenFlorian** [comment]
duplicate of #810

**Comment by billyinlasvegas** [comment]
Looked at #810 and was able to fix with a clean install, thanks for the help!!
