### ISSUE TITLE
[BUG] Only one Waypoint at a time 

### ISSUE THREAD

**Issue by tareksabet** [flybywiresim/a32nx#840]
**Mod Version**

Master, latest one

**Describe the bug**

I can only put one waypoint and it does not appear the name of it 

**To Reproduce**

1.cold & Dark 
2.entering F-PLN , Airways 
3. enter waypoints 

**Expected behavior**

to be able to enter multiple waypoints 

**Actual behavior**

I can only put one waypoint and it does not appear the name of it 

**References**

![Desktop Screenshot 2020 09 24 - 15 45 20 90](https://user-images.githubusercontent.com/70240330/94167189-83e63480-fe8c-11ea-9d01-aaee3737e6bc.png)
![Desktop Screenshot 2020 09 24 - 15 45 28 33](https://user-images.githubusercontent.com/70240330/94167234-8e083300-fe8c-11ea-9932-6d73c1e3654b.png)
![Desktop Screenshot 2020 09 24 - 15 45 35 50](https://user-images.githubusercontent.com/70240330/94167249-9496aa80-fe8c-11ea-8eab-ca79f1301bf4.png)

**Additional context**

tarek_sabet#7946 (if different from GitHub):

**Comment by AdenFlorian** [comment]
Can confirm, saw this last night.

**Comment by Aarondodd88** [comment]
Able to reproduce this also

**Comment by AdenFlorian** [comment]
fixed by #844
