### ISSUE TITLE
[BUG] ND ILS mode 

### ISSUE THREAD

**Issue by tareksabet** [flybywiresim/a32nx#841]
**Mod Version**

Master, latest one

**Describe the bug**

showing the route in the ND ILS mode 

**To Reproduce**

1. Enter a route in the MCDU 
2. switch ND mode to ILS

**Expected behavior**

 the route must be disappeared on ILS mode plus the ILS bar should be filled not empty 

**Actual behavior**

showing the route in the ND ILS mode 
**References**

![Desktop Screenshot 2020 09 24 - 16 18 58 01](https://user-images.githubusercontent.com/70240330/94168171-a3319180-fe8d-11ea-8fb3-078e5c2b79cb.png)

**Additional context**

tarek_sabet#7946 (if different from GitHub):

**Comment by 2hwk** [comment]
I may look into this when I have time as part of a ND overhaul
