### ISSUE TITLE
[BUG] ND VOR Mode 

### ISSUE THREAD

**Issue by tareksabet** [flybywiresim/a32nx#842]
**Mod Version**

Master, latest one

**Describe the bug**

showing the route in the ND VOR mode 

**To Reproduce**

1. Enter a route in the MCDU 
2. switch ND mode to VOR 

**Expected behavior**

the route must be disappeared on VOR mode plus the VOR bar should be filled not empty 

**Actual behavior**

showing the route in the ND VOR mode 

**References**

![Desktop Screenshot 2020 09 24 - 16 19 03 04](https://user-images.githubusercontent.com/70240330/94169010-8b0e4200-fe8e-11ea-80fd-92b77393c991.png)

**Additional context**

tarek_sabet#7946 (if different from GitHub):

**Comment by lukasrz** [comment]
Yes VOR it's not working at all! When I put VOR freq to MCDU it not show direction to VOR and distance (DME) Only VOR name is showed on PFD.

**Comment by NathanInnes** [comment]
#885 should fix this issue I think

**Comment by MisterChocker** [comment]
this has been fixed
