### ISSUE TITLE
[BUG] wrong appearance of ALT CRZ on the FMA 

### ISSUE THREAD

**Issue by tareksabet** [flybywiresim/a32nx#843]
**Mod Version**

Master, latest one

**Describe the bug**

it shows ALT CRZ on the FMA when descending and getting to an altitude lower than the CRZ level 
ex: descending to FL110 and showing ALT CRZ when maintaining the Altitude   

**To Reproduce**

1.start the flight
2. insert the CRZ LEVEL on the MCDU, start the flight
3. start descent i.e : FL110 and you're going to find ALT CRZ

**Expected behavior**

after the descent to FL110 it should appear ALT not ALT CRZ 

**Actual behavior**

after the descent to FL110 it shows ALT CRZ 

**References**

![Desktop Screenshot 2020 09 24 - 16 26 54 76](https://user-images.githubusercontent.com/70240330/94180452-50140a80-fe9e-11ea-9eaf-d111d6ee0875.png)

**Additional context**

tarek_sabet#7946 (if different from GitHub):

**Comment by PCGamesF1Tech** [comment]
At what distance from your destination?

**Comment by tareksabet** [comment]
> At what distance from your destination?
@PCGamesF1Tech at least 50 NM

**Comment by AdenFlorian** [comment]
i beleive this might be tied to the plane being stuck in CRZ phase

**Comment by AdenFlorian** [comment]
linked to #825 most likely, which im starting work on now
