### ISSUE TITLE
[BUG] Strobe lights always on in AUTO

### ISSUE THREAD

**Issue by ukflyer** [flybywiresim/a32nx#845]
**Mod Version**
latest master files

**Describe the bug**
Strobe lights in AUTO are always on 

**To Reproduce**

1. Select strobes to AUTO when starting up

**Expected behavior**
The AUTO position causes the strobe lights to illuminate automatically when the main gear shock absorbers are not compressed. 

**Actual behavior**
Strobe lights in AUTO always on

**References**

**Additional context**

Discord username (if different from GitHub):

**Comment by AdenFlorian** [comment]
was this ever working before? does this issue exist in the vanilla unmodded game?

**Comment by ukflyer** [comment]
Hi - just tested without mod -- the strobes in AUTO don't show when starting up  (just flicking on external power)

**Comment by AdenFlorian** [comment]
@wpine215 has confirmed this is an issue

**Comment by UncleClapton** [comment]
Starting work on this now.

**Comment by AdenFlorian** [comment]
working on a fix
