### ISSUE TITLE
[BUG] AP Speed selector uses Knots to calculate Mach

### ISSUE THREAD

**Issue by camilo625** [flybywiresim/a32nx#847]
**Mod Version**
master (24/9/2020)

**Describe the bug**

The speed selector for the AP uses a speed in knots to calculate the Mach speed

**To Reproduce**

1. Takeoff and select mach speed

**Expected behavior**

When selecting Mach, every click of the knob should translate in .01 mach

**Actual behavior**

Every click of the knob translates in 1 knot (can be seen on the tooltip) and then its converted to mach
![image](https://user-images.githubusercontent.com/38522306/94193292-8f366180-fe86-11ea-9e8d-544ab3813d47.png)

**References**

**Additional context**

Discord username (if different from GitHub): Camilo625#5575

**Comment by lousybyte** [comment]
This seems to be fixed?

![alt text](https://i.postimg.cc/15ZHV3b2/Screenshot-2020-10-05-124653.png)
