### ISSUE TITLE
[BUG]Autopilot doesn‘t work

### ISSUE THREAD

**Issue by Mischa1414** [flybywiresim/a32nx#848]
**Mod Version**

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by wpine215** [comment]
Please respect the issue template and fill it out in its entirety.
