### ISSUE TITLE
[BUG] Pitch down under climbing to Flight Level.

### ISSUE THREAD

**Issue by Middi25X** [flybywiresim/a32nx#851]
**Mod Version**

0.2.0 latest

**Describe the bug**

When i was climbing today suddnly airplane start to pitch down and airspeed disappear for a sec or 2,then it come back and it start climbing again. it was happening 2-3 times.

**To Reproduce**

1. When climb
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by lousybyte** [comment]
Maybe same as https://github.com/flybywiresim/a32nx/issues/817#issuecomment-697284165?

**Comment by Middi25X** [comment]
yes it is ! Thx
