### ISSUE TITLE
[BUG] Autopilot can't be re-engaged

### ISSUE THREAD

**Issue by lrargerich** [flybywiresim/a32nx#852]
**Mod Version**
Master

**Describe the bug**
After activating autopilot if you de-activate it during flight it can't be activated again.

**To Reproduce**
1. Normal manual takeoff
2. Engage AP
3. Disconnect AP with the stick button
4. Try to engage AP again

**Expected behavior**
Autopilot should activate again

**Actual behavior**
Nothing happens.

**References**

**Comment by jooglestumpe** [comment]
Try pressing AP disconnect again, then it should work.

**Comment by hotshotp** [comment]
issue is no longer reproduceable
