### ISSUE TITLE
Speeds are incorrect on take off[BUG]

### ISSUE THREAD

**Issue by Ares1378** [flybywiresim/a32nx#855]
**Mod Version**

**Describe the bug**

Managed speed bug is stuck at S speed once out of SRS mode.

**To Reproduce**

1. Takeoff
2.
3.

**Expected behavior**

Once out of SRS (managed speed of V2+10) aircraft should begin its acceleration to 250knots if below 10k MSL or what is selected

**Actual behavior**

**References**

Please refer to the following video.
https://www.youtube.com/watch?reload=9&v=ECV3IBkzZLc

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment]
fixed
