### ISSUE TITLE
ND Pseudo Waypoints

### ISSUE THREAD

**Issue by Ares1378** [flybywiresim/a32nx#856]
**Mod Version**

Master

**Describe the bug**

Pretty much all of these items are missing on the ND besides the TOC and TOD items. 

**To Reproduce**

1. go for a flight from point a to point B
2.
3.

**Expected behavior**

The following items should be displayed on the ND for the following reasons:
![image](https://user-images.githubusercontent.com/70821584/94207440-3ddda080-fe8d-11ea-8de8-0b6e206f86aa.png)
![image](https://user-images.githubusercontent.com/70821584/94207472-4cc45300-fe8d-11ea-8568-c4726f6d4aea.png)
![image](https://user-images.githubusercontent.com/70821584/94207490-5948ab80-fe8d-11ea-8723-449488a46206.png)
Better look at the symbols BUT PLEASE REFER TO THE DOCUMENTS ABOVE FOR DESCRIPTION:
![image](https://user-images.githubusercontent.com/70821584/94207774-f4da1c00-fe8d-11ea-9c6b-22437fd539cb.png)
![image](https://user-images.githubusercontent.com/70821584/94207809-07545580-fe8e-11ea-803e-91f499351620.png)
![image](https://user-images.githubusercontent.com/70821584/94207876-2c48c880-fe8e-11ea-98d0-044676746df7.png)
![image](https://user-images.githubusercontent.com/70821584/94207894-3965b780-fe8e-11ea-81e0-38eb6647e85d.png)
![image](https://user-images.githubusercontent.com/70821584/94207911-4a162d80-fe8e-11ea-93f7-169184a99dcb.png)
![image](https://user-images.githubusercontent.com/70821584/94207937-58fce000-fe8e-11ea-8641-94e79cb2c7b2.png)
![image](https://user-images.githubusercontent.com/70821584/94208139-c446b200-fe8e-11ea-90d9-ee1908f8f591.png)
![image](https://user-images.githubusercontent.com/70821584/94208153-cf014700-fe8e-11ea-86c5-55b17d95faba.png)
![image](https://user-images.githubusercontent.com/70821584/94208183-da547280-fe8e-11ea-8651-18021749fb56.png)

BELOW ARE THE CORRECT MCDU PERF PAGE PHASE CHANGES:

![image](https://user-images.githubusercontent.com/70821584/94207548-6b2a4e80-fe8d-11ea-9ce1-4d333402c29a.png)
![image](https://user-images.githubusercontent.com/70821584/94207565-754c4d00-fe8d-11ea-9263-61eb639a8f61.png)

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by tellurics** [comment]
Any updates so far?

**Comment by Benjozork** [comment]
This is gonna be part of VNAV and the reworked AP
