### ISSUE TITLE
[BUG] ILS Title on ND Incorrect

### ISSUE THREAD

**Issue by PANAM741** [flybywiresim/a32nx#860]
**Is your feature request related to a problem? Please describe.**

N/A

**Describe the feature you'd like to see implemented**

The APP type annunciator on ND should be in green.

![330D73A2-1E5D-40B2-8751-41A6A3879F03](https://user-images.githubusercontent.com/71863590/94225047-9aef4b80-feb9-11ea-8455-1cb85e09ec84.jpeg)

**References**

![76C4C9C6-293B-4A6F-8A7E-434B9C356CDB](https://user-images.githubusercontent.com/71863590/94225041-94f96a80-feb9-11ea-9251-97563d05ca3f.jpeg)

**Additional context**

Discord username (if different from GitHub):

**Comment by NathanInnes** [comment]
Working on it now

**Comment by Benjozork** [comment]
Also looks like the font size should be consistent across the top of the ND, but that might be for a separate ticket.

**Comment by NathanInnes** [comment]
I'm working on PFD css stuff as well anyways so I will look into what needs done
