### ISSUE TITLE
[BUG] no OVFY (overfly) function on MCDU

### ISSUE THREAD

**Issue by imkow** [flybywiresim/a32nx#869]
**Mod Version**

all

**Describe the bug**

**To Reproduce**

Open F-PLN page in MCDU

Press OVFY Button, so upward facing triangle is in scratchpad

Simply click left LSK (Line Select Key) for the WPT you want to overfly (in this case MTR)

**Expected behavior**

Should work

**Actual behavior**

N/A

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment]
closing since no reference provided

**Comment by foxmike80** [comment]
I don't know if that is reference enough or if it helps re-opening the issue, but here is link describing the function of the ovfy key:
http://www.a320dp.com/A320_DP/nav-flight-management/sys-14.2.14.html

**Comment by MisterChocker** [comment]
Hey, can you please open a new feature request then?
