### ISSUE TITLE
[BUG] Main Panel Floodlight does not work

### ISSUE THREAD

**Issue by ChruutvoLuzi** [flybywiresim/a32nx#873]
**Mod Version**
Latest Master Branch

**Describe the bug**

Main Panel Floodlight does not light up when turning the knob

**To Reproduce**

1. Start a flight
2. Turn the most left knob up underneath the glareshield
3.

**Expected behavior**

It should light up

**Actual behavior**

It, does not

**References**

**Additional context**

Was this working before/when did the issue start occurring?
With Light Improvements

Is this a problem in the vanilla unmodded game?
no

Discord username (if different from GitHub):
ChruutvoLuzi | SD-PB.ch#8902

Screenshot 

https://media.discordapp.net/attachments/314015589595086848/759091167127928953/Desktop_Screenshot_2020.09.25_-_18.36.55.50.png?width=1204&height=677

**Comment by ChruutvoLuzi** [comment]
Update: 

The LEDs light up but there is no actual light flowing out of it

**Comment by GlitchedYT** [comment]
Main panel flood light does not light up the PFD/ND. It is a reading light for the tray table. As of right now the tray table cannot be moved so it only lights up your feet.

**Comment by ChruutvoLuzi** [comment]
Oops just realised that. I think i was used to the way it worked with vanilla where the pfd got lit up aswell 

closing the issue
