### ISSUE TITLE
[BUG] No impact of burning fuel on flight physics

### ISSUE THREAD

**Issue by Alfapilot** [flybywiresim/a32nx#880]
**Mod Version**
Master

**Describe the bug**
Decreasing weight during flight doesnt impact on flight physics (as AOA or Fuel Flow for example).
The displayed GW on the ECAM decreases, but during cruise the plane stays at the same pitch angle from start until the very end. Because of that you cant start a flight with 100% fuel from the departure and execute step climbs while more and more fuel is burned. The change of Gross Weight only impacts on the pitch angle as soon as you manipulate the amount of fuel manually during flight.

**To Reproduce**
1. Start a flight with any amount of fuel  and let the aicraft climb to a logic cruise flight level all by autopilot
2. As soon as you reach the cruise phase pay attention on the pitch angle, fuel flow, engine thrust and stabiliser.
3. Stay at the same flight level and speed all the time and do not jump to any point by the menu or change fuel, just let it fly in realtime.
4. After some time when some fuel has been burned compare the parameters i mentioned at point 2 with the actual ones.

**Expected behavior**
 The pitch angle in cruise should decrease with time and fuel burn, as the aicraft gets lighter and lighter
**Actual behavior**
The pitch angle in cruise doesnt change at all during the whole flight. It only changes when you manipulate the amount of fuel in the menu inflight manually.

Was this working before/when did the issue start occurring?
From the very beginning

Is this a problem in the vanilla unmodded game?
Yes, it is also.

Discord username (if different from GitHub): Alfaheal#9895

**Comment by derl30n** [comment]
Closing since flight dynamics have been improved.
