### ISSUE TITLE
[BUG] Mod has influences on the default Citation CJ4 Jet

### ISSUE THREAD

**Issue by TYR521** [flybywiresim/a32nx#882]
**Mod Version**
Master

**Describe the bug**
When your mod is installed then the Anti-Ice switches on the Cessna Citation CJ4 are always lit, even when Anti-Ice is not active. Sounds crazy i know, but when i remove your Mod the problem is gone.

**To Reproduce**
Install your mod and load the CJ4. Look then at the Anti-Ice switches below the displays, you'll see that they are lit, but Anti-Ice isn't active.

**Expected behavior**
Your mod should only have an impact on the default A320Neo.

**Actual behavior**
Already described above.

**References**
https://imgur.com/G8XxD34

**Additional context**
The issue is also present on the Citation CJ4 mod from fspackages.
https://github.com/Working-Title-MSFS-Mods/fspackages

Was this working before/when did the issue start occurring?
I don't know if this issue is only by the current master branch or if it exist already longer.

Is this a problem in the vanilla unmodded game?
No

TYR521

**Comment by Benjozork** [comment]
Possibly related to this file ?

https://github.com/flybywiresim/a32nx/blob/master/A32NX/ModelBehaviorDefs/Asobo/Common/Subtemplates/Deice_Subtemplates.xml

cc. @UncleClapton

**Comment by TYR521** [comment]
I don't understand Code, sorry, but could be possible, it has at least "de-ice" in its name.

**Comment by Benjozork** [comment]
> 
> 
> I don't understand Code, sorry, but could be possible, it has at least "de-ice" in its name.

Just to clarify: I am commenting this as reference for other contributors, don't worry if you don't understand it !. GitHub is a bit different than your traditional messaging forums 😄

**Comment by TYR521** [comment]
Thank you! :D

**Comment by TYR521** [comment]
I can report that this is now fixed. I Using the current master version of the A32NX and the current CJ4 Mod in version 3.1.

Regards

**Comment by dga711** [comment]
The WorkingTitle CJ4 Mod also receives a lot of complaints about that and we can just redirect them to here.
Please be a good neighbour ;)

**Comment by J-Hoskin** [comment]
Fix it boys, letss goooooooooooooooo

**Comment by TYR521** [comment]
the "Deice_Subtemplates" file is responsible for this problem. The solution for me now is, I've copied the original "Deice_Subtemplates" file from "Official\Steam\fs-base-aircraft-common\ModelBehaviorDefs\Asobo\Common\Subtemplates" to the A32NX Mod and replaced the existing file. This has fixed the issue on the CJ4, and on the A32NX i didn't seen a problem so far.

**Comment by TYR521** [comment]
Found a solution without replacing the "Deice_Subtemplates" file in the A32NX. The Sim loads all mods in the community folder from top to bottom. The A320Neo mod has the folder name "A32NX" and the CJ4 has the name "workingtitle-aircraft-cj4", that means the CJ4 is loaded after the A32NX, and it seems so that the "Deice_Subtemplates" file of the 320 mod has an impact on the CJ4, and could be also have an impact on other mods. My solution to that was rename the "A32NX" folder to "z-A32NX", with this name is the 320 mod the last one to be loaded in the community folder, and has therefore no longer an impact on the CJ4.

**Comment by Snapmatics** [comment]
> Found a solution without replacing the "Deice_Subtemplates" file in the A32NX. The Sim loads all mods in the community folder from top to bottom. The A320Neo mod has the folder name "A32NX" and the CJ4 has the name "workingtitle-aircraft-cj4". That means the CJ4 is loaded after the A32NX, and it seems so that the "Deice_Subtemplates" file of the 320 mod has an impact on the CJ4, and could be also have an impact on other mods. My solution to that was rename the "A32NX" folder to "z-A32NX", with this name is the 320 mod the last one to be loaded in the community folder, and has therefore no longer an impact on the CJ4.

So, that means PR will come soon or tomorrow?

**Comment by lukecologne** [comment]
This is not a solution. We will need to fix this in our ModelBehaviour XML files.

**Comment by Snapmatics** [comment]
> This is not a solution. We will need to fix this in our ModelBehaviour XML files.

So that will take days?

**Comment by TYR521** [comment]
> This is not a solution. We will need to fix this in our ModelBehaviour XML files.

Yes, you're right, edited my post and wrote "work around" instead of "solution"

**Comment by lukecologne** [comment]
Opened a PR to fix this issue

**Comment by lukecologne** [comment]
@TYR521 can you try out if it fixes your issue?

**Comment by J-Hoskin** [comment]
Guys, just don't have core xml files in your reop/project. Create your own subtemplates and only include the items you are providing new functionality for. See our templates Control.xml, Lighting.xml, and Passenger.xml:

https://github.com/Working-Title-MSFS-Mods/fspackages/tree/main/src/workingtitle-aircraft-cj4/ModelBehaviorDefs/Asobo_CJ4

**Comment by TYR521** [comment]
> @TYR521 can you try out if it fixes your issue?

I've tested it and yes it works, thank you!
