### ISSUE TITLE
[BUG] Camera in clock pop out

### ISSUE THREAD

**Issue by randidiot** [flybywiresim/a32nx#886]
**Mod Version**
Latest master branch.

**Describe the bug**
Popping out the clock onto a 2nd screen reveals weird behaviour, appears to have some camera view.

**To Reproduce**
1. Pop out clock onto 2nd screen

**Expected behavior**
Clock pops out but doesnt have camera viewpoint as background

**References**
![image](https://user-images.githubusercontent.com/71235864/94332132-b3747880-0015-11eb-82b7-571f613809f2.png)
![image](https://user-images.githubusercontent.com/71235864/94332135-ba9b8680-0015-11eb-9111-16036101d45b.png)

Was this working before/when did the issue start occurring?
First time popping out the clock

Is this a problem in the vanilla unmodded game?
Unsure.

randidiot#6635

**Comment by Benjozork** [comment]
This is a game bug.
