### ISSUE TITLE
[BUG] Auto throttle not working in managed mode. 

### ISSUE THREAD

**Issue by Awemeter** [flybywiresim/a32nx#887]
**Mod Version**

0.3.0

**Describe the bug**

I departed from egll and armed autothrottle. When I engage manged speed nothing happens. only manual speed works.

**To Reproduce**

1. Spawn in the game at a gate. 
2.  press down on speed nob to go to manual
3. try to go back to managed (same thing happens in flight)

**Expected behavior**

I expected for the autothrottle to engage and speed up to 250 knots 

**Actual behavior**

after I took off and armed autothrottle and went into manual mode. I tried to put it into managed mode but nothing happened.
I tried to turn the autothrottle on and off but nothing changed. 

**References**

Sorry can't download any recording software. won't run. We can get in a discord call if that would be helpful. 
**Additional context**

I also have the sound mod installed that had me change the .json file 
https://mfsim-sounds.blogspot.com/2020/09/a320neosp-fs2020.html

I just did another test and it turns out when you spawn in you are in manged but if you go to manual you cant go back to manged.

Was this working before/when did the issue start occurring?
This issue started right after the download of a32nx 0.3.0
Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub): Awemeter#7919

**Comment by CoffeePanda0** [comment]
Did you have Generic AI models turned to On? I know the AI models can cause issues with batteries and other systems

**Comment by NickyNiclas** [comment]
https://streamable.com/6l4p3p This is related. Strangely when I changed from managed altitude to selected altitude it started following the selected speed.
