### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by CaptCQ** [flybywiresim/a32nx#889]
**Mod Version**

**Describe the bug**

**To Reproduce**

1. Start cold and dark at a stand.
2. Press batteries 1 & 2 via overhead panel.
3. Press ground power.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Yes. But the issue started for me on version 0.2.0.

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub): Sam Uter

**Comment by CoffeePanda0** [comment]
Can you describe the issue you are having? You just list how to reproduce. If the issue is the batteries not working, set AI Traffic use generic models to ON

**Comment by ferics** [comment]
> "If the issue is the batteries not working, set AI Traffic use generic models to ON", or try restarting once/twice might actually resolve the issue temporarily.

**Comment by NathanInnes** [comment]
Can you please describe the issue?
