### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by CaptCQ** [flybywiresim/a32nx#890]
**Mod Version**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Yes. But the issue started for me on version 0.2.0.

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub): Sam Uter

**Comment by CoffeePanda0** [comment]
Can you edit the template to provide more details?
