### ISSUE TITLE
ECAM on second monitor looks terrible, first picture 0.02 and second picture is 0.03

### ISSUE THREAD

**Issue by Totti1964** [flybywiresim/a32nx#891]
**Mod Version**

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

ECAM on my second monitor after update  looks terrible and has blue background. Only, if I put ECAM on second monitor. With version 0.02 it looks good.
![20200926_114812_resized](https://user-images.githubusercontent.com/71925603/94338512-202a4b80-fff3-11ea-93ba-9f10fcb6a2e8.jpg)
![20200926_115647_resized](https://user-images.githubusercontent.com/71925603/94338513-20c2e200-fff3-11ea-8f55-d201b6445ae6.jpg)

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Ares1378** [comment]
perhaps turn the brightness down....

IRL photo:
![image](https://user-images.githubusercontent.com/70821584/94343418-b2bff000-ffdd-11ea-828f-b85303df9a13.png)

**Comment by Totti1964** [comment]
I tried, but it don't work.

**Comment by Ares1378** [comment]
> I tried, but it don't work.

**Comment by Ares1378** [comment]
Well as you can see from the photo that I posted all of the screens look like this.....

**Comment by Totti1964** [comment]
Brightness control  only works in the VC of the bus, not on second monitor. I think, it is the background of the panel instruments. The clock has also a blue background, when I put it on second monitor.

**Comment by tareksabet** [comment]
@Totti1964 any updates on your issue ?

**Comment by MisterChocker** [comment]
closing since no response from op
