### ISSUE TITLE
on approach to EGLL ILS 27R no MCDU and manual thrust active

### ISSUE THREAD

**Issue by AirbusA35900** [flybywiresim/a32nx#892]
**Mod Version**

**Describe the bug**

**To Reproduce**

1.SELECT EGLL approach ils 27R, SELECT FLY.
2.THE ABOVE ISSUE was encountered simulating this
3.

**Expected behavior**

**Actual behavior**

**References**
![lhr](https://user-images.githubusercontent.com/70841347/94338917-c3cd2900-fffe-11ea-9af0-39f449a9c3b7.PNG)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by tareksabet** [comment]
@AirbusA35900 is it fixed ore not yet

**Comment by MisterChocker** [comment]
closing since this status of this issue is unclear. If still exists can reopened or open a new issue.
