### ISSUE TITLE
Much shorther IR alignment time as a configuration option

### ISSUE THREAD

**Issue by messer79** [flybywiresim/a32nx#894]
**Is your feature request related to a problem? Please describe.**

Over 7 minutes IR alignment time.

**Describe the feature you'd like to see implemented**

I would love to have an option in MCDU MENU to make the IR alignment time much shorter (30 secs - 1 min).

**References**

N/A

**Additional context**

N/A

Discord username (if different from GitHub):
N/A

**Comment by Benjozork** [comment]
Hello,

Our current stance is to not implement such functionality until we have a clear way to offer ease-of-use functions completely separate from the realistic experience we aim to provide. A separate "easy" preset or secret MCDU menu are being considered, bu no concrete plans exist as of yet.

Stay tuned !

**Comment by wpine215** [comment]
Implemented.

**Comment by messer79** [comment]
@wpine215 - It works perfectly. Thank you! 👍
