### ISSUE TITLE
[BUG] Radar doesn't change when CSTR/WPT/ARPT/VOR buttons toggled

### ISSUE THREAD

**Issue by melemed** [flybywiresim/a32nx#895]
**Mod Version**

Version 3

**Describe the bug**

CSTR/WPT/VOR/X/X do not have any effect on the radar screen. Constraints do not show, Airports do not populate on the radar screen, nor do the other functions. 

**To Reproduce**

1. spawn on the runway (everything on)
2. click on the 5 toggles 
3.

**Expected behavior**

nearby airports populate, constraints from the flight plan show in red (altitude, speed, etc)

**Actual behavior**

no change on the radar screen 

**References**

**Additional context**

Was this working before/when did the issue start occurring?
was working in version 2, and now not working in version 3
Is this a problem in the vanilla unmodded game?
no

Discord username (if different from GitHub):
melemed#4828

**Comment by Ares1378** [comment]
Unable to replicate. This was from using the latest master. The items take some time to populate. 
![image](https://user-images.githubusercontent.com/70821584/94347741-5a4c1b00-fffc-11ea-8345-a535efa04998.png)

**Comment by cobrafast** [comment]
CSTR always works instantly for me, but the other items usually take several minutes to show up and are also slow to update.

**Comment by MisterChocker** [comment]
fixed by now
