### ISSUE TITLE
[BUG] Wipers don't remove rain drops

### ISSUE THREAD

**Issue by messer79** [flybywiresim/a32nx#896]
**Mod Version**

Master

**Describe the bug**

Wipers do not wipe rain.

**To Reproduce**

1. Change weather to a rainy day.
2. Turn on wipers.
3.

**Expected behavior**

Wipers wipe rain drops.

**Actual behavior**

Wipers do not remove water from windshields.

**References**

N/A

**Additional context**

N/A

Was this working before/when did the issue start occurring?
N/A

Is this a problem in the vanilla unmodded game?
I haven't checked yet.

Discord username (if different from GitHub):
N/A

**Comment by DevWish** [comment]
I noticed this morning during a torrential downpour. I could still see out the windshield well enough, though.

**Comment by kielyscott** [comment]
Confirmed that this happens vanilla.

**Comment by MikeRomaa** [comment]
Bump!

**Comment by MikeRomaa** [comment]
Wait so this can only be fixed by Asobo? 😦

**Comment by Benjozork** [comment]
Yes.

**Comment by derl30n** [comment]
Issue persists
