### ISSUE TITLE
[BUG] Autobrake indication on Wheel page does not consistently correspond with added panel backlighting

### ISSUE THREAD

**Issue by DoToAdventures** [flybywiresim/a32nx#899]
**Mod Version**

Master

**Describe the bug**

After the addition of panel backlighting in #796 the autobrake indication on the wheelpage is pitch black and always visible on any higher than very low brightness setting on the lower ecam panel after landing with the autobrakes set to max

**To Reproduce**

1. Be on final
2. Land with autobrakes set to max (only tested max, perhaps also occurs with other settings)
3. Disengage autobrakes

**Expected behavior**

The text should not be visible

**Actual behavior**

The text is visible

**References**

![B9PIlEQ](https://user-images.githubusercontent.com/40623152/94340286-d8122580-0000-11eb-9333-33b6503064c8.png)

**Additional context**

Was this working before/when did the issue start occurring?
Presumably after #796 

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub): DoTo#5564

**Comment by Ares1378** [comment]
I can confirm this issue...... WHY YOU LANDING WITH AUTO BRAKES MAX DoTo?????????????

**Comment by DoToAdventures** [comment]
> 
> 
> I can confirm this issue...... WHY YOU LANDING WITH AUTO BRAKES MAX DoTo?????????????

I like to offer my passengers some action

**Comment by Benjozork** [comment]
@DoToAdventures see #786

**Comment by paul92ilm** [comment]
Seems to be fixed
I tried on ground and in flight to engage/disengage AUTO BRK (LO/MED/MAX)
No black text left on WHEEL ECAM page
I think this issue can be closed
