### ISSUE TITLE
[BUG] Upper and lower Ecams, APU and IRS don't work

### ISSUE THREAD

**Issue by aviationenthusiast** [flybywiresim/a32nx#901]
![Screenshot 2020-09-26 145710](https://user-images.githubusercontent.com/71930310/94341314-96857880-0008-11eb-9f42-700657260f9b.jpg)

I can still adjust the brightness on both panels, but they don't show any information no matter what I do. 
Bug appeared in a previous development version and is still present in the new stable release V0.3.

Also, I just noticed there are bigger issues accompanying this. The APU doesn't seem to start and the IRS doesn't work. It's hard to tell though as I can't see what's happening on the ECAM.

The other displays turn on right after turning one battery on, without external power and without going through self testing.

FS 2020 V1.7.12.0
No liveries or other add-ons installed.

**Comment by doratown** [comment]
**FS 2020 V1.7.12.0**

You should update to the latest 1.8.3.0

**Comment by aviationenthusiast** [comment]
Isn't there a way to fix the issues without updating?
