### ISSUE TITLE
[REQUEST] Strobes don't pulse as fast as irl

### ISSUE THREAD

**Issue by davidnorfolk96** [flybywiresim/a32nx#905]
**Is your feature request related to a problem? Please describe.**

Faster Pulse 

**Describe the feature you'd like to see implemented**

Based on the IRL plane, LED bulbs tend to pulse alot quicker than the typical WF bulb. 

**References**

Any youtube video with a a320 & sharklets. 

**Additional context**

N/A

Discord username (if different from GitHub):
David Norfolk

**Comment by NickyNiclas** [comment]
From what I can see in videos there is two pulses of ~4ms each with ~4ms in between the pulses per second.
![image](https://user-images.githubusercontent.com/40072565/94346426-d78f8400-002c-11eb-8cd8-618685f11fab.png)

**Comment by davidnorfolk96** [comment]
Eitherway, they seem abit too slow in the sim. could be a limitation though

**Comment by Snapmatics** [comment]
For now I can't get it to work. I think the SDK is not providing me that feature yet.

**Comment by NathanInnes** [comment]
Please provide video ref.

**Comment by lukecologne** [comment]
https://youtu.be/apiD-YMJnoY?t=139 working on it atm
