### ISSUE TITLE
Airways are not developped in the FMS[BUG]

### ISSUE THREAD

**Issue by alainzu** [flybywiresim/a32nx#906]
**Mod Version**

**Describe the bug**

Hi, I tried to enter manually a route from LFMT to LPMA using the A320 FMS
I wanted to enter NENDA to SNT via UN975
The airway was correctly recognized.
However the flightplan was only composed of initial waypoint NENDA and terminal waypoint of the airway SNT but did not recorded intermediate waypoints between NENDA and SNT???

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Please respect the issue template.

**Comment by alainzu** [comment]
I have developped the bug respecting the issue template
