### ISSUE TITLE
[BUG] A32NX 0.3 Crash to desktop when entering waypoint in FMC

### ISSUE THREAD

**Issue by ThubHulk** [flybywiresim/a32nx#907]
**Mod Version**

0.3

**Describe the bug**

When entering waypoint before two waypoints, it crashed MSFS

**To Reproduce**

1.INIT Page : entered LFPO/EGLL
2.F-PLN Page : click on LFPO and Selected OPAL7P SID and INSERT
3.F-PLN Page : click on EGLL and Selected Arrival on 27L + VIas BIG
4. F-PLN Page : entered Waypoint ALESO before BIG
5. Crash to desktop

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Dennis1108** [comment]
Hi i had same problem. Tried to put in a waypoint DF417 for the transition in EDDF and CTD i tried this two times ... always CTD

**Comment by lousybyte** [comment]
I can't replicate: [https://www.youtube.com/watch?v=RSWfQGa4zME](https://www.youtube.com/watch?v=RSWfQGa4zME)
Am I missing something?

**Comment by ThubHulk** [comment]
You forgot to select VIAS « BIG » I think 
The waypoint is inserted after just before BiG 

Envoyé de mon iPhone

**Comment by lousybyte** [comment]
The via is already inserted, can see it in the middle top, tried manually selecting as well, same result.

**Comment by ThubHulk** [comment]
I think the sequence of insert is important to generate the bug. It happens when selecting waypoint with VIAS function 

Envoyé de mon iPhone

**Comment by lousybyte** [comment]
I see what you're saying now and was able to replicate it.
Also tried to replicate it on the default 1.8.3 vanilla game, and the game crashed 3 times in a row a few seconds after spawn, so it seems it's an issue with that location and not the mod. If anything, the mod is somehow actually making it better.

Can read similar complaints on the official MSFS forum: [https://forums.flightsimulator.com/t/flights-are-crashing-when-starting-from-a-specific-zone/272930/21](https://forums.flightsimulator.com/t/flights-are-crashing-when-starting-from-a-specific-zone/272930/21)

**Comment by ThubHulk** [comment]
Thanks a lot 

Envoyé de mon iPhone

**Comment by ThubHulk** [comment]
I ve tried without the mod. And it does not crush 
So it seems to come from MOD

Without MOD i just cannot enter ALESO ; it does nothing but is does not crash

The link and CTD you mention is not my bug. 

I tried event when flying above the sea, and when i insert waypoint before BIG, it crashes also

**Comment by lousybyte** [comment]
I see the problem now, will push a PR soon to fix it.

**Comment by ThubHulk** [comment]
Thanks. Other point. I tried with 0.2 and no crash on this MOD version - does like no MOD : nothing
