### ISSUE TITLE
[BUG] Thrust limit jumping to 92.8% every ~500ms until 3000ft / is stuck at 100% before being moved 

### ISSUE THREAD

**Issue by lhoenig** [flybywiresim/a32nx#909]
**Mod Version**

master

**Describe the bug**

Throttle jumping to 92.8% every ~500ms until 3000ft after unfreezing it (ghost data from other airplanes again?)

**To Reproduce**

1. Start at EDDM (Munich) on the runway
2. Throttle will be at 92.% (like #748, just with this slightly lower number?)
3. Apply full throttle to un-freeze the throttle display
4. Throttle will jump back to 92.8% every 0.5s until you hit 3000ft

**Expected behavior**

Throttle should not jump

**Actual behavior**

Throttle will jump back to 92.8% every 0.5s until an altitude of 3000ft is reached (could be different for other airports, and maybe enough distance to the airport will also fix it)

**References**

https://gifyu.com/image/62TC

**Additional context**

Was this working before/when did the issue start occurring?
I just noticed it for the first time.

Is this a problem in the vanilla unmodded game?
No. In the unmodded game, the throttle will also be stuck at 92.8%, but after getting it unstuck, will behave normally.

Discord username (if different from GitHub):
lukas_#6140

**Comment by Benjozork** [comment]
Hello, can you clarify if you mean the actual throttle lever or the top-right thrust limit display on the upper ECAM ?

**Comment by lhoenig** [comment]
It was only the top-right ECAM value that was affected.
Hmm, Issue seems to be gone after simulator restart. Still stuck at 92.8% on load as expected, but no jumping anymore. I think I have had that multiple times now, though. Did anybody else have behaviour like this?

**Comment by lhoenig** [comment]
Nevermind, restarted flight and it reappeared!

**Comment by Benjozork** [comment]
Okay thanks, we are aware of innacuracies and values getting stuck in this area and work will be done. I will notify in this issue when progress is made.

**Comment by resir014** [comment]
This happens to me too, albeit with a slightly different number (88.4%), latest stable (v0.3.0).

One thing I noticed is that it will stay at 88.4% if I have autothrottle disarmed on the ground. When I arm the autothrottle it will then flicker with the normal throttle readings.

**Comment by devsnek** [comment]
I'm seeing this when stationary on the ground at idle thrust:

![](https://gc.gy/e4713678-e9cc-4096-8bf9-8a1cedbba6b4.gif)

Note that it is just that indicator, nothing is actually commanding the throttle to 92.8%.

**Comment by AdamNZ** [comment]
Confirmed! I thought it was just me. It's been happening for a fair while now, with many of the Master builds. Not sure whether I got it with the Stable build.

**Comment by hotshotp** [comment]
Yeah ive had this for like 2-3 weeks now

**Comment by dhkim0800** [comment]
This is an asobo bug. Something similar(92.8%) happens on vanila one too.

**Comment by ChruutvoLuzi** [comment]
Can confirm, have the same issue since days now
