### ISSUE TITLE
[BUG] Seemingly random CTD

### ISSUE THREAD

**Issue by BaconW4rrior** [flybywiresim/a32nx#912]
**Mod Version**

0.3.0

**Describe the bug**

Random crash to desktop, no error message shown. Tried different departures and arrivals but can be an hour or just 10 mins. Everything seems to be fine up until the crash. 

**To Reproduce**

1. Fly somewhere
2.
3.

**Expected behavior**

Flight to continue normally

**Actual behavior**

CTD

**References**

**Additional context**

Was this working before/when did the issue start occurring? 

Issue began with version 0.3.0, rolled back to 0.2.0 and CTD doesn't happen. 

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):
Super Bacon Warrior

**Comment by wpine215** [comment]
Not enough information to re-create or troubleshoot, unfortunately. In its current state, our mod does not touch any compiled code (e.g. WASM), so there is no way it is the direct cause of any crashes - those are likely a bug in the core simulator code itself, or the Coherent engine, and it is up to Asobo to fix them - I recommend making a bug report on their Zendesk
