### ISSUE TITLE
[BUG] APPR Angle of Attack

### ISSUE THREAD

**Issue by wirless450** [flybywiresim/a32nx#917]
**Mod Version**

15f27ad

**Describe the bug**

MCDU VAPP reference speed no longer fly's with a realistic angle of attack.

**To Reproduce**

1. After activating APPR mode on the MCDU the aircraft's angle of attack is now extremely high like the default A320 and feels more comfortable to ignore the VAPP speed and fly around 150-155 knots on final approach.

**Expected behavior**

Aircraft should feel like the actual weight of the aircraft reflects the MCDU VAPP and doesn't sink on approach with a high descent rate. 

**Actual behavior**

**References**

**Additional context**

Last version I have reverted back to which the aircraft flew well and the angle of attack correlates with the MCDU VAPP speed is https://github.com/flybywiresim/a32nx/commit/8589f56f03128c6363aac0805094d3cfd595e43c

**Was this working before/when did the issue start occurring?**

Bug started after 0.3.0 but was last working fine on https://github.com/flybywiresim/a32nx/commit/8589f56f03128c6363aac0805094d3cfd595e43c

**Comment by wirless450** [comment]
Bug appears after 65defb7 reverting asobo patch flight model changes.

**Comment by lousybyte** [comment]
Still an issue on 1.9.5 and 0.4.0?

**Comment by wirless450** [comment]
> 
> 
> Still an issue on 1.9.5 and 0.4.0?

This is now fixed thank you.
