### ISSUE TITLE
[BUG] MCDU From/to NOT WORKING

### ISSUE THREAD

**Issue by Cray738** [flybywiresim/a32nx#918]
**Mod Version**
27.09.2020 8:00UTC

**Describe the bug**
FROM/TO MCDU page doesn't work.

**Actual behavior**
When I'm trying to fill the departure and destination airport (ex. EPWA/EPKK) nothing happens. The "boxes" doesn't fill.

**References**

Was this working before/when did the issue start occurring?
Yes

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub): _Cray_#8391

**Comment by lousybyte** [comment]
Remove any screen FPS limiter mods you might have installed.

**Comment by Cray738** [comment]
Thanks for the support

niedz., 27 wrz 2020 o 10:18 lousybyte <notifications@github.com> napisał(a):
