### ISSUE TITLE
[BUG] Perfo, can't activate APPR phase

### ISSUE THREAD

**Issue by JLD95** [flybywiresim/a32nx#920]
**Mod Version**

v0.3.0

**Describe the bug**

Just before I should deccelerate, APPR phase in PERF menu is not activable

**To Reproduce**

1.  Plane arrive at deccelerate waypoint
2. 
3.

**Expected behavior**

APPR phase should be activable in order to have a reduced speed

**Actual behavior**

APPR phase in PERF menu is not activable

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by lousybyte** [comment]
This should be fixed now.
