### ISSUE TITLE
[REQUEST] Prevent maneuvering the gear at high altitudes

### ISSUE THREAD

**Issue by JLD95** [flybywiresim/a32nx#921]
**Is your feature request related to a problem? Please describe.**

at high altitudes, we can make an gear up/gear down

**Describe the feature you'd like to see implemented**

at high altitudes, gear up/gear down should be impossible

**References**

**Additional context**

Discord username (if different from GitHub):

**Comment by komp1821** [comment]
You're right that gear extension is inhibited during cruise, but there is no altitude condition to this.

At 264 kts IAS the L/G safety valve is de-energized which prevents landing gear extension.

Training manual: 
<img width="238" alt="nn" src="https://user-images.githubusercontent.com/71044068/94371150-906cc600-00f4-11eb-8262-ad0eb16b10ae.png">

**Comment by JLD95** [comment]
Ok thank you for the precise technical condition.

**Comment by 2hwk** [comment]
https://github.com/flybywiresim/a32nx/issues/2731 is a repeat of this, however as it has a more up to date issue template and better information, this is issue will be closed.
