### ISSUE TITLE
Abnormal ALT path during approach[BUG]

### ISSUE THREAD

**Issue by alainzu** [flybywiresim/a32nx#928]
**Mod Version**

**Describe the bug**

A320 FMGS generates abnormal ALT after entering APPR/STAR/TRANS on the ARRIVAL page

**To Reproduce**

1. Open Arrival page (in the example LFPG)
2. Enter APPR/STAR/TRANS (in the example=DJL8H/ILS 26L/OKIPA)
3. Open F-PLN page: an abnormally high altitude (288170 ???) was created between waypoints URELO (FL140=correct) and PG522 (9000= correct)
4. Vertical revision on OKIPA is impossible
5. Delete OKIPA waypoint is impossible

**Expected behavior**

correct path for DJL8H STAR should be TRO FL190 URELO FL140 OKIPA FL140

**Actual behavior**

Entering a STAR generates abnormal altitude at the TRANS waypoint whatever the STAR used for a given airport

**References**

![FMGC2](https://user-images.githubusercontent.com/71940317/94370259-446b5280-00ef-11eb-945e-efc92bf4a32b.jpg)
![FMGC](https://user-images.githubusercontent.com/71940317/94370266-4cc38d80-00ef-11eb-8b98-4ee4436e790a.jpg)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Ares1378** [comment]
The Flight plan page is currently all sorts of a mess. The MCDU is going to be completely redone page by page. Thank you for the report however, this page is to be completely redone!

**Comment by lousybyte** [comment]
This happens with vanilla as well, also with Navigraph beta. What I have noticed, if you go to VERT REV page, the constraint is empty, and if you leave it alone it just interprets it as maintain the altitude when you reach it.

**Comment by alainzu** [comment]
Thanks for your reply

I would also inform you that loading a flightplan created with Simbrief results in a systematic crash to desktop with or without Navigraph airac data

Best

 

De : Ares1378 [mailto:notifications@github.com] 
Envoyé : dimanche 27 septembre 2020 22:04
À : flybywiresim/a32nx
Cc : alainzu; Author
Objet : Re: [flybywiresim/a32nx] Abnormal ALT path during approach[BUG] (#928)

 

The Flight plan page is currently all sorts of a mess. The MCDU is going to be completely redone page by page. Thank you for the report however, this page is to be completely redone!
