### ISSUE TITLE
[BUG] Takeoff excesive climb pitch.

### ISSUE THREAD

**Issue by Berniep94** [flybywiresim/a32nx#931]
**Mod Version**
V0.3.0

**Describe the bug**
When activate AP after take off and reducing my throttle to CLB, my nose pitch goes way to high, like in the picture, my aircraft goes to Alpha Floor.

**To Reproduce**

1. Take Off Flex 35°
2. Continue climbing until i reach +1000  AGL
3. Reduce Throttle to CLB
4. Nose goes up
5. Speed goes down.

**Expected behavior**
Continue climbing without getting excesive angle of attack

**References**
![FlightSimulator_0VX1yN4APW](https://user-images.githubusercontent.com/71423997/94374580-86ce6880-00ca-11eb-8add-022a905093f2.jpg)

Was this working before/when did the issue start occurring? i havent seen it for a while.

Is this a problem in the vanilla unmodded game? i dont know.

Discord username (if different from GitHub):

**Comment by lousybyte** [comment]
Related #732

**Comment by MisterChocker** [comment]
This has been fixed by now
