### ISSUE TITLE
[BUG] Auto generated flight plan lead to CTD

### ISSUE THREAD

**Issue by bisinchi** [flybywiresim/a32nx#932]
**Mod Version**

version 0.3 master

**Describe the bug**

On Flight chose a flight from LFBO to LFKB, then chose a flight plan generated by Flight Simulator via High altitude airways, led to CTD straight after loading the situation. Flight plan generated via GPS Direct To did not lead to CTD and could be flown. 

**To Reproduce**

1. flight from LFBO to LFKB
2. Choose flightplan generated by Flight simulator via high altitude airways.
3.

**Expected behavior**

Flight plan should be loaded onto aircraft or at least should not lead to CTD.

**Actual behavior**

CTD at situation startup

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by NathanInnes** [comment]
Was this a one off event or does this happen consistently?

**Comment by bisinchi** [comment]
Hi, it happened twice. Second time i only chose flight plan without sid/star/procedure.Regards,
François.

Envoyé depuis Yahoo Mail pour Android 
 
  Le lun., sept. 28, 2020 à 1:03, Nathan Innes<notifications@github.com> a écrit :   


Was this a one off event or does this happen consistently?

**Comment by lousybyte** [comment]
LFBO has some issues, I get the same crashes without the mod as well. Other people mentioned they had no problems.

**Comment by bisinchi** [comment]
> LFBO has some issues, I get the same crashes without the mod as well. Other people mentioned they had no problems.

OK thanks for the feedback.

**Comment by lousybyte** [comment]
Is this still an issue for you after the Japan update?

**Comment by bisinchi** [comment]
> Is this still an issue for you after the Japan update?
I, just tried it with the latest update, no crash, so seems like it is fixed now.
