### ISSUE TITLE
[BUG] ND Wrong ND Range when in Rose Mode

### ISSUE THREAD

**Issue by Ares1378** [flybywiresim/a32nx#935]
**Mod Version**

Master

**Describe the bug**

When in ROSE Mode the map range should be:
1/4 of selected range for the inner circle.
1/2 of the selected range for the outer circle.

Message Ares#3394 in discord if you have any questions

Currently it uses the same the logic as the ARC mode. 

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by 2hwk** [comment]
Will investigate

**Comment by 2hwk** [comment]
Fixed by #4953 closing ☑️
