### ISSUE TITLE
NAV aids displayed incorrect on the ND

### ISSUE THREAD

**Issue by Ares1378** [flybywiresim/a32nx#936]
**Mod Version**

Master

**Describe the bug**

These items should appear as such on the ND and change colors for the following reasons:
![image](https://user-images.githubusercontent.com/70821584/94387377-945a1180-010f-11eb-986d-da1d624c017d.png)

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by 2hwk** [comment]
Fixed by #4953 closing ☑️
