### ISSUE TITLE
[BUG] AP not following STAR or approach

### ISSUE THREAD

**Issue by AndersHogqvist** [flybywiresim/a32nx#939]
**Mod Version**
master

**Describe the bug**
When I'm about to enter a STAR or approach (if I didn't chose a STAR) the AP stops following the flight path and just keeps flying straight ahead.

**To Reproduce**
1. Create an IFR flight plan including a STAR
2. Start the flight
3. Engage the autopilot in full managed mode

**Expected behavior**
The AP should navigate the aircraft along the flight path all the way to the last waypoint in the flight plan

**Actual behavior**
The AP stops navigating just before reaching the first waypoint in the STAR and keeps flying in a straight line.

**References**

**Additional context**
I'm using the latest release of the Navigraph beta for MSFS 2020, perhaps there's a problem with that rather than with the aircraft or this mod

Discord username (if different from GitHub): ZenIT_SWE

**Comment by lousybyte** [comment]
How far in the flight did you enter the STAR, were there any waypoints left in the flight plan except DEST? Also does it always happen or was it some specific route?
The AP **usually** follows the STAR regardless if Navigraph is used or not, but I always entered it before take off.

**Comment by AndersHogqvist** [comment]
I just experienced this again. I was flying ERNOV 1M STAR to EKCH and had just passed ERNOV when the aircraft stopped following the flight path. I also noticed that the flight path became dashed instead of a solid line

**Comment by AndersHogqvist** [comment]
I made three test flight to EKCH with the ERNOV 1M STAR, first with the STAR chosen in the flight planning window, then with both STAR and ILS 4L approach chosen and lastly with only the STAR chosen again. The first and third went well, but in the second one it started to steer towards the airport just after entering the STAR.

It seems that the issue is that the approach phase is activated as soon as I begin the descent if I have chosen an approach pre-flight.

**Comment by AndersHogqvist** [comment]
No I created the flight plans in the sim

**Comment by Pheome** [comment]
I always create with simbrief with actual airac and enter manualy to the MCDU and I check Navigraph too.

**Comment by Polluticorn** [comment]
Hello, 

I believe this just happened to me this morning. I was flying from KPIT to KFLL with routing KPIT/28L DCT CKB DCT COBBE DCT PSK DCT SLOJO Q83 JEVED Q97 KENLL DCT OMN FISEL7 KFLL/10L (created with simbrief). Flight was fine until I got to the WAKED waypoint. Aircraft briefly started to make the right turn to get on the downwind but stopped and continued strait. I manually changed the heading to stay with planned course. Once localizer was captured, managed heading mode started to work again. 

Hope this helps. I added a screen shot of where the a/c stopped following(start of the dotted course)

Thanks
![Loss of AP heading control](https://user-images.githubusercontent.com/72840032/96015204-e9cf3780-0e0c-11eb-82fb-7c7d9482b16c.png)

**Comment by hornet19853** [comment]
Followed this link from the Discord so I hope my comment is not out of place. I too have experienced this issue on a flight from KOKC/KTUL where the AP started a turn on course, kept straight and had to be manually put back on course. Do I need to post any documentation? Just commenting that I  have had this issue as well.

**Comment by lousybyte** [comment]
There's no need for documentation, just need to figure out what's causing these issues, so the more details the better, there must be something in common.

**Comment by Mariolink123** [comment]
It happened to me too, when the plane is within the proximity of the runaway during my STAR approach (still around 5 way points away), the AP started navigating me to the RW26R waypoint, so I assume maybe it's the waypoint calculation that's acting up

**Comment by lousybyte** [comment]
So is this the same as #1253?

**Comment by Mariolink123** [comment]
> So is this the same as #1253?

Yeah, exactly that

**Comment by Sierrapappayankee** [comment]
If any FBW contributors read this. I mentioned the same problem (aircraft veering off of flight plan & random insertions of USR waypoints) on the FS forums. One of the Navigraph admins came back to me saying that the problem lies in the game. He said **the waypoints in question are getting truncated** and therefore are read incorrectly in the flight plan. 
Sadly, his recommendation to avoid this problem was to start using the Working-title CRJ mod, as it uses it's own logic instead of the in-game logic. Not really a solution at all...

Big job, but is it time to implement a custom MCDU logic instead of using the very flawed in-game logic? (I am no programmer so I have no idea what that requires!)

**Comment by tracernz** [comment]
Exactly that is in progress currently.
