### ISSUE TITLE
FD should automatically turn on during the setup of the mcdu

### ISSUE THREAD

**Issue by GlitchedYT** [flybywiresim/a32nx#94]

**Comment by arvinjarvin** [comment]
In progress.

**Comment by NathanInnes** [comment]
Can you please describe more about this issue. Thanks :)

**Comment by FlyingCarpet7** [comment]
They should not come on automatically as far as I know. 

[The FD Command Bars are displayed when a flight director button is selected ON. On the ground, the flight director may be selected ON, but will not appear on the PFD until the thrust levers are moved to FLX or TO/GA.]

**Comment by hotshotp** [comment]
Closing as input from real pilot confirms that the behaviour is correct
