### ISSUE TITLE
[BUG] Transponder & frequency displays blank in instrument view.

### ISSUE THREAD

**Issue by davidfrp** [flybywiresim/a32nx#941]
**Mod Version**

 V0.3.0

**Describe the bug**

Transponder and radio frequency displays turn blank in instrument view.

**To Reproduce**

1. Enter instrument view.
2. Navigate the instrument view till you view the middle pedestal panel. The displays are off when viewed at directly.

**References**

![radio frequency and transponder display bug in instrument view A32NX v 0 3 0](https://user-images.githubusercontent.com/6499570/94413300-2ea36f00-017b-11eb-8efc-4eb0e0fb96cb.gif)

**Additional context**

Was this working before/when did the issue start occurring?
After one of the patches from Asobo. Not sure exactly when. 
If I have to be frank, it seems to be their responsibility. Not sure what can be done about this issue that's not on their end.

Is this a problem in the vanilla unmodded game?
Yes.

Discord username (if different from GitHub): Fibre#0690

**Comment by FlyingCarpet7** [comment]
I did see the same thing in Clumsy video.
Look at Timestamp 08:13

https://youtu.be/IiKd6AcPoZ0

**Comment by davidfrp** [comment]
Closed due to being a duplicate of issue #717
