### ISSUE TITLE
[BUG] TO Config page appears if APU started after landing

### ISSUE THREAD

**Issue by mythicfci** [flybywiresim/a32nx#942]
**Mod Version**
Master

**Describe the bug**
After landing, if you start the APU while taxiing to the gate, the TO Config menu appears on the ECAM.

**To Reproduce**
1. Start a flight, take off, and land as normal.
2. While still taxiing to the gate, start the APU.

**Expected behavior**
The ECAM should remain in the same state as it was after touchdown.

**Actual behavior**
After the APU is started, the TO Config menu appears.

**Additional context**
I've noticed this happening on two flights in a row now.

**Comment by FlyingCarpet7** [comment]
Happened to me as well
