### ISSUE TITLE
[BUG] Unable to use managed mode in autopilot

### ISSUE THREAD

**Issue by SWO-Fail** [flybywiresim/a32nx#943]
**Mod Version**
0.3.0 (latest stable)

**Describe the bug**
Unable to select managed mode in the autopilot once activated. This applies to speed, heading and altitude. Altitude select does not function (although selected speed and heading do function). V/S selection does not function at all. Bug will present when activating autopilot after a takeoff. Aircraft will immediately level out and the 'managed mode' dots on the autopilot panel will clear and are replaced by random values for speed and heading. FMC is also missing the flight plan even when correctly set in the pre-game flight select screen (although the nav display shows the flight path correctly).

**To Reproduce**
1. Fly as normal (any take-off will do - it reoccurs for me every time)
2. Engage autopilot and the aircraft will instantly level off
3. Engaging or disengaging autopilot has no effect on the issue
The below linked video is a good example of the issue

**Expected behaviour**
FMC should load flight plan data
When autopilot if activated it should follow the managed flight path and speed
User should be able to reactivate managed modes
User should be able to use the V/S knob

**Actual behaviour**
FMC is missing flight plan
As soon as AP1 is selected, autopilot will disengage managed mode. Select a random speed and heading and level off the aircraft immediately. On some occasions the aircraft will resume a climb again after some time to the value set when the sim loads in (5,000ft) but this does not happen every time.

**References**
1. Image of FMC missing flight plan when loading in ![FMC missing flightplan](https://user-images.githubusercontent.com/72012424/94425251-f62d8080-01ce-11eb-9c6a-ee6d31a46724.png)
2. Image of AP panel as normal when sim loads in ![AP panel pre activation](https://user-images.githubusercontent.com/72012424/94425243-f3cb2680-01ce-11eb-8d35-3c66fb603fe9.png)
3. Image of AP panel as soon as the user activates AP 1 ![AP panel post activation](https://user-images.githubusercontent.com/72012424/94425262-faf23480-01ce-11eb-959a-602d837c6d89.png)
4. Video demonstrating the issue as well (apologies for the music playing in the video) - https://streamable.com/rk3g6y

**Additional context**
I think I have only run into these issues since the most recent MSFS update. I have the exact same issue in the current master branch too.

Was this working before/when did the issue start occurring?
Yes, was working before and I think the most recent update coincides with the issue.

Is this a problem in the vanilla unmodded game?
No - not an issue in the un-modded game, nor was is an issue in 0.1.0 and 0.2.0 (for some time I was using master branches pre 0.2.0 and the issue was not in those either)

Discord username (if different from GitHub): SWO Fail

**Comment by lousybyte** [comment]
Does this happen every flight or just once?

**Comment by SWO-Fail** [comment]
Yes, I am able to replicate this in every single flight I do. I have tried different combinations of departure and arrival locations as well - the bug is consistent across all attempts.

**Comment by lousybyte** [comment]
> Until MSFS Update 3 releases on Tuesday, September 29th, we recommend disabling multiplayer, AI traffic, and ground AI when flying the A320neo. This will help you avoid issues introduced in the previous MSFS patch where other aircraft loading in will cause switches and knobs to change and other issues.
> 
> Also be aware that some custom liveries may interfere with the A320neo. Using the Navigraph beta may also lead to issues.

Can you please trying the workarounds quoted above first, and if you still have issues, try deleting the `A32NX folder` from `Community` and then replace it with the one from the current `master` branch: [https://github.com/flybywiresim/a32nx/archive/master.zip](https://github.com/flybywiresim/a32nx/archive/master.zip)

**Comment by tcarlisle2012** [comment]
It is worth mentioning that I fly the a32nx with multiplayer enabled, AI traffic enabled, and ground AI enabled and find all AP functions work as expected. 

Speed, heading, altitude, and vertical speed all work as expected -- in either in "managed" mode or "selected" mode. 

The only ting I can think that I am doing  differently, is I do have a flight plan in the FMC. If there is no flight plan in the FMC, of course I wouldn't expect managed mode to work. 

I use either of these methods to get a flight plan in the FMC:

1) From the globe menu, setup your flight by picking origin and destination, and make sure you check the option "IFR high airways". This will put an appropriate flight plan in the FMC. 

2) Use simbrief to plan your flight, and export the flight [plan and load that flight plan from the globe menu. 

If one is not doing either of those things, then I would not expect a flight plan to be in the FMC and would not expect any of the managed modes to work. 

If one is putting the flight plan in the FMC manually, there is more involved than just entering each waypoint. Waypoints give you lateral path,. You don't get vertical nav until you put in cruise altittude, climb profile, etc. Detailed instructions on that are out of the scope of this comment.

**Comment by SWO-Fail** [comment]
I am now able to get the mod to function correctly on the latest master branch that was posted 3 hours ago.
I will continue to test later when I have some time with the stable build 0.3.0 to see if I can also get that to work.

Steps to correct (although I am not sure why this worked as I had already done this multiple times):

1. Delete everything from the community folder (including all my non-A32NX mods)
2. Install A32NX master branch mod only with nothing else in the folder
3. Launch sim, load flight as normal and it worked
4. Exit sim, place all my original mods back into the folder
5. Launch sim and load flight again - once again, this worked without issue and functionality is returned

In reference to the above comment, I was loading the flight plan correctly but it would not load into the FMC. Since doing the above steps the FMC is populated correctly and AP functions as I would expect.

One thing I would note is that when loading up the sim at the start of today I realised I forgot to remove my non-A32NX mods from the folder and I exited the game via an 'alt-f4' while it was loading in before deleting the mods and relaunching (this happened before the above noted step 1 - I doubt this had any effect but it was something I did by accident before it started working again).

I have also started suffering from severely degraded frame rate after 30 minutes within the sim which looks similar to this issue on the forums. https://forums.flightsimulator.com/t/gameplay-degrades-with-time/238780
I assume this is an Asobo bug and not related to the master branch but I will report back after I get time to test the 0.3.0 release.

**Comment by docjonny** [comment]
Can you advise if Dual Ap1 and Ap2 are now available for a320NX and functional for dual Cat3 approach?

**Comment by SWO-Fail** [comment]
Version I am now on is the latest stable release (the version designed to cope with the new Japan update) - I haven't tested the current master branch.

AP still functions well like it did before I experienced the errors which made me report this bug (feel free to close this ticket if appropriate as my initial reason for raising this matter appears to be fixed).

CatIII Dual appears to work in principle but the PFD has no FMA to show that the mode is CatIII dual. The FMA for CatIII single does work every time I've tested.

I also have difficultly having CatIII dual to engage every time, but this may be due to limitations with the airport I'm landing at - I am not knowledgeable enough about the true function of the Airbus AP to confirm if this is why I only get CatIII single at a number of locations.

Please let me know if you would like further information from me.

**Comment by SWO-Fail** [comment]
![Uploading CatIII Dual with no FMA on PFD.png…]()

**Comment by SWO-Fail** [comment]
![CatIII Dual with no FMA on PFD](https://user-images.githubusercontent.com/72012424/95033287-5e1d2300-0709-11eb-8d99-6dca2d1f7702.png)

**Comment by docjonny** [comment]
This isn’t working for me. Tried landing at Malpensa 35R as you showed and cannot get both AP buttons to stay on together. MSFS version 1.9.3 and a32nx 0.3.1. What am I missing to get this dual connection?

**Comment by SWO-Fail** [comment]
As I mentioned above, I can't get it to work every time and I'm not sure what I do to get it to function. Sometimes CatIII dual will just engage during the ILS without me selecting anything specific, other times I cannot get it to engage (even at the same location).

I am unsure of the cause for this intermittent behaviour.

**Comment by docjonny** [comment]
Thanks. If you have any other airports you have succeeded with dual approach please feed me names and runways and I will try others. SWO= Surface Warfare Officer?
Jon

**Comment by docjonny** [comment]
Thanks. If you have any other airports you have succeeded with dual approach please feed me names and runways and I will try others. SWO= Surface Warfare Officer?

Jon

**Comment by SWO-Fail** [comment]
YMML to YSSY functions for CatIII dual. I'm on one of the recent master branches and the CatIII dual FMA is now also functional.
Video attached for reference. This is the ILS approach into 34L via the RIVET arrival.
https://streamable.com/l76arc
![RIVET3 Arrival](https://user-images.githubusercontent.com/72012424/95647744-8c419f00-0b1d-11eb-9c5c-07743041c6ac.png)
