### ISSUE TITLE
[BUG] Shades of color on ECAMs are darker than PDF/ND

### ISSUE THREAD

**Issue by cobrafast** [flybywiresim/a32nx#944]
**Mod Version**

master

**Describe the bug**

The upper and lower ECAM use a darker shades of color for text and numbers than the PFD and ND use. This makes the ECAMs harder to read.

**To Reproduce**

1. Start at runway, turn brightnesses up

**Expected behavior**

see above

**Actual behavior**

see above

**References**

Current state in-sim, ECAM texts appear clearly darker:
![img](https://x.ezl.re/20200927_124307.png)

Real airplane, ECAM texts appear at same shade/brightness as PFD/ND:
![img](https://forums.flightsimlabs.com/uploads/monthly_2017_03/1887874.jpg.e870cd6a773c4ba68031c33f94488d26.jpg)
There seems to be some darkening happening towards the lower end of the upper ECAM, which I believe could be a camera (rolling shutter) problem.

**Additional context**

Was this working before/when did the issue start occurring? Always been this way I think.

Is this a problem in the vanilla unmodded game? Probably.

Discord username (if different from GitHub): Cobra#5370

Continuation of #867

**Comment by Pleasure0102** [comment]
are all brightness knob levels at the same position ?

**Comment by cobrafast** [comment]
Yes. Additionally, the popout gauges I screenshotted are always at full brightness.

**Comment by Pleasure0102** [comment]
okay just wanted to make sure that they are infact the same brightness level.

**Comment by MuppetOwl** [comment]
Think all the LCD screens looks a bit "washed out" now. with the gray background and is now a bit difficult to read compared before. I have seen inside the cockpit on the Airbus A320 at night and the screen backlight does not look so bad. But on many pictures they do. Its the same when you take a picture of normal TV the back light show a lot more in the pictures than real life.
But still its not Oled screen like the Asobo one looks like, so should have a little backlight.
