### ISSUE TITLE
Self-test only when unpowered over 10 seconds

### ISSUE THREAD

**Issue by luke-bennellick** [flybywiresim/a32nx#945]
**Mod Version**
Master (0.3)

**Describe the bug**
When reducing the brightness on the following switches to zero:
PFD, ND, Upper ECAM, Lower ECAM, right PFD, right ND.

and then raising the brightness (thereby switching the screens back on), the screens switch to a self test mode immediately. In addition, reducing (for example) the right ND, will also swap the left ND screen to auto test (and vice versa).

**To Reproduce**
1. Reduce brightness on any screen to minimum so that it switches off.
2. Increase brightness on same screen to above minimum, and the screen goes into self test mode, along with corresponding screen on the opposite side of the cockpit.

**Expected behavior**
Lowering these switches to off and then increasing the brightness knob (switching them back on) should only enter self test mode once the screen is off for 10 seconds. If less than 10 seconds, the screen should just be as it was prior to being switched off.

**Actual behaviour**
Turning the screen brightness down for any screen (ND, PFD, Upper / Lower ECAM, right ND, right PDF) switches them off, and upon switching them back on they enter self test mode immediately.

**Comment by FlyingCarpet7** [comment]
The Screens (PFD, ND, upper and lower ECAM) actually have a combined ON-OFF/brightness control turn knob. When you get to lowest dim there is a detent/click to turn a bit more to the OFF position.
Turning it back ON within 10 seconds will however not initiate a self test like it is now. And of course all screens should work independently.

**Comment by luke-bennellick** [comment]
@FlyingCarpet7 you're correct, my initial report was wrong (and my pilot friend went to check with another 320 pilot). It can be switched off in terms of brightness, however it cannot be switched off in terms of actual function (without disabling the breaker, or disabling all electrical power).

I've updated the description.

**Comment by luke-bennellick** [comment]
*NOT RELEVANT TO ABOVE TICKET - PLEASE IGNORE FOR DEVELOPMENT PURPOSES**

In addition - in case you're interested. Older A320 displays with CRT screens did not have a minimum detent, and simply dimmed to minimum without switching off. The newer screens with LCD displays are able to entirely switch off. Perhaps you knew that, but I found it interesting.

**Comment by lukecologne** [comment]
> 
> 
> @FlyingCarpet7 you're correct, my initial report was wrong (and my pilot friend went to check with another 320 pilot). It can be switched off in terms of brightness, however it cannot be switched off in terms of actual function (without disabling the breaker, or disabling all electrical power).


This is incorrect. See this video by komp#1821 on the discord.
https://discordapp.com/channels/738864299392630914/754851312306487326/758257387432968222

**Comment by Ares1378** [comment]
@lukecologne what is @FlyingCarpet7 wrong about... everything he said is correct.

**Comment by lukecologne** [comment]
They said the DUs will never go into self-test mode when turned off by the control knobs, which is clearly possible as seen in the video, you just need to wait more than 10 seconds

**Comment by luke-bennellick** [comment]
@lukecologne Interesting. Perhaps this isn't something done very often and so the pilots haven't seen it. I'll amend my above ticket to reflect the correct behaviour.

**Comment by luke-bennellick** [comment]
@lukecologne thanks for your correction - I'm surprised that two active 320 FO's were not aware of this, however perhaps this is simply outside of the normal usage and as such not seen by relatively inexperienced pilots. Would you agree that my new definition of the bug correctly describes the correct behaviour?

**Comment by lukecologne** [comment]
Sounds good. IIRC the A320 pilots on the discord have stated that you don't turn off the screens when leaving the aircraft, so it's not a surprise that they didn't know this.

**Comment by luke-bennellick** [comment]
Interesting, then perhaps I'll hold off on my mockery of them :)

Thanks!

**Comment by infty12** [comment]
Hello everyone here,

I'm the FO that @luke-bennellick mentioned this systems behavior to. So, first off, apologies all round for the kerfuffle. @lukecologne also please convey my thanks to the colleagues on Discord for the very quick responses.

I couldn't believe my eyes when seeing the linked video, so I've just gone and checked for myself and, no surprise, find myself in agreement with my colleagues that consult for you.

Clearly this is what being furloughed six months does to you - you start getting basic stuff wrong. I'll take that away as a lesson in hubris.

It is indeed procedure to only dim rather than turn off the DUs on ground and that's probably where my mix up comes from, in addition to my carrier still (at least pre COVID) operating a lot of CRT cockpits where the behavior is closer to what I'd described to @luke-bennellick: no self test except when power cycling fully.

Hats off to the developers for the high fidelity product. Let's go ahead and close this ticket and pretend none of this happened. 🤫😉

**Comment by Ares1378** [comment]
@lukecologne yes yes I know I felt stupid after realizing it and deleted my comment hoping you didn’t see it hahahahaha! My apologies

**Comment by lukecologne** [comment]
No worries :) Probably wasn't the best idea including the tag from the original comment

**Comment by 2hwk** [comment]
Will look into this when I'm free, also fixing several other issues around displays
