### ISSUE TITLE
[REQUEST] Whole numbers for the QNH dial in hPa setting

### ISSUE THREAD

**Issue by liebbe10** [flybywiresim/a32nx#948]
**Is your feature request related to a problem? Please describe.**

When setting the QNH to the hPa setting the knob still uses the precision of inHg. So there are 3 knob positions all showing the same QNH but with an altimeter difference of 40ft.

**Describe the feature you'd like to see implemented**

When using the hPa setting only whole hPa should be selectable.

**References**

**Additional context**

Discord username (if different from GitHub):

**Comment by NathanInnes** [comment]
Duplicate issue of #138
