### ISSUE TITLE
[BUG] Autothrust incorrectly reponds when handflying in managed climb mode

### ISSUE THREAD

**Issue by sef3613** [flybywiresim/a32nx#949]
**Mod Version**

0.3.0

**Describe the bug**

Upon reaching acceleration altitude and moving the thrust levers to climb, the FMA correctly indicates that the autothrust is in "THR CLB." However, once the plane accelerates to 250 knots (in managed speed/managed climb), the thrust starts to reduce as if the autothrust is in "SPEED" mode. This only occurs with the autopilot OFF, and might be correlated to the fact that the flight directors seem to follow the pilot's pitch inputs.

**To Reproduce**

1. Takeoff with a SID and reduce thrust to the climb detent when commanded on the FMA, do not engage autopilot throughout this test.
2. Allow the plane to accelerate to the target speed (usually 250 knots) by pitching down.
3. Notice the engines changing thrust upon reaching 250 knots. 

**Expected behavior**

The engines should remain at a constant climb thrust when in "THR CLB" even when the plane reaches the target speed. The flight directors should command a nose up pitch to hold airspeed with the thrust staying constant.

**Actual behavior**

The engines start to spool back and reduce power if the airspeed reaches or slightly exceeds 250 knots, as if the autothrust is in "SPEED" mode.

**References**

![image](https://user-images.githubusercontent.com/70450099/94483124-68d73580-01a8-11eb-9a8f-cb0fc30b7e78.png)
Here you can see the CLB thrust is supposed to be "86.8% N1" but yet the engines are actually below 60% N1 due to the speed reaching 250 knots.

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by donstim** [comment]
This bug references being in the managed climb mode. Does it not occur also if in selected climb mode?

**Comment by sef3613** [comment]
There's no such thing as "selected climb," do you mean open climb? I don't believe it happens in any mode besides managed climb when hand-flying. THR CLB is a fixed thrust mode so it should hold the engine power constant regardless.

**Comment by donstim** [comment]
Same thing. In MSFS you go to open climb by clicking on "selected climb." Behavior should be the same in open climb mode, but i guess you didn't check that?

**Comment by sef3613** [comment]
It seems to behave correctly in selected/open climb. It's only in managed climb that the auto thrust chases the speed rather than hold climb thrust no matter what your speed is.

**Comment by sef3613** [comment]
![Screenshot (64)](https://user-images.githubusercontent.com/70450099/95019457-6b67de00-0633-11eb-8dc9-d84c8f6cfab2.png)
![A320 - 2020-10-04 11 18 57](https://user-images.githubusercontent.com/70450099/95019461-702c9200-0633-11eb-8370-292aae123fb6.png)

Notice the difference in the engine behavior on the 2 screenshots. In both screenshots I was handflying in managed climb and going over 250 knots. In the first screenshot, the engines incorrectly were spooling back from climb thrust trying to maintain speed. In the second screenshot, the engines correctly stayed at climb thrust even if I was going over the speed target and the FDs commanded a pitch up.

**Comment by nobodyn0se** [comment]
With the latest mod version, it behaves the same way in both OP CLB / CLB modes unless you turn the AP on. One workaround is to disable ATHR, it prevents the aircraft from going into SPEED mode when the target climb speed is reached. But the commanded N1 is about 3% higher than its max N1 (a different bug, regardless of AP status), so the aircraft will be a tad bit "overpowered" for climb.

**Comment by sef3613** [comment]
> It has been doing that, no change with the latest mod version, it behaves the same way in both OP CLB / CLB modes unless you turn the AP on. One workaround is to disable ATHR, it prevents the aircraft from going into SPEED mode when the target climb speed is reached. But the commanded N1 is about 3% higher than its max N1 (a different bug, regardless of AP status), so the aircraft will be a tad bit "overpowered" for climb.

Thank you for the feedback! I was told on the discord that they didn't see how this was a serious issue or that it "doesn't happen in open climb" which I've experienced. Glad I'm not crazy that this is a problem
