### ISSUE TITLE
Kicking AP off to land changes Thrust Mode and vertical mode [BUG]

### ISSUE THREAD

**Issue by Ares1378** [flybywiresim/a32nx#950]
**Mod Version**

Master

**Describe the bug**

Coming in on an ILS 30R into KMSP. Flew a coupled approach with the AP down to 300 RA disconnected AP and the thrust mode went from SPEED to THR CLB and the vertical FMA went to CLB. It should not change when the AP is disengaged It should maintain itself in the G/S mode and a variable thrust setting on an approach or level flight i.e SPEED/MACH until initiating the Go Around phase. Also after landing somehow the LOC pb was on.... 

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by tareksabet** [comment]
@Ares1378 there is a new FBW system we need also you to check it beside us.
Hope you're going to answer.

Tarek

**Comment by MisterChocker** [comment]
this has been fixed by now
