### ISSUE TITLE
No heading bug in rose modes on ND [BUG]

### ISSUE THREAD

**Issue by Ares1378** [flybywiresim/a32nx#951]
**Mod Version**

Master

**Describe the bug**

No heading bug in rose modes on ND (ROSE VOR, ROSE LS) Heading bug should always appear when spinning the heading knob or when heading is pulled (SELECTED)

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by AdenFlorian** [comment]
note how the cyan heading triangle is missing for VOR and ILS modes, but is visible in NAV mode. I believe this is what Ares was talking about.
![image](https://user-images.githubusercontent.com/3533988/95156750-ebd62e00-075c-11eb-93a6-e9e7b2ae85c7.png)
![image](https://user-images.githubusercontent.com/3533988/95156759-f1337880-075c-11eb-9f56-4df8f55a88e2.png)
![image](https://user-images.githubusercontent.com/3533988/95156770-f690c300-075c-11eb-91d9-1993453c5d7d.png)
