### ISSUE TITLE
[BUG]crash to desktop

### ISSUE THREAD

**Issue by diego19martin** [flybywiresim/a32nx#953]
**Mod Version**

MOD 3.0

**Describe the bug**

I have a problem with the MOD 3.0, it usually happens to me when I put a direct in the FMC it remains simulated for a second and it closes without any error message. Does it happen to someone? (It happened to me with the previous version too). It also happens when i add a waypont.

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by NathanInnes** [comment]
Download the latest master and see if you have this problem. A PR was recently merged to fix a CTD when entering waypoints.

**Comment by Tonyehrd** [comment]
I had the same issue, I resolved by deleting FS2Crew.

**Comment by Tonyehrd** [comment]
*Update, with the new Master and fs2crew no more CTD after putting in a direct or changing something in the MCDU.

**Comment by NathanInnes** [comment]
@diego19martin Let us know if the above solved your issue

**Comment by diego19martin** [comment]
Thanks for your help! I´ll give it a try with the last master update and tell you about it!

**Comment by callebstrom** [comment]
@NathanInnes I'm currently on latest master (from today at least) and I also encountered this issue just now when entering a waypoint in the FMC unfortunately.

**Comment by lousybyte** [comment]
Seems like a vanilla issue, had some crashes just my altering the waypoints on the main menu.
