### ISSUE TITLE
[REQUEST] Non instrument (visual) approach

### ISSUE THREAD

**Issue by wirless450** [flybywiresim/a32nx#954]
**Describe the feature you'd like to see implemented**

The ability to select a runway on the MCDU that is non RNAV / ILS approach etc. 

To be able to input a 3 or 5nm approach to a runway.

For example, to be able to conduct a visual approach to a runway while still tracking the runway centreline on the autopilot. 

**References**

Best reference I could find is this:

![Untitled thumb jpg 962b18cc14981c6a26e848863cecf790](https://user-images.githubusercontent.com/71955733/94502287-2d3f7880-0247-11eb-8175-f7573b04e093.jpg)

**Comment by Benjozork** [comment]
Is this in the real airplane ?

cc. @tareksabet

**Comment by bouill** [comment]
In the the real plane, there's one extra approach line for each runway with just the runway number, usable for visual, and containing the RW waypoint and a CF waypoint, on final track 4NM to runway
