### ISSUE TITLE
Flight director bug.. Vertical speed shows up on FMA

### ISSUE THREAD

**Issue by nabil74** [flybywiresim/a32nx#955]
**Mod Version**
Latest Master

**Describe the bug**
During cold and dark startup. turning FD on / off  and then on again makes V/S (vertical speed show on PFD

**To Reproduce**
Once aircraft is powered by extenal power or APU.
Turn FD on. PFD shows climb and thrust blue (armed) on the PFD correctly.
Turn FD off and then on again... The PFD shows Vertical speed mode..(even tough not selected).

**Expected behavior**
PFD should shown climb and thrust blue (armed). when turned off and on again to match previous state.

**Actual behavior**
Turn FD on. PFD shows climb and thrust blue (armed). Even though vertical speed is not armed / selected.

Is this a problem in the vanilla unmodded game?
Not sure.

Nabil

**Comment by Ares1378** [comment]
first off are you disengaging BOTH FDs? 
Second of all A/THR should not be armed the only FMA's that should appear on the ground with no engines running are the lateral and vertical modes i.e. CLB | NAV.
But yes when turning back on the FDs on the ground it should not go to V/S it should still show CLB | NAV
A/THR does not arm until the Thrust levers have been moved to the FLX or TOGA Detent and then becomes ACTIVE once the Thrust levers have been moved to the CL detent.

If both FDs are disengaged in-flight with no AP engaged:
Both Vertical and lateral modes will disengage and the A/THR mode will revert to SPEED/MACH
If both FDs are disengaged with the AP engaged:
No changes will happen to the FMA's

The following are the only reversionary modes in which you should get V/S:

CLB or OP CLB Engaged and an FCU altitude is selected below the aircraft ALT vertical mode switches to V/S on current V/S
DES or OP DES and an FCU altitude is selected above the aircraft ALT vertical mode switches to V/S on current V/S
ALT* Active and any change to the FCU selected altitude is changed the vertical mode will switch to V/S

CLB engaged and lose of NAV mode (Automatic or manual) OP CLB engages
DES engaged and lose of NAV mode (Automatic or manual) V/S engages

**Comment by MisterChocker** [comment]
seems to be outdated
