### ISSUE TITLE
[BUG] BAT 1 & 2 Text Colour Wrong

### ISSUE THREAD

**Issue by NathanInnes** [flybywiresim/a32nx#957]
**Mod Version**

master version. 2408e36b0df2f74bdb10f2857ce68c2eecd90ee6

**Describe the bug**

Battery 1 & 2 indicators should be AMBER text not white.

**To Reproduce**

1. Load up aircraft 
2. Inspect battery voltage.

**References**

![image](https://user-images.githubusercontent.com/18389085/94509769-fd737f00-020c-11eb-9633-288738d2df6c.png)
![image](https://user-images.githubusercontent.com/18389085/94509778-019f9c80-020d-11eb-8c85-a2c10bebb774.png)

**Additional context**

Was this working before/when did the issue start occurring?
N/A

Is this a problem in the vanilla unmodded game?
Yes.

Discord username (if different from GitHub): Sabes#8668

**Comment by tareksabet** [comment]
Also it is static

**Comment by NathanInnes** [comment]
Working on it now.
