### ISSUE TITLE
[BUG] No "Avail" shows on upper ecam when engine started

### ISSUE THREAD

**Issue by doratown** [flybywiresim/a32nx#958]
**Mod Version**
master

**Describe the bug**
"Avail" Should appear in upper ecam engine indication when N1 more than 18%

**To Reproduce**
1. Start engine
2. After N1 18% no Avail shows

**Expected behavior**
"Avail" appear in upper ecam engine indication when N1 is more than 18%

**Actual behavior**
Nothing appear in upper ecam engine indication

**References**
https://youtu.be/4NAs7DJ42eM?t=116

**Additional context**
Nil

Was this working before/when did the issue start occurring?
No
Is this a problem in the vanilla unmodded game?
Yes

**Comment by RichardPilbery** [comment]
I have a fix for this. Will submit shortly.
