### ISSUE TITLE
[BUG] F-PLN ND mode

### ISSUE THREAD

**Issue by tareksabet** [flybywiresim/a32nx#959]
**Mod Version**

Master latest version 

**Describe the bug**

the F-PLN ND mode already aligned with IRs not aligned yet 

**To Reproduce**

1.spawn in cold & Dark 
2. change to ND mode to F-PLN 
3.

**Expected behavior**

it shouldn't be aligned 

**Actual behavior**

it is already aligned 

**References**

![Desktop Screenshot 2020 09 29 - 08 15 15 81](https://user-images.githubusercontent.com/70240330/94520283-47b82880-022c-11eb-8ea9-6339a7242223.png)

**Additional context**

Was this working before/when did the issue start occurring?
it was working before 
Is this a problem in the vanilla unmodded game?
yes 

Discord username (if different from GitHub):

**Comment by lousybyte** [comment]
Seems intended according to this: [https://youtu.be/MywqXeeoYos?t=745](https://youtu.be/MywqXeeoYos?t=745)

**Comment by tareksabet** [comment]
> Seems intended according to this, just the plane symbol should not be present: https://youtu.be/MywqXeeoYos?t=745

@lousybyte I agree plus you can’t type basically any waypoints cz the IRs are still not aligned.

**Comment by NathanInnes** [comment]
You can still enter a flight plan tho, just the IRs don't have info to display where the aircraft is in relation to the waypoints.

**Comment by LorDawid** [comment]
It its correct, but the plane position shouldn't be there.

**Comment by lousybyte** [comment]
Related #186.
