### ISSUE TITLE
MECH alert horn button

### ISSUE THREAD

**Issue by 2hwk** [flybywiresim/a32nx#96]
MECH Pushbutton: When pressed, outside horn sounds (audible from the cockpit)

From: Eaglepilot [Discord: SM#6029]

**Comment by becas22** [comment]
Pressing the MECH pushbutton on the ACP will not trigger the horn outside.
Pressing the MECH pushbutton on the CALLS panel in the Overhead will.

That illustrated MECH p/b is used to select the microphone to talk to the mechanic.
