### ISSUE TITLE
Dark Screens after the 1.9.3.0 update[BUG]

### ISSUE THREAD

**Issue by alainzu** [flybywiresim/a32nx#963]
**Mod Version**

**Describe the bug**

Dark Screens after the 1.9.3.0 update[BUG]

**To Reproduce**

1. Load the 1.9.3.0 update
2. Load A320
3. Play

**Expected behavior**

**Actual behavior**

Dark screens MCDU+PFD+ND+ lower and upper ECAM

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Hello, someone already reported the same issue. Please look in the list of recently opened issue before opening a new one.
