### ISSUE TITLE
[BUG] insane climb/descent rate using autopilot

### ISSUE THREAD

**Issue by ZiCongQ** [flybywiresim/a32nx#965]
**Mod Version**
Any, it's a bug in the default a20n but wish it could be fixed via a32nx.

**Describe the bug**
Insane climb/descent rate when using autopilot to make a managed climb/descent.

**To Reproduce**

1. Takeoff/Descent.
2. Engage autopilot, managed altitude.
3. happens 9/10 times the aircraft would climb/descent at ~6000fpm rate

**Expected behavior**

**Actual behavior**

Climb/Descent in a more reasonable rate like 1k~2k fpm

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
Yes

Discord username (if different from GitHub):
CongQ#9443

**Comment by SleutelMan** [comment]
There is of course the workaround of using V/S. I would label this more as an improvement than as a bug with A32NX.

**Comment by MisterChocker** [comment]
fixed by game update
