### ISSUE TITLE
Speed suddenly goes to 0 mid climb out causing a stall then suddenly recovers causing an overspeed[BUG]

### ISSUE THREAD

**Issue by TheVivzzy** [flybywiresim/a32nx#969]
**Mod Version**

master

**Describe the bug**

During climb out on multiple occassions, between 15000ft-25000ft, the speed just goes to 0. The aircraft then stalls, going into TOGA and pitching down rapidly. Then 1 or 2 seconds, the speed goes back to the speed at which your climbing and because of the TOGA, it suddenly shows the speed at 400 plus knots causing an overspeed. Some flights this has happened multiple times on climb out.

**To Reproduce**

1. Engage Autopilot on climb out (managed speed, nav mode and either open climb or managed climb)
2. Leave the autopilot to fly the climb out.
3. Somewhere between 15,000ft to 25000ft the bug should occur

**Expected behavior**

Expected behaviour is the speed should maintain the set climb speed in the fmc. 

**Actual behavior**

Speed is managed normally, but then drops to 0 and the aircraft then stalls, going into TOGA and pitching down rapidly. Then 1 or 2 seconds, the speed goes back to the speed at which your climbing and because of the TOGA, it suddenly shows the speed at 400 plus knots causing an overspeed. 

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Has been a problem every since mod was applied.

Is this a problem in the vanilla unmodded game?
Not sure, but has been an issue from when I first downloaded the mod.

Discord username (if different from GitHub):
TheVivzzy #4014

**Comment by stevex77** [comment]
Maybe dumb question - because you experienced this in higher altitudes:
- Did you fly through any clouds when this happened? What was the weather / OAT?
- May it happen because of freezing effects to wings / probes?
- Were anti ice switches on during climb?
Thanks

**Comment by TheVivzzy** [comment]
No dont worry it isn't a dumb question. Yes i can confirm that I had the probe heat, anti ice switches on. I can tell its a bug because i use the pause button to stop the sim for 2/3 secs and then unpause, the airplane recovers and then continues flying normally. I am assuming if it was icing then the airplane should stall completely and not recover and the speed wouldn't overspeed to 350/400 knots. Feel free to correct me if i am wrong about this?

**Comment by stevex77** [comment]
I'm not an A320 rated pilot, so I'm not routinelly familiar with all the systems and conditions, just PPL / NIGHT / IR / with ATPL frozen currently. :)

Anyway this bird souldn't stall during normal managed climb with anti-ice systems on. :) Then this must be a bug. I'll try to reproduce this on vanilla A32N.

**Comment by jasonn85** [comment]
Was the pitot heat explicitly switched on (as opposed to being on auto by default)? If not, this is probably https://github.com/flybywiresim/a32nx/issues/245

**Comment by TheVivzzy** [comment]
I had it on as I was flying out of geneva late at night and temperature was 6 degrees on the ground. 

I would try to replicate this again deliberately but the Japan update has broken the mod. Once it is fixed, I will grab a few screenshots of my overhead panel when it happens again.

**Comment by Ares1378** [comment]
You must fly with the probe/window heat on its stops this issue from happening. This is a bug from the base aircraft and for some reason does not work in AUTO lights out. Try that and let me know if the problem still persists

**Comment by sepiroth887** [comment]
i had the same effect before the patch (1.8.3) but always after flying through cloud at altitude with probe/engine/wing de-ice off. From outside it would show massive icing (none visible from inside tho) and speed would show 0, AP dives, overspeed, speed recovers rinse repeat. 
AntiIce after this has next to no effect and would prevent any further climb past FL200 or so. 

(This happened on vatsim actually and i was able to divert on FL150 to another airport without the issue happening again)

**Comment by elbryan** [comment]
Are you referring to something like [this](https://www.youtube.com/watch?v=0ijelsPPIDY&feature=youtu.be&t=1324)?
If that's the problem you are facing, then it's icing (it's the pitot that gets clogged with ice and can no longer read the current airspeed)

**Comment by TheVivzzy** [comment]
Yes it is very similar to that video. But I remember having all my anti ices on and probe heat on and it was still doing that. I don't remember seeing any visible ice accumulation on the aircraft or the pitot.
