### ISSUE TITLE
Fuel X Feed

### ISSUE THREAD

**Issue by 2hwk** [flybywiresim/a32nx#97]
ON should be white

From: Eaglepilot [Discord: SM#6029]

**Comment by arvinjarvin** [comment]
Hi

Thanks for taking the time to open this issue.

We will look into this and keep you updated as we resolve the issue.

Arvin

**Comment by AdenFlorian** [comment]
ACTUAL:
![image](https://user-images.githubusercontent.com/3533988/92434561-c1954e80-f165-11ea-8835-458d9c51b2f9.png)

EXPECTED:
Can't find one, anyone got an irl pic of X FEED turned on in a neo?

**Comment by NathanInnes** [comment]
From pics I found online some are different. Some are green and white others are blue and white.
![image](https://user-images.githubusercontent.com/18389085/93730805-2dde6c00-fbc2-11ea-8913-ef4571050b3c.png)

**Comment by lukecologne** [comment]
Closing in favor of #956
