### ISSUE TITLE
[BUG] Overriding ILS frequency in NAV/RAD page causes LOC/GS indicators to not appear

### ISSUE THREAD

**Issue by efortier-95** [flybywiresim/a32nx#975]
**Mod Version**

v0.2.0

**Describe the bug**

When the aircraft navigation is on a flightplan to an airport, and the MCDU is loaded with an ILS approach to a runway with multiple frequencies (e.g., KLGA runway 22, or KDTW 22R/04L), the automatically loaded can sometimes be the wrong one. **This is not the issue**, the issue is that, when you try to manually override the frequency in the MCDU RAD/NAV page, the PFD will show the tuned frequency and identify the navaid but **the LS indicators (g/s and loc) will not appear**. The issue does not occur when no approach is selected in the flightplan (you can tune whichever frequency you want and both will work just fine).

**To Reproduce**

1. Set up a flightplan to KLGA
2. Load an ILS 22 approach
3. Verify that the frequency chosen in the LDA approach localizer
4. Overwrite the localizer frequency with the correct one.
5. Check the PFD to make sure the correct nav ident is displayed
6. Make sure that the LS button is lit
7. Note that the LOC/GS indicators are not appearing.

**Expected behavior**

Localizer/GS indicators appear for the tuned ILS frequency

**Actual behavior**

Localizer/GS indicators do not appear on PFD (not sure about ND ILS display mode)

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Not sure

Is this a problem in the vanilla unmodded game?
Not sure

Discord username (if different from GitHub):
Eefoe#0570

**Comment by MisterChocker** [comment]
fixed by now
