### ISSUE TITLE
[BUG] Route not visible on ND

### ISSUE THREAD

**Issue by AdenFlorian** [flybywiresim/a32nx#976]
related #964
**Mod Version**

master, after all our porting changes were merged.

**Describe the bug**

**To Reproduce**

spawn on runway
add from/to in mcdu
add a SID to the flight plan
look at ND

**Expected behavior**

should see green line with waypoints on ND

**Actual behavior**

no green line, no waypoints, but TOC and TOD seem to be visible?

**Comment by tyler58546** [comment]
Possibly related to this: https://www.reddit.com/r/MicrosoftFlightSim/comments/j282jj/193_vfr_map_and_gps_bug/

**Comment by sepiroth887** [comment]
![image](https://user-images.githubusercontent.com/685754/94637723-2176a500-028d-11eb-93de-2c20d1d29b11.png)
related?

**Comment by AdenFlorian** [comment]
> related?

posibly, i have found that theres an issue with this.instrument being undefined in the flight plan manager because of a missed change from last update. testing a fix now

**Comment by sepiroth887** [comment]
if i didn't hate JS this much i would be more helpful :D sorry golang/java dev at heart, UI + Code make my head spin :) 

I'm digging a bit through A32NX_BaseNDCompass and A32NX_NDCompass to pass some time while this remains unplayable :D
