### ISSUE TITLE
FMC do not load flight plan and do not recognize the ICAO codes to initialization   [BUG]

### ISSUE THREAD

**Issue by Horizonuy709** [flybywiresim/a32nx#978]
**Mod Version**

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by waar19** [comment]
Same bug, flight planing not work

**Comment by lousybyte** [comment]
Can you please follow the template and provide additional details, seemed to work fine from my tests. Make sure you use a clean install of the latest 0.3.1 release.

**Comment by sphectrum** [comment]
Was reproducible before 0.3.1 release. Not reproducible with 0.3.1 for me.

**Comment by Onkelpuh** [comment]
I have the same problem with the current version of MSFS 1.9.3.0 and the current version of FlyByWire 0.3.1
Flight planning created via menu in MSFS, flight started
No flight plan in MCDU and manual entry of xxxx / xxxx in INIT is not accepted / no reaction

![mcdu mit update 1 9 3 0 und Patch community airbus](https://user-images.githubusercontent.com/71586280/94689284-f9d81900-032e-11eb-9749-16c9b15ae24f.png)

**Comment by Superlister97** [comment]
Im having the same Issue. This is really frustrating :(

**Comment by lousybyte** [comment]
Try with the latest master version from [https://github.com/flybywiresim/a32nx/archive/master.zip](https://github.com/flybywiresim/a32nx/archive/master.zip), make sure to delete the A32NX folder and put the new one from the archive (do not just replace on top), also make sure your game is on 1.9.3 version.

**Comment by Onkelpuh** [comment]
current version on  https://github.com/flybywiresim/a32nx   loadet
MSFS version 1.9.3.0
The problem persists, even with the default Airbus without a mod, the same problem exists
MSFS has just been completely reinstalled, the error persists

**Comment by lousybyte** [comment]
Have you tried disabling multiplayer, AI traffic, and ground AI? From what I gathered there are still some issues from last patch that could affect some systems.

**Comment by Horizonuy709** [comment]
Yes, the problem is fixed,  but now do not show line waypoints route flight plan in the ND.
--
Enviado desde la aplicación myMail para Android miércoles, 30 septiembre 2020, 03:35p. m. -03:00 de lousybyte  notifications@github.com :

**Comment by apolinski** [comment]
I'm not seeing this problem. The FMC is working as expected for me.

**Comment by Onkelpuh** [comment]
thanks Asobo for the great patch 1.9.3.0 .... grrrrrrrrrrr
if I completely turn off the AI, turn off live weather, deactivate multiplayer and set the traffic at the airports completely to 0, I can use the A320Neo and also enter a flight plan, manually or via the flight planner and then fly super
it is a real progress that you are not allowed to use anything to be able to fly

**Comment by Horizonuy709** [comment]
Agree 100,%, like a yoke!!
-Enviado desde la aplicación myMail para Android jueves, 01 octubre 2020, 00:29p. m. -03:00 de Onkelpuh  notifications@github.com :

**Comment by lovefs2020hatethebugs** [comment]
So happy to see I`m not the only one with this problem. For me, turning off AI, traffic etc. didnt help at all so I´m basically screwed right now. 
My problem is exactly the same: MCDU/ init not reacting to my icao codes. Tried the newest master, the previous release, reinstalled FS. Nothing helped.

**Comment by lovefs2020hatethebugs** [comment]
*Possible Solution*

Guys, you might want to check if you have a cockpit FPS mod installed. I had the  highonsnow one installed and after deinstalling it, the problem was solved. We have a glass display refresh option now anyways. Cheers

**Comment by MisterChocker** [comment]
not following template
