### ISSUE TITLE
[BUG] Lights bleed into the cockpit

### ISSUE THREAD

**Issue by starvingjavi** [flybywiresim/a32nx#979]
**Mod Version**
1.9.3.0 adapted master

**Describe the bug**
When taking off and retracting gear the lights bleed into the cockpit

**To Reproduce**

1. Launch on any airport at night and set up the airplane for take off.
2. Turn on LDG lights, taxi lights to TO, runway turnoff lights on
3. Take off and gear up

**Expected behavior**
No lights should bleed into the cockpit

**Actual behavior**
Lights bleed into the cockpit

Was this working before/when did the issue start occurring?
It was working on previous patch

Discord username (if different from GitHub): Javi#2557

**Comment by nobodyn0se** [comment]
The default files must've overridden the mod files after update. Should be fixed when all the changes are ported over.

**Comment by NathanInnes** [comment]
Unable to replicate anymore. Changes must have fixed it now.
