### ISSUE TITLE
[BUG] start and end tag in DOOR_PANEL section of a320_neo_interior.xml

### ISSUE THREAD

**Issue by Wombii** [flybywiresim/a32nx#981]
**Mod Version**
master

**Describe the bug**
In A320_NEO_INTERIOR.xml lines 2605 and 2609 in the section for Component ID DOOR_PANEL:
Line starts with <Node_ID> but ends with </ANIM_NAME>

<Node_ID>SWITCH_DOORPANEL_LOCK</ANIM_NAME>
<Node_ID>PUSH_DOORPANEL_OPEN</ANIM_NAME>

**To Reproduce**

**Expected behavior**

**Actual behavior**

**References**

SimObjects\AirPlanes\Asobo_A320_NEO\model\A320_NEO_INTERIOR.xml

  ```
<Component ID="DOOR_PANEL">
		<UseTemplate Name="A32NX_SWITCH_DOORPANEL_LOCK">
			<Node_ID>SWITCH_DOORPANEL_LOCK</ANIM_NAME>
			<INVERT_ANIM>1</INVERT_ANIM>
		</UseTemplate>
		<UseTemplate Name="A32NX_PUSH_DOORPANEL_OPEN">
			<Node_ID>PUSH_DOORPANEL_OPEN</ANIM_NAME>
		</UseTemplate>
  </Component>
```

**Additional context**
I'm not very familiar with xml, but I assume a different start and end tag can cause issues.

Is this a problem in the vanilla unmodded game?
No

**Comment by SeanHanway** [comment]
Changing the closing tags to </Node_ID> doesn't have any impact or improvement to functionality for me, haven't testing changing the opening to <ANIM_NAME>
Does anyone know who developed this and if they were trying to make both NODE_IDand ANIM_NAME be assigned this value in one line or something?

**Comment by MisterChocker** [comment]
closing now
