### ISSUE TITLE
[BUG] Pitch too high 

### ISSUE THREAD

**Issue by EDKL1980** [flybywiresim/a32nx#984]
seems that the pitch is now slightly high on normal cruise flight level with normal speed abs light wind.

With Mach .78 the pitch was > than 10%

![1003E2B3-CC2E-41EE-88E0-C05801772D1B](https://user-images.githubusercontent.com/72131688/94669052-0d748700-0311-11eb-965e-db907410e4d4.jpeg)
![00A9080F-797A-49A3-836F-94FEA5DE4758](https://user-images.githubusercontent.com/72131688/94669066-11a0a480-0311-11eb-8f3f-42689242eb57.jpeg)
![314EDA4C-E1EF-4E0A-8249-D2DFF737FF51](https://user-images.githubusercontent.com/72131688/94669082-149b9500-0311-11eb-96bc-391733de718a.jpeg)
![A657F09D-CC0E-4A95-82A5-3D31A2540E06](https://user-images.githubusercontent.com/72131688/94669089-16fdef00-0311-11eb-9a28-f3888918473d.jpeg)

**Mod Version**

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by dmajestic80** [comment]
I have noticed this too especially when on approach and established on the ILS. I even tested with a very light aircraft (~3000kg fuel and 0 pax) The nose pitch is unusually high around 7 degrees. Removed the mod and didn't have this issue.

**Comment by PCGamesF1Tech** [comment]
Wind should be irrelevant, you are just moving inside the airmass (calm or 100kt makes no difference, just changes your ground speed, depending on direction).
Pitch should be around 2.5° nose up and power around 80% (depending on weight)

**Comment by EDKL1980** [comment]
Weight was balanced with loading 90% and around 10 tons of fuel balanced left and right with empty Center

**Comment by PCGamesF1Tech** [comment]
If within (MAC) limits no problem.
Light weight: 2.5°, some power
Medium weight: 2.5°, more power
Heavy weight: 2.5°, even more power

**Comment by EDKL1980** [comment]
Also experienced this issue during final approach. Flaps full and 140-145kts the pitch is too high. I always need to speed up to 150-160 which is definitively too fast for the final with flaps full

**Comment by apolinski** [comment]
I'm seeing the opposite. Pitch (really AoA) was too high pre 0.3.1 but now seems fine.  Cruising at FL350 at M0.78 I had an AoA of about 4 degrees, which is fine.  At lower altitudes the AoA is even lower.  The old fix of increasing the cruise_lift_scalar parameter now creates a huge over-correction. On my first flight in 0.3.1 with the old fix my AoA was negative 5-8 degrees during cruise, definitely weird looking.  Whatever 0.3.1 (or the 1.9.3 patch) did has improved things a lot.
