### ISSUE TITLE
[BUG] Nav frequencies and squawk codes on console disappear with changes in view.

### ISSUE THREAD

**Issue by johnwillimas** [flybywiresim/a32nx#986]
**Mod Version**

Master

**Describe the bug**

Display of numbers for frequencies and ATC squawk code seems related to zoom and orientation of view..... (Post 1.9.3 patch)
These two images only differ by zoom in or out by one notch on the keyboard. Numbers also disappear if view directly overhead of the gauges.

**To Reproduce**

1. Ctrl+1 cockpit view with engines started and electrics on etc.
2. Ctrl+6 to view console panel. 
3. Zoom in or change view with right mouse button to vertical : does not happen 100% of the time.

**Expected behavior**

Radio frequencies and squawk code should be displayed irrespective of zoom level and angle.

**Actual behavior**

Radio frequencies and squawk code are not displayed irrespective of zoom level and angle.

**References**

![no numbers](https://user-images.githubusercontent.com/38857762/94667258-7efb0800-0306-11eb-82ee-83a88d68e8b8.png)
![numbers](https://user-images.githubusercontent.com/38857762/94667263-815d6200-0306-11eb-8aa5-9b4edb28e8e5.png)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Yes. ( I will also report on Zen Desk)

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment]
Fixed by #2277
