### ISSUE TITLE
[BUG] Batteries will not turn on at all cold and dark - SOLVED

### ISSUE THREAD

**Issue by triggerhappy2cu** [flybywiresim/a32nx#987]
**Mod Version**
latest master branch

**Describe the bug**
Spawning into YMML cold and dark. No matter which way i try the batteries will not turn on.

**To Reproduce**

1. Spawn YMML at any gate
2. Try turn on the batteries 
3.

**Expected behavior**
They turn on

**Actual behavior**
Nothing happens

**Additional context**
I have tried ground power first and tried multiple resets etc, pc reboot.

Was this working before/when did the issue start occurring?
It's been on and off since the first be MSFX2020 patch

Is this a problem in the vanilla unmodded game?
Not Sure

Discord username (if different from GitHub):

**Comment by NathanInnes** [comment]
Please make sure you're on the latest master. I just spawned C&D with the latest and can't replicate your problem.

**Comment by yoplebop** [comment]
I have the same issue bsfore the last Japan-MSFS2020 update.
Since I strated A flight on the runway once (fully ready for take off) I cant start a flight at a gate  Cold & Dark,. Batts $ Ext Pwr no working. 
(I can still start a flight on the Runway) 
So it seems

**Comment by triggerhappy2cu** [comment]
i am on the latest master, i can start on the runway but not cold and dark

**Comment by triggerhappy2cu** [comment]
same as above^

**Comment by triggerhappy2cu** [comment]
after uninstalling this mod i still have the same problem.. dam.. 
@NathanInnes is there anything i can do to provide more info?

**Comment by triggerhappy2cu** [comment]
Uninstall the mega liveries pack. Everything works again! thanks @NathanInnes for trying to help so quickly

**Comment by yoplebop** [comment]
TNX!
Best wishes בברכה
*Gil Segal גיל סגל*
