### ISSUE TITLE
[BUG] Nose light blinking after take off

### ISSUE THREAD

**Issue by Rrobban** [flybywiresim/a32nx#988]
**Mod Version**
master

**Describe the bug**
After takeoff while climbing the nose light will start blinking even though its off. It lights up the cockpit and outside

**To Reproduce**
1. Take off
2.
3.

**Expected behavior**

**Actual behavior**
Nose light blinks with a interval of 10 to 60 seconds

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by elbryan** [comment]
Is this the same as https://github.com/flybywiresim/a32nx/issues/979? Perhaps it's already fixed in master branch.

**Comment by NathanInnes** [comment]
On latest master I can't replicate this issue.

**Comment by Rrobban** [comment]
Looks like i have some lightning close to me. It does look sometimes like the lightning strike would be inside the plane. Sorry if this is not a bug
