### ISSUE TITLE
PFD/ND Display Swap

### ISSUE THREAD

**Issue by 2hwk** [flybywiresim/a32nx#99]
PFD/ND button should swap display position

From: Eaglepilot [SM#6029]

**Comment by AdenFlorian** [comment]
can you take a picture of the button?

**Comment by mikecbr** [comment]
@AdenFlorian   
![image](https://user-images.githubusercontent.com/74787268/100467307-88200f80-30d2-11eb-8e90-55eab34939a3.png)

**Comment by BlueberryKing** [comment]
Part of https://github.com/flybywiresim/a32nx/issues/1921.
