### ISSUE TITLE
Are the climb and crz speeds correct?

### ISSUE THREAD

**Issue by August78** [flybywiresim/a32nx#991]
She climbs at 320 kts and then at cruise she slows down to 280. Are these speeds correct? For me it looks backwards hehe... :)

**Comment by NathanInnes** [comment]
Please respect the template for bug reports. If you have a general question then please ask it on discord instead of GitHub. 

The ottopilot and MCDU speeds are not working correctly to answer your question. It's a WIP.

**Comment by PCGamesF1Tech** [comment]
In cruise at higher altitudes you are using Mach, not indicated air speed (IAS).
With higher altitude the IAS decreases with constant Mach

**Comment by 2hwk** [comment]
Closed for not respecting issue template.
