### ISSUE TITLE
A320nx STARTING PROBLEM

### ISSUE THREAD

**Issue by benjack57** [flybywiresim/a32nx#993]
Hello
Hello
I installed the last version of A320NX 3.1 and I have a problem the plane does not load and MFS2020 stops and I am returned to the desktop
I have an error which appears from microsoft net framework the problem only concerns A320NX with other planes no problem

**Comment by lousybyte** [comment]
Please follow the issue template. We recommend disabling multiplayer, AI traffic, and ground AI.

**Comment by NathanInnes** [comment]
As said above, please follow the issue template. I will close this issue for now, keep up to date with this issue #1001
