### ISSUE TITLE
[BUG] First waypoint is skipped?

### ISSUE THREAD

**Issue by ErikNL80** [flybywiresim/a32nx#994]
**Mod Version**

Master

**Describe the bug**

I have done 2 flights in 1.9.3 and it seems that the first waypoint of the flightplan is skipped after take-off.

**To Reproduce**

1. Create a flightplan, start at a gate
2. Make sure you create an IFR flightplan and select the starting runway + a departure
3. Now conduct the flight and put heading to managed before the first waypoint

**Expected behavior**

I would expect the flightplan to follow the route to the first waypoint

**Actual behavior**

The plane skips the first waypoint and directly goes to the second one. 

**References**

**Additional context**

Was this working before/when did the issue start occurring?
First noticed this in 1.9.3
Is this a problem in the vanilla unmodded game?
Haven't tested this yet, only did some flights with the A320nx master.

Discord username (if different from GitHub):

**Comment by ErikNL80** [comment]
Here is an example, departure from Alesund. First waypoint is followed, the the plane skips the next one:

![Naamloos](https://user-images.githubusercontent.com/71258178/94713509-2ac64700-034b-11eb-9f0e-c831ed4ecd2a.png)

**Comment by AlphaMA1** [comment]
It is a bug in the base aircraft in 1.9.3.0.
I have encountered this with the unmodded A320 first time after updating to 1.9.3.0 yesterday.
Sometimes the AP skips the first (several?) waypoints, which to me showed as on some flights it skipping through (parts of) the selected departure procedure.

**Comment by 2hwk** [comment]
Seems ok in 1.12.13, closed
