### ISSUE TITLE
[BUG] FCU HDG BUG stuck 

### ISSUE THREAD

**Issue by tareksabet** [flybywiresim/a32nx#996]
**Mod Version**

master latest version

**Describe the bug**

can't go on selected heading 

**To Reproduce**

1.start in cold & Dark 
2. try to set the HDG Bug to selected 
3.

**Expected behavior**

it should go in selected mode 

**Actual behavior**

it stays in managed mode 

**References**

![Desktop Screenshot 2020 09 30 - 16 24 18 32](https://user-images.githubusercontent.com/70240330/94698612-c51d8f00-0339-11eb-8eda-6ae1010a8e67.png)

**Additional context**

Was this working before/when did the issue start occurring?
it was working before 
Is this a problem in the vanilla unmodded game?
didn't tested it on the vanilla

Discord username (if different from GitHub):

**Comment by AdenFlorian** [comment]
@tareksabet did you mean to close this? I've experienced this issue too on and off, need to know if it is wrong or not.
