### ISSUE TITLE
[BUG] PFD and other flight-management systems do not activate

### ISSUE THREAD

**Issue by pilotpuffin** [flybywiresim/a32nx#998]
**Mod Version**
0.1.51.  Latest FS version (Japan update).  Also have liveries megapack.

**Describe the bug**
PFD/FMS/EICAS does not initiate self-test or activate; ADIRS will not align

**To Reproduce**

1.  Load aircraft.
2.  Attempt to follow checklist to start.
3.  Even after engaging batteries and ground power, no response from PFD/FMS/EICAS or ADIRS.

(I also tried loading the aircraft on the runway.  It loaded with engines active but no PFD, etc.)

**Expected behavior**
PFD, etc., should initiate self-test and then power on.  ADIRS should align.  This worked perfectly yesterday, before FS update.

**Actual behavior**
As described _supra_.  After reading other issues, I tried activating ground power before batteries, but same result.

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Yes, this just began today following latest FS update.

Is this a problem in the vanilla unmodded game?

Unclear, but I suppose something in new FS update is causing issue.

**Comment by Dgh1974** [comment]
Exactly the same issue .. No buttons working a t all ( overhead )

Starting on runway the screens are on and can do a flight but lots is not working (LS button / no restraints / no frequencies visible in radio / squawk code nor visible etc etc etc )

**Comment by lousybyte** [comment]
We recommend disabling multiplayer, AI traffic, and ground AI, there's a known issue since the previous update in the base game.
Also the only supported stable release for 1.9.3 is 0.3.1 as mentioned above.

**Comment by Dgh1974** [comment]
Hi all 

Did some tests ... with all traffic on it sometimes it stays cold and dark.

Then when pressing escape ... SELLECT  RESTART .... it works ( with all traffic on at 30% ). 

I now tested this 7 times ... on 5 different times i also restarted fs2020 ... 7 times it worked

Can anyone test this also ?
